### PR TITLE
Move WaitForService() into e2eservice

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

The function is only for e2e service test, it is not necessary to keep the function in e2e test core framework.

**Which issue(s) this PR fixes**:

Ref: #77095

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks, feel free to ping me again once all tests passed.
/approve

**Comment by oomichi** [comment]
This makes circular dependency between e2enetwork and e2eservice packages like
```
     //test/e2e_node:e2e_node.test_binary
    //test/e2e_node:gen_e2e_node.test
    //test/e2e_node:go_default_test
    //test/e2e_node:_go_default_test-cgo
    //test/e2e/common:go_default_library
.-> //test/e2e/framework/network:go_default_library
|   //test/e2e/framework/service:go_default_library
`-- //test/e2e/framework/network:go_default_library 
```
We need to remove dependency from e2eservice at first.

/cc @oomichi

**Comment by oomichi** [comment]
Currently e2enetwork package calls `WaitForService()` to wait for a service which is created in the package for setting up test environments. It seems hard to separate the function from e2enetwork package.
So at this time, it is good enough to move this function into e2enetwork instead of e2eservice to collect related functions into the package.

**Comment by YuikoTakada** [comment]
@oomichi thank you for your comments. I will fix it.

**Comment by tanjunchen** [comment]
ci fails ...

**Comment by oomichi** [comment]
@YuikoTakada 
Unfortunately we need to rebase this based on the latest master as the error:
```
$ git merge --no-ff 9181b7b5e9211afab73a276768502f9c952e684a
Auto-merging test/e2e/kubectl/kubectl.go
CONFLICT (content): Merge conflict in test/e2e/kubectl/kubectl.go
Auto-merging test/e2e/framework/util.go
Automatic merge failed; fix conflicts and then commit the result.
# Error: exit status 1
```

**Comment by YuikoTakada** [comment]
@oomichi thanks, I will fix it.

**Comment by oomichi** [comment]
It is necessary to run `./hack/update-bazel.sh` for updating BUILD files.

**Comment by oomichi** [comment]
Thanks for doing this.
/retest
/priority backlog
/lgtm

**Comment by tanjunchen** [comment]
thanks
/lgtm

**Pull request merged**
