### PR TITLE
Automated cherry pick of #77165: Increase maxMsgSize for dockershim

### PR DESCRIPTION
**Pull request by bhks**
Cherry pick of #77165 on release-1.13.

#77165: Increase maxMsgSize for dockershim

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

I think this change is technically correct, so lgtm in that sense.

However, I don't _believe_ there will be any more releases for 1.13, unless I'm misremembering? 

Iirc, @odinuge you had some insights into the schedule last time? Mind linking where you found that info.

In other words, my lgtm is contingent upon 1.13 still being open for cherry-picks :)

**Comment by odinuge** [comment]
Hi,

1.13.12 was the last patch release for 1.13, so I guess we can close this.

The release info can be found in the `sig-release` repo:
https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by odinuge** [comment]
Closing ref. comment above, since we no longer intend to release a new patch version of v1.13.

/close

**Pull request closed without merging**
