### PR TITLE
fix hack/lib/golang.sh for bash 4.3

### LINKED ISSUE #77521: build/release.sh (hack/lib/golang.sh) requires minimum bash v4.4
**What happened**:  building Kubernetes release and it failed due to a variable not being set ([with `set -u` enabled](https://github.com/kubernetes/kubernetes/blob/caf9d94d697ce327e0c1c3dee71a1f06a6fc918e/build/release.sh#L25)). It appears a [recent commit](https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b) does not function as expected on `bash v4.3` (used Ubuntu 16). Additional details will be provided in comment below
```
kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable
```

**What you expected to happen**: successful build of Kuberentes release or documented minimum supported OS releases (i.e., bash versions)

**How to reproduce it (as minimally and precisely as possible)**: using Ubuntu 16 (`bash v4.3`), run [build/release.sh] using `release-1.14`, `v1.15.0-alpha.2` or `master` (containing https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b or subsequent cherry pick)

**Anything else we need to know?**:  It appears the issue is with how `bash v4.3` and `bash v4.4` create `readonly` variables, where I believe `v4.3` does not create the variables with the expected scope (created using `local` scope versus `global` scope). This creates a minimum supported OS version when running `build/release.sh` from the best I can tell.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.15.0-alpha.2` [`release-1.14`](https://github.com/kubernetes/kubernetes/commit/ffa6160e087d699282daca15085f9cb968240b80)
- Cloud provider or hardware configuration:  N/A
- OS (e.g: `cat /etc/os-release`):
```
release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):  `Linux armada-lb-build 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:  `build/release.sh`
- Network plugin and version (if this is a network-related bug):  N/A
- Others:

/sig release

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR fixes compatibiltiy issue with bash version 4.3 for script hack/lib/golang.sh, to solve the scope issue of `readonly` variables in both version 4.3 and 4.4, required variables are declared using `declare -g`

**Which issue(s) this PR fixes**:

Fixes #77521

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
w00t interesting! thanks for taking this on @adisky

**Comment by adisky** [comment]
@dims Tried fixing the scope resolution problem for readonly variable for bash version 4.3, tested the above changes on bash 4.4, trying to get it tested on 4.3

**Comment by adisky** [comment]
cc @cjschaef @aojea

**Comment by aojea** [comment]
Thanks @adisky , it's working for me now

**Comment by tpepper** [comment]
This has broken MacOS build:

```
/Users/tpepper/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh: line 166: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
!!! [0517 10:55:19] Call tree:
!!! [0517 10:55:19]  1: /Users/tpepper/src/github.com/kubernetes/kubernetes/hack/lib/init.sh:55 source(...)
!!! [0517 10:55:19]  2: build/../build/common.sh:37 source(...)
!!! [0517 10:55:19]  3: build/release.sh:29 source(...)
make: *** [quick-release] Error 1
```

**Comment by aojea** [comment]
This discussion seems related https://discuss.kubernetes.io/t/help-wanted-role-build-and-shell-cleanup/6064/10 , is it failing with the default bash version on Mac? version 3?

**Pull request merged**
