### PR TITLE
optimize test code of defer

### PR DESCRIPTION
**Pull request by wangkeqiang123**
**What this PR does / why we need it**:
there has some defer func ,I think maybe modify better,thanks!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/ok-to-test

**Comment by wangkeqiang123** [comment]
retest

**Comment by wangkeqiang123** [comment]
/assign @janetkuo
/assign @mikedanese
/assign @dixudx
pls help to review my PR when you see it, thanks a lot.

**Comment by dixudx** [comment]
@wangkeqiang123  Please squash your commits. Thanks.

**Pull request closed without merging**
