### PR TITLE
add err return

### PR DESCRIPTION
**Pull request by lojies**
Since err can be returned by previous code,  add err return.

### CODE REVIEW

**Comment by jfrazelle** [comment]
looks good to me

**Comment by jfrazelle** [comment]
@k8s-bot test this issue #28423

**Comment by jfrazelle** [comment]
@k8s-bot test this issue #27663

**Comment by lojies** [comment]
@jfrazelle can readd lgtm to this.

**Comment by lojies** [comment]
@jfrazelle @janetkuo

**Comment by janetkuo** [comment]
@lojies please squash this into one commit and we'll reapply the tag

**Comment by lojies** [comment]
@janetkuo i do this.

**Comment by lojies** [comment]
@janetkuo

**Pull request merged**
