### PR TITLE
Experiment to test endpoint access via proxy vs. master

### PR DESCRIPTION
**Pull request by satnam6502**
Two programs written to look for any discrepancies when accessing an application endpoint via the service proxy from outside the cluster vs. via the service inside the cluster.
If this is of any value it could be turned into a proper soak test or e2e test to avoid bit-rot.
@quinton-hoole @thockin @wojtek-t

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Yes, lets get this merged as soon as we have a green on shippable and Jenkins e2e.  I don't have time to do a proper review right now, but lets get it in first and review later, give that it's not connected to anything else at the moment.

**Comment by quinton-hoole** [comment]
Perhaps @mikedanese can review when he has a moment?

**Comment by satnam6502** [comment]
Actually, I'd like to change these tests to create and destroy their own Elasticsearch services and RCs rather than using the ones running in the cluster -- I think this more accurately reflects the scenario we are trying to debug. I will close this PR for now and then re-open when I am ready again.

**Comment by thockin** [comment]
Does it need to be as complex as ES ?  Would serve_hostname suffice?

**Comment by satnam6502** [comment]
OK. I will try serve_hostnames

**Pull request closed without merging**
