### PR TITLE
Fix some syntax errors under the staging/src/k8s.io/client-go/rest/ folder

### PR DESCRIPTION
**Pull request by ldsdsy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
For the overall rigour of the code
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Thank you！
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by lojies — COMMENTED** [review]
/lgtm

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by pacoxu** [comment]
Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Comment by ldsdsy** [comment]
Thanks for the advice, I have read the trivial edits policy and I am sure I have fixed all the syntax errors I could find under the staging/src/k8s.io/client-go/rest/ folder. I've just joined the kubernetes community and wanted to verify my workflow by submitting a few simple pr, after this one I won't be submitting typo pr again.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm
assign @caesarxuchao

**Pull request merged**
