### PR TITLE
fix typos  in /test/e2e_node

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @vishh

**Comment by nikhita** [comment]
The job is broken so retesting won't help: https://github.com/kubernetes/kubernetes/issues/83086 :(

Adding hold so that @fejta-bot won't automatically retest. Please feel free to remove the hold once the above issue has been closed (and the job is fixed).
/hold

**Pull request merged**
