### PR TITLE
Remove duplicate package import in empty_dir_test.go

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Remove duplicate package import.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rata** [comment]
If test pass (i.e. no missing line change to remove this include) it /lgtm

**Comment by rata** [comment]
@pandaamanda thanks for the PR!

@saad-ali assigning to you as that is what the bot says. But let me know if I should do anything different regarding the triage label (I did nothing with that). Thanks!

/assign @saad-ali

**Comment by pandaamanda** [comment]
PTAL  /assign @saad-ali

**Comment by pandaamanda** [comment]
/assign @thockin 
kindly ping for pr long time stuck.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
