### PR TITLE
Some fixes to tests to support large clusters

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please, github issue: #25845

**Comment by wojtek-t** [comment]
@zmerlynn - FYI, this is fixing one test that is actually scheduling a pod on all nodes and checking network on it; however, if we don't have route for this node, this will not work; this test is fixing it

**Comment by zmerlynn** [comment]
Why are we even starting tests before the nodes are actually route-ready? Shouldn't `validate-cluster.sh` block this?

**Comment by gmarek** [comment]
We discussed this - it has pros and cons, but we believe that preventing the scheduler from putting pods on those Nodes are good enough for most use cases (some tests may need to be rewritten though).

**Comment by wojtek-t** [comment]
We can add this check but:
1. what we are doing after this change is technically correct
2. if we add it, that would mean that to start 2000-node cluster we need ~1h more (to create routes). This is pretty expensive.

I think we may consider adding this check, but no in 1.3 timeframe.

**Pull request merged**
