### PR TITLE
fix typo "amd"

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:

 /kind cleanup

**What this PR does / why we need it**:
I search the typo error "amd" and fix it in two files
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by idealhack — APPROVED** [review]
/lgtm

**Comment by qingsenLi** [comment]
/cc @idealhack @sttts 
thanks

**Review by idealhack — APPROVED** [review]

**Comment by qingsenLi** [comment]
/assign @deads2k
Needs approved label.thanks

**Comment by qingsenLi** [comment]
/cc @lavalamp @sttts @deads2k 
Needs approval label,thanks

**Comment by qingsenLi** [comment]
/assign @sttts 
for approval

**Comment by qingsenLi** [comment]
/assign @smarterclayton @liggitt 
for approval,thanks

**Pull request merged**
