### PR TITLE
kube-up: ensure tokens file is correct on upgrades/downgrades

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://github.com/kubernetes/kubernetes/issues/43668

1.5 [hard-codes authorization rules](https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/gce/gci/configure-helper.sh#L915-L920), but if the `known_tokens.csv` file already exists, it [does not ensure it works with those authorization rules](https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/gce/gci/configure-helper.sh#L264).

```release-note
kube-up (with gce/gci and gce/coreos providers) now ensures the authentication token file contains correct tokens for the control plane components, even if the file already exists (ensures upgrades and downgrades work successfully)
```

This issue was fixed in 1.6 for the gce and coreos providers. This PR picks those fixes for the control plane elements from these commits:
* https://github.com/kubernetes/kubernetes/commit/968b0b30cfed1056c79bf51b6ca71e3998d4fb05
* https://github.com/kubernetes/kubernetes/commit/d94bb2677686165232e3c5039c6e59b650fbaf05

### CODE REVIEW

**Comment by liggitt** [comment]
@euank @yifan-gu @ethernetdan PTAL at the coreos change

@cjcullen @mikedanese PTAL at the gci change

cc @saad-ali @mwielgus @enisoc for v1.5.6

**Comment by cjcullen** [comment]
change LGTM, as long as this is a kosher way to fix downgrades...

**Comment by liggitt** [comment]
It's one of several upgrade/downgrade related changes that will be in v1.5.6

**Comment by yifan-gu** [comment]
Changes lgtm, but @ethernetdan said he has problems verifying the PR on coreos. Will be investigating.

**Comment by liggitt** [comment]
After many tears, was able to test an upgrade/downgrade using this fix.

1. Get the CI build and binaries:
```
mkdir 1.5.6
cd 1.5.6
curl https://storage.googleapis.com/kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.5.5-beta.0.31+367f71ca624fd9/kubernetes.tar.gz -o kubernetes-1.5.6.tar.gz
tar -xvf kubernetes-1.5.6.tar.gz
cd kubernetes
export KUBERNETES_RELEASE_URL=https://storage.googleapis.com/kubernetes-release-pull/ci/pull-kubernetes-e2e-gce
./cluster/get-kube-binaries.sh
```

2. when running the downgrade, run from the 1.5.6/kubernetes folder, and use the local binaries (`./cluster/gce/upgrade.sh -M -l`)

After downgrading to "1.5.6", verified tokens file was as expected:
```
/etc/srv/kubernetes $ more known_tokens.csv 
bogaWNWVPndo12xSzjhQ7EapW9g2WIi0,system:kube-controller-manager,uid:system:kube-controller-manager
ApBlGnenHX8pP6nTheKTURTUlFsoLCdc,system:kube-scheduler,uid:system:kube-scheduler
OQn1MXip8ypzwY0g2bYKgrddqFQqjHMW,admin,admin
k9rxakXB4cmOmnFXXA3TW5F9IlQVM7Ag,kubelet,kubelet
rSTbu3x50MnJK21zk0x5kThVgsBLj1TG,kube_proxy,kube_proxy
```

However, HEAD of release-1.5 contains the issue https://github.com/kubernetes/kubernetes/issues/42199 fixed by https://github.com/kubernetes/kubernetes/pull/42853, the cherry-pick for which (https://github.com/kubernetes/kubernetes/pull/43718) has not merged yet

**Comment by mwielgus** [comment]
/lgtm
applying lgtm per @cjcullen (and thumbs-up from @calebamiles on slack)

**Comment by liggitt** [comment]
successfully upgraded v1.5.5 -> ci/latest-1.6 -> ci/latest-1.5 and ensured kube-proxy and kube-dns were functioning correctly after upgrade and downgrade, and tokens file contained correct control plane users after each step

**Pull request merged**
