### PR TITLE
[local-up-cluster] fail fast if kubelet start failed

### LINKED ISSUE #36832: local-up-cluster should fail if kubelet dies
Problem

Local-up-cluster will start normally even if the hyperkube kubelet startup command fails.

Solution 

Ensure local-up-cluster fail-fast if things are broke or if individual daemons dont start

### PR DESCRIPTION
**Pull request by jayunit100**
Fixes #36832

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36915)

### CODE REVIEW

**Comment by jayunit100** [comment]
I think this should do what we need it to, breifly tested

**Comment by sjug** [comment]
Can you please follow the style guide for if statements, looks basic enough otherwise, should work. Will try and test to verify.

**Comment by jayunit100** [comment]
Yeah figured log cat was self explanatory , I can expand the line didn't wanna make too much real estate for a simple check but I agree it's a little long

**Comment by feiskyer** [comment]
@jayunit100 Cool. Encounter the same problem, could you fix bash style?

**Comment by jbeda** [comment]
Agree on bash style.  Also, when kubelet fails, might also output that to stderr with a message that kubelet failed.

**Comment by timothysc** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
