### PR TITLE
kubelet: drop bitArray implementation

### PR DESCRIPTION
**Pull request by giuseppe**
drop bitArray implementation and use the bitmap implementation from
k8s.io/kubernetes/pkg/registry/core/service/allocator.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

use the bitmap implementation that exists for k8s.io/kubernetes/pkg/registry/core/service/allocator instead of definiting a similar type with the same functionalities.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by endocrimes** [comment]
/triage accepted

/priority important-longterm
(code cleanup)

generally speaking lgtm after a first pass

**Comment by giuseppe** [comment]
@thockin PTAL :)

**Comment by aojea** [comment]
/assign @thockin 

I have doubts if it is good to create this dependency :thinking:

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
