### PR TITLE
Reduce the minwidth of the cli table printer

### PR DESCRIPTION
**Pull request by smarterclayton**
For a few columns we want to have a smaller width and 10 is excessive. The example is CPU and memory for nodes.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-bugs @soltysh 

```
$ kubectl get node
AGE           LABELS
9s            blah
```

becomes

```
$ kubectl get node
AGE   LABELS
9s    blah
```

**Review by soltysh — APPROVED** [review]
/lgtm

Although you did open a pandora box with tests that rely on those outputs.

**Comment by smarterclayton** [comment]
yeah, will fix the tests.  I just want to get this slimmed down so I have more wiggle room in broad tables to add useful data.

**Review by juanvallejo — APPROVED** [review]

**Review by dixudx — APPROVED** [review]
/lgtm

**Pull request merged**
