### PR TITLE
Update node pages to v1beta3 in web ui

### PR DESCRIPTION
**Pull request by bcbroussard**
Depends on #8304 and https://github.com/GoogleCloudPlatform/kubernetes/pull/8332

~~After https://github.com/GoogleCloudPlatform/kubernetes/pull/8332 lands I'll need do a quick update to one page for v1beta3 support.~~
Update: the changes have been made.

cc @jackgr @lavalamp @bgrant0607 @brendandburns

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM. Thanks!

**Comment by caesarxuchao** [comment]
why are we receiving this message? @ixdy

**Comment by dchen1107** [comment]
rebase please

**Comment by bcbroussard** [comment]
@dchen1107 will rebase once https://github.com/GoogleCloudPlatform/kubernetes/pull/8548 goes in

**Comment by thockin** [comment]
rebase please

**Comment by thockin** [comment]
needs rebase

**Comment by bcbroussard** [comment]
@thockin rebased

**Pull request merged**
