### PR TITLE
GCE cloud should delete return NotFound error

### LINKED ISSUE #54717: GCECloud: Should Delete return NotFound error
Some Delete methods in GCECloud return resource NotFound errors while others mask it.

For ex: DeleteHealthCheck returns NotFound: https://github.com/kubernetes/kubernetes/blob/5cb1cccd403d9d9b9c24d04ee7092e1064523afa/pkg/cloudprovider/providers/gce/gce_healthchecks.go#L68 while DeleteTargetHttpProxy masks it:https://github.com/kubernetes/kubernetes/blob/5cb1cccd403d9d9b9c24d04ee7092e1064523afa/pkg/cloudprovider/providers/gce/gce_targetproxy.go#L58

I think we should be consistent in either all of them should return NotFound or none of them

cc @csbell @bowei @nicksardo @freehan @G-Harmon thoughts?

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
consistent it with kubernetes/pkg/cloudprovider/providers/gce/gce_healthchecks.go
should delete return NotFound
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54717 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
```
W1028 17:53:28.896] # k8s.io/kubernetes/pkg/cloudprovider/providers/gce
W1028 17:53:28.897] pkg/cloudprovider/providers/gce/gce_targetproxy.go:20:2: imported and not used: "net/http"
```

**Comment by stewart-yu** [comment]
BTW, squah the commit. @jianglingxia

**Comment by jianglingxia** [comment]
ok,thanks,I have updated it,for your review again and approve it! @stewart-yu @mikedanese

**Comment by nikhiljindal** [comment]
Thanks for sending the PR @jianglingxia 
I think the cloud provider returning NotFound is better. Callers can choose to mask it if they want.
But lets wait to get resolution on https://github.com/kubernetes/kubernetes/issues/54717.

Also, am not sure if we can just change the cloud provider like this. We risk breaking existing callers that were depending on the cloud provider masking NotFound errors.

**Comment by bowei** [comment]
How was this tested? This is highly likely to break existing controllers that call the method.

**Comment by nikhiljindal** [comment]
@jianglingxia Can you update the PR to fix the callers as well?

**Comment by nicksardo** [comment]
@nikhiljindal Looks like the only callers that need to be updated are in MC.

Ingress-gce:
https://github.com/kubernetes/ingress-gce/blob/f7ed17613fbf9768eaefb6ba676c054de2712862/pkg/loadbalancers/loadbalancers.go#L960
https://github.com/kubernetes/ingress-gce/blob/f7ed17613fbf9768eaefb6ba676c054de2712862/pkg/loadbalancers/loadbalancers.go#L975

**Comment by nicksardo** [comment]
/close
Removed in separate PR during cloudprovider changes

**Pull request closed without merging**
