### PR TITLE
fix(staticcheck): fix static error of package `/pkg/volume/gcepd`

### PR DESCRIPTION
**Pull request by donggangcj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
@donggangcj, thanks for the PR, it looks good overall, however, please fix gofmt issue reported by pull-kubernetes-verify job (click on "Details" and "gofmt" in the test Job report.

**Comment by donggangcj** [comment]
@jsafrane  Thanks! My bad. Done:

**Comment by jsafrane** [comment]
can you please squash the commits? Otherwise lgtm.

**Comment by donggangcj** [comment]
@jsafrane  I have squashed these commit and thanks for your help!

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93136/pull-kubernetes-node-e2e/1283627559145181184 flake is #93210

**Comment by spiffxp** [comment]
/approve
/priority important-longterm
I don't think this increases risk but am not compelled to add this to 1.19 milestone at this time

**Pull request merged**
