### PR TITLE
Vendor skydns

### LINKED ISSUE #9289: We should vendor skyDNS
We build skyDNS and push a container and use that container but we have not vendored skyDNS code.

### PR DESCRIPTION
**Pull request by thockin**
Fixes #9289

Had to jump through a few hoops to make godep happy.

### CODE REVIEW

**Comment by thockin** [comment]
oh hell, this now drags libcontainer into the mess

**Comment by quinton-hoole** [comment]
Assigning to @ArtfulCoder for review when @thockin says it's ready.

**Comment by thockin** [comment]
I think this works now.  I had to do some manual revision control - not sure why.

**Comment by thockin** [comment]
At this point this should wait until after 1.0

**Comment by thockin** [comment]
For my own notes, since I lost the tree with the previous attempt: ~/src/kubernetes-vendor-skydns

**Pull request closed without merging**
