### PR TITLE
AWS: Remove check that forces loadBalancerSourceRanges to be 0.0.0.0/0. 

### LINKED ISSUE #38633: Service type loadBalancer (AWS cloudprovider) only supports 0.0.0.0/0 for loadBalancerSourceRanges field
**Kubernetes version** (use `kubectl version`):
v1.4.6

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS v1235.2.0
- **Kernel** (e.g. `uname -a`):
4.8.6-coreos-r1 #1 SMP Wed Dec 7 00:29:42 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
When creating a service-type loadBalancer, adding `service.beta.kubernetes.io/aws-load-balancer-internal` creates an internal ELB, but the only allowed value for `loadBalancerSourceRanges` is 0.0.0.0/0. This limitation prevents you from specifying custom CIDR range for your hybrid cloud (Direct Connect to private data center)

**What you expected to happen**:
The limitation is unnecessary. Even in an AWS only scenario (no hybrid cloud), it makes sense to allow a CIDR range for a subnet where your calling services are deployed.

**How to reproduce it** (as minimally and precisely as possible):
Create a service-type loadBalancer and set loadBalancerSourceRanges to a value other than 0.0.0.0/0

### PR DESCRIPTION
**Pull request by dhawal55**
fixes #38633

Remove check that forces loadBalancerSourceRanges to be 0.0.0.0/0. Also, remove check that forces service.beta.kubernetes.io/aws-load-balancer-internal annotation to be 0.0.0.0/0. Ideally, it should be a boolean, but for backward compatibility, leaving it to be a non-empty value

### CODE REVIEW

**Comment by dhawal55** [comment]
I signed the CLA, but the check is still failing. Probably, some noob mistake. Any help?

**Comment by dhawal55** [comment]
Aha, the CLA check passed after my comment.

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
Not sure why I didn't look at this - sorry!

**Comment by dhawal55** [comment]
Any updates?

**Comment by justinsb** [comment]
Can you update the comment on ServiceAnnotationLoadBalancerInternal, then LGTM

**Comment by justinsb** [comment]
Thanks for fixing!

/lgtm

**Comment by cdenneen** [comment]
@dhawal55 I don't think this should be treated as boolean so actual CIDR restrictions could be honored. If making a boolean then another annotation for array of CIDR's to apply as inbound and outbounds should be made available. Just because it's `internal` load balancer doesn't mean it should be `0.0.0.0/0`

**Comment by dhawal55** [comment]
@cdenneen The value of this annotation is not used. It just meeds the annotations to determine that this is an internal load balancer. The CIDR range for securityGroup is specified using ‘LoadbalacerSourceRanges’ field in spec

**Comment by cdenneen** [comment]
@dhawal55 just wanted to circle back on this. Since `loadBalancerSourceRanges` is much better and technically `service.beta.kubernetes.io/aws-load-balancer-internal` is a "boolean" that still allows string value for backward compatibility. Issue is boolean doesn't work:

`service.beta.kubernetes.io/aws-load-balancer-internal: true`
vs
`service.beta.kubernetes.io/aws-load-balancer-internal: 'true'`

The first boolean creates "external ELB" whereas the latter will create internal ELB.

Interesting enough a non-quoted CIDR will create internal as well:

`service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/8` (This doesn't make CIDR 10.0.0.0/8 as previously discussed so it's very confusing and should be loadBalancerSourceRanges)

Is there anyway we can fix the first case so `true` works?
Is there anyway we can start documenting the switch to boolean so that documentation can stop being confusing with `0.0.0.0/0` that doesn't work with CIDR changes.

**Comment by dhawal55** [comment]
Last I checked, you just need to add the annotation for internal LB, the value can be anything. Can you point me to the documentation where it says that it should be boolen or “0.0.0.0/0”

**Comment by cdenneen** [comment]
If the annotation is a string or CIDR like 0.0.0.0/0 it works... if you set to boolean like true it creates external:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3338

From the opening comment of this post you said it should be boolean but "leaving to be non-empty value"... so theoretically `true` should be non-empty?. 

https://github.com/kubernetes/kubernetes/pull/38636#issue-97611131

So is there anyway to have

`service.beta.kubernetes.io/aws-load-balancer-internal: true`

work just like:
`service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

**Pull request merged**
