### PR TITLE
Fixing readme for both Travis banner and removing Google outreach paragraph.

### PR DESCRIPTION
**Pull request by aronchick**

### CODE REVIEW

**Comment by lavalamp** [comment]
rerunning shippable

**Comment by lavalamp** [comment]
add to whitelist

**Comment by brendandburns** [comment]
Needs a rebase...

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
@aronchick needs a rebase

**Comment by ixdy** [comment]
The issue here is that the branch has merge conflicts, and so Shippable is continually failing:
```
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
```

**Comment by ixdy** [comment]
Removing LGTM to get the munger to stop spamming.

**Comment by wojtek-t** [comment]
@aronchick - what's the status of this? Can we close it?

**Comment by dlsniper** [comment]
This should be closed as the changes that it addresses are not applicable anymore.

**Pull request closed without merging**
