### PR TITLE
Backport CIDR allocator fixes to 1.8

### PR DESCRIPTION
**Pull request by satyasm**
**What this PR does / why we need it**:
Backport of the IPAM allocator enhancements to 1.8 branch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Doing a manual backport as the file structures have changed.

**Release note**:

```release-note
Backport of the IPAM allocator enhancements to 1.8 branch.
```

### CODE REVIEW

**Comment by satyasm** [comment]
/assign @jpbetz 

can you please help with merging these fixes into the 1.8 branch? thanks!

**Comment by satyasm** [comment]
please hold on to this PR till the errors are fixed.

**Comment by albertvaka** [comment]
Is this a backport from 1.9? I mean, does 1.9 already include these fixes or only 1.10+?

**Comment by satyasm** [comment]
the fixes were spread across 1.10 and head. the fixes post 1.10 have been back-ported to 1.10. This is a combined backport of all the fixes as current exists on head.

**Comment by albertvaka** [comment]
So 1.9 doesn't have these changes?

**Pull request merged**
