### PR TITLE
fix redundant alias clientset

### PR DESCRIPTION
**Pull request by NickrenREN**
remove redundant alias clientset

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@yujuhong  Sorry to bother you. I rebased the codes and checks passed. PTAL. Thanks

**Comment by yujuhong** [comment]
@NickrenREN you'll need to rebase again, sorry. I'll mark this PR with a higher priority after the rebase, so that it can get in sooner before running into more conflicts.

**Comment by NickrenREN** [comment]
@yujuhong   I have rebased the codes... PTAL

**Pull request merged**
