### PR TITLE
Enable hostpath provisioner for vagrant environment

### PR DESCRIPTION
**Pull request by dshulyak**
This flag is required to run e2e tests for certain features (petset), and for manual tests and debugging.

related: https://github.com/kubernetes/kubernetes/issues/32119

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32264)

### CODE REVIEW

**Comment by dshulyak** [comment]
@derekwaynecarr wdyt about this change? It really helps to run pet sets e2e tests on vagrant provider

**Comment by asalkeld** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cluster/vagrant/config-default.sh, line 109 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32264#-KRaG-3nUGv7vHgRITKH:-KRaG-3odgD3hh_UqPG9:ba4hb74) ([raw file](https://github.com/kubernetes/kubernetes/blob/59751cbafb92ed949e1b859bc02148ff3f4cefcc/cluster/vagrant/config-default.sh#L109)):*
> ```Shell
> 
> # If enabled will provision local pv's for claim with volume.alpha annotation
> # kube-controller-manager will be started with flag --enable-hostpath-provisioner
> ```

This sounds confusing to me. Why not simply "If enabled kube-controller-manager will be started with the --enable-hostpath-provisioner flag"

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32264)*

**Comment by dshulyak** [comment]
@derekwaynecarr maybe you can assign someone to take look at this change? I really need it for pet sets tests

**Comment by dshulyak** [comment]
I re-tested it couple of times, works as expected.

```
 5307 ?        Ss     0:00 /bin/sh -c /usr/local/bin/kube-controller-manager --master=127.0.0.1:8080 --cluster-name=kubernetes --cluster-cidr=10.246.0.0/16  --service_cluster_ip_range=10.247.0.0/16     --service-account-private-key-file=/srv/kubernetes/server.key --v=2 --root-ca-file=/srv/kubernetes/ca.crt  --enable-hostpath-provisioner 1>>/var/log/kube-controller-manager.log 2>&1
```

**Pull request merged**
