### PR TITLE
reduce garbage_collector test cases running time

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
test cases in test\integration\garbagecollector\garbage_collector_test.go wait.Poll interval is too long. So the case running time is too long. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
ping @soltysh

**Comment by sttts** [comment]
I would even reduce it further to 200ms.

**Comment by soltysh** [comment]
> I would even reduce it further to 200ms.

I'd prefer not, too short times lead to flakes.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
