### PR TITLE
Remove unnecessary test case and reference to cadvisor/container/crio package

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I70563c8d6d02952f1ef6843833c738cdc11241b9

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This helps eliminate the dependency on crio and will help reduce the size of our vendored dependencies

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@dims  Hi, how it would reduce the size of our vendored dependencies

**Comment by dims** [comment]
@WanLinghao i am doing some work in https://github.com/google/cadvisor/pull/2209 once that gets in, we could select which runtimes we support when vendoring in cadvisor in k/k

**Comment by liggitt** [comment]
is this still needed?

**Comment by dims** [comment]
@liggitt guess we can revive this if ever we remove the crio reference from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L30

**Pull request closed without merging**
