### PR TITLE
Removed unused var.

### PR DESCRIPTION
**Pull request by k82cn**
Removed unused var.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33178)

### CODE REVIEW

**Comment by k82cn** [comment]
ping @ Random-Liu  :).

**Comment by Random-Liu** [comment]
@k82cn I don't quite understand. Isn't this var used here https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/container_manager_test.go#L89?

**Comment by k82cn** [comment]
Nop, "kubeletProcessName" is defined in `resource_collector.go`, and this var is not used: removed the var that "n" is lower case, using the var that "n" is upper case which is defined in `resource_collector.go`.

**Comment by k82cn** [comment]
ping @Random-Liu , does it make sense to you?

**Comment by Random-Liu** [comment]
@k82cn Hm...I see...Haha

**Comment by Random-Liu** [comment]
@k8s-bot e2e test this issue #IGNORE.

**Pull request merged**
