### PR TITLE
Bump konnectivity-client to v0.31.1

### PR DESCRIPTION
**Pull request by cheftako**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bump konnectivity-client to v0.31.1
Includes a feature which allows KNP server count to be determined by lease.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

-->
```docs
NONE
```

### CODE REVIEW

**Comment by tallclair** [comment]
AFAICT there haven't been any client changes in the last 9 months, so I think this is effectively a no-op? I think that's why there aren't any vendored changes. I don't have an issue with updating the version for book-keeping & consistency though.

/lgtm

**Comment by cheftako** [comment]
> AFAICT there haven't been any client changes in the last 9 months, so I think this is effectively a no-op? I think that's why there aren't any vendored changes. I don't have an issue with updating the version for book-keeping & consistency though.
The client changes are essentially no but I wanted them to be inline with the agent/server changes.
Eg
registry.k8s.io/kas-network-proxy/proxy-agent:v0.31.1

These are not no-op.

**Comment by liggitt** [comment]
hrmm... is the feature in the server or the client? this didn't actually change any client code...

**Comment by liggitt** [comment]
(no objections to the bump, I guess, just making sure we're updating what we expected)

**Comment by BenTheElder** [comment]
Do I understand correctly?
We're versioning the server and client together, we want to bump the version of the server being used for test, and it makes sense to continue to match the client version?

If that's correct then is should probably be encoded in the tool we have for this sort of thing:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml

**Comment by jkh52** [comment]
> Do I understand correctly? We're versioning the server and client together, we want to bump the version of the server being used for test, and it makes sense to continue to match the client version?
> 
> If that's correct then is should probably be encoded in the tool we have for this sort of thing: https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml

Mostly correct but there is both a server and agent, in addition to the client lib (used by apiserver). In this case [v0.31.0...v0.31.1](https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.31.0...v0.31.1) the fixes are in the agent.

/lgtm

**Pull request merged**
