### PR TITLE
register batch/jobs to federation-apiserver

### PR DESCRIPTION
**Pull request by jianhuiz**
register batch/jobs api objects to federation-apiserver

**Release note**:
```release-note
Federation: Add `batch/jobs` API objects to federation-apiserver
```

@quinton-hoole @nikhiljindal @deepak-vij 
#34261

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35943)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Code looks good.
You need to run update-bazel.sh for verification to pass.

Same comment as: https://github.com/kubernetes/kubernetes/pull/35945#issuecomment-257603719
There is less than a week left in 1.5 code freeze

**Comment by jianhuiz** [comment]
update-bazel.sh updated

**Comment by nikhiljindal** [comment]
Adding LGTM so that this gets merged in 1.6 whenever the freeze is lifted

**Comment by nikhiljindal** [comment]
umm @jianhuiz Can you please add a release note to the PR description? Ping here when you have done that and I will fix the release note label.

**Comment by jianhuiz** [comment]
@nikhiljindal Added into the PR description. Isn't the PR title will be the release note?

**Comment by jianhuiz** [comment]
rebased and updated registry/batch/job/etcd

**Comment by nikhiljindal** [comment]
Build failed with `k8s.io/kubernetes/test/integration/federation/server_test.go:351: undefined: unversioned in unversioned.APIResourceList`

**Comment by jianhuiz** [comment]
rebased and fixed

**Comment by nikhiljindal** [comment]
LGTM, thx

**Pull request merged**
