### PR TITLE
add TestSet for Set Method

### PR DESCRIPTION
**Pull request by twilight0620**
What type of PR is this?
add TestSet for Set Method

Add one of the following kinds:
/kind cleanup

What this PR does / why we need it:
This method does not have ut test, so i add it.

Which issue(s) this PR fixes:
add ut tests

Special notes for your reviewer:
Does this PR introduce a user-facing change?
NONE

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

/release-note-none

### CODE REVIEW

**Review by alexzielenski — COMMENTED** [review]
Thanks for your contribution! Looking over the existing tests, I see there is another test that exercises the `Set` function of PortRange [here](https://github.com/kubernetes/kubernetes/blob/6203e523244361719a6b185aacf047c70f8d33a0/staging/src/k8s.io/apimachinery/pkg/util/net/port_range_test.go#L58). I also see the test cases are very similar. How is this PR different?

**Comment by leilajal** [comment]
@twilight0620 this test seems to be already existed. I'll close this for now. Please let us know if we need to reconsider. Thanks!
/close
/triage accepted

**Pull request closed without merging**
