### PR TITLE
Revert "Allow env to be updated via specific key in resource"

### PR DESCRIPTION
**Pull request by deads2k**
This introduced an unstable test that is failing in our queue.

/assign @soltysh 

I'm trying to find a real fix, but let's get the revert tested and ready.

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

I think https://github.com/kubernetes/kubernetes/pull/60303 fixes this without reverting it.

**Comment by deads2k** [comment]
Fix failed.  I think this is the way to go

/hold cancel

**Review by soltysh — APPROVED** [review]
/lgtm

I'll try to check what's causing it maybe over the weekend or so.

**Pull request merged**
