### PR TITLE
[1.28] Automated cherry pick of #119027: prep for go1.21: use -e in go list

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
Cherry pick of #119027 on release-1.28.

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
For some reason, in go1.21, go list does not allow importing main packages anymore, even if it is for the sake of tracking dependencies (which is a valid use case).

A suggestion to work around this is to use -e flag to permit processing of erroneous packages. However, this doesn't seem prudent.

#### Which issue(s) this PR fixes:
Ref https://github.com/kubernetes/kubernetes/pull/118996#issuecomment-1617386511
Ref: https://github.com/golang/go/issues/59186

#### Special notes for your reviewer:
I'm not sure if we should be doing `-e` since that allows processing of ALL erroneous packages.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xmudrii** [comment]
@liggitt @MadhavJivrajani Is this something that we want to merge at this point or when migrating to Go 1.21?

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve

**Comment by MadhavJivrajani** [comment]
/retest 
This was fixed at HEAD iirc

**Pull request merged**
