### PR TITLE
Updating timeouts to match master.

### PR DESCRIPTION
**Pull request by krousey**
#9180 #9013

This is not a complete fix, but it makes this long running connections timeout less often, and are there for less annoying.

I have a fix to add proper timeouts per request in the works, but it isn't likely to make 1.0.

@bgrant0607 @dchen1107

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM. I think the only clients connecting to Kubelet should be proxy-like functionality, and probably Heapster.

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by bprashanth** [comment]
Waiting on Dawn's ok-to-merge

**Comment by krousey** [comment]
@dchen1107 Have you had a chance to look at this yet?

**Comment by mikedanese** [comment]
Status? @dchen1107

**Comment by dchen1107** [comment]
We decided not to include this one to v1.0.0, but might patch the release later. So ok-to-merge, but not patch.

**Comment by dchen1107** [comment]
Wait, I forgot..

@krousey and I chatted offline. This is purely hacky, and since we decided not to include this to 1.0. @krousey plan to have a clean way to fix the issue. Should we close this one, @krousey?

**Comment by krousey** [comment]
@dchen1107 I wouldn't call this hacky at all, just not a complete solution.

I have another PR out now that has had 0 attention #10656

**Comment by dchen1107** [comment]
Agreed on not hacky. But still close this one in favor of #10656 which is targeted for post 1.0. :-) Thanks!

**Pull request closed without merging**
