### PR TITLE
Add cli-maintainers as approvers to cmd/(gendocs|genman|genyaml)

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind cleanup
/sig cli
/priority important-longterm

#### What this PR does / why we need it:
There was a problem with cli approvals in https://github.com/kubernetes/kubernetes/pull/106159, this should fix this for the future.

#### Special notes for your reviewer:
/assign @smarterclayton 
/cc @eddiezane @KnVerey @seans3 @dims 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
thanks for doing this @soltysh 

/approve
/lgtm

**Comment by pacoxu** [comment]
```
hack/update-yamlfmt.sh
```
/hold 
for verify failure
/test pull-kubernetes-verify

**Comment by dims** [comment]
@soltysh easy to fix like @pacoxu said `hack/update-yamlfmt.sh` needs to be run.

**Comment by soltysh** [comment]
/hold cancel
this should be fixed now

**Pull request merged**
