### PR TITLE
deflake network policies job

### PR DESCRIPTION
**Pull request by aojea**
/kind flake

This uses a new version with a possible fix for https://github.com/kubernetes-sigs/kube-network-policies/issues/12

It is not easy to repro and does not manifest in the CI with a high rate https://testgrid.k8s.io/sig-network-gce#network-policies,%20google-gce so I don't want to cut a new release until I'm confident the workaround in https://github.com/kubernetes-sigs/kube-network-policies/pull/24 solves the problem

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce-network-policies

2/2

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce-network-policies

3/3

**Comment by dims** [comment]
/approve
/lgtm

/hold 

(until you need to land it @aojea ... noting that `pull-kubernetes-e2e-gce-network-policies` failed)

**Comment by aojea** [comment]
> 
Kubernetes e2e suite: [It] [sig-network] Services should create endpoints for unready pods expand_less

/close

not need to merge, that is the flake I was chasing

**Pull request closed without merging**
