### PR TITLE
fix mistake about [avaliable] for index_test.go

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix Spelling error about [avaliable] for index_test.go
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE"
```

### CODE REVIEW

**Comment by heqg** [comment]
lgtm
/ok-to-test

**Comment by yangjunmyfm192085** [comment]
/assign  @msau42, @saad-ali 
Hi,  there is a low-level error,I hope to fix this.
could you help me merge it?
Thank you very much.

**Comment by yangjunmyfm192085** [comment]
/assign msau42
/assign saad-ali

Could you take a moment to help take a look?
Thank you very much.

**Comment by yangjunmyfm192085** [comment]
@msau42 , maybe approve label is not work before.
could you please label it again? thank you very much.

**Comment by pacoxu** [comment]
/test pull-kubernetes-node-e2e-containerd 
for hang

**Pull request merged**
