### PR TITLE
Add unit tests for NegotiateOutputStreamSerializer

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This improves test coverage of negotiate.go from 63.3% to 84.7%.

### CODE REVIEW

**Comment by oomichi** [comment]
/assign @sttts 

for getting appproval?

**Comment by oomichi** [comment]
@liggitt Could you take a look at this?

**Comment by oomichi** [comment]
@liggitt Could you take a look at this?

**Comment by liggitt** [comment]
@smarterclayton will this conflict with the streaming table change in flight?

**Comment by oomichi** [comment]
@smarterclayton Could you take a look ?

**Comment by oomichi** [comment]
After 3230a0b4fd14a6166f8362d4732e199e8779c426 this seems unnecessary.

**Pull request closed without merging**
