### PR TITLE
Run apt-get update before installing sudo

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

recent changes to kubekins broke local-e2e with the following error
```
E: Unable to locate package sudo
```

Change-Id: I9ad324a2a070bc068ed1f0f88a912eafb191ad90

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
Nice catch

/lgtm

**Comment by dims** [comment]
/approve

(hmm, wonder why bot did not add it automatically)

**Pull request merged**
