### PR TITLE
Add import restrictions for csi-api

### PR DESCRIPTION
**Pull request by nikhita**
The list of restrictions is as per csi-api's godeps.json: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/csi-api/Godeps/Godeps.json

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/sig storage
/kind bug

/cc @sttts @saad-ali @jsafrane @verult 

Related: https://github.com/kubernetes/publishing-bot/pull/113

**Comment by sttts** [comment]
/lgtm
/approve
/hold

@saad-ali feel free to unhold when you think the dependencies are correct.

**Comment by nikhita** [comment]
Oh this needs a rebase. Will update.

**Comment by nikhita** [comment]
@jsafrane @saad-ali Ptal.

**Comment by nikhita** [comment]
Removing the hold since lgtm is gone anyway.

/hold cancel

**Comment by cblecker** [comment]
needs rebase

**Comment by nikhita** [comment]
@cblecker Thanks. Rebased.

**Pull request merged**
