### PR TITLE
proto: protect field access with lock to avoid possible data race [11…

### PR DESCRIPTION
**Pull request by nikzayn**
#### What type of PR is this?
/kind bug
/needs-sig
/needs-triage

#### What this PR does / why we need it:
This PR solves the data race issues in unmarshal function that's why we need it.

#### Which issue(s) this PR fixes:
[116497](https://github.com/kubernetes/kubernetes/issues/116497)

#### Special notes for your reviewer:
I have updated the lock type from `sync.Mutex` -> `sync.RWMutex`

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Comment by UtopiaGitHub** [comment]
```
if reqMask != u.reqMask && errLater == nil {
		// A required field of this message is missing.
+		u.lock.RLock()
+		defer u.lock.RUnlock()
		for _, n := range u.reqFields {
			if reqMask&1 == 0 {
				errLater = &RequiredNotSetError{n}
```

I think what we should protect is the field u.reqFields where the operation at protobuf/proto/table_unmarshal.go:L260. Thus, the u.lock.RLock() and defer u.lock.RUnlock() should be added there.

**Comment by nikzayn** [comment]
> ```
> if reqMask != u.reqMask && errLater == nil {
> 		// A required field of this message is missing.
> +		u.lock.RLock()
> +		defer u.lock.RUnlock()
> 		for _, n := range u.reqFields {
> 			if reqMask&1 == 0 {
> 				errLater = &RequiredNotSetError{n}
> ```
> 
> I think what we should protect is the field u.reqFields where the operation at protobuf/proto/table_unmarshal.go:L260. Thus, the u.lock.RLock() and defer u.lock.RUnlock() should be added there.


@UtopiaGitHub I have updated the code please check!

**Comment by UtopiaGitHub** [comment]
> > ```
> > if reqMask != u.reqMask && errLater == nil {
> > 		// A required field of this message is missing.
> > +		u.lock.RLock()
> > +		defer u.lock.RUnlock()
> > 		for _, n := range u.reqFields {
> > 			if reqMask&1 == 0 {
> > 				errLater = &RequiredNotSetError{n}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think what we should protect is the field u.reqFields where the operation at protobuf/proto/table_unmarshal.go:L260. Thus, the u.lock.RLock() and defer u.lock.RUnlock() should be added there.
> 
> @UtopiaGitHub I have updated the code please check!

It's ok.

**Comment by dims** [comment]
please fix in https://github.com/gogo/protobuf/ and then propose an update to the copy we have in vendor/ directory

**Pull request closed without merging**
