### PR TITLE
merge pkg/api/v1/node into pkg/util/node

### LINKED ISSUE #55760: pkg/api/v1/node should be merged with pkg/util/node
[pkg/api/v1/node](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/node/util.go#L17) should be merged with [pkg/util/node](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go) .
These two pkgs both function on node condition/status...

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

merge pkg/api/v1/node into pkg/util/node
They have similar function on node resource.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55760

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by guangxuli** [comment]
@hzxuzhonghu I think this is dulplicated to https://github.com/kubernetes/kubernetes/pull/55588

/cc @cblecker

**Comment by sttts** [comment]
I don't think pkg/util is the right place for api helpers. Self-contained helper funcs can and should go into the helper package next to the api, compare https://github.com/kubernetes/kubernetes/pull/55492.

As far as I see pkg/util/node is already a kitchen sink package, full of unrelated code, with many dependency. Better clean that up than moving more code there.

**Comment by hzxuzhonghu** [comment]
>@hzxuzhonghu I think this is dulplicated to #55588

@guangxuli Sorry, I did not see.

@sttts Close this, if need I will be happy to do some work.

**Pull request closed without merging**
