### PR TITLE
AWS kube-up: Increase timeout waiting for docker start

### LINKED ISSUE #23623: Creating/Adding nodes on AWS always reports a failure
When creating a new cluster on AWS with the 1.2 version I always get a failure when checking docker on the nodes, but after the check loop ends everything seems to work fine and all nodes are marked as ready.
```
Sanity checking cluster...
Attempt 1 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 2 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 3 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 4 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 5 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 6 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 7 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 8 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 9 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 10 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 11 to check Docker on node @ 52.37.0.9 ...not working yet

Your cluster is unlikely to work correctly.
Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
```

The instance types for nodes is m4.large.

### PR DESCRIPTION
**Pull request by justinsb**
Apparently our cluster start time increased, to the point where users
are reporting spurious timeouts (#23623) and users are reporting that
increasing the timeout fixes the issue (thanks @paralin for the
suggestion and @jlfields for confirming).

Fix #23623

### CODE REVIEW

**Comment by mikedanese** [comment]
:lgtm: +lgtm 

<details><summary><i>Previously, k8s-bot (Kubernetes Bot) wrote…</i></summary>
> GCE e2e build/test **passed** for commit cc4ac5459c6ebf128ab64084289d567787f3d24c.
> * [Build Log](http://pr-test.k8s.io/25405/kubernetes-pull-build-test-e2e-gce/39268/build-log.txt)
> * [Test Artifacts](https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25405/kubernetes-pull-build-test-e2e-gce/39268/artifacts/)
> * [Internal Jenkins Results](http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//39268)
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/25405#-:-KHRo7Eu9L0Dioq5NtnZ:322772048)*

**Comment by roberthbailey** [comment]
@justinsb please create a cherry pick pull for this PR.

**Comment by roberthbailey** [comment]
Now that github is working, I've created a cherry pick.

**Comment by roberthbailey** [comment]
I merged #26098 so I'm going to remove the cherrypick candidate label.

**Pull request merged**
