### PR TITLE
Reorder rpc's to follow same order as functions in services.go

### PR DESCRIPTION
**Pull request by mkenigs**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I just reordered the rpc's. Thought following the same order in services.go and api.proto would be slightly clearer.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
(note that this loses git history on these methods)

**Review by mattjmcnaughton — COMMENTED** [review]
I'm +1 with @liggitt. 

I really appreciate the eye towards readability - however, in this context I think maintaining the git history offers more benefit.

**Comment by mkenigs** [comment]
@resouer @Random-Liu guess I should close this then?

**Comment by matthyx** [comment]
> @resouer @Random-Liu guess I should close this then?

I guess yes...

**Pull request closed without merging**
