### PR TITLE
Rename 1.1 jobs to *-release-1.1.

### PR DESCRIPTION
**Pull request by spxtr**
#23021

This needs to go in at the same time as #23753

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23754)

### CODE REVIEW

**Comment by ixdy** [comment]
What about `kubernetes-e2e-gce-scalability-1.1`?

**Comment by ixdy** [comment]
^

**Comment by spxtr** [comment]
Oh, we're not running that job anymore so I didn't change it. Think it's worth it?

**Comment by ixdy** [comment]
Maybe just delete it then?

**Comment by ixdy** [comment]
LGTM

**Comment by zmerlynn** [comment]
Marking `cherrypick-approved` for direct c-p for test job fixed.

**Comment by david-mcmahon** [comment]
Ready for lgtm?

**Comment by ixdy** [comment]
The other half needs to be remade on the `kubernetes/test-infra` repo.

**Comment by ixdy** [comment]
what's the status of this PR?

**Comment by spxtr** [comment]
Are we going to run e2e on 1.1 once 1.3 is out? If not, we can just close this.

**Pull request closed without merging**
