### PR TITLE
Fixed kibana image and controller to work through proxy

### PR DESCRIPTION
**Pull request by crassirostris**
As described in #34969, new kibana image doesn't work properly with proxies without additional configuration.

@piosz

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36103)

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by mindw** [comment]
The kibana gcr image lacks this fix. Is possible to refresh the image?

**Comment by Crassirostris** [comment]
@mindw Yes, sorry, I was waiting for the merge and forgot about it, one minute

**Comment by Crassirostris** [comment]
@mindw Please test

**Comment by mindw** [comment]
All is well now. Thanks!

**Comment by lhopki01** [comment]
This image is broken if we don't want to use kibana behind the proxy.

**Comment by lhopki01** [comment]
The image now takes forever to startup because it has to optimize all the paths.

**Comment by Crassirostris** [comment]
@lhopki01 Thank you very much for the feedback!

>This image is broken if we don't want to use kibana behind the proxy.

Yes, interpolation issues, sorry. You can temporary set KIBANA_BASE_URL to '' (two single quotes), I will fix it shortly

>The image now takes forever to startup because it has to optimize all the paths.

Yes, that is true. Unfortunately, as it was mentioned in https://discuss.elastic.co/t/how-to-avoid-dynamic-bundle-optimization/37367, there's no way to avoid this. However, if you wish to use kibana without proxy, it won't perform this lengthy operation.

**Comment by lhopki01** [comment]
> Yes, interpolation issues, sorry. You can temporary set KIBANA_BASE_URL to '' (two single quotes), I will fix it shortly
This doesn't work setting your container command to 
`command: ["/bin/sh", "-c", "/kibana/bin/kibana -e ${ELASTICSEARCH_URL}"]`
fixes the issue if you set the elasticsearch url as a env variable.

**Comment by Crassirostris** [comment]
@lhopki01 Are you sure it doesn't work? Try this:

```
docker run -e "KIBANA_BASE_URL=''" -ti gcr.io/google_containers/kibana:v4.6.1
```

What does it output?

And I'm not sure what you meant in your last post, sorry :) Could you please say it in other words?

**Comment by lhopki01** [comment]
@Crassirostris 
Sorry I wasn't clear.  I'm running this as pod in kubernetes so replacing the command of the containers with what I set fixes it.

With further testing if I set the variable as follows in kubernetes it works too
```
- name: "KIBANA_BASE_URL"
  value: "''"
```

**Comment by Crassirostris** [comment]
@lhopki01 No problem thanks!

Yes, that's because run script sets base url in config :)

>With further testing if I set the variable as follows in kubernetes it works too

That's what I meant in the first place, sorry for not being clear!

**Comment by lhopki01** [comment]
@Crassirostris 

I've got a fix here.  Should I create a pull request for it?

https://github.com/lhopki01/kubernetes/blob/be-able-to-not-set-kibana-baseurl/cluster/addons/fluentd-elasticsearch/kibana-image/run.sh

**Comment by Crassirostris** [comment]
@lhopki01 What's $VAR variable? I have a fix like this in-flight:

```
export KIBANA_BASE_URL=${KIBANA_BASE_URL:-"''"}
```

It will work for you if you just remove KIBANA_BASE_URL variable from pod specification, in a backward-compatible

**Comment by lhopki01** [comment]
oops that was meant to be $KIBANA_BASE_URL not $VAR

> export KIBANA_BASE_URL=${KIBANA_BASE_URL:-"''"}

That works too. 

Image will need to be rebuilt too.

**Comment by Crassirostris** [comment]
@lhopki01 Oh, I see

> Image will need to be rebuilt too.

Yes, absolutely. I'm running e2e tests right now, just to be sure that nothing broke

**Pull request merged**
