### PR TITLE
Enable NFS and GlusterFS tests in both node and cluster e2e tests

### PR DESCRIPTION
**Pull request by jingxu97**
This PR is to enable NFS and GlusterFS tests on both node and cluster
e2e tests.

It also change the code to use ExecCommandInPod instead of kubectl since
node does not have kubectl available

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36195)

### CODE REVIEW

**Comment by vishh** [comment]
@jingxu97 can #36186 be closed in favor of this.

**Comment by saad-ali** [comment]
`FAILED   hack/make-rules/../../hack/verify-bazel.sh`

* You have to update the BUILD file with the new files.

`FAILED   hack/make-rules/../../hack/verify-boilerplate.sh`

  * You need to follow [this template](https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.go.txt) *exactly* for the header including the new lines.

**Comment by jingxu97** [comment]
@k8s-bot node e2e test this

**Comment by jingxu97** [comment]
@k8s-bot unit test this

**Comment by jingxu97** [comment]
@k8s-bot unit test this

**Comment by jingxu97** [comment]
@k8s-bot unit test this

**Comment by jingxu97** [comment]
@vishh PTAL

**Comment by saad-ali** [comment]
LGTM

Test-only changes ok for post-code freeze merge.

**Comment by vishh** [comment]
lgtm

**Comment by vishh** [comment]
Nice work @jingxu97 !

**Pull request merged**
