### PR TITLE
Automated cherry pick of #73288 to release-1.12: Decouple node-problem-detector release from kubernetes

### PR DESCRIPTION
**Pull request by wangzhen127**
Cherry pick of #73288 on release-1.12.

#73288: Decouple node-problem-detector release from kubernetes

Also manually cherry picked the test fixes from #74922 and #75063.

Part of https://github.com/kubernetes/node-problem-detector/issues/236.

**Does this PR introduce a user-facing change?**:

```release-note
Node-Problem-Detector configuration is now decoupled from the Kubernetes release on GKE/GCE.
```

**Manual cluster test**:
Run the following command with this PR using an old version of NPD and customized release path and flags. In release-1.12, NPD is using v0.6.0. Change it to v0.5.0 in the test.
```
NODE_PROBLEM_DETECTOR_VERSION="v0.5.0" \
NODE_PROBLEM_DETECTOR_TAR_HASH="650ecfb2ae495175ee43706d0bd862a1ea7f1395" \
NODE_PROBLEM_DETECTOR_RELEASE_PATH=https://storage.googleapis.com/zhenw-gke-dev-public \
NODE_PROBLEM_DETECTOR_CUSTOM_FLAGS="--v=2 --logtostderr --system-log-monitors=/home/kubernetes/node-problem-detector/config/kernel-monitor.json --custom-plugin-monitors=/home/kubernetes/node-problem-detector/config/kernel-monitor-counter.json --port=20256" \
kubetest --build --up \
--provider=gce \
--gcp-project=zhenw-gke-dev \
--gcp-zone=us-central1-c
```
After cluster is up, manually verify a node:
1. `kube-env` of the VM instance: environment variables are correctly set.
2. `sudo journalctl -u kube-node-installation.service`: correct NPD version is downloaded.
3. `sudo cat /etc/systemd/system/node-problem-detector.service`: NPD flags are set correctly.
4. `sudo journalctl -u node-problem-detector.service`: NPD is running fine.

**Node E2E test**:
In node E2E test, the default version is now v0.6.2. Run the following command with this PR using a different version of NPD. 
```
make test-e2e-node FOCUS="NodeProblemDetector" SKIP="" REMOTE=true CLEANUP=true DELETE_INSTANCES=true EXTRA_ENVS="NODE_PROBLEM_DETECTOR_IMAGE=k8s.gcr.io/node-problem-detector:v0.5.0"
```
1. Verify the tests pass.
2. Verify the log that NPD v0.5.0 is used (instead of v0.6.2), which indicates that we can customize the NPD version in node e2e tests.

### CODE REVIEW

**Comment by wangzhen127** [comment]
/assign @Random-Liu 
Will fix the failure and update shortly.

**Comment by wangzhen127** [comment]
Just tested this cherry-pick by following the steps in the PR description.

**Comment by wangzhen127** [comment]
/assign @dougm
/assign @feiskyer

Assigning to branch manager and patch release manager. This cherry pick is for configuring NPD on GKE/GCE only.

**Comment by feiskyer** [comment]
cherry pick approved.

**Pull request merged**
