### PR TITLE
skip WaitForAttachAndMount for terminated pods in syncPod

### PR DESCRIPTION
**Pull request by sjenning**
Fixes https://github.com/kubernetes/kubernetes/issues/49663

I tried to tread lightly with a small localized change because this needs to be picked to 1.7 and 1.6 as well.

I suspect this has been as issue since we started unmounting volumes on pod termination https://github.com/kubernetes/kubernetes/pull/37228

xref openshift/origin#14383

@derekwaynecarr @eparis @smarterclayton @saad-ali @jwforres 

/release-note-none

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
this is the same gating logic that we use for pod level cgroup creation and destruction, so it appears safe to me.  will wait for bots to report green.

**Comment by derekwaynecarr** [comment]
not for this pr, but a good future gating test would be to see if we get events about a pod from the node after its death.  i am not sure how long it should wait, but maybe a node e2e could let us experiement on it in future.

**Comment by sjenning** [comment]
Can I get a cherry-pick-candidate on this?

**Pull request merged**
