### PR TITLE
Avoid serialization of maps when log level < 10

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Avoid serialization of maps when log level is below 10.

pprof has shown that this log line does multiple allocations

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
did you do a quick search to see if there are other cases?

**Comment by alculquicondor** [comment]
Added another commit for one more that could be helpful.

The rest of V>5 log lines are just simple values

**Comment by alculquicondor** [comment]
@kubernetes/release-managers 
is it too late to include this in the milestone?

**Comment by xmudrii** [comment]
@alculquicondor We're now past Code and Test Freeze in the release cycle, so this will have to wait for the master branch to get open again (Code Thaw is scheduled for December 6 after the 1.26 release). You can find more details in the [1.26 release calendar](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.26).

**Comment by mborsz** [comment]
/lgtm

Thanks!

**Pull request merged**
