### PR TITLE
Improve third party codec.

### PR DESCRIPTION
**Pull request by brendandburns**
Ref #13000 

@lavalamp @caesarxuchao

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
LGTM. Thanks @brendandburns. It needs rebase.

**Comment by wojtek-t** [comment]
e2e test flake:
 Services should serve a basic endpoint from pods

@k8s-bot test this please

**Comment by brendandburns** [comment]
Rebased and passing all tests, adding 'lgtm' label on @caesarxuchao 's earlier LGTM in a comment.

**Comment by wojtek-t** [comment]
@brendandburns - why are you not in the whitelist?

**Comment by caesarxuchao** [comment]
Shippable couldn't find the build. Sigh.

**Comment by wojtek-t** [comment]
@brendandburns - it seems that Shippable failure is real:

--- FAIL: TestInstallThirdPartyAPIGet (0.02s)

**Comment by brendandburns** [comment]
Test fixed, ptal.

Thanks!
--brendan

**Comment by caesarxuchao** [comment]
LGTM. Thank you!

**Pull request merged**
