### PR TITLE
Enable validate when test kubectl with List

### PR DESCRIPTION
**Pull request by janetkuo**
Since PR #14726 is merged, enable validate in `test-cmd.sh`
Ref issue #13812 

cc @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM. Thanks much.

**Comment by karlkfi** [comment]
kube-dns timed out coming up in the smoke test. 
Likely a flake, since this test doesn't change anything related.

**Comment by JanetKuo** [comment]
Re-applying lgtm label after rebase.

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Pull request merged**
