### PR TITLE
WIP: verify the DRA tests are failing on master (probably require NodeAlphaFeature annotation)

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@mimowo PTAL: https://github.com/kubernetes/kubernetes/pull/118685

**Comment by mimowo** [comment]
> @mimowo PTAL: #118685

Thanks for the pointer! I will let the tests to finish and will close the PR as it is already being addressed.

**Comment by mimowo** [comment]
/close 
Closing in favor of https://github.com/kubernetes/kubernetes/pull/118721

**Pull request closed without merging**
