### PR TITLE
Add AnswerDash to gh-pages.

### PR DESCRIPTION
**Pull request by jeffmendoza**
As requested by @aronchick

### CODE REVIEW

**Comment by fabioy** [comment]
@k8s-bot ok to test

**Comment by fabioy** [comment]
Is this tracking to see how often people access k8s docs?

**Comment by jeffmendoza** [comment]
It allows people to ask questions on the site/docs.

**Comment by jeffmendoza** [comment]
@fabioy Can we merge this?

**Comment by fabioy** [comment]
Sure. LGTM.

**Comment by fabioy** [comment]
Merge bot going nuts on this one. Manually merging, since it's a doc only change.

**Comment by jeffmendoza** [comment]
Thanks!

**Pull request merged**
