### PR TITLE
support nfs mount time options

### LINKED ISSUE #24721: Support NFS v3 tcp mode
We would like to mount a GlusterFS volume as NFS mount. GlusterFS supports [NFS v3 tcp mode](http://www.gluster.org/community/documentation/index.php/Gluster_3.1:_Manually_Mounting_Volumes_Using_NFS). NFS supports automatic reclaiming of disk space, which is useful. Can this be supported in Kubernetes?

Thanks.

### PR DESCRIPTION
**Pull request by rootfs**
fix #24721 and #17226 
@kubernetes/sig-storage

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29460)

### CODE REVIEW

**Comment by erictune** [comment]
@matchstick 

Can you assign someone with NFS knowledge to do a review on this.

**Comment by erictune** [comment]
I'd like to understand the security side of this.

Before this change, what sorts of users would you typically permit to use NFS volume source, and which would you not?  

After this change, by allowing those same users to specify mount options, can they harm the system by picking evil mount options?  Is this any worse than what they could do before this change?  If it is worse, do we need to filter certain options, or restrict them via PSP?

**Comment by rootfs** [comment]
@erictune All good points. So far I only pick up the protocol and performance related mount options (rsize/wsize/vers/proto). Security related options are not supported and will error out if specified.

**Comment by matchstick** [comment]
@ I and @saad-ali can review this. Assigning.

**Comment by saad-ali** [comment]
I don't think we should accept a blob of mount options in the NFS public API and leave it up to "magic" under the covers to parse filter and hand off to the mounter. This makes it harder for users to quickly understand which options are supported by k8s. 

Instead, I'd like the API to specify each permitted mount option as an explicit field that can be validated and documented properly. I realize this means a more verbose API.

Thoughts?

CC @kubernetes/sig-storage

**Comment by thockin** [comment]
I tend to agree with Saad on this.  How bad would it be to enumerate them?

**Comment by rootfs** [comment]
@saad-ali @thockin We have only a couple requested options (proto and vers), enumerating these options works for now and is of better usability. Making APIs for each of the mount options also has its own problem: when more options are requested, unless the customers know which options are supported, new mount options specified in the API are not backward compatible.

**Comment by kfox1111** [comment]
Yeah. not having them now is causing us problems.

For sure, I need:
* soft
* vers=3
* nolock

To make one of my nfs servers accessible.

I'm sure some of the tunings like r/wsize and retry, would be useful too.

There are a lot of options though. If you were going to add them explicitly, I'd suggest adding them all from the start. There are so many options because someone needed each and every one of them at one point or another. If we don't, were going to get users request new ones all the time and keep getting frustrated with it not providing the things they need.

**Comment by thockin** [comment]
I agree it would be better to add them all at once PROVIDED we can be
confident that none of them compromise the integrity of the host or the
security of the system overall.  It may also be he case that there are
things we would allow in PersistentVolumes (more admin-controlled) that we
would not want in plain pod volumes (user controlled).

We also need to characterize and document how they interact and what they
mean.

**Comment by rootfs** [comment]
@thockin @kfox1111 ok, I'll compile a list of Linux nfs mount options. If anybody can provide a list of options that work on mac, that'll be great.

**Comment by rootfs** [comment]
@matchstick would you consider adding this to storage meeting?

**Comment by saad-ali** [comment]
> @matchstick would you consider adding this to storage meeting?

Done

**Comment by Cocotton** [comment]
Are there any updates on this pull request?

**Comment by Cocotton** [comment]
Any updates on this PR?

**Comment by rootfs** [comment]
@Cocotton also see #31613 we need a consensus which direction we go.

**Comment by kfox1111** [comment]
Still could use this

**Comment by rootfs** [comment]
@kubernetes/sig-storage also see #31613

**Comment by tcf909** [comment]
Did this ever get merged or moved forward from a discussion standpoint?

Using AWS EFS is almost "unusable" without version=4.1 along with some other best practice options.

**Comment by rootfs** [comment]
@tcf909 we plan to have a solution for kube 1.6.

**Comment by argent-smith** [comment]
@k8s-merge-robot please keep it open ;)

**Comment by eparis** [comment]
I'm going to go ahead and close this. Something similar (but different) will need to be re-openned once https://github.com/kubernetes/community/pull/321 is finally decided...

**Pull request closed without merging**
