### PR TITLE
Set OWNERS of pkg/apis to api-(approvers/reviewers).

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It seems that this was a miss in #53997

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
looks like pkg/apis/core/OWNERS should probably be dropped to delegate here

**Comment by alculquicondor** [comment]
Dropped, except for the label

**Pull request merged**
