### PR TITLE
Skip test "MetricsGrabber should grab all metrics from API server." w…

### PR DESCRIPTION
**Pull request by pwittrock**
…hen running upgrade tests.

See #32704.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33045)

### CODE REVIEW

**Comment by foxish** [comment]
@pwittrock The test works as expected on 1.3 and higher?

**Comment by pwittrock** [comment]
@foxish I don't see it failing on 1.3 anywhere...yet...

**Comment by foxish** [comment]
@pwittrock The cherrypick bot expects a milestone of the form `release-x.y` I think. We should do a manual merge on v1.2 once the unit/integration tests pass.

**Comment by pwittrock** [comment]
SGTM

**Comment by pwittrock** [comment]
I think it probably doesn't even need that label to be merged.

**Pull request merged**
