### PR TITLE
replace predicates string with corresponding const in TestDefaultPredicates

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
replace predicates string with corresponding const in TestDefaultPredicates. Unify with the const in func defaultPredicates().
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by yastij — APPROVED** [review]
Thanks lgtm

**Comment by k82cn** [comment]
/approve no-issue

Just const str replacement.

**Pull request merged**
