### PR TITLE
Added indexer description for the API of NewIndexerInformer.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by eparis** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
