### PR TITLE
[kubeadm] added defaulting to API objects

### LINKED ISSUE #35424: kubeadm init --config breaks defaults
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubeadm defaults
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.4.3

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: kubeadm
- **Others**: N/A

**What happened**:
Using `kubeadm init --config /path/to/config.yml` appears to block default values from being set. I first noticed it where a pre-flight check of the Servicer CIDR was presenting itself as an empty string although I had not set it through the command line flag nor in the config file. I also noticed that kubelet requests to the API server were being sent to port 0 as the API server default port had not been set.

**What you expected to happen**:
A config file should only override defaults, not make it so that no defaults are set.

**How to reproduce it** (as minimally and precisely as possible):
Use `kubeadm init --config /path/to/config.yml` with an appropriate configuration file that does not set the service CIDR, for example, and note that pre-flight checks will fail due to the default values not being set.

**Anything else do we need to know**:
A temporary workaround is to explicitly set all values to their defaults or the value you desire.

### PR DESCRIPTION
**Pull request by pires**
**What this PR does / why we need it**: `kubeadm {init,join}` supports configuration to be passed as a file with the flag `--config`. However, there are no defaults in place to make sure mandatory configuration information always exists when it's not explicitly specified in the configuration file. This PR adds the mandatory default information.

**Which issue this PR fixes**: fixes #35424

**Special notes for your reviewer**: /cc @luxas @mikedanese 

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35796)

### CODE REVIEW

**Comment by mikedanese** [comment]
Can you please put auto generated changes in one commit separate from other changes?

**Comment by pires** [comment]
@mikedanese but ofc! Anyway, it seems I screwed up unit-tests. Adding kubeadm defaulting to `pkg/api/defaulting_test.go` doesn't sound right to me, so can you please point me in the right direction?

**Comment by mikedanese** [comment]
@pires I expect that round trip testing should start failing. You will need to add some stuff to the fuzzers https://github.com/kubernetes/kubernetes/blob/master/pkg/api/testing/fuzzer.go#L161

**Comment by pires** [comment]
@mikedanese OK but what about adding `kubeadm.k8s.io` to `pkg/api/defaulting_test.go`? Should I do it or is there a different way?

**Comment by pires** [comment]
@krousey sorry for pinging but perhaps you can shed some light into my questions above?

**Comment by luxas** [comment]
@pires Is there anything I can do for this to help it getting merged?
This is one of the last PRs we need before the release

cc @mikedanese your help might be needed here...

**Comment by pires** [comment]
@luxas if you can answer my question above, it would be great. Is adding `kubeadm.k8s.io` to `pkg/api/defaulting_test.go` the right thing to do?
After that, if the fuzzers complain, I'll add them.

**Comment by krousey** [comment]
@pires It would be ideal for API tests to be with the API group. Usually that means breaking up the huge central test into common testing utilities that each API group can re-use.

That being said, the particular test you reference seems overkill for testing defaulting. It's running fuzz a bunch of times to make sure some things are not defaulted. Maybe a simpler test is more appropriate.

**Comment by luxas** [comment]
Yes, @pires I think that means you should add `kubeadm.k8s.io` to `pkg/api/defaulting_test.go`
In an ideal world, it could be otherwise, but right now this test is centralized.

Add fuzzers if they complain as well

**Comment by pires** [comment]
After a while, I still don't get this to work and unfortunately I am in a position where, right now, I can't deliver this by myself. It's just a lot of things I'm totally new to, in this codebase.

I got the defaulting tests to work by:
* Removed defaulting for `ClusterInfo`
* Added another default value for `NodeConfiguration`:
```
	if len(obj.MasterAddresses) == 0 {
		obj.MasterAddresses = append(obj.MasterAddresses, "127.0.0.1")
	}
```
, without this it won't work 😕 
* Added the following to `pkg/api/defaulting_test.go` `TestDefaulting` func:
```
	{Group: "kubeadm.k8s.io", Version: "v1alpha1", Kind: "MasterConfiguration"}:               {},
	{Group: "kubeadm.k8s.io", Version: "v1alpha1", Kind: "NodeConfiguration"}:                 {},
```
* Added the following to `pkg/api/testing/fuzzer.go`:
```
	func(kmc *kubeadm.MasterConfiguration, c fuzz.Continue) {
		c.FuzzNoCustom(kmc) // fuzz self without calling this function again

		if kmc.API.BindPort == 0 {
			kmc.API.BindPort = int32(c.Rand.Int31())
		}
	},
	func(knc *kubeadm.NodeConfiguration, c fuzz.Continue) {
		c.FuzzNoCustom(knc) // fuzz self without calling this function again

		if knc.APIPort == 0 {
			knc.APIPort = int32(c.Rand.Int31())
		}
	},
```

I hope you guys have the patience to shed some more light into my path or the time to take it from here (and I'll learn from what you do!).

**Comment by mikedanese** [comment]
I can take a look.

**Comment by luxas** [comment]
@pires If you have activated that maintainers can push to your branch, @mikedanese can then update this PR so we can get it in.

**Comment by pires** [comment]
@luxas @mikedanese can't do that. I'm OK with closing this an open a new one that includes my commits, though.

**Comment by luxas** [comment]
OK, let's see if @mikedanese fixes it first :)

**Pull request closed without merging**
