### PR TITLE
Remove unused command waitfordetach from flex volume driver

### PR DESCRIPTION
**Pull request by jolestar**
**What this PR does / why we need it**:
Clean unused code.

**Special notes for your reviewer**:
See #35629
Original PR is https://github.com/kubernetes/kubernetes/pull/50754 , the PR's repo has bean deleted，so I create a new PR and merge upstream for test.
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jolestar** [comment]
@xiangpengzhao @jingxu97 @j-griffith Please look again.

**Review by rata — APPROVED** [review]
Thanks a lot for the PR, LGTM!

I've read the PRs and issues you link, and the ones linked there, etc.

It seems in the last PR, https://github.com/kubernetes/kubernetes/pull/50754, the diff is the same. And as the comment https://github.com/kubernetes/kubernetes/pull/50754#issuecomment-350203930 says, it seems it failed as: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50754/pull-kubernetes-e2e-gce-bazel/35447/. That is: "Something went wrong: failed to prepare test environment: boskos does not have a free gce-project at the moment"

It seems it was just a quota on the usage or something.

I didn't follow, though, on why you closed it and created a new one, identical. Didn't follow "the PR's repo has bean deleted" in this PR description. Was because tests weren't running for the other PR (https://github.com/kubernetes/kubernetes/pull/50754) ? 

In any case, if test pass now, LGTM. And thanks again!

It seems there might be some other volumes with this interface still, if you want to write more patches ;)

**Comment by rata** [comment]
(Assigning to chakri-nelluri as it was suggested but the bot in a previous comment)

**Comment by rata** [comment]
@jolestar all tests are green now. I've added the LGTM, it needs the review of @chakri-nelluri and it's ready to go in (just in case you didn't know how the process was)

Thanks again!

**Pull request merged**
