### PR TITLE
Upgrade go-autorest to v11.1.2

### LINKED ISSUE #75579: Long running operations may fail because of go-autorest bugs
**What happened**:

According to https://github.com/Azure/go-autorest/issues/357, the timeout set in context doesn't take effect and 15min is always used for long running operations.

We should upgrade the version of go-autorest to 11.1.2 or 11.3.2.

**What you expected to happen**:

Azure clients respect timeout set from context.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Cross refer https://github.com/kubernetes/test-infra/pull/11887.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/priority critical-urgent

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:

According to Azure/go-autorest#357, the timeout set in context doesn't take effect and 15min is always used for long running operations.

This PR upgradse the version of go-autorest to 11.1.2 so as to fix the issue.

**Which issue(s) this PR fixes**:

Fixes #75579

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade go-autorest to v11.1.2
```

/priority important-soon
/assign @liggitt @andyzhangx

### CODE REVIEW

**Comment by liggitt** [comment]
according to https://github.com/Azure/go-autorest/issues/357#issuecomment-456485651, this was fixed in v11.3.2, not v11.1.2

**Comment by liggitt** [comment]
ah, nevermind, I see v11.1.2 was a special backport patch release - https://github.com/Azure/go-autorest/releases/tag/v11.1.2

**Comment by liggitt** [comment]
/approve

will leave lgtm to @andyzhangx

**Review by dims — APPROVED** [review]
/lgtm

Looks legit :) does not add anything new.

**Comment by dims** [comment]
oops need to let @andyzhangx take a look

/hold

**Comment by liggitt** [comment]
thanks for all the effort to get these fixes in a non-disruptive way

**Review by andyzhangx — APPROVED** [review]
/lgtm
/test pull-kubernetes-e2e-aks-engine-azure

**Comment by feiskyer** [comment]
thanks, @liggitt and @dims.

**Pull request merged**
