### PR TITLE
Automated cherry pick of #14917 upstream release 1.1

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref #14917 (Improvements to deployment e2e)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @brendandburns to review

**Comment by bgrant0607** [comment]
This is needed for e2e tests?

**Comment by nikhiljindal** [comment]
Yes the original PR added more extensive e2e tests. It also fixed a bug in the controller.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
