### PR TITLE
fix invalid issue link in api conversion

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

When working on #49336, found invalid link `https://github.com/kubernetes/kubernetextensionsssues/39865`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
cc @janetkuo

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
/lgtm
Thanks for the fix.

**Comment by dixudx** [comment]
@erictune @lavalamp @smarterclayton Needs your `/approve no-issue`. Thanks.

**Comment by dixudx** [comment]
@erictune @lavalamp @smarterclayton Needs your /approve no-issue. Thanks.

**Comment by sttts** [comment]
Triviality.

**Pull request merged**
