### PR TITLE
Finish MetricsGrabber

### PR DESCRIPTION
**Pull request by gmarek**
@fgrzadkowski please review second commit. First one is already lgtm'd by @wojtek-t (#18714)

cc @wojtek-t

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
Do we actually use different kubelet ports in tests?

**Comment by gmarek** [comment]
We don't but @wojtek-t wanted to be sure that we can use it here.

**Comment by fgrzadkowski** [comment]
This LGTM modulo a minor comment.

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
