### PR TITLE
Move kubectl scheme

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/scheme` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/scheme.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/cc @janetkuo 

for `pkg/controller` update.

**Review by janetkuo — APPROVED** [review]

**Comment by seans3** [comment]
/cc @BenTheElder 

for `vendor/modules` change.

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
