### PR TITLE
Add any necessary comments

### PR DESCRIPTION
**Pull request by cubxxw**
Signed-off-by: xiongxinwei <3293172751nss@gmail.com>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Add any necessary comments.As the first step to becoming a Kubernetes

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kundan2707** [comment]
@cubxxw  please sign CLA

**Comment by liggitt** [comment]
sorry, I closed this since the diff was zero files, and I thought it was accidentally opened.

it looks like https://github.com/kubernetes/kubernetes/compare/433b968197f6775fff091851de64d7874a0172f5..17bf864c1fc20e4badc9a6e0659c5190310462e1 was originally adding some comments to functions... if you can recover that commit and reopen this PR or a new PR, we'll take a look at it

**Pull request closed without merging**
