### PR TITLE
[WIP] add swap in kubelet stats api

### LINKED ISSUE #105021: [KEP-2400] Add swap memory to the Kubelet stats API
#### What would you like to be added:

Add swap memory to the Kubelet stats API so that we have metrics on swap utilization.

- Code changes
- Add e2e coverage

#### Why is this needed:

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta

### PR DESCRIPTION
**Pull request by yxxhero**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Please see https://github.com/kubernetes/kubernetes/issues/105021
#### Which issue(s) this PR fixes:

Fixes #105021
#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/issues/105021
#### Does this PR introduce a user-facing change?

```release-note
add swap in kubelet stats api
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta
```

### CODE REVIEW

**Comment by yxxhero** [comment]
@mengjiao-liu

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Pull request closed without merging**
