### PR TITLE
Removes container RefManager

### PR DESCRIPTION
**Pull request by EricMountain**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:

Originally this change was part of #84792. However, to simplify that PR and get the fix through quicker, it was decided to split it in 2.

NB - This PR is based off #84792 with the expectation it would be merged first.

This cleanup consists in removing the container RefManager as it does not seem to be useful.

The only place the container Refs are used is in the prober, however even there it is optional. Other parts of the code that require Refs such as pkg/kubelet/kuberuntime/kuberuntime_container.go#recordContainerEvent do not make use of the RefManager construct.

Further, RefManager is not fed existing containers when the kubelet restarts, so it holds partial information after a restart.

Travelling back in time to try to understand the reason RefManager was introduced (newest to oldest commits):

This commit moved the RefManager to pkg/kubelet/container so it could be used by other packages (says the log):
https://github.com/kubernetes/kubernetes/commit/9f62b929b885

This commit turned the previous ref manager map into the RefManager:
https://github.com/kubernetes/kubernetes/commit/a06bc964143
"This enables pluggable container runtime to manage the container references."

This commit changes the dockerIDToRef map into generic containerIDToRef map:
https://github.com/kubernetes/kubernetes/commit/027f6854d0f

This commit introduces the dockerIDToRef map:
https://github.com/kubernetes/kubernetes/commit/dcc111bf13d
Comment is: "Start putting event generation into kubelet (not enabled yet)"

The reason for creating this reference manager appears to be "Needed to report events for containers belonging to deleted/modified pods." (https://github.com/kubernetes/kubernetes/commit/dcc111bf13d#diff-bf28da68f62a8df6e99e447c4351122dR116) That comment has since disappeared in the 5 year interim.

Also, the refs are cleared from the map as soon as the containers are deleted, and nowhere other than in the prober was GetRef used other than for checking if the ref existed prior to deleting it.

So I'm not sure what the idea was precisely behind this map, however it wasn't introduced as an afterthought e.g. for performance reasons. It was there, albeit in a different form, from the start.

**Which issue(s) this PR fixes**:

None.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

N/A

### CODE REVIEW

**Comment by matthyx** [comment]
/sig node
/kind bug
Please rebase your PR.

**Review by mattjmcnaughton — COMMENTED** [review]
I think this change makes a lot of sense. I don't see benefit it keeping around an entire rich struct just for this small use case.

I guess the only concern could be if there are unexpected performance concerns with respect to repeatedly generating container events? But I don't foresee probes running frequently enough to produce performance issues. I also agree with you that we don't see any evidence of performance concerns in the Git log.

Curious to hear from others as I said on the original diff.

Adding a hold until the preceding diff is merged. Do you also mind prefixing `[WIP]` to the title, so its clear this diff is not ready to be merged?

Thank you for all your work here!

/hold

**Comment by matthyx** [comment]
@EricMountain if your feature is ready, please change the title to remove WIP, and the label will disappear automatically.

**Comment by EricMountain** [comment]
> @EricMountain if your feature is ready, please change the title to remove WIP, and the label will disappear automatically.

Really the WIP was just to let #84792 go through first, though that isn't really necessary since this PR contains the commit from #84792 also. Hence, removing WIP, good idea thanks.

BTW we've been running this patch on our Datadog clusters for weeks/months now and it works well for us.

**Comment by dims** [comment]
@tedyu does this look good to you as well?

**Comment by tedyu** [comment]
Since @lavalamp was the author for https://github.com/kubernetes/kubernetes/commit/dcc111bf13d#diff-bf28da68f62a8df6e99e447c4351122dR116, he would be in better position to review this.

**Comment by lavalamp** [comment]
The original purpose of this was mapping docker ids to pods, IIRC? Probably to avoid querying the docker api/cli too often? You should get a kubelet owner to review this. I don't know now if it is important for anything. The change sounds reasonable if that's not a necessary thing to track any more.

**Comment by EricMountain** [comment]
@derekwaynecarr / @tallclair would you have an opinion on this?

@derekwaynecarr I think you authored `recordContainerEvent()` that does not use the `RefManager` struct and which I used as a basis for implementing #84792. Hence this proposed cleanup to remove `RefManager` completely.

Thanks!

**Comment by dims** [comment]
/test all

(to get rid of the remake job)

**Comment by dims** [comment]
/hold cancel

let's signal the approvers that this is ready

**Comment by derekwaynecarr** [comment]
I will review this now.  @EricMountain reached out saying this is dead code, and so let me confirm that is the case.

**Comment by derekwaynecarr** [comment]
I cannot precisely recall the historical reason for the refManager, but the refManager did persist a mapping of ContainerID->ObjectRef and all that was unique about the reference manager was that a ContainerID was a tuple of runtimeType/containerID.

Its possible this was done in case we ever supported more than one runtime at a time, which we do not, and any different container runtime options per node are behind the CRI itself now.

/approve
/lgtm

**Pull request merged**
