### PR TITLE
Adds OWNERS file for cluster/juju

### PR DESCRIPTION
**Pull request by lazypower**
**What this PR does / why we need it**: Adds an OWNERS file for the `cluster/juju` directory. This was requested by @mikedanese  over on https://github.com/kubernetes/kubernetes/pull/31736#issuecomment-252391221

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: N/A

**Special notes for your reviewer**: N/A

**Release note**:

``` NONE
```

Inserts @chuckbutler and @mbruzek as reviewers for the juju cluster directory.
Additional assignee of @marcoceppi and @castrojo to help handle overflow.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34393)

### CODE REVIEW

**Comment by mikedanese** [comment]
Need to sign the CLA.

/lgtm

**Comment by chuckbutler** [comment]
Ok, I just submit a CLA auth to the cla/linuxfoundation bot. I'll ping internally tomorrow to see if we have a corp agreement with CNCF here at canonical for this CLA and will move to get my membership amended if we need to do that. 

Thanks @mikedanese

**Comment by mbruzek** [comment]
lgtm

**Comment by mbruzek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34393)*

**Comment by mbruzek** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
Please accept invitations to kubernetes org.

**Comment by chuckbutler** [comment]
@mikedanese I missed my invite in a filter, but have since re-joined. Looks like Matt and I are already listed on the org page. The only holdout is castrojo as he's out on paternity leave. 

Is there a cheat sheet or other helpful listing of what we can do here during the CR cycle with the bots that I can hand off to the team? Mbruzek was scoping it out this morning and cursory google searches didn't yield helpful information. Just a few stray mailing list posts.

Thanks again for helping pilot us into reviewing contributors.

**Pull request merged**
