### PR TITLE
fix apiserver startup check

### PR DESCRIPTION
**Pull request by deads2k**
Startup detection logic was broken.  The integration tests weren't checking it because kube integration works differently that openshift integration. :(

@liggitt You at least knew this existed. ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33852)

### CODE REVIEW

**Comment by liggitt** [comment]
looks ok for now. eventually, I'd like to split ListenAndServe() into `listener := Listen(...)` (running synchronously), and `Serve(listener)`, run inside a goroutine

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #33880

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #33880

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #33880

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #IGNORE

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #IGNORE

**Comment by deads2k** [comment]
got 503 again

**Comment by deads2k** [comment]
@k8s-bot test this: issue #IGNORE

**Pull request merged**
