### PR TITLE
Increase timeout for namespace deletion.

### PR DESCRIPTION
**Pull request by wojtek-t**
From time to time we're observing timeouts on Jenkins in our scalability suite while waiting for namespace deletion.
This is basically because we're deleting objects from by namespace one by one and there is a throttling in controller-manager. Once #10217 is fixed, this should be much faster, but now since:
- Density is producing ~26000 events
- Load capacity is producing ~35000 events
  optimistically deleting the namespace is taking ~20 and ~30 minutes respectively.
  
  Thus I'm increasing this timeout to 60 minutes to fix the flakes.

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
This is so sad it takes more than 30 minutes to delete it! How about we delete events manually from the test code (I believe we can change rate limit for the client in the test) to decrease deletion time. WDYT?

**Comment by wojtek-t** [comment]
@fgrzadkowski - we can do it, but after more thinking about it, I don't agree:
- adding more complicated code, is not expected just before 1.0
- increasing timeout is an extremely simple change
- I'm going to fix it properly right after 1.0
 Thus I think we should just increase the timeout for now.

**Comment by wojtek-t** [comment]
cc @davidopp

**Comment by fgrzadkowski** [comment]
I'm not insisting, but the new code would be only in test, so it's not that bad.

**Comment by wojtek-t** [comment]
I think it's much easier to leave as is for now.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
LGTM

This is a test-only change, so no additional reviews needed.

**Comment by quinton-hoole** [comment]
This just all looks terribly wrong (not this particular PR, but the code around it).  Note to myself to understand it properly and fix it up soon.  Specifically:

1. The function deleteTestingNS() does nothing of the sort.  It just polls until all namespaces with some magic prefix are not in deleting state.  It would seem that that simply doesn't work if there are parallel test runs in flight.
2. If the comments in this PR are true, then we're deleting the contents of namespaces in a rather bizirre way.  I'd like to understand that.
3. Having namespace deletion take up to 60 minutes to complete is simply untenable in automated tests. Isn't this called for every test invocation?  Or perhaps it's once per test run.  Either way, it's way too long.

Q

**Comment by wojtek-t** [comment]
@quinton-hoole -  the rationale behind deleteTestingNS is as following:
- deleting namespace happens in the background
- deleting namespace after scalability tests can take more than half an hour
- deleteTestingNS is used only in scalability tests (and shouldn't be used anywhere else)
- the reason why we are using it, because deleting namespace in the background is affecting metrics of the currently running test

 How this should be done in the future:
- once we the namespace can be deleted fast (within seconds) - #7372 should solve that problem, at the end of scalability tests we should just wait until their namespace is fully deleted

**Pull request merged**
