### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by yarntime**
fix typos.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by yarntime** [comment]
Hi @quinton-hoole , it seems all tests have been passed, could you please help me to merge this pr and #38352? thanks.

**Comment by quinton-hoole** [comment]
Sure, thanks @yarntime

**Comment by quinton-hoole** [comment]
I think that this should auto-merge some time soon.  If not, feel free to ping me to address that.

**Comment by deads2k** [comment]
next time, it's probably worth combining https://github.com/kubernetes/kubernetes/pull/38352 and https://github.com/kubernetes/kubernetes/pull/38094 since they're both small and closely related.

**Comment by yarntime** [comment]
@quinton-hoole, @deads2k, ok, i get it. thank you very much.

**Comment by quinton-hoole** [comment]
Re-adding LGTM.

**Pull request merged**
