### PR TITLE
fix typo for federation/*

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**: fix typo for federation/*

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: small contribution :D

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by nikhiljindal** [comment]
lgtm, thx!
Did you use some tool to fix these or are these manual fixes?

**Comment by nikhiljindal** [comment]
verify-openapi failed. You also need to update the generated openapi spec

**Comment by aaron12134** [comment]
@k8s-ci-robot ok to test

**Comment by nikhiljindal** [comment]
@aaron12134 Why close this?

**Comment by xulike666** [comment]
@nikhiljindal I ran the ./hack/verify-federation-openapi-spec.sh but failed unexpectedly on the kubernetes/kubernetes@master branch.

**Pull request closed without merging**
