### PR TITLE
fix: unnecessary fmt.Sprintf in assertions

### PR DESCRIPTION
**Pull request by jdtuhui**
#### What type of PR is this?

/area test
/kind cleanup
/sig testing

#### What this PR does / why we need it:

Code simplification， and Unnecessary fmt.Sprintf in assertions

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/ok-to-test

**Review by jayeshmahajan — APPROVED** [review]

**Comment by bart0sh** [comment]
/lgtm

/assign @SergeyKanzhelev @mrunalp 
for approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
