### PR TITLE
Automated cherry pick of #16478 upstream release 1.1

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #16478 upstream release 1.1

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by davidopp** [comment]
LGTM

I guess you are confident the tests will pass on the original PR? Or did you want me to wait until the original PR merges?

**Comment by mikedanese** [comment]
@davidopp I'm starting on the list of things we need to cherry-pick :) we can leave until the original goes in but might as well prepare it

**Comment by davidopp** [comment]
OK sounds good, I'll wait to add the LGTM label until the original PR merges.

**Comment by davidopp** [comment]
I manually merged #16478 so that we can at least get this into the queue. Labeling LGTM now.

**Pull request merged**
