### PR TITLE
Move the sig-instrumentation test to a dedicated folder

### PR DESCRIPTION
**Pull request by crassirostris**
Move the last remaining test to sig-instrumentation folder, also move "metrics" package to the "framework" folder

Related issue: https://github.com/kubernetes/kubernetes/issues/49161

/cc @xiangpengzhao @piosz

### CODE REVIEW

**Comment by crassirostris** [comment]
@gmarek @spxtr Could you please approve?

**Comment by xiangpengzhao** [comment]
Thanks @crassirostris!  Task list https://github.com/kubernetes/kubernetes/issues/49161#issuecomment-320502371 updated. This PR lgtm. Other folks confirm please.

**Comment by crassirostris** [comment]
Thanks!

**Pull request merged**
