### PR TITLE
Fix sending an empty update when the source is ready

### PR DESCRIPTION
**Pull request by yujuhong**
/cc @Random-Liu

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
A minor change to fix the unit test.

**Comment by yujuhong** [comment]
Re-applied the lgtm label since it's a minor change to appease the unit test.

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by Random-Liu** [comment]
LGTM

**Comment by yujuhong** [comment]
This is a bug fix for reliability. Added to v1.2 candidate.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
