### PR TITLE
migrate kube-proxy metrics to stability framework

### PR DESCRIPTION
**Pull request by logicalhan**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR migrates kube-proxy metrics to the [metrics stability framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-stability-migration.md). 

**Does this PR introduce a user-facing change?**:
```release-note
Kube-proxy metrics are now marked as with the ALPHA stability level.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[KEP - Metrics Stability Migration]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-stability-migration.md
```

### CODE REVIEW

**Comment by logicalhan** [comment]
/uncc @kubernetes/dep-approvers @caseydavenport @brendanburns

**Review by andrewsykim — COMMENTED** [review]
Minor comments, lgtm otherwise

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
