### PR TITLE
devel/ tree additional minor edits

### PR DESCRIPTION
**Pull request by mikebrow**
Address line wrap issue #1488. Also cleans up other minor editing issues in the docs/devel/\* tree such as spelling errors, links,...

Signed-off-by: Mike Brown brownwm@us.ibm.com

### CODE REVIEW

**Comment by smarterclayton** [comment]
ok to test

**Comment by mikebrow** [comment]
rebased...

**Comment by mikebrow** [comment]
rebased

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
