### PR TITLE
fix image manager Start() function return

### PR DESCRIPTION
**Pull request by NickrenREN**
realImageGCManager's Start()  function will always return nil,we do not need the err return value,drop it.

### CODE REVIEW

**Comment by NickrenREN** [comment]
@dims  @dchen1107   Could one of you help ask the bot to test ?Thanks

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@feiskyer   k8s-bot  does not test ?

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@feiskyer Thanks a lot. Sorry to bother you.  Checks passed. Could you help with the review ?

**Comment by feiskyer** [comment]
LGTM

**Comment by NickrenREN** [comment]
@feiskyer @resouer Could you help add release-note-label  and lgtm label ? thanks

**Comment by resouer** [comment]
@feiskyer Sorry, but this actually changed the interface, so I need a confirmation that is this 100% OK from your side?

**Review by feiskyer — APPROVED** [review]
@resouer It is ok, since it never out even on errors (reporting errors by logs instead)

**Pull request merged**
