### PR TITLE
Bump npd from v0.8.16 to v0.8.18

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
[change log about v0.8.18](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.18)
#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
Waiting for https://github.com/kubernetes/k8s.io/pull/6523

**Comment by wangzhen127** [comment]
NPD v0.8.17 has been released.

**Comment by bzsuni** [comment]
cc @pacoxu

**Comment by pacoxu** [comment]
Code freeze will be end until v1.30 release(planned in April 17th).

**Comment by wangzhen127** [comment]
We just released NPD v0.8.18 and you can skip v0.8.17 now. See https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.18.

/hold

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by bzsuni** [comment]
Hi @liggitt  
for approval

**Comment by liggitt** [comment]
should we keep bumping this here, or should we drop it out of the cluster directory? unless tests depend specifically on that, shouldn't we start trimming things out of the cluster dir (which only exists for CI at this point)

**Comment by pacoxu** [comment]
> unless tests depend specifically on that, shouldn't we start trimming things out of the cluster dir (which only exists for CI at this point)

As I know, the ci-kubernetes-e2e-gce-cos-k8sstable1-default	is using the NPD(https://github.com/kubernetes/kubernetes/issues/121973 is a related flake for npd v0.8.13, fixed in v0.8.16+).
- https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sstable1-default
- https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-default

> **NOTE: This is a bad release because the container image and tar files do not match. And we could not fix it because registry.k8s.io do not allow tag mutation (https://github.com/kubernetes/k8s.io/pull/6522). Please use v0.8.17 instead, which is tagged to the same commit as v0.8.16.**

I prefer to bump this time for the release note in NPD https://github.com/kubernetes/node-problem-detector/releases.

See https://github.com/kubernetes/kubernetes/issues/122118 for context.

> should we keep bumping this here?

No. Only when there are some reason that we have to.

> should we drop it out of the cluster directory?

Probably yes.

**Comment by wangzhen127** [comment]
> I prefer to bump this time

+1 to bump the NPD version in k/k to a known good version.

**Pull request closed without merging**
