### PR TITLE
fix error flag in changlog

### PR DESCRIPTION
**Pull request by lojies**
**What type of PR is this?**
Flag --enable-profiling=false in changelog is error.This should be --profiling=false.

**What this PR does / why we need it**:
```
Usage:
  kube-controller-manager [flags]

Debugging flags:

      --contention-profiling   Enable lock contention profiling, if profiling is enabled
      --profiling              Enable profiling via web interface host:port/debug/pprof/ (default true)

```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/kind documentation
/priority important-soon
/ok-to-test
/release-note-none
/lgtm

/cc @deads2k

**Comment by lojies** [comment]
@deads2k @justaugustus @hoegaarden

**Pull request merged**
