### PR TITLE
move api server no kube dep packages

### PR DESCRIPTION
**Pull request by deads2k**
Simple moves, see commit titles.  I did not move the source of the generated swagger, I simply change the destination of the script.  I'm ok building a little debt to complete the move.

@sttts

### CODE REVIEW

**Comment by deads2k** [comment]
approved based on https://github.com/kubernetes/kubernetes/issues/40363

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
@sttts I pulled endpoints/openapi from the list.  it isn't generic, it's got a bunch of hardcoded types in it.

**Comment by deads2k** [comment]
> @sttts I pulled endpoints/openapi from the list. it isn't generic, it's got a bunch of hardcoded types in it.

According to @mbohlool the package was never intended to be generic.  I'd say move it to `kubeapiserver`, eliminate the default, and open an issue to provide some reasonable default implementation for @mbohlool.  I think people would want to provide a scheme (or something similar) and get working docs out.

**Comment by deads2k** [comment]
Bump bot

**Comment by mbohlool** [comment]
I will send a PR to move the function using those hard-coded types out of endpoints/openapi. The rest should be generic.

**Pull request merged**
