### PR TITLE
Revert pr 127400 due to regression

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind regression

#### What this PR does / why we need it:
Revert https://github.com/kubernetes/kubernetes/pull/127400 due to regression discovered in https://github.com/kubernetes/kubernetes/pull/127302
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

is there a test that can catch the regression we can merge as a follow-up?

**Comment by sttts** [comment]
@cici37 thanks for finding the issue. Will look into a similar solution as in https://github.com/kubernetes/kubernetes/pull/127504 for sharing through explicit wiring. That's definitely the better solution.

**Pull request merged**
