### PR TITLE
Initial v1 doc commit to gh-pages

### PR DESCRIPTION
**Pull request by krousey**
Basically I just copied from head, stripped the versioning information, added layouts, and then rewrote links.

### CODE REVIEW

**Comment by krousey** [comment]
cc @thockin @erictune @bgrant0607 

Have at it. I recommend looking at individual commits since the initial copy is bulky.

**Comment by krousey** [comment]
#11344

**Comment by thockin** [comment]
Now that I have context from Kris and Richie, LGTM

**Comment by thockin** [comment]
merging to make progress

**Pull request merged**
