### PR TITLE
API Machinery: Add equal func for Requirement struct

### PR DESCRIPTION
**Pull request by gavinfish**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Add Equal func for `Requirement` struct. This is useful when we need compare `Requirement` and `Selector` with cmp lib.

#### Which issue(s) this PR fixes:

Xref #94696

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Curious in what respects cmp.Equal works better than reflect.DeepEqual for internalSelector? Can you make an example?

Anyway, this PR looks good.

/lgtm
/approve

**Comment by gavinfish** [comment]
> Curious in what respects cmp.Equal works better than reflect.DeepEqual for internalSelector? Can you make an example?
> 
> Anyway, this PR looks good.
> 
> /lgtm
> /approve

For internalSelector, there is no big difference since all fields matter. But for other structs holding Selector(internalSelector) as a field, we need use `AllowUnexporterted` (most time this is not what we want as it acts similarly as reflect.DeepEqual) option or deliberately implement an `Equal` func dealing with Selector when we use cmp lib.

**Pull request merged**
