### PR TITLE
fix token validation in kubeadm

### LINKED ISSUE #157: badly formated --discovery flag value causes a panic
Something like
```
kubeadm join --skip-preflight-checks --discovery=token://81b2b0:c6c1cbd142c77d4c@ 172.31.0.157 :9898
```

or 
```
kubeadm join --skip-preflight-checks --discovery=token://81b2b0:c6c1cbd142c77d4c 
```

results in this:
```
[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x18e5d20, 0xc42000e070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/cmd/kubeadm/app/node.RetrieveTrustedClusterInfo(0xc4203a3480, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/node/discovery.go:36 +0xa6d
k8s.io/kubernetes/cmd/kubeadm/app/discovery.runTokenDiscovery(0xc4203a3480, 0xc4202e1530, 0xc4202e1530, 0xc4205f5b98)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:72 +0x54
k8s.io/kubernetes/cmd/kubeadm/app/discovery.For(0x0, 0x0, 0xc4203a3480, 0x5ce4e9, 0x18eeb00, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:39 +0x50
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*Join).Run(0xc42008a198, 0x25a8d00, 0xc420022010, 0x2, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:134 +0x59
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1(0xc42014fb00, 0xc4203a3400, 0x2, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:70 +0xf3
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42014fb00, 0xc4203a33c0, 0x4, 0x4, 0xc42014fb00, 0xc4203a33c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42014f440, 0xc42014fd40, 0xc42014fb00, 0xc42014f680)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42014f440, 0xc42033aed0, 0x25a8cc0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc4205f5f50, 0xc4200001a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:35 +0xe8
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:26 +0x22
```

### PR DESCRIPTION
**Pull request by xilabao**
fix https://github.com/kubernetes/kubeadm/issues/157

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot ok to test

**Comment by errordeveloper** [comment]
This is good, but please also add a slice length check [where the slice is accessed](https://github.com/kubernetes/kubernetes/blob/f17a5d38c2b5d68c4e73e57795447ab50e2a40ce/cmd/kubeadm/app/node/discovery.go#L36).

**Comment by xilabao** [comment]
Thank you for your remind! PTAL @errordeveloper

**Comment by luxas** [comment]
@xilabao You need to fix the bazel test, otherwise lgtm

**Review by errordeveloper — APPROVED** [review]
/lgtm

**Comment by xilabao** [comment]
@k8s-bot bazel test this unit test this

**Comment by luxas** [comment]
@xilabao Please fix the build:
```
cmd/kubeadm/app/node/discovery.go:37: cannot use false (type bool) as type *kubeadm.ClusterInfo in return argument
```

**Comment by xilabao** [comment]
@k8s-bot verify test this

**Comment by luxas** [comment]
> W0212 19:03:14.804] cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go:32: k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.TokenDiscovery composite literal uses unkeyed fields
W0212 19:03:14.804] cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go:33: k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.TokenDiscovery composite literal uses unkeyed fields
W0212 19:03:14.804] cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go:34: k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.TokenDiscovery composite literal uses unkeyed fields
W0212 19:03:14.813] cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go:35: k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.TokenDiscovery composite literal uses unkeyed fields

As soon as this passes, this PR LGTM

**Comment by luxas** [comment]
/lgtm
/approve

Thanks a lot @xilabao!

**Pull request merged**
