### PR TITLE
adds nav for K8S on DCOS solution/blueprint

### PR DESCRIPTION
**Pull request by mhausenblas**
@jeffmendoza @briandorsey this is the second part of the K8S on DCOS solution/blueprint init. As discussed and agreed, it adds a step to `gettingstarted.md`. See also PR https://github.com/GoogleCloudPlatform/kubernetes/pull/7287

### CODE REVIEW

**Comment by mhausenblas** [comment]
Concerning the CLA, please refer to the corporate Mesosphere Inc. one.

**Comment by jeffmendoza** [comment]
LGTM, needs #7287 merged first.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
I'm going to close this since #7287 was closed.

**Pull request closed without merging**
