### PR TITLE
kubelet: fix ip reporting for downward api

### LINKED ISSUE #79693: podIP = "" for hostNetwork pod
**What happened**: `status.podIP` is unset on a `hostNetwork: true` networking daemonset pod used by [kind](https://sigs.k8s.io/kind) (read via the downward api). Previously this was reliably set to match the hostIP.

**What you expected to happen**: This should be the hostIP (which is set).

**How to reproduce it (as minimally and precisely as possible)**: We know the kind CI tests cover this https://testgrid.k8s.io/conformance-kind#kind,%20master%20(dev)%20%5Bnon-serial%5D&show-stale-tests=&width=5

**Anything else we need to know?**: This is also tracked in https://github.com/kubernetes-sigs/kind/issues/679, we observed this change in https://github.com/kubernetes/kubernetes/compare/4b3987d0c...a33840e02

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by khenidak**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fixes https://github.com/kubernetes/kubernetes/issues/79693

Fixes #
#79693

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the quick fix. This really needs a test that would have caught this

**Comment by aojea** [comment]
agree with @liggitt , I think that the best way to test this is with an e2e test based on the comment in previous line.

What about something like this?

```
diff --git a/test/e2e/common/downward_api.go b/test/e2e/common/downward_api.go
index 13814bfdaf..3c12e5deb3 100644
--- a/test/e2e/common/downward_api.go
+++ b/test/e2e/common/downward_api.go
@@ -19,7 +19,7 @@ package common
 import (
        "fmt"
 
-       "k8s.io/api/core/v1"
+       v1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/api/resource"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/util/uuid"
@@ -227,8 +227,10 @@ var _ = ginkgo.Describe("[sig-node] Downward API", func() {
                expectations := []string{
                        "POD_UID=[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}",
                }
-
-               testDownwardAPI(f, podName, env, expectations)
+               hostNetwork := false
+               testDownwardAPI(f, podName, hostNetwork, env, expectations)
+               hostNetwork = true
+               testDownwardAPI(f, podName, hostNetwork, env, expectations)
        })
 })
 
:...skipping...
diff --git a/test/e2e/common/downward_api.go b/test/e2e/common/downward_api.go
index 13814bfdaf..3c12e5deb3 100644
--- a/test/e2e/common/downward_api.go
+++ b/test/e2e/common/downward_api.go
@@ -19,7 +19,7 @@ package common
 import (
        "fmt"
 
-       "k8s.io/api/core/v1"
+       v1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/api/resource"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/util/uuid"
@@ -227,8 +227,10 @@ var _ = ginkgo.Describe("[sig-node] Downward API", func() {
                expectations := []string{
                        "POD_UID=[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}",
                }
-
-               testDownwardAPI(f, podName, env, expectations)
+               hostNetwork := false
+               testDownwardAPI(f, podName, hostNetwork, env, expectations)
+               hostNetwork = true
+               testDownwardAPI(f, podName, hostNetwork, env, expectations)
        })
 })
 
@@ -307,7 +309,7 @@ var _ = framework.KubeDescribe("Downward API [Serial] [Disruptive] [NodeFeature:
 
 })
 
-func testDownwardAPI(f *framework.Framework, podName string, env []v1.EnvVar, expectations []string) {
+func testDownwardAPI(f *framework.Framework, podName string, hostNetwork bool, env []v1.EnvVar, expectations []string) {
        pod := &v1.Pod{
                ObjectMeta: metav1.ObjectMeta{
                        Name:   podName,
@@ -332,6 +334,7 @@ func testDownwardAPI(f *framework.Framework, podName string, env []v1.EnvVar, ex
                                        Env: env,
                                },
                        },
+                       HostNetwork:   hostNetwork,
                        RestartPolicy: v1.RestartPolicyNever,
                },
        }
```

**Comment by yujuhong** [comment]
/lgtm
/approve

please add a test

**Comment by aojea** [comment]
@yujuhong please check if this is valid #79751

**Comment by kcmartin** [comment]
@ khenidak Do you think that we can add release notes for this PR?

It would be awesome if we could state all user-facing changes within the release-notes block.

**Comment by kcmartin** [comment]
@khenidak Hi--following up for sig-release on my request above -- where are we at with getting user-facing changes into the release-notes block? Thanks!

https://github.com/kubernetes/kubernetes/pull/79700#issuecomment-511699395

**Comment by BenTheElder** [comment]
I don't think this is user facing, this puts the behavior back to what it was previously, and I don't think the broken behavior was in any release.

**Pull request merged**
