### PR TITLE
fix: do not delete the lb that does not exist

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

fix: do not delete the lb that does not exist

#### Which issue(s) this PR fixes:

Fixes #
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/860

#### Does this PR introduce a user-facing change?

```release-note
fix: do not delete the lb that does not exist
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/priority critical-urgent
/triage accepted
/sig cloud-provider
/area provider/azure
cc @feiskyer

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by cheftako** [comment]
> fix: do not delete the lb that does not exist
I think this should read "fix: do not call delete for a lb that does not exist"

**Pull request merged**
