### PR TITLE
Periodic runner in iptables KubeProxy

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #41030

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin - I added the second commit, but I'm not sure if we want to do it like this. Can you PTAL?

**Comment by wojtek-t** [comment]
I found & fixed one issue - now tests should be passing.
@thockin - PTAL

**Comment by thockin** [comment]
I have a branch I never pushed wherein I was revamping the PeriodicRunner to be simpler and better documented.  I did look at your port - let me see if I can blend them or else discard my uncommitted changes.

**Comment by thockin** [comment]
This still doesn't do the right thing in the face of no-op updates, such as endpoints for master leases.

Each Endpoint update triggers OnEndpointsUpdate(), which calls CallFunction(), which consumes a token.  We need to check whether the endpoint actually did anything meaningful BEFORE we CallFunction().  To do that we need to compare to `serviceMap`, which requires the lock be held.  But the lock can't be held across calls to CallFunction() because it has to run async.  Well, it will just be a race, so I guess not a big deal - sometimes the function will be called when it is not needed.

So what I am thinking, though I am out of time for tonight probably, is this:

Break the body of mergeService() into serviceChanged(), which returns old and new *ServiceInfo but does not actually update the map.  mergeService() then calls serviceChanged(), and if !equal, writes into the map.

OnServicesUpdate() and friends can check serviceChanged() and save the change only if it changed.  That needs the lock for serviceMap.  Even better might be to fast-loop through old and new and short-circuit as soon as anything changed, saving the change.  If nothing has changed, do not save.

Endpoints seems even easier.  endpointsToEndpointsMap() on old and new, and save the change if the results are not the same (which is what updateEndpointsMap does anyway).

That way we know that syncProxyRules is only called if we REALLY believe it is needed (I guess you might have deleted and added a service which makes a no-op but that seems like a corner case that doesn't matter).  We can get rid of reasons entirely, and get rid of the early-return cases that use reason codes.  calling syncProxyRules() really means to call it.  Adding the rate limiter is much easier then.

I still want to revamp the limiter to make it simpler.

**Comment by thockin** [comment]
WIP, not tested, just a piece of it:  https://github.com/kubernetes/kubernetes/compare/master...thockin:proxy-periodic-runner-2?expand=1

**Comment by wojtek-t** [comment]
@thockin - thanks a lot for taking a look. I think that what you wrote makes perfect sense. I'm happy to help with it, though since you already started doing this, I don't want to step on your toes. So let me know if you want me to take this from you.

**Comment by wojtek-t** [comment]
Actually, I looked again into the PR that you started and now I'm not 100% convinced that it is a good way to proceed.

 In particular, storing proxyEndpointsMap instead of *api.Endpoints in endpointsChange.
If there will be more than one update to Endpoints object between calling this updateEndpointsMap function, we would unnecessarily call DeepEqual for them on every update.
To clarify, if we Endpoints changes n times: E0 -> E1 -> ... -> En (and assume that all of those are valid updates), then in your approach we are computing endpointsToEndpointsMap and DeepEqual on every single step of those (so n times each). In my approach, we are computing endpointsToEndpointsMap and DeepEqual exactly once for the end state.

 So we're only doing it to get the information faster to not unnecessarily "loose" a token for rate-limiter.

 So maybe the pattern should be different. What i have in mind (which needs to be thought through more carefully) is:
1. we are leaving structures as they are now
2. each On* handler is calling prepareForSyncProxyRules function
3. prepareForSyncProxyRules is as following:
```
func prepareForSyncProxyRules() {
  1. check if we have a chance to get a token, if not, return
  2. merge the change maps to see if something changed, if not return
  3. call syncProxyRules
}
```

Or do you think it's overcomplication?

**Comment by thockin** [comment]
I think this is still a race.

>  1. check if we have a chance to get a token, if not, return

1.5. periodic timer fires and consumes token 

>  2. merge the change maps to see if something changed, if not return
>  3. call syncProxyRules

3.1. fail to get token, defer, but now stored state has changed.

Am I misunderstanding?

**Comment by wojtek-t** [comment]
We can block other threads from consuming it for example.

Yeah - I didn't want to say that there is no race. The question is how often it would happen and how much those races hurt us - these are not correctness issues - it's just about propagation time. 
I'm not saying it's fine to have those, though - just thinking loudly.

**Comment by wojtek-t** [comment]
@thockin - another thought. We are trying to avoid calling "syncProxyRules" if the update is actually "no-op" update. This is understandable in case of endpoints (since we have leader election based on them). But maybe we don't have to worry at all about services (and optimistically assume that when service changes, it really changes :-))

That would make the whole proposal you described in: https://github.com/kubernetes/kubernetes/pull/45343#issuecomment-300992580 easier to implement since we don't care about services part. The optimization I was trying to make is probably overcomplication when I'm thinking more about it. And if the service change is no-op change, well, we will loose a tocken, but that shouldn't happen often.

WDYT?

**Comment by thockin** [comment]
I thought about that - just doing the pre-check for endpoints, since we know that is a pain point.  I guess that is feasible, but it's sort of unsatisfying.

**Comment by thockin** [comment]
I'm still looking at how to do Services cleanly.  It looks like a lot of the logic in mergeService is to get better log messages.  I am leaving town in a couple hours, and I won't be back until late Monday.  Feel free to run with this, if you're itching to do it.  If we can get to a place where syncProxyRules doesn't early-return at all, that would be ideal, but I guess I would probably accept just endpoints.

I'll try to finish the more-async, simpler runner.  The above is really the pre-requisite.

**Comment by wojtek-t** [comment]
> I'm still looking at how to do Services cleanly. It looks like a lot of the logic in mergeService is to get better log messages. I am leaving town in a couple hours, and I won't be back until late Monday. Feel free to run with this, if you're itching to do it. If we can get to a place where syncProxyRules doesn't early-return at all, that would be ideal, but I guess I would probably accept just endpoints.

@thockin - I opened #45816 for it - we will need some minor changes on top of this, but this is already detecting whether services and endpoints changed or not. This should solve all the problems already mentioned above.

**Comment by wojtek-t** [comment]
@thockin - it rebased this PR on top of the other just to see if everything works fine. But please review just #45816

**Comment by thockin** [comment]
Closing because of all the other PRs.

**Pull request closed without merging**
