### PR TITLE
Set node-env map parser to nil if an empty string is passed

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

I introduced a bug in #119513 because node-env is a map of strings. This should fix it.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/pull/119578

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @dims @chendave

### CODE REVIEW

**Comment by upodroid** [comment]
/test pull-kubernetes-node-e2e-containerd-kubetest2

This identical to the test that was failing

**Comment by upodroid** [comment]
Can you add the milestone as well pls?

**Comment by dims** [comment]
/milestone v1.28

test only change to fix broken CI job

**Pull request merged**
