### PR TITLE
Typo fix: binded -> bound

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:

The word 'binded' does not exist in fact, so I replaced it with the correct word 'bound'. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the typo fix @Zhuzhenghao 
/lgtm
/approve
/ok-to-test
/priority backlog
/assign @oomichi

**Comment by neolit123** [comment]
@Zhuzhenghao typo fixes need to wait after 1.16 is released, we are in code freeze.

**Comment by oomichi** [comment]
> @Zhuzhenghao typo fixes need to wait after 1.16 is released, we are in code freeze.

Yes, right.
We need to wait at this time.
Please cancel the `/hold` after releasing v1.16.

/approve
/hold

**Comment by oomichi** [comment]
as https://kubernetes.slack.com/archives/C2C40FMNF/p1567190475094100

/hold cancel
/retest

**Comment by neolit123** [comment]
/lgtm cancel
we can mere this after code freeze ~10th of Sep.

**Review by yastij — COMMENTED** [review]
/lgtm

as code freeze ends tomorrow

**Pull request merged**
