### PR TITLE
Fix that fails to resize pvc of cinder volume.

### LINKED ISSUE #66705: Openstack: Fill size attribute for the V3 API volumes
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
#56829 patched out the Size field (was added PR #58685), it will cause issue #66687 again.
See also [9326e84#diff-c6603a39b8f63223075a6ac640bd6ef9R235](https://github.com/kubernetes/kubernetes/commit/9326e845e48e2cc61f57094bd7561e37fb831ce5#diff-c6603a39b8f63223075a6ac640bd6ef9R235) and #66687.

**What you expected to happen**:
PVC resizes of Cinder volumes successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by xiaoxubeii**
**What this PR does / why we need it**:
Fix that fails to resize pvc of cinder volume. See also #66687.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66705

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dims — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@xiaoxubeii can you please submit the same change to https://github.com/kubernetes/cloud-provider-openstack as well?

**Comment by xiaoxubeii** [comment]
@dims OK, i will commit.

**Pull request merged**
