### PR TITLE
fix the format for github error

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
It has nothing with any logic process. It just affect github refresh.

Every time I refresh (rebase and push master branch) on my own repo for K/K
it occurs
```shell
The page build failed for the `master` branch with the following error:

The variable `{{ pillar['federations_domain_map'] }` on line 486 in `CHANGELOG-1.3.md` was not properly closed with `}}`. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
ping @brendanburns 
PTAL

**Comment by bgrant0607** [comment]
@zhangxiaoyu-zidif what are you changing?

**Comment by bgrant0607** [comment]
Oh, nevermind. Missing curly.
Thanks.
/lgtm
/approve

**Pull request merged**
