### PR TITLE
Add CPUManager policy option to distribute CPUs across NUMA nodes instead of packing them

### PR DESCRIPTION
**Pull request by klueska**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR implements the logic describe in [KEP-2902](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2902-cpumanager-distribute-cpus-policy-option).

It adds a new `CPUManager` policy option called `distribute-cpus-across-numa` to the static `CPUManager` policy. When enabled, this will trigger the `CPUManager` to evenly distribute CPUs across NUMA nodes in cases where more than one NUMA node is required to satisfy the allocation.

#### Does this PR introduce a user-facing change?

```release-note
Add a new `distribute-cpus-across-numa` option to the static `CPUManager` policy. When enabled, this will trigger the `CPUManager` to evenly distribute CPUs across NUMA nodes in cases where more than one NUMA node is required to satisfy the allocation.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2902-cpumanager-distribute-cpus-policy-option
```

### CODE REVIEW

**Comment by klueska** [comment]
/cc @fromanirh @swatisehgal 

The core algorithm hasn't been implemented yet, but the base infrastructure is now in place.

Please take note of:
> This PR currently includes changes from #102015 which have not been merged yet. Please ignore the overlapping commits from this PR when reviewing.

**Comment by klueska** [comment]
@fromanirh @swatisehgal 
Added logic to implement the algorithm itself. Tests to come next.

**Review by swatisehgal — COMMENTED** [review]
Took a first pass, will do a deeper review of the algorithm in the coming days.

**Review by ffromani — COMMENTED** [review]
very nice PR. Mostly minor, non-blocking (more like notes for future cleanups) comments inline.
I like the algorithm to spread cores across NUMA zones, looks good so far, but I want to spend more time properly processing it.

**Review by ffromani — COMMENTED** [review]
again a batch of minor comments, mostly for future cleanups (when we move to beta or so). The algorithm itself is nicely written and very nicely commented. I want to review the tests carefully today/tomorrow, and if everything goes as I expect, I'll add my LGTM.

**Pull request merged**
