### PR TITLE
Revert #16840 and #16902 in 1.1 release (used for debugging watch issues)

### PR DESCRIPTION
**Pull request by wojtek-t**
@davidopp @brendandburns @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@lavalamp - can I apply "lgtm" label based on your LGTM?

**Comment by davidopp** [comment]
This claims to revert #16902 but it doesn't seem to do that, only #16840

**Comment by wojtek-t** [comment]
@davidopp - this doesn't revert the "framework" added in #16902 but it does remove using it. So it is effectively reverting #16902 from production code.

**Comment by davidopp** [comment]
Ah OK.

**Pull request merged**
