### PR TITLE
fix typo heathcheck in kubeadm generated file

### PR DESCRIPTION
**Pull request by icheikhrouhou**
fix typo found in generated files in Docs.
/assign @neolit123

### CODE REVIEW

**Review by draveness — APPROVED** [review]
/release-note-none
/priority backlog
/ok-to-test
/lgtm

**Review by draveness — COMMENTED** [review]
/kind documentation

**Review by neolit123 — COMMENTED** [review]
thanks @icheikhrouhou 
/lgtm
/approve

**Pull request merged**
