### PR TITLE
Add volume mode downgrade test: should not mount/map in <1.13

### PR DESCRIPTION
**Pull request by wongma7**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: The downgrade test added in https://github.com/kubernetes/kubernetes/pull/71167 is not running, because a downgrade test from 1.13->1.12 runs the tests in the 1.12 branch, and the test was only merged to 1.13. So here I would like to merge it into the 1.12 branch.

upgrade test, the test runs and is skipped, as expected
https://testgrid.k8s.io/sig-cluster-lifecycle-upgrade-skew#gce-1.12-1.13-upgrade-cluster
downgrade test, the test does not exist since it's not in 1.12 branch
https://testgrid.k8s.io/sig-cluster-lifecycle-upgrade-skew#gce-1.13-1.12-downgrade-cluster

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**: this is a partial cherry-pick of https://github.com/kubernetes/kubernetes/pull/71167

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
/sig storage
/assign @msau42 

Would like to get this test running, somehow neglected/forgot to check that it was. Then I can maybe add some more checks to it as part of https://github.com/kubernetes/kubernetes/issues/76044

**Comment by feiskyer** [comment]
/ok-to-test

@liggitt Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.

/assign @liggitt

**Comment by cblecker** [comment]
Previously reviewed/approved in https://github.com/kubernetes/kubernetes/pull/71167/commits/bee759b925e16e97e66881838b56fb1199cd5c6b in https://github.com/kubernetes/kubernetes/pull/71167

/approve

**Pull request merged**
