### PR TITLE
Adding e2e test for federation replicasets

### PR DESCRIPTION
**Pull request by nikhiljindal**
Its a basic test which tests that we can create and delete replicasets. Will enhance it when we write the replicaset controller.

cc @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30423)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @jianhuiz @mwielgus

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by nikhiljindal** [comment]
@mwielgus This is a simple test for verifying that replicasets can be created and deleted with federation-apiserver. This verifies the API code.

Once we have the controller, we can build on this to add more use cases for the controller.
PTAL

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by nikhiljindal** [comment]
@mwielgus Can you please take a look?

The test is same as our other tests (federation-event, federation-secret)

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
