### PR TITLE
fix: update WithDiscoveryQPS method description

### PR DESCRIPTION
**Pull request by davidebianchi**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix a method documentation

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

**Comment by davidebianchi** [comment]
Right sorry, I signed it

**Review by brianpursley — APPROVED** [review]
/lgtm

**Pull request merged**
