### PR TITLE
genericapiserver: cut off more dependencies – episode 5

### PR DESCRIPTION
**Pull request by sttts**
Follow-up of https://github.com/kubernetes/kubernetes/pull/40658

Left for episode 6:
- pkg/storage/etc
- pkg/storage/etc3
- pkg/storage/storagebackend/factory

approved based on #40363

### CODE REVIEW

**Comment by deads2k** [comment]
```
conversion-gen: add vendor package support - lgtm
pkg/api/testing: cut off fuzzers from static codecs - lgtm
pkg/genericapiserver/endpoints: cutting off pkg/api deps - lgtm
k8s.io/apiserver: add example api group - dear lord that took a lot of work.  lgtm
pkg/genericapiserver/registry/rest: cut off pkg/api dependency - lgtm
pkg/genericapiserver/registry/rest/resttest: cut off pkg/api dependency - lgtm
```

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Comment by deads2k** [comment]
@sttts looks like the bazel failure may be real for once: TestDeepCopyApiObjects

**Comment by sttts** [comment]
@deads2k fixed it. wrong GroupVersion for the `TestCodec`.

**Comment by deads2k** [comment]
> vendor/BUILD

noooooooo

**Comment by smarterclayton** [comment]
That was a good Luke Skywalker impression

On Feb 1, 2017, at 8:25 PM, Kubernetes Submit Queue <
notifications@github.com> wrote:

@sttts <https://github.com/sttts> PR needs rebase

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/40808#issuecomment-276838349>,
or mute the thread

**Pull request merged**
