### PR TITLE
sort containers by attempt number

### LINKED ISSUE #83050: When the time of a node changes to earlier, the pod may be "CreateContainerError" and can't recover itself
**What happened**:

I have a node "nodeA", I will run a pod "podA" on "nodeA", and "podA" has a container "containerA".
The time now is "timeA".

1. I run "podA" on a "nodeA" at "timeA", so kubelet create a container named "containerA_0", we can use command "docker inspect xxxxxxx" to see the "Created" field of "containerA_0" is "timeA".

2. The time of "nodeA" is changed to "timeB" for some reason. "timeB" is "timeA - 1h".

3. "containerA_0" encounters some errors and become "exited". Kubelet find that and create a container "containerA_1". We can use command "docker inspect xxxxxxxxxx" to see the "Created" fields of "containerA_1" is "timeB".

4. In this condition, when kubelet check the containerStatus of containerA, kubelet will see the "exited" "containerA_0" as the newest continerA , and kubelet will try to  create containerA_1 again and again but failed with error "Conflict ... is already in use by container xxxxxxx".

The reason is:
In `func "getPodContainerStatuses" (pkg/kubelet/kuberuntime/kuberuntime_container.go)`, the containers of podA is sorted by the "Created" field. 
```go
			}
		}
		statuses[i] = cStatus
	}

	sort.Sort(containerStatusByCreated(statuses))
	return statuses, nil
}
```

And `func "computePodActions"(pkg/kubelet/kuberuntime/kuberuntime_manager.go) --> "FindContainerStatusByName"(pkg/kubelet/container/runtime.go)` only pick the first "containerA" of podA's sorted containers, which is "containerA_0".
```go
// FindContainerStatusByName returns container status in the pod status with the given name.
// When there are multiple containers' statuses with the same name, the first match will be returned.
func (podStatus *PodStatus) FindContainerStatusByName(containerName string) *ContainerStatus {
	for _, containerStatus := range podStatus.ContainerStatuses {
		if containerStatus.Name == containerName {
			return containerStatus
		}
	}
	return nil
}
```

Because:
The "Created" field of "containerA_0" is "timeA", 
The "Created" field of "containerA_1" is "timeB",
 "timeB" is "timeA - 1h", so "timeB" < "timeA".
So, kubelet thinks containerA_0 is the newest containerA.
And because containerA_0 is "exited", in order, kubelet will create "containerA_1".
But "containerA_1" is already exist, so it will fail with error "Conflict ... is already in use by container xxxxxxx".

`log:`
```
E0924 09:07:24.225646   30207 remote_runtime.go:200] CreateContainer in sandbox "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Conflict. The name "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" is already in use by container xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. You have to remove (or rename) that container to be able to reuse that name.
E0924 09:07:24.225740   30207 kuberuntime_manager.go:779] container start failed: CreateContainerError: Error response from daemon: Conflict. The name "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" is already in use by container xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. You have to remove (or rename) that container to be able to reuse that name.
E0924 09:07:24.225772   30207 pod_workers.go:190] Error syncing pod xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)"), skipping: failed to "StartContainer" for "composer" with CreateContainerError: "Error response from daemon: Conflict. The name "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" is already in use by container xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. You have to remove (or rename) that container to be able to reuse that name."
```

5. After failing with the error "Conflict ... is already in use by container xxxxxxx", kubelet will try to remove the existed "containerA_1" to solve the conflict, but "containerA_1" is running, so remove failed.

`func "CreateContainer"(pkg/kubelet/dockershim/docker_container.go) --> "recoverFromCreationConflictIfNeeded" (pkg/kubelet/dockershim/helpers.go)`
```go
// See #33189. If the previous attempt to create a sandbox container name FOO
// failed due to "device or resource busy", it is possible that docker did
// not clean up properly and has inconsistent internal state. Docker would
// not report the existence of FOO, but would complain if user wants to
// create a new container named FOO. To work around this, we parse the error
// message to identify failure caused by naming conflict, and try to remove
// the old container FOO.
// See #40443. Sometimes even removal may fail with "no such container" error.
// In that case we have to create the container with a randomized name.
// TODO(random-liu): Remove this work around after docker 1.11 is deprecated.
// TODO(#33189): Monitor the tests to see if the fix is sufficient.
func recoverFromCreationConflictIfNeeded(client libdocker.Interface, createConfig dockertypes.ContainerCreateConfig, err error) (*dockercontainer.ContainerCreateCreatedBody, error) {
	matches := conflictRE.FindStringSubmatch(err.Error())
	if len(matches) != 2 {
		return nil, err
	}

	id := matches[1]
	klog.Warningf("Unable to create pod sandbox due to conflict. Attempting to remove sandbox %q", id)
	if rmErr := client.RemoveContainer(id, dockertypes.ContainerRemoveOptions{RemoveVolumes: true}); rmErr == nil {
		klog.V(2).Infof("Successfully removed conflicting container %q", id)
		return nil, err
	} else {
		klog.Errorf("Failed to remove the conflicting container %q: %v", id, rmErr)
		// Return if the error is not container not found error.
		if !libdocker.IsContainerNotFoundError(rmErr) {
			return nil, err
		}
	}

	// randomize the name to avoid conflict.
	createConfig.Name = randomizeName(createConfig.Name)
	klog.V(2).Infof("Create the container with randomized name %s", createConfig.Name)
	return client.CreateContainer(createConfig)
}
```

`log:`
```
W0924 09:07:39.224347   30207 helpers.go:286] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
E0924 09:07:39.225159   30207 helpers.go:291] Failed to remove the conflicting container "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": Error response from daemon: You cannot remove a running container xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Stop the container before attempting removal or use -f
```

6. In the problem, the pod have containStatus "CreateContainerError".
Even if the time of nodeA returns back to normal later, the problem can't recover itself. I must execute "docker rm -f <containerA_1>" or "docker rm <containerA_0>", then it will recover.
 

**What you expected to happen**:
After the time of nodeA returns back to normal, the problem can recover itself.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a pod with one container on a node.
2. Use command "date -s xxxxxxx" to change the time of the node to one hour early.
3. Use command "docker kill xxxxxxx" to kill the container of the pod.
4. The problem is now reproduced, and even if we change the time of the node back to nomal, the problem can't recover itself.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  kubelet version is 1.15.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #90298: time-shifting cause kubelet failed to create container
**What happened**:   

time-shifting cause  container created in the feature.
when time shift back to now a days, kubelet will failed to created new container.

```s
Apr 20 20:25:19 master kubelet[3580]: E0420 20:25:19.876407    3580 remote_runtime.go:200] CreateContainer in sandbox "f9dc950f0fdd6aadc8952849622ab6ae8ff6195a73905cdc90dadbf13f80dad2" from
 runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Conflict. The container name "/k8s_echo_echo-58d57fb7c-nrl5j_default_a9365d2a-d8cd-4a9d-948a-d84e064116
84_2" is already in use by container "0eaf56444980451ed2ca3f99bf09a571b61a6023f36519fc35ad3fe6375d5449". You have to remove (or rename) that container to be able to reuse that name.
```

**What you expected to happen**:

kubelet should create container

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.15.1

kubelet sort containers by create timestame which is the root cause of the problem.
sort by `Metadata.Attempt`  sames to solve this problem.

https://github.com/kubernetes/kubernetes/blob/1c62d2c368919de8bba93ea4706632bd2ac8027c/pkg/kubelet/kuberuntime/helpers.go#L52-L62

https://github.com/kubernetes/kubernetes/blob/d4bfcd1fda63aeb984eb0d83f5cc58768e359679/pkg/kubelet/dockershim/naming.go#L58-L79

/sig node

### PR DESCRIPTION
**Pull request by l1b0k**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

kubelet always get Newest container status .
If creation timestamps is not realiable, kubelet will inspect wrong container ,Pod will be in crash state.

**Which issue(s) this PR fixes**:
Fixes #90298
Fixes #83050 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig node

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
both bugs referred from the PR are closed. Please reopen one of them or ask in comments to re-open.

PR doesn't contain any tests to validate that the fix actually addresses the problem. I do realize it may be hard to come up with the proper test, but nevertheless, some thinking needs to be done here

**Comment by lilongfeng0902** [comment]
Hi，l1b0k，I have merged your code into the branch of 1.20.10, and I have tested，there is no longer exists the problem that we talk about.  thx!

**Comment by l1b0k** [comment]
> both bugs referred from the PR are closed. Please reopen one of them or ask in comments to re-open.
> 
> PR doesn't contain any tests to validate that the fix actually addresses the problem. I do realize it may be hard to come up with the proper test, but nevertheless, some thinking needs to be done here

@SergeyKanzhelev   thanks for reply , issue is reopened and tests are add , hope you have time review it.

**Comment by l1b0k** [comment]
> @endocrimes: The label(s) `triage/accept` cannot be applied, because the repository doesn't have them.
> 
> In response to [this](https://github.com/kubernetes/kubernetes/pull/108474#issuecomment-1117611007):
> 
> > /triage accept
> > /priority important-longterm
> > /cc @smarterclayton
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

@endocrimes hi, can this pr be accepted ?

**Comment by liggitt** [comment]
this needs a node reviewer/approver
/uncc

**Pull request closed without merging**
