### PR TITLE
Add initial brazilian portuguese translations #80650

### PR DESCRIPTION
**Pull request by fgsl**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
For use of Brazilian portuguese speakers.

**Which issue(s) this PR fixes**:
It's not a fix

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
Add initial brazilian portuguese translations
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
This PR fixes rebase issue of https://github.com/kubernetes/kubernetes/pull/86308

### CODE REVIEW

**Comment by fgsl** [comment]
@dims, @dixudx and @sftim, I destroyed my fork, recreated it and reapply my change in an uptodate branch.

**Comment by jtslear** [comment]
Hello, @jtslear as Bug Triage Shadow for 1.19. Assigning to sig-cli. If this is incorrect, please notify us and remove the sig.

/sig cli

**Comment by dougsland** [comment]
@fgsl Olá, there is conflict in your patch.  Could you please rebase your patch or close it?

**Comment by rikatz** [comment]
Hey @fgsl  nice to see you here :D

We've had a recently stopped pt_BR translation that moved forward. 

Maybe, as a suggestion you can take a look into that translation https://github.com/kubernetes/kubernetes/pull/61595 and improve it :D

If you have any question, you know where to find me ;)

**Comment by fgsl** [comment]
https://github.com/kubernetes/kubernetes/pull/86478#issuecomment-770519402

> @fgsl Olá, there is conflict in your patch. Could you please rebase your patch or close it?

Hi, @dougsland. Sorry for delay. I have rebased my branch and update my fork. What must I have to do now?

**Comment by rikatz** [comment]
@fgsl the rebase is bad, counting more than 5k files changed :)

As I've stated before, can you please take a look into the past PR from @cpanato, and instead of make a new one here see what can be improved in that translation?

Thanks!!

**Comment by dougsland** [comment]
> @fgsl the rebase is bad, counting more than 5k files changed :)
> 
> As I've stated before, can you please take a look into the past PR from @cpanato, and instead of make a new one here see what can be improved in that translation?
> 
> Thanks!!
@fgsl  I agree with @rikatz 
On top of that, how have you tested your change? exporting LANG=pt_BR variable is enough to test your changes?

**Comment by fgsl** [comment]
> > @fgsl the rebase is bad, counting more than 5k files changed :)
> > As I've stated before, can you please take a look into the past PR from @cpanato, and instead of make a new one here see what can be improved in that translation?
> > Thanks!!
> 
> @fgsl I agree with @rikatz
> On top of that, how have you tested your change? exporting LANG=pt_BR variable is enough to test your changes?

Right, @rikatz  and @dougsland.  I am closing this issue. I started it more than one year ago. And this is the second, because I made one another first: https://github.com/kubernetes/kubernetes/pull/86308. Then, I will work from zero, with one phrase by time, from contributions by @crpanato.

**Comment by rikatz** [comment]
Ok, you can ping me and @dougsland to review it or the parts once you think it's ready or if you need any help

**Pull request closed without merging**
