### PR TITLE
Fix kubectl run to print object on dry run

### LINKED ISSUE #19636: kubectl run --dry-run does not print object
This seems like a known issue (#11488, #17538) but I wanted to log this as a bug specifically because the help text is misleading.

```
$ kubectl help run
Create and run a particular image, possibly replicated.
Creates a replication controller or job to manage the created container(s).
...
Flags:
      --dry-run[=false]: If true, only print the object that would be sent, without sending it.
...
```

```
$ kubectl run --dry-run nginx --image=nginx
replicationcontroller "nginx" created
$ kubectl get rc
$
```

Replication controller is correctly not created but the object is not printed. We should either change the help text or print the object. I support the latter because I could really use the feature. :)

### PR DESCRIPTION
**Pull request by dims**
Originally Authored By tnachen in PR:
https://github.com/kubernetes/kubernetes/pull/25842

Fixes #19636

### CODE REVIEW

**Comment by janetkuo** [comment]
Hi @dims, you'll need to support `dry-run` in `generateService` too, otherwise you'll have something like:

```console 
$ kubectl run nginx --image=nginx --expose --port=8080 --dry-run 
service "nginx" created
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     1         0         0            0           <unknown>
```

Also I'd expect the unit test `TestGenerateService` needs to be updated with this change.

**Comment by dims** [comment]
@janetkuo ah. i was trying the following

```
kubectl run nginx --image=nginx --expose --port=8080 --dry-run -o yaml
kubectl run nginx --image=nginx --expose --port=8080 --dry-run -o json

```

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by janetkuo** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Comment by dims** [comment]
@janetkuo : looks like all the tests are green. Can you please bless this?

**Pull request merged**
