### PR TITLE
ParseEncryptionConfiguration: simplify code

### PR DESCRIPTION
**Pull request by php-coder**
**What this PR does / why we need it**:
Reorder `if`-s to make code a bit more readable. It also improves godoc comment and error message.

**Release note**:
```release-note
NONE
```

PTAL @sakshamsharma

### CODE REVIEW

**Comment by sakshamsharma** [comment]
lgtm (I can't approve though).
Thanks for catching those issues!

**Comment by kargakis** [comment]
@smarterclayton

**Comment by php-coder** [comment]
Test flake #46690

**Comment by php-coder** [comment]
`hack/.linted_packages` was updated.

**Comment by sakshamsharma** [comment]
@php-coder one approval is still missing. Although why `hack/.linted_packages` requires another approver is beyond me.

**Comment by php-coder** [comment]
@deads2k PTAL

**Comment by php-coder** [comment]
@smarterclayton PTAL

**Comment by php-coder** [comment]
Rebased.

**Comment by php-coder** [comment]
Test flake https://github.com/kubernetes/kubernetes/issues/49292

**Comment by fejta** [comment]
/retest
Automatic retester of approved PRs with test failures, please send feedback to fejta

**Pull request merged**
