### PR TITLE
Update etcd to 3.5.2

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind cleanup
/cc @dims 

#### What this PR does / why we need it:

Upgrade etcd to v3.5.2.  [Changelog](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v352-2022-02-01).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
Upgrade etcd to 3.5.2
```

### CODE REVIEW

**Comment by endocrimes** [comment]
Ah - looks like I need to build some etcd images in kubernetes/k8s.io and then re-kick ci

**Comment by endocrimes** [comment]
Ah I need to split this in 2 prs to handle image build + promotion, then bump the other side of things.

Gonna close then document it for the future.

/close

**Comment by FerminCastro** [comment]
We really need this. Please see https://github.com/kubernetes/website/issues/31822 and https://github.com/etcd-io/etcd/issues/13724 The lack of etcd 3.5.2 support is basically precluding all upgrades of kubeadm K8 clusters from 1.21 onwards

**Comment by endocrimes** [comment]
@FerminCastro Planning on following up on this this week, got side tracked with other work

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/pull/107917#issuecomment-1047158561

just for clarification, this PR only affects the version used for testing in the CI and the one used by kubeadm

https://github.com/kubernetes/kubernetes/blob/267272efe0725e14b3c2c7bc6fa3dd64a922a6a7/cmd/kubeadm/app/constants/constants.go#L322-L323

AFAIK the only etcd version that affect users here is the one in kubeadm, other kubernetes cluster that were not created by kubeadm depend on their respective installers

**Comment by neolit123** [comment]
For kubeadm we already want the unreleased 3.5.3
https://github.com/kubernetes/kubeadm/issues/2567

**Comment by FerminCastro** [comment]
So what do we do in the meantime with the k8 1.21 clusters (created with kubeadm) that cannot be upgraded?

**Comment by neolit123** [comment]
Use the tips that I provided on the k/website ticket. Once kubeadm catches
up with latest etcd, remove the ClusterConfiguration change, so that you no
longer pin etcd and prevent kubeadm from managing its upgrade.

**Comment by FerminCastro** [comment]
Sorry I thought from your comments that it was not officially supported 

<QUOTE>:

changing the etcd image on a running cluster is not something that we recommend.
advanced users follow the kubeadm implementations details:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/
and can change the image, but they are in unsupported territory after that.

</QUOTE>

can we use this then or will it leave us in an unsupported state?

Thanks again for the help

**Comment by neolit123** [comment]
You can manually change / pin the etcd image, but to get back to a
'supported state' you can revert the change.

**Pull request closed without merging**
