### PR TITLE
Fix iptables version detection code to handle RHEL 7 correctly

### LINKED ISSUE #82587: kube-proxy fails to restore iptable rules
*What happened**:
Running `hack/local-up-cluster.sh`, kube-proxy never succeeds calling `iptables-restore --noflush --counters`:

```
I0911 14:30:08.104508    1022 proxier.go:1420] Restoring iptables rules: *filter
:KUBE-SERVICES - [0:0]
:KUBE-EXTERNAL-SERVICES - [0:0]
:KUBE-FORWARD - [0:0]
-A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x00004000/0x00004000 -j ACCEPT
COMMIT
*nat
:KUBE-SERVICES - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SEP-SGYQAO2MFIR4HIEV - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SEP-SNPTLXDNVSPZ5ND2 - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SEP-7PPXA5JT5ALVQPIV - [0:0]
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x00004000/0x00004000 -j MASQUERADE
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x00004000/0x00004000
-A KUBE-SERVICES -m comment --comment "default/kubernetes:https cluster IP" -m tcp -p tcp -d 10.0.0.1/32 --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SVC-NPX46M4PTMTKRN6Y -j KUBE-SEP-SGYQAO2MFIR4HIEV
-A KUBE-SEP-SGYQAO2MFIR4HIEV -s 192.168.122.150/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-SGYQAO2MFIR4HIEV -m tcp -p tcp -j DNAT --to-destination 192.168.122.150:6443
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp -p udp -d 10.0.0.10/32 --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SVC-TCOU7JCQXEZGVUNU -j KUBE-SEP-SNPTLXDNVSPZ5ND2
-A KUBE-SEP-SNPTLXDNVSPZ5ND2 -s 172.17.0.2/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-SNPTLXDNVSPZ5ND2 -m udp -p udp -j DNAT --to-destination 172.17.0.2:53
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp -p tcp -d 10.0.0.10/32 --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SVC-ERIFXISQEP7F7OF4 -j KUBE-SEP-7PPXA5JT5ALVQPIV
-A KUBE-SEP-7PPXA5JT5ALVQPIV -s 172.17.0.2/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-7PPXA5JT5ALVQPIV -m tcp -p tcp -j DNAT --to-destination 172.17.0.2:53
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
COMMIT
I0911 14:30:08.104638    1022 iptables.go:397] running iptables-restore [--noflush --counters]
E0911 14:30:08.106159    1022 proxier.go:1423] Failed to execute iptables-restore: exit status 4 (Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
)
```

No matter how long I wait, kube-proxy always gets `Another app is currently holding the xtables lock`.

Adding `-w` to iptables-restore cmdline (via hacked version check) fixed the issue for me, but I am not able to judge what else it break (there must have been reason for https://github.com/kubernetes/kubernetes/pull/80368). Until now I was happy user of `local-up-cluster.sh` and I'd like have it working again.

**Anything else we need to know?**:

kernel-3.10.0-957.12.2.el7.x86_64
iptables-1.4.21-28.el7.x86_64
kubernetes v1.16.0-rc.1

/sig network

@danwinship, PTAL
cc @bertinatto

### PR DESCRIPTION
**Pull request by danwinship**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
#80368 broke kubernetes on RHEL 7. This should fix it. Correctly even.

**Which issue(s) this PR fixes**:
Fixes #82587.
See discussion there and in #82596 (which this is either an alternative or a follow-up to).

```release-note
NONE
```
/sig network
/priority critical-urgent
/assign @thockin

### CODE REVIEW

**Comment by danwinship** [comment]
ok, let's see what e2e-gce thinks of this...

**Comment by danwinship** [comment]
@mrunalp can you test this version against cri-o rhel7 too?

**Comment by mrunalp** [comment]
Yes, I will open a PR.

**Comment by mrunalp** [comment]
@danwinship Opened https://github.com/cri-o/cri-o/pull/2787. I will let you know how it goes.

**Comment by mrunalp** [comment]
The CRI-O PR is green with the changes here :+1:

**Comment by dcbw** [comment]
/lgtm
I'll hold off approve until tests pass.

**Pull request merged**
