### PR TITLE
Fix removeLabelOffNode in SchedulerPredicates

### PR DESCRIPTION
**Pull request by gmarek**
Ref #27320

Flake fix - P0.

cc @davidopp @kevin-wangzefeng

### CODE REVIEW

**Comment by davidopp** [comment]
Thanks for the debugging.

Would changing the original line to
`if node.Labels == nil || len(node.Labels[labelKey]) == 0 `
also work? (I suspect that's what was intended, and the != was a typo)

Anyway, marking this LGTM, feel free to stick with your approach (but note there is another line in the file that does `if node.Labels == nil || len(node.Labels[labelKey]) == 0` so now we will have two different approaches).

**Comment by gmarek** [comment]
Yeah `!=` was a mistake - I'll  change it to `==`

**Comment by davidopp** [comment]
Actually I think this is still not right. IIUC the failure condition we are trying to detect is that the updated node still has a k/v pair with key labelKey.  So I think it should be

```
if nodeUpdated.Labels == nil || len(nodeUpdated.Labels[labelKey]) != 0
```

cc/ @kevin-wangzefeng

**Comment by davidopp** [comment]
I created #27838 so we can get this merged sooner.

**Pull request closed without merging**
