### PR TITLE
[Federation] Add option to retrieve e2e cluster config from secrets

### PR DESCRIPTION
**Pull request by marun**
Previously the federation e2e setup was reading member cluster configuration from the test run's kubeconfig. This change removes that dependency in favor of reading member cluster configuration from secrets in the hosting cluster, and caches the configuration to avoid having to read it separately for each test.

cc: @kubernetes/sig-federation-pr-reviews @perotinus

### CODE REVIEW

**Comment by marun** [comment]
rebased

**Comment by marun** [comment]
rebased

**Comment by marun** [comment]
rebased

**Comment by marun** [comment]
@k8s-bot non-cri e2e test this

**Comment by madhusudancs** [comment]
We shouldn't do this. Particularly, we shouldn't read the secrets from the host cluster. The idea is to run the e2e tests as if a user were performing the operations. And users won't have access to the secrets in a properly secured cluster. [Enforcing RBAC in e2e clusters](https://groups.google.com/d/topic/kubernetes-dev/gASoXHp52R8/discussion) is a good example of this. We wouldn't have taken all the trouble if we did not care how these tests were run.

Moreover, this won't work as is when we merge @perotinus' PR #42042.

**Comment by marun** [comment]
@madhusudancs I'm not sure why the idea that e2e must be performed 'as if a user were performing the operations' precludes this proposal.  An administrator with full access to the secrets in the host clusters is still a user.  e2e testing is simply about validating behavior.  Why would it matter how credentials are sourced for performing test-time validation of behavior?

I think the current approach of looking for contexts in the test kubeconfig with a 'federation' prefix is brittle - there is no guarantee that such a context is a member cluster in the federation under test.   Whereas if a cluster and the secrets needed to access it are present in a federation control plane, that's an unambiguous indication that it's a member cluster for which propagation needs to be verified.

As to @perotinus's PR, why would it break this proposal?

**Comment by madhusudancs** [comment]
> I'm not sure why the idea that e2e must be performed 'as if a user were performing the operations' precludes this proposal. An administrator with full access to the secrets in the host cluster is still a user. Why does it matter how credentials are sourced for performing test-time validation of behavior?

Yeah, but he is not the only user. He is a special user and that's not what we want to test.

> I think the current approach of looking for contexts in the test kubeconfig with a 'federation' prefix is brittle - there is no guarantee that such a context is a member cluster in the federation under test.

I agree that the current approach is brittle. 

> Whereas if a cluster and the secrets needed to access it are present in a federation control plane, that's an unambiguous indication that it's a member cluster for which propagation needs to be verified.

Yeah, but this proposed approach isn't reading the secret from federation control plane. It reads it from the host cluster. And no one other than the federation controller manager should have access to these secrets in a properly secured cluster.

Note that the proposed approach is brittle too. It assumes that the secret name matches the clusterName which isn't the case always. You could get the secret name from the cluster object, but in any case we shouldn't be reading that secret at all.

I am fine reading the cluster list from the federation API server, but not reading the secrets from the host cluster.

One way to make this less brittle is to pass the kubeconfig contexts for the federation clusters as a flag to the e2e binary.

> As to @perotinus's PR, why would it break this proposal?

Because it uses service accounts, not kubeconfig.

**Comment by marun** [comment]
@madhusudancs I think this is a simple matter of separation of concerns - e2e needs to be configured, and then needs to execute tests.  I completely agree that test execution should adhere as closely as possible to realistic use cases.  I don't think it makes sense for test configuration to adhere to the same standard. 

> Yeah, but he is not the only user. He is a special user and that's not what we want to test.

I'm not suggesting that we test admin access to secrets.  Secret retrieval as proposed in this PR is  part of test setup, and orthogonal to test execution.

>> Whereas if a cluster and the secrets needed to access it are present in a federation control plane, that's an unambiguous indication that it's a member cluster for which propagation needs to be verified.

>Yeah, but this proposed approach isn't reading the secret from federation control plane. It reads it from the host cluster. And no one other than the federation controller manager should have access to these secrets in a properly secured cluster.

Yes, the secrets used to access a production cluster should be protected.  I don't see how that precludes reading the secrets from a test cluster.  I don't think doing so would compromise how a production cluster would be used, or that it would result in an unrealistic test environment.  

>Note that the proposed approach is brittle too. It assumes that the secret name matches the clusterName which isn't the case always. You could get the secret name from the cluster object, but in any case we shouldn't be reading that secret at all.

Good call - the secret name should be read from the cluster object.  I still don't see why we shouldn't be reading the secret as part of test setup, though.

> One way to make this less brittle is to pass the kubeconfig contexts for the federation clusters as a flag to the e2e binary.

Ugh. That's even more complicated.

>> As to @perotinus's PR, why would it break this proposal?

> Because it uses service accounts, not kubeconfig.

So can't this proposal be updated to use a service account instead of a kubeconfig?

**Comment by madhusudancs** [comment]
> I'm not suggesting that we test admin access to secrets. Secret retrieval as proposed in this PR is part of test setup, and orthogonal to test execution.

Test setup is part of the execution. You can't execute tests without setting them up. They are not orthogonal. They are dependent on each other.

> Yes, the secrets used to access a production cluster should be protected. I don't see how that precludes reading the secrets from a test cluster. 

We want the test environment to be as close to the commonly used environment as possible. It doesn't make sense to have a very different test environment than a common case.

> I don't think doing so would compromise how a production cluster would be used, or that it would result in an unrealistic test environment.

If your test environment is already working around how would you ever know? On the other hand, we need tests to ensure these credentials aren't exposed to clients outside the cluster through RBAC rules.

> Ugh. That's even more complicated.

Not entirely sure how that's complicated, but it is less brittle.

> So can't this proposal be updated to use a service account instead of a kubeconfig?

It can be. But once we install RBAC rules to not allow access outside the cluster, then you cannot.

**Comment by marun** [comment]
>> I'm not suggesting that we test admin access to secrets. Secret retrieval as proposed in this PR is part of test setup, and orthogonal to test execution.

> Test setup is part of the execution. You can't execute tests without setting them up. They are not orthogonal. They are dependent on each other.

A test does things to configure itself (setup) so that it can do things a user would do (execution).  I think conflating the requirements for these orthogonal operations is most unwise, as it all but guarantees the introduction of accidental complexity.  Since I'm apparently unable to convince you of something that to me is foundational to effective testing, I'll close this PR and direct my attention elsewhere.

**Comment by marun** [comment]
@madhusudancs I'll revise this PR so that secret retrieval is added as a new optional method for configuring the e2e tests.  The existing method will remain the default.

I think developers should be able to run e2e tests without having to duplicate configuration between init and test invocation.  I also think it will be useful to be able to run federation e2e in a cluster sans explicit kubeconfig as per #44424.

**Comment by madhusudancs** [comment]
@marun ack.

**Comment by marun** [comment]
@madhusudancs I did some refactoring and cleanup of the default method, and configuring from secrets is now only used if ``--federation-config-from-cluster=true`` is provided to the test command.

**Comment by marun** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by marun** [comment]
@k8s-bot gci gce e2e test this

somehow I doubt that this PR would have an impact on a statefulsets test

**Comment by marun** [comment]
federation e2e is green: http://prow.k8s.io/?type=presubmit&pull=44073&job=pull-kubernetes-federation-e2e-gce

**Comment by shashidharatd** [comment]
Cool. this LGTM
/lgtm

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44073#-:-Ki3D1ww3-v3gtGeyLI2:bewmcj3)*

**Pull request merged**
