### PR TITLE
Unify termination signal handling across platforms

### PR DESCRIPTION
**Pull request by rhcarvalho**
The signals are used to ensure proper execution of cleaning up actions to restore a terminal in:
- [pkg/kubectl/cmd/attach.go#L163-L226](https://github.com/kubernetes/kubernetes/blob/b8d000853edbfe3d0d9bcd85e8e511a98b6ac6af/pkg/kubectl/cmd/attach.go#L163-L226)
- [pkg/kubectl/cmd/util/editor/editor.go#L112-L137](https://github.com/kubernetes/kubernetes/blob/b8d000853edbfe3d0d9bcd85e8e511a98b6ac6af/pkg/kubectl/cmd/util/editor/editor.go#L112-L137)

All supported platforms can handle the same set of signals we're interested in, thus we don't need build contraints to use a set of signals on Linux, while restricting ourselves to only SIGINT on Darwin and Windows.

According to the documentation of os/signal, similar to SIGINT and SIGTERM, SIGHUP causes the program to exit, therefore add it to the list of handled signals.

The fist commit is part of #23643.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@smarterclayton @bparees PTAL

@bparees we could include this update in https://github.com/openshift/source-to-image/pull/452

**Comment by rhcarvalho** [comment]
I can drop the first commit. I included it here to avoid merge conflicts with the changes in  #23643.

**Comment by smarterclayton** [comment]
Kube compiles clients for more platforms than just linux, windows, and mac - please verify that the cross platform compiles works for others (bsd, a few others?)

**Comment by rhcarvalho** [comment]
@smarterclayton could you please give me a pointer to code? I looked at the last [release tar.gz](https://github.com/kubernetes/kubernetes/releases/download/v1.2.1/kubernetes.tar.gz) and the archive contains `kubernetes/platforms/{linux,windows,darwin}/$GOARCH/bin/kubectl`.

Where could I find the full list of supported platforms?

We could have then two definitions, one for `linux, darwin, windows` with the 4 signals we have currently, and a fallback for all other platforms with only `os.Interrupt`, which is the only signal of the 4 to be guaranteed for all platforms with Go support.

**Comment by smarterclayton** [comment]
Looks like we removed them, it's fine for now.

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
Needs to be rebased so the travis job stops showing up.

**Comment by rhcarvalho** [comment]
rebased

**Pull request merged**
