### PR TITLE
WIP: Test images/centralize images to agnhost

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by spiffxp** [comment]
@bclau I think this is stale in face of PR's opened against https://github.com/kubernetes/kubernetes/issues/76342 and should be closed, WDYT?

**Comment by bclau** [comment]
> 
> 
> @bclau I think this is stale in face of PR's opened against #76342 and should be closed, WDYT?

Indeed, it's a bit outdated, it contained the original code before it was split in multiple PRs. It still contains code that was not included in other PRs yet, so I'll keep it for a bit.

**Comment by johnSchnake** [comment]
ping @bclau with the latest round of your PRs is this ready to close?

**Comment by bclau** [comment]
> 
> 
> ping @bclau with the latest round of your PRs is this ready to close?

Yeah, this contained the serve-hostname bits, which have been included in part 3. It no longer contains anything useful.

**Pull request closed without merging**
