### PR TITLE
Fixed broken link (was pointing to content in a file that has since been moved).

### LINKED ISSUE #12357: Broken link on kubernetes.io to http://kubernetes.io/v1.0/DESIGN.html
On the page http://kubernetes.io/v1.0/docs/user-guide/walkthrough/README.html the link http://kubernetes.io/v1.0/DESIGN.html is broken. Reported by @ivant

@RichieEscarez

### PR DESCRIPTION
**Pull request by RichieEscarez**
Fixes #12357

### CODE REVIEW

**Comment by RichieEscarez** [comment]
hack/update-generated-docs.sh runs clean, im not sure how to fix the errors?

**Comment by bgrant0607** [comment]
You mean hack/run-gendocs.sh?

That rightfully fails. There's no such doc.

DESIGN.md does exist at the top level. 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/DESIGN.md

It probably just doesn't exist in gh_pages.

I recommend pointing at design/README.md instead (where "design" is lowercase, not uppercase).

**Comment by RichieEscarez** [comment]
Im not seeing "hack/run-gendocs.sh" in the directory anymore and the error is saying:
```
FAIL: changes needed but not made due to --verify
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh
```

**Comment by bgrant0607** [comment]
You're right. Looks like that script was refactored and renamed. 

The link is now correct, and the checks passed on Travis.

LGTM.

**Pull request merged**
