### PR TITLE
Remove redundant call of kube::release::gcs::release.

### PR DESCRIPTION
**Pull request by david-mcmahon**
This is called by build/push-official-release.sh.

### CODE REVIEW

**Comment by david-mcmahon** [comment]
cc @ihmccreery

**Comment by ihmccreery** [comment]
What about for `make release` for a dev build?

**Comment by ihmccreery** [comment]
I.e. `build/push-devel-build.sh` or something?

**Comment by david-mcmahon** [comment]
kube::release::gcs::release() exits immediately unless KUBE_GCS_UPLOAD_RELEASE=y is set and that is set only in the various build/push-* scripts anyway.

**Comment by ihmccreery** [comment]
LGTM.

**Pull request merged**
