### PR TITLE
Automated cherry pick of #61892 #62160 #62189 #62271 upstream release 1.8

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #61892 #62160 #62189 #62271 on release-1.9.
#61892 : Fix e2e tests for regional
#62160 : Fix disruptive tests for GKE regional clusters
#62189 : Fix resize nodes tests for Regional Clusters
#62271 : Fix remaining disruptive regional tests

Those changes are to fix upgrade tests for GKE Regional Clusters

### CODE REVIEW

**Comment by shyamjvs** [comment]
The reason for these failures is https://github.com/kubernetes/test-infra/issues/7646

@kubernetes/test-infra-maintainers The issue needs to be resolved asap - as it'll block merging any PRs to <= 1.9 release branches.

**Comment by shyamjvs** [comment]
@wojtek-t Actually, can you also cherry-pick https://github.com/kubernetes/kubernetes/pull/61203 in this PR since you're anyway adding a bunch of cherrypicks?

**Comment by BenTheElder** [comment]
gah, @krzyzacy kubemark is out of addresses https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/62322/pull-kubernetes-kubemark-e2e-gce/85657/

/retest

**Pull request merged**
