### PR TITLE
Fix apiserver container_env generation in configure-helper.sh

### PR DESCRIPTION
**Pull request by Katharine**
**What this PR does / why we need it**: The construction of `container_env` in `configure-helper.sh` is broken such that `ENABLE_CACHE_MUTATION_DETECTOR` and `ENABLE_PATCH_CONVERSION_DETECTOR` are mutually exclusive, due to multiple issues in the construction of the string.

This PR fixes the logic such that the array is correctly constructed, and adds unit tests verifying that it is correct.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Katharine** [comment]
/retest

I do not understand how this can possibly actually be breaking kops on AWS when it only changes GCE configuration.

**Comment by BenTheElder** [comment]
finally passed :neutral_face:, raising the flakiness issue to sig-release

**Comment by krzyzacy** [comment]
one day I'll write a this-is-fine plugin

**Pull request closed without merging**
