### PR TITLE
Revert "Add better logging when iptables-restore fails"

### PR DESCRIPTION
**Pull request by krzysied**
Reverts kubernetes/kubernetes#76171

@thockin @dcbw - FYI

### CODE REVIEW

**Comment by krzysied** [comment]
Example of logs:

```
E0502 12:20:18.998222       1 proxier.go:1374] Failed to execute iptables-restore: failed to acquire new iptables lock: timed out waiting for the condition
failed payload:
*filter
:KUBE-SERVICES - [0:0]
:KUBE-EXTERNAL-SERVICES - [0:0]
:KUBE-FORWARD - [0:0]
-A KUBE-SERVICES -m comment --comment "test-dlqat9-2/small-service-125: has no endpoints" -m tcp -p tcp -d 10.0.244.248/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-1/small-service-72: has no endpoints" -m tcp -p tcp -d 10.0.195.129/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-30/small-service-87: has no endpoints" -m tcp -p tcp -d 10.0.234.239/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-32/small-service-79: has no endpoints" -m tcp -p tcp -d 10.0.132.31/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-5/small-service-88: has no endpoints" -m tcp -p tcp -d 10.0.91.145/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-41/small-service-94: has no endpoints" -m tcp -p tcp -d 10.0.198.154/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-44/small-service-61: has no endpoints" -m tcp -p tcp -d 10.0.103.86/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-18/small-service-89: has no endpoints" -m tcp -p tcp -d 10.0.209.224/32 --dport 80 -j REJECT
-A KUBE-SERVICES -m comment --comment "test-dlqat9-42/small-service-40: has no endpoints" -m tcp -p tcp -d 10.0.155.8/32 --dport 80 -j REJECT
....
````

The kube-proxy.log size increased over 1000X due to this change.

**Comment by wojtek-t** [comment]
@thockin @dcbw

**Comment by dcbw** [comment]
@wojtek-t this logging is pretty useful though, so shouldn't we investigate *why* the proxy failed to restore, rather than killing good debug logging that should almost never happen?

**Comment by wojtek-t** [comment]
> @wojtek-t this logging is pretty useful though, so shouldn't we investigate why the proxy failed to restore, rather than killing good debug logging that should almost never happen?

I think both - I wouldn't say that logging 40MB or sth of iptables (in very large cluster) contents is particularly useful...

**Pull request merged**
