### PR TITLE
Modifies receiver names for struct FakeProxier to make them the same.

### PR DESCRIPTION
**Pull request by Nanfei-Chen**
Signed-off-by: Nanfei Chen <chennanfei@yeah.net>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Receiver names for struct FakeProxier are different, so that there are some weak warnings. Modifies receiver names to make them the same, and it is meaningful to eliminate those warnings
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Nanfei-Chen** [comment]
@dims Please helps to review this PR, thanks

**Comment by pacoxu** [comment]
> @Nanfei-Chen: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository. Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

Before we review this pr, you should handle the problem above.

> BTW, it seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked help-wanted. 

This may help in code readability.

**Comment by Nanfei-Chen** [comment]
@pacoxu Thanks, and I have solved the problem.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by Nanfei-Chen** [comment]
@dims Thanks, please helps to review!

**Comment by robscott** [comment]
Hey @Nanfei-Chen, where are these warnings coming from? Are there any issues to track this?

**Comment by Nanfei-Chen** [comment]
> Hey @Nanfei-Chen, where are these warnings coming from? Are there any issues to track this?

The warnings come from IDE tools for Go. I use GoLand now.

**Pull request merged**
