### PR TITLE
Enable more test images for s390x

### PR DESCRIPTION
**Pull request by yselkowitz**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

This enables the build of more test images on s390x so that the tests which depend thereon pass on s390x.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by mkumatag** [comment]
> These images are for node and storage tests. I'm not sure if we have automated builds for them yet.
> /sig node
> /sig storage
> 

At least we should test image building part once before we merge..

**Comment by SergeyKanzhelev** [comment]
@yselkowitz can you please confirm you tried to build them as per comment:

> At least we should test image building part once before we merge..

**Comment by hbrueckner** [comment]
@yselkowitz let me loop  @cwsolee here. Cindy could you have a look based on your k8s test efforts?

**Comment by cwsolee** [comment]
@hbrueckner Not sure what u're referring to, I don't think this is related to what my team has enabled.

**Comment by mkumatag** [comment]
> Finally managed to set up things to test build this. apparmor-loader currently does not build on any architecture, as the apparmor packages have been removed from the alpine repo; not sure what needs to happen here. The others did build successfully with the s390x additions.

I see that, but see that it got included into the edge repo, probably we can install from there. created https://github.com/kubernetes/kubernetes/issues/105528 to track this work,

**Review by mkumatag — CHANGES_REQUESTED** [review]

**Comment by mkumatag** [comment]
> Updating the base to 3.14 seems to work.

it will be great if you can attach image building logs to this PR for reference for all the images.

**Comment by yselkowitz** [comment]
Ping?

**Comment by yselkowitz** [comment]
I did not keep logs, but I did build them.

**Comment by mkumatag** [comment]
> I did not keep logs, but I did build them.

Let's merge this, will fix the errors if any..

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by yselkowitz** [comment]
Failure is completely unrelated.
/retest

**Comment by mkumatag** [comment]
> one of the post-job failed - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-node-perf-npb-is-test-images/1450295575680389120
> 
> @claudiubelu can you please retrigger the job?

pushed the image now via - https://github.com/kubernetes/kubernetes/pull/105823#issuecomment-949245964

**Pull request merged**
