### PR TITLE
Replace git volume with configmap in emptydir wrapper conflict test

### PR DESCRIPTION
**Pull request by wongma7**
**What this PR does / why we need it**: GitRepoVolumeSource is deprecated, use a ConfigMap instead. (This test is part of the conformance suite, so it would be good to allow downstreams to disable/not support gitRepo)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by msau42** [comment]
/lgtm

BTW, I don't think this is a conformance test.  It doesn't have the `ConformanceIt` and I don't see it [here](https://k8s-testgrid.appspot.com/conformance-all#GCE,%20master%20(dev))

**Comment by spiffxp** [comment]
/priority critical-urgent
SIG Testing chair here, this had lgtm and approved labels prior to entering code freeze

@msau42 true, but it looks like this could be promoted to conformance

**Pull request merged**
