### PR TITLE
Fix typos in rbac api.

### PR DESCRIPTION
**Pull request by zhanluxianshen**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix typos in rbac api.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aramase** [comment]
/triage accepted

/assign liggitt
(assigned as part of SIG Auth triage meeting)

This is not really a typo. Need to check if this is backward compatible or introduces any breaking changes.

**Comment by zhanluxianshen** [comment]
😀,Thanks for review.

**Pull request merged**
