### PR TITLE
Update the Windows server core 1809 image to July version 0709

### PR DESCRIPTION
**Pull request by YangLu1031**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
There is a vulnerability in windows-server-1809-v20190312, so update to latest version

**Does this PR introduce a user-facing change?**:

```release-note
Update the GCE windows node image to include hot fixes since July.
```

### CODE REVIEW

**Comment by yujuhong** [comment]
/ok-to-test

Please add a release note

**Comment by yujuhong** [comment]
/retest
/approve

The image was tested in the prototype repository and passed the tests.

**Comment by rhockenbury** [comment]
Does this include the KB for the windows defender fix?https://github.com/kubernetes/kubernetes/issues/75148#issuecomment-505559576

And if so, should windows defender be re-enabled for the gce windows nodes?

**Comment by yujuhong** [comment]
> Does this include the KB for the windows defender fix?[#75148 (comment)](https://github.com/kubernetes/kubernetes/issues/75148#issuecomment-505559576)
> 
> And if so, should windows defender be re-enabled for the gce windows nodes?

Not sure if the image includes the fix. @pjh 

Even if it does, let's wait a couple of days to make sure the tests are stable before trying to re-enabling windows defender.

**Comment by pjh** [comment]
@rhockenbury yes, this image should include that fix. As @yujuhong mentioned we'll merge this first, then try re-enabling Windows Defender next.

**Pull request merged**
