### PR TITLE
Fix block volume reconstruction

### LINKED ISSUE #83445: Block volume reconstruction does not delete global symlink
Reconstructed block volume leaves global symlink and does not un-map the device.

**How to reproduce it (as minimally and precisely as possible)**:

1. I have iSCSI block PV used in a pod. This is found in /var/lib/kubelet:
    ```
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/iscsi.json
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/2e8310c1-a75d-44f1-9639-694ec1c4ab8d

    /var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumeDevices/kubernetes.io~iscsi
    /var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumeDevices/kubernetes.io~iscsi/iscsi-block-pv
    ```

2. Stop kubelet, force-delete the pod, start new kubelet

3. After the reconstruction, this is found in /var/lib/kubelet:
    ```
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/iscsi.json
    /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/2e8310c1-a75d-44f1-9639-694ec1c4ab8d
    ```
    And my iSCSI device is still available on the node (i.e. `TearDownDevice` was not called).

**What you expected to happen**:
Global symlinks deleted + iSCSI volume detached from the node.

**Anything else we need to know?**:

Digging in kubelet logs, this is reconstruction of the block volume:

```
I1003 11:58:15.800962   15460 operation_executor.go:901] Starting operationExecutor.ReconstructVolume
I1003 11:58:15.802013   15460 volume_path_handler.go:203] FindGlobalMapPathFromPod: path /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/2e8310c1-a75d-44f1-9639-694ec1c4ab8d, mapPath /var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumeDevices/kubernetes.io~iscsi/iscsi-block-pv
I1003 11:58:15.802168   15460 volume_path_handler.go:227] CompareSymlinks: devGloBal /dev/sdd, devPod /dev/sdd
I1003 11:58:15.802293   15460 volume_path_handler.go:213] FindGlobalMapPathFromPod: globalMapPathUUID /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/2e8310c1-a75d-44f1-9639-694ec1c4ab8d
I1003 11:58:15.802392   15460 iscsi.go:268] globalMapPathUUID: /var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1:3260-iqn.2003-01.io.k8s:jsafrane-lun-0/2e8310c1-a75d-44f1-9639-694ec1c4ab8d, err: <nil>
I1003 11:58:15.802538   15460 iscsi.go:663] ConstructBlockVolumeSpec: TargetPortal: 127.0.0.1:3260, IQN: iqn.2003-01.io.k8s:jsafrane, Lun: 0, ISCSIInterface: default
I1003 11:58:15.802620   15460 volume_host.go:308] using default mounter/exec for kubernetes.io/iscsi
I1003 11:58:15.802658   15460 volume_host.go:308] using default mounter/exec for kubernetes.io/iscsi
W1003 11:58:15.802836   15460 reconciler.go:393] Could not construct volume information, cleanup the mounts. (pod.UID 2e8310c1-a75d-44f1-9639-694ec1c4ab8d, volume.SpecName iscsi-block-pv): volume: "kubernetes.io/iscsi/127.0.0.1:3260:iqn.2003-01.io.k8s:jsafrane:0" is not mounted
I1003 11:58:15.803015   15460 reconciler.go:428] Reconciler sync states: could not find information (PID: 2e8310c1-a75d-44f1-9639-694ec1c4ab8d) (Volume SpecName: iscsi-block-pv) in desired state, clean up the mount points
I1003 11:58:15.804038   15460 volume_host.go:308] using default mounter/exec for kubernetes.io/iscsi
I1003 11:58:15.804068   15460 volume_host.go:308] using default mounter/exec for kubernetes.io/iscsi
I1003 11:58:15.804648   15460 subpath_linux.go:215] Cleaning up subpath mounts for /var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volume-subpaths/iscsi-block-pv
W1003 11:58:15.804911   15460 mount_helper_common.go:33] Warning: Unmount skipped because path does not exist: /var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumes/kubernetes.io~iscsi/iscsi-block-pv
I1003 11:58:15.804989   15460 operation_generator.go:853] UnmountVolume.TearDown succeeded for volume "iscsi-block-pv" (OuterVolumeSpecName: "") pod "2e8310c1-a75d-44f1-9639-694ec1c4ab8d" (UID: "2e8310c1-a75d-44f1-9639-694ec1c4ab8d"). InnerVolumeSpecName "iscsi-block-pv". PluginName "kubernetes.io/iscsi", VolumeGidValue ""
E1003 11:58:15.805161   15460 operation_generator.go:868] UnmountVolume.MarkVolumeAsUnmounted failed for volume "" (UniqueName: "iscsi-block-pv") pod "2e8310c1-a75d-44f1-9639-694ec1c4ab8d" (UID: "2e8310c1-a75d-44f1-9639-694ec1c4ab8d") : no volume with the name "iscsi-block-pv" exists in the list of attached volumes
```

Interesting part is `volume: "kubernetes.io/iscsi/127.0.0.1:3260:iqn.2003-01.io.k8s:jsafrane:0" is not mounted`, everything goes bad from there.

Reason for the error is that kubelet checks if `/var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumeDevices/kubernetes.io~iscsi/` is symlink, while it should check `/var/lib/kubelet/pods/2e8310c1-a75d-44f1-9639-694ec1c4ab8d/volumeDevices/kubernetes.io~iscsi/iscsi-block-pv` instead.
 
Kubelet then just calls generic `cleanupMounts`, without putting the volume to ASW.

**Environment**:
- Kubernetes version (use `kubectl version`): today's master, 820b796c66744a8fcab1eebbf29ae223a65614d6

### PR DESCRIPTION
**Pull request by jsafrane**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

- Fix calculation of block device symlink path to check
- Fix reconstructed PV name in volume plugins that missed it. The PV must have a name, because it's used in a link name. I did not check CSI, because IMO the reconstruction needs #74026 fixed first.

**Which issue(s) this PR fixes**:
Fixes #83445

It fixes the issue on iSCSI. I tested on AWS too, it helps, still kubelet leaves global mount there, because the AWS plugin places global symlinks into
`/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-1d/vol-0cdf3ec1ac1149e0d`, while reconstructed volume does not have topology information and expects the symlink in `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/vol-0cdf3ec1ac1149e0d`. It is unrelated bug that's only on AWS.

**Does this PR introduce a user-facing change?**:
```release-note
Fixed cleanup of raw block devices after kubelet restart.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

cc @msau42 @jingxu97 @gnufied

### CODE REVIEW

**Comment by wongma7** [comment]
RE: aws, ConstructVolumeSpec already handled the case of different volume id format, I think ConstructBlockVolumeSpec simply needs to do the same thing: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/awsebs/aws_ebs.go#L266 . Then the volumeSpec will have the correct volumeID,  the plugin will return the correct volumeName, and finally reconstruct will check the correct GetPodDeviceMapPath. I will submit a patch soon

**Comment by wongma7** [comment]
/retest

lgtm (minus JSAF logs xd)

**Comment by jsafrane** [comment]
> lgtm (minus JSAF logs xd)


Fixed :-D

**Comment by jsafrane** [comment]
... and fixed disruptive block e2e tests:

1.To run
2. To check that global device symlink disappears

**Pull request merged**
