### PR TITLE
Make fake event recorder thread safe.

### PR DESCRIPTION
**Pull request by jsafrane**
I get frequent data race reports when unit testing my code because the event recorder is not thread safe.

I have a controller that starts a goroutine for potentially long operation. When the operation fails it emits an event to tell user that something went wrong. Now, my unit test pokes the controller with buggy data and expects that the event is emitted in the end. When I check that the event was recorded I get race with the goroutine emitting this event, as we both read/write `FakeRecorder.Events`. I don't have any locks in my goroutine and I do not want to add some just because of event recorder.

It seems that I am the first ever to read `FakeRecorder.Events`! So I made it private and added extra method to read it.

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot test this issue: #25169

**Comment by lavalamp** [comment]
You should consider putting a channel in this instead, for your test to read from. Otherwise how will you avoid your test being flaky if things take much longer than expected?

**Comment by jsafrane** [comment]
Reworked to channel, but I like it much less:

* Channel needs to be initialized, i.e. `NewFakeRecorder` is necessary.
* Channel has limited buffer. Current tests do not read it and I can't guarantee that it won't block in some of them.

**Comment by jsafrane** [comment]
Buffer for 1000 events is not enough, petset unit test was killed after 5 minutes... Reworked not to store events in the channel when nobody is interested in them.

**Comment by lavalamp** [comment]
Yup, sorry for not being clear, your second take is what I had in mind. Thanks! LGTM

**Pull request merged**
