### PR TITLE
[e2e] move Failf from e2e/framework to e2e/framework/log

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
[e2e] move Failf from `e2e/framework` to `e2e/framework/log`.
This is important to resolve circular dependencies.
Since there are so many references to `framework.Failf`, this is just the beginning!
There is still a lot of work to do. It is a Big Job.

**Which issue(s) this PR fixes**:

Ref #77095
Ref #77184

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
@andrewsykim Can you give me some advice ?

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/priority backlog

> There is still a lot of work to do. It is a Big Job.

indeed.

**Comment by oomichi** [comment]
nice work

/approve

**Pull request merged**
