### PR TITLE
Use auto mode networks instead of legacy networks in GCP

### PR DESCRIPTION
**Pull request by bowei**
Use of the --range flag creates legacy networks in GCP.

Legacy networks will not support new GCP features.

```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
@bowei Can we change this further to use a custom network and create a child subnetwork?  This would stop our quota issues whenever a region is added. I believe it'll also enable us to catch more bugs for features which require specifying subnets (ie ILB).

**Comment by bowei** [comment]
@nicksardo  I think the e2e tests already create a new network for each test, what specifically did you have in mind?

**Pull request merged**
