### PR TITLE
Automated cherry pick of #101380: fix TestMutatingWebhookResetsInvalidManagedFields flakes

### PR DESCRIPTION
**Pull request by kwiesmueller**
Cherry pick of #101380 on release-1.21.

#101380: fix TestMutatingWebhookResetsInvalidManagedFields flakes

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
/sig api-machinery
/wg api-expression
/cc @liggitt 
Hope this is correct, first cherry-pick.

**Comment by kwiesmueller** [comment]
@kubernetes/release-managers is this good for cherry picking?
Don't know about the release not label problem.

**Comment by liggitt** [comment]
+1 from my perspective, fix of a test-only flake introduced in 1.21 improves CI signal on the branch

can ping in slack on #release-management if you don't get a response

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
