### PR TITLE
Automated cherry pick of #96716: Bump node-problem-detector to v0.8.5

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #96716 on release-1.17.

#96716: Bump node-problem-detector to v0.8.5

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by wojtek-t** [comment]
/ok-to-test
/lgtm
/approve

@kubernetes/release-managers for cherrypick approval

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
