### PR TITLE
Automated cherry pick of #37248 #37401 #37362 #37303 origin release 1.4

### PR DESCRIPTION
**Pull request by jessfraz**
Automated cherry pick of #37248 #37401 #37362 #37303 origin release 1.4

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37864)

**Comment by jessfraz** [comment]
@k8s-bot test this #ignore

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
all green merging manually

**Pull request merged**
