### PR TITLE
Fix `default-container` announcement in 1.21 major themes

### LINKED ISSUE #100961: v1.21.0 changelog says "Default Container Labels" instead of "Default Container Annotations"
#### What happened:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#default-container-labels is wrong as it says default label can be specified, but KEP and other lines of changelog mentions annotation.

#### What you expected to happen:

Changelog is correct and consistent about  default container feature for kubectl.

#### Anything else we need to know?:

I'm still not able to get this feature to work actually for `kubectl logs`.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.0

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubectl cmd use  `the kubectl.kubernetes.io/default-container`  annotation for default container not label.
#### Which issue(s) this PR fixes:

Fixes #100961

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wilsonehusin** [comment]
Thanks for submitting the PR! Would you mind to put `NONE` on the release note block? I will get to this before/after #100968, whichever goes green first.

/triage accepted
/ok-to-test
/remove-kind bug
/kind documentation
/priority important-soon

**Comment by wilsonehusin** [comment]
/retitle Fix `default-container` announcement in 1.21 major themes

**Comment by pacoxu** [comment]
/assign @feiskyer
for approval

**Comment by wilsonehusin** [comment]
/approve

thanks @lojies!

**Pull request merged**
