### PR TITLE
Update to etcd client version 3.4.12

### LINKED ISSUE #93450: excessive watch cancellation logging on server shutdown
when a server is shut down, all watchers terminate, and are now logging that they are going to send a watch cancel request, and that they failed:
```
...
I0726 02:59:40.069592   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.069628   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
I0726 02:59:40.069770   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.069786   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
I0726 02:59:40.069864   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.069881   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
I0726 02:59:40.070058   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.070075   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
I0726 02:59:40.070236   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.070254   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
I0726 02:59:40.070379   54198 ???:1] sending watch cancel request for closed watcher{watch-id 11 0  <nil>}
W0726 02:59:40.070394   54198 ???:1] failed to send watch cancel request{watch-id 11 0  <nil>} {error 25 0  EOF}
...
```

looks like this was added in etcd in https://github.com/etcd-io/etcd/pull/11850 and picked to 3.4.10 in https://github.com/etcd-io/etcd/pull/12055

/cc @jingyih  @jpbetz

### LINKED ISSUE #94099: bazel-test-master - panic: field etcdserverpb.Request.ID has invalid type
**Which jobs are flaking**:
bazel-test-master
**Which test(s) are flaking**:
Showing up as **Overall** on TestGrid

The Test Names on TG are not presented as they are for e2e tests (Could this be because these are unit tests?)

Here are the Tests where the Panic occurs
- TestAllocatedLocallyButReleasedStorage
- TestServiceRegistryIPUpdate
- TestServiceRegistryUpdateExternalService
- TestServiceRegistryDeleteExternal
- TestShortNames
 
**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
`panic: field etcdserverpb.Request.ID has invalid type: got uint64, want pointer`

**Anything else we need to know**:
The panic has been noted in this (now closed) issue  #92070 This issue ended up bringing in an etcd fix.
So I guess first port of call is to see if we are somehow not picking up this etcd fix here?
 
**Specific failures on Prow's Spyglass**
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1295783299414757376
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1295675944714899459
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1294002990276939777

- links to go.k8s.io/triage appreciated

I had problems finding this error on triage will investigate further

/kind flake
/sig testing
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Updates to etcd client library 3.4.12:
* fixes https://github.com/kubernetes/kubernetes/issues/93450
* fixes https://github.com/kubernetes/kubernetes/issues/94099

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/area etcd
/cc @jingyih 
/sig api-machinery
/milestone v1.19

### CODE REVIEW

**Comment by jingyih** [comment]
cc @kubernetes/release-engineering

**Comment by BenTheElder** [comment]
will we also update the server?

**Comment by liggitt** [comment]
> will we also update the server?

no, we're sticking with 3.4.9 until https://github.com/etcd-io/etcd/issues/12144 / https://github.com/etcd-io/etcd/issues/12148 are resolved

**Comment by BenTheElder** [comment]
Those two issues appear to be closed with only a changelog update? Is there somewhere better to track the resolution?

**Comment by liggitt** [comment]
hmm... @jingyih, any suggestions?

**Comment by BenTheElder** [comment]
related https://github.com/kubernetes/kubernetes/pull/94102

**Pull request merged**
