### PR TITLE
kubeadm: move `getClientSet` to cmd utils

### PR DESCRIPTION
**Pull request by chendave**
`getClientSet` is used by both cmd `token` and `reset`, move this
method to cmd utils to decouple it from one specific cmd.

Signed-off-by: Dave Chen <dave.chen@arm.com>

/sig cluster-lifecycle

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
failure of `pull-kubernetes-verify-govet-levee` is irrelated as what I observed here: https://github.com/kubernetes/kubernetes/pull/111339

**Comment by chendave** [comment]
> failure of pull-kubernetes-verify-govet-levee is irrelated as what I observed here: https://github.com/kubernetes/kubernetes/pull/111339

the issue was tracked here: https://github.com/kubernetes/kubernetes/issues/111452

**Review by neolit123 — COMMENTED** [review]
thanks
/approve
/triage accepted

**Comment by nikhita** [comment]
/test pull-kubernetes-verify-govet-levee
test is fixed in https://github.com/kubernetes/test-infra/pull/26931

**Comment by chendave** [comment]
@neolit123  can you pls also LGTM on this?

**Pull request merged**
