### PR TITLE
Updates CoreOS cloud-configs to use Kubernetes 0.19.3.

### LINKED ISSUE #9075: Do not break CoreOS when deprecating kubernetes-ro
CoreOS does not have an equivalent to "kube-addons.sh", and so there are not system secrets created when the cluster is created.   So, when some of our CoreOS users run things like the Hazelcast example, or the elasticsearch example, they currently rely on kubernetes-ro to reach the apiserver.  When kuberenetes-ro support is removed (#8155), these examples will still work on GCE, because they can use the kubeconfig in their associated secret.  But, on CoreOS, it seems they will break.

Possible fix alternatives:
  1. Change #8155 to not remove support for the --readonly_port feature, but default it to off for GCE.
  1. Change all known examples to include instructions on how to generate a secret when setting up the example.
  1. Extend CoreOS cluster setup to include the kube-addons.sh secret-creation functionality.
  1. @lavalamp has a plan that uses a proxy in a sidecar.

Option 1 is nice because it allows us to defer fixing the problem until after 1.0 freeze.

### PR DESCRIPTION
**Pull request by pires**
- Fixes #9075
- Added instrumentation and configuration for service account tokens.
- Removed standalone stuff.
- Removed  Docker proxy cache stuff because it makes deployments slower and its usage is very limited.

/cc @thockin @AntonioMeireles @liggitt 

This has been tested with GCE and AWS. I **did not** update Azure, AWS CloudFront and other cloud-configs because I'm unable to test them. Please, CC their maintainers.

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
LGTM (&& thanks @pires !!!!)

**Comment by WIZARD-CXY** [comment]
Want to learn how you deal with service account tokens to apply it to ubuntu k8s deployment.

**Comment by pires** [comment]
@WIZARD-CXY See https://github.com/GoogleCloudPlatform/kubernetes/issues/9075#issuecomment-115042337

**Comment by WIZARD-CXY** [comment]
Thanks a lot!

May the force be with you

**Comment by mbforbes** [comment]
@thockin for triage, first review, and (hopefully) finding the second

**Comment by pires** [comment]
@mbforbes looks like @thockin lost track of this cause he's still looking for it. Care to ping him again?

**Comment by mbforbes** [comment]
Whoops sorry about that. 

(BTW needs rebase)

Let me assign to our current oncall to possibly multiplex better

**Comment by zmerlynn** [comment]
Needs rebase.

**Comment by pires** [comment]
Yeah, but now 3 newer versions have been released. So please, merge this and I'll take care of testing when 1.0 is out and update accordingly.

**Comment by zmerlynn** [comment]
GSG only fix. Merging.

**Comment by devurandom** [comment]
Can you please explain why you removed kube-register? Is that integrated into core Kubernetes now?

**Comment by devurandom** [comment]
I found https://github.com/GoogleCloudPlatform/kubernetes/pull/9303#issuecomment-109327392, which explains that kube-register is not needed since self-registration works. This was merged for 0.19.0.

**Pull request merged**
