### PR TITLE
Log when pod expires in scheduler

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #37232

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37284)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot gce node test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot node test this, issue: #IGNORE

**Comment by dims** [comment]
@k8s-bot test this

**Comment by dims** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot test this, issue: #IGNORE (error in queueing build)

**Comment by wojtek-t** [comment]
@k8s-bot etcd3 test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot kubemark test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot gci gke test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot kops test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot gke test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot gke test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this, issue: #IGNORE (Error queueing build.)

**Comment by wojtek-t** [comment]
Simple rebase.

**Comment by wojtek-t** [comment]
@k8s-bot etcd3 test this, issue: #IGNORE (error in queue)

**Comment by wojtek-t** [comment]
@k8s-bot node e2e test this, issue: #IGNORE (waiting for status to be reported)

**Comment by wojtek-t** [comment]
@k8s-bot kops test this, issue: #IGNORE

**Comment by saad-ali** [comment]
Does this need to be cherry-picked to 1.5? If so make sure to add `cherrypick-candidate` label

**Comment by wojtek-t** [comment]
It doesn't - it was purely extended logging in tests for debugging purposes.

**Comment by saad-ali** [comment]
> It doesn't - it was purely extended logging in tests for debugging purposes.

Ack. Thanks. Removing 1.5 milestone.

**Pull request merged**
