### PR TITLE
e2e: fix error checking in kubelet stats

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM. :-)

**Comment by yujuhong** [comment]
Thanks! This fixes the gce-serial suite (not a submit queue blocker) and should probably be merged sooner than later. @k8s-oncall

**Comment by lavalamp** [comment]
Build-cop merge.

**Comment by lavalamp** [comment]
Does this really need a release note?

**Comment by yujuhong** [comment]
> Does this really need a release note?

It needs to be cherry-picked to 1.2 with #24003, unfortunately.

**Pull request merged**
