### PR TITLE
Add a dockercfg-path parameter to the Mesos scheduler

### PR DESCRIPTION
**Pull request by MatMaul**
handle mesosphere/kubernetes-mesos#86

### CODE REVIEW

**Comment by MatMaul** [comment]
Regarding CLA : I should use a freshly created company CLA. The associated google group is ens-innovation-lab (Atos Toulouse), and I am in it.

**Comment by MatMaul** [comment]
I signed it!

**Comment by jdef** [comment]
LGTM. Please squash

**Comment by MatMaul** [comment]
Done.  I have no idea why it fails some tests with Go 1.3, it doesn't seem related to my change.

**Comment by jdef** [comment]
shipable build failed due to unrelated upstream integration test.

**Comment by bprashanth** [comment]
Kicked shippable

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Pull request merged**
