### PR TITLE
Clarify that contributions need to be from CLA-signers.

### PR DESCRIPTION
**Pull request by zmerlynn**

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @brendandburns

I did, in fact, clarify this with a lawyercat on our side, but I think it deserves some verbiage *somewhere*.

**Comment by zmerlynn** [comment]
(More context: https://github.com/GoogleCloudPlatform/kubernetes/pull/10049/files#r36242257, cc @karlkfi)

**Comment by alex-mohr** [comment]
Thanks Zach!  LGTM

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
