### PR TITLE
Update redis example to use alpine:3.4 as image

### PR DESCRIPTION
**Pull request by aledbf**
```
kubernetes/redis    v2                  40e584663e63        5 minutes ago       58.25 MB
kubernetes/redis    v1                  de309495e6c7        13 months ago       146 MB
```

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/21424)

### CODE REVIEW

**Comment by thockin** [comment]
As with all Alpine discussions - Alpine's DNS is broken.  Are we *sure* that this container will never need to DNS lookup anything in the kubernetes DNS space?  Is there something that is maybe not Alpine but is in the same lower-end size range that we could use?  busybox-glibc?

**Comment by thockin** [comment]
Or can we get a new Alpine image with musl 1.1.13 ?  That should have search path support.

**Comment by aledbf** [comment]
@thockin in this case alpine will work. That said I think is better to wait for this https://github.com/kubernetes/contrib/pull/525
```
redis             0.2                 36ae1080301a        About an hour ago   56.96 MB
```

> busybox-glibc?

the issue with busybox is the lack of packages (installing opkg is painful)

**Comment by aledbf** [comment]
> Alpine image with musl 1.1.13 ?

I tried that but to be honest I prefer to remove any potential issue with dns

**Comment by thockin** [comment]
I will see if I can get upstream alpine to cut a new release with a new musl

**Comment by aledbf** [comment]
@thockin `alpine:edge` already includes musl 1.1.13

**Comment by thockin** [comment]
Awesome!  Once that gets promoted to :latest, we can rebuild a bunch of
stuff.

**Comment by aledbf** [comment]
ping @thockin

**Comment by thockin** [comment]
This still only works on alpine:edge, not 3.3

```
$ docker run -ti --dns-search=google.com --dns=8.8.8.8 alpine:edge nslookup www
nslookup: can't resolve '(null)': Name does not resolve

Name:      www
Address 1: 216.58.194.164 sfo07s13-in-f4.1e100.net
Address 2: 2607:f8b0:4005:805::2004 sfo03s01-in-x04.1e100.net

$ docker run -ti --dns-search=google.com --dns=8.8.8.8 alpine:3.3 nslookup www
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'www': Name does not resolve

$ docker run -ti --dns-search=google.com --dns=8.8.8.8 alpine:latest nslookup www
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'www': Name does not resolve
```

**Comment by thockin** [comment]
I re-titled this to ubuntu-slim to match code, but i am wary.  Do we really want to manage a copy of ubuntu that we have to periodically update?

**Comment by aledbf** [comment]
> Do we really want to manage a copy of ubuntu that we have to periodically update?

Good question. From my point of view I don't see a real alternative until the next stable version of alpine

That said I repeat one of my comments: honestly I prefer to remove any potential issue with dns. `ubuntu-slim` is not alpine but 55MB is not bad considering is Ubuntu.

**Comment by thockin** [comment]
https://github.com/gliderlabs/docker-alpine/issues/165

Can we wait for an answer there?

**Comment by thockin** [comment]
It looks like the next Alpine build is due in a couple weeks - can this wait a little more?

**Comment by aledbf** [comment]
> can this wait a little more?

sure

**Comment by bprashanth** [comment]
> I re-titled this to ubuntu-slim to match code, but i am wary. Do we really want to manage a copy of ubuntu that we have to periodically update?

Yeah I think somehow users really want small images, its a number that one can easily acquire and compare. And the most likely candidates are busybox and alpine. Busybox is inadequate for a lot of things, at the very least you can't just apt-get in there, so alpine is a frequent candidate for random contrib project X. Except when it gets popular and things don't work because of DNS. 

So ubuntu-slim is a decent middle-ground IMO, that's why it's in contrib.

**Comment by thockin** [comment]
The problem with ubuntu-slim is that *we* are beholden to rebuild it when
upstream images change, and I just don't think we want to do that.

**Comment by bprashanth** [comment]
Agreed, but we did rebuild a bunch of images anyway when a CVE hits. I don't think we should need more than 1 standard goto image. Best case alpine is it, but I didn't really want to wait around hoping.

**Comment by bprashanth** [comment]
To clarify, I'm totally fine the direction this is heading in, just leaving my 2c :)
I didn't mean don't wait now

**Comment by therc** [comment]
Alpine 3.4 with the new musl is coming out today:

http://git.alpinelinux.org/cgit/aports/patch/?id=00864455a5b1ef971280c32347288d7f6f14e5a1

**Comment by aledbf** [comment]
ping @thockin

**Comment by thockin** [comment]
YAYAY!!!!

**Comment by thockin** [comment]
@bgrant0607 @goltermann Are we allowing examples in for 1.3 still?

**Comment by thockin** [comment]
If so, please milestone this in my absence.

**Comment by goltermann** [comment]
Adding v1.3 milestone - this meets our current bar.

**Comment by bgrant0607** [comment]
@thockin Who pushed the new image?

cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
@bgrant0607 / @thockin we have run into some serious problems with at least java and alpine 3.4 ... just an FYI.  I would encourage us to not using 3.4 until it is a tad more stable.  The googe/docker is pretty thin as it is.

cc: @mward29

**Pull request merged**
