### PR TITLE
Revert "kubelet: fix fail to close kubelet->API connections on heartbeat failure"

### LINKED ISSUE #100849: kubelet don't share transport by default after #95427
#### What happened:
In #95427, client-go don't share transport when c.Dial is not nil, https://github.com/kubernetes/kubernetes/blob/b0abe89ae259d5e891887414cb0e5f81c969c697/staging/src/k8s.io/client-go/transport/cache.go#L136
but kubelet custorm Dial by default, https://github.com/kubernetes/kubernetes/blob/b0abe89ae259d5e891887414cb0e5f81c969c697/cmd/kubelet/app/server.go#L929

After PR is integrated, the connections between kubelet and kube-apiserver in our cluster with 4000 nodes increases by five times.

#### What you expected to happen:
kubelet share transport by default, one kubelet only keep one connection to kube-apiserver.
@liggitt 

#### Anything else we need to know?:
start kubelet with rotate-certificates=false

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):EulerOS 2.9
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chenyw1990**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In https://github.com/kubernetes/kubernetes/pull/78016, there is a discuss about another solution
> As discussed in kubernetes/client-go#374, another way to fix this is using http/2.0's ping frame to keep connection alive and identify failed connections. but it seems to be a long-term solution.

after https://github.com/kubernetes/kubernetes/pull/96778 client-go has HTTP 2.0 health check,  so we don't need this change.

#### Which issue(s) this PR fixes:

Fixes #100849

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ehashman** [comment]
/retest

flake #99979

**Comment by ehashman** [comment]
Has @liggitt's comment been addressed? https://github.com/kubernetes/kubernetes/issues/100849#issuecomment-814577546 He stated this was working as intended.

**Comment by KubeStacker** [comment]
Hi  @chenyw1990  any update on this ?

**Comment by chenyw1990** [comment]
Hi @KubeStacker 
I added a comment waiting for liggitt's final confirmation.
https://github.com/kubernetes/kubernetes/issues/100849#issuecomment-913303930

**Comment by liggitt** [comment]
/hold

pending question about kubelet use of http/2 in https://github.com/kubernetes/kubernetes/issues/100849#issuecomment-914328079

**Comment by chenyw1990** [comment]
This PR is duplicated with #104844, so close it

/close

**Pull request closed without merging**
