### PR TITLE
test/e2e: fix GetCurrentKubeletConfig

### PR DESCRIPTION
**Pull request by marquiz**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Fixes getting of kubelet config through the configz endpoint in end-to-end tests in some scenarios. 

Seemingly on slow connections if the response to /configz request was
chunked the kubectl proxy was terminated before the response body was
received and read, causing unexpected EOF errors. This patch changes the
configz polling code so that the whole response body is read before
closing the proxy connection.

#### Special notes for your reviewer:

Faced the problem when reviewing/testing/debugging https://github.com/kubernetes-sigs/node-feature-discovery/pull/528. NFD e2e tests use the kubernetes e2e framework.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
I think the problem highlighted here is real, and explains some weird behaviour I've seen in the past. I think this code change is in the right direction, but I wonder if the current implementation -which is indeed an improvement- can be improved further.
Would it make sense to move the response read inside the pollImmediate loop body? would that make the code a bit more robust?

**Comment by aojea** [comment]
> Would it make sense to move the response read inside the pollImmediate loop body? would that make the code a bit more robust?

yes, also close the connection the body before retrying

**Comment by marquiz** [comment]
Thankls for the review @fromanirh and @aojea! There's certainly room for improvement as this was quick'ish PR after I finally figured out what was the issue last night 😇


> Would it make sense to move the response read inside the pollImmediate loop body? would that make the code a bit more robust?

Makes sense. Done.

> yes, also close the body before retrying

Good point. Done.

**Review by ffromani — COMMENTED** [review]
/lgtm
thanks @marquiz . From my POV now the code is as good as it can be.
I'll defer to the testing expert the final approval

**Comment by aojea** [comment]
/lgtm
/approve
Thanks

**Pull request merged**
