### PR TITLE
Remove kubeadm fuzzer from api testing

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
from @sttts https://github.com/kubernetes/kubernetes/pull/55961#discussion_r151926499
>Please only add fuzzer for apiserver types here, not for configs only used locally. Look for roundtrip_test.go files in the code-base. There are some more which have local fuzzers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: https://github.com/kubernetes/kubernetes/pull/55961#discussion_r151926499

**Special notes for your reviewer**:
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by luxas** [comment]
not sure how important we consider this issue to be.
Important enough for v1.9 or just let this cleanup slip?

**Comment by xiangpengzhao** [comment]
>not sure how important we consider this issue to be.
Important enough for v1.9 or just let this cleanup slip?

IMO, it's not important. It doesn't fix any bug. Leave it to next train would be ok.

**Comment by roberthbailey** [comment]
@kubernetes/sig-api-machinery-pr-reviews

**Comment by luxas** [comment]
Not sure why the "no-issue" hadn't any effect there...

**Pull request merged**
