### PR TITLE
Make sure etcd2 actually gets started

### PR DESCRIPTION
**Pull request by matthughes**
Need to actually start etcd2.  Right now it is just being configured and using the CoreOS Openstack image, nothing else is starting etcd2.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot test this github issu: #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this again please, issue #IGNORE (I accidentally broke one of the Jenkins slaves)

**Comment by ixdy** [comment]
Sorry again.
@k8s-bot unit test this again please, issue #IGNORE (I accidentally broke one of the Jenkins slaves)

**Comment by ixdy** [comment]
@k8s-bot e2e test this please, issue #21798

**Comment by ixdy** [comment]
@k8s-bot unit test this again please, issue #IGNORE

I give up.

**Pull request merged**
