### PR TITLE
Remove broken link in changelog-1.2

### PR DESCRIPTION
**Pull request by chymy**
Signed-off-by: chymy <chang.min1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chymy** [comment]
/assign @justaugustus 

Thanks!

**Comment by chymy** [comment]
/assign @feiskyer

Thanks!

**Comment by justaugustus** [comment]
@chymy -- Same comment as https://github.com/kubernetes/kubernetes/pull/97943#issuecomment-766252238.

In future, there is no reason to tag multiple reviewers for a changelog fix, much less in separate comments.

You'll be able to tell who is responsible for reviewing a change by:
- who is automatically tagged for review by Prow + GitHub
- bot comments that suggest an approver (https://github.com/kubernetes/kubernetes/pull/97943#issuecomment-758365755)

In this case: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/OWNERS

https://github.com/kubernetes/kubernetes/blob/676079605da916df0557de55ca544fda296d5752/OWNERS_ALIASES#L118-L137

You can read more on OWNERS here: https://go.k8s.io/owners

/unassign @justaugustus @cpanato 
/assign @wilsonehusin 
/ok-to-test
/triage accepted

**Comment by chymy** [comment]
Get it. Thank you very much @justaugustus.

**Comment by wilsonehusin** [comment]
Hey @chymy, thanks for the PR. In general, I don't think we should continue maintaining outdated documents especially for [releases we no longer maintain](https://kubernetes.io/docs/setup/release/version-skew-policy/). Kubernetes 1.2 reached end-of-life in 2016, so I'm going to close this.

/close

**Pull request closed without merging**
