### PR TITLE
Delete fails on notfound errors.

### LINKED ISSUE #8218: kubectl delete doesn't return error or print resource not found
If you run `kubectl delete resource <non_existent_resource_name>`, kubectl exits with 0 and prints nothing.

E.g.
```
$ ./cluster/kubectl.sh delete pod abc
$ echo $?
0
```
I expected to see a "resource not found" message and/or an error code when this occurred. It's very misleading when you type the wrong resource name and think you delete it.

### PR DESCRIPTION
**Pull request by j3ffml**
If deleting multiple resources, command will continue on error and
report not found resources at the end. You can ignore not found errors (previous behavior) by passing `--ignore-not-found`. 

Closes #8218

### CODE REVIEW

**Comment by jlowdermilk** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM

**Comment by thockin** [comment]
rebase

**Comment by thockin** [comment]
Fails CI

**Comment by jlowdermilk** [comment]
Whoops, I accidentally rebased/pushed from an older repo. Rebased the correct one now. PTAL.

**Pull request merged**
