### PR TITLE
Automated cherry pick of #23223

### PR DESCRIPTION
**Pull request by mikedanese**
Cherry pick of #23223 on release-1.2.

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @david-mcmahon @davidopp

**Comment by davidopp** [comment]
LGTM

**Comment by bgrant0607** [comment]
Tests failed. Also, the original PR hasn't even merged into master yet.

**Comment by mikedanese** [comment]
this is a new one for me:
```
+++ [0324 15:25:36] Placing binaries
+ godep go install ./...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /workspace/kubernetes
godep: [WARNING]:	$GOPATH: /go
+ ./hack/install-etcd.sh
curl: (18) transfer closed with 6395410 bytes remaining to read

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
!!! Error in /workspace/kubernetes/hack/lib/etcd.sh:71
  'tar xzf -' exited with status 18 2
```

@k8s-bot unit test this please issue: #IGNORE

**Comment by bgrant0607** [comment]
verify-godeps is failing in master.

**Comment by eparis** [comment]
```
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:   Current Directory: /workspace/kubernetes
godep: [WARNING]:   $GOPATH: /go
```

Is meaningless and should be ignored. (Those are the ONLY 4 lines I'm saying this about however)

**Comment by davidopp** [comment]
Why did the bot add "do-not-merge" label? There are no doc changes here.

**Comment by eparis** [comment]
I believe the bot said why it did it: https://github.com/kubernetes/kubernetes/pull/23456#issuecomment-201062430
```
This PR is not for the master branch but does not have the cherrypick-approved label. Adding the do-not-merge label.
```

**Comment by bgrant0607** [comment]
@davidopp See https://github.com/kubernetes/kubernetes/pull/23456#issuecomment-201062430

**Comment by davidopp** [comment]
So am I allowed to add cherrypick-approved, or do we wait until whoever is doing them as a batch does them all at once? We definitely want this in 1.2.1

**Comment by eparis** [comment]
@bgrant0607 has been adding the label. We should ask him to review this / #23223

**Pull request merged**
