### PR TITLE
Remove ExternalTrafficLocalOnly from kube_feature gate

### LINKED ISSUE #56645: [CLEANUP] Remove left over feature gate checks for ESIPP
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind cleanup
/sig network

**What happened**:
Ref https://github.com/kubernetes/kubernetes/pull/56562, https://github.com/kubernetes/kubernetes/pull/45857, https://github.com/kubernetes/kubernetes/issues/46404.

There are a few left over feature gate checks in https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go and probably somewhere else that have no effect. Would be great to clean it up.

/assign

### PR DESCRIPTION
**Pull request by MrHohn**
*What this PR does / why we need it**:
This PR is for v1.10.

External Source IP Preservation (ESIPP) had been promoted to GA since 1.7. Following the proposal on https://github.com/kubernetes/kubernetes/issues/46404#issuecomment-303939180, we should be able to remove it from feature gate now.

Added release note to announce this.

Also ref the previous attempt: https://github.com/kubernetes/kubernetes/pull/45857.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56645

**Special notes for your reviewer**:

**Release note**:

```release-note
"ExternalTrafficLocalOnly" has been removed from feature gate. It has been a GA feature since v1.7.
```

### CODE REVIEW

**Comment by m1093782566** [comment]
proxier part changes looks good to me.

/lgtm

**Review by tengqm — APPROVED** [review]

**Pull request merged**
