### PR TITLE
fix the overlapped leftside nav entries

### PR DESCRIPTION
**Pull request by caesarxuchao**
see the wrapped lines in the red rectangular for example
screenshot from 2015-07-19 14 30 34

@thockin @RichieEscarez @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Definitely need to fix this. I'll let @thockin review and merge, though, since I'm not at all familiar with the formatting.

**Comment by RichieEscarez** [comment]
Hi Chao, per our conversation, ill add this to my PR which will include a fix for the sub menu as well as all the work ive done to the nav menu. As discussed, ive added these changes to my branch and will close this.

**Comment by thockin** [comment]
Richie - is your PR about ready for testing?

**Comment by RichieEscarez** [comment]
@thockin, yes, just opened #11566

**Pull request closed without merging**
