### PR TITLE
Scheduler: replace system modeler with scheduler cache and do O(1) lookup for resource req

### PR DESCRIPTION
**Pull request by hongchaodeng**
Follow up on  #22189.
Please see the second commit for the fix.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
I confirmed that the e2e test "MaxPods" in scheduler_predicates is fixed now.

**Comment by wojtek-t** [comment]
@hongchaodeng - sorry I didn't get to it today (I spend most of the day debugging other regressions). Hopefully will get to it tomorrow.

**Comment by wojtek-t** [comment]
@hongchaodeng - these changes LGTM, but I would like to hold on with this until 1.2 release is cut (I think we will be able to merge it next week).

However, can you explain me how this change is fixing the problem? What exactly the problem was?
Thanks!

**Comment by hongchaodeng** [comment]
> However, can you explain me how this change is fixing the problem? What exactly the problem was?

If a pod was expired, the pod state would be gone. Then if the pod was added back, we should also make the pod state to be *Added*. 

The logic was correct in my initial commits so the jenkins wasn't failing at the beginning. However, remember that in only the last round we refactored the pod state thing and unfortunately it was NOT added back. Now the state machine checking failed.

Why flaky?
- The add logic is still correct. So if a pod is added, the information would be right.
- The failure was time racy in Update or Delete. If a pod was expired, which took ~30 seconds, then the state machine is completely wrong.

**Comment by davidopp** [comment]
@wojtek-t Why do you think we should leave this out of 1.2? Wouldn't it be better to not have the test flake?

**Comment by wojtek-t** [comment]
@hongchaodeng 

>
Why flaky?
The add logic is still correct. So if a pod is added, the information would be right.
The failure was time racy in Update or Delete. If a pod was expired, which took ~30 seconds, then the state machine is completely wrong.

Sorry - I wasn't clear enough. I understand your changes and what problem you are fixing.

The thing I do NOT understand is why it is supposed to fix the flake. It's just impossible than in a healthy 3-4- node cluster pods are expiring. It is just not happening (and for sure not in every second test run).
It must be something different. It's possible that this is a fix for it, but I would like to understand why. And expiring pods is not explanation.


@davidopp - I'm fine with cherry-picking it to 1.2, but not without understanding why this helps (and I do not understand it). If someone can expain it to me, I won't be blocking it.

**Comment by wojtek-t** [comment]
@hongchaodeng - did you have chance to look into it? I still don't believe that expiring pods were the reason of failures.
But once we understand the problem and believe that this PR fixes it, we may consider merging this into 1.2.

**Comment by hongchaodeng** [comment]
Sure. I will look into it today.

**Comment by hongchaodeng** [comment]
I couldn't reproduce the problems by running "validate MaxPods" twice.
I tried the commit at f29a1d6c5c63661d259f7119670ac1f6245bf481 and just reverting the revert #22355.

@gmarek Do you keep notes of the commit that you can reproduce it? If you run into the problem again, could you share the scheduler log?

**Comment by hongchaodeng** [comment]
At the mean time, I figured out why the scheduler was printing out errors. There were some "kube-system" pods that were assigned without scheduling. The pod state check was wrong in such case.

**Comment by wojtek-t** [comment]
>
At the mean time, I figured out why the scheduler was printing out errors. There were some "kube-system" pods that were assigned without scheduling. The pod state check was wrong in such case.

And that's the mystery, I think. That makes perfect sense to me now.
And it also explains why your change is fixing things. 
@davidopp - in my opinion that explains things and now I'm fine with proceeding with this PR.

Let me take another look later today.

**Comment by wojtek-t** [comment]
Well - actually I think it doesn't explain those issues now.
The only problem that it explains are errors that are generated in case of "UpdatePod" of those static pods.

The NodeInfo for that node should be correct once the pod was added... (unless I'm missing something).

**Comment by hongchaodeng** [comment]
> The NodeInfo for that node should be correct once the pod was added...

That's what I thought and tried to figure out. Either there is still problem in the code or sequences with test break the assumption. The problem is that I can't reproduce that.

**Comment by hongchaodeng** [comment]
I did make the second test reliably failed at commit c4ffcbdbaa0ec51555fa404309e13a86ccca7db5.

But the failure isn't about scheduling:
```
Mar 10 20:54:38.294: INFO: At 2016-03-10 20:46:26 +0000 UTC - event for maxp-264: {kubelet e2e-test-ubuntu-minion-ukmj} FailedSync: (events with common reason combined)
Mar 10 20:54:38.294: INFO: At 2016-03-10 20:46:26 +0000 UTC - event for maxp-287: {kubelet e2e-test-ubuntu-minion-ukmj} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 96259dad5d7a2f5b2991d457a0b7b1515709ad71c7be081421cc1ab317b6e869: no available IPv4 addresses on this network's address pools: bridge (5d1b7e86634b2ccb2cf99476ebfee7593352a0032caaae5866f021e4c4f4eca3)\n"
Mar 10 20:54:38.294: INFO: At 2016-03-10 20:46:26 +0000 UTC - event for maxp-264: {kubelet e2e-test-ubuntu-minion-ukmj} FailedSync: (events with common reason combined)
Mar 10 20:54:38.294: INFO: At 2016-03-10 20:46:26 +0000 UTC - event for maxp-287: {kubelet e2e-test-ubuntu-minion-ukmj} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 96259dad5d7a2f5b2991d457a0b7b1515709ad71c7be081421cc1ab317b6e869: no available IPv4 addresses on this network's address pools: bridge (5d1b7e86634b2ccb2cf99476ebfee7593352a0032caaae5866f021e4c4f4eca3)\n"
```

```
 validates MaxPods limit number of pods that are allowed to run [Slow] [It]
  ...
  Expected error:
      <*errors.errorString | 0xc208c161c0>: {
          s: "Timeout while waiting for pods with labels \"startPodsID=c2b2aefc-e700-11e5-86f7-42010af00002\" to be running",
      }
      Timeout while waiting for pods with labels "startPodsID=c2b2aefc-e700-11e5-86f7-42010af00002" to be running
  not to have occurred
```

**Comment by wojtek-t** [comment]
OK - your explanation from https://github.com/kubernetes/kubernetes/issues/22189#issuecomment-195108218 makes perfect sense and explains things.
I'm happy with this PR now.

@hongchaodeng - can you please rebase?

**Comment by davidopp** [comment]
ref/ #18831

**Comment by hongchaodeng** [comment]
@wojtek-t 
Rebased, fixed docs and code, also with minor improvement. PTAL!

**Comment by wojtek-t** [comment]
@hongchaodeng - thanks for the changes!
Can you please squash the commits?

**Comment by hongchaodeng** [comment]
Squashed commits

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
