### PR TITLE
Fixed API server portal_net flag that could break service networking on CoreOS

### PR DESCRIPTION
**Pull request by pires**
Fixed API server portal_net flag that could break service networking by assigning an IP address from a subnet already allocated to a node to a service.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
That flag may actually be correct as is. /cc @brendandburns, @cjcullen

**Comment by thockin** [comment]
Looks OK to me, but I don't have context on CoreOS...

**Comment by pires** [comment]
@jlowdermilk at first, I assumed the same but ```portal_net``` defines a subnet to be used for service IP allocation and you don't want that to clash with flannel subnet allocation to nodes.

**Comment by mbforbes** [comment]
Temporarily assigning to networks guru @cjcullen; CJ, feel free to re-assign or give to me and I can look into it.

**Comment by pires** [comment]
Any updates?

**Comment by cjcullen** [comment]
Sorry for the lag. This LGTM. We don't want the portal_net to be the same CIDR as what Flannel is using, so 10.100.0.0/16 should be good.

**Pull request merged**
