### PR TITLE
Use net.IP.Equal to compare net.IPs instead of bytes.Equal

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
cleanup. Use net.IP.Equal() instead of bytes.Equal()

#Example
package main

import (
	"fmt"
	"net"
)

func main() {
	fmt.Println(net.IP.Equal(net.IP("1.1.1.1"), net.IP("2.2.2.2")))
	fmt.Println(net.IP.Equal(net.IP("1.1.1.1"), net.IP("1.1.1.1")))
	fmt.Println(net.IP.Equal(net.IP("2001:db8:a0b:12f0::1"), net.IP("2001:db8:a0b:12f0::1")))
}

**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@kubernetes/sig-network-pr-reviews 
/assign @thockin

**Comment by gaurav1086** [comment]
@thockin thank you. Let's merge this.

**Review by cmluciano — COMMENTED** [review]
Can you rebase this so that we can make sure to give it another look?

**Comment by gaurav1086** [comment]
@cmluciano , this change is not needed anymore. Closing.

**Pull request closed without merging**
