### PR TITLE
Remove deprecated init-container in annotations

### LINKED ISSUE #41004: Enhancement for init containers annotation.
After #38382 , the InitContainers feature was promoted go GA; but the beta annotation value will still be respected and overrides the field value. Open this issue to trace the enhancement for initContainer annotation. Sub-tasks in my mind:

- [ ] set defaults for initContainer in annotation (refer to https://github.com/kubernetes/kubernetes/pull/39713#issuecomment-277128214 for the reason of this task)
- [ ] enhance `podutil.SetInitContainersAndStatuses` based on #31026
- [ ] use `podutil.SetInitContainersAndStatuses` in `conversion.go` to avoid duplicated code (avoid code missed before removing annotation and easy to remove when graduate).

### LINKED ISSUE #47264: kubectl apply ignoring changes to spec.initcontainers field
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:07Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1409.1.0
- **Kernel** (e.g. `uname -a`): Linux 4.11.2-coreos #1 SMP Tue May 23 22:04:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
`kubectl apply` ignores changes in `spec.initcontainers` field. The `spec.initContainers` field is also mirrored into alpha and beta annotations. I think the annotations from the previous run overwrite the changes specified in `spec.initcontainers` field. If I apply my changes as annotations, it works. Also, there is no `--feature-gates` option in kube-apiserver to turn it off annotations for initcontainers.

**What you expected to happen**:
`spec.initcontainers` changes should trump over annotations

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment with `spec.initcontainer` field populated in pod template. Apply the deployment. Make changes `spec.initcontainer` field and apply again. kubectl says deployment is configured but your changes are not applied

### LINKED ISSUE #50655: Remove deprecated init-container in annotations
Init containers have already graduated to GA in 1.6, we should remove the annotations.

/sig api-machinery node
/assign

### PR DESCRIPTION
**Pull request by liggitt**
fixes #50655
closes #41004
fixes #47264

Builds on #50654 and drops the initContainer annotations on conversion to prevent bypassing API server validation/security and targeting version-skewed kubelets that still honor the annotations

```release-note
The deprecated alpha and beta initContainer annotations are no longer supported. Init containers must be specified using the initContainers field in the pod spec.
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@liggitt sorry for the delay in #50654. Thanks for the following commit! :smile:

**Comment by xiangpengzhao** [comment]
@liggitt one newbie question on git: how to combine an unmerged commit into my branch from other's branch? Thanks! I see you did this in this PR.

**Comment by liggitt** [comment]
fetch the PR branch locally, check it out, add additional commits, then push to your own fork and open the PR (in this example, the kubernetes remote is named `upstream` and my fork is named `origin`):

```
git fetch upstream pull/50654/head:my-branch
git checkout my-branch
... do work, make additional commits ...
git push -u origin
```

**Comment by xiangpengzhao** [comment]
@liggitt awesome, thanks!

**Pull request merged**
