### PR TITLE
fix test/e2e/network

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

e2e_kubeadm: use log functions of core framework

**Which issue(s) this PR fixes**:

Fixes #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
@s-ito-ts 
This is the new PR.

**Comment by s-ito-ts** [comment]
Thanks @hwdef.
It seems that you forgot some changes.
Could you check the following?

https://github.com/kubernetes/kubernetes/blob/d18d97abfd171f5977be31bf9a7468ca8c48ed0e/test/e2e/network/util_iperf.go#L60
https://github.com/kubernetes/kubernetes/blob/d18d97abfd171f5977be31bf9a7468ca8c48ed0e/test/e2e/network/util_iperf.go#L76
https://github.com/kubernetes/kubernetes/blob/d18d97abfd171f5977be31bf9a7468ca8c48ed0e/test/e2e/network/util_iperf.go#L105

**Comment by hwdef** [comment]
@s-ito-ts 
Thanks a lot.
I am sorry about it.I have modified it.

**Comment by liggitt** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Pull request closed without merging**
