### PR TITLE
cluster/gce: Fetch image from image family

### PR DESCRIPTION
**Pull request by bobbypage**
Currently, we hardcode the exact image to use in cluster/gce. This is problematic as the image gets stale very frequently and has old versions of components such as containerd, kernel, and CVE issues.

Instead, fetch the latest image from the image family. This will ensure the image will stay up to date. Each image change in image family is expected to be minor. Switching to a new LTS milestone will require updating the image family set.

Signed-off-by: David Porter <david@porter.me>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
This is ready to review now.

/assign @cheftako

**Review by akhilerm — COMMENTED** [review]
Is this applicable only to cos images or to ubuntu images as well? Because in the e2e_node tests, we use the ubuntu image directly instead of the image family at [multiple locations](https://cs.k8s.io/?q=image%3A&i=nope&files=jobs%2Fe2e_node&excludeFiles=&repos=kubernetes/test-infra)

**Comment by bobbypage** [comment]
> Is this applicable only to cos images or to ubuntu images as well? Because in the e2e_node tests, we use the ubuntu image directly instead of the image family at [multiple locations](https://cs.k8s.io/?q=image%3A&i=nope&files=jobs%2Fe2e_node&excludeFiles=&repos=kubernetes/test-infra)

It should be applicable to both, it is not specific to COS or ubuntu, and image family could be passed in. Note that is only for cluster e2e tests, not node e2e tests (since node e2e have a specific image-config file).

**Review by akhilerm — APPROVED** [review]

**Comment by dims** [comment]
/kind cleanup
/priority important-soon
/triage accepted
/approve
/lgtm

Sorry i hadn't seen this one!

**Comment by adrianreber** [comment]
This breaks usage of `kubectl.sh` for me with:
```
.../kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 60: gcloud: command not found
```

**Pull request merged**
