### PR TITLE
Revert "Revert "Bump cadvisor godep""

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#13248

It seems it didn't cause our tests to fail.

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

cc @jimmidyson

**Comment by jimmidyson** [comment]
Hey now it's not my commit ;) Where's my contribution stats?  JK, honestly don't care personally although I know people that would... Might cherry-picking the original be an option when reverting reverts to retain original authorship?

**Comment by piosz** [comment]
You commit is here https://github.com/jimmidyson/kubernetes/commit/3b9cd131b6f17141cc19537ff31c158082e5e819 ;) It is still in the repo. Then I created this commit https://github.com/kubernetes/kubernetes/commit/31270e5e81baa00ca4970aacb15bdd772605e2d3 which removed all the stuff you added but not touching you commit, and then @wojtek-t created commit in this PR which reverted my commit. If you have any questions feel free to ask.

**Comment by jimmidyson** [comment]
@piosz Honestly I only mean this for discussion, no worries on outcome - happy to get this upgrade in :) Working with OSS I feel it's important to ensure that contributions are attributed properly. Right now this contribution is not attributed to the original contributor (me). Cherry picking the original commit would have done this for revert I think. I think this is something to think about in future for other such scenarios.

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Pull request merged**
