### PR TITLE
Dedent

### PR DESCRIPTION
**Pull request by matchstick**
Adding the dedent package and then applying it to the kubectl help commands. Also updating the documentation to reflect the use of dedent.

### CODE REVIEW

**Comment by matchstick** [comment]
Sorry but sending this up again since it was the third rebase attempt and I had changed my github id. 

The code has not changed at all. So I am just going to lgtm it. If you want to re-review feel free, it's not going to be committed until 1.3 is cut.

matchstick

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by MHBauer** [comment]
Is this related to 25922 or 17609?

**Comment by mikedanese** [comment]
Yes this is equivalent to #25922 and was lgtm'd by @janetkuo . The patch is by the same author. This closes #17609.

@matchstick I have two suggestions for the future:
* If you put "Closes: #17209" in the body of the PR description, the issue will be autoclosed
* You can change the name of your account in the settings :)

**Comment by matchstick** [comment]
Thanks mikedanese. Yes MHBauer you are correct on your comments. 

This commit is waiting for the v1.3 release to be cut then I can rebase and attempt to merge again.

**Comment by matchstick** [comment]
Repushed for rebase.

**Comment by matchstick** [comment]
@k8s-bot unit test this github issue #28121

**Comment by matchstick** [comment]
@k8s-bot unit test this github issue #28121

**Comment by matchstick** [comment]
@ixdy @fejta  Any idea why this PR timed out?

**Pull request merged**
