### PR TITLE
Remove deprecated versionless client interface methods

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes the long-deprecated versionless external client interfaces.

As new versions of API groups are added, the version these accessors targets shifts, which can silently make an application target an unintended version when recompiled with a newer client-go library.

**Does this PR introduce a user-facing change?**:
```release-note
client-go: the deprecated versionless API group accessors (like `clientset.Apps()` have been removed). Use an explicit version instead (like `clientset.AppsV1()`)
```

/sig api-machinery
/cc @sttts @lavalamp

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm

This is deprecated for so long. Let's remove it finally :+1:

**Comment by liggitt** [comment]
rebased to fix `.Core()` reference added in https://github.com/kubernetes/kubernetes/pull/72827/files#diff-02452a489cab3905278eefb9a8e3f4aaR76

**Pull request merged**
