### PR TITLE
Fix golint failures for pkg/kubelet/config/...

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Address the final golint failure by adding a comment explaining our
blank import.

**Which issue(s) this PR fixes**:
xref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

### CODE REVIEW

**Review by hvaara — COMMENTED** [review]
I'm not a reviewer, but this looks good to me

**Comment by mattjmcnaughton** [comment]
cc @derekwaynecarr - same as https://github.com/kubernetes/kubernetes/pull/84929. thanks :)

**Pull request merged**
