### PR TITLE
Update generated for 2017

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: repeat of #19222 for 2017. Some year we'll properly fix this.

**Which issue this PR fixes**: fixes ci-kubernetes-verify-master build

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
All of the generated code needs to be recreated.

**Comment by thockin** [comment]
This is really dumb.  Generated code should not have the copyright changed.  I'll file a gengo bug.  Not sure how to fix it.

**Comment by wojtek-t** [comment]
Will merge on green (as submit queue is blocked)

**Comment by wojtek-t** [comment]
Merging to fix the build.

**Comment by ixdy** [comment]
@wojtek-t thanks!
@smarterclayton I ran `hack/update-all.sh -v -a` but apparently it missed a file.
@thockin I agree that this is bad. I'm hoping that maybe the generated code situation will be a in a better place by 2018...

Frustratingly, the verify-boilerplate script has been copied into a number of other repos (at least contrib and test-infra, and maybe others), so we'll probably need to fix it in all of those, too.

**Comment by spxtr** [comment]
> Frustratingly, the verify-boilerplate script has been copied into a number of other repos (at least contrib and test-infra, and maybe others), so we'll probably need to fix it in all of those, too.

I think that's the goal of kubernetes/repo-infra.

**Comment by krzyzacy** [comment]
Really?! I thought we support ( or we currently have ) multiple years in the boilerplate ( at least in test-infra ).

**Comment by spxtr** [comment]
> Really?! I thought we support ( or we currently have ) multiple years in the boilerplate ( at least in test-infra ).

We do, the problem is that we verify that generated code that we check in matches what you would get if you generate it from scratch, but the checked in code had 2016 in the boilerplate.

**Pull request merged**
