### PR TITLE
Add missing heading in CHANGELOG

### LINKED ISSUE #101298: 'Source Code' heading is missing in CHANGELOG-1.xx.md
- Related issue: https://github.com/kubernetes/sig-release/issues/1528
- Related issue: https://github.com/kubernetes/website/issues/27606

#### What happened:
'Source Code' heading is missing in CHANGELOG-1.xx.md.

In https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md,

[As-is]

```Markdown
## Downloads for v1.21.0

filename | sha512 hash
-------- | -----------
```

#### What you expected to happen:

[To-be]

```Markdown
## Downloads for v1.21.0

### Source Code

filename | sha512 hash
-------- | -----------
```

#### How to see it:
- Visit https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md

#### Environment:

/assign

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Related issue: #101298
- Related issue: https://github.com/kubernetes/sig-release/issues/1528
- Related issue: https://github.com/kubernetes/website/issues/27606

#### What type of PR is this?

/kind documentation
/sig release

#### What this PR does / why we need it:

'Source Code' heading is missing in CHANGELOG-1.xx.md.

#### Which issue(s) this PR fixes:

Fixes #101298

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jihoon-seo** [comment]
How far back should we backport this change?

**Comment by jihoon-seo** [comment]
Since this PR updates just 2 Markdown files,
it is weird that some tests fail.

**Comment by wilsonehusin** [comment]
Are we missing this on other releases too? If so, I'd backport to [active release lines](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#detailed-release-history-for-active-branches).

The failures seem to be from flakes of other tests unrelated to this Markdown.

FYI the block has to be `NONE` for Prow to mark with `release-note-none` 😄 

/release-note-none
/retest

**Comment by jihoon-seo** [comment]
@wilsonehusin Thank you for your comments.

> FYI the block has to be `NONE` for Prow to mark with `release-note-none` 😄

I modified the content of this PR according to your noticing. Thanks!

---

> Are we missing this on other releases too? If so, I'd backport to [active release lines](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#detailed-release-history-for-active-branches).

In `master` branch,
the heading is missing in
- [`CHANGELOG/CHANGELOG-1.21.md`](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#v1210) (covered by this PR)
- [`CHANGELOG/CHANGELOG-1.20.md`](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#v1200) (covered by this PR)
- [`CHANGELOG/CHANGELOG-1.19.md`](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#downloads-for-v1190) (NOT covered by this PR)
- ...


In `release-1.21` branch,
- [`CHANGELOG/CHANGELOG-1.21.md`](https://github.com/kubernetes/kubernetes/blob/release-1.21/CHANGELOG/CHANGELOG-1.21.md#v1210) (NOT covered by this PR)

In `release-1.20` branch,
- [`CHANGELOG/CHANGELOG-1.20.md`](https://github.com/kubernetes/kubernetes/blob/release-1.20/CHANGELOG/CHANGELOG-1.20.md#v1200) (NOT covered by this PR)

and so on...

**Comment by wilsonehusin** [comment]
awesome, thanks for the research. let's cover the `CHANGELOG/CHANGELOG-1.19.md` in this PR and I can approve it to merge.

I find it harder to justify making changes for the ones to `release-1.xx` branches so I'd say we leave those.

also thanks for being responsive for this! in case you don't know, we usually hangout on Slack (`slack.k8s.io`) in `#release-notes` channel. you're welcome to join us if you're interested in this work 😄

**Comment by jihoon-seo** [comment]
@pmmalinov01 Thanks for re-triggering the failed test.

@wilsonehusin I did another commit, squash, and force-push. PTAL! 

Thank you all. :)

**Comment by pmmalinov01** [comment]
No problem, Thank you for helping out and staying on top of this with faster responses and fixes.

**Review by soniasingla — COMMENTED** [review]
Thanks @wilsonehusin & @pmmalinov01 for taking care of this!

/lgtm

**Comment by idealhack** [comment]
thanks!

/lgtm
/approve

**Pull request merged**
