### PR TITLE
DO NOT MERGE - Kubelet-specific port

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@gmarek this is more what I was looking for

**Comment by gmarek** [comment]
It's a half measure as it makes ordinary KubeletClient unusable. I think we should either kill it entirely, by moving everything to the 'master-kubelet' client, or explicitly tell users that they need to inject something that returns kubelet port to it (it can be a constant function for normal setups). I'm all for killing it, but I'm not sure how Node team feels about it.

**Comment by liggitt** [comment]
this isn't what made the KubeletClient unusable :-)

**Comment by liggitt** [comment]
I agree the stack is not set up to handle custom kubelet ports yet, I just didn't want *two* port-returning interfaces plumbed everywhere

**Comment by liggitt** [comment]
and you're right, anything that uses the KubeletClient directly will break with a custom port, but that's true with your existing pull as well, right?

**Comment by gmarek** [comment]
Yes, you're right - I need to do 10 things in the same time.

The story is that I actually removed the port from KubeletClient to avoid this 'two ports' problem, but I needed to put it back again to preserve backward compatibility. I thought that we'll be able to remove Port from KubeletClient quickly enough for it not to become a problem. The result would be a clean solution when KubeletClient returns cluster-wide stuff, and registry handles the rest by itself.  This also makes KubeletClient unusable by itself and changes it into something like helper library.

In your solution we'll end up with this additional call forever, but it's certainly nicer than dirty hack I put around my desired one. I guess it's just a question if we prefer slightly nicer solution eventually with the dirty hack for the time being, or something OK straight away. I guess it's just a matter of taste.

Whatever we decide, probably moving KubeletClient from 'client' to something else will help a bit with naming.

**Comment by liggitt** [comment]
> In your solution we'll end up with this additional call forever, but it's certainly nicer than dirty hack I put around my desired one. I guess it's just a question if we prefer slightly nicer solution eventually with the dirty hack for the time being, or something OK straight away. I guess it's just a matter of taste.

I think this gives us a single place to remove the double call once we deprecate the default node port, without having to replumb everything, right?

**Comment by gmarek** [comment]
OK, you're right - I wasn't aware than someone is depending on ConnectionInfo. If it's indeed the case it's probably better to have the logic returning correct port there. I'll work on moving KubeletClient out of 'client' directory, to some more appropriate place.

**Pull request closed without merging**
