### PR TITLE
Only call Detacher after the final unmount

### PR DESCRIPTION
**Pull request by ghost**
This is to ensure that the detacher gets called only after the final mount call. This check cannot be done in the detacher since it can either be running on the master or on the node.

### CODE REVIEW

**Comment by swagiaal** [comment]
@markturansky @saad-ali PTAL

**Comment by saad-ali** [comment]
LGTM

**Comment by swagiaal** [comment]
@k8s-bot unit test this

**Comment by swagiaal** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by swagiaal** [comment]
@saad-ali could you readd the lgtm label. The bot removed it.. I wonder why

**Comment by justinsb** [comment]
@k8s-bot test this [submit-queue is verifying that this PR is safe to merge]

**Comment by justinsb** [comment]
Automatic merge from submit-queue

**Comment by justinsb** [comment]
I apologize for the above incorrect comments. I was working on the munger locally & it "went rogue" - see #22136. I believe on this issue it incorrectly removed the LGTM label, and it also performed the merge.  However, the PR looks like it should have been merged by the real merger anyway... it had been queued for merge, and passed all the tests.  I will readd the LGTM label.  If there is anything else I should do to clean this up, please let me know.

**Pull request merged**
