### PR TITLE
Merge release 0.19.1 to master

### PR DESCRIPTION
**Pull request by brendandburns**
@eparis @zmerlynn @roberthbailey

### CODE REVIEW

**Comment by brendandburns** [comment]
Changes to mark-new-version are changes I had to make to not clone docs on point releases.  I can send that as a separate PR and rebase this if it's preferable to not have that in the diff.

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
something seems wrong....   the v0.19.1 tag is eb87c0b37261639eb04b1f9d6e70467090bb6e8c but should be bb63f031d4146c17113b059886aea66b09f6daf5   right?

**Comment by eparis** [comment]
nevermind, friggin git sucks at updating tags locally.....

**Comment by eparis** [comment]
LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
