### PR TITLE
Disable gzip compression in core control plane components

### PR DESCRIPTION
**Pull request by smarterclayton**
On local networks (such as the typical connection path between control
plane components) gzip compression increases CPU use and end to end p99
latency rather than decreasing it. Disable compression within the control
plane components like a 1.15 cluster would be configured.

Golang automatically enables transport level gzip, but local network 
clients may wish to disable it for better CPU usage and lower latency
(scheduler, controller-manager). Allow DisableCompression on rest.Config to
modify the underlying transport. This impacts the transport cache, but it
is expected that most clients connecting to the same servers within a
process will have the same compression config.

/kind bug

```release-note
Kubernetes client users may disable automatic compression when invoking Kubernetes APIs by setting the `DisableCompression` field on their rest.Config.  This is recommended when clients communicate primarily over high bandwidth / low latency networks where response compression does not improve end to end latency.
```
```docs
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/assign @wojtek-t 
@kubernetes/sig-scalability-pr-reviews @liggitt as discussed

**Comment by wojtek-t** [comment]
@smarterclayton - unit test failures seem legitimate; once fixed lgtm

**Comment by smarterclayton** [comment]
@liggitt any concern about naming of the flag?

**Comment by wojtek-t** [comment]
/lgtm

/hold
To let Jordan comment.

**Comment by smarterclayton** [comment]
Jordan and I briefly talked about naming, this is consistent with the golang field and if we need to we can rename pre 1.16 launch.  I want to determine whether this mitigates the bulk of the latency we see in the graphs.

/hold cancel

**Comment by liggitt** [comment]
lgtm

**Pull request merged**
