### PR TITLE
Bump CNI and etcd go base images to 1.7.6

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Addresses #46391 for CNI and etcd images.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @luxas

### CODE REVIEW

**Comment by cblecker** [comment]
Questions:
- According to https://github.com/kubernetes/kubernetes/issues/46391#issuecomment-304525312, we shouldn't be releasing CNI with these scripts anymore. If that's the case, is it preferable to just remove the script completely? If we aren't quite there yet, I figure it's good to update the base image.
- For the etcd image, should we add a release number to the tag and actually release a new etcd image? Or just leave it like this for the next time we actually bump and release an etcd image. 3.0.17 is still the latest patch revision for etcd 3.0.

**Comment by luxas** [comment]
@cblecker I plan to remove the CNI Makefile shortly, but I'm ok with bumping it now for the sake of consistency. The etcd bump makes a lot of sense if/when 3.0.18 comes out and we want to upgrade.

/lgtm

**Review by luxas — APPROVED** [review]

**Comment by cblecker** [comment]
Thanks @luxas!

**Comment by cblecker** [comment]
cross build still broken: https://github.com/kubernetes/kubernetes/issues/46520

**Pull request merged**
