### PR TITLE
Automated cherry pick of #105388: Copy VolumeSnapshotContent annotations in snapshottable.go

### PR DESCRIPTION
**Pull request by mauriciopoppe**
Cherry pick of #105388 on release-1.22.

#105388: Copy VolumeSnapshotContent annotations in snapshottable.go

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
hey @kubernetes/release-managers, could you please take a look at this cherrypick? Thanks in advance

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/hold cancel
/test pull-kubernetes-integration
pull-kubernetes-integration fixed via https://github.com/kubernetes/test-infra/pull/23936

**Pull request merged**
