### PR TITLE
bump agnhost base image

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup
/kind bug

**What this PR does / why we need it**:

It bumps the alpine version used by the agnhost image from 3.6 to 3.12, because the iperf version provided in that image is not working for IPv6 AT ALL ~multicast~, it has a known bug fixed with the version provided by the new alpine version.

```release-note
NONE
```

### CODE REVIEW

**Comment by claudiubelu** [comment]
You'll have to update ``build/dependencies.yaml`` too.

Other than that, LGTM. iperf is updated in the new image:

```
docker run --rm --entrypoint iperf claudiubelu/agnhost:2.26 -v
iperf version 2.0.13 (21 Jan 2019) pthreads

docker run --rm --entrypoint iperf claudiubelu/agnhost:2.25 -v
iperf version 2.0.9 (1 June 2016) pthreads
```

**Comment by mattfenwick** [comment]
👍 this is awesome , thanks @aojea !  We're seeing some problems with the iperf tests, hope this will clear them up!

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
