### PR TITLE
Automated cherry pick of #102176: Fix VolumeAttachment garbage collection for migrated PVs

### PR DESCRIPTION
**Pull request by timebertt**
Cherry pick of #102176 on release-1.21.

#102176: Fix VolumeAttachment garbage collection for migrated PVs

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by timebertt** [comment]
Checks are all green now.
/assign @gnufied 
for approval :)

**Comment by liggitt** [comment]
Is this fixing a regression or backporting a fix for a pre-existing bug? What are the risks of this change introducing a new regression to existing clusters?

**Comment by timebertt** [comment]
> Is this fixing a regression or backporting a fix for a pre-existing bug? What are the risks of this change introducing a new regression to existing clusters?

For anyone reading up on this: ref https://github.com/kubernetes/kubernetes/pull/102458#issuecomment-855299088

**Comment by puerco** [comment]
/lgtm
Thanks @timebertt

**Pull request merged**
