### PR TITLE
Delete hooks/pre-commit

### PR DESCRIPTION
**Pull request by alexandercampbell**
Fixes https://github.com/kubernetes/community/issues/729.

@pwittrock @xiangpengzhao 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
I'm not even sure we still should have this. This basically runs a small subset of `make verify`. Perhaps we should just remove this entirely and update docs to suggest using `make verify` locally prior to push.

**Comment by fejta** [comment]
+1 to deleting this file entirely

**Comment by xiangpengzhao** [comment]
Does `make verify` do the same things, or more, or less? I remembered that it runs longer time than `pre-commit`. It also doesn't make the binaries, right? I don't know if this is just what I want...I'm on the fence. If most folks think `pre-commit` as useless, I will agree to remove it.

**Comment by cblecker** [comment]
`make verify` does more, but it's also what the `pull-kubernetes-verify` job does. If you can't pass `make verify`, then your PR isn't going to pass CI either. If you're only running it once per PR before you push, then the pre-commit becomes useless.

**Comment by xiangpengzhao** [comment]
Agreed.

**Comment by xiangpengzhao** [comment]
>Run and pass make verify (can take 30-40 minutes)

https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#run-local-verifications

30-40 minutes...I don't think developers want to run this locally.

**Comment by xiangpengzhao** [comment]
Leaving all the verification work to CI might be most guys' final choice:)

**Comment by spiffxp** [comment]
@kubernetes/sig-contributor-experience-proposals @kubernetes/sig-testing-proposals I've never been a fan of the pre-commit stuff, and would be happy to see it go, but I'm under the impression some folks find it useful. WDYT?

**Comment by spiffxp** [comment]
/remove-kind design
... not a design thing, I guess proposal was the wrong team to hit, how do these even work

**Comment by cblecker** [comment]
@kubernetes/sig-contributor-experience-misc as it's the group that most people who care about contribex are in :)

**Comment by alexandercampbell** [comment]
Updated this PR to delete the pre-commit hook since all 6 people who have interacted with this PR seem to be in favor of deletion. PTAL

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
This LGTM.

**Pull request merged**
