### PR TITLE
Automated cherry pick of #77165: Increase maxMsgSize for dockershim

### PR DESCRIPTION
**Pull request by bhks**
Cherry pick of #77165 on release-1.14.

#77165: Increase maxMsgSize for dockershim

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Purpose of the original commit was that `maxMsgSize` in `dockershim` should equal `maxMsgSize` in `pkg/kubelet/remote/utils.go`. In 1.14, the `maxMsgSize` in `pkg/kubelet/remote/utils.go` is also 16MB, so we do need to update.

**Comment by tpepper** [comment]
/kind bug
from parent PR.

**Comment by bhagwat070919** [comment]
Thanks Everyone for help !!!!!!

**Pull request merged**
