### PR TITLE
node-e2e: Add container lifecycle e2e tests for preStop hook

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR adds e2e tests to ensure that the container's pre-stop hook is invoked if the startup or liveness probe fails.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig node
/sig testing

/cc @SergeyKanzhelev

### CODE REVIEW

**Comment by gjkim42** [comment]
/assign @SergeyKanzhelev 
This is a pre-factoring PR for the https://github.com/kubernetes/kubernetes/pull/119168 adding the container lifecycle e2e tests for prestop hook.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
