### PR TITLE
Automated cherry pick of #55119

### PR DESCRIPTION
**Pull request by pires**
Cherry pick of #55119 on release-1.7.

#55119: fix scheduler predicates test that may violate DNS label

### CODE REVIEW

**Comment by pires** [comment]
cc @kubernetes/sig-scheduling-pr-reviews

**Comment by pires** [comment]
cc @aveshagarwal @bsalamat @timothysc

**Comment by pires** [comment]
thank you @bsalamat. can you remove the `do-not-merge/cherry-pick-not-approved` label, please?

**Comment by bsalamat** [comment]
hmm... looks like this was not the command to remove do-not-merge/cherry-pick-not-approved.

**Pull request merged**
