### PR TITLE
Cleanup deprecated scheduler functions/files

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Cleans up ```ApplyFeatureGates` function which is currently a no-op, also removes the default package from algorithmprovider which is currently empty and serve no purpose.

**Which issue(s) this PR fixes**:
Part of #85822

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/cc @Huang-Wei

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Thanks @ahg-g for the series of refactoring PRs to make the code testable, stateless, and hence maintainable!

/lgtm

**Comment by Huang-Wei** [comment]
> ERROR(all) test/integration/daemonset/daemonset_test.go:49:2: "k8s.io/kubernetes/pkg/scheduler/algorithmprovider" imported but not used

Unused import needs to be cleaned out, and bazel update script might need to be rerun.

**Comment by ahg-g** [comment]
@Huang-Wei can you lgtm again pls

**Review by draveness — COMMENTED** [review]
/retest
/lgtm

**Pull request merged**
