### PR TITLE
Fix the wrong judgment of oom_score_adj

### PR DESCRIPTION
**Pull request by tanjing2020**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
oom_score_adj should be between [expectedMinOOMScoreAdj, expectedMaxOOMScoreAdj)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by spiffxp** [comment]
/milestone v1.21
This seems feasible to land today but I will defer to sig-node for priority and triage

**Comment by oomichi** [comment]
The check code has been added since 2016 long time back (a1fe3adbc7cf8ddd4724f7b2d21d90a6733f2e57)

/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm
/retest
/triage accepted

/cc @SergeyKanzhelev

**Pull request merged**
