### PR TITLE
diff: Make filename cross-platform compatible

### PR DESCRIPTION
**Pull request by apelisse**
```
`:` is not a valid character in Windows.
```

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mengqiy** [comment]
/lgtm
You may want to write a note in the PR description
```
`:` is not a valid character in Windows.
```

**Comment by liggitt** [comment]
> You may want to write a note in the PR description

no release note needed, this is fixing an issue that just merged and hasn't been released yet

**Pull request merged**
