### PR TITLE
Fixes a cross-build failure introduced in PR 51209. FYI, issue 51863.

### LINKED ISSUE #51863: cross-build: PR 51209 causing cross build failure
```
I0902 19:04:23.790] # k8s.io/kubernetes/pkg/kubelet/cm
I0902 19:04:23.790] pkg/kubelet/cm/container_manager_unsupported.go:75: undefined: kubecontainer in kubecontainer.RunContainerOptions
I0902 19:04:23.790] pkg/kubelet/cm/container_manager_unsupported.go:76: undefined: kubecontainer in kubecontainer.RunContainerOptions
```
https://github.com/kubernetes/kubernetes/pull/51209
https://k8s-testgrid.appspot.com/misc#cross-build
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/3141

---
cc: @kubernetes/sig-node-bugs @kubernetes/sig-node-test-failures @dchen1107 @jiayingz @vishh
/kind bug
/priority failing-test

### PR DESCRIPTION
**Pull request by jiayingz**
fixes #51863

### CODE REVIEW

**Comment by cblecker** [comment]
This lgtm and does fix the cross build. Will let @vishh, @dchen1107, and @derekwaynecarr handle the review/approve though.
/unassign
/assign @derekwaynecarr

**Comment by feiskyer** [comment]
LGTM

**Comment by dims** [comment]
LGTM

**Comment by dims** [comment]
@k8s-oncall Can we please merge this to fix the cross build?

**Comment by feiskyer** [comment]
Is pull-kubernetes-e2e-kops-aws always fail now? seems no success build in recent runs.

**Comment by cblecker** [comment]
@feiskyer Yeah, it's broken right now, but it's been made non-blocking (SQ will merge even if PRs fail it) until the test can be properly fixed next week.

**Pull request merged**
