### PR TITLE
metadata concealment: remove the legacy endpoints from the check

### LINKED ISSUE #94791: Metadata Concealment test exercises endpoints due to be removed 2020-09-30
https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server

>Warning: The v0.1 and v1beta1 metadata server endpoints are deprecated and scheduled for shutdown on September 30, 2020.

This test (which runs in most e2e jobs that run on GCE): https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/metadata_concealment.go#L34

Schedules a container that runs this: https://github.com/kubernetes/kubernetes/blob/master/test/images/metadata-concealment/check_metadata_concealment.go

Resulting in a number of legacy metadata endpoints getting hit.

To see if this test is going to start failing across all release branches on Sep 30th, we could try disabling the endpoints ahead of time via: https://cloud.google.com/compute/docs/storing-retrieving-metadata#disable-legacy-endpoints. In fact https://github.com/kubernetes/kubernetes/pull/69593 and https://github.com/kubernetes/kubernetes/pull/70253 added support for expecting different results based on whether `disable-legacy-endpoints` is set.  

My concern is the test expects 200 for some root endpoints, and 403 for disabled endpoints. However the e-mail I received as a GCP customer tells me any legacy endpoints may return 404.

I'm inclined to suggest we remove the legacy endpoints from the check, bump the image version, and cherry-pick use of the new image version back to all release-branches.

WDYT @dekkagaijin @ixdy @idealhack @mikedanese since you were involved with the earlier PRs
@kubernetes/sig-auth-misc 
/sig auth
/sig cloud-provider
/provider gcp
/sig testing
/priority important-soon
(I'm tempted to critical-urgent this but it's not drop-everything yet)
/milestone v1.20

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind cleanup
/sig auth
/sig cloud-provider
/provider gcp
/sig testing

**What this PR does / why we need it**:
> I'm inclined to suggest we remove the legacy endpoints from the check, bump the image version, and cherry-pick use of the new image version back to all release-branches.
From @spiffxp description in https://github.com/kubernetes/kubernetes/issues/94791.

>v1beta1 server and v0.1 metadata server endpoints were deprecated on September 30, 2020 and are in the process of being shutdown. Ensure that you update all requests to use v1. For more information, see Transitioning to the v1 metadata server endpoint.

**Which issue(s) this PR fixes**:
Fixes #94791

**Special notes for your reviewer**:
references:
- https://cloud.google.com/compute/docs/storing-retrieving-metadata#disable-legacy-endpoints
- https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
WDYT @dekkagaijin @ixdy @idealhack since you were involved with the earlier PRs
@kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
this is just changing the code in the test image. when/how does the test image get rebuilt and the version used in kube e2e's bumped to actually be effective?

**Review by spiffxp — CHANGES_REQUESTED** [review]
Needs to change VERSION file

**Comment by spiffxp** [comment]
/hold
for requested changes

**Comment by spiffxp** [comment]
@liggitt 
Next steps would be:
- https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-metadata-concealment-test-images will run on postsubmit
- If it passes, next step would be to promote via a k8s.io PR, e.g. https://github.com/kubernetes/k8s.io/pull/1558
- kubernetes/kubernetes PR to update image version used by e2e tests, e.g. https://github.com/kubernetes/kubernetes/pull/98101

**Comment by spiffxp** [comment]
We are in the midst of migrating away from gcr.io/kubernetes-e2e-test-images toward k8s.gcr.io/e2e-test-images (ref: https://github.com/kubernetes/kubernetes/issues/96770)

**Comment by pacoxu** [comment]
Thanks, @spiffxp for reviewing.
Version is changed, PTAL  again.

**Comment by pacoxu** [comment]
> /hold
> for requested changes

can I /hold cancel now？

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
