### PR TITLE
add readiness gates in kubectl extended output for pods

### PR DESCRIPTION
**Pull request by freehan**
ref: https://github.com/kubernetes/community/blob/master/keps/sig-network/0007-pod-ready%2B%2B.md

- add readiness gates column in the output of pods for wide option
- add readiness gates in pod description

```release-note
add readiness gates in extended output for pods
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by freehan** [comment]
/assign lavalamp for approval 
FYI, this PR unfortunately changed one of the unit tests under `pkg/registry`

**Comment by lavalamp** [comment]
Mechanically this is fine.

Did we do some sort of UI review that shows that this merits living as a top level column?

**Comment by seans3** [comment]
> Mechanically this is fine.
> 
> Did we do some sort of UI review that shows that this merits living as a top level column?

Yes. This has been on discussed and agreed upon weeks/months ago within SIG CLI.

**Pull request merged**
