### PR TITLE
Remove deprecated kubectl command aliases

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
These command aliases have been deprecated for more than two years. It's time to remove them.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: #8319 #6118 #8596

**Special notes for your reviewer**:
/sig cli

**Release note**:

```release-note
Remove deprecated kubectl command aliases `apiversions, clusterinfo, resize, rollingupdate, run-container, update`
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
@xiangpengzhao Thanks. Please enumerate the removed commands in the release note.

**Comment by bgrant0607** [comment]
BTW, the policy is here: https://kubernetes.io/docs/reference/deprecation-policy/

Most of these have been deprecated since 1.0.

**Comment by fabianofranz** [comment]
Thanks @xiangpengzhao !

Unit test failure seems legit:

```
/go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh: line 38: run_kubectl_using_deprecated_commands_test: command not found
```

**Comment by xiangpengzhao** [comment]
Thanks @bgrant0607 @fabianofranz !

Release note updated and test failure fixed (Tests are still rerunning. Hope they can pass). PTAL.

**Comment by xiangpengzhao** [comment]
All tests passed.

**Comment by fabianofranz** [comment]
Strange how it's asking for an approver from `pkg/OWNERS` instead of `pkg/kubectl/OWNERS`.

Anyways, needs an approval for docs, @pwittrock?

**Comment by fabianofranz** [comment]
> Strange how it's asking for an approver from pkg/OWNERS instead of pkg/kubectl/OWNERS.

@spiffxp any clue?

**Comment by xiangpengzhao** [comment]
/assign @brendandburns
for docs and pkg root approval. Thanks!

**Comment by xiangpengzhao** [comment]
@brendandburns all checks passed. thanks!

**Comment by bgrant0607** [comment]
@xiangpengzhao In the future, the convention is to put the manual changes and changes to generated files in separate commits.

/approve

**Comment by xiangpengzhao** [comment]
@bgrant0607 thanks for reminder! I thought the PR was trivial so I didn't separate it into commits. Will follow the convention in the future PRs :)

**Comment by xiangpengzhao** [comment]
@bgrant0607 @fabianofranz
btw, does this PR need a `release-note-action-required` label ?

**Comment by bgrant0607** [comment]
@xiangpengzhao Good idea.

**Comment by xiangpengzhao** [comment]
Thanks Brian !

**Pull request merged**
