### PR TITLE
cleanup: remove redundant return

### PR DESCRIPTION
**Pull request by HecarimV**
/kind cleanup
```release-note
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @Jefftree 
Would you mind looking at this one? Thank you
/triage accepted

**Comment by Jefftree** [comment]
Thanks for the PR. It looks like these were probably copied over from an autogenerated file (eg: https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/apis/autoscaling/zz_generated.deepcopy.go#L33)

I'm inclined to either keep the style as is or modify the generation script at the root to avoid adding the return for void functions.

**Comment by HecarimV** [comment]
> I'm inclined to either keep the style as is or modify the generation script at the root to avoid adding the return for void functions.

Thanks for your suggestions, it may be better to keep the style as-is.

**Pull request closed without merging**
