### PR TITLE
Automated cherry pick of #67430: cpumanager: rollback state if updateContainerCPUSet failed #66718: cpumanager: validate topology in static policy.

### PR DESCRIPTION
**Pull request by wanghaibo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Cherry pick of #67430 #66718 on release-1.10.
```

#67430: cpumanager: rollback state if updateContainerCPUSet failed
#66718: cpumanager: validate topology in static policy.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@wanghaibo Based on merge dates of parent PRs they don't seem to be included in 1.11. If that's the case we should also cherry-pick them to 1.11 to avoid regression between 1.10 and 1.11.

**Comment by wanghaibo** [comment]
@MaciekPytel  thanks,I will cherry-pick them to 1.11

**Comment by MaciekPytel** [comment]
@wanghaibo Please get an approval and lgtm from an OWNER in the appropriate directories (same as on normal PR) and I'll merge it.

**Comment by MaciekPytel** [comment]
With 1.13 released 1.10 has reached end of life. 1.10.12 was the last patch release and we're no longer accepting cherry-picks to 1.10 branch.

**Comment by wanghaibo** [comment]
@MaciekPytel thank you for your help

**Pull request closed without merging**
