### PR TITLE
[WIP] Fix v1.NamespaceAll issues with fake ClientSet

### LINKED ISSUE #493: Creating Events fails with fake ClientSet
**Problem description**

Creating Events via a record.EventRecorder does not work in combination with a fake ClientSet.
The generated error message is:

`'Server rejected event '&v1.Event{...}': request namespace does not match object namespace, request: "" object: "test"' (will not retry!)`

**How to reproduce**

```go
package main

import (
	"flag"
	"time"

	"github.com/golang/glog"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/kubernetes/scheme"
	clientcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
	"k8s.io/client-go/tools/record"
)

func main() {
	flag.Parse()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: "test",
			Name:      "dummy",
			SelfLink:  "/api/v1/namespaces/test/pods/dummy",
		},
	}

	cli := fake.NewSimpleClientset(pod)

	eventSink := &clientcorev1.EventSinkImpl{
		cli.CoreV1().Events(corev1.NamespaceAll),
	}

	eventBroadcaster := record.NewBroadcaster()
	eventBroadcaster.StartLogging(glog.V(3).Infof)
	eventBroadcaster.StartRecordingToSink(eventSink)

	r := eventBroadcaster.NewRecorder(scheme.Scheme, corev1.EventSource{Component: "test"})

	r.Event(pod, corev1.EventTypeNormal, "SomeReason", "Dummy event")

	time.Sleep(time.Second)
}
```

**Investigation**

At [fake/fake_event_expansion.go#L27](https://github.com/kubernetes/client-go/blob/release-9.0/kubernetes/typed/core/v1/fake/fake_event_expansion.go#L27), [`core.NewRootCreateAction()`](https://github.com/kubernetes/client-go/blob/release-9.0/testing/actions.go#L94) returns an `action` without Namespace:

```
x/vendor/k8s.io/client-go/testing.CreateActionImpl {
        ActionImpl: x/vendor/k8s.io/client-go/testing.ActionImpl {
                Namespace: "",
                Verb: "create",
                Resource: (*x/vendor/k8s.io/apimachinery/pkg/runtime/schema.GroupVersionResource)(0xc0000f5a58),
                Subresource: "",},
        Name: "",
        Object: x/vendor/k8s.io/apimachinery/pkg/runtime.Object(*x/vendor/k8s.io/api/core/v1.Event) *{
                ...
                Reason: "SuccessfulCreate",
                Message: "Dummy event",
                ...},}
```

Later, inside [c.Fake.Invokes()](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fake.go#L130), the action is [handled](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fixture.go#L91), but because `ns != obj.Namespace` an [error is returned](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fixture.go#L353-L356).

### PR DESCRIPTION
**Pull request by joshuarubin**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes kubernetes/client-go#493

**Special notes for your reviewer**:

So far this PR only includes a test that reproduces the issue.

The problem is that the FakeEvents interface is being created with `ns: ""` due to using `Events(v1.NamespaceAll)` which is the same as `Events("")`.

`FakeEvents.CreateWithEventNamespace` already properly handles namespaces as follows:

```go
func (c *FakeEvents) CreateWithEventNamespace(event *v1.Event) (*v1.Event, error) {
	action := core.NewRootCreateAction(eventsResource, event)
	if c.ns != "" {
		action = core.NewCreateAction(eventsResource, c.ns, event)
	}
	...
```

The question is if the `if` statement should be modified to treat `FakeEvents.ns == ""` with the understanding that it implies "all namespaces" instead of "no namespaces", something like:
```go
	if c.ns != "" {
		action = core.NewCreateAction(eventsResource, c.ns, event)
	} else {
		action = core.NewCreateAction(eventsResource, event.Namespace, event)
	}
```

Making this change in `kubernetes/typed/core/v1/fake/fake_event_expansion.go` does cause this test to pass. However, I've not made that change yet because it seems like `FakeCoreV1` would have to be updated in quite a few places, not just `FakeEvents.CreateWithEventNamespace`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Current implementation of `func (c *FakeEvents) CreateWithEventNamespace` is wrong. It should mimic the real client.

What are the other places that need update?

**Comment by jpeeler** [comment]
@joshuarubin can you update your PR to update all the fake methods and see what @caesarxuchao thinks?

**Pull request closed without merging**
