### PR TITLE
[e2e_node] Update tests in container_lifecycle to conform to best practices

### PR DESCRIPTION
**Pull request by dshebib**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update the tests in `containers_lifecycle_test` to use agnhost and properly set Context among other changes to cleanup and improve tests.

#### Special notes for your reviewer:
So far the only changes are replacing busyboxy image with agnhost and sharing context between tests. May be worth additional changes to reduce flakes and make sure tests are properly labelled as serial/slow etc.

#### Does this PR introduce a user-facing change?
only changes e2e tests
```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
So one suggestion may be tackle these changes one at a time.

PR 1) Replace busybox with agnhost
PR 2) Formatting
PR 3) replace context

Reviewing this it is a bit difficult seeing what all the changes are. And if there is any issues, we would have to revert the entire PR.

**Comment by SergeyKanzhelev** [comment]
/close

please open separate PRs. Reviewing change like this is close to impossible. At a minimum, it should be split into commits, but it is easier for everybody to just do separate PRs.

**Pull request closed without merging**
