### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lokichoggio**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it:**
Fix typo under cmd/kube-controller-manager and pkg/apis/autoscaling

**Which issue(s) this PR fixes:**
Fixes #

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?**
```
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**

### CODE REVIEW

**Comment by yxxhero** [comment]
@lokichoggio Please write your description for this. example: https://github.com/kubernetes/kubernetes/pull/108976

**Comment by yxxhero** [comment]
@lokichoggio Please rebase your code. The commits contains merge commit.

**Comment by lokichoggio** [comment]
add release note

**Pull request closed without merging**
