### PR TITLE
cherry pick #124618 to 1.28

### PR DESCRIPTION
**Pull request by gabesaba**
Changes to make tests compatible with 1.28
 - omit rename of "want" to "schedule" to reduce diff
 - call Scheduler.Run(), as ScheduleOne is not public interface
 - only verify pods scheduled; don't call ScheduleOne
 - Replace PodsInActiveQ check with PodSchedulingGated
 - update wait.Poll to wait.PollUntilContextTimeout - **new [1]**
 - update scheduling_queue_test hint function return type - **new [1]**
 - don't update plugin_tests.go, as relevant test no longer exists- **new [1]**

[1] Change is new in this PR. Changes above were originally introduced in previous PRs. See  #124848, #124849
 
#### What type of PR is this?
/kind bug

/sig scheduling
/assign @alculquicondor 

#### What this PR does / why we need it:
Cherry pick performance fix #124618
#### Which issue(s) this PR fixes:
#124384
#### Does this PR introduce a user-facing change?

```release-note
Improved scheduling latency when many gated pods
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Any changes from 1.29?

**Comment by gabesaba** [comment]
> Any changes from 1.29?

Yes. I updated the description to specify which changes are new to this PR, rather than previous cherry-picks (e.g. 1.29)

**Comment by gabesaba** [comment]
/cc kubernetes/release-managers

parent issue: #124384
parent pr: #124618

cherry picks:
  - #124848
  - #124849
  - #124851
  - #124866

**Review by Verolop — COMMENTED** [review]
/lgtm
(on behalf of release managers)

**Pull request merged**
