### PR TITLE
"fix issue(#49965)kubectl scale also says that it can work based on a label selector or all"

### LINKED ISSUE #49965: kubectl scale also says that it can work based on a label selector
Similar to https://github.com/kubernetes/kubernetes/issues/44800 

@kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
Fixes #49965 #44800

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
don't ```pull-kubernetes-e2e-kops-aws test``` why fail. just rebase master ~.~

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Comment by liggitt** [comment]
Looks fine to me, would like a test of both options (set up three items, make sure label selector only scales selected items, and all scales all)

**Comment by zjj2wry** [comment]
@liggitt i add some bash test for this :) thanks

**Comment by zjj2wry** [comment]
@liggitt ptal

**Comment by zjj2wry** [comment]
@pwittrock ptal

**Comment by zjj2wry** [comment]
kindly ping @pwittrock

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews this PR can added into 1.8 milestone? i have add bash test for this.

**Comment by mengqiy** [comment]
> this PR can added into 1.8 milestone? i have add bash test for this.

This PR miss code freeze. Cannot be added in 1.8 milestone.

**Comment by zjj2wry** [comment]
kindly ping@mengqiy @fabianofranz @pwittrock mind approve this?:-) thanks

**Comment by pwittrock** [comment]
@zjj2wry sorry have been distracted.  Will TAL

**Comment by zjj2wry** [comment]
@pwittrock not at all, i know you have mary thing about release.

**Pull request merged**
