### PR TITLE
replace test error checking with more readable way

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup
/sig testing

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Part of #77706

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
Thanks for doing this,

/lgtm

**Comment by danielqsj** [comment]
@oomichi could you help approve it ? :)

**Pull request merged**
