### PR TITLE
improve pleg error msg when it has never been successful

### LINKED ISSUE #69007: misleading PLEG error on kubelet start "last seen active 2562047h47m..."
When the kubelet first starts the folllowing error is emitted to the logs
```
skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
```
This is because the relist has not yet run which results in a duration that is just the time since the zero time instant (https://golang.org/pkg/time/#Time.IsZero)

xref https://bugzilla.redhat.com/show_bug.cgi?id=1632430

/sig node

### PR DESCRIPTION
**Pull request by sjenning**
fixes #69007

xref https://bugzilla.redhat.com/show_bug.cgi?id=1632430

@derekwaynecarr @dashpole

### CODE REVIEW

**Comment by dashpole** [comment]
/kind bug
/lgtm
after the unit test is fixed

**Comment by derekwaynecarr** [comment]
poke when updated test and would approve

**Comment by derekwaynecarr** [comment]
looks good, and tests now pass!

/approve

**Pull request merged**
