### PR TITLE
Switch to released versions of kustomize deps and new mergo package

### PR DESCRIPTION
**Pull request by dims**
related to https://github.com/kubernetes/kubernetes/issues/124279 ( Module github.com/imdario/mergo has been renamed as dario.cat/mergo )

Also see #107499

in order to get rid of the older import, we need to switch to the newer import in our usage as well as update to newest kustomize

nice side-effect we now can use released tags of kustomize!!

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
tracked down the `pull-kubernetes-unit` failure to:
https://github.com/darccio/mergo/commit/eb768768e3f1a0f18771f01c482f327fcc211092

**Comment by dims** [comment]
@liggitt followed the pattern you advised in https://github.com/kubernetes/kubernetes/issues/107499#issuecomment-1938831712

**Comment by dims** [comment]
/hold

Looks like we need to wait for https://github.com/kubernetes-sigs/kustomize/pull/5680

per conversation here:
https://github.com/kubernetes/kubernetes/pull/124217#discussion_r1582589910

cc @koba1t @varshaprasad96

**Comment by liggitt** [comment]
I realized we have 3 parallel PRs attempting to update kustomize... (https://github.com/kubernetes/kubernetes/pull/124812 https://github.com/kubernetes/kubernetes/pull/124217 https://github.com/kubernetes/kubernetes/pull/123339)

https://github.com/kubernetes/kubernetes/pull/123339 is the oldest and also took care of switching k/k to the v4 json-patch library to avoid using two names for the same library

I don't *think* the mergo update is strictly required to update kustomize, so maybe we could split that out to a standalone PR?

**Pull request closed without merging**
