### PR TITLE
hack: fixed issues from previous refactor PR

### PR DESCRIPTION
**Pull request by falcon78921**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:
This PR fixes mistakes I made in previous PR:
https://github.com/kubernetes/kubernetes/pull/75928

Fixes `pathlib` definitions & `print()` statements, thanks to another
GitHub member.

If there's anything else I need to fix, please let me know :)

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
/sig testing

Found another place the original PR sorta broke things, `urllib.request` doesn't exist in python 2

If you're moving this to python3 (which is great! since EOL for python 2 is coming up), I would go ahead and change the top line to `/usr/bin/env python3`.  I'm not super clear if there are other changes that need to happen to support that, but let's find out

**Comment by falcon78921** [comment]
@spiffxp yep, moving to Python3 was the plan :) Sorry about the mistakes. I'll change the line to `python3`.

**Comment by falcon78921** [comment]
@spiffxp I added `python3` to the shebang :)

**Comment by spiffxp** [comment]
... right, so TIL our boilerplate check has the `python` shebang hardcoded
```
Boilerplate header is wrong for: /home/prow/go/src/k8s.io/kubernetes/hack/update_owners.py
```

you can run this yourself locally within the kubernetes/kuberentes dir
```
./hack/verify-boilerplate.sh
```

I would suggest removing the shebang from https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py.txt

And updating https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py to treat `.py` files the same way it treats `.sh` files (since it doesn't seem to complain about their shebangs)

**Comment by falcon78921** [comment]
@spiffxp Thanks for the pointers! :) I opened #79448 in regards to the Prow error.

**Comment by spiffxp** [comment]
/priority important-longterm
/approve
/lgtm
This is going to need a /retest once #79448 lands, which I think fetja-bot periodically does for PR's that are otherwise mergeable

**Pull request merged**
