### PR TITLE
kubectl/pkg/cmd/create/create_deployment.go: Remove unessary logic

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
If not `generatorNameTemp != generatorName` means `generatorNameTemp == generatorNam`:).

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/91088

**Special notes for your reviewer**:
/cc @liggitt 
/cc @neolit123

### CODE REVIEW

**Comment by neolit123** [comment]
@zhouya0 
/lgtm

the change seems fine, but please let the bots pick reviewers. instead of `/cc` explicitly. thanks.

**Comment by zhouya0** [comment]
/close 
For https://github.com/kubernetes/kubernetes/pull/91113

**Pull request closed without merging**
