### PR TITLE
Fix: test case wrong output in cmd/kubeadm/app/cmd/completion_test.go

### PR DESCRIPTION
**Pull request by wppzxc**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
test case wrong output
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pacoxu — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/approve
/ok-to-test

this can merge after code freeze
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.24#summary

**Pull request merged**
