### PR TITLE
Remove TODO comment of package pkg/apis

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

Remove TODO comment of package pkg/apis

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
NONE
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
/assign @thockin
PTAL

**Comment by wgliang** [comment]
ack @thockin

**Comment by wgliang** [comment]
@erictune @lavalamp @smarterclayton

PTAL

**Comment by lavalamp** [comment]
Please don't remove TODOs without either addressing them or explaining why they're no longer relevant.

Also, don't remove comments near the TODO which continue to be useful.

**Pull request closed without merging**
