### PR TITLE
Update kube-dns to 1.14.4

### PR DESCRIPTION
**Pull request by bowei**
- Fixes broken arm dnsmasq image
- Fixes kube-dns log spam issue

kubernetes/dns#111

```release-note
none
```

### CODE REVIEW

**Comment by bowei** [comment]
@dchen1107 cherrypick to 1.7

**Comment by dchen1107** [comment]
/lgtm

I approved your pr for 1.7, please create a cherrypick pr. Thanks!

**Comment by dchen1107** [comment]
Ok, this is already cherrypick pr. The original one was merged a while back.

**Pull request merged**
