### PR TITLE
When choosing a host interface proxier must only consider the ones with an address assigned

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton @thockin

**Comment by smarterclayton** [comment]
LGTM, matches other code we have in master to find interface

**Comment by lavalamp** [comment]
Hard to imagine this being a bad thing to check.

**Comment by lavalamp** [comment]
Although-- now that I say that--

What about the case where the network interface is still coming online?

**Comment by ddysher** [comment]
I have a similar fix that's sitting for a week :(

#3337

**Pull request merged**
