### PR TITLE
Change the enforce-node-allocatable option usage

### PR DESCRIPTION
**Pull request by viviyww**
When run kubelet in window system, and we set enforce-node-allocatable
as none. pod, system-reserved, kube-reserved, but it still has errors.
And we need to set it to "" and it is ok. So I think we should change
the option usage comments. The default value for this is [pod].

Errors like:
# kubelet --enforce-node-allocatable none --cgroups-per-qos false
F0919 11:16:14.455634    1276 server.go:213] [invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) is not supported unless CgroupsPerQOS (--cgroups-per-qos) feature is turned on, invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) [none] is not supported on Windows]

### CODE REVIEW

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Hmm, I'm a little concerned about just updating the documentation, and not addressing the issue where `none` is causing failures. Would you mind sharing the error message you're seeing when you set it to `none` and perhaps the community could help you debug it a bit?

**Comment by viviyww** [comment]
> 
> 
> Hmm, I'm a little concerned about just updating the documentation, and not addressing the issue where `none` is causing failures. Would you mind sharing the error message you're seeing when you set it to `none` and perhaps the community could help you debug it a bit?

Hi, I have updated the commit comment.

**Comment by mattjmcnaughton** [comment]
> > Hmm, I'm a little concerned about just updating the documentation, and not addressing the issue where `none` is causing failures. Would you mind sharing the error message you're seeing when you set it to `none` and perhaps the community could help you debug it a bit?
> 
> Hi, I have updated the commit comment.

Thanks! What would you think of closing this pr, and instead opening an issue to address the underlying issue? Unless I'm misunderstanding things, I think the problem is that there is an actual bug, as opposed to the documentation being wrong.

**Comment by viviyww** [comment]
> 
> 
> > > Hmm, I'm a little concerned about just updating the documentation, and not addressing the issue where `none` is causing failures. Would you mind sharing the error message you're seeing when you set it to `none` and perhaps the community could help you debug it a bit?
> > 
> > 
> > Hi, I have updated the commit comment.
> 
> Thanks! What would you think of closing this pr, and instead opening an issue to address the underlying issue? Unless I'm misunderstanding things, I think the problem is that there is an actual bug, as opposed to the documentation being wrong.

Hello, I take a closer look at the process and if we set this as "", and then it will use the default value pods. Doesn't that seem to be a problem. Maybe it is not a bug.

**Comment by Pingan2017** [comment]
[invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) is not supported unless CgroupsPerQOS (--cgroups-per-qos) feature is turned on,

how about :
It shouled be set to '' when CgroupsPerQOS(--cgroups-per-qos) feature is turned off.

**Pull request closed without merging**
