### PR TITLE
Owners file related changes for kubectl and docs contributors

### PR DESCRIPTION
**Pull request by pwittrock**
- adding a command to kubectl updates the root .generated_docs file requiring root level approval: move .generated_docs under docs/
- run hack/update-generated-docs.sh so the docs are up to date
- add kubectl contributors to test/OWNERS and test/fixtures/pkg/kubectl/OWNERS so they can approve kubectl e2e test changes

```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
@k8s-bot kubemark e2e test this

**Comment by pwittrock** [comment]
@k8s-bot gci gke e2e test this

**Comment by spxtr** [comment]
This seems fine to me, but I don't really have context or approver-power. I'll assign to @dchen1107.

**Comment by pwittrock** [comment]
@k8s-bot cross build this

**Comment by dchen1107** [comment]
/lgtm 
and 
/approve

**Comment by spxtr** [comment]
@k8s-bot cross build this

**Pull request merged**
