### PR TITLE
Move pkg/client/unversioned/cache to pkg/client/cache; it is version-…

### PR DESCRIPTION
**Pull request by lavalamp**
…agnostic.

### CODE REVIEW

**Comment by smarterclayton** [comment]
+1

**Comment by smarterclayton** [comment]
LGTM once rebased

**Comment by lavalamp** [comment]
Rebased (actually redid, this is impossible to rebase), also included the other movement in the same PR since it's a pain to rebase these.

**Comment by lavalamp** [comment]
Rebased again.

**Comment by quinton-hoole** [comment]
Kicked Shippable.

**Comment by smarterclayton** [comment]
ok-to-merge

On Fri, Sep 4, 2015 at 9:46 PM, k8s-merge-robot <notifications@github.com>
wrote:

> The author of this PR is not in the whitelist for merge, can one of the
> admins add the 'ok-to-merge' label?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13341#issuecomment-137892632>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
.... and I missed getting it before it needed to rebase

**Comment by wojtek-t** [comment]
@lavalamp - please rebase

**Comment by wojtek-t** [comment]
@lavalamp - can you please rebase?

**Comment by lavalamp** [comment]
Rebased AGAIN. Hopefully the flag underscore thingy I now see not passing locally is something wrong with my setup.

@k8s-oncall please prioritize merging this if possible.

**Comment by mikedanese** [comment]
Will merge on green.

**Comment by lavalamp** [comment]
Thanks!

**Comment by mikedanese** [comment]
Well, he's right...

**Comment by lavalamp** [comment]
Lol. That should be suppressed if it's already been merged. Also I think we need a better system for rebases, the fewer people necessary in the loop the better. hm.

**Pull request merged**
