### PR TITLE
Fix syncReplicaSet by re-enqueuing on a wider criterion

### LINKED ISSUE #67662: Create pod failed and not retry due to controller manager ignore timeout error
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

**What happened**:

In some case, controller manager failed to create pod as replicas number defined in ReplicaSet spec. Normally if  replicaset controller fails to create a pod, it will try later.

(https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L437)

```
func (rsc *ReplicaSetController) processNextWorkItem() bool {
	key, quit := rsc.queue.Get()
	if quit {
		return false
	}
	defer rsc.queue.Done(key)

	err := rsc.syncHandler(key.(string))
	if err == nil {
		rsc.queue.Forget(key)
		return true
	}

	utilruntime.HandleError(fmt.Errorf("Sync %q failed with %v", key, err))
	rsc.queue.AddRateLimited(key)

	return true
}
```

But `manageReplicas` func in `syncHandler` ignore timeout error for some reason(https://github.com/kubernetes/kubernetes/pull/49915), then if a create pod request really timeout during accessing apiserver, this failed `key` will not add to the queue again. Then the pod should be created will never be created again.

(https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L497)

```
			err := rsc.podControl.CreatePodsWithControllerRef(rs.Namespace, &rs.Spec.Template, rs, controllerRef)
			if err != nil && errors.IsTimeout(err) {
				// Pod is created but its initialization has timed out.
				// If the initialization is successful eventually, the
				// controller will observe the creation via the informer.
				// If the initialization fails, or if the pod keeps
				// uninitialized for a long time, the informer will not
				// receive any update, and the controller will create a new
				// pod when the expectation expires.
				return nil
			}
			return err
```

I saw this happened in a production environment.

```
I0808 15:42:02.252808       1 controller_utils.go:158] Updating ready status of pod app-485859248-app-v1-0-cfb4f7c97-5bqx2 to false
I0808 15:42:02.268176       1 controller_utils.go:158] Updating ready status of pod app-485859248-app-v1-0-cfb4f7c97-n5tj8 to false
I0808 15:45:32.723956       1 controller_utils.go:95] Starting deletion of pod data-infra/app-485859248-app-v1-0-cfb4f7c97-5bqx2
I0808 15:45:32.732262       1 replica_set.go:477] Too few replicas for ReplicaSet data-infra/app-485859248-app-v1-0-cfb4f7c97, need 4, creating 1
I0808 15:45:32.740614       1 controller_utils.go:95] Starting deletion of pod data-infra/app-485859248-app-v1-0-cfb4f7c97-n5tj8
I0808 15:46:32.737094       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"data-infra", Name:"app-485859248-app-v1-0-cfb4f7c97", UID:"cd2edaad-956c-11e8-abf4-00163e042223", APIVersion:"extensions", ResourceVersion:"5302543", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: the server was unable to return a response in the time allotted, but may still be processing the request (post pods)
```

**What you expected to happen**:

 Controller manager will retry and create pod again.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @caesarxuchao

### PR DESCRIPTION
**Pull request by goodluckbot**
**What this PR does / why we need it**:
Fix syncReplicaSet in replica_set.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67662

**Special notes for your reviewer**:
NONE

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@goodluckbot PTAL at the failing verify test:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67996/pull-kubernetes-verify/104701/

thanks.

**Comment by liggitt** [comment]
this needs a test demonstrating the bug it is fixing

**Pull request closed without merging**
