### PR TITLE
Copy edits for typos

### PR DESCRIPTION
**Pull request by epc**
CLA signed previously.
`/hack/update-generated-docs.sh` run.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by epc** [comment]
I just rebased this, didn't notice it hadn't been merged until this morning.

**Comment by wojtek-t** [comment]
@epc - please rebase

**Comment by epc** [comment]
Rebased…again.

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@epc - can you please rebase one more time (sorry for that - we had huge problems with our tests)

/workspace/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh

**Comment by epc** [comment]
You've added docker as a dependency to building the kubernetes docs?  Seriously?

**Comment by epc** [comment]
Rebased & reran both `./hack/verify-generated-docs.sh` and `./hack/update-generated-docs.sh`.
The first time I ran update-generated-docs.sh it complained that I didn't have docker installed, but after running verify-generated-docs.sh first then it proceeded w/o complaint (I still don't have docker installed).

**Comment by wojtek-t** [comment]
I'm afraid it's still not solved:

/workspace/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
FAILED

**Comment by wojtek-t** [comment]
What you really need to run is
hack/update-api-reference-dosc.sh

**Comment by epc** [comment]
Rebased, reinstalled docker, re-ran `hack/update-api-reference-docs.sh`, re-pushed branch.

**Comment by wojtek-t** [comment]
@epc - thanks; looks much better now

LGTM - thanks for your change!

**Pull request merged**
