### PR TITLE
Change the node name from "machine" to "node"

### PR DESCRIPTION
**Pull request by chendave**
Latest change on master (https://github.com/kubernetes/kubernetes/pull/92571)  rename the node name from "machine" to "node"
but haven't update all the affected code, which causes some of testcases
invalid.

Depends on https://github.com/kubernetes/kubernetes/pull/92752

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
/hold for https://github.com/kubernetes/kubernetes/pull/92752

this could pass the CI unless the above one merged.

**Comment by chendave** [comment]
/assign @Huang-Wei 

may you take a look?

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Given 1.19 is code freezed, and this is not a must-have for 1.19, so
/hold

Feel free to unhold when 1.20 cycle starts.

**Comment by chendave** [comment]
> /lgtm
> /approve
> 
> Given 1.19 is code freezed, and this is not a must-have for 1.19, so
> /hold
> 
> Feel free to unhold when 1.20 cycle starts.

sure, seems like 1.20 cycle will be scheduled two month later?

**Comment by dims** [comment]
@chendave k8s master is open for business now. changes will not be automatically picked to 1.19 release branch though.

**Comment by Huang-Wei** [comment]
Thanks @dims.

/hold cancel
BTW: this is NOT a 1.19 candidate.

**Comment by chendave** [comment]
thank you @dims @Huang-Wei !

**Pull request merged**
