### PR TITLE
Automated cherry pick of #15409

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #15409 on release-1.1.

### CODE REVIEW

**Comment by lavalamp** [comment]
Is the remaining part of the "fix after rebase" commit necessary, or can it be combined with the commit that introduced the changes? :)

**Comment by caesarxuchao** [comment]
The remaining is necessary. Those only exist in the 1.1 branch, not in the master, so they need a commit to fix.

**Comment by lavalamp** [comment]
OK, I understand. LGTM

**Comment by caesarxuchao** [comment]
Shippable is a flake:

```
FAILED: pod never started running timed out waiting for the condition
```

**Pull request merged**
