### PR TITLE
Use cloud-controller-manager by default on CI

### PR DESCRIPTION
**Pull request by elmiko**
/kind cleanup

this is a continuation of the work started by @aojea in https://github.com/kubernetes/kubernetes/pull/114557

### CODE REVIEW

**Comment by andrewsykim** [comment]
Periodic job running e2e tests in k8s.io/cloud-provider-gcp pulling latest k/k: https://testgrid.k8s.io/provider-gcp-periodics#E2E%20Full%20-%20Cloud%20Provider%20GCP%20-%20with%20latest%20k8s.io/kubernetes

**Comment by dims** [comment]
Sweet @andrewsykim !!

**Comment by elmiko** [comment]
/hold

do we want to squash this before merging?

**Comment by elmiko** [comment]
cool, i'll put a new version up today

**Comment by elmiko** [comment]
squashed and combined commit messages

**Pull request merged**
