### PR TITLE
vclib: enable VM disk attach test

### PR DESCRIPTION
**Pull request by dougm**
**What this PR does / why we need it**:

Follow up to PR #58534 , where this test was disabled due to a limitation in
govmomi/simulator.  The test passes as expected with godeps update of govmomi.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This PR is 1-line update to the vSphere Cloud Provider tests and godep update of the vendor'd vmware/govmomi repo.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dougm** [comment]
@divyenpatel this is a follow up to my previous PR you had reviewed, taking care a TODO item.  Can you PTAL?

**Review by divyenpatel — APPROVED** [review]

**Comment by dougm** [comment]
Deleted my remote branch by accident, GH auto closed the PR.  The "Reopen" button is grey'd out, I'll just open a new PR.

**Pull request closed without merging**
