### PR TITLE
kubeadm: remove ObjectMeta from output.BootstrapTooken

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

metav1.TypeMeta is what needed to make a runtime object.
ObjectMeta is not needed and can be safely removed.

```release-note
NONE
```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/lgtm
/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
@bart0sh thanks!
/approve
/lgtm
/hold
leaving the last world to @rosti as suggested by @neolit123  (feel free to unhold)

**Comment by bart0sh** [comment]
@rosti kindly ping for approval.

**Review by rosti — APPROVED** [review]
Thanks @bart0sh !
And sorry for the delay!
/hold cancel
/lgtm
/approve

**Pull request merged**
