### PR TITLE
Skip Kubectl deployment test on clusters older that v1.2.0-alpha.7.726

### LINKED ISSUE #21421: v1.2 Deployment e2e shouldn't run against against masters before v1.2
Right now, the following test is running from v1.2 clients against v1.1 masters:

**Kubectl client Kubectl run deployment should create a deployment from an image [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:938 Expected error: <errors.errorString | 0xc20855cfd0>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.3 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config run e2e-test-nginx-deployment --image=nginx --namespace=e2e-tests-kubectl-7chcz] [] Error from server: the server could not find the requested resource\n [] 0xc2085564a0 exit status 1 true [0xc20803ce60 0xc20803ce98 0xc20803cec8] [0xc20803ce60 0xc20803ce98 0xc20803cec8] [0xc20803ce80 0xc20803cec0] [0x886450 0x886450] 0xc208648420}:\nCommand stdout:\n\nstderr:\nError from server: the server could not find the requested resource\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.3 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config run e2e-test-nginx-deployment --image=nginx --namespace=e2e-tests-kubectl-7chcz] [] Error from server: the server could not find the requested resource [] 0xc2085564a0 exit status 1 true [0xc20803ce60 0xc20803ce98 0xc20803cec8] [0xc20803ce60 0xc20803ce98 0xc20803cec8] [0xc20803ce80 0xc20803cec0] [0x886450 0x886450] 0xc208648420}: Command stdout: stderr: Error from server: the server could not find the requested resource error: exit status 1 not to have occurred*

My guess is that this test is not expected to pass against pre-v1.2 clusters.

Enabling deployments by default was incorporated in CI build `v1.2.0-alpha.7.726+0615f52054378a`.

cc @janetkuo

### PR DESCRIPTION
**Pull request by ikehz**
Fixes #21421.

### CODE REVIEW

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-csi

**Comment by bgrant0607** [comment]
@ihmccreery FYI, this is a UX feature, not CSI.

**Comment by ihmccreery** [comment]
@k8s-bot test this again please, issue #21485

**Comment by ihmccreery** [comment]
@k8s-bot Test this again please, issue #21490

**Comment by ihmccreery** [comment]
@k8s-bot unit test this again please issue #18708

**Pull request merged**
