### PR TITLE
Remove independent tests for job metrics

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Moves checks for some metrics into bigger tests. This should reduce the runtime of the suite. In my local machine, it shaved ~10s.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by alculquicondor** [comment]
/retitle Remove independent tests for metrics


It actually doesn't need a rebase. The bot failed to remove the label. Could you manually remove it @dims?

**Comment by alculquicondor** [comment]
/retitle Remove independent tests for job metrics

**Comment by dims** [comment]
Done! thanks @alculquicondor

**Review by kannon92 — COMMENTED** [review]
/lgtm

**Pull request merged**
