### PR TITLE
Fix test for provisioning in unmanaged zone.

### PR DESCRIPTION
**Pull request by jsafrane**
defer evaluates arguments of the deferred function immediately, so it actually
deleted a storage class and a claim before the test could do anything useful.

The test passed just accidentally, as the test is expected to time out. It
timed out from wrong reasons though.

@copejon @kubernetes/sig-storage-pr-reviews 

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot unit test this
@k8s-bot kops aws e2e test this

**Comment by jsafrane** [comment]
rebased, restoring lgtm

**Comment by ixdy** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot non-cri node e2e test this

**Comment by jsafrane** [comment]
rebased, restoring lgtm

**Comment by ixdy** [comment]
This appears to have broken gce-gce-slow? https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/3730/

**Comment by rmmh** [comment]
It looks like line 202 should be deleted as well for symmetry.

Or, instead of deferring these functions, just call them at the end of the test? It would be easier to read.

**Pull request merged**
