### PR TITLE
Ipvs: Enable Source Port hash flag for "mh" method.

### LINKED ISSUE #115526: kube-proxy IPVS mode configured with method SourceHash and Maglev should evenly distribute connections to all endpoints
### What would you like to be added?

# Problem
The current support of the load distribution method `sh` and `mh` in kube-proxy ipvs mode only performs hashing of source IP address to select endpoints. As a result, all connections from a single client (i.e. from a particular source IP) are always forwarded to only one endpoint matching with the hash value of this source IP. If the client opens a vast majority of connections to the k8s cluster, it will result in traffic imbalance as only one endpoint located on one node handles the connections while the remaining endpoints/nodes are idle. 

Here is an example of the problem when using `mh` method for kube-proxy

- Deploy a service with 4 endpoints located on 4 nodes.

```console
~ # kubectl get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
alpine-deployment-ffdbfd876-hzff4   1/1     Running   0          2m24s   11.0.2.2   node-002   <none>           <none>
alpine-deployment-ffdbfd876-vrw69   1/1     Running   0          2m24s   11.0.1.2   node-001   <none>           <none>
alpine-deployment-ffdbfd876-w4vh5   1/1     Running   0          2m24s   11.0.4.2   node-004   <none>           <none>
alpine-deployment-ffdbfd876-xgd59   1/1     Running   0          2m24s   11.0.3.2   node-003   <none>           <none>

~ # kubectl get services
NAME             TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
alpine-service   LoadBalancer   12.0.234.80   <pending>     7001:32000/TCP   3m56s
```

- Open 200 connections from a client to node IP of any node (e.g. telnet 192.168.1.1 32000). All connections receive replies from only one single endpoint.

- The distribution printout also shows that all connections are forwarded to the endpoint (e.g. 1.0.4.2:5001 in this example)
```console
TCP  192.168.1.1:32000 mh
  -> 11.0.1.2:5001                Masq    1      0          0
  -> 11.0.2.2:5001                Masq    1      0          0
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.4.2:5001                Masq    1      0          200
```
- Similar issue is seen with `sh` method

```console
TCP  192.168.1.1:32000 sh
  -> 11.0.1.2:5001                Masq    1      0          200
  -> 11.0.2.2:5001                Masq    1      0          0
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.4.2:5001                Masq    1      0          0
```

### Why is this needed?

Connections from a client should be evenly distributed to all endpoints like `rr` to avoid unbalanced load distribution between cluster nodes and endpoints.

This can be easily done by enabling the source port hash flag that IPVS supports for the methods which performs hashing on both source IP and source port when selecting the target endpoint.

```
 sh - Source Hashing: assigns jobs  to  servers  through  looking  up  a  statically
              assigned  hash  table  by their source IP addresses.  This scheduler has two flags:
              sh-fallback, which enables fallback to a different server if  the  selected  server
              was  unavailable,  and  sh-port,  which  adds  the  source  port number to the hash
              computation.

mh  -  Maglev  Hashing:  assigns  incoming  jobs  based  on Google's Maglev hashing
              algorithm, providing an almost equal share of jobs to each real server and provides
              minimal  disruption. When the set of real servers changes, a connection will likely
              be sent to the same real server as it was before.  This scheduler  has  two  flags:
              mh-fallback,  which  enables  fallback to a different server if the selected server
              was unavailable, and mh-port, which  adds  the  source  port  number  to  the  hash
              computation.
```

### PR DESCRIPTION
**Pull request by sondinht**
#### What type of PR is this?
/kind bug
/area kube-proxy
/area ipvs

#### What this PR does / why we need it:

When using `mh` or `sh`, kube-proxy always forwards connections from a client to only one single endpoint, leading to imbalance of traffic distribution as this endpoint is always busy to handle new connections while the others located on other nodes are entirely idle. See example in #115526 for more details.

The connections should be evenly distributed to all running endpoints to avoid unbalanced traffic distribution in this particular use-case when one dominant client can generate a vast majority of connections/traffic to a k8s cluster. 

#### Which issue(s) this PR fixes:
Fixes #115526

#### Special notes for your reviewer:

The fix in this PR simply enables the source port hash flag that IPVS supports for the distribution methods which includes both source IP and source port in calculating hash and selecting the target endpoint. Connections from a client with different source ports will be thus forwarded to all endpoints.

After enabling the flag, ipvs evenly distributes connections from a client to all endpoints like the printout examples below
```console
TCP  192.168.1.1:32000 mh (mh-port)
  -> 11.0.1.2:5001                Masq    1      0          41
  -> 11.0.2.2:5001                Masq    1      0          54
  -> 11.0.3.2:5001                Masq    1      0          50
  -> 11.0.4.2:5001                Masq    1      0          55
```

```console
TCP  192.168.1.1:32000 sh (sh-port)
  -> 11.0.1.2:5001                Masq    1      0          48
  -> 11.0.2.2:5001                Masq    1      0          50
  -> 11.0.3.2:5001                Masq    1      0          51
  -> 11.0.4.2:5001                Masq    1      0          51
```

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by gjkim42 — COMMENTED** [review]
> The connections should be evenly distributed to all running endpoints to avoid unbalanced traffic distribution in this particular use-case when one dominant client can generate a vast majority of connections/traffic to a k8s cluster.

I think this PR can break the existing use cases. Some users may use `sh` or `mh` to not distribute their traffic evenly on purpose.

Maybe, it would be better to introduce `sh-port` or `mh-port` modes.

**Comment by sondinht** [comment]
> > The connections should be evenly distributed to all running endpoints to avoid unbalanced traffic distribution in this particular use-case when one dominant client can generate a vast majority of connections/traffic to a k8s cluster.
> 
> I think this PR can break the existing use cases. Some users may use `sh` or `mh` to not distribute their traffic evenly on purpose.
> 
> Maybe, it would be better to introduce `sh-port` or `mh-port` modes.

IMO, new modes for `sh-port` or `mh-port` are not really needed because the requirement for enabling session affinity from a client IP is not specific to `sh` or `mh`.

Users can set `sessionAffinity` to ClientIP in the service spec regardless of the used distribution method if they want to keep all connections from a source IP being handled by a pod. For instance:

```
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 5001
      nodePort: 32000
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
```

With this option enabled, kube-proxy forwards all connections from a client IP to the same pod within the configured timeoutSeconds as the example below

```console
TCP  192.168.1.1:32000 mh (mh-port) persistent 300
  -> 11.0.1.2:5001                Masq    1      0          0
  -> 11.0.2.2:5001                Masq    1      0          200
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.4.2:5001                Masq    1      0          0
```

**Comment by gjkim42** [comment]
> Users can set `sessionAffinity` to ClientIP in the service spec regardless of the used distribution method if they want to keep all connections from a source IP being handled by a pod. For instance:

This means users who don't change the specs may get sudden behavior changes.
I guess changing the existing behavior needs a [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) at least.

This looks more like a feature than a bug.

/remove-kind bug
/kind feature

**Comment by sondinht** [comment]
> This means users who don't change the specs may get sudden behavior changes. I guess changing the existing behavior needs a [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) at least.
> 
> This looks more like a feature than a bug.

Agee with the classification for the PR. This Source Port Hash flag should have been enabled at the first place when `sh` and `mh` were introduced.

Since `mh` was just released in [v1.27.0-alpha.1](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#v1270-alpha1), it is probably not used widely I think.

**Comment by uablrek** [comment]
Without this fix the `sh` scheduler will not load-balance, which makes it pretty useless IMHO. But to make it useful _is_ backward incompatible.

So, I suggest you set this for the `mh` scheduler _only_ since that has not been supported until now. Let the useless `sh` scheduler be as it is.

**Comment by sondinht** [comment]
> ~Without this fix the `sh` scheduler will not load-balance, which makes it pretty useless IMHO. But to make it useful _is_ backward incompatible.~
> 
> Scratch that! `sh` without source port _is_ quite possible the useful case. The user want _all_ connections from a source to end up in the same destination POD, regardless of source port.
> 
> ~So, I suggest you set this for the `mh` scheduler _only_ since that has not been supported until now. Let the useless `sh` scheduler be as it is.~
> 
> May be the same for `mh`. To load-balance on source port feels a bit like an only-in-test-env thing.
> 
> Makes me doubtful of this entire PR...

Users can enable `sessionAffinity` explicitly in service spec to keep all connections from a source to be terminated in the same POD as I commented earlier in https://github.com/kubernetes/kubernetes/pull/115527#issuecomment-1418286604. 

Correct me if I'm wrong, the parameter `sessionAffinity` is implemented solely for this purpose, irrespective of the load distribution method being used (e.g. `rr` can be used with `sessionAffinity` for the same use-case when needed). 

To maintain potential NBC for `sh`, the PR can enable only the flag for `mh` like you suggested. Though, IMO, the support of `sh` without the flag seems to be an incomplete load distribution method in k8s.

**Comment by uablrek** [comment]
> To maintain potential NBC for sh, the PR can enable only the flag for mh like you suggested. Though, IMO, the support of sh without the flag seems to be an incomplete load distribution method in k8s.

Fair point. But _if_ there are `sh` users out there they are most likely counting on the current behavior. So, I will approve the update for `mh` only. It should be merged before [Mars 15](https://www.kubernetes.dev/resources/release/) to get into v1.27.

This PR should be renamed and reclassified as a bug on the previously added [feature](https://github.com/kubernetes/kubernetes/issues/114619)

**Comment by uablrek** [comment]
@gjkim42 Thanks for pointing out the `sh` backward incompatibility. I would have missed it :smile:

**Review by uablrek — APPROVED** [review]

**Comment by uablrek** [comment]
Accepted as a part of the [allow mh scheduler](https://github.com/kubernetes/kubernetes/issues/114619) feature. The behaivor of `sh` remains as-is.

I have tested this PR with `mh` scheduler for ClusterIP, loadBalancerIP and externalIPs. I also tested that the `sh` scheduler still behaves as before.

/lgtm

**Comment by uablrek** [comment]
/assign @thockin
/assign @andrewsykim 

You are approvers for the [pkg/util/ipvs/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/ipvs/OWNERS) update. If it's acceptable, please add me as approver/reviewer in that file,

**Comment by thockin** [comment]
@uablrek send me a PR to add yourself to OWNERS, then you can approve this :)

**Comment by gjkim42** [comment]
It looks fine to fix the behavior of `mh` scheduler if it has not been released yet.

Anyway, I have a question for the naming.
Do we need to reserve `mh` for just mh without source port hashing and use a different name(e.g. `mh-port`) for this scheduler?

**Comment by sondinht** [comment]
> Anyway, I have a question for the naming. Do we need to reserve `mh` for just mh without source port hashing and use a different name(e.g. `mh-port`) for this scheduler?

The name of ipvs scheduler supported by k8s ipvs mode is one-one mapping with the distribution method that ipvs is currently supporting. IMO, having an additional name `mh-port` for `mh` will:
- Confuse users as they can neither find the description of `mh-port` in ipvs or k8s document.
- Need additional codes in proxier to handle the new name which contradicts to the original idea of the previous PR [114878](https://github.com/kubernetes/kubernetes/pull/114878). This PR tries to remove the check of the supported scheduler name.

**Pull request merged**
