### PR TITLE
Automated cherry pick of #33280

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #33280 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33949)

### CODE REVIEW

**Comment by freehan** [comment]
LGTM

**Comment by freehan** [comment]
Need one more person to take a final look.

**Comment by bprashanth** [comment]
@freehan requesting secondary review for the code *in* 0.8.0 (already checked in), or this pr (which is a version bump)?

**Comment by freehan** [comment]
This is just a version bump in k8s main repo. The code change for 0.8.0 is in contrib repo. Suggesting  secondary review for the code change in 0.8.0.

**Comment by bprashanth** [comment]
Yeah that's already in, and you're probably the best reviewer for that too, which is why I put you on it :)
https://github.com/kubernetes/contrib/pull/1771, https://github.com/kubernetes/contrib/pull/1820

If you go over the code once again and re-raise concerns, I can fix them in retro before this goes in.

**Comment by freehan** [comment]
LGTM. Bunch of bug fixes.

**Comment by jessfraz** [comment]
does this fix specific issues that we need to close when it is merged?

**Comment by bprashanth** [comment]
yes https://github.com/kubernetes/kubernetes/issues/33279, forgot to prefix "fixes" with the bug link in my initial pr

**Comment by jessfraz** [comment]
awesome I added all the label so it should go through the queue

**Pull request merged**
