### PR TITLE
it is 2017 now. change 2016 to 2017

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
it is 2017 now. change 2016 to 2017

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jellonek** [comment]
What about other files which have 2014, 2015? ;)

**Comment by zhangxiaoyu-zidif** [comment]
@jellonek Great, you mention it. I will put them in this PR. =)

**Comment by liggitt** [comment]
No, the header stays locked to the year the file was created

**Comment by zhangxiaoyu-zidif** [comment]
@liggitt I feel confused. I just refer to https://github.com/kubernetes/kubernetes/pull/25500. Some rules changed or I miss something?

**Comment by zhangxiaoyu-zidif** [comment]
@nebril @pigmej  please refer to https://github.com/kubernetes/kubernetes/pull/25500. I am much more confused.

**Comment by liggitt** [comment]
That PR was only changing generated files. That already happened for 2017 in https://github.com/kubernetes/kubernetes/pull/39342

**Comment by zhangxiaoyu-zidif** [comment]
@liggitt Thank you for your explanation. I see it. =)

**Pull request closed without merging**
