### PR TITLE
Automated cherry pick of #104279: Copy golang license to staging copies

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #104279 on release-1.20.

#104279: Copy golang license to staging copies

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
from RelEng:
/lgtm

**Pull request merged**
