### PR TITLE
Add more tracing steps in generic_scheduler

### LINKED ISSUE #83399: Add more tracing steps in generic_scheduler
**What would you like to be added**:
We have [trace](https://github.com/kubernetes/kubernetes/blob/dc0013a506d50c54d5a5833e92d82fce61301c2e/pkg/scheduler/core/generic_scheduler.go#L195) enabled in generic_scheduler. However, the steps being traced seem outdated. In particular, the "snapshot" is expensive and should be traced. Other steps can be traced as well wherever appropriate, e.g., PreFilter.

**Why is this needed**:
Improve granularity of tracing.

/sig scheduling

### PR DESCRIPTION
**Pull request by wgliang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #83399

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add more tracing steps in generic_scheduler
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by liu-cong** [comment]
Be aware that this change is likely to affect how trace log is triggered for each step. Looking at the implementation of the `trace` package, if there are `n` steps, log for each step is triggered if the step takes longer than `threshold/n` (in our case, `threshold`=100ms). A common trace log will be printed  if the function takes longer than 100ms and this behavior is not changed.
In practice some heavy features like pod affinity tend to take long time and therefore is more likely to be traced in the "Priority" step.

But in general it lgtm. @ahg-g , do you have any concerns?

**Comment by ahg-g** [comment]
> Be aware that this change is likely to affect how trace log is triggered for each step. Looking at the implementation of the `trace` package, if there are `n` steps, log for each step is triggered if the step takes longer than `threshold/n` (in our case, `threshold`=100ms). A common trace log will be printed if the function takes longer than 100ms and this behavior is not changed.
> In practice some heavy features like pod affinity tend to take long time and therefore is more likely to be traced in the "Priority" step.
> 
> But in general it lgtm. @ahg-g , do you have any concerns?

I don't have concerns about that in particular, but we should limit the number of steps to 6 to avoid making another allocation, I think the last one "selecting host" can be dropped (we can certainly consider it as part of prioritizing), the first one as well "basic checks" we can drop as well.

**Comment by wgliang** [comment]
> > Be aware that this change is likely to affect how trace log is triggered for each step. Looking at the implementation of the `trace` package, if there are `n` steps, log for each step is triggered if the step takes longer than `threshold/n` (in our case, `threshold`=100ms). A common trace log will be printed if the function takes longer than 100ms and this behavior is not changed.
> > In practice some heavy features like pod affinity tend to take long time and therefore is more likely to be traced in the "Priority" step.
> > But in general it lgtm. @ahg-g , do you have any concerns?
> 
> I don't have concerns about that in particular, but we should limit the number of [steps to 6](https://github.com/kubernetes/kubernetes/blob/1c9d1f006feec678afc12d208c5285d7dde9a566///vendor/k8s.io/utils/trace/trace.go#L74) to avoid making another allocation, I think the last one "selecting host" can be dropped (we can certainly consider it as part of prioritizing), the first one as well "basic checks" we can drop as well.

Basically agree with you that `Selecting host done` does not have any complicated calculations and external dependencies and can be removed. But I have a different opinion on `basic checks`, podPassesBasicChecks contains `pvc` check requests, I suggest we can keep it.

```
pvcName := volume.PersistentVolumeClaim.ClaimName
Pvc, err := pvcLister.PersistentVolumeClaims(namespace).Get(pvcName)
If err != nil {
// The error has already enough context ("persistentvolumeclaim "myclaim" not found")
Return err
}
```

**Comment by ahg-g** [comment]
> > > Be aware that this change is likely to affect how trace log is triggered for each step. Looking at the implementation of the `trace` package, if there are `n` steps, log for each step is triggered if the step takes longer than `threshold/n` (in our case, `threshold`=100ms). A common trace log will be printed if the function takes longer than 100ms and this behavior is not changed.
> > > In practice some heavy features like pod affinity tend to take long time and therefore is more likely to be traced in the "Priority" step.
> > > But in general it lgtm. @ahg-g , do you have any concerns?
> > 
> > 
> > I don't have concerns about that in particular, but we should limit the number of [steps to 6](https://github.com/kubernetes/kubernetes/blob/1c9d1f006feec678afc12d208c5285d7dde9a566///vendor/k8s.io/utils/trace/trace.go#L74) to avoid making another allocation, I think the last one "selecting host" can be dropped (we can certainly consider it as part of prioritizing), the first one as well "basic checks" we can drop as well.
> 
> Basically agree with you that `Selecting host done` does not have any complicated calculations and external dependencies and can be removed. But I have a different opinion on `basic checks`, podPassesBasicChecks contains `pvc` check requests, I suggest we can keep it.
> 
> ```
> pvcName := volume.PersistentVolumeClaim.ClaimName
> Pvc, err := pvcLister.PersistentVolumeClaims(namespace).Get(pvcName)
> If err != nil {
> // The error has already enough context ("persistentvolumeclaim "myclaim" not found")
> Return err
> }
> ```

sounds good, lets remove the select host step then.

/hold

**Pull request merged**
