### PR TITLE
Promote lease API test to Conformance

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/enhancements/issues/589

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
+1 to a more descriptive test name :)

Other than that, works for me :) Going to let someone else approve bc I must admit, I'm the most knowledgeable about what tests are Conformance tests and which ones aren't...

**Comment by liggitt** [comment]
lgtm

/retest

**Comment by smarterclayton** [comment]
/approve

Leases are required for implementation of efficient node status checks

**Comment by smarterclayton** [comment]
@johnbelamaric can you also take a peek at this (just to make sure I didn't miss anything)

**Pull request merged**
