### PR TITLE
Merge v9 tag

### PR DESCRIPTION
**Pull request by eparis**
https://github.com/GoogleCloudPlatform/kubernetes/pull/3663

did something wrong.  v0.9.0 is not in the master branch. This fix is a little awkward.  I went back in time to 9192a4ce228f86f1b05d2b1add6c52d6ac0ffb64 and merged the v0.9.0 tag in there. I then manually updated to 0.9+ which we want in development.

I does mean that we have commits like 96af0c3e5bac4c07635ac3653724c0721ed64403 where @brendandburns changed pkg/version/base.go in master which don't really mean anything. bisects on that path will give slightly weird versions, but no one will notice...

So history is non-linear.  Yes, this works.  Building on top of this commit will give versions like:
v0.9.0-150-g12ce8e9e0f9417
Which is what we want, the previous PR shows the problem with what we have today.

### CODE REVIEW

**Comment by dchen1107** [comment]
Thanks for the fix. LGTM to me, but still want @filbranden take another look. I kicked out the flaky travis for a rerun too.

**Comment by filbranden** [comment]
Let me take a closer look at it... I'm in meetings until 2pm Pacific, will look at it as soon as I have some free time.

Cheers,
Filipe

**Comment by eparis** [comment]
build failure appears to be unrelated....

**Comment by zmerlynn** [comment]
@jbeda is looking now

**Comment by jbeda** [comment]
This isn't what we want to do.  The problem is that the tag is pointing to the wrong commit.  Brendan pushed the tag to a commit that isn't referenced in any branch.  It is essentially an orphaned branch.

The correct thing to do here is to create a new tag and force push that to the master.  That new tag should point to the commit that is actually in the branch.

It might also be that the release that Brendan created is wrong too.

I'm going to close this and document the steps I take in the original issue.

**Comment by filbranden** [comment]
Yep... removing and recreating the tag to point to 96af0c3e5bac4c07635ac3653724c0721ed64403 is all we need here and looking at [`v0.9.0`](https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.9.0) it looks like Brendan just did that.

**Comment by dchen1107** [comment]
@eparis Thanks for looking into this. Now the issue is fixed by @jbeda. Closing this one.

**Pull request closed without merging**
