### PR TITLE
Fix some TODOs in e2e

### PR DESCRIPTION
**Pull request by brendandburns**
@gmarek @piosz @quinton-hoole

### CODE REVIEW

**Comment by wojtek-t** [comment]
@brendandburns - can you please rebase?

**Comment by mwielgus** [comment]
@k8s-bot test this

**Comment by brendandburns** [comment]
Rebased.  ptal.

thanks!
--brendan

**Comment by mwielgus** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
LGTM, all test pass.

**Comment by wojtek-t** [comment]
@brendandburns - can you please rebase?

**Comment by brendandburns** [comment]
removing LGTM, this is failing one of the e2e for some reason, will debug and re-add.

**Comment by fejta** [comment]
This PR has had no meaningful activity for multiple months. If it is still valid please rebase, push a new commit and reopen the PR. Thanks!

**Pull request closed without merging**
