### PR TITLE
Add verb to authorizer attributes

### PR DESCRIPTION
**Pull request by liggitt**
Related to https://github.com/kubernetes/kubernetes/issues/2877

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/kube-iam

**Comment by liggitt** [comment]
@k8s-bot ok to test

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by deads2k** [comment]
lgtm

**Comment by erictune** [comment]
lgtm

**Comment by liggitt** [comment]
rebased, tagged based on eric's lgtm

**Comment by deads2k** [comment]
> rebased, tagged based on eric's lgtm

ouch! :)

**Comment by liggitt** [comment]
@k8s-bot test this

**Pull request merged**
