### PR TITLE
Automated cherry pick of #65823: Fix truncating and buffering backends integration.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #65823 on release-1.10.

#65823: Fix truncating and buffering backends integration.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@loburm Can you add release note to #65823?

**Comment by loburm** [comment]
@MaciekPytel 
Done, thanks for pointing.

**Comment by loburm** [comment]
@sttts could you take a look?

**Pull request merged**
