### PR TITLE
Update moby/spdystream to v0.4.0

### PR DESCRIPTION
**Pull request by dims**
Needed to pick up one more PR https://github.com/moby/spdystream/pull/99

related to: https://github.com/moby/spdystream/issues/92

/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @thockin 

(yet another PR with only go.mod/sum changes)

**Comment by aojea** [comment]
👍 so fast

**Pull request merged**
