### PR TITLE
Move remaining *Options to metav1

### PR DESCRIPTION
**Pull request by smarterclayton**
Primarily delete options, but will remove all internal references to non-metav1 options (except ListOptions).

Still working through it @sttts @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton I'm working on a client-go/dynamic move which would conflict with this pull.  Is it close enough I should delay?

**Comment by smarterclayton** [comment]
Should be pretty close.

**Comment by smarterclayton** [comment]
Ready, assuming it goes green.

**Comment by smarterclayton** [comment]
Actually one more minor change.

**Comment by deads2k** [comment]
surprisingly painless.  lgtm

**Comment by deads2k** [comment]
All the previous moves for these types triggered rebase hell.  Bumping priority early this time.  Also, this blocks moving client-go package to client-go

**Comment by deads2k** [comment]
`TestRoundTripTypes`  When you update, you have remove and re-add both tags.

**Comment by smarterclayton** [comment]
Fixed the failures

**Comment by deads2k** [comment]
bazel `k8s.io/kubernetes/pkg/apis/policy/v1beta1/types.generated.go:27: can't find import: "github.com/ugorji/go/codec`

**Pull request merged**
