### PR TITLE
Rename 'preferred' TopologyManager policy to 'best-effort'

### PR DESCRIPTION
**Pull request by klueska**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Based on the feedback from https://docs.google.com/document/d/1g5Aqa0BncQGRedSJH0TJQWq3mw3VxpJ_ufO1qokJ1LE we have decided to rename the `preferred` policy of the `TopologyManager` to `best-effort`.  The reasoning for this is outlined in the document.

Since this change is coming before the `TopologyManager` was ever part of a release, this does not introduce a user-facing change.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by mattjmcnaughton** [comment]
Also, @klueska thoughts on applying for membership in the k8s community if you're going to be heavily contributing to the topology work? I think a main benefit would be that you don't need to wait for your prs to be marked "ok-to-test" :)

**Comment by klueska** [comment]
Yeah. That's probably a good idea. Can I add you as one of my 2 sponsors?

**Comment by lmdaly** [comment]
lgtm!

**Comment by mattjmcnaughton** [comment]
On Thu, Jul 18, 2019 at 06:55:41AM -0700, Kevin Klues wrote:
> Yeah. That's probably a good idea. Can I add you as one of my 2 sponsors?
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/80301#issuecomment-512825933

Sure if I meet the qualifications? I think you have to be an approver which I'm
not :)

**Comment by klueska** [comment]
@mattjmcnaughton can I get an /lgtm again please

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Pull request merged**
