### PR TITLE
Enable extensions/v1beta1/NetworkPolicy by default

### PR DESCRIPTION
**Pull request by caseydavenport**
Fixes https://github.com/kubernetes/kubernetes/issues/28401

For some reason this also triggered an update to the swagger spec (which apparently hadn't been done before but wasn't failing validation...)

### CODE REVIEW

**Comment by caseydavenport** [comment]
I still need to test this works.

**Comment by caseydavenport** [comment]
I've tested that this works using the vagrant provider - the NetworkPolicy resource is indeed enabled by default.

**Comment by thockin** [comment]
LGTM.  @derekwaynecarr are you OK to review this or should we get someone else?  We'll want to cherry-pick the min-set of this into 1.3.1.

Jenkins says: Please run hack/update-api-reference-docs.sh

@matchstick FYI

**Comment by caseydavenport** [comment]
OK - auto generation completed and all checks passing :)

What are we considering the minimum set that must be cherry-picked?  It seems like there is a bunch of API documentation that wasn't generated the first time around for some reason that should probably be cherry picked as well.

**Comment by thockin** [comment]
The min-set should be the master.go and docs.

**Comment by thockin** [comment]
I think this will have to be a manual or semi-manual cherrypick

**Comment by thockin** [comment]
did we get a cherry-pick for this?

**Comment by caseydavenport** [comment]
@thockin - I don't think so.  What is the process for a manual / semi-manual cherry-pick?

**Comment by fabioy** [comment]
@caseydavenport Cherrypick approved. Please create a cherrypick PR for this off the 1.3 release branch (not 1.3.0). Thank you.

**Comment by caseydavenport** [comment]
@fabioy thanks, I've opened https://github.com/kubernetes/kubernetes/pull/29556

**Pull request merged**
