### PR TITLE
Automated cherry pick of #64231: Update function hasClusterTag to fix issue #64230

### PR DESCRIPTION
**Pull request by ghost**
Cherry pick of #64231 on release-1.10.

#64231: Update function hasClusterTag to fix issue #64230

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vainu-arto** [comment]
release-note NONE

**Comment by vainu-arto** [comment]
**Release note**:

```release-note
NONE
```

**Comment by vainu-arto** [comment]
@MaciekPytel Any chance of getting this cherrypick applied? I have a production cluster that hits the bug this fixes, and could really use official binaries with the fix.

**Comment by MaciekPytel** [comment]
@vainu-arto Sorry I missed your comment. I've approved cherry-pick, but you also need an approval from code OWNER, same as for normal PR. 
In the meantime freezing branch for 1.10.10:
/hold

**Comment by vainu-arto** [comment]
/assign @justinsb @ihoegen @chrislovecnm 

Could one of you who reviewed/approved this PR on master also approve the cherrypick to 1.10? The code there is exactly the same, the PR is applied exactly as-is.

**Comment by MaciekPytel** [comment]
/hold cancel

The cherry-pick is approved, but it needs owner approve/lgtm by Thursday to make it into the final 1.10 release. I'll close this PR if it's not approved by then.

**Comment by MaciekPytel** [comment]
@vainu-arto @justinsb @ihoegen @chrislovecnm ^

**Comment by MaciekPytel** [comment]
With 1.13 released 1.10 has reached end of life. 1.10.12 was the last patch release and we're no longer accepting cherry-picks to 1.10 branch.

**Pull request closed without merging**
