### PR TITLE
kubelet/rkt: Fix a typo in container gc.

### PR DESCRIPTION
**Pull request by yifan-gu**
@timstclair Ehh, turns out I made a silly mistake.

### CODE REVIEW

**Comment by timstclair** [comment]
Oops! Time to add `rkt_test.go`? LGTM.

**Comment by yifan-gu** [comment]
@timothysc absolutely :P

**Comment by timstclair** [comment]
@timstclair :)

**Comment by yifan-gu** [comment]
That flip is caused by cosmic ray

**Pull request merged**
