### PR TITLE
remove resourcename validation in create role

### PR DESCRIPTION
**Pull request by xilabao**
@liggitt Since #44659 is not correct. I think we should fix the validation in create role command.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by xilabao** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by cblecker** [comment]
/lgtm
/release-note-none
/unassign
Adding LGTM on @liggitt's behalf :)

**Comment by xilabao** [comment]
@fabianofranz @pwittrock PTAL

**Pull request merged**
