### PR TITLE
Delete field.Path arg of assignSecurityContext()

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Comment by php-coder** [comment]
It's better to use this field because it simplifies debugging of problems when server is rejecting a request and you want to find out which provider was involved.

I have a PR for OpenShift that instead of removing this field, make it usable: https://github.com/openshift/origin/pull/13842

I'm awaiting @pweil- response and if he will approve it, I'd like to do the same changes in the Kubernetes.

**Comment by derekwaynecarr** [comment]
i will hold review pending @pweil-

**Comment by php-coder** [comment]
@pweil- ping

**Pull request closed without merging**
