### PR TITLE
apf: remove v1alpha1 API

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The v1alpha1 API was deprecated in v1.20 and has not been used since v1.21.
Given that the apf API has evolved to v1beta3, I think it makes sense to clean up the earlier API versions.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/api-review
/assign @liggitt 
For APF. Thank you.
/triage accepted

**Comment by liggitt** [comment]
This is only ok to do because we switched the storage version to v1beta1 in the same release v1beta1 was introduced (https://github.com/kubernetes/kubernetes/pull/96527/files#diff-1083ad1d288464507552098a30e5f816d56c19f15edf36aaae46afdf43fe1ecd). Otherwise, we could have persisted alpha data into etcd while the feature was in beta, and would *have* to remain able to decode and convert it.

**Comment by liggitt** [comment]
dropped the release note since this is not user-facing

/lgtm
/approve

**Comment by SataQiu** [comment]
> importantly, we cannot do the same thing with v1beta1, v1beta2, etc, even if a lot of time passes, since nothing currently ensures storage has been migrated

Got it. Thanks for the detailed explanation.

**Pull request merged**
