### PR TITLE
Move to extensions/v1beta1

### PR DESCRIPTION
**Pull request by caesarxuchao**
move from experimental/v1alpha1 to extensions/v1beta1

### CODE REVIEW

**Comment by caesarxuchao** [comment]
It's still WIP. I open the PR to track TODOs.

**Comment by caesarxuchao** [comment]
TODO:
1. fix the DISCLAIMER in pkg/apis/extensions/types.go

**Comment by lavalamp** [comment]
Also rename: client.Experimental() -> client.Extensions()

**Comment by caesarxuchao** [comment]
Yes, added to the TODO list. That can be a separate PR.

**Comment by lavalamp** [comment]
OK, I think a second PR is OK for the additional renames.

LGTM

**Comment by lavalamp** [comment]
I would ask for a squash, but I know the additional commits make rebases easier.

**Comment by caesarxuchao** [comment]
ref #15378

**Comment by lavalamp** [comment]
@caesarxuchao can you cherry-pick this? Let me know how difficult it is.

**Pull request merged**
