### PR TITLE
Automated cherry pick of #70392: Lookup PX api port from k8s service

### PR DESCRIPTION
**Pull request by harsh-px**
Cherry pick of #70392 on release-1.10.

#70392: Lookup PX api port from k8s service

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/ok-to-test

@harsh-px @jsafrane This needs lgtm/approve by Thursday to make it into 1.10.12. Note that 1.10.12 will be the last 1.10 release, so this is the only chance.

**Comment by harsh-px** [comment]
@jsafrane Can you take a look when you get a chance?

**Comment by MaciekPytel** [comment]
Sorry, this barely missed the deadline :(
With 1.13 released 1.10 has reached end of life. 1.10.12 was the last patch release and we're no longer accepting cherry-picks to 1.10 branch.

**Pull request closed without merging**
