### PR TITLE
Automated cherry pick of #37431

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #37431 on release-1.5.

#37431: hold namespaces briefly before processing deletion

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37629)

### CODE REVIEW

**Comment by dims** [comment]
@kubernetes/test-infra-maintainers @kubernetes/sig-testing - Anyone know why the status says "Github CI tests are not green." given that all the jenkins jobs are green?

**Comment by wojtek-t** [comment]
@dims - I've seen at least few more such PRs (one if this is mine). My hypothesis is that we have so many PRs and churn, that merge-bot is out of quota for api calls to github and is not picking up this information. But that's just my guess

**Comment by dims** [comment]
@wojtek-t : here's the issue for tracking this sort of issue https://github.com/kubernetes/contrib/issues/2102

**Comment by ixdy** [comment]
@k8s-bot unit test this

**Comment by dims** [comment]
@k8s-bot unit test this

**Pull request merged**
