### PR TITLE
fix typos: remove duplicated word in comments

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**: Remove the duplicated word `the` in comments

**Which issue this PR fixes** : fixes #

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by supereagle** [comment]
@smarterclayton for /approve

**Comment by cblecker** [comment]
@supereagle please check the author for your commit. It looks to not match your github user (may need to reset-author the commit)

**Comment by supereagle** [comment]
@cblecker  Thanks for reminding and tips, I have fixed this.

@k8s-bot ok to test

**Comment by supereagle** [comment]
@smarterclayton for /approve

**Comment by cblecker** [comment]
/assign @smarterclayton
for approval

**Comment by supereagle** [comment]
@cblecker @jayunit100 @smarterclayton  Have rebased. Please add /lgtm and /approve, thanks.

**Comment by cblecker** [comment]
/assign @smarterclayton 
for approval

**Comment by supereagle** [comment]
/assign @smarterclayton
for approval

**Pull request merged**
