### PR TITLE
reflect convertToAPIContainerStatuses in pkg/kubelet/kubelet_pods.go

### LINKED ISSUE #80875: Refactor kubelet convertStatusToAPIStatus
The kubelet's `convertStatusToAPIStatus()` in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go iterates `podStatus` 3 times in order to construct the 3 container status lists in `PodStatus`. This could be refactored to make a single pass through `podStatus`.

/kind cleanup
/sig node

### PR DESCRIPTION
**Pull request by yylt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind cleanup

**What this PR does / why we need it**:
reflect convertToAPIContainerStatuses() to make containerStatus at 1 time insert

**Which issue(s) this PR fixes**:

Fixes #80875

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Looping in @verb and @Rand01ph is I believe they are/were also working on this issue. @verb is this similar to what you pictured? Do you want to take over review here?

/cc @verb 

/ok-to-test

**Comment by yylt** [comment]
Hi @Rand01ph, Could you review this PR ? I also interesting how to merge handle with InitContainer or EphemeralContainer

**Comment by verb** [comment]
Thanks @mattjmcnaughton for looping me in. I'm happy to take over the review.

Hi @yylt, thanks for digging into this issue. I've added some [comments to the issue](https://github.com/kubernetes/kubernetes/issues/80875#issuecomment-548799862). Let's discuss there how to refactor this for all of the container types.

**Pull request closed without merging**
