### PR TITLE
When binding a pvc, Search for pv with a claimRef even if accessModes…

### PR DESCRIPTION
**Pull request by wongma7**
claimRef when specified is supposed to take precedence over all else, including accessModes. Currently only volumes with matching access modes are considered, this pr saves the unmatched ones and searches them for a pre-bound volume.

Originally reported here https://bugzilla.redhat.com/show_bug.cgi?id=1366500

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30522)

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by jsafrane** [comment]
If we need to match PVs regardless of their access mode, we need to go through *all* PVs and our mode-index (`pvIndex.listByAccessModes`) is completely useless.

Short term, I would propose to remove the index, match the mode manually and use shared informer as suggested by #26247. Long-term, we could add index based on ClaimRef namespace+name (to quickly find pre-bound volumes) and index based on volume size+mode (to find the smallest matching volume).

**Comment by wongma7** [comment]
@jsafrane I am working on the long-term solution. I have the index by ClaimRef working okay. and now I am not sure if volume size+mode index is actually needed or if I can keep the current mode index. Now with this solution it should quickly catch the pre-bound volume then proceed as it did before. I see in the past the list of volumes was sorted by size but that was too slow, would maintaining an index of volume size+mode be costly?

Also, discussion in BZ has started about whether this behavior should even be supported :)

**Comment by thockin** [comment]
Why is it more correct to bind in a way that is invalid and unlikely to work than to just not bind?

I move to close this PR as working-as-intended, and instead just update any errant docs.

**Comment by wongma7** [comment]
OK, if we close, I can make another PR to correct the behavior of capacity so that it must be satisfied for binding to occur.

(FWIW, I agree it makes more sense to enforce size & access modes always, ClaimRef will still work as a way for reserving a PV for a PVC)

@erinboyd

**Comment by thockin** [comment]
verify capacity sounds like verify mode, in other words correct.  I'd be happy to consider that PR.

**Pull request closed without merging**
