### PR TITLE
--image-gc-high-threshold should less than 100 - imagefs.available

### PR DESCRIPTION
**Pull request by olderTaoist**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
`ImageGCManager` garbage collect should before `Eviction Manager`

#### Which issue(s) this PR fixes:
Fixes #124868

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

KEP: [reasonable --image-gc-high-threshold](https://github.com/kubernetes/enhancements/pull/4739)

### CODE REVIEW

**Comment by haircommander** [comment]
I'm not personally sure what the process for tightening validation on an object is, but it's possible this needs a feature gate so a user upgrading to a version with this doesn't have sudden outages from this additional validation (without a little bit of warning at least)

If we don't think this warrants a full feature, maybe the kubelet could start by emitting an event about the misconfiguration, and then in some future version error on the case.

This may need discussion in SIG-Node meeting

**Comment by haircommander** [comment]
in the meantime, 
/ok-to-test

**Comment by olderTaoist** [comment]
> I'm not personally sure what the process for tightening validation on an object is, but it's possible this needs a feature gate so a user upgrading to a version with this doesn't have sudden outages from this additional validation (without a little bit of warning at least)
> 
> If we don't think this warrants a full feature, maybe the kubelet could start by emitting an event about the misconfiguration, and then in some future version error on the case.
> 
> This may need discussion in SIG-Node meeting

agree，add `ImageGCHighThresholdAccurate` feature gate

**Comment by haircommander** [comment]
I brought this up at this week's SIG Node meeting. we came to consensus that we should have a feature gate here, and correspondingly there should be a KEP so we can discuss the nitty gritty about it. One note @SergeyKanzhelev mentioned is we should make sure we can still allow image GC to be disabled (formerly done by setting to 100%) even if the eviction threshold is lower

**Comment by SergeyKanzhelev** [comment]
one scenario when customer may have wanted to set image GC threshold higher is to disable GC (when they know there is never anything to clean up). This change will affect those customers. Perhaps we can also introduce the disable image GC feature alongside this one?

**Comment by yujuhong** [comment]
> I brought this up at this week's SIG Node meeting. we came to consensus that we should have a feature gate here, and correspondingly there should be a KEP so we can discuss the nitty gritty about it. One note @SergeyKanzhelev mentioned is we should make sure we can still allow image GC to be disabled (formerly done by setting to 100%) even if the eviction threshold is lower

I wonder whether we actually need to fail the validation.... It seems to me a warning is probably sufficient since this is a node-level configuration.

**Comment by SergeyKanzhelev** [comment]
> I brought this up at this week's SIG Node meeting. we came to consensus that we should have a feature gate here, and correspondingly there should be a KEP so we can discuss the nitty gritty about it. One note @SergeyKanzhelev mentioned is we should make sure we can still allow image GC to be disabled (formerly done by setting to 100%) even if the eviction threshold is lower

Just to confirm the point: https://github.com/search?q=image-gc-high-threshold%3D100&type=code I saw more examples in other places.


> > I brought this up at this we...
> I wonder whether we actually need to fail the validation.... It seems to me a warning is probably sufficient since this is a node-level configuration.

Warning and ability to disable GC would be a great combination. No need to show a warning to people trying to disable the feature legitimately.

**Pull request closed without merging**
