### PR TITLE
stop: Check for error when resizing rcs

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by vmarmol** [comment]
@googlebot did you check this one?

**Comment by vmarmol** [comment]
LGTM, thanks!

**Comment by roberthbailey** [comment]
FYI, this looks like it's causing our e2e tests for kubectl to fail. @ixdy @quinton-hoole

**Comment by ixdy** [comment]
Is this a bug in the tests or a bug in kubernetes itself? I see it's caused several tests to start failing.

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:125
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../cluster/../platforms/linux/amd64/kubectl [kubectl --server=https://104.197.87.130 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config stop -f examples/guestbook] []  <nil>  Error: [Resizing the controller failed with: replicationControllers "frontend" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-master" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-slave" not found; Current resource version Unknown]
[] <nil> 0xc208845480 exit status 1 <nil> true [0xc2089a0190 0xc2089a01b0 0xc2089a01d0] [0xc2089a0190 0xc2089a01b0 0xc2089a01d0] [0xc2089a01a8 0xc2089a01c8] [0x657730 0x657730] 0xc208a69320}:
Command stdout:

stderr:
Error: [Resizing the controller failed with: replicationControllers "frontend" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-master" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-slave" not found; Current resource version Unknown]
```

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:80
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../cluster/../platforms/linux/amd64/kubectl [kubectl --server=https://104.197.87.130 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config stop -f examples/update-demo/nautilus-rc.yaml] []  <nil>  Error: Resizing the controller failed with: replicationControllers "update-demo-nautilus" not found; Current resource version Unknown
[] <nil> 0xc2089d21a0 exit status 1 <nil> true [0xc2082b0670 0xc2082b0690 0xc2082b06c0] [0xc2082b0670 0xc2082b0690 0xc2082b06c0] [0xc2082b0688 0xc2082b06a8] [0x657730 0x657730] 0xc2089b5920}:
Command stdout:

stderr:
Error: Resizing the controller failed with: replicationControllers "update-demo-nautilus" not found; Current resource version Unknown
```

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:94
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../cluster/../platforms/linux/amd64/kubectl [kubectl --server=https://104.197.87.130 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config stop -f examples/update-demo/nautilus-rc.yaml] []  <nil>  Error: Resizing the controller failed with: replicationControllers "update-demo-nautilus" not found; Current resource version Unknown
[] <nil> 0xc208a2f0a0 exit status 1 <nil> true [0xc20803ac68 0xc20803ac88 0xc20803acb0] [0xc20803ac68 0xc20803ac88 0xc20803acb0] [0xc20803ac80 0xc20803aca8] [0x657730 0x657730] 0xc208c89200}:
Command stdout:

stderr:
Error: Resizing the controller failed with: replicationControllers "update-demo-nautilus" not found; Current resource version Unknown
```

**Comment by ixdy** [comment]
I think I might know what's wrong. Opening an issue now.

**Pull request merged**
