### PR TITLE
Fix wrong tail -f command

### PR DESCRIPTION
**Pull request by resouer**
Minor fix. The original command `tailf` is wrong.

### CODE REVIEW

**Comment by ashcrow** [comment]
Very small documentation fix. Looks good. Does not require build tests.

cc @thockin

**Comment by wojtek-t** [comment]
@resouer - it seems there are some problems with Shippable - can you please rebase your PR - I think this should fix the problem

**Comment by ashcrow** [comment]
@wojtek-t I've been seeing this shippable error in a few PRs. Is this something that was fixed in code or is it a problem with shippable itself?

**Comment by wojtek-t** [comment]
@ashcrow - I think I've seen some PR fixing it

**Pull request merged**
