### PR TITLE
Rkt gc

### PR DESCRIPTION
**Pull request by yifan-gu**
@vmarmol @dchen1107 @jonboulle @bakins

The first commit is from #7465

### CODE REVIEW

**Comment by jonboulle** [comment]
@yifan-gu I guess this is anticipating a follow up? otherwise seems like a timer unit would do for now - https://github.com/coreos/rkt/blob/master/dist/init/systemd/rkt-gc.timer

**Comment by yifan-gu** [comment]
@jonboulle kubelet has a loop for GarbageCollection, so we only need to implement one shot here.

**Comment by yifan-gu** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L563

Though I like the systemd timer ;) @jonboulle

**Comment by jonboulle** [comment]
ok, thanks!

**Comment by vmarmol** [comment]
+1 to keeping the frequency in control by the Kubelet. With time we'll want to customize the policy as well.

Looks good overall.

**Comment by yifan-gu** [comment]
`MinAge` has slightly different means to `grace-period`, where `MinAge` starts from the stop of the container while `grace-period` starts from the trigger of the gc.
I added a TODO to think about it later :)
Rebased, and changed rkt_gc.go to gc.go
@vmarmol

**Comment by vmarmol** [comment]
I'm fine with the change in general, but I wanted to clarify how the GC policy currently used works. I was leaning towards no GC in rkt initially until we can re-create a policy like the ones we have today. We do depend on old containers for status and that'd be good to keep.

From my reading of the rkt help `grace-period` was also from the stop of the container since it is when it became "unused". How does it work if it is defined from the start of the GC operation?

Maybe I'm missing something :)

**Comment by yifan-gu** [comment]
@vmarmol In rkt, when gc is called, the container will be moved to gc directory, the ctime is changed at that time, so it's computed from that time. We don't actually know when the container stops now

/cc @jonboulle @vcaputo

**Comment by vmarmol** [comment]
Aaaah thank you for walking me through that @yifan-gu :) We can probably still use MinAge and the behavior will be that at least MinAge will be used. Fine for a followup.

LGTM

**Pull request merged**
