### PR TITLE
Fix windows kubelet startup

### LINKED ISSUE #93262: Kueblet fails to start due to device plugin manager on windows
**What happened**:
The pr https://github.com/kubernetes/kubernetes/pull/80917 introduced device manager for windows.   We are seeing test failures since the PR was merged:

The tests have no windows nodes coming online.  From https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1285006290715676672:

```
2020/07/20 00:55:29 e2e.go:474: Cluster nodes:
k8s-master-26157211-0   Ready   master   3m11s   v1.20.0-alpha.0.249+6ceb6c6845348e
```
When looking at the kubelet logs the error is 

```
I0720 19:24:36.710427    4332 manager.go:132] Creating Device Plugin manager at /var/lib/kubelet/device-plugins/kubelet.sock
F0720 19:24:36.710427    4332 server.go:265] failed to run Kubelet: bad socketPath, must be an absolute path: /var/lib/kubelet/device-plugins/kubelet.sock
```

**What you expected to happen**:
The kubelet mounts the device manager via a namedpipe not a unix socket.

**How to reproduce it (as minimally and precisely as possible)**:
use a build from the main branch.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.0-alpha.0.234+a789d56b65d352
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #

* Reverts https://github.com/kubernetes/kubernetes/pull/80917
* Includes https://github.com/kubernetes/kubernetes/pull/93063
* Fixes https://github.com/kubernetes/kubernetes/issues/93262

**Does this PR introduce a user-facing change?**:
```release-note
Reverted devicemanager for Windows node added in 1.19rc1.
```

/sig windows

### CODE REVIEW

**Comment by aarnaud** [comment]
the device-plugins manager works on windows 1.16 to 1.18 , the change in tbe PR was to let Go convert path for windows. maybe you need to create device-plugins directory before start kubelet ?

**Comment by liggitt** [comment]
pull-kubernetes-e2e-azure-file-windows passed - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93263/pull-kubernetes-e2e-azure-file-windows/1285307624048300033

**Comment by liggitt** [comment]
pull-kubernetes-e2e-azure-disk-windows passed - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93263/pull-kubernetes-e2e-azure-disk-windows/1285307624023134209

**Review by michmike — APPROVED** [review]
/lgtm
/approve 

thanks Jordan for taking care of this!

**Pull request merged**
