### PR TITLE
Validation cleanup part 3

### PR DESCRIPTION
**Pull request by thockin**
Part 3 of several, builds on #17246

Use types for better tracking of validation errors.

@lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by lavalamp** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot unut test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@thockin - can you please rebase?

**Comment by wojtek-t** [comment]
It seems that it somehow doesn't need rebase anymore.

@k8s-bot e2e test this please

**Pull request merged**
