### PR TITLE
Allow SecurityContext in GCE

### PR DESCRIPTION
**Pull request by pmorie**
...depends on #16701.

@ArtfulCoder

### CODE REVIEW

**Comment by pmorie** [comment]
@kubernetes/goog-testing PTAL

**Comment by pmorie** [comment]
@vishh Maybe I can bug you about this one since we're sitting at the same table RIGHT NOW

**Comment by pmorie** [comment]
I have tested in GCE with the current SecurityContext E2Es that I expect to work.

**Comment by vishh** [comment]
LGTM. Thanks @pmorie!

**Comment by ixdy** [comment]
this should not have been merged, as #16701 was not LG'd.

**Pull request merged**
