### PR TITLE
Release 0.21.2

### PR DESCRIPTION
**Pull request by zmerlynn**
Branch contains:
- #11084

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @thockin (yay, confimed doc stuff fixed)
cc @roberthbailey @alex-mohr for LGTM

**Comment by thockin** [comment]
This does not seem to include docs/README and examples/README ?

**Comment by zmerlynn** [comment]
@thockin: You intentionally didn't send that PR on `release-0.21`?

**Comment by zmerlynn** [comment]
(This branch also contains a bunch of doc fixes. I didn't include them in the description because they're probably not going in the release notes.)

**Comment by thockin** [comment]
oh, because I opted not to CP that into 0.21

**Comment by thockin** [comment]
LGTM

**Comment by zmerlynn** [comment]
This isn't ready, give me a sec.

**Comment by zmerlynn** [comment]
Tag shifted but otherwise same. SLAMMING.

**Pull request merged**
