### PR TITLE
CKA Ref

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Removed

### CODE REVIEW

**Comment by nsvijay04b1** [comment]
> ### kubectl shortcuts
> ```shell
> cat << EOF >> .bashrc
> ########## Kubernetes alias - start ##########
> alias k='kubectl'
> 
> alias ke='k edit'
> 
> alias kd='k describe'
> 
> alias ka='k apply'
> alias kaf='ka -f'
> 
> alias kdl='k delete'
> alias kdlf='kdl -f'
> 
> alias kg='k get'
> alias kga='kg all'
> alias kgs='kg svc'
> alias kgp='kg pods'
> alias kgn='kg nodes'
> alias kgd='kg deploy'
> alias kgc='kg componentstatuses'
> 
> alias kc='k config'
> alias kcg='kc get-contexts'
> alias kcu='kc use-context'
> alias kcc='kc current-context'
> ########## Kubernetes alias - end ##########
> EOF
> ```
> 
> ### tmux config
> ```shell
> cat << EOF > .tmux.conf
> # Send prefix
> set-option -g prefix C-a
> unbind-key C-a
> bind-key C-a send-prefix
> 
> # Use Alt-arrow keys to switch panes
> bind -n M-Left select-pane -L
> bind -n M-Right select-pane -R
> bind -n M-Up select-pane -U
> bind -n M-Down select-pane -D
> 
> # Shift arrow to switch windows
> bind -n S-Left previous-window
> bind -n S-Right next-window
> 
> # Mouse mode
> setw -g mouse on
> 
> # Set easier window split keys
> bind-key v split-window -h
> bind-key h split-window -v
> 
> # Easy config reload
> bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."
> EOF
> ```
> 
> # kubernetes-bookmarks
> Resource	Link
> Kubernetes Docs	https://kubernetes.io/docs/home/
> Kubectl Reference Docs	https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
> Kubectl Cheat Sheet	https://kubernetes.io/docs/reference/kubectl/cheatsheet/
> Kubectl Overview	https://kubernetes.io/docs/reference/kubectl/overview/
> Kubectl - Overview	https://kubernetes.io/docs/reference/kubectl/overview/#custom-columns%5D,
> View Find Resources	https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources
> JSONPath	https://kubernetes.io/docs/reference/kubectl/jsonpath/
> Generators	https://kubernetes.io/docs/reference/kubectl/conventions/#generators
> busybox	https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates
> PORTS	https://kubernetes.io/blog/2020/02/07/deploying-external-openstack-cloud-provider-with-kubeadm/
> Taints and Tolerations	https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
> Assigning Pods to Nodes	https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
> Labels and Selectors	https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
> Security Context for a Pod or Container	https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
> Init Containers + busybox	https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
> Liveness Readiness and Startup Probes	https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
> Environment Variables	https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
> Command and Arguments	https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
> Inject Data Into Applications	https://kubernetes.io/docs/tasks/inject-data-application/
> StaticPods	https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/
> Secrets	https://kubernetes.io/docs/concepts/configuration/secret/
> Create TLS secret	https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-tls-em-
> Credentials Securely using Secrets	https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
> ConfigMaps	https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
> Images	https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry
> Image from a Private Registry	https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
> Resource Quotas	https://kubernetes.io/docs/concepts/policy/resource-quotas/
> Limit Ranges	https://kubernetes.io/docs/concepts/policy/limit-range/
> Requests and Limits	https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
> Services	https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
> Services Examples + TLS secret example	https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#creating-a-service
> DaemonSet	https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
> Deployments	https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
> Jobs	https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
> CronJobs	https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
> CronJobs example	https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
> Network Policies	https://kubernetes.io/docs/concepts/services-networking/network-policies/
> Ingress Controller	https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
> Ingress Examples	https://kubernetes.io/fr/docs/concepts/services-networking/ingress/
> RBAC	https://kubernetes.io/docs/reference/access-authn-authz/rbac/
> Service Accounts	https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
> Certificates	https://kubernetes.io/docs/concepts/cluster-administration/certificates/
> Certificate Management with kubeadm	https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/
> Certificates paths and requirements	https://kubernetes.io/docs/setup/best-practices/certificates/
> Certificate Signing Request	https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request-object-to-send-to-the-kubernetes-api
> TLS bootstrapping - Kubernetes	https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/
> Volumes	https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
> Volumes - hostPath	https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
> Volumes - emptyDir	https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
> Persistent Volumes	https://kubernetes.io/docs/concepts/storage/persistent-volumes/
> Persistent Volumes Claims	https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
> Persistent Volume, Claim, Pod - Example	https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
> Configure Multiple Schedulers	https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
> ETCD	https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
> Kubernetes versioning	https://kubernetes.io/docs/setup/release/version-skew-policy/
> Install kubectl, kube-apiserver, kube-scheduler, etc..	https://kubernetes.io/docs/tasks/tools/install-kubectl/
> Installing kubeadm, kubeclt, kubelet	https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
> Single master cluster with kubeadm	https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
> Upgrading kubeadm clusters	https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
> Nodes	https://kubernetes.io/docs/concepts/architecture/nodes/
> Pod Security Policies	https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privileged
> Debugging DNS Resolution	https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

tmux conf is not working...  can you use this instead?
************************************************
cat << EOF > .tmux.conf
# 0 is too far from ` ;)
# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

#set -g default-terminal screen-256color
set -g status-keys vi
set -g history-limit 10000

setw -g mode-keys vi
setw -g mode-mouse on
setw -g monitor-activity on

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.tmux.conf

# THEME
set -g status-bg black
set -g status-fg white
set -g window-status-current-bg white
set -g window-status-current-fg black
set -g window-status-current-attr bold
set -g status-interval 60
set -g status-left-length 30
set -g status-left '#[fg=green](#S) #(whoami)'
set -g status-right '#[fg=yellow]#(cut -d " " -f 1-3 /proc/loadavg)#[default] #[fg=white]%H:%M#[default]'

#synchronize-panes
bind-key x set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"
EOF
************************************************

**Comment by nsvijay04b1** [comment]
useful kubectl aliases

```
cat << EOF >> .bashrc
########## Kubernetes alias - start ##########
alias k='kubectl'
source <(kubectl completion bash) 
source <(kubectl completion bash|sed "s/kubectl/k/g")

alias kd='k describe '
alias kdp='k describe pod '
alias kdd='k describe deploy '
alias kds='k describe svc '

alias kg='k get '
alias kgp='k get pod '
alias kgd='k get deploy '
alias kgs='k get svc '
alias kgn='k get no '

alias ke='k edit '
alias ka='k apply -f '
alias kc='k create '

alias kdl='k delete --force '
alias kdlf='k delete --force -f '

alias kl='k logs '

alias kcv='k config view '
alias kgc='k config get-contexts '
alias kcc='k config current-context '
alias ksn='k config set-context  --current ' 
alias kuc='k config use-context '
alias ksc='k config set-context '
export do="--dry-run=client -oyaml"
########## Kubernetes alias - end ##########
EOF
```

**Comment by nsvijay04b1** [comment]
```
### **Tips**
# set the labels and selector before creating a deployment/service pair.
kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run=client | kubectl set  selector --local -f 'environment=qa' -o yaml | kubectl create -f - 

kubectl create deployment my-dep -o yaml --dry-run=client | kubectl label --local -f -  environment=qa -o yaml | kubectl create -f -

#List users in kube conbfig
kubectl config view -o jsonpath='{range .users[*]}{.name}{"\n"}{end}'

#List all pods that are Running
kubectl get pods --field-selector=status.phase=Running

#Display all the resources in the namespace
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind 2>/dev/null 


#override spec like imagePullSecrets
kubectl run hello --restart=Never --image=nginx  --overrides='{ "apiVersion": "v1", "spec": { "imagePullSecrets": [{"name": "your-registry-secret"}] } }' --dry-run=client -oyaml

#patch a deployment with port
kubectl  patch deployments  apple -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx","ports":[{"protocol":"TCP","containerPort":80,"name":"nginxport"}]}]}}}}'


###  **systemctl** 
sudo systemctl list-unit-files --type service --all | grep -v enabled
sudo systemctl list-unit-files --type service --all | grep -v running
sudo systemctl cat nginx.service  # To see the full contents of a unit file
sudo systemctl show nginx.service #see the low-level details of the unit’s settings on the system
sudo systemctl edit nginx.service #add a unit file snippet  to append or override settings in the default unit file
sudo systemctl edit --full nginx.service #modify the entire content of the unit file
```

**Comment by sgrzebieta** [comment]
# Kubernetes Bookmarks

## 01 - General

[ETCD Manager](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd)

[KUBELET - Service management](https://v1-14.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/)

[KUBECTL - Cheat Sheet](https://v1-14.docs.kubernetes.io/docs/reference/kubectl/cheatsheet/)

[KUBECTL - Help](https://v1-14.docs.kubernetes.io/docs/reference/kubectl/overview/)

[DNS for Services and Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records-1)

[kubectl Generators](https://v1-14.docs.kubernetes.io/docs/reference/kubectl/conventions/#generators)

[Get a Shell to a Running Container - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/)

[Annotations - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)

[Labels and Selectors - Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

## 02 - Nodes

[Safely Drain a Node while Respecting Application SLOs - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)

[Taints and Tolerations - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/taint-and-toleration/)

## 03 - Pods

[Configure Liveness and Readiness Probes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)

[Assign CPU Resources to Containers and Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/)

[Command and Arguments](https://v1-14.docs.kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#run-a-command-in-a-shell)

[Define Environment Variables for a Container - Kubernetes](https://v1-14.docs./kuberneteskubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)

[Configure a Security Context for a Pod or Container - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)

[Init Containers - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/pods/init-containers/)

[Configure Pod Initialization - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/)

[Multi Container Pods](https://v1-14.docs.kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/)

[Pod Overview - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates)

[NodeSelector - Assigning Pods to Nodes](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)

[Static Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/static-pod/)

[Horizontal Pod Autoscaler Walkthrough - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)

[Advanced Scheduling in Kubernetes - Kubernetes](https://v1-14.docs.kubernetes.io/blog/2017/03/advanced-scheduling-in-kubernetes/)

[Determine the Reason for Pod Failure - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#writing-and-reading-a-termination-message)

[Define Environment Variables for a Container - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)

[Expose Pod Information to Containers Through Files - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#store-pod-fields)

[Assigning Pods to Nodes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinit)

[DNS for Services and Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields)

## 04 - Deployments

[Run a Stateless Application Using a Deployment - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/)

[Deployments - RollingUpdates](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)

## 05 - Services

[Services - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/service/)

[Exposing an External IP Address to Access an Application in a Cluster - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/)

[Use Port Forwarding to Access Applications in a Cluster - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)

## 06 - ConfigMaps

[Configure a Pod to Use a ConfigMap - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)

[Configure a Pod to Use a ConfigMap - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)

[Configure a Pod to Use a ConfigMap - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files)

## 07 - Secrets

[Secrets - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/secret/)

[Secrets - Kubernetes - Use Case](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/secret/#use-cases)

## 08 - ServiceAccounts

[Managing Service Accounts - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/)

[Configure Service Accounts for Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/)

## 09 - Cronjobs

[Running Automated Tasks with a CronJob - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/)

## 10 - PersistentVolumes

[Persistent Volumes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes)

[Persistent Volumes Caims - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)

[Storage Classes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk)

[Configure a Pod to Use a PersistentVolume for Storage - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolumeclaim)

[Volumes - Kubernetes - EmptyDir](https://v1-14.docs.kubernetes.io/docs/concepts/storage/volumes/#emptydir)

[Limit Storage Consumption - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/)

[Hostpath Persistent Volume](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)

## 11 - Network Policy

[Network Policies - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/network-policies/)

[Declare Network Policy - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/)

## 12 - Logs

[Cluster Level Logging with Kubernetes - Kubernetes](https://v1-14.docs.kubernetes.io/blog/2015/06/cluster-level-logging-with-kubernetes/)

[Logging Architecture - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/cluster-administration/logging/)

[Troubleshoot Clusters - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/#looking-at-logs)

## 13 - Jobs

[Jobs - Run to Completion - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#advanced-usage)

[Jobs - Run to Completion - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)

[Parallel Processing using Expansions - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/job/parallel-processing-expansion/)

## 14 - CustomSchedulers

[Configure Multiple Schedulers - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/)

## 15 - Ingress

[Ingress - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/ingress/)

## 16 - LoadBalancer

[Create an External Load Balancer - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/)

## 17 - DaemonSets

[DaemonSet - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/controllers/daemonset/#writing-a-daemonset-spec)

[Perform a Rollback on a DaemonSet - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/manage-daemon/rollback-daemon-set/)

## 18 - RBAC

[Using RBAC Authorization - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/access-authn-authz/rbac/)

## 19 - Images

[Pull an Image from a Private Registry - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

## 20 - Troubleshooting

[Debug Services - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/debug-application-cluster/debug-service/)

[Debugging DNS Resolution - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)

[Troubleshoot Clusters - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/)

## 21 - DNS

[DNS for Services and Pods - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

[Customizing DNS Service - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/)

[Debugging DNS Resolution - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)

[Configuring Private DNS Zones and Upstream Nameservers in Kubernetes - Kubernetes](https://v1-14.docs.kubernetes.io/blog/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes/)

[Customizing DNS Service - Kubernetes - StubDomain](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers)

[DNS for Services and Pods - Kubernetes - Pods](https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods)

[DNS for Services and Pods - FQDN](https://v1-13.docs.kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

## 22 - Install and Config

[Certificates - Kubernetes](https://v1-14.docs.kubernetes.io/docs/concepts/cluster-administration/certificates/)

[Overview of kubectl - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/kubectl/overview/)

[Certificate Rotation - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/tls/certificate-rotation/)

[Install and Set Up kubectl - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/tools/install-kubectl/)

[Encrypting Secret Data at Rest - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/encrypt-data/)

[v1.13 Release Notes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/setup/release/notes/)

[TLS bootstrapping - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#token-authentication-file)

[Operating etcd clusters for Kubernetes - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/)

## Bootstrap

[TLS bootstrapping - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#bootstrap-tokens)

[Authenticating with Bootstrap Tokens - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#configmap-signing)

[Authenticating - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/access-authn-authz/authentication/#bootstrap-tokens)

[TLS bootstrapping - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#authorize-kubelet-to-create-csr)

[TLS bootstrapping - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#approval)

[Authenticating with Bootstrap Tokens - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#bootstrap-token-secret-format)

[TLS bootstrapping - Kubernetes](https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#kubelet-configuration)

[PKI certificates and requirements - Kubernetes](https://v1-14.docs.kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts)

[Configure a Pod to Use a ConfigMap - Kubernetes](https://v1-14.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories)

[Configuring each kubelet in your cluster using kubeadm - Kubernetes](https://v1-14.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd)

[Kubernetes Components - Kubernetes](https://kubernetes.io/docs/concepts/overview/components/)

## Node

[Install and Set Up kubectl - Kubernetes](https://kubernetes.io/docs/tasks/tools/install-kubectl/)

[Releases · kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/releases)

## Multicontainer Patterns

[Logging - sidecar](https://kubernetes.io/docs/concepts/cluster-administration/logging/#using-a-sidecar-container-with-the-logging-agent)

[Communicate Between Containers in the Same Pod Using a Shared Volume - Kubernetes](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/)

[The Distributed System ToolKit: Patterns for Composite Containers - Kubernetes](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/)

**Comment by sgrzebieta** [comment]
`kubectl get endpoints front-end-service -o=jsonpath='{.subsets[*].addresses[*].ip}' | tr ' ' '\n' | xargs -I % kubectl get pods --field-selector=status.podIP=%`

**Comment by sgrzebieta** [comment]
1. Generate the certificate key

`kubeadm alpha certs certificate-key`

2. Print the join command

`kubeadm token create --print-join-command`

3. Add the following flags to the above join command

`--control-plane --certificate-key "Certificate-key from step 1"`

4. Command should look like below

`sudo kubeadm join 192.168.0.200:6443 --token 9vr73a.a8uxyaju799qwdjv --discovery-token-ca-cert-hash sha256:7c2e69131a36ae2a042a339b33381c6d0d43887e2de83720eff5359e26aec866 --control-plane --certificate-key f8902e114ef118304e561c3ecd4d0b543adc226b7a07f675f56564185ffe0c07`

**Comment by chaosaffe** [comment]
@kubernetes/community-admins 
This PR is designed to allow people to circumvent rules put in place for the CKA and CKAD exams, and while it may not technically be a form of cheating it certainly doesn't follow with the CoC for the Kubernetes community. 

I would request that this PR, and any like it that are identified be removed for public consumption, and that anyone who participated in this thread have their CKA or CKAD re-examined to ensure validity and consistency of both those certifications.

To anyone who has participated in this thread:
I would ask you to review the Kubernetes community [Code of Conduct], specifically considering unprofessional and unethical behavior. The Linux Foundation Kubernetes Certifications are _hard_, and they are so for a reason. People like myself consider achieving those certifications a badge of honor and recognition of the years of hard work we have put in to learning and understanding how to deploy, operate and leverage Kubernetes. You have done yourself, and the community, a true disservice by choosing to circumvent the examinations rather than dedicate yourself to understanding the concepts and learning the skills required to complete these certifications.

**Pull request closed without merging**
