### PR TITLE
e2e: remove unused method in e2e/framework/log

### PR DESCRIPTION
**Pull request by haosdent**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove unused method in e2e/framework/log

**Which issue(s) this PR fixes**:
Ref #86052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
interesting, I'd like to see the result.

/ok-to-test
/cc @oomichi

**Review by alejandrox1 — COMMENTED** [review]
Thank you for catching this @haosdent !
/approve
/priority backlog
/milestone v1.18

**Pull request merged**
