### PR TITLE
Improve codes which checks whether sandbox contains containers

### PR DESCRIPTION
**Pull request by FengyunPan**
Currently evictSandboxes() checks whether sandbox contains
containers, it traverses all the containers for every sandbox,
but when cluster has many containres, it wastes a lot of time.
It is better to use sets in this case.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by dashpole** [comment]
Generally, we don't optimize unless we can measure performance increases, but I think this also makes the code cleaner, and easier to understand as well.
/lgtm

**Pull request merged**
