### PR TITLE
Remove 1.2.* release notes in CHANGELOG.md

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Remove 1.2.* release notes in CHANGELOG.md to make the file smaller so its content can be shown.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: https://github.com/kubernetes/kubernetes/issues/48985#issuecomment-328076817

**Special notes for your reviewer**:
This is just a quick fix before we have an ideal solution of #48985 
/cc @jdumars 
/priority important-soon
/sig release

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @david-mcmahon

**Comment by david-mcmahon** [comment]
Why not move these into CHANGELOG-1.2.md rather than deleting altogether?

**Comment by dchen1107** [comment]
Before we have a systematic solution to address #48985, how about creating a separate CHANGELOG-1.2.md file, and move all related content over, instead of completely removing 1.2.* release notes? 

cc/ @kubernetes/sig-release-members

**Comment by dchen1107** [comment]
@david-mcmahon Just saw we made the same suggestion separately here. :-)

**Comment by xiangpengzhao** [comment]
@david-mcmahon @dchen1107 I was thinking there was another place where some old changelog had already been kept when I saw the last sentence(`Please see the Releases Page for older releases.`) of CHANGELOG.md :)

Will move 1.2 changelog to a separate file.

**Comment by xiangpengzhao** [comment]
/hold
TOC needs update

**Comment by xiangpengzhao** [comment]
TOC updated. PTAL. @david-mcmahon @dchen1107 

/hold cancel

**Comment by xiangpengzhao** [comment]
FYI: update TOC by [this script](https://gist.github.com/xiangpengzhao/a1d191eb1220dc1a19f92d4a33c09b6b) which is derived from https://github.com/kubernetes/release/blob/master/lib/common.sh

**Comment by abitrolly** [comment]
Something wrong with milestone.

**Pull request merged**
