### PR TITLE
Automated cherry pick of #14827 #14302 upstream release 1.1

### PR DESCRIPTION
**Pull request by timstclair**
Fixes https://github.com/kubernetes/kubernetes/issues/14159

### CODE REVIEW

**Comment by lavalamp** [comment]
Is there an issue to go with this cherry-pick? (adding a link to an existing issue that this addresses is fine, otherwise create one.) LGTM otherwise.

**Comment by timstclair** [comment]
Updated description, but this is picking the fixes for https://github.com/kubernetes/kubernetes/issues/14159

**Comment by timstclair** [comment]
cc/ @thockin who asked for the cherry pick

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
