### PR TITLE
Remove 1.10-deprecated flags that map to KubeletConfiguration

### PR DESCRIPTION
**Pull request by mtaufen**
This PR removes 1.10-deprecated flags that map to the KubeletConfiguration
type. There are still some newer flags (legacy from flag->config migrations),
which should be removed in 1.13.

```release-note
The following flags, deprecated in v1.10, are removed in v1.12.
These values can still be set via the Kubelet config file (https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/).
Remember to check the config file defaults when migrating, as some differ from flags.
-------------------------------------------------------------------------------------------
Kubelet flag name                              | KubeletConfiguration field
-------------------------------------------------------------------------------------------
--fail-swap-on                                 | failSwapOn
--experimental-fail-swap-on                    | failSwapOn
--pod-manifest-path                            | staticPodPath
--sync-frequency                               | syncFrequency
--file-check-frequency                         | fileCheckFrequency
--http-check-frequency                         | httpCheckFrequency
--manifest-url                                 | staticPodURL
--manifest-url-header                          | staticPodURLHeader
--address                                      | address
--port                                         | port
--read-only-port                               | readOnlyPort
--anonymous-auth                               | authentication.anonymous.enabled
--authentication-token-webhook                 | authentication.webhook.enabled
--authentication-token-webhook-cache-ttl       | authentication.webhook.cacheTTL
--client-ca-file                               | authentication.x509.clientCAFile
--authorization-mode                           | authorization.mode
--authorization-webhook-cache-authorized-ttl   | authorization.webhook.cacheAuthorizedTTL
--authorization-webhook-cache-unauthorized-ttl | authorization.webhook.cacheUnauthorizedTTL
--tls-cert-file                                | tlsCertFile
--tls-private-key-file                         | tlsPrivateKeyFile
--tls-cipher-suites                            | tlsCipherSuites
--tls-min-version                              | tlsMinVersion
--registry-qps                                 | registryPullQPS
--registry-burst                               | registryBurst
--event-qps                                    | eventRecordQPS
--event-burst                                  | eventBurst
--enable-debugging-handlers                    | enableDebuggingHandlers
--contention-profiling                         | enableContentionProfiling
--healthz-port                                 | healthzPort
--healthz-bind-address                         | healthzBindAddress
--oom-score-adj                                | oomScoreAdj
--cluster-domain                               | clusterDomain
--cluster-dns                                  | clusterDNS
--streaming-connection-idle-timeout            | streamingConnectionIdleTimeout
--node-status-update-frequency                 | nodeStatusUpdateFrequency
--minimum-image-ttl-duration                   | imageMinimumGCAge
--image-gc-high-threshold                      | imageGCHighThresholdPercent
--image-gc-low-threshold                       | imageGCLowThresholdPercent
--volume-stats-agg-period                      | volumeStatsAggPeriod
--feature-gates                                | featureGates
--kubelet-cgroups                              | kubeletCgroups
--system-cgroups                               | systemCgroups
--cgroups-per-qos                              | cgroupsPerQOS
--cgroup-driver                                | cgroupDriver
--cgroup-root                                  | cgroupRoot
--cpu-manager-policy                           | cpuManagerPolicy
--cpu-manager-reconcile-period                 | cpuManagerReconcilePeriod
--runtime-request-timeout                      | runtimeRequestTimeout
--hairpin-mode                                 | hairpinMode
--max-pods                                     | maxPods
--pod-cidr                                     | podCIDR
--pod-max-pids                                 | podPidsLimit
--resolv-conf                                  | resolverConfig
--cpu-cfs-quota                                | cpuCFSQuota
--enable-controller-attach-detach              | enableControllerAttachDetach
--make-iptables-util-chains                    | makeIPTablesUtilChains
--iptables-masquerade-bit                      | iptablesMasqueradeBit
--iptables-drop-bit                            | iptablesDropBit
--container-log-max-size                       | containerLogMaxSize
--container-log-max-files                      | containerLogMaxFiles
--max-open-files                               | maxOpenFiles
--kube-api-content-type                        | contentType
--kube-api-qps                                 | kubeAPIQPS
--kube-api-burst                               | kubeAPIBurst
--serialize-image-pulls                        | serializeImagePulls
--eviction-hard                                | evictionHard
--eviction-soft                                | evictionSoft
--eviction-soft-grace-period                   | evictionSoftGracePeriod
--eviction-pressure-transition-period          | evictionPressureTransitionPeriod
--eviction-max-pod-grace-period                | evictionMaxPodGracePeriod
--eviction-minimum-reclaim                     | evictionMinimumReclaim
--pods-per-core                                | podsPerCore
--protect-kernel-defaults                      | protectKernelDefaults
--system-reserved                              | systemReserved
--kube-reserved                                | kubeReserved
--enforce-node-allocatable                     | enforceNodeAllocatable
--system-reserved-cgroup                       | systemReservedCgroup
--kube-reserved-cgroup                         | kubeReservedCgroup
```

### CODE REVIEW

**Comment by liggitt** [comment]
should kubelet configuration reach v1 before removal of the GA flags?

**Comment by smarterclayton** [comment]
Yes

**Comment by mtaufen** [comment]
It's not that simple IMO. The deprecation policy for a beta componentconfig API is more conservative than the deprecation policy for a GA CLI element of an admin-facing component. `max(9 months, 3 releases)` vs `max(6 months, 1 release)`. So the beta componentconfig API would already have greater stability, which probably satisfies whatever implicit analogue to rule 3 applies to CLI elements.

>Rule #3: An API version in a given track may not be deprecated until a new API version at least as stable is released.

Kubelet componentconfig API (same policy as regular APIs):
>Rule #4a: Other than the most recent API versions in each track, older API versions must be supported after their announced deprecation for a duration of no less than:
>
>GA: 12 months or 3 releases (whichever is longer)
>Beta: 9 months or 3 releases (whichever is longer)
>Alpha: 0 releases

Kubelet CLI:
>Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:
>
>GA: 6 months or 1 release (whichever is longer)
>Beta: 3 months or 1 release (whichever is longer)
>Alpha: 0 releases

https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Comment by mtaufen** [comment]
We can revisit this in the future, but closing for now.

**Pull request closed without merging**
