### PR TITLE
Add missing LICENSE/README/NOTICE files to Godeps tree.

### PR DESCRIPTION
**Pull request by david-mcmahon**
In preparation for new LICENSE generation tool.
These files were generated by the tool.

### CODE REVIEW

**Comment by zmerlynn** [comment]
@david-mcmahon: Travis thinks you're in pre-commit hell. Did you verify that you could commit this without #22116? I was assuming you could commit these, then #22116 and it would be fine, but it looks like the changes to the Godeps dir are getting rejected.

**Comment by david-mcmahon** [comment]
Travis sez (twice now):
https://travis-ci.org/kubernetes/kubernetes/builds/112176443#L364

ERROR: exit status 128
`git ls-tree -r --name-only upstream/release-1.1 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
output: fatal: Not a valid object name upstream/release-1.1

Not sure what the problem is exactly.

**Comment by david-mcmahon** [comment]
@ixdy says we can ignore this travis check, so lgtm away!

**Comment by ixdy** [comment]
er, that's not what I said.

You linked output from the `hack/verify-generated-docs.sh` check, which I think will fail on Travis due to #18047, but this won't fail the build.

What's more worrying is that `hack/verify-godeps.sh` is *actually* failing. We don't run this check on Jenkins for ?reasons?, which is why it isn't failing there.

**Comment by bgrant0607** [comment]
It would be useful to just all the checks as part of the test script rather than as separate lines in the travis config.

**Comment by bgrant0607** [comment]
Users fail to run these all the time.

**Comment by ixdy** [comment]
@bgrant0607 that's what `hack/verify-all.sh` does in theory, though a number of the verification checks are excluded there for unclear reasons (incl. the godeps check).

Jenkins runs `hack/verify-all.sh` because I didn't want to have to keep updating the config as new checks were added.

**Comment by zmerlynn** [comment]
@david-mcmahon: I can confirm the `hack/verify-godeps.sh` failure manually. The problem is that the godep tree is completely autogenerated by the `godeps` tool (which I should've thought about), and `verify-godeps.sh` is checking that. I think you need to create a parallel directory other than `_workspace` and check *that* as well in order to proceed.

**Comment by david-mcmahon** [comment]
Yes, i had been updating the other PR #22116 this morning to deal with this fact.
I'm abandoning this PR.

**Pull request closed without merging**
