### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by majst01**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix spelling of InstanceMetadata in cloud-provider.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note
Fix documentation typo in cloud-provider
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @cheftako @andrewsykim 

NOTE: Walter, Andrew, quick/easy/small PR. please take a look

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Comment by jberkus** [comment]
This change does not require a release note.

**Pull request merged**
