### PR TITLE
Enable “Kubernetes Monitoring” and “PodSecurityPolicies” on the same cluster

### PR DESCRIPTION
**Pull request by davidebelloni**
Without that the daemonset "metadata-agent" return:

```pods "metadata-agent-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 8799: Host port 8799 is not allowed to be used. Allowed ports: []]```

```release-note
NONE
```

### CODE REVIEW

**Comment by davidebelloni** [comment]
Hi @kawych and @piosz ,
I'm new to this workflow. Can you explain me where is blocked this PR?

Thanks!

**Comment by idealhack** [comment]
@davidebelloni Thanks for your work. As the robot said, instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md).

/ok-to-test

**Comment by davidebelloni** [comment]
@idealhack thanks for the reply and sorry for missing the link!

**Comment by kawych** [comment]
@davidebelloni Can you please clarify what environment did you test it on? GCE? GKE? It seems that on GCE, the startups scripts don't create cluster role that you're using, unless ENABLE_POD_SECURITY_POLICY is set.

**Comment by kawych** [comment]
I think that you need to move this role binding under a podsecuritypolicies/ subdirectory. If pod security policies are disabled, the cluster role you are using doesn't exist (this is the default setting on GCE).

This function sets up manifests: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L2027
Note that it relies on pod security policy being under podsecuritypolicies/ subdirectory.

**Comment by kawych** [comment]
@davidebelloni I agree, your change is unlikely to affect these jobs. Some tests are very flaky, they should pass at some point.

**Pull request merged**
