### PR TITLE
Create CoreDNS and kube-dns folders

### LINKED ISSUE #61435: coredns manifest appears in the addons folder on master when it is diabled
**Is this a BUG REPORT or FEATURE REQUEST?**:
/king bug
/sig network

**What happened**:
Created an e2e cluster on GCE today. Found coredns manifest appears in the addons folder even if it is disabled:
```
# On master node.
$ pwd
/etc/kubernetes/addons/dns
$ ls
coredns.yaml.in  kube-dns.yaml
```

Coredns resources are not created though, probably because `coredns.yaml.in` is a raw template (contains something like `{{ pillar['dns_server'] }}`) that wouldn't pass validation.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster on HEAD and check `/etc/kubernetes/addons/dns` folder.

@rajansandeep

### PR DESCRIPTION
**Pull request by rajansandeep**
**What this PR does / why we need it**:
Separate the CoreDNS and kube-dns manifests by creating their own folders (dns/coredns and dns/kube-dns) 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61435 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
cc @MrHohn

### CODE REVIEW

**Comment by rajansandeep** [comment]
Please let me know if I've missed out on any cluster-up scripts change.

**Review by MrHohn — APPROVED** [review]
Thanks! This looks good

/lgtm

**Comment by MrHohn** [comment]
/assign @zmerlynn 
for approval.

**Review by zouyee — APPROVED** [review]

**Comment by zouyee** [comment]
some conflicts need to be resolved.😄

**Comment by rajansandeep** [comment]
@MrHohn can I get the lgtm tag again. I had to rebase this PR. Thanks!

**Comment by MrHohn** [comment]
Sorry for the delay.
/lgtm

**Comment by rajansandeep** [comment]
@zmerlynn awaiting approval.

**Comment by rajansandeep** [comment]
@kubernetes/sig-cluster-lifecycle-api-reviews for review/approval.

**Comment by rajansandeep** [comment]
@MrHohn need the lgtm tag again, had to rebase. Thanks!
Also, can we do something about getting the additional approval required? Seems to be taking an unusually long time :/

**Comment by fturib** [comment]
@thockin : thank you for the approval. Can you also add the right labels so it can get merged ? (I am thinking milestones labels - I guess it is status/approved-for-milestone)

**Comment by fturib** [comment]
@luxas, @timothysc : I think only the Owner of the SIG can set the labels for having that PR merged for this release. Can you add it ? - test is in good shape, PR is approved. Thanks!

**Comment by roberthbailey** [comment]
I set the milestone to 1.11 which I think is what was missing.

**Pull request merged**
