### PR TITLE
Delete redundant print 'got:'

### LINKED ISSUE #50592: Unit test error message should follow go style
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Unit test error message match the conventional Go style:

https://github.com/golang/go/wiki/CodeReviewComments#useful-test-failures
For example:

if got, want := set.Status.Replicas, 3; got != want {
  t.Errorf("set.Status.Replicas = %v; want %v", got, want)
}

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Delete redundant print 'got:'

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/50592

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@erictune 
PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@janetkuo PTAL

**Review by janetkuo — APPROVED** [review]

**Comment by zhangxiaoyu-zidif** [comment]
@janetkuo 
could you add "/approve no issue" label
Thanks.

**Comment by zhangxiaoyu-zidif** [comment]
@janetkuo
could you add "/approve no-issue" label
Thanks.

**Pull request merged**
