### PR TITLE
Update external provisioner test to use latest nfs-provisioner

### PR DESCRIPTION
**Pull request by wongma7**
**What this PR does / why we need it**: latest nfs-provisioner will work with cri-containerd, so let's update it

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: I want to move this test to use nfs-client-provisioner soon anyway since a lot of our e2e tests already use a containerized nfs server and it would be good to be consistent. So this can be treated as something of a stopgap but it would be nice to have ASAP to unblock https://github.com/kubernetes-incubator/external-storage/issues/432#issuecomment-417511065

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Random-Liu** [comment]
@msau42 Can you take another look at this?

**Comment by msau42** [comment]
/lgtm

cc @mkimuram

**Comment by Random-Liu** [comment]
Based on the test result, this PR does fix the Dynamic PV test failure, e.g.:
```
I0904 18:03:33.907] [BeforeEach] [sig-storage] In-tree Volumes
I0904 18:03:33.907]   test/e2e/framework/framework.go:144
I0904 18:03:33.907] [1mSTEP[0m: Creating a kubernetes client
I0904 18:03:33.907] Sep  4 18:02:44.003: INFO: >>> kubeConfig: /workspace/.kube/config
I0904 18:03:33.908] [1mSTEP[0m: Building a namespace api object, basename volumes
I0904 18:03:33.908] [1mSTEP[0m: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in e2e-tests-volumes-bhfnf
I0904 18:03:33.908] [1mSTEP[0m: Waiting for a default service account to be provisioned in namespace
I0904 18:03:33.908] [BeforeEach] [sig-storage] In-tree Volumes
I0904 18:03:33.908]   test/e2e/storage/in_tree_volumes.go:64
I0904 18:03:33.908] [BeforeEach] [Driver: gcepd]
I0904 18:03:33.908]   test/e2e/storage/in_tree_volumes.go:77
I0904 18:03:33.909] [BeforeEach] [Testpattern: Dynamic PV (default fs)] subPath
I0904 18:03:33.909]   test/e2e/storage/testsuites/subpath.go:106
I0904 18:03:33.909] Sep  4 18:02:45.043: INFO: Creating resource for dynamic PV
I0904 18:03:33.909] [1mSTEP[0m: creating a StorageClass e2e-tests-volumes-bhfnf-gcepd-sc
I0904 18:03:33.909] [1mSTEP[0m: creating a claim
I0904 18:03:33.909] Sep  4 18:02:45.089: INFO: Waiting up to 5m0s for PersistentVolumeClaim pvc-bwd5g to have phase Bound
I0904 18:03:33.909] Sep  4 18:02:45.108: INFO: PersistentVolumeClaim pvc-bwd5g found but phase is Pending instead of Bound.
I0904 18:03:33.909] Sep  4 18:02:47.116: INFO: PersistentVolumeClaim pvc-bwd5g found and phase=Bound (2.027402107s)
I0904 18:03:33.909] [It] should support readOnly file specified in the volumeMount
I0904 18:03:33.910]   test/e2e/storage/testsuites/subpath.go:336
I0904 18:03:33.910] [1mSTEP[0m: Creating pod pod-subpath-test-gcepd-dynamicpv-rvfr
I0904 18:03:33.910] [1mSTEP[0m: Creating a pod to test subpath
I0904 18:03:33.910] Sep  4 18:02:47.198: INFO: Waiting up to 5m0s for pod "pod-subpath-test-gcepd-dynamicpv-rvfr" in namespace "e2e-tests-volumes-bhfnf" to be "success or failure"
I0904 18:03:33.910] Sep  4 18:02:47.217: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 18.853147ms
I0904 18:03:33.910] Sep  4 18:02:49.228: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 2.029726796s
I0904 18:03:33.910] Sep  4 18:02:51.236: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 4.037521272s
I0904 18:03:33.911] Sep  4 18:02:53.246: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 6.04772902s
I0904 18:03:33.911] Sep  4 18:02:55.263: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 8.065328108s
I0904 18:03:33.911] Sep  4 18:02:57.275: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 10.076698512s
I0904 18:03:33.911] Sep  4 18:02:59.300: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 12.101346733s
I0904 18:03:33.911] Sep  4 18:03:01.380: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 14.182033665s
I0904 18:03:33.911] Sep  4 18:03:03.387: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 16.189332732s
I0904 18:03:33.911] Sep  4 18:03:05.436: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 18.237522815s
I0904 18:03:33.912] Sep  4 18:03:07.450: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 20.252042755s
I0904 18:03:33.912] Sep  4 18:03:09.462: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 22.264337837s
I0904 18:03:33.912] Sep  4 18:03:11.468: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 24.269396566s
I0904 18:03:33.912] Sep  4 18:03:13.480: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 26.281534613s
I0904 18:03:33.912] Sep  4 18:03:15.483: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Pending", Reason="", readiness=false. Elapsed: 28.284758151s
I0904 18:03:33.912] Sep  4 18:03:17.508: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr": Phase="Succeeded", Reason="", readiness=false. Elapsed: 30.309401207s
I0904 18:03:33.912] [1mSTEP[0m: Saw pod success
I0904 18:03:33.913] Sep  4 18:03:17.508: INFO: Pod "pod-subpath-test-gcepd-dynamicpv-rvfr" satisfied condition "success or failure"
I0904 18:03:33.913] Sep  4 18:03:17.523: INFO: Trying to get logs from node e2e-10-4eb99-minion-group-9wvl pod pod-subpath-test-gcepd-dynamicpv-rvfr container test-container-subpath-gcepd-dynamicpv-rvfr: <nil>
I0904 18:03:33.913] [1mSTEP[0m: delete the pod
I0904 18:03:33.913] Sep  4 18:03:17.579: INFO: Waiting for pod pod-subpath-test-gcepd-dynamicpv-rvfr to disappear
I0904 18:03:33.913] Sep  4 18:03:17.618: INFO: Pod pod-subpath-test-gcepd-dynamicpv-rvfr no longer exists
I0904 18:03:33.913] [1mSTEP[0m: Deleting pod pod-subpath-test-gcepd-dynamicpv-rvfr
I0904 18:03:33.913] Sep  4 18:03:17.618: INFO: Deleting pod "pod-subpath-test-gcepd-dynamicpv-rvfr" in namespace "e2e-tests-volumes-bhfnf"
I0904 18:03:33.913] [AfterEach] [Testpattern: Dynamic PV (default fs)] subPath
I0904 18:03:33.914]   test/e2e/storage/testsuites/subpath.go:120
I0904 18:03:33.914] [1mSTEP[0m: Deleting pod
I0904 18:03:33.914] [AfterEach] [Driver: gcepd]
I0904 18:03:33.914]   test/e2e/storage/in_tree_volumes.go:83
I0904 18:03:33.914] [AfterEach] [sig-storage] In-tree Volumes
I0904 18:03:33.914]   test/e2e/framework/framework.go:145
I0904 18:03:33.914] Sep  4 18:03:17.636: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0904 18:03:33.914] [1mSTEP[0m: Destroying namespace "e2e-tests-volumes-bhfnf" for this suite.
I0904 18:03:33.914] Sep  4 18:03:33.701: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
I0904 18:03:33.914] Sep  4 18:03:33.883: INFO: namespace: e2e-tests-volumes-bhfnf, resource: bindings, ignored listing per whitelist
I0904 18:03:33.915] Sep  4 18:03:33.905: INFO: namespace e2e-tests-volumes-bhfnf deletion completed in 16.251349767s
I0904 18:03:33.915] 
I0904 18:03:33.915] 
I0904 18:03:33.915] [32m• [SLOW TEST:49.902 seconds][0m
I0904 18:03:33.915] [sig-storage] In-tree Volumes
I0904 18:03:33.915] [90mtest/e2e/storage/utils/framework.go:22[0m
I0904 18:03:33.915]   [Driver: gcepd]
I0904 18:03:33.915]   [90mtest/e2e/storage/in_tree_volumes.go:74[0m
I0904 18:03:33.915]     [Testpattern: Dynamic PV (default fs)] subPath
I0904 18:03:33.915]     [90mtest/e2e/storage/testsuites/subpath.go:99[0m
I0904 18:03:33.915]       should support readOnly file specified in the volumeMount
I0904 18:03:33.916]       [90mtest/e2e/storage/testsuites/subpath.go:336[0m
```

Thanks! @wongma7

**Pull request merged**
