### PR TITLE
proxy startup-time config handling cleanup (take 2)

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
retrying #117297 after it was reverted

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/priority important-longterm
/triage accepted

### CODE REVIEW

**Comment by danwinship** [comment]
ok, the fix is moving the `o.platformApplyDefaults()` call from `o.ApplyDefaults()` (which is called on the baseline mostly-empty `Config` object) to `o.Complete()` (which, among other things, throws away the existing `o.config` if you passed a config file on the command line).

The kubeadm CI bug can be reproduced by starting the bad version of kube-proxy with a config file that does not specify a `mode`. Because `platformApplyDefaults` was being called too early, the `mode: iptables` that it set was getting overwritten with the empty `mode` from the config file, and then `newProxyServer` ended up creating no `proxier` object because it doesn't have a case for `mode is invalid`, since that was supposed to be impossible at that point...

**Comment by aojea** [comment]
> ok, the fix is moving the o.platformApplyDefaults() call from o.ApplyDefaults() (which is called on the baseline mostly-empty Config object) to o.Complete() (which, among other things, throws away the existing o.config if you passed a config file on the command line).

AFAIK `opts.ApplyDefaults(opts.config)` it is only generating a default config with defaults, the `opts.config` passed as parameters will be always empty, no?

if that is the case, why don't we just do

```
diff --git a/cmd/kube-proxy/app/server.go b/cmd/kube-proxy/app/server.go
index 2aa6d5a8244..dc3c5f8c0be 100644
--- a/cmd/kube-proxy/app/server.go
+++ b/cmd/kube-proxy/app/server.go
@@ -207,8 +207,11 @@ func (o *Options) AddFlags(fs *pflag.FlagSet) {
 
 // NewOptions returns initialized Options
 func NewOptions() *Options {
+       config := new(kubeproxyconfig.KubeProxyConfiguration)
+       proxyconfigscheme.Scheme.Default(config)
+
        return &Options{
-               config:      new(kubeproxyconfig.KubeProxyConfiguration),
+               config:      config,
                healthzPort: ports.ProxyHealthzPort,
                metricsPort: ports.ProxyStatusPort,
                errCh:       make(chan error),
@@ -438,25 +441,6 @@ func (o *Options) loadConfig(data []byte) (*kubeproxyconfig.KubeProxyConfigurati
        return proxyConfig, nil
 }
 
-// ApplyDefaults applies the default values to Options.
-func (o *Options) ApplyDefaults(in *kubeproxyconfig.KubeProxyConfiguration) (*kubeproxyconfig.KubeProxyConfiguration, error) {
-       external, err := proxyconfigscheme.Scheme.ConvertToVersion(in, v1alpha1.SchemeGroupVersion)
-       if err != nil {
-               return nil, err
-       }
-
-       proxyconfigscheme.Scheme.Default(external)
-
-       internal, err := proxyconfigscheme.Scheme.ConvertToVersion(external, kubeproxyconfig.SchemeGroupVersion)
-       if err != nil {
-               return nil, err
-       }
-
-       out := internal.(*kubeproxyconfig.KubeProxyConfiguration)
-
-       return out, nil
-}
-
 // NewProxyCommand creates a *cobra.Command object with default parameters
 func NewProxyCommand() *cobra.Command {
        opts := NewOptions()
```

the rest LGTM

**Comment by aojea** [comment]
/lgtm

> But we can simplify a little, https://github.com/kubernetes/kubernetes/commit/ab604363614488f14da1db06ef66c1d111146ff2
❤️

**Comment by danwinship** [comment]
>  `cmd/kube-proxy/app/server.go:214:3: unstructured logging function "Fatalf" should not be used (logcheck) `

@#$!$! I totally checked to see if it was marked "Deprecated"!

**Pull request merged**
