### PR TITLE
WIP - set apiVersion/kind in list items

### LINKED ISSUE #3030: REST api - 'kind' property not always exists on entities
'kind' property exists only on the outer entity in REST api hence providing not aligned behavior for REST api consumers.
Example: when querying for all services (/api/v1beta1/services) there's an attribute 
"kind": "ServiceList" on the collection, but in the "items" section with the actual services - none of the services has the "kind" attribute.
But when querying for a specific service, for example:
http://localhost:8080/api/v1beta1/services/kubernetes-ro
There is a "kind": "Service" on the entity.

I don't see the necessity to have the "kind" property in the first place since the user knows which resource was called by the api specific url, but even if it has a reason and is by design, the entities attributes should be identical whether retrieved as a single entity or as a collection. Otherwise the client should be adding/deleting attributes when retrieved as a collection by their collection type - which is doable, but definitely not elegant.
In other words, either "kind" should be present in each entity when retrieved in bulk AND when retrieved as a single entity, or not present at all for all cases.

### LINKED ISSUE #80609: Decoding should not clear apiVersion/kind
**What would you like to be added**:
When using a typed client, decoding to a versioned struct (not an internal API type), the apiVersion/kind information returned from the server should not be dropped.

**Why is this needed**:
The `GroupVersionKind()` method included in the ObjectKind interface is largely useless when dealing with arbitrary runtime.Object instances, since typed instances drop this information here:

https://github.com/kubernetes/kubernetes/blob/69a34f6a6f67de47cb9b72b6ac98e089d301beb3/staging/src/k8s.io/apimachinery/pkg/runtime/helper.go#L245-L259

This is the decoder used when a client requests a decoder that does not do conversion:

https://github.com/kubernetes/kubernetes/blob/69a34f6a6f67de47cb9b72b6ac98e089d301beb3/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/codec_factory.go#L175-L179

I could see clearing group/version/kind information when converting to an internal version, but I don't see the benefit of stripping it on decode if we're only dealing with a versioned struct.

/sig api-machinery
/cc @smarterclayton 

Note that https://github.com/kubernetes/kubernetes/issues/3030 still needs to be resolved before apiVersion/kind could be depended on for individual objects for all API responses, but this would at least solve the issue with an update of an object clearing the apiVersion/kind in an update response (xref https://github.com/kubernetes-sigs/controller-runtime/issues/526)

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind api-change
/kind bug

**What this PR does / why we need it**:

Explores fixing https://github.com/kubernetes/kubernetes/issues/3030 by:
* generating code in conversion to populate apiVersion/kind in external types
* avoiding clearing apiVersion/kind when decoding into external types

This is *very* WIP/experimental. Still need to:
- [ ] discuss this approach to populating apiVersion/kind
- [ ] measure allocation impact to list conversions (cc @kubernetes/sig-scalability-pr-reviews)

If we move forward with this approach, still need to:
- [ ] clean up the GVK-clearing decoder
- [ ] figure out a better way to avoid short-circuit memory-equivalent unsafe copy of list items
- [ ] add tests around proto decoding preserving GVK in lists and individual items

**Which issue(s) this PR fixes**:
Fixes #3030
Fixes #80609

**Does this PR introduce a user-facing change?**:
```release-note
`apiVersion` and `kind` fields are now correctly populated in individual list items
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@kubernetes/sig-cluster-lifecycle-pr-reviews 
@rosti @vincepri

**Comment by neolit123** [comment]
cc @fabriziopandini

**Comment by bai** [comment]
👋 Hello from Bug Triage team! This PR has not been updated for a while, so I'd like to check its status. The code freeze is starting June 25th (about 4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.19, is it still planned for this release?

**Comment by bai** [comment]
Hey 👋 Bug Triage here. This PR has not been updated for a while, so I'd like to check on the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.20, is it still planned for this release?

**Pull request closed without merging**
