### PR TITLE
Remove unused `numExistingEndpoints` variable

### PR DESCRIPTION
**Pull request by akhilles**
#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by Kartik494** [comment]
@akhilles could you update your PR description to add kind as `/kind cleanup`

**Comment by akhilles** [comment]
> @akhilles could you update your PR description to add kind as `/kind cleanup`

Done

**Comment by aojea** [comment]
good catch
/lgtm
/assign @robscott

**Comment by robscott** [comment]
Thanks @akhilles!

/approve

**Pull request merged**
