### PR TITLE
expose: Use separate parameters for default and custom name

### PR DESCRIPTION
**Pull request by 0xmichalis**
cc: @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can we get a simple test case?

**Comment by smarterclayton** [comment]
ok to test

**Comment by kargakis** [comment]
@smarterclayton can we get this merged?

**Comment by smarterclayton** [comment]
LGTM

**Comment by rjnagal** [comment]
Travis came through. Integration timed out on shippable on one of the runs. LG, merging.

**Pull request merged**
