### PR TITLE
Use Container-optimzed OS images for nodes by default

### PR DESCRIPTION
**Pull request by abgworrall**
Part of the deprecation of the debian-based ContainerVM images.

```release-note
kube-up and kubemark will default to using cos (GCI) images for nodes.
The previous default was container-vm (CVM, "debian"), which is deprecated.
If you need to explicitly use container-vm for some reason, you should set
KUBE_NODE_OS_DISTRIBUTION=debian
```

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test

@abgworrall This likely merits a release note either way. Can you modify your PR body accordingly?

**Comment by timstclair** [comment]
I think there are a couple other places to update:

- https://github.com/kubernetes/kubernetes/blob/33fc75e223cd8968a5bafe26f2de630c9f3bffa1/cluster/kubemark/gce/config-default.sh#L38
- https://github.com/kubernetes/kubernetes/blob/33fc75e223cd8968a5bafe26f2de630c9f3bffa1/cluster/gce/config-test.sh#L73

Changing the default of the test _may_ have implications to our test jobs, if they don't override that value explicitly (e.g. https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-serial.env -- although I think setting the distribution is sufficient in that case?)

**Comment by mtaufen** [comment]
There's little risk to leaving the test configs as they are (we can swing back around and update them and remove the CVM test jobs when CVM is fully deprecated). Last year the CVM e2e tests relied on CVM being the default. Not sure about now. Also not sure about Kubemark, but I'd wager it's the same there too.

**Comment by abgworrall** [comment]
Thanks :) I just followed a breadcrumb trail that led to `NODE_OS_DISTRIBUTION`. New patches added.

Are we sure we want to keep running tests on the OS we don't use ? I notice that ~180 of the test jobs explicitly specify a `KUBE_NODE_OS_DISTRIBUTION` already; perhaps the ones that don't, should.

**Comment by abgworrall** [comment]
Ah, I understand the testing problem a little better now. I agree, we should leave them as debian. I'll undo the changes for testing.

**Comment by gmarek** [comment]
@abgworrall please rebase.

**Pull request merged**
