### PR TITLE
Test: use new intstr functions

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

#116665 introduces `intstr` contructors from `int32`; this PR updates code to use them.

/hold pending #116665

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Can you remind me why we didn't just change the original FromInt() to int32?  It's not a public API.

**Comment by skitt** [comment]
> Can you remind me why we didn't just change the original FromInt() to int32? It's not a public API.

I’m not sure it would have been tractable for me to convert everything in one PR (just from a review perspective; although at least in this PR most of the changes would have become unnecessary). It also turned out to be useful to keep the `int` version for a bunch of use-cases involving port numbers — getting that to be consistent is another battle...

**Comment by thockin** [comment]
> It also turned out to be useful to keep the int version for a bunch of use-cases involving port numbers 

I think it would be cleaner to call `intstr.FromInt(int32(port))` that to have `FromInt32()` forever.

What about generics?

something like:

https://go.dev/play/p/noMl3HAd1h_z

Since it is internal, this seems legit to me.

**Comment by skitt** [comment]
Ah, digging into this some more I remember one of the concerns I had — the overflow check in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L59 means that a plain `FromInt()` from a smaller type, used as `FromInt(int32(foo))` for `foo int` would result in a change in behaviour.

I like the generic approach to handle all smaller types, and I agree `FromInt()` is nicer to read than `FromInt32()` (but less explicit obviously).

**Comment by thockin** [comment]
This is an internal API - we can either change it and disallow anything larger than int32 via the type system or we can keep the (gross) range check, but that's really a vestigial artifact from pre-generic days.

**Comment by skitt** [comment]
I’ve done this as #119285, without using generics for two reasons — there are no users of `FromInt()` with types smaller than `int32`, and using a generic type means that all numeric constants need to be cast to one of the supported types.

**Comment by thockin** [comment]
> using a generic type means that all numeric constants need to be cast to one of the supported types

How often do we need to use literals?  If we use generics you need to cast literals and almost nothing else.  If we don't use generics we have to cast almost everywhere, including literals.  Why is it better to not use generics?

**Comment by skitt** [comment]
> How often do we need to use literals? If we use generics you need to cast literals and almost nothing else. If we don't use generics we have to cast almost everywhere, including literals. Why is it better to not use generics?

105 times in the current code-base.

With the suggested generics,

```go
type smallInt interface {
	int8 | int16 | int32
}
```

most current uses of non-literals need to be cast anyway (from `int`). We could use `constraints.Integer` or `constraints.Signed` to accept any integer type, relying on the existing comment that it’s up to callers to ensure that the given value fits in an `int32`; then no casts would ever be needed. That’s effectively what you’re suggesting in https://github.com/kubernetes/kubernetes/pull/119285#issuecomment-1635092843 ;-).

(The code produced for generics isn’t great, see https://godbolt.org/z/WrK57rcP3, but that’s probably not worth worrying about here compared to the convenience factor.)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
