### PR TITLE
kubectl factory client access: Moves remaining internal references to remaining callers.

### PR DESCRIPTION
**Pull request by seans3**
* "InternalVersionJSONEncoder" is only called one place (convert.go), and "InternalVersionDecoder" is also only called one place (get.go)
* Moves these functions referencing internal versions of resources to the two remaining callers, since convert.go and get.go are already difficult to clean and have several references to internal resources.
* Removes dependency on internal versions of resources from factory_client_access.go.
* Replaces internal resource dependency (api) to external version (corev1).

Helps address:
https://github.com/kubernetes/kubectl/issues/83

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
LGTM for me

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
lgtm as well

**Pull request merged**
