### PR TITLE
Add Kind to LocalObjectReference

### PR DESCRIPTION
**Pull request by liggitt**
Adds `Kind` to `LocalObjectReference`. Defaults `Kind` to the previously implicit kind for existing objects, and adds validation to ensure we don't allow unsupported values to be specified.

### CODE REVIEW

**Comment by liggitt** [comment]
@pmorie can you verify the defaults and validation for ConfigMapVolumeSource, ConfigMapKeySelector and SecretKeySelector are correct?

**Comment by bgrant0607** [comment]
@liggitt Motivation?

This assumes that kinds are unique across API groups.

**Comment by liggitt** [comment]
we have an ObjectReference we'd like to convert to a LocalObjectReference (just like the serviceaccount `secrets` field should be a []LocalObjectReference), but it is missing the Kind field.

Agree on needing the API group to fully qualifiy the kind, but I really didn't want to propagate the single apiVersion field in ObjectReference until we'd resolved how to handle the things discussed in https://github.com/kubernetes/kubernetes/pull/12951#discussion_r38799725

**Comment by thockin** [comment]
I feel like Kind makes sense when you're addressing a polymorphic object
with a sub-resource that exists on various Kinds.  I don't feel like we
have any real principles in the various *ObjectReference and it's starting
to really show.

**Comment by deads2k** [comment]
Specifying a kind on an ObjectReference allows an intent based field.  For example, we use it to represent `Subjects` for authorization.  A Subject can be a user, a group, or a service account.  We can have a single `Subjects []ObjectReference` because we have a kind field.  Without that field we wouldn't be able to do that.

You can also envision similar utility for describing something you want to trigger based on a `LocalObjectReference`.  You can have `Triggers []LocalObjectReference` that can point at multiple different kinds.

`Kind` by itself has some value.  I agree that I want to specify `apiGroup` in particular, but I really dislike having a field called `apiVersion` that is used to store my `apiGroup` since I almost always want it to auto-negotiate a version for me.

**Comment by thockin** [comment]
If you don't know the actual Kind, then it falls into the polymorphic case
I mentioned.  The question for me is, assuming you know the Kind (e.g.
configmap volume only references a configmap), should it be not allowed to
specify Kind, allowed but defaulted and validated to the known kind, or
required for the user to specify Kind.

As we do more and more cross-reference fields, I think we want consistency.

**Comment by deads2k** [comment]
I would say that it should be defaulted (not forced) and validated for single allowed kind.  That way if a user sets it to something strange, he won't see his value stomped (which may actually point at something he isn't expecting).

**Comment by thockin** [comment]
If we add this field, it has to come with defaults for all existing uses.
And we still have to address API group, which is sort of an intrinsic part
of a kind, but happens to be coupled to a version by convention.

**Comment by liggitt** [comment]
> If we add this field, it has to come with defaults for all existing uses.

which it does

**Comment by thockin** [comment]
I also am a non-fan of reuse.  It makes for crappy docs and exposes details
of implementations.

Can we just inline-define a struct for this?  What does swagger so with
that?

**Comment by bgrant0607** [comment]
@thockin No idea about the anon. inline struct. The reflection API is non-obvious enough that we'd just have to try it to see whether go-restful did what we expected.

**Pull request closed without merging**
