### PR TITLE
no need to remove file respectively

### PR DESCRIPTION
**Pull request by guangxuli**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33724)

### CODE REVIEW

**Comment by ericchiang** [comment]
lgtm

@kubernetes/sig-auth can someone label appropriately?

**Comment by ericchiang** [comment]
@k8s-bot gke e2e test this, issue: #33672

**Comment by ericchiang** [comment]
@k8s-bot gke e2e test this, issue: #33672

**Comment by guangxuli** [comment]
@ericchiang ptal, GCE e2e, build failed, I think it is not relative to this PR. Thanks.

**Comment by ericchiang** [comment]
@guangxuli this is an extremely small, non-functional change. While the e2e tests should pass, I don't know how much CI time we want to take up to get this in. Would it be okay if we add this to the next update to the oidc plugin?

**Comment by guangxuli** [comment]
@ericchiang okay, thanks.

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this

**Comment by deads2k** [comment]
> @guangxuli this is an extremely small, non-functional change. While the e2e tests should pass, I don't know how much CI time we want to take up to get this in. Would it be okay if we add this to the next update to the oidc plugin?

Given how unlikely this is to collide with another change, I'm willing to go `retest-not-required` on this pull and give it one more shot, but @ericchiang does raise a good point.  If our queue is flaking and this had to run through, I'd deprioritize this.

**Pull request merged**
