### PR TITLE
Move pkg/kubelet/apis to k8s.io/kubelet/pkg/apis

### PR DESCRIPTION
**Pull request by michaelbeaumont**
**What type of PR is this?**
/kind cleanup
/area code-organization

**What this PR does / why we need it**:
At the moment, in order to programmatically validate which labels kubelet will accept if provided through `--node-labels`, the user needs to import from k8s.io/kubernetes, which is not intended for consumption as a module.
Resurrects https://github.com/kubernetes/kubernetes/pull/92527 which went stale without a resolution (https://github.com/kubernetes/kubernetes/pull/92527#issuecomment-663658293)

**Does this PR introduce a user-facing change?**:

```release-note
APIs for kubelet annotations and labels from k8s.io/kubernetes/pkg/kubelet/apis are now available under k8s.io/kubelet/pkg/apis/
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by dims** [comment]
looks like a well contained change (basically move well_known_labels.go over and fix references). LGTM from a code-org perspective.

/approve

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
This is nice.

**Comment by liggitt** [comment]
This looks reasonable to me. As an aside, the old `pkg/kubelet/apis` and new `staging/src/k8s.io/kubelet/pkg/apis` packages should have approvals limited to API approvers or node API approvers to make sure cross-version breaking changes aren't accidentally merged. cc @derekwaynecarr 

/lgtm
/approve

**Pull request merged**
