### PR TITLE
owners: update puerco/cpanato and clean up old members

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

owners: update puerco/cpanato and clean up old members

As part of the onboard described in this issue: https://github.com/kubernetes/sig-release/issues/1590

/assign @justaugustus @jeremyrickard @hasheddan @saschagrunert 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/sig architecture
/assign @smarterclayton @liggitt 

Jordan, Clayton, needs root approval please.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
