### PR TITLE
change kubemark from ReplicationController to Deployment

### PR DESCRIPTION
**Pull request by xieyanker**
**What type of PR is this?**

/kind api-change
/kind cleanup

**What this PR does / why we need it**:

As far as I know, the `ReplicationController` has been replaced by `ReplicationSet` and `Deployment`, the new version is no longer recommended to use `ReplicationController`.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xieyanker** [comment]
/test pull-kubernetes-e2e-gce

It seems the failed test not related to this commit.
```shell
I1219 03:02:40.119] • Failure [131.004 seconds]
I1219 03:02:40.120] [sig-storage] In-tree Volumes
I1219 03:02:40.120] test/e2e/storage/utils/framework.go:23
I1219 03:02:40.120]   [Driver: local][LocalVolumeType: block]
I1219 03:02:40.120]   test/e2e/storage/in_tree_volumes.go:70
I1219 03:02:40.120]     [Testpattern: Pre-provisioned PV (default fs)] volumes
skipped 31208 lines unfold_more
I1219 03:15:55.114] 
I1219 03:15:55.114] [Fail] [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (default fs)] volumes [It] should allow exec of files on the volume 
I1219 03:15:55.114] test/e2e/framework/util.go:829
I1219 03:15:55.114] 
I1219 03:15:55.114] Ran 744 of 4841 Specs in 1610.470 seconds
I1219 03:15:55.114] FAIL! -- 743 Passed | 1 Failed | 0 Pending | 4097 Skipped
```

**Comment by liggitt** [comment]
`Kubemark Up` failed on this PR, even though the job succeeded. This was corrected in https://github.com/kubernetes/test-infra/pull/15657

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-kubemark-e2e-gce-big shows kubemark-up hasn't succeeded since this was merged

**Comment by liggitt** [comment]
speculative revert PR opened in https://github.com/kubernetes/kubernetes/pull/86464 to see if that makes the job go green

**Pull request merged**
