### PR TITLE
Automated cherry pick of #16749

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #16749 on release-1.1.

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr 

LGTM

**Comment by vishh** [comment]
@dchen1107: I don't see any unit test or integration test failures. I'm not sure why the unit test jenkins job is reporting failure. I suspect issues with the unit test framework on jenkins. This PR should be good to go.
This might need a manual merge though.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by piosz** [comment]
Merging manually due to an issue with CLA

**Pull request merged**
