### PR TITLE
chore: Fix typo in `pkg/scheduler/schedule_one.go`

### PR DESCRIPTION
**Pull request by utam0k**
#### What type of PR is this?

/kind clean-up

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Just fix a typo.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lianghao208** [comment]
I don't think this is a typo though, `iff` means `If and only if` and it's commonly used.

**Comment by utam0k** [comment]
> I don't think this is a typo though, `iff` means `If and only if` and it's commonly used.

Thanks for your comment. I didn't know it 🤦‍♂

**Comment by sanposhiho** [comment]
Yes, it's not a typo and I've seen many people sending the same PR. So did I 😅 
https://github.com/kubernetes/kubernetes/pull/104542

**Pull request closed without merging**
