### PR TITLE
Backport e2e Image Override Changes

### PR DESCRIPTION
**Pull request by r4f4**
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
 /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Enables running Openshift CI on s390x

**Which issue(s) this PR fixes**: 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by r4f4** [comment]
I signed it

**Comment by neolit123** [comment]
@r4f4 hello, 1.15 is not going to have any more releases.
was this backport requested by a maintainer?

**Comment by r4f4** [comment]
> @r4f4 hello, 1.15 is not going to have any more releases.
> was this backport requested by a maintainer?

@dbenoit17 can also chime in on why this was done. Basically we have to patch the `vendor/kubernetes` side of things in Openshift every time to be able to run CI on s390x. It would be better if the changes were in Kubernetes proper instead so they trickle down to Openshift.

**Comment by neolit123** [comment]
1.15 will be hard to make another release at this point.
if you want a discussion you can send an email to this mailing lists:
https://groups.google.com/forum/#!forum/kubernetes-sig-release

or send a message in #sig-release on k8s slack.

**Comment by r4f4** [comment]
> 1.15 will be hard to make another release at this point.
> if you want a discussion you can send an email to this mailing list:
> https://groups.google.com/forum/#!forum/kubernetes-sig-release
> 
> or send a message in #sig-release on k8s slack.

Ok. So I'll close this PR. Thanks.

**Pull request closed without merging**
