### PR TITLE
Cobra update and bash completions fix

### PR DESCRIPTION
**Pull request by eparis**
filename extensions weren't working.  kubectl create -f [tab][tab] wasn't showing .json/yaml files.  Only directories.

### CODE REVIEW

**Comment by mbforbes** [comment]
@jlowdermilk unsure whether you have context on conbra and bash completions—feel free to reassign elsewhere if not

**Comment by jlowdermilk** [comment]
lgtm. Test failure looks like flake. I kicked travis.

**Comment by jlowdermilk** [comment]
Hmmm, still broken: https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/61327954 Unit test failing in pkg/client for v1beta1. Can you take a look? If you don't think this should affect it, rebasing may resolve.

**Comment by jlowdermilk** [comment]
Shippable green, merging.

**Pull request merged**
