### PR TITLE
federation: Upgrading the groupversion to v1beta1

### PR DESCRIPTION
**Pull request by nikhiljindal**
This PR contains 2 commits:
- Removing fields from Cluster API object that we are not using. This includes: Capacity, Allocatable and ClusterMeta.
- Move code and rename groupversion `federation/v1alpha1` to `federation/v1beta1`

cc @kubernetes/sig-cluster-federation

### CODE REVIEW

**Comment by lavalamp** [comment]
@caesarxuchao can you review? I didn't see anything obviously wrong but I also didn't look very carefully...

**Comment by quinton-hoole** [comment]
cc: @davidopp @matchstick This is the PR to achieve what was discussed yesterday w.r.t. correctly reflecting this as beta, not alpha.

**Comment by quinton-hoole** [comment]
@caesarxuchao This LGTM.  Will leave it to you to approve after review.

**Comment by caesarxuchao** [comment]
The changes look fine. I think you will cherry-pick it to 1.3 branch? You might have problem cherry-picking the clientset changes, because https://github.com/kubernetes/kubernetes/pull/27293 is not cherry-picked to 1.3.

**Comment by caesarxuchao** [comment]
Per offline discussion, @nikhiljindal will manually fix the conflicts during cherry-pick. LGTM.

**Comment by nikhiljindal** [comment]
e2e failure seems like a flake
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/27450

**Comment by erictune** [comment]
@eparis is this going to be a pain to cherry pick/rebase?

**Comment by eparis** [comment]
The pick was easy, but it doesn't build. Must be some missing pre-req...
```
$ hack/update-all.sh -v
Running in short-circuit mode; run with -a to force all scripts to run.
Updating generated-protobuf
+++ [0629 16:11:47] Verifying Prerequisites....
+++ [0629 16:11:47] Building Docker image kube-build:build-c01f95343e.
+++ [0629 16:11:47] Running build command....
Go version: go version go1.6.2 linux/amd64
+++ [0629 16:11:55] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0629 16:11:56] Building go targets for linux/amd64:
    cmd/libs/go2idl/go-to-protobuf
    cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo
+++ [0629 16:12:02] Placing binaries
2016/06/29 16:12:02 Unable to add directory "k8s.io/kubernetes/pkg/apis/certificates/v1alpha1": unable to *find* "k8s.io/kubernetes/pkg/apis/certificates/v1alpha1": cannot find package "k8s.io/kubernetes/pkg/apis/certificates/v1alpha1" in any of:
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubernetes/pkg/apis/certificates/v1alpha1 (vendor tree)
	/usr/local/go/src/k8s.io/kubernetes/pkg/apis/certificates/v1alpha1 (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apis/certificates/v1alpha1 (from $GOPATH)
!!! Error in hack/update-generated-protobuf-dockerized.sh:43
  'PATH="${KUBE_ROOT}/_output/local/go/bin:${PATH}" "${gotoprotobuf}" --proto-import="${KUBE_ROOT}/vendor" --proto-import="${KUBE_ROOT}/third_party/protobuf"' exited with status 1
Call stack:
  1: hack/update-generated-protobuf-dockerized.sh:43 main(...)
Exiting with status 1
!!! Error in hack/../hack/../build/common.sh:620
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: hack/../hack/../build/common.sh:620 kube::build::run_build_command(...)
  2: hack/../hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
Updating generated-protobuf FAILED
```

**Comment by erictune** [comment]
@nikhiljindal Can you take a look at the build failure, or better yet checkout out release-1.3, check out https://github.com/kubernetes/kubernetes/pull/28119, apply this commit, and see why it won't build.

**Comment by nikhiljindal** [comment]
Yes am talking to @eparis on slack.
certificates/v1alpha1 group version was recently added on HEAD in https://github.com/kubernetes/kubernetes/pull/25562. Its not required in 1.3.

**Comment by nikhiljindal** [comment]
Confirmed with @eparis that he was able to cherrypick this PR fine.

**Comment by erictune** [comment]
@nikhiljindal  Does this PR require action by the user when upgrading from 1.2.x to 1.3.0?  (Think about non-developer users.) If so, please edit your first comment to have  a release-note block, like in https://github.com/kubernetes/kubernetes/pull/28132.  If it is just an optional feature, please change the label to just release-note.  If it is not a complete feature by itself, then apply "release-note-none" label instead.

**Comment by madhusudancs** [comment]
@erictune Changed the label to release-note-none

@nikhiljindal and others who might be interested.
Reason: This API did not even exist in 1.2. So there is no action to be taken by the users while going from 1.2 to 1.3. Also, it is not a feature by itself. So it is not that useful to have it in the release note. Release note should be added in the PR that introduced this API.

**Pull request merged**
