### PR TITLE
client-go: support detect homedir with SNAP_REAL_HOME and os/user.HomeDir

### PR DESCRIPTION
**Pull request by HollowMan6**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Detect homedir with $SNAP_REAL_HOME, so that we can get the right $HOME when running inside snap. https://github.com/snapcore/snapd/pull/9189

Also when $HOME is unset, try os/user.HomeDir

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
FYI, the same change was suggested downstream in controller-runtime and I suggested to instead open an issue with snap, as updating all possible software that accesses $HOME to fallback to some non-standard additional home dir seems unreasonable to me compared to making snap instead find a way to have everything in the same $HOME (overlay? links?): https://github.com/kubernetes-sigs/controller-runtime/pull/2266

**Comment by jpbetz** [comment]
> updating all possible software that accesses $HOME to fallback to some non-standard additional home dir seems unreasonable to me compared to making snap instead find a way to have everything

I fully agree. This change does not belong in core Kubernetes.

**Comment by HollowMan6** [comment]
I know you have a right to reject a PR, but what you are choosing is actually causing great blockers to lots of developers like us who wants to publish their apps to snap store. Now I need to use go vendor mode and [patch exactly the same code in this PR](https://github.com/HollowMan6/packaging/blob/main/snap_homedir.patch) to get it fixed. Although I'm not involved into snap project, "Making snap instead find a way to have everything in the same $HOME (overlay? links?)" may not be possible at all due to possible technical or security reasons. That's quite arrogant for you to close all those PRs before hearing any feedback from https://forum.snapcraft.io/t/feature-request-stop-using-snap-real-home-to-visit-real-home-files/34683

Actually some SDK has already support the SNAP_REAL_HOME long time ago, like [the openstacksdk](https://github.com/openstack/openstacksdk/blob/d5aba8a6b1a26debf93c5a3c78fb539a490efe5d/openstack/config/loader.py#L43-L53), I don't know why they are so willing to merge PRs like this https://opendev.org/openstack/openstacksdk/commit/78dd1a73d8ff063612560a9882b26bffa5f9e51a?style=unified&whitespace=

**Comment by HollowMan6** [comment]
@jpbetz @alvaroaleman If you don't want to introduce $SNAP_REAL_HOME anyway, I would recommend another way to fix this, like using guesses, as snap remaps $HOME into `/home/$USER/snap/<software>/$SNAP_VERSION`. In this case, we can do such that:
- If the $HOME contains more than 3 directory levels, then go up 3 directory levels to use guesses to fetch the kubeconfig.

If would be quite irresponsible if you just blame snap and do nothing at your side to get things fixed and done.

**Comment by thockin** [comment]
I concur with @jpbetz and while I know it's not what you want to hear, I'd appreciate it if you take a less accusatory tone.

Snap defining $HOME to mean something other than its normal meaning is weird and broken.  LOTS of software looks at $HOME, and almost none looks at $SNAP_REAL_HOME.  If some critical mass of users relied on snap  day-to-day, maybe.  But as it stands, they don't seem to be in a position to demand that the world adapt to their bizarro conventions.

I don't object to checking `user.Current()` for `.HomeDir` - but I would check that AFTER looking for $HOME - anything else is a potentially breaking change.

I could also see an argument to look for $XDG_CONFIG_HOME (that's at least somewhat standard), but again *after* looking for $HOME.  

Crawling up the directory tree is pretty sketchy, and I don't think we want to entertain that idea.

I can't speak to OpenStack's decisions - we are not them.  If some massive body of users chimes in saying that this is a pain point for them, I'll be happy to re-evaluate.

**Comment by BenTheElder** [comment]
Please see discussions on https://github.com/kubernetes/enhancements/pull/2111

Changing the lookup logic for kubeconfig is a major breaking change that affects many other pieces of software.

**Comment by HollowMan6** [comment]
Just want to mention one funny off-topic thing. It's so hilarious that you silently changed the GPG key format from binary to ASCII armored https://github.com/kubernetes/website/pull/41307, causing [numerous breaks](https://github.com/kubernetes/release/issues/2862#issuecomment-1559273287). I can't think of any use case or valid reason for making such kind of change, but you still made it. Asking for updating all possible scripts that fetch the keys to fall back to the binary format for resolving such kind of unnecessary change is really a "clever way" to fix the problem. As it stands, it doesn't seem to be in a position to demand that the world adapts to its changing conventions.

Meanwhile, you said this PR would introduce breaking changes, but I can't see any "break" at all, as we will anyway return to $HOME, and who will set the `SNAP_*` if they are not running inside a snap environment?

I also mentioned that making snap instead finds a way to have everything in the same $HOME can be difficult technically, but is it also a technical difficulty to continue delivering the binary GPG format consistently?

**Comment by BenTheElder** [comment]
For The Record: We don't control the GPG key because we're still using the GCP package host with a few volunteer Google employees publishing packages for the project.  The project would not have made that change and we're fully aware of the breakage and discussing mitigations. Long term there's an active effort to move to project controlled hosting.

This is not a productive conversation though. See the conversation in https://github.com/kubernetes/enhancements/pull/2111 for details on why we have to be careful with changes like this. A politely proposed [enhancement](https://github.com/kubernetes/enhancements) outlining how to implement this in a non-breaking way could be considered.

**Pull request closed without merging**
