### PR TITLE
coreos/azure: Updates for 1.0

### PR DESCRIPTION
**Pull request by errordeveloper**
- Bump CLI tools version
- Bump CoreOS image IDs
- Use etcd2 shipped in stable channel
- Prefix unit names for consistency
- Run proxy on master as well
- Allocate node port for the app
- Update docs
- No need to register nodes any more
- Remove stale argument `--cloud_provider=vagrant`
- Refactor how addons are delivered
- Remove fluentd (it can be optionally dropped into addons dir)
- Script Azure endpoint creation for Guestbook example
- Provide only SkyDNS addon out-of-the-box

### CODE REVIEW

**Comment by errordeveloper** [comment]
Ok, looks like the example doesn't work as DNS add-on is missing...

**Comment by errordeveloper** [comment]
Ok, I figured how to fix SkyeDNS, was just missing master URL.

**Comment by errordeveloper** [comment]
The only remaining part is to make addon pods/rcs get created on boot or document the creation of (not sure).

**Comment by thockin** [comment]
You should not need --master_url for skydns if your master certs are
working.  Search the history of issues here for much discussion.

On Tue, Jul 21, 2015 at 8:10 AM, Ilya Dmitrichenko <notifications@github.com

**Comment by errordeveloper** [comment]
@thockin I didn't get to enable TLS yet... actually, a question to do with that - is it quite reasonable to use same cert as I am already using for SSH?

**Comment by thockin** [comment]
I am out of my depth on cert issues - I don't have a lot of direct experience here.  I'll punt you at others  @roberthbailey

**Comment by roberthbailey** [comment]
What kind of key usage is enabled on your ssh certificate (the apiserver will need a cert that can be used for server auth)?

For client components to validate the apiserver, they will need the public cert for the CA that signed the apiserver's server cert. This is passed to the apiserver when it starts up, so that it can be injected into the service accounts created by the system (and used, for example, by DNS). On GCE, we also distribute the CA cert to all of the nodes at startup so that the kubelets can validate the apiserver when joining the cluster.

**Comment by errordeveloper** [comment]
@roberthbailey right, so there is no CA cert being generated as part of [this](https://github.com/GoogleCloudPlatform/kubernetes/blob/7645513d2aa2edadfa090de708607464eab826d1/docs/getting-started-guides/coreos/azure/lib/azure_wrapper.js#L99), as far as I can see. Not sure CA generation would take just one extra `openssl` call or just a flag, but then may be it's probably just easier to generate a separate cert anyways. Should I really make this part of this PR or a follow-up one would be acceptable?

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
I'm happy having you enable TLS in a follow up PR (and we can discuss how to do it there or in an issue rather than in this change).

**Comment by mikedanese** [comment]
@errordeveloper can you rebase and run ./hack/run-gendocs.sh and ./hack/verify-boilerplate.sh? This is failing travis https://travis-ci.org/GoogleCloudPlatform/kubernetes/builds/72093970

**Comment by roberthbailey** [comment]
Changes LGTM, but travis is complaining about your docs being out of date. Can you run a `make clean` and re-push to see if that makes travis happier?

**Comment by errordeveloper** [comment]
Ok, it looks like it's passing now, and I hope 31122529f32c688c217a7c98e999149ded13c94f makes sense.

**Comment by errordeveloper** [comment]
I am not sure of the failure on shippable, and I cannot restart the build to confirm whether it's flaky or not...

**Comment by thockin** [comment]
Shippable was 50/50.  For future, youcan always close/open a PR to kick all the CI.

**Comment by thockin** [comment]
LGTM overall

**Pull request merged**
