### PR TITLE
update klog version to v2

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind feature

**What this PR does / why we need it**:
Addresses the scalability concerns in https://github.com/kubernetes/kubernetes/issues/89190, subtask of kubernetes/enhancements#1602, use klog.SetLogger function, so should update klog version to v2.
As @serathius suggest, this update will require different approvers, so give a separate PR from https://github.com/kubernetes/kubernetes/pull/89683 for this update

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by serathius** [comment]
/cc @dims 
@dims could you help upgrading klog to v2?

To I avoid changing all imports in k/k at once I was thinking about aliasing, but apparently it doesn't work https://github.com/golang/go/issues/26904

**Comment by dims** [comment]
@serathius we are at v2 :) https://github.com/kubernetes/klog/blob/master/go.mod#L1

**Comment by serathius** [comment]
@dims I think problem is that v2 is not used in k/k repo.
For structured logging we need SetLogger function that was implemented in v2.

**Review by logicalhan — APPROVED** [review]
/lgtm

/assign @liggitt

**Comment by dims** [comment]
This needs some more thought ... there are lot of references to `k8s.io/klog` in the vendor/ directories. i

```
[dims@dims-a02 17:08] ~/go/src/k8s.io/kubernetes/vendor ⟩ rg "k8s.io/klog" | grep "\.go"
k8s.io/gengo/parser/parse.go:	"k8s.io/klog"
k8s.io/gengo/generator/execute.go:	"k8s.io/klog"
k8s.io/gengo/generator/import_tracker.go:	"k8s.io/klog"
k8s.io/utils/trace/trace.go:	"k8s.io/klog"
k8s.io/utils/mount/mount_helper_common.go:	"k8s.io/klog"
k8s.io/utils/mount/fake_mounter.go:	"k8s.io/klog"
k8s.io/utils/mount/mount_linux.go:	"k8s.io/klog"
k8s.io/utils/mount/mount_helper_windows.go:	"k8s.io/klog"
k8s.io/utils/mount/mount_windows.go:	"k8s.io/klog"
k8s.io/utils/nsenter/nsenter.go:	"k8s.io/klog"
k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go:	"k8s.io/klog"
k8s.io/kube-openapi/pkg/generators/config.go:	"k8s.io/klog"
k8s.io/kube-openapi/pkg/generators/api_linter.go:	"k8s.io/klog"
k8s.io/kube-openapi/pkg/generators/openapi.go:	"k8s.io/klog"
k8s.io/repo-infra/cmd/kazel/kazel.go:	"k8s.io/klog"
github.com/google/cadvisor/metrics/prometheus.go:	"k8s.io/klog"
github.com/google/cadvisor/accelerators/nvidia.go:	"k8s.io/klog"
github.com/google/cadvisor/container/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/manager/container.go:	"k8s.io/klog"
github.com/google/cadvisor/manager/manager.go:	"k8s.io/klog"
github.com/google/cadvisor/zfs/watcher.go:	"k8s.io/klog"
github.com/google/cadvisor/machine/machine_libipmctl.go:	"k8s.io/klog"
github.com/google/cadvisor/machine/machine.go:	"k8s.io/klog"
github.com/google/cadvisor/machine/info.go:	"k8s.io/klog"
github.com/google/cadvisor/devicemapper/dmsetup_client.go:	"k8s.io/klog"
github.com/google/cadvisor/devicemapper/thin_pool_watcher.go:	"k8s.io/klog"
github.com/google/cadvisor/events/handler.go:	"k8s.io/klog"
github.com/google/cadvisor/devicemapper/thin_ls_client.go:	"k8s.io/klog"
github.com/google/cadvisor/fs/fs.go:	"k8s.io/klog"
k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:	"k8s.io/klog"
k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go:	"k8s.io/klog"
k8s.io/gengo/examples/import-boss/generators/import_restrict.go:	"k8s.io/klog"
k8s.io/gengo/examples/set-gen/generators/tags.go:	"k8s.io/klog"
k8s.io/gengo/examples/set-gen/generators/sets.go:	"k8s.io/klog"
sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go:	"k8s.io/klog"
sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go:	"k8s.io/klog"
github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go:	"k8s.io/klog"
github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/op.go:	"k8s.io/klog"
github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go:	"k8s.io/klog"
github.com/google/cadvisor/cache/memory/memory.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/cpuload/cpuload.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/sysinfo/sysinfo.go:	"k8s.io/klog"
github.com/google/cadvisor/info/v2/conversion.go:	"k8s.io/klog"
github.com/google/cadvisor/container/systemd/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/container/docker/handler.go:	"k8s.io/klog"
github.com/google/cadvisor/container/docker/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/container/docker/plugin.go:	"k8s.io/klog"
github.com/google/cadvisor/container/crio/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/container/containerd/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/container/crio/plugin.go:	"k8s.io/klog"
github.com/google/cadvisor/container/common/fsHandler.go:	"k8s.io/klog"
github.com/google/cadvisor/container/common/helpers.go:	"k8s.io/klog"
github.com/google/cadvisor/container/libcontainer/handler.go:	"k8s.io/klog"
github.com/google/cadvisor/container/libcontainer/helpers.go:	"k8s.io/klog"
github.com/google/cadvisor/container/raw/factory.go:	"k8s.io/klog"
github.com/google/cadvisor/container/raw/watcher.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/oomparser/oomparser.go:	"k8s.io/klog"
github.com/google/cadvisor/container/raw/handler.go:	"k8s.io/klog"
github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/filter/filter.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/cloudinfo/gce/gce.go:	"k8s.io/klog"
github.com/google/cadvisor/utils/cpuload/netlink/reader.go:	"k8s.io/klog"
github.com/google/cadvisor/container/systemd/install/install.go:	"k8s.io/klog"
github.com/google/cadvisor/container/docker/install/install.go:	"k8s.io/klog"
github.com/google/cadvisor/container/crio/install/install.go:	"k8s.io/klog"
github.com/google/cadvisor/container/containerd/install/install.go:	"k8s.io/klog"
```

**Comment by 44past4** [comment]
I have tried to find all places in the vendor/ directory which can be broken by upgrade to v2.
The main change in the API of v2 is the type of value which is returned from V() function.
It seems that only in the k8s.io/utils/trace/trace.go and github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go files we are using result of V() function as boolean.

**Comment by 44past4** [comment]
I wonder if for making migration of those vendored libraries to klog v2 we shouldn't add something like:
```go
type Verbose = bool 

func (v Verbose) Enabled() bool {
	return v.enabled
}
```
and change the result of V() function in klog v1 to `Verbose` instead of `bool`.
This should not break any existing code which is using klog but at the same time we could have a code in the vendor libraries which would be compatible with both klog v1 and klog v2.

**Comment by dims** [comment]
@yuzhiquan Please use v2.0.0-rc1 of klog, please patch up references for `if klog.V(x) {` to `if klog.V(x).Enabled() {` by hand in the vendored directories. 

please make sure there is no references to the older klog version in any of the go.mod/sum files and don't worry about failures in the dependencies CI job. 

As long as you get a green on `pull-kubernetes-e2e-gce` we can ask the scalability folks to try it out.

**Comment by BenTheElder** [comment]
> by hand in the vendored directories.

doesn't CI explicitly block manipulating vendored code so that you can't sneak in changes?

**Comment by dims** [comment]
yes, the statement was about getting the code in shape here so scalability folks can patch in the change in this PR and start a run. NOT for merging the change @BenTheElder

**Comment by dims** [comment]
we have had trouble in the past where the changes in klog ran into scalability issues, so trying to be careful here.

**Comment by yuzhiquan** [comment]
> @yuzhiquan Please use v2.0.0-rc1 of klog, please patch up references for `if klog.V(x) {` to `if klog.V(x).Enabled() {` by hand in the vendored directories.
> 

update version to v2.0.0-rc1, but not found any `if klog.V(x) {`  in `vendor/k8s.io/klog/v2`

> please make sure there is no references to the older klog version in any of the go.mod/sum files and don't worry about failures in the dependencies CI job.

Can not get this, i run update-vendor.sh, doesn't remove older version, so how to do this?

> As long as you get a green on `pull-kubernetes-e2e-gce` we can ask the scalability folks to try it out.

**Comment by 44past4** [comment]
> update version to v2.0.0-rc1, but not found any `if klog.V(x) {` in `vendor/k8s.io/klog/v2`

There is at least one occurence of klog.V() usage as boolean in `vendor/k8s.io/utils/trace/trace.go`:
```go
if stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) {
```

and in `github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go`:
```go
if klog.V(4) {
```

**Comment by yuzhiquan** [comment]
> @yuzhiquan:
> 
> > update version to v2.0.0-rc1, but not found any `if klog.V(x) {` in `vendor/k8s.io/klog/v2`
> 
> There is at least one occurence of klog.V() usage as boolean in `vendor/k8s.io/utils/trace/trace.go`:
> 
> ```go
> if stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) {
> ```
> 
> and in `github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go`:
> 
> ```go
> if klog.V(4) {
> ```

ok. update 2 files in vendor:
`vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go`
`vendor/k8s.io/utils/trace/trace.go`

**Comment by dims** [comment]
@yuzhiquan @44past4 @serathius  i’ve scripted the klog v2 hack it’s here https://gist.github.com/dims/ec84055b6354f2b2beea2196e28770d5 see https://github.com/dims/kubernetes/commits/hack-klog-v2 for the output

**Comment by yuzhiquan** [comment]
> @yuzhiquan @44past4 @serathius i’ve scripted the klog v2 hack it’s here https://gist.github.com/dims/ec84055b6354f2b2beea2196e28770d5 see https://github.com/dims/kubernetes/commits/hack-klog-v2 for the output

Nice, run script at k/k, so many files effected!

**Comment by yuzhiquan** [comment]
https://github.com/kubernetes/kubernetes/pull/90183 will fix this, this pr will close

**Pull request closed without merging**
