### PR TITLE
move formatAndMount and diskLooksUnformatted to mount_linux

### LINKED ISSUE #16729: Move formatAndMount and diskLooksUnformatted to mount_linux.go
The functions formatAndMount and diskLooksUnformatted execute linux commands and should be moved to mount_linux.go

### PR DESCRIPTION
**Pull request by ghost**
Fixes #16729

### CODE REVIEW

**Comment by swagiaal** [comment]
@saad-ali could you review this ?

**Comment by saad-ali** [comment]
Yes, I'll take a look today.

**Comment by saad-ali** [comment]
LGTM

**Comment by swagiaal** [comment]
@saad-ali thanks for reviewing!.. could you add lgtm tag ?

**Comment by swagiaal** [comment]
@k8s-bot test this please

**Comment by swagiaal** [comment]
@k8s-bot test this

**Pull request merged**
