### PR TITLE
Update to version 2.5.1 of the fluent-plugin-kubernetes_metadata_filter

### LINKED ISSUE #226: Error while watching pods: too old resource version with v2.4.5
Error while watching pods: too old resource version: 23630883 (23632006) (RuntimeError)

complete stacktrace
```
#<Thread:0x00007f53f192fb70@/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:43:in `rescue in set_up_pod_thread': undefined method `<' for nil:NilClass (NoMethodError)
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:38:in `set_up_pod_thread'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274:in `block in configure'
/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:133:in `block in process_pod_watcher_notices': Error while watching pods: too old resource version: 23630883 (23632006) (RuntimeError)
        from /usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/watch_stream.rb:28:in `block in each'
        from /usr/local/bundle/gems/http-4.4.1/lib/http/response/body.rb:37:in `each'
        from /usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/watch_stream.rb:25:in `each'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:110:in `process_pod_watcher_notices'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:40:in `set_up_pod_thread'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274:in `block in configure'
Unexpected error undefined method `<' for nil:NilClass
  /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:43:in `rescue in set_up_pod_thread'
  /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:38:in `set_up_pod_thread'
  /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274:in `block in configure'
```

### PR DESCRIPTION
**Pull request by Ghazgkull**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Updates to version 2.5.1 of the fluent-plugin-kubernetes_metadata_filter plugin. This version of the plugin contains a change to address the problem of unhandled "410 Gone" errors during the plugin's pod watch. (See https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/243)

**Which issue(s) this PR fixes**:

Fixes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/226

**Special notes for your reviewer**:

@monotek I originally reported this defect to the fluentd-elasticsearch helm chart a couple months back and you thankfully rolled back to an earlier version in order to avoid this bug: https://github.com/kiwigrid/helm-charts/issues/340#issuecomment-635920365

I jumped in and contributed a fix to the kubernetes metadata filter plugin which is now available in this release.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Ghazgkull** [comment]
I signed it

**Review by monotek — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Review by monotek — CHANGES_REQUESTED** [review]
Sorry, I've just recognized you did not raised the image version in the makefile.

**Comment by Ghazgkull** [comment]
@monotek Thanks for the heads up. Fixed.

**Review by monotek — APPROVED** [review]

**Comment by Ghazgkull** [comment]
Thanks, @monotek. This is my first contribution to this project so I’m not 100% sure of the PR process here. Is there someone I should reach out to now to request this change be merged?

**Comment by Ghazgkull** [comment]
The bots are saying this PR needs to be targetted to milestone v1.19. I'm assuming I don't have permission to do that myself?

/milestone v1.19

**Comment by Ghazgkull** [comment]
@DirectXMan12 @kawych Can I please request help applying the required milestone tag?

**Comment by Ghazgkull** [comment]
Apologies for all the chatter. I'm new to the project here and trying to navigate the process for the first time. As an outsider, I don't have permission to actually view project membership (https://github.com/orgs/kubernetes/teams/milestone-maintainers/members gives me a 404), so I'm left groping in the dark.

@coffeepac Looking through other PRs in this area, I see your approvals appearing before the bot adds the v1.19 milestone label. So I'm speculating that you might be the approval I need?

**Comment by Ghazgkull** [comment]
More noise... I realize now that the problem is that `/lgtm` was removed by the bot when I added the Makefile change it didn't get restored when @monotek re-approved the change.

**Comment by nikhita** [comment]
@monotek can you re-apply lgtm?

/assign @onlydole 
(release team lead) for applying the milestone

**Review by monotek — APPROVED** [review]
/lgtm
/approve

**Comment by monotek** [comment]
I've just pushed the image to quay.io/fluentd_elasticsearch/fluentd:v3.0.3 :)

**Pull request merged**
