### PR TITLE
[gce provider] More wrappers for alpha/beta backend service

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Sorry, some more wrapper functions I missed last time.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #NONE 

**Special notes for your reviewer**:
/assign @rramkumar1  

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
/assign @bowei 
for approval.

**Comment by m1093782566** [comment]
Let me try it...

/status approved-for-milestone

**Comment by MrHohn** [comment]
@m1093782566 Oh it works, thanks!

**Pull request merged**
