### PR TITLE
API Schema fix: container port keys

### PR DESCRIPTION
**Pull request by lavalamp**
The first of (likely) many such fixes.

As part of Apply, we're allowing more specificity into the schema, in particular, the ability for associative lists to have more than one key field.

This should be 100% backwards compatible (nothing pays attention to the new openapi schema annotations yet). As such, I'm sending it to master rather than the feature branch.

We will not remove the existing merge key annotations, even though they are largely redundant, so as not to change any existing behavior.

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/hold

(should make sure some other api approver at least sees this before it merges)

**Comment by liggitt** [comment]
> nothing pays attention to the new openapi schema annotations yet

do we have enough experience with using this attribute to be confident this is the structure we want? are the strings simple field names or jsonpath relative to the item? (i.e. can you have a list key that is not a top-level field in the item?)

**Comment by apelisse** [comment]
I suspect you can un-hold @lavalamp

**Comment by lavalamp** [comment]
/hold cancel

haha forgot I did that.

**Pull request merged**
