### PR TITLE
cleaning consts and BUILD on nodecontroller

### PR DESCRIPTION
**Pull request by yastij**
this is the last PR for #52356 

**What this PR does / why we need it**:

**Which issue this PR fixes**: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
```
I1020 17:27:55.288] Verifying hack/make-rules/../../hack/verify-bazel.sh
I1020 17:28:13.631] diff -Naupr /go/src/k8s.io/kubernetes/pkg/controller/node/BUILD /tmp/verify-bazel.GaN22X/go/src/k8s.io/kubernetes/pkg/controller/node/BUILD
I1020 17:28:13.632] --- /go/src/k8s.io/kubernetes/pkg/controller/node/BUILD	2017-10-20 17:21:50.756249104 +0000
I1020 17:28:13.632] +++ /tmp/verify-bazel.GaN22X/go/src/k8s.io/kubernetes/pkg/controller/node/BUILD	2017-10-20 17:28:06.552039554 +0000
I1020 17:28:13.632] @@ -60,7 +60,6 @@ go_library(
I1020 17:28:13.632]          "//pkg/util/node:go_default_library",
I1020 17:28:13.632]          "//pkg/util/system:go_default_library",
I1020 17:28:13.632]          "//pkg/util/taints:go_default_library",
I1020 17:28:13.633] -        "//pkg/util/version:go_default_library",
I1020 17:28:13.633]          "//plugin/pkg/scheduler/algorithm:go_default_library",
I1020 17:28:13.633]          "//vendor/github.com/golang/glog:go_default_library",
I1020 17:28:13.633]          "//vendor/github.com/prometheus/client_golang/prometheus:go_default_library",
I1020 17:28:13.633] 
I1020 17:28:13.633] Run ./hack/update-bazel.sh
I1020 17:28:14.387] FAILED   hack/make-rules/../../hack/verify-bazel.sh	19s
```

**Comment by yastij** [comment]
@cblecker - weird, I ran it. 

I'll have a look tomorrow

**Comment by gmarek** [comment]
Generally lgtm, assuming you can make the test pass.

**Comment by gmarek** [comment]
@yastij - is this PR still a thing? Do you want to clean it up or close it?

**Pull request closed without merging**
