### PR TITLE
Fix broken left nav bar links to api-references in k8s.io

### PR DESCRIPTION
**Pull request by RichieEscarez**
New .md files for building the new .html  api file  with jekyll - so header and nav are added

In the .html files,
-  manually changed color from  #ba3925 to #428BCB
- removed opening html  and footer tags
- set max-width to auto

Also added javascript to override max-width (this works in the html but does not display - WIP)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thank you @RichieEscarez! This is much better than what I did here:
https://github.com/GoogleCloudPlatform/kubernetes/tree/gh-pages/_tools/release_docs

if we can make the javascript to work, it will be perfect.

**Comment by RichieEscarez** [comment]
@caesarxuchao can you please LGTM this? Ive got another priority I need to work on and can come back to the width javascript override after.

**Comment by caesarxuchao** [comment]
It works on my local build. So LTGM.
FWIW, one other thing I noticed is that when I click api-reference in the left nav bar, the nav bar is scrolled up after loading and its font is larger. I think this is caused by the style defined in the definitions/operations html.

**Comment by vishh** [comment]
@RichieEscarez: This PR needs a rebase

**Comment by nikhiljindal** [comment]
IIUC, this will be overwritten, whenever we run _tools/import_master_docs.sh again.
We should be updating the tool to do such things.
cc @krousey @thockin

**Comment by caesarxuchao** [comment]
@nikhiljindal, you are right. This is just a temporary fix. We need to look for better way to generate the api-reference html files. The whole process is brittle now.

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11833 ran that tool again and essentially reverted this PR

**Comment by RichieEscarez** [comment]
I just opened #11850 that renames the .html files so our temporary fix does not get overwritten/overloaded in gh-pages when the script runs.

**Comment by RichieEscarez** [comment]
Also just opened #11851 to remove the .html files from the api-reference folder so that our temp fix works again. If the doc script gets run again, then per #11850, files with different names will be uploaded and this issue wont occur.

**Pull request merged**
