### PR TITLE
kube-controller-manager: add option for concurrent-job-syncs

### LINKED ISSUE #80397: Allow ConcurrentJobSyncs to be set for kube-controller-manager
**What would you like to be added**:
The ability to set `ConcurrentJobSyncs` for the kube-controller-manager at runtime.  It looks like the option exists in the code, but a mechanism is not available to set it via kops.  If I understand the code correctly, a flag needs to be added in order to be able to set the value using kops.

**Why is this needed**:
We want to shift a lot of our batch processing jobs from running directly on our CI servers to running as jobs on Kubernetes.  Unfortunately if too many jobs are launched on kubernetes, they begin to back up.  We've noticed up to a 10 minute delay between when the logs indicate that a job has finished and when the kubernetes API actually reflects the same on our small ~30 node cluster.

### PR DESCRIPTION
**Pull request by millerick**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
There are `--concurrent-[resource]-sync` options for most other resource types.  This addresses that gap.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/80397

**Special notes for your reviewer**:
It is not clear from documentation how to resolve this issue:
image

**Does this PR introduce a user-facing change?**:
```release-note
Adds `--concurrent-job-syncs` as an option for the kube-controller-manager
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
> Not mergeable. Must be in milestone v1.17.

this change cannot target 1.17, because it's a feature.


you can try asking in the #sig-api-machinery channel if this change is desired.

**Comment by millerick** [comment]
> this change cannot target 1.17, because it's a feature.

What branch should it merge into then?

**Comment by justaugustus** [comment]
@millerick --

> > this change cannot target 1.17, because it's a feature.
> 
> What branch should it merge into then?

This would merge to master (I've changed the base of the PR to `master`) and be considered a PR for 1.18. You'll need to do some cleanup on the local branch to fix the conflicts.

As @neolit123 mentioned, because this is a feature, we wouldn't consider it cherry pick to the 1.17 release branch. You can view our documentation on cherry picks for specific criteria and process: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md.

@kubernetes/sig-api-machinery-feature-requests -- for visibility

/milestone v1.18
/check-cla

**Comment by millerick** [comment]
Moving to https://github.com/kubernetes/kubernetes/pull/85815 because I accidentally deleted things...

**Pull request closed without merging**
