### PR TITLE
Automated cherry pick of #51302

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #51302 on release-1.7.

#51302: Block instance identity, block recursive=true

### CODE REVIEW

**Comment by ihmccreery** [comment]
Ref #8867.

**Comment by ihmccreery** [comment]
Ping @cjcullen @q-lee

**Comment by ihmccreery** [comment]
Ping @q-lee (CJ is on vacation).

**Comment by Q-Lee** [comment]
The config itself looks good, and has already been reviewed. I agree that this should be pulled into a patch.

**Comment by ihmccreery** [comment]
Re: kops, looks like a flake to me:

```
I0907 17:14:33.655] Installing collected packages: awscli, botocore, PyYAML, docutils, rsa, s3transfer, jmespath, python-dateutil, pyasn1, futures
I0907 17:14:34.887]   Running setup.py install for PyYAML
I0907 17:14:34.995]     checking if libyaml is compilable
I0907 17:14:34.996]     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
I0907 17:14:35.017]     build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
I0907 17:14:35.017]      #include <yaml.h>
I0907 17:14:35.017]                       ^
I0907 17:14:35.017]     compilation terminated.
I0907 17:14:35.052]     
I0907 17:14:35.052]     libyaml is not found or a compiler error: forcing --without-libyaml
```

**Comment by ihmccreery** [comment]
@wojtek-t for release approval

**Comment by ihmccreery** [comment]
Ping @wojtek-t for release approval.

**Comment by wojtek-t** [comment]
@ihmccreery - approved.

Next time please assign this to me - I have so many PRs where I'm cc-ed that I can easily miss such pings.

**Pull request merged**
