### PR TITLE
[WIP] Strip Heapster Setup

### PR DESCRIPTION
**Pull request by DirectXMan12**
This is a first-try at stripping out Heapster setup.  Unfortunately, due to the size and the potential to accidentally mess up non-PR tests, I don't think we should try and land this for 1.12.  We'll land it next release with the rest of the Heapster removal.

Basically, I went through and attempted to remove all of the Heapster setup code that I could obviously find.  I've probably missed some subtle bits here and there, and I've almost certainly yanked some GCE setup logic that will cause issues, so I'd appreciate if some of the GCE folks could take a look when they get the time.

This also removes references to Heapster in kubemark, so a review from that neck of the woods would be appreciated.

```release-note
Remove cluster installation utilities for Heapster.
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@kubernetes/sig-autoscaling-pr-reviews @kubernetes/sig-gcp-pr-reviews @kubernetes/sig-scalability-pr-reviews

**Comment by DirectXMan12** [comment]
/hold

just to be safe

**Comment by aleksandra-malinowska** [comment]
/sig instrumentation
cc @piosz

**Comment by shyamjvs** [comment]
> I've almost certainly yanked some GCE setup logic that will cause issues

I think this shouldn't be done for the reason I mentioned in https://github.com/kubernetes/kubernetes/pull/68090#discussion_r214525660.

**Pull request closed without merging**
