### PR TITLE
TEST/DO NOT REVIEW: kubelet: don't reset status for non-termianted pods

### PR DESCRIPTION
**Pull request by yujuhong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is still incorrect - you're clearing the container status which is what violates the invariant.  I think it's just that we need to "ensure the invariant".

**Comment by smarterclayton** [comment]
So something I had trouble finding - can we guarantee (or is it already guaranteed?) that before the sync loop starts a container it records status in the status manager?  An initial state?  If so, then terminate pod can safely check the status manager under a lock and any container not yet started can be assumed to have not started (which means status manager can omit a termination state for that container or properly set it to "successful").

**Comment by dims** [comment]
/close

please reopen if needed

**Pull request closed without merging**
