### PR TITLE
Enable parallel image pulls with docker 1.9.

### PR DESCRIPTION
**Pull request by aveshagarwal**
This PR changes SerializeImagePulls from bool to util.BoolFlag and works as follows:

If docker API version >=1.21 (docker 1.9) and a user has not provided SerializeImagePulls, it defaults to parallel image pulls.

If a user has provided SerializeImagePulls, then it respects the value of SerializeImagePulls irrespective of docker API version.

For docker API version < 1.21, it keeps the current behavior as it is.

For rkt, it changes the current behavior, as it defaults to parallel image pulls unless user has provided   SerializeImagePulls and set it to true.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by vishh** [comment]
@aveshagarwal: Image pulls had to be serialized to work around certain Aufs issues. Have those issue been fixed in docker 1.9?

In general, I'd prefer the distribution infrastructure to disable this flag when required, instead of making it a dynamic configuration inside kubelet.

**Comment by aveshagarwal** [comment]
@vishh based on https://github.com/docker/docker/issues/15283, it seems that aufs issues are fixed in docker 1.9

**Comment by yujuhong** [comment]
https://github.com/kubernetes/kubernetes/issues/10959#issuecomment-165976343 seems to indicate the opposite. Although it that was true, serializing image pulling didn't fix the problem...

**Comment by vishh** [comment]
@yujuhong: AFAIK there is more than one issue with Aufs. Serializing image pulls was just one of the band aids. 

@aveshagarwal: We have added support for docker v1.9.x yet because of performance issues. I'd like to run this PR through multiple e2e runs before accepting that v1.9 has the previously known issues fixed.

In general though, I'd prefer pushing the dynamic config outside of kubelet.

**Comment by ncdc** [comment]
@vishh I'm guessing you're saying you want this in the salt code instead of the Kubelet code? We were hoping to put it in the Kubelet so that OpenShift could take advantage of it as well. Otherwise, we'll have to modify both the salt code and the OpenShift installer to perform the same logic to check for Docker >= 1.9.

**Comment by aveshagarwal** [comment]
Rebased.

**Comment by vishh** [comment]
@ncdc: I'd prefer keeping this logic out of kubelet.

**Comment by derekwaynecarr** [comment]
I agree with @vishh that the kubelet can stay unchanged.

In OpenShift, we can just change the default similar to what we do for cpu-cfs-quota as seen here:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/node_config.go#L149

**Pull request closed without merging**
