### PR TITLE
AWS/GCE: Rework use of master name

### PR DESCRIPTION
**Pull request by zmerlynn**
- Add a pillar for `hostname` (because even if there's a good Salt function for it, I don't trust it to return the short hostname)
- Move `INITIAL_ETCD_CLUSTER` to just the GCE turn-up
- Remove `master_name`, which isn't needed

### CODE REVIEW

**Comment by zmerlynn** [comment]
This is still failing bring-up on AWS, haven't even checked GCE. Will diagnose later.

**Comment by zmerlynn** [comment]
Dropped the WIP, AWS bring-up works with these changes.

**Comment by zmerlynn** [comment]
I pushed a new version that will work after #30080 goes in. Please ignore test results until then (and since I'm really OOO today, someone can manually kick the bot when it does).

**Comment by jszczepkowski** [comment]
LGTM

**Pull request merged**
