### PR TITLE
Test Factory.PrintObject by fake command.

### LINKED ISSUE #32133: Test Factory.PrintObject by fake command
When working on the patch for #31702 , it found `cmd_test.go` mock `Factory` manually by function pointer which should be done by gomock; and add more unit test in factory_test.go.

cc @smarterclayton / @AdoHe / @pwittrock

### PR DESCRIPTION
**Pull request by k82cn**
fixes #32133

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32458)

### CODE REVIEW

**Comment by k82cn** [comment]
cc @AdoHe

**Comment by AdoHe** [comment]
given a quick look, why add fake command here?

**Comment by k82cn** [comment]
Avoid dependency on a special command, such as `NewCmdRun`; and also avoid the dependency of `NewApiFactory` because it's testing `Factory.PrintObject`.

**Comment by k82cn** [comment]
@AdoHe , any more comments?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32458#-:-KSK-wKFaxwSsh9ZW66N:b-xvj17q)*

**Comment by AdoHe** [comment]
IMO, I don't want to use fake command here, dependency on a special command should not be a problem. Also if we make `Factory` an interface, `NewAPIFactory` is just constructing a factory instance, and use it to test the `PrintObject` should be actually what we should do.

**Comment by k82cn** [comment]
en, OK. let me close this :).

**Pull request closed without merging**
