### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Merging master into feature-serverside-apply

### PR DESCRIPTION
**Pull request by apelisse**
Let's merge master in the feature-branch one more time...

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
@jennybuckley @kwiesmueller

**Comment by apelisse** [comment]
@BenTheElder Do you know what might be causing the error with the spellcheck? Seems specifically related to that merge. Thanks.

**Comment by BenTheElder** [comment]
@apelisse that's probably because we switched to a new version of the job for master only, I'll tweak the config to invert the branch selection so that the master version blacklists old releases rather than whitelisting the master branch.

**Pull request merged**
