### PR TITLE
Move test-only volume files to test-only volume package

### PR DESCRIPTION
**Pull request by timstclair**
For https://github.com/kubernetes/kubernetes/issues/21114

### CODE REVIEW

**Comment by saad-ali** [comment]
Looks like you missed a couple of renames:
```
# k8s.io/kubernetes/test/integration
_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:55: undefined: volume.NewFakeVolumeHost
_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:57: undefined: volume.FakeVolumePlugin
FAIL	k8s.io/kubernetes/test/integration [build failed]
```

**Comment by timstclair** [comment]
Oops, missed the `-tags integration` flag. Fixed.

**Comment by saad-ali** [comment]
LGTM. Could you please rebase, then I'll add the LGTM label

**Comment by timstclair** [comment]
Rebased.

**Pull request merged**
