### PR TITLE
Only log requests for configured consumptions in ResourceConsumer

### PR DESCRIPTION
**Pull request by pbeschetnov**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently in e2e tests the ResourceConsumer sends requests for all resource types, even those that were not set. This pollutes the logs with empty consumption requests.

Example:
```
Apr  1 05:05:17.594: INFO: RC rc: sending request to consume 0 of custom metric QPS
Apr  1 05:05:17.594: INFO: ConsumeCustomMetric URL: {https   35.222.52.255 /api/v1/namespaces/horizontal-pod-autoscaling-475/services/rc-ctrl/proxy/BumpMetric  false delta=0&durationSec=30&metric=QPS&requestSizeMetrics=10  }
Apr  1 05:05:17.602: INFO: RC rc: sending request to consume 0 MB
Apr  1 05:05:17.603: INFO: ConsumeMem URL: {https   35.222.52.255 /api/v1/namespaces/horizontal-pod-autoscaling-475/services/rc-ctrl/proxy/ConsumeMem  false durationSec=30&megabytes=0&requestSizeMegabytes=100  }
```

We can reduce the unnecessary log lines by not printing the consumptions that are not being initialized and updated.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pbetkier — APPROVED** [review]
Looks good to me!

Could you verify that the logs are as expected by running an HPA test with these changes?

**Comment by pbeschetnov** [comment]
Sure, here is an example:
```
Apr  4 11:32:22.180: INFO: RC rc-light: consume 50 millicores in total
Apr  4 11:32:22.180: INFO: RC rc-light: setting consumption to 50 millicores in total
Apr  4 11:32:22.180: INFO: RC rc-light: sending request to consume 50 millicores
Apr  4 11:32:22.180: INFO: ConsumeCPU URL: {https   146.148.74.197 /api/v1/namespaces/horizontal-pod-
autoscaling-6253/services/rc-light-ctrl/proxy/ConsumeCPU  false durationSec=30&millicores=50&requestS
izeMillicores=100  }
Apr  4 11:32:22.181: INFO: RC rc-light: consume 0 MB in total
Apr  4 11:32:22.181: INFO: RC rc-light: disabling mem consumption
Apr  4 11:32:22.181: INFO: RC rc-light: consume custom metric 0 in total
Apr  4 11:32:22.181: INFO: RC rc-light: disabling consumption of custom metric QPS
Apr  4 11:32:22.441: INFO: waiting for 1 replicas (current: 2)
Apr  4 11:32:42.551: INFO: waiting for 1 replicas (current: 2)
Apr  4 11:32:52.342: INFO: RC rc-light: sending request to consume 50 millicores
Apr  4 11:32:52.342: INFO: ConsumeCPU URL: {https   146.148.74.197 /api/v1/namespaces/horizontal-pod-
autoscaling-6253/services/rc-light-ctrl/proxy/ConsumeCPU  false durationSec=30&millicores=50&requestS
izeMillicores=100  }
Apr  4 11:33:02.553: INFO: waiting for 1 replicas (current: 2)
Apr  4 11:33:22.467: INFO: RC rc-light: sending request to consume 50 millicores
Apr  4 11:33:22.467: INFO: ConsumeCPU URL: {https   146.148.74.197 /api/v1/namespaces/horizontal-pod-
autoscaling-6253/services/rc-light-ctrl/proxy/ConsumeCPU  false durationSec=30&millicores=50&requestS
izeMillicores=100  }
...
Apr  4 11:37:42.681: INFO: RC rc-light: stopping metric consumer
Apr  4 11:37:42.681: INFO: RC rc-light: stopping mem consumer
Apr  4 11:37:42.681: INFO: RC rc-light: stopping CPU consumer
```

**Comment by oomichi** [comment]
lgtm, let's run tests.

/triage accepted
/ok-to-test
/cc @oomichi

**Pull request merged**
