### PR TITLE
Log the returned error for TestChangeCRD

### PR DESCRIPTION
**Pull request by liggitt**
Debugging for https://github.com/kubernetes/kubernetes/issues/116364

/kind flake

```release-note
NONE
```

### CODE REVIEW

**Comment by tkashem** [comment]
from the error
```
E0308 16:49:00.372462   90441 watcher.go:219] watch chan error: rpc error: code = Canceled desc = context canceled
    change_test.go:145: unexpected watch event: ERROR, {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: rpc error: code = Canceled desc = context canceled","reason":"InternalError","details":{"causes":[{"message":"rpc error: code = Canceled desc = context canceled"}]},"code":500}
```

context canceled is coming from here?
https://github.com/kubernetes/kubernetes/blob/713ded736824d669d9fae9ac4a29b1ec18d66446/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L219

exactly 8 of them

**Comment by liggitt** [comment]
cc @wojtek-t @p0lyn0mial @smarterclayton @sttts @tkashem for visibility in case any of you know of changes in the context / apiserver / watch stack that could explain cancellation errors coming back from watches where they didn't previously ... this error has spiked in the last week or so

**Comment by wojtek-t** [comment]
Hmm - https://github.com/kubernetes/kubernetes/pull/110960 is highly unlikely to cause changes resulting in context being cancelled. Especially, given that as @tkashem wrote above this error seems to be coming from etcd3 watcher, which we didn't really touch there...
[Although that was also my first thought...]

BTW - if we're getting this error returned to the user, given it's coming from etcd3 watcher - doesn't that even mean that watchcache is disabled in this test? @liggitt ^^

**Comment by wojtek-t** [comment]
Looking into these logs, my hypothesis is (due to logs timing), that those errors are happening somewhere around server shutdown...

**Comment by liggitt** [comment]
> BTW - if we're getting this error returned to the user, given it's coming from etcd3 watcher - doesn't that even mean that watchcache is disabled in this test? @liggitt ^^

or the watch cache wasn't ready, or there was something about the request (like it watching without a resourceVersion specified) which bypassed the watch cache

**Comment by liggitt** [comment]
> Looking into these logs, my hypothesis is (due to logs timing), that those errors are happening somewhere around server shutdown...

the error is happening after about 5 seconds of the test running, which means we're ~here:

https://github.com/kubernetes/kubernetes/blob/8b413d224a9422a1163f3779055a1aad21794813/staging/src/k8s.io/apiextensions-apiserver/test/integration/change_test.go#L151-L168

stopCh doesn't shut down the server, it just makes the watch loops return on their next iteration

we're not seeing `timed out waiting for clients to complete` messages in the test failure, and the errors come from inside the loop, so we didn't pass `<-drained`, so I don't see a way for us to have gotten to server shutdown

It really seems like a context got confused somewhere in the server handler stack and a cancel from one spot is bleeding across and affecting other requests

**Comment by wojtek-t** [comment]
Heh...
Indeed - the test is watching withour setting RV:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/test/integration/change_test.go#L133

So I have a strong hypothesis, that the changes that we observe here are due to this PR:
https://github.com/kubernetes/kubernetes/pull/115096

@MadhavJivrajani - - FYI

Assuming this is true, I would be willing to say that it seems like a test issue...

**Comment by liggitt** [comment]
hmm... is it correct for a watch to return an Error event when the request context is canceled? I would have expected the watch to just close

**Comment by wojtek-t** [comment]
I guess you're right.
I guess the error seems to be coming from:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L249
and we're trying to catch that later:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L165

but this log line:
```
E0308 16:49:00.372181   90441 watcher.go:219] watch chan error: rpc error: code = Canceled desc = context canceled
```

suggest that this `cancelled` error is wrapped in some rpc code, which may mean we're not handling it correctly?

**Comment by liggitt** [comment]
yeah, I think this check is not working correctly:

https://github.com/kubernetes/kubernetes/blob/8b413d224a9422a1163f3779055a1aad21794813/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L164-L175

**Comment by wojtek-t** [comment]
Yeah. And as I wrote above, https://github.com/kubernetes/kubernetes/pull/115096 was the trigger why we only started seeing them recently...

**Comment by liggitt** [comment]
> Yeah. And as I wrote above, #115096 was the trigger why we only started seeing them recently...

ack, fix for the cancellation error recognition in https://github.com/kubernetes/kubernetes/pull/116393

**Pull request closed without merging**
