### PR TITLE
Fix display of CHANGELOG-1.19.md by inserting newline

### PR DESCRIPTION
**Pull request by takotakot**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Documentation small fix.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by takotakot** [comment]
I've just signed a CLA as an individual. (But the email address is different from the one used with GitHub because of avoiding spams.)

I'm sorry that I can't get the right meaning of:
> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
.

**Comment by takotakot** [comment]
I signed it

**Comment by takotakot** [comment]
I signed it

**Review by Damans227 — APPROVED** [review]

**Comment by takotakot** [comment]
@cici37 Do you have a time to review?

**Comment by dims** [comment]
@kubernetes/sig-release-leads wanna take a peek? small PR that just adds a new line in a changelog

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Pull request merged**
