### PR TITLE
Update elasticsearch_discovery.go

### PR DESCRIPTION
**Pull request by mulloymorrow**
Doesn't build. Too many arguments

### CODE REVIEW

**Comment by mulloymorrow** [comment]
I signed It!

**Comment by mikedanese** [comment]
Is your gopath setup correctly? This looks correct. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/pods.go#L33. Can you paste the command you are using to build?

**Comment by mulloymorrow** [comment]
I was just running `make`. The default should be `make all`. 

If we rearrange the makefile, make works by default: 

```make
.PHONY: elasticsearch_discovery build push all

TAG = 1.0
elasticsearch_discovery:
	go build elasticsearch_discovery.go

build:
	docker build -t kubernetes/elasticsearch:$(TAG) .

push:
	docker push kubernetes/elasticsearch:$(TAG)

all:	elasticsearch_discovery build push 
```

**Comment by mulloymorrow** [comment]
`FROM kubernetes/elasticsearch:1.0`. Done!

**Pull request closed without merging**
