### PR TITLE
FEATURE BRANCH ONLY: Add apelisse and jennybuckley to top-level approvers

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/approve

fyi @ixdy @BenTheElder 

This is an attempt to make it easier for Jenny & Antoine to make progress when I'm not available.

**Comment by apelisse** [comment]
Can someone lgtm?

**Comment by BenTheElder** [comment]
It would be great if you all could write up something regarding friction with feature branches, I think this is something other people are interested in looking at solving.

**Pull request merged**
