### PR TITLE
feat: enable kubectl to print objects in CSV format

### LINKED ISSUE #995: [request] add -o csv for easy exporting of resources to spreadsheets.
**What would you like to be added**: 
I would like to be able to use the output flag to specify csv format when listing resources. For example:
`kubectl get pods -o csv` would output the current pods in a CSV format.
An example of proper CSV format could be 

```
NAME    ,READY   ,STATUS    ,RESTARTS   ,AGE
Inky    ,1/1     ,Running   ,3          ,1d10h
Blinky  ,1/1     ,Running   ,132        ,2d11h
Pinky   ,1/1     ,Running   ,2          ,3d12h
Clyde   ,1/1     ,Running   ,0          ,196d13h
```
Which in monospace would not only look like properly formatted CSV, but it would also be properly formatted CSV.

This flag would be valid on any resource that is 'get'-able.

**Why is this needed**:

Not only is this an easy add, as it would be very useful in automation and reporting.  Personally, I would be able to perform cluster analysis much faster with this, using something akin to  

`kubectl get pods -o csv > myreport.csv`

where I could then paste in formulas in excel and crunch numbers with my own parser.

Thanks for the consideration!

### PR DESCRIPTION
**Pull request by knight42**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add CSV writer which is able to output objects in CSV format.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubectl/issues/995

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubectl-get is able to print objects in CSV format now.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Bjohnson131** [comment]
Big Thank you for taking this on!

**Review by eddiezane — APPROVED** [review]
This LGTM! Thanks for taking this one on.

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
Thanks for your PR, but I'm not convinced about the overall value of CVS output in here. The implementation looks legit, but I'm worried that kubectl won't get much value from this kind of output. I'd prefer to learn more about the potential user base first before making a decision to include new printer.

**Comment by Bjohnson131** [comment]
> /hold
> Thanks for your PR, but I'm not convinced about the overall value of CVS output in here. The implementation looks legit, but I'm worried that kubectl won't get much value from this kind of output. I'd prefer to learn more about the potential user base first before making a decision to include new printer.

why

**Comment by Bjohnson131** [comment]
Hey @soltysh  if you have a moment, I think the issue has garnered a bit more attention.
https://github.com/kubernetes/kubectl/issues/995

It would also be a feature which wouldn't accrue much debt in the future, as the CSV format hasn't changed for nearly half a century.

**Pull request closed without merging**
