### PR TITLE
Automated cherry pick of #54971: Rev Azure SDK to v11.1.1

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #54971 on release-1.8.

#54971: Rev Azure SDK to v11.1.1

### CODE REVIEW

**Comment by feiskyer** [comment]
This cherry pick is required to fix following errors:

> Warning CreatingLoadBalancerFailed 3m (x12 over 33m) service-controller Error creating load balancer (will retry): Failed to ensure load balancer for service default/appp-lb: network.SecurityGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SecurityRuleParametersMissing" Message="Required security rule parameters are missing for security rule with Id: /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/MC_group_cluster_westeurope/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-xxxxxxxx-nsg/securityRules/a9e85febbfbabxxxxxxxxxxxxxxxx-TCP-80-Internet. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups." Details=[]

Refer https://github.com/Azure/AKS/issues/199 for more details for this issue.

/assign @brendanburns

**Comment by jpbetz** [comment]
@feiskyer are there corresponding CP requests for 1.9 and 1.10?

**Comment by feiskyer** [comment]
@jpbetz  this cherry pick is only required for 1.8. There is no such issues on 1.9 and 1.10.

**Comment by jpbetz** [comment]
@feiskyer I'm uncomfortable with this cherry pick. This code change delta of this PR is large and appears to contain substantial amounts of new code. Historically, a major source of regressions on stable kubernetes release branches has been due to a large set of code changes pulled in via a dependency.  I also don't understand why this was committed to master for the 1.11 release and needs to be in the 1.8 release, but not 1.9 and 1.10.

My recommendation is that we let this code bake on master for the 1.11 release and do not attempt to cherry pick it to the stable kubernetes release branches.  Please escalate on your side if you feel that is the incorrect decision.

**Comment by feiskyer** [comment]
@jpbetz This is a bug fix for Azure SDK in 1.8 release, see [here](https://github.com/kubernetes/kubernetes/pull/62249#issuecomment-379530452). 

I didn't cherry pick a master PR because code base has changed a lot and too many codes need to rewrite. While in this PR,only one file is changed outside of vendors.

**Comment by jpbetz** [comment]
> I didn't cherry pick a master PR because code base has changed a lot and too many codes need to rewrite. While in this PR,only one file is changed outside of vendors.

Hold on. The cherrypick is from master (https://github.com/kubernetes/kubernetes/pull/54971), but it was merged on Nov 6, 2017 which means it was originally released in 1.9. So what we're really doing here is backporting code that was originally included in 1.9 back to 1.8.  That was not at all clear from the above discussion.

**Comment by feiskyer** [comment]
> So what we're really doing here is backporting code that was originally included in 1.9 back to 1.8. That was not at all clear from the above discussion.

@jpbetz Yep, this is what I'm trying to do. There are also other vendor updates PR in master branch, but as I said, such PR requires a lot of code rewrites. Do you think this make sense?

**Comment by jpbetz** [comment]
@feiskyer Here's my current understanding. Please correct me if any of this is wrong:

- Currently
  - k8s 1.8 vendors Azure SDK v10.0
  - k8s 1.9 vendors Azure SDK v11.1
  - k8s 1.10 vendors Azure SDK v12.4
- The purpose of this cherry pick is to fix the "Missing security rule parameters while deploying a LoadBalancer" issue (https://github.com/Azure/AKS/issues/199)
- The is fixed in Azure SDK v11.1 by adding support for `SourceAddressPrefixes` (https://github.com/Azure/AKS/issues/199#issuecomment-379528839)
- The proposed fix is to bump k8s 1.8 to Azure SDK v11.1 which adds 18,687 lines of code and removes −3,045 lines of code across 147 files.

Is this correct?  If so, let's instead backport just the fixes needed to resolve this issue in Azure SDK to v10, release a new patch version of v10, and vendor that in to k8s 1.8.  Sound reasonable?

**Comment by feiskyer** [comment]
> Is this correct? If so, let's instead backport just the fixes needed to resolve this issue to Azure SDK v10, release a new patch version of v10, and vendor that in to k8s 1.8. Sound reasonable?

@jpbetz Correct and thanks of advice. Let me check whether it possible to cut a new v10 release in Azure SDK.

**Comment by feiskyer** [comment]
@jpbetz As said [here](https://github.com/Azure/azure-sdk-for-go/issues/1586#issuecomment-382054019), it is not possible to release a new Azure SDK v10.X now:

> Sorry we won't be releasing a patch for a pre-released SDK version (to be frank I don't know that we could even build it given all the refactoring that's happened in the specs repo).

Could we use v11 instead (as what have done in this PR)?

**Comment by jpbetz** [comment]
@feiskyer No. The change is far to large. k8s cherrypicks must be limited to targeted fixes for stability reasons.

**Comment by feiskyer** [comment]
@jpbetz OK, thanks. So we can only leave this as a known issue for v1.8.X now.

cc @brendandburns @khenidak

**Comment by jpbetz** [comment]
Ok. Closing this.  If a Azure SDK v10.x is ever released to fix this please feel free to submit a new cherry pick request to backport it to 1.8 that way.

**Pull request closed without merging**
