### PR TITLE
Supplement unit test for kubectl logs

### PR DESCRIPTION
**Pull request by YuxiJin-tobeyjin**
**What this PR does / why we need it**:
Supplement unit test for kubectl logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE

```

### CODE REVIEW

**Comment by YuxiJin-tobeyjin** [comment]
cc @zhangxiaoyu-zidif

**Comment by YuxiJin-tobeyjin** [comment]
ping @pwittrock  PTAL.
Many thanks.

**Comment by pwittrock** [comment]
@YuxiJin-tobeyjin Thanks.  Sorry I am OOO for a few weeks.  Re-assigned.

**Comment by YuxiJin-tobeyjin** [comment]
/assign @liggitt 
Need approval from sig-cli-maintainers,ping @liggitt PTAL.
Many thanks.

**Comment by liggitt** [comment]
In general, exact human-readable error message comparisons make for fragile unit tests. Any way to check for errors but avoid duplicating/hard-coding copies of the error strings?

**Comment by apelisse** [comment]
I don't disagree with @liggitt, maybe in the defense of OP:
- That's how tests in this file are written already,
- More tests is *usually* a good thing.

**Comment by YuxiJin-tobeyjin** [comment]
@liggitt Sir,I think this is kind of UT test style,most of the UT tests are using "contain" or "Deepequal" to verify the test results.
My new added tests are written following this style and meant to cover the cases that were not been covered before.
WDYT @liggitt 
Many thanks.

**Comment by YuxiJin-tobeyjin** [comment]
@apelisse 
Thank you. I totally agree with you.

**Comment by YuxiJin-tobeyjin** [comment]
@liggitt WDYT
I just start my journey on writing K8S UT. Your advice will give me great encouragement.

**Comment by YuxiJin-tobeyjin** [comment]
ping @liggitt

**Pull request merged**
