### PR TITLE
Mark startupProbe test as NodeAlphaFeature and fix podClient

### LINKED ISSUE #82747: [Failing Test] [sig-node] startup_probe_test.go
**Which jobs are failing**:
ci-kubernetes-node-kubelet-serial

**Which test(s) are failing**:
StartupProbe [Serial] [Disruptive] [NodeFeature:StartupProbe]

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:
```
It's not enough to set this flag in the kubelet because the apiserver needs it too
```
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by matthyx**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #82747

**Special notes for your reviewer**:
Reimplementation of https://github.com/kubernetes/kubernetes/pull/82748

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/retest

once this merges, can you pick to release-1.16 to clean up CI there?

**Comment by odinuge** [comment]
Nice, thanks for the patch @matthyx! :smile:  

> @liggitt: once this merges, can you pick to release-1.16 to clean up CI there?

Fixing in 1.16 would be ok, but currently we only run the serial kubelet tests in master, ref [test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L244), but maybe we should run for releases too?

We do have a `ci-kubernetes-node-kubelet-alpha` running in master for tests marked with `NodeAlphaFeature`, but since this is also marked as `Serial`, no ci (afaik) will therefore run these tests. Should we maybe create a new `ci-kubernetes-node-kubelet-alpha-serial` job to run against alpha features like this one?


Any thoughts @mattjmcnaughton @derekwaynecarr?

**Comment by matthyx** [comment]
@odinuge maybe it's a mistake from me to put `Serial`... what the real meaning of it?

**Comment by odinuge** [comment]
`[Serial]` means that the tests cannot be executed in parallell, and therefore have to be executed in series. A simple example is when the tests are modifying kernel parameters or other system related things that will interrupt other tests (eg. when testing pod eveiction during DiskPressure).

I am not familiar with this test or the code it is testing, but from the comment `These tests are located here as they require tempSetCurrentKubeletConfig to enable the feature gate for startupProbe. Once the feature gate has been removed, these tests should come back to test/e2e/common/container_probe.go.` it looks like it is required. https://github.com/kubernetes/kubernetes/pull/83570/files#diff-22a96a726c53dcd89c707a9bd7c245c5R48. I am pretty sure that `tempSetCurrentKubeletConfig` will restart kubelet before/after each test.

**Comment by matthyx** [comment]
Yes, it's definitely needed... let's see what @mattjmcnaughton @derekwaynecarr have to say about it.

**Comment by matthyx** [comment]
> Should we maybe create a new `ci-kubernetes-node-kubelet-alpha-serial` job to run against alpha features like this one?
> 
> Any thoughts @mattjmcnaughton @derekwaynecarr?

/cc @mattjmcnaughton @derekwaynecarr

**Comment by mattjmcnaughton** [comment]
Defer to @derekwaynecarr here :)

**Comment by matthyx** [comment]
@odinuge who else could I poke to have a job that will run this test?
Also I would love to see some load tests with that feature enabled before pushing it to beta...

**Pull request merged**
