### PR TITLE
Remove unnecessary loop.

### PR DESCRIPTION
**Pull request by roberthbailey**
This loop is checking the same file without modifying the file between checks. If it fails the first time, it just delays exiting for an extra 100 or so seconds.

### CODE REVIEW

**Comment by lavalamp** [comment]
That is a super weird bit of code... (before your change, I mean)

Was the intention that it actually re-get the file before each check? Would that make more sense than this fix?

**Comment by satnam6502** [comment]
I ended up writing it this way because the minions file (in general) grows. For a large cluster as the minions come up they get added to this file. The loop does re-check the file with the grep command.

**Comment by satnam6502** [comment]
But this check is now done earlier, so this loop is not needed anymore at this point.

**Comment by lavalamp** [comment]
Ah, thanks for explanation!

**Pull request merged**
