### PR TITLE
Increase expected fluent CPU usage

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #26185

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by gmarek** [comment]
We should really find the thing that caused this, not just bump the threshold, which was perfectly happy for the last half a year.

**Comment by wojtek-t** [comment]
Readding lgtm - release-note-noe was missing.

**Comment by wojtek-t** [comment]
Merging manually to unblock the merge queue.

**Pull request merged**
