### PR TITLE
[DRA] Add RUNTIME_CONFIG="resource.k8s.io/v1alpha1"

### PR DESCRIPTION
**Pull request by moshe010**
This flag is required to enable the DRA resource api

Signed-off-by: Moshe Levi <moshele@nvidia.com>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update how to enable DRA with local-up-cluster.sh
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by bart0sh — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
@kubernetes/release-managers : as in PR https://github.com/kubernetes/kubernetes/pull/113976 this is a non-risk fix for documentation of the new dynamic resource allocation feature. Would be good to have in 1.26.

**Review by cpanato — APPROVED** [review]
/lgtm
/triage accepted
/priority important-soon
/milestone v1.26

**Pull request merged**
