### PR TITLE
Remove Rancher Credential Provider from upstream kubernetes

### LINKED ISSUE #77098: Remove Rancher Credential Provider from upstream kubernetes
Rancher 1.6 is using it still. Current Rancher version is 2.2.x per @alena1108. So we could possibly remove it from upstream and let the rancher folks maintain it in their own tree.

We don't need to carry the extra weight as mentioned in https://github.com/kubernetes/kubernetes/issues/76506

Since this is useful only in the rancher environment, we don't really need the traditional deprecation period. Right @alena1108?

### PR DESCRIPTION
**Pull request by dims**
This is useful only in rancher environment, they are using this in a
very old branch (1.6), they are currently at 2.2.x. There is just no
point in us carrying this code as this is not useful to anyone else
outside of the rancher environment. Let us please remove this code from
upstream.

Change-Id: I5196d0edd79a7809c3a04e6028ddbd01063f224b

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #77098

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Rancher credential provider has now been removed
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @wlan0 
cc @alena1108 
/sig cloud-provider
/area cloud-provider

**Comment by liggitt** [comment]
do we have an explicit ack that this is unused in current rancher deployments?

**Comment by dims** [comment]
@liggitt yes in https://github.com/kubernetes/kubernetes/issues/77098#issuecomment-486845685

**Comment by liggitt** [comment]
I found it a little hard to tell from that if that was an official ack. Are we certain this is unused?

**Comment by alena1108** [comment]
@liggitt I work for Rancher, and this code leverages an older - 1.x - version of the product. We are planning to maintain it for some time, but it's ok to remove the Rancher credential provider code from the upstream k8s. We can maintain it in our own k8s fork.

**Comment by liggitt** [comment]
/lgtm
/approve
per https://github.com/kubernetes/kubernetes/pull/77099#issuecomment-486866401

**Pull request merged**
