### PR TITLE
enable psp by default

### PR DESCRIPTION
**Pull request by pweil-**
Enable the extensions/psp resource by default

**Release note**:
```release-note
PodSecurityPolicy resource is now enabled by default in the extensions API group.
```

### CODE REVIEW

**Comment by pweil-** [comment]
@liggitt

**Comment by liggitt** [comment]
LGTM. Most impressive ratio of changed lines to changed generated lines. 

Unrelatedly, do we have a destination API group in mind for PSP?

**Comment by mikedanese** [comment]
@cjcullen

**Comment by mikedanese** [comment]
Can you please add a release note for this?

**Comment by pweil-** [comment]
> Unrelatedly, do we have a destination API group in mind for PSP?

I think the policy group is probably the best fit with the runner up being authorization.

**Comment by pweil-** [comment]
> Can you please add a release note for this?

added

**Comment by kargakis** [comment]
@php-coder

**Comment by mikedanese** [comment]
@kubernetes/api-approvers

**Comment by kargakis** [comment]
> I think the policy group is probably the best fit with the runner up being authorization.

+1 for the policy group

**Comment by mikedanese** [comment]
Are we planning to make that move before 1.6 is cut?

**Comment by pweil-** [comment]
> Are we planning to make that move before 1.6 is cut?

no

**Comment by mikedanese** [comment]
What compatibility guarantee are we committing as we turn this on by default? If we move this to policy will we break users?

**Comment by pweil-** [comment]
PSP is still considered beta and [subject to change](https://kubernetes.io/docs/api/).  It was not, however, enabled by default like the guidelines say.

**Pull request merged**
