### PR TITLE
use underscode instead of hyphen while defined function in cherry_pick_pull.sh

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
Signed-off-by: wuyingjun <71485611@qq.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
I met a problem when I used sh but not bash executing check_pick_pull.sh
image
In the shell command language, a word consisting solely of underscores, digits, and alphabetics from the portable character set. The first character of a name is not a digit.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
adapt for sh execution cherry_pick_pull.sh
```
/sig instrumentation
/sig architecture
/sig cli
/sig contributor-experience

### CODE REVIEW

**Comment by aojea** [comment]
the scripts expect `bash`, no?
```
#!/usr/bin/env bash
```

**Comment by wuyingjun-lucky** [comment]
> the scripts expect `bash`, no?
> 
> ```
> #!/usr/bin/env bash
> ```

Yes 
 But why not adapt sh  
and  I search others functions defined in the hack dir just like ‘ function grab_profiles_from_component ’ defined in 
 (https://github.com/kubernetes/kubernetes/blob/master/hack/grab-profiles.sh)
and in the shell command language, a word consisting solely of underscores, digits, and alphabetics from the portable character set. The first character of a name is not a digit.

**Comment by dims** [comment]
sorry wont-fix.

**Pull request closed without merging**
