### PR TITLE
Fix error in i18n package usage examples

### PR DESCRIPTION
**Pull request by y1hao**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix an error in the i18n package documentation for the usage examples.

#### Special notes for your reviewer:

I read about [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). But I think this is still worth it since it is not a spelling mistake but a wrong usage example.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mpuckett159 — APPROVED** [review]

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
