### PR TITLE
Fix crash in kubectl drain

### LINKED ISSUE #83794: kubectl drain can crash if apiserver connection breaks during delete/evict
**What happened**:
kubectl drain crashed with panic when apiserver connection disappeared
while there were pods that couldn't be evicted/deleted
(sorry, the problem is a bit hard to reproduce and the log was lost)

**What you expected to happen**:
kubectl drain should exit with a proper error message

**How to reproduce it (as minimally and precisely as possible)**:
Try kubectl drain multiple times, interrupting the connection during
eviction/deletion

**Anything else we need to know?**:
The `pendingList` here can be `nil` in case if `GetPodsForDeletion()` returns an error,
and `pendingList.Pods()` will panic upon accessing `.items`:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/drain/drain.go#L332-L335
This causes the c

**Environment**:
- Kubernetes version (use `kubectl version`):
The problem is present as of 37226f8e8306475895d7e68eb52c57e57f00ee28 but is also present in earlier versions

(I have a fix for this bug)

### PR DESCRIPTION
**Pull request by ivan4th**
When there's a pod that can't be evicted/deleted, and apiserver
connection breaks at a wrong moment, kubectl can panic due
to nil pointer dereference. This PR also improves drain tests
to avoid confusing panics with fatal errors.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
kubectl drain can crash if apiserver becomes unavailable at a wrong moment.

**Which issue(s) this PR fixes**:

Fixes #83794

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
LGTM
/priority important-longterm
/assign @apelisse

**Comment by ivan4th** [comment]
oops, did one wrong push, sorry (reverted to the initial state as it was during @neolit123 comment)

**Comment by ivan4th** [comment]
Folks... could you review this one please?..

**Pull request merged**
