### PR TITLE
rkt: Add pre-stop lifecycle hooks for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
When a pod is being terminated, the pre-stop hooks of all the containers
will be run before the containers are stopped.

cc @yujuhong @Random-Liu @sjpotter

### CODE REVIEW

**Comment by yifan-gu** [comment]
@k8s-bot test this please, flake #23451

**Comment by yifan-gu** [comment]
Replying LGTM after rebase

**Comment by yifan-gu** [comment]
@yujuhong Hmm, not sure why the test is failing. I didn't find the failing test is reported as a flake anywhere.

Also, it runs correctly on my machine.

**Comment by yujuhong** [comment]
@k8s-bot unit test this. ISSUE: #23682

**Comment by yifan-gu** [comment]
Re-apply lgtm, added release-note-none label.

**Comment by yifan-gu** [comment]
Tests are passing, the test scripts fails though.
@k8s-bot test this please

**Comment by yifan-gu** [comment]
Re-applying LGTM after rebase.

**Pull request merged**
