### PR TITLE
[WIP]Criproxy for e2enode

### PR DESCRIPTION
**Pull request by pacoxu**
only for testing 
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial
/test pull-kubernetes-node-e2e-containerd-serial-ec2

### CODE REVIEW

**Comment by pacoxu** [comment]
Try copilot summary:

This pull request introduces a new feature to enable CRI API proxy for failure injection in Kubernetes end-to-end tests. The most important changes include adding support for the CRI proxy feature, creating new test cases to validate the feature, and updating the test framework to accommodate the new functionality.

### CRI Proxy Feature Addition:
* [`test/e2e/feature/feature.go`](diffhunk://#diff-337683b7f1560f35fe4a306d97241505a4b6e852d0aea485221d7f6ab67524d8R360-R362): Added a new feature flag `CriProxy` for testing CRI API proxy.
* [`test/e2e/framework/test_context.go`](diffhunk://#diff-c017e0c5e68c14cb966137bc87de3d3ab8475dc25f9b5fdb47a2b8174830054fR280-R281): Introduced a new field `CriProxyEnabled` in `NodeTestContextType` to indicate if the CRI proxy is enabled.
* [`test/e2e_node/criproxy/endpoint.go`](diffhunk://#diff-6f4a5b142173ae2f1d69d54b3d8881798e2ce6d4febbb11e3addaf4bd7f20158R1-R33): Created a new file with a function to generate a new Unix socket endpoint for the CRI proxy.
* [`test/e2e_node/criproxy/proxy_image_service.go`](diffhunk://#diff-9eea046a36318e595429df394ab564dcf73ec5a885a59b432abca4f0cd53a17fR1-R104): Implemented CRI proxy methods for image services, including `ListImages`, `ImageStatus`, `PullImage`, `RemoveImage`, and `ImageFsInfo`.

### Test Cases for CRI Proxy:
* [`test/e2e_node/criproxy_test.go`](diffhunk://#diff-dcd76cc2b505c998483ff0bcbce6d93e983b2a9797bb21f2f224ade754dcad7fR1-R151): Added new test cases to validate CRI proxy functionality, including error injection and timeout scenarios.
* [`test/e2e_node/image_pull_test.go`](diffhunk://#diff-5b3235610f2b8d8a57d576a79c2a222728c0ef26173d0d9a74d169ca317f159aR1-R304): Introduced tests for parallel and serialized image pulls with CRI proxy enabled, ensuring proper handling of image pull delays and overlaps.

### Framework Updates:
* [`test/e2e_node/e2e_node_suite_test.go`](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R51): Updated the test suite to include CRI proxy initialization and teardown, and added a command-line flag to enable the CRI proxy. [[1]](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R51) [[2]](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R73) [[3]](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R114) [[4]](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R248-R263) [[5]](diffhunk://#diff-6006f3929c5632cdba80da0724bbf16c898e204339efb20812320ab847303c36R300-R303)

These changes collectively enhance the Kubernetes test framework by introducing a new mechanism to simulate CRI API failures, which will help in testing the robustness of the system against such failures.

**Comment by SergeyKanzhelev** [comment]
Yay! it worked!

**Pull request closed without merging**
