### PR TITLE
Upgrade klog to avoid panics crashing components

### LINKED ISSUE #100155: [Structured Logging] when klog is passed nil, it causes components to panic while logging
#### What happened:

When `klog.KObj` is passed a `nil` ref while logging, it panics:

```
Mar 10 23:23:57 kind-worker kubelet[241]: E0310 23:23:57.580249 241 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Mar 10 23:23:57 kind-worker kubelet[241]: goroutine 4504 [running]:
Mar 10 23:23:57 kind-worker kubelet[241]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41cc2c0, 0x7377320)
Mar 10 23:23:57 kind-worker kubelet[241]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
Mar 10 23:23:57 kind-worker kubelet[241]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Mar 10 23:23:57 kind-worker kubelet[241]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
Mar 10 23:23:57 kind-worker kubelet[241]: panic(0x41cc2c0, 0x7377320)
Mar 10 23:23:57 kind-worker kubelet[241]: /usr/local/go/src/runtime/panic.go:965 +0x1b9
Mar 10 23:23:57 kind-worker kubelet[241]: k8s.io/kubernetes/vendor/k8s.io/api/core/v1.(*Pod).GetName(0x0, 0x40a4c60, 0x73f4568)
Mar 10 23:23:57 kind-worker kubelet[241]: :1 +0x5
Mar 10 23:23:57 kind-worker kubelet[241]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.KObj(0x5191890, 0x0, 0x9c, 0xa, 0xc000f09b00, 0x40)
Mar 10 23:23:57 kind-worker kubelet[241]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1587 +0x31
Mar 10 23:23:57 kind-worker kubelet[241]: k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).killContainersWithSyncResult.func1(0xc0016ba1d0, 0xc0007f02c0, 0x0, 0x0, 0xc000a3f320, 0xc00090c380)
Mar 10 23:23:57 kind-worker kubelet[241]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:677 +0x2ae
Mar 10 23:23:57 kind-worker kubelet[241]: created by k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).killContainersWithSyncResult
Mar 10 23:23:57 kind-worker kubelet[241]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:670 +0x105
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/100050/pull-kubernetes-e2e-kind/1369786002343727104/artifacts/logs/kind-worker/kubelet.log

#### What you expected to happen:

`nil` or an empty reference should be logged.

#### How to reproduce it (as minimally and precisely as possible):

`klog.KObj(nil)`

#### Anything else we need to know?:

I have fixed this in https://github.com/kubernetes/klog/pull/225 so we will need to bump klog.

ht @pacoxu for reporting in https://github.com/kubernetes/kubernetes/pull/100109

/priority critical-urgent
/sig instrumentation

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind bug
/kind flake
/priority critical-urgent

#### What this PR does / why we need it:

Upgrades klog to pull in critical bugfixes.

#### Which issue(s) this PR fixes:

Fixes #100155 and https://github.com/kubernetes/kubernetes/issues/98976#issuecomment-791354062. These are the only two changes in the vendor diff.

#### Special notes for your reviewer:

~Waiting on a klog release, testing this against HEAD for now.~

Upgraded to klog v2.8.0.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @dims @serathius @pacoxu

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]

**Comment by dims** [comment]
please use klog `v2.7.0`:
https://github.com/kubernetes/klog/releases/tag/v2.7.0

**Comment by ehashman** [comment]
/sig node

FYI

**Comment by palnabarun** [comment]
/milestone v1.21

(since this is a critical fix)

**Comment by pacoxu** [comment]
Need ./hack/update-internal-modules.sh ？

**Comment by ehashman** [comment]
flake #99801 
/test pull-kubernetes-e2e-kind

**Comment by ehashman** [comment]
@dims @liggitt would you PTAL? :smile:

**Comment by kikisdeliveryservice** [comment]
Looks like:
https://github.com/kubernetes/kubernetes/issues/99979

/test pull-kubernetes-e2e-kind

**Pull request merged**
