### PR TITLE
Move inter-pod affinity predicate and priority functions from default to non-default due to negative performance effects even when not using the feature

### PR DESCRIPTION
**Pull request by davidopp**
Also disable e2e's that assume the feature is enabled.

cc/ @gmarek @wojtek-t @kevin-wangzefeng

### CODE REVIEW

**Comment by davidopp** [comment]
ref/ #22985

**Comment by wojtek-t** [comment]
Tests didn't started I don't know why.

@k8s-bot test this please github issue: #IGNORE

**Comment by wojtek-t** [comment]
LGTM

**Comment by davidopp** [comment]
@k8s-bot e2e test this issue: #25322

**Pull request merged**
