### PR TITLE
libvirt_coreos: to remove old skydns fork fetching from addons

### PR DESCRIPTION
**Pull request by sdminonne**
@thockin @girishkalele  ref https://github.com/kubernetes/kubernetes/pull/29720.
Goal of this PR is: 
- to remove obsolete DNS config files.
- to propose a way to fetch the real template

As soon https://github.com/kubernetes/kubernetes/pull/29720 will be merged I'm OK to modify this accordingly.

FYI: @lhuard1A

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by girishkalele** [comment]
@sdminonne I like this deduplication effort. One suggestion would be to add your sed transform to the Makefile and generate the CoreOS configs in the cluster/addons/dns directory instead of on-the-fly during cluster bringup.

**Comment by thockin** [comment]
I think we should carry a bare minimum number of transforms in the "central" dir.

**Comment by sdminonne** [comment]
@thockin thanks
@girishkalele many apologizes only now I'm seeing your comment: I wrote in this way 'cause the libvirt_coreos dns config file are not valid yaml file and it can be misleading. As soon #29720 will get merged we can try to find a better way (jinja transform may help).

**Pull request merged**
