### PR TITLE
Wait for the port to be ready before starting

### PR DESCRIPTION
**Pull request by fraenkel**
Fixes the portforward flakes. See #27673 & #27680

### CODE REVIEW

**Comment by fraenkel** [comment]
@sttts Here is one attempt. With two containers we have to see if the container terminated rather than the pod.

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by sttts** [comment]
Looks good. Can you double check that it does what it should by temporarily adding an `time.Sleep(10*time.Second)` in the portforward container binary?

**Comment by sttts** [comment]
lgtm

**Comment by fraenkel** [comment]
@sttts The port forwarding tests passed with 50 tries each.  The failures above are some logging tests.

**Comment by sttts** [comment]
@fraenkel can you push the second commit in another PR to check that we can really reproduce the issue with that?

**Comment by fraenkel** [comment]
@stts Good news, both GCE e2e and GCE etcd3 e2e fail miserably without the fix.

**Comment by fraenkel** [comment]
@stts a clean run

**Comment by sttts** [comment]
@k8s-bot cvm gce e2e test this

**Comment by sttts** [comment]
Lgtm. This should fix #27673 & #27680 and reenable the three portforwarding tests. If this is not the case, do not hesitate to revert.

**Comment by sttts** [comment]
@jessfraz we are seeing flakes (#27680) on the 1.4 branch which would be fixed by 37103 and 38260. Please consider them for cherry-picking.

**Comment by sttts** [comment]
@saad-ali @david-mcmahon we are seeing flakes (#27680) on the 1.5 branch which would be fixed by 37103 and 38260. Please consider them for cherry-picking.

**Comment by jessfraz** [comment]
cherry-picked both in #38782

**Pull request merged**
