### PR TITLE
Add ravi to sig scheduling approvers

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
According to the requirement of Approver at community-membership.md, I meet the following requirements so I'd like to add myself as an approver of scheduler.

I have :

- Authored more than ~40 commits to k/k repository and 22 commits in kube-incubator/descheduler.
- Been co-maintainer on descheduler.
- Been a reviewer for more than 3 months.
- Reviewed/helped in reviewing more than 70 PRs.
- Been helping new contributors in getting upto speed and guide them on performance aspects of the kube-scheduler.

As an approver,

-   I agree to only approve familiar PRs
-   I agree to be responsive to review/approve requests as per community expectations
-   I agree to continue my reviewer work as per community expectations
-   I agree to continue my contribution, e.g. PRs, mentor contributors

```release-note
NONE
```

/cc @bsalamat @k82cn @aveshagarwal

### CODE REVIEW

**Comment by bsalamat** [comment]
LGTM

Thanks @ravisantoshgudimetla for your contributions.

Let's wait for @k82cn to make sure he has seen and approves this PR as well.

**Comment by k82cn** [comment]
/lgtm

@ravisantoshgudimetla , thanks very much for your contribution :)

**Comment by ravisantoshgudimetla** [comment]
Thanks @bsalamat and @k82cn.

/assign @dchen1107 for approval.

**Comment by ravisantoshgudimetla** [comment]
retest-not-required

**Review by k82cn — APPROVED** [review]

**Comment by ravisantoshgudimetla** [comment]
ping @dchen1107 

cc @smarterclayton  as I don't know if any other github group for owners exist.

**Pull request merged**
