### PR TITLE
proxy/ipvs: github user name change: daman1807 -> aroradaman

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
@aroradaman have you already updated the CNCF and community records with the change?

**Comment by aroradaman** [comment]
@aojea I created this PR for the update - https://github.com/kubernetes/org/pull/4245
I'm not sure if anything else is required

**Comment by aojea** [comment]
/lgtm
/approve

/hold

unhold once that merges https://github.com/kubernetes/org/pull/4245

**Pull request merged**
