### PR TITLE
Move scalability, upgrade, and common packages to framework/log

### PR DESCRIPTION
**Pull request by johnSchnake**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is part of the transition to using framework/log instead
of the Logf inside the framework package. This will help with
import size/cycles when importing the framework or subpackages.

**Which issue(s) this PR fixes**:
Ref #77359

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig testing
/area test
/area test-framework

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/lgtm

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
