### PR TITLE
Revert #77552 now the actual fix #77580 got merged

### LINKED ISSUE #77551: Large tests (>500 nodes) fail on cluster set-up
**Which jobs are failing**: sig-scalability-gce/gce-scale-performance

**Which test(s) are failing**: Up

**Since when has it been failing**: since today

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance

**Reason for failure**: Set-up scripts report only 500 nodes to be up, even though we see in api-server more nodes that registered

### PR DESCRIPTION
**Pull request by mm4tt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
It reverts https://github.com/kubernetes/kubernetes/pull/77552 which was a temporary workaround that is no longer needed now as https://github.com/kubernetes/kubernetes/pull/77580 got in.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/77551

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

@liggitt - FYI

@mm4tt - did you verify the problem was fixed?
/hold

**Comment by mm4tt** [comment]
> Matt Matejczyk - did you verify the problem was fixed?
> /hold

@wojtek-t, indirectly, kubemark was broken due to it and #77580 fixed all the problems - https://github.com/kubernetes/kubernetes/issues/77602

**Comment by wojtek-t** [comment]
@mm4tt - feel free to cancel hold then.

**Pull request merged**
