### PR TITLE
cleanup some dead cloudprovider code

### PR DESCRIPTION
**Pull request by wgliang**
```release-note
NONE
```

### CODE REVIEW

**Review by libaoan — APPROVED** [review]
done

**Comment by jsafrane** [comment]
/approve
the AWS changes

**Comment by wgliang** [comment]
/cc @bowei @kerneltime @jingxu97 @abrarshivani
PTAL,thanks.

**Comment by wgliang** [comment]
/cc @bowei @kerneltime @jingxu97 @abrarshivani
PTAL,thanks.

**Comment by wgliang** [comment]
/cc @bowei @kerneltime @jingxu97 @abrarshivani
PTAL,thanks.

**Comment by nikhita** [comment]
/retest

/assign @MrHohn 
for approval

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
