### PR TITLE
Update runtime-spec to v1.0.2

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

We can now use the new version since v1.0.2 has be officially released.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

runc and cadvisor are the only vendored projects which use runtime-spec. I created two PRs to update the version there too:
- https://github.com/opencontainers/runc/pull/2277
- https://github.com/google/cadvisor/pull/2454

**Does this PR introduce a user-facing change?**:

```release-note
- Update opencontainers/runtime-spec dependency to v1.0.2
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- Changelog: https://github.com/vbatts/oci-runtime-spec/blob/1ac6f8d7dca90deb1740d45ead3408bf0dd857a1/ChangeLog
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on top of the latest master, this should be ready now

**Comment by liggitt** [comment]
/priority backlog
/approve
for dep changes
cc @kubernetes/sig-node-pr-reviews for lgtm

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
