### PR TITLE
Add `upstream` option to CoreDNS ConfigMap

### LINKED ISSUE #78919: [Failing Test] DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver in master-blocking
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-network] DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]

**Since when has it been failing**:
Failing since 6/10 at 16:58.
[k/k diff](https://github.com/kubernetes/kubernetes/compare/3a50c0069...d873167e8).
Decent chance that the failure is due to https://github.com/kubernetes/kubernetes/pull/78691

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_configmap.go:506
Jun 11 05:58:40.949: dig result did not match: []string{} after 2m0s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:103
```

/cc @kubernetes/sig-network-test-failures 
/priority critical-urgent
/kind failing-test
/milestone v1.15

/cc @jimangel @smourapina @alenkacz

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Re-adds the `upstream` option required to resolve external names 
Needed for CoreDNS 1.3.1

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/78919

**Special notes for your reviewer**:

Missed adding this part while reverting the changes in #78691. 
(Sorry!)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Review by alejandrox1 — APPROVED** [review]
Thank you so much for tackling this so quickly
/lgtm
/milestone v1.15

**Pull request merged**
