### PR TITLE
ignore empty patch in set selector

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
if there is no change, we don't need to try set the selector.

**Which issue this PR fixes**: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by asalkeld** [comment]
Looks good to me

**Comment by xilabao** [comment]
@asalkeld can you approve?

**Comment by xilabao** [comment]
@asalkeld kindly ping.

**Comment by xilabao** [comment]
@asalkeld ptal

**Pull request closed without merging**
