### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by mingyang91**
**What this PR does / why we need it**:

Have typo in comment

**release-note-none**
```release-note-none
```

/assign @justinsb

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks for contribution!

**Comment by xiangpengzhao** [comment]
/hold
until code freeze ends to stop fejta-bot retesting.

**Comment by rowleyaj** [comment]
This is a duplicate of #50923

**Pull request closed without merging**
