### PR TITLE
Update Hostprocess agnhost container to use PATH extension

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This was a bug in hcsshim (https://github.com/microsoft/hcsshim/pull/1174) which has been merged and released. We shouldn't need this any more and caused some confusion in https://github.com/kubernetes/kubernetes/issues/120071

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows

### CODE REVIEW

**Comment by jsturtevant** [comment]
The previous commit failed with `Aug 22 22:09:40.525: INFO: Logs: 'c:\hpc\agnhost' is not recognized as an internal or external command,`. I dropped the `cmd /c` part which means it couldn't find it.  

Instead of adding that back, I've opted to use the `Args` as this would be how it is used across the rest of the e2e suite

**Comment by jsturtevant** [comment]
I forgot that `/agnhost` won't resolve properly in the HPC container.

**Comment by marosset** [comment]
/lgtm
(pending CI)

**Comment by jsturtevant** [comment]
/hold 
since windows test isn't required

**Comment by jsturtevant** [comment]
Looked into this a bit and found that the `PATHEXT` doesn't seem to be set as described in https://github.com/microsoft/hcsshim/pull/1174: 

```
PS C:\hpc> echo "$env:PATHEXT"
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL;
```

When I set it manually it still errors:

```
PS C:\hpc> echo $env:PATHEXT
.COM;.EXE;.BAT;.CMD; ;.CPL

.\agnhost
Program 'agnhost' failed to run: Class not registeredAt line:1 char:1
```

**Comment by jsturtevant** [comment]
This will require further investigation and as it is a relatively small use case for our e2e's with a workaround I am going to close this out until we get more feedback on use cases.

**Pull request closed without merging**
