### PR TITLE
make comments of `(c *threadSafeMap) updateIndices` optimization code more accurate

### PR DESCRIPTION
**Pull request by kidlj**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

To make comments of `(c *threadSafeMap) updateIndices` optimization code more accurate.

#### Special notes for your reviewer:

cc @wojtek-t 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
/ok-to-test
/priority backlog
thanks!

**Comment by MadhavJivrajani** [comment]
@kidlj please also go through this piece of documentation once: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits 
This is a valid change, but it's likely that there are similar fixes in the same file and it'd be greatly appreciated if those could be batched together with this ❤️

**Comment by kidlj** [comment]
@MadhavJivrajani Thank you for the kind reminder, I have read the documentation and examined the whole file again(`thread_safe_store.go`), and couldn't find another similar issue that can be fixed together. But I do think the edit here can make the affecting function easier to understand.

/test pull-kubernetes-unit

**Pull request merged**
