### PR TITLE
Reuse the caculated node resource usage information

### LINKED ISSUE #102977: scheduler: cache the state of node resource usage for node resource plugins
#### What would you like to be added:
cache the state of node resource usage for multiple node resource plugins.

#### Why is this needed:

Scheduler is able to enable config multiple node resource plugins, for example, enable both `NodeResourcesLeastAllocated` and `NodeResourcesBalancedAllocation`.

when the multiple node resource plugins are enabled, `allocatable` and `requested` are calculated for each of the plugin, this is not necessary. We just need to calculated once for a node/pod/resource combination, and reuse the data for other node resource plugins directly.

/sig scheduling

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

btw, this PR take the chance to cleanup a typo.

#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/102977

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
this is performance related change, also cc other maintainers for thoughts.

/cc @alculquicondor  @Huang-Wei

**Comment by alculquicondor** [comment]
I don't think this is worth the added complexity. Some reasons:
- calculating the resources is O(1) (we only look at the cached usage for the node and the usage of the incoming pod). Maybe O(R) if you consider the individual resources.
- In any other usage of the state storage, there is one key per plugin. This is adding a key per node, with the additional cost of locking.
- We are already unifying the node resources plugins #101822. Perhaps something can be done there, like precalculating the usage of the incoming pod in PreFilter and PreScore.

**Comment by chendave** [comment]
> calculating the resources is O(1) (we only look at the cached usage for the node and the usage of the incoming pod). Maybe O(R) if you consider the individual resources.

There is no extra looping against resources, but just cache the state within the existing looping, so it is not changing the original complexity.

> In any other usage of the state storage, there is one key per plugin. This is adding a key per node, with the additional cost of locking.

yes, the key is indexed per node, one cached data VS. one extra `calculateResourceAllocatableRequest`. The state is shared by multiple plugins, so it cannot be indexed by plugin.

> We are already unifying the node resources plugins #101822. Perhaps something can be done there, like precalculating the usage of the incoming pod in PreFilter and PreScore.

Different intentions actually, one PR should be simply enough to address one issue.

**Comment by ahg-g** [comment]
1) I doubt this will have tangible performance impact, if anything, it may cause lock contention when writing to the state map. Did you benchmark the change?
2) The pattern of writing state per node per scheduling cycle is not one we want to encourage, state is meant to be written in pre-processing extension points (PreFilter, PreScore etc.).
3) Sharing state across plugins isn't also a good pattern because order of execution is not guaranteed.

/hold

**Pull request closed without merging**
