### PR TITLE
Fix golint error under scheduler/factory.

### PR DESCRIPTION
**Pull request by tizhou86**
**What this PR does / why we need it**:
Fix golint error under scheduler/factory.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Not sure, if I understood correctly, I see that go-lint is working correctly on CI tests, is it failing locally for you?

**Comment by tizhou86** [comment]
@ravisantoshgudimetla I ran the hack/verify-golint.sh locally and my golint version is 1.10.3

**Comment by tizhou86** [comment]
The Error message is: 
Errors from golint:
pkg/scheduler/factory/factory.go:1088:2: can probably use "var extenders []algorithm.SchedulerExtender" instead

**Review by ravisantoshgudimetla — APPROVED** [review]
Thanks for PR @tizhou86 

/lgtm

**Pull request merged**
