### PR TITLE
resourceClaimController should be registered like the others one to keep code clean

### LINKED ISSUE #115995: Code optimize on kubernetes/cmd/kube-controller-manager/app/controllermanager.go
I am a new guy to kubernetes world, and today I am looking at the source code k8s, I found out a line of code can optimize

```
func NewControllerInitializers(loopMode ControllerLoopMode) map[string]InitFunc {
	controllers := map[string]InitFunc{}

	// All of the controllers must have unique names, or else we will explode.
	register := func(name string, fn InitFunc) {
		if _, found := controllers[name]; found {
			panic(fmt.Sprintf("controller name %q was registered twice", name))
		}
		controllers[name] = fn
	}

	register("endpoint", startEndpointController)
	register("endpointslice", startEndpointSliceController)
	register("endpointslicemirroring", startEndpointSliceMirroringController)
	register("replicationcontroller", startReplicationController)
	register("podgc", startPodGCController)
	register("resourcequota", startResourceQuotaController)
	register("namespace", startNamespaceController)
	register("serviceaccount", startServiceAccountController)
	register("garbagecollector", startGarbageCollectorController)
	register("daemonset", startDaemonSetController)
	register("job", startJobController)
	register("deployment", startDeploymentController)
	register("replicaset", startReplicaSetController)
	register("horizontalpodautoscaling", startHPAController)
	register("disruption", startDisruptionController)
	register("statefulset", startStatefulSetController)
	register("cronjob", startCronJobController)
	register("csrsigning", startCSRSigningController)
	register("csrapproving", startCSRApprovingController)
	register("csrcleaner", startCSRCleanerController)
	register("ttl", startTTLController)
	register("bootstrapsigner", startBootstrapSignerController)
	register("tokencleaner", startTokenCleanerController)
	register("nodeipam", startNodeIpamController)
	register("nodelifecycle", startNodeLifecycleController)
	if loopMode == IncludeCloudLoops {
		register("service", startServiceController)
		register("route", startRouteController)
		register("cloud-node-lifecycle", startCloudNodeLifecycleController)
		// TODO: volume controller into the IncludeCloudLoops only set.
	}
	register("persistentvolume-binder", startPersistentVolumeBinderController)
	register("attachdetach", startAttachDetachController)
	register("persistentvolume-expander", startVolumeExpandController)
	register("clusterrole-aggregation", startClusterRoleAggregrationController)
	register("pvc-protection", startPVCProtectionController)
	register("pv-protection", startPVProtectionController)
	register("ttl-after-finished", startTTLAfterFinishedController)
	register("root-ca-cert-publisher", startRootCACertPublisher)
	register("ephemeral-volume", startEphemeralVolumeController)
	if utilfeature.DefaultFeatureGate.Enabled(genericfeatures.APIServerIdentity) &&
		utilfeature.DefaultFeatureGate.Enabled(genericfeatures.StorageVersionAPI) {
		register("storage-version-gc", startStorageVersionGCController)
	}
	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DynamicResourceAllocation) {
		controllers["resource-claim-controller"] = startResourceClaimController
	}

	return controllers
}
```

in this line, ``controllers["resource-claim-controller"] = startResourceClaimController``, I think it can run rewrite as ``register("resource-claim-controller, startResourceClaimController)``, cus the logic here should be like impl the startController logic and then we put it into the register to find out if the controller was registered twice, if so the program will panic. I think it's better that we change to the one that I provide, which can make code clean as well, but as I'm a new guy, I need some advice on it, can someone help me out?

/help wanted
/area controller-manager

### PR DESCRIPTION
**Pull request by charles-chenzz**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
all controller should have same format of code to keep code cleaner and also the register function is to check whether if a controller was registerd twice, if we directly set resourceClaimController into controller, it might have bug
#### Which issue(s) this PR fixes:

Fixes #115995 

#### Special notes for your reviewer:
review whether my understanding is right, if not please tell me
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

I don't remember why `register` was not used from the beginning. Perhaps it was added while I was still working on my PR and then I didn't notice during a rebase.

Thanks for cleaning this up!

**Comment by charles-chenzz** [comment]
@pohly  sorry for the ping, but the auto test all passed and now seems like need approved for the merge

**Comment by pohly** [comment]
@charles-chenzz: I cannot approve PRs in this part of the Kubernetes code base.

/assign @soltysh 

For approval.

**Comment by pohly** [comment]
@charles-chenzz: please rebase your branch.

You cannot update it and push the result back to your repo while you have a pending PR that uses the branch. I create a different branch for each PR.

**Comment by charles-chenzz** [comment]
> @charles-chenzz: please rebase your branch.
> 
> You cannot update it and push the result back to your repo while you have a pending PR that uses the branch. I create a different branch for each PR.

would you tell me how to rebase my branch now? since my local branch is update and I didn't see the rebase button

**Comment by charles-chenzz** [comment]
image
I think it should be fine now

**Comment by pohly** [comment]
No, those "Merge branch" commits must not show up in this PR. Some other projects require a PR to have them to ensure that test runs are up-to-date, but Kubernetes does that differently.

To resolve this:
```
git checkout master
git reset --hard 0891ba97397c6025afa8baadffeb837a7016f8e3
git push charles-chenzz +master
```

0891ba97397c6025afa8baadffeb837a7016f8e3 is the commit that we want to have in master. The last command assumes that `charles-chenzz` is the name of your private remote - check with `git remote`.

**Comment by charles-chenzz** [comment]
> No, those "Merge branch" commits must not show up in this PR. Some other projects require a PR to have them to ensure that test runs are up-to-date, but Kubernetes does that differently.
> 
> To resolve this:
> 
> ```
> git checkout master
> git reset --hard 0891ba97397c6025afa8baadffeb837a7016f8e3
> git push charles-chenzz +master
> ```
> 
> [0891ba9](https://github.com/kubernetes/kubernetes/commit/0891ba97397c6025afa8baadffeb837a7016f8e3) is the commit that we want to have in master. The last command assumes that `charles-chenzz` is the name of your private remote - check with `git remote`.

thanks very much,  let me try it now

**Comment by charles-chenzz** [comment]
I think it's ready now, would you please check about it? @soltysh  @pohly

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by charles-chenzz** [comment]
image

I have no clue about why pods.go will failed to pass the test

**Comment by charles-chenzz** [comment]
I check the test code and found out it might be internet problem on the test server or something to cause it failed to test, base the log show, my assume should be right. Plus, yesterday it can went through all the test and now the commit version is  same as yesterday. so rerun then it should be good imo

**Comment by charles-chenzz** [comment]
all test passed now, would you please take a look ? @soltysh

**Comment by charles-chenzz** [comment]
sorry for the ping again, but this PR is ready to merge @soltysh

**Comment by pohly** [comment]
Please stop pinging him. It just adds noise and won't make the review happen sooner.

**Comment by charles-chenzz** [comment]
> 

very sorry about it. won't happen again

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
