### PR TITLE
expose: Use resource builder

### PR DESCRIPTION
**Pull request by 0xmichalis**
Plus:
- Rename flag `--service-name` to `--name`
- Some refactoring

### CODE REVIEW

**Comment by rjnagal** [comment]
Integration tests are failing. Tests are still using service-name


NAME       LABELS    SELECTOR        IP(S)     PORT(S)
frontend   <none>    name=frontend             80/TCP
Successful get service frontend {{(index .spec.ports 0).port}}: 80
Error: unknown flag: --service-name
Run 'kubectl help' for usage.
!!! Error in ./hack/test-cmd.sh:536
  'kubectl expose service frontend --port=443 --service-name=frontend-2 "${kube_flags[@]}"' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:536 main(...)
Exiting with status 1
+++ [0513 14:14:25] Clean up complete

**Comment by kargakis** [comment]
@rjnagal don't know what I was thinking while submitting the PR yesterday. Updated all `--service-name` instances to `--name`. Thanks

**Comment by bprashanth** [comment]
@kargakis Is there an issue I can refer to for context?

**Comment by kargakis** [comment]
> @kargakis Is there an issue I can refer to for context?

@bprashanth if I knew of any I would have added it in the commit message;)

**Comment by jlowdermilk** [comment]
LGTM. Needs rebase.

**Comment by kargakis** [comment]
rebased

**Comment by kargakis** [comment]
rebased vol.2

can we get this merged now?

**Comment by jlowdermilk** [comment]
Shippable is flake, but travis green. Merging.

**Comment by jlowdermilk** [comment]
Sorry, not merging. There's a freeze in place, will merge afterwards. Kicking shippable in the meantime.

**Comment by jlowdermilk** [comment]
hmmm. `hack/test-cmd.sh` appears to be failing on shippable.

```
I0520 17:49:30.970537   21142 manager.go:151] Version: {KernelVersion:3.13.0-43-generic ContainerOsVersion:Ubuntu precise (12.04.5 LTS) DockerVersion:Unknown CadvisorVersion:0.13.0}
I0520 17:49:30.971377   21142 plugins.go:69] No cloud provider specified.
W0520 17:49:31.519457   21142 server.go:535] No api server defined - no events will be sent to API server.
!!! [0520 17:49:36] Timed out waiting for http://127.0.0.1:10248/healthz
!!! Error in ./hack/test-cmd.sh:43
  'return 1' exited with status 1
```

If it's passing for you locally, you may want to rebase again :/

**Comment by kargakis** [comment]
Still that fail on shippable? It's confusing that travis is green.

**Comment by jlowdermilk** [comment]
Kicked shippable. LGTM.

**Pull request merged**
