### PR TITLE
Put podAntiAffinity in PodSpec.

### LINKED ISSUE #45318: Do not use annotation for pod affinity
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Check https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-statefulset.yaml#L80-L96 , it is still using `scheduler.alpha.kubernetes.io/affinity`, we should move it to `PodSpec`.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

In 1.6, we moved the `affinity` from `annotations` to `PodSpec`, but the `annotations` still works with `AffinityInAnnotations=true`. Please check https://docs.google.com/document/d/1YP3OJTKMpXkWAhipPjx9-bDMxJ87JZ6AcVak7c3SGos/edit for detail.

**Release note**:

```release-note
```

Fixed #45318

### CODE REVIEW

**Comment by a-robinson** [comment]
/approve

Thanks @gyliu513! Could you provide context on how this affects which versions of Kubernetes this config will run on now? Does it need a minimum of 1.5 now vs 1.4 previously?

**Comment by gyliu513** [comment]
@a-robinson Yes, it needs a minimum 1.6 now if want to put the `affinity` to `PodSpec`, please check https://docs.google.com/document/d/1YP3OJTKMpXkWAhipPjx9-bDMxJ87JZ6AcVak7c3SGos/edit for detail.

In 1.6, we moved the `affinity` from `annotations` to `PodSpec`, but the `annotations` still works with `AffinityInAnnotations=true`.

**Comment by gyliu513** [comment]
@a-robinson can you please add a `lgtm` label to make this can be merged?

**Comment by a-robinson** [comment]
/lgtm

If that doesn't work, then you'll have to ask someone else since I don't have labeling privileges anymore. Sorry for the delay!

**Comment by gyliu513** [comment]
Thanks @a-robinson 

/cc @thockin @eparis can you please help merge this?

**Pull request merged**
