### PR TITLE
Automated cherry pick of #110256: kubelet: Mark ready condition as false explicitly for terminal pods

### PR DESCRIPTION
**Pull request by bobbypage**
Cherry pick of #110256 on release-1.22.

#110256: kubelet: Mark ready condition as false explicitly for terminal pods

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed a 1.22 regression kubelet issue that could result in invalid pod status updates to be sent to the api-server where pods would be reported in a terminal phase but also report a ready condition of true in some cases.
```

### CODE REVIEW

**Comment by bobbypage** [comment]
Cherrypick was not fully clean - manual conflict on the e2e test which was resolved manually.

```
$ git diff
diff --cc test/e2e_node/node_shutdown_linux_test.go
index 78d8c59362f,32ff9ccb549..00000000000
--- a/test/e2e_node/node_shutdown_linux_test.go
+++ b/test/e2e_node/node_shutdown_linux_test.go
@@@ -23,20 -24,28 +23,33 @@@ import
        "fmt"
        "os"
        "path/filepath"
 +      "strconv"
        "time"

 -      apierrors "k8s.io/apimachinery/pkg/api/errors"
        "k8s.io/apimachinery/pkg/fields"
+       "k8s.io/apimachinery/pkg/watch"
+       "k8s.io/client-go/tools/cache"
+       watchtools "k8s.io/client-go/tools/watch"
        "k8s.io/kubectl/pkg/util/podutils"
++<<<<<<< HEAD
++=======
+
+       admissionapi "k8s.io/pod-security-admission/api"
++>>>>>>> test: update graceful node shutdown e2e with watch

        "github.com/onsi/ginkgo"
        "github.com/onsi/gomega"
        "k8s.io/kubernetes/pkg/apis/scheduling"
 +      "k8s.io/kubernetes/pkg/features"
        "k8s.io/kubernetes/test/e2e/framework"

 -      "github.com/godbus/dbus/v5"
        v1 "k8s.io/api/core/v1"
 -      schedulingv1 "k8s.io/api/scheduling/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
++<<<<<<< HEAD
++=======
+       "k8s.io/apimachinery/pkg/util/wait"
+       "k8s.io/kubernetes/pkg/features"
++>>>>>>> test: update graceful node shutdown e2e with watch
        kubeletconfig "k8s.io/kubernetes/pkg/kubelet/apis/config"
        kubelettypes "k8s.io/kubernetes/pkg/kubelet/types"
        testutils "k8s.io/kubernetes/test/utils"
@@@ -119,14 -158,9 +160,9 @@@ var _ = SIGDescribe("GracefulNodeShutdo
                                framework.ExpectEqual(len(list.Items), len(pods), "the number of pods is not as expected")

                                for _, pod := range list.Items {
-                                       if isPodStatusAffectedByIssue108594(&pod) {
-                                               framework.Logf("Detected invalid pod state for pod %q: pod status: %+v", pod.Name, pod.Status)
-                                               framework.Failf("failing test due to detecting invalid pod status")
-                                       }
-
                                        if kubelettypes.IsCriticalPod(&pod) {
 -                                              if isPodShutdown(&pod) {
 -                                                      framework.Logf("Expecting critical pod to be running, but it's not currently. Pod: %q, Pod Status %+v", pod.Name, pod.Status)
 +                                              if pod.Status.Phase != v1.PodRunning {
 +                                                      framework.Logf("Expecting critcal pod to be running, but it's not currently. Pod: %q, Pod Status Phase: %q, Pod Status Reason: %q", pod.Name, pod.Status.Phase, pod.Status.Reason)
                                                        return fmt.Errorf("critical pod should not be shutdown, phase: %s", pod.Status.Phase)
                                                }
                                        } else {
@@@ -151,15 -185,10 +187,20 @@@
                                framework.ExpectEqual(len(list.Items), len(pods), "the number of pods is not as expected")

                                for _, pod := range list.Items {
++<<<<<<< HEAD
 +                                      if isPodStatusAffectedByIssue108594(&pod) {
 +                                              framework.Logf("Detected invalid pod state for pod %q: pod status: %+v", pod.Name, pod.Status)
 +                                              framework.Failf("failing test due to detecting invalid pod status")
 +                                      }
 +                                      if pod.Status.Phase != v1.PodFailed || pod.Status.Reason != "Shutdown" {
 +                                              framework.Logf("Expecting pod to be shutdown, but it's not currently: Pod: %q, Pod Status Phase: %q, Pod Status Reason: %q", pod.Name, pod.Status.Phase, pod.Status.Reason)
++=======
+                                       if !isPodShutdown(&pod) {
+                                               framework.Logf("Expecting pod to be shutdown, but it's not currently: Pod: %q, Pod Status %+v", pod.Name, pod.Status)
++>>>>>>> test: update graceful node shutdown e2e with watch
                                                return fmt.Errorf("pod should be shutdown, phase: %s", pod.Status.Phase)
                                        }
 +
                                }
                                return nil
                        },

```

**Comment by bobbypage** [comment]
ping @kubernetes/release-managers 

for cherrypick approvals.

Thank you!

**Comment by puerco** [comment]
Thanks @bobbypage !
/priority important-soon
/lgtm

**Pull request merged**
