### PR TITLE
Automated cherry pick of #105122: added keys for structured logging

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #105122 on release-1.22.

#105122: added keys for structured logging

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
ping @thockin 
for approval

**Comment by ialidzhikov** [comment]
/cc @jsafrane
@jsafrane can you approve the 1.22 backport as well? Thank you in advance!

**Comment by justaugustus** [comment]
> /cc @jsafrane @jsafrane can you approve the 1.22 backport as well? Thank you in advance!

Applying the `approved` label on the basis of [@jsafrane's approval for the 1.21 cherry pick](https://github.com/kubernetes/kubernetes/pull/105138#issuecomment-959749686).
/label tide/merge-method-squash

**Comment by justaugustus** [comment]
> > /cc @jsafrane @jsafrane can you approve the 1.22 backport as well? Thank you in advance!
> 
> Applying the `approved` label on the basis of [@jsafrane's approval for the 1.21 cherry pick](https://github.com/kubernetes/kubernetes/pull/105138#issuecomment-959749686). /label tide/merge-method-squash

Same for @mattcary's [`lgtm`](https://github.com/kubernetes/kubernetes/pull/105138#issuecomment-925101957).
/lgtm

**Pull request merged**
