### PR TITLE
Add Topology Manager Interfaces

### PR DESCRIPTION
**Pull request by lmdaly**
**What this PR does / why we need it**:
Adding Topology Manager interfaces based on merged design proposal here: https://github.com/kubernetes/community/pull/1680
Issue for tracking PRs: https://github.com/kubernetes/kubernetes/issues/72828

Interfaces added:
* Topology Manager
* Policy

**What type of PR is this?**

/kind feature

**Does this PR introduce a user-facing change?**:

```release-note
NONE

```

### CODE REVIEW

**Comment by lmdaly** [comment]
@ConnorDoyle @balajismaniam @nolancon

**Comment by lmdaly** [comment]
Some tests fail due to a dependency on another PR, should we make the two PRs into one in order to get the tests to pass?
Or is it sufficient to have a merge order? Tests should pass when PR: is merged: https://github.com/kubernetes/kubernetes/pull/72913

**Comment by RenaudWasTaken** [comment]
@lmdaly you can include these commits in your PR for now and rebase once that PR is merged

**Comment by spiffxp** [comment]
/hold
ref: https://github.com/kubernetes/enhancements/issues/693#issuecomment-466728227

**Comment by klueska** [comment]
As this PR stands now, the tests will never pass because they are not based on a branch that includes the SocketMask changes.

**Review by klueska — APPROVED** [review]
LGTM pending passing tests after rebased on `SocketMask` changes in https://github.com/kubernetes/kubernetes/pull/72913

**Pull request merged**
