### PR TITLE
Update CHANGELOG OWNERS

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Update CHANGELOG OWNERS with 1.23 release team

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
Temporarily remove @AuraSinis @parul5sahoo @sam-cogan from the list. Will add them back after they become Kubernetes org member.

**Review by wilsonehusin — APPROVED** [review]
I'm not sure if I have enough karma, let's try it!

/approve

**Comment by Damans227** [comment]
Lemme see if I can approve myself, lol! 

/approve
/lgtm

**Pull request merged**
