### PR TITLE
remove unnecessary type arguments

### PR DESCRIPTION
**Pull request by haoruan**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Go has type deduction, the type parameters are unnecessary in these cases
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
Thanks for the PR! I would appreciate the existing way more since it would be more clear and more maintainable in this way. Please feel free to comment if there is any strong objection. Thank you
/triage accepted
/close

**Comment by haoruan** [comment]
I agree for the maintainability and readability, but seems this new way has been widely used in k/k, for examples:
https://github.com/kubernetes/kubernetes/blob/20fc8a939c3394bd31edd06a893b75d1c312e27c/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L241
https://github.com/kubernetes/kubernetes/blob/20fc8a939c3394bd31edd06a893b75d1c312e27c/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L561

And also noticed the suggestion https://github.com/kubernetes/kubernetes/issues/113709#issuecomment-1488144153 to replace it.

So how about consider it from the code consistency point?

**Comment by haoruan** [comment]
@cici37 for above comments, thanks

**Pull request closed without merging**
