### PR TITLE
Fixing resourcequota link

### LINKED ISSUE #26844: The file "resourcequota" in docs/user-guide/resourcequota path can't be found
The file "resourcequota"  URL is http://kubernetes.io/docs/admin/resourcequota/, not http://kubernetes.io/docs/user-guide/resourcequota/.

Maybe we shoud delete https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/resourcequota. Because it references http://kubernetes.io/docs/user-guide/resourcequota/, but we get an "404 Error!" page.

### PR DESCRIPTION
**Pull request by Pensu**
Fixes #26844

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by wojtek-t** [comment]
@david-mcmahon - what's the procedure for merging such changes?

**Comment by david-mcmahon** [comment]
cc @johndmulhausen

**Comment by Pensu** [comment]
@brendandburns Do you have merge it yourself or something? @david-mcmahon

**Pull request merged**
