### PR TITLE
fix cleaning typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix cleaning typo

### CODE REVIEW

**Comment by timchenxiaoyu** [comment]
cc @timstclair

**Comment by timstclair** [comment]
@timchenxiaoyu we appreciate the cleanup, but it would be great if you could batch these - have you found any other typos that need fixing?

**Comment by timstclair** [comment]
It looks like you have quite a few currently open - would you mind collapsing these all into a single PR? Less overhead for reviewers.

**Comment by bgrant0607** [comment]
@timchenxiaoyu This is not only a lot of overhead for our reviewers, even with the new bulk-LGTM tool, but also for our test infrastructure. 

https://github.com/kubernetes/kubernetes/pulls/timchenxiaoyu

@fejta do you have ideas about how to make comment-only changes cheaper and get merged faster? Maybe treat them similar to doc changes (no retest, move to head of queue, etc.)?

cc @brendandburns

**Comment by brendandburns** [comment]
Yeah, we shouldn't test comment only PRs, this would involve improving the munger...



________________________________

**Comment by timchenxiaoyu** [comment]
I do not understand should I fix all typo in one PRs?

**Comment by timstclair** [comment]
Yes please. There's no reason to keep such trivial & similar changes separate.

**Comment by timchenxiaoyu** [comment]
ok,I know ,I will do my best to fix typos I found in one PRs.

**Comment by dchen1107** [comment]
@timchenxiaoyu are you still working on including other typo fixes into this pr? Thanks!

**Comment by timchenxiaoyu** [comment]
yes,but I cloud not find all typo in short time.do my best

**Comment by timchenxiaoyu** [comment]
I signed it!

**Comment by timchenxiaoyu** [comment]
I change my compute,do I need sign again?

**Comment by timchenxiaoyu** [comment]
ok, I don't set git user email.

**Comment by timchenxiaoyu** [comment]
@dchen1107 I have commit all typo,please check!

**Comment by fejta** [comment]
Will you please rebase and squash this into a single commit?

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by timchenxiaoyu** [comment]
sorry,my code has change so much.but I can close this comment,and recommit all typo if necessary ?

**Comment by fejta** [comment]
You shouldn't need a new PR. Just read the instructions in my previous comment to squash your 5 commits into a single commit. The command is `git rebase -i HEAD~5` and then change each `pick` line after the first to either `s` (for squash) or `f` (for fixup). They both merge the commit into the previous commit. The difference between squash and fixup is that fixup removes the commit message whereas squash appends it to the previous commit message.

**Comment by timchenxiaoyu** [comment]
operate error .close this pr,create new one

**Pull request closed without merging**
