### PR TITLE
Fix for kubectl issue 834:

### LINKED ISSUE #834: "kubectl help api-resources --sort-by" text mentions nodes, not API resources
Looks like a case of copy/paste:

$ ack "sort nodes list"
staging/src/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go
108:	cmd.Flags().StringVar(&o.SortBy, "sort-by", o.SortBy, "If non-empty, sort nodes list using specified field. The field can be either 'name' or 'kind'.")

staging/src/k8s.io/kubectl/pkg/cmd/top/top_node.go
118:	cmd.Flags().StringVar(&o.SortBy, "sort-by", o.Selector, "If non-empty, sort nodes list using specified field. The field can be either 'cpu' or 'memory'.")
$

### PR DESCRIPTION
**Pull request by syedriko**
"kubectl help api-resources --sort-by" text mentions nodes, not API resources

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubectl/issues/834

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by brianpursley — APPROVED** [review]

**Comment by brianpursley** [comment]
/lgtm
/assign @deads2k
This PR fixes a mistake in the help text

**Review by seans3 — APPROVED** [review]

**Pull request merged**
