### PR TITLE
use framework.ExpectNoError() for e2e/apps

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The e2e test framework has ExpectNoError() for readable test code.
This replaces gomega.Expect(err).NotTo(gomega.HaveOccurred()) with it for e2e/apps.
- cronjob.go
- daemon_restart.go
- disruption.go
- job.go
- network_partition.go
- rc.go
- replica_set.go
- statefulset.go

**Which issue(s) this PR fixes**:
Ref #77103

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig testing

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM as per the refactor ticket.
thanks.
/assign @janetkuo

**Comment by oomichi** [comment]
Much readable, thanks

/lgtm

**Pull request merged**
