### PR TITLE
Correct DaemonSet example

### PR DESCRIPTION
**Pull request by pop**
**What this PR does / why we need it**:
Corrects DaemonSet design doc including an example which would not validate.
`spec.template.spec.containers` was type `map` instead of type an `array`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Nope

**Special notes for your reviewer**:
One character change ❤️ !

**Release note**:

NONE

### CODE REVIEW

**Comment by ElijahCaine** [comment]
@smarterclayton I'm confused as to what I need to do to appease the bot. Can you help me out?

**Comment by smarterclayton** [comment]
The docs repo has been moved out, so any PR that changes them gets flagged.  See http://kubernetes.io/editdocs/ for more info.  You'll need to open this PR against `kubernetes/kubernetes.github.io`

**Comment by ElijahCaine** [comment]
@smarterclayton Hmm. This doc doesn't seem to exist in kubernetes.github.io, but this example is very useful. Should we close it or should we try to migrate the example over to the DaemonSet user guide?

**Comment by smarterclayton** [comment]
Ah, designs moved to kubernetes/community.

**Comment by ElijahCaine** [comment]
@smarterclayton Thanks for the heads up. This can be closed now.

**Pull request closed without merging**
