### PR TITLE
Remove plain text username and password, since they are kept encoded

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
`docker login` produces a file which looks like this:
```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "xyzabc12345..."
    }
  }
}
```
but our `kubectl create secret` will keep the username and password in plain text in the generated secret as well. This PR removes the two bits, since they are already there encoded in auth field.

/assign @liggitt @deads2k 
@kubernetes/sig-auth-pr-reviews fyi

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
looks like TestSecretForDockerRegistryGenerate needs to be fixed up

**Comment by liggitt** [comment]
need to understand why this was there in the first place... I assume it wasn't done just for fun. Does an old docker require this, or old kube?

**Comment by errordeveloper** [comment]
I think old docker required email.

**Comment by soltysh** [comment]
> need to understand why this was there in the first place... I assume it wasn't done just for fun. Does an old docker require this, or old kube?

> I recall that old docker required email

That is correct, older `.dockercfgjson` format required email. Now, that we have moved to the new format it's not required anymore. Thus I'm proposing removing it.

**Comment by soltysh** [comment]
I've rebased and fixed the broken tests.

**Comment by soltysh** [comment]
@liggitt friendly ping

**Comment by liggitt** [comment]
> Now, that we have moved to the new format it's not required anymore. Thus I'm proposing removing it.

Is it merely optional, or not even supported?

Do we have any tests that use these against actual private registries (v1? v2?) to make sure removing this still functions properly?

**Comment by soltysh** [comment]
> Is it merely optional, or not even supported?

Optional.

> Do we have any tests that use these against actual private registries (v1? v2?) to make sure removing this still functions properly?

I doubt it.

**Comment by dims** [comment]
LGTM 👍

**Comment by liggitt** [comment]
>> Do we have any tests that use these against actual private registries (v1? v2?) to make sure removing this still functions properly?
> 
> I doubt it.

we need to make sure pulls from both v1 and v2 registries still work

**Comment by soltysh** [comment]
> we need to make sure pulls from both v1 and v2 registries still work

I'll do it for 1.12

**Pull request closed without merging**
