### PR TITLE
Add config option for AWS EBS root volume size

### PR DESCRIPTION
**Pull request by erulabs**
I wanted it to be a bit easier to have custom sizes for minion and master root EBS disks when using AWS.

Typically I have tiny images and attach persistent disks for all my pods, but I have a use case where I'd _like_ to have plenty of scratch space on my nodes for "EmptyDir" style data.

This makes it easier! :dancer:

Thanks!

### CODE REVIEW

**Comment by erulabs** [comment]
I signed it!

**Comment by galacto** [comment]
This change didn't worked as it is. I replaced BLOCK_DEVICE_MAPPINGS_BASE variable with actual string and voila it worked. 

Thanks .

**Comment by erulabs** [comment]
@galacto Hrm? Mind sharing? This change has worked for me for a number of clusters. Note that kube-down doesn't delete the persistent volumes on AWS, and will re-attach them on kube-up even if you've changed something here in the util.sh. You have to actually delete the disks manually from AWS. Not sure if this applies to GCE.

**Comment by galacto** [comment]
@erulabs GCE has different way of doing it refer this #3192
for aws I did like this:
in util.sh

MINION_BLOCK_DEVICE_MAPPINGS="[{\"DeviceName\": \"/dev/sda1\",\"Ebs\":{\"DeleteOnTermination\":true,\"VolumeSize\":${MINION_DISK_SIZE}}},{\"DeviceName\": \"/dev/sdc\",\"VirtualName\":\"ephemeral0\"},{\"DeviceName\": \"/dev/sdd\",\"VirtualName\":\"ephemeral1\"},{\"DeviceName\": \"/dev/sde\",\"VirtualName\":\"ephemeral2\"},{\"DeviceName\": \"/dev/sdf\",\"VirtualName\":\"ephemeral3\"}]"

and in config-default.sh introduced this variable
MINION_DISK_SIZE=${MINION_DISK_SIZE:-100}

unfortunately I lost the error message I got when I did that but it was kind of incorrect parameters 

one more thing to note is when I created EBS through console it did not work, I had to create it through aws cli.

**Comment by mbforbes** [comment]
@brendandburns dumping AWS changes to you, sorry for the noise, please redistribute as you can

**Comment by roberthbailey** [comment]
This is still failing shippable after a few runs. I think you may need to rebase before it will pass.

**Comment by roberthbailey** [comment]
Removing lgtm label until this is rebased. @brendandburns please re-add it once shippable is passing.

**Comment by erulabs** [comment]
Rebase complete - test's ought to pass shortly :+1: Thanks guys!

**Comment by brendandburns** [comment]
LGTM, shippable is now passing.

**Pull request merged**
