### PR TITLE
[KEP-3962]Add feature gate for MAP

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Add feature gate `MutatingAdmissionPolicy` for enabling mutation policy in admission chain.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @jpbetz 
Would you please take a look when have time? Thanks

**Comment by jpbetz** [comment]
/approve
For API Machinery 

Should this be combined with the feature PR?

**Comment by jpbetz** [comment]
Leaving LGTM with @alexzielenski

**Comment by alexzielenski** [comment]
I think we want to merge this with the rest of the implementation. I've added the commit to our WIP implementation branch

**Comment by cici37** [comment]
@alexzielenski We could merge this PR separately. The API changes is the one need to go with implementation. :)

**Review by jiahuif — CHANGES_REQUESTED** [review]
Looks like we need to add this before `OpenAPIEnums` to keep the feature gates sorted, according to the verify CI job.

**Pull request merged**
