### PR TITLE
Automated cherry pick of #66264: extend timeout to workaround slow arm64 math

### PR DESCRIPTION
**Pull request by joejulian**
Cherry pick of #66264 on release-1.10.

#66264: extend timeout to workaround slow arm64 math

### CODE REVIEW

**Comment by timothysc** [comment]
@kubernetes/release-maintainers - per cherry-pick

**Comment by guineveresaenger** [comment]
@foxish for cherry-pick approval

**Comment by guineveresaenger** [comment]
oh whoops - Caleb is branch manager for 1.10
/cc @calebamiles

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by guineveresaenger** [comment]
And I picked the wrong person again. The cherrypicks doc needs updating.

/cc @MaciekPytel

**Comment by MaciekPytel** [comment]
Looks good, but this cherry-pick was opened past deadline for 1.10.6. Currently I'm only cherry-picking PRs that fix release-blocking tests, so we can get the release going. Please ping me if you think this is critical for 1.10.6, otherwise I'll merge it after the release.

**Comment by MaciekPytel** [comment]
Discussed with @joejulian offline and it looks quite urgent. I'll merge this PR after the tests recover, unless it would cause significant delay to 1.10.6 relase.

**Pull request merged**
