### PR TITLE
Enable support for memory eviction configuration via salt

### PR DESCRIPTION
**Pull request by vishh**
Added evictions based on memory by default whenever the available memory is < 100Mi.

Updated GCE and GCI.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
lgtm for the gci script change

**Comment by dchen1107** [comment]
LGTM overall.

@roberthbailey Are you ok with the limit we choose here?

**Comment by roberthbailey** [comment]
Yes, even a g1-small has 1.7G of memory, and running nodes on an f1-micro isn't likely to do anything useful. So at most this holds back ~5% of the VM's memory.

**Comment by roberthbailey** [comment]
```
Found illegal 'flag' usage. If these are false positives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
cluster/saltbase/salt/kubelet/default:  {% set eviction_hard="--eviction-hard=" + pillar['eviction_hard'] %}
FAILED   ./hack/../hack/verify-flags-underscore.py	61s
```

**Comment by vishh** [comment]
@dchen1107 I made some changes to satisfy pre-commit hooks. PTAL

**Comment by vishh** [comment]
@k8s-bot test this github issue: #20242

**Comment by vishh** [comment]
@k8s-bot test this github issue #IGNORE

**Comment by vishh** [comment]
@k8s-bot test node e2e github issue #IGNORE

**Comment by vishh** [comment]
@k8s-bot node e2e test this github issue #IGNORE

**Comment by dchen1107** [comment]
LGTM again!

**Pull request merged**
