### PR TITLE
Update URL to azure guide

### PR DESCRIPTION
**Pull request by Phelimb**
This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23788)

### CODE REVIEW

**Comment by Phelimb** [comment]
I signed it!

**Comment by zmerlynn** [comment]
cc @bgrant0607: Thoughts on how to handle this PR? It seems like this is actually just a doc bug to handle the redirect for `/azure` correctly.

**Comment by bgrant0607** [comment]
Now that kubernetes.io has launched, maybe we need to update all the breadcrumbs we left in the main repo.
cc @eparis

**Comment by roberthbailey** [comment]
@johndmulhausen -- this fixes a broken URL, but with the split of the docs repository is it needed?

**Comment by eparis** [comment]
ok to test

**Comment by roberthbailey** [comment]
ping @johndmulhausen -- does this PR belong here or in the docs repository?

**Comment by roberthbailey** [comment]
ping @johndmulhausen -- does this PR belong here or in the docs repository?

**Comment by roberthbailey** [comment]
@Phelimb - I had a chat with @johndmulhausen and if you want to make this change, you should send a PR against the master branch instead of the 1.2 release branch.

**Pull request closed without merging**
