### PR TITLE
Manual cherry pick of kube-openapi changes for release-1.20

### LINKED ISSUE #101755: kube-apiserver memory consumption during CRD creation
#### What happened:
The CustomResourceDefinitions creation causes kube-apiserver high memory consumption. CRD has multiple versions.
Several creations during a short period of time may cause kube-apiserver restarting.
#### What you expected to happen:
kube-apiserver shouldn't consume an unreasonably huge amount of memory during processing objects such as CRD
#### How to reproduce it (as minimally and precisely as possible):
Apply yaml and watch kube-apiserver memory consumption:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: applications.deployment.nrm.netcracker.com
spec:
  group: deployment.nrm.netcracker.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: hub
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              milestones:
                properties:
                  activationTimestamp:
                    format: date-time
                    type: string
                type: object
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              notServed:
                type: string
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha10
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              milestones:
                properties:
                  activationTimestamp:
                    format: date-time
                    type: string
                type: object
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha5
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha6
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha7
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha8
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha9
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
#### Anything else we need to know?:
/sig api-machinery

#### Environment:
- Kubernetes version: 1.20.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #105932: High CPU Utilization in kube-apiserver when a large number of CRDs are created
### What happened?

In [Crossplane](https://crossplane.io/), we would like to register thousands of CRDs in a single cluster representing the many Cloud services possibly from multiple Cloud Providers. In our early trials with kind clusters, we have observed that simultaneously posting just over 700 CRDs results in a CPU-utilization spike in kube-apiserver, due to the background OpenAPI spec publishing job. We were also made aware of the memory consumption [issue](https://github.com/kubernetes/kubernetes/issues/101755) during CRD creation. 

We made similar observations in a GKE cluster on which we installed  over 650 CRDs, making the total 685. Unfortunately, we could not identify the root cause but we have observed the cluster flipping between the "repairing" state and the "available" state for an extended period of time. Our observation is that the cluster could come out of the repairing state but for a couple of times, it was in repairing state again, with no new CRD registrations or object creations from our side. The only probes we utilized during this period were `kubectl get` commands. 

In [our tests](https://github.com/crossplane-contrib/terrajet/issues/47#issuecomment-920316141), we have observed that on an arm64 machine with 8 CPU cores, API server enters a high CPU utilization period of about 20 min after 750+ CRDs are created. If the API server saturates the CPU resources allocated to it, this may also disrupt its services. So we have a couple of questions:
1. Can we expect the fix for the memory issue referenced above improve the situation with the CPU?
2. Are there any plans for introducing the number of CRDs in a cluster as a scalability dimension in the [thresholds document](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md)? If so, is it reasonable to expect our use cases covered?
3. Is it possible/reasonable to turn off the `/openapi/v2` endpoint to prevent aggregation of the OpenAPI schemas of the CRDs? Who are the clients of this endpoint?
4. In the GKE case, is there a way to monitor kube-apiserver CPU/memory consumption, crashes, etc.? So that we can reason about our empirical observations described above.

### What did you expect to happen?

We were not expecting to observe CPU usage spikes for extended periods in our tests. For the GKE cluster experiment, we were not expecting service disruptions. 

### How can we reproduce it (as minimally and precisely as possible)?

Simultaneously create a large number (>650) of CRDs with OpenAPI schemas.

### Anything else we need to know?

It looks like the average schema size in bytes per CRD could be a relevant parameter. If needed, we can supply those numbers assuming schemas are serialized in JSON. If you'd like to see some example CRDs we used in the above observations, please take a look at this [branch](https://github.com/ulucinar/provider-tf-azure/tree/fix-ps-670/package/crds) of one of the Crossplane providers.

### Kubernetes version

<details>
v1.21.0 in local tests where we observed high CPU utilization. <br>
v1.20.10-gke.301 for GKE: <br>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ulucinar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Updates `kube-openapi` dependency to consume the aggregated OpenAPI spec lazy-marshaling behavior introduced with: 
https://github.com/kubernetes/kube-openapi/pull/251
and cherry picked to the `kube-openapi/release-1.20` branch with:
https://github.com/kubernetes/kube-openapi/pull/266

Looks like lazy-marshaling introduced with https://github.com/kubernetes/kube-openapi/pull/251 enables us to [better scale](https://github.com/crossplane/crossplane/issues/2649#issuecomment-956914007) in the #-of-CRDs-per-cluster dimension. 

#### Which issue(s) this PR fixes:

Fixes #101755
Fixes #105932

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @apelisse 
/cc @DangerOnTheRanger 
/sig api-machinery

### CODE REVIEW

**Comment by ulucinar** [comment]
Hi @DangerOnTheRanger, @apelisse,
Can we please get a `ok-to-test` label for this PR also?

**Comment by puerco** [comment]
Thanks a lot @ulucinar !
/lgtm

**Pull request merged**
