### PR TITLE
Genericapiserver support log file handler

### LINKED ISSUE #60784: generic apiserver should support logsHandler
now only kube-apiserver support logs handler `/logs`

We should support it for all generic apiservers.

/sig api-machinery

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

1. logs handler `/logs` support genericapiserver

1. add a new flag `--logs-dir` to allow specify logs directory.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60784

**Release note**:

```release-note
Generic apiserver support logs handler, and add a new `--logs-dir` flag to allow users specify the logs directory.
```

### CODE REVIEW

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60786)

**Comment by hzxuzhonghu** [comment]
@sttts @deads2k ptal

**Comment by deads2k** [comment]
I'm not sold on this change.  The logs endpoint has had multiple problems over time and I expect things like log aggregation to handle this in production environments.  For a while, this even exposed an entire directory of potentially sensitive logs by default.  

@liggitt I remember you having opinions here too.

**Comment by liggitt** [comment]
Agree. Surfacing local directories via the API is not a pattern I'd want to see extended.

**Comment by yliaog** [comment]
+1

**Pull request closed without merging**
