### PR TITLE
Use metadata.name instead of hostname label when setting affinity

### PR DESCRIPTION
**Pull request by wongma7**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind cleanup

**What this PR does / why we need it**: since kubernetes.io/hostname may not equal node.Name, as the comment details, we should make sure to use node.Name. turns out "metadata.name" is the key for this.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
/assign @mkimuram 
/sig storage
ty

**Comment by jsafrane** [comment]
`should access volume from different nodes` passes
/lgtm
/approve

**Comment by jsafrane** [comment]
/assign @pohly @andrewsykim 
for approval

**Review by pohly — APPROVED** [review]
/approve

**Pull request merged**
