### PR TITLE
Fix broken links in Ubuntu Getting Started Guide

### LINKED ISSUE #37937: ci-kubernetes-e2e-gci-gke-reboot-release-1.5: broken test run
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot-release-1.5/348/

Multiple broken tests:

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by triggering kernel panic and ensure they function upon restart {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:105
Dec  2 00:41:16.838: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #34123 #35398

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:111
Dec  2 00:51:30.053: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #33407 #33623

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:93
Dec  2 01:01:43.786: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #33874

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:119
Dec  2 01:11:57.783: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #33405

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:99
Dec  2 00:20:53.733: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #33882 #35316

Failed: [k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:127
Dec  2 00:31:07.215: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:159
```
Issues about this test specifically: #33703 #36230

Previous issues for this suite: #37776 #37879

### LINKED ISSUE #38506: Install in Ubuntu - Broken link
Link in this page:

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

is broken.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Fix a broken link in docs

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #38506 

**Special notes for your reviewer**:
First time contributing. It looks like these docs are legacy anyways, but I believe I've linked them to the right place.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
I signed it!

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-docs give this PR a look at this small PR? Looks like it was incorrectly auto assigned by the bot. Thanks!

**cc: @jaredbhatti**

**Comment by cblecker** [comment]
Any word on this? Happy Holidays :)

**Comment by devin-donnelly** [comment]
@cblecker Are you sure this is the right place to update this? It probably hasn't been seen to because sig-docs usually only deals with this repo: https://github.com/kubernetes/kubernetes.github.io

I don't usually see PRs in this repo.

**Comment by cblecker** [comment]
@devin-donnelly This PR updates links to the docs in the other repo.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-docs-misc please take a look at this PR. Thanks!

**Comment by cblecker** [comment]
@smarterclayton @brendandburns bump :)

**Comment by chrislovecnm** [comment]
@k8s-bot test this

**Comment by cblecker** [comment]
Tests have all passed 😄

**Comment by chrislovecnm** [comment]
I escalated this, the assigned folks are super busy ;( appreciate you patience! There is current work that is underway to make this more efficient

**Comment by chrislovecnm** [comment]
Actually to be clear I asked for help on this ;)

**Comment by apelisse** [comment]
Fixed by https://github.com/kubernetes/kubernetes.github.io/pull/1932

**Comment by cblecker** [comment]
Thanks @apelisse!

**Pull request closed without merging**
