### PR TITLE
Update Azure/azure-sdk-for-go

### LINKED ISSUE #84516: BYOK(Bring Your Own Key) support for azure disk
**What would you like to be added**:
BYOK(Bring Your Own Key) support for azure disk

dependency: https://github.com/Azure/azure-sdk-for-go/tree/master/services/compute/mgmt/2019-07-01/compute

**Why is this needed**:

/kind feature
/assign
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup
/kind feature

**What this PR does / why we need it**:
Update Azure modules:
 - github.com/Azure/azure-sdk-for-go v35.0.0+incompatible

**Which issue(s) this PR fixes**:

Fixes #84516

**Special notes for your reviewer**:
```
hack/pin-dependency.sh github.com/Azure/azure-sdk-for-go v35.0.0+incompatible
hack/update-vendor.sh
```

**Does this PR introduce a user-facing change?**:

```release-note
Update Azure SDK versions to v35.0.0
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

/kind bug
/assign @feiskyer @justaugustus
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
@chewong could you take a look at this failure? Thanks.
```
W1030 05:14:38.610] 2019/10/30 05:14:38 main.go:319: Something went wrong: starting e2e cluster: failed to generate ARM templates: failed to generate ARM templates: error during /go/src/k8s.io/kubernetes/aks-engine generate /workspace/aks648705628/kubernetes.json --output-directory /workspace/aks648705628: exit status 1.
```

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
@kubernetes/dep-approvers could you help to take a look?

**Comment by chewong** [comment]
> @chewong could you take a look at this failure? Thanks.
> 
> ```
> W1030 05:14:38.610] 2019/10/30 05:14:38 main.go:319: Something went wrong: starting e2e cluster: failed to generate ARM templates: failed to generate ARM templates: error during /go/src/k8s.io/kubernetes/aks-engine generate /workspace/aks648705628/kubernetes.json --output-directory /workspace/aks648705628: exit status 1.
> ```

https://github.com/kubernetes/test-infra/pull/14998 is currently affecting most of the Azure-related builds. I've already reverted the PR and waiting for @k8s-ci-robot to update the job configuration. Sorry about that.

**Pull request merged**
