### PR TITLE
AWS owners files - Tweaking layout  and throwing my hat n the ring

### PR DESCRIPTION
**Pull request by chrislovecnm**
cc: @justinsb and @zmerlynn 

Fixed layout of OWNERS files to have approvers and reviewers sections.  Also, threw my hat into the ring.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot bazel test this

**Comment by rootfs** [comment]
@justinsb @zmerlynn any comment?

**Comment by chrislovecnm** [comment]
@k8s-bot bazel test this

**Comment by rootfs** [comment]
@chrislovecnm please also add @jsafrane and @gnufied to aws provider. They are working on various aws issues.

**Comment by gnufied** [comment]
Yes please. If not as a approver please add us as a reviewer.

**Comment by justinsb** [comment]
I think the proposed expanded list of reviewers is great - thank you all.

My understanding is that we shouldn't generally add people to approvers right away though, that some period as a reviewer is required: https://github.com/kubernetes/community/blob/master/governance.md

**Comment by deads2k** [comment]
> My understanding is that we shouldn't generally add people to approvers right away though, that some period as a reviewer is required: https://github.com/kubernetes/community/blob/master/governance.md

Correct.  

@justinsb I'm not familiar with the guts of `pkg/credentialproviders/aws`.  It's parent package is a docker keyring impl I made significant changes in, so that's why I'm on the parent.  When you're happy with the `pkg/credentialproviders/aws` list, let me know and I'll approve that.

**Comment by chrislovecnm** [comment]
@rootfs you asked me to add people and did an LGTM ... 

I would like people to add themselves.  This is an ownership thing.  If you want this responsibility, then in my mind you need to ask for it via a PR.

**Comment by kris-nova** [comment]
Where is this coming from? Is this the official list? This seems like something sig-aws should own and manage, and am wondering where this list is coming from?  I don't remember ever reviewing this in the sig.

**Comment by chrislovecnm** [comment]
@kris-nova this is part of the new core process with OWNERS, not sure if that was your question

**Comment by chrislovecnm** [comment]
Keep or open

**Pull request closed without merging**
