### PR TITLE
fix nil pointer on Time string function

### PR DESCRIPTION
**Pull request by armstrongli**
it panics on debugging.

fix issue: https://github.com/kubernetes/kubernetes/issues/108435

### CODE REVIEW

**Comment by kerthcet** [comment]
please check the cla first, you can refer to this https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#sign-the-cla

**Comment by armstrongli** [comment]
@kerthcet the CLA has been signed, need `/retest` to trigger verification.

**Comment by armstrongli** [comment]
i'm sure i have signed the doc. but the job keeps failing.

image

**Comment by armstrongli** [comment]
ack. updating

**Comment by kerthcet** [comment]
Just curious about you changed your username or email only,  or both of them.

**Comment by liggitt** [comment]
this was previously proposed and declined in https://github.com/kubernetes/kubernetes/pull/105982 because of https://github.com/kubernetes/kubernetes/pull/105982#discussion_r742312742

does this approach have the same issue?

**Comment by liggitt** [comment]
/close

per https://github.com/kubernetes/kubernetes/pull/108436#issuecomment-1058145120

**Pull request closed without merging**
