### PR TITLE
Trigger syncClaim after PV provisioning to reduce wait

### LINKED ISSUE #18830: Dynamically provisioned volumes are bound after 10 minutes
I'm testing dynamic provisioning on AWS. When I create a claim with `volume.alpha.kubernetes.io/storage-class` annotation, Kubernetes creates a PV, marks it as Bound, while the claim is still `Pending`. The claim gets `Bound` only after 10 minutes, i.e. on the next provisioner controller refresh.

When the provisioning is complete, the claim should be marked as Bound immediately, probably somewhere at this place: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go#L294

### PR DESCRIPTION
**Pull request by markturansky**
Resolves #18830 

@pmorie @kubernetes/rh-storage

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
@k8s-bot e2e test this again please

**Comment by markturansky** [comment]
The flakes are strong with this one.

```
!!! [1218 05:23:05] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/healthz; tried 45 waiting 1 between each
!!! Error in ./hack/test-update-storage-objects.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-update-storage-objects.sh:48 startApiServer(...)
  2: ./hack/test-update-storage-objects.sh:123 main(...)
Exiting with status 1
```

**Comment by markturansky** [comment]
@k8s-bot test this

**Comment by markturansky** [comment]
All green.

@saad-ali @pmorie @thockin who will be the reviewer?  Single change to the controller (to trigger an update on claim) w/ a unit test that tests it.

**Comment by markturansky** [comment]
@saad-ali @thockin this is a good 1.2 candidate.  it's a better user experience to not wait for the next sync period (defaulted now to 10 minutes).

PTAL?  This is a small PR.

**Comment by saad-ali** [comment]
Will take a look today

**Comment by saad-ali** [comment]
LGTM. Thanks Mark!

**Comment by swagiaal** [comment]
@k8s-bot unit test this

**Comment by alex-mohr** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Pull request merged**
