### PR TITLE
Automated cherry pick of #64588: Fix some log issues in flexvolume

### PR DESCRIPTION
**Pull request by louyihua**
Cherry pick of #64588 on release-1.11.

#64588: Fix some log issues in flexvolume

### CODE REVIEW

**Comment by louyihua** [comment]
@saad-ali @sjenning Please approve this cherry-pick.

**Comment by liggitt** [comment]
this issue existed in 1.10 as well... seems like this fix can be deferred to 1.11.1

**Comment by calebamiles** [comment]
/hold
@foxish please remove the hold when you're ready to cut 1.11.1

**Pull request merged**
