### PR TITLE
apiserver: add egress_type label to egress dial metrics

### PR DESCRIPTION
**Pull request by andrewsykim**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:'

This PR adds an `egress_type` label to the existing apiserver metrics `egress_dialer_dial_duration_seconds` and `egress_dialer_dial_failure_count`.  The label is especially useful to help determine which apiserver code paths are exercised for the respective metric. Cardinality should be minimal since there are only three valid values for the egress type today: `controlplane`, `etcd`, and `cluster`. 

Also includes some minor refactoring and clean up

#### Does this PR introduce a user-facing change?

```release-note
apiserver: add egress_type label to egress dial metrics
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
cc @cheftako @jkh52

**Comment by aojea** [comment]
LGTM

**Pull request closed without merging**
