### PR TITLE
Revert "Modify GCI mounter to enable NFSv3"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#36610

This broke a lot of tests in
https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow
https://k8s-testgrid.appspot.com/google-gke#gci-gke-slow
https://k8s-testgrid.appspot.com/google-gke#gci-gke

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37375)

### CODE REVIEW

**Comment by piosz** [comment]
cc @jingxu97 @mtaufen @vishh

**Comment by piosz** [comment]
cc @saad-ali

**Comment by dims** [comment]
LGTM 👍

**Comment by piosz** [comment]
Merging manually to unblock the queue

**Pull request merged**
