### PR TITLE
fix kubelet panic when DynamicKubeletConfig enabled

### LINKED ISSUE #103579: kubelet failed to start when DynamicKubeletConfig enabled
#### What happened:

kubelet failed to start when specifying `--feature-gates=DynamicKubeletConfig=true` ,with following error:

```
E0708 16:08:50.142443    6073 kubelet.go:1329] "Image garbage collection failed once. Stats initialization may not have completed yet" err="failed to get imageFs info: 
panic: semver: Parse(1.22): No Major.Minor.Patch elements found

goroutine 129 [running]:
k8s.io/kubernetes/vendor/github.com/blang/semver.MustParse(0x55e3169ffe96, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/blang/semver/semver.go:319 +0x245
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.parseSemver(...)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/version_parser.go:38
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*GaugeVec).DeprecatedVersion(0xc0002adc00, 0xc000134120)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/gauge.go:116 +0xa5
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*lazyMetric).preprocessMetric(0xc0002adc10, 0x1, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/metric.go:108 +0xbd
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*lazyMetric).Create(0xc0002adc10, 0xc000154010, 0x0)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/metric.go:144 +0x155
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000154000, 0xc000850650, 0x1, 0x1)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:169 +0xdf
k8s.io/kubernetes/pkg/kubelet/metrics.Register.func1()
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go:470 +0x942
sync.(*Once).doSlow(0x55e31a7ac2b0, 0xc000563658)
        /usr/local/go/src/sync/once.go:68 +0xee
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
k8s.io/kubernetes/pkg/kubelet/metrics.Register(0xc000563710, 0x2, 0x2)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go:446 +0x88
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeModules(0xc000841500, 0x6, 0x55e3183bc9f8)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1348 +0x169
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000841500, 0xc00044a720)
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1447 +0x75
created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
        /root/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1204 +0x57
```

#### How to reproduce it (as minimally and precisely as possible):
Try to start kubelet with `--feature-gates=DynamicKubeletConfig=true`:

`FEATURE_GATES=DynamicKubeletConfig=true hack/local-up-cluster.sh`

#### Environment:
- Kubernetes version (use `kubectl version`): master branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by borgerli**
#### Which issue(s) this PR fixes:

Fixes #103579

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by adisky — COMMENTED** [review]
/triage accepted
/release-note-none
/priority important-soon
/lgtm

**Comment by fromanirh** [comment]
/lgtm
considering the error message and the fact that digging in the history all the versions we used in this file are in the form `MAJOR.MINOR.VERSION`

I'd suggest a second ack (lgtm) to move forward

**Review by SergeyKanzhelev — APPROVED** [review]

**Pull request merged**
