### PR TITLE
GC kubemark image after cluster starts up

### LINKED ISSUE #59567: Problems with kubemark image lifecycle
After looking at @thockin 's [PR](https://github.com/kubernetes/kubernetes/pull/57824), I realized that there are some problems with how we're using kubemark images for our CI-testing:

1. Every run of every kubemark job creates and pushes a kubemark image to the image registry of the project in which the cluster would be created. But the kubemark cluster setup uses the `<registry>/kubemark:latest` image. This means that a race b/w 2 kubemark jobs while pushing the image is possible, and it may happen that one job is using the image from another one. This can be solved by using a random image tag to uniquify the runs.

2. Every run of every kubemark job pushes a new image to a docker registry. So we have a huge list of leaked kubemark images in the projects where we're running kubemark jobs - e.g O(10^5) images in [one of our projects](https://pantheon.corp.google.com/gcr/images/k8s-jkns-pr-kubemark/GLOBAL/kubemark?gcrImageListsize=50) used for kubemark pre-submit. Each image is about 72 MB and at the cost of [0.026 $/GB](https://cloud.google.com/container-registry/pricing) for our GCS buckets, it's ~$180/month for that project. Another such project is of our kubemark-small job (running once every 20m) which has ~30k stale images. Overall, we're likely spending an estimated O(1000) $/month just on stale kubemark images. Few things we should do IMO:
  - delete the kubemark image at the end of the run
  - delete the pre-existing stale kubemark images
  - in general, make janitor garbage collect images also (cc @krzyzacy @BenTheElder )

3. PR https://github.com/kubernetes/kubernetes/pull/57824 changed the kubemark image registry to `staging-k8s.gcr.io`, instead of the earlier `gcr.io`. However, the manifest for the kubemark deployment [hasn't been updated](https://github.com/kubernetes/kubernetes/blob/3586986416b174d390376311c909d665416bf5c0/test/kubemark/resources/hollow-node_template.yaml#L38) - so all jobs will continue using old kubemark image (albeit the `:latest` one). This needs to be fixed asap.

cc @wojtek-t @porridge @kubernetes/sig-scalability-bugs 
/assign

### PR DESCRIPTION
**Pull request by shyamjvs**
Last piece to fix https://github.com/kubernetes/kubernetes/issues/59567

/cc @wojtek-t 

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@shyamjvs - to be clear, there is still possibility that we will be leaking those images if something will go wrong, right? So that's more like "stop the bleeding" rather than a proper fix, right?

**Comment by shyamjvs** [comment]
> to be clear, there is still possibility that we will be leaking those images if something will go wrong, right?

While I wouldn't deny the possibility, I think that shouldn't happen as we're adding a trap command right after successfully pushing the image and that should be called whenever/however the script exits.

> So that's more like "stop the bleeding" rather than a proper fix, right?

I wouldn't fully agree with that as any solution that solves this problem by deleting images needs to do it at some point (and this one is simply deleting it right when it's not needed anymore). Do you have some other fix in mind?

**Comment by wojtek-t** [comment]
> I wouldn't fully agree with that as any solution that solves this problem by deleting images needs to do it at some point (and this one is simply deleting it right when it's not needed anymore). Do you have some other fix in mind?

Asynchronous GC - in that case we have a guarantee that all non-needed images will be removed.
Even if you have trap here, the executora of that script mya kill you at any time non-gracefully, I think.
So there is a possibility of leak in my opinion.

I'm not saying that we should merge that - it's obviously an improvement, but I would like to set the expectations clearly.
Or maybe you're saying that if we leak a couple of images per week, we don't care at all?

**Comment by shyamjvs** [comment]
You're right that some kind of periodic GC'ing will probably be a more concrete approach. My feeling though is that'd be an overkill (and possibly more complex) compared to this. Even if we're deleting successfully 99% of the times, that's good enough win for us IMO.

**Comment by wojtek-t** [comment]
>  Even if we're deleting successfully 99% of the times, that's good enough win for us IMO.

Yes - that\s probably fine - I just wanted to set the expectations correctly for this PR.

/lgtm

**Pull request merged**
