### PR TITLE
Typo fix for changelog-1.10

### PR DESCRIPTION
**Pull request by warmchang**
**What this PR does / why we need it**: Typo fix for changelog-1.10

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by warmchang** [comment]
ping @lavalamp & @dchen1107 , please check and tag approve & lgtm.
Thanks.

**Comment by nikhita** [comment]
/assign @lavalamp 
for approval

**Pull request merged**
