### PR TITLE
Updating nettest image to latest code

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/11014

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@ixdy

**Comment by nikhiljindal** [comment]
Have pushed the updated image to gcr.io with @ArtfulCoder's help

**Comment by ixdy** [comment]
I think you need to update test/e2e/networking.go L167, too.

Also please run the test locally and verify that it's fixed, since the pull request Jenkins won't.

**Comment by nikhiljindal** [comment]
Thanks for catching that @ixdy! Have fixed it.
Running e2e locally to verify.

**Comment by ixdy** [comment]
LGTM assuming Jenkins is still good and your local e2e works.

@quinton-hoole can you provide a second set of eyes?

**Comment by nikhiljindal** [comment]
Verified that e2e passes locally.
Ready to be merged.

**Comment by brendandburns** [comment]
LGTM, ok-to-merge.

I'm merging so we can get clean e2e overnight.

**Pull request merged**
