### PR TITLE
Don't label the UI e2e test as part of the conformance suite

### PR DESCRIPTION
**Pull request by roberthbailey**
It's a test to ensure that an _optional_ cluster addon is working.

/cc @erictune

### CODE REVIEW

**Comment by ihmccreery** [comment]
LGTM.

**Comment by erictune** [comment]
sgtm

**Comment by bryk** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Comment by roberthbailey** [comment]
Re-testing because the PR builder broke and wasn't running, not because of a test flake.

k8s-bot test this issue: #IGNORE

**Comment by bryk** [comment]
Can I help you anyhow to get this merged?

**Comment by roberthbailey** [comment]
The e2e error is `Failed to create static ip e2e-gce-builder-2-3-master-ip`. Looks like the PR builder is out of quota.

**Comment by roberthbailey** [comment]
@bryk -- can you ask @gmarek or @mwielgus to un-wedge the PR builder?

**Comment by bryk** [comment]
All right, I'll work with them. Can you LGTM the UI addon PR, so that I can get it merged today? https://github.com/kubernetes/kubernetes/pull/20330#issuecomment-179642767

**Comment by gmarek** [comment]
@k8s-bot test this

**Pull request merged**
