### PR TITLE
Automated cherry pick of #108167: Fix nodes volumesAttached status not updated

### PR DESCRIPTION
**Pull request by mattcary**
Cherry pick of #108167 on release-1.22.

#108167: Fix nodes volumesAttached status not updated

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve
/kind bug
/priority important-soon
/sig storage

https://github.com/orgs/kubernetes/teams/release-managers - for cherrypick approval

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
