### PR TITLE
Code cleanup: group consts togather

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

This is a code cleanup, which groups all consts togather.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60772)

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve no-issue

**Pull request merged**
