### PR TITLE
Bump dependency: cel-go to v0.21.0

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @dims 
When you have time:) Thank you!

**Comment by dims** [comment]
nice we are dropping `golang.org/x/text/width` :)

thanks @cici37 

/approve
/lgtm

**Comment by dims** [comment]
- diff in dependency - https://github.com/google/cel-go/compare/v0.20.1...v0.21.0
- no new init() methods!

**Pull request merged**
