### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Add and move apply tests

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by kwiesmueller — APPROVED** [review]

**Comment by apelisse** [comment]
We probably need to merge master back in
/hold

**Comment by jennybuckley** [comment]
/unhold
master is merged back in

**Pull request merged**
