### PR TITLE
upgrade json-patch to v4.11.0

### LINKED ISSUE #98080: CustomResources dropping "null" values from arrays
**What happened**:

While attempting to work around https://github.com/kubernetes/kubernetes/issues/98079, I encountered an issue where data was not preserved when writing a custom resource instance to the apiserver with kubectl.

Specifically, I am using a CRD that has a properly which is an array of values which can either be an integer, or null:

```
spec:
  properties:
    allocations:
      items:
        nullable: true
        type: integer
      type: array
```

When using kubectl to modify the resource, all of the "null" values are lost upon write. So, if I attempt to write a resource with the following:

```
allocations:
- 1
- 5
- null
- null
```

It is written successfully. However, when I query the resource from the API afterwards, this is what I get back:

```
allocations:
- 1
- 5
```

The null entries have been lost.

**What you expected to happen**:

The null entries in the array should be maintained. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a CustomResourceDefinition with a property like the one specified above, and create an instance of it (you may need to pass `--validate=false` in order to bypass the bug in https://github.com/kubernetes/kubernetes/issues/98079).

Notice that `null` values are removed from the array.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Also reproduced on master by @liggitt 

CC @sttts @apelisse 

/sig api-machinery

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:
Fixes #98080

refer to https://github.com/evanphx/json-patch/releases/tag/v5.5.0 which include the fix https://github.com/evanphx/json-patch/pull/143

#### Special notes for your reviewer:
We upgrade to 4.11.0 for nulls in arrays merge.

And we don't choose v5.5.0 for its Break change: 
- JSON patch implemented by https://github.com/evanphx/json-patch now conforms to RFC6902 replacement semantics and does not accept "replace" patch operations if the specified path does not exist.

#### Does this PR introduce a user-facing change?
```release-note
fix nulls are handles of array's and objects in json patches.
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/assign @liggitt

Currently, v4.5.0 cannot be removed for kustomize
- sigs.k8s.io/kustomize/api@v0.8.10 is using github.com/evanphx/json-patch@v4.5.0+incompatible.
- staging/src/k8s.io/sample-cli-plugin/go.sum is using v4.5.0+incompatible.

**Comment by pacoxu** [comment]
A test case need to be Updated

**Comment by liggitt** [comment]
> A test case need to be Updated

That's concerning. It looks like we intentionally avoided moving to github.com/evanphx/json-patch/v5 because of compatibility implications (https://github.com/kubernetes/kubernetes/pull/91622#issuecomment-637087847)

**Comment by pacoxu** [comment]
> > A test case need to be Updated
> 
> That's concerning. It looks like we intentionally avoided moving to github.com/evanphx/json-patch/v5 because of compatibility implications ([#91622 (comment)](https://github.com/kubernetes/kubernetes/pull/91622#issuecomment-637087847))

The breaking change here is `{"op": "replace", "path": "/noname", "value": "test"}` will panic if the path doesn't exists.

```
➜  gopath go get github.com/evanphx/json-patch/v5/@v5.5.0
➜  gopath vi main.go
➜  gopath go run main.go
panic: replace operation does not apply: doc is missing key: /noname: missing value

goroutine 1 [running]:
main.main()
	/Users/xupaco/git/gopath/main.go:24 +0x2fa
exit status 2
➜  gopath cat main.go
package main

import (
	"fmt"

	jsonpatch "github.com/evanphx/json-patch/v5"
)

func main() {
	original := []byte(`{"name": "John", "age": 24, "height": 3.21, "": 12}`)
	patchJSON := []byte(`[
		{"op": "replace", "path": "/name", "value": "Jane"},
                {"op": "remove", "path": "/height"},
		{"op": "replace", "path": "/noname", "value": "test"}
	]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}

	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Original document: %s\n", original)
	fmt.Printf("Modified document: %s\n", modified)
}
```

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit
a data race

**Comment by liggitt** [comment]
Looks like json-patch also released v4.10.0 to make the fix available in the v4 stream. That seems like it might be a better version to switch to.

**Comment by pacoxu** [comment]
/hold
go mod problem during upgrading to 4.10.0
I opened https://github.com/evanphx/json-patch/issues/145.

**Comment by monopole** [comment]
Thanks @pacoxu for looking into this.
Holding on https://github.com/kubernetes-sigs/kustomize/pull/3938 as well.

**Comment by BenTheElder** [comment]
v4.11.0 should be out and fixed per https://github.com/evanphx/json-patch/issues/145#issuecomment-854356783

**Comment by pacoxu** [comment]
Thanks. @BenTheElder 
I updated the PR with v4.11.0.

**Comment by liggitt** [comment]
dependency update looks great.

would be good to add an explicit test case to cover https://github.com/kubernetes/kubernetes/issues/98080 to ensure this works as expected with this update and does not regress in the future

**Comment by pacoxu** [comment]
A test case with `drop` array is added.

**Review by BenTheElder — APPROVED** [review]
LGTM

**Pull request merged**
