### PR TITLE
Remove prometheus dependencies whitelist  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
 
/kind cleanup 
 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/89267

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by tanjunchen** [comment]
kindly /cc @lavalamp

**Comment by tanjunchen** [comment]
kindly
/cc @lavalamp

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by serathius** [comment]
ping  @dchen1107

**Pull request merged**
