### PR TITLE
Remove docker health handler from kubelet /healthz

### LINKED ISSUE #17743: kubelet /healthz endpoint should not include docker daemon health
Supervisord babysits docker daemon and kubelet separately. Having kubelet's health depending on docker seems unnecessary and cause kubelet to (potentially) be restarted when docker restarts.
Note that kubelet already checks the container runtime healthiness when reporting the node status, so changing this should not affect pod scheduling.

/cc @dchen1107

### PR DESCRIPTION
**Pull request by yujuhong**
Docker's health is checked separately from kubelet by the processing monitoring
tool (e.g., supervisord). kubelet should not be killed when docker is down.
This change removes the docker health handler from kubelet's /healthz handler.

This fixes #17743

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I assume we have other checks that verify docker API version?

I agree that the kubelet should not be recycled when docker daemon is down so I have no major issue with this PR.

Just to record for future discussion, we actually would like the kubelet to do more aggressive monitoring of the docker daemon to isolate if/when it wedges and mark the node as unschedulable.  Some instances where docker reports healthy, but its not include a) containers are unable to speak out to network, b) the docker remote api becomes unresponsive, c) leaking iops, etc.  

Longer term, I would like the kubelet to monitor more of these potential scenarios in the same vein it monitors docker daemon resource limits by placing it in its own /docker cgroup and setting resource controls such that when our operations team report issues, we can add intelligence into the daemon for the whole community to gain rather than scripting around it outside of the project per-se.

/cc @ncdc

**Comment by yujuhong** [comment]
> I assume we have other checks that verify docker API version?

Yes, kubelet checks docker version and set node status accordingly. Killing docker (or kubelet) if the version requirement fails doesn't help to begin with.

> Just to record for future discussion, we actually would like the kubelet to do more aggressive monitoring of the docker daemon to isolate if/when it wedges and mark the node as unschedulable. Some instances where docker reports healthy, but its not include a) containers are unable to speak out to network, b) the docker remote api becomes unresponsive, c) leaking iops, etc.

Most of the issues we've seen are detectable using `docker ps` as the health check, and we are planning to switch to that soon (see #17525). In the long run, we may even check the error rate of docker operations as an indication of docker healthiness, as also discussed in #17525. The a, b, c cases you mentioned seem quite specific though, and that may require kubelet to perform a thorough list of checks. @dchen1107 may have different opinions since she feels strongly on whether kubelet should play the role of software doctor.


> Longer term, I would like the kubelet to monitor more of these potential scenarios in the same vein it monitors docker daemon resource limits by placing it in its own /docker cgroup and setting resource controls such that when our operations team report issues, we can add intelligence into the daemon for the whole community to gain rather than scripting around it outside of the project per-se.

Docker daemon is already running in the /docker-daemon cgroup. We haven't set a resource limit for it or for kubelet because both of them currently consume more resource than desired. Setting a unrealistic limits now may just hinder the performance. We are working on brining down the resource usage of both kubelet and docker. After the short-term goal is achieved, we will measure and set resource limits.

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@dchen1107, PTAL!

**Comment by dchen1107** [comment]
@derekwaynecarr Let's move kubelet's role on detecting docker daemon's issue to #17525 or open a new issue so that we won't lost our discussion. Thanks!

> I assume we have other checks that verify docker API version?
Yes, https://github.com/kubernetes/kubernetes/pull/15994 was introduced to check docker's version, and mark node NotReady if the version is below 1.6.2 for kubernetes 1.1 release.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
ok to test

**Pull request merged**
