### PR TITLE
use bytes.HasPrefix instead of bytes.Index

### LINKED ISSUE #34538: YAMLReader should use more performance sensitive methods
FYI. Just open issue to track @smarterclayton comment on #34297

### PR DESCRIPTION
**Pull request by adohe-zz**
fix #34538 @smarterclayton ptal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34540)

### CODE REVIEW

**Comment by AdoHe** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
quota IN_USE_ADDRESSES exceeded.

@k8s-bot gcc e2e test this

**Comment by AdoHe** [comment]
@k8s-bot gce e2e test this

**Comment by AdoHe** [comment]
@smarterclayton do we still want this or I can close this?

**Comment by smarterclayton** [comment]
I think we do want this.  Just forgot about it :)

**Pull request closed without merging**
