### PR TITLE
Update cAdvisor godeps to v0.31.0

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
Update the cAdvisor dependency for the 1.12 release.

**Special notes for your reviewer**:
Some of the interfaces of cAdvisor changed this release.  The values used here maintain the previous behavior.

This PR adds a few new new vendored dependencies that were added as part of adding mesos containerizer support.  All new dependencies have Apache 2.0 licenses.

**Release note**:
```release-note
- cAdvisor: Fix NVML initialization race condition
- cAdvisor: Fix brtfs filesystem discovery
- cAdvisor: Fix race condition with AllDockerContainers
- cAdvisor: Don't watch .mount cgroups
- cAdvisor: Reduce lock contention during list containers
```

/assign @dchen1107 @thockin

### CODE REVIEW

**Comment by dashpole** [comment]
apologies for letting this slip so late.  Thanks to @bboreham for reminding us.

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr 

/approve

**Pull request merged**
