### PR TITLE
change CPUCFSQuotaPeriod default value to 100us to match Linux default

### PR DESCRIPTION
**Pull request by paskal**
Draft of redoing #111520 after revert in #112077.

/test pull-kubernetes-e2e-gce-alpha-features

### CODE REVIEW

**Comment by paskal** [comment]
/retest
/test pull-kubernetes-e2e-gce-alpha-features

Expected result: e2e gce test fails.

**Review by odinuge — CHANGES_REQUESTED** [review]
Hi!

Can you please elaborate more about the need for this PR?

Having a cfs period of 100us does not make sense in general (I have been working quite a bit on that piece of kernel code), and trying to write that value _will_ fail and return an error. The default is indeed `100ms`, with `1ms` as the absolute smallest value (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/core.c#n10546) and `1s` as the highest one (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/core.c#n10545).

The default period of 100ms is defined here; https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/fair.c#n4802.

So unless you have some other thoughts here, it's a hard NACK from me, since merging this will just fail starting up containers with cpu limits.

Thanks
Odin

**Comment by paskal** [comment]
Here is a description from https://www.kernel.org/doc/html/latest/scheduler/sched-bwc.html#management:

> cpu.cfs_quota_us: run-time replenished within a period (in microseconds)
> <...>
> The default values are:
> `cpu.cfs_period_us=100ms`

@odinuge that "in microseconds" reference led me to believe that the default value is in microseconds, which for example results in the valid range from 1μs to 1s in the k8s setting for `cpu.cfs_period_us`.

The piece of code which I don't understand now is Linux source and is this code in k8s which divides user-provided duration by 1000:

https://github.com/kubernetes/kubernetes/blob/17dd76f5d49848e0bcb057035cda7946b578584f/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L167-L171

Default value is not divided and if taken as-is could be converted to 100μs, however if user input of 100μs is provided then it's converted to 100ns which results in error trying to set `cpu.max` to 100 where as minimal value should be 1000 (1μs if I'm not messing up the units?).

k8s source code _comments_ and maybe the default value representation (100μs which you say should be 100ms, according to k8s code logic then divided by 1000) are wrong to some extend, and maybe the kernel.org documentation is unclear. I would be extremely grateful if you would tell me what's the right state of things and what that `run-time replenished within a period (in microseconds)` next to the value with default in `100ms` in documentation means.

**Comment by odinuge** [comment]
> The piece of code which I don't understand now is Linux source [...]

I don't follow here. What is it you don't understand.

> and is this code in k8s which divides user-provided duration by 1000:

The go `Duration` type is measured in nano seconds https://pkg.go.dev/time#Duration, while the kernel value is in micro seconds. Hence, the `ns` value is divided on 1000 to get a `us` value. But yeah, the code _could_ have been clearer with better definitions about the units, that could be an improvement.

More about how the OCI defines these values here; https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#cpu


> Default value is not divided and if taken as-is could be converted to 100μs, however if user input of 100μs is provided then it's converted to 100ns which results in error trying to set cpu.max to 100 where as minimal value should be 1000 (1μs if I'm not messing up the units?).

For the first q, the default value is `100000`, and it is in us. And `100000 us` in `ms` is `100ms`. For number two, I think my comment above should describe it, right?


> I would be extremely grateful if you would tell me what's the right state of things

There might be bugs here, but I think the current world, before your previous PR was the correct state we want to be in. If you run that code, and you get another CFS period (either on cgroup v1 or v2), we have a bug; but i don't _think_ so, but it might be the case. Same for when you set the CFS period manually via that flag to `200ms`. If its not being set to `200ms`, we have a bug.

> and what that run-time replenished within a period (in microseconds) next to the value with default in 100ms in documentation means.

I think thats just a description about what that value is. If the example in the kernel doc is hard to reason around, and having explicitly set to `100000` would have been better for clarity, thats an improvement you can send to the kernel folks 😄 

Does that all make overall sense @paskal?

Also, is your intention with this PR(s) to fix a concrete bug you are seeing with wrong values, or have you not experienced any bugs yet?


Thanks
Odin

**Comment by paskal** [comment]
Thanks a lot for jumping in and providing an explanation! Everything is way clearer for me now. I'll update the k8s code and comments to reflect my understanding so it would also be easier for future readers. I think kernel.org documentation could be clarified to say that it's in microseconds if the unit is not provided; I'll try to introduce that change once I finish here.

My changes were coming not from a bug but from trying to understand the CPU limiting logic and encode that (at first, incorrect) understanding into the code.

**Comment by odinuge** [comment]
Ack, thanks for the answer @paskal! Feel free to cc me on your k8s improvements and when you update the kernel docs. Happy to review and approve them for you! 😄 

Closing this PR now, and then you can open another PR with comments clarifying behavior. 

Thanks
Odin

/close

**Pull request closed without merging**
