### PR TITLE
Use latest heapster image

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating config files to use latest heapster image
Latest image includes GoogleCloudPlatform/heapster#387

cc @bgrant0607 @krousey @rjnagal @vmarmol

### CODE REVIEW

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10755

**Comment by krousey** [comment]
LGTM

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/heapster/pull/391 got merged!
This is now ready to be merged.

**Comment by lavalamp** [comment]
LGTM when jenkins passes :)

**Comment by vmarmol** [comment]
Should be good, @rjnagal uploaded the release :)

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by lavalamp** [comment]
The first jenkins failure is actually a failure to run heapster. Can you investigate? I know it passed the second time, but you didn't change anything so that means at a minimum that it's flakey, no?

**Comment by nikhiljindal** [comment]
My guess is that the first run failed because it was not able to get heapster:0.16.
I created this PR before Rohit's PR was merged :)

**Comment by nikhiljindal** [comment]
Indeed, I see the following in logs:
```
Failed to pull image "gcr.io/google_containers/heapster:v0.16.0" from pod "monitoring-heapster-v5-5nxcc_kube-system" and container "heapster": [Tag v0.16.0 not found in repository gcr.io/google_containers/heapster, Tag v0.16.0 not found in repository gcr.io/google_containers/heapster]
```

**Comment by lavalamp** [comment]
OK, so it just hadn't been pushed yet. SGTM

**Pull request merged**
