### PR TITLE
Make CRDList lifecycle consistent with CRD

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

xref https://github.com/kubernetes/kubernetes/pull/92220#issuecomment-660491491

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @deads2k 
/sig api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
#93210 flake in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93211/pull-kubernetes-node-e2e/1284547265532268544/

**Comment by cbandy** [comment]
I see one more `+k8s:prerelease-lifecycle-gen:deprecated=1.19` on `ConversionReview` which was introduced in the same commit as the others, 555225eb29124a83cdc5c01ebe01c605d74450c6:

https://github.com/kubernetes/kubernetes/blob/66020d22923055133f5f05ca16fbfb66a79053c5/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L475-L479

I do not know anything about these, but thought I should point it out.

**Pull request merged**
