### PR TITLE
fix Contributor License Agreement broken link

### PR DESCRIPTION
**Pull request by mahmud2011**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Fixes a broken link in documentation.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

N/A

**Does this PR introduce a user-facing change?**:

NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

N/A

### CODE REVIEW

**Comment by justaugustus** [comment]
Thank you!

/ok-to-test
/lgtm
/assign @liggitt @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by SergeyKanzhelev** [comment]
fixing labels (doesn't matter which sig, but it's needed):

/sig testing

**Pull request merged**
