### PR TITLE
Fix a race condition in SharedInformer

### LINKED ISSUE #59822: Shared informer has a race condition
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

 /kind bug

**What happened**: I was testing a cluster-api machine controller, and I noticed a double channel close panic on test cleanup.

**What you expected to happen**: No panic.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new shared informer.
2. Concurrently start and add a listener.

There is a path where it can call `run` and `pop` on the `sharedProcessor` twice. When this happens, closing the stop channel will trigger a double close inside of `pop`. Also, this means that 2 copies of `run` are happening on the `sharedProcessor` which seems to violate the guarantee that events to a single handler will be delivered sequentially. Aside from the double close panic on shutdown, this could be the source of heisenbugs in controllers relying on this guarantee.

I'll have a PR out shortly.

cc @kubernetes/sig-api-machinery-bugs

### PR DESCRIPTION
**Pull request by krousey**
**What this PR does / why we need it**:

This fixes a race condition that can occur in the `sharedIndexInformer`

**Which issue(s) this PR fixes**:
Fixes #59822

**Release note**:

```release-note
Fixed a race condition in k8s.io/client-go/tools/cache.SharedInformer that could violate the sequential delivery guarantee and cause panics on shutdown.
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
[test comment pls ignore]
/test pull-kubernetes-bazel-test-canary

**Comment by krousey** [comment]
Without the fix, I was able to use golang.org/x/tools/cmd/stress to generate about 76 panics in 31000 runs with the following:

```console
> go test -c
> stress cache.test -test.run=TestSharedInformerInitializationRace
```

After the fix in the second commit, I got 0 failures in 870,000 runs.

**Comment by smarterclayton** [comment]
How far does this need to be backported? @kubernetes/sig-api-machinery-bugs

**Comment by krousey** [comment]
@smarterclayton I came upon this while testing a controller using the 1.8 release libraries. I would like at least that far back to make my life easier.

**Comment by wojtek-t** [comment]
@krousey - great finding! LGTM

**Comment by krousey** [comment]
@mbohlool can we approve this for the 1.9 branch yet?

**Comment by rmmh** [comment]
re-adding cherrypick-candidate for debugging

**Pull request merged**
