### PR TITLE
statefulset: handle API error on pod deletion

### LINKED ISSUE #113833: Stateful set status not correctly updated when API error occurs
### What happened?

It was found during a review that stateful set status might not be correctly updated when new revision is being rolled out and API error occurs when deleting a pod.

https://github.com/kubernetes/kubernetes/pull/112737#issuecomment-1258893736

### What did you expect to happen?

The status should be updated correctly

### How can we reproduce it (as minimally and precisely as possible)?

Not easy to reproduce, but should be possible with this unit test

https://github.com/kubernetes/kubernetes/blob/ec0b200f3df8835c23c7e5239a4e82d2ca3d601f/pkg/controller/statefulset/stateful_set_control_test.go#L563-L630

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

handle API error on pod deletion when new revision is being rolled out

#### Which issue(s) this PR fixes:

Fixes #113833

#### Does this PR introduce a user-facing change?

```release-note
statefulset status will be consistent on API errors
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
failure `Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce` looks irrelevant
/test pull-kubernetes-unit

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
