### PR TITLE
build: Update to debian-base@v2.1.2 and debian-iptables@v12.1.1

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency security
/sig release api-machinery

**What this PR does / why we need it**:

- build: Update to debian-base@v2.1.2 and debian-iptables@v12.1.1
- cluster/images/etcd: Build etcd@3.4.9-2 using debian-base@v2.1.2

cc: @kubernetes/release-engineering @cjcullen 
ref: https://github.com/kubernetes/release/pull/1450, https://github.com/kubernetes/kubernetes/pull/93562, https://github.com/kubernetes/kubernetes/issues/92616, https://github.com/kubernetes/kubernetes/issues/93114

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
build: Update to debian-base@v2.1.2 and debian-iptables@v12.1.1
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
> /assign

@BenTheElder -- you beat me to it :upside_down_face:

**Comment by BenTheElder** [comment]
nit: PR title doesn't match versions in the files (debian-base = 2.1.2)
is debian iptables 12.1.1 based on debian-base 2.1.2 ?

**Comment by justaugustus** [comment]
> nit: PR title doesn't match versions in the files (debian-base = 2.1.2)

Fixed.

> is debian iptables 12.1.1 based on debian-base 2.1.2 ?

Yep: https://github.com/kubernetes/release/pull/1456

/test pull-kubernetes-e2e-gce

**Pull request merged**
