### PR TITLE
Automated cherry pick of #15414 upstream release 1.1

### PR DESCRIPTION
**Pull request by thockin**
This PR never got cherrypicked for 1.1

@zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
Ugh. I can easily add the beta annotation in `kube-proxy`, but the Ingress one is dicier after we've shipped, isn't it?

**Comment by thockin** [comment]
oh yeah, let me pull that commit out

**Comment by thockin** [comment]
Ugh, now that it is out, I should roll it back in head, I guess.

**Comment by thockin** [comment]
OK, this is 2 of the 3 commits in the original PR

**Comment by zmerlynn** [comment]
I like it. LGTM.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by zmerlynn** [comment]
Green! Merging.

**Pull request merged**
