### PR TITLE
Automated cherry pick of #86090: Update v1.17.0 CHANGELOG to match final draft

### PR DESCRIPTION
**Pull request by tpepper**
Cherry pick of #86090 on release-1.17.

#86090: Update v1.17.0 CHANGELOG to match final draft

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by justaugustus** [comment]
Release Manager approval:
/lgtm
/approve

**Comment by tpepper** [comment]
Prow somehow didn't get Jordan's approve, so I've manually added the label.

**Comment by tpepper** [comment]
(also for the record, we know we're merging this in parallel to the master branch PR, but it's a minor docs-only change and we'd like it in ASAP for readers of the changelog of the release that's being announced...right now!!)

**Pull request merged**
