### PR TITLE
WIP - Define priority when multiple PSP objects match

### PR DESCRIPTION
**Pull request by liggitt**
When a pod is admitted, PodSecurityPolicies are tried, in order, until one allows the pod.

Some policies can apply defaults to unset fields on a pod in order to admit it. For example, a PSP that requires pods to run with a specific uid can admit pods that don't specify a uid by assigning them a uid within the allowed range.

This means the order PodSecurityPolicies are evaluated in can change what the final pod looks like. For example:
1. An admin user has access to a privileged PSP that allows any uid (including an unset uid or uid=0)
2. All users (including the admin user) have access to a restrictive PSP that requires uid 100000
3. The admin user creates a pod and does not specify a uid in the pod spec
  a. If the pod is admitted with the privileged PSP, it is persisted without an explicit uid
  b. If the pod is admitted with the restrictive PSP, it is persisted with a uid of 100000

Which approach is desired could vary by cluster.
* To enforce least privilege, an administrator could want PSP to apply the tightest restrictions that don't violate the capabilities the pod spec requested.
* For greater ease of use, an administrator could want PSP to avoid modifying pods during admission if possible.

This PR adds a priority field to the PodSecurityPolicy object to let administrators order their configured PSPs, letting them indicate preferred policies.

```release-note
PodSecurityPolicy: When multiple policies allow a particular pod, the PodSecurityPolicy admission plugin uses a new `priority` field on the policy object to determine which one to use. Policies are sorted by priority (highest first), then name.
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-auth-pr-reviews @pweil-

**Comment by liggitt** [comment]
@kubernetes/sig-auth-api-reviews

**Review by pweil- — COMMENTED** [review]
LGTM

@php-coder I'd like the next step to be discussion or implementation about allowing the admission plugin to take sorting strategy as configuration so that we can use our own downstream methods (where it runs priority -> restrictiveness -> name).

**Comment by liggitt** [comment]
@kubernetes/api-reviewers PTAL

**Comment by smarterclayton** [comment]
Clarify description, priority is primarily for defaulting - allow less restrictive defaults to be applied over more restrictive defaults.

**Comment by smarterclayton** [comment]
Example:

1. admin user has access to run a PSP that allows uid=0, and one that has uid=HIGH
2. when an admin user wants to create a pod, the PSP that is selected is likely uid=HIGH
3. for better user experience, admins by default want their pods run with uid=0 (so they can run admin like workloads)
4. admins configure priority of the PSP allowing uid=0 to be higher than the one with uid=HIGH, thus ensuring that defaulting of pods with no security context set are allowed to run as root.

**Comment by liggitt** [comment]
> Clarify description, priority is primarily for defaulting - allow less restrictive defaults to be applied over more restrictive defaults.

Updated description

**Comment by gambol99** [comment]
any idea in which release then one will get merged? ..

**Comment by liggitt** [comment]
I'd like to see https://github.com/kubernetes/kubernetes/pull/52849 merged soon, which would make behavior deterministic and would avoid unnecessarily restricting pods

**Pull request closed without merging**
