### PR TITLE
Always set namespace of Node resources to empty string

### LINKED ISSUE #3831: kubectl doesn't handle creating nodes properly...
It forces the namespace to be 'default' when nodes have no namespace.

We need to special case the handling of Nodes in kubectl.

### PR DESCRIPTION
**Pull request by j3ffml**
Closes #3831.

/cc @brendanburns

### CODE REVIEW

**Comment by erictune** [comment]
fyi @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I have a general purpose solution in the works that interfaces with RESTMapper.  Depending on your urgency, I should have a PR for that tomorrow.  My solution will also make sure that we do not expose a /ns/{ns}/nodes URL form on the server and swagger is right, etc.  

If you want to merge this as is to get around an other blocker that is fine too.  I just will make a note to generalize this a little more.

**Comment by jlowdermilk** [comment]
I'll let @brendanburns decide whether to merge now or wait for general purpose solution.

**Comment by satnam6502** [comment]
What's the status of the PR? Thanks.

**Comment by jlowdermilk** [comment]
I recommend we close this in favor of the more generic solution in #3944.

**Pull request closed without merging**
