### PR TITLE
MESOS: Remove redirfd executable and support in the executor

### PR DESCRIPTION
**Pull request by sttts**
With `km minion` we don't use the redirfd mechanism anymore.

### CODE REVIEW

**Comment by sttts** [comment]
@jdef for review

**Comment by jdef** [comment]
minor question. otherwise lgtm.

**Comment by sttts** [comment]
Replaced the echo.

**Comment by sttts** [comment]
@k8s-bot test this

**Comment by sttts** [comment]
@k8s-bot test this

**Pull request merged**
