### PR TITLE
[e2e] Add acceptableFailureRatio to service latency test

### PR DESCRIPTION
**Pull request by MrHohn**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
From https://github.com/kubernetes/kubernetes/issues/74308, it is unreasonable to fail the test just for a single probe flake. This PR adds an `acceptableFailureRatio` and can hopefully deflake the service latency test.

**Which issue(s) this PR fixes**:

Fixes #TBD 

**Special notes for your reviewer**:
cc @BenTheElder @freehan @mm4tt 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
Thank you! This looks good to me.
/lgtm
I think we have to get additional approval since it's conformance? otherwise happy to approve as well..
/hold
poking @pwittrock @spiffxp

**Comment by mm4tt** [comment]
LGTM, thanks!

**Comment by spiffxp** [comment]
/area conformance
this is a change to a conformance test's behavior, I agree it de-flakes things but would like sign-off from someone in test/conformance/OWNERS, will ping accordingly

**Comment by oomichi** [comment]
According to the description of the conformance test, the test should require 100 iterations but it actually does 200 iterations without any errors. Then I feel this adds ~50% acceptable ratio for getting 100+ iterations. That seems reasonable for me.

/lgtm

**Comment by spiffxp** [comment]
/lgtm
I read as ~5% instead of ~50%, so remain valid if 190 samples are taken instead of 200, and then use percentiles based on that.  This seems totally reasonable to me, just want to confirm.

**Comment by MrHohn** [comment]
> I read as ~5% instead of ~50%, so remain valid if 190 samples are taken instead of 200, and then use percentiles based on that. This seems totally reasonable to me, just want to confirm.

Thanks @spiffxp and @oomichi, yep 0.05 should be 5% :)

**Comment by oomichi** [comment]
Oops, my bad. That  is better than I expected :-)

**Comment by smarterclayton** [comment]
/approve
/hold cancel

Latency measurement seems completely reasonable to allow some failures (unlike a test that verifies that service endpoints don't drop connections during a rolling update, for example).  Although historically this test is a canary when regressions do happen, conformance is not measuring connection failures, just latency.

**Pull request merged**
