### PR TITLE
Cleanup more extensively in e2e (0/7)

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes issues caused by graceful deletion.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@roberthbailey FYI this is cleanup that should work with and without graceful deletion being enabled, but which fixes most of the problems from #9165

**Comment by roberthbailey** [comment]
```
Summarizing 1 Failure:

[Fail] Services [It] should be able to up and down services 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:259

Ran 84 of 146 Specs in 500.618 seconds
FAIL! -- 83 Passed | 1 Failed | 2 Pending | 60 Skipped
```

**Comment by roberthbailey** [comment]
I think this is the relevant bit of the test log:

```
[BeforeEach] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:50
STEP: Creating a kubernetes client
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/.kube/config
STEP: Building a namespace api object
Aug 19 10:05:14.664: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-services-wmazi
Aug 19 10:05:14.668: INFO: Get service account default in ns e2e-tests-services-wmazi failed, ignoring for 5s: serviceaccounts "default" not found
Aug 19 10:05:19.675: INFO: Service account default in ns e2e-tests-services-wmazi with secrets found. (5.011425713s)
STEP: Waiting for a default service account to be provisioned in namespace
Aug 19 10:05:19.676: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-services-wmazi
Aug 19 10:05:19.682: INFO: Service account default in ns e2e-tests-services-wmazi with secrets found. (6.390284ms)
[BeforeEach] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:62
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/.kube/config
STEP: Building a namespace api objects
Aug 19 10:05:24.693: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-service-0-uq7x6
Aug 19 10:05:24.699: INFO: Get service account default in ns e2e-tests-service-0-uq7x6 failed, ignoring for 5s: serviceaccounts "default" not found
Aug 19 10:05:29.705: INFO: Service account default in ns e2e-tests-service-0-uq7x6 with secrets found. (5.011799433s)
Aug 19 10:05:34.711: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-service-1-u0d1m
Aug 19 10:05:34.716: INFO: Get service account default in ns e2e-tests-service-1-u0d1m failed, ignoring for 5s: serviceaccounts "default" not found
Aug 19 10:05:39.719: INFO: Service account default in ns e2e-tests-service-1-u0d1m with secrets found. (5.008143427s)
[It] should be able to up and down services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:277
STEP: 2015-08-19 10:05:39.733844854 -0700 PDT Creating replication controller service1
Aug 19 10:05:39.743: INFO: 2015-08-19 10:05:39.743306217 -0700 PDT Created replication controller with name: service1, namespace: e2e-tests-service-0-uq7x6, replica count: 3
Aug 19 10:05:42.743: INFO: 2015-08-19 10:05:42.743531387 -0700 PDT service1 Pods: 3 out of 3 created, 1 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:42.743: INFO: Ignoring prom push, push gateway unavailable
Aug 19 10:05:45.743: INFO: 2015-08-19 10:05:45.743761212 -0700 PDT service1 Pods: 3 out of 3 created, 1 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:45.743: INFO: Ignoring prom push, push gateway unavailable
Aug 19 10:05:48.744: INFO: 2015-08-19 10:05:48.744014757 -0700 PDT service1 Pods: 3 out of 3 created, 3 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:48.744: INFO: Ignoring prom push, push gateway unavailable
STEP: 2015-08-19 10:05:48.785042949 -0700 PDT Creating replication controller service2
Aug 19 10:05:48.794: INFO: 2015-08-19 10:05:48.794460873 -0700 PDT Created replication controller with name: service2, namespace: e2e-tests-service-0-uq7x6, replica count: 3
Aug 19 10:05:51.794: INFO: 2015-08-19 10:05:51.794644927 -0700 PDT service2 Pods: 3 out of 3 created, 0 running, 3 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:51.794: INFO: Ignoring prom push, push gateway unavailable
Aug 19 10:05:54.794: INFO: 2015-08-19 10:05:54.794888658 -0700 PDT service2 Pods: 3 out of 3 created, 2 running, 1 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:54.794: INFO: Ignoring prom push, push gateway unavailable
Aug 19 10:05:57.795: INFO: 2015-08-19 10:05:57.795130612 -0700 PDT service2 Pods: 3 out of 3 created, 3 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Aug 19 10:05:57.795: INFO: Ignoring prom push, push gateway unavailable
STEP: 2015-08-19 10:06:01.695712701 -0700 PDT Deleting replication controller service1 in namespace e2e-tests-service-0-uq7x6
Aug 19 10:06:03.728: INFO: Deleting RC took: 2.033131846s
Aug 19 10:06:03.732: INFO: Terminating RC pods took: 3.119421ms
[AfterEach] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
STEP: Collecting events from namespace "e2e-tests-services-wmazi".
Aug 19 10:06:03.754: INFO: Pod e2e-tests-container-probe-3kz64 test-webserver-867a36cf-4694-11e5-ae46-42010af07603 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod e2e-tests-pods-34ez0 liveness-exec node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod e2e-tests-service-0-uq7x6 service2-8r097 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod e2e-tests-service-0-uq7x6 service2-rombs node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod e2e-tests-service-0-uq7x6 service2-xgip4 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod e2e-tests-var-expansion-ka55i var-expansion-92c58fc7-4694-11e5-8b1e-42010af07603 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system elasticsearch-logging-v1-jirel node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system elasticsearch-logging-v1-yjw1n node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system fluentd-elasticsearch-pull-e2e-1-minion-qxw8 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system fluentd-elasticsearch-pull-e2e-1-minion-wpl2 node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system kibana-logging-v1-3gfzo node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system kube-dns-v8-hholm node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system kube-ui-v1-8ns01 node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system monitoring-heapster-v8-p052n node=pull-e2e-1-minion-qxw8, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Pod kube-system monitoring-influx-grafana-v1-fnh4t node=pull-e2e-1-minion-wpl2, deletionTimestamp=<nil>
Aug 19 10:06:03.754: INFO: Waiting up to 1m0s for all nodes to be ready
Aug 19 10:06:08.758: INFO: Node pull-e2e-1-minion-qxw8 condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-19 10:00:12 -0700 PDT
Aug 19 10:06:08.758: INFO: Successfully found node pull-e2e-1-minion-qxw8 readiness to be true
Aug 19 10:06:08.758: INFO: Node pull-e2e-1-minion-wpl2 condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-19 10:00:11 -0700 PDT
Aug 19 10:06:08.758: INFO: Successfully found node pull-e2e-1-minion-wpl2 readiness to be true
STEP: Destroying namespace "e2e-tests-services-wmazi" for this suite.
[AfterEach] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:71
STEP: Destroying namespace e2e-tests-service-0-uq7x6
STEP: Destroying namespace e2e-tests-service-1-u0d1m


• Failure [74.164 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:952
  should be able to up and down services [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:277

  Expected error:
      <*errors.StatusError | 0xc208441680>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: ""},
              Status: "Failure",
              Message: "replicationControllers \"service1\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "service1",
                  Kind: "replicationControllers",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      replicationControllers "service1" not found
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:259
```

**Comment by yujuhong** [comment]
LGTM. Waiting on jenkins to be green.

**Comment by smarterclayton** [comment]
All green - will be online at email in case we have more failures outside the window.

**Comment by smarterclayton** [comment]
This is green again, can I get a merge?

**Comment by smarterclayton** [comment]
Maybe from @k8s-oncall?

**Comment by zmerlynn** [comment]
I wish I could respond snarkily as the bot, too. @thockin, could you get on that? ;)

**Comment by smarterclayton** [comment]
:)

**Comment by zmerlynn** [comment]
@saad-ali is primary, but Jenkins is green, so things look happy for a merge.

**Comment by smarterclayton** [comment]
Thanks

**Comment by saad-ali** [comment]
Thanks @zmerlynn, we'll watch Jenkins and see how it goes

**Pull request merged**
