### PR TITLE
integration test run PreShutdownHooks before close.

### LINKED ISSUE #66962: integration test have legacy after case finished, which may result in test flaky
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
When running integration test of a directory, for example,  `make test-integration WHAT=./test/integration/scheduler`, the later cases may result in FAIL. With logs like:
```
E0802 16:07:18.224269   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:40094/api/v1/namespaces: dial tcp 127.0.0.1:40094: connect: connection refused
E0802 16:07:18.775333   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:42557/api/v1/namespaces: dial tcp 127.0.0.1:42557: connect: connection refused
E0802 16:07:20.262979   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:43115/api/v1/namespaces: dial tcp 127.0.0.1:43115: connect: connection refused
E0802 16:07:21.332655   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:39557/api/v1/namespaces: dial tcp 127.0.0.1:39557: connect: connection refused
E0802 16:07:21.427371   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:37194/api/v1/namespaces: dial tcp 127.0.0.1:37194: connect: connection refused
E0802 16:07:21.996686   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:44807/api/v1/namespaces: dial tcp 127.0.0.1:44807: connect: connection refused
E0802 16:07:22.600754   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:45935/api/v1/namespaces: dial tcp 127.0.0.1:45935: connect: connection refused
E0802 16:07:23.823705   68602 repair.go:88] unable to refresh the service IP block: Get http://127.0.0.1:45728/api/v1/services: dial tcp 127.0.0.1:45728: connect: connection refused
E0802 16:07:23.824653   68602 repair.go:73] unable to refresh the port block: Get http://127.0.0.1:45728/api/v1/services: dial tcp 127.0.0.1:45728: connect: connection refused
E0802 16:07:23.828503   68602 controller.go:184] unable to create required kubernetes system namespace kube-system: Post http://127.0.0.1:45728/api/v1/namespaces: dial tcp 127.0.0.1:45728: connect: connection refused
E0802 16:07:23.828835   68602 controller.go:184] unable to create required kubernetes system namespace kube-public: Post http://127.0.0.1:45728/api/v1/namespaces: dial tcp 127.0.0.1:45728: connect: connection refused
E0802 16:07:23.839390   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:45728/api/v1/namespaces: dial tcp 127.0.0.1:45728: connect: connection refused
E0802 16:07:23.852897   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:45026/api/v1/namespaces: dial tcp 127.0.0.1:45026: connect: connection refused
E0802 16:07:24.732762   68602 controller.go:197] unable to sync kubernetes service: Post http://127.0.0.1:35560/api/v1/namespaces: dial tcp 127.0.0.1:35560: connect: connection refused
```

**What you expected to happen**:
Should cleanup all resources after a case finished.

**How to reproduce it (as minimally and precisely as possible)**:
`make test-integration WHAT=./test/integration/scheduler`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66962 

**Special notes for your reviewer**:
Run `PreShutdownHooks` before close master.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
@BenTheElder @deads2k I assumed you might be interested in this.

**Comment by BenTheElder** [comment]
this SGTM, but I don't know enough about the integration test architecture to say for sure 😬

**Comment by deads2k** [comment]
no strong opinion.

/assign @sttts 
/approve

**Comment by sttts** [comment]
The better fix would be to use https://github.com/kubernetes/kubernetes/blob/fd8758b047855699e4672c3417e21cb837f5f414/cmd/kube-apiserver/app/testing/testserver.go#L55 instead of another piece of duct-tape around `startMasterOrDie`. The later should die.

**Comment by sttts** [comment]
/lgtm

as this is flake related.

**Pull request merged**
