### PR TITLE
Remove int support from json patches

### PR DESCRIPTION
**Pull request by ash2k**
**What this PR does / why we need it**:
JSON only contains `int64` and `float64` types for numbers so `int` is not needed.

**Special notes for your reviewer**:
This is a follow up for https://github.com/kubernetes/kubernetes/pull/62981.

**Release note**:
```release-note
NONE
```
/sig api-machinery
/kind cleanup
/cc liggitt sttts

### CODE REVIEW

**Comment by lavalamp** [comment]
/assign @mbohlool 

JSON doesn't reliably transport numbers bigger than 54 bits...

**Comment by lavalamp** [comment]
Why would we remove int? int64 is the thing that's not reliably transmitted by JSON?

**Comment by mbohlool** [comment]
> JSON only contains int64 and float64 types for numbers

JSON number does not have type actually. It is safer to use int32 vs int64 as most parsers support up to 53 bits. Anyhow I don't see any reasoning in the reference issues why we should remove int.

/hold

**Comment by ash2k** [comment]
Originally JSON parser produces only `float64` for numbers when marshalled into `interface{}`. JSON parser we use only ever produces either `int64` or `float64` for numbers. `int` is just not needed.

**Comment by ash2k** [comment]
@mbohlool there is a misunderstanding. I'm talking about parsed JSON (`map[string]interface{}` etc), not JSON itself. I know that JSON does not have integers, only floats.

**Comment by ash2k** [comment]
> Anyhow I don't see any reasoning in the referenced issue why we should remove int.

What is the reasoning to keep it? Why have `int` but not, say, `int32` and/or `int16`?

**Comment by ash2k** [comment]
@mbohlool `/hold cancel` please :)
@liggitt PTAL

**Comment by sttts** [comment]
Sgtm. Can you blame who owns the json patch code?

**Comment by sttts** [comment]
> JSON number does not have type actually. It is safer to use int32 vs int64 as most parsers support up to 53 bits. Anyhow I don't see any reasoning in the referenced issue why we should remove int.

@mbohlool in all our JSON data structure code we have an invariant on the valid types (which do not include `int`). We have code paths which even panic (intentionally) if they happen to hit an unknown type. So this PR is correct and desired from this point of view.

**Comment by ash2k** [comment]
@sttts 
Code in k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go was introduced in https://github.com/kubernetes/kubernetes/pull/40666

k8s.io/apimachinery/pkg/util/mergepatch/util.go was refactored in https://github.com/kubernetes/kubernetes/pull/40942, originally introduced in https://github.com/kubernetes/kubernetes/pull/16980

k8s.io/apimachinery/pkg/util/strategicpatch/patch.go was also introduced in https://github.com/kubernetes/kubernetes/pull/16980

FYI @jackg @mengqiy

**Comment by sttts** [comment]
Lgtm. Giving @jackg @mengqiy some time to take a look.

**Pull request merged**
