### PR TITLE
build: install Go with gimme in GOPATH instead of _output

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Placing the Go toolchain inside a module (like k/k) is problematic for golangci-lint: it led to "load embedded ruleguard rules: rules/rules.go:13: can't load fmt" with Go 1.20 and golangci-lint 1.53.2 because one linter changed go/build.Default (fixed in 1.53.3) and again with Go 1.21 (unknown reason). So instead of _output/local/.gimme, $GOPATH/pkg/kubernetes/gimme is used. A slight advantage is that different Kubernetes work trees can share the same toolchains.

#### Which issue(s) this PR fixes:
Related-to: https://github.com/kubernetes/kubernetes/pull/118996

#### Special notes for your reviewer:

Another alternative would be to not override where gimme installs Go.

#### Does this PR introduce a user-facing change?
```release-note
When installing Go via gimme during a build because there is no Go or the version doesn't match, Kubernetes will now use $GOPATH/pkg/kubernetes/gimme instead of _output/local/.gimme.
```

### CODE REVIEW

**Comment by liggitt** [comment]
-1 on touching files outside the kubernetes-owned paths...

**Comment by liggitt** [comment]
`$GOPATH/pkg/$foo` isn't a well-defined path, right? I wouldn't expect us to drop stuff under that location

**Comment by pohly** [comment]
> -1 on touching files outside the kubernetes-owned paths...

I understand the motivation, but "Go toolchain inside module" seems to be an installation scenario that is prone to random failures.

> $GOPATH/pkg/$foo isn't a well-defined path, right?

I've seen other tools use `pkg`, but I don't remember exactly what it was and whether there is an official convention around it.

What about not messing with gimme install paths at all? Would that also be surprising for developers?

**Comment by pohly** [comment]
That comment applies when the Go tooling looks for code for the current module.

What breaks is importing code from the toolchain in that directory. We can wait and see whether the golangci-lint author figures out whether it is a bug in Go, gocritic, ruleguard or golangci-lint.

**Comment by pohly** [comment]
The problem remains unsolved upstream. I have a different workaround in https://github.com/kubernetes/kubernetes/pull/119860: instead of installing the toolchain elsewhere permanently, it just gets copied temporarily while compiling golangci-lint.

**Comment by liggitt** [comment]
> The problem remains unsolved upstream.

I think it's resolved by github.com/quasilyte/go-ruleguard v0.3.20-0.20230809210434-067b93001706 (xref https://github.com/quasilyte/go-ruleguard/pull/456 and https://github.com/quasilyte/go-ruleguard/pull/455)

can you try `cd hack/tools && go get github.com/quasilyte/go-ruleguard@v0.3.20-0.20230809210434-067b93001706` to see if that resolves the resolution issue on go1.21?

**Comment by pohly** [comment]
That works.

/close

**Pull request closed without merging**
