### PR TITLE
Don't repeat field name in errors

### LINKED ISSUE #10452: Validation changes break Elasticsearch and Kibana logging
```
$ kubectl create -f es-controller.yaml
The ReplicationController "elasticsearch-logging-v1" is invalid:spec.template.spec.containers[0].ports[1].name: spec.template.spec.containers[0].ports[1].name: invalid value 'es-transport-port': must be a IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])* and it must containts at least one letter [a-z], hypens cannot be adjacent to other hyphens): e.g. "http"
```

### PR DESCRIPTION
**Pull request by thockin**
Fixes #10452 short-term issue.

### CODE REVIEW

**Comment by thockin** [comment]
@quinton-hoole @lavalamp

**Comment by quinton-hoole** [comment]
LGTM!

**Comment by lavalamp** [comment]
LGTM

**Comment by zmerlynn** [comment]
This broke tests, and I didn't notice the big X because Shippable was being flaky. @cjcullen is taking #10588

**Pull request merged**
