### PR TITLE
Fix a typo in readme

### PR DESCRIPTION
**Pull request by ihac**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fix a typo in metrics doc.

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
NONE
<!--
If no, just write "NONE" in the release-note block below.
If yes, a release note is required:
Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the string "action required".

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the PR
/ok-to-test
/priority backlog

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by ihac** [comment]
Already fixed by others. Close this PR.

**Pull request closed without merging**
