### PR TITLE
DNS healthz container - add quiet option to stop flooding logs

### PR DESCRIPTION
**Pull request by girishkalele**

### CODE REVIEW

**Comment by a-robinson** [comment]
To be clear, if the logs are ever valuable, we don't need to get rid of them. It's fine for our kube-system components to do some logging, since we need to be able to debug problems. I was just passing on a note that one particular user found the healthz logs a little annoying.

LGTM'ing on the premise that you've already thought this through, but feel free to abandon this change if you think the non-quiet logging has value.

**Comment by girishkalele** [comment]
@a-robinson 

Thanks, yes, I looked at the exechealthz code - it will still print errors and abnormal condition logs. The quiet flag just skips the trace-level logs that are too chatty.

**Comment by girishkalele** [comment]
Added 1.3 milestone - would be good to have this in GKE soon, its flooding the logs.

**Comment by therc** [comment]
For what it's worth, I implemented the flag and have been using it for months. I never once needed or wanted to turn it off. We use a custom Ansible setup, so I forgot to suggest or create a Salt PR.

**Comment by girishkalele** [comment]
@a-robinson
 
Just rebased, no changes.

**Comment by girishkalele** [comment]
@k8s-bot Test this again.

**Comment by fejta** [comment]
@k8s-bot node e2e test this issue #24479

**Pull request merged**
