### PR TITLE
Revert #63905: Setup dns servers and search domains for Windows Pods

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

From https://github.com/kubernetes/kubernetes/pull/63905#issuecomment-396709775:

> I don't think this change does anything on Windows. On windows, the network endpoint configuration is taken care of completely by CNI. If you would like to pass on the custom dns polices from the pod spec, it should be dynamically going to the cni configuration that gets passed to CNI. From there, it would be passed down to platform and would be taken care of appropriately by HNS.

> etc\resolve.conf is very specific to linux and that should remain linux speicfic implementation. We should be trying to move away from platform specific code in Kubelet.
Docker is not managing the networking here for windows. So it doens't really care about any network settings. So passing it to docker shim's hostconfig also doens;t make sense here.

DNS for Windows containers will be set by CNI plugins.  And this change also introduced two endpoints for sandbox container.  So this PR reverts #63905 .

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

The PR should also be cherry-picked to release-1.11.

Also, https://github.com/kubernetes/kubernetes/issues/66588 is opened to track the process of pushing this to CNI.

**Release note**:

```release-note
Revert #63905: Setup dns servers and search domains for Windows Pods. DNS for Windows containers will be set by CNI plugins.
```

/sig windows
/sig node
/kind bug

### CODE REVIEW

**Review by PatrickLang — APPROVED** [review]

**Comment by PatrickLang** [comment]
Agreed w/ revert. This causes an extra NIC to be added by Docker. That can break DNS because it won't have the right DNS settings.

Will add lgtm once @daschott or I test it in a cluster

**Comment by PatrickLang** [comment]
Also looking for 2nd review with @madhanrm

**Comment by PatrickLang** [comment]
/priority critical-urgent
this causes a regression in DNS reliability from v1.10

**Comment by madhanrm** [comment]
LGTM, since this is a revert

**Comment by alinbalutoiu** [comment]
LGTM. We should have a document on how Windows supports the DNS to be passed to the pods.

**Comment by PatrickLang** [comment]
Just to clarify a bit - the Docker DNS config is used for networks managed by Docker, but not CNI. The previous PR (being reverted here) used the Docker DNS config.

The bad side effect is that setting these options in the Docker config causes another virtual NIC to be added to the pod. That NIC only has the NAT DNS servers, which don't include kube-dns. That causes intermittent failures accessing the cluster DNS on v1.11.

This is a regression from v1.10

**Comment by feiskyer** [comment]
ping @dchen1107 for approval

**Comment by PatrickLang** [comment]
Manual testing done. It's correctly doing just 1 NIC now
```
Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (01d5abe6-eth0):

   Connection-specific DNS Suffix  . : default.svc.cluster.local
   Link-local IPv6 Address . . . . . : fe80::2905:3914:d30c:6484%23
   IPv4 Address. . . . . . . . . . . : 10.240.0.11
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 10.240.0.1
```

**Comment by PatrickLang** [comment]
Need a linked issue & PR in CNI repo too

**Comment by feiskyer** [comment]
> Need a linked issue & PR in CNI repo too

@PatrickLang Which issue are you referring?

**Pull request merged**
