### PR TITLE
Update created-by annotation details

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
This PR removes created-by annotation item from the deprecation section and indicates that it has been removed in 1.9 release.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
1.9 release is not rolled out yet. This is an early modification to the change log.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by crimsonfaith91** [comment]
@liggitt I updated the change log accordingly. Pinging you for review. :)

**Review by janetkuo — COMMENTED** [review]
This should be done in 1.9 change log, instead of 1.8.

**Comment by liggitt** [comment]
And not made directly, gathered by release tool from description of the PR that made the change

**Comment by crimsonfaith91** [comment]
@janetkuo @liggitt Thanks for clarifying! It looks weird to change 1.8 log for a 1.9 change. I thought I was asked to modify 1.8 log from this comment: https://github.com/kubernetes/kubernetes/pull/54445#issuecomment-340833587

**Comment by janetkuo** [comment]
> I thought I was asked to modify 1.8 log from this comment: https://github.com/kubernetes/kubernetes/pull/54445#issuecomment-340833587

What @liggitt meant was the **release-note** block in the PR description. It'll be parsed by release tool to generate changelogs (done by release team).

**Comment by crimsonfaith91** [comment]
@janetkuo i see! thanks!

**Pull request closed without merging**
