### PR TITLE
continue Fix error format and info for get_test.go

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
continue fix the error info 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49441 

**Special notes for your reviewer**:

**Release note**:

```release-note
    NONE

### CODE REVIEW

**Comment by jianglingxia** [comment]
cc @derekwaynecarr  @ghodss 
thanks for your review

**Comment by jianglingxia** [comment]
PTAL @mengqiy
/assign @pwittrock
thanks for you review!

**Comment by adohe** [comment]
ok to test.

**Pull request merged**
