### PR TITLE
don't assert error inside wait.Poll loops

### PR DESCRIPTION
**Pull request by songxiao-wang87**
What type of PR is this?
/kind bug

What this PR does / why we need it:
see https://github.com/kubernetes/kubernetes/pull/114411

Which issue(s) this PR fixes:
none

Special notes for your reviewer:
none

Does this PR introduce a user-facing change?
none

```release-note

NONE

```

### CODE REVIEW

**Comment by songxiao-wang87** [comment]
@yangjunmyfm192085

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Comment by aojea** [comment]
great , thanks for doing this

/lgtm
/approve

**Pull request merged**
