### PR TITLE
Merge pkg/api/unversioned.go into pkg/api/unversioned/types.go

### LINKED ISSUE #14584: merge pkg/api/unversioned.go and pkg/api/unversioned/types.go
I assume we should merge them to pkg/api**s**/unversioned/types.go?

@kubernetes/goog-csi

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #14584

So types in pkg/api/unversioned.go are part of the unversioned package

It's just one copy-paste and a bunch of sed.

@lavalamp @krousey

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, but this is the sort of thing that will make cherry-picks very unpleasant. I would like it anyway... @brendandburns opinions?

**Comment by lavalamp** [comment]
Let's try and get it in. You may have to do some work to get the cherry pick in.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
@caesarxuchao can you rebase this please?

**Comment by caesarxuchao** [comment]
Rebased.

**Comment by lavalamp** [comment]
lgtm assuming tests pass.

**Comment by caesarxuchao** [comment]
add back "lgtm" as it's just a rebase

**Pull request merged**
