### PR TITLE
GCE: bump COS image version to cos-stable-63-10032-71-0

### PR DESCRIPTION
**Pull request by yujuhong**
```release-note
GCE: bump COS image version to cos-stable-63-10032-71-0
```

### CODE REVIEW

**Comment by dashpole** [comment]
Is there a corresponding change in test-infra?

**Comment by yujuhong** [comment]
Once this PR lands, all GCE tests on the master branch will be testing overlay2 + live-restore. 
This does not affect GKE, which we will determine how to roll out later.

/approve no issue

> Is there a corresponding change in test-infra?

Updated the node e2e configuration in https://github.com/kubernetes/test-infra/pull/5965

**Comment by yujuhong** [comment]
Manually applied `approved` based on @dchen1107's LGTM

**Pull request merged**
