### PR TITLE
Fix CHANGELOG-1.27 cronjob correctly

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by whyrass — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

Does this need a backport to the 1.27 release branch?

**Comment by kkkkun** [comment]
> /lgtm
> 
> Does this need a backport to the 1.27 release branch?

I will cherry-pick to 1.27 when merged.

**Pull request merged**
