### PR TITLE
Add name to kubernetes service https port.

### PR DESCRIPTION
**Pull request by cjcullen**
This was suggested on Slack today. I figured I'd send a PR rather than open an issue.

### CODE REVIEW

**Comment by cjcullen** [comment]
@thockin see any problems doing this?

**Comment by smarterclayton** [comment]
This would be better if it was done on top of https://github.com/kubernetes/kubernetes/pull/14871

**Comment by smarterclayton** [comment]
Actually, this is fixed by https://github.com/kubernetes/kubernetes/pull/14871 incidentally (he added a name)

**Comment by cjcullen** [comment]
SGTM. Closing this in favor of #14871.

**Pull request closed without merging**
