### PR TITLE
Extracting EndpointSliceTracker into a new shared EndpointSlice package

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The EndpointSlice and EndpointSliceMirroring controllers share a lot of logic, most notably the EndpointSliceTracker which was nearly identical. This extracts that out into a new util package. This package may also be useful in the future for extracting other code shared by the controllers.

**Special notes for your reviewer**:
This is a follow up to https://github.com/kubernetes/kubernetes/pull/93441. I'm not sure if this should or should not be part of the 1.19 release.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig network
/priority important-longterm
/assign @freehan

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
Hi @robscott The code freeze is starting 12.11.2020 which about 3 weeks away and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time. As the PR is tagged for 1.20, is it still planned for this release?

**Comment by robscott** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/99997.

/close

**Pull request closed without merging**
