### PR TITLE
Update kube-openapi to fix schema parsing

### PR DESCRIPTION
**Pull request by apelisse**
There is a bug with the Time type that it doesn't accept null, which is
inconvenient because creationTimeStamp should always be set to null.

**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
/lgtm
you might need to run hack/update-staging-godeps.sh

**Comment by apelisse** [comment]
> you might need to run hack/update-staging-godeps.sh

Good catch Jenny, you saved me a few hours here :-)

**Pull request merged**
