### PR TITLE
low hanging fruit for using cobra commands

### PR DESCRIPTION
**Pull request by deads2k**
This makes the simple updates to use cobra commands instead of individual ones

/assign liggitt
/assign ncdc
/assign sttts

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton this will probably need your approval since it hits so many commands.

**Comment by smarterclayton** [comment]
/lgtm

This is the right way to unify our commands (and avoid hyperkube and individual binary drift)

**Comment by deads2k** [comment]
> /cherrypick release-1.9
>  Delete branch

@kargakis did I spell it wrong or is the cherrypick bot openshift only?

**Comment by kargakis** [comment]
Yeah, we only use it in Openshift for now

**Comment by deads2k** [comment]
> Yeah, we only use it in Openshift for now

man that's annoying.  That my second favorite bot.

**Pull request merged**
