### PR TITLE
Fixing issue with capitalization in allow-privileged

### PR DESCRIPTION
**Pull request by hyperbolic2346**
**What this PR does / why we need it**:
Config option in kubernetes-master allow-privileged would do odd things if you used True instead of true.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/374
**Special notes for your reviewer**:

**Release note**:

```release-note
Fixed issue with kubernetes-worker option allow-privileged not properly handling the value True with a capital T.
```

### CODE REVIEW

**Comment by Cynerva** [comment]
@hyperbolic2346 If we're fixing this in kubernetes-worker, can we fix it in kubernetes-master too? It also has the `allow-privileged` option and I would like to keep their behavior consistent.

See https://github.com/hyperbolic2346/kubernetes-1/blob/ec0bedbf43360e29be32fc0e538a20678f6c3fe0/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L841

**Comment by hyperbolic2346** [comment]
@Cynerva Added in kubernetes-master changes.

**Comment by Cynerva** [comment]
Thanks!

/approve no-issue
/lgtm

**Pull request merged**
