### PR TITLE
Add max docker api version support

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
WIP for https://github.com/kubernetes/kubernetes/issues/53221

**Comment by jessfraz** [comment]
LGTM :)

**Comment by derekwaynecarr** [comment]
I am fine with this change as a way of tracking the internal dockershim.

**Comment by derekwaynecarr** [comment]
is there a strong need to have this in the 1.12 milestone?

**Comment by dims** [comment]
@derekwaynecarr this is the response to the point you made in https://github.com/kubernetes/kubernetes/pull/64283#issuecomment-417893539 (we bumped the docker API version when we updated vendor depenencies)

**Comment by derekwaynecarr** [comment]
@dims i tend to agree w/ @yujuhong analysis https://github.com/kubernetes/kubernetes/pull/64283#issuecomment-418917383

**Pull request closed without merging**
