### PR TITLE
e2e/examples: remove obsolete tests

### PR DESCRIPTION
**Pull request by pohly**
These tests depend on files that were removed in
https://github.com/kubernetes/kubernetes/pull/61246 and thus can no
longer be run in Kubernetes. Moving the tests to kubernetes/examples
is tracked in https://github.com/kubernetes/examples/issues/214.

The file removal did not break the automated E2E testing probably
because the tests are under the Feature:Example tag and thus not
enabled during normal CI runs.

**What this PR does / why we need it**:

Removing also the obsolete tests makes it simpler to rework the
"repo-root" setting because less code uses it.

**Special notes for your reviewer**:

This was already discussed on Slack. @serathius agreed to having the code removed.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dixudx — COMMENTED** [review]
/ok-to-test

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

Thanks for doing this!

**Comment by pohly** [comment]
Looks like PR #69103 is now also ready for merging. It contains the same change, so we can close this one here.

**Pull request closed without merging**
