### PR TITLE
Fix incorrect volume plugin name in log, PersistentDisk->EBS

### PR DESCRIPTION
**Pull request by liubin**
Change a log word that may be confuse people.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by jdumars** [comment]
Hi, please make sure release notes are properly taken care of. Thanks!

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/59229)

**Comment by liubin** [comment]
I'm sorry, corrected the release note. @jdumars

**Comment by liubin** [comment]
ping @jsafrane

**Pull request closed without merging**
