### PR TITLE
Add request.memory to  kube-apiserver, kube-controller-manager, kube-scheduler static pod

### PR DESCRIPTION
**Pull request by max8899**
Make kube-apiserver, kube-controller-manager, kube-scheduler static pod with qos class Garanteed

Signed-off-by: Lei Gong <lgong@alauda.io>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
recently my kube-apiserver keeps restarting. I found that this was due to lack of disk space and was expelled by evict manager along with other normal pod. Then I found that the qos class of kube-apiserver is Bursted, in which case will be evicted by kubelet firstly. So may be we should specify both the limits and requests in spec.resources of the static pod so that the Qos could be Garanteed.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: Add requests.memory for static pod so that they will not evicted firstly when lacking of resource.
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
@max8899 thank you for the PR.

please add a release note under "...user facing change" in the PR description:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md

```release-note
kubeadm: ensure QoS class "Guaranteed" for control plane static pods
```

/ok-to-test
/priority backlog

@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @timothysc @fabriziopandini

**Comment by max8899** [comment]
@fabianofranz  I comes from the estimate referring to docker stat of one of my apiserver, and yes , it might be incorrect. Found an old issue: https://github.com/kubernetes/kubernetes/issues/12002, and will continue to work on this.

**Comment by max8899** [comment]
@fabriziopandini as mentioned in slack, remaining the qos class to be Burstable, but adding the requests.memory will reduce the oom_score_adj value

**Comment by rosti** [comment]
Hi @max8899 and thanks for your contribution!

Can you also change the commit message and PR caption & justification so that they reflect the what the actual change is doing now?

**Comment by seh** [comment]
It's hard to tell whether this change is adding resource limits where they didn't exist before. Is that what you're doing here?

**Comment by fabriziopandini** [comment]
@max8899 I'm not 100% sure it can be applied to static pods, but what about using https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ instead?

@rosti @neolit123 @mauilion opinions?

**Comment by neolit123** [comment]
@fabriziopandini 
> I'm not 100% sure it can be applied to static pods,

i think, yes.

> but what about using  https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ instead?

re: critical addons: we are already doing `system-cluster-critical` for the CP pods and `system-node-critical` for kube-proxy.

QoS classes on the other hand are something else, yet and i have no context on how they relate to priority and preemption, exactly.

@seh 
> It's hard to tell whether this change is adding resource limits where they didn't exist before. Is that what you're doing here?

it's a case of adding limits so they satisfy a QoS class.
explained here: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed
i don't think there are limits by default.

@max8899 
> I comes from the estimate referring to docker stat of one of my apiserver, and yes , it might be incorrect

i personally think the memory limit of 250 is low.
we should not end up in a state where it does work for the minimum viable kubeadm cluster, but once put in production all users need to bump the value manually - and it's not exactly a beginner level tweak.

adding 1Gi might be on the safer side.

**Comment by seh** [comment]
I don't see where this is adding _limits_ that were missing before; it looks to be adding _requests_ that were missing. [`staticpod.ComponentResources` defines only the requests](https://github.com/kubernetes/kubernetes/blob/18d93cffae003def7e43e01921b81ee7cbc92ed0/cmd/kubeadm/app/util/staticpod/utils.go#L79), and says nothing of limits, which means they default to the node's allocatable values.

I would not run my API servers with a limit at this point; I've allowed them to burst up to using nine CPUs, even if they're running much more quietly at other times. Putting a hard cap on that would be unsuitable for our deployments.

**Comment by max8899** [comment]
@neolit123 @fabianofranz  @rosti @seh thanks for your reply. I'll explain why this pr is needed and what did I do.

Since every component communicate with api server, people will get into trouble when it dies, e.g. when the nodes is lack of resource, which is exactly my case, when api server dies, I don't know what happened to my k8s cluster, is every component down? is node in healthy state? It'll take me a lot of time to reading system logs to find out the reason instead of using kubectl. 

So at first I came across the idea that **api server need to be died last in the case of OOM**, so I added limits to static pod, this helps these critical pod have a Guaranteed QOS class, which means, `oom_score_adj` is -998. 

But I found this is not a new problem, and it has discussed in issue https://github.com/kubernetes/kubernetes/issues/12002, it's better to limit the memory of api server to 30% of the node or more. But we don't know the memory of a node before the pod is not bind to it. 

In fact, adding limits might not be what users expected. Some people put api server into a single node and just hopes it will use all of the resources of this machine.

So the problem turns to "**let api server use memory as much as possible and not evicted by evict manager of OOM killer**"

It's impossible :）.

@neolit123 thanks for the support of my idea, but I found 1Gi might not be enough, like in issue https://github.com/kubernetes/kubernetes/issues/67732, one api server costs 50Gi memory.

So the problems turns to "**let api server not the first to be evicted**".  This means we need to reduce the `oom_score_adj`. The following formula shows how this value is calculated:
`oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity` 

A larger requests.memory helps to reduce the `oomScoreAdjust`, 250Mi might reduce this value a bit, but it helps comparing to `besteffortOOMScoreAdj` which is 1000.

**Comment by neolit123** [comment]
> So the problems turns to "let api server not the first to be evicted". This means we need to reduce the oom_score_adj. The following formula shows how this value is calculated:
oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity
> A larger requests.memory helps to reduce the oomScoreAdjust, 

/cc @vishh
any comments on the above and how we proceed with this PR?
does the 250Mi make sense here?

**Comment by neolit123** [comment]
@seh 
> I don't see where this is adding limits that were missing before; it looks to be adding requests that were missing. 

my mistake, these are requests.

**Comment by max8899** [comment]
@fabriziopandini @neolit123 @rosti @seh 

250 Mi is fairly enough for requests, any feedback?

**Comment by seh** [comment]
That value is a reasonable choice, but the title of the PR is still misleading. This patch does not wind up changing the pod QoS. Given that, how does this patch help to achieve your goal?

**Comment by neolit123** [comment]
@seh as far as understand reading the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed) , qos will be guaranteed by matching the values.

**Comment by seh** [comment]
Yes, I'd agree _if_ the proposed code changes here were setting a limit. As [I noted previously](https://github.com/kubernetes/kubernetes/pull/72424#issuecomment-452040511), I don't see such limits being set. What am I missing?

**Comment by neolit123** [comment]
> Yes, I'd agree if the proposed code changes here were setting a limit. As I noted previously, I don't see such limits being set. What am I missing?

you are right. :roll_eyes: 

so, if we have to set the request and limit to match the 250Mi to satisfy a QoS class this will not work as the limit itself would be too low to satisfy all use cases.

> Every Container in the Pod must have a memory limit and a memory request, and they must be the same.
Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.

@max8899 this sort of drifts this PR change into an unknown state.

**Comment by max8899** [comment]
@neolit123 change the pr title

@seh The code of limit has been removed from my origin pr. I've explained it [here](https://github.com/kubernetes/kubernetes/pull/72424#issuecomment-452203348) 

Anything still blocking, please let me know

**Pull request closed without merging**
