### PR TITLE
Fix golint issues for `core/v1/validation`

### PR DESCRIPTION
**Pull request by stevedotmt**
reference https://github.com/kubernetes/kubernetes/issues/68026

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fix golint issue in `pkg/apis/core/v1/validation`

**Which issue(s) this PR fixes**:

Fixes #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by gkarthiks** [comment]
hi @steveazz  please use `Ref:` or something like that instead of `Fixes` as this would close the issue. Thanks.

**Comment by steveazz** [comment]
> please use Ref: or something like that instead of Fixes as this would close the issue. Thanks.

@gkarthiks so sorry about that! Thank you for the tip 🙇

**Pull request merged**
