### PR TITLE
Automated cherry pick of #118053: Updating the nodeAffinity of gated pods having nil affinity

### LINKED ISSUE #118052: Updating the nodeAffinity of gated pods having nil affinity is not allowed
### What happened?

When a gated pod is created with nil affinity and a user/controller tries to update its nodeAffinity, the validation fails.

### What did you expect to happen?

The pod gets updated with the new affinity as per rules in [KEP-3838](https://github.com/kubernetes/enhancements/commit/ac65b5853a9a5b8fb77a8c3069c07780057a4c9e)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod as in the following using `kubectl create`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: example-no-affinity-
spec:
  schedulingGate:
    - name: "example-gate" # just to ignore any other component that should add a scheduling gate
  containers:
    - name: example-container
      image: 'quay.io/openshifttest/hello-openshift:1.2.0'
```
2. Try to update the pod as with:
```shell
 kubectl patch pod example-no-affinity-hz4lz -p '{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"expr","operator":"In","values":["value"]}]}]}}}}}'

```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
Kubernetes Version: v1.27.1
```

</details>

### Cloud provider

<details>
Tested on kind and OpenShift
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aleskandro**
Cherry pick of #118053 on release-1.27.

#118053: Updating the nodeAffinity of gated pods having nil affinity

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed #118052: nodeAffinity on pods can change prior to scheduling gates being removed even when podSpec.affinity is nil in the initial spec, this matches the 1.28 behavior to allow consistent integrators to be written.
```

### CODE REVIEW

**Comment by ahg-g** [comment]
/lgtm
/approve

but you need an api-reviewer to approve

**Comment by aleskandro** [comment]
Thanks @ahg-g, 

maybe @ligitt can help, as he approved the parent one. I also see lavalamp is vacationing.

Hi @liggitt, can you approve this PR?

/assign ligitt

**Comment by cpanato** [comment]
@aleskandro this CP is only required for the release-1.27 branch?

**Comment by aleskandro** [comment]
@cpanato I'd argue yes, as the feature is beta starting from 1.27+. WDYT?

**Comment by cpanato** [comment]
> @cpanato I'd argue yes, as the feature is beta starting from 1.27+. WDYT?

thanks for the clarification and for quick reply :)

**Review by cpanato — APPROVED** [review]
/triage accepted
/lgtm
/priority important-soon

**Comment by aleskandro** [comment]
I rebased the PR to the latest 1.27 changes, but the failure test seems to depend on https://github.com/kubernetes/kubernetes/pull/119005

**Comment by pohly** [comment]
@aleskandro: did you run `hack/update-vendor.sh` after rebasing? When I run it in your branch, I get changes that you need to include in your PR.

**Comment by aleskandro** [comment]
Hi @pohly should I? My changes should not involve any update to the deps.

**Comment by pohly** [comment]
I agree that it is odd, but it would be a way forward. Let's discuss in https://github.com/kubernetes/kubernetes/issues/119016.

**Comment by liggitt** [comment]
dependency test fix merged

**Comment by aleskandro** [comment]
Hi @liggitt thanks!

May I get an lgtm again?

/unhold

**Pull request merged**
