### PR TITLE
Added [Privileged] label for the test cases, which is trying to run privileged containers

### PR DESCRIPTION
**Pull request by pontiyaraja**
**What this PR does / why we need it**:

- Added **[Privileged]** label for test cases. 
- These test cases are required special permission(privileged access) to run privileged containers 
- This action is disallowed by the [pod security policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```
error message :
Error creating Pod
  Expected error:
      <*errors.StatusError | 0xc000ed6360>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
              Status: "Failure",
              Message: "Pod \"pod-host-path-test\" is invalid: [spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy, spec.containers[1].securityContext.privileged: Forbidden: disallowed by cluster policy]",
              Reason: "Invalid",
              Details: {
                  Name: "pod-host-path-test",
                  Group: "",
                  Kind: "Pod",
                  UID: "",
                  Causes: [
                      {
                          Type: "FieldValueForbidden",
                          Message: "Forbidden: disallowed by cluster policy",
                          Field: "spec.containers[0].securityContext.privileged",
                      },
                      {
                          Type: "FieldValueForbidden",
                          Message: "Forbidden: disallowed by cluster policy",
                          Field: "spec.containers[1].securityContext.privileged",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 422,
          },
      }
      Pod "pod-host-path-test" is invalid: [spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy, spec.containers[1].securityContext.privileged: Forbidden: disallowed by cluster policy]
  not to have occurred

```
**Release note**:

```release-note
NONE
```

/area test
/sig rc
/sig testing
/sig architecture
/kind cleanup

cc @spiffxp

/assign @bgrant0607 @janetkuo

### CODE REVIEW

**Comment by dims** [comment]
@pontiyaraja we may have some conformance tests that need this label too. Can you please run the conformance tests without giving privileged and see what fails? (and then add the label to the ones that fail)

example of what i ran into earlier : https://github.com/kubernetes/kubernetes/issues/59978

**Comment by pontiyaraja** [comment]
@dims Sure, I will test all conformance tests, and add the [privileged] label where ever it requires.

**Comment by spiffxp** [comment]
/remove-area test
/area conformance

@pontiyaraja to echo what @dims said, you should be focusing first on adding these sorts of tags to tests that use `ConformanceIt`

**Comment by pontiyaraja** [comment]
@spiffxp okay Aaron, I will add labels for conformance tests first.

**Review by timothysc — APPROVED** [review]
/lgtm 

However, I don't have the bandwidth to audit whether these tests "should" be privileged.

**Comment by dims** [comment]
@timothysc From my previous experiment, they all work fine without privileged, as the privileged mode is needed *ONLY* when these run on SELinux please see chatter in:
https://github.com/kubernetes/kubernetes/issues/59978

**Comment by pontiyaraja** [comment]
@timothysc @dims I tested it in the below environment.

```
Static hostname: globant-Latitude-3490
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: d1dd76a3e5e74d31bb287281eb2c7351
           Boot ID: 5644964c9dd04c56a557f4171da4a53f
  Operating System: Ubuntu 16.04.5 LTS
            Kernel: Linux 4.15.0-36-generic
      Architecture: x86-64

```
All the tests are required Privileges label

**Comment by timothysc** [comment]
@pontiyaraja I'm pretty surprised by that, and it contradicts what @dims stated earlier.  We need someone who has the bandwidth to dig through each test.

**Comment by dims** [comment]
@pontiyaraja from memory, there are 2 things `--allow-privileged` in the kubelet command line and the `privileged: true` in security context. I'd like to see which of these tests that you have marked as with the tag fail when both are false... ie (don't set --allow-privileged in kubelet and remove privileged from security context).

**Comment by pontiyaraja** [comment]
@dims I have tested it by removing/set to false privileged from security context, two test cases in host_path.go are success without any failure and volume based tests are failing for below scenarios,

- Driver: hostPathSymlink   
- Driver: ceph [Feature:Volumes]
- Driver: nfs
- Driver: iscsi [Feature:Volumes]
- Driver: rbd [Feature:Volumes]

**Comment by dims** [comment]
@pontiyaraja So... 
- for the things that fail as you mentioned let's add the privileged label
- for the tests that do not fail, let's remove the privileged from security context (and of course do not add the label)

Let's do the above and try getting it past different folks in review.

**Comment by mgdevstack** [comment]
@pontiyaraja Is it good for review or any actionable points remaining (apart from rebasing)?

**Comment by pontiyaraja** [comment]
> @pontiyaraja Is it good for review or any actionable points remaining (apart from rebasing)?

@mgdevstack this PR has to be closed. can't add privileged tag for some test cases.

**Pull request closed without merging**
