### PR TITLE
don't retry apiserver retryable errors on the e2e framework

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup

```release-note
NONE
```

Don't handle apiserver request retries on the e2e framework:
- the client-go already handle retryable errors 
https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/staging/src/k8s.io/client-go/rest/with_retry.go#L163-L183

- the retryable logic should not be unbounded, or it can keep retrying forever
https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/staging/src/k8s.io/client-go/rest/request.go#L873-L874

- this will drift from users setups, with the possibility of hide real issues

### CODE REVIEW

**Comment by tallclair** [comment]
> the client-go already handle retryable errors

Can you point to where client-go handles retryable API errors? All I can find is https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/staging/src/k8s.io/client-go/rest/request.go#L859-L871, but that only handles network errors.

> the retryable logic should not be unbounded, or it can keep retrying forever

This happens within a polling loop, so it's bounded by the poll timeout. Note that this doesn't actually retry the request directly, it just says "continue polling" rather than treating the error as terminal.

> this will drift from users setups, with the possibility of hide real issues

This is a tricky balance. On the one hand, I agree - we don't want to hide issues in test retry logic. On the other hand, our CI runs pretty hot with more churn than a typical cluster, so is more prone to things like timeout errors. We're balancing not wanting tests to flake to transient errors, and not wanting to hide real issues in retries.

With that in mind, I at least agree that internal (500) errors should not be considered retryable - those likely reveal real bugs (e.g. a panic) that should be fixed.

**Comment by tallclair** [comment]
Sorry if I'm missing something, but the code block you linked to seems to just check `f.IsErrorRetryable(httpReq, err)`, and the only implementation of that I can find is [here](https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/staging/src/k8s.io/client-go/rest/request.go#L859-L871), which doesn't seem to check API errors. Am I missing something?

> ... we are converting "retryable errors" in wait.PollTimeout errors

In most cases where we use `handleWaitingAPIError` we also capture the last API error, and use that instead of the timeout error in that case: https://github.com/kubernetes/kubernetes/blob/751e9c0f5b8af2c9f0e5f63e019c8e9fa483306f/test/e2e/framework/pod/wait.go#L282-L285

However, I see we're missing that logic in a few places, which should be fixed.

**Comment by aojea** [comment]
> Sorry if I'm missing something, but the code block you linked to seems to just check `f.IsErrorRetryable(httpReq, err)`, and the only implementation of that I can find is [here](https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/staging/src/k8s.io/client-go/rest/request.go#L859-L871), which doesn't seem to check API errors. Am I missing something?
> 
> >

hmm,I need to double check but I think that client-go follows the stdlibrary semantics https://pkg.go.dev/net/http#Client.Do

> An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem). A non-2xx status code doesn't cause an error.

a 50x doesn't have err != nil

**Comment by aojea** [comment]
@tallclair please check this snippet https://gist.github.com/aojea/31ab71c894c15f46a567c5e8aa235a17

```sh
go run clientgo_retry.go 
I0506 09:22:52.057536   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:52.057628   18842 round_trippers.go:469] Request Headers:
I0506 09:22:52.057647   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:52.060300   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 2 milliseconds
I0506 09:22:53.061235   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 1 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:53.061325   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:53.061339   18842 round_trippers.go:469] Request Headers:
I0506 09:22:53.061357   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:53.061821   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:54.062547   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 2 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:54.062636   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:54.062651   18842 round_trippers.go:469] Request Headers:
I0506 09:22:54.062669   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:54.063019   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:55.063223   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 3 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:55.063314   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:55.063327   18842 round_trippers.go:469] Request Headers:
I0506 09:22:55.063345   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:55.063781   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:56.063987   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 4 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:56.064065   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:56.064079   18842 round_trippers.go:469] Request Headers:
I0506 09:22:56.064098   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:56.064460   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:57.064664   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 5 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:57.064735   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:57.064750   18842 round_trippers.go:469] Request Headers:
I0506 09:22:57.064767   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:57.065102   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:58.065345   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 6 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:58.065462   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:58.065476   18842 round_trippers.go:469] Request Headers:
I0506 09:22:58.065495   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:58.065924   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:22:59.066563   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 7 to https://127.0.0.1:33267/?timeout=30s
I0506 09:22:59.066647   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:22:59.066660   18842 round_trippers.go:469] Request Headers:
I0506 09:22:59.066678   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:22:59.067151   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:23:00.067424   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 8 to https://127.0.0.1:33267/?timeout=30s
I0506 09:23:00.067535   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:23:00.067549   18842 round_trippers.go:469] Request Headers:
I0506 09:23:00.067568   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:23:00.068015   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:23:01.068607   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 9 to https://127.0.0.1:33267/?timeout=30s
I0506 09:23:01.068731   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:23:01.068746   18842 round_trippers.go:469] Request Headers:
I0506 09:23:01.068769   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:23:01.069222   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
I0506 09:23:02.070220   18842 with_retry.go:241] Got a Retry-After 1s response for attempt 10 to https://127.0.0.1:33267/?timeout=30s
I0506 09:23:02.070295   18842 round_trippers.go:463] GET https://127.0.0.1:33267/?timeout=30s
I0506 09:23:02.070308   18842 round_trippers.go:469] Request Headers:
I0506 09:23:02.070324   18842 round_trippers.go:473]     Accept: application/json, */*
I0506 09:23:02.070707   18842 round_trippers.go:574] Response Status: 500 Internal Server Error in 0 milliseconds
duration error: 10.013440484s
```

it retries by default 10 times, if the retry-after is 1 second it means the request blocks for 10 seconds ... if we add another loop on top sounds, excessive to me

**Comment by liggitt** [comment]
In general, I agree 500 errors shouldn't be retried/masked, but if our e2e was encountering timeout or toomanyrequests errors, that still seems worth retrying on. I'm not confident that client-go will internally retry those in all scenarios.

**Comment by aojea** [comment]
> I'm not confident that client-go will internally retry those in all scenarios.

/hold

It seems most of the points here are in favor of the retries, I accept the majority ...

**Pull request closed without merging**
