### PR TITLE
Remove ExportOptions from api/internal and use unversioned

### PR DESCRIPTION
**Pull request by smarterclayton**
Should only have one internal object in use

Part of #37530

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37532)

### CODE REVIEW

**Comment by smarterclayton** [comment]
@caesarxuchao this is part of the "move unversioned into its own API group" PR

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
lgtm

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
Applying label.

**Comment by caesarxuchao** [comment]
lgtm.

**Pull request merged**
