### PR TITLE
e2e: fix unit test

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Unit tests under test/e2e didn't run and some of them became broken over time. This PR fixes the broken ones and ensures that pull-kubernetes-unit executes the tests.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
does this code run in CI?

**Comment by pohly** [comment]
It does not run in the CI because of https://github.com/kubernetes/kubernetes/blob/b74d023e70d6064c7f3f77031e7d26ec38497fc9/hack/make-rules/test.sh#L47

I am currently fixing one other failure in test/e2e/framework/node/wait_test.go. With that fix, unit tests under test/e2e/framework could get enabled in pull-kubernetes-unit (= aka "make test"). Should I add that in this PR or create separate ones?

**Comment by pohly** [comment]
I have pushed some additional commits. I can move some of those into separate PRs, if that is preferred.

**Comment by pohly** [comment]
The tests ran successfully in this job: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109961/pull-kubernetes-unit/1524326330156453888

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

thanks for catching this (!)

**Pull request merged**
