### PR TITLE
optimize podSandboxChanged() function and fix some function notes

### PR DESCRIPTION
**Pull request by NickrenREN**

### CODE REVIEW

**Comment by NickrenREN** [comment]
@thockin  @feiskyer  Could one of you help ask k8s-bot to test and review ?  Thanks

**Comment by feiskyer** [comment]
@NickrenREN  It seems this PR didn't make any sense. `neccessary` is correct and words inside sentence should be lower-cased.

**Comment by NickrenREN** [comment]
@feiskyer  Thanks !  Modified.
ps: I just want to keep the notes style consistent before

**Comment by Random-Liu** [comment]
> @NickrenREN It seems this PR didn't make any sense. neccessary is correct and words inside sentence should be lower-cased.

It seems that `neccessary` is not correctly spelled.

/lgtm
/approve

**Comment by Random-Liu** [comment]
/lgtm

@NickrenREN Thanks for the fix!

**Comment by NickrenREN** [comment]
＠k8s-bot ok to test

**Comment by NickrenREN** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
