### PR TITLE
[kubelet] nodestatus: remove map nil check

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Remove unncessary nil check around map for reading

In this case, we are reading from this map: devicePluginCapacity, and not writing to it, so this should be okay.

From Effective Go: "A nil map behaves like an empty map when reading, but attempts to write to a nil map will cause a runtime panic; don't do that."

Code example: https://play.golang.com/p/WuKDVgsb1oJ

**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by dashpole** [comment]
Those are maps, not slices... https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4652

We should ensure they are not nil, or change the function that provides them to return an empty map instead of nil

**Comment by gaurav1086** [comment]
@dashpole my bad, thanks for pointing out. So, in this case, we are reading from this map: devicePluginCapacity, and not writing to it, so this should be okay. 

From Effective Go:  "A nil map behaves like an empty map when reading, but attempts to write to a nil map will cause a runtime panic; don't do that."

Code example: https://play.golang.com/p/WuKDVgsb1oJ

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Please include a summary of alll the useful comments from the discussion in either the commit message or the pull request description.

**Comment by gaurav1086** [comment]
@mattjmcnaughton thanks for the review. Commit comment updated.

**Comment by gaurav1086** [comment]
Hi, the tests are all passing, can we merge this ? Thank you.

**Pull request merged**
