### PR TITLE
delete NOT Operator in checkMinVersion

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
Minor change:  no need to use `NOT` Operator continuously.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
/assign

@stewart-yu Thanks for your PR. But, checkMinVersion checks if ipset current version satisfies required min version - please check the comment message.

So, I think this function should return true when condition satisfied, otherwise return false?

**Comment by stewart-yu** [comment]
You are right. Fix it now, PTAL @m1093782566

**Comment by m1093782566** [comment]
@stewart-yu I am going to close this PR.

Please feel free to re-open if you have any other thoughts :)

/close

**Pull request closed without merging**
