### PR TITLE
implement HttpDebug and add --http-debug flag to kubectl flags

### LINKED ISSUE #8610: kubectl: dump request response
It would be great to be able to get the full request/response that kubectl is making out to a log file or stderr. It really aids in debugging and learning an API if you can drop down and see the "raw" requests.

For example etcdctl gives you a `curl` example and the raw output:

```
$ etcdctl --debug -o json set foobar baz
Cluster-Endpoints: http://172.17.8.101:4001
Curl-Example: curl -X PUT http://172.17.8.101:4001/v2/keys/foobar -d value=baz
{"action":"set","node":{"key":"/foobar","value":"baz","modifiedIndex":11282,"createdIndex":11282},"prevNode":{"key":"/foobar","value":"baz","modifiedIndex":11162,"createdIndex":11162},"etcdIndex":11282,"raftIndex":19965,"raftTerm":4}
```

### PR DESCRIPTION
**Pull request by mikedanese**
All the cool clients have --http-debug. Fixes #8610 and looks like:

```
➜  kubernetes git:(http-debug) kubectl --http-debug get node e2e-test-mikedanese-minion-0rfr
> HTTP_DEBUG - Request:
----------------
GET /api HTTP/1.1
Host: 130.211.161.152


----------------
> HTTP_DEBUG - Response:
----------------
HTTP/1.1 200 OK
Content-Length: 47
Content-Type: application/json
Date: Thu, 18 Jun 2015 07:17:05 GMT

{
  "versions": [
    "v1beta3",
    "v1"
  ]
}
----------------
> HTTP_DEBUG - Request:
----------------
GET /api/v1/nodes/e2e-test-mikedanese-minion-0rfr HTTP/1.1
Host: 130.211.161.152


----------------
> HTTP_DEBUG - Response:
----------------
HTTP/1.1 200 OK
Content-Length: 1209
Content-Type: application/json
Date: Thu, 18 Jun 2015 07:17:05 GMT

{"kind":"Node","apiVersion":"v1","metadata":{"name":"e2e-test-mikedanese-minion-0rfr","selfLink":"/api/v1/nodes/e2e-test-mikedanese-minion-0rfr","uid":"a148ea1b-1532-11e5-8615-42010af01449","resourceVersion":"16617","creationTimestamp":"2015-06-17T20:51:30Z","labels":{"kubernetes.io/hostname":"e2e-test-mikedanese-minion-0rfr"}},"spec":{"podCIDR":"10.245.1.0/24","externalID":"5086424907822824310","providerID":"gce://mikedanese-k8s/us-central1-b/e2e-test-mikedanese-minion-0rfr","unschedulable":true},"status":{"capacity":{"cpu":"1","memory":"3800808Ki","pods":"100"},"conditions":[{"type":"Ready","status":"True","lastHeartbeatTime":"2015-06-18T07:17:00Z","lastTransitionTime":"2015-06-17T20:51:40Z","reason":"kubelet is posting ready status"}],"addresses":[{"type":"InternalIP","address":"10.240.28.238"},{"type":"ExternalIP","address":"130.211.164.179"}],"nodeInfo":{"machineID":"","systemUUID":"FAE45FFE-30E9-2B02-161F-1B13A0FA5AA5","bootID":"e88e3f67-bae2-400e-9ff3-74b5266dc7e9","kernelVersion":"3.16.0-0.bpo.4-amd64","osImage":"Debian GNU/Linux 7 (wheezy)","containerRuntimeVersion":"docker://1.6.2","kubeletVersion":"v0.18.0-1099-g6c42c9d843b4e4","kubeProxyVersion":"v0.18.0-1099-g6c42c9d843b4e4"}}}
----------------
NAME                              LABELS                                                   STATUS
e2e-test-mikedanese-minion-0rfr   kubernetes.io/hostname=e2e-test-mikedanese-minion-0rfr   Ready,SchedulingDisabled
```

Willing to take any feedback on the format.
cc @jlowdermilk

### CODE REVIEW

**Comment by mikedanese** [comment]
I got #10000!!!! @thockin owes me lunch or something.

**Comment by saad-ali** [comment]
=)
Assigning @thockin

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
I totally set you up by talking 9999 and then leaving the office.

I am not the right person to review this

**Comment by mbforbes** [comment]
Ugh I am so jealous

**Comment by bgrant0607** [comment]
cc @philips @deads2k @liggitt

**Comment by deads2k** [comment]
I like the idea of having a flag, but how would you feel about wiring it into a transport more like the one here: https://github.com/openshift/origin/pull/3088.  The flag could accept a set of strings indicating which output you'd like to output.  We could also have it accept a number to indicate verbosity.

**Comment by smarterclayton** [comment]
I would prefer something tied to verbosity of logs myself - we already have a mechanism for delivering a choice from a user about how much debugging to add.  I'm reassured to see both settled on Transports.

**Comment by deads2k** [comment]
> I would prefer something tied to verbosity of logs myself - we already have a mechanism for delivering a choice from a user about how much debugging to add. I'm reassured to see both settled on Transports.

I could see leaving the option of triggering off of verbosity, but I do rather like the idea of being able to plumb it all the way down via a flag.  I personally had two common use cases:
 1. Dear lord, why is this command so slow.  Show me the URL its hitting and the response time.
 1. What is this command hitting, I want to try tweaking it via curl.

Neither of those are directly related any other piece of the system that might also have verbose logging.

**Comment by smarterclayton** [comment]
Having two ways to get debug logging is a lot harder to triage someone else's problem. Practically, when providing support to a user, I want to ask for the information that solves the problem.  We already have logging for understanding what is happening - a developer wading through a bit more logs when they want to understand why something is slow if it reduces the amount of help / documentation / ui overhead required to get that.

We don't have multiple trace flags on the other components, so I don't think we need a second flag here.

**Comment by mikedanese** [comment]
I actually did this (to debug some of my own problem) and submitted it before I'd seen #8610, and if I had read the issue a little closer, I would have known this is already flushed out in openshift.

**Comment by philips** [comment]
@mikedanese So, is the plan that you are going to port the openshift patch over? A bit confused about the way forward after the close.

**Comment by mikedanese** [comment]
@deads2k can speak on the process and timeframe, but once openshift/origin#3088 is finalized, I believe they are planning on submitting a PR here. Correct?

**Comment by smarterclayton** [comment]
I'm fine with either pull - I just really wanted this to be associated with loglevel for simplicity (allows us to trace controller requests too).

**Comment by deads2k** [comment]
> @deads2k @smarterclayton can speak on the process and timeframe, but once openshift/origin#3088 is finalized, I believe they are planning on submitting a PR here. Correct?

I'm putting the pull together now

**Comment by deads2k** [comment]
Ported under https://github.com/GoogleCloudPlatform/kubernetes/pull/10032

**Comment by mikedanese** [comment]
@deads2k Thanks!

**Pull request closed without merging**
