### PR TITLE
Add a function that can customize the timeout

### LINKED ISSUE #100918: increase ssh timeout
Hello, 

I have opened a [PR](https://github.com/kubernetes/node-problem-detector/pull/533) to [node-problem-detector](https://github.com/kubernetes/node-problem-detector) but node-problem-detector uses [k8s.io/kubernetes/pkg/ssh](https://github.com/kubernetes/kubernetes/tree/master/pkg/ssh) as ssh library and `sshDialTimeout` set in [right here](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L166). [In that failing merge check](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/node-problem-detector/533/pull-npd-e2e-test/1379563125270908928#1:build-log.txt%3A222) there is ssh connectivity errors, so to be able to debug the problem we need to increase `sshDialTimeout` constant in [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L166)

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #100918

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by bilalcaliskan** [comment]
@wzshiming thank you for the PR, but you changed the most commonly used functions, it will cause whole clients who uses that common functions to fail i guess, they need to change the function call. Would not it be nice to just increase the constant value mentioned in the issue to not affect the clients?

**Comment by wzshiming** [comment]
Use global variables to pass the timeout I don’t think it’s a good idea

**Comment by bilalcaliskan** [comment]
O think changing the most used fuction signatures does not look good idea, either. But it was just a suggestion, eventually it is your choice 🙂

**Comment by wzshiming** [comment]
> O think changing the most used fuction signatures does not look good idea, either. But it was just a suggestion, eventually it is your choice 🙂

Just added two public functions, the original function is still.
I just sent a PR, wait for others to review

**Comment by ehashman** [comment]
@wzshiming per https://github.com/kubernetes/kubernetes/issues/100918#issuecomment-822789114 can you please open this PR directly against node-problem-detector to fix their usage rather than modifying this here? I don't believe this is intended to be a publicly-consumable package.

/close

**Pull request closed without merging**
