### PR TITLE
Run hack/run-gendocs.sh

### LINKED ISSUE #11136: All Shippable builds are failing with "Please run hack/run-gendocs.sh"
I guess we merged a doc PR that hadn't run hack/run-gendocs.

Go to
https://app.shippable.com/builds/55a35fe2bd047d0c00e25ed8
or any other recent build to see the problem.

We should run hack/run-gendocs and submit the result ASAP.

### PR DESCRIPTION
**Pull request by davidopp**
Fixes #11136 

@brendanburns @zmerlynn

### CODE REVIEW

**Comment by wojtek-t** [comment]
@davidopp - did you look into the Shippable failure? Is it a real issue?

**Comment by zmerlynn** [comment]
@wojtek-t: The Shippable failure is #11105.

**Comment by zmerlynn** [comment]
LGTM. Merging to get head back.

**Comment by wojtek-t** [comment]
@zmerlynn - thanks for explanation

**Comment by zmerlynn** [comment]
@wojtek-t: Yeah, master is a little messy right now. :(

**Pull request merged**
