### PR TITLE
Fix AWS kubelet registration.

### PR DESCRIPTION
**Pull request by dpratt**
This commit allows the AWS cloud provider plugin to work on EC2 instances
that do not have a public IP. The EC2 metadata service returns a 404 for the
'public-ipv4' endpoint for private instances, and the plugin was bubbling this
up as a fatal error.

### CODE REVIEW

**Comment by dpratt** [comment]
This fixes #11543

**Comment by dpratt** [comment]
I have signed the CLA.

**Comment by jtblin** [comment]
@dpratt I don't think it fixes #11543 entirely. The root cause of #11543 is when using private dns zone in AWS (e.g. `mydomain.io`) in the DHCP opts. That said, we definitely need this change as well when not using public ip addresses! :+1:

**Comment by jtblin** [comment]
@dpratt is correct, there is no way to distinguish between the error responses. It's probably possible to distinguish from request errors by testing the `Error()` value but I am not sure that'd provide too much value. The best we can do is logging an error as @justinsb said above. It'd be great to get that in before `1.2` release freeze.

**Comment by dpratt** [comment]
I'm not really sure of the best/most idiomatic way to hold the 'have we already logged this' state inside the aws plugin. Is there anywhere else that we do a similar pattern?

**Comment by jtblin** [comment]
I don't think you need to keep track of the fact that you've already logged it. Just use `glog.V(2)` and it won't show up unless users increase the verbosity of the logs so it should be fine imho. My $0.02.

**Comment by therc** [comment]
The golang glog doesn't support the C++ implementation's LOG_FIRST_N or LOG_EVERY_N and never will.

**Comment by justinsb** [comment]
@dpratt I'm fine with V(2), ideally leaving a TODO to revisit whether we can get the 404 error out (or otherwise verify that the error is what we expect).

**Comment by justinsb** [comment]
ok to test

**Comment by justinsb** [comment]
Sorry, looks like another rebase is needed as well.  Looking at it, it's because #11543 merged first, and it added a return of api.NodeLegacyHostIP in the get-self-NodeAddresses case.  I believe that's correct, because we want both branches in that function to behave the same way.

**Comment by dpratt** [comment]
Okay - I'll rebase this and add the relevant logging bits.

**Comment by dpratt** [comment]
Rebased and pushed.

**Comment by justinsb** [comment]
LGTM - thanks for fixing

**Pull request merged**
