### PR TITLE
Correctly send list metadata with v1beta1 PartialObjectMetadataList

### PR DESCRIPTION
**Pull request by smarterclayton**
The ListMeta field was accidentally omitted. The v1 api version will change the
protobuf ID ordering to match other lists, but v1beta1 can't do that without being
backwards incompatible.

/kind bug

```release-note
Resource list requests for PartialObjectMetadata now correctly return list metadata like the resourceVersion and the continue token.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Part of kubernetes/enhancements#929

/assign @liggitt

**Comment by liggitt** [comment]
> The v1 api version will change the protobuf ID ordering to match other lists

can you open a tracking issue for fixing the tag ID in v1, and make sure that is included in our list so we don't forget?

nothing in our proto serialization/deserialization path pins tag id 1 to the list meta, right?

**Comment by liggitt** [comment]
/lgtm
/approve

/hold
for question, unhold once answered

**Comment by smarterclayton** [comment]
> can you open a tracking issue for fixing the tag ID in v1, and make sure that is included in our list so we don't forget?

It's in the KEP

> nothing in our proto serialization/deserialization path pins tag id 1 to the list meta, right?

correct, I had entertained the idea of a fast proto deserializer for object meta but partial mostly solves it

**Pull request merged**
