### PR TITLE
Addons in namespace

### PR DESCRIPTION
**Pull request by marekbiskup**
WORK IN PROGRESS 
DO NOT MERGE

additional changes to putting addons in namespaces. I'll continue working tomorrow (remove old secrets from 'default')

cc @satnam6502 @zmerlynn 

@satnam6502 , you can cherry-pick my second commit if you want
(or just patch your sources).

### CODE REVIEW

**Comment by marekbiskup** [comment]
related to #10487

**Comment by zmerlynn** [comment]
Thanks for fixing the other whitespace issues. I nearly commented on the other PR but bit my tongue. :)

**Comment by thockin** [comment]
What's the relationship to #10487 ?

**Comment by satnam6502** [comment]
Yes, as Tim says, what the relation to the PR #10487 ?
I was hoping that we could have got #10487 merged soon-ish. I tried to find all the mysterious white space additions I could (thanks for getting the ones I missed) and the other changes you add are quite minor -- I would vote for getting #10487 merged so it can soak and then layer on the small changes afterwards. @zmerlynn does your LGTM for #10487 still stand and if yes, two TLs willing, do you think we can argue for a merge of that PR soon?

**Comment by zmerlynn** [comment]
@satnam6502: I believe @marekbiskup is basically proposing you take 50c1946dae2752d51b6a0dcb85cc9b08af298b53 and incorporate it it into #10487, if you're going to continue working on it during US business hours, otherwise he's going to work on it tonight.

**Comment by zmerlynn** [comment]
50c1946dae2752d51b6a0dcb85cc9b08af298b53 LGTM.

**Comment by satnam6502** [comment]
I will rebase 50c1946  in a few moments and push and also kick off an e2e. However, I am out and about for most of today in SF but I shall try to keep my laptop closeby.

**Comment by zmerlynn** [comment]
Meta-comment: I'm sorry for a305269e1830b0ebc00a83af734712ab3be2cad3 and the 1000 lines of bash code that accreted after. We really need a Go program here running as an add-on controller.
 
image

**Comment by marekbiskup** [comment]
@satnam6502 , do whatever you prefer. If you merge #10487, I can merge my contribution independently. Or you can patch my changes into yours.

This PR was meant only to give you additional changes that may help in getting #10487 done.

**Pull request closed without merging**
