### PR TITLE
fix: fix typo of the parameter in add/maxResourceList function

### PR DESCRIPTION
**Pull request by fengzixu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
In `maxResourceList` and `addResourceList` function, we used the `new` key word as a parameter name. But I think it should use the `newList` according to the comment.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
what's the typo being fixed?

**Comment by fengzixu** [comment]
In `maxResourceList` and `addResourceList` function, we used the `new` key word as a parameter name. But I think it should use the `newList` according to the comment.

@liggitt Sorry for explaining not clear

**Comment by liggitt** [comment]
thanks for the PR, but since this is permitted by the language, and we have dozens of similar uses in the codebase, I don't see a lot of value in fixing just these few:

```
UpdateFunc: func(old, new interface{}) { handleAPIServiceChange(new.(*v1.APIService)) },
KubeletConfig(old *kubeletconfig.KubeletConfiguration) (new *kubeletconfig.KubeletConfiguration, err error)
func renameImportUsages(f *ast.File, old, new string) {
for _, new := range newTolerations {
old, new    node.RuntimeClass
func ValidatePodSecurityPolicyUpdate(old *policy.PodSecurityPolicy, new *policy.PodSecurityPolicy) field.ErrorList {
UpdateFunc: func(old, new interface{}) {
func referencesDiffs(old []metav1.OwnerReference, new []metav1.OwnerReference) (added []metav1.OwnerReference, removed []metav1.OwnerReference, changed []ownerRefPair) {
func (c *Controller) podAddedDeletedUpdated(old, new interface{}, deleted bool) {
func (sched *Scheduler) onPvUpdate(old, new interface{}) {
```

/close

**Pull request closed without merging**
