### PR TITLE
Upgrade the default csi-proxy version installed by kube-up.sh

### PR DESCRIPTION
**Pull request by mauriciopoppe**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Upgrade the default csi-proxy version installed by kube-up.sh, the binary is already available in gke-release

```
gsutil ls gs://gke-release/csi-proxy/v1.0.1-gke.0
gs://gke-release/csi-proxy/v1.0.1-gke.0/csi-proxy.exe
gs://gke-release/csi-proxy/v1.0.1-gke.0/csi-proxy.exe.sig
gs://gke-release/csi-proxy/v1.0.1-gke.0/notices.tar.gz
gs://gke-release/csi-proxy/v1.0.1-gke.0/notices.tar.gz.sig
```

#### Does this PR introduce a user-facing change?

```release-note
kube-up.sh installs csi-proxy v1.0.1-gke.0
```

/cc @jingxu97 @pjh @ddebroy @jsturtevant

### CODE REVIEW

**Comment by yujuhong** [comment]
/approve

Would this get tested by any of the presubmits?

**Comment by jingxu97** [comment]
> /approve
> 
> Would this get tested by any of the presubmits?

No, presubmit will only test new csiproxy version after this change is merged.
So currently it is manual testing.

**Pull request merged**
