### PR TITLE
use v1.ResourcePods instead of hard coding "pods"

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

use v1.ResourcePods instead of hard coding 'pods'

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@sakeven , thanks for your contribution; `v1.ResourcePods` means max Pods can be started in the agent, so it seems not suitable for those place.

**Comment by sakeven** [comment]
@k82cn , so is there any constant exactly representing resource "pods"?

I see the [comment](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4143) of resource constants is ```The following identify resource constants for Kubernetes object types```.

**Comment by k82cn** [comment]
wow, yes; lgtm :).

**Comment by sakeven** [comment]
Failed test pull-kubernetes-unit has been reported in #48368 .

**Comment by sakeven** [comment]
@k82cn approve or close?

**Comment by k82cn** [comment]
I'm OK with that; can you also grep other hard code "pod"?

**Comment by sakeven** [comment]
Ok

**Comment by sakeven** [comment]
@k82cn updated. I only do fix in the scope of scheduler out of which there are too many.

**Comment by sakeven** [comment]
@k82cn PTAL.

**Pull request merged**
