### PR TITLE
Add Japanese translation for kubectl

### PR DESCRIPTION
**Pull request by girikuncoro**
**What this PR does / why we need it**:
I messed up the original PR(#45562) which was already been reviewed and approved. This PR provides first attempt to translate kubectl in Japanese (related to #40645 and #40591).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
No issues

**Special notes for your reviewer**:
Should be reviewed by member of Japanese k8s community (I stayed in Japan for 4 years, but my language is not as good as native Japanese)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
Thanks @girikuncoro I think you need to re-run `hack/generate-bindata.sh`

**Comment by girikuncoro** [comment]
@brendandburns seems like I just passed the CI now after rebase and regenerate bindata, can you kindly approve?

**Comment by brendandburns** [comment]
/approve
/lgtm


--brendan

________________________________

**Comment by girikuncoro** [comment]
/release-note
This might use the title as the release note

**Comment by girikuncoro** [comment]
@brendandburns can you remove the `do-not-merge` label also? thanks!

**Comment by brendandburns** [comment]
@girikuncoro done, sorry for the delay.

**Pull request merged**
