### PR TITLE
WIP: Revert "Ensure that Reason and Message are preserved on pod status"

### PR DESCRIPTION
**Pull request by rphillips**
Reverts kubernetes/kubernetes#103785

Testing CI.

### CODE REVIEW

**Comment by pacoxu** [comment]
```
[ 5160.754869] systemd-journald[100]: Failed to open system journal: No space left on device
```
Found this in both(this pr ci, example run in https://github.com/kubernetes/kubernetes/issues/103879#issue-951727209).
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103880/pull-kubernetes-node-kubelet-serial/1418634958255165440/artifacts/n1-standard-2-cos-81-12871-1290-12-a8890dc5/serial-1.log

**Comment by dantingl** [comment]
Do we have a plan when to submit this patch? The reverted patch has a regression that pod status in `kubectl` command is stuck with an error even after the error is resolved.

**Comment by krmayankk** [comment]
not sure this is a bug, since its trying to revert a fix done by @smarterclayton , may be you can quickly triage it ?

**Comment by dims** [comment]
there's no explanation in the PR body and here languishing since July. @rphillips please check with @smarterclayton internally and reopen it with details for why revert is needed?

/close

**Pull request closed without merging**
