### PR TITLE
Boilerplate checks on 2014, but commit included a 2015 (breaks travis)

### PR DESCRIPTION
**Pull request by smarterclayton**
Revert boilerplate to 2014 until hack/verify-boilerplate.sh is fixed

### CODE REVIEW

**Comment by smarterclayton** [comment]
@thockin @brendandburns can I get a merge on this so travis starts passing again?

**Comment by jbeda** [comment]
cc: @zmerlynn

**Comment by zmerlynn** [comment]
Sorry, I still need to add the precommit hooks.

**Comment by zmerlynn** [comment]
I should have these in my repo now. Egg, face, apologies. I'll fix hack/verify-boilerplate.sh now.

**Comment by dchen1107** [comment]
My pr #3225 was out with one proposed fix for boilerplate issue of "Copyright 2015".

**Comment by zmerlynn** [comment]
Missed that. New fix should last another year. I was about to add a loop
but this is easy enough.

**Pull request merged**
