### PR TITLE
Update staging in release 1.5

### PR DESCRIPTION
**Pull request by caesarxuchao**
This PR runs hack/update-staging-client.sh in kubernetes release-1.5 branch. This helps client-go release-2.0 branch to pick up the bug fixes. I cannot follow the regular cherrypick process because the staging/ folder has been changed too much in the master branch.

cc @saad-ali since he's the release czar of kubernetes 1.5.

Fixes https://github.com/kubernetes/client-go/issues/66. cc @hongchaodeng

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@sttts @lavalamp could you approve this PR? It just runs hack/update-staging-client.sh in the release-1.5 branch to update the staging area, which will be published to client-go release-2.0 branch. Thanks.

**Comment by sttts** [comment]
smoke tested the examples: they compile fine.

**Comment by sttts** [comment]
lgtm with the limited testing I can do. A second pair of eyes wouldn't harm.

**Comment by lavalamp** [comment]
LGTM

@saad-ali this is so we can update the 1.5 client with fixes that have already been cherrypicked into the 1.5 branch. Sound OK to you?

**Comment by saad-ali** [comment]
> @saad-ali this is so we can update the 1.5 client with fixes that have already been cherrypicked into the 1.5 branch. Sound OK to you?

Ack. Approving

**Comment by caesarxuchao** [comment]
@k8s-bot kops aws e2e test this

**Comment by caesarxuchao** [comment]
@k8s-bot kops aws e2e test this

**Comment by caesarxuchao** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
Tracking AWS issue in https://github.com/kubernetes/kubernetes/issues/41152

**Comment by zmerlynn** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
