### PR TITLE
[Federation] federated pod autoscaler controller

### PR DESCRIPTION
**Pull request by irfanurrehman**
This PR implements second part of federated pod autoscaler.
The issue to handle the whole feature is https://github.com/kubernetes/kubernetes/issues/38974
This PR is on top of https://github.com/kubernetes/kubernetes/pull/38976, which will be reviewed separately.
Please review only the last 2 commits in this PR.

cc @kubernetes/sig-cluster-federation
@shashidharatd @kshafiee @deepak-vij

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@jianhuiz Can you review this since you wrote a controller recently for https://github.com/kubernetes/kubernetes/pull/36197

**Comment by irfanurrehman** [comment]
@nikhiljindal @jianhuiz @mwielgus 
I am in a process of rewriting this as suggested by marcin here https://github.com/kubernetes/kubernetes/issues/38974.
Will raise a preliminary PR soon. suggest to review then.

**Comment by nikhiljindal** [comment]
@irfanurrehman I assume this can be closed now?

**Comment by irfanurrehman** [comment]
closing this in favour of https://github.com/kubernetes/kubernetes/pull/40162

**Pull request closed without merging**
