### PR TITLE
Use specific mount binary name in glusterfs plugin.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@jingxu97 Can you please review this PR? The mount binary path is common to linux and in switch we use linux, so it would be good to rename for no confusion while going through the code.

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by humblec** [comment]
Addressed this in https://github.com/kubernetes/kubernetes/pull/45995. Closing this PR.

**Pull request closed without merging**
