### PR TITLE
Fix a typo: coverting -> converting

### PR DESCRIPTION
**Pull request by e-nikolov**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
@e-nikolov Thanks for your first contribution! :smile: 

/assign @liggitt 
for approval

**Comment by cblecker** [comment]
/retest
Adding `retest-not-required` as it's a comment typo update.

**Pull request merged**
