### PR TITLE
add indexer for pod cacher

### PR DESCRIPTION
**Pull request by shaloulcy**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

If resource version given, the list interface will use the cacher. The apiserver will list all cached data, then filter the data by label or field selector. Indeed, we can add the indexers for cacher to accelerate

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shaloulcy** [comment]
I signed it

**Comment by shaloulcy** [comment]
I signed it

**Comment by wojtek-t** [comment]
@shaloulcy - thanks for this change - this is one of things I wanted to do for quite some time already.
That said, it's too late in the release cycle (week before code freeze) for me to find enough time for it.

But let me maybe start with some high-level comments:
(1) there are couple changes to interfaces in this PR, mainly label.Selector.RequiresExactMatch - can you please open a dedicated PR just for this one?
(2) This PR should be splitted into commits
- introduce the necessary interfaces, fields in structs etc.
- implementation of these (with tests)
- use of the interfaces (i.e. create the index for pods)
Can you please work on it - this will make reviewing a bit easier.

@kubernetes/sig-scalability-pr-reviews @jpbetz @mm4tt - FYI

**Comment by shaloulcy** [comment]
> @shaloulcy - thanks for this change - this is one of things I wanted to do for quite some time already.
> That said, it's too late in the release cycle (week before code freeze) for me to find enough time for it.
> 
> But let me maybe start with some high-level comments:
> (1) there are couple changes to interfaces in this PR, mainly label.Selector.RequiresExactMatch - can you please open a dedicated PR just for this one?
> (2) This PR should be splitted into commits
> 
> * introduce the necessary interfaces, fields in structs etc.
> * implementation of these (with tests)
> * use of the interfaces (i.e. create the index for pods)
>   Can you please work on it - this will make reviewing a bit easier.
> 
> @kubernetes/sig-scalability-pr-reviews @jpbetz @mm4tt - FYI
great, I will work on it

**Comment by wojtek-t** [comment]
This wasn't fixed yet.

**Comment by markyjackson-taulia** [comment]
Hello, @lavalamp
I wanted to touch base to ensure this was on track for v1.18 release. I see some conflicting files

**Comment by wojtek-t** [comment]
@markyjackson-taulia - this one is blocked on https://github.com/kubernetes/kubernetes/pull/85445 - we need to have that one in first

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia - this one is blocked on #85445 - we need to have that one in first

#85445 appears to have been merged, are we good to close this now @wojtek-t ?

**Comment by markyjackson-taulia** [comment]
Once the conflicts are corrected of course

**Comment by wojtek-t** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/87939

**Pull request closed without merging**
