### PR TITLE
Fix kubectl e2e test by removing check for the token in logs

### LINKED ISSUE #81845: [Failing Test] [sig-cli] Kubectl client [k8s.io] Simple pod should handle in-cluster config
**Which jobs are failing / job(s) where test is present**:
* ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel
* ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew

**Which test(s) are failing**:
[sig-cli] Kubectl client [k8s.io] Simple pod should handle in-cluster config

**Since when has it been failing**:
It has been failing since 8/13.

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-orphaned#gce-new-master-upgrade-master-parallel
* https://testgrid.k8s.io/sig-cli-master#skew-cluster-stable1-kubectl-latest-gce

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:621
Expected
    <exec.CodeExitError>: {
        Err: {
            s: "error running &{../../../../kubernetes_skew/cluster/kubectl.sh [../../../../kubernetes_skew/cluster/kubectl.sh --server=https://34.83.124.226 --kubeconfig=/workspace/.kube/config exec --namespace=kubectl-5797 nginx -- /bin/sh -x -c /tmp/kubectl get pods --token=invalid --v=7 2>&1] []  <nil> I0821 19:51:49.587176     102 merged_client_builder.go:164] Using in-cluster namespace\nI0821 19:51:49.587839     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.594295     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.602903     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.603669     102 round_trippers.go:420] GET https://10.0.0.1:443/api/v1/namespaces/kubectl-5797/pods?limit=500\nI0821 19:51:49.603894     102 round_trippers.go:427] Request Headers:\nI0821 19:51:49.604071     102 round_trippers.go:431]     Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json\nI0821 19:51:49.604204     102 round_trippers.go:431]     User-Agent: kubectl/v1.17.0 (linux/amd64) kubernetes/90df64b\nI0821 19:51:49.604360     102 round_trippers.go:431]     Authorization: Bearer <masked>\nI0821 19:51:49.628462     102 round_trippers.go:446] Response Status: 401 Unauthorized in 23 milliseconds\nI0821 19:51:49.629333     102 helpers.go:199] server response object: [{\n  \"kind\": \"Status\",\n  \"apiVersion\": \"v1\",\n  \"metadata\": {},\n  \"status\": \"Failure\",\n  \"message\": \"Unauthorized\",\n  \"reason\": \"Unauthorized\",\n  \"code\": 401\n}]\nF0821 19:51:49.629526     102 helpers.go:114] error: You must be logged in to the server (Unauthorized)\n + /tmp/kubectl get pods '--token=invalid' '--v=7'\ncommand terminated with exit code 255\n [] <nil> 0xc0048fcf90 exit status 255 <nil> <nil> true [0xc00592a1e8 0xc00592a200 0xc00592a218] [0xc00592a1e8 0xc00592a200 0xc00592a218] [0xc00592a1f8 0xc00592a210] [0x9d21f0 0x9d21f0] 0xc001ba2360 <nil>}:\nCommand stdout:\nI0821 19:51:49.587176     102 merged_client_builder.go:164] Using in-cluster namespace\nI0821 19:51:49.587839     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.594295     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.602903     102 merged_client_builder.go:122] Using in-cluster configuration\nI0821 19:51:49.603669     102 round_trippers.go:420] GET https://10.0.0.1:443/api/v1/namespaces/kubectl-5797/pods?limit=500\nI0821 19:51:49.603894     102 round_trippers.go:427] Request Headers:\nI0821 19:51:49.604071     102 round_trippers.go:431]     Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json\nI0821 19:51:49.604204     102 round_trippers.go:431]     User-Agent: kubectl/v1.17.0 (linux/amd64) kubernetes/90df64b\nI0821 19:51:49.604360     102 round_trippers.go:431]     Authorization: Bearer <masked>\nI0821 19:51:49.628462     102 round_trippers.go:446] Response Status: 401 Unauthorized in 23 milliseconds\nI0821 19:51:49.629333     102 helpers.go:199] server response object: [{\n  \"kind\": \"Status\",\n  \"apiVersion\": \"v1\",\n  \"metadata\": {},\n  \"status\": \"Failure\",\n  \"message\": \"Unauthorized\",\n  \"reason\": \"Unauthorized\",\n  \"code\": 401\n}]\nF0821 19:51:49.629526     102 helpers.go:114] error: You must be logged in to the server (Unauthorized)\n\nstderr:\n+ /tmp/kubectl get pods '--token=invalid' '--v=7'\ncommand terminated with exit code 255\n\nerror:\nexit status 255",
        },
        Code: 255,
    }
to contain substring
    <string>: Authorization: Bearer invalid
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:721
```

I think the failure is coming from this part of the test https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl/kubectl.go#L720

/milestone v1.16
/priority critical-urgent
/kind failing-test
/sig sig-cli
/cc @kubernetes/sig-cli-test-failures 
/cc @Verolop @jimangel @soggiest @alenkacz

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81845

**Special notes for your reviewer**:
The logs will no longer (1.16+) contain the token.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tpepper** [comment]
/priority critical-urgent
from parent PR

**Review by alejandrox1 — APPROVED** [review]
Thank you @odinuge !
/lgtm

**Comment by odinuge** [comment]
Ping @kubernetes/patch-release-team :smile:

**Pull request merged**
