### PR TITLE
framework k8s.io/apiextensions-apiserver dependency

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

1. less code to vendor into external users of the framework
    
    The following dependencies become obsolete due to this change (from `dep`):
    
    (8/23) Removed unused project github.com/grpc-ecosystem/go-grpc-prometheus
    (9/23) Removed unused project github.com/coreos/etcd
    (10/23) Removed unused project github.com/globalsign/mgo
    (11/23) Removed unused project github.com/go-openapi/strfmt
    (12/23) Removed unused project github.com/asaskevich/govalidator
    (13/23) Removed unused project github.com/mitchellh/mapstructure
    (14/23) Removed unused project github.com/NYTimes/gziphandler
    (15/23) Removed unused project gopkg.in/natefinch/lumberjack.v2
    (16/23) Removed unused project github.com/go-openapi/errors
    (17/23) Removed unused project github.com/go-openapi/analysis
    (18/23) Removed unused project github.com/go-openapi/runtime
    (19/23) Removed unused project sigs.k8s.io/structured-merge-diff
    (20/23) Removed unused project github.com/go-openapi/validate
    (21/23) Removed unused project github.com/coreos/go-systemd
    (22/23) Removed unused project github.com/go-openapi/loads
    (23/23) Removed unused project github.com/munnerz/goautoneg
    
2. works around https://github.com/kubernetes/kubernetes/issues/75338
    which currently breaks vendoring
    
    Some recent changes to crd_util.go must now be pulling in the broken
    k8s.io/apiextensions-apiserver packages, because it was still working
    in revision 2e90d92db9a807fcc140977e7a4798c6078014c2 (as demonstrated by
    https://github.com/intel/pmem-CSI/tree/586ae281ac2810cb4da6f1e160cf165c7daf0d80).

**Which issue(s) this PR fixes**:
Related-to #75338

**Special notes for your reviewer**:

The original motivation was issue #75338, but after noticing how many unused packages can be removed from downstream users of the framework I am convinced that this is worthwhile even if #75338 gets fixed.

I am working on a blog post for kubernetes.io that shows how to use the E2E framework in Kubernetes 1.14, and the end result will be much nicer with this PR merged into it.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig testing
/cc @dims

### CODE REVIEW

**Comment by pohly** [comment]
/priority important-soon

Rationale: I'm trying to get more people to use the test/e2e/framework, and this PR would make that a lot cheaper in 1.14.

**Comment by pohly** [comment]
For reference, the repo and branch where I noticed the reduction of packages is https://github.com/pohly/cluster-driver-registrar/tree/termination.

**Comment by spiffxp** [comment]
I am OK with this in the abstract but before I drop approve:
- does this change prevent downstream consumers of framework from testing crds?
- framework is a monolith and needs to be broken up, but I have concerns this is a one off motivated by pain rather than part of a plan. I am willing to approve as such (just this instance not necessarily this pattern), but do you have links to discussion of further plans?

**Comment by pohly** [comment]
> does this change prevent downstream consumers of framework from testing crds?

No. They simply have to use `k8s.io/kubernetes/test/utils/crd` to get the same code as before (and then deal with the dependencies...).

> framework is a monolith and needs to be broken up, but I have concerns this is a one off motivated by pain rather than part of a plan

True. If I had had a plan (and time) earlier, this would have been more organized. I was aware of the still large number of packages that the framework pulled it, I just had no idea that a lot of it was due to this one package.

I'll file an enhancement ticket about restructuring `test/e2e/framework` (and `test` in general). There is one already about moving to staging, perhaps I'll just add that there. Now I need to run though. Back later...

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

/cc @johnSchnake @stevesloka

**Comment by timothysc** [comment]
This doesn't need to be for 1.14.

**Comment by dims** [comment]
Ack @timothysc

**Comment by pohly** [comment]
It doesn't need to be for 1.14, but it would be nice.

Let me check what the test failures were... ah, golint now gets applied. Not sure whether I should apply the same exception as before or fix this. Let's fix it.

The other errors seem unrelated.

**Comment by spiffxp** [comment]
/lgtm
FWIW I'm willing to try and land this in v1.14, the changes appear purely mechanical.  If you'd rather not land this now, I've milestoned https://github.com/kubernetes/kubernetes/pull/75339

**Comment by pohly** [comment]
> I'll file an enhancement ticket about restructuring test/e2e/framework (and test in general). There is one
> already about moving to staging, perhaps I'll just add that there.

I added it to the existing issue because it is part of the entire "move code around and break API" operation: https://github.com/kubernetes/kubernetes/issues/74352#issuecomment-472793284

**Comment by pohly** [comment]
This PR would also avoid https://github.com/kubernetes/kubernetes/issues/75403.

**Comment by neolit123** [comment]
> This PR would also avoid #75403.

IMHO it if was in separate PR we might have merged this particular fix as critical urgent. but others should weight comments in.

**Comment by pohly** [comment]
> IMHO it if was in separate PR we might have merged this particular fix as critical urgent. but others should weight comments in.

Not sure I understand. This PR avoids the issue because a whole bunch of problematic packages no longer get included. First k8s.io/apiextensions-apiserver turned out to broken (fixed), then one of its dependencies "misbehaves" (k8s.io/component-base calling `klog.InitFlags`).

There's a workaround for the later (don't call `klog.InitFlags` again), it's just not nice and thus the original assessment for this PR still applies ("nice to have for 1.14, but not a critical bug fix and thus not eligible").

**Comment by neolit123** [comment]
> Not sure I understand. This PR avoids the issue because a whole bunch of problematic packages no longer get included. 

ok, i guess i misunderstood. instead of avoiding, i though a separate commit was added that address the klog flags problem.

**Comment by timothysc** [comment]
I'm going to defer to @spiffxp on this one. 
/hold

**Comment by spiffxp** [comment]
The reason I'm leaning toward including this in v1.14 is that it sounds like test/e2e/framework is unusable to downstream consumers unless this lands.  Let's see what CI signal looks like

**Comment by pohly** [comment]
@spiffxp not unusable, but it would be a lot nicer. If you are interested, follow https://github.com/kubernetes-csi/cluster-driver-registrar/pull/41. In it, I am adding E2E testing to cluster-driver-registrar, which is necessary to ensure that a bug doesn't reappear. When using Kubernetes master, it adds over 2500 new files. My PR reduces that by 500. 2000 is still a lot, though. I'm now waiting for review feedback. Hopefully it's not just "this is too big, go away"...

The reduction in different unique projects is at a similar scale (20% less).

**Pull request merged**
