### PR TITLE
Fix SCTP default-deny test

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind cleanup
/kind flake

#### What this PR does / why we need it:

The test is about SCTP and the accessed service only forwarded SCTP traffic to the server Pod but the client Pod used TCP protocol, so the test traffic never reached the server Pod and the test NetworkPolicy was never enforced, which lead to test success even if the default-deny policy was implemented wrongly. In some cases it may got failure result if there was an external server having same IP as the cluster IP and listening to TCP 80 port.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
> In some cases it may got failure result if there was an external server having same IP as the cluster IP and listening to TCP 80 port.

besides the protocol thing, how can not be a failure if there is a deny-all?

**Comment by tnqn** [comment]
> > In some cases it may got failure result if there was an external server having same IP as the cluster IP and listening to TCP 80 port.
> 
> besides the protocol thing, how can not be a failure if there is a deny-all?

The test client Pod accessed TCP/80 port of the service while kube-proxy (or similar proxies) only proxied SCTP/80 traffic. The traffic didn't reach the backend Pod and was routed to external network. If there is an server configured with this IP, the test would be a failure (it got response). I found this issue because of this case.

Besides, even when the test is a success, it's not because of the enforcement of the deny-all policy, but because the traffic was routed to external network and dropped there.

**Comment by aojea** [comment]
> he traffic didn't reach the backend Pod and was routed to external network. If there is an server configured with this IP, the test would be a failure (it got response). I found this issue because of this case.

wow, what are the odds? so you have an overlapping network with connectivity and the packet unfortunately hits the other network

/test pull-kubernetes-e2e-ubuntu-gce-network-policies

```
Kubernetes e2e suite: [sig-network] NetworkPolicyLegacy [LinuxOnly] NetworkPolicy between server and client should deny ingress access to updated pod [Feature:NetworkPolicy] expand_more	
```

**Comment by tnqn** [comment]
> > he traffic didn't reach the backend Pod and was routed to external network. If there is an server configured with this IP, the test would be a failure (it got response). I found this issue because of this case.
> 
> wow, what are the odds? so you have an overlapping network with connectivity and the packet unfortunately hits the other network

Yes, I guess it's normal that the underlay network has overlapping with the default service CIDR as the former could use 10.0.0.0/8 and the latter is 10.96.0.0/12. When the test failed, the allocated service IP was "10.110.83.242", which looked like a very normal priviate IP and it was indeed used by a server in my corporate network.

**Comment by aojea** [comment]
/hold

I'm holding just to check that the job that test the network policies doesn't fail, it is not required and we can merge with it failing

pull-kubernetes-e2e-ubuntu-gce-network-policies

**Pull request merged**
