### PR TITLE
bump json-iterator dependency

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Pulls in depth limit in json-iterator, removes our extension-based depth limiter. [Unit](https://github.com/kubernetes/kubernetes/blob/1fcd46c250ea0cfe4c84bc5db63d83534101fb1d/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json_limit_test.go) and [integration](https://github.com/kubernetes/kubernetes/blob/1fcd46c250ea0cfe4c84bc5db63d83534101fb1d/staging/src/k8s.io/apiextensions-apiserver/test/integration/limit_test.go#L120-L215) [tests](https://github.com/kubernetes/kubernetes/blob/1fcd46c250ea0cfe4c84bc5db63d83534101fb1d/test/integration/apiserver/max_request_body_bytes_test.go#L192-L254) remain in place.

Waiting for v1.1.8 to be tagged before merging.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig api-machinery
/cc @cjcullen @dims

### CODE REVIEW

**Comment by liggitt** [comment]
this is ready

**Comment by dims** [comment]
/lgtm
/hold

feel free to remove the hold when appropriate

**Pull request merged**
