### PR TITLE
Improve dashboard addon

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The PR introduce improvements such as:
- Remove superfluous `dashboard-` prefix from the manifest file names. They are already located in `addons/dashboard/`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR, but I think the current manifest grouping makes sense and should be kept. the serviceaccount+deployment are related and should be created together, as should the role+rolebinding

**Comment by ialidzhikov** [comment]
> thanks for the PR, but I think the current manifest grouping makes sense and should be kept. the serviceaccount+deployment are related and should be created together, as should the role+rolebinding

Applied the suggestion.

**Comment by liggitt** [comment]
thanks for the PR, but the filename changes have a slight downside (loses git history, requires any consumers of individual files to adjust), without compelling benefit.

I also think the filenames originated from https://github.com/kubernetes/dashboard/tree/master/aio/deploy/recommended, which still prefixes with dashboard. If we were going to change at all, I'd expect us to sync closer to the dashboard's canonical examples.

**Pull request closed without merging**
