### PR TITLE
Update `dims` as approver for some top level dirs

### PR DESCRIPTION
**Pull request by dims**
- signed up 15 months ago for reviewer roles https://github.com/kubernetes/kubernetes/pull/93821
- also see previous discussions here https://github.com/kubernetes/kubernetes/pull/85638 (on why we need to reduce folks on root and can't add `dims` there)

Today's context as example - there were really easy changes in `/cmd` and we are so close to code freeze:
https://github.com/kubernetes/kubernetes/pull/106159

SOAP Box : We really need to DROP folks who have not reviewed anything for a LONG time!

/assign @liggitt @thockin @smarterclayton 

- `staging`
- `plugin`
- `pkg`
- `cmd`

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
I'm +1, slightly. A few thoughts:
* I don't see a significant difference between approver on all dirs containing go code (cmd/pkg/plugin/staging) and top-level approver (OWNER_ALIASES and vendor content is about the only difference...). The context required to ack changes across all commands/packages is significant.
* I've seen (very) occasional acks of things that deserved more scrutiny from @dims, but I trust @dims' judgment and restraint generally. I'd encourage and expect slightly more caution while carrying greater approve power, and to lean more on specific subtree owners whenever possible, or when anything less than 100% sure about a change (as I do)
* I'm not sure the biggest challenge facing the project currently is too *few* things merging :-)

**Comment by dims** [comment]
cc @brendandburns @davidopp @dchen1107 @lavalamp @mikedanese @smarterclayton @thockin (as approvers in these OWNERS files)

**Comment by thockin** [comment]
Thanks for all you do, @dims.  With great power, yadda yadda...  When in doubt, PLEASE ask for a consult.  As said above - our biggest issue isn't really "too few PRs merging".

/lgtm
/approve

**Comment by dims** [comment]
thanks you all! thanks @thockin for coordinating

**Comment by aojea** [comment]
+1

**Pull request merged**
