### PR TITLE
Ansible: Adding kube-apiserver basic auth

### PR DESCRIPTION
**Pull request by jeffbean**
This enables use of the UI for Kubernetes through the apiserver basic auth.

### CODE REVIEW

**Comment by jeffbean** [comment]
@eparis

**Comment by eparis** [comment]
hmmmm, this is the first time we are hard coding the same security for everyone across all clusters...  And the place to change it is buried deep in a defaults/ file no one will ever find...

I guess I like the idea, but not the default user....

**Comment by jeffbean** [comment]
Didn't think about the security around it. Ill think on this on how to maybe have dynamic values but without prompts hopefully.

**Comment by eparis** [comment]
@jeffbean I'm going to close. I liked it (other than the default password).  If you want to resubmit, it'll have to be in contrib...

**Pull request closed without merging**
