### PR TITLE
Reduce hard code to avoid more mistakes

### PR DESCRIPTION
**Pull request by hello2mao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Reduce hard code to avoid more mistakes.

```release-note
None
```

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by MrHohn** [comment]
@hello2mao You might need to run `.hack/update-bazel.sh` to update the BUILD file to include the new dependency.

**Pull request merged**
