### PR TITLE
Fix golint failures: replicationcontroller and replicationcontroller/storage packages in pkg/registry/core #68026

### PR DESCRIPTION
**Pull request by rakeshreddybandi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fix golint issues for pkg/registry/core/replicationcontroller and pkg/registry/core/replicationcontroller/storage

**Which issue(s) this PR fixes**:

Related to #68026.

**Special notes for your reviewer**:
Errors from golint:
```
pkg/registry/core/replicationcontroller/doc.go:17:1: package comment should be of the form "Package replicationcontroller ..."
pkg/registry/core/replicationcontroller/strategy.go:173:31: error strings should not be capitalized or end with punctuation or a newline
pkg/registry/core/replicationcontroller/strategy.go:193:5: exported var StatusStrategy should have comment or be unexported

pkg/registry/core/replicationcontroller/storage/storage.go:51:1: exported function NewStorage should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:64:6: exported type REST should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:114:1: exported method StatusREST.New should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:130:6: exported type ScaleREST should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:138:1: exported method ScaleREST.GroupVersionKind should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:152:1: exported method ScaleREST.Get should have comment or be unexported
pkg/registry/core/replicationcontroller/storage/storage.go:161:1: exported method ScaleREST.Update should have comment or be unexported
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rakeshreddybandi** [comment]
fyi @spzala

**Comment by spiffxp** [comment]
/ok-to-test
/approve
the /hack changes, I don't have rights for the rest

**Comment by spzala** [comment]
Test failure seems not related to the change. Trying retest. 
/retest

**Comment by rakeshreddybandi** [comment]
Hi @deads2k Can you help reviewing this PR when you get a chance? Thanks in advance

**Pull request closed without merging**
