### PR TITLE
Revert "Decrese fluentd cpu request"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#47906

### CODE REVIEW

**Comment by piosz** [comment]
cc @mwielgus @mikedanese @crassirostris

**Comment by piosz** [comment]
As discussed offline I'll check this locally.

**Comment by piosz** [comment]
Pods on master node:
```
  Namespace			Name							CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----							------------	----------	---------------	-------------
  kube-system			cluster-autoscaler-kubernetes-master			10m (1%)	0 (0%)		300Mi (8%)	0 (0%)
  kube-system			etcd-empty-dir-cleanup-kubernetes-master		0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			etcd-server-events-kubernetes-master			100m (10%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			etcd-server-kubernetes-master				200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			fluentd-gcp-v2.0-hspmw					100m (10%)	0 (0%)		200Mi (5%)	300Mi (8%)
  kube-system			kube-addon-manager-kubernetes-master			5m (0%)		0 (0%)		50Mi (1%)	0 (0%)
  kube-system			kube-apiserver-kubernetes-master			250m (25%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-controller-manager-kubernetes-master		200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-kubernetes-master			75m (7%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			l7-lb-controller-v0.9.5-kubernetes-master		10m (1%)	0 (0%)		50Mi (1%)	0 (0%)
  kube-system			npd-v0.4.1-ffqsz					20m (2%)	200m (20%)	20Mi (0%)	100Mi (2%)
  kube-system			rescheduler-v0.3.0-kubernetes-master			10m (1%)	0 (0%)		100Mi (2%)	0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  980m (98%)	200m (20%)	720Mi (20%)	400Mi (11%)
```

**Comment by piosz** [comment]
@dchen1107 @caesarxuchao this had to go in 1.7

**Comment by caesarxuchao** [comment]
@piosz @gmarek are we still going to solve the original issue https://github.com/kubernetes/kubernetes/issues/47905?

**Comment by piosz** [comment]
@caesarxuchao we decreased resource request for a number of components including #47910. As I wrote in https://github.com/kubernetes/kubernetes/pull/48066#issuecomment-311087015 there is problem with overcommiteed master (at least for now) so the original issue is fixed.

**Comment by piosz** [comment]
ping @caesarxuchao 
This should go in 1.7

**Comment by dchen1107** [comment]
Done! Please create your cherrypick pr for v1.7. Thanks!

**Comment by piosz** [comment]
@dchen1107 thanks!
sent #48266

**Pull request merged**
