### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by stealthybox**
/kind documentation

**Release Note**
```release-note
NONE
```

**Special notes for your reviewer**:
image

### CODE REVIEW

**Comment by justaugustus** [comment]
(I hope I'm not the only one who said, "Oh look, doggos, that's an auto-approve!")

For SIG Release:
/lgtm
/approve
/priority important-soon
/milestone v1.15

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
