### PR TITLE
kubectl logs test: use agnhost pause instaed of fixed duration sleep

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Avoids fixed-duration sleep in test case in favor of holding the container alive until SIGTERM on deletion.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

If we think this pattern will be common we can add this functionality as a flag to the logs-generator subcommand, but I think this is reasonable for now.

Follow-up to https://github.com/kubernetes/kubernetes/pull/125037

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by eddiezane — APPROVED** [review]
Thank you!

/lgtm

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
NONE
```

**Comment by BenTheElder** [comment]
unrelated flake:
> Kubernetes e2e suite: [It] [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should support readOnly file specified in the volumeMount [LinuxOnly] 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125071/pull-kubernetes-e2e-gce/1793366953469939712

/retest

**Pull request merged**
