### PR TITLE
Add Mesosphere solution to kubernetes.io

### PR DESCRIPTION
**Pull request by jeffmendoza**
This is visible [here](http://jeffmendoza.github.io/kubernetes/solutions/mesosphere.html), though that is not pulling the updated css or images, as the links are to kubernetes.io.

cc: @mhausenblas
xref https://github.com/mesosphere/kubernetes-mesos/issues/449

### CODE REVIEW

**Comment by saad-ali** [comment]
Documentation ok for 1.0. Adding reviewer

**Comment by erictune** [comment]
@erickhan

**Comment by erictune** [comment]
Let's not merge until @erickhan gets a chance to comment.

**Comment by erickhan** [comment]
LGTM. thanks!

**Comment by thockin** [comment]
I'll take a look today

**Comment by jeffmendoza** [comment]
@thockin Can we get this merged? We need the css for more markdown docs that Richie is working on.

**Comment by jeffmendoza** [comment]
Ping @erickhan @erictune @thockin Any blockers on this?

**Comment by mhausenblas** [comment]
@jeffmendoza is there anything I can help with, here?

**Comment by davidopp** [comment]
Our PMs and the Mesosphere PMs are discussing how to best present this material. So we've temporarily put it on the back burner.

**Comment by air** [comment]
Hi @davidopp! I'm the Mesosphere PM for Kubernetes, we met on the call last week.
Maybe there's some miscommunication - I don't believe there's a reason from our side to block this. Let me know if there's a reason not to move forward. Thanks! cc: @mhausenblas

**Comment by jdef** [comment]
once we push the new k8s/dcos packaging (very, very soon) the examples at the bottom of this doc will need updates
/cc @sttts

**Comment by sttts** [comment]
Here is the k8s tutorial. We can copy examples from there for v1.0.2: https://github.com/mesosphere/mesosphere-docs/blob/6a849120339f915153e8b1e5590e43b680f27521/services/kubernetes.md

**Comment by jdef** [comment]
our k8s/dcos package has just been updated in universe, the docs here must be updated to match

**Comment by davidopp** [comment]
Please don't merge this without my OK.

**Comment by jeffmendoza** [comment]
sorry, force pushed my branch

**Pull request closed without merging**
