### PR TITLE
README: remove go report card

### PR DESCRIPTION
**Pull request by philips**
This service seems broken, probably because the k8s repo is larger than
the normal project. I have emailed the service author but for the time
being remove the badge.

### CODE REVIEW

**Comment by philips** [comment]
Here is an example, gofmt has 0% errors but is failing: https://goreportcard.com/report/k8s.io/kubernetes#gofmt

**Comment by sarahnovotny** [comment]
LGTM

**Comment by philips** [comment]
Talked to @shawnps and this is a known issue. We can revert once goreportcard is fixed: https://github.com/gojp/goreportcard/issues/139

**Comment by hermanschaaf** [comment]
Hi there, I am one of the Go Report Card maintainers (with @shawnps)

We just pushed a fix to speed up checks for repositories with generated files (by completely ignoring them), which fixes gojp/goreportcard#139. This seems to also have sped up the Kubernetes report enough that all the checks complete within a few minutes:

screenshot from 2016-08-17 00 52 49

Hopefully this is enough to get the Go Report Card badge back into the Kubernetes readme! :smile:

**Comment by sarahnovotny** [comment]
wheeeee!

Thank you

**Pull request merged**
