### PR TITLE
Automated cherry pick of #60373: Bump cfssl to be compatible with Go 1.10

### PR DESCRIPTION
**Pull request by yue9944882**
Cherry pick of #60373 on release-1.10.

Provide golang 1.10 support for kubernetes 1.10 release

#60373: Bump cfssl to be compatible with Go 1.10

Complie release-1.10 with golang 1.10 and we will get the following error:

```
$./hack/local-up-cluster.sh
...
# k8s.io/kubernetes/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment
!!! [0806 09:44:49] Call tree:
!!! [0806 09:44:49]  1: /Users/zuoxiu.jm/go/src/k8s.io/kubernetes/hack/lib/golang.sh:712 kube::golang::build_binaries_for_platform(...)
!!! [0806 09:44:49]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1
!!! Error in ./hack/local-up-cluster.sh:204
  Error in ./hack/local-up-cluster.sh:204. 'make -C "${KUBE_ROOT}" WHAT="cmd/kubectl cmd/hyperkube"' exited with status 2
Call stack:
  1: ./hack/local-up-cluster.sh:204 main(...)
Exiting with status 1
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
Kubernetes 1.10 is using go1.9.3, so I don't think the fact that it doesn't compile on go1.10 is really a bug that needs to be fixed in patch release. Is there something user facing issue this is fixing? Otherwise I'd rather not cherry-pick this.

**Comment by yue9944882** [comment]
hi @MaciekPytel,

> I don't think the fact that it doesn't compile on go1.10 is really a bug that needs to be fixed in patch release.

To clarify, kube release-1.10 can be successfully compiled by golang 1.10 and we're right now doing so in our production environment. It is the 'local-up-cluster.sh' script now failing and this cherry-pick is only for fixing that script. It's sort of inconvenient to switch between release-1.10 and master branches.

**Comment by yue9944882** [comment]
@MaciekPytel or we should explicitly forbid go versions later than 1.10 in that script. WDYT?😃

**Comment by MaciekPytel** [comment]
>To clarify, kube release-1.10 can be successfully compiled by golang 1.10 and we're right now doing so in our production environment. It is the 'local-up-cluster.sh' script now failing and this cherry-pick is only for fixing that script.

Right, the problem is this is not a few lines change in this script, which would be pretty low risk. Instead it bumps up an external dependency which can potentially introduce a bug or behavior change to all 1.10 clusters. 

>  It's sort of inconvenient to switch between release-1.10 and master branches.

Patch releases are meant for fixing production-impacting bugs (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#patch-releases). I don't think the above justifies the inherent risk of updating an external dependency.

**Comment by yue9944882** [comment]
> Dependencies, such as Docker or Etcd, should also not be changed unless absolutely necessary, and also just to fix critical bugs (so, at most patch version changes, not new major nor minor versions).

@MaciekPytel  True that it doesn't meet that requirement. 😅 

/close

**Pull request closed without merging**
