### PR TITLE
doc: fix typo in cmd

### PR DESCRIPTION
**Pull request by halfcrazy**
**What this PR does / why we need it**:
 fix typo in cmd

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jamiehannaford — APPROVED** [review]
/lgtm

**Comment by halfcrazy** [comment]
ok-to-test?

**Pull request closed without merging**
