### PR TITLE
Revert "Ignore `daemonset-controller-hash` label key in federation before comparing the federated object with its cluster equivalent."

### PR DESCRIPTION
**Pull request by janetkuo**
This reverts commit 3530c9ce8771b76ef19b1cac547c5ccc053d408a.

~This needs to wait for #47258, otherwise federation test won't pass~ (merged)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by madhusudancs** [comment]
/approve 

@janetkuo code LGTM. I will apply the label once PR #47258 is merged and the clusters are recycled.

**Comment by janetkuo** [comment]
#47258 was merged

**Comment by madhusudancs** [comment]
@janetkuo let's wait until midnight for clusters to recycle.

**Comment by janetkuo** [comment]
/retest

failure seems unrelated

**Comment by janetkuo** [comment]
federation is broken: #46827, waiting on fix to be merged

**Comment by janetkuo** [comment]
@madhusudancs now it finally passed!

**Comment by madhusudancs** [comment]
@janetkuo awesome!

/lgtm

**Pull request merged**
