### PR TITLE
test images: Minor changes to trigger postsubmit image building jobs

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/sig testing

/kind flake
/priority important-soon

**What this PR does / why we need it**:

Some of these images didn't have any job run for them. Some of these images previously failed due to an issue that has been addressed since.

Making a change into their image directory will spawn a postsubmit job that will build that image.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by spiffxp** [comment]
/retest

This is part of https://github.com/kubernetes/kubernetes/issues/96770

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Intended to trigger postsubmit jobs created via https://github.com/kubernetes/kubernetes/issues/96432

**Comment by spiffxp** [comment]
Part of https://github.com/kubernetes/k8s.io/issues/1522, https://github.com/kubernetes/kubernetes/issues/96770

**Comment by jingxu97** [comment]
@spiffxp @claudiubelu  some sig-network tests for gce failed because k8sprow.azurecr.io/kubernetes-e2e-test-images/jessie-dnsutils:1.4 is not available. From my manual checking only jessie-dnsutils:1.0 is available.

**Comment by chewong** [comment]
@jingxu97 We have stopped copying test images to k8sprow.azurecr.io since most of the test images used by master branch are available at `k8s.gcr.io/e2e-test-images`.

**Pull request merged**
