### PR TITLE
Update fluent-plugin-s3 plugin

### PR DESCRIPTION
**Pull request by oper25**
added new fluent-plugin-s3 plugin

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by coffeepac** [comment]
@oper25 

1. thanks for the PR!
2. you'll need to sign the CLA
3. what's the usecase for adding this?

**Comment by dims** [comment]
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

**Comment by dims** [comment]
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

**Pull request closed without merging**
