### PR TITLE
Remove descriptions from internal API

### PR DESCRIPTION
**Pull request by pmorie**
@thockin

### CODE REVIEW

**Comment by pmorie** [comment]
@eparis

**Comment by thockin** [comment]
This LGTM but even such changes come with risk at this point.  Is there any reason, other than tidiness to do this now?

**Comment by pmorie** [comment]
@thockin it can wait, I questioned even submitting it because I don't want to add to the noise.  I'm fine if you want to just close this for now and we can clean it up after the dust settles.

**Comment by pmorie** [comment]
Sorry for the distraction!

**Comment by thockin** [comment]
You don't need to close it, I just wanted to get a sense of whether it was
urgent or just one for the stockpile.

If you re-open it we can consider it in a few weeks.  I think we want this
anyway.

**Pull request closed without merging**
