### PR TITLE
Fix UT TestIsPodUpdated in daemonset_util_test.go

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

For UT TestIsPodUpdated in daemonset_util_test.go，
this case fails："templateGeneration and hash don't match"
then i find badGeneration equal to templateGeneration.
we should modify  badGeneration，not equal to templateGeneration.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mysunshine92** [comment]
ping @erictune

**Comment by mysunshine92** [comment]
ping @erictune

**Comment by mysunshine92** [comment]
ping @erictune

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/priority backlog
/triage accepted

**Comment by soltysh** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/pull/107241 which has a more complete fix

**Pull request closed without merging**
