### PR TITLE
Examples: fixed cassandra mirror detection that assumes an FTP site will always be presented

### PR DESCRIPTION
**Pull request by tactical-drone**
**What this PR does / why we need it**:
This fixes regressions in the cassandra example docker image creation scripts

**Which issue this PR fixes** : #45882

**Special notes for your reviewer**:
Pound that accept button, it will be fine.

**Release note**:

```
Fixed the cassandra docker image cassandra mirror detection logic
bumped cassandra to v3.10, as v3.9 is no longer on the mirrors
bumped ubuntu-slim to v0.9
```

### CODE REVIEW

**Comment by pompomJuice** [comment]
I ran it on ubuntu xenial and it works.

**Comment by resouer** [comment]
@k8s-bot ok to test

**Review by resouer — APPROVED** [review]
code change LGTM

**Comment by resouer** [comment]
Next time I think you can use `git commit --amend && git push` to amend to original PR branch, instead of opening a new one.

**Pull request merged**
