### PR TITLE
Switch to the maintained go-jose repository

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

github.com/square/go-jose has been archived, and go-jose is now "maintained" in github.com/go-jose/go-jose. This switches to v2.6.1 of the latter.

We still end up carrying gopkg.in/square/go-jose.v2 in vendor because of go-oidc. There is a version of go-oidc using go-jose/v3 but that is tied up in the protogen upgrade; see #114772 for details. The latter include a bump to go-jose/v3; if appropriate we could pull that out separately instead of this (the diffstat is only a few lines more).

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
The 2.x stream is not maintained in the go-jose repo any more, so I'm not sure I see the point in switching to it, especially if we are still *also* vendoring the square/go-jose impl still

**Comment by skitt** [comment]
> The 2.x stream is not maintained in the go-jose repo any more, so I'm not sure I see the point in switching to it, especially if we are still _also_ vendoring the square/go-jose impl still

That’s the official position, but they _did_ tag https://github.com/go-jose/go-jose/releases/tag/v2.6.1 since that notice was added.

The main driver behind this is that since https://github.com/square/go-jose is archived, if any important update happens anywhere on the v2 branch, it will be in the go-jose repo, not in the square repo; tracking the former makes it easier to quickly update if necessary.

However it might be preferable to migrate to v3 instead. https://github.com/kubernetes/kubernetes/pull/114772 is a mess but I can pull out the go-jose v3 commit into a separate PR.

**Comment by liggitt** [comment]
> That’s the official position, but they _did_ tag https://github.com/go-jose/go-jose/releases/tag/v2.6.1 since that notice was added.
> 
> The main driver behind this is that since https://github.com/square/go-jose is archived, if any important update happens anywhere on the v2 branch, it will be in the go-jose repo, not in the square repo; tracking the former makes it easier to quickly update if necessary.

I don't have good context on the archive of the square version or the spin up of the new org... are we confident in the maintainership of the new org/repo?

> However it might be preferable to migrate to v3 instead. https://github.com/kubernetes/kubernetes/pull/114772 is a mess but I can pull out the go-jose v3 commit into a separate PR.

If we can actually migrate in a way that drops out the unmaintained square/go-jose dep, that seems worth considering

**Comment by stlaz** [comment]
As per triage meeting, we think that the first thing to do here would be to verify that we are fine with the new owner of the go-jose/go-jose dependency.

The second step should be to migrate go-oidc to the new, v3 go-jose dependency, then bump it here along with moving the go-jose dep to v3, too.

**Comment by skitt** [comment]
@stlaz thanks for the update. go-oidc has already migrated to v3 in the new repository.

It occurred to me that another option might be to switch to golang-jwt; it’s already in k/k’s dependency tree, and it seems to support all the features needed (although it doesn’t expose all of them). golang-jwt seems to be well-maintained, unlike go-jose.

**Comment by skitt** [comment]
@stlaz #114772 shows how to bump to go-jose/v3 and go-oidc/v3.

**Pull request closed without merging**
