### PR TITLE
Move pkg/kubectl/cmd/util/openapi to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/cmd/util/openapi` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util/openapi.
* Creates `k8s.io/kubectl/test/data/openapi` for test data.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @nikhita 

for `staging/publishing`

**Comment by seans3** [comment]
/assign @BenTheElder 

for `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
/lgtm cancel

To stop retesting (needs rebase)

**Pull request merged**
