### PR TITLE
refactor get to remove cobra dependency

### PR DESCRIPTION
**Pull request by adohe-zz**
FYI. I am also thinking about some basic principles when we refactor CLI commands, I will put that in the doc later. @kubernetes/sig-cli-misc ptal.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot test this

**Comment by smarterclayton** [comment]
Overall shape looks good, won't be able to look at this until next week though.  Feel free to reassign

**Comment by AdoHe** [comment]
Rebased and fix unit test. @smarterclayton please take a look, there are a lot of refactor work to do, I would like to start with basic CRUD operations.

**Comment by AdoHe** [comment]
@k8s-bot gci gce e2e test this

**Comment by fabianofranz** [comment]
@k8s-bot test this

**Comment by fabianofranz** [comment]
@AdoHe needs a rebase.

**Comment by AdoHe** [comment]
@fabianofranz yes, I will rebase this asap.

**Comment by AdoHe** [comment]
@smarterclayton just rebase this, could you please help review? I would like move this forward and do more commands refactor.

**Comment by fabianofranz** [comment]
@k8s-bot test this

**Comment by fabianofranz** [comment]
@k8s-bot test this

**Comment by fabianofranz** [comment]
@adohe Needs a rebase, but apart that this looks good.

**Comment by adohe** [comment]
@fabianofranz sorry about respond so late, I just rebase this. Please take another look, I would like to get this merged asap.

**Comment by fabianofranz** [comment]
@adohe some legit failures, like needing `gofmt` in "verify", `k8s.io/kubernetes/pkg/kubectl/cmd/testing/fake.go:463: undefined: kubectl.ResourcePrinter`, bazel, etc.

**Comment by adohe** [comment]
@k8s-bot unit test this

**Pull request closed without merging**
