### PR TITLE
don't enable psp by default and fix comment

### PR DESCRIPTION
**Pull request by pweil-**
don't enable psp by default and fix comment

@gmarek

### CODE REVIEW

**Comment by pmorie** [comment]
LGTM.

**Comment by pmorie** [comment]
Removing LGTM, too trigger happy.

**Comment by pmorie** [comment]
Apologies for the premature label, @pweil-, I had missed that the first change affected the generated docs.

**Comment by pweil-** [comment]
rebased

**Comment by pweil-** [comment]
rebased

**Comment by pweil-** [comment]
failure: 
```
[Fail] Downward API [It] should provide pod IP as an env var 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1442
```

**Comment by pweil-** [comment]
@k8s-bot test this

**Comment by pweil-** [comment]
@k8s-bot test this issue: #20403

**Pull request merged**
