### PR TITLE
Improve resource quota example, add README

### LINKED ISSUE #8749: Resource quota example missing README.md
Resource quota example is missing readme.  Was it once there and was accidentally deleted?

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes #8749

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@pmorie - since you raised the issue, please review the doc.

**Comment by derekwaynecarr** [comment]
Updated with Analytics watermark per ```hack/run-gendocs.sh```

Can I get an lgtm @pmorie?

**Comment by erictune** [comment]
lgtm

**Comment by bgrant0607** [comment]
Tests fail:
```
--- FAIL: TestExampleObjectSchemas (0.83s)
	examples_test.go:333: skipping : ../examples/elasticsearch/apiserver-secret.yaml/apiserver-secret
	examples_test.go:328: ../examples/resourcequota/limits.yaml: limits does not have a test case defined
	examples_test.go:328: ../examples/resourcequota/namespace.yaml: namespace does not have a test case defined
	examples_test.go:328: ../examples/resourcequota/quota.yaml: quota does not have a test case defined
	examples_test.go:348: Expected 1 examples, Got 0
FAIL
coverage: 0.0% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/examples	0.991s
```

**Comment by derekwaynecarr** [comment]
It has not been my day.  Will fix up

**Comment by derekwaynecarr** [comment]
I have informed the examples test of my examples.

One thing that would be cool is if I didn't have to inform it.  Parse example files (yaml or json) and determine kind, from kind attempt to parse it into the proper internal struct.  Post 1.0 type of thing maybe.

Anyway, this should be passing again.

**Comment by bgrant0607** [comment]
Thanks.

**Pull request merged**
