### PR TITLE
Set CGO_ENABLED explicitly for each build command execution.

### PR DESCRIPTION
**Pull request by vishh**
It is not obvious whether CGO is used or not in certain cases. 

cc @luxas

### CODE REVIEW

**Comment by luxas** [comment]
Sorry, but this will fail.
I also tried this once some months ago, but we can't enable CGO in all cases.
Then it will also try to enable CGO when cross-compiling darwin kubectl, and it'll fail with an `net` error of some kind.

To test it out locally, run `make release` to verify if this is the case anymore.

**Comment by jfrazelle** [comment]
depending on the net error it might just need a `-a`

**Comment by vishh** [comment]
Testing on OS X now.

**Comment by luxas** [comment]
@vishh The long story here is that we're cross-compiling test binaries for OS X, and if we're setting `CGO_ENABLED` always to 1, I think the gc linker will search for OS X cgo libraries and fail when there are no such libraries installed in `kube-cross`. The solution is to make the test targets also statically linked ('cause they don't have C code I think, correct me if I'm wrong)

But I'm fixing effectively all of these statements in #26028, so can we proceed the discussion there? (And it has been up for ~2 months)

**Comment by vishh** [comment]
@luxas Thanks for explaining! Closing this PR in favor of #26028

**Pull request closed without merging**
