### PR TITLE
Delete the duplicate description of v1.19.0 dependency

### PR DESCRIPTION
**Pull request by houjun41544**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
There are duplicate descriptions about v1.19.0 dependency。
[https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by MHBauer — COMMENTED** [review]
Also duplicated in the table of contents/index at the top.

Not sure if this will need to be cherry-picked to 1.19 branch.

**Review by hasheddan — COMMENTED** [review]
@houjun41544 could you update table of contents as @MHBauer suggested here?

**Comment by houjun41544** [comment]
@hasheddan Updated! Thank you for reminding.

**Pull request closed without merging**
