### PR TITLE
Fixed typo in getting-started-guides:scratch

### PR DESCRIPTION
**Pull request by arisu1000**

### CODE REVIEW

**Comment by arisu1000** [comment]
I signed it!

**Comment by ashcrow** [comment]
Shippable 1.3 failure is unrelated to the changes in this PR:

```
F0930 08:57:41.895343   16701 integration.go:967] This test has timed out.
```

**Comment by wojtek-t** [comment]
LGTM - thanks for your change!

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by arisu1000** [comment]
Thanks!

**Pull request merged**
