### PR TITLE
Move tolerations to PodSpec for calico-node.yaml.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by gmarek** [comment]
I have similar comment as in second PR from the list - why do we have those tolerations at all? @caseydavenport

**Comment by gyliu513** [comment]
@gmarek the calico node needs to be run on all nodes, including both master and worker node, so I think that we still need the `tolerations`?

**Comment by gmarek** [comment]
Nope, we don't. Daemonset will run everywhere (if nothing changes when I wasn't watching).

**Comment by caseydavenport** [comment]
> Daemon pods do respect taints and tolerations

@gmarek according to [the daemonset documentation](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled) taints/tolerations are respected by DaemonSets.

**Comment by caseydavenport** [comment]
It doesn't look like any of the nodes in these scripts actually get taints applied to them, so there's probably a case for just removing these altogether. 

cc @dnardo

**Comment by dnardo** [comment]
I think for the master that is true,  But we still want the ciritical pod should work right?

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by gyliu513** [comment]
Done, thanks @dnardo and @gmarek

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by gyliu513** [comment]
@mikedanese can you please mark this as milestone 1.7, otherwise  it may not get merged due to submit queue now only allowing PRs with 1.7 milestone.

**Pull request merged**
