### PR TITLE
migrate kubelet and scheduler event test to sig instrumentation

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:

Migrate event relevant e2e tests to sig-instrumentation. Not fully sure, please feel free to contact me if you have better solution.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Ref Umbrella issue #49161

**Special notes for your reviewer**:

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by fejta** [comment]
LGTM

/ok-to-test
/assign @crassirostris @DirectXMan12 @fabxc @fgrzadkowski @piosz @x13n 
/unassign @spxtr @fejta

**Comment by crassirostris** [comment]
I don't agree with the incentive of this PR

Sig-instrumentation team doesn't control the code that generates those events, so we can't e.g. fix a bug that was escalated to sig level without involvement of sig-scheduling or sig-node. Overall these sigs have much more context into why these tests may be failing and how to fix it.

I'd say that sig-instrumentation is responsible for the pipelines for logs and metrics, not the concrete log entries, metrics, or events

**Comment by fgrzadkowski** [comment]
+1 to what Mik wrote. SIG instrumentation is responsible for the pipeline itself, not for verifying that individual components will generate expected events.

**Comment by crassirostris** [comment]
This test should be divided into several and moved into appropriate folders (e.g. node and scheduling)

**Comment by guangxuli** [comment]
Hmm, yes, this event test just to check events for scheduler and kubelet component. I am not sure which group is fit this file. sig-scheduling or sig-node or divided into several just as @crassirostris mentioned. @yujuhong @enisoc any idea?

**Comment by guangxuli** [comment]
After check the code carefully i think we should not divide the event into sig-scheduling and sig-node, because it is a conformance test between scheduler and kubelet.

**Comment by guangxuli** [comment]
hi @enisoc do you agree to put event e2e file to scheduler folder ?

**Comment by yujuhong** [comment]
What @crassirostris suggested sounds good to me.

**Comment by guangxuli** [comment]
@yujuhong thanks, will do that.

**Comment by guangxuli** [comment]
The events e2e test file has been move to sig node folder, ref #54279, so close this PR is reasonable now.

**Pull request closed without merging**
