### PR TITLE
Bumped debian-base from 2.0.0 to 2.0.1

### PR DESCRIPTION
**Pull request by sambdavidson**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Bump debian base to catch vuln fixes. This bump has already been pushed. Just reflecting that push in the repository

/assign @tallclair @immutableT

### CODE REVIEW

**Comment by spiffxp** [comment]
/test pull-kubernetes-integration 
re: pull-kubernetes-node-e2e-containerd, it's been timing out most of the day, it's non-blocking https://github.com/kubernetes/kubernetes/issues/89847

**Comment by BenTheElder** [comment]
FTR this PR did not update the digests etc. necessary to actually pick up the changes. https://github.com/kubernetes/kubernetes/pull/90507

**Pull request merged**
