### PR TITLE
WIP: test: Add node e2e test to verify static pod termination

### PR DESCRIPTION
**Pull request by bobbypage**
Add node e2e test to verify that static pods can be started after a previous static pod with the same config temporarily failed termination.

The scenario is:

1. Static pod is started
2. Static pod is deleted
3. Static pod termination fails (internally `syncTerminatedPod` fails), e.g. due to volume unmount failing
4. At later time, pod termination should succeed, (volumes unmount successfully) 
5. New static pod with the same config is (re)-added
6. New static pod is expected to start successfully (but it does not, because the pod is lost - it is not in config or in runtime pods anymore and as such no updates are delivered to the pod worker)

To repro this scenario, setup a pod using a NFS mount. The NFS server is stopped which will result in volumes failing to unmount and `syncTerminatedPod` to fail. The NFS server is later started, allowing the volume to unmount successfully.

xref:

1. https://github.com/kubernetes/kubernetes/pull/113145#issuecomment-1289587988
2. https://github.com/kubernetes/kubernetes/pull/113065
3. https://github.com/kubernetes/kubernetes/pull/113093
4. https://github.com/kubernetes/kubernetes/issues/113091

Signed-off-by: David Porter <david@porter.me>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by smarterclayton** [comment]
Merged into #113145

**Pull request closed without merging**
