### PR TITLE
Automated cherry pick of #90980: Avoid using socket for hints

### PR DESCRIPTION
**Pull request by iwankgb**
Cherry pick of #90980 on release-1.19.

#90980: Avoid using socket for hints

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Using NUMA nodes instead of sockets for CPU manager hints.
```

### CODE REVIEW

**Comment by iwankgb** [comment]
This cherry-pick accompanies #99209 to fix #98870 for 1.19.

**Comment by ehashman** [comment]
@iwankgb does this also affect 1.18? We will need a backport for that branch as well, it's still supported.

Please add a release note.

/priority important-soon
/triage accepted
/ok-to-test

**Comment by klueska** [comment]
Did the change I reviewed for 1.20 apply cleanly, or were there any merge conflicts that needed to be resolved in the backport?

**Comment by iwankgb** [comment]
@ehashman original PR lacks release note. Should I add some anyway?
@klueska the change applied cleanly.

**Comment by klueska** [comment]
Thanks for confirming

/lgtm
/approve

**Pull request merged**
