### PR TITLE
auto nominate aojea to test reviewers

### PR DESCRIPTION
**Pull request by aojea**
following the communite guidelines I'd like to ask to be included as a reviewer in the `test/OWNERS`
I've been doing reviews and contributing in the test area for almost 2 years now, mainly in networking related bits, 
just I want to formalize it because I will keep doing it ;)

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
+1

**Comment by dims** [comment]
Big +1

**Comment by SataQiu** [comment]
+1

**Comment by aojea** [comment]
hahah ironically the ipv6 jobs fails
`pull-kubernetes-conformance-kind-ipv6-parallel -- Job failed.`

**Comment by oomichi** [comment]
big +1

/lgtm

**Comment by alejandrox1** [comment]
Huge +1
Thank you for everything you do @aojea 
/approve

**Comment by BenTheElder** [comment]
/lgtm
/approve
+1000

**Comment by aojea** [comment]
Thanks folks, appreciate the support given

**Pull request merged**
