### PR TITLE
Increase default value of apps/v1beta2 DeploymentSpec.RevisionHistoryLimit to 10

### LINKED ISSUE #49913: Increase default value of DeploymentSpec.RevisionHistoryLimit to 10 in apps/v1beta2
All controllers that use the `RevisionHistoryLimit` field have a default value of 10 for the field, except for `Deployment`, which has a default of 2. We should increase it to 10 for consistency on its default value across controllers. 

/sig apps

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

All controllers that use the `RevisionHistoryLimit` field have a default value of 10 for the field, except for `Deployment`, which has a default of 2. We should increase it to 10 for consistency on its default value across controllers.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49913

**Special notes for your reviewer**:
/cc @janetkuo @foxish @liyinan926

**Release note**:

```release-note
Increase default value of apps/v1beta2 DeploymentSpec.RevisionHistoryLimit to 10
```

### CODE REVIEW

**Comment by liyinan926** [comment]
@dixudx We only plan to do this for `apps/v1beta2`. You also need to update `defaults_test.go`.

**Comment by dixudx** [comment]
@liyinan926 Updated. PTAL. Thanks.

**Comment by liyinan926** [comment]
LGTM.

**Comment by sttts** [comment]
@tsmetana can you take a look here?

**Comment by sttts** [comment]
Wrong Tomas it seems. @tnozicka ptal

**Comment by bgrant0607** [comment]
Ref https://github.com/kubernetes/features/issues/353

@dixudx @liyinan926 I don't see this mentioned in #49135

Also, default values should be documented in the API documentation in the field comments in v1beta2/types.go.

Both the API documentation and the release note should be written for Kubernetes users, not just for Kubernetes contributors, which means they should use the json names, not Go type/field names.

**Comment by liyinan926** [comment]
@bgrant0607 this is part of the work on "ensure that the defaults and validation are consistent and appropriate across all controllers." mentioned in #49135. #49913 has more details on inconsistency of the default value of `RevisionHistoryLimit`.

**Comment by liyinan926** [comment]
@dixudx you will also need to update https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1beta2/defaults.go#L105 and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/apps/v1beta2/types.go#L310.

**Review by kow3ns — CHANGES_REQUESTED** [review]
You will need to update the documentation at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/apps/v1beta2/types.go#L310 to reflect the new default value. You will have to re-run code generation to get the documentation change to pick up.

**Comment by dixudx** [comment]
@liyinan926 @kow3ns Updated. PTAL. Thanks.

**Review by kow3ns — APPROVED** [review]

**Comment by kow3ns** [comment]
@dixudx could you please update the release note to indicate that the default value applies to the Deployment Kine apps/v1beta2 GroupVersion to disambiguate from extensions?

**Comment by dixudx** [comment]
@kow3ns Done.

**Comment by mml** [comment]
:-1:

/unassign wojtek-t

**Comment by mml** [comment]
OK, after all those gymnastics, it looks like @kow3ns has this under control.

/unassign

**Comment by dixudx** [comment]
@thockin @smarterclayton Needs your `approval`. Thanks.

**Comment by thockin** [comment]
FWIW the corr3ct protocol would be to `/assign thockin` which makes it WAY more visible to me. :)

**Pull request merged**
