### PR TITLE
set proxy when build containers for users behind proxy

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Fixes: https://github.com/kubernetes/kubernetes/issues/49921

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
how about 

```
MacPro-2:kubernetes klaus$ git diff
diff --git a/build/common.sh b/build/common.sh
index 80c6fc7d8a..ebc5de71ff 100755
--- a/build/common.sh
+++ b/build/common.sh
@@ -568,6 +568,8 @@ function kube::build::run_build_command_ex() {
     --env "GOFLAGS=${GOFLAGS:-}"
     --env "GOLDFLAGS=${GOLDFLAGS:-}"
     --env "GOGCFLAGS=${GOGCFLAGS:-}"
+       --env "http_proxy=${http_proxy:-}"
+       --env "https_proxy=${https_proxy:-}"
   )

   # If we have stdin we can run interactive.  This allows things like 'shell.sh'
```

**Comment by jbeda** [comment]
@k82cn I don't think that'll work when the build container runs on a different machine (VM locally or remote machine) from the workstation.

/approve
/lgtm

**Pull request merged**
