### PR TITLE
doc: fix typo in docs

### PR DESCRIPTION
**Pull request by halfcrazy**
**What this PR does / why we need it**:
fix typo in docs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by halfcrazy** [comment]
ok-to-test?

**Comment by php-coder** [comment]
This is all generated docs, could you also find and fix the original typo?

**Comment by halfcrazy** [comment]
@php-coder The origin typo will be corrected in my pull request https://github.com/kubernetes/kubernetes/pull/59136/files .

**Comment by php-coder** [comment]
@halfcrazy Typically, changes in types.go should go together with generated data in the same PR (but it different commits). I even don't sure that the tests will pass as they check for that.

**Comment by halfcrazy** [comment]
cherry-picked to #59136

**Pull request closed without merging**
