### PR TITLE
Move all CHANGELOG files into a folder

### PR DESCRIPTION
**Pull request by Spacebody**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Move all CHANGELOG files into a folder, so that the structure of this repo becomes more concise and it keeps the list of files shown in webpage short, even more CHANGELOG files will be added in future. 

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
Just a cleanup for the structure of this repo.

**Does this PR introduce a user-facing change?**:
None

```release-note
Move all CHANGELOG files into a folder `CHANGELOG`
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by Spacebody** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Signed.

**Comment by liggitt** [comment]
thanks for the PR, changelogs have been relocated under the CHANGELOG folder independently

/close

**Pull request closed without merging**
