### PR TITLE
fixtodo: move node status condition code to kubelet_node_conditions.go to be centralized

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
I notice there is a TODO in kubelet_node_status.go:`the node status condition code out to a different file.`. So I  move node status condition code to kubelet_node_conditions.go to be centralized and add unit test for the functions. I am not sure if this TODO is necessary. If this TODO is meaningless, I will close this PR.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
[#61628](https://github.com/kubernetes/kubernetes/issues/61628)
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mtaufen** [comment]
Hi @hanxiaoshuai. Thanks for this work.

I'm currently in the middle of a refactor that goes a little further and moves these to a separate package, explicitly injects the data dependencies, and adds better test coverage for these setters. If it would be possible to leave things as they are a bit longer, it will make it much easier for me to keep this refactor up-to-date with upstream (cleaner rebase). 

I can add you as a reviewer on the refactor, if you're interested.

**Comment by hanxiaoshuai** [comment]
@mtaufen Oh, I am very interested in it. It is great if  I Could be a reviewer on the refactor. Thanks

**Comment by tallclair** [comment]
Closing per @mtaufen's comment.

**Pull request closed without merging**
