### PR TITLE
Fix source annotation in kubelet

### LINKED ISSUE #13875: Update annotations in kubelet broke source annotations
PR #13334 allows kubelet to update annotations.

This broke mirror pods because they contain the original source annotations.
 - Mirror pod contains all annotations from the original static pod, including `config.source: file`
 - When the config watcher first sees the mirror pod from the apiserver, it sets the `config.source: api` to the annotations in the mirror pod and caches it.
 - The next time, the config watcher would compare the mirror pod with the copy in the cache, and sees the difference:
```
existing: map[string]string{"kubernetes.io/config.mirror":"mirror", "kubernetes.io/config.seen":"2015-09-11T19:10:12.335167065Z", "kubernetes.io/config.source":"api"}
new: map[string]string{"kubernetes.io/config.mirror":"mirror", "kubernetes.io/config.seen":"2015-09-11T19:09:21.926288705Z", "kubernetes.io/config.source":"file"}
```
The config watcher would then think this is an update and trigger a kubelet pod sync. The mirror pod would also be mistaken as regular pod later on in kubelet, causing more attempts to create a mirror pod. These extra syncs and operations may have caused the cpu spikes observed in #12429

Kubelet should always overwrites the source annotation before comparing existing and the new pods at the config watcher.

### PR DESCRIPTION
**Pull request by yujuhong**
kubelet relies on source annotation to distinguish pods from different sources.
It should always annotate the source when receiving the pod to avoid any
confusion. This commit fixes that and also make sure we don't overwrite the
first seen time.

This PR fixes #13875

### CODE REVIEW

**Comment by yujuhong** [comment]
Need to fix the unit tests.

**Comment by yujuhong** [comment]
Ready for review. I ended up having to clean up the test quite a bit.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
ok to test

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by dchen1107** [comment]
This PR is marked as LGTM for at least 2 days, and ok-to-merge is not required for @yujuhong. Even though, @alex-mohr added that one day ago. Why it is not merged still?

**Comment by lavalamp** [comment]
The log level is not high enough, I can't see in the logs why it keeps getting skipped...

**Comment by alex-mohr** [comment]
Sorry for the delay in merging.  @lavalamp is pushing the submit queue with fixes and a higher log level so we can see why this hasn't merged.  Hopefully not too much longer, and hope it doesn't cause you a rebase!

**Comment by yujuhong** [comment]
No problem. @lavalamp, @alex-mohr, thanks for looking into it.

**Comment by yujuhong** [comment]
It'd be good to merge this sooner, as the bug is causing the integration test to be unstable, blocking #12894 to go in.

**Comment by alex-mohr** [comment]
@lavalamp Did you get a chance to restart the merge bot with higher log level to figure this one out?

**Comment by nikhiljindal** [comment]
Self merging to unblock other PRs. We are getting close to 1.1 code freeze.

**Comment by lavalamp** [comment]
@alex-mohr Yes; it says "submit-queue.go:155] Error validating PR status: <nil>"

Which, if I read correctly, means that it didn't recognize the testing status. I think there's a bug in there somewhere. I or @brendandburns should add some more logging to see exactly what it was unhappy about

**Pull request merged**
