### PR TITLE
Automated cherry pick of #48636

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #48636 on release-1.7.

#48636: Fix issues for local storage allocatable feature

### CODE REVIEW

**Comment by dashpole** [comment]
@jingxu97 can you run the localStorageAllocatableEviction node e2e test on this, just as a sanity check that this works on the 1.7 branch?

**Comment by jingxu97** [comment]
@dashpole I run the test localStorageAllocatableEviction and it passed. PTAL

**Pull request merged**
