### PR TITLE
e2e test replace CreateSync in createPodOrFail

### PR DESCRIPTION
**Pull request by JornShen**
/kind bug
/kind cleanup

failing test: [sig-network] Services should serve a basic endpoint from pods [Conformance]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1361731285994704896

replace it with CreateSync
 
```release-note
NONE
```

### CODE REVIEW

**Comment by JornShen** [comment]
ref  https://github.com/kubernetes/kubernetes/pull/99202/files#r578542283

**Comment by JornShen** [comment]
I also think is it here suitable for us to skip it or not pop error out and failed the test? @aojea 
The pod error creating is not test content of these test cases, they are the prepare content of cases.

**Comment by aojea** [comment]
/lgtm
Great, thanks for following up

> I also think is it here suitable for us to skip it or not pop error out and failed the test?

If we skip or not error we can't guarantee that this functionality works,  nobody will notice that this test case didn't run
IMHO we should skip only for scenarios that we know the test is going to fail, i.e. an AWS test in a GCP cluster.
Suppressing errors is not a good bad practice and it always end abused, tests results should be binary, or pass or not pass, if the test have false positives or negatives.

> The pod error creating is not test content of these test cases, they are the prepare content of cases.

The e2e test must guarantee that the systems works correctly, every step is part of the test, this is not like in an integration test that you spawn an external database to test your code, in this case the pods are part of the system under test and can not fail.

**Pull request merged**
