### PR TITLE
Automated cherry pick of #15183 #15428 upstream release 1.1

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #15183 #15428 upstream release 1.1

### CODE REVIEW

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@mikedanese 

    Generated docs are out of date. Please run hack/update-generated-docs.sh
    !!! Error in hack/verify-generated-docs.sh:28
      '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1

Can you please fix that?

**Pull request merged**
