### PR TITLE
force rbd image unlock if the image is not used

### LINKED ISSUE #31790: Ceph : Unable to mount volumes for pod ... : rbd: image ext4-0002 is locked by other nodes
Version

kubernetes v1.3.6

Description

All pods using a ceph persistent storage are in state : 
Unable to mount volumes for pod ... : rbd: image ext4-0002 is locked by other nodes

Steps To Reproduce

All pods were running correctly on all nodes
A node crash during the week-end (don't know why wet)
Current Result

All pods using ceph persistent volumes are in this state.
On the ceph cluster, each rbd has one exclusive lock

Expected Result

Unlock the rbd before mounting it on another node

The problem was discussed here https://github.com/openshift/origin/issues/7983 but seems like this is the most appropriate place.

The problem is the same in v1.3.6 as the code handling this is the same.

I seems relevant to this https://github.com/kubernetes/kubernetes/pull/10563#issuecomment-128361389 and maybe to this https://github.com/kubernetes/kubernetes/issues/20262

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
Ceph RBD image could be locked if the host that holds the lock is down. In such case, the image cannot be used by other Pods. 

The fix is to detect the orphaned locks and force unlock.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #31790

**Special notes for your reviewer**:

Note, previously, RBD volume plugin maps the image, mount it, and create a lock on the image. Since the proposed fix uses `rbd status` output to determine if the image is being used, the sequence has to change to: rbd lock checking (through `rbd lock list`), mapping check (through `rbd status`), forced unlock if necessary (through `rbd lock rm`), image lock, image mapping, and mount.

**Release note**:

```release-note
force unlock rbd image if the image is not used
```

### CODE REVIEW

**Comment by rootfs** [comment]
@k8s-bot gci gke e2e test this

**Comment by smarterclayton** [comment]
Added label based on comments.

**Comment by Hexta** [comment]
@rootfs What will happen when the host that previously locked the image connects to Ceph again? In the case of temporary network failure, for example.

**Comment by rootfs** [comment]
@Hexta The unlock is preempted when the rbd image is no longer used. If the dead host restarts, it has to check the lock before re-mapping the image. By that time, the host will detect a lock held by others and thus voluntarily withdraw.

A more robust solution is to leverage exclusive lock that becomes available in kernel rbd.

**Comment by Hexta** [comment]
@rootfs OK But I  asked what will happen in the case of a temporary network error. The host can reconnect to Ceph without restarting.

**Comment by rootfs** [comment]
@Hexta yes, in such case, we have to rely on exclusive lock.

**Comment by rootfs** [comment]
@Hexta created an issue #43809 
will start working on it.

**Comment by pdumais** [comment]
@rootfs: According to your comment on March 29, and according to my experiments, am I correct in assuming that the failed node must have been restarted in order for the lock to be released? In my situation, if the failed node stays down, the other nodes won't ever be able to acquire the lock because "rbd status" will still list watchers. I was under the impression that this case would be detected as orphaned and the lock would be released as per line #164 of this PR.

**Pull request merged**
