### PR TITLE
Add debugging output to mungedocs when --verbose=true.

### PR DESCRIPTION
**Pull request by mml**
Hope to understand why verify-generated-docs is failing on jenkins but
not here.

### CODE REVIEW

**Comment by zmerlynn** [comment]
I'm crunched, reassigning for now.

**Comment by eparis** [comment]
So every time I run git commit I'm going to get spammed with all sorts of lines?

**Comment by eparis** [comment]
no, I get it now.  /me learns to read.  I'm not sure why I need it.  Can't I just run update-generated-docs ? Why would I want something that could be diffed like this?

**Comment by eparis** [comment]
I'd much rather have just the output that matters, even if it isn't in the unified diff format.  How about writing a new helper, like Equal, which gives you 'lines removed' and 'lines added' ?   Then we just print those. Instead of before/after?

**Comment by mml** [comment]
How about I leave behind a TODO comment to do that?  Even as crappy as this is, it did help me figure out why a test was failing when before there was no useful output at all.

**Comment by eparis** [comment]
ok. p.s. why was the test failing? normally I'd tell people to use `hack/update-generated-docs.sh; git diff`

**Comment by mml** [comment]
> ok. p.s. why was the test failing? normally I'd tell people to use hack/update-generated-docs.sh; git diff

In all the cases I've found, the test passes when run outside docker, but fails within because a markdown dependency was missing from the docker image.  While I can run verify-generated-docs within docker, update-generated-docs doesn't currently work (meaning export) inside docker.

**Pull request merged**
