### PR TITLE
Update schedule logic to properly calculate missed schedules

### PR DESCRIPTION
**Pull request by kmala**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

cherry-pick of #118724  and #118940 

#### Which issue(s) this PR fixes:

`None`

#### Does this PR introduce a user-facing change?

```release-note
Fix cronjob controller handling of complex schedules, like "30 6-16/4 * * 1-5", for example
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
