### PR TITLE
HugePages feature is beta in 1.10 release

### LINKED ISSUE #53672: HugePages work tracker
This issue is meant to track planned work items for pre-allocated hugepages across releases.

This issue captures the plan of record discussed in the wg-resource-mgmt meetings.

## v1.9
- [x] HugePages should be restricted via ResourceQuota [**Owner**: @lichuqiang , fixed #54292]

Assess ability to graduate feature to beta.

## 1.10
- [x] HugePages should require the user to request cpu or memory [**Owner**: @tanshanshan fixed #54379]
- [x] HugePages should not be tied to QoS [**Owner**: @tanshanshan fixed #54379]
- [ ] HugePages promoted to beta [**Owner:** @derekwaynecarr, #56939]

## Future
- [ ] HugePages isolated at container and not just pod boundary [**Owner**: TBD]
- [ ] HugePages should be restricted via LimitRange [**Owner**: TBD]

cc @sjenning @jeremyeder @vishh @ConnorDoyle @kubernetes/sig-node-feature-requests

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What this PR does / why we need it**:
Graduate support of HugePages to beta.

**Which issue(s) this PR fixes**
Fixes #53672

**Special notes for your reviewer**:

```release-note
HugePages feature is beta
```

### CODE REVIEW

**Comment by tianshapjq** [comment]
/cc 
looks like a huge project.

**Comment by brendandburns** [comment]
@derekwaynecarr what has changed between the 1.9 release and now to make this qualify for beta?

If we have additional work planned, it feels like we should wait until its done.

If we don't have additional work planned, why wait to 1.10?

**Comment by tianshapjq** [comment]
@brendandburns [HugePages work tracker](https://github.com/kubernetes/kubernetes/issues/53672), maybe this is the work plan for 1.10.

**Comment by brendandburns** [comment]
Looked at the work tracker, let's merge this once the other two items in the beta list are merged...

**Comment by derekwaynecarr** [comment]
@brendanburns -- i held this pending merge of https://github.com/kubernetes/kubernetes/pull/54379

**Comment by derekwaynecarr** [comment]
@brendandburns -- prerequisite pr has merged, this should be good to go.

**Pull request merged**
