### PR TITLE
Random typo fix

### PR DESCRIPTION
**Pull request by JHilker**
**What this PR does / why we need it**: Random typo fix, because why not.

**Which issue(s) this PR fixes**  N/A

**Special notes for your reviewer**: N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by JHilker** [comment]
Signed CLA

**Comment by msau42** [comment]
Test CLA

**Comment by JHilker** [comment]
Ok, actually signed CLA 😬

image

**Pull request merged**
