### PR TITLE
Update scripts for syncing client-go

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Use `hack/godep-restore.sh` instead of `godep restore` to sync the staged content. I encountered the same issue #42403 when running `godep restore`.

Use `hack/update-staging-client-go.sh` instead of `staging/copy.sh` according to the hint when running `staging/copy.sh`
```
Do not run this script directly, but via hack/update-staging-client-go.sh.
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
Thanks, @xiangpengzhao.

**Comment by caesarxuchao** [comment]
@k8s-bot kops aws e2e test this

**Comment by caesarxuchao** [comment]
@thockin could you help approve the change? Thanks.

**Comment by xiangpengzhao** [comment]
ping @dchen1107 or @thockin for approve. thanks!

**Comment by xiangpengzhao** [comment]
Close this one because a later PR #45503 has included the change here.

**Pull request closed without merging**
