### PR TITLE
GCE: bump COS image version to cos-beta-73-11647-64-0

### PR DESCRIPTION
**Pull request by yguo0905**
This PR bumps COS image version to `cos-beta-73-11647-64-0` from `cos-stable-65-10323-64-0`.

Compared with the previous one, the new image has

 - Docker upgrade from 17.03 to 18.09.
 - Kernel upgrade from 4.4 to 4.14.

**Does this PR introduce a user-facing change?**:

```release-note
GCE: bump COS image version to cos-beta-73-11647-64-0
```

/kind feature
/cc @filbranden 
/cc @yujuhong 
/cc @dchen1107

### CODE REVIEW

**Review by filbranden — APPROVED** [review]
/lgtm

Thanks @yguo0905 !

**Comment by Random-Liu** [comment]
This broke the containerd test.

That is fine! It time to change the containerd test setup script to work with Docker 18.09 :)

**Pull request merged**
