### PR TITLE
Change some logic about lock 

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind cleanup
/kind design

**What this PR does / why we need it**:

Change some logic about lock.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
Thanks, @cwdsuzhou for your PR. Did you see any actual improvement from this change? We recently made a similar change to pod affinity and we saw worse performance in practice. Besides, you are optimizing the path that the scheduler communicates with extenders. Communicating with extenders is very slow and improving lock contention probably will not make much of a difference. Moreover, it is very unlikely that a scheduler has more than one or two prioritizing extenders. So, there may not be much of a lock contention among extenders to begin with.

**Comment by cwdsuzhou** [comment]
Thanks for your clarification @bsalamat

**Pull request closed without merging**
