### PR TITLE
test images: sets HOME=/root in cloudbuild.yaml

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind bug
/sig testing
/priority important-soon

**What this PR does / why we need it**:

The default cloudbuild has ``HOME=/builder/hom``e and docker buildx is in ``/root/.docker/cli-plugins/docker-buildx``

We need to set the HOME to /root explicitly since we're using docker buildx.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Documentation: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md#simple-build-example

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by hh** [comment]
Flake or Failure:
/test pull-kubernetes-bazel-test
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96238/pull-kubernetes-bazel-test/1324116929438289920#1:build-log.txt%3A172
> TIMEOUT: //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test (Summary)

**Comment by hh** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-test

Seems pretty flakey overall today:
image

**Pull request merged**
