### PR TITLE
COS: Keep the docker network checkpoint

### PR DESCRIPTION
**Pull request by yujuhong**
This is necessary for enabling the live-restore feature.

**What this PR does / why we need it**:
This is necessary for enabling the live-restore feature on COS.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
COS: Keep the docker network checkpoint
```

### CODE REVIEW

**Comment by cblecker** [comment]
@yujuhong With #55260 being merged, is this PR still valid?

**Comment by yujuhong** [comment]
> @yujuhong With #55260 being merged, is this PR still valid?

Not needed for now, but will need it later when bumping the COS image version. Keeping the PR open.

**Pull request merged**
