### PR TITLE
kube-apiserver: enable admissionregistration v1beta1 api by default

### PR DESCRIPTION
**Pull request by sttts**
We have this enabled in the GCE cluster and in local-cluster-up, but forgot to switch the default. If we want people to use this feature by default in production clusters, we better enable the API.

Moreover, this PR fixes that beta works without alpha.

```release-note
Enable admissionregistration.k8s.io/v1beta1 by default in kube-apiserver.
```

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/approve no-issue

@lavalamp @smarterclayton We have a beta tag, but I didn't see candidates.  I'm inclined to merge for 1.9.0.  Comments?

**Comment by caesarxuchao** [comment]
I'll close https://github.com/kubernetes/kubernetes/pull/56644 since this one is more complete.

**Pull request merged**
