### PR TITLE
Update guestbook frontend php script as suggested in issue #18640.

### PR DESCRIPTION
**Pull request by amygdala**
Update guestbook frontend php script as suggested in issue #18640.
(also created new GCR image version with the changes).

### CODE REVIEW

**Comment by bshaffer** [comment]
LGTM

**Comment by bgrant0607** [comment]
cc @carlosrdrz

**Comment by bgrant0607** [comment]
It would be useful for someone with a non-privileged account to confirm that they can pull the new image.

**Comment by amygdala** [comment]
@bgrant0607 Brian, I got Takashi, who is not on the google-samples project, to do a test pull of gcr.io/google-samples/gb-frontend:v4, and he was successful.

**Comment by bgrant0607** [comment]
Thanks, @amygdala.  LGTM

**Pull request merged**
