### PR TITLE
Modify `apimachinery` imports using `staging`

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

Currently some of the imports of `apimachinery` use
`k8s.io/kubernetes/staging/src/k8s.io/apimachinery...`. Replace
these with `k8s.io/apimachinery`, as is in use throughout the rest
of the code base.

Signed-off-by: mattjmcnaughton <mattjmcnaughton@gmail.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
Ah, it looks like I may have failed to take some step regarding `BUILD` files - I'll fix and push an updated diff, and then retest.

**Comment by kargakis** [comment]
/assign @mikedanese

needs an approval

**Comment by mattjmcnaughton** [comment]
@mikedanese just wanted to give a quick ping - this is ready for a look whenever you get the chance - thanks so much :)

**Comment by mikedanese** [comment]
Ya this is better.

/lgtm

**Pull request merged**
