### PR TITLE
Cherry pick 65711 65786

### LINKED ISSUE #65647: Problem with kubectl apply `-o jsonpath` or `-o go-template` flags
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind** ***bug***

**What happened**: 
I have a test suite that uses the output of `kubectl apply` with `-o jsonpath` flag set. It has been working fine in 1.10.5 and below but not in 1.11. 

Issuing the following command, results in the following error: 
```
kubectl apply -f /tmp/pod.yaml -o=jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'
error: unable to match a printer suitable for the output format "jsonpath={.kind }{.metadata.namespace} {.metadata.name}", allowed formats are: json,name,yaml
```
I get similar error if I use go-templates

**What you expected to happen**:
In previous version I would get this: 
```
kubectl apply -f /tmp/pod.yaml -o=jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'
Pod default apiserver-f6ayla
```

**How to reproduce it (as minimally and precisely as possible)**:
Problem is not found in `kubectl get` but so far only in `kubectl apply`. 
To reproduce issue a `kubectl apply` with `-o =jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'` flags set or similar.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):

> NAME="Ubuntu"
> VERSION="16.04 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
This cherry picks #65711 and #65786 onto release 1.11.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65647

/assign @deads2k @juanvallejo 
for review
/assign @foxish 
for 1.11 approval

**Release note**:
```release-note
fixes a regression in kubectl printing behavior when using go-template or jsonpath output that resulted in a "unable to match a printer" error message
```

### CODE REVIEW

**Comment by deads2k** [comment]
compile failure.  Dirty pick?

**Comment by soltysh** [comment]
> compile failure. Dirty pick?

Yeah, unfortunately parts had to be fixed manually and I'm only a human :cry:

**Review by juanvallejo — APPROVED** [review]

**Comment by liggitt** [comment]
/sig cli
/priority critical-urgent
/milestone v1.11
/status approved-for-milestone

priority is to fix regression in printing behavior

**Comment by foxish** [comment]
Is this good to go @liggitt @soltysh

**Comment by soltysh** [comment]
@foxish - yes

**Comment by deads2k** [comment]
/lgtm

@juanvallejo can you pick up the rebase here.

**Comment by juanvallejo** [comment]
@deads2k 

On it

**Comment by juanvallejo** [comment]
@deads2k rebased here https://github.com/kubernetes/kubernetes/pull/65979

**Comment by foxish** [comment]
Please close this if https://github.com/kubernetes/kubernetes/pull/65979 supersedes it.

**Pull request closed without merging**
