### PR TITLE
Remove buggy GCE post turn-up cluster validation code (rely on validate-cluster.sh)

### LINKED ISSUE #7266: Remove the "Attempt N to check Docker and pause pod" loop from GCE turn-up
There's a section of code where it says "Sanity checking cluster" for GCE that I always assumed was in `validate-cluster.sh`, but is GCE OSS specific, here: https://github.com/GoogleCloudPlatform/kubernetes/blob/cf824ae5e07965ba0b4b15ee88e08e2679f36978/cluster/gce/util.sh#L697 . I believe after the addition of `getcomponentstatuses` and various Docker monitoring improvements, this entire section of code can just be gutted. Furthermore, I think that after the switch to cAdvisor in a pod, the code is actually buggy: I spun up a 10 node GCE cluster and logged into a node, and the `/pause` pod that I had was a `fluentd` related one, which isn't guaranteed to exist.

cc @fabioy @satnam6502

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes #7266

### CODE REVIEW

**Comment by satnam6502** [comment]
I have prepared exactly the same PR.
Does GCE cluster bring up work after this change?

S

**Comment by satnam6502** [comment]
I ask because after my version of this (identical?) change I can no longer bring up a cluster.
```
Using master: kubernetes-master (external IP: 104.154.78.159)
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

..............................................................
```

**Comment by roberthbailey** [comment]
As an aside, when turning up clusters I often see it slow down on this piece of validation and repeatedly say that docker isn't working yet on various nodes. Do we expect this to now be caught by the cluster validation instead?

**Comment by zmerlynn** [comment]
Yes, I had no trouble with cluster bring up. The "waiting forever" loop is actually before this hunk of code, so that's a different issue?

And yes, I expect it to get caught by cluster validation. After this, you may see validate loop a couple of times instead (I did).

**Comment by roberthbailey** [comment]
The waiting forever loop just makes sure we can curl the master. This loop checked that the nodes were ready and healthy. But I think that the cluster validation below also checks that nodes are ready and healthy so it should be redundant.

**Pull request merged**
