### PR TITLE
Use the existing RS instead of the updated one

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fix for https://github.com/kubernetes/kubernetes/pull/20897

cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@nikhiljindal - changing this in my PR fixes the problem. However, it seems the problem may be somewhere else - I will try to debug it. But thanks a lot for exposing the problem!
@lavalamp - FYI

**Comment by wojtek-t** [comment]
OK - I understand what is happening here.

Basically, the problem is that you are trying to do a no-op update. And if that's the case, we seem to be returning an empty object (which is a bug). I will fix that independently.

**Comment by wojtek-t** [comment]
OK - since I'm able to fix it now, I'm closing this PR.

**Comment by lavalamp** [comment]
Yup, @wojtek-t found the underlying cause. Thanks @nikhiljindal

**Pull request closed without merging**
