### PR TITLE
Delete unused interface

### PR DESCRIPTION
**Pull request by farah**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Interface `Expectations` was created 5 years ago and is never used.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
"NONE"
```

### CODE REVIEW

**Comment by farah** [comment]
Thanks @cheftako. Could you approve? :)

**Comment by cheftako** [comment]
Sorry @farah I'm not an owner for pkg/controller. Going with the suggestion above.
/assign @erictune

**Comment by farah** [comment]
@erictune just a friendly ping.

**Comment by farah** [comment]
@erictune hi eric, could you please take a look? :)

**Comment by farah** [comment]
Hi @deads2k  @cheftako, could either of you guys take a look at this PR? It's very small change. I think @erictune  is currently inactive.

**Comment by cheftako** [comment]
Sorry @farah still working my way to becoming an owner. @deads2k is a good choice :+1:

**Review by pacoxu — APPROVED** [review]

**Comment by farah** [comment]
@cheftako 
@deads2k 

Friendly bump.

**Pull request merged**
