### PR TITLE
Update Owners for Scheduler

### PR DESCRIPTION
**Pull request by timothysc**
Update Owners file for scheduler component to spread the reviews around. 

/cc @davidopp  per previous sig-mtg.

### CODE REVIEW

**Comment by davidopp** [comment]
@gmarek isn't going to be working on scheduler after the taints/tolerations work so please remove him

**Comment by timothysc** [comment]
> @gmarek isn't going to be working on scheduler after the taints/tolerations work so please remove him 

done.

**Comment by davidopp** [comment]
I'm not sure whether @wojtek-t wants to be in assignees -- I'll let him decide. The way we've been doing it so far is that I've been reassigning to him when it's something I think he is best suited for. Since scheduler isn't really his main focus, I'm not sure it's fair to give him 1/3 of the random reviews.

**Comment by wojtek-t** [comment]
>
I'm not sure whether @wojtek-t wants to be in assignees -- I'll let him decide. The way we've been doing it so far is that I've been reassigning to him when it's something I think he is best suited for. Since scheduler isn't really his main focus, I'm not sure it's fair to give him 1/3 of the random reviews.

I'm fine with that for now. If it would be too much, I we can change it in the future.

**Pull request merged**
