### PR TITLE
kubeadm: pass etcd progress notification flag to etcd

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The experimental-watch-progress-notify-interval flag specifies an interval
at which etcd sends data to the kube-api server.

It is used by the WatchBookmark feature which is GA since 1.17.
It will be used by a new WatchList feature which is Alpha since 1.25

In addition to that the feature was graduated to GA (non-experiment) in etcd 3.5 without any code changes
#### Which issue(s) this PR fixes:

xref: https://github.com/kubernetes/kubeadm/issues/2731

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: enable the --experimental-watch-progress-notify-interval flag for etcd and set it to 5s. The flag specifies an interval at which etcd sends watch data to the kube-apiserver.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the pr. i think you need to run ./hack/update-gofmt.sh first.

/approve
/triage accepted

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: enable the --experimental-watch-progress-notify-interval flag for etcd and set it to 5s. The flag specifies an interval at which etcd sends watch data to the kube-apiserver.
```

**Comment by p0lyn0mial** [comment]
> thanks for the pr. i think you need to run ./hack/update-gofmt.sh first.

I did, plus `pull-kubernetes-verify` is happy. I think we are good.

**Comment by aojea** [comment]
awesome :clap:

**Pull request merged**
