### PR TITLE
Remove some useless code

### PR DESCRIPTION
**Pull request by weekface**
**What this PR does / why we need it**:
code optimization,remove some useless code.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
/ok-to-test

@weekface Please rebase and squash your commits, the later commit will cause errors when cherry-picking and rebasing.

**Comment by weekface** [comment]
@dixudx Squashed. PTAL

**Comment by weekface** [comment]
@liggitt PTAL

**Review by php-coder — APPROVED** [review]

**Pull request merged**
