### PR TITLE
Add createdby annotation for rbd and quobyte and make dynamical createdby key const

### PR DESCRIPTION
**Pull request by NickrenREN**
make dynamical createdby key const

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by krmayankk** [comment]
@NickrenREN what is the problem being solved ? We are using rbd provisioner heavily and i am interested in knowing what are you using these annotations for ?

**Comment by NickrenREN** [comment]
Just added for rbd and quobyte for display and keep same with other provisioners

**Comment by jsafrane** [comment]
lgtm, but rebase please.

**Comment by NickrenREN** [comment]
Thanks @jsafrane , done

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
