### PR TITLE
Revert "Use a helper to find built binaries"

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts GoogleCloudPlatform/kubernetes#6783

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @ixdy

**Comment by eparis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/6815    reverts only the broken portion....

**Comment by dchen1107** [comment]
Ok, close this one. Thanks!

**Comment by eparis** [comment]
reopened.  @dchen1107 was right.  just revert the whole thing.

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
