### PR TITLE
[ubuntu] kube-down gracefully

### LINKED ISSUE #17147: [ubuntu] kube-down gracefully
kube-down should be conducted only after all of the resouces being deleted completely. Otherwise we would suffer 
```
$ rm -rf /var/lib/kubelet
rm: cannot remove ‘/var/lib/kubelet/pods/24c42a99-8818-11e5-b321-005056b45392/volumes/kubernetes.io~secret/default-token-t6sw8’: Device or resource busy
```

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #17147

### CODE REVIEW

**Comment by dalanlan** [comment]
ping @zmerlynn

**Comment by zmerlynn** [comment]
Isn't this going to conflict with your other PR, #17055? I was vaguely pausing until that was resolved. cc @MikeSpreitzer

**Comment by dalanlan** [comment]
Rebase done

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
