### PR TITLE
Fix hack/update-codecgen.sh script

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
