### PR TITLE
Update PV/PVC assume cache with invalidations in scheduler factory.

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Update PV/PVC assume cache with invalidations in scheduler factory.

There is no guarantee in which order different event handlers will be
called. If we use different event handlers, it's possible PV/PVC assume
cache will be updated after invalidations.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
/assign @msau42 
I found it's possible PV/PVC assume cache will be updated after invalidations, because order of event handlers to be called is random. 

Quoted from https://godoc.org/k8s.io/client-go/tools/cache#SharedInformer:

```
// AddEventHandler adds an event handler to the shared informer using the shared informer's resync
// period.  Events to a single handler are delivered sequentially, but there is no coordination
// between different handlers.
```

So I think it's better to update PV/PVC assume cache with invalidations. This is like current [scheduler cache implementation](https://github.com/kubernetes/kubernetes/blob/v1.14.0-alpha.0/pkg/scheduler/factory/factory.go#L806).

**Comment by msau42** [comment]
The whole predicate ecache design is being redesigned/reconsidered, so maybe we should hold off on this until we have a better understanding of the new design.  I prefer to avoid leaking volume binder cache details into the scheduler if we can.

Do you see a problem if the informer caches are updated at a different time?

**Comment by resouer** [comment]
@msau42 @cofyc We don't need to do invalidate in `factory.go` after the new design of eclass cache. See:  https://docs.google.com/document/d/1x907Ow183mHVdmIgBO_BjZA0DPjPnB1lzCRnbBtm1Ks/edit

**Comment by cofyc** [comment]
/close
In favor of new design.

**Pull request closed without merging**
