### PR TITLE
keep dashboard in burstable QoS

### LINKED ISSUE #49189: Dashboard memory limits/requests do not ensure Guaranteed QoS as stated in comment
As discussed in https://github.com/kubernetes/kubernetes/pull/44712#discussion_r126015758, recent changes on the memory limits of the dashboard made it loose its Guaranteed QoS as the limit and request are now different:

```
diff --git a/cluster/addons/dashboard/dashboard-controller.yaml b/cluster/addons/dashboard/dashboard-controller.yaml
index 92a389056d..1c583c1d80 100644
--- a/cluster/addons/dashboard/dashboard-controller.yaml
+++ b/cluster/addons/dashboard/dashboard-controller.yaml
@@ -25,10 +25,10 @@ spec:
           # keep request = limit to keep this container in guaranteed class
           limits:
             cpu: 100m
-            memory: 50Mi
+            memory: 300Mi
           requests:
             cpu: 100m
-            memory: 50Mi
+            memory: 100Mi
         ports:
         - containerPort: 9090
         livenessProbe:
```

The memory limits should probably be fixed to restore the Guaranteed QoS on that pod.

> If limits and optionally requests (not equal to 0) are set for all resources across all containers and they are equal, then the pod is classified as Guaranteed.

cf. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md#qos-classes

/kind bug

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

Fix Dashboard memory limits to ensure Guaranteed QoS

**Which issue this PR fixes** : fixes #49189

**Special notes for your reviewer**:
cc @maciaszczykm @pdecat

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
We switched it on purpose, because 100m is too low value for Dashboard especially when we are handling logs and large numbers of resources.

cc @floreks @bryk @kubernetes/dashboard-maintainers

**Comment by maciaszczykm** [comment]
Regarding: https://github.com/kubernetes/kubernetes/pull/44712#discussion_r126074747

Other solutions are increasing requests value to match limits or removing this comments. Merging this pull request may cause out of memory issues for Dashboard.

**Comment by dixudx** [comment]
@maciaszczykm So a preferred way is to modify the comment. Right?

What about changing the comment to "Keep this container in Burstable class to avoid out of memory issue for Dashboard" ?

**Comment by floreks** [comment]
> What about changing the comment to "Keep this container in Burstable class to avoid out of memory issue for Dashboard" ?

Looks good to me.

**Comment by maciaszczykm** [comment]
Can we remove it completely perhaps?

**Comment by dixudx** [comment]
@maciaszczykm It would be okay to completely remove the comment. But I'd prefer to keep it to tell others why we set it to Burstable QoS. WDYT.

@floreks Any comments?

**Comment by maciaszczykm** [comment]
@dixudx It is fine for me.

**Comment by dixudx** [comment]
@maciaszczykm @floreks PTAL. Thanks.

**Comment by maciaszczykm** [comment]
I am looking at you comment after changes and it is not true:

```
# Keep this container in burstable class to avoid out of memory issue
```

Keeping it in burstable class does not allow us to avoid out of memory issues. Setting high enough value does.

**Comment by dixudx** [comment]
@maciaszczykm Well, it's true. If we had enough resource, we can also keep it in `guaranteed` class.

To avoid such confusing comment, I think removing it completely is better. WDYT.

**Comment by maciaszczykm** [comment]
I can keep it in burstable class (i.e. 30m/50m) and it will still crash due out of memory issues.

**Comment by maciaszczykm** [comment]
It should be closed. https://github.com/kubernetes/kubernetes/pull/53046 is newer.

**Comment by roberthbailey** [comment]
@dixudx - please reopen if you'd like to see further progress on this PR.

**Pull request closed without merging**
