### PR TITLE
Add fatal message

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Add fatal message

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
How about "expected an error"

**Comment by zhangxiaoyu-zidif** [comment]
Hi, @mikedanese I fix the message.
PTAL, thanks a lot.

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
Small test error message fix so adding 1.7.

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
