### PR TITLE
Use context in controller-manger.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

1. Use the single context (or stopch) in all goroutines (SecureServing server, InsecureServing server and controllers.)
2. Add ability to propagate stop signal to goroutines.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/sig apps

### CODE REVIEW

**Comment by liggitt** [comment]
I don't object to the change in the Run method, but this doesn't actually change any behavior, correct?

**Comment by jfbai** [comment]
> I don't object to the change in the Run method, but this doesn't actually change any behavior, correct?

@liggitt Thanks a lot. :)

When run method panic, it means all the controllers should stop and the insecure and secure server should stop,  but in current logic, there is no action to propagate the close channel signal to the child goroutine.

**Comment by liggitt** [comment]
ok... but practically, if Run panics, the process exits, so clean teardown is meaningless, right?

/cc @sttts

**Comment by liggitt** [comment]
I'll defer to @sttts on the run plumbing, though I don't particularly see the point of this change

**Pull request closed without merging**
