### PR TITLE
Update common.go

### PR DESCRIPTION
**Pull request by wangzhuzhen**
Make code more readable.

### CODE REVIEW

**Comment by wangzhuzhen** [comment]
I signed it！

**Comment by euank** [comment]
-1, I think this is less readable because it conveys less information; before it was clear the second return value will always be nil, now it requires reading 4 lines to get that same information.

**Comment by wangzhuzhen** [comment]
hi, @euank 
Thanks for your reply.
I have closed this PR.
I commit this PR because when I read this code, the first return value is nil, but the second return value represent it as "pod", I know it means nil too, but why not use nil directly? Meanwhile, in the second function tryDecodePodList(), the first and second return values are pods，so i commit this PR，change the first return value as pod.

**Pull request closed without merging**
