### PR TITLE
Automated cherry pick of #114863: Use label selector for filtering out resources when pruning.
#115571: Add integration test for diff --prune --selector

### PR DESCRIPTION
**Pull request by nathanmartins**
Cherry pick of #114863 #115571 on release-1.25.

#114863: Use label selector for filtering out resources when pruning.
#115571: Add integration test for diff --prune --selector

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Make kubectl diff --prune behave correctly with the --selector/-l flag
```

### CODE REVIEW

**Comment by KnVerey** [comment]
/approve
/triage accepted
/release-note-edit ```Make kubectl diff --prune behave correctly with the --selector/-l flag```

**Comment by KnVerey** [comment]
/release-note-edit

```
Make kubectl diff --prune behave correctly with the --selector/-l flag
```

**Comment by KnVerey** [comment]
/release-note-edit ```release-note Make kubectl diff --prune behave correctly with the --selector/-l flag```

/cc kubernetes/release-managers

**Comment by KnVerey** [comment]
/release-note-edit

```release-note
Make kubectl diff --prune behave correctly with the --selector/-l flag
```

**Comment by Verolop** [comment]
@KnVerey @nathanmartins in order to accept this cherry pick for 1.25, I requested a LGTM for 1.26 & 1.24. We typically like to include all affected branches when merging a backport.
thanks!

**Comment by nathanmartins** [comment]
@ardaguclu @danlenar, can you guys approve this, please?

**Review by Verolop — COMMENTED** [review]
/lgtm

**Comment by Verolop** [comment]
@nathanmartins since it was already approved by the relevant reviewers, and one of the branches was ready to go, I LGTM'd the other two so they could make it on time for the deadline.
Thanks!

**Pull request merged**
