### PR TITLE
fix-up test/e2e/common/e2elog

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
 use log functions of core framework
**Which issue(s) this PR fixes**:
Ref #81427
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/lgtm
/approve

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for doing this :)

**Comment by tanjunchen** [comment]
@oomichi  @mattjmcnaughton  you are welcome

**Comment by liggitt** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Comment by alejandrox1** [comment]
/hold
we need to look at this in testing commons
/assign @andrewsykim @timothysc @alejandrox1

**Pull request closed without merging**
