### PR TITLE
kubelet: Imporve cmd comment for how kubelet works

### PR DESCRIPTION
**Pull request by gxglls**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR imporve cmd comment of kubelet which describe how kubelet works，the old description  is inaccurate after k8s 1.6+ version，about CRI / docker / container runtime

### CODE REVIEW

**Comment by gxglls** [comment]
HI @matthyx @Random-Liu , this pr pass all test, can it add tags approve to continue, thanks!

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit
the bot hangs for merge

**Pull request merged**
