### PR TITLE
WIP: windows: Fix Pods with Projected Volumes

### LINKED ISSUE #102849: Windows Pods with a Projected Volume is stuck at ContainerCreating
#### What happened:

When a Windows Pod is created with a Projected Volume is stuck at ContainerCreating

#### What you expected to happen:

The Pod should go to Running.

#### How to reproduce it (as minimally and precisely as possible):

Create a Windows Pod with a Projected Volume.

#### Anything else we need to know?:

The KEP, [proposal for file permission handling in projected service account volume](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d#diff-f4218ebfe0ced84087844da9d87b126752414e347e727c0455687d69e8e3d912) and its [implementation](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d) did not take Windows in to account. An [os.Chown()](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d#diff-f4218ebfe0ced84087844da9d87b126752414e347e727c0455687d69e8e3d912R403) was introduced which is not supported on Windows.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration: AWS / Azure 
- OS: Windows Server 2019 1809
- Kernel:

### PR DESCRIPTION
**Pull request by aravindhp**
#### What type of PR is this?

/kind bug
/kind regression

#### Which issue(s) this PR fixes:
Fixes #102849

#### Special notes for your reviewer:
Not ready for review yet

#### Does this PR introduce a user-facing change?
NONE

### CODE REVIEW

**Comment by liggitt** [comment]
cc @msau42 @zshihang fyi

**Comment by aravindhp** [comment]
This is on hold until https://github.com/microsoft/Windows-Containers/issues/136 can be resolved.

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Pull request closed without merging**
