### PR TITLE
Add prefix to common networking e2e tests

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Common networking e2e tests shared by node and cluster suites should also have prefix `[sig-network]`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Umbrella issue #49161

**Special notes for your reviewer**:
/cc @bowei 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
@bowei 

This should be moved to a networking subdirectory.  See kubectl for an example.

**Comment by pwittrock** [comment]
@k8s-bot ok to test

**Comment by pwittrock** [comment]
This should also use the Ginkgo framework to set the prefix, not manually add it.

**Comment by bowei** [comment]
@xiangpengzhao  can you sync up with @pwittrock regarding what changes are needed?

**Comment by pwittrock** [comment]
Rather, why is this test file in the "common" directory, when it only contains network tests?  Shouldn't it be in the "network" directory?

**Comment by bowei** [comment]
I think it's also reused by node tests. Perhaps it needs both tags (sig-node and sig-network) or none, depending on what policy we are taking for shared tests...

**Comment by xiangpengzhao** [comment]
>This should be moved to a networking subdirectory. See kubectl for an example.

@pwittrock as per https://github.com/kubernetes/kubernetes/pull/49942#issuecomment-319442072, this is shared by node e2e also. So it should be left where it is now.

**Comment by xiangpengzhao** [comment]
>Perhaps it needs both tags (sig-node and sig-network) or none, depending on what policy we are taking for shared tests...

IMO, we are looking for owners for e2e test cases, no matter whether they are shared by cluster e2e and node e2e. So prefix it in this PR with [sig-network] would be ok. @grodrigues3 WDYT?

**Comment by xiangpengzhao** [comment]
>This should also use the Ginkgo framework to set the prefix, not manually add it.

Will address this when we have a consensus on above comments :)

**Comment by xiangpengzhao** [comment]
@pwittrock @bowei PTAL. Thanks!

**Comment by xiangpengzhao** [comment]
Hope the test flake `pull-kubernetes-node-e2e` can be fixed in #50591.

**Comment by xiangpengzhao** [comment]
#50591 merged and image flake was flake, but the timeout flake still exists. weird.
/retest

**Comment by xiangpengzhao** [comment]
After taking anther look at the test failures (described in #50590), I think the root cause if that I import `k8s.io/kubernetes/test/e2e/network` and use `network.SIGDescribe` to set the prefix. Note that when the package is imported, these cluster e2e tests of network will be running in node e2e (which should not).

If we do want to add prefix of these common e2e tests, we may still have to manually add it, as the first version of this PR did. I find that [e2e/common/volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/volumes.go) also did in that way. See: #50054

**Comment by xiangpengzhao** [comment]
I will revert it to the former way to verify this.

**Pull request merged**
