### PR TITLE
WIP: DO NOT MERGE: Test Ubuntu 22.04 Jammy

### PR DESCRIPTION
**Pull request by bobbypage**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111232/pull-kubernetes-e2e-gce-ubuntu-containerd/1549181715329585152/

Failed `Kubernetes e2e suite: [It] [sig-node] NodeProblemDetector should run without error`


```
I0719 00:33:15.748]   [38;5;13mTest Panicked[0m
I0719 00:33:15.748]   [38;5;13mIn [1m[It][0m[38;5;13m at: [1m/usr/local/go/src/runtime/panic.go:99[0m
I0719 00:33:15.748] 
I0719 00:33:15.748]   [38;5;13mruntime error: slice bounds out of range [:-1][0m
I0719 00:33:15.748] 
I0719 00:33:15.749]   [38;5;13mFull Stack Trace[0m
I0719 00:33:15.749]     k8s.io/kubernetes/test/e2e/node.glob..func8.2()
I0719 00:33:15.749]     	test/e2e/node/node_problem_detector.go:160 +0x29ae
I0719 00:33:15.749] [38;5;243m------------------------------[0m
I0719 00:33:15.749] [38;5;14mS[0m[38;5;14mS[0m
I0719 00:33:15.749] [38;5;243m------------------------------[0m
```

**Comment by bobbypage** [comment]
fix for the NPD ubuntu issue - https://github.com/kubernetes/kubernetes/pull/111238

**Comment by bobbypage** [comment]
Got a green run on pull-kubernetes-e2e-gce-ubuntu-containerd  - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111232/pull-kubernetes-e2e-gce-ubuntu-containerd/1549304629219561472/

**Comment by endocrimes** [comment]
oh this is awesome - thanks @bobbypage

**Comment by bobbypage** [comment]
rebased again upstream

**Comment by bobbypage** [comment]
pull-kubernetes-e2e-gce-ubuntu-containerd passed - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111232/pull-kubernetes-e2e-gce-ubuntu-containerd/1551657508009938944/

**Pull request closed without merging**
