### PR TITLE
Automated cherry pick of #123069: build etcd image v3.5.12
#123150: etcd: Update to version 3.5.12

### PR DESCRIPTION
**Pull request by bzsuni**
Cherry pick of #123069 #123150 on release-1.26.

#123069: build etcd image v3.5.12
#123150: etcd: Update to version 3.5.12

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
etcd: Update to version 3.5.12
```

### CODE REVIEW

**Comment by bzsuni** [comment]
for approval please 
@dims

**Comment by humblec** [comment]
@bzsuni can you please rebase this PR ?

**Comment by humblec** [comment]
@bzsuni friendly ping as without this 1.28 and 1.27 PRs will not get in .. thanks in advance!

**Comment by bzsuni** [comment]
> @bzsuni friendly ping as without this 1.28 and 1.27 PRs will not get in .. thanks in advance!

I'm very sorry, I didn't notice your ping @humblec

**Comment by bzsuni** [comment]
@saschagrunert and this, thank you very much

**Comment by saschagrunert** [comment]
This PR is not approved.

**Comment by bzsuni** [comment]
> ahrtr

The approve label did not take effect，for approval again please @ahrtr

**Comment by bzsuni** [comment]
cc @dims 
for approval please

**Comment by humblec** [comment]
Thanks @bzsuni .. no worries on missing ping 👍 ..

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
@humblec ah I see it's for Kubernetes v1.26, which is no longer actively maintained: https://kubernetes.io/releases/patch-releases/#1-26

Do you mind closing this PR?

**Comment by bzsuni** [comment]
> @humblec ah I see it's for Kubernetes v1.26, which is no longer actively maintained: https://kubernetes.io/releases/patch-releases/#1-26
> 
> Do you mind closing this PR?

#121803 this also for v1.26，maybe can this be merged? @saschagrunert

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/kubernetes/pull/121803 is part of the Feb patches, which is the last one for v1.26.

**Pull request closed without merging**
