### PR TITLE
Fix kube-up for GKE. cluster-version is no more.

### PR DESCRIPTION
**Pull request by gmarek**
cc @roberthbailey

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
This change LGTM. I'm not GKE expert, but since we hope this will fix tests I will merge once all checks pass.

**Comment by fgrzadkowski** [comment]
(For the last 2 weeks kubernetes-soak-weekly-deploy-gke jenkins project is red)

**Comment by roberthbailey** [comment]
Which test suite still needs this?

**Comment by gmarek** [comment]
GKE soak tests.

**Comment by jlowdermilk** [comment]
Actually `cluster-version` and is needed by gke-ci.

**Pull request merged**
