### PR TITLE
Make node e2e exit nonzero on test failures

### PR DESCRIPTION
**Pull request by ixdy**
Probably need to cherry-pick this to 1.3 too.

cc @lavalamp @pwittrock @fejta

### CODE REVIEW

**Comment by ixdy** [comment]
This is basically a partial revert of #26461.

**Comment by fejta** [comment]
LGTM

**Comment by ixdy** [comment]
looks safe to merge

**Comment by lavalamp** [comment]
@k8s-oncall I'm going to manually merge this to remove false passes from the e2e node test.

**Comment by fabioy** [comment]
@ixdy Could you create a PR for this cherrypick?

**Comment by apelisse** [comment]
cc @lavalamp

**Pull request merged**
