### PR TITLE
Fix e2e flake: Sync deployment status when with RecreateDeploymentStrategy

### PR DESCRIPTION
**Pull request by janetkuo**
Addresses #19732

Deployment status may fail to update due to conflict. Retry it periodically. 

cc @mqliang @nikhiljindal @ghodss @ironcladlou @kargakis @bgrant0607

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot unit test this

**Comment by kargakis** [comment]
lgtm

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by janetkuo** [comment]
@k8s-bot test this

**Comment by janetkuo** [comment]
@k8s-bot e2e test this

**Comment by janetkuo** [comment]
@k8s-bot e2e test this

**Comment by nikhiljindal** [comment]
cc @k8s-oncall: This should help with fixing e2e flakes.
Please feel free to manually merge this, since the merge bot is blocked.

**Comment by nikhiljindal** [comment]
@k8s-bot test this please

**Pull request merged**
