### PR TITLE
Add link to diagram of `kubectl rolling-update`

### PR DESCRIPTION
**Pull request by andreykurilin**
fixes issue: #kubernetes/kubernetes.github.io#528

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/25810)

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@andreykurilin where the original image is located?

**Comment by andreykurilin** [comment]
@idvoretskyi: at kubeenetes.github.io repo. see https://github.com/kubernetes/kubernetes.github.io/pull/529

**Comment by idvoretskyi** [comment]
@andreykurilin good.

**Comment by smarterclayton** [comment]
It would be more appropriate to point the user from the help command to a documentation page on k8s.io rather than to an SVG directly.

**Comment by andreykurilin** [comment]
@smarterclayton It will not work, since docs from k8s is fully generated from command description, so if link to image is missed in docstrings, a proper page at k8s will not display image.

**Comment by smarterclayton** [comment]
That sound like a doc problem then.  Putting an image markdown file in a
help command to get it to show up on the docs seems like we have a gap in
our doc generation flow.

**Comment by idvoretskyi** [comment]
cc @kubernetes/docs - folks, possibly you may suggest something.

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
As per discussion in other thread it's fine to add for now.

**Comment by janetkuo** [comment]
ok to test

**Comment by janetkuo** [comment]
Pasting my comment from https://github.com/kubernetes/kubernetes.github.io/pull/529:

I feel that this diagram contains implementation details and therefore is more suitable for developers rather than end users. WDYT?

**Comment by andreykurilin** [comment]
kubernetes.github.io part is merged yesterday.

**Comment by andreykurilin** [comment]
@janetkuo @smarterclayton Do I need to do any additional changes? or everything is ok?

**Comment by andreykurilin** [comment]
Can anyone put LGTM tag or abandon this PR?

**Comment by andreykurilin** [comment]
smarterclayton thanks

**Comment by andreykurilin** [comment]
@smarterclayton How can I recheck tests?

**Comment by smarterclayton** [comment]
@k8s-bit test this issue #IGNORE

**Pull request merged**
