### PR TITLE
chore: move Azure caches to a separate package

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup
/priority important-soon
/sig cloud-provider
/area provider/azure

**What this PR does / why we need it**:

chore: move Azure caches to a separate package.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
@liggitt could you help to approve vendor changes?
/assign @liggitt

**Pull request merged**
