### PR TITLE
[WIP] Add events for pending namespace deletions

### LINKED ISSUE #70916: Make it clear why a namespace is still in Terminating
Users need to know why a namespace is not being deleted when it has been in the Terminating state for a sufficiently long amount of time (see #64002). We should have a status condition or set of events that make it clear which objects the namespace deleter is trying / failing to delete.

/kind feature
/sig api-machinery

### PR DESCRIPTION
**Pull request by wozniakjan**
**What type of PR is this?**
/kind feature
/sig cli
/sig api-machinery

**What this PR does / why we need it**:
For users to understand what is preventing the namespace deletion and not remove `kubernetes` finalizer from namespaces: https://github.com/kubernetes/kubernetes/issues/64002, https://github.com/kubernetes/kubernetes/issues/60807, https://github.com/kubernetes/kubernetes/issues/66735

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70916

**Special notes for your reviewer**:
sample output
```
$ kubectl describe ns test
Name:         test
Labels:       <none>
Annotations:  <none>
Status:       Terminating

No resource quota.

No resource limits.
Events:
  Type     Reason            Age                  From                  Message
  ----     ------            ----                 ----                  -------
  Warning  FailedDiscovery   2m8s (x18 over 12m)  namespace-controller  Failed to discover resources: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
```

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the pull request, but if the namespace is terminating, no events will be allowed to be created in it

**Comment by wozniakjan** [comment]
interesting, this differs from my observation. I clearly see a namespace in terminating with events created for it.

**Comment by liggitt** [comment]
> interesting, this differs from my observation. I clearly see a namespace in terminating with events created for it.

I added my own finalizer to a namespace to get it to stick in terminating mode:
```
$ kubectl get ns foo -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2018-11-27T14:13:59Z"
  deletionTimestamp: "2018-11-27T14:20:25Z"
  name: foo
  resourceVersion: "346"
  selfLink: /api/v1/namespaces/foo
  uid: aef36ed2-f24e-11e8-8fbd-8a006092ee01
spec:
  finalizers:
  - foo.bar.com/foo
status:
  phase: Terminating
```

then tried to create an event in it:
```
$ more event.json 
{"kind":"Event","apiVersion":"v1","metadata":{"name":"foo","namespace":"foo"},"involvedObject":{}}

$ kubectl create -f event.json 
Error from server (Forbidden): error when creating "event.json": events "foo" is forbidden: unable to create new content in namespace foo because it is being terminated
```

what invocation are you using to start your API server? do you have the NamespaceLifecycle admission plugin enabled? It is enabled by default unless you override admission plugins with `--admission-plugins` and omit it

**Comment by wozniakjan** [comment]
> what invocation are you using to start your API server? do you have the NamespaceLifecycle admission plugin enabled? It is enabled by default unless you override admission plugins with --admission-plugins and omit it

@liggitt I believe `NamespaceLifecycle` is enabled
```
--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```
I examined the event
```
LAST SEEN   FIRST SEEN   COUNT     NAME                                                        KIND        SUBOBJECT                                TYPE      REASON             SOURCE                                   MESSAGE
3m          1h           28        test.156afe43094989d5                                       Namespace                                            Warning   FailedDiscovery    namespace-controller                     Failed to discover resources: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
```
The involved object is populated correctly but namespace is actually `default`
```
Name:             test.156afe43094989d5
Namespace:        default
...
Involved Object:
  API Version:       v1
  Kind:              Namespace
  Name:              test
  Resource Version:  17608019
  UID:               b09b5e9f-f23a-11e8-b89b-fa163e041cac
```

And I suspect the culprit is this part of the code
https://github.com/kubernetes/kubernetes/blob/7c8274ecdfb885daf606adf222b45af0e39b151a/pkg/controller/namespace/namespace_controller.go#L77

I will take a look how persistent volume controller implements the events, PVs are "also" not namespaced so that should be a pattern I was supposed to follow I think

**Comment by wozniakjan** [comment]
@dims thanks for running the tests, I completely forgot about checking if I didn't break any (turns out I did)

**Comment by wozniakjan** [comment]
closing in favour of https://github.com/kubernetes/kubernetes/pull/73405

**Pull request closed without merging**
