### PR TITLE
Remove deprecated comment about cleanup the target_path of CSI volumes

### LINKED ISSUE #101332: Deprecate and remove behaviour of kubelet removing CSI nodepublish path
This came out from discussion in https://github.com/kubernetes/kubernetes/pull/101305#discussion_r617708905 

The kubelet should not be removing node-publish directory (or file for block volumes). Kubelet should only be responsible for removing parent directory and corresponding json files. It is the storage provider which should remove the node-publish directory.

/sig storage

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It was deprecated to removal of CSI nodepublish path by kubelet in 1.22.

FYI: https://github.com/kubernetes/kubernetes/pull/101441

#### Which issue(s) this PR fixes:

Fixes #101332

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [CSI spec]: https://github.com/container-storage-interface/spec/blob/da58351ba3d7baf850877be3425e76ff30645d33/spec.md#nodeunpublishvolume
```

### CODE REVIEW

**Comment by gnufied** [comment]
Is there a way we can verify that drivers that are being moved from intree to out of tree at least have been fixed? We will have to probably do manually, but we should do it IMO.

**Comment by carlory** [comment]
@gnufied  I checked the latest version of the following volume plugins.

| Driver           | remove target path | CSI Driver                                                   |
| ---------------- | ------------------ | ------------------------------------------------------------ |
| AWS EBS          | yes                | https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/mount_linux.go#L139 |
| Azure Disk       | yes                | https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/pkg/azuredisk/nodeserver.go#L302 |
| Azure File       | yes                | https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefile/nodeserver.go#L134 |
| Ceph FS          | yes                | https://github.com/ceph/ceph-csi/blob/devel/internal/cephfs/nodeserver.go#L570 |
| Ceph RBD         | yes                | https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/nodeserver.go#L929 |
| GCE PD           | yes                | https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/utils_linux.go#L89 |
| OpenStack Cinder | yes                | https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/mount/mount.go#L234 |
| Portworx         | yes                | https://github.com/libopenstorage/openstorage/blob/master/csi/node.go#L269 |
| vSphere          | yes                | https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/pkg/csi/service/node.go#L221C27-L221C45 |

The following storage drivers will not have CSI migration support.

- Flocker 
- GlusterFS
- Quobyte          
- ScaleIO             
- StorageOS        
- PhotonPersistentDisk

**Comment by carlory** [comment]
> We deprecated this and added a test to csi-sanity to ensure the driver removes the target_path a long time ago (>2.5 years) so I don't see much risk in removing this now. Maintained drivers should pass the sanity test and remove target_path during NodeUnpublish.

the sanity test validates this case [`should remove target path`](https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L453). I have check migrating volume plugins is ok, but I have a worry about other csi drivers that may not adopt this requirement and they never do sanity test. i.e. vmware/cloud-director-named-disk-csi-driver. So I think we should add a ActionRequired label in release-note to notify user to check their csi driver again before they upgrade k8s cluster.

cc @xing-yang @dobsonj what do you think?

**Comment by dobsonj** [comment]
> > We deprecated this and added a test to csi-sanity to ensure the driver removes the target_path a long time ago (>2.5 years) so I don't see much risk in removing this now. Maintained drivers should pass the sanity test and remove target_path during NodeUnpublish.
> 
> the sanity test validates this case [`should remove target path`](https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L453). I have check migrating volume plugins is ok, but I worry about other csi drivers that may not adopt this requirement and they never do sanity test. i.e. vmware/cloud-director-named-disk-csi-driver. So I think we should add a ActionRequired label in release-note to notify user to check their csi driver again before they upgrade k8s cluster.
> 
> cc @xing-yang @dobsonj what do you think?

Thanks a lot for checking all the migrated plugins, and for your fix in vmware/cloud-director-named-disk-csi-driver :)

The spec states that "The SP MUST delete the file or directory it created at this path" as part of [NodeUnpublishVolume](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume) and the sanity test [validates it](https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L453), so IMO it's a bug in the driver if it does not adhere to the spec at this point.

I think it makes sense to release note it (the note you have looks fine to me). I'm not so sure ActionRequired is necessary though, do we really want to ask users to audit their CSI drivers for correct behavior before upgrading?

**Comment by carlory** [comment]
https://github.com/container-storage-interface/spec/pull/335.

This PR's title and description identify that it clarifies staging and target paths for blocks. But the changes in the PR are not consistent with the description. It looks like the PR also take effect on volumes with an access type of mount. In the NodeUnpublishVolumeRequest section, the PR adds the following text:

```
// The SP MUST delete the file or directory it created at this path.
```

Creation of target_path is the responsibility of the SP, so it makes sense to say that the SP must delete the file or directory it created at this path. My concern is that for volumes with an access type of mount, if the SP umount volumes at target_path successfully but forgot to delete mountpoint, the CO can take over the cleanup task and delete the mountpoint? Does this behavior make sense, or it is forbidden for the CO to do that?

Currently, there are two places where the mountpoint will be deleted in kubelet:

1. the csi volume plugin will delete the mountpoint when the volume is unpublished. This behavior is deprecated and leaves a TODO item to remove it.
2. when kubelet clean up orphaned pod directories, it will scan the pod volume directories and delete all empty directories in the pod volume directories immediately. https://github.com/carlory/kubernetes/blob/fbc9274e834015ec4574752d34fba358d6c23481/pkg/kubelet/kubelet_volumes.go#L158

For target_path, if we only changes the csi volume plugin not to delete the mountpoint, the kubelet will still delete the mountpoint when the mountpoint is directory and empty. 

So it maybe not a good idea to remove the kubelet's cleanup behavior for mountpoint and it will cause some bugs. I want to confirm whether the CO's cleanup behavior for mountpoint has other risks when the mountpoint is umounted. 

If it is safe, I think we can keep the kubelet's cleanup behavior and treat it as dreprecated behavior. otherwise, we have to remove the kubelet's cleanup behavior for mountpoint.

I still hope that the csi driver has implemented the cleanup logic for mountpoint that was required by the CSI spec. 

What do you think about that `the CO is still able to cleanup the target_path/staging_path if the path is umounted but still exists`? 

/cc @dobsonj @jsafrane @bswartz

**Comment by jsafrane** [comment]
> if the SP umount volumes at target_path successfully but forgot to delete mountpoint, the CO can take over the cleanup task and delete the mountpoint? Does this behavior make sense, or it is forbidden for the CO to do that?

CO should not unmount the directory, however, if SP leaves an empty directory, I do not see any problem when CO deletes it.

> So it maybe not a good idea to remove the kubelet's cleanup behavior for mountpoint and it will cause some bugs. I want to confirm whether the CO's cleanup behavior for mountpoint has other risks when the mountpoint is umounted.

> If it is safe, I think we can keep the kubelet's cleanup behavior and treat it as dreprecated behavior. otherwise, we have to remove the kubelet's cleanup behavior for mountpoint.

I think it's safe to keep the current cleanup - it can't break anything if kubelet just removes the publish directory. As long as is it not mounted.

**Comment by carlory** [comment]
/hold cancel
/cc @jsafrane @dobsonj 
Please review again.

**Comment by jsafrane** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
