### PR TITLE
Remove unused field in test/e2e/kubectl/kubectl.go

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
After k8s-ci-robot merge pull request kubernetes#87597 from mikedanese/rctx, the E2E test cases have been deleted in kubectl.go and these variables are no longer used. Also ref: #99243
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
Nice cleanup.

/triage accepted
/priority backlog
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
