### PR TITLE
Require table converter

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
* Rather than silently defaulting storage to a name+creationTimestamp-only table converter implementation, require storage implementations to explicitly provider a converter (and allow them to easily provide the default name+creationTimestamp-only implementation if they want).
* When installing endpoints, ensure all listers implement table conversion (this catches storage implementations that wrap standard storage and forget to delegate ConvertToTable)
* Remove the kubectl e2e test added to ensure all resources added table conversions

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @smarterclayton @robscott

### CODE REVIEW

**Comment by liggitt** [comment]
```
Errors from staticcheck:
test/e2e/kubectl/kubectl.go:2125:6: func verbsContain is unused (U1000)
test/e2e/kubectl/kubectl.go:2135:6: func deleteObj is unused (U1000)
test/e2e/kubectl/kubectl.go:2143:6: func createObjValidateOutputAndCleanup is unused (U1000)
```

...

**Comment by robscott** [comment]
@liggitt I think this probably makes sense to try to get in to 1.18. If not, we'd want to get this PR into 1.18 to avoid 1.18-1.19 skew failures: https://github.com/kubernetes/kubernetes/pull/89057

**Comment by liggitt** [comment]
I'd take the PR dropping the test for 1.18. I'd like to limit non-test changes in code-freeze.

**Pull request merged**
