### PR TITLE
Show resource limits with describe

### LINKED ISSUE #9258: Kubectl describe of a pod should show resource limits on a container if specified
This is a general usability improvement.

### PR DESCRIPTION
**Pull request by jsdir**
Closes #9258

### CODE REVIEW

**Comment by erictune** [comment]
ok to test

**Comment by quinton-hoole** [comment]
@bgrant0607 @dchen1107 doe either of you have bandwidth to review?  I'm a bit snowed under right now.

**Comment by derekwaynecarr** [comment]
I can review since I requested it

**Comment by bgrant0607** [comment]
Thanks, @derekwaynecarr 

We're removing interpretContainerStatus from kubectl get pods in PR #9032. This looks at status.lastState, among other things. We should add equivalent info to describe. Please at least factor out the big switch on state, so that we could also use it to display lastState.

**Comment by derekwaynecarr** [comment]
@jsdir - The change looked good when I tried it.

```shell
Name:				nginx-7wbly
Image(s):			nginx
Node:				10.245.1.3/10.245.1.3
Labels:				run=nginx
Status:				Running
Replication Controllers:	nginx (1/1 replicas created)
Containers:
  nginx:
    Image:	nginx
    Limits:
      cpu:		250m
      memory:		6Mi
    State:		Running
      Started:		Fri, 05 Jun 2015 16:12:38 -0400
    Ready:		True
    Restart Count:	0
Conditions:
```

@bgrant0607 - We can hold on this PR until #9032 lands.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - this PR still has the big switch on state, but is an improvement on what existed previously for the end-user.  are you fine taking as is and factoring out state in a follow-on?

**Comment by bgrant0607** [comment]
Yes, I'm fine with refactoring in a separate PR

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
Re-running Shippable.

Otherwise, LGTM.

cc @davidopp for another LGTM

**Comment by davidopp** [comment]
LGTM

**Comment by mbforbes** [comment]
Shippable still hasn't started. Fingers crossed for soon...

**Pull request merged**
