### PR TITLE
Remove prometheus references from etcd version monitor

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
Part of https://github.com/kubernetes/kubernetes/issues/89267

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/89267

**Special notes for your reviewer**:
/cc @RainbowMango
/cc @serathius
**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Basically sounds good to me.
We still have a little bit more complex part that is `github.com/prometheus/client_model/go`, we can handle it by next round.

/lgtm
/approve

**Comment by dims** [comment]
thanks @zhouya0

**Comment by BenTheElder** [comment]
/approve
seems reasonable, though I'm not sure I grokked the full implications, I'll have to read that KEP thoroughly at some point.

**Comment by BenTheElder** [comment]
heh, this is what I get for circling back to a "TODO" tab, guess @dims beat me by a day :-)

**Comment by dims** [comment]
LOL @BenTheElder

**Pull request merged**
