### PR TITLE
Fixes mixed tabs and spaces in shell files

### PR DESCRIPTION
**Pull request by seemethere**
**What this PR does / why we need it**:
Fixes files that had mixed indentation

**Special notes for your reviewer**:
This doesn't change functionality but it does make the files conform to the style that is prevalently found in those files. (4 spaces / 2 spaces / Tabs)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by charrywanganthony** [comment]
Did you stumble across the problem or write a script intend to find them all?  IMHO, if it is convenient to you, write a script and find them all will be good. ^_^

**Comment by seemethere** [comment]
@charrywanganthony Just stumbled upon it. On closer inspection (or rather I just ran a script) I found two more files that have mixed indentation:

```
$ find . -type f -not -path "./vendor/*" -not -path "./.git/*" -not -name "./.*" | xargs python ~/scripts/indent_finder.py | grep mixed
./cluster/gce/delete-stranded-load-balancers.sh : mixed tab 8 space 4
./hack/e2e-internal/e2e-status.sh : mixed tab 8 space 4
```

Strangely enough it doesn't find the original file I had modified, even on the master branch.

Script used can be found here: http://www.freehackers.org/Indent_Finder

**Comment by seemethere** [comment]
Updated original PR text to reflect more changes

**Comment by zmerlynn** [comment]
This PR produces could produce a lot of noise / conflicts (in fact, you got hit with needs-rebase almost immediately), but doesn't enforce what it's trying to fix. Please add a verifier if you think this should be enforced - otherwise it'll just bitrot and we'll have to do this again.

**Comment by seemethere** [comment]
@zmerlynn I made a mixed indentation linter here: https://github.com/seemethere/misto,

Can you point me in the direction of where to place that linter so that it'll work on PR's?

**Pull request closed without merging**
