### PR TITLE
Optimize writeline and writeBytesLine in proxier.go

### PR DESCRIPTION
**Pull request by JornShen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

In proxier.go  of iptables and ipvs, there are same func `writeLine`  and `writeBytesLine` 
migrate it to public util pkg and add UT.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Might take a look at https://github.com/kubernetes/kubernetes/pull/97552 and see if that works out as a performance win.

/lgtm
/approve

**Comment by JornShen** [comment]
> Might take a look at #97552 and see if that works out as a performance win.
> 

Thanks for pointing out !
I will give it a try later.

@thockin

**Pull request merged**
