### PR TITLE
cadvisor bump: various fixes & improvements to prometheus metrics

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Could someone please explain why this is failing? `hack/verify-godeps.sh master` is failing on what looks like non-go files, test files in the cadvisor repo. Should I not commit them, even though `godep update` added them to vendored godeps?

**Comment by vishh** [comment]
@jimmidyson: I don't see why test files are needed. I'd vote for removing them.

**Comment by vishh** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
@vishh Hmm they're pulled in when going a `godep update` so it's a bit annoying having to go in & remove files after that. Of course I can remove them but it seems like an extra step with no value I can think of.

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra @smarterclayton

**Comment by vishh** [comment]
Hmm.. I agree. Since it is a general issue, we can clean up all the test
files in one shot and not complicate this PR.

**Comment by vishh** [comment]
@jimmidyson: I can make a cadvisor tag for this update.

**Comment by jimmidyson** [comment]
@vishh Ah that would be great. I'd personally be tempted to just leave in test files & update validation script instead.

**Comment by vishh** [comment]
@jimmidyson: Can we close this PR in favor of #14556 ?

**Comment by jimmidyson** [comment]
Yes. Forgot all about this one.

**Pull request closed without merging**
