### PR TITLE
add GinkgoRecover to a go routine to unblock upgrade tests from repor…

### PR DESCRIPTION
**Pull request by mbohlool**
…ting test results

### CODE REVIEW

**Comment by abgworrall** [comment]
/label release-note-none
/label cherrypick-approved
[restore dawn's approval]

**Comment by abgworrall** [comment]
@wojtek-t ...

We need this fix merged into 1.7, so that we can see results from the 1.7 -> 1.8 upgrade tests. Without those results, we can't really release code freeze on 1.8, which has already slipped one day, so this is urgent. Submit Queue appears busted, so we're asking for a manual merge. WDYT ?

**Comment by wojtek-t** [comment]
Merging manually.

**Comment by lavalamp** [comment]
@fejta I am not sure why the submit queue has not merged this, and I don't have time today to figure it out, and I also am not sure who owns the submit queue, so I am merging this manually. Or I would, I guess @wojtek-t beat me to it.

**Pull request merged**
