### PR TITLE
Add version flag to e2e.test

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Should be easy to find the version of the e2e.test binary without having to run the tests (and looking at the logs)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks @dims 
/lgtm

**Comment by johnSchnake** [comment]
Tried locally:

```
$ bazel build //test/e2e:e2e.test_binary
Starting local Bazel server and connecting to it...
...
...
Target //test/e2e:gen_e2e.test up-to-date:
  bazel-bin/test/e2e/e2e.test
...

$ bazel-bin/test/e2e/e2e.test --version
v1.18.0-alpha.2.1551+8f3dfea11fd80c-dirty

$ git describe
v1.18.0-alpha.2-1551-g8f3dfea11fd
```

/lgtm

**Pull request merged**
