### PR TITLE
add changelog for the feature branch

### PR DESCRIPTION
**Pull request by lavalamp**
**What this PR does / why we need it**:

Implement suggestion from sync meeting from a while ago.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/assign @jennybuckley 

cc @apelisse @seans3

**Comment by jennybuckley** [comment]
Not that it matters very much but we should probably fix this to be readable in .md

https://github.com/kubernetes/kubernetes/blob/768d734cde2833f65f37f2cc2c0a8cfd01c84a30/CHANGELOG-FEATURE.md

**Comment by lavalamp** [comment]
Oh yes that's very bad, weird, I put it in an MD viewer before sending the
PR.

**Comment by lavalamp** [comment]
Please take a look at https://github.com/kubernetes/kubernetes/pull/63106

**Pull request merged**
