### PR TITLE
ginkgo-e2e: Adds ginkgo focus and dryRun options

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig testing
/kind feature

#### What this PR does / why we need it:

This will allow us to run tests matching a specific regex when running ``ginkgo-e2e.sh``. The ``dryRun`` option will allow us to make sure we're matching the right tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by spiffxp** [comment]
Out of curiosity, what's the entrypoint you're working with here / use-case you're trying to solve for?

The script is already setup to allow passing along flags directly to the e2e binary vs. plumbing them through env vars, e.g. I'm pretty sure `hack/ginkgo-e2e.sh --ginkgo.dryRun=true` would accomplish what you're trying to do with `GINKGO_DRYRUN=true hack/ginkgo-e2e.sh`

https://github.com/kubernetes/kubernetes/blob/e35dff68afa694af575495f6dd0c4ec36a723f4b/hack/ginkgo-e2e.sh#L199

**Comment by spiffxp** [comment]
To rephrase https://github.com/kubernetes/kubernetes/pull/105269#issuecomment-928426039 slightly

I'd rather not approve until I understand what problem this is trying to solve that can't be solved by the existing mechanisms we have in place

**Comment by claudiubelu** [comment]
> 
> 
> Out of curiosity, what's the entrypoint you're working with here / use-case you're trying to solve for?
> 
> The script is already setup to allow passing along flags directly to the e2e binary vs. plumbing them through env vars, e.g. I'm pretty sure `hack/ginkgo-e2e.sh --ginkgo.dryRun=true` would accomplish what you're trying to do with `GINKGO_DRYRUN=true hack/ginkgo-e2e.sh`
> 
> https://github.com/kubernetes/kubernetes/blob/e35dff68afa694af575495f6dd0c4ec36a723f4b/hack/ginkgo-e2e.sh#L199

Indeed, that also works.

/close

**Pull request closed without merging**
