### PR TITLE
kubectl: fix example for patch command

### PR DESCRIPTION
**Pull request by tobstarr**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

[Analytics]()

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@tobstarr thanks a lot for the PR. The docs are automatically generated. Could you change the line in pkg/kubectl/cmd/patch.go and then run hack/update-all.sh?

Also, could you follow the googlebot's comment to sign the CLA? https://github.com/kubernetes/kubernetes/pull/25746#issuecomment-219746825

**Comment by tobstarr** [comment]
I signed it!

**Comment by caesarxuchao** [comment]
@tobstarr thanks a lot for the PR. The docs are automatically generated. Could you change the line in pkg/kubectl/cmd/patch.go and then run hack/update-all.sh?

If you don't have time, I can take this PR over :)

**Comment by caesarxuchao** [comment]
Close in favor of #26581.

**Pull request closed without merging**
