### PR TITLE
DRA: rename pkg/cm/dra/plugin files

### LINKED ISSUE #125924: DRA: rename pkg/cm/dra/plugin files
### What would you like to be added?

https://github.com/kubernetes/kubernetes/pull/125163#discussion_r1665552886:
- plugin.go -> registration.go
- client.go -> plugin.go

The PR above moved everything related to `Plugin` into `client.go` because that was where most of the code already was, but didn't renamed the files to avoid a larger diff and merge conflicts.

Once https://github.com/kubernetes/kubernetes/pull/125488 is merged, we can do the renaming.

### Why is this needed?

Code clarity.

/sig node

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Code clarity.

#### Which issue(s) this PR fixes:

Fixes #125924

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/cc @pohly 

Can we merge it as soon as possible to avoid getting new conflicts?

**Review by pohly — APPROVED** [review]
/lgtm
/approve

"git diff" doesn't show it, but the files really were renamed whole-sale:
```
$ diff -c <(git show FETCH_HEAD~~:pkg/kubelet/cm/dra/plugin/client.go) <(git show FETCH_HEAD~:pkg/kubelet/cm/dra/plugin/plugin.go) | wc -l
0
$ diff -c <(git show FETCH_HEAD~~:pkg/kubelet/cm/dra/plugin/plugin.go) <(git show FETCH_HEAD~:pkg/kubelet/cm/dra/plugin/registration.go) | wc -l
0
```

**Comment by carlory** [comment]
> Rebase once more? Sorry.

will do

**Comment by carlory** [comment]
```
(base) ➜  kubernetes git:(fix-125924-1) diff -c <(git show FETCH_HEAD~~:pkg/kubelet/cm/dra/plugin/client.go) <(git show FETCH_HEAD~:pkg/kubelet/cm/dra/plugin/plugin.go) | wc -l
       0
(base) ➜  kubernetes git:(fix-125924-1) diff -c <(git show FETCH_HEAD~~:pkg/kubelet/cm/dra/plugin/plugin.go) <(git show FETCH_HEAD~:pkg/kubelet/cm/dra/plugin/registration.go) | wc -l
       0
(base) ➜  kubernetes git:(fix-125924-1)
```

**Comment by pohly** [comment]
/lgtm
/priority important-soon

Let's merge this right away to avoid further conflicts.

**Pull request merged**
