### PR TITLE
Bump logexporter version to v20200227-da16e1b17

### PR DESCRIPTION
**Pull request by oxddr**
/kind feature
/release-note-none
/sig scalability
/priority important-soon

### CODE REVIEW

**Comment by mm4tt** [comment]
/lgtm
/approve

/hold
Please verify that logexpoter worked in presubmits

**Comment by oxddr** [comment]
/hold cancel

logexporter worked fine https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88653/pull-kubernetes-e2e-gce-100-performance/1235224572588986368/artifacts/e2e-88653-95a39-minion-group-7s2j/logexporter-qxvpg.log

The error message at the beginning of each line is being fixed with https://github.com/kubernetes/test-infra/pull/16629

**Pull request merged**
