### PR TITLE
e2e: fix deployment non-unique env vars to avoid SSA error

### LINKED ISSUE #88182: "SHOULD NOT HAPPEN" should not happen
Seen in the KIND e2e test: 

```
2020-02-14T23:57:17.149523077Z stderr F E0214 23:57:17.145040       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
2020-02-14T23:57:17.166960149Z stderr F E0214 23:57:17.166281       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
2020-02-14T23:57:17.182220465Z stderr F E0214 23:57:17.181242       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
```

a) maybe we shouldn't log this more than 1x per second or something?
b) maybe the error could make it clearer that the problem is the user's data?
c) maybe we could fix the test triggering this?

/sig api-machinery
/wg apply

Logs that I saw this in: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88177/pull-kubernetes-e2e-kind/1228463295606820865/artifacts/logs/kind-control-plane/pods/kube-system_kube-apiserver-kind-control-plane_08a7fd62a1b3bb0f98714e7546afd587/kube-apiserver/0.log

### PR DESCRIPTION
**Pull request by sttts**
/kind bug

Fixes #88182

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/milestone v1.20

**Comment by lavalamp** [comment]
@apelisse do we need to do anything else here?

**Comment by apelisse** [comment]
We're aware this is an issue, we're tracking and planning on solving this.

**Pull request merged**
