### PR TITLE
Link to cronjob schedule syntax

### PR DESCRIPTION
**Pull request by sftim**
**What type of PR is this?**

/kind documentation
/sig cli

**What this PR does / why we need it**:

Now that Kubernetes documentation covers the [syntax for CronJob schedules](https://docs.k8s.io/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax), link to that page.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
I might have done the automated generation wrong; it's my first time on this, and I had to piece together the docs on what to do from different places. I hope Prow & friends can let me know if there's a mismatch.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
After reading https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#what-parts-of-a-pr-are-api-changes I think this _doesn't_ require API review, but I'm not 100% certain.

**Comment by dougsland** [comment]
Hello @sftim, please correct me if I am wrong, the wikipedia seems more generic page about cron. 
The page https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/  seems a similar goal.

**Comment by sftim** [comment]
https://docs.k8s.io/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax explains the specific format of Cron-like syntax that CronJob uses. This is more relevant than the Wikipedia page, which can only explain things more generally.

**Comment by dougsland** [comment]
> https://docs.k8s.io/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax explains the specific format of Cron-like
> syntax that CronJob uses. This is more relevant than the Wikipedia page, which can only explain things more generally.

Sure, I was double checking as now we are very specific instead of generic. +1 
/lgtm

**Comment by sftim** [comment]
Think this is ready for approval.

/assign @erictune

Please let me know if it needs a rebase, or other changes.

**Review by pacoxu — APPROVED** [review]

**Comment by dougsland** [comment]
@sftim will require rebase

**Comment by sftim** [comment]
Hi @pacoxu - would you be willing to review again? I took out the part of the change that update CronJob v2alpha1.

**Review by pacoxu — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
/assign @erictune
for approval

**Comment by sftim** [comment]
(rebased)

**Comment by pacoxu** [comment]
The verify ci failed and asked to `hack/update-openapi-spec.sh`.

**Review by soltysh — COMMENTED** [review]
The change looks good, but can you please apply that also in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/batch/v1/types.go as well. Also pls fix the verify failures.

**Pull request closed without merging**
