### PR TITLE
Change node e2e cri-validation configs

### PR DESCRIPTION
**Pull request by yujuhong**
Copy the configs to a new directory to test non-cri implementation. We can
remove the original directory after the dependent PRs are merged.

### CODE REVIEW

**Comment by yujuhong** [comment]
Depends on #41378.
Related to https://github.com/kubernetes/test-infra/pull/1897

**Comment by Random-Liu** [comment]
Can we change the directory name? It will be less misleading.

**Comment by yujuhong** [comment]
> Can we change the directory name? It will be less misleading.

Change of direction -- I will copy the configs to a different directory (non-cri_validation) for the time being, so I don't have to coordinate the test-infra changes with this one.

**Comment by yujuhong** [comment]
Rebased. Ready for review.

**Comment by Random-Liu** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot cross build this

**Comment by yujuhong** [comment]
@dchen1107 could you approve this?

**Comment by yujuhong** [comment]
Marking p1 to restore test coverage of non-cri builds.

**Comment by ixdy** [comment]
/approve

for `hack/`

**Comment by dchen1107** [comment]
lgtm

**Pull request merged**
