### PR TITLE
Promote metrics for VAP and CRD validation rules to beta.

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Since the feature CRD validation rules and ValidatingAdmissionPolicy have both been promoted to Stable, we would love to promote the related metrics to Beta stability level. Thanks

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Promoted the metrics for both VAP and CRD validation rules to beta.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/sig instrumentation
/assign @richabanker 
if you have time :) Thank you!

**Review by richabanker — APPROVED** [review]
/lgtm

**Comment by cici37** [comment]
/assign @logicalhan 
For approval. Thank you!

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
