### PR TITLE
fix golint issues for pkg/volume/git_repo

### PR DESCRIPTION
**Pull request by leakingtapan**
**What this PR does / why we need it**:
Fixes goling issue for pkg/volume/git_repo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Ref #68026

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by idealhack** [comment]
/ok-to-test

@leakingtapan Please remove `Fixes #68026` as it will close that issue, otherwise this is LGTM

**Comment by leakingtapan** [comment]
@idealhack thx for the remind. updates the description to use ref

**Comment by leakingtapan** [comment]
/assign @vishh @gnufied @saad-ali 
could you approve the PR? thx

**Comment by oomichi** [comment]
/lgtm cancel

Could you rebase this on the latest source?

**Comment by leakingtapan** [comment]
@oomichi Done

**Comment by idealhack** [comment]
/lgtm

the change is easy to review, but it needs too many approvers

**Comment by oomichi** [comment]
@leakingtapan Thanks for updating,

/lgtm

**Comment by spiffxp** [comment]
needs rebase

**Pull request closed without merging**
