### PR TITLE
fix golint errors on master for 1.6

### PR DESCRIPTION
**Pull request by jessfraz**
Needs to be merged before https://github.com/kubernetes/test-infra/pull/1299 is merged

updates https://github.com/kubernetes/kubernetes/issues/37254

### CODE REVIEW

**Comment by rmmh** [comment]
The error message was "error strings should not be capitalized or end with punctuation or a newline" -- is the capitalization not an issue too?

**Comment by jessfraz** [comment]
it seems to be fine when testing locally

**Comment by rmmh** [comment]
oh, they just made the error message needlessly generic

**Comment by jessfraz** [comment]
"generic" [insert go generics joke here]

**Comment by jessfraz** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
