### PR TITLE
Go SSH e2e tests

### PR DESCRIPTION
**Pull request by mbforbes**
This PR:
- adds a Go SSH library to our godeps
- implements a simple utility for doing SSH's in e2e tests
- implements a simple e2e test that SSH's to all nodes

This will allow us to:
- rip out the last shell test, meaning our e2e tests will all be in Go
- write node reboot tests (in Go)
- write salt idempotency tests (in Go) (for upgrades)

### CODE REVIEW

**Comment by roberthbailey** [comment]
@mbforbes - this is awesome! I'm really looking forward to getting rid of that last pesky shell test. :)

**Comment by satnam6502** [comment]
We should all come out of our shells. +1.

**Comment by mbforbes** [comment]
Thanks for the comments everyone—PTAL.

**Comment by mbforbes** [comment]
I've removed my workaround for the bug #7412 as it seemed the most expedient way to get this merged. This resolves the type problems raised. PTAL @roberthbailey (reviewer) and @zmerlynn (requested the exit code vs error separation).

**Comment by mbforbes** [comment]
I addressed the comments; PTAL. I also added an additional SSH test for a nonexistent host. This, and some of the e2e SSH test cases, are more unit tests than e2e tests. If you'd like me to be pedantic and split this out into a `util_test.go` file I'm willing to—I didn't now because of time / lack of other unit tests for e2e test utils.

**Comment by roberthbailey** [comment]
LGTM. Will merge on green.

**Pull request merged**
