### PR TITLE
Conformance Test for DNS

### LINKED ISSUE #9107: Make DNS required (update docs, add conformance test)
This issue is a follow on from the discussion in PR #5284 by @piosz where folks like @pires and @eparis @nzwulfin  and maybe @derekwaynecarr complain about changing the key guestbook example to use DNS which makes it a nicer example for Kubernetes deployments that have a DNS add-on but breaks it for other clusters that don't. A very good point was made: the key example that most people try out should work on bare Kubernetes without the need to assume any add-ons services.

Although we can imagine some post 1.0 fixes (e.g. absorb DNS functionality into core Kubernetes @thockin ) I think it is very important to get our examples and documentation in very good shape for the 1.0 release so that everyone has a very good out of the box experience with the key guestbook example for any Kubernetes deployment that we explicitly support.

I propose the following approach for 1.0:
* Produce a variety of guestbook examples which make different assumptions about the type of the Kubernetes deployment.
* Have a `guestbook-bare` example that works without DNS.
* Have a `guestbook-dns` example that works with DNS.
* Have other `guestbook-XXX` examples that work with other Kubernetes deployments that can provide an alternative to our DNS add-on to achieve the same effect.
* Produce a clear matrix in our documentation that explains which example should be run depending on your deployment.
* Make clear at the beginning of the `README.md` for each of the examples the deployment that is expected.
* Perhaps modify the examples to make sure the pre-requisites are available before running e.g. in a Makefile as a pre-check?

@RichieEscarez @bgrant0607

### PR DESCRIPTION
**Pull request by ArtfulCoder**
Closes #9107

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
#9107

**Comment by thockin** [comment]
@goltermann @bgrant0607 we can merge this when tests pass.

**Comment by ArtfulCoder** [comment]
Thanks Phil for the manual merge :)

**Comment by bgrant0607** [comment]
Adding cherrypick-candidate

**Pull request merged**
