### PR TITLE
Add labels for SIG storage components

### PR DESCRIPTION
**Pull request by ehashman**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Automatically adds sig-storage label to these components on review

**Which issue(s) this PR fixes**:

I won't have to manually tag these when they get stuck in the ether of `do-not-merge/needs-sig` :)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/approve

Thanks!

**Comment by ehashman** [comment]
Gentle ping, need an approver from:

 - @jingxu97
  - @saad-ali
  - @jsafrane

**Pull request merged**
