### PR TITLE
tests: Adds configurable registry for etcd image

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test
/area conformance

/sig windows
/sig testing

**What this PR does / why we need it**:

The image ``quay.io/coreos/etcd:v3.3.10`` does not have Windows
support and Windows Containers cannot be spawned using it.

Makes the etcd image's registry configurable, so the tests can be
configured to use a registry which has Windows support.

**Which issue(s) this PR fixes**:

Related issue: #60487

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
This seems pretty straightforward for me.

/lgtm

**Comment by spiffxp** [comment]
/approve
/hold
I'm good with this, I would like to double-check with someone from test/conformance/testdata/OWNERS

**Pull request merged**
