### PR TITLE
Try to diagnose v1.1 e2e service fail (WIP)

### PR DESCRIPTION
**Pull request by thockin**
Investigate #19729

### CODE REVIEW

**Comment by ixdy** [comment]
cc @ihmccreery

**Comment by ixdy** [comment]
What is the status/intent for this PR?

**Comment by thockin** [comment]
I will revisit soon

**Comment by ihmccreery** [comment]
@thockin #19729 is no longer an issue; something somewhere along the line resolved it.

**Comment by fejta** [comment]
@thockin Mind if I ask you to either a) make some progress on this PR this week or else b) close it out until it is ready for review again? Thanks!

**Comment by zmerlynn** [comment]
We're not going to ship another 1.1 release at this point. I'm closing this so it's not going to clutter any queries.

**Pull request closed without merging**
