### PR TITLE
Support volume mounts with kubectl debug

### LINKED ISSUE #114184: VolumeMount support in ephemeral containers with kubectl debug
### What would you like to be added?

At present, I cannot attach an ephemeral container with a volume mount by using "kubectl debug".
I would prefer to have some way to create an ephemeral container with volume mount using kubectl debug.
It could be something similar to [patch command](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#alternate-forms-of-the-kubectl-patch-command)

I don't know if it's already possible to do it.[Blog](https://iximiuz.com/en/posts/kubernetes-ephemeral-containers/) indicates one way of doing it with API call, but kubectl debug would be much easier.

### Why is this needed?

Real world use case would be - 
Use case - I have a statefulset with a PVC where I store all the data related to the application. When the app crashes and it needs to be investigated, it is only possible to share net and pid namespace. If I want to investigate the file system it's just not possible as containers use different mount space.
By using the same volume mount as the crashing container of the pod, it is possible to check the data present in the PVC.  There might be security concerns also with this , but it needs to be explored

### PR DESCRIPTION
**Pull request by AverageMarcus**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds the ability to mount volumes into ephemeral containers when using `kubectl debug`. This allows for fixing / debugging issues in pods related to data stored in PVs. For example, fixing issues with corrupt Redis data.

#### Which issue(s) this PR fixes:

Fixes #114184

#### Does this PR introduce a user-facing change?

```release-note
Adds a new `--volume` flag to `kubectl debug` to support mounting volumes into ephemeral containers
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ardaguclu** [comment]
@AverageMarcus thanks for working on this and spending effort. 

There are numerous different kind of flag requests with respect to kubectl debug and we are very reluctant to add new one(for example, you are proposing for volumemounts, someone request securitycontext, etc.). Because the command might become unmanageable due to lots of flags.

However, I fully understand the request to manage volumemounts or other resources. In order to provide a solution for this, we have decided to implement custom profiles in kubectl debug in addition to that static profiles which can be used to dynamically change the fields according to your needs(This is the KEP https://github.com/kubernetes/enhancements/issues/1441, feel free to drop your comments). Thanks.

**Comment by AverageMarcus** [comment]
@ardaguclu maybe I'm missing it but I don't actually see where custom profiles are describe to handle dynamic use cases, just a couple comments that it'd be good. Is there another KEP open somewhere to cover them? The KEP linked to has this line which seems to disagree with the idea to implement custom profiles:

> It might be possible to support user-configurable profiles, but it's not a goal of this KEP, and we have no plans to implement it.

**Comment by ardaguclu** [comment]
Sorry for not being explicit, that's the comment I'm referring to https://github.com/kubernetes/enhancements/issues/1441#issuecomment-1484966305. I was/am planning to work on this, but unfortunately I couldn't have found free slots yet.

**Comment by AverageMarcus** [comment]
No worries! I just wanted to be sure I wasn't missing something. :) 

When you do start work on it I'd be happy to comment / review if you like. I agree the `kubectl debug` is quite noisy with the args (I think mixing the three types together might have been a mistake in hindsight) and I've love to see it improved. It's such a useful tool! 😁

**Comment by cshiv** [comment]
Hello @ardaguclu I am not clear how profiles can help in mounting a volume to a container, Can you please provide more details.
I am curious on some of the possibilities with ephemeral containers like -
1. Attaching a subset of volumes as mount to containers
2. Defining path to be mounted for the volume.

**Pull request closed without merging**
