### PR TITLE
Update kubectl-cluster-info.md

### PR DESCRIPTION
**Pull request by aronchick**
The hyphen has been removed from the command.

### CODE REVIEW

**Comment by lavalamp** [comment]
The document you changed is auto-generated. Please change the source of the text :)

**Comment by aronchick** [comment]
I signed it!

**Comment by yujuhong** [comment]
@aronchick, thanks for the PR! Looking at #6118, I think we are deprecating `clusterinfo` in favor of `cluster-info`. Both commands should work for the meantime until the transition period is over, so the auto-generated files (as @lavalamp pointed out) `kubectl-cluster-info.md` and `kubectl-clusterinfo.md` co-exist. There is no need to change the files.

On the other hand, `kubectl cluster-info` doesn't seem to be working as expected. I will file an issue for that.

**Comment by bgrant0607** [comment]
Yes, the hyphenated forms are now preferred, and, as was pointed out, these files are auto-generated.

**Pull request closed without merging**
