### PR TITLE
Automated cherry pick of #107084: Update CHANGELOG to add missing release notes.

### PR DESCRIPTION
**Pull request by humblec**
Cherry pick of #107084 on release-1.23.

#107084: Update CHANGELOG to add missing release notes.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by humblec** [comment]
@cici37 @puerco the cherry-pick labels for `do-no-merge-release-note-required` labels are added as the parent PR dont have the `release note`.  Please take a look at this .

**Comment by humblec** [comment]
@cici37 @puerco @karenhchu can you please approve this cherrypick to release note please ? Thanks in advance!

**Comment by humblec** [comment]
Cc @cpanato

**Comment by puerco** [comment]
Thanks a lot @humblec !
/lgtm
/approve

**Pull request merged**
