### PR TITLE
Leaderelection racefix

### PR DESCRIPTION
**Pull request by hdonnay**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This fixes a race in both the `leaderelection` and `resourcelock` packages that showed up when run under the race detector with sufficiently short timeouts/leases configured.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i though for a minute that this PR is by @deads2k  :)
thank you @hdonnay but we are no longer accepting patches for 1.10.
1.10 is unsupported at this point.

is this fixed in 1.11 and newer versions?

/hold

**Comment by hdonnay** [comment]
Ah, okay. The project I'm working on is using the v1.10 go-client, so I fixed it on that branch.

It looks like the patches apply cleanly to v1.11, so I've rebased the commits and the PR.

**Comment by liggitt** [comment]
thanks for the PR, but no more 1.11.x releases are being cut. v1.11.10 was the final 1.11.x release.

/close

**Pull request closed without merging**
