### PR TITLE
Add some additional validation for object keys.

### PR DESCRIPTION
**Pull request by brendandburns**
@lavalamp @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
Name is the last segment, so it could end with `/..`, right?

**Comment by lavalamp** [comment]
LGTM

**Comment by brendandburns** [comment]
@liggitt yes, that's possible, but I think that other validation will catch it (e.g. we'll try to overwrite a directory with an object.

**Comment by liggitt** [comment]
As a minimally disruptive back port, this LGTM

**Comment by lavalamp** [comment]
... a test would be nice? I applied the LGTM label but the bot is going slow, so maybe you can add a test?

**Comment by brendandburns** [comment]
@lavalamp tests added.

**Comment by liggitt** [comment]
Thanks

**Comment by lavalamp** [comment]
LGTM

**Comment by ihmccreery** [comment]
Bypassing Shippable.  @jlowdermilk will run unit & integration tests manually.

**Pull request merged**
