### PR TITLE
fix the mistake in the release note

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug
/kind documentation

#### What this PR does / why we need it:

Sorry. The description for two metrics is completely wrong. 😓 🙏 (They're switched with each other)

https://github.com/kubernetes/kubernetes/pull/116326

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
@kubernetes/sig-release-leads Could anyone check this? 🙏

**Review by sanchita-07 — APPROVED** [review]
/lgtm
/approve

**Review by harshanarayana — COMMENTED** [review]
/lgtm 
/approve

**Comment by sanposhiho** [comment]
@harshanarayana Could you `/approve` again? Seems haven't worked.

**Pull request merged**
