### PR TITLE
Support for PodDisruptionBudget in Kubectl

### PR DESCRIPTION
**Pull request by mwielgus**
Based on:

https://github.com/kubernetes/kubernetes/pull/35287

cc: @davidopp @soltysh @wojtek-t

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36495)

### CODE REVIEW

**Comment by soltysh** [comment]
@k8s-bot unit test this flake #36351

**Comment by soltysh** [comment]
LGTM

**Comment by saad-ali** [comment]
Removing milestone and marking `do-not-merge` until we have had a chance to review this feature's post-code freeze exception (https://groups.google.com/forum/#!topic/kubernetes-milestone-burndown/RaiyVVkbKaU).

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by davidopp** [comment]
LGTM

Personally I would have put current (and maybe total) in "get" as well as describe, but I guess this is OK.

**Comment by soltysh** [comment]
> Personally I would have put current (and maybe total) in "get" as well as describe, but I guess this is OK.

This can be easily added in the next release. At this point we should merge this in as is.

**Comment by saad-ali** [comment]
> Removing milestone and marking `do-not-merge` until we have had a chance to review this feature's post-code freeze exception (https://groups.google.com/forum/#!topic/kubernetes-milestone-burndown/RaiyVVkbKaU).

The request for exception to 1.5 release code freeze for the "PodDisruptionBudget" feature has been approved. Adding 1.5 milestone and removing `do-not-merge` label.

**Pull request merged**
