### PR TITLE
Handle MarkFlagFilename error

### PR DESCRIPTION
**Pull request by yuzhiquan**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Handle MarkFlagFilename error
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/triage accepted
/priority important-longterm

### CODE REVIEW

**Comment by JornShen** [comment]
same MR as  https://github.com/kubernetes/kubernetes/pull/77587
And this is comment  of @danwinship  before
https://github.com/kubernetes/kubernetes/pull/77587#discussion_r313589829

**Comment by yuzhiquan** [comment]
> same MR as #77587
> And this is comment of @danwinship before
> [#77587 (comment)](https://github.com/kubernetes/kubernetes/pull/77587#discussion_r313589829)

Thanks,
just an read code pr.

**Pull request closed without merging**
