### PR TITLE
UT address already in use error

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
image
Locate the problem by looking at the code ，I found that this method (src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/testserver/test_server.go:36) has problems when used concurrently,And in this method also has a note to remind ,as this _It is possible but unlikely that someone else will bind this port before we get a chance to use it._

This test case is unstable, and this test case often fails when we run ci
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
could you Use git rebase to reapply your commits ?

**Comment by muyangren2** [comment]
> 

i will do it right now，thanks

**Pull request closed without merging**
