### PR TITLE
Revert "Merge pull request #90942 from ii/ii-create-pod%2Bpodstatus-resource-lifecycle-test"

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit 8e5c02255cc62c504cb6e5ab8ded9df966ad9891 in https://github.com/kubernetes/kubernetes/pull/90942

Newly introduced test is flaking, see:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-ubuntu-containerd/1286493826562658304
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-ubuntu-containerd/1286474574245924867
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286474574245924868
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286412665119313926

And reverts 8a3fc2d7e2043bc980bb5301d2f4292020f1a2dd in #92589

Newly introduced test is flaking, see:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286504904986202114
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286501878984609792
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286495839270735874
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286401342444670980
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286392657853026304
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1286377181127118850

/milestone v1.19
/priority critical-urgent

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/ci-signal

**Comment by BenTheElder** [comment]
Should find some time to write an updated e2e writing guide and include something like "please `/test all` N times and watch for flakes of your new test" 🤔

**Comment by liggitt** [comment]
cc @spiffxp @Riaankl

**Pull request merged**
