### PR TITLE
Fix api reference generation script on os x.

### PR DESCRIPTION
**Pull request by brendandburns**
@nikhiljindal @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Thanks, @brendandburns. FYI, the reason I added the `-u` is because without it, the output will be owned by root, and the copy here https://github.com/kubernetes/kubernetes/pull/18043/files#diff-8fad002bbed1978389dea43230dff5efR88 will fail. The change is good if it works in OSX, I don't have an environment to test it though.

**Comment by brendandburns** [comment]
this works on my os x machine.

**Comment by brendandburns** [comment]
self-LGTM because this is broken @ HEAD.

**Pull request merged**
