### PR TITLE
replace locking map with a struct named nodeRoutesStatuses

### PR DESCRIPTION
**Pull request by wccsama**
**What type of PR is this?**
```
/kind cleanup
```
**What this PR does / why we need it**:
```
Packaging locking map into a struct is more concise and reusable.
```
**Which issue(s) this PR fixes**:

```
NONE
```
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
Hi @wccsama! Thanks for the PR, I had a similar one open a few months back https://github.com/kubernetes/kubernetes/pull/80109 - I agree the locking in the routes controller can be cleaned up a bit. We should coordinate and try to get the best of both PRs together.

**Comment by wccsama** [comment]
> Hi @wccsama! Thanks for the PR, I had a similar one open a few months back #80109 - I agree the locking in the routes controller can be cleaned up a bit. We should coordinate and try to get the best of both PRs together.

Yes, should I close  this pr and wait for your pr merged? After that, I can refactor the struct to this 
"routes map[types.NodeName][]PodCidrInfo" and PodCidrInfo like "cidr string 、 routeExist bool"

**Pull request closed without merging**
