### PR TITLE
Update kube-dns to 1.14.6

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Update kube-dns to version 1.14.6

* Logging cleanups
* Updates kube-dns to use client-go 3
* Updates containers to use alpine as the base image on all platforms
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/assign @jbeda 
for kubeadm approval

**Comment by cblecker** [comment]
@bowei should https://github.com/kubernetes/kubernetes/commit/90c1a1e8b38987705bc21d14eb24f3bb20911b25 be updated too?

**Comment by cblecker** [comment]
Looks like the failures are legitimate, and the DNS pod isn't coming up

**Pull request closed without merging**
