### PR TITLE
[Refactor] Make QoS naming consistent across the codebase

### PR DESCRIPTION
**Pull request by dubstack**
@derekwaynecarr @vishh PTAL. Can one of you please attach a LGTM.

### CODE REVIEW

**Comment by dubstack** [comment]
@k8s-bot e2e test this issue #28076

**Comment by dubstack** [comment]
@k8s-bot unit test this issue #28076

**Comment by dubstack** [comment]
@k8s-bot unit test this issue: #28076

**Comment by dubstack** [comment]
@k8s-bot unit test this issue: #28076

**Comment by derekwaynecarr** [comment]
Thanks for the follow-up.

**Pull request merged**
