### PR TITLE
Update fluentd to 1.4.0

### PR DESCRIPTION
**Pull request by ialidzhikov**
Signed-off-by: ialidzhikov <i.alidjikov@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:
Update fluentd to 1.4.0 and update gems to latest versions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by monotek** [comment]
Did you already tested it?
If so, in which environment?

**Comment by ialidzhikov** [comment]
@monotek , I successfully validated the image from this PR in our logging stack in [gardener/gardener](https://github.com/gardener/gardener).

**Review by monotek — CHANGES_REQUESTED** [review]
You forgot to raise the image version in: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Makefile#L19

I would go to 2.5.0.

The new image tag has to be set in the daemonset too: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml

**Comment by ialidzhikov** [comment]
Nice catch, thank you.

**Comment by ialidzhikov** [comment]
Updated `fluent-plugin-elasticsearch` from 3.3.1 to 3.3.2 in order to include the following fix [uken/fluent-plugin-elasticsearch#560](https://github.com/uken/fluent-plugin-elasticsearch/pull/560). 

@monotek is there anything blocking the merge/new image creation?

**Review by monotek — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Updated fluent-plugin-elasticsearch from 3.3.2 to 3.3.3 in order to include the following improvement uken/fluent-plugin-elasticsearch#562.

**Review by monotek — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@coffeepac , @piosz , any feedback?

**Comment by coffeepac** [comment]
looks fine.  I'll push the images in a bit then approve the PR.

Thanks for your patience!

**Comment by coffeepac** [comment]
the base debian image is actually not okay.  it has a plethora of security violations.  I've also tried the non-slim version of debian and its actually worse.  

however, this is better than the the current version so I'll approve it and follow up with a PR to swap out the base image for something else.

**Comment by ialidzhikov** [comment]
Thank you!

**Pull request merged**
