### PR TITLE
Federation apiobject replicaset

### PR DESCRIPTION
**Pull request by jianhuiz**
add subreplicase (structure is the same as replicaset)t api object and registry
generate subreplicaset client
#19313 #23653, #23269, this requires #23847

@nikhiljindal @quinton-hoole, @deepak-vij, @XiaoningDing, @alfred-huangjian @mfanjie @huangyuqi @colhom

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23998)

### CODE REVIEW

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Will look at this when https://github.com/kubernetes/kubernetes/pull/23847 is done.
I expect that a lot of comments might be same.

**Comment by nikhiljindal** [comment]
removing from v1.3

**Comment by eparis** [comment]
ok to test

**Comment by quinton-hoole** [comment]
ok to test

**Comment by nikhiljindal** [comment]
I dont think Jianhui is working on this anymore.
Closing

**Pull request closed without merging**
