### PR TITLE
should not ignore err when convert api version

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
should not ignore err when convert api version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/approve
for `cmd/cloud-controller-manager`
/assign @sttts 
for the rest

**Comment by stewart-yu** [comment]
/hold 
until PR[https://github.com/kubernetes/kubernetes/pull/63283](https://github.com/kubernetes/kubernetes/pull/63283) get merged

**Pull request merged**
