### PR TITLE
WIP: remove pod mutation for PVs with supplemental GIDs

### LINKED ISSUE #27197: Supplemental groups on PVs mutate pod spec in kubelet
#20490 added a beta feature which allows PVs to be annotated with a GID that owns them.  This is to facilitate volumes like NFS that cannot be safely chowned/chmoded from the client and thus do not work with FSGroup.  There are a couple issues with this PR that need to be sorted out:

1.  The pod spec should not be mutated.  We should formalize in the contract for volume plugins that the `api.Pod` they are passed is a read-only view and should not be mutated.  We should probably do a copy of the pod when creating Mounters.
2.  Currently there is no security policy check to see whether the Pod can use the supplemental group the volume is annotated with.  We must be able to validate this.

@kubernetes/sig-storage

### PR DESCRIPTION
**Pull request by pmorie**
Resolves #27197 

Still WIP -- posting for early review since we want this in for 1.3.

@kubernetes/sig-storage 

cc @pweil- for `SecurityContextProvider` changes

### CODE REVIEW

**Comment by pmorie** [comment]
still need to add unit tests.  The e2e for this will likely take some doing itself, so I will do it in a follow up.

**Comment by jsafrane** [comment]
The concept looks good to me, however the number of failing tests is scary

**Comment by pmorie** [comment]
Figured out the problem with the failing tests but still need to write some unit tests.

**Comment by pmorie** [comment]
Closing, as we decided that this is going to be a 1.4 feature rather than 1.3.

**Pull request closed without merging**
