### PR TITLE
 add typemeta to every sub-controller configuration, so we can serializable config for KCM

### PR DESCRIPTION
**Pull request by stewart-yu**
**What type of PR is this?**
/kind cleanup
/kind feature

**What this PR does / why we need it**:
 add `typemeta` to every sub-controller configuration, so we can serializable config for KCM.
we want KCM's --config will look like as below in future:
```
kind: KubeControllerManagerConfiguration
apiVersion: kubecontrollermanager.config.k8s.io/v1alpha1
foo: bar
---
kind: DaemonSetControllerConfiguration
apiVersion: kubecontrollermanager.config.k8s.io/v1alpha1
bar: baz
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
/assign @luxas 
for review

**Review by luxas — APPROVED** [review]
/lgtm
/approve
Thanks @stewart-yu!

**Comment by sttts** [comment]
This topic needs a KEP. I have not seen a deep discussion of this topic. Personally I am not convinced about the usability to have 50 differently versioned objects.

**Comment by liggitt** [comment]
agree, the set-of-config-objects-keyed-by-type approach was not what I expected. was that described somewhere? the associated issue (https://github.com/kubernetes/enhancements/issues/786) doesn't have a design or KEP linked. it would be good to sketch out the end goal as a first step

**Comment by nikopen** [comment]
as code freeze is approaching soon and the design is missing, I'm moving this to the next milestone.

/milestone v1.15

feel free to move this back if consensus is reached.

**Comment by liggitt** [comment]
closing per https://github.com/kubernetes/kubernetes/pull/74059#issuecomment-464145233

can reopen if needed once this direction is proposed and agreed on

/close

**Pull request closed without merging**
