### PR TITLE
Add 7-stage upgrade jobs

### PR DESCRIPTION
**Pull request by ikehz**
Add version-skewed Kubectl tests to the upgrade jobs to get visibility that new `kubectl` will work with old cluster.

### CODE REVIEW

**Comment by ixdy** [comment]
Kinda sad we no longer have the nice odd/even split, but otherwise LGTM.

**Comment by ihmccreery** [comment]
xref #18402 #18403

**Comment by ihmccreery** [comment]
> Kinda sad we no longer have the nice odd/even split, but otherwise LGTM.

Yes, also coordinating PRs between 3 different branches is horrible.

**Comment by ihmccreery** [comment]
Manually merging to monitor Jenkins.

**Pull request merged**
