### PR TITLE
Update docker.md, simplified kill command

### PR DESCRIPTION
**Pull request by bdevloed**
docker ps -a | awk '{print $1}' could be replaced with docker ps -aq

### CODE REVIEW

**Comment by mikedanese** [comment]
@bdevloed Thanks for your contribution! This looks good to me but we need you to sign the CLA before we can accept it. Please follow @googlebot's instructions,

**Comment by bdevloed** [comment]
Done

Op za 1 aug. 2015 07:53 schreef Mike Danese <notifications@github.com>:

**Comment by mikedanese** [comment]
LGTM. Thanks!

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
very weird failure by jenkins... looks like someone deleted intermediate docker image during the build. Two failed in a row with the same error. @k8s-bot ok to test.

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Jenkins flake; passed previously.  Merging.

**Pull request merged**
