### PR TITLE
Add kubectl version guard around kubectl port-forward

### LINKED ISSUE #26594: v1.2 "Kubectl client Simple pod should support port-forward" hanging when run with v1.3 Kubectl
```
Kubectl client Simple pod 
  should support port-forward
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:525
[BeforeEach] Kubectl client
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:100
STEP: Creating a kubernetes client
May 31 15:09:49.323: INFO: >>> testContext.KubeConfig: /usr/local/google/home/ihmccreery/.kube/config

STEP: Building a namespace api object
May 31 15:09:49.377: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-uc5qv
May 31 15:09:49.418: INFO: Service account default in ns e2e-tests-kubectl-uc5qv with secrets found. (40.713401ms)
STEP: Waiting for a default service account to be provisioned in namespace
May 31 15:09:49.418: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-uc5qv
May 31 15:09:49.459: INFO: Service account default in ns e2e-tests-kubectl-uc5qv with secrets found. (40.667732ms)
[BeforeEach] Kubectl client
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:120
[BeforeEach] Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:190
STEP: creating the pod from /usr/local/google/home/ihmccreery/Documents/kubernetes-alt/test/e2e/testing-manifests/kubectl/pod-with-readiness-probe.yaml
May 31 15:09:49.459: INFO: Running '/usr/local/google/home/ihmccreery/Documents/kubernetes/cluster/kubectl.sh --server=https://146.148.104.150 --kubeconfig=/usr/local/google/home/ihmccreery/.kube/config create -f /usr/local/google/home/ihmccreery/Documents/kubernetes-alt/test/e2e/testing-manifests/kubectl/pod-with-readiness-probe.yaml --namespace=e2e-tests-kubectl-uc5qv'
May 31 15:09:50.066: INFO: stderr: ""
May 31 15:09:50.066: INFO: stdout: "pod \"nginx\" created\n"
May 31 15:09:50.066: INFO: Waiting up to 5m0s for 1 pods to be running and ready: [nginx]
May 31 15:09:50.066: INFO: Waiting up to 5m0s for pod nginx status to be running and ready
May 31 15:09:50.107: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-uc5qv' status to be 'running and ready'(found phase: "Pending", readiness: false) (40.643351ms elapsed)
May 31 15:09:52.151: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-uc5qv' status to be 'running and ready'(found phase: "Running", readiness: false) (2.084719295s elapsed)
May 31 15:09:54.193: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-uc5qv' status to be 'running and ready'(found phase: "Running", readiness: false) (4.126926727s elapsed)
May 31 15:09:56.236: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-uc5qv' status to be 'running and ready'(found phase: "Running", readiness: false) (6.170280744s elapsed)
May 31 15:09:58.279: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-uc5qv' status to be 'running and ready'(found phase: "Running", readiness: false) (8.212968774s elapsed)
May 31 15:10:00.322: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nginx]
[It] should support port-forward
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:525
STEP: forwarding the container port to a local port
May 31 15:10:00.322: INFO: starting port-forward command and streaming output
May 31 15:10:00.322: INFO: Asynchronously running '/usr/local/google/home/ihmccreery/Documents/kubernetes/cluster/kubectl.sh /usr/local/google/home/ihmccreery/Documents/kubernetes/cluster/kubectl.sh --server=https://146.148.104.150 --kubeconfig=/usr/local/google/home/ihmccreery/.kube/config port-forward --namespace=e2e-tests-kubectl-uc5qv nginx :80'
May 31 15:10:00.323: INFO: reading from `kubectl port-forward` command's stderr

[hangs]

^C

[...]

• Failure [65.392 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1200
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:526
    should support port-forward [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:525

    May 31 15:10:51.904: Failed to read from kubectl port-forward stderr: EOF

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:97
```

Repro:

```
$ git checkout release-1.2
$ make clean && make quick-release
$ go run ./hack/e2e.go --check_version_skew=false -v --test '--test_args=--ginkgo.focus=Kubectl\sclient\sSimple\spod\sshould\ssupport\sport-forward --kubectl-path=<PATH TO 1.3 KUBECTL>'
```

My guess is just that this test just isn't resilient to empty output.  Then there's the separate issue of actually fixing the root problem.

### PR DESCRIPTION
**Pull request by ikehz**
Fixes #26594 (once this gets backported to v1.2 and v1.3).

### CODE REVIEW

**Comment by caesarxuchao** [comment]
This PR LGTM

> Fixes #26594

IIUC there are other problems in 26594?

**Comment by caesarxuchao** [comment]
FYI
```
!!! 'gofmt -s -w' needs to be run on the following files: 
./test/e2e/portforward.go
FAILED   ./hack/../hack/verify-gofmt.sh	9s
```

**Comment by ihmccreery** [comment]
> IIUC there are other problems in #26594?

Nope, cherry picking #23445 solved the other problems.

**Comment by ihmccreery** [comment]
Oops, thanks.  `gofmt`ed, re-applying LGTM.

**Comment by caesarxuchao** [comment]
Thanks!

**Comment by ihmccreery** [comment]
@k8s-oncall please prioritize merging this: once it merges, it needs to be backported to v1.3 and v1.2 to get tests green.

**Pull request merged**
