### PR TITLE
Fix typo in empty_dir.go

### PR DESCRIPTION
**Pull request by eltociear**
#### What type of PR is this?
fix

#### What this PR does / why we need it:
fixed typo
assigment -> assignment
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/ok-to-test
/priority backlog
/kind cleanup

**Comment by dims** [comment]
/approve

NOTE: single word typo with an lgtm already.

**Pull request merged**
