### PR TITLE
Change maxsize to size in logrotate.

### PR DESCRIPTION
**Pull request by bprashanth**
How do I trigger a test? I usually test logrotate with `logrotate -s` and that works as expected.

### CODE REVIEW

**Comment by zmerlynn** [comment]
Fix in Salt LGTM, not sure about GCI? @adityakali?

**Comment by adityakali** [comment]
Please update it at https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L95 as well.
Thanks!

**Comment by bprashanth** [comment]
Done, PTAL

**Comment by bprashanth** [comment]
I'm adding cherry-pick, unless someone objects. @roberthbailey as cherry pick czar (or whatever that role is).

**Comment by adityakali** [comment]
LGTM. Thanks!

**Comment by bprashanth** [comment]
subsumed by https://github.com/kubernetes/kubernetes/pull/29139, so removed cherrypick labels

**Comment by roberthbailey** [comment]
Do they need to be cherry picked together though (since that one built on top of this one)?

**Comment by bprashanth** [comment]
@roberthbailey the options added in https://github.com/kubernetes/kubernetes/pull/29139 essentially revert this pr. Those options are more reliable to avoid file name collisions for log rotate in spans > 1s (and we shouldn't be filling up maxsize in 1s, hopefully).

**Pull request merged**
