### PR TITLE
cleanup: skip a test validate time_zone letter case in darwin

### LINKED ISSUE #109220: TestValidateCronJob cant pass in macos
### What happened?

```bash
$ go test ./pkg/apis/batch/validation -run  TestValidateCronJob

--- FAIL: TestValidateCronJob (0.01s)
    validation_test.go:1355: expected failure for spec.timeZone: Invalid value: "AMERICA/new_york": unknown time zone AMERICA/new_york
    validation_test.go:1378: expected failure for spec.timeZone: Invalid value: "AMERICA/new_york": unknown time zone AMERICA/new_york
FAIL
FAIL    k8s.io/kubernetes/pkg/apis/batch/validation     0.028s
FAIL

```

### What did you expect to happen?

test withnot FAIL

### How can we reproduce it (as minimally and precisely as possible)?

In a macos.
do `make test` or `go test ./pkg/apis/batch/validation -run  TestValidateCronJob`

### Anything else we need to know?

https://github.com/golang/go/issues/21512  golang upstrem disscusion.

We use time.LoadLocation to validate time_zone setting in object spec like cronjob.(It is ok)

We also add a test try to validate `AMERICA/new_york` is not a crroct value.

This test is not true sometimes, for example, in default macos this is a true time_zone value.(maybe also true in other case insensitive os, but I have no device to try)

At least we should get the test to pass on macos, I hope.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here

Darwin MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
We use `time.LoadLocation` to validate time_zone setting in object spec like cronjob. 
We also add a test try to validate `AMERICA/new_york` is not a crroct value.
This test is not true sometimes, for example, in default macos this is a true time_zone value.(maybe also true in other case insensitive os, but I have no device to try)
#### Which issue(s) this PR fixes:

Fixes #109220

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

This is an important test. This means that we are using an unstable mechanism to validate the cronjob API surface. That's a problem that has to be resolved before this field graduates from alpha

**Comment by liggitt** [comment]
cc @soltysh

**Comment by liggitt** [comment]
rather than dropping this, I could live with skipping it on darwin only, and adding an issue to remove the skip and resolve the instability prior to graduating the TimeZone field to beta

**Comment by liggitt** [comment]
@Abirdcfly @soltysh - once there's an issue open to resolve this as part of graduation criteria from alpha → beta, we can unhold this

**Comment by dims** [comment]
@Abirdcfly see https://github.com/kubernetes/kubernetes/pull/109261/files i liked that one better :)

**Comment by Abirdcfly** [comment]
Thanks for @dims  's suggestion.
Follow @dims 's suggestion to rewrite the code, meanwhile, after testing, this testcase runs normally on windows, the detailed reason may be https://github.com/kubernetes/kubernetes/issues/109220#issuecomment-1087292183

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/triage accepted
/priority important-longterm

**Comment by soltysh** [comment]
> @Abirdcfly @soltysh - once there's an issue open to resolve this as part of graduation criteria from alpha → beta, we can unhold this

Added that explicitly in the KEP - https://github.com/kubernetes/enhancements/pull/3263/files

/hold cancel

/milestone v1.24

**Pull request merged**
