### PR TITLE
Remove support for building "run containers".

### PR DESCRIPTION
**Pull request by jbeda**
This was untested, broken and largely unused.

Related to #12 and #2455#issuecomment-68803245.

### CODE REVIEW

**Comment by proppy** [comment]
can you also remove `local_docker.md` and friends?

**Comment by jbeda** [comment]
Couldn't find any friends to remove so just removed local_docker.md.  Let me know if I missed something.

**Comment by proppy** [comment]
Oh yes, you removed the bootstrap stuff in the previous commit too.

**Comment by proppy** [comment]
LGTM :crying_cat_face: (make sure travis is happy)

**Comment by jbeda** [comment]
Thanks @proppy.  Eventually this will come back better and stronger.

**Pull request merged**
