### PR TITLE
Make adding audit annotations thread-safe

### PR DESCRIPTION
**Pull request by tallclair**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is the first PR in a series of audit logging refactors (broken up for smaller PRs) to clean up the audit handling in the request chain. This PR does the following:

1. Remove unused k8s.io/apiserver/pkg/audit/event package
2. Add a new `AddAuditAnnotations` method for bulk-adding audit annotations
3. Eliminate direct modification of the audit event outside of the audit package (`AddAuditAnnotation(s)` is the only way to log annotations now)
4. Make AddAuditAnnotation(s) thread-safe by storing a mutex on the audit context. In a future PR, I will consolidate all the audit context variables into a single object.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig api-machinery auth
/assign @liggitt

### CODE REVIEW

**Comment by enj** [comment]
cc @ibihim

**Comment by tallclair** [comment]
/milestone v1.24

I know it's super late to be adding this to the milestone, but based on some issues with annotation race conditions that we saw in past releases, I think we want this.

If this is too large of a change this late in the release cycle, I also have a smaller change that drops most of the refactoring and just adds the annotation mutex. (I'd still want the refactor for v1.25 though)

**Comment by dims** [comment]
@tallclair could you please find some approvers? i've requested too many to Jordan already :)

**Comment by liggitt** [comment]
the need for metrics and the desire to annotate impacted requests impacted by go1.18 sha1 certificate deprecation (https://github.com/kubernetes/kubernetes/pull/109024/files#r836397931) makes this more than just nice-to-have, imo

**Comment by liggitt** [comment]
> If this is too large of a change this late in the release cycle, I also have a smaller change that drops most of the refactoring and just adds the annotation mutex. (I'd still want the refactor for v1.25 though)

all else being equal, I'd strongly prefer the smaller change for 1.24 (I haven't looked at the details of the PR)

**Comment by lavalamp** [comment]
Sorry this was actually on my list, just not at the top.

A smaller PR would be easier though!!

**Comment by tallclair** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/109078

The new PR didn't end up being that much smaller with the second "optional" commit, but I think it's a conceptually smaller change. I'd still like to pick the changes from this PR (preventing all direct access to the audit event) back up for v1.25.

**Pull request closed without merging**
