### PR TITLE
Rename k8s.io/{kube-gen -> code-generator}

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by deads2k** [comment]
@cheftako this is the rename we agreed to here: https://groups.google.com/forum/#!topic/kubernetes-dev/hdMe3GGgFhI .  Approving.

**Comment by caesarxuchao** [comment]
It looks like you haven't changed the vendor/k8s.io/code-generator symlink to point to the new path?
Also need to run hack/update-gofmt.sh

lgtm.

**Comment by sttts** [comment]
> It looks like you haven't changed the vendor/k8s.io/code-generator symlink to point to the new path?

I think I did. Will take another look tomorrow. Had to run to a meetup today....

**Pull request merged**
