### PR TITLE
Revert "change CPUCFSQuotaPeriod default value to 100us to match Linu…

### PR DESCRIPTION
**Pull request by aojea**
…x default"

This reverts commit f2d591fae62822a8e96b0e015e6e42224286b5d5.

/kind bug
```release-note
NONE
```

It breaks the job https://testgrid.k8s.io/google-gce#gce-cos-master-alpha-features

ref https://github.com/kubernetes/kubernetes/pull/112075

the kubelet fail to run the apiserver pod, it fails with the following error

```
CI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "max 100": write /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod566772ddea2984f4084dd4cd59d51bff.slice/cri-containerd-78fd8bfc8b28488f6d87c32d6c79810266f119a935675ce8cdc435fd8a9a01c3.scope/cpu.max: invalid argument: unknown,StartedAt:1970-01-01 00:00:00 +0000 UTC,FinishedAt:2022-08-24 04:06:36 +0000 
```

> Aug 24 04:06:39.347467 bootstrap-e2e-master kubelet[2211]: I0824 04:06:39.347403    2211 status_manager.go:538] "Ignoring same status for pod" pod="kube-system/kube-apiserver-bootstrap-e2e-master" status={Phase:Running Conditions:[{Type:PodHasNetwork Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-08-24 04:06:35 +0000 UTC Reason: Message:} {Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-08-24 04:06:31 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-08-24 04:06:31 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kube-apiserver]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-08-24 04:06:31 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kube-apiserver]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-08-24 04:06:31 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.138.0.2 PodIP:10.138.0.2 PodIPs:[{IP:10.138.0.2}] StartTime:2022-08-24 04:06:31 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:kube-apiserver State:{Waiting:&ContainerStateWaiting{Reason:CrashLoopBackOff,Message:back-off 10s restarting failed container=kube-apiserver pod=kube-apiserver-bootstrap-e2e-master_kube-system(566772ddea2984f4084dd4cd59d51bff),} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:StartError,Message:failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "max 100": write /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod566772ddea2984f4084dd4cd59d51bff.slice/cri-containerd-78fd8bfc8b28488f6d87c32d6c79810266f119a935675ce8cdc435fd8a9a01c3.scope/cpu.max: invalid argument: unknown,StartedAt:1970-01-01 00:00:00 +0000 UTC,FinishedAt:2022-08-24 04:06:36 +0000 UTC,ContainerID:containerd://78fd8bfc8b28488f6d87c32d6c79810266f119a935675ce8cdc435fd8a9a01c3,}} Ready:false RestartCount:1 Image:registry.k8s.io/kube-apiserver-amd64:v1.26.0-alpha.0.170_d436f5d0b7eb87 ImageID:sha256:04e5b74f4306e7a7db0d72e38b1d5c62d5c4628ef4fe2c376341a5729cb3ffd2 ContainerID:containerd://78fd8bfc8b28488f6d87c32d6c79810266f119a935675ce8cdc435fd8a9a01c3 Started:0xc0010b178a}] QOSClass:Burstable EphemeralContainerStatuses:[]}

### CODE REVIEW

**Comment by aojea** [comment]
/hold

testing if is this really the one causing the problem

/test pull-kubernetes-e2e-gce-alpha-features

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce-alpha-features
/hold cancel

I'm almost sure this was the one breaking the job

**Comment by aojea** [comment]
it was this commit, the job `pull-kubernetes-e2e-gce-alpha-features` is working now

>  I0826 22:28:03.865] Aug 26 22:28:03.864: INFO: 20 / 23 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)

/assign @liggitt @dims 
/cc @bobbypage @paskal @endocrimes

**Comment by bobbypage** [comment]
Sorry for the breakage.

Sounds like there is some issue where if the alpha feature gate for that PR is enabled, then it is writing `max 100` to cpu.max cgroup file. That shouldn't be valid...

>> cpu.max
>> A read-write two value file which exists on non-root cgroups. The default is “max 100000”.

>> The maximum bandwidth limit. It’s in the following format:

>> $MAX $PERIOD
>> which indicates that the group may consume upto $MAX in each $PERIOD duration. “max” for $MAX indicates no limit. If only one number is written, $MAX is updated.

based on https://docs.kernel.org/admin-guide/cgroup-v2.html

So we should expect default to be `max 100000` not `max 100`. There may be some issue in the conversation...

**Comment by paskal** [comment]
Seems like the test fails even after revert, and according to the problem log I would say it's unlikely associated with the change this PR is reverting: in case of problems with that change, kubelet won't start with message like following:

```
Aug 03 14:35:19.780469 e2e-e2a60cb2ac-a7d53-minion-group-05r1 kubelet[4188]: E0803 14:35:19.772966    4188 run.go:74] "command failed" err="failed to validate kubelet configuration, error: invalid configuration: cpuCFSQuotaPeriod (--cpu-cfs-quota-period) {100µs} requires feature gate CustomCPUCFSQuotaPeriod, path: &TypeMeta{Kind:,APIVersion:,}"
```

**Comment by liggitt** [comment]
pull-kubernetes-e2e-gce-alpha-features is failing at head, started failing with the change from 100ms to 100us, and is passing on this revert. 
 
/retest
/lgtm

**Comment by dims** [comment]
@liggitt needs `api-approvers` to `/approve`

**Comment by aojea** [comment]
@paskal you should have been checking a different thing, it was causing a job to fail because the kubelet failed to run the apiserver pod, all green since this merge and the commit was reverted

https://testgrid.k8s.io/google-gce#gce-cos-master-alpha-features

**Comment by aojea** [comment]
/sig node

this feature is in alpha since 1.12, feature should evolve or being removed ... but what we should not do is to modify them if there is no intention of promotion

```
	// owner: @szuecs
	// alpha: v1.12
	//
	// Enable nodes to change CPUCFSQuotaPeriod
	CPUCFSQuotaPeriod featuregate.Feature = "CustomCPUCFSQuotaPeriod"
```

/cc @deads2k @wojtek-t 

for wg-reliability

**Comment by paskal** [comment]
What should we do then? Enabling this feature leaves you with 1000x of the default value, which has already created a lot of confusion over four years.

Also, I have no idea what precisely went wrong in GCP and led to the e2e test failure. I would be very grateful if someone could pinpoint how these code changes led to the failing test.

**Comment by liggitt** [comment]
This is the error:

> failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "max 100": write /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod566772ddea2984f4084dd4cd59d51bff.slice/cri-containerd-78fd8bfc8b28488f6d87c32d6c79810266f119a935675ce8cdc435fd8a9a01c3.scope/cpu.max: invalid argument: unknown

The logic with the merged PR is trying to write "max 100" to the `cpu.max` cgroup, not the default of `100000`

**Comment by aojea** [comment]
> What should we do then? Enabling this feature leaves you with 1000x of the default value, which has already created a lot of confusion over four years.

skimming the original PR that introduced the feature https://github.com/kubernetes/kubernetes/pull/63437, it seems that the feature gate was more a safeguard/opt-in flag than a new feature, can you check with  sig-node check if we can promote  or what is needed to make these feature GA, and configure it correctly?

Note: you can test the behavior sending the same PR and using `/test pull-kubernetes-e2e-gce-alpha-features` on the PR comments, so the bot triggers the job for testing the code and reproduce the problem

**Comment by liggitt** [comment]
based on https://github.com/kubernetes/kubernetes/pull/112077#issuecomment-1230508390, I suspect something in the kubelet config → runtime → CRI pipeline is misconverting / handling units incorrectly when the feature is enabled

**Comment by paskal** [comment]
I'll try to untangle what is going on and redo the PR. It looks like the value provided by the user was indeed divided by 1000, so the scope changes dramatically: it would mean that the default value was okay, but whatever the user provided was 1000x smaller than the user thought. I feel like I opened Pandora's box here.

I would need `/ok-to-test` from someone in #112108 to proceed with tests.

**Comment by liggitt** [comment]
> it would mean that the default value was okay, but whatever the user provided was 1000x smaller than the user thought

fwiw... the alpha jobs that started failing ere not explicitly configuring the value differently from the default, so even the default value had issues

**Comment by paskal** [comment]
Can of Pandora's boxes\* then. I have one theory of why this might be happening. Still, if it's not the case and the default, which theoretically should not be affected by the flag, is altered after my changes, I'll need some quality time with a psychotherapist.

**Comment by paskal** [comment]
For history, I was wrong, and the default value is 100ms and not 100μs: PR #112123 clarified the code to prevent mistakes about units of measurement around this feature in the future. I'll try clarifying [linked](https://www.kernel.org/doc/html/latest/scheduler/sched-bwc.html#management) kernel.org documentation as well.

Also, based on @aojea comment, I'll try to initiate promotion of the feature added in #63437 in 1.12 to GA.

**Comment by szuecs** [comment]
I am not sure if we should graduate or delete it. We run happily with disabled CFS and load tested that it does not make sense in serving HTTP APIs with low latency requirements to use CFS in any kind of configuration. It was done to unblock us and others back then, but after years of not using it, I can't really argue to promote to GA.
@vishh was right in his original statement.

**Comment by paskal** [comment]
We tried CPU Limiting and abolished it altogether as well, as it turned out to be too problematic. I won't be working on making this feature GA.

**Pull request merged**
