### PR TITLE
kubeadm: Expose only the cluster-info ConfigMap in the kube-public ns

### LINKED ISSUE #320: Only the cluster-info ConfigMap should be exposed in the kube-public namespace
Currently it seems like all ConfigMaps in the kube-public namespace are, which is sub-optimal
This can and should be cherrypicked into the v1.6 and v1.7 releases.
PR: https://github.com/kubernetes/kubernetes/pull/48050

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Noticed a bug; we should only expose the `cluster-info` ConfigMap.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes: https://github.com/kubernetes/kubeadm/issues/320

**Special notes for your reviewer**:

Cherrypick-candidate for v1.8 cc @dchen1107 
Not blocking the release though...

**Release note**:

@jbeda @pipejakob @timothysc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Looks right. I'll approve the cherrypick. cc @dchen1107.

**Comment by luxas** [comment]
Got lgtm and was approved by the release team. Adding the label

**Comment by luxas** [comment]
@caesarxuchao Did this get cherrypicked?

**Comment by caesarxuchao** [comment]
No. Some how i missed this one. 1.7.1 ok?

**Comment by luxas** [comment]
@caesarxuchao Let's do it by "best effort". If you still cherrypick, include, if not, v1.7.1 is fine. 
Security patch but was in v1.6 as well...

**Pull request merged**
