### PR TITLE
fix typecast missing

### LINKED ISSUE #120478: Failed test Namespaces [Serial] should apply changes to a namespace status [Conformance]
### Which jobs are failing?

https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master

### Which tests are failing?

 [It] [sig-api-machinery] Namespaces [Serial] should apply changes to a namespace status [Conformance] 

### Since when has it been failing?

Since https://github.com/kubernetes/kubernetes/pull/119459

### Testgrid link

https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master

### Reason for failure (if possible)

Change on the assertions semantics?

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig api-machinery
/sig testing

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes #120478

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
Thanks for the quick fix

**Pull request merged**
