### PR TITLE
fix string trim func isBackendPoolOnSameLB in azure

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
`TrimRight` should be corrected to `TrimSuffix` since it's string based trimming.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @liggitt
/assign @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
the fix looks good, a unit test demonstrating the bug would be good as well

**Comment by beautytiger** [comment]
> the fix looks good, a unit test demonstrating the bug would be good as well

Good idea. A test case is added to prove this fix, although the test case is a little unusual in real life.

**Comment by beautytiger** [comment]
Shall we go on? @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
@beautytiger thanks for the fix, looks like this is a bug need to cherry-pick, we should never use `TrimRight`

**Comment by beautytiger** [comment]
> @beautytiger thanks for the fix, looks like this is a bug need to cherry-pick, we should never use `TrimRight`

@andyzhangx 
Thanks for your reminding. Let me do the cherry-pick work.
And which branch shall I target to?

**Pull request merged**
