### PR TITLE
bump honnef.co/go/tools to support go1.20

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Updates analysis tooling to support go1.20 language changes (still works on go1.19 as well)

xref https://github.com/kubernetes/kubernetes/pull/114502#issuecomment-1385609481 https://github.com/kubernetes/release/issues/2815

#### Special notes for your reviewer:

Bumps to HEAD rather than a released tag

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
that's funny... the new version worked on both go1.19 and go1.20, but failed the job because it caught a shadowing issue the old version missed... pushed an update that fixes that

**Comment by dims** [comment]
good one :)

/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
/hold cancel
canary and current verify jobs passed

**Pull request merged**
