### PR TITLE
Move to golang 1.12.1 official image

### PR DESCRIPTION
**Pull request by dims**
We used 1.12.0 + hack to download 1.12.1 binaries as we were in a rush
on friday since the images were not published at that time. Let's remove
the hack now and republish the kube-cross image

Change-Id: I3ffff3283b6ca755320adfca3c8f4a36dc1c2b9e

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/75372

**Comment by liggitt** [comment]
Need to bump the version file as well to 1.12.1-2

**Comment by dims** [comment]
Ack @liggitt 

@ixdy if i remember right you had mentioned that we don't bump version numbers, is that the same for the `-2` suffix too?

Jordan,
When Jeff responds, i will update the PR. If i am not reachable, please feel free to copy commits to another PR or update this one itself (i have clicked on "allow edits from maintainers" checkbox).

Thanks!

**Comment by neolit123** [comment]
cc @jpbetz 
hello, can you answer the above questions related to the revision `-2`?

basically we had a custom golang 1.12.1 image for a couple of days, but now we need to use the official one, thus having a revision:

> Need to bump the version file as well to 1.12.1-2

seems appropriate?

**Comment by ixdy** [comment]
The first part of the kube-cross version

**Comment by ixdy** [comment]
The first part of the kube-cross version (before the dash) refers to the golang version. The piece after the dash is the image revision. So `v1.12.1-2` would be the correct version to use here.

**Comment by liggitt** [comment]
> If i am not reachable, please feel free to copy commits to another PR or update this one itself (i have clicked on "allow edits from maintainers" checkbox).

added a commit to bump to `1.12.1-2`

**Comment by liggitt** [comment]
(need to build/push the new kube-cross image before CI will go green on this PR)

**Comment by javier-b-perez** [comment]
I'm building the images now... should take ~2 hours.

**Comment by javier-b-perez** [comment]
the image k8s.gcr.io/kube-cross:v1.12.1-2 is available now

**Comment by dims** [comment]
Thanks @liggitt @ixdy

**Comment by dims** [comment]
and thanks @javier-b-perez !

**Pull request merged**
