### PR TITLE
Updated doc.go files in staging/src/k8s.io/metrics

### PR DESCRIPTION
**Pull request by alejandrox1**
Added vanity urls to imports and updated package descriptions.

Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>

**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Update imports and package information in `staging/src/k8s.io/metrics/pkg/apis`.

**Which issue(s) this PR fixes**:

xref: #68231

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/priority backlog
/sig instrumentation

### CODE REVIEW

**Comment by alejandrox1** [comment]
assign @lavalamp

**Comment by dims** [comment]
/assign @liggitt 

Jordan, easy one, just adds the `// import` after the package statement. can you please look?

/milestone v1.15

**Comment by dstrebel** [comment]
Hello! We are starting Code Freeze for 1.15. Is this PR still planned to be included in 1.15?

**Pull request merged**
