### PR TITLE
remove most of contrib as it's moving to a seperate repo

### PR DESCRIPTION
**Pull request by mikedanese**
let's see how badly things break

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
LGTM

**Comment by eparis** [comment]
This broke ansible as it used stuff out in the tree (built binaries, stuff in cluster, etc)

**Comment by mikedanese** [comment]
@eparis I apoligize for that. Does it make sense to move this into cluster/ as a provider?

**Comment by eparis** [comment]
not sure, still mulling over how I want to suggest dealing with things.

**Comment by thockin** [comment]
Some of these things are "neat things you can do with kubernetes".  Some of them are "tools to help us write e2e tests and do demos".  Some of these are "tools we use as part of making kube releases".  I think the last kind should stay with the main repo, no?

release-notes at least.  I am ambivalent on the rest.  I think the for-demos directory should be unpacked.

**Comment by mikedanese** [comment]
I asked @brendandburns if he wanted submit-queue in new contrib repo or in a subdirectory of build/ and he opted for new contrib repo. I would group release notes with that. The "for-tests" images have been moved to [./contrib/for-tests](https://github.com/kubernetes/kubernetes/tree/master/test/images). What is the distinction between "for-demos" and "neat things you can do with kubernetes"?

**Comment by thockin** [comment]
Nothing.  for-tests and for-demos was artificial, we should just flatten it.

**Pull request merged**
