### PR TITLE
Automated cherry pick of #97980: Revert "Merge pull request #92817 from kmala/kubelet"

### PR DESCRIPTION
**Pull request by ehashman**
Cherry pick of #97980 on release-1.20.

#97980: Revert "Merge pull request #92817 from kmala/kubelet"

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix the regression in 1.20 with the slow pods termination. Before this fix pods may take an additional time to terminate - up to one minute. Reversing the change that ensured that CNI resources cleaned up when the pod is removed on API server.
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Link to issue: #97288

**Comment by ehashman** [comment]
filed flake as #98039

/retest ?

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
