### PR TITLE
Automated cherry pick of #78672: Enable resize in default gce storageclass

### PR DESCRIPTION
**Pull request by msau42**
Cherry pick of #78672 on release-1.14.

#78672: Enable resize in default gce storageclass

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
poke @mikedanese
/unassign

**Comment by BenTheElder** [comment]
er
/uncc
:upside_down_face:

**Comment by hoegaarden** [comment]
Consulting https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#patch-releases I don't think this qualifies as a change that should go into a patch release.

I will close this PR (and the ones on the other release branches).

Please, if you don't agree with that decision, ping me, the @kubernetes/patch-release-team, or re-open the PR(s)!

/close

**Pull request closed without merging**
