### PR TITLE
from #61246 note removed examples and regression for master

### PR DESCRIPTION
**Pull request by lathama**
**What this PR does / why we need it**:
Documentation correction in changelogs after examples were removed from project in #61246

**Which issue(s) this PR fixes**
None

**Special notes for your reviewer**:
Also addressed regressions with changelogs that link to master. I am happy to answer any questions.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by lathama** [comment]
@jberkus or @foxish can you comment on the release notes changes. Should this be done elsewhere?

**Comment by lathama** [comment]
@brendandburns or whom-ever what do I need to do here? Shall I just close this?

**Comment by lathama** [comment]
Ok, required tests have passed (not sure why for a doc update) so what is next?

**Comment by nikhita** [comment]
/sig release
/kind cleanup

/cc @nickchase 

/assign @thockin 
for approval

**Comment by nikhita** [comment]
@lathama sorry that it's taking so much time to get a review! Usually top-level directory changes require approval from a small group of people and they are usually pretty busy folks...

**Comment by lathama** [comment]
Thank you @thockin I think the label it wants is /approved with a d because of reasons.

**Comment by nikhita** [comment]
> Thank you @thockin I think the label it wants is /approved with a d because of reasons.

@lathama /approve is the correct command but there was an outage in the automation recently, and hence it did not catch the command.

@thockin can you approve again?

**Comment by lathama** [comment]
@nikhita ack, thanks, I did not know about the outage.

**Comment by lathama** [comment]
Should I take the time and do a PR for each release branch?

**Comment by nikhita** [comment]
> Should I take the time and do a PR for each release branch?

I'm not sure I follow. Can you clarify what PR/changes you have in mind?

**Comment by lathama** [comment]
Backporting the corrections to each release branch. Several release branches are linking to master branch for documentation and examples. Currently mobile, will comment in detail later.

**Pull request merged**
