### PR TITLE
Fix builds on selinux systems

### PR DESCRIPTION
**Pull request by derekwaynecarr**
The build was broken on SELinux enabled systems.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
It's still broken on the copy output piece, working my way through that now...

**Comment by derekwaynecarr** [comment]
This should be all good now.

/cc @ncdc @pmorie

**Comment by derekwaynecarr** [comment]
thanks @eparis

**Comment by alex-mohr** [comment]
Because submit queue is blocked, I'm going to kick off re-tests of the top 5 PRs in the queue, then merge them if they pass.
@k8s-bot test this please: issue #IGNORE

**Pull request merged**
