### PR TITLE
Correct kubectl delete's wrong synopsis

### PR DESCRIPTION
**Pull request by feihujiang**
#11362

In synopsis of kubectl_delete.md, It says "if both a filename and command line arguments are passed, the command line arguments are used and the filename is ignored."

But when I test, 
$kubectl delete pods asdf -f pod.yaml
error: when paths, URLs, or stdin is provided as input, you may not specify a resource by arguments as well

So I think the description "if both a filename and command line arguments are passed, the command line arguments are used and the filename is ignored." is not right, we should correct it

### CODE REVIEW

**Comment by feihujiang** [comment]
@thockin @mikedanese Could you please review this PR?

**Comment by jlowdermilk** [comment]
lgtm

**Comment by bgrant0607** [comment]
Wait, file names are command-line arguments.

**Comment by bgrant0607** [comment]
The delete synopsis says:
```
Delete a resource by filename, stdin, resource and name, or by resources and label selector.
```
How about:
```
Only one type of argument may be specified: filenames, resources and names, or resources and label selector
```

**Comment by bgrant0607** [comment]
This will also need to be rebased. We're making sweeping doc transformation changes at the moment.

**Comment by feihujiang** [comment]
@bgrant0607 @jlowdermilk Changed according to your advice, Could you please review this again?

**Comment by mikedanese** [comment]
@feihujiang can you rebase onto HEAD? I think that might fix gendoc issues.

**Comment by bgrant0607** [comment]
Thanks. LGTM, but we already cut 1.0.1, so this will need to wait.

**Comment by feihujiang** [comment]
@mikedanese I have rebased onto master. @bgrant0607 OK, I see.

**Comment by mikedanese** [comment]
@feihujiang this needs a rebase and for you to run ./hack/run-gendocs.sh again but it's LGTM so hopefully we can merge when CI checks are green.

**Comment by feihujiang** [comment]
@mikedanese Sorry, I'm on a business trip, will be back next week, and then I'll do this as soon as possible.

**Comment by feihujiang** [comment]
@mikedanese Hi, I have rebased onto the master, please review. I checked Jenkins GCE e2e failing, it isn't  relevant to this PR. Need ok-to-test again.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by feihujiang** [comment]
@mikedanese 
The failing message is:
[Fail] Probing container [It] with readiness probe should not be ready before initial delay and never restart 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/container_probe.go:59

But I don't know what's the matter.

**Comment by mikedanese** [comment]
@feihujiang our parallel e2e builds have been flaky.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@feihujiang please rebase again :( I will merge right away.

**Comment by feihujiang** [comment]
@mikedanese I have rebased, please review.

**Comment by mikedanese** [comment]
Merging since it's text only and @feihujiang has already had to rebase twice.

**Pull request merged**
