### PR TITLE
federation: Adding secret API

### PR DESCRIPTION
**Pull request by kshafiee**
This adds the secret API to federation-apiserver.

### CODE REVIEW

**Comment by kshafiee** [comment]
I signed it!

**Comment by nikhiljindal** [comment]
ok to test

**Comment by nikhiljindal** [comment]
Thanks @kshafiee, the changes LGTM. Will add the LGTM label once we have 1.3 finalized and we start merging non-1.3 federation changes.

Will be great if you can add a test that creates a secret and then verifies that you can get it.
Fine to do it in your next PR. You can look at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federated-service.go for a similar existing test.

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
@kshafiee can you please rebase?

deep_copy.go and conversion.go files are now gone.

**Comment by nikhiljindal** [comment]
I assume this is now superseded by https://github.com/kubernetes/kubernetes/pull/29138.
@kshafiee Can we close this?

**Pull request closed without merging**
