### PR TITLE
 Fix a grammatical problem in a comment

### PR DESCRIPTION
**Pull request by lioncruise**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
Thanks for this contribution :smile: :+1:!

/lgtm
/ok-to-test

**Comment by nikhita** [comment]
@luxas Oops, looks like the bot didn't remove `needs-ok-to-test`!

**Pull request merged**
