### PR TITLE
Updating link to Container Engine docs

### PR DESCRIPTION
**Pull request by MikeJeffrey**
More useful landing page.

### CODE REVIEW

**Comment by bgrant0607** [comment]
I'm not sure we want to make this change. cc @kmerker

**Comment by MikeJeffrey** [comment]
Requested by Kit and Mansoor. No rush, low priority.

**Comment by mansoorj** [comment]
The original request was to use https://cloud.google.com/container-engine/docs/before-you-begin as the landing page. Since the user followed the link from a "getting started" page, we should avoid long-winded and general-purpose pages and steer them to a specific set of instructions that help them get started. 

Also, with the k8s v1.0 announcement, we should expect a spike in traffic to the website, so I'd prioritize it higher than low.

**Comment by brendandburns** [comment]
@bgrant0607 I think that this is better than the existing marketing page.  It has calls to action and sane docs.

I'm ok with @mansoorj 's suggestion (sorry I didn't notice it before I hit merge) I will send a PR to adjust that.

**Pull request merged**
