### PR TITLE
Only output json format from tests when building junit reports

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Follow up from https://github.com/kubernetes/kubernetes/pull/80822:
* Only outputs json format from tests when building junit reports (keeps output more readable when running manually)
* Changes install message for junit tool to match auto-installer

**Special notes for your reviewer**:
Addresses:
* https://github.com/kubernetes/kubernetes/pull/80822#issuecomment-517175258
* https://github.com/kubernetes/kubernetes/pull/80822#discussion_r309478304

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig testing
/cc @cblecker @BenTheElder

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
/priority important-soon
TestVolumeProvision is baaaack
/retest

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/80528 flake
/retest

**Pull request merged**
