### PR TITLE
Remove e2e test that checked scheduler priority function for spreading of ReplicationController pods

### LINKED ISSUE #47769: SchedulerPriorities - swarm of 1.6 -> 1.7 upgrade failures
## [Triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-5-.*-1-7.*upgrade&test=SchedulerPriorities)

Includes links to these:
* SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node
* SchedulerPriorities [Serial] Pod should be prefer scheduled to node that satisify the NodeAffinity
* SchedulerPriorities [Serial] [Pod should avoid to schedule to node that have avoidPod annotation](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new/18#k8sio-schedulerpriorities-serial-pod-should-avoid-to-schedule-to-node-that-have-avoidpod-annotation)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:85
Expected error:
    <*errors.errorString | 0xc420c35060>: {
        s: "1 / 15 pods in namespace \"kube-system\" are NOT in RUNNING and READY state in 5m0s\nPOD                                 NODE                                         PHASE   GRACE CONDITIONS\nkube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]\n",
    }
    1 / 15 pods in namespace "kube-system" are NOT in RUNNING and READY state in 5m0s
    POD                                 NODE                                         PHASE   GRACE CONDITIONS
    kube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:84
```

/sig scheduling
/assign @davidopp 

See also #47767

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:
Remove e2e test that checked scheduler priority function for spreading of ReplicationController pods.
The test is flaky in our test clusters, but passes in our local clusters. It looks like our e2e test clusters are not deterministic enough for checking all of the scheduler priority functions. Besides, this functionality is checked extensively by our unit tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47769

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bsalamat** [comment]
@kubernetes/sig-scheduling-misc 
@dchen1107 @davidopp @monopole

**Comment by bsalamat** [comment]
@davidopp I think this PR should be cherrypicked.

**Comment by dchen1107** [comment]
This one requires cherrypick to v.17 branch. Thanks!

**Pull request merged**
