### PR TITLE
AzureDisk: Parse zoned first before using it

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

`zoned` should be parsed first before using.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/pull/67121#discussion_r208639436

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @ddebroy @khenidak @andyzhangx

### CODE REVIEW

**Comment by andyzhangx** [comment]
wait @ddebroy for review first, thanks.

**Review by ddebroy — APPROVED** [review]
lgtm .. thank you!

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
