### PR TITLE
Avoid unnecessary GET request when updating pod status

### PR DESCRIPTION
**Pull request by yujuhong**
When sending out an pod status update, kubelet GETs the pod from the apiserver
Terminates if the apiserver returns an not found error; otherwise, proceed to
to update.

Even after a pod has been deleted, there might still be queued up updates for
the pod. This leads to expensive, unncessary GET operations. The situation is
worse when there are batch creation/deletion of a significant number of pods
(e.g., E2E tests), leaving many updates in the queue.

This change checks whether a pod exists before GET the pod from the apiserver
to avoid redundant GETs.

### CODE REVIEW

**Comment by yujuhong** [comment]
Forked from #20110.

**Comment by yujuhong** [comment]
@timstclair, ping! I would like to get this in for v1.2 to solve cleanup issue after batch deletion of pods.

**Comment by timstclair** [comment]
Sorry, LGTM.

**Comment by yujuhong** [comment]
Thanks!

**Pull request merged**
