### PR TITLE
Add support for GetNodeResources to AWS

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Blocked on test fixes in #5072 (and could use some more testing as well).

**Comment by brendandburns** [comment]
LGTM, but Travis says a unit test is busted

**Comment by justinsb** [comment]
Yes - any chance you could peek at #5072 if you're in "review mode"?  That is the unit test fix that needs to land.  (The AWS mock does not apply instance filters - it just returns all instances)

**Comment by justinsb** [comment]
This should be unblocked now that #5072 is in

**Comment by brendandburns** [comment]
Still LGTM, but now needs a rebase... (sorry!  promise to merge quickly once rebased)

**Comment by justinsb** [comment]
No problem - rebases are easy (when I get them right).  And the conflicts are mostly with my own code anyway :-)

**Pull request merged**
