### PR TITLE
update/fix kubectl proxy example in help string

### LINKED ISSUE #8943: '--api-prefix' option in 'kubectl proxy' documentation is wrong
Without `--api-prefix`, `kubectl proxy` works just fine,
```
$ curl localhost:8001/api/
{
  "versions": [
    "v1beta1",
    "v1beta2",
    "v1beta3"
  ]
}
```

With '--api-prefix=xxx-api', it stops work:
```
$ curl localhost:8001/xxx-api/
404 page not found
```

My `kubectl` version:
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-878-g851f6b754241c0-dirty", GitCommit:"851f6b754241c01f30c43cddd2f9ca8c7c3f42f5", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-893-g58b683fe296da8-dirty", GitCommit:"58b683fe296da870fdbc6eb1a32dcf50ed94a8e3", GitTreeState:"dirty"}
```
 
@jlowdermilk, could you take a look? Thanks.

### PR DESCRIPTION
**Pull request by j3ffml**
For #6584. Closes #8943

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Ah, I duplicated your work.

@jlowdermilk, how do you manage to only regenerate the relevant docs? When I run hack/run-gendocs.sh, it regenerates every docs, which is annoying.

**Comment by caesarxuchao** [comment]
lol, you just answered my question in #8949 : )

**Comment by jlowdermilk** [comment]
Yep. For simplicity's sake, since this already has the minimal gendocs output, want to close #8949?

**Comment by caesarxuchao** [comment]
Yes. LGTM.

**Pull request merged**
