### PR TITLE
Revert "Use watch param instead of deprecated /watch/ prefix"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#41887

To fix submit queue.
@deads2k @liggitt

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-oncall - this broke kubemark-500

**Comment by deads2k** [comment]
@wojtek-t do know which requests are miss categorized?

**Comment by wojtek-t** [comment]
@deads2k - ohh, it seems that this time it may be test issue.
I think that we are missing "WATCH" here:
https://github.com/kubernetes/kubernetes/blob/7332baf9a32fedef031b9d65eb9ec9bb6aa32860/test/e2e/framework/metrics_util.go#L224

If someone can send a PR for it, it would be great..

**Comment by deads2k** [comment]
> If someone can send a PR for it, it would be great..

on it.

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/42003

**Comment by wojtek-t** [comment]
I merged that one. I'm 99% it will help, but if not, we should merge this one (otherwise we should close this one).

**Comment by deads2k** [comment]
I'll check kubemark again in two hours to see if we've gotten a good run.  Please wait until then (job 2789: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/) before merging this.

**Comment by deads2k** [comment]
2789 pulled an old level: `c8a87d3` instead of `c4e3ed5`.  Waiting one more.

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
We're back to green here https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/ on build https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2790/

**Pull request closed without merging**
