### PR TITLE
runtime container data need remain consistent

### PR DESCRIPTION
**Pull request by lilongfeng0902**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We meet the question that the pod is not running normally when we power off one node of the cluster and power on again a few minutes later. We follow the commits to modify, this problem will not happen again.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Containers are GCed in `removeStaleState()` by default for cpu/memory manager. It would not be the best place to remove unsynced containers.  

https://github.com/kubernetes/kubernetes/blob/520b991347b9c77635c0e4555f1703a86dcdd4ff/pkg/kubelet/cm/memorymanager/memory_manager.go#L300-L349

BTW, can you open a bug report for this problem and reproduce the steps? Does it happen every time and what pod container will meet this problem? 

/ok-to-test

**Comment by pacoxu** [comment]
BTW, #84462 add `buildContainerMapFromRuntime` for CPUManager stored state. It should not cover removing the containers.
/cc @klueska

**Comment by lilongfeng0902** [comment]
> Containers are GCed in `removeStaleState()` by default for cpu/memory manager. It would not be the best place to remove unsynced containers.
> 
> https://github.com/kubernetes/kubernetes/blob/520b991347b9c77635c0e4555f1703a86dcdd4ff/pkg/kubelet/cm/memorymanager/memory_manager.go#L300-L349
> 
> BTW, can you open a bug report for this problem and reproduce the steps? Does it happen every time and what pod container will meet this problem?
> 
> /ok-to-test

Thanks for your review, maybe I should try my best to reproduce the problem and find some useful bug report, it's not very easy. It doesn't happen everytime. I need confirm that what pod container will meet the problem.

**Pull request closed without merging**
