### PR TITLE
build: move some of hack/lib/ into a new cluster/lib/ 

### PR DESCRIPTION
**Pull request by mikedanese**
Some functionality in hack/lib is currently depended on by cluster/common.sh
so kube-up from the full release tar (which does not include hack/) is currently
broken. With this PR we create cluster/lib/ and move the necessary bits from
hack/ over to get kube-up working again.

https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L27-L28

Fixes: 96d1b8d1b2b3c935d905e85957927e578118c417

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot please e2e test this.

**Comment by mikedanese** [comment]
@k8s-bot please e2e test this.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
ping @zmerlynn

**Comment by zmerlynn** [comment]
Glancing at the existing contents, the intent of `hack` is not to be shipped. There's actually no place for common shell code other than `cluster/` right now, I don't think.

**Comment by mikedanese** [comment]
@zmerlynn can we move hack/lib/ into cluster? that would mean build/ would have to depend on cluster (which doesn't seem like a big deal).

**Comment by zmerlynn** [comment]
Alternately, we create some common ground *somewhere*, but I don't know where. Maybe for simplification that's `cluster/lib` and we let `hack/lib` live on as the "don't ship this"?

**Comment by zmerlynn** [comment]
Change the commit message / PR? Otherwise LGTM. (I know you didn't say PTAL yet, but I was scanning PRs.)

**Comment by mikedanese** [comment]
@zmerlynn updated commit and description PTAL

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
