### PR TITLE
Automated cherry pick of #68642: remove submit-queue from readme

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #68642 on release-1.10.

#68642: remove submit-queue from readme

Cherry picking to supported branches (at least 1.11, 1.10)

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @MaciekPytel 
for cherry-pick approval

/assign @smarterclayton 
for approval

**Comment by MaciekPytel** [comment]
/hold cancel
/lgtm

Manually approving, as this is a trivial doc change.

**Pull request merged**
