### PR TITLE
Updating to etcd v3.3.15

### LINKED ISSUE #72102: kube-apiserver 1.13.x refuses to work when first etcd-server is not available.
**How to reproduce the problem**:
Set up a new demo cluster with kubeadm 1.13.1.
Create default configurationwith `kubeadm config print init-defaults`
Initialize cluster as usual with `kubeadm init`

Change the `--etcd-servers` list in kube-apiserver manifest to `--etcd-servers=https://127.0.0.2:2379,https://127.0.0.1:2379`, so that the first etcd node is unavailable ("connection refused").

The kube-apiserver is then not able to connect to etcd any more.

Last message: `Unable to create storage backend: config (\u0026{ /registry [https://127.0.0.2:2379 https://127.0.0.1:2379] /etc/kubernetes/pki/apiserver-etcd-client.key /etc/kubernetes/pki/apiserver-etcd-client.crt /etc/kubernetes/pki/etcd/ca.crt true 0xc000381dd0 \u003cnil\u003e 5m0s 1m0s}), err (dial tcp 127.0.0.2:2379: connect: connection refused)\n","stream":"stderr","time":"2018-12-17T12:13:19.608822816Z"}`

kube-apiserver does not start.

If I upgrade etcd to version 3.3.10, it reports an error `remote error: tls: bad certificate", ServerName ""`

**Environment**:
- Kubernetes version 1.13.1
- kubeadm in Vagrant box

I also experience this bug in an environment with a real etcd cluster.

/kind bug

### PR DESCRIPTION
**Pull request by dims**
etcd v3.3.14 contains a fix we need namely https://github.com/etcd-io/etcd/pull/10911

Change-Id: I282b2994d2a6c32d7afec7732237677a20e32983

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #72102

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gyuho** [comment]
cf. https://github.com/kubernetes/kubernetes/pull/81435

Kubernetes may need pass `grpc.WithBlock` with this change.

**Comment by gyuho** [comment]
Overall, CIs look good. I also manually tested with my Kubernetes cluster.

I will do the official v3.3.14 release today.

**Comment by gyuho** [comment]
https://github.com/etcd-io/etcd/releases/tag/v3.3.14 has been released.

**Comment by dims** [comment]
@liggitt `lint-dependencies.sh` is asking me to roll back some of the vendored deps including the `etcd` one.. weird! PTAL?

```
github.com/coreos/etcd
    pinned:    v0.0.0-20190816232144-5cf5d88a18ae
    preferred: v3.3.10+incompatible
    hack/pin-dependency.sh github.com/coreos/etcd v3.3.10+incompatible
github.com/grpc-ecosystem/go-grpc-middleware
    pinned:    v0.0.0-20190222133341-cfaf5686ec79
    preferred: v1.0.0
    hack/pin-dependency.sh github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go.uber.org/atomic
    pinned:    v0.0.0-20181018215023-8dc6146f7569
    preferred: v1.3.1
    hack/pin-dependency.sh go.uber.org/atomic v1.3.1
go.uber.org/multierr
    pinned:    v0.0.0-20180122172545-ddea229ff1df
    preferred: v1.1.0
    hack/pin-dependency.sh go.uber.org/multierr v1.1.0
```

**Comment by liggitt** [comment]
That just means the "minimal" version go prefers differs from the pinned version. Minimal version selection will always prefer a tagged version over a v0.0.0 version

**Comment by dims** [comment]
@liggitt shouldn't it prefer `v3.3.14` (over `v3.3.10+incompatible`)

**Comment by dims** [comment]
Also i had run `hack/pin-dependency.sh github.com/coreos/etcd v3.3.14` and ended up with v0.0.0 version

**Comment by liggitt** [comment]
The presence of https://github.com/etcd-io/etcd/blob/v3.3.14/go.mod means go tidy will normalize that tag to a v0.0.0 pseudoversion, and prefer semver tags without go.mod files as bigger

**Comment by dims** [comment]
@liggitt ok, i just rolled back the 3 things - `go-grpc-middleware`, `atomic`, `multierr` to slightly older versions as requested by `lint-dependencies.sh`. 

Now i am left with
```
github.com/coreos/etcd
    pinned:    v0.0.0-20190816232144-5cf5d88a18ae
    preferred: v3.3.10+incompatible
    hack/pin-dependency.sh github.com/coreos/etcd v3.3.10+incompatible
```

Which reverts back the etcd change we were trying to upgrade :) 

How do we deal with this situation?

Thanks,
Dims

**Comment by dims** [comment]
Please note that we will have to merge https://github.com/kubernetes/kubernetes/pull/81435 as well

**Comment by liggitt** [comment]
> Now i am left with
> 
> ```
> github.com/coreos/etcd
>     pinned:    v0.0.0-20190816232144-5cf5d88a18ae
>     preferred: v3.3.10+incompatible
>     hack/pin-dependency.sh github.com/coreos/etcd v3.3.10+incompatible
> ```
> 
> Which reverts back the etcd change we were trying to upgrade :)
> 
> How do we deal with this situation?

go makes this situation very painful to deal with.

etcd should not have tagged a patch release > 2.x and added a go.mod file (it should have kept any pre-existing 3.x.y streams go.mod-free)

The only way I see to fix this is for etcd to tag a v3.3.15 patch release with the go.mod file removed

**Comment by dims** [comment]
@gyuho @jpbetz Can you please take a look at the suggestion from @liggitt above?

**Comment by gyuho** [comment]
@dims @liggitt @jpbetz 

> Minimal version selection will always prefer a tagged version over a v0.0.0 version if any dependency in the graph expresses a preference for that tagged version

Isn't this why we have `go.mod` file, so people can pin later version manually? What `go.mod` has `v3.3.10+incompatible` in the first place? Just trying to understand how k8s updates and validates `go.mod` file.

Does kubernetes allow upstream project to migrate to go module? Would this happen again when kubernetes upgrades to etcd v3.4?

**Comment by liggitt** [comment]
> Why does `go.mod` in the PR have `v3.3.10+incompatible` in the first place?

That is how go represents tags of dependencies that are not module-aware. See https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean

> Does kubernetes allow upstream project to migrate to go module?

To be clear, this is an issue with go modules, not kubernetes specifically. Our verification scripts ensure that we are using the same version of dependencies that someone using our k8s.io/{api,apimachinery,apiserver,client-go} libraries would use.

> Would this happen again when kubernetes upgrades to etcd v3.4?

We would have to root out any transitive dependencies on any semantically-tagged etcd versions. It looks like we have the following today:

> github.com/spf13/viper@v1.3.2 github.com/coreos/go-etcd@v2.0.0+incompatible
> github.com/spf13/viper@v1.3.2 github.com/coreos/etcd@v3.3.10+incompatible

**Comment by gyuho** [comment]
> Why does go.mod in the PR have v3.3.10+incompatible in the first place?

>> That is how go represents tags of dependencies that are not module-aware. See

I understand that. I was asking why we are not updating `go.mod` file manually to pin etcd `v3.3.14`?

Btw, if removing `go.mod` file is the only way, I can change it back to glide...

**Comment by liggitt** [comment]
> I was asking why we are not updating `go.mod` file manually to pin etcd `v3.3.14`?

We can do that for kubernetes/kubernetes, but we have no way to pin a dependency on v3.3.14 in k8s.io/apiserver that would be picked up by things that consume k8s.io/apiserver as a library.

**Comment by gyuho** [comment]
@liggitt Ok now makes sense. Thanks for the explanation!

**Comment by gyuho** [comment]
@dims @liggitt @jpbetz https://github.com/etcd-io/etcd/releases/tag/v3.3.15 has been released with `go.mod` file removed.

**Comment by dims** [comment]
Looks so much better @gyuho @liggitt (just 3 deps to vendor)

**Comment by jingyih** [comment]
Can we update the PR title? This is actually updating to etcd v3.3.15.

**Comment by BenTheElder** [comment]
FYI https://prow.k8s.io/command-help#retitle

**Comment by liggitt** [comment]
because all GRPC clients in our build will pick up the new GRPC version, here are the noted behavior changes we're picking up with this bump:
1.18: https://github.com/grpc/grpc-go/releases/tag/v1.18.0
  * client: make handshake required 'on' by default, not 'hybrid'
1.19: https://github.com/grpc/grpc-go/releases/tag/v1.19.0
  * keepalive: apply minimum ping time of 10s to client and 1s to server 
1.20: https://github.com/grpc/grpc-go/releases/tag/v1.20.0
  * transport: remove RequireHandshakeHybrid support
1.21: https://github.com/grpc/grpc-go/releases/tag/v1.21.0
  * none noted
1.22: https://github.com/grpc/grpc-go/releases/tag/v1.22.0
  * none noted
1.23: https://github.com/grpc/grpc-go/releases/tag/v1.23.0
  * client: remove option to send RPCs before HTTP/2 handshake is completed

**Comment by liggitt** [comment]
looks like some of the added golang/x/tools replace statements aren't needed anymore

**Comment by dims** [comment]
@liggitt waiting on the gce-big job. all others are green. i had to blacklist a few more packages since a grpc public method got deprecated (make staticcheck happy)

**Comment by warmchang** [comment]
@dims Does this PR need cherry pick to release-1.13/release-1.14/release-1.15? thanks!

**Comment by ylhyh** [comment]
> @dims Does this PR need cherry pick to release-1.13/release-1.14/release-1.15? thanks!

There should be a hotfix for 1.15 at least

**Comment by dims** [comment]
@warmchang @ylhyh if you need a hot-fix, please consider - https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-515979520

I'd note recommend destabilizing the 1.15 code base with all the grpc changes that this PR needs. Note that there is another PR in progress that needs to get in as well, namely https://github.com/kubernetes/kubernetes/pull/81435

**Pull request merged**
