### PR TITLE
Remove deprecated API definitions to make the spec valid

### LINKED ISSUE #54815: Kubernetes 1.8 OpenApi Spec is invalid
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I pass the 1.8 OpenAPI spec to Swagger's validator, I get an error that looks like:

```
# swagger-codegen validate -i openapi_kubernetes_1.8.json
attribute definitions.io.k8s.kubernetes.pkg.api.v1.PersistentVolume.description is unexpected
...
Exception in thread "main" io.swagger.codegen.cmd.ValidateException
	at io.swagger.codegen.cmd.Validate.run(Validate.java:34)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

The full output is at https://gist.github.com/ceridwen/a0007517d5410bdca0ae1653f136646f.

**What you expected to happen**:

I expected validation to pass.  Validation on the 1.6 and 1.7 specs passes.

**How to reproduce it (as minimally and precisely as possible)**:

Download https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.8/api/openapi-spec/swagger.json and run swagger-codegen version 2.2.3  on it.

**Environment**:
- Kubernetes version (use `kubectl version`): I noticed this issue on minikube v0.23.
- OS (e.g. from /etc/os-release): Mac OS X 10.12.6
- Kernel (e.g. `uname -a`): Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
- Others: swagger-codegen 2.2.3.

### PR DESCRIPTION
**Pull request by ceridwen**
**What this PR does / why we need it**:
This removes the deprecated API definitions that makes the current OpenAPI spec not conform to the standard.

**Which issue(s) this PR fixes** 
Fixes  #54815

**Special notes for your reviewer**:
This is targeted against 1.8 because I really don't want to have to work around this bug for the whole 1.8 life cycle.  I can make the same change to 1.9 if it's still necessary.

**Release note**:

```release-note
Remove deprecated API definitions to make the spec valid
```

### CODE REVIEW

**Comment by jpbetz** [comment]
@ceridwen How about we submit this to master first, get it approved and merged there and then cherry pick to 1.8 since it really should be applied to both?  The cherry pick to 1.8 won't require review once it's on master, just patch manager approval (me).

@mbohlool is out till the end of the year.

**Comment by ceridwen** [comment]
I don't understand why the failing tests failed.  Is there an explanation of what those tests test that someone can point me to?

**Comment by ceridwen** [comment]
I created a new pull request against master.

**Comment by jpbetz** [comment]
@ceridwen Would you please reference the pull to master (by PR #) from this PR? That way we can navigate to it.

**Comment by ceridwen** [comment]
The PR against master is at #55965.

**Comment by jpbetz** [comment]
@ceridwen Would you run`hack/update-openapi-spec.sh` on this PR?

From  `pull-kubernetes-verify` logs:

```
openapi-spec is out of date. Please run hack/update-openapi-spec.sh
```

**Comment by jpbetz** [comment]
I pulled this PR locally and ran `hack/update-openapi-spec.sh`. It re-added all lines in `hack/update-openapi-spec.sh` removed by this PR. `pull-kubernetes-verify` won't pass until running `hack/update-openapi-spec.sh` is a no-op.

Since we're past the deadline for 1.8.5 PRs to merge, I'm removing `cherrypick-approved` for this PR until after 1.8.5 is released. We can attempt to get this in to 1.8.6 in a couple weeks if we can get tests passing.

**Pull request closed without merging**
