### PR TITLE
apiextensions: fix panic with KUBE_API_VERSIONS set

### PR DESCRIPTION
**Pull request by sttts**
https://github.com/kubernetes/kubernetes/pull/48837 introduced a panic in apiextension-apiserver triggered by the `hack/test-update-storage-objects.sh` script in CI.

### CODE REVIEW

**Comment by sttts** [comment]
@fejta @kubernetes/kubernetes-build-cops this fixes might be critical for the queue, as soon as people rebase to today's master. The gce-etcd3 test stops it from being merged.

**Comment by fejta** [comment]
Thanks! go.k8s.io/oncall shows who is buildcop right now if you want this manually merged (but it looks like the sq is merging things)

**Comment by kow3ns** [comment]
@sttts [Prow](https://prow.k8s.io/?type=batch) looks okay so far. I will keep an eye out for issues and be ready to manually merge if necessary.

**Pull request merged**
