### PR TITLE
Fix kubectl edit: no such file

### LINKED ISSUE #22371: kubectl edit: no such file
This used to work...

```
$ kubectl edit svc hostnames-3512299341
error: open /tmp/usr/local/google/home/thockin/src/kubernetes/_output/local/bin/linux/amd64/kubectl-edit-fplln.yaml: no such file or directory
```

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #22371

@kubernetes/kubectl

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Can you modify the test in `test-cmd.sh` so it catches this regression?

**Comment by janetkuo** [comment]
Test added. PTAL

**Comment by kargakis** [comment]
LGTM

**Comment by jlowdermilk** [comment]
Thanks, pls squash commits and I'll add label/merge.

**Comment by janetkuo** [comment]
Squashed commits and applying LGTM. Thanks!

**Comment by eparis** [comment]
This PR is already included in the release-1.2 branch and does not require cherrypick-ing

**Pull request merged**
