### PR TITLE
Kubemark: allow choosing image-service

### PR DESCRIPTION
**Pull request by mm4tt**
/kind feature

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
I like this and it seems kubemark is passing - we should clean this up and merge.

**Comment by mm4tt** [comment]
Let me just double check that the flag was indeed set. Then I'll clean up and send for review

**Comment by mm4tt** [comment]
Dunno why the presubmit was cancelled. But I verified manually and everything works. This is ready for review

/test pull-kubernetes-kubemark-e2e-gce-big



/assign @wojtek-t

**Pull request merged**
