### PR TITLE
Enabled load e2e test for gce-scalability

### PR DESCRIPTION
**Pull request by piosz**
addresses #3139 

cc @davidopp @fgrzadkowski @wojtek-t

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Shippable is green. Merging.

**Comment by piosz** [comment]
Thanks!

**Comment by davidopp** [comment]
Stupid question: what does this PR actually do? It seems like the behavior is basically the same before and after this change. Sorry for the cluelessness.

**Comment by piosz** [comment]
The test is now run on Jenkins in kubernetes-e2e-gce-scalability job after "[Performance suite]" prefix is added.

**Pull request merged**
