### PR TITLE
upgrade test for BoundServiceAccountTokenVolume

### PR DESCRIPTION
**Pull request by zshihang**
Cherry pick of #94835 on release-1.19.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
add BoundServiceAccountTokenVolume upgrade test to 1.19 so that we can have signal in 1.19->1.20 upgrade test.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/ok-to-test

test-only change needed in 1.19 branch to enable 1.19 -> 1.20 upgrade testing for feature in progress for 1.20

**Comment by cpanato** [comment]
@zshihang from which PR is this cherry-pick?

**Comment by zshihang** [comment]
> @zshihang from which PR is this cherry-pick?

https://github.com/kubernetes/kubernetes/pull/94835

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
