### PR TITLE
Fix print type of podname

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
It is better to change it to %s. According to context and other prints of this file, pod name's print type are all %s, except this one.
Although it does not affect the result.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
seems not necessary; '%v' also works for `string`.

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by zhangxiaoyu-zidif** [comment]
@brendandburns  could you help to add "ok to test" lable.
Thank you very much

**Comment by zhangxiaoyu-zidif** [comment]
@brendanburns could you add "/approve no-issue" for this PR. Many thanks.

**Comment by zhangxiaoyu-zidif** [comment]
@brendanburns 
For approval. =)

**Pull request merged**
