### PR TITLE
Kill a few more uses of 'gcloud preview'

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by roberthbailey** [comment]
We should cherry pick this into the 1.1 branch.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this (huh?)

**Comment by thockin** [comment]
I simply CAN NOT get shippable to do anything but timeout.

**Pull request merged**
