### PR TITLE
Revert openapi publish

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Several issues were found post-merge in https://github.com/kubernetes/kubernetes/pull/67205:
* https://github.com/kubernetes/kubernetes/issues/71159
* https://github.com/kubernetes/kubernetes/issues/71143
* https://github.com/kubernetes/kubernetes/issues/71142

Reverting for freeze, will work on resolving those issues out of master

```release-note
NONE
```

/assign sttts roycaihw

### CODE REVIEW

**Comment by sttts** [comment]
Lgtm, after rebase.

**Comment by dims** [comment]
ouch!

**Comment by liggitt** [comment]
/assign @smarterclayton 
for approval

**Review by dims — APPROVED** [review]

**Review by dougm — COMMENTED** [review]
watching for inclusion in 1.13.0-beta.1

**Comment by roycaihw** [comment]
FYI, a WIP PR is opened to address the issues: https://github.com/kubernetes/kubernetes/pull/71192.

**Pull request merged**
