### PR TITLE
Automated cherry pick of #117802: Update podFailurePolicy comments from alpha-level to beta

### PR DESCRIPTION
**Pull request by kerthcet**
Cherry pick of #117802 on release-1.26.

#117802: Update podFailurePolicy comments from alpha-level to beta

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Revised the comment about the feature-gate level for PodFailurePolicy from alpha to beta
```

### CODE REVIEW

**Comment by kerthcet** [comment]
cc @liggitt it's a cherry-pick of https://github.com/kubernetes/kubernetes/pull/117802, also another one https://github.com/kubernetes/kubernetes/pull/117815

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
