### PR TITLE
kubeadm: upgrade coredns to v1.9.3

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

with https://github.com/kubernetes/kubernetes/pull/110488 that upgrade coredns in kube-up only.

#### Special notes for your reviewer:
- https://github.com/coredns/corefile-migration/releases/tag/v1.0.17 for corefile migration to v1.9.3

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: update CoreDNS to v1.9.3.
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/hold 
as the image wait util `registry.k8s.io/coredns/coredns:v1.9.3` is ready.

**Comment by pacoxu** [comment]
/hold cancel 
for https://github.com/kubernetes/k8s.io/pull/3821

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: update CoreDNS to v1.9.3.
```

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
/approve

for dep updates

**Pull request merged**
