### PR TITLE
Automated cherry pick of #11329

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by brendandburns** [comment]
@zmerlynn @a-robinson

**Comment by zmerlynn** [comment]
Cross-link #11329

**Comment by zmerlynn** [comment]
LGTM (fixed the title .. it doesn't super matter, but makes the subjects scan the same).

**Comment by a-robinson** [comment]
Travis and shippable are both complaining with `/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/api/swagger-spec is out of date. Please run hack/update-swagger-spec.sh`, apparently due to links containing 0.20.0 rather than 0.20.2. I assume we just ignore that on release branches?

**Comment by zmerlynn** [comment]
@a-robinson: Ugh, that's messy. I should've ran gendocs and checked in a commit, but we basically had some gendocs related fixes prior, and 0.21.2 shipped with the wrong stamps due to ... something. We're not ignoring it, but I think when @brendandburns builds the next release it'll actually work, maybe. This is clean on `release-1.0`.

**Pull request merged**
