### PR TITLE
kubectl: remove dead factory code

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/kubectl 

@madhusudancs ptal since you unplugged this

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.

I'll leave it open a day in case this was unexpected.  @kargakis Remind me tomorrow.

**Comment by kargakis** [comment]
@deads2k wasn't unexpected, it has been replaced by MapBasedSelectorForObject in https://github.com/kubernetes/kubernetes/commit/ed7ad6dcf36a68216dd823c3e03adb4a6963e210#diff-961b43a40b4bf2300c985aa16ebcc813R152

**Comment by kargakis** [comment]
Was used only by kubectl expose

**Comment by smarterclayton** [comment]
LGTM

**Comment by madhusudancs** [comment]
@kargakis LGTM.

**Pull request merged**
