### PR TITLE
Remove deferred cleanups from tests/e2e/examples.go

### PR DESCRIPTION
**Pull request by mwielgus**
It is enough to just delete the namespace (what happens after each test, examples.go:54)
cc: @jszczepkowski

### CODE REVIEW

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
(Sorry for delay, thought I had reviewed already. :/)

**Comment by zmerlynn** [comment]
Over to @quinton-hoole for ok-to-merge

**Comment by quinton-hoole** [comment]
ok-to-merge

**Pull request merged**
