### PR TITLE
Fixed ubuntu upstart scripts for etcd

### PR DESCRIPTION
**Pull request by PhilibertDugas**
Trying again the pull request as the first one had the wrong author information

### CODE REVIEW

**Comment by dchen1107** [comment]
I don't have any experience on writing upstart configuration. cc-ed @dyema for help. Thanks!

**Comment by dyema** [comment]
LGTM

**Comment by dchen1107** [comment]
Thanks, Amey.

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by asdfsx** [comment]
Still can not boot etcd when using systemd.
Got an error:
```shell
Failed to start etcd.service: Unit etcd.service failed to load: No such file or directory. 
```
so I add the following command into the ubunu/util.sh, before `sudo service etcd start`
```shell
sudo systemctl daemon-reload 
```
After this command execute, 
but etcd still cannot boot up.
I think there's also sth wrong with those init_script

So maybe docker is still a good choice

**Comment by asdfsx** [comment]
And I think it's also like a bug in ubuntu's systemd system. It make kind of loop while booting etcd in systemd.
```shell
service etcd start -> systemctl start etcd -> /run/systemd/generator.late/etcd.service 
                                   A                                 |
                                   |                      /etc/init.d/etcd start
                                   |                                 |
                                   |                       /lib/lsb/init-functions
                                   |                                 |
                                   |              /lib/lsb/init-functions.d/40-systemd
                                   |                                 |
                                   ---------------------/bin/systemctl start etcd
```
I don't know much about upstart, and systemd configuration.
And this really made me tired.

**Comment by asdfsx** [comment]
there's still a big problem
in current version the docker.service doesn't support enviroment variable writen in /etc/default/docker
so I also modify the /lib/systemd/system/docker.service
```shell
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/docker daemon $DOCKER_OPTS
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```
add EnvironmentFile, and DOCKER_OPTS

**Pull request merged**
