### PR TITLE
Set close-on-exec on the inhibitor lock fd

### LINKED ISSUE #106292: Kubelet leaks /run/systemd/inhibit/X.ref when exec iptables triggering selinux
### What happened?

```
type=AVC msg=audit(1636522420.778:201): avc:  denied  { write } for  pid=8920 comm="iptables" path="/run/systemd/inhibit/2.ref" dev="tmpfs" ino=58429 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:systemd_logind_inhibit_var_run_t:s0 tclass=fifo_file permissive=1


type=SYSCALL msg=audit(1636522420.778:201): arch=x86_64 syscall=execve success=yes exit=0 a0=c0012aa2e8 a1=c0005aab90 a2=c000fd3d00 a3=8 items=0 ppid=7642 pid=8920 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=iptables exe=/usr/sbin/xtables-nft-multi subj=system_u:system_r:iptables_t:s0 key=(null)
```
ppid 7642 == kubelet

```
# ls -lia /proc/7642/fd
...
16134 l-wx------. 1 root root 64 Nov 10 05:32 26 -> /run/systemd/inhibit/2.ref

# cat /proc/7642/fdinfo/26 
pos:	0
flags:	0104001
mnt_id:	28
```
https://unix.stackexchange.com/questions/639998/how-to-interpret-octal-flags-in-proc-pid-fdinfo-n

### What did you expect to happen?

iptables should not have the /run/systemd/inhibit/X.ref fd passed to him
we can:
- set close on exec flag
- close all fds when we exec programs
- both

### How can we reproduce it (as minimally and precisely as possible)?

Centos 8.4 with permissive selinux
kubelet 1.22.3 with shutdownGracePeriod / shutdownGracePeriodCriticalPods set

### Anything else we need to know?

_No response_

### Kubernetes version

```console
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

none

### OS version

```console
Centos 8.4
```

### Install tools

kubeadm

### Container runtime (CRI) and and version (if applicable)

containerd 1.5.7

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by champtar**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Do not leak the inihibitor lock on exec, make selinux happy

#### Which issue(s) this PR fixes:
Fixes #106292 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/triage accepted
/ok-to-test

Similar to https://github.com/s-urbaniak/uevent/pull/1/files#diff-c34cdbc81a6de518e5a2d06b326bfc4179ff5e6b996927ea9232fc0340a424f2R45-R50, it seems to be valid.
/cc @wzshiming @bobbypage

**Comment by bobbypage** [comment]
Thanks @champtar. Can you provide a bit more details on why we need to set `CloseOnExec` on the fd? Is it same reason as  @pacoxu mentioned in https://github.com/kubernetes/kubernetes/pull/106293#issuecomment-966762378 ? Perhaps would be great to leave a comment inline in the code on why it's needed. Thanks!

**Comment by champtar** [comment]
@bobbypage yes this is exactly @pacoxu linked comment, so I copy pasted most of it.
Golang os.Open actually always set O_CLOEXEC (https://github.com/golang/go/blob/release-branch.go1.17/src/os/file_unix.go#L217) so we just need to be careful with fd that are created via raw syscall or passed from other process

**Comment by wzshiming** [comment]
I am more curious, here should only call Systemd interface through dbus, maybe it is more appropriate to fix it in `github.com/godbus/dbus/v5`?

**Comment by champtar** [comment]
Thanks @wzshiming for making me dive a bit.
O_CLOEXEC flag is lost:
- when you use `dup()`, you must use `fcntl(oldfd, F_DUPFD_CLOEXEC)` instead
- when you pass an fd via recvmsg/SCM_RIGHTS, but you can set MSG_CMSG_CLOEXEC flag to have O_CLOEXEC on all received file

Even better, this is already fixed in golang 1.17+ by https://github.com/golang/go/commit/e97d8eb027c0067f757860b6f766644de15941f2
Now the question is if we want this interim fix for k8s branches not compiled with 1.17+
/retest

**Comment by champtar** [comment]
Any interest to get branches before 1.23 fixed ?

**Comment by wzshiming** [comment]
Since this is an upstream bug and it has been fixed in the new version, I personally don't think we need to deal with it. 

> Now the question is if we want this interim fix for k8s branches not compiled with 1.17+
Maybe make an interim fix in your own branch, the current k/k main branch does not have this bug

**Comment by dims** [comment]
/close

closing this per last comment from @wzshiming

**Pull request closed without merging**
