### PR TITLE
expose: Load input object for increased safety

### PR DESCRIPTION
**Pull request by 0xmichalis**
cc: @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can we add a simple test case to this to?  Thanks for making these changes.

**Comment by smarterclayton** [comment]
Is the travis failure related or a flake?

```
I0505 16:35:33.298210   37517 replication_controller.go:329] Replication Controller has been deleted default/frontend
FAIL!
Get rc {{range.items}}{{.id}}:{{end}}
  Expected: 
  Got:      redis-slave:
579 ./hack/test-cmd.sh
```

**Comment by smarterclayton** [comment]
```
--- FAIL: TestRunExposeService (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a5db1]
goroutine 27 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x249
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.RunExpose(0xc20805ff80, 0x7f901cc92230, 0xc208204770, 0xc208134ea0, 0xc2081e2b00, 0x2, 0x2, 0x0, 0x0)
	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/_test/_obj_test/expose.go:113 +0x751
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·012(0xc208134ea0, 0xc2081e2b00, 0x2, 0x2)
	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/_test/_obj_test/expose.go:42 +0xbf
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.TestRunExposeService(0xc2081cd0e0)
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/expose_test.go:61 +0xa87
testing.tRunner(0xc2081cd0e0, 0x14b40f0)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e
```

**Comment by kargakis** [comment]
Travis is green at last!:relaxed:

**Comment by kargakis** [comment]
@smarterclayton can we merge this now?

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
