### PR TITLE
Automated cherry pick of #28159

### PR DESCRIPTION
**Pull request by sttts**
Cherry pick of #28159 on release-1.3.

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM

**Comment by eparis** [comment]
If etune approves this for 1.3.0 I will pick it up into #28119 and will try to remember to close this PR. If he doesn't appove we'll need this to get it into 1.3.1.  remember, pre- x.y.0 you don't have to open the picks by hand.

**Comment by ncdc** [comment]
This is required to make the new alpha seccomp functionality we added for 1.3 work with Docker 1.10 so it would be great to have it in 1.3.0

**Comment by ncdc** [comment]
Closing since this has been approved for the batch update #28119

**Pull request closed without merging**
