### PR TITLE
Update ContainerState.Termination to ContainerState.Terminated

### PR DESCRIPTION
**Pull request by caesarxuchao**
Update ContainerState.Termination to ContainerState.Terminated in pkg/api/types.go and pkg/api/v1/types.go
#7018  #6979

@krousey @bgrant0607

### CODE REVIEW

**Comment by dchen1107** [comment]
Thanks for fixing this for me. :-)

**Comment by bgrant0607** [comment]
LGTM

**Comment by thockin** [comment]
needs rebase

**Comment by caesarxuchao** [comment]
Rebased. Let's see if it still passess all tests.

**Comment by thockin** [comment]
Negative on CI
￼

**Comment by caesarxuchao** [comment]
It's because the Goimports on my machine randomly removes actual dependencies. I can't fix it. Have you ever met similar problems?

**Comment by thockin** [comment]
Fix your GOPATH

**Comment by caesarxuchao** [comment]
Shippable is green

**Pull request merged**
