### PR TITLE
Bump the fsnotify from version v1.6.0 to v1.7.0

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
https://github.com/fsnotify/fsnotify/releases/tag/v1.7.0
#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
/cc @dims for approve.
Thanks

**Comment by dims** [comment]
Looking at https://github.com/fsnotify/fsnotify/compare/v1.6.0...v1.7.0 looks like they added support for a bunch of OS's. the backend_inotify.go for linux support doesn't look too bad. we should be ready to yank this back out if we see trouble in linux or windows in our CI systems.

/approve
/lgtm

**Pull request merged**
