### PR TITLE
adds Ubuntu node e2e test

### PR DESCRIPTION
**Pull request by yguo0905**
**What this PR does / why we need it**:

Add node e2e test for Ubuntu image.

**Special notes for your reviewer**:

**Release note**:

```NONE```

### CODE REVIEW

**Comment by yguo0905** [comment]
@dchen1107

**Comment by dchen1107** [comment]
Please include one more job for node serial test. Thanks!

**Comment by yguo0905** [comment]
Done.

**Comment by yguo0905** [comment]
I changed the PROJECT name since it was too long (>30 chars). Please take a look and LGTM again.

**Pull request merged**
