### PR TITLE
Cleanup ginkgo.Fail calls from the e2e test framework

### LINKED ISSUE #81939: cleanup ginkgo.Fail calls from the e2e test framework
/help
/kind cleanup
/area e2e-testing-framework

mini guide:
- make sure you have signed the CNCF [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)
- clone kubernetes;/kubernetes
- search for ginkgo.Fail calls under test/e2e/framework
e.g. https://github.com/kubernetes/kubernetes/search?q=%22ginkgo.Fail%22&unscoped_q=%22ginkgo.Fail%22
- replace them with this [wrapper function](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/log/logger.go#L57) that was added in this PR:
https://github.com/kubernetes/kubernetes/pull/80253
- send a PR for kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81939

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by oomichi — CHANGES_REQUESTED** [review]
/assign

**Comment by beautytiger** [comment]
@oomichi 
Thanks for your guide.
limit changes within test/e2e/framework. How about it?

**Review by draveness — COMMENTED** [review]
/ok-to-test

**Pull request merged**
