### PR TITLE
extend cmd valid resources information about roles

### PR DESCRIPTION
**Pull request by xilabao**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37366)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
lgtm.  I'm still interested in seeing this list auto-populated or least tested via reflection.

**Comment by xilabao** [comment]
@k8s-bot cvm gce e2e test this

**Comment by deads2k** [comment]
@k8s-bot cvm gce e2e test this

test wedged in infrastructure

**Pull request merged**
