### PR TITLE
fix typos for pod replacement policy

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

There were a few typos for `podRecreationPolicy` rather than `podReplacementPolicy`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
thx!
/lgtm

**Comment by kannon92** [comment]
/assign @alculquicondor 
For the job controller code.

not sure who to ask for apis changes?

**Comment by alculquicondor** [comment]
/approve

I see @liggitt was already requested for review. Let's wait.

**Pull request merged**
