### PR TITLE
cluster/aws: Add option for kubeconfig context

### LINKED ISSUE #24877: AWS: kube-up configure kube-config context
I've run `kube-up` to create a cluster, which resulted in a `aws_kubernetes` cluster and user being created in kube-config. 

Now I want to run `kube-up` again with different parameters, to create a second cluster in a different AWS account. I would like to use a different name for the cluster and user for this cluster. From what I can see from the [script](https://github.com/kubernetes/kubernetes/blob/e9c57e6970c5628f77bbd637bee1aac16fa7ff80/cluster/aws/util.sh#L1291), there seems to be no way to completely override the name used.

I understand that I can use a separate kube-config file, but I don't want to do that. I want to use the same kube-config file, with multiple clusters and users, all handled by `kube-up`.

### PR DESCRIPTION
**Pull request by paralin**
Added KUBE_CONFIG_CONTEXT environment variable to customize the kubeconfig context created at the end of the aws kube-up script.

Fixes #24877 

This PR does barely anything and shouldn't require e2e tests. It's just a minor convenience.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24910)

### CODE REVIEW

**Comment by paralin** [comment]
Probably should be assigned to @justinsb

**Comment by eparis** [comment]
ok to test

**Comment by paralin** [comment]
? Tested twice and one flaked I guess?

**Comment by eparis** [comment]
looks like it, can you look through the lsit of flakes and try to find a match for that dynamic provisioning flake?

**Comment by eparis** [comment]
@k8s-bot test this issue: #24620

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue: #IGNORE

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this issue: #26431

**Comment by paralin** [comment]
@yujuhong @mikedanese "Milestone is for future release and can't be merged"? can someone set a milestone on this?

Thanks!

**Comment by paralin** [comment]
I like how one bot is triggering the other bot with a comment :)

**Pull request merged**
