### PR TITLE
Automated cherry pick of #120222: apf: use context for queue wait

### LINKED ISSUE #119799: apf queue wait time for a request exceeds the hard-coded 15s threshold
### What happened?

The user receives a timeout `504` for a certain request:
```
I0726 22:18:10.778212      11 httplog.go:129] "HTTP" verb="LIST" URI="/api/v1/namespaces/<ns>/pods?
pretty=true&allowWatchBookmarks=false&labelSelector=<selector>&resourceVersion=862900435&watch=false" 
latency="1m0.037950467s" userAgent="Kubernetes Java Client/16.0.0-SNAPSHOT" 
audit-ID="caa77d18-9f66-4d8e-a29d-146a2efbb22c" srcIP="10.100.150.226:45302" 
apf_pl="workload-low" apf_fs="service-accounts" resp=504 statusStack=
```

This is the stack trace from httplog:
```
goroutine 32409485 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0ff829340, 0x0?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:314 +0x90
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0ff829340, 0x1?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:296 +0x25
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc084b08690, 0xc0da50ebe0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:255 +0xd8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00e854978, {0x5713ec8, 0xc08c402740}, 0xdf8475800?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:146 +0x2e3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.withRequestDeadline.func1({0x5713ec8, 0xc08c402740}, 0xc050286c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go:100 +0x362
net/http.HandlerFunc.ServeHTTP(0x1?, {0x5713ec8?, 0xc08c402740?}, 0x8?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withWaitGroup.func1({0x5713ec8?, 0xc08c402740}, 0xc050286c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:77 +0x766
net/http.HandlerFunc.ServeHTTP(0xc00383daf0?, {0x5713ec8?, 0xc08c402740?}, 0xc0abaab680?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*goaway).ServeHTTP(0xc01017d100, {0x5713ec8, 0xc08c402740}, 0xc050286c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/goaway.go:72 +0x146
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuditAnnotations.func1({0x5713ec8, 0xc08c402740}, 0xc050286a00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit_annotations.go:36 +0x125
net/http.HandlerFunc.ServeHTTP(0x5714e78?, {0x5713ec8?, 0xc08c402740?}, 0x56cf548?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1({0x5713ec8?, 0xc08c402740}, 0xc050286600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0x18d
net/http.HandlerFunc.ServeHTTP(0x481b860?, {0x5713ec8?, 0xc08c402740?}, 0xd?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1({0x5713ec8, 0xc08c402740}, 0xc090260f68?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0x126
net/http.HandlerFunc.ServeHTTP(0x5715f18?, {0x5713ec8?, 0xc08c402740?}, 0x56cf548?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.withLogging.func1({0x5705a98, 0xc090260f68}, 0xc050286400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:128 +0x339
net/http.HandlerFunc.ServeHTTP(0x5714e78?, {0x5705a98?, 0xc090260f68?}, 0x56cf548?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1({0x5705a98, 0xc090260f68}, 0xc050286000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x1ed
net/http.HandlerFunc.ServeHTTP(0x5714e78?, {0x5705a98?, 0xc090260f68?}, 0x10?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.withRequestReceivedTimestampWithClock.func1({0x5705a98, 0xc090260f68}, 0xc052439f00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/request_received_time.go:38 +0x167
net/http.HandlerFunc.ServeHTTP(0xc0cf0282c0?, {0x5705a98?, 0xc090260f68?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithMuxAndDiscoveryComplete.func1({0x5705a98, 0xc090260f68}, 0xc052439f00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/mux_discovery_complete.go:52 +0x191
net/http.HandlerFunc.ServeHTTP(0xc00e580000?, {0x5705a98?, 0xc090260f68?}, 0x8?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1({0x5705a98?, 0xc090260f68?}, 0xc0cf0282c0?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:74 +0xb1
net/http.HandlerFunc.ServeHTTP(0x481b860?, {0x5705a98?, 0xc090260f68?}, 0x8?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.withAuditID.func1({0x5705a98, 0xc090260f68}, 0xc052439e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/with_auditid.go:66 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc0abaabc98?, {0x5705a98?, 0xc090260f68?}, 0x3e59880?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0f1ab6d3f?, {0x5705a98?, 0xc090260f68?}, 0x5?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x2b
net/http.serverHandler.ServeHTTP({0x699880?}, {0x5705a98, 0xc090260f68}, 0xc052439e00)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.initALPNRequest.ServeHTTP({{0x5714e78?, 0xc0f3196e40?}, 0xc057590e00?, {0xc0091c8e10?}}, {0x5705a98, 0xc090260f68}, 0xc052439e00)
	/usr/local/go/src/net/http/server.go:3556 +0x245
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0x815d928?, 0x0?, 0x0?, 0xc0abaabfb0?)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2311 +0x83
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2025 +0x64a
" addedInfo="
logging error output: \"{\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\
"Timeout: request did not complete within the allotted timeout\\\",\\\
"reason\\\":\\\"Timeout\\\",\\\"details\\\":{},\\\"code\\\":504}\
\"
"
```

The timeout filter aborted the request and sent a `504` to the caller:
https://github.com/kubernetes/kubernetes/blob/953be8927218ec8067e1af2641e540238ffd7576/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L146

The goroutine that the timeout handler spawned to execute the request (rest of the handler chain) was in flight for more than `60s`, and it is recording a `429` response code, implying that apf rejected the request.
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Request",
  "auditID": "caa77d18-9f66-4d8e-a29d-146a2efbb22c",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/<ns>/pods?pretty=true&allowWatchBookmarks=false&labelSelector=<selector>&resourceVersion=862900435&watch=false",
  "verb": "list",
  "user": {
    "username": "system:serviceaccount:<sa>",
    "uid": "5ab073d0-5c0e-4985-bca3-20038108d401",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:<sa>",
      "system:authenticated"
    ],
    "extra": {
      "authentication.kubernetes.io/pod-name": [
        "<pod-name>"
      ],
      "authentication.kubernetes.io/pod-uid": [
        "11916349-428e-4d9f-9167-899fcacbf6d5"
      ]
    }
  },
  "sourceIPs": [
    "10.100.150.226"
  ],
  "userAgent": "Kubernetes Java Client/16.0.0-SNAPSHOT",
  "objectRef": {
    "resource": "pods",
    "namespace": "<ns>",
    "apiVersion": "v1"
  },
  "responseStatus": {
    "metadata": {},
    "code": 429
  },
  "requestReceivedTimestamp": "2023-07-26T22:17:10.740109Z",
  "stageTimestamp": "2023-07-26T22:18:10.904195Z"
}
```

This means that the request was waiting in the queue for `60s` before it was removed from the queue and rejected. We are already aware of the fact that the removal check happens upon arrival of a new request for the priority level. But we only check the queue that has been selected for the newly arrived request, there could be other queues in the queueset that could have old requests that are candidate for rejection.

When a new request arrives, we assign it to a queue first and then remove old requests from the selected queue. This means, the logic for selecting a queue for the new request takes into account the work in seat-seconds of these "should be rejected now" requests waiting in the set of queues being considered. 

So a queue with more work in seat-seconds is less likely to be selected and this phenomenon may contribute to a request waiting for more than `15s`
Also there is the extreme case of new request not arriving for the given priority level.

https://github.com/kubernetes/kubernetes/blob/1620473a9a01dd6bbef3398c0acb2e581d0a13c3/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L568-L576

https://github.com/kubernetes/kubernetes/blob/1620473a9a01dd6bbef3398c0acb2e581d0a13c3/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L619-L620

Other observations:
- Maximum observed time from audit logs was 61.9922s out of the thousands of examples
- The given priority level (`workload-low`) was maxed out, requests that failed to be dispatched were rejected with reasons cancelled or time-out 

How we can avoid this issue:
A: when a new request arrives:
- we scan all the queues of the queueset and reject the requests that have been waiting for more than `15s` 
- we select a queue for the new request
(we depend on new request arrival for the queueset, as we do today, and iterating trough the requests waiting in the queues for the queueset is costly to the O(n), n is the number of requests waiting)

B: we can use the context of the request, if it has a deadline (true for all non long-running requests - it's the `timeout` specified in the request URI, otherwise `60s`
- we derive a new context from the request context, and pass the new context to the promise that will be used by req.wait(). the new context has a deadline of 1/4 of the request timeout (`15s` at most)
This approach does not depend on arrival of new request - https://github.com/kubernetes/kubernetes/pull/105849 is a work in progress for this approach.

### What did you expect to happen?

Ideally, queue wait time of a request should not exceed its deadline or does not depend on arrival of any future request.

### How can we reproduce it (as minimally and precisely as possible)?

Hard to reproduce manually, but audit entry and httplog from production shows it's happening

### Kubernetes version

v1.23.17

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #120222 on release-1.28.

#### Which issue(s) this PR fixes:
Fixes #119799

```release-note
NONE
```

/kind bug

### CODE REVIEW

**Comment by tkashem** [comment]
@wojtek-t  There was a conflict inside the removed function `removeTimedOutRequestsFromQueueToBoundLocked` of queueset.go, so i think it was a clean pick.

I think it's because we did not cherry-pick https://github.com/kubernetes/kubernetes/pull/119385 in 1.28, 

```
--- a/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
+++ b/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
@@@ -632,43 -618,6 +617,85 @@@ func (qs *queueSet) shuffleShardLocked(
        return bestQueueIdx
  }
  
++<<<<<<< HEAD
++// removeTimedOutRequestsFromQueueToBoundLocked rejects old requests that have been enqueued
++// past the requestWaitLimit
++func (qs *queueSet) removeTimedOutRequestsFromQueueToBoundLocked(queue *queue, fsName string) {
++      timeoutCount := 0
++      disqueueSeats := 0
++      now := qs.clock.Now()
++      reqs := queue.requestsWaiting
++      // reqs are sorted oldest -> newest
++      // can short circuit loop (break) if oldest requests are not timing out
++      // as newer requests also will not have timed out
++
++      // now - requestWaitLimit = arrivalLimit
++      arrivalLimit := now.Add(-qs.qCfg.RequestWaitLimit)
++      reqs.Walk(func(req *request) bool {
++              if arrivalLimit.After(req.arrivalTime) {
++                      if req.decision.Set(decisionReject) && req.removeFromQueueLocked() != nil {
++                              timeoutCount++
++                              disqueueSeats += req.MaxSeats()
++                              req.NoteQueued(false)
++                              metrics.AddRequestsInQueues(req.ctx, qs.qCfg.Name, req.fsName, -1)
++                      }
++                      // we need to check if the next request has timed out.
++                      return true
++              }
++              // since reqs are sorted oldest -> newest, we are done here.
++              return false
++      })
++
++      // remove timed out requests from queue
++      if timeoutCount > 0 {
++              qs.totRequestsWaiting -= timeoutCount
++              qs.totSeatsWaiting -= disqueueSeats
++              qs.reqsGaugePair.RequestsWaiting.Add(float64(-timeoutCount))
++              qs.seatDemandIntegrator.Set(float64(qs.totSeatsInUse + qs.totSeatsWaiting))
++      }
++}
++
++||||||| constructed merge base
 +// removeTimedOutRequestsFromQueueToBoundLocked rejects old requests that have been enqueued
 +// past the requestWaitLimit
 +func (qs *queueSet) removeTimedOutRequestsFromQueueToBoundLocked(queue *queue, fsName string) {
 +      timeoutCount := 0
 +      disqueueSeats := 0
 +      now := qs.clock.Now()
 +      reqs := queue.requestsWaiting
 +      // reqs are sorted oldest -> newest
 +      // can short circuit loop (break) if oldest requests are not timing out
 +      // as newer requests also will not have timed out
 +
 +      // now - requestWaitLimit = arrivalLimit
 +      arrivalLimit := now.Add(-qs.qCfg.RequestWaitLimit)
 +      reqs.Walk(func(req *request) bool {
 +              if arrivalLimit.After(req.arrivalTime) {
 +                      if req.decision.Set(decisionReject) && req.removeFromQueueLocked() != nil {
 +                              timeoutCount++
 +                              disqueueSeats += req.MaxSeats()
 +                              req.NoteQueued(false)
 +                              metrics.AddRequestsInQueues(req.ctx, qs.qCfg.Name, req.fsName, -1)
++                              metrics.AddSeatsInQueues(req.ctx, qs.qCfg.Name, req.fsName, -req.MaxSeats())
 +                      }
 +                      // we need to check if the next request has timed out.
 +                      return true
 +              }
 +              // since reqs are sorted oldest -> newest, we are done here.
 +              return false
 +      })
 +
 +      // remove timed out requests from queue
 +      if timeoutCount > 0 {
 +              qs.totRequestsWaiting -= timeoutCount
 +              qs.totSeatsWaiting -= disqueueSeats
 +              qs.reqsGaugePair.RequestsWaiting.Add(float64(-timeoutCount))
 +              qs.seatDemandIntegrator.Set(float64(qs.totSeatsInUse + qs.totSeatsWaiting))
 +      }
 +}
 +
++=======
++>>>>>>> apf: remove timeoutOldRequestsAndRejectOrEnqueueLocked function
```

I have cherry-picked https://github.com/kubernetes/kubernetes/pull/119385 into 1.28, once this PR merges, i can cherry-pick https://github.com/kubernetes/kubernetes/pull/120222 which should be 100% clean

**Comment by wojtek-t** [comment]
Let's close the relevant PR and let's cherrypick both PRs in a single PR [as separate commits]
This is effectively what:
```
hack/cherrrypick_pull.sh upstream/release-1.28 119385 120222
```
would do

**Comment by tkashem** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/121006

**Pull request closed without merging**
