### PR TITLE
[WIP] Use Openstack native networking for inter pod communication 

### PR DESCRIPTION
**Pull request by timbyr**
Organise package into files based on functionality.

Implement Routes using Neutron ExtraRoutes extension.

Optimise LoadBalancer creation and removal by handling errors more efficiently.

Add floating IPs and security groups to LoadBalancer creation so k8s services can be externally exposed.

Configuration option to allow for hostname override with instance IP, this allows k8s to work without fqdn resolution, which is currently broken in neutron based deployments.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/19473)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Assigned to thockin to triage, prioritize and find a reviewer. cc @bprashanth

**Comment by thockin** [comment]
Any way to break up that second commit for easier review?

@anguslees for consult

**Comment by thockin** [comment]
@eparis if you're playing with the GH munger, can you figure out why this turns up as "XS" when it clearly isn't.

**Comment by anguslees** [comment]
@timbyr: First of all, thanks!  There's a lot of really great improvements in there, and I'm keen to get them merged asap.

In it's current form, this change is just about impossible to review, since combining the file restructuring with edits has completely broken the usefulness of side-by-side diffs.  It would be great if we could break this into a no-op restructure, followed by the separate logical changes you call out in your description (also since one or two of those overlap with other PRs in progress and so having them separate will make them easier to handle those merge conflicts).  You've done a lot of work here already, so I understand if you don't have the remaining time/energy to do that split - I'm happy to do the leg work at this point, just say the word.

**Comment by timbyr** [comment]
Can do! I was thinking there was at least 3 or 4 logical commits there and I have bandwidth to rework.

**Comment by eparis** [comment]
@kubernetes/rh-networking

**Comment by eparis** [comment]
Is this still active or should it be closed?

**Comment by timbyr** [comment]
@eparis  It can be closed.
Work is being broken up in different pull requests.

**Pull request closed without merging**
