### PR TITLE
job controller: don't mutate shared cache object

### LINKED ISSUE #100551: [Failing Test] k8s.io/kubernetes/test/integration/job.TestMain (ci-kubernetes-integration-master)
#### Which jobs are failing:
ci-kubernetes-integration-master

#### Which test(s) are failing:
k8s.io/kubernetes/test/integration/job.TestMain

#### Since when has it been failing:
https://github.com/kubernetes/kubernetes/compare/e71e284b7...d8193c950

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#integration-master

#### Reason for failure:
```
I0325 00:27:19.608278  130047 etcd.go:74] etcd already running at http://127.0.0.1:2379
FAIL	k8s.io/kubernetes/test/integration/job	64.998s
```

I can't seem to find a match for `test/integration/job` beyond that?

#### Anything else we need to know:
Most likely related to #100295 as it was merged during that set of commits

Example Spyglass link: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1374827993762893824

/cc @adtac 
/sig apps
/priority critical-urgent
/milestone v1.21

### PR DESCRIPTION
**Pull request by adtac**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

The Job controller has been mutating the shared cache for a loooong time, but I guess no one noticed this. When I tried to reproduce the failing integration test report https://github.com/kubernetes/kubernetes/issues/100551 locally, after several hours of very frustrating debugging, I noticed the mutation detector catching this bug. I believe this is also the true root cause of this bug, so to confirm this, I've modified the TestSuspendJob integration test to run _all_ subtests in pre-submit (previously, only the first subtest was run in pre-submit, the others were run in post-submit). If this PR's CI signals are green, we should be good.

#### Which issue(s) this PR fixes:

Fixes #100551

#### Special notes for your reviewer:

/cc @alculquicondor @soltysh @ahg-g 
/sig apps

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by palnabarun** [comment]
/milestone v1.21
/priority critical-urgent

since the issue being solved by this PR is in the milestone and is critical urgent

**Comment by ahg-g** [comment]
/lgtm

wow, good catch.

**Comment by ahg-g** [comment]
We should backport this as far back as we can

**Comment by adtac** [comment]
The following mutation was triggered and detected by the feature gate=true, suspend=true->false subtest: http://ix.io/2U3u/diff

As you can see the mutation is entirely within the .status.conditions[0] `Suspended` condition. IMO the bug has always been around for a long time and was constantly being triggered, but we didn't observe it until now because:

1. the mutation detector only runs on integration tests, and
2. none of the job controller integration tests do a job `Update()` (TestSuspendJob is the first integration test to do that)

These are just possible hypotheses, I'm not 100% sure.

**Review by soltysh — APPROVED** [review]
/approve

**Comment by alculquicondor** [comment]
+1 to cherrypicking

**Review by saschagrunert — APPROVED** [review]
Good, let's wait for this PR before cutting v1.21.0-rc.0 (https://github.com/kubernetes/sig-release/issues/1489)

**Comment by ialidzhikov** [comment]
> We should backport this as far back as we can

@adtac can you take care to backport this PR to the affected versions?

**Comment by ialidzhikov** [comment]
> > We should backport this as far back as we can
> 
> @adtac can you take care to backport this PR to the affected versions?

Ping @adtac @ahg-g 

/cc @janetkuo

**Comment by alculquicondor** [comment]
@ialidzhikov could you handle this?

See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md for instructions

**Comment by adtac** [comment]
I'll do this tomorrow :+1:

**Comment by adtac** [comment]
1.20: https://github.com/kubernetes/kubernetes/pull/104129
1.19: https://github.com/kubernetes/kubernetes/pull/104130
1.18: https://github.com/kubernetes/kubernetes/pull/104132
1.17: https://github.com/kubernetes/kubernetes/pull/104133

**Pull request merged**
