### PR TITLE
 Refactor kubeadm api validation.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
This PR refactor kubeadm api validation to use field json name. When users get a validation error, they can easily know which field is invalid in their config files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
@fabriziopandini I remember we mentioned this refactoring in some comment. I didn't see this change was done, so I send this PR to address this.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@xiangpengzhao thanks! fixing this is in my todo list but not not yet addressed.

I'm ok with the PR, but I'm wondering if it is possible to limit the changes to `validation.go` and `validation_test.go` only. WDYT?

**Comment by timothysc** [comment]
@liztio - can you please review.

**Review by timothysc — APPROVED** [review]
/approve 

letting others @liztio @fabriziopandini lgtm

**Comment by xiangpengzhao** [comment]
@fabriziopandini sorry for late response. The change in files other than `validation.go` and `validation_test.go` was intending to make the function signature more clear. Since this PR already get merged, let's leave it as-is :)

**Pull request merged**
