### PR TITLE
DeamonSet test expect daemons on unschedulable Nodes

### PR DESCRIPTION
**Pull request by gmarek**
Ref. #15803

This is the last test from the per-pr builder suite that needs to be fixed. Probably quite a lot of other ones will be broken.

cc @davidopp @bgrant0607 @wojtek-t

### CODE REVIEW

**Comment by roberthbailey** [comment]
This seems backwards -- why do we expect DaemonSet pods to be running on nodes that aren't marked as scheduleable? Shouldn't DaemonSet respect the unscheduleable field and skip those nodes?

**Comment by mikedanese** [comment]
@roberthbailey we decided that was a bad idea. We don't want to overload the unschedulable bit that way. See https://github.com/kubernetes/kubernetes/pull/14054#issuecomment-144229094

**Comment by roberthbailey** [comment]
Thanks for the clarification. Makes sense. Do we have a way for a kubelet to indicate that it is not "accepting" yet or is that still TBD?

**Comment by bgrant0607** [comment]
@roberthbailey It's TBD, but is probably subsumed by the taints/tolerations proposal: 
https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md

**Comment by roberthbailey** [comment]
Thanks, I'll take a look through that doc.

**Comment by davidopp** [comment]
My recollection is that we originally had DaemonSet respect unschedulable because that's how we identified the master, and running regular pods on the master didn't work (something about the CIDR allocation? I forget). But then we fixed things so that you can run pods on the master, so it isn't necessary to prevent daemons from running on the master. I guess if you don't want your daemon to run on the master, you can label the master node and put a selector on your DaemonSet so it avoids the master.

But as Mike and Brian alluded to, we plan to clean all of this up when we get some time.

**Comment by davidopp** [comment]
@k8s-bot e2e test this issue: #21995

(that issue is closed, but I think we don't need to reopen it because it went in after this e2e ran)

**Comment by mikedanese** [comment]
@davidopp I do not fixing the master's small cidr issue. The blocker was daemonset ignoring node capacity, which we did fix up.

**Comment by gmarek** [comment]
@mikedanese - PTAL at this PR fixing test when master is registered. It seems that daemon is correctly running on master node. OTOH if we want to prevent daemons from running on master, we probably should label master machine somehow, similarly to what we need to do with master pods: #21267.

**Comment by mikedanese** [comment]
LGTM. In e2e cluster it looks like the master cidr is a /24 which should be fine (was /30 last time i looked which broke daemonsets that selected the master).

**Comment by gmarek** [comment]
@k8s-bot test this issue: #IGNORE

infra failure

**Pull request merged**
