### PR TITLE
Note equivalence class for dev and other fix

### PR DESCRIPTION
**Pull request by resouer**
**What this PR does / why we need it**:
1. Add a note for predicate developers to respect equivalence class design
2. Add comments and re-ordered the related data structure, ref https://github.com/kubernetes/community/pull/1031
3. Fix some nits (typo, code length etc)

**Special notes for your reviewer**:

**Release note**:

```release-note
Scheduler predicate developer should respect equivalence class cache
```

### CODE REVIEW

**Comment by dims** [comment]
@resouer Please rebase

**Comment by resouer** [comment]
@dims Yes, just rebased!

**Comment by dims** [comment]
re-applying lgtm blown away by rebase

/lgtm

**Comment by resouer** [comment]
It seems `pull-kubernetes-federation-e2e-gce` is flaky.

**Pull request merged**
