### PR TITLE
[e2e_node] containers_lifecycle organize tests

### PR DESCRIPTION
**Pull request by dshebib**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
1. group related tests in containers_lifecycle so they are easy to find
2. break apart different tests into different test cases so they can be run in parallel

#### Does this PR introduce a user-facing change?
only changes e2e tests

```release-note
NONE
```

### CODE REVIEW

**Comment by dshebib** [comment]
/cc @pohly @BenTheElder @bart0sh 

Sorry for the large diff, but this will help when introducing shared Context. None of the tests should have been altered in any way.

**Comment by pohly** [comment]
/unassign

I'd like to leave this to SIG Node reviewers.

**Comment by haircommander** [comment]
FYI this is going to be tricky to review because it's quite large. It would be easier if it was broken up more, or if there was less code duplication between the two implementations.

**Comment by aojea** [comment]
my recommendation is that unless this refactor has a nice improvement over current state then is better to not do it, this code churn to move things around can cause subtle bugs and also make more difficult to bisect in case of problems

**Comment by pohly** [comment]
One possible alternative is to define helper functions which preserve the current indention of most code and then just reorganize how tests are registered by calling those helper functions.

I don't know whether this is applicable here. It is something that I have done elsewhere to avoid code churn.

**Comment by dshebib** [comment]
This PR now consists of only 2 commits: the first only adds ginkgo.When() to encase testcases (this should make it easier to share context and run together properly) and the second is from running gofmt on the resulting file.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

cc @impact-maker 

This PR makes things better. We will have more reorganization of it later with the https://github.com/kubernetes/kubernetes/issues/126369

**Pull request merged**
