### PR TITLE
Adds Windows support for etcd image

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind feature

/sig windows

**What this PR does / why we need it**:

We can use `docker buildx` in order to build and push Windows images from the same Linux node, as long as the Dockerfile does not have any `RUN` commands in the Windows step.

We also need to create a non-default builder instance in order to be able to build and push Windows images.

The Windows images have to be built and pushed directly to the registry.

For Windows containers without Hyper-V isolation, the host OS Version and the Container OS Version need to match, which is why we added multiple Windows OS Versions to the building process.

Adds support for Windows OS Versions: 1809, 2004, 20H2, 2022.

Bumped etcd image revision to 2.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The etcd container image now supports Windows.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
The k8s control plane does not run on windows, does it? What's the purpose of this?

**Comment by yliaog** [comment]
i think it is for e2e tests

**Comment by claudiubelu** [comment]
> 
> 
> i think it is for e2e tests

Yes, pretty much. There are some tests that require the etcd image. The test ``[sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]`` comes to mind, especially since it's a Conformance test.

**Comment by mkorbi** [comment]
Hello @claudiubelu
This PR has been updated frequently, but it looks like the merge is blocked/waiting for approval/lgtm, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.
As the PR is tagged for 1.20, is it still planned for this release?

**Comment by claudiubelu** [comment]
> 
> 
> Hello @claudiubelu
> This PR has been updated frequently, but it looks like the merge is blocked/waiting for approval/lgtm, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.
> As the PR is tagged for 1.20, is it still planned for this release?

Yes. Waiting reviews.

**Comment by mkorbi** [comment]
Hey @claudiubelu  short reminder, code freeze will be by today

**Comment by erismaster** [comment]
@claudiubelu Hi 👋🏽 I'm from the Bug Triage team. We've crossed the Code Freeze for 1.20 release on 12th November. As this PR is tagged with 1.20, I'm sending a final reminder to either move the milestone to 1.21 or clear the milestone.

**Comment by jeremyrickard** [comment]
👋 1.20 Release Lead here,  we're pretty late into code freeze at this point, so I'm going to bump this to 1.21. 

/milestone v1.21

**Comment by saschagrunert** [comment]
@claudiubelu @kubernetes/sig-windows-feature-requests do you see a way to move forward with this one? If not we probably have to close it.

**Comment by jsturtevant** [comment]
We merged support for other Windows images using buildx: https://github.com/kubernetes/kubernetes/pull/93889 so this is an accepted way forward.  I don't think we are blocked other than need of reviews and approval

/cc @chewong

**Comment by kcmartin** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (less than 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the PR is tagged for 1.21, is it still planned for this release?

**Comment by claudiubelu** [comment]
Image build logs with this PR: https://paste.ubuntu.com/p/wnrRRxxvjm/ (just fyi, forgot to bump revision number before running)

**Comment by erismaster** [comment]
@claudiubelu we are past code freeze, going to move this to 1.22

/milestone v1.22

**Comment by xmudrii** [comment]
@claudiubelu Is there any update on this PR? Is there anything that we can help with to move it forward?

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu Is there any update on this PR? Is there anything that we can help with to move it forward?

It has been ready to merge for a while now. I've only had to rebase it from time to time.

**Comment by marosset** [comment]
/milestone v1.23
/assign @jpbetz 

It looks like this PR has been ready to merge since v1.21 timeframe. 
Are there any outstanding issues with this PR that need to be addressed?

**Comment by jpbetz** [comment]
> /milestone v1.23
> /assign Joe Betz
> 
> It looks like this PR has been ready to merge since v1.21 timeframe.
> Are there any outstanding issues with this PR that need to be addressed?

I never got an answer to my original question: "The k8s control plane does not run on windows, does it? What's the purpose of this?" https://github.com/kubernetes/kubernetes/pull/92433#issuecomment-648180514

**Comment by jyotimahapatra** [comment]
Hi 👋 I'm the bug triage shadow. I wanted to check in and see if this is targeted for 1.23 milestone. 

Attempting to nudge the conversation forward, @claudiubelu I wanted to bring attention to a question asked earlier in the thread https://github.com/kubernetes/kubernetes/pull/92433#issuecomment-889326571 .

**Comment by marosset** [comment]
> > /milestone v1.23
> > /assign Joe Betz
> > It looks like this PR has been ready to merge since v1.21 timeframe.
> > Are there any outstanding issues with this PR that need to be addressed?
> 
> I never got an answer to my original question: "The k8s control plane does not run on windows, does it? What's the purpose of this?" [#92433 (comment)](https://github.com/kubernetes/kubernetes/pull/92433#issuecomment-648180514)

This is used in one of the e2e conformance tests.
`Kubernetes e2e suite.[sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]`
We need a Windows flavor of this image in order to run this test on Windows nodes.

**Comment by marosset** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L213
Is the test manifest

**Pull request merged**
