### PR TITLE
Fix admission webhook documentation typos

### PR DESCRIPTION
**Pull request by sporkmonger**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Addresses a small number of documentation typographical errors related to admission webhooks.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sporkmonger** [comment]
FWIW, I don't think this should be `kind/api-change` as it's purely a documentation PR.

**Comment by liggitt** [comment]
needs a rebase, lgtm otherwise

**Pull request closed without merging**
