### PR TITLE
migrate the rest reference of pkg/util/exec to k8s.io/utils/exec

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

There are still some reference of `pkg/util/exec`, need to migrate to `k8s.io/utils/exec`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
there's one more reference https://cs.k8s.io/?q=pkg%2Futil%2Fexec&i=nope&files=&repos=kubernetes/kubernetes

**Comment by danielqsj** [comment]
@dims thanks, cleaned

**Review by dims — APPROVED** [review]

**Comment by danielqsj** [comment]
@thockin  can you help review it? thanks

**Pull request merged**
