### PR TITLE
kubelet: Add container runtime option for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
3rd take (ugh...), waiting #7951 to be in first.

I am running e2e on gce/debian for this. Will report result.

/cc @vmarmol @dchen1107 @yujuhong

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, Did the cross-build come back clean?

**Comment by yifan-gu** [comment]
@vmarmol Yes. And e2e is good
```
Ran 38 of 43 Specs in 1451.809 seconds
I0508 02:14:04.531242    7668 driver.go:96] All tests pass
SUCCESS! -- 38 Passed | 0 Failed | 1 Pending | 4 Skipped 2015/05/08 02:14:04 Running: teardown
```

**Comment by vmarmol** [comment]
Sorry, I meant `hack/build-cross.sh`, but I ran it and it comes back clean :)

**Comment by yifan-gu** [comment]
@vmarmol NW, I think e2e runs release.sh which runs the cross building :)

**Pull request merged**
