### PR TITLE
Made some optimizations, including modifying variable names, omitting…

### PR DESCRIPTION
**Pull request by changshuchao**
… unnecessary parentheses, and conflicting variable names and package names.

Signed-off-by: changshuchao <chang.shuchao1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/release-note-none
/priority backlog

What is the reason for these improvements? Are they flagged by some linter?

**Comment by changshuchao** [comment]
@SergeyKanzhelev , Yes, this is not necessary, but it will make the code look more standardized :)

**Comment by changshuchao** [comment]
@ehashman  Hey, i need lgtm label ,thx!

**Comment by SergeyKanzhelev** [comment]
/lgtm

those a very minor code cleanups. Since tests were run for them anyway, let's just have it. @changshuchao please review our PR policy on [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) before your next PR submission.

**Comment by changshuchao** [comment]
ok,i will. Thanks btw    : )

**Comment by changshuchao** [comment]
@ehashman Hey, i need approve label ,thx!

**Pull request merged**
