### PR TITLE
test: Only trigger GPU Upgrade e2e on gce/gke.

### PR DESCRIPTION
**Pull request by ruquanzhao**
Signed-off-by: Ruquan Zhao <ruquan.zhao@arm.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
These tests will call:
```
test/e2e/cloud/gcp/common/upgrade_mechanics.go
    ControlPlaneUpgradeFunc()
      * controlPlaneUpgrade()
    ClusterUpgradeFunc()
      * controlPlaneUpgrade()
      * nodeUpgrade()
    ClusterDowngradeFunc()
      * nodeUpgrade()
      * controlPlaneUpgrade()
```
All [*] func is only implemented on `providers [gce, gke]`.
So it will raise failures on other `providers` such as `local`.
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ruquanzhao** [comment]
@justinsb @cheftako 
Can you please take a look？Thanks

**Comment by aojea** [comment]
> /cc @aojea can you pls take a look? is that change make sense to you?

it makes sense but not familiar with these tests at all, I don't know how they are triggered

> @justinsb @cheftako Can you please take a look？Thanks

I defer to them, they should know better, maybe @BenTheElder is familiar with these too

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
