### PR TITLE
Use physical memory for stats of kubelet

### PR DESCRIPTION
**Pull request by adam-jian-zhang**
This is a hack to make kubelet use physical memory for calculate memory usage of the node without changing the data structure which only accounts private working set and commited pages. We patch the second to include the difffrom phsical available memory to the sum of private working set and commited pages. After the change,
memory usage = memoryPrivWorkingSetBytes + memoryCommittedBytes
	     = totalPhys - AvailPhys

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

https://github.com/kubernetes/kubernetes/issues/112111

#### Does this PR introduce a user-facing change?

```release-note
Use physical memory for kubelet stats for windows nodes. After the change, 
memory usage(for windows node) = memoryPrivWorkingSetBytes + memoryCommittedBytes = totalPhys - AvailPhys 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
@adam-jian-zhang do you have a corresponding issue to link to?

**Comment by matthyx** [comment]
This looks like a WIP, please change it to Draft and ping me when we can review it. Thanks!

**Comment by adisky** [comment]
/ok-to-test
@adam-jian-zhang can you update the PR title that it is windows specific also link the issue in PR description

**Comment by adam-jian-zhang** [comment]
> @adam-jian-zhang do you have a corresponding issue to link to?

https://github.com/kubernetes/kubernetes/issues/112111

More background:
We had a customer reported the issue the way kubelet windows handles memory caused windows worker node reporting different memory usage with their monitoring tool and in some case cause the node to go unresponding due to kubelet try to allocate pods to already full node, and cause cascading failure to entire cluster.

The code in this PR is an attempt to fix the issue by using physical memory to do scheduling. We provided dev build for  customer to test, and customer have reported the result are better than before, and wishes a fix from upsteam instead a dev build.

**Comment by matthyx** [comment]
ok... please add a release note too
/sig windows

**Comment by marosset** [comment]
@pbozzay - Do you have any thoughts on which memory stats Windows containers should be reporting?
There are a few different options and none of them map 1:1 with what is being reported for Linux

**Comment by marosset** [comment]
Let's discuss at an upcoming SIG-Windows community meeting. (@brasmith-ms FYI)
/milestone v1.27

**Comment by valaparthvi** [comment]
Hello @adam-jian-zhang! I'm from the K8s 1.27 release team (more specifically the bug-triage team). I am checking in to see if this PR is on track for 1.27.

**Comment by bart0sh** [comment]
This PR requires SIG-windows review. assigning reviewers.

/assign @jayunit100 @jsturtevant @marosset

**Comment by valaparthvi** [comment]
Hi @adam-jian-zhang, @kubernetes/sig-windows-leads. I am from the Bug Triage Shadow team for K8s release v1.27.
With Code Freeze coming in on March 15, please ensure the PR goes in before that if you would like for it to be a part of v1.27 release. Post Code Freeze, we will only be able to accept Release Blockers and Critical issues.

**Comment by ffromani** [comment]
> > /assign @matthyx
> 
> I don't have a particular opinion on that, @ffromani WDYT?

DISCLAIMER: I only glanced at the code and I'm not a windows expert
From the PR discussion and cover letter it seems to me windows wants/needs to do accounting differently. I think we should avoid hacks: either this approach is correct/acceptable according to windows standards (therefore is not an hack! let's just rephrase the PR description and code comments) or we should go the extra mile and implement the clean approach windows requires.

**Comment by jsturtevant** [comment]
sig-windows is looking into the change, we are consulting with some Windows internal folks before making the change

**Comment by Howard-Haiyang-Hao** [comment]
memory usage = memoryPrivWorkingSetBytes + memoryCommittedBytes is kind of missing the Virtual memory concepts and physical memory concepts. I am not sure if we want to show the the application virtual memory usage or the physical memory usage.

**Comment by dims** [comment]
> sig-windows is looking into the change, we are consulting with some Windows internal folks before making the change

/hold for ⬆️

**Pull request closed without merging**
