### PR TITLE
Automated cherry pick of #88006: Unregister csiplugin even if socket path is gone #89934: Simplify unregistration of csiplugin

### LINKED ISSUE #87282: kubelet can't unregister csiplugin after csiplugin pod is deleted from node
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
Cherry pick of #88006 #89934 on release-1.17.

#88006: Unregister csiplugin even if socket path is gone
#89934: Simplify unregistration of csiplugin

/kind bug

Fixes #87282

```release-note
NONE
```
/sig node

### CODE REVIEW

**Comment by tedyu** [comment]
@saad-ali
Can you approve this ?

**Comment by tedyu** [comment]
@saad-ali
Can you approve this ?

**Comment by tpepper** [comment]
@saad-ali we're out of sync between branches.  Did intentionally not lgtm/approve this for 1.17 where you did for 1.18 (https://github.com/kubernetes/kubernetes/pull/90125)?  We should either merge this one also or close it.

**Comment by ehashman** [comment]
@tpepper where are we with this? Should I look for an approver or does it matter at this point (since I think 1.17 has fallen out of support)?

**Comment by cpanato** [comment]
The last patch release for 1.17 is scheduled for [01.13.2021](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#117) and we will not accept more cherry-picks for this branch and the cherry-pick deadline for the upcoming patch release is over.

closing this CP.

/close

**Pull request closed without merging**
