### PR TITLE
controller: drop extra rs deep-copy

### PR DESCRIPTION
**Pull request by 0xmichalis**
@janetkuo @mwielgus

### CODE REVIEW

**Comment by kargakis** [comment]
Not needed because we already deep-copy before updateReplicaSetStatus
https://github.com/kubernetes/kubernetes/blob/34a15408286ccd4e875004798298f4ffc3573882/pkg/controller/replicaset/replica_set.go#L609

**Comment by ethernetdan** [comment]
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by kargakis** [comment]
@kubernetes/test-infra-maintainers tests shouldn't rerun automatically for PRs that are not destined for the next milestone.

**Comment by kargakis** [comment]
@k8s-bot verify test this

**Pull request merged**
