### PR TITLE
AWS kube-up: Allow VPC CIDR to be specified (experimental)

### PR DESCRIPTION
**Pull request by miguelfrde**
Hey @justinsb regarding the question I asked on Slack that @gy8 pointed me to a previous conversation between you and him. Here's a simple fix to allow to configure the base VPC CIDR.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23362)

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
I'm going to re-assign to justin. It is 'fine' in my eyes. I don't like the whole base/cidr implementation and don't love exposing that to a user. Then again, I don't use the AWS stuff, so I'm not going to force 3 env vars that suit my tastes.

**Comment by dengshuan** [comment]
I think it's better to just expose `VPC_CIDR` and `SUBNET_CIDR` as environment variable here instead of `VPC_CIDR_BASE`. Because what if someone else want to change vpc cidr suffix, do we need to add another variable `VPC_CIDR_SUFFIX` and let users configure it.
So I'd suggest to change [these lines](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L105-L108) to
```
MASTER_IP_SUFFIX=.9   # Currently I'm not sure if this is important and configurable
VPC_CIDR=${VPC_CIDR:-172.20.0.0/16}
SUBNET_CIDR=${SUBNET_CIDR:-172.20.0.0/24}
```

**Comment by ajohnstone** [comment]
Agree with @dengshuan so that the cidr range can be adjusted. Would be nice to get this released as currently sed'ing the files.

**Comment by ajohnstone** [comment]
After looking at closer, this should ideally aid in configuring the following... otherwise a number of other issues will occur. Or at least documentation should highlight when configuring this option.

```
export NON_MASQUERADE_CIDR="172.16.0.0/14"
export SERVICE_CLUSTER_IP_RANGE="172.16.0.0/16"
export DNS_SERVER_IP="172.16.0.10"
export MASTER_IP_RANGE="172.17.0.0/24"
export CLUSTER_IP_RANGE="172.18.0.0/16"
```

**Comment by justinsb** [comment]
I think this is the right place to start; we'll consider it experimental for the moment, but people do need this.

**Pull request merged**
