### PR TITLE
kubelet: Fix log directory path for long pod names

### PR DESCRIPTION
**Pull request by rphillips**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Creating a directory name over 255 characters will fail due to filesystem limitations limiting names to 255 characters. Trim the podName to allow the namespace and UID to be inserted.

ref: https://github.com/kubernetes/kubernetes/pull/74441
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711544

**Special notes for your reviewer**:
/cc @Random-Liu @dashpole @sjenning @derekwaynecarr 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rphillips** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by derekwaynecarr** [comment]
well, obviously we can’t have names that are too long... do we know if this will confuse any collectors?

**Comment by Random-Liu** [comment]
Based on Kubernetes naming convention, any name can be as long as 253 https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

We also have the symlink `/var/log/containers/<pod_name>_<pod_namespace>_<container_name>-<container_id>.log`, that seems to be an even longer name...

I think splitting name, namespace, uid into sub-directories seem to be a safer solution, but we need to handle backward compatibility.

**Comment by yujuhong** [comment]
> well, obviously we can’t have names that are too long... do we know if this will confuse any collectors?

Hmm...some logging agents parse the pod metadata from the path. This will affect them (even though realistically that the logs of such pods may have never been collected correctly)

**Comment by rphillips** [comment]
I investigated the code some more. Container GC's `evictPodLogsDirectories` enumerates the log files and deletes stale log directories based on parsing the log directory name for the UID. We should preserve this functionality across a fix we come up with.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L343

**Comment by Random-Liu** [comment]
What do we think about splitting name, namespace, uid into sub-directories?

That requires carefully handling backward compatibility, but I think it is doable. I've done it once https://github.com/kubernetes/kubernetes/pull/74441

**Comment by rphillips** [comment]
Closing this PR in favor of the issue:

https://github.com/kubernetes/kubernetes/issues/80042

**Pull request closed without merging**
