### PR TITLE
Bump docker/docker dep

### PR DESCRIPTION
**Pull request by jamiehannaford**
**What this PR does / why we need it**:

Bumps docker/docker dependency to use latest changes, notably new logging types added in https://github.com/moby/moby/pull/32914.

**Which issue(s) this PR fixes**:

Paves the way for https://github.com/kubernetes/features/issues/253.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jamiehannaford** [comment]
@dchen1107 @thockin Seems the CI is complaining about a Docker dep not being installed (`github.com/containerd/continuity/pathdriver`). I can't seem to get this installed, though. These are the steps I ran:

```
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/docker/docker'
hack/run-in-gopath.sh go get -d github.com/docker/docker
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/docker/docker checkout master'
hack/run-in-gopath.sh bash -c 'cd $GOPATH/src/github.com/docker/docker && vndr'
hack/run-in-gopath.sh hack/godep-save.sh
```

After doing this, `github.com/containerd/continuity/pathdriver` exists in `_output/local/go/src` but not `vendor`. Did I miss anything out?

**Comment by liggitt** [comment]
What versions of docker is the bumped level compatible with? Does it drop support for any currently supported versions?

**Comment by jamiehannaford** [comment]
> What versions of docker is the bumped level compatible with?

The engine API version for this new commit is v1.35. They have not pulled in this changeset into a docker-ce release yet, but I assume that will happen soon. (cc @thaJeztah)

> Does it drop support for any currently supported versions?

Not that I'm aware of, no. I was assuming the tests would catch any compatibility breaks, but as stated above, a required dependency isn't being installed. Do you know why that might be?

**Comment by liggitt** [comment]
> I was assuming the tests would catch any compatibility breaks

I don't know if automated CI runs against all supported versions

**Comment by thaJeztah** [comment]
API v1.35 has indeed not been in a Docker release yet; current API version for "edge" is 1.33, upcoming 17.11 edge release will be 1.34. When using the API it's recommended to pin to a specific version if possible (and use version negotiation)

I see some changes related to the jsonfile reader; probable related to https://github.com/moby/moby/pull/34162 and https://github.com/moby/moby/pull/34946

/cc @cpuguy83 @dnephin

**Comment by thockin** [comment]
Assign back to me once it is LGTM'ed and ready for approval.

**Comment by yujuhong** [comment]
@jamiehannaford kubelet no longer serves the logs through docker (except for the journald log driver, which we are working on to deprecate).When using the the json-file log driver, kubelet reads the log file directly to serve `kubectl logs` requests. To add the support, you need to change the "kubelet" code in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go

@kubernetes/sig-node-feature-requests 
@kubernetes/sig-node-pr-reviews

**Comment by dchen1107** [comment]
I am ok to bump docker dep if required. But the pr description indicates that this is for kubectl logs, which is unnecessary for now. Kubelet removed the dependency on docker logs when serving kubectl logs since 1.7(?) release.

**Comment by jamiehannaford** [comment]
@yujuhong @dchen1107 Ah okay, thanks for the pointers. I'll do the updates for `--until` there instead. Do you feel bumping the Docker dep is a nice-to-have anyway? If not, I can close this out.

**Comment by jamiehannaford** [comment]
Closing as this is no longer necessary. Can resurrect if there's a need down the line.

**Pull request closed without merging**
