### PR TITLE
tests: Refactor agnhost image pod usage - network

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

A previous commit added  a few agnhost related functions that creates agnhost pods / containers for general purposes.

Refactors tests to use those functions.

**Which issue(s) this PR fixes**:

Fixes #
Depends On: #87266

**Special notes for your reviewer**:

/cc @alejandrox1 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by alejandrox1 — COMMENTED** [review]
Looks good though it'll need a rebase after https://github.com/kubernetes/kubernetes/pull/87266 goes in

/priority backlog

**Comment by alejandrox1** [comment]
thought it would need a rebase but i guess not.
gonna rerun ci to see if the prev failures were flakes while I do another review

prev failures
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94595/pull-kubernetes-conformance-kind-ipv6-parallel/1308762268007141376/
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94595/pull-kubernetes-e2e-kind-ipv6/1308762268116193280
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94595/pull-kubernetes-e2e-kind/1308762268091027456
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94595/pull-kubernetes-bazel-test/1308762267981975552
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94595/pull-kubernetes-e2e-gce-ubuntu-containerd/1308762268053278720/

/rerun

**Comment by alejandrox1** [comment]
ha the command is not rerun
/retest

**Review by alejandrox1 — COMMENTED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
hi folks, I couldn' t investigate deeper but looks like this PR broke the DNSConfigmap tests
https://k8s-testgrid.appspot.com/sig-network-kind#sig-network-kind,%20master

**Pull request merged**
