### PR TITLE
Update kube-openapi to 15aac26d736a

### PR DESCRIPTION
**Pull request by apelisse**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update to use lazy serialization in kube-openapi. This doesn't actually do anything lazy yet because we need another update that I'll push soon.

#### Which issue(s) this PR fixes:
Expected 15%-ish improvement in memory usage for "unused" k8s clusters.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```
yet

### CODE REVIEW

**Comment by apelisse** [comment]
Uses most recent version of kube-openapi.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by cheftako** [comment]
/lgtm
/approve
Cloud provider piece looks fine.

**Pull request merged**
