### PR TITLE
e2e: fix flaky test 'should contain OpenAPI V3 for Aggregated APIServer'

### LINKED ISSUE #117443: Flaky Test - should contain OpenAPI V3 for Aggregated APIServer
The test fails because there are 2 different tests creating the same aggregated apiserver with the same name

https://github.com/kubernetes/kubernetes/blob/658ea4b59142f1442627b0ee46dd1a917e3aa766/test/e2e/apimachinery/openapiv3.go#L135-L141

https://github.com/kubernetes/kubernetes/blob/df5d84ae811bc119e715ee39dafea5067dd32f77/test/e2e/apimachinery/aggregator.go#L86-L90

so, when they run at the same time, one of them fails because the object already exist.

The solution can be to run those jobs serially (under the same ginkgo block) or just a different name for each test

##### Error text:
```
[FAILED] creating apiservice v1alpha1.wardle.example.com: apiservices.apiregistration.k8s.io "v1alpha1.wardle.example.com" already exists
In [It] at: test/e2e/apimachinery/aggregator.go:358 @ 04/12/23 22:07:23.204

```
#### Recent failures:
[14/04/2023, 21:54:17 pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117371/pull-kubernetes-e2e-gce/1646965089519013888)
[13/04/2023, 11:19:16 pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117282/pull-kubernetes-e2e-gce/1646442899551817728)
[12/04/2023, 15:45:04 pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116593/pull-kubernetes-e2e-gce/1646147133046263808)

/kind failing-test
/kind flake

/sig api-machinery

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

If applied this commit will deflake the [e2e test](https://github.com/kubernetes/kubernetes/blob/658ea4b59142f1442627b0ee46dd1a917e3aa766/test/e2e/apimachinery/openapiv3.go#L135-L165) "should contain OpenAPI V3 for Aggregated APIServer"

#### Which issue(s) this PR fixes:

Fixes #117443

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
Hello @aojea,
I tried to go with the simplest way without too messing with the e2e code with which I am still not comfortable yet. If I misunderstood something or if you do not feel comfortable with this PR, please let me know.
I'll take time tomorrow to rebuild and re-run all the apimachinery e2e tests on a better computer.
Remaining at your disposal.

Best,

**Comment by aojea** [comment]
/ok-to-test

This duplication seems to be added here, please see https://github.com/kubernetes/kubernetes/issues/117443 for context
/assign @apelisse @lavalamp @Jefftree

**Comment by TommyStarK** [comment]
@aojea , I am giving another try but it seems my simple solution is not that simple. Giving a different name for the testOpenAPI V3 Aggregated server is not going to be that easy. Test seems coupled with this [pkg](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1). I keep digging to understand how it works under the hood. Also figuring out if those [files](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver/artifacts/example) are used. Will ask for help if I cannot find my way alone

**Comment by TommyStarK** [comment]
@aojea , I am giving another try but it seems my simple solution is not that simple. Giving a different name for the testOpenAPI V3 Aggregated server is not going to be that easy. Test seems coupled with this [pkg](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1). I keep digging to understand how it works under the hood. Also figuring out if those [files](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver/artifacts/example) are used. Will ask for help if I cannot find my way alone

**Comment by apelisse** [comment]
Have you tried pinging the people who know the most about this? @Jefftree @alexzielenski

**Comment by apelisse** [comment]
Oh I see Jeff was pinged, good :-)

**Comment by TommyStarK** [comment]
Yes we did :) At your disposal if there is any change to make

**Comment by TommyStarK** [comment]
Yes we did :) At your disposal if there is any change to make

**Comment by Jefftree** [comment]
Thanks for the fix! This is definitely better than forcing the two tests to run in serial. 

LGTM

**Comment by Jefftree** [comment]
I think it makes sense to also backport this to v1.27 once merged.

**Comment by TommyStarK** [comment]
If you want me to create the cherry-pick to backport it to 1.27, please tell me :) Thank you for the review

**Comment by TommyStarK** [comment]
CI failure does not seem to be related with my changes

Screenshot 2023-04-19 at 19 56 49

/retest-required

**Comment by TommyStarK** [comment]
CI failure does not seem to be related with my changes

Screenshot 2023-04-19 at 19 56 49

/retest-required

**Comment by aojea** [comment]
Thanks

**Pull request merged**
