### PR TITLE
Use the v1.12 branch by default

### PR DESCRIPTION
**Pull request by timothysc**
Final update for kubeadm 1.12 default switching. 

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-release-members 
/assign @tpepper 
/lgtm 
/approve 

@tpepper unhold when ready to cut RC!

### CODE REVIEW

**Comment by timothysc** [comment]
/test pull-kubernetes-bazel-test
/test pull-kubernetes-integration

Just as a reminder, merging this change will make some tests fail for a while until release is actually cut.

**Comment by timothysc** [comment]
Hah, the test failure highlights my previous message  
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.12.txt", status: 404 Not Found

**Comment by tpepper** [comment]
Do we normally force push this patch?  Ie: that endpoint really doesn't resolve until 1.12.0 tag is pushed.  Looks like comparable last time didn't need that: https://github.com/kubernetes/kubernetes/pull/65229

**Comment by neolit123** [comment]
@timothysc 
do we have to also bump the version in `kubeadm/v1alpha2/defaults.go`?

**Comment by neolit123** [comment]
@tpepper 
> Do we normally force push this patch? Ie: that endpoint really doesn't resolve until 1.12.0 tag is pushed. Looks like comparable last time didn't need that: #65229

v1.11.0 was tagged ~10 days after https://github.com/kubernetes/kubernetes/pull/65229 was merged.
not sure how that worked. :thinking:

**Comment by neolit123** [comment]
/lgtm cancel
to stop the bot auto-testing, for now

/hold
we need to sync with sig-docs on when the reference docs are generated.
we also need to understand why the endpoint is still missing. in previous cycles it seems that this PR is viable for RC1.

**Comment by tpepper** [comment]
I can't find any discussion in Slack history, but I feel like somebody may have done something back in June to magically fix this?

**Comment by AishSundar** [comment]
/cc @jberkus 

May be @jberkus can provide some insight of how this went in 1.11?

**Comment by timothysc** [comment]
This one should be good to go and if we need to cherry-pick an update later in 1.13 it should be ok.

**Comment by AishSundar** [comment]
@timothysc did you mean cherrypick into 1.12 ?

**Comment by timothysc** [comment]
self re-applying, we need to get this through.

**Comment by dims** [comment]
/lgtm 

Ack @timothysc

**Pull request merged**
