### PR TITLE
RFC: Add explicit capabilities to E2E tests

### PR DESCRIPTION
**Pull request by timstclair**
**Problem this PR fixes**

Tests should be explicit and dumb, otherwise you need tests for your tests. We have a lot of logic in our E2E's today that autodetects whether certain features (capabilities) are present, and tests them if they are, or skips the test if they're not (examples below). But what happens if there's a bug in the detection logic? Tests could be skipped (a.k.a. "passing") for a long time before anyone notices.

Examples:
- [AppArmor](https://github.com/kubernetes/kubernetes/blob/1e5e4fdb9d3dcd0e39a57e56eb9d71368673ba97/test/e2e_node/apparmor_test.go#L40)
- [Federation](https://github.com/kubernetes/kubernetes/blob/1e5e4fdb9d3dcd0e39a57e56eb9d71368673ba97/test/e2e/framework/util.go#L422)
- [sysctls](https://github.com/kubernetes/kubernetes/blob/1e5e4fdb9d3dcd0e39a57e56eb9d71368673ba97/test/e2e/common/sysctl.go#L103)

**What this PR does**

This adds a set of explicit capabilities to the `TestContext`, and 2 framework methods to check those capabilities:
- `framework.RunWithCapability(cap)` - Only run the test if the capability is present
- `framework.RunWithoutCapability(cap)` - Only run the test if the capability is NOT present

The examples above would check for capabilities like `"AppArmor"`, `"sysctls"`, `"Federated"`, and skip the tests as needed.

This makes the capabilities explicit, and moves the decisions into the test spec, so there are fewer opportunities for accidentally skipping tests.

As an example, I piped capabilities through to the node e2e image specs, and converted the AppArmor tests to use them. If we like this direction, we need to: pipe flags through cluster e2e tests, add some flags for manual testing, and convert more tests to use capabilities rather than auto detection.

**FAQ**
- _What about the [Feature:Foo] labels?_ - This would require a bunch of raw string parsing and having a central list of all the features. It also would require some hackery to make the `focus` and `skip` ginkgo flags continue to work. Also, see the examples above, these aren't sufficient.
- _Capabilities is an overloaded term! makes me think Linux capabilites!_ - It's a lot less overloaded than "Features", but let me know if you have a better idea.
- _So I need to list all the capabilities when I run tests?_ - If we move forward with this, I propose adding an optional `--autodetect-capabilities` flag for manual testing that performs all the autodetect logic we have today.
- _Why not SkipWith(out)Capability?_ - I thought the positive made the relationship a little clearer. Open to suggestions here...

Addresses https://github.com/kubernetes/kubernetes/issues/29346

@kubernetes/sig-testing @kubernetes/sig-node @Random-Liu

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33706)

### CODE REVIEW

**Comment by spiffxp** [comment]
I guess I still have a tough time seeing how this is different than the `[Feature:Foo]` labels.  In a way this seems like a potentially more flexible way of describing the same thing, since we're leaning less on stringly typed conventions?

**Comment by timstclair** [comment]
It's just another way of expressing the same thing. If we had a master list of all the features, and figured out which features were missing from the suite + the negative of the features that are present, and skip all those, and join that skip with the user provided skip (or `[Flaky]` `[Serial]`, etc.), that would also work. I think the regex to express all that get's pretty messy, and requires more regex string parsing than I'd like.

My approach here is just adding another nob to express the same thing more directly.

**Comment by fejta** [comment]
@k8s-bot gke e2e test this

**Comment by fejta** [comment]
@jayunit100 any thoughts about this? want to do this review?

**Comment by spiffxp** [comment]
@timstclair I guess what I was trying to say was it seems like your way is better, why wouldn't we just start using that instead of crazy regexes.  The less complex we can make testing's surface area, the better.

but I'll also defer to @jayunit100 since he tried to help us push the tags a bit more formally

**Comment by timothysc** [comment]
reassigning, b/c @jayunit100 doesn't have acls.

**Comment by fejta** [comment]
@timothysc what do you mean by acls? If you're assigned you should be able to /lgtm

**Comment by timothysc** [comment]
@fejta ohh.. I didn't know.. adding him back then.

**Comment by timstclair** [comment]
This was automatically closed for lack of activity. I don't have the bandwidth to push it to completion right now. If anyone does, please take ownership of these changes. /cc @kubernetes/sig-testing-pr-reviews

**Comment by spiffxp** [comment]
I'm in the same boat, will /cc @kubernetes/sig-testing-feature-requests to see if that makes this easier to find in the noise down the line

**Pull request closed without merging**
