### PR TITLE
expose common name validation methods

### PR DESCRIPTION
**Pull request by deads2k**
Expose common object name validation methods for downstream use.

### CODE REVIEW

**Comment by smarterclayton** [comment]
David is putting in place general tests and behaviors that (post 1.0) can be used to ensure all rest objects are being correctly validated.

**Comment by krousey** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release.  Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0.  We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why.  We're currently accepting changes that meet any of the following criteria:
   1. Changes directly related to v1.0 issues: https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0
   2. Changes addressing P0 bugs: https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0
   3. Changes to supported platforms to bring them up to par with the primary development platforms
   4. Docs, user experience, and test related fixes

Thanks again for your contribution!  The community is really what has made this project so exciting.

**Comment by mbforbes** [comment]
(Unsure whether you'd rather not have an assignee given this is v1.0-post, but assigning @smarterclayton for PR consistency.)

**Comment by deads2k** [comment]
rebased

**Comment by deads2k** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
