### PR TITLE
use multi-arch busybox for e2e

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Since [multi-arch is supported already for Official images on Dockerhub](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/), we can use `busybox` directly instead of having our own `GetBusyBoxImage` for multi-arch. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
xref #53958

**Special notes for your reviewer**:
/assign @mkumatag @ixdy 

**Release note**:

```release-note
Use multi-arch busybox image for e2e
```

### CODE REVIEW

**Comment by dixudx** [comment]
@mkumatag Per [our discussion](https://github.com/kubernetes/kubernetes/pull/53958#issuecomment-336941576), I think we can update `busybox` in our e2e as well.

**Comment by ixdy** [comment]
/ok-to-test
/approve

Seems fine to me. @mkumatag @luxas you agree?

**Review by mkumatag — APPROVED** [review]
LGTM

**Comment by dixudx** [comment]
ping @quinton-hoole @shashidharatd for approval. Thanks.

**Comment by shashidharatd** [comment]
/lgtm
Please fix the rebase issue. will apply the lgtm again. Thanks !

**Comment by dixudx** [comment]
@shashidharatd Rebased. PTAL.

**Comment by shashidharatd** [comment]
/lgtm
federation pre-submit is failing due to some infra issue and not related to the PR.

**Comment by luxas** [comment]
Thanks @dixudx!

**Pull request merged**
