### PR TITLE
fix typo about volumes

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
@nickrenren @vishh
for  approve !thanks

**Comment by NickrenREN** [comment]
thanks  for fixing  this 

/approve no-issue

**Comment by jianglingxia** [comment]
/assign @vishh
for your approve thanks

**Comment by jianglingxia** [comment]
/assign @vishh
PTAL,for your approve thanks very much

**Comment by jianglingxia** [comment]
sorry，please label  
/approve no-issue
thanks！ @vishh

**Comment by jianglingxia** [comment]
thanks very much for you @NickrenREN ,but maybe need @vishh  /approve no-issue，otherwise the CI don't label approved label?

**Comment by NickrenREN** [comment]
yeah, it is true. 
btw, bot already knows that vishh has approved, do not know why it does not add approve label.
```
This pull-request has been approved by: FengyunPan, NickrenREN, jianglingxia, vishh

No associated issue. Update pull-request body to add a reference to an issue, or get approval with /approve no-issue

The full list of commands accepted by this bot can be found here.

详细信息
Needs approval from an approver in each of these OWNERS Files:
pkg/cloudprovider/providers/openstack/OWNERS [NickrenREN]
pkg/kubelet/OWNERS [vishh]
```

**Comment by NickrenREN** [comment]
@jianglingxia  maybe you can add a bogus issue and modify the first comment ( add `fixes...`) so that you do not need to bother @vishh again.

**Pull request merged**
