### PR TITLE
Automated cherry pick of #117586: Add DisruptionTarget condition when preempting for critical

### PR DESCRIPTION
**Pull request by mimowo**
Cherry pick of #117586 on release-1.26.

#117586: Add DisruptionTarget condition when preempting for critical

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Add DisruptionTarget condition to the pod preempted by Kubelet to make room for a critical pod
```

### CODE REVIEW

**Comment by mimowo** [comment]
Note: here I had to resolve conflicts as Context wasn't passed to gingko test functions in 1.26. Thus, I pass the TODO context here: https://github.com/kubernetes/kubernetes/pull/118221/files#diff-94cfb00d75a10103bd0a3476b3db35446dbde4c4050913210445023abad3ae38R124. This is an analogous to the other pre-existing test in the file.

**Comment by SergeyKanzhelev** [comment]
/lgtm cancel

new tests are failing. Trying the test again, but it passed on 1.27 meaning that it may be a real issue

/test pull-kubernetes-node-kubelet-serial-pod-disruption-conditions

**Comment by SergeyKanzhelev** [comment]
re-run also failed. @mimowo can you please take a look?

**Comment by mimowo** [comment]
/pull-kubernetes-node-kubelet-serial-pod-disruption-conditions

**Comment by mimowo** [comment]
@SergeyKanzhelev thanks for testing, after setting the expected phase to Failed in the commit the test passed.

The test was failing as the phase expected in this test is Succeeded (on master). This is after https://github.com/kubernetes/kubernetes/pull/115331, which determines the phase based on the status of the container exit codes (https://github.com/kubernetes/kubernetes/blob/11067ceb328cb2b133af24431df63670d2f73b25/pkg/kubelet/kubelet_pods.go#L1473). In this test a sleep container is used with exits with 0 when receiving SIGTERM. Prior to that the phase was set to Failed independently of the container exit codes in https://github.com/kubernetes/kubernetes/blob/11067ceb328cb2b133af24431df63670d2f73b25/pkg/kubelet/preemption/preemption.go#L106. 

These phase changes don't matter for adding of the condition so I think it is safe to continue with cherry-pick. 

That being said, we have missed this scenario when reviewing the impacted scenarios (see release notes in https://github.com/kubernetes/kubernetes/pull/115331). Thus, I open an issue to discuss if the setting of phase is correct and clean up the code if it is: https://github.com/kubernetes/kubernetes/issues/118310

**Comment by mimowo** [comment]
/skip

(new tests are passing after the manual phase adjustment in https://github.com/kubernetes/kubernetes/compare/5d3f7feb709357f45adf8b890c13048911ec9fc3..b935de6df5447cbb749fb8d7e6dad0bcb01992a4)

**Review by Verolop — APPROVED** [review]
/lgtm

**Pull request merged**
