### PR TITLE
[WIP] testing Integration testserver

### PR DESCRIPTION
**Pull request by aojea**

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kubernetes-integration


hmm, does this reproduces the hang?

**Comment by aojea** [comment]
> ```
>         goroutine 2894 [select]:
>         k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).dispatchEvents(0xc008773600)
>         	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/
>     teardown_test.go:63: expected 20493 or fewer, got 20887
> --- FAIL: TestTestingAPIServerCleanTeardown (16.22s)
> ```
> 
> the test starts with 20493 goroutines XD

and :smile: 

```
I0228 16:08:18.717329  222515 watch_cache.go:566] Replace watchCache (rev: 1594) 
I0228 16:08:18.726192  222515 cacher.go:411] cacher (*core.ServiceAccount): initialized
I0228 16:08:18.726728  222515 watch_cache.go:566] Replace watchCache (rev: 1594) 
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

https://github.com/golang/go/issues/38184

**Comment by fedebongio** [comment]
/triage accepted
@aojea let us know when it's ready Thanks!

**Pull request closed without merging**
