### PR TITLE
Add datapolicy tags to  pkg/kubelet/

### PR DESCRIPTION
**Pull request by serathius**
/kind feature

**What this PR does / why we need it**:
This PR adds "datapolicy" tags to golang structures as described in [Defend against logging secrets via static analysis](https://github.com/kubernetes/enhancements/issues/1933). Those tags will be used by for ensuring this data will not be written to logs by Kubernetes system components. 

List of datapolicy tags available:
* `security-key` - for TLS certificate keys. Keywords: `key`, `cert`, `pem` 
* `token` - for HTTP authorization tokens. Keywords: `token`, `secret`, `header`, `auth`
* `password` - anything passwordlike. Keywords: `password`

**Special notes for your reviewer**:

Due to size of Kubernetes codebase first iteration of tagging was done based on greping for particular keyword. Please ensure that tagged fields do contain type of sensitive data that matches their tag. Feel free to suggest any additional places that you think should be tagged.

**Does this PR introduce a user-facing change?**:
No
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1933
```

/cc @PurelyApplied
/sig instrumentation security
/priority important-soon
/milestone v1.20

### CODE REVIEW

**Comment by serathius** [comment]
ping @yujuhong

**Review by ehashman — APPROVED** [review]
/lgtm

As per #95997 I'm assuming the StaticPodURLHeader headers could potentially contain auth info.

**Review by mrunalp — APPROVED** [review]

**Comment by ehashman** [comment]
/assign @liggitt 

see https://github.com/kubernetes/kubernetes/pull/107121#pullrequestreview-898330204

**Comment by liggitt** [comment]
The description links to a KEP marked as deprecated. Is there an updated link or doc describing why we're adding these tags (for static analysis only, I assume)

**Comment by liggitt** [comment]
/approve
from API perspective, adding the tag is fine
/hold for additional tag on the URL field and an updated description to a non-deprecated doc/reference

**Comment by liggitt** [comment]
I updated the PR description to link to that KEP instead, thanks

**Comment by serathius** [comment]
> The description links to a KEP marked as deprecated. Is there an updated link or doc describing why we're adding these tags (for static analysis only, I assume)

Done

**Pull request merged**
