### PR TITLE
add ineligible_endpoints.yaml

### PR DESCRIPTION
**Pull request by zachmandeville**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR stems from a discussion in the [January 26 Conformance Office Hours](https://docs.google.com/document/d/1W31nXh9RYAb_VaYkwuPLd1hFxuRX3iU0DmaQ4lkCsX8).  There are a number of GA endpoints that do not qualify for conformance, and should be excluded for testing, but the exact endpoints and the reason for their ineligibility has been opaque.  This yaml contains a list of these endpoints, the reason for their ineligibility, and a link with further context for this reason.  Its intention is to give a transparent, community-supported way to maintain and report upon conformance-ineligible GA endpoints.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
---

/area conformance

### CODE REVIEW

**Comment by hh** [comment]
Thanks for initiating this @zachmandeville !

**Review by hh — APPROVED** [review]
I'm happy with this approach, makes the list more accessible.

**Comment by dims** [comment]
@zachmandeville @hh how do we ensure that this list is up-to-date? Also where can/should we use/surface this information? (docs? apisnoop?)

**Comment by hh** [comment]
> how do we ensure that this list is up-to-date?
This list is intended to be manually curated.
This initial seeding was generated from our current sql exceptions within APISnoop.
- https://github.com/cncf/apisnoop/blob/main/apps/snoopdb/tables-views-functions.org#ineligible-endpoint

> Also where can/should we use/surface this information? (docs? apisnoop?)

We will be dropping that table from APISnoop and instead using this file (as merged to main/master) as the authoritative source of ineligible endpoints.

I suspect this list will be updated shortly when I create another PR to this folder with a swagger.json with alpha and beta feature flags disabled. Some of these are alpha and beta endpoints that are difficult to tell apart from GA (they don't have alpha or beta in the path or operationId).

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit 
for merge

**Comment by Riaankl** [comment]
/test pull-kubernetes-unit
Unrelated flake
```
=== SKIP: vendor/k8s.io/legacy-cloud-providers/vsphere TestVolumes (0.00s)
    vsphere_test.go:787: No config found in environment
=== Failed
=== FAIL: pkg/proxy/config TestInitialSync (0.10s)
```

**Pull request merged**
