### PR TITLE
Bump the pod memory to higher levels to work on power

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

ppc64le architecture machines by default pagesize is 64K (vs 4K on intel), this usually end up using more memory for th workloads, so to run this testcase successfully, need to increase the pod memory limits to higher lavel.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @yujuhong 

@kubernetes/sig-node-pr-reviews

**Comment by yujuhong** [comment]
I think the summary API test only checks that the numbers are in the right range (with no intention to track usage regression), so bumping the number should be fine.
/cc @dashpole 
/approve

**Comment by dashpole** [comment]
Agree with the above, this is mostly meant to check "Is this about what we expect the pod to use?".  The lower bound is also much more important than the upper bound for checking, so it is fine to raise, especially if it is failing on valid setups.
/lgtm

**Comment by mkumatag** [comment]
Thanks a lot, guys @dashpole @yujuhong @dims.

**Comment by mkumatag** [comment]
assertion for pod spec is working fine but `.Node.SystemContainers[pods].Memory:` is failing because I'm running tests with parallel=8(default settings) for the node test. which is resulting in exceeding the memory limit check for the whole node.

```

    Timed out after 60.000s.
    Expected
        <string>: Summary
    to match fields: {
    .Node.SystemContainers[pods].Memory:
    	Expected
    	    <string>: MemoryStats
    	to match fields: {
    	.UsageBytes:
    		Expected
    		    <uint64>: 430702592
    		to be <=
    		    <int64>: 400000000
    	.WorkingSetBytes:
    		Expected
    		    <uint64>: 420806656
    		to be <=
    		    <int64>: 400000000
    	}

    }
```

code located at: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/summary_test.go#L116:L118

IMO we should change the limit to `memoryLimit := memoryCapacity.Value()` what do you say? @dashpole @yujuhong

**Comment by dashpole** [comment]
@mkumatag That sounds fine to me.

**Comment by mkumatag** [comment]
> @mkumatag That sounds fine to me.

I have submitted another PR to fix this - https://github.com/kubernetes/kubernetes/pull/73196

**Pull request merged**
