### PR TITLE
Refactor CR converter code to share code between nopConverter and webhookConverter

### PR DESCRIPTION
**Pull request by mbohlool**
A step toward adding monitoring in #74376

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm cancel

the integration test failure is legitimate. with this branch, the kind returned in a list of custom resources is incorrect:

`
$ kubectl get foos -o yaml -v=9
I0307 09:45:36.305417   33385 round_trippers.go:438] GET https://localhost:6443/apis/company.com/v1/namespaces/default/foos?limit=500 200 OK in 8 milliseconds
I0307 09:45:36.305447   33385 round_trippers.go:444] Response Headers:
I0307 09:45:36.305453   33385 round_trippers.go:447]     Date: Thu, 07 Mar 2019 14:45:36 GMT
I0307 09:45:36.305457   33385 round_trippers.go:447]     Content-Type: application/json
I0307 09:45:36.305461   33385 round_trippers.go:447]     Content-Length: 603
I0307 09:45:36.305492   33385 request.go:942] Response Body: {"apiVersion":"company.com/v1","items":[{"apiVersion":"company.com/v1","kind":"FooList","metadata":{"creationTimestamp":"2019-03-07T14:45:36Z","generation":1,"labels":{"pruneGroup":"true"},"name":"test","namespace":"default","resourceVersion":"1818","selfLink":"/apis/company.com/v1/namespaces/default/foos/test","uid":"ab0583a4-40e7-11e9-b34a-8a006092ee01"},"nestedField":{"otherSubfield":"subfield2","someSubfield":"subfield1"},"otherField":"field2","someField":"field1"}],"kind":"FooList","metadata":{"continue":"","resourceVersion":"1818","selfLink":"/apis/company.com/v1/namespaces/default/foos"}}
`

note the individual item is set to `"kind":"FooList"`

**Comment by liggitt** [comment]
that also demonstrates we need a test that explicitly checks the content of returned custom resource data, when fetched as a list and as an individual item. an integration test that fetches an individual item and a list, decodes into `map[string]interface{}`, clears non-deterministic fields (uid, creationTimestamp, resourceVersion), and does a deepequal on the remaining fields against an expected output.

**Comment by mbohlool** [comment]
There is another part of the #74376 that need to be imported here. Will fix and ping you.

**Comment by mbohlool** [comment]
@liggitt I added the test from the original PR and fixed the bazel build problem. This is good to go.

**Comment by mbohlool** [comment]
merged as part of main pr #74376

**Pull request closed without merging**
