### PR TITLE
remove duplicated import

### PR DESCRIPTION
**Pull request by CaoShuFeng**
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
/lgtm

**Comment by wojtek-t** [comment]
@CaoShuFeng 
```
W0116 15:01:43.014] FAILED: Build did NOT complete successfully
I0116 15:01:43.115] staging/src/k8s.io/apiserver/pkg/admission/config_test.go:212:3: undefined: apiserverapi
```

Seems like a real issue.

**Comment by CaoShuFeng** [comment]
@wojtek-t 
Done.

**Pull request merged**
