### PR TITLE
Move ComputePodChanges to the Docker runtime

### PR DESCRIPTION
**Pull request by vmarmol**
Depends on the refactoring in #7479. Split into two PRs for ease of review.

/cc @yujuhong @dchen1107 @yifan-gu

### CODE REVIEW

**Comment by yujuhong** [comment]
Correct me if I am wrong. Prober is only used in dockertools/manager, so eventually we will create the prober there, instead of in the kubelet?

**Comment by vmarmol** [comment]
The Prober will be used by other runtimes too so it will probably be created by Kubelet and injected into the runtimes.

**Comment by yujuhong** [comment]
I was thinking that each runtime can create its own prober, so that kubelet doesn't have to create and pass the runner. Since kubelet uses runner for other purposes, this seems fine to me. Thanks for clarifying.

**Comment by vmarmol** [comment]
Yes, Travis is green finally :)

**Comment by yifan-gu** [comment]
LGTM! Thanks @vmarmol !

**Pull request merged**
