### PR TITLE
make sure mounter not nil and fix some typo

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
make sure mounter not nil  then and fix some typo
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
@jianglingxia Please squash your commits. Then I'll lgtm. Thanks.

**Comment by jianglingxia** [comment]
have squash @dixudx
for lgtm，thanks

**Comment by jianglingxia** [comment]
/cc @jsafrane
thanks!

**Comment by jianglingxia** [comment]
thanks @dixudx 
for approve @saad-ali

**Pull request merged**
