### PR TITLE
Revert "kubectl: Make scaling smarter"

### PR DESCRIPTION
**Pull request by zmerlynn**
Broke `kubernetes-e2e-gce-scalability`.

Reverts kubernetes/kubernetes#18169

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM

**Comment by kargakis** [comment]
I have a bunch of tests refactored in that PR, it would be a waste not to include them in master. The fix to the e2e test is outlined [here](https://github.com/kubernetes/kubernetes/pull/18169#issuecomment-174192850)

**Comment by zmerlynn** [comment]
@kargakis: If you or someone else can pick them up, that's great. Typically @k8s-oncall (which is the hat I was/am wearing) has way more to handle, so we revert first to get things back on track. At the moment, I still have one more fire to put out.

**Comment by ixdy** [comment]
@kargakis please send in a PR to revert this revert (essentially the same thing as the original PR) + a commit to fix the broken test. As Zach mentioned, our builds are in a pretty sad state right now, so reverts are the quickest and easiest way to fix breakages.

**Pull request merged**
