### PR TITLE
Omit comparison with boolean constant

### PR DESCRIPTION
**Pull request by chuntaochen**
What type of PR is this?

Add one of the following kinds:
/kind cleanup

What this PR does / why we need it:
Modify static check
https://staticcheck.io/docs/checks#S1002

 Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?

```release-note
  Omit comparison with boolean constant
```

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by apelisse** [comment]
/triage accepted
/lgtm
/approve

Thanks!

**Comment by GreenApple10** [comment]
/recc @apelisse
Reverted the modification of other areas but kubectl.
Thanks!

**Pull request merged**
