### PR TITLE
Rewrite "Location" header in apiserver proxy.

### PR DESCRIPTION
**Pull request by enisoc**
So that redirects work correctly.

### CODE REVIEW

**Comment by a-robinson** [comment]
Assigning @davidopp since unfortunately lavalamp is out

**Comment by bgrant0607** [comment]
Reassigning to @nikhiljindal, who's been working on apiserver.

**Comment by jimmidyson** [comment]
:+1: Would love to see this merged.

**Comment by brendandburns** [comment]
LGTM.  merging.

**Pull request merged**
