### PR TITLE
Use prometheus extraction library for metric parsing in e2e tests

### PR DESCRIPTION
**Pull request by timstclair**
This has the benefit of:
- Simplify metric parsing code and making it more readable
- More robust to formatting changes, as the extraction library is part of the same repo as the generating code

### CODE REVIEW

**Comment by mikedanese** [comment]
@timstclair can you seperate the godep change into it's own commit per the last line of this section https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#using-godep

**Comment by timstclair** [comment]
@mikedanese Done. I had it that way locally but squashed before submitting the PR >.<  Should I re-squash it after the LGTM?

Also, is that e2e failure a flake?

**Comment by mikedanese** [comment]
@timstclair no I don't think you need to resquash. There is currently no consistency in our squashing policy but we are trying to decide on a standard. Thanks!

**Comment by bprashanth** [comment]
NIce! thanks, this is exactly what the todo is about. If you feel like, e2e.util.ReadLatencyMetrics requires the same care.

**Comment by wojtek-t** [comment]
cc @fgrzadkowski

**Comment by timstclair** [comment]
@bprashanth - This PR already addresses e2e.ReadLatencyMetrics, or was there another one I missed?

**Comment by bprashanth** [comment]
Ah, sorry I missed that. will defer to Mike for lgtm since it's assigned to him

**Comment by mikedanese** [comment]
LGTM but I think it needs one more rebase to fix shippable.

**Pull request merged**
