### PR TITLE
Log spelling formatting

### PR DESCRIPTION
**Pull request by dengyufeng2206**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
According to https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
Capitalize the first letter of the sentence
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by marseel** [comment]
Thanks!

/lgtm
/approve

**Comment by derekwaynecarr** [comment]
Thank you for the update.

/lgtm
/approve

**Pull request merged**
