### PR TITLE
Fix typo in runtime_cache.go

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by roberthbailey** [comment]
@pmorie I've noticed that most of the RedHat folks aren't getting the CLA bot warning any longer but you still seem to be. Any ideas why you aren't passing the automated checks?

**Comment by roberthbailey** [comment]
Code LGTM. Will merge on green.

**Comment by pmorie** [comment]
@roberthbailey I believe it's because I hadn't switched my public email on my gh account over to my redhat.com email address.  Let's see what happens now.

**Comment by roberthbailey** [comment]
@pmorie that would explain it.

**Comment by pmorie** [comment]
@roberthbailey Fixed

**Comment by roberthbailey** [comment]
Thanks! (now just waiting for a green dot...)

**Comment by pmorie** [comment]
@roberthbailey Presumably the travis build will run at some point.

**Comment by roberthbailey** [comment]
I think it's actually next in line!

**Comment by pmorie** [comment]
I should have gotten a low number from the scalper

**Pull request merged**
