### PR TITLE
Verify that the we get a non-nil subtree before consulting it.

### LINKED ISSUE #27919: kube-dns panic in treecache
(blocking #27819)
This is in a modified local copy, but I don't think I've introduced this.

```
I0623 01:36:31.861596       1 dns.go:422] Received DNS Request:federated-service.e2e-tests-service-p27lt.federation.default.svc.cluster.local., exact:true                                    
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                       
[signal 0xb code=0x1 addr=0x8 pc=0x64208c]                                                                                                                                                    

goroutine 114 [running]:
panic(0x1756500, 0xc820014060)
/usr/local/go/src/runtime/panic.go:481 +0x3e6                                                                                                                                                 
k8s.io/kubernetes/pkg/dns.(*TreeCache).getEntry(0xc820014ec0, 0xc82022e5f0, 0x11, 0xc820254150, 0x6, 0x7, 0x0, 0x0, 0x6400)                                                                   
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/dns/treecache.go:101 +0x6c                                                                                          
k8s.io/kubernetes/pkg/dns.(*KubeDNS).Records(0xc820116000, 0xc82022e5f0, 0x4f, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/dns/dns.go:442 +0x60b
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).CNAMERecords(0xc82000a600, 0xc82022e5f0, 0x4f, 0xe00010005, 0xc82022e5f0, 0x4f, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:658 +0xa4                                                      
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc82000a600, 0x7f74497fee50, 0xc820261d80, 0xc8202a2360)                                                 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:375 +0x329a                                                    
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc820015430, 0x7f74497fee50, 0xc820261d80, 0xc8202a2360)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:209 +0xbb
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serve(0xc8200524e0, 0x7f74498500e8, 0xc8202a10b0, 0x7f74498500c0, 0xc820015430, 0xc82023fc00, 0x60, 0x200, 0xc82014a028, 0xc820299b60, ...)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:576 +0x7ef                                                                        
created by k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serveUDP                                                                                                                   
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:530 +0x3e1                                                                        
```

### PR DESCRIPTION
**Pull request by mml**
Fixes #27919

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @girishkalele who is KubeDNS owner.

LGTM, thanks!

@girishkalele We have a bunch of PRs updating KubeDNS. Is it fine if we merge these PRs and then build and push a new KubeDNS image only once (instead of doing it once for all these PRs)?

**Comment by quinton-hoole** [comment]
For the record, LGTM.

**Comment by girishkalele** [comment]
@nikhiljindal @mml 

I was wondering about the multiple parallel DNS changes in-flight.

Can we consolidate the kubedns changed into one PR - taking the pkg/dns/* changes out of their existing PRs since the code change doesn't get exercised without pushing the kubedns container (and upgrading the yaml file to point to the new tag).

The kube-dns PR can then push the final kubedns as the next tag version, bump up the yaml file and let e2e tests run against that.

**Comment by girishkalele** [comment]
@mml 

I didn't mean this PR - let this PR merge in - but the more complex kubedns changes that are still in flight.

**Comment by nikhiljindal** [comment]
@girishkalele 
Yes I am bumping up the version and pushing a new image in my PR (https://github.com/kubernetes/kubernetes/pull/27708) that contains the more complex changes.
The only other DNS change is https://github.com/kubernetes/kubernetes/pull/27960.

**Comment by mml** [comment]
There is more debugging output added in #27972 and if we care to change our version of skydns, I also added some debugging info in skynetservices/skydns#283.

**Comment by girishkalele** [comment]
I would wait till post-1.3 to update our Godeps pointer to skynetservices/skydns.
Currently, it points to a ref from March 4, about 9 commits behind HEAD.

```
			"ImportPath": "github.com/skynetservices/skydns/singleflight",
			"Comment": "2.5.3a-32-gf7b6fb7",
			"Rev": "f7b6fb74bcfab300b4e7e0e27b1fe6c0ed555f78"
```

**Pull request merged**
