### PR TITLE
Disabling unit tests for verifying federation secret and namespace update

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes/issues/36473#issuecomment-259605870

Essentially https://github.com/kubernetes/kubernetes/pull/36536 part 2.

cc @mwielgus @saad-ali

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36563)

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by mwielgus** [comment]
I have a fix for finalizer test failures. Do not merge yet.

**Comment by mwielgus** [comment]
See: https://github.com/kubernetes/kubernetes/pull/36613

**Comment by dims** [comment]
@mwielgus @nikhiljindal Do we abandon this PR? Or at least take off the v1.5 milestone

**Comment by mwielgus** [comment]
It can be closed.

**Pull request closed without merging**
