### PR TITLE
Add labels when conformance/ directory changes

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

So we don't have to do this manually for every PR

Change-Id: I4dc656e84ff6c48bc582b2aee6615bef11553257

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@justinclayton @bgrant0607 really easy one, just adding labels to OWNERS file. please take a look

**Comment by bgrant0607** [comment]
Thanks
/lgtm
/approve

**Pull request merged**
