### PR TITLE
Update Gophercloud dependency for reauth problem

### LINKED ISSUE #55656: Endless recursive requests to server when server response error
Upstream Issue in Gophercloud : https://github.com/gophercloud/gophercloud/issues/232
Upstream fix in Gophercloud : https://github.com/gophercloud/gophercloud/pull/604

Can we please update to latest gophercloud for 1.9?

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Fixes picked up from gophercloud:
https://github.com/gophercloud/gophercloud/compare/443743e88335413103dcf1997e46d401b264fbcd...0b6b13c4dd9e07a89f83cbe4617c13ad646d6362

Including the one for endless loop on reauth:
https://github.com/gophercloud/gophercloud/pull/604

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55656

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
The verify-staging-godeps.sh is broken.

**Comment by dims** [comment]
@FengyunPan it's almost ready now (past the verify problem)

**Comment by dims** [comment]
Thanks @idvoretskyi 

/assign @thockin

**Pull request merged**
