### PR TITLE
Link `apiextensions-apiserver` binary statically

### LINKED ISSUE #2786: Enforce static linking for all shipped binary artifacts
We reuse the artifacts in our debian and rpm packages and therefore cannot guarantee that we meet all the runtime dependencies they require. For example the kubelet is dynamically linked to glibc, which could be linked statically.

We should check which binaries are not static and try to link them accordingly. We can verify that either directly in the k/k build scripts or via `krel stage`, for example by extending the ELF header parser to search for the `PT_INTERP` section:

https://github.com/file/file/blob/FILE5_36/src/readelf.c#L1581
https://github.com/kubernetes/release/blob/bbee49970ab0bc59c20b5d46fd57e9fd4e228544/pkg/binary/elf.go#L125-L131

The kubernetes build scripts already maintain a list in:
https://github.com/kubernetes/kubernetes/blob/d98e9620e37995597f25f9a5d7e228dcf9dbbb1f/hack/lib/golang.sh#L327-L336

Binaries which are not statically linked right now:

- [x] kubelet: https://github.com/kubernetes/kubernetes/pull/114225
- [ ] apiextensions-apiserver: https://github.com/kubernetes/kubernetes/pull/114226
- [x] kube-aggregator: https://github.com/kubernetes/kubernetes/pull/114227
- [x] kubectl-convert: https://github.com/kubernetes/kubernetes/pull/114228

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

The apiextensions-apiserver itself only depends on the following runtime libraries when linking dynamically:

```
> ldd _output/bin/apiextensions-apiserver
        linux-vdso.so.1 (0x00007ffd1b39f000)
        libpthread.so.0 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libpthread.so.0 (0x00007fe836022000)
        libc.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6 (0x00007fe835e00000)
        /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/ld-linux-x86-64.so.2 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib64/ld-linux-x86-64.so.2 (0x00007fe836029000)
```

We now move the apiextensions-apiserver to become a static binary as well to achieve maximum portability.

#### Which issue(s) this PR fixes:

Closes https://github.com/kubernetes/release/issues/2786

#### Special notes for your reviewer:
/sig release
#### Does this PR introduce a user-facing change?

```release-note
Make `apiextensions-apiserver` binary linking static (also affects the deb and rpm packages).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-architecture PTAL

**Comment by valaparthvi** [comment]
Hi, Bug Triage Team for v1.27 here o/
I am checking in to make sure this PR is on track for the 1.27 milestone.

**Comment by valaparthvi** [comment]
Hi, @saschagrunert @kubernetes/sig-release-leads. I am from the Bug Triage Shadow Team for K8s release 1.27.
With Code Freeze coming in on March 15, please ensure the PR goes in before that if you would like for it to be a part of v1.27 release. Post Code Freeze, we will only be able to accept Release Blockers and Critical issues.

**Comment by saschagrunert** [comment]
Gave it a rebase.

**Comment by dims** [comment]
we landed the other PR for static linking, so we should be consistent and land this as well.

xref: https://github.com/kubernetes/kubernetes/pull/114227

**Pull request merged**
