### PR TITLE
Update service pages to v1beta3 in web ui

### PR DESCRIPTION
**Pull request by bcbroussard**
Depends on #8304

cc @jackgr @lavalamp @bgrant0607 @brendandburns

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks, @bcbroussard, I can't find any problem. Have you guys tested it? And how can I view the GUI?

**Comment by bcbroussard** [comment]
@caesarxuchao yes we have tested all of these locally in vagrant. The webUI is built into the apiserver, so I'll goto https://<k8s master>/static/app/ . Ping me (bcbroussard) on the irc channel and I can go into more details.

**Comment by bcbroussard** [comment]
@caesarxuchao can I get a LGTM status label?

**Comment by thockin** [comment]
rebase, please

**Comment by bgrant0607** [comment]
I'd like to get all of the v1beta3-related PRs ASAP, prior to the 0.18 cut. Please rebase.

**Comment by thockin** [comment]
needs rebase

**Comment by bcbroussard** [comment]
@thockin rebased

**Comment by bgrant0607** [comment]
Tests failed:
```
Error: [$injector:nomod] Module 'kubernetesApp.components.dashboard' is not available!
```

**Comment by bcbroussard** [comment]
@bgrant0607 This error occasionally occurs due to a race condition in the gulp build task. I verified that #8612 works and it is built with this PR as a dependency. If the #8612 build passes are you ok merging both to fix this? I'll have a fixed PR ready just in case.

Jack mentioned that his outstanding PR refactoring the build has fixed the race condition.

**Comment by bgrant0607** [comment]
Restarted Travis. Not sure why Shippable didn't run.

**Comment by bcbroussard** [comment]
Rebuilt and pushed an updated version to restart Shippable and Travis

**Pull request merged**
