### PR TITLE
Check error return from snapshot Restore

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR adds check for the return value of snapshottable.Restore.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by whs-dot-hk** [comment]
Hi,

I found another place restoring snapshottable

https://github.com/kubernetes/kubernetes/blob/8f0d626228cf890461cf24cd1cfb861bba1f9815/pkg/registry/core/service/portallocator/allocator.go#L199

what do you think about matching that style?

**Comment by tedyu** [comment]
@whs-dot-hk 
I was following the style of error reporting at line 226 above my change.

**Comment by liggitt** [comment]
/unassign
/assign @thockin

checking error results makes sense in general, but will defer to @thockin (or delegate) in case there are edges I'm not aware of here

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
