### PR TITLE
Fix for alpha CI jobs failing with AllowUnsafeMalformedObjectDeletion switched on

### PR DESCRIPTION
**Pull request by dims**
Fix for https://github.com/kubernetes/kubernetes/issues/128704

Either we roll/revert the entire alpha feature or try to move forward with something like what is in this PR.

based on notes from @liggitt in:
https://github.com/kubernetes/kubernetes/issues/128704#issuecomment-2466016860

```
Cause is at https://github.com/kubernetes/kubernetes/pull/127513/files?file-filters%5B%5D=.go&show-viewed-files=true#r1835235231

That check is inverted. I didn't sweep the rest of the PR to see if the same flip exists elsewhere.
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Looking at the PR again, this seems to be the only occurrence of the inversion.

**Comment by liggitt** [comment]
The change looks correct at a glance, I'd like to see us add a unit test for this, but will let the original PR author create that

/lgtm
/approve
/hold in case you want more eyes or to verify with an alpha run that this works as expected

**Comment by dims** [comment]
`pull-kubernetes-e2e-kind-alpha-features` succeeded, hopefully `pull-kubernetes-e2e-kind-alpha-beta-features` will as well. will `/unhold` after that. 🤞🏾 nothing else is hiding behind this!!!

**Comment by dims** [comment]
/hold cancel

`pull-kubernetes-e2e-kind-alpha-beta-features` is ✅ 
`pull-kubernetes-e2e-kind-alpha-features` is ✅

**Comment by dims** [comment]
one failure in `pull-kubernetes-integration`

```
{Failed  === RUN   TestSelectableFields
    testserver.go:285: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing"
    testserver.go:169: runtime-config=map[api/all:true]
    testserver.go:170: Starting apiextensions-apiserver on port 34563...
    testserver.go:196: Waiting for /healthz to be ok...
panic: conversion webhook for tests.example.com/v1, Kind=Shirt failed: Post "https://127.0.0.1:34537/convert?timeout=30s": write tcp 127.0.0.1:60346->127.0.0.1:34537: write: broken pipe

goroutine 63900 [running]:
k8s.io/apiserver/pkg/storage/etcd3.decodeObj({0x30ff6b0?, 0xc0005adb80?}, {0x3119800, 0x4a38aa0}, {0xc00003c000?, 0x1e0?, 0x2?}, 0x5b73)
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:730 +0x1c6
k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).prepareObjs(0xc002ae9040, 0xc0028b8370)
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:676 +0xe5
k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).transform(0xc002ae9040, 0xc0028b8370)
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:565 +0x3b
k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).serialProcessEvents(0xc002ae9040, 0xc002c964d0?)
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:441 +0x11e
created by k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).processEvents in goroutine 63898
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:433 +0xb3
```

**Comment by liggitt** [comment]
Sigh. Unrelated integration failure (should spawn an issue to track)

/retest

**Comment by tkashem** [comment]
the test PR: https://github.com/kubernetes/kubernetes/pull/128726

**Pull request merged**
