### PR TITLE
Fix broken link anchor in autoscaling comment

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
The trailing quote here breaks the link anchor in the generated docs by
appending &#34 to the anchor.

**What this PR does / why we need it**:
This PR removes a trailing `"` from a comment that seems to be breaking a link in the generated docs.

See [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#crossversionobjectreference-v2beta1-autoscaling). The "More info" link for `kind` doesn't work because the `#types-kinds` anchor is corrupted.

**Special notes for your reviewer**:
I'm not sure what needs to be done beyond this. Do I need to run something to regenerate the docs? Or is that done automatically later?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
/assign @thockin 

I also ran `hack/update-generated-swagger-docs.sh`. Happy to revert that if that's taken care of by a CI process or something 👍

**Comment by jonjohnsonjr** [comment]
I'm confused by the whitespace changes here, so maybe I'm doing something wrong. Running `./hack/update-generated-swagger-docs.sh` on a clean master produces the same whitespace changes :/

@neolit123 any idea what I need to do differently?

**Comment by neolit123** [comment]
@jonjohnsonjr 
did you try running `./hack/update-openapi-spec.sh`?

**Comment by jonjohnsonjr** [comment]
I managed to run `./hack/update-openapi-spec.sh`, but I still can't figure out why this whitespace is changing, so I'll just close the PR. Sorry for the trouble!

**Pull request closed without merging**
