### PR TITLE
WIP: Adds Windows kube-proxy image

### PR DESCRIPTION
**Pull request by claudiubelu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
please reopen when needed @claudiubelu trying to clean the incoming PR queue

**Comment by claudiubelu** [comment]
Opened up another PR: https://github.com/kubernetes/kubernetes/pull/109939

**Pull request closed without merging**
