### PR TITLE
Change build/mark-new-version.sh to always create a backmerge branch

### LINKED ISSUE #10825: Versioned API descriptions breaks existing release flow
#10690 doesn't work with our existing release flow. I thought it did, but, from https://github.com/GoogleCloudPlatform/kubernetes/pull/10812#issuecomment-119078638: 

>The process we use right now is to create the release branch locally, tag it, propose a PR (like this one), then push the branch. Most of those instructions are actually sitting right in mark-new-version.sh, and some are here: https://github.com/zmerlynn/kubernetes/blob/i1883/docs/devel/releasing.md#branching-tagging-and-merging.
>
>The problem, and I didn't really think about it long enough when it went in, is that the new sandwich commit you're creating, is always going to get backmerged back like this - git will always try to mutate head from the release version. We take that as good from the release version because we've been trying to keep the head version in sync with the patch version (long story), but not for these cases.
>
>We do have a weird cost for merging back and forth between release N-1 and master (we try to keep the release tags merged back to master). Not sure how to crack this particular nut.

cc @eparis @thockin 

closing out #10812.

### PR DESCRIPTION
**Pull request by zmerlynn**
...that reverts the doc diff.

This changes mark-new-version to create a backmerge branch that will
additionally handle the revert of the doc diff that's now created for
every release.

Sidebar: I really wish I knew a good git visualizer for GitHub - this
thing is going to start creating some awesome Gordian knots of merges.
(Or more like little Omegas, since they basically just change
version/base.go.)

Fixes #10825

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @eparis @thockin

**Comment by zmerlynn** [comment]
Sample .0 postamble:
```
Success you must now: 

- Push the tag:
   git push https://github.com/GoogleCloudPlatform/kubernetes.git v9999.9999.0
   - Please note you are pushing the tag live BEFORE your PRs.
       You need this so the builds pick up the right tag info.
       If something goes wrong further down please fix the tag!
       Either delete this tag and give up, fix the tag before your next PR,
       or find someone who can help solve the tag problem!

- I created the branch v9999.9999.0-merge-to-master for you. Submit this as a pull request to master:
   git push <personal> v9999.9999.0-merge-to-master
  and get someone to approve that PR. I know this branch looks odd. The purpose of this
  branch is to get the tag for the version onto master for things like 'git describe'.

- Push the new release branch
   git push https://github.com/GoogleCloudPlatform/kubernetes.git deleteme:release-9999.9999
```

I need to test on a .1. I'm sure I'll get a chance soon.

**Comment by zmerlynn** [comment]
Sample proposal: https://github.com/GoogleCloudPlatform/kubernetes/compare/GoogleCloudPlatform:master...zmerlynn:v9999.9999.0-merge-to-master?expand=1 (note that it includes this PR because the branch I was working off of included this PR because snake/tail)

**Comment by eparis** [comment]
should a backmerge branch be merged if we are working on say 0.19.4 but head is 0.20.2 ?  Like: https://github.com/GoogleCloudPlatform/kubernetes/pull/10839/files#diff-ee35feac4b2e319b9a5954bbcd6ab69fL155 talks about?

**Comment by zmerlynn** [comment]
I'm trying to figure out if there's an easy way to detect that while you're doing the backmerge, except possibly through version math. I can just add the instructions back in to use your brain here.

**Comment by zmerlynn** [comment]
@eparis: I added a strongly worded message. We can figure out if there's an automated way later. It does require a human on the other side to merge as well, so there have to be two people to screw up merging that tag...

**Comment by eparis** [comment]
might be even stronger than we need, but this LGTM

**Comment by brendandburns** [comment]
LGTM, but it would be nice if we validated that it was the latest version and didn't print the instructions otherwise.

**Comment by zmerlynn** [comment]
Okay, after discussion with @thockin, we're taking this path. Self-merging to advance release.

**Pull request merged**
