### PR TITLE
Promote endPort in Network Policy to GA

### PR DESCRIPTION
**Pull request by rikatz**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR promotes endPort field in Network Policy to GA

#### Which issue(s) this PR fixes:
Fixes [enhancements/2079](https://github.com/kubernetes/enhancements/issues/2079)

#### Does this PR introduce a user-facing change?
```release-note
endPort field in Network Policy is now promoted to GA

Network Policy providers that support endPort field now can use it to specify a range of ports to apply a Network Policy.

Previously, each Network Policy could only target a single port.

Please be aware that endPort field MUST BE SUPPORTED by the Network Policy provider. In case your provider does not support endPort and this field is specified in a Network Policy, the Network Policy will be created covering only the port field (single port).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2079-network-policy-port-range
```

/sig network
/triage accepted
/hold
/priority important-longterm
/assign @thockin @aojea @danwinship 

P.S.: PR is in hold so I can write a proper RELEASE NOTE :)

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by rikatz** [comment]
@thockin I will keep the hold and write a good RELEASE NOTE here, or maybe feature this in release blog :)

**Comment by sftim** [comment]
For the extended changelog, could we also link to https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports?

**Pull request merged**
