### PR TITLE
delete unused functions in pkg/util directory

### LINKED ISSUE #115088: Cleanup dead code in the codebase
https://github.com/kubernetes/kubernetes/pull/111654 started here but it got big (shocking!) and the contributor got busy.  There are a lot of potential cleanups in there, though, and I hate wasting work.

I see it as an opportunity for someone to rack up some PRs and net-negative LOCs (the best kind!) - just take over that PR, break it up into a bunch of smaller PRs, and send them our way!

A very eager beaver might automate this, but there's a lot of manually-identified low-hanging fruit, I think.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

xref #115088

#### Special notes for your reviewer:
This PR follows the content of #111654, the purpose is to split #111654 into many small PRs, this PR only modifies the pkg/util directory
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by brandond** [comment]
Removing exported functions from a util package feels like a breaking change, is it expected that we may lose things out of `k8s.io/kubernetes/pkg/util` without any deprecation period, and not even a changelog entry?

cc @thockin

**Comment by dims** [comment]
@brandond only guarantees are things in the staging repository. please feel free to copy over things you need that got dropped from here.

**Comment by brandond** [comment]
OK. We'll see if we can get the Mirantis folks to stop using that package.

**Comment by thockin** [comment]
Thanks.  We simply can't support API compat for all of our own internal packages and moving them all to `internal/...` is tedious and painful.  I know we've said this before, and I know some people do itr anyway.  We need to keep repeating it.

**Comment by thockin** [comment]
And if there are APIs we need to export, we can consider doing so via the staging mechanism, or you can fork them.

**Comment by liggitt** [comment]
> I know we've said this before, and I know some people do it anyway. We need to keep repeating it.

To be fair, it is called out explicitly in the [README](https://github.com/kubernetes/kubernetes/#to-start-using-k8s):

> To use Kubernetes code as a library in other applications, see the [list of published components](https://git.k8s.io/kubernetes/staging/README.md). Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

... and attempting to use k8s.io/kubernetes as a library requires jumping through tons of hoops to rewrite module requires, etc.

If there are more visible places to mention that, I'm happy to add more mentions wherever.

**Comment by brandond** [comment]
Yeah, this is probably an odd case though, in that cri-dockerd is code that was moved out from Kubernetes... clearly it was not scrubbed of all imports that were acceptable while part of the project, but are not now that it's been moved out.

**Pull request merged**
