### PR TITLE
Move changelog files to its own dir

### PR DESCRIPTION
**Pull request by NickrenREN**
We have split changelog into several files, as time goes on, there will be more and more files in the root directory, that will get messy.
Move changelog files out of root directory and create a symbolic link

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
@kubernetes/sig-release-pr-reviews

**Comment by brendandburns** [comment]
This seems reasonable to me, but do we know if there are external links to these files?

**Comment by xiangpengzhao** [comment]
I'm not sure if we still want to do this now.
xref: https://github.com/kubernetes/release/pull/421 https://github.com/kubernetes/release/pull/433
/cc @david-mcmahon

**Comment by thockin** [comment]
Almost certainly there are.

**Comment by xiangpengzhao** [comment]
original issue: #48985

**Comment by NickrenREN** [comment]
@xiangpengzhao  thanks for pointing it out.  I am not familiar with release scripts, do you mean we need to update these scripts if we want to move the changelog files to its own directory ?
btw: i really think it is not a good option to putting all changelog files in the root directory.

**Comment by NickrenREN** [comment]
@brendanburns @thockin   i create a symbolic link for CHANGELOG.md and do not know how to deal with other release version changelog files. what's your opinion ?

**Comment by xiangpengzhao** [comment]
>do you mean we need to update these scripts if we want to move the changelog files to its own directory ?
btw: i really think it is not a good option to putting all changelog files in the root directory.

Agreed. I also suggested to create a sub-dir for all changelog files. Currently all files in root dir should just be a workaround. I'm not sure what @david-mcmahon plans to fix this in his scripts mentioned above as I didn't go through them :) If we all agree on moving the changelog files to a sub-dir, then the scripts should be updated accordingly.

> do not know how to deal with other release version changelog files. 

AFAIK, now only CHANGELOG-1.7.md  is linked by [releases page](https://github.com/kubernetes/kubernetes/releases)

**Comment by david-mcmahon** [comment]
Things are just settling down from all the other changes in this area.  I understand the interest in keeping the top-level clean, but this will cause:

1. [Email group](https://groups.google.com/forum/#!forum/kubernetes-announce) notification links to no longer work
2. github release page links to no longer work (though these can be hand updated as needed)
3. Other places linking to CHANGELOG.md and anchors?

Also note, that with kubernetes/release#421, CHANGELOG.md is going away.  In fact there's still work to be done to pull the current CHANGELOG.md apart and put it into individual CHANGELOG-x.y.md files.

And of course, any changes to the location will require further updates to tooling in kubernetes/release.

**Pull request closed without merging**
