### PR TITLE
Revert "kubelet/network: report but tolerate errors returned from GetNetNS()"

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts kubernetes/kubernetes#43879

Per comment at https://github.com/kubernetes/kubernetes/issues/46651#issuecomment-305339470, I am reverting this pr to see if the serial build can be fixed.

cc/ @freehan @dcbw @thockin @kubernetes/sig-network-misc

### CODE REVIEW

**Comment by dchen1107** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by dchen1107** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by feiskyer** [comment]
@k8s-bot pull-kubernetes-cross test this

**Comment by dchen1107** [comment]
I am going to merge this one to so that we can kick out 1.7 beta.0

**Pull request merged**
