### PR TITLE
Reduce kubeadm tls bootstrap wait

### PR DESCRIPTION
**Pull request by chenk008**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We are trying to accelerate `kubeadm join`.

When kubeadm start kubelet and wait kubelet finish tls bootstrap, mostly the bootstrap will finish in one second. Now the wait period is 5s, it may waste about 4s.  

#### Special notes for your reviewer:

The check period is shorter at the beginning, and the period cap is 5s. So we don't use `ExponentialBackoffWithContext` or `PollImmediate`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i am not in favour of implementing the backoff with a for{} the way this change does. didn't the wait package have something more usable? like a backoff with cancel?

alternatively we could discuss reducing TLSBootstrapRetryInterval to less than 5 seconds.

this is a rather sensitive area of kubeadm that affects all users. i much rather keep what works as is than stripping a few seconds from join time.

**Comment by chenk008** [comment]
I agree that  the backoff with a for loop is a little bit nasty.  The `ExponentialBackoffWithContext` will break when  backoff retry duration reach the  cap, the `PollImmediate` always retry with a fixed duration. 

We are trying to reduce K8s node bootstrap time when scale out hundreds of nodes. We hope to achieve that the duration is less than 10s between `kubeadm join` and `NodeReady`.  The stripping of 4 seconds from join time is import. Please help me to improve it.

Maybe we could just reduce TLSBootstrapRetryInterval to 1 second? @neolit123

**Comment by neolit123** [comment]
> Maybe we could just reduce TLSBootstrapRetryInterval to 1 second? @neolit123

@SataQiu  @pacoxu WDYT?

**Comment by pacoxu** [comment]
> > Maybe we could just reduce TLSBootstrapRetryInterval to 1 second? @neolit123

5s seems to be not  too long for common use cases. 
In @chenk008 's use case, 1s would be better.

I cannot presee any problems with 1s interval. So I agree to change it.
Making it confiugrable would be better in my opinion. For a similar case, we use ENV to overwrite the default interval in our best practice. A flag is too heavy for this case.

**Comment by neolit123** [comment]
we have a tracking issue for changing timeouts via the api but it needs design and nobody is working on it. it can be done gor beta4.
https://github.com/kubernetes/kubeadm/issues/2463

we can change the interval to 1s and see how our ci behaves. if users complain for some reason we must revert.

**Comment by pacoxu** [comment]
> we have a tracking issue for changing timeouts via the api but it needs design and nobody is working on it. it can be done for beta4. [kubernetes/kubeadm#2463](https://github.com/kubernetes/kubeadm/issues/2463)

It makes sense. I will take a look later.

> we can change the interval to 1s and see how our ci behaves. if users complain for some reason we must revert.

Agree.

**Comment by chenk008** [comment]
@neolit123 @pacoxu I have changed the TLSBootstrapRetryInterval to 1s. Please take a look, thanks!

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
