### PR TITLE
Add CloudStack cloud provider (extended and refactored)

### LINKED ISSUE #26045: Add CloudStack cloud provider
I have been working on CloudStack cloudprovider integration. PR is coming soon.

### PR DESCRIPTION
**Pull request by svanharmelen**
This PR is superseding PR #26165 is which some groundwork for this PR has been done. So this PR now fixes #26165 and fixes #26045.

I've been in contact with @ngtuna about this updated version of his earlier work (which is still in this PR as one squashed commit) and he has given his 👍  for this :wink:

This PR adds additional logic for allocating and associating a public IP, if the `—load-balancer-ip` option is not used. It will do proper management of public IP’s that are allocated by this provider ( so IP’s that are no longer needed/used will also be released again).

Additionally the provider can now also work with CloudStack projects and advanced (VPC) networks. And lastly the Zone interface now returns an actual zone (supplied by the cloud config), a few logical errors are fixed and the first few tests are added.

All the functionality is extensively tested against both basic and advanced (VPC) networks and of course all new and existing (integration) tests are all passing.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29740)

### CODE REVIEW

**Comment by svanharmelen** [comment]
@mikedanese @lavalamp I noticed you followed up on the original PR of this provider (#26165), could you maybe push things along here as well :wink:

As for the CLA thingy, I'm certainly the author of these commits but indeed I squashed some commits from @ngtuna (so he would still get credits for his early work on this) into a single commit which is also in this PR. @ngtuna can you confirm that you are OK with this as we discussed by mail already? I guess that would fix the CLA part...

Let me know what else needs to be done to move this forward.

**Comment by mikedanese** [comment]
@ngtuna please say you are ok with these commits being contributed

**Comment by ngtuna** [comment]
I'm okay. Great to see things are moving so fast. +1 @svanharmelen @mikedanese

**Comment by svanharmelen** [comment]
Thanks @ngtuna!

@mikedanese I just did a forced update of the commit containing the dependency, as I noticed Jenkins is also checking on license files. The dep is licensed under the Apache 2.0 license, but there was no license file in the package directory itself, but only in the repo (one directory up).

So I quickly added one to the package directory as well to prevent any verification errors. All should be go to verify and test now :grin:

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
LGTM

**Comment by svanharmelen** [comment]
@mikedanese I noticed the `replicationcontroller` integration test failed with the following error: `replicationcontroller_test.go:368: timed out waiting for the condition`.

I had this once while running the tests locally as well. But the next time I executed the tests (directly afterwards without making any changes) it did pass successfully. So is this test known to have this inconsistent result and/or any timing related issues? As I cannot imagine how this would be related to the code I added in the PR.

As for the failed verification, I can see it did find the license I added to the new dependency so that part should be good. But I cannot seem to run the `hack/update-godep-licenses.sh` script successfully on my mac, so looking into that now.

**Comment by svanharmelen** [comment]
@mikedanese fixed the verify error by running `make/update-godep-licenses.sh` on a linux box that I had laying around. So maybe you could give it another nudge?

Additionally it would be nice if we could just use the build container for this (will check if I can fix that next week):

```
> ./build/run.sh hack/update-godep-licenses.sh
+++ [0730 01:05:12] Verifying Prerequisites....
+++ [0730 01:05:12] Using Docker for MacOS
+++ [0730 01:05:21] Building Docker image kube-build:build-8ba4e0bc61
+++ [0730 01:05:45] Running build command....
+++ [0730 01:05:45] Creating data container kube-build-data-8ba4e0bc61
hack/update-godep-licenses.sh: line 136: jq: command not found
+++ [0730 01:05:47] Running build command....
+++ [0730 01:05:48] Output directory is local.  No need to copy results out.
```

**Comment by svanharmelen** [comment]
@mikedanese seems that running the `hack/update-godep-licenses.sh` script was indeed the problem for the failing verify test. And just as I had when running the test locally, the second time running the integration test worked out better (strangely enough) :wink:

So I guess we are good to move this forward... Thx!

**Comment by svanharmelen** [comment]
@mikedanese any change you can put the `lgtm` label back on? It was removed when I fixed the godeps licenses last week, but it now seems to be holding the submit queue from moving on. Thx!!

**Comment by runseb** [comment]
@svanharmelen great to see you improve on @ngtuna work especially since we are using your cloudstack go client.

Can you add me as owner of this provider so that I can get notice if there are issues.

thanks

**Comment by svanharmelen** [comment]
@runseb I thought the owners file was used to list the people who coded and maintain the provider, so that's why I removed you initially. But will add you back if that makes you happy...

But let me then add you back in the next PR that I am currently working on and which I will create right after this one is merged. I would like to not change code in this PR again as that will trigger all tests and verifications to have to run again.

But rest assured, your name is already added back in my local stash with features for the next PR :wink:

**Comment by mikedanese** [comment]
@svanharmelen The OWNERS file is not who wrote the code, It's who should manage incoming code reviews. I don't think it's supposed to have names of people not in the org, I need to check with someone.

**Comment by svanharmelen** [comment]
@mikedanese ah... Totally didn't know that, so thanks for the feedback!

**Comment by runseb** [comment]
@svanharmelen @mikedanese my understanding is that the OWNERS file is needed to know who "owns" the code in the sense not only of modifying (and understanding it), but also in the sense of answering questions about it (triage issues being filed).

So if questions where asked about cloudstack due to this provider being available, then I committed to @bgrant0607 that @ngtuna and myself would be there to make sure issues filed on this provider would be answered and taken care of.

I am already a maintainer on helm, so if that can help having an acceptable OWNERS file to get the PR merged then I am happy to be in this file.

The authorship of the code in my view is clear based on the commits.

**Comment by svanharmelen** [comment]
If that is the case, then I think the current OWNERS file (with @runseb also added to it) should be fine. As I too will be comitted to maintaining this provider and any related issues, questions and PR's.

As a Terraform core comitter one of the things I do for that project is also managing the Terraform CloudStack provider (which I also wrote and maintain) in much the same way @runseb described above (triage issues, answer questions, help debug and review and merge PR's).

So I fully intent to support, manage and maintain this provider for time to come as well.

**Comment by mikedanese** [comment]
https://groups.google.com/forum/#!topic/kubernetes-dev/Kr6vxdd3bGg is relevant.

**Comment by svanharmelen** [comment]
@mikedanese good discussion 👍 

> If someone submits code that we would like to have but existing contributors are not able and willing to maintain, the authors need to sign up to maintain the code, fix broken tests, respond to issues and PRs, answer user questions, etc. In that scenario, the authors could get a fast-pass to admittance to the org, but ideally this would be rare, since they should have built karma and trust by fixing bugs, etc. before contributing something major

Reading this, I understand I did not yet build any karma within the Kubernetes project. Still I would certainly like to sign up to maintain (together with @runseb) this provider. Maybe the other open-source projects I'm involved in could give me some indirect karma :wink:

For example I've been a non-HashiCorp core-committer for almost 2 years now. Working on TF-core every now and then, but always maintaining the CloudStack provider and Chef provisioner:

Here's a small snipped from a HashiCorp [blog post](https://www.hashicorp.com/blog/terraform-improve.html) about community guidelines in which I'm actually used as an example:

>Just like our contribution guidelines, this isn't new. This is a formalization of what we've already been doing. Most of the 30 providers have come from the community, and we've always required automated tests to verify functionality. And some providers even have core committers from the community to maintain them. For example, HashiCorp doesn't have any CloudStack expertise, but Sander van Harmelen has been a non-HashiCorp core maintainer for over a year and keeping CloudStack stable and up to date.

Additionally the company I work for (which also happens to be one of the biggest CloudStack contributors) is fully supportive and has made the decision to fully go and embrace Kubernetes. So in that way I'm backed by my company and am able to also (next to my private time) spend working hours on managing and maintain the provider.

Hope this helps 😀

**Comment by mikedanese** [comment]
Sorry, forgot about this, can you just remove the OWNERS file for now so we can get this in? Happy to add people to the org after some contriubtions. I can remeber to ping all involved in PRs to this directory.

**Comment by svanharmelen** [comment]
@mikedanese sounds like a good way forward for now, thanks! Just rebased the PR and removed the OWNERS file, so all yours again :wink:

**Comment by mikedanese** [comment]
LGTM

**Comment by svanharmelen** [comment]
@mikedanese thanks for reviewing and guiding us to a mergable PR! Very nice we could land this one before 1.4 :grinning:

**Comment by runseb** [comment]
great, thanks for merging.

**Comment by ixdy** [comment]
FYI this broke the linux/ppc64le build:
```
# k8s.io/kubernetes/cmd/kubemark
/usr/local/go/pkg/tool/linux_amd64/link: running powerpc64le-linux-gnu-gcc failed: exit status 1
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.RunAsUserStrategy.CodecEncodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:12942:(.text+0x2010efc): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convT2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*FSGroupStrategyOptions).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13075:(.text+0x2011980): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.FSGroupStrategyType.CodecEncodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13195:(.text+0x2012294): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convT2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*SupplementalGroupsStrategyOptions).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13328:(.text+0x2012d18): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.SupplementalGroupsStrategyType.CodecEncodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13448:(.text+0x201362c): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convT2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*PodSecurityPolicyList).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13640:(.text+0x2014558): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*PodSecurityPolicyList).codecDecodeSelfFromArray':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13777:(.text+0x20151a0): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*NetworkPolicy).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:13963:(.text+0x2015e98): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*NetworkPolicy).codecDecodeSelfFromMap':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:14008:(.text+0x201623c): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:14014:(.text+0x20164d0): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-183829930/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*NetworkPolicy).codecDecodeSelfFromArray':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:14094:(.text+0x20169a4): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
```

#30384

**Comment by mikedanese** [comment]
How? presubmits where green...

**Comment by ixdy** [comment]
Presubmit only tests amd64 to keep things quick.

We accidentally stopped doing a full release on post-submit recently - https://github.com/kubernetes/test-infra/issues/393.

**Comment by svanharmelen** [comment]
@ixdy could you help me understand what part of the code in this PR breaks anything? As I fail to understand what I can do to fix the build based on the given output...

Happy to look into it and will do some testing myself as well once I'm behind a desk (in a few hours) again.

**Comment by svanharmelen** [comment]
@ixdy I started with verifying if this PR is actually breaking the `ppc64le` build, but it turns out it does not. When I revert to commit 9f8625fb (the last commit before the three commits in this PR) and run `./build/release.sh` I get the same error:

```
+++ [0816 08:22:21] Building go targets for linux/ppc64le:
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    federation/cmd/federation-apiserver
    federation/cmd/federation-controller-manager
    plugin/cmd/kube-scheduler
hyperkube build for ppc64le is disabled. Creating dummy text file instead.
# k8s.io/kubernetes/cmd/kubemark
/usr/local/go/pkg/tool/linux_amd64/link: running powerpc64le-linux-gnu-gcc failed: exit status 1
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*ThirdPartyResourceDataList).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7070:(.text+0x20130e0): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*Ingress).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7411:(.text+0x2014b58): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*Ingress).codecDecodeSelfFromMap':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7448:(.text+0x2015244): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*Ingress).codecDecodeSelfFromArray':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7515:(.text+0x20158e4): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7499:(.text+0x2015980): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*IngressList).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7757:(.text+0x20166c0): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.convI2E'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*IngressList).codecDecodeSelfFromMap':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7788:(.text+0x2016a64): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7794:(.text+0x2016dbc): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*IngressList).codecDecodeSelfFromArray':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7865:(.text+0x2017408): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:7849:(.text+0x20174a4): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.writebarrierptr'
/tmp.k8s/go-link-861458801/go.o: In function `k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions.(*IngressSpec).CodecDecodeSelf':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/pkg/apis/extensions/types.generated.go:8084:(.text+0x2017f18): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
```

So I guess the build problem is caused by another PR merged just before this PR was merged, and not this PR itself.

/cc @mikedanese

**Comment by luxas** [comment]
@svanharmelen I do not think this PR is the root cause, the error occurs just when the binaries grow too big, so it's a golang bug.

Thanks for looking into it anyway!

**Comment by svanharmelen** [comment]
I came to more or less the same conclusion after doing some digging, so thanks for the confirmation @luxas!

**Comment by ixdy** [comment]
@svanharmelen sorry about that! I saw this vendored code in the failure stack traces and just assumed it was the cause.

**Comment by svanharmelen** [comment]
@ixdy no problem of course :+1:

**Pull request merged**
