### PR TITLE
dockertools: remove some dead code

### PR DESCRIPTION
**Pull request by yujuhong**
Remove `dockerRoot` that's not used anywhere.

### CODE REVIEW

**Comment by Random-Liu** [comment]
The PR hits a soft lockup on GCI:
```
[  907.620742] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [cat:17925]
[  907.628041] Modules linked in: fuse dummy sch_htb ebt_ip ebtable_filter ebtables veth xt_mark ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 xt_addrtype nf_nat br_netfilter uinput ip6table_filter ip6_tables aesni_intel aes_x86_64 glue_helper lrw i2c_piix4 gf128mul ablk_helper cryptd [last unloaded: configs]
[  907.660386] CPU: 0 PID: 17925 Comm: cat Not tainted 4.4.21+ #1
[  907.666336] Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
[  907.675685] task: ffff880126c64100 ti: ffff8800b0ee4000 task.ti: ffff8800b0ee4000
[  907.683290] RIP: 0010:[<ffffffff81090f2b>]  [<ffffffff81090f2b>] prepare_to_wait_event+0x2b/0xf0
[  907.692327] RSP: 0000:ffff8800b0ee7a90  EFLAGS: 00000202
[  907.697760] RAX: 000000000000008c RBX: ffff88012b6a4000 RCX: ffff880126c64100
[  907.705007] RDX: 0000000000000001 RSI: ffff8800b0ee7ad0 RDI: ffff88012b6a40d0
[  907.712253] RBP: ffff8800b0ee7ab0 R08: ffff88012fc152c0 R09: fffffffffff724b4
[  907.719585] R10: 0000000000000000 R11: 0000000000000000 R12: ffff88012b6a40d0
[  907.726835] R13: 0000000000000001 R14: ffff8800b0ee7ae8 R15: ffff88012b6a40d0
[  907.734086] FS:  0000000001580200(0063) GS:ffff88012fc00000(0000) knlGS:0000000000000000
[  907.743174] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  907.749030] CR2: 000000c41ff972f6 CR3: 00000000b2252000 CR4: 00000000001406b0
[  907.756283] Stack:
[  907.758408]  0000000000000010 ffff88012b6a4000 ffff88012b6a40d0 ffff880126c64100
[  907.766417]  ffff8800b0ee7b20 ffffffffa00cc2d0 fffffffffffffe00 0000000000000000
[  907.774702]  ffffffff00000000 ffff880126c64100 ffffffff81090b90 ffff8800b0ee7ae8
[  907.782713] Call Trace:
[  907.785282]  [<ffffffffa00cc2d0>] 0xffffffffa00cc2d0
[  907.790362]  [<ffffffff81090b90>] ? wait_woken+0x90/0x90
[  907.795792]  [<ffffffffa00cc719>] 0xffffffffa00cc719
[  907.800869]  [<ffffffffa00d01dc>] fuse_simple_request+0x11c/0x1c0 [fuse]
[  907.807688]  [<ffffffffa00d0ef1>] fuse_dev_cleanup+0xa81/0x1e70 [fuse]
[  907.815192]  [<ffffffff81194396>] lookup_fast+0x256/0x330
[  907.820714]  [<ffffffff81192bc4>] ? path_init+0x1f4/0x3c0
[  907.826229]  [<ffffffff81196e13>] path_openat+0x383/0x1510
[  907.831833]  [<ffffffff81127028>] ? unlock_page+0x58/0x60
[  907.837353]  [<ffffffff81199175>] do_filp_open+0x85/0x130
[  907.842870]  [<ffffffff8157e14e>] ? _raw_spin_unlock+0xe/0x10
[  907.848736]  [<ffffffff811a6cd4>] ? __alloc_fd+0xc4/0x170
[  907.854298]  [<ffffffff811872af>] do_sys_open+0x12f/0x280
[  907.859817]  [<ffffffff81001901>] ? syscall_trace_enter_phase1+0x151/0x1a0
[  907.866812]  [<ffffffff8118741e>] SyS_open+0x1e/0x20
[  907.871893]  [<ffffffff8157e5ee>] entry_SYSCALL_64_fastpath+0x12/0x71
[  907.878710] Code: 0f 1f 44 00 00 55 65 48 8b 0c 25 80 ae 00 00 48 89 e5 41 55 41 54 53 4c 63 ea 48 83 ec 08 f6 c2 81 74 10 48 8b 41 08 48 8b 40 08 <a8> 04 0f 85 9c 00 00 00 48 89 f3 48 c7 46 10 90 0b 09 81 49 89 
[  907.905994] Kernel panic - not syncing: softlockup: hung tasks
[  907.911938] CPU: 0 PID: 17925 Comm: cat Tainted: G             L  4.4.21+ #1
[  907.919096] Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
[  907.928432]  0000000000000000 ffff88012fc03e20 ffffffff812e67d4 ffffffff8171229d
[  907.936488]  ffff88012fc03eb0 ffff88012fc03ea0 ffffffff81125c6b 0000000000000008
[  907.944498]  ffff88012fc03eb0 ffff88012fc03e48 0000000000000010 0000000000000000
[  907.952534] Call Trace:
[  907.955105]  <IRQ>  [<ffffffff812e67d4>] dump_stack+0x63/0x8f
[  907.961103]  [<ffffffff81125c6b>] panic+0xc6/0x1ec
[  907.966013]  [<ffffffff810e87ef>] watchdog_timer_fn+0x1ef/0x1f0
[  907.972062]  [<ffffffff810e8600>] ? watchdog+0xa0/0xa0
[  907.977319]  [<ffffffff810af2bf>] __hrtimer_run_queues+0x10f/0x280
[  907.983615]  [<ffffffff810af6ec>] hrtimer_interrupt+0xac/0x1b0
[  907.989566]  [<ffffffff81580a18>] smp_apic_timer_interrupt+0x68/0xa0
[  907.996056]  [<ffffffff8157f322>] apic_timer_interrupt+0x82/0x90
[  908.002447]  <EOI>  [<ffffffff81090f2b>] ? prepare_to_wait_event+0x2b/0xf0
[  908.009587]  [<ffffffffa00cc2d0>] 0xffffffffa00cc2d0
[  908.014674]  [<ffffffff81090b90>] ? wait_woken+0x90/0x90
[  908.020114]  [<ffffffffa00cc719>] 0xffffffffa00cc719
[  908.025205]  [<ffffffffa00d01dc>] fuse_simple_request+0x11c/0x1c0 [fuse]
[  908.032037]  [<ffffffffa00d0ef1>] fuse_dev_cleanup+0xa81/0x1e70 [fuse]
[  908.038694]  [<ffffffff81194396>] lookup_fast+0x256/0x330
[  908.044226]  [<ffffffff81192bc4>] ? path_init+0x1f4/0x3c0
[  908.049757]  [<ffffffff81196e13>] path_openat+0x383/0x1510
[  908.055379]  [<ffffffff81127028>] ? unlock_page+0x58/0x60
[  908.060894]  [<ffffffff81199175>] do_filp_open+0x85/0x130
[  908.066509]  [<ffffffff8157e14e>] ? _raw_spin_unlock+0xe/0x10
[  908.072383]  [<ffffffff811a6cd4>] ? __alloc_fd+0xc4/0x170
[  908.078012]  [<ffffffff811872af>] do_sys_open+0x12f/0x280
[  908.083624]  [<ffffffff81001901>] ? syscall_trace_enter_phase1+0x151/0x1a0
[  908.090631]  [<ffffffff8118741e>] SyS_open+0x1e/0x20
[  908.095734]  [<ffffffff8157e5ee>] entry_SYSCALL_64_fastpath+0x12/0x71
[  908.103322] Kernel Offset: disabled
[  908.106945] Rebooting in 10 seconds..
[  918.166571] ACPI MEMORY or I/O RESET_REG.
```
/cc @dchen1107

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this

**Pull request merged**
