### PR TITLE
fix golint verify errors: drop the else

### PR DESCRIPTION
**Pull request by yasongxu**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
metrics/pkg/client/custom_metrics/multi_client.go
Errors from golint:
multi_client.go:123  if block ends with a return statement, so drop this else and outdent its block
multi_client.go:135  if block ends with a return statement, so drop this else and outdent its block

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @yasongxu 

/kind cleanup
/ok-to-test
/sig instrumentation
/priority backlog
(?)

**Comment by poothia** [comment]
lgtm

**Pull request closed without merging**
