### PR TITLE
kube-controller-manager: unit tests WatchListClient feature for client-go

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Tests whether the `WatchListClient` (defined in client-go) is exposed as a command line option for `KCM` with its default value set to `false`. 

We specificity test for `KCM` because this will be the only component using the watch-list feature for this release (targeted for `1.30`). 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
requires:
- https://github.com/kubernetes/kubernetes/pull/122555 
- https://github.com/kubernetes/kubernetes/pull/122571
- https://github.com/kubernetes/kubernetes/pull/122738

xref: https://github.com/kubernetes/enhancements/issues/3157

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/3157-watch-list/README.md
- [Other doc]: https://docs.google.com/document/d/1g9BGCRw-7ucUxO6OtCWbb3lfzUGA_uU9178wLdXAIfs/edit#heading=h.lymszxjovg65
```

### CODE REVIEW

**Comment by deads2k** [comment]
Just additional tests for https://github.com/kubernetes/kubernetes/pull/122738 ?  No objection, but next time you could get Ben to include them.

**Comment by p0lyn0mial** [comment]
> Just additional tests for https://github.com/kubernetes/kubernetes/pull/122738 ? No objection, but next time you could get Ben to include them.

Yes, just additional tests, no problem. Although, I prefer to open smaller PRs for easier review.

**Comment by p0lyn0mial** [comment]
/assign @deads2k @soltysh 

cc @wojtek-t

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
