### PR TITLE
agnhost/netexec: logging cleanup and print more verbose errors

### PR DESCRIPTION
**Pull request by dcbw**
There's currently no way to know whether an error is for SCTP or
UDP, for example:

Jul 24 09:55:54.469: INFO: netserver-0[e2e-nettest-3476].container[webserver].log
2020/07/24 09:53:52 Started UDP server
2020/07/24 09:53:52 Error occurred. error:protocol not supported

In this case the "Error occurred. error:protocol not supported" is
actually for the SCTP socket. Make that more apparent.

/kind cleanup
/sig network
/priority important-soon
/area test
/milestone v1.20

```release-note
NONE
```

### CODE REVIEW

**Comment by dcbw** [comment]
@aojea @kubernetes/sig-network-misc @sttts

**Comment by dcbw** [comment]
/retest
lots of test pod timeout

**Comment by aojea** [comment]
LGTM, however, 
@fedepaol and @danwinship were working on this recently so they may have better insights
https://github.com/kubernetes/kubernetes/pull/92657
https://github.com/kubernetes/kubernetes/pull/89582

**Comment by dcbw** [comment]
@aojea yeah, I'll poke them for review. At least their PRs don't conflict with this one

**Comment by claudiubelu** [comment]
/lgtm

Pretty straight-forward, it just adds more logging info, which is always useful.

**Comment by dcbw** [comment]
@claudiubelu could I get an /approve too since it looks good to you? Thanks!

**Comment by dcbw** [comment]
infra timeout flakes?
```
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading golang.org/x/tools v0.0.0-20200710042808-f1c4188a97a1
{"component":"entrypoint","file":"prow/entrypoint/run.go:245","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15m0s grace period","severity":"error","time":"2020-07-27T19:25:24Z"}
```
/retest

**Pull request merged**
