### PR TITLE
Update rbac role data to v1beta1

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by deads2k** [comment]
heh, @liggitt want to add me to approvers?

**Comment by liggitt** [comment]
> heh, @liggitt want to add me to approvers?

https://github.com/kubernetes/kubernetes/pull/40596

**Comment by liggitt** [comment]
tagging based on https://github.com/kubernetes/kubernetes/pull/40579#issuecomment-275667531

**Pull request merged**
