### PR TITLE
Fix exit code check in hack/grab-profiles.sh

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
`[ $? ]` is True regardless of whether the last command succeeds or not, which causes the script to not work.

For example:
```
# ./hack/grab-profiles.sh -s "1.1.1.1" -m --inuse-space
Error in getopt
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SataQiu** [comment]
A simple test:
```sh
# cd /
# files=$(ls | grep invalid)
# echo $?
1
# files=$(ls | grep root)
# echo $?
0
```
That looks as expected.

**Comment by tnqn** [comment]
> A simple test:
> 
> ```shell
> # cd /
> # files=$(ls | grep invalid)
> # echo $?
> 1
> # files=$(ls | grep root)
> # echo $?
> 0
> ```
> 
> That looks as expected.

However the expression itself is always true when it's evaluated alone, try the following:
```
root@k8s01:/# files=$(ls | grep invalid)
root@k8s01:/# if [[ $? ]]; then echo executed; fi
executed
root@k8s01:/# files=$(ls | grep root)
root@k8s01:/# if [[ $? ]]; then echo executed; fi
executed
```

**Comment by tnqn** [comment]
I guess it's because when only `$?` is evaluated in the expression, it's treated as string case. So it's true as long as the length of the value is non-zero.


[ -n&nbsp;STRING ] or [ STRING ] | True if the length of&nbsp;"STRING"&nbsp;is non-zero.
-- | --

/retest

**Pull request merged**
