### PR TITLE
Automated cherry pick of #15341

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #15341 on release-1.1.

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by dchen1107** [comment]
Flaky test: Job should run a job to completion when tasks sometimes fail and are locally restarted is marked as flaky now.
ok to test

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
e2e test flake:
"Job should run a job to completion when tasks sometimes fail and are locally restarted"

@k8s-bot test this please

**Comment by wojtek-t** [comment]
cluster didn't started correctly

@k8s-bot test this please

**Pull request merged**
