### PR TITLE
Add more events to HPA controller

### LINKED ISSUE #22174: Improve HPA decisions understability by exporting better described events
As a follow up from our offline discussion, we want to let users know that:
- why decision was made (ie. increased CPU usage)
- HPA uses the default autoscaling policy

ref #22171

### PR DESCRIPTION
**Pull request by fgrzadkowski**
- Use controller framework in HPA controller.
- Add events to improve understandability of HPA controller decisions

Fixes #22174

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
This PR increases time for HPA controller unit tests from 24s to 41s. This is waaaay too long. If this goes in I'll file a separate issue to speed them up.

**Comment by piosz** [comment]
LGTM, just a nit.

**Comment by fgrzadkowski** [comment]
@k8s-bot please test this.

**Comment by fgrzadkowski** [comment]
@k8s-bot test this github issue: #IGNORE

**Comment by fgrzadkowski** [comment]
@k8s-bot test this github issue: #22435

**Comment by piosz** [comment]
LGTM

**Pull request merged**
