### PR TITLE
ingress: migrate extensions.Ingress to networking.Ingress

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is a find/replace within my editor. I made the import
networkingv1beta1 so that it will be easier to replace for
the future v1 migration.

**Which issue(s) this PR fixes**:
Related: kubernetes/enhancements#758

**Special notes for your reviewer**:
- I'm hoping that I hit all of the variations, but it's possible that something got missed.

**Does this PR introduce a user-facing change?**:
-->
```release-note
ingress:  Update in-tree Ingress controllers, examples, and clients to target networking.k8s.io/v1beta1
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by cmluciano** [comment]
I forgot to run the verify tests before submitting, will fix this up tomorrow

/hold

**Comment by cmluciano** [comment]
strangely make update didn't really do anything. 

/hold cancel

**Comment by cmluciano** [comment]
@thockin had to  rebase/fixed tests, can I get your lgtm again?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
