### PR TITLE
Enable DNS for pods from files

### PR DESCRIPTION
**Pull request by thockin**
@satnam6502

### CODE REVIEW

**Comment by satnam6502** [comment]
I applied this patch and now I see elasticsearch can be reached from the Fluentd -> Elasticsearch container that is launched via a manifest file. From the Fluentd -> Elasticsearch container:
```
$ curl elasticsearch.default:9200/_search?pretty
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 0,
    "successful" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```
Still waiting to see if any data makes its way from the Fluentd collector to Elasticsearch.

**Comment by satnam6502** [comment]
Ah, we're in business! Logs are being ingested into Elasticsearch.
```
$ curl elasticsearch.default:9200/_search?size=10
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits
":[]}}root@fluentdesmanife2u464h05heqcpotoddodpnehjaqsde:/# curl elasticsearch.default:9200/_search?size=10
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits
":[]}}root@fluentdesmanife2u464h05heqcpotoddodpnehjaqsde:/# curl elasticsearch.default:9200/_search?size=10
{"took":98,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":41394,"max_score":1.0,
"hits":[{"_index":"logstash-2015.01.06","_type":"fluentd","_id":"AUq_2ox5t-RMM9w8rS3O","_score":1.0,"_source":{"mes
sage":"I0106 15:10:53.898987    4933 server.go:324] GET /healthz: (11.044us) 200","tag":"kubelet","@timestamp":"201
5-01-06T15:10:53+00:00"}},{"_index":"logstash-2015.01.06","_type":"fluentd","_id":"AUq_2ox5t-RMM9w8rS3T","_score":1
.0,"_source":{"message":"I0106 15:10:54.221524    4933 event.go:92] Event(api.ObjectReference{Kind:\"BoundPod\", Na
mespace:\"default\", Name:\"kibana-pod\", UID:\"ed6e2512-95b5-11e4-8bc0-42010af0d11e\", APIVersion:\"v1beta1\", Res
ourceVersion:\"\", FieldPath:\"spec.containers{kibana-image}\"}): status: 'running', reason: '
```

**Comment by thockin** [comment]
Thanks for the testing.  I want to beef up the test around this before commit.  Soon.

**Comment by thockin** [comment]
OK, tests are beefed up.  If this goes green, I think it's ready to go.

**Comment by satnam6502** [comment]
LGTM as far as I can tell. Would you like to squash the four commits into one?

**Comment by satnam6502** [comment]
Ah, a go fmt required on validation_test.go

**Comment by thockin** [comment]
I'd rather not squash - they are distinct changes.  Gofmt was bitching about whitespace.  I rejiggered it and repushed just now.

**Pull request merged**
