### PR TITLE
Fix rs release test to poll on 409s

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/43895

@caesarxuchao @fgimenez ptal

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot gce etcd3 e2e test this Up failure

**Comment by caesarxuchao** [comment]
Thanks.

**Comment by fgimenez** [comment]
@kargakis oh, sorry about that and thanks for fixing it.

How could the problem be caught earlier? The tests passed on every local execution, should I had used a particular set up, or execute more times?

**Pull request merged**
