### PR TITLE
Automated cherry pick of #85361: Fix label mutation in endpoints controller

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #85361 on release-1.16.

Needs to merge before we can re-enable the cache mutation detector in alpha e2e jobs without turning them red - https://github.com/kubernetes/test-infra/pull/15298

#85361: Fix label mutation in endpoints controller

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/patch-release-team for approval

**Comment by justaugustus** [comment]
On behalf of Release Engineering:
/lgtm
/approve

**Pull request merged**
