### PR TITLE
Migrate oom watcher not relying on cAdviosr's API any more

### PR DESCRIPTION
**Pull request by WanLinghao**
Migrate oom watcher not relying on cAdviosr any more.
It is part of plan of removing cAdvisor from k8s.
For more informations about this plan, please refer:
https://github.com/kubernetes/kubernetes/issues/68522

/kind feature

```release-note
Migrate oom watcher not relying on cAdviosr's API any more
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@dashpole PTAL
I have tested this by /proc/sysrq-trigger file

**Comment by dashpole** [comment]
It still relies on cAdvisor code, just not the event watcher interface.  The title is a little bit misleading.  That is totally fine for now.  I especially like the separation of the watcher into linux and unsupported.  Ill take another pass after the tests pass

**Comment by WanLinghao** [comment]
@dashpole  Hi, the test is fine now

**Comment by WanLinghao** [comment]
@yujuhong  PTAL

**Comment by WanLinghao** [comment]
@yujuhong friendly ping

**Comment by WanLinghao** [comment]
part of #76660

**Comment by yujuhong** [comment]
/approve
based on @dashpole's lgtm

**Comment by WanLinghao** [comment]
/assign vishh
for hack approve

**Comment by sttts** [comment]
/approve

for the remaining golint exception.

**Pull request merged**
