### PR TITLE
Don't delete the pod infrastructure container on health check failures.

### PR DESCRIPTION
**Pull request by brendandburns**
Hoping that this helps address https://github.com/GoogleCloudPlatform/kubernetes/issues/4406

### CODE REVIEW

**Comment by mikedanese** [comment]
This is unfortunate. I ran e2e on this and got one failure `[It] should contain environment variables for services` which I'm thinking is unrelated. I'll try and investigate what caused this regression.

**Comment by brendandburns** [comment]
@mikedanese there is a separate fix for that e2e fail.  See:

https://github.com/GoogleCloudPlatform/kubernetes/pull/4407

for the fix (I hope) to that failure mode.

**Comment by brendandburns** [comment]
although perhaps not.  I think we also need to add some retry logic to the log polling code, I will do that next

**Comment by dchen1107** [comment]
LGTM thanks for the fix.

**Pull request merged**
