### PR TITLE
dependencies: logr v1.4.2, zap v1.27.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

No particular reason for updating besides staying up-to-date.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
https://github.com/uber-go/zap/compare/v1.26.0...v1.27.0

**Comment by pohly** [comment]
/pull pull-kubernetes-e2e-kind-canary

Testing LABEL_FILTER, please ignore.

**Comment by pohly** [comment]
```
panic: test timed out after 3m0s
	running tests:
		TestRoundtripToUnstructured (1m24s)
		TestRoundtripToUnstructured/v1.admissionregistration.k8s.io/ValidatingAdmissionPolicyBinding (0s)
```

/retest
/assign @klueska 

For approval.

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
