### PR TITLE
remove nodeName from getAwsInstance

### PR DESCRIPTION
**Pull request by dhawal55**

### CODE REVIEW

**Comment by justinsb** [comment]
Does this work in 1.3 @dhawal55 ? I don't see how it can, because the volume mounting is now run from kube-controller-manager, and mounts volumes on the nodes.

**Comment by dhawal55** [comment]
I haven't tried it. I'm trying to go through the new `attach_detach_controller.go` and trying to figure out how it's computing nodeName.

**Comment by pmorie** [comment]
@dhawal55 could you please edit the description to say what this PR is doing?  Thanks.

**Comment by dhawal55** [comment]
Never mind. Closing this. I have another pull request with the fix.

**Pull request closed without merging**
