### PR TITLE
Checkout latest stable version after git clone in "Getting started locally" doc

### PR DESCRIPTION
**Pull request by phanect**
Users need to checkout latest tag or the user use development version of Kubernetes

### CODE REVIEW

**Comment by phanect** [comment]
Signed.

**Comment by phanect** [comment]
ok to test

**Comment by phanect** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
Mostly I would expect Kubernetes developers, as opposed to Kubernetes users in general, to use this way of running Kubernetes.

Do you prefer running locally over other single-node methods? If so, why?

**Comment by phanect** [comment]
In my understanding, this document is also for Kubernetes *users* who want to debug their YAML config files.
If this doc is for people who develops Kubernetes, plz decline this PR :)

**Comment by bgrant0607** [comment]
IMO, this doc should be in docs/devel instead.

We should direct users to vagrant or single-node Docker.

cc @mikedanese @fgrzadkowski @pwittrock @brendandburns @erictune

**Comment by erictune** [comment]
I agree.

**Comment by phanect** [comment]
That's good idea.
Well, then plz close this PR when you no longer required.

**Comment by mikedanese** [comment]
Thanks. Continuing this in #19205

**Pull request closed without merging**
