### PR TITLE
Integration test for pod deletion cost feature

### PR DESCRIPTION
**Pull request by ahg-g**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Adds integration test for pod deletion cost feature.

#### Which issue(s) this PR fixes:
Part of #45509 https://github.com/kubernetes/enhancements/issues/2255

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by ahg-g** [comment]
/assign @janetkuo 

This is for beta graduation.

**Comment by johnSchnake** [comment]
Questions for you about the feature/test:
 - The KEP states that "Documentation should stress the fact that this is best effort." Does that impact the reliability/flakiness of the test?
 - Even if the feature was disabled it seems like there is just a random chance of the 'correct' pod being removed, especially when there are only two. Would it make more sense and increase reliability of the test to have 5/10/15 pods so that the chance of the 'right' pod being left is reduced?

**Comment by ahg-g** [comment]
> The KEP states that "Documentation should stress the fact that this is best effort." Does that impact the reliability/flakiness of the test?

It shouldn't. In the larger scheme of things the feature is best effort since there could be race conditions between the time the annotation is set and the scale down request. In the test, we try to make sure that the cluster state is set up such that the controller should be making the expected decision. I think there is no other way to test "preference/best effort" features.

> Even if the feature was disabled it seems like there is just a random chance of the 'correct' pod being removed, especially when there are only two. 

No, it shouldn't. That is why I am setting the restart count of the container. In the case where the feature is disabled, the other pod should always be the one removed, and this is verified in the test cases.

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
