### PR TITLE
Implement check drop capabilities.go

### LINKED ISSUE #103271: [PodSecurity] restricted capabilities
Tasks:
- [x] Decide on restricted capabilities policy - discussion in https://docs.google.com/document/d/1Z26yS26z5saILHzj9nSvlbGOBJP_6c182Fl-vAi8AQY/edit
    - Proposal has buy-in
- [ ] Update Pod Security Standards documentation - https://github.com/kubernetes/website/pull/27882
- [ ] Implement `check_dropCapabilities.go`
  - in restricted v1.22+, must drop ALL, may only add back CAP_NET_BIND_SERVICE
  - sketch of this check in https://github.com/liggitt/kubernetes/commits/podsecurity-dropcap

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Builds on https://github.com/kubernetes/kubernetes/pull/103469, last three commits are new

#### Which issue(s) this PR fixes:

Fixes #103271

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @tallclair @sejr @mgutierrez98

### CODE REVIEW

**Comment by tallclair** [comment]
Verify needs a cleanup. Otherwise,
/lgtm

**Comment by liggitt** [comment]
fixed boilerplate (https://github.com/kubernetes/kubernetes/compare/c7d8fd5100a0be917412e6b24a4c04738da77347..6408f3dffc0e0ed138af349a2805c03cf36102ec)

**Comment by liggitt** [comment]
/retest

integration timeout

**Comment by liggitt** [comment]
timeout again

/retest

**Comment by liggitt** [comment]
integration flake is really bad, tracked in https://github.com/kubernetes/kubernetes/issues/103512

**Pull request merged**
