### PR TITLE
move kubernetes-namespaces to docs/user-guide

### PR DESCRIPTION
**Pull request by mikedanese**
optional, but it's an example focused on a single feature @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. Please bidirectionally link this example and namespaces.md.
cc @JanetKuo

**Comment by bgrant0607** [comment]
And we'll need to clean up the old files in gh_pages.

**Comment by mikedanese** [comment]
They are now bidirectionally linked.

**Comment by bgrant0607** [comment]
Search for /examples in docs/user-guide/namespaces/README.md. The command paths need to be updated. You need @thockin's new munger change. :-)

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
