### PR TITLE
Better output

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?
Enhancement 

#### What this PR does / why we need it:
 For better (more informative) output for developers when test fails.
#### Which issue(s) this PR fixes:

It fixes part of  #105678 

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
Please squash into a single commit. It's usually a good idea to do that right away; GitHub is good at showing changes between force-pushes.

Otherwise it looks good.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Review by pohly — CHANGES_REQUESTED** [review]

**Review by pohly — APPROVED** [review]
There are still cases where empty lines where removed unnecessarily, but so be it.

@NikhilSharmaWe: in future PRs, please pay attention to white space changes. Only change that when there is a reason to do it.

/lgtm

**Review by soltysh — APPROVED** [review]
/approve
/triage accepted
/priority backlog

**Pull request merged**
