### PR TITLE
refactor the SimpleMetaFactory test code

### PR DESCRIPTION
**Pull request by wanghaoran1988**

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
I signed it!

**Comment by wanghaoran1988** [comment]
I've signed it!

**Comment by wanghaoran1988** [comment]
@lavalamp Please help have a look when you can, thanks.

**Comment by lavalamp** [comment]
@k8s-bot ok to test

/lgtm

Sorry for delay, I was OOO.

**Comment by wanghaoran1988** [comment]
@k8s-bot verify test this

**Pull request closed without merging**
