### PR TITLE
Remove deprecated kube-proxy flags

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Most of kube-proxy flags are deprecated from 1.7 (#34727). According our [Deprecation Policy](https://kubernetes.io/docs/reference/deprecation-policy/), these flags can be removed in 1.9.
```
Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:
GA: 6 months or 1 release (whichever is longer)
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: #34727

**Special notes for your reviewer**:
/cc @ncdc @thockin 

**Release note**:

```release-note
action required: The kube-proxy component has been converted to use a configuration file from 1.7. The old flags were marked deprecated then and are removed in 1.9. Cluster administrators should switch to using the configuration file.
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
e2e test failed due to kube-proxy config (it uses flag `--master` which is removed in this PR)
```
Error: unknown flag: --master
Usage:
  kube-proxy [flags]
```

How to change the CI config to make kube-proxy only use config file instead of flag?

@krzyzacy any idea? :)

**Comment by ncdc** [comment]
I looked at the deprecation policy yesterday. It’s 2 releases or 1 year,
whichever is longer. We haven’t hit 1 year yet.

**Comment by xiangpengzhao** [comment]
@ncdc thanks for the point. I double check the deprecation policy. There are below rules:

```
Rule #5a: CLI elements of user-facing components (e.g. kubectl) must function after their announced deprecation for no less than:
GA: 1 year or 2 releases (whichever is longer)
```

```
Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:
GA: 6 months or 1 release (whichever is longer)
```

I think kube-proxy is not a user-facing component but an admin-facing one. So the `Rule #5b` is applicable for it. (6 months)

**Comment by ncdc** [comment]
Ah ok, thanks for the clarification. I think we need to finish moving the
config types into their own api group and get my help PR in first before we
remove the flags. Also, do we need to call the api beta or GA before we
remove the flags? Finally, do we think the overall community is ready for
using a config file for this?

Cc @thockin @mikedanese @jbeda @smarterclayton

**Comment by xiangpengzhao** [comment]
> I think we need to finish moving the config types into their own api group 

@ncdc You mean #53645 (`move KubeProxyConfiguration out of componentconfig API group`), right? Agree on waiting it.

>and get my help PR in first before we remove the flags. 

Which PR is that?

>Also, do we need to call the api beta or GA before we remove the flags? 

I'm not so sure :)

>Finally, do we think the overall community is ready for using a config file for this?

I don't think so, TBH :) Our CI tests are even using the deprecated flags... I also know there are users are used to using flags instead of config file. We may want to wait for an extra release.

**Comment by xiangpengzhao** [comment]
Got it. Agreed :)

**Comment by thockin** [comment]
Agree - remove EARLY in a cycle.  I don't think we've had enough practical overlap with config files to rip this away yet, and even 1.10 might be too soon, honestly.

**Comment by xiangpengzhao** [comment]
/close

until the community is ready for this.

**Pull request closed without merging**
