### PR TITLE
Revert "Merge pull request #87258 from verult/slow-rxm-attach"

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit 15c3f1b119ff4b4073c86df05c819a9672b80d68, reversing
changes made to 52d7614a8ca5b8aebc45333b6dc8fbf86a5e7ddf.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Reverts https://github.com/kubernetes/kubernetes/pull/87258 based on evidence that it caused leaked volumes in e2e runs (see https://github.com/kubernetes/kubernetes/pull/87258#issuecomment-579932107)

**Which issue(s) this PR fixes**:
Fixes diffResources volume leak in e2e runs

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig storage testing
/cc @verult @saad-ali

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

To fix broken E2E tests

**Comment by verult** [comment]
/lgtm

Will look into flaky tests

**Comment by odinuge** [comment]
Flake on e2e-gce looks like https://github.com/kubernetes/kubernetes/issues/87441
/retest

**Comment by liggitt** [comment]
the stage flakes are brutal
/retest

**Comment by liggitt** [comment]
Runc flake
/retest

**Pull request merged**
