### PR TITLE
Update snapshot controller to use k8s.gcr.io

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Move to a stable image repo instead of staging which auto-deletes images after 60 days

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by xing-yang** [comment]
Have we also updated the csi-snapshotter sidecar to use v2.1.1 image?

**Comment by msau42** [comment]
Snapshotter is still using v2.1.0: https://github.com/kubernetes/kubernetes/pull/93521

There shouldn't be a dependency between the two right?

**Comment by xing-yang** [comment]
> Snapshotter is still using v2.1.0: #93521
> There shouldn't be a dependency between the two right? 

We have never tested them separately.  They may not work properly if versions are different.

**Comment by xing-yang** [comment]
Is k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1 not available yet?  I can do docker pull of v2.1.0, but not v2.1.1.

**Comment by msau42** [comment]
In principle though they are supposed to be compatible. The upgrade of the snapshot controller can happen independently of the sidecar since they are deployed separately. If there is a problem with the version skew, we need to fix it

**Comment by msau42** [comment]
> Is k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1 not available yet? I can do docker pull of v2.1.0, but not v2.1.1.

We'll need to pull from quay and push to staging, and then promote.

**Pull request merged**
