### PR TITLE
Make PodContainerSpecChange private

### PR DESCRIPTION
**Pull request by jiangyaoguo**
Eliminate TODO.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by jiangyaoguo** [comment]
@dchen1107 Seems github missed the LGTM.

**Comment by jiangyaoguo** [comment]
@dchen1107 GCE e2e failed with unrelated reason. How can I re-trigger the GCE e2e test?  Does this need special privilege?

**Comment by dchen1107** [comment]
Your pr needs to rebase now. You can type "ok to test" to trigger GCE e2e test.

**Comment by dchen1107** [comment]
lgtm

**Pull request merged**
