### PR TITLE
kuberuntime labels belongs to kubelet types pkg

### PR DESCRIPTION
**Pull request by resouer**
Address previous TODO: Labels in kuberuntime should be moved to  kubelet types pkg.

### CODE REVIEW

**Comment by resouer** [comment]
unit test failed because of flake: #39604

**Comment by resouer** [comment]
@k8s-bot gci gke e2e test this

**Comment by resouer** [comment]
kindly ping @vishh, any free time to take a look on this?

**Comment by Random-Liu** [comment]
@resouer I'm not sure about this.

We previously had to expose [4 labels](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/labels.go#L20-L23) because summary api are using them. Or else, we prefer to keep the labels private in runtime packages as implantation detail.

I don't think we want to move all the labels to kubelet and make it public.

I believe the intention of the original `TODO` is to move the labels to `kubelet/types/labels.go` to share it with dockertools. However, now we don't need to do that because ideally cri integration will be switched to be default this release.

**Comment by resouer** [comment]
@Random-Liu Agreed. This is not needed after CRI rolled out. Closed.

**Comment by resouer** [comment]
Oops, it just came to me I shouldn't close it like this, we need to remove those TODOs, see #40196.

**Pull request closed without merging**
