### PR TITLE
Automated cherry pick of #53110

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #53110 on release-1.8.

#53110: Fix host network flake tests

### CODE REVIEW

**Comment by yujuhong** [comment]
/test pull-kubernetes-e2e-gce-bazel

This PR only fixes a bug in a specific node e2e test. Should not affect any other tests.

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by abgworrall** [comment]
This is lovely, but I'm not going to merge it this close to the release; it can go into 1.8.1.

**Comment by yujuhong** [comment]
> This is lovely, but I'm not going to merge it this close to the release; it can go into 1.8.1.

@abgworrall, this is a test fix that should help stabilize the node e2e tests, as they are flaky now. I see no reason to delay this...

**Pull request merged**
