### PR TITLE
Make typography a bit more consistent

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
LGTM

@RichieEscarez this level of detail is hard to maintain, but I think it is good.

**Comment by RichieEscarez** [comment]
Yes, i think this is a step towards improvement.

To provide better usability/consumability of our docs (so that things are easier to find (pages are easy to scan), therefore people are learning faster), we want to highlight only whats important given the context of the document. This lends to less user frustration and higher quality docs.

**A couple guidelines:**
(1)
We should only capitalize proper nouns (ie, do not capitalize our Kubernetes terms):

So for example, for a conceptual topic, say "services", i think its okay to capitalize or italicize a single instance of the term "*Services*" when we define it, but all instances after (or in pages that are not specifically about services) should be written without extra formatting. The importance here is that this reduces the clutter/distraction on the page so that someone would be able to scan that page and immediately find the definition of "services".

(2)
Other formatting such as `codeblocks` should be reserved for code:

Similarly, to reduce the cluttering affect of lots of codeblock formatting on a single page, we should only highlight the code, including examples, commands, and keywords in codeblocks. For example "to do xyz, specify `etcd`...." is okay, but referring the "etcd" on its own as a product or to describe the type of instance should not be highlighted.

**Conclusion:**
Ultimately, we need to reserve formatting for whats important (in the context of the page) and then do it consistently.

That said, these changes (although they do not adhere to the guidelines above) are consistent with the way our documentation is currently formatted. And consistency itself is also important.

LGTM 
(for the time being - to align with current library wide formatting)

For the future: 
A Kubernetes library wide effort of format clean up (for consistency and to align with the guidelines above) is needed.

**Comment by bgrant0607** [comment]
@RichieEscarez Please document the documentation formatting conventions.

**Comment by RichieEscarez** [comment]
@bgrant0607 yes, will do, ive already noted for myself to put something together and add it in the repo

**Pull request merged**
