### PR TITLE
k8s.io/apiserver: refactor GenericAPIServer healthz code.

### PR DESCRIPTION
**Pull request by siyuanfoundation**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
refactor GenericAPIServer healthz code to reduce some repetitive code.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
cc @logicalhan

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by jpbetz** [comment]
I love seeing how this reorganizes the code such that there is only one lock per object. That's a win for maintainability. Thanks @siyuanfoundation

**Comment by jiahuif** [comment]
/triage accepted
Thank you.

**Pull request merged**
