### PR TITLE
bump cni version

### PR DESCRIPTION
**Pull request by freehan**
@mikedanese do you mind take a look and see if I miss anything?

### CODE REVIEW

**Comment by mikedanese** [comment]
This looks good, verified with some grepping (probably what you did :) )

**Comment by freehan** [comment]
@mikedanese Thanks! Hope downloading cni tarball will not span across multiple repos any time soon. :P

**Comment by pbx0** [comment]
@freehan Was there a reason to bump cni directly to master over the recent v0.3.0 release. It might be better to follow the releases when possible since they should have received more careful testing.

**Comment by freehan** [comment]
@pbx0 Yeah. I know that is not ideal. But v0.3.0 release does not include the critical fixes required and people are waiting for it. https://github.com/kubernetes/kubernetes/issues/27603#issuecomment-230851539

Since we are post 1.3 release and we have some time till 1.4, so I bump it to HEAD and let the test rolling. We can always bump it to 0.4 once that is out.

**Comment by pbx0** [comment]
@freehan Thanks for the quick response, it makes sense since you had a critical fix. I also found myself bumping CNI and saw that it was just done upstream as well.

**Pull request merged**
