### PR TITLE
Revert "Merge pull request #43946 from jhorwit2/jah/host-path-psp"

### LINKED ISSUE #47863: structure of allowHostPaths in PodSecurityPolicy does not allow for future checks
extracted from https://github.com/kubernetes/kubernetes/pull/47811

the current implementation of `allowHostPaths` in PodSecurityPolicy is not friendly to future checks, like ensuring the path is ReadOnly

### PR DESCRIPTION
**Pull request by jhorwit2**
fixes #47863

This reverts commit b5eadb5d6b9ce34a673caeafe4fa0971c4b91139, reversing
changes made to 1889d654f5c76fcc6ce14c6d3702c06a6498695d.

**What this PR does / why we need it**:

Revert whitelist host paths in psp due to API concerns. Please refer to https://github.com/kubernetes/kubernetes/pull/47811 for the concerns.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

cc @liggitt @ericchiang @smarterclayton 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by liggitt** [comment]
looks like you're missing generated files from the original PR, please run `hack/update-all.sh` and update

**Comment by ericchiang** [comment]
@k8s-bot ok to test

**Comment by liggitt** [comment]
@kubernetes/sig-auth-api-reviews @kubernetes/api-reviewers

**Comment by liggitt** [comment]
the revert LGTM

I look forward to getting this in in 1.8

**Comment by liggitt** [comment]
cc @smarterclayton @saad-ali as original PR approvers

**Comment by smarterclayton** [comment]
/approve

for reverting.  This prevents us from shipping a beta API that we do not believe will be extensible in the future and while this would be valuable for 1.7.1, the risk of future lock in is too high.

**Pull request merged**
