### PR TITLE
Make kubectl top pod test table-driven

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34966)

### CODE REVIEW

**Comment by ivan4th** [comment]
@k8s-bot gci gke e2e test this

**Comment by ivan4th** [comment]
(ping)

**Comment by ivan4th** [comment]
(ping)

**Comment by janetkuo** [comment]
Sorry for the delay. Will review it this week

**Comment by ivan4th** [comment]
Thanks!

**Comment by janetkuo** [comment]
*[pkg/kubectl/cmd/top_pod_test.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJdYgoGF91wXdrMV08:-KWJdYgpdSADN1VHzz2A:b-kxzhii) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L58)):*
> ```Go
> 		{
> 			name:            "all in namespace",
> 			expectedPath:    "namespaces/testnamespace/pods",
> ```

s/testnamespace/testNS/g

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966)*

**Comment by janetkuo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubectl/cmd/top_pod_test.go, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJWjd0fiuEjLtrr6I8:-KWJWjd1wQ0v8cPj6bzj:bbvlm5z) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L52)):*
> ```Go
> 				0: testNS,
> 				1: "secondtestns",
> 				3: "thirdtestns",
> ```

What's the key of this map?

---

*[pkg/kubectl/cmd/top_pod_test.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJdYgoGF91wXdrMV08:-KWJe-JifmiG3-T2zQkp:b-pbc2j8) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L58)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary>
> s/testnamespace/testNS/g
</details>
Why not just add `baseMetricsAddress` and `metricsApiVersion` here?

---

*[pkg/kubectl/cmd/top_pod_test.go, line 90 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJYsgy-C1aIf9UcYhI:-KWJYsgy-C1aIf9UcYhJ:b9ufx2n) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L90)):*
> ```Go
> 		var expectedContainerNames, nonExpectedMetricsNames []string
> 		for n, m := range metricsList.Items {
> 			if namespace, found := testCase.expectedMetrics[n]; found {
> ```

n == 3 never happens, but testCase.expectedMetrics[3] exists?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966)*

**Comment by ivan4th** [comment]
Updated the PR. Also, moved the test data to the end of top_pod_test.go because it's only used for this test.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubectl/cmd/top_pod_test.go, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJWjd0fiuEjLtrr6I8:-KX4m4trOhWW3TS9FrCY:bxlfym0) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L52)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary>
> What's the key of this map?
</details>
Added a comment above

---

*[pkg/kubectl/cmd/top_pod_test.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJdYgoGF91wXdrMV08:-KX4m9srMrMf-OcDV2AU:boktv02) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L58)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary>
> Why not just add `baseMetricsAddress` and `metricsApiVersion` here?
</details>
testNS can't be used as namespace, so I changed it to testns. As of baseMetricsAddress and metricsApiVersion, I added topPathPrefix and updated test cases to use it (the full string is too long)

---

*[pkg/kubectl/cmd/top_pod_test.go, line 90 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJYsgy-C1aIf9UcYhI:-KX4mQD5DPQ2Wx-URDJG:brm8xgr) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L90)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary>
> n == 3 never happens, but testCase.expectedMetrics[3] exists?
</details>
Oops, good catch. This was a typo that didn't break the test. Fixed

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-:-KX4mf251HoIAlwenX2k:bdordjn)*

**Comment by ivan4th** [comment]
Can we move forward with this? It's a bit tiresome to rebase this PR because the code is touched relatively often & I have to reapply the changes manually to the converted test.

**Comment by janetkuo** [comment]
Sorry, will review it this week

**Comment by janetkuo** [comment]
*[pkg/kubectl/cmd/top_pod_test.go, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJWjd0fiuEjLtrr6I8:-KYVRIbFJMUl22tmQtEI:b-o7vipw) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L52)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Added a comment above
</blockquote></details>

just `[]string`

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966)*

**Comment by janetkuo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kubectl/cmd/top_pod_test.go, line 52 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJWjd0fiuEjLtrr6I8:-KY_rZngiv8dp5ZUcW4S:b-tifd8t) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L52)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary><blockquote>

just `[]string`
</blockquote></details>

Suggest renaming it `namespaces`, and make it `[]string` instead of `map`

---

*[pkg/kubectl/cmd/top_pod_test.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966#-KWJdYgoGF91wXdrMV08:-KYVRqkxuN9-K36FtkpV:b-bo3vr0) ([raw file](https://github.com/kubernetes/kubernetes/blob/cdc24111914a06ad5877e87af04476c6599fa12d/pkg/kubectl/cmd/top_pod_test.go#L58)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

testNS can't be used as namespace, so I changed it to testns. As of baseMetricsAddress and metricsApiVersion, I added topPathPrefix and updated test cases to use it (the full string is too long)
</blockquote></details>

I mean `topPathPrefix + "/namespaces/" + testNS + "/pods"`

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34966)*

**Comment by janetkuo** [comment]
A few comments, LGTM otherwise

**Comment by ivan4th** [comment]
Did the requested changes

**Review by janetkuo — APPROVED** [review]

**Comment by ivan4th** [comment]
Flake: #38556

@k8s-bot cri e2e test this

**Comment by ivan4th** [comment]
@k8s-bot cri e2e test this

**Comment by janetkuo** [comment]
The CRI GCE e2e test failure is unrelated to this change.  It's failing consistently; luckily, it's not blocking submit queue.

**Pull request merged**
