### PR TITLE
Added helper funcs to schedulercache.Resource.

### LINKED ISSUE #46924: Add helper funcs for schedulercache.Resource
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
code enhancement

**Kubernetes version** (use `kubectl version`):
master branch

**Description**:
There're some duplicated code slice about building/adding `v1.ResourceList` into `schedulercache.Resource`, it's better to have helper funcs to avoid duplication.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
Avoid duplicated code slice by helper funcs.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46924 

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wojtek-t** [comment]
Great - thanks!

/lgtm

**Pull request merged**
