### PR TITLE
rolebinding often used for serviceaccount

### PR DESCRIPTION
**Pull request by ptux**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

rolebinding often used for serviceaccount

```release-note

The change affects the following CLI command:

kubectl create rolebinding -h

```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

NOTE: this just updates the description with another example @soltysh so should be quick to review.

**Comment by deejross** [comment]
The tests will continue to fail until the syntax error mentioned above is fixed. This is the error logs from the tests:

```
vendor/k8s.io/kubectl/pkg/cmd/create/create_rolebinding.go:45:97: syntax error: unexpected newline, expecting comma or )
vendor/k8s.io/kubectl/pkg/cmd/create/create_rolebinding.go:47:3: invalid character U+0023 '#'
```

**Comment by ptux** [comment]
@soltysh 

this is a friendly remainder.

**Review by helayoty — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
