### PR TITLE
Use request to deal with resource requirement in priority functions.

### LINKED ISSUE #12574: Use request instead of limit in prioritizer function LeastRequestedPriority()
In https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/resource-qos.md, we have defined the QoS of CPU/Memory resources. Based on the description, I think it would make more sense to use requested resource instead of resource limit when prioritizing the node with respect to free resources. That is, free resource on a node should be measured by `capacity - sum_of_requested_resource`.

Besides, limits are replaced by requests in the corresponding predicate function `CheckPodsExceedingFreeResources()`, so I think it is necessary that we make similar changes in prioritizer function. 

What do you think? I would be happy to implement this if you think it is OK.

@davidopp @AnanyaKumar 

> update 2015.08.14:

In fact, as mentioned by @AnanyaKumar in the comments, we should use request instead of limit when scheduling. So, basically we need to change almost every limit in all priority functions. I will handle them carefully and send PR sooner. We can have further discussion based on the PR.

Regards

### PR DESCRIPTION
**Pull request by HaiyangDING**
fix https://github.com/kubernetes/kubernetes/issues/12574

I think this change is necessary as described in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md. However this change may affect users' habit.

We can have further discussion in this PR.

@davidopp @AnanyaKumar

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @piosz @jszczepkowski

**Comment by davidopp** [comment]
@HaiyangDING Thanks very much for noticing this! I agree with this change.

Let's let the PR sit for a few days just to make sure nobody has an objection. Ping me in a few days and I'll LGTM if nobody has objected.

@vishh

**Comment by vishh** [comment]
LGTM. Thanks for noticing and posting this PR @HaiyangDING!

**Comment by HaiyangDING** [comment]
@davidopp  @vishh 

Thanks for merging this! The corresponding documents need update as well, and I will send another PR on this.

**Pull request merged**
