### PR TITLE
Cleanup: Audit log and error capitalization

### PR DESCRIPTION
**Pull request by ShivangGoswami**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Inconsistent format of error strings

**Which issue(s) this PR fixes**:
Partial Fix for #15863 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NO

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
/ok-to-test
/kind cleanup
/priority backlog

**Comment by nikhita** [comment]
/assign @mikedanese 
for approval

**Comment by nikhita** [comment]
I have removed the release note for this PR, since it doesn't include a user-facing change.

/retest

**Pull request merged**
