### PR TITLE
GCE/Windows: use "return" as "continue" for ForEach-Object

### LINKED ISSUE #81734: SSH in Windows test cluster doesn't work
I followed the document to create an e2e cluster https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/README-GCE-Windows-kube-up.md

However, `gcloud compute ssh` doesn't work after the cluster is up.

I got the following error:
```
Warning: Permanently added 'compute.3660176483394069101' (ECDSA) to the list of known hosts.
lantaol@XX.XXX.XXX.X: Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

/cc @yujuhong @kubernetes/sig-windows-misc

### PR DESCRIPTION
**Pull request by yujuhong**
Using `continue` would exit the current processing scope.
https://blogs.technet.microsoft.com/msftcam/2015/03/17/powershell-gotcha-foreach-object-and-continue/

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81734

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pjh** [comment]
Weeeeeird. Nice find!

/lgtm

**Comment by yujuhong** [comment]
Verified the fix by manually running the patched script on one of @Random-Liu's Windows nodes. SSH worked for him after that.

**Comment by yujuhong** [comment]
@jingxu97 I think you had issues with SSH before. This may solve your issue.

**Pull request merged**
