### PR TITLE
Cleanup pod print in kubelet package

### PR DESCRIPTION
**Pull request by Random-Liu**
Small cleanup in docker manager.

### CODE REVIEW

**Comment by yifan-gu** [comment]
@Random-Liu Are we planning to retire GetPodFullname entirely? I found there are other places that still use it.

**Comment by Random-Liu** [comment]
@yifan-gu Good question...My understanding is that @yujuhong want to use `format.Pod` instead of `PodFullName` only when printing pod, so that we can change the printing format of pod easily in the future.

**Comment by yifan-gu** [comment]
@Random-Liu sgtm, then how about also cleaning up the prints in prober.go runonce.go as well in this PR to make it more consistent? (Maybe there are other places)

**Comment by Random-Liu** [comment]
Sure~ Thanks! :)

**Comment by Random-Liu** [comment]
@yifan-gu I can also only find prober.go and runonce.go which need to be cleaned up. PTAL, :)

**Comment by yifan-gu** [comment]
LGTM

**Comment by yifan-gu** [comment]
Sorry, do you mind squashing the two commits? As they are really small and related.

**Comment by Random-Liu** [comment]
Sure!

**Comment by Random-Liu** [comment]
Squashed, :)

**Comment by yifan-gu** [comment]
@Random-Liu Thank you, LGTM

**Comment by Random-Liu** [comment]
Sorry, there is an extra import.

**Comment by Random-Liu** [comment]
@k8s-bot e2e test this please.

**Comment by Random-Liu** [comment]
@k8s-bot unit test this please.

**Comment by Random-Liu** [comment]
@k8s-bot unit test this please.

**Comment by yujuhong** [comment]
Thanks for the cleanup and the review!

**Pull request merged**
