### PR TITLE
contrib: Secret generation is too important as not to have an utility

### PR DESCRIPTION
**Pull request by txomon**
This helps creating secrets for volume mounts.

### CODE REVIEW

**Comment by eparis** [comment]
as nothing in repo makes use of this, I believe it would belong in github.com/kubernetes/contrib/

**Comment by txomon** [comment]
We found this in the repo too:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/secret.go

**Comment by pmorie** [comment]
@txomon does this do anything `kubectl create secret` doesn't do?  If not I suggest we close this out.

**Comment by txomon** [comment]
Nope I found it out later, it should be the same as --from-dir

**Comment by pmorie** [comment]
@txomon okay to close this now that you know about kubectl create secret?

**Comment by txomon** [comment]
Yes, sorry, I thought you had already closed it =)

**Pull request closed without merging**
