### PR TITLE
Add quantity and ResourceList jsonpb unmarshaling

### LINKED ISSUE #59: Type resource.Quantity unmarshals with json, but not jsonpb
Hi all.

Given that the API types are actually protobufs, I would expect to use `jsonpb` to Marshal/Unmarshal, not the standard `json` package.

Here was my setup:

```
package clienttest

import (
	"bytes"
	"encoding/json"
	"testing"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/stretchr/testify/assert"

	log "github.com/sirupsen/logrus"
)

func quantityOrDie(s string) resource.Quantity {
	q, err := resource.ParseQuantity(s)
	if err != nil {
		log.Fatal(err)
	}
	return q
}

func getContainer() corev1.Container {
	return corev1.Container{
		Resources: corev1.ResourceRequirements{
			Limits: corev1.ResourceList{
				"cpu": quantityOrDie("0.2"),
				"ram": quantityOrDie("2000000000"),
			},
		},
	}
}

func TestMarshalContainerJsonpb(t *testing.T) {
	c := getContainer()
	m := jsonpb.Marshaler{}
	s, err := m.MarshalToString(&c)
	assert.NoError(t, err, "Could not marshal Container")
	log.WithField("buffer", s).Info("Marshalled Container")

	cc := corev1.Container{}
	u := jsonpb.Unmarshaler{}
	err = u.Unmarshal(bytes.NewBufferString(s), &cc)
	assert.NoError(t, err, "Could not unmarshal Container")
	log.WithField("container", cc.String()).Info("Unmarshalled Container")
}

func TestMarshalContainerJson(t *testing.T) {
	c := getContainer()
	b, err := json.Marshal(c)
	assert.NoError(t, err, "Could not marshal Container")
	log.WithField("buffer", string(b)).Info("Marshalled Container")

	cc := corev1.Container{}
	err = json.Unmarshal(b, &cc)
	assert.NoError(t, err, "Could not unmarshal Container")
	log.WithField("container", cc.String()).Info("Unmarshalled Container")
}
```

The error message is:

```
--- FAIL: TestMarshalContainerJsonpb (0.00s)
    resource_requirements_test.go:47: 
        	Error Trace:	resource_requirements_test.go:47
        	Error:      	Received unexpected error:
        	            	json: cannot unmarshal string into Go value of type map[string]json.RawMessage
        	Test:       	TestMarshalContainerJsonpb
        	Messages:   	Could not unmarshal Container
```

Also, when I switched from `github.com/gogo/protobuf/jsonpb` to `github.com/golang/protobuf/jsonpb` things got even worse:

```
--- FAIL: TestMarshalContainerJsonpb (0.00s)
panic: reflect.Value.Addr of unaddressable value [recovered]
	panic: reflect.Value.Addr of unaddressable value
```

Should I be using the `json` package with these types?

Thanks,
-mk

### PR DESCRIPTION
**Pull request by katrogan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:
See below.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/apimachinery/issues/59

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the PR @katrogan 

the discussion in https://github.com/kubernetes/apimachinery/issues/59 does not suggest that the addition of PB methods and `jsonpb` was approved, but i will defer to the owners.
/cc @liggitt @smarterclayton

**Comment by liggitt** [comment]
It's not clear that supporting jsonpb should be a goal. Can you give more details about why using the stdlib json decoder is insufficient?

If we decide this should be supported, this definitely needs tests demonstrating all API types can be decoded using this method.

**Comment by katrogan** [comment]
hi @liggitt thanks for reviewing!

> It's not clear that supporting jsonpb should be a goal. 

Agreed, however what I'm trying to support in this case is that the default json encoder cannot properly unmarshal the string field name format used by [quantity.proto](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/generated.proto#L86) since the [quantity struct](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go#L88) has a totally different structure.

We are trying to use the generated PodSpec proto and unmarshal that to the corresponding golang struct. We have a python SDK that writes these protos and we read them in a golang service which is why we chose proto as a common message format.

**Comment by liggitt** [comment]
> the default json encoder cannot properly unmarshal the string field name format used by [quantity.proto](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/generated.proto#L86)

this statement is confusing to me... why is a json encoding being used in combination with a proto definition?

**Comment by katrogan** [comment]
>  why is a json encoding being used in combination with a proto definition?

We need some way to unmarshal the proto binary blob into a go struct, for which we've been using jsonpb.  For example, we use our python client to populate the full PodSpec proto, serialize that over the wire and then in our server go code we need a way to unmarshal the proto to a go struct so we can create pod resources. This nearly works except for the one field mismatch in Quantity proto.

**Comment by liggitt** [comment]
> For example, we use our python client to populate the full PodSpec proto, serialize that over the wire and then in our server go code we need a way to unmarshal the proto to a go struct

would something like this work?
```go
podSpec := &v1.PodSpec{}
err := podSpec.Unmarshal(data)
...
```

**Comment by liggitt** [comment]
/close

It's not clear that this is a use case we intend to support. Adding piecemill support/fixes to enable something we don't test for or expect our types to be used for will not provide long-term stability for those use cases, which is essential in an API.

**Pull request closed without merging**
