### PR TITLE
Scheduler: remove outdated TODO in node_affinity.go

### PR DESCRIPTION
**Pull request by gavinfish**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Both preFilter and preScore are ready. I think it is time to remove this.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gavinfish** [comment]
> Can you rather try to remove the whole file?
> I think we should be ready to do it now.

PodTopologySpread plugin also depends on this file. I have created an issue #99786 to track it.

Besides, some other components like daemonset and kubelet also depends on it for predication.

**Comment by alculquicondor** [comment]
kubelet and daemonset should be using the component-helpers package instead. @AliceZhang2016 is looking into that.

**Pull request merged**
