### PR TITLE
feat: use framework.ExpectEqual instead of should

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig testing
/assign @oomichi 

**What this PR does / why we need it**:

use framework.ExpectEqual instead of should in e2e test

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
Thanks for doing this.
/lgtm

**Comment by derekwaynecarr** [comment]
node changes look good.

/approve

**Comment by draveness** [comment]
Hi @oomichi, this needs approval from you. :)

**Comment by bskiba** [comment]
/approve
For autoscaling changes. Thanks!

**Comment by oomichi** [comment]
@draveness  Now I am happy to approve after seeing multiple `/approve` :-)

/approve

**Comment by draveness** [comment]
Thank you all for the reviews. 😁

**Pull request merged**
