### PR TITLE
Keep track of remaining pods when a node is deleted

### PR DESCRIPTION
**Pull request by alculquicondor**
Cherry pick of #93938

**What type of PR is this?**

/kind bug

**Does this PR introduce a user-facing change?**:

```release-note
Scheduler bugfix: Scheduler doesn't lose pod information when nodes are quickly recreated. This could happen when nodes are restarted or quickly recreated reusing a nodename.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
@kubernetes/release-managers

**Comment by alculquicondor** [comment]
ping @kubernetes/release-managers

**Comment by alculquicondor** [comment]
please review this important fix @kubernetes/release-managers

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
