### PR TITLE
update cephfs e2e test from v1beta3 to v1

### LINKED ISSUE #17964: ceph e2e says v1beta3
test/e2e/volumes.go

```
559     ////////////////////////////////////////////////////////////////////////
560     // Ceph
561     ////////////////////////////////////////////////////////////////////////
562 
563     Describe("CephFS", func() {
564         It("should be mountable", func() {
565             config := VolumeTestConfig{
566                 namespace:   namespace.Name,
567                 prefix:      "cephfs",
568                 serverImage: "gcr.io/google_containers/volume-ceph",
569                 serverPorts: []int{6789},
570             }
571 
572             defer func() {
573                 if clean {
574                     volumeTestCleanup(c, config)
575                 }
576             }()
577             pod := startVolumeServer(c, config)
578             serverIP := pod.Status.PodIP
579             Logf("Ceph server IP address: %v", serverIP)
580             By("sleeping a bit to give ceph server time to initialize")
581             time.Sleep(20 * time.Second)
582 
583             // create ceph secret
584             secret := &api.Secret{
585                 TypeMeta: unversioned.TypeMeta{
586                     Kind:       "Secret",
587                     APIVersion: "v1beta3",
588                 },
```

@rootfs @markturansky

### PR DESCRIPTION
**Pull request by rootfs**
fix #17964

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by ixdy** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
This PR is actually only changing the test that is "[Skipped]". So applying e2e-not-required label.

**Pull request merged**
