### PR TITLE
Add back anti-affinity to CoreDNS pods

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Following #90248, adding back pod anti-affinity to CoreDNS pods
 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by MrHohn** [comment]
cc @prameshj

**Comment by prameshj** [comment]
/lgtm

eventually, we should consider using Topology Spreading(which is expected to be GA in 1.20) to achieve this. I have a WIP PR for it - https://github.com/kubernetes/kubernetes/pull/90867/files

cc @alculquicondor

**Comment by alculquicondor** [comment]
Topology Spreading is going GA in 1.19. Please update.

**Pull request merged**
