### PR TITLE
Fix errorf for get test

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
If the error messages do not use format, use t.Error() will be fine.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
ping @brendandburns 
PTAL

**Comment by CaoShuFeng** [comment]
We also have glog.Infof() glog.Warningf().
Will we update them all?

**Comment by zhangxiaoyu-zidif** [comment]
@fabianofranz 
PTAL

**Pull request merged**
