### PR TITLE
Promote E2E test to verify job completion after successful tasks completion to conformance

### PR DESCRIPTION
**Pull request by globervinodhn**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: This PR requests to promote an existing e2e test with respect to job completion to conformance. The e2e creates a job and waits until the associated pods/tasks execute successfully. Once done, the job must reach completion status.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**: The existing E2E test case requested for promotion is the simplest test case to verify job behaviour. The created JOB should reach completion status once the assigned tasks are completed successfully. The test is found to be non-flaky, non-disruptive in nature. Existing E2E case executes in 12 seconds.

**Does this PR introduce a user-facing change?**: NONE

release-note-none

cc @brahmaroutu @mgdevstack 

/area conformance

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm
/approve 
/hold 
/assign @bgrant0607 

Jobs are v1 so I'm ok with this promotion.

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by bgrant0607** [comment]
The way Job determines completion is fundamentally unsound. 

https://github.com/kubernetes/kubernetes/issues/28486

I suggest we don't promote this to conformance until that is resolved.

**Comment by timothysc** [comment]
I'm going to close this PR given the previous comment as we'd need to fix the tests first.

**Pull request closed without merging**
