### PR TITLE
Add checking the nil value 

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

Add checking the nil value.

Thanks.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The change looks good, but the file is generated. Could you modify the template [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/client-gen/generators/generator_for_clientset.go#L151), and run hack/update-codegen.sh? Thanks.

**Comment by tanshanshan** [comment]
hi, @caesarxuchao , 

> Conflicting files
federation/client/clientset_generated/federation_release_1_5/clientset.go
pkg/client/clientset_generated/release_1_5/clientset.go

@k8s-merge-robot says there are two Conflicting files, but I can not find these two files in  kubernetes:master,  so, how do I  deal with the  need-rebase  label?
Thanks.

**Comment by caesarxuchao** [comment]
What does "git rebase" say?

**Comment by tanshanshan** [comment]
@caesarxuchao ,  I check my operation ,

> > git rebase upstream/master

the result is 

> Using index info to reconstruct a base tree...
> A       federation/client/clientset_generated/federation_release_1_5/clientset.go
> A       pkg/client/clientset_generated/release_1_5/clientset.go
> Falling back to patching base and 3-way merge...
> Auto-merging pkg/client/clientset_generated/clientset/clientset.go
> Auto-merging federation/client/clientset_generated/federation_clientset/clientset.go

so  I  execute git push  ,  the need-rebase has been gone.

And ,  why not the robot give me a lgtm label?

Thanks

**Comment by tanshanshan** [comment]
hi @caesarxuchao , could you give me a lgtm label, Thanks.

**Comment by caesarxuchao** [comment]
I guess I need to put "\lgtm" in a separate comment.

**Comment by caesarxuchao** [comment]
Could you run hack/update-codegen.sh again and squash the changes in the same commit?

**Comment by tanshanshan** [comment]
hi @caesarxuchao  ,the robot does not give me a lgtm label , 
Sorry to disturb you many times.

Thanks.

**Comment by caesarxuchao** [comment]
This still lgtm. I'm OOO these weeks. Please contact @lavalamp if this doesn't get merged.

**Pull request merged**
