### PR TITLE
pkg/kubeapiserver: fix staticcheck warning

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

fix staticcheck warning

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @deads2k 
/unassign

not sure whether there was a reason for those extra fields in the admission initializer

**Comment by BenTheElder** [comment]
/kind cleanup
/priority important-longterm
needs a rebase

**Comment by hwdef** [comment]
@BenTheElder 
Cloud you please add a lgtm label for this PR?
Thank you very much!

**Pull request merged**
