### PR TITLE
Upgraded cloud config template for CoreOS/azure to kubernetes 1.1.2

### PR DESCRIPTION
**Pull request by kikov79**

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM 

@colemickens any thoughts?

**Comment by brendandburns** [comment]
Oh, and 1.1.2 is now out...  Upgrade to 1.1.2?

**Comment by kikov79** [comment]
Ok, give me a second.

**Comment by colemickens** [comment]
LGTM but I have not tested it or looked at this setup in many months at this point.

**Comment by brendandburns** [comment]
@kikov79 I'm assuming you tested this?  If you confirm that it works for you, I'm ok w/ merging.

**Comment by kikov79** [comment]
Yes, I'm running a kubernetes 1.1.2 cluster using this method.
There are still some missing features (i.e. AdmissionControl) I would like to work on.

**Comment by brendandburns** [comment]
LGTM, thanks for the PR.

**Pull request merged**
