### PR TITLE
Make hack/update_codecgen.sh script work after previous failure

### PR DESCRIPTION
**Pull request by wojtek-t**
cc @thockin @davidopp

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek PTAL

**Comment by thockin** [comment]
is 'touch' right?  Or should we `git co --` them ?

**Comment by gmarek** [comment]
This whole script is a terrible mess... Is there a reason why you don't want to just substitute the old trap with new one? Touching existing files shouldn't break anything.

**Comment by wojtek-t** [comment]
>
is 'touch' right? Or should we git co -- them ?

@thockin git co is not needed, because those files are already committed

**Comment by wojtek-t** [comment]
>
Is there a reason why you don't want to just substitute the old trap with new one? 

@gmarek - yeah, you're right we can do it. I can do it tomorrow.

**Comment by wojtek-t** [comment]
@gmarek - PTAL

**Pull request merged**
