### PR TITLE
Keep the comment name consistent with the function name

### PR DESCRIPTION
**Pull request by xichengliudui**
/kind cleanup
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for this fix!

Out of curiosity, do you know if this causes this file to pass `golint`? If so, can you please remove this file from `hack/.golint_failures`?

**Comment by xichengliudui** [comment]
@mattjmcnaughton  Thanks for the tip.

**Pull request closed without merging**
