### PR TITLE
Remove packages which are now apimachinery

### PR DESCRIPTION
**Pull request by deads2k**
Removes all the content from the packages that were moved to `apimachinery`.  This will force all vendoring projects to figure out what's wrong.  I had to leave many empty marker packages behind to have verify-godep succeed on vendoring heapster.

@sttts straight deletes and simple adds

### CODE REVIEW

**Comment by sttts** [comment]
Looks good in general. But tests must be green.

Best regards,
   Stefan

**Comment by deads2k** [comment]
I think this waits on https://github.com/kubernetes/kubernetes/pull/39916

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Comment by deads2k** [comment]
Noooooooooo

**Comment by deads2k** [comment]
@k8s-bot test this

**Pull request merged**
