### PR TITLE
Remove spammy logs in tests

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #44707

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #44757

**Comment by gmarek** [comment]
\lgtm

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #44757

**Comment by wojtek-t** [comment]
Applying label based on https://github.com/kubernetes/kubernetes/pull/44761#issuecomment-296166814 comment

**Pull request merged**
