### PR TITLE
Improve performance for VMSS LoadBalancerBackendAddressPools updates

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/sig cloud-provider
/kind bug
/area provider/azure
/priority important-soon
/milestone v1.18

**What this PR does / why we need it**:

Improve performance for VMSS LoadBalancerBackendAddressPools updates. Since multiple VMSS instance's LoadBalancerBackendAddressPools doesn't support concurrent updating, this PR changes the updating logic to squential-sync + concurrent-async requests. In this way, the performance of VMSS LoadBalancerBackendAddressPools updates would be improved a lot.

Here is a performance comparison for 31 nodes (1 vmss with 30 nodes + 1 vmss with 1 node) cluster:

| | EnsureHostsInPool (old->new)  |   EnsureBackendPoolDeleted (old->new)|
|---|---|---|
|Standard LB  |11m30s -> 1m43s    |    7m30s -> 3m30s|
|Basic LB   |  27m50s -> 1m9s    |     5m8s  -> 1m3s|

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is continue of https://github.com/kubernetes/kubernetes/pull/88094, which would only included in 1.18.

**Does this PR introduce a user-facing change?**:

```release-note
Azure VMSS LoadBalancerBackendAddressPools updating has been improved with squential-sync + concurrent-async requests.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
where is `UpdateVMs()` func invoked? is this PR completed?

**Comment by feiskyer** [comment]
@andyzhangx See https://github.com/kubernetes/kubernetes/pull/88699/files#diff-1479a5428f7074b3c03f815cec378b13R1114 and
https://github.com/kubernetes/kubernetes/pull/88699/files#diff-1479a5428f7074b3c03f815cec378b13R1414

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
