### PR TITLE
mount-utils: force-format xfs-filesystems too

### LINKED ISSUE #4: xfs: missing args
https://github.com/kubernetes/mount-utils/blob/master/mount_linux.go#L436 does only cater for ext3/ext4.
I think there should be an check for xfs too, which adds `-f` to force format, or else you might end up with:

```
I0909 20:35:40.848768       1 grpc.go:72] GRPC call: /csi.v1.Node/NodePublishVolume requests {"target_path":"/var/lib/kubelet/pods/179a5e86-43a5-43f7-b78e-b11af4368674/volumes/kubernetes.io~csi/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"prometheus-k8s-1","csi.storage.k8s.io/pod.namespace":"openshift-monitoring","csi.storage.k8s.io/pod.uid":"179a5e86-43a5-43f7-b78e-b11af4368674","csi.storage.k8s.io/serviceAccount.name":"prometheus-k8s","openebs.io/cas-type":"localpv-lvm","openebs.io/volgroup":"datavg","storage.kubernetes.io/csiProvisionerIdentity":"1631215660348-8081-local.csi.openebs.io"},"volume_id":"pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937"}
I0909 20:35:40.864001       1 mount_linux.go:366] Disk "/dev/datavg/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/datavg/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937]
I0909 20:35:41.646181       1 mount_linux.go:376] Disk successfully formatted (mkfs): xfs - /dev/datavg/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937 /var/lib/kubelet/pods/179a5e86-43a5-43f7-b78e-b11af4368674/volumes/kubernetes.io~csi/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937/mount
E0909 20:35:41.648622       1 mount_linux.go:150] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/datavg/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937 /var/lib/kubelet/pods/179a5e86-43a5-43f7-b78e-b11af4368674/volumes/kubernetes.io~csi/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937/mount
Output: mount: /var/lib/kubelet/pods/179a5e86-43a5-43f7-b78e-b11af4368674/volumes/kubernetes.io~csi/pvc-d5be05a4-f5f8-4b7e-83b3-b53eaaff8937/mount: wrong fs type, bad option, bad superblock on /dev/mapper/datavg-pvc--d5be05a4--f5f8--4b7e--83b3--b53eaaff8937, missing codepage or helper program, or other error.
```

i.e. xfs filesystems are not force-formatted

### LINKED ISSUE #135: fails to format
**What steps did you take and what happened:**

```
   ----              ----               -------
  Warning  FailedScheduling  6m2s              default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: selectedNode annotation reset for PVC "elasticsearch-elasticsearch-cdm-4qo1qel7-1"
  Normal   Scheduled         16s               default-scheduler  Successfully assigned openshift-logging/elasticsearch-cdm-4qo1qel7-1-6db94d4d88-lwtv7 to alp-dts-g-c01oco09
  Warning  FailedMount       5s (x5 over 13s)  kubelet            MountVolume.SetUp failed for volume "pvc-c9073859-fd54-4890-b444-b96e6f46dea1" : rpc error: code = Internal desc = failed to format and mount the volume error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/datavg/pvc-c9073859-fd54-4890-b444-b96e6f46dea1 /var/lib/kubelet/pods/0c34d38c-88f0-4a1c-bf6f-02e6b3ab05cd/volumes/kubernetes.io~csi/pvc-c9073859-fd54-4890-b444-b96e6f46dea1/mount
Output: mount: /var/lib/kubelet/pods/0c34d38c-88f0-4a1c-bf6f-02e6b3ab05cd/volumes/kubernetes.io~csi/pvc-c9073859-fd54-4890-b444-b96e6f46dea1/mount: wrong fs type, bad option, bad superblock on /dev/mapper/datavg-pvc--c9073859--fd54--4890--b444--b96e6f46dea1, missing codepage or helper program, or other error.

```

beacause:

```
 mkfs.xfs /dev/datavg/pvc-c9073859-fd54-4890-b444-b96e6f46dea1
mkfs.xfs: /dev/datavg/pvc-c9073859-fd54-4890-b444-b96e6f46dea1 appears to contain an existing filesystem (xfs).
mkfs.xfs: Use the -f option to force overwrite.
```

Maybe it should force by default or some notes added to the docs.

**What did you expect to happen:**
formatting should happen

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LVM Driver version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

#### What type of PR is this?

/kind bug
/sig storage

#### What this PR does / why we need it:

XFS filesystems are not force-formatted, this might lead to failures as initially experienced in https://github.com/openebs/lvm-localpv/issues/135 

#### Which issue(s) this PR fixes:

Fixes: https://github.com/openebs/lvm-localpv/issues/135
Fixes: https://github.com/kubernetes/mount-utils/issues/4

*Should I maybe clone the issue into this repo?*

#### Special notes for your reviewer:
See similar behaviour for ext3/4 filesystems.

#### Does this PR introduce a user-facing change?
NONE

```release-note
XFS-filesystems are now force-formatted (option `-f`) in order to avoid problems being formatted due to detection of magic super-blocks. This aligns with the behaviour of formatting of ext3/4 filesystems.
```

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@saad-ali ptal?

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @jingxu97

For approval.

**Comment by saad-ali** [comment]
I'd like to make sure I understand this: Format shouldn't happen if there is no filesystem. What would cause this code path to be hit (i.e. no filesystem detected, but format fails because a filesystem exists)? I couldn't quite follow https://github.com/openebs/lvm-localpv/issues/135
Is this a "hammer" approach masking other bugs?

I checked the PR that introduced force for ext3/ext4 formatting (https://github.com/kubernetes/utils/pull/127) and I didn't see a good explanation there either.

**Comment by sastorsl** [comment]
> Is this a "hammer" approach masking other bugs?

The code relies on underlying OS tooling which simply checks the volume for traces of file systems, and gives you a warning that you are about to overwrite a file system you _possibly_ hold dear - "are you really sure...".

The _default_ behavior of `mkfs` is to stop at this point.

This is fine in a manual environment, but with regards to automatically provisioning file systems this will only halt provisioning needlessly. You create and remove file systems all the time, so there will quickly be traces of old file systems all the time.

> -f     Force overwrite when an existing filesystem is detected on the device. By default, mkfs.xfs will not write to the device if it suspects that there is a filesystem or partition table on the device already.

When creating a logical volume, _lvm_ will take what is marked as **available**. This is your security.

Then mkfs comes in and creates a file system.
Yes, there are traces of an old file system there, it is to be expected, and must be passed, hence the `-f`.

**Review by saad-ali — APPROVED** [review]
> You create and remove file systems all the time, so there will quickly be traces of old file systems.
> Yes, there are traces of an old file system there, it is to be expected, and must be bypassed, hence the -f.

SGTM, thanks!

/lgtm
/approve

**Pull request merged**
