### PR TITLE
fix cache.Get error handling on bad key

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, argh

**Comment by lavalamp** [comment]
Introduced in #3810, along with other instances. @mikedanese can you double check that the others that PR added have been fixed (or commented with explanation)?

**Comment by mikedanese** [comment]
In #3810, all other ignored errors are in test

**Comment by smarterclayton** [comment]
Another reason why named return parameters can be bad - fake shadowing.

**Pull request merged**
