### PR TITLE
kubeadm-init: add details about --token

### LINKED ISSUE #768: help string for kubeadm --token does not mention the syntax
## What keywords did you search in kubeadm issues before filing this one?

token syntax

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

- **Cloud provider or hardware configuration**: local hardware
- **OS** (e.g. from /etc/os-release): 16.04.4 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): Linux mjs-api-dal10-a 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
I tried a token with a different syntax and kubeadm failed with a complaint that mentions the required syntax.

## What you expected to happen?
I expected success regardless of token syntax, because the restriction on token syntax is not documented.

## How to reproduce it (as minimally and precisely as possible)?
Just try `kubeadm init` with a config file or command line flag that supplies a token with the wrong syntax.

## Anything else we need to know?
Nothing.

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
Add details about the required format when passing
a bootstrap token using 'kubeadm init --token'.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#768

**Special notes for your reviewer**:

NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/area kubeadm
/sig cluster-lifecycle

@kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
Thanks!

**Pull request merged**
