### PR TITLE
Enabling fluentd on kubemark

### PR DESCRIPTION
**Pull request by krzysied**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Enabling fluentd pods in kubemark cluster. Those pods will be "running" on hollow nodes.
We want to make number of kubemark system pods as close to standard cluster as possible.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Let me hold it then - @krzysied - please investigate.

/hold

**Comment by krzysied** [comment]
@wojtek-t I couldn't reproduce this issue locally.  I also spotted that recently this presubmit passed. Based on the logs, there was a problem with gce node at that time. This affected kubemark cluster health.
Example from the kubemark kube-controller-manager log:
```
I1016 15:36:42.888616       1 controller_utils.go:169] Recording status change NodeNotReady event message for node hollow-node-7r6st
```
This corresponds with pods being ready but not running.

IMHO the issue was unrelated to this PR.

**Comment by krzysied** [comment]
Run 1184476931924430848:
```
I1016 15:39:48.494569       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 15:39:48.494551124 +0000 UTC m=+2013.306587713. Adding it to the Taint queue.
I1016 15:41:03.505182       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-jskq is NotReady as of 2019-10-16 15:41:03.505172325 +0000 UTC m=+2088.317208905. Adding it to the Taint queue.
I1016 15:43:28.538981       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-lkr9 is NotReady as of 2019-10-16 15:43:28.538965866 +0000 UTC m=+2233.351002446. Adding it to the Taint queue.
I1016 15:43:43.552600       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-tppt is NotReady as of 2019-10-16 15:43:43.552585846 +0000 UTC m=+2248.364622451. Adding it to the Taint queue.
I1016 15:44:03.562141       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 15:44:03.562133848 +0000 UTC m=+2268.374170439. Adding it to the Taint queue.
I1016 16:02:13.697178       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 16:02:13.697160643 +0000 UTC m=+3358.509197235. Adding it to the Taint queue.
I1016 16:05:38.730802       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 16:05:38.730786096 +0000 UTC m=+3563.542822687. Adding it to the Taint queue.
I1016 16:08:58.762594       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 16:08:58.762578521 +0000 UTC m=+3763.574615109. Adding it to the Taint queue.
I1016 16:13:28.800134       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 16:13:28.80009128 +0000 UTC m=+4033.612127855. Adding it to the Taint queue.
I1016 16:16:48.830634       1 node_lifecycle_controller.go:825] Node e2e-83897-ac87c-minion-group-nsr8 is NotReady as of 2019-10-16 16:16:48.830621681 +0000 UTC m=+4233.642658270. Adding it to the Taint queue.
```
There are only serial logs so it's impossible to debug further.

**Comment by krzysied** [comment]
Exmaple of failed run https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84020/pull-kubernetes-kubemark-e2e-gce-big/1184697512951287808
This run failed the same way is ones from current PR.

**Comment by mm4tt** [comment]
I agree with @krzysied, the failures doesn't seem related to this PR, especially given that Krzysiek found other run that failed in the same way and was in no way related to this PR.
Let's merge it and keep and eye on the next kubemark runs (both presubmits and CI tests).

/lgtm
/hold cancel

**Comment by krzysied** [comment]
/test pull-kubernetes-e2e-gce

Retesting gce e2e test. IMHO changes in kubemark script shouldn't have impact on gce test.

**Pull request merged**
