### PR TITLE
Fix node upgrade in e2e tests

### PR DESCRIPTION
**Pull request by wojtek-t**
This is fixing automatic ugprade tests in GCE

@davidopp @pwittrock

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32779)

### CODE REVIEW

**Comment by gmarek** [comment]
@pwittrock - if we want to run automatic upgrade tests on 1.4 branch we need to cherry-pick this.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this, issue: #32548

**Comment by davidopp** [comment]
LGTM

**Comment by pwittrock** [comment]
@foxish Can you cherrypick this as a one-off before doing any others?

**Comment by pwittrock** [comment]
Does this need to be in 1.2 and 1.3 as well?

**Comment by davidopp** [comment]
> Does this need to be in 1.2 and 1.3 as well?

Maisem seemed to imply yes.

**Comment by pwittrock** [comment]
Alright, we should make sure the script being invoked exists in the right place in those branches.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this, issue: #32548

**Comment by pwittrock** [comment]
This shouldn't require retest since it is only for upgrades which aren't done anyway right?

**Comment by wojtek-t** [comment]
@pwittrock - correct; adding retest-not-required.

**Pull request merged**
