### PR TITLE
Fix preventing addon RCs that dont have version and similar prefixes from being deleted

### LINKED ISSUE #20125: kube-addons identifies monitoring-grafana and monitoring-influxdb as the same RC spec
kube-addons today identifies RC specs by only matching the prefix assuming that suffix will always be a version number ex:monitoring-grafana-v1. Ideally we should just check if the entire string matches both in server and on file and delete/create RCs as and when needed.

By placing two RC specs monitoring-grafana and monitoring-influxdb as a cluster addon, what happens is that monitoring-influxdb keeps getting deleted as the addons update script assumes that a newer version is available for update. This causes influxdb RC to be deleted and recreated periodically whenever the addon update script is triggered. Should we have mandate for version number to be present always in RC? We dont have that check in place for Service specs. Doing full string match should cover the use cases of: 
1) newer version of the RC being available if a version suffix is present.
2) delete RCs for whom the spec is no longer available
3) create RC for a newly available spec.

Also, for the rolling upgrade of RC specs, would it make sense if the versions can be pulled from something like labels within the RC spec instead of going for file names?

### PR DESCRIPTION
**Pull request by vjsamuel**
Fixes #20125

### CODE REVIEW

**Comment by brendandburns** [comment]
@davidopp for triage.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
This makes it so we can't update an addon by modifying the version in the name.

**Comment by davidopp** [comment]
@mikedanese - so you're saying this PR is not a good idea?

**Comment by mikedanese** [comment]
Yes this looks broken as is.

**Pull request closed without merging**
