### PR TITLE
Disable all alpha feature gates by default in local-up-cluster.sh

### LINKED ISSUE #46691: No nodes resources in local cluster.
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
```
[root@ib15b13 kubernetes]# kc version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.835+77a8c258391f30", GitCommit:"77a8c258391f30bb1d99c8eef0aba79218eaa445", GitTreeState:"clean", BuildDate:"2017-05-31T07:16:40Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.835+77a8c258391f30", GitCommit:"77a8c258391f30bb1d99c8eef0aba79218eaa445", GitTreeState:"clean", BuildDate:"2017-05-31T07:16:40Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): RHE 7.2
- **Kernel** (e.g. `uname -a`): `Linux ib15b13.eng.platformlab.ibm.com 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:
The node resource is empty when start local cluster by `./hack/local-up-cluster.sh`.

**What you expected to happen**:
There's one node in this local cluster.

**How to reproduce it** (as minimally and precisely as possible):

```
./hack/local-up-cluster.sh
kubectl get nodes
```

### PR DESCRIPTION
**Pull request by wanghaoran1988**
**What this PR does / why we need it**:
Disable all alpha feature gates by default in local-up-cluster.sh
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46691

**Special notes for your reviewer**:

**Release note**:
```
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by liggitt** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by ncdc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this #46713

**Comment by cblecker** [comment]
etcd failure is related to https://github.com/kubernetes/kubernetes/issues/46713

**Review by k82cn — APPROVED** [review]

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
