### PR TITLE
Bump GCI version to gci-dev-56-8938-0-0 for k8s v1.5

### PR DESCRIPTION
**Pull request by mtaufen**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35877)

### CODE REVIEW

**Comment by mtaufen** [comment]
GKE smoke failed trying to create a firewall:
```
W1030 11:33:15.388] ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
W1030 11:33:15.388]  - Internal Error
W1030 11:33:15.388] 
W1030 11:33:25.868] Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-pr-gke/global/firewalls/e2e-gke-agent-pr-53-0-http-alt].
I1030 11:33:25.987] NAME                            NETWORK                SRC_RANGES  RULES            SRC_TAGS  TARGET_TAGS
I1030 11:33:25.988] e2e-gke-agent-pr-53-0-http-alt  e2e-gke-agent-pr-53-0  0.0.0.0/0   tcp:80,tcp:8080            gke-e2e-gke-agent-pr-53-0-522e6c41-node,k8s-e2e-gke-agent-pr-53-0-node
W1030 11:33:26.023] ... gke:test-setup(): Could not create firewall
W1030 11:33:26.023] 2016/10/30 11:33:26 e2e.go:723: Step 'up' finished in 3m34.783767764s
W1030 11:33:26.023] 2016/10/30 11:33:26 e2e.go:721: Running: teardown
```

**Comment by mtaufen** [comment]
@k8s-bot GKE test this

**Comment by mtaufen** [comment]
@k8s-bot unit test this

**Comment by mtaufen** [comment]
@k8s-bot cvm gke e2e test this

**Comment by vishh** [comment]
What is the changelog? Can you obtain that from the GCI team?

**Comment by mtaufen** [comment]
Looks like it will be along the lines of:

**[gci-dev-56-8938-0-0](#gci-dev-56-8938-0-0)**
Kernel     [ChromiumOS-4.4](https://chromium.googlesource.com/chromiumos/third_party/kernel/+/67a3c2abbff92d91f14964cae7a5826826a3c5d8)
Kubernetes v1.4.4

But the final changelog update hasn't gone in yet.

**Comment by vishh** [comment]
I'd like to soak this PR for a couple of days before the freeze. LGTM'ing it.

**Pull request merged**
