### PR TITLE
Replace map[string]string with labels.Set (TODO)

### LINKED ISSUE #27274: TODO: replace map[string]string with labels.LabelSet type
pkg/api/types.go:133

### PR DESCRIPTION
**Pull request by nebril**
fixes #27274

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/27275)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test.

Same TODO exists in v1/types.go as well. Changing that will be an API change.
cc @kubernetes/api-review-team

**Comment by nikhiljindal** [comment]
Assigning to @erictune for API review

**Comment by lavalamp** [comment]
> Same TODO exists in v1/types.go

Please remove that TODO, it's definitely not a change we'd want to make.

I'm kind of on the fence about this change, to be honest. I'd probably be less conflicted about a change that simply removed the TODO. This adds a dependency to the api types that I'd just as soon not add. It's not that important for the internal types though...

**Comment by nebril** [comment]
OK, I will revert this change and simply remove both TODOs in the commit.

**Comment by lavalamp** [comment]
LGTM thanks for bearing with me :)

**Comment by lavalamp** [comment]
ok to test

@k8s-bot test this issue: #IGNORE

**Comment by nebril** [comment]
@lavalamp I didn't know that generated protobuffs copied comments. TIL.

**Comment by lavalamp** [comment]
:)

**Pull request merged**
