### PR TITLE
Fix wc zombie goroutine issue in volume util

### PR DESCRIPTION
**Pull request by dashpole**
See [Cadvisor #1558](https://github.com/google/cadvisor/pull/1558).  This should solve problems for those using images that do not support "wc".
cc: @timstclair

### CODE REVIEW

**Comment by timstclair** [comment]
Can we change the cAdvisor method to a function (it doesn't need the `RealFSInfo` object), and just call that from here instead of duplicating the logic?

**Comment by dashpole** [comment]
Sure.  My plan is to replace all of this code with cAdvisor function calls once core metrics are established.

**Comment by dashpole** [comment]
But I can start here, I guess.

**Comment by dashpole** [comment]
@vish, this shouldnt need a release label.

**Comment by calebamiles** [comment]
@saad-ali, I think this needs to be cherry picked onto 1.5. Can we make that happen?

**Comment by saad-ali** [comment]
> @saad-ali, I think this needs to be cherry picked onto 1.5. Can we make that happen?

Yes. @dashpole feel free to cherry-pick this and associated PRs. Please assign cherry pick PRs to me.

**Comment by zakharovvi** [comment]
Hello!

Could you please cherry-pick this fix to 1.4 branch too? 

We had 30k+ zombie 'wc -l' processes on some nodes last time.

**Pull request merged**
