### PR TITLE
Update CHANGELOG link of older releases

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
CHANGELOG dir is changed，fix page 404 error
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
LGTM

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Thanks for the cleanup!
/lgtm
/approve

**Pull request merged**
