### PR TITLE
Reduce kubelet LOC: extract getters

### PR DESCRIPTION
**Pull request by pmorie**
Step 1 of #25028 as discussed in @kubernetes/sig-node meeting

### CODE REVIEW

**Comment by ncdc** [comment]
Wouldn't it make more sense to just call the file getters.go? We're already in the kubelet package/directory.

**Comment by yujuhong** [comment]
> Wouldn't it make more sense to just call the file getters.go? We're already in the kubelet package/directory.

I think `kubelet_getters.go` is fine because these are methods of the `Kubelet` type.

**Comment by yujuhong** [comment]
@pmorie Besides moving the code to a new file, did you modify anything?

**Comment by pmorie** [comment]
@ncdc 

> Wouldn't it make more sense to just call the file getters.go? We're already in the kubelet package/directory.

I originally called it that, but not all the files contain kubelet code.  For now, I want to refactor to all kubelet proper files being called `kubelet_*.go`.  In a vacuum, no, I wouldn't normally call this `kubelet_getters.go`, though.

**Comment by pmorie** [comment]
@yujuhong Nope, it is 100% translation, not transformation.

**Comment by yujuhong** [comment]
Marked e2e-not-required since there is no real change in this PR (just move code to a new file), and have already passed per-PR e2e/unit/integration tests.

**Pull request merged**
