### PR TITLE
Adding cascading deletion support to more federation controllers

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref #33612

Adding cascading deletion support for federated daemonsets and ingress.
The code is same as that for namespaces. Just ensuring that DeletionHelper functions are called at right places in these controllers.
e2e tests coming up in another PR.

cc @kubernetes/sig-cluster-federation @caesarxuchao @madhusudancs @mwielgus

```release-note
federation: Adding support for DeleteOptions.OrphanDependents for federated daemonsets and ingresses. Setting it to false while deleting a federated daemonset or ingress also deletes the corresponding resource from all registered clusters.
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36330)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Pushed another commit for autogenerated bazel and test owner changes to fix tests

**Comment by nikhiljindal** [comment]
Rebased

**Comment by nikhiljindal** [comment]
Updated the code to include fix from https://github.com/kubernetes/kubernetes/pull/36377 in all these controllers

**Comment by madhusudancs** [comment]
@nikhiljindal code generally looks good to me. I suppose these are all similar to each other and similar to the changes in the namespace controller?

**Comment by nikhiljindal** [comment]
Yes thats right.
Mostly just copy paste and search replace :)

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this

**Comment by nikhiljindal** [comment]
I am seeing the same unit test flakiness in daemonset and ingress tests as https://github.com/kubernetes/kubernetes/issues/36422. Will include the same fix here.

Forked out the commits for replicaset and deployment out to https://github.com/kubernetes/kubernetes/pull/36476 since they do not require any change.

**Comment by nikhiljindal** [comment]
secret test failed. Rebased to include https://github.com/kubernetes/kubernetes/pull/36463

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this

**Comment by nikhiljindal** [comment]
Rebased the PR and disabled flaky tests as per https://github.com/kubernetes/kubernetes/issues/36540

**Comment by nikhiljindal** [comment]
Readding LGTM after rebase

**Pull request merged**
