### PR TITLE
Cleaned up lint errors in pkg/kubeapiserver/server.

### PR DESCRIPTION
**Pull request by cheftako**
**What this PR does / why we need it**:
Fixes lint errors in pkg/kubeapiserver/server.
Enables lint testing of pkg/kubeapiserver/server.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes part of issues/68026

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by cheftako** [comment]
cc @fedebongio

**Comment by cheftako** [comment]
Hi @yue9944882 I get the idea. Personally I think we should encourage small PRs like this. They are easy to inspect and know they are correct which makes them easier to review and approve than larger PRs which hit many files and cover a variety of different fixes. Should we need to roll it back we are rolling back just the problematic code and not other things as well. Lastly I think we need to encourage participation /engagement in the project. Indicating to people we won't accept their work unless they do more may not be the best way to go about that.

**Comment by yue9944882** [comment]
> They are easy to inspect and know they are correct which makes them easier to review and approve than larger PRs which hit many files and cover a variety of different fixes.

take this pull as example, the requested owner area is `pkg/kubeapiserver`. tho we involve more sub-pkgs under it, it's doesn't request any more load of owners. but yeah, putting several pkgs into a pull makes it a bit harder to review but maybe we can divide the change into several logical commits to sort things clear. especially for such one-liner pulls. 

it's just a polite suggestion. my point is that if we deal with the pkgs one-by-one, it'll possibly take us year-ish time to close the issue.

**Pull request merged**
