### PR TITLE
[Federation][init-02] Stop passing command factory to the init command.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PR #35856 which will be reviewed independently.

Design Doc: PR #34484

cc @kubernetes/sig-cluster-federation @nikhiljindal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35859)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM, thanks @madhusudancs

**Comment by madhusudancs** [comment]
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
Adding `retest-not-required` label because it only touches federation.

**Pull request merged**
