### PR TITLE
fix static check in kubectl/pkg/cmd/annotate.

### PR DESCRIPTION
**Pull request by haosdent**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:

Fix static check failures in kubectl/pkg/cmd/annotate

**Which issue(s) this PR fixes**:

Ref: #81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by haosdent** [comment]
@SataQiu could you help to review this? Thank you in advance.

**Review by SataQiu — COMMENTED** [review]
Thanks @haosdent 
/approve 
for hack

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
