### PR TITLE
Fix some typo err

### PR DESCRIPTION
**Pull request by zhangmingld**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shubheksha** [comment]
@zhangmingld, can you change the release note to `NONE`?

**Comment by ravisantoshgudimetla** [comment]
Thanks for the PR @zhangmingld

**Comment by zhangmingld** [comment]
> @zhangmingld, can you change the release note to `NONE`?

Sure, I have changed it

**Comment by zhangmingld** [comment]
> Thanks for the PR @zhangmingld

it`s my pleasure~

**Pull request merged**
