### PR TITLE
remove componentstatus support in v1.25

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
```
[root@paco ~]# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
etcd-0               Healthy     {"health":"true","reason":""}
controller-manager   Healthy     ok
```
ComponentStatus is deprecated for about 6 releases(almost 2 years) and the result doesn't make sense.

https://github.com/kubernetes/kubernetes/pull/93570

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
https://github.com/pacoxu/kubernetes/blob/d9c7255ab40ee707e5b861ac88dd7855565c59a8/cluster/validate-cluster.sh#L157-L182
I change it to use API Server healthz.

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver: remove the componentstatus API. 
```

### CODE REVIEW

**Comment by liggitt** [comment]
I agree the API doesn't make sense in all deployment topologies, and if we were deciding whether to newly add it today, we wouldn't, but per the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/), stable APIs aren't removed, even though they can be marked as deprecated:

> GA API versions may be marked as deprecated, but must not be removed within a major version of Kubernetes
>
> Note: There are no current plans for a major version revision of Kubernetes that removes GA APIs.

**Comment by pacoxu** [comment]
> GA API versions may be marked as deprecated, but must not be removed within a major version of Kubernetes

Got it. Thanks.

**Pull request closed without merging**
