### PR TITLE
rkt.go: format err

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
the modification makes code clean, simple, and easy to inspect.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by euank** [comment]
-1 for similar reasoning as https://github.com/kubernetes/kubernetes/pull/44747#issuecomment-297837675

The way forwards for rkt integration is [CRI/rktlet](https://github.com/kubernetes-incubator/rktlet/).
This doesn't fix a real bug nor really increase readability by any significant amount.

**Review by yifan-gu — DISMISSED** [review]
LGTM

**Comment by zhangxiaoyu-zidif** [comment]
@ euank I don't agree with you. It's better to keep same format with other K8s codes.
A unified and standard code style seems to be important.
You may think it is not necessary or useless, but I insist my opinion.
Thanks all the same.

**Comment by zhangxiaoyu-zidif** [comment]
@yifan-gu you agree with euank， and think this PR is redundant?

**Comment by yifan-gu** [comment]
@zhangxiaoyu-zidif I don't have strong opinion on this.

**Pull request closed without merging**
