### PR TITLE
Refactor kubectl create role and clusterrole, use generator

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
Refactor kubectl create role and clusterrole, use generator. but don't change use pattern.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
```hack/update-bazel.sh 
!!! [0815 15:49:43] Call tree:
!!! [0815 15:49:43]  1: hack/update-bazel.sh:29 kube::util::go_install_from_commit(...)
!!! Error in /Users/admin/go/src/k8s.io/kubernetes/hack/lib/util.sh:534
  Error in /Users/admin/go/src/k8s.io/kubernetes/hack/lib/util.sh:534. '((i<3-1))' exited with status 1
Call stack:
  1: /Users/admin/go/src/k8s.io/kubernetes/hack/lib/util.sh:534 kube::util::go_install_from_commit(...)
  2: hack/update-bazel.sh:29 main(...)
Exiting with status 1```
i cann't update build file, who know this? thanks

**Comment by zjj2wry** [comment]
@fabianofranz can you help me review this?

**Comment by NickrenREN** [comment]
Maybe you need to squash your commits

**Comment by zjj2wry** [comment]
@smarterclayton maybe you alse know this area code. the k8s robot random to you. can you help review this?  🐰

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Pull request closed without merging**
