### PR TITLE
etcd version for 1.19 is 3.4.13 for cve fixes

### LINKED ISSUE #97234: kubeadm v1.20.0 incorrectly tries to use etcd 3.4.9 for v1.19.4 clusters
**What happened**:

Found while testing kubeadm 1.20 for openSUSE Kubic in openQA. The test attempted to bootstrap a simple kubernetes 1.19.4 cluster with `kubeadm init --kubernetes-version=1.19.4` but this test failed, complaining it could not find a etcd container with tag `etcd:3.4.9-1` - etcd 3.4.9 images were removed from our registry after the recent CVE, which was resolved by 3.4.13, which was supported as of k8s 1.19.1 (https://github.com/kubernetes/kubernetes/commit/3226dafee1d184463710a6bbde910b4924262b39 for reference)

This seems to be because https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants.go#L472 still references etcd 3.4.9 for clusters of version `19` even though 3.4.13 is the correct version to be used. Thanks to @Vogtinator for finding that.

**What you expected to happen**:

Kubeadm should use etcd v3.4.13 for all clusters version 1.19.1 and higher

**How to reproduce it (as minimally and precisely as possible)**:

Run `kubeadm init --kubernetes-version=1.19.4` , check version of etcd. It should be `3.4.13`, but with this bug it will be `3.4.9`

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): 

NAME="openSUSE MicroOS"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20201209"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20201209"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"

- Kernel (e.g. `uname -a`):

Linux r2d2 5.9.12-1-default #1 SMP Wed Dec 2 09:24:35 UTC 2020 (46922da) x86_64 x86_64 x86_64 GNU/Linux

/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Etcd version check in kubeadm upgrade still references etcd 3.4.9 for clusters of version 19 even though 3.4.13 is the correct version to be used. 

https://github.com/kubernetes/kubernetes/blob/release-1.19/cmd/kubeadm/app/constants/constants.go#L436
		19: "3.4.13-0",
https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/constants/constants.go#L472
		19: "3.4.9-1",

**Which issue(s) this PR fixes**:
Fixes #97234

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
kubeadm now installs version 3.4.13 of etcd when creating a cluster with v1.19
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm
/triage accepted

**Comment by fabriziopandini** [comment]
/approve
This was an oversight in https://github.com/kubernetes/kubernetes/pull/94287 😓 
This change should be backported in the 1.20 branch

**Comment by fabriziopandini** [comment]
/hold
@pacoxu please add a release note:
kubeadm now installs version xx of etcd when creating a cluster with v1.19

**Comment by pacoxu** [comment]
@fabriziopandini release note is edited.

**Comment by fabriziopandini** [comment]
@pacoxu do you mind cherry-picking this in the 1-20 branch?

**Comment by pacoxu** [comment]
ok 
Cherry pick pr is #97284

**Pull request merged**
