### PR TITLE
[WIP] Propagate runtime handler to CRI PullImage calls

### PR DESCRIPTION
**Pull request by kkmsft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
Propagate runtime handler to CRI PullImage calls
    
Adds runtime handler to PodSandboxConfig in order to propagate it to PullImage. Related KEP can be found here: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/windows-runtimeclass-support.md
    
Currently, PodSandboxConfig is passed to PullImage. Modifying the PodSanboxConfig to accommodate the runtime class handler helps us to reuse the utility function code to extract run time class from Pod spec. This approach is different from the one specified in the KEP, but result is the same.
    
Note: The same approach can be used in case of RunPodSandbox, but in order to maintain the backward compatibility, we just reuse the PodSanboxConfig's RuntimeHandle

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Propagate runtime handler to CRI PullImage calls
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

[KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/windows-runtimeclass-support.md

```

### CODE REVIEW

**Comment by PatrickLang** [comment]
cc @jterry75 - I put this on the agenda for discussion with SIG-Node tomorrow https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.hcbalr5n27m8

**Review by tallclair — COMMENTED** [review]
I think the original vision for the runtime_handler parameter was that the runtime would have a cached map of pod sandbox ID to runtime handler. IIRC, the motivation was that the runtime information (dates back to runtime parameters) shouldn't change once the sandbox is created, and this was a programmatic way to ensure that different parameters would not be passed in. For example, what would happen if the runtimeclass was updated with a different RuntimeHandler after the pod was started, and then the image pull happened with that different RuntimeHandler?

I think there's an argument that the Kubelet should be responsible for caching that information, in which case this change makes sense, but I do think we need to make sure this case is handled correctly.

**Comment by PatrickLang** [comment]
@tallclair if "the runtime information (dates back to runtime parameters) shouldn't change once the sandbox is created," do you know if this is enforced? My intent and assumption was that runtimeHandler shouldn't change between pull & createpodsandbox.

However, I do think that two pods could be pulled & run with different handlers. eg: 1 with extra isolation, 1 without, on the same node.

Does that align with your understanding?

**Comment by PatrickLang** [comment]
Also - if there is a future where the pull behavior might change between different runtimeHandlers, where each has its own image list - should the List & Remove methods also be updated to require PodSandboxConfig?

**Comment by PatrickLang** [comment]
Here's an indication where someone else suggested there may be a containerd snapshotter behavior change based on PodSandboxConfig. Later Lantau suggests RuntimeClass would be a good way to do it. 

https://github.com/kubernetes/kubernetes/issues/71745#issuecomment-448216022

**Comment by PatrickLang** [comment]
cc @linxiulei from the other issue. Any opinions on this?

**Comment by linxiulei** [comment]
It looks good to me. However, worrying that PodSandboxConfig supplies too much data makes sense. I think this is more a question of if k8s would like to standardize PullImage with runtimeclass. If not, as we already propagated PodSandboxConfig users can customize the feature with annotations

**Comment by tallclair** [comment]
> if "the runtime information (dates back to runtime parameters) shouldn't change once the sandbox is created," do you know if this is enforced?

Originally the runtime handler could only be passed to RunPodSandbox, so there was no way for it to change for a sandbox.

> Also - if there is a future where the pull behavior might change between different runtimeHandlers, where each has its own image list - should the List & Remove methods also be updated? In that case, I'm wondering whether PodSandboxConfig supplies too much data, vs just using runtimeHandler as a string.

I didn't follow this piece. Isn't this whole PR about having different pull behavior between different runtime handlers?

**Comment by tallclair** [comment]
BTW, I'm not too worried about duplicating the runtime handler in the RunPodSandboxRequest, since the API is still alpha. We should just make sure to flag it as something to fix in a move to beta.

**Comment by kkmsft** [comment]
@jterry75 - List/Stats/Remove seems to be used used in GC context. So there is no runtime context during those operations and also no user intend involved during those operations..

**Comment by jterry75** [comment]
@kkmsft - Even in a GC context you can imagine the race condition causing a launch failure on CreateContainer that I posed above. If a Remove was issued between a Pull and Create we would end up removing all versions of that image and thus the Create would fail. We have to have remove be contextual as well

**Comment by yujuhong** [comment]
> @kkmsft, @PatrickLang - I don't see how Kubelet will be able to manage images without forwarding this as well to `ListImages`, `ImageStatus` and `RemoveImage`. For example imagine we use this behavior to `PullImage(windows/nanoserver, 17763-handler)`. We now have the 17763 version on disk. We issue another `PullImage(windows/nanoserver, 18362-handler)`. We now have both 17763 and 18362 images resident. We run the worker container for 17763 and then issue a `RemoveImage(windows/nanoserver)`. We will end up remove both images even though the 2nd image is still valid (and potentially in use). Without the `RuntimeHandler` passed to `RemoveImage` we cant possibly know what the orchestrator needed.

+1 Maybe we should revisit what passing the runtime handler indicates in these image-related methods. We may not want to dictate everything about the runtime handler, but I also don't want to cause diverging CRI implementations.

Another possible direction is not to pass runtime handler to the image methods, but properly define a spec that encompasses all information needed to pull )or remove) the image. Of course, there would still be a gap as kubelet needs to know what image each runtime handler map to, and that's something we need to address. Doing it this way preserves the possibility of running a separate image service.

There's the bigger question of whether using per-OS-version handler provides the best user experience -- do users really want to specify what version to use, especially when it comes to hyper-v implementations?

/cc @tallclair @Random-Liu since they may have some thoughts to share as well.

**Comment by tedyu** [comment]
```
properly define a spec that encompasses all information needed to pull )or remove) the image
```
+1

**Comment by Random-Liu** [comment]
In the current proposal, for the following 2 cases, what the runtime handler will be? And how is the underlying container runtime expected to handle it?
1) A multi-arch image with multiple build versions using hyperV. What architecture will be used? What build version will be used?
2) A multi-arch image with multiple build versions using process-isolation. This one is more straightforward to me, we'll match a working build version and use the OS architecture.

**Comment by jterry75** [comment]
> In the current proposal, for the following 2 cases, what the runtime handler will be? And how is the underlying container runtime expected to handle it?
> 
> 1. A multi-arch image with multiple build versions using hyperV. What architecture will be used? What build version will be used?
> 2. A multi-arch image with multiple build versions using process-isolation. This one is more straightforward to me, we'll match a working build version and use the OS architecture.

@Random-Liu - Yes this proposal is for 1. Since an image has no arch/os/version tags in CRI the way to achieve those is though a known runtime handler. IE: `runhcs-hypervisor-<version>`. That way the multi-arch / multi-version image would have to match the arch and version of the handler so we know that we always pull and activate the appropriate image for that handler.

**Comment by josiahbjorgaard** [comment]
@PatrickLang A gentle reminder that v1.17 code freeze is this Thursday, Nov. 14 at 5PM pacific time.

**Comment by Random-Liu** [comment]
We discussed this in sig-node.

One concern was brought up in the sig-node is that this proposal only added the `PodSandboxConfig` into `PullImage` call, but other image management methods are not aware of it. This breaks image management of Kubelet, for example kubelet doesn't know whether an image for a given pod is pulled or not, because it might be pulled for one runtime handler, but not the one that is going to be used.

One new solution we proposed is to add `Annotations` field into the `ImageSpec` to make the "image definition" extensible. For windows alpha support, the required information can be passed through annotations, but for beta or GA, we should clearly define the requirement, and graduate the annotation into a field in `ImageSpec`.

The reasons we think adding an `Annotations` to `ImageSpec` is reasonable are:
1) OCI image spec also contains `Annotations` as part of image metadata https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest, and there are even predefined annotations https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys, so logically `Annotations` is part of the "image definition".
2) Experiment features with Annotations and eventually graduate it to fields when the feature is stable is a common practice currently in CRI. This makes it possible for future innovations to happen as well. :)

@PatrickLang Is this approach OK to you? And does it work for the use cases?

/cc @yujuhong @tallclair @dchen1107

**Comment by jterry75** [comment]
@Random-Liu - I think this idea works just fine and is indeed a good solution. In thinking through the use of RuntimeHandlers in the proposal the reason we landed there is because it was clear if Kubelet would know what annotations to set on an image. Thats why using the RuntimeHandler allowed the caller to be pretty dumb and just pass the same one to both Pull and RunP. In this approach it really means that the caller needs to know which RuntimeHandler is what os/version set of annotations to the ImageSpec.

As long as there is a way for the user (Kubelet) to know that. I am more than happy with your idea and think it more closely aligns with the OCI Image spec.

**Comment by jtslear** [comment]
Hello @kkmsft and @tallclair 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this PR still intended for milestone 1.18? I see we have some conflicts that need resolution and we are still awaiting further reviews.

**Comment by jterry75** [comment]
@PatrickLang / @kkmsft - We can close this right? We are using the image annotations?

**Comment by kkmsft** [comment]
@jterry75 - Yes Closing this. Will raise a PR with annotations.

**Pull request closed without merging**
