### PR TITLE
[WIP]migrate to github.com/distribution/distribution/v3

### LINKED ISSUE #103849: Migrate from github.com/docker/distribution to github.com/distribution/distribution/v3
#### What happened:
Kubernetes libraries have a dependency on `github.com/docker/distribution`
#### What you expected to happen:
Kubernetes libraries have a dependency on `github.com/distribution/distribution/v3`. Note the github org just changed, its the same project. I believe the v2 -> v3 was mostly to get around go.mod weirdness with versions, rather than large breaking changes, but am not sure.
#### How to reproduce it (as minimally and precisely as possible):
Look at go.mod, I suppose

#### Anything else we need to know?:
`github.com/docker/distribution@v2.7.1+incompatible`, the library in use, is 2.5 years old. It does not have a go.mod file, and in turn depends on a bunch of other libraries without go.mod files. This generally makes importing these libraries a pain - you can see 350 projects needing to add `replace` hacks to go.mod to work around these issues: https://github.com/search?q=%22replace+github.com%2Fdocker%2Fdistribution%22&type=code

It would be great to upgrade to the latest version.

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:
Fixes #103849

#### Special notes for your reviewer:
```
{
-	"directDependencies": [163](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107211/check-dependency-stats/1511977924343894016#1:build-log.txt%3A16),
-	"transitiveDependencies": 262,
-	"totalDependencies": 323,
+	"directDependencies": 162,
+	"transitiveDependencies": 286,
+	"totalDependencies": 343,
 	"maxDepthOfDependencies": 29
 }
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/priority important-soon
since this should be in 1.24.

**Comment by pacoxu** [comment]
/assign @liggitt

What's next for this?
Need this be reviewed by sig-node?

**Comment by pacoxu** [comment]
The key change is like below:
```
pkg/kubelet/images/image_manager.go
pkg/util/parsers/parsers.go

staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go
staging/src/k8s.io/kubectl/pkg/cmd/run/run.go
```
The references are changed to use distribution v3.

**Comment by liggitt** [comment]
This is a surprising *increase* in transitive dependencies for this switch. New transitive dependencies:

- github.com/Shopify/logrus-bugsnag
- github.com/bitly/go-simplejson
- github.com/bshuster-repo/logrus-logstash-hook
- github.com/bugsnag/bugsnag-go
- github.com/bugsnag/osext
- github.com/bugsnag/panicwrap
- github.com/denverdino/aliyungo
- github.com/distribution/distribution/v3
- github.com/docker/go-events
- github.com/docker/go-metrics
- github.com/docker/libtrust
- github.com/golang-jwt/jwt/v4
- github.com/gomodule/redigo
- github.com/gorilla/handlers
- github.com/mitchellh/osext
- github.com/ncw/swift
- github.com/yvasiyarov/go-metrics
- github.com/yvasiyarov/gorelic
- github.com/yvasiyarov/newrelic_platform_go
- google.golang.org/cloud

And it looks like there were no removed transitive dependencies. Is this change actually an improvement?

Did the additional deps come from github.com/distribution/distribution/v3 or from the other dependency bumps?

**Comment by howardjohn** [comment]
Does the fact v2 had no go.mod and v3 does make it look worse than it is? Not sure how the dependencies are reported in the case of go.mod

**Comment by liggitt** [comment]
> Does the fact v2 had no go.mod and v3 does make it look worse than it is? Not sure how the dependencies are reported in the case of go.mod

maybe, though if most of the added transitives are used by packages we don't actually use (which is what it looks like, given how little changed in `vendor/`), the go.mod informing go of the transitive deps actually does make version resolution worse

**Comment by liggitt** [comment]
given the minimal use of the docker/distribution dep (looks like we use the image spec parser, a regex, and an error), I'd strongly consider extracting/forking just the package we use and dropping the dep

**Comment by smarterclayton** [comment]
The image regex spec is part of our public API (Unfortunately) in how we deal with secrets, so I'm supportive of an extract and fork that very tightly controls changes to it.  It's been stable for most of 5 years now, and several other projects I know of have extracted that bit for similar reasons.

**Comment by pacoxu** [comment]
/hold
so we should wait for `https://github.com/kubernetes/utils/pull/231` and change to use `kuberentes/util` or something like that.

**Comment by pacoxu** [comment]
@dims So I would use https://github.com/k8s-internal/distribution instead.

**Comment by dims** [comment]
@pacoxu haven't decided yet. that github org and repo was just for testing things

**Comment by ritazh** [comment]
/remove-sig auth 
Feel free to add us back if needed.

**Comment by dims** [comment]
@pacoxu let me close this WIP since it is too old. please file a fresh PR or reopen this when you want to pick this up.

**Comment by pacoxu** [comment]
https://github.com/distribution/distribution/issues/3587 
I will follow up if there is any update.

**Pull request closed without merging**
