### PR TITLE
fix staticcheck: pkg/volume/awsebs

### PR DESCRIPTION
**Pull request by yuxiaobo96**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix staticcheck: pkg/volume/awsebs

**Which issue(s) this PR fixes**:

ref:#81657

**Special notes for your reviewer**:

```shell
pkg/volume/awsebs/aws_ebs.go:485:2: field namespace is unused (U1000)
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
/test pull-kubernetes-e2e-gce-csi-serial
--

**Comment by justinsb** [comment]
Thanks @yuxiaobo96 - always great to clean these things up!

/approve

**Comment by yuxiaobo96** [comment]
/assign @liggitt for /hack approval.
Thanks.

**Pull request merged**
