### PR TITLE
Drop publishing-bot rules for the release-1.26 branch

### PR DESCRIPTION
**Pull request by akhilerm**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- Drop publishing-bot rules for the `release-1.26` branch which went EOL on 28 Feb 2024

The changes are auto generated by running
```
update-rules -branch release-1.26  -delete -o /tmp/rules.yaml -rules staging/publishing/rules.yaml
```

cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
