### PR TITLE
Add e2e test for daemonset pod affinity

### PR DESCRIPTION
**Pull request by ivan4th**
Add e2e test for #31136. Includes commits from #31136 and #33451, will linearize the history if/when these PRs are merged.

EDIT: #33451 got merged so I updated this PR.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33523)

### CODE REVIEW

**Comment by ivan4th** [comment]
@k8s-bot gke e2e test this

**Comment by ivan4th** [comment]
@k8s-bot gci gce e2e test this

flake: #34014

**Comment by ivan4th** [comment]
I hope it'll be possible to merge this in 1.6. So let's keep it open for now

**Comment by cblecker** [comment]
This PR doesn't appear to be active, and there is no criteria for moving it forward.
Removing lifecycle/frozen status.

/remove-lifecycle frozen

**Pull request closed without merging**
