### PR TITLE
Remove deprecated rolling-update command

### LINKED ISSUE #88051: Remove deprecated command `kubectl rolling-update`
`kubectl rolling-update` has been deprecated and hidden since April 2018 (https://github.com/kubernetes/kubernetes/pull/61285) in v1.11, and has been replaced with `kubectl rollout`.

Let's remove it completely from kubectl and tests, and then the website and any docs.

/sig cli

### PR DESCRIPTION
**Pull request by julianvmodesto**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:
This removes the deprecated and hidden command `rolling-update`, which was replaced with `rollout`.

This command has been deprecated and hidden since April 2018.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/88051

**Does this PR introduce a user-facing change?**:

```release-note
Removes the deprecated command `kubectl rolling-update`
```

/sig cli
/area kubectl

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by smarterclayton** [comment]
/approve

Don't let the door hit you on the way out

**Comment by pptfz** [comment]
This removes the deprecated and hidden command rolling-update, which was replaced with rollout.

I didn't find a way to implement the rolling update from the Kubectl official documentation Could you give me a hand ？ thank you

[kubectl official documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#rollout)

**Pull request merged**
