### PR TITLE
Return nil when err is nil

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Return nil directly when err is nil

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
This is effectively a noop. Why is this needed?

**Comment by zhangxiaoyu-zidif** [comment]
@cblecker  Sir， please refer to https://github.com/kubernetes/kubernetes/pull/29866, https://github.com/kubernetes/kubernetes/pull/45162. That may be a format. Thanks.

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Pull request merged**
