### PR TITLE
cri: allow `GetContainerEvents` to pass a context

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The context can be used for timeout purposes for example, not really for Kubernetes but other consumers like cri-tools.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
PTAL @sairameshv @harche 
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Test failures are not related, see https://github.com/kubernetes/kubernetes/issues/125829, https://github.com/kubernetes/kubernetes/pull/125860

**Comment by saschagrunert** [comment]
Green tests PTAL again @harche

**Review by harche — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
/lgtm
/assign @mrunalp @yujuhong 
for approval

**Pull request merged**
