### PR TITLE
fix the running of the kube-controller-manager

### PR DESCRIPTION
**Pull request by Iceber**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
The `ControllerManagerCommand` runs through `k8s.io/component-base/cli` and cannot call `os.Exit` within `command.Run`, otherwise it will not be able to execute the cleanup in `cli.Run`.
https://github.com/kubernetes/kubernetes/blob/f92152da72bf2de312a54c77ef234e94dabf61c8/cmd/kube-controller-manager/controller-manager.go#L34-L38

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @pohly 

IIRC this has changed recently just in the other direction

**Review by pohly — APPROVED** [review]
> IIRC this has changed recently just in the other direction

No, this change here is aligned with similar changes in other commands and with the `cli.Run` refactoring, therefore:

/lgtm

**Comment by Iceber** [comment]
@pohly @lavalamp rebased, PTAL

**Review by pohly — APPROVED** [review]
/lgtm

**Pull request merged**
