### PR TITLE
Stop clear non-existant retention policy rule

### PR DESCRIPTION
**Pull request by ameukam**
This command is now not necessary and create some noise on the trail logs.
See: https://github.com/kubernetes/k8s.io/pull/4902

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ameukam** [comment]
/release-note-none
/sig k8s-infra
/triage accepted

cc @dims @BenTheElder

**Comment by ameukam** [comment]
Every time this command is invocated, the metadata for all the staging buckets are regenerated.
e.g.: https://github.com/k8s-infra-ci-robot/k8s.io/blob/765a49db2205239532e74dadf1bb322cdfdd636f/audit/projects/k8s-infra-e2e-boskos-011/buckets/kubernetes-staging-6affe00594-us-central1/metadata.txt#L13-L16

**Comment by BenTheElder** [comment]
LGTM

**Pull request merged**
