### PR TITLE
[wip] Move tolerate-unready-endpoints annotation to beta

### PR DESCRIPTION
**Pull request by bprashanth**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35713)

### CODE REVIEW

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/28718#issuecomment-256731695

**Comment by smarterclayton** [comment]
Break users as per API alpha -> beta rules?

**Comment by smarterclayton** [comment]
When we move from beta to field will people also be broken?

**Comment by bprashanth** [comment]
>Break users as per API alpha -> beta rules?

I can go eitherway (though I think only petset really uses this, and we're breaking petset with name change), if we agree we want to do this vs something fancier like a special type of Service.

>When we move from beta to field will people also be broken?

we can't right? we'll have to convert. We already beta annotations that we'll have to treat in a similar way (the external source ip stuff, pod hostname).

**Comment by smarterclayton** [comment]
Kind of tempted to leave this at alpha until we have more time to discuss.  Changing the name doesn't help anyone much, and if this stays alpha for another release while we have time to get more experience I'm ok with that.

**Comment by bprashanth** [comment]
SG, we can discuss on https://github.com/kubernetes/kubernetes/issues/25283. If anyone wants otherwise, speak up and I'll reopen.

**Comment by thockin** [comment]
@bowei This maybe is the answer to what we were discussing this evening?

**Comment by xiang90** [comment]
@bprashanth 

can we reopen and make this feature beta?

**Pull request closed without merging**
