### PR TITLE
dependencies: update opencontainers/selinux to v1.11.0

### PR DESCRIPTION
**Pull request by akhilerm**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- updates opencontainers/selinux to v1.11.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
I also wonder how our selinux test coverage is ... https://github.com/kubernetes/kubernetes/issues/86080 is long-lived and still unresolved as far as I know. If this update regresses selinux, would we know?

cc @jsafrane

**Comment by akhilerm** [comment]
/cc @jsafrane 

Pinging to see if the update will cause regression in selinux, (context: selinux volume relabelling as mentioned in the comment above)

**Comment by akhilerm** [comment]
@liggitt What should we do about this PR?

**Comment by liggitt** [comment]
still looking for storage reviewer and test coverage

**Comment by jsafrane** [comment]
It looks good from storage perspective.

**Pull request merged**
