### PR TITLE
Adding dims as approver for test/

### PR DESCRIPTION
**Pull request by dims**
In 16fb6733a1680844f9408cc3e606bfc98669fdd3, i signed up as a reviewer
for test/ (8 months ago).

Here's what i have to show for it:
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Amerged+label%3Aarea%2Ftest+commenter%3Adims

Especially see the most recent conformance related reviews. Hoping this
is enough of a track record!

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@BenTheElder @spiffxp happy to continue as reviewer if you feel i am not ready, so don't hesitate to say so.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/retest

anecdotally I have seen you on enough PR's that I've been involved in that I'm fine with this, and not compelled to bust out my script that counts stats (I can, if folks think it's necessary)

/hold
for input from @BenTheElder

**Comment by BenTheElder** [comment]
/lgtm
/approve
TIL `commenter:` thanks :-)
And thanks for all your work here!
/hold cancel

**Comment by dims** [comment]
thanks @spiffxp @BenTheElder !!

**Pull request merged**
