### PR TITLE
Revert "node: device-mgr: Handle recovery flow by checking if healthy devices exist"

### LINKED ISSUE #116340: Failing E2E Node Test: E2E: E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across pod and kubelet restarts
Failing:

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial
https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial

```
E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across pod and kubelet restarts[Changes]
````

```
E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments after the device plugin has been re-registered[Changes]
```

Failing since `03-06`.

Last passing: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1632668265144651776
First failing: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1632668265144651776

### PR DESCRIPTION
**Pull request by bobbypage**
Reverts kubernetes/kubernetes#114640

Fixes https://github.com/kubernetes/kubernetes/issues/116340

```release-note
NONE
```

### CODE REVIEW

**Comment by bobbypage** [comment]
/hold

Seeing if revert of this will result in test passing

**Comment by bobbypage** [comment]
The serial tests are passing with this change reverted - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116341/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1633193789466087424/

**Comment by bobbypage** [comment]
cc @swatisehgal

**Comment by bobbypage** [comment]
I suggest we revert this PR for now, fix the the PR to ensure the tests will not break and then re merge the PR.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

thank you!

**Comment by SergeyKanzhelev** [comment]
@swatisehgal please ping when you have the fix ready.

**Comment by swatisehgal** [comment]
> I suggest we revert this PR for now, fix the the PR to ensure the tests will not break and then re merge the PR.

Ack, Thanks @bobbypage. 

> @swatisehgal please ping when you have the fix ready.

I am on it!

**Comment by swatisehgal** [comment]
PR with fix : https://github.com/kubernetes/kubernetes/pull/116376.

**Pull request merged**
