### PR TITLE
Fix scheduling e2e test case for local ephemeral storage

### LINKED ISSUE #51741: New SchedulerPredicates Conformance test is constantly failing
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

There are several CI e2e jobs that are failing this new Conformance test:

    [sig-scheduling] SchedulerPredicates [Serial] validates local ephemeral storage resource limits of pods that are allowed to run [Conformance] 1m6s
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:221
    Expected
        <bool>: false
    to equal
        <bool>: true
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:160

Here is one such failure:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5422

Moreover, this new test has been consistently failing on multiple e2e jobs ever since it was merged to master:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce
https://k8s-testgrid.appspot.com/google-aws#kops-aws-serial
https://k8s-testgrid.appspot.com/sig-scheduling#gce-serial
https://k8s-testgrid.appspot.com/sig-scheduling#gke-serial

Here is the pull request for the new test:
https://github.com/kubernetes/kubernetes/pull/50005

I don't know if this is a legitimate problem with the scheduler in these jobs and if the test is running and passing elsewhere, or if there is a flaw in the test itself.

@kubernetes/sig-scheduling-bugs 
@NickrenREN

### PR DESCRIPTION
**Pull request by NickrenREN**
Fix scheduling e2e test case for local ephemeral storage

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51741

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

/assign @pipejakob

### CODE REVIEW

**Comment by pipejakob** [comment]
I thought that the purpose of a Conformance test was that it should pass against any valid Kubernetes cluster, regardless of deployment or options. If this is a test that only matters if you've enabled a specific feature, shouldn't it have a tag like "[Feature:EphemeralStorage]" instead of "[Conformance]"? That way, the test will be skipped by default and will need to be opted-into by test jobs that run with the feature enabled.

**Comment by NickrenREN** [comment]
Thanks @pipejakob . Modified,  sorry for ignoring the `Conformance`

**Comment by pipejakob** [comment]
/lgtm

Next step will be to figure out what e2e jobs this *should* be enabled in, and make sure they opt into testing the feature.

**Comment by luxas** [comment]
@kubernetes/sig-scheduling-pr-reviews PTAL

I'm tempted to just add the approval label here to fix lots of test failures
cc @kubernetes/kubernetes-release-managers as this affects our CI signal heavily

**Comment by luxas** [comment]
Can we manually merge this or bump the SQ priority due to that it's making several test suites fail?

**Comment by luxas** [comment]
@k8s-oncall Can you please merge this manually?
I may do that as well if I get support from someone else...

**Pull request merged**
