### PR TITLE
Automated cherry pick of #15790 upstream release 1.1

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #15790 upstream release 1.1

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
