### PR TITLE
daemonset don't place pods on notready nodes

### LINKED ISSUE #16105: DaemonSet should not schedule pods on NotReady nodes
It appears in my cluster that DaemonSet is scheduling pods on NotReady nodes.

To reproduce:

  1. Spin up a 6 node cluster on AWS
  2. Create a DaemonSet
  3. Scale back down to 3 nodes on AWS
  4. DaemonSet will continue to schedule and reschedule pods on the NotReady nodes.

Sample node list output:

```
NAME                                         LABELS                                                              STATUS     AGE
ip-172-20-0-168.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-168.us-west-2.compute.internal   NotReady   13h
ip-172-20-0-169.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-169.us-west-2.compute.internal   NotReady   13h
ip-172-20-0-170.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-170.us-west-2.compute.internal   NotReady   13h
ip-172-20-0-244.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-244.us-west-2.compute.internal   Ready      12m
ip-172-20-0-245.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-245.us-west-2.compute.internal   Ready      12m
ip-172-20-0-246.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-246.us-west-2.compute.internal   Ready      12m
```

Sample pods output:

```
NAME              READY     STATUS        RESTARTS   AGE
cassandra-joag3   0/1       Terminating   0          47s
cassandra-jyjab   0/1       Terminating   0          57s
cassandra-l9o8b   1/1       Running       0          12m
cassandra-qmcw2   0/1       Terminating   0          37s
cassandra-r31tf   1/1       Running       0          12m
cassandra-ua95o   1/1       Running       0          12m
```

Sample DaemonSet output:

```
NAME        CONTAINER(S)   IMAGE(S)                                SELECTOR         NODE-SELECTOR
cassandra   cassandra      gcr.io/google_containers/cassandra:v6   name=cassandra   <none>
```

### PR DESCRIPTION
**Pull request by mikedanese**
TODO: add a unit test

Fixes #16105

### CODE REVIEW

**Comment by davidopp** [comment]
Looks good but we probably shouldn't merge this without a unit test...

**Comment by mikedanese** [comment]
@davidopp added a unit test.

**Comment by davidopp** [comment]
LGTM

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

**Comment by davidopp** [comment]
I'm just going to manually merge this. It's just waiting on Shippable but it passed the Jenkins unit tests and it's blocking a cherrypick.

**Pull request merged**
