### PR TITLE
Add Host field to TCPSocketAction

### PR DESCRIPTION
**Pull request by louyihua**
Currently, TCPSocketAction always uses Pod's IP in connection. But when a pod uses the host network, sometimes firewall rules may prevent kubelet from connecting through the Pod's IP.

This PR introduces the 'Host' field for TCPSocketAction, and if it is set to non-empty string, the probe will be performed on the configured host rather than the Pod's IP. This gives users an opportunity to explicitly specify 'localhost' as the target for the above situations.

```release-note
Add Host field to TCPSocketAction
```

### CODE REVIEW

**Comment by louyihua** [comment]
@k8s-bot tell me a joke

**Comment by louyihua** [comment]
@smarterclayton
This is a required patch to solve the openshift BUG 1405440 & 1430729.

**Comment by soltysh** [comment]
@kubernetes/sig-network-pr-reviews ptal

**Comment by nikhiljindal** [comment]
We generally recommend keeping real code changes and autogenerated changes in separate commit for easier reviewing.

This is an API change so cc @kubernetes/api-reviewers.

Assigning to @thockin to triage since this a network related API change.

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by louyihua** [comment]
@k8s-bot node e2e test this

**Comment by louyihua** [comment]
@k8s-bot verify test this

**Comment by louyihua** [comment]
@k8s-bot kops aws e2e test this

**Comment by louyihua** [comment]
@k8s-bot kops aws e2e test this

**Comment by louyihua** [comment]
@k8s-bot kops aws e2e test this

**Comment by louyihua** [comment]
Always fail one the aws e2e with strange error :(

**Comment by jwendell** [comment]
I would also add:

```diff
diff --git a/pkg/kubectl/describe.go b/pkg/kubectl/describe.go
index 0359b9c..c63654d 100644
--- a/pkg/kubectl/describe.go
+++ b/pkg/kubectl/describe.go
@@ -1123,7 +1123,7 @@ func DescribeProbe(probe *api.Probe) string {
                url.Path = probe.HTTPGet.Path
                return fmt.Sprintf("http-get %s %s", url.String(), attrs)
        case probe.TCPSocket != nil:
-               return fmt.Sprintf("tcp-socket :%s %s", probe.TCPSocket.Port.String(), attrs)
+               return fmt.Sprintf("tcp-socket %s:%s %s", probe.TCPSocket.Host, probe.TCPSocket.Port.String(), attrs)
        }
        return fmt.Sprintf("unknown %s", attrs)
 }
```

**Comment by louyihua** [comment]
@jwendell
Thanks! Have added this to commit.

**Comment by jwendell** [comment]
@louyihua no problem. I was also working on that feature, for the last 3 days at least, and just saw this PR. The only difference to my work was that chunk above.

**Comment by louyihua** [comment]
@thockin
All tests are passed now.

**Comment by louyihua** [comment]
@k8s-bot unit test this

**Pull request merged**
