### PR TITLE
HPA: removed duplicated events, added events in all execution paths.

### LINKED ISSUE #36357: Duplicated events in HPA controller
Extracted from https://github.com/kubernetes/kubernetes/pull/36235#issuecomment-258675817.

It seems we are exporting some events twice.

cc @kubernetes/autoscaling

### PR DESCRIPTION
**Pull request by jszczepkowski**
HPA: removed duplicated events, added events in all execution paths. Fixes #36357.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36436)

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @DirectXMan12

**Comment by piosz** [comment]
LGTM, thanks!

**Comment by piosz** [comment]
@saad-ali this is a bug fix.

**Comment by saad-ali** [comment]
> @saad-ali this is a bug fix.

Ack, thanks. Ok for post-code freeze merge

**Pull request merged**
