### PR TITLE
Automated cherry pick of #70353: Improve Azure instance metadata handling

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #70353 on release-1.10.

#70353: Improve Azure instance metadata handling

### CODE REVIEW

**Comment by feiskyer** [comment]
Fixed gofmt issues because of go1.11.

**Comment by PatrickLang** [comment]
/test pull-Kubernetes-cross

(just verifying how this works in Prow for a non-Windows test)

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
