### PR TITLE
Fix validation with List object not to use CRDs if unnecessary

### LINKED ISSUE #116245: kubectl apply requires CRDs to apply non-CRD resources if we use `kind: List`
### What happened?

kubectl apply performs validation before the apply. 

Non-CRD resources (e.g. pods / deployments) don't need CRD schema for validation, but if we use `kind: List` resource, kubectl calls `LIST apis/apiextensions.k8s.io/v1/customresourcedefinitions`.
In my Kubernetes cluster, administrator doesn't allow users to list CRDs, so user cannot apply non-CRD resources (e.g. pods / deployments) with `kind: List` resource.

### What did you expect to happen?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx-unprivileged
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx2
  name: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx-unprivileged
        resources: {}
status: {}
```

```console
$ kubectl apply -f example.yaml -v=7
I0303 17:59:37.216395  205040 loader.go:373] Config loaded from file:  /home/user/.kube/config
I0303 17:59:37.217086  205040 round_trippers.go:463] GET https://127.0.0.1:41981/openapi/v2?timeout=32s
I0303 17:59:37.217097  205040 round_trippers.go:469] Request Headers:
I0303 17:59:37.217111  205040 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0303 17:59:37.217124  205040 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:59:37.236776  205040 round_trippers.go:574] Response Status: 200 OK in 19 milliseconds
I0303 17:59:37.301207  205040 round_trippers.go:463] GET https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments/nginx
I0303 17:59:37.301223  205040 round_trippers.go:469] Request Headers:
I0303 17:59:37.301232  205040 round_trippers.go:473]     Accept: application/json
I0303 17:59:37.301243  205040 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:59:37.303149  205040 round_trippers.go:574] Response Status: 404 Not Found in 1 milliseconds
I0303 17:59:37.303436  205040 round_trippers.go:463] POST https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments?fieldManager=kubectl-client-side-apply&fieldValidation=Strict
I0303 17:59:37.303445  205040 round_trippers.go:469] Request Headers:
I0303 17:59:37.303453  205040 round_trippers.go:473]     Content-Type: application/json
I0303 17:59:37.303462  205040 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:59:37.303471  205040 round_trippers.go:473]     Accept: application/json
I0303 17:59:37.307537  205040 round_trippers.go:574] Response Status: 201 Created in 4 milliseconds
deployment.apps/nginx created
I0303 17:59:37.307789  205040 round_trippers.go:463] GET https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments/nginx2
I0303 17:59:37.307800  205040 round_trippers.go:469] Request Headers:
I0303 17:59:37.307812  205040 round_trippers.go:473]     Accept: application/json
I0303 17:59:37.307821  205040 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:59:37.309887  205040 round_trippers.go:574] Response Status: 404 Not Found in 2 milliseconds
I0303 17:59:37.310034  205040 round_trippers.go:463] POST https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments?fieldManager=kubectl-client-side-apply&fieldValidation=Strict
I0303 17:59:37.310042  205040 round_trippers.go:469] Request Headers:
I0303 17:59:37.310051  205040 round_trippers.go:473]     Accept: application/json
I0303 17:59:37.310060  205040 round_trippers.go:473]     Content-Type: application/json
I0303 17:59:37.310068  205040 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:59:37.312482  205040 round_trippers.go:574] Response Status: 201 Created in 2 milliseconds
deployment.apps/nginx2 created
I0303 17:59:37.312733  205040 apply.go:476] Running apply post-processor function
```

`GET https://127.0.0.1:41981/apis/apiextensions.k8s.io/v1/customresourcedefinitions` doesn't happen because we're going to apply two Deployments.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: nginx
    name: nginx
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
      spec:
        containers:
        - image: nginxinc/nginx-unprivileged
          name: nginx-unprivileged
          resources: {}
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: nginx2
    name: nginx2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx2
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx2
      spec:
        containers:
        - image: nginxinc/nginx-unprivileged
          name: nginx-unprivileged
          resources: {}
  status: {}
```

```console
$ kubectl apply -f nginx.yaml -v=7
I0303 17:57:00.999835  203689 loader.go:373] Config loaded from file:  /home/user/.kube/config
I0303 17:57:01.000493  203689 round_trippers.go:463] GET https://127.0.0.1:41981/openapi/v2?timeout=32s
I0303 17:57:01.000502  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.000511  203689 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0303 17:57:01.000521  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.023040  203689 round_trippers.go:574] Response Status: 200 OK in 22 milliseconds
I0303 17:57:01.098303  203689 round_trippers.go:463] GET https://127.0.0.1:41981/apis/apiextensions.k8s.io/v1/customresourcedefinitions
I0303 17:57:01.098323  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.098338  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.098351  203689 round_trippers.go:473]     Accept: application/json
I0303 17:57:01.100017  203689 round_trippers.go:574] Response Status: 200 OK in 1 milliseconds
I0303 17:57:01.102327  203689 round_trippers.go:463] GET https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments/nginx
I0303 17:57:01.102340  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.102349  203689 round_trippers.go:473]     Accept: application/json
I0303 17:57:01.102357  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.103710  203689 round_trippers.go:574] Response Status: 404 Not Found in 1 milliseconds
I0303 17:57:01.103983  203689 round_trippers.go:463] POST https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments?fieldManager=kubectl-client-side-apply&fieldValidation=Strict
I0303 17:57:01.103992  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.104001  203689 round_trippers.go:473]     Content-Type: application/json
I0303 17:57:01.104009  203689 round_trippers.go:473]     Accept: application/json
I0303 17:57:01.104017  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.108753  203689 round_trippers.go:574] Response Status: 201 Created in 4 milliseconds
deployment.apps/nginx created
I0303 17:57:01.109011  203689 round_trippers.go:463] GET https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments/nginx2
I0303 17:57:01.109019  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.109028  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.109036  203689 round_trippers.go:473]     Accept: application/json
I0303 17:57:01.110090  203689 round_trippers.go:574] Response Status: 404 Not Found in 1 milliseconds
I0303 17:57:01.110295  203689 round_trippers.go:463] POST https://127.0.0.1:41981/apis/apps/v1/namespaces/default/deployments?fieldManager=kubectl-client-side-apply&fieldValidation=Strict
I0303 17:57:01.110303  203689 round_trippers.go:469] Request Headers:
I0303 17:57:01.110314  203689 round_trippers.go:473]     Content-Type: application/json
I0303 17:57:01.110326  203689 round_trippers.go:473]     Accept: application/json
I0303 17:57:01.110335  203689 round_trippers.go:473]     User-Agent: kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
I0303 17:57:01.115945  203689 round_trippers.go:574] Response Status: 201 Created in 5 milliseconds
deployment.apps/nginx2 created
I0303 17:57:01.116125  203689 apply.go:476] Running apply post-processor function
```

`GET https://127.0.0.1:41981/apis/apiextensions.k8s.io/v1/customresourcedefinitions` should not happen because we're going to apply two Deployments.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-20T03:35:13Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

```
$ kind version
kind v0.17.0 go1.19.1 linux/amd64
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux desktop 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by y1r**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- introduce `validateList` on paramVerifyingSchema to check HasSupport in items one by one
- introduce test with pod in list object

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/116245

#### Does this PR introduce a user-facing change?

```release-note
Fix validation with List object not to use CRDs if unnecessary
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ardaguclu** [comment]
Thanks for the PR @y1r!

There was a simpler approach in this PR to fix that issue https://github.com/kubernetes/kubernetes/pull/116247

**Comment by ardaguclu** [comment]
and sorry I didn't know that you were working on it :)

**Comment by y1r** [comment]
Sorry for forget to assign myself in the issue https://github.com/kubernetes/kubernetes/issues/116245 and taking your time to prepare PR.

I think in order to behave correctly on custom resources in a list object, it should check items one by one. What do you think?

**Comment by ardaguclu** [comment]
It is already checking via https://github.com/kubernetes/kubernetes/blob/84b226409aa656fbacdcd633807dd0b04d1fb34e/staging/src/k8s.io/kubectl/pkg/validation/schema.go#L143 and https://github.com/kubernetes/kubernetes/blob/84b226409aa656fbacdcd633807dd0b04d1fb34e/staging/src/k8s.io/kubectl/pkg/validation/validation.go#L57

Just unnecessary CRD request exists.

**Comment by y1r** [comment]
I've confirmed that https://github.com/kubernetes/kubernetes/pull/116247 solves the issue https://github.com/kubernetes/kubernetes/issues/116245. I'm closing this PR now.

**Pull request closed without merging**
