### PR TITLE
cleanup: delete unused AuditDynamicOptions in apiserver

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
kubernetes do not use this struct.

https://cs.k8s.io/?q=AuditDynamicOptions&i=nope&files=&excludeFiles=&repos= also show no project use this struct.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alexzielenski** [comment]
/lgtm

leftover from dynamic auditing which was removed in https://github.com/kubernetes/kubernetes/pull/91502

/assign @deads2k 
since you authored that PR

**Comment by dims** [comment]
/approve

this is a code cleanup of unused code so happy to land it.

**Pull request merged**
