### PR TITLE
chore: unnecessary use of fmt.Sprintf

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix staticcheck unnecessary use of fmt.Sprintf (S1039)

#### Which issue(s) this PR fixes:

Fixes #
#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
on a fence of trivial edit. I wonder if we can add a linter that will not allow adding those in future.

/approve

approve for node e2e files.

**Comment by bart0sh** [comment]
/ok-to-test
/triage accepted
/priority important-longterm

@testwill please, fill the PR description

**Comment by testwill** [comment]
> /ok-to-test /triage accepted /priority important-longterm
> 
> @testwill please, fill the PR description

ok

**Pull request closed without merging**
