### PR TITLE
Update Docker for Mac installation link

### PR DESCRIPTION
**Pull request by VojtechVitek**
**What this PR does / why we need it**:

Fixes broken obsolete link about Docker for Mac installation.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34617)

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
LGTM

**Comment by errordeveloper** [comment]
@k8s-bot ok to test

**Comment by VojtechVitek** [comment]
Rebased again, can we merge this? This is one-liner in Markdown, no need to wait for complex tests.

@zmerlynn @errordeveloper

**Comment by VojtechVitek** [comment]
@zmerlynn @errordeveloper @apelisse Anything else blocking merge right now?

**Comment by apelisse** [comment]
This can't be merged because it is not milestoned for the upcoming release.

**Comment by VojtechVitek** [comment]
@apelisse oh, that applies even for one-liner documentation fixes, like this one? Note that this PR fixes broken links in the docs only, nothing else. :)

**Comment by apelisse** [comment]
cc @saad-ali That seems fine for post-freeze merge.

**Comment by dims** [comment]
@apelisse LGTM ( on behalf of @saad-ali ) doc fixes are still ok

**Review by zmerlynn — APPROVED** [review]
/lgtm

**Pull request merged**
