### PR TITLE
Bump l7-lb-controller resource usage threshold in tests

### LINKED ISSUE #45512: Regression in gce-scalability density test
As you can see, density test in our gce 100-node clusters has been constantly failing for many days now: https://k8s-testgrid.appspot.com/google-gce#gce-scalability
And in about 50-60% of these cases, the sole reason seems to be OOM'ing of L7 loadbalancer:
```
Container l7-lb-controller-v0.9.3-e2e-scalability-master/l7-lb-controller is using 62.90625/60 MB of memory
not to have occurred
```
It was bumped up to version 0.9.3 from 0.9.2 in commit https://github.com/kubernetes/kubernetes/commit/71ca925b05ba987e20c48ac0b83c19fea1bdb9aa and that seems to be the cause.
Maybe we should consider reverting this PR? (cc @nicksardo)

Could this be something related to the go1.8 upgrade which happened around the same time? (ref https://github.com/kubernetes/kubernetes/issues/45216)
And besides loadbalancer, we have kube-proxy OOM'ing too in the other 40% of the cases, but that seems to be an older issue (https://github.com/kubernetes/kubernetes/issues/44613).

cc @k8s-mirror-scalability-bugs @wojtek-t @gmarek

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #45512

### CODE REVIEW

**Comment by shyamjvs** [comment]
Any reason why 75 and not 65 (which I guess should also be fine)?

**Comment by wojtek-t** [comment]
I don't want to be that close to the real value (we're observing more than 63MB, so we can also observe more than 65MB).

**Comment by shyamjvs** [comment]
/lgtm

Just thought that tight bounds help keep us under better check over time :)

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by shyamjvs** [comment]
I guess the bazel test should pass once https://github.com/kubernetes/test-infra/pull/2727 is merged. It is an issue with git index locking, and retrying here might not help.

**Comment by shyamjvs** [comment]
@k8s-bot bazel test this
Let's see if it works now.

**Comment by shyamjvs** [comment]
Yup, it worked.

**Pull request merged**
