### PR TITLE
Use beta default class annotation for default storageclass tests.

### LINKED ISSUE #43150: [k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by * the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/795/

Failed: [k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by removing the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:349
Expected
    <bool>: true
to equal
    <bool>: false
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:356
```

Failed: [k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by changing the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:325
Expected
    <bool>: true
to equal
    <bool>: false
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go
```

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
The default storageclasses are still installed with the beta annotation, so the test should explicitly use the beta annotation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #43150

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@k8s-bot kops aws e2e test this

**Comment by msau42** [comment]
@k8s-bot kops aws e2e test this

**Comment by marun** [comment]
@msau42 Have you run the failing serial tests locally?  They won't run pre-merge in ci.

**Comment by msau42** [comment]
Yes, I ran all 3 dynamic provisioning tests locally with a freshly synced workspace.

**Comment by msau42** [comment]
@k8s-bot kops aws e2e test this

**Comment by ethernetdan** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gce e2e test this

**Comment by msau42** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
