### PR TITLE
Unset KUBERNETES_PROVIDER when KUBERNETES_CONFORMANCE_TEST is set

### LINKED ISSUE #26269: Conformance tests try to use gce as provider, when it should be provider independent
I'm trying to run e2e tests against my k8s cluster

```bash
export E2E_REPORT_DIR=${WORKSPACE}/results/
export NUM_MINIONS=2
export KUBERNETES_CONFORMANCE_TEST=y
export KUBECONFIG=${WORKSPACE}/k8s_files/kubeconfig.yml
hack/ginkgo-e2e.sh -host=https://10.91.97.170
```
 but i got error

```bash
00:00:17.997 /var/lib/jenkins/workspace/kubernetes-e2e-conformance-docker/src/k8s.io/kubernetes/cluster/../cluster/gce/util.sh: line 37: gcloud: command not found
00:00:18.000 !!! Error in /var/lib/jenkins/workspace/kubernetes-e2e-conformance-docker/src/k8s.io/kubernetes/cluster/../cluster/gce/util.sh:37
00:00:18.000   'gci_images=($(gcloud compute images list --project google-containers       --regexp='gci-dev.*' --format='value(name)'))' exited with status 127
00:00:18.001 Call stack:
00:00:18.001   1: /var/lib/jenkins/workspace/kubernetes-e2e-conformance-docker/src/k8s.io/kubernetes/cluster/../cluster/gce/util.sh:37 source(...)
00:00:18.001   2: /var/lib/jenkins/workspace/kubernetes-e2e-conformance-docker/src/k8s.io/kubernetes/cluster/kube-util.sh:100 source(...)
00:00:18.001   3: hack/ginkgo-e2e.sh:44 main(...)
00:00:18.001 Exiting with status 1
```

```KUBERNETES_CONFORMANCE_TEST=y``` should set ```KUBERNETES_PROVIDER``` to "", but its changed somehow to gce

Until yesterday it was working

### PR DESCRIPTION
**Pull request by pskrzyns**
fixes #26269
same as #26530 - i accidentally lost my fork and couldn't rebase there ;)
@mikedanese PTAL

### CODE REVIEW

**Comment by pskrzyns** [comment]
re-test cause failed test is flake https://github.com/kubernetes/kubernetes/issues/27335

**Comment by pskrzyns** [comment]
cc @kubernetes/sig-testing

**Comment by pskrzyns** [comment]
@spiffxp can we merge it ?

**Comment by spiffxp** [comment]
@pskrzyns this would be useful in the release-1.2 and release-1.3 branches, do you mind cherry-picking? otherwise I can cherry-pick in a day or so

**Comment by pskrzyns** [comment]
@spiffxp I created pull request for 1.3
as for 1.2 there is merge conflict and i dont know how to handle it so plz take a look

**Pull request merged**
