### PR TITLE
Juju kubernetes-master charm: improve status messages

### LINKED ISSUE #143: Kubernetes master reports ready/active but has not yet deployed supplementary containers
Juju reports the application as ready, but kubedns, etc are not yet deployed. After the 5 minute update-status window they appear.

Would at least accept messaging updates to waiting and "kube-system containers to start"

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This update to the kubernetes-master charm does the following:
1. Remove "Kubernetes master services ready" status which was occurring too early
2. Add "Waiting for kube-system pods to start" status
3. Replace "Rendering the Kubernetes DNS files." status with "Deploying KubeDNS"
4. Add "Waiting to retry KubeDNS deployment" status

The purpose of this is to give better feedback to the operator during cluster deployment.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/143, which we are tracking in a separate repository

**Special notes for your reviewer**:

This is a rebase of https://github.com/juju-solutions/kubernetes/pull/103, where prior review was done, though it was targeted against a fork.

**Release note**:

```release-note
Juju kubernetes-master charm: improve status messages
```

### CODE REVIEW

**Comment by mbruzek** [comment]
@k8s-bot ok to test

**Comment by mbruzek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40691)*

**Comment by ivan4th** [comment]
But perhaps I was added to juju OWNERS by mistake...

**Comment by Cynerva** [comment]
Thanks @ivan4th. I'll follow up with the team to see if we can get the owners file corrected.

**Comment by Cynerva** [comment]
@k8s-bot cvm gce e2e test this

Looks like a flaky test run, hoping we can try again.

**Comment by Cynerva** [comment]
@k8s-bot cvm gce e2e test this

One last try before I reach out for help on this one.

**Pull request merged**
