### PR TITLE
kubeadm: only taint CP nodes when the legacy "master" taint is present

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

During upgrade when a CP node is missing the old / legacy "master"
taint, assume the user has manually removed it to allow
workloads to schedule.

In such cases do not re-taint the node with the new "control-plane"
taint.

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/2200#issuecomment-1118213511

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: only taint control plane nodes when the legacy "master" taint is present. This avoids a bug where "kubeadm upgrade" will re-taint a control plane node with the new "control plane" taint even if the user explicitly untainted the node.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/triage accepted
/kind bug
/priority important-soon

/cc @pacoxu @SataQiu
PTAL for review.

**Review by pacoxu — COMMENTED** [review]
/lgtm

As this is only needed for upgrades from 1.23 to 1.24, this can be removed in v1.25 or later.
However, this logic has no side effects, so we can keep it.

**Comment by neolit123** [comment]
> As this is only needed for upgrades from 1.23 to 1.24, this can be removed in v1.25 or later.
However, this logic has no side effects, so we can keep it.

Yep we can change the code later in 1.25 following the KEP plan.

**Pull request merged**
