### PR TITLE
Removed duplicated 'default' in kubelet's help message

### PR DESCRIPTION
**Pull request by k82cn**
```release-note
None
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot kops aws e2e test this

**Comment by k82cn** [comment]
Example of duplicated default message in help:

```
      --host-network-sources stringSlice                        Comma-separated list of sources from which the Kubelet allows pods to use of host network. [default="*"] (default [*])
```

**Comment by dchen1107** [comment]
Thanks for helping us clean up the code base.

**Comment by k82cn** [comment]
/lgtm

echo dchen1107's lgtm.

**Comment by k82cn** [comment]
ping @dchen1107 for lgtm label; seems it's ignore by robot :)

**Comment by k82cn** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by k82cn** [comment]
@dchen1107 , ping for lgtm label :).

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Comment by k82cn** [comment]
@dchen1107 , ping for lgtm label :).

**Pull request merged**
