### PR TITLE
Re-add pkg/generated/bindata.go

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: I removed `pkg/generated/bindata.go` in #62432 as it had drifted out-of-date and was automatically generated by `make` and `bazel`.

This broke some downstream users who import `k8s.io/kubernetes`.

It's unclear whether the project intends for `k8s.io/kubernetes` to be vendorable, as there are other generated files which are not saved in the repo, including `pkg/generated/openapi/zz_generated.openapi.go` and `test/e2e/generated/bindata.go`, but `pkg/generated/bindata.go` seems to be a core dependency for current uses.

The new verify check added in #65882 will ensure that this file stays up-to-date. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This partially addresses #65968. We also need to cherry-pick this to release-1.11.

**Release note**:

```release-note
Re-adds `pkg/generated/bindata.go` to the repository to allow some parts of k8s.io/kubernetes to be go-vendorable.
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @thockin 
cc @mattfarina @tamalsaha @BenTheElder

**Comment by dims** [comment]
/lgtm

yes please!

**Comment by ixdy** [comment]
#65985 for cherrypick.

**Comment by ixdy** [comment]
#66009 for cherrypick.

**Pull request merged**
