### PR TITLE
Use versioned api in kube-proxy

### PR DESCRIPTION
**Pull request by fisherxu**
**What this PR does / why we need it**:
Now in kube-proxy someplace still use the internal version api, change to use versioned api. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danwinship** [comment]
so when are we supposed to use versioned vs unversioned APIs?

**Comment by MHBauer** [comment]
@danwinship as far as I can tell, pretty much never use the unversioned API unless you are in the rest<->storage layer of an apiserver.

**Comment by danwinship** [comment]
That is one seriously boring diff.
/lgtm

**Comment by thockin** [comment]
/lgtm
/approve

Thanks!

**Comment by fisherxu** [comment]
Thanks @thockin for approvel :)

**Pull request merged**
