### PR TITLE
remove empty line before ConformanceIt

### PR DESCRIPTION
**Pull request by Jefftree**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

Remove empty line between Conformance comments and ConformanceIt function. This affects some of our analysis tools.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

I can't see how this will have a negative impact. Curious if its possible to update the tools to handle whitespace? But that can be more of a long term thing.

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm
/approve

**Pull request merged**
