### PR TITLE
WIP: /dev/shm for pods.

### PR DESCRIPTION
**Pull request by mrunalp**
This is work in progress for https://github.com/GoogleCloudPlatform/kubernetes/issues/4823

### CODE REVIEW

**Comment by mrunalp** [comment]
@thockin Does this work for /dev/shm? This is a WIP. I will update it with tests once I know I am on the right path with the approach.

**Comment by vishh** [comment]
@mrunalp: It should work. Are you seeing any issues?

**Comment by mrunalp** [comment]
@vishh None so far. But thanks for the confirmation. I will fix the tests update the PR and test this more.

**Comment by mrunalp** [comment]
@vishh I updated the code to remove the shm volumes before creating mirror pod. However, from the test failures that I am seeing in integration, I think that these volumes are probably being getting cleaned up by cleanupOrphanedVolumes. Any suggestions on how to fix?

```
I0331 17:35:57.260266   23262 event.go:185] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"container-vm-guestbook-manifest-127", UID:"8b0c177115717f5d80a61795ead28644", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"implicitly required container POD"}): reason: 'started' Started with docker id /k8s_POD.60ca18de_container-vm-guestbook-manifest-127_default_8b0c177115717f5d80a61795ead28644_643b2633
I0331 17:35:57.260326   23262 event.go:185] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"container-vm-guestbook-manifest-127", UID:"8b0c177115717f5d80a61795ead28644", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{redis}"}): reason: 'created' Created with docker id /k8s_redis.4f581b06_container-vm-guestbook-manifest-127_default_8b0c177115717f5d80a61795ead28644_c7bcde60
I0331 17:35:57.260402   23262 event.go:185] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"container-vm-guestbook-manifest-127", UID:"8b0c177115717f5d80a61795ead28644", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{redis}"}): reason: 'started' Started with docker id /k8s_redis.4f581b06_container-vm-guestbook-manifest-127_default_8b0c177115717f5d80a61795ead28644_c7bcde60
I0331 17:35:57.260469   23262 event.go:185] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"container-vm-guestbook-manifest-127", UID:"8b0c177115717f5d80a61795ead28644", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{guestbook}"}): reason: 'created' Created with docker id /k8s_guestbook.288a2a8b_container-vm-guestbook-manifest-127_default_8b0c177115717f5d80a61795ead28644_dd32de06
I0331 17:35:57.260535   23262 event.go:185] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"container-vm-guestbook-manifest-127", UID:"8b0c177115717f5d80a61795ead28644", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{guestbook}"}): reason: 'started' Started with docker id /k8s_guestbook.288a2a8b_container-vm-guestbook-manifest-127_default_8b0c177115717f5d80a61795ead28644_dd32de06
E0331 17:35:57.266727   23262 kubelet.go:1453] Could not tear down volume "8b0c177115717f5d80a61795ead28644/shm": remove /tmp/kubelet_integ_2.858734698/pods/8b0c177115717f5d80a61795ead28644/volumes/kubernetes.io~empty-dir/shm: device or resource busy
F0331 17:35:57.754547   23262 integration.go:778] FAILED: unexpected endpoints: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1"' exited with status 255
```

**Comment by mrunalp** [comment]
One way could be to filter out these "shm" volumes in cleanupOrphanedVolumes, however that feels like a hack :(
@thockin @vishh Any ideas?

**Comment by vishh** [comment]
The kubelet's internal representation of a Pod changes often and so the volume you injected will disappear soon. 
@thockin suggested the following hack instead of using kubernetes volumes for this purpose.
```shell
docker run -it -v /dev/shm/pod_id:/dev/shm busybox
```
WDYT about re-using the hosts '/dev/shm'?

**Comment by thockin** [comment]
I apologize for dropping off radar for a week or two - my big PRs are in,
and I will be returning to review duty for a while :)

Specifically, /dev/shm/kubelet/pods/$pod_id would parallel
/var/lib/kubelet/...  It's quick and dirty.

**Comment by mrunalp** [comment]
@thockin Welcome back to PR reviews :)
@vishh @thockin Yes, that should work. I can rework the PR to do that. Thanks!

**Comment by brendandburns** [comment]
Closing per pull request policy, as it hasn't been updated in 21 days.  Please re-open when you have updated it.

**Pull request closed without merging**
