### PR TITLE
node e2e: stop testing trusty+docker 1.8

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
We should add a new image for docker v1.11 later.

**Comment by tmrts** [comment]
LGTM 👍

**Comment by vishh** [comment]
Marking as P1 to unblock another v1.3 PR that is dependent on this.

**Comment by dchen1107** [comment]
LGTM

**Comment by goltermann** [comment]
is this a candidate for retest-not-required, or do we need the submit queue to test it?

**Comment by dchen1107** [comment]
retest not required.

**Comment by erictune** [comment]
@yujuhong should this be a cherry-pick candidate?

**Comment by yujuhong** [comment]
Yes, it's required by #27208, which is a cherry-pick candidate.

**Comment by eparis** [comment]
I believe this was the very last PR to get in the 'fast forward'

**Comment by yujuhong** [comment]
> I believe this was the very last PR to get in the 'fast forward'

Yep, just verified that. Thanks!

**Pull request merged**
