### PR TITLE
MESOS: Add MESOS_DOCKER_DUMP_LOGS to enforce log dumping

### PR DESCRIPTION
**Pull request by sttts**
For e2e testing debugging we need the logs. This PR adds the MESOS_DOCKER_DUMP_LOGS variable which can be passed to kube-down to dump the logs (in the same way as in kube-up on error).

### CODE REVIEW

**Comment by karlkfi** [comment]
LGTM

**Comment by sttts** [comment]
@karlkfi done

**Comment by sttts** [comment]
@k8s-bot test this

**Comment by karlkfi** [comment]
The default configs needs to accept overrides, like everything else in that file.

**Comment by sttts** [comment]
@karlkfi good point. later night hacking....

**Comment by sttts** [comment]
@karlkfi PTAL

**Comment by sttts** [comment]
@karlkfi ping

**Pull request merged**
