### PR TITLE
add pwittrock to cli-maintainers and cli

### PR DESCRIPTION
**Pull request by pwittrock**
```release-note
NONE
```

Add pwittrock (sig-cli-tl) back so they can review and approve PRs.

### CODE REVIEW

**Comment by zhouya0** [comment]
You have to rebase your branch to get this test pass.

**Comment by pwittrock** [comment]
@zhouya0  thanks

**Comment by lavalamp** [comment]
/lgtm
/approve

(maybe next time you remove yourself, leave an `# emeritus` comment :) )

**Comment by pwittrock** [comment]
> (maybe next time you remove yourself, leave an # emeritus comment :) )

Good idea

**Pull request merged**
