### PR TITLE
Automated cherry pick of #17110

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #17110 on release-1.1.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
ref #17271

**Comment by lavalamp** [comment]
LGTM but tests broken

**Comment by jlowdermilk** [comment]
Both failures look like flakes.
@k8s-bot test this

**Comment by jlowdermilk** [comment]
@k8s-bot e2e test this

**Comment by lavalamp** [comment]
Agree this shouldn't cause the e2e failure I see (" [Fail] Docker Containers [It] should be able to override the image's default commmand (docker entrypoint) [Conformance] ").

Is the release branch broken?

@k8s-bot test this

**Comment by jlowdermilk** [comment]
Release branch [looks fine](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/), but it's possible that running e2e tests in parallel on 1.1 makes them flakier than usual (pr builder runs tests in parallel).

**Comment by jlowdermilk** [comment]
@k8s-bot e2e-test this

**Comment by jlowdermilk** [comment]
Durr... @k8s-bot e2e test this

**Comment by dalanlan** [comment]
Thanks :-)

**Pull request merged**
