### PR TITLE
Replace all time.Now().Sub with time.Since

### PR DESCRIPTION
**Pull request by shinytang6**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Just some small tweaks:) l found that `time.Now().Sub` are used in some places while others not. I think they should be consistent.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shinytang6** [comment]
I signed it

**Review by neolit123 — COMMENTED** [review]
/approve
/kind cleanup
/priority backlog

**Comment by neolit123** [comment]
@shinytang6 thanks for the PR.
/ok-to-test

**Comment by cheftako** [comment]
Not sure you found all occurences (I think you may have missed from of our Fake Clock code) My list is -
./staging/src/k8s.io/apimachinery/pkg/api/meta/table/table.go:70:	return duration.HumanDuration(time.Now().Sub(timestamp.Time))
./staging/src/k8s.io/apimachinery/pkg/util/clock/clock_test.go:47:	if tc.Now().Sub(tt) != time.Hour {
./staging/src/k8s.io/apimachinery/pkg/util/clock/clock_test.go:48:		t.Errorf("input: %s now=%s gap=%s expected=%s", tt, tc.Now(), tc.Now().Sub(tt), time.Hour)
./staging/src/k8s.io/apimachinery/pkg/util/wait/wait_test.go:534:	duration := time.Now().Sub(start)
./staging/src/k8s.io/apimachinery/pkg/util/wait/wait_test.go:558:	duration := time.Now().Sub(start)
./staging/src/k8s.io/client-go/tools/cache/reflector.go:366:	watchDuration := r.clock.Now().Sub(start)
./staging/src/k8s.io/client-go/util/flowcontrol/backoff_test.go:117:		t.Errorf("expected GC to skip entry, elapsed time=%s maxDuration=%s", tc.Now().Sub(lastUpdate), maxDuration)
./staging/src/k8s.io/client-go/util/flowcontrol/backoff_test.go:124:		t.Errorf("expected GC of entry after %s got entry %v", tc.Now().Sub(lastUpdate), r)
./staging/src/k8s.io/client-go/util/flowcontrol/backoff.go:102:	return p.Clock.Now().Sub(eventTime) < entry.backoff
./pkg/kubelet/remote/remote_runtime.go:299:		if time.Now().Sub(timeout) >= identicalErrorDelay {
./pkg/kubelet/remote/remote_runtime.go:320:		if !ok || err.Error() != lastMsg || time.Now().Sub(r.errorPrinted[containerID]) >= identicalErrorDelay {
./pkg/kubelet/remote/remote_runtime.go:508:		if !ok || err.Error() != lastMsg || time.Now().Sub(r.errorPrinted[containerID]) >= identicalErrorDelay {
./pkg/kubelet/kuberuntime/kuberuntime_manager.go:857:		if time.Now().Sub(timeout) >= identicalErrorDelay {
./pkg/kubelet/kuberuntime/kuberuntime_manager.go:916:		if !ok || err.Error() != lastMsg || time.Now().Sub(m.errorPrinted[podFullName]) >= identicalErrorDelay {
./pkg/kubelet/kuberuntime/kuberuntime_container.go:483:	return int64(metav1.Now().Sub(start.Time).Seconds())
./pkg/controller/route/route_controller.go:195:					klog.Infof("Created route for node %s %s with hint %s after %v", nodeName, route.DestinationCIDR, nameHint, time.Now().Sub(startTime))
./pkg/printers/internalversion/printers.go:848:		jobDuration = duration.HumanDuration(time.Now().Sub(obj.Status.StartTime.Time))
./pkg/cloudprovider/providers/gce/gce_tpu.go:161:		duration := time.Now().Sub(start)
./cmd/kubeadm/app/phases/upgrade/postupgrade.go:281:	if time.Now().Sub(certs[0].NotBefore) > expiry {
./plugin/pkg/auth/authorizer/node/node_authorizer_test.go:831:						diff := time.Now().Sub(start)

**Comment by shinytang6** [comment]
@cheftako Thanks for reminding! l have updated the code. PTAL

**Review by neolit123 — COMMENTED** [review]
/approve

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
please squash your commits into one @shinytang6

**Comment by shinytang6** [comment]
@neolit123 Done :)

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by cheftako** [comment]
Seems unlikely the failure was from this change, so I've set the test to rerun. It may just be a flake.

**Comment by shinytang6** [comment]
Hey @cheftako @neolit123 , do I still need approval from someone else?

**Comment by neolit123** [comment]
>> do I still need approval from someone else?

yes

> needs approval from a top-level approver or all the package maintainers.

try posting the in the #pr-reviews slack channel.

**Comment by dims** [comment]
Thanks @thockin

**Pull request merged**
