### PR TITLE
Move blunderbuss assignees into tree

### PR DESCRIPTION
**Pull request by eparis**
Until the submit queue code lands this has 0 effect. But it's hard(ish) to test the submit-queue code without these being here.

### CODE REVIEW

**Comment by eparis** [comment]
@bgrant0607 @lavalamp When this gets merged it'll enabled me to turn on the other half.

**Comment by eparis** [comment]
https://github.com/kubernetes/contrib/pull/530 is blocked until this merges

**Comment by eparis** [comment]
@k8s-bot test this flake: #22244

**Comment by lavalamp** [comment]
LGTM - exciting!

**Comment by eparis** [comment]
removing LGTM so I can put it back after I updated to include https://github.com/kubernetes/contrib/pull/531

**Comment by bgrant0607** [comment]
Thanks!

**Comment by bgrant0607** [comment]
Would it be possible to indirect through github teams? For instance, use kubernetes/kubectl (and other people) for pkg/kubectl?

**Comment by eparis** [comment]
Not yet, no. But it's software, anything's possible.

**Pull request merged**
