### PR TITLE
[WIP] Experiments with containerd/runc DO NOT MERGE (1e902b2d)

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
xref: https://github.com/kubernetes/kubernetes/pull/91733

**Comment by BenTheElder** [comment]
Timeout https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91746/pull-kubernetes-e2e-gce-ubuntu-containerd/1268360302756368384/
/retest

**Comment by BenTheElder** [comment]
pod status failed https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91746/pull-kubernetes-e2e-gce-ubuntu-containerd/1268388362373304323/ @liggitt ding ding ding
/retest

**Comment by dims** [comment]
/retitle [WIP] Experiments with containerd/runc DO NOT MERGE (g1e902b2d)

**Comment by dims** [comment]
/retitle [WIP] Experiments with containerd/runc DO NOT MERGE (1e902b2d)

**Comment by dims** [comment]
unrelated failure:

/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by dims** [comment]
unrelated failure
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by dims** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91746/pull-kubernetes-e2e-gce-ubuntu-containerd/1268954581103022080/
```k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container ```

/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Pull request closed without merging**
