### PR TITLE
Added namespace to Spark example.

### PR DESCRIPTION
**Pull request by k82cn**
Issues #23537 [Added namespace to Spark example].

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
do we need something to actually create that namespace?
please squash to a single commit.

**Comment by zmerlynn** [comment]
You're going to have to change the example instructions if you do this - you can't just change the resource file. The instructions are assuming you're using the default namespace.

**Comment by k82** [comment]
@zmerlynn , do you mean it also need to update `README.md` that Spark's using `spark-cluster` as namespace explicitly?

**Comment by zmerlynn** [comment]
@k82: Yes, exactly. The example is not just the resources, but the set of instructions as well.

**Comment by k82** [comment]
Updated branch to squash to a single commit :).

**Comment by eparis** [comment]
ok to test

**Comment by k82** [comment]
Update README accordingly.

**Comment by eparis** [comment]
I think `--namepsace=` is deprecated. I feel like `examples/cluster-dns` does a good job showing namespaces...   I know that the openshift and k8s-pet-store still use --namespace, but I think those should be re-written...

**Comment by k82** [comment]
@eparis , sure, I'll update this to follow `examples/cluster-dns` way; and should we log the other issues for k8s-pet-store & openshift, or just pull request is fine?

**Comment by eparis** [comment]
File an issue, and if you want, update them yourself!

**Comment by k82** [comment]
Sure, I'll file an issue and update them :).

**Comment by k82** [comment]
ping @eparis  :).

**Comment by eparis** [comment]
I notice in the e2e tests that this is failing in 
FAIL	k8s.io/kubernetes/examples	0.874s
when running hack/test-go.sh

Given that is exactly the area you are touching I'm going to first believe it is not a flake and is a real issue. What do you get when you run that test locally?

**Comment by k82** [comment]
Thanks for your comments :). I think I missed e2e's case for namespace; update the code accordingly.

**Comment by eparis** [comment]
ok to test

**Pull request merged**
