### PR TITLE
Fix comments

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by soltysh** [comment]
/unassign
@brendandburns mind approving this as well, since you have the necessary power.

**Comment by zjj2wry** [comment]
@brendandburns mind add the ```no issue```,  thanks

**Comment by byronyi** [comment]
Seems to be a bot fight :( @gyliu513 could you help to stop this?

**Pull request merged**
