### PR TITLE
Extend OpenStack Cloud Provider Instance Tests

### PR DESCRIPTION
**Pull request by dagnello**
Adding OpenStack cloud provider Instance coverage for:
ExternalID
InstanceID

### CODE REVIEW

**Comment by davidopp** [comment]
cc/ @ashw7n

**Comment by davidopp** [comment]
@dagnello Please see this comment about the CLA -- looks like you did not sign it yet
https://github.com/kubernetes/kubernetes/pull/23770#issuecomment-204616178

**Comment by davidopp** [comment]
@dagnello I'm not sure why you're getting this error from the cla-bot
https://github.com/kubernetes/kubernetes/pull/23770#issuecomment-204616178
as it seems that the commit was authored by you. Can you look into it though?

**Comment by davidopp** [comment]
ok to test

**Comment by dagnello** [comment]
@davidopp looks like I submitted this commit prior to accepting the CLA.

**Comment by dagnello** [comment]
cla/google test

**Comment by yujuhong** [comment]
@dagnello, it doesn't seem like the email you use in the commit is associated with your github account. Could you try making them consistent?

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
