### PR TITLE
fix portallocator comments

### PR DESCRIPTION
**Pull request by drinktee**
**What this PR does / why we need it**:
fix portallocator comments

**Which issue(s) this PR fixes** :

**Release note**:
NONE

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
/lgtm

Tagging @soltysh for /approve tag

**Comment by soltysh** [comment]
> Tagging @soltysh for /approve tag

I don't have that power here, @liggitt or @deads2k are good candidates.

**Pull request merged**
