### PR TITLE
fixbug: fix gce deprecated method

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

> /kind bug

**What this PR does / why we need it**:
fix gce deprecated method
image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zgfh** [comment]
@yujuhong @mwielgus please have a look

**Comment by zgfh** [comment]
@neolit123 anything should I do to merge this ?

**Comment by neolit123** [comment]
/assign @vishh
as recommended by the bot.

@zgfh the PR needs approval.
if you are getting no response try pinging someone from this file on k8s slack:
https://github.com/kubernetes/kubernetes/blob/417310ca122939e8e0a27ad62ed108c0f9eabf4d/cluster/gce/OWNERS

**Pull request closed without merging**
