### PR TITLE
fix verify gendocs

### PR DESCRIPTION
**Pull request by mikedanese**
master verify gendocs is broken. GA beacon and other stuff.

### CODE REVIEW

**Comment by mikedanese** [comment]
@lavalamp

**Comment by lavalamp** [comment]
LGTM

**Comment by zmerlynn** [comment]
How did this get past Shippable? My bad. :(

**Comment by lavalamp** [comment]
It was probably a merge of something with a stale pass.

**Comment by zmerlynn** [comment]
Yeah, this is a case where we need a submit queue versus a presubmit check.

**Comment by mbforbes** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11073#issuecomment-120511345 +1

**Comment by zmerlynn** [comment]
@rjnagal for merge

**Comment by bgrant0607** [comment]
Build is broken, so I'm merging.

**Pull request merged**
