### PR TITLE
kubelet: Add container runtime option for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
Second take after #7743 since the glibc problem should be gone now by #7859

/cc @vmarmol @dchen1107 @yujuhong

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM.

**Comment by vmarmol** [comment]
LGTM :)

**Comment by ixdy** [comment]
This PR broke non-Linux builds:
```
+++ [0507 19:52:01] linux/amd64: go build started
+++ [0507 19:52:23] linux/amd64: go build finished
+++ [0507 19:52:01] linux/386: go build started
+++ [0507 19:52:28] linux/386: go build finished
+++ [0507 19:52:01] linux/arm: go build started
+++ [0507 19:52:27] linux/arm: go build finished
+++ [0507 19:52:01] darwin/amd64: go build started
# github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt/gc.go:21: undefined: runtime
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341 kube::golang::build_binaries_for_platform(...)
  2: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:447 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:31 main(...)
Exiting with status 1
+++ [0507 19:52:01] darwin/386: go build started
# github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt/gc.go:21: undefined: runtime
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341 kube::golang::build_binaries_for_platform(...)
  2: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:447 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:31 main(...)
Exiting with status 1
+++ [0507 19:52:01] windows/amd64: go build started
# github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt/gc.go:21: undefined: runtime
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341 kube::golang::build_binaries_for_platform(...)
  2: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:447 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:31 main(...)
Exiting with status 1
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:384
  '( kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eval "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local parallel=false; if [[ ${#platforms[@]} -gt 1 ]]; then
    local gigs; gigs=$(kube::golang::get_physmem); if [[ ${gigs} -gt ${KUBE_PARALLEL_BUILD_MEMORY} ]]; then
        kube::log::status "Multiple platforms requested and available ${gigs}G > threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in parallel"; parallel=true;
    else
        kube::log::status "Multiple platforms requested, but available ${gigs}G < threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in serial"; parallel=false;
    fi;
fi; if [[ "${parallel}" == "true" ]]; then
    kube::log::status "Building go targets for ${platforms[@]} in parallel (output will appear in a burst when complete):" "${targets[@]}"; local platform; for platform in "${platforms[@]}";
    do
        ( kube::golang::set_platform_envs "${platform}"; kube::log::status "${platform}: go build started"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-}; kube::log::status "${platform}: go build finished" ) &> "/tmp//${platform//\//_}.build" &
    done; local fails=0; for job in $(jobs -p);
    do
        wait ${job} || let "fails+=1";
    done; for platform in "${platforms[@]}";
    do
        cat "/tmp//${platform//\//_}.build";
    done; exit ${fails};
else
    for platform in "${platforms[@]}";
    do
        kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; kube::golang::set_platform_envs "${platform}"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-};
    done;
fi )' exited with status 3
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:384 kube::golang::build_binaries(...)
  2: hack/build-cross.sh:31 main(...)
Exiting with status 1
!!! Error in /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:433
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:433 kube::build::run_build_command(...)
  2: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/release.sh:32 main(...)
Exiting with status 1
```

**Comment by vmarmol** [comment]
Reverted and will try again. We still need the stubs for these cases.

**Comment by yifan-gu** [comment]
I think we can remove the build label

**Pull request merged**
