### PR TITLE
Expose informer constructors

### LINKED ISSUE #45939: Expose Informer constructors in generated clientsets
This is a feature request.

I'd like to reuse methods like [newDeploymentInformer()](https://github.com/kubernetes/kubernetes/blob/b844f7d4a4018beb664a9f0b075d83f717a631ab/staging/src/k8s.io/client-go/informers/apps/v1beta1/deployment.go#L44) but they are private at the moment.
The use case: I need to construct Informers for a specific namespace (or a set of namespaces) and instead of reusing this code I have to duplicate it many times (per object Kind). Would be awesome if Informers generator is updated to expose an additional method that does the same but also takes a namespace name as an argument. Seems to be no risk and a trivial change.
I'm more than happy to make the change myself if some guidance is provided :)

EDIT: additional details about the use case: I want to be able to limit [Smith](https://github.com/atlassian/smith) to only work with a single namespace because it may be run in a restricted environment where it only has permissions to work within a single namespace. That is a real use case: we have a cluster where a user (a team) gets very limited permissions - can only do things within their own namespace. However such team should be able to use tools like Smith.

I had to copy-paste and modify lots of code for informers I need - see https://github.com/atlassian/smith/pull/58/files#diff-e2db373b7d288a95d41535cb69e73f7d

### PR DESCRIPTION
**Pull request by ash2k**
**What this PR does / why we need it**:
See #45939

**Which issue this PR fixes**
Fixes #45939

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ash2k** [comment]
ptal @eparis @lavalamp

**Comment by ncdc** [comment]
It does seem a bit backwards to have a private constructor calling a public one. I wonder if it would make more sense to modify the `Informer()` definitions to inline like this?

```go
func (f *controllerRevisionInformer) Informer() cache.SharedIndexInformer {
  return f.factory.InformerFor(
    &apps_v1beta1.ControllerRevision{},
    func(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
      return NewControllerRevisionInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
    },
  )
}
```

It's certainly not necessary to make this change. Or if not this, maybe rename `newControllerRevisionInformer` to something like `defaultControllerRevisionInformer`?

I'm ok proceeding with this PR. @deads2k @sttts @liggitt wdyt? 

cc @kubernetes/sig-api-machinery-pr-reviews 

/ok-to-test

**Comment by liggitt** [comment]
this does make it more likely someone will create a new informer when they should get a shared one from a factory...

**Comment by ncdc** [comment]
@liggitt that's certainly a possibility, but I think we have an established pattern that hopefully people will continue to follow. Also, we can either periodically manually audit for new unshared informers, or write some tooling to warn about them. I know @smarterclayton will certainly let everyone know when he spots new duplicate caches 😄

**Comment by deads2k** [comment]
> this does make it more likely someone will create a new informer when they should get a shared one from a factory...

As I recall the use-case from slack, he wanted to create an informer for a specific namespace he was managing.  That was never going to be shared.

**Comment by ncdc** [comment]
@deads2k correct. If you look at the description for #45939, it has been updated with more details about the use case.

**Comment by smarterclayton** [comment]
`o-o' <-- me

**Comment by ash2k** [comment]
Rebased, renamed method as per suggestion, re-generated code.

@ncdc IMHO version with named function reads better (less clutter) but I can make the change, no problem. PTAL.

**Comment by caesarxuchao** [comment]
> this does make it more likely someone will create a new informer when they should get a shared one from a factory...

@ash2k Can we add a comment at the new public methods telling people to get informer from the factory when possible?

**Comment by ash2k** [comment]
@caesarxuchao added a comment

**Comment by ash2k** [comment]
@lavalamp @wojtek-t ptal

**Comment by caesarxuchao** [comment]
Thanks. lgtm.

**Comment by ash2k** [comment]
@ncdc could you add lgtm label again please?

**Comment by ncdc** [comment]
@ash2k please rebase, then I'll relabel

**Comment by ash2k** [comment]
@ncdc rebased.

**Comment by ash2k** [comment]
PR, go away from my dashboard (https://github.com/kubernetes/test-infra/issues/1576)

**Pull request merged**
