### PR TITLE
Remove  pkg/kubectl/cmd/rollout from lintignore with changes

### PR DESCRIPTION
**Pull request by alex-slynko**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
General linter cleanup

**Which issue(s) this PR fixes**:
Part of #68026

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by prksu** [comment]
Hi @alex-slynko thanks for your PR

This PR related to kubectl not kubelet. Please change your PR title ~~kubelet/pkg/rollout~~ to pkg/kubectl/cmd/rollout

**Comment by alex-slynko** [comment]
Sorry, fixed it @prksu

**Pull request closed without merging**
