### PR TITLE
scheduler:  Rename UpdatePodTolerations for code style consistency

### LINKED ISSUE #129015: Rename `UpdatePodTolerations` to `UpdatePodToleration` for code style consistency
### What would you like to be added?

Checked the scheduler `ActionTypes`, finding a non-consistent error about `UpdatePodTolerations` which we usually name it with singular, like `UpdatePodLabel`, `UpdateNodeTaint`.

However, this may lead to backward incompatibility, but the framework is not versioned, so I think it's ok, just need to add a `action required` for reminding.

cc @kubernetes/sig-scheduling-misc 

/kind cleanup
/remove-kind feature

### Why is this needed?

code style consistency.

### PR DESCRIPTION
**Pull request by zhifei92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The other scheduler ActionTypes are singular. Here, we rename UpdatePodTolerations to UpdatePodToleration for code style consistency.

#### Which issue(s) this PR fixes:

Fixes #129015

#### Does this PR introduce a user-facing change?

```release-note
Action required for custom plugin developers.
The `UpdatePodTolerations` action type is renamed to `UpdatePodToleration`, you have to follow the renaming if you're using it.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
@zhifei92 We need a release note on this since it's a breaking change for the custom plugins.

**Comment by zhifei92** [comment]
> We need a release note on this since it's a breaking change for the custom plugins.

Please check if it's ok.

**Comment by haosdent** [comment]
I have a minor suggestion regarding the title. Should we avoid using "refactor(scheduler)" in the title of this MR since it is more like fixing the code style issues than refactoring something in the scheduler?

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by sanposhiho** [comment]
/release-note-edit
```release-note
Action required for custom plugin developers.
The `UpdatePodTolerations` action type is renamed to `UpdatePodToleration`, you have to follow the renaming if you're using it.
```

**Review by kerthcet — COMMENTED** [review]
/lgtm

But I think better not to use word like `you` in the statement, my suggestion is like 
```
ACTION REQUIRED:  Replace action type `UpdatePodTolerations` with `UpdatePodToleration` in customized scheduler plugins if used.
```

The sig doc team will put another eye on this I believe. cc @sftim

**Pull request merged**
