### PR TITLE
Backport of #17401 to release-1.1

### PR DESCRIPTION
**Pull request by aaronlevy**
Backport of https://github.com/kubernetes/kubernetes/pull/17401

### CODE REVIEW

**Comment by philips** [comment]
@k8s-teamcity-mesosphere What does: "[20:13:08][Step 6/6] ERROR: Invalid interpolation format for "entrypoint" option in service "mesosslave" mean? This seems like a problem on the testing side.

**Comment by ixdy** [comment]
ok to test

**Comment by karlkfi** [comment]
The Mesosphere smoke tests are not currently working on cherry-pick PRs. You can ignore it for now, @philips 

It has to do with the master test script changes not having all been cherry-picked yet.

**Comment by aaronlevy** [comment]
Rebased against release-1.1 to include fixes to unrelated unit-test failures.

**Comment by dchen1107** [comment]
LGTM.

**Comment by zmerlynn** [comment]
Kermity, merging.

**Pull request merged**
