### PR TITLE
Use realistic value for the memory example of kube-reserved and system-reserved

### PR DESCRIPTION
**Pull request by nak3**
Use realistic value for the memory example of kube-reserved and system-reserved

Currently, kublet help shows the memory example of
kube-reserved and system-reserved as 150G. This 150G is not realistic
value and it leads misconfiguration or confusion. This patch changes
to example value as 500Mi.

Before(same with system-reserved):
```
      --kube-reserved value                                A set of ResourceName=ResourceQuantity (e.g. cpu=200m,memory=150G) pairs that describe resources reserved for kubernetes system components. Currently only cpu and memory are supported. See http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md for more detail. [default=none]
```

After(same with system-reserved):
```
      --kube-reserved value                                A set of ResourceName=ResourceQuantity (e.g. cpu=200m,memory=500Mi) pairs that describe resources reserved for kubernetes system components. Currently only cpu and memory are supported. See http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md for more detail. [default=none]
```

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot ok to test

**Comment by derekwaynecarr** [comment]
@k8s-bot cvm gce e2e test this

**Comment by derekwaynecarr** [comment]
this is a bug fix that should go in 1.6 milestone.  the help text here will cause confusion if not addressed.

**Review by derekwaynecarr — APPROVED** [review]

**Comment by liggitt** [comment]
@k8s-bot bazel test this

**Pull request merged**
