### PR TITLE
pkg:kubelet: fix import issue caused by merging conflicts

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by yifan-gu** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/6766/files

**Comment by vmarmol** [comment]
@xiang90 we just merged #6767 which did the same. Sorry I didn't see yours till now :P thanks for the fix though!

**Comment by xiang90** [comment]
@pmorie @vmarmol Oh. You are too fast.

**Pull request closed without merging**
