### PR TITLE
Update k/utils to v0.0.0-20211116205334-6203023598ed

### LINKED ISSUE #100241: kubelet uses 120GB memory after 20,000 job created and retains 80GB memory after jobs completed and deleted
#### What happened:
1.create 20K job and each job is a java application running data monitor and analysis 
2.delete all jobs after they have been completed
3.kubelet memory usage 120GB memory:
```
Name:   kubelet
Umask:  0022
State:  S (sleeping)
Tgid:   9278
Ngid:   9278
Pid:    9278
PPid:   9274
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 1024
Groups:
VmPeak: 126307060 kB
VmSize: 126307056 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:  106238456 kB
VmRSS:  85699368 kB
RssAnon:        85675408 kB
RssFile:           23960 kB
RssShmem:              0 kB
VmData: 126179776 kB
VmStk:       132 kB
VmExe:     48260 kB
VmLib:      2072 kB
VmPTE:    210628 kB
VmSwap:    72604 kB
Threads:        362
```

#### What you expected to happen:
kubelet should use and retain less memory 

#### Anything else we need to know?:
Through pprof,we find the inuse_space size is 360MB.And 67% of 120GB is Anonymous(through mmap?).

#### Environment:
- Kubernetes version (use `kubectl version`):
- Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-22T06:47:35Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Centos 7.5
- Kernel (e.g. `uname -a`):
- 3.10.0-957.21.3.el7.x86_64 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
pprof png:
profile002

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Cherry-pick of #106473.
I think we can expect quite a big performance boost from this PR.

https://github.com/kubernetes/kubernetes/issues/100241#issuecomment-1016399463
#### Which issue(s) this PR fixes:

Fixes #100241

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
/lgtm

This picks up https://github.com/kubernetes/utils/pull/228 which fixes an inotify memory leak. The utils inotify package is used by cAdvisor and (thus by kubelet), so backporting this should help address the kubelet memory leak.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
