### PR TITLE
docs: update `kubectl` to use proper testgrid url

### PR DESCRIPTION
**Pull request by rjsadow**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
This PR corrects the testgrid url that was changed by sig-k8s-infra and sig-testing earlier this year. 

#### Which issue(s) this PR fixes:
ref: https://github.com/kubernetes/test-infra/issues/30370

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @ardaguclu @brianpursley @eddiezane @KnVerey @mpuckett159 @seans3 @soltysh

### CODE REVIEW

**Comment by mpuckett159** [comment]
Whoops wasn't paying attention

/lgtm

**Comment by letmerecall** [comment]
duplicate of #119934 ?

**Comment by rjsadow** [comment]
> duplicate of #119934 ?

Heh, yep! Thanks :)

**Pull request closed without merging**
