### PR TITLE
WIP: test agnhost 2.30

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

#### What this PR does / why we need it:

Dummy PR to validate staging test images.

/hold

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
thanks @chewong :)

note that you can open PR as a draft as well and you can still run CI jobs.

**Comment by chewong** [comment]
The test result looks good. It hasn't failed once

**Pull request closed without merging**
