### PR TITLE
fix satisfy typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix satisfy typo

### CODE REVIEW

**Comment by grodrigues3** [comment]
Alright, this seems like a lot of overhead for a really simple PR.  @thockin @brendandburns I'll open a ticket to try and make the assignee (for review and LGTM) and the approver (for approve) the same person if the content of the PR allows.

**Comment by fejta** [comment]
@k8s-bot bazel test this issue https://github.com/kubernetes/test-infra/pull/2105

**Comment by timchenxiaoyu** [comment]
@k8s-bot test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot non-cri node e2e test this
@k8s-bot verify test this
@k8s-bot node e2e test this
@k8s-bot kubemark e2e test this
@k8s-bot unit test this
@k8s-bot gci gke e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by grodrigues3** [comment]
@k8s-bot verify test this

**Pull request merged**
