### PR TITLE
Remove problematic Dbus restart test

### LINKED ISSUE #121124: GracefulNodeShutdown tests failing due to connection with dbus
### Which jobs are failing?

Any test that runs Gracefulshutdown seems to be having issues.

### Which tests are failing?

Reference: https://github.com/kubernetes/kubernetes/issues/120726

In this case, they are failing consistently.

### Since when has it been failing?

The tests were flaky but as of 9/29, they have been failing ever since.

### Testgrid link

https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd

### Reason for failure (if possible)

@rphillips and I were looking into these failures.  We are able to reproduce on a GCP instance but we are seeing failures to sending dbus shutdown signals.

We have looked into this code but it does not look like any code is responsible for this failure.  One thing we did see is that there was a new release of COS around then.

We are seeing failures in the logs.

Running this test locally we can sometimes see issues with dbus.

```
E1010 20:47:08.348826    3687 nodeshutdown_manager_linux.go:193] "Unable to watch the node for shutdown events" err="failed reading InhibitDelayMaxUSec property from logind: Failed to activate service 'org.freedesktop.login1': timed out (service_start_timeout=25000ms)"
```

Running this locally (after copying the image config):

### Anything else we need to know?

```
export SSH_USER=core && make test-e2e-node INSTANCE_PREFIX=kehannon REMOTE=true IMAGE_CONFIG_FILE="/home/kehannon/Downloads/image-config-serial.yaml" CLEANUP=false RUNTIME=remote CONTAINER_RUNTIME_ENDPOINT="unix:///run/containerd/containerd.sock" FOCUS="after restart dbus, should be able to gracefully shutdown" SKIP="" TEST_ARGS='--kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
```

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by kwilczynski**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

Restarting the Dbus broker service at runtime is generally not recommended or supported according to the feedback from the systemd maintainers.

Many systemd components (but also other software and services) that rely on Dbus wouldn't reconnect to a new Unix socket following the Dbus broker restart. This can lead to anything from authentication timeouts (since the systemd-logind and the polkitd services would be impacted) to the system generally broken following the Dbus broker restart. 

Different software might handle this differently and choose to reconnect on a socket write or read timeout. However, systemd at large is not one of these.

Given that tests are nowadays commonly run on either Googe Container-optimised OS (COS) or Fedora CoreOS, the addition of the Dbus broker restart has unwelcome side effects on these platforms.

Thus, remove a problematic test that performs Dbus broker restart and, in doing so, fix several currently failing tests on platforms that do not handle Dbus service restart gracefully.

#### Which issue(s) this PR fixes:

Fixes #121124

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by kannon92** [comment]
Btw, serial jobs are the ones that will run this.

/test pull-kubernetes-node-kubelet-serial-containerd

**Comment by saschagrunert** [comment]
Ou, this looks like a flake worth of investigation:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121506/pull-kubernetes-node-crio-e2e/1717135391808557056


```
{ failed [FAILED] Expected
    <string>: 3e0d9138669908f438c06993e9a6815bbd8c05411b8e9acfc297b3c8b017c28c
to contain substring
    <string>: registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9
In [It] at: test/e2e_node/image_id_test.go:69 @ 10/25/23 11:32:39.356
}
```

/test pull-kubernetes-node-crio-e2e
/test pull-kubernetes-node-kubelet-serial-containerd

**Comment by kannon92** [comment]
I think this test will really help the serial tests.  

We are starting to get test reports with this fix.  

My main concern is this worth calling out as an unsupported item for this feature?

**Comment by rphillips** [comment]
/lgtm

@kwilczynski WIP needs to be removed.

**Review by mrunalp — APPROVED** [review]

**Comment by rphillips** [comment]
According to systemd maintainers, restarting dbus and using systemd is an unsupported operation.

We are seeing `sudo` timeouts in CI based on the restart and systemd-logind hanging on the request. This is causing CI jobs to hit their time limit (roughly 4 hours).

**Comment by saschagrunert** [comment]
Have a fix for the failing image ID test in https://github.com/kubernetes/kubernetes/pull/121531

**Pull request merged**
