### PR TITLE
update prompt in create rolebinding/clusterrolebinding

### PR DESCRIPTION
**Pull request by xilabao**

### CODE REVIEW

**Comment by ncdc** [comment]
@deads2k @liggitt

**Comment by deads2k** [comment]
lgtm

**Comment by xilabao** [comment]
@k8s-bot bazel test this

**Comment by rmmh** [comment]
@k8s-bot bazel test this

**Comment by rmmh** [comment]
@k8s-bot bazel test this

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #34953

**Comment by pwittrock** [comment]
@k8s-bot ok to test

**Pull request merged**
