### PR TITLE
Fix kubelet AppArmor rejection test

### LINKED ISSUE #125829: Failure cluster [cd640ec5...] `Cannot enforce AppArmor: AppArmor is not enabled on the host`
##### Error text:
```
[FAILED] PodStatus: {Phase:Failed Conditions:[] Message:Pod was rejected: Cannot enforce AppArmor: AppArmor is not enabled on the host Reason:AppArmor NominatedNodeName: HostIP: HostIPs:[] PodIP: PodIPs:[] StartTime:2024-06-28 22:07:45 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[] Resize: ResourceClaimStatuses:[]}
Expected
    <v1.PodPhase>: Failed
to equal
    <v1.PodPhase>: Pending
In [It] at: k8s.io/kubernetes/test/e2e_node/apparmor_test.go:234 @ 06/28/24 22:07:45.325

```
#### Recent failures:
[7/1/2024, 11:31:16 AM ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1807798937965301760)
[7/1/2024, 11:28:16 AM ci-crio-cgroupv2-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-features/1807798182281744384)
[7/1/2024, 11:22:18 AM ci-kubernetes-node-swap-fedora](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-fedora/1807796672529436672)
[7/1/2024, 10:30:17 AM ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1807783585558564864)
[7/1/2024, 10:27:17 AM ci-crio-cgroupv2-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-features/1807782831171047424)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
The corresponding e2e test needs to be adjusted side by side to the merged PR: https://github.com/kubernetes/kubernetes/pull/125776.
#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/125829

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Green tests :green_circle:: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125860/pull-crio-cgroupv1-node-e2e-features/1808433520016625664

**Comment by saschagrunert** [comment]
/assign @dims 

PTAL too @harche @sohankunkerkar @sairameshv @haircommander

**Comment by dims** [comment]
thanks @saschagrunert 

/approve
/lgtm

/hold

(if you need additional reviewers, if not please remove hold)

**Pull request merged**
