### PR TITLE
kubectl print endpoint list

### PR DESCRIPTION
**Pull request by deyuanix**
/cc @thockin

### CODE REVIEW

**Comment by ddysher** [comment]
With the PR, we can do:
```
$ cluster/kubectl.sh get endpoints               
current-context: "lucid-walker-725_kubernetes"
Running: cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl get endpoints
NAME                    ENDPOINTS
elasticsearch-logging   10.244.2.6:9200
kibana-logging          10.244.1.5:80
kube-dns                10.244.3.5:53
kubernetes              10.240.100.146:6443
kubernetes-ro           10.240.100.146:7080
monitoring-grafana      10.244.2.5:80
monitoring-heapster     10.244.0.6:8082
monitoring-influxdb     10.244.2.5:8086

$ cluster/kubectl.sh get endpoints kubernetes
current-context: "lucid-walker-725_kubernetes"
Running: cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl get endpoints kubernetes
NAME                ENDPOINTS
kubernetes          10.240.100.146:6443
```

Otherwise:
```
$ cluster/kubectl.sh get endpoints
current-context: "lucid-walker-725_kubernetes"
Running: cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl get endpoints
F0223 21:11:33.319125   14264 get.go:168] error: unknown type &api.EndpointsList{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"/api/v1beta1/endpoints?namespace=default", ResourceVersion:"1455"}, Items:[]api.Endpoints{api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"elasticsearch-logging", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/elasticsearch-logging?namespace=default", UID:"f0f91b8e-bbc2-11e4-acfb-42010af06492", ResourceVersion:"303", CreationTimestamp:util.Time{Time:time.Time{sec:63560337466, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.2.6", Port:9200}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kibana-logging", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/kibana-logging?namespace=default", UID:"f0fca9f0-bbc2-11e4-acfb-42010af06492", ResourceVersion:"218", CreationTimestamp:util.Time{Time:time.Time{sec:63560337466, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.1.5", Port:80}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-dns", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/kube-dns?namespace=default", UID:"ded2c061-bbc2-11e4-acfb-42010af06492", ResourceVersion:"246", CreationTimestamp:util.Time{Time:time.Time{sec:63560337436, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"UDP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.3.5", Port:53}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kubernetes", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/kubernetes?namespace=default", UID:"", ResourceVersion:"7", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.240.100.146", Port:6443}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kubernetes-ro", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/kubernetes-ro?namespace=default", UID:"", ResourceVersion:"6", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.240.100.146", Port:7080}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"monitoring-grafana", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/monitoring-grafana?namespace=default", UID:"dee0a098-bbc2-11e4-acfb-42010af06492", ResourceVersion:"319", CreationTimestamp:util.Time{Time:time.Time{sec:63560337436, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.2.5", Port:80}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"monitoring-heapster", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/monitoring-heapster?namespace=default", UID:"dee37e23-bbc2-11e4-acfb-42010af06492", ResourceVersion:"335", CreationTimestamp:util.Time{Time:time.Time{sec:63560337436, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.0.6", Port:8082}}}, api.Endpoints{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"monitoring-influxdb", GenerateName:"", Namespace:"default", SelfLink:"/api/v1beta1/endpoints/monitoring-influxdb?namespace=default", UID:"dee604f4-bbc2-11e4-acfb-42010af06492", ResourceVersion:"320", CreationTimestamp:util.Time{Time:time.Time{sec:63560337436, nsec:0, loc:(*time.Location)(0xf1a360)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Protocol:"TCP", Endpoints:[]api.Endpoint{api.Endpoint{IP:"10.244.2.5", Port:8086}}}}}

$ cluster/kubectl.sh get endpoints kubernetes
current-context: "lucid-walker-725_kubernetes"
Running: cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl get endpoints kubernetes
NAME                ENDPOINTS
kubernetes          10.240.100.146:6443
```

**Comment by bgrant0607** [comment]
Awesome. LGTM.

**Comment by thockin** [comment]
LGTM.  I'll merge with my PR when this goes in.

**Comment by satnam6502** [comment]
Is it worth relating these endpoints to any publicly exposed IPs for services that map to these endpoints?

**Pull request merged**
