### PR TITLE
tests: Updates resource-consumer to 1.9 in tests

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing
/sig windows

/priority important-soon

#### What this PR does / why we need it:

``resource-consumer:1.9`` also includes Windows support.

#### Which issue(s) this PR fixes:

Fixes #
Related: #96770

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/retest

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Review by chewong — COMMENTED** [review]
Manually verified this with some autoscaling test cases.
/lgtm
pull-kubernetes-e2e-aks-engine-windows-contianerd failure is due to httpd images.

**Pull request merged**
