### PR TITLE
correct coverage MainStart argument order

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/109697/files#r866309577

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
TestHSTS integration flake
/retest

**Comment by dims** [comment]
LOL, oopsy-daisy

/approve
/lgtm

**Comment by liggitt** [comment]
after https://github.com/kubernetes/kubernetes/pull/113956 and https://github.com/kubernetes/kubernetes/pull/113983 land, we can pick this to those release branches if we think it's useful (I'm not sure we're even using this coverage info on release branches)

**Comment by BenTheElder** [comment]
> (I'm not sure we're even using this coverage info on release branches)

We're not, we only run the coverage job on the main branch, and it was broken for some time.

Conceptually it's a good idea, go 1.20 will offer essentially this but built in as a go build option.

**Pull request merged**
