### PR TITLE
Update pods.md

### PR DESCRIPTION
**Pull request by mrphoebs**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@mrphoebs Thanks a lot for your contribution! However, even for such a small change you need to sign a CLA (our lawyers require it). Please sign the CLA (the instructions are above) and ping this thread again.

**Comment by erictune** [comment]
Also, I think that is supposed to say "pets" as in "pets vs cattle"
https://blog.engineyard.com/2014/pets-vs-cattle

**Comment by erictune** [comment]
Maybe a link to the pets vs cattle article would help, or more precise
words.

**Comment by mrphoebs** [comment]
Sorry for the delay, I've signed the form. pets makes sense in the context
of the engine yard article. The link would be helpful for context.

On Fri, May 1, 2015 at 4:13 AM, Eric Tune <notifications@github.com> wrote:

> Maybe a link to the pets vs cattle article would help, or more precise
> words.
>
>
> On Thu, Apr 30, 2015 at 3:41 PM, Eric Tune <etune@google.com> wrote:
>
> > Also, I think that is supposed to say "pets" as in "pets vs cattle"
> > https://blog.engineyard.com/2014/pets-vs-cattle
> >
> >
> > On Thu, Apr 30, 2015 at 5:22 AM, Wojciech Tyczynski <
> > notifications@github.com> wrote:
> >
> >> @mrphoebs <https://github.com/mrphoebs> Thanks a lot for your
> >> contribution! However, even for such a small change you need to sign a
> CLA
> >> (our lawyers require it). Please sign the CLA (the instructions are
> above)
> >> and ping this thread again.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/7558#issuecomment-97752890
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/7558#issuecomment-97991417>
> .
>



-- 
-Suman
http://www.sumankarthik.com

**Comment by erictune** [comment]
I fixed this via "Explain what pets are. #7624".  @mrphoebs thanks for letting us know where our docs are unclear.  future issues and PRs welcome!

**Pull request closed without merging**
