### PR TITLE
kubectl cp command supports coping remote file into local directory

### PR DESCRIPTION
**Pull request by bruceauyeung**
**What this PR does / why we need it**:
before this PR, `kubectl cp testpod:/tmp/testfile /home` will fail with error:
>error: open /home: is a directory

with this PR, `kubectl cp testpod:/tmp/testfile /home` will successfully copy remote `testfile` into directory `/home`

other minor improvements to make codes follow Go code conventions and more robust

**Release note**:

```
kubectl cp subcommand supports coping remote file into local directory now.
```
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>

### CODE REVIEW

**Comment by soltysh** [comment]
@bruceauyeung the change looks ok, do you think it's possible to have a test case for this?

**Comment by soltysh** [comment]
@k8s-bot ok te test

**Comment by bruceauyeung** [comment]
@soltysh test cases added, PTAL

**Comment by bruceauyeung** [comment]
@soltysh some tests failed , is there anything i can do ?

**Comment by soltysh** [comment]
@fabianofranz mind approving this one?

**Comment by fabianofranz** [comment]
@bruceauyeung need to `go vet`.

**Comment by bruceauyeung** [comment]
sorry for the delay ! I just am busy looking after my newborn boy recently.
rebased and vet error is fixed.
@fabianofranz @soltysh

**Comment by bruceauyeung** [comment]
hi @fabianofranz @soltysh, the vet error is already fixed.  would you mind take a look at this?

**Comment by bruceauyeung** [comment]
rebased and fixd a bug in untarAll function: if `io.Copy` fails, outFile will be left unclosed.

**Comment by fabianofranz** [comment]
/lgtm
/approve no-issue
@bruceauyeung thanks, sorry about the delay and congrats about your newborn!  ;)

**Pull request merged**
