### PR TITLE
cloudstack: change createLoadBalancerRule to create corresponding firewall rules

### PR DESCRIPTION
**Pull request by joschi36**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The current loadbalancer implementation in cloudstack doesn't create the corresponding firewall rules. So you would need to create the firewall rules manually in Cloudstack, which shouldn't be the case in my opinion.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Tested with Cloudstack 4.5 API

**Does this PR introduce a user-facing change?**:

```release-note
Cloud-Provider Cloudstack: By creating a service with type "Loadbalancer", corresponding firewall rules in Cloudstack will be created. 
```
/sig cloud-provider

### CODE REVIEW

**Review by resmo — APPROVED** [review]

**Review by resmo — APPROVED** [review]

**Comment by sebgoa** [comment]
@resmo note that the cloudstack provider is soon going to be removed from the core k8s repo. @joschi36 please get in touch with cloudstack folks to sort this out.

**Comment by onitake** [comment]
The same thing as for https://github.com/kubernetes/kubernetes/pull/71072#issuecomment-439085494 applies here.

**Comment by onitake** [comment]
For anyone interested: We've built a Cloudstack CCM based on the Kubernetes sources.
https://github.com/swisstxt/cloudstack-cloud-controller-manager

It includes the changes proposed by @joschi36 .

Contributions are welcome!

**Pull request closed without merging**
