### PR TITLE
Print conditions of RC/RS in 'kubectl describe' command

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
If conditions of RC/RS exist, print them in 'kubectl describe' command.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Print conditions of RC/RS in 'kubectl describe' command.
```

### CODE REVIEW

**Comment by soltysh** [comment]
/lgtm
@k8s-bot ok to test
@xiangpengzhao mind updating the release notes, this is changing kubectl output
@kubernetes/sig-cli-pr-reviews fyi

**Comment by xiangpengzhao** [comment]
@soltysh Thanks! Updated PR title as release note.

**Comment by smarterclayton** [comment]
Actually, the position is wrong.  We already display conditions below the pod template on deployments - these new additions should be consistent.  Please ensure that conditions for all controllers are consistently placed.

**Comment by smarterclayton** [comment]
Removing lgtm and approve.

**Comment by xiangpengzhao** [comment]
@smarterclayton Thanks Clayton for pointing that out! I will be OOO for several days. I will fix it ASAP when I'm back to office.

One more thing, I find that many objects in the current `describe.go` don't have consistent fields of their conditions be printed. e.g. 
pod:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\n")
```
node:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\tLastHeartbeatTime\tLastTransitionTime\tReason\tMessage\n")
```
deployment:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\tReason\n")
```

We should make them display consistent fields. Either printing all of the fields of each object, or printing same fields, e.g. `Type Status Reason Message`, might be okay.

We might also want to display conditions for other objects, whose conditions are not displayed yet.

I'll work on this after we decide which way we want to display conditions. But I hope someone can review and merge my former cleanup PR #43947 first, since it would be painful to rebase if I work on the two PRs at the same time.

**Comment by xiangpengzhao** [comment]
Addressed Clayton's comment. My above comment https://github.com/kubernetes/kubernetes/pull/44710#issuecomment-295814920 needs more discussion.

@smarterclayton PTAL

**Comment by soltysh** [comment]
> Addressed Clayton's comment. My above comment #44710 (comment) needs more discussion.

Open a separate issue to discuss this topic and ping sig-cli

/lgtm

**Pull request merged**
