### PR TITLE
Add docs on making a release

### PR DESCRIPTION
**Pull request by thockin**
Proposal for release process for this project-in-a-project

@vishh @ArtfulCoder @satnam6502

### CODE REVIEW

**Comment by vishh** [comment]
LGTM. Needs an entry for v1.5. I can send a separate PR for that.

**Comment by thockin** [comment]
Vish, you can add 1.5

**Comment by satnam6502** [comment]
Just to make sure I understand, is this what you are saying.
* I want to updated gcr.io elasticsearch from v3 to v4
* I make an image `kubernetes/elasticsearch:v4`
* I update the YAML files to use `kubernetes/elasticsearch:v4` rather than bumping the gcr.io image tag
* Then deploy and test.
* Then adjust the PR by reverting YAML to use gcr.io with new tag, but do not push.
* Send for review.
* When LGTM perform actual push.
?

**Comment by thockin** [comment]
On Mon, May 18, 2015 at 9:12 AM, Satnam Singh <notifications@github.com> wrote:
>
> Just to make sure I understand, is this what you are saying.
>
> I want to updated gcr.io elasticsearch from v3 to v4
> I make an image kubernetes/elasticsearch:v4
> I update the YAML files to use kubernetes/elasticsearch:v4 rather than bumping the gcr.io image tag
> Then deploy and test.

s/kubernetes/satnam6502/

> Then adjust the PR by reverting YAML to use gcr.io with new tag, but do not push.

You'll have to re-build (or re-tag) the container image, too.

> Send for review.
> When LGTM perform actual push. ?

I'm totally open to better plans - I just wrote down what I know how how to do.

**Comment by vishh** [comment]
For now, I don't intend to make a new kube2sky release for every PR since
it discourages me from making small PRs.
In general, we need to push an image to gcr.io before updating the
replication controller config.

**Comment by satnam6502** [comment]
Often I rebuild an image 10s of time (I think I did more than 40 pushes one day last week?) so as long as the process does not impede quick iteration then it is fine by me. This seems OK since we go from GCR.IO(v3) -> SATNAM6502(delat1) -> SATNAME6502(delta2) -> SATNAM6502(delta3) -> GCR.IO(v4) so that is still two edges.

**Comment by thockin** [comment]
Yeah, the main point is that we only push to gcr.io once we're pretty
confident it all works, and we don't commit to using a pushed image until
we've tested it again.

**Pull request merged**
