### PR TITLE
Fix invalid markdown format

### PR DESCRIPTION
**Pull request by YidaHu**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
This PR fixes the invalid markdown format. In table, format of description is broken due to `$` mark,  The invalid format confuses the markdown parser we use downstream for generating reference API docs. Better wrap them with backticks .
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
We don't define that these comments are Markdown format, and so I'm not convinced that this is the right fix.

Unless we define some doc comment convention to indicate that comments are actually Markdown, we should not put Markdown formatting into comments.

/hold
The code organization folks and / or SIG Architecture are welcome to confirm that Kubernetes code comments for API details are Markdown, and unhold - if so, though, we might want to add some lints!

**Comment by sftim** [comment]
Where should the fix go, instead? I'd say we should fix the API reference docs generator code.

**Comment by YidaHu** [comment]
> > We don't define that these comments are Markdown format, and so I'm not convinced that this is the right fix.
> > Unless we define some doc comment convention to indicate that comments are actually Markdown, we should not put Markdown formatting into comments.
> > /hold The code organization folks and / or SIG Architecture are welcome to confirm that Kubernetes code comments for API details are Markdown, and unhold - if so, though, we might want to add some lints!
> 
> I tend to agree... these comments are used both for godoc, for openapi, and for API doc generation from that openapi. Ideally we could come up with an approach that makes for readable content in all three spots. We control the openapi → api doc translation, so if there are readability issues specific to that, we should at least consider resolving them with a change in that translator.
> 
> > This PR fixes the invalid markdown format. In table, format of description is broken due to $ mark, The invalid format confuses the markdown parser we use downstream for generating reference API docs.
> 
> Is $ even a special character that requires escaping in markdown? I don't see it referenced in any of these places:
> 
> * https://www.markdownguide.org/basic-syntax/
> * https://www.markdownguide.org/extended-syntax/
> * https://daringfireball.net/projects/markdown/
1. Yes, if it can be solved by modifying the translator, it is indeed the best.

2. In table, The `$` mark is problematic.
At the same time, `"` is escaped as `\&quot;` and cannot be recognized by markdown, I think it should be `&quot;`.

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**value** | **str** | Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \&quot;$$(VAR_NAME)\&quot; will produce the string literal \&quot;$(VAR_NAME)\&quot;. Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \&quot;\&quot;. | [optional] 
**value_from** | [**V1EnvVarSource**](V1EnvVarSource.md) |  | [optional]

**Comment by YidaHu** [comment]
> Where should the fix go, instead? I'd say we should fix the API reference docs generator code.

Thanks, you're right, I see what you mean.

**Comment by sftim** [comment]
The API generator code is https://github.com/kubernetes-sigs/reference-docs/

**Pull request closed without merging**
