### PR TITLE
Rename test dir to allude sig-apps ownership

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/sig-apps-pr-reviews other sigs have already followed this pattern and it seems that this is what @kubernetes/sig-testing-misc wants too

Ref https://github.com/kubernetes/kubernetes/issues/49161

ptal

### CODE REVIEW

**Comment by spiffxp** [comment]
/test pull-kubernetes-verify
/lgtm

@kargakis can you link https://github.com/kubernetes/kubernetes/issues/49161 in your PR description?

**Comment by kargakis** [comment]
> @kargakis can you link #49161 in your PR description?

Done

**Comment by kargakis** [comment]
Seems like verify-golint is blocking this ..... ?

**Comment by kargakis** [comment]
Trivial rebase, reapplying lgtm

**Pull request merged**
