### PR TITLE
v1beta3 api json for grafana example

### PR DESCRIPTION
**Pull request by sub-mod**
@vishh Kindly review

### CODE REVIEW

**Comment by vishh** [comment]
Holding on to this PR while these changes get merged into main heapster repo which has automated testing.

**Comment by sub-mod** [comment]
@vishh is it ok to commit now ?

**Comment by vishh** [comment]
LGTM. Did you test the new configs?

**Comment by vishh** [comment]
@bgrant0607: We have e2e tests for many of the examples. Should we multiplex those tests to run with v1beta3 support?

**Comment by bgrant0607** [comment]
Adding the examples to the examples test would be useful.

How hard would it be to run v1beta3 in e2e?

We will certainly need to flip e2e over to v1beta3 once we expose it by default.

**Comment by vishh** [comment]
We need the e2e cluster to run a apiserver with v1beta3 turned on. As a short term hack, we can restart the apiserver with the appropriate flags once the e2e cluster is up. 
I am merging this PR as-is since e2e testing is beyond the scope of this PR.

**Pull request merged**
