### PR TITLE
apiextensions: add invalid validation schema regex test

### PR DESCRIPTION
**Pull request by sttts**
Prevents https://github.com/kubernetes/kubernetes/issues/65470, and is good for published OpenAPI schemas, not to publish invalid data.

```release-note
CustomResourceDefinition with invalid regular expression in the pattern field of OpenAPI v3 validation schemas are not considere structural.
```

### CODE REVIEW

**Comment by sttts** [comment]
/hold

Will use this to add a validation check.

**Comment by sttts** [comment]
We probably need ratcheting here.

/hold

**Comment by sttts** [comment]
@liggitt updated for structural schemas. Ptal.

**Comment by liggitt** [comment]
the validation test is no longer correct since the validation was limited to structural validation

**Comment by sttts** [comment]
/retest

CI is down.

**Pull request merged**
