### PR TITLE
Add new PodPresetTemplate type to settings API

### LINKED ISSUE #44971: settings API group should have a PodPresetTemplate type
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

---

In SIG service-catalog, we have plans for controllers to create `PodPreset` resources as part of their work.  Currently, there is no `PodPresetTemplateSpec` resource that would allow APIs to be constructed that express requirements for a pod preset spec to be created as well as `ObjectMeta` fields like labels and annotations.

Proposed type:

```go
type PodPresetTemplateSpec struct {
  metav1.ObjectMeta

  Spec PodPresetSpec
}
```

### PR DESCRIPTION
**Pull request by jpeeler**
Fixes #44971

### CODE REVIEW

**Review by pmorie — COMMENTED** [review]
Looks good, but where are the generated conversions, deep copies, etc.

**Comment by pmorie** [comment]
@k8s-bot ok to test

**Comment by dims** [comment]
@k8s-bot verify test this

**Comment by soltysh** [comment]
You need someone from @kubernetes/api-approvers to look into this one.

**Comment by pmorie** [comment]
We need to put this on hold for now.  The primary driver for this type is extensions to Kubernetes that will create PodPresets.  Currently, however, we do not know how those extensions (like service catalog) could validate API types from the core without attempting to create them.  I created https://github.com/kubernetes/kubernetes/issues/44995 to try to figure this out, but so far there has not been any movement.

**Pull request closed without merging**
