### PR TITLE
Fix scalability flakes in small clusters

### LINKED ISSUE #26185: [k8s.io] Density [Feature:Performance] should allow starting 30 pods per node {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/4982/

Failed: [k8s.io] Density [Feature:Performance] should allow starting 30 pods per node {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:150
There should be no high-latency requests
Expected
    <int>: 2
not to be >
    <int>: 0
```

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #26185

@xiang90 @hongchaodeng @gmarek

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@k8s-bot test this issue: #23545

**Comment by xiang90** [comment]
Thanks. LGTM

**Comment by xiang90** [comment]
BTW, from the gc log, we generated more than 300MB "garbage" during the test. @hongchaodeng and I will investigate why...

**Comment by wojtek-t** [comment]
@k8s-bot e2e node test this please, issue: #26431

**Comment by wojtek-t** [comment]
@k8s-bot e2e node test this please, issue: #26431

**Comment by wojtek-t** [comment]
@k8s-bot node e2e test this please, issue: #26431

**Comment by wojtek-t** [comment]
@k8s-bot node e2e test this please, issue: #26431

**Pull request merged**
