### PR TITLE
'synchoronizing' word error

### PR DESCRIPTION
**Pull request by StudyNick**
'synchoronizing' word error

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by StudyNick** [comment]
@MrHohn re-commit

**Comment by MrHohn** [comment]
/lgtm

@k8s-bot ok to test

**Comment by brendandburns** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by brendandburns** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot unit test this
@k8s-bot kops aws e2e test thi

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by rmmh** [comment]
@k8s-bot test this

**Comment by MrHohn** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
