### PR TITLE
Add proto file for gRPC pod-status service

### PR DESCRIPTION
**Pull request by kl52752**
Change-Id: I68cf94fccc7a032716368a7bacf4e82625e5245a

#### What type of PR is this?
/kind feature
/kind api-change

#### What this PR does / why we need it:
This PR adds gRPC server implementation for podstatus kubelet API for [KEP] (https://github.com/kubernetes/enhancements/pull/4184)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
One tip, check the failing jobs and clock on the errors, in this case you can see in one of them
```
go version go1.21.1 linux/amd64
Your vendored results are different:
diff -Naupr -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/kubelet/go.mod /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.f2Gdn3/kubernetes/vendor/k8s.io/kubelet/go.mod
--- vendor/k8s.io/kubelet/go.mod	2023-10-06 13:43:01.607907458 +0000
+++ /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.f2Gdn3/kubernetes/vendor/k8s.io/kubelet/go.mod	2023-10-06 13:46:50.894697461 +0000
@@ -9,6 +9,7 @@ require (
 	github.com/gogo/protobuf v1.3.2
 	github.com/stretchr/testify v1.8.2
 	google.golang.org/grpc v1.54.0
+	google.golang.org/protobuf v1.31.0
 	k8s.io/api v0.0.0
 	k8s.io/apimachinery v0.0.0
 	k8s.io/apiserver v0.0.0
@@ -50,7 +51,6 @@ require (
 	golang.org/x/time v0.3.0 // indirect
 	google.golang.org/appengine v1.6.7 // indirect
 	google.golang.org/genproto/googleapis/rpc v0.0.0-20230525234030-28d5490b6b19 // indirect
-	google.golang.org/protobuf v1.31.0 // indirect
 	gopkg.in/inf.v0 v0.9.1 // indirect
 	gopkg.in/yaml.v2 v2.4.0 // indirect
 	gopkg.in/yaml.v3 v3.0.1 // indirect
Vendor Verify failed.
If you're seeing this locally, run the below command to fix your directories:
hack/update-vendor.sh
go version go1.21.1 linux/amd64
All pinned versions of checked dependencies match their preferred version.
```

so run `hack/update-vendor.sh` to update the dependencies correctly

**Comment by aojea** [comment]
It needs also the implementation bits and tests

**Comment by dims** [comment]
please reopen if needed.

**Pull request closed without merging**
