### PR TITLE
bump CSI version to 1.2.0

### PR DESCRIPTION
**Pull request by gnufied**
This bumps bundled CSI version to 1.2.0, so as latest changes for expansion and volume listing can be pulled in.

/sig storage
/kind feature
/priority important-soon

```release-note
Bump CSI version to 1.2.0
```

### CODE REVIEW

**Comment by gnufied** [comment]
cc @saad-ali

**Review by saad-ali — APPROVED** [review]
/approve
/lgtm
/milestone v1.17

**Pull request merged**
