### PR TITLE
Move test cases to a proper test method

### PR DESCRIPTION
**Pull request by php-coder**
**What this PR does / why we need it**:
Prior this change, we had tests in `TestValidatePodSpec()` method that is designated for testing `ValidatePodSpec()`. But because we test code from the `ValidateSecurityContext()` method, the tests should belong to `TestValidateSecurityContext()`.

This PR improves the tests. Now the tests become less fragile because `ValidatePodSpec()` do a lot more validations than `ValidateSecurityContext()`.

**Which issue(s) this PR fixes**:
Related to https://github.com/kubernetes/kubernetes/pull/52803 where this code and tests were introduced.

**Release note**:
```release-note
NONE
```

PTAL @jessfraz 
CC @simo5

### CODE REVIEW

**Comment by php-coder** [comment]
PTAL @tallclair

**Comment by php-coder** [comment]
Checks has failed because of "pull access denied for gcr.io/google_containers/kube-cross, repository does not exist or may require 'docker login'" error.

/retest

**Comment by php-coder** [comment]
/assign @liggitt 

PTAL.

**Comment by liggitt** [comment]
looks good, but squash before merge

**Comment by php-coder** [comment]
@liggitt Squashed. PTAL.

**Pull request merged**
