### PR TITLE
Updating google.golang.org/api (to version v0.45.0)

### PR DESCRIPTION
**Pull request by basantsa1989**
Updating to latest google.golang.org/api (version v0.45.0)

/kind design
/kind api-change

Commands run:

##Commit ID points to the commit that updates the API to version v0.45.0
hack/pin-dependency.sh github.com/GoogleCloudPlatform/k8s-cloud-provider 2e28a39f7bad9f4e3b88ac701235761d4b80d4b0
hack/update-vendor.sh

##Commit ID points to the commit tagging the v0.45.0 release
hack/pin-dependency.sh google.golang.org/api de9f25cba16a59e6a62c6b97478882f5392143f5
hack/update-vendor.sh
hack/verify-vendor.sh

### CODE REVIEW

**Comment by dims** [comment]
@basantsa1989 need help doing this?

**Comment by basantsa1989** [comment]
> @basantsa1989 need help doing this?

@dims thanks a lot for offering to help!
My goal here is to update google.golang.org/api version. While updating the transitive dependencies, I had to update grpc version and that led to this error:

``` warning: ignoring symlink /usr/local/google/home/basantsa/go/src/k8s.io/kubernetes/cluster/gce/custom
warning: ignoring symlink /usr/local/google/home/basantsa/go/src/k8s.io/kubernetes/cluster/gce/ubuntu
go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
go: finding module for package google.golang.org/grpc/naming
go: downloading google.golang.org/grpc/examples v0.0.0-20210526223527-2de42fcbbce3
go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20210526223527-2de42fcbbce3
warning: ignoring symlink /usr/local/google/home/basantsa/go/src/k8s.io/kubernetes/cluster/gce/cos
warning: ignoring symlink /usr/local/google/home/basantsa/go/src/k8s.io/kubernetes/cluster/gce/custom
warning: ignoring symlink /usr/local/google/home/basantsa/go/src/k8s.io/kubernetes/cluster/gce/ubuntu
go: finding module for package google.golang.org/grpc/naming
k8s.io/kubernetes/pkg/registry/registrytest imports
        k8s.io/apiserver/pkg/storage/etcd3/testing imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.38.0, replaced by google.golang.org/grpc@v1.37.0), but does not contain package google.golang.org/grpc/naming```

Looks like I have to wait till etcd, grpc dependencies are fixed. This seems to be a known issue: https://github.com/etcd-io/etcd/issues/12124

I need to wait for this PR to get in: https://github.com/kubernetes/kubernetes/pull/100488

Please let me know if I am missing anything.

**Comment by liggitt** [comment]
grpc update is merged, this should be able to be rebased now

**Comment by basantsa1989** [comment]
> grpc update is merged, this should be able to be rebased now

Thanks @liggitt ! 
There were too many changes. Closed this and opened a new PR: https://github.com/kubernetes/kubernetes/pull/102926

**Pull request closed without merging**
