### PR TITLE
Automated cherry pick of #76749: Avoid using tag filters for EC2 API where possible

### PR DESCRIPTION
**Pull request by mcrute**
Cherry pick of #76749 on release-1.14.

#76749: Avoid using tag filters for EC2 API where possible

/kind bug
/sig aws cloud-provider
/priority critical-urgent
/assign @micahhausler

### CODE REVIEW

**Comment by mcrute** [comment]
ping @zhan849

**Comment by tpepper** [comment]
Given the length of inactivity here, can @kubernetes/sig-cloud-provider-bugs either close or lgtm/approve this.

**Comment by hogepodge** [comment]
To my eye this looks fine, especially as a cherry pick, but I'd like to get one set of eyes from /area provider/aws

**Comment by jaypipes** [comment]
/assign tpepper

Hi Tim, team has signed off on this. Can you approve the cherry-pick, please? thanks! :)

**Pull request merged**
