### PR TITLE
Implement dummy device operation by netlink for ipvs proxier

### LINKED ISSUE #54054: {ip link add dev} returns 2 does not mean an device exists
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Currently, we implement network interface operations, e.g. create a dummy device and delete a dummy interface via ip cmd and then collect the exist code. For example, we assume command `ip link add kube-ipvs0 type dummy` returns 2 means the dummy device `kube-ipvs0` exists, see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1529 .

However, from the man page of ip command, it says exit status 2 just means an error was reported by the kernel, see http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS.

So, that's a bug.

**What you expected to happen**:

Find a way to exactly know if an network interface exists or not. The netlink package can be a dedicated way.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Currently, we implement network interface operations, e.g. create a dummy device and delete a dummy interface via ip cmd and then collect the exist code. For example, we assume the following command:
```
ip link add kube-ipvs0 type dummy 
```
returns 2 means the dummy device `kube-ipvs0` exists, see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1529 .

However, from the man page of ip command, exit status 2 just means an error was reported by the kernel, see http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS.

So, that's a bug.

This PR implements dummy device operation by netlink for ipvs proxier so that can get ride of ip command operations.

**Which issue this PR fixes**: 

fixes #54054

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/sig network
/area kube-proxy
/kind bug

### CODE REVIEW

**Comment by m1093782566** [comment]
ping for review~

**Comment by m1093782566** [comment]
@kubernetes/sig-network-bugs @kubernetes/sig-network-pr-reviews

**Comment by cmluciano** [comment]
This looks correct to me, but it would be great to have a unit test for the new logic

**Comment by m1093782566** [comment]
@cmluciano Glad to receive your feedback.

I have tried to created some UTs for it and found that the UTs require root privilege to operate network devices. Unfortunately, the Unit Test runs in upstream CI can NOT acquire root privilege.

**Pull request merged**
