### PR TITLE
Add missing trace dependency to kubemark

### PR DESCRIPTION
**Pull request by mborsz**
#### What type of PR is this?
/kind bug
#### What this PR does / why we need it:
The PR adds missing dependency to the kubemark that has been introduced in https://github.com/kubernetes/kubernetes/pull/114504 and lack of it causes all kubemark tests to fail with 

```
W0314 14:14:24.216591      11 http2_server.go:637] [transport] transport: http2Server.HandleStreams failed to read frame: read unix /tmp/3255691351->@: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3274003]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubelet.NewMainKubelet(0xc0006f6f38, _, _, {_, _}, _, {_, _}, {0x0, 0x0, ...}, ...)
        pkg/kubelet/kubelet.go:518 +0x1263
k8s.io/kubernetes/cmd/kubelet/app.createAndInitKubelet(0x0?, 0x0?, {0x7ffe4984abe6?, 0x0?}, 0x0?, {0x7ffe4984abe6?, 0x0?}, {0x0, 0x0, 0x0})
        cmd/kubelet/app/server.go:1213 +0x3bc
k8s.io/kubernetes/cmd/kubelet/app.RunKubelet(0xc0006f6e00, 0xc0005e0000, 0x0)
        cmd/kubelet/app/server.go:1154 +0x4eb
k8s.io/kubernetes/pkg/kubemark.(*HollowKubelet).Run(0xc0007721f8)
        pkg/kubemark/hollow_kubelet.go:125 +0xa5
main.run(0x0?, 0xc000ab41a0)
        cmd/kubemark/hollow-node.go:272 +0x1271
main.newHollowNodeCommand.func1(0xc000005200?, {0xc00064afc0?, 0x6?, 0x6?})
```

Given that this issue happens again (prev https://github.com/kubernetes/kubernetes/pull/113887) it also adds a naive unit test that checks if kubelet isn't crashing in the 3s first seconds of life. It is sufficient to detect this issue (tested by removing TracerProvider dependency).

#### Special notes for your reviewer:

Also did tiny refactoring (moved all the code from cmd/ to app/) to make it more unit testable and follow pattern used e.g. by kubelet.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks for fixing this!

This is fixing failiing kubemark tests - @kubernetes/release-managers - FYI

/milestone v1.27

**Comment by xmudrii** [comment]
FYI @kubernetes/release-team-leads ^^

**Comment by pacoxu** [comment]
/close

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce
is green.

**Pull request merged**
