### PR TITLE
Pass the mandatory parameters to build arm64 binaries

### PR DESCRIPTION
**Pull request by chendave**
The parameters are needed to build the test binaries, e.g. `e2e_node.test` `ginkgo` etc.

ref:
https://github.com/kubernetes-sigs/kubetest2/pull/229
https://github.com/kubernetes/test-infra/pull/29727

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
 CI job `ci-kubernetes-node-arm64-ubuntu-serial` will test node e2e on arm64, `use-dockerized-build` and `target-build-arch` are required to run this job.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig node
/sig testing

/cc @ike-ma 
/cc @dims 
/cc @pacoxu

### CODE REVIEW

**Comment by chendave** [comment]
The job ci-kubernetes-node-arm64-ubuntu-serial is failing because the binaries, such as "ginkgo" are copied from the wrong location and was build for `linux/amd64` instead.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-arm64-ubuntu-serial/1666321790525247488/build-log.txt


/hold

need the change in the kubetest2 get in first.

**Comment by pacoxu** [comment]
Link to https://github.com/kubernetes/kubernetes/blob/9f7e43915766607b7ff281b91caf17cca7123576/test/e2e_node/builder/build.go#L32-L34 for reviewing.

**Comment by chendave** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/229 is now merged.

/hold cancel

**Comment by chendave** [comment]
/assign @dims @pacoxu 

for review and approval, thanks!

**Review by pacoxu — APPROVED** [review]
/lgtm

**Pull request merged**
