### PR TITLE
Update and improve ConfigMap resource lifecycle test

### LINKED ISSUE #90921: Write CoreV1ConfigMap test - +2 endpoint Coverage
# Progress `[6/7]`
* [x] Original approval issue: #87120
* [x]  Test approval issue: [kubernetes/kubernetes#90921](https://github.com/kubernetes/kubernetes/issues/90921)
* [x]  Test pr: [PR](https://github.com/kubernetes/kubernetes/pull/87212)
* [x]  Two weeks soak start date: 24 April 2020 [testgrid-link](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=should%20run%20through%20a%20ConfigMap%20lifecycle)
* [x]  Two weeks soak end date: 8 May 2020
* [ ]  Promote pr: [With Watch tool](https://github.com/kubernetes/kubernetes/pull/90941) 
* * [x]  [update to improve](https://github.com/kubernetes/kubernetes/pull/90944)
* [x]  Two weeks soak start date: 8 June 2020 [testgrid-link](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=should%20run%20through%20a%20ConfigMap%20lifecycle)
* [x]  Two weeks soak end date: 23 June 2020
This issue is created to allow edit by @Riaankl

/wip
/hold

# Notes
This issue proposes the writing of a new test for the API endpoints `listCoreV1ConfigMapForAllNamespaces`, `listCoreV1ConfigMapForAllNamespaces` with the intention of promoting it to Conformance. This issue contains a **very basic mock test** in order to start the conversation about what a good e2e test would look like for this endpoint. The code below is verified to be hitting the intended endpoint, show as per the queries in APIsnoop's live view of the cluster's audit logs.

## Deploy APISnoop
```shell
kubectl apply -f ~/cncf/apisnoop/deployment/k8s/raiinbow.yaml
```

# Identify an untested feature Using APISnoop
According to this APIsnoop query, there are still some remaining ConfigMap endpoints which are untested.

```
SELECT
  operation_id,
  -- k8s_action,
  -- path,
  description
  FROM untested_stable_core_endpoints
  where path not like '%volume%'
  and operation_id ilike '%ConfigMap%'
 ORDER BY operation_id desc
 LIMIT 150
       ;
```

```
               operation_id                |               description               
-------------------------------------------|-----------------------------------------
 listCoreV1ConfigMapForAllNamespaces       | list or watch objects of kind ConfigMap
 deleteCoreV1CollectionNamespacedConfigMap | delete collection of ConfigMap
(2 rows)
```

# Use API Reference to Lightly Document the Feature
* [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/kubernetes-api/)
* [client-go - ConfigMap](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/configmap.go)

# The mock test
## Test outline
1. Create a ConfigMap with a static label
2. Patch the ConfigMap with a new Label and updated data
3. Get the ConfigMap to ensure it's patched
4. List all ConfigMaps in all Namespaces find the ConfigMap(1) ensure that the ConfigMap is found and is patched
5. Delete Namespaced ConfigMap(1) via a Collection with a LabelSelector

## Example in Go
```shell
go get -v -u k8s.io/apimachinery/pkg/apis/meta/v1
go get -v -u k8s.io/client-go/kubernetes
go get -v -u k8s.io/client-go/tools/clientcmd
```

This mock test uses client-go's standard functions for talking to the Event area of the API.

```go
package main

import (
  "fmt"
  "flag"
  "os"
  "encoding/json"
  v1 "k8s.io/api/core/v1"
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  "k8s.io/client-go/kubernetes"
  "k8s.io/apimachinery/pkg/types"
  "k8s.io/client-go/tools/clientcmd"
)

func main() {
  // uses the current context in kubeconfig
  kubeconfig := flag.String("kubeconfig", fmt.Sprintf("%v/%v/%v", os.Getenv("HOME"), ".kube", "config"), "(optional) absolute path to the kubeconfig file")
  flag.Parse()
  config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
  if err != nil {
    fmt.Println(err)
  }
  // make our work easier to find in the audit_event queries
  config.UserAgent = "live-test-writing"
  // creates the clientset
  ClientSet, _ := kubernetes.NewForConfig(config)

  testNamespaceName := "default"
  testConfigMapName := "test-configmap"

  _, err = ClientSet.CoreV1().ConfigMaps(testNamespaceName).Create(&v1.ConfigMap{
    ObjectMeta: metav1.ObjectMeta{
      Name: testConfigMapName,
      Labels: map[string]string{
        "test-configmap-static": "true",
      },
    },
    Data: map[string]string{
      "valueName": "value",
    },
  })
  if err != nil {
    fmt.Println(err)
    return
  }
  fmt.Println("[status] created ConfigMap")

  configMapPatchPayload, err := json.Marshal(v1.ConfigMap{
    ObjectMeta: metav1.ObjectMeta{
      Labels: map[string]string{
        "test-configmap": "patched",
      },
    },
    Data: map[string]string{
      "valueName": "value1",
    },
  })
  if err != nil {
    fmt.Println(err)
    return
  }
  _, err = ClientSet.CoreV1().ConfigMaps(testNamespaceName).Patch(testConfigMapName, types.StrategicMergePatchType, []byte(configMapPatchPayload))
  if err != nil {
    fmt.Println(err)
    return
  }
  fmt.Println("[status] patched ConfigMap")

  configMap, err := ClientSet.CoreV1().ConfigMaps(testNamespaceName).Get(testConfigMapName, metav1.GetOptions{})
  if err != nil {
    fmt.Println(err)
    return
  }
  if configMap.Data["valueName"] != "value1" || configMap.Labels["test-configmap"] != "patched" {
    fmt.Println("[error] failed to patch ConfigMap")
    return
  }
  fmt.Println("[status] ConfigMap was patched successully")

  // listing in all namespaces to hit the endpoint
  configMapList, err := ClientSet.CoreV1().ConfigMaps("").List(metav1.ListOptions{
    LabelSelector: "test-configmap-static=true",
  })
  if err != nil {
    fmt.Println(err)
    return
  }
  if len(configMapList.Items) == 0 {
    fmt.Println("[error] no ConfigMaps found")
    return
  }
  testConfigMapFound := false
  for _, cm := range configMapList.Items {
    if cm.ObjectMeta.Name == testConfigMapName &&
       cm.ObjectMeta.Namespace == testNamespaceName &&
       cm.ObjectMeta.Labels["test-configmap-static"] == "true" &&
       cm.Data["valueName"] == "value1" {
      testConfigMapFound = true
      break
    }
  }
  if testConfigMapFound == false {
    fmt.Println("[error] unable to find ConfigMap in list")
    return
  }
  fmt.Println("[status] found updated ConfigMap")

  err = ClientSet.CoreV1().ConfigMaps(testNamespaceName).DeleteCollection(&metav1.DeleteOptions{}, metav1.ListOptions{
    LabelSelector: "test-configmap-static=true",
  })
  if err != nil {
    fmt.Println(err)
    return
  }
  fmt.Println("[status] deleted ConfigMap")

  fmt.Println("[status] complete")

}
```

# Verify with APISnoop
Discover useragents:

```
select distinct useragent from audit_event where bucket='apisnoop' and useragent not like 'kube%' and useragent not like 'coredns%' and useragent not like 'kindnetd%' and useragent like 'live%';
```

```
     useragent     
-------------------
 live-test-writing
(1 row)
```

Display endpoints hit by the test:

```
select * from endpoints_hit_by_new_test where useragent like 'live%'; 
```

```
     useragent     |               operation_id                | hit_by_ete | hit_by_new_test 
-------------------|-------------------------------------------|------------|-----------------
 live-test-writing | createCoreV1NamespacedConfigMap           |        288 |               2
 live-test-writing | deleteCoreV1CollectionNamespacedConfigMap |          0 |               2
 live-test-writing | listCoreV1ConfigMapForAllNamespaces       |          0 |               1
 live-test-writing | patchCoreV1NamespacedConfigMap            |          2 |               2
 live-test-writing | readCoreV1NamespacedConfigMap             |         23 |               1
(5 rows)
```

Show the change in coverage after the mock test:

```
select * from projected_change_in_coverage;
```

```
   category    | total_endpoints | old_coverage | new_coverage | change_in_number 
---------------|-----------------|--------------|--------------|------------------
 test_coverage |             438 |          183 |          185 |                2
(1 row)
```

# Final notes
If a test with these calls gets merged, ****Conformance coverage will go up by 2 points****

### LINKED ISSUE #90957: Watch event test verification tooling
* [Ticket status](#sec-1)
* [Current problem](#sec-2)
* [Proposed solution](#sec-3)

This Issue replace #90574

# Ticket status
* [ ]  [K8s watch events test tooling #323](https://github.com/cncf/apisnoop/pull/323)
* [ ]  [Watch event test verification tooling #90574](https://github.com/kubernetes/kubernetes/issues/90574)
* [X] [PR #91416 ](https://github.com/kubernetes/kubernetes/pull/91416)
# Current problem
Watch events may be missed and the test may still pass. We need to ensure that all expected watch events are seen.

Watch events are not collected and checked at the end of the test.

# Proposed solution
In order to solve the problem, we must collect all watch events as they come in and perform a check at the end of the test to ensure that the order is correct and they contain no errors.

```go
package main

import (
  "fmt"
)

func main() {
  expectedWatchEventsAll := [][]string{
    {
      "ADDED",
      "ADDED",
      "DELETED",
    },
    {
      "ADDED",
      "MODIFIED",
      "MODIFIED",
      "DELETED",
    },
    {
      "ADDED",
      "MODIFIED",
      "DELETED",
    },
  }
  for expectedExampleInt, expectedWatchEvents := range expectedWatchEventsAll {
	  fmt.Println("Running example", expectedExampleInt)
    allowedAttempts := 3
    failure := VerifyWatchEventOrder(allowedAttempts, expectedWatchEvents, func() []string {
      var myWatchEvent string
      var watchEvent []string
      fmt.Println("An event takes place (1/3)")
      myWatchEvent = "ADDED"
      watchEvent = append(watchEvent, myWatchEvent)

      fmt.Println("An event takes place (2/3)")
      myWatchEvent = "MODIFIED"
      watchEvent = append(watchEvent, myWatchEvent)

      fmt.Println("An event takes place (3/3)")
      myWatchEvent = "DELETED"
      watchEvent = append(watchEvent, myWatchEvent)

      return watchEvent
    })
    if failure != "" {
      fmt.Println(failure, "watch events occured in the wrong or incorrect order")
    }
    fmt.Println("Check complete")
  }
}

func VerifyWatchEventOrder(retries int, expectedWatchEvents []string, scenario func() []string) (failure string) {
  var attemptContainsFailure bool
attempts:
  for try := 1; try <= retries; try++ {
    if try == retries {
      return failure
    }
    actualWatchEvents := scenario()
    if len(expectedWatchEvents) != len(actualWatchEvents) {
      failure = "expected watch events count does not match the count of actual watch events"
      attemptContainsFailure = true
      continue
    }
    for watchEventInt, watchEvent := range actualWatchEvents {
      if expectedWatchEvents[watchEventInt] != watchEvent {
        failure = fmt.Sprintf("(index %v) %v not found, found %v instead. %v/%v attempts", watchEventInt, expectedWatchEvents[watchEventInt], watchEvent, try, retries)
        attemptContainsFailure = true
      }
    }
    if attemptContainsFailure == false {
      failure = ""
      break attempts
    }
  }
  return failure
}
```

```
Running example 0
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
(index 1) ADDED not found, found MODIFIED instead. 2/3 attempts watch events occured in the wrong or incorrect order
Check complete
Running example 1
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
expected watch events count does not match the count of actual watch events watch events occured in the wrong or incorrect order
Check complete
Running example 2
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
Check complete
```

### PR DESCRIPTION
**Pull request by riaankleinhans**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Adds more checks throughout the test:

* created
* modified
* deleted

**Which issue(s) this PR fixes**:
Fixes #90921
Resolves #90957 

[#88034 (comment)](https://github.com/kubernetes/kubernetes/pull/88034#discussion_r384103741)
(https://github.com/kubernetes/kubernetes/pull/88034#issuecomment-626251014)

**Special notes for your reviewer**:
Should fix flakiness

**Does this PR introduce a user-facing change?**:

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```
NONE
```

/sig testing

### CODE REVIEW

**Comment by Riaankl** [comment]
https://github.com/kubernetes/kubernetes/pull/89707#issuecomment-624890751

**Comment by BobyMCbobs** [comment]
This PR has been updated to use and now depends on the merging of the new [watch tooling](https://github.com/kubernetes/kubernetes/pull/91416)

**Comment by spiffxp** [comment]
/release-note-none

/approve
/lgtm
to get us some signal, I'm still not convinced this is the right way to go, will summarize in another comment

**Pull request merged**
