### PR TITLE
 Upgrade Azure network API version to 2018-07-01

### LINKED ISSUE #78011: LoadBalancer Service stuck on pending when EnableTcpReset is enabled on SLB
**What happened**:

LoadBalancer Service stuck on pending when EnableTcpReset is enabled on SLB:

```sh
 kubectl describe service nginx
Name:                     nginx
Namespace:                default
Labels:                   run=nginx
Annotations:              <none>
Selector:                 run=nginx
Type:                     LoadBalancer
IP:                       10.0.25.177
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32269/TCP
Endpoints:                10.244.0.27:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                  From                  Message
  ----     ------                      ----                 ----                  -------
  Warning  CreatingLoadBalancerFailed  3m13s (x6 over 13m)  service-controller    Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx: timed out waiting for the condition
  Normal   EnsuringLoadBalancer        33s (x7 over 15m)    service-controller    Ensuring load balancer
  Warning  CreateOrUpdateLoadBalancer  1s (x40 over 15m)    azure-cloud-provider  Code="EnableTcpResetCannotBeSpecifiedForApiVersion" Message="Specified api-version 2017-09-01 does not meet the minimum required api-version 2018-07-01 for EnableTcpReset property." Details=[]
````

This is because the Azure network API version 2017-09-0 is too old. To fix it, the API verison should be upgraded to at least 2018-07-01.

**What you expected to happen**:

Azure cloud provider should set the LB rules successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The fix should be cherry picked to old stable versions. However, release-1.12 is using Azure SDK v19.2.0, which doesn't include network API version 2018-07-01. So cloud probably only cherry pick the fix to 1.13 and 1.14 branch.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig azure
/kind bug
/priority critical-urgent

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

LoadBalancer Service stuck on pending when EnableTcpReset is enabled on SLB. This is because the Azure network API version 2017-09-0 is too old. 

This PR fixes the issue by upgrading the network API version to 2018-07-01.

**Which issue(s) this PR fixes**:

Fixes #78011

**Special notes for your reviewer**:

Should cherry pick to 1.13 and 1.14.

**Does this PR introduce a user-facing change?**:

```release-note
 Upgrade Azure network API version to 2018-07-01, so that EnableTcpReset could be enabled on Azure standard loadbalancer (SLB).
```

/sig azure
/kind bug
/priority critical-urgent
/milestone v1.15

### CODE REVIEW

**Review by justaugustus — CHANGES_REQUESTED** [review]
@feiskyer -- Any reason to not bump this to an even more recent network API version:
- 2019-02-01
- 2018-12-01
- 2018-11-01
- 2018-10-01
- 2018-08-01

**Comment by feiskyer** [comment]
@justaugustus for more recent versions, we should also upgrade Azure Go SDK versions. Then, a lot of new dependencies would be introduced, and make it hard for cherry picking.

So the PR only upgrades the API version, and keep the Azure Go SDK version still same.

**Comment by justaugustus** [comment]
@feiskyer -- totally understand, but I think smaller cherry picks is not a "good enough" reason. I'm worried that that will put us in the same position of letting a very old API version linger around for a long time again.

Are there specific cherry picks that you have in mind?

**Comment by feiskyer** [comment]
@justaugustus Actually, another reason is too much dependencies conflicts happened when upgrading Azure Go SDK. See https://github.com/kubernetes/kubernetes/pull/76656 for more context on the confliction issues.

**Comment by justaugustus** [comment]
Ahhh, I just read it. We should come up with a plan to get up to date incrementally and get it documented.
Let's chat after KubeCon.

**Comment by feiskyer** [comment]
pull-kubernetes-e2e-aks-engine-azure is failing consistently. The cluster couldn't be setup. opened #78013 for tracking the failing tests.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
/assign @dims

@dims Could you help to approve the go modules updates?

**Comment by dims** [comment]
@feiskyer should the `pull-kubernetes-e2e-aks-engine-azure` succeed before we merge this?

/approve
/hold

Hold for the CI job above to go green

**Comment by feiskyer** [comment]
> @feiskyer should the pull-kubernetes-e2e-aks-engine-azure succeed before we merge this?

there's a known issue in aks-engine caused by #76953, and the fix for testing failure would be in different repos (aks-engine and test-infra). So it's ok to skip this job.

**Comment by justaugustus** [comment]
Based on @feiskyer's comment, I'm going to lift the hold on this.
/hold cancel

**Pull request merged**
