### PR TITLE
Fix an error in comment

### PR DESCRIPTION
**Pull request by houjun41544**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm

**Comment by houjun41544** [comment]
@nikhita Would you please help to approve this?

**Comment by houjun41544** [comment]
@yujuhong Would you please help to approve this?

**Pull request merged**
