### PR TITLE
Adding UDP network policies tests

### PR DESCRIPTION
**Pull request by knabben**
**What type of PR is this?**
/kind feature
/sig network
/area testing

**What this PR does / why we need it**:
Adding initial UDP coverage for network policy suite test

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/kubernetes/issues/97640

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by knabben** [comment]
```
Jan 31 17:28:12.706: INFO: Validation of udp-network-policy-6455-z/c -> udp-network-policy-6455-x/a FAILED !!!
Jan 31 17:28:12.706: INFO: error <nil> 
Jan 31 17:28:12.706: INFO: Expected blocked pod connection was instead ALLOWED --- run 'kubectl exec c -c cont-81-udp -n udp-network-policy-6455-z -- nc -v -z -w 1 -u s-udp-network-policy-6455-x-a.udp-network-policy-6455-x.svc.cluster.local 81'
```

netcat (`OpenBSD netcat (Debian patchlevel 1.130)`) is exiting with status 0, even when the connection is not really made on UDP.

Not existent port UDP 1404 test with a manual test from the agnhost container:

```
bash-5.0# nc -v -w 1 -u s-udp-network-policy-529-x-a.udp-network-policy-529-x.svc.cluster.local 1404
Connection to s-udp-network-policy-529-x-a.udp-network-policy-529-x.svc.cluster.local 1404 port [udp/*] succeeded!
bash-5.0# echo $?
0
```

**Comment by knabben** [comment]
Swapping the nc to agnhost connect with UDP after https://github.com/kubernetes/kubernetes/pull/98639 arrives.

**Comment by jayunit100** [comment]
YAYYYyyy UDP netpol tests  THANK YOU ~!
/lgtm
/approve

**Pull request merged**
