### PR TITLE
Remove wrong comment

### PR DESCRIPTION
**Pull request by july2993**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
It does not assume proxier.mu is held because it locks it at the first line.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by uablrek** [comment]
Thanks.

/lgtm

**Comment by pacoxu** [comment]
the unit is flake for #104730

**Pull request merged**
