### PR TITLE
Update the e2e-gce timeout to 3 hours, we've bumped up against it recently

### PR DESCRIPTION
**Pull request by brendandburns**
Mean runtime is 2:10, that's a little close for comfort.

@spxtr @ixdy @ihmccreery

### CODE REVIEW

**Comment by ixdy** [comment]
That regression worries me a little bit. It seems we've gotten about 15-20m worse in the last few days?

I think we're also running more tests due to #19425 (e.g. all of the reboot tests); unclear if that was intentional or not.

**Comment by ixdy** [comment]
Also, it appears that most builds are finishing in under 2hr, most well under. I don't think this increase is needed?

**Comment by ihmccreery** [comment]
Once #20230 is resolved and #19667 is in, we'll move to running most tests in parallel by default, which will dramatically speed this up: `-gce` should take ~30 minutes, and the serial tests will take ~90.

**Comment by brendandburns** [comment]
@ixdy I see MTTR @ 2:34
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/

And we had a build time out recently:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10548/

**Comment by ixdy** [comment]
@brendandburns that's coming from the [Build History Metrics Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Build+History+Metrics+Plugin) and is reporting mean time to recovery. I'm not sure it's actually really a useful stat at all.

The timeout you linked is really strange:
```
00:19:52 ++ gsutil -mq cp gs://kubernetes-release/ci/v1.2.0-alpha.6.627+3f5e4179999dd6/kubernetes.tar.gz gs://kubernetes-release/ci/v1.2.0-alpha.6.627+3f5e4179999dd6/kubernetes-test.tar.gz .
00:27:17 ++ [[ ! -z '' ]]
00:27:17 ++ [[ ! '' == \t\r\u\e ]]
00:27:17 ++ [[ gce == \a\w\s ]]
00:27:17 ++ mkdir -p /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.ssh/
00:27:17 ++ cp /var/lib/jenkins/gce_keys/google_compute_engine /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.ssh/
00:27:17 ++ cp /var/lib/jenkins/gce_keys/google_compute_engine.pub /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.ssh/
00:27:17 ++ md5sum kubernetes.tar.gz kubernetes-test.tar.gz
00:27:18 e3bbc5c21c1bebb7ef1e24f658546631  kubernetes.tar.gz
00:27:19 00d1bbb9df38552b44d9aad7702961d0  kubernetes-test.tar.gz
00:27:19 ++ tar -xzf kubernetes.tar.gz
00:35:16 ++ tar -xzf kubernetes-test.tar.gz
01:18:23 ++ cd kubernetes
```

Somehow we spent ~an hour to download and extract the kubernetes tarball. That doesn't seem normal. I'd rather timeout in these cases (since something is obviously wrong) rather than silently let them through.

**Pull request closed without merging**
