### PR TITLE
PodFitsResources() checks not only CPU and Memory but also including GPU

### PR DESCRIPTION
**Pull request by lixiaobing1**
In file "docs\devel\scheduler_algorithm.md", line 45:
"- `PodFitsResources`: Check if the free resource (CPU and Memory)"
Here it should add GPU because PodFitsResources() also handle the resouce GPU:
    if allocatable.NvidiaGPU < podRequest.nvidiaGPU+nodeInfo.RequestedResource().NvidiaGPU {
        return false,
            newInsufficientResourceError(nvidiaGpuResourceName, podRequest.nvidiaGPU, nodeInfo.RequestedResource().NvidiaGPU, allocatable.NvidiaGPU)
    }

### CODE REVIEW

**Comment by brendandburns** [comment]
can you change this to read `(for example CPU, Memory and GPU)`

that way we won't have to continually updated this section as new resources are added.

thanks!

**Comment by Hui-Zhi** [comment]
LGTM

**Comment by jfrazelle** [comment]
lgtm

**Comment by lixiaobing10051267** [comment]
sorry, can I understand that I  should check all "CPU and Memory"?

**Comment by brendandburns** [comment]
@lixiaobing10051267 can you update this PR to reflect my earlier comment?

**Comment by lixiaobing10051267** [comment]
@brendandburns sorry can u express the operation in detail?

**Comment by lixiaobing10051267** [comment]
The GPU scheme is required to be promoted, close PR here, thanks:)

**Pull request closed without merging**
