### PR TITLE
Specify CustomResourcePublishOpenAPI is beta

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind documentation

**What this PR does / why we need it**:
Specify CustomResourcePublishOpenAPI is beta.
Ref kubernetes/enhancements#692

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
please provide the links to k/enhancements.

**Comment by roycaihw** [comment]
/lgtm

The enhancement issue is https://github.com/kubernetes/enhancements/issues/692

**Comment by ialidzhikov** [comment]
Approved labels is also needed. 🙃

**Comment by roycaihw** [comment]
/assign @deads2k

for approval

**Comment by roycaihw** [comment]
The feature went to GA in 1.16 and the kube_features file is up-to-date

/close

**Pull request closed without merging**
