### PR TITLE
Automated cherry pick of #16053 upstream release 1.1

### LINKED ISSUE #15382: Pod Disks should schedule a pod w/two RW PDs flake
Failed 2 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8824/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w_two_RW_PDs_both_mounted_to_one_container__write_to_PD__verify_contents__delete_pod__recreate_pod__verify_contents__and_repeat_in_rapid_succession/

/cc @saad-ali

### LINKED ISSUE #15978: GCE Cloudprovider `waitForOp` sometimes causes panics due to `invalid memory address or nil pointer dereference`.
While investigating #15382, I discovered that the `pkg/cloudprovider/providers/gce/gce.go:waitForOp(...)` method (copied below) sometimes causes panics due to `invalid memory address or nil pointer dereference`.

```GO
func waitForOp(op *compute.Operation, getOperation func() (*compute.Operation, error)) error {
	pollOp := op
	consecPollFails := 0
	for pollOp.Status != "DONE" {
		var err error
		time.Sleep(3 * time.Second)
		pollOp, err = getOperation()
		if err != nil {
			if consecPollFails == 2 {
				// Only bail if we've seen 3 consecutive polling errors.
				return err
			}
			consecPollFails++
		} else {
			consecPollFails = 0
		}
	}
	if pollOp.Error != nil && len(pollOp.Error.Errors) > 0 {
		return &googleapi.Error{
			Code:    int(pollOp.HttpErrorStatusCode),
			Message: pollOp.Error.Errors[0].Message,
		}
	}
	return nil

}
```
Error: `E1020 20:36:34.301927    3625 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`

Stack trace indicates the culprit is this line:
```GO
	for pollOp.Status != "DONE" {
```

I'll fix this along with #15382. This method also has the potential to block indefinitely if there is a bad server response, so the fix should also fix the max amount of time to wait.

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry picks PR #16053 to upstream release v1.1.
- Fixes #15978: GCE Cloudprovider `waitForOp` sometimes causes panics due to `invalid memory address or nil pointer dereference`
  - Fixes a bug where anytime there is a GCE error doing a get poll operation call the code would panic due to `nil pointer dereference`. This affects all GCE calls.
- Fixes #15382: Pod Disks should schedule a pod w/two RW PDs flake
  - Instead of using operation manager to defer to pending detach operations, this change ensures that attach/detach operations for the same GCE PD are atomic. This prevents a whole host of nasty race conditions.

CC @thockin

### CODE REVIEW

**Comment by saad-ali** [comment]
@k8s-bot unit test this please

**Comment by saad-ali** [comment]
@k8s-bot unit test this please

**Comment by saad-ali** [comment]
@k8s-bot test this

**Comment by saad-ali** [comment]
Jenkins Unit Tests are broken on release branch.
Re-running GCE E2E which flaked on an unrelated test.

**Comment by eparis** [comment]
I think the bot might be missing it because of the failed jenkins unit/integration  :-(

I'll dig in more in the morning....

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
