### PR TITLE
Automated cherry pick of #77661: Kubelet provides an updated and complete status of

### PR DESCRIPTION
**Pull request by mfpierre**
Cherry pick of #77661 on release-1.13.

#77661: Kubelet provides an updated and complete status of

### CODE REVIEW

**Review by yastij — APPROVED** [review]
/lgtm
/hold

Im in favor of cherrypicking this, holding to few CI runs.

**Comment by tpepper** [comment]
@yastij have you run those tests?

**Comment by yastij** [comment]
@tpepper - CI didn't complain

/hold cancel

**Comment by yastij** [comment]
@Random-Liu for approval

**Comment by mfpierre** [comment]
Hey, friendly reminder about this cherry-pick, it didn't make it for the last `1.12.10` release https://github.com/kubernetes/kubernetes/pull/77934 but it would be nice to have it for `1.13` & `1.14`

**Comment by tpepper** [comment]
@vishh, @Random-Liu can you give these two cherry picks a review and decide if they should be approved or closed?

**Comment by tpepper** [comment]
As this cherry pick never received its `/approve` from OWNERS and the 1.13.12 release today was the last for this branch, I'm closing this PR.

**Pull request closed without merging**
