### PR TITLE
Make resources' names in lowercase in generated clients

### PR DESCRIPTION
**Pull request by caesarxuchao**
Depending on #19912, only the commit "Use lowercase names in individual typed clients" is relevant.

Fixing #19894 for the generated clients.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this please

**Comment by krousey** [comment]
This looks fine, but I see this commit in #19912 as well. Which PR should this be submitted through? You can add my LGTM for the lowercase commit only on this PR when it's ready to go through.

**Comment by caesarxuchao** [comment]
@krousey I just removed that commit from #19912. It was a mistake.

Have you approved all commits in this PR or just the lower case commit?

**Comment by krousey** [comment]
Just the lower case as you said that was the only relevant one.

**Comment by caesarxuchao** [comment]
Sure. Thanks.

**Comment by caesarxuchao** [comment]
smarterclayton approved the other commits. I'm going to apply the label.

**Pull request merged**
