### PR TITLE
kubeadm: fix typo

### PR DESCRIPTION
**Pull request by globin**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34097)

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
Thanks for the PR!

However, you need to sign the CLA before I can merge it

**Comment by globin** [comment]
We (Mayflower GmbH) signed the company CLA earlier today, but I guess that's only recognised for @mayflower.de addresses, is there a possibility to add additional mail adresses/github account handles?

**Comment by luxas** [comment]
Or is it possible you just commit with your @mayflower.de address? I think that's easiest
Also, have you signed the linux foundation CLA as well?

**Comment by globin** [comment]
Should both be signed and commited with the company address now

**Comment by luxas** [comment]
reply `I signed it!` and the bot will check again

**Comment by globin** [comment]
I signed it!

**Comment by luxas** [comment]
@thockin @david-mcmahon Do you know why the CLA bot doesn't pick up this email?
I can't check why...

**Comment by luxas** [comment]
Seems like you're authorized for Linux Foundation, so applying human-approved CLA and lgtm since the bot doesn't seem to respond anymore...

**Pull request merged**
