### PR TITLE
Automated cherry pick of #48594 #48538

### PR DESCRIPTION
**Pull request by luxas**
Cherry pick of #48594 #48538 on release-1.7.

#48594: Add node-name flag to `init` phase
#48538: Add node-name flag to `join` phase

### CODE REVIEW

**Comment by wojtek-t** [comment]
@luxas - I'm fine with this PR, but I would prefer the original one to be merged first [it's not yet lgtm-ed, though I agree it's close to be :)]

**Comment by luxas** [comment]
@wojtek-t It is/was LGTM'd a couple of times, but failed on the unit/kops flakiness earlier this week. Now unfortunately needs a rebase and in order to keep things simple I'm cherrypicking now when the patch is easily applicable on release-1.7.

Even though I'm doing it now master and release-1.7 have diverged a bit, so I had to add a third commit for adopting to v1.7 -- only some trivial lines of code

It's most important to get it into v1.7 so I think it's ok to merge this now when tests are passing.
Then we have some time to check out the kubeadm e2e CI before v1.7.1 is cut

@wojtek-t Makes sense to merge now? If the tests had been okay #48594 would have been merged last Friday. Now it had to wait for the SQ and then had to rebase on large changes at HEAD, which makes it a lot harder to backport.

**Comment by luxas** [comment]
cc @GheRivero does this look good to you?

**Review by dmmcquay — APPROVED** [review]

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by luxas** [comment]
@wojtek-t Please remove the do-not-merge label so this can merge. Thanks!

**Comment by luxas** [comment]
https://github.com/kubernetes/kubernetes/pull/48594 is on its way into master now that presubmits aren't completely broken for pretty much the first time this week, so I think it makes sense to get this in as well

**Comment by dmmcquay** [comment]
/lgtm

I agree with @luxas assessment

**Comment by wojtek-t** [comment]
Agree - cherrypick approved.

**Pull request merged**
