### PR TITLE
move logs to kubectl/util

### PR DESCRIPTION
**Pull request by mengqiy**
Move `pkg/util/logs` to `pkg/kubectl/util/logs` per https://github.com/kubernetes/kubernetes/issues/48209#issuecomment-311730681
This will make kubeadm, kubefed, gke-certificates-controller and e2e have dependency on kubectl, which should be fine.

partially addresses: kubernetes/community#598

```release-note
NONE
```

/assign @apelisse @monopole

### CODE REVIEW

**Comment by apelisse** [comment]
> This will make kubeadm, kubefed, gke-certificates-controller and e2e have dependency on kubectl, which should be fine

is it?

**Comment by mengqiy** [comment]
IMO it is ok for all other k8s native clients to depend on kubectl.
And gke-certificates-controller is also OK to depend on kubectl per https://github.com/kubernetes/kubernetes/issues/48209#issuecomment-311730681.

If you disagree, we can move it to `kubernetes/common` repo.

**Comment by monopole** [comment]
Phil and I discussed the idea that the ultimate end state - the top level kubectl repo -
would have a subdir containing generally useful command line utils that it could vendor to other
command line programs in the k8s family.

We weren't happy with it, because it blurs the purpose of the kubrctl repo, making it both the home of shared libs and an executable.  Integration testing and rules about who vendors what will be easier if things like helm, kubectl, kubeadm, kubecfg, etc. are treated the same way rather than
having kubectl continue to be a special case.

But since common doesn't exist yet...  I'm in favor of this as an intermediate state.  

/lgtm

**Comment by mengqiy** [comment]
Rebased. PTAL

**Comment by monopole** [comment]
/approve 

Helps move  kubernetes/community#598 along.  

May move logs to common later, if there's movement on #50475

**Pull request merged**
