### PR TITLE
make log clear: cleanupOrphanedPodDirs()

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
make log clear: cleanupOrphanedPodDirs()

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mtaufen** [comment]
Ah, there is already another PR from the same branch: https://github.com/kubernetes/kubernetes/pull/54830

**Comment by zhangxiaoyu-zidif** [comment]
yes, thanks! it seems that "reopen" does not work

**Pull request closed without merging**
