### PR TITLE
kubelet/rkt: Add RunInContainer()/ExecInContainer()/PortForward().

### PR DESCRIPTION
**Pull request by yifan-gu**
@vmarmol @dchen1107 @jonboulle @bakins

Depends on #7465

### CODE REVIEW

**Comment by vmarmol** [comment]
Looks good overall, needs a rebase.

**Comment by yifan-gu** [comment]
Comments addressed, rebased, but I think it will not pass CI due to missing deps #7555

**Comment by yifan-gu** [comment]
Just rebased @vmarmol

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
