### PR TITLE
Improve unit test coverage

### PR DESCRIPTION
**Pull request by vantuvt**
**What this PR does / why we need it**:
Improve unit test coverage.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sjenning** [comment]
Thanks @vantuvt 

While this does add a unit test for `KnownControllers()`, that function basically take no arguments, has a single code code path, and always returns the same thing unless someone changes the code for it to return something else.  In which case the person making that change will just trip over the test case and need to change it as well.

I don't see this test adding any value.

**Comment by vantuvt** [comment]
Thanks for the review @sjenning.

When looking at the `KnownControllers` function it wasn't clear to me if a test was needed either. Given that this function seems to be critical to the startup path for the manager, how does someone who changes the set of known controllers know if they broke something? Sorry if this is a very basic question. I'm very new to K8s and still finding my way around. TIA.

**Comment by sjenning** [comment]
> Given that this function seems to be critical to the startup path for the manager, how does someone who changes the set of known controllers know if they broke something?

I agree, but this test doesn't provide that assurance.  All this test tells you is "you changed the controller list from what is was before" which really must be intentionally done by changing `KnownControllers()`.  So the test would really just be a confirmation dialog box asking:

You changed `KnownControllers()`.  Are you sure you meant to change `KnownControllers()`?  If so, change the test too please.

**Comment by vantuvt** [comment]
Those are good points. The test, however, indirectly provides some coverage of the `NewControllerInitializers` function too which has some (albeit simple) branch logic. Perhaps it's worth converting this test to cover that function explicitly instead?

**Pull request closed without merging**
