### PR TITLE
fix hpa comment and command line help

### PR DESCRIPTION
**Pull request by krmayankk**
```release-note
NONE
```

### CODE REVIEW

**Review by gjtempleton — CHANGES_REQUESTED** [review]
Are you sure this is right? It seems this period is still used for determining the period with which the HPAController re-syncs the number of pods in the objects it controls as per here: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L120

I do agree that this needs updating though at this isn't the only thing this resync period is used for these days, as the same resync period is used for periodic invalidation of the cache of custom metrics APIs available to the HPA: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/autoscaling.go#L59

**Comment by krmayankk** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L120

I dont see anything else being synced other than HPA objects ? What else is being synced @gjtempleton ? That queue is used to enter HPA objects . Pods are not even in the picture. Once HPA determines it needs to scale, it figures out the target from the HPA object and calls sscale

**Comment by krmayankk** [comment]
> Are you sure this is right? It seems this period is still used for determining the period with which the HPAController re-syncs the number of pods in the objects it controls as per here: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L120
> 
> I do agree that this needs updating though at this isn't the only thing this resync period is used for these days, as the same resync period is used for periodic invalidation of the cache of custom metrics APIs available to the HPA: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/autoscaling.go#L59

That line is the queue for containing the HPA object itself ? Pods are never in the picture as far as i can tell from code. Once HPA determines it needs to scale, it figures out the target from the HPA object and calls scale on the Deployment,ReplicaSet and StatefulSet. The desired and current replicas can be computed from these objects, so why would we ever look at the pods.

Yeah the second line is also used invalidation. What would you suggest we should update the comments to ?

**Comment by krmayankk** [comment]
@gjtempleton how about 
```The period for syncing the number of HPA's in horizontal pod autoscaler and for periodically invalidating the cache of custom metrics ``` ?

**Comment by jennybuckley** [comment]
I think the original comment was referring to syncing the the number of pods (CurrentReplicas) in the status of each HPA object (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/autoscaling/v1/types.go#L67-L68)

**Comment by krmayankk** [comment]
> I think the original comment was referring to syncing the the number of pods (CurrentReplicas) in the status of each HPA object (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/autoscaling/v1/types.go#L67-L68)

sure, so essentially it controls the how often it looks at the HPA objects, which in turn controls how often the CurrentReplicas in the HPA Status is updated. So we should make it more clear from 
`The period for syncing the number of pods in horizontal pod autoscaler.`
TO
`The period for syncing the number of current Replicas being managed by horizontal pod autoscaler.` Thoughts ?

**Comment by jennybuckley** [comment]
To me these both seem about equally clear. Is there a significant difference in meaning between `pods` and `replicas`?
/remove-sig api-machinery
I think this is more of a decision for sig/autoscaling

**Comment by krmayankk** [comment]
@jennybuckley for some reason, it was not clear to me what pods its syncing until i learnt its basically updating the replicas field in the HPA status. I would make that more clear in the option. Upto you .

`The period for syncing the number of current/observed Replicas being managed by horizontal pod autoscaler.`

**Pull request closed without merging**
