### PR TITLE
remove stack trace log when sorting with a bad unsortable field

### LINKED ISSUE #103239: kubectl get crash when sorting with a bad unsortable field
#### What happened:

I am getting a crash when trying to sort pod with kubectl on `.status.containerStatuses[]`

#### What you expected to happen:

Not crashing and at least an error message

#### How to reproduce it (as minimally and precisely as possible):

* `kubectl get pod -o name --sort-by=.status.containerStatuses[]`

#### Anything else we need to know?:

<details>
<summary>Crash log</summary>

```
chmouel@ibra 🐎 ~% /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/bin/linux/amd64/kubectl get pod -o name --sort-by=.status.containerStatuses[]                                
F0627 11:17:19.785868   49533 sorter.go:332] Field {.status.containerStatuses[]} in *unstructured.Unstructured is an unsortable type: interface, err: unsortable type: map[string]interface {}
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000182001, 0xc0000c2240, 0xbf, 0x111)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3092c60, 0xc000000003, 0x0, 0x0, 0xc0006223f0, 0x0, 0x2624982, 0x9, 0x14c, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x3092c60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1e6cd3e, 0x31, 0xc0006d1bc0, 0x4, ...)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1514
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*RuntimeSort).Less(0xc0006d1ac0, 0x1, 0x0, 0x30)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go:332 +0x76d
sort.insertionSort(0x20cb1f8, 0xc0006d1ac0, 0x0, 0x3)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/sort/sort.go:40 +0xc4
sort.quickSort(0x20cb1f8, 0xc0006d1ac0, 0x0, 0x3, 0x4)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/sort/sort.go:222 +0x205
sort.Sort(0x20cb1f8, 0xc0006d1ac0)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/sort/sort.go:231 +0x76
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.SortObjects(0x0, 0x0, 0xc00092a2d0, 0x3, 0x3, 0x7ffd8bffbbe5, 0x1b, 0x1, 0x1b0dde0, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go:145 +0x45d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*SortingPrinter).sortObj(0xc000892480, 0x209de60, 0xc0001b3440, 0x40e358, 0x10)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go:82 +0xb9
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*SortingPrinter).PrintObj(0xc000892480, 0x209de60, 0xc0001b3440, 0x2097040, 0xc000182008, 0x0, 0x20)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go:64 +0x92
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*TablePrinter).PrintObj(0xc0001ef440, 0x209de60, 0xc0001b3440, 0x2097040, 0xc000182008, 0xc0001b3460, 0xc00091b0e0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/table_printer.go:46 +0x174
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/printers.ResourcePrinterFunc.PrintObj(...)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/printers/interface.go:31
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).printGeneric(0xc0000ee870, 0xc000949180, 0xc00047ae80, 0x1)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:823 +0x78f
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Run(0xc0000ee870, 0x20ec6c0, 0xc000159700, 0xc00042db80, 0xc00047ae80, 0x1, 0x4, 0x0, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:502 +0x1330
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func2(0xc00042db80, 0xc00047ae80, 0x1, 0x4)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:180 +0x135
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00042db80, 0xc00047ae40, 0x4, 0x4, 0xc00042db80, 0xc00047ae40)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000617400, 0xc000184180, 0xc000184120, 0x6)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 33 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x3092c60)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xdf

goroutine 9 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1f1d190, 0x20954a0, 0xc00052e000, 0x1, 0xc000114ba0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1f1d190, 0x12a05f200, 0x0, 0x1, 0xc000114ba0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1f1d190, 0x12a05f200, 0xc000114ba0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 194 [IO wait]:
internal/poll.runtime_pollWait(0x7fc1d58223f0, 0x72, 0xffffffffffffffff)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000b40e18, 0x72, 0xb900, 0xb97a, 0xffffffffffffffff)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000b40e00, 0xc000cf2000, 0xb97a, 0xb97a, 0x0, 0x0, 0x0)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000b40e00, 0xc000cf2000, 0xb97a, 0xb97a, 0x81da, 0xc000cf579b, 0x5)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0003be008, 0xc000cf2000, 0xb97a, 0xb97a, 0x0, 0x0, 0x0)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0003ab4d0, 0xc000cf2000, 0xb97a, 0xb97a, 0x81da, 0xc000192800, 0x0)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc000380278, 0x2093300, 0xc0003ab4d0, 0x40b985, 0x1be3bc0, 0x1da1000)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000380000, 0x2096bc0, 0xc0003be008, 0x5, 0xc0003be008, 0x9)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000380000, 0x0, 0x0, 0xc00072e000)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000380000, 0xc000209000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc000185c20, 0xc000202738, 0x9, 0x9, 0x95a06b, 0xc000693c78, 0x407005)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x2093100, 0xc000185c20, 0xc000202738, 0x9, 0x9, 0x9, 0xc000c06190, 0x5042083d556f00, 0xc000c06190)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/io/io.go:328 +0x87
io.ReadFull(...)
        /home/linuxbrew/.linuxbrew/opt/go/libexec/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc000202738, 0x9, 0x9, 0x2093100, 0xc000185c20, 0x0, 0xc000000000, 0xc0009429f0, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc000202700, 0xc0009429f0, 0x0, 0x0, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000693fa8, 0x0, 0x0)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00039c000)
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /home/chmouel/GIT/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5
```
</details>

#### Environment:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-beta.0.145+a0f9c8c2778b97", GitCommit:"a0f9c8c2778b979cdd112d6802e3f41db19c2bc7", GitTreeState:"clean", BuildDate:"2021-06-27T09:09:52Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}` `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: tried on kind latest and openshift 4.7
- OS (e.g: `cat /etc/os-release`): debian sid
- Kernel (e.g. `uname -a`): 5.11.x
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others: kubectl compiled from tip branch (as of this bug report) with GO version 1.16.5

### PR DESCRIPTION
**Pull request by novahe**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
only print the error message and exit `klog.Exitf` , instead of using `klog.Fatalf` which is what is outputting the stack trace. 
#### Which issue(s) this PR fixes:

Fixes #103239

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by brianpursley** [comment]
It was unclear to me that just changing from `FatalF` to `ExitF` would omit the stack trace, but it appears to.  Here is the output I see with this PR:
```
F0706 17:21:53.696009  319939 sorter.go:332] Field {.status.containerStatuses[]} in *unstructured.Unstructured is an unsortable type: interface, err: unsortable type: map[string]interface {}
exit status 1
```

It is definitely cleaner than the huge stack trace you get currently and it does tell you that what you are sorting on is unsortable, so I think that is actionable for someone who sees this.

/lgtm

**Review by brianpursley — APPROVED** [review]

**Comment by eddiezane** [comment]
Thanks!

/approve

**Pull request merged**
