### PR TITLE
Automated cherry pick of #68823: Extract cpu requests to separate env variables.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #68823 on release-1.12.

#68823: Extract cpu requests to separate env variables.

### CODE REVIEW

**Comment by nikhita** [comment]
/kind feature
/retest

/assign @feiskyer 
for cherry-pick approval

**Comment by feiskyer** [comment]
@loburm  Could you add release notes in the original PR?

**Comment by loburm** [comment]
@feiskyer Done.

**Pull request merged**
