### PR TITLE
fixes data race in node controller

### LINKED ISSUE #6416: data race in node-controller error handling
stack trace here: https://github.com/mesosphere/kubernetes-mesos/issues/197#issuecomment-89336229

it's due to a shared `err` variable:
https://github.com/mesosphere/kubernetes-mesos/blob/1ec68d48d69c107df81b7bb5c1269f1072d70bd6/hack/patches/k8s---issue199.patch

### PR DESCRIPTION
**Pull request by jdef**
fixes #6416

### CODE REVIEW

**Comment by jdef** [comment]
I've already signed the CLA as james dot defelice at ishisystems dot com

**Comment by jdef** [comment]
PTAL @yujuhong

**Comment by yujuhong** [comment]
Thanks! The PR LGTM. Will merge on green.

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by davidopp** [comment]
LGTM

Thanks for catching this!

@yujuhong, Shippable is green so I think it's OK for you to merge?

**Comment by yujuhong** [comment]
Yes, travis failed because of #6199. It's a known issue.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/199

**Pull request merged**
