### PR TITLE
Fix grammar in api rules README

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: fix grammar in api rules documentation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by neolit123** [comment]
@CecileRobertMichon 
thanks for the PR!

please, take a look at this comment about singing the CLA: https://github.com/kubernetes/kubernetes/pull/69012#issuecomment-424146717
a CLA is required for submitting patches to k8s.

**Comment by neolit123** [comment]
/sig architecture
(?)

**Comment by CecileRobertMichon** [comment]
@neolit123 thanks! I had signed the CLA but it took a while to show here, looks like it shows as signed now. Let me know if there is anything else I should do.

**Comment by CecileRobertMichon** [comment]
/sig docs
(?)

**Comment by nikhita** [comment]
/retest

/assign @liggitt 
for approval

**Pull request merged**
