### PR TITLE
Cleanup manual conversions

### PR DESCRIPTION
**Pull request by thockin**
These might have been needed in the past, but no longer.  The ones that are left are a bad situation.

When we do codegen we: a) remove generated files; b) set a build tag to ignore generated files.  Then conversion-gen tool searches for specially-named conversion functions.  When there is a cross-API dependency, it can't find the functions (because (a) and (b) above) so they generate a compile error.  We should do better.  For now, docs++.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by alexzielenski** [comment]
>


>  When there is a cross-API dependency, it can't find the functions (because (a) and (b) above) so they generate a compile error. 

I haven't looked deeply into conversion-gen, so here are some assumptions I'm making (forgive me if its an oversimplification):

1. Generates a list of all GVKs (and their runtime type)
2. Pair all GVKs with all other GVKs of the same GroupKind (to find the list of necessary conversions)
3. Find all manually implemented conversion functions
4. Filter out all manually implemented conversions functions from the list of GVK pairs
5. Generate conversion functions for the remaining GVK pairs

IIUC the issue is that to determine #3 the codebase needs to be compilable. This fails due to missing symbol references after removing generated code and enabling a build tag.

I'm surprised that we need a valid full build for this. I would expect it to be possible to perform a best-effort typecheck (where type check/symbol errors are repalced with an Error AST node, or similar).

**Review by alexzielenski — APPROVED** [review]
/lgtm

can confirm PR is a no-op: removes manually written top level conversions functions to replace them with autogenerated ones with identical content.

**Comment by thockin** [comment]
> IIUC the issue is that to determine # 4 the codebase needs to be compilable. This fails due to missing symbol references after removing generated code and enabling a build tag.

More than that, we always exclude generated code when generating code.  Fundamentally, it's (IMO) sloppy and horrible that we just search for functions with the right name and fingerprint.  I think it would be better to do something like:
* Types which have manual conversions say so with a tag.
* Conversion-gen doesn't need the function to exist in order to "find it" - it just emits calls to the manual function or the named-by-convention function.

**Pull request merged**
