### PR TITLE
Remove deprecated flag --conntrack-max from kube-proxy

### LINKED ISSUE #78296: Remove deprecated kube-proxy flag --conntrack-max
The flag has been deprecated for many releases and can be removed.

The depreciation guide specifies that admin-only CLI flags can be removed after 6 months: https://kubernetes.io/docs/reference/using-api/deprecation-policy/

/kind cleanup
/sig network
/priority backlog

### PR DESCRIPTION
**Pull request by rikatz**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: This PR removes the deprecated flag ``--conntrack-max`` from kube-proxy

**Which issue(s) this PR fixes**:
Fixes #78296 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vllry** [comment]
/uncc @nicksardo 
/uncc @thockin 

FYI we usually mark WIP PRs as `WIP:` and make sure folks aren't subscribed unless we're ready to ask for reviews... Kubernetes notifications get exceedingly noisy.

/ok-to-test

**Comment by vllry** [comment]
@rikatz looks like you figured a bunch out, fingers crossed that the API tests pass! I've been struggling with that in #78294, as I'm not very familiar with the api machinery.

**Comment by rikatz** [comment]
@vllry tks for the help :D

I've been thinking if I was missing something (maybe the right place was staging and not the directly pkg itself). If this is the case let me know I would be more than happy to make things right :D

**Comment by vllry** [comment]
Hmm, looks like you're hitting the same issue that I was.

I understand broadly that you will need to implement a conversion function by hand, as the code generator does not understand how to resolve the mismatched struct signatures. However, I'm a little fuzzy on exactly how, and any other concerns (like if we care about field retention on an alpha API). I haven't poked anyone yet due to it being a long weekend.

**Comment by rikatz** [comment]
Good to know this isn't strange at all only to me!

I'm correcting here the _test files to reflect the change into the API and the cmd as well, and I'll wait a followup into your PR of the resource-container to see what am I missing.

In the meantime, if I can figure out something will also give you a feedback of what I did wrong here.

Thanks!

**Comment by rikatz** [comment]
@vllry Seems I've made a mess here with the commits (sorry about that, Jetlag...).

I'll close this PR and open other one more clean and correctly verified.

**Pull request closed without merging**
