### PR TITLE
Modify the initialization of results in generic_scheduler.go

### PR DESCRIPTION
**Pull request by jiulongzaitian**
Signed-off-by: zhangjie <zhangjie0619@yeah.net>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by allencloud** [comment]
LGTM , although I am not a maintainer.

**Comment by xiangpengzhao** [comment]
/release-note-none

This PR doesn't need a release note. A release-note label will lead to noise in CHANGELOG.

**Pull request merged**
