### PR TITLE
Use policy client with explicit version

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** :
Fixes partially #55993

**Special notes for your reviewer**:
/cc @caesarxuchao @sttts

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@supereagle currently the project is in code freeze for 1.9, so we can't merge the PRs since they are not critical.

Also, do you mind sending these changes in one PR is they are small enough? That way the changes can be merged faster.

**Comment by supereagle** [comment]
@caesarxuchao Sure, I will merge the changes for several clients into one PR if they are small enough, instead of one PR for each client. BTW, when can we remove these deprecated clients? Is there any plan?

**Comment by sttts** [comment]
/assign @fabianofranz 

For kubectl approval.

**Pull request merged**
