### PR TITLE
Update pd csi e2e yamls with latest driver

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update the gce pd csi driver to the latest in the e2e tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by davidz627** [comment]
noice
/lgtm

**Comment by saad-ali** [comment]
Very noice!

/lgtm
/approve

**Pull request merged**
