### PR TITLE
use nginx1.13 for echoserver test image on s390x

### PR DESCRIPTION
**Pull request by hchenxa**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
the docker image can not be built on s390x as the module of nginx-mod-http-lua and nginx-mod-http-lua-upstream was not available in repo v3.9.

@mkumatag @listx I need to change the s390 base image to use nginx:1.13-alpine as:

the nginx:1.13-alpine using v3.8 alpine apk repo and have the nginx lua module
the nginx:1.15-apline did not have nginx lua module in default alpine apk repo
the nginx lua module in v3.8 alpine apk repo have compatibility issues on nginx:1.15-alpine, after some test, only nginx:1.13-alpine can be used now.

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/84269

**Special notes for your reviewer**:
@mkumatag

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
the agnhost image is consolidating all the different image features,[ it has implemented an echo server](https://github.com/kubernetes/kubernetes/blob/48b90db9c32615d71d607080a59414b437fafc0b/test/images/agnhost/README.md#netexec) and it seems that it has an [s390x version](https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/agnhost-s390x?gcrImageListsize=30). Maybe you can use that?
/cc @bclau

**Comment by mkumatag** [comment]
> the agnhost image is consolidating all the different image features,[ it has implemented an echo server](https://github.com/kubernetes/kubernetes/blob/48b90db9c32615d71d607080a59414b437fafc0b/test/images/agnhost/README.md#netexec) and it seems that it has an [s390x version](https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/agnhost-s390x?gcrImageListsize=30). Maybe you can use that?
> /cc @bclau

@aojea we need to check anyone else is using this image, if not we can just deprecate this image.

**Comment by hchenxa** [comment]
seems still have some project using this docker image for test, refer https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/ingress/gce/static-ip-2/rc.yaml

test/e2e/testing-manifests/ingress/gce/static-ip-2/rc.yaml

**Comment by bclau** [comment]
> 
> 
> the agnhost image is consolidating all the different image features,[ it has implemented an echo server](https://github.com/kubernetes/kubernetes/blob/48b90db9c32615d71d607080a59414b437fafc0b/test/images/agnhost/README.md#netexec) and it seems that it has an [s390x version](https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/agnhost-s390x?gcrImageListsize=30). Maybe you can use that?
> /cc @bclau

Yeah, that could solve the problem. I'll need to see how the image is used though. If it's replaceable, we can go ahead.

> 
> 
> seems still have some project using this docker image for test, refer https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/ingress/gce/static-ip-2/rc.yaml

It's still under testing, so we could potentially replace it with the agnhost image.

FWIW, using nginx 1.3 lets the image be built, but it doesn't look right to me: https://paste.ubuntu.com/p/yQCZ7xGkrq/

From what I've noticed, the s390x images do not have any networking interfaces, for some reason.

**Comment by bclau** [comment]
From what I can see, those are the usages of the ``echoserver`` image:

    # test/e2e/network/ingress.go tests
    should create ingress with backend HTTPS
    should support multiple TLS certs
    multicluster ingress should get instance group annotation
    should be able to switch between IG and NEG modes
    should be able to create a ClusterIP service
    should sync endpoints to NEG
    rolling update backend pods should not cause service disruption
    should sync endpoints for both Ingress-referenced NEG and standalone NEG
    should remove clusters as expected
    single and multi-cluster ingresses should be able to exist together
    should conform to Ingress spec

    # /healthz readiness probe
    Creating and updating ingresses should happen promptly with small/medium/large amount of ingresses
    test/e2e/network/scale/localrun/ingress_scale.go

    # not sure this test even needs the echoserver image, since the container name is "busybox"
    should update PodDisruptionBudget status
    should block an eviction until the PDB is updated to allow it

In some cases, the image is being used for certificate-related tests, which I don't think agnhost can handle. Though, we could use ``nginx`` instead?

And there are some tests which shouldn't require ``echoserver`` at all, see the last test names.

**Comment by listx** [comment]
@hchenxa @claudiubelu what is the status of this PR?

**Pull request closed without merging**
