### PR TITLE
kubeadm: check ignore preflights errors len instead of nil

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:
when dig into https://github.com/kubernetes/kubeadm/issues/2943

```release-note
None
```

### CODE REVIEW

**Comment by chendave** [comment]
I tried this command locally, and cannot reproduce it. 

```kubeadm reset --force --v=6```

```golang
if ignorePreflightErrorsFromCLI != nil
```
this check seems like is correct, looking into this.

/lgtm
/hold

pls lift the hold if the UT is happy.

**Comment by pacoxu** [comment]
@chendave I can reproduce it by `reset` for multi times.

**Pull request closed without merging**
