### PR TITLE
auth delegation role

### PR DESCRIPTION
**Pull request by deads2k**
Add a bootstrap role for authentication and authorization delegation.  Useful for extension API servers.

@kubernetes/sig-auth

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37020)

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
role looks fine. I don't love the name, but nothing extremely better springs to mind

**Comment by deads2k** [comment]
@k8s-bot gce etcd3 e2e test this: issue #37184

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Pull request merged**
