### PR TITLE
Run tests for third-party code

### PR DESCRIPTION
**Pull request by pmorie**
The deep_equal_test is not being run.

### CODE REVIEW

**Comment by pmorie** [comment]
@zmerlynn Am I missing something?

**Comment by pmorie** [comment]
Also maybe needed for https://github.com/GoogleCloudPlatform/kubernetes/pull/8858

**Comment by pmorie** [comment]
@bgrant0607 i feel like we should figure this out for 1.0

**Comment by bgrant0607** [comment]
LGTM.

cc @ixdy @lavalamp

**Comment by bgrant0607** [comment]
Does this run the tests in third_party? The original assumption was that third_party was for non-Go code.

**Comment by bgrant0607** [comment]
And for code that was tested by someone else.

Maybe we should just run third_party/golang?

**Comment by zmerlynn** [comment]
Yeah... I'm all for testing everything, but we have enough fish to fry maintaining our own tests?

**Comment by bgrant0607** [comment]
@zmerlynn The issue is that we've forked some code in third_party/golang, so we really should be testing it.

**Comment by pmorie** [comment]
Correct, this is to run tests for forked code.

**Comment by zmerlynn** [comment]
I'm worried that this raises the barrier to entry into third_party and would potentially force us to fork code bases we haven't already forked in order to fix flaky tests in them. We have a `third_party/forked` dir, can we restrict to that, possibly after reorg?

**Comment by pmorie** [comment]
@zmerlynn 

> I'm worried that this raises the barrier to entry into third_party and would potentially force us to fork code bases we haven't already forked in order to fix flaky tests in them. We have a third_party/forked dir, can we restrict to that, possibly after reorg?

I'm not sure I see how this raises the barrier; what am I missing?

**Comment by zmerlynn** [comment]
Am I misreading something or isn't it now including all of `third_party`? Sorry, bouncing between between things. So if someone wants to put package `foo` in `third_party` and it happens to have some Go code in it, they have to make sure it has no flakey tests? I guess that seems like an unlikely scenario if we're not also forking the code. Okay, nevermind.

LGTM.

**Comment by pmorie** [comment]
@zmerlynn 

>  So if someone wants to put package foo in third_party and it happens to have some Go code in it, they have to make sure it has no flakey tests?

Correct, if you fork code into third_party, you have to make sure the tests work.

**Comment by lavalamp** [comment]
third_party only includes go code that we've modified for some reason. (and other non-go code, but we don't care about that here.) We should really run the tests in it.

go dependencies that we *haven't* changed are in the Godeps dir, and in theory we don't need to run their unit tests-- whoever last updated the dependency should have verified that it worked.

**Pull request merged**
