### PR TITLE
[1.20][go1.15] Update to go1.15.10

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature
/area dependency

**What this PR does / why we need it**:

- Update to go1.15.10

Tracking issue: https://github.com/kubernetes/release/issues/1940
Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1615405842039400

/assign @justaugustus @mkumatag @liggitt @dims 
cc: @kubernetes/release-engineering 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Kubernetes is now built using go1.15.10
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
build and CI failures look relevant

**Comment by cpanato** [comment]
found an issue in the publishing bot, fixing 
cc @nikhita

**Comment by liggitt** [comment]
blocked by https://github.com/kubernetes/publishing-bot/pull/246

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
