### PR TITLE
Update sig-cli reviewers and approvers

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This updates the sig-cli reviewers and approvers.

**Special notes for your reviewer**:
/assign @pwittrock @seans3 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig cli
/priority backlog

### CODE REVIEW

**Comment by smarterclayton** [comment]
/approve
/hold

for any other comments for two days.  Have all participants been notified?  Has this been discussed in the sig-cli meetings and mailing list?

**Comment by soltysh** [comment]
> for any other comments for two days. Have all participants been notified? Has this been discussed in the sig-cli meetings and mailing list?

This was discussed with other SIG-CLI over the past days and was brought up during today's sig-cli. 

:+1: for 2 days soak time

**Comment by smarterclayton** [comment]
Time's up

/hold cancel

**Pull request merged**
