### PR TITLE
modify kubenet mutex and add timer

### PR DESCRIPTION
**Pull request by freehan**

### CODE REVIEW

**Comment by dcbw** [comment]
Is the concern here access to the pod cidr map still, or is there an issue with running concurrent execution of other parts of TearDownPod/SetUpPod?

**Comment by freehan** [comment]
I still have concerns about accessing pod cidr map in concurrent go routines. https://blog.golang.org/go-maps-in-action

Also, I am adding hostPort support in kubenet. This involves manipulating iptables during SetUpPod and TearDownPod.

**Comment by freehan** [comment]
Maybe we should just be thorough and protect pod cidr map with getter/setter.

**Comment by dcbw** [comment]
> Also, I am adding hostPort support in kubenet.

@freehan I was going to do that at some point too :)  I wonder if that should be eventually be new CNI sub-plugin like the IPAM plugins are.

**Comment by dcbw** [comment]
LGTM; I've got some changes in the rkt kubenet PR that will conflict with this, so we should get this merged first.

**Comment by freehan** [comment]
>I wonder if that should be eventually be new CNI sub-plugin like the IPAM plugins are.

Yeah. I thought so too. But it looks to me that CNI handles L3 stuff mostly. It does not touch ports yet. 

Plus I feel that it will not fit in 1.3 timeline unless we fork CNI.

**Comment by freehan** [comment]
@dcbw 
Here is an example that something went wrong in kubenet suite. https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-kubenet/1790/

5 tests failed in this run. I checked `service up and down` test. It failed because pod `service2-xtv0w` stuck in pending state. Kubelet cannot retrieve pod ip even setUpPod returned successfully. 

My guess is the podCIDR map got corrupted.

**Pull request merged**
