### PR TITLE
Delete unuse err check

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
err has fatal, this err check  can't execute.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
thank you ~

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zjj2wry** [comment]
assign @pwittrock @eparis

**Pull request merged**
