### PR TITLE
Remove generally available feature gate MinDomainsInPodTopologySpread

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

GA: v1.30

A follow-up of https://github.com/kubernetes/kubernetes/pull/123481

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `MinDomainsInPodTopologySpread`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
It looks correct
/lgtm
/approve

@logicalhan can you PTAL to check the removal of feature gates with the versioning thing is correct?

/assign @thockin

**Pull request merged**
