### PR TITLE
Automated cherry pick of #54257

### PR DESCRIPTION
**Pull request by tiran**
Cherry pick of #54257 on release-1.8.

#54257: Use GetByKey() in typeLister_NonNamespacedGet

**Release note**:
```
Optimize excessive memory allocation in resource listers on GET requests
```

### CODE REVIEW

**Comment by enj** [comment]
/lgtm

@wojtek-t cherrypick approval?

**Comment by wojtek-t** [comment]
@jpbetz is 1.8 patch release manager

**Comment by enj** [comment]
/ok-to-test

@jpbetz this fix is merged in 1.7 and 1.9, just need 1.8.

**Comment by jpbetz** [comment]
Cherry pick approved for 1.8.

**Comment by jpbetz** [comment]
Need a lgtm and approval from appropriate owners.

**Pull request merged**
