### PR TITLE
Remove unused NodeRegexp var from master

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
`Failed to create static ip pull-e2e-5-master-ip`
@k8s-bot ok to test

**Comment by ashcrow** [comment]
@nikhiljindal another e2e flake.

Change looks good to me. The variable doesn't show up in ```pkg```, ```cmd```, nor ```api``` so it seems like a safe removal.

**Comment by nikhiljindal** [comment]
Same error again
```
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:41:01  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
16:41:01 
16:41:01 Failed to create static ip pull-e2e-0-master-ip 
```

@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
