### PR TITLE
EOL Google's registry caching mirror

### PR DESCRIPTION
**Pull request by thockin**
Docker's v1 registry has gotten slower and slower, and they have no
interest in fixing it.  Using a mirror forces v1 mode.  Measurements
show that v1 with our mirror is slower than v2 with docker's registry in
just about all metrics.

@timbot
@brendanburns 

We should get this into the next release.

@bakins - apparently CoreOS setups also use a cache, and I bet you suffer the same problem.

### CODE REVIEW

**Comment by mbforbes** [comment]
Assigning to @brendandburns—@thockin please drive to the necessary two LGTM's if you want this in fast! TY!

**Comment by brendandburns** [comment]
LGTM #1

**Comment by kelseyhightower** [comment]
LGTM

**Comment by brendandburns** [comment]
Ok to merge on Kelsey's LGTM since this is a simple PR.

**Pull request merged**
