### PR TITLE
Automated cherry pick of #18840 #18903 upstream release 1.0

### PR DESCRIPTION
**Pull request by ikehz**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@ihmccreery - I guess e2e tests in 1.0 branch are so broken that this PR is not mergable, unless you do it manually...

**Comment by ihmccreery** [comment]
Merging by hand.

**Pull request merged**
