### PR TITLE
Automated cherry pick of #49495 upstream release 1.7

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #49495 on release-1.7.

#49495: make it possible to allow discovery errors for controllers

### CODE REVIEW

**Comment by wojtek-t** [comment]
@deads2k - it seems those failures are not flakes. Can you please take a look?

**Comment by deads2k** [comment]
> @deads2k - it seems those failures are not flakes. Can you please take a look?

Looks like an incomplete federation stub of some kind.  Maybe they can just do whatever they change in 1.8.

**Comment by wojtek-t** [comment]
@deads2k - this is not failing on 1.7 branch and on other cherrypicks. This is related to this particular PR.

**Comment by foxish** [comment]
@kubernetes/sig-federation-bugs @nikhiljindal PTAL.
This fix is important for 1.7, and appears blocked by the failing unit test.

**Comment by wojtek-t** [comment]
@foxish - I'm pretty convinced that failing unit tests are related to this cl - I have seen this failure on any other PR to 1.7 branch and on this one I've seen them 5+ times

**Comment by foxish** [comment]
Sorry, I see that now. I was thrown off by @deads2k's comment. Investigating further.

**Comment by foxish** [comment]
Looks like these tests were deleted entirely in master in https://github.com/kubernetes/kubernetes/pull/47890.

**Comment by wojtek-t** [comment]
I'm not convinced that those flakes aren't real issues - those are to frequent comparing to other PRs.
Also it's pretty late and we really want to cut the release today.
So I'm declining to take this PR into 1.7.4 - we should try to let this in for 1.7.5 (we can consider another patch release next week if this is so important).

**Comment by foxish** [comment]
/test pull-kubernetes-e2e-gce-etcd3

They don't look related to the change though.

**Comment by foxish** [comment]
Different tests failing each time, which make me suspect it is indeed a flake. Retesting.
/test pull-kubernetes-e2e-gce-etcd3

**Comment by foxish** [comment]
@wojtek-t, removed do-not-merge. 1.7.4 is cut already as I understand. Targeting this for 1.7.5.

**Pull request merged**
