### PR TITLE
DNS: expose 53/TCP

### LINKED ISSUE #7474: kube-dns pod should expose TCP port
This is necessary for large DNS responses, as in multi-record responses to headless.  Also ports will need to be named.

### PR DESCRIPTION
**Pull request by thockin**
Finish v1beta3 conversion, too.

Fixes #7474 

@vishh or  @cjcullen 

Will add e2e coverage of this if I can figure it out.

### CODE REVIEW

**Comment by mbforbes** [comment]
@cjcullen of course feel free to swap around

**Comment by thockin** [comment]
e2e is hard - the only tool I know that can do TCP lookups is dig, and busybox !has dig.  will keep thinking about this.

In the mean time, manually tested.

**Comment by vishh** [comment]
LGTM

**Comment by mbforbes** [comment]
(To @vishh as he's already looked now.) I'll merge on green tomorrow—squash maybe?

**Comment by thockin** [comment]
Give me a bit to figure out e2e.  I can't figure out how to reproducibly
get a container with `dig` in it that isn't full-on ubuntu.  Grr.  I could
get source code and build my own static binary, but that's not really
reproducible.

**Comment by mbforbes** [comment]
Mmm... wish I knew more about *nix tooling ... @zmerlynn does, I think—thoughts?

**Comment by thockin** [comment]
The dig source code is the ISC bind distribution and does not have a
provision for static (the old issue with libresolve being dynamic no matter
what).  Still hunting for a good answer.

**Comment by zmerlynn** [comment]
When I had to do this in bring up scripts on our system, I was left with
"getent hosts".

**Comment by thockin** [comment]
Added e2e, PTAL

**Comment by vishh** [comment]
Thanks for the e2e Tim. LGTM

**Pull request merged**
