### PR TITLE
Fix config file names inside fluentd-gcp image

### PR DESCRIPTION
**Pull request by crassirostris**
Need this in order to merge https://github.com/kubernetes/kubernetes/pull/36358

Because on container-vm we need implicitly used configuration file

@piosz

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36370)

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by Crassirostris** [comment]
@k8s-bot unit test this

**Comment by Crassirostris** [comment]
@k8s-bot gci gke e2e test this

**Comment by Crassirostris** [comment]
@k8s-bot unit test this

**Comment by Crassirostris** [comment]
@k8s-bot gci gke e2e test this

**Comment by Crassirostris** [comment]
@k8s-bot node e2e test this

**Pull request merged**
