### PR TITLE
Deprecate HostConfig at container start and only set network configuration for infracontainer

### LINKED ISSUE #20454: Kubelet: Deprecate HostConfig at container start
HostConfig at container start will be deprecated in docker 1.10 https://github.com/docker/docker/releases/tag/v1.10.0-rc2.

Hence HostConfig at container create is added long time ago. After some compatibility check to make sure HostConfig at container create is compatible with versions after 1.7, we could use HostConfig at container create instead of start.

For issue #19720

### LINKED ISSUE #20583: Kubelet should not rely on containerID for termination message detection.
Now kubelet creates the container log by joining `(pod metadata)+(container name)+(containerID)` [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L731), and then mount it to container by adding it to `bind` in `HostConfig` [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L739), and pass it to container when start [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L775).

It means that we could only creating container log directory after `create` the container, because we can only get `containerID` after creating it. [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L714)

However, as is mentioned in issue #20454, `HostConfig` at container start will be deprecated from 1.10, and will be completely removed by 1.12. Although for 1.10 we could still use it, there will be quite a lot of annoying warning log in `docker.log`:
```
time="2016-02-03T20:28:57.867598821Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:28:58.330340910Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:39:38.184004120Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:39:38.624884402Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
```

So after 1.12 we could only pass `HostConfig` to container create. If so, we should
  * not rely on containerID when creating the container log directory
  * Or, find some other ways to mount directory to container after it is created but not started.

/cc @kubernetes/sig-node

### LINKED ISSUE #20759: Kubelet should not set network configurations except NetworkMode for non-infra containers.
As is discussed  in #20737.

Since docker has added some network configuration check for 

1) We should not set any other network configurations (such as hostname, exposedPorts,  DNS etc.) for non-infra containers except `NetworkMode=container:InfraContainerId`

2) We should let the network configuration of infrastructure container follow the [ValidateNetMode()](https://github.com/docker/docker/blob/42ee908b3faa231322052c27d9ec8ffebc1c40eb/runconfig/hostconfig_unix.go#L27) check.

/cc @kubernetes/sig-network @kubernetes/sig-node

### PR DESCRIPTION
**Pull request by Random-Liu**
In this PR:
- The first commit is another try for #20615, nothing is changed.
- The second commit changed the container network configuration code to make sure only infracontainer is configured with specific network configuration.

With this PR, local cluster with docker 1.9+ works for me. I also tried the e2e test in `dns.go` and `networking.go`, it works.

/cc @dchen1107 @yujuhong @ArtfulCoder 

Fixes #20454.
Fixes #20583.
Fixes #20759

### CODE REVIEW

**Comment by Random-Liu** [comment]
Addressed comments, will squash the last commit before merging.

**Comment by yujuhong** [comment]
LGTM. @dchen1107, @ArtfulCoder, anyone wants to take a second look?

**Comment by dchen1107** [comment]
LGTM

**Comment by Random-Liu** [comment]
Add lgtm again because I just did a rebase.

**Pull request merged**
