### PR TITLE
fix todo: remove the unused flag

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fix todo: remove the unused flag
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @deads2k @sttts 
cc @hzxuzhonghu

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton for approval

**Comment by smarterclayton** [comment]
Comment on the issue why it’s safe to remove now?

**Comment by thockin** [comment]
Has this cleared the announce-and-wait deprecation window?

**Comment by hanxiaoshuai** [comment]
@smarterclayton @thockin RepairMalformedUpdates is moved to k8s.io/apimachinery/pkg/api/validation/objectmeta.go, and it is defined by true. The RepairMalformedUpdates in apis/core/validation is not used.

**Comment by thockin** [comment]
Yes, but you're removing a flag, which will break anyone who has this flag set.  Typically we would call MarkDeprecated() on it and let it sit for 6 months before removing it.

**Pull request closed without merging**
