### PR TITLE
Move StatefulSetStartOrdinal feature gate to beta

### PR DESCRIPTION
**Pull request by pwschuurman**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR moves the StatefulSetStartOrdinal from alpha -> beta. It also default enables the feature.

#### Does this PR introduce a user-facing change?
```release-note
Enable the "StatefulSetStartOrdinal" feature gate in beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
- KEP: https://github.com/kubernetes/enhancements/issues/3335
- Blog: https://github.com/kubernetes/website/pull/37418

### CODE REVIEW

**Comment by liggitt** [comment]
commented on https://github.com/kubernetes/kubernetes/pull/112744/files#r1114602379, but there's a validation fix needed to always validate the field if non-nil, regardless of feature gate validation

**Comment by pwschuurman** [comment]
> commented on https://github.com/kubernetes/kubernetes/pull/112744/files#r1114602379, but there's a validation fix needed to always validate the field if non-nil, regardless of feature gate enablement

Raised https://github.com/kubernetes/kubernetes/issues/116025. To be fixed in https://github.com/kubernetes/kubernetes/pull/116027

**Review by soltysh — CHANGES_REQUESTED** [review]
You also need to update the api fields https://github.com/kubernetes/kubernetes/blob/d446bebca8008ff8ba8906c76647c0ae40dbb6f0/staging/src/k8s.io/api/apps/v1/types.go#L263 
so they say beta, all of them :sweat_smile:

**Comment by pwschuurman** [comment]
> You also need to update the api fields
> 
> https://github.com/kubernetes/kubernetes/blob/d446bebca8008ff8ba8906c76647c0ae40dbb6f0/staging/src/k8s.io/api/apps/v1/types.go#L263
> 
> 
> so they say beta, all of them

Thanks updated all the `types.go` files, and reflected changes to the autogenerated files.

**Review by soltysh — APPROVED** [review]
/lgtm
from sig-apps pov
tests are blocked by switching this to on by default in https://github.com/kubernetes/kubernetes/pull/115468

**Comment by smarterclayton** [comment]
/approve

given sig tag and backport of the validation issue

**Pull request merged**
