### PR TITLE
Code optimization

### PR DESCRIPTION
**Pull request by zdj6373**
Accept function, the same sentence information repeated three times, under the optimization, recorded in the call function

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37679)

**Comment by zdj6373** [comment]
@brendandburns  Be free to help review, thank you

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot kops aws e2e test this

LGTM.

**Comment by zdj6373** [comment]
@brendandburns help “@k8s-bot kops aws e2e test this”，thank you

**Pull request merged**
