### PR TITLE
Demote namespace e2e test to flaky in parallel (and fix it's name).

### PR DESCRIPTION
**Pull request by ghost**
As per @caesarxuchao's oncall handoff email, this test has failed 19 times out of the past 400 parallel runs.  The proposed fix is blocked in #7372.  Until it's fixed, demote this test to flaky.
I also renamed the tests so as to be correctly formed sentences, as per the rest of thew test suite.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
Urgh!  e2e failures look totally unrelated to this PR.  While I debug that in parallel, lets rety:

@k8s-bot please test this again.

**Comment by quinton-hoole** [comment]
And another flake.  Both failed tests were as a result of redis master pod never reaching ready state:

```
gave up waiting for pod 'redis-master-5fnhc' to be 'running' after 5m0s
```

I wonder whether someone borked that image somehow?  Either way, it has nothing to do with this PR. 

Retrying.

@k8s-bot test this again please

**Comment by caesarxuchao** [comment]
Sorry @quinton-hoole, i just realized this commit is wait for my LGTM. I just apply the label. Thank you!

**Pull request merged**
