### PR TITLE
add HostIP field of podStatus while pod is evicted but not deleted.

### PR DESCRIPTION
**Pull request by volume-ji**
**What this PR does / why we need it**:
1. When I create a controlled or isolated pod setting the ephemeral-storage limits and requests, it'is easy to exceed ephemeral-storage limit size, which lead to that the docker container is killed by eviction_manager, remains pod body with Evicted status when I use the command: 'kubectl get po <pod-name> -n <my-namespace> -o wide' and status structure  initialize four fields again. Actually, the Evicted pod will not be deleted by invoking kube-apiserver API interface. 
2. When I use the command "kubectl get po <pod-name> -n <my-namespace> -o yaml", I get the result consists of status(pod) which have four fields including phase, message, reason and startTime. It lacks the field of HostIP which can be obtained completely from kubelet if the pod has assigned to one node.
3. It's  essential that filling up the status structure that totally have 11 fields. When pod is evicted, container is killed. conditions, containerStatuses, initContainerStatuses, podIP and qosClass filed of status are meaningless, they can be ignored. but hostIP filed can be obtained from pod's status.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #NONE 

**Special notes for your reviewer**:
NONE
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
cc @kubernetes/sig-node-pr-reviews

**Comment by vishh** [comment]
Why do you need the host IP of an evicted pod?

**Pull request closed without merging**
