### PR TITLE
openstack: Implement the `Routes` provider API

### PR DESCRIPTION
**Pull request by anguslees**
``` release-note

Implement the Routes provider API for OpenStack using Neutron extraroute extension.  This removes the need for flannel/etc where supported.  To use, ensure all your nodes are on the same Neutron (private) network and specify the router ID in new `[Route]` section of provider config:

    [Route]
    router-id = <router UUID>
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32663)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Probably someone better than me to review this @kubernetes/sig-openstack

**Comment by errordeveloper** [comment]
In the light of https://github.com/kubernetes/features/issues/88, would it be possible to implement this functionality as an add-on without making any changes to KCM at this point? / cc @kubernetes/sig-cluster-lifecycle @kubernetes/sig-network

**Comment by errordeveloper** [comment]
@anguslees the previous comment doesn't relate to your work here. However, I can see you are proposing changes to `cluster/`, and I believe no new features are accepted for that particular directory - it's been deprecated. I you would like to help maintaining the Heat template, we can discuss that on the list. I don't know who maintains it right now.

**Comment by anguslees** [comment]
@errordeveloper: I'm happy to drop the cluster/ changes from this PR, if you think we're organisationally unable to reach a conclusion on that portion.

**Comment by anguslees** [comment]
@dagnello: can you review this?

**Comment by anguslees** [comment]
@k8s-bot kubemark e2e test this

**Comment by justinsb** [comment]
I don't think making cloudprovider functionality optional should impact merging this. This looks like good code that adds a valuable feature for OpenStack users, and we don't want it to bitrot to the point where we lose it.

I believe the most-recent plan I've heard for https://github.com/kubernetes/features/issues/88 is to create a separate kcm per cloudprovider, and then just require a kcm-core and a kcm-openstack.  Having a few more controllers is not going to be the tricky bit there, I don't think: getting the first one out is the hard one; the rest are then easy.

**Comment by anguslees** [comment]
ping @dagnello for openstack review

**Comment by fejta** [comment]
@k8s-bot cvm gce e2e test this

**Comment by anguslees** [comment]
@k8s-bot unit test this

**Comment by dagnello** [comment]
@anguslees lgtm.  I like the "NewCaller" cleanup on failure idea :)

**Comment by anguslees** [comment]
`./hack/verify-test-owners.sh` suddenly wants me to become the owner of various tests that aren't mine??
@k8s-bot verify test this

**Comment by anguslees** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gce e2e test this

**Comment by anguslees** [comment]
@mikedanese for re-lgtm following bazel-induced rebase

**Comment by anguslees** [comment]
@mikedanese / @smarterclayton : quick, re-apply your lgtm label before another CI bot breaks!

**Comment by anguslees** [comment]
@mikedanese / @smarterclayton: too late, the CI bots are all broken again :(

**Comment by anguslees** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot verify test this
@k8s-bot kops aws e2e test this

**Comment by anguslees** [comment]
@k8s-bot kops aws e2e test this

**Comment by justinsb** [comment]
@anguslees AWS kops bots are hitting rate limits so my understanding is that they are non-blocking until we work around / get higher limits.

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
