### PR TITLE
Automated cherry pick of #65926: Fix RunAsGroup.

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #65926 on release-1.10.

#65926: Fix RunAsGroup.

### CODE REVIEW

**Comment by feiskyer** [comment]
> do we typically do cherry-picks for alpha features?

I think it's ok because this is actually a regression bug fix.

**Comment by Random-Liu** [comment]
@liggitt Without this, we don't support this feature at all. I think we should cherry-pick to make this feature actually "supported".

**Comment by Random-Liu** [comment]
@MaciekPytel for approval.

**Pull request merged**
