### PR TITLE
Added kubectl apply validation to prevent using --dry-run=server with --force

### PR DESCRIPTION
**Pull request by brianpursley**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
If you try to use `kubectl apply` with  `--dry-run=server`  and `--force` flags, it will hang indefinitely because it is waiting for the resource to be deleted but that never actually happens because dry run is being used.

This PR adds a validation check to prevent `--dry-run=server` and `--force` from being used at the same time.

**Which issue(s) this PR fixes**:
This is associated with https://github.com/kubernetes/kubernetes/issues/90017, but I'm not sure I can say this "fixes" it because it just prevents that combination of flags.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by zhouya0** [comment]
/lgtm
The programme loops in:https://github.com/kubernetes/kubernetes/blob/eb50f4dd096813b2fd28314d09f88b8d0bd1ab8d/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L213-L221

So actually `--force` will run into `deleteAndCreate` function and delete resource(if resource is changed), but `--sever-dry-run` will never let the deletion happen and above logic will never reach the condition.
By the way, seems change this logic to use `WaitCmd` is better(never have infinity loop) and I'll try to submit a PR on that.

**Comment by brianpursley** [comment]
> /lgtm
> The programme loops in:
> 
> https://github.com/kubernetes/kubernetes/blob/eb50f4dd096813b2fd28314d09f88b8d0bd1ab8d/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L213-L221
> 
> So actually `--force` will run into `deleteAndCreate` function and delete resource(if resource is changed), but `--sever-dry-run` will never let the deletion happen and above logic will never reach the condition.
> By the way, seems change this logic to use `WaitCmd` is better(never have infinity loop) and I'll try to submit a PR on that.

@zhouya0 Thanks. Do you think I should make a change in this PR to use WaitCmd instead?

**Comment by zhouya0** [comment]
Yes, Sure go ahead. :)
Just I don't know If I get the really meaning of `// TODO: use wait ` written by @soltysh.

**Comment by brianpursley** [comment]
> Yes, Sure go ahead. :)
> Just I don't know If I get the really meaning of `// TODO: use wait ` written by @soltysh.

Yeah, actually I'm not sure what that means either. I wonder if it is already done because it looks like it is using `wait` already.

I'm not going to make any change to that code.

**Comment by julianvmodesto** [comment]
I think this is right to make `--force` incompatible here.

Thanks for the test -- I wonder if this is something we want in integration instead though?

/lgtm

cc @apelisse

**Pull request merged**
