### PR TITLE
kube-scheduler: ensure the default config output of --write-to-config is usable

### LINKED ISSUE #103308: Scheduler: Ensure the default config output of --write-to-config is usable
--write-to-config flag in the scheduler writes to a file the default component config; however this config if passed back to the scheduler is not usable because it lists all default plugins as enabled without disabling them.

To make the configuration usable as an input config while at the same time useful for debugging, the output should disable all plugins for each extension point using the "*" expression.

/help
/sig scheduling
/good-first-issue

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kube-scheduler: ensure the default config output of --write-to-config is usable

#### Which issue(s) this PR fixes:

Fixes #103308

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ahg-g — COMMENTED** [review]
did you test that this works in practice?

First `kube-scheduler --master=http://localhost:8080 --write-config-to default.yaml`
Then `kube-scheduler --master=http://localhost:8080 --config default.yaml`

**Comment by SataQiu** [comment]
> did you test that this works in practice?
> 
> First `kube-scheduler --master=http://localhost:8080 --write-config-to default.yaml`
> Then `kube-scheduler --master=http://localhost:8080 --config default.yaml`

I tested it with a `kind` cluster and the `kube-scheduler` was able to launch using the generated configuration file.

```sh
shida.qsd@B-W5YRML85-0316 kubernetes % kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊

shida.qsd@B-W5YRML85-0316 kubernetes % make kube-scheduler
+++ [0701 10:18:18] Building go targets for darwin/amd64:
    cmd/kube-scheduler

shida.qsd@B-W5YRML85-0316 kubernetes % ./_output/bin/kube-scheduler --kubeconfig=/Users/shida.qsd/.kube/config --write-config-to default.yaml
I0701 10:20:27.389304   98750 serving.go:347] Generated self-signed cert in-memory
W0701 10:20:27.825291   98750 authentication.go:316] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0701 10:20:27.825337   98750 authentication.go:340] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0701 10:20:27.825364   98750 authorization.go:193] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0701 10:20:27.953497   98750 configfile.go:132] "Wrote configuration" file="default.yaml"

shida.qsd@B-W5YRML85-0316 kubernetes % ./_output/bin/kube-scheduler --kubeconfig=/Users/shida.qsd/.kube/config --config default.yaml
I0701 10:21:11.465938   99418 serving.go:347] Generated self-signed cert in-memory
W0701 10:21:11.675834   99418 authentication.go:316] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0701 10:21:11.675880   99418 authentication.go:340] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0701 10:21:11.675917   99418 authorization.go:193] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
W0701 10:21:11.891671   99418 authorization.go:47] Authorization is disabled
W0701 10:21:11.891699   99418 authentication.go:47] Authentication is disabled
I0701 10:21:11.891730   99418 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I0701 10:21:11.895248   99418 secure_serving.go:195] Serving securely on [::]:10259
I0701 10:21:11.896362   99418 tlsconfig.go:240] "Starting DynamicServingCertificateController"
......
```

[default.yaml.txt](https://github.com/kubernetes/kubernetes/files/6744984/default.yaml.txt)

**Comment by ahg-g** [comment]
Thanks
/lgtm
/approve

**Comment by alculquicondor** [comment]
I would like to revert this, after merging #99582 has merged

@chendave could you verify if it works and send a revert PR?

**Comment by chendave** [comment]
sure, on it, also found a defect, I will send a PR to fix it today.

**Pull request merged**
