### PR TITLE
Update go-etcd client library version and add ugorji codec to dependencies

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This improves performance of reading responses from etcd server.

Latency metrics in 100 node cluster with 8-core master during density test (30 pods per node):

```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.013133s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.013133s}
INFO: Top latency metric: {Verb:POST Resource:services Quantile:0.99 Latency:981.668ms}
INFO: Top latency metric: {Verb:POST Resource:limitranges Quantile:0.99 Latency:564.016ms}
INFO: Top latency metric: {Verb:POST Resource:services Quantile:0.9 Latency:512.61ms}
```

Ref #4521 
@wojtek-t @davidopp

### CODE REVIEW

**Comment by xiang90** [comment]
@fgrzadkowski Any data about the latency before the change?

**Comment by fgrzadkowski** [comment]
I'm running it now.

**Comment by fgrzadkowski** [comment]
Results from one run without this change (current HEAD):
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.307695s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.089075s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:576.638ms}
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:427.68ms}
INFO: Top latency metric: {Verb:POST Resource:bindings Quantile:0.99 Latency:395.389ms}
```
Which gives around 25% improvement.

Both results are after a single run, so in reality difference might be slightly different.

**Comment by xiang90** [comment]
@fgrzadkowski Got it. Thank you!

**Comment by lavalamp** [comment]
LGTM

**Comment by quinton-hoole** [comment]
This PR seems to have introduced a large number of e2e test failures.  
Most of them manifest as:

"cannot allocate resources of type serviceipallocation at this time"

from:

https://github.com/GoogleCloudPlatform/kubernetes/blob/51750a4680cbb161b068b7748c8d00cacb8a893a/pkg/registry/service/allocator/etcd/etcd.go#L147

We're considering rolling this PR back as a result.

**Comment by quinton-hoole** [comment]
Any major objections @fgrzadkowski ?

**Comment by quinton-hoole** [comment]
@lavalamp @davidopp FYI

**Comment by krousey** [comment]
Sorry @fgrzadkowski, we're going to roll this back and hope it improves the stability.

**Comment by fgrzadkowski** [comment]
Thanks, I'll look into this.

**Pull request merged**
