### PR TITLE
cleanup: add i18n.T on kubectl Long usage descriptions

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Ref kubernetes/kubectl#910

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rikatz** [comment]
@pandaamanda can you please rebase?

/triage accepted 
/priority backlog

**Comment by pandaamanda** [comment]
@rikatz  rebased.

**Comment by pandaamanda** [comment]
PTAL, tks.
/assign @smarterclayton  @pwittrock

**Comment by apelisse** [comment]
is there an issue tracking all the places where we need to do that, or are these the only location that don't have it?

**Comment by rikatz** [comment]
It seems there's a non tracking issue in kubectl repo, but I agree maybe tracking this (or having a batch PR instead of a lot of split ones) would be much better

**Comment by apelisse** [comment]
https://github.com/kubernetes/kubectl/issues/910

Is this the kubectl issue you're referring to?

**Comment by rikatz** [comment]
> [kubernetes/kubectl#910](https://github.com/kubernetes/kubectl/issues/910)
> 
> Is this the kubectl issue you're referring to?

yes, which apparently is closed. I just got your comment and went through issue description to see if there was a related issue.

**Comment by apelisse** [comment]
Thanks, I'm not planning on leading this effort, but strongly suggest someone does, including: testing, proper process so that we don't "forget" to document specific strings, how are we getting the translations in etc.

Let me know if I need to approve/lgtm anything.

**Comment by rikatz** [comment]
Thanks @apelisse 

Yeah, I'm not putting my step forward on this effort right now, because I'm pretty out of bandwidth but I can for sure take this PR + the issues to the next sig-cli meeting so we can decide what to do.

Anyway it seems there's no rush on those i18n 

I'll put a hold until the discussion

/hold

**Comment by rikatz** [comment]
/lgtm cancel

I'll start raising the i18n issue and process migration this week, then we can return into this

**Comment by rikatz** [comment]
@pandaamanda I'm going to close this PR, as there probably will be a new KEP about the translations of kubectl commands :)

Anyway thanks for the effort!!!

/close

**Pull request closed without merging**
