### PR TITLE
Update go.mod for go 1.23

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

xref https://github.com/kubernetes/release/issues/3650

* Updates go.mod files to use go1.23
* Updates go.mod files to indicate go1.23 runtime compatibility settings should be used (`godebug default=go1.23`); this change will be picked to release branches and adjusted to match the original go minor version for the release branch

Includes https://github.com/kubernetes/gengo/pull/281 required when running with go1.23 runtime defaults

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@liggitt we need to fix this line

https://github.com/kubernetes/kubernetes/blob/139cc3c659dd1624f7a4bbcc3b07fda79539677a/staging/src/k8s.io/kms/internal/plugins/_mock/Dockerfile#L15

**Comment by liggitt** [comment]
hrmm...

> 2024/09/10 16:29:41 Failed executing local generator: some targets had errors: type k8s.io/api/admissionregistration/v1alpha1.NamedRuleWithOperations cannot be converted to protobuf: unable to embed type "k8s.io/api/admissionregistration/v1alpha1.RuleWithOperations" as field "ruleWithOperations" in "k8s.io/api/admissionregistration/v1alpha1.NamedRuleWithOperations": did not recognize the provided type

**Comment by dims** [comment]
> and adjusted to match the original go minor version for the release branch

+100

**Comment by dims** [comment]
/approve
/lgtm

/hold

(please remove hold when ready! adding it just in case you needed more reviewers)

**Comment by SuperQ** [comment]
This kind of change breaks Go version support. The [`go` directive is a _minimum_ support specification](https://go.dev/ref/mod#go-mod-file-go). Currently Go 1.22 is still supported, which means any user still using the Go 1.22 compiler is forced to update ahead of the support schedule.

In the future, please take care to follow the Go support schedules and not change the minimum supported Go version until it is EoL.

**Comment by dims** [comment]
@SuperQ this is conscious decision, not an arbitrary one. We work closely with the go team and know exactly what the schedules are. 

please feel free to read:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3744-stay-on-supported-go-versions
- https://github.com/kubernetes/enhancements/issues/3744

thanks!

**Pull request merged**
