### PR TITLE
Fix panic when AlphaFeatureGate isn't configured for gcp.

### LINKED ISSUE #56009: invalid memory address or nil pointer dereference when creating a PersistentVolumeClaim on GCP
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
An error occured when creating a PersistentVolumeClaim on a single node cluster created with kubeadm. The cluster is created by following [Kelsey Hightower's tutorial](https://github.com/kelseyhightower/kubeadm-single-node-cluster)
The PersistentVolumeClaim remains _Pending_ and we see the following errors in the log of the _kube-controller-manager_:
```
E1119 07:37:19.250536       1 goroutinemap.go:166] Operation for "provision-default/mypvc[584905c8-ccfc-11e7-b129-42010a840006]" failed. No retries permitted until 2017-11-19 07:37:27.250512635 +0000 UTC (durationBeforeRetry 8s). Error: recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:1094
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:816
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_disks.go:296
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/gce_util.go:183
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go:382
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1313
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1210
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:130
/usr/local/go/src/runtime/asm_amd64.s:2197
E1119 07:37:34.250371       1 goroutinemap.go:166] Operation for "provision-default/mypvc[584905c8-ccfc-11e7-b129-42010a840006]" failed. No retries permitted until 2017-11-19 07:37:50.250352128 +0000 UTC (durationBeforeRetry 16s). Error: recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:1094
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go:816
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_disks.go:296
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/gce_util.go:183
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go:382
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1313
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1210
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:130
/usr/local/go/src/runtime/asm_amd64.s:2197
```

**What you expected to happen**:
A Persistent Volume is created and ready to use

**How to reproduce it (as minimally and precisely as possible)**:
- create a single node cluster on gce with kubeadm, eg [Kelsey Hightower's tutorial](https://github.com/kelseyhightower/kubeadm-single-node-cluster)
- create a StorageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gold
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```
- create a PersistentVolumeClaim
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gold
```

**Anything else we need to know?**:
We are also having this issue on a cluster we try to create from scratch on GCE using CentOS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Ubuntu 17.04
- Kernel (e.g. `uname -a`): Linux kubeadm-single-node-cluster 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
When AlphaFeatureGate isn't configured, the pointer will be nil. This PR fixes it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56009

**Special notes for your reviewer**:
cc @jsiebens 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
I guess this should be cherry-picked to 1.8 as well.

**Comment by yujuhong** [comment]
`AlphaFeatureGate` is exported and there are other components (e.g., ingress) using it. How about changing `GCECloud` to always initialize the feature gate to avoid hitting this accidentally?

**Comment by xiangpengzhao** [comment]
>AlphaFeatureGate is exported and there are other components (e.g., ingress) using it. How about changing GCECloud to always initialize the feature gate to avoid hitting this accidentally?

@yujuhong Good point :+1: ! I see below code in ingress-gce. Yes it has the same risk of panic as the issue #56009. It'd be safe to always initialize the feature gate.
https://github.com/kubernetes/ingress-gce/blob/74bbb015ad75fdb6eb0166068c9ec4936131017f/cmd/glbc/main.go#L293-L294
```go
	enableNEG := cloud.AlphaFeatureGate.Enabled(gce.AlphaFeatureNetworkEndpointGroup)
	ctx := context.NewControllerContext(kubeClient, *watchNamespace, *resyncPeriod, enableNEG)
```

**Comment by xiangpengzhao** [comment]
@yujuhong updated. PTAL. Thanks!

**Comment by yujuhong** [comment]
/lgtm
Need approval from @nicksardo or @bowei 
And milestone approval from @thockin or @abgworrall

**Comment by nicksardo** [comment]
Thanks @xiangpengzhao. Feel free to assign me for the 1.8 cherrypick.

**Comment by xiangpengzhao** [comment]
@nicksardo cherrypick https://github.com/kubernetes/kubernetes/pull/56160 sent. PTAL. Thanks!

**Comment by xiangpengzhao** [comment]
@nicksardo @yujuhong As 1.9 branch has been cut and it's in code slush now, will this PR be in 1.9? or do I need to cherry-pick it to 1.9?

**Comment by yujuhong** [comment]
No need to cherrypick to 1.9. We just need a `status/approved-for-milestone` label. 
I've already pinged @abgworrall (sig-gcp lead). I'll apply the label unless he has objections.

**Comment by abgworrall** [comment]
No objections, label away

**Pull request merged**
