### PR TITLE
Update cAdvisor dependency.

### PR DESCRIPTION
**Pull request by vmarmol**
Brings with it:
- Lower logging
- Better event storage and management
- Support for container labels

/cc @vishh @rjnagal @dchen1107

### CODE REVIEW

**Comment by vmarmol** [comment]
Running e2e, all is clean so far.

**Comment by vmarmol** [comment]
All e2e tests pass.

**Comment by rjnagal** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM. Thanks for fixing logging. :-)

**Pull request merged**
