### PR TITLE
Use v0.0.0 gitVersion on branches in support of new .gitattributes solution.

### PR DESCRIPTION
**Pull request by david-mcmahon**
Update bad link as well.
Prefer master branch untyped values.

ref #55353

### CODE REVIEW

**Comment by enisoc** [comment]
Is this needed to unbreak something, or is it just long-term cleanup? Can it wait until after the 1.6.13 cut tomorrow?

**Comment by david-mcmahon** [comment]
It's a bit of fallout from #55353 (leave versions as is vs. zero'ing them out).   I had hoped this minor nit would be ignored, but @cblecker  noticed on 1.8 yesterday so I'm cleaning all of these up.  It can certainly wait.

**Comment by enisoc** [comment]
The error is the following in TestAggregatedAPIServer:

```
apiserver_test.go:353: an error on the server ("Error: 'x509: certificate signed by unknown authority'\nTrying to reach: 'https://kubernetes.default.svc/api'") has prevented the request from succeeding
```

This only happens on pull jobs, and not on the CI job. I also can't reproduce the problem locally. The test on master does something completely different.

Since 1.6 is technically end-of-life, I'm just going to ignore this error (assuming it's due to a change in the test env for PRs) rather than ask people to spend time diagnosing it.

**Pull request merged**
