### PR TITLE
Automated cherry pick of #13114 #13528

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #13114 #13528 on release-1.0.

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot unit test this please

This should hopefully fix `kubernetes-pull-test-unit-integration` on release-1.0.

**Comment by jlowdermilk** [comment]
lgtm

**Comment by ixdy** [comment]
Probably not strictly necessary, but without #14298 the unit test output is pretty verbose.

Also this may or may not work without #14024 - we'll see, I guess.

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by jlowdermilk** [comment]
@ixdy, looks like this fixes it. unit/integration passes and test results were produced.

**Pull request merged**
