### PR TITLE
change directory permissions from 0755 to 0750

### PR DESCRIPTION
**Pull request by yanghaichao12**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
change directory permissions from 0755 to 0750

Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE

### CODE REVIEW

**Comment by RenaudWasTaken** [comment]
@yanghaichao12 if you want this merged, you need to rebase

**Comment by yanghaichao12** [comment]
@RenaudWasTaken hi, it's done

**Comment by RenaudWasTaken** [comment]
/lgtm

For approval:
/assign @jiayingz @ConnorDoyle @vishh

**Pull request merged**
