### PR TITLE
AWS: Support wheezy, for parity with GCE

### PR DESCRIPTION
**Pull request by justinsb**
GCE uses Debian Wheezy, and I've hit some issues with Ubuntu (particularly around btrfs) where it would be nice to be on the same software stack as GCE.  Having the default configuration be the same means AWS should get the benefit of all of GCE's testing :-)

### CODE REVIEW

**Comment by mikedanese** [comment]
Out of curiosity, what was the motivation for trying to use btrfs? What problems were you having?

**Comment by justinsb** [comment]
btrfs was the only configuration I found that really worked at all with 14.04 LTS, although it may be that this predates our current method of installing Docker.  Without btrfs, I was always hitting the "no such file/device" error.

With btrfs, it worked but I would eventually hit the problem where the disk filled up, Docker crashed, and it could only be fixed by deleting all the btrfs subvolumes and starting again.

I'm not sure I was installing aufs correctly, so I'm hoping that by having the option to choose storage methods & a few operating systems I can actually figure out which configuration is best.

If there is a recommended known good configuration, I would love to know what it is!

I think btrfs on recent kernels is actually pretty good, and has a lot of features that make it really well suited to running container images.  The sensible long-term options look like LVM thin-provisioning (devicemapper) and btrfs, and I personally still prefer btrfs.   However running on some of the older kernels remains problematic.

**Comment by justinsb** [comment]
Rebased to remove the (deliberately introduced) conflict :-)

**Comment by cjcullen** [comment]
LGTM

**Comment by krousey** [comment]
@justinsb I think this needs another rebase.

**Comment by justinsb** [comment]
Thanks - rebased!

**Comment by justinsb** [comment]
I added a commit that reverted the change of default OS, so that the default remains as Ubuntu (14.04).

I would love to have a discussion about what the best choice of storage (aufs/btrfs/overlayfs/devicemapper) and OS is.  I will open a separate bug.

Reasons for not changing the default to Debian:  Ubuntu makes it a little easier to switch to a newer but still semi-supported kernel; so we can get a kernel where btrfs is (more) stable.  Ubuntu has been the default on AWS up until now, and it feels wrong to make such a big switch now (without separate discussion).

**Comment by cjcullen** [comment]
Still LGTM.

**Pull request merged**
