### PR TITLE
Update crictl to v1.11.0.

### PR DESCRIPTION
**Pull request by Random-Liu**
Update `crictl` to newly released v1.11.0 version on GCE. See https://github.com/kubernetes-incubator/cri-tools/releases/tag/v1.11.0

**Release note**:

```release-note
Update crictl on GCE to v1.11.0.
```
@kubernetes/sig-node-pr-reviews @feiskyer @yujuhong @dchen1107

### CODE REVIEW

**Comment by jberkus** [comment]
This does, in fact, need a release note for the version change.  Please fix?

**Comment by dims** [comment]
@Random-Liu i've filed a cherry pick for you. Can you please add a release note for this please?

**Comment by Random-Liu** [comment]
> Can we put a release note in anyway? Noting the version change will help folks off GCE using CRI-O know to upgrade to the new release version.

@jberkus Done.

**Pull request merged**
