### PR TITLE
ignore duplicate resource in create rolebinding

### PR DESCRIPTION
**Pull request by xilabao**

### CODE REVIEW

**Comment by ymqytw** [comment]
@k8s-bot ok to test

**Comment by ymqytw** [comment]
@xilabao The change LGTM. But is there a issue discussing why we should ignore duplicates?

**Comment by xilabao** [comment]
@ymqytw we ignore the duplicate rules in create roles (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/create_role.go#L252). I think we could do the similar thing for rolebinding.

**Comment by ymqytw** [comment]
@xilabao So this is considered as a bug?
cc: @deads2k @xingzhou

**Comment by ymqytw** [comment]
@deads2k Please remove the `do-not-merge` label.

**Comment by ymqytw** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
