### PR TITLE
Automated cherry pick of #65342: update NPD version to v0.5.0 for gci

### PR DESCRIPTION
**Pull request by dashpole**
Cherry pick of #65342 on release-1.10.

#65342: update NPD version to v0.5.0 for gci

### CODE REVIEW

**Comment by dashpole** [comment]
This is to help mitigate https://github.com/kubernetes/kubernetes/issues/45419 on gci, by creating a condition when the unregister_netdevice error occurrs frequently.

**Comment by dashpole** [comment]
/release-note-none
/assign @Random-Liu 
for lgtm
/assign @vishh 
for approval
/assign @MaciekPytel
for milestone and cherrypick approval

**Comment by MaciekPytel** [comment]
@dashpole Can you add a release note to #65342 (for automated cherry-picks the note is taken from parent PR), containing an information what changes in new version? Otherwise lgtm.

**Comment by dashpole** [comment]
@MaciekPytel done

**Comment by dashpole** [comment]
/sig gcp
probably makes more sense actually

**Pull request merged**
