### PR TITLE
fix error message of custrom resource validation

### PR DESCRIPTION
**Pull request by CaoShuFeng**
/assign @deads2k 
/assign @sttts 

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/lgtm

Came across this in https://github.com/kubernetes/kubernetes/issues/53379 as well.

**Comment by nikhita** [comment]
Maybe this should be cherry picked to 1.7 and 1.8 too.

**Comment by CaoShuFeng** [comment]
> Maybe this should be cherry picked to 1.7 and 1.8 too.

How can I do this?
Is there any doc?

**Comment by nikhita** [comment]
> Is there any doc?

https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md#how-do-cherrypick-candidates-make-it-to-the-release-branch under "INDIVIDUAL CHERRYPICKS".

**Pull request merged**
