### PR TITLE
 fix pod infra containers oom-score-adj testing

### LINKED ISSUE #82771: [Failing Test] [sig-node] pod infra containers oom-score-adj should be -998 and best effort container's should be 1000
**Which jobs are failing**:
ci-kubernetes-node-kubelet-serial

**Which test(s) are failing**:
[k8s.io] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup pod infra containers oom-score-adj should be -998 and best effort container's should be 1000

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:
```
framework.ServeHostnameImage started with  the process of agnhost 
```
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
framework.ServeHostnameImage started with  the process of agnhost

**Which issue(s) this PR fixes**:

Fixes #82771

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
Thanks for looking into this! Ran the tests locally, and now they pass! :smile: 

/lgtm

**Comment by oomichi** [comment]
According to https://github.com/kubernetes/kubernetes/commit/c752ea8134bfd5f46996aca22215c7fa2c84c43c#diff-eb7b79470992813ea1905e96c298b47b
this change seems good for me.

/approve

**Pull request merged**
