### PR TITLE
pod will be created only after pod termination

### LINKED ISSUE #58814: Pods recreated without waiting for termination with strategy.type=Recreate
/kind bug
/sig scheduling
/sig autoscaling

**What happened**:

Created a deployment with strategy.type=Recreate. Deleted a pod created by that deployment. Ran kubectl get pods. See the old pod being terminated and a new one being created.

This is an issue for pods that should only have one running instance.

Also same problem when using RollingUpdate strategy with maxSurge=0 and maxUnavailable=1.

**What you expected to happen**:

Expected for Kubernetes to wait for the old pod to be completely terminated.

**How to reproduce it (as minimally and precisely as possible)**:

Should be easy to reproduce with a pod that takes a while to terminate.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11-gke.1", GitCommit:"3500f53730c1fea7b57901977df165c3eb317bce", GitTreeState:"clean", BuildDate:"2017-12-08T18:05:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GCP

### PR DESCRIPTION
**Pull request by poonai**
**What this PR does / why we need it**:
pod will be created only after the pod terminated completely for recreate strategy. 
**Which issue(s) this PR fixes**:
Fixes #58814

**Special notes for your reviewer**:

**Release note**:

```release-note
pod will be created only after the pod terminated completely for recreate strategy
```

### CODE REVIEW

**Comment by sch00lb0y** [comment]
@k8s-bot cla test

**Comment by sch00lb0y** [comment]
@caesarxuchao @ingvagabund @tnozicka @lavalamp please review.

**Comment by krmayankk** [comment]
@sch00lb0y i think the behavior is not defined for recreate clearly, but i guess i agree that we should make sure the pods should be terminated fully before new ones are brought up .WDYT @kargakis @janetkuo ?

**Comment by tnozicka** [comment]
https://github.com/kubernetes/kubernetes/issues/58814#issuecomment-368036027

Making RS to know about / observe Deployments seems like bad coupling to me.

**Comment by kargakis** [comment]
> Making RS to know about / observe Deployments seems like bad coupling to me.

+1

**Comment by sch00lb0y** [comment]
>I  understand Recreate strategy as the way/policy to create pods while  changing from one RS to another on upgrade and it already waits there  for no old pods to be running. If you want that guarantee between pods  with the same revision, StatefulSet does that.
>Making RS to know about / observe Deployments seems like bad coupling to me.

closing this

**Pull request closed without merging**
