### PR TITLE
Fix broken SELinux detection

### LINKED ISSUE #83679: SELinux Volumes not relabeled in 1.16, test coverage of volume relabeling is lacking
**What happened**:
After upgrading from kubelet 1.15 -> 1.16, volumes are no longer relabeled as container_file_t for selinux, causing most pods to fail.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
* Run a kubernetes cluster on 1.15.[0-3]. 
* Create a pod with a secret, configmap, or with provisioned storage (ebs-csi-driver). 
* Find that file on disk of the node, and observe it is labeled with the file type container_file_t and the pod is able to read it.
* Upgrade the kubelet to 1.16
* Delete the pod, and observe it fail on launch. Find the file on disk and see it labeled tmpfs_t or unlabeled_t for configmap/secret and provisioned volumes, respectively.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15 / 1.16
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): RHEL 7.7
- Kernel (e.g. `uname -a`): 3.10.0-1062.1.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others:

### PR DESCRIPTION
**Pull request by simonswine**
The upgrade of dependencies in #78187 introduced a regression in
detecting if SELinux is enabled or not. As the library requires
the golang build tag `selinux` to be enabled after that version update.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The dependency update PR #78187 broke SELinux detection

All versions since that change have problems starting pods on SELinux enabled hosts

**Which issue(s) this PR fixes**:

Fixes #83679

**Special notes for your reviewer**:

I am not too much of an bazel/gazelle expert and I am not too sure what other implications my changes might have.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

https://github.com/kubernetes/kubernetes/commit/51177c1ebbb105e354e114a56fa12cc2aee0993e

Before regression: https://github.com/opencontainers/selinux/blob/4a2974bf1ee960774ffd517717f1f45325af0206/go-selinux/selinux.go#L1

With regression, requiring the build tag: https://github.com/opencontainers/selinux/blob/v1.2.2/go-selinux/selinux_linux.go#L1

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve

@kubernetes/patch-release-team @guineveresaenger This should get CP'd into 1.16/1.17

**Comment by liggitt** [comment]
I would like to see a test added that would have caught this regression.

**Pull request merged**
