### PR TITLE
fix broken links to KEPs in swagger.json

### PR DESCRIPTION
**Pull request by oke-py**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Pod reference contains broken links to KEP.

**Which issue(s) this PR fixes**:

ref https://github.com/kubernetes/website/issues/26168

**Special notes for your reviewer**:

The same links exist in the files below. They should be modified manually?
```
$ git grep -l "https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md"
staging/src/k8s.io/api/core/v1/generated.proto
staging/src/k8s.io/api/core/v1/types.go
staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
staging/src/k8s.io/api/node/v1alpha1/generated.proto
staging/src/k8s.io/api/node/v1alpha1/types.go
staging/src/k8s.io/api/node/v1alpha1/types_swagger_doc_generated.go
staging/src/k8s.io/api/node/v1beta1/generated.proto
staging/src/k8s.io/api/node/v1beta1/types.go
staging/src/k8s.io/api/node/v1beta1/types_swagger_doc_generated.go
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/testdata/swagger.json
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json
```
```
$ git grep -l "https://git.k8s.io/enhancements/keps/sig-network/0007-pod-ready%2B%2B.md"
pkg/apis/core/types.go
staging/src/k8s.io/api/core/v1/generated.proto
staging/src/k8s.io/api/core/v1/types.go
staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/testdata/swagger.json
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json
```
```
$ git grep -l "https://git.k8s.io/enhancements/keps/sig-node/20190226-pod-overhead.md"
pkg/apis/core/types.go
pkg/apis/node/types.go
staging/src/k8s.io/api/core/v1/generated.proto
staging/src/k8s.io/api/core/v1/types.go
staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
staging/src/k8s.io/api/node/v1alpha1/generated.proto
staging/src/k8s.io/api/node/v1alpha1/types.go
staging/src/k8s.io/api/node/v1alpha1/types_swagger_doc_generated.go
staging/src/k8s.io/api/node/v1beta1/generated.proto
staging/src/k8s.io/api/node/v1beta1/types.go
staging/src/k8s.io/api/node/v1beta1/types_swagger_doc_generated.go
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/testdata/swagger.json
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[Other doc]: https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/
```

### CODE REVIEW

**Comment by yliaog** [comment]
the file is automatically generated, please take a look at k8s.io/kube-openapi/cmd/openapi-gen/

**Review by Cheef5 — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
