### PR TITLE
add supported proxymodes in componentconfig

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:
kube-proxy now support four proxymode, but we only defined two in componmentconfig.
We should extend the definition in it.
And declare kernelspace is supported for windows in help message.

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
A duplication of #53780? FYI.

**Comment by Mashimiao** [comment]
hmm, seems not total duplication of #53780. If #53780 landed first, I can rebase my PR.

**Comment by Mashimiao** [comment]
rebased. @liggitt  @nikhiljindal  PTAL

**Comment by m1093782566** [comment]
Please check the HEAD, I think the change is already there?

**Pull request closed without merging**
