### PR TITLE
Automated cherry pick of #80942: Fix a bug in the IPVS proxier where virtual servers are not

### PR DESCRIPTION
**Pull request by andrewsykim**
Cherry pick of #80942 on release-1.13.

#80942: Fix a bug in the IPVS proxier where virtual servers are not

### CODE REVIEW

**Comment by andrewsykim** [comment]
There's more context in https://github.com/kubernetes/kubernetes/pull/80942, but adding some here for reviewers:

A few releases ago the IPVS proxy added graceful termination support, mainly because removing an IPVS backend also deletes all of it's connections, unlike the iptables proxy which persists the connection even after the endpoint is removed.

This mainly fixes a bug where we don't trigger graceful termination for a deleted Service if it has real servers and as a result, the Service can never be deleted. The following check was problematic and removed as part of this PR:
```
// If we still have real servers graceful termination is not done
if len(rsList) > 0 {
    continue
}
```

When reviewing the PR though, we realized that there's no need to trigger graceful termination at all if a Service is _deleted_.  At that point we shouldn't care about connections terminating and only attempt graceful termination if a backend is removed for an existing Service and so we updated the PR to ignore graceful termination on Service deletion entirely. 

It's worth calling out that graceful termination on Service deletion was initially added because IPVS with sysctl `expire_nodest_conn=0` will silently drop packets of a destination server that is no longer available, so pods would persist connections to a deleted Service. Because in https://github.com/kubernetes/kubernetes/pull/71834 we set `expire_nodest_conn=1`, we don't have to worry about the kernel silently dropping packets for removed backends and we can immediately remove a virtual server along with it's real servers immediately when a Service is deleted.

@lbernail please add more if I missed anything.

/assign @thockin @lbernail  @m1093782566

**Comment by tpepper** [comment]
/kind bug
/priority important-soon
from parent PR

**Comment by thockin** [comment]
Thanks!

/approve

**Pull request merged**
