### PR TITLE
Addresses vSphere Volume Attach limits

### PR DESCRIPTION
**Pull request by dagnello**
This PR resolves bug #29878.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29881)

### CODE REVIEW

**Comment by dagnello** [comment]
@mikedanese can I get release 1.3 on this PR?  It addresses a bug fixes related to 1.3 release.  Would like to get this resolved in the next 1.3.x tag.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
cc @abithap @dkalleg @imkin

**Comment by dkalleg** [comment]
@mikedanese Tested and works as advertised, lgtm

**Comment by fabioy** [comment]
@dagnello Cherrypick approved. Please create a cherrypick PR. Thanks.

**Pull request merged**
