### PR TITLE
Setup monitoring using heapster outside of GCE as well.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by jbeda** [comment]
@vishh I just moved this stuff to `cluster/addons`.  It might make sense to have a file there with the start/stop boilerplate.

I'm thinking something like `cluster/addons/cluster-monitoring/addon.sh` or something.

We can then source that and call out to it.

**Comment by jbeda** [comment]
Assign back to me when you are are ready for me to take another look.

**Comment by vishh** [comment]
Ack.

**Comment by bgrant0607** [comment]
@vishh Are you still working on this?

**Comment by vishh** [comment]
Yes I am. I have Grafana working through proxy on apiserver. I will get to
this PR soon.

**Comment by erictune** [comment]
@vishh Are you still working on this?

**Comment by vishh** [comment]
Yeah. The groundwork required for this PR is complete. I will wrap this up
soon.

**Comment by vishh** [comment]
Wrapped up this feature via another PR.

**Pull request closed without merging**
