### PR TITLE
CHANGELOG: two item should merge to one item

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
/CHANGELOG: list should be one item

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by heqg** [comment]
/assign @liggitt
Thanks!

**Comment by liggitt** [comment]
Please combine the change log typo fix PRs into a single commit and PR for easier test/review

**Comment by heqg** [comment]
> Please combine the change log typo fix PRs into a single commit and PR for easier test/review

OK， I have  combine the above change log typo fix PRs into this PR。
pls help me to review or approve this pr。 
Thank you very much.

**Comment by heqg** [comment]
> Please combine the change log typo fix PRs into a single commit and PR for easier test/review

ok， i have combine the above change log  into this pr.
please help to review or merge it. 
thanks.

**Comment by heqg** [comment]
/assign @liggitt
Thanks!

**Review by saschagrunert — CHANGES_REQUESTED** [review]
Changes LGTM. @heqg can you please rebase and drop the merge commit from this PR?

**Comment by heqg** [comment]
> drop the merge commit fro

sorry, by the way ,how to drop the merge commit from this PR?

**Comment by heqg** [comment]
> merge

can you  help to approve it ?thanks

**Comment by heqg** [comment]
> Changes LGTM. @heqg can you please rebase and drop the merge commit from this PR?

can you help to approve it ?thanks

**Comment by saschagrunert** [comment]
> > drop the merge commit fro
> 
> sorry, by the way ,how to drop the merge commit from this PR? can you help me to deal it ,thanks a lot

Yes, you can do an interactive rebase `git rebase -i master` and then drop (`d`) the commits.

**Comment by heqg** [comment]
> > > drop the merge commit fro
> > 
> > 
> > sorry, by the way ,how to drop the merge commit from this PR? can you help me to deal it ,thanks a lot
> 
> Yes, you can do an interactive rebase `git rebase -i master` and then drop (`d`) the commits.


I'm really sorry., I failed to perform the operation.
In addition, after i rebase again , I  have commit another one based on this pr problem. https://github.com/kubernetes/kubernetes/pull/97911

Please help me to reviewed it，and then I will close this pr。
thank very much

**Pull request closed without merging**
