### PR TITLE
Fix name for Pods of NonIndexed Jobs

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Removes generate name from NonIndexed Jobs. Otherwise, the name has the form:

`job-name--1-`

where `-1` comes from the invalid completion index.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This was accidentally added in #101601. I'm pretty sure this is just a cosmetic issue: pods would still be created because podGenerateNameWithIndex already truncates the names to fit the pod name limits.

#### Does this PR introduce a user-facing change?

```release-note
Fix 1.22 regression so pod name of NonIndexed jobs does not include rogue -1 substring
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by travisn** [comment]
What would it take to get this backported to the next 1.22.x release? This is causing pod creation failure with certain job names as seen [here](https://github.com/rook/rook/issues/9294).

**Comment by alculquicondor** [comment]
Oh, please create a cherry-pick https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Comment by travisn** [comment]
In our effort to support all K8s versions, we found a small fix on our side to work with this issue, so it can wait for 1.23 from my perspective.

**Comment by alculquicondor** [comment]
Sg, I'm happy to lgtm if you send the cherry-pick

**Pull request merged**
