### PR TITLE
kubeadm: rename the `kube-dns` phases addon

### LINKED ISSUE #856: rename the `kube-dns` property in `kubeadm alpha phase addon`
the `kube-dns` addon property is being present in `kubeadm alpha phase addon`.

the docs also mention the following:
```
**Please note that if kubeadm is invoked with --feature-gates=CoreDNS=true, CoreDNS is installed instead of kube-dns.**
```
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon

CoreDNS is on by default in 1.11 which suggests that both the docs and the `addon` sub command need to change for that.

TODO:
- rename the addon property to `coredns` in `.....phases/addons.go`.
- document the feature gate change and that the user can install `kube-dns` by setting the feature gate to `false`:
(CoreDNS docs issue:
https://github.com/kubernetes/kubeadm/issues/843#issuecomment-391740086)

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
The command `kubeadm alpha phases addon` has a property
called `kube-dns` which would install kube-dns, pre 1.11.

In the case of 1.11 this property will install CoreDNS,
because the property is also bound to the `CoreDNS` feature gate,
which is now `true` by default.

Fix that by renaming the property to `coredns`, updating the Cobra
info and also updating the unit tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubeadm/issues/856

**Special notes for your reviewer**:
Please verify if we are OK with the "hard rename".

**Release note**:

```release-note
kubeadm: rename the addon parameter `kube-dns` to `coredns` for `kubeadm alpha phases addons` as CoreDNS is now the default DNS server in 1.11.
```

@kubernetes/sig-cluster-lifecycle-pr-reviews 
/area kubeadm

### CODE REVIEW

**Comment by neolit123** [comment]
FYI @timothysc mentioned this on slack:
> Just keep in mind that in 1.12 we are planning to eliminate phases in favor for the sub-commands like `init`

**Review by timothysc — APPROVED** [review]
/approve 

I'm ok with this change, I'll let @detiber have final lgtm.

**Review by luxas — APPROVED** [review]
/lgtm
Thanks @neolit123!

**Pull request merged**
