### PR TITLE
add space for output

### PR DESCRIPTION
**Pull request by ChiuWang**
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by bsalamat — APPROVED** [review]
/lgtm

approval for the scheduler file.

**Comment by nikhita** [comment]
/assign @fabriziopandini 
approval for the kubeadm bits

**Comment by fabriziopandini** [comment]
/lgtm 
For the kubeadm bit

/approve 
Because also the scheduler bit is lgtm

**Pull request merged**
