### PR TITLE
Bump cel-go to v0.11.2

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR is to bump cel-go and indirect dependencies.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @liggitt 
Would you mind to take a look when have time? Thank you^

**Comment by liggitt** [comment]
I assume this is a replay of https://github.com/kubernetes/kubernetes/pull/108954/commits/4c90653d19471f0116cb988872cfdffec2e8e212

updates lgtm, but will need rebumping against master

**Comment by cici37** [comment]
> I assume this is a replay of [4c90653](https://github.com/kubernetes/kubernetes/commit/4c90653d19471f0116cb988872cfdffec2e8e212)
> 
> updates lgtm, but will need rebumping against master

I didn't aware of the same changes there-_-. I have rebased on master^

**Comment by liggitt** [comment]
/lgtm
/approve

dropped a few deps:
```diff
 {
 	"directDependencies": 230,
-	"transitiveDependencies": 262,
-	"totalDependencies": 323,
+	"transitiveDependencies": 258,
+	"totalDependencies": 319,
 	"maxDepthOfDependencies": 29
 }
```

can pick up the other optimization change from https://github.com/kubernetes/kubernetes/pull/108954 in a follow up

cc @jpbetz

**Comment by pacoxu** [comment]
/test pull-kubernetes-integration
Failing test cases are different from the last failing.

**Comment by jpbetz** [comment]
/lgtm
Thanks @cici37 for opening the PR for the CEL base env optimization was well

**Pull request merged**
