### PR TITLE
Adds a new cloud provider - hpe

### PR DESCRIPTION
**Pull request by spradeepv**
**What this PR does / why we need it**: It adds a new cloud provider - hpe

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This plugin gets an external IP from a ipam server and assigns it to the service.
**Release note**:
```release-note
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
We don't want to add any new cloud provider for now. There is an ongoing effort of moving cloud provider from the main repository (kubernetes/kubernetes) and thus from the core kubernetes. This will unblock adding new cloud providers.
If you would be able to help with this effort of moving cloud providers (which would speed up addding the hpe cloud provider) @thockin can probably point you to specific action items.

**Comment by wojtek-t** [comment]
FYI - the decision about cloud providers is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/README.md
And the design for transition to new state is described here:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md

**Comment by spradeepv** [comment]
@wojtek-t Thanks for the information. I will close this PR for now.

**Pull request closed without merging**
