### PR TITLE
Check for pvcVolume with IsOperationPending() before markPVCResizeInProgress()

### PR DESCRIPTION
**Pull request by houjun41544**
…rogress()

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnufied** [comment]
/lgtm

@houjun41544 can you rebase your branch, the PR itself looks good.

**Comment by houjun41544** [comment]
@gnufied I have rebased the branch.

**Pull request merged**
