### PR TITLE
Run hack/run-gendocs.sh to fix issue, otherwise shippable is failed f…

### PR DESCRIPTION
**Pull request by dchen1107**
…or all prs.

cc/ @ArtfulCoder

### CODE REVIEW

**Comment by zmerlynn** [comment]
I think I narrowly beat you with #11474 :)

**Comment by ArtfulCoder** [comment]
waiting for shippable

**Comment by dchen1107** [comment]
I should totally beat you if Brian didn't stop me at the first place.

**Comment by zmerlynn** [comment]
Oh, sure, merge her version. ;)

**Pull request merged**
