### PR TITLE
Fix #8373 add kubectl for cluster validation

### LINKED ISSUE #8373: Missing step of install kubectl in ubuntu doc
Though I have successfully installed kubernetes via [the ubuntu doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md) :smiley: , still want to point out this doc missing the step to install `kubectl`.

Thus, if user just follow the guide in the doc without having much knowledge about kubernetes, he/she would get error "__It looks as if you don't have a compiled kubectl binary__" during the `validate-cluster` step of `kube-up.sh`.

Manually install kubectl on at least master node should be necessary (suggest to let user also install on minion node for convenience), any way, the installation step is [pretty simple](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/kubectl.md).

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
Fix https://github.com/GoogleCloudPlatform/kubernetes/issues/8373. Tested OK!

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
(running e2e on this won't give any useful results, so not responding to the bot)

**Comment by WIZARD-CXY** [comment]
@roberthbailey shall we merge?

**Comment by tobegit3hub** [comment]
This works well for me. We need this in trunk :smiley:

**Comment by roberthbailey** [comment]
Thanks @saad-ali for merging. I was mostly AFK today but figured the lgtm label would prompt the oncall to merge the PR for you.

**Pull request merged**
