### PR TITLE
The e2e tests will re-honor --host option. #8499

### PR DESCRIPTION
**Pull request by rrati**

### CODE REVIEW

**Comment by roberthbailey** [comment]
@jlowdermilk is OOO today, re-assigning to @quinton-hoole

**Comment by quinton-hoole** [comment]
Fixes #8499 (at least in part).

**Comment by quinton-hoole** [comment]
Could you please identify the PR that introduced this regression?
I just want to confirm that we understand how it was introduced, and that this is an appropriate fix for it, as I have no context on why this option was introduced and then removed/broken.

**Comment by quinton-hoole** [comment]
@rrati See above.

**Comment by rrati** [comment]
This looks to have been introduced by this sha:
3f3760a14a0f063cb608c8ff58357819f01739b5
from #8201

**Comment by rrati** [comment]
@quinton-hoole See above.

**Comment by quinton-hoole** [comment]
In that case this does not seem to be the correct fix.  In this PR you're only incorporating one specific field.  What about the rest?  Assigning to @jlowdermilk for further advice, as he's more familiar with this part of the code base.

**Comment by timothysc** [comment]
Please expedite, this has broken e2e in non-gce envs.

**Comment by quinton-hoole** [comment]
@roberthbailey may be able to find someone suitable, as @jlowdermilk is out today.  Assigning to the former.

**Comment by roberthbailey** [comment]
This change looks fine to me. I'll patch it locally and run GCE e2e to make sure it passes and then merge.

**Comment by quinton-hoole** [comment]
Can anyone answer my question as to why this PR merges only one specific field here:

https://github.com/GoogleCloudPlatform/kubernetes/pull/8500/files#diff-8349006db2c242fd7424e1dfb3295840R202

Note that there is currently a merge freeze in place:

https://groups.google.com/forum/#!topic/kubernetes-dev/gGXraJNAcaw

Please do not merge this yet.

Thanks

Q

**Comment by roberthbailey** [comment]
Fair enough. I'm reassigning to you for now then.

**Comment by jlowdermilk** [comment]
This change lgtm. The removal of host override in 3f3760a was not intended, just the deprecated `auth-path` option.

**Comment by timothysc** [comment]
@jlowdermilk could we get a merge once we're unblocked by #8534

**Comment by jlowdermilk** [comment]
Yeah, will merge once freeze ends.

**Comment by timothysc** [comment]
@jlowdermilk | @rrati I believe we can close this one now.

**Pull request merged**
