### PR TITLE
Automated cherry pick of #65330: add rate limiting for NEG calls

### PR DESCRIPTION
**Pull request by freehan**
Cherry pick of #65330 on release-1.11.

#65330: add rate limiting for NEG calls

### CODE REVIEW

**Comment by rramkumar1** [comment]
@freehan We should make sure that GLBC 1.2 gets cherry picked back as well.

**Comment by foxish** [comment]
Is this manually verified and ready for a cherrypick into 1.11.1? @freehan @bowei

**Comment by jdumars** [comment]
I added the cherry-pick-candidate label to the parent PR which is required for the CP approval process.

**Pull request closed without merging**
