### PR TITLE
update the outdated links

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm
/approve no-issue
@k8s-bot ok to test

**Comment by jianglingxia** [comment]
can I resubmit the pr?how to resubmit it ?thanks!

**Comment by nikhita** [comment]
@jianglingxia can you rebase to fix the conflicts? the tests should pass once the conflicts are fixed. :)

**Comment by jianglingxia** [comment]
sorry,the file in the pr has removed to examples module,so I close the pr ,thanks!

**Pull request closed without merging**
