### PR TITLE
fix healthcheck update problem introduced by #41223

### PR DESCRIPTION
**Pull request by freehan**
ref: https://github.com/kubernetes/kubernetes/pull/41223

surgical fix for https://github.com/kubernetes/kubernetes/pull/41223#issuecomment-279120970

### CODE REVIEW

**Comment by freehan** [comment]
@k8s-bot unit test this

**Comment by dcbw** [comment]
LGTM

**Review by dcbw — APPROVED** [review]
LGTM

**Comment by freehan** [comment]
adding LGTM label based on comment

**Pull request merged**
