### PR TITLE
miscellaneous group version updates

### PR DESCRIPTION
**Pull request by deads2k**
A grab bag of minor fixes to bring more of the GroupVersion changes under control.  I'm expecting these to be very non-contentious

@caesarxuchao @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM, travis is broken in master

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this please

**Comment by deads2k** [comment]
@k8s-bot unit test this please

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
