### PR TITLE
fix typo on Evictor's Preempt func

### PR DESCRIPTION
**Pull request by Gekko0114**
#### What type of PR is this?
/kind bug
/kind documentation

#### What this PR does / why we need it:
Fixed typo.

#### Special notes for your reviewer:
Thank you for reviewing this PR.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Comment by sanposhiho** [comment]
/title fix typo on Evictor's Preempt func

**Comment by sanposhiho** [comment]
/retitle  fix typo on Evictor's Preempt func

**Review by rasooll — APPROVED** [review]

**Comment by Gekko0114** [comment]
Hi @ahg-g,
Could you take a look?
/assign ahg-g

**Pull request merged**
