### PR TITLE
Add SSH_OPTS support in cluster/ubuntu/config-default.sh  #17934

### LINKED ISSUE #17934: SSH/SCP options customization for ubuntu install
Hi,

Right now in the installation script for Ubuntu there are hardcoded SSH_OPTS. In my case I am using a custom SSH port, and, unless I am mistaken, I have no way to customize it, either globally or on a per-host basis. Would it be possible to do that? I can try to submit a patch if necessary.

Thanks.

### PR DESCRIPTION
**Pull request by lojies**
Add SSH_OPTS support.This can change ssh and scp default port.

fixes #17934

### CODE REVIEW

**Comment by lojies** [comment]
@mikedanese

**Comment by lojies** [comment]
I signed it!

**Comment by lojies** [comment]
@k8s-merge-robot

**Comment by lojies** [comment]
@mikedanese can this be test or i need to do some changes.

**Comment by bgrant0607** [comment]
cc @resouer

**Comment by bgrant0607** [comment]
ok to test

**Pull request closed without merging**
