### PR TITLE
Convert private.sh test to Go and remove basic.sh and private.sh

### PR DESCRIPTION
**Pull request by satnam6502**
This PR is part of the Issue #3130 effort to re-write the bash end-to-end tests in Go. This PR adds a test in Go that replaces `publish.sh` and it removes the files `basic.sh` and `public.sh`. I observed that `KUBERNETES_PROVIDER` is not always set so I pass this in via a flag and add it to the test context. I have also increased the test timeout for the Go e2e tests to 10 minutes. @filbranden @lavalamp @roberthbailey @zmerlynn 

As a point of principle, I think we should move away from making direct use of environment variables in these end to end tests and use instead a pre-populated context structure.

### CODE REVIEW

**Comment by filbranden** [comment]
Looks good, merging.

Agree on your point about moving away from environment variables, hopefully we're making progress towards that goal.

Cheers,
Filipe

**Comment by zmerlynn** [comment]
Do you have any plans for changing the test driver to be less dumbly
integrated with Jenkins? If you continue down this path, it's just going to
keep looking like all of our tests are gone and goe2e.sh is going to get
longer and longer. I'd prefer a route that plays nicely with hack/e2e.go,
even in the short term.

**Comment by zmerlynn** [comment]
(I think you replied to this on another thread, but there's a half dozen at
this point.)

**Comment by filbranden** [comment]
@zmerlynn I'm not really familiar with Jenkins but from the looks of it right now Jenkins just calls a single script `hack/jenkins/build.sh` which is then calling `hack/e2e.go` which runs all the tests in sequence. I guess somehow Jenkins can tell from the output which tests failed/succeeded.

How is that different from a single `cmd/e2e/e2e.go` that runs all the tests in sequence/in parallel and reports on the success/failure of each of them? Isn't that equivalent?

I guess we can talk more about how Jenkins works and what's required to make it work with the new test framework.

I think Jenkins integration is certainly important but I wouldn't block on the refactor since even if Jenkins only reports a single success/failure we can still go to the logs to understand which were the tests that failed.

Or am I missing something?

**Comment by zmerlynn** [comment]
`hack/jenkins/e2e.sh` calls `hack/e2e.go` with `-tap`, which gives TAP (Test Anything Protocol) grid output at an individual test granularity. You're losing that right now, making it less transparent to see what's going on.

It would be easy enough to run each of the go e2e tests separately with a thumbs up/down to get the TAP output for each, then I'd also add an option to disable timeout and let Jenkins actually use *its* timeout, which is covering all the existing tests.

**Comment by filbranden** [comment]
Ah ok I see... In that case, you might be interested in #3545 which should allow you to break `goe2e.sh` into multiple separate scripts, one for each of the Go e2e tests.

**Comment by zmerlynn** [comment]
This is an example the TAP Results Page.

image

**Comment by zmerlynn** [comment]
I'm actually busy with other stuff, crazily enough, and the path you're on increases the cognitive load anytime someone has to look at the build to figure out what's broken, which is why I'm asking for a plan to fix it.

**Comment by filbranden** [comment]
I think actually the best path forward is to make `cmd/e2e/e2e.go` support `-tap` as well, which we can use in `goe2e.sh`. This is consistent with our goal of getting rid of the shell script tests and is what we want long term anyways. I'll take a look at that, if it's as easy as I expect it will be I'll send you a PR for it tomorrow.

Cheers,
Filipe

**Comment by zmerlynn** [comment]
There's actually support for TAP in there already. (That's what it's
outputting.) It's not actually the best TAP in the world (in particular,
it's not terrible *useful* TAP - the std{out,err} that was spewed is lost),
but it actually is TAP. (There's another page I didn't show that has the
whole test stdout/stderr once you drill down, for failures.)

You then get into a fun set of plumbing issues. You can either try to
integrate it in as subtest output in hack/e2e.go somehow (see
https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin for what I mean
about subtests), or you could somehow output a separate TAP file as part of
the e2e process and Jenkins can slurp it up, too.

**Comment by zmerlynn** [comment]
At the end of the day, you're actually going to want to merge a lot of the stuff we did in `hack/e2e` into `cmd/e2e`. :/ I should port my random shuffler pretty soon before the tests get too accidentally reliant on order.

**Comment by zmerlynn** [comment]
I have a proposal for a bridge between two worlds:

1. You add an `--except` to `hack/e2e.go` so that things can be excluded from wildcard pickups, so that Jenkins can call `hack/e2e.go --except=goe2e.sh`
2. One of us changes `hack/jenkins/e2e.tap` to call cmd/e2e/e2e.go directly, putting TAP output in a separate file in a similar fashion to the `e2e.$BLAH.tap` in there today. (call it go-e2e.$BLAH.tap, maybe?)
3. We reconfigure Jenkins to pickup both tap files (trivial)

Then it's easy to drain one pool and add to the other. It also fixes an annoyance I've had for a while, which is that anytime goe2e.sh fails-via-timeout, it destroys other tests. This way, it's run last.

**Pull request merged**
