### PR TITLE
agnhost: Check symlink target's permissions for Windows

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug

/sig testing
/sig windows
/priority important-soon
/milestone v1.25

#### What this PR does / why we need it:

We're not interested in checking the file permissions of the symlink itself, but it's target's permissions.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsturtevant** [comment]
do this fix a particular test?

**Comment by claudiubelu** [comment]
> do this fix a particular test?

Not right now, since we don't test any type of file permissions on Windows. I've split it of a previous PR: https://github.com/kubernetes/kubernetes/pull/104660

**Comment by marosset** [comment]
LGTM (especially give that we have another PR that addresses file permission issues in the codebase).

**Review by marosset — APPROVED** [review]
/lgtm

Thanks @claudiubelu!

**Comment by yselkowitz** [comment]
Anyone planning on promoting agnhost:2.40 so that kubernetes tests can move to it?

**Pull request merged**
