### PR TITLE
Fix a typo in kubeadm/GetEtcdPodSpec

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Fix a typo in kubeadm/GetEtcdPodSpec.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
Thanks @cimomo!
/lgtm
/approve no-issue

**Comment by cimomo** [comment]
Thank you @luxas  :)

**Comment by cimomo** [comment]
@luxas Could this be merged? Thanks.

**Pull request merged**
