### PR TITLE
Run Docker containers as top-level containers in Debian.

### PR DESCRIPTION
**Pull request by vmarmol**
This should fix the issue for GCE/GKE, I'll work on libcontainer/Docker changes to fix overall.

Part of #8215

/cc @rjnagal @dchen1107 

Ran e2e and the run came back green!

### CODE REVIEW

**Comment by rjnagal** [comment]
I wish there was a way to single out GKE from Debian, as Debian has systemd enabled in the latest version.

Looking around ...

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
PTAL @rjnagal this is ready to go I believe. We can improve the OS family detection later. I will also try to get the necessary changes into Docker 1.7.

**Comment by rjnagal** [comment]
ok, let's go with this for now.

LGTM

**Comment by dchen1107** [comment]
@vmarmol sorry about you have to rebase it again.

**Comment by vmarmol** [comment]
@dchen1107 no worries! Rebased and re-pushed.

**Comment by dchen1107** [comment]
I kicked out shippable for you again.

**Pull request merged**
