### PR TITLE
quote interpreted string in JSONPath

### PR DESCRIPTION
**Pull request by daizuozhuo**
Added the quote interpreted string function and corresponding doc in #16981 . @thockin @bgrant0607

### CODE REVIEW

**Comment by daizuozhuo** [comment]
@eparis Could you check it?

**Comment by eparis** [comment]
@k8s-bot ok to test
@k8s-bot test this
@k8s-but unit test this

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
I patched this in and it does seem much nicer.  Can you come up with a better title for this PR?

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
