### PR TITLE
e2e dns scale test: Create client pod before scale services

### LINKED ISSUE #64774: New e2e testsuites for DNS scale fail to setup the cluster
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

For these 2 test suites visible in the testgrid at network-gce :
http://k8s-testgrid.appspot.com/sig-network-gce#gce-coredns-performance
http://k8s-testgrid.appspot.com/sig-network-gce#gce-kubedns-performance

the testsuite cannot setup correctly the cluster, due to a firewall issue (I think)
See part of the build log below:

```
I0605 12:39:36.975] NAME                                        STATUS                     ROLES     AGE       VERSION
I0605 12:39:36.976] gce-coredns-performance-master              Ready,SchedulingDisabled   <none>    27s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-377q   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-6w50   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-vf6h   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:37.308] Validate output:
I0605 12:39:37.645] NAME                 STATUS    MESSAGE              ERROR
I0605 12:39:37.646] etcd-1               Healthy   {"health": "true"}   
I0605 12:39:37.646] controller-manager   Healthy   ok                   
I0605 12:39:37.646] scheduler            Healthy   ok                   
I0605 12:39:37.647] etcd-0               Healthy   {"health": "true"}   
I0605 12:39:37.652] Cluster validation succeeded
W0605 12:39:37.752] Done, listing cluster services:
W0605 12:39:37.752] 
I0605 12:39:37.853] Kubernetes master is running at https://35.231.139.160
I0605 12:39:37.955] GLBCDefaultBackend is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
I0605 12:39:37.955] Heapster is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/heapster/proxy
I0605 12:39:37.956] CoreDNS is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
I0605 12:39:37.956] kubernetes-dashboard is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
I0605 12:39:37.956] Metrics-server is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
I0605 12:39:37.956] 
I0605 12:39:37.957] To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
I0605 12:39:37.958] 
I0605 12:40:00.832] NAME                                                             NETWORK                  DIRECTION  PRIORITY  ALLOW            DENY
I0605 12:40:00.832] gce-coredns-performance-minion-gce-coredns-performance-http-alt  gce-coredns-performance  INGRESS    1000      tcp:80,tcp:8080
I0605 12:40:01.785] allowed:
I0605 12:40:01.785] - IPProtocol: tcp
I0605 12:40:01.785]   ports:
I0605 12:40:01.786]   - '80'
I0605 12:40:01.786] - IPProtocol: tcp
I0605 12:40:01.786]   ports:
I0605 12:40:01.786]   - '8080'
I0605 12:40:01.786] creationTimestamp: '2018-06-05T05:39:39.559-07:00'
I0605 12:40:01.786] description: ''
I0605 12:40:01.786] direction: INGRESS
I0605 12:40:01.787] id: '4755345594321156708'
I0605 12:40:01.787] kind: compute#firewall
I0605 12:40:01.787] name: gce-coredns-performance-minion-gce-coredns-performance-http-alt
I0605 12:40:01.787] network: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-prl-flaky/global/networks/gce-coredns-performance
I0605 12:40:01.787] priority: 1000
I0605 12:40:01.787] selfLink: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-prl-flaky/global/firewalls/gce-coredns-performance-minion-gce-coredns-performance-http-alt
I0605 12:40:01.788] sourceRanges:
I0605 12:40:01.788] - 0.0.0.0/0
I0605 12:40:01.788] targetTags:
I0605 12:40:01.788] - gce-coredns-performance-minion
=======
W0605 13:00:04.876] Failed to create firewall gce-coredns-performance-minion-gce-coredns-performance-nodeports in k8s-jkns-e2e-gce-prl-flaky
=======
W0605 13:00:04.878] 2018/06/05 13:00:04 process.go:152: Step './hack/e2e-internal/e2e-up.sh' finished in 26m29.118690007s
W0605 13:00:04.879] 2018/06/05 13:00:04 e2e.go:523: Dumping logs from nodes to GCS directly at path: gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-coredns-performance/4/artifacts
W0605 13:00:04.879] 2018/06/05 13:00:04 process.go:150: Running: ./cluster/log-dump/log-dump.sh /workspace/_artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-coredns-performance/4/artifacts
W0605 13:00:04.924] Trying to find master named 'gce-coredns-performance-master'
W0605 13:00:04.924] Looking for address 'gce-coredns-performance-master-ip'
I0605 13:00:05.025] Checking for custom logdump instances, if any
I0605 13:00:05.025] Sourcing kube-util.sh
I0605 13:00:05.025] Detecting project
I0605 13:00:05.026] Project: k8s-jkns-e2e-gce-prl-flaky
I0605 13:00:05.026] Network Project: k8s-jkns-e2e-gce-prl-flaky
I0605 13:00:05.026] Zone: us-east1-b
I0605 13:00:05.026] Dumping logs from master locally to '/workspace/_artifacts'
W0605 13:00:05.833] Using master: gce-coredns-performance-master (external IP: 35.231.139.160)
I0605 13:00:33.644] Changing logfiles to be world-readable for download
I0605 13:00:36.930] Copying 'kube-apiserver kube-apiserver-audit kube-scheduler rescheduler kube-controller-manager etcd etcd-events glbc cluster-autoscaler kube-addon-manager fluentd startupscript' from gce-coredns-performance-master
W0605 13:00:38.107] 
W0605 13:00:38.108] Specify --start=42264 in the next get-serial-port-output invocation to get only the new output starting from here.
W0605 13:00:41.259] scp: /var/log/cluster-autoscaler.log*: No such file or directory
W0605 13:00:41.333] scp: /var/log/fluentd.log*: No such file or directory
W0605 13:00:41.333] scp: /var/log/startupscript.log*: No such file or directory
W0605 13:00:41.337] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

**What you expected to happen**:
I would think that setup the cluster is part of the process of the test-infra job, not the e2e test itself.

Any missing flag or option on the job definition (see below) ?
Need guidance on how to find the root cause of this error.

**How to reproduce it (as minimally and precisely as possible)**:

Just look at the testgrid, it happen every 6 hours.
http://k8s-testgrid.appspot.com/sig-network-gce#gce-coredns-performance
http://k8s-testgrid.appspot.com/sig-network-gce#gce-kubedns-performance

**Anything else we need to know?**:

job definition is:

```
  "ci-kubernetes-e2e-gce-coredns-performance": {
    "args": [
      "--cluster=gce-coredns-performance",
      "--env=CLUSTER_DNS_CORE_DNS=true",
      "--extract=ci/latest",
      "--gcp-master-image=gci",
      "--gcp-node-image=gci",
      "--gcp-nodes=3",
      "--gcp-zone=us-east1-b",
      "--provider=gce",
      "--test_args=--ginkgo.focus=\\[Feature:PerformanceDNS\\]",
      "--timeout=60m",
      "--use-logexporter"
    ],
    "scenario": "kubernetes_e2e",
    "sigOwners": [
      "sig-network"
    ]
  },

```

NOTE: this job definition was copied from another one that seems working fine:

```
  "ci-kubernetes-e2e-gci-gce-coredns": {
    "args": [
      "--check-leaked-resources",
      "--cluster=",
      "--env=CLUSTER_DNS_CORE_DNS=true",
      "--extract=ci/latest",
      "--gcp-zone=us-central1-f",
      "--ginkgo-parallel=30",
      "--provider=gce",
      "--test_args=--ginkgo.skip=\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8",
      "--timeout=150m"
    ],
    "scenario": "kubernetes_e2e",
    "sigOwners": [
      "sig-network"
    ]
  },
```

**Environment**:
- Kubernetes version (use `kubectl version`): current (branch master)
- Cloud provider or hardware configuration: gce

### PR DESCRIPTION
**Pull request by chrisohaver**
**What this PR does / why we need it**:

Move client pod creation to before scale service creation. 
In my local tests, this fixes #64774.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@chrisohaver - the fact that something passed once in the other order doesn't mean that you weren't lucky.
We should first understand what was causing that to fail in previous shape before making this change.

**Comment by chrisohaver** [comment]
Per scalability team - we should split the services into two namespaces to avoid the (recently discovered) limitation of services per namespace.

**Pull request closed without merging**
