### PR TITLE
coreos/azure bump etcd version to v2.1.0-alpha.0

### PR DESCRIPTION
**Pull request by idoshamun**

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm. /cc @errordeveloper

**Comment by errordeveloper** [comment]
@idosh thanks for you contribution! Could you please clarify why _alpha_ should be required upstream?

**Comment by idosh** [comment]
No special reason, just thought to test it and it worked.

**Comment by roberthbailey** [comment]
@errordeveloper do you have any concerns merging this change? If you think we should hold on supporting 2.1.0 until it is out of alpha I would certainly understand.

**Comment by errordeveloper** [comment]
@roberthbailey @idosh I am just not quite sure if there is a need to merge an upgrade to _alpha_ version of software that most part of Kubernetes depends on.

**Comment by errordeveloper** [comment]
@idosh, if you need to use newer version of etcd downstream, we could provide a way of setting it without having to modify the code.

**Comment by idosh** [comment]
It isn't necessary.
You can close the PR, if you don't want to use alpha version

**Comment by mbforbes** [comment]
@idosh It looks like the consensus above is to not switch to the new version of etcd quite yet while it's in alpha. I'm closing this, but please feel free to open an issue if you'd like to do what @errordeveloper suggested and add a way to set it without having to modify code.

Thank you for thinking to keep us on the bleeding edge! :-)

**Pull request closed without merging**
