### PR TITLE
Don't use Yoda conditions

### PR DESCRIPTION
**Pull request by navist2020**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
It is not so good that the literal is on the left side of the comparison.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/triage accepted

**Comment by navist2020** [comment]
ping @matthyx @ehashman

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
