### PR TITLE
Rename --experimental-control-plane into --control-plane

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Rename --experimental-control-plane into --control-plane

**Which issue(s) this PR fixes**:

Ref # https://github.com/kubernetes/kubeadm/issues/1373

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: rename the join flag --experimental-control-plane to --control-plane
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks  @yuexiao-wang !
please rebase the PR so that we can get the CI tests to pass. :)

/priority important-soon

**Comment by yuexiao-wang** [comment]
Got it. but I cannot find conflicts in cmd/join.go by git  command. I will modify my local code to resolve conflicts

**Comment by neolit123** [comment]
> Merge branch 'master' into rename-experimental

yeah, we shouldn't add merge commits. you should try `git push --force ...` instead.

**Review by yagonobre — COMMENTED** [review]
Thanks @yuexiao-wang 
Can you add `kubeadm:` prefix to release note?

**Comment by neolit123** [comment]
please use this for the release note:
`kubeadm: rename the join flag --experimental-control-plane to --control-plane`

NOTE: we are discussion in slack ATM if it's OK to do this hard-rename.
to my understanding we shouldn't do it like that (we should add a new flag `--control-plane` first), but this needs some discussion.

**Comment by neolit123** [comment]
> also looks like this should be the absolute last step we do before the release.

/hold

**Comment by rosti** [comment]
The underlying feature (HA) is in alpha, but the flag is part of the command line interface of join and that is GA.
I am not sure which deprecation policy applies here. Might be that we can flip this overnight (like what the PR does at the moment) or rename the flag to `control-plane` and add an `experimental-control-plane` alias to it, which will be held in place for about 3 minor releases.
In all cases, we have to wait for HA to become at least beta in order to remove the `experimental` portion of that flag, so we need to hold the PR for future use.

@timothysc @fabriziopandini WDYT?

**Comment by timothysc** [comment]
Thank you for the PR, but we can not accept a name change on this flag b/c it is not yet ready for promotion.  

Please see: https://github.com/kubernetes/kubeadm/issues/1373 for details.

**Pull request closed without merging**
