### PR TITLE
Automated cherry pick of #88251: fix incorrect configuration of kubepods.slice unit by kubelet

### PR DESCRIPTION
**Pull request by reegnz**
Cherry pick of #88251 on release-1.16.

#88251: fix incorrect configuration of kubepods.slice unit by kubelet

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by reegnz** [comment]
@odinuge do you think this will make it to the aug 12th deadline? Since that will be the last 1.16 release I would be really glad to have this fix included.

**Comment by odinuge** [comment]
Well, lets see how fast we can get it approved... All cherry-picks needs a changelog entry, so you have to add one to the PR.

/lgtm
/kind bug
/assign @sjenning

**Comment by reegnz** [comment]
@odinuge seems like the original PR didn't have a release note. I set release notes to none for now.

**Review by odinuge — COMMENTED** [review]
/ok-to-test

**Comment by reegnz** [comment]
Anything else I need to do to get this merged for tomorrow's deadline?

**Comment by odinuge** [comment]
Ping @kubernetes/release-managers

**Comment by reegnz** [comment]
Okay, I'm guessing this won't make it into the release?

Sorry, didn't have much time to babysit this PR. :(

**Pull request merged**
