### PR TITLE
Remove DeprecatedInsecureServingOptionsWithLoopback

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
`DeprecatedInsecureServingOptionsWithLoopback` is deprecated and unused, can be removed now.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SataQiu** [comment]
/assign @liggitt 
Can these be safely removed now?

**Comment by deads2k** [comment]
Glad to see this go.

/lgtm
/hold cancel

**Pull request merged**
