### PR TITLE
print out the raw pod json instead of the whole golang struct

### LINKED ISSUE #95232: 6KB log messages during networking Granular checks
**What happened**:

We print out massive go structs during the granular network checks

**What you expected to happen**:

not print 7K log messages :) 

**How to reproduce it (as minimally and precisely as possible)**:

run sonobuoy with
```
--e2e-focus=Granular
```

and you'll get this

```
&v1.Pod{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-container-pod", GenerateName:"", Namespace:"nettest-1221", SelfLink:"/api/v1/namespaces/nettest-1221/pods/test-container-pod", UID:"3e5d45b7-0a59-4655-a2e6-914b4d4568aa", ResourceVersion:"74384", Generation:0, 

CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63737147943, loc:(*time.Location)(0x7f3eb60)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:

[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"e2e.test", Operation:"Update", APIVersion:"v1", Time:(*v1.Time)(0xc0021b5720), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0021b5740)}, v1.ManagedFieldsEntry{Manager:"kubelet", Operation:"Update", APIVersion:"v1", Time:(*v1.Time)(0xc0021b5760), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0021b5780)}}}, Spec:v1.PodSpec{Volumes:[]v1.Volume{v1.Volume{Name:"default-token-p9ffh", 

VolumeSource:v1.VolumeSource{HostPath:(*v1.HostPathVolumeSource)(nil), EmptyDir:(*v1.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*v1.GitRepoVolumeSource)(nil), Secret:(*v1.SecretVolumeSource)(0xc002540140), NFS:(*v1.NFSVolumeSource)(nil), ISCSI:(*v1.ISCSIVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:

(*v1.PersistentVolumeClaimVolumeSource)(nil), RBD:(*v1.RBDVolumeSource)(nil), FlexVolume:(*v1.FlexVolumeSource)(nil), Cinder:(*v1.CinderVolumeSource)(nil), CephFS:(*v1.CephFSVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), 

DownwardAPI:(*v1.DownwardAPIVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), AzureFile:(*v1.AzureFileVolumeSource)(nil), ConfigMap:(*v1.ConfigMapVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), Projected:(*v1.ProjectedVolumeSource)(nil), PortworxVolume:

(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOVolumeSource)(nil), StorageOS:(*v1.StorageOSVolumeSource)(nil), CSI:(*v1.CSIVolumeSource)(nil), Ephemeral:(*v1.EphemeralVolumeSource)(nil)}}}, InitContainers:[]v1.Container(nil), Containers:[]v1.Container{v1.Container{Name:"webserver", Image:"k8s.gcr.io/e2e-test-images/agnhost:2.21", Command:[]string(nil), Args:[]string{"netexec", "--http-port=8080", "--udp-port=8081"}, WorkingDir:"", Ports:[]v1.ContainerPort{v1.ContainerPort{Name:"http", HostPort:0, ContainerPort:8080, Protocol:"TCP", HostIP:""}}, EnvFrom:[]v1.EnvFromSource(nil), Env:[]v1.EnvVar(nil), Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), 

Requests:v1.ResourceList(nil)}, VolumeMounts:[]v1.VolumeMount{v1.VolumeMount{Name:"default-token-p9ffh", ReadOnly:true, MountPath:"/var/run/secrets/kubernetes.io/serviceaccount", SubPath:"", MountPropagation:(*v1.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]v1.VolumeDevice(nil), LivenessProbe:(*v1.Probe)(nil), ReadinessProbe:(*v1.Probe)(nil), StartupProbe:(*v1.Probe)(nil), Lifecycle:(*v1.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", 

TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*v1.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]v1.EphemeralContainer(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc00253a158), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"default", DeprecatedServiceAccount:"default", 

AutomountServiceAccountToken:(*bool)(nil), NodeName:"ip-10-0-4-40.us-west-2.compute.internal", HostNetwork:false, HostPID:false, HostIPC:false, ShareProcessNamespace:(*bool)(nil), SecurityContext:(*v1.PodSecurityContext)(0xc0028decb0), ImagePullSecrets:[]v1.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*v1.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]v1.Toleration{v1.Toleration{Key:"node.kubernetes.io/not-ready", Operator:"Exists", Value:"", Effect:"NoExecute", TolerationSeconds:(*int64)(0xc00253a190)}, 

v1.Toleration{Key:"node.kubernetes.io/unreachable", Operator:"Exists", Value:"", Effect:"NoExecute", TolerationSeconds:(*int64)(0xc00253a1b0)}}, HostAliases:[]v1.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(0xc00253a1b8), DNSConfig:(*v1.PodDNSConfig)(nil), ReadinessGates:[]v1.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(0xc00253a1bc), PreemptionPolicy:(*v1.PreemptionPolicy)(0xc0021e2420), Overhead:v1.ResourceList(nil), 

TopologySpreadConstraints:[]v1.TopologySpreadConstraint(nil), SetHostnameAsFQDN:(*bool)(nil)}, Status:v1.PodStatus{Phase:"Running", Conditions:[]v1.PodCondition{v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, 

LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63737147943, loc:(*time.Location)(0x7f3eb60)}}, Reason:"", Message:""}, v1.PodCondition{Type:"Ready", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63737147945, loc:(*time.Location)(0x7f3eb60)}}, Reason:"", Message:""}, v1.PodCondition{Type:"ContainersReady", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, 

LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63737147945, loc:(*time.Location)(0x7f3eb60)}}, Reason:"", Message:""}, v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63737147943, loc:(*time.Location)(0x7f3eb60)}}, Reason:"", Message:""}}, Message:"", Reason:"", NominatedNodeName:"", HostIP:"10.0.4.40", 

PodIP:"100.96.1.71", PodIPs:[]v1.PodIP{v1.PodIP{IP:"100.96.1.71"}}, StartTime:(*v1.Time)(0xc0021b57c0), InitContainerStatuses:[]v1.ContainerStatus(nil), ContainerStatuses:[]v1.ContainerStatus{v1.ContainerStatus{Name:"webserver", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(0xc0021b57e0), Terminated:(*v1.ContainerStateTerminated)(nil)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:true, RestartCount:0, 

Image:"k8s.gcr.io/e2e-test-images/agnhost:2.21", ImageID:"k8s.gcr.io/e2e-test-images/agnhost@sha256:ab055cd3d45f50b90732c14593a5bf50f210871bb4f91994c756fc22db6d922a", ContainerID:"containerd://41f112204ba84b839d2e4b29070cae6e76a861a65f3196089b3e900abf03f2d2", Started:(*bool)(0xc00253a219)}}, QOSClass:"BestEffort", EphemeralContainerStatuses:[]v1.ContainerStatus(nil)}}
```
in the logs :) !

**Anything else we need to know?**:
easy fix, will print out the pod json which is much more concise.

### PR DESCRIPTION
**Pull request by jayunit100**
fixes #95232

### CODE REVIEW

**Comment by jayunit100** [comment]
The new logging output < 1 kb, much more easier to read for debugging - it retains pod and host ip which is the most important info for this test

```
Oct  1 08:31:44.996: INFO: Tries: 10, in try: 9, stdout: {"responses":["netserver-1"]}, stderr: , command run in Pod { "name: test-container-pod, namespace: nettest-1167, hostIp: 10.0.0.80, podIp: 100.96.3.105, conditions: [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-10-01 08:31:14 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-10-01 08:31:16 -0400 EDT  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-10-01 08:31:16 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-10-01 08:31:14 -0400 EDT  }]" }

```

**Comment by jayunit100** [comment]
bazel flake
```
ARNING: Download from https://github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz failed: class java.io.IOException Tried to reconnect at offset 1,011,754 but server didn't support it
20
ER
```

**Comment by rikatz** [comment]
/kind cleanup
/priority backlog
/lgtm

As far as I know, making logs readable is a good thing! :)
Thaks

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
