### PR TITLE
missed registering kubelet-config-file for the command line use case running test-e2e-node target

### PR DESCRIPTION
**Pull request by dims**
we really gotta revisit all the e2e-node scenarios and fix things up right. this is a patch/hack for now as i broke something when https://github.com/kubernetes/kubernetes/pull/116517 landed.

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by upodroid** [comment]
Not entirely sure why you would want to run the E2E test locally. It is the first option on the docs. :(

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md

**Comment by dims** [comment]
`pull-kubernetes-node-e2e-containerd` and `pull-cadvisor-e2e-kubernetes` are green!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
/retest

the failure is clearly a flake

**Comment by gjkim42** [comment]
I think this fixed [my issue](https://github.com/kubernetes/kubernetes/pull/116517#issuecomment-1468619064).
/lgtm
/retest-required

**Pull request merged**
