### PR TITLE
Fix a crash for kubelet when without EtcdClient.

### PR DESCRIPTION
**Pull request by cedbossneo**
Authored by dchen1107, commit: 6e6f465a3699ffc080628310694810ad04c7d498

### CODE REVIEW

**Comment by brendandburns** [comment]
CLA verified.

Thanks for the PR.  You need to run gofmt on the code...

**Comment by dchen1107** [comment]
@filbranden Are we really want to merge this fix to release-0.8? Filipe, I thought you are going to provide a cleaner fix for this? I would rather to hold on a cleaner fix since this only affects containerVM users, and we should have fix ready before cutting next containerVM release.

**Comment by filbranden** [comment]
Yes, I'm planning to fix this by changing `EtcdClientOrDie()` to return a `tools.EtcdClient` instead of a `*etcd.Client` which means a `nil` in return value of that function will become a real `nil`, this is what @lavalamp suggested.

The problem is that I just tried Kubernetes from head in standalone mode and it broke at `pkg/client/cache/listwatch.go:38`, so I believe that is something that was introduced in #3285.

I was kind of waiting for that to be fixed before proceeding with the pointer -> interface changes and I think I'd like to fix this in the master branch before backporting something to the 0.8 branch...

**Comment by erictune** [comment]
#3577 fixes listwatch problem.

**Comment by filbranden** [comment]
Now standalone kubelet is blocked on #3584, once that one is fixed I'll look into removing reflect once again...

**Comment by bgrant0607** [comment]
Is this PR still relevant?

**Comment by filbranden** [comment]
I would say "no" since we solved it by having the pointer be a real nil pointer.

**Pull request closed without merging**
