### PR TITLE
Automated cherry pick of #24006

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #24006 on release-1.2.

### CODE REVIEW

**Comment by david-mcmahon** [comment]
cc @eparis the bot added `release-note-label-needed` to this PR.

**Comment by eparis** [comment]
parent has 'release-note-none'   which means this PR must follow the process....

**Comment by david-mcmahon** [comment]
@eparis but `release-note-none` is a valid state.  The only time a release branch PR should need a release-note-* label is when it isn't traced to a master parent (with a valid release-note-* label).

**Comment by zmerlynn** [comment]
I'm manually merging this PR and ignoring Travis. I've validated it manually.

**Comment by caesarxuchao** [comment]
Thank you @zmerlynn

**Comment by eparis** [comment]
@david-mcmahon I was under the impression the process said that all cherry-picks must have either release-note or release-note-action-required.  CP without release notes were prohibited...

**Comment by david-mcmahon** [comment]
@eparis It has been a fluid process, but we've been stable on [only using master for release-note state](https://github.com/kubernetes/kubernetes/pull/23555/files#diff-e63cd1ccf1502a0b570b0acfd59807d0R45) since https://github.com/kubernetes/kubernetes/pull/23555#issuecomment-204195429.

Can you skim the [doc](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md) and make sure we're in sync?  If there's anything that's not in-line with what the munger is doing (or we can make it do soonish), I'll fix in a PR.

**Pull request merged**
