### PR TITLE
fix top node output format incorrect

### LINKED ISSUE #105112: When the node is abnormal, the output format of the Top node is incorrect
#### What happened:
image

#### What you expected to happen:
image

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wujiangfa-xlauncher**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix top node output format incorrect
#### Which issue(s) this PR fixes:

Fixes #105112

#### Special notes for your reviewer:
NONE
#### Does this PR introduce a user-facing change?

```release-note
NONE
```
NONE
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

```docs
NONE
```

### CODE REVIEW

**Comment by lauchokyip** [comment]
Link: https://github.com/kubernetes/kubectl/issues/1111

**Comment by brianpursley** [comment]
I guess there are no unit tests for metrics printer.

It seems like the lines removed should fix the problem though as the tabs are redundant.

/retest

**Review by brianpursley — APPROVED** [review]

**Review by eddiezane — APPROVED** [review]
Thanks!

/approve

**Pull request merged**
