### PR TITLE
update ExecProbeTimeout comment about its removal

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind documentation
/kind deprecation

#### What this PR does / why we need it:

This PR updates a code comment to clarify that the definitive removal of the ExecProbeTimeout kubelet feature gate is not definitively determined. This change is meant to advocate for a further extension of this feature gate beyond 1.20.0 (the current comment suggests the feature gate will be removed starting with 1.21.0)

tl;dr This feature gate was introduced in 1.20.0. We should allow more future release headroom for folks to continue using a ExecProbeTimeout=false configuration if they need more time to adapt their cluster workload specifications before enabling container exec livenessProbe functionality.

#### Which issue(s) this PR fixes:

Relates to #99854

#### Special notes for your reviewer:

Some background matter that describes the side-effects of not being able to continue to use `ExecProbeTimeout=false`:

- https://github.com/kubernetes/kubernetes/pull/97057
- https://github.com/kubernetes/kubernetes/issues/97060

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
See also discussion here: https://github.com/kubernetes/kubernetes/pull/98085

**Comment by jackfrancis** [comment]
Thanks @dims and @SergeyKanzhelev.

@SergeyKanzhelev, is it worth having a distinct discussion to reach consensus around when to officially remove this kubelet feature gate option? I'm very happy to see that there seems to be movement on delaying this another release cycle, but is it too much work to ask folks to weigh in on whether or not 1.22 is the right release cycle to lock this feature gate?

cc @lachie83

**Comment by SergeyKanzhelev** [comment]
/close 

in favor of #100023, let's not use TODO

**Comment by jackfrancis** [comment]
Thanks @SergeyKanzhelev!

**Pull request closed without merging**
