### PR TITLE
Update admission control args in imagepolicy comment

### PR DESCRIPTION
**Pull request by FengyunPan**
Use '--admission-control-config-file' rather than
'--admission-controller-config-file'

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by FengyunPan** [comment]
@brendandburns It seems that need '/approve no-issue' not '/approve', thank you.

**Pull request merged**
