### PR TITLE
Remove 'exec' network plugin - use CNI instead

### LINKED ISSUE #38639: Deprecate Exec Network Plugin
Is anyone still using the [exec network plugin](http://kubernetes.io/docs/admin/network-plugins/#exec)? We want to deprecate it in 1.6. 

@kubernetes/sig-network @kubernetes/sig-node

### PR DESCRIPTION
**Pull request by freehan**
fixes: #38639

### CODE REVIEW

**Comment by freehan** [comment]
@k8s-bot verify test this

**Comment by thockin** [comment]
This needs a release note

**Comment by hex108** [comment]
Hi @freehan , when I run `make` in the master branch, `pkg/generated/bindata.go` will be modified. I found the commit modifies `pkg/generated/bindata.go` which seems not necessary. Could you please help confirm it? Thanks.

**Comment by freehan** [comment]
@hex108  hmmm... That stays the same for me though...

**Comment by hex108** [comment]
@freehan If I understand correctly, `pkg/generated/bindata.go` is generated from directory `${KUBE_ROOT}/translations/...`, and there is no change in this directory, so `bindata.go` should not be modified.

**Comment by bboreham** [comment]
This command-line option explanation still (obliquely) refers to exec plugins
https://github.com/kubernetes/kubernetes/blob/ed5a23652566b48694ccdfacc5cff0790905a1a1/cmd/kubelet/app/options/options.go#L180

Similarly this comment:
https://github.com/kubernetes/kubernetes/blob/55bee3ad21f025b1416a4e1f10de753f484b66d3/pkg/apis/componentconfig/v1alpha1/types.go#L329

(noting here in case I forget before doing a PR)

**Comment by freehan** [comment]
@bboreham Thanks for pointing it out! I will submit another PR to clean this up.

**Pull request merged**
