### PR TITLE
[1.18] Cherry pick of #92644: Wait for all informers to sync in /readyz.

### PR DESCRIPTION
**Pull request by jprzychodzen**
Cherry pick of #92644 on release-1.18.

#92644: Wait for all informers to sync in /readyz.

/cc @wojtek-t 
/cc @mborsz 
/cc @mm4tt

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
/lgtm

**Comment by wojtek-t** [comment]
/approve

@kubernetes/release-managers - for cherrypick approval

**Comment by jprzychodzen** [comment]
@kubernetes/release-managers

**Pull request merged**
