### PR TITLE
Upgrade to Kibana 4 for cluster logging

### PR DESCRIPTION
**Pull request by satnam6502**
Now that HEAD requests work through our proxy service this PR upgrades our Kibana viewer for log information to the latest version which now has a back-end service which can speak to Elasticsearch using DNS. @a-robinson

### CODE REVIEW

**Comment by satnam6502** [comment]
@vish in case you are interested.

**Comment by zmerlynn** [comment]
And I think you meant to cc @vishh

**Comment by a-robinson** [comment]
Wow, this is quite an improvement. Is kibana now running in a more standard web frontend mode where all its requests to elasticsearch are done from the kibana instance rather than from the browser?

LGTM

**Comment by satnam6502** [comment]
Yes, it is a huge improvement. I am very happy about the change to Kibana4 since we now don't have any accesses from the browser into the cluster to try and access Elasticsearch. We had to fix our handling of HEAD in our proxy to make it work out (a PR I submitted last week) which then unblocked the use of Kibana4.

**Comment by satnam6502** [comment]
Well, technically, there are accesses from the browser but they work by going through a Kibana URL that adds a `/elasticsearch` path segment which is then re-rerouted to the actual Elasticsearch instance. I had implemented something with proxy_pass in nginix in an earlier configuration.

**Pull request merged**
