### PR TITLE
ADD UT TEST of cinder volume

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
add ut test to func ConstructVolumeSpec in cinder test 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
PTAL @jsafrane 
thanks,but why panic: runtime error: invalid memory address or nil pointer dereference [recovered]?

**Comment by jianglingxia** [comment]
/cc @dims
thanks

**Comment by jsafrane** [comment]
> but why panic: runtime error: invalid memory address or nil pointer dereference [recovered]?

Because you did not test `err`. It looks like `ConstructVolumeSpec` failed.

**Comment by jianglingxia** [comment]
yes,you right! @jsafrane 
--- FAIL: TestConstructVolumeSpec (0.00s)
	cinder_test.go:239: ConstructVolumeSpec failed: directory /cinderVolume/ is not mounted
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf99bdd]
why the directoy not mounted

**Comment by jsafrane** [comment]
/lgtm cancel

The test still fails:

```
--- FAIL: TestConstructVolumeSpec (0.00s)
	cinder_test.go:239: ConstructVolumeSpec failed: directory /cinderVolume/ is not mounted
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x168187b]

goroutine 13 [running]:
testing.tRunner.func1(0xc4200d6b40)
	GOROOT/src/testing/testing.go:711 +0x5d9
panic(0x17e9a80, 0x21e6d20)
	GOROOT/src/runtime/panic.go:491 +0x2a2
k8s.io/kubernetes/pkg/volume.(*Spec).Name(...)
	pkg/volume/plugins.go:330
k8s.io/kubernetes/pkg/volume/cinder.TestConstructVolumeSpec(0xc4200d6b40)
	pkg/volume/cinder/cinder_test.go:241 +0x47b
testing.tRunner(0xc4200d6b40, 0x19b7410)
	GOROOT/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:789 +0x569

```

**Comment by jianglingxia** [comment]
yes,the err is not nil,so test failed,but I can understand why err return not nil!

**Comment by dims** [comment]
please add me back when this is ready

**Pull request closed without merging**
