### PR TITLE
remove dead code in pkg/api

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
remove dead code
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
/assign @erictune

For approval.

**Comment by hzxuzhonghu** [comment]
ping @erictune

**Comment by hzxuzhonghu** [comment]
/test pull-kubernetes-e2e-gce

ping @erictune

**Comment by hzxuzhonghu** [comment]
ping @thockin

**Pull request merged**
