### PR TITLE
[kubectl] Lookup Host from kubeconfig when needed

### PR DESCRIPTION
**Pull request by dims**
Found this when developing `kubetest2-ec2`, it's easier to lookup than artificially thread in `--host` parameter when we already have kubeconfig

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

You can see the errors for 2 test cases in:
- `[It] [sig-cli] Kubectl client Simple pod should support exec through kubectl proxy`
- `[It] [sig-cli] Kubectl client Simple pod should support exec through an HTTP proxy`

in the following log:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119811/pull-kubernetes-e2e-ec2/1691053796903358464

next run with this commit applied shows that these 2 tests pass:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119811/pull-kubernetes-e2e-ec2/1691077445404332032

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
lookups add an additional dependency on the dns resolver that can cause flakes

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
