### PR TITLE
Update prometheus client to v1.1.0

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Update the golang prometheus client to the latest version and refactor the usage of the legacy HTTP handler.

**Does this PR introduce a user-facing change?**:
```release-note
- Update prometheus client to v1.1.0
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
- Release Notes: https://github.com/prometheus/client_golang/releases/tag/v1.1.0
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@logicalhan @solodov It might be that this update clashes with your plans in the [Metrics Stability KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-stability-migration.md), right?

**Comment by RainbowMango** [comment]
> @logicalhan @solodov It might be that this update clashes with your plans in the [Metrics Stability KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-stability-migration.md), right?

Can you explain why we need this pr? Is there a bug need to fix or need feature we wanted?

Furthermore, why we need to "revert" the code that we had just migrate from prometheus to stability framework? 

Let's hold for a while. 
/hold

**Comment by logicalhan** [comment]
This is basically going to break a bunch of metrics. If you want to update the handler you’d have to do it in the legacyregistry package.

**Comment by saschagrunert** [comment]
I will close this for now since I see that it goes not into the right direction.

**Pull request closed without merging**
