### PR TITLE
[WIP] Add e2e tests for dualstack downward api

### PR DESCRIPTION
**Pull request by aramase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
- Adds e2e tests for dualstack downward api support

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/uncc @mattjmcnaughton 

Happy to take a shot at reviewing once this diff is no longer WIP. Feel free to ping me.

**Comment by aojea** [comment]
> /test pull-kubernetes-conformance-kind-ipv6

if you want this patch tested by this kind job you have to add a temporary commit to "promote" the test to conformance ;)

**Pull request closed without merging**
