### PR TITLE
Make sure we pick up the latest release.

### PR DESCRIPTION
**Pull request by ovidiucp**

### CODE REVIEW

**Comment by ovidiucp** [comment]
I signed it!

**Comment by ovidiucp** [comment]
The ubuntu/util.sh change simplifies the code quite a bit. One other thing it lets one do is build a cluster for high availability by simply specifying multiple master nodes. The script takes care of setting up etcd in a cluster, and taking care of setting up flanneld to talk to the right etcd server.

I tested it on a 4 node Ubuntu cluster running 14.04.

**Comment by quinton-hoole** [comment]
@ovidiucp My apologies for the delay responding.  I'd love to get this in as soon as we can.  Assigning to @mikedanese for review, as he has way better context than I do.

**Comment by mikedanese** [comment]
"Make sure we pick up the latest release" is the title of this change and it has no description. Latest release of what? There's a huge diff with reformatting and renaming. I need some context to review this.

**Comment by ovidiucp** [comment]
Sorry, github picked up another file I submitted to my repo. The change
originally contained download-release.sh only. The file that was added is
util.sh, which had its own change description which got eaten in the
process.

The changes to util.sh are here:

https://github.com/kubernetes/kubernetes/pull/23898/commits/3d22b96327a9722ec8fc013001241c242efc275e

The purpose of those changes is to allow any combination of masters and
minions to be specified at cluster build time. This makes it possible to
build a highly available cluster, instead of one where you have only one
master.

The change to util.sh gets rid of most global variables used for holding
the IP values, passing instead the IP values to the various shell functions.

On Sun, May 8, 2016 at 7:35 PM, Mike Danese <notifications@github.com>
wrote:

> "Make sure we pick up the latest release" is the title of this change and
> it has no description. Latest release of what? There's a huge diff with
> reformatting and renaming. I need some context to review this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/23898#issuecomment-217764518>
>



-- 
This confidential email is read by the NSA (at the least).

**Comment by ovidiucp** [comment]
I forgot to mention, the ubuntu version of download-release.sh downloads the released .tar.gz file again. Right now the version of the downloaded file is manually encoded within the script. My change fetches the released version automatically, similar to the shell script available on the main Kubernetes site below:

https://get.k8s.io/

Ideally the installation on bare metal ubuntu should work with the files available in the already downloaded package. That however is more work that needs to be done.

**Comment by mikedanese** [comment]
Can you please remove the unrelated commit from this PR?

**Comment by ovidiucp** [comment]
Argh, I messed up the rebase. I'm closing this pull request and will be submitting another one containing just the one file requested.

**Comment by mikedanese** [comment]
Thanks. Please ping me on the issue.

**Pull request closed without merging**
