### PR TITLE
test(portforward): deflake TestGetListener

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1302902043437961222

```
=== RUN   TestGetListener
    portforward_test.go:321: Test case #0 failed: Data {localhost tcp4 false 127.0.0.1} an error has been raised(false) where it should not (or reciprocally): unable to create listener: Error listen tcp4 127.0.0.1:12345: bind: address already in use
    portforward_test.go:321: Test case #1 failed: Data {127.0.0.1 tcp4 false 127.0.0.1} an error has been raised(false) where it should not (or reciprocally): unable to create listener: Error listen tcp4 127.0.0.1:12345: bind: address already in use
    portforward_test.go:334: Asked a tcp6 forward for: ::1:12345, got listener ::1:12345, expected: 12345
--- FAIL: TestGetListener (0.00s)
```

**Which issue(s) this PR fixes**:

Part of #94528

**Special notes for your reviewer**:

### Alternative

We could wait for port `12345` to be closed, not sure which one is better.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
I would expected us to use the "allocate a free port" mechanism for the portforwarding:

```diff
diff --git a/staging/src/k8s.io/client-go/tools/portforward/portforward_test.go b/staging/src/k8s.io/client-go/tools/portforward/portforward_test.go
index 5b9afabeaab..041da05cac6 100644
--- a/staging/src/k8s.io/client-go/tools/portforward/portforward_test.go
+++ b/staging/src/k8s.io/client-go/tools/portforward/portforward_test.go
@@ -17,6 +17,7 @@ limitations under the License.
 package portforward
 
 import (
+	"fmt"
 	"net"
 	"net/http"
 	"os"
@@ -309,12 +310,13 @@ func TestGetListener(t *testing.T) {
 	}
 
 	for i, testCase := range testCases {
-		expectedListenerPort := "12345"
-		listener, err := pf.getListener(testCase.Protocol, testCase.Hostname, &ForwardedPort{12345, 12345})
+		forwardedPort := &ForwardedPort{0, 12345}
+		listener, err := pf.getListener(testCase.Protocol, testCase.Hostname, forwardedPort)
 		if err != nil && strings.Contains(err.Error(), "cannot assign requested address") {
 			t.Logf("Can't test #%d: %v", i, err)
 			continue
 		}
+		expectedListenerPort := fmt.Sprintf("%d", forwardedPort.Local)
 		errorRaised := err != nil
 
 		if testCase.ShouldRaiseError != errorRaised {
@@ -331,7 +333,7 @@ func TestGetListener(t *testing.T) {
 		}
 
 		host, port, _ := net.SplitHostPort(listener.Addr().String())
-		t.Logf("Asked a %s forward for: %s:%v, got listener %s:%s, expected: %s", testCase.Protocol, testCase.Hostname, 12345, host, port, expectedListenerPort)
+		t.Logf("Asked a %s forward for: %s:%v, got listener %s:%s, expected: %s", testCase.Protocol, testCase.Hostname, 0, host, port, expectedListenerPort)
 		if host != testCase.ExpectedListenerAddress {
 			t.Errorf("Test case #%d failed: Listener does not listen on expected address: asked '%v' got '%v'", i, testCase.ExpectedListenerAddress, host)
 		}
```

**Comment by knight42** [comment]
@liggitt PTAL

**Pull request merged**
