### PR TITLE
Reverted conversion of influx-db to PetSet.

### PR DESCRIPTION
**Pull request by jszczepkowski**
``` release-note
Reverted conversion of influx-db to Pet Set, it is now a Replication Controller.
```

Reverted conversion of influx-db to PetSet, it is now a Replication Controller and Persistent Volumes are no longer used.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
This PR reverts #28109, because of problems with `kubernetes-e2e-gce-master-on-cvm`: see https://github.com/kubernetes/kubernetes/pull/28840#issuecomment-237386430.

**Comment by jszczepkowski** [comment]
PetSet are not yet ready to convert influx-db to use them, as there are problems with deleting of persistent volumes: see #16337 & https://github.com/kubernetes/kubernetes/pull/28840#issuecomment-237044354.

**Comment by jszczepkowski** [comment]
CC @bprashanth

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
Bumping pri due to increasing dep chain (#30047) and blocked build, though that build's been red for a while. (Should perhaps be just moved to blocking, though.)

**Pull request merged**
