### PR TITLE
Add SharedCredentials Provider to AWS

### PR DESCRIPTION
**Pull request by ghost**
This will allows authentication with the AWS API using the
~/.aws/credentials file which is created by runnign 'aws configure' on
a node.

Signed-off-by: Sami Wagiaalla swagiaal@redhat.com

### CODE REVIEW

**Comment by swagiaal** [comment]
@justinsb WDYT ?

**Comment by justinsb** [comment]
I don't see any downside to allowing this.  Though I would ask what you're working on here, and how you plan on distributing this file.  I believe we're already planning on replication the cloud configuration file (even if we don't do so today), so it might make more sense to try to get credentials from there.

No real objection to this though, just want to make sure we aren't encouraging people to do things that we actually don't want them to do!

**Comment by swagiaal** [comment]
> Though I would ask what you're working on here, and how you plan on distributing this file.
No particular plan. I just thought it would be a good quick way to get started with a tutorial or something.

> I believe we're already planning on replicating the cloud configuration file (even if we don't do so today), so it might make more sense to try to get credentials from there.

Which cloud configuration file ? Can you elaborate on this a bit ?

> No real objection to this though, just want to make sure we aren't encouraging people to do things that we actually don't want them to do!

Got it. So the role provider is considered better practice

**Comment by justinsb** [comment]
Sorry for delay.  The cloud configuration file is passed into each cloud provider e.g. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/plugins.go#L54

I don't think anyone actually uses this any more, although presumably if we wanted to distribute cloud configuration information, we should probably piggy back off this.

I did have a patch a while ago to accept an AccessKey and SecretKey from that configuration file for AWS, but (for me at least) instance roles proved much more convenient, so who knows where that code is!

I think we should prefer instance roles; I'm very open to accepting AccessKey/SecretyKey in the cloud configuration file if it is useful (though I'd want to know why), and I'm also (less) open to a separate file although I'd want to know why and how we plan to distribute that file.

**Comment by mbforbes** [comment]
Needs a rebase. Also @brendandburns for an owner.

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
