### PR TITLE
Add support for binary files in configmap

### LINKED ISSUE #32432: Enable ConfigMaps to store binary files as well as character files.
**Is this a BUG REPORT or FEATURE REQUEST?**

FEATURE REQUEST

Please enable ConfigMaps to store binary files as well as character files.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+coreos.0", GitCommit:"f6f0055b8e503cbe5fb7b6f1a2ee37d0f160c1cd", GitTreeState:"clean", BuildDate:"2016-08-29T17:01:01Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: HP EliteOne 800 G1 AiO
- **OS** (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`) (kubectl client):  `Linux derek-HP-EliteOne-800-G1-AiO 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
  `
- Target environment is a three node Vagrant (VirtualBox) cluster running CoreOS 1164.1.0.

**What happened?**

After creating a ConfigMap from a directory containing a binary Java keystore file, command `kubctl describe configmap` reported a size for the binary file that was larger than the original file:

```
derek@derek-HP-EliteOne-800-G1-AiO~:$ kubectl describe configmap platinum-fix-brvm-config
Name:       platinum-fix-brvm-config
Namespace:  default
Labels:     <none>
Annotations:    <none>

Data
====
brvm-fix44.xml: 334363 bytes
keystore.jks:   2266 bytes
settings.txt:   910 bytes
derek@derek-HP-EliteOne-800-G1-AiO~:$ ls -l keystore.jks 
-rw-rw-r-- 1 derek derek 1326 Sep  9 17:52 keystore.jks
```

When run inside a container having a mounted volume created from the ConfigMap, command `ls --format=long --dereference keystore.jks` also reported a file size larger than the original: 

```
-rw-r--r--. 1 root root 2266 Sep 10 00:58 keystore.jks
```

A Java application in the container that attempted to read `keystore.jks` reported an exception claiming that the file was invalid.

**What did you expect to happen?**
- Kubernetes reports the size of the binary file in the ConfigMap as the same as the original file.
- Kubernetes container log reports the size of the binary file in the ConfigMap as the same as the original file.
- Java application successfully reads binary file `keystore.jks`.
- Result of command `file keystore.jks` should be `keystore.jks: Java KeyStore`.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a ConfigMap from a directory that contains a Java keystore file (or some other binary file).
2. Run `kubectl describe configmap` and observe the file size.
3. Compare the file size in the ConfigMap to the original file size. 
4. Map the ConfigMap to a volume, mount the volume in a container, and run `ls --format=long --dereference keystore.jks` and compare the file size of the result to the original file size.

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:
Config Maps do not support binary files. We do not want to change the API for
config maps. So we need a way to encode the file contents in a standard fashion.
One option is to check the file contents if they are binary and encode them as
MIME messages. since MIME messages can carry base64 content, we will not
corrupt the contents. We also add code on the other side to detect that the
config map data is a MIME message and decode that when we save it into a file

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #32432

**Special notes for your reviewer**:

**Release note**:

```release-note
kubectl --from-file can now detect binary files and transparently encode it as MIME. On the server-side these MIME payload is decoded and stored without corrupting the data.
```

### CODE REVIEW

**Comment by liggitt** [comment]
this approach will not work, for several reasons:
* it assumes no existing data has a "MIME-Version: 1.0" prefix
* it is not backwards compatible (old kubelets will misinterpret newly/differently encoded data)

we need a different field to hold binary content

see discussion starting at https://github.com/kubernetes/kubernetes/issues/32432#issuecomment-247006141 for an explanation of why we can't add an encoding scheme like this to an existing field. all the same points about adding base64 encoding to the current field apply to this encoding scheme as well.

**Comment by dims** [comment]
@liggitt for the first one "it assumes no existing data has a "MIME-Version: 1.0" prefix or contains mime messages" .... the tradeoff is we have a broken implementation right now where we don't warn folks using --from-file with binary either when they are creating a config map or as logs in kubelet when we mount the file. they discover that their binary file is corrupted when they do a hex dump of some kind. So this trade off is way better IMHO.

for the second one, "it is not backwards compatible", we could 
- either warn them when the text is binary throw in a new flag that they they can use
- or check server version?

Also, are we ok with adding a new field? i thought that was off the table...

Thanks,
Dims

**Comment by liggitt** [comment]
> the tradeoff is we have a broken implementation right now where we don't warn folks using --from-file with binary either when they are creating a config map or as logs in kubelet when we mount the file. they discover that their binary file is corrupted when they do a hex dump of some kind. So this trade off is way better IMHO.

today, we have "garbage in, garbage out". running the risk of corrupting data of people who are using the current system properly (by putting their own application-level encoding on top of the config map string data) is not better. we could certainly warn or validate that only UTF-8 data was allowed in the string data.

> Also, are we ok with adding a new field? i thought that was off the table...

it's the proper way to accomplish this if we want to do this.

**Comment by dims** [comment]
Interesting, thanks @liggitt looks like we need to resurrect @zreigz 's PR from https://github.com/kubernetes/kubernetes/pull/33549

**Comment by thockin** [comment]
I was about to write what @liggitt wrote, and then I was about to re-write https://github.com/kubernetes/kubernetes/issues/32432#issuecomment-249221358

There are multiple viable ways to solve this.  I think we'd all be happy to see it solved. :)  I don't have a strong preference for models, and I think it would be worthwhile to sketch out all of them and see which tastes least-bad.

**Comment by dims** [comment]
@liggitt @thockin - ok let me try adding a `ContentEncoding` field in `EnvVarSource` and `KeyToPath` which can be an empty string `""` or `"base64"`. 

Sounds good?

**Comment by liggitt** [comment]
> I think it would be worthwhile to sketch out all of them and see which tastes least-bad.

I agree on this. The three that come to mind are:
1. a new parallel field in ConfigMap for binary content
2. a new parallel field in ConfigMap for specifying per-key content encoding
3. point of use specification of content encoding 

1 seems the most straightforward to me, and would map well to a unified structure in a v2 api if we ever get there. old clients will ignore binary data rather than misinterpret it, which I think I prefer

2 keeps the encoding specification together with the data, which is good, but means old clients will misinterpret binary data if they don't know about the encoding.

3 seems like the worst option to me… we not only have the possibility for misinterpretation of binary data, moving the content encoding spec to the point of use means that both the creator and consumer have to worry about specifying the encoding correctly.

**Comment by dims** [comment]
@liggitt for Option #1, newer kubectl will send stuff that older server would not understand. right?

**Comment by liggitt** [comment]
> for Option #1, newer kubectl will send stuff that older server would not understand. right?

Yes, the new binary data would be dropped by the old server. There is no way to plumb non-utf8 binary data through the existing configmap objects such that old apiservers and kubelets will actually deliver it correctly into containers.

**Pull request closed without merging**
