### PR TITLE
kubeadm: fix golint warnings in package_validator

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixed the following golint warnigns:
 - package_validator.go:68:1: receiver name should not be an underscore, omit the name if it is unused
 - package_validator.go:89:1: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
 - package_validator.go:96:1: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
 - package_validator.go:119:1: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — APPROVED** [review]
Thanks @bart0sh 
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh thanks for this cleanup!
/approve
/lgtm

**Pull request merged**
