### PR TITLE
Configure 1.1 branch to use numeric-only names for upgrade jobs

### PR DESCRIPTION
**Pull request by ikehz**
Other half of #23096.

### CODE REVIEW

**Comment by ihmccreery** [comment]
@eparis How do I do this, now that @k8s-merge-robot is complaining?  This change doesn't make sense as a cherry-pick, because it's a test configuration.

**Comment by eparis** [comment]
just call it a cherry-pick and get @bgrant0607 approval.

**Comment by ihmccreery** [comment]
@k8s-bot test this again issue #23638

**Comment by spxtr** [comment]
LGTM

**Comment by ihmccreery** [comment]
Submitting along with #23096.

**Pull request merged**
