### PR TITLE
apimachinery/clock: Delete the apimachinery/clock package

### LINKED ISSUE #94738: There are two clock packages with divergent history
**What happened**:
I discovered a need to update one of the two clock packages, and preparation for that revealed the divergent history of the two.

One line of development can be seen in
- https://github.com/kubernetes/kubernetes/commits/0fdb33b25e3cb207705f225aec7d30b900dd1e89/staging/src/k8s.io/client-go/util/clock/clock.go , and then
- https://github.com/kubernetes/kubernetes/commits/master/staging/src/k8s.io/apimachinery/pkg/util/clock/clock.go

It looks like early on that was cloned into k8s.io/utils, and from there we have an independent line of development:
- https://github.com/kubernetes/utils/commits/master/clock/testing/fake_clock.go

**What you expected to happen**:
The two clock packages would be kept in sync for a while and then one removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Delete the clock package after having a soak period
of 1 release cycle (1.24). The package that should
be used now is the k8s.io/utils/clock package.

#### Which issue(s) this PR fixes:

Fixes #94738

#### Special notes for your reviewer:

It was suggested that we wait for a release or two to make it easier for folks to migrate
their code: https://github.com/kubernetes/kubernetes/issues/94738#issuecomment-931386501

Types were deprecated in 1.23.

#### Does this PR introduce a user-facing change?

```release-note
apimachinery/clock: This deletes the apimachinery/clock package. Please use k8s.io/utils/clock instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @MikeSpreitzer @liggitt

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Do we have a community policy that says how long the soak period should be?

**Comment by fedebongio** [comment]
@MikeSpreitzer I actually don't know, but looks like we don't have one official policy for packages. 

/cc @lavalamp @deads2k @liggitt 
/triage accepted

**Pull request merged**
