### PR TITLE
Automated cherry pick of #46395

### PR DESCRIPTION
**Pull request by rohitagarwal003**
Cherry pick of #46395 on release-1.6.

#46395: Implement FakeVolumePlugin's ConstructVolumeSpec method

### CODE REVIEW

**Comment by msau42** [comment]
@k8s-bot ok to test

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
