### PR TITLE
[go] Bump images, versions and deps to use Go 1.20.5

### PR DESCRIPTION
**Pull request by jeremyrickard**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

* Bump images, dependencies and versions to go 1.20.5

/assign @dims
cc https://github.com/orgs/kubernetes/teams/release-managers

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3099

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Go 1.20.5
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/milestone v1.28

### CODE REVIEW

**Comment by dims** [comment]
still in draft @jeremyrickard - poke me please when ready for review? thanks!

**Review by thockin — COMMENTED** [review]
/approve

**Pull request merged**
