### PR TITLE
Make log-dump use 'gcloud ssh' for GKE also

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/test-infra/issues/4323

I tested it locally (with some hacking for mimicking gke's DumpClusterLogs function in kubetest) and it worked.

cc @ericchiang

### CODE REVIEW

**Comment by krzyzacy** [comment]
shall we give it a different name to differentiate between `ssh-to-node` from cluster/gce/util.sh?

**Comment by shyamjvs** [comment]
Can do that - though in effect this one will just overwrite it currently.
Ideally we should use the one in cluster/gce/util.sh also for GKE (which is tricky since we don't have a cluster/gke/util.sh anymore). Added a TODO for now.

**Comment by krzyzacy** [comment]
gke has something in kubetest: https://github.com/kubernetes/test-infra/blob/master/kubetest/gke.go#L308-L322 - which is also gross

maybe we want to move the log-dump logic into kubetest in the future, which can be more clear for each provider.

**Comment by shyamjvs** [comment]
Nevermind, I fixed it to use the actual ssh-to-node for gke too.

**Comment by zmerlynn** [comment]
I would really rather avoid bringing in the bash here at all - this script needs to die, and its dependence on the cluster/* dir needs to die with it. This is only extending it.

**Comment by shyamjvs** [comment]
I agree that we should eventually move out the bash code. However that invites quite some changes as there are multiple dependencies (across cloud-providers) which the script is using currently.
This fix should go in for now to unblock debugging our gke tests. We can work on the long-term fix later - I'm afraid I won't be having time for that before this release.

**Comment by zmerlynn** [comment]
I don't think this was the right direction - the custom provider, with IPs, would've gotten you everything except serial console output (which didn't exist when I ported it).

**Comment by shyamjvs** [comment]
Explained the reason here - https://github.com/kubernetes/test-infra/issues/4323#issuecomment-328996765

**Comment by zmerlynn** [comment]
Can you at least add a TODO with a deadline to remove it?

**Comment by zmerlynn** [comment]
Perferably to remove the whole script. :p

**Comment by shyamjvs** [comment]
Done. But I didn't put a deadline as I can't commit to one - I have some more critical things on my plate currently.

**Comment by krzyzacy** [comment]
I'll try to move the dump logic from here to kubetest and rewrite in go, maybe next quarter.

**Comment by shyamjvs** [comment]
> I'll try to move the dump logic from here to kubetest and rewrite in go, maybe next quarter.

[Logexporter](https://github.com/kubernetes/test-infra/tree/master/logexporter) pretty much implements this logic and is written in go (and it's much much cleaner and efficient as it runs as a daemonset on the cluster). It's also a cloud-provider independent tool since it belongs to the k8s plane. Though we still need SSH as a fallback for nodes in case there are some k8s control-plane failures.

And I'm a bit hesitant in moving the dump logic from here to kubetest as log-dump.sh is a script that needs to live independent of test-infra (as someone who's running tests on their local clusters should also be able to use it - the reason why we have this script in the k8s repo). Earlier discussion about this - https://github.com/kubernetes/kubernetes/pull/49426#issuecomment-317477577

**Comment by krzyzacy** [comment]
@shyamjvs thanks for the pointing, missed that thread. And why we haven't flip logexporter on yet? I forgot the reason behind.

**Comment by zmerlynn** [comment]
I actually don't agree with the assessment there. `kubetest` is very much part of our e2e infrastructure now - it's not just test-infra. I wouldn't object to the polymorphism needed here being implemented in `kubetest` because `kubetest` already has the concept of a `deployer`, which is what you need here. The code that runs on the node is important, too, but only for the "mostly working" case. A lot of the interesting cases, logexporter is not useful.

**Comment by zmerlynn** [comment]
This is perhaps jaded by the fact that 90% of the issues I look at are cluster-lifecycle issues, of course.

**Comment by shyamjvs** [comment]
@krzyzacy Because it's not cherry-picked to earlier releases. Though I guess turning it on by default should still not hurt those jobs - they should just remain unaffected (i.e. using the traditional ssh method) neglecting the additional logexporter-related params.

**Comment by shyamjvs** [comment]
@zmerlynn The logdump script should be usable even outside our e2e framework. All it does is getting logs from the entire cluster, which someone who's running some experiments on a cluster (having nothing to do with e2e framework at all) should also be able to use.

> The code that runs on the node is important, too, but only for the "mostly working" case. A lot of the interesting cases, logexporter is not useful.

I agree that logexporter will not be useful when the cluster's not working, that's why we fallback to the default mode of SSH'ing. But such failures shouldn't be too common (if they are then we're having a bigger trouble of jobs failing very frequently and they should be fixed).

**Comment by zmerlynn** [comment]
We've made a conscious choice to move things like this out of the main
repo. Anything that needs knowledge of the specifics of the deployment
should live outside the main k8s repo. So whether it's a separate binary or
moved into kubetest, it should go

**Comment by shyamjvs** [comment]
I'm not against the fact that the log-dump script should be independent of deployer-specific logic. Just saying that we need it to work from within this repo (for e.g even without someone running e2e tests) :)

**Comment by krzyzacy** [comment]
@foxish ^^ cvm-1.7.5 does not have this fix

**Pull request merged**
