### PR TITLE
[pkg/watch/json]: remove dead code

### PR DESCRIPTION
**Pull request by ideapark**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note none

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
This seems OK given that nobody in-tree references it and that there's almost nothing in this directory.

@lavalamp or @deads2k - any objections?

/approve
/lgtm
/hold

@thinpark - give the API machinery leads a chance to look at it and if no concerns, go ahead and clear the hold.

**Comment by lavalamp** [comment]
Not sure how this happened, but I think the canonical copy is maybe [here](https://github.com/kubernetes/kubernetes/blob/d08e68e75974eb31fd65422c969b352ed8397edc/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/watch.go#L31).

/lgtm
/approve

**Pull request merged**
