### PR TITLE
Revert "Enable pod level cgroups by default"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#41349

This PR seems to visibly increase pod startup latency - for more details see:
https://github.com/kubernetes/kubernetes/issues/42000#issuecomment-282288939

@derekwaynecarr @justinsb @vishh

### CODE REVIEW

**Comment by wojtek-t** [comment]
For now I added do-not-merge label, as I would like to confirm it locally (and give chance for @derekwaynecarr to take a look).

**Comment by ncdc** [comment]
Thanks for putting do-not-merge on it. We'd definitely like a chance to review and see if there's anything obvious that could be fixed. cc @smarterclayton

**Comment by derekwaynecarr** [comment]
@sjenning has a PR tagged that will let us see the latency for cgroup create, update, delete calls.

https://github.com/kubernetes/kubernetes/pull/41988

Can we wait for that to merge so we know what the dominant time actually is?  I also would prefer that we NOT do a full revert of the commit, but just disable the flag if needed.  There was another commit in that PR that is needed for node allocatable to function.

**Comment by wojtek-t** [comment]
@derekwaynecarr - I'm fine with waiting until Monday. Also, reverting just the flag default sounds ok.

**Comment by wojtek-t** [comment]
@derekwaynecarr - we talked with @gmarek about this PR. And basically we are observing these problems in kubemark-500. But in kubemark by-design we are running multiple (in kubemark-500 ~80) hollow-kubelets on a single node of base cluster (and these hollow-kubelets are running as pods).

That means, that those hollow-kubelets are running in cgroups after your PR. Which means that maybe we are now enforcing resource isolation differently between the, so maybe this can lead to such things?
That's kind of guessing, but we should understand what exactly is happening here.

**Comment by derekwaynecarr** [comment]
@wojtek-t -- i prefer understanding over revert hammer.  are the hollow-kubelets best effort qos?

**Comment by jsafrane** [comment]
I think it might be related, I can't start pods on my Fedora 24:

```shell
$ kubectl describe pod
...

  26s           11s     3       kubelet, ip-172-18-12-230.ec2.internal  spec.containers{busybox}        Normal  Pulling         pulling image "gcr.io/google_containers/busybox"
  26s           10s     3       kubelet, ip-172-18-12-230.ec2.internal  spec.containers{busybox}        Normal  Pulled          Successfully pulled image "gcr.io/google_containers/busybox"
  26s           10s     3       kubelet, ip-172-18-12-230.ec2.internal  spec.containers{busybox}        Warning Failed          Failed to create container with error: rpc error: code = 2 desc = Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
  26s           10s     3       kubelet, ip-172-18-12-230.ec2.internal                                  Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "busybox" with rpc error: code = 2 desc = Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice": "Create Container Failed"
```

If I manually apply this PR (i.e. revert #41349), it starts working .

**Comment by derekwaynecarr** [comment]
@jsafrane -- that is not related.  what docker cgroup execution driver are you running and what is the value for your --cgroup-driver for kubelet.  they need to match.  pass --cgroup-driver=systemd and --cgroup-root=/ and you are fine

**Comment by derekwaynecarr** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/42052

**Pull request closed without merging**
