### PR TITLE
Automated cherry pick of #126966: Update cni-plugins to v1.5.1

### PR DESCRIPTION
**Pull request by saschagrunert**
Cherry pick of #126966 on release-1.31.

#126966: Update cni-plugins to v1.5.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Updated cni-plugins to [v1.5.1](https://github.com/containernetworking/plugins/releases/tag/v1.5.1).
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @kubernetes/release-engineering

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/assign @dims

**Comment by saschagrunert** [comment]
@kubernetes/release-engineering PTAL

**Review by xmudrii — APPROVED** [review]
For cherry-pick approval

**Pull request merged**
