### PR TITLE
Fix improperly formatted Calico CRD files

### PR DESCRIPTION
**Pull request by caseydavenport**
#### What type of PR is this?

/kind failing-test

Resulting in failing tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1390417411659796480

#### What this PR does / why we need it:

This commit broke the Calico manifests: https://github.com/kubernetes/kubernetes/commit/6d86fc6a15f7134ec80b55ba174615919201783e

This fixes the CRDs so they can be installed properly.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/test
want to check what is the network policy job

**Comment by pacoxu** [comment]
Thanks.
😂

**Pull request merged**
