### PR TITLE
cleanup: omit redundant arguments in make call

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Simplify make call by omitting redundant arguments 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by DangerOnTheRanger** [comment]
Slice capacity is equivalent to length if only one number is passed to `make`, so I agree that it's redundant. LGTM from me as soon as CI is green!

/ok-to-test

**Comment by HecarimV** [comment]
> Slice capacity is equivalent to length if only one number is passed to `make`, so I agree that it's redundant. LGTM from me as soon as CI is green!

Thanks for your review, the CI has passed.

**Pull request merged**
