### PR TITLE
Define TestableConfig in k/apiserver/pkg/util/flowcontrol

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Collect the parameters of newTestableController into a named type.

Also tolerate the surprising situation in which a request's user
groups include neither `system:authenticated` nor
`system:unauthenticated` --- because this is observed to happen in
some tests.

Also a few other minor fixups.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This was originally part of #97036 , and was factored into a separate PR in response to review.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@lavalamp 
@deads2k 
@yue9944882 
@adtac 
@tkashem 
@ahg-g 
@MikeSpreitzer

**Review by yue9944882 — COMMENTED** [review]
LGTM

these refactoring is basically trivial

**Comment by wojtek-t** [comment]
/lgtm

Thanks!

**Pull request merged**
