### PR TITLE
kubeadm: bump to use golang generic

### PR DESCRIPTION
**Pull request by chendave**
pls refer to https://github.com/kubernetes/kubernetes/pull/112377 for details, I am not sure when the legacy approach is not available, but we'd better not to use the deprecated code.

NOTE:  this is on top of https://github.com/kubernetes/kubernetes/pull/113462, so only the second commit need to be reviewed in this pr.

#### What type of PR is this?

/kind deprecation
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i don't object to this change but also not sure why we need it. are the old ways of using sets deprecated?

/cc @pacoxu @SataQiu 
what is your position on generics?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/community/blob/master/sig-architecture/generics.md#generics-policy
According to sig arch decisions, I think we can start using it. However, we need to know the benefit better.
- Will this cause extra effort for a bugfix that needs to be cherry-picked to the old version?

I prefer to use it in new feature implementation and tests, or elsewhere we really need it.

**Comment by neolit123** [comment]
cherry picks are my biggest concern and because of that i would prefer if we do not add generics to our code base.

**Comment by chendave** [comment]
> are the old ways of using sets deprecated?

@neolit123 yes, it's deprecated, you will see the deprecated warning in the IDE, here is the source for the deprecation, https://github.com/kubernetes/kubernetes/blob/7d9c0e0a78e519cac0f892a8be2f063bedc94bad/staging/src/k8s.io/apimachinery/pkg/util/sets/string.go#L19-L25

> cherry picks are my biggest concern

I don't understand what's the cherry pick you meant here? could you pls elaborate a little bit?

> However, we need to know the benefit better.

@pacoxu  you might find some data given by the original commit in the apimachinery

https://github.com/kubernetes/kubernetes/pull/112377#issuecomment-1274621907


Overall, from my point of view, since this is deprecated in the apimachinery, eventually, we need to migrate to this way to use it even this might not the best time to do that.

**Comment by pacoxu** [comment]
It would be ok to merge this as there is a deprecated message.
However, I still prefer to merge this in the next release cycle as this is not that urgent.

**Comment by chendave** [comment]
>  I still prefer to merge this in the next release cycle as this is not that urgent.

+1

let's hold this until 1.27 is open

**Comment by neolit123** [comment]
> let's hold this until 1.27 is open

+1

> I don't understand what's the cherry pick you meant here? could you pls elaborate a little bit?

backport to old kubeadm where an older golang is used and generics are unsupported.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by chendave** [comment]
Just note that I will rebase this in my next day.

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
