### PR TITLE
Re-activate DaemonRestart tests, they've been clean in gce-flaky for > 10 runs

### PR DESCRIPTION
**Pull request by brendandburns**
@quinton-hoole @ixdy

### CODE REVIEW

**Comment by quinton-hoole** [comment]
This test just failed it's last run.  What makes you think it's fixed?

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:240
Sep 29 13:42:58.193: RcManager created/deleted pods after restart

/job/kubernetes-e2e-gce-flaky/5534

**Comment by brendandburns** [comment]
@quinton-hoole (to be fair, that's the first time that one flaked in 20 runs)

I've extended the regexp.  The other two tests continue to be stable.

--brendan

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Ref/ #14693

**Comment by quinton-hoole** [comment]
One of the tests matched by your new regex just failed again.  Removing LGTM.  It's definitely still flaky (2 failures out the past 10 runs).
To be clear, we have 150 tests, so if each one fails say 1 out of 30 runs, statistically every single run will fail.  So observing a test to not have failed for 20 runs is not useful, unless an actual bug was found and fixed.

job/kubernetes-e2e-gce-flaky/5546/

Identified problems

DaemonRestart Controller Manager should not create/delete replicas across restart

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:240
Sep 30 07:34:19.853: RcManager created/deleted pods after restart

**Comment by brendandburns** [comment]
@quinton-hoole that's exactly the test that should be marked as still flaky by this regexp...  Am I misunderstanding something?

**Comment by quinton-hoole** [comment]
@brendandburns you are so right.  LGTM.  Sorry.

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Pull request merged**
