### PR TITLE
Make nodePort optional in v1 API

### PR DESCRIPTION
**Pull request by thockin**
@bgrant0607 Is this change kosher?  It's low risk, but not STRICTLY compatible...

### CODE REVIEW

**Comment by bgrant0607** [comment]
The current swagger spec is inconsistent with our validation code. One of them must be considered wrong. 

LGTM

**Comment by bgrant0607** [comment]
Ref #12774

**Comment by bgrant0607** [comment]
Also ref #8901

**Comment by thockin** [comment]
Now can I change it to be a pointer, so it does not get emitted when 0 ?

**Comment by bgrant0607** [comment]
We don't guarantee stability of the Go structs, but would need to think about compatibility between new client and old server, and vice versa.

**Pull request merged**
