### PR TITLE
Use watch param instead of deprecated /watch/ prefix

### PR DESCRIPTION
**Pull request by liggitt**
Reopen of https://github.com/kubernetes/kubernetes/pull/41722 after reverted in https://github.com/kubernetes/kubernetes/pull/41774

Required https://github.com/kubernetes/kubernetes/pull/41797 to merge first

cc @deads2k @wojtek-t

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton as original approver

**Comment by liggitt** [comment]
@k8s-bot bazel test this@k8s-bot gce etcd3 e2e test this

**Comment by wojtek-t** [comment]
I'm afraid this broke kubemark-500 again (so @deads2k fix didn't help - metrics seem to be broken again).

**Pull request merged**
