### PR TITLE
Support specifying percentages in PDB for pods controlled by Jobs

### PR DESCRIPTION
**Pull request by linxiulei**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR add support to specify percentages in PDB for pods controlled by Jobs. 

Without this PR, `disruption` controller reports error `"Failed to sync PDB" err="jobs.batch does not implement the scale subresource" podDisruptionBudget="default/job-pdb".`

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
TODO
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
cc @soltysh
was something like this attempted before?

**Comment by jiahuif** [comment]
I wonder if this is worth its own KEP.
/remove-sig api-machinery

**Comment by soltysh** [comment]
/hold
/close
this was was discussed with sig-apps on Dec 11th, the majority of the sig is against implementing this functionality, we don't envision expanding PDBs to support jobs in the near future

**Comment by linxiulei** [comment]
/reopen

I think the PR was not really about making PDB support Jobs, which is already implemented. Instead, this PR was to make PDB support percentage values in `minAvailable` (i.e. 50% instead of 5) for Jobs. So it might be worthwhile to have a conclusive opinion in whether if PDB should support Job completely or not

**Pull request closed without merging**
