### PR TITLE
follow our go code style: error->err

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubernetes/kubernetes/issues/50189
```release-note
NONE
```

### CODE REVIEW

**Comment by shiywang** [comment]
/assign @k82cn 
/assign @resouer 
similar to https://github.com/kubernetes/kubernetes/pull/47393 
@justinsb mind take a look ?

**Comment by k82cn** [comment]
any tools to check it? e.g.  golint

**Comment by shiywang** [comment]
@k82cn I tried `./hack/verify-golint.sh` seems it can't do sanity check for naming rules like this for now, I'm not sure if we can add more coding style check refer to [our code conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md).

ping @Random-Liu @dchen1107 for approval

**Comment by shiywang** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by k82cn** [comment]
en, yes. it seems golint did not check against such kind of code style.

prefer to open an issue for code conventions; I got different feedback for such kind of code style :).

**Comment by k82cn** [comment]
please rebase.

**Comment by shiywang** [comment]
@k82cn done, ptal

**Comment by k82cn** [comment]
/lgtm

please ping kubelet's approvers for approval :).

**Comment by shiywang** [comment]
ping @Random-Liu @dchen1107 for approval

**Comment by shiywang** [comment]
/assign @dchen1107  
for approval

**Comment by shiywang** [comment]
@Random-Liu sorry, I think this pr need an `/approval no-issue` here since it doesn't address any specific issue.

**Pull request merged**
