### PR TITLE
WIP - DO NOT MERGE - Run tests with 1.22 beta APIs removed

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**

Exercise CI / tests without beta APIs served that will be removed in 1.22.

Not intended to merge, just to ensure all kube components work properly

Failures seen:

---

shouldServe needs to adjust to check the external type, added a commit

---

failure starting a server:
```
E0203 12:17:07.824311   62077 updater.go:139] retry 2, failed to update storage version for csidrivers.storage.k8s.io: StorageVersion.internal.apiserver.k8s.io "storage.k8s.io.csidrivers" is invalid: status.storageVersions[0].decodableVersions: Invalid value: []string{"storage.k8s.io/v1"}: decodableVersions must include encodingVersion storage.k8s.io/v1beta1
```
@roycaihw - does that mean DecodableVersions is being built from our REST storage map? that will not include everything we are able to decode (we no longer serve extensions/v1beta1 ReplicaSets but we can still decode them)

---

/cc @deads2k

### CODE REVIEW

**Comment by liggitt** [comment]
looks like `shouldServe` returning false is not actually stopping serving the type

**Comment by liggitt** [comment]
`resourceServingInfo.New()` returns the internal type, which does not implement the APILifecycleDeleted interface

**Comment by liggitt** [comment]
failure starting a server:
```
E0203 12:17:07.824311   62077 updater.go:139] retry 2, failed to update storage version for csidrivers.storage.k8s.io: StorageVersion.internal.apiserver.k8s.io "storage.k8s.io.csidrivers" is invalid: status.storageVersions[0].decodableVersions: Invalid value: []string{"storage.k8s.io/v1"}: decodableVersions must include encodingVersion storage.k8s.io/v1beta1
```

**Comment by roycaihw** [comment]
sorry for the late reply. Yes, this is a bug in storage version API. David has a fix in https://github.com/kubernetes/kubernetes/pull/99951.

**Pull request closed without merging**
