### PR TITLE
Change rbd base image back to fedora 26

### LINKED ISSUE #67269: RBD tests fail with hostname: command not found\n/bootstrap.sh
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
e2e tests which use RBD server image fail with ```hostname: command not found\n/bootstrap.sh```

**What you expected to happen**:
These tests succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Run e2e tests which use RBD server image.

**Anything else we need to know?**:
/sig storage

This issue is introduced by below commit:
https://github.com/kubernetes/kubernetes/commit/f4caccccfe49bc1075842d18c84385ebbab6a9c7#diff-e5d0ceccff9054af3c69ac1b4d5930d2R18

It change the base image from fedora 26 to fedora 28.
In fedora 26, hostname command is installed as a dependency for [```RUN yum install -y wget strace psmisc procps-ng ceph ceph-fuse && yum clean all```](https://github.com/kubernetes/kubernetes/blob/master/test/images/volume/rbd/Dockerfile#L23)
However, in fedora 28, it is not installed, as a result, this issue happens due to lack of hostname command.

**Environment**:
- Kubernetes version (use `kubectl version`): k8s 1.12 alpha

### PR DESCRIPTION
**Pull request by mkimuram**
Due to the compatiblility issue for ceph server, it needs to change
back to fedora 26 from fedora 28, as a workaround.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67269

**Special notes for your reviewer**:
/sig storage
@dims @rootfs

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mkimuram** [comment]
@dims @rootfs 

Please review and ok-to-test it.

**Comment by rootfs** [comment]
/assign @luxas @ixdy 
for approval

**Comment by dims** [comment]
LGTM 👍

**Comment by mkimuram** [comment]
@luxas @ixdy

Could you approve it?

**Comment by ixdy** [comment]
/approve
/hold

I am unable to push this because `docker manifest` is broken on linux. https://github.com/docker/for-linux/issues/396

**Comment by ixdy** [comment]
/hold cancel

was able to push it after all

**Pull request merged**
