### PR TITLE
Move HPA v2beta2 deprecation to 1.23.

### PR DESCRIPTION
**Pull request by josephburnett**
#### What type of PR is this?

/kind cleanup
/kind deprecation

#### What this PR does / why we need it:

We are creating an HPA v2 stable API to replace the HPA v2beta2 API (https://github.com/kubernetes/enhancements/issues/2702).  We have been working toward landing the stable API in v1.22 ([tracking doc](https://docs.google.com/document/d/1QGT9Waxc500ICGX_TGIoxfOWKmWbXYC6TWxfdUC2Njg/edit#)), the version in which v2beta2 is slated for deprecation.  However in the course of creating the new API we have discovered a few places for improvement.

For example, we see an opportunity to create a common meta.v1 ObjectReference to replace the many api-group-specific object references ([comment](https://github.com/kubernetes/kubernetes/pull/102534#discussion_r650776250)).

And we would like to use the existing meta.v1 Condition instead of the autoscaling-specific conditions.  However there is some additional data we need to populate and we need time to figure out how ([comment](https://github.com/kubernetes/kubernetes/pull/102534#discussion_r650825535)).

Therefore we would like to defer the deprecation of v2beta2 to 1.23 so have time to make this change carefully and improve the ecosystem around us.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

KEP: [sig-autoscaling/2702-graduate-hpa-api-to-GA/README.md](https://github.com/supriya-premkumar/enhancements/blob/bf8ae4c23a13ec030058c059bc98fef7e95c24b9/keps/sig-autoscaling/2702-graduate-hpa-api-to-GA/README.md)

### CODE REVIEW

**Comment by thockin** [comment]
This seems like it should be non-contentious?

/approve

**Comment by josephburnett** [comment]
Needs lgtm label.

**Comment by liggitt** [comment]
> This seems like it should be non-contentious?

This is extending v2beta2 past https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/1635-prevent-permabeta/

v2beta2 was added in 1.12

The deprecation clock was started in 1.19 as part of https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/1635-prevent-permabeta/

All beta API versions were on the clock as of 1.19. The motivation remains to avoid accumulating additional usage on an API version we know will not be around long term.

I think the 1.22 deadline should remain. If more time before GA is needed, a v2beta3 could be reasonable.

**Comment by mwielgus** [comment]
@liggitt 
We made an effort to graduate it 1.22 but additional, unexpected changes were requested (common object reference type in meta). The person working on this didn't manage to get them approved before going for well deserved vacation. He is, however, more than committed to finish everything for 1.23.  

This is an unfortunate situation, I fully understand the need of getting apis out of beta, but creating a v2beta3, exactly the same as v2beta2 (or a half-baked GA) with a sole purpose of bypassing the deadline doesn't make sense in my opinion. There is also no person at this moment who can drop everything and do it before the code freeze on Jul 8th (vacation season is starting after months of lockdown). Making v2beta2 deprecated without a proper version will confuse users - they have no other version to go. And they will have to ignore it. 

The exceptional move of deprecation marker by one version is, in my opinion, the lesser evil.

**Comment by thockin** [comment]
Have we decided what we want to do here?  I see both sides, for sure, but I
worry abut punishing users in this case.

**Comment by liggitt** [comment]
The reasons for "just one more release" could easily be applied to every beta version that wasn't prioritized and wasn't ready for promotion by the deprecation deadline. Starting a review 3 weeks before code freeze for the release where the beta version is deprecated is too late. I think it is a bad precedent to set to casually lengthen the lifetime and accumulate another 4 months of usage on this version.

**Pull request merged**
