### PR TITLE
Hyperkube cleanup

### PR DESCRIPTION
**Pull request by thockin**
In response to the hyperkube refactorings, which I did not make time to review, I send my review in the form of a PR.  Open for debate.

This focuses on 2 things:

1) cmd/\* should not need to know about how they are used (ie standalones or hyperkube).  But they can be factored to make different usage possible.  Keep all of the noise about hyperkube in a hyperkube directory.

2) Flags in libs is an anti-pattern.  The flags are rightly part of the the top-level application, even if that application is librarified for reuse in different apps.

I also folded pkg/hyperkube into cmd/hyperkube, since it is not used anywhere else and is not really a useful abstraction on its own.  I could be talked out of this, so I left it as a separate commit.

### CODE REVIEW

**Comment by thockin** [comment]
This conflicts with my own #4233 - I'll have to hand-merge whichever one loses the race (assuming this one flies at all)

**Comment by mbforbes** [comment]
Assigning @brendandburns because of coarse area; please feel free to re-assign!

**Comment by smarterclayton** [comment]
Agree deeply on 2 above.

**Comment by smarterclayton** [comment]
The `cmd/hyperkube` vs `pkg/cmd/hypercube` comes down to whether you *ever* want someone to reuse the code.  After a while of fiddling back and forth, I started to lean towards packages with "main" having as few lines of code as possible... i.e. they should only be a `func main() {}` and a few lines of startup code.  Everything else (including opinionated setup) can be in a package, with little downside.  package `main` is really the `private` keyword, and I think there is some small value in letting people reuse your top level start constructs (for test suites or integration code).

We *might* be interested in exposing the hyperkube commands as sub-commands of openshift in the future, for simple convenience (need to run the proxy, just step right up and use this handy nested command).  Right now we have more of an opinionated setup (no flags, very little choice of how the setup goes) so we're calling into components directly.

But ultimately no strong preference on 1.

**Comment by thockin** [comment]
@smarterclayton You can put all your app logic in a package, but that package should (IMO) live under cmd/ not under pkg/ .  With very few exceptions, flags should be declared by code that knows it is a command, and not code that thinks it is a generic lib.

**Comment by thockin** [comment]
I'll rebase this again - but are there fundamental disagreements with this?  It's painful to keep rebasing

**Comment by smarterclayton** [comment]
Because it's Friday:

But if you have a reusable command, isn't that a library?

**Comment by thockin** [comment]
@satnam6502 regarding flag changes

**Comment by thockin** [comment]
There are libs that are really very much "app logic" and libs that are "plausibly generic utility logic".  Reasonable people can probably argue about where the line between them is.  My rule of thumb is whether I can reason about using the API to a module in a totally different app (where busyboxing a bunch of crap together does not count as "different").  Flags are ab obvious red flag - generic libs can not, by definition, know enough about the app they are used in to declare flags.

We violate this every hour of every day in Google, and I hate it.  Some apps, when you run --help, dump THOUSANDS of flags, 99.9% of which no user of that app will ever set.

**Comment by smarterclayton** [comment]
I do not disagree that is a problem.  It's only when reuse is relevant that there's value - for instance cobra defines command local flags, so you use a New* method to get a command which has its flags neatly packaged together.  Static flag registration across scopes is agreed bad.

**Comment by thockin** [comment]
So are you against this PR in whole, in part, or not at all? :)

**Comment by smarterclayton** [comment]
Not at all, I needed a good bike shed and this was a convenient target

**Comment by thockin** [comment]
Happy to help.  Anything else I can do to lubricate my way to an LGTM?

**Comment by thockin** [comment]
rebased again.

ping?

**Comment by thockin** [comment]
Rebased.  ping again.

**Comment by thockin** [comment]
I'll self-commit if I have to ping one more time, so help me :)

**Comment by smarterclayton** [comment]
Test flake (sync bad hash apparently wasn't deflaked)

**Comment by satnam6502** [comment]
@smarterclayton : I assume you will drive this towards a merge -- otherwise I can review and then merge to save @thockin the indignity of self merging.

**Comment by thockin** [comment]
All green

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
(I'll make a follow-up PR to fix some GOMAXPROCS stuff)

**Pull request merged**
