### PR TITLE
Fix broken links in kubelet after moving proposals to subdirs

### LINKED ISSUE #918: Organize Design Proposals Folder
The design proposals folder is getting a little out of hand, and we could do a few things to help improve it.

- [ ] In lieu of sig subdirs, create functional area subdirs with clear ownership
- [ ] Create OWNERS files in those subdirs
- [ ] Disambiguate proposals from accepted changes as tracked by #914

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**:
fix incorrect links in kubelet after  kubernetes/community#1010

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes  kubernetes/community#918

**Special notes for your reviewer**:
CC @bgrant0607
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
Component flags are user-facing. We should be linking to kubernetes.io docs rather than design proposals.

**Comment by bgrant0607** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by huzhengchuan** [comment]
thanks, it will fix it @bgrant0607

**Comment by huzhengchuan** [comment]
@bgrant0607  i fix the comments, help me  review  it.

**Comment by huzhengchuan** [comment]
@resouer @tmrts  help me review it, thanks.

**Comment by bgrant0607** [comment]
@huzhengchuan Reviewers are generally auto-assigned based on OWNERS file. You can also notify the relevant SIG(s). cc @kubernetes/sig-node-pr-reviews

**Comment by huzhengchuan** [comment]
ok, I know. thanks for your help. @bgrant0607

**Comment by huzhengchuan** [comment]
Kindly ping @tmrts  @resouer  help review this fix, thanks!

**Review by resouer — APPROVED** [review]

**Comment by resouer** [comment]
/lgtm

minor fix, ping @yujuhong for approve

**Pull request merged**
