### PR TITLE
Update docs to describe new PR release-note block parsing.

### PR DESCRIPTION
**Pull request by david-mcmahon**

### CODE REVIEW

**Comment by david-mcmahon** [comment]
cc @bgrant0607

**Comment by david-mcmahon** [comment]
k8s-bot retest

**Comment by roberthbailey** [comment]
lgtm

**Comment by david-mcmahon** [comment]
Assigned @roberthbailey's in-line lgtm.

**Comment by david-mcmahon** [comment]
@k8s-bot retest: UNKNOWN

**Pull request merged**
