### PR TITLE
Fix golint errors in pkg/util/taints

### PR DESCRIPTION
**Pull request by markmc**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

General linter cleanup, part of KubeCon new contributor workshop

**Which issue(s) this PR fixes**:

Part of #68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/assign @vishh @dchen1107 

/ok-to-test
/lgtm

Thanks and hope you're having fun at the summit :)

**Comment by mattjmcnaughton** [comment]
Ah, it looks like from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78118/pull-kubernetes-typecheck/1130474974511894532, that there is still a reference to `NewTaintsVar` somewhere.

**Comment by markmc** [comment]
> Ah, it looks like from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78118/pull-kubernetes-typecheck/1130474974511894532, that there is still a reference to `NewTaintsVar` somewhere.
> 
> Should be an easy fix :)

Thanks, @mattjmcnaughton ! Clearly I need to improve my local testing foo

**Comment by markmc** [comment]
Error was e.g.

```
$ git fetch https://github.com/kubernetes/kubernetes.git pull/78118/head
From https://github.com/kubernetes/kubernetes
 * branch                  refs/pull/78118/head -> FETCH_HEAD
$ git merge --no-ff af8ef5ec49786f9a1819bf63473ab6acd6a261bd
merge: af8ef5ec49786f9a1819bf63473ab6acd6a261bd - not something we can merge
```

Sounds like kubernetes/test-infra#5541

**Comment by SataQiu** [comment]
Any update?  @markmc 
/approve

**Pull request closed without merging**
