### PR TITLE
Allow `build/run.sh make help` to run

### PR DESCRIPTION
**Pull request by spiffxp**
**What this PR does / why we need it**: typo fix; `build/run.sh make help` doesn't work for me on OS X w/ docker 1.13.x, this PR fixes that

**Release note**:

```release-note
NONE
```
 /cc @spxtr

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot unit test this

**Comment by ixdy** [comment]
manually tagging `approved` cause this is dumb.

**Pull request merged**
