### PR TITLE
Fix DNS latency of 5s when use iptables forward

### LINKED ISSUE #62628: DNS latency of 5s when uses iptables forward in pods network traffic
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The DNS will get a 5s latency of AAAA when uses iptables forward in network traffic between pods.

**What you expected to happen**:
No latency.

**How to reproduce it (as minimally and precisely as possible)**:
- CNI configuration
```{
        "name": "mynet",
        "type": "macvlan",
	"master": "eth0",
        "ipam": {
                "type": "host-local",
                "subnet": "172.20.0.0/17",
		"rangeStart": "172.20.64.129",
		"rangeEnd": "172.20.64.254",
		"gateway": "172.20.127.254",
		"routes": [
			{"dst":"0.0.0.0/0"},
			{"dst":"172.20.80.0/24", "gw":"172.20.0.62"}
		]
        }
}
```
-   Network Architecture
The cluster cidr is 172.20.80.0/24, gw is current node. Cluster, pods and nodes are in l2 network using VXLAN. 

**Anything else we need to know?**:
If cni gw of cluster cidr is current node, the network traffic between pods and services will use iptables forward:
```
-P FORWARD ACCEPT
-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD

-N KUBE-FORWARD
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 172.20.0.0/17 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 172.20.0.0/17 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```
If enable forwarding conntrack, netfilter will drop first AAAA record packet when requests dns. It will cause dns latency of 5s.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-327.18.2.el7.x86_64
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by xiaoxubeii**
**What this PR does / why we need it**:
Fix the dns latency of 5s when uses iptables forward.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62628

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@bowei @thockin

**Comment by MrHohn** [comment]
Would be great if we can have a cluster wide knob for tweaking this defaultDNSOptions so user can place this workaround via that. I believe this might help mitigate the packet dropping bug for pod DNS resolution, but whether there would be any other side effect is unclear to me and that's why I'm hesitated.

Another pod wide option would be something like below (similar to what you posted on https://github.com/weaveworks/weave/issues/3287#issuecomment-385896924):
```
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: nginx
  dnsPolicy: "ClusterFirst"
  dnsConfig:
    options:
      - name: single-request-reopen
```
The given options will be merged with the pre-set ones (e.g. `ndots:5`).

**Comment by Quentin-M** [comment]
I would just like to add here that the `single-request(-reopen)` workaround does not work with Alpine-based containers, as musl does not support the option (see below). Unfortunately, Alpine Linux is the base image to 90% of our infrastructure.

[src/network/resolvconf.c](https://git.musl-libc.org/cgit/musl/tree/src/network/resolvconf.c)
```
                if (!strncmp(line, "options", 7) && isspace(line[7])) {
                        p = strstr(line, "ndots:");
                        if (p && isdigit(p[6])) {
                                p += 6;
                                unsigned long x = strtoul(p, &z, 10);
                                if (z != p) conf->ndots = x > 15 ? 15 : x;
                        }
                        p = strstr(line, "attempts:");
                        if (p && isdigit(p[9])) {
                                p += 9;
                                unsigned long x = strtoul(p, &z, 10);
                                if (z != p) conf->attempts = x > 10 ? 10 : x;
                        }
                        p = strstr(line, "timeout:");
                        if (p && (isdigit(p[8]) || p[8]=='.')) {
                                p += 8;
                                unsigned long x = strtoul(p, &z, 10);
                                if (z != p) conf->timeout = x > 60 ? 60 : x;
                        }
                        continue;
                }
```

[src/network/lookup.h](https://git.musl-libc.org/cgit/musl/tree/src/network/lookup.h)
```
struct resolvconf {
        struct address ns[MAXNS];
        unsigned nns, attempts, ndots;
        unsigned timeout;
};```

**Comment by Quentin-M** [comment]
Here is the workaround we are about to use: https://github.com/weaveworks/weave/issues/3287#issuecomment-390383565

**Comment by xiaoxubeii** [comment]
@MrHohn OK, that's a compromise settlement, i will close the pr : )

**Comment by steven-sheehy** [comment]
Since we run various helm charts, not every pod we run is under our control to be able to add a custom dnsConfig to specify single-request-reopen. A custom kubelet flag to enable this would help, but I think this should be enabled by kubelet by default. From my understanding of the option, single-request-reopen sounds pretty safe since it provides a fallback for the existing functionality to try a new socket. If underlying libraries don't support it like alpine, it will just be ignored. Anyway this PR could be reopened?

**Comment by Quentin-M** [comment]
I just posted a little write-up about our journey troubleshooting the issue, and how we are worked around it in production: https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/. 

@steven-sheehy Our workaround does not involve setting dnsConfig, nor does it require any change from the users.

**Comment by steven-sheehy** [comment]
@Quentin-M I tried your workaround and it still occurs. Left a comment on your blog. We may be suffering from the SNAT race condition as well. Regardless, we at least need a [cluster level option](https://github.com/kubernetes/kubernetes/issues/59031) to tweak this.

**Comment by Quentin-M** [comment]
This workaround works for both SNAT and DNAT. Just a few thoughts:

You may have to adjust the latency by a few ms depending on your network conditions. 
You also would need to make sure that you are applying it to the right network interfaces depending on your CNI/network configuration.

**Pull request closed without merging**
