### PR TITLE
Fix: Removes Deprecated ioutil

### PR DESCRIPTION
**Pull request by donuts-are-good**
Happy Hacktoberfest! Thank you for taking a moment to review my PR!

#### What type of PR is this?
/kind cleanup
/kind deprecation
#### What this PR does / why we need it:
io/ioutil has been deprecated in favor of the drop in replacements "io" and "os". This commit addresses those instances of ioutil with the respective function replacements.
#### Special notes for your reviewer:
Happy Hacktoberfest! Thank you for taking a moment to review my PR!
#### Does this PR introduce a user-facing change?
NONE
```release-note

Deprecated: io/ioutil has been deprecated in go. In most cases this is a drop in replacement with 'io' and 'os'. This commit removes all usage of io/ioutil.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by donuts-are-good** [comment]
Am I supposed to be doing periodic rebases of this PR? I want this to get merged, but so far no interaction from an actual human on this PR.

**Comment by andyzhangx** [comment]
could you fix the merge conflict? thanks.

**Comment by bart0sh** [comment]
@donuts-are-good 

> Am I supposed to be doing periodic rebases of this PR? I want this to get merged, but so far no interaction from an actual human on this PR.

There are [a lot of attempts](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+deprecated+ioutil+is%3Aopen) to remove deprecated ioutil. Successful ones usually target relatively small amount of code. This approach has at least 3 advantages:
- it's easier to review / approve
- it doesn't require frequent rebasing
- it doesn't require review/approval from a lot of SIGs, which usually speeds up review and approval

However, if you want to do it once for the whole codebase, you'll have to rebase a lot unless you're lucky and your PR will be reviewed and approved fast.

**Comment by donuts-are-good** [comment]
> @donuts-are-good
> 
> > Am I supposed to be doing periodic rebases of this PR? I want this to get merged, but so far no interaction from an actual human on this PR.
> 
> There are [a lot of attempts](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+deprecated+ioutil+is%3Aopen) to remove deprecated ioutil. Successful ones usually target relatively small amount of code. This approach has at least 3 advantages:
> 
>     * it's easier to review / approve
> 
>     * it doesn't require frequent rebasing
> 
>     * it doesn't require review/approval from a lot of SIGs, which usually speeds up review and approval
> 
> 
> However, if you want to do it once for the whole codebase, you'll have to rebase a lot unless you're lucky and your PR will be reviewed and approved fast.

Thanks for the reply. What do you recommend, one file at a time?

**Comment by donuts-are-good** [comment]
Thanks for the attention @mmiranda96 - what action is required from the author? I'm new to the process and this is my first PR to k8s.

**Comment by mmiranda96** [comment]
@donuts-are-good I would recommend you to close this PR and instead create smaller ones. Try to tackle a couple of directories in the same PRs (something like max 5), and try to ensure each PR touches files from the same SIG. That way, you'll need less reviewers and approvers.

**Comment by donuts-are-good** [comment]
> @donuts-are-good I would recommend you to close this PR and instead create smaller ones. Try to tackle a couple of directories in the same PRs (something like max 5), and try to ensure each PR touches files from the same SIG. That way, you'll need less reviewers and approvers.

Sounds good to me thanks

**Pull request closed without merging**
