### PR TITLE
Automated cherry pick of #92258: Add logic to check if local NVMe SSDs in node boot-up script

### PR DESCRIPTION
**Pull request by SidneyShen**
Cherry pick of #92258 on release-1.18.

#92258: Add logic to check if local NVMe SSDs in node boot-up script

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by SidneyShen** [comment]
@kubernetes/release-managers
Please help with cherry-pick review

**Comment by SidneyShen** [comment]
@kubernetes/release-managers please help with the review and merge, thanks!

**Comment by tpepper** [comment]
I'd like to understand a little bit more the failure scenario, impact, and test coverage on this cherry pick.  The mainline PR is sparse on detail, doesn't say how common or likely this is.

**Comment by SidneyShen** [comment]
Hi @tpepper, thanks for the comments. The original logic in this script has the environment variable **NODE_LOCAL_SSDS_EXT** , the format of which will be "#,scsi/nvme,block/fs". Users can specify multiple configurations by separating them by a semi-colon ex. "2,scsi,fs;1,nvme,block" is a request for 2 SCSI formatted and mounted SSDs and 1 NVMe block device SSD. However the original code (the snippet I modified) assumes all the NVMe disks are attachable data disks. It did this by scanning all the disk symlink under the path "/dev/nvme*" and tries to format and mount available ones. However, it is possible that one of the NVMe is boot disk, which would ultimately fail the node boot. The current fix is a short-term workaround and straightforward, if user did not specify any NVMe disk via **NODE_LOCAL_SSDS_EXT**, the code should directly return instead return. This did not happen before if the boot disk is not behind NVMe controller or user did not specify the local ssd via **NODE_LOCAL_SSDS_EXT**.

**Comment by tpepper** [comment]
> This did not happen before if the boot disk is not behind NVMe controller or user did not specify the local ssd via **NODE_LOCAL_SSDS_EXT**.

Still unclear is the likelihood/impact.  Eg: Was this always happening but rare?  How did we miss it?  Was it impossible before or unlikely?  Is a new GCP feature causing this to now be possible and likely?

**Comment by SidneyShen** [comment]
> > This did not happen before if the boot disk is not behind NVMe controller or user did not specify the local ssd via **NODE_LOCAL_SSDS_EXT**.
> 
> Still unclear is the likelihood/impact. Eg: Was this always happening but rare? How did we miss it? Was it impossible before or unlikely? Is a new GCP feature causing this to now be possible and likely?

GKE currently only supports the SCSI disk as boot disk, there is no way for user to specify a boot disk behind NVMe controller. This failure did not happen on the existing clusters and regular machine types. As GCP is introducing new machine types using NVMe as boot disk, k8s will fail boot up on this new VMs due to this issue. That's said, this is a new issue for new VM types.

**Comment by tpepper** [comment]
> > > This did not happen before if the boot disk is not behind NVMe controller or user did not specify the local ssd via **NODE_LOCAL_SSDS_EXT**.
> > 
> > 
> > Still unclear is the likelihood/impact. Eg: Was this always happening but rare? How did we miss it? Was it impossible before or unlikely? Is a new GCP feature causing this to now be possible and likely?
> 
> GKE currently only supports the SCSI disk as boot disk, there is no way for user to specify a boot disk behind NVMe controller. This failure did not happen on the existing clusters and regular machine types. As GCP is introducing new machine types using NVMe as boot disk, k8s will fail boot up on this new VMs due to this issue. That's said, this is a new issue for new VM types.

Ok.  This sounds like adding feature support then and is less likely to be something we would cherry pick.

**Comment by tpepper** [comment]
Patch release has discussed and decided to treat this as a feature / non-priority-critical-urgent today for 1.17.  If the incidence increases (eg: this becomes something that can be hit, and it is being hit be test-infra) we can always choose in the future to backport it.

**Pull request closed without merging**
