### PR TITLE
Fix nil-map panic in AppArmor skip

### PR DESCRIPTION
**Pull request by krousey**

### CODE REVIEW

**Comment by yujuhong** [comment]
lgtm

**Comment by smarterclayton** [comment]
Panic, test, very low risk

/approve

**Comment by smarterclayton** [comment]
Also applying the label without slash :)

**Comment by ethernetdan** [comment]
@enisoc this should make `beta.4` also

**Comment by ethernetdan** [comment]
@k8s-bot bazel test this

**Pull request merged**
