### PR TITLE
Fixed propagation of kube master certs during master replication.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed propagation of kube-master-certs during master replication.

### CODE REVIEW

**Comment by mwielgus** [comment]
lgtm

**Comment by jszczepkowski** [comment]
@k8s-bot bazel test this
issue #40295

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this
issue #39471

**Comment by jszczepkowski** [comment]
@k8s-bot node e2e test this

**Comment by jszczepkowski** [comment]
@roberthbailey can you approve?

**Pull request merged**
