### PR TITLE
Share the host's timezone with the build container

### LINKED ISSUE #20791: Time(zone) logged in golang.sh is wrong
Time in status messages logged from `golang.sh` is `GMT+0` for some reason. I'm in `GMT+2`. 

The strange thing is that they both seem to use the same function `kube::log::status` in `cluster/lib/logging.sh`
Example output: 
```
$ make quick-release
KUBE_RELEASE_RUN_TESTS=n build/release.sh
----------------------- RIGHT ---------------------------
+++ [0207 20:46:50] Verifying Prerequisites....
+++ [0207 20:46:50] Building Docker image kube-build:cross-1.4.2-2.
+++ [0207 20:57:58] Building Docker image kube-build:build-b54447e80c.
+++ [0207 20:58:54] Running build command....
-------------------- WRONG -----------------------------
+++ [0207 18:58:55] Multiple platforms requested and available 13G >= threshold 11G, building platforms in parallel
+++ [0207 18:58:55] Building go targets for linux/amd64
    linux/arm in parallel (output will appear in a burst when complete):
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
+++ [0207 18:58:55] linux/amd64: go build started
+++ [0207 19:01:46] linux/amd64: go build finished
+++ [0207 18:58:55] linux/arm: go build started
+++ [0207 19:01:46] linux/arm: go build finished
+++ [0207 19:01:46] Multiple platforms requested and available 13G >= threshold 11G, building platforms in parallel
+++ [0207 19:01:46] Building go targets for linux/amd64
    linux/386
    linux/arm
    darwin/amd64
    darwin/386
    windows/amd64
    windows/386 in parallel (output will appear in a burst when complete):
    cmd/kubectl
+++ [0207 19:01:46] linux/amd64: go build started
+++ [0207 19:02:20] linux/amd64: go build finished
+++ [0207 19:01:46] linux/386: go build started
+++ [0207 19:03:05] linux/386: go build finished
+++ [0207 19:01:46] linux/arm: go build started
+++ [0207 19:02:20] linux/arm: go build finished
+++ [0207 19:01:46] darwin/amd64: go build started
+++ [0207 19:03:04] darwin/amd64: go build finished
+++ [0207 19:01:46] darwin/386: go build started
+++ [0207 19:03:06] darwin/386: go build finished
+++ [0207 19:01:46] windows/amd64: go build started
+++ [0207 19:03:06] windows/amd64: go build finished
+++ [0207 19:01:46] windows/386: go build started
+++ [0207 19:03:05] windows/386: go build finished
+++ [0207 19:03:06] Multiple platforms requested and available 13G >= threshold 11G, building platforms in parallel
+++ [0207 19:03:06] Building go targets for linux/amd64
    darwin/amd64
    windows/amd64 in parallel (output will appear in a burst when complete):
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0207 19:03:06] linux/amd64: go build started
+++ [0207 19:04:18] linux/amd64: go build finished
+++ [0207 19:03:06] darwin/amd64: go build started
+++ [0207 19:05:14] darwin/amd64: go build finished
+++ [0207 19:03:06] windows/amd64: go build started
+++ [0207 19:05:14] windows/amd64: go build finished
+++ [0207 19:05:14] Placing binaries
------------------- RIGHT ---------------------------------
+++ [0207 21:06:01] Running build command....
+++ [0207 21:06:03] Output directory is local.  No need to copy results out.
+++ [0207 21:06:03] Building tarball: salt
+++ [0207 21:06:03] Building tarball: manifests
+++ [0207 21:06:03] Starting tarball: client darwin-386
+++ [0207 21:06:03] Starting tarball: client darwin-amd64
+++ [0207 21:06:03] Starting tarball: client linux-386
+++ [0207 21:06:03] Starting tarball: client linux-amd64
+++ [0207 21:06:03] Starting tarball: client linux-arm
+++ [0207 21:06:03] Starting tarball: client linux-arm64
+++ [0207 21:06:03] Starting tarball: client linux-ppc64le
+++ [0207 21:06:03] Starting tarball: client windows-386
+++ [0207 21:06:03] Starting tarball: client windows-amd64
+++ [0207 21:06:03] Waiting on tarballs
+++ [0207 21:06:03] Building tarball: server linux-amd64
+++ [0207 21:06:05] Starting Docker build for image: kube-apiserver
+++ [0207 21:06:05] Starting Docker build for image: kube-controller-manager
+++ [0207 21:06:05] Starting Docker build for image: kube-scheduler
+++ [0207 21:06:05] Starting Docker build for image: kube-proxy
+++ [0207 21:06:38] Deleting docker image gcr.io/google_containers/kube-controller-manager:47b97fb78bdb6c3bdfd8a02a9839f538
Untagged: gcr.io/google_containers/kube-controller-manager:47b97fb78bdb6c3bdfd8a02a9839f538
Deleted: bb28a9ade9d7b7c1bf10edc8e7a1a0cdcd5f8149e022e29f04a754f0ca7bb193
+++ [0207 21:06:38] Deleting docker image gcr.io/google_containers/kube-scheduler:dd44edd0f08cbce228398d190ff31463
Untagged: gcr.io/google_containers/kube-scheduler:dd44edd0f08cbce228398d190ff31463
Deleted: b55718fd86ac4697e09d288f97ec9f206c987bd51276da9b5336aca36781c4b9
+++ [0207 21:06:38] Deleting docker image gcr.io/google_containers/kube-apiserver:2d8b816e76ee4641db581474dd4a1b83
Untagged: gcr.io/google_containers/kube-apiserver:2d8b816e76ee4641db581474dd4a1b83
Deleted: 944d553afb1eedf6f019716a4141dd8a859289216c828abe2ed6c53bbf03f07e
+++ [0207 21:06:53] Deleting docker image gcr.io/google_containers/kube-proxy:5b8dc1abf093c5f63806cbfa96346058
Untagged: gcr.io/google_containers/kube-proxy:5b8dc1abf093c5f63806cbfa96346058
Deleted: 96cb9004f0012829ffd07d8e86bec54ff7bb0d813eca83df676e9c4d0b294f5a
+++ [0207 21:06:53] Docker builds done
+++ [0207 21:06:53] Pulling and writing Docker image for addon: gcr.io/google_containers/pause:2.0
+++ [0207 21:06:53] Pulling and writing Docker image for addon: gcr.io/google_containers/kube-registry-proxy:0.3
Pulling repository gcr.io/google_containers/kube-registry-proxy
2.0: Pulling from google_containers/pause
Digest: sha256:9ce5316f9752b8347484ab0f6778573af15524124d52b93230b9a0dcc987e73e
Status: Image is up to date for gcr.io/google_containers/pause:2.0
Status: Image is up to date for gcr.io/google_containers/kube-registry-proxy:0.3
gcr.io/google_containers/kube-registry-proxy: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
+++ [0207 21:07:01] Addon images done
+++ [0207 21:07:40] Building tarball: server linux-arm
+++ [0207 21:07:40] Starting Docker build for image: kube-apiserver
+++ [0207 21:07:40] Starting Docker build for image: kube-controller-manager
+++ [0207 21:07:40] Starting Docker build for image: kube-scheduler
+++ [0207 21:07:40] Starting Docker build for image: kube-proxy
+++ [0207 21:07:45] Deleting docker image gcr.io/google_containers/kube-proxy-arm:9205b2a9c94914e742f39c7e59bcf995
+++ [0207 21:07:45] Deleting docker image gcr.io/google_containers/kube-scheduler-arm:57e40ffac0107f8b444997392e5c4d0f
Untagged: gcr.io/google_containers/kube-proxy-arm:9205b2a9c94914e742f39c7e59bcf995
Deleted: 5d547b3946b3050c3eb65f1599315898b13bc739f6cfb28c87e987176075f2f4
Untagged: gcr.io/google_containers/kube-scheduler-arm:57e40ffac0107f8b444997392e5c4d0f
Deleted: 8eaddd6d97ced14456516d7523a8a55d07dca7f87ea7b9dea7981bee763dfd50
+++ [0207 21:07:45] Deleting docker image gcr.io/google_containers/kube-controller-manager-arm:abaecec5dff5155b712cb6ab7a3cc47b
Untagged: gcr.io/google_containers/kube-controller-manager-arm:abaecec5dff5155b712cb6ab7a3cc47b
Deleted: 661cef8379bd95693ceb962d8592f35bce4ae80056b398139cf3323bfc29b74e
+++ [0207 21:07:46] Deleting docker image gcr.io/google_containers/kube-apiserver-arm:7dea5aa188e3e6ce8d92edd927bc86f7
Untagged: gcr.io/google_containers/kube-apiserver-arm:7dea5aa188e3e6ce8d92edd927bc86f7
Deleted: d3df4a3bd70cf1280090a5b3a61ec7500cd98c07be3f4bf411f2355fa929f07d
+++ [0207 21:07:46] Docker builds done
+++ [0207 21:08:05] Building tarball: test
+++ [0207 21:08:05] Building tarball: full
```
This also affects `e2e` logs and is quite annoying.
@mikedanese @ixdy @zmerlynn

### PR DESCRIPTION
**Pull request by luxas**
Fixes #20791 
@ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
Thanks! Though can you update `hack/jenkins/gotest-dockerized.sh` with the same fix, so our unit tests also get a correct time zone shown?

**Comment by ixdy** [comment]
(if you don't want to do that, I guess we can always do it in a separate PR. but seems easy enough to do here?)

**Comment by luxas** [comment]
@ixdy Fixed. Can't test it though, but I think it should be pretty safe.

**Comment by ixdy** [comment]
Thanks, LGTM! The Jenkins unit/integration build should confirm if this works or not.

**Comment by ixdy** [comment]
@k8s-bot e2e test this, flake #18963

**Comment by ixdy** [comment]
@k8s-bot test this, issue #IGNORE

(realized I hadn't set the timezone on most of our Jenkins VMs, so it was hard to tell if this change actually helped.)

**Pull request merged**
