### PR TITLE
Automated cherry pick of #110255: Endpoints and EndpointSlices should not publish IPs for terminal pods

### PR DESCRIPTION
**Pull request by robscott**
Cherry pick of #110255 on release-1.23.

#110255: add pod util to verify pod is terminal

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by robscott** [comment]
cc @kubernetes/release-managers

**Pull request merged**
