### PR TITLE
Rename controlplane.Master struct to Instance

### PR DESCRIPTION
**Pull request by spiffxp**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Picking up https://github.com/kubernetes/kubernetes/pull/94734 to fix compile error

**Which issue(s) this PR fixes**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Please use the name "Instance"

I started this already https://github.com/kubernetes/kubernetes/pull/94734

It's actually not used many places so I don't think you need an alias.

**Comment by spiffxp** [comment]
/close
works for me

**Comment by spiffxp** [comment]
/reopen
Chatted with @lavalamp offline, I'll try to push https://github.com/kubernetes/kubernetes/pull/94734 forward here instead

**Comment by spiffxp** [comment]
/retest
flakes

**Comment by spiffxp** [comment]
/retest
flake in pull-kubernetes-bazel-test
```
--- FAIL: TestDevicePluginReRegistrationProbeMode (2.04s)
    manager_test.go:222: 
        	Error Trace:	manager_test.go:222
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
```

**Comment by BenTheElder** [comment]
unit tests flaking is concerning, do we have this one tracked https://github.com/kubernetes/kubernetes/pull/95044#issuecomment-698607047 ?

**Comment by spiffxp** [comment]
ended up on this path while working https://github.com/kubernetes/kubernetes/issues/94900

**Pull request merged**
