### PR TITLE
Fix #43583 (kubenet: remove code forcing bridge MAC address)

### LINKED ISSUE #43583: kubenet: remove code forcing bridge MAC address
A while back code (https://github.com/containernetworking/cni/pull/254) was added to CNI's 'bridge' plugin to ensure a consistent bridge MAC address based on the IP address given to the bridge.  This means we can effectively revert some of https://github.com/kubernetes/kubernetes/issues/30783 because that functionality is now handled by CNI.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
*kubenet: remove code forcing bridge MAC address*

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #43583 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

cc @dcbw @freehan

### CODE REVIEW

**Comment by freehan** [comment]
Thanks for the PR. will LGTM this once cni binary are bumped.

**Comment by dcbw** [comment]
LGTM once we bump the binaries;  @squeed has a PR to do that already for some other reasons.

But once we get @sqeed's PR we can get rid of the LinkByName() code `plugin.syncEbtablesDedupRules(link.Attrs().HardwareAddr)` and pull the bridge hardware address out of the CNI Result structure.

**Comment by xiangpengzhao** [comment]
@freehan @dcbw Thanks !

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by xiangpengzhao** [comment]
@dcbw any updates on bumping the binaries?

**Comment by freehan** [comment]
https://github.com/kubernetes/kubernetes/pull/51250 is merged

/retest
/lgtm
/apprve

**Pull request merged**
