### PR TITLE
Update wordpress to 4.8.1

### PR DESCRIPTION
**Pull request by ghost**
Security minor release update

### CODE REVIEW

**Comment by netroby** [comment]
ping @wojtek-t @piosz @jeffvance @jeffmendoza

**Comment by jeffmendoza** [comment]
Please use https://github.com/kubernetes/examples

**Comment by jeffmendoza** [comment]
@ahmetb @sebgoa Will these examples be removed from the main repo?

**Comment by piosz** [comment]
@netroby please sign CLA

**Comment by ahmetb** [comment]
@netroby Please submit a pull request to https://github.com/kubernetes/examples instead. 
@jeffmendoza We will remove them at some point. We're maintaining a grace period to not to break anything, such as the e2e tests.

**Comment by jeffmendoza** [comment]
@ahmetb FYI, when I removed all the docs, I moved the configs that were used by tests to here: https://github.com/kubernetes/kubernetes/tree/master/test/fixtures/doc-yaml

**Comment by cblecker** [comment]
Per above, we're not updating these examples in k/k anymore. Please submit PR to https://github.com/kubernetes/examples instead.
/close

**Pull request closed without merging**
