### PR TITLE
fieldmanagertest: Reduce API surface of the test package

### PR DESCRIPTION
**Pull request by apelisse**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:
Simplify the test package interface.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by alexzielenski — APPROVED** [review]
/lgtm

other than the name of the function & package, it seems nothing has changed when moving testfieldmanager.go to the new location

**Comment by apelisse** [comment]
> other than the name of the function & package, it seems nothing has changed when moving testfieldmanager.go to the new location

Correct, I'm sad git isn't smarter in showing the diff here.

**Comment by apelisse** [comment]
It's actually making the TestFieldManager into an interface, and the old TestFieldManager as an impl that is only accessible through the internal/testing. So that's slightly different, but no behavior change, that's just moving/renaming fundamentally.

**Pull request merged**
