### PR TITLE
Update api/swagger-spec files for the branch.

### PR DESCRIPTION
**Pull request by david-mcmahon**
This is a new requirement this branch.

A companion change will also be required to https://github.com/kubernetes/release/blob/master/anago

### CODE REVIEW

**Comment by lavalamp** [comment]
I think this is wrong, it should be a branch name, not a tag name.

**Comment by david-mcmahon** [comment]
This is new from last time we branched.
This is from running straight hack/update-swagger-spec.sh.  If we need to change what it is inserting, that's another thing to investigate.

**Comment by lavalamp** [comment]
@nikhiljindal can confirm

**Comment by caesarxuchao** [comment]
We should have a munger or a script doing this change automatically, the links in release 1.1 swagger-spec is versioned, see https://github.com/kubernetes/kubernetes/blob/release-1.1/api/swagger-spec/v1.json

**Comment by caesarxuchao** [comment]
These should be automatically updated by running build/versionize-docs.sh:
https://github.com/kubernetes/kubernetes/blob/master/build/versionize-docs.sh#L88-L102

**Comment by david-mcmahon** [comment]
@caesarxuchao But there's nothing there that's touching api/swagger-spec.  Something should have been added in https://github.com/kubernetes/kubernetes/pull/19577 to satisfy the versionize-docs.sh requirement, but sadly that is something that is not regularly tested as part of the submit process - as it's a release-only activity - for now.

**Comment by caesarxuchao** [comment]
Re: I think this is wrong, it should be a branch name, not a tag name.

Agree. That's what we did for [1.2 release](https://github.com/kubernetes/kubernetes/blob/release-1.1/api/swagger-spec/v1.json#L11083). Also, if we are creating releasing branch using the script, it will replace HEAD with branch name as well, see [here](https://github.com/kubernetes/kubernetes/blob/master/build/versionize-docs.sh#L34)

**Comment by david-mcmahon** [comment]
@lavalamp @caesarxuchao sure it's wrong, but it's what happens when you run hack/update-swagger-spec.sh (which is what hack/verify-swagger-spec.sh tells you to run).
What has to happen is (probably):
* Run update-swagger-spec.sh from versionize-docs.sh and figure out why it is using tag vs branch.

**Comment by caesarxuchao** [comment]
Re: But there's nothing there that's touching api/swagger-spec

https://github.com/kubernetes/kubernetes/blob/master/build/versionize-docs.sh#L101

**Comment by caesarxuchao** [comment]
Re: But there's nothing there that's touching api/swagger-spec

You are right, the line I pasted is updating the api docs, not the swagger spec. I guess the update-swagger-spec.sh was called in chain elsewhere but that behavior got changed.

**Comment by david-mcmahon** [comment]
PTAL

**Comment by caesarxuchao** [comment]
I think you also have to run  ./hack/update-api-reference-docs.sh manually in the 1.3 branch

**Comment by david-mcmahon** [comment]
Thanks for checking on that.  PTAL with a new commit.

**Comment by nikhiljindal** [comment]
versionize-docs used to update types.go files and then run all the update doc scripts.
Descriptions in swagger spec are picked up from types.go comments.
Ref: https://github.com/kubernetes/kubernetes/blob/master/build/versionize-docs.sh#L88-L102

So you need to update types.go files as well. The comments there should say release-1.3 instead of HEAD.

**Comment by caesarxuchao** [comment]
@nikhiljindal types.go are updated when we cut the release on Friday. It's just swagger spec and whatever that based on swagger spec needs to be updated.

LGTM. Thanks.

**Comment by nikhiljindal** [comment]
thanks @caesarxuchao!
LGTM

**Comment by david-mcmahon** [comment]
@k8s-oncall please merge this ASAP for beta release today.

**Comment by lavalamp** [comment]
lgtm

**Comment by lavalamp** [comment]
@david-mcmahon tests are red?

**Comment by david-mcmahon** [comment]
Tests are red because this PR is outstanding. :)

**Comment by lavalamp** [comment]
No, the tests are red *on this PR*?

**Comment by david-mcmahon** [comment]
#27560 too is causing trouble.  both need to be merged to get the branch sane.

**Comment by lavalamp** [comment]
Yeah, the verify script is not happy about your changes. https://00e9e64bac42b0d8d72c3981c02e06a3d1bc40fb5bd8f160a0-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F27499%2Fkubernetes-pull-test-unit-integration%2F30842%2Fbuild-log.txt?qk=AD5uMEvsvA7y4EHPaR51ehZBRZ_uJSi9b1pqUMH3y6dhAvM3oKeYSwClo7H69Ix1IOuHgwsnUlXztLFvg8xeQV6Ma0yche2u22lvVjCnfC-Q0XHTVs6UJGO7F18XjmZ22Pwfr7rywNo7ejO1YKR3h_GaHnPxKGSwgghvZ2SyH0ocFRzc9oJO7dgyu-W6AOO5Hgs9xT6GPN1PdT7fi3CxYou5GI0GqNcqXJold4ybzWleuVDmR1LWl4mctA9YrOVqq-06jZAQJUVSmHxED7cYqLGZKjwBll2RY8xY1dEfpEchJsaPJk4cVXWPckHTv7EgRsndMm_5aG0BKlgRDsNrrAqgpMxmSzMoFydowua8IXYkQZi9fSg2iUOblghmxSuFm1tEs_ggby25Kcqwm5IwHgkMueCqrAD14iCwLbFUG87855FRJSIOFDboAX_C2uLFUJUBh-GNkcAEU8LXxn6CJFnQe8V0j1nQJRbynNq30EOPxqO6CZPR7d-Y-in8wCRE19jz9Z9zOqotcNMkqv1fFPvBTeU1T1l5T5EkSsG71RcGnFJLqjgt256o7zhBfmnaCfaI-DtaR90OTqNFrF2_QIuep2Tjdmysm8Vbcr8Nel4qSLgbwaMr6jiJh2YDNatdeIfmcNcxy_X3yMG9kmFDNxEUNrLRgo2uCWu_NCMh8gCNwes6tfDvgSOf0eQuoqCvkvqGp6qV8RMeCgYJvisTAuMZQGT4qxgyMdUe76_Om4x51MqfKkyYJ3OC1Vs_6s-tHUmPLjKZWUPQf9RBUMyiaKaA4f4FUI5L0sVPYDNf75NZYN2GIU7svS9Pg2EhXb7ish0Q9tCL3kaqr9B0WTocg_3GqJEYeYNhvlNpj-yXWSnwr2M4FJpc7sHJzuG8P1husPzBtC7wreEo6vWSnBW0X71KH8WyGPDAhAg2mAb4JQGni2HuRPyszwg

**Comment by david-mcmahon** [comment]
Now that we've sorted out all the issues, I could just move 27560 into here.

**Comment by lavalamp** [comment]
I'll merge as soon as the tests finish.

**Comment by lavalamp** [comment]
OK, unit tests passed. Good enough for me.

**Pull request merged**
