### PR TITLE
fix typos:information

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

fix typos:information

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot verify test this

**Comment by zhangxiaoyu-zidif** [comment]
@NickrenREN could you send '/ok to test', that I could restest it.

**Comment by NickrenREN** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
You have several typo pulls:

 1. https://github.com/kubernetes/kubernetes/pull/43904
 1. https://github.com/kubernetes/kubernetes/pull/44708
 1. https://github.com/kubernetes/kubernetes/pull/45327
 1. https://github.com/kubernetes/kubernetes/pull/45395
 1. https://github.com/kubernetes/kubernetes/pull/45592

Can you please combine them into a single pull?

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k 
#43904 : I can't solve the test failed. I don't know why.
#44708: I miss cla label. But I signed it.
#45327 : This only one can be gathered.
#45395:  I can't solve the test failed. I don't know why.
#45592: The latest one I pull request.
In fact, that's all.

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k 
#43904 : I can't solve the test failed. I don't know why.
#44708: I miss cla label. But I signed it.
#45327 : This only one can be gathered.
#45395:  I can't solve the test failed. I don't know why.
#45592: The latest one I pull request.
In fact, that's all.

**Comment by deads2k** [comment]
from the log: 

```
I0505 00:52:26.075]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0505 00:52:26.075] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	98s
```

**Comment by deads2k** [comment]
```
I0505 02:43:13.742] pkg/apis is out of date. Please run hack/update-generated-protobuf.sh
I0505 02:43:13.779] FAILED   hack/make-rules/../../hack/verify-generated-protobuf.sh	85s
```

**Comment by zhangxiaoyu-zidif** [comment]
I can't solve the test failed. So I closed it.

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k  Thanks, I did that before, but still failed. I really  don't know why. So I start to hesitate my computer.... and env ...

**Pull request closed without merging**
