### PR TITLE
move registry packages for all API groups

### PR DESCRIPTION
**Pull request by deads2k**
This continues the pattern of `registry/<group>/resource` for our backing storage.  This entire pull is nothing but moves.  I'll reswizzle the actual storage next, but these are cargo-culted everywhere, so I want to lay this down early.

@sttts @ncdc

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33169)

### CODE REVIEW

**Comment by sttts** [comment]
Went through the commits: only renames and corresponding fixes for the imports. lgtm from my side.

**Comment by ncdc** [comment]
lgtm here as well

**Comment by deads2k** [comment]
Sets a new pattern for creating a new API type or group, bumping priority to prevent cargo-culters from grabbing the wrong pattern to copy.

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this issue #31706

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this issue #33175

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this issue #33175

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this issue #33175

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this issue #33175

**Pull request merged**
