### PR TITLE
Remove scheduledjobs

### PR DESCRIPTION
**Pull request by soltysh**
This is a prerequisite for promoting CronJobs to beta.

**Release note**:
```release-note
Remove deprecated ScheduledJobs endpoints, use CronJobs instead.
```

### CODE REVIEW

**Comment by deads2k** [comment]
Alpha resources can be dropped at any time and as I recall, cronjob (the transition) existed last release.

/lgtm

**Comment by smarterclayton** [comment]
/approve

Fits the requirements for one release alpha removal and a beta or higher replacement exists.

**Comment by soltysh** [comment]
The PR was lgtmed and approved, for some reason the bot didn't picked up the approval. I'll apply the labels manually.

**Comment by pwittrock** [comment]
This broke the [kubectl skew tests](https://k8s-testgrid.appspot.com/master-kubectl-skew#skew-cluster1.7-kubectl1.8-gce&width=20).  Please create a patch to the 1.7 branch to disable the test when running against a 1.8+ cluster.

**Comment by pwittrock** [comment]
@soltysh @smarterclayton @deads2k

**Pull request merged**
