### PR TITLE
Migrate sig-ui e2e test

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:
Migrate sig-ui e2e tests

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Ref Umbrella issue #49161

**Special notes for your reviewer**:

**Release note**:

none

### CODE REVIEW

**Comment by guangxuli** [comment]
gently ping @sttts

**Comment by guangxuli** [comment]
ping @fabianofranz

**Comment by guangxuli** [comment]
ping @sttts

**Comment by guangxuli** [comment]
@kubernetes/sig-ui-pr-reviewes

**Comment by guangxuli** [comment]
ping @sttts

**Review by janetkuo — APPROVED** [review]

**Comment by guangxuli** [comment]
thanks @janetkuo 
gently ping @sttts

**Comment by guangxuli** [comment]
ping @sttts

**Comment by guangxuli** [comment]
ping @sttts

**Comment by guangxuli** [comment]
gentle ping @fejta Could you help approve this? Thanks.

**Comment by fejta** [comment]
/lgtm
/approve

Please consider adding an OWNERS file to test/e2e/ui

**Comment by guangxuli** [comment]
@fejta thanks so much.

**Pull request merged**
