### PR TITLE
Bump fsouza/go-dockerclient godep

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This PR bumps the fsouza/go-dockerclient so we can take advantage of newer features in Docker.

I am looking to prototype some behavior with `docker --cpu-quota run` in a follow-on.

cc @dchen1107

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM and thanks for picking up this.

**Comment by brendandburns** [comment]
Shippable looks like a flake, hitting it again.

**Comment by dchen1107** [comment]
@derekwaynecarr Could you please rebase  your pr to get this merged? Thanks!

**Comment by dchen1107** [comment]
@derekwaynecarr a separate PR #12286 is also upgrading fsouza/go-dockerclient to the same revision. Maybe we can close this one?

**Comment by derekwaynecarr** [comment]
@dchen1107 - I rebased, take which ever PR you want.

**Pull request merged**
