### PR TITLE
Update generated copyrights for 2018

### LINKED ISSUE #57728: Code generator wants to replace 2017 with 2018 in all generated license statements
Happy New Year! Now when I run make I get a diff like this in every zz_generated file:
```
diff --git a/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
index 5cebdd5d5b..0d7f685c3b 100644
--- a/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
+++ b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
@@ -1,7 +1,7 @@
 // +build !ignore_autogenerated
 
 /*
-Copyright 2017 The Kubernetes Authors.
+Copyright 2018 The Kubernetes Authors.
```

Not sure what a smart solution is, but we could merge something like #57729 in the meantime.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
- Update boilerplate regex to support 2018
- Add generated runtime and generated device plugin scripts to `hack/update-all.sh` target list
- Run `make update` to regenerate all generated code

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57728

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
+100 THANKS!

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/priority critical-urgent
@wojtek-t I don’t know if you’re online for CET today, but if so, would you mind reviewing?

**Comment by wojtek-t** [comment]
/approve no-issue

Thanks!

**Comment by mbohlool** [comment]
cc @jpbetz

**Comment by mbohlool** [comment]
trying to cp this into 1.9 but a test is failing: https://github.com/kubernetes/kubernetes/pull/57767

Do you guys have any idea why?

**Comment by cblecker** [comment]
1.9: #57767
1.8: #57771
Will work on the cherry-pick for 1.7 later

**Comment by nikhita** [comment]
This PR has the best branch name ever :)

**Comment by m1093782566** [comment]
:+1:

**Comment by nikhita** [comment]
For 1.7: https://github.com/kubernetes/kubernetes/pull/57796

**Pull request merged**
