### PR TITLE
Automated cherry pick of #66157: Bump version of event-exporter.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #66157 on release-1.10.

#66157: Bump version of event-exporter.

### CODE REVIEW

**Comment by x13n** [comment]
I'm not in OWNERS file on 1.10 branch, you need to have these approved by @piosz

**Comment by nikhita** [comment]
Closing and reopening to retrigger prow to remove the `do-not-merge/cherry-pick-not-approved` label.

/assign

**Comment by nikhita** [comment]
/unassign

The labels are fixed now. :+1:

**Comment by nikhita** [comment]
/assign @piosz 
for approval

**Comment by MaciekPytel** [comment]
@loburm @piosz This has been hanging for a month now. Do we still need this? If so can you review? Otherwise let's close it.

**Comment by loburm** [comment]
Let's close it in favor of other (I'll create cherrypick soon)

**Pull request closed without merging**
