### PR TITLE
Running hack/update-all.sh on master

### PR DESCRIPTION
**Pull request by nikhiljindal**
Running `hack/update-all.sh` on master

[Analytics]()

cc @k8s-oncall

### CODE REVIEW

**Comment by nikhiljindal** [comment]
I am not sure why is this PR required.
We call verify-all.sh in our tests, so ideally this should not be required.

**Comment by luxas** [comment]
@nikhiljindal I guess you saw this: https://github.com/kubernetes/kubernetes/pull/23684#issuecomment-216654698

**Comment by nikhiljindal** [comment]
@luxas I hadnt. Just like you, I had my own PR where I was seeing these spurious updates unrelated to my PR :)

**Comment by mml** [comment]
The "fix" breaks verify-codecgen.

```
FAILED   ./hack/../hack/verify-codecgen.sh	123s
```

**Comment by nikhiljindal** [comment]
Looks like update-codecgen and verify-codecgen are out of sync.

On HEAD currently, verify-codecgen is passing, but it fails if run after update-codecgen.

verify-codecgen should just be calling update-codecgen rather than duplicating logic.
That is how other verify-* scripts work.
cc @wojtek-t

**Comment by nikhiljindal** [comment]
Thanks @mml for filing https://github.com/kubernetes/kubernetes/issues/25103 for codecgen issue.

Apart from the codecgen files, CHANGELOG.md file got updated as well.

I see @ihmccreery touched it last.
@ihmccreery Does the auto generated change look good to you?

**Comment by lavalamp** [comment]
I'm testing a fix for #25103 right now.

**Comment by ihmccreery** [comment]
Er, that TOC looks weird.  Why are there two 1.3.0-alpha.3 sections?

**Comment by luxas** [comment]
Is this necessary anymore as #25108 is in?

@ihmccreery I guess the TOC problem is somewhere in `hack/update-generated-docs`.
Can you take a look at it please? Because now, many PRs includes this change often without even noticing it.

**Comment by ihmccreery** [comment]
The CHANGELOG issue was my fault; I copy-pasted things wrong in https://github.com/kubernetes/kubernetes/pull/24942; fixed in #25203.

**Comment by nikhiljindal** [comment]
Great, thanks @ihmccreery and @lavalamp for the fixes!
Closing this one

**Pull request closed without merging**
