### PR TITLE
Fix cleanup of file subpaths

### LINKED ISSUE #105536: Orphaned pod found, but error not a directory occurred when trying to remove the volumes dir
#### What happened:

One of our nodes had a hard reboot. After this, the following message was occurring in the kubelet logs every 2 seconds:

```
Oct 07 12:46:32 k8s-master2-staging kubelet[7310]: E1007 12:46:32.359145    7310 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"1d4bfc07-3469-4eaa-992f-6d23c17f3aee\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=1
```

Indeed, the orphaned pod directory exists and contains 1 stale volume directory with a file in it (probably explaining the "not a directory" error):

```
sjors@k8s-master2-staging:~$ sudo ls -la /var/lib/kubelet/pods/1d4bfc07-3469-4eaa-992f-6d23c17f3aee/volumes/kubernetes.io~csi/pvc-13c81b28-4038-40d5-b6e8-4194e1d7be0e
total 12
drwxr-x--- 2 root root 4096 Oct  7 12:37 .
drwxr-x--- 3 root root 4096 Oct  2 19:37 ..
-rw-r--r-- 1 root root  270 Oct  7 12:37 vol_data.json
```

Deleting this file manually leads to immediate resolving of the Kubelet error 2 seconds later:

```
Oct 07 12:46:40 k8s-master2-staging kubelet[7310]: I1007 12:46:40.359957    7310 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=1d4bfc07-3469-4eaa-992f-6d23c17f3aee path="/var/lib/kubelet/pods/1d4bfc07-3469-4eaa-992f-6d23c17f3aee/volumes"
```

#### What you expected to happen:

I know that the Kubelet tries to clean up orphaned pod directories, and various issues have been fixed regarding this in the past, such as figuring out stale mounts and deleting old directories (#60987 for example).

However, it looks like when there are files present, it fails to remove the stale directory.

#### How to reproduce it (as minimally and precisely as possible):

I think, but have not attempted, it can be reproduced by these steps:

1. start a Pod with a mounted PVC
2. manually create a file inside a Pod's `volumes/kubernetes.io~csi/pvc-...` directory
3. hard-reboot the machine, so that the kubelet gets no chance to clean up the Pod directory, i.e. directory becomes orphaned
4. (If creating the file of step 2 was not possible before, it can also be done after the reboot, but before the kubelet comes up.)
5. observe error in the Kubelet logs.

#### Anything else we need to know?:

The CSI provider used is Hetzner Cloud (hcloud-csi-driver:1.6.0), I'm not sure if it's responsible for creating the file.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.22.1
- Cloud provider or hardware configuration: bare-metal, 3 masters
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.3 LTS
- Kernel (e.g. `uname -a`): 5.4.0-88-generic
- Install tools: kubeadm 1.22.1

### LINKED ISSUE #106942: kubelet delete orphaned pod volumes failed
### What happened?

when kubelet cleanupOrphanedPodDirs，it may fail when the path is a file ，the log is

````
Dec 10 16:36:18 node1 kubelet: E1210 16:36:18.360278   14390 kubelet_volumes.go:179] orphaned pod "306a14d5-2c8f-44d8-bc13-857539fab97d" found, but failed to rmdir() subpath at path /var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0/1: not a directory : There were a total of 1 errors similar to this. Turn up verbosity to see them.
Dec 10 16:36:18 node1 systemd-logind: Removed session 10112.
Dec 10 16:36:18 node1 systemd-logind: New session 10113 of user root.
Dec 10 16:36:18 node1 systemd: Started Session 10113 of user root.
Dec 10 16:36:19 node1 systemd-logind: Removed session 10113.
Dec 10 16:36:19 node1 systemd-logind: New session 10114 of user root.
Dec 10 16:36:19 node1 systemd: Started Session 10114 of user root.
Dec 10 16:36:19 node1 systemd-logind: Removed session 10114.
Dec 10 16:36:20 node1 systemd-logind: New session 10115 of user root.
Dec 10 16:36:20 node1 systemd: Started Session 10115 of user root.
Dec 10 16:36:20 node1 systemd-logind: Removed session 10115.
Dec 10 16:36:20 node1 kubelet: E1210 16:36:20.396360   14390 kubelet_volumes.go:179] orphaned pod "306a14d5-2c8f-44d8-bc13-857539fab97d" found, but failed to rmdir() subpath at path /var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0/1: not a directory : There were a total of 1 errors similar to this. Turn up verbosity to see them.
Dec 10 16:36:20 node1 systemd-logind: New session 10117 of user root.
Dec 10 16:36:20 node1 systemd: Started Session 10117 of user root.
Dec 10 16:36:20 node1 systemd-logind: New session 10116 of user root.
Dec 10 16:36:20 node1 systemd: Started Session 10116 of user root.
Dec 10 16:36:20 node1 systemd-logind: Removed session 10116.
Dec 10 16:36:20 node1 systemd-logind: Removed session 10117.
Dec 10 16:36:20 node1 systemd-logind: New session 10118 of user root.
Dec 10 16:36:20 node1 systemd: Started Session 10118 of user root.
Dec 10 16:36:20 node1 systemd-logind: Removed session 10118.
Dec 10 16:36:21 node1 systemd-logind: New session 10119 of user root.
Dec 10 16:36:21 node1 systemd: Started Session 10119 of user root.
Dec 10 16:36:21 node1 systemd-logind: Removed session 10119.
Dec 10 16:36:22 node1 kubelet: E1210 16:36:22.345810   14390 kubelet_volumes.go:179] orphaned pod "306a14d5-2c8f-44d8-bc13-857539fab97d" found, but failed to rmdir() subpath at path /var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0/1: not a directory : There were a total of 1 errors similar to this. Turn up verbosity to see them.

`````

when can see ,this path is a file ,not a directory
````
[root@node1 est73vf8503ba-0]# pwd
/var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0
[root@node1 est73vf8503ba-0]# cat /var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0/1 1
[root@node1 est73vf8503ba-0]# cat /var/lib/data/kubelet/pods/306a14d5-2c8f-44d8-bc13-857539fab97d/volume-subpaths/cudald/est73vf8503ba-0/1
[root@node1 est73vf8503ba-0]#
[root@node1 est73vf8503ba-0]#
[root@node1 est73vf8503ba-0]#
````

### What did you expect to happen?

kubelet can delete the file and path  when deleting orphaned pod

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes 1.20.2+docker+nvidia-docker，and the pod has GPU allocated

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.20.5
</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
centos7.6
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Allow kubelet orphan cleanup to delete both files and empty directories used as subpath mount points.

A pod does not need to use a directory as a subpath, it can use a file (unix domain socket, pipe, ...) too. Therefore the cleanup should use `os.Remove` that deletes both files and empty directories.

This contrasts with whole volumes - a volume is always a directory.

#### Which issue(s) this PR fixes:

Fixes: #106942

#### Does this PR introduce a user-facing change?

```release-note
Fixed cleanup of Pod volume mounts when a file was used as a subpath.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
/priority important-soon

cc @gnufied @jingxu97 @msau42

**Comment by gnufied** [comment]
cc @dobsonj

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
