### PR TITLE
staging unit test replace ioutil readfile to os.readfile

### PR DESCRIPTION
**Pull request by j0rGeT**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will replace ioutil.ReadFile by os.ReadFile

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by miladhzzzz** [comment]
adding comment so i can be assigned :)

**Review by miladhzzzz — APPROVED** [review]
everything seems ok,
this PR only touches test files.

**Comment by vaibhav2107** [comment]
@j0rGeT  Could you please sign the CLA in order to approve/merge PR
You can see more about CLA here https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by nilekhc** [comment]
Thanks for your pull request.  However, [trivial](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) changes like this should be avoided as we have very limited resources to handle reviews and approvals.  Focus efforts on fixes that have meaningful impact on end users (bugs, docs, etc).

/close

**Pull request closed without merging**
