### PR TITLE
fix a typo in test/e2e/apimachinery/resource_quota.go

### PR DESCRIPTION
**Pull request by haoruan**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix a typo in test/e2e/apimachinery/resource_quota.go
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by haoruan** [comment]
Sorry, forgot to update conformance yaml, now should pass the verification. @deads2k @cici37

**Comment by cici37** [comment]
/lgtm
@conformance-behavior-approvers
for approval

**Comment by dims** [comment]
/approve
/lgtm

thanks for fixing!

**Pull request merged**
