### PR TITLE
Automated cherry pick of #27509

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #27509 on release-1.2.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
cc @roberthbailey

**Comment by jlowdermilk** [comment]
PR builder is failing on
```

• Failure [63.083 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1200
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:526
    should support exec through an HTTP proxy [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:456

    Jun 24 15:20:53.540: Can't build static kubectl due to missing hack/build-go.sh. Error=stat /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/kubernetes/hack/build-go.sh: no such file or directory

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:256
```

I'm not sure how this works for head, but this cherrypick doesn't affect that test, and it's passing on the continuous build. cc @spxtr

**Comment by eparis** [comment]
@roberthbailey The bot is really angry on 1.2 these days. Adding LGTM is going to make it comment like wild.  You are going to have to 1.2 by hand.

**Comment by roberthbailey** [comment]
I'll revert if our post-submit 1.2 tests start failing.

**Comment by roberthbailey** [comment]
wow, it took the label off of the cherry pick PR instead of the original PR.

**Pull request merged**
