### PR TITLE
cleanup: remove unused code of Resource() and Kind() in kubeadm

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
In #115088, kubeadm related are not cleanup yet.

#### Which issue(s) this PR fixes:
xref #115088

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Fb9027 — APPROVED** [review]

**Review by Fb9027 — APPROVED** [review]

**Review by Fb9027 — APPROVED** [review]
Disconnect still in my email on my Facebook in my Instagram locking me out

**Comment by SataQiu** [comment]
@pacoxu 
I'm not sure, but I have a feeling that we shouldn't change beta API, especially deleting something. 
Maybe clean up the unused code in a new API version (`v1beta4`)?
We can create an issue for `v1beta4`.

**Comment by pacoxu** [comment]
> I'm not sure, but I have a feeling that we shouldn't change the beta API, especially deleting something.

Not sure if there are consumers of these two functions.
/close
this maybe not be a good cleanup. A similar PR is hold for https://github.com/kubernetes/kubernetes/pull/115095/files#r1072811617.


> Maybe clean up the unused code in a new API version (`v1beta4`)?
> We can create an issue for `v1beta4`.

Yes. Probably, we should avoid adding these for v1beta4 later.

**Pull request closed without merging**
