### PR TITLE
also consider init container when get ImageLocality HostPriority

### PR DESCRIPTION
**Pull request by ChenLingPeng**
Signed-off-by: forrestchen <forrestchen@tencent.com>

**What this PR does / why we need it**:

Now in ImageLocalityPriority, we only consider Spec.Containers, we should also consider InitContainers since PodFitsResources also consider InitContainer.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by ChenLingPeng** [comment]
Have no idea why this test failed. @k82cn could you PTAL?

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Review by k82cn — COMMENTED** [review]
Please add cases that shown initContainer's contribution.

**Comment by k82cn** [comment]
> Have no idea why this test failed. @k82cn could you PTAL?

Not sure, but it seems not related to this PR.

**Comment by ChenLingPeng** [comment]
a test case added.

**Comment by timothysc** [comment]
So I'm debating whether the extra weight makes sense or whether to add a weight or not.  

e.g. - Are we giving too much weight to the point where we make locally optimal/globally sub-optimal decisions...

**Comment by ChenLingPeng** [comment]
@timothysc thanks for the comment.
The first thought is that a pod with `Spec.InitContainers` should prefer bind to node with the image init container need, just like what `Spec.Containers` does. 
When consider about image locality, I think the images in `Spec.InitContainers` has the equal influence with images in `Spec.Containers`, right?

> Are we giving too much weight to the point where we make locally optimal/globally sub-optimal decisions...

Not think too much about global decisions though it will truly affect the scheduler decision if this applied. But I think we should adjust the algo weight instead.

**Comment by timothysc** [comment]
So I'm going to close this one.  I think adding extra-weighting towards init containers will lead towards sub-optimal steering in the long haul.  

If you can describe a use case otherwise please feel free to reopen.

**Pull request closed without merging**
