### PR TITLE
fix: remove the redundant count variable

### PR DESCRIPTION
**Pull request by qmloong**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
clean up the worthless count variable

#### Which issue(s) this PR fixes:

Fixes #
None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by XudongLiuHarold — APPROVED** [review]
/lgtm

**Comment by qmloong** [comment]
Friendly ping. @aojea @MrHohn @freehan

**Comment by aojea** [comment]
/lgtm
/approve

It seems that it was always this way :shrug:  https://github.com/kubernetes/kubernetes/commit/724b142f076d3382372e014f2797dc72cf42e351

I'm going to hold it so @robscott can take a look, maybe he remembers something about it ... we can unhold it in a few days if there is no answer
/hold

**Pull request merged**
