### PR TITLE
refactor `GetOldRCs()` 

### PR DESCRIPTION
**Pull request by mqliang**
move `GetNewRCTemplate(deployment)` out of for loop

### CODE REVIEW

**Comment by ashcrow** [comment]
This looks much simpler now. Was the ```newRCTemplate``` variable added for readability or do you have a plan to use it again later?

**Comment by mqliang** [comment]
@ashcrow Existing code put `GetNewRCTemplate(deployment)` in the for loop, so it will be invocate several times, so I move it out of loop and bind to ` newRCTemplate` variable. Such a refactor could also keep consistance whith function `GetNewRC`: https://github.com/mqliang/kubernetes/blob/deployment-redundant/pkg/util/deployment/deployment.go#L71-L74

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by ashcrow** [comment]
The error *seems* related ...

```
[Fail] Deployment [It] deployment should delete old pods and create new ones 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:173
```

as [pkg/controller/deployment/deployment_controller.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L91) does call ```getOldRCs``` which forwards to the changed function in this PR.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
The same test failed for the second time:
"Deployment deployment should delete old pods and create new ones"

I'm pretty sure this is not a coincidence.

@mqliang Can you please take a look?

**Comment by mqliang** [comment]
@wojtek-t The test failure seems to be caused by this statement `api.Semantic.DeepEqual(rc.Spec.Template, newRCTemplate)`, which should be `api.Semantic.DeepEqual(rc.Spec.Template, &newRCTemplate)`, and it has been fixed by someone else. I rebased my PR and repushed,  hoping all tests successful.

**Comment by ashcrow** [comment]
Looks to be the same error still...

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:42
  deployment should delete old pods and create new ones [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:38
```

**Comment by bprashanth** [comment]
Please change the title of the pr to better reflect what you're doing/why, since it's going to show up in git and it doesn't look like you're doing anythign to GetOldRCs()

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by wojtek-t** [comment]
ok to test

**Pull request merged**
