### PR TITLE
Upstream Kubernetes Mesos controller manager and km binary (copy)

### PR DESCRIPTION
**Pull request by karlkfi**
Copy of #9265 to make the CLA bot happy.

Closes #9265

### CODE REVIEW

**Comment by davidopp** [comment]
@karlkfi isn't listed as a CLA signer either. (I'm not just saying this because of the bot output, but also I checked the internal system that is driven by the same database, and it said the same thing.)

**Comment by karlkfi** [comment]
I have not personally signed the CLA. However, I AM on the mesosphere engineering mailing list. Is the bot only checking my primary github email? I have added my mesosphere email to github, but it is not set as the primary email.

**Comment by karlkfi** [comment]
I have added my mesosphere email as my github public email address (for now). Does that help?

**Comment by karlkfi** [comment]
I signed it!

**Comment by karlkfi** [comment]
On the signing page is says:

```
You are covered by the following corporate agreements:

Agreement	Name	Date Signed
Google Corporate CLA	Mesosphere, Inc.	Jun 02, 2015 11:06 PDT
```

**Comment by davidopp** [comment]
This didn't fix the CLA issue, so I'm closing.

**Pull request closed without merging**
