### PR TITLE
bump gengo to latest

### PR DESCRIPTION
**Pull request by deads2k**
bumping gengo to limit surprises while working on https://github.com/kubernetes/kubernetes/pull/39475

@kubernetes/sig-api-machinery-misc

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot test this

**Comment by deads2k** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
Ah, yes, this update changed a test-related API.  I can send you a PR

**Comment by thockin** [comment]
The fix is easy: change AddFile() to AddFileForTest() in cmd/libs/go2idl/openapi-gen/generators/openapi_test.go

**Pull request merged**
