### PR TITLE
Automated cherry pick of #59519: Report InstanceID for vSphere Cloud Provider as UUID obtained from product_serial file

### PR DESCRIPTION
**Pull request by abrarshivani**
Cherry pick of #59519 on release-1.9.

#59519: Report InstanceID for vSphere Cloud Provider as UUID obtained from product_serial file

### CODE REVIEW

**Comment by divyenpatel** [comment]
@stttts @jsafrane Can you please help removing label ` do-not-merge/cherry-pick-not-approved ` from this PR? 

We nee to cherry pick this PR to 1.9 branch. This PR is fixing the bug reported by customer - https://github.com/kubernetes/kubernetes/issues/58927

**Comment by sttts** [comment]
@mbohlool is the 1.9 release manager. He has to approve this.

**Comment by mbohlool** [comment]
How this is tested?

**Comment by divyenpatel** [comment]
@mbohlool This is tested with running vsphere e2e test cases. E2E test cases are modified to use provider ID, as part of this PR - https://github.com/kubernetes/kubernetes/pull/59761/

**Comment by abrarshivani** [comment]
@mbohlool This is manually tested e2e on vSphere Infrastructure. 

Tested:
```
Launched K8s cluster using kubeadm (Used Ubuntu VM compatible with vSphere version 6.5.)
Note: Installed Ubuntu from ISO
Observed following:

Master
> cat /sys/class/dmi/id/product_uuid
743F0E42-84EA-A2F9-7736-6106BB5DBF6B

> cat /sys/class/dmi/id/product_serial
VMware-42 0e 3f 74 ea 84 f9 a2-77 36 61 06 bb 5d bf 6b

Node
> cat /sys/class/dmi/id/product_uuid
956E0E42-CC9D-3D89-9757-F27CEB539B76

> cat /sys/class/dmi/id/product_serial
VMware-42 0e 6e 95 9d cc 89 3d-97 57 f2 7c eb 53 9b 76

With this fix controller manager was able to find the nodes.
```

**Comment by mbohlool** [comment]
can those tests be ported in 1.9 release branch too?

**Comment by divyenpatel** [comment]
> can those tests be ported in 1.9 release branch too?

@mbohlool in previous releases we were asked to not cherry pick test changes as guideline suggests "Patch releases should not contain new features, so ensure that cherry-picks are for bug/security fixes only." - https://github.com/kubernetes/sig-release/blob/master/ephemera/README.md#patch-release-manager 


To cherry pick these tests to 1.9 branch we will have to cherry pick bunch of PRs

- https://github.com/kubernetes/kubernetes/pull/54438
- https://github.com/kubernetes/kubernetes/pull/59211
- https://github.com/kubernetes/kubernetes/pull/59761
- https://github.com/kubernetes/kubernetes/pull/59872
- https://github.com/kubernetes/kubernetes/pull/58713
- https://github.com/kubernetes/kubernetes/pull/59514
- https://github.com/kubernetes/kubernetes/pull/57258
- https://github.com/kubernetes/kubernetes/pull/56593

If test changes are allowed to be cherry picked then can we cherry pick them in separate PR?

@kubernetes/vmware

**Comment by mbohlool** [comment]
I guess I am a little nervous to have a code in 1.9 branch with no test. If you guys feel the feature does not need a test here, I can live with that. I definitely don't want a loads of e2e tests to be added for this change. If you want to add test, thought, it should be in the same PR.

(btw, how did you infer from the documentation that we do not cherry pick test changes? we do that all the time actually. Any code change comes into the branch should come with its test code).

**Comment by abrarshivani** [comment]
@mbohlool Test ```pull-kubernetes-e2e-kops-aws``` is failing continuously and seems to be an environmental issue. Would like to you know whether something needs to be done from our side?

**Pull request merged**
