### PR TITLE
Update Cluster Autoscaler version to 1.3.8

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
Update Cluster Autoscaler version to 1.3.8. Release notes: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.3.8
```

### CODE REVIEW

**Comment by losipiuk** [comment]
@foxish Could you please include that in next patch release of 1.11. It is about fixing CVEs resulting from old debian-base image used for building cluster-autoscaler.

**Comment by foxish** [comment]
Looks like this missed the 1.11.9 train unfortunately. Will target for the next one.

**Pull request merged**
