### PR TITLE
Increase the cpu reservation for the fluentd-es pod so that it can survive the scalability tests.

### PR DESCRIPTION
**Pull request by roberthbailey**
xref: https://github.com/kubernetes/kubernetes/issues/26185

### CODE REVIEW

**Comment by lavalamp** [comment]
Does this change both master and nodes?

**Comment by lavalamp** [comment]
@gmarek explains that this isn't actually the test failure, I'll let him explain here.

**Comment by roberthbailey** [comment]
AFAICT it will change both the master and nodes. I don't see any way to separate them.

**Comment by gmarek** [comment]
@wojtek-t PR will fix the test failure. The thing is that as flutentd-es actually uses more than .1 core we probably should merge this PR as well, or we're risking starving it. OTOH this is problematic PR - we can end up in the same situation that we did when we bumped kube-proxy cpu requests.

**Comment by wojtek-t** [comment]
I definitely agree we need this PR too. I'm just saying that it won't fix test failures.

But sure - it LGTM

**Comment by wojtek-t** [comment]
Actually - @roberthbailey let me step back with this one.
We used to have a problem in the past, that increasing reservations of our pods caused problems on upgrade (because the amount of space for user pods decreased).
We will face the same problem here, right?

**Comment by wojtek-t** [comment]
Discussed offline - lgtm

**Comment by gmarek** [comment]
We should have a separate manifest for master machine with the higher request. This PR in practice increasing the "tax" by 0.1 core/node - this is a big change. @davidopp @bgrant0607

**Comment by vishh** [comment]
FYI: Fluentd behavior on GCI should be no different from old Container VM because we do not set CPU limits on Fluentd pod.

**Comment by roberthbailey** [comment]
It turns out that this wasn't necessary to fix the scalability tests, so I'm going to close this PR.

**Pull request closed without merging**
