### PR TITLE
Bumped Heapster version to 1.4.3

### PR DESCRIPTION
**Pull request by loburm**
```release-note
Bumped Heapster version to 1.4.3 - more details https://github.com/kubernetes/heapster/releases/tag/v1.4.3.
```

### CODE REVIEW

**Comment by piosz** [comment]
@jpbetz to give you more context: we didn't manage to release the stable version of Heapster 1.5 before Kubernetes 1.8, so reverting to the previous stable version.

**Comment by liggitt** [comment]
> @jpbetz to give you more context: we didn't manage to release the stable version of Heapster 1.5 before Kubernetes 1.8, so reverting to the previous stable version.

how risky is this change? there's a fair number of issues pending a 1.8.1 release... is this going to extend the time we need to soak before cutting a 1.8.x release?

**Comment by jpbetz** [comment]
@piosz Would you please summarize what happens when a k8s cluster running heapster-v1.5.0-beta.0 is downgraded to heapster-v1.4.3. Has this been tested? Are there any steps cluster operators would need to take?

**Comment by piosz** [comment]
@liggitt low risk change - Heapster 1.4.3 is well tested with Kubernetes 1.7.
@jpbetz no action required. Heapster is almost stateless (it remembers the latest value of metrics) and doesn't have any API, so nothing should happen in case of downgrade, except from a short downtime window (up to 2 minutes) for horizontal pod autoscaler, which basically happens during every Heapster restart.

**Comment by piosz** [comment]
@jpbetz ping

**Comment by jpbetz** [comment]
We're about to cut release 1.8.1. We are minimizing the cherry picks we accept to keep the branch stable. If this is a critical fix, please let me know and I'll review, otherwise it will be cherry picked for 1.8.2.  Thanks!

**Comment by piosz** [comment]
@jpbetz yes, please include this is 1.8.1

**Comment by jpbetz** [comment]
Looks like the `pull-kubernetes-e2e-kubeadm-gce` test is not progressing due to https://github.com/kubernetes/test-infra/issues/4912. Looking in how to mitigate this now.

**Pull request merged**
