### PR TITLE
Remove misleading listType=map on CRD Validation rules

### PR DESCRIPTION
**Pull request by jpbetz**
#### What type of PR is this?

/kind cleanup
/kind api-change

#### What this PR does / why we need it:

Per https://github.com/kubernetes/kubernetes/pull/112883#discussion_r1007167949 the `listType=map` tags on CRD validation rules is not respected because it is nested under `spec.versions` which is marked as atomic. This change removes the tags, since they are not active and only serve to confuse API users.

#### Special notes for your reviewer:

From a system behavior point of view this is a no-op.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by cici37 — COMMENTED** [review]
The following should be removed together:
1. https://github.com/kubernetes/kubernetes/blob/526650fc137b2e68267182b1b5116aa566be51e5/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go#L128-L131
2. https://github.com/kubernetes/kubernetes/blob/572804c93d10bce53727ca1c9c0384108ebab27e/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go#L167-L170

**Comment by jpbetz** [comment]
/close
Closing due to lack of interest. If anyone is willing to review please feel free to reopen.

**Pull request closed without merging**
