### PR TITLE
build/external: Move dependencies.yaml and update OWNERS

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Moves `build/dependencies.yaml` to `build/external/dependencies.yaml` and seeds an initial OWNERS.

**Which issue(s) this PR fixes**:

Ref: #80546

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by yastij — APPROVED** [review]
/lgtm

**Review by SataQiu — APPROVED** [review]

**Review by neolit123 — COMMENTED** [review]
thanks a lot for helping with this move @justaugustus 
i'm +1 on having the YAML in a sub directory.

WRT to the name of the path, would it be better to use `build/dependencies/versions.yaml` as you suggested earler?

**Comment by justaugustus** [comment]
> WRT to the name of the path, would it be better to use `build/dependencies/versions.yaml` as you suggested earler?

@neolit123 -- I opted for `build/external/dependencies.yaml` here because thinking about it a little, I didn't feel like `versions.yaml` told a complete story i.e., the file has dependency names, versions, references to files.

I'm also thinking that `build/external` could house "other stuff" (maybe example configs for external deps?), but that's a future discussion I think.

**Comment by cblecker** [comment]
I thought based on https://github.com/kubernetes/kubernetes/issues/80546#issuecomment-515732207 and https://github.com/kubernetes/kubernetes/issues/80546#issuecomment-516775698 we were going to document things before we looked at expanding this. Or am I misunderstanding?

**Comment by cblecker** [comment]
/hold
based on https://github.com/kubernetes/kubernetes/pull/80799#issuecomment-517100532

**Comment by xmudrii** [comment]
@justaugustus @cblecker Hello! I'm the bug triage lead for the 1.16 release cycle and considering this PR is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking PRs will be considered to be merged. Is this PR still planned for the 1.16 release?

**Comment by xmudrii** [comment]
@justaugustus This seems to be RelEng related and may be related for this release too. Should we leave this in 1.16 milestone or move to 1.17?

**Comment by lachie83** [comment]
Confirmed with @justaugustus that this is NOT release blocking

**Pull request closed without merging**
