### PR TITLE
Update comments.

### PR DESCRIPTION
**Pull request by HaiyangDING**
Change limit to request in the comments in CheckPodsExceedingFreeResources()

### CODE REVIEW

**Comment by piosz** [comment]
Shippable is failing while trying to verify gendocs. Syncing to head should fix the problem. Could you do it?

**Comment by HaiyangDING** [comment]
@piosz 

Hi, what do you mean by "Syncing to head"?

**Comment by piosz** [comment]
```
git fetch upstream
git rebase upstream/master
```
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#keeping-your-development-fork-in-sync

**Comment by HaiyangDING** [comment]
@piosz 

Thanks, I'll try that.

**Comment by piosz** [comment]
Thanks for the change!

**Pull request merged**
