### PR TITLE
Automated cherry pick of #61235: Support new NODE_OS_DISTRIBUTION 'custom' on GCE

### PR DESCRIPTION
**Pull request by yguo0905**
Cherry pick of #61235 on release-1.8.

#61235: Support new NODE_OS_DISTRIBUTION 'custom' on GCE

### CODE REVIEW

**Comment by yguo0905** [comment]
@BenTheElder @krzyzacy 
The kubetest issue happened again.

**Comment by krzyzacy** [comment]
@yguo0905 I sent https://github.com/kubernetes/kubernetes/pull/61636 for 1.8

**Comment by krzyzacy** [comment]
(still pending on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-stable2/1104)

**Comment by krzyzacy** [comment]
(nvm, shouldn't matter)

**Pull request merged**
