### PR TITLE
Graduate custom metrics API to v1beta1

### PR DESCRIPTION
**Pull request by DirectXMan12**
This graduates `custom-metrics.metrics.k8s.io/v1alpha1` to `custom.metrics.k8s.io/v1beta1`.  The move is more-or-less just a straightforward rename.

Part of kubernetes/features#117 and kubernetes/features#118

```release-note
the custom metrics API (custom.metrics.k8s.io) has moved from v1alpha1 to v1beta1
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-autoscaling-misc @kubernetes/sig-instrumentation-misc 
cc @piosz

**Comment by wojtek-t** [comment]
This is a bit more product decision (do we have enough knowledge to say that it's fine for beta)?
I don't have enough context to unassigning myself from that.

Once this is lgtmed be more involved people, I'm happy to approve this PR.

**Comment by piosz** [comment]
@erictune could you please take a look on behalf of @kubernetes/api-approvers

**Comment by smarterclayton** [comment]
/approve

On sig recognizance

**Comment by calebamiles** [comment]
manually added `lgtm` after rebase.

**Comment by smarterclayton** [comment]
Pre ship the group needs to be renamed to custom.metrics.k8s.io, I expect that to be covered in the metrics to v1beta1 PR.  Please link here

**Comment by calebamiles** [comment]
should a `do-not-merge` be applied here @smarterclayton, @DirectXMan12? or is it fine to let this merge as SQ decides?

**Comment by piosz** [comment]
I changed the api group in release notes.

**Comment by smarterclayton** [comment]
> but nothing to do with this PR besides cross linking to the other PR correct

Correct

**Pull request merged**
