### PR TITLE
Add priority class to CoreDNS pods

### LINKED ISSUE #1337: CoreDNS pods lack a positive priority value (no priority class specified)
## What keywords did you search in kubeadm issues before filing this one?

- _dns_
- _coredns_
- _priority_
- _class_
- _priorityclass_

## Is this a BUG REPORT or FEATURE REQUEST?

_BUG REPORT_

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:  
  AWS EC2
- **OS** (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.5.0
VERSION_ID=1911.5.0
BUILD_ID=2018-12-15-2317
PRETTY_NAME="Container Linux by CoreOS 1911.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- **Kernel** (e.g. `uname -a`):  
  `Linux ip-10-105-50-28 4.14.84-coreos #1 SMP Sat Dec 15 22:39:45 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`

## What happened?

After running _kubeadm init_ (allowing it to run [the "addon/coredns" phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-addon)), my cluster has a _Deployment_ called "coredns" in the "kube-system" namespace, and its pod spec template lacks a value for [the `PriorityClassName` field](https://github.com/kubernetes/api/blob/release-1.13/core/v1/types.go#L2886-L2893).

Without this field present, the CoreDNS pods receive the default pod priority, which is zero unless an administrator has created a `PriorityClass` object with a positive value and designated it as the global default. Normally, these CoreDNS pods will run on the master machines which will repel most tenant-submitted workload by virtue of the role taint, but still, it would be safer to run these CoreDNS pods at a boosted priority to make it clear that they must be scheduled and keep running at the expense of other, lesser pods—assuming that we agree that in-cluster DNS is a critical service.

## What you expected to happen?

The "coredns" _Deployment_'s pod spec template would have its "priorityClassName" populated with the value "system-cluster-critical," granting it a priority of 2,000,001,000.

## How to reproduce it (as minimally and precisely as possible)?

Run either _kubeadm init_ or _kubeadm init phase addon coredns_, confirm that it succeeds, then inspect the pods created by the resulting _Deployment_:
```
kubectl get pods \
  --namespace=kube-system \
  --selector=k8s-app=kube-dns \
  --output=custom-columns='NAME:{.metadata.name},CLASS:{.spec.priorityClassName},VALUE:{.spec.priority}'
NAME                       CLASS    VALUE
coredns-86c58d9df4-xfp9f   <none>   0
coredns-86c58d9df4-zn7rd   <none>   0
```

## Anything else we need to know?

If we can't agree that [the built-in priority class "system-cluster-critical"](https://sourcegraph.com/github.com/kubernetes/kubernetes@71050b6f2dfe67bb2fb6d0acf6a64bc1e3cc50b0/-/blob/pkg/apis/scheduling/helpers.go#L35-41) is appropriate here, we could define a weaker or lower priority class. At the level at which _kubeadm init_ operates, though, it's hard to say how we'd guess what a more appropriate priority value would be, and we may inadvertently make it more difficult for administrators to restrict use of high-priority classes by introducing more of them.

Some precedent for using the "system-cluster-critical" priority class in _kubeadm_: kubernetes/kubernetes#63684 (addressing #395).

### PR DESCRIPTION
**Pull request by ojmhetar**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Adds `priorityClassName` to give preference in scheduling CoreDNS pods over less critical pods.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubeadm/issues/1337

**Special notes for your reviewer**:
I realize that we might want to wait until some of the issues in CoreDNS are addressed. At some point, CoreDNS should have the same priority as kube-dns as a default, cluster critical component. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

cc @timothysc

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/hold
/priority important-longterm

this PR is not updating the coredns manifests in kubeadm, but it links to a kubeadm issue:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go

also not sure we ended up agreeing that we should do this for kubeadm.
/assign @fabriziopandini @timothysc 

we might decide to scope this to the cluster folder only?

**Comment by ojmhetar** [comment]
My mistake. Should I file a separate issue for this?

**Comment by neolit123** [comment]
historically we'e made such updates in the same PR for all deployers.

**Comment by fabriziopandini** [comment]
XREF https://github.com/kubernetes/kubeadm/issues/1291
This problem does not affect only CoreDNS

**Comment by neolit123** [comment]
@ojmhetar 
please replace the `Fixes ...` in the PR description with:
`xref kubernetes/kubeadm#1337`

otherwise it will close the tracking issue.
thanks.

**Comment by ojmhetar** [comment]
Are there reasons to scope this to the cluster folder? Otherwise, I can update this PR to include the manifest in kubeadm.

**Comment by timothysc** [comment]
@ojmhetar - please update this PR to modify the kubeadm manifests as well.

**Comment by ojmhetar** [comment]
fixed for coredns. I see that the same is missing for kubedns, do we want to address that here?

**Comment by yagonobre** [comment]
@ojmhetar IMO you should add it to kubedns as well.

**Review by rajansandeep — COMMENTED** [review]
The changes for kube-dns should be done in the cluster folder as well.

**Comment by ojmhetar** [comment]
@rajansandeep kubedns already has these changes since 1.11: 
https://github.com/kubernetes/kubernetes/blob/release-1.11/cluster/addons/dns/kube-dns/kube-dns.yaml.base#L88

**Comment by rajansandeep** [comment]
@ojmhetar Sorry, that part skipped by me.
/lgtm

**Comment by ojmhetar** [comment]
no worries! 😄

**Comment by timothysc** [comment]
/approve  

- from kubeadm side.  

/hold cancel

**Pull request merged**
