### PR TITLE
Update gazelle to latest to fix vendoring issue

### LINKED ISSUE #60730: verify-bazel failing with 'cannot find package "github.com/bazelbuild/buildtools/build"' etc
/kind bug

verify-bazel is currently failing with the following stacktrace:
```
$ hack/verify-bazel.sh 
../../internal/config/directives.go:24:2: cannot find package "github.com/bazelbuild/buildtools/build" in any of:
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/build (vendor tree)
        [path]/.gvm/gos/go1.9.4/src/github.com/bazelbuild/buildtools/build (from $GOROOT)
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/buildtools/build (from $GOPATH)
../../internal/rules/construct.go:27:2: cannot find package "github.com/bazelbuild/buildtools/tables" in any of:
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/tables (vendor tree)
        [path]/.gvm/gos/go1.9.4/src/github.com/bazelbuild/buildtools/tables (from $GOROOT)
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/buildtools/tables (from $GOPATH)
!!! [0302 11:47:54] Call tree:
!!! [0302 11:47:54]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483
  Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483. '((i<3-1))' exited with status 1
Call stack:
  1: /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483 kube::util::go_install_from_commit(...)
  2: ./hack/update-bazel.sh:34 main(...)
Exiting with status 1
!!! [0302 11:47:54] Call tree:
!!! [0302 11:47:54]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473
  Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473. '((i<3-1))' exited with status 1
Call stack:
  1: /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473 kube::util::go_install_from_commit(...)
  2: ./hack/update-bazel.sh:34 main(...)
Exiting with status 1
!!! Error in hack/verify-bazel.sh:43
  Error in hack/verify-bazel.sh:43. 'GOPATH="${_tmp_gopath}" ./hack/update-bazel.sh' exited with status 1
Call stack:
  1: hack/verify-bazel.sh:43 main(...)
Exiting with status 1
```

Ironically, this is caused by a fix upstream which would probably prevent #60442 from occurring again - gazelle vendored `github.com/bazelbuild/buildtools` in https://github.com/bazelbuild/bazel-gazelle/pull/145, which means that when we hackily download gazelle's dependencies with `go get -d`, we no longer also download the `github.com/bazelbuild/buildtools` package.

We then checkout an older version of gazelle, which hasn't vendored `github.com/bazelbuild/buildtools`, and so the dependency is missing, and we fail to build.

For the master branch, we can probably just bump to latest gazelle. The older release branches will probably require more hacks.

Happy Friday!
/assign

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: Fixes #60730 for the master branch. There are otherwise no functional differences.

**Release note**:

```release-note
NONE
```

/priority critical-urgent
/milestone v1.10
/kind bug
/sig testing

### CODE REVIEW

**Comment by ixdy** [comment]
/sig release
too?

**Comment by BenTheElder** [comment]
is queue/fix still a thing? cc @cjwagner

**Pull request merged**
