### PR TITLE
expose master count configuration in a cli option on apiserver

### LINKED ISSUE #18535: Multiple apiservers fighting over endpoint
I've done a bunch of searching for an answer to this but don't see a real solution. If you're running with the [currently recommended](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md#load-balancing) solution for multiple api servers they continuously update the kubernetes service endpoint. This doesn't _really_ cause any problems until you try to use the Ingress resource since the endpoint modification causes the ingress controller (at least the haproxy one, I don't see any reason why the same wouldn't be true of any other) to continuously restart.

It also spams the kube-proxy logs with:
```
kube-proxy[1580]: I1210 21:44:08.572592    1580 proxier.go:352] Setting endpoints for "default/kubernetes:" to [10.0.167.163:443]
```
every couple seconds.

It looks like #8649 is the latest attempted fix, however (at least on AWS) there's no address to advertise since ELBs aren't static IPs. #6672 references #6995 but neither of those end up in real solutions. #7273 looks like it was exactly what I'm looking for but then #7704 seems to have removed it without any explanation that I saw.

This is all a really long winded way to say, what's the real recommended way to run multiple API servers?

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #18535

### CODE REVIEW

**Comment by mikedanese** [comment]
reassigning since lavalamp is out

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Needs rebase.

**Comment by mikedanese** [comment]
@k8s-bot unit test this please

**Comment by davidopp** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by mikedanese** [comment]
@k8s-bot e2e test this please

**Pull request merged**
