### PR TITLE
Fix etcd path construction

### PR DESCRIPTION
**Pull request by tallclair**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes etcd path construction to handle invalid input.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig api-machinery
/milestone v1.26

### CODE REVIEW

**Comment by tallclair** [comment]
Note: the unit tests in this patch differ significantly from the v1.25 and older versions (https://github.com/kubernetes/kubernetes/pull/113684) due to a number of test refactors on the master branch, such as https://github.com/kubernetes/kubernetes/commit/e49c225eb9e7c428aca97e8031089e7ad91ca7c4 and https://github.com/kubernetes/kubernetes/commit/75a1ef87b32213a7d3d1c2027dd515e4f74c1777

**Comment by wojtek-t** [comment]
[For posterity - this LGTM too]

**Pull request merged**
