### PR TITLE
Include serial port output in GCP log-dump

### PR DESCRIPTION
**Pull request by mtaufen**
This should help us debug reboot failures e.g. https://github.com/kubernetes/kubernetes/issues/33882
Also useful for OOM-kill investigation.

/cc @dchen1107

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37248)

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot test this

**Comment by mikedanese** [comment]
@k8s-bot bazel test this

**Comment by mtaufen** [comment]
@jessfraz this should be cherry-picked to 1.4 along with https://github.com/kubernetes/kubernetes/pull/37401

**Comment by jessfraz** [comment]
cherry-picked in #37864

**Pull request merged**
