### PR TITLE
WIP: Allow apiserver to destroy rest storages2

### PR DESCRIPTION
**Pull request by ingvagabund**
DO-NOT-MERGE
/hold
only for debugging

### CODE REVIEW

**Comment by yue9944882** [comment]
is this proposed by @sttts? we discussed about this a year ago i remember..

**Comment by ingvagabund** [comment]
@yue9944882 full store is at https://github.com/kubernetes/kubernetes/pull/84667

This is to debug https://github.com/kubernetes/kubernetes/pull/84667 actually so I don't have to change the original PR.

**Comment by ingvagabund** [comment]
Something between `1772446c46fab6786bdc58f17a7fa6584768c17e` (2019-11-08) and `6f08d42dec2f2444ba59fd46d5d40ff7c6e6c8ab` (2019-11-06) got merged that causes the failure.

**Pull request closed without merging**
