### PR TITLE
fixed typo in kubeadm/v1alpha1/defaults.go

### PR DESCRIPTION
**Pull request by bistros**
**What this PR does / why we need it**:
fixed some typo in comment

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
Thanks for the fix!

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by bistros** [comment]
I did signed CLA

**Comment by bistros** [comment]
retry sign CLA

**Comment by stewart-yu** [comment]
Kindly hint, may be same as [https://github.com/kubernetes/kubernetes/pull/56565](https://github.com/kubernetes/kubernetes/pull/56565)

**Review by luxas — APPROVED** [review]
Thanks @bistros for your contribution!

Did you sign the CLA for dev.bistros@gmail.com? If not, please do, or use an other commit email. If that doesn't help, please follow the support steps outlined in the bot message above.

@stewart-yu let's merge this one as-is, and exclude this change from https://github.com/kubernetes/kubernetes/pull/56565

That way both authors will be able to contribute.

@bistros in the future, please go through many kubeadm source code files and fix other comment issues and typos at the same time. https://github.com/kubernetes/community/blob/master/CONTRIBUTING.md#trivial-edits

Happy to have you start contributing to kubeadm!

**Comment by xiangpengzhao** [comment]
comment to verify CLA.

**Comment by xiangpengzhao** [comment]
@bistros seems like the bot still can't pass the CLA verification. Please check your CLA status :)

**Comment by bistros** [comment]
Sorry, I sent a mail to helpdesk at linuxfoundation
and wating a reply

**Review by luxas — APPROVED** [review]
/approve no-issue

**Comment by luxas** [comment]
Yay, the CLA bot went green!!
Thanks for this contribution, looking forward to see what you will help us with next :smile:

**Pull request merged**
