### PR TITLE
Fix hash bangs to use /usr/bin/env

### PR DESCRIPTION
**Pull request by colemickens**
I executed this on the entire tree (except Godeps):

```
find . -type f -print0 | xargs -0 sed -i 's|#!/bin/|#!/usr/bin/env |g'
```

This increases portability, and for example, enables building Kubernetes on NixOS.

edit: This is the better command to run: 

```
cd kubernetes/kubernetes
find * -type f -exec sed -i 's|#!/bin/|#!/usr/bin/env |g' {} +
```

That still doesn't always get everything, I'm not sure why. For my own notes:

```
find build/ -type f -exec sed -i 's|#!/bin/|#!/usr/bin/env |g' {} +
find cluster/ -type f -exec sed -i 's|#!/bin/|#!/usr/bin/env |g' {} +
```

### CODE REVIEW

**Comment by ixdy** [comment]
Without some sort of verification check in `hack/verify-*`, this is likely to be an endless chase.

**Comment by ixdy** [comment]
(unassigning myself because I don't really have the cycles to review this. hopefully the bot will reassign to someone else.)

**Comment by ihmccreery** [comment]
+1 to what @ixdy said; add a linter?

**Comment by ihmccreery** [comment]
Also I don't understand your edit; please clarify?

**Comment by colemickens** [comment]
@ihmccreery The first command repeatedly missed files the `cluster/` directory. I force pushed a new commit after running the second command that got the files in `cluster/`. I don't pretend to understand xargs; the latter is more intuitive to me and seems to work correctly.

I'll look at adding a linter, I agree it's probably an uphill battle without one.

**Comment by colemickens** [comment]
Rebased, added a `verify-shebangs.sh` script.

This doesn't catch every single instance, but it catches most - including all of the ones that a developer would run into when trying to build/deploy.

There are places where startup scripts are emitted that are not caught because they don't appear at the beginning of the line. If I relax that restriction and match anywhere in the file, then it falsely matches things like Google Groups URLS `#!forum/` or doc URLs `#!/v1/`.

**Comment by ihmccreery** [comment]
This PR has needed a rebase for a month and a half.  I'm going to close as abandoned; @colemickens feel free to reopen if you want to take this over the finish line.

**Pull request closed without merging**
