### PR TITLE
Remove unnecessary ETCD_UNSUPPORTED_ARCH for arm64

### PR DESCRIPTION
**Pull request by dims**
we should only use this env var for `arm`, since `arm64` is fully supported by etcd folks, let us drop this!

(ex - https://github.com/etcd-io/etcd/releases/tag/v3.5.6)

ppc64le comment should be dropped as well

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig architecture
/priority important-soon

### CODE REVIEW

**Comment by aojea** [comment]
> we should only use this env var for `arm`, since `arm64` is fully supported by etcd folks, let us drop this!

is it fully supported?

https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/op-guide/supported-platform.md

> Tier 3: etcd is guaranteed to build, may be lightly tested (or not), and so it should be considered unstable.

**Comment by serathius** [comment]
For v3.5 we reverted arm64 support to tier 3, because we lost access to arm machines for testing. There are couple of people interested in working on improving it, however no progress yet.

**Comment by dims** [comment]
@serathius are you happy with the arm64 CI testing progress to let this PR land?

**Comment by serathius** [comment]
We still need to do some work for etcd to officially give full support to arm64, however this can be a separate decision for K8s.

**Comment by dims** [comment]
@aojea - per last comment from @serathius we are ok to land this. thanks!

**Comment by dims** [comment]
@aojea @serathius can you please `/lgtm`?

**Comment by dims** [comment]
@serathius had to rebase, can you please reapply `/lgtm`

**Pull request merged**
