### PR TITLE
First draft of Cluster Federation RFC.

### PR DESCRIPTION
**Pull request by ghost**
First draft of Cluster Federation RFC.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Ping.  Can this be merged?

**Comment by bgrant0607** [comment]
Sorry, I thought you were collecting feedback. If you're done collecting feedback, could you convert the Google doc into markdown?

**Comment by quinton-hoole** [comment]
OK, no, I"m not done collecting feedback yet.  Lets leave it unmerged for now, if that's the protocol.

**Comment by piosz** [comment]
Is this PR active? If not please close it according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/pull-requests.md

**Comment by quinton-hoole** [comment]
The majority of feedback is in the linked doc now.  I'm busy tidying it up before converting to MD format here.  But I'm happy to close this PR in the mean time.

**Pull request closed without merging**
