### PR TITLE
Clarifies redaction around some rogue 10 mCPUs

### PR DESCRIPTION
**Pull request by marianogappa**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32283)

### CODE REVIEW

**Comment by MarianoGappa** [comment]
I signed it!

**Comment by smarterclayton** [comment]
You need to sign the CLA via the CNCF - changes look fine to me otherwise and then I'll merge it.

**Comment by MarianoGappa** [comment]
@smarterclayton thanks; sent. Awaiting approval.

**Comment by MarianoGappa** [comment]
@smarterclayton there.
screen shot 2016-10-11 at 6 46 26 pm

**Comment by smarterclayton** [comment]
ok to test

**Comment by bgrant0607** [comment]
@MarianoGappa Sorry, but this document has moved to the community repo (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md), and some of the issues have been fixed. Please open a new PR in that repo if you still see anything that needs to be addressed.

**Pull request closed without merging**
