### PR TITLE
Cherry pick 108339 back to v1.23

### PR DESCRIPTION
**Pull request by cheftako**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Bump konnectivity network proxy to v0.0.28.
Includes a fix to ensure the KAS calls Close() on the egress connection.
Pulls in updates ANP binary fixes (https://github.com/kubernetes-sigs/apiserver-network-proxy/commits/v0.0.28)

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
FYI, there is a PR open for fixing another goroutine leak (https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/337). It might be easier to cut v0.0.29 and cherry-pick that together with the changes in v0.0.28.

**Comment by rata** [comment]
@andrewsykim big +1. Didn't know this was already opened, but thanks a lot anyways!

@cheftako will you handle the backporting of the new ANP release (I mean 0.029 when that is done) to all supported k8s versions? If not, I can help

**Comment by liggitt** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/pull/108438

**Pull request closed without merging**
