### PR TITLE
Release 0.21.1

### PR DESCRIPTION
**Pull request by zmerlynn**
Already in the branch:
#10877
#10884
#10562
#10488

### CODE REVIEW

**Comment by zmerlynn** [comment]
@thockin: aa618a97f41b71722305906e86372b8f60e5a254 doesn't look right, but the commit message and the `mark-new-version.sh` session pretty clearly show I'm tagging `v0.21.1` here, so I'm not sure what's going on. I'm proceeding.

**Comment by zmerlynn** [comment]
Self-merging to proceed with the release. (Don't do this at home.)

**Comment by zmerlynn** [comment]
Recording this session here:

```
zml@zml:~/kubernetes$ ./build/mark-new-version.sh v${VER}.${PATCH}
+++ Versioning documentation and examples
+++ [0708 18:52:37] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
+++ [0708 18:52:43] Placing binaries
etcd -data-dir /tmp/test-etcd.9Nk5ce --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null
Waiting for etcd to come up.
+++ [0708 18:52:48] On try 1, etcd: :
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0708 18:52:49] Starting kube-apiserver
+++ [0708 18:52:50] On try 2, apiserver: : ok
+++ [0708 18:52:50] Updating
    ./build/../hack/../api/swagger-spec
+++ [0708 18:52:50] SUCCESS
+++ [0708 18:52:50] Clean up complete
[release-0.21 aa618a9] Versioning docs and examples for 0.21.1
 2 files changed, 104 insertions(+), 104 deletions(-)
+++ Updating to v0.21.1
+++ Committing version change
[release-0.21 906122a] Kubernetes version v0.21.1
 1 file changed, 2 insertions(+), 2 deletions(-)
+++ Tagging version
+++ Updating to v0.21.1-dev
+++ Committing version change
[release-0.21 9d2691d] Kubernetes version v0.21.1-dev
 1 file changed, 2 insertions(+), 2 deletions(-)
+++ Constructing backmerge branches
Switched to a new branch 'v0.21.1-merge-to-master-tmp-1436406771'
[v0.21.1-merge-to-master-tmp-1436406771 539e7c8] Revert "Versioning docs and examples for 0.21.1"
 2 files changed, 104 insertions(+), 104 deletions(-)
Branch v0.21.1-merge-to-master set up to track remote branch master from upstream.
Switched to a new branch 'v0.21.1-merge-to-master'
Merge made by the 'recursive' strategy.
 pkg/version/base.go | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
Switched to branch 'release-0.21'
Your branch is ahead of 'upstream/release-0.21' by 3 commits.
  (use "git push" to publish your local commits)
Deleted branch v0.21.1-merge-to-master-tmp-1436406771 (was 539e7c8).

Success you must now:

- Push the tag:
   git push https://github.com/GoogleCloudPlatform/kubernetes.git v0.21.1
   - Please note you are pushing the tag live BEFORE your PRs.
       You need this so the builds pick up the right tag info.
       If something goes wrong further down please fix the tag!
       Either delete this tag and give up, fix the tag before your next PR,
       or find someone who can help solve the tag problem!

- Send branch: release-0.21 as a PR to release-0.21 <-- NOTE THIS
- Get someone to review and merge that PR

- I created the branch v0.21.1-merge-to-master for you. What I don't know is if this is
  the latest version. If it is, AND ONLY IF IT IS, submit this branch as a pull
  request to master:

   git push <personal> v0.21.1-merge-to-master

  and get someone to approve that PR. I know this branch looks odd. The purpose of this
  branch is to get the tag for the version onto master for things like 'git describe'.

  IF THIS IS NOT THE LATEST VERSION YOU WILL CAUSE TIME TO GO BACKWARDS. DON'T DO THAT, PLEASE.

Already on 'release-0.21'
Your branch is ahead of 'upstream/release-0.21' by 3 commits.
  (use "git push" to publish your local commits)
```

**Comment by thockin** [comment]
LGTM

**Pull request merged**
