### PR TITLE
kube-proxy userspace, never delete service of lb while there is no en…

### PR DESCRIPTION
**Pull request by njuicsgz**
kube-proxy userspace, never delete service of lb while there is no endpoint of this service. Delete when the Service object disappears on api-server.

### CODE REVIEW

**Comment by njuicsgz** [comment]
for issue #13299

I will change the UT tomorrow if there is no negative comments.

**Comment by njuicsgz** [comment]
open a new issue #25314 to trace.

**Comment by thockin** [comment]
Sorry, I didn't see this when I made my own fix.  This change would leak records.  I'm closing this in favor of mine.  Sorry, normally I wouldn't do that, but I didn't read ahead to see you already had a fix proposed.

**Comment by njuicsgz** [comment]
@thockin Never mind, your fix LGTM. And I will verify after your PR merged in 1.2.

**Pull request closed without merging**
