### PR TITLE
Enable protobuf compilation by default

### PR DESCRIPTION
**Pull request by smarterclayton**
Enables protobuf compilation, build verification checks, and generates all initial code.

kubectl is now 47M on OSX, build time from clean on a 2014 MBP (4 core) on Go 1.6 is ~150s.

@wojtek-t

### CODE REVIEW

**Comment by smarterclayton** [comment]
Next steps after this:

1. Implement client protobuf watch and refactor stream serializer and codec factory as necessary to get that in
2. Flag for controller managers and nodes to attempt to use protobuf (experimental) in their client
3. Turn on the flag in some test suites, run full e2e
4. Handle third party resources (nested json encoding in proto) correctly
5. Clean up quantity serialization

**Comment by wojtek-t** [comment]
>
Next steps after this:
Implement client protobuf watch and refactor stream serializer and codec factory as necessary to get that in

Hmm - isn't that only a matter of sending a request with a correct "ContentType" and handle it using a correct serializer? Can you please clarify, because it seems I'm missing something here.

>
Flag for controller managers and nodes to attempt to use protobuf (experimental) in their client

And scheduler. Shouldn't this be just a parameter to client library? WDYT?

>
Clean up quantity serialization

This is just an optimization, right? We can even live without it, right?

**Comment by wojtek-t** [comment]
@smarterclayton - I went through the PR and it LGTM.
Please rebase and feel free to self-apply lgtm label.

My only comments were about next steps - please see above.

**Comment by wojtek-t** [comment]
>>
Flag for controller managers and nodes to attempt to use protobuf (experimental) in their client
>
And scheduler. Shouldn't this be just a parameter to client library? WDYT?

BTW - I'm happy to send a PR for it - just let me know.

**Comment by smarterclayton** [comment]
> Hmm - isn't that only a matter of sending a request with a correct "ContentType" and handle it using a correct serializer? Can you please clarify, because it seems I'm missing something here.

Currently the client library (in request.go) implements "Watch()" which uses the default Codec.Encoder, which is not correct - it would need to get a streaming codec.  My thought is that it may be appropriate to collapse streaming codec factory into codec factory, so there would be new methods on NegotiatedSerializer - `StreamingSerializerFor() ...` which is strongly typed.  However, it needs some thought still because the wrapper methods (that take a serializer) actually have to also handle streaming.  Mostly code movement.

> And scheduler. Shouldn't this be just a parameter to client library? WDYT?

The parameter to client library should be there (for everything except watch) but we'd need to make it an opt-in for now (until we have negotiation).

> Clean up quantity serialization

Since it's part of the public API I'd probably want to sort out what the correct behavior is.  I don't like the current implementation.

**Comment by wojtek-t** [comment]
>
Currently the client library (in request.go) implements "Watch()" which uses the default Codec.Encoder, which is not correct - it would need to get a streaming codec. My thought is that it may be appropriate to collapse streaming codec factory into codec factory, so there would be new methods on NegotiatedSerializer - StreamingSerializerFor() ... which is strongly typed. However, it needs some thought still because the wrapper methods (that take a serializer) actually have to also handle streaming. Mostly code movement.

Thanks for clarification.

>
The parameter to client library should be there (for everything except watch) but we'd need to make it an opt-in for now (until we have negotiation).

Can you point me to this parameter?
And sure - we need to make it possible to opt-in. I'm happy to do it. Do you want me to do that?

>
Clean up quantity serialization

Since it's part of the public API I'd probably want to sort out what the correct behavior is. I don't like the current implementation.

Why do you think it's bad?

**Comment by smarterclayton** [comment]
The parameter should be `ContentType` in the client.Config object.

Regarding quantity - the way we model it in JSON is as a string.  I'd want
to run some tests just on performance, but it's possible that it would be
better to output it the exact same way in proto (as a string) for client
libraries that need to handle it.  On the other hand, there's a lot of
rules for handling it, so maybe the distinct type is better.  But in terms
of consistency for client libraries it's much, much simpler.

**Comment by wojtek-t** [comment]
>
The parameter should be `ContentType` in the client.Config object.

Thanks - I can send a PR adding contentType parameter to our binaries tomorrow.

>
Regarding quantity - the way we model it in JSON is as a string.  I'd want
to run some tests just on performance, but it's possible that it would be
better to output it the exact same way in proto (as a string) for client
libraries that need to handle it.  On the other hand, there's a lot of
rules for handling it, so maybe the distinct type is better.  But in terms
of consistency for client libraries it's much, much simpler.

Thanks for clarification.

**Comment by smarterclayton** [comment]
Trivial change to add generated-protobuf to hack/update-all.sh as commented on the thread.

**Comment by smarterclayton** [comment]
Trivial rebase, reapplying

**Comment by smarterclayton** [comment]
Bumping to p2 so it goes ahead of some other stuff in the queue, otherwise we'll be waiting months to enable.

**Comment by smarterclayton** [comment]
Trivial rebase

**Comment by smarterclayton** [comment]
@k8s-bot test this issue: #21484

**Comment by smarterclayton** [comment]
Looks like the node e2e job has hung

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Pull request merged**
