### PR TITLE
Improve service unit test failure report

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

To follow up https://github.com/kubernetes/kubernetes/pull/119150#discussion_r1310293456, mark the helper functions with t.Helper() so that if t.Errorf() in these functions gets called, it will report that the failure occurred on the line number of the caller of the helper, rather than the line number of the helper itself, which makes it hard to identify which case causes the failure.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

cc @danwinship 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm

before:
```
danw@p1:kubernetes (master *)> git diff -U0
diff --git a/pkg/api/service/util_test.go b/pkg/api/service/util_test.go
index 5a308239c5c..2af840c98f8 100644
--- a/pkg/api/service/util_test.go
+++ b/pkg/api/service/util_test.go
@@ -47 +47 @@ func TestGetLoadBalancerSourceRanges(t *testing.T) {
-       checkError("10.0.0.1/32,")
+       checkError("10.0.0.1/32")
danw@p1:kubernetes (master *)> go test -count=1 ./pkg/api/service/
--- FAIL: TestGetLoadBalancerSourceRanges (0.00s)
    util_test.go:35: Expected error parsing: "10.0.0.1/32"
    util_test.go:41: Expected error parsing: "10.0.0.1/32"
FAIL
FAIL	k8s.io/kubernetes/pkg/api/service	0.004s
FAIL
```

after:

```
danw@p1:kubernetes (master *)> git diff -U0
diff --git a/pkg/api/service/util_test.go b/pkg/api/service/util_test.go
index 5a308239c5c..9653d624fe3 100644
--- a/pkg/api/service/util_test.go
+++ b/pkg/api/service/util_test.go
@@ -28,0 +29 @@ func TestGetLoadBalancerSourceRanges(t *testing.T) {
+               t.Helper()
@@ -47 +48 @@ func TestGetLoadBalancerSourceRanges(t *testing.T) {
-       checkError("10.0.0.1/32,")
+       checkError("10.0.0.1/32")
danw@p1:kubernetes (master *)> go test -count=1 ./pkg/api/service/
--- FAIL: TestGetLoadBalancerSourceRanges (0.00s)
    util_test.go:48: Expected error parsing: "10.0.0.1/32"
    util_test.go:48: Expected error parsing: "10.0.0.1/32"
FAIL
FAIL	k8s.io/kubernetes/pkg/api/service	0.004s
FAIL
```

**Comment by tnqn** [comment]
Thank you @danwinship.

/assign @thockin

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
