### PR TITLE
Add kubectl-convert to client-binaries

### LINKED ISSUE #99076: kubectl-convert is not included in release artifacts
#### What happened:

`kubectl convert` was removed in 1.20 in favor of a `kubectl-convert` plugin. However, this is not included in release artifacts.

#### What you expected to happen:

The binary is included in release artifacts, and ideally easily installable via kubectl plugin managers like `krew`.

/sig cli
/assign @soltysh

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?

/kind cleanup
/kind documentation

/sig cli
/sig release
/priority backlog

#### What this PR does / why we need it:
In https://github.com/kubernetes/kubernetes/pull/96190 I moved all the remaining bits of kubectl to staging repository. Per https://github.com/kubernetes/kubectl/issues/725 it was decided that `kubectl convert` will become a plugin but I missed it in that PR. This should fix our release such that it will include `kubectl-convert` binaries along `kubectl`. 

#### Which issue(s) this PR fixes:
Fixes #99076 

#### Special notes for your reviewer:
/assign @liggitt @neolit123 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
I typically would not prefer to add a binary to our release artifacts that has already been removed from `kubectl` because of its dependencies. However, I also understand that `kubectl-convert` is pretty tightly coupled to k8s versions. I wonder how we feel about this compared to something like `kubeadm`, which has seen some [motivation to be moved out of k/k](https://github.com/kubernetes/enhancements/pull/1425). `kubectl-convert` is difficult because the same reason it was broken out from `kubectl` (dependency on internal types) seems to be the primary motivation for including it in k/k release process. Would like to discuss more before we commit to releasing as part of k/k because we are trying to minimize churn on the artifacts we are producing.

/hold

**Comment by neolit123** [comment]
> I typically would not prefer to add a binary to our release artifacts that has already been removed from kubectl because of its dependencies. However, I also understand that kubectl-convert is pretty tightly coupled to k8s versions. I wonder how we feel about this compared to something like kubeadm, which has seen some motivation to be moved out of k/k. 

while we had plans to move kubeadm out of k/k the preference was to still continue releasing it.

> kubectl-convert is difficult because the same reason it was broken out from kubectl (dependency on internal types) seems to be the primary motivation for including it in k/k release process. Would like to discuss more before we commit to releasing as part of k/k because we are trying to minimize churn on the artifacts we are producing.

i'm +1 on including kubectl-convert in the release, or if not kubectl-convert, a general mechanism to allow users to migrate their manifests on disk away from a unsupported API.

**Comment by hasheddan** [comment]
Another thing to note is that we should actively be testing artifacts that are part of the k/k release bundles. Do we have periodic jobs exercising `kubectl-convert` functionality?

**Comment by justaugustus** [comment]
+1 to @hasheddan's assessment. Will hold any comments from my side pending response.
/area release-eng

**Comment by liggitt** [comment]
> `kubectl-convert` is difficult because the same reason it was broken out from `kubectl` (dependency on internal types) seems to be the primary motivation for including it in k/k release process.

Pairing `kubectl-convert` to the same release process as `kube-apiserver` makes sense to me, because that is the cadence at which changes to built-in types and conversion logic are released. The command is useful when users need to [migrate their manifests from a deprecated version to a stable version](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#migrate-to-non-deprecated-apis). Requiring users to compile their own instance doesn't seem reasonable, so I think it should be built/released _somehow_.

That said, if the goal of `kubectl` cutting `k8s.io/kubernetes` dependencies was to [allow it to have its own release](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1020-kubectl-staging#motivation), putting a new artifact explicitly coupled to the `kube-apiserver` release in the same bundle as `kubectl` seems like backtracking.

> Another thing to note is that we should actively be testing artifacts that are part of the k/k release bundles. Do we have periodic jobs exercising kubectl-convert functionality?

+1 to testing.

**Comment by soltysh** [comment]
> Another thing to note is that we should actively be testing artifacts that are part of the k/k release bundles. Do we have periodic jobs exercising `kubectl-convert` functionality?

We used to have some test in test-cmd suite, lemme ensure they are properly testing `kubectl-convert`.

**Comment by soltysh** [comment]
Now with convert test in 2nd commit.

**Comment by dims** [comment]
/approve

(/build changes look good)

**Comment by justaugustus** [comment]
(Will drop an `/approve` on this once the verify test passes.)

**Comment by soltysh** [comment]
> (Will drop an `/approve` for `build/` on this once the verify test passes.)

Fixed all the bits, should be good now.

**Review by hasheddan — COMMENTED** [review]
/hold cancel

Acknowledging that this is a special case and testing has been added.

/retest

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/28724: _Document how to install kubectl convert plugin_

**Pull request merged**
