### PR TITLE
Added field selector for listing pods

### PR DESCRIPTION
**Pull request by ravigadde**
Added a field selector for listing pods

### CODE REVIEW

**Comment by ravigadde** [comment]
I authored the commits.

**Comment by brendandburns** [comment]
You need to sign the CLA, details in CONTRIBUTING.md

**Comment by brendandburns** [comment]
This LGTM, modulo getting the CLA signed.

**Comment by ravigadde** [comment]
@brendanburns I think there is some confusion between individual and corporate CLAs. I had originally signed an individual CLA. After signing the corporate CLA, I started seeing this error. I have now added my corporate email to my github account. Hope that helps.

**Comment by fgrzadkowski** [comment]
LGTM.

Can you please look into travis/shippable failures?

**Comment by ravigadde** [comment]
Fixed the travis issue. Can anyone tell me what the shippable failure is? I cant see it.

**Comment by fgrzadkowski** [comment]
F0421 13:48:12.847654    3342 integration.go:393] static-pod-from-manifest FAILED: mirror pod has not been created or is not running: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1" --maxConcurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:47 runTests(...)
  2: ./hack/test-integration.sh:61 main(...)
Exiting with status 1

**Pull request merged**
