### PR TITLE
node_e2e: Update framework to provide OS distro

### PR DESCRIPTION
**Pull request by euank**
This PR is a result of this comment: https://github.com/kubernetes/kubernetes/issues/28192#issuecomment-229470987

I tested locally that adding a test that looked something like:

```
It("should skip coreos", func() {
  if f.OSDistro == "coreos" {
    framework.Skipf("skip")
  }
})
```

worked as expected.

I also trimmed a bit of old code related to coreos.

cc @vishh @yifan-gu @dubstack @mtaufen

### CODE REVIEW

**Comment by euank** [comment]
@k8s-bot test this issue: #27462

**Comment by vishh** [comment]
* Making tests run based on distros is going to make managing tests much harder. 
* We have a goal to make it possible to easily share tests between cluster and node level e2es. This PR will make it more difficult to reach this goal.

**Comment by euank** [comment]
The options we're picking between in the other issue are:

1) Develop the feature to work sanely across multiple cgroupdriver impls to begin with
2) Alter the CoreOS configuration for the node_e2e test and lose visibility of other changes breaking the systemd cgroup driver
3) Skip a small number of tests on CoreOS

Either 2 or 3 should be temporary pending on 1 and we can revert this then. I'd like to keep visibility if we can.

**Comment by timstclair** [comment]
+1 to what Vish said, but I also think it would be useful to have a way to _temporarily_ disable individual tests for specific distros. Is there a way we can fix this on the jenkins side to ignore specific test-host combinations that we set?

**Comment by euank** [comment]
Actually, on looking a second more, we already have `framework.TestContext.OSDistro` which could be used by configuring a flag for the framework.

I don't think the e2e_node test sets that flag, but that would be the saner way to do that these changes (or use the os-release file to auto-populate it for node-e2e tests perhaps).

I'll open a new PR just to trim the old code and close this one pending discussion in the related issue.

**Pull request closed without merging**
