### PR TITLE
bump(github.com/fsouza/go-dockerclient) 25bc220b299845ae5489fd19bf89c5278864b050

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @derekwaynecarr ptal

**Comment by smarterclayton** [comment]
LGTM

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by bparees** [comment]
travis failure looks like a flake, can someone rerun it?

**Comment by eparis** [comment]
it's not a flake. it is the godep tool....

give me a minute.

**Comment by eparis** [comment]
when https://github.com/kubernetes/kubernetes/pull/20107 lands, you will likely need to rebase. You can go review that one to speed it along   :)

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by eparis** [comment]
My PR merged, can you rebase to clean up the travis failure?

**Comment by bparees** [comment]
@eparis done.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Pull request merged**
