### PR TITLE
Improvement on Kubectl CheatSheet base64 examples

### PR DESCRIPTION
**Pull request by caarlos0**
**What this PR does / why we need it**:

Little improvement on a kubectl cheat sheet example.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

`echo blah | base64` will actually result in the base64 of `blah\n`, which will usually not be intended by the user.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot bazel test this

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by cblecker** [comment]
@brendandburns looks like this one needs a manual merge due to https://github.com/kubernetes/kubernetes/pull/44621#issuecomment-294924252

**Comment by caarlos0** [comment]
ping?

**Comment by fejta** [comment]
Manually merging

**Comment by caarlos0** [comment]
@fejta thanks! =D

**Pull request merged**
