### PR TITLE
kubeadm: support patching kubeconfig files

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This patch supports applying patches over kubeadm generated kubeconfig files. It's useful for installers that need specific customizations not supported by kubeadm options.

For example, in a cluster created by kind, the server address in kubeconfig is the advertise address of the API server, but the Node IP may change after docker restarts. Replacing the server address with loopback address can make the cluster survive docker restart.

More discussion can be found at https://github.com/kubernetes-sigs/kind/pull/2671#issuecomment-1076715990

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
cc @BenTheElder @neolit123 @aojea

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: support applying patches over kubeadm generated kubeconfig files
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
> For example, in a cluster created by kind, the server address in kubeconfig is the advertise address of the API server, but the Node IP may change after docker restarts. Replacing the server address with loopback address can make the cluster survive docker restart.

is there any other use case that is not "use loopback as server for kubeconfig"?

**Comment by tnqn** [comment]
> > For example, in a cluster created by kind, the server address in kubeconfig is the advertise address of the API server, but the Node IP may change after docker restarts. Replacing the server address with loopback address can make the cluster survive docker restart.
> 
> is there any other use case that is not "use loopback as server for kubeconfig"?

Do you mean using 127.0.0.1/[::1] in kubeconfig for all use cases? The problem is other installers may not want to have loopback address as an alternative address of the certificate. For example, the default certificate generated by kubeadm doesn't have it, kind adds it for its own reason: https://github.com/kubernetes-sigs/kind/blob/dbcc39c6b8fb395863dc124fe74aca902ea7fef5/pkg/cluster/internal/kubeadm/config.go#L167-L171

**Comment by aojea** [comment]
> > > For example, in a cluster created by kind, the server address in kubeconfig is the advertise address of the API server, but the Node IP may change after docker restarts. Replacing the server address with loopback address can make the cluster survive docker restart.
> > 
> > 
> > is there any other use case that is not "use loopback as server for kubeconfig"?
> 
> Do you mean using 127.0.0.1/[::1] in kubeconfig for all use cases? The problem is other installers may not want to have loopback address as an alternative address of the certificate. For example, the default certificate generated by kubeadm doesn't have it, kind adds it for its own reason: https://github.com/kubernetes-sigs/kind/blob/dbcc39c6b8fb395863dc124fe74aca902ea7fef5/pkg/cluster/internal/kubeadm/config.go#L167-L171

I forget about the certificate, thanks

**Review by neolit123 — COMMENTED** [review]
@tnqn i went quickly trough the PR and i don't see major blockers.

However as mentioned earlier the design must be updated and approved.  KEPs are a verbose process but that is how bigger k8s changes are made. It helps us to avoid design mistakes.

Please PR this:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/1739-customization-with-patches

- possibly add a new doc section about kubeconfigs
- make the document generic for kubeadm generated files and not only static pods
- change document release targets and dates
- explain what happens with kubeconfig patches during upgrade
- explain that kubeadm kubeconfig phases must now process patches
- document the list of new patch targets
- add user stories

**Comment by tnqn** [comment]
Thanks @neolit123 for your guidance! will create a PR for that.

**Comment by neolit123** [comment]
@tnqn IIRC this is no longer needed in kind for the time being?

**Comment by tnqn** [comment]
> @tnqn IIRC this is no longer needed in kind for the time being?

Yes, the original issue has been resolved in another way. Please let me know if I should continue implementing this for other use cases or just close it.

**Comment by neolit123** [comment]
we should close this for now, since there is no other demand and code freeze is august 3rd.

**Pull request closed without merging**
