### PR TITLE
Refactored SeedProvider and Updated Docker

### PR DESCRIPTION
**Pull request by chrislovecnm**
This is a redo of the last PR that I munged 😄 
- fixed maven build folder structure
- updated build to C\* 3.4
- refactored Seed Provider - improved error handling, updated default SeedProvider code
- added start of unit tests.  Not as comprehensive as I would like
- updated docker image to debian:jessie
- installed openjdk 8
- added some docker fu to make the image smaller
- updated docker to C\* 3.4 and update yaml
- updated README content.  Added a section about the docker, and the SeedProvider

Have not had a chance to test the docker on k8s, because I do not have a local docker repo.

NOTE: someone needs to push the docker image into the google repo. Not sure what the process is ...  I will submit another PR request with changes to the yaml files.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
cc @kubernetes/examples 
cc @bgrant0607
cc @bprashanth

Monkeyed last PR, so here yah go

**Comment by chrislovecnm** [comment]
@bgrant0607 @brendandburns might I get a 'ok-to-merge'??

**Comment by brendandburns** [comment]
LGTM.  thanks

**Comment by brendandburns** [comment]
Once this is merged, ping me and I will push the new images.  (we should really automate that...)

**Comment by chrislovecnm** [comment]
@brendandburns will do. Want to test more other thing.

**Comment by chrislovecnm** [comment]
@brendandburns if you like u can push the docker, but I want to do some more testing next week. I changed A LOT of things. The example yaml and the readme are still referencing the current version, v8. I did that deliberately ;) I will submit another PR with some example tweaks.

Thanks

Chris

**Comment by pmdcosta** [comment]
@chrislovecnm Has there been any progress on this ? The V9 image hasn't been pushed yet, and even if I build it myself, the pods crash at startup.

**Comment by chrislovecnm** [comment]
V9 or v8? I need to test a couple of things in v9 as well.

Chris

**Comment by pmdcosta** [comment]
The current gcr.io/google-samples/cassandra:v8 image works fine, but Cassandra is still in v2.x.
I can build the image for V9 using your commit, but it crashes at startup.

**Comment by chrislovecnm** [comment]
@pmdcosta need more information on this.  Just did more smoke testing and it works like a champ for me locally. Please open another issue and let's get this more stable!!

**Pull request merged**
