### PR TITLE
test/e2e/network: mark tests in test/e2e/network/netpol/network_legacy.go with NetworkPolicyLegacy

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The new network policy e2e tests and the "legacy" network policy tests use the exact same test names and ginkgo filters, which means I have to run both of them at all times. This PR updates the ginkgo description for the legacy tests from NetworkPolicy to NetworkPolicyLegacy. This way a ginkgo focus of NetworkPolicy selects all tests, but adding a skip filter NetworkPolicyLegacy will skip the legacy tests only.  

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jayunit100** [comment]
sgtm, @danwinship is this cool with yall ? works for me !

**Comment by jayunit100** [comment]
@knabben @san

**Comment by andrewsykim** [comment]
Some NetworkPolicyLegacy test failed here https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102933/pull-kubernetes-e2e-ubuntu-gce-network-policies/1405310420356435968, which means the filter is working as expected :)

**Comment by aojea** [comment]
the ingress job passed, I didn't have time why is marked as failed
```
Ran 25 of 6401 Specs in 5465.489 seconds
SUCCESS! -- 25 Passed | 0 Failed | 0 Pending | 6376 Skipped
PASS
Ginkgo ran 1 suite in 1h31m7.66137326s
Test Suite Passed
```

SGTM, defer to Dan the final lgtm
/assign @danwinship

**Comment by danwinship** [comment]
/lgtm
(do we still need the legacy tests?)

**Comment by aojea** [comment]
> /lgtm
> (do we still need the legacy tests?)

at least ovn kubernetes ci in github was blowing up with the new tests.
I asked to keep them at least one release more in case anybody else has the same issue, also we have enough signal on the new tests from other CNIs.

I think that we can/must  remove them after this release giving people enough time and alternatives

**Pull request merged**
