### PR TITLE
transform into an efficient code

### PR DESCRIPTION
**Pull request by jjmengze**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
it seems that if we already know the length of envs []v1.EnvVar in container, use make to create map is more efficiently.

#### Which issue(s) this PR fixes:

`none`

#### Special notes for your reviewer:
`NONE`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by jjmengze** [comment]
@giuseppe cloud you please give this pr an ok to test ,thanks.

**Comment by ehashman** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Comment by jjmengze** [comment]
@ehashman thanks for your information, but it seems to me that is a too small problem to create an issue. 

When the number of environmental variables is quite large It would helpful .

If this pr needs an issue it is free contact to me, I will create it at any time.

**Pull request closed without merging**
