### PR TITLE
cleanup redundant testcases

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Thanks for the catch. Could you clean up this file thoroughly? There are some other duplications like:

- NodeResourcesMostAllocatedArgs resources empty (L382 and L405)
- ...

**Comment by chendave** [comment]
> Thanks for the catch. Could you clean up this file thoroughly? There are some other duplications like:

Done.

**Pull request merged**
