### PR TITLE
Fix raw extension openapi definition

### LINKED ISSUE #55890: Openapi generator and the RawExtension type
The Service Catalog includes the `RawExtension` type in `ServiceInstance.spec.parameters`. The openapi schema generated for it is wrong. It has two problems:
- it includes the `Raw` field, which is marked as required
- it doesn't allow additional properties to be included under it

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT
/kind bug

**What happened**:
If the Service Catalog openapi schema is exposed to kubectl (this currently requires a few tweaks and a patch), it reports validation errors when creating a ServiceInstance resource. 

**What you expected to happen**:
The schema should allow ServiceInstance.spec.parameters to include arbitrary properties and not require the `Raw` property to be included.

**How to reproduce it (as minimally and precisely as possible)**:
not easy at the moment (I'll add instructions later if I'm unable to fix this myself)

**Anything else we need to know?**:
I'd like to tackle this problem myself, but I need guidance. Should openapi-gen handle this automatically for all occurences of RawExtension, or should each field of type `RawExtension` be json-tagged individually? 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by jennybuckley**
**What type of PR is this?**
/kind bug
/sig api-machinery
/priority important-longterm

**What this PR does / why we need it**:
Changes the definition of RawExtension to this (adding `json:"-"`)
```
type RawExtension struct {
    ...
    Raw []byte `json:"-" protobuf:"bytes,1,opt,name=raw"`
    ...
}
```
I noticed that this removes Raw from the openapi defintion of it, making it just `type: object`, without changing how it is marshalled or unmarshalled (since we have custom functions for that). This fixes a known issue with the client side validation of RawExtension

**Which issue(s) this PR fixes**:
Fixes #55890

**Does this PR introduce a user-facing change?**:
```release-note
Fixed a bug with the openAPI definition for io.k8s.apimachinery.pkg.runtime.RawExtension, which previously required a field "raw" to be specified
```

### CODE REVIEW

**Comment by roycaihw** [comment]
/lgtm

This doesn't introduce any user-facing change in apiserver handling a request (besides the openapi spec itself is visible to user), but it will cause a few client-side change that are user-facing (kubectl and the openapi-generated clients won't require `raw` in a field of `RawExtension` type and/or error on unknown fields). Could you add a release note mentioning that the spec is fixed?

also please squash the first and the third commits

**Comment by jennybuckley** [comment]
/retest
@roycaihw I think this is ready now

**Comment by lavalamp** [comment]
nice find

/approve

**Pull request merged**
