### PR TITLE
Fixing master.yaml: Replacing <master-private-up> with $private_ipv4.

### PR DESCRIPTION
**Pull request by guoshimin**

### CODE REVIEW

**Comment by guoshimin** [comment]
Signed the license agreement.

**Comment by zmerlynn** [comment]
The actual GSGs reference this: https://github.com/GoogleCloudPlatform/kubernetes/blob/285a990cbe6538a32c87c835a8d32a44c9eb8ab1/docs/getting-started-guides/coreos/coreos_multinode_cluster.md and https://github.com/GoogleCloudPlatform/kubernetes/blob/6ff9e98fee2c3f15fd2167d613e65527c0daa7f3/docs/getting-started-guides/aws-coreos.md

**Comment by guoshimin** [comment]
This guide
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md
references
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml

**Comment by zmerlynn** [comment]
Sorry, I'll be clearer: My point was that you can't just change the yaml without changing the getting started guides that are referring to them.

**Comment by guoshimin** [comment]
coreos_multinode_cluster.md
<https://github.com/GoogleCloudPlatform/kubernetes/blob/285a990cbe6538a32c87c835a8d32a44c9eb8ab1/docs/getting-started-guides/coreos/coreos_multinode_cluster.md>,
as it stands, is already broken. My fix will make the guide work again.
aws-coreos.md
<https://github.com/GoogleCloudPlatform/kubernetes/blob/6ff9e98fee2c3f15fd2167d613e65527c0daa7f3/docs/getting-started-guides/aws-coreos.md>
does
not reference the master.yaml I'm changing. It references a different
master.yaml: kubernetes/docs/getting-started-guides/aws/cloud-configs/master.yaml

**Comment by zmerlynn** [comment]
Oh, you're right. Sorry, fast fingers.

LGTM

**Pull request merged**
