### PR TITLE
watchCache: Use for operation `&` instead of operation `%` to get better performance

### PR DESCRIPTION
**Pull request by novahe**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The idea comes from the java high-performance [arraydeque](http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/00cd9dc3c2b5/src/share/classes/java/util/ArrayDeque.java#l244) array. When using cyclic array, there will be a lot of `%` operations, and the use of `&` will have a better performance.

Here are performance comparison data：
```bash
goos: darwin
goarch: amd64
pkg: k8s.io/apiserver/pkg/storage/cacher
cpu: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
BenchmarkWatchCache_updateCache-4       79304628                13.04 ns/op
BenchmarkWatchCache_updateCacheOld-4    30225078                36.73 ns/op
PASS
ok      k8s.io/apiserver/pkg/storage/cacher     23.059s

```
`a%b` == `a&(b-1)` require: b=2^n,  so watchCache cyclic array capacity must be 2^n

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
 I modified a lot of test cases to adapt it, because of capacity must be 2^n.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
you should add an explanation about the change, why it improves the performance and how? ...

**Review by cndoit18 — COMMENTED** [review]
I'm also curious to have more explanations of how it improves performance.

**Comment by novahe** [comment]
> I'm also curious to have more explanations of how it improves performance.

use this bench to explain:
```go
func BenchmarkWithANDOperation(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = i & (128 - 1)
	}
}

func BenchmarkWithModuloOperation(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = i % 128
	}
}
```
Output: 
```bash
goos: darwin
goarch: amd64
pkg: github.com/halfrost/LeetCode-Go
cpu: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
BenchmarkWithANDOperation
BenchmarkWithANDOperation-4      	1000000000	         0.3679 ns/op
BenchmarkWithModuloOperation
BenchmarkWithModuloOperation-4   	1000000000	         0.3418 ns/op
PASS
```
But it doesn’t seem to look good, I will close this farce. : )

**Pull request closed without merging**
