### PR TITLE
Fix api description in swagger

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
　NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zjj2wry** [comment]
@deads2k the **pull-kubernetes-federation-e2e-gce** maybe failed recently? need i rebase latest master?

**Comment by deads2k** [comment]
> @deads2k the pull-kubernetes-federation-e2e-gce maybe failed recently? need i rebase latest master?

federation doesn't work well.  The status on it is ignored.

**Pull request merged**
