### PR TITLE
Add FAQ to extending api docs.

### PR DESCRIPTION
**Pull request by bprashanth**
Questions that came up working with people new to the code base and adding an experimental resource

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@bprashanth, thank you! But 1 and 3 will not be true after we have more API group support (#13707 etc). Could you add a line of notice there?

**Comment by caesarxuchao** [comment]
#13777 added the FAQ. Closing this one. Thank you @bprashanth.

**Comment by bprashanth** [comment]
@caesarxuchao I think we still need to surface the required --runtime-config option somewhere, people are getting stumped, or is that going away too?

**Comment by caesarxuchao** [comment]
@bprashanth I agree. How about adding a line here: https://github.com/kubernetes/kubernetes/blob/master/docs/admin/cluster-management.md#creating-and-configuring-a-cluster
Do you have better ideas? I can't find a better place in the docs. Thanks.

**Pull request closed without merging**
