### PR TITLE
[WIP] fix: scheduler v1beta3 doesn't append out-of-tree plugins correctly

### LINKED ISSUE #108083: scheduler v1beta3 pre-appends an out-of-tree plugin instead of append
### What happened?

Out-of-tree plugin typically composes its scheduler ComponentConfig like:

```yaml
profiles:
- plugins:
    preFilter:
      enabled:
      - name: Foo
    filter:
      enabled:
      - name: Foo
```

recently I found that when this is applied into the latest v1beta3 config, `Foo` is pre-appended to the finalized plugin list - i.e., `{preFilter|filter}.enabled = "Foo, <default in-tree plugins>"`.

### What did you expect to happen?

Same as the behavior of v1beta1 and v1beta2, out-of-tree plugin should be placed **at the end** of the finalized pluginList, i.e., preFilter.enabled = "<default plugins>, Foo".

### How can we reproduce it (as minimally and precisely as possible)?

A unit test gist https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808 is created to reproduce this issue.

After `git apply` this diff, run `go test ./cmd/kube-scheduler/app/...`:

```
--- FAIL: TestSetup (4.57s)
    --- FAIL: TestSetup/out-of-tree_component_configuration_v1beta3 (0.39s)
        server_test.go:551: Unexpected plugins diff (-want, +got):   map[string]*config.Plugins{
              	"default-scheduler": &{
              		QueueSort: {Enabled: {{Name: "PrioritySort"}}},
              		PreFilter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeAffinity"},
              				{Name: "NodePorts"},
              				... // 3 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		Filter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeUnschedulable"},
              				{Name: "NodeName"},
              				... // 11 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		PostFilter: {Enabled: {{Name: "DefaultPreemption"}}},
              		PreScore:   {Enabled: {{Name: "TaintToleration"}, {Name: "NodeAffinity"}, {Name: "PodTopologySpread"}, {Name: "InterPodAffinity"}}},
              		... // 7 identical fields
              	},
              }
FAIL
FAIL	k8s.io/kubernetes/cmd/kube-scheduler/app	4.977s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/config	[no test files]
ok  	k8s.io/kubernetes/cmd/kube-scheduler/app/options	0.698s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/testing	[no test files]
FAIL
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# master
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by miamipanther**
#### What type of PR is this?
/kind regression
/kind bug

#### What this PR does / why we need it:

After introducing multipoint in v1beta3, out-of-tree plugin is placed at the beginning instead of the end of finalized plugin list, this behavior is regression comparing to v1beta1 and v1beta2.  

#### Which issue(s) this PR fixes:

Fixes #108083

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
@miamipanther you need to sign the cla first. refer to this link https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#sign-the-cla for help.

**Comment by kerthcet** [comment]
CLA check failed for your commit username may be different from your cla used name. @miamipanther

**Comment by Huang-Wei** [comment]
/ok-to-test

Thanks @miamipanther . Could you add the testcases that can reproduce this issue in this PR? (https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808)

**Comment by miamipanther** [comment]
> /ok-to-test
> 
> Thanks @miamipanther . Could you add the testcases that can reproduce this issue in this PR? (https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808)

test case added @Huang-Wei

**Comment by miamipanther** [comment]
Investigating the test failure

**Comment by miamipanther** [comment]
As there is another PR to fix the issue #108083: https://github.com/kubernetes/kubernetes/pull/108613 Close this PR

**Pull request closed without merging**
