### PR TITLE
Remove copies of ObjectDiff function

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34775)

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]

**Comment by ivan4th** [comment]
(ping)
Can we merge this?..

**Comment by ivan4th** [comment]
(ping)

**Comment by lavalamp** [comment]
/lgtm

(sorry for delay, I've been out on paternity leave)

**Comment by ivan4th** [comment]
No problem, thanks!

**Comment by ivan4th** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
