### PR TITLE
[addon/storage-class] update storageclass groupversion in storage-class

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
[addon/storage-class] update storageclass groupversion in storage-class
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
/ok-to-test

I will approve once @saad-ali or a delegate from @kubernetes/sig-storage-pr-reviews approves.

**Comment by jsafrane** [comment]
/lgtm
from sig-storage

**Comment by zouyee** [comment]
Hi ,@roberthbailey would you like to approve it? thanks!

**Pull request merged**
