### PR TITLE
stop ticker

### PR DESCRIPTION
**Pull request by foxyriver**
**What this PR does / why we need it**:

stop ticker after using it

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@foxyriver 
there is a failing unit tests after this change:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/66262/pull-kubernetes-bazel-test/52907/

/kind cleanup
@kubernetes/sig-node-pr-reviews

**Comment by rphillips** [comment]
-1, startWatch() is an async go-routine function, so stopping the ticker in defer will prematurely stop the ticker.

**Comment by yujuhong** [comment]
> -1, startWatch() is an async go-routine function, so stopping the ticker in defer will prematurely stop the ti

Yep. The PR is not correct.

**Pull request closed without merging**
