### PR TITLE
upgrade rules_docker

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: Upgrades us to the current rules_docker release. we were on 0.7.0 (jan 2019_, rules_docker is on 0.14.4 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
Seems legit to me.
/lgtm
/approve
/hold lift at will

I've opened https://github.com/kubernetes/repo-infra/issues/207 to consider managing `rules_docker` in k/repo-infra.

**Comment by spiffxp** [comment]
/hold cancel
here we go

**Comment by justaugustus** [comment]
Fiddlesticks.
needs `./hack/update-bazel.sh`

**Comment by BenTheElder** [comment]
- hack/update-bazel.sh is bikeshedding format
- the other failure is a stale result. That job is still re-running
Will push autoformatting sigh.

**Comment by BenTheElder** [comment]
update-bazel should be happy with the additional blank line between rules now ...
(the previous formatting came from the rules_docker readme 🙄 )

**Comment by BenTheElder** [comment]
since this is not lgtm
/milestone v1.19
I think we want to ship this, in hopes that it deflakes image pulls, but I will defer judgement.
test-infra is on 0.14.1 (will send an update there too)

**Comment by BenTheElder** [comment]
Just some e2e pending now, otherwise green.

**Comment by BenTheElder** [comment]
test-infra matching here: https://github.com/kubernetes/test-infra/pull/18833

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
