### PR TITLE
remove function apply-encryption-config in configure-helper

### PR DESCRIPTION
**Pull request by zshihang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by shihan9** [comment]
trigger cla check.

**Comment by filbranden** [comment]
/unassign

I'd prefer if one of the other owners would be able to take a look at this one. Thanks!

**Pull request merged**
