### PR TITLE
Allow backendpools in Azure Load Balancers which are not owned by cloud provider

### LINKED ISSUE #36880: Azure Cloud Provider forbids custom backend pools and thus custom rules in Azure Load Balancer
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
azure load balancer
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Kind of both
**Kubernetes version** (use `kubectl version`): current master

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): Linux ma-k8s-0 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: custom Ansible+kubeadm
- **Others**:

**What happened**:
The Azure cloud provider complains with "loadbalancer is misconfigured with a different backend pool" when I add custom load balancer rules with separate backend pools through the Azure Portal or through Azure Resource Templates. I need to add these custom rules to expose the Kubernetes API endpoints. Adding a dedicated Azure Load Balancer just for the API is not possible, as otherwise I get error messages about Azure Load Balancer limitations (only one LB allowed per Availability Set)

**What you expected to happen**:
I would have expected that the Azure Cloud Provider just ignores existing backend pools.

**How to reproduce it** (as minimally and precisely as possible):
As described in "What happened"

**Anything else do we need to know**:
I created a fix for this and am currently testing this. I will create a PR in a few minutes when everything goes well.

I created this issue before finishing the PR because I wanted to discuss the reason behind this limitation?

### PR DESCRIPTION
**Pull request by codablock**
**What this PR does / why we need it**: It fixes #36880

**Which issue this PR fixes**: fixes #36880

**Special notes for your reviewer**:

**Release note**:
```release-note
Allow backendpools in Azure Load Balancers which are not owned by cloud provider
```

Instead of bailing out when we find another backend pool, we just ignore
other backend pools and add ours to the list of existing.

Fixes #36880

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36882)

### CODE REVIEW

**Comment by codablock** [comment]
CC @colemickens

**Comment by colemickens** [comment]
Thanks for the fix. Did you test it manually, and if so, how?

**Comment by codablock** [comment]
I tested this manually. I created a resource group from a template that also sets up an Azure Load Balancer with appropriate rules, probes and frontend/backend pools to load balance to my master nodes for the Kubernetes API port. The name of the load balancer matches the name that the cloud provider will later try to use.

Then I deploy Kubernetes to the VMs (Ansible+kubeadm) and wait for everything to properly start. When Kubernetes is ready, the cloud provider does not try anything with the Azure Load Balancers yet as there are no services of type LoadBalancer.

When I create a service of type LoadBalancer now, the cloud provider will skip creating the Azure Load Balancer as there is already one with the desired name. When it then tries to the backend pool to the LB, it immediately bails out with the error "loadbalancer is misconfigured with a different backend pool"

When this PR is applied, it does not bail out and everything seems to work as expected. My custom LB rules for the API and the LoadBalancer services work as expected.

Does this have a chance to land in 1.5?

**Comment by colemickens** [comment]
I need to test this with ACS-Engine to ensure everything works as expected, our configuration is different than what you've described. If it looks good we can ask about pulling it into 1.5 as a fix.

**Comment by colemickens** [comment]
This looks good and works for me. I'm assuming you setup the rules and tested deploying an actual LoadBalanced service... and I'm guessing that you have the master marked as unscheduleable? Can you confirm?

**Comment by codablock** [comment]
Yes I have setup the rules and tested an actual LoadBalanced service, both work fine together.

I'm currently not able to test it with the master marked as unschedulable due to me using kubeadm as written here: https://github.com/colemickens/azure-kubernetes-status/issues/11#issuecomment-260701416

**Comment by colemickens** [comment]
I've been told that [the new multi vip feature](https://azure.microsoft.com/en-us/documentation/articles/load-balancer-multivip-overview/) launched recently, [which we are using with DSR, which we now leverage to avoid using NodePort for Service trafffic](https://github.com/kubernetes/kubernetes/pull/36256) also enables you to have the master in multiple backends, as we discussed on Slack.

CC: @brendandburns as FYI.

**Comment by codablock** [comment]
What should I do about the release note label error from k8s-merge-robot? I added a release note to the PR description.

**Comment by colemickens** [comment]
@codablock Did you fix the `go fmt` issue? You need to go fmt the files you touched, otherwise the build will keep failing.

Pinging @brendandburns for removing the `release-note-label-needed` label, as well as for another approval for backport to 1.4.

**Comment by codablock** [comment]
Sorry, was not aware of go fmt. Executed it now and re-pushed.

**Comment by colemickens** [comment]
@k8s-bot cvm gke e2e test this

@k8s-bot bazel test this

**Comment by colemickens** [comment]
@k8s-bot gci gke e2e test this

**Comment by colemickens** [comment]
@k8s-bot gci gke e2e test this

**Comment by codablock** [comment]
@colemickens Anything I have to do about the do-not-merge/release-note-label-needed labels?

**Comment by colemickens** [comment]
@codablock You can add a release note if you want to expedite this process.

I think you probably want this cherry-picked into 1.5, but I'm guess it's probably too late. But when 1.5.1 is opened up, you can get it cherry-picked. (jessfraz is currently doing the cherry-picking for 1.4.x, not sure if that will still be true)

**Comment by colemickens** [comment]
@k8s-bot kops aws e2e test this

**Comment by codablock** [comment]
@colemickens I already added a release note in the initial PR description by using the PR template. I can not add release note labels by myself and did not find information on how to do this with the help of the bots.

I'm fine with having this only in 1.5.1. For 1.4., it depends on you and if acs-engine needs this.

**Comment by colemickens** [comment]
@k8s-bot kops aws e2e test this

**Comment by ixdy** [comment]
@kubernetes/contributor-experience how are reviewers who don't have write access supposed to set the release-note labels on PRs?

**Comment by ixdy** [comment]
@colemickens I think AWS is known-broken right now and doesn't block merges.

**Comment by foxish** [comment]
> @kubernetes/contributor-experience how are reviewers who don't have write access supposed to set the release-note labels on PRs?

@grod was working on a change to allow us to infer the release-note labels from the PR itself.

**Comment by foxish** [comment]
oops. @grodrigues3.

**Comment by colemickens** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
