### PR TITLE
Remove direct references to prometheus/testutil from kubelet/metrics

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup
/kind feature
**What this PR does / why we need it**:
To get [metrics stability](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md) into Beta, we will make it illegal to directly import prometheus methods in Kubernetes components.
Remove direct references to prometheus/testutil from kubelet/metrics

**Which issue(s) this PR fixes**:

Ref kubernetes/enhancements#1238

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Wow! This PR duplicated with mine https://github.com/kubernetes/kubernetes/pull/83713.

I introduced [testutils.CollectAndCompare](https://github.com/kubernetes/kubernetes/pull/83699) this morning and intended to rewrite the test case, not just simply migrate them. 

To avoid duplicate work, I can publish some tasks if you are interested. Is this ok?
Maybe you can go through https://github.com/kubernetes/kubernetes/pull/83062 first, I can publish tasks and provide some guidances.

**Comment by SataQiu** [comment]
Emmm........ This makes me unhappy :(
@RainbowMango
Can you create an open issue to hold all the releated works about metric refactor in k/k ?
I think it will speed things up.

**Pull request merged**
