### PR TITLE
Refine kubectl doc

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by bgrant0607** [comment]
kubectl.md is generated. These changes would need to be made in kubectl itself. It produces the help text that's dumped into kubectl.md.

/cc @jlowdermilk

**Comment by bgrant0607** [comment]
See also #4011

**Comment by jlowdermilk** [comment]
Making the help text uniform would be useful. You can find the source from which kubectl.md is generated under [pkg/kubectl/cmd](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/pkg/kubectl/cmd).

**Comment by kargakis** [comment]
Cool, I'll take a look in `kubectl`'s source code tomorrow.

**Comment by jlowdermilk** [comment]
FYI, this is being done in #4065. If you have no objections, let's close this one, and you can suggest changes there.

**Comment by kargakis** [comment]
@jlowdermilk sure thing, I will check that issue out then.

**Pull request closed without merging**
