### PR TITLE
Better help message for get and describe

### PR DESCRIPTION
**Pull request by hurf**
Follow up #11313
Add tips for shortcut ns and ep.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thank you @hurf. When I try `kubectl describe ep xxx`, it returns `error: no description has been implemented for "Endpoints"`. Other things seem fine.

**Comment by hurf** [comment]
Fixed, all commands are tested.

**Comment by caesarxuchao** [comment]
Thank you @hurf. So I see `describe` doesn't work for ComponentStatus either. LGTM.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Pull request merged**
