### PR TITLE
test images: Adds OWNERS files for images

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind documentation

/sig testing

**What this PR does / why we need it**:

Adds reviewers to the OWNERS files in the kubernetes/test/images folder. The reviewers are added automatically, based on their contributions on an image (>= 20% code churn).

Note that the code churn is taken into account for authors, and not committers.

I have excluded myself from a few of the images (``ipc-utils``, ``nonroot``). The code for those images is very small, and I've surpassed the 20% threshold just with cleanups / refactors.

Script used to generate the OWNERS files: https://paste.ubuntu.com/p/smspRYH7fT/

Script logs: https://paste.ubuntu.com/p/CgT53yKBjf/

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
I hope I didn't make any mistakes with the aliases. I am familiar with some of them, but not all.

Also, I was thinking that we could maybe add OWNERS for the agnhost subcommands, since those used to be the images that we've centralized into agnhost.

**Comment by claudiubelu** [comment]
It seems that not everyone is added to the organization. I've removed them for now. If they join, they can be readded.

**Review by fejta — COMMENTED** [review]
Is there a reason we don't have any approvers for these images?

**Comment by claudiubelu** [comment]
> 
> 
> Is there a reason we don't have any approvers for these images?

I didn't add any because I don't know what are the criteria for someone to become an approver in the Kubernetes community, especially since they are the ones that will get to merge the PRs. For reviewers is simple: you want people that know that particular codebase to say if it's ok or not.

Anyways, I can easily add the same people to the approvers category too, if you want me to.

**Comment by fejta** [comment]
* Sure, just change reviewers to approvers
* The people being added as approvers should approve becoming approvers
  - For this reason I'd recommend separating this out into different PRs
  - and/or moving nautilus, kitten, agnhost into #89152 as they'll need to review it anyway
* Packages should have multiple approvers

**Comment by claudiubelu** [comment]
> 
> 
>     * Sure, just change reviewers to approvers
> 
>     * The people being added as approvers should approve becoming approvers
>       
>       * For this reason I'd recommend separating this out into different PRs
>       * and/or moving nautilus, kitten, agnhost into #89152 as they'll need to review it anyway
> 
>     * Packages should have multiple approvers

I've split the OWNERS as follows:
- #89152: agnhost, busybox, kitten, nautilus
- #90166: apparmor-loader, echoserver, jessie-dnsutils, metadata-concealment, sample-apiserver
- #90167  cuda-vector-add, nonewprivs, pets, redis, volume
- this, the rest.

@filbranden @johnSchnake @balajismaniam @tallclair @anfernee @jszczepkowski @vikaschoudhary16 Please give your ok that you are willing to be the approvers for these images.

**Comment by filbranden** [comment]
@claudiubelu I haven't really been involved in Kubernetes projects in a while, so I don't think you should include me in an OWNERS file here.

**Comment by vikaschoudhary16** [comment]
@claudiubelu I haven't really been involved in Kubernetes projects in a while, so I don't think you should include me in an OWNERS file here.

**Review by fejta — COMMENTED** [review]
/assign @johnSchnake @balajismaniam @tallclair @anfernee @jszczepkowski

**Review by anfernee — APPROVED** [review]

**Comment by tallclair** [comment]
/lgtm
/approve
For the nonroot image
/hold

**Comment by dims** [comment]
@tallclair what do we need to do to remove the hold on this?

**Comment by claudiubelu** [comment]
Not everyone agreed to become an OWNER. We still need to hear from @johnSchnake, @balajismaniam, @jszczepkowski . If we don't hear from them until... I don't know, next week? We should remove them. :)

**Pull request merged**
