### PR TITLE
Ignore first SIGINT in node-e2e tests

### PR DESCRIPTION
**Pull request by odinuge**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Node e2e tests exceeding the global timeout are sent SIGINT, resulting
in no artifacts or console output. This will ignore the first SIGINT,
and since all children processes are being stopped due to SIGINT, we can
clean up before exiting.

SIGINT is sent here: https://github.com/kubernetes/test-infra/blob/master/kubetest/process/process.go#L195-L206

#### Which issue(s) this PR fixes:

Fixes #

xref: #102148

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by odinuge** [comment]
Optimally we should not use the same timeout for the global execution and the ginkgo test, to make sure everything works smoother. This will however mitigate the biggest issue when we get no signal about what is wrong.

**Comment by odinuge** [comment]
/retest

flake

**Comment by fromanirh** [comment]
Added a minor request here: https://github.com/kubernetes/kubernetes/issues/102148#issuecomment-846371618 - if we can improve easily I'd try to do it, otherwise if this possible improvemente requires too much work, let's go ahead with this change.

**Comment by fromanirh** [comment]
/hold
to let other reviewer chime in, feel free to remove

**Comment by fromanirh** [comment]
/lgtm
for reasons discussed here: https://github.com/kubernetes/kubernetes/issues/102148#issuecomment-846373334

**Comment by harche** [comment]
@odinuge @giuseppe I noticed similar crash in cgroup v2 related tests in my local testing too.

**Comment by odinuge** [comment]
> @odinuge @giuseppe I noticed similar crash in cgroup v2 related tests in my local testing too.

Ahh, nice! The new tests help surface issues with the systemd cgroup driver both on cgroup v1 and v2. :tada:

**Comment by odinuge** [comment]
Well, the more I deal with systemd and cgroup stuff, the more I think it would be a better approach to just use a systemd slice for `kubepods.slice`, and just set `Delegate=true` and do what we want underneath. It is another discussion ofc., but the current solution has quite a few bugs and issues, and a lot of stuff has to be done at least twice in order to "hope" for the best. This is especially true for cgroup v2.... :/

I do _love_ systemd and how it deals with cgroups, so that is not the issue. It is just that the complexity with k8s' qos handling and multiple cgroups etc. that makes it so hard to properly handle all the edge cases.

**Comment by BenTheElder** [comment]
I'm not sure that there will always be two of these (e.g. bootstrap.py + kubetest vs decorate: true + kubetest2, versus local usage...) and don't have a lot of time to look at this currently 😅

**Comment by odinuge** [comment]
Hmm. No output at all from `pull-kubernetes-node-kubelet-serial`... Strange.

/test pull-kubernetes-node-kubelet-serial

**Comment by odinuge** [comment]
As seen in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102209/pull-kubernetes-node-kubelet-serial/1402658877538832384/, the node_e2e jobs will now properly print the test output and dump artifacts in case of a timeout. So this works as expected!

cc @ehashman @fromanirh

**Comment by fromanirh** [comment]
will review again this PR shortly

**Comment by odinuge** [comment]
Thanks @dims!

/hold cancel

**Pull request merged**
