### PR TITLE
Fix typo in admission webhook

### PR DESCRIPTION
**Pull request by arghya88**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

Fixes typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by arghya88** [comment]
@thockin Can you please review this.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
/ok-to-test

**Pull request merged**
