### PR TITLE
clean up pkg/apis/meta/v1/time.go

### PR DESCRIPTION
**Pull request by CaoShuFeng**
This file has been moved to staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go

**Release note**:
```
NONE
```
/assign @sttts

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
/assign @lavalamp 
For approve.

**Comment by CaoShuFeng** [comment]
rebased

**Comment by sttts** [comment]
@smarterclayton is this approved?

**Comment by sttts** [comment]
@smarterclayton approved?

**Pull request merged**
