### PR TITLE
fix race condition when attach azure disk in vmss

### LINKED ISSUE #71991: race condition when attach/detach azure disk in vmss
**What happened**:
When attach/detach azure disk in vmss, it updates whole VM info, including: networkProfile, storageProfile, while this would lead to race condition when there is also network related setting changing in k8s cloud provider.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/update

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig azure
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
When attach/detach azure disk in vmss, it updates whole VM info, including: `networkProfile`, `storageProfile`, while this would lead to race condition when there is also network related setting changing in k8s cloud provider in the mean time.
This PR fixed this issue by using a new vm data and only updates `storageProfile` related info.

Related RESET api doc could be found here:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/update

**Which issue(s) this PR fixes**:

Fixes #71991

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
none
```

**Release note**:
```
fix race condition when attach azure disk in vmss
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig azure

cc @brendandburns @khenidak 

By my testing, it works well in disk attach/detach, while let me hold for a while, check with vmss team first. Thanks.
/hold

### CODE REVIEW

**Comment by andyzhangx** [comment]
@feiskyer

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
