### PR TITLE
Cleanup #11029 to use go autocast-after-type-switch

### PR DESCRIPTION
**Pull request by justinsb**
(thanks to brendandburns for the suggestion)

### CODE REVIEW

**Comment by mikedanese** [comment]
This isn't compiling.

**Comment by justinsb** [comment]
Sorry; pushed a bad version and then pushed but forgot to force-push.  Totally my fail.

Repushed.

**Comment by justinsb** [comment]
Looks like a flake

@k8s-bot test this please

**Comment by mikedanese** [comment]
LGTM

**Pull request merged**
