### PR TITLE
Spaces don't work in e2e regex's.  Doh!

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@alex-mohr All of the test failures in this PR are a result of
https://github.com/kubernetes/kubernetes/pull/13697#issuecomment-141262005
which breaks the build.

Tests need to be rerun once that's resolved.

**Comment by alex-mohr** [comment]
@k8s-bot test this please (mea culpa, but breakage fixed)

**Comment by quinton-hoole** [comment]
@alex-mohr You might want to merge this one manually, seeing as until it goes in, all auto-merges are going to proceed without any e2e tests whatsoever, which is really really bad :-)

**Comment by alex-mohr** [comment]
yeah, thanks quinton.  I'll go regen all tests for pending prs.

**Pull request merged**
