### PR TITLE
Remove glusterfs support.

### LINKED ISSUE #35557: Question: Can vendor LGPL3 Go code be included?
In our [GlusterFS storage manager](https://github.com/heketi/heketi) we are contemplating changing our license from Apache 2 to LPGL 3.

Currently this code is used in the [vendor/...](https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/heketi/heketi) for the storage dynamic provisioner of GlusterFS.  Would there be any conflicts if we change license?

I also noticed that the [Yaml](https://github.com/kubernetes/kubernetes/blob/master/vendor/gopkg.in/yaml.v2/README.md) code is currently using a LGPL3 with a clause to allow static linking, although they changed their license in their [repo to Apache 2](https://github.com/go-yaml/yaml/commits/v2/LICENSE).

### LINKED ISSUE #70802: Update heketi dependency after licensing issues are fixed
Please see discussion in:
- https://github.com/heketi/heketi/issues/1279
- https://github.com/kubernetes/kubernetes/issues/35557#issuecomment-436973405

Once things are fixed we need to update k/k with latest from heketi repo

Alternative : Drop GlusterFS in-tree plugin

### PR DESCRIPTION
**Pull request by thockin**
Because of licensing issues, we can not ship glusterfs support.

**What type of PR is this?**

/kind feature

Fixes #70802
Fixes #35557

```release-note
Glusterfs volumes are no longer supported.  Users of glusterfs in Kubernetes should not upgrade until these issues are resolved.
```

### CODE REVIEW

**Comment by thockin** [comment]
I hope to heck we don't need to do this.

**Comment by thockin** [comment]
@childsb @saad-ali @humblec @kubernetes/sig-architecture-pr-reviews

**Comment by dims** [comment]
@thockin hope we don't need it. but we need to remove the heketi files too.

**Comment by thockin** [comment]
oh, yeah, duh.  Will update if we have to go there.  Simple enough

**Comment by humblec** [comment]
>Glusterfs volumes are no longer supported.  Users of glusterfs in Kubernetes should not upgrade until these issues are resolved.>

Oh.. No!!! It is such a terrifying ordeal. :( 

 >oh, yeah, duh. Will update if we have to go there. Simple enough
I hope you dont have to update this PR any more , in the worst case scenario, we need glusterfs_test.go and other api references to be taken out :((

**Comment by obnoxxx** [comment]
After the prep work had been done the final relicensing PR for heketi is now up: https://github.com/heketi/heketi/pull/1419. It should get merged later today. 

I would really appreciate if this one here could not get merged, since we're resolving the issue. :-)

**Comment by thockin** [comment]
Happy to kill this one.  Thanks @obnoxxx and everyone for getting over the finish line.

**Pull request closed without merging**
