### PR TITLE
Bumped Heapster to v1.4.0-beta.0

### PR DESCRIPTION
**Pull request by piosz**
Heapster release candidate for Kubernetes 1.7

cc @dchen1107 @caesarxuchao

### CODE REVIEW

**Comment by dchen1107** [comment]
@piosz  Can we have the release note for this heapster upgrade? Any new features or bug fixes for this upgrade?

**Comment by piosz** [comment]
@caesarxuchao it's not a flake but some real problem with influxdb

**Comment by piosz** [comment]
The problem is with missing labels we removed in this Heapster release (https://github.com/kubernetes/heapster/issues/1654). I made a fix.

**Comment by DirectXMan12** [comment]
LGTM once it passes tests

**Comment by DirectXMan12** [comment]
I'm honestly a little surprised that we run Influx queries in the Kubernetes e2e tests.  Testing that data gets correctly to a Heapster sink should be the job of the Heapster e2es.  Nothing in Kubernetes should be talking directly to Influx (yes, I know that InitialResources talks directly to Influx.  If that's not already deprecated, it should be).

**Comment by DirectXMan12** [comment]
ping @marun can you approve?

**Pull request merged**
