### PR TITLE
Remove defined error

### PR DESCRIPTION
**Pull request by yiqinguo**
This line can be remove,the err has been defined above.

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Review by resouer — COMMENTED** [review]
Remember to add release note: NONE next time, so you will not get release not required label

**Comment by yiqinguo** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
/assign @dchen1107
for approval

**Comment by yiqinguo** [comment]
/test pull-kubernetes-federation-e2e-gce
--

**Comment by cblecker** [comment]
/assign @dchen1107 
for approval

**Comment by cblecker** [comment]
ping @dchen1107 for approval

**Comment by resouer** [comment]
ping @Random-Liu for a approve, it's a minor fix and been lgtm

**Pull request closed without merging**
