### PR TITLE
Added exporting autoscaling metrics in Heapster config

### PR DESCRIPTION
**Pull request by piosz**
Addresses #11748

@vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM. @piosz we should consider adding an e2e test to ensure that the GCM backend works and has the necessary data.

**Comment by piosz** [comment]
There is already implemented (not yet enabled since this PR is prerequisite for it) autoscaling e2e test #11685 which indirectly test those metrics. Also once #11570 is done @socaa can implement it.

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Don't you need to update the version of the addon when you change its config so the addon-controller will pick up the change on upgrade?

**Comment by piosz** [comment]
@alex-mohr good point. Will change the version to make sure #12098 can be updated.

**Pull request merged**
