### PR TITLE
Move planner to federation utils

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @quinton-hoole @jianhuiz

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34470)

### CODE REVIEW

**Comment by mwielgus** [comment]
@k8s-bot e2e test this

**Comment by quinton-hoole** [comment]
Yes, LGTM.  Apologies for the delay.

**Comment by mwielgus** [comment]
@k8s-bot gce e2e test this

**Comment by mwielgus** [comment]
@k8s-bot gce e2e test this

**Comment by mwielgus** [comment]
@k8s-bot e2e test this

**Comment by mwielgus** [comment]
@k8s-bot gce e2e test this

**Comment by mwielgus** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
@k8s-bot unit test this issue #34601

**Comment by mwielgus** [comment]
@k8s-bot unit test this issue #34601

**Comment by mwielgus** [comment]
@k8s-bot unit test this issue #34601

**Pull request merged**
