### PR TITLE
Add release api in device plugin

### LINKED ISSUE #86539: No Device Plugin Callback for Releasing devices against Allocate
**What would you like to be added**:

Device Plugin Callback to release(dis-allocation) the hardware or devices at the finalization of pods.

**Why is this needed**:

Currently the following simple API are ready for Device Plugin,
https://github.com/kubernetes/kubernetes/blob/92e0de32698864f4dce876d79e80386261e3e18c/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.proto#L48-L67

but device and hardware, platform acceleration getting complicated including edge A.I and pre-process for sensing data. in generally, if allocation is required to bind the hardware to pods, there could also be release(dis-allocation) callback which will take care of device specific finalization when pods exit.

**Note**:

I am not so sure where I could start this discussion(or already discussion is in progress or done), if this is not the place, tell me where I could tag this issue. thanks in advance and appreciated.

### PR DESCRIPTION
**Pull request by yechenglin007**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:

Device Plugin Callback to release(dis-allocation) the hardware or devices at the finalization of pods.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/86539#L52

**Special notes for your reviewer**:

since this PR add a new API, it also should update https://github.com/kubernetes/kubelet/tree/master/pkg/apis/deviceplugin/v1beta1 files if merged.

**Does this PR introduce a user-facing change?**:

```release-note
- Rlease() API should be used in k8s-device-plugin for user, it will back uuid to vendor when a pod exit.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

Release() API should be updated in following doc,

- Usage doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md

### CODE REVIEW

**Comment by fujitatomoya** [comment]
related to https://github.com/kubernetes/kubernetes/issues/86539

**Review by mattjmcnaughton — COMMENTED** [review]
cc @klueska @jiayingz 

Tagging some folks who I think might have a better context for this review :)

/ok-to-test
/uncc

**Comment by klueska** [comment]
Was this addition to the API ever discussed in one of the sig-node meetings? I don't recall any discussion of it. Also, you mention that the `k8-device-plugin` requires this functionality in order to work as expected. Are you referring to the NVIDIA `k8-device-plugin`? I'm fairly familiar with this plugin and not sure what you are expecting for it to do in this new `Release()` call. From the NVIDIA container stack point of view, no cleanup of the GPUs is necessary.

**Comment by jiayingz** [comment]
+1 to discuss this on sig-node first.

**Comment by yechenglin007** [comment]
> Was this addition to the API ever discussed in one of the sig-node meetings? I don't recall any discussion of it.
> 
> Also, you mention that the `k8-device-plugin` requires this functionality in order to work as expected. Are you referring to the NVIDIA `k8-device-plugin`? I'm fairly familiar with this plugin and not sure what you are expecting for it to do in this new `Release()` call. From the NVIDIA container stack point of view, no cleanup of the GPUs is necessary.

sorry for not discuss in sig-node meeting, i will have a discussion on slack #sig-node 

you are right, for current NVIDIA `k8s-device-plugin` cases, no cleanup of the GPUs is necessary. but for general API, i think Allocate()/Release() should be paired, also for more complex case, for example, NVIDIA/INTEL/AMD `k8s-device-plugin` allocate a GPU to a pod, even if this pod exit, NVIDIA/INTEL/AMD `k8s-device-plugin` still think that this GPU is busy, since there is no `GPU is free now` signal to NVIDIA/INTEL/AMD `k8s-device-plugin`, so that NVIDIA/INTEL/AMD `k8s-device-plugin` can not do else tasks of this GPU by itself in future, since it don't know if this GPU is free now.

thanks

**Comment by klueska** [comment]
Given the long discussion in https://github.com/kubernetes/kubernetes/pull/87223, I'm hesitant to approve this PR until all of the concerns raised in the thread have been addressed and the interested parties agree on the approach.

**Comment by mewais** [comment]
It might not be necessary for GPUs to clean up after they are released from pods, but that does not mean this is the universal case. Consider FPGAs for example, if you don't clean up the FPGA after the pod releases it, whatever is programmed on it will keep working, potentially filling up the network with useless traffic and wasting power for no reason. On a large scale this can be really bad.

Is there any update on this? Or about the concerns in #59110 being addressed?

/remove-lifecycle stale

**Comment by fujitatomoya** [comment]
@mewais 

> It might not be necessary for GPUs to clean up after they are released from pods,

NO, GPU is no problem with current interface.

> but that does not mean this is the universal case.

This is our focus and use case.

> Is there any update on this? Or about the concerns in #59110 being addressed?

so far, no update. you might want to take a look at https://github.com/kubernetes/kubernetes/issues/86539, there is some consideration about Container Device Interfaces. but i do not see any actual activity on that. Anybody happens to know?

**Comment by mewais** [comment]
A new PR also addresses this: https://github.com/kubernetes/kubernetes/pull/91190

**Comment by fujitatomoya** [comment]
@yechenglin007 

friendly ping.

**Comment by yechenglin007** [comment]
> @yechenglin007
> 
> friendly ping.

i will

**Comment by ehashman** [comment]
Hi @yechenglin007, thanks for this contribution! Since this PR is not mergeable in its current state, I'm going to close it. Please feel free to reopen it when you've had a chance to take another look.

/close

**Pull request closed without merging**
