### PR TITLE
Change log:Fix Spelling error about [occuring]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Change log:Fix Spelling error about [occuring]

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by heqg** [comment]
> /lgtm

Can you help to leaves an  /ok-to-test ? 
thks。

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by heqg** [comment]
> /lgtm



> /lgtm


hi @hasheddan
Sorry, I did not find your email address, so I left a message here.

I am heqg.
Recnetly. I want to apply for a member in commmunity, I hope to get your sponsorship.

Since a year ago, I have been engaged in kubenetes related work. For example: Deployment and O&M of k8s
Besides, I want to make my own contributions to the community, and also to improve my abilities.

I know that my capabilities still need to be improved. But, I am sure that I can do better in future.

If you agree, I will submit an application for issus and expect to get your reply + 1.

Looking forward to get your sponsorship.and Hope you to give me a chance.

Thank you very much. Thanks again.

**Pull request merged**
