### PR TITLE
add myself to build and test approvers

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by ixdy** [comment]
what's the policy around adding yourself to approvers but not reviewers?

**Comment by mikedanese** [comment]
Not sure. Who would know?

**Comment by ixdy** [comment]
@apelisse @grodrigues3 https://github.com/kubernetes/kubernetes/pull/40752#issuecomment-276467612

**Comment by mikedanese** [comment]
I'm a reviewer in 60 packages already, I thought approvers was intended to spread review load. I have done enough work in both test/ and build/ to approve mine and others changes but I'd rather not take more review load.

**Comment by mikedanese** [comment]
https://k8s-gubernator.appspot.com/pr/mikedanese

**Comment by ixdy** [comment]
fair enough. /lgtm

**Pull request merged**
