### PR TITLE
Add aggregation labels reconciliation to rbac helpers

### PR DESCRIPTION
**Pull request by nanorobocop**
#### What this PR does / why we need it:

Currently, during Role/ClusterRole reconciliation inside `k8s.io/component-helpers/auth/rbac/`, all labels are left in place, including role aggregation labels.
It means, if new role has less aggregation labels, the resulting role would have old aggregation labels as well.
As a result, aggregation role would have extra permissions because of extra aggregation labels.
This PR introduces AggrLabelPrefixes field for ReconcileRoleOptions in order to reconcile aggregation labels as well.

#### Which issue(s) this PR fixes:

Fixes # no

#### Special notes for your reviewer:

Existing tests passed.
Added new tests for AggrLabelPrefixes logic. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by nanorobocop** [comment]
Hi @enj, @mikedanese, could you please help to check this PR?

**Comment by nanorobocop** [comment]
Hi @enj, @mikedanese, could you please help to check this PR?

**Comment by enj** [comment]
/remove-lifecycle rotten
/triage accepted
/assign @deads2k @enj

It has been a loooong time since I read any of this code.  Will try to take a look in 2022.

**Comment by dims** [comment]
@enj it's 2022! Happy New Year!

**Comment by dims** [comment]
This PR has needs a kind/ label. Please pick one from https://github.com/kubernetes/kubernetes/labels?q=kind and apply it. Please see https://prow.k8s.io/command-help on how to use the bot to apply labels

**Comment by nanorobocop** [comment]
@dims Sorry, I missed your message before. 
Set kind as feature, since I don't have particular bug scenario.

**Pull request closed without merging**
