### PR TITLE
Fix staticcheck failures on apiserver/plugin/pkg/{authenticator, auth…

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
…orizer}

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix staticcheck failures on apiserver/plugin/pkg/{authenticator, authorizer}

Errors reported by staticchecker:
```
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go:133:2: field now is unused (U1000)
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/certs_test.go:22:5: var caKey is unused (U1000)
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/certs_test.go:70:5: var badCAKey is unused (U1000)
vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/certs_test.go:22:5: var caKey is unused (U1000)
vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/certs_test.go:70:5: var badCAKey is unused (U1000)
```

**Which issue(s) this PR fixes**:
Part of #92402

**Special notes for your reviewer**:
I also see a bunch of statckerrors on `test/e2e_node/*`, which are not listed in [hack/.staticcheck_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures). Those errors are not fixed in this PR.

**Does this PR introduce a user-facing change?**:
```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Many prs failing with this message. Let’s retest tomorrow

**Comment by ruiwen-zhao** [comment]
From the log of the failed pull-kubernetes-bazel-build, it looks like a timeout: `Process did not finish before 2h0m0s timeout`.  It does not seem to be relevant of this PR, so going to retest it to give it another shot.

**Comment by SergeyKanzhelev** [comment]
/lgtm
/priority backlog
/assign @dims 
/assign @dchen1107 

(@dims, just for hack/)

**Comment by dims** [comment]
/approve 
(for hack/)

**Pull request merged**
