### PR TITLE
Fix flake in quota integration test

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/kubernetes/kubernetes/issues/41885

### CODE REVIEW

**Comment by deads2k** [comment]
@gmarek @wojtek-t @k8s-oncall this fixes a prevalent flake.  I think its worth a manual merge on green.

**Comment by deads2k** [comment]
@k8s-bot cvm gce e2e test this: issue #41902

**Comment by derekwaynecarr** [comment]
@k8s-bot verify test this

**Pull request merged**
