### PR TITLE
WIP: Manage container termination in a non-blocking manner

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #121398 

TODOs
- [ ] fix e2e tests of https://github.com/kubernetes/kubernetes/pull/124086/files
- [x] fix `Should transition to Failed phase a pod which is deleted while pending`

This manages container termination in a non-blocking way.
xref:
- https://github.com/kubernetes/kubernetes/pull/121412
- https://github.com/kubernetes/enhancements/issues/4438
- https://github.com/kubernetes/enhancements/issues/753

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/uncc all

### CODE REVIEW

**Comment by dims** [comment]
/close

please reopen if needed

**Comment by gjkim42** [comment]
/open

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4438-container-restart-termination

I'll try to work on this in v1.31.

**Pull request closed without merging**
