### PR TITLE
Default lockfile to empty string while alpha

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Let's revisit the default when its no longer marked alpha.
Fixes: https://github.com/kubernetes/kubernetes/issues/21078
/cc @vishh @mikedanese

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
see https://github.com/kubernetes/kubernetes/issues/21078

@liggitt

**Comment by vishh** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot e2e test this please. Flake: #21094

**Comment by mikedanese** [comment]
Ok, I definitely did link the issue... @eparis @lavalamp why did k8s-bot delete my comment?

**Comment by mikedanese** [comment]
slightly annoying that it deletes the comment...  but regex should be more lenient.

image

**Comment by eparis** [comment]
Delete is the only way it doesn't spam you every 10 minutes...

Capital `F` in `Flake` breaking the regex?

The regex should probably also take a URL instead of the `#number` version...

**Pull request merged**
