### PR TITLE
Add foreground deletion check to ensure GC is aware of the new custom type

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Adds a check to ensure GC is aware of our new resource type before waiting on the dependent to be cleaned up

**Which issue(s) this PR fixes**:
xref  #87473

```release-note
NONE
```

/cc @lavalamp @caesarxuchao 
/sig api-machinery

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/retest

this certainly helps eliminate some test failures, but it probably won't fix the [case](https://github.com/kubernetes/kubernetes/issues/87473#issuecomment-577888478) I encountered.

**Comment by liggitt** [comment]
> this certainly helps eliminate some test failures, but it probably won't fix the [case](https://github.com/kubernetes/kubernetes/issues/87473#issuecomment-577888478) I encountered.

That is why I didn't want to touch the order or type of deletion of the existing owner/dependent objects. My hope is that this will reduce the noise caused by laggy GC but still exercise the problem you observed.

**Comment by lavalamp** [comment]
/lgtm

Good idea.

**Comment by liggitt** [comment]
Something is resource-constraining our test machines… seeing lots of timeouts on tests that passed reliably before 

/retest

**Comment by liggitt** [comment]
Runc flake
/retest

**Pull request merged**
