### PR TITLE
fix indentation with 'kubectl describe node'

### PR DESCRIPTION
**Pull request by sallyom**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fixes indentation of `kubectl describe node`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sallyom** [comment]
with PR:
```console
$ kubectl describe node ip-10-0-134-66.us-east-2.compute.internal
-------------
Addresses:
  InternalIP:   10.0.134.66
  InternalDNS:  ip-10-0-134-66.us-east-2.compute.internal
  Hostname:     ip-10-0-134-66.us-east-2.compute.internal
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         2
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      8162888Ki
  pods:                        250
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         1500m
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7548488Ki
  pods:                        250
System Info:
  Machine ID:                             blah
  System UUID:                            blah
  Boot ID:                                blah
  Kernel Version:                         blah
  OS Image:                               blah
  Operating System:                       linux
  Architecture:                           amd64
  Container Runtime Version:              cri-o://blah
  Kubelet Version:                        blah
  Kube-Proxy Version:                     blah
```
Without fix:
```console
$ kubectl describe node ip-10-0-134-66.us-east-2.compute.internal
-------------
Addresses:
  InternalIP:   10.0.134.66
  InternalDNS:  ip-10-0-134-66.us-east-2.compute.internal
  Hostname:     ip-10-0-134-66.us-east-2.compute.internal
Capacity:
 attachable-volumes-aws-ebs:  39
 cpu:                         2
 hugepages-1Gi:               0
 hugepages-2Mi:               0
 memory:                      8162888Ki
 pods:                        250
Allocatable:
 attachable-volumes-aws-ebs:  39
 cpu:                         1500m
 hugepages-1Gi:               0
 hugepages-2Mi:               0
 memory:                      7548488Ki
 pods:                        250
System Info:
 Machine ID:                              blah
 System UUID:                             blah
 Boot ID:                                 blah
 Kernel Version:                          blah
 OS Image:                                blah
 Operating System:                        linux
 Architecture:                            amd64
 Container Runtime Version:               cri-o://blah
 Kubelet Version:                         blah
 Kube-Proxy Version:                      blah
```

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
