### PR TITLE
Fixed incorrect service name

### PR DESCRIPTION
**Pull request by eghobo**

### CODE REVIEW

**Comment by ashcrow** [comment]
@eghobo can you double check the user you used to commit with and verify it has the proper CLA?

Otherwise, looks good to me.

**Comment by eghobo** [comment]
@ashcrow: I did (actually I signed CLA for all my github emails ;)). It's strange because previous commit went through.

**Comment by ashcrow** [comment]
@eghobo ha! @googlebot came through after the comment :smile:.

@smarterclayton this is an extra small typo fix that looks good to me.

**Comment by derekwaynecarr** [comment]
LGTM

**Pull request merged**
