### PR TITLE
Remove dead code from the controlplane instance

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup

Remove dead code from the controlplane instance

I can't find any usage of `nodeAddressProvider` on the repo, seems this comes from the `installTunneler` era by checking the `git history`

```release-note
NONE
```

### CODE REVIEW

**Comment by SRI0000000** [comment]
Hi guys, I am new to this field and I really wanna contribute. But **I don't know even where to start**. I have some knowledge in C and Java. Can anyone please help and guide me?

**Comment by aojea** [comment]
/retest

seems unrelated `TestDifferentWidths`
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111945/pull-kubernetes-unit/1562912745068695552

cc @MikeSpreitzer , I think you have some history with this test :smile:

**Pull request merged**
