### PR TITLE
fix the typo in the v1alpha3 doc.go

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
fixing reference controlManangerExtraArgs in the v1alpha3 doc.go.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubeadm/issues/1178

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@neolit123 PTAL. Thanks

**Comment by neolit123** [comment]
thank you @yuexiao-wang 
sorry but i realized that the other PR will be sufficient...

once we merge it, clicking "refresh now" at the bottom of this page:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

will update the godocs page as it uses the "master" branch.
the release-1.12 branch will remain incorrect, but that's not critical.

thanks and sorry again.
/close

**Comment by yuexiao-wang** [comment]
ok

**Comment by yuexiao-wang** [comment]
It is updated for the page:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

**Comment by neolit123** [comment]
yes, i refreshed it.
thanks @yuexiao-wang

**Pull request closed without merging**
