### PR TITLE
enable deployment and daemonset in gce upgrade tests

### PR DESCRIPTION
**Pull request by mikedanese**
No more experimental

ref #14674

### CODE REVIEW

**Comment by ihmccreery** [comment]
Is there a way we can do this without updating every single config, (e.g. what we do with flaky tests)?

**Comment by mikedanese** [comment]
How do we do this for flaky tests?

**Comment by ihmccreery** [comment]
Nevermind.  I was confused.  This is for cluster settings; I was thinking it was for sets of tests.  LGTM.  Also kicking Shippable.

**Comment by mikedanese** [comment]
@k8s-bot unit test this please

**Pull request merged**
