### PR TITLE
Use PollUntilContextTimeout to replace PollWithContext in test

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Use PollUntilContextTimeout to replace PollWithContext in test
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
Hi @andrewsykim, Could you please review this pr? Thank you very much.

**Comment by bart0sh** [comment]
@bzsuni can you fix CI failures and provide more detailed description / reasoning for this change?

**Comment by carlory** [comment]
Please run ./hack/update-gofmt.sh

**Pull request closed without merging**
