### PR TITLE
Send semantic versions to version parser for development/testing.

### LINKED ISSUE #20823: Error when running kubectl e2e test: Unable to parse server version
I am running kube from latest master branch, when I am testing kubectl run job e2e test on local cluster (hack/local-up-cluster.sh), I am seeing following errors:

```
• Failure [2.602 seconds]
Kubectl client
/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1030
  Kubectl run job
  /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:954
    should create a job from an image when restart is Never [Conformance] [It]
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:952

    Feb  8 11:42:40.438: Failed to get server version: Unable to parse server version "v0.12.0.17515+dd0c313e8baf17-dirty": Invalid character(s) found in patch number "0.17515"

    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:306
------------------------------
```

### PR DESCRIPTION
**Pull request by jayunit100**
Fixes #20823

### CODE REVIEW

**Comment by ihmccreery** [comment]
Hm. We abandoned four-part semvers a long time ago; I'd rather not clutter things up trying to support pre-v1.0 versions.  Why do you need this?

**Comment by jayunit100** [comment]
Should I close this?.... I thought it was a non issue also but , iirc I saw it running from head this wknd somehow in a branch got add a dirty commit with an extra period in it. Not really sure why.

**Comment by ihmccreery** [comment]
What you posed in #20823 is a `v0.7.0` version, which is very, very old.  I'm not sure how you got that version on HEAD of your branch; perhaps you hadn't pulled tags for a (very) long time?

**Comment by ihmccreery** [comment]
So, yes, close it unless you think there's something else here.

**Comment by jayunit100** [comment]
Ok. If this crops up again somehow just ping and we can revisit.

**Comment by jayunit100** [comment]
@rrati I think you said you just saw  this issue crop up again ?

**Comment by rrati** [comment]
Yes.  I had this pop up on me.  I was running off a branch with the latest sha from Apr 20, 2016 and then updated to Apt27 2016.  I rebuilt on my branch and ran into this error.

**Comment by rrati** [comment]
Actually, I'm still seeing this problem.  Running e2e conformance against my local-up-cluster I see these errors"

INFO: update-demo-nautilus-i82qt is running right image but validator function failed: Unable to parse server version "v0.8.0.23366+833bfba72ed693": Invalid character(s) found in patch number "0.23366"

**Comment by jayunit100** [comment]
FYI, @rrati confirmed that this actually can happen to anyone who doesnt have tags on their git repo.  we could possibly reopen or else just add something to `local-up-cluster` which fails fast if builds are done w/o tags.

**Comment by ihmccreery** [comment]
cc @david-mcmahon re: how we version software.  If a dev doesn't pull tags, they get a build that thinks it's extremely old.

**Comment by rrati** [comment]
It seems incredibly silly to have a build system produce something that won't run because of a missing tag.  If the fix above would resolve this issue w/o impacting builds with tags, why wouldn't we want it?

**Comment by david-mcmahon** [comment]
The build has been designed around the [assumption that tags exist ](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L52) in the repository from which you are building. 

The easiest fix here is to sync tags in the copy of the repository from which you're building.

We could track a new feature (in a new issue) for the build and project that would check if tags are in the repo before trying to pull a version from them and set the version to 999.999.999-dev or the like or some other string that might require modifications to the semver lib and other dependent checks of the version format.  

If there are _some_ tags in the repo but unsynced and out of date, there's no good way to know what the intention of the user is at that point.

**Pull request closed without merging**
