### PR TITLE
Hollow-node should use separate client for heartbeats

### PR DESCRIPTION
**Pull request by mborsz**
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:

This is the way it works for normal kubelets: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L593 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mborsz** [comment]
Fixes #79887

**Comment by wojtek-t** [comment]
LGTM - once tests are passing

**Comment by wojtek-t** [comment]
/lgtm cancel

It seems there are some real issues for gofmt and bazel.

**Comment by mborsz** [comment]
I fixed gofmt and bazel lints.

**Pull request merged**
