### PR TITLE
apiserver: fix kubeconfig documentation link in comment

### LINKED ISSUE #123015: wrong document link in apiserver code
### What happened?

https://github.com/kubernetes/kubernetes/blob/eb0fcf9e216f83e200e1c04e24d0484394da6b86/staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go#L100

`https://kubernetes.io/docs/user-guide/kubeconfig-file/` not exist

### What did you expect to happen?

-

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
master
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
none
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by hunshcn**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Clean up outdated links

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/123015

#### Does this PR introduce a user-facing change?

```release-notes
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by justankiit — APPROVED** [review]
lgtm

**Comment by hunshcn** [comment]
ping @kumarankit999 for lgtm again

**Comment by kumarankit999** [comment]
Hey @hunshcn, Can you refer to the issue the PR has raised?

**Comment by hunshcn** [comment]
No, this is a mistake I found when reading the source code. Since it was
very simple, I just submitted PR. Do I need to create a issue for this?

Ankit Kumar ***@***.***> 于 2024年1月24日周三 12:26写道：

**Comment by hunshcn** [comment]
ready to go, request review

**Pull request closed without merging**
