### PR TITLE
[1.24] vendor: bump runc to 1.1.3

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This is a manual backport of PR #110496 to release-1.24 branch.

#### Does this PR introduce a user-facing change?
```release-note
Fix "dbus: connection closed by user" error after dbus daemon restart.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
/lgtm

We should try introducing (and backporting) a Serial E2E for this.

**Review by mrunalp — APPROVED** [review]

**Comment by pacoxu** [comment]
There is a regression in runc v1.1.3 https://github.com/opencontainers/runc/pull/3554 that is fixed in v1.1.4.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
