### PR TITLE
[WIP] separate API authorization from generic authorization

### PR DESCRIPTION
**Pull request by deads2k**
There are two very different cases for authorization:  
1. API requests where we have significant structured information about the request itself
2. Generic requests where we have only the URL, body contents, and method.

Combining those two different cases creates a bifurcated execution path for many would-be authorizers, split based on which call is being made.  This pull:
1. Splits those two calls apart to make it very clear which information is available in each case.  
2. Protects the API endpoints by wiring directly into the API routes using a filter.
3. Eliminates drift between the API installer and the APIRequestInfoResolver by providing the metadata based on the same source used for the API endpoints themselves. 
4. Provides an extension point for a custom authorizer to gather additional data.
5. Resolves the full set of API request information:
   1.  UserInfo
   2.  Verb
   3.  API Version
   4. Namespace
   5. Resource
   6. Subresource
   7. Kind
   8. ResourceName
6.  Limits the set of information for generic request information
   1. UserInfo
   2. URL
   3. Method
7.  Refactors the api server handler creation to make it easy to inspect whether authorization has been applied.

TODO:
- [ ] confirm e2e tests still work
- [ ] confirm that basic auth authentication works as expected
- [ ] plumb through the extension builder
- [ ] add APIVersion to parameters
- [ ] plumbing a context through authorization calls will enhance traceability.  
- [ ] reattach a minimal set of muxes in the master struct

Follow up:
- [ ] parse API request body

@smarterclayton Here's a first cut at splitting the two authorization types and getting the authorization attributes from the single source of truth.

@erictune I think enough is complete to see the overall structure and intent.  I've got a list of todos before committing, but feedback is welcome.

@liggitt  I've opened up the muxes and handlers from master quite a bit.  We're wired in here from openshift, do you see anything I've made harder for us?

### CODE REVIEW

**Comment by smarterclayton** [comment]
I don't know if I like subresources being split.  Each subresource is its own resource, and while it has a relation to a parent, I don't want clients authorizing to a Resource only (encourages bad behavior, since a prime purpose of subresources is partitioning user classes).

What's the reasoning for splitting?  We will probably have multi segment subresources eventually.

**Comment by deads2k** [comment]
> What's the reasoning for splitting?  We will probably have multi segment subresources eventually.

I like to keep separate things separate.  Concat-ing resources and subresources into a single string makes it harder for alternate implementations to do interesting things.  For instance, what if an authorizer wants to express rights to `get` a `status` subresource on any resource.  Having separate fields makes it easy to write that logic, but doesn't make any harder for someone to have authorizer that forces each status subresource to be called out.  I don't see a reason to make life harder for authorizer implementations.

**Comment by smarterclayton** [comment]
Ok

**Comment by deads2k** [comment]
@erictune 

The design of making policy decisions as filters in the go-restful router's filterchain does not handle the case of wanting to proxy an API request from one server to another.  Creating an authorizing proxy requires that the proxier be able to interpret the request patterns of the API it is authorizing.  The `APIRequestInfoResolver` does this today, so it ends up being reusable for authorizing the API itself and authorizing proxy requests against a conformant API.

The problem we were trying to solve was how to make sure that the authorization attributes were always correct.  Since the APIInstaller was the source of truth, that seems like an obvious place to put it, but it didn't work in all cases.  The problem can also be resolved by an integration test that reads the swagger doc and tests every request pattern against the `APIRequestInfoResolver` to make certain that requests are all interpreted correctly.  That would satisfy the need for fidelity, while also allowing authorization outside of the go-restful routes themselves.

Closing this pull request.

@smarterclayton anything to add?

**Comment by erictune** [comment]
I like the swagger-based integration test idea.

**Pull request closed without merging**
