### PR TITLE
fix Master-blocking failing tests in verify.godeps and verify.staging-godeps

### LINKED ISSUE #74261: Master-blocking failing tests: verify.godeps and verify.staging-godeps
**Which jobs are failing**:
* [master-blocking/verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Which test(s) are failing**:

| Job | Test | Reason for failure |
|---|---|---|
| [verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) | [verify.godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819) | `Your vendored results are different: diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto /tmp/gopath.fjRjH3/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto`
| [verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) | [verify.staging-godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819) | `Unexpected dirty working directory`

**Since when has it been failing**:
2019-02-19, [build 26960](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26960), [k/k 42b7bb1c1](https://github.com/kubernetes/kubernetes/commit/42b7bb1c1)

**Anything else we need to know**:
Related: https://github.com/kubernetes/kubernetes/issues/73999
I wonder if there's an opportunity for automation/testing before end to end tests there 🤔

/kind failing-test
/priority important-soon
/sig api-machinery

cc @smourapina @alejandrox1 @mortent @kacole2

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This block master testing in verify.godeps and verify.staging-godeps.

**Which issue(s) this PR fixes**:

Fixes #74261

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-testing how are the verify tests passing on the PRs introducing these changes? Are the verify update scripts running in the wrong order?

**Comment by BenTheElder** [comment]
`pull-kubernetes-godeps` should be running to cover these (?) not sure what broke.
cc @cblecker

**Pull request merged**
