### PR TITLE
Use bigger keys for RSA-PSS, default for TLS 1.3 (Golang 1.13 requirement)

### LINKED ISSUE #80733: apimachinery: Golang 1.13 requires bigger keys
Golang 1.13 uses TLS 1.13 by default (opt-out), which introduces RSA-PSS. 
RSA-PSS does not work with keys that are too small.

The issue was uncovered during Fedora mass rebuild which uses Golang 1.13:

```
k8s.io/apimachinery/pkg/util/httpstream/spdy
2019/07/28 19:34:59 http: TLS handshake error from 127.0.0.1:43166: tls: failed to sign handshake: crypto/rsa: key size too small for PSS signature
2019/07/28 19:34:59 http: TLS handshake error from 127.0.0.1:39248: tls: failed to sign handshake: crypto/rsa: key size too small for PSS signature
2019/07/28 19:34:59 http: TLS handshake error from 127.0.0.1:48100: tls: failed to sign handshake: crypto/rsa: key size too small for PSS signature
--- FAIL: TestRoundTripAndNewConnection (0.03s)
```

See https://github.com/golang/go/issues/30055

/sig api-machinery

### PR DESCRIPTION
**Pull request by eclipseo**
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Update RSA keys to 1024 bits to use with RSA-PSS which are the default for TLS 1.3.
TLS 1.13 is the default starting Golang 1.13.

**Which issue(s) this PR fixes**:

Fixes #80733

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

This PR was tested on Fedora Rawhide:

Before: https://kojipkgs.fedoraproject.org//work/tasks/5166/36635166/build.log
After: https://kojipkgs.fedoraproject.org//work/tasks/1053/36661053/build.log

### CODE REVIEW

**Comment by eclipseo** [comment]
Signed the CLA: https://identity.linuxfoundation.org/system/files/clas/signed/cla_individual-99805ea5c05cf6cfce1bd8d24f5e9a6876f7d247.pdf

**Comment by liggitt** [comment]
/hold

what happens to existing clusters with keys that were previously accepted on upgrade?

it may be fine to work around this for a test, but we should consider the compatibility implications of this required configuration change before silencing the test failure

**Comment by liggitt** [comment]
> what happens to existing clusters with keys that were previously accepted on upgrade?
> 
> it may be fine to work around this for a test, but we should consider the compatibility implications of this required configuration change before silencing the test failure

/hold cancel

the key sizes that are affected have been vulnerable to cracking for ~20 years. this is release-note worthy, but requiring production clusters to use a minimum of 1024-bit keys is entirely reasonable (most should be at least 2048 at this point)

**Comment by liggitt** [comment]
@eclipseo are there any other 512-bit keys lurking around that you ran into? did you get a clean unit test run in the other kubernetes repos with go1.13 with this?

**Comment by eclipseo** [comment]
> @eclipseo are there any other 512-bit keys lurking around that you ran into? did you get a clean unit test run in the other kubernetes repos with go1.13 with this?

I encountered this bug only on apimachinery, other parts are building fine:
https://koji.fedoraproject.org/koji/search?match=glob&type=package&terms=golang-k8s*
But I found it only because it is occurring in a test, if some other part of the code is using 512bits keys other than in tests, I can't detect it.

**Comment by tedyu** [comment]
By TLS 1.13, I think you meant TLS 1.3

**Pull request merged**
