### PR TITLE
Automated cherry pick of #66064 upstream release 1.11 1536134932

### PR DESCRIPTION
**Pull request by lbernail**
Cherry pick of #66064 on release-1.11.

#66064 : fix Local externalTrafficPolicy is not respected for ipvs NodePort

/sig network
/area ipvs

### CODE REVIEW

**Comment by m1093782566** [comment]
/assign @thockin 
for cherry-pick approval.

**Comment by lbernail** [comment]
Ok from the test output it looks like the update to tests require a more recent version of proxier_test.go
Looking into it

**Comment by lbernail** [comment]
The update to tests had been merged in `TestOnlyLocalLoadBalancing` instead of `TestOnlyLocalNodePorts`
My new commit should fix this

I can rebase it to clean the commits if need

**Comment by lbernail** [comment]
@m1093782566 I think we are good now, can you add the "lgtm" label back?
Let me know if you would rather I squash the commits for the test (I'm not sure how to handle a cherrypick that requires additional changes)

**Comment by lbernail** [comment]
Thank you for approving
I think the last thing missing is the `do-not-merge/cherry-pick-not-approved` label

/assign @foxish for cherry-pick approval

**Pull request merged**
