### PR TITLE
Update CleanupAndExit and OnServiceSynced field comment and bugfix panic params in the construct method

### PR DESCRIPTION
**Pull request by xigang**
**What type of PR is this?**
 /kind bug
 /kind cleanup

**What this PR does / why we need it**:
- Update Update the CleanupAndExit field for the Options and the OnServiceSynced for the ServiceHandler comment
- bugfix: panic log params in the construct method when maxInterval is less than minInterval

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

```

### CODE REVIEW

**Comment by xigang** [comment]
cc @andrewsykim @caseydavenport

**Comment by xigang** [comment]
cc @dchen1107

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
