### PR TITLE
Fix up #10851 to be golang 1.3 compatible.

### PR DESCRIPTION
**Pull request by jbeda**
See also #11016

### CODE REVIEW

**Comment by jbeda** [comment]
Local unit tests passed for me.

**Comment by jbeda** [comment]
Looks like shippable is busted now because of some missing GA beacons in md files.  But 1.3 built just fine.

**Comment by mbforbes** [comment]
Cool, and the other fmt errors were just symptoms of the same `for range` cause?

**Comment by mbforbes** [comment]
Do we need TLs? Does Joe count? :-) @alex-mohr @roberthbailey

**Comment by jbeda** [comment]
I don't count :)  Better for someone with more context to OK things.  gofmt looks clean, I think.

**Comment by vmarmol** [comment]
LGTM, ping @dchen1107 @thockin

**Comment by vmarmol** [comment]
Since it is breaking us, I'll merge on green. Preferably with a TL LGTM :)

**Comment by thockin** [comment]
LGTM, ok

**Comment by bgrant0607** [comment]
LGTM
ok to merge

**Comment by jbeda** [comment]
I've got to run and pick up the kids -- I'll check back in a bit.  Looks like the build works so I don't anticipate any issues.

**Comment by vmarmol** [comment]
Thanks for the fix @jbeda!

**Comment by vmarmol** [comment]
@k8s-bot please test this

**Pull request merged**
