### PR TITLE
Use read lock for reconciler#getHandlers and clean up for the pluginmanager

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
For reconciler#getHandlers, read lock should suffice.

Also contains minor change where entry is deleted from map directly.

Related to #73891

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @msau42 @taragu

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Could you please update your pull request/commit title to reflect that this diff contains general clean up for the `pluginmanager` (i.e. not just adding the `ReadLock`)?

**Comment by tedyu** [comment]
@taragu 
Can you review ?

**Comment by taragu** [comment]
@tedyu sure! Thanks for fixing this.
/approve

**Comment by saad-ali** [comment]
/milestone v1.15

bug fix

**Pull request merged**
