### PR TITLE
Adding tests for namespace API:

### PR DESCRIPTION
**Pull request by mkurylec**
Adding testcases for namespaces api group
* list
	-listing default namespaces
* create
	- creating a namespace with empty data
	- creating a namespace with valid name
	- creating a namespace with invalid (containing uppercase) generate name
	- creating a namespace with valid generateName
	- creating a namespace with valid generateName and labels

**Special notes for your reviewer**:
Hi review team: 
This is my first PR. I'm thankful for guidance and advice. 

Placed the changes on a separate folder since i was not sure if i should place it under apimachinery directly, and  looking to learn and calibrate if this is ok.

The intention here was to exercise scenarios for this api group. 
Created 2 sections: one for list and one for create. 
list:
a) "list with empty options should show built-in by default namespaces"
Here i tried to make sure that the default namespaces were brought. Since the result of invoking list brings existing namespaces also, the test focuses on the presence of the default ones. Using a map to hold the expected and check presence.

create:
a) "creating a namespace with empty parameters should fail"
Expecting it to fail with empty parameters.

b) "creating a namespace with only (valid) name parameter should succeed"
creating it with the minimum object. Expecting it to return a namespace. Checking afterwards against the creation data sent.

c) "creating a namespace with invalid generateName (containing uppercase) should fail"
Expecting it to fail with generate name not following the grammar.

d) "creating a namespace with valid generateName (all lowercase)"
Using generateName instead of name directly here. So expecting name formation to be different (using it as a prefix)

e) "creating a namespace with valid generateName (all lowercase) and labels set"
Like scenario (d) but asking to put labels on it.

Down below, created a struct named "NamespaceVerifier" that would let me hold "default expecations" and letting me override only the ones I am specifically looking for in the precise scenario.This would allow me to verify that the object returned makes sense (and not duplicate individual expect lines on each scenario).
Invoking verifyAll would run all the checks against the fields.

I placed some TODO comments with doubts regarding types.

Thanks a lot!

### CODE REVIEW

**Comment by BenTheElder** [comment]
CLA needs fixing, if I had to guess we should have 
/sig api-machinery
review this

**Comment by BenTheElder** [comment]
test

**Comment by timothysc** [comment]
/hold 

Please touch base with @kubernetes/sig-architecture-feature-requests prior to making these changes it requires their sign-off, then looping in the appropriate folks from there 

@kubernetes/steering-committee

**Comment by bgrant0607** [comment]
cc @k8s-mirror-api-machinery-pr-reviews

**Comment by bgrant0607** [comment]
@mkurylec Please create the tests first and get them reviewed by API machinery.

Then propose the tests to be added to conformance in a separate PR, after they prove non-flaky.

cc @AishSundar

**Comment by bgrant0607** [comment]
In-progress guidelines:
https://github.com/kubernetes/community/pull/1867/files

**Comment by bgrant0607** [comment]
Note that creating and mutating namespaces can be privileged operations.

cc @liggitt

**Comment by liggitt** [comment]
> Note that creating and mutating namespaces can be privileged operations.

Today, e2e tests (of which conformance is a subset) generally assume the test runner has high levels of privilege on the target cluster.

https://github.com/kubernetes/community/pull/2081 discusses the idea of running conformance tests that verify the inverse - that the cluster limits what a particular user can do

**Comment by mkurylec** [comment]
thanks for answering, let me amend both PRS. Thanks a lot!

**Pull request closed without merging**
