### PR TITLE
removing unnecessary shallow copy on SyncService

### LINKED ISSUE #46703: shallow of pods shouldn't be done on syncService
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/controller/endpoint/endpoints_controller.go` we have `syncService ` that perform unnecessary shallow copy on pods (`line 343`) : 

- we get the pods from the cache i think
- we do not mutate the pods (i.e only reading values)

so we can avoid this deepCopy i think.

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**: remove shallow copy + avoid using same index name as the nested loop

**Which issue this PR fixes**: fixes #46703 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by yastij** [comment]
@wojtek-t - PTAL

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by yastij** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by yastij** [comment]
@thockin - Milestone is for a future release and cannot be merged, this change won't make it to the 1.7 ?

**Comment by thockin** [comment]
Unless you can show how this is a significant bugfix, 1.7 has entered the
stabilization period.

**Comment by yastij** [comment]
@thockin thanks for the information !

**Comment by yastij** [comment]
@thockin - pull-kubernetes-federation-e2e-gce broken ?

**Pull request merged**
