### PR TITLE
cri-api: remove redundant leading space

### PR DESCRIPTION
**Pull request by maxsxu**
Signed-off-by: Max Xu <xuhuan@live.cn>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove redundant leading space.

#### Special notes for your reviewer:

It is a trivial code cleanup but will make developers more comfortable.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
please review our trivial edits policy https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits. Thank you for your PR, I advice to find an issue marked with help-wanted

/close

**Comment by maxsxu** [comment]
> please review our trivial edits policy https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits. Thank you for your PR, I advice to find an issue marked with help-wanted
> 
> /close

Thanks for reminding, I'll combine this trivial fix with other PRs.

**Pull request closed without merging**
