### PR TITLE
Use abstract cache.NewListWatchFromClient to make the code clean

### PR DESCRIPTION
**Pull request by 249043822**
Use abstract cache.NewListWatchFromClient to make the code clean

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33425)

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by 249043822** [comment]
@yujuhong , As of some flakes, the tests got failed, now i have made it retest by force-push, it's green,
need lgtm label again, thanks

**Comment by yujuhong** [comment]
@249043822 Please rebase, thanks!

**Comment by 249043822** [comment]
@yujuhong have rebased!

**Comment by yujuhong** [comment]
@k8s-bot gci gce e2e test this. issue: #IGNORE

**Pull request merged**
