### PR TITLE
*: remove --insecure-allow-any-token option

### LINKED ISSUE #49031: Remove --insecure-allow-any-token authenticator
/kind feature

Impersonation is sufficiently capable that this method seems redundant, even when debugging.

@deads2k I remember you were the one who originally requested this. Any objections to removing?

/cc @kubernetes/sig-auth-feature-requests

### PR DESCRIPTION
**Pull request by ericchiang**
~Since the authenticator is still used in e2e tests, don't remove
the actual package. Maybe a follow up?~

edit: e2e and integration tests have been switched over to the tokenfile
authenticator instead.

```release-note
The --insecure-allow-any-token flag has been removed from kube-apiserver. Users of the flag should use impersonation headers instead for debugging.
```

closes #49031

cc @kubernetes/sig-auth-pr-reviews

### CODE REVIEW

**Comment by ncdc** [comment]
/unassign
/assign @liggitt 
FYI @mattmoyer

**Comment by liggitt** [comment]
> Since the authenticator is still used in e2e tests, don't remove the actual package. Maybe a follow up?

If we're going to remove it, let's remove it.

**Comment by ericchiang** [comment]
Fully removed

**Pull request merged**
