### PR TITLE
should use time.Since instead of time.Now().Sub

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
should use time.Since instead of time.Now().Sub

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by m1093782566** [comment]
@wgliang Would you please tell use why we should migrate "time.Now().Sub" to "time.Since"? With golang version update?

**Comment by wgliang** [comment]
@m1093782566 The time.Since helper has the same effect as using time.Now().Sub(x) but is easier to read.

**Comment by m1093782566** [comment]
From the source,

```
// Since returns the time elapsed since t.
// It is shorthand for time.Now().Sub(t).
func Since(t Time) Duration {
	return Now().Sub(t)
}
```

FYI.

**Comment by wgliang** [comment]
@smarterclayton PTAL.

**Comment by derekwaynecarr** [comment]
nice simplification.

/approve no-issue

**Review by janetkuo — APPROVED** [review]

**Comment by wgliang** [comment]
Need your HELP，@smarterclayton

**Comment by dims** [comment]
please ignore the output from pull-kubernetes-local-e2e-containerized it's not a required job and is currently not fully working yet

**Review by dims — APPROVED** [review]

**Comment by wgliang** [comment]
/cc @smarterclayton @ lavalamp @ brendandburns 
PTAL

**Comment by wgliang** [comment]
/cc @smarterclayton @lavalamp @brendandburns 
PTAL

**Pull request merged**
