### PR TITLE
Port all remaining features to versioned

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Port all remaining features to versioned

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/triage accepted
/assign @jpbetz

### CODE REVIEW

**Review by jpbetz — APPROVED** [review]
/lgtm
/approve

**Comment by Jefftree** [comment]
Fixed the linting to check the versioned feature gates rather than the unversioned ones (since it's empty now).

**Comment by BenTheElder** [comment]
/approve
for hack

**Comment by pacoxu** [comment]
/test pull-kubernetes-e2e-gce-cos-alpha-features
/lgtm 
after rebase

**Pull request merged**
