### PR TITLE
Update memory requirements for influxdb

### PR DESCRIPTION
**Pull request by gmarek**
It starts to fail in soak cluster after few days.

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
Fix for soak suite.

**Comment by bprashanth** [comment]
I've seen this oom on a low load small cluster after a few days, do we know how much the memory grows by?

**Comment by gmarek** [comment]
@bprashanth - we don't - that's one of the reason we need to make it bigger and monitor it. We might want to gather information about container resource usage in soak cluster. Sadly resource-usage-gatherer if turned on is running after each test, which would generate a lot of spam. We can create a suite running one test only, that's run only to gather resources. I can do this given free cycles, but if someone beats me to it, I won't have anything against it.

**Pull request merged**
