### PR TITLE
Automated cherry pick of #70699: Include read access to controllerrevisions for

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #70699 on release-1.12.

#70699: Include read access to controllerrevisions for

### CODE REVIEW

**Comment by feiskyer** [comment]
@liggitt Should this fix be included in the v1.12.3?

**Comment by liggitt** [comment]
> @liggitt Should this fix be included in the v1.12.3?

The master PR hasn't merged yet, so I would hold it

**Comment by liggitt** [comment]
/hold
For master

**Pull request merged**
