### PR TITLE
Align Extender's validation with prioritizers.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
Align Extender's validation with prioritizers.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Review by ravigadde — APPROVED** [review]
/lgtm

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Pull request merged**
