### PR TITLE
add debugging for aggregator flake

### PR DESCRIPTION
**Pull request by liggitt**
capture current state of the APIService and extension server pod for output in failure cases

xref https://github.com/kubernetes/kubernetes/issues/63622

```release-note
NONE
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
> I opened #64587 to capture the state of the APIService, extension server pods, and those pod logs in failures cases

We might also need to get the logs from the pod that is running the sample-apiserver even if it doesn't fail. From the logs I saw it looked like it wasn't failing, just taking a long time (or forever) to start the server.

**Comment by liggitt** [comment]
> We might also need to get the logs from the pod that is running the sample-apiserver even if it doesn't fail. From the logs I saw it looked like it wasn't failing, just taking a long time (or forever) to start the server. Not sure how possible that is to do, though.

that would cause a timeout failure, which this should capture

**Comment by jennybuckley** [comment]
ah I see you were saying if the test failed, not if the pod failed. My mistake. Are you going to just keep retesting this until it flakes?

**Comment by liggitt** [comment]
> Are you going to just keep retesting this until it flakes?

since it only kicks in when the test fails, I'd probably merge this to get data from CI runs

**Pull request merged**
