### PR TITLE
refactor certs in GCE to break up usages

### PR DESCRIPTION
**Pull request by mikedanese**
TODO: debian

### CODE REVIEW

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
@k8s-bot test this
My bad.

**Comment by pipejakob** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/gce/gci/configure-helper.sh, line 219 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41667#-KdDi5fDoZETCtHMFzob:-KdDi5fDoZETCtHMFzoc:b-t7szzu) ([raw file](https://github.com/kubernetes/kubernetes/blob/dd3ed2af132e128e4370063782186f2e9a20b29d/cluster/gce/gci/configure-helper.sh#L219)):*
> ```Shell
>   fi
> 
>   if [[ ! -z "${KUBELET_CERT}" && ! -z "${KUBELET_KEY}" ]]; then
> ```

Wouldn't the "set -o nounset" make the script die if $KUBELET_CERT or $KUBELET_KEY were unset here? The other checks in this file (including your diff) use the pattern "${VAR:-}" for safety. Whether it's required or not, I'd standardize on one convention.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41667)*

**Comment by mikedanese** [comment]
@pipejakob done, thanks.

**Comment by mikedanese** [comment]
@k8s-bot test this

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by mikedanese** [comment]
@k8s-bot unit test this
@k8s-bot kops aws e2e test this

**Pull request merged**
