### PR TITLE
Fix typo and spelling inconsistency

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
1. Fix typo
 - behaviour -> behavior (Change British notation to US notation, so this is not typo acutually)
2. Correct spelling inconsistency
 - The **k**ubelet and The **K**ubelet are mixed. I unified the notation to `The Kubelet`.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

I don't feel strongly about `Kubelet` vs `kubelet`, but agree that standardization makes sense!

**Comment by mattjmcnaughton** [comment]
Also, welcome to k8s :)

**Comment by hase1128** [comment]
@dchen1107 @mattjmcnaughton 
Could you add `approve` label to this PR?

**Comment by hase1128** [comment]
@dchen1107 @mattjmcnaughton
Could you add approve label to this PR?

**Comment by mattjmcnaughton** [comment]
@dchen1107 has the auth to do the final sign-off. thanks :)

**Comment by hase1128** [comment]
@dchen1107 
Would you give any feedback or add approval label?

**Pull request closed without merging**
