### PR TITLE
Code optimization

### PR DESCRIPTION
**Pull request by yarntime**
**What this PR does / why we need it**:
    use util.Int32Ptr instead of int32

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
@k8s-bot ok to test

/lgtm

Sorry for delay, I was OOO.

**Comment by lavalamp** [comment]
argh, sorry, if you rebase this I'll do my best to tag it again in 24 hours.

**Comment by grodrigues3** [comment]
@yarntime this needs rebase

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Pull request closed without merging**
