### PR TITLE
chore(kubectl_utils): remove windows specifc command addition for sync

### LINKED ISSUE #101172: Add sync to the windows node for storage E2E tests
#### What would you like to be added:

We'd like to add https://docs.microsoft.com/en-us/sysinternals/downloads/sync to the windows nodes

#### Why is this needed:

Discussed in https://github.com/kubernetes/kubernetes/pull/100377#discussion_r614367327, some storage e2e tests need the `sync` call to flush data to disk, this utility is not available in windows nodes or agnhost

/sig storage
/sig testing

### PR DESCRIPTION
**Pull request by crisboarna**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Cleans up windows specific test command configuration after conclusion of #101172

#### Which issue(s) this PR fixes:
Fixes #101172

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
``

/sig testing

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
/ok-to-test

There aren't presubmit e2e tests for storage & windows in the k/k repo, we usually test them from the CSI Driver repos instead

**Comment by crisboarna** [comment]
@mauriciopoppe is this good to merge now?

**Comment by mauriciopoppe** [comment]
@jingxu97 I think the e2e windows tests weren't run, what do you think about merging it as it is?

**Comment by crisboarna** [comment]
Hi @jingxu97, would this PR be good to merge ?

**Comment by mauriciopoppe** [comment]
@pohly I saw that you can approve this PR, could you help us with it?

**Pull request merged**
