### PR TITLE
Add skydns to deps.

### PR DESCRIPTION
**Pull request by rjnagal**
Fixes godep build ./...
Also pulls in github.com/miekg/dns.
rackspace/gophercloud doesn't seem to need kr/text and golang-pretty anymore.

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM, needs rebase.

**Comment by rjnagal** [comment]
Rebased.

**Comment by thockin** [comment]
Still says it can't merge

**Comment by rjnagal** [comment]
@thockin Brendan just reverted the change I rebased to :)
Let me re-rebase!

**Comment by rjnagal** [comment]
@thockin All's well again.

**Comment by markturansky** [comment]
Is there a reason not to include golang-pretty in Godeps?  I found it useful when debugging.

**Comment by rjnagal** [comment]
godep save dropped it automatically as nothing in kubernetes codebase was using it. Are you planning on using it somewhere in kube code?

**Comment by markturansky** [comment]
I see.  I only used it when debugging because it is helpful to see my data, and those pretty printed statements were never checked in, of course.

**Pull request merged**
