### PR TITLE
Promote mkumatag to approver in test/images

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I653d4c40901cf5ba0097c31a64ea55b3b10e418e

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
@mkumatag has been around for a long time and has taken on a lot of the multi-arch enablement work. So it's only fair that we promote him to approver.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @ixdy @luxas 

cc @mkumatag

**Comment by mkumatag** [comment]
/lgtm

no doubt about it :P

**Comment by ixdy** [comment]
strongly agree. thanks @dims !

/lgtm
/approve

**Comment by mkumatag** [comment]
Thanks for your support guys @dims @ixdy @luxas

**Pull request merged**
