### PR TITLE
Use e2eskipper package in test/e2e/framework/

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR use e2eskipper package instead of using func Skip* in kubernetes/test/e2e/framework/

**Which issue(s) this PR fixes**:

Ref: #87047

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
We need to run ./hack/update-gofmt.sh to pass CI

**Review by timothysc — APPROVED** [review]
/approve  
to unblock 
/assign @alejandrox1

**Comment by YuikoTakada** [comment]
@tanjunchen thanks. done

**Pull request merged**
