### PR TITLE
Bump version for the sample-device-plugin image

### PR DESCRIPTION
**Pull request by mkumatag**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

I see some changes pushed after 1.6 version not bumped the version in the VERSION file, hence this PR is for bumping the version and also pushing the image

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mkumatag** [comment]
/cc @Prajyot-Parab @Karthik-K-N 

can someone please gimme quick ack?

**Review by Karthik-K-N — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123129/pull-kubernetes-node-e2e-containerd/1754400978318135296 

/hold
as https://github.com/kubernetes/kubernetes/issues/123127 will fail pull-kubernetes-node-e2e-containerd which is required CI.

**Pull request merged**
