### PR TITLE
Remove genyaml binary

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
ugh! we should not be checking in binaries!

Looks like this was added inadvertantly in https://github.com/kubernetes/kubernetes/pull/75432

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

I'd like to see a follow up add a verify script that prevents future mistakes like this

**Comment by BenTheElder** [comment]
s/remote/remove? :upside_down_face:

**Comment by dims** [comment]
fixed @BenTheElder

**Pull request merged**
