### PR TITLE
Skip LB session affinity test on AWS

### LINKED ISSUE #67946: e2e tests for LoadBalancer service session affinity with ESIPP fail on AWS
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
```
[sig-network] Services
  should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1580
[BeforeEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:141
STEP: Creating a kubernetes client
Aug 27 21:12:18.186: INFO: >>> kubeConfig: /tmp/kubeconfig-751029509
STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:83
[It] should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1580
STEP: creating service in namespace e2e-tests-services-g9z6g
STEP: creating service service in namespace e2e-tests-services-g9z6g
STEP: creating replication controller service in namespace e2e-tests-services-g9z6g
I0827 21:12:18.249332       8 runners.go:177] Created replication controller with name: service, namespace: e2e-tests-services-g9z6g, replica count: 3
I0827 21:12:21.299803       8 runners.go:177] service Pods: 3 out of 3 created, 3 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
STEP: waiting for loadbalancer for service e2e-tests-services-g9z6g/service
Aug 27 21:12:21.302: INFO: Waiting up to 20m0s for service "service" to have a LoadBalancer
Aug 27 21:32:21.307: INFO: Timed out waiting for service "service" to have a load balancer
[AfterEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Collecting events from namespace "e2e-tests-services-g9z6g".
STEP: Found 17 events.
Aug 27 21:32:21.311: INFO: At 2018-08-27 21:12:18 +0000 UTC - event for service: {replication-controller } SuccessfulCreate: Created pod: service-msvzk
Aug 27 21:32:21.311: INFO: At 2018-08-27 21:12:18 +0000 UTC - event for service: {replication-controller } SuccessfulCreate: Created pod: service-8rjng
Aug 27 21:32:21.311: INFO: At 2018-08-27 21:12:18 +0000 UTC - event for service: {replication-controller } SuccessfulCreate: Created pod: service-hrxwk
Aug 27 21:32:21.311: INFO: At 2018-08-27 21:12:18 +0000 UTC - event for service: {service-controller } CreatingLoadBalancerFailed: Error creating load balancer (will retry): failed to ensure load balancer for service e2e-tests-services-g9z6g/service: unsupported load balancer affinity: ClientIP
Aug 27 21:32:21.311: INFO: At 2018-08-27 21:12:18 +0000 UTC - event for service: {service-controller } EnsuringLoadBalancer: Ensuring load balancer
```

**What you expected to happen**:
The test should either succeed or be skipped on AWS

**How to reproduce it (as minimally and precisely as possible)**:
Run this test on an AWS cluster with the AWS cloud provider configured

**Anything else we need to know?**:
The test sets the service's session affinity to `v1.ServiceAffinityClientIP` here:

https://github.com/kubernetes/kubernetes/blob/965df0744726df87058bc27a1cb26ae3ee606dcc/test/e2e/network/service.go#L2019

The AWS cloud provider specifically only supports `v1.ServiceAffinityNone`:

https://github.com/kubernetes/kubernetes/blob/fdb5707194d56cbbd0da11c5be3a2a5653e714c9/pkg/cloudprovider/providers/aws/aws.go#L3249-L3252

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Let me know if the added comment doesn't make sense.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67946

**Special notes for your reviewer**:
/assign @ncdc 
cc @grayluck 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM. Do you want anyone else (e.g. from sig-network) to review?

**Comment by MrHohn** [comment]
> LGTM. Do you want anyone else (e.g. from sig-network) to review?

Sure, adding owner from https://github.com/kubernetes/kubernetes/commits/master/pkg/cloudprovider/providers/aws/OWNERS.
/assign @justinsb

**Review by dcbw — APPROVED** [review]
/lgtm

**Comment by MrHohn** [comment]
Thanks!

**Pull request merged**
