### PR TITLE
Fix kubeadm taints to not override existing node taints

### PR DESCRIPTION
**Pull request by ashleyschuett**
**What this PR does / why we need it**:
If a node has existing taints they are being replaced with taints from the kubeadm config. 

An example of this is that the `uninitialized` taint that kubelet sets for external cloud provider is being removed, and replaces with the master taint if set, or removed leaving the nodes taints empty if `noTaintMaster=true` . 

```release-note
None
```

### CODE REVIEW

**Comment by ashleyschuett** [comment]
The test that failed is 
```{
  "nothing missing but taint unwanted",
   kubeadmconstants.LabelNodeRoleMaster,
   []v1.Taint{kubeadmconstants.MasterTaint},
   nil,
   "{\"spec\":{\"taints\":null}}",
}```

This test is actually asserting that the previous behavior is the correct behavior and goes against what the logic in this PR is. Should I remove the test or does the logic of this change need to be discussed more? I think the test should be removed as I would not expect that taints are removed because they aren't specified in the config file.

**Comment by fabriziopandini** [comment]
@ashleyschuett thanks for your PR!
The test fails because with your PR we are removing the possibility to delete all the current taints using mark-master. 
I'm not aware of a use cases when this is required, but since this behaviour is there and there is a specific unit test better to ask 
 /CC @luxas @ijc 
Thoughts here?

**Comment by ijc** [comment]
The test/behaviour came in #55479 where I said in the PR intro:
> The code also arranges to remove an existing taint if it is unwanted. I'm unsure if this behaviour is correct or desirable, I think a reasonable argument could be made for leaving an existing taint in place too.

Which if I understand correctly is exactly the issue here? I have no strong feelings for either behaviour and I don't recall any of the reviewers questioning the above or the behaviour (which makes me suspect they had no particular opinion also rather than explicitly agreed with it doing it that way).

So long as the `noTaintMaster` aspect of #55479 remains functional I don't really have an opinion on the behaviour WRT existing taints. IOW I'm fine with the behaviour being changed and the test remove or, perhaps better, adjusted for the new behaviour.

**Comment by ashleyschuett** [comment]
I updated the test to reflect both the empty case, and the merge case. So if the kubeadm taints is nil the nodes taints should not be removed, and that if there are existing taints they should be merged with the kubeadm config.

**Comment by timothysc** [comment]
/approve 

thx @ashleyschuett !

**Pull request merged**
