### PR TITLE
Allow upgrade target version to be specified

### PR DESCRIPTION
**Pull request by mbforbes**
... in the upgrade e2e test.

+cc @ixdy @roberthbailey @zmerlynn

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by mbforbes** [comment]
Kicking shippable....

**Comment by mbforbes** [comment]
Shippable has a true failure, but not in this code:
```
 ./hack/verify-gofmt.sh
./pkg/kubectl/resource_printer.go:976:6: expected operand, found 'range'
./pkg/kubectl/resource_printer.go:981:2: expected '{', found 'return'
./pkg/kubectl/resource_printer.go:984:6: expected '(', found 'IDENT' formatLabelHeaders
```

**Comment by mbforbes** [comment]
... but that code hasn't changed in two days so unless shippable is failing for everyone else... ? Very weird. I'm going to kick again.

**Comment by ixdy** [comment]
Pretty sure you've just hit a series of flakes today; LGTM otherwise.

@k8s-bot test this please

**Comment by mbforbes** [comment]
Today is not my day for CI.

**Comment by ixdy** [comment]
it's been a pretty bad day for CI all over, not just you...

**Comment by ixdy** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
@k8s-bot test this work, please

**Comment by mbforbes** [comment]
The cluster failed to turn up in Jenkins, never having touched this test:

```
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..................................................Build timed out (after 30 minutes). Marking the build as aborted.
```

**Comment by mbforbes** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
yeah, you were the lucky winner of #10868 probably.

**Comment by mbforbes** [comment]
All green! @roberthbailey can I get a label with that LGTM please? Also, who is another TL for an LGTM? @alex-mohr? @davidopp?

**Comment by ixdy** [comment]
LGTM too

**Comment by mbforbes** [comment]
BTW please hold off on merging, going to sanity check this a couple times manually (and looking at #11068 first)

**Comment by davidopp** [comment]
LGTM

Please feel free to apply the ok-to-merge label yourself once you are satisfied, assuming you haven't made any changes.

**Comment by mbforbes** [comment]
Ack, thank you!

**Comment by mbforbes** [comment]
Sorry for the delay—jumping around other issues. Checking now...

**Comment by mbforbes** [comment]
Verified manually:
```bash
$ make clean && make release-skip-tests
$ go run hack/e2e.go --up --down --v --test --test_args="--ginkgo.focus=Skipped.*Cluster\supgrade.*upgrade-cluster --upgrade-target=0.21.1" --check_version_skew=false
```

**Pull request merged**
