### PR TITLE
Updating the Reviewers / Approvers for WinKernel Proxier

### PR DESCRIPTION
**Pull request by kumarvin123**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Updates the owners and reviewers of Winkernel Proxier.

**Which issue(s) this PR fixes**:
None.

```release-note
None
```

### CODE REVIEW

**Comment by ksubrmnn** [comment]
Please update this PR to only include adding you to the owners file as I believe you are currently the only kubernetes org member

**Comment by ksubrmnn** [comment]
Please add release note NONE to the PR description

**Comment by kumarvin123** [comment]
> Please update this PR to only include adding you to the owners file as I believe you are currently the only kubernetes org member

Done. @ksubrmnn , Can you please approve this?

**Review by ksubrmnn — APPROVED** [review]

**Comment by kumarvin123** [comment]
@feiskyer , Can you please set the milestone to this PR?
/milestone v1.20

**Comment by liggitt** [comment]
this will be moved back into the milestone as part of the [phased reopen for 1.20 merges](https://docs.google.com/document/d/1yI7o7R2bOB7QtkHUFMHMb5XObiJmzIAnJPuxhdAX-CA/edit)

**Pull request merged**
