### PR TITLE
Switch mholt/caddy to use fork due to verify-godeps issue

### LINKED ISSUE #71177: verify.godeps and verify.staging-godeps failing in verify jobs on master and 1.13 branch
**Which jobs are failing**:
* [verify-master](https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify-master)
* [verify-1.13](https://k8s-testgrid.appspot.com/sig-release-1.13-blocking#verify-1.13)

**Which test(s) are failing**:
* verify godeps
* verify staging-godeps
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/3127

**Since when has it been failing**:
11/17 6am ish

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify-master

**Reason for failure**:
```# cd /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/mholt/caddy; git checkout 2de495001514ed50eac2e09f474c32d417100c5c
error: Your local changes to the following files would be overwritten by checkout:
	dist/CHANGES.txt
	dist/README.txt
Please commit your changes or stash them before you switch branches.
Aborting
godep: error downloading dep (github.com/mholt/caddy/caddyfile): exit status 1
godep: Error downloading some deps. Aborting restore and check.
!!! [1117 16:55:51] Call tree:
!!! [1117 16:55:51]  1: /go/src/k8s.io/kubernetes/build/../build/common.sh:518 kube::build::run_build_command_ex(...)
!!! [1117 16:55:51]  2: /go/src/k8s.io/kubernetes/build/run.sh:39 kube::build::run_build_command(...)```

```# cd /tmp/gopath.KZbghM/src/github.com/mholt/caddy; git checkout 2de495001514ed50eac2e09f474c32d417100c5c
error: Your local changes to the following files would be overwritten by checkout:
	dist/CHANGES.txt
	dist/README.txt
Please commit your changes or stash them before you switch branches.
Aborting
godep: error downloading dep (github.com/mholt/caddy/caddyfile): exit status 1
godep: Error downloading some deps. Aborting restore and check.
```

/kind failing-test
/sig testing
/assign @cblecker 
/priority critical-urgent
/milestone v1.13

/cc @jberkus @BenTheElder @mariantalla @mortent

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
https://github.com/mholt/caddy/pull/2345 introduced a change to master that prevents this dependency from cloning cleanly. As a result, verify-godeps hits an error after it clones master, as it can't checkout a previous commit after cloning.

Until master is fixed, verify-godeps will fail. This is particularly impacting as we gear towards a release. This PR swaps over to use a clone under my username that is exactly 3 commits behind the current master, so that we can checkout back to the same vendored commit.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71177

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
xref
https://github.com/kubernetes/kubernetes/issues/71177
https://github.com/mholt/caddy/pull/2345

**Comment by cblecker** [comment]
/hold

Might be quicker to fix upstream. This is still in the back pocket, as it's passing tests.

**Pull request closed without merging**
