### PR TITLE
Remove changes that accidentally sneaked in during a rebase.

### PR DESCRIPTION
**Pull request by madhusudancs**
```release-note
NONE
```

### CODE REVIEW

**Comment by shashidharatd** [comment]
/lgtm

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41872#-:-KdZkXssP5nHM178FyKv:b-8ks5qa)*

**Review by shashidharatd — APPROVED** [review]
/lgtm

**Comment by shashidharatd** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
@k8s-bot gci gce e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot gci gce e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot gci gce e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot gci gce e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot gci gce e2e test this

**Pull request merged**
