### PR TITLE
Automated cherry pick of #68786 on release 1.11

### LINKED ISSUE #73458: 1.11.7 still missing this commit: 4ca62e4f39c59ebe66a59685a8f020315dfd3016
**What happened**:
can not access the NodePort from outside cluster when kube-proxy is in ipvs mode.
**What you expected to happen**:
can access the NodePort from outside cluster when kube-proxy is in ipvs mode.
**How to reproduce it (as minimally and precisely as possible)**:
We test this using 1.11.6. and find the filterRules in ipvs mode is useless. We cherry pick this commit and problem solved. add this two rules in KUBE-FORWARD
```
-A KUBE-FORWARD -s 10.0.0.0/8 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.0.0.0/8 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```
/sig network
/area kube-proxy

### PR DESCRIPTION
**Pull request by rramkumar1**
/kind bug

Fixes #73458

```release-note
kube-proxy restores the *filter table when running in ipvs mode.
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by foxish** [comment]
Can you please add a relnote regarding the user-facing effect of this change? @rramkumar1

**Comment by rramkumar1** [comment]
@foxish Done

**Pull request merged**
