### PR TITLE
Update structured-merge-diff to v4.1.1

### PR DESCRIPTION
**Pull request by kevindelgado**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Updates dependency sigs.k8s.io/structured-merge-diff to v4.1.1

#### Does this PR introduce a user-facing change?

```release-note
Updates dependency sigs.k8s.io/structured-merge-diff to v4.1.1
```

### CODE REVIEW

**Comment by apelisse** [comment]
@liggitt I don't understand how `./hack/update-internal-modules.sh` is different from `update-vendor.sh`. And also, it looks like one has to run it after pinning a dependency, we should maybe mention it at the end of the script like we do for `update-vendor.sh`.

**Comment by liggitt** [comment]
if this is marked as a bug, might be helpful to note the bug that is being fixed

**Comment by apelisse** [comment]
Mostly fixes https://github.com/kubernetes-sigs/structured-merge-diff/issues/186

**Comment by kevindelgado** [comment]
Are we trying to get this in 1.21 @apelisse ?

**Comment by apelisse** [comment]
No, I'm preparing for v1.22

**Pull request merged**
