### PR TITLE
fix typo in ipvs proxier README

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:

Fix typo.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendotjs** [comment]
ping @andrewsykim @lbernail, it's very weird that @danwinship's `approve` label didn't take effect. Can you help to approve?  : )

**Comment by danwinship** [comment]
/approve
?

**Pull request merged**
