### PR TITLE
Changelog: mention kube-scheduler bits deprecation

### LINKED ISSUE #106885: kube-scheduler default port (breaking) change not mentioned in 1.23 changelog
### What happened?

It looks like default HTTPS port for kube-scheduler has changed from 10251 to 10259 between 1.22.4 and 1.23.0 releases and it has not been mentioned in the changelog.
```
I1208 11:30:46.202095       1 deprecated_insecure_serving.go:54] Serving healthz insecurely on [::]:10251
```

```
I1208 09:17:41.523334       1 secure_serving.go:200] Serving securely on [::]:10259
```

EDIT: Actually, I see now that 1.22.4 listens on 10259, but also on 10251 and 1.23.0 just stopped listening on 10251.

### What did you expect to happen?

Breaking changes to be included in the changelog.

### How can we reproduce it (as minimally and precisely as possible)?

With kube-prometheus-stack installed, with kube-scheduler scraping configured, upgrade kube-scheduler from 1.22.4 to 1.23.0.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ingvagabund**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Mention deprecation of certain bits in the kube-scheduler

#### Which issue(s) this PR fixes:

Fixes #106885

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by AuraSinis — APPROVED** [review]
reviewed, lgtm

**Comment by pacoxu** [comment]
@kubernetes/release-managers  for cherry-pick approval.

**Comment by liggitt** [comment]
I didn't notice this was against the 1.23 branch... can you also open it against `master`?

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/kubernetes/pull/107022

**Review by xmudrii — APPROVED** [review]
The `master` PR got merged, so merging this should be fine now.
/lgtm
/approve

**Pull request merged**
