### PR TITLE
WIP: Check network summary e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Checking if the test fails on `master` and trying to fix that.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
The failure has to be related to the machine itself as it seems. I'm trying to find a difference between the current failing runs and the [last successful one](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126213/pull-kubernetes-node-crio-cgrpv2-e2e/1824928809829273600)

- it's using the same CRI-O commit (1c04ca9768e535cf22017da6e6cee620bb3a6431)
- no changes in [summary_test.go in the past months](https://github.com/kubernetes/kubernetes/commits/master/test/e2e_node/summary_test.go)

**Comment by kannon92** [comment]
Yes, @bitoku modified this job to set drop_infra=true.

https://github.com/kubernetes/kubernetes/pull/126213#issuecomment-2294996921

https://github.com/kubernetes/test-infra/commit/6f15247688a7ced397428a6a64bdaa00c8d3b671

**Comment by haircommander** [comment]
I think we need a cadvisor bump to fix that. Something with https://github.com/google/cadvisor/pull/3565

**Comment by uablrek** [comment]
> I think we need a cadvisor bump to fix that. Something with https://github.com/google/cadvisor/pull/3565

Yes, that fix is not in K8s. Metrics fail without systemd in v1.30.3, v1.31.0 and master with crio version 1.29.2, but works with containerd.

I re-tested manual update as in https://github.com/google/cadvisor/pull/3565#issuecomment-2224988348, and it works for that K8s commit (v1.31.0-alpha.3.185+2d4514e1690dc5-dirty), **but it doesn't work on K8a master**! (v1.32.0-alpha.0.754+048c8536d6450c-dirty).

So _something else_ has been merged into K8s that breaks metrics for cri-o. At least for 1.29.2.

My crio version 1.29.2 is out of the skew-interval (I think). Shall I update crio and drop this if it works? I am only testing, so this is not urgent/important for me BTW.

**Comment by uablrek** [comment]
```
030f28e125740671f0bf68a5eae7f2d1a3818b2b is the first bad commit
commit 030f28e125740671f0bf68a5eae7f2d1a3818b2b
Author: Krzysztof Wilczyński <kwilczynski@redhat.com>
Date:   Fri Jul 19 01:38:03 2024 +0900

    KEP-4191: Split Image Filesystem promotion to Beta
    
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@redhat.com>

 pkg/features/kube_features.go | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)
bisect found first bad commit
```

**Comment by saschagrunert** [comment]
cc @kwilczynski

**Comment by kwilczynski** [comment]
> ```
> 030f28e125740671f0bf68a5eae7f2d1a3818b2b is the first bad commit
> commit 030f28e125740671f0bf68a5eae7f2d1a3818b2b
> Author: Krzysztof Wilczyński <kwilczynski@redhat.com>
> Date:   Fri Jul 19 01:38:03 2024 +0900
> 
>     KEP-4191: Split Image Filesystem promotion to Beta
>     
>     Signed-off-by: Krzysztof Wilczyński <kwilczynski@redhat.com>
> 
>  pkg/features/kube_features.go | 8 ++++++--
>  1 file changed, 6 insertions(+), 2 deletions(-)
> bisect found first bad commit
> ```

@uablrek, this commit just changes the default setting for a feature flag, so not sure what impact it would have here?

Related:

- https://github.com/kubernetes/kubernetes/pull/126205

If you drop it, does it fix the failing test? Would be interesting to see if there is a connection to the Split Image Filesystem.

**Comment by uablrek** [comment]
What's the feature-gate?

**Comment by uablrek** [comment]
Yes it works with `KubeletSeparateDiskGC=false`, and with manual cadvisor update https://github.com/google/cadvisor/pull/3565#issuecomment-2224988348 for crio version 1.29.2, and K8s master. (containerd works without any fixes)

**Comment by uablrek** [comment]
I tested with containerd v2.0.0-rc.4, which also works without fixes (used 1.7.11 before)

**Pull request closed without merging**
