### PR TITLE
Move InMemoryResponseWriter into own package

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Move InMemoryResponseWriter into own package. Fixes code duplication in 3 places.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/assign @jpbetz @sttts 
/cc @richabanker 

Not sure what the most idiomatic naming scheme is, open to suggestions. This is used both by openapi and discovery so I thought it didn't make sense to be a utility in either one of the packages and opted for a stand alone one.

**Comment by richabanker** [comment]
/lgtm
Thanks for the cleanup!

**Comment by sttts** [comment]
:+1:

**Pull request merged**
