### PR TITLE
Restructure cmd/kubeadm/OWNERS

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

After a year of virtually the same people in `cmd/kubeadm/OWNERS`, the SIG has decided to refresh the list of reviewers/approvers a little. If you feel more/other changes are needed yet, please speak up here in this thread, in our weekly SIG meeting or ping me on Slack.

Thanks all everyone that has helped out here and thanks to you who are stepping up more now!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews 

Please ACK that you are ok with this officially here as well:
@kad @timothysc @jamiehannaford @xiangpengzhao @lukemarsden @errordeveloper @mattmoyer @justinsb @fabriziopandini

### CODE REVIEW

**Comment by kad** [comment]
ACK. Thanks @luxas

**Comment by jamiehannaford** [comment]
ACK. Thanks!

**Comment by fabriziopandini** [comment]
ACK!

**Comment by xiangpengzhao** [comment]
ACK. Glad to be on the list and work with folks! Thanks @luxas !

/retest

**Comment by lukemarsden** [comment]
ack, I'll be back after paternity leave! 👶 ✨

**Review by timothysc — APPROVED** [review]
per discussion on the sig 

/lgtm 
/approve

**Pull request merged**
