### PR TITLE
Cherry pick of #93908: Updating EndpointSlice controllers to return i…

### PR DESCRIPTION
**Pull request by ping035627**
Cherry pick of #93908 on release-1.17.

#93908 : Updating EndpointSlice controllers to return if error encountered

For details on the cherry pick process, see the cherry pick requests page.

/sig network
/priority critical-urgent

### CODE REVIEW

**Comment by tpepper** [comment]
> Needs approval from an approver in each of these files:
> * **[pkg/controller/endpointslice/OWNERS](https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/controller/endpointslice/OWNERS)**

We need input from the applicable approvers.  The peer cherry pick on 1.18 is approved.  If the 1.17 variant was missed, please chase down lgtm/approve, otherwise if it was intentionally not approved please close.

**Comment by cpanato** [comment]
@wojtek-t @robscott can you please review this cherry pick as well? thanks!

**Comment by robscott** [comment]
I don't think it's quite as critical to pick this back to 1.17, but it seems low risk and potentially helpful for any alpha users.

/lgtm

**Comment by tpepper** [comment]
Given @wojtek-t 's commentary here I'm going to close this one and merge just https://github.com/kubernetes/kubernetes/pull/94097

**Pull request closed without merging**
