### PR TITLE
Support go 16 in gofmt

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
hmmm - it seems it is incompatible with Go 1.5 - that is strange...

**Comment by thockin** [comment]
Did the Go folks change the result of running gofmt again?

**Comment by wojtek-t** [comment]
>
Did the Go folks change the result of running gofmt again?

@thockin - it seems so
I worked around the problematic file, so that both 1.5 and 1.6 gofmt is now producing the same output for all files.

PTAL

**Comment by wojtek-t** [comment]
@eparis - FYI

**Comment by eparis** [comment]
I was wondering how I was going to handle that gofmt issue. LGTM

**Comment by wojtek-t** [comment]
>
I was wondering how I was going to handle that gofmt issue. LGTM

yeah - it's sad that gofmt is changing between versions...

**Pull request merged**
