### PR TITLE
fix kubemark e2e test script

### PR DESCRIPTION
**Pull request by mlmhl**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

**What this PR does / why we need it**:

We should iterate and print the arguments array `ARGS` correctly.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @mborsz 

Maciek - can you please take a look?

**Comment by mlmhl** [comment]
@wojtek-t  @shyamjvs  Could you approve this PR?

**Pull request merged**
