### PR TITLE
Add SataQiu to hack/ approvers

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Recently, I created an issue: #81657
This PR adds myself as an approver for `hack` to help approve the PRs related to `hack/.staticcheck_failures` as well as `hack/.shellcheck_failures` and `hack/spelling_failures`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @fejta

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/approve
/lgtm

Thanks for all the work in this space!

**Comment by RainbowMango** [comment]
Congratulations. That will hurry up PR process.

**Pull request merged**
