### PR TITLE
Add TLS conf for Go1.7

### LINKED ISSUE #33936: New fields in tls.Config in golang 1.7
When using go 1.7, `pkg/util/net/http_test.go` is failing with the following error:

```
--- FAIL: TestCloneTLSConfig (0.00s)
        http_test.go:72: New fields seen in http.Transport: [DynamicRecordSizingDisabled Renegotiation]
                Add to CopyClientTLSConfig if client-relevant, then add to expected list in TestCopyClientTLSConfig
FAIL
FAIL    k8s.io/kubernetes/pkg/util/net  0.007s
```

### PR DESCRIPTION
**Pull request by k82cn**
fixes #33936 / #38596

### CODE REVIEW

**Review by jessfraz — APPROVED** [review]

**Comment by k82cn** [comment]
PR for master at #39213 . PTAL

**Comment by k82cn** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Comment by thockin** [comment]
@k8s-bot verify test this

**Comment by thockin** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by k82cn** [comment]
@thockin , it seem we need to update `Copyright` from 2016 to 2017 :). Sample output of `./hack/update-codecgen.sh`, any comments?

```
diff --git a/federation/apis/federation/v1beta1/zz_generated.conversion.go b/federation/apis/federation/v1beta1/zz_generated.conversion.go
index f5caec409c..91b6b70460 100644
--- a/federation/apis/federation/v1beta1/zz_generated.conversion.go
+++ b/federation/apis/federation/v1beta1/zz_generated.conversion.go
@@ -1,7 +1,7 @@
 // +build !ignore_autogenerated

 /*
-Copyright 2016 The Kubernetes Authors.
+Copyright 2017 The Kubernetes Authors.
```

**Comment by k82cn** [comment]
@thockin , it seems we need to update `Copyright` from 2016 to 2017, any comments?

```
diff --git a/pkg/util/sets/string.go b/pkg/util/sets/string.go
index da66eaf8e7..baef7a6a2b 100644
--- a/pkg/util/sets/string.go
+++ b/pkg/util/sets/string.go
@@ -1,5 +1,5 @@
 /*
-Copyright 2016 The Kubernetes Authors.
+Copyright 2017 The Kubernetes Authors.
```

**Comment by thockin** [comment]
Rebase to upstream master - it's fixed there

**Comment by thockin** [comment]
oops, this is the release branch.  Ugh, what a mess.  @jessfraz - should we touch all the generated files to update dates (bogus_ or live with broken tests? :)

**Comment by jessfraz** [comment]
oh yeah I'll cherrypick the patch for the dates

**Comment by jessfraz** [comment]
ok i merged the pr to fix the dates

**Comment by jessfraz** [comment]
@k8s-bot verify test this please

**Comment by jessfraz** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jessfraz** [comment]
all green merging

**Pull request merged**
