### PR TITLE
Fix kubectl Stratigic Merge Patch compatibility

### LINKED ISSUE #36916: Fix kubectl strmrg patch compatibility
#35647 introduced a non-backwards compatible change in kubectl and uses the server version to fallback on the old behavior.  @smarterclayton noted that using the server version to drive client behavior is not acceptable because the server version may not be published, or there may be federated servers with different versions.

We need to work out a solution, which may include rolling back parts of the original change.

### PR DESCRIPTION
**Pull request by mengqiy**
As @smarterclayton pointed out in [comment1](https://github.com/kubernetes/kubernetes/pull/35647#pullrequestreview-8290820) and [comment2](https://github.com/kubernetes/kubernetes/pull/35647#pullrequestreview-8290847) in PR #35647,
we cannot assume the API servers publish version and they shares the same version.

This PR removes all the calls of GetServerSupportedSMPatchVersion().
Change the behavior of `apply` and `edit` to:
Retrying with the old patch version, if the new version fails.
Default other usage of SMPatch to the new version, since they don't update list of primitives.

fixes #36916

cc: @pwittrock @smarterclayton

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37038)

### CODE REVIEW

**Comment by pwittrock** [comment]
*[pkg/kubectl/cmd/apply.go, line 535 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038#-KWoaLCXglzmNUOFXym8:-KWoaLCXglzmNUOFXym9:b-de99g2) ([raw file](https://github.com/kubernetes/kubernetes/blob/f32696e7349c417526d9f243fd90960fc24b60ae/pkg/kubectl/cmd/apply.go#L535)):*
> ```Go
> 	// Compute a three way strategic merge patch to send to server.
> 	patch, err := strategicpatch.CreateThreeWayMergePatch(original, modified, current, versionedObject, p.overwrite, strategicpatch.SMPatchVersion_1_5)
> 	if err != nil {
> ```

Add a comment explaining this is failing to create a patch, not failing to send the patch.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038)*

**Comment by pwittrock** [comment]
*[pkg/kubectl/cmd/apply.go, line 541 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038#-KWoaSaouEN3-agywKbg:-KWoaSaouEN3-agywKbh:bx3r025) ([raw file](https://github.com/kubernetes/kubernetes/blob/f32696e7349c417526d9f243fd90960fc24b60ae/pkg/kubectl/cmd/apply.go#L541)):*
> ```Go
> 	_, err = p.helper.Patch(namespace, name, api.StrategicMergePatchType, patch)
> 	if err != nil {
> 		// Retry SMPatchVersion_1_0 when applying the SMPatchVersion_1_5 patch
> ```

// Because the failure may be due to the server not supporting the 1_5 version

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038)*

**Comment by pwittrock** [comment]
Looks good

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038#-:-KWodovCdeLwVSQAT2Xs:bsrfkwe)*

**Comment by dims** [comment]
@pwittrock @deads2k @ymqytw - Is this needed for 1.5? (cc @brendandburns)

**Comment by ymqytw** [comment]
@dims Yes.

**Comment by pwittrock** [comment]
@smarterclayton FYI, this is the change to work around the server not returning the version

**Comment by pwittrock** [comment]
Looks like some debug logic was added to the PR, so I will hold off on reviewing further

**Comment by ymqytw** [comment]
> Looks like some debug logic was added to the PR, so I will hold off on reviewing further

Sorry. I type one additional `a` when committing. I have removed them.

**Comment by smarterclayton** [comment]
Overall change looks good, thank you for refining.

**Comment by ymqytw** [comment]
@k8s-bot test this

**Comment by ymqytw** [comment]
@k8s-bot test this

**Comment by pwittrock** [comment]
:lgtm

---

Reviewed 2 of 2 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37038#-:-KWu412Ra0TR5DQ6SWi_:b-8eqf7b)*

**Comment by ymqytw** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by pwittrock** [comment]
>
W1118 17:01:13.023] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W1118 17:01:13.023]  name: u'operation-1479515969501-f154209e'
W1118 17:01:13.023]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W1118 17:01:13.023]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/operations/operation-1479515969501-f154209e'
W1118 17:01:13.023]  status: StatusValueValuesEnum(DONE, 3)
W1118 17:01:13.023]  statusMessage: u'Timed out waiting for cluster initialization. Cluster API may not be available.'
W1118 17:01:13.023]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/clusters/e2e-gke-agent-pr-11-0'
W1118 17:01:13.024]  zone: u'us-central1-f'>] finished with error: Timed out waiting for cluster initialization. Cluster API may not be available.
W1118 17:01:13.077] 2016/11/18 17:01:13 e2e.go:724: Step 'up' finished in 22m26.578217945s
W1118 17:01:13.078] 2016/11/18 17:01:13 e2e.go:722: Running: teardown

Some test failures seem unrelated to teh changes

**Comment by ymqytw** [comment]
After all the checks are green this round, I will rerun all the jenkins tests one more time to make sure we are not the cause.

**Pull request merged**
