### PR TITLE
kubectl: Fix golint warnings for plugins/*

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

We currently have an entry in `hack/.golint_failures` for `pkg/kubectl/plugins`. If we lint the files in `plugins/` then we can safely remove this entry.
 
`golint` emits the following warnings (only one of each type shown)
```
exported method EnvList.Slice should have comment or be unexported
error var IncompletePluginError should have name of the form ErrFoo
func name will be used as plugins.PluginsEnvVarPluginLoader by other packages, and that stutters; consider calling this EnvVarPluginLoader
```

This PR clears all `golint` warnings from `kubectl/plugins/`.

1. Remove entry from `hack/.golint_failures`
2. Add missing documentation to exported types and functions.
3. Rename error variables to `ErrFoo`.
4. Rename `PluginsEnvVarPluginLoader` to `KubectlPluginsPathPluginLoader` (mirrors env var name).
5. Rename `XDGDataPluginLoader` to `XDGDataDirsPluginLoader` (to make uniform change above).

**Special notes for your reviewer**:

Felt a bit dirty doing this cleanup because the code in `plugins/` is particularly clean and well written already.

**Release note**:

```release-note
NONE
```
/sig cli
/kind cleanup

### CODE REVIEW

**Comment by rootfs** [comment]
Here are my golint warning types:
```
 comment on  type Description should be of the form "Description ..." (with optional leading article)
 comment on  type Source should be of the form "Source ..." (with optional leading article)
 error var  should have name of the form ErrFoo
 exported const  should have comment or be unexported
 exported function  should have comment or be unexported
 exported method  should have comment or be unexported
 exported type  should have comment or be unexported
 exported var  should have comment or be unexported
 func name  be used as plugins.PluginsEnvVarPluginLoader by other packages, and that stutters; consider calling this EnvVarPluginLoader
```

**Comment by tcharding** [comment]
@rootfs can you please explain why you posted the lint output? I ask only in order to improve my future pull requests. thanks

**Comment by fabianofranz** [comment]
/lgtm
/approve no-issue

> Felt a bit dirty doing this cleanup because the code in plugins/ is particularly clean and well written already.

Thanks @tcharding, made my day.  :)

**Pull request merged**
