### PR TITLE
Add some unit tests in the belly of the kubelet

### PR DESCRIPTION
**Pull request by fire833**
This PR doesn't add too much, but I found a few methods that didn't have unit tests in the kubelet area of the code, so I figured I would add some.

This PR is still a WIP, will add to a few stub tests that I added soon.

#### What type of PR is this?

/kind unit-test
/kind cleanup

#### Which issue(s) this PR fixes:
Work for #109717 

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by s-kawamura-w664 — COMMENTED** [review]
Is this PR still WIP?
Let me make one comment, because the test fails in my envrionment.

**Comment by fire833** [comment]
> Is this PR still WIP? Let me make one comment, because the test fails in my envrionment.

It is not, I am done with this one. I updated that test case.

**Comment by fire833** [comment]
My goodness I screwed this up

**Pull request closed without merging**
