### PR TITLE
Move the check of presence of minMatchNum in EvenPodsSpreadPredicate

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In EvenPodsSpreadPredicate, after minMatchNum is retrieved, we should perform the presence check so that, in case constraint.TopologyKey is not in map, we can continue.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
I don't think it is worth doing this change. Having a variable set close to where it will be used is useful from readability point of view, at the same time this if statement should not really happen, and if it does it indicates a bug that should be fixed, not optimize the code to exit early.

**Comment by tedyu** [comment]
```
Having a variable set close to where it will be used is useful from readability point of view,
```
Agreed.
For the second point, I think once (though unlikely) such error is encountered, it should be surfaced ASAP.

**Comment by tedyu** [comment]
@Huang-Wei 
Can you take a look ?

**Comment by Huang-Wei** [comment]
I agree with @ahg-g. Code readability wins in this case, esp. that error usually doesn't happen.

/close

**Comment by tedyu** [comment]
I wonder if there is better way of conveying that certain error logs reflect bug in the code.
Since panic is not recommended, we should make it easier for developers and users to spot such scenario more easily.

**Pull request closed without merging**
