### PR TITLE
Graduate IndexedJob to stable

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind feature

/area conformance

#### What this PR does / why we need it:

- Lock feature gate to true and schedule for deletion in 1.26
- Remove checks on feature gate
- Graduate E2E test to Conformance

#### Which issue(s) this PR fixes:

Ref kubernetes/enhancements#2214

KEP update: kubernetes/enhancements#3113

#### Special notes for your reviewer:

The E2E test is not flaky: https://testgrid.k8s.io/sig-apps#gce&include-filter-by-regex=Indexed%20job

Indexed Jobs are more performant than NonIndexed Jobs: kubernetes/enhancements#3239

#### Does this PR introduce a user-facing change?

```release-note
Indexed Jobs graduates to stable
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: http://git.k8s.io/enhancements/keps/sig-apps/2214-indexed-job
- [Usage]: https://kubernetes.io/docs/tasks/job/indexed-parallel-processing-static/
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
@kubernetes/sig-architecture-pr-reviews @kubernetes/cncf-conformance-wg

/assign @soltysh 
for SIG Apps

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
are the scale tests mentioned in https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2214-indexed-job#beta---ga-graduation in place?

**Comment by liggitt** [comment]
/approve
for API doc change

**Comment by alculquicondor** [comment]
> are the scale tests mentioned in https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2214-indexed-job#beta---ga-graduation in place?

Yes, the results are included in the KEP.

**Comment by alculquicondor** [comment]
ah, I'm missing conformance

@dims could you assign someone?

**Comment by dims** [comment]
/assign @johnbelamaric @smarterclayton 

(for conformance approval)

**Comment by johnbelamaric** [comment]
The test grid link only shows green for the last couple days, results are missing before that. But I assume this test has been around for a long time?

**Comment by alculquicondor** [comment]
Yes, it has been there since 1.22 :)

**Pull request merged**
