### PR TITLE
Fix some golint failures of pkg/registry

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix some golint failures of pkg/registry:
- pkg/registry/admissionregistration/mutatingwebhookconfiguration/storage
- pkg/registry/admissionregistration/validatingwebhookconfiguration/storage
- pkg/registry/apps/daemonset/storage
- pkg/registry/autoscaling/horizontalpodautoscaler/storage
- pkg/registry/batch/cronjob/storage
- pkg/registry/batch/job/storage

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/unassign
not a reviewer for pkg/, and the hack change is just removing these files from the failures list, doesn't really need review.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
