### PR TITLE
Automated cherry pick of #97860: move all variables in sampleAndWaterMarkHistograms::innerSet

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #97860 on release-1.19.

#97860: move all variables in sampleAndWaterMarkHistograms::innerSet

Reason for cherry pick: Fixes https://github.com/kubernetes/kubernetes/issues/97685

**Does this PR introduce a user-facing change?**:

```release-note
Fixes a performance regression in 1.19 on ARM architectures computing priority and fairness metrics
```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]

**Review by hasheddan — APPROVED** [review]
/lgtm

@tkashem parent PR merged to `master` 18 days ago so I am guessing this needs CP on 1.20 also?

/hold

**Comment by tkashem** [comment]
> @tkashem parent PR merged to master 18 days ago so I am guessing this needs CP on 1.20 also?

@hasheddan 1.20 cherry-pick has already merged - https://github.com/kubernetes/kubernetes/pull/97866

**Comment by hasheddan** [comment]
@tkashem okay :+1: Please do your best to group cherry picks together when they need to go to multiple branches. This means the fix was in v1.20.2, but not v1.19.7, which went out the same day. Although from the context, it looks like it may not have been realized at the time that this was applicable to 1.19.

/hold cancel

**Pull request merged**
