### PR TITLE
Add lilic as SIG Instrumentation reviewer

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind cleanup
/sig instrumentation

#### What this PR does / why we need it:

Adds @lilic to SIG Instrumentation Reviewers :tada: 

#### Which issue(s) this PR fixes:

Follow-up to https://github.com/kubernetes/org/pull/2800

#### Special notes for your reviewer:

@lilic has been participating in SIG Instrumentation for many years, and is currently the subproject owner of kube-state-metrics. She is involved in many areas of instrumentation in the CNCF ecosystem and has been getting pinged to review more things in k/k lately for instrumentation.

Hence, I would like to propose recognizing @lilic as a reviewer.

/assign @logicalhan @dashpole @brancz @lilic 
/cc @serathius @RainbowMango

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

(non-binding!)

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve
😃

**Comment by lilic** [comment]
Thank you! 🙇‍♀️  🎉 
/lgtm from my side 😄

**Comment by ehashman** [comment]
I'll chase down a top-level approver.

**Comment by thockin** [comment]
/approve

thanks for being willing @lilic

**Pull request merged**
