### PR TITLE
Update swagger specs

### PR DESCRIPTION
**Pull request by fejta**
Trying to figure out why they got out of date in parallel.. maybe we missed this in https://github.com/kubernetes/kubernetes/pull/23806?

### CODE REVIEW

**Comment by lavalamp** [comment]
Aren't these checked by some verify-* scripts?

**Comment by lavalamp** [comment]
This looks like it might have something to do with changes @smarterclayton is working on.

**Comment by bgrant0607** [comment]
That doesn't look like legal swagger to me.

**Comment by bgrant0607** [comment]
More specifically: `*versioned.Event`

**Comment by fejta** [comment]
So... revert #23806 then?

@lavalamp yes `hooks/pre-commit` checks for this and @bgrant0607 this is what `hack/update-swagger-spec.sh` outputs after the hook runs and fails at head.

**Comment by lavalamp** [comment]
@fejta @nikhiljindal we shouldn't only be checking this in the precommit hook. It should be verified by some CI script, which should agree with the precommit hook. So if this is needed, why isn't everything failing CI?

**Comment by nikhiljindal** [comment]
`hack/verify-swagger-spec.sh` is supposed to verify that the swagger spec is updated.
I see that it did run for https://github.com/kubernetes/kubernetes/pull/23806 on jenkins but surprisingly passed.

**Comment by lavalamp** [comment]
It's passing for everything at head.

This PR is failing, but the verify script doesn't explain why and appears to claim that the swagger passes. I'll let @nikhiljindal figure out what is going on :)

**Comment by nikhiljindal** [comment]
Verified that `hack/verify-swagger-spec.sh` is broken on HEAD right now, so the CI tests should be failing?

@fejta You need to run `hack/update-api-reference-docs.sh` as well.

**Comment by nikhiljindal** [comment]
@lavalamp yes verify-swagger-spec is passing on this PR (since the spec is updated now).
Its verify-api-reference-docs which is failing.

**Comment by nikhiljindal** [comment]
Re: valid swagger spec, yes it does not look like a valid spec to me.
But running `swagger-tools validate` didnt generate any more errors than the existing one (https://github.com/kubernetes/kubernetes/issues/16748).

I am fine with merging this to fix broken HEAD.

**Comment by fejta** [comment]
@nikhiljindal repushed with files changed by `hack/update-api-reference-docs.sh`

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by smarterclayton** [comment]
I'll open a follow up on why it's outputting a pointer rather than
object as the type.

**Comment by nikhiljindal** [comment]
Fixed the release note label and added back the LGTM label.

Also filed https://github.com/kubernetes/kubernetes/issues/24240 to track removing the pointer from swagger spec.
Also filed https://github.com/kubernetes/kubernetes/issues/24233 to fix verify-swagger-spec on travis and jenkins.

**Pull request merged**
