### PR TITLE
Fix races in NodeController.

### LINKED ISSUE #13258: Node controller kills pods on a recently recovered node
This test is failing pretty frequently at head. It fails with the following message:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:567
Expected error:
    <*errors.errorString | 0xc2088f40b0>: {
        s: "failed to wait for pods responding: pod with UID 3a70b8fa-4ca9-11e5-8a57-42010af00443 is no longer a member of the replica set.  Must have been restarted for some reason.  Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-ag64m/pods 16793} []}",
    }
    failed to wait for pods responding: pod with UID 3a70b8fa-4ca9-11e5-8a57-42010af00443 is no longer a member of the replica set.  Must have been restarted for some reason.  Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-ag64m/pods 16793} []}
not to have occurred

@kubernetes/goog-testing @quinton-hoole @piosz @jszczepkowski

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #13258

### CODE REVIEW

**Comment by gmarek** [comment]
I run affected test 5 times, and it succeeded 5 times in a row.

**Comment by gmarek** [comment]
cc @smarterclayton @jszczepkowski @wojtek-t

**Comment by gmarek** [comment]
@k8s-bot test this please

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
