### PR TITLE
beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18 

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated

**Does this PR introduce a user-facing change?**:

```release-note
beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
#89460
#89461

### CODE REVIEW

**Comment by matthyx** [comment]
Hi @wawa0210 I see this label is present in some other files... would you mind making all these changes in the same PR?

**Comment by wawa0210** [comment]
> Hi @wawa0210 I see this label is present in some other files... would you mind making all these changes in the same PR?

I just modified everything involved, but they belong to different modules, for easy review, I mentioned different pr

**Comment by wawa0210** [comment]
https://github.com/kubernetes/kubernetes/issues/89477

**Pull request merged**
