### PR TITLE
KEP-3638: Promote plugin resolution to beta

### PR DESCRIPTION
**Pull request by ardaguclu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR promotes plugin subcommand resolution feature in kubectl to beta

#### Does this PR introduce a user-facing change?
```release-note
Promotes plugin subcommand resolution feature to beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3638
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold
for KEP approval

**Comment by ardaguclu** [comment]
unrelated failure;
/retest

**Comment by ardaguclu** [comment]
Since KEP is merged;
/hold cancel

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
