### PR TITLE
cleanup dot imports and make test error checking more readable in test/e2e/scheduling

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup
/sig testing

**What this PR does / why we need it**:

in test/e2e/scheduling:
1. cleanup dot imports
2. make test error checking more readable

**Which issue(s) this PR fixes**:

Part of #68026

**Special notes for your reviewer**:

/assign @oomichi 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
This should be a part of https://github.com/kubernetes/kubernetes/issues/68026 not https://github.com/kubernetes/kubernetes/issues/77706

**Review by ravisantoshgudimetla — COMMENTED** [review]
I am fine with these changes. Is this something sig-testing is doing across board?

/cc @spiffxp

**Comment by spiffxp** [comment]
/hold
is there an umbrella issue for moving everything to use ginkgo / gomega?

**Comment by oomichi** [comment]
@spiffxp That is a nice point. We are working for using ginkgo/gomega under https://github.com/kubernetes/kubernetes/issues/68026

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/issues/68026 is about golint in general.  I'd rather see something that address all of the golint failures for a given file and remove it from our list of exclusions if that's the case

This seems very mechanical and driven to game PR metrics

**Comment by danielqsj** [comment]
> This should be a part of #68026 not #77706

Addressed. Thanks.

**Comment by spiffxp** [comment]
Can you please address the remainder of the golint failures and remove these files from `hack/.golint_failures`?

**Comment by oomichi** [comment]
> Can you please address the remainder of the golint failures and remove these files from hack/.golint_failures?

++ It is not necessary to take more PRs for fixing that.

**Comment by danielqsj** [comment]
fix the remaining golint error, PTAL @oomichi @spiffxp

**Comment by spiffxp** [comment]
/approve
/lgtm
Thanks for iterating on this @danielqsj

**Pull request merged**
