### PR TITLE
Bump metadata proxy to v0.1.9

### PR DESCRIPTION
**Pull request by ikehz**
**What this PR does / why we need it**: Bump GCE metadata proxy to v1.9 to pick up GoogleCloudPlatform/k8s-metadata-proxy#15.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump GCE metadata proxy to v0.1.9 to pick up security fixes.
```

### CODE REVIEW

**Comment by ihmccreery** [comment]
(These tests won't pass until https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/16 is in & I've cut the new version.)

**Comment by zouyee** [comment]
duplicate https://github.com/kubernetes/kubernetes/pull/57928

**Comment by ihmccreery** [comment]
@zouyee, how is this a duplicate of #57928?

**Comment by ihmccreery** [comment]
v0.1.8 is out

/retest

**Comment by ihmccreery** [comment]
/assign @bowei

I can't seem to get in touch with @vishh.

**Pull request merged**
