### PR TITLE
Update examples/k8petstore to v1

### PR DESCRIPTION
**Pull request by caesarxuchao**
update the json files in k8petstore.sh to v1;
because the publicIP field in service is not supported in v1, the frontend service is now updated to use a load balancer.
#9286

@jayunit100 @jlowdermilk @krousey  @nikhiljindal  @bgrant0607

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The link to arch.dot is dead, @jayunit100 could you take a look? Thanks.

**Comment by jayunit100** [comment]
hey thanks for finding this.   im fine with the changes so long as `k8petstore.sh` runs out of the box.

**Comment by jayunit100** [comment]
@caesarxuchao ah yes, its actually `k8petstore.dot` .  the name of the file changed.  that should be fixed to !

**Comment by ixdy** [comment]
Note to whoever reviews: the "Jenkins builder" check will not finish, since I changed the name to "Jenkins GCE e2e" while the test was running. (Note that "Jenkins GCE e2e" succeeded.)

**Comment by jayunit100** [comment]
@caesarxuchao @eparis can you clarify "because the publicIP field in service is not supported in v1, the frontend service is now updated to use a load balancer."  ... that **big** is news to me ?

**Comment by krousey** [comment]
Just to copy my response from the external mailing list in case people only see this.

I believe the intended replacement for publicIPs is the service type of NodePort.

As noted here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md#v1-conversion-tips-from-v1beta3, publicIPs and createExternalLoadBalancer were removed in favor of using service types of ClusterIP, NodePort, or LoadBalancer documented here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#external-services. 

The functionality of NodePort doesn't seem to be identical to publicIPs, but there is a note on the API conversion tips to contact @thockin if you think it doesn't satisfy your use case. He would really be able to explain what is going on here. Hope this helps.

**Comment by krousey** [comment]
With that being said, maybe we should have an example using NodePort instead of LoadBalancer.

**Comment by jayunit100** [comment]
Yeah, lets do it in here ? @krousey can we change this PR to use NodePorts ?

**Comment by caesarxuchao** [comment]
Hi @jayunit100 @krousey, at first I also wanted to use NodePorts in this example, but I can't figure out how to do this step in the script for arbitrary cloud platforms:

"This gives developers the freedom to set up their own load balancers, to configure cloud environments that are not fully supported by Kubernetes, or even to just expose one or more nodes' IPs directly." (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#external-services)

**Comment by jayunit100** [comment]
@caesarxuchao then, in the interim, do you like the idea of moving the changes into a brand new script, we'll call it k8petstore1x.sh ...... That way we can merge this, with the intent of deprecating k8petstore.sh as soon as 1x is generally available ?   

Or should we just shift to 1x now ?  Im open to either option.  but just think we should support publicIPs until there is a clear alternative implemented.

**Comment by krousey** [comment]
@brendandburns How should this work with NodePort?

**Comment by caesarxuchao** [comment]
Hi @jayunit100 @krousey, I'm afraid the original k8petstore.sh doesn't work on a cloud cluster. The publicIP does NOT really create a public IP. The user needs to make the specified IP public manually. I tried the original script on a GCE cluster and I cannot connect to the public IP.

I think we should accept this PR, and make another PR to add a script that works for NodePort. What do you think?

**Comment by eparis** [comment]
publicIPs never created an IP.  publicIPs configured the proxy/iptables so that IPs which were already existing in your infrastructure were functional.

I'm perfectly happy if there is a better new way to do it, but I need to see what that is...

**Comment by jayunit100** [comment]
Can we add keep the old k8petstore.sh , and make your cloud one a new file k8petstorev1.sh? That way it's backward compatible for the time being .

**Comment by caesarxuchao** [comment]
Hi @eparis, thank you for the explanation. The name "Public IP" is confusing. Neither the README nor the comments in the k8spetstore.sh indicate that the user needs configure the IP themselves. I guess this is a reason why this API got deprecated. 

@jayunit100, ok, I will make it a separate file and modify the README accordingly. I will also add a line in README to remind people they need to configure public IP themselves.

I think we can update the original script to use NodePort later. I think NodePort is very similar to "publicIP".

What do you think?

**Comment by jayunit100** [comment]
sounds great ! ... but like eric said.... remember that, in a normal VM or machine with the regular old flannel and public network setup, publicIP works automatically.  CloudProviders are the exception, because they usually cant do networky operations easily.    So i dont think we should say you need to "set up" a public ip .

**Comment by caesarxuchao** [comment]
Hi @jayunit100, thanks for the explanation! Then how about something like this: "if you are running k8s on a cloud platform, then you need to configure the publicIP manually to make it public..." ?

**Comment by eparis** [comment]
Also should point out, publicIP worked just fine on most/all cloud infrastructures.  you set the publicIP to the IP of any VM (the ACTUAL IP of the VM, not the 'public ip of the vm' typically reported by cloud provider consoles). And things just worked...

**Comment by jayunit100** [comment]
@caesarxuchao im not too worried about the exact phrasing of the readme.  we can iterate later. go for it, and thanks for noticing this change.  @eparis thats a good point - alot of cloud VMs already have a reserved outward ip, so it really isnt a problem in that case .

**Comment by caesarxuchao** [comment]
Thank you @eparis @jayunit100. My understanding is, in case of running on a cloud, a user cannot supply an arbitrary IP address to the publicIP field. It either has to be an IP that has been reserved/configured by the cloud as an outward IP, or has to be configured by the user later, am I right?

**Comment by eparis** [comment]
to get the old publicIPs working you needed 2 things.

1. the publicIP had to be set that the ACTUAL ip assigned to a machine where the kube-proxy was running (or was going to be assigned to a machine where the kube-proxy was running in the future)
2. people had to have some way to eventually reach that IP.

For places (like digital ocean) where the IP of a machine on the internet was the same as the IP assigned to your VM this was easy.
For things like AWS where you VM was assigned an 'internal IP' and an 'external IP' you had to (confusingly) set the kubernetes publicIP == 'internal ip' then others would connect via the AWS public ip.

Anyway, I want to know how the nodePort thing works...

**Comment by caesarxuchao** [comment]
Thank you so much @eparis. I just tested it on GCE. You are right, I need to pass the "internal IP" of a node to "publicIP", and then access the service on "external IP:3000". It's a bad user experience : (

**Comment by caesarxuchao** [comment]
Hi @jayunit100 @eparis , I updated it. Now there are two scripts, k8petstore.sh and k8petstore-loadbalancer.sh. PTAL. Thanks.

I will try the NodePort and will let you know.

**Comment by caesarxuchao** [comment]
I tried NodePort. It's very similar to PublicIP, except that you don't need to specify an IP. As stated in the doc, it will create ports on each node that allow external access to the service. I tried it on GCE, you can access the service on any minion node's IP address at services/frontend.spec.ports[*].nodePort.

**Comment by jayunit100** [comment]
thanks @caesarxuchao  thats very good to know.  we can  update  #8145 accordingly also.

**Comment by brendandburns** [comment]
This LGTM to me.  @jayunit100 do you want to update this for NodePort, or merge it as is?

**Comment by caesarxuchao** [comment]
@jayunit100 @brendanburns  I'm writing a script for NodePort. Probably I will push a commit today.

**Comment by caesarxuchao** [comment]
I just noticed @brendandburns gave an LGTM. I will make the second commit a separate PR.

**Comment by jayunit100** [comment]
sounds great ! thanks for all this !

**Pull request merged**
