### PR TITLE
Remove cmd/integration test

### LINKED ISSUE #24440: RFC: Deprecate cmd/integration/integration.go
The integration test is hard to debug -- it runs tests concurrently with interspersed logs. I doubt that it's catching any bug that neither unit test nor a e2e test can catch, and both unit and e2e tests are easier to debug.
I'd vote for deprecating this file and remove/move all the tests. Any objections?

Here is a list of tests that it curretnly runs: 
https://github.com/kubernetes/kubernetes/blob/f0c33d65b6fea84d791059d96c93a15e4b3de4ec/cmd/integration/integration.go#L1022
```
		runReplicationControllerTest,
		runAtomicPutTest,
		runPatchTest,
		runServiceTest,
		runAPIVersionsTest,
		runMasterServiceTest,
		func(c *client.Client) {
			runSelfLinkTestOnNamespace(c, api.NamespaceDefault)
			runSelfLinkTestOnNamespace(c, "other")
		},
```

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #24440

After few cleanup PRs:
https://github.com/kubernetes/kubernetes/pull/27182
https://github.com/kubernetes/kubernetes/pull/27535
https://github.com/kubernetes/kubernetes/pull/26016

The only things that are being tested here is:
- starting master components without any verification (so if it didn't start, it will still work :P)
- checking if kubelet is starting containers from http manifest.

The latter is already tested in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/http_test.go#L54

So the test is now useless, at the same time, significantly increasing time spent on integration tests.

@lavalamp @mikedanese @spxtr @fejta

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek

**Comment by spxtr** [comment]
This is awesome.

**Comment by wojtek-t** [comment]
friendly ping - can someone please take a look?

**Comment by spxtr** [comment]
@jlowdermilk might also be interested.

**Comment by jlowdermilk** [comment]
lgtm +1000

**Pull request merged**
