### PR TITLE
Revert #76586, restructure LICENSES file generation

### LINKED ISSUE #85196: [Failing test] gce-cos-master-alpha-features (ci-kubernetes-e2e-gci-gce-alpha-features)
**Which jobs are failing**:
gce-cos-master-alpha-features
conformance-GCE-master
skew-cluster-latest-kubectl-stable1-gce
gci-gce-ingress
gce-cos-master-scalability-100

**Which test(s) are failing**:
test start up

**Since when has it been failing**:
12th November 23:16 PST

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

**Reason for failure**:

```
W1113 09:05:35.030] Failed to execute 'curl -s  http://127.0.0.1:4002/v2/members/$(curl -s  http://127.0.0.1:4002/v2/members -XGET | sed 's/{\"id/\n/g' | grep bootstrap-e2e-master\" | cut -f 3 -d \") -XDELETE -L 2>/dev/null' on bootstrap-e2e-master despite 5 attempts
W1113 09:05:35.030] Last attempt failed with: 
W1113 09:05:39.900] Updated [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/zones/us-west1-b/instances/bootstrap-e2e-master].
W1113 09:06:44.042] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/zones/us-west1-b/instances/bootstrap-e2e-master].
W1113 09:07:00.168] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-master-https].
W1113 09:07:02.255] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-minion-all].
W1113 09:07:06.404] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-master-etcd].
W1113 09:07:12.867] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/regions/us-west1/addresses/bootstrap-e2e-master-ip].
W1113 09:07:31.322] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-default-internal-master].
W1113 09:07:32.079] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-default-internal-node].
W1113 09:07:33.401] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/firewalls/bootstrap-e2e-default-ssh].
I1113 09:07:34.497] Deleting firewall rules remaining in network bootstrap-e2e: 
W1113 09:08:30.754] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-boskos-gce-project-16/global/networks/bootstrap-e2e].
W1113 09:08:31.142] W1113 09:08:31.140186    9616 loader.go:223] Config not found: /workspace/.kube/config
I1113 09:08:31.407] Property "clusters.k8s-boskos-gce-project-16_bootstrap-e2e" unset.
W1113 09:08:31.509] W1113 09:08:31.407002    9663 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:31.509] W1113 09:08:31.407293    9663 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:31.645] W1113 09:08:31.645324    9710 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:31.646] W1113 09:08:31.646206    9710 loader.go:223] Config not found: /workspace/.kube/config
I1113 09:08:31.747] Property "users.k8s-boskos-gce-project-16_bootstrap-e2e" unset.
W1113 09:08:31.856] W1113 09:08:31.856358    9758 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:31.857] W1113 09:08:31.857260    9758 loader.go:223] Config not found: /workspace/.kube/config
I1113 09:08:31.959] Property "users.k8s-boskos-gce-project-16_bootstrap-e2e-basic-auth" unset.
I1113 09:08:32.099] Property "contexts.k8s-boskos-gce-project-16_bootstrap-e2e" unset.
I1113 09:08:32.102] Cleared config for k8s-boskos-gce-project-16_bootstrap-e2e from /workspace/.kube/config
I1113 09:08:32.103] Done
W1113 09:08:32.203] W1113 09:08:32.097713    9804 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:32.204] W1113 09:08:32.098096    9804 loader.go:223] Config not found: /workspace/.kube/config
W1113 09:08:32.204] 2019/11/13 09:08:32 process.go:155: Step './hack/e2e-internal/e2e-down.sh' finished in 7m13.536227968s
W1113 09:08:32.205] 2019/11/13 09:08:32 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W1113 09:08:37.490] 2019/11/13 09:08:37 main.go:319: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 2
W1113 09:08:37.490] Traceback (most recent call last):
W1113 09:08:37.491]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 778, in <module>
W1113 09:08:37.493]     main(parse_args())
W1113 09:08:37.493]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 626, in main
W1113 09:08:37.493]     mode.start(runner_args)
W1113 09:08:37.494]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W1113 09:08:37.494]     check_env(env, self.command, *args)
W1113 09:08:37.494]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W1113 09:08:37.494]     subprocess.check_call(cmd, env=env)
W1113 09:08:37.494]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1113 09:08:37.495]     raise CalledProcessError(retcode, cmd)
W1113 09:08:37.496] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--runtime-config=api/all=true', '--test_args=--ginkgo.focus=\\[Feature:(Audit|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes|RunAsGroup|TTLAfterFinished|NodeLease|VolumeSnapshotDataSource|CSIInlineVolume)\\]|Networking --ginkgo.skip=Networking-Performance|IPv6|Feature:Volumes|csi-hostpath-v0 --minStartupPods=8', '--timeout=180m')' returned non-zero exit status 1
E1113 09:08:37.505] Command failed
```

**Anything else we need to know**:
/sig testing
/milestone v1.17

/priority critical-urgent

/cc @droslean  @hasheddan @alejandrox1

### LINKED ISSUE #85213: [Failing Test] gce-cos-master-default (ci-kubernetes-e2e-gci-gce)
**Which jobs are failing**:
`gce-cos-master-default (ci-kubernetes-e2e-gci-gce)`

**Since when has it been failing**:
`13th Nov 22:46 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default

**Reason for failure**:
```console
 W1113 13:46:56.575] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:46:56.576] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:46:56.577] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:46:56.577] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:46:56.577] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:46:56.581] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:46:57.011] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:46:57.011] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:46:57.011] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:46:57.011] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:46:57.011] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:46:57.012] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:46:57.403] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:46:57.404] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:46:57.404] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:46:57.404] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:46:57.404] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:46:57.406] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:46:57.577] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:46:57.577] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:46:57.577] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:46:57.577] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:46:57.578] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:46:57.581] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:47:00.749] INSTANCE_GROUPS=bootstrap-e2e-minion-group
W1113 13:47:00.750] NODE_NAMES=bootstrap-e2e-minion-group-7g14 bootstrap-e2e-minion-group-d8w2 bootstrap-e2e-minion-group-hnng bootstrap-e2e-minion-group-pnlw
I1113 13:47:01.731] Failures for bootstrap-e2e-minion-group (if any):
W1113 13:47:02.641] 2019/11/13 13:47:02 process.go:155: Step './cluster/log-dump/log-dump.sh /workspace/_artifacts' finished in 1m31.948444385s
W1113 13:47:02.642] 2019/11/13 13:47:02 process.go:153: Running: ./hack/e2e-internal/e2e-down.sh
W1113 13:53:40.750]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W1113 13:53:40.750]     subprocess.check_call(cmd, env=env)
W1113 13:53:40.750]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1113 13:53:40.750]     raise CalledProcessError(retcode, cmd)
W1113 13:53:40.751] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-master-image=gci', '--gcp-node-image=gci', '--gcp-nodes=4', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--publish=gs://kubernetes-release-dev/ci/latest-green.txt', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=50m')' returned non-zero exit status 1
E1113 13:53:40.759] Command failed 
```

**Anything else we need to know**:
/cc @alenkacz @hasheddan @alejandrox1 
/sig cluster-lifecycle
/priority critical-urgent

### LINKED ISSUE #85214: [Failing Test] gce-cos-master-reboot (ci-kubernetes-e2e-gci-gce-reboot)
**Which jobs are failing**:
`gce-cos-master-reboot (ci-kubernetes-e2e-gci-gce-reboot)`

**Since when has it been failing**:
`13th Nov 23:41 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-reboot

**Reason for failure**:
```console
 W1113 13:32:33.931] scp: /var/log/cluster-autoscaler.log*: No such file or directory
W1113 13:32:33.931] scp: /var/log/kube-addon-manager.log*: No such file or directory
W1113 13:32:33.931] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:32:33.931] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:32:33.932] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:32:33.937] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
I1113 13:32:34.037] Dumping logs from nodes locally to '/workspace/_artifacts'
I1113 13:32:34.038] Detecting nodes in the cluster
I1113 13:33:52.498] Changing logfiles to be world-readable for download
I1113 13:33:53.002] Changing logfiles to be world-readable for download
I1113 13:33:54.016] Changing logfiles to be world-readable for download
W1113 13:34:24.439] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:34:24.440] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:34:24.440] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:34:24.441] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:34:24.442] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:34:24.448] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:34:28.936] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:34:28.997] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:34:29.051] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:34:29.227] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:34:29.299] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:34:29.410] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:34:29.604] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 13:34:29.618] scp: /var/log/fluentd.log*: No such file or directory
W1113 13:34:29.665] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 13:34:29.673] scp: /var/log/kubelet.cov*: No such file or directory
W1113 13:34:29.674] scp: /var/log/startupscript.log*: No such file or directory
W1113 13:34:30.247] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 13:35:09.250] INSTANCE_GROUPS=err-e2e-minion-group
W1113 13:35:09.251] NODE_NAMES=err-e2e-minion-group-2mhk err-e2e-minion-group-85xv err-e2e-minion-group-nqwr
I1113 13:35:16.629] Failures for err-e2e-minion-group (if any):
W1113 13:35:20.683] 2019/11/13 13:35:20 process.go:155: Step './cluster/log-dump/log-dump.sh /workspace/_artifacts' finished in 3m27.690020477s
W1113 13:35:20.733] 2019/11/13 13:35:20 process.go:153: Running: ./hack/e2e-internal/e2e-down.sh
W1113 13:42:24.749]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W1113 13:42:24.749]     subprocess.check_call(cmd, env=env)
W1113 13:42:24.749]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1113 13:42:24.750]     raise CalledProcessError(retcode, cmd)
W1113 13:42:24.751] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=err-e2e', '--gcp-network=err-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--test_args=--ginkgo.focus=\\[Feature:Reboot\\] --minStartupPods=8', '--timeout=180m')' returned non-zero exit status 1 
```

**Anything else we need to know**:
/cc @alenkacz @hasheddan @alejandrox1 
/sig cluster-lifecycle
/milestone v1.17
/priority critical-urgent

### LINKED ISSUE #85215: [Failing Test] gce-cos-master-slow (ci-kubernetes-e2e-gci-gce-slow)
**Which jobs are failing**:
`gce-cos-master-slow (ci-kubernetes-e2e-gci-gce-slow)`

**Since when has it been failing**:
`12th Nov 23:08 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-slow

**Reason for failure**:
```console
 W1113 14:32:49.037] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 14:32:49.037] scp: /var/log/fluentd.log*: No such file or directory
W1113 14:32:49.037] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 14:32:49.038] scp: /var/log/kubelet.cov*: No such file or directory
W1113 14:32:49.038] scp: /var/log/startupscript.log*: No such file or directory
W1113 14:32:49.048] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 14:32:49.864] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 14:32:49.864] scp: /var/log/fluentd.log*: No such file or directory
W1113 14:32:49.864] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 14:32:49.865] scp: /var/log/kubelet.cov*: No such file or directory
W1113 14:32:49.865] scp: /var/log/startupscript.log*: No such file or directory
W1113 14:32:49.867] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 14:32:51.202] scp: /var/log/kube-proxy.log*: No such file or directory
W1113 14:32:51.202] scp: /var/log/fluentd.log*: No such file or directory
W1113 14:32:51.203] scp: /var/log/node-problem-detector.log*: No such file or directory
W1113 14:32:51.203] scp: /var/log/kubelet.cov*: No such file or directory
W1113 14:32:51.203] scp: /var/log/startupscript.log*: No such file or directory
W1113 14:32:51.206] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
W1113 14:32:56.151] INSTANCE_GROUPS=bootstrap-e2e-minion-group
W1113 14:32:56.152] NODE_NAMES=bootstrap-e2e-minion-group-50w4 bootstrap-e2e-minion-group-gw0p bootstrap-e2e-minion-group-j898
I1113 14:32:57.717] Failures for bootstrap-e2e-minion-group (if any):
W1113 14:32:59.458] 2019/11/13 14:32:59 process.go:155: Step './cluster/log-dump/log-dump.sh /workspace/_artifacts' finished in 2m23.140729534s
W1113 14:32:59.459] 2019/11/13 14:32:59 process.go:153: Running: ./hack/e2e-internal/e2e-down.sh
W1113 14:39:32.993]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W1113 14:39:32.994]     subprocess.check_call(cmd, env=env)
W1113 14:39:32.994]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1113 14:39:32.994]     raise CalledProcessError(retcode, cmd)
W1113 14:39:32.995] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-master-image=gci', '--gcp-node-image=gci', '--gcp-zone=europe-west1-c', '--ginkgo-parallel=25', '--test_args=--ginkgo.focus=\\[Slow\\] --ginkgo.skip=\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=150m')' returned non-zero exit status 1 
```
**Anything else we need to know**:
/cc @alenkacz @hasheddan @alejandrox1 
/milestone v1.17
/priority critical-urgent
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Reverts LICENSES change until https://github.com/kubernetes/kubernetes/pull/76586/files#r345786033 is resolved

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/85215 
Fixes https://github.com/kubernetes/kubernetes/issues/85214 
Fixes https://github.com/kubernetes/kubernetes/issues/85213 
Fixes https://github.com/kubernetes/kubernetes/issues/85196

```release-note
NONE
```

/cc @dims @thockin @JishanXing

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/hold

for CI to go green

**Comment by dims** [comment]
cc @JishanXing

**Comment by liggitt** [comment]
/test pull-kubernetes-e2e-gce-alpha-features

just to check

**Comment by liggitt** [comment]
pull-kubernetes-node-e2e-containerd failure is preexisting and is https://github.com/kubernetes/kubernetes/issues/85040

**Comment by oxddr** [comment]
@liggitt - can we have this PR cherry-picked to v1.17 branch - it broke scalability tests there too: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-1.17-scalability-100

**Comment by liggitt** [comment]
this will get included in 1.17 in the daily fast-forward of the branch, no cherry-pick needed

**Pull request merged**
