### PR TITLE
Fix IP field name and add namespace support in Cassandra example

### LINKED ISSUE #10034: Cassandra's KubernetesSeedProvider works only with the default namespace
The namespace seems to be hard coded [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java#L105):

```java
        String host = "https://kubernetes.default.cluster.local";
        String serviceName = getEnvOrDefault("CASSANDRA_SERVICE", "cassandra");
        String path = "/api/v1/namespaces/default/endpoints/";
        try {
            String token = getServiceAccountToken();

            SSLContext ctx = SSLContext.getInstance("SSL");
            ctx.init(null, trustAll, new SecureRandom());
```

### PR DESCRIPTION
**Pull request by mwielgus**
Fixes IP field name in `KubernetesSeedProvider.java` (ip must be in lowercase) and almost fixes #10034 (the new version of the image needs to be pushed to `gcr.io/google_containers`).
`kubernetes-cassandra.jar` was built with jdk 1.7.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR!  I would like to double check this myself, and then this is good to merge.

--brendan

**Comment by glerchundi** [comment]
@mwielgus I'm not sure but, maybe you should use the namespace in url too? Something like this:

```
        String podNamespace = getEnvOrDefault("POD_NAMESPACE", "default");
        String host = String.format("https://kubernetes.%s.cluster.local", podNamespace);
        String serviceName = getEnvOrDefault("CASSANDRA_SERVICE", "cassandra");
        String path = String.format("/api/v1/namespaces/%s/endpoints/", podNamespace);
```

**Comment by mwielgus** [comment]
It works without this. And, at least on my cluster, kubernetes service is in the default namespace.

**Comment by mwielgus** [comment]
@brendanburns is it good to go?

**Comment by gmarek** [comment]
LGTM, @quinton-hoole can you take a look?

**Comment by quinton-hoole** [comment]
I'm happy to take a look when I have time, but it's not at the top of my priority list right now.  Give the U.S. vacation, it might only happen next week.

**Comment by mwielgus** [comment]
Ping :)

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
