### PR TITLE
remove confusing, dead code from master.go

### PR DESCRIPTION
**Pull request by deads2k**
Found while chasing something else, looks completely dead.

### CODE REVIEW

**Comment by MHBauer** [comment]
Looks dead to me.

**Comment by deads2k** [comment]
@caesarxuchao @nikhiljindal significant dead code cleanup.  Looks like discovery ran through here at one point.

**Comment by caesarxuchao** [comment]
Yeah, I think it's deprecated after introducing the generic APIServer. LGTM. Thanks.

**Comment by lavalamp** [comment]
@deads2k @caesarxuchao Please remember to apply retest-not-required for changes like this, thanks.

**Pull request merged**
