### PR TITLE
upgrade flannel to 0.5.3 for ubuntu

### PR DESCRIPTION
**Pull request by dalanlan**
- upgrade flannel to a higher release to get rid of potential bugs
- tear down cluster gracefully

### CODE REVIEW

**Comment by dalanlan** [comment]
ping @zmerlynn

**Comment by dalanlan** [comment]
ping @zmerlynn 
Could you please kindly review this?

**Comment by dalanlan** [comment]
Not sure whether @zmerlynn  is available for reviewing this. 
Since this patch could block #15059, ping again:)

**Comment by zmerlynn** [comment]
Backlogged, sorry.

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
