### PR TITLE
Bumped the number of times a node tries to lookup itself

### LINKED ISSUE #81879: kube-proxy gives up too soon waiting for node registration in hack/local-up-cluster.sh
**What happened**:
I checked out the latest `master` branch and tried `hack/local-up-cluster.sh`.  The kube-proxy gave up on trying to lookup the node, 4 second before the node registered itself.

```
mspreitz@mjs-dev-1:~/go/src/k8s.io/kubernetes$ git status
On branch master
Your branch is up to date with 'upstream/master'.

nothing to commit, working tree clean

mspreitz@mjs-dev-1:~/go/src/k8s.io/kubernetes$ git rev-parse HEAD
d2e2337744072553ae7756ba972607ffb6532a85

mspreitz@mjs-dev-1:~/go/src/k8s.io/kubernetes$ LOG_LEVEL=7 hack/local-up-cluster.sh
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap.
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory '/home/mspreitz/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/mspreitz/go/src/k8s.io/kubernetes'
make[1]: Leaving directory '/home/mspreitz/go/src/k8s.io/kubernetes'
+++ [0823 23:55:31] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
make: Leaving directory '/home/mspreitz/go/src/k8s.io/kubernetes'
WARNING: No swap limit support
Kubelet cgroup driver defaulted to use: cgroupfs
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...

...

kubelet ( 8040 ) is running.
Create default storage class for 
storageclass.storage.k8s.io/standard created
Local Kubernetes cluster is running. Press Ctrl-C to shut it down.

Logs:
  /tmp/kube-apiserver.log
  /tmp/kube-controller-manager.log
  
  /tmp/kube-proxy.log
  /tmp/kube-scheduler.log
  /tmp/kubelet.log

To start using your cluster, you can open up another terminal/tab and run:

  export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
  cluster/kubectl.sh

Alternatively, you can write to the default kubeconfig:

  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt
  cluster/kubectl.sh config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
W0823 23:57:06]: kube-proxy terminated unexpectedly, see /tmp/kube-proxy.log
```

Looking in `/tmp/kube-proxy.log`, I see it makes several failed attempts to GET its node; the last one ends like this:
```
I0823 23:57:05.197907    7905 round_trippers.go:420] GET https://localhost:6443/api/v1/nodes/127.0.0.1
I0823 23:57:05.197947    7905 round_trippers.go:427] Request Headers:
I0823 23:57:05.197957    7905 round_trippers.go:431]     Accept: application/vnd.kubernetes.protobuf, */*
I0823 23:57:05.197967    7905 round_trippers.go:431]     User-Agent: hyperkube/v1.17.0 (linux/amd64) kubernetes/d2e2337
I0823 23:57:05.200494    7905 round_trippers.go:446] Response Status: 404 Not Found in 2 milliseconds
E0823 23:57:05.200641    7905 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
F0823 23:57:05.200670    7905 server.go:440] unable to get node IP for hostname 127.0.0.1
```

In `kube-apiserver.log`, I see several failed attempts to GET the node.  Here is the last one:
```
I0823 23:57:09.667220    7596 httplog.go:90] GET /api/v1/nodes/127.0.0.1?timeout=10s: (2.315961ms) 404 [hyperkube/v1.17.0 (linux/amd64) kubernetes/d2e2337 127.0.0.1:42586]
```

Very shortly after that, there is a POST to /nodes:
```
I0823 23:57:09.771850    7596 httplog.go:90] POST /api/v1/nodes: (4.914782ms) 201 [hyperkube/v1.17.0 (linux/amd64) kubernetes/d2e2337 127.0.0.1:42586]
```

And after that the GETs of the node succeed.  Here is the first success:
```
I0823 23:57:09.776273    7596 httplog.go:90] GET /api/v1/nodes/127.0.0.1?resourceVersion=0&timeout=10s: (828.039µs) 200 [hyperkube/v1.17.0 (linux/amd64) kubernetes/d2e2337 127.0.0.1:42586]
```

**What you expected to happen**:
I expected `hack/local-up-cluster.sh` in `master` to work.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout master and try `hack/local-up-cluster.sh`

**Anything else we need to know?**:
This might be very easy to fix.  In `pkg/util/node/node.go`, there is a function `GetNodeIP` that makes a limited number attempts to GET the node with an exponential back-off.  I suspect just increasing the number of tries by one will solve this.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Intel VM
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: git; `hack/local-up-cluster.sh`
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Increased the number of tries in pkg/util/node/node.go::GetNodeIP by 1, because the kube-proxy was giving up too early.

Based on early feedback, this PR went further (but no longer does):

> The second commit goes much further, introducing a parameter and a new exponential backoff function in the wait utility package.

**Which issue(s) this PR fixes**:

Fixes #81879

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-node-bugs

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer 
@yue9944882

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr here :)

I'm not entirely opposed to this solution. However, it does feel like we're implementing a bit of a stop-gap solution. I wonder, did you explore how difficult it would be to make this value a parameter that the user can specify? I _think_ a parameter is justifiable here, acceptable wait time does seem like it would very based on different use cases and different environments in which the node is running.

**Comment by MikeSpreitzer** [comment]
No, I did not consider adding a parameter.  Before asking about the difficulty of implementing it I wonder about the advisability of doing it.  I am not enthusiastic about increasing the complexity of invoking the relevant processes.  As long as the revised fixed time limit does not conflict with other time limits, I would rather do that and keep it simpler for operators.

**Comment by mattjmcnaughton** [comment]
On Sat, Aug 24, 2019 at 07:54:51AM -0700, Mike Spreitzer wrote:
> No, I did not consider adding a parameter.  Before asking about the difficulty of implementing it I wonder about the advisability of doing it.  I am not enthusiastic about increasing the complexity of invoking the relevant processes.  As long as the revised fixed time limit does not conflict with other time limits, I would rather do that and keep it simpler for operators.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81880#issuecomment-524556492

Definitely see your point and also don't want to increase complexity :)

At the same time, my concern is that currently updating this value requires a
new k8s major release. So if someone was in a similar situation to yourself, but
needed to use 7 instead of 6, they'd need to wait 3 months for that to be
released.

I wonder if a nice middle ground is a parameter with the sensible default of 6?
For users who are happy with 6, nothing has to change. But for users who need a
different value, they don't need to wait for a k8s release.

What do you think?

**Comment by MikeSpreitzer** [comment]
@mattjmcnaughton : that's what I thought you meant in the first place.  But I see your point that if a problem is discovered then it takes a long time to fix.  I will sadly draft a revision that adds a parameter.

**Comment by mattjmcnaughton** [comment]
On Sun, Aug 25, 2019 at 09:02:33AM -0700, Mike Spreitzer wrote:
> @mattjmcnaughton : that's what I thought you meant in the first place.  But I see your point that if a problem is discovered then it takes a long time to fix.  I will sadly draft a revision that adds a parameter.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81880#issuecomment-524641541

Also an option to wait for someone else to chime in with their thoughts - I'm
just one opinion :)

**Comment by mattjmcnaughton** [comment]
On Wed, Aug 28, 2019 at 10:03:06AM -0700, Mike Spreitzer wrote:
> BTW, @mattjmcnaughton , adding a parameter seems to have bumped this way up in the level of review needed.  https://github.com/kubernetes/kubernetes/pull/81880#issuecomment-524676449 seems to be saying, if I understand correctly, that now a KEP is needed for this!
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81880#issuecomment-525833760

Yeah, I'd really love someone from the community w/ a little more experience
than me to weigh in here - cc @derekwaynecarr.

It's asking for a KEP because an API change is being made... I'm curious on
Derek's thoughts on the different trade offs between the two approaches.

Thank you for your patience :)

**Comment by vllry** [comment]
> No, I did not consider adding a parameter. Before asking about the difficulty of implementing it I wonder about the advisability of doing it. Do we really want to increase the operational complexity of the relevant process(es)? Would it be sufficient to observe that the revised fixed time limit causes no problems?

Seconding this. For a startup time in the range of seconds, a parameter (and everything that implies) seems overkill.

**Comment by bowei** [comment]
We should be careful of adding flags -- they become surface area that must be maintained at the API level.
Settings can be tuned within a patch release if it truly causes a problem wrt to the values, so it does not require waiting 3 months for a fix.
We would also get signal that the value is truly required to be a tunable if there is a PR raised multiple times to bump the value.

**Comment by mattjmcnaughton** [comment]
On Thu, Sep 05, 2019 at 05:35:40PM -0700, Bowei Du wrote:
> We should be careful of adding flags -- they become surface area that must be maintained at the API level.
> Settings can be tuned within a patch release if it truly causes a problem wrt to the values, so it does not require waiting 3 months for a fix.
> We would also get signal that the value is truly required to be a tunable if there is a PR raised multiple times to bump the value.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81880#issuecomment-528659757

Strong points as well :) It is certainly an option to bump this default one or
two times, and only make it a parameter if we find ourselves continuously
bumping the value.

**Comment by MikeSpreitzer** [comment]
OK, I changed the branch in this PR back to pointing at simply bumping the count.
The more extensive revision is preserved as https://github.com/MikeSpreitzer/kubernetes/tree/fix81879%2Bparam

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for your work here @MikeSpreitzer !

/assign @smarterclayton

**Comment by thockin** [comment]
I am +1 on a simple fix.  Why 6 and not 10, though?  What is the practical downside of just waiting longer?

It looks like this is just used by kube-proxy, so adding a retries param to GetNodeIP() seems viable, too (if we want to keep this function really generic), but I don't see why we NEED to do that absent a real use case.

**Comment by MikeSpreitzer** [comment]
I was nervous about waiting longer because when I first started working on a related issue I heard about higher level management logic with timeouts that are longer than the current timeouts but not like 500 seconds, and did not want to change the way this logic interacts with that.

**Comment by danwinship** [comment]
"6" (which translates to a total wait of 31 seconds) seems to work in practice. If we really needed to bump beyond that then we should probably rework the way that `local-up-cluster.sh` startup works anyway.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
Thanks for popping this back onto my radar.  Not sure why this never completed.  @bentheelder can you enlighten?

We'll need to cherry pick this to 1.17

**Comment by dims** [comment]
@thockin please approve https://github.com/kubernetes/kubernetes/pull/85663 for the cherry-pick

**Comment by BenTheElder** [comment]
I think this PR was opened before this presubmit was running or required, had no code changes since then, so it was never started. I did enable it running and reporting without blocking merges for O(months) before we made it blocking.

Prow handles this poorly. IIRC there actually is support for triggering newly required jobs but that isn't enabled for some reason.

**Pull request merged**
