### PR TITLE
Drop init container annotations during conversion

### LINKED ISSUE #54816: Unable to delete Job with initContainers
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

See: https://groups.google.com/forum/#!topic/kubernetes-users/YVmUgktoqtI

**What you expected to happen**:

The Job to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

I was using an initContainer to `git clone` a repo.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:  Container Engine
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
https://github.com/kubernetes/kubernetes/pull/51816/files#diff-0fa94eafdf1c7cd2171c836b53fd6323 removed special handling of init container annotations in API conversion in 1.8

However, older clients (like 1.7 kubectl) still performed that handling in some paths, which would make an object round-tripped through kubectl show up with additional annotations.

Those additions would get flagged as disallowed mutations in some objects.

This change strips init-container annotations during conversion so that old clients sending init container annotations (which are inert in 1.8+) don't trigger validation errors around immutable fields.

Fixes #54816

```release-note
Restores the ability of older clients to delete and scale jobs with initContainers
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/api-reviewers @janetkuo

**Comment by caesarxuchao** [comment]
#54816 happens in 1.7. An 1.7 kubectl creates the additional annotations, but the latest one shouldn't. Our version skew [policy](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) states that "client should be skewed no more than one minor version from the master", so I don't think we need this fix in the master. Can we directly target it to 1.7 and 1.8?

**Comment by liggitt** [comment]
> Can we directly target it to 1.7 and 1.8?

We can't make this change in 1.7 (since 1.7 still supports 1.5 kubelets, which require the annotation), only 1.8.

**Comment by liggitt** [comment]
> I don't think we need this fix in the master

I'd like to treat init container annotations consistently... we still drop them in pod conversion. We can remove these when we remove that behavior.

**Review by janetkuo — APPROVED** [review]

**Comment by caesarxuchao** [comment]
> I'd like to treat init container annotations consistently... we still drop them in pod conversion. We can remove these when we remove that behavior.

Perhaps I missed something, can we remove the special code in the pod conversion altogether? We are heading to 1.10, neither 1.8 kubelet or 1.9 kubectl will add the annotation.

**Review by soltysh — APPROVED** [review]

**Comment by liggitt** [comment]
> can we remove the special code in the pod conversion altogether? We are heading to 1.10, neither 1.8 kubelet or 1.9 kubectl will add the annotation.

We have to drop the annotations from the pod until we guarantee no kubelet honoring those annotations will make use of them. We don't support kubelets older than 2 versions skewed from the apiserver, but we don't prevent them, either, so I'd keep that drop in place for the immediate future.

**Comment by liggitt** [comment]
any other comments?

**Comment by caesarxuchao** [comment]
> We don't support kubelets older than 2 versions skewed from the apiserver, but we don't prevent them, either, so I'd keep that drop in place for the immediate future.

If you can get to it before it's merged, could you capture this in the comment of `dropInitContainerAnnotations`?

**Comment by liggitt** [comment]
> If you can get to it before it's merged, could you capture this in the comment of dropInitContainerAnnotations?

updated

**Comment by caesarxuchao** [comment]
/lgtm

Thanks.

**Comment by janetkuo** [comment]
@liggitt are we cherrypicking this into 1.8 and 1.9?

**Comment by liggitt** [comment]
Yes. Will open them shortly

**Comment by liggitt** [comment]
picks opened

**Pull request merged**
