### PR TITLE
Pod log location must validate container if provided

### PR DESCRIPTION
**Pull request by fabianofranz**
Backport https://github.com/kubernetes/kubernetes/pull/17886 to **release-1.0**.

### CODE REVIEW

**Comment by fabianofranz** [comment]
cc @liggitt

**Comment by liggitt** [comment]
LGTM
cc @brendandburns @lavalamp

**Comment by lavalamp** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by fabianofranz** [comment]
@liggitt can you check and paste the Jenkins error here, please?

**Comment by lavalamp** [comment]
Possibly legit fail, look at second half:

```
03:05:04 Summarizing 3 Failures:
03:05:04 
03:05:04 [Fail] Probing container [It] with readiness probe that fails should never be ready and never restart 
03:05:04 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:88
03:05:04 
03:05:04 [Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
03:05:04 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69
03:05:04 
03:05:04 [Fail] Services [It] should be able to change the type and nodeport settings of a service 
03:05:04 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1069
03:05:04 
03:05:04 Ran 64 of 99 Specs in 646.985 seconds
03:05:07 FAIL! -- 61 Passed | 3 Failed | 2 Pending | 33 Skipped 

...

02:57:36 ------------------------------
02:57:57 [BeforeEach] Probing container
02:57:57   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:39
02:57:57 STEP: Creating a kubernetes client
02:57:57 >>> testContext.KubeConfig: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@5/.kube/config
02:57:57 STEP: Building a namespace api object
02:57:57 INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-container-probe-blzhn
02:57:57 INFO: Get service account default in ns e2e-tests-container-probe-blzhn failed, ignoring for 5s: serviceaccounts "default" not found
02:57:57 INFO: Service account default in ns e2e-tests-container-probe-blzhn with secrets found. (5.044025263s)
02:57:57 STEP: Waiting for a default service account to be provisioned in namespace
02:57:57 INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-container-probe-blzhn
02:57:57 INFO: Service account default in ns e2e-tests-container-probe-blzhn with secrets found. (2.359721ms)
02:57:57 [It] with readiness probe that fails should never be ready and never restart
02:57:57   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:99
02:57:57 [AfterEach] Probing container
02:57:57   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:41
02:57:57 STEP: Collecting events from namespace "e2e-tests-container-probe-blzhn".
02:57:57 
02:57:57 
02:57:57 • Failure [70.359 seconds]
02:57:57 Probing container
02:57:57 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:101
02:57:57   with readiness probe that fails should never be ready and never restart [It]
02:57:57   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:99
02:57:57 
02:57:57   expecting wait timeout error but got: Get https://104.197.108.92/api/v1/namespaces/e2e-tests-container-probe-blzhn/pods/test-webserver-3d90cbd0-981a-11e5-8b78-42010af00003: dial tcp 104.197.108.92:443: connection refused
02:57:57 
02:57:57   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:88
02:57:57 ------------------------------
```

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
Only failure on latest run was `should *not* be restarted with a docker exec "cat /tmp/health" liveness probe` test, which is flaky in the release-1.0 branch (seeing flakes apart from this branch). Manually merging.

**Pull request merged**
