### PR TITLE
Update basic audit filter's comment message

### PR DESCRIPTION
**Pull request by CaoShuFeng**
**Release note**:

```NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
@k8s-bot ok to test

**Comment by soltysh** [comment]
I've added retest-not-required label, since this is just comment.

**Comment by soltysh** [comment]
@k8s-bot unit test this

**Comment by CaoShuFeng** [comment]
ping

**Comment by soltysh** [comment]
This is minor comment change I'll just approve by myself.

**Pull request merged**
