### PR TITLE
Update aws.go

### PR DESCRIPTION
**Pull request by vjm**
Ensure that private loadbalancers do not get public subnets assigned

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Do we have an issue open for this?  Trying to figure out what you fixed :)

**Comment by vjm** [comment]
I am trying to find an existing issue as well. Basically if you have
multiple AZs, one public the other not, it will not properly exclude
subnets that are not route-able.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by vjm** [comment]
@chrislovecnm i updated this formatting issue

**Comment by gnufied** [comment]
Not really familiar with loadbalancer changes.

/unassign

**Comment by justinsb** [comment]
Update: we discussed this on slack, I thought that internal ELBs could be in public subnets.  I need to verify.  I believe tagging solved the particular issue here.  We also identified a few more issues though!

**Pull request closed without merging**
