### PR TITLE
Fix potential nil dereference in nodeinfo

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
`if err!=nil`, `nodeinfo` could be nil, `nodeInfo.Node()` may be panic.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
`nodeinfo.Node()` will return `nil` if `nodeinfo` is `nil`:

**Comment by ahg-g** [comment]
see here: https://github.com/kubernetes/kubernetes/blob/965137a992ed755474f17fa6377ee3555745addd/pkg/scheduler/framework/v1alpha1/types.go#L429

so this PR is not needed.

**Comment by yuzhiquan** [comment]
> see here:
> 
> https://github.com/kubernetes/kubernetes/blob/965137a992ed755474f17fa6377ee3555745addd/pkg/scheduler/framework/v1alpha1/types.go#L429
> 
> so this PR is not needed.

Oops, only check `Get` function, not check the `Node` function, sorry for this.

**Pull request closed without merging**
