### PR TITLE
Unify aliases for "k8s.io/apimachinery/pkg/api/errors"

### LINKED ISSUE #85118: Unify aliases under test directory for "k8s.io/apimachinery/pkg/api/errors"
**What happened**:
Many files under test directory import `"k8s.io/apimachinery/pkg/api/errors"`.
But, different aliases are defined for each file.

For example,
```
test/e2e/auth/service_accounts.go:
        apierrors "k8s.io/apimachinery/pkg/api/errors"

test/e2e/auth/pod_security_policy.go:
        apierrs "k8s.io/apimachinery/pkg/api/errors"

test/e2e/auth/audit_dynamic.go:
        "k8s.io/apimachinery/pkg/api/errors"
```
```
$ grep -rs \"k8s.io/apimachinery/pkg/api/errors\" test/ | grep apierrors | wc -l
15
$ grep -rs \"k8s.io/apimachinery/pkg/api/errors\" test/ | grep apierrs | wc -l
32
$ grep -rs \"k8s.io/apimachinery/pkg/api/errors\" test/ | egrep -v "apierrors|apierrs" |  wc -l
60
```
We can get more readability if the aliases are unified.
I suggest that we unify the alias to "apierrs" because many files use it.

https://github.com/kubernetes/kubernetes/pull/85078 adds "apierrs" to `hack/.import-aliases`. We should resolve the aliases before https://github.com/kubernetes/kubernetes/pull/85078 will be merged.

/kind cleanup
/sig testing

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**
/kind cleanup
/sig testing

**What this PR does / why we need it**:

Many files under test directory import "k8s.io/apimachinery/pkg/api/errors".
But, different aliases are defined for each file.

For example,
```
test/e2e/auth/service_accounts.go:
        apierrors "k8s.io/apimachinery/pkg/api/errors"

test/e2e/auth/pod_security_policy.go:
        apierrs "k8s.io/apimachinery/pkg/api/errors"

test/e2e/auth/audit_dynamic.go:
        "k8s.io/apimachinery/pkg/api/errors"
```
```
grep -rs \"k8s.io/apimachinery/pkg/api/errors\" ./ | grep apierrors | wc -l
     200

grep -rs \"k8s.io/apimachinery/pkg/api/errors\" ./ | grep apierrs | wc -l
      51
```

We can get more readability if the aliases are unified.
We can unify the alias to "apierrors" because most of files use it.

**Which issue(s) this PR fixes**:

Fixes #85118

**Special notes for your reviewer**:

/assign @k-toyoda-pi
/cc @fejta

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
I don't see any harm in this change, and agree that consistency almost always leads to greater readability.

My one concern would be maintaining consistency going forward. AFAIK, we don't have any linting tools which would allow us to ensure we're only using `apierrors`. That being said, perhaps the fact that all existing examples would use `apierrors` would be enough to encourage new code?

Marking as LGTM, but always possible I'm missing an issue that another reviewer will raise :)

/lgtm

**Comment by liggitt** [comment]
a sweep like this will require a lot of rebases for open PRs. I'm inclined to hold this until after master opens for 1.18, given we have ~2 days until code freeze

**Review by fejta — COMMENTED** [review]
/approve

**Comment by danielqsj** [comment]
@liggitt now, master branch is open for 1.18. Could you help review it? Thanks

**Pull request merged**
