### PR TITLE
Adding extra logging in case of error.

### PR DESCRIPTION
**Pull request by krousey**
Hopefully we'll get a bit more information when the upload fails.

cc @kubernetes/sig-api-machinery @ncdc @lavalamp 

ref: #24620

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, too

**Comment by krousey** [comment]
Is this p0 worthy due to the flakiness of the issue? (was actually stable over the weekend, but was really flaky last week)

**Comment by lavalamp** [comment]
Yeah, I'm OK with prioritizing anything that reduces the flaky test burden.

**Comment by krousey** [comment]
@k8s-oncall What's up with this PR? The merge build seems to never happen and now I can't find it in the queue? It's just an e2e change for more info on a test that is actively flaking. Can I get a manual merge?

**Comment by fabioy** [comment]
Unclear what happened (it was in the queue). I'll just merge this manually

**Pull request merged**
