### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by oilbeater**

### CODE REVIEW

**Comment by nikhita** [comment]
@oilbeater Thanks for making your first contribution to Kubernetes! 🎉

**Comment by deads2k** [comment]
looks like something went wrong with a rebase.

**Comment by oilbeater** [comment]
rebase master to see if ci still failed

**Comment by php-coder** [comment]
still /lgtm

**Comment by oilbeater** [comment]
it seems the approve label not been added

**Comment by oilbeater** [comment]
still need a approve /assign @smarterclayton

**Comment by bsalamat** [comment]
Never mind. I don't have approval power in the modified directories.

**Comment by nikhita** [comment]
This has been fixed in https://github.com/kubernetes/kubernetes/pull/59464. Closing.

/close

**Pull request closed without merging**
