### PR TITLE
Update to golang 1.10.4

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: updates the build to use golang 1.10.4. There are a few compiler fixes as noted in https://github.com/golang/go/issues?q=milestone%3AGo1.10.4

It's pretty late in the k8s 1.12 release cycle, so we might want to wait till 1.12.1 for this? I'm not sure how critical the fixes are.

**Release note**:

```release-note
Update to golang 1.10.4
```

/sig release
/hold
because kube-cross isn't published yet

### CODE REVIEW

**Comment by tpepper** [comment]
Given we've just announced delay of the release, I'm somewhat willing to entertain accepting this for 1.12 ASAP.  We have 9 days.

**Comment by ixdy** [comment]
What `kind` even applies to this PR? cleanup?

**Comment by tpepper** [comment]
If we had test automation comparing our core components and dependencies used versions versus the corresponding upstream latest patch versions...this would be kind failing-test :)

**Comment by neolit123** [comment]
k/k needs more kinds for sure.

**Comment by tpepper** [comment]
pull-kubernetes-cross failure looks legit @ixdy ?

**Comment by ixdy** [comment]
yeah, that failure is expected until kube-cross gets published. (working on that.)

**Comment by ixdy** [comment]
ok, that retest was a little jumpy, since the image hasn't been published yet.

**Comment by tpepper** [comment]
I'm a bit worried by the size of storage merge for v1.12 today. I want to see the test results there still showing ok this morning, and then intend to unhold this PR this afternoon. Need the team to watch test results especially closely for a good 72hrs after this as it may have not just simpler immediate master branch and quickly following release-1.12 branch issues, but long running scalability issues.

/cc @wojtek-t @shyamjvs

**Comment by tpepper** [comment]
Here we go...no reason to expect issues but arrrr hands on deck me k8s maties

/kind critical-urgent
/milestone v1.12

**Comment by tpepper** [comment]
Argh
/priority critical-urgent

**Pull request merged**
