### PR TITLE
spelling mistake

### PR DESCRIPTION
**Pull request by songxiao-wang87**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
none

Which issue(s) this PR fixes:
none

Special notes for your reviewer:
none

Does this PR introduce a user-facing change?
none

```release-note

NONE

```

### CODE REVIEW

**Comment by heqg** [comment]
your are missing : do-not-merge/release-note-label-needed

wloud you to add the following commit?
```release-note
NONE
```

**Comment by yangjunmyfm192085** [comment]
needs CLA

**Pull request merged**
