### PR TITLE
fix wrong condition description in PVC

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

no condition type named ResizeStarted

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by humblec** [comment]
cc @gnufied

**Review by r0b2g1t — APPROVED** [review]

**Comment by sftim** [comment]
IMO, we could changelog this.

**Comment by liggitt** [comment]
I don't think a doc update about a doc update is worth the noise, imo

**Pull request merged**
