### PR TITLE
Rename vars scheduledJob to cronJob

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Rename vars scheduledJob to cronJob

**Special notes for your reviewer**:
refer to #45480

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
