### PR TITLE
Ensure all new API versions of resources default to DeleteDependents

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

For compatibility, resources with dependents that existed prior to server-side garbage collection default to orphaning dependents when deleted.

This PR sweeps the strategies for those resources and ensures that any future API versions introduced will default to using server-side garbage collection.

**Which issue(s) this PR fixes**:
xref #71772

**Special notes for your reviewer**:

Best viewed [ignoring whitespace](https://github.com/kubernetes/kubernetes/pull/71792/files?utf8=%E2%9C%93&diff=split&w=1)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
fixed unit tests

**Pull request merged**
