### PR TITLE
Change log level to Debug

### LINKED ISSUE #95380: cpumanager "ignoring terminated container" should not be a warning
kubernetes 1.19.2

seeing tons of these, feels like something that should be debug or info ... not really actionable or something that it should warn about ?

```
W1007 20:33:44.086277    4842 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container
```

/sig node

### PR DESCRIPTION
**Pull request by tech-geek29**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #95380

Release Notes:
```release-note
NONE
```

### CODE REVIEW

**Review by adisky — COMMENTED** [review]
/lgtm

**Comment by n4j** [comment]
@liggitt Can you approve this?

**Comment by liggitt** [comment]
> @liggitt / @dims Can anyone of you approve this?

changes like this should be approved by the package approvers... are there additional node approvers that should be added to that package?

**Comment by SergeyKanzhelev** [comment]
/assign @cynepco3hahue @klueska 

would any of you pls review?

**Comment by cynepco3hahue** [comment]
/lgtm
I like the idea to move reduce the verbosity of reconcile logs, because once the CPU manager enabled with the static policy it flood the kubelet log.

**Comment by n4j** [comment]
@derekwaynecarr @vishh @ConnorDoyle Can anyone of you approve this PR?

**Comment by klueska** [comment]
These warning should only be "flooding " the logs if you have init containers that exit and the their corresponding app containers are then long running. When this happens, each init containers will hit one of these messages everytime around the reconcile loop until its app containers exit.

Otherwise, these logs should only appear sporadically if an app container happens to exit after the reconcile loop has started. The message should only appear once and then not appear the next time around the loop (because at that point the container will be gone).

With all of that said -- I am happy to accept this change, as these really are only relevant when debugging, and not a warning that should cause concern as they happen quite often for good reason.

/lgtm
/approve

**Pull request merged**
