### PR TITLE
annotate some addtional errors in e2e tests

### PR DESCRIPTION
**Pull request by macb**
**What this PR does / why we need it**:
Adds some additional context to e2e test failures.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: some work toward #34059

**Special notes for your reviewer**: I didn't want to go through all of the offending cases so I picked off a few files and addressed those.

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34295)

### CODE REVIEW

**Comment by macb** [comment]
signed sla `cla/linuxfoundation`

**Comment by fejta** [comment]
@k8s-bot ok to test

**Comment by fejta** [comment]
Great change! Thanks for making it.

**Comment by fejta** [comment]
@k8s-bot kubemark e2e test this

**Comment by fejta** [comment]
@k8s-bot gci gce e2e test this

**Comment by fejta** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot kubemark e2e test this

**Pull request merged**
