### PR TITLE
Fix gocritic lint errors for cmd/kubeadm/*

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix gocritic lint errors for `cmd/kubeadm/*`

FYI: https://go-critic.com/overview.html#equalfold

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted

**Comment by SataQiu** [comment]
Hi @dims, cloud you please have a look?
/assign @dims

**Pull request merged**
