### PR TITLE
kubeadm:workflow:runner: add func AppendPhases

### PR DESCRIPTION
**Pull request by s-z-z**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

add func AppendPhases, so we can add many Phases in one function.

#### Does this PR introduce a user-facing change?

NONE

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR, but i don't think we need this change.
in all places it looks like this:
```
r.AppendPhase(...)
r.AppendPhase(...)
r.AppendPhase(...)
```
and there isn't much gain for us if we call:
```
r.AppendPhases(...,
...,
...,
)
```

if you want to help please add kubeadm unit tests where they are needed.

**Comment by suzi1037** [comment]
I think it is more concise.

1. When adding new phase, just type it, which the common prefix typing break mind. 
2. phase is not just for one command. when other command use your phases
```
r.AppendPhases(
  yourphase.NewPhaseFoo,
  yourphase.NewPhaseBar,
  ...
)
```
u see, they are grouped, more readable for viewer.

3. every downstream user should have a for loop with current style. 

Of course this isn't a huge improvement. If you insist, I'll close it

**Comment by neolit123** [comment]
> every downstream user should have a for loop with current style.

these functions are not an API.

> Of course this isn't a huge improvement. If you insist, I'll close it

let's focus on more significant changes.

also see:
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits

/close

**Comment by suzi1037** [comment]
thanks, [neolit123](https://github.com/neolit123)
Your guidance is invaluable. I will read it carefully.

**Pull request closed without merging**
