### PR TITLE
Alias local packagename for pkg/util/errors

### PR DESCRIPTION
**Pull request by zhengguoyong**
change reseaon:
1: There are other errors package, for example pkg/api/errors, so use utilerrors to distinguish
2: Some useplace while import pkg/util/errors alias a local name, but not all. so i think it better to alias a same local name for all the useplace
3: Somewhere it use utilErrors to alias a local name , i think we should use utilerrors, change it and make consistent

### CODE REVIEW

**Comment by zhengguoyong** [comment]
@smarterclayton 
Hello smarterclayton, would you please help me have a review for this PR ?
thank you very much.

**Comment by smarterclayton** [comment]
The changeset is showing that all of the files were changed from 0644 to 0755 - is that intentional?

**Comment by zhengguoyong** [comment]
soory, it is my mistake, thank you for your attentive review,
i changed it , please review again , thanks.
@smarterclayton

**Comment by zhengguoyong** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
LGTM thanks

**Comment by zhengguoyong** [comment]
thanks very much.
please help me add "ok-to-merge" label,
also PR: #15472
@smarterclayton

**Pull request merged**
