### PR TITLE
Remove GA featuregate about KubeletPodResourcesGetAllocatable in 1.30

### PR DESCRIPTION
**Pull request by ii2day**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `KubeletPodResourcesGetAllocatable`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Removed generally available feature gate `KubeletPodResourcesGetAllocatable`.
```

**Comment by ii2day** [comment]
> Changelog suggestion
> 
> ```
> Removed generally available feature gate `KubeletPodResourcesGetAllocatable`.
> ```

Okay, that's been changed.

**Comment by dims** [comment]
/approve
/lgtm

book keeping!

**Pull request merged**
