### PR TITLE
fix TestDescribeServiceAccount fail

### LINKED ISSUE #54619: unit test case TestDescribeServiceAccount probabilisticly fail
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
unit test fail randomly. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
cd k8s.io/kubernetes/pkg/printers/internalversion
go test -v -test.run TestDescribeServiceAccount
```
**Anything else we need to know?**:
```
# go test -v -test.run TestDescribeServiceAccount
=== RUN   TestDescribeServiceAccount
--- FAIL: TestDescribeServiceAccount (0.00s)
	describe_test.go:1694: expected : "Name:                bar\nNamespace:           foo\nLabels:              <none>\nAnnotations:         <none>\nImage pull secrets:  test-local-ref(not found)\nMountable secrets:   test-objectref (not found)\nTokens:              <none>\nEvents:              <none>\n"
		 but got output:
		 "Name:                bar\nNamespace:           foo\nLabels:              <none>\nAnnotations:         <none>\nMountable secrets:   test-objectref (not found)\nTokens:         <none>\nImage pull secrets:  test-local-ref (not found)\nEvents:              <none>\n"
FAIL
exit status 1
FAIL	k8s.io/kubernetes/pkg/printers/internalversion	0.082s

```
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54619 

**Special notes for your reviewer**:
unit test case `TestDescribeServiceAccount` probabilisticly fail because of map key sequence is not guaranteed 
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@hzxuzhonghu have open PR #54563 yesterday fix this, mind close this? thanks

**Comment by hzxuzhonghu** [comment]
@zjj2wry Sorry, I missed it. As PR #54563 already fixed this, I am closing it.

**Comment by deads2k** [comment]
I don't think this is the correct solution. The describer itself should be predictable. See #54628

**Comment by hzxuzhonghu** [comment]
@deads2k Good

**Pull request closed without merging**
