### PR TITLE
Allow pods to opt out of PodPreset mutation via an annotation on namespace

### LINKED ISSUE #44161: Allow pods to opt out of mutation via PodPresets
`PodPreset` can make changes in a pod's spec that can have security implications, especially if the pod runs with elevated permissions or capabilities.  It should be possible to annotate a pod to indicate that that pod should not be manipulated by `PodPreset`.

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): PodPreset

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Kubernetes version** (use `kubectl version`):

1.6

**Environment**:

Any cluster

### PR DESCRIPTION
**Pull request by jpeeler**
This is a new admission controller that intercepts the create and update
of PodPreset resources. The selector on a PodPreset spec may be modified
via two methods:

1) A cluster wide default selection criteria as specified in the
admission control config file, such as in this example:

```
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: "PodPresetRestriction"
  configuration:
    apiVersion: podpresetrestriction.admission.k8s.io/v1alpha1
    kind: Configuration
    defaultSelector:
      matchLabels:
        component: redis
```

2) An annotation on the same namespace as the PodPreset with a key of
podpresetrestriction.alpha.kubernetes.io/defaultSelector and a JSON
formatted matchExpression, an example being:
kubectl annotate ns foo \
podpresetrestriction.alpha.admission.kubernetes.io/defaultSelector=\
'{ "matchExpressions": \
[{"key": "openshift.io/build.name", "operator": "DoesNotExist" }]}'

With either option the resulting pod preset selector will contain the
default selector criteria and will allow matching pods to opt-out of
preset mutation.

**What this PR does / why we need it**:
This essentially mitigates potential security issues due to pod spec manipulation with privileged pods.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44161

### CODE REVIEW

**Comment by jpeeler** [comment]
Note the way I've written this is case matters for the annotation. Not sure what the proper convention for that is.

**Review by derekwaynecarr — CHANGES_REQUESTED** [review]
Instead of this approach, can we do the following:

1. Author an admission controller that intercepts create/update of PodPreset object.
1. Have the admission controller apply a clause to the LabelSelector for the PodPreset that adds a set of default MatchExpressions exclusion based on an annotation on the Namespace itself.
1. Pods that have a key/value label pair that match the NotIn clause (from the default set applied to a PodPreset in the earlier phase) are automatically excluded with no additional annotation needed.

This aligns with how we handle similar use cases for node selector defaulting, and toleration defaulting.

**Comment by derekwaynecarr** [comment]
FYI @liggitt

**Comment by derekwaynecarr** [comment]
I would expect a similar configuration as https://github.com/kubernetes/kubernetes/pull/30302

**Comment by derekwaynecarr** [comment]
FYI @pmorie

**Comment by derekwaynecarr** [comment]
fyi @jwforres for tracking

**Comment by derekwaynecarr** [comment]
@jpeeler -- here is more detail on what i think is the minimum needed.

**PodPresetRestriction**
This is a new admission controller that intercepts the create and update of `PodPreset` resources.  It allows cluster-admin users to augment a `PodPreset` selector to merge in additional selector criteria specified globally at the cluster level (via config) or local to each namespace (via annotation).

It supports the following admission control configuration to let operators define cluster wide default selection criteria.

```
type Configuration struct {
  metav1.TypeMeta

  // DefaultSelector is merged with every PodPreset selector
  DefaultSelector []metav1.LabelSelector
}
```

For example, if I want every `PodPreset` cluster-wide to have in its selector a check for the label foo with value bar, I can define the following configuration:

```
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: "PodPresetRestriction"
  configuration:
    apiVersion: podpresetrestriction.admission.k8s.io/v1alpha1
    kind: Configuration
    defaultSelector:
      matchLabels:
        foo: bar
```

If a cluster wide default is not appropriate, it also supports pulling a default selector from an annotation on the namespace that contains the incoming `PodPreset`.  For example, if I want to ensure that every `PodPreset` in the namespace foo has a selector that forces it to exclude pods that have the label `openshift.io/build.name`, I can annotate the namespace as follows:

```
$ kubectl annotate\
  namespace foo\
  podpresetrestriction.alpha.kubernetes.io/defaultSelector\
  '{ "matchExpressions": { "key": "openshift.io/build.name", "operator": "DoesNotExist"  } }'
```

The resultant `PodPreset` in the `foo` namespace would have the specified `matchExpression` merged into its selector.  Since selectors are ANDed together, we know that our PodPreset will always exclude pods that have this specified label.

**Comment by derekwaynecarr** [comment]
Per private discussion, let's keep both options open (i.e. mutation of incoming PodPreset, or opt-out annotation on an incoming Pod) as separate PRs.

**Comment by bgrant0607** [comment]
cc @pwittrock

**Comment by derekwaynecarr** [comment]
@jpeeler -- this will need a rebase given recent changes in kube admission chains.  can we rebase and poke for review?  i would like to get closure on this for 1.7 as its critical for our ability to prevent abuse scenarios when coupled with service catalog.

**Comment by pmorie** [comment]
@jpeeler the title and description on this and your other PR match - would you please disambiguate them?

**Comment by derekwaynecarr** [comment]
for 1.7, we can use https://github.com/kubernetes/kubernetes/pull/44965

we can hold on doing this route until a later time.

**Pull request closed without merging**
