### PR TITLE
add kubectl config view test code

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
kubectl config view test code

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
think you very much :)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@fabianofranz Can you help me review this ? think you very much

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@k8s-bot gci gce e2e test this

**Comment by fabianofranz** [comment]
@zjj2wry thanks!
/release-note-none
/lgtm
/approve

**Pull request merged**
