### PR TITLE
Convert update-codecgen.sh to use a hardcoded list

### PR DESCRIPTION
**Pull request by lavalamp**
@thockin @luxas hopefully this will make it work for you.

@wojtek-t sorry, but I never want to debug this file again...

### CODE REVIEW

**Comment by thockin** [comment]
unsurprisingly I hate this.  Why does order matter?  Why is the sort not sufficient?  Why would sort come out differently on different machines?

**Comment by lavalamp** [comment]
ugorji reuses code or not depending on if the dependencies have already been generated.

**Comment by thockin** [comment]
I think this is better:  https://github.com/kubernetes/kubernetes/pull/24242/commits/f6c1fa5c274855d4f2c51598fe578ec80d2d9537

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/25240

**Comment by wojtek-t** [comment]
@thockin - IIUC, your PR is not fixing the sorting problem.

**Comment by wojtek-t** [comment]
I don't like this PR, but I'm fine with that. But since @thockin feels strongly about it, I will let him decide.

**Comment by thockin** [comment]
It fixed it for me.  When I ran it on my laptop I saw "old logic said no"
when I said "yes".  There are cases where the glob compare is not right,
for whatever reason, but this is right.

I don't like that we have an N^2 loop that does several hundred scans of
dependency lists, but this seems to produce stable results for my laptop
and for jenkins, including with vendor support.

What about the PR don't you like, and what would you change?  I just want
this problem to be fixed.

**Comment by wojtek-t** [comment]
Actually - i think I didn't understand it at first pass ( I mean the alternative PR). Now I see what it changes and it LGTM

**Comment by wojtek-t** [comment]
So personally, I would prefer proceeding with the alternative one.

**Comment by thockin** [comment]
Sorry, I replied here.  Yes, I think we should close this one.

**Comment by lavalamp** [comment]
OK it's official-- @thockin owns this script now ;)

**Comment by therc** [comment]
Somebody needs to make shot glasses with the picture of @thockin at the bottom, for those occasions when the script goes crazy again.

**Pull request closed without merging**
