### PR TITLE
Refactor:move clean method to suitable place

### PR DESCRIPTION
**Pull request by yanghaichao12**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Refactor the test case of kubectl，move method to right place

**Which issue(s) this PR fixes**:
Fixes #

/release-note-none
/priority backlog

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/kind cleanup

**Comment by apelisse** [comment]
That's much cleaner, thanks
/lgtm
/approve

**Comment by yanghaichao12** [comment]
@neolit123 @apelisse thank you!

**Pull request merged**
