### PR TITLE
improved error message when object with generateName already exists

### LINKED ISSUE #32220: Confusing error when object with generateName already exists
Spawned from https://github.com/openshift/origin/issues/10237

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/rest/create.go#L106 is converting an AlreadyExists error into a server timeout error if it has a generateName

```
// CheckGeneratedNameError checks whether an error that occurred creating a resource is due
// to generation being unable to pick a valid name.
func CheckGeneratedNameError(strategy RESTCreateStrategy, err error, obj runtime.Object) error {
    if !errors.IsAlreadyExists(err) {
        return err
    }

    objectMeta, kind, kerr := objectMetaAndKind(strategy, obj)
    if kerr != nil {
        return kerr
    }

    if len(objectMeta.GenerateName) == 0 {
        return err
    }

    return errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)
}
```

That means that this returns really confusing errors:

```
data='{"kind":"Secret","apiVersion":"v1","metadata":{"name":"foo","generateName":"foo"}}'
$ oc create -f - <<< "$data"
secret "foo" created
$ oc create -f - <<< "$data"
Error from server: error when creating "STDIN": The POST operation against Secret could not be completed at this time, please try again.
```

### PR DESCRIPTION
**Pull request by poonai**
Signed-off-by: பாலாஜி <rbalajis25@gmail.com>

**What this PR does / why we need it**:
improved error message when object with generateName already exists
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #32220

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sch00lb0y** [comment]
@deads2k please review

**Comment by dims** [comment]
/ok-to-test

@sch00lb0y பாலாஜி, can you please add a unit test too?

**Comment by sch00lb0y** [comment]
@dims  I have added the unit test. check now

**Comment by mikedanese** [comment]
What is the diff between the error messages?

**Comment by sch00lb0y** [comment]
@mikaelh 
If name and GenerateName are present in the resource while creating, it showing `errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)` timeout error instead of name already exist error. 
So I set GenerateName empty in beforeCreate if the resource has a name.

**Pull request closed without merging**
