### PR TITLE
Makefile catch untagged dirs

### LINKED ISSUE #65928: make generated_files is not detecting codegen tag changes correctly
/kind bug

It seems like `make generated_files` doesn't always detect codegen tag changes correctly, for example, when someone adds or removes a `// +k8s:` codegen tag.

An easy way to reproduce this bug:
1. Run `make generated_files` and copy `pkg/generated/openapi/zz_generated.openapi.go` out of tree.
2. Find some package with a `// +k8s:openapi-gen=true` tag and remove it. For example,
```diff
diff --git a/staging/src/k8s.io/api/batch/v2alpha1/doc.go b/staging/src/k8s.io/api/batch/v2alpha1/doc.go
index f4ed01ad84..6c25b323f8 100644
--- a/staging/src/k8s.io/api/batch/v2alpha1/doc.go
+++ b/staging/src/k8s.io/api/batch/v2alpha1/doc.go
@@ -15,6 +15,5 @@ limitations under the License.
 */

 // +k8s:deepcopy-gen=package
-// +k8s:openapi-gen=true

 package v2alpha1 // import "k8s.io/api/batch/v2alpha1"
```
3. Run `make generated_files` again.
4. Diff `pkg/generated/openapi/zz_generated.openapi.go` with the version generated in step 1. Notice that there's no diff.
5. Run `make clean` followed by `make generated_files` again.
6. Diff `pkg/generated/openapi/zz_generated.openapi.go` with the version generated in step 1. This time there's a diff.

I noticed this behavior while reviewing #65440.

At first I thought #54372 may be suspect, but it seems like the error is probably around https://github.com/kubernetes/kubernetes/blob/5114d4e0b040d2f00417e0fd3e11204afd30f63c/build/root/Makefile.generated_files#L104-L107 and that PR didn't touch it.

/assign @thockin @ixdy

### PR DESCRIPTION
**Pull request by thockin**
Fixes #65928

I am not 100% sure this is worthwhile.  Thoughts?

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Can you explain why this would have caught #65928?

**Comment by thockin** [comment]
@sttts this detects a change in the list of directories being processed, which forces the files to be removed in dirs that are no longer being processed.

Anyone want to review this?

**Comment by thockin** [comment]
See #72222

**Pull request closed without merging**
