### PR TITLE
Revert "[kubelet] Fix oom-score-adj policy in kubelet"

### PR DESCRIPTION
**Pull request by vishh**
Reverts kubernetes/kubernetes#32251

This PR is breaking cross builds. I have no clue why node e2e is being compiled on non-linux platforms. 

<details>
+++ [0915 19:15:44] darwin/amd64: go build started
# k8s.io/kubernetes/test/e2e_node

test/e2e_node/container_manager_test.go:80: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:80: undefined: dockerProcessName
test/e2e_node/container_manager_test.go:80: undefined: dockerPidFile
test/e2e_node/container_manager_test.go:89: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:89: undefined: kubeletProcessName
test/e2e_node/container_manager_test.go:116: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:130: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:168: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:209: undefined: getPidsForProcess
+++ [0915 19:15:44] windows/amd64: go build started
# k8s.io/kubernetes/test/e2e_node

test/e2e_node/container_manager_test.go:80: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:80: undefined: dockerProcessName
test/e2e_node/container_manager_test.go:80: undefined: dockerPidFile
test/e2e_node/container_manager_test.go:89: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:89: undefined: kubeletProcessName
test/e2e_node/container_manager_test.go:116: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:130: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:168: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:209: undefined: getPidsForProcess
+++ [0915 19:15:44] linux/arm: go build started
</details>

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32841)

### CODE REVIEW

**Comment by vishh** [comment]
Manually merging this to ensure that HEAD is no longer broken once the tests pass.

**Comment by vishh** [comment]
@k8s-bot test unit github issue #IGNORE

**Comment by vishh** [comment]
cc  @saad-ali

**Comment by vishh** [comment]
@k8s-bot unit test this github issue #IGNORE

**Comment by ixdy** [comment]
> I have no clue why node e2e is being compiled on non-linux platforms.

because our builds are a mess. lol.

**Pull request merged**
