### PR TITLE
Update flocker-go godep to pick up new LICENSE file.

### LINKED ISSUE #21195: Update flocker-go to pull in their new license file
/cc @goltermann @zmerlynn 

We want https://github.com/kubernetes/kubernetes/blob/master/Godeps/LICENSES.md to no longer say "UNKNOWN" for flocker-go.

### PR DESCRIPTION
**Pull request by goltermann**
Fixes #21195.

This pulls in an update of flocker-go, which will get the newly added LICENSE file.

Two caveats:
1) it also pulls in a single code fix from https://github.com/ClusterHQ/flocker-go/pull/2
2) hack/verify-godeps.sh is failing with tons of changes on my machine, but this is straightforward, so I'm going to use our Travis machinery to verify that stuff is ok

### CODE REVIEW

**Comment by goltermann** [comment]
Crud, same verify-godeps issue in Travis.  @lavalamp do you know how a change this small would trigger so many Godeps.json diffs?

**Comment by lavalamp** [comment]
We only run the godeps verifier on godeps changes, so if something breaks in the mean time, it gets mad.

**Comment by lavalamp** [comment]
Hm, I will try to investigate.

**Comment by lavalamp** [comment]
Let's see what the tests think about #21733

**Comment by lavalamp** [comment]
@goltermann Try checking out v53 of godep and redoing this. See #21771

**Comment by eparis** [comment]
To fix the CI, @goltermann really needs to be on top of #21771   (or put #21771 on top of this)

**Comment by goltermann** [comment]
@eparis @lavalamp Jenkins and godeps are happy, seeking LGTM.

**Comment by lavalamp** [comment]
LGTM, but if @eparis's PR merges first, this will probably need a rebase. (You can avoid this by fetching @eparis's change and doing a git cherry-pick of the relevant commit instead of recreating it.)

**Comment by eparis** [comment]
It might not require a rebase, git is sometimes really smart if 2 people do exactly the same thing....

**Pull request merged**
