### PR TITLE
Add `kubectl config get-credentials` and `kubectl config delete-credentials`

### PR DESCRIPTION
**Pull request by AndreasAbdi**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:

/kind feature

**What this PR does / why we need it**:
Adds the operations
`kubectl config delete-credentials`
`kubectl config get-credentials`
Also adds bash autocomplete for delete-credentials.

For feature parity against `kubectl config get-clusters, add-cluster, delete-cluster` etc. 
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kubernetes/kubectl/issues/396
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add `kubectl config delete-credentials` and `kubectl config get-credentials` operations to kubectl. 
```

### CODE REVIEW

**Comment by AndreasAbdi** [comment]
I signed it.

**Comment by mengqiy** [comment]
2 new commands
/cc seans soltysh

**Pull request closed without merging**
