### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by imhunterand**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by imhunterand** [comment]
hi can you invite to contribute your github repository as member
please invite my github username.

**Comment by cblecker** [comment]
@fedebongio Is there a reason we are triaging this PR that was opened in error and was already closed?

**Comment by BenTheElder** [comment]
It's the SIG architecture triage process, they go through issues with the needs triage and sig arch label in a regular recurring call.

triaging accepted takes it out of the filtered search, they've been doing this for a long time

**Comment by cblecker** [comment]
@BenTheElder Could we use things like `/triage unresolved` instead? https://github.com/kubernetes/kubernetes/labels?q=triage%2Funresolved

**Comment by BenTheElder** [comment]
TIL we have this label, I just hopped into the triage meeting and we're discussing now, thanks!

**Comment by fedebongio** [comment]
Hi @cblecker, sorry for the noise. Ben jumped into our triage meeting and provided more context. 

We do triages twice a week, and we go through everything that says: needs-triage. Now with more context, I understand your comment, I guess it's the first time in 5 years that happens to us. We do triage everything (open, merged, closed) for consistency and hygiene. 

It seems that we just found another crack in the process with this one. Could all the "closed" issues automatically get rid of the needs-triage label?

**Comment by cblecker** [comment]
@fedebongio I think `/triage unresolved` should help. We might be also able to add in a fejta-bot style commenter that looks for closed issues and PRs with needs-triage, and automatically applies the unresolved label

Happy to discuss more. Feel free to ping me on slack.

**Pull request closed without merging**
