### PR TITLE
e2e_storage:stop using deprecated framework.ExpectNotEqual

### PR DESCRIPTION
**Pull request by Rei1010**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
test/e2e/scheduling stop using deprecated framework.ExpectNotEqual

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/pull/115961

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by Rei1010** [comment]
@HirazawaUi @mattcary @chrishenzie ptal

**Comment by HirazawaUi** [comment]
Looks good, but need to wait for the sig-storage maintainer to review it further
/lgtm

**Comment by Rei1010** [comment]
@carlory ptal thx

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
