### PR TITLE
Promote existing E2E tests for Node Affinity validation to conformance

### PR DESCRIPTION
**Pull request by globervinodhn**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR requests for promotion of two existing E2E test cases to validate NodeAffinity and concerned pod scheduling to conformance. The two tests are listed below,
1. "validates that NodeAffinity is respected if not matching"
2. "validates that required NodeAffinity setting is respected if matching"

**Which issue(s) this PR fixes**: NONE
Fixes #

**Special notes for your reviewer**: Requests for promotion of 2 existing E2E test cases to conformance, details of which are as listed below,

1. "validates that NodeAffinity is respected if not matching"
   - The test takes approximately 7-9 seconds for execution.
   - The test verifies that the pod is not scheduled when there are no matching nodes are found as per the NodeAffinity values provided.
2. "validates that required NodeAffinity setting is respected if matching"
   - The test takes approximately 24 to 27 seconds for execution.
   - The test verifies that the pod is scheduled when there are no matching nodes are found as per the NodeAffinity values provided.

Both the tests are found to be non-flaky and non-disruptive in nature.

**Does this PR introduce a user-facing change?**: NONE

release-note-none

/area conformance

### CODE REVIEW

**Comment by spiffxp** [comment]
This is missing the required changes to `conformance.txt`

**Comment by globervinodhn** [comment]
> This is missing the required changes to `conformance.txt`

Have resolved the concern.

**Comment by spiffxp** [comment]
/close
These tests cannot be promoted as-is.

>Examples of tests which are not eligible to conformance:
>- anything that checks specific Events are generated, as we make no guarantees about the contents of events, nor their delivery
>  - If a test depends on events it is recommended to change the test to use an informer pattern and watch specific resource changes instead.

These tests both call `WaitForSchedulerAfterAction(...)` which uses `common.ObserveEventAfterAction(...)` in conjunction with predicates like `scheduleFailureEvent` that look at event fields, eg:
```go
func scheduleFailureEvent(podName string) func(*v1.Event) bool {
	return func(e *v1.Event) bool {
		return strings.HasPrefix(e.Name, podName) &&
			e.Type == "Warning" &&
			e.Reason == "FailedScheduling"
	}
}
```

**Pull request closed without merging**
