### PR TITLE
Make metadata fake client implement testing.FakeClient

### PR DESCRIPTION
**Pull request by howardjohn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This mirrors most (maybe all?) other fake clients. Example of a real
world use case this would have been useful:
https://github.com/istio/istio/pull/35434

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by howardjohn** [comment]
ping @caesarxuchao, do you have a chance to take a look?

**Comment by caesarxuchao** [comment]
Sorry for the delay.

/lgtm
/approve
/retest

**Comment by pacoxu** [comment]
/remove-sig api-machinery
bot hang

**Pull request merged**
