### PR TITLE
Docs updated for CLI deprecations

### PR DESCRIPTION
**Pull request by jorahn**
**What this PR does / why we need it**: Fixed docs

**Release note**: NONE

```release-note
```

### CODE REVIEW

**Review by gyliu513 — APPROVED** [review]

**Comment by jorahn** [comment]
Anything else required to merge this?

**Comment by brendandburns** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by jorahn** [comment]
edited Release note: NONE

**Pull request merged**
