### PR TITLE
Fixing timing issues with examples

### PR DESCRIPTION
**Pull request by goltermann**
Partial fixes for examples tests.

### CODE REVIEW

**Comment by goltermann** [comment]
Partial fix for #27086

**Comment by dchen1107** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by goltermann** [comment]
@spxtr can you take a look today?

**Comment by spxtr** [comment]
@goltermann is it a hassle to find a better reviewer for this? I don't have any context in these tests and I also don't have go readability.

If you think that's fine then I'll take a look.

**Comment by goltermann** [comment]
It's completely busted now, so I'm not going to make it worse :)

@jayunit100, you last touched this file - are you able to take a look?  See https://k8s-testgrid.appspot.com/k8s#gce-examples&width=5 for recent test history.

**Comment by jayunit100** [comment]
@tstclair I know how to fix this I think - for each needs a wait.  I hate the fact that the e2e folks are burdened by this but also realize examples/ are going to be deprecated soon. 

 What do you think we should do? @sig-testing

**Comment by spxtr** [comment]
@kubernetes/sig-testing ^^

**Comment by goltermann** [comment]
My fixes do work, are you suggesting there's a better way?

**Comment by spxtr** [comment]
LGTM, sorry for the delay.

**Pull request merged**
