### PR TITLE
k8s.io/client-go: add ClientConfig option to override raw config

### PR DESCRIPTION
**Pull request by IvoGoman**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The `clientcmd.ClientConfig` interface offers the [RawConfig](https://github.com/kubernetes/kubernetes/blob/6d83e22ba48e6e5c09c9b61612ecdf9ce07e4ccf/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L63) method, which states _RawConfig returns the merged result of all overrides_. 
The [existing implementation](https://github.com/kubernetes/kubernetes/blob/6d83e22ba48e6e5c09c9b61612ecdf9ce07e4ccf/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L128-L130) however only returns the plain RawConfig without overrides.

We have the use-case that we are generating KubeConfigs for remotely managed clusters and want to override fields in the RawConfig. This will enable us to use **client-go** directly instead of implementing this ourselves.

This PR adds a additional Constructor method `NewClientWithRawConfigOverride` which sets the new struct field 
`overrideRawConfig` to indicate the raw config returned should be merged with overrides.

Based on this field the `RawConfig` method will return a merged raw config or not.
```golang
func (config *DirectClientConfig) RawConfig() (clientcmdapi.Config, error) {
	switch config.overrideRawConfig {
	case true:
		return config.mergedRawConfig()
	default:
		return config.config, nil
	}
}
```

With the additional `overrideRawConfig` it should not impact or lead to unexpected behaviour with the current usage of `clientcmd.ClientConfig`

Over the years the have been several issues on k8s.io/client-go w.r.t. this problem [client-go#220](https://github.com/kubernetes/client-go/issues/220), [client-go#735](https://github.com/kubernetes/client-go/issues/735), [kubernetes#87554](https://github.com/kubernetes/kubernetes/issues/87554). But there has not been a definitive answer to whether or not this should be fixed directly in the RawConfig method. Thus, I am proposing this PR to not impact the existing behaviour.

#### Which issue(s) this PR fixes:

Fixes 87554

#### Does this PR introduce a user-facing change?
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by jiahuif** [comment]
/assign @deads2k
for context of #87554
/triage accepted

**Comment by IvoGoman** [comment]
Hey @deads2k, do you have time to review this?

**Comment by IvoGoman** [comment]
@yliaog would you mind taking a look at this PR?

**Comment by deads2k** [comment]
Discussed via slack and this was updated to leave the existing interface alone and produce a new method with a clear method indicating the new behavior and a new interface that contains the old.

/ok-to-test
/lgtm
/approve

**Pull request merged**
