### PR TITLE
[Federation] Expose autoscaling apis through federation api server

### PR DESCRIPTION
**Pull request by irfanurrehman**
This PR implements first part of federated pod autoscaler.
The issue to handle the whole feature is https://github.com/kubernetes/kubernetes/issues/38974

cc @kubernetes/sig-cluster-federation
@shashidharatd @kshafiee @deepak-vij

**Release note**:

```
federation users can now use federated autoscaling resources and create federated horizontalpodautoscalers
```

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
@mwielgus can you take this one?

**Comment by mwielgus** [comment]
@irfanurrehman - the code is mostly auto-generated, right? If yes then please do the rebase and get the tests green and I will LGTM it.

**Comment by irfanurrehman** [comment]
@mwielgus , yes you are right this one is mostly generated code.
I did rebase it yesterday night, and tests pass in my local env.
But not sure, why they are failing here. The logs don't look relavant to my portion of code at all.
Trying to figure out why they are failing here.

**Comment by irfanurrehman** [comment]
@k8s-bot test unit/integration

**Comment by irfanurrehman** [comment]
@k8s-bot test unit/integration this

**Comment by irfanurrehman** [comment]
@k8s-bot test this

**Comment by irfanurrehman** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by irfanurrehman** [comment]
@k8s-bot gci gce e2e test this

**Comment by irfanurrehman** [comment]
@k8s-bot cri node e2e test this

**Comment by irfanurrehman** [comment]
@mwielgus all tests pass as of now. Some tests seem flake to me, failures vanish if I rerun them (but not sure how to address them).
Also, it will be amazingly kind, if you can review this next PR in chain (mostly autogenerated code) https://github.com/kubernetes/kubernetes/pull/40158
and take a quick look at the actual controller code and give your comments here https://github.com/kubernetes/kubernetes/pull/40158

**Comment by irfanurrehman** [comment]
@mwielgus PTAL!, I have rebased it couple of times already.

**Comment by mwielgus** [comment]
LGTM

**Comment by irfanurrehman** [comment]
@mwielgus, I think you need to close the review also, to get this automatically merged.
thanks again!

**Comment by mwielgus** [comment]
No, you are in the merge queue but at position +10.  So it will take a while.

**Comment by irfanurrehman** [comment]
@mwielgus 
got it. Thanks for correcting my understanding!
It will be great if you can have a quick glance and give some suggestions for https://github.com/kubernetes/kubernetes/pull/40162 also.

**Pull request merged**
