### PR TITLE
Add ability to watch namespaces from client

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Add client methods to support watch of namespaces.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@dchen1107 can you take a look at this one?

**Comment by smarterclayton** [comment]
Add a client test please.

**Comment by derekwaynecarr** [comment]
@smarterclayton will add a test today that uses an EmptyWatch

**Comment by derekwaynecarr** [comment]
@smarterclayton - added a test case to validate watch constructs what we expect.

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
