### PR TITLE
Small refactor: Pretty object print util

### LINKED ISSUE #8976: Capture spew.Sprintf() with all our favorite config into a util func
util.PrettyPrintObject() or something.  Then find all the places that printf %#v on an object and use this instead.

### PR DESCRIPTION
**Pull request by fanzhangio**
- Fixed issue : https://github.com/kubernetes/kubernetes/issues/8976

**Which issue(s) this PR fixes** :
Fixes #8976
https://github.com/kubernetes/kubernetes/issues/8976

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anfernee** [comment]
cc @thockin

**Comment by janetkuo** [comment]
Test failures seem to be caused by merge conflicts, because "ok-to-test" is applied after "PR needs rebase".

**Comment by janetkuo** [comment]
I updated release note to be NONE (in PR description). PR won't get merged if the release-note process isn't followed.

**Comment by mml** [comment]
@fanzhangio Can you paste some before/after output so we can evaluate the change?

**Comment by fanzhangio** [comment]
PrettyPrintObject() will print object in a more structured way, with readable 

* Before output
"[{[{1.2.3.5  <nil> <nil>}] <nil> [{ 333 } { 222 }]} {[{1.2.3.4  <nil> <nil>} {1.2.3.6  <nil> <nil>}] <nil> [{ 111 }]}]"

* After output
"[{Addresses:[{IP:1.2.3.5 Hostname: NodeName:<nil> TargetRef:<nil>}] NotReadyAddresses:<nil> Ports:[{Name: Port:333 Protocol:} {Name: Port:222 Protocol:}]} {Addresses:[{IP:1.2.3.4 Hostname: NodeName:<nil> TargetRef:<nil>} {IP:1.2.3.6 Hostname: NodeName:<nil> TargetRef:<nil>}] NotReadyAddresses:<nil> Ports:[{Name: Port:111 Protocol:}]}]"

@mml

**Comment by fanzhangio** [comment]
@janetkuo 
The output is a pretty format of printed object with key value mapping rather than the raw "%+v"

**Pull request closed without merging**
