### PR TITLE
Automated cherry pick of #73968: record event on endpoint update failure

### PR DESCRIPTION
**Pull request by freehan**
Cherry pick of #73968 on release-1.10.

#73968: record event on endpoint update failure

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by freehan** [comment]
It looks like bazel-build on release-1.10 branch is broken?  @krzyzacy

**Comment by krzyzacy** [comment]
@freehan 1.10 is out of support now - we are in 1.14 cycle and we only run CI for three releases back.

**Comment by krzyzacy** [comment]
(and there should be no more 1.10 releases :-) )

**Comment by freehan** [comment]
Okay. Closing cherry-pick for 1.10

**Pull request closed without merging**
