### PR TITLE
Add some tests for printing pv

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

 /kind flake

**What this PR does / why we need it**:

In printers_test.go, currently printing pv tests are not included. I add some cases for it

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
@shiywang @deads2k 

PTAL thanks

**Comment by juanvallejo** [comment]
/ok-to-test
/lgtm

cc @soltysh @seans3 

@seans3 will this drift from / collide with any of the work you're doing externalizing printer handlers?

**Comment by cwdsuzhou** [comment]
> /ok-to-test
> /lgtm
> 
> cc @soltysh @seans3
> 
> @seans3 will this drift from / collide with any of the work you're doing externalizing printer handlers?

Collision has happened and I have fixed

**Review by shiywang — APPROVED** [review]

**Comment by cwdsuzhou** [comment]
@juanvallejo @shiywang could you take a look again since I have reset the PR to solve the collision

**Comment by cwdsuzhou** [comment]
ping @soltysh @liggitt @monopole

**Comment by juanvallejo** [comment]
/lgtm

cc @soltysh for approval

**Comment by cwdsuzhou** [comment]
/assign @smarterclayton @deads2k 

PTAL, thanks!

**Pull request merged**
