### PR TITLE
Update to adding proxier test that uses "iptables-restore --test" to validate iptables rules

### LINKED ISSUE #36850: Enhanced kube-proxy:iptables testing with iptables-restore --test
## FEATURE REQUEST:
At present the rules generated by kube-proxy (pkg/proxy/iptable/proxier) cannot be / are not validated  for syntactic correctness. 

### Options 1
```
iptables-restore --test
```
Given a rules set, it validates if the rules are correct.
This test does more than just syntactic validation.

1. It expects the kernel modules for tables to be loaded (or available for modprobe)
2. You need root privileges to run --test. 
Given this we can run the validation tests as part of e2e tests inside   docker container.

### Option 2
It is still desirable to have this as part of the unit test. 
Update iptables-restore.c to separate out the parser and then use it for proper unit test validation.

### PR DESCRIPTION
**Pull request by dougbtv**
**What this PR does / why we need it**: 

> "This PR tests iptable rules of the proxier on a live node, to make sure they are syntactically valid."
-yuval-k

Additionally, this PR replaces #47662

It repairs the tests to utilize the additional parameter added to the `runSSHCommand(...)` function in `./pkg/ssh/ssh.go`, as well as fixes the reference to the location of the `k8s.io/utils/exec/testing` package.

**Which issue(s) this PR fixes**:

fixes #36850

**Special notes for your reviewer**:

**Release note**:

```
Adding an e2e test to test the iptables proxier tools
```

### CODE REVIEW

**Comment by dougbtv** [comment]
I verified that the email address I have on the commit is the same as what I use to sign into the Linux Foundation, and the CNCF appears to show that I have signed the CLA. At least it says for groups: "Authorized CNCF Contributors", and trying to sign the CLA again, says: "You are already authorized to contribute code to this project through your membership with CNCF - Red Hat, Inc.."

**Comment by dougbtv** [comment]
...But did realize I hadn't associated that email address with this account, which I did in response to this. Should pass the CLA test, now, I think.

**Comment by cmluciano** [comment]
The verify checks are complaining about a format issue. A go-fmt over your patchset should fix this. Also run `./hack/update-bazel.sh` to make sure the build files are updated.

**Comment by dougbtv** [comment]
Thanks a bunch for the eyes @cmluciano -- and for finding this PR / closing out the other. I found the gofmt issue, and amended my PR with it. 

Question: Should I commit the changed `./test/e2e/BUILD` file after running the `./hack/update-bazel.sh`?

**Comment by cmluciano** [comment]
Yep, the generated file needs commited

**Comment by dougbtv** [comment]
Thanks again @cmluciano -- I wound up generating it incorrectly, but got that file amended in there on a subsequent try (generating a lot of work and output from the poor CI robot), and it looks like it might have passed, this time.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-pr-reviews

**Comment by cmluciano** [comment]
/retest 

guess the device-plugin is a flake, but I will look into it

**Pull request closed without merging**
