### PR TITLE
Move ncdc to emeritus

### PR DESCRIPTION
**Pull request by ncdc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I am moving myself to emeritus as I am now firmly on the end-user side of things.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @jpbetz @janetkuo @BenTheElder 

Assigning one person from each SIG
/triage accepted

**Review by janetkuo — APPROVED** [review]

**Review by BenTheElder — COMMENTED** [review]
Docs: https://go.k8s.io/owners

bikeshedding here, but we usually use `emeritus_approvers` field (like `approvers`) which could be read by tooling 😅 

Thank you for PR-ing yourself out when you don't have the time.

**Comment by ncdc** [comment]
> bikeshedding here, but we usually use emeritus_approvers field

I'll make the change. I was following what is in `OWNERS_ALIASES`

**Comment by ncdc** [comment]
@BenTheElder ok I made the change everywhere, including OWNERS_ALIASES. Might not be what we want. PTAL & let me know. Thanks!

**Comment by ncdc** [comment]
Now I see why they were commented out in OWNERS_ALIASES

**Pull request merged**
