### PR TITLE
Another temp. fix for the API not showing in k8s.io - also resolves the script overwrite issue

### PR DESCRIPTION
**Pull request by RichieEscarez**
Renaming the old api docs for the time being so that the .md files are rendered in Jekyll. The source that gets used with the .md files is located in gh-pages in the _indcludes folder (the source being a copy of these .html files that have been manually edited) - this is a temporary fix

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@RichieEscarez, we shouldn't rename these two files, because probably we have links that directs people to these two files. I can add several lines in gh-pages/_tools/release_docs/main.go. to move these two files to _include when copying from master.

**Comment by nikhiljindal** [comment]
Yes, we have links directing people to these files.
Updating the tool to move these files to _include while importing them from master is a better fix.

**Comment by thockin** [comment]
Agree we should not do this in master.

I made the equivalent manual changes in my personal fork (dump docs/api-reference.html into _includes, remove v1.0/docs/api-reference/*.html).  It's not quite working as I expect.  Is there more processing that needs to happen to these HTML files?

http://thockin.github.io/kubernetes/v1.0/

**Comment by caesarxuchao** [comment]
It seems your html files include some <head> twice, e.g., starting from line 627 in your definitions.html,
```
<p>&lt;!DOCTYPE html&gt;<html lang="en"><head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
```

I don't know if this causes the mess in the webpage though.

**Comment by thockin** [comment]
I just copied the HTML files from v1.0/docs/api-reference into _includes.
It does not diff cleanly against head, I assume because of your transforms,
which I don't know what they are doing.

The files in _include are full HTML files, with DOCTYPE etc, but it seems
they should not be - is your HTML preprocessing step supposed to strip that
out?

**Comment by caesarxuchao** [comment]
No, my transform is not striping those. It's not supposed to work with
Richie's manual changes.

I think what Richie does is copying the html from master, not
gh-pages, removing DOCTYPE tag, then moving to the _include.

I plan to submit a PR tomorrow to automate this.

On Saturday, July 25, 2015, Tim Hockin <notifications@github.com> wrote:

> I just copied the HTML files from v1.0/docs/api-reference into _includes.
> It does not diff cleanly against head, I assume because of your transforms,
> which I don't know what they are doing.
>
> The files in _include are full HTML files, with DOCTYPE etc, but it seems
> they should not be - is your HTML preprocessing step supposed to strip that
> out?
>
> On Sat, Jul 25, 2015 at 1:55 PM, Chao Xu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > It seems your html files include some twice, e.g., starting from line 627
> > in your definitions.html,
> >
> > <p>&lt;!DOCTYPE html&gt;<html lang="en"><head>
> > <meta charset="utf-8"/>
> > <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
> >
> > I don't know if this causes the mess in the webpage though.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124892661
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124896692>
> .
>


-- 
Regards,
Chao Xu

**Comment by thockin** [comment]
I am out now, but I can fix it manually later and wait for your automation.

**Comment by caesarxuchao** [comment]
Thank you!

On Saturday, July 25, 2015, Tim Hockin <notifications@github.com> wrote:

> I am out now, but I can fix it manually later and wait for your automation.
> On Jul 25, 2015 2:33 PM, "Chao Xu" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > No, my transform is not striping those. It's not supposed to work with
> > Richie's manual changes.
> >
> > I think what Richie does is copying the html from master, not
> > gh-pages, removing DOCTYPE tag, then moving to the _include.
> >
> > I plan to submit a PR tomorrow to automate this.
> >
> > On Saturday, July 25, 2015, Tim Hockin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I just copied the HTML files from v1.0/docs/api-reference into
> _includes.
> > > It does not diff cleanly against head, I assume because of your
> > transforms,
> > > which I don't know what they are doing.
> > >
> > > The files in _include are full HTML files, with DOCTYPE etc, but it
> seems
> > > they should not be - is your HTML preprocessing step supposed to strip
> > that
> > > out?
> > >
> > > On Sat, Jul 25, 2015 at 1:55 PM, Chao Xu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > It seems your html files include some twice, e.g., starting from line
> > 627
> > > > in your definitions.html,
> > > >
> > > > <p>&lt;!DOCTYPE html&gt;<html lang="en"><head>
> > > > <meta charset="utf-8"/>
> > > > <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
> > > >
> > > > I don't know if this causes the mess in the webpage though.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124892661
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124896692
> > >
> > > .
> > >
> >
> >
> > --
> > Regards,
> > Chao Xu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124898875
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/11850#issuecomment-124910473>
> .
>


-- 
Regards,
Chao Xu

**Pull request closed without merging**
