### PR TITLE
test: use low terminationGracePeriod for deployment test

### LINKED ISSUE #32692: [k8s.io] Deployment paused deployment should be ignored by the controller {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/15525/

Failed: [k8s.io] Deployment paused deployment should be ignored by the controller {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:74
Sep 14 11:33:00.885: Err : timed out waiting for the condition
. Failed to remove deployment test-paused-deployment pods : &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1/namespaces/e2e-tests-deployment-9ki39/pods ResourceVersion:3586} Items:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-paused-deployment-965846846-8nxge GenerateName:test-paused-deployment-965846846- Namespace:e2e-tests-deployment-9ki39 SelfLink:/api/v1/namespaces/e2e-tests-deployment-9ki39/pods/test-paused-deployment-965846846-8nxge UID:826ad71f-7aa9-11e6-8b7c-42010af0002f ResourceVersion:2271 Generation:0 CreationTimestamp:2016-09-14 11:31:53 -0700 PDT DeletionTimestamp:2016-09-14 11:32:19 -0700 PDT DeletionGracePeriodSeconds:0xc820cfd830 Labels:map[name:nginx pod-template-hash:965846846] Annotations:map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"e2e-tests-deployment-9ki39","name":"test-paused-deployment-965846846","uid":"8260c449-7aa9-11e6-8b7c-42010af0002f","apiVersion":"extensions","resourceVersion":"1902"}}
] OwnerReferences:[] Finalizers:[] ClusterName:} Spec:{Volumes:[{Name:default-token-2oveh VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc82111c180 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> Quobyte:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil> VsphereVolume:<nil> AzureDisk:<nil>}}] InitContainers:[] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx-slim:0.7 Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-2oveh ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc820cfd930 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:gke-jenkins-e2e-default-pool-2fce17a8-qope SecurityContext:0xc820fad4c0 ImagePullSecrets:[] Hostname: Subdomain:} Status:{Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-14 11:31:53 -0700 PDT Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-14 11:31:53 -0700 PDT Reason:ContainersNotReady Message:containers with unready status: [nginx]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-14 11:31:53 -0700 PDT Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP: StartTime:2016-09-14 11:31:53 -0700 PDT InitContainerStatuses:[] ContainerStatuses:[{Name:nginx State:{Waiting:0xc821117cc0 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/nginx-slim:0.7 ImageID: ContainerID:}]}}]}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:249
```

Previous issues for this test: #28067 #28378

### PR DESCRIPTION
**Pull request by 0xmichalis**
Hopefully fixes https://github.com/kubernetes/kubernetes/issues/32692

@janetkuo PTAL

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33011)

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/32770

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/32685

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@k8s-bot gce e2e test this issue: https://github.com/kubernetes/kubernetes/issues/31776

**Comment by kargakis** [comment]
@k8s-bot gce e2e test this issue: #31776

**Comment by janetkuo** [comment]
LGTM too

**Pull request merged**
