### PR TITLE
Remove duplicate deleteAllEtcdKeys() from integration tests.

### PR DESCRIPTION
**Pull request by jsafrane**

### CODE REVIEW

**Comment by ixdy** [comment]
needs rebase, otherwise LGTM

**Comment by jsafrane** [comment]
Rebased

**Comment by ixdy** [comment]
LGTM

**Comment by jsafrane** [comment]
rebased (fixing compilation error)

**Comment by ixdy** [comment]
@k8s-bot unit test this, flake #28076

still LGTM

**Comment by ixdy** [comment]
@k8s-bot node e2e test this, issue #28047 (and maybe others)

**Pull request merged**
