### PR TITLE
Fix typo on words situations and response

### PR DESCRIPTION
**Pull request by DasyDong**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix two typo :   

* situarions should be situations
* repsonses  should be responses

**Which issue(s) this PR fixes:**
Fixes #

**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig docs
/priority backlog

### CODE REVIEW

**Comment by oomichi** [comment]
/retest

after https://github.com/kubernetes/kubernetes/pull/87196 is merged

**Comment by DasyDong** [comment]
If no more response  in one weeks, I will close this pr

**Pull request closed without merging**
