### PR TITLE
Use scheduler.New() Instead of factory.NewConfigFactory() in volumescheduling Integration Test

### PR DESCRIPTION
**Pull request by ahmad-diaa**
**What type of PR is this?**
/kind cleanup
/sig scheduling

/assign @alculquicondor 

**What this PR does / why we need it**:
Moving users of `factory.NewConfigFactory` to `scheduler.New`

**Which issue(s) this PR fixes**:

Part of #71859

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority backlog
/retest

**Comment by liggitt** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Pull request merged**
