### PR TITLE
delete unreachable code

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**What this PR does / why we need it**:
After panic， the code is unreachable，delete them.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by YuPengZTE** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot kops aws e2e test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
