### PR TITLE
fix e2e test `test should assign default SC to PVCs that have no SC set` failure

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
When the cluster exists `storageclass.kubernetes.io/is-default-class: "true"
` When annotating the storage class, the e2e test case `test should assign default SC to PVCs that have no SC set` reports an error.
```
   Jan 31 14:06:57.427: INFO: Success - PersistentVolumeClaim retro-pvc-krf4d got updated retroactively with StorageClass retroqr5w4
   Jan 31 14:06:57.442: INFO: Unexpected error:
       <*errors.StatusError | 0xc0006fc8c0>:
       Operation cannot be fulfilled on storageclasses.storage.k8s.io "provisioning-nfs": the object has been modified; please apply your changes to the latest version and try again
       {
           ErrStatus:
               code: 409
               details:
                 group: storage.k8s.io
                 kind: storageclasses
                 name: provisioning-nfs
               message: 'Operation cannot be fulfilled on storageclasses.storage.k8s.io "provisioning-nfs":
                 the object has been modified; please apply your changes to the latest version and
                 try again'
               metadata: {}
               reason: Conflict
               status: Failure,
       }
   [FAILED] in [It] - test/e2e/storage/pvc_storageclass.go:152 @ 01/31/24 14:06:57.442

```
#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mattcary** [comment]
/lgtm

thank you!

**Review by yangjunmyfm192085 — COMMENTED** [review]
/test pull-kubernetes-e2e-kind

**Review by pohly — APPROVED** [review]
/approve

**Pull request merged**
