### PR TITLE
Update docker instructions to 1.0.1

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by brendandburns** [comment]
Jenkins is clearly a flake...

**Comment by dalanlan** [comment]
Why dont you take etcd:2.1.0 into consideration? 2.1.x seems to be a big step:-)

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
@dalanlan 
We haven't switched to etcd 2.1.x for Kubernetes in general.  We should do that, but we'll need to run it through lots of testing first.

We had already updated to 2.0.12 for all of the other kubernetes installs.

**Comment by mikedanese** [comment]
LGTM

**Comment by mikedanese** [comment]
e2e is a flake

**Pull request merged**
