### PR TITLE
Merge release 0.18.2 back into to master

### PR DESCRIPTION
**Pull request by brendandburns**
@zmerlynn @eparis @dchen1107

### CODE REVIEW

**Comment by eparis** [comment]
huh?  0 changes?  again?

**Comment by brendandburns** [comment]
yeah, what is even weirder is that the commit https://github.com/brendandburns/kubernetes/commit/5920e2764a44e435771363bd18720742e18386c9 shows the diff I would expect...

--brendan

**Comment by eparis** [comment]
so what went wrong today?  what's this stuff I see in the tree about reverts and stuff?  give me a headstart on my new detective work....

**Comment by brendandburns** [comment]
so I accidentally merged the release branch changes into master, and then I reverted them...

I just keep finding new ways to mess this process up... *sigh*

**Comment by eparis** [comment]
ok, so you did the merge, so you were done and all was well in the world (even though you skipped the PR step I guess?)  But then you reverted.

Now when you try to merge again good see 'you already added the commit that changed pkg/version/base.go and then you made another change to it, so the version in the tree must be the newer/better version'   So it didn't update it again.

Since you already did the merge, and it seems to have been a good merge, how about a plain normal PR that just updates pkg/version/base.go

**Pull request closed without merging**
