### PR TITLE
Revert "Add the ability to edit fields within a config map."

### LINKED ISSUE #40396: kubectl edit not working
kubectl edit is not working on HEAD. It's working on 1.5.

```
$ kubectl edit -f pod.yaml
error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well
```

@kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #40396 
This reverts commit 31eca372c9a228ca825c2dbc93a7880a8b06946f.

#38445 broke edit for all resources other than configmaps:
```
$ kubectl edit serviceaccount default
Error from server (NotFound): configmaps "serviceaccount" not found
```
also, `edit` is a generic command, we can't add subcommands that claim the `configmap` space and mess with the things resourcebuilder accepts

### CODE REVIEW

**Comment by liggitt** [comment]
cc @brendandburns @fabianofranz @kubernetes/sig-cli-pr-reviews

**Comment by fabianofranz** [comment]
I'll investigate how the tests didn't catch that.

**Comment by liggitt** [comment]
LGTM by original reviewer, approving to get the revert in the queue

**Comment by liggitt** [comment]
cc @k8s-oncall once tests are green

**Comment by liggitt** [comment]
> I'll investigate how the tests didn't catch that.

looks like a known issue - https://github.com/kubernetes/kubernetes/issues/39168

**Comment by bgrant0607** [comment]
Thanks

**Comment by fabianofranz** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/40396

**Pull request merged**
