### PR TITLE
deps: opencontainers/go-digest -> v1.0.0

### PR DESCRIPTION
**Pull request by endocrimes**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates opencontainers/go-digest to the released version of v1.0.0.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Nice! looks like no code changes as such, just docs/comments/headers etc.

**Comment by endocrimes** [comment]
looks like a flake? but gonna retest to be sure
/retest

**Comment by dims** [comment]
@endocrimes so here's how you check if it is a flake. Make sure you switch on `CI` check box next to `Include results from`

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=MirrorPodWithGracePeriod

**Comment by dims** [comment]
@endocrimes looks like this needs a rebase.

**Comment by endocrimes** [comment]
@dims bumped

**Comment by dims** [comment]
thanks! let's wait for main branch to open up for business.

**Comment by endocrimes** [comment]
@dims Curious as to when the main branch is opening back up? - Pruning PRs and just saw this again :sweat_smile:

**Pull request merged**
