### PR TITLE
Move the remaining kubectl bits to k8s.io/kubectl

### LINKED ISSUE #725: Determine what happens to the "kubectl convert" functionality
## kubectl convert is deprecated

The initial `kubectl convert` deprecation was announced prior to release 1.13. Following the Kubernetes deprecation policy, this `kubectl` subcommand is now eligible to be removed in release 1.17. The following are options for next steps as this `convert` functionality is removed from `kubectl`. If you have an opinion, please add comments to this issue so that we can quickly drive consensus and make a decision on which option we will pursue.

- [Convert as a Plugin](#convert-as-a-plugin)
- [Convert as a Binary](#convert-as-a-binary)
- [Convert into the API Server](#convert-into-the-api-server)
- [Drop convert functionality](#drop-convert-functionality)

## Convert as a Plugin

We could move the `kubectl convert` code into a plugin named `kubectl-convert`. The invocation of the plugin would mimic the current command: `kubectl convert`.

- **Pro**: Users depending on this functionality will still be able to convert resource versions.
- **Pro**: The command will appear similar. Naming the plugin `kubectl-convert` will ensure `kubectl` users can type the same command: `kubectl convert`.
- **Con**: The users will have to find and download this separate binary.
- **Con**: The plugin would have to vendor in most of the Kubernetes.

## Convert as a Binary

- **Pro**: Users depending on this functionality will still be able to convert resource versions.
- **Con**: The users will have to find and download this separate binary.
- **Con**: The plugin would have to vendor in most of the Kubernetes.

## Convert into the API Server

- **Pro**: Users depending on this functionality will still be able to convert resource versions.
- **Pro**: Convert code already lives in the API machinery.
- **Con**: It may take a long time to get this into the API Server.

## Drop convert functionality

- **Pro**: This will be the simplest to implement; just remove `kubectl convert` subcommand code.
- **Con**: Users depending on this functionality will *NOT* be able to convert resource versions.

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is culmination of the efforts from https://github.com/kubernetes/enhancements/issues/1020

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubectl/issues/725

**Special notes for your reviewer**:
/assign @pwittrock @seans3 

**Does this PR introduce a user-facing change?**:
```release-note
Introduce kubectl-convert plugin. 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1020-kubectl-staging/README.md
- [Code Organization Agenda]: https://docs.google.com/document/d/1HtTI0rJEGP_MSf6eO87aCmx_tzpovPAAg7U2Zxwm8FE/edit?ts=5c9d0a4c#bookmark=id.fqfpdy1w5idg
```

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
for sufficient exposure

**Comment by kikisdeliveryservice** [comment]
Is this PR somehow stuck? It's been passing but tide pending for a long time now.. :thinking:

**Comment by soltysh** [comment]
> Is this PR somehow stuck? It's been passing but tide pending for a long time now.. thinking

I'm seeing problems with `pkg/kubelet/cm/devicemanager` mentioned in https://github.com/kubernetes/kubernetes/issues/94528
I'll keep an eye on this one.

**Comment by piradata** [comment]
> - [Code Organization Agenda]: https://docs.google.com/document/d/1HtTI0rJEGP_MSf6eO87aCmx_tzpovPAAg7U2Zxwm8FE/edit?ts=5c9d0a4c#bookmark=id.fqfpdy1w5idg

this was shared as anyone with the link can edit

**Pull request merged**
