### PR TITLE
Bash completion annotations for rollingupdates

### PR DESCRIPTION
**Pull request by eparis**
This updates the generated bash completions so that either the --filename= or the --image flags will be automatically suggested to users.  As one of these is required for the command to be useful.

### CODE REVIEW

**Comment by eparis** [comment]
This is not ready for merge.  The shippable problem seems like it may be real. Will update after I dig deeper.

**Comment by bgrant0607** [comment]
Cc @nikhiljindal @ironcladlou

This PR also enables kubectl to take multiple filenames. Please update the PR description and docs.

**Comment by eparis** [comment]
@bgrant0607 it does not though (at least it's not supposed to) as i check to make sure only 1 name was given an error if not.

**Comment by eparis** [comment]
fixed the test shown by shippable.  It does not have a change as @bgrant0607 was concerned.  While the command line will take a comma separated list, or even using -f multiple time, such an invocation will be rejected in the argument validation function.

**Comment by jlowdermilk** [comment]
lgtm, needs rebase

**Comment by eparis** [comment]
rebased.

**Comment by eparis** [comment]
rebased again (rebases due to changed in docs/, not in other code)

**Pull request merged**
