### PR TITLE
Optimize provisioner plugin result check logic

### PR DESCRIPTION
**Pull request by NickrenREN**
If err is not returned by findProvisionablePlugin(...), storageClass is certainly not nil

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by saad-ali** [comment]
This PR might go against the top comment in that file:

```
// PLEASE DO NOT ATTEMPT TO SIMPLIFY THIS CODE.
// KEEP THE SPACE SHUTTLE FLYING.
```

Will let @jsafrane review.

**Comment by jsafrane** [comment]
> // PLEASE DO NOT ATTEMPT TO SIMPLIFY THIS CODE.
> // KEEP THE SPACE SHUTTLE FLYING.

That applies to the gigantic if-then-else tree in binding code, provisioning is much simpler and easier to refactor.

Indeed, now that alpha provisioning is gone `findProvisionablePlugin` can't return nil class.

/assign
/lgtm

**Comment by jsafrane** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
