### PR TITLE
defaultpodtopologyspread: access listers in plugin instantiation

### PR DESCRIPTION
**Pull request by adtac**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR is a cherry pick of https://github.com/kubernetes/kubernetes/pull/92840 into the 1.18 release branch. See that PR for more details.

**Which issue(s) this PR fixes**:

Updates https://github.com/kubernetes/kubernetes/issues/92781

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig scheduling
/cc @alculquicondor @ahg-g

### CODE REVIEW

**Comment by alculquicondor** [comment]
Also reference #87905

**Comment by alculquicondor** [comment]
/ok-to-test

/lgtm
/approve
from scheduling

**Comment by alculquicondor** [comment]
@kubernetes/release-managers

**Comment by alculquicondor** [comment]
@kubernetes/release-managers

**Comment by jkaniuk** [comment]
@kubernetes/release-managers

**Pull request merged**
