### PR TITLE
Add docs around importing auth plugins

### LINKED ISSUE #545: README does not mention authentication plugins
The client-go README does not even mention the fact that authentication plugins exist.  It should be explained that they exist and how to get the desired ones plugged in.

You can see in #242 and #345 other developers who suffered from this lack of information.

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Documents the method for adding auth plugin support

**Which issue(s) this PR fixes**:
fixes https://github.com/kubernetes/client-go/issues/545

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig api-machinery
cc @MikeSpreitzer

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
How about putting a mention of plugins in the main README?

**Comment by liggitt** [comment]
> How about putting a mention of plugins in the main README?

There's no other API-level documentation in the README, and it explicitly directs to two of these examples for in-pod and out-of-pod use.

I did open https://github.com/kubernetes/client-go/pull/546 to call out the package in the listing of interesting things provided

**Comment by MikeSpreitzer** [comment]
@liggitt - good enough answer.  Thanks.

**Pull request merged**
