### PR TITLE
Migrated scheduler files binder.go binder_test.go to structured logging

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: jyz0309 <45495947@qq.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Ref #105841 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by shivanshuraj1333 — CHANGES_REQUESTED** [review]

**Comment by Huang-Wei** [comment]
LGTM. Could you squash the commits?

**Comment by jyz0309** [comment]
> LGTM. Could you squash the commits?

Done.

**Comment by pohly** [comment]
> > LGTM. Could you squash the commits?
> 
> Done.

Can you also rewrite the commit message of the remaining commit? See https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines

**Comment by jyz0309** [comment]
> > > LGTM. Could you squash the commits?
> > 
> > 
> > Done.
> 
> Can you also rewrite the commit message of the remaining commit? See https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines

Done! Thanks for reminding!

**Comment by pohly** [comment]
> Done! Thanks for reminding!

The commit message body still contains the result of squashing and multiple signed-off-by lines. What it should have is a short summary of why this is useful and a reference to the issue.

But let's merge it anyway:

/lgtm
/approve

**Comment by pohly** [comment]
/assign @xing-yang 

For approval.

**Pull request merged**
