### PR TITLE
Storage Validation: Promote multivolume test.

### PR DESCRIPTION
**Pull request by brahmaroutu**
This PR promotes existing test to Validation Suite. A Validation test can then be promoted to a Conformance test if it is determined to be portable.

/sig storage
/sig testing
/area conformance
/kind test
/release-note none

### CODE REVIEW

**Review by alejandrox1 — APPROVED** [review]
Need to run gofmt on this but overall it looks good.

/priority important-longterm
/kind feature
/lgtm

**Comment by alejandrox1** [comment]
[pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/74697/pull-kubernetes-e2e-gce/70607/) failed previously but none of the failures seem directly related to this so let's see what happens after another run.

/test pull-kubernetes-e2e-gce

**Comment by msau42** [comment]
/hold

Can we have a detailed plan/KEP/spreadsheet of what test cases we want to add to the storage validation suite and get it reviewed and approved by sig-storage?

**Comment by brahmaroutu** [comment]
@msau42 I would like to work on getting a google doc with the list of tests. We can iterate on it.

**Comment by msau42** [comment]
Sounds good thanks!

**Comment by alejandrox1** [comment]
@brahmaroutu @msau42 any updates on this PR?

**Comment by msau42** [comment]
I think it would be good to come up with a detailed plan on how to test persistent storage in k8s conformance. I unfortunately don't have the bandwidth to do this, but would be happy to discuss and review, along with @johnbelamaric

**Review by andrewchoi5 — APPROVED** [review]

**Pull request closed without merging**
