### PR TITLE
Handle deleted DaemonSet properly

### LINKED ISSUE #64313: Foreground deletion for daemonset doesn't work
/kind bug
/priority critical-urgent

**What happened**:
In https://github.com/kubernetes/kubernetes/pull/63979 I'm removing all the reapers, unfortunately when invoking foreground deletion on a DaemonSet the delete operation hangs and controller indefinitely tries to manage a removed DS. 

**What you expected to happen**:
A foreground deletion properly removes DaemonSet and all its dependents. 

**How to reproduce it (as minimally and precisely as possible)**:
Invoke a delete operation against kube API (without using `kubectl delete` command). 

**Anything else we need to know?**:
This behavior makes it so that none of the consumers of the API is not able to remove the DS controller due to [this custom logic](https://github.com/kubernetes/kubernetes/blob/8b442973ac950faa1ecc580df75b756062a937a5/pkg/kubectl/delete.go#L300-L324) present in the DS reaper. A working fix that passed the tests with the aforementioned PR is in https://github.com/kubernetes/kubernetes/pull/64306 but I'm not 100% it's correct. 

This is an issue that needs fixing before 1.11 goes out.

/assign @kow3ns @janetkuo 
/sig apps

/cc @deads2k

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:
After kubectl reapers are removed (#63979) and foreground deletion are used, DaemonSet controller may race with garbage collector when it tries to update DaemonSet status of the DaemonSet being deleted. 

Here's what happened:
1. Someone/something performs a foreground deletion on a DaemonSet
1. DaemonSet finalizer and DeletionTimestamp are both set
1. DaemonSet history objects (ControllerRevisions) and pods are being deleted by garbage collector; meanwhile, DaemonSet controller tries to update DaemonSet status. 
    * Updating DaemonSet status requires constructing DaemonSet history objects, to figure out current revision and which pods do/don't belong to current revision
1. When updating DaemonSet status, DaemonSet controller tries to create a DaemonSet history object that matches current DaemonSet spec
1. Garbage collector then tries to delete that DaemonSet history object. And repeat. 

Because we can't make DaemonSet pods be deleted before DaemonSet history objects (DaemonSet history objects don't own DaemonSet pods!), we cannot reliably calculate DaemonSet status without history objects anyways. Therefore, we don't update DaemonSet status for DaemonSet being deleted. 

Note that the reason why the kubectl delete hack works is because it forces DaemonSet pods to be removed before history objects. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64313

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by janetkuo** [comment]
I decided not to add a release note for this fix, but can add one if the reviewer thinks it's necessary.

**Comment by liggitt** [comment]
will the "Skip updating status for DaemonSet being deleted" fix need to be picked to older releases?

**Comment by liggitt** [comment]
> kubectl reapers are removed in 1.11 which exposed this problem. This fix will be in 1.11 too.

kubectl 1.11 can run delete against 1.10.x. I think we should pick the controller change at least to 1.10.

**Comment by janetkuo** [comment]
> kubectl 1.11 can run delete against 1.10.x. I think we should pick the controller change at least to 1.10.

Good catch! In this case, we should probably keep the kubectl hack (i.e. revert the 2nd commit) in 1.11 until 1.12. Otherwise users can still hit this problem with 1.11 kubectl + 1.10.0-4 server.

**Comment by liggitt** [comment]
> In this case, we should probably keep the kubectl hack (i.e. revert the 2nd commit) in 1.11 and remove it in 1.12.

That would be ugly, but short-lived.

I still think we should also pick back the actual API fix for clients that use foregroundDeletion

**Comment by janetkuo** [comment]
For keeping the kubectl hack in 1.11: https://github.com/kubernetes/kubernetes/pull/64847

**Comment by soltysh** [comment]
> For keeping the kubectl hack in 1.11: #64847

I'm inclined to leave it there even until 1.13.

**Comment by zparnold** [comment]
Hello there! @janetkuo I'm Zach Arnold working on Docs for the 1.11 release. This PR was identified as one needing some documentation in the https://github.com/kubernetes/website repo around your contributions (thanks by the way!) When you have some time, could you please modify/add/remove the relevant content that needs changing in our documentation repo? Thanks! Please let me or my colleague Misty know (@zparnold/@Misty on K8s Slack) if you need any assistance with the documentation.

**Comment by janetkuo** [comment]
@zparnold sorry didn't notice your message until now. I don't think this PR needs documentation. It's fixing an old bug that could cause some trouble when people delete their DaemonSet without using kubectl. Did someone ask for a doc for this PR?

**Comment by zparnold** [comment]
@jberkus did. Or at least he flagged it as something potentially needing documentation around it.

**Pull request merged**
