### PR TITLE
test: prefer NoError/Error over Nil/NotNil

### PR DESCRIPTION
**Pull request by trashhalo**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
replaces calls to require/assert Nil/NotNil to NoError/Error

[NoError](https://godoc.org/github.com/stretchr/testify/require#NoError) is for asserting no error was return
[Error](https://godoc.org/github.com/stretchr/testify/require#Error) is for asserting an error was returned

```golang
return Fail(t, fmt.Sprintf("Received unexpected error:\n%+v", err), msgAndArgs...)
```
```golang
return Fail(t, "An error is expected but got nil.", msgAndArgs...)
```
When these fail their message explicitly calls out that we were or were not expecting an error. This communicates the intent of the assertion.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by trashhalo** [comment]
cla signed. im not sure how to kick it so it rechecks.

**Comment by trashhalo** [comment]
@kikisdeliveryservice 1. awesome name. 2. sorry I noticed there was a email I was supposed to click for the cla. email clicked.

**Comment by trashhalo** [comment]
none of the test failures look related to the test changes I made. Example:

pull-kubernetes-e2e-azure-file-windows #1285374967063515136

error creating cluster: cannot deploy: cannot get the create deployment future response: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-1'. Error message: \\\"Command execution finished, but failed because it returned a non-zero exit code of: '1'\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"}]

uh wat?

**Comment by kikisdeliveryservice** [comment]
I believe that your test changes are run in `pull-kubernetes-bazel-test `as they are unit tests. You can look at the log (scroll doooown :smile: ) https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/93214/pull-kubernetes-bazel-test/1285374962059710470/build-log.txt
```
//pkg/controller/endpointslice:go_default_test                           PASSED in 39.5s
//pkg/kubelet/cm:go_default_test                                         PASSED in 4.1s
//pkg/kubelet/dockershim:go_default_test                                 PASSED in 4.0s
//pkg/volume/awsebs:go_default_test                                      PASSED in 4.4s
//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured:go_default_test PASSED in 4.9s
//staging/src/k8s.io/apimachinery/pkg/util/net:go_default_test           PASSED in 35.0s
//staging/src/k8s.io/apiserver/pkg/audit/policy:go_default_test          PASSED in 3.2s
//staging/src/k8s.io/client-go/testing:go_default_test                   PASSED in 37.5s
//staging/src/k8s.io/legacy-cloud-providers/aws:go_default_test          PASSED in 11.8s
//staging/src/k8s.io/legacy-cloud-providers/azure:go_default_test        PASSED in 14.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/containerserviceclient:go_default_test PASSED in 3.6s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/deploymentclient:go_default_test PASSED in 4.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/interfaceclient:go_default_test PASSED in 80.0s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/loadbalancerclient:go_default_test PASSED in 3.2s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/publicipclient:go_default_test PASSED in 82.1s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/securitygroupclient:go_default_test PASSED in 26.1s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/snapshotclient:go_default_test PASSED in 132.1s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient:go_default_test PASSED in 30.2s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/subnetclient:go_default_test PASSED in 2.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmclient:go_default_test PASSED in 20.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmsizeclient:go_default_test PASSED in 3.2s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmssclient:go_default_test PASSED in 25.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmssvmclient:go_default_test PASSED in 82.9s
//staging/src/k8s.io/legacy-cloud-providers/azure/retry:go_default_test  PASSED in 5.5s
//staging/src/k8s.io/legacy-cloud-providers/gce:go_default_test          PASSED in 5.5s
```



They passed :)

Those unrelated e2e are likely flakes (as you only modified unit tests and no code) and we can retest.

/retest

**Review by RoundNutz4 — APPROVED** [review]

**Comment by trashhalo** [comment]
dealt with the conflict :D

**Comment by trashhalo** [comment]
Oh man these tests are flakey. Thanks for poking this pr @SergeyKanzhelev !! You are the best

**Comment by SergeyKanzhelev** [comment]
> Oh man these tests are flakey. Thanks for poking this pr @SergeyKanzhelev !! You are the best

there is [some instability](https://kubernetes.slack.com/archives/C2C40FMNF/p1600288237351500) that I think got fixed. So should all pass now =)

**Pull request merged**
