### PR TITLE
Make hugepages comparison work on 32-bit platforms

### LINKED ISSUE #51978: cross-build: PR 50072 causing cross build failure
```
I0905 20:53:34.195] # k8s.io/kubernetes/pkg/volume/empty_dir
I0905 20:53:34.195] pkg/volume/empty_dir/empty_dir_linux.go:54: constant 2508478710 overflows int32
```
https://github.com/kubernetes/kubernetes/pull/50072
https://k8s-testgrid.appspot.com/misc#cross-build
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/3195

---
cc: @kubernetes/sig-node-bugs @kubernetes/sig-node-test-failures @childsb @derekwaynecarr @eparis @smarterclayton @squall0gd
/kind bug
/priority failing-test

### PR DESCRIPTION
**Pull request by liggitt**
fixes #51978

### CODE REVIEW

**Comment by dims** [comment]
LGTM Statfs_t.Type is int64 or int32 based on platform 👍

**Comment by liggitt** [comment]
kops failure is known and unrelated

**Comment by sjenning** [comment]
thanks!
/lgtm

**Comment by ericchiang** [comment]
Manually marking as approved since this breaks cross-compilation for the release process.

**Comment by thockin** [comment]
Marking as critical fix

**Pull request merged**
