### PR TITLE
Removed mesos related labels.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
I'm going to move Mesos related to kube-meos or close it. So remove mesos related labels.

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by thockin** [comment]
If you remove the labels before closing issues, will you lose them?

**Comment by k82cn** [comment]
@thockin , I had closed or moved them this morning :).

**Comment by k82cn** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
