### PR TITLE
e2e metrics grabber failing test

### PR DESCRIPTION
**Pull request by aojea**
/kind failing-test
/kind flake
```release-note
NONE
```

Some tests started to fail recently with current error:

>         s: "error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)",

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=waiting%20for%20controller%20manager%20pod%20to%20expose%20metrics

It seems it started since this PR #96216

That added an nginx pod to serve the controller-manager and scheduler secure ports
https://github.com/kubernetes/kubernetes/pull/96216/commits/c4c25747789d7a394ae31501f7c0b5beb92e711d

The failing test doesn't have the nginx pod running, serving the endpoints, hence the test fails to grab the metrics.

However, I don't think that we should install "infrastructure" elements in the e2e framework, so it is better to revert the nginx frontend and modify the test to work as before, just using the new ports.

### CODE REVIEW

**Comment by aojea** [comment]
/test
I want to find a job that run one of the failing tests
```
Kubernetes e2e suite.[sig-storage] [Serial] Volume metrics PVController.*
```

**Comment by aojea** [comment]
/hold
ok, this "unexpected" is "expected"
```
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Client sent an HTTP request to an HTTPS server.",
                        Field: "",
                    },
```

**Comment by liggitt** [comment]
if the test changes in https://github.com/kubernetes/kubernetes/pull/96216 introduced flakes/failures (which they did), reverting that seems reasonable to me

**Comment by aojea** [comment]
> if the test changes in #96216 introduced flakes/failures (which they did), reverting that seems reasonable to me

is not only that, it installs a pod at the beginning of the e2e test to act as a proxy for this ports
I think that we should not add those workarounds , the e2e framework should test the cluster as is

**Comment by liggitt** [comment]
> I think that we should not add those workarounds , the e2e framework should test the cluster as is

There is no topology neutral way to get metrics from controller-manager or scheduler without making changes to the cluster.

Either:
1. grant anonymous access to /metrics and use the API server proxy endpoint
2. add a forwarder that can make use of credentials and authenticate the request

**Comment by BenTheElder** [comment]
Why can't the grabber just use authenticated credentials directly?

We should be avoiding dependency on cluster configuration and installing something that allows unauthed access seems problematic.

**Comment by aojea** [comment]
> Why can't the grabber just use authenticated credentials directly?

is using the f.Clientset, is not that authenticated?

**Comment by liggitt** [comment]
> > Why can't the grabber just use authenticated credentials directly?
> 
> is using the f.Clientset, is not that authenticated?

credentials don't survive the API server proxy and get send to the backend pod

**Comment by knight42** [comment]
I am investigating the root cause https://github.com/kubernetes/kubernetes/pull/101960

**Comment by aojea** [comment]
> I am investigating the root cause #101960

thanks, I'll try to see if we can avoid the nginx pod, one dependency less :)

**Comment by knight42** [comment]
I have spotted 1 instance for now.

According to the logs:
```
I0513 12:14:41.521] I0513 12:14:37.277313   84013 metrics_proxy.go:150] [DEBUG] metrics-proxy nginx config: 
I0513 12:14:41.521] server {
I0513 12:14:41.521] 	listen 10257;
I0513 12:14:41.521] 	server_name _;
I0513 12:14:41.522] 	proxy_set_header Authorization "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InZDZEkxeTZLbjNKUGswNk5QeWdwa3ROT0p3M244NnFfRjBza3lpQWdxVncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRyaWNzLXByb3h5LXRva2VuLWd0cDZoIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im1ldHJpY3MtcHJveHkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyZmE0NDA5Yy0zMGE2LTRlMWQtODJiMS1jMzhlMTFiZjM2MjUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06bWV0cmljcy1wcm94eSJ9.D28Lvn8lmqHH21r_vfWJMFSp0uRXDxhX0m-6mNA7RdX-2S202kL1GqU7RUIV7F3uqPJB_8de6yzLqDu3kaHmpNB1FN68LQcgTCsV5A-V8axwXWCwlaCzb-40ig0UvasyaxOx4wg2TMWK3HxnViSEDD3B2t0KOefbHugeexImbYdsmUJkp_6Nctj2DSK3EH67NwmONYR61Xphnyh9a_CCP3rI6qvmgGD3pbtCaGuiupoBcHW1QniwkM4SlvOoov_g5Sx8l8vLWfaFbLhjC71tRGmH2DEyoXjjvJxe8j4An7bHk5ByGyZAJ3w1kQJlRUU7N9rHUM3kag_Z8tfS4QBEjw";
I0513 12:14:41.522] 	proxy_ssl_verify off;
I0513 12:14:41.522] 	location /metrics {
I0513 12:14:41.523] 		proxy_pass https://10.40.0.2:10257;
I0513 12:14:41.523] 	}
I0513 12:14:41.523] }
I0513 12:14:41.523] 
I0513 12:14:41.523] I0513 12:14:41.473977   84013 metrics_proxy.go:198] Successfully setup metrics-proxy
...

I0513 12:19:27.432] [It] should grab all metrics from a Scheduler.
...

I0513 12:19:27.433] 
I0513 12:19:27.433] May 13 12:19:19.525: FAIL: Unexpected error:
I0513 12:19:27.433]     <*errors.StatusError | 0xc001a726e0>: {
I0513 12:19:27.434]         ErrStatus: {
I0513 12:19:27.434]             TypeMeta: {Kind: "", APIVersion: ""},
I0513 12:19:27.434]             ListMeta: {
I0513 12:19:27.434]                 SelfLink: "",
I0513 12:19:27.434]                 ResourceVersion: "",
I0513 12:19:27.434]                 Continue: "",
I0513 12:19:27.434]                 RemainingItemCount: nil,
I0513 12:19:27.434]             },
I0513 12:19:27.434]             Status: "Failure",
I0513 12:19:27.435]             Message: "the server is currently unable to handle the request (get pods metrics-proxy:10259)",
I0513 12:19:27.435]             Reason: "ServiceUnavailable",
I0513 12:19:27.435]             Details: {
I0513 12:19:27.435]                 Name: "metrics-proxy:10259",
I0513 12:19:27.435]                 Group: "",
I0513 12:19:27.435]                 Kind: "pods",
I0513 12:19:27.435]                 UID: "",
I0513 12:19:27.435]                 Causes: [
I0513 12:19:27.436]                     {
I0513 12:19:27.436]                         Type: "UnexpectedServerResponse",
I0513 12:19:27.436]                         Message: "unknown",
I0513 12:19:27.436]                         Field: "",
I0513 12:19:27.436]                     },
I0513 12:19:27.436]                 ],
I0513 12:19:27.436]                 RetryAfterSeconds: 0,
I0513 12:19:27.436]             },
I0513 12:19:27.436]             Code: 503,
I0513 12:19:27.437]         },
I0513 12:19:27.437]     }
I0513 12:19:27.437]     the server is currently unable to handle the request (get pods metrics-proxy:10259)
```

It seems that the [scheduler pod had not show up](https://github.com/kubernetes/kubernetes/blob/09268c16853b233ebaedcd6a877eac23690b5190/test/e2e/framework/metrics/metrics_proxy.go#L43-L50) when we [setup e2e test suite](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L312), so the nginx config is incomplete.

**Comment by aojea** [comment]
superseded by https://github.com/kubernetes/kubernetes/pull/101960

**Comment by jingxu97** [comment]
currently in-tree storage tests for Windows are failing. Seems related to this? https://testgrid.kubernetes.io/google-windows#gce-windows-2019-containerd-master


The error is 
```
metrics_grabber.go:103] Did not receive an external client interface. Grabbing metrics from ClusterAutoscaler is disabled.
May 13 17:56:18.470: FAIL: Error getting c-m metrics : error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods metrics-proxy:10257)
```

**Pull request closed without merging**
