### PR TITLE
Update verflag.go to work with pflag so that --version keeps working.

### PR DESCRIPTION
**Pull request by filbranden**
This is a limitation of pflag that could be addressed by ogier/pflag#11, so once that is implemented we can look into reverting this one.

For now, this seems to be as good as we can do it, so let's proceed with it to make at least the expected --version calls work as one would expect.

@jbeda

### CODE REVIEW

**Comment by jbeda** [comment]
Do we want to try and add a fix to spf13/pflag instead?  It should be a pretty small change there.

**Comment by filbranden** [comment]
I'm working on the patch for ogier/pflag now... Fix is actually ready, I'm writing a unit test for it and I'll make sure it works with our testcase. I guess let's hold this one for now, see if we can push one upstream shortly...

**Comment by jbeda** [comment]
@spf13 has suggested he is happy to take fixes.

**Comment by filbranden** [comment]
Ok I just sent spf13/pflag#3 which should fix it... If it gets included we can refresh our Gopath version and then go back to having `--version` and `--version=raw` working and drop this PR then.

Cheers,
Filipe

**Comment by jbeda** [comment]
Very cool -- let's give it a day or two and see if it comes together.

**Comment by filbranden** [comment]
We haven't really heard from @spf13...

@jbeda Do you have a suggestion on how to proceed? We can always merge this one and revert it later once this gets upstream...

Alternatively, we could fork spf13/pflag and spf13/cobra on some repository where we can push our changes and switch k8s to use our fork?

**Comment by jbeda** [comment]
Yeah -- let's merge this one and see if we hear from @spf13.  If we have to fork, we'd have to fork commander too, probably.  Ug

**Comment by jbeda** [comment]
The only thing that worries me is that there may be others that are expecting `--version=raw` to work.  Is it better to introduce 2 bool flags or just give up on the 'act as bool' stuff for now?

**Comment by filbranden** [comment]
Do you have an out-of-band contact of @spf13 that we can use to try to nudge him into reviewing that PR?

Regarding your argument of someone expecting `--version=raw` the same could be applied to someone expecting `-version` or `-version=raw` to keep working so in a way that boat has already sailed :-)

I also don't know if there's a way to keep both `--version` and `--version=raw` working with the unpatched spf13/pflag, that's why I (for now) split it into a `--raw_version` flag in order to keep the feature available until we get the upstream support we want...

Looks like Travis is not happy with this one, I might need to rebase...

**Comment by filbranden** [comment]
We can abandon this one once #3740 is merged.

Thanks Joe for helping prioritize it with Steve!

**Comment by jbeda** [comment]
woohoo!  The system works.

**Pull request closed without merging**
