### PR TITLE
Implementing a proper master/worker split in the juju cluster code.

### PR DESCRIPTION
**Pull request by mbruzek**
```
release-note-none
```

General updates to the cluster/juju Kubernetes provider, to bring it up to date.

Updating the skydns templates to version 11
Updating the etcd container definition to include arch.
Updating the master template to include arch and version for hyperkube container.
Adding dns_domain configuration options.
Adding storage layer options.

[Analytics]()

### CODE REVIEW

**Comment by mbruzek** [comment]
It is not clear to me why release-note-label-needed was flagged here. I have read the pull-request instructions and put `release-note-none` in the original comment from the start. Please let me know why the k8s-merge-robot is indicating the label is needed.

**Comment by mbruzek** [comment]
@zmerlynn: Is there anything that can be done to get a review? Or an "OK to test"?

**Comment by zmerlynn** [comment]
@mbruzek: Apologies, I was out a while for the long weekend and wasn't paying much attention to PRs. Looking.

**Comment by zmerlynn** [comment]
Adding `e2e-not-required` - our normal e2es won't touch this.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by mbruzek** [comment]
@zmerlynn It appears that the last check for submit queue is not running. I know kubernetes is nearing a release (and we would really like to be in there for that release). What are the rules for submit queue? I am pretty sure this work does not impact or fail the tests. Can you advise?

**Comment by dims** [comment]
@mbruzek : the milestone 1.3 is missing, from what i am told the submit queue is only processing those marked 1.3 at the moment

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by mbruzek** [comment]
@zims and @zmerlynn this PR has been in the queue for a very long time. I am not clear if it requires any action from my side. Can someone please review this work and let me know what needs to be done to get the 1.3 milestone marker?

**Comment by zmerlynn** [comment]
@mbruzek: I'm not sure this is something we'd c-p for 1.3 at this point. I didn't see that it wasn't added to the milestone. I'll get it merged and proposed (since it's not in the mainline providers, it has low impact on testing), but just warning that we may defer it.

**Comment by zmerlynn** [comment]
@mbruzek: Also, you're failing here:
```
Verifying ./hack/../hack/verify-flags-underscore.py
Found illegal 'flag' usage. If these are false positives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
cluster/juju/layers/kubernetes/reactive/k8s.py:    check_call(split(cmd.format(kubeconfig, cluster_name, server, ca)))
cluster/juju/layers/kubernetes/reactive/k8s.py:    check_call(split(cmd.format(kubeconfig, context, cluster_name, user)))
cluster/juju/layers/kubernetes/reactive/k8s.py:    client_key = '/srv/kubernetes/client.key'
cluster/juju/layers/kubernetes/reactive/k8s.py:    tlslib.client_key(None, client_key, user='ubuntu', group='ubuntu')
cluster/juju/layers/kubernetes/templates/skydns-rc.yml:        - --kube_master_url=http://{{ private_address }}:8080
FAILED   ./hack/../hack/verify-flags-underscore.py	65s
Build step 'Execute shell' marked build as failure
[xUnit] [INFO] - Starting to record.
```

**Comment by goltermann** [comment]
@mbruzek we'll need this test investigated and in the queue soon (today-ish) if this is still needed for the v1.3 release.  Please take a look.

**Comment by goltermann** [comment]
Removing from v1.3 milestone, as we're aiming to release tomorrow.

**Comment by mbruzek** [comment]
@goltermann and @zmerlynn I have fixed the underscore issue. Can this change be re-reviewed? 

I was hung up at the pre-commit hook which attempted to build and did not complete in over 25 minutes on my machine. Are there logs or anything we can collect to troubleshoot this problem?

**Comment by goltermann** [comment]
Readding LGTM, since only change since last LGTM was fixing flag underscores.

**Pull request merged**
