### PR TITLE
Replace boot2docker references with docker-machine

### PR DESCRIPTION
**Pull request by cmluciano**
Trying once again to correct #19016

### CODE REVIEW

**Comment by cmluciano** [comment]
Ok @karlkfi This should be good to go after the tests pass

**Comment by karlkfi** [comment]
@k8s-bot ok to test

**Comment by karlkfi** [comment]
I'm assuming the e2e failure was a flake. Since this is a documentation-only change, the e2e tests are not required.

**Comment by karlkfi** [comment]
For posterity (documenting the flakey test):

```
Summarizing 1 Failure:

[Fail] Deployment [It] deployment should scale up and down in the right order 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:284

Ran 119 of 212 Specs in 441.797 seconds
FAIL! -- 118 Passed | 1 Failed | 2 Pending | 91 Skipped 
```

**Pull request merged**
