### PR TITLE
kubectl: remove redundant test

### PR DESCRIPTION
**Pull request by seans3**
* Removes cmd_printing_test.go
* This file has two tests which both test the "IllegalPackageSourceChecker".
* The "IllegalPackageSourceChecker" is located in another repo (cli-runtime), and it is unit tested there: https://github.com/kubernetes/cli-runtime/blob/master/pkg/genericclioptions/printers/sourcechecker_test.go
* Testing this in `kubectl` requires an internal type, which is not allowed.

helps fix:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

/sig cli
/kind cleanup
/area kubectl
/assign

### CODE REVIEW

**Comment by apelisse** [comment]
LGTM, you have to update bazel BUILD file

**Comment by juanvallejo** [comment]
@seans3 I think we should move these two test cases to https://github.com/kubernetes/cli-runtime/blob/master/pkg/genericclioptions/printers/sourcechecker_test.go. We can also just delete the customcolumn printer pieces from this file

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
