### PR TITLE
fix bad url

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

fix bad url in the readme file

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks!

ping @csbell for approval.

**Comment by wackxu** [comment]
@csbell Please take a look at this PR, it needs your approve, thanks.

**Comment by wackxu** [comment]
cc @csbell @shashidharatd @quinton-hoole Please take a look at this PR, it needs your approve, thanks.

**Comment by wackxu** [comment]
@nikhiljindal @mwielgus @marun @irfanurrehman Please take a look at this PR, it needs your approve, thanks.

**Pull request merged**
