### PR TITLE
kubeadm: remove usage of the "certificates" API for cert renewal

### LINKED ISSUE #2047: deprecate and remove '--use-api' for cert renewal
kubeadm has a flag under the `kubeadm alpha certs renew` command called `--use-api` that allows users to renew a certificate by sending a CSR and blocking until a privileged user (e.g. admin) approves it, the KCM can then sign the certificate using the root CA:

the CSR API is changing to support and require signer names:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md#signers

the KCM is no longer going to be able to sign arbitrary certificates and external signers will be required. the legacy signers may be removed in certificates.v1.

actions:
- [x] deprecate `--use-api`
assigned: @neolit123 
PR: https://github.com/kubernetes/kubernetes/pull/88827
cycle: 1.18

- [x] remove `--use-api` once certficates/v1 is out?
assigned: @neolit123 
PR: https://github.com/kubernetes/kubernetes/pull/90143
cycle: 1.19? watching [this issue](https://github.com/kubernetes/enhancements/issues/1513).

- [x] remove flag from the docs:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#create-certificate-signing-requests-csr
PR: https://github.com/kubernetes/website/pull/26841
cycle: missed 1.19

----
for more details see the following links and the discussion in this same ticket:
https://github.com/kubernetes/kubernetes/pull/88246#issuecomment-592588131
https://github.com/kubernetes/enhancements/pull/1400/files
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md
https://github.com/kubernetes/kubernetes/pull/86933
https://github.com/kubernetes/kubernetes/pull/86476

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

WIP: waiting on https://github.com/kubernetes/enhancements/issues/1513 to go GA.

The flag "--use-api" for "alpha certs renew" was deprecated in 1.18.
Remove the flag and related logic that executes certificate renewal
using "api/certificates/v1beta1". kubeadm continues to be able
to create CSR files and renew using the local CA on disk.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#2047

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: remove the deprecated "--use-api" flag for "kubeadm alpha certs renew"
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by rosti — APPROVED** [review]
Thanks @neolit123 !
/lgtm

I would leave the hold for @fabriziopandini to TAL at it too.

**Comment by neolit123** [comment]
this PR and the usage in kubeadm partially blocks the pending changes in the certificates API:
https://github.com/kubernetes/kubernetes/pull/91754
so let's proceed with it.

thanks
/hold cancel

**Comment by tibetsam** [comment]
could you please update 1.19 documents? it is still using this removed flag.
https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

Create certificate signing requests (CSR)
You can create the certificate signing requests for the Kubernetes certificates API with kubeadm alpha certs renew --use-api.

If you set up an external signer such as cert-manager, certificate signing requests (CSRs) are automatically approved. Otherwise, you must manually approve certificates with the kubectl certificate command. The following kubeadm command outputs the name of the certificate to approve, then blocks and waits for approval to occur:

sudo kubeadm alpha certs renew apiserver --use-api &

**Comment by neolit123** [comment]
@tibetsam

thanks for catching that.
reopening https://github.com/kubernetes/kubeadm/issues/2047 to track this.
maybe you can also help us by sending a PR for kuberentes/website?

**Comment by tibetsam** [comment]
@neolit123 PR was created. FYI. https://github.com/kubernetes/website/pull/26841

**Pull request merged**
