### PR TITLE
fix mungegithub and the verification build

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by lavalamp** [comment]
Merge first, ask questions later.

**Comment by lavalamp** [comment]
@smarterclayton fyi because this fixes something about your original change.

I'm not sure why the munger on your system didn't include this and also why the testing didn't start detecting it until just now. I think the latter was somehow triggered by the release @david-mcmahon just did.

**Comment by david-mcmahon** [comment]
@lavalamp I'd be surprised if it was the update to the branch that caused the master munger to start failing.

**Comment by lavalamp** [comment]
I think there's a git command that looks for release branches that maybe suddenly started working?

**Comment by david-mcmahon** [comment]
Yes one of the *munge* scripts actually hardcodes looking for upstream/<branch>, but prior to today's push the <branch> already existed so that wouldn't have been 'new'.

**Comment by lavalamp** [comment]
Exactly-- that's why I don't understand why it would have stopped working
just now.

**Pull request merged**
