### PR TITLE
switching rolling update to external clients

### PR DESCRIPTION
**Pull request by deads2k**
Switches rolling update to use external clients.  This is a pretty strange looking command.

@kubernetes/sig-cli-maintainers 
/assign @soltysh 

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
This lgtm, but is blocked by #66965

**Comment by deads2k** [comment]
Interesting.  The test is listed as passing on GCE

**Pull request merged**
