### PR TITLE
fix creating pod from file failure in scheduler-predicates

### LINKED ISSUE #29816: [k8s.io] SchedulerPredicates [Serial] validates that embedding the JSON NodeAffinity setting as a string in the annotation value work {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1822/

Failed: [k8s.io] SchedulerPredicates [Serial] validates that embedding the JSON NodeAffinity setting as a string in the annotation value work {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:711
Expected error:
    <*errors.errorString | 0xc820f1a590>: {
        s: "Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.176.226 --kubeconfig=/workspace/.kube/config create -f apiVersion: v1\nkind: Pod\nmetadata:\n  name: with-labels\n  annotations:\n    scheduler.alpha.kubernetes.io/affinity: >\n      {\n        \"nodeAffinity\": {\n          \"requiredDuringSchedulingIgnoredDuringExecution\": {\n            \"nodeSelectorTerms\": [\n              {\n                \"matchExpressions\": [\n                  {\n                    \"key\": \"kubernetes.io/e2e-az-name\",\n                    \"operator\": \"In\",\n                    \"values\": [\"e2e-az1\", \"e2e-az2\"]\n                  }\n                ]\n              }\n            ]\n          }\n        }\n      }\n    another-annotation-key: another-annotation-value\nspec:\n  containers:\n  - name: with-labels\n    image: gcr.io/google_containers/pause:2.0\n --namespace=e2e-tests-sched-pred-uefsh] []  <nil>  the path \"apiVersion: v1\" does not exist\n [] <nil> 0xc82134f360 exit status 1 <nil> true [0xc8212c00f0 0xc8212c0118 0xc8212c0140] [0xc8212c00f0 0xc8212c0118 0xc8212c0140] [0xc8212c0108 0xc8212c0130] [0xabbaf0 0xabbaf0] 0xc82183e3c0}:\nCommand stdout:\n\nstderr:\nthe path \"apiVersion: v1\" does not exist\n\nerror:\nexit status 1\n",
    }
    Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.176.226 --kubeconfig=/workspace/.kube/config create -f apiVersion: v1
    kind: Pod
    metadata:
      name: with-labels
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "kubernetes.io/e2e-az-name",
                        "operator": "In",
                        "values": ["e2e-az1", "e2e-az2"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        another-annotation-key: another-annotation-value
    spec:
      containers:
      - name: with-labels
        image: gcr.io/google_containers/pause:2.0
     --namespace=e2e-tests-sched-pred-uefsh] []  <nil>  the path "apiVersion: v1" does not exist
     [] <nil> 0xc82134f360 exit status 1 <nil> true [0xc8212c00f0 0xc8212c0118 0xc8212c0140] [0xc8212c00f0 0xc8212c0118 0xc8212c0140] [0xc8212c0108 0xc8212c0130] [0xabbaf0 0xabbaf0] 0xc82183e3c0}:
    Command stdout:
    
    stderr:
    the path "apiVersion: v1" does not exist
    
    error:
    exit status 1
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2005
```

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
fix #29816
ref https://github.com/kubernetes/kubernetes/pull/25584#discussion_r73349738 and https://github.com/kubernetes/kubernetes/pull/25584#discussion_r73349328

### CODE REVIEW

**Comment by gmarek** [comment]
Fixes broken test - P2.

**Comment by kevin-wangzefeng** [comment]
@k8s-bot unit test this please, issue #29992

**Comment by gmarek** [comment]
@k8s-bot unit test this issue: #27462

**Comment by gmarek** [comment]
@k8s-bot test this issue: #30012

**Pull request merged**
