### PR TITLE
Replace limits with requests in scheduler documentation.

### PR DESCRIPTION
**Pull request by HaiyangDING**
Due to https://github.com/kubernetes/kubernetes/pull/11713 and https://github.com/kubernetes/kubernetes/pull/12718

### CODE REVIEW

**Comment by wojtek-t** [comment]
@HaiyangDING - please run: "hack/update-generated-docs.sh" to fix tests.

**Comment by davidopp** [comment]
LGTM

Thanks for doing this. BTW, there are a bunch of other places in the documentation where we need to make the same change. If you have time, it would be great if you could help with that! I've filed an issue #13074 about it.

**Comment by davidopp** [comment]
(Oh and yes, please run the command @wojtekt-t mentioned, so that the tests will pass.)

**Comment by HaiyangDING** [comment]
@wojtek-t Thank you! I will do that.

@davidopp OK, I will check all of them and make corresponding changes.

**Pull request merged**
