### PR TITLE
Fix StatefulSet API doc

### PR DESCRIPTION
**Pull request by tengqm**
**What this PR does / why we need it**:
This PR fixes the API documentation generated for `updateStrategy` of StatefulSet.
The current documentation failed to describe available choices. It only mentioned the default value.
  
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
cc @kow3ns

**Comment by kow3ns** [comment]
@tengqm can you split this into two commits please. The first containing your modifications to types.go and the second containing the auto-generated docs.

**Comment by tengqm** [comment]
@kow3ns PTAL, thanks!

**Comment by errordeveloper** [comment]
Would be good to review this and get it in before it rots. Any takers?

**Comment by dhilipkumars** [comment]
cc @smarterclayton please approve

**Comment by tengqm** [comment]
Three months passed ...

**Pull request closed without merging**
