### PR TITLE
Randomize test nodePort to prevent collision

### LINKED ISSUE #37982: TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation {service}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/719/

Failed: TestServiceRegistryExternalTrafficBetaAnnotationHealthCheckNodePortUserAllocation {service}

```
rest_test.go:1012: Unexpected failure creating service Internal error occurred: Failed to allocate requested HealthCheck nodePort 30200: provided port is already allocated
panic: interface conversion: interface is nil, not *api.Service
/usr/local/go/src/runtime/panic.go:500 +0x1ae
/usr/local/go/src/testing/testing.go:579 +0x474
/usr/local/go/src/runtime/panic.go:458 +0x271
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest_test.go:1014 +0x5da
/usr/local/go/src/testing/testing.go:610 +0xca
/usr/local/go/src/testing/testing.go:646 +0x530
```

### PR DESCRIPTION
**Pull request by MrHohn**
Fix #37982.

/assign @bowei 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pmichali** [comment]
Should rand.Seed() be called to seed the generator?

**Comment by MrHohn** [comment]
@pmichali The apimachinery/pkg/util/rand package already takes care of that, see https://github.com/kubernetes/kubernetes/blob/b00c1b66f4638c606d49e552fcdd62ae4f927fcd/staging/src/k8s.io/apimachinery/pkg/util/rand/rand.go#L30.

**Comment by pmichali** [comment]
@MrHohn Gotcha. It's using an apimachinery wrapper for rand that initializes it. Thanks!

**Comment by bowei** [comment]
barring a more deterministic method to get unique ports

/lgtm

**Comment by MrHohn** [comment]
/assign @wojtek-t
For approval.

**Comment by MrHohn** [comment]
@wojtek-t Thanks!

**Pull request merged**
