### PR TITLE
Fix golint failure not contained in .golint_failures

### PR DESCRIPTION
**Pull request by sshukun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
During fixing golint issues of other packages, one failure occured after `verify_golint.sh` in this file.
This file is not contained in `.golint_failures` and this failure is the only failure in this package.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sshukun** [comment]
/assign @jennybuckley
Could you please take a look at this, thanks.

**Review by kwiesmueller — APPROVED** [review]
@apelisse @jennybuckley  you need to approve to merge.
Also don't know exactly what the golint file is, but is there a reason field manager is not in it?
Wouldn't know a reason for anything to be excluded from linting.

**Comment by apelisse** [comment]
I don't quite understand why it's not?

/lgtm

**Comment by kwiesmueller** [comment]
Added a task to the apply board, so we take a look on why field manager is not in there
https://github.com/orgs/kubernetes/projects/38#card-30852127

**Pull request merged**
