### PR TITLE
add E2eScheduling to SchedulingLatency with label

### PR DESCRIPTION
**Pull request by yiyang5055**
**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

add e2eScheduling metric to  SchedulingLatency Summary metrics with e2e scheduling operation label value

**Which issue(s) this PR fixes**:

#86126 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yiyang5055** [comment]
@resouer @k82cn  please review

**Comment by yiyang5055** [comment]
pinging @bsalamat @k82cn @resouer

**Comment by liu-cong** [comment]
/hold

Suggestion: use `e2e_scheduling_duration_seconds`

Reasons for not using `scheduling_duration_seconds`:
* We are considering deprecating it and switch to Histogram metrics, see #86391
* Adding a `e2eScheduling` label seems weird to me. In my opinion, labels specify "independent" time series. In this case, the label `operation` specifies different operations during a scheduling cycle. I can use the label to analyze latency for a specific operation, or if I don't specify an operation, I am looking at all operations. `e2eScheduling` is NOT an operation, and it includes all other operations.

**Comment by yiyang5055** [comment]
> /hold
> 
> Suggestion: use `e2e_scheduling_duration_seconds`
> 
> Reasons for not using `scheduling_duration_seconds`:
> 
> * We are considering deprecating it and switch to Histogram metrics, see #86391
> * Adding a `e2eScheduling` label seems weird to me. In my opinion, labels specify "independent" time series. In this case, the label `operation` specifies different operations during a scheduling cycle. I can use the label to analyze latency for a specific operation, or if I don't specify an operation, I am looking at all operations. `e2eScheduling` is NOT an operation, and it includes all other operations.

ok, i'm understand
/cc @liu-cong

**Comment by ahg-g** [comment]
/close 

based on https://github.com/kubernetes/kubernetes/pull/86247#issuecomment-567582998

**Pull request closed without merging**
