### PR TITLE
Improve code coverage for pkg/printer

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@fabianofranz can you help review this? think you :)

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by fabianofranz** [comment]
tks @zjj2wry!
/lgtm
/approve

**Comment by fabianofranz** [comment]
No worries @zjj2wry, thanks a lot for helping make Kube better covered by tests!

**Pull request merged**
