### PR TITLE
Revert "Add kubelet awareness to taint tolerant match caculator."

### PR DESCRIPTION
**Pull request by davidopp**
Reverts kubernetes/kubernetes#26501

Original PR was not fully reviewed by @kubernetes/sig-node 

cc/ @timothysc @resouer

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34350)

### CODE REVIEW

**Comment by yujuhong** [comment]
Marking P1 since this is a revert. Delaying it will cause more troubles for other PRs touching the same code.

**Comment by timothysc** [comment]
@yujuhong 
Could we please denote what the issue(s)/question(s) are from the node side?

**Comment by yujuhong** [comment]
> @yujuhong 
> Could we please denote what the issue(s)/question(s) are from the node side?

I have no idea. I didn't actually review the PR. I think @davidopp wanted an opportunity to make a final pass, and have someone from the node side to take a look as well (which would be good). 
/cc @dchen1107 to review or delegate.

**Comment by vishh** [comment]
I intended to review the original PR, but due to v1.4 never got to it.

**Comment by dchen1107** [comment]
@davidopp I can review the revert-revert.

**Pull request merged**
