### PR TITLE
Parse the last partial line in CRI logs

### PR DESCRIPTION
**Pull request by mrunalp**
@Random-Liu @yujuhong @runcom @feiskyer PTAL

Fixes part of https://github.com/kubernetes/kubernetes/issues/44976

This should work while we find a longer term format for CRI logs.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

**What this PR does / why we need it**:
This PR attempts to parse the last line of  log even if it doesn't have a newline. Today for CRI based log formats such lines are ignored and empty output is returned.

**Which issue(s) this PR fixes** 
Fixes part of #44976

**Special notes for your reviewer**:
Use a CRI runtime like CRI-O and the output will be empty for these commands without this PR.
```
# kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/configmap/configmap.yaml
# kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/configmap/pod-configmap-volume1.yaml 
# kubectl logs dapi-test-pod-1 
very# 
```

**Release Note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@mrunalp - this implements what was proposed here in the absence of a better solution?

https://github.com/kubernetes/kubernetes/issues/44976#issuecomment-297830964

what you have now is better than what we have previously, so this works for me for the moment.

**Comment by mrunalp** [comment]
@derekwaynecarr Yes, that's what this PR implements. 
This can be improved later when we modify the log format but is the best we can do for now.

**Comment by derekwaynecarr** [comment]
this is no worse than what we have before, and makes more content visible to users that were previously invisible.  in that vein, this is good to me and doesn't preclude us doing more in future.

/approve
/lgtm

**Comment by Random-Liu** [comment]
LGTM. I prefer adding a helper function instead of copying code, but I'm fine with doing that in another PR.

**Review by feiskyer — COMMENTED** [review]
LGTM. We may also add a test for such case.

**Pull request merged**
