### PR TITLE
Update --image-gc-low-threshold option's description

### PR DESCRIPTION
**Pull request by ytinirt**
kubelet option '--image-gc-low-threshold' description says it 'should not be larger than that of --image-gc-high-threshold'. But actually, it must less than '--image-gc-high-threshold', according to https://github.com/kubernetes/kubernetes/blob/02659772cb2662600fb1273654bdb05921ae246e/pkg/kubelet/apis/config/validation/validation.go#L84

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Avoiding ambiguity of kubelet option's description.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
According to validation code, *ImageGCLowThresholdPercent* must be less than *ImageGCHighThresholdPercent*: 
https://github.com/kubernetes/kubernetes/blob/ac7e5cbf692603d1ed691dcfe245d2d19715150c/pkg/kubelet/apis/config/validation/validation.go#L83-L85

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
Confirmed it matches the validation code.

/lgtm

**Comment by dims** [comment]
/approve

thanks for noticing and fixing

**Pull request merged**
