### PR TITLE
Improve the accuracy of error msg in /pkg/scheduler/internal/queue

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
There is an error message that only prints the pod name, it is recommended to also print the namespace

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
/ok-to-test
/lgtm

Might be useful for debugging.

**Review by damemi — APPROVED** [review]
/approve

**Pull request merged**
