### PR TITLE
Move pkg/kubectl/apps to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/apps` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/apps.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/cc @BenTheElder 

for `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/approve

**Pull request merged**
