### PR TITLE
Clean up deep copy needed for UpdateStatefulSet

### LINKED ISSUE #106615: StatefulSet PVC tests failing
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106568/pull-kubernetes-unit/1462136832413143040

### Which tests are failing?

StatefulSet control tests

### Since when has it been failing?

The delete PVC unit tests started flaking when https://github.com/kubernetes/kubernetes/pull/99728 was merged

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106568/pull-kubernetes-unit/1462136832413143040

### Reason for failure (if possible)

#99728 exposed a sharp edge in UpdateStatefulSet, where the set was assumed to be unmodified, but actually creating a new revision for it changes it.

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig apps

/assign @mattcary

### PR DESCRIPTION
**Pull request by mattcary**
/kind failing-test
/assign @liggitt 
/sig apps

xref #106615

```release-note
None
```

### CODE REVIEW

**Comment by mattcary** [comment]
I wasn't able to reproduce the race locally, but I'm optimistic this is the problem.

**Comment by liggitt** [comment]
/lgtm
/approve

this fix looks fine, but doesn't resolve all the flakes in the AutoDeletePVC unit test (I got a flake in the first ~25 runs running on this branch using [stress](https://pkg.go.dev/golang.org/x/tools/cmd/stress)):

```
go test -race -c ./pkg/controller/statefulset/
stress ./statefulset.test 
...
--- FAIL: TestStatefulSetControl (15.48s)
    --- FAIL: TestStatefulSetControl/CreatesPods/Monotonic/Retain/StatefulSetAutoDeletePVCEnabled (0.01s)
        stateful_set_control_test.go:196: Failed to turn up StatefulSet : claim for Pod foo-0 was not created
        stateful_set_control_test.go:204: Failed to scale statefulset to 3 replicas
        stateful_set_control_test.go:207: Failed to set ReadyReplicas correctly
        stateful_set_control_test.go:210: Failed to set UpdatedReplicas correctly
```

**Comment by liggitt** [comment]
tagging into milestone to fix CI regression

**Comment by mattcary** [comment]
> /lgtm /approve
> 
> this fix looks fine, but doesn't resolve all the flakes in the AutoDeletePVC unit test (I got a flake in the first ~25 runs running on this branch using [stress](https://pkg.go.dev/golang.org/x/tools/cmd/stress)):
> 
> ```
> go test -race -c ./pkg/controller/statefulset/
> stress ./statefulset.test 
> ...
> --- FAIL: TestStatefulSetControl (15.48s)
>     --- FAIL: TestStatefulSetControl/CreatesPods/Monotonic/Retain/StatefulSetAutoDeletePVCEnabled (0.01s)
>         stateful_set_control_test.go:196: Failed to turn up StatefulSet : claim for Pod foo-0 was not created
>         stateful_set_control_test.go:204: Failed to scale statefulset to 3 replicas
>         stateful_set_control_test.go:207: Failed to set ReadyReplicas correctly
>         stateful_set_control_test.go:210: Failed to set UpdatedReplicas correctly
> ```

Cool, I didn't know about stress!

These look like different flakes--not a mutation detector race---so probably better to fix in another PR anyway.

**Pull request merged**
