### PR TITLE
fix grammar

### PR DESCRIPTION
**Pull request by mahendrabishnoi2**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fixes a grammar error.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
cc @cheftako

**Comment by dims** [comment]
/approve

NOTE: single word comment fixup

**Pull request merged**
