### PR TITLE
Rename experimental-runtime-integration-type to experimental-cri

### PR DESCRIPTION
**Pull request by yujuhong**
Also rename the field in the component config to `EnableCRI`

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36319)

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot cri node e2e test this

**Comment by feiskyer** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot cri node e2e test this

**Comment by yujuhong** [comment]
@k8s-bot cri node e2e test this

**Comment by timstclair** [comment]
`s/runtime-integration-type/enable-cri/` in `test/e2e_node/jenkins/cri_validation` too.

**Comment by timstclair** [comment]
You beat me too it :)  LGTM

**Comment by timstclair** [comment]
There seems to be a github bug right now where it shows all lables applied from the author. The LGTM came from me though...

**Comment by yujuhong** [comment]
Don't think the unit test failure was caused by the change in this PR: `I1107 10:19:30.176] FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/namespace	3.136s`

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
Rebased

**Comment by yujuhong** [comment]
@k8s-bot cri node e2e test this

**Comment by yujuhong** [comment]
Bumping to p2 to better coordinate with the test-infra side change.

**Pull request merged**
