### PR TITLE
Code cleanups in kubelet_test.go

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Its a goal of mine to make kubelet_test.go not a 5000 line file in a follow-on PR by splitting things out, but this cuts some of the unnecessary fat in a couple tests where we had redundant stuff.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24722)

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@pmorie - if we can keep a similar code addition to deletion ratio, one day this file may not take so longer to page down!

**Comment by pmorie** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM. Thanks for the cleanup!

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue #https://github.com/kubernetes/kubernetes/issues/24538

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/24991

**Comment by yujuhong** [comment]
@derekwaynecarr kubelet failed to compile, probably due to recent changes. Could you take a look? Thanks!

```
# k8s.io/kubernetes/pkg/kubelet
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go:1282: cannot use port (type int) as type int32 in field value
```

**Comment by derekwaynecarr** [comment]
fixed the cast problem for port to use int32 now.

**Comment by saad-ali** [comment]
Manually merging low small low risk PRs to drain submit queue

**Pull request merged**
