### PR TITLE
Update to golang@1.13.8

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Update to golang@1.13.8.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Before merge:
- [x] build/push cross-build image for 1.13.8 (`k8s.gcr.io/kube-cross:v1.13.8-1`)

**Does this PR introduce a user-facing change?**:

```release-note
Update to use golang 1.13.8
```

### CODE REVIEW

**Comment by listx** [comment]
QQ: who/what determines that we need to move to golang 1.13.7? (or, what does this PR fix?)

Is there a history of bumping these versions as a sort of routine change whenever golang releases a new version?

**Comment by cblecker** [comment]
/ok-to-test

@listx: We try to track master with the latest golang, as to keep aligned with security fixes. Right now it's the `build/` owners who make the calls, but we're hoping to doc these polices more clearly and transition this over to to the Release Engineering subproject of sig-release (@justaugustus and crew).

**Comment by ialidzhikov** [comment]
@cblecker , I adapted to golang@1.13.8.

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

/assign @BenTheElder @javier-b-perez 
Assigning for image build

**Comment by listx** [comment]
> /ok-to-test
> 
> @listx: We try to track master with the latest golang, as to keep aligned with security fixes. Right now it's the `build/` owners who make the calls, but we're hoping to doc these polices more clearly and transition this over to to the Release Engineering subproject of sig-release (@justaugustus and crew).

SG

Looks like the pull-kubernetes-verify test is failing because we haven't yet built a kube-cross image yet (that uses the golang version in this PR). @BenTheElder / @javier-b-perez what's the usual procedure for building the cross images? Should we merge this PR in first, or build the kube-cross image beforehand?

**Comment by dims** [comment]
@listx someone pulls this PR, builds the kube-cross with new version, uploads the new image, then `/retest` this PR to merge it.

**Comment by justaugustus** [comment]
qq (non-blocking): Is there anything stopping us from building kube-cross in K8s Infra today?

**Comment by BenTheElder** [comment]
I clone the PR, rebase, and then push it *before* merge.
currently this is how the flow goes, but you could imagine a two step PR
process with auto pushed images.

I'd like to make PRs not so slow before recommending that myself...

**Comment by BenTheElder** [comment]
I can help with pushing this image but probably not today unless it's
urgent.

**Comment by cblecker** [comment]
Not urgent. Thanks Ben!

**Comment by cblecker** [comment]
Not urgent. Thanks Ben!

**Comment by justaugustus** [comment]
Hi @ialidzhikov! Now that https://github.com/kubernetes/kubernetes/pull/88562 has merged, can you rebase this PR?

I've pushed a new kube-cross:v1.13.8-1 image in https://github.com/kubernetes/k8s.io/pull/610, so once you rebase, all of the tests should pass.

**Pull request merged**
