### PR TITLE
NPD: Update NPD test.

### PR DESCRIPTION
**Pull request by Random-Liu**
For https://github.com/kubernetes/node-problem-detector/issues/58.

Update NPD e2e test based on the new behavior.

Note that before merging this PR, we need to merge all pending PRs in npd, and release the v0.3.0-alpha.1 version of NPD.

/cc @dchen1107 @kubernetes/node-problem-detector-reviewers

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
/lgtm

and 

/approve

**Comment by dchen1107** [comment]
The latest version of NPD image is still in @Random-Liu's personal repository, not in gcr.io yet. I removed /approve. Will re-approve once the image is pushed to the official repository.

**Comment by Random-Liu** [comment]
Remove the lgtm, will re-apply after new image is pushed.

**Comment by Random-Liu** [comment]
@k8s-bot test this.

**Comment by dchen1107** [comment]
LGTM

**Comment by Random-Liu** [comment]
@k8s-bot node e2e test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
