### PR TITLE
Change the default CLUSTER_IP_RANGE used by e2e

### PR DESCRIPTION
**Pull request by bowei**
The existing choice intersects with the range reserved for auto
subnets and cannot be used with some GCP features.

Addressing https://github.com/kubernetes/kubernetes/issues/47379 

Cherrypick of 0e6af317a8567271231487b2e3463236b5c9b6dd from 1.7.

```release-note
none
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
Should we also fix config-default.sh (the settings used for real clusters rather than test clusters)? And why doesn't this have a release note? We should definitely point this change out on the next patch release on each release branch.

**Comment by dchen1107** [comment]
I am manually merging this, so that we can kick out the new round of upgrade tests.

**Comment by enisoc** [comment]
@roberthbailey I discussed your concerns with @dchen1107 and my understanding is as follows:

1. The setting in [config-default.sh](https://github.com/kubernetes/kubernetes/blob/release-1.6/cluster/gce/config-default.sh#L80) was already different from the one used in tests. It was only the specific value used in tests that caused problems, so non-test clusters should not be affected.

2. In general, for test-only changes, I do not require a release note.

**Comment by roberthbailey** [comment]
> so non-test clusters should not be affected

Do we actually know that this is true? Since our test infrastructure does not mimic the configs for non-test clusters, I don't think we have any signal whether or not non-test clusters are affected.

**Comment by enisoc** [comment]
@bowei Can you comment on these concerns?

**Comment by bowei** [comment]
@roberthbailey as far as I can tell, what @enisoc said above is correct -- the test IP range was already different, and the change only touches the test configuration.

**Comment by roberthbailey** [comment]
I didn't realize that the test range had diverged from the non-test range. FWIW, that is why I filed https://github.com/kubernetes/kubernetes/issues/21052 18 months ago -- we have a lack of test coverage on the non-test deployment options, to the point where it almost makes more sense to launch all clusters with config-test.sh rather than config-default.sh because we have no real idea if the later's configuration settings even work.

**Pull request merged**
