### PR TITLE
Refactor persistent volume tests

### PR DESCRIPTION
**Pull request by tsmetana**
This is an attempt to make the binder tests a bit more concise. The PVCs are being created by a "templating" function. There is also a handful of PVs in the tests but those vary quite more and I don't think similar approach would save us much code.

Reference:
https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29006#-KPJuVeDE0O6TvDP9jia

@jsafrane: I hope this is what you have on mind.

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot kubemark e2e test this

**Comment by jsafrane** [comment]
@k8s-bot kops aws e2e test this

**Comment by thockin** [comment]
NB you have to LGTM *and* approve.

**Pull request merged**
