### PR TITLE
Automated cherry pick of #67971: Add ability to build with runtime coverage instrumentation

### PR DESCRIPTION
**Pull request by Katharine**
Cherry pick of #67971 on release-1.11.

#67971: Add ability to build with runtime coverage instrumentation

### CODE REVIEW

**Comment by BenTheElder** [comment]
typecheck failure is CI fault, kops is flakes I think

**Comment by nikhita** [comment]
/assign @thockin 
for approval

/assign @foxish 
for cherry-pick approval

**Pull request merged**
