### PR TITLE
[kubelet] Allow opting out of automatic cloud provider detection in kubelet. By default kubelet will auto-detect cloud providers

### LINKED ISSUE #28231: In 1.3, kubelet cloud-provider setting is not respected when --cloud-provider=""
It appears that the kubelet will detect and use the cloud provider as detected by cadvisor thus overriding the cloud provider passed in at runtime: https://github.com/kubernetes/kubernetes/blob/release-1.3/pkg/kubelet/kubelet.go#L1117. This will break our private cloud configuration where we do not use our cloud provider's load balancing and instead use our own load balancing tier. In my opinion, the cloud provider specified at kubelet runtime should be respected for the node.

Am I reading this correctly?
Any thoughts on how to handle this properly?

Thank you!

### PR DESCRIPTION
**Pull request by vishh**
fixes #28231

### CODE REVIEW

**Comment by vishh** [comment]
@dchen1107 Kindly advice if this PR is worth a cherry-pick

**Comment by enoodle** [comment]
Thanks @vishh  :+1:

**Comment by dchen1107** [comment]
This is a behavior regression from 1.2 release, and do break the private cloud user's the cloud configuration without any workaround. We should cherry-pick the fix. Thanks!

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @erictune

**Comment by erictune** [comment]
@vishh Does this require action by the user when upgrading to 1.3.0?  If so, please edit your first comment to have  a release-note block, like in https://github.com/kubernetes/kubernetes/pull/28132.  If not, please change to release-note-none label.

**Pull request merged**
