### PR TITLE
Nominate hex108 as a scheduler reviewer

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Self-nominate myself as a scheduler reviewer

I am familiar with scheduler code base, and would like to help review scheduler code.

- I have been member since Dec 2018
- Help review these PRs:  https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Ahex108
- My reviewed/merged PRs: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ahex108+

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig scheduling
/assign @k82cn @bsalamat

### CODE REVIEW

**Comment by bsalamat** [comment]
/lgtm

Thanks, @hex108 for your contributions and help with reviewing PRs.

**Comment by hex108** [comment]
Thanks @k82cn @bsalamat !

Kindly ping @thockin @liggitt @wojtek-t for approval.

**Pull request merged**
