### PR TITLE
API server: fix default_konnectivity_socket_path typo.

### PR DESCRIPTION
**Pull request by jkh52**
Make it consistent with configure-helper.sh

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Avoid confusion, become less brittle.

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jkh52** [comment]
i signed cla

**Comment by Jefftree** [comment]
This change is in line with what we pass to the kube-apiserver (https://github.com/kubernetes/kubernetes/blob/c8ebc8ab75a9c36453cf6fa30990fd0a277d856d/cluster/gce/gci/configure-helper.sh#L931).

/lgtm
/assign @cheftako 
/test pull-kubernetes-e2e-gce-network-proxy-grpc
/test pull-kubernetes-e2e-gce-network-proxy-http-connect

**Comment by jkh52** [comment]
I think github has been a bit slow today.

/retest

**Pull request merged**
