### PR TITLE
Add example of using gitRepo

### LINKED ISSUE #13353: the docs need a gitRepo volume example
The docs need a gitRepo volume example.

### PR DESCRIPTION
**Pull request by resouer**
Fix #13353

### CODE REVIEW

**Comment by resouer** [comment]
@brendandburns Could you please review this?

**Comment by brendandburns** [comment]
LGTM.  thanks!

**Comment by resouer** [comment]
Emm ... jenkins not satisfied again ,,, @brendandburns

**Comment by wojtek-t** [comment]
Jenkins failure is unrelated flake:
"Pods should have their container restart back-off timer increase exponentially"

@k8s-bot test this please

**Pull request merged**
