### PR TITLE
Update volumes doc to fix broken link and describe new file.

### LINKED ISSUE #7810: nfs example link broken
This page:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md

Links to this YAML:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/nfs/test.yaml

Which doesn't exist.

There are several examples now in the NFS folder:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/nfs

### PR DESCRIPTION
**Pull request by mbforbes**
Fixes #7810

### CODE REVIEW

**Comment by mbforbes** [comment]
+cc @jsafrane @thoraxe

**Comment by thoraxe** [comment]
TY!

**Comment by mbforbes** [comment]
NP! I'm a bit concerned about keeping the doc up-to-date with the file a few directories over, but we'll see what Eric has to say. Might just move this description to the examples directory entirely. Thanks for reporting this!

**Comment by jsafrane** [comment]
Looks good to me, thanks!

**Comment by erictune** [comment]
@mbforbes 
I'd suggest inlining the example rather than linking it.  This will be more helpful to readers.

If there is a concern is about inlined examples getting stale, then someone could do either of the following things:
  - generate final docs by merging the example and a template doc.  Allows examples to remain in examples dir.
  - generate examples by extracting them from a doc with inlined examples.  examples would be bracketed by something like `# BEGIN API EXAMPLE` and `# END`.  

@nikhiljindal I think has been working on doc automation.  He may have ideas.

**Comment by erictune** [comment]
I merged this since it is an improvement.

**Pull request merged**
