### PR TITLE
update getting-started-guides/coreos to v1

### PR DESCRIPTION
**Pull request by caesarxuchao**
a loose end in #5799

@bgrant0607 @nikhiljindal @krousey

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by bgrant0607** [comment]
Please look more closely.
v1beta1 != v1 schema.

**Comment by caesarxuchao** [comment]
ah...Forgot the metadata block..Sorry.

**Comment by caesarxuchao** [comment]
Fixed. PTAL, thanks.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Needs 2nd LGTM @quinton-hoole

**Comment by bgrant0607** [comment]
Trying @lavalamp for a 2nd LGTM

**Comment by quinton-hoole** [comment]
lgtm, ok-to-merge.  Sorry - I just saw this one.  Feel free to assign to me in future to get my attention.

**Pull request merged**
