### PR TITLE
Don't stop the next poll when it fails to grab logs

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

See https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1852485735551078400

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/cc @dims 

because it was added in https://github.com/kubernetes/kubernetes/pull/118141

**Comment by wendy-ha18** [comment]
The PR is trying to solve this issue https://github.com/kubernetes/kubernetes/issues/128510

**Comment by aojea** [comment]
I'm not in favor of this, the error is lefit

```
    {
        ErrStatus: 
            code: 500
            details:
              causes:
              - message: unknown
                reason: UnexpectedServerResponse
              kind: pods
              name: dns-test-3928ca26-e2c4-4c99-9509-2b0a28959732
            message: an error on the server ("unknown") has prevented the request from succeeding
              (get pods dns-test-3928ca26-e2c4-4c99-9509-2b0a28959732)
            metadata: {}
            reason: InternalError
            status: Failure,
    }
```

the goal of the tests is to identify problems, not just to pass no matter what

Have we analyzed why there is an unknown error, that may be most probably a bug, and if we ignore doing this things we are lowering the bar

@dims @carlory we need to revert this change, apiserver failing to get logs is not expected

**Comment by aojea** [comment]
There are no logs because a bug in kubetest2  https://github.com/kubernetes-sigs/kubetest2/pull/273 , sending PR to fix it

**Pull request merged**
