### PR TITLE
WIP: Only create SSA models for CRDs with structural schema

### LINKED ISSUE #85127: nullable in OpenAPI schema breaks server-side-apply
With `nullable: true` in a CRD we get:
```
E1111 19:21:58.602019       1 customresource_handler.go:655] error building openapi models for clusteroperators.config.openshift.io: ERROR $root.definitions.io.openshift.config.v1.ClusterOperator.properties.status.properties.extension has invalid property: nullable
```

This is because gnostic's OpenAPI proto types have no nullable support.

Luckily CRDs keep working because in the upper error case we don't stop serving, just set the SSA schema to nil.

### LINKED ISSUE #90902: "error building openapi models" error logged serving CRD containing x-kubernetes-int-or-string
extracted from https://github.com/kubernetes/kubernetes/issues/85127#issuecomment-605890538

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: intorstrings.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: intorstrings
    singular: intorstring
    kind: IntOrString
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        intorstr:
          x-kubernetes-int-or-string: true
---
apiVersion: stable.example.com/v1
kind: IntOrString
metadata:
  name: int
intorstr: 1
---
apiVersion: stable.example.com/v1
kind: IntOrString
metadata:
  name: string
intorstr: "string"
```

produces this log line:

```
customresource_handler.go:652] error building openapi models for intorstrings.stable.example.com: ERROR $root.definitions.com.example.stable.v1.IntOrString.properties.intorstr has invalid property: anyOf
```

/sig api-machinery
/assign @apelisse 
/priority important-soon

The message is a no-op, and means server-side apply for that custom resource falls back to "no schema" mode.

### PR DESCRIPTION
**Pull request by apelisse**
And also, the current code only understands V2, so we should use that
exclusively, or we're guaranteed to have errors in the future.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
I'm sure this change is wrong, but I never can remember why.

It does look much better to me because:
1. The parser the we use is built for openapi v2, so it seems surprising that we're trying to shove v3 in it. I'm not surprised it's failing.
2. I thought we wanted to only support structured schemas in server-side apply, wasn't it the goal of our alignement discussions?

So yes, I think the patch is good, but I'm also sure I'm missing something.
It's also temporary since jenny has a PR going-on that will read v3 directly and convert without the "wrong" parser.

/assign @sttts @liggitt 
/cc @kwiesmueller @jennybuckley @lavalamp 

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/90902

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Would this resolve the issue seen in https://github.com/openfaas/faas-netes/issues/630#issuecomment-625444213? Let's make sure we have test coverage for that scenario as well.

**Comment by apelisse** [comment]
Sorry, that's clearly a WIP. Yes, I have this bug in mind, though I'm surprised it's triggering a 500 on their end?

**Comment by liggitt** [comment]
> 2. I thought we wanted to only support structured schemas in server-side apply, wasn't it the goal of our alignment discussions?

I thought so too, but see https://github.com/kubernetes/kubernetes/pull/77354#discussion_r317738195

When the current code encounters an error, it logs but continues enabling SSA in schemaless mode. Would this PR effectively do the same thing, just not log an error?

**Comment by liggitt** [comment]
> Would this PR effectively do the same thing, just not log an error?

It looks like it would get here with `schema` == nil:

https://github.com/kubernetes/kubernetes/blob/058eecbfefc29665f4255243774d3fe2863ca664/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go#L127

Not sure what that does

**Comment by jtslear** [comment]
Hello, @jtslear here from Bug Triage! This PR has not been updated for a long time, so I'd like to check on the status. The code freeze is starting June 25th and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.19, is it still planned for this release?

**Comment by jtslear** [comment]
@kubernetes/sig-api-machinery-pr-reviews 

This PR hasn't seen any activity in the past month.  Is this PR still valid for v1.19?

**Comment by apelisse** [comment]
Almost certainly not.

**Pull request closed without merging**
