### PR TITLE
[flaky test] fix devicemanager TestDevicePluginReRegistrationProbeMode once in while failed on macos

### PR DESCRIPTION
**Pull request by alberthuang24**
#### What type of PR is this?

/kin bug
/kind failing-test

#### What this PR does / why we need it:

- reappear:  
```bash
go test ./pkg/kubelet/cm/devicemanager
```

Fails frequently on my computer.

```
go test ./pkg/kubelet/cm/devicemanager
I0524 18:00:43.307874   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/tmp/mock1621850443306065000.sock"
I0524 18:00:43.308831   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/tmp/mock1621850443308513000.sock"
I0524 18:00:43.309325   74080 device_plugin_stub.go:237] "ListAndWatch"
E0524 18:00:43.309905   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Canceled desc = grpc: the client connection is closing" resourceName="mock"
I0524 18:00:43.310217   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/tmp/mock1621850443309804000.sock"
I0524 18:00:43.310661   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.311073   74080 device_plugin_stub.go:271] "Allocate" request="&AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[ADeviceId],},},}"
E0524 18:00:43.311628   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="mock"
I0524 18:00:43.311871   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/tmp/mock1621850443311652000.sock"
I0524 18:00:43.312089   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.312298   74080 device_plugin_stub.go:258] "GetPreferredAllocation" request="&PreferredAllocationRequest{ContainerRequests:[]*ContainerPreferredAllocationRequest{&ContainerPreferredAllocationRequest{AvailableDeviceIDs:[],MustIncludeDeviceIDs:[],AllocationSize:-1,},},}"
E0524 18:00:43.312484   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="mock"
I0524 18:00:43.312622   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.312775   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.312827   74080 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
I0524 18:00:43.313213   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin774535850/device-plugin.sock"
I0524 18:00:43.313552   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.313606   74080 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
I0524 18:00:43.313923   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265/device-plugin.sock"
E0524 18:00:43.314208   74080 plugin_watcher.go:68] "Failed to traverse plugin socket path" err="failed to watch /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265, err: lstat /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265/server.sock: no such file or directory" path="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265"
I0524 18:00:43.314220   74080 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
E0524 18:00:43.314316   74080 plugin_watcher.go:79] "Error when handling create event" err="stat file /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265/server.sock failed: stat /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265/server.sock: no such file or directory" event="\"/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin081483265/server.sock\": CREATE"
I0524 18:00:43.314551   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.314623   74080 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
I0524 18:00:43.315452   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock"
I0524 18:00:43.315523   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.315916   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.316305   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.339578   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.new"
I0524 18:00:43.339615   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.340270   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.341259   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.364006   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.third"
I0524 18:00:43.364034   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.364557   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.365058   74080 device_plugin_stub.go:237] "ListAndWatch"
E0524 18:00:43.387664   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.387812   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.388001   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
I0524 18:00:43.388034   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.389030   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock"
I0524 18:00:43.389054   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.389596   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.390573   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.411304   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.new"
I0524 18:00:43.411343   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.411993   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.412504   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.434582   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.third"
I0524 18:00:43.434627   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.435089   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.436171   74080 device_plugin_stub.go:237] "ListAndWatch"
E0524 18:00:43.458505   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.458744   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.458934   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
I0524 18:00:43.459142   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.460035   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock"
I0524 18:00:43.460059   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.460531   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.461019   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.483170   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.new"
I0524 18:00:43.483194   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.483657   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.484139   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.509534   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.third"
I0524 18:00:43.509571   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.510628   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.511121   74080 device_plugin_stub.go:237] "ListAndWatch"
E0524 18:00:43.531659   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.531854   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.532086   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
I0524 18:00:43.532219   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.532804   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock"
I0524 18:00:43.532817   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.533082   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.533452   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.555089   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.new"
I0524 18:00:43.555129   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.555928   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.557433   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.579644   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin547371884/device-plugin.sock.third"
I0524 18:00:43.579671   74080 device_plugin_stub.go:190] "Deprecation file not found. Invoke registration"
I0524 18:00:43.580123   74080 manager.go:414] "Got registration request from device plugin with resource" resourceName="fake-domain/resource"
I0524 18:00:43.580603   74080 device_plugin_stub.go:237] "ListAndWatch"
E0524 18:00:43.602491   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.602805   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
E0524 18:00:43.603013   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unavailable desc = transport is closing" resourceName="fake-domain/resource"
I0524 18:00:43.603844   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:43.603937   74080 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
I0524 18:00:43.604594   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock"
I0524 18:00:43.605190   74080 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
I0524 18:00:43.605643   74080 device_plugin_stub.go:163] "GetInfo"
E0524 18:00:43.605689   74080 goroutinemap.go:150] Operation for "/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/server.sock" failed. No retries permitted until 2021-05-24 18:00:44.105652 +0800 CST m=+0.810286634 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0524 18:00:43.606972   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:43.632335   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock.new"
E0524 18:00:44.610072   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Canceled desc = grpc: the client connection is closing" resourceName="fake-domain/resource"
I0524 18:00:44.610588   74080 device_plugin_stub.go:163] "GetInfo"
E0524 18:00:44.610835   74080 goroutinemap.go:150] Operation for "/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/server.sock" failed. No retries permitted until 2021-05-24 18:00:45.610792 +0800 CST m=+2.315418336 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0524 18:00:44.611564   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:44.633551   74080 device_plugin_stub.go:142] "Starting to serve on socket" socket="/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock.third"
E0524 18:00:45.610827   74080 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Canceled desc = grpc: the client connection is closing" resourceName="fake-domain/resource"
I0524 18:00:45.611220   74080 device_plugin_stub.go:163] "GetInfo"
I0524 18:00:45.611227   74080 device_plugin_stub.go:163] "GetInfo"
I0524 18:00:45.611944   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:45.612096   74080 device_plugin_stub.go:237] "ListAndWatch"
I0524 18:00:45.653855   74080 manager.go:585] "Failed to write checkpoint file" err="rename /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/.836521195 /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/kubelet_internal_checkpoint: no such file or directory"
E0524 18:00:45.653893   74080 manager.go:192] "Writing checkpoint encountered" err="failed to write checkpoint file \"kubelet_internal_checkpoint\": rename /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/.836521195 /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/kubelet_internal_checkpoint: no such file or directory"
--- FAIL: TestDevicePluginReRegistrationProbeMode (2.05s)
    manager_test.go:223:
        	Error Trace:	manager_test.go:223
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
E0524 18:00:45.654104   74080 plugin_watcher.go:79] "Error when handling create event" err="stat file /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock.third failed: stat /var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock.third: no such file or directory" event="\"/var/folders/gm/l1qgxw0520v1kt5488cxtz5c0000gn/T/device_plugin198264007/device-plugin.sock.third\": CREATE"
I0524 18:00:45.654348   74080 fake_topology_manager.go:29] "NewFakeManager"
E0524 18:00:45.763860   74080 manager.go:550] "Unexpected: unhealthyDevices and endpoints are out of sync"
I0524 18:00:45.829064   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:45.829246   74080 fake_topology_manager.go:34] "GetAffinity" podUID="0cef8707-f966-4a7f-803a-5cb8d3aae412" containerName=""
I0524 18:00:45.829284   74080 fake_topology_manager.go:34] "GetAffinity" podUID="0cef8707-f966-4a7f-803a-5cb8d3aae412" containerName=""
I0524 18:00:45.849307   74080 fake_topology_manager.go:34] "GetAffinity" podUID="2efb7623-05c9-4e57-8904-8cc7e63e3684" containerName=""
I0524 18:00:45.870669   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:45.870724   74080 fake_topology_manager.go:34] "GetAffinity" podUID="d650b2a3-8221-4aa9-a7c3-635edc4416b4" containerName="fd4a5a04-f132-4869-88f6-7642a316c615"
I0524 18:00:45.890869   74080 fake_topology_manager.go:34] "GetAffinity" podUID="d650b2a3-8221-4aa9-a7c3-635edc4416b4" containerName="d5b1234c-20c0-43fe-bd5c-2e1f9ae25eb2"
I0524 18:00:45.912430   74080 fake_topology_manager.go:34] "GetAffinity" podUID="d650b2a3-8221-4aa9-a7c3-635edc4416b4" containerName="e4aff7d0-a453-44c4-91a0-08a3fe58f3a0"
I0524 18:00:45.934035   74080 fake_topology_manager.go:34] "GetAffinity" podUID="d650b2a3-8221-4aa9-a7c3-635edc4416b4" containerName="e680ea10-0215-410f-9673-9b3144c69f83"
I0524 18:00:45.955932   74080 fake_topology_manager.go:29] "NewFakeManager"
I0524 18:00:45.955999   74080 fake_topology_manager.go:34] "GetAffinity" podUID="1178fab2-3be0-400f-b66d-afb363b36203" containerName=""
I0524 18:00:45.998977   74080 topology_hints.go:45] "Resource does not have a topology preference" resource="testdevice"
E0524 18:00:45.999116   74080 topology_hints.go:69] "Unable to generate topology hints: requested number of devices unavailable" resource="testdevice" request=6 available=4
I0524 18:00:45.999146   74080 topology_hints.go:60] "Regenerating TopologyHints for resource already allocated to pod" resource="testdevice" pod="" containerName="fakeContainer"
E0524 18:00:45.999174   74080 topology_hints.go:56] "Resource already allocated to pod with different number than request" resource="testdevice" pod="" containerName="fakeContainer" request=4 allocated=2
E0524 18:00:45.999196   74080 topology_hints.go:56] "Resource already allocated to pod with different number than request" resource="testdevice" pod="" containerName="fakeContainer" request=2 allocated=4
I0524 18:00:46.001236   74080 topology_hints.go:95] "Resource does not have a topology preference" resource="testdevice"
I0524 18:00:46.001305   74080 topology_hints.go:110] "Regenerating TopologyHints for resource already allocated to pod" resource="testdevice" pod=""
E0524 18:00:46.001344   74080 topology_hints.go:118] "Unable to generate topology hints: requested number of devices unavailable" resource="testdevice" request=6 available=4
I0524 18:00:46.001361   74080 topology_hints.go:110] "Regenerating TopologyHints for resource already allocated to pod" resource="testdevice" pod=""
E0524 18:00:46.001386   74080 topology_hints.go:106] "Resource already allocated to pod with different number than request" resource="testdevice" pod="" request=4 allocated=2
E0524 18:00:46.001403   74080 topology_hints.go:106] "Resource already allocated to pod with different number than request" resource="testdevice" pod="" request=2 allocated=4
FAIL
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/devicemanager	2.715s
FAIL
```
 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
```
go test ./pkg/kubelet/cm/devicemanager
stress -p 5 ./devicemanager.test
```

Running stress for about 100 or 1000 times in you env would help to verify the flake.

**Comment by HongjiangHuang** [comment]
> ```
> go test ./pkg/kubelet/cm/devicemanager
> stress -p 5 ./devicemanager.test
> ```
> 
> Running stress for about 100 or 1000 times in you env would help to verify the flake.

image

😅 my stress does not seem to have a -p option.
Can you tell me what -p for?

**Comment by pacoxu** [comment]
https://pkg.go.dev/golang.org/x/tools@v0.1.0/cmd/stress

```
  -p N
    	run N processes in parallel (default 4)
```
https://github.com/golang/tools/blob/v0.1.2/cmd/stress/stress.go#L32

**Pull request closed without merging**
