### PR TITLE
Experiment to see if slow reads block writes

### PR DESCRIPTION
**Pull request by lavalamp**
For @timothysc

### CODE REVIEW

**Comment by timothysc** [comment]
@lavalamp so this branch 'origin/pr/9031' seems to have other issues..  

Make test fails.

**Comment by lavalamp** [comment]
@timothysc How did shippable & travis both pass, then?

**Comment by timothysc** [comment]
@lavalamp dunno re: shippable. 

This patch doesn't really change the response profile.

**Comment by lavalamp** [comment]
OK, thanks for checking.

**Pull request closed without merging**
