### PR TITLE
apiserver: construct logger for httplog only when log level is  3

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
when `klog` log level is below `3`, remove httplog filter from the handler chain. We can avoid context copy and memory allocation associated with httplog.
 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
@MikeSpreitzer @wojtek-t let me know if this is useful. This is orthogonal to the optimization of key/value pairs in httplog we have discussed.

**Comment by MikeSpreitzer** [comment]
Sounds good, if you can make it actually work and pass the tests.

**Comment by tkashem** [comment]
Interesting, I am seeing the following error from watch
```
E0824 18:47:56.493042   56565 watch.go:180] unable to start watch - can't get http.Flusher: &metrics.ResponseWriterDelegator{ResponseWriter:(*http2.responseWriter)(0xc00efb3e30), status:0, written:0, wroteHeader:false}
```

So httplog actually embeds the `http.ResponseWriter` of the request with a `Flusher`. I will need to find a way to decouple this.

**Comment by deads2k** [comment]
The verbosity can change at runtime, so we cannot statically exclude the http log.

/hold

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
Well, I suppose the tests ought to pass.
/remove-lgtm

**Comment by tkashem** [comment]
@MikeSpreitzer I am hoping https://github.com/kubernetes/kubernetes/pull/104920 will fix the failed tests here.

**Comment by tkashem** [comment]
> The verbosity can change at runtime, so we cannot statically exclude the http log.

@deads2k I changed the PR to do the check at runtime - for each request, if log level is 3 only then we enable httplog for the given request.

**Comment by deads2k** [comment]
My concern about handling log level change was addressed.

/hold cancel

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
