### PR TITLE
Fix golint issues in pkg/apis/autoscaling/validation

### PR DESCRIPTION
**Pull request by hvaara**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint issues in `pkg/apis/autoscaling/validation`

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:
There's a [spelling change](https://github.com/kubernetes/kubernetes/pull/85041/files#diff-4364e3f754b12e39f60eea33105f6c7eR137) in the field of one of the errors. I don't know if this needs a release-note. Please let me know and I'll update the PR description.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/area code-organization
/sig testing

### CODE REVIEW

**Comment by hvaara** [comment]
@liggitt Thanks for reviewing and approving!

Does the [spelling change](https://github.com/kubernetes/kubernetes/pull/85041/files#diff-4364e3f754b12e39f60eea33105f6c7eR137) require a release-note? Otherwise I'll set it to `NONE`.

**Comment by liggitt** [comment]
no release note required

**Pull request merged**
