### PR TITLE
Move scheduler's SchedulerExtender interface to core/extenders.go

### LINKED ISSUE #87396: Move scheduler's SchedulerExtender interface to core/extenders.go
```scheduler/algorithm``` is deprecated, and ```SchedulerExtender``` must move somewhere else, and the best place is in ```core/extenders.go```.

/sig scheduling
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Move scheduler's SchedulerExtender interface to core/extenders.go

**Which issue(s) this PR fixes**:

Fixes #87396

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by haosdent** [comment]
```

1m56s
--
# k8s.io/kubernetes/pkg/scheduler/core pkg/scheduler/core/generic_scheduler.go:40:2: imported and not used: "k8s.io/kubernetes/pkg/scheduler/algorithm" !!! [0121 01:36:08] Call tree: !!! [0121 01:36:08]  1: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...) !!! [0121 01:36:08]  2: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...) !!! [0121 01:36:08]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...) !!! [0121 01:36:08] Call tree: !!! [0121 01:36:08]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...) !!! [0121 01:36:08] Call tree: !!! [0121 01:36:08]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...) make[1]: *** [Makefile:93: all] Error 1


```

```
diff -u ./pkg/scheduler/factory.go.orig ./pkg/scheduler/factory.go
--- ./pkg/scheduler/factory.go.orig	2020-01-21 01:57:32.894849188 +0000
+++ ./pkg/scheduler/factory.go	2020-01-21 01:57:32.894849188 +0000
@@ -37,7 +37,6 @@
 	"k8s.io/client-go/tools/cache"
 	"k8s.io/klog"
 	kubefeatures "k8s.io/kubernetes/pkg/features"
-	"k8s.io/kubernetes/pkg/scheduler/core"
 	"k8s.io/kubernetes/pkg/scheduler/algorithmprovider"
 	schedulerapi "k8s.io/kubernetes/pkg/scheduler/apis/config"
 	"k8s.io/kubernetes/pkg/scheduler/apis/config/validation"
diff -u ./pkg/scheduler/core/generic_scheduler_test.go.orig ./pkg/scheduler/core/generic_scheduler_test.go
--- ./pkg/scheduler/core/generic_scheduler_test.go.orig	2020-01-21 01:57:33.014860936 +0000
+++ ./pkg/scheduler/core/generic_scheduler_test.go	2020-01-21 01:57:33.018861327 +0000
@@ -36,9 +36,9 @@
 	"k8s.io/apimachinery/pkg/util/wait"
 	"k8s.io/client-go/informers"
 	clientsetfake "k8s.io/client-go/kubernetes/fake"
-	"k8s.io/kubernetes/pkg/scheduler/core"
 	schedulerapi "k8s.io/kubernetes/pkg/scheduler/apis/config"
 	extenderv1 "k8s.io/kubernetes/pkg/scheduler/apis/extender/v1"
+	"k8s.io/kubernetes/pkg/scheduler/core"
 	"k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpodtopologyspread"
 	"k8s.io/kubernetes/pkg/scheduler/framework/plugins/interpodaffinity"
 	"k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodeaffinity"
diff -u ./pkg/scheduler/core/extender_test.go.orig ./pkg/scheduler/core/extender_test.go
--- ./pkg/scheduler/core/extender_test.go.orig	2020-01-21 01:57:33.026862110 +0000
+++ ./pkg/scheduler/core/extender_test.go	2020-01-21 01:57:33.026862110 +0000
@@ -33,9 +33,9 @@
 	"k8s.io/client-go/informers"
 	clientsetfake "k8s.io/client-go/kubernetes/fake"
 	podutil "k8s.io/kubernetes/pkg/api/v1/pod"
-	"k8s.io/kubernetes/pkg/scheduler/core"
 	schedulerapi "k8s.io/kubernetes/pkg/scheduler/apis/config"
 	extenderv1 "k8s.io/kubernetes/pkg/scheduler/apis/extender/v1"
+	"k8s.io/kubernetes/pkg/scheduler/core"
 	"k8s.io/kubernetes/pkg/scheduler/framework/plugins/queuesort"
 	framework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
 	internalcache "k8s.io/kubernetes/pkg/scheduler/internal/cache"
diff -u ./pkg/scheduler/scheduler_test.go.orig ./pkg/scheduler/scheduler_test.go
--- ./pkg/scheduler/scheduler_test.go.orig	2020-01-21 01:57:33.370895785 +0000
+++ ./pkg/scheduler/scheduler_test.go	2020-01-21 01:57:33.370895785 +0000
@@ -43,7 +43,6 @@
 	clientcache "k8s.io/client-go/tools/cache"
 	"k8s.io/client-go/tools/events"
 	volumescheduling "k8s.io/kubernetes/pkg/controller/volume/scheduling"
-	"k8s.io/kubernetes/pkg/scheduler/core"
 	schedulerapi "k8s.io/kubernetes/pkg/scheduler/apis/config"
 	"k8s.io/kubernetes/pkg/scheduler/core"
 	frameworkplugins "k8s.io/kubernetes/pkg/scheduler/framework/plugins"

Run ./hack/update-gofmt.sh
```

Forgot to rebase?

**Comment by haosdent** [comment]
Rest part LGTM besides build failure, need @ahg-g @Huang-Wei to help to continue to review.

**Comment by haosdent** [comment]
```

6m43s
--
import cycle not allowed in test package k8s.io/kubernetes/pkg/scheduler/core (test) 	imports k8s.io/kubernetes/pkg/scheduler/core # k8s.io/kubernetes/pkg/scheduler vet: pkg/scheduler/scheduler_test.go:944:28: SchedulerExtender not declared by package algorithm make[1]: *** [Makefile:386: vet] Error 1


```

**Comment by ahg-g** [comment]
/lgtm
/approve

Thanks

**Pull request merged**
