### PR TITLE
Automated cherry pick of #102213: Upgrade konnectivity-client for GRPC connection fixes

### PR DESCRIPTION
**Pull request by cheftako**
Cherry pick of #102213 on release-1.20.

#102213: Upgrade konnectivity-client for GRPC connection fixes

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

#### Does this PR introduce a user-facing change?
```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
None
```

### CODE REVIEW

**Comment by cheftako** [comment]
Related to #102273

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
@cheftako can you please rebase?

**Comment by cheftako** [comment]
> Walter Fender can you please rebase?

Done, and thanks :D

**Comment by cpanato** [comment]
/reopen
closed by mistake

**Comment by cpanato** [comment]
weird, it says it is closed but it is merged (https://github.com/kubernetes/kubernetes/commits/release-1.20)

some weird state happen here, do you know who can looks at it? @nikhita @mrbobbytables

**Comment by cheftako** [comment]
> weird, it says it is closed but it is merged (https://github.com/kubernetes/kubernetes/commits/release-1.20)
> 
> some weird state happened here, do you know who can look at it? Nikhita Raghunath Bob Killen

https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml#L28 makes it look like it has legitimately been merged.

**Pull request closed without merging**
