### PR TITLE
Support loading UTF16 files if a byte-order-mark is present

### PR DESCRIPTION
**Pull request by brendandburns**
Add support in kubectl for loading UTF16 encoded files if they have a correct BOM (Byte-Order-Mark https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning
of the file. Falls back on UTF8 encoding, if no understandable BOM is present.

Fixes part of https://github.com/kubernetes/kubernetes/issues/39007

@fabianofranz @deads2k @kubernetes/sig-cli-misc

### CODE REVIEW

**Comment by brendandburns** [comment]
hold on this, I need to add a flag...

**Comment by brendandburns** [comment]
Ok, no need for a flag, slight refactor.

**Comment by deads2k** [comment]
Change looks fine to me.  Can you rename the first commit to `bump(golang.org/x/text): 2910a502d2bf9e43193af9d68ca516529614eed3`?

How would we deal with names that have funny characters in them?  Not all types are restricted to ascii.

@fabianofranz any concerns?  If not, I'll tag after the commit name gets updated.

**Comment by fabianofranz** [comment]
> @fabianofranz any concerns?

Nothing from me.

**Comment by brendandburns** [comment]
@deads2k renamed, ptal.

Thanks!

**Comment by brendandburns** [comment]
@k8s-bot gci gce e2e test this

**Comment by deads2k** [comment]
@brendandburns tagged.  I think its release-note worthy if you could type one into your description.

**Comment by brendandburns** [comment]
@k8s-bot bazel test this

**Comment by brendandburns** [comment]
@deads2k thanks, updated.

**Pull request merged**
