### PR TITLE
Moves table printing out of Kubernetes core

### PR DESCRIPTION
**Pull request by seans3**
* Moves table printing (in humanreadble.go) into cli-runtime repository; a common repository out of core
* Copies PrintOptions into cli-runtime/interfaces.go
* Updates humanreadable_flags.go (in `pkg/kubectl`) to use the moved code.
* Updates `pkg/registry` storage.go files to use the moved code.

Helps address:
kubernetes/kubectl#80

```release-note
NONE
```
/kind cleanup
/sig cli
/assign

### CODE REVIEW

**Comment by liggitt** [comment]
There are several distinct things in the humanreadable printer, used by different components:

Used by the server:
1. Given an object and a matching printer handler, make a table (`HumanReadablePrinter#PrintTable()`). This is only used by the server and should stay in the server, not move to cli-runtime. (as an aside, it calls DecorateTable(), but does not actually need to... none of the options passed to PrintTable exercise anything inside DecorateTable())

Used by kubectl:
1. Given a table object, print it (`HumanReadablePrinter#PrintObj()`, `if table, ok := obj.(*metav1beta1.Table); ok` case). This should move to cli-runtime as a `NewTablePrinter() ResourcePrinter` (and not expose `metav1beta1.Table` externally in any function signatures so we can graduate it to handle both `metav1beta1.Table` and `metav1.Table` without breaking consumers)

2. Given a non-table object, and no matching registered handler, print it (`HumanReadablePrinter#PrintObj()`, `if h.defaultHandler != nil` case). This is probably ok to keep as an option (whether to print default columns or just return an error if asked to print a non-table), but I don't think we need to allow customization of how non-table objects are printed by the table printer (we don't use that flexibility today, and omitting the DefaultTableHandler method would avoid referencing `metav1beta1.TableColumnDefinition` objects in function signatures).

3. Given a non-table object, and a matching registered handler, print it (`HumanReadablePrinter#PrintObj()`, `if handler := h.handlerMap[t]; handler != nil` case). I don't think we should move this to cli-runtime, since we don't intend to support this beyond this release.

I think a good first step would be to split HumanReadablePrinter into TablePrinter and TableGenerator in the existing package, to start teasing apart the server and client use.

**Comment by liggitt** [comment]
cc @smarterclayton

**Comment by seans3** [comment]
Closing this PR, since we will move in a different direction. As Jordan described, we will break up `humanreadable.go` into the server part (table generation), and the client part (table printing). We will move the client part used by `kubectl` into `k8s.io/cli-runtime/pkg/printers`.

**Pull request closed without merging**
