### PR TITLE
Fix Informer Race

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: #27004

This is a possible workaround. It force the queue to wait for Replace, Add, Update, Delete synchronized with store side.

I have a couple of thoughts during my path to finding the solution:
- Resync is unnecessary. Even though with this workaround there is still race. I remember from the original resync issue&PR, RH folks mentioned that they were missing events. Now I'm not surprised with the race we found. Once we fix the race we shouldn't use resync at all.
- The store and queue is tightly coupled. There is a lot of race conditions without locking the entire store, e.g. between ListKeys() and GetKeyBy(X), between queue.Add() and store.Add()... I would like to spend more time on redesigning the interaction between queue and store and make synchronization in one place -- preferably the store.

### CODE REVIEW

**Comment by lavalamp** [comment]
Thanks for working on this!!

This is sorta close to what I'd expect, but I don't understand why you're signalling a condition variable in your SyncStore. I guess I'd just expect you to share a lock between informer and the sync store, and the sync store should lock around add, update, or delete. You may have to be slightly clever to prevent both Informer AND the sync store trying to lock when the informer itself makes a change or checks something.

**Comment by lavalamp** [comment]
> Resync is unnecessary

No, many controllers need to periodically revisit items.

**Comment by hongchaodeng** [comment]
The conditional variable is used to release the deltaFIFO.lock and wait until data is reflected on store. Basically, queue.Add/Delete are now sync-ed with store.Add/Delete.

> I guess I'd just expect you to share a lock between informer and the sync store, and the sync store should lock around add, update, or delete.

Can you clarify in details? If it's taking too much time, feel free to take over the code.

> No, many controllers need to periodically revisit items.

Would you mind sharing any use case for Resync? If they need to relist all items why don't they just call store.List()?

**Pull request closed without merging**
