### PR TITLE
k8s.io/code-generator: Enable generate-*  scripts usage as module deps

### PR DESCRIPTION
**Pull request by LorbusChris**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

So far, the generate scripts could not be required as dependencies
with Go Modules (e.g. in tools.go) as they were installed without
proper module context.

This commit enables the generator scripts to be used as versioned
dependencies with Go Modules by forcing installation into
the fully-qualified module directory.

**Which issue(s) this PR fixes**:
Fixes #91358 #85559

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```
/cc @liggitt @sttts

### CODE REVIEW

**Comment by liggitt** [comment]
/ok-to-test

this looks good to me, would like sttts to take a look

**Comment by liggitt** [comment]
verify failure looks related:

```
Generating deepcopy funcs
F0805 20:08:12.764648   21389 deepcopy.go:131] Failed loading boilerplate: open /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0000c6001, 0xc008f4b680, 0xd2, 0x122)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x9a19a0, 0xc000000003, 0x0, 0x0, 0xc004ae36c0, 0x97a42b, 0xb, 0x83, 0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x9a19a0, 0x3, 0x0, 0x0, 0x78a3a2, 0x1e, 0xc00787fae8, 0x1, 0x1)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
k8s.io/gengo/examples/deepcopy-gen/generators.Packages(0xc004ae2070, 0xc0000d4f00, 0x7679be, 0x6, 0xc004ae2070)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/gengo@v0.0.0-20200428234225-8167cfdcfc14/examples/deepcopy-gen/generators/deepcopy.go:131 +0xf7
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000d4f00, 0xc00787fe38, 0x7679be, 0x6, 0x7952d0, 0x0, 0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/gengo@v0.0.0-20200428234225-8167cfdcfc14/args/args.go:206 +0x1a9
main.main()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:77 +0x46b

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x9a19a0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:416 +0xd8
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-codegen.sh	293s
```

**Comment by liggitt** [comment]
I think the boilerplate default is counting on the package path including the k8s.io/kubernetes/vendor prefix:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/pkg/util/build.go#L60

that doesn't seem right

**Comment by LorbusChris** [comment]
@liggitt installing twice, with relative path and fully qualified module path seems to work. Not super pretty though :/

**Comment by liggitt** [comment]
> @liggitt installing twice, with relative path and fully qualified module path seems to work. Not super pretty though :/

it seems like the last one installed will win, and will be wrong in one environment or the other

**Comment by liggitt** [comment]
it seems likely the implementation of `DefaultSourceTree()`, `CurrentPackage()` or `BoilerplatePath()` might need adjusting

**Comment by LorbusChris** [comment]
Unfortunately, I won't be able to look into fixing those any time soon. :/

**Comment by LorbusChris** [comment]
Hm actually, this may already work as-is with Go Modules?!

One remaining problem though is that the scripts won't have the executable bit when vendoring them with `go mod vendor`.

**Comment by caesarxuchao** [comment]
/assign @sttts @liggitt 

Thanks for taking a look.

**Comment by LorbusChris** [comment]
To clarify exactly what works: Doing this in e.g. `tools.go`, the scripts are correctly vendored with `go mod vendor`:
```
import (
	_ "k8s.io/code-generator" // Imports non-go generator scripts
)
```

**Comment by LorbusChris** [comment]
> it seems likely the implementation of `DefaultSourceTree()`, `CurrentPackage()` or `BoilerplatePath()` might need adjusting

It looks like this is issue https://github.com/kubernetes/kubernetes/issues/82531

Wondering whether this PR here can be closed.

**Pull request closed without merging**
