### PR TITLE
Move DescribeIng() into e2eingress

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

The function is only for e2e ingress test, it is not necessary to keep the function in e2e test core framework.

Ref: https://github.com/kubernetes/kubernetes/issues/77095

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
/test pull-kubernetes-node-e2e-containerd
/lgtm  
good job!

**Review by gavinfish — COMMENTED** [review]
/lgtm
The failing test is tracked at #89847

**Pull request merged**
