### PR TITLE
 Presize map with proper capacity in cache

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The Snapshot function of pkg/scheduler/internal/cache/cache.go can presize the cloned maps with sizes of respective maps.

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
/ok-to-test

please combine those commits into one.

**Comment by tedyu** [comment]
Close in favor of #73727

**Pull request closed without merging**
