### PR TITLE
Ensure we capture http and trace related logs

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I64a30029778615e679b244ddba801833218d1573

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

When we are running apiserver related code, we do not currently capture
the logs from `httplog.NewLogged` and `trace.LogIfLong` since the
default log verbosity is not set. So just make sure we have a minimum
verbosity set in these circumstance.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

[Given that we run all e2e tests (non-scalability ones) at v4 verbosity also]

**Comment by alculquicondor** [comment]
Why not do this via command line flags?
Sometimes the verbosity gets in the way for local development.

**Pull request merged**
