### PR TITLE
docs: fix storage e2e test README

### PR DESCRIPTION
**Pull request by cvvz**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by RomanBednar** [comment]
The focus regex suggested seems correct:

Old:
```
$ ginkgo -v --dry-run -focus='External.Storage.*csi-hostpath' -skip='\[Feature:|\[Disruptive\]'  ./_output/local/go/bin/e2e.test -- -storage.testdriver=/tmp/hostpath-testdriver.yaml | grep Specs
Ran 0 of 7490 Specs in 0.218 seconds
```

New:
```
$ ginkgo -v --dry-run -focus='External.Storage.*hostpath.csi.k8s.io' -skip='\[Feature:|\[Disruptive\]'  ./_output/local/go/bin/e2e.test -- -storage.testdriver=/tmp/hostpath-testdriver.yaml | grep Specs
Ran 185 of 7490 Specs in 0.279 seconds
```

/lgtm

**Comment by mattcary** [comment]
/release-note-none

(this is just test docs change)

**Pull request merged**
