### PR TITLE
clustertrustbundle, token_manager: migrate to contextual logging

### PR DESCRIPTION
**Pull request by oxxenix**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
migrate `pkg/kubelet/clustertrustbundle`, `pkg/kubelet/token_manager` to contextual logging

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/wg structured-logging
/area logging
/priority important-longterm
/cc @kubernetes/wg-structured-logging-reviews

### CODE REVIEW

**Comment by bart0sh** [comment]
/lgtm

/assign @SergeyKanzhelev @mrunalp 
for approval

**Review by mrunalp — APPROVED** [review]

**Comment by bart0sh** [comment]
@pohly @liggitt @dims Can you approve `golangci` config changes in  the `hack` directory?

**Pull request merged**
