### PR TITLE
Add Heapster liveness probe

### PR DESCRIPTION
**Pull request by mksalawa**
**What this PR does / why we need it**:
Add liveness probe for heapster service.

**Which issue this PR fixes**
[https://github.com/kubernetes/heapster/issues/1251](https://github.com/kubernetes/heapster/issues/1251)

**Release note**:

``` release-note
Added liveness probe to Heapster service.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31878)

### CODE REVIEW

**Comment by mksalawa** [comment]
cc @piosz

**Comment by piosz** [comment]
add to whitelist

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
This is required for #29023 so should be include into 1.4.

**Comment by piosz** [comment]
ok to test

**Comment by piosz** [comment]
cc @mwielgus

**Pull request merged**
