### PR TITLE
'kubectl config get-contexts'

### PR DESCRIPTION
**Pull request by minjungsung1994**
Implemented json option for output

#### What type of PR is this?
feature

#### What this PR does / why we need it:
This feature can provide json option for 'kubectl config get-contexts' command
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
NONE
#### Does this PR introduce a user-facing change?

```release-note
Implemented json option for output
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lauchokyip** [comment]
Hi @minjungsung1994 , thanks for the PR! 

Before reviewing, can you provide some contexts why the outputting json from the command `kubectl config get-ontexts` would be needed?

**Comment by minjungsung1994** [comment]
Hello, @lauchokyip 
I wanted to shoot kubectl command result to frontend in my page and to do so, it's better to
get the result in JSON format. Other commands like 'kubectl get pods' support JSON output and I thought
why not for 'kubectl config get-contexts'.

**Comment by eddiezane** [comment]
> Hello, @lauchokyip I wanted to shoot kubectl command result to frontend in my page and to do so, it's better to get the result in JSON format. Other commands like 'kubectl get pods' support JSON output and I thought why not for 'kubectl config get-contexts'.

Thanks for the PR and explanation! Since this data is already available locally JSON output isn't something we'd want add to the command. I'd recommend you pull it from the kubeconfig directly.

**Comment by minjungsung1994** [comment]
@eddiezane 
It's not the matter of whether the data is available or unavailable. It's just one way to export the data (in this case, in JSON format). If I want to convert the data in JSON format, it requires much longer lines on client-side. Also, this JSON output feature is supported for many kubernetes commands, except some. If you look at the code, this output function was supposed to be supported in other forms as well. From the codeline, it seeems like someone was trying to add more output formats, but either forgot or didn't have enough time to do so. 
`	
if !validOutputTypes.Has(outputFormat) {
		return fmt.Errorf("output must be one of '' or 'name': %v", outputFormat)
}
`
If I understand wrong about "the data is available part", I would like to know more about it. Also, if you have a better way to export the data in JSON format instead of changing this file, may I have your opinion
@KnVerey Adding her to this, since she reviewed this pr as well :)

**Comment by minjungsung1994** [comment]
@pwittrock @eddiezane :  Ready for review

**Comment by eddiezane** [comment]
@minjungsung1994 does the output of `kubectl config view -o json` meet your needs?

**Comment by minjungsung1994** [comment]
@eddiezane Yes, eventually it gives the output that I wanted, but are there any reasons/rules not to have this option if it can be covered with other commands?

**Comment by eddiezane** [comment]
> are there any reasons/rules not to have this option if it can be covered with other commands?

We try to avoid adding extra things to maintain if the functionality exists elsewhere.

I discussed this with the other maintainers and we agreed that the functionality provided by `kubectl config view` already covers the use case and elect to not merge this.

If you're looking for other ways to contribute I can point you to some issues though!

**Comment by minjungsung1994** [comment]
@eddiezane If you're looking for other ways to contribute I can point you to some issues though! >> I would like to know those opportunities

**Pull request closed without merging**
