### PR TITLE
Cherry pick of #107033: Remove JSON logging performance regression

### PR DESCRIPTION
**Pull request by serathius**
Cherry pick of #107035 on release-1.23.

#107035: Remove JSON logging performance regression

For details on the cherry pick process, see the cherry pick requests page.

```release-note
Fix 1.23 performance regression in JSON logging caused by syncing stdout every time error was logged.
```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@serathius can you add to this PR the same release note from the master PR?

**Comment by cpanato** [comment]
@serathius I don't see a PR for the main branch, this is something that only applies to this branch? does the main branch is already fixed?
can you clarify a bit? thanks!

**Comment by ialidzhikov** [comment]
This is the PR for the main branch - https://github.com/kubernetes/kubernetes/pull/107035.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@cpanato , what about the release note? Will it be picked automatically from the corresponding PR for the main branch?

**Comment by cpanato** [comment]
> @cpanato , what about the release note? Will it be picked automatically from the corresponding PR for the main branch?

yes, I've update the PR description to match the main PR, before was linking to an issue, that is why we saw the release needed label

**Pull request merged**
