### PR TITLE
Increase test coverage in `pkg/controllers/podautoscaler/metrics`

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

Increase test coverage for `pkg/controllers/podautoscaler/metrics`. The biggest addition is unit tests for `pkg/controller/podautoscaler/metrics/utilization.go`.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/lgtm
/approve no-issue

@mattjmcnaughton Great job, really appreciated. Thanks!

**Comment by mattjmcnaughton** [comment]
My pleasure @MaciekPytel - thanks for the review :)

**Pull request merged**
