### PR TITLE
Bumped rescheduler version to 0.3.0

### LINKED ISSUE #32531: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/2248/

Failed: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:67
Expected error:
    <*errors.errorString | 0xc8211e20b0>: {
        s: "Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels \"k8s-app=kube-dns,version=v19\" to be running",
    }
    Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels "k8s-app=kube-dns,version=v19" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:66
```

Previous issues for this test: #31277 #31347 #31710 #32260

### PR DESCRIPTION
**Pull request by piosz**
fix #32531

https://github.com/kubernetes/contrib/pull/2474 needs to be merged first

cc @ethernetdan @marun @k82cn @aveshagarwal 

``` release-note
Rescheduler uses taints in v1beta1 and will remove old ones (in version v1alpha1) right after its start.
```

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot unit test this

**Comment by Random-Liu** [comment]
@piosz Please update the release note. This is still shown as TBD in our release note.
https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md#other-notable-changes

**Comment by piosz** [comment]
@Random-Liu thanks for reminder. Done.

@davidopp should I add something about the upgrade procedure here? Also feel free to edit.

**Comment by davidopp** [comment]
@piosz If there is something the user needs to do when upgrading from 1.5 to 1.6 then yes you should put it in the "breaking changes" of the "scheduling SIG" section of the release notes. IIRC there was some nontrivial instructions for people who don't upgrade all master components approximately atomically?

**Pull request merged**
