### PR TITLE
Automated cherry pick of #116749: Adding additional validations to queried endpoint

### PR DESCRIPTION
**Pull request by princepereira**
Cherry pick of #116749 on release-1.26.

#116749: Adding additional validations to queried endpoint

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix 1.25 regression in WinProxy sync to handle queried endpoints without any IpConfigurations
```

### CODE REVIEW

**Comment by marosset** [comment]
@sbangari @MikeZappa87 for owner approval

**Comment by marosset** [comment]
@sbangari @MikeZappa87 - ping

**Review by MikeZappa87 — APPROVED** [review]

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
