### PR TITLE
remove validation for gce pd replica

### LINKED ISSUE #114436: validation has a GCE-ism baked in
pkg/apis/core/validation/validation.go

```
func ValidateReadOnlyPersistentDisks(volumes []core.Volume, fldPath *field.Path) field.ErrorList {                                                                             
    allErrs := field.ErrorList{}
    for i := range volumes {
        vol := &volumes[i]
        idxPath := fldPath.Index(i)
        if vol.GCEPersistentDisk != nil {
            if !vol.GCEPersistentDisk.ReadOnly {
                allErrs = append(allErrs, field.Invalid(idxPath.Child("gcePersistentDisk", "readOnly"), false, "must be true for replicated pods > 1; GCE PD can only be mounted on multiple machines if it is read-only"))
            }    
        }    
        // TODO: What to do for AWS?  It doesn't support replicas
    }    
    return allErrs
}
```

We should probably just get rid of this.

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind cleanup
/kind feature

#### What this PR does / why we need it:
This validation is **not** critical, it can be removed and rely on the platform error.
#### Which issue(s) this PR fixes:

Fixes #114436 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Removing validation is not simple. This is because, during an upgrade, there might be an apiserver running a version below that would attempt to validate the field.

- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#backward-compatibility-gotchas
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#new-enum-value-in-existing-field (this is a similar example of loosening validation).

**Comment by thockin** [comment]
This shouldn't be so bad - add a feature-gate which, if set, skip this validation.  Roll that out in one release, change it to on-by-default in next release.

**Comment by alculquicondor** [comment]
I should have said "not that simple" :)

Although I talked with @kidddddddddddddddddddddd in slack and they said that they would pick up the task if nobody else makes progress on it.

**Comment by alculquicondor** [comment]
> This shouldn't be so bad - add a feature-gate which, if set, skip this validation. Roll that out in one release, change it to on-by-default in next release.

We already have patterns for this, and it's not with feature gates. Feature gates are not enough because the objects that are already failing validation need to keep passing.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#new-enum-value-in-existing-field

**Comment by kidddddddddddddddddddddd** [comment]
> This shouldn't be so bad - add a feature-gate which, if set, skip this validation. Roll that out in one release, change it to on-by-default in next release.

I'm aware of this now, at first I don't have a idea. I see someone else has picked up that issue :).

**Pull request closed without merging**
