### PR TITLE
feat(cli):Add inherit flag for kubectl config set-context command

### LINKED ISSUE #38053: current context set to "" (no character)
**Working environment**: 2 CoreOS instances (master+worker)

**Problem**: Current-context set to ""

**Steps to reproduce:**
 Basically, use this command:

`$ kubectl config set-context $CONTEXT --namespace=<insert-namespace-name-here>`

without any value in the $CONTEXT environment.

Now I can't switch back to any namespaces.

```
$ kubectl config view 
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
Fixes #38053 #7804

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Comment by zjj2wry** [comment]
@deads2k Still need this `inherit` flag? this will fix two issues.

**Comment by liggitt** [comment]
I'm not sure about adding this to this command. Would you expect it to overwrite current values for the target context with the values from the current context, or only default empty ones? 

If we want to keep the config commands granular, a `copy-context --from=... --to=...` would let you replicate a context, then set one aspect of the new context

**Comment by zjj2wry** [comment]
@liggitt i want inherit current-context as default when `--inherit=true`. as issue #38053, user want only update namespace. this flag will help this.

**Comment by liggitt** [comment]
if the context being edited and the current context both have a value, it's ambiguous which should take precedence. What would you expect to result from this:

starting kubeconfig:
```yaml
…
contexts:
- name: a
  context:
     user: a-user
     cluster: a-cluster
     namespace: a-namespace
- name: b
  context:
    user: b-user
    cluster: b-user
    namespace: b-namespace
current-context: b
```

command:
```
kubectl config set-context a --inherit --namespace=new-namespace
```

**Comment by liggitt** [comment]
Duplicating an existing context and modifying values in a context are two distinct operations, akin to `cp file1 file2 && vi file2`

**Comment by zjj2wry** [comment]
@liggitt thank you remind this, seems this will overwrite. this is not expected, right?

if i copy then edit, should we have a command can combine multi config file?

**Pull request closed without merging**
