### PR TITLE
Revert "storage e2e: disable health check containers"

### LINKED ISSUE #101336: e2e storage: re-enable health check sidecars
#### What would you like to be added:

https://github.com/kubernetes/kubernetes/pull/100637 added newer hostpath deployments but removed the csi-external-health-monitor-agent because it seemed to cause overhead without being needed for the tests.

#### Why is this needed:

We should re-enable it and check whether that really causes tests to fail because of the extra load.

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This reverts commit 0c2cee5676e64976f9e767f40c4c4750a8eeb11f.

The health check containers are not required for any test, but we want
to run them anyway to ensure that they cause no unexpected issues.

#### Comments for reviewers

I'm going to run pull tests multiple times to verify whether the health check containers affect testing.

With sidecars:
- 15 tests failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385117021733130240
- 4 tests failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385137151947051008
- Success: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385164516391653376
- Success: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385189339390021632

Without sidecars:
- 19 tests failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385214623258513408
- 2 tests failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385230066312548352
- 8 tests failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101360/pull-kubernetes-e2e-kind/1385247969111969792

#### Which issue(s) this PR fixes:
Fixes #101336 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
The pull-kubernetes-e2e-kind job is very flaky, without and without the health check sidecars. In my experiments (see description), it actually was worse without them.

Therefore enabling these sidecars again should be okay.

**Comment by mauriciopoppe** [comment]
I created a GKE cluster and I tried running a CSI hostpath e2e test with the latest version of the master branch (May 6th), I saw that the two new containers in `csi-hostpathplugin` are always showing as unhealthy with this error:

```
I0506 21:37:57.830822       1 main.go:82] Version: v0.2.0
 I0506 21:37:58.032923       1 connection.go:153] Connecting to unix:///csi/csi.sock
 I0506 21:37:58.054920       1 common.go:111] Probing CSI driver for readiness
 I0506 21:37:58.054953       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
 I0506 21:37:58.054963       1 connection.go:183] GRPC request: {}
 I0506 21:37:58.069293       1 connection.go:185] GRPC response: {}
 I0506 21:37:58.069471       1 connection.go:186] GRPC error: <nil>
 I0506 21:37:58.069517       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
 I0506 21:37:58.069527       1 connection.go:183] GRPC request: {}
 I0506 21:37:58.096833       1 connection.go:185] GRPC response: {"name":"csi-hostpath-ephemeral-3492","vendor_version":"v1.4.0"}
 I0506 21:37:58.097008       1 connection.go:186] GRPC error: <nil>
 I0506 21:37:58.097021       1 main.go:136] CSI driver name: "csi-hostpath-ephemeral-3492"
 I0506 21:37:58.097034       1 connection.go:182] GRPC call: /csi.v1.Node/NodeGetCapabilities
 I0506 21:37:58.097039       1 connection.go:183] GRPC request: {}
 I0506 21:37:58.246720       1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}}]}
 I0506 21:37:58.246984       1 connection.go:186] GRPC error: <nil>
 I0506 21:37:58.247010       1 main.go:158] CSI driver does not support Node VolumeCondition Capability, exiting
 stream closed
```

What's interesting is that the **test doesn't fail** however after plugin registration is done this pod goes to `CrashLoopBackOff` because of these two containers, even if the tests can pass with these unhealthy containers I believe that there's an additional workload in the kubernetes component that has to restart these two containers every 10s, 20s, 40s, etc.

**Comment by pohly** [comment]
We are currently running the E2E tests with an old csi-driver-host-path release due to another issue that blocked updating it. Once we release a new csi-driver-host-path, we can update the YAML files and this issue should go away.

**Comment by msau42** [comment]
What is the eta for that? We are trying to triage the increased test flakiness and this is issue is one suspect.

**Comment by pohly** [comment]
I'm waiting for someone to review my csi-driver-host-path PRs and (optionally) the patch releases of the sidecars. Then I can prepare a new release.

**Comment by pohly** [comment]
Regarding test flakiness: the baseline has to be with this PR and https://github.com/kubernetes/kubernetes/pull/100637. Then testing is done with old sidecars and old driver, which is consistent.

**Pull request merged**
