### PR TITLE
remove unused events in event.go

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
/ok-to-test

Thanks for this pr!

Could I trouble you to peruse this list and see if there are any other unused events in this pr that we can remove? For example, grepping shows me that `HostPortConflict` and `NodeSelectorMismatching` also are unused. (Also, if you don't have time to do this, just lmk and I'm happy to create an additional cleanup PR).

Also, quick gut check... is there ever a situation in which a k8s 1.x cluster could have created an event and a 1.y cluster needs to know how to handle it? So even if the 1.y cluster can't produce the event, we still need to keep it in the code base?

**Comment by mysunshine92** [comment]
> 
> 
> /ok-to-test
> 
> Thanks for this pr!
> 
> Could I trouble you to peruse this list and see if there are any other unused events in this pr that we can remove? For example, grepping shows me that `HostPortConflict` and `NodeSelectorMismatching` also are unused. (Also, if you don't have time to do this, just lmk and I'm happy to create an additional cleanup PR).
> 
> Also, quick gut check... is there ever a situation in which a k8s 1.x cluster could have created an event and a 1.y cluster needs to know how to handle it? So even if the 1.y cluster can't produce the event, we still need to keep it in the code base?

thank you for your suggestions. i will open another one PR for clean up work.

**Comment by mysunshine92** [comment]
cc @yujuhong 
please add an approved label, thanks.

**Comment by mysunshine92** [comment]
cc @cblecker 
please add an lgtm and approved label, thanks.

**Comment by mysunshine92** [comment]
cc @derekwaynecarr 
please add an lgtm and approved label, thanks.

**Comment by cblecker** [comment]
@mysunshine92 Please note: We are currently in the 1.15 release code freeze and as such this PR will not be able to be merged until that lifts. Thanks for your contribution!

**Comment by yujuhong** [comment]
/lgtm
/approve

As the previous comment said, this won't be merged until the code freeze is lifted. Thanks!

**Pull request merged**
