### PR TITLE
Update gofmt for go1.10, and fix go vet errors

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Update gofmt for go1.10, and fix go vet errors

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
/cc @BenTheElder 
This will need to get merged shortly after CI is updated to run testing in go1.10.1

**Comment by BenTheElder** [comment]
verify update here: https://github.com/kubernetes/test-infra/pull/7517

**Comment by cblecker** [comment]
Pushed an additional commit with govet fixes for the following errors:
```
I0403 00:29:19.091] Verifying verify-govet.sh
I0403 00:29:19.104] 
I0403 00:29:19.105] +++ Running case: verify.govet 
I0403 00:29:19.107] +++ working dir: /go/src/k8s.io/kubernetes
I0403 00:29:19.108] +++ command: bash "hack/make-rules/../../hack/verify-govet.sh"
W0403 00:34:10.547] # k8s.io/kubernetes/test/e2e_node/runner/remote
W0403 00:34:10.549] test/e2e_node/runner/remote/run_remote.go:137: struct field tag `json:"count, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.550] test/e2e_node/runner/remote/run_remote.go:145: struct field tag `json:"image, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.551] test/e2e_node/runner/remote/run_remote.go:146: struct field tag `json:"image_description, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.551] test/e2e_node/runner/remote/run_remote.go:149: struct field tag `json:"image_regex, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.552] test/e2e_node/runner/remote/run_remote.go:152: struct field tag `json:"previous_images, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.552] test/e2e_node/runner/remote/run_remote.go:154: struct field tag `json:"machine, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.553] test/e2e_node/runner/remote/run_remote.go:155: struct field tag `json:"resources, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:10.554] test/e2e_node/runner/remote/run_remote.go:157: struct field tag `json:"tests, omitempty"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
W0403 00:34:32.734] # k8s.io/kubernetes/test/e2e/scheduling
W0403 00:34:32.734] test/e2e/scheduling/nvidia-gpus.go:202: k8s.io/kubernetes/test/e2e/framework.ResourceGathererOptions composite literal uses unkeyed fields
W0403 00:34:42.459] # k8s.io/kubernetes/test/integration/master
W0403 00:34:42.460] test/integration/master/synthetic_master_test.go:669: loop variable k captured by func literal
I0403 00:34:47.741] Makefile:365: recipe for target 'vet' failed
I0403 00:34:47.748] +++ exit code: 2
I0403 00:34:47.752] +++ error: 1
I0403 00:34:47.773] FAILED   verify-govet.sh	328s
```

**Comment by cblecker** [comment]
For ease of review, this is mostly whitespace changes: https://github.com/kubernetes/kubernetes/pull/60599/files?w=1

**Comment by liggitt** [comment]
do these gofmt changes fail on go1.9?

**Comment by cblecker** [comment]
Yes, they do. CI was updated to go1.10, so we should get a green run off the verify job with these changes in place.

**Comment by cblecker** [comment]
I don't know about the govet changes though.. I'm not sure if they previously failed under 1.9.

**Comment by liggitt** [comment]
That's unfortunate, and will make picks painful

**Comment by cblecker** [comment]
I'm going to manually approve for `staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go`. It's whitespace changes on comment lines, and we want to get this PR in to fix pull-kubernetes-verify and ci-kubernetes-verify-master.

**Comment by BenTheElder** [comment]
FWIW the verify / integration image is rarely touched, it's possible verify is running somewhat stale govet etc. on the 1.9 image (maybe some 1.9.x instead of 1.9.3?), if these changes would pass under a go1.9 vet/fmt version then we can look at fixing those images.

**Pull request merged**
