### PR TITLE
Move pkg/kubectl/util/logs to staging

### PR DESCRIPTION
**Pull request by damemi**
* Moves pkg/kubectl/util/logs to staging
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util/logs.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Comment by damemi** [comment]
cc @seans3

**Comment by seans3** [comment]
/hold

temporarily

**Comment by apelisse** [comment]
/approve

for `vendor/modules.txt`

**Review by nikhita — APPROVED** [review]
/approve

**Pull request merged**
