### PR TITLE
Add tests for LessThanOrEqual

### PR DESCRIPTION
**Pull request by xychu**
#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xychu** [comment]
kindly ping @derekwaynecarr and @deads2k , grateful if you could have a look when it's convenient.

**Comment by dims** [comment]
@fedebongio this has an easy to review test case which really LGTM

/lgtm

**Pull request merged**
