### PR TITLE
Cherry pick of #15706

### PR DESCRIPTION
**Pull request by jszczepkowski**
HorizontalPodAutoscaler API: removal of ResourceConsumption target, introduction of CPU request utilization & other cleanups.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Jenkins tests failed due to known flakiness in kubectl: #15493.

**Comment by nikhiljindal** [comment]
fwiw, this PR added swagger-spec/v1beta1.json with ingress/{name}/status, even tough the corresponding change (https://github.com/kubernetes/kubernetes/pull/15783) hasnt been cherrypicked yet.
verify-swagger-spec should have failed, which it did when I tried to cherrypick https://github.com/kubernetes/kubernetes/pull/15785, but not sure why it did not fail on this PR.

**Comment by piosz** [comment]
There was an issue with swagger (see #15748). I don't know the details. @fgrzadkowski do you think it may be related?

**Comment by fgrzadkowski** [comment]
Good question. I'm not sure but it might.

**Pull request merged**
