### PR TITLE
Implement ResourceVersion and optimistic locking in the testing ObjectTracker

### LINKED ISSUE #463: testing ObjectTracker should implement ResourceVersion and optimistic locking
In other words `client-go/testing/fixture.go` should modify `ResourceVersion` on each `Update()` and error if the supplied version does not match the previous.

I have done a simple implementation of this for my own testing.

### PR DESCRIPTION
**Pull request by bboreham**
**What this PR does / why we need it**:

Ensure `ResourceVersion` changes on each object update, and return an error on updates attempted against the wrong version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes https://github.com/kubernetes/client-go/issues/463

**Special notes for your reviewer**:

**Release note**:
```release-note
Implement ResourceVersion and optimistic locking in the testing ObjectTracker (may cause unit tests which made unsafe assumptions to fail) 
```

### CODE REVIEW

**Comment by liggitt** [comment]
> Before I start fixing up the tests, which might take a while, I would appreciate some advice on whether (a) this whole idea is likely to be accepted and (b) whether any of those categories should actually work as the tests expect.

I don't think adding server-side behavior beyond simple existence checking is really something we should pursue. If a test wants to check a specific behavior, it can add a reactor to accomplish that.

**Comment by bboreham** [comment]
Ah.  Do you think there are existing cases where optimistic locking has been implemented as an additional reactor?

**Comment by liggitt** [comment]
> Do you think there are existing cases where optimistic locking has been implemented as an additional reactor?

the implementations I've seen are less concerned about reimplementing optimistic locking and are more concerned with exercising the controller's handling of conflict errors

for example:

https://github.com/kubernetes/kubernetes/blob/ba33abd5282acb9ee840d06a0e1fbf00466fbe4f/pkg/controller/history/controller_history_test.go#L506-L521

https://github.com/kubernetes/kubernetes/blob/ba33abd5282acb9ee840d06a0e1fbf00466fbe4f/pkg/controller/history/controller_history_test.go#L623-L638

https://github.com/kubernetes/kubernetes/blob/ba33abd5282acb9ee840d06a0e1fbf00466fbe4f/pkg/controller/history/controller_history_test.go#L548-L550

**Comment by bboreham** [comment]
Thanks.  That's very different from what I wanted to do, which was to flush out a race condition by executing my code thousands of times from multiple goroutines.

FWIW I did not pick up from reading the code that I should do it as a Reactor.  It talks about embedding `Fake` into a struct, and "faking out just the method you want to test".

**Comment by bboreham** [comment]
On further reflection, I don't think the behaviour can be implemented as an additional reactor, since the check must be done with a lock around the data store.

Also I observe that the [key part of your example](https://github.com/kubernetes/kubernetes/blob/ba33abd5282acb9ee840d06a0e1fbf00466fbe4f/pkg/controller/history/controller_history_test.go#L515) is wrong - it should return the current object in the store, and instead it returns the updated value passed in.

How about I re-do this as an option on `testing.NewObjectTracker()`, so it's there for people who want to test optimistic locking, but we don't have to force it on all the existing tests?

**Comment by liggitt** [comment]
> Also I observe that the key part of your example is wrong - it should return the current object in the store, and instead it returns the updated value passed in.

Actually, when returning an error, I don't think the returned object matters a whole lot

> How about I re-do this as an option on testing.NewObjectTracker(), so it's there for people who want to test optimistic locking, but we don't have to force it on all the existing tests?

This starts down a rabbit hole I don't think we want the fake client to go. To make this actually work like the server, you'd also need to increment resource version when updating an object (mutating what is passed in), avoid incrementing resource version if the updated object is identical to the already existing object, etc.

My point about the reactor was that it lets you test specific responses (conflict response, etc).

If you want to test against a fully functional storage implementation, you can actually spin up a real etcd storage in a unit test and get 100% fidelity on resourceVersion handling, conflicts, etc. We do this in the tests for the rest handlers already:

https://github.com/kubernetes/kubernetes/blob/36877dafe40495cb43994464e2427355f99042c7/pkg/registry/apps/replicaset/storage/storage_test.go#L116-L142

**Comment by bboreham** [comment]
> Actually, when returning an error, I don't think the returned object matters a whole lot... it could (should) probably just return nil for the object there

The Kubernetes optimistic locking scheme requires both returning an error and returning the current value of the object.

**Comment by liggitt** [comment]
> The Kubernetes optimistic locking scheme requires both returning an error and returning the current value of the object.

not in the api... if you attempt a put of an object with a conflicting resourceVersion, you get a status error back, not the current object

**Comment by bboreham** [comment]
I apologise.  I have no idea where I got that idea from: all the references I just checked say the right thing to do after a conflict is to GET the current object.  And the code I was working on does that.

Thank you for your attention.

**Pull request closed without merging**
