### PR TITLE
Remove spaces from kubectl describe hpa

### PR DESCRIPTION
**Pull request by shiywang**
Fixes comment left here: https://github.com/kubernetes/kubernetes/pull/36033#discussion_r108020701

@kubernetes/sig-cli-pr-reviews  @DirectXMan12 

```release-note
remove spaces from kubectl describe hpa
```

### CODE REVIEW

**Comment by shiywang** [comment]
@DirectXMan12 @smarterclayton ptal, thanks

**Comment by DirectXMan12** [comment]
First of all, please give a more detailed description in the PR body.

Second of all, why?  What is the motivation for this PR?

**Comment by shiywang** [comment]
@DirectXMan12 thanks, release-note added and tittle changed, PTAL

**Comment by shiywang** [comment]
ping @smarterclayton for approval

**Review by droot — APPROVED** [review]
/lgtm

**Review by juanvallejo — APPROVED** [review]

**Comment by shiywang** [comment]
@liggitt mind aprove it ?

**Pull request merged**
