### PR TITLE
Fix some errors in the e2e doc and make it more consistent

### PR DESCRIPTION
**Pull request by asalkeld**
- "--tests" is not a valid argument
- use --ginko-skip to exclude (not focus)
- add "--check_node_count=false" to test against local cluster
- always use "--" for long args (there was a mix of "-" and "--" and it was a bit confusing)

### CODE REVIEW

**Comment by dubstack** [comment]
@k8s-bot please e2e test this #27524

**Comment by dubstack** [comment]
LGTM.
cc @timstclair

**Comment by timstclair** [comment]
@k8s-bot e2e test this #27524

**Comment by timstclair** [comment]
LGTM. Thanks!

**Comment by timstclair** [comment]
@k8s-bot e2e test this issue: #27524

**Pull request merged**
