### PR TITLE
Update typo in k8s.po in line 2170 

### PR DESCRIPTION
**Pull request by deveshgoyal1000**
Fixed typo mistake

What type of PR is this?
/kind bug
/kind documentation

What this PR does / why we need it:
Fix typo

### CODE REVIEW

**Comment by mpuckett159** [comment]
/ok-to-test

Thank you for the PR!

**Review by r0b2g1t — APPROVED** [review]

**Review by deveshgoyal1000 — COMMENTED** [review]
reviewed

**Review by mzaian — COMMENTED** [review]
/lgtm

**Pull request merged**
