### PR TITLE
Support completion for kubectl cp

### LINKED ISSUE #5: kubectl cp doesn't feature tab completion
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T19:15:41Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

It would be helpful if `kubectl cp` completed pod-names, like most other `kubectl` parameters do. This way, you wouldn't have to issue `kubectl get pod` and copy the pod name before copying a file from or to a pod.

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**: With this PR, kubectl cp supports completion. I tested this PR in bash and zsh.

```
$ kubectl cp kube-system/<tab>
kube-system/kube-state-metrics-769566fdfb-4v52s:   kube-system/kubernetes-dashboard-6b6ddbd46-t5bv9:  kube-system/prometheus-694594c45b-qk5lq:
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubectl#5

**Special notes for your reviewer**: @cblecker

**Release note**:

```release-note
`kubectl cp` supports completion.
```

### CODE REVIEW

**Comment by cblecker** [comment]
This looks fine to me.
/lgtm
/assign @deads2k 
/test pull-kubernetes-typecheck

**Comment by deads2k** [comment]
@eparis this sort of thing smells like you.  You done completions before?  I don't really know what it does.

**Comment by juanvallejo** [comment]
lgtm. From what I understand, you'll need to specify a namespace `foo/` before being able to tab-complete a pod's name right?

**Comment by superbrothers** [comment]
@juanvallejo No. This completion completes filedirs, `<namespace>/`, and **`<pod-name>:` of current namespace.**

```
$ kubectl get po
NAME                   READY     STATUS    RESTARTS   AGE
nginx-8586cf59-8qxtc   1/1       Running   0          12s
nginx-8586cf59-scp9r   1/1       Running   0          41s
nginx-8586cf59-w6rnv   1/1       Running   0          12s
$ kubectl cp <tab><tab>
api/                           .dockerized-kube-version-defs  nginx-8586cf59-8qxtc:
.bazelrc                       docs/                          nginx-8586cf59-scp9r:
build/                         examples/                      nginx-8586cf59-w6rnv:
BUILD.bazel                    .generated_files               _output/
CHANGELOG-1.10.md              .git/                          OWNERS
CHANGELOG-1.2.md               .gitattributes                 OWNERS_ALIASES
CHANGELOG-1.3.md               .github/                       pkg/
CHANGELOG-1.4.md               .gitignore                     plugin/
CHANGELOG-1.5.md               Godeps/                        README.md
CHANGELOG-1.6.md               hack/                          staging/
CHANGELOG-1.7.md               .kazelcfg.json                 SUPPORT.md
CHANGELOG-1.8.md               kube-public/                   test/
CHANGELOG-1.9.md               kube-system/                   third_party/
CHANGELOG.md                   labels.yaml                    _tmp/
cluster/                       LICENSE                        translations/
cmd/                           logo/                          vendor/
code-of-conduct.md             .make/                         WORKSPACE
CONTRIBUTING.md                Makefile
default/                       Makefile.generated_files
```

**Comment by cblecker** [comment]
@deads2k Any other concerns before approval?

**Comment by superbrothers** [comment]
ping @deads2k @eparis

**Comment by cblecker** [comment]
ping @deads2k @eparis

**Comment by deads2k** [comment]
it looks plausible.  I guess I'll trust it does good things.  In big clusters, the general approach seems questionable.

/approve

**Pull request merged**
