### PR TITLE
Fixing Kubernetes UI Graph Component's Legend Height Issue

### PR DESCRIPTION
**Pull request by imesh**
As I found Kubernetes UI graph component has set a fixed height for the legend section. As a result when more than three elements were present it was not fully displayed. Please see the below image:

issue

I fixed this by setting the legend height to auto, in the diff the change is not clear because the css is having all the content in one line:
svg.legend { height: auto; }

Fixed preview:
fix

### CODE REVIEW

**Comment by imesh** [comment]
I have now signed the CLA. Thanks!

**Comment by mikedanese** [comment]
This fixes #9347 so marking v1

**Comment by jlowdermilk** [comment]
lgtm

**Comment by imesh** [comment]
Thanks for accepting the PR! It's nice to contribute to Kubernetes.

**Comment by bcbroussard** [comment]
Thanks for the fix @imesh!

**Comment by preillyme** [comment]
Really appreciate the fix @imesh keep up the awesome work?

**Comment by imesh** [comment]
@bcbroussard, @preillyme It's a pleasure!

**Pull request merged**
