### PR TITLE
use availability_zone instead of availability (update godep for gophercloud)

### LINKED ISSUE #44032: storageclass cinder is ignoring availability zone
**Is this a BUG REPORT or FEATURE REQUEST?** BUG report

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-1+c0b74ebf3ce26e-dirty", GitCommit:"c0b74ebf3ce26e46b5397ffb5ce71cd02f951130", GitTreeState:"dirty", BuildDate:"2017-03-30T08:19:21Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): centos 7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I created new cinder storageclass, however it does ignore availability zone and it will provision volumes zone called nova (default)

yaml used to create cinder:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
provisioner: kubernetes.io/cinder
parameters:
  availability: zone-1
```

```
% openstack volume list
+--------------------------------------+-------------------------------------------------------------+-----------+------+-------------+
| ID                                   | Display Name                                                | Status    | Size | Attached to |
+--------------------------------------+-------------------------------------------------------------+-----------+------+-------------+
| d71f8af4-2e84-4908-a3e8-b5f64d0ed3aa | kubernetes-dynamic-pvc-810f0f8b-191b-11e7-9a54-fa163e26fe46 | error     |   12 |             |
+--------------------------------------+-------------------------------------------------------------+-----------+------+-------------+

% openstack volume show d71f8af4-2e84-4908-a3e8-b5f64d0ed3aa
+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                        | Value                                                                                                                                                                                   |
+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| attachments                  | []                                                                                                                                                                                      |
| availability_zone            | nova                                                                                                                                                                                    |
| bootable                     | false                                                                                                                                                                                   |
| consistencygroup_id          | None                                                                                                                                                                                    |
| created_at                   | 2017-04-04T09:56:43.000000                                                                                                                                                              |
| description                  | None                                                                                                                                                                                    |
| encrypted                    | False                                                                                                                                                                                   |
| id                           | d71f8af4-2e84-4908-a3e8-b5f64d0ed3aa                                                                                                                                                    |
| multiattach                  | False                                                                                                                                                                                   |
| name                         | kubernetes-dynamic-pvc-810f0f8b-191b-11e7-9a54-fa163e26fe46                                                                                                                             |
| os-vol-tenant-attr:tenant_id | b23efb65b1d44b5abd561511f40c565d                                                                                                                                                        |
| properties                   | kubernetes.io/created-for/pv/name='pvc-810f0f8b-191b-11e7-9a54-fa163e26fe46', kubernetes.io/created-for/pvc/name='storage-es-data-0', kubernetes.io/created-for/pvc/namespace='default' |
| replication_status           | disabled                                                                                                                                                                                |
| size                         | 12                                                                                                                                                                                      |
| snapshot_id                  | None                                                                                                                                                                                    |
| source_volid                 | None                                                                                                                                                                                    |
| status                       | error                                                                                                                                                                                   |
| type                         | None                                                                                                                                                                                    |
| updated_at                   | 2017-04-04T09:56:43.000000                                                                                                                                                              |
| user_id                      | 56ebdadedcbd34ccac211665a0bf5d78060040f1ff05fb5e896d77e7f882650d                                                                                                                        |
+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

I added manual print here https://github.com/kubernetes/kubernetes/blob/v1.6.0/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L145

It prints out:
```
{"log":"I0404 11:08:15.852302       1 openstack_volumes.go:145] Createvolume availability: zone-1\n","stream":"stderr","time":"2017-04-04T11:08:15.852382116Z"
```

I tried to remove that newline from that string, but still it is creating that to nova availability zone. For me this looks like gophercloud volumes.CreateOpts{ is not working as should in createvolume function https://github.com/kubernetes/kubernetes/blob/v1.6.0/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L144-L171 
**What you expected to happen**:
I except that if I define availability, like docs says it should also use that parameter when provisioning volume.

**How to reproduce it** (as minimally and precisely as possible):

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
provisioner: kubernetes.io/cinder
parameters:
  availability: zone-1
```

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.2.2_2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: zone-1
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 12Gi
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by zetaab**
**What this PR does / why we need it**: there is typo in json variable name

**Which issue this PR fixes**: fixes #44032

**Special notes for your reviewer**:our openstack environment region name is not nova, so I tested this and it works now

All cinder blockstorages are using variable name availability_zone instead of availability. Docs: 

v3:
https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-a-volume-detail#create-a-volume

v2:
https://developer.openstack.org/api-ref/block-storage/v2/index.html?expanded=create-volume-detail#create-volume

I could not find v1 documentation anymore from openstack pages. However, https://developer.rackspace.com/docs/cloud-block-storage/v1/api-reference/cbs-volumes-operations/#create-a-volume documentation says also availability_zone is the correct one. 

Like mentioned in https://github.com/kubernetes/kubernetes/issues/44032#issuecomment-291488494 openstack CLI is using availability_zone

### CODE REVIEW

**Comment by cblecker** [comment]
Hi @zetaab,
We can't directly modify a vendor, as they're versioned.

It looks like this was added to gophercloud here: https://github.com/gophercloud/gophercloud/commit/b06120d13e262ceaf890ef38ee30898813696af0

We could update the godep to pull this change in. Information on updating godeps is here: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

**Comment by zetaab** [comment]
is that correctly updated deps?

**Comment by cblecker** [comment]
You actually need to use the Godep tool to do this kind of update, as it tracks when the updates were done and the hashes of those updates.

Directions and details here: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

**Comment by zetaab** [comment]
I tried to follow those instructions but it does not work, maybe someone who have done this before can do it?

```
 kubernetes [fixzone2●] % godep restore
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics/install) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apimachinery/announced) not found
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics/v1alpha1) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics/install) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apimachinery/announced) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics/v1alpha1) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset) restored, but was unable to load it with error:
	Package (k8s.io/client-go/discovery) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/fake) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/runtime) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/scheme) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/typed/metrics/v1alpha1) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/typed/metrics/v1alpha1/fake) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/custom_metrics) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/api/meta) not found
godep: Dep (k8s.io/metrics/pkg/client/custom_metrics/fake) restored, but was unable to load it with error:
	Package (k8s.io/apimachinery/pkg/labels) not found
godep: Error checking some deps.
```

```
kubernetes [fixzone2●●] % ./hack/godep-save.sh
godep: Package (google.golang.org/genproto/googleapis/bigtable/admin/v2) not found
!!! Error in ./hack/godep-save.sh:37
  Error in ./hack/godep-save.sh:37. 'GOPATH=${GOPATH}:${KUBE_ROOT}/staging godep save "${REQUIRED_BINS[@]}"' exited with status 1
Call stack:
  1: ./hack/godep-save.sh:37 main(...)
Exiting with status 1
 kubernetes [fixzone2●●] %
```

**Comment by zetaab** [comment]
@cblecker any ideas?

**Comment by cblecker** [comment]
Oh hmm.. try using `hack/godep-restore.sh` to restore the deps instead of invoking godep restore directly. I'll review and update those docs as they don't include that.

**Comment by cblecker** [comment]
I just tried [this](https://github.com/cblecker/community/blob/2349b86fb1d78e2b10f719b06e7f1cef303ecdad/contributors/devel/godep.md#using-godep) locally, and it seems to have worked. If you wouldn't mind testing on your environment to see if that allows you to update the godep, that would be great.

**Comment by zetaab** [comment]
@cblecker your instructions works pretty well, if those files are now OK :)

The only thing which did not work is verify godeps

% ./hack/verify-godeps.sh
Checking for 'Godeps/' changes against '/master'
fatal: Not a valid object name /master

i tried also execute godep update and rerun it, but it did not help

**Comment by cblecker** [comment]
Ah! Are you working off a git branch, or just a clone of master?

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by zetaab** [comment]
I was working in that fixzone2 branch

**Comment by zetaab** [comment]
@k8s-bot verify test this

**Comment by zetaab** [comment]
@cblecker do you have idea how to fix that one failing job? 

I cannot execute that failing command 

```
(kubernetes) kubernetes [fixzone2] % ./hack/verify-staging-godeps.sh
Checking whether godeps are restored
  jq not found. Please install.

Execute script hack/godep-restore.sh to download dependencies.
(kubernetes) kubernetes [fixzone2] % ./hack/godep-restore.sh
Starting to download all kubernetes godeps. This takes a while
Download finished
(kubernetes) kubernetes [fixzone2] % ./hack/verify-staging-godeps.sh
Checking whether godeps are restored
  jq not found. Please install.

Execute script hack/godep-restore.sh to download dependencies.
```

**Comment by zetaab** [comment]
@k8s-bot bazel test this

**Comment by zetaab** [comment]
@k8s-bot verify test this

**Comment by zetaab** [comment]
@cblecker thanks for helping 👍

**Comment by cblecker** [comment]
@zetaab No problem! Glad to help.

As the meaningful code change is for the openstack provider, do you want to have a look @anguslees?

**Comment by zetaab** [comment]
ping @dchen1107 @anguslees could you check this please

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs 

@idvoretskyi Can you add the sig/openstack label please?

**Comment by cblecker** [comment]
@dchen1107 @zetaab Does this need a release note? Only piece that is blocking merge here.

**Comment by zetab** [comment]
well, imo someone (who have access) could add release-note-none or release-note and remove release-note-label-needed and do-not-merge? This is basically godep update for gophercloud, and if i check previous changelog items, some of these are there. So if we just add release-note its fine for me(its added to changelog with that i think?).

**Comment by zetaab** [comment]
well, imo someone (who have access) could add release-note-none or release-note and remove release-note-label-needed and do-not-merge? This is basically godep update for gophercloud, and if i check previous changelog items, some of these are there. So if we just add release-note its fine for me(its added to changelog with that i think?).

**Comment by cblecker** [comment]
Release notes are needed when there is a breaking change, or a notable change in functionality (for better or worse). In this case, I this looks like just a bug fix.
/release-note-none

Will still need @dchen1107 to remove the `do-not-merge`

**Comment by zetaab** [comment]
@k8s-bot non-cri e2e test this

**Comment by pospispa** [comment]
@k8s-bot non-cri e2e test this

**Comment by idvoretskyi** [comment]
cc  @kubernetes/sig-openstack-bugs

**Pull request merged**
