### PR TITLE
Make kubernetes-src.tar.gz contain source code again

### LINKED ISSUE #36403: kubernetes-src.tar.gz contains no source code
Due to #30787, we no longer copy the source code into `${LOCAL_OUTPUT_ROOT}`. [We bundle up `${LOCAL_OUTPUT_ROOT}` to produce the `kubernetes-src.tar.gz` file](https://github.com/kubernetes/kubernetes/blob/2dea8a8f8f7f8ea44284c937499b5a946491add5/build-tools/lib/release.sh#L98-L102), however.

Confirmed that the `kubernetes-src.tar.gz` file now contains nothing useful:
```console
$ curl -s https://storage.googleapis.com/kubernetes-release/release/v1.5.0-beta.0/kubernetes-src.tar.gz | tar tz
vf -
drwxr-x--- saadali/eng       0 2016-11-05 18:50 ./
-rw-r----- saadali/eng    2819 2016-11-05 18:50 ./localtime
-rw------- saadali/eng      32 2016-11-05 18:50 ./rsyncd.password
-rw-r----- saadali/eng    1502 2016-11-05 18:50 ./Dockerfile
-rwxr-x--- saadali/eng    2286 2016-11-05 18:50 ./rsyncd.sh
```

cc @saad-ali @jbeda @zmerlynn

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: This PR fixes `kubernetes-src.tar.gz` by reviving the logic for `kube-source.tar.gz` from before #30787.

**Which issue this PR fixes**: fixes #36403

@saad-ali @jbeda @zmerlynn

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36407)

### CODE REVIEW

**Comment by ixdy** [comment]
Since I referenced it, the old logic I mostly copied:
https://github.com/jbeda/kubernetes/blob/06b1a9636dbc1d30b0d5f7c6a1f59194800bf3e1/build/common.sh#L452-L460
https://github.com/jbeda/kubernetes/blob/06b1a9636dbc1d30b0d5f7c6a1f59194800bf3e1/build/common.sh#L467

**Comment by zmerlynn** [comment]
@k8s-bot node e2e test this

**Comment by ixdy** [comment]
Thanks @zmerlynn . I don't think @jbeda will have a chance to look before the end of this week.

**Comment by ixdy** [comment]
FYI this appears to be doing the right thing:
```console
$ curl -s https://storage.googleapis.com/kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.6.0-alpha.0.184+db393f07f35044/kubernetes-src.tar.gz | tar tzvf - | wc -l
   13979
```

**Comment by saad-ali** [comment]
Readding LGTM. Also ok for post-code freeze merge since this fixes a build issue.

**Comment by ixdy** [comment]
I'm still working on something, let's not merge this yet.

**Comment by saad-ali** [comment]
> I'm still working on something, let's not merge this yet.

Ack

**Comment by ixdy** [comment]
wtf SQ!

**Comment by jbeda** [comment]
I'm sorry I'm behind the ball here, but is there a reason not to use `git archive` here?  I haven't used it before but it looks like exactly what we'd want.  It looks to respect `.gitignore` and so we wouldn't need the funky find pattern.

**Comment by ixdy** [comment]
If I'd known about `git archive` I might've used it. :)

**Pull request merged**
