### PR TITLE
make kubeadm return error if api-server is not accessible

### PR DESCRIPTION
**Pull request by bg-chun**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When api-server is not accessible, Kubeadm keep trying to publish new bootstrap token and stuck there.
```bash
# kubeadm token create --print-join-command --v=5
I0229 05:44:03.289883 2080320 token.go:122] [token] validating mixed arguments
I0229 05:44:03.289939 2080320 token.go:131] [token] getting Clientsets from kubeconfig file
I0229 05:44:03.289964 2080320 cmdutil.go:81] Using kubeconfig file: /root/.kube/config
I0229 05:44:03.291276 2080320 token.go:246] [token] loading configurations
I0229 05:44:03.291649 2080320 interface.go:432] Looking for default routes with IPv4 addresses
I0229 05:44:03.291661 2080320 interface.go:437] Default route transits interface "enp25s0f3"
I0229 05:44:03.292364 2080320 interface.go:209] Interface enp25s0f3 is up
I0229 05:44:03.292420 2080320 interface.go:257] Interface "enp25s0f3" has 2 addresses :[10.0.0.236/24 fe80::3eec:efff:fe5e:f835/64].
I0229 05:44:03.292447 2080320 interface.go:224] Checking addr  10.0.0.236/24.
I0229 05:44:03.292460 2080320 interface.go:231] IP found 10.0.0.236
I0229 05:44:03.292471 2080320 interface.go:263] Found valid IPv4 address 10.0.0.236 for interface "enp25s0f3".
I0229 05:44:03.292479 2080320 interface.go:443] Found active IP 10.0.0.236
I0229 05:44:03.292503 2080320 kubelet.go:218] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
I0229 05:44:03.301420 2080320 token.go:253] [token] creating token
timed out waiting for the condition
```

This is because it has not well-defined error handling logic.
This PR is trying to add error handling logic if api-server is not accessible.

#### Which issue(s) this PR fixes:
Fixes #

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
hello, looks like the whole function needs a refactor
UpdateOrCreateTokens

here is some pseudo code of what we should do:
```
for _, token := range tokens {
  var lastError error
  err = wait.PollUntilContextTimeout(
  ....

  // 1. make API call to get the secret
  // 2. if the secret exists and failIfExists is true exit the poll check using apierrors.IsAlreadyExists(), for any other error retry the poll.
  // 3. don't use  CreateOrUpdateSecret, the function already has poll inside, just call Create()...

  ) // poll end
}
```

does that make sense to you?

we are close to code freeze for 1.30, so might not be a good idea to merge such a change, but you can try updating it before the 6th of March.

**Comment by bg-chun** [comment]
> hello, looks like the whole function needs a refactor UpdateOrCreateTokens
> 
> here is some pseudo code of what we should do:
> 
> ```
> for _, token := range tokens {
>   var lastError error
>   err = wait.PollUntilContextTimeout(
>   ....
> 
>   // 1. make API call to get the secret
>   // 2. if the secret exists and failIfExists is true exit the poll check using apierrors.IsAlreadyExists(), for any other error retry the poll.
>   // 3. don't use  CreateOrUpdateSecret, the function already has poll inside, just call Create()...
> 
>   ) // poll end
> }
> ```
> 
> does that make sense to you?
> 
> we are close to code freeze for 1.30, so might not be a good idea to merge such a change, but you can try updating it before the 6th of March.

+2 sounds good.
Do you have preference for timeout duration?

**Comment by neolit123** [comment]
> +2 sounds good.
Do you have preference for timeout duration?

there is already a PollUntilContextTimeout in there. it has the correct interval/timeout.

**Review by neolit123 — COMMENTED** [review]
do you still have plans to update this @bg-chun ?

**Review by neolit123 — COMMENTED** [review]
/close
PR is inactive

**Pull request closed without merging**
