### PR TITLE
Revert "Bump cadvisor godep"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#13191

### CODE REVIEW

**Comment by piosz** [comment]
Jenkins is broken and this change may be the cause.

cc @jimmidyson @vishh @yujuhong

**Comment by jimmidyson** [comment]
@piosz Where can I see the Jenkins logs for the failed build? It passed on the original merge - https://github.com/kubernetes/kubernetes/pull/13191

**Comment by wojtek-t** [comment]
@jimmidyson 
 Our e2e tests are constantly failing since ~ your PR was merged. However, unfortunately this wasn't the only PR merged around that time, so the problem might be unrelated. We are currently reverting possible suspects and will be re-reverting them once our tests will get back to green

**Comment by jimmidyson** [comment]
@wojtek-t I can't see the Jenkins logs (which would be great for contributors to see - public Jenkins for an OSS project would be great...). If you can share the logs then I can see if I can help with resolution - at least see if it's something my PR could have impacted upon. Might speed up resolution? Happy to help.

**Comment by wojtek-t** [comment]
Our team is still working on making our Jenkins to be public, but this is still not done.
It's difficult to explicitly show logs that we can blame, but the symptoms are that at some point some pods just doesn't start. I'm looking into logs and didn't see anything suspicious yet.
(In fact we were initially suspecting #13186, but reverting it locally doesn't help).

The real problem is that none of the PRs merged around that time seem suspicious.

**Comment by wojtek-t** [comment]
BTW - my personal feeling is that it's NOT related to your PR, but we're a bit paranoid now :)

**Comment by jimmidyson** [comment]
My PR has no impact on the starting of pods, all to do with exposing metrics, nothing more - unless I'm missing something :)

**Comment by piosz** [comment]
@jimmidyson you are probably right, the only problem with your PR is that it was merged in at the wrong time;) Sorry for the inconvenience. Once Jenkins will be fixed I'll try to re-revert you change.

**Comment by jimmidyson** [comment]
@piosz No worries! Hope you get it sorted soon.

**Comment by jimmidyson** [comment]
@piosz Any news on this? Anything I can do to help get this back in?

**Comment by piosz** [comment]
Thanks for you involvement @jimmidyson . There is nothing to do from your side.

@bprashanth since you are oncall could you please re-revert this change carefully?

**Pull request merged**
