### PR TITLE
Revert v1beta1 PodDisruptionBudget selector patchStrategy to pre-1.21 behavior

### LINKED ISSUE #108137: policy/v1beta1 PodDisruptionBudget selector patchStrategy changed unexpectedly in 1.21 upgrade
### What happened?

PDB was upgraded to v1 in 1.21. Despite the changelog saying that the behavior of the v1beta1 implementation should have stayed the same, it appears that the `patchStrategy` for the `selector` field was set to `replace`. I believe this is the change in question: https://github.com/kubernetes/kubernetes/pull/99290/files#diff-d4e188b2d9ba60f8c95c9a44c54d1e470c5796eccc4f28eccd446e6ed77f32b5R41

https://github.com/kubernetes/kubernetes/blob/f7ad5e91417dc4ac04bce1d1b15e11e6fed619d4/staging/src/k8s.io/api/policy/v1beta1/types.go#L41

When running `kubectl patch` with a starting config that had a `selector` with both a `matchExpressions` key and a `matchLabels` key, and a patch that had a `selector` with just a `matchLabels` key, the behavior between 1.20 and 1.21 differs. What we get is the `matchExpressions` key gets deleted, rather than merged with the patch's `matchLabels` key to make one unified selector.

```console
% kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
  namespace: my-ns
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app: my-app
```

### What did you expect to happen?

In 1.20, the behavior we'd get is thus, which is desirable for us because it lets us inject a base assumption about our PDBs into everything we do:

```console
% kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
  namespace: my-ns
spec:
  maxUnavailable: 10%
  selector:
    matchExpressions:
    - key: support
      operator: NotIn
      values:
      - "true"
    matchLabels:
      app: my-app
```

### How can we reproduce it (as minimally and precisely as possible)?

This is my repro case:

`vendor_config.json`

```json
{
  "apiVersion": "policy/v1beta1",
  "kind": "PodDisruptionBudget",
  "metadata": {
    "name": "my-pdb",
    "namespace": "my-ns"
  },
  "spec": {
    "maxUnavailable": "25%",
    "selector": {
      "matchLabels": {
        "app": "my-app"
      },
      "matchExpressions": [
        {
          "key": "support",
          "operator": "NotIn",
          "values": ["true"]
        }
      ]
    }
  }
}
```

`user_config.json`:

```json
{
  "apiVersion": "policy/v1beta1",
  "kind": "PodDisruptionBudget",
  "metadata": {
    "name": "my-pdb",
    "namespace": "my-ns"
  },
  "spec": {
    "maxUnavailable": "10%",
    "selector": {
      "matchLabels": {
        "app": "my-app"
      }
    }
  }
}
```

Compare by using the `kubectl patch` command from earlier in this report: `kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"`

### Anything else we need to know?

I also brought this up in Slack: https://kubernetes.slack.com/archives/C2GL57FJ4/p1644947167394309

I don't think we want to switch to using just `--type merge` for PDBs, because that wouldn't solve issues where our users want to use `matchExpressions` without having to re-specify the `matchExpressions` from our base. Putting aside the fact that changing the behavior of the v1beta1 implementation was probably not intentional, it also seems undesirable to change how selectors work in general. I don't know how widely scoped this change will be across various resource types, too, so we're starting down quite a bit of nasty discovery time.

### Kubernetes version

<details>
This is the version I used to demonstrate my repro case, but I confirmed that this occurs even in kubectl v1.21.0.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

For my "happy" repro case, this is what the version output looks like:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS (the hard way)
</details>

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Reverts strategic merge patch behavior for the `selector` field in `v1beta1` PodDisruptionBudget objects to match pre-1.21 behavior.

#### Which issue(s) this PR fixes:
Fixes #108137

#### Does this PR introduce a user-facing change?
```release-note
Fixes a regression in 1.21 in v1beta1 PodDisruptionBudget handling of "strategic merge patch"-type API requests for the `selector` field. Prior to 1.21, these requests would merge `matchLabels` content and replace `matchExpressions` content. In 1.21, patch requests touching the `selector` field started replacing the entire selector. This is consistent with server-side apply and the v1 PodDisruptionBudget behavior, but should not have been changed for v1beta1.
```

/cc @mortent 
/cc @jpbetz

### CODE REVIEW

**Review by 2rs2ts — APPROVED** [review]
Thank you for the quick turnaround on this!

**Comment by liggitt** [comment]
added an integration test exercising all strategic merge patch, merge patch, and apply patch types against v1 and v1beta1. Verified the test passes against this PR, passes against 1.20, and fails against 1.21-master.

**Comment by jpbetz** [comment]
/lgtm

Huge thanks for fixing.

**Comment by 2rs2ts** [comment]
Will this be backported to 1.21-23?

**Pull request merged**
