### PR TITLE
Fix code generators-- make scheme building composable

### PR DESCRIPTION
**Pull request by thockin**
Rebase @lavalamp's #25526

### CODE REVIEW

**Comment by thockin** [comment]
@wojtek-t @lavalamp @smarterclayton

**Comment by thockin** [comment]
Alas...

```
hack/build-go.sh pkg/api/meta/metatypes
Go version: go version go1.6.1 linux/amd64
+++ [0523 20:58:50] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0523 20:58:50] Building go targets for linux/amd64:
    pkg/api/meta/metatypes
can't load package: import cycle not allowed
package k8s.io/kubernetes/pkg/api/meta/metatypes
	imports k8s.io/kubernetes/pkg/conversion
	imports k8s.io/kubernetes/pkg/runtime
	imports k8s.io/kubernetes/pkg/api/meta/metatypes
import cycle not allowed
```

This is still unusable to generate the files that are currently orphaned.

**Comment by thockin** [comment]
In PR #25978 I have added a flag to deepcopy-gen to optionally generate init() funcs.  It seems to work, but there's a separate issue with it trying to call generated functions in the `time` pkg (stdlib).

```
pkg/api/unversioned/zz_generated.deep_copy.go:296: undefined: time.DeepCopy_time_Time
```

I could simply check the type's package name and see if it has any "/" in it.  That seems to work...

**Comment by lavalamp** [comment]
@thockin we should *not* be generating deep copies for stdlib time-- that's
what the unversioned.Time type is for. The recursive descent should stop
there.

**Comment by smarterclayton** [comment]
Should be fixed in the issue I opened today.

On May 24, 2016, at 6:22 PM, Daniel Smith <notifications@github.com> wrote:

@thockin we should *not* be generating deep copies for stdlib time-- that's
what the unversioned.Time type is for. The recursive descent should stop
there.

On Mon, May 23, 2016 at 11:13 PM, Tim Hockin <notifications@github.com>
wrote:

> In PR #25978 <https://github.com/kubernetes/kubernetes/pull/25978> I have
> added a flag to deepcopy-gen to optionally generate init() funcs. It seems
> to work, but there's a separate issue with it trying to call generated
> functions in the time pkg (stdlib).
>
> pkg/api/unversioned/zz_generated.deep_copy.go:296: undefined:
time.DeepCopy_time_Time
>
> I could simply check the type's package name and see if it has any "/" in
> it. That seems to work...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/pull/26133#issuecomment-221175990>
>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/26133#issuecomment-221419794>

**Comment by thockin** [comment]
@lavalamp This PR + Clayton's (merged) + mine (based on this one, needs to rebase on Clayton's) are rather tangled.  What do you think about this:

I will un-base mine from this (yours).
I will rebase mine on Clayton's and subsume his changes into mine.
I will prove that mine all works.
Then we can re-add this PR.

There are just too many moving parts right now.  Thoughts?

**Comment by lavalamp** [comment]
Sure. Do what you need to, I'm going to be distracted by merge queue for at
least another week.

**Pull request closed without merging**
