### PR TITLE
kubelet/rkt: Fix rkt status parsing, and resource requirement convert…

### PR DESCRIPTION
**Pull request by yifan-gu**
…ion.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by yifan-gu** [comment]
Should fix #7708

**Comment by dchen1107** [comment]
Shippable is really flaky, I kicked out it again. Travis is tooooooooo slow!

**Comment by yifan-gu** [comment]
@dchen1107 Travis is taking 1hr for one commit! And there are more than 200 PRs in the queue.

**Comment by dchen1107** [comment]
I know! We need to do something to speed up travis. For your pr, once shippable is green, I can merge it. :)

**Comment by yifan-gu** [comment]
I rebased master, hope shippable can be green, it's impossible to wait for travis these days...

**Comment by yujuhong** [comment]
LGTM. Shippable is green. Merging :)

**Pull request merged**
