### PR TITLE
Automated cherry pick of #45892

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #45892 on release-1.6.

#45892: Update fluentd-gcp image version

### CODE REVIEW

**Comment by crassirostris** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crassirostris** [comment]
@enisoc Sorry! I found another issue in the image, which allowed e2e tests to pass, but was introducing performance regression

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (159/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:4051)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGTLh-000Uf1-QW
	for dev@imwiz.com; Thu, 01 Jun 2017 10:53:27 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=TpqS2BFlmxogxCp0JC0Nl3NMCB8=; b=jYjFuPOhPxCI6k7E
	GZxXwcLlkHcCtd/RLCl0E130vDl6i5T/jrg4FW9/vcUSs9LSN2GkxHgUj/YAaCtW
	6Kul7keZi9bB5iff+1NzzqpBHQ/oryYFS+yDXf6CwO/5QoYNgHcURnO2IlDNZ07n
	Yur7uiLEog/gr/QaHi2ZFE7axN4=
Received: by filter1083p1mdw1.sendgrid.net with SMTP id filter1083p1mdw1-25134-5930467A-24
        2017-06-01 16:53:14.831557495 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 95u06f19QeKm8uy1nTQtAQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 16:53:14.778 +0000 (UTC)
Date: Thu, 01 Jun 2017 09:53:14 -0700

**Pull request closed without merging**
