### PR TITLE
remove windows service not used global variable

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <1015105054@qq.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
variable `service` in `pkg/windows/service/service.go` is not used, so we  can remove it
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gy95** [comment]
kindly ping @dchen1107 @thockin PTAL 😄

**Review by wzshiming — APPROVED** [review]

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by gy95** [comment]
ping @wzshiming @thockin  need release-note-label :)

**Pull request merged**
