### PR TITLE
Job: Use generic sets to avoid unnecessary string casts in valiations

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I replaced older sets with the generic sets to avoid unnecessary string casts in the validations.

I understand that it isn't necessary to replace deprecated sets with generic sets since there is no plan to remove deprecated sets, but I think that this replacement would be valuable since we can avoid unnecessary casting.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
This seems to fall under an unnecessary change. Do you have a reason why you need to implement this?

code looks good but I doubt we would see a performance improvement.

**Comment by tenzen-y** [comment]
> I understand that it isn't necessary to replace deprecated sets with generic sets since there is no plan to remove deprecated sets, but I think that this replacement would be valuable since we can avoid unnecessary casting.

@kannon92 As I described in PR descriptions, I think that avoiding casts would be valuable.
Do you think this reason is insufficient for this replacement?

**Comment by kannon92** [comment]
> @kannon92 As I described in PR descriptions, I think that avoiding casts would be valuable. Do you think this reason is insufficient for this replacement?

I think its probably fine.. I'm thinking of the ptr change and that using generics to clean up code is probably a good change.

/lgtm
/assign @thockin @liggitt

**Pull request merged**
