### PR TITLE
Let COS docker validation node test against gci-next-canary

### LINKED ISSUE #47134: COS Docker validation node test needs to run against gci-next-canary
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): no

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): docker validation

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

COS plan to use family gci-next-canary in container-vm-image-staging for future Docker upgradation and validation. The properties file under test/e2e_node/jenkins/docker_validation/cos-docker-validation.properties should be changed for this.

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I already have a PR. I just need to file a issue for it due to the new policy.

### PR DESCRIPTION
**Pull request by kewu1992**
**What this PR does / why we need it**:
This is for COS docker validation node test. We plan to use family gci-next-canary in container-vm-image-staging for future Docker upgration and validation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47134

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kewu1992** [comment]
@Random-Liu Please review.

**Comment by Random-Liu** [comment]
@kubernetes/kubernetes-release-managers This is pure test infra change for docker validation test. It doesn't touch any production code, and the docker validation test suite is not blocking/critical suite.

Is it ok to merge this?

/lgtm
/approve

**Comment by Random-Liu** [comment]
@k8s-bot ok to test

**Comment by Random-Liu** [comment]
@kewu1992 You need to associated a issue this the PR. That is the new policy.

**Comment by Random-Liu** [comment]
Offline communicated with the release manager @dchen1107. It's ok to merge this test only change to 1.7.

**Comment by Random-Liu** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
