### PR TITLE
Expanding "all" falls back to discovered resources

### PR DESCRIPTION
**Pull request by fabianofranz**
Follow-up of https://github.com/kubernetes/kubernetes/pull/41354

Fixes https://github.com/kubernetes/kubernetes/issues/41353

When expanding `kubectl get all`, discover all user resources on the server if none of the ones wanted by the client is available. 

This allows `kubectl get all` to be successfully used against servers that do not have defined any of these hardcoded [UserResources](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/shortcut_restmapper.go#L106-L115) resources.

Makes `kubectl` compatible to be used with the [service-catalog](https://github.com/kubernetes-incubator/service-catalog) API server.

**Release note**:

```release-note
NONE
```

@k82cn @liggitt @pmorie @kubernetes/sig-cli-pr-reviews

### CODE REVIEW

**Comment by liggitt** [comment]
how do we follow the guidelines for which resources are included in the `all` alias if we're falling back to discovered resources?

**Comment by fabianofranz** [comment]
> how do we follow the guidelines for which resources are included in the all alias if we're falling back to discovered resources?

We only fallback in case none of the wanted resources is available on the server. 

But if we do fallback (which is what happens in the service catalog API), I'm afraid we can't enforce the guidelines other than checking namespaced (maybe admin-level resources?). There isn't anything in the API that denotes a resource like secret or pvc, for example, is potentially unrecoverable.

**Comment by fabianofranz** [comment]
Option being (in case we don't do any API change) to have another hardcoded [UserResources](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/shortcut_restmapper.go#L106-L115) list for the meaning of "all" in the svc catalog API?

**Comment by pwittrock** [comment]
Is this for 1.6?

**Comment by fabianofranz** [comment]
> Is this for 1.6?

I don't think so, @pmorie confirm?

**Comment by deads2k** [comment]
I remember talking with @smarterclayton and @lavalamp about including an explicit opt-in for having a resource included in `all`.  The opt-in via discovery would allow us to collapse onto a single set of behavior for all servers, including the kube one.

**Comment by fabianofranz** [comment]
@deads2k Are you referring to an opt-in on the client, or something the cluster admin configures so the "all" concept would move server-side? On discovery we still check the server resources to make sure what we're considering as "all" on the client exists as server-side resources.

**Comment by deads2k** [comment]
> @deads2k Are you referring to an opt-in on the client, or something the cluster admin configures so the "all" concept would move server-side? On discovery we still check the server resources to make sure what we're considering as "all" on the client exists as server-side resources.

Opt-in on the server side, so that the server owns the concept of what is included in "all".

**Comment by fabianofranz** [comment]
> Opt-in on the server side, so that the server owns the concept of what is included in "all".

If we move it server-side, @juanvallejo and @pwittrock [have a proposal](https://github.com/kubernetes-incubator/service-catalog/pull/386) that makes use of the `+k8s:openapi-gen=x-kubernetes-display-all:true` tag to make a given resource part of the definition of "all". This will require taking that information from the swagger schema but I think it's a good approach.

However until OpenAPI definitions are available on both APIs and we have the aggregator working, I'd like to get `kubectl get all` not failing when used against both kube and the service-catalog APIs. Since our current approach is hardcoded `UserResources` and I said that every user resource is checked on server and discarded if not present, why don't we just add the service-catalog resources to the list we currently have? I'd repurpose this PR then. 

WDYT @liggitt? @pmorie would "bindings" and "instances" be the resources that are part of "all"? E.g.

```
var UserResources = []schema.GroupResource{
	{Group: "", Resource: "pods"},
	{Group: "", Resource: "replicationcontrollers"},
	{Group: "", Resource: "services"},
	{Group: "apps", Resource: "statefulsets"},
	{Group: "autoscaling", Resource: "horizontalpodautoscalers"},
	{Group: "batch", Resource: "jobs"},
	{Group: "extensions", Resource: "deployments"},
	{Group: "extensions", Resource: "replicasets"},
	{Group: "servicecatalog.k8s.io", Resource: "bindings"},
	{Group: "servicecatalog.k8s.io", Resource: "instances"},
}
```

**Comment by deads2k** [comment]
> If we move it server-side, @juanvallejo and @pwittrock have a proposal that makes use of the +k8s:openapi-gen=x-kubernetes-display-all:true tag to make a given resource part of the definition of "all".

Information that is needed to build a `RESTMapper` has always been the job of our discovery endpoints.  I don't think we should pursue a path that requires swagger to generate a proper `RESTMapper`.

In addition, simply defaulting a different assumption that doesn't work in general doesn't seem like a great improvement.  It seems like it would just make people angry as it "breaks" when we try to fix it.

**Comment by liggitt** [comment]
> why don't we just add the service-catalog resources to the list we currently have?

including resources that don't exist in-tree in a hardcoded alias in-tree sets a bad precedent, imo

**Comment by fabianofranz** [comment]
> I remember talking with @smarterclayton and @lavalamp about including an explicit opt-in for having a resource included in all

> Information that is needed to build a RESTMapper has always been the job of our discovery endpoints. I don't think we should pursue a path that requires swagger to generate a proper RESTMapper.

@deads2k Something similar to `Namespaced`? Or more generic like maybe annotations in the resource kind?

**Comment by deads2k** [comment]
> @deads2k Something similar to Namespaced? Or more generic like maybe annotations in the resource kind?

Probably something like a list of "these are the groups I'm a part of", where "all" is an option.  Then we make "all" un-special in kubectl.  That would allow someone to show their "deployment-y things" as an option too.

**Comment by pwittrock** [comment]
@monopole Can you review this when you are available?

**Comment by fabianofranz** [comment]
> Probably something like a list of "these are the groups I'm a part of", where "all" is an option. Then we make "all" un-special in kubectl. That would allow someone to show their "deployment-y things" as an option too.

The API part of it is in https://github.com/kubernetes/kubernetes/pull/43338. Once that gets merged I'll update this PR to have `kubectl` respect the new `categories` field that moves 'all' to the server side.

**Comment by monopole** [comment]
Still waiting on #43338, right?

**Comment by fabianofranz** [comment]
@monopole yep.

**Pull request closed without merging**
