### PR TITLE
Revert "Revert "syncNetworkUtil in kubelet and fix loadbalancerSourceRange on GCE

### PR DESCRIPTION
**Pull request by freehan**
Reverts kubernetes/kubernetes#30729

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30814)

### CODE REVIEW

**Comment by freehan** [comment]
just bump into another problem. Will ping you when this is ready

**Comment by thockin** [comment]
@fabioy for cherry pick consideration

**Comment by freehan** [comment]
changing KUBE-XLB name back to KUBE-FW based on discussion

**Comment by freehan** [comment]
KUBE-FW has N rules per sourceRanges
KUBE-XLB has M rules per local endpoints

If we combine them, KUBE-XLB will end up with N * M rules. Any other tricks to solve this?

**Comment by thockin** [comment]
I had to write it all out to understand, but now I do.  Yech.  The names
still make me grumpy.  OK

**Comment by girishkalele** [comment]
Potentially ipsets would solve this - reducing the N rules to 1 source ip-set rule - but we then need a whole new library to manage the ipset.

**Comment by thockin** [comment]
yeah, optimize as a second pass.

**Comment by freehan** [comment]
Rebased. Only code gen changes. Reapplying lgtm

**Comment by fabioy** [comment]
Cherrypick approved. I'm assuming this supercedes #30486 and I can drop the "cherrypick candidate" label from that one?

**Comment by thockin** [comment]
Correct

**Comment by fabioy** [comment]
Ugh, too many conflicts, couldn't create an automatic cherrypick. Please create one and I'll try to get this in quickly. Thanks.

**Comment by freehan** [comment]
Can we let this sit overnight?

**Comment by thockin** [comment]
yes please

**Comment by thockin** [comment]
This really needs e2e coverage

**Comment by liggitt** [comment]
just saw this go into 1.3 in https://github.com/kubernetes/kubernetes/issues/31019. is there an urgent reason this was needed in 1.3? the linked issues didn't seem to be high priority enough to justify such a large pick

**Comment by fabioy** [comment]
Combined, they fix two networking issues, which was deemed fix worthy. This issue was passed over previous patch releases until it was deemed ok.

**Pull request merged**
