### PR TITLE
Cherry-pick of set of fixes for fluentd logging agent

### PR DESCRIPTION
**Pull request by piosz**
This PR consists of:
1. Cherry-pick of PR which migrates fluentd from manifest pod (#32088). We need this change to easily manage fluentd, which is required to fix a bunch of problems with it.
1. Revert of @ixdy's security patch hack #39706 with cherry-pick of the proper fix from #39770
1. Preventing fluentd from exporting its own logs #38286, @38213
1. Fix for wrong log severity in Stackdriver #39151
1. A few minor fixes for fluentd to avoid merge conflicts #37681, #37941, #38218, #33584

All those changes are combined together in a single PR because of merge conflicts. 

```release-note
Migrated fluentd logging agent to DaemonSet.
```

### CODE REVIEW

**Comment by piosz** [comment]
Also please do not apply LGTM label until all reviewers approve the PR.

**Review by crassirostris — CHANGES_REQUESTED** [review]
IMO, it'd be greate to include https://github.com/kubernetes/kubernetes/pull/40012 and https://github.com/kubernetes/kubernetes/pull/40017

**Comment by piosz** [comment]
I'll add #39598 but it's already huge so let's stay without the others PRs and limit the scope of this one.

**Comment by Crassirostris** [comment]
@piosz OK, it's just https://github.com/kubernetes/kubernetes/pull/40012 is very important for managed master

**Comment by piosz** [comment]
I added #39598

**Review by crassirostris — APPROVED** [review]

**Comment by piosz** [comment]
Thanks @saad-ali. Let's wait for approval from @fabioy and @ixdy

**Comment by piosz** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by piosz** [comment]
Please do not merge yet. We need to figure out whether we want to have it backported to 1.5.

**Pull request closed without merging**
