### PR TITLE
[WIP][1.18][go1.15] Update to go1.15

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency release-eng
/sig release

**What this PR does / why we need it**:

Update to go1.15.0

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

Tracking issue: https://github.com/kubernetes/release/issues/1421

**Special notes for your reviewer**:

Usually we don't backport Golang minor updates to previous branches, but because Kubernetes 1.19 will be built on go1.15 and go1.14 is being skipped by the Kubernetes community, we need to update to go1.15 on previous branches as well to remain on a supported Golang version for the Kubernetes 1.18 and 1.17 support cycles.

This is a WIP PR. There are a few other commits to cherry pick before this is ready to go.
/hold 

**Does this PR introduce a user-facing change?**:

```release-note
- Kubernetes is now built with go1.15.0
```

### CODE REVIEW

**Comment by liggitt** [comment]
it would be good to enumerate all the updates/picks required for this… 

the most concerning ones I recall are the bbolt/etcd bump (required for go1.14+), and the x509 common name deprecation in go1.15 which has the potential to be a breaking change, which we are allergic to in patch releases for anything but severe security or bug fixes (e.g. data loss issues)

**Comment by justaugustus** [comment]
> it would be good to enumerate all the updates/picks required for this…

Heh, I was going to in https://github.com/kubernetes/release/issues/1421 before tagging you here! :)
bbolt, etcd updates, errors.As for net, another error handling commit, and the cert stuff are what come to mind at the moment.

**Comment by dims** [comment]
Do we still need this @justaugustus ?

**Comment by justaugustus** [comment]
> Do we still need this @justaugustus ?

This is still active, but dependent on https://github.com/kubernetes/kubernetes/pull/94449.

**Comment by warmchang** [comment]
> > Do we still need this @justaugustus ?
> 
> This is still active, but dependent on #94449.

#94449 is done.
/retest

**Comment by cjellick** [comment]
Think this is still going to happen for 1.18 and 1.17?

**Comment by Linux-kubernetes-k8s** [comment]
请问源码编译（容器方式）先拉取了镜像。怎样修改文件避免编译再次拉取。编译版本v1.18.15

**Comment by justaugustus** [comment]
We're going to skip the upgrade at this point.
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1612486916175400?thread_ts=1612480925.169900&cid=C2C40FMNF

/close

**Pull request closed without merging**
