### PR TITLE
Simplify the sorting codes

### PR DESCRIPTION
**Pull request by miaoyq**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by miaoyq** [comment]
If this change is OK, I will modify other similar codes.

**Comment by liggitt** [comment]
lgtm, remove WIP?

**Comment by miaoyq** [comment]
@liggitt Have removed.  :)

**Comment by miaoyq** [comment]
There are still a lot of simillar codes in the project,  may I simplify them in the same way? @liggitt

**Pull request merged**
