### PR TITLE
remove phaseTransition

### PR DESCRIPTION
**Pull request by yingchunliu-zte**
Signed-off-by: yingchunliu-zte <liu.yingchun@zte.com.cn>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Phasetransition is redundant. Completeterminating and completesync will put messages in lastundeliveredworkupdate.

### CODE REVIEW

**Comment by yingchunliu-zte** [comment]
> Signed-off-by: yingchunliu-zte [liu.yingchun@zte.com.cn](mailto:liu.yingchun@zte.com.cn)
> 
> #### What type of PR is this?
> /kind cleanup
> 
> #### What this PR does / why we need it:
> Phasetransition is redundant. Completeterminating and completesync will put messages in lastundeliveredworkupdate.

sig/node

**Comment by yingchunliu-zte** [comment]
> /ok-to-test

/ok-to-test

**Comment by yingchunliu-zte** [comment]
> /assign @random-liu

/assign @random-liu

**Comment by yingchunliu-zte** [comment]
> Signed-off-by: yingchunliu-zte [liu.yingchun@zte.com.cn](mailto:liu.yingchun@zte.com.cn)
> 
> #### What type of PR is this?
> /kind cleanup
> 
> #### What this PR does / why we need it:
> Phasetransition is redundant. Completeterminating and completesync will put messages in lastundeliveredworkupdate.
/assign @mrunalp

**Comment by yingchunliu-zte** [comment]
> Signed-off-by: yingchunliu-zte [liu.yingchun@zte.com.cn](mailto:liu.yingchun@zte.com.cn)
> 
> #### What type of PR is this?
> /kind cleanup
> 
> #### What this PR does / why we need it:
> Phasetransition is redundant. Completeterminating and completesync will put messages in lastundeliveredworkupdate.

/assign @249043822

**Comment by 249043822** [comment]
https://github.com/kubernetes/kubernetes/issues/106884#issuecomment-1051049209
https://github.com/kubernetes/kubernetes/pull/108366#discussion_r816453182

**Comment by yingchunliu-zte** [comment]
> #108366 (comment)

#108366 (comment) no problem, but phasetransition is redundant.

**Comment by SergeyKanzhelev** [comment]
> > #108366 (comment)
> 
> #108366 (comment) no problem, but phasetransition is redundant.

Listed comments provide explanation why it's needed. This is sensitive area and if you have a strong feeling about it, please reopen and explain why the timing will not change with this update.

/close

**Pull request closed without merging**
