### PR TITLE
minor fix on log message

### PR DESCRIPTION
**Pull request by gorilla001**
**What this PR does / why we need it**:
* fix debug log message

```release-note

```

### CODE REVIEW

**Comment by nikhita** [comment]
@gorilla001 thanks for your first contribution to Kubernetes! :tada:

**Comment by idealhack** [comment]
Thanks for contributing. It seems you'd better cherry-pick the commit on a new branch. You can either rebase or open a new PR.

**Comment by k82cn** [comment]
please sign  cncf-cla, and why there're 100+ commit?

**Comment by idealhack** [comment]
Please address my comment above and open a new PR, thanks

/close
since this PR with master won’t work

**Pull request closed without merging**
