### PR TITLE
fixup some apimachinery packages

### PR DESCRIPTION
**Pull request by deads2k**
Moves the meta/v1/validation to apimachinery (since its logically shared) and moves the funny `apimachinery/pkg/genericapiserver/openapi/common` to `apimachinery/pkg/openapi`.

@kubernetes/sig-api-machinery-misc

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot verify test this

**Comment by deads2k** [comment]
@k8s-bot cvm gke e2e test this

**Comment by sttts** [comment]
lgtm

**Comment by deads2k** [comment]
@k8s-bot gci gke e2e test this

**Comment by deads2k** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
