### PR TITLE
Enhance message in cluster-info dump

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR fixes the information message prints in the end after the cluster-info dump command.
- Added newline in the end
- Enhanced the message for dumping information to standard out

**Which issue this PR fixes** *

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by mkumatag** [comment]
ping @fabianofranz

**Comment by mkumatag** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot verify test this

**Comment by mkumatag** [comment]
@fabianofranz everything is green, can you PTAL

**Comment by fabianofranz** [comment]
thanks @mkumatag 
/lgtm
/approve no-issue

**Pull request merged**
