### PR TITLE
Correctly use dogfood Cloud SDK and test endpoint by default for Jenkins GKE e2e tests (release-1.1)

### PR DESCRIPTION
**Pull request by ikehz**
Redo of #18547 that properly overrides defaults.

@spxtr If you're not aware of my screw-up, this might be a good thing to think about as a starting place; how to avoid all this weirdness?

### CODE REVIEW

**Comment by ihmccreery** [comment]
@jlowdermilk Second commit is diff from #18547.  PTAL, and I'll squash when it looks good.

**Comment by ihmccreery** [comment]
Fixed https://github.com/kubernetes/kubernetes/pull/18318#discussion_r47857258 here as well.

**Comment by jlowdermilk** [comment]
Looks good. I'll let submit queue pick it up and keep an eye on the jobs.

**Comment by ihmccreery** [comment]
@jlowdermilk great, thanks.

**Comment by ihmccreery** [comment]
Rebased, squashed.

**Comment by ihmccreery** [comment]
Just rebased, squashed; reapplying LGTM.

**Pull request merged**
