### PR TITLE
cluster/mesos lives in the incubator now

### PR DESCRIPTION
**Pull request by calebamiles**
**What this PR does / why we need it**:

Removes `cluster/mesos` which has been subsumed by https://github.com/kubernetes-incubator/kube-mesos-framework. As `@karlkfi` is the only maintainer listed in an `OWNERS` file and taking into account https://github.com/kubernetes/kubernetes/issues/38392, this code is dead and should be removed.

**Release note**:

 `NONE`

### CODE REVIEW

**Comment by calebamiles** [comment]
Could one of @eparis, @jbeda, @mikedanese, @roberthbailey, @zmerlynn please take a look. Thanks!

**Comment by calebamiles** [comment]
Also @deads2k, @k82cn PTAL

**Review by k82cn — APPROVED** [review]
/lgtm

We're going to keep those files/features in kube-mesos incubator projects.

**Comment by deads2k** [comment]
lgtm

**Pull request merged**
