### PR TITLE
kubemark: enable CRI in the hollow kubelet

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
#42739 and #42768 were merged. 

Are you folks ok with trying this again? I promise to watch the builds and revert if necessary. So far the kubemark failures has helped directed our attention to some real bugs.

/cc @Random-Liu

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by wojtek-t** [comment]
I'm fine with trying this again.

**Comment by wojtek-t** [comment]
@brendandburns - btw, this PR shouldn't be lgtm-ed by bulk-lgtm tool - even though it's one-liner, this is pretty non-trivial change, that requires conscious decision.

**Comment by eparis** [comment]
He actually did it during the community meeting while we all watched him. Public shame!

**Comment by yujuhong** [comment]
@wojtek-t, do you mind giving your lgtm? 

@k8s-bot cvm gce e2e test this (known issue about pod deletion; fix is on the way).

**Comment by gmarek** [comment]
It seems that everything works now. Thanks!

**Comment by yujuhong** [comment]
Awesome. Thanks for the help @wojtek-t @gmarek!

**Comment by wojtek-t** [comment]
@yujuhong - you're welcome. It's great that thanks to kubemark we found, debugged and fixed some real issues. Thanks for all the work you did here.

**Pull request merged**
