### PR TITLE
Ubernetes Lite: apply auto-labels to dynamically provisioned volumes

### LINKED ISSUE #22532: Ubernetes Lite: Validate the PVs created dynamically are still labeled
I created a PV and it wasn't labeled with the Ubernetes-Lite tags, but I wasn't running under Ubernetes-Lite at the time...

```
"annotations": {
            "kubernetes.io/createdby": "aws-ebs-dynamic-provisioner",
            "volume.alpha.kubernetes.io/storage-class": "foo",
            "volume.experimental.kubernetes.io/provisioning-required": "volume.experimental.kubernetes.io/provisioning-completed"
        }
```

### PR DESCRIPTION
**Pull request by justinsb**
It's yet more repeated code, but I think it's a minimal targeted fix for 1.2.  I think #21386 is a better answer, and if we can get that into 1.2, we should.  But if we can't then I think we should just do this.

Fix #22532

### CODE REVIEW

**Comment by justinsb** [comment]
Marking for cherry-pick when/if this merges.  We need either this or #21386 in 1.2 IMO

**Comment by justinsb** [comment]
I'm going to assign this to @saad-ali as the person best place to make the call vs #21386 (as the reviewer on that one)

**Comment by saad-ali** [comment]
The original API PV object, which is created by the provisioner before the volume is actually provisioned, is not updated, is that ok?

Between this and #21386, since the 1.2 branch is cut, I'd go with the minimal change required (this PR).

**Comment by justinsb** [comment]
> The original API PV object, which is created by the provisioner before the volume is actually provisioned, is not updated, is that ok?

Yeah; I don't think there's really an alternative here (at least in the way this PR does it).  Until we actually create the volume, we can't cleanly know the tags.  In practice, we can predict the tags today, but that isn't true in the general case.

**Comment by justinsb** [comment]
I'm hitting this issue while testing this PR on GCE, but I'm getting a surprising error in the kube-controller-manager logs:

```
E0309 17:38:43.010372       9 gce_util.go:159] error getting labels for volume "": json: invalid use of ,string struct tag, trying to unmarshal "projects/kubernetes-e2e-justinsb/zones/us-central1-a/disks/" into uint64
```

Anyone have any idea?  cc @quinton-hoole because Ubernetes-Lite

**Comment by justinsb** [comment]
I think I found it... a silly error where I'm using the wrong variable.  Will fix & clean up the function declaration to match our style.

**Comment by justinsb** [comment]
Fix pushed, and now verified working on GCE also (as well as AWS).  I had made a stupid mistake where I used the arg name from the function return parameters.  Turns out that weird error happens when you pass an empty disk name to Disks.Get.

**Comment by saad-ali** [comment]
Thanks Justin. Will review by EOD.

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
This should be cherry-picked for 1.2

**Comment by eparis** [comment]
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.

**Pull request merged**
