### PR TITLE
Automated cherry pick of #73016: Bump the pod memory to higher levels to work on power

### PR DESCRIPTION
**Pull request by mikebrow**
Cherry pick of #73016 on release-1.13.

#73016: Bump the pod memory to higher levels to work on power

### CODE REVIEW

**Comment by mikebrow** [comment]
need this cherry picked due to the runc memory issue created by mitigation of recent CVE.. [opencontainers/runc#1980](https://github.com/opencontainers/runc/issues/1980)

@yujuhong

**Comment by yujuhong** [comment]
This PR touches only summary API test. The test was meant to check that all resources are reported with reasonable/valid values. It did not intend to enforce strict limits. Bumping the memory limits to unblock the releases.

/lgtm
/approve

**Pull request merged**
