### PR TITLE
Add `image_id` to CRI `ContainerStatus` message

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
There is a conversion function `ConvertPodStatusToRunningPod`, which can override the `Container.ImageID` into a digested reference from the `ContainerStatus` CRI RPC, which gets mapped from the `image_ref`:

https://github.com/kubernetes/kubernetes/blob/411c29c39f03687a30a8667295c61590def8fc89/pkg/kubelet/container/helpers.go#L259-L292

To avoid that failure case, we now introduce the same `image_id` into the container status and let runtimes separate the fields.

We also add a note that the mapping from the digested reference of the CRI to the Kubernetes Pod API `ImageID` field is intentional and should not change.

#### Which issue(s) this PR fixes:
Follow-up on: https://github.com/kubernetes/kubernetes/pull/123508

#### Special notes for your reviewer:
PTAL @mrunalp @haircommander @mikebrow @kubernetes/sig-node-pr-reviews 

_This is not a bug, it's preventing internal API misusage to create one._

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@mikebrow @SergeyKanzhelev ptal

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
