### PR TITLE
avoid use abbreviation in flag

### PR DESCRIPTION
**Pull request by mqliang**
@wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: hack/verify-generated-docs.sh:28 main(...)

@mqliang - can you please fix?

**Comment by mqliang** [comment]
@wojtek-t Updated. PTAL.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
Merging manually to have it merge before 1.2 release is cut.

**Pull request merged**
