### PR TITLE
test/e2e: Add e2e tests for kubectl --subresource

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR adds e2e tests for the `kubectl --subresource` feature.
xref: https://github.com/kubernetes/enhancements/issues/2590 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Adding e2e tests for kubectl --subresource for beta graduation
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2590-kubectl-subresource
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by justinsb** [comment]
This test may be flaky (?)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1635697963260973056/


```


8s
--
{ failed [FAILED] Expected     <string>: "...  6m42s   v..." to equal               \|     <string>: "...  6m43s   v..." In [It] at: test/e2e/kubectl/kubectl.go:1993 @ 03/14/23 18:16:38.104 }


```

**Pull request merged**
