### PR TITLE
pkg/kubelet: Replace deprecated func usage from the `k8s.io/utils/pointer` pkg

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/pull/111585 and https://github.com/kubernetes/kubernetes/pull/111585#issuecomment-1214203495.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
https://github.com/kubernetes/utils/pull/249
/lgtm

**Review by endocrimes — APPROVED** [review]
/triage accepted
/priority important-soon
/lgtm

**Comment by ialidzhikov** [comment]
Sorry for the many force-pushed. Something got wrong during the rebase. Now the PR should be ready for review again.

**Review by mrunalp — APPROVED** [review]

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
