### PR TITLE
Move kubeadm to staging

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Move `cmd/kubeadm` to staging
```

### CODE REVIEW

**Comment by dims** [comment]
The failure in pull-kubernetes-e2e-kubeadm-gce is unrelated. Please see https://github.com/kubernetes/kubernetes/issues/53570 for the underlying problem with latest images

**Comment by luxas** [comment]
@dims sorry, I'm out and can't look into the failure. Most probably infra-related given the recent history: http://prow.k8s.io/?job=pull-kubernetes-e2e-kubeadm-gce
(also when taking into account that the CI job seems to be green: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce)

**Comment by dims** [comment]
Looks like there isn't enough support for this right now (sig-clusterlifecycle meeting)

Thanks,
Dims

**Comment by thockin** [comment]
I don't get the "not enough support"?  If this can be extracted with relatively low pain, it should.  It absolutley should.  What's the concern?

**Comment by dims** [comment]
@thockin  Please see the discussion in the 2017-10-10 17.04.10 SIG-cluster-lifecycle meeting. Starts around 4:00 minutes into the meeting. 

https://www.youtube.com/watch?v=fRidax7z7A0&index=2&list=PL69nYSiGNLP29D0nYgAGWt1ZFqS9Z7lw4

**Pull request closed without merging**
