### PR TITLE
Mutable nodeAffinity for PVs

### LINKED ISSUE #69528: nodeAffinity for the volumes should be mutable
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig storage

**What happened**:

I use `nodeAffinity` for describe nodes where my volume is connected to.

After long time I may want to reassign this volume to another nodes.
There is no way for change `nodeAffinity` for the existing persistentVolume after it is already created.

```
kubectl apply -f /tmp/pv-00001-volume.yaml
The PersistentVolume "pv-00001" is invalid: nodeAffinity: Invalid value: core.VolumeNodeAffinity{Required:(*core.NodeSelector)(0xc439e294a0)}: field is immutable
```

**What you expected to happen**:
Updated `VolumeNodeAffinity` for the PersistentVolume

**How to reproduce it (as minimally and precisely as possible)**:
Create volume with:
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["node1", "node2", "node3", "node4", "node5"]
```
Try to update targeted hostnames for the volume.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version **v1.12.0**
- Cloud provider or hardware configuration: **baremetal**

### PR DESCRIPTION
**Pull request by kvaps**
**What type of PR is this?**

/kind api-change
/kind feature

**What this PR does / why we need it**:

Allows to update/remove nodeAffinity for existing PVs.

See #69528 and https://github.com/LINBIT/linstor-csi/pull/56 for more details

**Which issue(s) this PR fixes**:

Fixes #69528

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

```release-note
Allow updating nodeAffinity terms for PersistentVolumes
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @msau42 
xref https://github.com/kubernetes/kubernetes/issues/69528#issuecomment-564143848

**Comment by msau42** [comment]
Sorry for the delay in response. I thought about it in https://github.com/kubernetes/kubernetes/issues/69528#issuecomment-606972452, and unfortunately I think making this field mutable is going to open up some irrecoverable situations if the NodeAffinity changes in the middle of scheduling or binding.

**Pull request closed without merging**
