### PR TITLE
Remove delay on first invocation of ItemExponentialFailureRateLimiter::When

### PR DESCRIPTION
**Pull request by dprotaso**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

When using this rate limiter with an empty queue I was seeing delays when
adding a new item with `AddRateLimited`. This is odd as I would expect delays
only on subsquent additions after a failure.

This change removes the delay on the first invocation of `When`.

#### Special notes for your reviewer:
👋

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dprotaso** [comment]
Unit test failure seems unrelated
```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters: TestErrConnKilledHTTP2 
```

/retest

**Comment by ncdc** [comment]
I'm not sure this is a desirable change for the typical invocations of Add and AddRateLimited. Usually you want to do this:

1. When you get an informer event, you call queue.Add()
2. The worker pops from the queue and tries to reconcile
3. If reconciliation fails, you call queue.AddRateLimited()
4. If it succeeds, you call queue.Forget() to reset the rate limiter for that item

With the change in this PR, step 3 would result in an immediate requeue, instead of being rate limited.

**Comment by ncdc** [comment]
AFAIK, yes - QPS/bucket is for the queue in its entirety, irrespective of individual items. Backoff is per item.

**Comment by dprotaso** [comment]
> QPS/bucket is for the queue in its entirety,

to clarify it's only for _failed_ items in the queue - correct?

**Comment by ncdc** [comment]
It looks like it only applies to AddRateLimited

**Comment by liggitt** [comment]
yeah, ItemExponentialFailureRateLimiter is only used to rate-limit requeues because of failures

I agree with Andy that we don't want to change the behavior. Documenting the rate limit only applies to calls to `AddRateLimited` seems useful

**Comment by dprotaso** [comment]
Sounds good - thanks!

**Pull request closed without merging**
