### PR TITLE
Add node e2e test for mirror pod.

### PR DESCRIPTION
**Pull request by Random-Liu**
This is a node e2e test for mirror pod.

After this get merged, I'll revisit the mirror pod manager PR. #18638

/cc @yujuhong

### CODE REVIEW

**Comment by yujuhong** [comment]
We should delete the disabled static/mirror pod test in cmd/integration/integration.go after this lands.

**Comment by Random-Liu** [comment]
Fixes #20762.

**Comment by pwittrock** [comment]
Nice

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #24579

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #24579

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #24579

**Comment by Random-Liu** [comment]
Rebased, self apply LGTM again.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #24628

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #21484

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #21484

**Pull request merged**
