### PR TITLE
kubelet/get-pod-from-path: unused param should be removed

### PR DESCRIPTION
**Pull request by chentao1596**
**What this PR does / why we need it**:

    I think unused param should be removed, please make sure it, thank you!

### CODE REVIEW

**Comment by chentao1596** [comment]
@yujuhong @vishh @dchen1107 hi, /cc, please, thank you

**Comment by chentao1596** [comment]
@yujuhong @vishh @dchen1107  hi, please take a look, thank you!

**Comment by vishh** [comment]
@k8s-bot ok to test

**Comment by chentao1596** [comment]
@vishh I have not found any relations with this commit for this error(report by k8s-ci-robot), can you help to ask to test it again? thank you!

**Comment by chentao1596** [comment]
@vishh Hi, i am sorry for this delay, all checks have been through, PTAL, thank you!

**Pull request closed without merging**
