### PR TITLE
Add config for the main gke-jenkins jobs to e2e.sh

### PR DESCRIPTION
**Pull request by j3ffml**
This is a cherrypick of just the `cluster/gke` changes from #13863 so that gke e2e tests running versioned k8s releases use the stable `gcloud container` command group, in case we want to test features/make breaking changes on `gcloud alpha|beta container`.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
LGTM

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Pull request merged**
