### PR TITLE
Deregister clusters during federated namespace e2e tear down.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is causing other tests to leak resources.

cc @mwielgus @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33869)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@madhusudancs Perhaps I'm being dumb, but it's not clear to me how these lingering cluster objects in the federation control plane are causing more general cloud resource leaks?  Can you provide some context to help me to understand?

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
@quinton-hoole 

> @madhusudancs Perhaps I'm being dumb, but it's not clear to me how these lingering cluster objects in the federation control plane are causing more general cloud resource leaks? Can you provide some context to help me to understand?

I haven't identified all the sources yet, but here is one example - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federated-ingress.go#L70. It creates a federated ingress object and does not expect the ingress object to be copied to underlying clusters because as far as that test is concerned, it did not register any clusters. But a potential preceding run of the namespace test registered the clusters but failed to de-register them. This test which did not expect to have those ingress objects in the underlying clusters has now inevitably created those objects without its control. Here are some other examples - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federation-authn.go#L45, https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federation-authn.go#L65 and https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federation-authn.go#L79.

Note that there can be other unintended side effects of not properly cleaning up as well. For example, this test - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federation-apiserver.go#L57- doesn't do what it is intended to do if the namespace test runs before this test and does not properly clean up.

**Comment by madhusudancs** [comment]
@quinton-hoole 

> but it's not clear to me how these lingering cluster objects in the federation control plane are causing more general cloud resource leaks?

Also, for additional clarification, it is not any "general cloud resource" we are leaking. We are leaking specifically those resources that we create in our test suite.

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
Thanks @madhusudancs .  That makes perfect sense. Code looks good to me. LGTM.

**Comment by quinton-hoole** [comment]
@madhusudancs And my apologies.  There's a fix for one of the errors that you're seeing in your Federation GCE e2e test in https://github.com/kubernetes/kubernetes/pull/33607 , which I decided not to merge, due to the other problems with that PR.  I'll send a separate PR for the good part of that fix now.

**Comment by madhusudancs** [comment]
@quinton-hoole sure, thanks! And thanks for the review!

**Comment by quinton-hoole** [comment]
#33977 is the above-mentioned fix.

**Comment by madhusudancs** [comment]
> #33977 is the above-mentioned fix.

@quinton-hoole ack.

**Pull request merged**
