### PR TITLE
Automated cherry pick of #48786 upstream release 1.7

### PR DESCRIPTION
**Pull request by janetkuo**
Cherrypick #48786 to fix a regression in 1.7

### CODE REVIEW

**Comment by yujuhong** [comment]
/lgtm

The description is wrong. Should be 1.7 :-)

Assigning to the 1.7 branch manager for approval.
/assign @caesarxuchao

**Comment by caesarxuchao** [comment]
cc @wojtek-t

**Comment by janetkuo** [comment]
Description updated

**Comment by wojtek-t** [comment]
Cherrypick approved.

**Comment by janetkuo** [comment]
pull-kubernetes-federation-e2e-gce failure: #47978

**Comment by wojtek-t** [comment]
I'm temporarily adding do-not-merge label due to some problems with release branch. Will remove it once we figure it out.

**Comment by wojtek-t** [comment]
OK - this is good to go. Removing do-not-merge label.

/retest

**Pull request merged**
