### PR TITLE
MOD:fix spelling errors

### PR DESCRIPTION
**Pull request by calmkart**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
cleanup: fix the spelling errors

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the typo fixes.
/lgtm
/ok-to-test

**Comment by oomichi** [comment]
Nice catch.

/retest
/lgtm
/approve

**Pull request merged**
