### PR TITLE
Fix spell error

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
Fix the word spelling error
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @JieJhih 
/ok-to-test
/kind cleanup
/lgtm

**Comment by dims** [comment]
@thockin another tiny change, PTAL

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
