### PR TITLE
v1beta3: fields that cannot be updated are marked "cannot be udpated"

### LINKED ISSUE #1728: Document which in-place updates work and which ones don't
It's non-obvious. See #1712.

### PR DESCRIPTION
**Pull request by yujuhong**
This fixes #1728.

### CODE REVIEW

**Comment by yujuhong** [comment]
@vishh, @bgrant0607

**Comment by bgrant0607** [comment]
Awesome, thanks. Could you please regenerate the swagger using hack/update-swagger-spec.sh?

**Comment by yujuhong** [comment]
@bgrant0607, done! It seems that `hack/update-swagger-spec.sh` has not been run for a long time, so my PR includes many changes in the spec. Maybe we should verify this in pre-submit hook and/or travis?

**Comment by nikhiljindal** [comment]
Yes. We need to do that.

**Comment by bgrant0607** [comment]
LGTM.

**Comment by vishh** [comment]
LGTM

**Pull request merged**
