### PR TITLE
Juju kubernetes-master: Fix UpdateAddonsTactic to use local repo

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This PR does 2 things:
1. When building the kubernetes-master charm, instead of cloning the Kubernetes repo from github to pull the addons, just use the local repository instead
2. If the KUBE_VERSION environment variable is set, then clone the local repository and checkout the corresponding branch instead

We need this to guarantee that, when we are developing and building charms against a stable release, we can pull in addon versions that work with it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/213

**Special notes for your reviewer**:

**Release note**:

```release-note
Juju kubernetes-master: Fix UpdateAddonsTactic to use local repo
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
@k8s-bot ok to test

**Comment by marcoceppi** [comment]
@k8s-bot node e2e test this
@k8s-bot cri node e2e test this

I find these failures concerning, possibly flakey?

**Comment by marcoceppi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41251)*

**Comment by Cynerva** [comment]
@k8s-bot kops aws e2e test this

**Comment by chuckbutler** [comment]
Fantastic, this successfuly closed 213 during my testing. I'm +1

/approve

**Comment by Cynerva** [comment]
@david-mcmahon are you able to give this a review? It would be much appreciated!

**Comment by Cynerva** [comment]
Closing since this was change was merged in via #41351

**Pull request closed without merging**
