### PR TITLE
Fix: dynamic provisioning for vSphere

### PR DESCRIPTION
**Pull request by kerneltime**
**What this PR does / why we need it**:

Cherry pick of https://github.com/kubernetes/kubernetes/pull/30836
Without this dynamic provisioning in vSphere fails.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35474)

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by kerneltime** [comment]
These failures don't seem related to the change. Let me know how I can help.

**Comment by kcrawley** [comment]
@kerneltime thank you for pointing this out. i was curious as to how (or if) this was being handled. this appears to be io (disk) related.

at some point i was going to look into dynamic provisioning of entire nodes; which is what sparked my interest in flannel (because ssh'ing into every minion and adding/changing routes is far from ideal).

**Comment by kerneltime** [comment]
@kcrawley this is just the ability to create persistent volumes for pods not automatic addition of nodes. The cloud provider framework provides functionality for pods mostly. What you are asking for is being discussed in sig-lifecycle and you should look at kube-anywhere and kubeadm.

**Pull request merged**
