### PR TITLE
Add detailed err in ensure docker process error

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

**What this PR does / why we need it**:
Add detailed error.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ggaaooppeenngg** [comment]
@dixudx What's wrong with pull-kubernetes-e2e-kubeadm-gce-canary?

**Comment by dixudx** [comment]
> What's wrong with pull-kubernetes-e2e-kubeadm-gce-canary?

W0130 08:42:55.313] Getting shared build location from: gs://kubernetes-jenkins/shared-results/master:4b3d9e71df14454ce3ee3535429f1acd42c1eb5a,59025:ac86428d5971dd1da246cae157a79ad64b720b81/bazel-build-location.txt
W0130 08:42:55.351] Failed to get shared build location: HTTP Error 404: Not Found

/retest

**Comment by dixudx** [comment]
@ggaaooppeenngg Currently `pull-kubernetes-e2e-kubeadm-gce-canary` is not a must-pass job. Let it go.

**Comment by ggaaooppeenngg** [comment]
@dixudx PR does not have approved label, what should I do next?

**Comment by dixudx** [comment]
/retest

ping @yujuhong @tallclair for approval. Thanks.

**Pull request merged**
