### PR TITLE
Automated cherry pick of #44406 upstream release 1.6

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #44406 on release-1.6.

#44406: CRI: Stop following container log when container exited.

@enisoc 

**Release note**:
```release-note
`kubectl logs -f` now stops following when container stops.
```

### CODE REVIEW

**Comment by yujuhong** [comment]
This is not a critical bug, but it's still annoying for the users.

/lgtm

/cc @dchen1107

**Comment by enisoc** [comment]
To make sure I understand: It used to stop automatically pre-CRI (v1.5), and this is fixing CRI (v1.6) to behave the same way?

**Comment by yujuhong** [comment]
> To make sure I understand: It used to stop automatically pre-CRI (v1.5), and this is fixing CRI (v1.6) to behave the same way?

Yes, that's correct.

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Pull request merged**
