### PR TITLE
allow kubectl -f to filter by selector

### LINKED ISSUE #32544: kubectl path based resource selection should support filtering with label selector
Right now it is not supported:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/builder.go#L546-L552

### PR DESCRIPTION
**Pull request by mikedanese**
cc @kubernetes/kubectl

Fixes #32544

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32599)

### CODE REVIEW

**Comment by dgonzalez** [comment]
I would like to shadow this code review

**Comment by mikedanese** [comment]
this is blocking #33698

**Comment by pwittrock** [comment]
@ymqytw Would you shadow this as well?

**Comment by pwittrock** [comment]
@janetkuo Let me know if you don't have bandwidth for this

**Comment by janetkuo** [comment]
Please add a test for this, e.g. in `hack/make-rules/test-cmd.sh`

**Comment by ymqytw** [comment]
Looks good for now, but need rebase and a test.

**Comment by mikedanese** [comment]
@ymqytw I rebased and added a test

**Comment by ymqytw** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/kubectl/resource/builder.go, line 713 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32599#-KSt14ersMs3jQzGEe8s:-KSt14ersMs3jQzGEe8t:bersz25) ([raw file](https://github.com/kubernetes/kubernetes/blob/3406566ddf85bac092ea42faf02bda7461fe3fa3/pkg/kubectl/resource/builder.go#L713)):*
> ```Go
> 		return &Result{err: fmt.Errorf("name cannot be provided when a selector is specified")}
> 	}
> ```

It should return a error, if len(b.resourceTuples) != 0, isn't it?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32599)*

**Comment by mikedanese** [comment]
@ymqytw Agree. fixed.

**Comment by mikedanese** [comment]
@k8s-smoke test this please, issue: #33672

**Comment by ymqytw** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot smoke test this please, issue: #33672

**Comment by mikedanese** [comment]
@k8s-bot e2e test this please, issue: #33672

**Comment by bgrant0607** [comment]
@mikedanese Does this support filtering for all commands that support --filename?

**Comment by mikedanese** [comment]
@bgrant0607 it adds infrastructure to but individual commands need to be slightly retrofitted.

**Pull request merged**
