### PR TITLE
fix incorrect log

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
fix incorrect log in nfs_test.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE
**Special notes for your reviewer**:
NONE
**Release note**:
NONE

### CODE REVIEW

**Comment by sjenning** [comment]
nice test cleanup :+1: 
/release-note-none
/sig storage
/ok-to-test

**Review by oomichi — COMMENTED** [review]
/LGTM

**Pull request merged**
