### PR TITLE
Automated cherry pick of #47140 upstream release 1.7

### PR DESCRIPTION
**Pull request by seanknox**
Cherry pick of #47140 on release-1.7.

#47140: Update Azure SDK

**Release note**:
```release-note
Prerequisite to fix a number of bugs on Azure provider, including inconsistent attach/detach disk behavior, moving disks between nodes and hang during mount/format
```

### CODE REVIEW

**Comment by seanknox** [comment]
This is cherry-pick number three, building on top of #49049 and #48961. The actual change set is identical to PR #47140.

**Comment by wojtek-t** [comment]
Can you please squash the commits?

**Comment by wojtek-t** [comment]
Also, I'm a bit lost - are some commits in this PR also part of the other PR?

**Comment by seanknox** [comment]
@wojtek-t thanks and will squash the commits. once https://github.com/kubernetes/kubernetes/pull/49049 is merged the commits from that PR will go away.

**Comment by brendandburns** [comment]
@wojtek-t (just to explain) in order to streamline the cherry-picking processing, we built some of the picks on top of cherry-picks that we expected to go in before others. That's why there are some commits from other cherry-picks. 

Once they merge and we rebase, those commits should drop out.

It was easier to do that to make sure that the cherry-picks were clean, rather than waiting and rebasing after the merges.

Hope that makes sense.

Thanks!
--brendan

**Comment by seanknox** [comment]
@wojtek-t Squashed the manual commits for this cherry pick. The remaining commits are the original work from Brendan's original PR in https://github.com/kubernetes/kubernetes/pull/47140.

**Comment by seanknox** [comment]
@wojtek-t I think this PR is ready now, let us know if you need anything.

**Comment by jdumars** [comment]
This PR is a pre-requisite for this implementation of the fixes below (as outlined in #49056 ).

Addresses the current issues with Blob Disks:

* Significantly faster attach process. Disks are now usually available for pods on nodes under 30 sec if formatted, under a min if not formatted.
* Adds support to move disks between nodes.
* Adds consistent attach/detach behavior, checks if the disk is leased/attached on a different node before attempting to attach to target nodes.
* Fixes a random hang behavior on Azure VMs during mount/format (for both blob + managed disks).
* Fixes a potential conflict by avoiding the use of disk names for mount paths

**Comment by wojtek-t** [comment]
@seanknox I added some release based on comment from the other PR. Feel free to adjust it.

@brendandburns - please LGTM and approve it.

**Comment by seanknox** [comment]
Perfect, thank you!

**Comment by jdumars** [comment]
@wojtek-t looks like everything is in order now.  Thank you again for your help with these.

**Comment by brendandburns** [comment]
I think we need cherrypick-approved on the original? @wojtek-t I think that is for you as release owner?

**Comment by wojtek-t** [comment]
Should be good to go now.

**Comment by wojtek-t** [comment]
> I think we need cherrypick-approved on the original? @wojtek-t I think that is for you as release owner?

No - that's not needed - this one should have "cherrypick-approved". I'm just personally having a schema that I'm not approving the original before the cherrypick is good to go - it's just easy to figure out what else is requested by not yet prepared for submitting.

**Comment by brendandburns** [comment]
@wojtek-t great, many thanks.

**Comment by seanknox** [comment]
/retest

This passed all tests earlier, and all of the pending tests are actually finished. Not sure what's up, so kicking them off again.

**Comment by seanknox** [comment]
@wojtek-t guessing the queue might be feeling some pain, hence why this PR has been stuck...JFYI.

**Comment by brendandburns** [comment]
hey @wojtek-t I don't know why the status here is locked up, I'm going to close and re-open to try to break something loose...

**Pull request merged**
