### PR TITLE
Removed mesos flags from known-flags.txt.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by luxas** [comment]
/lgtm
/approve

Thanks!

**Review by luxas — APPROVED** [review]

**Comment by gyliu513** [comment]
Thanks @luxas , as this PR does not have an issue related, so seems using `/approve no-issue`?

**Comment by gyliu513** [comment]
Seems I still need an `/approve no-issue` label? @mikedanese @luxas

**Comment by luxas** [comment]
@gyliu513 No, not needed. I added the approved label manually, which is the outcome of the SQ making a PR `APPROVED`. I did that because it's not worth to ping hack approvers for this... also Mike approved

**Pull request merged**
