### PR TITLE
fix staticcheck of pkg/util/ebtables

### PR DESCRIPTION
**Pull request by Aresforchina**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:
fix staticcheck of pkg/util/ebtables
**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/kind cleanup
/priority backlog

/assign @SataQiu 
for /hack approval.

**Comment by SataQiu** [comment]
Thanks 
/approve

**Pull request merged**
