### PR TITLE
add GlobalEnv admission controller: using single annotation `global.env` value in namespace

### LINKED ISSUE #48180: Create custom cluster wide environment variables inject into every container
**Is this a BUG REPORT or FEATURE REQUEST?**:
Probably a feature request

/kind feature

**Anything else we need to know?**:

I have not found a way to inject global environment variables, either cluster-wide or per-namespace. The most common use cases I have seen are:

1. Indicate what environment or location we are in, e.g. `ENVIRONMENT=dev` or `ENVIRONMENT=prod`. Sure, I could set something on every deployment and daemonset and manual pod and .... but that is overhead and is messy. Could use configmap or secret, same issue. The cluster administrator should be able to say, "define the following environment vars that are injected into every container in the cluster (or, at best, limited by namespace).
2. Enabling features. E.g. I might want APM enabled on many of my app containers, but only when run in a kube cluster (as opposed to just running the image on my laptop), or perhaps only in certain environments. Cluster manager should be able to set a global env var of `ENABLE_APM=true` that then causes any container that consumes it to know, "I must enable APM now."

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.2
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CoreOS1235.6.0
- Kernel (e.g. `uname -a`): 4.7.3-coreos-r2
- Install tools: direct
- Others:

If it is there and I missed it, apologies.

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
The open issue was opened a long time ago and keeps active.

#### Which issue(s) this PR fixes:
Fixes #48180
image

#### Special notes for your reviewer:

This pr is an implementation of proposal 2 in https://github.com/kubernetes/kubernetes/issues/48180#issuecomment-867455423.

> Proposal 2: We can implement it as a new AdmissinoController, you can enable or disable it on the apiserver side.
> 
> A configmap: namespace kube-system configmap which is named cluster-wide-envs
> ** Or a namespace annotation named `global.env`, which works for pods in the namespace.**
> ** If enabled, the admission controller will add envFrom. configMapRef to every pod in the cluster**

env can save in multi places: the initial implement with namespace annotation.
1. in a configmap for all
2. in a configmap: key for namespace, value like A=B,C=D  
3. in namespace annotation

#### Does this PR introduce a user-facing change?
```release-note
add GlobalEnv admission controller: namespaced annotation to add default envs to pods
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Not sure if a KEP is needed.
```docs
- [KEP]: https://github.com/kubernetes/enhancements/pull/3612
```

### CODE REVIEW

**Comment by aojea** [comment]
> Not sure if a KEP is needed.

you are defining a new annotation and introduction a mechanism that can override current environment variables on pods, I think that a KEP is needed involving at least sig-api-machiner and sig-auth

**Comment by pacoxu** [comment]
> you are defining a new annotation and introducing a mechanism that can override current environment variables on pods, I think that a KEP is needed involving at least sig-api-machiner and sig-auth

There has been no new admission plugin recently. I want an initial idea/preliminary conclusions of whether sig will accept this design draft before converting it to a KEP.(Maybe the KEP is simple).  
I initially thought I would write a kyverno plugin if this is not accepted by k/k. 😄

**Comment by pacoxu** [comment]
> I initially thought I would write a [kyverno](https://github.com/kyverno/kyverno) plugin if this is not accepted by k/k. 😄

There is already one. https://github.com/kubernetes/kubernetes/issues/48180#issuecomment-867451341
So I will write a KEP later.

**Comment by pacoxu** [comment]
KEP https://github.com/kubernetes/enhancements/pull/3612

**Comment by tallclair** [comment]
This definitely requires a KEP. I'm going to close this for now, and you can reopen it once the KEP is marked implementable.

**Pull request closed without merging**
