### PR TITLE
Support for adding test-handler for containerd

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Some of the Runtimeclass tests, needs a test handler to be present (same as https://github.com/kubernetes/test-infra/pull/12732), let's add a switch to add this to config.toml when needed for testing.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'm fairly certain @Random-Liu already has something like this wired up for some existing jobs, curious why we need new bash for this :D

**Comment by dims** [comment]
@BenTheElder those are for the sig-node specific end to end tests AFAICT. 

[This](https://github.com/kubernetes/kubernetes/issues/87989#issuecomment-584813152) should be the last set of changes to make sure the following CI jobs go green:
- `pull-kubernetes-e2e-gce-ubuntu-containerd`
- `ci-kubernetes-e2e-ubuntu-gce-containerd`

In these 2 new CI jobs, we use ubuntu for both master and worker, we install specific versions of `containerd` and `runc` and ensure that they work correctly.

**Comment by justaugustus** [comment]
Looks sane!
/lgtm
/approve

**Pull request merged**
