### PR TITLE
Sort the victims after PDBViolation partitioning

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In selectVictimsOnNode, we sort all the potential victims before partitioning w.r.t. PDBViolation.
Suppose the size of violatingVictims is m and the size of nonViolatingVictims is n.
Complexity for current operation is (m+n) log(m+n).

This PR moves the sorting to after the partitioning, resulting in m log(m) + n log(n) complexity.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
@Huang-Wei 
Please take a look.

**Comment by Huang-Wei** [comment]
The PR doesn't seem to improve the perf in a practical case as `(m+n)` is usually less than 100, and `violatingVictims` might be less. So I'm not sure it worth the extra complexity. But if you can mock a test to prove that it performs much better, I'm fine with it.

**Comment by tedyu** [comment]
@Huang-Wei 
I wonder why the nonViolatingVictims need to be sorted.
I would think that nonViolatingVictims wouldn't have difference among themselves w.r.t. reprievePod

Thanks

**Comment by tedyu** [comment]
@bsalamat @Huang-Wei 
I ask the above question because, it seems the absence of any single nonViolatingVictim from the selection (due to podFitsOnNode returning false) would still end up with valid selection (of victims).

**Comment by Huang-Wei** [comment]
@tedyu I'm not seeing a nil nonViolatingVictim would cause side effect. If fits is false, it will bypass that node:

https://github.com/kubernetes/kubernetes/blob/df346787d2da6aa6afe36496ad522307e2e59463/pkg/scheduler/core/generic_scheduler.go#L987

Not sure if it's what you mean. If not, could you elaborate?

**Comment by tedyu** [comment]
My first attempt at benchmarking the change is with the following test:
```
func TestSelectNodesForPreempt(t *testing.T) {
	defer algorithmpredicates.SetPredicatesOrderingDuringTest(order)()
	tests := []struct {
		name                 string
		predicates           map[string]algorithmpredicates.FitPredicate
		nodes                []string
		pod                  *v1.Pod
		pods                 []*v1.Pod
		expected             map[string]map[string]bool // Map from node name to a list of pods names which should be preempted.
		addAffinityPredicate bool
	}{
		{
			name:       "a pod that does not fit on any machine",
			predicates: map[string]algorithmpredicates.FitPredicate{"matches": falsePredicate},
			nodes:      []string{"machine1", "machine2"},
			pod:        &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "new", UID: types.UID("new")}, Spec: v1.PodSpec{Priority: &highPriority}},
			pods: []*v1.Pod{
				{ObjectMeta: metav1.ObjectMeta{Name: "a", UID: types.UID("a")}, Spec: v1.PodSpec{Priority: &midPriority, NodeName: "machine1"}},
				{ObjectMeta: metav1.ObjectMeta{Name: "b", UID: types.UID("b")}, Spec: v1.PodSpec{Priority: &midPriority, NodeName: "machine2"}}},
			expected: map[string]map[string]bool{},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			assignDefaultStartTime(test.pods)

			nodes := []*v1.Node{}
			for _, n := range test.nodes {
				node := makeNode(n, 1000*5, priorityutil.DefaultMemoryRequest*5)
				node.ObjectMeta.Labels = map[string]string{"hostname": node.Name}
				nodes = append(nodes, node)
			}
			if test.addAffinityPredicate {
				test.predicates[algorithmpredicates.MatchInterPodAffinityPred] = algorithmpredicates.NewPodAffinityPredicate(FakeNodeInfo(*nodes[0]), schedulertesting.FakePodLister(test.pods))
			}
			for i := 1; i < 100; i++ {
				pod := &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: strconv.Itoa(i), UID: types.UID("a")}, Spec: v1.PodSpec{Priority: &midPriority, NodeName: "machine2"}}
				test.pods = append(test.pods, pod)
			}
			nodeNameToInfo := schedulernodeinfo.CreateNodeNameToInfoMap(test.pods, nodes)
			// newnode simulate a case that a new node is added to the cluster, but nodeNameToInfo
			// doesn't have it yet.
			newnode := makeNode("newnode", 1000*5, priorityutil.DefaultMemoryRequest*5)
			newnode.ObjectMeta.Labels = map[string]string{"hostname": "newnode"}
			nodes = append(nodes, newnode)
			_, err := selectNodesForPreemption(test.pod, nodeNameToInfo, nodes, test.predicates, PredicateMetadata, nil, nil)
			if err != nil {
				t.Error(err)
			}
		})
	}
}
```
where more pods are put on certain node.
However, selectVictimsOnNode would run to this call with fits being false:
```
	if fits, _, err := podFitsOnNode(pod, meta, nodeInfoCopy, fitPredicates, queue, false); !fits {
```
bypassing the sorting logic.

Let me dig some more ...

**Comment by tedyu** [comment]
This is how I timed the execution time for sorting:
```
	now = time.Now()
...
	duration = time.Now().Sub(now)
```
This is the test where I add 100 pods (for machine1) so that length of potentialVictims.Items is above 100:
```
func TestSelectNodesForPreempt(t *testing.T) {
	defer algorithmpredicates.SetPredicatesOrderingDuringTest(order)()
	tests := []struct {
		name                 string
		predicates           map[string]algorithmpredicates.FitPredicate
		nodes                []string
		pod                  *v1.Pod
		pods                 []*v1.Pod
		expected             map[string]map[string]bool // Map from node name to a list of pods names which should be preempted.
		addAffinityPredicate bool
	}{
		{
			name:       "mixed priority pods are preempted",
			predicates: map[string]algorithmpredicates.FitPredicate{"matches": algorithmpredicates.PodFitsResources},
			nodes:      []string{"machine1", "machine2"},
			pod:        &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "machine1", UID: types.UID("machine1")}, Spec: v1.PodSpec{Containers: largeContainers, Priority: &highPriority}},
			pods: []*v1.Pod{
				{ObjectMeta: metav1.ObjectMeta{Name: "a", UID: types.UID("a")}, Spec: v1.PodSpec{Containers: smallContainers, Priority: &midPriority, NodeName: "machine1"}},
				{ObjectMeta: metav1.ObjectMeta{Name: "b", UID: types.UID("b")}, Spec: v1.PodSpec{Containers: smallContainers, Priority: &lowPriority, NodeName: "machine1"}},
				{ObjectMeta: metav1.ObjectMeta{Name: "c", UID: types.UID("c")}, Spec: v1.PodSpec{Containers: mediumContainers, Priority: &midPriority, NodeName: "machine1"}},
				{ObjectMeta: metav1.ObjectMeta{Name: "d", UID: types.UID("d")}, Spec: v1.PodSpec{Containers: smallContainers, Priority: &highPriority, NodeName: "machine1"}},
				{ObjectMeta: metav1.ObjectMeta{Name: "e", UID: types.UID("e")}, Spec: v1.PodSpec{Containers: largeContainers, Priority: &highPriority, NodeName: "machine2"}}},
			expected: map[string]map[string]bool{"machine1": {"b": true, "c": true}},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			assignDefaultStartTime(test.pods)

			nodes := []*v1.Node{}
			for _, n := range test.nodes {
				node := makeNode(n, 1000*5, priorityutil.DefaultMemoryRequest*5)
				node.ObjectMeta.Labels = map[string]string{"hostname": node.Name}
				nodes = append(nodes, node)
			}
			if test.addAffinityPredicate {
				test.predicates[algorithmpredicates.MatchInterPodAffinityPred] = algorithmpredicates.NewPodAffinityPredicate(FakeNodeInfo(*nodes[0]), schedulertesting.FakePodLister(test.pods))
			}
			for i := 1; i < 100; i++ {
				pod := &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: strconv.Itoa(i), UID: types.UID(strconv.Itoa(i))},
					Spec: v1.PodSpec{Priority: &midPriority, NodeName: "machine1"}}
				test.pods = append(test.pods, pod)
			}
			nodeNameToInfo := schedulernodeinfo.CreateNodeNameToInfoMap(test.pods, nodes)
			// newnode simulate a case that a new node is added to the cluster, but nodeNameToInfo
			// doesn't have it yet.
			newnode := makeNode("newnode", 1000*5, priorityutil.DefaultMemoryRequest*5)
			newnode.ObjectMeta.Labels = map[string]string{"hostname": "newnode"}
			nodes = append(nodes, newnode)
			nodeToPods, err := selectNodesForPreemption(test.pod, nodeNameToInfo, nodes, test.predicates, PredicateMetadata, nil, nil)
			if err != nil {
				t.Error(err)
			}
		})
	}
}
```
I ran both versions several times.
Here were the execution time when potentialVictims was sorted:

33890359
33704670
30363357
31408061

Here were the execution time when violatingVictims and nonViolatingVictims were sorted separately (50% vs 50%):

32645903
31930228
30160236
29370112

@Huang-Wei 
What do you think ?

**Pull request closed without merging**
