### PR TITLE
Renamed packge name to apiv1

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
Renamed packge name from k8s_api_v1 to apiv1
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
thanks for your review @deads2k @ghodss

**Comment by deads2k** [comment]
I just realized where the weirdness comes from.  This is pointing to the old kube package references which @caesarxuchao wants to call out and hunt down for replacement/refactoring.  

I'll leave the rename up to him, but he may want to keep the separation.

**Comment by jianglingxia** [comment]
PTAL @caesarxuchao
thanks very much

**Comment by jianglingxia** [comment]
PTAL @caesarxuchao
thanks very much for your time

**Comment by caesarxuchao** [comment]
Indeed I was trying to differentiate them with the import of k8s.io/api/core/v1. But "k8s_api_v1" is not a good name, "apiv1" is better, so lgtm.

**Comment by jianglingxia** [comment]
PTAL label /ok-to-test @caesarxuchao
thanks

**Comment by jianglingxia** [comment]
PTAL label /ok-to-test @caesarxuchao
thanks,the pr test failed .but I have not Permissions to let the ci test it,thanks very much!

**Comment by jianglingxia** [comment]
PTAL label /ok-to-test @caesarxuchao
thanks,the pr test failed .but I have not Permissions to let the ci test it,thanks very much!
/assign   @brendandburns

**Comment by caesarxuchao** [comment]
I'm manually adding the "approved" label. The PR just changes the import aliases.

**Pull request merged**
