### PR TITLE
update vendored dependency github.com/docker/distribution

### PR DESCRIPTION
**Pull request by ameukam**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates : 
```
github.com/docker/distribution
github.com/docker/distribution/digestset
```

The following dependencies are also updated :
```
github.com/docker/go-connections/nat
github.com/docker/go-connections/sockets
github.com/docker/go-connections/tlsconfig
github.com/go-openapi/spec
github.com/go-openapi/validate
github.com/matttproud/golang_protobuf_extensions/pbutil
```

Part of #69776

**Which issue(s) this PR fixes** :

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by ameukam** [comment]
FYI @dims

**Comment by dims** [comment]
@ameukam - there does not seem to be any specific go code that seems to have changed ...

**Comment by ameukam** [comment]
@dims sorry to bothering you on this PR. I should have been more clear on my mention. I just wanted to be sure i'm following correctly the process.

**Comment by dims** [comment]
@ameukam i would have expected some changes to the go code within the docker repository. not sure what went wrong.

**Comment by justinsb** [comment]
Neither `/distribution` nor `/reference` looks to have any changes other than test code, so I think all the changes were pruned away.

Is there a change we're trying to pick up here?

Also - the version of docker we're vendoring a9fbbdc8dd seems to vendor a third version of docker/distribution 83389: https://github.com/moby/moby/blob/a9fbbdc8dd8794b20af358382ab780559bca589d/vendor.conf#L65 

Not sure how we're choosing versions here

**Comment by dims** [comment]
@roycaihw we need to figure out which SHA of the docker repo we want to pull in. Also we have to come up with a good reason to update as well. we are trying to document good reasons here - https://github.com/kubernetes/community/pull/2918

**Comment by roycaihw** [comment]
@dims I guess you were going to tag @ameukam, but accidentally tagged me in your previous comment?

**Comment by dims** [comment]
whoooops sorry @roycaihw ... yes, directed at @ameukam

**Comment by ameukam** [comment]
With #69776 closed, I will close this PR.
/close

**Pull request closed without merging**
