### PR TITLE
pull from master so richie can test

### PR DESCRIPTION
**Pull request by krousey**
@RichieEscarez

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM. It's all in _v1.1 folder which is still hidden, so we can just merge and revise later.

**Comment by caesarxuchao** [comment]
@krousey is it pulled from master or release-1.1?

**Comment by krousey** [comment]
master like he asked

**Comment by caesarxuchao** [comment]
@RichieEscarez if you just need something to test with I'll merge this PR. If you need something accurate we can ask @krousey to pull from release-v1.1.

**Comment by RichieEscarez** [comment]
@caesarxuchao , this is just for testing. As mentioned over chat. Its not clear if the alpha/beta extension content will be in release-v1.1. For now, please LGTM for testing, then we can figure out what is correct for GA later

**Comment by thockin** [comment]
CI will never fire for this branch

**Comment by thockin** [comment]
Manually merging

**Comment by caesarxuchao** [comment]
Thanks @thockin

**Comment by nikhiljindal** [comment]
@krousey I assume you had to make some changes in script to get this to work, for ex: _tools/import_doc still says v1.0. Do you have a PR to submit those changes?

Also, do we have the steps to generate a PR like this documented somewhere?
@caesarxuchao and I are making some changes after which we will have to regenerate the docs.

**Comment by krousey** [comment]
@nikhiljindal No. I didn't use the script. I just ran the tool manually with the right flags and then ran the sed command. I didn't update it since this seemed like a one-off from the official release process.

**Comment by bgrant0607** [comment]
Most page titles are broken. They are specified like this:
```
title: "</strong>"
```
which either appears as `</strong>` in the browser tab title, or as the file name.

Only a handful are useful page descriptions:
```
grep -r "^title:" . | grep -v "</strong>"
./gs-localmachine.md:title: "Getting Started: Local-machine Solutions"
./gs-custom.md:title: "Getting Started: Custom Solutions"
./basicstutorials.md:title: "Quick Walkthrough: Kubernetes Basics"
./multi-tier.md:title: "Examples: Multi-tier Applications"
./api-ref.md:title: "Kubernetes API Reference"
./gs-turnkey.md:title: "Getting Started: Turn-key Solutions"
./setup-config.md:title: "Examples: Setup and Configuration"
./app-admin-detailed.md:title: "Application Administration: Detailed Walkthrough"
./deploy-clusters.md:title: "Examples: Deploying Clusters"
```

**Pull request merged**
