### PR TITLE
add valid resource types for kubectl get

### PR DESCRIPTION
**Pull request by huangyuqi**
- the tips of `kubectl get` miss some resource type, including: `componentstatuses`  `endpoints` `quota` 
- the command `kubectl get` does not support `-o name`

### CODE REVIEW

**Comment by ashcrow** [comment]
Travis caught this:

```
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
```

**Comment by jlowdermilk** [comment]
Change lgtm, just need to run `hack/update-generated-docs.sh` to regen kubectl md/bash completion/etc

**Comment by huangyuqi** [comment]
Thanks , @jlowdermilk , I have ran the script you mentioned. But the shippable always builds time-out.
How can i fix it?

**Comment by jlowdermilk** [comment]
lgtm. You can ignore shippable. Jenkins unit/integration runs the same tests, so mergebot should pick this up shortly.

**Pull request merged**
