### PR TITLE
Automated cherry pick of #80173: make node lease renew interval more heuristic

### PR DESCRIPTION
**Pull request by gaorong**
Cherry pick of #80173 on release-1.13.

#80173: make node lease renew interval more heuristic

```release-note
make node lease renew interval more heuristic based on node-status-update-frequency in kubelet
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
One quick question - do we have a policy around cherry-picks to address alpha features? My understanding if this feature didn't graduate to beta until 1.14. And I know we typically try and reserve cherry-picks for critical issues.

That being said, its a fairly small amount of code to cherry pick.

I'm fine either way, was just curious :)

**Comment by wojtek-t** [comment]
> One quick question - do we have a policy around cherry-picks to address alpha features? My understanding if this feature didn't graduate to beta until 1.14. And I know we typically try and reserve cherry-picks for critical issues.

Yes - we shouldn't cherrypick it to 1.13 - only 1.14 and 1.15.

**Comment by gaorong** [comment]
thanks for reminding, close this one.

**Pull request closed without merging**
