### PR TITLE
Move /e2e/framework/ssh/ssh.go to framework package

### PR DESCRIPTION
**Pull request by clarklee92**
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e2e packages will use ssh.go functions from `framework`, avoiding dependency on each other between `ssh package` and `framework package`.

**Which issue(s) this PR fixes**:

Ref:  #81427

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
Emm... I think this is the opposite direction.
Ref: https://github.com/kubernetes/kubernetes/issues/76206
/cc  @andrewsykim @oomichi

**Comment by oomichi** [comment]
@SataQiu 
> Emm... I think this is the opposite direction.

Yeah, I can see your feeling.
It is better to move minimum functions into e2e core framework from subpackages if necessary.
I don't want to see swing pendulum between the core framework and subpackages..

**Comment by clarklee92** [comment]
> @SataQiu
> 
> > Emm... I think this is the opposite direction.
> 
> Yeah, I can see your feeling.
> It is better to move minimum functions into e2e core framework from subpackages if necessary.
> I don't want to see swinging pendulum between the core framework and subpackages..

Yes, I also don't like the way both sides are called. Currently, if we want to break the `framework`'s dependence on SSH subpackages, we need to copy almost all the functions which means minimum makes no sense. 
My suggestion is to move the subpackage `ssh` and use it as a tool under the framework. The reason why I did not remove the subpackage completely is that the `metric` subpackage cannot import the framework for the time being (because of loop dependence).

**Review by alejandrox1 — COMMENTED** [review]
Cleaning up dependencies as per  #81427 is important work but we shouldn't undue good work that has gone into refactoring the e2e test framework.
If this PR was to be merged, it would indeed reduce the dependence of the framework on one of its subpackages but ultimately we would have to move all ssh-related functions out of the framework, reverting a lot of the work that has been done here.

The way forward would be to refactor/clean up the places where e2essh is called within the framework.
For example, one of the places is this func:
```go
func getMasterUsageByPrefix(prefix string) (string, error) {
    sshResult, err := e2essh.SSH(...)
    ....
}
```
Instead of moving `e2e.SSH()` into the framework we should refactor or move `getMasterUsageByPrefix()` out of the framework (maybe into a subpackage or into the test pkg that calls it).

/priority important-longterm

**Comment by BenTheElder** [comment]
would prefer we stop using ssh entirely, generally a hostexec pod should be possible and doesn't require special provider magic, pure k8s...

**Comment by BenTheElder** [comment]
> So we cannot replace all e2essh due to NonSchedulable master node in general, but it is nice to replace as possible to avoid special provider magic.

I don't think we should have SSH to "master node" either and I'm suspicious of tests actually needing it. Can you elaborate?

**Comment by oomichi** [comment]
@BenTheElder 
> I don't think we should have SSH to "master node" either and I'm suspicious of tests actually needing it. Can you elaborate?

I also was surprised due to that based on current code.
But current code does, for example: https://github.com/kubernetes/kubernetes/blob/e865c0b21945ca1ad0792e89c13bf9ed074a3806/test/e2e/framework/resource_usage_gatherer.go#L567-L573

That is only for Kubemark. I am not sure the situation of Kubemark TBH today.

**Comment by BenTheElder** [comment]
i'm pretty sure that is not critical to test functionality, and further is a remnant of some GCP clusters having master <-> node ssh available (?)

cc @cheftako

**Comment by cheftako** [comment]
> i'm pretty sure that is not critical to test functionality, and further is a remnant of some GCP clusters having master <-> node ssh available (?)
> 
> cc Walter Fender

The test @oomichi points out does not look to be part of the SSH Tunnels code (which is deprecated and we are actively working on getting rid of).
I would have been surprised if we need more ssh in tests for the SSH Tunnel as the master code already has code for tunneling to the nodes.
It looks to me to be part of some resource/performance gathering utility. 
I think it probably should be replaced with some sort of hostexec pod.

**Pull request closed without merging**
