### PR TITLE
Delete deprecated NodePhase

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Find that Node Phase is still shown (as empty) in `kubectl describe node` result. Since Node Phase is deprecated and no longer used, we should delete it. I think maybe it's also time to delete the field in API completely and discourage client to patch NodeStatus with NodePhase.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
ref: https://github.com/kubernetes/kubernetes/pull/30005 , https://github.com/kubernetes/kubernetes.github.io/pull/549

**Release note**:

```release-note
None
```

@bgrant0607 @dchen1107 @mwhooker

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/sig-node-api-reviews

**Comment by bgrant0607** [comment]
https://kubernetes.io/docs/home/deprecation-policy/

**Comment by xiangpengzhao** [comment]
@bgrant0607 Thanks Brian!

>As with whole REST resources, an individual field which was present in API v1 must exist and function until API v1 is removed.

According to the policy and current API version, seems like the deprecated `NodePhase` should be kept for a very long term, right? Feel free to close this PR if so:)

However, I still prefer to remove [Phase](https://github.com/kubernetes/kubernetes/pull/44388/files#diff-b6046cf9a49c5cec609fe53ba861940dL2037) in `kubectl describe node` result. Will create a small PR.

**Comment by bgrant0607** [comment]
@xiangpengzhao Correct.

**Pull request closed without merging**
