### PR TITLE
verify-golangci-lint.sh: support arbitrary GOBIN

### LINKED ISSUE #117831: logcheck doesn't work with dockerized build
### What happened?

This is a subset of "make verify doesn't work under build/run.sh anymore" xref: https://github.com/kubernetes/kubernetes/issues/117821

In two places we assume the path for "local builds"
https://github.com/kubernetes/kubernetes/blob/ace6a79372113b8d850a58cdba740cdef4bc10ee/hack/golangci.yaml#L42

https://github.com/kubernetes/kubernetes/blob/ace6a79372113b8d850a58cdba740cdef4bc10ee/hack/golangci-strict.yaml#L41

But when dockerized it will be at `_output/dockerized/bin/logcheck.so`

### What did you expect to happen?

`build/run.sh make verify WHAT=golangci-lint` should work.

### How can we reproduce it (as minimally and precisely as possible)?

`build/run.sh make verify WHAT=golangci-lint`

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

The in-tree configs use a relative path to find logcheck.so. This is useful because then the invocation of golangci-lint also works outside of the script. But when running with a containerized build, GOBIN points somewhere else. For that case, a temporary copy of the configuration has to be created with an absolute path.

#### Which issue(s) this PR fixes:
Fixes #117831

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Works with and without containers:
```console
$ hack/verify-golangci-lint.sh 
go version go1.21.3 linux/amd64
installing golangci-lint and logcheck plugin from hack/tools into /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin
running env LOGCHECK_CONFIG=/nvme/gopath/src/k8s.io/kubernetes/hack/logcheck.conf /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin/golangci-lint run --color=always --config=/nvme/gopath/src/k8s.io/kubernetes/hack/golangci.yaml ./...
...
$ build/run.sh make verify WHAT=golangci-lint
+++ [1025 09:40:12] Verifying Prerequisites....
+++ [1025 09:40:13] Building Docker image kube-build:build-4c1617df56-5-v1.29.0-go1.21.3-bullseye.0
+++ [1025 09:43:17] Syncing sources to container
+++ [1025 09:43:19] Output from this container will be rsynced out upon completion. Set KUBE_RUN_COPY_OUTPUT=n to disable.
+++ [1025 09:43:19] Running build command...
Verifying verify-golangci-lint.sh

+++ Running case: verify.golangci-lint 
+++ working dir: /go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-golangci-lint.sh"
installing golangci-lint and logcheck plugin from hack/tools into /go/src/k8s.io/kubernetes/_output/dockerized/bin
go: downloading github.com/golangci/golangci-lint v1.54.1
...
go: downloading sigs.k8s.io/logtools v0.5.0
running env LOGCHECK_CONFIG=/go/src/k8s.io/kubernetes/hack/logcheck.conf /go/src/k8s.io/kubernetes/_output/dockerized/bin/golangci-lint run --color=always --config=/tmp.k8s/tmp.gR7k5rPu1W/golangci.yaml ./...
running ( cd /go/src/k8s.io/kubernetes/staging/src/k8s.io/api; env LOGCHECK_CONFIG=/go/src/k8s.io/kubernetes/hack/logcheck.conf /go/src/k8s.io/kubernetes/_output/dockerized/bin/golangci-lint run --color=always --config=/tmp.k8s/tmp.gR7k5rPu1W/golangci.yaml --path-prefix staging/src/k8s.io/api ./... )
...
```

**Comment by pohly** [comment]
/hold

For approval by a second approver.

/cc @BenTheElder

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
Thanks Patrick!

**Pull request merged**
