### PR TITLE
Added a support for system-z architecture by adding system-z host

### PR DESCRIPTION
**Pull request by gajju26**
Added a support for system-z architecture by adding system-z host
architecture name as s390x in the switch case.

### CODE REVIEW

**Comment by ixdy** [comment]
@gajju26 please sign the CLA as requested. Thanks!

**Comment by gajju26** [comment]
@ixdy I'm working for IBM and covered as part of Google Corporate CLA (my id has been added as graut.ibm@gmail.com). Please let me know if there is any additional info required.

**Comment by ixdy** [comment]
Great, thanks for getting the CLA stuff worked out.

There are a few other locations which case on the machine type (just searching for `uname -m`):
hack/local-up-cluster.sh
cluster/get-kube.sh
cluster/kubectl.sh

It'd probably be worth updating those, too. Thanks!

**Comment by gajju26** [comment]
@ixdy   as per review comment I have changed the following files for to support system-z architecture.
hack/local-up-cluster.sh
 cluster/get-kube.sh
 cluster/kubectl.sh

**Comment by ixdy** [comment]
lgtm
ok to test

**Comment by ixdy** [comment]
@gajju26 can you please squash your two commits into one?

**Comment by gajju26** [comment]
@ixdy I have squashed two commits into one. Thanks!!!!

**Comment by ixdy** [comment]
@gajju26 hmm, I'm not sure what happened, but now there appear to be 4 commits in your pull request, rather than 2 or 1.

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit is a pretty useful guide I just found that explains how to use `git rebase -i` to squash commits.

**Comment by gajju26** [comment]
@ixdy I have squashed two commits into one. Thanks!!!!

**Comment by ixdy** [comment]
LGTM, thanks!

**Comment by ixdy** [comment]
@k8s-bot e2e test this

**Pull request merged**
