### PR TITLE
fix typo in staging/src/k8s.io/apiserver/plugin/pkg/audit/doc.go

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**: Fix a typo in the document file staging/src/k8s.io/apiserver/plugin/pkg/audit/doc.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: This is my first PR on k8s, looking forward to contributing more on this project in the future.

**Release note**:

`NONE`

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by CaoShuFeng** [comment]
This test always fails.
Maybe we can rebase it?

**Comment by huangjiuyuan** [comment]
Hi, @CaoShuFeng 
Thank you for your advice, I have rebased this commit and pushed again.

**Pull request closed without merging**
