### PR TITLE
node: e2e device plugin test improvements

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup
/kind flake

#### What this PR does / why we need it:
Improve e2e_node device plugin test which also started to flake lately (but their flakiness is still under control atm. Nevertheless, let's try to improve!)

The goal is to modernize these old tests a bit, make the intent more explicit and add stricter checks using facilities introduced after the tests were first written (e.g. podresources API)

#### Which issue(s) this PR fixes:
Fixes #N/A

#### Special notes for your reviewer:
Spawn from and prerequisite to get #116376 merged

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
N/A
```

### CODE REVIEW

**Comment by ffromani** [comment]
The PR is now complete and ready for review

**Comment by ffromani** [comment]
serial-crio-cgroup-v1 failure not relevant:
```
E2eNode Suite: [It] [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should correctly account for terminated pods after restart 
```

**Comment by ffromani** [comment]
`node-kubelet-serial-containerd` failure unrelated: ```
E2eNode  Suite: [It] [sig-node] Density [Serial] [Slow] create a batch of pods  latency/resource should be within limit when create 10 pods with 0s  interva | E2eNode  Suite: [It] [sig-node] Density [Serial] [Slow] create a batch of pods  
````

**Comment by ffromani** [comment]
`node-kubelet-serial-crio-groupv2` again fails for unrelated reasons:
```
E2eNode Suite: [It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
````

Peeking into the prow logs we see the tests changed in this PR actually runs and pass.

**Comment by ffromani** [comment]
ok, hitting a known issue here at least in the cgroupv2 lane: https://github.com/kubernetes/kubernetes/issues/116872

Retrying one last time, otherwise we're just wasting cycles

**Comment by ffromani** [comment]
> ok, hitting a known issue here at least in the cgroupv2 lane: #116872
> 
> Retrying one last time, otherwise we're just wasting cycles

htting this pretty regularly on both crio lanes. Full disclosure: getting also other unrelated failures e.g. `Garbage Collection Test: Many Pods with Many Restarting Containers Should eventually garbage collect containers when we exceed the number of dead containers per container expand_more`

cc @SergeyKanzhelev @mrunalp

**Review by mrunalp — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
/skip

as per comments above

**Pull request merged**
