### PR TITLE
Adding cert and basic auth files for federation-apiserver

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/26731

cc @kubernetes/sig-cluster-federation @madhusudancs @colhom

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30673)

### CODE REVIEW

**Comment by madhusudancs** [comment]
@nikhiljindal I guess you are already aware of this since you are one of the assigned reviewers, but just drawing your attention - PR #30615. Also, I do not want to block this PR, but I just want to give you a heads-up. I am going to rip out all the shell scripts that the initialization code implements to avoid having multiple competing implementations in our repo. My plan is to leave the shell scripts as is in 1.4 to whet the new code a bit and remove them in 1.5 time frame.

**Comment by madhusudancs** [comment]
@nikhiljindal based on our offline discussion and to unblock you from accessing swagger spec, I have reviewed this PR. A couple of minor nits, then please feel free to add the LGTM label yourself.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[cluster/common.sh, line 854 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30673#-KPKEGCkMjnye-lfTTGf:-KPKEGCkMjnye-lfTTGg:b-cgyn03) ([raw file](https://github.com/kubernetes/kubernetes/blob/6e5c02d0dff842bca804fb779a2b573c8b3b6f9c/cluster/common.sh#L854)):*
> ```Shell
>   }
> }
> ```

Unnecessary blank line here.

---

*[federation/cluster/common.sh, line 248 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30673#-KPKDVIEqQlmQBKzkR0A:-KPKDVIEqQlmQBKzkR0B:bbpzeup) ([raw file](https://github.com/kubernetes/kubernetes/blob/6e5c02d0dff842bca804fb779a2b573c8b3b6f9c/federation/cluster/common.sh#L248)):*
> ```Shell
> 
>   local kube_temp="${KUBE_TEMP}/federation"
>   mkdir "${kube_temp}"
> ```

you need `mkdir -p` for safety (or handle error).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30673#-:-KPKFzlxLyuu0g08NKUK:bl1ri7z)*

**Comment by nikhiljindal** [comment]
Thanks @madhusudancs 
Yes sorry for missing https://github.com/kubernetes/kubernetes/pull/30615.
It will be cool to convert the shell script code to Go! Didnt realize that we were going to do that in 1.4!

I have updated the code as per comments.
Also updated the code to generate a valid random password (reused existing function that generates kube password) rather than using "admin".
Thanks!

**Comment by madhusudancs** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30673)*

**Comment by madhusudancs** [comment]
LGTM!

**Comment by nikhiljindal** [comment]
Updated hack/verify-flags/exceptions.txt to fix hack/verify-flags-underscore.py

**Comment by eparis** [comment]
what makes this a p1?

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this issue: https://github.com/kubernetes/kubernetes/issues/30754

**Pull request merged**
