### PR TITLE
Remove experimental keystone authenticator

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

experimental-keystone-url and experimental-keystone-ca-file were always
experimental. So we don't need a deprecation period.
KeystoneAuthenticator was on the server side and needed userid/password
to be passed in and used that to authenticate with Keystone. We now
have authentication and authorization web hooks that can be used. There
is a external repo with a webook for keystone which works fine along
with the kubectl auth provider that was added in:
a0cebcb559c5c0ab8a2e50b1ee11cc62f9ebb3a8

So we don't need this older style / hard coded / experimental code
anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
kube-apiserver: the experimental in-tree Keystone password authenticator has been removed in favor of extensions that enable use of Keystone tokens.
```

### CODE REVIEW

**Comment by dims** [comment]
fyi https://cloudblog.switch.ch/author/zioproto/

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-pr-reviews

**Comment by liggitt** [comment]
I'm in favor of removing this and pointing people to the openstack kubectl auth provider and webhook authenticators.

That said, it looks like https://github.com/kubernetes/kubernetes/pull/39587 was not documented properly. @dims, can you open a documentation pull request against https://kubernetes.io/docs/admin/authentication/ removing the keystone password section, and adding a subsection under "Webhook Token Authentication" that details configuration of kubectl with the openstack auth provider?

**Comment by dims** [comment]
@liggitt i opened a WIP PR so i remember to do this - https://github.com/kubernetes/website/pull/7304

**Comment by dims** [comment]
@liggitt i'll be moving the personal repo into a git repo in the OpenStack foundation, so there's a pre-req before i wrap up the documentation PR. so it has the right info

**Comment by liggitt** [comment]
> i'll be moving the personal repo into a git repo in the OpenStack foundation, so there's a pre-req before i wrap up the documentation PR. so it has the right info

the kubectl side should be documented now.

your webhook authenticator is one possible option for turning keystone tokens into userinfo, and could be referenced as an example, without being positioned as the one true keystone webhook token authenticator (even once it is in the openstack foundation, alternative user mappings could be achieved through alternate webhooks)

**Comment by dims** [comment]
@liggitt got it!

**Comment by ericchiang** [comment]
Is this targeted for 1.10?

**Comment by liggitt** [comment]
cc @kubernetes/sig-openstack-pr-reviews

**Review by anguslees — APPROVED** [review]
/lgtm

Good to see this gone...

**Pull request merged**
