### PR TITLE
Update golang.org/doc/ to go.dev/doc/.

### PR DESCRIPTION
**Pull request by yanghesong**
Signed-off-by: yanghesong <hesong.yang@foxmail.com>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
https://golang.org/doc/ was not access in some areas, such as China, but the URL https://go.dev/doc/ can be accessed.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by yanghesong** [comment]
> If you still need this PR then please rebase, if not, please close the PR

Done.

**Review by brianpursley — CHANGES_REQUESTED** [review]
It appears you have mistakenly created two empty files:
* staging/src/k8s.io/kubectl/pkg/apply/element.go
* staging/src/k8s.io/kubectl/pkg/apply/parse/item.go

Please remove these files.

**Comment by yanghesong** [comment]
> It appears you have mistakenly created two empty files:
> 
> * staging/src/k8s.io/kubectl/pkg/apply/element.go
> * staging/src/k8s.io/kubectl/pkg/apply/parse/item.go
> 
> Please remove these files.

Thanks!
Done.

**Pull request closed without merging**
