### PR TITLE
Update cri-tools to v1.20.0

### PR DESCRIPTION
**Pull request by rajibmitra**
Signed-off-by: rajibmitra <rajib.jolite@gmail.com>

**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:
This updates cri-tools to the latest release[ v1.20.0](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.20.0)
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update cri-tools to [v1.20.0](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.20.0)
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Thanks!
/approve
(for `build/`)

**Comment by justaugustus** [comment]
For `cluster/gce/gci/`:
/assign @dchen1107 @yguo0905 @cheftako

**Pull request merged**
