### PR TITLE
cleanup: delete unnacessary nil check before range

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In golang, range for nil slice or map will generate no loop, so the nil check is not necessary at all.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks

/lgtm
/ok-to-test
/priority backlog

**Comment by neolit123** [comment]
@beautytiger hi, please take a look at the bazel-test and bazel-build failures above.

**Comment by tanjunchen** [comment]
/hold 
for ci

**Review by SataQiu — APPROVED** [review]
Thanks @beautytiger !
/lgtm
/approve
/hold cancel

**Comment by SataQiu** [comment]
Ref: #87807
/test pull-kubernetes-verify

**Pull request merged**
