### PR TITLE
Automated cherry pick of #102882: devicemanager: checkpoint: support pre-1.20 data

### PR DESCRIPTION
**Pull request by ffromani**
Cherry pick of #102882 on release-1.20.

#102882: devicemanager: checkpoint: support pre-1.20 data

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a regression in 1.20 where the kubelet cannot read devicemanager checkpoint data persisted by a 1.19 kubelet
```

### CODE REVIEW

**Comment by fromanirh** [comment]
/hold
I'll most likely need to backport some missing utilities

**Comment by fromanirh** [comment]
verified the (reduced version of) e2e tests locally on BM - the serial lane doesn't have multi-NUMA, SRIOV-enabled machines.

**Comment by fromanirh** [comment]
FYI @endocrimes @klueska @swatisehgal

**Comment by klueska** [comment]
So the "core" code changes cherry-picked cleanly, but you needed to patch up the e2e tests with some extra commits? or did you have to also tweak the first commit in this chain to resolve some conflicts?

**Comment by fromanirh** [comment]
> So the "core" code changes cherry-picked cleanly, but you needed to patch up the e2e tests with some extra commits? or did you have to also tweak the first commit in this chain to resolve some conflicts?

the core code changes got it relatively cleanly. The lion's share of the changes and extra work went into the e2e tests. I'd still be kindly requesting/happy with a deep review, because the 1.20 branch is in deep maintenance mode and I'd love to contribute positively to the stability of the branch.

Note: I'm aware I'm asking quite a lot here, still I believe this backport is worth because it _silently_ breaks the devicemanager flow on upgrades.

**Review by endocrimes — APPROVED** [review]
/lgtm

this is a _slightly_ riskier backport but imo worth it to de-risk upgrades for folks.

**Comment by puerco** [comment]
Thank you for providing context around the changes and the extra commit @fromanirh 
/lgtm

**Pull request merged**
