### PR TITLE
Use errors.Errorf instead of errors.Wrapf when the err is nil

### PR DESCRIPTION
**Pull request by navist2020**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
Use `errors.Errorf` instead of `errors.Wrapf` when the err is nil.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Can you reproduce a problem with this? It seems to be dead code.

/lgtm
/assign @fabriziopandini

**Review by binacs — COMMENTED** [review]
Perhaps we should use `errors` instead of `github.com/pkg/errors`. More at https://github.com/kubernetes/kubernetes/issues/103043

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/ok-to-test

using pkg/errors in kubeadm is fine.

**Comment by navist2020** [comment]
> Can you reproduce a problem with this? It seems to be dead code.
> 
> /lgtm
> /assign @fabriziopandini

Hi @pacoxu. I cant reproduce this problem. I am just learning code and find this problem.

**Pull request merged**
