### PR TITLE
Update images, dependencies and version to Go 1.19.1

### PR DESCRIPTION
**Pull request by palnabarun**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- Bump kube-cross, go-runner image to Go 1.19.1 based ones
- Bump test Makefile to Go 1.19.1
- Bump default go version for publishing bot to 1.19.1

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/2658

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Go 1.19.1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

/sig release
/cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by palnabarun** [comment]
**Note:** The PR should be merged only after the relevant images have been promoted. The tests would fail before that.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
