### PR TITLE
Automated cherry pick of #32587

### PR DESCRIPTION
**Pull request by mbohlool**
Cherry pick of #32587 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32721)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Once #32587 was approved for cherrypick, do-not-merge label will be removed here by bot. Thanks for the fix.

**Comment by mbohlool** [comment]
Is there anything else I need to do for this PR?

**Comment by mbohlool** [comment]
look like it is merged in batch PR  #32800  There should be an automated way to close this PR after it is merged in a batched PR.

**Pull request closed without merging**
