### PR TITLE
Add crds as CustomResourceDefinition shortname

### PR DESCRIPTION
**Pull request by nikhita**
See https://github.com/kubernetes/apiextensions-apiserver/issues/6#issuecomment-361539766.
Fixes kubernetes/apiextensions-apiserver#6

Before:

```
➜  kubectl get crds
the server doesn't have a resource type "crds"
```

After:

```
➜  kubectl get crds
No resources found.
```

**Release note**:

```release-note
 `crds` is added as a shortname for CustomResourceDefinition i.e. `kubectl get crds` can now be used.
```

/cc sttts deads2k soltysh pwittrock

### CODE REVIEW

**Comment by nikhita** [comment]
@kubernetes/sig-cli-api-reviews

**Comment by sttts** [comment]
@kubernetes/sig-api-machinery-api-reviews

**Comment by sttts** [comment]
Discuessed in https://github.com/kubernetes/apiextensions-apiserver/issues/6.

Would add a release note.

/approve

**Comment by nikhita** [comment]
> Would add a release note.

Added. ptal.

**Pull request merged**
