### PR TITLE
Release 1.2 cherrypick batch 16/3 morning

### PR DESCRIPTION
**Pull request by eparis**
#22921: Fix job selector validation and tests
#23037: Updated documentation about monitoring addons

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. Perhaps could have used the automatic cherrypick script for this one, but last time I tried it, it didn't work for me, and I haven't had time to figure it out.

LGTM

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by eparis** [comment]
I'll try to pick something today and see how the script holds up, since after today I think we should go back to asking people to do their own....

**Comment by bgrant0607** [comment]
Green, merging.

**Pull request merged**
