### PR TITLE
remove unused code when build garbageCollector 

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fixup of https://github.com/kubernetes/kubernetes/pull/125814

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/triage accepted
/assign @thockin

### CODE REVIEW

**Comment by kolyshkin** [comment]
These two commits should be squashed, otherwise git-bisect is broken.

**Comment by thockin** [comment]
We have terrible commit-hygiene - this is unfortunately a side-effect of lots of past decisions wrt generated code.

/label tide/merge-method-squash

**Pull request merged**
