### PR TITLE
remove legacy insecure port options from genericapiserver

### PR DESCRIPTION
**Pull request by deads2k**
The insecure port has been a source of problems and it will prevent proper aggregation into a cluster, so the genericapiserver has no need for it.  In addition, there's no reason for it to be in the main kube-apiserver flow either.  This pull removes it from genericapiserver and removes it from the shared kube-apiserver code.  It's still wired up in the command, but its no longer possible for someone to mess up and start using in mainline code.

@kubernetes/sig-api-machinery-misc @ncdc

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
waiting for https://github.com/kubernetes/kubernetes/pull/43383 to merge before re-tagging.

**Pull request merged**
