### PR TITLE
remove versioning interface

### PR DESCRIPTION
**Pull request by deads2k**
Builds on prior restmapping/converter separation to completely remove the versioning interface which isn't needed.

intersection of @kubernetes/sig-api-machinery-pr-reviews and @kubernetes/sig-cli-maintainers  again

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
/assign @soltysh 

cleans cruft that mostly hits cli

**Comment by deads2k** [comment]
prereqs merged.  rebased.  This is scrubbing the dead code.

**Comment by mfojtik** [comment]
/lgtm

looks like removing the dead code mostly.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
