### PR TITLE
Update list of migrated directories

### PR DESCRIPTION
**Pull request by serathius**
#### What type of PR is this?

Add more directories to list of directories migrated to structured logging.
Needed for https://github.com/kubernetes/kubernetes/issues/98976
/kind cleanup
/cc @ehashman 

Generated by passing list of all directories, running the validation and removing the failures.

```release-note
NONE
```

### CODE REVIEW

**Comment by serathius** [comment]
Updated directories to cover subdirectories.

**Comment by serathius** [comment]
Directories still needed to be migrated:
```
pkg/kubelet/cadvisor/...
pkg/kubelet/cm/...
pkg/kubelet/config/...
pkg/kubelet/container/...
pkg/kubelet/cri/...
pkg/kubelet/images/...
pkg/kubelet/kubeletconfig/...
pkg/kubelet/kuberuntime/...
pkg/kubelet/logs/...
pkg/kubelet/nodeshutdown/...
pkg/kubelet/preemption/...
pkg/kubelet/prober/...
pkg/kubelet/status/...
pkg/kubelet/volumemanager/...
pkg/kubelet/winstats/...
```

**Comment by ehashman** [comment]
note for the next one of these: need to include `cmd/kubelet` too :)

**Pull request merged**
