### PR TITLE
[WIP] Updating ghodss/yaml  and gopkg.in/yaml.v2 to latest version

### LINKED ISSUE #67477: duplicate container volumeMounts not validated
I accidentally included a duplicate `volumeMounts:` line below, and validation did not fail. I expected this to fail:

```
apiVersion: v1
kind: Pod
metadata:
  name: bugtest
spec:
  restartPolicy: Never
  containers:
    - image: debian:stretch
      name: rbd-rw
      command: ["bash", "-c", "cat /proc/mounts | grep /mnt"]
      volumeMounts:
      - name: foo
        mountPath: /mnt/foo
      volumeMounts:
      - name: bar
        mountPath: /mnt/bar
  volumes:
    - name: foo
      emptyDir: {}
    - name: bar
      emptyDir: {}
```

But nope, no error on apply, and only one of the volumes shows up:

```
dev:~ $ kubectl apply -f test.yaml
pod/bugtest created
dev:~ $ kubectl logs bugtest
/dev/mapper/debvg-root /mnt/bar ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
```

Reproduced with client+server Kubernetes 1.11.2, and also with the kubectl client at git tip (cffa2aed0e4f3a3723d1cf977e3386dbeb1aa046):

```
dev:~ $ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"devel +015873c153 Mon Aug 13 04:48:19 2018 +0000", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Do we just need to set the YAML package's [Decoder.SetStrict](https://godoc.org/gopkg.in/yaml.v2#Decoder.SetStrict) to true?

I see no references to SetStrict in the git repo.

Will investigate later. Filing before I forget.

/cc @lavalamp

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I63ceeb4622d759fb68e5ff8065f47890e8ee09c5

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67477

**Special notes for your reviewer**:

**Release note**:

```release-note
Update to latest code in ghodss/yaml. New code implements stricter yaml parsing to catch duplicate elements.
```

### CODE REVIEW

**Comment by cblecker** [comment]
Dep bump with no licence changes.
/approve

@dims is the release note needed for this one? Is the difference in yaml parsing that significant? If so, is our test coverage good enough to ensure we don't have regressions?

**Comment by nikhita** [comment]
/sig api-machinery


The last update of this package was 3 years ago (https://github.com/kubernetes/kubernetes/pull/13702). If this had a number of harmless additions (to be caught by tests) and numerous bug fixes, we should update this. :+1:

**Comment by dims** [comment]
/hold

testing

**Comment by dims** [comment]
Looks like just updating to newest repos for the 2 packages is not enough... i needed the following patch to recreate the `kubectl apply -f ~/test.yaml` scenario mentioned here : https://github.com/kubernetes/kubernetes/issues/67477#issuecomment-413618811

```
[dims@dims-mac 17:12] ~/go/src/k8s.io/kubernetes ⟩ git diff
diff --git a/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go b/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
index 3cd85515d4..ffce5edfd8 100644
--- a/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
+++ b/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
@@ -69,7 +69,7 @@ func (d *YAMLToJSONDecoder) Decode(into interface{}) error {
        }

        if len(bytes) != 0 {
-               err := yaml.Unmarshal(bytes, into)
+               err := yaml.UnmarshalStrict(bytes, into)
                if err != nil {
                        return YAMLSyntaxError{err}
                }
diff --git a/vendor/github.com/ghodss/yaml/yaml.go b/vendor/github.com/ghodss/yaml/yaml.go
index 6e7f14fc7f..c21bbb5efd 100644
--- a/vendor/github.com/ghodss/yaml/yaml.go
+++ b/vendor/github.com/ghodss/yaml/yaml.go
@@ -32,9 +32,20 @@ type JSONOpt func(*json.Decoder) *json.Decoder

 // Unmarshal converts YAML to JSON then uses JSON to unmarshal into an object,
 // optionally configuring the behavior of the JSON unmarshal.
+// For strict decoding, use UnmarshalStrict.
 func Unmarshal(y []byte, o interface{}, opts ...JSONOpt) error {
+       return unmarshal(y, o, yaml.Unmarshal, opts...)
+}
+
+// UnmarshalStrict is like Unmarshal but enables strict YAML decoding,
+// returning an error on any duplicate field names.
+func UnmarshalStrict(y []byte, o interface{}, opts ...JSONOpt) error {
+       return unmarshal(y, o, yaml.UnmarshalStrict, opts...)
+}
+
+func unmarshal(y []byte, o interface{},yamlUnmarshal func([]byte, interface{}) error, opts ...JSONOpt) error {
        vo := reflect.ValueOf(o)
-       j, err := yamlToJSON(y, &vo, yaml.Unmarshal)
+       j, err := yamlToJSON(y, &vo, yamlUnmarshal)
        if err != nil {
                return fmt.Errorf("error converting YAML to JSON: %v", err)
        }
```

**Comment by dims** [comment]
I've logged https://github.com/ghodss/yaml/pull/37

**Comment by liggitt** [comment]
I agree that duplicate elements overwriting  earlier fields is confusing and not desirable. However, tightening existing behavior also has the potential to break things that are currently working,  so the bar is generally very high for changing things like this, and we need to enumerate what components this changes behavior for. 

* Are there working manifests this will break  or cause to be rejected?
* Will they be rejected by client side behavior, or server-side behavior?

**Comment by dims** [comment]
Looks like https://github.com/ghodss/yaml/pull/36 is in progress, so i closed out mine

**Comment by dims** [comment]
@liggitt ack. will try to answer those questions once i have it working and can kick the tires so to say.

**Comment by dims** [comment]
will revisit when https://github.com/ghodss/yaml/pull/38 gets merged

**Comment by dims** [comment]
Will need to resurrect just a bit of stuff from here later in 1.14 possibly (for strict yaml parsing by default)

**Pull request closed without merging**
