### PR TITLE
Fix godeps

### PR DESCRIPTION
**Pull request by ncdc**
This should make godeps verification happy post #39448

### CODE REVIEW

**Comment by eparis** [comment]
@k8s-oncall this should unblock the queue. I will likely merge by hand after the test go green if someone else doesn't.

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by deads2k** [comment]
FAILED   hack/make-rules/../../hack/verify-bazel.sh	5s

**Comment by ncdc** [comment]
Working on it

**Comment by ncdc** [comment]
@k8s-bot unit test this

**Pull request merged**
