### PR TITLE
Remove unused code in e2e/framework/framework.go

### PR DESCRIPTION
**Pull request by llhuii**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by llhuii** [comment]
> @llhuii: The following tests **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-dependencies	[6ce868f](https://github.com/kubernetes/kubernetes/commit/6ce868fe93f2b0486ce38bce2a1c652ed399ace7)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99625/pull-kubernetes-dependencies/1366752016264597504)	`/test pull-kubernetes-dependencies`
> pull-kubernetes-verify	[6ce868f](https://github.com/kubernetes/kubernetes/commit/6ce868fe93f2b0486ce38bce2a1c652ed399ace7)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99625/pull-kubernetes-verify/1366752018714071040)	`/test pull-kubernetes-verify`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=99625). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Allhuii). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

```
Your vendored results are different:
diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/api/go.sum /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.Qfrqhe/kubernetes/vendor/k8s.io/api/go.sum
--- vendor/k8s.io/api/go.sum	2021-03-02 14:08:46.894721301 +0000
+++ /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.Qfrqhe/kubernetes/vendor/k8s.io/api/go.sum	2021-03-02 14:11:55.705876079 +0000
@@ -200,7 +200,6 @@ k8s.io/klog/v2 v2.0.0/go.mod h1:PBfzABfn
 k8s.io/klog/v2 v2.5.0 h1:8mOnjf1RmUPW6KRqQCfYSZq/K20Unmp3IhuZUhxl8KI=
 k8s.io/klog/v2 v2.5.0/go.mod h1:hy9LJ/NvuK+iVyP4Ehqva4HxZG/oXyIS3n3Jmire4Ec=
 k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd/go.mod h1:WOJ3KddDSol4tAGcJo0Tvi+dK12EcqSLqcWsryKMpfM=
-sigs.k8s.io/structured-merge-diff/v4 v4.0.2 h1:YHQV7Dajm86OuqnIR6zAelnDWBRjo+YhYV9PmGrh1s8=
 sigs.k8s.io/structured-merge-diff/v4 v4.0.2/go.mod h1:bJZC9H9iH24zzfZ/41RGcq60oK1F7G282QMXDPYydCw=
 sigs.k8s.io/structured-merge-diff/v4 v4.0.3 h1:4oyYo8NREp49LBBhKxEqCulFjg26rawYKrnCmg+Sr6c=
 sigs.k8s.io/structured-merge-diff/v4 v4.0.3/go.mod h1:bJZC9H9iH24zzfZ/41RGcq60oK1F7G282QMXDPYydCw=
```

too strange. It's ok to run my local vm.

**Comment by llhuii** [comment]
/retest
after pull and rebase the update master branch

**Review by neolit123 — COMMENTED** [review]
i don't recall what this did, but it's no longer being used.

/lgtm
/approve
/triage accepted

**Pull request merged**
