### PR TITLE
Unify code for List and GetToList for etcd and cacher

### PR DESCRIPTION
**Pull request by wojtek-t**
This is in preparation to merging those two also at the interface level.

```release-note
NONE
```

/kind cleanup
/priority important-longterm
/sig api-machinery

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @jpbetz 

Joe - would you help with reviewing this one too? :)

**Comment by wojtek-t** [comment]
/retest

@jpbetz - can you please help with reviewing?

**Comment by jpbetz** [comment]
I looked at this for a while and couldn't find anything wrong with it. Existing test coverage seems good to me.

/lgtm

**Pull request merged**
