### PR TITLE
Refactor util clock into it's own pkg

### PR DESCRIPTION
**Pull request by resouer**
Continue my work ref #15634

### CODE REVIEW

**Comment by resouer** [comment]
@yujuhong Fixed rebase

**Comment by resouer** [comment]
@k8s-bot e2e test this issue: #27451

**Comment by resouer** [comment]
@k8s-bot e2e test this issue: #27335

**Comment by resouer** [comment]
Fixed rebase again > <

**Comment by yujuhong** [comment]
@resouer too bad you'll need to rebase again :-(

Let's hope this is the last time since the queue is now open to all PRs.

**Comment by yujuhong** [comment]
ping?

**Comment by resouer** [comment]
Ah, sorry for miss this notification, will update this soon

**Comment by yujuhong** [comment]
Failed unit test ..

**Comment by yujuhong** [comment]
@resouer 
```
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/config	2.048s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util	2.667s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util/editor	1.024s
ok  	k8s.io/kubernetes/pkg/kubectl/resource	1.391s
FAIL	k8s.io/kubernetes/pkg/kubelet [build failed]
ok  	k8s.io/kubernetes/pkg/kubelet/client	1.173s
ok  	k8s.io/kubernetes/pkg/kubelet/cm	2.021s
ok  	k8s.io/kubernetes/pkg/kubelet/config	1.341s
ok  	k8s.io/kubernetes/pkg/kubelet/container	1.123s
```

The change looks good to me. Once you fix the build failure, I'll apply the label. Thanks!

**Comment by resouer** [comment]
i can not re-produce this failure by doing make test in local.  really don't know why ...

**Comment by yujuhong** [comment]
It's an easy fix :-)
From the build.log:
```
# k8s.io/kubernetes/pkg/kubelet
pkg/kubelet/kubelet_test.go:64: imported and not used: "k8s.io/kubernetes/pkg/util"
```

**Comment by resouer** [comment]
Aha, `pkg/util` is used in my commit, that's what I am struggling, but actually it has been removed in a latest commit, so CI will complain after it do rebase and why I can not reproduce it locally ...

**Pull request merged**
