### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Just a small fix which I encountered while following the docs.

_Just awaiting my manager to agree to the CLA._

### CODE REVIEW

**Comment by JanetKuo** [comment]
ok to test

**Comment by JanetKuo** [comment]
@k8s-bot ok to test

**Comment by JanetKuo** [comment]
@k8s-bot: ok to test

**Comment by wojtek-t** [comment]
@jacobtomlinson can you please sign the CLA and ping this thread after that?

**Comment by jacobtomlinson** [comment]
Just awaiting my manager to sign a corporate one. I'll ping it back shortly.

**Comment by jacobtomlinson** [comment]
I signed it! Corporation: Met Office Informatics Lab

**Comment by mikedanese** [comment]
This commit was made with an @jacobtomlinson.co.uk email address. Can you sign it for that email or for your github account?

**Comment by jacobtomlinson** [comment]
I updated the name on the commit, looks like I accidentally had my personal email in my git config.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by alex-mohr** [comment]
[Shippable reporting broken, but appears unrelated.  Re-running.]

**Comment by alex-mohr** [comment]
Thanks @jacobtomlinson !

**Pull request merged**
