### PR TITLE
Update heapster's combined googleinfluxdb version to 0.14.0.

### PR DESCRIPTION
**Pull request by a-robinson**
@vishh

### CODE REVIEW

**Comment by a-robinson** [comment]
Cribbed from #9615, maybe there was a reason this one wasn't included?

**Comment by vishh** [comment]
No. I missed this because the PR that introduced the combined one was still in flight.

**Comment by vishh** [comment]
LGTM

**Comment by a-robinson** [comment]
The minions in the MIG never even came up in the e2e failure, which shouldn't be affected by this. Was e2e flaky last night?

**Comment by vishh** [comment]
The e2e tests will not capture this change. So Its OK to ignore e2e failure.

**Pull request merged**
