### PR TITLE
Use Go 1.7.4 due to security fixes

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**: Golang released 1.7.4 with few security fixes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
- bump Go compiler to 1.7.4
```

### CODE REVIEW

**Comment by luxas** [comment]
cc @jessfraz @ixdy

**Comment by dims** [comment]
Looks like 2 changes went into 1.7.4:
https://github.com/golang/go/issues?q=milestone%3AGo1.7.4

**Comment by dims** [comment]
@kad @luxas - looking at the last bump to 1.7.3, looks like a test image had to be updated too
https://github.com/kubernetes/kubernetes/pull/35716/commits/64ac70bf34406009b8bb296032bdca932aed6fcc

**Comment by luxas** [comment]
@dims yes, and the patched golang version should also be updated

**Comment by kad** [comment]
@dims this part seems to be not present anymore in current master branch.

**Comment by jessfraz** [comment]
oh thanks I was going to do this, but you saved me!

**Comment by jessfraz** [comment]
did you also make the changes to https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.5

**Comment by ixdy** [comment]
should we also update the `K8S_PATCHED_GOLANG_VERSION` in the cross-build image? I'm not sure if @luxas' patches still apply/are still needed.

**Comment by jessfraz** [comment]
they are still needed afaik, but yeah that should be updated as well

**Comment by kad** [comment]
@jessfraz no, I didn't before but now there is new PR also for test infra: kubernetes/test-infra#1281

as for K8S_PATCHED_GOLANG_VERSION, I think it still needed, as 1.7.3->1.7.4 has only two fixes that are not related to issue. I'll check, probably update this PR soon.

**Comment by kad** [comment]
patches seems applicable. Updated PR.

**Comment by jessfraz** [comment]
ah I'll push the image

**Comment by jessfraz** [comment]
@k8s-bot test this #ignore

**Comment by jessfraz** [comment]
I pushed the image so most things should not fail now

**Comment by jessfraz** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
This PR has merge conflicts and caused the build to start failing (see https://github.com/kubernetes/kubernetes/pull/38035#issuecomment-264622936). I believe it might require https://github.com/kubernetes/kubernetes/pull/36964 to also be cherry picked.

Regardless, I will not cherry pick this PR in my batch cherry pick. @kad please prepare a separate cherry pick to the  release-1.5 branch. See "About Cherrypicks" section in https://groups.google.com/forum/#!topic/kubernetes-dev/mvIXrgEyHPY for help on merge conflicts.

**Comment by saad-ali** [comment]
> This PR has merge conflicts and caused the build to start failing (see #38035 (comment)). I believe it might require #36964 to also be cherry picked.
> 
> Regardless, I will not cherry pick this PR in my batch cherry pick. @kad please prepare a separate cherry pick to the release-1.5 branch. See "About Cherrypicks" section in https://groups.google.com/forum/#!topic/kubernetes-dev/mvIXrgEyHPY for help on merge conflicts.

I cherrypicked both PRs in: https://github.com/kubernetes/kubernetes/pull/38059

**Pull request merged**
