### PR TITLE
Wait for arc.getArchive() to complete before running tests

### PR DESCRIPTION
**Pull request by fejta**
Fixes https://github.com/kubernetes/kubernetes/issues/27104

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
`Jenkins GCE Node e2e` should succeed be green if fix works, right?

**Comment by fejta** [comment]
I'm not 100% sure... It didn't seem to fail previously?

**Comment by dchen1107** [comment]
Merge this to stop node pr build breakage issue.

**Comment by dchen1107** [comment]
Looks like the node e2e test still failed with the same reason here.

**Comment by dchen1107** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Comment by dchen1107** [comment]
This pr is pretty straightforward, which reverts partial of commit e94e1c6#diff-2cf4815674d337c5531ee1bbf343d97c based on @fejta's comment. Also the issue was introduced right after that commit. Meanwhile, we (@fejta and myself) think there might still be something weird happening with the client, Aka it is hard to tell what the base commit id is.

The pr has nothing to do with GCE e2e. I am manually merging it now.

**Pull request merged**
