### PR TITLE
discover valid resources for kubectl instead of current hard-coded way

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Per [discussion](https://github.com/kubernetes/kubernetes/pull/51089#issuecomment-326748956) and [discussion](https://github.com/kubernetes/kubernetes.github.io/pull/5260#discussion_r136697237).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
xref #51089

**Special notes for your reviewer**:
/assign @liggitt @caesarxuchao 

**Release note**:

```release-note
discover valid resources for kubectl instead of current hard-coded way
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
It's strange this PR doesn't have a release note label. Maybe bot is sleeping...

**Comment by xiangpengzhao** [comment]
Hmmm, my comment wakes it up.

**Comment by dixudx** [comment]
/assign @mengqiy

PTAL. Thanks.

**Comment by liggitt** [comment]
We cannot require server contact to display command help.  A separate command to display valid resources (like https://github.com/kubernetes/kubernetes/pull/42873) would be best, and we can reference that command from the help text

**Comment by liggitt** [comment]
Also, the factory is not usable for client building prior to command invocation (not all flags that affect server contact have not been parsed yet), and making calls in constructing the command mean those calls will be made for every invocation of kubectl that runs any command, not just this one.

**Comment by xiangpengzhao** [comment]
xref: #51324

**Pull request closed without merging**
