### PR TITLE
CHANGELOG/CHANGELOG-1.18.md: Fix spelling

### PR DESCRIPTION
**Pull request by sanmai-NL**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fix 'aggregation' spelling.

**Which issue(s) this PR fixes**:
Not applicable.

**Special notes for your reviewer**:
Not applicable.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by sanmai-NL** [comment]
/assign @justaugustus 
I've signed the CLA.

**Comment by justaugustus** [comment]
@sanmai-NL -- Please update the PR title, description, and description to describe what spelling you're fixing.

Example:
```
CHANGELOG/CHANGELOG-1.18.md: Fix spelling
```

ref: https://chris.beams.io/posts/git-commit/
/hold
/ok-to-test

**Comment by sanmai-NL** [comment]
/retest

All flakes.

**Comment by justaugustus** [comment]
@sanmai-NL -- Can you address my comment before sending this for retest: https://github.com/kubernetes/kubernetes/pull/87969#issuecomment-584995058

**Comment by sanmai-NL** [comment]
@justaugustus Will do. Why before?

**Comment by justaugustus** [comment]
> ... Why before?

@sanmai-NL -- because tests cost money :sweat_smile: 
Not a great answer especially since this is a markdown change, but I'm just trying to encourage good submission habits.

**Comment by sanmai-NL** [comment]
@justaugustus: Yeah, I figured that. Besides this only being a docs change, you only asked me to change some things that aren't altering the Git history, so tests wouldn't be re-run anyhow. May I propose you spend some time on limiting test runs to those that may be impacted by a change? This could save you CI budget if that's a limitation you're running into.

**Comment by sanmai-NL** [comment]
> @sanmai-NL: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

@justaugustus

**Comment by justaugustus** [comment]
@sanmai-NL -- Can you also update the commit message? My original message was supposed to mention that as well.

**Comment by justaugustus** [comment]
@sanmai-NL -- Did you have a chance to get back to this one?

**Comment by sanmai-NL** [comment]
Thanks for reminding. No, been too busy. Will try to fix today! If not close the PR and let your team make the typo fixes please. 🙂

**Comment by sanmai-NL** [comment]
@justaugustus: should be done now.

**Comment by justaugustus** [comment]
Thanks for the fix, @sanmai-NL (and sorry for the wait)!
/ok-to-test
/lgtm
/approve
/hold cancel

**Pull request merged**
