### PR TITLE
feat: use buffer for decoding

### PR DESCRIPTION
**Pull request by nilekhc**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by nilekhc** [comment]
https://github.com/kubernetes/kubernetes/pull/119167#issuecomment-1924647423

/close

**Pull request closed without merging**
