### PR TITLE
disable HTTP2 ingress test

### LINKED ISSUE #75186: [Failing test] gce-cos-<branch>-ingress are timing out
**Which jobs are failing**:
* [`ci-kubernetes-e2e-gci-gce-ingress`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/20602)
* [`ci-kubernetes-e2e-gce-cos-k8sbeta-ingress`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/6339)

**Which test(s) are failing**:
The jobs are timing out, but just before that, the following tests failed:
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes`
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should update ingress while sync failures occur on other ingresses`
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] should create NEGs for all ports with the Ingress annotation, and NEGs for the standalone annotation otherwise` (in `gce-cos-master-ingress`)
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes` (in `gce-cos-1.14-ingress`)

**Since when has it been failing**:
late 2019-03-07

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-ingress
* https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-ingress

**Reason for failure**:
Timeout related to the L7 controller:
```
error: L7 controller failed to delete all cloud resources on time. timed out waiting for the condition
```

/sig network
/priority critical-urgent (failing consistently in release blocking jobs, blocking other tests entirely from running)

cc @kubernetes/sig-network-test-failures 
cc @smourapina @alejandrox1 @kacole2 @mortent

### PR DESCRIPTION
**Pull request by freehan**
fix:  https://github.com/kubernetes/kubernetes/issues/75186
ref: https://github.com/kubernetes/ingress-gce/issues/675

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by MrHohn** [comment]
Will need milestone 1.14 for this PR to be merged.
cc @mariantalla

**Comment by mariantalla** [comment]
Thanks for the heads up @freehan @MrHohn . Have I understood this right? :
* the healthcheck endpoint of the gce loadbalancer api now returns type:http2
* however to gce go client (used by the tests?) does not yet support http2 object type
* => this PR is disabling the tests around ingress using http2
  * temporarily, until the vendored `google.golang.org/api/compute/v1` gets updated to the version that can support http2 type healthchecks.

If I got this right, makes sense for now; however is there an plan (e.g. an issue somewhere) to reintroduce the tests? Is this behaviour covered with e2e tests somewhere else?

**Comment by MrHohn** [comment]
Ref https://github.com/kubernetes/ingress-gce/issues/667.

As many of these ingress test cases are in fact GCP specific (e.g. HTTP2 isn't surfaced as a generic knob through Ingress API), it doesn't make much sense for them to present in k/k and block OSS release. It seems folks are working on porting these over and maintain them in k/ingress-gce instead.

**Comment by tpepper** [comment]
> Thanks for the heads up @freehan @MrHohn . Have I understood this right? :
> 
> * the healthcheck endpoint of the gce loadbalancer api now returns type:http2
> * however to gce go client (used by the tests?) does not yet support http2 object type
> * => this PR is disabling the tests around ingress using http2
>   
>   * temporarily, until the vendored `google.golang.org/api/compute/v1` gets updated to the version that can support http2 type healthchecks.
> 
> If I got this right, makes sense for now; however is there an plan (e.g. an issue somewhere) to reintroduce the tests? Is this behaviour covered with e2e tests somewhere else?

Summary like this would be very beneficial to have in the commit and PR description.

**Pull request merged**
