### PR TITLE
Fix resource requests in cassandra-daemonset.yaml

### PR DESCRIPTION
**Pull request by wfhartford**
The current file fails validation because the resource request syntax is incorrect.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26981)

### CODE REVIEW

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
ok to test

@apelisse @fejta @ixdy @rmmh Is there a way to (a) make those "ok to test" messages notify the assignee and (b) add a `needs-ok-to-test` label?

**Comment by bgrant0607** [comment]
@chrislovecnm Does this still need to be fixed, or can it be closed?

**Comment by ixdy** [comment]
@bgrant0607 not within the plugin itself, no. at least not without writing the Java to do so.

**Comment by apelisse** [comment]
@bgrant0607 Sorry for not acknowledging before, but this is definitely on my todo list. Because it's done through the plugin, it's not a "5 minutes fix" unfortunately. But yes, I will try to fix that somehow (as soon as I have time).

**Comment by chrislovecnm** [comment]
@bgrant0607 yes this should go through it is broken on master.

**Comment by jeffmendoza** [comment]
@wfhartford The Cassandra example moved to examples/storage/. Can you update the PR?

**Comment by chrislovecnm** [comment]
Also @wfhartford please update the docs https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/README.md#step-5-use-a-daemonset-instead-of-a-replication-controller

@jeffmendoza we gotta have that done as well.

**Comment by wfhartford** [comment]
I seem to have messed something up with the pull request when I rebased. Git is not my native language, sorry. Can anyone enlighten me on what I might have done wrong? If its easiest, I can just create a new PR.

**Comment by jeffmendoza** [comment]
Ah, looks like a merge, try "git rebase origin/master" assuming origin is the upstream repo.

**Comment by wfhartford** [comment]
That looks a little better. Thanks @jeffmendoza

**Comment by jeffmendoza** [comment]
LGTM

**Comment by chrislovecnm** [comment]
@jeffmendoza @smarterclayton @bprashanth this is also fixed via https://github.com/kubernetes/kubernetes/pull/30577 ... which one do we want in?

**Comment by bprashanth** [comment]
> which one do we want in?

Whichever gets in first

**Pull request merged**
