### PR TITLE
kubeadm: add OWNERS file

### PR DESCRIPTION
**Pull request by mikedanese**
I'm picking @luxas @errordeveloper and me as the initial code reviewers. Happy to add others

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33687)

### CODE REVIEW

**Comment by luxas** [comment]
Hah, nice!
I was just about to add exactly this file and send it as a PR

But seems like you were about a minute faster :smile:

LGTM for me, and I guess it's ok for @errordeveloper as well

**Comment by luxas** [comment]
Removing lgtm until @jbeda is added here.
Self-apply when ready

**Comment by jbeda** [comment]
I'm game! LGTM

**Comment by lavalamp** [comment]
thanks!

**Pull request merged**
