### PR TITLE
Ensure that only IPs are used as node addresses in OpenStack LBs

### LINKED ISSUE #64317: Only IPs should be used as node addresses for OpenStack LBs
/kind bug
/sig-openstack

**What happened**:
I observed a strange behaviour regarding LBaaS when creating a service and having nodes in the cluster that have no valid IP address configured. While it is expected, that no Loadbalancer can be created in such a situation, the error message that popped up in the controller was rather unhelpful:
```
error creating LB pool member for node: <node_name>, Invalid request due to incorrect syntax or missing required parameters.
```

The OpenStack logs showed the actual problem:
```
create failed (client error): Invalid input for address. Reason: '<node_hostname>' is not a valid IP address.
```

Investigation of the [relevant code](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L492)  revealed the issue here: Since the node had no valid IP address configured, the function returned the first address listed for the node, which was the hostname in this case. Of course, LBaaS can't create  a pool member based on the hostname of the node.

**What you expected to happen**:
Instead of logging a unhelpful message like `Invalid request due to incorrect syntax or missing required parameters`, the cloud provider should say what the actual issue was: No valid address could be found.

**Anything else we need to know?**:
Just to be clear: The node in this case had a working IP address & network configuration. Due to a botched Nova config change and [this issue](https://bugs.launchpad.net/nova/+bug/1751923), nova did no longer report the IP addresses of nodes.
Because of this, the node_controller removed all IP addresses from the node status.
This is of course expected, but a better error message might have helped to find the root cause of our issues faster.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10, but also applies to older versions
- Cloud provider or hardware configuration: OpenStack

### PR DESCRIPTION
**Pull request by gonzolino**
**What this PR does / why we need it**:
ATM, when no InternalIP can be found for a node, the openstack cloud provider tries to create a LB with whatever is the first address it can find for the node. This could also be the hostname or a dns name.
However, LBaaS will reject anything that is not an IP address for pool members. Therefore a meaningful error should be returned instead of just returning the first address of the node, even if it is clear that this will lead to an error in LBaaS.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64317

**Special notes for your reviewer**:

**Release note**:

```release-note
Provide a meaningful error message in openstack cloud provider when no valid IP address can be found for a node
```

### CODE REVIEW

**Review by dims — APPROVED** [review]

**Review by FengyunPan2 — APPROVED** [review]
/approve

**Pull request merged**
