### PR TITLE
Automated cherry pick of #96966: p&f e2e test: log response header for better troubleshooting

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #96966 on release-1.20.

#96966: p&f e2e test: log response header for better troubleshooting

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
/assign @MikeSpreitzer @lavalamp 
cc @BenTheElder

**Comment by tkashem** [comment]
- #103171 cherry-picks #96966 
- once 103171 merges, I will cherry-pick #96984

**Comment by tkashem** [comment]
taking over for https://github.com/kubernetes/kubernetes/pull/102709

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM

**Review by BenTheElder — APPROVED** [review]
LGTM

**Comment by puerco** [comment]
Thank you @tkashem 
/lgtm

**Comment by tkashem** [comment]
> once this PR merges, I will cherry-pick APF e2e test: wait for steady state before proceeding #96984

cherry picked 96984 - https://github.com/kubernetes/kubernetes/pull/103825

**Pull request merged**
