### PR TITLE
Remove Service Load Balancer Feature Gate

### LINKED ISSUE #94498: Feature gate ServiceLoadBalancerFinalizer is GA - when does it get removed?
When should it be removed?

@MrHohn 

/sig network
/kind cleanup

### PR DESCRIPTION
**Pull request by bbyrne5**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: 
Removes feature gate for the Service Load Balancer

**Which issue(s) this PR fixes**:

Fixes #94498

**Special notes for your reviewer**: 
Seems to pass all tests after just removing the gate.

**Does this PR introduce a user-facing change?**:

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks!
/lgtm
/approve

**Comment by dims** [comment]
/assign @liggitt 

quick one. removing a feature gate string

**Comment by liggitt** [comment]
/unassign

network approvers should ack this one

**Pull request merged**
