### PR TITLE
add test in create authinfo

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zjj2wry** [comment]
ping @deads2k mind for approver?

**Pull request merged**
