### PR TITLE
Automated cherry pick of #68422: Fix AWS NLB security group updates

### PR DESCRIPTION
**Pull request by M00nF1sh**
Cherry pick of #68422 on release-1.12.

#68422: Fix AWS NLB security group updates

Tests done:
1. created an kops cluster with [binaries built by this PR](https://storage.googleapis.com/kubernetes-release-pull/ci/pull-kubernetes-e2e-kops-aws/v1.12.5-beta.0.82+8063abb5de1b08)
2. verified the original issue as described in #68422 is gone.

### CODE REVIEW

**Comment by feiskyer** [comment]
/assign @justinsb 

@justinsb could you help to approve the cherry pick?

**Comment by d-nishi** [comment]
/lgtm @M00nF1sh @feiskyer 

I will get this closed in a day or two since I can't approve to close.

**Pull request merged**
