### PR TITLE
update strategic patch test for merge list of maps

### PR DESCRIPTION
**Pull request by adohe-zz**
Refer #26418 for more details. @janetkuo the test case is added, ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26510)

### CODE REVIEW

**Comment by AdoHe** [comment]
@janetkuo kindly ping.

**Comment by AdoHe** [comment]
@janetkuo kindly ping, ptal.

**Comment by AdoHe** [comment]
@janetkuo kindly ping. Is this test still necessary or I will close this pr?

**Comment by AdoHe** [comment]
@pwittrock would you please help with this one? Seem @janetkuo is quite busy.

**Comment by pwittrock** [comment]
@AdoHe Yes.  Sorry you were blocked for so long.

**Comment by pwittrock** [comment]
@k8s-bot e2e test this issue: #IGNORE Hung tests

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE Hung tests

**Pull request merged**
