### PR TITLE
metrics: make IMPLEMENTATIONS.md and CONTRIBUTING.md authorative in k/k

### PR DESCRIPTION
**Pull request by sttts**
Part of https://github.com/kubernetes/kubernetes/issues/57559.

### CODE REVIEW

**Comment by sttts** [comment]
/hold

until https://github.com/kubernetes/metrics/pull/15 is merged.

**Comment by DirectXMan12** [comment]
kubernetes/metrics#15 is merged.  Go ahead.

**Comment by spiffxp** [comment]
/lgtm
/hold cancel
will need an /approve from @DirectXMan12 or @piosz

**Pull request merged**
