### PR TITLE
fixing docker -d deprecation

### PR DESCRIPTION
**Pull request by aanm**
`docker -d` was removed on docker 1.10

I only did a grep "docker -d" in the repo. I hope there isn't a:

```
docker \
  -d
```

Signed-off-by: André Martins aanm90@gmail.com

### CODE REVIEW

**Comment by brendandburns** [comment]
When was `docker daemon` introduced?  We need to ensure compatability...

**Comment by dchen1107** [comment]
@aanm Thanks for the pr. @Random-Liu and I talked about this yesterday on removing -d option, including our containervm image too.

**Comment by dchen1107** [comment]
Compatibility check: docker daemon was fully introduced for docker 1.8, but it is compatible with docker 1.7 release which we haven't dropped the support yet. 

LGTM

**Comment by dchen1107** [comment]
@derekwaynecarr

**Comment by aanm** [comment]
@dchen1107 ah cool thanks for checking that out

**Comment by dchen1107** [comment]
My above compatibility check is wrong. There is a copy&paste error when I tested it: instead of passing "daemon", I passed "--daemon" as startup options for my docker daemon. 

Just verify it again, it is not compatible with docker 1.7 release. In this case, we have to detect docker version and pass different option based on the version.

**Comment by aanm** [comment]
The bash ones were easy. The `cluster/saltbase/salt/docker/docker.service` is more tricky. Any suggestions?

**Comment by luxas** [comment]
@aanm 
```
docker \
    -d 
```
is unfortunately fully possible. E.g. in `docker-multinode` scripts.

**Comment by aanm** [comment]
@dchen1107 docker was released today

**Comment by dchen1107** [comment]
@aanm Please fix the failure tests. Otherwise lgtm

**Comment by aanm** [comment]
@dchen1107 I've fix it but I'm still waiting to get some news from jenkins. What about getting the correct docker version under `cluster/saltbase/salt/docker/docker.service`?

**Comment by justinsb** [comment]
@k8s-bot test this

**Comment by aanm** [comment]
Please note the `cluster/saltbase/salt/docker/docker.service` is not detecting the different versions of docker so it will fail with versions **lower** than 1.8.0.

**Comment by luxas** [comment]
How is it with Kubernetes docker compability? I think I've heard somewhere that Kubernetes should support three docker versions back. So for `v1.2` that would mean: `1.10.0`, `1.9.1`, `1.8.3`, if I understand it correctly.

But I don't know for sure... See #13742

**Comment by a-robinson** [comment]
Fixes #20980

**Comment by dchen1107** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #22088

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: #22128

**Pull request merged**
