### PR TITLE
Fixes incorrect output.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by ixdy** [comment]
lgtm

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by ixdy** [comment]
@k8s-bot unit test this please

**Comment by ashcrow** [comment]
@wojtek-t / @ixdy: That's two test requests in a row with no bot run for unit/integration.

**Comment by wojtek-t** [comment]
@ashcrow - I don't understand - tests were run but they failed.

However, the failure:

    11:10:56 (B./hack/test-cmd.sh: line 492: file: command not found
    11:10:56 error: there was a problem with the editor "cat"
    11:10:56 !!! Error in ./hack/test-cmd.sh:492

seems like some infrastructural problem.
@ixdy - can you please take a look?

**Comment by ashcrow** [comment]
@wojtek-t my mistake. It looked like the same results from the previous runs and I thought it wasn't updating.

**Comment by ixdy** [comment]
Looks like the containerized tests started failing after #16160. @jlowdermilk

**Comment by ixdy** [comment]
@k8s-bot unit test this please

**Pull request merged**
