### PR TITLE
Remove pkg/util/merge and replace with evanphx/json-patch

### PR DESCRIPTION
**Pull request by mikedanese**
This is to add RFC6902 and RFC7386 JSON Patch capabilities as well as helpers. [evanphx/json-patch](http://github.com/evanphx/json-patch) provides utilities to create and apply patches and better test coverage compared with the single method in pkg/util/merge. JSON Patch is currently used by kubectl --patch and --override and this is a drop in replacement. It will soon be used by apiserver PATCH verb #4578 and config reconciliation #1702.

### CODE REVIEW

**Comment by mikedanese** [comment]
@ghodss may be interested.

**Comment by ghodss** [comment]
:+1:

**Comment by vishh** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
