### PR TITLE
controller: fix error message

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
just fix error typo, think you :)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by k82cn** [comment]
/lgtm

typo

**Review by kow3ns — APPROVED** [review]

**Comment by kow3ns** [comment]
/approve no-issue 
Trivial fix for error message naming

**Comment by kow3ns** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
