### PR TITLE
Fixed e2e_node build error on Mac.

### LINKED ISSUE #33091: Node e2e build failed on MacOS
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **OS**:
MacOS
- **Kernel** (e.g. `uname -a`):
Darwin Klauss-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**What happened**:

Build failed:

```
klauss-mbp:kubernetes klaus$ make
+++ [0920 22:00:50] Generating bindata:
    /Users/klaus/Workspace/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0920 22:00:50] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0920 22:00:50] Building go targets for darwin/amd64:
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/test/e2e_node
test/e2e_node/container_manager_test.go:80: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:80: undefined: dockerProcessName
test/e2e_node/container_manager_test.go:80: undefined: dockerPidFile
test/e2e_node/container_manager_test.go:89: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:89: undefined: kubeletProcessName
test/e2e_node/container_manager_test.go:116: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:130: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:168: undefined: getPidsForProcess
test/e2e_node/container_manager_test.go:209: undefined: getPidsForProcess
make: *** [all] Error 1
```

**What you expected to happen**:
Successfully built

**How to reproduce it** (as minimally and precisely as possible):

```
$git checkout master
$git fetch upstream
$git merge upstream/master
$make
```

**Anything else do we need to know**:
N/A

### PR DESCRIPTION
**Pull request by k82cn**
fixes #33091 

cc @vishh , any suggestion to avoid duplicated codes?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33105)

### CODE REVIEW

**Comment by vishh** [comment]
Why is this PR required?

**Comment by Random-Liu** [comment]
@k82cn The problem is not that the functions are missing.
Actually, those functions are in [resource_collector.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/resource_collector.go#L1), it is just specified as only build on Linux (it can indeed only build on Linux).

**Comment by k82cn** [comment]
@Random-Liu / @vishh , although those functions are in `resource_collector.go`, this file is built for linux only. In the new PR, added an new file, named `resource_collector_unsupported.go`, for other OS.

One more question is that, should we ignore `e2e_node.test` build on other OS?

**Comment by Random-Liu** [comment]
> One more question is that, should we ignore e2e_node.test build on other OS?

@k82cn We should do that, and we've already done that. If you run `make release` or `make cross`, I think e2e_node won't be built on Mac. However, it seems that `make` will just build everything regardless of the platform.

**Comment by k82cn** [comment]
> @k82cn We should do that, and we've already done that. If you run make release or make cross, I think e2e_node won't be built on Mac. However, it seems that make will just build everything regardless of the platform.

That looks like this. What OS does e2e_node support?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33105#-:-KSUMgQLc0X2b6K0dPhB:be87jco)*

**Comment by Random-Liu** [comment]
LGTM. @k82cn Have you verified in your environment? :)

**Comment by k82cn** [comment]
Yes, it works on my Mac :).

**Comment by Random-Liu** [comment]
Cool. Thanks a lot for the fix @k82cn.

**Pull request merged**
