### PR TITLE
Make fullyLabeledReplicas optional in rc status

### LINKED ISSUE #22996: Version-skewed client/master causing `fullyLabeledReplicas` errors in Kubectl apply
When Kubectl is at v1.2 and master is at v1.1:

**Kubectl client Kubectl apply should apply a new configuration to an existing RC**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:537 Expected error: <errors.errorString | 0xc2084e5b20>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-nb5k6] [] 0xc20837a1e0 error validating \"STDIN\": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false\n [] 0xc208436b60 exit status 1 true [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a68 0xc2083e7a88 0xc2083e7aa0] [0x95e260 0x95e380 0x95e380] 0xc20839d500}:\nCommand stdout:\n\nstderr:\nerror validating \"STDIN\": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-nb5k6] [] 0xc20837a1e0 error validating "STDIN": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false [] 0xc208436b60 exit status 1 true [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a68 0xc2083e7a88 0xc2083e7aa0] [0x95e260 0x95e380 0x95e380] 0xc20839d500}: Command stdout: stderr: error validating "STDIN": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false error: exit status 1 not to have occurred*

In the reverse case, when Kubectl is as v1.1 and master is at v1.2:

**Kubectl client Kubectl apply should apply a new configuration to an existing RC**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:463 Expected error: <errors.errorString | 0xc2082aefa0>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ody8f] [] 0xc20854f830 error validating \"STDIN\": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false\n [] 0xc208370e60 exit status 1 true [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784970 0xc208784998 0xc2087849d0] [0x6da490 0x6da5b0 0x6da5b0] 0xc20820a0c0}:\nCommand stdout:\n\nstderr:\nerror validating \"STDIN\": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false\n\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ody8f] [] 0xc20854f830 error validating "STDIN": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false [] 0xc208370e60 exit status 1 true [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784970 0xc208784998 0xc2087849d0] [0x6da490 0x6da5b0 0x6da5b0] 0xc20820a0c0}: Command stdout: stderr: error validating "STDIN": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false not to have occurred*

cc @bgrant0607

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #22996.

Explanation of the error: https://github.com/kubernetes/kubernetes/issues/22996#issuecomment-197039332

I verified this fixed the version skew on my local cluster.

@ihmccreery @bgrant0607 @janetkuo

### CODE REVIEW

**Comment by bgrant0607** [comment]
@caesarxuchao Please keep ReplicaSet consistent with RC.

**Comment by caesarxuchao** [comment]
@bgrant0607 done.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@pwittrock please merge manually once tests pass if submit queue is blocked

**Comment by pwittrock** [comment]
ACK

**Pull request merged**
