### PR TITLE
Stop updating boundPods objects.

### PR DESCRIPTION
**Pull request by erictune**
Does not clean up your existing boundPods records.
Does not clean up all the dead code.  Future PRs from me
will do that.

### CODE REVIEW

**Comment by erictune** [comment]
I saw a integration test failure once.  Then a bunch of passes.  Trying to repro.

**Comment by erictune** [comment]
@lavalamp

**Comment by yujuhong** [comment]
Doesn't kubelet still watch the boundpods? How will it handle this?

**Comment by erictune** [comment]
No.  Kubelet watches Pods.

**Comment by erictune** [comment]
Okay, this will pass integration test reliably once #5337 merges.  Wait for that.

**Comment by erictune** [comment]
Okay, IMO this is ready.

**Comment by lavalamp** [comment]
LGTM.

This does break cloud providers not using salt, or have they all switched over? Do we need to wait until "breakage day" to merge?

**Comment by erictune** [comment]
All cloud providers have had one of the following done to them:
 - They already fixed it
 - I sent them a PR, which may be pending
 - Their flags are in an RPM or something which is in their own repo or who knows where.  Too bad.

Additionally, I've been asking recently-added cloud providers to pin their install instructions to a specific release, so that people don't accidentally walk into this. 

Also, service env vars have been broken for like a month or more for people who used etcd-based distros.

Also, a PR which disabled the use of the flags that use etcd already went in.  So people will get the idea from that that something is wrong.

**Comment by erictune** [comment]
So, we don't need to wait for breakage day.

**Comment by bgrant0607** [comment]
Awesome! LGTM. A number of other changes are waiting on this, so merging.

**Comment by bgrant0607** [comment]
Ref #2483

**Pull request merged**
