### PR TITLE
Use errors.Is to check for a specific error in staging dir

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Comparing with `==` will fail on wrapped errors. Use errors.Is to check for a specific error

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@Fish-pro Please, consider including other than io.EOF errors.
Hint:
```
~/go/src/k8s.io/kubernetes $ git grep 'err ==' | grep -v ^vendor | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | sort -u 
ErrExit
ErrFIFOClosed
ErrNoContext
ErrNoNodesAvailable
ErrNoZoneTagInVC
ErrRegistryUnavailable
ErrorNotVmssInstance
ObjectCountNotFoundErr
ObjectCountStaleErr
enqueuedVirtualDeleteEventErr
fakeError
missingResourceError
namespacedOwnerOfClusterScopedObjectErr
processorErr
```

**Comment by Fish-pro** [comment]
> @Fish-pro Thank you for your PR.
> 
> Please, consider including other than io.EOF errors.
> 
> Hint:
> 
> ```
> ~/go/src/k8s.io/kubernetes $ git grep 'err ==' | grep -v ^vendor | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | sort -u 
> ErrExit
> ErrFIFOClosed
> ErrNoContext
> ErrNoNodesAvailable
> ErrNoZoneTagInVC
> ErrRegistryUnavailable
> ErrorNotVmssInstance
> ObjectCountNotFoundErr
> ObjectCountStaleErr
> enqueuedVirtualDeleteEventErr
> fakeError
> missingResourceError
> namespacedOwnerOfClusterScopedObjectErr
> processorErr
> ```

@bart0sh 
Thank you forr review
The amount of modification is huge，the following content is not changed because err is of `interface{}` type
```sh
➜  kubernetes git:(cleanup/errorsis) ✗ git grep 'err ==' | grep -v ^vendor | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | grep -v "err == nil" | sort -u
staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go:		if err == http.ErrAbortHandler {
test/integration/client/cert_rotation_test.go:			// do 'err == ctx.Err()', instead use 'errors.Is'.
```

**Comment by Fish-pro** [comment]
> @Fish-pro Thank you for your PR.
> 
> Please, consider including other than io.EOF errors.
> 
> Hint:
> 
> ```
> ~/go/src/k8s.io/kubernetes $ git grep 'err ==' | grep -v ^vendor | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | sort -u 
> ErrExit
> ErrFIFOClosed
> ErrNoContext
> ErrNoNodesAvailable
> ErrNoZoneTagInVC
> ErrRegistryUnavailable
> ErrorNotVmssInstance
> ObjectCountNotFoundErr
> ObjectCountStaleErr
> enqueuedVirtualDeleteEventErr
> fakeError
> missingResourceError
> namespacedOwnerOfClusterScopedObjectErr
> processorErr
> ```

@bart0sh 
A pr modification, the change is huge, can it be divided into multiple pr modifications, to ensure stability
This pr modifies the staging directory, the unmodified part below, because err is of type `interface{}`
```sh
➜  kubernetes git:(cleanup/errorsis) ✗ git grep 'err ==' | grep -v ^vendor | grep ^staging | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | grep -v "err == nil" | sort -u
staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go:		if err == http.ErrAbortHandler {
```

**Comment by bart0sh** [comment]
> A pr modification, the change is huge, can it be divided into multiple pr modifications, to ensure stability

Abosolutely

**Comment by apelisse** [comment]
/unassign
I'll let someone else take a look at this.

**Pull request closed without merging**
