### PR TITLE
fix freespace for image GC

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:
use 'continue' in the loop instead of 'break'
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by derekwaynecarr** [comment]
nice catch.

/kind bug
/approve no-issue
/lgtm

**Comment by derekwaynecarr** [comment]
fyi @vikaschoudhary16 @sjenning -- we may want to pick this back into origin.

/sig node

**Pull request merged**
