### PR TITLE
Automated cherry pick of #10961 on release 0.21

### PR DESCRIPTION
**Pull request by thockin**
Builds on #11022

### CODE REVIEW

**Comment by thockin** [comment]
@zmerlynn

**Comment by zmerlynn** [comment]
@thockin - needs rebase .. did the script misfire? Oh. It probably built the cherry-pick on the base branch, not on top of #11022.

**Comment by zmerlynn** [comment]
#10961 cross-link

**Comment by thockin** [comment]
PTAL

**Comment by zmerlynn** [comment]
LGTM.

**Pull request merged**
