### PR TITLE
Use t.Fatalf instead

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
we can use t.Fatalf to take place of t.Errorf + t.FailNow()

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@calebamiles could you add this PR v1.7 milestone.

**Comment by zhangxiaoyu-zidif** [comment]
@fabianofranz  could you approve it =) ?

**Pull request merged**
