### PR TITLE
Update comments for golint.

### PR DESCRIPTION
**Pull request by k82cn**
Update comments for golint.

### CODE REVIEW

**Comment by cblecker** [comment]
@k82cn This needs a rebase, even though the bots aren't reporting it :(

**Comment by cblecker** [comment]
A little late to the game there, @k8s-merge-robot.

**Comment by k82cn** [comment]
rebased :).

**Comment by k82cn** [comment]
@k8s-bot bazel test this

**Comment by cblecker** [comment]
Failure looks like it relates to https://github.com/kubernetes/kubernetes/pull/43766. Will likely need another rebase after it merges.

**Comment by k82cn** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
