### PR TITLE
add a blocking accept method to RateLimiter

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
I'm part of the RedHat CLA.

@smarterclayton ptal.

**Comment by smarterclayton** [comment]
LGTM

**Comment by bprashanth** [comment]
I think you need to gendocs

**Comment by smarterclayton** [comment]
It's breaking on a lot of pulls - I assumed someone else would fix because bens code doesn't change the cli

**Comment by bprashanth** [comment]
Fair enough, i think it's fixed, i kicked shippable and travis will merge if they finish green

**Comment by bprashanth** [comment]
Looks like the failures are legit: 
```
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers_test.go:45: cannot use rl (type fakeRL) as type util.RateLimiter in argument to RateLimit:
	fakeRL does not implement util.RateLimiter (missing Accept method)
```

**Comment by bparees** [comment]
thanks @bprashanth, missed that.  updated.

**Comment by bparees** [comment]
added a unit test for the new behavior.

**Comment by bparees** [comment]
@smarterclayton @bprashanth the travis errors look flaky and unrelated to my changes, any advice?

**Comment by bprashanth** [comment]
That looks like https://github.com/GoogleCloudPlatform/kubernetes/issues/6199, i kicked travis, we'll see

**Comment by smarterclayton** [comment]
Shippable passing is usually enough.

**Pull request merged**
