### PR TITLE
Typo fix in returned messages: healtcheck->healthcheck

### PR DESCRIPTION
**Pull request by AdamDang**
In the following three files:
pkg/proxy/iptables/proxier.go
pkg/proxy/ipvs/proxier.go
pkg/proxy/winkernel/proxier.go
There are same typos that need to be fixed:
healtcheck->healthcheck

### CODE REVIEW

**Review by idealhack — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by nikhita** [comment]
/hold

for commits to be squashed.

**Comment by AdamDang** [comment]
@nikhita 
Hi , I've got the skill to squash commits and tried to squash commits in this PR. :)
Does it work?

**Comment by idealhack** [comment]
It works! It'll be better if you could improve the commit message :)

**Comment by AdamDang** [comment]
@nikhita Rebase is done. and I 've solved the conflicts, too.

**Comment by nikhita** [comment]
@AdamDang Thanks for rebasing. Could you also squash the commits into a single commit? Lgtm after that.

**Comment by AdamDang** [comment]
@nikhita 
When I execute git rebase -i HEAD~2, I got much more than 2 commits in the list. How to deal with them?
for example:
pick 21966c19cf Typo fix: healtcheck->healthcheck
pick bfc2d7bdd7 gazelle: disable proto rules
pick 01f94051c8 Remove the go_default_library_protos filegroups using buildozer
pick e7f1eaf289 update to rules_go 0.12.1
pick a725660640 Update to gazelle 0.12.0 and run hack/update-bazel.sh
pick f31183fa3d Set gazelle:prefix on staging/src and remove sed hack
pick b0af0f68b1 gazelle: set proper importmap on dependencies in vendor/
pick 23ceebac22 Run hack/update-bazel.sh
pick d3a22cbd2f Reformat openapi/def.bzl and pkg/version/def.bzl using latest buildifier rules
pick 095a9e53ca Use new go_genrule from kubernetes/repo-infra based on go_path
pick 4c7c058a61 Remove go_prefix from root BUILD file
pick 347c3612c9 Set gazelle:importmap_prefix for everything under staging/src
pick b42e9125c4 Run hack/update-bazel.sh
... ...

**Comment by idealhack** [comment]
@AdamDang Given the remote`upstream` is pointed to `k/k` and `origin` is pointed to your fork:

I think you can run

```
git rebase upstream master
git push origin -f
```

or

```
git fetch upstream
git reset --hard upstream master
git cherry-pick 21966c19cf9ddd81d3184e5227e0b9961aafa7bf
git push origin -f
```

`21966c19cf9ddd81d3184e5227e0b9961aafa7bf` is your fix commit hash.

If that doesn't work, find the nearest git guru :)

**Comment by nikhita** [comment]
@AdamDang Were you able to get it working?

If you need help with it, please ping me on Slack (I am @nikhita there). I am happy to walk you through it. :)

**Comment by nikhita** [comment]
> I think maybe I'd better recreate this PR, for so long time passed and so many changes happened. What do you think?

I think this PR is fine, but thanks for trying! :)

/retest
/lgtm

@cblecker could you add the squash label here and remove the hold after that?

/assign @thockin 
for approval

**Comment by cblecker** [comment]
Typo fix to error messages. Low risk to release, but will improve release quality.
Adding to v1.13..

/milestone v1.13
FYI @AishSundar

**Pull request merged**
