### PR TITLE
Update metrics docs for v1.32 release(Note this must be committed after the code freeze)

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update metrics documentation for the v1.32 release, and there will be a separate PR for the website repo.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Note this must be committed after the code freeze to avoid missing metrics.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig instrumentation

/cc @logicalhan

### CODE REVIEW

**Comment by pacoxu** [comment]
Is this target to v1.32?

cc @fsmunoz

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by mengjiao-liu** [comment]
Please put the tag `/milestone v1.32` on it to include it in the release.
/cc @logicalhan

**Comment by SataQiu** [comment]
/hold

please cancel hold when ready @mengjiao-liu

**Comment by fsmunoz** [comment]
> Is this target to v1.32?
> 
> cc @fsmunoz

Yes, thanks, I see milestone was already added since then.

**Pull request merged**
