### PR TITLE
Move remaining PD test back from flaky

### PR DESCRIPTION
**Pull request by wojtek-t**
cc @gmarek @saad-ali

### CODE REVIEW

**Comment by gmarek** [comment]
I failed yesterday around 3PM US time. Are we sure we want to move it out of flaky?

**Comment by wojtek-t** [comment]
#11561 was merged yesterday (it probably won't fix all of the failure - see #11302, but on the other way having just this one test in flaky (where other tests are failing in base gce suite) also isn't the best approach.

**Comment by gmarek** [comment]
There are couple other tests that I'd happily move to flaky to keep this test company:)

**Comment by saad-ali** [comment]
Let's hold off on this until I have a chance to resolve #11302
I'm going to be digging into that more today.

**Comment by wojtek-t** [comment]
@saad-ali - since #11302 is fixed - can you please LGTM this PR?

**Comment by saad-ali** [comment]
LGTM
The test has been stable since the fix for #11302 was merged yesterday.

**Pull request merged**
