### PR TITLE
Remove deprecated selectorSpread

### LINKED ISSUE #108444: remove `SelectorSpread` plugin
### What would you like to be added?

Feature gate `DefaultPodTopologySpread` is GA, shall we remove `SelectorSpread` plugin then. I also get support from https://github.com/kubernetes/kubernetes/pull/91793#issuecomment-639800733.  Or next release will be the proper time.

### Why is this needed?

Remove unneeded plugin.

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind feature
/sig scheduling
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/108444

#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED: the kube-scheduler `selectorSpread` plugin has been removed, please use the `podTopologySpread` plugin instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold
for #117649

**Comment by kerthcet** [comment]
/hold cancel
Ready for review now.

**Comment by alculquicondor** [comment]
oh wait... but v1beta3 still could use the plugin, couldn't it?

**Comment by alculquicondor** [comment]
Yes, sorry for the confusion

/hold

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by kerthcet** [comment]
> Also, remember to get this change documented.

Updated, and will follow the documentation.

**Pull request merged**
