### PR TITLE
Fix typo in kubedns-controller.yaml.sed

### PR DESCRIPTION
**Pull request by lukaszo**
cc @MrHohn

### CODE REVIEW

**Comment by MrHohn** [comment]
Thanks for the fix!

/lgtm
/approve

**Review by bowei — APPROVED** [review]
/approve /lgtm

**Comment by lukaszo** [comment]
@bowei can you also set a 1.6 milestone?

**Comment by MrHohn** [comment]
@bowei This is missing approve label.

**Comment by lukaszo** [comment]
@k8s-bot unit test this

**Pull request merged**
