### PR TITLE
fix created typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix created typo

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot ok to test

**Comment by timchenxiaoyu** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot non-cri e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Pull request merged**
