### PR TITLE
Remove extraneous CHANGELOGS on the 1.10 branch.

### PR DESCRIPTION
**Pull request by david-mcmahon**
**What this PR does / why we need it**:

Initial change on a new branch so we can tag a commit that doesn't exist on master.

This normally happens during the course of a release, automatically via `anago`.  This provides an opportunity here to fix the issue at branch time, described in detail below.

ref https://github.com/kubernetes/sig-release/issues/85

### CODE REVIEW

**Review by enisoc — APPROVED** [review]
LGTM but I'll defer to @calebamiles to add the lgtm label.

**Comment by ixdy** [comment]
@cjwagner tests above are failing with
```
I0221 17:06:45.141] Call:  /workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py --branch=release-1.10 --prow
W0221 17:06:45.167] Traceback (most recent call last):
W0221 17:06:45.168]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 170, in <module>
W0221 17:06:45.168]     main(ARGS.branch, ARGS.script, ARGS.force, ARGS.prow)
W0221 17:06:45.168]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 94, in main
W0221 17:06:45.169]     tag = VERSION_TAG[BRANCH_VERSION.get(ver, ver)]
W0221 17:06:45.169] KeyError: '1.10'
E0221 17:06:45.169] Command failed
```

**Comment by calebamiles** [comment]
total speculation that https://github.com/kubernetes/test-infra/pull/6919 would fix the above test failure. Better question is why this works for 1.9

**Pull request merged**
