### PR TITLE
Automated cherry pick of #65313: Adds cri-tools as a dependency to kubeadm deb/rpms

### PR DESCRIPTION
**Pull request by rdodev**
Cherry pick of #65313 on release-1.11.

#65313: Adds cri-tools as a dependency to kubeadm deb/rpms

```release-note
Adds cri-tools as a dependency to kubeadm deb/rpms
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/approve
Thanks for the cherrypick!
/kind bug
/priority important-soon
/status approved-for-milestone
/assign @foxish 
/sig cluster-lifecycle
/milestone v1.11

**Comment by foxish** [comment]
Cherrypick approved. Please update the release note.

**Pull request merged**
