### PR TITLE
Allow ingress without backends

### LINKED ISSUE #82203: Add ability to create empty ingress
**What would you like to be added**:
Ability to create empty ingresses

**Why is this needed**:
Empty ingresses will be patched later by scripts/apps to add/update/delete rules dynamically as needed.

Note: I am using the described strategy with configmaps/secrets as k8s allows creating empty configmaps/secrets.

This might be achieved by removing the check for empty rules in [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L215) `pkg/apis/networking/validation/validation.go`
```go
else if len(spec.Rules) == 0 {
		allErrs = append(allErrs, field.Invalid(fldPath, spec.Rules, "either `backend` or `rules` must be specified"))
	}
```

See #69422
/sig network

### PR DESCRIPTION
**Pull request by darshanime**
Signed-off-by: darshanime <deathbullet@gmail.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Allows creation of Ingress without specying backends

**Which issue(s) this PR fixes**:
Fixes #82203

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
WIP
```
```docs
WIP
```

### CODE REVIEW

**Comment by darshanime** [comment]
The `IngressSpec.Backend` field is already optional - https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/types.go#L242, so it is semantically safe to allow ingress without it.

**Comment by danwinship** [comment]
ping @bowei

**Pull request closed without merging**
