### PR TITLE
Updating federated service controller to support cascading deletion

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes/issues/33612

Service controller is special than other federation controllers because it does not use federatedinformer and updater to sync services (it was written before we had those frameworks).
Updating service controller code to instantiate these frameworks and then use deletion helper to perform cascading deletion.
Note that, I havent changed the queuing logic in this PR so we still dont use federated informer to manage the queue. Will do that in the next PR.

cc @kubernetes/sig-federation-misc  @mwielgus @quinton-hoole

```release-note
federation: Adding support for DeleteOptions.OrphanDependents for federated services. Setting it to false while deleting a federated service also deletes the corresponding services from all registered clusters.
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36390)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Am sending it out right now since I have this code ready. Not critical for 1.5 but will be great if we can get it in :)

**Comment by quinton-hoole** [comment]
LGTM.

**Comment by quinton-hoole** [comment]
@nikhiljindal Please add an e2e test for this.

**Comment by quinton-hoole** [comment]
@nikhiljindal and also unit tests.

**Comment by nikhiljindal** [comment]
cc @shashidharatd 
I am going to rebase and add e2e tests. This is the first step to move service controller to use the new federated informer pattern but this does not go all the way. More work is needed after this PR

**Comment by nikhiljindal** [comment]
Rebased and added a e2e tests

**Comment by shashidharatd** [comment]
@nikhiljindal, I have started working on refactoring the service controller to new federated-informer framework. I have re-based my work on top of this PR. I will put up a PR for review in few days in that regard.

I have following proposal on refactoring service controller. request to give your opinion, especially @quinton-hoole, who is much familiar with service controller code.

- Separate dns related code from service controller into a separate controller. this dns-controller will watch on federation services and add/delete/update dns records accordingly. We shall store the service load-balancer endpoints in annotations by global/region/zone names. this dns-controller can be optionally enabled/disabled as required.
- Federation service controller will just reconcile federation service with cluster service and any updates in cluster service status will be updated to federation service and also updates endpoints in annotations.
- recently in some disaster recovery scenario, we found that the dns records of services shards in offline clusters should be removed, otherwise the clients will get possibly non-reachable service load-balancer endpoints upon dns query. removing the dns records of services in offline cluster will facilitate the smooth failover.
- We should also be removing the dns records for service shards in de-registered cluster. this will also solve the issue of leftover dns records in CI environment.

cc @quinton-hoole, @madhusudancs, @deepak-vij, @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Hi @shashidharatd 

My apologies for taking so long to respond.  I blame it on Father Christmas :-)

1.  I like the general idea of separating the DNS logic out completely into a separate controller.  I do however wonder how well that will work in practise, given that the DNS controller will need to monitor the existence and health of all of the cluster-level services (which the existing service controller does in it's local cache - the cluster-level services are not persisted to the federation etcd).  Perhaps give it a try and see how well the code works out.
2. SGTM
3. Removing DNS records on the basis of API server uncontactability is a pretty contentious issue, unfortunately.  The core of the problem is that it is necessary to distinguish lack of network connectivity between the Federation control plane and the API server of a cluster, from more general unreachability of one or more services in a clustere.  More specifically, in your proposal, if the Federation control plane (particularly the DNS controller that you contemplate above) loses connectivity to one or more (or all) cluster API servers (possibly due to a problem on the Federation end), it would remove the DNS records for (potentially all) clusters, even if the services are in those clusters are in fact perfectly contactable by external clients of the service (hence causing a completely unnecessary global outage).   For that reason you ideally need some sort of quorum to agree that a given service in a cluster (as opposed to the API server of a cluster) is truely uncontactable.  I wrote up some ideas around this [here](https://github.com/kubernetes/kubernetes/blob/master/docs/design/federated-services.md), specifically "If Cluster Federation Global Service Health Checking is enabled, multiple service health checkers running across the federated clusters collaborate to monitor the health of the service endpoints, and automatically remove unhealthy endpoints from the DNS record (e.g. a majority quorum is required to vote a service endpoint unhealthy, to avoid false positives due to individual health checker network isolation)."   The current implementation (which explicitly does not remove DNS records when cluster API servers become uncontactable from the Federation control plane), effectively errs on the side of caution, assuming that either the cluster API server, or the link between the Federation control plane and the cluster API server have failed, rather than the service itself having become uncontactable by it's clients (which is more often the case.  If we want to improve upon that, I'd suggest using the above "quorum based service health checks" approach, rather than the one you suggest.
4. On your forth point, I tend to agree.  If a cluster is explicitly deregistered from a federation, it's cluster services should no longer be part of federated services, and the associated DNS records should be removed.

**Comment by shashidharatd** [comment]
Thanks @quinton-hoole for the elaborate response and apologies for missing this design detail which was already well thought of. I do completely agree with the argument presented above.
We were trying to solve a scenario involving the dumb clients failing over smoothly to a healthy service endpoint and the right way to do is to have Cluster Federation Global Service Health Checking as you pointed out. The current cluster health check done by cluster controller is just a single health check and lacks quorum.
I would soon amend my PR to distinguish between cluster unregistration(cluster object removal) from other cluster conditions and handle dns records removal for entire cluster only upon cluster unregistration. We shall leave the dns records as-is and expect the users to have "Cluster Federation Global Service Health Check" and update the dns records accordingly.
I would request you to give your valuable feedback on the PR i have raised here #39328

**Comment by nikhiljindal** [comment]
Rebased and added e2e test

**Comment by nikhiljindal** [comment]
Adding LGTM as per comment above

**Comment by nikhiljindal** [comment]
Failing Open API test is known flaky: https://github.com/kubernetes/kubernetes/issues/39604
@k8s-bot unit test this

**Pull request merged**
