### PR TITLE
Empty label is equal for topologies.

### LINKED ISSUE #40799: Empty label are not considered in the same topologies.
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
If the value of label is empty, the nodes are not considered in the same topologies.

**How to reproduce it** (as minimally and precisely as possible):
Refer to the PR.

### PR DESCRIPTION
**Pull request by k82cn**
fixes #40799

### CODE REVIEW

**Comment by wojtek-t** [comment]
Something is wrong with submit queue - it's not picking this up even though it's green.
Required Github CI test is not green: Jenkins Bazel Build

@k8s-bot test this

**Comment by k82cn** [comment]
> Something is wrong with submit queue - it's not picking this up even though it's green.

Failed again even though it's green: `Required Github CI test is not green: Jenkins GCE etcd3 e2e`


@k8s-bot test this

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by wojtek-t** [comment]
Bazel is green and Submit queue still doesn't want to pick it up.

@fejta @kubernetes/test-infra-maintainers - can someone please take a look?

If we won't manage to solve it, I will merge manually tomorrow.

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Pull request merged**
