### PR TITLE
Remove network plugin cni dir in kubeadm reset

### PR DESCRIPTION
**Pull request by ccronca**
Clean network plugin cni dir in kubeadm reset.
https://github.com/kubernetes/kubernetes.github.io/pull/1505

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35709)

### CODE REVIEW

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
I guess this is fine, otherwise kubelet might start up with the wrong config.
LGTM

**Comment by luxas** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
But please squash your commits to one.
Ask if you don't know how to do that :)

**Comment by luxas** [comment]
@k8s-bot test this

**Comment by luxas** [comment]
@k8s-bot test this

**Comment by luxas** [comment]
@k8s-bot test this

**Comment by rmmh** [comment]
This second commit is bad-- you should rebase commits and push -f, not merge master into your branch.

This PR shouldn't have 29,016 additions and 51,663 deletions.

**Comment by luxas** [comment]
Whoaa, I didn't notice @camilocot had added a _merge commit_, just checked the files changed...

Thanks @rmmh, I'm closing this now and carrying the commit in a similar patch I have up, since there hasn't been any activity to rebase it for ~a month either.

Sorry @camilocot, your "real" commit will be merged, but in an other PR

**Pull request closed without merging**
