### PR TITLE
rewrite kubectl command references to GoogleCloudPlatform

### PR DESCRIPTION
**Pull request by mikedanese**
#12211

### CODE REVIEW

**Comment by bgrant0607** [comment]
These should probably all point to docs.k8s.io links instead. For instance, the API reference is http://kubernetes.io/v1.0/docs/api-reference/definitions.html

**Comment by bgrant0607** [comment]
I can't figure out how to get the redirected URLs to work, but the kubernetes.io links do work.

**Comment by caesarxuchao** [comment]
LGTM. Thank you!

**Comment by caesarxuchao** [comment]
@bgrant0607, the kuberenetes.io docs are for v1.0, not HEAD, is that ok?

**Comment by mikedanese** [comment]
I see https://github.com/kubernetes/kubernetes/blob/master/build/versionize-docs.sh#L47 but it doesn't apply to the cobra comments

**Comment by caesarxuchao** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
Let's go ahead with the sed replacement and then figure out the right solution. 
LGTM.

**Pull request merged**
