### PR TITLE
Fixes Hazelcast example

### LINKED ISSUE #7731: hazelcast example is broken
I followed the instructions in the [tutorial] (https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/hazelcast) and got this output:
```
$kubectl get pods hazelcast
POD         IP           CONTAINER(S)   IMAGE(S)              HOST                                     LABELS           STATUS    CREATED         MESSAGE
hazelcast   10.244.0.5                                        kubernetes-minion-7jsw/130.211.122.180   name=hazelcast   Running   About an hour   
                         hazelcast      pires/hazelcast-k8s                                                             Running   9 seconds       last termination: exit code 1
```
Note the "last termination: exit code 1".

And [here] (http://pastebin.com/1mNt57Ps) is the log.

It seems to be a problem of hazelcast rather than Kubernetes. @pires @nikhiljindal

### PR DESCRIPTION
**Pull request by pires**
Upgraded to `hazelcast-bootstrapper` `0.2` and `pires/hazelcast-k8s:0.2`.
We now use `v1beta3` API.
Fixes #7731

Removed single pod stuff because we now rely on service endpoints for discovery.

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

**Comment by caesarxuchao** [comment]
LGTM. Wait for @nikhiljindal to merge it on Monday.

**Comment by caesarxuchao** [comment]
Could you fix a typo? "This is the way that we use initially use Services with Hazelcast."

**Comment by pires** [comment]
@caesarxuchao done.

Will squash after someone waives the green flag for merging.

**Pull request merged**
