### PR TITLE
Automated cherry pick of #28604 #29062

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #28604 #29062 on release-1.3.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @gmarek @mqliang @cjcullen

**Comment by davidopp** [comment]
any reason not to LGTM this now?

**Comment by davidopp** [comment]
@bgrant0607 are you going to do the cherrypick? I labeled the two PRs as cherrypick-candidate and 1.3 milestone.

**Comment by bgrant0607** [comment]
@davidopp I was looking over the changes in this PR first. If we LGTM it, I believe it should be merged automatically.

**Comment by bgrant0607** [comment]
@bprashanth Were any conflicts resolved manually, or was this a straightforward patch?

**Comment by bgrant0607** [comment]
This is a bigger change than we'd like, but I think we should go ahead with cherrypicking  #28604, because I believe there will additional bugs we want to fix.

LGTM

**Comment by bprashanth** [comment]
There were some conflicts that I resolved manually (function args changed from 1.3 to HEAD, I kept the 1.3 version). I only cherrypicked the one pr I needed from this stack (https://github.com/kubernetes/kubernetes/issues/28832). I suppose things should fail if i picked wrong.

**Pull request merged**
