### PR TITLE
Automated cherry pick of #65593: Limit usage of system critical priority classes to the

### PR DESCRIPTION
**Pull request by bsalamat**
Cherry pick of #65593 on release-1.11.

#65593: Limit usage of system critical priority classes to the

### CODE REVIEW

**Comment by bsalamat** [comment]
/sig scheduling
cc/ @ravisantoshgudimetla @aveshagarwal @derekwaynecarr

**Comment by ravisantoshgudimetla** [comment]
/retest
/lgtm

Derek and Avesh are out this week. 

/cc @liggit. Can you please approve this?

**Comment by bsalamat** [comment]
cc @deads2k for approval

**Pull request merged**
