### PR TITLE
[mesos/docker] Dump logs on kube-up error

### PR DESCRIPTION
**Pull request by karlkfi**
This makes it easier to debug automated deployment failure, especially in CI.

xref: https://github.com/mesosphere/kubernetes-mesos/issues/305

### CODE REVIEW

**Comment by karlkfi** [comment]
@davidopp (or someone at google): can you share the jenkins gce e2e failure?

**Comment by a-robinson** [comment]
@karlkfi are you not able to download the output from the "Build Log" link in k8s-bot's post?

**Comment by sttts** [comment]
otherwise, lgtm

**Comment by karlkfi** [comment]
@a-robinson When I click on "Details" next to "Jenkins GCE e2e" from this page it asks me which of my gogole accounts to log in as, I select my @mesosphere.io one and get redirected to a page that says "Access not possible". URL bar says [https://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/4731/].

**Comment by karlkfi** [comment]
From the @k8s-bot build logs I see:

```
Summarizing 7 Failures:

[Fail] Kubectl client Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:579

[Fail] Kubectl client Kubectl expose [It] should create services for rc 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:579

[Fail] Kubectl client Simple pod [It] should support exec 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:926

[Fail] Kubectl client Simple pod [It] should support port-forward 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:194

[Fail] Kubectl client Kubectl patch [It] should add annotations for pods in rc 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:579

[Fail] Kubectl client Kubectl logs [It] should find a string in pod logs 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:579

[Fail] Kubectl client Guestbook application [It] should create and stop a working application 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:722

Ran 84 of 142 Specs in 1007.119 seconds
FAIL! -- 77 Passed | 7 Failed | 2 Pending | 56 Skipped 
```

None of those look like they could have been affected by this PR. 
Are they bugs on master? Have they been recently fixed?

**Comment by karlkfi** [comment]
rebase (no-op) & extracted compose_file variable

**Comment by a-robinson** [comment]
Yes, the k8s-bot Build Log is the same as the Jenkins GCE e2e check. We'll see how your latest commit fairs, it may have been a flake?

**Comment by karlkfi** [comment]
@a-robinson looks like a flake. might want to keep an eye on it.

**Comment by karlkfi** [comment]
FWIW, here's an example of kube-up failing on our TeamCity CI (and this pr working):

```
[14:44:59][Step 5/8] Waiting (up to 120s) for http://apiserver:8888/healthz to be healthy
[14:46:59][Step 5/8] Timed out
[14:46:59][Step 5/8] Exited 1
[14:46:59][Step 5/8] Dumping logs to '/go/src/github.com/GoogleCloudPlatform/kubernetes/cluster/mesos/docker/logs'
[14:46:59][Step 5/8] Process exited with code 1
```

I'll make timeouts modifiable in another PR.

**Pull request merged**
