### PR TITLE
Revert "Add Mesos hyperkube minion server "

### PR DESCRIPTION
**Pull request by mikedanese**
This breaks make quick-release @sttts

Reverts GoogleCloudPlatform/kubernetes#11928

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM.

**Comment by sttts** [comment]
Checking.

**Comment by mikedanese** [comment]
Here is an example build log: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/c9bc1456ff1d69158baf34dd682992b790ba27a8/kubernetes-pull-build-test-e2e-gce/3962/build-log.txt

**Comment by sttts** [comment]
Here is the fixed version: https://github.com/GoogleCloudPlatform/kubernetes/pull/12096

**Pull request merged**
