### PR TITLE
Generalize and improve hack/local_up_cluster.sh

### PR DESCRIPTION
**Pull request by salv-orlando**
**What this PR does / why we need it**:

It extends the ability of the local_up_cluster to run distinct services in distinct nodes.
While the 3 start modes provided satisfy a number of common use cases, there could be different needs, for instance running the scheduler on a dedicated VM.

While far from deserving any sort of priority, the changes in this PR make the hack/local_up_cluster.sh more generic, enable different scenarios for building development environment, and make the script a bit more readable (according to the author's opinion at least...)

Special care was taken about ensuring backward compatibility w.r.t env variables. Even if the author believes backward compatibility was preserved, this kind of things always need to be checked 2 or 3 times by independent eyes!

**Which issue this PR fixes**

No issue was created on github.

**Special notes for your reviewer**:

The first 2 commits fix what the author believes could be considered bugs in local_up_cluster.sh
The 3rd commit is mostly about improving script output
The 4th commit actually includes most of the PR logic
The 5th commit is exclusively about the DNS service. The author is not really convinced about that commit, as there's a lot of special casing around DNS in local_up_cluster.sh

Moreover, the logic in this PR is inspired by (nice word for 'shamelessly copies') what devstack (www.devstack.org) does with the ENABLED-SERVICES variables. This is actually code the author had been using locally for a while and thought it might be worth checking whether the community thinks it could be useful also for other people.

(the author sincerely hopes this PR is in accordance with the project guidelines - and apologizes in advance for any mistake)

**Release note**:

The author does not think this deserves a release note because:
1) The author ignores whether changes in hack/local_up_cluster.sh deserve a release note
2) changes were done in a backward compatible way (hopefully)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36669)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Changes look ok, will try more and give feedback on Monday.

**Comment by jayunit100** [comment]
by *nodes* do you mean *MODES* ? just making sure. After all, "distinct nodes" sounds like docker-in-docker

**Comment by salv-orlando** [comment]
Hello @smarterclayton & @jayunit100!  Thanks for your comments!
I do not mean "MODES". But I should probably not have used "NODE" as well.

For instance, when I spin up a development environment sometimes I have all services on a single instance. Sometimes instead I run additional instances with the kubelet only on them (and that's where nokubelet or kubeletonly come useful). It also often happens that I run the kubelet and the kube-proxy an all these instances. In other cases instead I also have a dedicated instance for the API server and another one running the scheduler and controller manager.

That's why I ended up with changing local_up_cluster.sh in this way.
As stated earlier, I've been using this in my dev envs for a while, even before the START_MODE was introduced. I actually think START_MODE is very useful, and so I thought it might make sense to generalize it.

**Comment by jayunit100** [comment]
So when you say "I run additional instances with the kubelet only", how does this work once distributed? Iirc we assumed loopback for master components but maybe this script has other use cases since I last looked in detail

**Comment by salv-orlando** [comment]
@jayunit100 I think local_up_cluster allows for overriding the loopback assumption for master (at least I do that regularly, not sure if that's legit or not); also for networking i always use CNI plugins.

These are the local_up_cluster env vars I override on master:
```
export HOSTNAME_OVERRIDE=kubedev-master
export API_HOST=192.168.1.241
export API_HOST_IP=$API_HOST
export NET_PLUGIN=cni
export LOG_LEVEL=4
export START_MODE=nokubelet
```

For all other cases where there is a loopback assumption for master, I agree it just makes no sense to spread services across nodes.

**Comment by jayunit100** [comment]
Ah ok . How does auth work in that case? How are you giving tokens to the kubelet to read the apiserver end points ?

**Comment by salv-orlando** [comment]
@jayunit100 good point. After the patch that added auth support for components merged, my setup stopped working. In order to fix it kubeconfig and the certificates generated by the api server should present in $CERT_DIR when the kubelet (or any other component) starts.
 I would have loved if @dims left somehow an option to allow connections to the insecure port in the fix for issue 33966, but I understand why it has been done that way.

One of the commits in this PR simply fails the script if one tries to launch a service that requires kubeconfig and that file is not present. Adding more automation is possible, but surely out of scope for this PR (and probably out of scope for local_up_cluster as a whole). Therefore my workflow is:

1. Start the API server with START_MODE=kube-api
2. Get contents of $CERT_DIR and propagate them to every instance where services are running
3. Start services on every other instance according to their $START_MODE

Step #2 at the moment is handled with a separate script.

**Comment by jayunit100** [comment]
Ahhh ok.  So since we don't support multiple nodes in  local-up.... Is there a way the multi cluster parameters and functionality could be externalized  to minimize the complexity bloat of local up?  After all when debugging itnwould be tricky to understand why anyone uses START_MODE and so on.

Maybe 

- local-service-up.sh
- local-up-cluster.sh (depends on local-service-up)
- simple-up-cluster.sh (depends on local-service-up)

simple-up-cluster.sh could have your hacks to do a simple multi node cluster without salt, which is great and  will probably be used by someone else:)

**Comment by jayunit100** [comment]
(Either way I think the changes here are good, just thinking for the future..., I just noticed that we have this new "kubelet only" stuff today, which I assume is for the node testing, but maybe you've found a clever new way to apply it.. the salt stuff got exhausting for a lot of people who want a simple 2 or 3 node cluster).

**Comment by salv-orlando** [comment]
@jayunit100 When I have a chance to deploy my stuff on AWS or vSphere I'm more than happy to use kube-up and the salt installer. However most of the infrastructure I use runs on OpenStack... A while ago I tried very hard to use the salt stuff there too, but I was never impressed with the result (more at: http://salv-orlando.github.io/K8S-OS-Vagrant/)

Also, deploying with kube-up takes a while, and patience is definitely not my virtue ;)

**Comment by salv-orlando** [comment]
Do you have any additional feedback for me?
Also, I see some check apparently are hang, I would like to retrigger those.
Is there a way to do that without pushin a new commit?

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by salv-orlando** [comment]
with the latest rebase I removed a commit for fixing an issue when starting the DNS service as that has been fixed in the meanwhile, and added a new commit for treating the discovery service in the same way as any other service.

**Comment by salv-orlando** [comment]
need to verify failure. at first glance I do not see relationship with my patch.

**Comment by salv-orlando** [comment]
The last update introduced a syntax error in hack/local-up-cluster.sh
I am slightly surprised a bit that no test covered that.

I will fix the issue shortly.

**Comment by salv-orlando** [comment]
PR rebased! Once checks will complete reviews will be more than welcome!

**Pull request closed without merging**
