### PR TITLE
clean unused package: pkg/util/term

### PR DESCRIPTION
**Pull request by WanLinghao**
Clean unused package which was  used by  ./pkg/kubelet/rkt/rkt.go. And the rkt.go file has been removed.

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@smarterclayton @lavalamp  PTAL

**Comment by nikhita** [comment]
/assign @lavalamp 
for approval

**Comment by nikhita** [comment]
@smarterclayton can you approve again? I don't think prow picks up edits while looking at `/approve` comments.

**Comment by WanLinghao** [comment]
@lavalamp friendly ping

**Comment by runcom** [comment]
This has broken CRI-O altogether as we were using that `SetSize` function

**Pull request merged**
