### PR TITLE
Fix kube-apiserver restart.

### LINKED ISSUE #7120: gce provider's restart-apiserver function is no longer correct
Now that kube-apiserver runs in a container, `/etc/init.d/kube-apiserver` no longer exists:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L983-L985

/cc @ArtfulCoder

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #7120

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by derekwaynecarr** [comment]
Who is using this function?  I thought we were going to remove it since it was only referenced in one old e2e test around services.sh (which I think got rid of it in an earlier PR).

**Comment by roberthbailey** [comment]
It's still used in the services.sh e2e test. That test is currently passing at head for GCE but only because of a bug (#7119). 

@derekwaynecarr  If you want to get rid of that last shell test, I'd be reaaaaally happy.

**Comment by roberthbailey** [comment]
Shippable is happy. Merging.

**Pull request merged**
