### PR TITLE
cloud_cidr_allocator: don't assume gce cidrs are validated

### LINKED ISSUE #29500: ControlPlane node is not ready in scalability tests when run on GCE
In scalability tests, the control-plane node is never initialized to be ready.
We're usually not suffering from them as almost all our tests run 100+ nodes and we tollerate 1% of nodes not initialized correctly.
But this is problematic for tests like:
https://testgrid.k8s.io/sig-scalability-experiments#watchlist-off

Looking into kubelet logs, the reason seem to be:
```
May 11 09:09:13.886270 bootstrap-e2e-master kubelet[2782]: E0511 09:09:13.886233    2782 kubelet.go:2753] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```

FWIW - it seems to be related to some of our preset settings, as, e.g.
https://testgrid.k8s.io/sig-scalability-node#node-containerd-throughput

don't suffer from it.

@kubernetes/sig-scalability @mborsz @Argh4k 
@p0lyn0mial - FYI

### PR DESCRIPTION
**Pull request by aojea**
The cloud_cidr_allocator should not assume that the cidrs allocated for the Nodes are validated and will be always single stack or dual-stack.

/kind bug
/kind cleanup
```release-note
cloud-cidr allocators only considers the first cidr of each IP family to assign to the nodes
```

Fixes: https://github.com/kubernetes/test-infra/issues/29500

### CODE REVIEW

**Comment by basantsa1989** [comment]
@aojea when the provider returns incorrect list of cidrs (like 2 ipv4 addresses), we do know which one of them is the valid ipv4 address that is meant for podCIDR. 

In your changes here, we are assuming it is the first one, is that the expected behavior?

I don't see the current behavior as a "bug". It is designed to handle dual stack and we expect at most 2 cidrs from the providers, one IPv4 and one IPv6.

**Comment by aojea** [comment]
> @aojea when the provider returns incorrect list of cidrs (like 2 ipv4 addresses), we do not know which one of them is the valid ipv4 address that is meant for podCIDR.
> 
> In your changes here, we are assuming it is the first one, is that the expected behavior?
> 
> I don't see the current behavior as a "bug". It is designed to handle dual stack and we expect at most 2 cidrs from the providers, one IPv4 and one IPv6.

/reopen

@basantsa1989  I'm not convinced that this behavior is correct, since there are at least 2 situations this dual-stack assumption leaves a cluster unusable and is confusing for users.
Assuming ordered precedence seems legit, since GCE has this notion of primaries and secondaries too ... we should talk to find a solution but leaving it as "worked as intended" does not sound correct

**Comment by aojea** [comment]
> > @aojea when the provider returns incorrect list of cidrs (like 2 ipv4 addresses), we do not know which one of them is the valid ipv4 address that is meant for podCIDR.
> > In your changes here, we are assuming it is the first one, is that the expected behavior?
> > I don't see the current behavior as a "bug". It is designed to handle dual stack and we expect at most 2 cidrs from the providers, one IPv4 and one IPv6.
> 
> /reopen
> 
> @basantsa1989 I'm not convinced that this behavior is correct, since there are at least 2 situations this dual-stack assumption leaves a cluster unusable and is confusing for users. Assuming ordered precedence seems legit, since GCE has this notion of primaries and secondaries too ... we should talk to find a solution but leaving it as "worked as intended" does not sound correct

I just realized this will move to the cloud-controller-amanger so maybe is not worth the effort to fix it here

**Pull request closed without merging**
