### PR TITLE
Update cadvisor and other repos for klog

### LINKED ISSUE #70264: Use a forked version of glog in kubernetes
Based on the discussion in SIG-Arch on Oct 25 and previous experiment in https://github.com/kubernetes/kubernetes/pull/69333, we should start by forking glog, cleanup the code to suit our use cases and switch over to it. Also see issue https://github.com/kubernetes/kubernetes/issues/61006

Tasks:
- [x] Request a new repository for the forked code in https://github.com/dims/klog in the kubernetes org(?)
- [x] Update k8s.io/klog README.md to explain it is a permanent fork.
- [ ] update github.com/kubernetes/repo-infra/kazel/kazel.go to use klog
- [ ] update k8s.io/gengo/ to use klog
- [ ] update k8s.io/kube-openapi/ to use klog
- [ ] update github.com/google/cadvisor to use klog
- [ ] vendor all the repos above into k/k and switch k/k from glog to klog
- [ ] add verify scripts to prevent adding any new vendor dependencies that use glog

cc @thockin @tallclair @erictune @justinsb @lavalamp 

/kind feature

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

- Move from the old github.com/golang/glog to k8s.io/klog
- klog as explicit InitFlags() so we add them as necessary
- we update the other repositories that we vendor that made a similar
change from glog to klog
  * github.com/kubernetes/repo-infra
  * k8s.io/gengo/
  * k8s.io/kube-openapi/
  * github.com/google/cadvisor
- Entirely remove all references to glog
- Fix some tests by explicit InitFlags in their init() methods

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70264

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Racking up the big numbers!

/lgtm
/approve

**Comment by dims** [comment]
reapply `/lgtm` from @thockin as this was a simple rebase.

**Pull request merged**
