### PR TITLE
kubelet - Remove unused code

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Looks like we have a bunch of unused methods. Let's clean them up

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @Random-Liu 
/assign @derekwaynecarr 

Can one of you please look at this? it's just cleaning up unused code

**Comment by yujuhong** [comment]
/lgtm

Thanks for the cleanup!

**Pull request merged**
