### PR TITLE
Make interface references consistent across the gluster plugin code.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
If you're able to add a comment here:
```
pkg/volume/glusterfs/glusterfs_minmax.go:31:2: exported var ErrNotFound should have comment or be unexported
```

Then that's the last lint issue for `pkg/volume/glusterfs`, and would allow us to add it to `hack/.linted_packages`:
```
echo pkg/volume/glusterfs >> hack/.linted_packages
LC_ALL=C sort -o hack/.linted_packages hack/.linted_packages
```

**Comment by humblec** [comment]
@cblecker Thanks!.. I have addressed the comment :).Also added glusterfs to linted_packages. Please let me know if it ( adding to linted_packages) should not be done by me.

**Comment by humblec** [comment]
@cblecker @rootfs  Can you please bring back `approve` and `lgtm` here? Thanks!

**Comment by cblecker** [comment]
/assign @madhusudancs 
for hack/ approval

**Comment by humblec** [comment]
@k8s-bot kops aws e2e test this

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
.

**Pull request merged**
