### PR TITLE
run govet in golangci-lint instead of ./hack/verify-govet.sh in pull-kubernetes-verify

### LINKED ISSUE #109183: run govet in golangci-lint instead of ./hack/verify-govet.sh in pull-kubernetes-verify
### What would you like to be added?

run govet in golangci-lint instead of ./hack/verify-govet.sh.

### Why is this needed?

govet can be used in golangci-lint. We don't need to run govet with `./hack/verify-govet.sh`
Also, govet itself doesn't have a way to ignore issues from the lint, but golangci-lint has.
In some case, we may want to ignore issues from govet.
For example: https://github.com/kubernetes/kubernetes/pull/108727#discussion_r839305151

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- add govet to golangci-lint config.
- remove ./hack/verify-govet.sh so that pull-kubernetes-verify doesn't run go vet command.
- change `hack/verify-govet-levee.sh` to use `make vet`.

govet can be used in golangci-lint. We don't need to run govet with ./hack/verify-govet.sh
Also, govet itself doesn't have a way to ignore issues from the lint, but golangci-lint has.
In some case, we may want to ignore issues from govet.
For example: https://github.com/kubernetes/kubernetes/pull/108727#discussion_r839305151

#### Which issue(s) this PR fixes:

Fixes #109183

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
Mmm, seems the current `./hack/verify-govet.sh` is not running under `/staging` dir.

**Comment by liggitt** [comment]
> Mmm, seems the current `./hack/verify-govet.sh` is not running under `/staging` dir.

that's concerning... looks like we have exposure to real issues in non-test files:

```
staging/src/k8s.io/apimachinery/pkg/util/managedfields/gvkparser.go:61:39: copylocks: literal copies lock value from *typeSchema: sigs.k8s.io/structured-merge-diff/v4/schema.Schema contains sync.Once contains sync.Mutex (govet)

staging/src/k8s.io/component-base/metrics/counter.go:215:15: copylocks: literal copies lock value from *v: k8s.io/component-base/metrics.CounterVec contains k8s.io/component-base/metrics.lazyMetric contains sync.RWMutex (govet)

staging/src/k8s.io/component-base/metrics/gauge.go:192:24: copylocks: newGaugeFunc passes lock by value: k8s.io/component-base/metrics.GaugeOpts contains sync.Once contains sync.Mutex (govet)
func newGaugeFunc(opts GaugeOpts, function func() float64, v semver.Version) GaugeFunc {
                       ^
staging/src/k8s.io/component-base/metrics/gauge.go:208:24: copylocks: NewGaugeFunc passes lock by value: k8s.io/component-base/metrics.GaugeOpts contains sync.Once contains sync.Mutex (govet)
func NewGaugeFunc(opts GaugeOpts, function func() float64) GaugeFunc {
                       ^
staging/src/k8s.io/component-base/metrics/gauge.go:211:22: copylocks: call of newGaugeFunc copies lock value: k8s.io/component-base/metrics.GaugeOpts contains sync.Once contains sync.Mutex (govet)

staging/src/k8s.io/component-base/metrics/gauge.go:218:13: copylocks: literal copies lock value from *v: k8s.io/component-base/metrics.GaugeVec contains k8s.io/component-base/metrics.lazyMetric contains sync.RWMutex (govet)

staging/src/k8s.io/component-base/metrics/histogram.go:202:17: copylocks: literal copies lock value from *v: k8s.io/component-base/metrics.HistogramVec contains k8s.io/component-base/metrics.lazyMetric contains sync.RWMutex (govet)

staging/src/k8s.io/component-base/metrics/metric.go:172:26: copylocks: assignment copies lock value to r.markDeprecationOnce: sync.Once contains sync.Mutex (govet)

staging/src/k8s.io/component-base/metrics/metric.go:173:17: copylocks: assignment copies lock value to r.createOnce: sync.Once contains sync.Mutex (govet)

staging/src/k8s.io/component-base/metrics/summary.go:196:15: copylocks: literal copies lock value from *v: k8s.io/component-base/metrics.SummaryVec contains k8s.io/component-base/metrics.lazyMetric contains sync.RWMutex (govet)
```

**Comment by liggitt** [comment]
can you spawn a separate issue for resolving the real bugs in non-test files identified by the run

**Comment by liggitt** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/109197

**Comment by liggitt** [comment]
mind opening an issue for https://github.com/kubernetes/kubernetes/pull/109184#issuecomment-1085185835 and tagging sig-cloud-provider?

the remaining issues look like ones we can clean up in 1.25 as part of enabling this

**Comment by sanposhiho** [comment]
@liggitt I opened https://github.com/kubernetes/kubernetes/issues/109229

**Pull request closed without merging**
