### PR TITLE
Introduce testutil package to support metrics testing

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Wrap `prometheus/testutil` in metrics stability framework, that will help:
1. Remove direct reference to Prometheus from k/k.
2. Improve components test cases making them more readable.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by RainbowMango** [comment]
This PR needs an approve label.

@logicalhan

**Pull request merged**
