### PR TITLE
Remove deprecated fields from kubescheduler.config.k8s.io/v1alpha2

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

These flags are deprecated, so they can be removed from new version.

**Which issue(s) this PR fixes**:

Refs #87617

**Does this PR introduce a user-facing change?**:

```release-note
Remove deprecated fields from .leaderElection in kubescheduler.config.k8s.io/v1alpha2
```

### CODE REVIEW

**Comment by liggitt** [comment]
removal looks fine, unit tests are unhappy

**Comment by alculquicondor** [comment]
I forgot to remove the fields from defaults :sweat:

**Comment by alculquicondor** [comment]
Tests passing :smiley: 

friendly ping @liggitt

**Pull request merged**
