### PR TITLE
tests: Updates cuda-vector-add:1.0 image to the promoted registry

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

With this commit, we're no longer using any images from the ``gcr.io/kubernetes-e2e-test-images`` registry.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/96770
Depends On: https://github.com/kubernetes/test-infra/pull/100887

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
/hold

Until the image is built and promoted.

**Comment by pacoxu** [comment]
depends on #100887

**Comment by spiffxp** [comment]
/kind cleanup
/milestone v1.22
As sig-testing chair

https://github.com/kubernetes/kubernetes/pull/100887 should merge soon, but I'm going to assume we need to see that image actually get built, pushed, and promoted before merging this @claudiubelu

**Comment by pacoxu** [comment]
/hold cancel
Since kubernetes/k8s.io#2338 and #100887 are merged.
/lgtm

just wait for the image to be promoted by the post CI.

**Comment by claudiubelu** [comment]
> 
> 
> /hold cancel
> Since [kubernetes/k8s.io#2338](https://github.com/kubernetes/k8s.io/pull/2338) and #100887 are merged.
> /lgtm
> 
> just wait for the image to be promoted by the post CI.

Image has been promoted:

```
docker pull k8s.gcr.io/e2e-test-images/cuda-vector-add:1.0
1.0: Pulling from e2e-test-images/cuda-vector-add
Digest: sha256:0d474909d4b4f59f3cb3e1240396b334f2ce2c7d45b8f11ae41f7e847fd768d9
Status: Image is up to date for k8s.gcr.io/e2e-test-images/cuda-vector-add:1.0
k8s.gcr.io/e2e-test-images/cuda-vector-add:1.0
```

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
/hold
Uh, hang on, removing the e2e registry is probably release-note-worthy

**Comment by spiffxp** [comment]
/approve cancel
Can you keep this PR just to the image move? 

Removal of the registry needs some more work and I would rather land this first.

```
$ rg -l kubernetes-e2e-test-images
hack/testdata/pod-with-large-name.yaml
staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
test/e2e/testing-manifests/serviceloadbalancer/netexecrc.yaml
test/e2e/testing-manifests/kubectl/agnhost-primary-pod.yaml
test/e2e/testing-manifests/ingress/multiple-certs/rc.yaml
test/e2e/testing-manifests/ingress/http2/rc.yaml
test/e2e/testing-manifests/ingress/http/rc.yaml
test/e2e/testing-manifests/ingress/pre-shared-cert/rc.yaml
test/e2e/testing-manifests/ingress/neg/rc.yaml
test/e2e/testing-manifests/ingress/neg-clusterip/rc.yaml
test/e2e/testing-manifests/ingress/neg-exposed/rc.yaml
test/e2e/testing-manifests/ingress/static-ip/rc.yaml
test/e2e/testing-manifests/ingress/gce/static-ip-2/rc.yaml
test/fixtures/doc-yaml/user-guide/multi-pod.yaml
test/fixtures/pkg/kubectl/cmd/auth/rbac-resource-plus.yaml
test/images/windows/Makefile
test/images/README.md
test/images/Makefile
```

**Comment by claudiubelu** [comment]
> 
> 
> /approve cancel
> Can you keep this PR just to the image move?
> 
> Removal of the registry needs some more work and I would rather land this first.
> 
> ```
> $ rg -l kubernetes-e2e-test-images
> hack/testdata/pod-with-large-name.yaml
> staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
> test/e2e/testing-manifests/serviceloadbalancer/netexecrc.yaml
> test/e2e/testing-manifests/kubectl/agnhost-primary-pod.yaml
> test/e2e/testing-manifests/ingress/multiple-certs/rc.yaml
> test/e2e/testing-manifests/ingress/http2/rc.yaml
> test/e2e/testing-manifests/ingress/http/rc.yaml
> test/e2e/testing-manifests/ingress/pre-shared-cert/rc.yaml
> test/e2e/testing-manifests/ingress/neg/rc.yaml
> test/e2e/testing-manifests/ingress/neg-clusterip/rc.yaml
> test/e2e/testing-manifests/ingress/neg-exposed/rc.yaml
> test/e2e/testing-manifests/ingress/static-ip/rc.yaml
> test/e2e/testing-manifests/ingress/gce/static-ip-2/rc.yaml
> test/fixtures/doc-yaml/user-guide/multi-pod.yaml
> test/fixtures/pkg/kubectl/cmd/auth/rbac-resource-plus.yaml
> test/images/windows/Makefile
> test/images/README.md
> test/images/Makefile
> ```

Sure, done.

Most of the changes needed for that are in this PR: https://github.com/kubernetes/kubernetes/pull/100470 . It just needs a rebase, and to include the other changes that I've dropped from this PR. I'm not sure if the author of that PR is still around, but if needed, I can do that as well, since I've left some comments with required updates that haven't been addressed since.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold cancel

**Comment by spiffxp** [comment]
> I'm not sure if the author of that PR is still around, but if needed, I can do that as well, since I've left some comments with required updates that haven't been addressed since.

Opening a new PR to supersede would be appreciated.  I don't expect them to get back to it sooner than O(weeks)

**Pull request merged**
