### PR TITLE
Bump cfssl to be compatible with Go 1.10

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by cblecker** [comment]
@sttts staging godeps needs to be updated

**Comment by cblecker** [comment]
/lgtm cancel
Stopping retesting loop as verify job failure is legitimate

**Comment by sttts** [comment]
> I see you have this in the 1.11 milestone. Is there any problem with this being merged before freeze (and therefore being in 1.10)?

We pull in a security related library. I would prefer to have some soak time. Do we care about Go 1.10 for Kube 1.10?

**Comment by cblecker** [comment]
@sttts We won't be moving to go1.10 for 1.10. That will be 1.11. Will this break though, if it's merged without go1.10? Doesn't look like it if tests pass.

**Comment by sttts** [comment]
> Doesn't look like it if tests pass.

The last words before the flakes started 🙂

**Comment by cblecker** [comment]
/lgtm
/hold

Heh.. If it's not needed, then we can just hold until after freeze :)

**Review by cblecker — APPROVED** [review]

**Comment by sttts** [comment]
> Heh.. If it's not needed, then we can just hold until after freeze :)

Yeah, would avoid unnecessary changes now. We will have flake hell anyway the next days.

**Comment by cblecker** [comment]
/lgtm cancel
staging godeps needs to be updated

**Pull request merged**
