### PR TITLE
Automated cherry pick of #34994 #35161 #35224 #35321 #35646 #35652 #35349 #35350 #35717 #35819 #35813 #35821 #35724 #36267 nov premounter

### PR DESCRIPTION
**Pull request by jingxu97**
Make "mounter" change into one cherrypick

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37249)

### CODE REVIEW

**Comment by jessfraz** [comment]
I fixed the base branch to be the release branch I assume that's what you intended

**Comment by jingxu97** [comment]
@jessfraz actually this is a cherrypick based on a master branch (a commit right before the first commit for this while PR), just try to put everything together into one PR. A second step is to cherrypick this PR to release 1.4

**Comment by jessfraz** [comment]
But aren't these already merged into master?

**Comment by mtaufen** [comment]
@jessfraz creating this PR was just a hack to first bundle the PRs prior to cherry-picking to 1.4. This cut down on the initial number of conflicts to resolve and helped us avoid having to restart the cherry-pick from the beginning in the event of a mistake. https://github.com/kubernetes/kubernetes/pull/37336 is the end result that will actually need to be cherry-picked.

**Comment by jingxu97** [comment]
close this PR in favor of PR #37336

**Pull request closed without merging**
