### PR TITLE
Automated cherry pick of #126749: fix v1a3 ResourceSliceList metadata field name

### PR DESCRIPTION
**Pull request by thockin**
Cherry pick of #126749 on release-1.31.

#126749: fix v1a3 ResourceSliceList metadata field name

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
The resource/v1alpha3.ResourceSliceList filed which should have been named "metadata" but was instead named "listMeta" is now properly "metadata".
```

### CODE REVIEW

**Comment by thockin** [comment]
@kubernetes/release-managers

**Comment by aojea** [comment]
> 
> Kubernetes e2e suite: [It] [sig-node] NodeProblemDetector [NodeFeature:NodeProblemDetector] should run without error expand_less	2m11s
> { failed [FAILED] an error on the server ("Internal Error: failed to get imageFs stats: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory\"") has prevented the request from succeeding (get nodes e2e-96554dd2cc-674b9-minion-group-x9lb:10250)

/test pull-kubernetes-e2e-gce

seems unrelated

**Comment by thockin** [comment]
ping @kubernetes/release-managers ICYMI

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
