### PR TITLE
Update kubectl docs.

### PR DESCRIPTION
**Pull request by MikeJeffrey**
Updated the docs for clarity, and standardized the examples with 4 leading spaces and // for comments. The 4 spaces will affect the doc generation script, but should be a positive change overall.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Looks good so far. You'll want to rebase and squash into a single commit. 14 is overkill.

**Comment by jlowdermilk** [comment]
Also, travis is unhappy because you need to regenerate `kubectl.md`. Run `hack/run-gendocs.sh` to fix.

**Comment by kargakis** [comment]
"You'll want to rebase and squash into a single commit. 14 is overkill."
Furthermore wouldn't it have been even better if the commit history was clearer and not overflown by merge commits?

**Comment by MikeJeffrey** [comment]
Yup, I messed up the rebase/squash. Will fix.

**Comment by kargakis** [comment]
@MikeJeffrey sorry for the misunderstanding but I wasn't referring specifically to your commits found in this pr but all the commits in general in Kubernetes.

**Comment by brendandburns** [comment]
@kargakis (this is totally off-topic, so I appologize to @MikeJeffrey :P) The reason that we prefer a small number of commits is that in the case of rollback, it's quite tricky to figure out which bits you need to rollback if there are large number of commits.

I would argue that each PR should be a small, focused modification of the code, and as such, really only deserving a single commit.  IMHO, if we find ourselves with PRs that really feel like they are logically multiple commits, then that is a good indication that they really ought to be multiple PRs.

Hope that helps explain our philosophy around git management in the project.  I'm definitely open to suggestions, though, if you have concrete use cases that you'd like to see improved.

Best!
--brendan

**Comment by kargakis** [comment]
@brendanburns again there is a misunderstanding which probably comes from the fact that I don't explain myself in a clear manner. I totally agree with what you said about small commits ie. isolation of different functionality etc. What I meant is that if you take a look at the history of the Kubernetes repository, it's overflown by `Merge pull request*` commits which makes it difficult to iterate over the real commits.

**Comment by brendandburns** [comment]
@kargakis ah, that's from "merge" button on github.  I don't know if there is a way to avoid having those commits in the log.  If there is a way to achieve that, while still using the github UX, I'm definitely open to it...

Thanks!
--brendan

**Comment by MikeJeffrey** [comment]
Looks like the build failed, but I can't see why. I ran hack/run-gendocs.sh and added the kubectl.md file to this commit.

**Comment by brendandburns** [comment]
LGTM, but needs rebase.

**Comment by brendandburns** [comment]
oops, nm, looks ok.  Will merge in the AM.

**Comment by bgrant0607** [comment]
Sorry, needs to be rebased again.

**Comment by MikeJeffrey** [comment]
Didn't mean to close this.

**Pull request closed without merging**
