### PR TITLE
Automated cherry pick of #90476: fix backoff manager timer initialization race

### PR DESCRIPTION
**Pull request by zhan849**
Cherry pick of #90476 on release-1.18.

#90476: fix backoff manager timer initialization race

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by zhan849** [comment]
Hi @liggitt , seems there are labels haven’t released. Can you pls check? Thanks!

**Comment by liggitt** [comment]
the @kubernetes/patch-release-team is responsible for managing this PR in the release branch at this point

**Pull request merged**
