### PR TITLE
Fixed golint failures for pkg/proxy/apis/config/v1alpha1

### PR DESCRIPTION
**Pull request by c3y1huang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixed golint failures for `pkg/proxy/apis/config/v1alpha1`

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:
This is my first PR to Kubernetes. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```

```

### CODE REVIEW

**Comment by tanjunchen** [comment]
> **What type of PR is this?**
> /kind cleanup
> 
> **What this PR does / why we need it**:
> Fixed golint failures for `pkg/proxy/apis/config/v1alpha1`
> 
> **Which issue(s) this PR fixes**:
> Fixes #68026
> 
> **Special notes for your reviewer**:
> This is my first PR to Kubernetes.
> 
> **Does this PR introduce a user-facing change?**:
> 
> ```
> None
> ```
> 
> **Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> 
> ```
> 
> ```
First:
Please Use Ref #68026
Second:
Sig up CNCF

**Comment by c3y1huang** [comment]
I signed it

**Comment by c3y1huang** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I signed it

**Comment by c3y1huang** [comment]
("I signed it")

**Comment by c3y1huang** [comment]
> > **What type of PR is this?**
> > /kind cleanup
> > **What this PR does / why we need it**:
> > Fixed golint failures for `pkg/proxy/apis/config/v1alpha1`
> > **Which issue(s) this PR fixes**:
> > Fixes #68026
> > **Special notes for your reviewer**:
> > This is my first PR to Kubernetes.
> > **Does this PR introduce a user-facing change?**:
> > ```
> > None
> > ```
> > 
> > 
> > **Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> > ```
> > 
> > ```
> 
> First:
> Please Use Ref #68026
> Second:
> Sig up CNCF

Thanks, fixed.

**Comment by dcbw** [comment]
@c3y1huang I believe these files are generated files, so I think you might have to change the generator code to conform to golint :(

**Comment by thockin** [comment]
I appreciate the intent, but the underscores are part of the code generation system, and not something we want to "fix" at the moment.

**Comment by c3y1huang** [comment]
Thanks for the heads up. I will look at something else outside code generation system.

**Pull request closed without merging**
