### PR TITLE
Merge release 0.18 to master

### PR DESCRIPTION
**Pull request by brendandburns**
@zmerlynn @eparis not sure what went wrong that I had to manually fix up the version.  Might be that we never cut a release-0.18 branch until the 0.18.1 release...

### CODE REVIEW

**Comment by eparis** [comment]
i'll take a look....

**Comment by zmerlynn** [comment]
LGTM, but @eparis can you make sure it looks good?

**Comment by eparis** [comment]
yeah, something got to be wrong since he had to do a manual fixup.  I'll see what it was...

**Comment by eparis** [comment]
3ish things?

1. @jlowdermilk didn't follow all of the instructions given by build/mark-new-version.sh when cutting v0.18 and thus the release branch wasn't created correctly back then.
2. @brendandburns created the branch forking from 754d3ce99ee50f392369868bf6ba1e866801b086 (v0.18) when it should have been forked from 24712e81700bf4a469aad30d7e3ca905e305ce01 (v0.18.0+). 
3. the release-0.18 branch includes e1966ccfa0ffcad5a162ff6dbd22e7872990e3b3 which doesn't seem like the right thing (probably you trying to fix this versions stuff?

None of this REALLY matters as the code seems ok. What it did cause was a conflict in pkg/version/base.go (because master changed it in 24712e81700bf4a469aad30d7e3ca905e305ce01) and obviously this new release-0.18 branch changed it as well. Since the instructions say to automatically resolve conflicts with master (git merge -s recursive -X ours) that means @brendanburns updates in the release-0.18 branch were 'solved' with what was in master (aka, the wrong thing)

@brendandburns fix here is ok. History is a little jacked and the release-0.18 branch has some useless thing in it, but it seems to get the code where it belongs.  If you want (and honestly it does not really matter) we can

- force push 3e5707be5bd051d96b8ba96ed50273e3b6f2dae5 back to the release-0.18
- take https://github.com/GoogleCloudPlatform/kubernetes/pull/9228 instead of this PR

My branch solved the merge conflicts manually.

Either is LGTM I think....

**Comment by brendandburns** [comment]
thanks for the git analysis @eparis 
I created the release-0.18 branch using the v0.18.0 tag, which I guess was the wrong thing to do (but the github UI makes it soooo easy ;)

I'm just going to merge this, we'll do better on 0.19

**Pull request merged**
