### PR TITLE
Fix typo

### LINKED ISSUE #52136: Fixed some small comment typo.
Typo fix. Will add the PR links.

### PR DESCRIPTION
**Pull request by xingzhou**
Fixed typo.

Fixed #52136 

**Release note**:
```
None
```

### CODE REVIEW

**Review by resouer — APPROVED** [review]
ping @yujuhong for approve

**Comment by xingzhou** [comment]
Anything updated for the review and merge process? I saw:
"Milestone is for a future release and cannot be merged"

**Comment by resouer** [comment]
@xingzhou  We are under 1.8 code freeze, no code should be ship except urge fix. Please stay tuned.

**Pull request merged**
