### PR TITLE
Add LinuxOnly tag to e2e testing session affinity

### PR DESCRIPTION
**Pull request by mgdevstack**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Adds [LinuxOnly] tag to e2e which are testing session affinity.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
- Windows does not support session affinity.
_[Source]_: https://github.com/kubernetes/kubernetes/pull/76443#issuecomment-526124281
 - This PR is blocking #76443 to get merged.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/area conformance
/sig node
/sig testing
/priority important-soon
@kubernetes/sig-node-pr-reviews
@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Code looks good to me :)

I will let someone approve actually setting these tests to LinuxOnly (although it certainly makes sense to me if that func isn't supported by windows).

Should we add a issue to make it so these tests eventually support windows or is that already a WIP?

**Comment by mgdevstack** [comment]
ETA for its support in Windows might be 2020 or later based on @PatrickLang's https://github.com/kubernetes/kubernetes/pull/76443#issuecomment-526403028

It would be great if SIG-Windows tracks its process.

**Comment by johnbelamaric** [comment]
/hold
/lgtm
/approve

Needs to go in for 1.17.

**Pull request merged**
