### PR TITLE
[WIP] Update salt for Node Autoprovisioning support in CA

### PR DESCRIPTION
**Pull request by bskiba**
**What this PR does / why we need it**:
Add flags for Node Autoprovisioning to Cluster Autoscaler saltbase

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by bskiba** [comment]
assign @MaciekPytel

**Comment by bskiba** [comment]
assign @aleksandra-malinowska

**Comment by mwielgus** [comment]
Let's put this CL on hold for a moment. It might be simpler for now to just pass all of the required stuff via autoscaler_mig_config and get this stuff running in alpha. We can get back here in the fullness of time.

Sorry for confusion.

**Pull request closed without merging**
