### PR TITLE
refactor: v1 event expansion.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Cleanup v1 event client, according to the comments in #83065

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/sig api-machinery
/assign @liggitt 
/assign @yastij

### CODE REVIEW

**Comment by yastij** [comment]
@liggitt - do we want to maintain this, given the plans for `events.k8s.io` ?

**Comment by liggitt** [comment]
marking that method as deprecated seems fine

/ok-to-test
/lgtm
/approve
/priority backlog

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
