### PR TITLE
WIP: Continue to support (deprecated) publicIPs

### PR DESCRIPTION
**Pull request by justinsb**
Not doing so breaks e2e tests and people that may be using them,
even though we will eventually want to stop supporting this now
that we have better alternatives for typical use cases (NodePort)

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM - merging to try and get e2e green.

**Comment by lavalamp** [comment]
@thockin can you do a retroactive review?

**Comment by lavalamp** [comment]
tentative result: only one run but services.sh passed and it was solid red before, so that's an improvement, at least.

**Comment by thockin** [comment]
LGTM

**Pull request merged**
