### PR TITLE
vendor: bump runc/libcontainer to v1.2.1

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Bump runc/libcontainer to v1.2.0.

For one thing, this release decouples device management from libcontainer/cgroups. You can see the result of this in a dropped cilium/ebpf dependency (which is only needed for device management).

#### Special notes for your reviewer:

1. ~~I'm also including #128237 here; will rebase once it's merged.~~ Rebased.

2. It looks like a bug in `hack/lint-dependencies.sh` script -- it insists `golang.org/x/exp` is a dependency of `github.com/opencontainers/runc`, while in fact it is only used by `github.com/cilium/ebpf` which is being removed here. Because of this bug, I had to add opencontainers/runc to hack/unwanted-dependencies.json under x/exp.

3. ~~A new dependency golang.org/x/execabs is being removed in the next patch release (https://github.com/opencontainers/runc/pull/4465)~~

4. The issue with containerd and userns in runc v1.2.0 is fixed in v1.2.1.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by dims** [comment]
@kolyshkin Are you ok with folks running Containerd 1.6/1.7 with older runc versions with 1.2.0 runc vendored into kubelet? ( Want to make sure we don't end up with something like https://github.com/opencontainers/runc/issues/3849 )

**Comment by kolyshkin** [comment]
> @kolyshkin Are you ok with folks running Containerd 1.6/1.7 with older runc versions with 1.2.0 runc vendored into kubelet? ( Want to make sure we don't end up with something like [opencontainers/runc#3849](https://github.com/opencontainers/runc/issues/3849) )

As of now we're not aware of any issues similar to opencontainers/runc#3849.

**Comment by liggitt** [comment]
> 2\. It looks like a bug in `hack/lint-dependencies.sh` script -- it insists `golang.org/x/exp` is a dependency of `github.com/opencontainers/runc`, while in fact it is only used by `github.com/cilium/ebpf` which is being removed here. Because of this bug, I had to add opencontainers/runc to hack/unwanted-dependencies.json under x/exp.

fwiw, it's not really a bug, runc still depends on ebpf (https://github.com/opencontainers/runc/blob/v1.2.0/libcontainer/cgroups/devices/ebpf_linux.go#L11), so all of ebpf's dependencies get flattened into runc's go.mod file and passed on to it's dependencies according to `go mod graph`.

**Comment by SergeyKanzhelev** [comment]
we really looking forward to adopt the 1.2.0 as it is fixes a few bugs.

lgtm and approve from SIG Node.

@samuelkarp is containerd switching to it? Any concerns from containerd perspective? Also we need to make sure our e2e-s are running against the new runc.

**Comment by SergeyKanzhelev** [comment]
@samuelkarp mentioned offline there may be a bug with 1.2.0. @samuelkarp can you please link it here?

**Comment by samuelkarp** [comment]
https://github.com/opencontainers/runc/issues/4466

**Comment by dims** [comment]
@SergeyKanzhelev please see https://github.com/containerd/containerd/pull/10877 and discussion on slack  https://cloud-native.slack.com/archives/CGEQHPYF4/p1729607023643899

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev please see [containerd/containerd#10877](https://github.com/containerd/containerd/pull/10877) and discussion on slack https://cloud-native.slack.com/archives/CGEQHPYF4/p1729607023643899

@dims I think it will be best to wait for containerd to confirm it is ok to update. It will be best to have reference in k/k matching the actual binary we are testing in e2e. Do you agree or I am missing something?

**Comment by dims** [comment]
@SergeyKanzhelev i agree with you!

**Comment by dims** [comment]
xref: https://github.com/opencontainers/runc/issues/4475

**Comment by dims** [comment]
@SergeyKanzhelev `containerd to confirm it is ok to update` is done now. https://github.com/containerd/containerd/pull/10877 is landing

**Comment by SergeyKanzhelev** [comment]
I guess there is not much reason to hold - let's get more soak time by merging on weekend.

/unhold

**Pull request merged**
