### PR TITLE
Automated cherry pick of #62655: Modify the kubeadm upgrade DAG for the TLS Upgrade

### PR DESCRIPTION
**Pull request by stealthybox**
Cherry pick of #62655 on release-1.10.

#62655: Modify the kubeadm upgrade DAG for the TLS Upgrade

**Release note**:
```release-note
Action Required: kubeadm upgrade no longer supports downgrading 1.10 clusters to 1.9 clusters due to an incompatibility between the kubernetes 1.9 and 1.10 featureGates struct. Please backup /etc/kubernetes/manifests, the etcd database, and the kubeadm-config configmap if you anticipate a need to rollback.
```

### CODE REVIEW

**Comment by stealthybox** [comment]
/retest

`ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: Unable to find the server at accounts.google.com`

**Comment by stealthybox** [comment]
```bash
cd ~/go/src/k8s.io/kubernetes
bazel build //cmd/kubeadm --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64

cd ~/repos
git clone git@github.com:stealthybox/vagrant-kubeadm-testing.git
cd vagrant-kubeadm-testing

issue=cherry-63110 ./copy_kubeadm_bin.sh
vagrant up && vagrant ssh -- -tt sudo bash
# root@vagrant:/vagrant#
target_bin=/vagrant/bin/cherry-63110_kubeadm /vagrant/testTLSUpgradeNoDowngrade.sh
```

#### /vagrant/testTLSUpgradeNoDowngrade.sh
```bash
#!/bin/bash
# Usage:
#   target_bin=/vagrant/bin/TLSUpgrade_kubeadm /vagrant/testTLSUpgradeNoDowngrade.sh
set -ex

source_bin=${source_bin:-kubeadm}
target_bin=${target_bin}

[ "$source_bin" = "" ] && echo "please set source_bin" && exit 1
[ "$target_bin" = "" ] && echo "please set target_bin" && exit 2

${source_bin} reset \
  && ${source_bin} init --kubernetes-version 1.9.1 \
  && kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

sleep 120 # wait for CNI and Node Ready
${target_bin} upgrade apply --yes 1.10.0  # non-TLS to TLS
sleep 60 # wait for cluster components to stabilize
${target_bin} upgrade apply --yes 1.10.1 # TLS to TLS

echo
echo Test Passed
```

**Comment by timothysc** [comment]
@liztio please see the comment on slack.

**Comment by stealthybox** [comment]
^ link to [slack comment](https://kubernetes.slack.com/archives/C13J86Z63/p1524617195000021)

also added to the [agenda](https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit#heading=h.kk5v11vg5l2d) for tomorrow's call

**Review by timothysc — COMMENTED** [review]
/approve 

Waiting on conversation before lgtm

**Review by timothysc — APPROVED** [review]
/lgtm

**Pull request merged**
