### PR TITLE
Correct wrong syntax

### PR DESCRIPTION
**Pull request by zhoumingcheng**
Signed-off-by: zhoumingcheng <zhoumingcheng@beyondcent.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
For the overall rigour of the code
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Thank you！
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zhoumingcheng** [comment]
/assign @deads2k
please take a look, thanks!

**Comment by zhoumingcheng** [comment]
/assign @smarterclayton
please take a look, thanks!

**Review by logicalhan — APPROVED** [review]
/lgtm 
/approve

**Comment by zhoumingcheng** [comment]
/assign @liggitt
please take a look, thanks!

**Pull request merged**
