### PR TITLE
Fix comments about default mount propagation

### PR DESCRIPTION
**Pull request by gnufied**
We changed Private to be default mount propagation scheme but never got around to updating
docs and comments.

/sig storage

cc @jsafrane @liggitt 

```release-note
None
```

### CODE REVIEW

**Comment by liggitt** [comment]
api-machinery doesn't own storage APIs

**Comment by liggitt** [comment]
@kubernetes/sig-storage-api-reviews 

/lgtm
this should be picked to 1.10 and 1.11

**Comment by gnufied** [comment]
@liggitt sure. I will cherry pick.

**Pull request merged**
