### PR TITLE
AWS kube-up: Allow KUBE_VPC_CIDR to be specified (experimental)

### PR DESCRIPTION
**Pull request by c4po**
https://github.com/kubernetes/kubernetes/issues/23478

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23867)

### CODE REVIEW

**Comment by justinsb** [comment]
@c4po this looks good but apparently you haven't signed the CLA?

**Comment by c4po** [comment]
I signed it.

**Comment by justinsb** [comment]
ok to test

**Comment by justinsb** [comment]
I've realized we also have #23362, which was technically earlier...

**Pull request closed without merging**
