### PR TITLE
remove unused funcs for e2e predicates

### PR DESCRIPTION
**Pull request by 249043822**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
these funcs are not referenced by predicate testcases now

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE
```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
/lgtm

**Comment by 249043822** [comment]
@chendave I have rebased to make all tests success

**Pull request merged**
