### PR TITLE
promote crd discovery e2e to conformance

### PR DESCRIPTION
**Pull request by roycaihw**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Promote the CRD discovery doc e2e test (which merged in https://github.com/kubernetes/kubernetes/pull/82036) to the conformance suite, to cover all endpoints for conformance. This is the one remaining bit-flipping mentioned in https://github.com/kubernetes/kubernetes/pull/81864#issuecomment-526361962

[Run history of that test](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=5&sort-by-flakiness=&include-filter-by-regex=&include-filter-by-regex=CustomResource.*discovery)

/area conformance

@kubernetes/sig-architecture-pr-reviews @kubernetes/sig-api-machinery-pr-reviews @kubernetes/cncf-conformance-wg

/cc @johnbelamaric @liggitt 
/assign @smarterclayton 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm

**Comment by BenTheElder** [comment]
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-e2e-gce
(soak testing)

**Pull request merged**
