### PR TITLE
Tell kubernetes-master not to wait on flannel.

### PR DESCRIPTION
**Pull request by bprashanth**

### CODE REVIEW

**Comment by bprashanth** [comment]
do not check-in, default provider is set to flannel for e2e testing

**Comment by bprashanth** [comment]
1 e2e failure is kubectl test flake:
```
14:01:46 Kubectl client
14:01:46 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:914
14:01:46   Kubectl describe
14:01:46   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:563
14:01:46     should check if kubectl describe prints relevant information for rc and pods [Conformance] [It]
14:01:46     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:562
14:01:46 
14:01:46     Dec 12 22:01:04.385: Failed to find Events: in Name:		redis-master
14:01:46     Namespace:	e2e-tests-kubectl-ujaqz
14:01:46     Image(s):	redis
14:01:46     Selector:	app=redis,role=master
14:01:46     Labels:		app=redis,role=master
14:01:46     Replicas:	1 current / 1 desired
14:01:46     Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
14:01:46     No volumes.
14:01:46     No events.
14:01:46 
```

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Comment by bprashanth** [comment]
Removed test settings, PTAL

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/18593

**Comment by thockin** [comment]
LGTM

**Comment by bprashanth** [comment]
Open closing to get tests again, this has been stuck in the queue long enough so I'm going to merge on green

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Pull request merged**
