### PR TITLE
Automated cherry pick of #71923: diff: Fix overlapping filenames

### PR DESCRIPTION
**Pull request by apelisse**
Cherry pick of #71923 and #71974 on release-1.13.

#71923: diff: Fix overlapping filenames
#71974 

```release-note
Fix overlapping filenames in diff if multiple resources have the same name.
```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm

thanks

**Comment by tpepper** [comment]
@apelisse the bot's not picking up release notes apparently when there are multiple PR's commites being cherry picked.  Can you add a release note to this PR's description text?

**Pull request merged**
