### PR TITLE
Automated cherry pick of #65289: Add a GPUClusterDowngrade test.

### PR DESCRIPTION
**Pull request by jiayingz**
Cherry pick of #65289 on release-1.11.

#65289: Add a GPUClusterDowngrade test.

### CODE REVIEW

**Review by rohitagarwal003 — APPROVED** [review]
/lgtm

**Comment by jberkus** [comment]
Holding for 1.11.1.  Do not approve cherrypick until after 1.11.0 release.

**Comment by jiayingz** [comment]
@vishh or @tpepper could you help approve for cherry-pick? Thanks!

**Comment by jiayingz** [comment]
@tpepper could you help reset the v1.11 milestone? Thanks!

**Review by foxish — APPROVED** [review]

**Pull request merged**
