### PR TITLE
Move install of version handler to genericapiserver

### PR DESCRIPTION
**Pull request by jianhuiz**
This is to satisfy kbuectl verification

Please review only the last commit.
#19313 #23653

@nikhiljindal @quinton-hoole, @deepak-vij, @XiaoningDing, @alfred-huangjian @mfanjie @huangyuqi @colhom

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
`hack/verify-govet.sh` failed which I assume is due to https://github.com/kubernetes/kubernetes/pull/23847.

You dont really need the commits in https://github.com/kubernetes/kubernetes/pull/23847 to be able to make this change, right?

**Comment by nikhiljindal** [comment]
This still duplicates the call in both federated-apiserver and master.go.
How about splitting InstallSupport() into InstallVersionHandler and InstallHealthChecks?
Then we can call InstallVersionHandler (which is needed by both) in genericapiserver and call InstallHealthChecks only in master.go.

**Comment by jianhuiz** [comment]
the test requires TestRun() in server_test.go which was added in #23847

**Comment by jianhuiz** [comment]
Do you want me to do it in this one or will you create a new PR?

> This still duplicates the call in both federated-apiserver and master.go.
How about splitting InstallSupport() into InstallVersionHandler and InstallHealthChecks?
Then we can call InstallVersionHandler (which is needed by both) in genericapiserver and call InstallHealthChecks only in master.go.

**Comment by nikhiljindal** [comment]
Feel free to do it in this one.

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Pull request merged**
