### PR TITLE
Plumb node labels through salt

### PR DESCRIPTION
**Pull request by j3ffml**
Expose `--node-labels` flag on kubelet via a startup script env var.

cc @fabioy @roberthbailey

### CODE REVIEW

**Comment by dchen1107** [comment]
@jlowdermilk Can you provide more information on your use cases here?

**Comment by jlowdermilk** [comment]
@dchen1107, the use case is custom labels for scheduling constraints. Basically making [node selection](http://kubernetes.io/v1.1/docs/user-guide/node-selection/README.html) easier by putting labels on nodes at cluster creation time.

**Comment by roberthbailey** [comment]
LGTM but CI seems unhappy.

**Comment by jlowdermilk** [comment]
Change was just rebase, re-adding lgtm.

**Comment by roberthbailey** [comment]
still lgtm for the record.

**Comment by jlowdermilk** [comment]
pr that caused the original rebase got reverted.

**Comment by jlowdermilk** [comment]
@k8s-oncall, can I get a manual merge pretty please? I've had to rebase 3 times while waiting for mergebot.

**Comment by dchen1107** [comment]
lgtm again.

**Comment by dchen1107** [comment]
Merged it manually to unblock gke work. :-)

**Pull request merged**
