### PR TITLE
Remove duplicate value assginment when validating limitrange

### PR DESCRIPTION
**Pull request by hurf**
It's unnecessary to get the quantities again from limit.

### CODE REVIEW

**Comment by hurf** [comment]
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
I missed this clean-up when porting yesterday.  Thanks for the fix.

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

**Pull request merged**
