### PR TITLE
Automated cherry pick of #53167 upstream release 1.8

### PR DESCRIPTION
**Pull request by dashpole**
cherrypick of #53167

```release-note
BugFix: Exited containers are not Garbage Collected by the kubelet while the pod is running
```

### CODE REVIEW

**Comment by abgworrall** [comment]
/assign @jpbetz 
This is patch manager territory now ;)

**Comment by jpbetz** [comment]
We are starting 1.8.2 code freeze. Removing `cherrypick-approved` label temporarily on all PRs that are not yet ready to merge either due to missing approvals or failing tests. This label will be added back to this PR after 1.8.2 is released. See [Release Cut](https://github.com/kubernetes/sig-release/blob/master/ephemera/patch-release-manager.md#release-cut) for process details.

**Comment by jpbetz** [comment]
Cherry pick approved for 1.8.  This needs lgtm and approval from appropriate owners before merge-bot will activate.

**Pull request merged**
