### PR TITLE
[1.13] Automated cherry pick of #75144: kubelet: updated logic of verifying a static critical pod

### PR DESCRIPTION
**Pull request by Huang-Wei**
Cherry pick of #75144 on release-1.13.

#75144: kubelet: updated logic of verifying a static critical pod

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/assign @derekwaynecarr
for approval

/assign @tpepper
for 1.13 patch release

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by Huang-Wei** [comment]
@feiskyer this PR is not complete. I will combine another cherrypick PR along with this one. Thanks for reviewing. Will ping you later.

**Comment by Huang-Wei** [comment]
/unhold

Good to go now.

**Comment by Huang-Wei** [comment]
/hold cancel

Good to be merged now.

**Comment by Huang-Wei** [comment]
@derekwaynecarr could you help to /approve? @tpepper wants to include this in upcoming 1.13.5 release. Thanks!

**Pull request merged**
