### PR TITLE
modify logs

### PR DESCRIPTION
**Pull request by caiyixiang**
Modify some log first letter capitals, consistent with this file

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by resouer** [comment]
But I was told that ERROR should not start with upper letter ...

**Comment by caiyixiang** [comment]
@resouer hi,I'm not sure if need first letter capital, but some of the same files have a capital start and some lower case starts. I think it's better to keep it consistent

**Comment by caiyixiang** [comment]
@resouer and others start with capital letters in this file

**Comment by resouer** [comment]
I will leave @thockin for decision, he's the big boss 😆

**Comment by caiyixiang** [comment]
@thockin @resouer  ok ,thanks.In fact, I found some other files have the same problem, I would like to know whether there is a fixed standard?

**Comment by thockin** [comment]
NAK.  Errors should start lower-case.  I read this in some go style guide at some point and I agree.  I think logs should, too, but that's a bigger fight.

I'd welcome a PR to change errors in the other direction, though :)

**Pull request closed without merging**
