### PR TITLE
client-go/tools/record: use struct as LRU key

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind feature
/kind bug

#### What this PR does / why we need it:

increase performance and avoid ambiguity

e.g.: these two produce the same key in the original code:
* Component="ab", Host="c"
* Component="a", Host="bc"

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Users should change their code to change the return type of the callbacks. So, this is a breaking that is easy to fix. 

#### Does this PR introduce a user-facing change?

```release-note
EventSpamKeyFunc and EventAggregatorKeyFunc can return any comparable object now. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by huww98** [comment]
/cc @olagacek
as you introduce the SpamKeyFunc

**Comment by huww98** [comment]
Hi @logicalhan , PTAL~. Thanks

**Comment by aojea** [comment]
> * Component="ab", Host="c"
> * Component="a", Host="bc"

/hold

do we have more evidence of key collision or is this just an assumption? I can see there are multiple fields joined to create the key
```
	return strings.Join([]string{
		event.Source.Component,
		event.Source.Host,
		event.InvolvedObject.Kind,
		event.InvolvedObject.Namespace,
		event.InvolvedObject.Name,
		event.InvolvedObject.FieldPath,
		string(event.InvolvedObject.UID),
		event.InvolvedObject.APIVersion,
		event.Type,
		event.Reason,
		event.Message,
```

> So, this is a breaking that is easy to fix.

if you maintain a lot of downstream projects it is a lot if easy to fix things to do :)

**Comment by huww98** [comment]
> do we have more evidence of key collision or is this just an assumption? I can see there are multiple fields joined to create the key

I have not seen real collision in real project. But it is easy to construct a reproducer. I just read the code when investigating this issue https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/969#issuecomment-2056331501 . And I create this PR because I think the implementation is not ideal.

The earlier we make the change, the less we break :) And I think not that many projects are using `EventSpamKeyFunc` or `EventAggregatorKeyFunc`

**Comment by aojea** [comment]
> But it is easy to construct a reproducer.

then there should be a test with a reproducer ... but I still see fields that are unique,

```
                event.InvolvedObject.Kind,
		event.InvolvedObject.Namespace,
		event.InvolvedObject.Name,
		string(event.InvolvedObject.UID),
```

> The earlier we make the change, the less we break :) And I think not that many projects are using `EventSpamKeyFunc` or `EventAggregatorKeyFunc`

that sounds fair https://grep.app/search?q=EventAggregatorKeyFunc  and https://grep.app/search?q=EventSpamKeyFunc , but I still don't have clear this is really needed, since it seems that is the user who decides the key

**Pull request closed without merging**
