### PR TITLE
Rename PetSet to StatefulSet

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: #35534

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: 

**Special notes for your reviewer**: cc @erictune @foxish @kubernetes/sig-apps @ymqytw 

**Release note**:

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35663)

### CODE REVIEW

**Comment by AlexMioMio** [comment]
StatefulSet is better than PetSet,easy to understand

**Comment by smarterclayton** [comment]
Had one questions for @caesarxuchao regarding the removal of the client, but otherwise this looks ok (we don't have to fix all nits here and I don't want you to rebase this more than once).

**Comment by caesarxuchao** [comment]
We have client-go now, it's not useful to keep old version of released clientset in the main repository, so I'm fine with changing the release_1_4 folder. I'll remove those folder entirely in another PR.

@smarterclayton I didn't see your question on github?

**Comment by smarterclayton** [comment]
It went to the other PR - probably came in as a commit comment.

**Comment by smarterclayton** [comment]
This LGTM but will let others get a minute to chime in.  Setting this P1 to jump the queue.

**Comment by smarterclayton** [comment]
We didn't quite settle on what we called the members of a StatefulSet, I
tried out "member" in the proposal.  Probably can discuss and change later.

On Oct 27, 2016, at 7:16 PM, Eric Tune <notifications@github.com> wrote:

*@erictune* commented on this pull request.
------------------------------

In pkg/client/unversioned/conditions.go
<https://github.com/kubernetes/kubernetes/pull/35663#pullrequestreview-6164056>
:

> @@ -77,11 +77,11 @@ func ReplicaSetHasDesiredReplicas(rsClient extensionsclient.ReplicaSetsGetter, r
 	}
 }

-// PetSetHasDesiredPets returns a conditon that checks the number of
petset replicas
-func PetSetHasDesiredPets(psClient appsclient.PetSetsGetter, petset
*apps.PetSet) wait.ConditionFunc {
+// StatefulSetHasDesiredPets returns a conditon that checks the
number of petset replicas

s/Pets/Pods/? Okay to do in future PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/35663#pullrequestreview-6164056>,
or mute the thread

**Comment by erictune** [comment]
lgtm

**Comment by bprashanth** [comment]
I'm sure Clayton and Eric have this covered, LGTM

**Comment by janetkuo** [comment]
> We didn't quite settle on what we called the members of a StatefulSet, I
tried out "member" in the proposal.  Probably can discuss and change later.

Yes it's in the petset rename checklist #35534. Current plan is to just call them pods

**Comment by bprashanth** [comment]
I guess we can chip away at the internal types the controller uses like pcb (petControlBlock) and petSyncer. @m1093782566 fyi, since you volunteered to help.

**Comment by chrislovecnm** [comment]
@k8s-bot test this

**Comment by chrislovecnm** [comment]
Nice ...

**Comment by chrislovecnm** [comment]
@janetkuo does this close the rename or just finishes out a few bullets?

**Comment by janetkuo** [comment]
@chrislovecnm just the first two items

**Comment by janetkuo** [comment]
This script just got merged before the 2nd test... will rebase and update it 

```
FAILED   hack/make-rules/../../hack/verify-test-owners.sh
```

**Comment by janetkuo** [comment]
@k8s-bot gci gce e2e test this

**Comment by chrislovecnm** [comment]
@k8s-bot gci gke e2e test this

**Comment by chrislovecnm** [comment]
When will this go into a beta release? And now we have to what PRs.

**Pull request merged**
