### PR TITLE
Fix cronjob stub 400

### PR DESCRIPTION
**Pull request by resouer**
Encountered a 400 doc stub

```NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Actually, it DOES: `Adding label:do-not-merge because PR changes docs prohibited to auto merge`  I saw that and merged.  I missed the no-issue because I used a github canned reply.

**Comment by fejta** [comment]
^ @spxtr @dchen1107 FYI (empirical data about the no-issue requirement)

**Comment by thockin** [comment]
I have now added a canned reply for "approved, no issue", so it will be less likely for me to flub again.

**Pull request merged**
