### PR TITLE
Automated cherry pick of #64355: bump(github.com/evanphx/json-patch):

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #64355 on release-1.10.

#64355: bump(github.com/evanphx/json-patch):

### CODE REVIEW

**Comment by MaciekPytel** [comment]
This is a duplicate of #64418

**Comment by MaciekPytel** [comment]
#64418 was closed, let's proceed with this one.

**Comment by MaciekPytel** [comment]
/hold 
Freezing branch for 1.10.4.

**Comment by sttts** [comment]
/approve

for the dep change.

**Pull request merged**
