### PR TITLE
kubeadm: wrap runtime tests in a t.Run

### PR DESCRIPTION
**Pull request by bart0sh**
**What this PR does / why we need it**:

Improved runtime tests by using [T.Run API](https://golang.org/pkg/testing/#T.Run) 

This should improve testing output and make it more visible
which test is doing what.

**Which issue(s) this PR fixes**:

This PR addresses [this review comment](https://github.com/kubernetes/kubernetes/pull/64611#pullrequestreview-137441722) 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by chuckha** [comment]
/lgtm

Thank you for improving kubeadm's tests!

**Comment by bart0sh** [comment]
@timothysc please, approve

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
