### PR TITLE
Handle panic in async event reporting

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@timothysc PTAL

**Comment by krousey** [comment]
This looks fine, but what is panicking?

**Comment by timothysc** [comment]
> This looks fine, but what is panicking?
+1

Also, @lavalamp had suggested we should probably increase the channel queue vs. the go-routine which I had originally done.

**Comment by liggitt** [comment]
Nothing regularly, just saw the guard was missing while I was in the code.

**Comment by ixdy** [comment]
@k8s-bot test this [had to purge queue]

**Pull request merged**
