### PR TITLE
Rename `NodeConfiguration` to `JoinConfiguration` in the kubeadm v1alpha3 Config API

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
In v1alpha3, we have made the design decision that `NodeConfiguration` will be renamed `JoinConfiguration`. This PR implements that change. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: kubernetes/kubeadm#911
Depends on:
 - [x] https://github.com/kubernetes/kubernetes/pull/65776
 - [x] https://github.com/kubernetes/kubernetes/pull/65628
 - [x] https://github.com/kubernetes/kubernetes/pull/65629
 - [x] https://github.com/kubernetes/kubernetes/pull/65631
 - [x] https://github.com/kubernetes/kubernetes/pull/65940
 - [x] https://github.com/kubernetes/kubernetes/pull/65787
 - [ ] https://github.com/kubernetes/kubernetes/pull/65945

**Special notes for your reviewer**:

Please only review the last three commits here.

**Release note**:

```release-note
[action required] The `NodeConfiguration` kind in the kubeadm v1alpha2 API has been renamed `JoinConfiguration` in v1alpha3
```
@kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
LGTM on Fabrizio's rebase of my fork. Thanks a lot!
@timothysc this should be good to LGTM fully now 👍🏻

**Comment by fabriziopandini** [comment]
@luxas @timothysc rebased again to resolve a config in `cmd/kubeadm/app/cmd/config.go` introduced by https://github.com/kubernetes/kubernetes/pull/66074

**Comment by luxas** [comment]
Please update the generated files again

**Review by timothysc — APPROVED** [review]
/lgtm

**Pull request merged**
