### PR TITLE
Add support for konnectivity service to the etcd3 client.

### PR DESCRIPTION
**Pull request by cheftako**
If konnectivity service is enabled, the etcd client will now use it.
This did require moving a few methods to break circular dependencies.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
If konnectivity service is enabled, the etcd client will now use it.
This did require moving a few methods to break circular dependencies.

**Which issue(s) this PR fixes**:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md

**Special notes for your reviewer**:
This is part of an alpha feature and is disabled by default.
It is a follow on to https://github.com/kubernetes/kubernetes/pull/78543

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md
```

### CODE REVIEW

**Review by wenjiaswe — COMMENTED** [review]
@cheftako as you said, most change are making sure the dependencies works, they look good to me, as long as all tests pass. For the etcd client part, lgtm with one question, is there konnectivity test that could verify this works?

**Comment by anfernee** [comment]
nice /lgtm

**Review by hexfusion — APPROVED** [review]
thanks @cheftako

**Pull request merged**
