### PR TITLE
Just use runtime.NumCPU on windows

### PR DESCRIPTION
**Pull request by dims**
docker folks added NumCPU implementation for windows that
supported hot-plugging of CPUs. The implementation used the
GetProcessAffinityMask to be able to check which CPUs are
active as well.
https://github.com/moby/moby/commit/3707a76921b412cb42e6134beaa0bddbb5e08f25

The golang "runtime" package has also bene using GetProcessAffinityMask
since 1.6 beta1:
https://github.com/golang/go/commit/6410e67a1eb38df3cc72cef818ed392bea907251

So we don't seem to need the sysinfo.NumCPU from docker/docker as at this point the goland implementation seems suffice.

(Note that this is PR is an effort to get away from dependencies from
docker/docker)

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Newest implementation in docker/moby:
https://github.com/moby/moby/blob/master/pkg/sysinfo/numcpu_windows.go#L28-L36

Newest implementation in golang:
https://github.com/golang/go/blob/master/src/runtime/os_windows.go#L364-L376

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
A surface level reading of the upstream commits looks like this makes to me. I'd be very happy to see this dependency cleaned up. Would like node/windows folks to weigh in.

**Review by feiskyer — APPROVED** [review]
looks good to me

**Comment by dims** [comment]
@feiskyer can you please `/approve` and `/lgtm`?

**Pull request merged**
