### PR TITLE
Add Json marshal/unmarshal methods for protobuf/jsonpb

### PR DESCRIPTION
**Pull request by tamalsaha**
Why?
We are using protobufs generated from api objects to write a custom grpc server. We also use https://github.com/grpc-ecosystem/grpc-gateway to serve a JSON api. Without these methods, the marshaling fails.

ref:
https://godoc.org/github.com/golang/protobuf/jsonpb#JSONPBMarshaler

### CODE REVIEW

**Comment by tamalsaha** [comment]
cc: @deads2k

**Comment by tamalsaha** [comment]
@dims , tests are passing I think.

**Comment by smarterclayton** [comment]
/hold

I may not get a chance to look at this until after code freeze, which may mean 1.10.  Is that an issue?

**Comment by smarterclayton** [comment]
Are you using the objects in k8s.io/api when you say “protobuf generated from objects”?

**Comment by tamalsaha** [comment]
> Are you using the objects in k8s.io/api when you say “protobuf generated from objects”?

We use the ObjectMeta. That pulls in the the `Time` object.

>  I may not get a chance to look at this until after code freeze, which may mean 1.10. Is that an issue?
:) 1.9 will be better. But I can just use my fork.

**Comment by tamalsaha** [comment]
@smarterclayton, mind taking another look at it ?

**Comment by smarterclayton** [comment]
I'm ok with this, please fix the test failures and I'll review and tag

**Comment by tamalsaha** [comment]
I am not very well versed in bazel. I am getting the following error:
```
W0130 11:58:01.059] 	vendor/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go: import of github.com/golang/protobuf/jsonpb, which is not a direct dependency
``
How do I fix this?

**Pull request closed without merging**
