### PR TITLE
Fix the portal net used in the default ubuntu cluster scripts...

### PR DESCRIPTION
**Pull request by a-robinson**
...to actually be on a private IP range.

This came up in issue #6667.

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by thockin** [comment]
LGTM but I did not audit the rest of the ubuntu scripts to ensure that is unique... did you?

**Comment by a-robinson** [comment]
Ugh, you're completely right, I don't actually know how flannel is allocating pod IPs in these setups, so I don't know whether they'll conflict. I should definitely learn how, but don't have the time today.

In the meantime, this shouldn't be merged.

**Comment by WIZARD-CXY** [comment]
@a-robinson  The ip range that flannel used is configured by using `/opt/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}' by user 
And our team is working on merge the ubuntu single node and multiple nodes into one as this pr 
https://github.com/GoogleCloudPlatform/kubernetes/pull/5498.

**Comment by a-robinson** [comment]
Ah, I wasn't aware of that work, @WIZARD-CXY. Thanks for the pointer! Is there any chance that, while you guys are in there, you or @resouer could swap out the 11.1.1.0/24 portal nets for a subnet in an actual private IP range, like something under 10.0.0.0/8 or 172.16.0.0/12?

**Comment by WIZARD-CXY** [comment]
@a-robinson ok no problem

**Comment by a-robinson** [comment]
Thanks!

**Pull request closed without merging**
