### PR TITLE
fix Kubeadm phase addon error

### PR DESCRIPTION
**Pull request by fabriziopandini**
What this PR does / why we need it:
fix Kubeadm phase addon error

Which issue this PR fixes
[#437](https://github.com/kubernetes/kubeadm/issues/437)

Special notes for your reviewer:
CC @luxas @andrewrynhard

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

Thanks for fixing this!

**Comment by andrewrynhard** [comment]
@fabriziopandini Thanks for the fix!

**Pull request merged**
