### PR TITLE
Stop using deprecated gcloud commands

### LINKED ISSUE #12881: Migrate test infrastructure to new gcloud commands for MIGs
In the per-PR e2e tester, I see a bunch of lines like this:

```
WARNING: This preview command will be removed soon.
WARNING: These managed infrastructure preview commands have been migrated to "gcloud compute intance-groups managed" command group.
WARNING: See https://cloud.google.com/sdk/gcloud/reference/ for more details.
WARNING: Please use instead [gcloud compute instance-groups managed list].
```

which means that our per-PR builder is going to break abruptly in the next few weeks after a gcloud release. 

https://github.com/kubernetes/kubernetes/pull/11692 switched us over to the new API but it appears that there are some places where we are still using the preview commands.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fixes #12881

cc @piosz

### CODE REVIEW

**Comment by roberthbailey** [comment]
There's also a preview command in gke/util.sh.

**Comment by wojtek-t** [comment]
@roberthbailey - please don't look at this PR yet - I'm just experimenting now.

**Comment by wojtek-t** [comment]
@roberthbailey - I will let you know when it will be ready for review.

**Comment by wojtek-t** [comment]
This is now ready for review.

**Comment by wojtek-t** [comment]
@roberthbailey - friendly ping

**Comment by roberthbailey** [comment]
LGTM. (sorry, haven't been paying attention to PRs assigned to me)

**Comment by wojtek-t** [comment]
@roberthbailey - no problem. Thanks!

**Pull request merged**
