### PR TITLE
Migrate test/apiserver to structured logging

### PR DESCRIPTION
**Pull request by thickforest**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by johnSchnake** [comment]
Same comment https://github.com/kubernetes/kubernetes/pull/102429#pullrequestreview-671738214

**Comment by pacoxu** [comment]
unless sig-instrumentation define /test as a target for structured logging with agreement from sig-testing, we should not accept similar PRs.

also kubeadm and kubectl are out of scope for the time being.

/close

**Pull request closed without merging**
