### PR TITLE
Upgrading to heapster v0.18.2.

### PR DESCRIPTION
**Pull request by vishh**
cc @piosz @jszczepkowski 

This is required to fix some bugs with node auto-scaling.

cc @dchen1107

### CODE REVIEW

**Comment by vishh** [comment]
@piosz: Once this is merged, can you cherry-pick this into v1.1 release branch?

**Comment by dchen1107** [comment]
Can you update pr description to the link of release notes for book tracking? Or at least including PRs including this release.

**Comment by dchen1107** [comment]
Thanks for last minute fix. I will leave autoscaling team to merge and cherrypick.

**Comment by piosz** [comment]
Thanks @vishh! I'm closing this PR in favor of #14559 which bump the version and tune the config.

**Pull request closed without merging**
