### PR TITLE
Automated cherry pick of #64427: add external resource group support for azure disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #64427 on release-1.11.

#64427: add external resource group support for azure disk

### CODE REVIEW

**Comment by andyzhangx** [comment]
/assign @jsafrane @rootfs 
This is a combined cherry-pick with https://github.com/kubernetes/kubernetes/pull/64427, https://github.com/kubernetes/kubernetes/pull/65443 & https://github.com/kubernetes/kubernetes/pull/65516

**Comment by andyzhangx** [comment]
@jsafrane I have cherry-picked with https://github.com/kubernetes/kubernetes/pull/65691 now, PTAL

**Comment by nikhita** [comment]
/assign @foxish 
for cherry-pick approval

**Comment by foxish** [comment]
> add external resource group support for azure disk
Is this really a bug fix? It reads like a feature to me.

**Comment by andyzhangx** [comment]
Hi @foxish resource group should not be limited for azure disk plugin, OpenShift on Azure won't work in some scenarios, RedHat are requiring this fix in prior version, thanks.

**Comment by saad-ali** [comment]
> Hi @foxish resource group should not be limited for azure disk plugin, OpenShift on Azure won't work in some scenarios, RedHat are requiring this fix in prior version, thanks.

It does look like a feature being cherry picked back. That said, if Azure folks say that it is critical and promise it does not break backwards compat, I have no objections with accepting the cherry pick, since it is isolated to the Azure volume plugin.

**Pull request merged**
