### PR TITLE
Verify generated stuff in CI

### PR DESCRIPTION
**Pull request by thockin**
trying this out to see if it catches the current issue

### CODE REVIEW

**Comment by vmarmol** [comment]
#11031

**Comment by thockin** [comment]
@ixdy jenkins should not be passing this

**Comment by ixdy** [comment]
Why shouldn't it be passing it? It doesn't run anything in the Travis or Shippable configs.

**Comment by thockin** [comment]
Jenkins, Shippable, etc should all run verify-generated-*, which is failing
at HEAD.

**Comment by ixdy** [comment]
Jenkins only runs the e2e tests and nothing else right now.

**Comment by thockin** [comment]
We should fix that? Not sure

**Comment by nikhiljindal** [comment]
I like the way it is. Jenkins is fast since it doesnt duplicate the checks that shippable is already running.

**Comment by thockin** [comment]
This is ready for review - who knows anything about shippable?  The fact that shippable failed here actually means success because the build *is* broken in this branch.

**Comment by thockin** [comment]
@wojtek-t

**Comment by ixdy** [comment]
This looks fine to me, though I'd actually like to see everything passing. Shippable bails after the first thing that fails, which in this case is `./hack/verify-generated-conversions.sh`, so none of the rest of the tests are running. I'd like to see it all pass before merging, ideally.

**Comment by thockin** [comment]
rebase - now that you saw it fail and the CI breaking error is fixed, it should pass.

**Comment by thockin** [comment]
Given that shippable is taking 2+ hours to run tests, remind me why we don't want Jenkins to do it?

**Comment by thockin** [comment]
This is green now

**Comment by wojtek-t** [comment]
LGTM

**Comment by thockin** [comment]
Nobody wants to take responsibility for OKing this ? :)  rebased and pushed again, and I'll self merge

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (34/30 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:42499)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-7097-robin=eikaas.no@sgmail.github.com>)
	id 1ZEhbV-0021NB-Ey
	for robin@eikaas.no; Mon, 13 Jul 2015 19:33:27 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=UHOGXP+Up48jm8CFXgw7RCA8SBc=; b=s8+IcZHxAbmrqnPD
	iw47WZju8KwmfHdrdNXCzrO6Od9vy8dl0mtu+yF9+tHjWHZ05s595qsqgh+6+5nw
	lJGFm7160t6AOXwFm/3Py6AUtHQCPLx5kZHDAS9b5eFMWG0wNFYL8ptbx0vrJFwZ
	Zo7F7IzIW9ldhs9yvM8bPbzebuI=
Received: by filter0814p1mdw1.sendgrid.net with SMTP id filter0814p1mdw1.2498.55A3F65C19
        2015-07-13 17:33:16.915641742 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd-020 (SG) with ESMTP id 14e887a5a9c.1b33.21d218
	for <robin@eikaas.no>; Mon, 13 Jul 2015 17:33:16 +0000 (UTC)
Date: Mon, 13 Jul 2015 10:33:16 -0700

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
What's the value of having all of these steps broken out separately in the test configs vs. just running one script that runs all the checks and tests? The latter would make it easier for developers to do exactly what shippable does.

**Comment by thockin** [comment]
I made the smallest possible change, though I agree

**Pull request merged**
