### PR TITLE
Accept healthy instances in list of active instances

### LINKED ISSUE #79581: Draining a node with a pod that uses an AWS NLB does not deregister instances or close the nodeports on said node
**What happened**: Using a pod like the nginx-ing-cntlr with an AWS Network Load Balancer (NLB), and then draining the node its running on to force a migration to another node pool, does not reliably deregister the drained nodes from the NLB Target group. This causes the nodeport used by the NLB to remain open, and the drained node ends up continuing to funnel traffic for other pods cause of `externalTrafficPolicy: Cluster` being used. This leads to connection timeouts for clients, and downtime on migrations.

Switching to a Classic ELB, instead of an NLB, with connection draining enabled does work, and the instances that are drained are practically removed immediately from the instances targeted by the ELB, as expected. There seems to be some sort of issue with NLB's as this is not happening, or happening rarely (only saw it once in many tests but couldn't recreate it).

The node + LB [sync](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L643) set seems to be working as I see in the controller-mgr logs that the nodes are updated as I went from 11 nodes to 8, after attempting to drain + migrate a nodepool of 3 nodes with nginx-ing-cntlr all running on them:

```
I0630 22:08:34.548236 7 service_controller.go:639] Detected change in list of current cluster nodes. New node set: map[ip-172-16-153-92.us-east-2.compute.internal:
{}
ip-172-16-107-18.us-east-2.compute.internal:
{}
ip-172-16-131-114.us-east-2.compute.internal:
{}
ip-172-16-175-60.us-east-2.compute.internal:
{}
ip-172-16-100-188.us-east-2.compute.internal:
{}
ip-172-16-110-179.us-east-2.compute.internal:
{}
ip-172-16-173-181.us-east-2.compute.internal:
{}
ip-172-16-183-203.us-east-2.compute.internal:
{}
]

22:08:34
I0630 22:08:34.845543 7 service_controller.go:647] Successfully updated 6 out of 6 load balancers to direct traffic to the updated set of nodes
I0630 22:08:34.845543 7 service_controller.go:647] Successfully updated 6 out of 6 load balancers to direct traffic to the updated set of nodes
```

However, this update does not seem to be translating into deregistering instances from the NLB. And i've waited minutes & hours in case timeouts were playing a hand, but that didn't seem to help.

**What you expected to happen**: On node draining, with `externalTrafficPolicy: Cluster` being used, that the NLB would deregister the instances as expected.

**How to reproduce it (as minimally and precisely as possible)**: Launch a Deployment + NLB service on a node and drain it to force it over to another node pool. Watch the instances in the AWS NLB Target group never get out of "healthy" status or be drained + removed.

**Anything else we need to know?**:

**Environment**: AWS EKS
- Kubernetes version (use `kubectl version`): 1.12 & 1.13
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): AWS Linux 2
- Kernel (e.g. `uname -a`): 4.14.123-111.109.amzn2.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug): core-dns v1.2.6
- Others:

### PR DESCRIPTION
**Pull request by hoelzro**
Fixes GH #79581

Healthy instances have a nil Reason associated with their target health,
so without this, actualIDs ends up as empty (well, without healthy
instance IDs in it, anyway).  As a result, any instances not present
in the instances parameter are perceived to be already out of the target
group, and are thus never deregistered.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR fixes a bug where cordoned nodes are not deregistered from an NLB's target group on AWS.

**Which issue(s) this PR fixes**:

Fixes #79581

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cordoned nodes are now deregistered from AWS target groups.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hoelzro** [comment]
Hello @micahhausler! I know we're coming out of the holiday season so you're probably really busy, but is there any chance I could get a review on this PR? I'd really like for it to make it into the next patch release if possible.  I know it has the XL label, but that's really just the tests - the actual change is pretty small!

**Comment by otterley** [comment]
I have duplicated the problem that this PR claims to address.  When a node is cordoned (unschedulable), the node (instance) should be deregistered from the NLB's Target Group.  But currently it is not, which can cause clients to receive TCP RSTs until the health check fails or until the controller finally notices the node has gone and deregisters the instance.

It's important that we fix this issue to prevent customer traffic from experiencing client errors during scale-in.

**Comment by mbelang** [comment]
@otterley Is this only happening during scale-in events? I'm having issues with NLB with nginx-ingress  where NLB closes connection without the client knowing about it. It causes wierd issues on the client side. I'm using plane default keep-alive timeout for nginx-ingress 75s with NLB and 60s on upstream and my upstream servers have keep-alive of 5s.

See below the NLB resetting connections. I assume this is bad as the targets should control how and when the connection is closed.

lb-reset-count

**Comment by otterley** [comment]
@mbelang I suspect these issues are unrelated.  If you're having issues with NLBs spontaneously closing Keep-Alive connections to clients (without receiving RSTs from the targets while their associated pods are still alive), I believe that's a different matter.

**Comment by mbelang** [comment]
That is what I thought. Thanks for the answer.

**Comment by micahhausler** [comment]
Can you squash the commits before we merge? 

Thanks for writing the tests!

**Comment by hoelzro** [comment]
@micahhausler Squashed and pushed!  I re-ran the tests to be safe - I got some failures, but I see the same failures on 6e38a0f46e8.

**Comment by micahhausler** [comment]
Thanks! I think eventually I'd really like to refactor this to use [`elbv2iface.ELBV2API`](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/elbv2iface/#ELBV2API) so you don't have to stub out all those methods, but that is more work than is probably fair to ask for this PR

**Comment by primeroz** [comment]
Sorry to ask a question in a closed PR but does this logic conflict with https://github.com/kubernetes/kubernetes/pull/90823 ?

**Comment by rittneje** [comment]
@hoelzro I have the same question as @primeroz. What exactly is this bugfix?

**Comment by hoelzro** [comment]
@primeroz @rittneje From my understanding (which is rather limited at the moment - I'm on paternity leave so the cluster in my head is currently underprovisioned :sweat_smile: ), #90823 is more about "make sure that unschedulable nodes can participate in load balancing", and my fix is more "make sure that if the controller wants to take a node out of the load balancer that it actually gets taken out".  1f010cc makes mention of load balancer labels to remove a node from a pool - I believe that without my fix, adding such a label to a node would fail to remove it from the AWS target group.

**Pull request merged**
