### PR TITLE
Revert "Speculative workaround for #74890"

### PR DESCRIPTION
**Pull request by neolit123**
Reverts kubernetes/kubernetes#75305

Umbrella issue: migrate kubernetes to Go 1.12.1
xref: https://github.com/kubernetes/kubernetes/issues/75372

/assign @spiffxp @dims 
cc @justinsb
/priority critical-urgent
/kind failing-test

/hold
please unhold once test-infra and k/k are ready with go 1.12.1

cc @maria @alejandrox1 
after this PR merges we need to watch the tests from this ticket again:
https://github.com/kubernetes/kubernetes/issues/74890

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt @ixdy 

Jeff, Jordan, please `/approve` this ... we need to go back to sync.Once now that one way or another we will be using 1.12.1 golang

**Comment by ixdy** [comment]
/approve
/hold

should we wait for #75413 to merge first?

**Comment by liggitt** [comment]
won't this reintroduce problems with diffResources until https://github.com/kubernetes/kubernetes/pull/75413 merges?

**Comment by dims** [comment]
@liggitt yep, the other one is almost ready

**Comment by justinsb** [comment]
/lgtm

(in case anyone thought I might be upset about seeing this reverted ;-) )

**Pull request merged**
