### PR TITLE
kubectl: move translated data into kubectl

### PR DESCRIPTION
**Pull request by seans3**
* Moved generated translate binary data into kubectl.
* Only kubectl depends on this generated translate binary data.
* Removes a kubectl dependency on Kubernetes core.

**NOTE:**
The following translation artifacts must be copied into the new kubectl repo before we can build `kubectl` from the new repo. These include
* /translations/kubectl/...
* /translations/extract.py
* /hack/update-translations.sh
* /hack/generate-bindata.sh

Helps address:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
lgtm, looks like you'll need to add the new location of the generated.go file to golint ignores

**Comment by soltysh** [comment]
You still have the same problem that Juan mentions about updating golint failures.

**Comment by seans3** [comment]
> You still have the same problem that Juan mentions about updating golint failures.

Actually, directories with generated files like `bindata.go` do not go into the golint_failures file, since they are handled specially by `hack/verify-golint.sh`.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
