### PR TITLE
Move bgrant0607 to emeritus status.

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Per note in https://github.com/kubernetes/kubernetes/issues/93637#issuecomment-668313095 @bgrant0607 has requested to be marked as emeritus.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
@bgrant0607 - Thank you for all your work over the years! Should you find the time again to dive into things, we'll be so happy to move you back.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig contributor-experience
/priority important-soon

/assign @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, @dims. I'm happy to move to emeritus, at least for now, since I can't respond in a timely fashion to review/approval requests.

I wonder if this will let me approve since I won't be in the future approval list. :-)

/lgtm
/approve

**Comment by BenTheElder** [comment]
@bgrant0607 thank you 🙃 

> I wonder if this will let me approve since I won't be in the future approval list. :-)

For the record / for anyone curious: approval is always computed from the OWNERS files in the target branch (master here).

**Pull request merged**
