### PR TITLE
DO NOT MERGE Generate a client for third party resource data

### PR DESCRIPTION
**Pull request by derekwaynecarr**
I think this should let folks work against this client to build controllers using informer framework as meta.Accessor will be happy.

/cc @kubernetes/sig-api-machinery @kubernetes/rh-cluster-infra

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
It would be great if @sjenning could verify this actually meets his needs ;-)

**Comment by derekwaynecarr** [comment]
NM, this is flawed: https://github.com/kubernetes/kubernetes/pull/25587/files#diff-fc41a16809f37286507ea42a77257bd1R62

Closing.

**Comment by derekwaynecarr** [comment]
To make this real, we would need to make the entry point for ThirdPartyResourceDatas be the groupVersionResource that it should invoke so we dont hard code "thirdpartyresourcedatas" as the resource on the server.

I would need to look a little more into how the client gen code to see how much is involved there.

**Comment by caesarxuchao** [comment]
@derekwaynecarr could you ping me when you've done that change to client-gen? Thanks.

**Comment by krousey** [comment]
@derekwaynecarr Assigning back to you, because I don't know what to do with this.

**Comment by derekwaynecarr** [comment]
Closing this PR as I don't anticipate changing client-gen anytime soon.

**Pull request closed without merging**
