### PR TITLE
Expose EmptyDir metrics

### LINKED ISSUE #69507: Exposing ephemeral storage metrics to prometheus
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

Now, we only expose PVC related volumes metrics to protheus, https://github.com/kubernetes/kubernetes/pull/51553
but we need ephemeral storage metrics too, such as EmptyDir usage and capacity info.

/assign 
/sig storage
/cc @jingxu97 @gnufied

### PR DESCRIPTION
**Pull request by NickrenREN**
**What type of PR is this?**
 /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Exposing EmptyDir  metrics to prometheus

Fixes #69507

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Exposing EmptyDir metrics to prometheus
```

### CODE REVIEW

**Comment by anmolsachan** [comment]
@NickrenREN 
I went through the PR. I have following questions:
	- I see here in the PR that Ephimeral storage is considered only as the emptyDir volumes. While according to Kubernetes Docs ( https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage ) it may also include container logs, image layers and container writable layers. Are these already available via some other metrics ?
	- The pr concentrates on the Pod level ephemeral metrics, is it possible to expose those up to container level ? 
	- Is it possible to expose metrics related to ephemeral-storage-requests and ephemeral-storage-limits on container level ?

**Comment by gnufied** [comment]
Same comment as here - https://github.com/kubernetes/kubernetes/issues/69507#issuecomment-447076929 . I am not sure if we want to expose ephemeral volumes metrics via prometheus because they are persisted for far longer and volume themselves will disappear shortly.

**Comment by anmolsachan** [comment]
@julienlim Tagging you have a look at this PR.

**Comment by derekwaynecarr** [comment]
I am trying to think about how this metric would be used.  As a kubelet admin, I administer the rootfs and/or imagefs, and its not obvious to me why I would need metrics at the granularity of an individual empty dir.  Eviction decisions are primarily made at the node level when rootfs is scarce.  Maybe this would help me know if eviction decisions are primarily a result of abuse of empty dir?

**Comment by NickrenREN** [comment]
@derekwaynecarr Emptydir info can not only help analyze eviction decisions。
We have other use cases which need the ephemeral storage usage info. 
We store some ephemeral info in Emptydir and we need to watch  the ephemeral storage usage to help us make decisions on what to do next.
And many other use cases described here: https://github.com/kubernetes/kubernetes/issues/69507#issuecomment-447861033
https://github.com/kubernetes/kubernetes/issues/69507#issuecomment-457258875

**Comment by NickrenREN** [comment]
@anmolsachan  sorry, i missed your comment somehow.

>- I see here in the PR that Ephimeral storage is considered only as the emptyDir volumes. While according to Kubernetes Docs ( https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage ) 

There are some other ephemeral storage volume types, we can add them later

> - The pr concentrates on the Pod level ephemeral metrics, is it possible to expose those up to container level ?
> - Is it possible to expose metrics related to ephemeral-storage-requests and ephemeral-storage-limits on container level ?

Yes, i focus on pod level volume metrics at first. And since we have container metrics in `PodStats`, we certainly can expose metrics on container level,  but i am not sure if we need to.

**Comment by adriananeci** [comment]
Can we reopen/reconsider this PR?

**Pull request closed without merging**
