### PR TITLE
Automated cherry pick of #52679 #53209 #53599

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #52679 #53209 #53599 on release-1.8.

#52679: bazel: set --incompatible_comprehension_variables_do_not_leak=false
#53209: bazel: bazel: set --incompatible_disallow_set_constructor=false to fix breakage
#53599: query --incompatible_comprehension_variables_do_not_leak=false

x-ref #52677

### CODE REVIEW

**Comment by BenTheElder** [comment]
@jpbetz ignore `pull-kubernetes-e2e-kubeadm-gce` for now, it's not required and has issues, [we're considering not displaying it on GitHub](https://github.com/kubernetes/test-infra/issues/4932).

**Comment by jpbetz** [comment]
@ixdy this has conflicts with the base branch, please rebase.

**Pull request merged**
