### PR TITLE
WIP: Removed HPA objects from extensions api group

### LINKED ISSUE #21578: HPA in GA step 3
remove client support for HPA in version extensions/v1beta1

Follow up #18528

### PR DESCRIPTION
**Pull request by piosz**
``` release-note
HorizontalPodAutoscaler is no longer supporter in extensions/v1beta1 version. Use autoscaling/v1 instead.
```

fix #21578

[Analytics]()

### CODE REVIEW

**Comment by piosz** [comment]
@caesarxuchao I removed HPA objects from extensions/v1beta1 and release_1_2, release_1_3 clients don't compile. It's not a surprise since both are using HPA in the removed version. What should I do to make the change possible? How about removing them?

cc @wojtek-t

**Comment by piosz** [comment]
cc @kubernetes/autoscaling

**Comment by caesarxuchao** [comment]
Currently to make the code compile, I think we need to update all the code in the repo that uses release_1_2 or release_1_3 client to use release_1_4.

In the future, we plan to make clients a separate repo. In the main repo, client will be in the vendor/ directory, and all components use the vendored client. @lavalamp what do you think?

**Comment by lavalamp** [comment]
Will this change actually break a 1.3 client? At the very least, a 1.3 client needs to continue working against 1.4.

**Comment by caesarxuchao** [comment]
This [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/release_1_3/typed/extensions/v1beta1/horizontalpodautoscaler.go) will be broken, because this PR removes the v1beta.HorizontalPodAutoscaler.

**Comment by piosz** [comment]
As discussed offline with @lavalamp @caesarxuchao the plan is to:
- remove support for HPA in extensions/v1beta1 from client for 1.4 #21578
- remove support for HPA in extensions/v1beta1 from server for 1.5 #29778

Closing the PR in the meantime.

**Pull request closed without merging**
