### PR TITLE
Enable profiling by default re: #6623

### PR DESCRIPTION
**Pull request by timothysc**
per conversation with @wojtek-t & @vmarmol

### CODE REVIEW

**Comment by timothysc** [comment]
#6623 needs to be merged 1st or else the scheduler will crash.

**Comment by vmarmol** [comment]
LGTM

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
But we need to merge #6623 before it to avoid scheduler crashes.

**Comment by vmarmol** [comment]
#6623 is in. Thanks @wojtek-t @timothysc! Merging

**Pull request merged**
