### PR TITLE
Moves e2e service util functions into service_util.go and cleans up

### PR DESCRIPTION
**Pull request by MrHohn**
Basically moves codes into a central place for service util functions.

Some other codes are touched mostly only due to this migration. Also put a bunch of network reachability utils functions into network_utils.go. They seem somehow redundant, may consider combine they later.

@bowei @freehan

### CODE REVIEW

**Comment by bowei** [comment]
Looks ok to me -- this is just moving a bunch of code, right?

**Comment by freehan** [comment]
LGTM

**Comment by freehan** [comment]
need to rebase

**Comment by MrHohn** [comment]
@bowei Yes, basically moving codes into service_util.go and capitalizing public functions.

Rebased, thanks for reviewing! Wait for the tests to pass.

**Pull request merged**
