### PR TITLE
Run Rescheduler e2e on GCE only

### LINKED ISSUE #31277: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/2067/

Failed: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:66
Expected error:
    <*errors.errorString | 0xc820808600>: {
        s: "Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels \"k8s-app=kube-dns,version=v19\" to be running",
    }
    Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels "k8s-app=kube-dns,version=v19" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:65
```

### PR DESCRIPTION
**Pull request by piosz**
fix #31277

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31325)

### CODE REVIEW

**Comment by piosz** [comment]
@mikedanese @mwielgus @wojtek-t

**Comment by mikedanese** [comment]
Thanks, can you say why this test doesn't run well on GKE?

**Comment by mwielgus** [comment]
LGTM

**Comment by piosz** [comment]
@mikedanese Rescheduler is not enabled on GCE

**Pull request merged**
