### PR TITLE
Automated cherry pick of #118876: kubectl explain should work for both cluster and namespace

### PR DESCRIPTION
**Pull request by atiratree**
Cherry pick of #118876 on release-1.27.

#118876: kubectl explain should work for both cluster and namespace

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.27 regression in `kubectl explain`
```

### CODE REVIEW

**Comment by cpanato** [comment]
@atiratree @ardaguclu this CP is only needed for release-1.27 branch?

**Comment by atiratree** [comment]
@cpanato I do not think it is necessary because openapi/v3 was behind a env variable feature gate in 1.26 and not available by default; see https://github.com/kubernetes/kubernetes/pull/116390. But I can make the cherry-pick if there is a demand for it.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ardaguclu** [comment]
transient, unrelated failure;
/test pull-kubernetes-dependencies

**Comment by ardaguclu** [comment]
As far as I can see, this will fix https://github.com/kubernetes/kubernetes/pull/119086 dependency failure.

**Pull request merged**
