### PR TITLE
Fix Borg pub link in README

### PR DESCRIPTION
**Pull request by xirehat**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
The Borg link in README.md is redirected to the wrong page(https://ai.google/research/pubs/pub43438/). Now current link shows us: 

Page not found
Sorry, this page could not be found.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
IMO this change does not need a changelog entry @xirehat

**Comment by xirehat** [comment]
You mean I should remove answer of this question `Does this PR introduce a user-facing change?` @sftim

**Comment by sftim** [comment]
> You mean I should remove answer of this question `Does this PR introduce a user-facing change?` 

The correct answer is: **NONE**

**Comment by xirehat** [comment]
> > You mean I should remove answer of this question `Does this PR introduce a user-facing change?`
> 
> The correct answer is: **NONE**
Updated, Thanks for the advice. @sftim

**Comment by xirehat** [comment]
@derekwaynecarr Could you please look into this PR?

**Comment by xirehat** [comment]
@dims could you please look into this PR?

**Comment by dims** [comment]
@xirehat please remove the merge commit in this PR. it should have only one commit with only your change.

**Comment by dims** [comment]
now it has 3 commits! :)

please open a fresh PR

**Comment by xirehat** [comment]
@dims sorry, it's my bad, I fixed it. please check it

**Pull request merged**
