### PR TITLE
Temporary hack for missing cadvisor image tag

### PR DESCRIPTION
**Pull request by dims**
Related to https://github.com/kubernetes/kubernetes/issues/123643

Picking the latest SHA from the `gcr.io/cadvisor/cadvisor` repo:
https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor

This SHA corresponds to `v0.999-bobbypage` tag:
https://explore.ggcr.dev/?repo=gcr.io/cadvisor/cadvisor

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by bobbypage** [comment]
/hold

The image is back, sorry about that, release issues on my side for next version.

**Comment by dims** [comment]
thanks @bobbypage !

**Pull request closed without merging**
