### PR TITLE
Support for the use of OIDC authorization codes in kubeconfig.

### PR DESCRIPTION
**Pull request by kfox1111**
This PR adds support for not having to manually fetch the id and
refresh tokens but instead use an authorization code to fetch the
tokens.

It can be used like the following:

kubectl config set-credentials "minikube" \
  --auth-provider=oidc \
  --auth-provider-arg=client-id=kubernetes \
  --auth-provider-arg=client-secret=xxxxx  \
  --auth-provider-arg=idp-issuer-url=https://<yourprovider> \
  --auth-provider-arg=authorization-code=<authcodefromprovider>

On first kubectl request to the apiserver, it will replace the
authorization-code in the config file with a valid id token, and
if authorized, a refresh token.

This significantly cuts down on the effort an end user needs to
do in order to setup OIDC. It also enhances security by letting
the user not have to handle the tokens themselves.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
oidc authorization-code support was added to allow kubectl to directly consume an oidc authorization code. This greatly simplifies the setup of oidc.
```

### CODE REVIEW

**Comment by ericchiang** [comment]
/assign

What provider are you planning to use this with?

> This significantly cuts down on the effort an end user needs to
do in order to setup OIDC.

This feels like such a weird use of the authorization code. The OAuth2 client that's performing the login flow (which isn't kubectl) already has to validate the "state" parameter of the authorization response[1]. At that point, why don't they do the code exchange? What's the benefit of leaving half of the authorization response handling to a webapp and giving the other half to kubectl?

> It also enhances security by letting
the user not have to handle the tokens themselves.

I don't follow.

[1] https://tools.ietf.org/html/rfc6749#section-4.1.2

**Comment by kfox1111** [comment]
I guess thats been where i've been confused with kubectl. It kind of is the client. It uses the client-id, client-secret, and refresh tokens as a full client would. but currently expects a second, external client to deal with the auth code and getting the initial id/refresh tokens. As you can see from the patch, it is so similar to the refresh flow, it is basically just a copy/paste from the token refresh code with a couple of tweaks to handle the auth code instead.

I've been testing this out with dex, but should handle any oidc server that supports public clients. Google authentication should also work with this.

The idea that I'm trying to implement is this:
1. user logs into the kubernetes dashboard. it is also protected by oidc (I have a prototype). user clicks on a link to get an access code for the cli. it redirects to something like:
https://oidc.example.com:5556/auth?approval_prompt=force&client_id=kubernetes&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=openid+email+profile+offline_access+groups

2. Once the user authenticates with their local browser, it should spit out a page like this:
https://developers.google.com/accounts/images/installedresult.png
User can retrieve an access code without installing anything.

3. With the cli flags listed above, kubectl can then immediately make use of the code pasted by the user.

No extra client needs to be installed on the system to facilitate this flow with this PR.

I think this makes it much simpler to use for our users. Plus should be safer to use in a multi user cli environment. (we have some) where spawning a web server on the clients localhost may not be as secure as doing it on an android phone. This would allow the users web browser and cli to be on separate hosts.

**Comment by ericchiang** [comment]
> user logs into the kubernetes dashboard.

What does this mean? The kubernetes dashboard doesn't support OAuth2.

> No extra client needs to be installed on the system to facilitate this flow with this PR.

You still need something to facilitate the initial redirect and print the commands a user needs to enter to configure kubectl, right? I would have expected that to do the code exchange and handle proper things like state values.

While I agree that this could be easier, I think there are better steps we could take forward, like building better webapps to do the initial redirect and print commands to the user. I don't think having kubectl handle half of the authorization response processing like this is a good practice. It encourages users to skip the use of the "state" URL parameter.

**Comment by kfox1111** [comment]
Actually, the dashboard kind of does.... :)
I'm almost ready to propose this chart to upstream. Documentation attached here
https://github.com/kfox1111/charts/blob/oidc/stable/kubernetes-dashboard/MiniKubeOIDC.md

I have a patch set against dex to finish smoothing off the rough edges there too. I'm trying to get permission to contribute that. Will be posting it asap.

The final thing to do after that is to add a logout link and kubeconf link into the dashboard, and then I think it will work very smoothly end to end. Hoping to get that done really soon now.

Probably should pull in sig ui too while we're at it:
/sig ui

**Pull request closed without merging**
