### PR TITLE
bump zeitgeist to release v0.5.3

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- bump zeitgeist to release v0.5.3

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
/assign @liggitt @dims @saschagrunert @xmudrii 
cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
@cpanato I don't think we need a release note for that change.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
