### PR TITLE
Revert "Update cobra/pflag.  Also update generated kubectl documentation...

### PR DESCRIPTION
**Pull request by piosz**
Reverts GoogleCloudPlatform/kubernetes#5464 because it broke jenkins build.

cc @brendanburns @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @brendanburns, @filbranden 
This change broke jenkins - the problem was that we're calling:
cluster/kubectl.sh --match-server-version version
(see https://github.com/GoogleCloudPlatform/kubernetes/blob/e6517e48ebc38a262f65b3a52698ffb512a90726/hack/e2e.go#L124)
instead of:
cluster/kubectl.sh version --match-server-version

Thus, we're reverting this change to fix jenkins tests.

**Comment by wojtek-t** [comment]
Merging now to fix e2e tests.

**Comment by piosz** [comment]
It helped. Jenkins is happy now. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/3533/

**Comment by wojtek-t** [comment]
@brendanburns - I think that PR should be reverted in the future (i.e. your original PR should be committed). However, we need to fix e2e tests first and since it wasn't obvious how to fix it in the best way, I decided to temporarily revert your change.

**Comment by brendandburns** [comment]
yep, thanks for doing the revert.  I will try to figure out what went wrong...

**Pull request merged**
