### PR TITLE
Try to verify bazel build works for kubemark image

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold

### CODE REVIEW

**Comment by krzyzacy** [comment]
/unassign @gmarek @shyamjvs 
experimenting with PR

**Comment by krzyzacy** [comment]
:-( how about -
/unassign @wojtek-t @gmarek 
/assign

**Comment by krzyzacy** [comment]
@shyamjvs hummm, new issue here is that there's no bazel workspace info in the k8s tarball.. I'll need to think of some other way to work around this..

**Comment by BenTheElder** [comment]
don't close this, we should be able to fix it (discussion ongoing in test-infra).

**Comment by BenTheElder** [comment]
```
W1212 03:10:36.705] containerregistry.client.v2_2.docker_http_.BadStateException: Bad status during token exchange: 401
W1212 03:10:36.705] {"errors":[{"code":"DENIED","message":"Unable to access the repository, please check that you have permission to access it."}]}
```
😕

**Comment by krzyzacy** [comment]
(ok, reviving this PR for experimenting the kubemark presubmit job - cc @shyamjvs )

**Pull request closed without merging**
