### PR TITLE
Deprecation: Replace `strings.Title` with `Caser`

### PR DESCRIPTION
**Pull request by chendave**
`strings.Title` is deprecated as of golang 1.18[1], and suggest to use `golang.org/x/text/cases` instead.

[1] https://github.com/golang/go/issues/48367

Signed-off-by: Dave Chen <dave.chen@arm.com>

/kind deprecation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The use of `strings.Title` is deprecated by golang, switch to use golang.org/x/text/cases instead 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
@liggitt @dims  is this something k8s should catch up with?

**Comment by chendave** [comment]
I don't know if the `cases.Title` impact anything for Kubernetes at the moment or in the future. Cause this change will vendor some packages, I will close it if you guys think the old usage is fine for us.

**Comment by dims** [comment]
let's defer to Jordan here @chendave

**Comment by liggitt** [comment]
I don't think we should take dependencies outside the stdlib for this... the stdlib function won't be removed, I'm more confident in its stability than external libraries, and adding thousands of LOC for this is a negative.

The deprecation says "Deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.", but unicode punctuation doesn't matter for our use cases.

**Comment by dims** [comment]
@chendave thanks for the effort, but agree with Jordan.

/close

**Pull request closed without merging**
