### PR TITLE
federation: Adding dnsprovider flags to federation-controller-manager

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
LGTM!  Thanks @nikhiljindal

**Comment by nikhiljindal** [comment]
Updated the bring up script to set DNS_PROVIDER as per KUBERNETES_PROVIDER if its empty.

**Comment by quinton-hoole** [comment]
@nikhiljindal, boilderplate comment needs fixing...

```
Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/federation/cmd/federation-controller-manager/app/plugins.go
FAILED   ./hack/../hack/verify-boilerplate.sh	1s
```

**Comment by nikhiljindal** [comment]
Rebased and fixed the boilerplate.
All tests passing now!

**Comment by quinton-hoole** [comment]
Re-applied LGTM.

**Comment by piosz** [comment]
@quinton-hoole why this is P1?

**Comment by quinton-hoole** [comment]
@piosz I elevated it it to P1 as it's blocking today's release branch for 1.3.  My apologies, I should have added a comment when I did that.

**Comment by piosz** [comment]
@quinton-hoole there is >30 PRs in submit queue with milestone 1.3 which basically means that all of them are blockers for today's release.

**Pull request merged**
