### PR TITLE
remove seccomp profile path on security context

### LINKED ISSUE #117045: Remove SeccompProfilePath
Look for "// TODO: Deprecated, remove after we switch to Seccomp field". Fix it. See https://github.com/kubernetes/kubernetes/pull/115898 as example.

/cc @saschagrunert 

/help
/good-first-issue
/sig node

add @saschagrunert as a reviewer when sending a PR.

(issue is a follow up from https://github.com/kubernetes/kubernetes/pull/117020/files#r1154025906)

### PR DESCRIPTION
**Pull request by charles-chenzz**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove the deprecated seccomp profile path
#### Which issue(s) this PR fixes:

Fixes #117045 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by bart0sh** [comment]
@charles-chenzz Can you look at https://github.com/kubernetes/kubernetes/pull/117084 ? It seems it goes further than this PR and removes also unused code.

**Comment by charles-chenzz** [comment]
> @charles-chenzz Can you look at #117084 ? It seems it goes further than this PR and removes also unused code.

@bart0sh  I would prefer stay at this moment, cus the issues only ask for remove the code ``todo`` and didn't request more, so I am not very sure that we need to remove the other unused code.

**Comment by charles-chenzz** [comment]
/assign @SergeyKanzhelev 
ready for approve now

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
