### PR TITLE
Productionize the cockroachdb example a little more

### PR DESCRIPTION
**Pull request by a-robinson**
Includes:
- A service for clients to use
- Readiness/liveness probes
- An extended graceful termination period
- Automatic prometheus monitoring (when prometheus is configured to watch for annotations on services, as in [CoreOS's recent blog post](https://coreos.com/blog/prometheus-and-kubernetes-up-and-running.html), for example)

I'm leaving the management of certs to future work, but if anyone that sees this needs help with them in the meantime, don't hesitate to reach out.

Successor to #28446

@bprashanth - if you're still interested in / open to an e2e test (as mentioned in https://github.com/cockroachdb/cockroach/issues/5967#issuecomment-230188807), let me know and I'll put one together. If so, I assume you'd want it as part of the `petset` test group rather than the `examples` tests?

cc @tschottdorf 

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31125)

### CODE REVIEW

**Comment by a-robinson** [comment]
@k8s-bot I signed it!

**Comment by bprashanth** [comment]
@a-robinson any suggestions on how we guage the production readiness of this example? It would be great if we could run something like jepsen on the kube+cockroach app stack (I'm guessing just any old 3 tier nginx -> app -> postgres db but with cockroach should work). We're currently at the point where we don't know if what we have is sufficient to run production ready dbs yet. Figured it would be easiest to start by productionizing some more modern examples like cockroach/etcd. 

Maybe this will require a seperate cockraoch-kube repo where people can bang at it, report issues etc, and we upstream feature requests (kind of like https://github.com/CyCoreSystems/etcd-petset)? or can we go straight to charts like: https://github.com/kubernetes/charts/pull/37?

Re certs: what creates the secrets in a normal deployment?  can you describe the issue a bit more.

**Comment by a-robinson** [comment]
> @a-robinson any suggestions on how we guage the production readiness of this example? It would be great if we could run something like jepsen on the kube+cockroach app stack (I'm guessing just any old 3 tier nginx -> app -> postgres db but with cockroach should work). We're currently at the point where we don't know if what we have is sufficient to run production ready dbs yet. Figured it would be easiest to start by productionizing some more modern examples like cockroach/etcd.

Either our [acceptance tests](https://github.com/cockroachdb/cockroach/tree/develop/acceptance) or our [jepsen tests](https://github.com/cockroachdb/jepsen/tree/master/cockroachdb) could work for that purpose. I'm not sure how much work would be required to get the jepsen tests running in k8s though. @knz may have a better idea of how custom of a setup is needed to get them running?
 
> Maybe this will require a seperate cockraoch-kube repo where people can bang at it, report issues etc, and we upstream feature requests (kind of like https://github.com/CyCoreSystems/etcd-petset)? or can we go straight to charts like: kubernetes/charts#37?

A separate repo or a chart would be fine by me. Although the [chart contributors guide mentions that charts shouldn't use alpha features](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements), so we'd have to fudge the rules a bit to do that.

> Re certs: what creates the secrets in a normal deployment? can you describe the issue a bit more.

The operator typically would create them on their local machine and then distribute them when dropping the binaries onto each instance. There's a [quick walkthrough in our docs](https://www.cockroachlabs.com/docs/secure-a-cluster.html#step-2--create-security-certificates). As you mentioned on #28446, there are certainly more dynamic ways that it could be done at startup if needed.

**Comment by a-robinson** [comment]
On an unrelated note, I won't be able to fix the release-note label, since apparently my labeling privileges went away recently :(

**Comment by knz** [comment]
Re setting up @jepsen tests. The test require
- the cockroach binary and a couple of utilty programs copied to the VM/container
- a SSH daemon enabled, and a user account that can log into it remotely with passwordless key auth,
- passwordless sudo for that account. sudo is used to change the system clock (via `ntpdate` and a custom program) and invoke `tcptump`, which also need to be available.

**Comment by a-robinson** [comment]
Thanks, that all sounds pretty manageable, with the SSH part perhaps being a little awkward.

**Comment by bprashanth** [comment]
@k8s-bot test this github issue #30714

**Comment by bprashanth** [comment]
LGTM, I think we should get together a working group of people interested in getting {db of choice} on kube and have them run {acceptance tests} at least once as a starting point. I'm going to propose something along these lines at sig-apps or a community meeting. Let me know if you have anyone on your side interested.

**Comment by a-robinson** [comment]
Sorry for the small modification, I just ensured all resources had the `app=cockroachdb` label and added a brief blurb about how to clean up the resources when you're done.

Also, looks like the 1.4 code freeze is in pretty full effect, so should we assume that this won't be merged until mid-September?

**Comment by a-robinson** [comment]
> LGTM, I think we should get together a working group of people interested in getting {db of choice} on kube and have them run {acceptance tests} at least once as a starting point. I'm going to propose something along these lines at sig-apps or a community meeting. Let me know if you have anyone on your side interested.

Yeah, I'd be happy to be part of that group from our side. I'll also check into running acceptance tests on top of Kubernetes sometime in the next couple weeks.

**Comment by viglesiasce** [comment]
Hey @a-robinson @bprashanth!

We now have an [incubator folder](https://github.com/kubernetes/charts/tree/master/incubator) in the charts repository for any charts that require features that are currently in alpha. 

We would love to have this added to incubator and then promoted to stable (along with the others) when PetSets are in Beta.

**Comment by bprashanth** [comment]
SGTM
A recurring question: what is fair grounds for the charts repo? the minikube.sh script in this example? dockerfiles for custom init containers? or is the answer "treat your charts subdir like a private repo"?

**Comment by viglesiasce** [comment]
@bprashanth 

For the most part whatever you need to make the chart useful. You can setup a .helmignore file to exclude files, like Dockerfiles. A solid README (already included here) is required and the chart should install with sane defaults. Once https://github.com/kubernetes/minikube/pull/541 is merged in you can use a dynamically provisioned PVC for the minkube testing and shouldn't require that script anymore. 

An example of the PVC pattern can be found in the MySQL chart:
https://github.com/kubernetes/charts/pull/46

**Comment by a-robinson** [comment]
Thanks @viglesiasce, I'll take a look at getting cockroachdb set up there soon.

@bprashanth is there anything you need from me to re-LGTM this?

**Comment by viglesiasce** [comment]
Awesome @a-robinson! Looking forward to it.

**Comment by bprashanth** [comment]
Oh, sorry for the delay I assumed you were moving it but getting this in as is SGTM

**Pull request merged**
