### PR TITLE
Fix federation-apiserver authentication e2e tests

### LINKED ISSUE #35251: Federation e2e tests are timing out
It looks like the addition of some new e2e tests (by @nikhiljindal ?) made the test run take a bit longer, and not fit into it's timeout threshold.  

@shashidharatd FYI. 

root      9001  0.0  0.0 270936  6256 ?        Sl   08:48   0:00                          \_ /workspace/kubernetes/platforms/linux/amd64/ginkgo /workspace/kubernetes/platforms/linux/amd64/e2e.test -- --kubeconfig=/workspace/.kube/config --ginkgo.flakeAttempts=1 --host=https://104.198.234.41 --provider=gce --gce-project=k8s-jkns-e2e-gce-federation --gce-zone=us-central1-f --gke-cluster=jenkins-e2e --kube-master=jenkins-us-central1-f-master --cluster-tag= --repo-root=/workspace/kubernetes/cluster/../cluster/gce/../../cluster/gce/../../cluster/.. --node-instance-group=jenkins-us-central1-f-minion-group --prefix=jenkins-us-central1-f --network=jenkins-e2e --master-os-distro=gci --node-os-distro=debian --num-nodes=3 --minStartupPods=8 --report-dir=/workspace/_artifacts --ginkgo.focus=\[Feature:Federation\]
root      9009  0.0  0.1 538720 61168 ?        Sl   08:48   0:05                              \_ /workspace/kubernetes/platforms/linux/amd64/e2e.test --test.timeout=24h --ginkgo.seed=1476978533 --ginkgo.slowSpecThreshold=5.00000 --kubeconfig=/workspace/.kube/config --ginkgo.flakeAttempts=1 --host=https://104.198.234.41 --provider=gce --gce-project=k8s-jkns-e2e-gce-federation --gce-zone=us-central1-f --gke-cluster=jenkins-e2e --kube-master=jenkins-us-central1-f-master --cluster-tag= --repo-root=/workspace/kubernetes/cluster/../cluster/gce/../../cluster/gce/../../cluster/.. --node-instance-group=jenkins-us-central1-f-minion-group --prefix=jenkins-us-central1-f --network=jenkins-e2e --master-os-distro=gci --node-os-distro=debian --num-nodes=3 --minStartupPods=8 --report-dir=/workspace/_artifacts --ginkgo.focus=\[Feature:Federation\]
++ docker stop kubernetes-e2e-gce-federation-5358
kubernetes-e2e-gce-federation-5358
+ rc=124
+ [[ 124 -eq 124 ]]
+ echo 'Build timed out'
Build timed out
+ echo 'Exiting with code: 124'
Exiting with code: 124
+ exit 124
Build step 'Execute shell' marked build as failure

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**: Fixes couple of federation e2e tests

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes # partly fixes #35251

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35687)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Thanks @shashidharatd 
cc @kubernetes/sig-cluster-federation 

Can you please add some more context, why do we need to disable anonymous auth?
The same yaml file is used by our federation-up.sh script to bring up federation control plane on clusters. Do we need anonymous auth disabled there as well? Or we need to disable it only in tests?

**Comment by nikhiljindal** [comment]
@k8s-bot federation gce e2e test this

**Comment by mml** [comment]
@k8s-bot ok to test

**Comment by shashidharatd** [comment]
@nikhiljindal , if anonymous-auth plugin is enabled, API requests need not have user credentials for authentication check. By disabling anonymous-auth plugin, federation apiserver will honor request with authentic user credentials only and i think that's the way forward.
There won't be any impact by disabling anonymous-auth, as I can see that already there are other auth plugin's used in federation api-server, basic-auth, token-auth and client certs. Any one of them succeeds is good enough to pass the authentication check. federation-up.sh, basically uses kubeconfig and there are user credentials generated for federation api-server.

**Comment by quinton-hoole** [comment]
Nice surgical fix!  Thanks @shashidharatd .  LGTM.

**Comment by nikhiljindal** [comment]
Federation e2e failure is unrelated to this PR.
Being fixed in https://github.com/kubernetes/test-infra/pull/949

**Pull request merged**
