### PR TITLE
Use single struct in internal type to reduce difference with external type

### PR DESCRIPTION
**Pull request by php-coder**
**What this PR does / why we need it**:
This PR reduces the differences between internal and external types by removing leftovers after revert of one of the changes.

**Special notes for your reviewer**:
We had `IDRange` in both types prior 9440a68744 commit (https://github.com/kubernetes/kubernetes/pull/44714) that splitted it into `UserIDRange`/`GroupIDRange`. Later, in c91a12d205 commit (https://github.com/kubernetes/kubernetes/pull/47824) we had to revert these changes because they broke backward compatibility but `UserIDRange`/`GroupIDRange` structs were left in the internal type.

### CODE REVIEW

**Comment by php-coder** [comment]
/sig auth
/kind cleanup
/release-note-none

PTAL @tallclair @liggitt 
CC @simo5

**Comment by liggitt** [comment]
/lgtm
thanks for the cleanup

**Comment by php-coder** [comment]
Re-pushed to fix error from gofmt (one empty line has been removed).

**Pull request merged**
