### PR TITLE
Use gsed on the mac.

### LINKED ISSUE #37474: cluster/gce/upgrade.sh fails to upgrade nodes when run from a mac
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5 beta 2

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): CVM
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh

**What happened**: Step 6 of https://docs.google.com/document/d/19Q4AzWLD5jd2FNaPyKy2xdTN4JIGUUpvwDwg0tcBkyc/edit# fails

**What you expected to happen**: Node upgrade to succeed.

**How to reproduce it** (as minimally and precisely as possible): Follow the manual upgrade steps outlined in the linked document.

**Anything else do we need to know**: The error is because the metadata is too large for the new node instance template. 

```
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - Value for field 'resource.properties.metadata.items[2].value' is too large: maximum size 32768 character(s); actual size 33595.
```

### PR DESCRIPTION
**Pull request by roberthbailey**
**What this PR does / why we need it**: Fixes node upgrades when run from a mac

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #37474

**Special notes for your reviewer**:

```release-note
Use gsed on the Mac
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37562)

### CODE REVIEW

**Comment by roberthbailey** [comment]
I ran through https://docs.google.com/document/d/19Q4AzWLD5jd2FNaPyKy2xdTN4JIGUUpvwDwg0tcBkyc/edit# and was able to successfully upgrade my nodes when using `upgrade.sh` from this branch.

**Comment by roberthbailey** [comment]
@saad-ali @davidopp

**Comment by davidopp** [comment]
Can you add a comment explaining that you're doing this because sed doesn't work on Mac?

**Comment by roberthbailey** [comment]
In the shell code?

**Comment by davidopp** [comment]
yes

**Comment by roberthbailey** [comment]
comment and extra check added to match https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd.sh#L177

**Comment by roberthbailey** [comment]
@jessfraz this looks broken in the 1.4 release branch as well (https://github.com/kubernetes/kubernetes/blob/release-1.4/cluster/gce/util.sh#L1713) so I'll create a cherry pick for both 1.5 and 1.4 once it merges.

**Comment by davidopp** [comment]
LGTM

**Comment by roberthbailey** [comment]
@zmerlynn - can you look at the kops error?

**Comment by zmerlynn** [comment]
@k8s-bot aws e2e test this

@roberthbailey: It's either the same low-grade flake I've been chasing, or it's a residual issue off this morning. I'll try to watch this space.

**Comment by davidopp** [comment]
Marking P0 because this is blocking manual upgrade testing on Mac.

**Pull request merged**
