### PR TITLE
add tests to daemon controller

### PR DESCRIPTION
**Pull request by surajssd**
add unit tests to `pkg/controller/daemon` package
to increase coverage of package.

Tries to take a stab at https://github.com/kubernetes/kubernetes/issues/50598

```release-notes
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
cc @k82cn

**Comment by k82cn** [comment]
My overall comments here: https://github.com/kubernetes/kubernetes/issues/50598#issuecomment-342344492

**Pull request closed without merging**
