### PR TITLE
Adding dims as reviewer for test/

### PR DESCRIPTION
**Pull request by dims**
Will try to spend more time with test/ reviews this cycle.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm
👍

**Comment by oomichi** [comment]
I am looking forward to seeing much reviews from dims :-)

/lgtm

**Comment by BenTheElder** [comment]
/lgtm
/approve
Yes please!

**Comment by dims** [comment]
/milestone v1.19

this is just a change to owners file, so trying to get this in. there's quite a bit of things in ci that are hurting, will help me nudge things along.

**Comment by liggitt** [comment]
> there's quite a bit of things in ci that are hurting

speaking of which... sigh...

/retest

**Pull request merged**
