### PR TITLE
move daemonset to generalized label selector

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by davidopp** [comment]
Mike: I'm not going to have time to review this before I go out of town. If you need it reviewed sooner, please reassign.

**Comment by davidopp** [comment]
ref/ #341

**Comment by mikedanese** [comment]
@erictune fixed.

**Comment by erictune** [comment]
lgtm

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot e2e test this please

**Pull request merged**
