### PR TITLE
Decouple etcd node.expiration logic from DeleitonTimestamp

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: https://github.com/kubernetes/kubernetes/issues/23902

### CODE REVIEW

**Comment by wojtek-t** [comment]
It actually fixes #23902

**Comment by wojtek-t** [comment]
LGTM

**Comment by hongchaodeng** [comment]
@wojtek-t @gmarek 
Tests are all green.

**Comment by hongchaodeng** [comment]
It seems like there is a race in pod autoscaler test related to client.
Irrelevant here. Gonna rebase and push it again.

**Comment by hongchaodeng** [comment]
Unit test failed in pod autoscaler test related to client.
See https://github.com/kubernetes/kubernetes/issues/23361

Rebased it and tried running it again

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: https://github.com/kubernetes/kubernetes/issues/24298

**Pull request merged**
