### PR TITLE
NodeMetrics, PodMetrics: Add doc for metav1.ObjectMeta

### LINKED ISSUE #104707: no explanation for metadata filed of NodeMetrics/PodMetrics
#### What happened:
no explanation for metadata filed of NodeMetrics/PodMetrics,  code:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go#L33
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go#L65
should be like
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/autoscaling/v1/types.go#L86-L88
$ kubectl explain NodeMetrics
KIND:     NodeMetrics
VERSION:  metrics.k8s.io/v1beta1

DESCRIPTION:
     NodeMetrics sets resource usage metrics of a node.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>

   timestamp	<string> -required-
     The following fields define time interval from which metrics were collected
     from the interval [Timestamp-Window, Timestamp].

   usage	<map[string]string> -required-
     The memory usage is the memory working set.

   window	<string> -required-
and
$ kubectl explain PodMetrics
KIND:     PodMetrics
VERSION:  metrics.k8s.io/v1beta1

DESCRIPTION:
     PodMetrics sets resource usage metrics of a pod.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   containers	<[]Object> -required-
     Metrics for all containers are collected within the same time window.

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>

   timestamp	<string> -required-
     The following fields define time interval from which metrics were collected
     from the interval [Timestamp-Window, Timestamp].

   window	<string> -required-

#### What you expected to happen:
able to see the explanation for metadata filed of NodeMetrics/PodMetrics
#### Environment:
Kubernetes Version: v1.22.0-rc.0+1199c36

### PR DESCRIPTION
**Pull request by arajkumar**
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Adds documentation for `metav1.ObjectMeta` field in NodeMetrics & PodMetrics types.

#### Which issue(s) this PR fixes:

Fixes #104707

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by serathius** [comment]
LGTM, leaving it to API reviewer.
/assign @erictune

**Comment by liggitt** [comment]
/approve

doc-change only, making it consistent with other types

**Pull request merged**
