### PR TITLE
fix typos in kubectl pkg

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aramase** [comment]
ping @pwittrock @derekwaynecarr @ghodss

**Comment by aramase** [comment]
ping @derekwaynecarr @ghodss

**Comment by aramase** [comment]
@spiffxp I just rebased the PR. Can you approve it?

**Comment by spiffxp** [comment]
/retest
/lgtm
@aramase unfortunately I don't have /approve rights for these files

**Comment by smarterclayton** [comment]
/approve no-issue

I hate "no-issue"

**Pull request merged**
