### PR TITLE
cronjob: fix flaky unit test TestController2_updateCronJob

### LINKED ISSUE #99505: CronJob unit tests are flaky
#### Which jobs are flaking:
pull-kubernetes-unit 

#### Which test(s) are flaking:
k8s.io/kubernetes/pkg/controller/cronjob: TestController2_updateCronJob/spec.schedule_changed 
k8s.io/kubernetes/pkg/controller/cronjob: TestController2_updateCronJob 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98582/pull-kubernetes-unit/1365354170114117632

/sig apps
/assign @soltysh

### PR DESCRIPTION
**Pull request by alaypatel07**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:

Test TestController2_updateCronJob checks if the controller pushes the cronjob 
on the queue at the correct time upon a change in spec.schedule. This fixes the
calculation of time duration 

#### Which issue(s) this PR fixes:

Fixes #99505

#### Special notes for your reviewer:

/assign @soltysh

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP] - https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/19-Graduate-CronJob-to-Stable/README.md
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
flake https://github.com/kubernetes/kubernetes/issues/98784

**Comment by alaypatel07** [comment]
just making sure another run on unit test passes

/test pull-kubernetes-unit

**Comment by BenTheElder** [comment]
(it passed, running again)
/test pull-kubernetes-unit
without patch: https://github.com/kubernetes/kubernetes/pull/92316#issuecomment-787502952

**Comment by pacoxu** [comment]
👍
/lgtm
nice fix

**Comment by pacoxu** [comment]
/lgtm cancel
I test it on my machine
1m35s: 1101 runs so far, 2 failures (0.18%)
```
--- FAIL: TestController2_updateCronJob (1.69s)
    --- FAIL: TestController2_updateCronJob/spec.schedule_changed (1.69s)
        cronjob_controllerv2_test.go:421: Expected "1.1s" got "2.2s"
--- FAIL: TestController2_updateCronJob (1.49s)
    --- FAIL: TestController2_updateCronJob/spec.template_changed (0.38s)
        cronjob_controllerv2_test.go:421: Expected "0s" got "600ms"
```

go test -race -c ./pkg/controller/cronjob
stress -p 60 ./cronjob.test

I run stress on the UT.

**Comment by pacoxu** [comment]
When the flake happen, there are messages like

> E0301 13:05:15.008917   49566 cronjob_controller.go:270] Cannot determine if snazzycats/mycronjob needs to be started: too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew

https://github.com/kubernetes/kubernetes/blob/c198632a12971efa55f9d659bcc9f59b79651edc/pkg/controller/cronjob/utils.go#L128-L148

**Comment by alaypatel07** [comment]
> /lgtm cancel
I test it on my machine with your branch.
1m35s: 1101 runs so far, 2 failures (0.18%)

Thanks for trying this locally, I was fearful this might happen but wasn't able to pin point.

I think the reason why this happens is the go-routine where we wait for the `queue.Get()` can be waiting to get some CPU time in a stress test, while other go-routines are running.

Since this test checks for the time cron should be next scheduled and verifies that by checking the contents of the queue, it feels more like an e2e test than a unit test

I think we should remove this and add a corresponding e2e test with the right SLA.

Curious to hear other thoughts.

**Review by soltysh — CHANGES_REQUESTED** [review]
I'd try to replace the current queue in tests with a mock, such that you'll be able to read the duration in the `AddAfter` call, instead of relying on time passing by.

**Review by soltysh — APPROVED** [review]
Run this locally ~6k times w/o any failures.
/lgtm
/approve
/triage accepted
/priority important-longterm

**Comment by BenTheElder** [comment]
Thanks all!

**Pull request merged**
