### PR TITLE
Simplify zap logger initialization

### PR DESCRIPTION
**Pull request by serathius**
/kind cleanup

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
NONE
```

/wg structured-logging
/cc @kubernetes/wg-structured-logging-reviews

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
Maybe need to gofmt?

**Comment by yuzhiquan** [comment]
/lgtm
Well done!

**Pull request merged**
