### PR TITLE
test/ : fix non-ascii characters

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
/kind cleanup
 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/87679

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by liggitt** [comment]
can we fix the remaining issues in a single PR? I see 35 instances of `‘` in 9 .go files (excluding generated files)

**Comment by tanjunchen** [comment]
> can we fix the remaining issues in a single PR? I see 35 instances of `‘` in 9 .go files (excluding generated files)

sure i will update all .go file in test/.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
