### PR TITLE
Prune inactive owners from cmd/kube-controller-manager/OWNERS.

### PR DESCRIPTION
**Pull request by mrbobbytables**
**What type of PR is this?**

/kind cleanup

**Which issue(s) this PR fixes**:

This is part of a larger cleanup of inactive owners.

OWNERS removed had no activity from January 1st, 2018 to September 1st, 2019. 

For more information on this clean up, see the below links:
- Tracking Issue: https://github.com/kubernetes/kubernetes/issues/76269
- [Kubernetes-dev mailing list announcement](https://groups.google.com/d/msg/kubernetes-dev/4160VsBL7OI/BsBRZSqpCQAJ)

**Special notes for your reviewer**:

Assigning all approvers for review

/assign deads2k lavalamp mikedanese sttts

**Does this PR introduce a user-facing change?**: 

```release-note
NONE
```

/sig contributor-experience
/priority important-soon

### CODE REVIEW

**Comment by lavalamp** [comment]
/lgtm
/approve

/hold

for comments; feel free to unhold after sufficient time.

I think it would be good to @ mention all those removed in this PR?

**Comment by mrbobbytables** [comment]
> I think it would be good to @ mention all those removed in this PR?

They were @ mentioned in the the original tracking thread (although it's been edited to just point to the updated list). Will @ mention below:

249043822 - is not currently an org member / not assignable

for notification ack:
@dalanlan @ddysher @fgrzadkowski @ghodss @girishkalele @goltermann @jdef @jszczepkowski @markturansky @mfanjie

**Pull request merged**
