### PR TITLE
sample-controller: remove README and LICENSE

### PR DESCRIPTION
**Pull request by nikhita**
The README and LICENSE are authoritative in the `k8s.io/sample-controller` repo.

The README in `k8s.io/sample-controller` is updated in https://github.com/kubernetes/sample-controller/pull/1.

Ref https://github.com/kubernetes/kubernetes/pull/52753#issuecomment-335921582.

**Release note**:

```release-note
NONE
```

/assign @sttts @munnerz

### CODE REVIEW

**Comment by sttts** [comment]
Hope I wasn't too late.

**Comment by nikhita** [comment]
maybe a `/lgtm cancel` would be good too.

**Comment by sttts** [comment]
Can we create a PR that moves all those files back into the repo (with the exception of client-go which is manually mantained and has its own release tags)?

**Comment by nikhita** [comment]
> Can we create a PR that moves all those files back into the repo (with the exception of client-go which is manually mantained and has its own release tags)?

Created https://github.com/kubernetes/kubernetes/issues/54398 and https://github.com/kubernetes/kubernetes/pull/54399. Closing.

**Pull request closed without merging**
