### PR TITLE
parameterizing the swift object store w/ env vars

### LINKED ISSUE #47966: OpenStack: Make Swift Object Store Parameterizable
@kubernetes/sig-OpenStack-misc

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:

Currently swift object store has a hard-coded name: `kubernetes`. E.g.,

```shell
swift post kubernetes --read-acl '.r:*,.rlistings'
```

**What you expected to happen**:

Make swift object store parameterizable. E.g.,

```shell
swift post ${SWIFT_OBJECT_STORE} --read-acl '.r:*,.rlistings'
```

**How to reproduce it (as minimally and precisely as possible)**:

```shell
cd kubernetes # Or whichever path you have extracted the release to
KUBERNETES_PROVIDER=openstack-heat ./cluster/kube-up.sh
```

This defaults to the hard-coded `kubernetes` swift object store.

**Anything else we need to know?**:

Here is the patch file to address this issue:

```
From 26453645f35e01083dd4d63afe514e3dfb363145 Mon Sep 17 00:00:00 2001
From: Julien Chastang <julien.c.chastang@gmail.com>
Date: Wed, 21 Jun 2017 15:23:26 -0600
Subject: [PATCH] parameterizing the swift object store w/ env vars

---
 cluster/openstack-heat/config-default.sh | 3 +++
 cluster/openstack-heat/util.sh           | 8 ++++----
 2 files changed, 7 insertions(+), 4 deletions(-)

diff --git a/cluster/openstack-heat/config-default.sh b/cluster/openstack-heat/config-default.sh
index 66702a3..08f4fcd 100644
--- a/cluster/openstack-heat/config-default.sh
+++ b/cluster/openstack-heat/config-default.sh
@@ -43,6 +43,9 @@ CLUSTER_IP_RANGE=${CLUSTER_IP_RANGE:-10.244.0.0/16}
 
 SWIFT_SERVER_URL=${SWIFT_SERVER_URL:-}
 
+# Swift object store
+SWIFT_OBJECT_STORE=${SWIFT_OBJECT_STORE:-kubernetes}
+
 # Flag indicates if new image must be created. If 'false' then image with IMAGE_ID will be used.
 # If 'true' then new image will be created from file config-image.sh
 CREATE_IMAGE=${CREATE_IMAGE:-true} # use "true" for devstack
diff --git a/cluster/openstack-heat/util.sh b/cluster/openstack-heat/util.sh
index 66726db..c81b16c 100644
--- a/cluster/openstack-heat/util.sh
+++ b/cluster/openstack-heat/util.sh
@@ -108,7 +108,7 @@ function create-stack() {
 #   ROOT
 #   KUBERNETES_RELEASE_TAR
 function upload-resources() {
-  swift post kubernetes --read-acl '.r:*,.rlistings'
+  swift post ${SWIFT_OBJECT_STORE} --read-acl '.r:*,.rlistings'
 
   locations=(
     "${ROOT}/../../_output/release-tars/${KUBERNETES_RELEASE_TAR}"
@@ -119,11 +119,11 @@ function upload-resources() {
   RELEASE_TAR_PATH=$(dirname ${RELEASE_TAR_LOCATION})
 
   echo "[INFO] Uploading ${KUBERNETES_RELEASE_TAR}"
-  swift upload kubernetes ${RELEASE_TAR_PATH}/${KUBERNETES_RELEASE_TAR} \
+  swift upload ${SWIFT_OBJECT_STORE} ${RELEASE_TAR_PATH}/${KUBERNETES_RELEASE_TAR} \
     --object-name kubernetes-server.tar.gz
 
   echo "[INFO] Uploading kubernetes-salt.tar.gz"
-  swift upload kubernetes ${RELEASE_TAR_PATH}/kubernetes-salt.tar.gz \
+  swift upload ${SWIFT_OBJECT_STORE} ${RELEASE_TAR_PATH}/kubernetes-salt.tar.gz \
     --object-name kubernetes-salt.tar.gz
 }
 
@@ -196,7 +196,7 @@ function run-heat-script() {
     fi
     SWIFT_SERVER_URL=$(openstack catalog show object-store --format value | egrep -o "$rgx" | cut -d" " -f2 | head -n 1)
   fi
-  local swift_repo_url="${SWIFT_SERVER_URL}/kubernetes"
+  local swift_repo_url="${SWIFT_SERVER_URL}/${SWIFT_OBJECT_STORE}"
 
   if [ $CREATE_IMAGE = true ]; then
     echo "[INFO] Retrieve new image ID"
-- 
2.10.2

```

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: OpenStack
- OS (e.g. from /etc/os-release): `CentOS Linux 7 (Core)`
- Kernel (e.g. `uname -a`): `Linux af62f8f82399 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by julienchastang**
closes #47966

### CODE REVIEW

**Comment by hogepodge** [comment]
Thanks @julienchastang. I closed my PR.

@kubernetes/sig-openstack-bugs

**Comment by julienchastang** [comment]
I am sorry everyone, but I cannot sign a CLA without legal review from my organization, and that will just hold things up. So if someone would not mind doing this on my behalf, that would much appreciated. I understand I may lose authorship, but _c'est la vie_.

**Comment by hogepodge** [comment]
@julienchastang I'll reopen my pull request. Thanks for your work, and I'm sorry you got tripped up the the CLA.

**Comment by julienchastang** [comment]
@hogepodge can you do the rebase? Thanks.

**Comment by lpabon** [comment]
Do we need this PR anymore now that we merged #48281 ?

**Comment by dims** [comment]
hmm `/close` does not work on PR(s). @julienchastang can you please close the PR?

**Pull request closed without merging**
