### PR TITLE
Remove Godeps

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This is the part that was missed when godeps was removed before 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
We publish a [synthetic Godeps.json file](https://github.com/kubernetes/api/blob/master/Godeps/Godeps.json) for staging repos for downstream consumers who may be using glide. Although maybe we can remove this right now since go 1.16 is in module-aware mode by default? cc @dims @liggitt

/hold
If we decide to remove this, I want to ensure that we clean up the corresponding godeps bits from the publishing-bot too.

**Comment by nikhita** [comment]
From https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/917-go-modules/README.md#publish-staging-component-modules-to-individual-repositories:

> Generate synthetic Godeps.json files containing the SHA or git tag of module dependencies, for consumption by downstream consumers using dependency management tools like glide. Continue publishing these at least until our minimum supported version of go defaults to enabling module support (currently targeted for go 1.13, which is approximately Kubernetes 1.16-1.17 timeframe).

**Comment by wzshiming** [comment]
I got it, thanks

**Comment by dims** [comment]
@nikhita +1 to clean up Godeps and update that KEP as well.

**Comment by liggitt** [comment]
I'm in favor of dropping these at this point. cc @sttts @deads2k for visibility.

**Comment by nikhita** [comment]
- PR to update the KEP - https://github.com/kubernetes/enhancements/pull/2774
- PR to remove support for publishing synthetic `Godeps.json` files in publishing-bot - https://github.com/kubernetes/publishing-bot/pull/261.

The second PR is a breaking change. If we decide not to introduce a breaking change (https://github.com/kubernetes/publishing-bot/pull/261#issuecomment-852924144), we could just use `skip-godeps: true` in the rules file here and unblock k/k.

**Comment by deads2k** [comment]
> I'm in favor of dropping these at this point. cc @sttts @deads2k for visibility.

I agree.  It's time, even if it causes some downstream/self pain.

**Comment by liggitt** [comment]
/lgtm
/approve

@nikhita feel free to unhold when it makes sense for the publishing bot

**Comment by dims** [comment]
@nikhita please remove hold?

**Comment by dims** [comment]
/hold cancel

( chatter on slack - https://kubernetes.slack.com/archives/CHGFYJVAN/p1623163166090300 )

**Pull request merged**
