### PR TITLE
Guard both kill and wait with APISERVER_PID.

### PR DESCRIPTION
**Pull request by mml**
@lavalamp followup missed from last review.

### CODE REVIEW

**Comment by mml** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
LGTM, thanks

**Comment by mml** [comment]
@k8s-bot test this please

**Comment by lavalamp** [comment]
@eparis any idea why the merge bot said the same thing four times?

**Comment by eparis** [comment]
@lavalamp because jenkins was misbehaving yesterday and not taking instructions like a good little robot.

**Comment by mml** [comment]
image

**Pull request merged**
