### PR TITLE
Adds HTTPS logic to agnhost netexec

### LINKED ISSUE #90211: agnhost/netexec test image supports HTTPS
**What would you like to be added**:

The `agnhost` image used in E2E tests is used for testing a wide variety of OS-agnostic features. One of these is `netexec`, which runs an HTTP server with various endpoints that can be used to validate things like request/response.

It would be useful to allow for `agnhost`'s `netexec` functionality to also support HTTPS so all of that logic can be tested for TLS-based traffic.

Currently, `netexec` can be run like:
```bash
/agnhost netexec --http-port 8080
```

I'm proposing something along the lines of:
```bash
/agnhost netexec --http-port 8443 --tls-cert-file "/cert.pem" --tls-private-key-file "/key.pem"
```

The default certificate/private key being basically identical to what [agnhost/porter](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#porter) provides.

**Why is this needed**:

One use case is #86139 where the intent is to add HTTPS functionality to lifecycle hooks (postStart/preStop). There is currently no easy way to test this logic because the container which receives the HTTPS request (in this case, `agnhost/netexec`) does not support HTTPS traffic.

### PR DESCRIPTION
**Pull request by jasimmons**
The agnhost image used for testing has a `netexec` path which supports
two new flags, `--tls-cert-file` and `--tls-private-key-file`. If the
former is provided, the HTTP server will be upgraded to HTTPS, using the
certificate (and private key) provided.

By default, there are keys already mounted into the container at
`/localhost.crt` and `/localhost.key`, which contain PEM-encoded TLS
certs with IP SANs for `127.0.0.1` and `[::1]`.

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Adds the ability to test `netexec` logic with TLS-encrypted requests/responses.

**Which issue(s) this PR fixes**:

Fixes #90211 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
Looks good, great addition. I'm actually wondering if we can use this change in a few other places that requires https, so we can reduce the number of used images even further. I'll have to look into that.

/lgtm

**Comment by jasimmons** [comment]
Thanks @claudiubelu ! Can you help me understand what's next? It looks like I might need to update the `VERSION` / `agnhost.go`'s version -- should I do that in this PR?

**Comment by claudiubelu** [comment]
> 
> 
> Thanks @claudiubelu ! Can you help me understand what's next? It looks like I might need to update the `VERSION` / `agnhost.go`'s version -- should I do that in this PR?

Yep, please do, I forgot about that. :)

Also, could you also update the agnhost README file to include the HTTPS info at the netexec section? It would be a good idea to keep it updated.

**Comment by jasimmons** [comment]
@claudiubelu updated! That's all that's documented in the README so if there's anything else that still needs to be done, let me know!

**Comment by claudiubelu** [comment]
/lgtm

Thanks!

**Comment by jasimmons** [comment]
@claudiubelu It looks like this PR still needs `approved` -- is this something you can grant, or do you know who I can try to reach out to in order to get it?

**Comment by claudiubelu** [comment]
Let's try.

/approve

**Pull request merged**
