### PR TITLE
[WIP] move CloudProvider to KubeletConfiguration

### LINKED ISSUE #620: Propagate cfg.CloudProvider to nodes as well using Dynamic Kubelet Config
If `cfg.CloudProvider` is specified, the same value should be set in `cfg.KubeletConfiguration.BaseConfig.CloudProvider` in the defaulting code, so that the kubelets can get the same config automatically.

ref: #28 

cc @kris-nova (will make code in kubicorn easier I guess) @xiangpengzhao @mtaufen @dims 

Note that this is a temporary workaround though, we want to move everything out of tree eventually...

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubeadm/issues/620

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-pr-reviews @mtaufen

**Review by luxas — COMMENTED** [review]
I didn't realize that this wasn't already in the external type... Haven't made up my mind on what to do with this then yet,  but I guess this is reasonable as a stop-gap :thinking: 
cc @jhorwit2 @wlan0 @thockin @jagosan @cheftako

**Comment by dims** [comment]
@luxas here's the other part i haven't touched yet which is the configuration file for the cloud settings ... `CloudConfigFile` in KubeletFlags is a path to a file. 

One idea is we should create a `CloudConfig` which is a string in `KubeletConfiguration` and load it up from `CloudConfigFile`. So we could dynamically propagate the contents of the file to various nodes too. Open to other options as well.

**Comment by mtaufen** [comment]
Please don't embed serialized structures in KubeletConfiguration fields.

After several conversations with @liggitt last quarter, we decided to change dynamic config a little bit so that the keys in the ConfigMap get unpacked as files in the same dir, and relative paths in the KubeletConfiguration start in that dir (this is not yet implemented, but will be soon). 

So if we put `CloudConfigFile` in KubeletConfiguration, you could just provide the actual file in the ConfigMap used for dynamic config, and a relative path in the `KubeletConfiguration.CloudConfigFile` field could reference this file.

I also have another question; why can't `CloudProvider` be determined from `CloudConfigFile`, rather than being a separate field?

**Comment by mtaufen** [comment]
If you intend to use dynamic config for the cloud config file, It should also be the case that everything in the file can be homogeneous across a pool of nodes (e.g. pools of nodes should be able to share the same config source).

**Comment by luxas** [comment]
> After several conversations with @liggitt last quarter, we decided to change dynamic config a little bit so that the keys in the ConfigMap get unpacked as files in the same dir, and relative paths in the KubeletConfiguration start in that dir (this is not yet implemented, but will be soon).

This is nice :+1: 

> I also have another question; why can't CloudProvider be determined from CloudConfigFile, rather than being a separate field?

Usage of the cloud config file is optional for the cloud provider. Many clouds don't even use it. It might or might not make sense to share that file between nodes.
I'm just thinking this might make sense as a migration path to out-of-tree cloud providers eventually as well -- to keep this in the KubeletConfig struct. Others may disagree.

**Comment by dims** [comment]
/close

will revive later

**Pull request closed without merging**
