### PR TITLE
fix rbd volume ConstructVolumeSpec

### PR DESCRIPTION
**Pull request by wenjun93**
**What this PR does / why we need it**:
1. rbd plugin.ConstructVolumeSpec() construct volume spec with fake value, cause kubelet volume manager will create two volumesInUse in node Status.
2. change plugin.GetVolumeName(), create volumeName using rbd pool instead of monitors, as monitors make the volumeName too long. Also, this is to fit plugin.ConstructVolumeSpec() since makeGlobalPDName only uses rbd pool and image.

```
before fix:
volumesAttached:
  - devicePath: ""
    name: kubernetes.io/rbd/[xxxxxxx:6789 xxxxxxxxx:6789]:volume-9a106847-4def-4d1e-9603-4c7099b22a31
  volumesInUse:
  - 'kubernetes.io/rbd/[]:'
  - kubernetes.io/rbd/[xxxxxxx:6789 xxxxxxxxx:6789]:volume-9a106847-4def-4d1e-9603-4c7099b22a31

after fix:
volumesAttached:
  - devicePath: ""
    name: kubernetes.io/rbd/volumes:volume-9a106847-4def-4d1e-9603-4c7099b22a31
  volumesInUse:
  - kubernetes.io/rbd/volumes:volume-9a106847-4def-4d1e-9603-4c7099b22a31

### CODE REVIEW

**Comment by wenjun93** [comment]
@rootfs @jingxu97 Could you please review this PR in yours convenience, thanks

**Comment by wenjun93** [comment]
see also #56924

**Comment by rootfs** [comment]
This construct loses rbd secret. 
@sbezverk is also working on this but from another prospective.

**Comment by sbezverk** [comment]
@rootfs @wejun93 right original construct will lose bunch of data, I built new construct for rbd block volume, but since I am @ kubevon I did not have a chace to test it. Same construct with minor addition of fstype can be use for normal mountable rbd volume construct

**Comment by wenjun93** [comment]
@rootfs @sbezverk thanks! do we also need secret and fstype when construct volumeSpec?
 ConstructVolumeSpec is used to reconstructVolume from pod dir in reconciler. I mean, do we need the whole volumeSource information when reconstructVolume right?
@sbezverk I see your PR, it's for raw block device right, with the spec information from apiserver, is it also necessary here? BTW, have a nice journey at kubecon.

**Comment by rootfs** [comment]
after discussion, this is the way to go
@sbezverk

**Pull request merged**
