### PR TITLE
eliminate kubectl dependency on k8s.io/kubernetes/pkg/util

### PR DESCRIPTION
**Pull request by mengqiy**
Ref: https://github.com/kubernetes/kubernetes/issues/48209

/assign @apelisse @monopole 

cc: @pwittrock 
```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
Nice!

/lgtm

**Comment by mengqiy** [comment]
Someone helps to remove the `do-not-merge` label?

**Comment by apelisse** [comment]
Done!

**Pull request merged**
