### PR TITLE
Changed value receiver to reference receiver

### LINKED ISSUE #105155: A bug that mutates a not-used copy of a struct
Report a bug that mutates a not-used copy of a struct.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L49-L50

Here "PatchMeta" is struct which will be copied by value. The mutation on the copy receiver "pm" doesn't do anything to the original struct in the caller. As a consequence, this mutation has no meaningful effect. 

```
type PatchMeta struct {
	patchStrategies []string
	patchMergeKey   string
}

func (pm PatchMeta) SetPatchStrategies(ps []string) {
	pm.patchStrategies = ps
}
```

The fix is to use pointer receiver.
```
func (pm *PatchMeta) SetPatchStrategies(ps []string) {
	pm.patchStrategies = ps
}
```

A similar issue:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L41-L42

Found by #deepgo.

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What this PR does / why we need it:
bug
#### Which issue(s) this PR fixes:

Fixes #105155 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by gjkim42 — COMMENTED** [review]
https://tour.golang.org/methods/8

> In general, all methods on a given type should have either value or pointer receivers, but not a mixture of both.

Maybe we can change all receivers of PatchMeta to use pointer receivers.

**Comment by NikhilSharmaWe** [comment]
Guidance needed on how to proceed in the PR, how to be able to achieve to goal(changing value receiver to reference receiver) and also make all the test pass. What can be the reason for the error.

**Comment by apelisse** [comment]
One test is flaking, the other one is a static check that is supposed to fail but doesn't anymore (yes, you did fix that static check failure).

Stepping back a little, what bug does this fix? How can this be meaningful? Is this function ever called? How does the caller mis-behave?

**Comment by NikhilSharmaWe** [comment]
@apelisse I don't know much about when the functions is called but As mentioned in the issue here "PatchMeta" is struct which will be copied by value. The mutation on the copy receiver "pm" doesn't do anything to the original struct in the caller. As a consequence, this mutation has no meaningful effect.

**Comment by apelisse** [comment]
Right, but you see my point. If the code does nothing, then ... either 1. it's not needed, or 2. it's not even used, or 3. it causes a bug somewhere that we haven't realized. Which of these options is it?

Because:
- For 1 and 2, we can probably delete the function (and for 1, change the calling site)
- For 3, it shows that we have a lack of test coverage somewhere, and I'd like the test to be added.

Fixing a piece of code that doesn't work without knowing what the code does is not good enough here.

**Comment by NikhilSharmaWe** [comment]
So, should I delete the function then.

**Comment by NikhilSharmaWe** [comment]
And what do you mean by ->  for 1, change the calling site.

**Comment by apelisse** [comment]
> And what do you mean by -> for 1, change the calling site.

I don't know yet if the function is used. If it's used by someone, it probably doesn't need to.

**Pull request closed without merging**
