### PR TITLE
[WIP][NOT FOR REVIEW] test depstat prow job

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>

#### What this PR does / why we need it:
Test the recently added prow job which runs [depstat](https://github.com/kubernetes-sigs/depstat)

#### Which issue(s) this PR fixes:

Testing fix for #98698

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
@dims can you please drop an `/ok-to-test`?

**Comment by RinkiyaKeDad** [comment]
@dims it's [failing ](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102011/check-dependency-stats/1393236297912422400#1:build-log.txt%3A33) because:
```
/bin/bash: line 5: cd: /go/src/k8s.io/kubernetes: No such file or directory
```

Is there a way to navigate the file system of this container without merging another PR in test-infra? We would need to do some `pwd`s to get an idea of where we are so that we can change the `cd` accordingly.

**Comment by dims** [comment]
@RinkiyaKeDad dang, we forgot the path alias `path_alias: k8s.io/kubernetes` 

See example in https://github.com/kubernetes/test-infra/blob/36dd89144e5c02b40746f4199d7bf0b6d7c454db/config/jobs/kubernetes-sigs/kind/kind-presubmits.yaml#L6

**Comment by RinkiyaKeDad** [comment]
@dims it's now [failing](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102011/check-dependency-stats/1393575058647027712#1:build-log.txt%3A33) because:

```
/bin/bash: line 5: depstat: command not found
```

If depstat didn't get installed then shouldn't it fail earlier during the `go install` itself?

**Comment by dims** [comment]
we'll need a `export PATH=$PATH:$GOPATH/bin`

**Comment by RinkiyaKeDad** [comment]
I guess I will have to create a new PR to see the latest test.

**Pull request closed without merging**
