### PR TITLE
feature: support symlink forbidden for hostpath

### LINKED ISSUE #99499: psp.allowedHostPaths could not reject symlink
#### What would you like to be added:
Add a admithandler in kubelet to reject symlink vol. if pods want to use a hostpath, there is no need to use symlink, becase pods could use its symlink target path.

#### Why is this needed:
psp.allowedHostPaths using prefix could not reject symlink, which would make all system path such as /dev, /root exposed to pods using symlink.

### PR DESCRIPTION
**Pull request by nicktming**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
fix security problem

#### Which issue(s) this PR fixes:

Fixes #99499

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adisky** [comment]
@nicktming This implements a feature that required discussion with sig-node, Please go through KEP process https://github.com/kubernetes/enhancements/#is-my-thing-an-enhancement
/hold

**Comment by BenTheElder** [comment]
wasn't PSP just deprecated? https://github.com/kubernetes/kubernetes/pull/97171

**Comment by nicktming** [comment]
> @nicktming This implements a feature that required discussion with sig-node, Please go through KEP process https://github.com/kubernetes/enhancements/#is-my-thing-an-enhancement
> /hold

ping @enhancements-reviewers

**Comment by nicktming** [comment]
> wasn't PSP just deprecated? #97171

@BenTheElder i could not the find the upcoming solution page after psp is deprecated, could you provider it for me?

**Comment by BenTheElder** [comment]
I'm not an active member of that SIG, I've seen prototypes and some discussion but I'm not sure what the plan is yet.

> ping @enhancements-reviewers

That's not how KEPs work, see https://github.com/kubernetes/enhancements/blob/master/keps/README.md

**Comment by liggitt** [comment]
Thanks for the interest, I mentioned some of the compatibility issues with this approach in https://github.com/kubernetes/kubernetes/issues/99499#issuecomment-791988021

I would expect this to funnel through sig-storage as a feature request if you'd like to present the request there and see if there is support for a proposal.

/sig storage

**Comment by nicktming** [comment]
@liggitt i agree, so should i go through KEP process at the next step ?

**Comment by liggitt** [comment]
> @liggitt i agree, so should i go through KEP process at the next step ?

I'd recommend getting feedback from sig-storage (either in discussion in a sig-storage meeting or from sig-storage leads) on whether a feature like this would be supported by the sig. 

My perspective is that hostPath volumes should not be used with untrusted pods, and that scenarios to try to let pods use them while still locking them down would be better served by avoiding hostPath volumes entirely.

**Pull request closed without merging**
