### PR TITLE
[e2e] Move gpu_util.go to e2e/framework/gpu

### PR DESCRIPTION
**Pull request by jiatongw**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

- Move `gpu_util.go` to `framework/gpu`.  
- Fix references of some methods to use the right package

Reference issue #76206 (parent issue #75601 )

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jiatongw** [comment]
/area test
/area test-framework
/sig testing

cc @andrewsykim

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
