### PR TITLE
Compute priorities in parallel

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #24246

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32575)

### CODE REVIEW

**Comment by gmarek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[plugin/pkg/scheduler/generic_scheduler.go, line 259 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-KSaKamFLZFSJosSTkSr:-KSaKamFLZFSJosSTkSs:b-bh54wl) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f65e06dad49af38232c2c17659ae6f28bfe5d7/plugin/pkg/scheduler/generic_scheduler.go#L259)):*
> ```Go
> 
> 	meta := priorities.PriorityMetadata(pod, nodes)
> 	results := make([]schedulerapi.HostPriorityList, 0, len(priorityConfigs))
> ```

Won't `make([]schedulerapi.HostPriorityList, len(priorityConfigs))` and removing following `for` work?

---

*[plugin/pkg/scheduler/generic_scheduler.go, line 314 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-KSaNlN1r8qPiLEumme8:-KSaNlN1r8qPiLEumme9:b-4xsvf9) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f65e06dad49af38232c2c17659ae6f28bfe5d7/plugin/pkg/scheduler/generic_scheduler.go#L314)):*
> ```Go
> 	// Summarize all scores.
> 	result := make(schedulerapi.HostPriorityList, 0, len(nodes))
> 	for i := range nodes {
> ```

You can parallelize this as well.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575)*

**Comment by gmarek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575)*

**Comment by gmarek** [comment]
Only minor nits. Generally LGTM.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-:-KSaO2V4hgVFrZOjeA6V:b-ehjhdj)*

**Comment by wojtek-t** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[plugin/pkg/scheduler/generic_scheduler.go, line 259 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-KSaKamFLZFSJosSTkSr:-KSaTdtgEY6UcV5NQMFX:b-90bamr) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f65e06dad49af38232c2c17659ae6f28bfe5d7/plugin/pkg/scheduler/generic_scheduler.go#L259)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Won't `make([]schedulerapi.HostPriorityList, len(priorityConfigs))` and removing following `for` work?
</details>
From the correctness point of view, it will be the same. From the performance point of view, we avoid allocating HostPriorityList multiple times unnecessarily.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575)*

**Comment by wojtek-t** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[plugin/pkg/scheduler/generic_scheduler.go, line 314 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-KSaNlN1r8qPiLEumme8:-KSaU4uBFgiM6hcWa-8D:b-7yd1q4) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f65e06dad49af38232c2c17659ae6f28bfe5d7/plugin/pkg/scheduler/generic_scheduler.go#L314)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> You can parallelize this as well.
</details>
Added a TODO.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575)*

**Comment by wojtek-t** [comment]
@gmarek - PTAL

**Comment by gmarek** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[plugin/pkg/scheduler/generic_scheduler.go, line 259 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-KSaKamFLZFSJosSTkSr:-KSajGECtSDCKLrpijIP:bf3e1q6) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f65e06dad49af38232c2c17659ae6f28bfe5d7/plugin/pkg/scheduler/generic_scheduler.go#L259)):*
> make([]schedulerapi.HostPriorityList, len(priorityConfigs))
Discussed f2f - it's not a performance problem, as `make(x, y)` preallocates a slice, but for some reason default value of slice (schedulerapi.HostPriorityList) is not a nil, but empty slice...

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32575#-:-KSajeaBAnUXEiRpFCd9:bb6ywmx)*

**Pull request merged**
