### PR TITLE
always collect containerd logs during e2e-node tests

### PR DESCRIPTION
**Pull request by MHBauer**
containerd is almost always running, even below docker

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Instead of configuring all of the tests that use containerd to collect the containerd logs, it looks better to collect the containerd logs by default, as it is almost always running.

**Which issue(s) this PR fixes**:
Helping to debug tests.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/cc @mikebrow 
/assign @dims

### CODE REVIEW

**Review by mikebrow — COMMENTED** [review]
LGTM
logs!

**Comment by MHBauer** [comment]
looks like it works to me if you check the  
pull-kubernetes-node-e2e job 
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/95411/pull-kubernetes-node-e2e/1314290597049143296/artifacts/tmp-node-e2e-079a38db-cos-81-12871-1200-0/containerd.log

**Comment by MHBauer** [comment]
testing /test
/test

**Comment by MHBauer** [comment]
nope, not in the list, looking for ci-kubernetes-node-kubelet-benchmark

**Comment by MHBauer** [comment]
Given that I don't think it'll fail, it's less 'required' logs, and more 'collect by default' logs.

**Comment by ehashman** [comment]
Re: https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/test/e2e_node/services/logs.go#L76

Is this still valid? It sounds like we want to move away from requiring runtime-specific logs from this comment?

**Comment by MHBauer** [comment]
@ehashman 
> Re:
> 
> https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/test/e2e_node/services/logs.go#L76
> 
> Is this still valid? It sounds like we want to move away from requiring runtime-specific logs from this comment?

https://github.com/kubernetes/kubernetes/pull/95411#issuecomment-705805738
https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/test/e2e_node/services/services.go#L165-L174

It does not matter. It does not fail if the log does not exist, so we might as well have a big list of desired logs.

I can clean it up some more, since I am already in here.

**Pull request merged**
