### PR TITLE
Automated cherry pick of #59083: Ensure IP is set for Azure internal loadbalancer

### PR DESCRIPTION
**Pull request by brendandburns**
Cherry pick of #59083 on release-1.9.

#59083: Ensure IP is set for Azure internal loadbalancer

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
gofmt varification still failed. run hack/update-gofmt.sh

**Comment by brendandburns** [comment]
@jdumars  @feiskyer this is ready to go now, I think...

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
