### PR TITLE
dynamically provision the PVs for cloud provider e2e tests

### LINKED ISSUE #118360: Removal of intree storage plugin is causing us to lose important test coverage
### What happened?

When we removed the intree plugins - https://github.com/kubernetes/kubernetes/pull/116301 

We are also removing the e2es and in-process losing coverage such as for pre-provisioned or inline volumes. This causes those code paths to be error prone.

IMO - my naive thinking was to remove the plugin actively from `kubernetes/pkg` etc, but at the same time keep the vendored dependencies so as we can build the e2e and keep using it.

### What did you expect to happen?

Run e2e and I would expect inline, pre-provisioned volume tests to still be running.

### How can we reproduce it (as minimally and precisely as possible)?

Run e2e and

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We need to remove cloud provider dependencies from our vendor, which will lose some tests that don't use dynamically provision PVCs and volume creation/deletion is out of scope for Kubernetes.

We need to use Dynamic provision PVs and then copy the fields to Pod/PV objects to simulate importing these objects outside.

For a more detailed discussion refer to: https://github.com/kubernetes/kubernetes/issues/118360#issuecomment-1570750797
#### Which issue(s) this PR fixes:

Fixes #118360

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
@msau42 This is my first experience with the e2e test for k8s and I'm not sure I'm doing it right, so please help correct me if the approach is not as expected! :)

**Comment by rishiraj88** [comment]
Please guide me on using the comments starting with '/' to effect specific platforn tasks like testing and code execution.

**Comment by HirazawaUi** [comment]
> Please guide me on using the comments starting with '/' to effect specific platforn tasks like testing and code execution.

You might get something helpful from: https://prow.k8s.io/command-help?repo=kubernetes%2Fkubernetes

**Comment by HirazawaUi** [comment]
@msau42 Do you have time to take a look?

**Comment by gnufied** [comment]
Can you rebase this PR? And test it with real cluster? I doubt this PR works as written.

**Comment by HirazawaUi** [comment]
> And test it with real cluster? I doubt this PR works as written.

I remember I have tested this PR on gce and aks and it works fine.


> otherwise none of the pods will be schedulable by default.

If the pod cannot be scheduled, the e2e test will fail directly, right? so I think the pod has been scheduled normally.

I am in an environment where I don’t have easy access to public cloud (including gcp and azure), but I have purchased aks and gce to test this PR. Considering that this PR is almost a year old now, I have lost too many details about using public cloud storage, but it is undoubtedly working properly.

**Comment by jsafrane** [comment]
I think a better place for pre-provisioned / in-line volume creation is in implementations of e2e [ProviderInterface](https://github.com/kubernetes/kubernetes/blob/2f6c4f5eab85d3f15cd80d21f4a0c353a8ceb10b/test/e2e/framework/provider.go#L89) functions `CreatePD` / `DeletePD` / `CreatePVSource` / `DeletePVSource`, e.g. in [the AWS test provider](https://github.com/kubernetes/kubernetes/blob/6aebda9b1e358e6c79416923ada758d99b479d9d/test/e2e/framework/providers/aws/aws.go). 
You will need to pass a namespace (or the whole `framework`) there to create the PVCs / Pods in the right place, however, it will allow non-storage tests to benefit from these functions, e.g. in autoscaler tests: https://github.com/kubernetes/kubernetes/blob/74888e49f2c2696ba3ad83875c77a40628823605/test/e2e/autoscaling/cluster_size_autoscaling.go#L482-L483

**Comment by HirazawaUi** [comment]
@jsafrane

Thank you for your review.

However, it has been a year since this PR was submitted, and I have lost context and do not have enough bandwidth to fix it. In order to not affect our scheduled progress, I will choose to close it and let others continue working on it.

I hope that my work still has some merits and can provide some convenience for future work.

**Pull request closed without merging**
