### PR TITLE
skip if ResourceHealthStatus is disabled

### LINKED ISSUE #126426: [Flaking Test][sig-node] Device Plugin Failures Pod Status [NodeFeature:ResourceHealthStatus] will report a Healthy and then Unhealthy single device in the pod status
### Failure cluster [9fb245590f3f7a34151d](https://go.k8s.io/triage#9fb245590f3f7a34151d)

In multi test grid:
- https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-features
- https://testgrid.k8s.io/sig-node-containerd#pull-containerd-node-e2e
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features

##### Error text:
```
[FAILED] Timed out after 60.001s.
Expected
    <[]v1.ResourceStatus | len:0, cap:0>: nil
to equal
    <[]v1.ResourceStatus | len:1, cap:1>: 
        - name: test.device/device-plugin-failures-9005
          resources:
          - health: Healthy
            resourceID: testdevice
In [It] at: k8s.io/kubernetes/test/e2e_node/device_plugin_failures_pod_status_test.go:160 @ 07/27/24 19:46:29.206

```
#### Recent failures:
[2024/7/29 09:16:22 ci-crio-cgroupv2-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-features/1817730650166267904)
[2024/7/29 09:12:23 ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1817729643927572480)
[2024/7/29 09:12:22 ci-cos-cgroupv2-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-features/1817729643990487040)
[2024/7/29 09:12:22 ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1817729644124704768)
[2024/7/29 09:06:23 ci-cos-cgroupv1-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1817728133495787520)

/kind failing-test
/sig node

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #126426

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by endocrimes — COMMENTED** [review]
/lgtm
/approve

**Comment by kannon92** [comment]
Looking at this I don't know if this PR is actually causing it. I will look into this.

**Comment by kannon92** [comment]
https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-resource-health-status fixed this issue.

/hold cancel

**Pull request merged**
