### PR TITLE
Upgrade dep json-iterator/go to fix base64 decode bug

### LINKED ISSUE #62742: POST rejects base64 data containing newlines, but PATCH accepts it
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: Trying to `kubectl apply -f` a `Secret` with a multi-line string in its `data` throws an error if it is being created, but works fine if it is overwriting an existing `Secret`.

**What you expected to happen**: The `kubectl apply -f` of the `Secret` with a multi-line string should either succeed or fail in both cases described above.

**How to reproduce it (as minimally and precisely as possible)**:
**secret-multiline.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  config: |
    aW52b2ljZTogMzQ4NDMKZGF0ZSAgIDogMjAwMS0wMS0yMwpiaWxsLXRvOiAmaWQwMDEKICAgIGdp
    dmVuICA6IENocmlzCiAgICBmYW1pbHkgOiBEdW1hcnMKICAgIGFkZHJlc3M6CiAgICAgICAgbGlu
    ZXM6IHwKICAgICAgICAgICAgNDU4IFdhbGttYW4gRHIuCiAgICAgICAgICAgIFN1aXRlICMyOTIK
    ICAgICAgICBjaXR5ICAgIDogUm95YWwgT2FrCiAgICAgICAgc3RhdGUgICA6IE1JCiAgICAgICAg
    cG9zdGFsICA6IDQ4MDQ2CnNoaXAtdG86ICppZDAwMQpwcm9kdWN0OgogICAgLSBza3UgICAgICAg
    ICA6IEJMMzk0RAogICAgICBxdWFudGl0eSAgICA6IDQKICAgICAgZGVzY3JpcHRpb24gOiBCYXNr
    ZXRiYWxsCiAgICAgIHByaWNlICAgICAgIDogNDUwLjAwCiAgICAtIHNrdSAgICAgICAgIDogQkw0
    NDM4SAogICAgICBxdWFudGl0eSAgICA6IDEKICAgICAgZGVzY3JpcHRpb24gOiBTdXBlciBIb29w
    CiAgICAgIHByaWNlICAgICAgIDogMjM5Mi4wMAp0YXggIDogMjUxLjQyCnRvdGFsOiA0NDQzLjUy
    CmNvbW1lbnRzOiA+CiAgICBMYXRlIGFmdGVybm9vbiBpcyBiZXN0LgogICAgQmFja3VwIGNvbnRh
    Y3QgaXMgTmFuY3kKICAgIEJpbGxzbWVyIEAgMzM4LTQzMzgu

```

**secret-dummy.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  config: ZHVtbXk=

```

The following command gives an error:
```bash
$ kubectl apply -f secret-multiline.yaml
Error from server (BadRequest): error when creating "secret-multiline.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret: ObjectMeta: v1.ObjectMeta: TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 76, error found in #10 byte of ...|TQzMzgu\n"},"kind":"|..., bigger context ...|3QgaXMgTmFuY3kKICAgIEJpbGxzbWVyIEAgMzM4LTQzMzgu\n"},"kind":"Secret","metadata":{"annotations":{"kube|...

```

However, this works:
```bash
$ kubectl apply -f secret-dummy.yaml
secret "mysecret" created
$ kubectl apply -f secret-multiline.yaml
secret "mysecret" configured
```

**Anything else we need to know?**: I was able to reproduce this both on a cluster with kubernetes `v1.8.7` and with minikube using version `v1.10.0`. In both cases `kubectl` was `v1.10.0`.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): Arch Linux
- Kernel (e.g. `uname -a`): 4.15.15-1-ARCH

### PR DESCRIPTION
**Pull request by ceshihao**
**What this PR does / why we need it**:
upgrade dep `json-iterator/go` to fix base64 decode bug #62742

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62742

**Special notes for your reviewer**:
Just upgrade `json-iterator/go` to latest which includes base64 decode fix https://github.com/json-iterator/go/pull/266
No other code changes

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
/assign
Please update your git version and rerun. Your older git version is causing changes to comments in Godeps.json when there shouldn’t be.

**Comment by ceshihao** [comment]
@cblecker Thanks for reminder.

I have regenerated `Godeps.json` using a new version git.

**Comment by cblecker** [comment]
/hold
There's an issue with deps on master.

**Comment by cblecker** [comment]
Please run `hack/update-staging-godeps.sh`

**Comment by ceshihao** [comment]
commit after run `hack/update-staging-godeps.sh`

**Comment by cblecker** [comment]
/cc @lavalamp 
/sig api-machinery

Any concerns with bumping this dep, @lavalamp?

**Comment by lavalamp** [comment]
I'm not super thrilled with the use of unsafe package, other than that it seems fine. I guess we already do unsafe things occasionally :(

/approve

**Pull request merged**
