### PR TITLE
remove strings.compare(), use string native operation

### PR DESCRIPTION
**Pull request by knightXun**
I notice we use strings.Compare() in some code, we can remove it and use native operation.

### CODE REVIEW

**Comment by knightXun** [comment]
@ solty i made wrong operation....

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by ericchiang** [comment]
A note that strings.Compare's godoc recommends not using it.

> Compare is included only for symmetry with package bytes. It is usually clearer and always faster to use the built-in string comparison operators ==, <, >, and so on.

/approve

**Pull request merged**
