### PR TITLE
Prevents the attempt to create an existing namespace, in the kubefed init routine

### LINKED ISSUE #47159: kubefed init errors if namespace already exists
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG

**What happened**:

```
$ kubectl create ns federation-system
$ kubefed init my-fed --dns-provider=google-clouddns \
        --federation-system-namespace="federation-system" \
        --etcd-persistent-storage=false
Error from server (AlreadyExists): namespaces "federation-system" already exists
```

**What you expected to happen**:
I expected the command to not error if the namespace already existed.
kubefed should only create a namespace if it doesnt already exist, otherwise just use the one i gave.

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:
nope

### PR DESCRIPTION
**Pull request by arthur0**
**Fixes errors in the `kubefed init` routine, when an existing namespace is passed as `--federation-system-namespace` parameter.**

Fixes #47159

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
I am not entirely sure if we want to do this. Right now, we say make assumptions that there is only one federation control plane per namespace. A lot of operations in `kubefed join` is based on this assumption. This change breaks the assumption.

**Comment by arthur0** [comment]
I understand. It's possible to verify if the annotation  "federation-name" already exists in the existent namespace, if it is the case, prevents the creation of federation control plane and shows the message like "should be only one federation control plane per namespace", what you think @madhusudancs ?

**Comment by arthur0** [comment]
cc @derekwaynecarr

**Comment by madhusudancs** [comment]
@arthur0 I am not sure how that would work. Could you please elaborate a bit?

**Comment by arthur0** [comment]
@madhusudancs Yes I can:
* Create the federation namespace, if not exists, with "federation.alpha.kubernetes.io/federation-name" annotation

* If the namespace exists and it has the annotation, return the error: 
`the federation.alpha.kubernetes.io/federation-name annotation already exists for namespace my-own-namespace and there is allowed only one federation control plane per namespace`

* If the namespace exists and not have the annotation, create it.

**Comment by arthur0** [comment]
@k8s-ci-robot ok to test

**Comment by madhusudancs** [comment]
@arthur0 sorry about the delay. It's not very different than the current approach, is it? If you are checking if the annotation exists, you might as well check if the namespace exists right?

**Comment by arthur0** [comment]
I thought I could have a namespace dedicated to my setup resources before `kubefed init` and this routine would add the own resources and the annotation that indicates that Federation Control Plane was deployed in this namespace. 

I know this validation based on annotation is not a better way to solve the issue, so I'm closing this PR.

**Comment by madhusudancs** [comment]
@arthur0 This solution solve your failure scenario. But most failures of this type occur because previous instance of kubefed failed to complete or simply crashed. It wouldn't solve that. We need a more generic solution to this problem.

**Comment by arthur0** [comment]
@madhusudancs I agree.

**Pull request closed without merging**
