### PR TITLE
unit test for kubectl config use-context

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
unit test for kubectl config use-context

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
think you

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@adohe

**Comment by ymqytw** [comment]
Similar comments as in https://github.com/kubernetes/kubernetes/pull/43450#pullrequestreview-28713087.

**Comment by ymqytw** [comment]
@k8s-bot ok to test

**Comment by ymqytw** [comment]
/release-note-none
/lgtm
@zjj2wry need a rebase.

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Comment by ymqytw** [comment]
@zjj2wry Please squash commits.

**Comment by ymqytw** [comment]
`Jenkins verification` is failing.
Please run `hack/update-bazel.sh` to update.

**Comment by ymqytw** [comment]
@k8s-bot bazel test this

**Comment by ymqytw** [comment]
@fabianofranz Mind Approve?

**Pull request merged**
