### PR TITLE
Delete not working writePerfData

### LINKED ISSUE #18642: getDebugInfo from e2e/metrics_util.go does not work
For quite some time we're seeing errors like:
```
01:12:58 Dec 14 01:12:58.971: INFO: Warning: Error trying to fetch threadcreate debug data: Get https://146.148.76.126/debug/pprof/threadcreate?debug=2: x509: certificate signed by unknown authority
```

This code should be either fixed (if someone is really looking at those profiles), or removed if it's there only because it may be useful eventually.

@wojtek-t moved this function to metrics_util and I'm not sure who was the original author. Any opinions
@dchen1107 @timothysc @davidopp?

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #18642

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
`ERROR: Error fetching remote repo 'origin'`...

@k8s-bot unit test this

**Comment by gmarek** [comment]
wait flake: #19067
@k8s-bot unit test this

**Pull request merged**
