### PR TITLE
Versioned Configuration Management - Design Proposal

### PR DESCRIPTION
**Pull request by khenidak**
This is a design proposal that describes how Kubernetes can be modified to allow the following:
1. Versioned configuration management (ConfigMaps).
2. Consistent configuration management release cycle (following existing roll-forward, roll back process).
3. Apply new configuration without the need to restart pod's containers.

The design change will not break existing features and existing pods and containers can be deployed on Kubernetes without change.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35394)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Previous discussion in #31701, #22368, #30716

**Comment by bgrant0607** [comment]
And #24957, re. signals. #9043 re. in-place rolling update or #13488 re. rolling restart.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by khenidak** [comment]
I signed it!

**Comment by khenidak** [comment]
I signed it!

**Comment by bgrant0607** [comment]
@khenidak Thanks for the proposal. Unfortunately it's pretty far from something we'd accept. I suggest discussing your issues at SIG Apps.
https://github.com/kubernetes/community/blob/master/sig-apps/README.md

cc @pwittrock @kargakis

**Pull request closed without merging**
