### PR TITLE
Symlink cluster/gce/cos to cluster/gce/gci

### PR DESCRIPTION
**Pull request by mtaufen**
Fixes: #43139

As I just unfortunately found out after spending an hour getting to the point where I could test this, upgrade.sh does not support upgrading nodes to local binaries. So someone will have to cut a release to test whether this change actually works.

### CODE REVIEW

**Comment by mtaufen** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by ethernetdan** [comment]
@gmarek @vishh does this look okay? 

@enisoc I'd like to get this in `beta.4` if possible

**Comment by enisoc** [comment]
@ethernetdan Ack. I will wait to cut beta.4.

**Pull request merged**
