### PR TITLE
Fix comments on caculating scores.

### PR DESCRIPTION
**Pull request by hurf**
Minor change in comments by formula given in priorities.go

### CODE REVIEW

**Comment by gmarek** [comment]
Looks good to me, but I prefer syntax from priorities.go: (((capacity - requested) * 10) / capacity), as it has explicit bracketing, which I like.

**Comment by hurf** [comment]
Sure, I'll modify to the format with explicit bracketing.

**Comment by gmarek** [comment]
Perfect. Thanks for fixing this. I'll merge this change in the afternoon.

**Comment by gmarek** [comment]
Can you squash commits?

**Comment by hurf** [comment]
@gmarek - I've done that, sorry for the time gap.

**Pull request merged**
