### PR TITLE
Add UT test to openstack_test.go

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
add ut test to toAuth3Options func
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign @dims
PTAL thanks

**Comment by dims** [comment]
Thanks @jianglingxia !

**Pull request merged**
