### PR TITLE
Remove deprecated cadvisor flags

### PR DESCRIPTION
**Pull request by dims**
The cadvisor flags were deprecated way back in:
8ec1958667e66fb3da2a1f1428998f59f8b027f2

It's time to clean them up!

Change-Id: I9a9def6e2b41c818f1c47126ae2f4a6034bf0563

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove deprecated flags that were leaked from cadvisor
```

### CODE REVIEW

**Comment by dashpole** [comment]
I'm not sure i'm comfortable with this, given that we still compile cAdvisor into the kubelet, and users of cAdvisor rely on many of those flags.  IMO, we should wait until cAdvisor is removed to remove its flags.

**Comment by dims** [comment]
@dashpole is there a KEP or issue for removing cadvisor entirely?

**Comment by dashpole** [comment]
I would say that is covered by https://github.com/kubernetes/kubernetes/issues/68522

**Comment by dims** [comment]
thanks @dashpole 
/close

**Pull request closed without merging**
