### PR TITLE
fix err message typo and small change in UX

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
1. small ux change

2. fix typo: convertable to convertible

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
What's the UX change?  Scoping the `err`?

**Comment by zjj2wry** [comment]
@deads2k maybe you say，i just unknow describe，main fix typo 😊，think you～

**Pull request merged**
