### PR TITLE
Add myself as reviewer to test/conformance/OWNERS

### PR DESCRIPTION
**Pull request by spiffxp**
I'd like to start fielding more reviews of this code since I'm actively
involved in efforts that are consumers of it

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
I'd rather get an /lgtm from one of the existing approvers in this file than go off my own test/OWNERS-based /approve

**Comment by mml** [comment]
/lgtm
/approve

Pretty quiet around these parts, but welcome aboard.

**Pull request merged**
