### PR TITLE
Add Service integration tests for internalTrafficPolicy when Type=ExternalName

### PR DESCRIPTION
**Pull request by andrewsykim**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This is a follow-up to https://github.com/kubernetes/kubernetes/pull/104846 -- I figured it wouldn't hurt to add some integration tests that exercise the new API behavior introduced and to ensure we don't regress. 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
The new Service storage registry unit tests are pretty extensive actually, so maybe these tests are actually not needed? Thoughts?

/assign @khenidak @thockin

**Comment by aojea** [comment]
> k8s.io/kubernetes/pkg/controller/statefulset: TestStatefulSetControlLimitsHistory expand_more	

/retest

**Pull request merged**
