### PR TITLE
Generate missing enums and add enums to docs in openapi

### LINKED ISSUE #113830: Include enum details in descriptions of api/openapi-spec/v3/ json files
### What would you like to be added?

In `api/openapi-spec/v3/*.json` fields, the openapiv3 `description` of enum fields should contain the documentation of all the enum values. This provides language client users with convenient access to all the API documentation available for all enum values.

*Background:*

In discovery, OpenAPIv3 enum fields include both a openapiv3 `enum` field enumerating the supported enumeration values and documentation of the enum fields in the `description`field. E.g.:

```json
"type": {
  "description": "Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate.\n\nPossible enum values:\n - `\"OnDelete\"` Replace the old daemons only when it's killed\n - `\"RollingUpdate\"` Replace the old daemons by new ones using rolling update i.e replace them on each node one after the other.",
  "type": "string",
  "enum": [
    "OnDelete",
    "RollingUpdate"
  ]
}
```

However, in order to not break clients that are generated from the openapiv3 stored in json files under api/openapi-spec/v3, we do not include the `enum` field:

```
"type": {
  "description": "Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate.\n\n",
   "type": "string"
}
```

Excluding enum here was done intentionally, for two reasons:
- Clients currently consider the field a 'string', and for many language clients, changing a field value from string to an enum is backward incompatible.
- Using an enum can break clients when a enum value is added.

But there is not reason not to include all possible documentation about the enum values in the `description` field.

### Why is this needed?

Provides language client users with full documentation about enum values.

### PR DESCRIPTION
**Pull request by jpbetz**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #113830

Also generates enums that were fixed by https://github.com/kubernetes/kube-openapi/pull/327.

#### Does this PR introduce a user-facing change?

```release-note
Add enum symbol documentation to description fields of enums in OpenAPIv3 discovery endpoints.
```

### CODE REVIEW

**Comment by jpbetz** [comment]
cc @jiahuif

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by liggitt** [comment]
included in https://github.com/kubernetes/kubernetes/pull/114869

/close

**Pull request closed without merging**
