### PR TITLE
Show openapi custom columns in `kubectl get`

### LINKED ISSUE #143: Enable use-openapi-print-columns in kubectl
If the openapi scheme lists the columns to print for an object, we should print them.

### PR DESCRIPTION
**Pull request by apelisse**
Change the name of the flag to something slightly more user-friendly,
while making it default true. The flag is kept so that someone can
revert it temporarly if things go wrong.

**What this PR does / why we need it**: OpenAPI can specify for some columns to be used in `kubectl get`. That's very useful for non-core/hard-coded type in order to print more valuable data in get.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Closes kubernetes/kubectl#143

**Release note**:
```release-note
`kubectl get` will now use OpenAPI schema extensions by default to select columns for custom types.
```

### CODE REVIEW

**Comment by apelisse** [comment]
cc @droot 

Must be merged after #53472

/hold

**Comment by smarterclayton** [comment]
I'd like to see this also applied to the server side code so we're not only working on half the solution.

**Comment by apelisse** [comment]
I'm probably missing some context. Could you elaborate?

How is this half the solution, since it does exactly what I expect?

**Comment by smarterclayton** [comment]
We are moving most of this to the server side.  In the last release, we
said that more additions to kubectl get needed to be paired to changes on
the server side table serving so that they don't fall out of sync.  Turning
this on by default in the client without changing the server means the
server side components are now falling behind.

**Comment by apelisse** [comment]
*Updated to fix the broken tests.*

I don't disagree with you but:
- This is a short patch, I don't think it adds too much to the technical debt,
- Why shouldn't we take an easy win when it's there? People actually need that feature:
- We really shouldn't let that happen: https://twitter.com/prydonius/status/917816589201879040 :smile:

**Comment by arschles** [comment]
> We really shouldn't let that happen: https://twitter.com/prydonius/status/917816589201879040 😄

+1 on this. We already have the custom column syntax documented in the [service-catalog walkthrough docs](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#step-3---viewing-clusterserviceclasses). Being able to remove it and have the custom columns "just work" (from the user perspective) would be tremendous from a UX point of view.

**Comment by pwittrock** [comment]
@smarterclayton I don't follow the argument that we should hold off on UX improvements in the client so the server doesn't fall behind.  Isn't needing to pairing client / server features the opposite of what we want since we can expect to work in client / server version skewed environments and will never be able to transactionally update both.

Failing to provide an adequate solution for printing extensions will likely result in folks doing something much worse - such as forking kubectl and compiling in custom logic (yes this was proposed), or writing plugins to print resources.

**Comment by smarterclayton** [comment]
I'm trying to land server side for 1.9 (although it's pretty close to the
wire).  We have to have that to support any realistic extension use case.
The server is ultimately the one who controls output, not the client,
because the client will always be field skewed with the server.  I'd rather
focus on finishing server side than continuing to poke at it from the CLI
side.  Are you saying you don't agree with the move to have it on the
server side?

On Tue, Nov 14, 2017 at 11:52 PM, Phillip Wittrock <notifications@github.com

**Comment by pwittrock** [comment]
@smarterclayton Thanks for all you responses.

> The server is ultimately the one who controls output, not the client, because the client will always be field skewed with the server.

I believe the implementation here is still driven by the server.  As I understand it, this approach and the server-side-printing approach are very similar - in both cases the server provides to the client a list of columns + the structured data to populate those columns, and the client then formats the data for printing in a generic way without compiling in any information about the type.  In neither case should version skew occur since the server controls the data is printed by the client.  (round-tripping through structs aside, which won't happen for extension types and really shouldn't happen for non-extension types)

The difference with this implementation vs server-side-printing, is 1) that the server attaches the columns metadata to the object *schema* instead of including it in the response body, and 2) the server cannot pre-process the information in the object configuration.

> Are you saying you don't agree with the move to have it on the server side?

Not entirely.  Btw, do you have a link to the latests design for server-side-printing?  I read the initial design, but that was some time ago, and things have probably changed since I read it.

The information currently in `describe` - absolutely - yes this belongs in server-side-printing.

The information in `get` - I think we need to be careful about what we provide from the server.  Note: *I do not intend this PR as a replacement for server-side-printing for get*.

I am wary of having the server do much pre-processing of the data in the object configuration for a simple `get` / *GET*.  I tend to think the information in `get` should be pulled directly from what is in the object configuration (I am sure there are some exceptions to this but don't know what they are), and have controllers write back aggregated / pre-processed information to the Status fields. 
  This is done instead of having the printer perform aggregation or processing.  This approach simplifies the printer and makes the information more accessible through the usual means to language specific clients (such as client-go).  What we have seen with the pre-processing done in `describe` is that users come to depend on that data and then build tools that consume it because they don't want to calculate it themselves (understandably).  In these cases, I would prefer users got the data directly from the status of the object instead of having the printer alter both formatting and the information.

> I'd rather focus on finishing server side than continuing to poke at it from the CLI side. 

I don't think this will reduce focus on server side printing except that it reduces the negative impact of server side printing failing to land in 1.9, and reduces the impact of unknown-unknowns discovered with server-side-printing post code freeze.  The feature enabled in this PR was completed and merged in 1.8, but kept as opt-in.  This PR is limited to changing the default flag value so it is opt-out, and updating some tests.

*My own bias'ed analysis:*

## Risks of not enabling this feature in 1.9

- server side printing doesn't land in 1.9
- server side printing lands in 1.9 but has unknown-unknowns that prevent it from adequately addressing the needs of extensions in 1.9 (either on the server side, or in the client integration)
- server side printing lands in 1.9, but extensions have trouble rebasing their extension servers on the 1.9 codebase (I find this rather challenging myself)

## Risks of enabling this feature

- it introduces an *optional* dependency (only used if can be retrieved) on openapi for `get` (unknown-unknowns)
  - similar types of risks would be present for integrating server-side-printing in the client
  - we've optimized retrieving openapi now so it is relatively small (serialized proto), cached correctly (not just ttl based), and fast to parse
- it gets some adoption over server-side-printing
  - if this happens, we should figure out why and use this to improve server-side-printing

Thoughts?

**Comment by pwittrock** [comment]
@smarterclayton Planning on lgtming this today if you have no other comments.

**Pull request merged**
