### PR TITLE
refactor(apiserver): remove the insecure flags

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: Jian Zeng <anonymousknight96@gmail.com>

#### What type of PR is this?

/kind cleanup
/kind deprecation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver: the insecure address flags `--address`, `--insecure-bind-address`, `--port` and `--insecure-port` (inert since 1.20) are removed
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jonyhy96** [comment]
hi @knight42 i found that i issued a duplicate pr on that, maybe u can checkout my pr which is barely same as ur's but remove some in kubeadm test files. would be grateful if u add me as a co-author on this

**Comment by liggitt** [comment]
change looks good, but is the e2e bringup failure legitimate? is that invocation setting one of the deprecated flags?

**Comment by aojea** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/106859/pull-kubernetes-e2e-gce-ubuntu-containerd/1468413601273352192/artifacts/e2e-ba468f5940-a7d53-master/kube-apiserver.log

> Error: unknown flag: --address

**Comment by knight42** [comment]
@liggitt Hi! All tests passed now.

**Pull request merged**
