### PR TITLE
scheduler: remove deprecated v1beta3 KubeSchedulerConfiguration component config

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
v1beta3 has been deprecated since v1.26(https://github.com/kubernetes/kubernetes/pull/112257/commits/700065a18dc72f89c3d849de01e01c735135ba4f), it can be removed in v1.29 as planed.

#### Which issue(s) this PR fixes:

Ref: #117556

#### Does this PR introduce a user-facing change?

```release-note
kube-scheduler component config (KubeSchedulerConfiguration) kubescheduler.config.k8s.io/v1beta3 is removed in v1.29. Migrate kube-scheduler configuration files to kubescheduler.config.k8s.io/v1.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
-[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/785-scheduler-component-config-api
```

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
As planned, we can remove now.
/lgtm
/hold for @alculquicondor

**Comment by alculquicondor** [comment]
:partying_face: 
/hold cancel
/approve

**Comment by SataQiu** [comment]
/assign @liggitt
for api approve

**Pull request merged**
