### PR TITLE
Job: Fix test case names for the validations

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I fixed test case names for the validations.
In actual behavior, the case `update pod failure policy` removes the podFailurePolicy, and the case `remove pod failure policy` updates the podFailurePolicy.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm 
/assign @alculquicondor

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by tenzen-y** [comment]
@deads2k @liggitt @smarterclayton Hi API reviewers! 
Could you please take a look? Thanks in advance.

**Pull request merged**
