### PR TITLE
CLEANUP: cmd/kube-apiserver: fully qualify option references for clarity

### PR DESCRIPTION
**Pull request by sttts**
/kind cleanup

Cleanup the option field names and make structure explicit. Pure field renaming.

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt 

I think this can wait for a week or so right @sttts ?

**Comment by sttts** [comment]
/hold

We have to decide whether we really want this noise, or part of it.

**Comment by haircommander** [comment]
if we do go for it, LGTM from SIG-node perspective :+1:

**Comment by liggitt** [comment]
I don't feel super-strongly about the change... "Values" seems slightly worse than "Extra", the rename churn is unpleasant and the result is clearer, but not *that* much clearer.

🤷

**Comment by sttts** [comment]
Not doing this for now.

**Pull request closed without merging**
