### PR TITLE
Update network plugin version to v1

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
@feihujiang Just update the code to use v1 API.

### CODE REVIEW

**Comment by feihujiang** [comment]
Could you please remove the line of [The fields "apiVersion" and "kind" are optional in version v1beta1](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/exec/exec.go#L40) in exec.go  since v1beta1 isn't supported?

**Comment by WIZARD-CXY** [comment]
Ok

**Comment by feihujiang** [comment]
Thanks. 
The code looks okay to me, but I'm not familiar with this module, so that may not be worth a lot.

**Comment by WIZARD-CXY** [comment]
@feihujiang I found this little bug because I've developed a new k8s network plugin https://github.com/WIZARD-CXY/cxy-sdn and want use this piece of code.

**Comment by dalanlan** [comment]
Ref #16849

**Comment by WIZARD-CXY** [comment]
ping @thockin since it's a very small change

**Comment by thockin** [comment]
This is a very small change, but it's not right, unfortunately.  The network plugin API is not v1 yet.

**Comment by dalanlan** [comment]
Maybe it's better to recover the doc change[ #16849] (v1->v1beta1);-)

**Comment by feihujiang** [comment]
@thockin What's the [// This struct represents version "v1"](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L59) mean or just a wrong note?

**Comment by thockin** [comment]
That's a good point, and probably a bug in the comment.

**Comment by feihujiang** [comment]
@thockin Thanks, got it.

**Comment by feihujiang** [comment]
@WIZARD-CXY Would you like to open a new PR to recover the doc change and fix the bug in the comment.?

**Comment by WIZARD-CXY** [comment]
@thockin @feihujiang Then what version is the right version?

**Comment by feihujiang** [comment]
I think it is v1beta1.

**Comment by feihujiang** [comment]
@WIZARD-CXY I have free time, so let me fix these.

**Comment by WIZARD-CXY** [comment]
ok

May the force be with you

**Pull request closed without merging**
