### PR TITLE
Allow disabling LoadBalancer HealthCheck port allocation

### PR DESCRIPTION
**Pull request by xh4n3**
#### What type of PR is this?
/kind feature
/sig network

#### What this PR does / why we need it:
Some LoadBalancer implementations choose to route traffic to pods (or nodes where the target pods are running), instead of attaching every node to the LoadBalancer's backend, e.g. [Alibaba Cloud](https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/v2.7.0/pkg/controller/service/clbv1/vgroups.go#L429-L437), [Huawei Cloud](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/release-1.17/pkg/cloudprovider/huaweicloud/elb.go#L566-L607). In such cases, allocating a HealthCheck port would be unnecessary (node port is precious). This PR adds the `--enable-service-health-check-port` flag to allow disabling HealthCheck port allocation (for apiserver) and serving (for kube-proxy).

#### Special notes for your reviewer:
A similar case is the [spec.allocateLoadBalancerNodePorts](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation), where a kubernetes user can specify if a service should be allocated with a NodePort. However, since the LoadBalancer implementation in one cluster is not changing, I think a global flag for apiserver and kube-proxy is enough.

#### Does this PR introduce a user-facing change?
```release-note
Introduce the `--enable-service-health-check-port` flag to allow disabling HealthCheck port allocation (for apiserver) and serving (for kube-proxy).
```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

This will require a KEP, I personally don't like the idea of make this a flag

**Comment by xh4n3** [comment]
@aojea Thanks for the input. I created https://github.com/kubernetes/enhancements/issues/4144 to discuss this. Would you mind sharing your thoughts on this?

**Comment by xh4n3** [comment]
Will create a new PR for this.

**Pull request closed without merging**
