### PR TITLE
Fix an 'index out of range' panic when setting capabilities.

### PR DESCRIPTION
**Pull request by yifan-gu**
cc @yujuhong @feiskyer

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33417)

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM

**Comment by yifan-gu** [comment]
@k8s-bot test this please issue #IGNORE

**Comment by yifan-gu** [comment]
@k8s-bot gke e2e test this

**Comment by feiskyer** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Pull request merged**
