### PR TITLE
self nominate aroradaman as sig-network-reviewer

### PR DESCRIPTION
**Pull request by aroradaman**
#### What this PR does / why we need it:

What started as a hobby to spend a few hours on weekends has become a passion 😄
Now I'm more familiar with the networking code base of k/k, I'd like to continue helping.

PR(s) authored/reviewed: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Aaroradaman+label%3Asig%2Fnetwork

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by PranitRout07** [comment]
Hey @aroradaman i am also trying to understand the code bases? Can you suggest some of strategies you have followed to understand the codebase?

**Comment by aojea** [comment]
This alias is to wide and covers a lot of code, including apiserver and controller manager.
Should we make you reviewer in a more specific area, afaik you were involved mostly in kube-proxy bits, that I'm supportive of you as reviewer there

**Comment by aojea** [comment]
> This alias is to wide and covers a lot of code, including apiserver and controller manager. Should we make you reviewer in a more specific area, afaik you were involved mostly in kube-proxy bits, that I'm supportive of you as reviewer there

Talked offline with @danwinship and @thockin , in the future will revisit the approver alias but this is correct and you have done a great work so far

/lgtm

**Comment by aroradaman** [comment]
/retest 

> Kubernetes e2e suite: [It] [sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance] [sig-node, Conformance]

**Comment by aroradaman** [comment]
> Hey @aroradaman i am also trying to understand the code bases? Can you suggest some of strategies you have followed to understand the codebase?


@PranitRout07 we can connect async on k8s slack.

**Comment by thockin** [comment]
congrats and thanks!

**Pull request merged**
