### PR TITLE
4009/add e2e tests for cdi devices

### PR DESCRIPTION
**Pull request by elezar**
#### What this PR does / why we need it:

This is a follow-up to #118254 that adds end-to-end tests for the use of CDI devices in the device plugin.

See specifically https://github.com/kubernetes/kubernetes/pull/118254#issuecomment-1632628972

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm
/ok-to-test

we plan to have this work ready for the _next_ cycle, hence the priority

**Comment by ffromani** [comment]
I believe the lanes are now failing for a missing/wrong import

**Comment by elezar** [comment]
> I believe the lanes are now failing for a missing/wrong import [EDIT] of course no rush to fix, we can (and likely should) wait for the parent PR to be merged.

Yes, this only contains the commit on top at the moment, so none of the dependencies / proto updates are there.

**Comment by bart0sh** [comment]
The test was added by https://github.com/kubernetes/kubernetes/pull/121440
/close

**Pull request closed without merging**
