### PR TITLE
Fix statefulset conversion

### LINKED ISSUE #87583: unable to reapply statefulset with volumeClaimTemplate/apiVersion
**What happened**:
I tried to apply the same statefulset twice and on the second apply, the api reported a validation error.

**What you expected to happen**:
I would expect that the same statefulset should apply successfully or fail consistently any number of times.

**How to reproduce it (as minimally and precisely as possible)**:
Apply this stateful set twice.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

The second attempt with fail.
```
The StatefulSet "web" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Anything else we need to know?**:
The cause of this appears to be the combination of the api server removing the `apiVersion` and `kind` fields from the applied configuration, and the api server performing validation to see that nothing has changed in the config.  The same issue does not appear in kubernetes v1.16 because even though the `apiVersion` and `kind` fields are removed, the validation is not performed.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug
/priority critical-urgent

**What this PR does / why we need it**:
Fixes apiVersion/kind defaulting of the PVC object nested within statefulsets to match what conversion accomplished for us in 1.16.

Also updated local-up-cluster defaults to match kube-apiserver defaults (this problem was only reproducible with a storage type of protobuf)

**Which issue(s) this PR fixes**:
Fixes #87583

**Does this PR introduce a user-facing change?**:
```release-note
Fix regression in statefulset conversion which prevented applying a statefulset multiple times.
```

/cc @apelisse @wojtek-t 
/sig apps

### CODE REVIEW

**Comment by lavalamp** [comment]
Why did proto storage have a different behavior?

**Comment by liggitt** [comment]
@smarterclayton can confirm, but my understanding is that JSON encoding is self-identifying. Proto storage encodes apiVersion and kind separately from the rest of the object (and therefore omits encoding apiVersion/kind fields directly) so the correct type can be determined to decode the rest of the bytes to. The handling of that is done specially for top-level items, and that special handling wasn't in place for this nested type.

**Comment by lavalamp** [comment]
Ah, we tell the proto encoder to ignore those fields.

We probably need to have a different top level object for embedding; this change fixes up the current data but isn't future proof if these fields could hold more than one value.

**Comment by liggitt** [comment]
> this change fixes up the current data but isn't future proof if these fields could hold more than one value.

actually, I think I need to rework this to be a custom conversion to get round-tripping happy again, and they actually cannot hold more than one value... these are embedded v1 PersistentVolumeClaim objects, so their apiVersion/kind must always be v1/PersistentVolumeClaim

**Comment by liggitt** [comment]
there are a few things that caused this that we'll want to avoid:
* embedding top-level (typemeta-containing) types inside individual object schemas (this was the only one I found in a sweep)
* using reflect-based conversion which has these unpleasant magical side-effects (@wojtek-t and @smarterclayton are looking at excising that)

**Comment by lavalamp** [comment]
ah, makes sense!

**Comment by liggitt** [comment]
Switched to conversion-based approach, round-trip tests pass. Will add unit tests specifically around this issue, then will be ready for review

**Comment by liggitt** [comment]
added an integration test to exercise the whole decoding/defaulting/conversion/storage stack.

on master:
```
--- FAIL: TestVolumeTemplateNoopUpdate (3.24s)
    testserver.go:181: runtime-config=map[api/all:true]
    testserver.go:182: Starting kube-apiserver on port 50401...
    testserver.go:198: Waiting for /healthz to be ok...
    statefulset_test.go:106: StatefulSet.apps "web" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

with this fix:
```
--- PASS: TestVolumeTemplateNoopUpdate (3.77s)
    testserver.go:181: runtime-config=map[api/all:true]
    testserver.go:182: Starting kube-apiserver on port 50544...
    testserver.go:198: Waiting for /healthz to be ok...
```

**Comment by wojtek-t** [comment]
> using reflect-based conversion which has these unpleasant magical side-effects (@wojtek-t and @smarterclayton are looking at excising that)

Yeah - I'm trying to get rid of it completely and I'm actually not that far from it. Though I'm always lacking time for it...

**Comment by liggitt** [comment]
fixed staticcheck error in test file

**Comment by sathieu** [comment]
This probably caused ServerSide apply to generate a diff when the applied `volumeClaimTemplates` item has no `apiVersion`/`kind`. See https://github.com/argoproj/argo-cd/issues/11143.

Maybe the [doc](https://v1-25.docs.kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components) should be updated to include `apiVersion` and ` kind`?

**Pull request merged**
