### PR TITLE
Verify metadata schema when decoding unstructured objects in resource builder

### LINKED ISSUE #660: Kubectl silently remove all annotation if any of them is set to the string true without quotes
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
Tested on 1.12 , 1.13 and 1.14 

**Environment**:
- **Cloud provider or hardware configuration**: GKE and local Kind Cluster

**What happened**:
When applying a manifest for which one of the annotations has the value _true_ unquoted then all annotations are removed when the resource is created on the cluster.

Please see https://github.com/weaveworks/flux/issues/2091 as the original issue that brought me to this conclusion.

From that case you can also see a way to reproduce the issue using KIND and this test repo [here](https://github.com/primeroz/flux-bug-test-repo/)

**What you expected to happen**:
The resource to be created with all the annotations attached and an annotation with the string _true_ 

I would expect an error at least 

**How to reproduce it** (as minimally and precisely as possible):
Follow the example in [this repo](https://github.com/primeroz/flux-bug-test-repo/) using flux or just `kubectl create namespace vault && kubectl apply -f https://github.com/primeroz/flux-bug-test-repo/blob/master/test-cm-no-checksum/ConfigMap-vault-vault-auth-jwt.yaml`

**Anything else we need to know**:

I am not 100% sure this is a kubectl or apiserver validation issue but i felt that if it was the apiserver i would get an error back rather than a silent drop , reason why i am creating this one here

### LINKED ISSUE #59113: kubectl-apply silently drops annotations with boolean values
/kind bug

**What happened**:
When creating resource with boolean value in annotation, kubectl apply completes sucessfully without any errors, but resource has no annotations.

**What you expected to happen**:

Error similar to what `kubectl create` returns

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl apply -f <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    bool: true
data: {}
EOF
configmap "test" created
```

Creates:
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"kube-system"}}
  creationTimestamp: 2018-01-31T14:23:42Z
  name: test
  namespace: kube-system
  resourceVersion: "9612155"
  selfLink: /api/v1/namespaces/kube-system/configmaps/test
  uid: 5689a651-0692-11e8-a6e3-005056bced2e
```

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

### LINKED ISSUE #67966: annotations not being applied to ingress and no subsequently no events
/kind bug

**What happened**:

Applied ingress with annotations and the annotations are ignored.

**What you expected to happen**:

The annotations to be applied and visible when describing the ingress.

**How to reproduce it (as minimally and precisely as possible)**:

Apply this;

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ydos-ingress
  namespace: ydos
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1M
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "YDOS-SESSION-EX"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ydos/wildcard-yellowdog-tech-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
spec:
  tls:
  - hosts:
    - service.yellowdog.tech
    secretName: wildcard-yellowdog-tech-secret
  rules:
  - host: service.yellowdog.tech
    http:
      paths:
      - path: /ydos
        backend:
          serviceName: ydos-svc
          servicePort: 80
```

Describe the ingress;

`$ kubectl describe ingress ydos-ingress -n ydos
Name:             ydos-ingress
Namespace:        ydos
Address:          130.61.9.241
Default backend:  default-http-backend:80 (<none>)
TLS:
  wildcard-yellowdog-tech-secret terminates service.yellowdog.tech
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  service.yellowdog.tech
                          /ydos   ydos-svc:80 (<none>)
Annotations:
Events:  <none>
`

**Anything else we need to know?**:

This is being deployed into a kubernetes ingress-nginx environment. The nginx controller is being updated but no annotations are being applied by kubernetes so affinity is not being configured in the nginx pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+2.1.5.el7", GitCommit:"ea4c95b07dd46d5563e4f6851ede13157bf04266", GitTreeState:"archive", BuildDate:"2018-03-23T02:54:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.1-2+e49fe6296d12ea", GitCommit:"e49fe6296d12ea823430bb7bda457d1201b17277", GitTreeState:"clean", BuildDate:"2018-07-24T14:24:53Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
NAME           STATUS    ROLES     AGE       VERSION   EXTERNAL-IP    OS-IMAGE                  KERNEL-VERSION                  CONTAINER-RUNTIME
130.   Ready     node      8d        v1.11.1   130.61.33.85   Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1
130.    Ready     node      8d        v1.11.1   130.61.74.1    Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1
130.   Ready     node      8d        v1.11.1   130.61.95.73   Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #68227: Service annotations for AWS ELB randomly does not "take"
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Defined the nginx ingress controller service like so:

```
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: '...'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: true
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: 5
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: 'my-bucket'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: 'ingress-elb'
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
```

**What you expected to happen**:

A new ELB with TLS certificate on port 443, no TLS certificate on port 80, and access logs sent to S3 bucket "my-bucket".

The load balancer is created, TLS certificate is attached as expected, no access logging is configured. Furthermore, changing the annotations and re-applying the spec has non-deterministic results. I removed the annotations regarding the logging setup, and the TLS certificate was eventually removed from my load balancer. I had to destroy it and re-create it for it to exist again.

I am also unable to confirm whether or not the annotations are actually created. Listing the service with either `kubectl get service -n ingress-nginx ingress-nginx -o json` or `kubectl describe service` shows only one annotation, `kubectl.kubernetes.io/last-applied-configuration`.

**How to reproduce it (as minimally and precisely as possible)**:

Create a service with the above annotations, observe that no logging is set up.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): OSX
- Kernel (e.g. `uname -a`): 16.7.0
- Install tools: kops

### LINKED ISSUE #70962: Annotations broken with 'kubectl apply -f'
**What happened**:
We applied an ingress with annotations that had integers as values but no annotations were applied in Kubernetes and no failure was thrown.

**What you expected to happen**:
We would expect an error to be thrown similar to this one:
`error: services "your-service" could not be patched: cannot convert int64 to string`

**How to reproduce it (as minimally and precisely as possible)**:
Create a file `anno-test-service.yaml` with the following:
```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    test.key: "1"
    #test.key: 2
  name: anno-test-service
  namespace: default
spec:
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
```
Apply, `kubectl apply -f ./anno-test-service.yaml`
Verify, `kubectl get service anno-test-service -o yaml | grep "test.key"`

Uncomment `test.key: 2`
Apply, `kubectl apply -f ./anno-test-service.yaml`
Verify, `kubectl get service anno-test-service -o yaml | grep "test.key"`

You will see that it fails to apply any annotations this time but continued to apply the service without errors.  To get an error edit manually with `kubectl edit service anno-test-service` and add `test.key: 2`.

**Anything else we need to know?**:
This bug can be replicated on anything that uses annotations as long as it is applied using a file: `kubectl apply -f`

We have confirmed this exists on `1.10.x` -> `1.12.x` versions of kubectl

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.9", GitCommit:"474de708598cdefe41816d37ba8e2de66a2d4d55", GitTreeState:"clean", BuildDate:"2018-11-02T23:44:11Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
**Google GKE**
- OS (e.g. from /etc/os-release):
**Ubuntu**
- Kubectl Version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
```
- Stackdriver logs:
**Manual Edit Failure**:
```
{
 insertId:  "ezs8fceiw238"  
 labels: {
  cluster_version:  "1.10.7-gke.9"   
 }
 logName:  "projects/cloud-dev/logs/cloudaudit.googleapis.com%2Factivity"  
 protoPayload: {
  @type:  "type.googleapis.com/google.cloud.audit.AuditLog"    
  methodName:  "io.k8s.extensions.v1beta1.ingresses.patch"   
  request: {
   @type:  "k8s.io/Patch"    
   metadata: {
    annotations: {
     ingress.kubernetes.io/proxy-connect-timeout:  60      
    }
   }
  }
  resourceName:  "extensions/v1beta1/namespaces/kube-system/ingresses/kube-dashboard"   
  response: {
   @type:  "core.k8s.io/v1.Status"    
   apiVersion:  "v1"    
   code:  500    
   kind:  "Status"    
   message:  "cannot convert int64 to string"    
   status:  "Failure"    
  }
  serviceName:  "k8s.io"    
 }
 receiveTimestamp:  "2018-11-12T20:28:53.543783353Z"  
 severity:  "ERROR"  
 timestamp:  "2018-11-12T20:28:47.983545Z"  
}
```

**kubectl file apply success (but failed to apply annotations, they are NULL)**:
```
{
 insertId:  "18ot33oei0sx8"  
labels: {
  cluster_version:  "1.10.7-gke.9"   
 }
 logName:  "projects/cloud-dev/logs/cloudaudit.googleapis.com%2Factivity"  
 protoPayload: {
  @type:  "type.googleapis.com/google.cloud.audit.AuditLog"   
  methodName:  "io.k8s.extensions.v1beta1.ingresses.patch"   
  request: {
   @type:  "k8s.io/Patch"    
   metadata: {
    annotations: {
     ingress.kubernetes.io/auth-signin:  null      
     ingress.kubernetes.io/auth-url:  null      
     ingress.kubernetes.io/ssl-redirect:  null      
     ingress.kubernetes.io/whitelist-source-range:  null      
     kubectl.kubernetes.io/last-applied-configuration:  "{"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"kube-dashboard","namespace":"kube-system"},"spec":{"rules":[{"host":"kube.dev.cloud","http":{"paths":[{"backend":{"serviceName":"kube-dashboard","servicePort":80},"path":"/"}]}}],"tls":[{"hosts":["kube.dev.cloud"],"secretName":"tls-env-cloud"}]}}
"      
     kubernetes.io/ingress.class:  null      
     kubernetes.io/tls-acme:  null      
    }
   }
  }
  resourceName:  "extensions/v1beta1/namespaces/kube-system/ingresses/kube-dashboard"   
  serviceName:  "k8s.io"   
 }
 receiveTimestamp:  "2018-11-12T20:35:50.350227061Z"  
 severity:  "NOTICE"  
 timestamp:  "2018-11-12T20:35:43.100513Z"  
}
```

/kind bug

### LINKED ISSUE #82536: Unexpected handling of invalid ingress annotation
**What happened**:

I used kubectl to apply an Ingress resource with an annotation, whose value was accidentally an integer (instead of a string). The Kubernetes API server accepted the resource, but silently removed all annotations (also valid ones).

**What you expected to happen**:

I expected, that the server either rejects the resource or removes only the invalid annotation.

**How to reproduce it (as minimally and precisely as possible)**:

Create minimal Ingress resource file with one wrong typed annotation, e.g. *ingress.yaml* with:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invalid-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: 240
spec: 
    rules:
      - host: invalid-domain.invalid
```

Now apply it:

```
lukas@lukas-ThinkPad-T460p:~/Downloads$ kubectl apply -f ingress.yaml 
ingress.extensions/invalid-ingress created
```

Afterwards get the resource definition from the server:

```
lukas@lukas-ThinkPad-T460p:~/Downloads$ kubectl get -o yaml ingress invalid-ingress
[...]
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: [...]
  creationTimestamp: "2019-09-10T14:51:29Z"
  [...]
```

_metadata.annotations_ only contains the key _kubectl.kubernetes.io/last-applied-configuration_, but not _kubernetes.io/ingress.class_ from the original definition.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux compute-0017.prod.figo.systems 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz GenuineIntel GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #84759: Kubectl drops all annotations when one is not a valid string.
**What happened**:'
Kubectl drops all annotations when one is not a valid string.  for example true/false/on/off

**What you expected to happen**:
EIther warn on bad annoations or fail on the first one. 

**How to reproduce it (as minimally and precisely as possible)**:

Take this foo.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    foobar: on
    bar: avalidstring
  name: panaji-ing
  namespace: shared
  labels:
    msftkube/app: panaji-ing
spec:
  rules:
  - host: some-host.foo.com
    http:
      paths:
      - backend:
          serviceName: some-service
          servicePort: grpc
```
kubectl apply --dry-run -f .\foo.yaml -o yaml

The output will not contain the annotation. (just last-applied)

More relistic exmples might be these nginx annotations
```
   nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/auth-tls-verify-client: on
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.7
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): windows
- Kernel (e.g. `uname -a`): win10
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ensures resource builder doesn't hand off unstructured objects with schema-invalid metadata to commands that can accidentally truncate annotations/labels/etc with accessor get/set invocations

**Which issue(s) this PR fixes**:
Fixes #59113
Fixes https://github.com/kubernetes/kubernetes/issues/70962 
Fixes https://github.com/kubernetes/kubernetes/issues/68227 
Fixes https://github.com/kubernetes/kubectl/issues/660 
Fixes https://github.com/kubernetes/kubernetes/issues/82536 
Fixes https://github.com/kubernetes/kubernetes/issues/67966
Fixes https://github.com/kubernetes/kubernetes/issues/84759

**Does this PR introduce a user-facing change?**:
```release-note
Commands like `kubectl apply` now return errors if schema-invalid annotations are specified, rather than silently dropping the entire annotations section.
```

/sig cli

### CODE REVIEW

**Comment by jpbetz** [comment]
This looks right. Do we need to do anything for `ListMeta`?

/lgtm

**Comment by liggitt** [comment]
we never post ListMeta to the server (and it only overlaps with ObjectMeta on SelfLink/ResourceVersion, both of which are compatible), so I don't think so

**Pull request merged**
