### PR TITLE
Healthcheck the kubelet on the secure port rather than the read-only port.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by karlkfi** [comment]
Why health check on the secure port and then disable SSL cert verification? Why not just give it the root CA so it can validate?

I'm also not clear why you would want to health check on the SSL port in the first place, given that the readonly http method is always enabled (given the current impl).

**Comment by roberthbailey** [comment]
The read-only port was a temporary hack to make local healthchecking & heapster keep working. I want to get rid of the read-only port before more services start to depend on it. 

I suppose we could do a secure check on platforms where the root cert exists, but I'm not sure that it's in a consistent enough place to add it in yet.

**Comment by roberthbailey** [comment]
@karlkfi Have I addressed your concerns?

**Comment by roberthbailey** [comment]
Ping @karlkfi

**Comment by roberthbailey** [comment]
Accidentally closed this, but still hoping for @karlkfi to take a second look.

**Comment by andyzheng0831** [comment]
Please also change cluster/gce/trusty/node.yaml line 403.

**Comment by roberthbailey** [comment]
Re-assigning to @dchen1107

**Comment by roberthbailey** [comment]
@andyzheng0831 done.

**Comment by roberthbailey** [comment]
Ping @dchen1107.

**Comment by karlkfi** [comment]
Sorry I missed the ping. Was letting the firehose of notifications fly past me for a while, but I'm caught up again.

I don't have a problem with this change, but I also don't feel like I have made enough changes to or use the GCE cluster to really have authority to approve other changes. I'd like someone from google to approve.

@andyzheng0831 or @eparis are the likely candidates.

**Comment by roberthbailey** [comment]
Thanks @karlkfi. I was really trying to make sure you didn't object to the change. :)

**Comment by karlkfi** [comment]
I'm still not sure we're going to remove the read-only endpoint in the near future. So users can still  configure their own health/checks however they want. Since this only affects the automated GCE cluster (or anything else that uses salt), I'm not too worried about it. I'd be more nervous about limiting serving `/healthz` to SSL-only, which requires slightly increased cpu.

That said, I've learned that `/healthz` is a bit of a hybrid liveness/readiness endpoint, depending on how the component uses it. Liveness certainly doesn't need SSL, from a data encryption standpoint, but readiness may be much more expensive and potentially return more sensitive details. In which case, a little more SSL overhead is unlikely to be a big deal. Tho in this case the more sensitive data is on the `/healthz/*` endpoints, not on the root `/healthz` which just returns "ok".

**Comment by mikedanese** [comment]
@karlkfi less ports == better? Probably want to move this discussion into #12968 for visibility.

**Comment by karlkfi** [comment]
I don't feel super strongly about it. Agree that less ports is good and the cpu cost is probably too low to be a bottleneck, at least not before we get to real HA.

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
