### PR TITLE
Use const value for pod's conditions

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by henriquetruta** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44720)*

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
