### PR TITLE
add a regression test for Audit-ID http header

### PR DESCRIPTION
**Pull request by CaoShuFeng**
This change add a test for: https://github.com/kubernetes/kubernetes/pull/48492

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@CaoShuFeng: please rebase

**Comment by CaoShuFeng** [comment]
@sttts 
Rebased.

**Pull request merged**
