### PR TITLE
CHANGELOG.md: update outdated link

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
I am not sure that if the file was generated automatically. 
But I find some links were outdated. 
Release note:

NONE

### CODE REVIEW

**Comment by cblecker** [comment]
Updating 1.6 makes sense, but I don't think we need to go back and update links from 1.4, etc.

**Comment by zhangxiaoyu-zidif** [comment]
@cblecker I am not sure that if it's worth updating these links. If you think it is unnecessary, that would be fine to close this PR. :).

**Comment by brendandburns** [comment]
This seems fine to me, I agree with @cblecker wrt 1.4.

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@brendandburns Hi! I do not know what is wrt1.4. Dose it mean I need fix these links from v1.4 on. :)
Thanks for your reviewing.

**Comment by cblecker** [comment]
@zhangxiaoyu-zidif You've suggested changes around lines 1000-1006 and lines 1210-1213. Those are part of the 1.6 changelog. You've *also* suggested changes around 4517-4521, and 6243-6250. Those are in the 1.4 and 1.2 changelog sections.

**Comment by zhangxiaoyu-zidif** [comment]
@cblecker @brendandburns 
PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot node e2e test this

**Comment by brendandburns** [comment]
@zhangxiaoyu-zidif wrt == "with regards too" apologies, it's an english acronym, I should have been more verbose.

/lgtm
/approve

**Comment by zhangxiaoyu-zidif** [comment]
@brendandburns @cblecker Thank you！ you are both nice and kind~ ：）

**Pull request merged**
