### PR TITLE
Admission control attributes has access to resource name

### PR DESCRIPTION
**Pull request by derekwaynecarr**
I have a use case where I want to prohibit deletion of a resource because it is immortal!

In OpenShift we have a couple namespaces that should never be deleted that hold key infrastructure components required to run the server.  I want to prevent deletion of these namespaces via admission control as a backstop to our own policy enforcement.

In order to support an immortal resource in admission control, I need access to the resource name and namespace on the request.  Right now, we just had namespace because we were pulling name from the request object on create/update.  On delete, that object is not available so we need to pass it into admission control.

I am fine if this is post Kube 1.0.

Related: https://github.com/openshift/origin/issues/3274

### CODE REVIEW

**Comment by saad-ali** [comment]
Assigned @bgrant0607

v1.0 triage needed

**Comment by derekwaynecarr** [comment]
@bgrant0607 - do you want to block deletion of the ```default``` namespace in Kube 1.0?  In the GCE scenario (not sure about GKE), if a user was to delete the namespace, the system does reprovision it with the requisite services, but it would result in losing all the add-ons, etc.  In OpenShift, we were concerned about deleting our ```openshift-infra``` namespace because that holds the service account credentials used to run all of our controllers.  It's protected via policy and auth, but the root account could accidentally delete it (which I did when testing), and bad things result from that for us.  Either way, I could see an argument that the ```default``` namespace is also immortal and should not be purged at least for Kube 1.0.  If you agree, I can augment this PR with a change to ```NamespaceLifecycle``` plug-in to prevent deletion of ```default``` namespace.

**Comment by bgrant0607** [comment]
Yes, deletion of the default namespace would not be good.

**Comment by derekwaynecarr** [comment]
Ok.  I will add that to this PR tomorrow and poke it.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - I modified the PR to prevent deletion of the ```default``` namespace.  This should be good to go.

**Comment by bgrant0607** [comment]
LGTM.

This does mean that we'll probably need to add a special shutdown method to enable us to recursively delete everything, as discussed in #4630, but we can cross that bridge later.

**Comment by bgrant0607** [comment]
I proposed a solution to the shutdown problem in #10179.

**Comment by jlowdermilk** [comment]
@derekwaynecarr, the shippable failure looks like bad sync. Can you rebase?

**Comment by derekwaynecarr** [comment]
Rebased.  Will see how shippable responds this time.

**Comment by jlowdermilk** [comment]
Sorry something else I merged caused a conflict. On the bright side, the test that was causing timeouts is disabled at head, so rebase should also fix Shippable.

**Comment by bgrant0607** [comment]
```
Auto-merging plugin/pkg/admission/serviceaccount/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/serviceaccount/admission_test.go
Auto-merging plugin/pkg/admission/securitycontext/scdeny/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/securitycontext/scdeny/admission_test.go
Auto-merging plugin/pkg/admission/resourcequota/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/resourcequota/admission_test.go
Auto-merging plugin/pkg/admission/namespace/lifecycle/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/namespace/lifecycle/admission_test.go
Auto-merging plugin/pkg/admission/namespace/autoprovision/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/namespace/autoprovision/admission_test.go
Auto-merging plugin/pkg/admission/exec/denyprivileged/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/exec/denyprivileged/admission_test.go
Auto-merging plugin/pkg/admission/deny/admission_test.go
CONFLICT (content): Merge conflict in plugin/pkg/admission/deny/admission_test.go
Auto-merging pkg/apiserver/resthandler.go
CONFLICT (content): Merge conflict in pkg/apiserver/resthandler.go
Auto-merging pkg/admission/interfaces.go
CONFLICT (content): Merge conflict in pkg/admission/interfaces.go
Auto-merging pkg/admission/attributes.go
CONFLICT (content): Merge conflict in pkg/admission/attributes.go
Automatic merge failed; fix conflicts and then commit the result.
```
#10052 was merged, so my guess is that this conflicts with that.

**Comment by derekwaynecarr** [comment]
Rebased.

**Pull request merged**
