### PR TITLE
bump metadata-proxy to v0.1.11, update tests & test image

### PR DESCRIPTION
**Pull request by dekkagaijin**
Picks up https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/26

@mikedanese PTAL

/kind bug

```release-note
In addition to restricting GCE metadata requests to known APIs, the metadata-proxy now restricts query strings to known parameters.
```

### CODE REVIEW

**Comment by mikedanese** [comment]
@dekkagaijin tests are broke.

**Comment by dekkagaijin** [comment]
The tests should get a job and stop making us working folk deal with their failures.

**Comment by nikopen** [comment]
tests seem to be failing for this, if it's not critical for v1.13.0 then it has to be moved out as code freeze is today at 5pm PST

**Comment by ixdy** [comment]
/approve
/retest

webhook dropped?

**Comment by ixdy** [comment]
`[sig-auth] Metadata Concealment should run a check-metadata-concealment job to completion` failed, which seems problematic?

**Comment by dekkagaijin** [comment]
@ixdy yeah, looks like there's no insight into the failure in the logs, so I'll have to get a test cluster setup myself

**Comment by nikopen** [comment]
@dekkagaijin @ixdy Is it critical for 1.13? If not, it should be moved out to a patch release

/priority critical-urgent

**Comment by AishSundar** [comment]
@ixdy @dekkagaijin is this needed for 1.13? We are code freeze and I rather wait to take this in for 1.14 if its not critical

/remove-priority critical-urgent

**Comment by nikopen** [comment]
`master` will become 1.13.0 in a few weeks, and PRs to master are gatekeeped just before the release. Let's move this to post release so it merges for 1.13.1 or others

/milestone clear

**Comment by dekkagaijin** [comment]
Anything works, I'll keep an eye on this PR

**Comment by dekkagaijin** [comment]
Pinging this again now that 1.13 is out

**Pull request merged**
