### PR TITLE
Bump aws-sdk-go version to workaround #16238

### LINKED ISSUE #16238: godep restore failing due to Godep issue
The aws-sdk-go library just renamed a package from internal -> private to work around Go's vendoring experiment changes:
https://github.com/aws/aws-sdk-go/commit/c09f1bb2f2270137bd1708d4668dc6beb2fb52f2

But we have a Godep dependency on some of these internal packages (we don't use them directly, but Godeps saves them anyway)

The problem is that godep ignores the branch when first pulling the code because it shells out to `go get`, so it tries to do a fetch on a package that doesn't exist on master: https://github.com/tools/godep/issues/186

I think this combines to mean that `godep restore` is broken right now (or at least returning an exit code; I'm not sure if it actually is OK).  If you have a dirty Godeps tree, `hack/verify-godeps.sh` will also fail (but there is a short-circuit in there when the tree is clean which means that Shippable is still passing).

I don't know really how we should fix this (properly).  A workaround is to manually:

```
rm -rf ${GOPATH}/src/github.com/aws/aws-sdk-go/
go get github.com/aws/aws-sdk-go
pushd ${GOPATH}/src/github.com/aws/aws-sdk-go/
git checkout v0.9.9
popd
godep restore
```

### PR DESCRIPTION
**Pull request by justinsb**
This bumps aws-sdk-go to the latest version (currently unreleased), to
workaround a Godep problem when a package listed in Godeps no longer
exists on the master branch.  See #16238 for the gory details.

Fixes #16238.

We will likely want to bump up again to the next released version once
it is released, but this version appears to be pretty similar to the
last released version (0.9.16)

### CODE REVIEW

**Comment by justinsb** [comment]
I'm actually having problems getting this to pass my _local_ commit hooks tests, I think because I've been doing some things that are unusual.  The proof-of-the-pudding is whether shippable approves anyway...

**Comment by justinsb** [comment]
Aha - got it to pass locally by deleting the reference from Godeps.json and Godeps/_workspace and starting from scratch.  Godeps doesn't delete no-longer referenced things from the workspace :-(

**Comment by eparis** [comment]
While I think this is right for "master" for the release 1.1 I think using https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L24 (immediately before `godep restore`) is a safer fix.

**Comment by eparis** [comment]
then again, people rarely update godep in a release branch so maybe we need nothing there   :)

**Comment by davidopp** [comment]
Reassigning to @lavalamp

**Comment by dchen1107** [comment]
ping ... This one blocks #16127. Thanks!

**Comment by lavalamp** [comment]
lgtm... sorry, I thought I already rubber stamped this.

**Comment by eparis** [comment]
the bot was within about 2 minutes of merging this when google internal e2e went red.  do we want to merge by hand to unblock others?

**Pull request merged**
