### PR TITLE
Modify the kubelet document url

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Modify the URL of "KEP 14 - Moving ComponentConfig API types to staging repos"

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by CaoDonghui123** [comment]
need an `/ok-to-test` to run `/test pull-kubernetes-e2e-kind`

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
