### PR TITLE
Adjust Heapster requirements and bump nanny version

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #27185

I verified it by creating a cluster manually, and it works as expected.

@gmarek @Q-Lee @mwielgus @piosz @roberthbailey @fabioy

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM

**Comment by wojtek-t** [comment]
@zmerlynn

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #27276

**Comment by roberthbailey** [comment]
lgtm

**Comment by zmerlynn** [comment]
To be clear, is this superseding #27185? (catching up)

**Comment by zmerlynn** [comment]
Oh, I see the comment in the other one now. Got it, ignoer me. LGTM.

**Comment by wojtek-t** [comment]
Merging manually to unblock our tests.

**Pull request merged**
