### PR TITLE
Fix dbus shutdown events not continuing if they are not valid

### LINKED ISSUE #97951: GracefulNodeShutdown dbus shutdown events not continuing if they are not valid
**What happened**:

https://github.com/kubernetes/kubernetes/blob/9caf675ed1a055ebce18cf34e8284028a729fd00/pkg/kubelet/nodeshutdown/systemd/inhibit_linux.go#L125-L157

 kubelet from panic after getting the wrong signal, and restart.

image

`gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #97951

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
GracefulNodeShutdown avoid getting the wrong signal and not working
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
@wzshiming thanks for the fix.

Can I ask why this is needed? The expectation is this should only be of bool type, since this is doing a dbus match on the `PrepareForShutdown`  on the logind interface `org.freedesktop.login1.Manager` and `PrepareForShutdown` should be supplying a bool: https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html

```
PrepareForShutdown(b start);
```

https://github.com/kubernetes/kubernetes/blob/a525ddc85216f3cf86d82ae68953a4996c13b22a/pkg/kubelet/nodeshutdown/systemd/inhibit_linux.go#L128

Were you seeing something different? Curious to understand in what case / what signal was actually sent?

**Comment by wzshiming** [comment]
@bobbypage

Because can send this signal manually
`gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown true`

I discovered the problem when I first sent the signal with the wrong type

**Comment by bobbypage** [comment]
> Because can send this signal manually

I see... I don't think it's expected that users are suppose to emit `PrepareForShutdown` themselves. Rather, upon a system shutdown, logind will emit this signal:

https://github.com/systemd/systemd/blob/v247/src/login/logind-dbus.c#L1602 

One way you can try it out is with a scheduled shutdown.

```
shutdown -h +1
```

That should result in `logind` sending the `PrepareForShutdown` event to kubelet.

**Comment by wzshiming** [comment]
This effect is not triggered.
The pods didn't shutdown, only the machines shutdown.

**Comment by bobbypage** [comment]
Hmm, I just tried on a GCE instance and was it worked fine.

I spinned up a cluster 1.20 with kubetest2 

```
kubetest2 gce --build --up --legacy-mode --gcp-project ${PROJECT} -num-nodes=1 --gcp-zone=us-central1-c
```

I sshd into the node and enabled the feature gate and updated kubelet config:

```
vim /etc/default/kubelet
# add --feature-gates=GracefulNodeShutdown=true
```


```
vim /home/kubernetes/kubelet-config.yaml
# add the following
shutdownGracePeriod: '30s'
shutdownGracePeriodCriticalPods: '10s'
```

restarted config and kubelet
```
$ systemctl daemon-reload
$ systemctl restart kubelet.service 
```

validate that inhibit lock is taken
```
$  systemd-inhibit
     Who: kubelet (UID 0/root, PID 3406/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```

Deploy a pod that catches SIGTERM as a test, I have [this](https://gist.github.com/bobbypage/a95048136c52b1de35881538806c6f68) little go program as a test. The pod definition is super basic:

```
apiVersion: v1
kind: Pod
metadata:
  name: shutdown-example-app
spec:
  containers:
  - name: shutdown-example-app
    image: gcr.io/my-project/shutdown-app:1.0
```


After the app is deployed, can tail the logs of the pod with kubectl. On the node initiate a scheduled shutdown with `shutdown -h +1`. You should see `Got SIGTERM Shutdown` printed for about 20seconds (as expected) due to the inhibit lock before the machine is fully shutdown.

**Comment by wzshiming** [comment]
I don't know why it doesn't happen automatically.
image

**Comment by bobbypage** [comment]
> I don't know why it doesn't happen automatically.

What do you mean, can you please explain what you observed? Did steps in https://github.com/kubernetes/kubernetes/pull/97952#issuecomment-760643439 not work?

**Comment by wzshiming** [comment]
image

https://www.freedesktop.org/wiki/Software/systemd/inhibit/
> The PreparingForShutdown and PreparingForSleep boolean properties are true between the two PrepareForShutdown() resp PrepareForSleep() signals that are sent out. Note that these properties do not trigger PropertyChanged signals.

I found a problem with this property, but can't find how to modify it

**Comment by bobbypage** [comment]
`PreparingForShutdown` is readonly, so it's expected that you can't modify it. 

```
readonly b PreparingForSleep = false;
```
(xref: https://www.freedesktop.org/wiki/Software/systemd/inhibit/)

As mentioned earlier, I don't think you should be modifying or calling the logind shutdown related APIs manually, instead they should be called by logind as a result of a shutdown (e.g. initiated as `shutdown -h +1`).

**Comment by wzshiming** [comment]
I agree with you, but reality doesn't automatically trigger anything.

**Comment by bobbypage** [comment]
I think it makes sense to debug the inhibit stuff separately: [here's](https://gist.github.com/bobbypage/13ca9e1e8aee728dc2c7e0e1fd9b59ea) a small test program to test the delay inhibitor. 

Run that program and have separate session monitoring `dbus-monitor --monitor --system`.

Then run `shutdown -h +1`.

In my system I see:

dbus get's the schedule shutdown
```
method call time=1610696158.686421 sender=:1.16 -> destination=org.freedesktop.login1 serial=3 path=/org/freedesktop/login1; interface=org.freedesktop.login1.Manager; member=ScheduleShutdown
   string "poweroff"
   uint64 1610696218684738
```

After a minute on my system I see logind sending the `PrepareForShutdown` event:

```
signal time=1610696218.802077 sender=:1.1 -> destination=(null destination) serial=24 path=/org/freedesktop/login1; interface=org.freedesktop.login1.Manager; member=PrepareForShutdown
   boolean true
```

and the go program receives the event and prints "Preparing to Shutdown". 

Do you mind trying that on your system?

**Comment by wzshiming** [comment]
image

**Comment by bobbypage** [comment]
Thanks for the test, it points it's some issue with logind / dbus, not kubelet related. 

I tested on a new fresh ubuntu 20.04 VM and it worked as expected:

```
gcloud compute instances create ub-2 --image-family=ubuntu-2004-lts --image-project=ubuntu-os-cloud --project=${MY-PROJECT} --zone=us-central1-c
```

```
porterdavid_google_com@ub-1:~$ uname -a
Linux ub-1 5.4.0-1034-gcp #37-Ubuntu SMP Wed Jan 6 19:44:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

porterdavid_google_com@ub-1:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

porterdavid_google_com@ub-1:~$ systemd --version
systemd 245 (245.4-4ubuntu3.3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

screenshot

**Comment by wzshiming** [comment]
@bobbypage Thank you very much for your help! 
I'll go to the systemd community to ask this question. 

I think this PR is necessary, merge it to make kubelet more robust.

**Comment by wzshiming** [comment]
If this PR works, merge it to make kubelet more robust!

**Comment by ehashman** [comment]
Per @bobbypage's last comment, it sounds like this is a dbus and/or logind issue, not a kubelet issue, and we've identified a workaround, so I am going to close this.

/close

**Comment by wzshiming** [comment]
> Per @bobbypage's last comment, it sounds like this is a dbus and/or logind issue, not a kubelet issue, and we've identified a workaround, so I am going to close this.
> 
> /close

@ehashman  @bobbypage  
My fix is to avoid kubelet from panic after getting the wrong signal.

image

`gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown`

**Comment by wzshiming** [comment]
@ehashman @bobbypage PTAL

**Comment by bobbypage** [comment]
@wzshiming @ehashman

sorry for the confusion, as per 

> Per @bobbypage's last comment, it sounds like this is a dbus and/or logind issue, not a kubelet issue, and we've identified a workaround, so I am going to close this.
> 
> /close

I think @wzshiming was facing a dbus/logind issue but this PR fixes a different problem which should still be addressed. @wzshiming reopened this as https://github.com/kubernetes/kubernetes/pull/98200 so let's address the issue there.

**Pull request closed without merging**
