### PR TITLE
fix staging godeps

### PR DESCRIPTION
**Pull request by sjenning**
Fixes https://github.com/kubernetes/kubernetes/issues/41909

Just ran `hack/update-staging-godeps.sh` on master

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@deads2k -- this looks like your area?

**Comment by deads2k** [comment]
I just saw this too.  I'm trying to figure out how something merged without being verified.

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/41650 merged via the queue.  I don't understand how we got dirty unless the bot did some crazy stuff.

**Comment by deads2k** [comment]
@eparis once verification passes, this deserves a manual merge.

**Comment by eparis** [comment]
merging by hand. All test passed. Will unblock queue.

**Pull request merged**
