### PR TITLE
Replace klog.V(0).Infof with klog.Infof in some files

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
wow, `V(0)`...
thank you for this cleanup @mysunshine92 

/priority backlog
/ok-to-test
/lgtm

**Comment by mysunshine92** [comment]
cc @dchen1107

**Comment by mysunshine92** [comment]
@dchen1107 @neolit123 , woluld you like to add approved label?

**Comment by neolit123** [comment]
@mysunshine92 try pinging on these slack channels #sig-node, #sig-apps if nobody responds until the end of this week. thanks.

/assign @janetkuo
/retest

**Comment by mysunshine92** [comment]
@dchen1107 @neolit123 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
@dchen1107 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
@dchen1107 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
ping @janetkuo

**Comment by mysunshine92** [comment]
@dchen1107 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
@dchen1107 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
@dchen1107 , woluld you like to add approved label?

**Comment by mysunshine92** [comment]
ping @neolit123

**Comment by mysunshine92** [comment]
ping @k82cn

**Comment by neolit123** [comment]
@mysunshine92
this PR needs approval from sig-node and sig-apps.
you can try pinging them on slack.
thanks

/unassign
/uncc

**Comment by mysunshine92** [comment]
> 
> 
> @mysunshine92
> this PR needs approval from sig-node and sig-apps.
> you can try pinging them on slack.
> thanks
> 
> /unassign
> /uncc

thanks for your help ,i will ping them on slack.

**Comment by mysunshine92** [comment]
ping @k82cn
please add an approved label, thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an approved label, thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label, thanks.

**Comment by k82cn** [comment]
why do we want to change log level?

**Comment by mysunshine92** [comment]
> 
> 
> why do we want to change log level?

@k82cn V(0) is the default log level, so use klog.Infof is ok, which is equal to klog.V(0).Infof.
this PR is cleanup work.
please add an /approve label, thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an approved label, thanks.

**Pull request closed without merging**
