### PR TITLE
include file name in the error when visiting files

### LINKED ISSUE #60916: kubectl apply: print filename along with line number on parse errors
/kind feature

**What happened**:
I ran this command on top of a directory that had an invalid yaml

`kubectl apply --validate=true --dry-run=true --filename=dir_with_multiple_yamls`

kubectl reported this error:

`error: error converting YAML to JSON: yaml: line 17: could not find expected ':'`

From that error message, one has no idea which file contains the syntax error.

Note that on certain different errors, filename is being reported, i.e. when you create a file that just contains "--".

**Minimal example**:

```
mkdir /tmp/kubetest
cd /tmp/kubetest
echo -e "--\na: b" > broken.yaml
kubectl apply --validate=true --dry-run=true --filename=$PWD
```

**What you expected to happen**:

on yaml parse error, kubectl should report filename as well as the line number -- at least in case directory is specified in kubectl apply

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.3+coreos.0 & v1.9.3+coreos.0

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
/kind bug
/sig cli

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60916

**Special notes for your reviewer**:
/cc @kubernetes/sig-cli-api-reviews 
**Release note**:

```release-note
include file name in the error when visiting files
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by dixudx** [comment]
ping @liggitt @smarterclayton for approval. Thanks.

**Pull request merged**
