### PR TITLE
move client/cache and client/discovery to client-go

### PR DESCRIPTION
**Pull request by deads2k**
mechanical changes to move those packages.  Had to create a `k8s.io/kubernetes/pkg/client/tests` package for tests that were blacklisted from client-go.  We can rewrite these tests later and move them, but for now they'll still run at least.

@caesarxuchao @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
hmmm.... may have to break apart testing.  I'll simplify this to just client/cache

**Comment by sttts** [comment]
Looks good!

**Comment by deads2k** [comment]
approved based on https://github.com/kubernetes/kubernetes/issues/40363

**Comment by deads2k** [comment]
pulled in https://github.com/kubernetes/kubernetes/pull/40366 (also in merge queue) to avoid a conflict.

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
