### PR TITLE
verify-golangci-lint.sh: clarify intended usage of warnings

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Contributors have created PRs because the linter found issues. That is often not necessary and should be discussed before working on a PR.

While at it, output formatting gets updated a bit (extra blank lines, wording).

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/hold

In case that we want some additional approver.

**Comment by alculquicondor** [comment]
LGTM

**Comment by pohly** [comment]
/sig testing
/hold cancel

This has enough positive comments that we should go ahead and merge it. Can someone add the milestone?

**Pull request merged**
