### PR TITLE
Automated cherry pick of #93011: fix: azure disk resize error if source does not exist

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #93011 on release-1.18.

#93011: chore: add diskclient.ListByResourceGroup interface

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/retest
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
