### PR TITLE
Clean up local volum provisioner e2e tests

### LINKED ISSUE #28: Migrate all e2e tests from k/k repo
- [x] copy all local volume provisioner e2e tests from k/k repo (#31)
- [x] clean up local provisioner e2e tests in k/k repo (https://github.com/kubernetes/kubernetes/pull/72617)

/assign

e2e tests from k/k repo:

- [x] Local volume provisioner [Serial] should create and recreate local persistent volume
- [x] Local volume provisioner [Serial] should not create local persistent volume for filesystem volume that was not bind mounted
- [x] Local volume provisioner [Serial] should discover dynamically created local persistent volume mountpoint in discovery directory
- [x] Stress with local volume provisioner [Serial] should use be able to process many pods and reuse local volumes (done in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/31)

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/28

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/hold
wait until CI for the external repo is setup and run successfully

**Comment by cofyc** [comment]
I guess we can merge this now.

**Comment by cofyc** [comment]
@msau42 
Done.

- b7a33511e53b9821ef8f5be2754f4d7fa0564bae Clean old local-volume-provisioner tests
- 513ae63bf6d08f87f6dfcd6160677722217f47f9
  - `Stress with local volume provisioner [Serial] should use be able to process many pods and reuse local volumes` is replaced by `"Stress with local volumes [Serial] should be able to process many pods and reuse local volumes` which does not use local-volume-provisioner to provision/recycle PVs

**Pull request merged**
