### PR TITLE
Generate federation apiserver extensions replicaset client

### PR DESCRIPTION
**Pull request by jianhuiz**
generate clientset for extensions/ReplicaSet of federation apiserver

@nikhiljindal @quinton-hoole, @deepak-vij
#24764

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@nikhiljindal Can you take this one please?

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Thanks code changes LGTM.

I cant understand how the commits are ordered.
The 2nd and 3rd commit should have been auto generated after running hack/update-codegen with code changes from the 4th commit?

Can you combine 2nd and 3rd commit and move the 4th commit to be the 2nd commit?

**Comment by jianhuiz** [comment]
arranged commits and rebased

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this issue: #IGNORE

**Pull request merged**
