### PR TITLE
Fix a spelling error

### PR DESCRIPTION
**Pull request by nuistzyw**
> /kind cleanup

**What this PR does / why we need it**:
   Fix a spelling error
**Which issue(s) this PR fixes**:
   Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:
None

### CODE REVIEW

**Comment by nuistzyw** [comment]
@liggitt PTAL

**Comment by nikhita** [comment]
/kind cleanup
/release-note-none

/hold
@nuistzyw can you squash the commits into a single commit?

**Pull request merged**
