### PR TITLE
Wire contexts to Core controllers

### PR DESCRIPTION
**Pull request by damemi**
#### What type of PR is this?
/kind design

#### What this PR does / why we need it:
This wires a context to Core controllers in kube-controller-manager, so that KCM can eventually release on cancel.

This originally came from PR https://github.com/kubernetes/kubernetes/pull/101379, which builds on top of https://github.com/kubernetes/kubernetes/pull/101125

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]

**Comment by nikhita** [comment]
/kind feature
/remove-kind design

We are removing the `kind/design` label. Please see https://github.com/kubernetes/community/issues/5641 for more details.

**Comment by damemi** [comment]
/retest
I think I've gotten to all the feedback, and decided to squash too. Let me know if it would be easier if I broke out the staging components to their own commit. Otherwise, this is ready for some more eyes

**Review by soltysh — COMMENTED** [review]
Two more nits and you're good to go

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
