### PR TITLE
pkg/client: fix staticcheck warning

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

 fix staticcheck warning

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
/assign @SataQiu 
Please add an approved label for hack

**Review by SataQiu — APPROVED** [review]
/approve
for hack

This PR need rebase.

**Comment by hwdef** [comment]
@SataQiu 
Thanks for your review!

**Comment by hwdef** [comment]
@caesarxuchao 
Cloud you please add a lgtm label for this PR?
Thank you very much.

**Pull request merged**
