### PR TITLE
Automated cherry pick of #80157 upstream release 1.15 

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #80157 on release-1.15
#80157 : Remove manual conversions for ListOptions

### CODE REVIEW

**Comment by liggitt** [comment]
/hold
unit tests are flaking on master with this PR. see fix in https://github.com/kubernetes/kubernetes/pull/80236

**Comment by wojtek-t** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/80241 (I also cherrypicked the test fix that Jordan found and fixed)

**Pull request closed without merging**
