### PR TITLE
simplify findServicePort in proxy

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
/kind cleanup

Simplify `findServicePort` and some related code.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
While this is certainly simpler, it also hides that we intentionally only support numerical ports right now. A port reference in general is an IntString in kubernetes.

**Comment by hzxuzhonghu** [comment]
>@hzxuzhonghu worth a UT ?
@krmayankk The existing ut already covered this function.

**Comment by hzxuzhonghu** [comment]
>it also hides that we intentionally only support numerical ports right now. A port reference in general is an IntString in kubernetes.

actually i do not understand very much about this.  If `findServicePort ` is exposed as a public function, I think we should surely keep it as it was. But now it is only used internally to find `443` matching service port.

**Comment by hzxuzhonghu** [comment]
@sttts As @deads2k said https://kubernetes.slack.com/archives/C0EG7JC6T/p1526385005000167 . Services here have a fixed 443 port is intended. Seems in the near future, we would not change `ResolveEndpoint`.

**Pull request closed without merging**
