### PR TITLE
Fix spelling of process

### PR DESCRIPTION
**Pull request by mattkelly**
**What this PR does / why we need it**:

Just a spelling fix for a function name and associated comments.

**Special notes for your reviewer**:
N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mattkelly** [comment]
Looks like a flake to me?

/retest

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by mattkelly** [comment]
Rebased.

**Comment by mattkelly** [comment]
@dixudx rebased again - mind taking another look?

**Review by dixudx — APPROVED** [review]
/lgtm

**Pull request closed without merging**
