### PR TITLE
Cleanup useless metrics.go for garbagecollector

### PR DESCRIPTION
**Pull request by FengyunPan**
The metrics of garbagecollector are already published with the
workqueue metrics, so metrics.go is useless, let's cleanup it.
See https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.

@caesarxuchao we spoke about this before and I think you were convinced.  I'll leave the sign-off to you.

**Comment by caesarxuchao** [comment]
Yes. I had talked with @FengyunPan on the cleanup.

/lgtm

**Comment by caesarxuchao** [comment]
I'll manually add the approval label since @deads2k had lgtm'ed it.

**Pull request merged**
