### PR TITLE
CleanUP the deplicate func in conditions.go

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
delete the deplicate fun ServiceAccountHasSecrets,thanks
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
Where is the same name function?

**Comment by jianglingxia** [comment]
pkg/client/unversioned/conditions.go  @stewart-yu

**Comment by jianglingxia** [comment]
reopen #58915 ,I will close this pr,thanks

**Pull request closed without merging**
