### PR TITLE
add appsv1 deployment generator

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @liggitt 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
lgtm, please squash your changes

**Comment by soltysh** [comment]
Can you please check and fix the basel tests?

**Comment by zjj2wry** [comment]
@soltysh ready

**Comment by zjj2wry** [comment]
rebased, @deads2k you are the owner of this code, can you review this for another look, thanks :- )

**Comment by zjj2wry** [comment]
@liggitt for approve

**Pull request closed without merging**
