### PR TITLE
Add init container pod deletion test

### PR DESCRIPTION
**Pull request by smarterclayton**
Exploring termination revealed we have race conditions in certain
parts of pod initialization and termination. To better catch these
issues refactor the existing test so it can be reused, and then test
a number of alternate scenarios.

Tests issues found in #102344

/hold

As I want to add more tests before merge.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/kind cleanup
/priority important-soon
/triage accepted
/release-note-none

**Comment by SergeyKanzhelev** [comment]
@smarterclayton is it ready to be looked at?

**Comment by smarterclayton** [comment]
/hold cancel

remove commit with more iterations since this passed

**Comment by ehashman** [comment]
/hold

to prevent accidental merging

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Pull request closed without merging**
