### PR TITLE
e2e scheduling priorities: do not reference control loop variable

### PR DESCRIPTION
**Pull request by ingvagabund**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

`podListForEachNode` function references control loop variable when construction `nodeNameToPodList[nodeName]`.
Making all references in the list identical (corresponding to the control variable reference).
Thus, making all the pods in the list identical.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Introduced in https://github.com/kubernetes/kubernetes/pull/100762.

https://play.golang.org/p/tRlv22yrj20 as an example of the current behavior.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
Thank you.

**Review by damemi — COMMENTED** [review]
/lgtm

**Pull request merged**
