### PR TITLE
kubelet: Fix NPE in ephemeral storage eviction

### LINKED ISSUE #98260: kubelet podEphemeralStorageLimitEviction panic
**What happened**:

image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #98260

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix NPE in ephemeral storage eviction
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by bobbypage** [comment]
/retitle kubelet: Fix NPE in ephemeral storage eviction

**Comment by bobbypage** [comment]
Looks reasonable to me, we should check `podStats.EphemeralStorage.UsedBytes != nil` considering it's dereferenced in the next line

/lgtm

**Review by ehashman — APPROVED** [review]
/lgtm

/priority backlog
/triage accepted

**Review by pacoxu — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@wzshiming, @bobbypage does it make sense to cherry-pick this PR to release-1.20 as well?

**Comment by wzshiming** [comment]
> @wzshiming, @bobbypage does it make sense to cherry-pick this PR to release-1.20 as well?

Should not be needed,  release-1.20 this problem does not exist, 

https://github.com/kubernetes/kubernetes/blob/60f1b19e16f949d8df90476df5fde459e095f992/pkg/kubelet/eviction/eviction_manager.go#L508-L539

**Pull request merged**
