### PR TITLE
Add timeout, fix potential startup hang

### LINKED ISSUE #19435: test-update-storage-objects.sh is flaky
Pasted from #16698 

```
!!! [0108 21:12:42] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/healthz; tried 120 waiting 1 between each
!!! Error in ./hack/test-update-storage-objects.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-update-storage-objects.sh:48 startApiServer(...)
  2: ./hack/test-update-storage-objects.sh:123 main(...)
Exiting with status 1
+++ [0108 21:12:42] Killing api server
+++ [0108 21:12:42] Clean up complete
```

I've run this repeatedly, and all I can tell so far is that it's flaky.  The specific flakiness is that sometimes (more often than not) after we've run cluster/update-storage-objects.sh the API server will never become healthy.  The timeout is 2m, and even with --v=10, it's clear that the apiserver is not doing anything.  The process is running.

If after the test fails (I've commented out the cleanup code that kills etcd and apiserver), I kill it and manually start it, it seems to come up every time.

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #19435

@wojtek-t When you get back, take a look at the second commit.
@smarterclayton question for you in the final commit.

### CODE REVIEW

**Comment by deads2k** [comment]
I'm currently in the middle of rebasing openshift on kube, I won't be able to review this in a reasonable time.  Removing my assignment for re-assigning by the bot.

**Comment by yujuhong** [comment]
@lavalamp you may want to assign a reviewer yourself...

**Comment by lavalamp** [comment]
Or @mml, feel free to review this if you want :)

**Comment by mml** [comment]
I can take a look.  @nikhiljindal LMK if you were almost done or something.  I'll give it back.

**Comment by mml** [comment]
Nice work.  LGTM

**Comment by eparis** [comment]
Not that you are likely to notice, but sorry for all the label noise, I was using this PR to test https://github.com/kubernetes/contrib/pull/450

**Comment by lavalamp** [comment]
Thanks @mml! @k8s-oncall this is a flake fix, please consider it a candidate for manual merging.

**Comment by wojtek-t** [comment]
The second commit LGTM - thanks @lavalamp !

**Pull request merged**
