### PR TITLE
remove input parameter that is invalid before

### PR DESCRIPTION
**Pull request by CKchen0726**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
remove input parameter that is invalid before

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by CKchen0726** [comment]
@freeformz @brosner Hi, could you please review the code in this pr? Thanks.

**Comment by JornShen** [comment]
/lgtm 
@msau42 have a free for a look? a little cleanup :)

**Comment by wilsonehusin** [comment]
hello @CKchen0726! can you please edit the PR description to use `NONE` instead of `NA`? `NONE` is the accepted format so that the label `release-note-none` will be added to this PR. thanks!

**Pull request merged**
