### PR TITLE
Automated cherry pick of #67224: Add namespace for (cluster)role(binding) cloud-provider.

### PR DESCRIPTION
**Pull request by grayluck**
Cherry pick of #67224 on release-1.11.

#67224: Add namespace for (cluster)role(binding) cloud-provider.

### CODE REVIEW

**Comment by grayluck** [comment]
Manual test:
```
$ kk auth can-i list configmaps --as=system:serviceaccount:kube-system:cloud-provider
yes
$ kk auth can-i create events --as=system:serviceaccount:kube-system:cloud-provider  
yes
```
/assign @bowei 
/priority important-soon

**Comment by grayluck** [comment]
/assign @foxish 
For milestone 1.11 and cherrypick approval.

**Comment by nikhita** [comment]
/unassign

@foxish is the cherry-pick approved?

**Pull request merged**
