### PR TITLE
refactor: use generic set in kubelet

### PR DESCRIPTION
**Pull request by daemon365**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
specific sets are deprecated
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by swatisehgal** [comment]
/triage accepted
priority/important-longterm

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Comment by haiyux** [comment]
@dcbw @derekwaynecarr PTAL

**Comment by haiyux** [comment]
@bart0sh What do I need to do?

**Comment by bart0sh** [comment]
@haiyux sorry, my bad. Moving further.

**Comment by bart0sh** [comment]
/assign @mrunalp @derekwaynecarr @dchen1107 
for a final approval

**Pull request closed without merging**
