### PR TITLE
Replace package "golang.org/x/net/context" with "context"

### LINKED ISSUE #60560: Should replace all `golang.org/x/net/context` with context
[As of Go 1.7 this package(`golang.org/x/net/context`) is available in the standard library under the name context. https://golang.org/pkg/context. ](https://godoc.org/golang.org/x/net/context) So we should replace all golang.org/x/net/context with context

TODO:

- [ ] when [protoc-gen-go contextPkgPath](grpc contextPkgPath  [golang.org/x/net/context](https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/grpc/grpc.go#L55) ) change to `"context"` remove the `golang.org/x/net/context` from vendor

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
Replace package "golang.org/x/net/context" with "context"

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60560

**Special notes for your reviewer**:
As of Go 1.7 this package(golang.org/x/net/context) is available in the standard library under the name context. see (https://godoc.org/golang.org/x/net/context)

It is almost machinery replace. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
Seems like a good idea.  Please squash.

/approve

**Review by cheftako — APPROVED** [review]
/lgtm

**Comment by hzxuzhonghu** [comment]
squashed

**Comment by hzxuzhonghu** [comment]
resolved conflicts, ping for another approval.

**Comment by deads2k** [comment]
squash bazel please

**Comment by hzxuzhonghu** [comment]
squashed @deads2k

**Comment by deads2k** [comment]
This has been rebased a couple times, bumping priority so it goes in before needing to be redone again.

**Pull request merged**
