### PR TITLE
update go to 1.6.3

### PR DESCRIPTION
**Pull request by jessfraz**
``` release-note
updated go version to 1.6.3
```

### CODE REVIEW

**Comment by spxtr** [comment]
I think you'll need to hit `hack/jenkins/gotest-dockerized.sh` and `build/common.sh`'s `KUBE_BUILD_IMAGE_CROSS_TAG` as well.

**Comment by jfrazelle** [comment]
thanks! updated!

**Comment by dims** [comment]
Looks good to me 👍

**Comment by spxtr** [comment]
LGTM, thanks.

**Comment by spxtr** [comment]
On a side note, we should probably document all these places to bump the version somewhere. When I went to 1.6.1 or 1.6.2 I missed one and it took a long time to realize it.

**Comment by jfrazelle** [comment]
yes I was thinking of even simplifying it by catting a file or something?

**Comment by spxtr** [comment]
That works for some things but we don't always have the source tree handy when we're doing things. In particular, `hack/jenkins/dockerized-e2e-runner.sh` is curled from github without the rest of the source.

**Comment by jfrazelle** [comment]
@spxtr ah makes sense then I can add some docs, do you have a preferred location?

**Comment by spxtr** [comment]
I don't really know a good location. Presumably somewhere in `docs/`, but I'm worried it will go out of date like just about everything else over there.

**Comment by luxas** [comment]
LGTM! :)
`docs/devel` is for developers, but not sure how up-to-date those docs are.

**Pull request merged**
