### PR TITLE
fix typo Kubernets to Kubernetes

### PR DESCRIPTION
**Pull request by Songjoy**
fix typo Kubernets to Kubernetes in line 239

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
i tough we fixed these in a recent PR...

/kind cleanup
/priority backlog
/ok-to-test
/lgtm

**Comment by neolit123** [comment]
thanks for this typo fix @Songjoy !

**Review by neolit123 — APPROVED** [review]

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
