### PR TITLE
Add explanation for large-cluster-size-threshold arg 

### LINKED ISSUE #119499: Arg large-cluster-size-threshold targets zone size not cluster size,  having unmatched effect with arg description
### What happened?

The arg large-cluster-size-threshold for kube-controller-manager works as zone size threshold when determining node eviction rate.  If there are multiple zones, the description for arg stating "cluster" threshold would be missleading.

https://github.com/kubernetes/kubernetes/blob/4457f85eb3dfa34e46d6d776a3b7e89088dc9279/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1152-L1163

ARG: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

### What did you expect to happen?

Matched arg description

### How can we reproduce it (as minimally and precisely as possible)?

Multiple zones cluster

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by JackTroy**
Add explanation for large-cluster-size-threshold arg about multiple zones cluster

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fix misleading description of arg large-cluster-size-threshold

#### Which issue(s) this PR fixes:

Fixes #119499

#### Does this PR introduce a user-facing change?
no

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
no

### CODE REVIEW

**Comment by JackTroy** [comment]
@bart0sh It seems this pr requires triage from node. Could you help with this?

**Comment by mrunalp** [comment]
@deads2k @soltysh ptal

**Pull request merged**
