### PR TITLE
Refactor log* and ssh* fucntions in test/e2e/framework/util.go

### PR DESCRIPTION
**Pull request by WanLinghao**
This commit is part of test/e2e/framework/util.go refactor job.
It moves log function and ssh function to their own packages:
```
test/e2e/framework/log/
test/e2e/framework/ssh/
```
For more detail, please refer:https://github.com/kubernetes/kubernetes/issues/77095
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
oops, it seems it would import huge change both in test/e2e/framework and out test/e2e/framework...
I am not sure if we need this change now..

**Comment by johnSchnake** [comment]
Based on the discussions in related tickets the log stuff got split into multiple PRs which are still ongoing and I put up https://github.com/kubernetes/kubernetes/pull/77336 for the ssh code.

**Comment by timothysc** [comment]
Closing this issue per last comment.

**Pull request closed without merging**
