### PR TITLE
Move file cluster/log-dump.sh -> cluster/log-dump/log-dump.sh in release 1.7

### PR DESCRIPTION
**Pull request by shyamjvs**
DumpClusterLogs step is failing for jobs running against release 1.7 as test-infra expects the file in the new path (i.e. cluster/log-dump/log-dump.sh):
- https://k8s-testgrid.appspot.com/google-gce-scale#gce-1.7

Cherry-picking those commits. I can squash them if you want.

/cc @wojtek-t

### CODE REVIEW

**Comment by shyamjvs** [comment]
fyi - @fejta

**Comment by shyamjvs** [comment]
Also please let's wait for bug-fix https://github.com/kubernetes/kubernetes/pull/49426 to be merged before this, so we can include that too.

**Comment by wojtek-t** [comment]
I'm against this change. If test-infra expects file in new location, just move it there instead of introducing a bunch of changes to release branch.

Also, you need to follow the style of cherrypicks (cherrypick-candiate label on original PRs, added milestone, explanation why this is necessary (usually as a release not, but in this case probably not), etc.)

**Comment by shyamjvs** [comment]
> I'm against this change. If test-infra expects file in new location, just move it there instead of introducing a bunch of changes to release branch.

Do we want to be able to run logexporter on our gce-scalability tests on release branches? If no, I can change this PR to just move the file as you said. If yes, I can squash these commits to single one so we don't add multiple commits in our release branch (especially since most of them are trivial changes).

> Also, you need to follow the style of cherrypicks (cherrypick-candiate label on original PRs, added milestone, explanation why this is necessary (usually as a release not, but in this case probably not), etc.)

Thanks for the lead. Will do it depending on answer to the above question (in case of 'no' I'll have to create a new commit instead of cherry-pick).

**Comment by wojtek-t** [comment]
> Do we want to be able to run logexporter on our gce-scalability tests on release branches?

I don't think we need it for now.

**Comment by shyamjvs** [comment]
@wojtek-t Done. Just moving the file for now. PTAL

**Comment by fejta** [comment]
Isn't this just a regression in kubetest? 

https://github.com/kubernetes/test-infra/commit/ac08d17aec5ad81f60f8ffde3f7ade746e3540c0

**Comment by fejta** [comment]
nm looks like the move was intentional.

What is the motivation for the move?

**Comment by shyamjvs** [comment]
@fejta The reason for moving it was so we can have all scripts logdump-related inside a separate dir (which for now is log-dump.sh and logexporter-daemonset.yaml). Adding them directly inside `cluster/` didn't seem like a good idea, so.

**Pull request merged**
