### PR TITLE
Automated cherry pick of #67705: Set --audit-webhook-mode flag properly based on the env

### PR DESCRIPTION
**Pull request by x13n**
Cherry pick of #67705 on release-1.11.

#67705: Set --audit-webhook-mode flag properly based on the env

### CODE REVIEW

**Comment by x13n** [comment]
@wojtek-t @foxish Can you approve?

**Comment by x13n** [comment]
/retest

Hmm... how can this have both `cherrypick-approved` and `do-not-merge/cherry-pick-not-approved` at the same time?

**Comment by nikhita** [comment]
> Hmm... how can this have both cherrypick-approved and do-not-merge/cherry-pick-not-approved at the same time?

Prow bug. This was fixed in prow. Closing and reopening to retrigger.

**Comment by nikhita** [comment]
/retest

The labels are fixed now. :+1:

**Comment by x13n** [comment]
@nikhita Thanks for fixing the labels!

**Pull request merged**
