### PR TITLE
Adding an example for kubectl plugin list

### PR DESCRIPTION
**Pull request by bergerhoffer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Added an example for kubectl plugin list

#### Does this PR introduce a user-facing change?

```release-note
Added an example for the kubectl plugin list command.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
@bergerhoffer thanks for this! Is there a specific reason you came across the need for this? It would be nice to have someone audit other commands if that's something you're interested in.

/ok-to-test
/lgtm
/approve
/triage accepted
/priority backlog

**Review by eddiezane — APPROVED** [review]

**Comment by bergerhoffer** [comment]
Hi @eddiezane! On OpenShift, we pull these help commands to autogenerate our CLI documentation, and the way it's coded, commands only appear if there is an example for the command. 

This was the only major one that I noticed seemed to be missing now (I had submitted one or two others in the past), but there might be other subcommands that could use them as well.

**Comment by eddiezane** [comment]
@bergerhoffer stellar thank you!

The failing test is some gofmt changes you'll need to fix manually.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106600/pull-kubernetes-verify/1462954599903137792

**Comment by bergerhoffer** [comment]
@eddiezane Just updated, let me know if it looks good, thanks!

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
