### PR TITLE
use log func in test/e2e/apimachinery

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

use log functions of core framework

**Which issue(s) this PR fixes**:

Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM
/assing @oomichi

**Comment by hwdef** [comment]
@oomichi 
Could you please add an approved lable for this PR?
Thank you!

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm
/approve

**Pull request merged**
