### PR TITLE
Automated cherry pick of #110191: kubelet: Pod probes should be handled by pod worker

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #110191 on release-1.22.

#110191: kubelet: Pod probes should be handled by pod worker

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix 1.22 regression so pods will now post their readiness during termination.
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by bobbypage** [comment]
https://github.com/orgs/kubernetes/teams/release-managers - for cherrypick approval

Thank you!

**Comment by aojea** [comment]
> https://github.com/orgs/kubernetes/teams/release-managers - for cherrypick approval
> 
> Thank you!

ping @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
