### PR TITLE
[release-1.28] update build cross image to the correct release branch image

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- update build cross image to the correct release branch image
this just update the image tag to use the correct for the release branch

/assign @liggitt @saschagrunert @Verolop @ameukam 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by danbudris — APPROVED** [review]

**Comment by cpanato** [comment]
cc @kubernetes/release-managers for cherry pick :)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
