### PR TITLE
Fixes for golint tip

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix lint in 1.4 branch.

@ncdc

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37694)

**Comment by ncdc** [comment]
@wojtek-t looks like golint isn't happy?

**Comment by wojtek-t** [comment]
This is super strange - it passes for me locally in 1.4 branch - I don't understand it.

**Comment by ncdc** [comment]
@wojtek-t last time I checked, we don't pin to a specific golint version, so CI could be running a different copy than you are.

**Comment by ncdc** [comment]
@ixdy @spxtr @eparis @pwittrock @jessfraz is it finally time to reconsider blocking on golint, or at the very least require pinning to a specific revision of it?

**Comment by jessfraz** [comment]
I am going to pin the image to a specific golint version, the issue for tracking is here: https://github.com/kubernetes/kubernetes/issues/37254

**Comment by pwittrock** [comment]
Makes sense to me

**Comment by jessfraz** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/37710 which pins to a version, thanks!

**Pull request closed without merging**
