### PR TITLE
Corrected cassandra example's indent.

### PR DESCRIPTION
**Pull request by k82cn**
No logic changed; just correct java code's indent.

### CODE REVIEW

**Comment by k82** [comment]
ping @amygdala :).

**Comment by amygdala** [comment]
sorry for delay; looking shortly

**Comment by amygdala** [comment]
ok to test @k8s-bot

**Comment by k82** [comment]
The UT failed at `rated-apiserver/app`:

`
FAIL	k8s.io/kubernetes/federation/cmd/federated-apiserver/app	0.296s
`

**Comment by k82** [comment]
Rebase to correct unit test result, ping @amygdala.

**Comment by k82** [comment]
Rebased.

**Comment by amygdala** [comment]
@k8s-bot test this

**Comment by k82** [comment]
@amygdala , the code are rebased, would you help to review it and mark label? thanks :).

**Pull request merged**
