### PR TITLE
add opt-in compression support in apiserver

### PR DESCRIPTION
**Pull request by armstrongli**
add opt-in snappy compression support in Transformer to shrink the data size in storage.

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

this is a feature to do data compression on storage to shrink data size.

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/122799

#### Does this PR introduce a user-facing change?

```release-note
Added a storage compression option to the apiserver
```

### CODE REVIEW

**Comment by armstrongli** [comment]
@sftim , the `release-note` is updated. please help review.

**Comment by sftim** [comment]
Try this:
```diff
-add storage compression option to enable data compression by cluster admins
+Added a storage compression option to the kube-apiserver.
```

**Comment by armstrongli** [comment]
updated with tiny tuning from `kube-apiserver` to `apiserver` as it is a lib finally bumped to kubernetes/apiserver and can be used by other projects or customized apiservers.

**Comment by sftim** [comment]
Try this, then:
```diff
-Added a storage compression option to the apiserver
+Added a storage compression option to the kube-apiserver and to the `apiserver` library code.
```
(Changelogs are Markdown)

**Comment by armstrongli** [comment]
@sftim the release-note is generated by the postsubmit job on pushing a new release. it isn't required on each PR as far as i know. can you help point the files required to change if release-note doesn't work like that?

**Comment by sftim** [comment]
You edit the PR description so that the post-submit can find the changelog text embedded in it. All you need to do is to edit this description for the PR, and automation (plus some manual fettling within SIG Release) does the rest.

**Comment by armstrongli** [comment]
the PR has the `release-note` label added, it means pow service has got the description and reacts for this PR.

**Comment by armstrongli** [comment]
@alexzielenski  , @aramase please help review.

**Comment by alexzielenski** [comment]
@armstrongli This sounds like a change that should be talked about more in the SIG meeting. SIG etcd is likely the best place to take this discussion to get approval from the SIG. 

My own impression is that if you wanted compression for data at-rest in storage, I would've it to be put directly into etcd and just work transparently, rather than apiserver needing to do the compression work.

**Comment by jiahuif** [comment]
+1 For discussion and potentially its own KEP.
Please update here after the discussions. Thank you.

**Comment by aramase** [comment]
This change requires a KEP and needs to be discussed in the SIG API Machinery meeting before an implementation.

This was closed during the SIG Auth triage meeting.

/close

**Pull request closed without merging**
