### PR TITLE
Rename cAdvisor info API to cadvisorApi

### PR DESCRIPTION
**Pull request by vmarmol**

### CODE REVIEW

**Comment by vmarmol** [comment]
Assigning to @vishh as per your request in #5151

**Comment by vmarmol** [comment]
@googlebot but we're pals! we go way back :'(

**Comment by vmarmol** [comment]
@googlebot don't worry I'll try not to take it personal :P

**Comment by vishh** [comment]
LOL... Don't mess with @googlebot ;)
LGTM

**Pull request merged**
