### PR TITLE
Clean up genclient tags for hub types

### PR DESCRIPTION
**Pull request by yue9944882**
/kind cleanup
/cc @liggitt @sttts 

a follow-up of completely externalizing client suites

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
> @k8s-ci-robot k8s-ci-robot added kind/api-change  and removed kind/api-change  labels 27 seconds ago

ok.. you win 😅

**Comment by liggitt** [comment]
/approve

@sttts has lgtm

**Comment by yue9944882** [comment]
/assign @sttts

let's get this in!

**Review by sttts — COMMENTED** [review]
/lgtm

**Pull request merged**
