### PR TITLE
update go.mod for go1.17

### PR DESCRIPTION
**Pull request by riita10069**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

I thought about upgrading my go version to 1.17.

The description in go.mod seems to have changed a bit since 1.17.
https://golang.org/doc/go1.17#go-command

So I run `go mod tidy -go=1.17` for updating go.mod.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
> I thought about upgrading my go version to 1.17.

We're already using go 1.17, updating the go version in go.mod controls what go _language features_ are enabled, not what go version is used.

Are there any compelling language features that should push us to change this?

**Comment by thockin** [comment]
I don't even know where to find a spec for the differences between
versions...

**Comment by riita10069** [comment]
Thank you for your reply.

I read the following NOTE.
https://tip.golang.org/ref/mod#graph-pruning

In go1.16 or earlier, it was not possible to determine the required library and version without looking at the module graph, but in go 1.17, it will be possible, because it will be written in go.mod.

As a result, I thought that it would not have to fetch a large number of go.mods, so it would reduce the time it takes to build 
go.
What do you think?

**Comment by BenTheElder** [comment]
> In go1.16 or earlier, it was not possible to determine the required library and version without looking at the module graph, but in go 1.17, it will be possible, because it will be written in go.mod.
>
> As a result, I thought that it would not have to fetch a large number of go.mods, so it would reduce the time it takes to build
go.
> What do you think?

That sounds interesting but I don't think it applies to this repo at all.

Kubernetes uses vendoring so we don't fetch modules when building at all, we only use modules to describe dependencies for managing vendor. We also use some additional tooling to list all dependencies explicitly and pin them to a specific version in go.mod already (take a look at the comments at the top of go.mod and the scripts it references).

**Comment by riita10069** [comment]
Thank you.I understand these things so close this PR.

**Pull request closed without merging**
