### PR TITLE
PodPriority - Update DropDisabled[Alpha]Fields behaviour 

### PR DESCRIPTION
**Pull request by sbezverk**
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

See for reference issue: #72169

```release-note
None
```
/sig api-machinery
/kind cleanup
/release-notes-none

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm, please squash commits

**Comment by sbezverk** [comment]
@liggitt Done

**Comment by sbezverk** [comment]
@liggitt please lgtm when you have a second

**Comment by sbezverk** [comment]
@liggitt lost lgtm due to rebase

**Comment by liggitt** [comment]
linking PR's that had a test flake because of https://github.com/kubernetes/kubernetes/issues/71696

**Pull request merged**
