### PR TITLE
azure: switch log verbosity for cache refresh logs

### PR DESCRIPTION
**Pull request by aramase**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Changes log levels for cache refresh logs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by sureshpalemoni — APPROVED** [review]

**Review by andyzhangx — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
