### PR TITLE
Fix docstring: Say "flag options" instead of "flag statements"

### PR DESCRIPTION
**Pull request by tnguyen-rh**
[Analytics]()

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by AdoHe** [comment]
There is no need to add newline, otherwise LGTM.

**Comment by tnguyen-rh** [comment]
@AdoHe 
Thanks for the review.  I've removed the extraneous newlines and rebased.

**Comment by tnguyen-rh** [comment]
@ixdy Hi, i don't have a lot of experience to judge "too spammy" so this is not really a complaint, more like a request for your opinion.  Does 4 repetitions (5, if you include the original) count as "too spammy"?

**Comment by ixdy** [comment]
It's too spammy, but I don't have a good way of fixing it at the moment. :\

**Pull request merged**
