### PR TITLE
Format kubelet.go

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mtaufen** [comment]
Is this the result of `gofmt`, or manually formatted? Seems that `gofmt` wants to reverse this change in the verify job.

**Comment by ggaaooppeenngg** [comment]
@mtaufen 

It's gofmt result, my go version is  `go version devel +4a2bec9726 Tue Jun 5 00:43:22 2018 +0000 darwin/amd64`

Is the reason that gofmt in jenkins is old?

**Comment by mtaufen** [comment]
Can you try it with go version 1.10.2? I think this is the current version Kubernetes builds with.
I'd expect someone to re-format the entire repo when we upgrade to a go version with the new formatting behavior, rather than one-off PRs.

**Comment by ggaaooppeenngg** [comment]
There is no change in gofmt(1.10.2), but for latter gofmt, behaviors changed. I am closing this pr, and open an issue https://github.com/kubernetes/kubernetes/issues/65079 for it.

**Pull request closed without merging**
