### PR TITLE
Unexport a symbol in proxier

### LINKED ISSUE #7370: iptables invocations fail if another process is modifying iptables rules
If another process is altering iptables rules at the time k8s attempts to add iptables rules it will fail with a locking error. k8s should use -w and retry after a delay.

Below, an external process (openshift-sdn-node) modifies iptables at roughly the same time and k8s fails without retrying.

```
Apr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -t nat -D POSTROUTING -s 10.1.0.0/16 '!' -d 10.1.0.0/16 -j MASQUERADE
...
Apr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -I INPUT 2 -i lbr0 -m comment --comment 'traffic from docker' -j ACCEPT
Apr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661746    2237 proxier.go:337] Failed to initialize iptables: error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Apr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661912    2237 node.go:245] WARNING: Could not modify iptables.  iptables must be mutable by this process to use services.  Do you have root permissions?
Apr 27 11:40:22 ose3-master.example.com openshift-node[2237]: I0427 11:40:22.147405    2237 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: "kubernetes-ro, router, database, frontend, ruby-example, docker-registry, kubernetes"
```

Related to https://github.com/openshift/origin/issues/1922

### PR DESCRIPTION
**Pull request by thockin**
Fixes #7370

### CODE REVIEW

**Comment by smarterclayton** [comment]
I think we might just want a clean error returned by NewProxier and then we'll periodically retry.  I'll make those changes, sorry for the firedrill.

**Comment by thockin** [comment]
Want I should drop this?

**Comment by smarterclayton** [comment]
Do you think it's cleaner to just exit immediately?

**Comment by thockin** [comment]
yes :)

**Comment by thockin** [comment]
If you agree, ACK.  I'll drop the second commit here - I still want the
first.

**Comment by smarterclayton** [comment]
ACK

----- Original Message -----
> If you agree, ACK.  I'll drop the second commit here - I still want the
> first.
>

**Comment by thockin** [comment]
Edited the subject to just mention unexporting

**Comment by smarterclayton** [comment]
LGTM

**Comment by satnam6502** [comment]
@smarterclayton beat me to it while I was at lunch :-)

**Pull request merged**
