### PR TITLE
fix v1a3 ResourceSliceList metadata field name

### LINKED ISSUE #126659: ResourceSliceList object has `listMeta` field instead of `metadata` field
### What happened?

Listing `v1alpha3.ResourceSlice`s on v1.31.0 returns an object with a `listMeta` field instead of the standard `metadata` field for (list) objects:

```sh
$ curl -kL --cert client.pem --key client.key.pem 'https://127.0.0.1:39987/apis/resource.k8s.io/v1alpha3/resourceslices'

{
  "kind": "ResourceSliceList",
  "apiVersion": "resource.k8s.io/v1alpha3",
  "listMeta": {
    "resourceVersion": "522"
  },
  "items": []
}
```

Listing `v1alpha2.ResourceSlice`s on v1.30.3 behaves correctly:

```sh
$ curl -kL --cert client.pem --key client.key.pem 'https://127.0.0.1:34519/apis/resource.k8s.io/v1alpha2/resourceslices'

{
  "kind": "ResourceSliceList",
  "apiVersion": "resource.k8s.io/v1alpha2",
  "metadata": {
    "resourceVersion": "422"
  },
  "items": []
}
```

This is also propagated to the Swagger spec (which is how I noticed it, since I maintain the Rust bindings for the client API). v1.31.0:

```json
    "io.k8s.api.resource.v1alpha3.ResourceSliceList": {
        "listMeta": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta",
          "description": "Standard list metadata"
        }
```

v1.30.3:

```json
    "io.k8s.api.resource.v1alpha2.ResourceSliceList": {
        "metadata": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta",
          "description": "Standard list metadata"
        }
```

### What did you expect to happen?

As explained above.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy v1.31.0 with `DynamicResourceAllocation` feature gate enabled and runtime config `resource.k8s.io/v1alpha3=true`. With kind, this is:

    ```yaml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    featureGates:
      DynamicResourceAllocation: true
    runtimeConfig:
      'resource.k8s.io/v1alpha3': 'true'
    ```

2. Perform the API server request as in the above curl command in any way you like as long as it lets you see the raw JSON response.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0
```

</details>

### Cloud provider

<details>
kind 0.23.0
</details>

### OS version

<details>

```console
N/A
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by thockin**
This field was incorrectly named "listMeta" and was missed in review.

/cc @johnbelamaric @klueska 

/kind bug
/kind api-change

Fixes #126659

```release-note
The resource/v1alpha3.ResourceSliceList filed which should have been named "metadata" but was instead named "listMeta" is now properly "metadata".
```

### CODE REVIEW

**Review by johnbelamaric — COMMENTED** [review]
/lgtm

**Comment by liggitt** [comment]
Thanks, can you pick to 1.31 as well?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/126761

**Pull request merged**
