### PR TITLE
Add new nginx-1.14-1-copy image for e2e testing.

### PR DESCRIPTION
**Pull request by whypro**
#### What type of PR is this?

/kind flake

/sig testing

#### What this PR does / why we need it:

The e2e testing in PR https://github.com/kubernetes/kubernetes/pull/94833 needs two images that have same hash but different tags. So I add a new image `nginx:1.14-1-copy` based on `nginx:1.14-1` for that purpose.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by whypro** [comment]
@claudiubelu PTAL, Thanks!

**Comment by claudiubelu** [comment]
Hmm, so you basically need the image SHA as different tags.

With how the Image Builder currently works, that's a bit unlikely. We are using the Image Builder / Promoter to automate the image building and promoting process, so we don't have to rely on humans to do it for us.

Recently, we've mirrored a few images from dockerhub in order to avoid the dockerhub ratelimit issue, including the busybox, httpd, nginx images, but we were hitting a 401 Unauthorized issue in the Image Builder when pushing the same SHA to the staging registry. We've ended up having a workaround that generates a new SHA for the images, so the image ``nginx:1.14-1`` has a different SHA ``nginx:1.14-alpine`` we had previously. Even this nginx-copy image you're creating will have a different SHA from ``nginx:1.14-1`` since it will have a different label, so it will not help the test case you're trying to cover.

You can read more about this here:

https://github.com/kubernetes/test-infra/issues/20884
https://github.com/kubernetes/kubernetes/pull/99609

**Comment by claudiubelu** [comment]
So, I've been thinking about this for a bit. What I said previously is still true, this would still not work. However, if you really want 2 identical test images but published as 2 different tags, I think you can actually do that. All you have to do is add the same image SHA [here](https://github.com/kubernetes/k8s.io/blob/290f7ad862949b1194b60d473bc5b0e4ec0e4bc3/k8s.gcr.io/images/k8s-staging-e2e-test-images/images.yaml#L55) as 2 different image tags, and then the Image Promoter will then promote that same image SHA as 2 different tags.

**Comment by claudiubelu** [comment]
> 
> 
> So, I've been thinking about this for a bit. What I said previously is still true, this would still not work. However, if you really want 2 identical test images but published as 2 different tags, I think you can actually do that. All you have to do is add the same image SHA [here](https://github.com/kubernetes/k8s.io/blob/290f7ad862949b1194b60d473bc5b0e4ec0e4bc3/k8s.gcr.io/images/k8s-staging-e2e-test-images/images.yaml#L55) as 2 different image tags, and then the Image Promoter will then promote that same image SHA as 2 different tags.

That doesn't work either, apparently: https://github.com/kubernetes/k8s.io/pull/2351

**Comment by claudiubelu** [comment]
The image ``nginx:1.14-1-copy`` has been pushed (https://github.com/kubernetes/k8s.io/pull/2351), and it has the same sha as the ``nginx:1.14-1`` image:

```
ubuntu@ubuntu:~/run_e2e/kubernetes$ docker pull k8s.gcr.io/e2e-test-images/nginx:1.14-1
1.14-1: Pulling from e2e-test-images/nginx
bdf0201b3a05: Pull complete
3d0a573c81ed: Pull complete
8129faeb2eb6: Pull complete
3dc99f571daf: Pull complete
Digest: sha256:503b7abb89e57383eba61cc8a9cb0b495ea575c516108f7d972a6ff6e1ab3c9b
Status: Downloaded newer image for k8s.gcr.io/e2e-test-images/nginx:1.14-1
k8s.gcr.io/e2e-test-images/nginx:1.14-1
ubuntu@ubuntu:~/run_e2e/kubernetes$ docker pull k8s.gcr.io/e2e-test-images/nginx:1.14-1-copy
1.14-1-copy: Pulling from e2e-test-images/nginx
Digest: sha256:503b7abb89e57383eba61cc8a9cb0b495ea575c516108f7d972a6ff6e1ab3c9b
Status: Downloaded newer image for k8s.gcr.io/e2e-test-images/nginx:1.14-1-copy
k8s.gcr.io/e2e-test-images/nginx:1.14-1-copy
```

We can close this now.

/close

**Pull request closed without merging**
