### PR TITLE
[Code clean] Add method incPosition to reduce useless judgement on Parse.consume

### LINKED ISSUE #102257: The logic in staging/src/k8s.io/apimachinery/pkg/labels/selector.go:831 can be optimize
https://github.com/kubernetes/kubernetes/blob/ebd61572c579476a6537b9002d90c978f24dda4e/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L827-L840

The response is same at line_829 and line_834. The line_834 just inc the position.

So add a method which just inc the position to take place of line_834.

### PR DESCRIPTION
**Pull request by horizonzy**
#### What type of PR is this?
code enhancement.

#### What this PR does / why we need it:
optimize the logic.

#### Which issue(s) this PR fixes:

Fixes #102257

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by horizonzy** [comment]
@MadhavJivrajani Hi, do me a favor to trigger it to test.

**Comment by MadhavJivrajani** [comment]
Sure thing
/ok-to-test

**Comment by horizonzy** [comment]
> Have you seen this as as significant source of allocations and latency in the system? While we appreciate optimizations, we like to focus on ones with significant payoff. Without a clear payoff, this review probably won't be prioritized

Yep, it's not high priority. I just see the code is not most suitable,  so create a method to make it look better.

**Pull request closed without merging**
