### PR TITLE
fixing comments to follow golang style guide

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**:
Modifying some comments to follow the style guide in https://golang.org/doc/effective_go.html#commentary and https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

`NONE`

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
k8s-merge-robot assigns nobody. Let's wait and see.

**Comment by huangjiuyuan** [comment]
@krousey

**Pull request closed without merging**
