### PR TITLE
refactor kubelet long function, extract addAdmitHandler func

### PR DESCRIPTION
**Pull request by oulinbao**
**What this PR does / why we need it**:
refactor long func

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by oulinbao** [comment]
@jhorwit2, could you show me the error reasons? I can't access it. On my local pc, node e2e test is also failed even in master branch. Thanks.

**Comment by jhorwit2** [comment]
/retest

@oulinbao it may be a fluke. I'm going to rerun the tests.

**Comment by oulinbao** [comment]
@jhorwit2 This is still failed, how could I do next?

**Comment by jhorwit2** [comment]
@oulinbao The failures to me seem specific to this PR since I don't see similar failures in other test runs for other PRs. 

@kubernetes/sig-node-pr-reviews PTAL

**Pull request closed without merging**
