### PR TITLE
update notes

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
update notes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jianhuiz — APPROVED** [review]

**Review by mourya007 — COMMENTED** [review]
I think it is a typo fix https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/staging/src/k8s.io/client-go/pkg/apis/clientauthentication/v1beta1/types.go#L40

**Pull request merged**
