### PR TITLE
use ffjson for encode/decode

### PR DESCRIPTION
**Pull request by brendandburns**
@davidopp @wojtek-t

### CODE REVIEW

**Comment by brendandburns** [comment]
Probably only worth reviewing the [second commit](https://github.com/brendandburns/kubernetes/commit/ac3a01209b6992127760a4f5413cd5e97ae0b542)

**Comment by brendandburns** [comment]
@lavalamp too since this is relevant to CSI
@smarterclayton because he's interested...

**Comment by brendandburns** [comment]
Tests are failing... Let me figure out what is going wrong.

**Comment by lavalamp** [comment]
@wojtek-t has a change for uugorji or whatever it is. Let's just wait for that?

**Comment by brendandburns** [comment]
PR in question is:

https://github.com/kubernetes/kubernetes/pull/14031

Let's do a side by side comparison?  I like the fact that ffjson has a built in buffer pool.

**Comment by wojtek-t** [comment]
@brendandburns @lavalamp 
I was running some benchmarks and they show that ugorji is significantly faster than ffjson.
So I'm not sure if it's worth doing this one...

**Comment by wojtek-t** [comment]
@brendandburns - BTW I also tried to use ffjson and there were some problems with it (i.e. there seem to be some incompatibilities between it).
Note, that there were also a bunch of problems with ugorji stuff and I spent some time working with its maintainer to fix it, but it seems that it's now fixed. So it seems we're a bit further with that one.
[The only remaining issue that is blocking that is that go-etcd is using the old version of that which is incompatible with the new version and I have some problems with managing dependencies]. So I just need to update etcd (once we replace go-etcd with that @timothysc is working on it) to use the newer version of the codec and this will be mostly done.

**Comment by brendandburns** [comment]
ok, I'll close this in favor of @wojtek-t 's ugorji PR.

**Pull request closed without merging**
