### PR TITLE
fix log

### PR DESCRIPTION
**Pull request by menghao11**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by menghao11** [comment]
I signed it!

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
Closed and re-opened to see if the CLA issue is fixed...

**Pull request closed without merging**
