### PR TITLE
build kube-env in build-kube-env, not in verify-prereqs

### PR DESCRIPTION
**Pull request by mikedanese**
cc @ihmccreery @zmerlynn 

ENABLE_\* is not respected right now unless verify-prereqs is called first

### CODE REVIEW

**Comment by mikedanese** [comment]
This needs to be cherry picked.

@k8s-bot unit test this pleas

**Comment by ihmccreery** [comment]
What about `helper/coreos/` and `helper/trusty/`?  It seems—to me, not really understanding the state of `cluster/` so well—like it'd be better if this stayed in `util.sh` and just moved to a separate function that was called by `build-kube-env`.

**Comment by mikedanese** [comment]
@ihmccreery fixed PTAL

**Comment by ihmccreery** [comment]
LGTM.

**Comment by mikedanese** [comment]
@k8s-bot test this please

**Comment by mikedanese** [comment]
Test fixin

**Pull request merged**
