### PR TITLE
[WIP] generic scaler scalerfor continued job scale

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**:
checks if job scale endpoint(#58468) fixes generic scaler in kubectl(#58298)

**Release note**:

```release-note
NONE

```

### CODE REVIEW

**Comment by deads2k** [comment]
This looks great. Squash down your commits an fix the vet error.

@pwittrock @kubernetes/sig-cli-maintainers After this we'll have generic scale in `kubectl`!

**Comment by p0lyn0mial** [comment]
I am closing this pull as my intention was to see whether `job scale` endpoint fixes issues I have encountered while working on `generic scaler` for `kubectl`.

**Pull request closed without merging**
