### PR TITLE
azure - Keyvault as KMS

### PR DESCRIPTION
**Pull request by khenidak**
**What this PR does / why we need it**:
Adds azure's KeyVault as KMS provider for kubernetes. 

**Special notes for your reviewer**:
The change adds azure glang's SDK(keyvault) as dependency 

**Notes**
**How to use**:

1. Modify Azure cloud provider file */etc/kubernetes/azure.json* to include 
"clusterKeyVault" : "{KEY-VAULT-NAME}"

2. Create encryption config

```
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - kms:
        cachesize: 100
        configfile: /etc/kubernetes/azureOverride.yaml
        name: azure-keyvault
    - identity: {}
```

3. Provide empty overrides (/etc/kubernetes/azureOverride.yaml)

```
vaultName: ""
keyName: ""
keyVersion: ""
```

4. Modify kube-apiserver startup arguments *add the following parameter, point to encryption config*

```
--experimental-encryption-provider-config=/etc/kubernetes/encryptionConfig.yaml
```

5. Follow instruction [here](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) for the rest. 

**Using default values**
if no overrides provided then: 

1. Cloud provider will use the key vault provided and will assume it has Encrypt/Decrypt permission on said key vault
2. The default key expected is **k8s-secret-key**. If the key is not in the key vault the cloud provider will attempt to create it (and will need Create/Key permission).
3. The cloud provider will always use **latest** version of the key. Users are encouraged to use overrides and use fixed version of the key

**Using non-default values**
User can provide an override values, in this case the cloud provider expects to find the key **and will not attempt to create it**, it also expects to have Encrypt/Decrypt permission

### CODE REVIEW

**Comment by khenidak** [comment]
FYI: @jdumars @brendanburns

**Comment by ericchiang** [comment]
cc @kubernetes/sig-auth-pr-reviews 
cc @kubernetes/sig-api-machinery-pr-reviews 
cc @destijl 

There's been push back on other threads to adding more compiled in KMS providers to kube-apiserver. The GCE and the Vault implementation have been okay-ed to help prove out an external API, but I've been under the impression that future work would focus on enabling external integrations with KMSs.

See:
https://github.com/kubernetes/kubernetes/issues/51965
https://github.com/kubernetes/kubernetes/pull/48574#issuecomment-324713204
https://github.com/kubernetes/community/pull/888#issuecomment-332329545
https://github.com/kubernetes/kubernetes/issues/52916

**Comment by luxas** [comment]
@ericchiang Thanks. Yes, this is _exactly the reason_ I pushed back on the thing in the first place.
Where do we draw the line? What companies do we "favor"? such things.

All of these have to be externalized in the end anyway.
I agreed to do two in-tree providers in order for the SIG to get more experience so a decent "real" API can be created later. Not sure how to deal with this as we said two, not three.

cc @bgrant0607

**Comment by brendandburns** [comment]
Given that it is not currently possible to externalize a KMS, it seems that we have to support adding additional KMS, otherwise this is unfairly favoring one provider over another.

We can not tell people that they can not implement an interface, if we don't have an alternative solution.

If this is controversial, I'm happy to discuss this with SIG api machinery or with the Kubernetes steering committee.  Let me know what people prefer.

@smarterclayton @philips @thockin @bgrant0607

**Comment by luxas** [comment]
> Given that it is not currently possible to externalize a KMS, it seems that we have to support adding additional KMS, otherwise this is unfairly favoring one provider over another.

Well, that's why I didn't want the Google KMS thing to merge (https://github.com/kubernetes/kubernetes/pull/48574#issuecomment-324713204); as we'll end up exactly here :/
History repeating itself as with cloud provider integrations...
We need to remember that this is explicitely stated alpha code though.

cc @deads2k @liggitt

**Comment by brendandburns** [comment]
Yeah @luxas I agree with you, and this is why it is a good topic for a SIG or the steering committee.

**Comment by bgrant0607** [comment]
There are other threads about cloud-provider-specific code. I'll try to catch up and comment.

**Comment by jdumars** [comment]
I think there is a high level of willingness to deprecate in-tree solutions once a viable alternative is in place.  But, as Brendan says, there are real-world use cases for a solution right now.  Having a reasonable workaround in place while the optimal solution is developed doesn't seem out of alignment with the norms of the project. 

Ultimately, this has to be a collective decision at the SIG level, and if not there, then in the steering committee on the general question of "are we blocking all future in-tree work on functionality tied to in-progress, but unreleased extensibility?" This will be a recurring theme, and we need a way to arbitrate the diminution of technical debt with the business/compliance/operability needs of the user base.

**Comment by khenidak** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/51965#issuecomment-339333937

**Comment by dims** [comment]
@jdumars we have to use the same yard stick everywhere - whether it is the cloud providers or the volume drivers or the kms's - it's very hard to take out once things get into the main repo. 

if you have seen my 2 deprecation notices over the last few days, there's about a half dozen more so we are looking at a year for at least one of the "features" (SSH tunnels in kube api server).  

It's hard to get even reasonably sane thing like kubeadm out of k/k. (i tried!)

**Comment by brendandburns** [comment]
@dims, I agree completely, but we should have held the line at not including a GCP provider. (as @luxas tried to do)

It's fine to block the whole project on architecturally correct solutions. It's not ok to block individual providers when other providers are present.

But, of course, this really needs to be a SIG/Steering comittee discussion.

**Comment by khenidak** [comment]
Folks, mean while we are trying to get clarity and pick up https://github.com/kubernetes/kubernetes/issues/51965 as it will unblock the entire community..

**Comment by jdumars** [comment]
@dims (and others) I totally get it.  And, I am a obviously a very strong proponent of continuing down the path of separating things out.  The struggle comes when alternative implementations (if even possible) accrue more technical debt than putting in something that will be deprecated and removed later.  Also, deferring implementation based on incomplete, unfunded, or unplanned dependencies is not a great practice. 

In the realms of regulatory compliance, there's the notion of a compensating control.  It provides an assurance around a procedural exception that ensures the spirit of the intended regulation is being met.  I propose that we consider a solution like that in this case.  Specifically, that as part of this implementation, we equally commit to deprecate it as soon as it is viable to do so.

**Comment by deads2k** [comment]
We need to see a non-cloudprovider KMS plugin go in to gain experience for an external API, so the Vault plugin needs to merge.  Beyond that, I'd say that GCE wedged the door open for cloudproviders and it is hard to say that GCE is special.

@lavalamp haven't seen you in the thread.

**Comment by bgrant0607** [comment]
@deads2k Does the non-cloud-provider plugin mechanism enable out-of-tree plugins?

**Comment by deads2k** [comment]
> @deads2k Does the non-cloud-provider plugin mechanism enable out-of-tree plugins?

Yeah.  It's highlighting problems and shortcomings we have to day with the only kms provider as a cloud provider which access to secondary configuration mechanisms and enablement.  You don't get that experience by allowing a second cloudprovider KMS plugin which has the same backdoors.

**Comment by deads2k** [comment]
> @deads2k Does the non-cloud-provider plugin mechanism enable out-of-tree plugins?
> Yeah. It's highlighting problems and shortcomings we have to day with the only kms provider as a cloud provider which access to secondary configuration mechanisms and enablement. You don't get that experience by allowing a second cloudprovider KMS plugin which has the same backdoors.

Yes in the sense that you won't gain the same experience you need to create an out of tree implementation without it.

**Comment by lavalamp** [comment]
I haven't read this entire thread, but it seems like we had an informal agreement that we were going to make the next one of these to come along build the out-of-tree plugin mechanism...

If we need to take both the GCP cloud provider KMS & vault KMS stuff out to make it fair I'm 100% OK with that! (others may be less happy)

**Comment by lavalamp** [comment]
cc @cheftako

**Comment by deads2k** [comment]
> If we need to take both the GCP cloud provider KMS & vault KMS stuff out to make it fair I'm 100% OK with that! (others may be less happy)

I could live with that.  I could also live with someone finding the commonalities that exist and using that to create an external API.

**Comment by destijl** [comment]
I think what's best for Kubernetes here is to remove the Google KMS integration and block all of the implementations (including Vault) on the new API. I spoke with @sakshamsharma on slack and he's agreed to take on coming up with a PR that is the least disruptive way to remove the Google integration.

Also @kksriram since this affects the Vault PR which is fairly close to merge.

**Comment by khenidak** [comment]
as we are moving to out of tree KMS integration this PR is no longer needed.

**Pull request closed without merging**
