### PR TITLE
Call master-branch e2e-runner.sh from release-1.0 e2e.sh.

### PR DESCRIPTION
**Pull request by spxtr**
ref #18981

### CODE REVIEW

**Comment by spxtr** [comment]
@k8s-bot e2e test this again please

**Comment by spxtr** [comment]
@k8s-bot e2e test this again please

E2E tests are very flaky on 1.0.

**Comment by spxtr** [comment]
@k8s-bot e2e test this again please

**Comment by spxtr** [comment]
```
[Fail] Pod Disks [It] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
[Fail] Services [BeforeEach] should serve multiport endpoints from pods 
[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
```

```
[Fail] Kibana Logging Instances Is Alive [It] should check that the Kibana logging instance is alive 
```

```
[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
[Fail] Cadvisor [It] should be healthy on every node. 
[Fail] Probing container [It] with readiness probe that fails should never be ready and never restart 
[Fail] Services [It] should serve a basic endpoint from pods 
```

Looks like 1.0 tests are extremely flaky on PR Jenkins, which is strange considering these same tests are fine on e2e Jenkins in the release-1.0 job.

**Comment by ixdy** [comment]
LGTM

The release-1.0 job is running the tests in serial, not parallel. We probably are missing a lot of parallel fixes in release-1.0.

@k8s-bot e2e test this

**Comment by spxtr** [comment]
Is it worth switching off parallel for 1.0? It's failing every time.

**Comment by ixdy** [comment]
We could try this, though I don't know if it'll finish within timeout in that case.

**Comment by spxtr** [comment]
Manual merge to watch Jenkins.

**Pull request merged**
