### PR TITLE
Fix nil pointer dereference in metrics value calculator.

### PR DESCRIPTION
**Pull request by humblec**
Backport of# 78222

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Overall, this cherry-pick makes sense to me @humblec .

Could I trouble you to close this PR and create a new pr using the cherry-pick process outlined here? https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

I think that will make things the easiest on the 1.15 branch maintainer, as it gets everything in a standard format.

thanks so much :)

**Comment by humblec** [comment]
@mattjmcnaughton sure :) , closing in favor of  https://github.com/kubernetes/kubernetes/pull/80642

**Pull request closed without merging**
