### PR TITLE
Remove dead codes

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind cleanup
/kind bugfix

**What this PR does / why we need it**:

Remove the unused code

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by jsafrane** [comment]
@cwdsuzhou, please fix the commit message, it does not remove any verbosity, just dead code.

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou, please fix the commit message, it does not remove any verbosity, just dead code.

thanks, done

**Comment by cwdsuzhou** [comment]
ping @jsafrane PTAL

**Comment by jsafrane** [comment]
I still see "Remove verbose error" in the commit message (`git show HEAD` in your work tree)

**Comment by cwdsuzhou** [comment]
> I still see "Remove verbose error" in the commit message (`git show HEAD` in your work tree)

Sorry, my mistake,  I have done now

**Pull request merged**
