### PR TITLE
Update to go1.11.4

### PR DESCRIPTION
**Pull request by ixdy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is basically a rehash of #72035. It turns out that go1.11.3 introduced some regressions, so we need to update to go1.11.4 instead.

This release includes some fixes besides just the regression fix; full details at https://github.com/golang/go/issues?q=milestone%3AGo1.11.4+label%3ACherryPickApproved.

**Which issue(s) this PR fixes**:
x-ref #72032

**Does this PR introduce a user-facing change?**:

```release-note
Update to use go1.11.4.
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @cblecker 

It seems like docker hasn't published a `golang:1.11.4` image yet, so I can't build the cross-build image yet.

**Comment by cblecker** [comment]
/priority critical-urgent
/lgtm
/hold

This looks good, but placing hold so @fejta-bot doesn't go nuts retesting this.

Something is stalled out on the docker side for publishing the new tags: https://github.com/docker-library/golang/issues/255

**Comment by ixdy** [comment]
yep, working on the images now.

**Pull request merged**
