### PR TITLE
Change Topology.NUMANode in device plugin interface to a repeated field

### PR DESCRIPTION
**Pull request by klueska**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind api-change

> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Based on the discussion [here](https://github.com/kubernetes/kubernetes/pull/74423/#discussion_r317580396) we have decided to make this a repeated field so that future device plugins can associate a single device with multiple NUMA nodes if desired.

Since this is being changed before any release with this field added, there is no user-facing change.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by cbf123 — APPROVED** [review]
Agreed, makes sense to allow for future flexibility.

**Comment by liggitt** [comment]
/priority important-soon
/milestone v1.16

important to include this change before releasing the interface

**Comment by klueska** [comment]
Closing, as we have now included the one commit from this PR in https://github.com/kubernetes/kubernetes/pull/80570 to reduce the number of PRs that need to be merged by tide.

**Pull request closed without merging**
