### PR TITLE
Revert "MESOS: Refactor scheduler"

### PR DESCRIPTION
**Pull request by mikedanese**
Reverts kubernetes/kubernetes#16316

cc @bgrant0607 @sttts

### CODE REVIEW

**Comment by mikedanese** [comment]
If #17167 passes CI we can merge that instead but if it doesn't we should revert

**Comment by mikedanese** [comment]
```
➜  kubernetes git:(master) ✗ make test WHAT=contrib/mesos/pkg/scheduler/podtask
hack/test-go.sh contrib/mesos/pkg/scheduler/podtask 
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [1112 10:02:46] Running tests without code coverage
# k8s.io/kubernetes/contrib/mesos/pkg/scheduler/podtask
_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/scheduler/podtask/port_mapping_test.go:193: too many arguments in call to New
FAIL    k8s.io/kubernetes/contrib/mesos/pkg/scheduler/podtask [build failed]
!!! Error in hack/test-go.sh:239
  'return ${rc}' exited with status 2
Call stack:
  1: hack/test-go.sh:239 main(...)
Exiting with status 1
make: *** [test] Error 1
```

**Comment by sttts** [comment]
Taking care of that immediately.

**Comment by mikedanese** [comment]
@sttts please review #17167. If that fixes ci, we won't merge this

**Comment by sttts** [comment]
@mikedanese here is the fix: https://github.com/kubernetes/kubernetes/pull/17169

**Pull request closed without merging**
