### PR TITLE
Fix DsFromManifest() after we switch from extensions/v1beta1 to apps/v1

### PR DESCRIPTION
**Pull request by jiayingz**
in cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml.

**What this PR does / why we need it**:
Fixes broken node e2e jobs caused by https://github.com/kubernetes/kubernetes/pull/64296.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by vishh** [comment]
There is an accidental tar file included in this commit. Please remove it.

Otherwise /lgtm /approve

**Comment by soltysh** [comment]
This PR is not quite right, DaemonSet internals still exists in extensions, you can't update that to apps, which broke these tests. I've fixed those in https://github.com/kubernetes/kubernetes/pull/64404 but it looks like you have a mess in DS tests :/

**Comment by grosskur** [comment]
My pull request (#63997) is failing e2e node tests due to the DaemonSet switch from extensions/v1beta1 to apps/v1. I think we need to cherry-pick this fix into the release-1.9 branch /cc @mbohlool

**Comment by mindprince** [comment]
@grosskur Yeah, here's the 1.9 PR: https://github.com/kubernetes/kubernetes/pull/64342

**Comment by grosskur** [comment]
Great, thanks!

**Pull request merged**
