### PR TITLE
Increase buffer sizes in cacher for watchers interested in all/many o…

### PR DESCRIPTION
**Pull request by wojtek-t**
Should increase throughput of cacher in large clusters.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34725)

### CODE REVIEW

**Comment by ncdc** [comment]
cc @deads2k @liggitt @timothysc

**Comment by timothysc** [comment]
Guys we really need to vet this properly...  Could you please describe the motivations and experiment here?

**Comment by wojtek-t** [comment]
The problem is that if the dispatching function:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L442

is not able to put an event for the watcher into its input channel, the the processing of events of the given type for all watchers hang.

The exact issue I've seen in large clusters is that when you call watch with a given resource version the cacher:
- blocks receiving events
- takes all events since that resourceVersion until now
- passes them as "initEvents" to the dispatcher for that particular watcher
- restores receiving events
- in large clusters with large throughput I've seen len(initEvents) to be up to 10000; processing them with buffers of size 10, can actually block processing events for ~1s

And there are exactly 20 such watchers in the system right now (in the default configuration with all controllers).

This PR:
- increases size of the "result channel" for those watchers that (probably) reduces the amount of context switches
- increases size of "input channel" for those watchers, what enables accepting more incoming events while processing those eventInits until anything will start hanging

**Comment by timothysc** [comment]
awesome, thanks for the description @wojtek-t!

**Pull request merged**
