### PR TITLE
do not evict high priority pods when diskPressure in k8s 1.15

### LINKED ISSUE #83317: Static pods be evicted when diskPressure. Commit c05d506 doesn't seem to work.
**What happened**:

My k8s version is 1.15.
I want my static pods which are not in "kube-system" won't be evicted when diskPressure.
I found that after PR: https://github.com/kubernetes/kubernetes/pull/80491/files ,  static pods should not be evicted when diskPressure.
I won't update to 1.16 temporarily.
So I cherry-picked this commit: c05d5060193221dd5ebcf031d2b2708af5d00c5f to my kubelet.

But when I did some tests, I found that this commit doesn't work when diskPressure.
I think the reason is like info in this comment: https://github.com/kubernetes/kubernetes/issues/73572#issuecomment-470444663

detail:

When diskPressure , the pod sent to `IsCriticalPod` is a mirrorPod.(`pkg/kubelet/eviction/eviction_manager.go#evictPod`).

When a mirrorPod list-watched by kubelet, the `annotation[kubernetes.io/config.source]` is set to be the source that kubelet list-watch the pod from, which is `"api"`. (`pkg/kubelet/config/config.go#updatePodsFunc`)

Because the `annotation[kubernetes.io/config.source]` of  mirrorPod is `"api"`, the func `"pkg/kubelet/types/pod_update.go#IsStaticPod"` returns `false`. 
So static pods will be evicted when diskPressure.

I thought how to fix it.
The func `"pkg/kubelet/types/pod_update.go#IsCriticalPod"` deals with staticPod and mirrorPod in different scene. 
So I changed my kubelet to add the verifying of mirrorPod after the verifying of staticPod.
just like this(My original code is k8s1.15 cherry-pick c05d5060193221dd5ebcf031d2b2708af5d00c5f, so it looks strange.):
```go
func IsCriticalPod(pod *v1.Pod) bool {
	if IsStaticPod(pod) {
		return true
	}
	if IsMirrorPod(pod) {
		return true
	}
	if utilfeature.DefaultFeatureGate.Enabled(features.PodPriority) {
		if pod.Spec.Priority != nil && IsCriticalPodBasedOnPriority(*pod.Spec.Priority) {
			return true
		}
	}
	if utilfeature.DefaultFeatureGate.Enabled(features.ExperimentalCriticalPodAnnotation) {
		if IsCritical(pod.Namespace, pod.Annotations) {
			return true
		}
	}
	return false
}
```

After I changed my code to this, static pod didn't be evicted when diskPressure.
So I think this is the reason. And I think this is a Bug.

Maybe I will set `pod.Spec.Priority` to my static pods to prevent eviction temporarily, and I also hope this bug will be fixed in a good way.

**What you expected to happen**:
Static pods won't be evicted when diskPressure.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a static pod on a node. The pod is not set `pod.Spec.Priority` or `pod.Spec.PriorityClassName`. 
2. Let the node under diskPressure (using `fallocate -l 104G file1`).

Then the static pod will be evicted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): My kubelet is k8s1.15  cherry-pick c05d5060193221dd5ebcf031d2b2708af5d00c5f.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by andy-wolf168**
What type of PR is this?
/kind bug

What this PR does / why we need it:
As #83317 reported, static pod would be evicted when diskPressure arises.

This PR adds check for mirror pod for criticality.

Which issue(s) this PR fixes:
Fixes #83317

NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Hi @andy-wolf168 !

It looks like this cherry-pick got created in a bit of an unorthodox way - could I trouble you to close this diff and recreate it following the instructions here? https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

Doing so will make it easier for reviewers to determine the exact changes you're proposing cherry-picking. Thanks! Let me know if you have any questions :)

**Comment by feiskyer** [comment]
@andy-wolf168 why so many commits are introduced? could you only cherry-pick the required commit?

**Comment by tpepper** [comment]
Based on https://github.com/kubernetes/kubernetes/pull/87812 now being open I'm going to close this one.

**Pull request closed without merging**
