### PR TITLE
test images: Fixes Windows httpd images

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind failing-test

/sig windows
/sig testing

/priority important-soon

#### What this PR does / why we need it:

A 32-bit php was included in the images, instead of the 64-bit one. The base image
is nanoserver-based, which does not support 32-bit apps. Because of this, httpd
fails to start.

Additionally, we've previously removed the busybox-helper dependency, but was
left in in the httpd images. This removes the dependency from the httpd images.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Currently, the Windows test jobs are using the images published in ``k8s.gcr.io/e2e-test-images`` registry, and tests are failing because of the httpd images: https://testgrid.k8s.io/sig-windows-releases#aks-engine-azure-windows-master-containerd

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@claudiubelu please ping me when the others have reviewed this. thanks!

**Comment by chewong** [comment]
Let's make sure we run pull-kubernetes-e2e-aks-engine-azure-windows and pull-kubernetes-e2e-aks-engine-windows-contianerd when we modify `test/utils/image/manifest.go`

**Comment by claudiubelu** [comment]
> 
> 
> Let's make sure we run pull-kubernetes-e2e-aks-engine-azure-windows and pull-kubernetes-e2e-aks-engine-windows-contianerd when we modify `test/utils/image/manifest.go`

Sure, sounds good, but we'd still have to merge this first. :)

After we merge this, I'll update https://github.com/kubernetes/kubernetes/pull/87607 to try out the new httpd image and we'll run the windows-containerd job as well. If it passes, it's safe to promote.

**Review by chewong — COMMENTED** [review]
/lgtm
manually verified the following test cases with the updated httpd images:

```
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should have a working scale subresource [Conformance]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance]
```

**Comment by dims** [comment]
@chewong thanks for verifying locally

/approve
/lgtm

**Pull request merged**
