### PR TITLE
Fix typo cgroupDriver -> cgroup-driver

### PR DESCRIPTION
**Pull request by wnxn**
Signed-off-by: Xin Wang <wileywang@yunify.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix a typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @wnxn 
/ok-to-test
/lgtm
/priority backlog

**Review by neolit123 — APPROVED** [review]
thanks @wnxn 
/approve

**Pull request merged**
