### PR TITLE
federation  core client with version

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
federation  core change corev1,Replace the deprecated clientSet.Core() with clientSet.CoreV1().
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49538 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
@jianglingxia  Good catch, sorry for missing these.

**Comment by m1093782566** [comment]
good catch!

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

The tests wont pass unless you update the autogenerated client as well.

Can you add more context on why are you changing this?
Are you changing only the federation clientset? Only Core? Why not others?

cc @caesarxuchao

**Comment by caesarxuchao** [comment]
I think @supereagle has other PRs to change other packages and clients other than `Core`. I think the overall direction is correct, it's better to call out the version explicitly.

**Comment by jianglingxia** [comment]
I have updated the autogenerated client,As I saw @supereagle  had modified the CMD、plugin、test section, so I directly modified federation section and avoid duplication!thanks

**Pull request closed without merging**
