### PR TITLE
MESOS: Add mesos/docker CI scripts

### PR DESCRIPTION
**Pull request by karlkfi**
Resolves https://github.com/mesosphere/kubernetes-mesos/issues/633

### CODE REVIEW

**Comment by karlkfi** [comment]
I made copies of our CI builds to test this PR. 
Once merged, the old CI builds will be updated to use the new steps to preserve the test history/statistics.

Build Release: https://teamcity.mesosphere.io/viewLog.html?buildId=78235&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_1BuildReleaseNew&guest=1
Unit Tests: https://teamcity.mesosphere.io/viewLog.html?buildId=78245&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_2UnitTestsDev&guest=1
Integration Tests: https://teamcity.mesosphere.io/viewLog.html?buildId=78256&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_3IntegrationTestsNew&guest=1
Smoke Tests: https://teamcity.mesosphere.io/viewLog.html?buildId=78185&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_4SmokeTestsNew&guest=1
Conformance Tests: https://teamcity.mesosphere.io/viewLog.html?buildId=78258&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_5ConformanceTestsNew&guest=1
E2E Tests: https://teamcity.mesosphere.io/viewLog.html?buildId=78268&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_6e2eTests&guest=1

Note: `./build/release.sh` is broken on master:head. So that test wont pass till that's fixed.

**Comment by sttts** [comment]
While I really like to have those scripts under version control, I don't like to have them here in the k8s repository so much, especially run-with-cluster.sh. When something breaks with teamcity and we have to quickly do some workaround in those scripts, we are doomed because our change must go into each pending PR and we have to force push onto master.

In short: I would very much prefer to have a mesosphere/kubernetes-ci repository and put those scripts there. Having CI scripts in the main repo is a bad idea.

**Comment by karlkfi** [comment]
We have permission to self-merge anything under the contrib/mesos dir without Google sign-off. As long as these scripts don't affect any non-mesos builds or test processes I don't think it will be a problem to also bypass the merge bot in case of a broken CI. Google has done that several times for their [Jenkins scripts](https://github.com/kubernetes/kubernetes/tree/master/hack/jenkins) that impact a lot more people.

In order to move towards true testing federation and blocking PRs with our CI failures we need our CI scripts publicly available, easily accessible, and reproducible by all PR submitters.

**Comment by sttts** [comment]
Commit permissions does not change the PR-in-flight problem. We cannot reach them.

**Comment by sttts** [comment]
What is the advantage of having CI scripts here instead of a separate k8s-ci repo?

**Comment by sttts** [comment]
Trying to be clear about my concerns which I would like to have resolved before merging:

Use Case: 
- CI is broken because of some external change (a new docker version, some python dependency, a changed kernel on the teamcity hosts)
- When I as Teamcity test engineer notice this that all PRs are red in smoke tests, I fix the CI scripts to work around the problem
- Now developer A changes his PR and by this triggers another smoke-test run on teamcity
- I as Teamcity test engineer want that the new smoke-test of developer A is green again. I do not want that I have to tell him (I don't even know developer A) that he has to fix something for the CI to work, e.g. rebasing.

**Comment by karlkfi** [comment]
Ok, to document our offline discussion:

There's a simple workaround to the above (hopefully exceptional) use case, which is to prepend a CI build step (not in the scripts here) that can checkout and use `contrib/mesos/ci` scripts from another repo/branch. This would only be use if we need to fix something immediately and have it apply to all PRs, without waiting for them to rebase.

The long term plan, tho, is to run tests against the PR merge branches, but that will require some more complicated CI work to avoid triggering PR tests every time a master commit is made.

**Comment by sttts** [comment]
:+1:

**Comment by karlkfi** [comment]
I've update all the builds in TeamCity to have the new "Override CI Scripts" build step. They are all defaulting (for now) to use the scripts from this branch. Once this PR is merged, after a sufficient amount of time that most PRs can be expected to have been merge, the defaults can be set to the empty string to disable the override.

**Comment by sttts** [comment]
lgtm

**Comment by sttts** [comment]
@karlkfi Don't delete the branch because it's the override in the tests. Nearly did that a second ago.

**Comment by karlkfi** [comment]
Yeah, I'm going to update the tests now to use master ci scripts.

**Comment by sttts** [comment]
@karlkfi Was thinking about the idea to compare the last change in contrib/mesos/ci for master and the given PR in test. We could then checkout/keep whatever is newer. Then we can rid of the manual override.

**Comment by karlkfi** [comment]
Smoke tests are set to override with ci scripts from kubernetes/kubernetes:master. All others are only triggering automatically on master, so their override is disabled.

**Pull request merged**
