### PR TITLE
[WIP]add priority field for PodSecurityPolicy

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

fix TODO(liggitt): add priority field to allow admins to bucket differently

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
add priority field for PodSecurityPolicy
```

### CODE REVIEW

**Comment by wackxu** [comment]
@liggitt We need add a configuration to allow user to configure the sort type for psp, one is by `name`, the other is by `priority`, is it  reasonable?

**Comment by liggitt** [comment]
> We need add a configuration to allow user to configure the sort type for psp, one is by name, the other is by priority, is it reasonable?

Before adding this, we need to resolve questions about priority in particular namespaces, and whether a global priority like this is what we want

**Comment by php-coder** [comment]
> we need to resolve questions about priority in particular namespaces, and whether a global priority like this is what we want

Hm... sounds like that it could take years :-| Maybe we can start from alpha annotation with priority on PSP? No obligations, fully optional, and less code to add.

Opinions? Objections?

CC @kubernetes/sig-auth-api-reviews

**Comment by liggitt** [comment]
> Maybe we can start from alpha annotation with priority on PSP? No obligations, fully optional, and less code to add.

No, alpha annotations as an initial step for a future field don't work well. 

With the preference for non-mutating PSPs, it's not clear that we still need priority to the same degree.

**Comment by tallclair** [comment]
FWIW, I would still like to consider separating defaulting from validation in PSPs. There are all sorts of problems with defaulting, and it's actually a bigger issue than just PSP. If we don't have defaults, there's no need for priority. I don't have a proposal at this time, but I'd like to follow up on it (or if anyone else is interested go for it :)

**Comment by php-coder** [comment]
> If we don't have defaults, there's no need for priority.

I'd expect that PodPreset will set defaults. Is it reasonable?

**Comment by dims** [comment]
/close

please reopen if necessary

**Pull request closed without merging**
