### PR TITLE
Combine creating a volume and applying tags in one operation

### PR DESCRIPTION
**Pull request by renan**
**What this PR does / why we need it**:

The previous version forced us to create AWS IAM Policies that are too
permissive when dealing with volumes. That's because:

1. Volumes were created without tags that identifies the new resource as
managed by the cluster. So technically the resourse, at creation time,
is not owned by the cluster.

2. Tags were added to the volume making the resource now managed by the
cluster. The problem being that it could make ANY volume as managed by the
cluster. Thus allowing resources that aren't really part of the cluster,
or part of no cluster at all, to become a resource managed by the cluster.

By combining the operations we can both make the code simpler, since we
don't need to deal with deleting a volume in case we can't apply tags to
it, plus the security model gets a nice improvement.

The IAM policy declaration can go from:
```
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateVolume"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:volume/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateTags"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:volume/*"
      ],
      "Condition": {
        "StringEquals": { "aws:RequestTag/kubernetes.io/cluster/$CLUSTERID": "owned" }
      }
    },
```

to:
```
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateVolume"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:volume/*"
      ],
      "Condition": {
        "StringEquals": { "aws:RequestTag/kubernetes.io/cluster/$CLUSTERID": "owned" }
      }
    },
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by renan** [comment]
Is there anything else I can do for this PR?

**Comment by justinsb** [comment]
This is wonderful, thank you @renan and sorry for the delay

/approve
/lgtm

**Comment by renan** [comment]
Hey @justinsb. No worries, I just came back from vacation so I was checking my open PRs. When running tests with a rebase against master they were falling because of some variable and syntax changes, hence I had to rebase which made everything be green again. I think this is ready for a final check and /lgtm :)

**Comment by shubheksha** [comment]
@justinsb, could you slap another lgtm on this as it was removed?

**Comment by justinsb** [comment]
Sorry for delay!

/lgtm

**Comment by justinsb** [comment]
`https://gcr.io/v2/: net/http: TLS handshake timeout` => flake

/retest

**Comment by bertinatto** [comment]
@justinsb, @gnufied:

Calling `c.tagging.createTag` had the (interesting) side-effect of allowing the volume to be `available` by the time `CreateDisk` returned.

Currently, `CreateDisk` returns while the volume status in AWS is `creating`, so k8s tries to attach the volume and get an error in the first few tries:

```
Events:
  Type     Reason                  Age                From                                  Message
  ----     ------                  ----               ----                                  -------
  Warning  FailedScheduling        19s (x6 over 28s)  default-scheduler                     pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               19s                default-scheduler                     Successfully assigned default/app to ip-172-18-0-74.ec2.internal
  Warning  FailedAttachVolume      15s (x4 over 19s)  attachdetach-controller               AttachVolume.Attach failed for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948" : "Error attaching EBS volume \"vol-01cce92492ab6d0b0\"" to instance "i-0fcdf055a3d119b1b" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  7s                 attachdetach-controller               AttachVolume.Attach succeeded for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948"
  Normal   Pulling                 1s                 kubelet, ip-172-18-0-74.ec2.internal  pulling image "centos"
```

It seems like we have 3 options:

1. Wait for the volume status to be `available` before `CreateDisk` returns.
2. Wait in `AttachDisk` instead.
3. Allow k8s to try and fail until  it succeeds (current implementation).

What do you think should be the right approach?

**Comment by renan** [comment]
@bertinatto Hmmm. I am running on v1.11.2 and this behavior (option number 3) you describe is also present there.

**Pull request merged**
