### PR TITLE
fix print object should be updated error

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
	Print object should be updated.
　　After this patch, it goes the same as create.go
https://github.com/kubernetes/kubernetes/blob/025439988428d2b78342549419706639cd6e52a6/pkg/kubectl/cmd/create.go#L346
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@soltysh PTAL

**Review by soltysh — APPROVED** [review]
/lgtm
/approve no-issue

**Comment by soltysh** [comment]
@WanLinghao thanks for noticing it!

**Pull request merged**
