### PR TITLE
enhanced the docker build documentation for readability and clarity

### PR DESCRIPTION
**Pull request by iamyaash**
#### What type of PR is this?
kind documentation

#### What this PR does / why we need it:
To enhance the documentation for building Kubernetes in Docker Environment.

#### Which issue(s) this PR fixes:

Fixes #
This update introduces an initial step for cloning the repository and navigating to the root directory. Additionally, the **Overview** section has been revised for better clarity and understanding.

#### Does this PR introduce a user-facing change?

```release-note
This change improves documentation clarity, making it more understandable for new users and contributors.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/remove-area kubeadm
/remove-sig cluster-lifecycle

**Pull request merged**
