### PR TITLE
Automated cherry pick of #28428

### PR DESCRIPTION
**Pull request by fabioy**
Cherry pick of #28428 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30889)

### CODE REVIEW

**Comment by fabioy** [comment]
@justinsb Let me know if you'd still like this to be merged (and help me resolve the CLA check). Thanks.

**Comment by erictune** [comment]
ok to test

**Comment by fabioy** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
