### PR TITLE
should return err when generate Patch error

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
should return err when `generatePatch` occur error

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
It is duplicate of https://github.com/kubernetes/kubernetes/pull/55235

**Comment by stewart-yu** [comment]
cc @lavalamp  cc @smarterclayton

**Comment by stewart-yu** [comment]
Kindly ping @smarterclayton @resouer , not sure, i think this pr need your review

**Comment by liggitt** [comment]
/assign @dchen1107 
for approval

**Comment by stewart-yu** [comment]
@brendandburns @smarterclayton PTAL

**Comment by nikhita** [comment]
/assign @lavalamp 
for approval

**Comment by lavalamp** [comment]
If this is worth fixing, it's worth testing. Please add a test.

And someone on the node team should probably review.

**Comment by yujuhong** [comment]
The fix looks good.

@stewart-yu could you add a unit test as @lavalamp mentioned? Thanks!

**Comment by stewart-yu** [comment]
@yujuhong Sure, will fix ASAP. And thanks all!

**Comment by hzxuzhonghu** [comment]
It's hard to make below function return error,  so ut is not easy to mock.
```
	generatePatch := func(condition v1.NodeCondition) ([]byte, error) {
		raw, err := json.Marshal(&[]v1.NodeCondition{condition})
		if err != nil {
			return nil, err
		}
		return []byte(fmt.Sprintf(`{"status":{"conditions":%s}}`, raw)), nil
	}
```

**Pull request closed without merging**
