### PR TITLE
test: use newer test images for better s390x coverage

### PR DESCRIPTION
**Pull request by yselkowitz**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

﻿This uses the new image versions with s390x enabled via https://github.com/kubernetes/kubernetes/pull/102785 so that the tests which depend thereon will pass on s390x.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @mkumatag

### CODE REVIEW

**Comment by yselkowitz** [comment]
@mkumatag what is missing to get the new versions from #102785 built and pushed, so that we can proceed with this?

**Comment by mkumatag** [comment]
> @mkumatag what is missing to get the new versions from #102785 built and pushed, so that we can proceed with this?

I see some post-merge failure for one of the job, anyways lemme trigger the tests and see how it goes

/ok-to-test

**Comment by yselkowitz** [comment]
> we need to bump the images here as well - https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-e2e-test-images/images.yaml

OK, if you can get the post-merge job to run again to build node-perf/npb-is, then I can post the PR for these and the glusterdynamic-provision promotions.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
