### PR TITLE
add test for set selector

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by zhangxiaoyu-zidif — APPROVED** [review]

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-bazel test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-bazel test this

**Comment by zjj2wry** [comment]
@fabianofranz can you help me review this? think you

**Comment by fabianofranz** [comment]
Thanks @zjj2wry!
/lgtm
/approve

**Pull request merged**
