### PR TITLE
kube-proxy config update

### PR DESCRIPTION
**Pull request by kundan2707**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Change in kube-proxy config documentation
#### Which issue(s) this PR fixes:

Fixes # 
https://github.com/kubernetes/website/issues/44529

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kundan2707** [comment]
@derekwaynecarr @roycaihw can you please have a look?

**Comment by danwinship** [comment]
lgtm but I can't approve either

**Comment by aojea** [comment]
> lgtm but I can't approve either

sudo @thockin

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
