### PR TITLE
Automated cherry pick of #112067: client-go: make retry in Request thread safe

### LINKED ISSUE #109155: client-go: the retry logic in rest.Request should be thread safe
### What happened?

the newly refactored retry logic introduced in 1.22 by https://github.com/kubernetes/kubernetes/pull/102217 broke the thread safety of `*Request`. According to Clayton, it's not a release blocker for 1.24. 
So the goal is to fix it in 1.25 and then back port all the way to 1.22.

Please note that there are other members (not related to retry logic) of `Request` that are not thread safe depending on how different methods of a `Request` object is used from multiple go routines.

https://github.com/kubernetes/kubernetes/pull/102217/files#r837633535

Also, the comments on some of these methods and sections for retry logic can be improved:
- For instance, we may want to rename `IsErrorRetryable` to `IsHttpErrRetryable` and `checkWait` to `isServerIndicatedRetry`. 
That would have helped bring this back into mental cache faster and possibly help some future refactorer.

### What did you expect to happen?

Maintain thread safety of `*Request`

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #112067 on release-1.22.

Fixes #109155

#112067: client-go: make retry in Request thread safe

1.22 end of support is approaching soon:
- cherry-pick for 1.23 https://github.com/kubernetes/kubernetes/pull/112067 needs to be reviewed and merged
- and then we can merge this PR before end of 1.22 support

(I opened in advance since the end of support is approaching soon)

```release-note
NONE
```

/sig api-machinery
/kind bug

### CODE REVIEW

**Comment by tkashem** [comment]
/hold

we need to wait until 1.23 PR https://github.com/kubernetes/kubernetes/pull/112067 is reviewed and merged.

Our window of 1.22 end of support is approaching soon, i would love to get it in before that.

**Comment by wojtek-t** [comment]
/lgtm
/approve
/hold cancel

@kubernetes/release-managers - for cherrypick approval

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
