### PR TITLE
Revert changes to the flb-exporter hash value

### PR DESCRIPTION
**Pull request by liurupeng**
#### What type of PR is this?
/kind maintenance

#### What this PR does / why we need it:
Revert changes to the flb-exporter hash value

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
No
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liurupeng** [comment]
@ibabou

**Review by ibabou — APPROVED** [review]

**Pull request merged**
