### PR TITLE
Add cast checks to controllers to prevent nil panics

### LINKED ISSUE #18041: Nil panic in binder controller when passed DeletedFinalStateUnknown
Nil panic in binder controller in Delete handler func.   Requires checks when casting obj to PV.

```
E1121 22:51:15.085506   11954 util.go:82] Recovered from panic: &runtime.TypeAssertionError{interfaceString:"", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*api.PersistentVolume", missingMetho
d:""} (interface conversion: interface is cache.DeletedFinalStateUnknown, not *api.PersistentVolume)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:76
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:64
/usr/lib/golang/src/runtime/asm_amd64.s:402
/usr/lib/golang/src/runtime/panic.go:387
/usr/lib/golang/src/runtime/iface.go:225
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller.go:125
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller.go:72
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:182
<autogenerated>:23
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:252
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:126
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:125
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:126
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/lib/golang/src/runtime/asm_amd64.s:2232
```

### PR DESCRIPTION
**Pull request by markturansky**
Resolves #18041

@pmorie PTAL? This PR is just cast checking in all handler methods in 2 controllers..

### CODE REVIEW

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by pmorie** [comment]
@markturansky Add a unit test?

**Comment by markturansky** [comment]
@pmorie unit test added.  I also implemented @liggitt's suggestion in the downstream patch (https://github.com/openshift/origin/pull/6170)

**Comment by markturansky** [comment]
@k8s-bot test this

**Comment by markturansky** [comment]
@k8s-bot test this

hoping for that non-flaky e2e test run.

**Comment by markturansky** [comment]
@k8s-bot test this

no flake this time, pls

**Comment by markturansky** [comment]
The flakes are strong this this one.

```
FAIL!
Get rc {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      nginx-deployment-fnbwu:
(B
1058 ./hack/test-cmd.sh
(B
!!! Error in ./hack/test-cmd.sh:50
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:50 runTests(...)
  2: ./hack/test-cmd.sh:1270 main(...)
```

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by markturansky** [comment]
@pmorie all green this time.

**Comment by markturansky** [comment]
@pmorie had to rebase, so lost the lgtm tag.  Please re-add?

**Pull request merged**
