### PR TITLE
Bigger scarier

### PR DESCRIPTION
**Pull request by thockin**
Proposed: make the unversioned warnings EVEN MORE noticeable.

### CODE REVIEW

**Comment by erictune** [comment]
LGTM.

**Comment by thockin** [comment]
Someone still has to tag it OK to merge

**Comment by erictune** [comment]
@thockin needs rebase.

**Comment by thockin** [comment]
rebased and new docs generated

**Comment by thockin** [comment]
Every new doc that goes in demands a rebase of this, followed by a 4 hour shippable run.  I plead for mercy.

**Pull request merged**
