### PR TITLE
Typo in changelog 1.11

### PR DESCRIPTION
**Pull request by etiennecoutaud**
There is no small PR 😄 !

### CODE REVIEW

**Review by idealhack — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
> There is no small PR!

Yes!! :muscle: :tada: 

Thanks for the PR, @etiennecoutaud! 

cc @nickchase

**Comment by yastij** [comment]
/ cc @nickchase can you approve ?

**Comment by yastij** [comment]
/ cc @nickchase 

can you PTAL when you have some bandwidth ?

**Comment by yastij** [comment]
/cc @nickchase 

can you PTAL when you have some bandwidth ?

**Comment by nikhita** [comment]
/assign @wojtek-t 
for approval (quick one!)

**Pull request merged**
