### PR TITLE
Don't allow --csr-only for CA certs or all

### PR DESCRIPTION
**Pull request by liztio**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:

Having a CSR doesn't make sense for CAs. Nor does it make sense to "generate all" for CSRs: this will end up failing for CA certificates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@liztio looks great!
After #71069 merges we should make sure CSR LocalFlags got removed from the new "all" phase  
Probably test on `baseName:      ""`  should became `baseName:      "all"` too

**Review by neolit123 — APPROVED** [review]

**Pull request merged**
