### PR TITLE
use strings.Cut in go1.18

### PR DESCRIPTION
**Pull request by Abirdcfly**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
like golang/go has already done, kubernetes also should use cut function to let the code raise the level of abstraction significantly. 

golang/go commit : https://github.com/golang/go/commit/4d8db00641cc9ff4f44de7df9b8c4f4a4f9416ee 

golang/go issue: https://github.com/golang/go/issues/46336
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
The code should just be simplified without changing the original meaning.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
cc @dims

### CODE REVIEW

**Comment by aojea** [comment]
I suggest to hold on golang 1.18 specifics for 1.24 , @dims  has sent an email about generics to the mailing list, but maybe we should make extensive to this too

**Comment by dims** [comment]
yes, please don't do things specific to go1.18 until 1.25 is open

**Comment by Abirdcfly** [comment]
Not as complicated as golang generics, the `Cut` function just simplifies the expression and should have no other impact on the code. (The test failed may because #107377 ,The test will still fail even if it is a blank commit，see https://github.com/kubernetes/kubernetes/pull/92316#issuecomment-1079639183).

if we put the use of the cut function in version 1.25, should I turn off this pr or just add a milestone or just leave it as it is ？@dims

**Comment by lavalamp** [comment]
It is actually not that easy to verify that none of these change behavior. I recommend doing only a few at a time such that you only need one approver for a PR

**Pull request closed without merging**
