### PR TITLE
Automated cherry pick of #107970: Make JSON schema round tripping test more strict

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #107970 on release-1.23.

#107970: Make JSON schema round tripping test more strict

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix OpenAPI serialization of the x-kubernetes-validations field
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
