### PR TITLE
diff all of pkg/ when verifying swagerspec instead of just pkg/api/

### LINKED ISSUE #15245: ./hack/verify-generated-swagger-docs.sh doesn't verify changes to experimental API
Clean master when swagger is not up to date
```
➜  kubernetes git:(master) git status
# On branch master
nothing to commit, working directory clean
```
I run it and it succeds:
```
➜  kubernetes git:(master) ./hack/verify-generated-swagger-docs.sh 
+++ [1007 10:40:30] Building go targets for linux/amd64:
    cmd/genswaggertypedocs
+++ [1007 10:40:30] Placing binaries
Generating swagger type docs for unversioned
Generating swagger type docs for v1
Generating swagger type docs for experimental/v1alpha1
+++ [1007 10:40:32] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [1007 10:40:39] Placing binaries
etcd -data-dir /tmp/tmp.APJGUcnQsd --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null
Waiting for etcd to come up.
+++ [1007 10:40:40] On try 1, etcd: : 
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [1007 10:40:41] Starting kube-apiserver
+++ [1007 10:40:42] On try 2, apiserver: : ok
+++ [1007 10:40:42] Updating 
    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/after-build/../../api/swagger-spec
+++ [1007 10:40:42] SUCCESS
+++ [1007 10:40:42] Clean up complete
diffing /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/pkg/api against freshly generated swagger type documentation
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/pkg/api up to date.
```
And the swagger spec is modified
```
➜  kubernetes git:(master) ✗ git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   pkg/apis/experimental/v1alpha1/types_swagger_doc_generated.go
#
no changes added to commit (use "git add" and/or "git commit -a")
```
@nikhiljindal @erictune

### PR DESCRIPTION
**Pull request by mikedanese**
we are doing this to include experimental apis in pkg/apis/

Fixes #15245

### CODE REVIEW

**Comment by mikedanese** [comment]
Shippable break is due to #15242

**Comment by nikhiljindal** [comment]
I would add that "we are doing this to include experimental apis in pkg/apis/" to the description.

LGTM, thanks!

**Comment by nikhiljindal** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Thanks for fixing this!

**Comment by mikedanese** [comment]
I think this is causing weird stuff to happen in precommit checks for some people.

**Pull request merged**
