### PR TITLE
pkg/kubelet: Add initial node info to cache

### LINKED ISSUE #26590: Unable to get Pod IP from downward API when kubelet cannot contact API server
When a kubelet is not in standalone mode, and attempts to start a static pod with host networking, and the kubelet is unable to contact an API server, it is unable to get the host IP from the node information. Essentially, in `Kubelet.GetNode` it will return `kl.initialNodeStatus` if the kubelet is in standalone mode, if not it attempts to get that information from the `CachedNodeInfo`, which it appears is filled via API server watches. If the kubelet cannot contact the API server, that cache is never filled, so the kubelet cannot return node info, meaning `podStatus.IP` is never properly filled out.

### PR DESCRIPTION
**Pull request by derekparker**
Add initial node information to nodeInfo cache when registering with the
apiserver. This allows the kubelet to obtain node information in the
future, even if it is unable to contact the API server.

Fixes #26590

### CODE REVIEW

**Comment by derekparker** [comment]
Can I get a look at this, please? cc @dchen1107 @vishh @mikedanese

**Comment by vishh** [comment]
What is the use case?

**Comment by derekparker** [comment]
@vishh our (coreos) personal use case is that, due to lack of kubelet checkpointing, we're working on a (temporary solution) "user-space" checkpointing system to checkpoint the apiserver pod manifest in a self-hosted cluster. This is so that if the system ever reboots/crashes we have a "checkpointed" apiserver manifest that we expose as a static manifest on disk that the kubelet can pick up and run. That static manifest makes use of the downward API for the IP address. When the pod is using host networking, the kubelet looks in the node store for the IP. That store is filled from the API server exclusively. In that scenario, there is no API server for the kubelet to talk to to get this information, so the value is the empty string.

The information should be available regardless of if the node can reach the API server. It is local information, after all, so we shouldn't have to rely on contacting an API server to retrieve it. In this patch, I simply pre-fill the cache store with the node information.

**Comment by vishh** [comment]
@derekparker https://github.com/kubernetes/kubernetes/pull/27107 does something similar. Does that satisfy your use case?

**Comment by aaronlevy** [comment]
@derekparker is out of office this week

@vishh I tested https://github.com/kubernetes/kubernetes/pull/27303 and it doesn't resolve this issue.

Repro is adding a simple api pod manifest with `hostNetwork: true` to a static-pod dir, then starting a kubelet which can't contact an api-server. Example pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  hostNetwork: true
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "$(MY_POD_IP)" ]
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  restartPolicy: Never
```

**Comment by aaronlevy** [comment]
Fwiw, I opened an alternative PR here: https://github.com/kubernetes/kubernetes/pull/27508

**Comment by vishh** [comment]
@derekparker @aaronlevy Can we close this PR in favor of #27508 ?

**Comment by derekparker** [comment]
@vishh I'm fine with that.

**Pull request closed without merging**
