### PR TITLE
Fix external-lb-source-ip-preservation.md

### LINKED ISSUE #32313: external-lb-source-ip-preservation.md breaks kubernetes-verify-master
Introduced by 30e7c055d42fe4d6632632f908b7d46bb1e350a7

```
+++ [0908 11:59:42] Building go targets for linux/amd64:
    cmd/mungedocs
/go/src/k8s.io/kubernetes/docs/proposals/external-lb-source-ip-preservation.md
----
unversioned-warning:
not printing failed chunk: too many lines
contents were modified

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/docs/ is out of date. Please run hack/update-munge-docs.sh
```

### PR DESCRIPTION
**Pull request by dims**
Fix build break

Fixes #32313

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32314)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-oncall can you please take a look at this PR. Looks like build queue is down for an hour now

**Comment by girishkalele** [comment]
Hmmmm...my PR did pass all the checks at that time though...did something change with the munge-doc check ?

**Comment by foxish** [comment]
Does this need to be cherrypicked into v1.4? @girishkalele @mml

**Comment by girishkalele** [comment]
This is just a proposal doc - we don't need to cherry-pick it - if we do cherry-pick this, we also need #32219 which fixes a build breakage from this PR.

**Comment by mml** [comment]
@girishkalele if you look at the output from your run, the script ran into trouble because it didn't know about upstream/release-1.4, but the code is such that it still exits  0 when this happens.

**Pull request merged**
