### PR TITLE
Move DockerHung test in the end

### LINKED ISSUE #123928: Failure cluster [fb7fd2c4...] in ci-kubernetes-e2e-gci-gce-alpha-enabled-default
##### Error text:
```
[FAILED] an error on the server ("Internal Error: failed to list pod stats: rpc error: code = Unknown desc = failed to decode sandbox container metrics for sandbox \"0171ff000af5ac84916cd7efd64b2fb10927406a38fb3fb088ac1852311ab8ea\": failed to get pod sandbox stats since sandbox container \"0171ff000af5ac84916cd7efd64b2fb10927406a38fb3fb088ac1852311ab8ea\" is not in ready state") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-3clh:10250)
In [It] at: k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:380 @ 02/29/24 00:30:22.402

```
#### Recent failures:
[3/14/2024, 8:00:12 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768170244460777472)
[3/14/2024, 7:20:11 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768160175937556480)
[3/14/2024, 6:40:11 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768150109595373568)
[3/14/2024, 5:57:11 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768139287661907968)
[3/14/2024, 5:18:12 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768129474517274624)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by esotsal**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Checking the logs from https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1768108836683517952/artifacts/bootstrap-e2e-minion-group-sgqx/ i noticed that container is destroyed 

I see also from kernel logs that docker is blocked for 120second ( around the same time the container is destroyed )

Could it be that Docker Hung should be moved to be last in the test to avoid deleting a container? 

image

#### Which issue(s) this PR fixes:
Attempt to fix https://github.com/kubernetes/kubernetes/issues/123928

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/hold 

alpha jobs needs to disabled the evented pleg feature

**Comment by aojea** [comment]
> /hold
> 
> alpha jobs needs to disabled the evented pleg feature

upps
/hold cancel 

not the problem https://github.com/kubernetes/kubernetes/issues/123928#issuecomment-2035202033

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
