### PR TITLE
Remove conntrack max from proxy tests in kubeadm

### PR DESCRIPTION
**Pull request by rikatz**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: We're removing the deprecated flag ``--conntrack-max`` from kube-proxy but the tests are failing because of kubeadm test files still uses this flag.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rikatz** [comment]
Related issue: #78296 
Related failing PR: #78365

**Review by yagonobre — COMMENTED** [review]
Thanks @rikatz 

/ok-to-test
/kind cleanup
/priority backlog

**Comment by neolit123** [comment]
hi @rikatz 

> We're removing the deprecated flag --conntrack-max from kube-proxy but the tests are failing because of kubeadm test files still uses this flag.

could you please reference the kube-proxy tracking issue / PRs?

**Comment by rikatz** [comment]
@neolit123 

Related issue: #78296
Related failing PR: #78365

**Comment by neolit123** [comment]
@rikatz 

this changes in this PR has to be made part of https://github.com/kubernetes/kubernetes/pull/78365
i.e. combine them.

**Comment by rikatz** [comment]
Tks @neolit123 will proceed that way so :)

**Pull request closed without merging**
