### PR TITLE
Log response body when http probe fails.

### PR DESCRIPTION
**Pull request by bprashanth**
To help debug https://github.com/kubernetes/kubernetes/issues/21940

### CODE REVIEW

**Comment by bprashanth** [comment]
This message is confusing. Everything passed. 
```
GCE e2e build/test errored for commit fcc7e99.

Build Log
Test Artifacts
Internal Jenkins Results
Please reference the list of currently known flakes when examining this failure.
```
@kubernetes/goog-testing

**Comment by timstclair** [comment]
lgtm

**Comment by spxtr** [comment]
Might consider manually merging. Submit queue is pretty long.

**Comment by ixdy** [comment]
Yeah, I must've fat-fingered the Jenkins configuration when adding that flake link. Fixed now.

**Comment by bprashanth** [comment]
@k8s-oncall can I get a hand merge?

**Comment by gmarek** [comment]
Here you are.

**Pull request merged**
