### PR TITLE
Fix storage feature gate testing

### LINKED ISSUE #71091: VolumeScheduling unit tests assume the feature gate is off
**What happened**: Tests pass/fail depending on what tests run before them. If VolumeScheduling is on, StorageClasses must have a VolumeBindingMode field. If it is off, it can be nil.

**What you expected to happen**: Test pass/fail determinstically 

**How to reproduce it (as minimally and precisely as possible)**: ref: https://github.com/kubernetes/kubernetes/pull/65829

**Anything else we need to know?**: They should use SetFeatureGateDuringTest instead. Consider allowing VolumeBindingMode to be nil. (Same issue as VolumeMode).

/kind bug

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind bug
@kubernetes/sig-storage-pr-reviews 

**What this PR does / why we need it**:
Fixes feature gate setting in pkg/controller/volume/persistentvolume

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71091

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
squashed

**Comment by AishSundar** [comment]
@msau42 how confident are we in getting this in by Code freeze tomorrow?

**Comment by msau42** [comment]
This issue will be addressed by https://github.com/kubernetes/kubernetes/pull/71100
/close

**Pull request closed without merging**
