### PR TITLE
genconversion=false should skip fields during conversion generation

### PR DESCRIPTION
**Pull request by smarterclayton**
Currently it only skips if the fields don't match, but that leaves no
way for callers to say "no really, ignore this field".

@wojtek-t @thockin _must_ be able to ignore a non-convertible field (if the types are different but we still want the autogeneration of everything else)

### CODE REVIEW

**Comment by thockin** [comment]
No impact on generated code?

**Comment by smarterclayton** [comment]
Well, now that it isn't checked in it's surprisingly hard to be sure, but I
didn't see any changes.  Will do a second pass in the morning (only
deprecated fields in v1 use it).

**Comment by smarterclayton** [comment]
Deprecated fields that were already omitted because they're not in one or
the other.  This is when a field is the same, but no automatic conversion
is possible, which we don't have in Kube yet.

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
