### PR TITLE
change error message (line 837, glusterfs.go) to log level 2

### PR DESCRIPTION
**Pull request by lucasdu2**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Basic debugging information when Kubernetes fails to provision a GlusterFS volume is hidden in too-high log level (level 4). PR moves this information to log level 2. 

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:
none

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by lucasdu2** [comment]
> 

CLA check passes now

**Comment by lucasdu2** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/20580498/106724/#/?version=2)
> 
> * ❌ The commit ([79d4791](https://github.com/kubernetes/kubernetes/commit/79d479102a525d83bef5a761ef84a469c6a4a772)) is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

CLA check passes now

**Comment by humblec** [comment]
@dims anything to correct here on CLA side?.

**Comment by dims** [comment]
@humblec nah. if you see the checks above ^^ both EasyCLA and cla/linuxfoundation is green ✅

**Comment by humblec** [comment]
Thanks @dims

**Pull request closed without merging**
