### PR TITLE
Switch network tester image to gcr.io

### PR DESCRIPTION
**Pull request by satnam6502**

### CODE REVIEW

**Comment by satnam6502** [comment]
Ping?

**Comment by zmerlynn** [comment]
Rebase?

**Comment by satnam6502** [comment]
How is this?

**Comment by zmerlynn** [comment]
LGTM

**Comment by bprashanth** [comment]
travis failure looks like https://github.com/GoogleCloudPlatform/kubernetes/issues/6199
kicked it, will wait around anyway for the sake of best practice though it won't test much in this change

**Pull request merged**
