### PR TITLE
PDB checks should not be done for terminal pods while evicting

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Signed-off-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
PDB checks should not be done for terminal pods while evicting
```

/cc @feiskyer

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
It looks fine to me, but I don't have enough expertise in this area and don't have approval powers either. Owners of the code may provide a better review.

**Comment by ravisantoshgudimetla** [comment]
@bsalamat This is cherry-pick of #68892 on 1.12 which was already reviewe and merged.

**Comment by bsalamat** [comment]
Ah, I thought it was the same PR. This is fine with me, but I don't have approval power for the files changed here.

/lgtm

**Pull request merged**
