### PR TITLE
remove unused code in test/e2e/apps/deployment

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
/kind cleanup

**What this PR does / why we need it**:

remove unused code in test/e2e/apps/deployment 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
Thanks
/lgtm

**Comment by tanjunchen** [comment]
/cc @SataQiu 
/cc @oomichi  
the conflicts happens so  i update it. please review it again.Thanks

**Review by SataQiu — COMMENTED** [review]
/test pull-kubernetes-e2e-gce

**Pull request merged**
