### PR TITLE
Automated cherry pick of #65226: Put all the node address cloud provider retrival complex

### PR DESCRIPTION
**Pull request by lingxiankong**
Cherry pick of #65226 on release-1.11.

#65226: Put all the node address cloud provider retrival complex

### CODE REVIEW

**Comment by lingxiankong** [comment]
@jberkus @calebamiles @foxish please help to review. A related issue in cloud-provider-openstack repo: https://github.com/kubernetes/cloud-provider-openstack/issues/280

**Comment by foxish** [comment]
Needs lgtm+approval.
cc @ingvagabund @derekwaynecarr

**Comment by lingxiankong** [comment]
@ingvagabund @derekwaynecarr could you please review this PR? There is a critical issue needs this change, thanks!

**Comment by mikedanese** [comment]
Why are we cherry picking this. What does this fix?

**Comment by lingxiankong** [comment]
@mikedanese I believe if you open the link of the original PR you will get more information.

The problem we want to fix is, on the cloud environment(e.g. we are using openstack), it's highly likely that some nodes are loosing private and external ip address so that the user cannot attach the pod because the kubelet is not reachable. An related issue is here https://github.com/kubernetes/kubernetes/issues/68270

@mikedanese make sense to you?

**Comment by openstacker** [comment]
> I actually don't have the necessary approver permission. I'll leave this to sig node to assess the risk of a cherry pick. This looks like a pretty significant diff which concerns me,
> 
> @kubernetes/sig-node-bugs @kubernetes/sig-node-pr-reviews

@mikedanese Thanks, Mike. That's a very critical bug which is affecting almost all cloud providers (Azure, OpenStack, vsphere, etc). For the worst case if we can't cherry-pick this one, we do need a solution for the bug. Thanks.

**Comment by alena1108** [comment]
Is this fix planned for 1.11.5? We really really need it as a lot of users complained about this bug

**Comment by openstacker** [comment]
@alena1108 We hope it can meet the v1.11.5 release. But unfortunately seems some reviewers are not aware of the severity of this bug.

**Comment by alena1108** [comment]
@dchen1107 Seems like the pr has been Approved, what else does it take for it to be merged and become a part of  v1.11.5?

**Comment by foxish** [comment]
Branch is currently frozen for an upcoming release. Will target this for 1.11.6

**Comment by openstacker** [comment]
@foxish Thanks, so is there anything else we need to do for this PR or just wait? Thanks.

**Comment by foxish** [comment]
Labels look good. No other action needed.

**Comment by alena1108** [comment]
@foxish what is the approximate ETA for v1.11.6, how many weeks from now? We need to update our users

**Comment by alena1108** [comment]
@foxish `v1.11.6-beta.0` was cut yesterday; any reason this pr is still not a part of it? We'd really like to start testing/evaluating it

**Comment by foxish** [comment]
1.11.6-beta.0 is just automatically cut and mirrors what's in 1.11.5.

I'll review it this week and it should make it into 1.11.6.

**Comment by lingxiankong** [comment]
Can anybody please tell me that which stable release will this PR land in?

**Comment by idealhack** [comment]
should be 1.11.6, the commit will be tagged then

**Pull request merged**
