### PR TITLE
Automated cherry pick of #75750: Improve volume operation metrics

### PR DESCRIPTION
**Pull request by msau42**
Cherry pick of #75750 on release-1.14.

#75750: Improve volume operation metrics

```release-note
Adds a new "storage_operation_status_count" metric for kube-controller-manager and kubelet to count success and error statues.
```

### CODE REVIEW

**Comment by tpepper** [comment]
@msau42 can you update the release note?

**Comment by msau42** [comment]
added

**Comment by msau42** [comment]
on a side note, is the tooling supposed to automatically take the release note from the parent pr?

**Comment by tpepper** [comment]
> on a side note, is the tooling supposed to automatically take the release note from the parent pr?

It is supposed to and does, but sometimes it gets confused.  I'm not seeing why it should have failed on this one.

**Pull request merged**
