### PR TITLE
Fix golint issues in pkg/security/apparmor

### PR DESCRIPTION
**Pull request by hypnoglow**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint issues in `pkg/security/apparmor`

**Which issue(s) this PR fixes**:
Part of https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

---

/priority backlog
/area code-organization

### CODE REVIEW

**Comment by hypnoglow** [comment]
I'm not sure what sig apparmor belongs to, but probably it's **auth**.

/sig auth

/assign @lavalamp

**Review by SataQiu — APPROVED** [review]

**Comment by hypnoglow** [comment]
This was fixed in #84111 so I'm closing this.

**Pull request closed without merging**
