### PR TITLE
ContainerGC cleanup duplicated running containers

### LINKED ISSUE #98520: kubelet don't cleanup duplicated running containers
**What happened**:
In our cluster, a node's docker has some problem. after the node restarts, the docker response is very slow. after all pods become running, we find that a pod on this node has duplicated running containers. 

**What you expected to happen**:
kubelet’s ContainerGC can cleanup duplicated running containers

**How to reproduce it (as minimally and precisely as possible)**:
I simulate the problem scenario by restarting the exited container

1、create a pod on a node, you can use this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test1
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command: ["sleep", "1000000"]
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        ports:
        - containerPort: 81
          name: test
```
2、after pod running, log in to the node where the pod is located, kill the container:
image

3, start the exited container:
image

then, two duplicated containers will running on the node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.20.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):20.04.1 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`):Linux ecs-linux-0008-43ee 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chenyw1990**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
kubelet’s ContainerGC should be able to cleanup duplicated running containers

**Which issue(s) this PR fixes**:
Fixes #98520

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
For any container defined in a single Pod, ContainerGC should keep the latest created and running instance when there are multiple found running
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
/lgtm
thanks @chenyw1990

**Comment by rphillips** [comment]
Seems like this is uncovering a bug in either Kubelet's state machine or Docker's state machine. Have you been able to trace Kubelet/Docker's log file to see how the two containers are getting started?

**Comment by chenyw1990** [comment]
@rphillips docker' log file has lose , the problem scenario is as follows:
image

The scenario we encountered is more complicated. I simplified the scenario,
When the kubelet starts the container for the first time, timeout occurs,
If the pod status changes before the pleg relist detects the container status, the kubelet will create and start a container again. Because the Docker receives two start container requests, docker runs two same containers.

**Comment by derekwaynecarr** [comment]
I tend to agree with @rphillips that this is uncovering an issue in the state machine, and it seems like something we should catch in a sync loop iteration and not require container gc to uncover it.  its not clear for example if two containers were running that canceling one of them based on age is the right choice (especially if its running a workload).  can we explore other changes we can make to better prevent duplicate?  the create and start steps should be separate, so we should be able to detect if a container was already created .

**Comment by derekwaynecarr** [comment]
@mrunalp ^ have we ever seen similar via CRI path?

**Comment by chenyw1990** [comment]
@derekwaynecarr 
another people has report this issue again，
https://github.com/kubernetes/kubernetes/issues/98520#issuecomment-834976190

I think it's useful to clean up duplicate run containers.

**Comment by mrunalp** [comment]
I haven't seen this issue reported for CRI runtimes. I don't think it should be possible to hit it with CRI unless the runtime is doing some additional checks beyond invoking runc start.

**Pull request closed without merging**
