### PR TITLE
remove duplicate default message for some flag

### PR DESCRIPTION
**Pull request by pandaamanda**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove the default message.
```
root@k8s-EC600G3-GE:~/go/kubernetes# kubelet -h | grep memory-manager-policy
      --memory-manager-policy string                             Memory Manager policy to use. Possible values: 'None', 'Static'. Default: 'None' (default "None") (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
```
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by adisky — COMMENTED** [review]
/triage accepted
Looks good to me.
update here also https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L540

**Comment by pandaamanda** [comment]
> /triage accepted
> Looks good to me.
> update here also https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L540

thanks. updated.

**Pull request merged**
