### PR TITLE
Change regional PD cloud provider references to use the beta API

### LINKED ISSUE #59988: Improve k8s support for multizone PDs.
/kind feature

* Add more e2e tests for multizone PDs.
* Align with ongoing volume topology work.

/sig storage
/assign

### PR DESCRIPTION
**Pull request by verult**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59988

**Special notes for your reviewer**: Depends on a version of the GCP Go beta compute client that is not yet available. Also need to rebase with #60337 once it's merged.

/hold
/cc @abgworrall 
/assign @saad-ali

### CODE REVIEW

**Comment by jberkus** [comment]
@saad-ali if this PR is going to be in 1.10, then it needs status/approved-for-milestone.  Also daily updates on progress.  Thanks!

**Comment by verult** [comment]
Currently we are waiting for a version of the GCP Go beta compute client scheduled to be available on Saturday, 3/4.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60450)

**Comment by verult** [comment]
Integrated with up-to-date client, which is added as a separate commit.

**Comment by saad-ali** [comment]
/lgtm
/approve

For vendor dir approval
/assign @thockin

**Comment by verult** [comment]
Ran regional PD tests repeatedly on a multizonal cluster. Verified the following tests on single-zone clusters to catch potential regressions:
Persistent Volumes GCE
Volume Provisioning
PD tests
Also verified PV GCE and Volume Provisioning tests on a multizone cluster.

**Pull request merged**
