### PR TITLE
Fixing spelling error in api docs for `spec.serviceAccountName`

### PR DESCRIPTION
**Pull request by jmcshane**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The `spec.serviceAccount` field in the pod template has a spelling error in the API docs

#### Special notes for your reviewer:

This was discovered in discussion of kubernetes/website#37083

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by jmcshane** [comment]
@fedebongio rebased and all tests passing, can you reapply lgtm?

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
