### PR TITLE
Rename master to control plane in test/integration

### PR DESCRIPTION
**Pull request by spiffxp**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Renames "master" to "control plane" in test/integration

Explicitly left untouched are occurrences that might be api, flag, or
package changes that are out of scope for test/integration, e.g.:
- `system:masters`
- `MasterCount` (pkg/controlplane.Instance)
- `--endpoint-reconciler-type master-count`

In most other cases, the replacements were of the form:
- master -> control plane (in comments/quotes not referencing vars)
- master -> controlplane (files/packages)
- master -> controlPlane (vars/funcs)
- Master -> ControlPlane (vars/funcs)

**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes/kubernetes/issues/94900

Doesn't completely fix, but brings the list down to 
```
apiserver/admissionwebhook/admission_test.go
apiserver/admissionwebhook/client_auth_test.go
apiserver/admissionwebhook/load_balance_test.go
apiserver/admissionwebhook/reinvocation_test.go
apiserver/admissionwebhook/timeout_test.go
apiserver/certreload/certreload_test.go
auth/node_test.go
auth/rbac_test.go
certificates/admission_subjectrestriction_test.go
client/cert_rotation_test.go
controlplane/kube_apiserver_test.go
framework/controlplane_utils.go
ipamperf/README.md
```

**Special notes for your reviewer**:

I am open to suggestions if there are better names. I'll post the
specific replacements I used in a separate comment.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
Script used.  Tries to care of specific cases before doing the more general cases, then fixes up exceptions afterwards.
```bash
#!/bin/bash

# func/var/comment renames
find . -type f -name '*.go' | while read -r f; do
  gsed -i -E \
    -e 's/Congfig/Config/g' \
    -e 's/SetMaster/SetInstance/g' \
    -e 's/Master metrics/Control plane metrics/g' \
    -e 's/Master/ControlPlane/g' \
    -e 's/master-token/controlplane-token/g' \
    -e 's/package master/package controlplane/g' \
    -e 's/masterCount/controlPlaneCount/g' \
    -e 's!(//.*)master!\1control plane!g' \
    -e 's!(".*)master!\1control plane!g' \
    -e 's/master/controlPlane/g' \
    -e 's/system:(not)?control planes/system:\1masters/g' \
    -e 's/ControlPlaneCount/MasterCount/g' \
    -e 's/control plane-count/master-count/g' \
    -e 's/control plane count/controlPlaneCount/g' \
    -e 's/control plane.G/controlPlane.G/g' \
    -e 's/((a)n( ))?API control plane/\2\3control plane/g' \
    "${f}"
done 

# file/package renames
renamed=false

if [[ -f ./framework/master_utils.go ]]; then
  git mv ./framework/{master,controlplane}_utils.go
  renamed=true
fi

if [[ -d ./master ]]; then
  git mv ./{master,controlplane}
  gsed -i \
    -e 's/package master/package controlplane/' \
    ./controlplane/*.go
  git mv ./controlplane/synthetic_{master,controlplane}_test.go
  renamed=true
fi

if ${renamed}; then
  pushd ../../
  ./hack/update-bazel.sh
  popd
fi
```

**Comment by spiffxp** [comment]
/cc @liggitt @lavalamp 
if you have opinions or guidance here
/wg naming
/hold
for comment

**Comment by lavalamp** [comment]
IMO "control plane" is the plural, "instance" is the singular. It will be very confusing to use the word "control plane" to refer to only one apiserver if there are multiple. Unfortunately that means that mass find-replacing is going to be hard to verify.

I was taking the other approach, the rename script I was using parses go files and finds references (but currently misses *_test.go references). I was going to do one symbol at a time.

**Comment by spiffxp** [comment]
@laval
>IMO "control plane" is the plural, "instance" is the singular

That makes sense.  My concern is `instance` is pretty generic without some kind of qualifier.  e.g.
- `masterConfig` -> `instanceConfig`
- `NewIntegrationTestMasterConfig` -> `NewIntegrationTestInstanceConfig`

The best I can come up with given that opinion is to fully qualify, but it feels super verbose, e.g.
- `masterConfig` -> `controlPlaneInstanceConfig`
- `NewIntegrationTestMasterConfig` -> `NewIntegrationTestControlPlaneInstanceConfig`

Other things I considered
- `CPInstace/cpInstance`, but that could easily be confused with any of "cluster provider", "credentials provider", "cloud provider"
- `apiserver`, but there are tests in here that deal with apiservers separate from this, it seems like an instance of control plane is more than just an apiserver

WDYT?

**Comment by lavalamp** [comment]
Yeah it's clear from the package for my cases. I agree it's verbose to fully specify. I don't have a better idea, though. "CP" is jargony but might be worth it.

This is probably why the existing term persists, honestly.

**Comment by spiffxp** [comment]
/retest
flake (https://github.com/kubernetes/kubernetes/issues/93902)

**Review by neolit123 — COMMENTED** [review]
looking at the tests / diff, "master" seems to be mostly a shorthand for a "kube-apiserver instance".
i think of "control-plane" as the umbrella, singular entity that includes all instances of the control-plane components.

**Comment by spiffxp** [comment]
Ack.  I'll take another pass.  I'm coming at it from tests just needing a control plane to talk to, and they don't care how many instances it's composed of.  But it may be easier to just have everything talk to an instance.

**Comment by spiffxp** [comment]
I will take a crack at this via smaller scope PRs, followup in linked issue

**Pull request closed without merging**
