### PR TITLE
Remove some unused codes in stateful_set_utils.go

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority backlog

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by qingsenLi** [comment]
/assign @erictune @soltysh 
for approval.thanks

**Comment by qingsenLi** [comment]
/assign @erictune
PTAL,thanks

**Comment by qingsenLi** [comment]
/assign @liggitt @msau42
for approval.thanks

**Pull request merged**
