### PR TITLE
Add KUBE_EMULATED_VERSION env variable to set the emulated-version of apiserver

### PR DESCRIPTION
**Pull request by siyuanfoundation**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add KUBE_EMULATED_VERSION env variable to set the emulated-version of kube apiserver

The new compatibility feature has added a new `--emulated-version` flag to the api-server. We need a env variable to configure that in the kube apiserver config script.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/4330
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
We generally don't add features to cluster/, but I don't think we should require this feature to be exclusively tested on other e2e clusters so

/lgtm
/approve
/hold

**Comment by BenTheElder** [comment]
We should however, also explore testing with kOps, kind / kinder, .... especially if the tests will be integrating against the cluster management (seems plausible for this feature, I don't think we'll be doing normal e2e tests here...), at some point sig testing + infra are still looking to wind down kube-up.sh, probably in 2025 given the CI migration work taking precedent.

**Comment by jpbetz** [comment]
/lgtm
/approve

https://github.com/kubernetes/cloud-provider-gcp/blob/master/cluster/gce/gci/configure-kubeapiserver.sh will need this as well.. ideally via a rebase of the duplicated cluster directory there.

**Pull request merged**
