### PR TITLE
specific protocol is TCP

### PR DESCRIPTION
**Pull request by jedichien**
``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

in my case, I meet problem which is caused by default dashboard yaml.
so I add my solution which is "protocol: TCP" in addons/dashboard yaml file.

[Analytics]()

### CODE REVIEW

**Comment by ChienWorld** [comment]
I signed it!

**Comment by mikedanese** [comment]
Can you explain what problem this fixed for you?

cc @bryk

**Comment by ChienWorld** [comment]
sure, the problem is when I use it in my internet environment which connect via proxy, I can't deploy to my kubernetes cluster which mean dashboard not run. After I add protocol option, now I use dashboard very well.

**Comment by bryk** [comment]
@ChienWorld Hmm.... This must be some kind of flakiness in your deployment. This was TCP always, since TCP is the default option. Can you verify that this works without specifying the TCP option? If yes, how can I repro this? 

See code:
https://github.com/kubernetes/kubernetes/blob/4b4048a084d9a14ea4e72bb6e90dbd6493ba6945/pkg/api/v1/types.go#L901

And docs:
http://kubernetes.io/docs/user-guide/services/

**Comment by bryk** [comment]
@kubernetes/dashboard-maintainers

**Comment by mikedanese** [comment]
This is a default and it's a best practice to not specify defaults in config:

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/config-best-practices.md

**Pull request closed without merging**
