### PR TITLE
Admit failed, intercepting Pod Failed, bug fix.

### PR DESCRIPTION
**Pull request by davshen**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/123980

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by davshen** [comment]
> [CLA Missing ID](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/20580498/124014/#/?version=2) [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/20580498/124014/#/?version=2)
> 
> * ❌ The email address for the commit ([ad256d0](https://github.com/kubernetes/kubernetes/commit/ad256d0cb742afee217c32bacacc1fddbad44e13)) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

/reset

**Comment by bart0sh** [comment]
@davshen Can you provide unit or e2e test case covering this?

**Comment by Homura222** [comment]
I think 2581 line also should be fixed.

**Comment by bart0sh** [comment]
This and https://github.com/kubernetes/kubernetes/pull/124072 look like duplicates.
Please, agree with @yangyefei90 which one to close, thanks.

**Pull request closed without merging**
