### PR TITLE
(scheduler e2e) Create balanced pods in parallel

### PR DESCRIPTION
**Pull request by damemi**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Backport of https://github.com/kubernetes/kubernetes/pull/102138 to create scheduler e2e balance pods in parallel for large clusters, in order to prevent timeouts

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/sig scheduling
/cc @alculquicondor

**Comment by alculquicondor** [comment]
This one seems to require more work

**Comment by alculquicondor** [comment]
ahh, ol' bazel
/lgtm

**Comment by ialidzhikov** [comment]
/assign @huang-wei
for approval

**Comment by ialidzhikov** [comment]
/cc @kubernetes/release-managers
for approval (second time)

**Review by saschagrunert — APPROVED** [review]
/lgtm
Double checked that this patch is already part of `release-1.21`, too.

**Pull request merged**
