### PR TITLE
Remove when alpha support for affinity is removed

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
 remove when alpha support for affinity is removed

**Special notes for your reviewer**:
refer to https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature
Now it's not alpha feature yet.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
cc @aveshagarwal @davidopp it looks like you authored/reviewed the original code.

**Comment by aveshagarwal** [comment]
But we had re-added validation for affinities annotations.

**Comment by zhangxiaoyu-zidif** [comment]
Hi，@aveshagarwal. I have not understand that. =) Is that deleted code newly added? Or we need to remain these code? 
1) If it is not necessary, should I fix the comment "TODO: remove when alpha support for affinity is removed", en, this comment may be  "TODO: remove when not support for affinity in annotation"
2) continue to delete them.
Sir, I hope for your instruction =)

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-verify test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by aveshagarwal** [comment]
@zhangxiaoyu-zidif affinities are already beta now.  This validation, we had readded to address upgrade issues in 1.6.

**Comment by aveshagarwal** [comment]
I think that this PR should be closed now as https://github.com/kubernetes/kubernetes/pull/47869 is already merged.

**Comment by zhangxiaoyu-zidif** [comment]
@aveshagarwal Thank you. I will close it.

**Pull request closed without merging**
