### PR TITLE
yamlfmt cleanup

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- simplifies logic ... NArgs() returns len(Args())
- add `labels` (sig/testing, sig/contributor-experience) and `reviewers` (myself + existing approvers) to OWNERS

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/assign @dims 
cc @dims @thockin

### CODE REVIEW

**Review by mimani68 — APPROVED** [review]

**Comment by dims** [comment]
won't merge until we check out what the ci job found :)

```
{Script Error ScriptError YAML files need to be formatted
Please run 'hack/update-yamlfmt.sh'}
```

**Review by thockin — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
fixed

**Pull request merged**
