### PR TITLE
Move versioned generators into their own package

### PR DESCRIPTION
**Pull request by smarterclayton**
pkg/kubectl has a lot of files. Move everything generator related
into pkg/kubectl/generate (generic) or pkg/kubectl/generate/versioned
(type specific).

Move the DescriberFn and GeneratorFn out of kubectl/cmd/util and into
the respective versioned packages, along with tests.

@kubernetes/sig-cli-bugs

**What this PR does / why we need it**:

Continue to clean up pkg/kubectl, separate out implementation and interfaces

**Special notes for your reviewer**:
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k @soltysh hit this while I was trying to split binaries out of a command - I realized that kubectl/cmd/util still pulls in all internal types.

**Comment by smarterclayton** [comment]
@soltysh when you have chance if you could review

**Review by soltysh — APPROVED** [review]
@smarterclayton sorry for the delay this all lgtm, would you mind rebasing it and once you do feel free to self-tag it so that it lands fast. I don't want to hold you back on this.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
