### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Move apply to apimachinery

### PR DESCRIPTION
**Pull request by apelisse**
**What this PR does / why we need it**:
This PR updates the apply code to not depend on Resources (the full list of all resources available on the server), but just a single Schema. And then moves the code from kubectl to apimachinery.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Did we argue about whether move or copy helps us more?

**Comment by lavalamp** [comment]
(chatted off-line; I reserve the right to an "itoldyouso" if this move causes a merge conflict that would have been avoided by just copying)

/approve

**Comment by apelisse** [comment]
And I'll be happy to fix that merge conflict if it happens :D

**Pull request merged**
