### PR TITLE
Add PodHostIPs test

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
@wzshiming it lgtm, do you have WIP because of something?

**Comment by wzshiming** [comment]
> @wzshiming it lgtm, do you have WIP because of something?

It is ready, sorry I forgot to remove the WIP

**Comment by wzshiming** [comment]
`pull-kubernetes-e2e-kind-beta-features` This has not been passed, according to the test name, is this feature not being moved to beta caused?

**Comment by aojea** [comment]
/lgtm

the test fails because the gate is disabled

**Pull request merged**
