### PR TITLE
cleanup:use copy other than for loop

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Use copy other than for loop
Code simplification, a by-product of debugging https://github.com/kubernetes/kubernetes/pull/110811
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Abirdcfly** [comment]
kindly ping @thockin 🙋‍♂️

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
