### PR TITLE
using cobra commands for gke-certificate-controller

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

using cobra commands

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@kubernetes/sig-auth-api-reviews @ericchiang @tallclair @liggitt @mikedanese This was promised to move out of tree when it was first added.  It's been a while, it seems like its time to remove it instead of refactoring it.

**Comment by mikedanese** [comment]
I agree. Adding deps will not make that easier. @cheftako can we move this into the gcp cloud-controller-manager repo? Where is that code destined?

**Comment by cheftako** [comment]
@mikedanese I agree that this should move to the gcp repo once it exists. However we are still a little while from that occurring. More to the point we are probably a year from being able to delete the code from here.

**Comment by deads2k** [comment]
> @mikedanese I agree that this should move to the gcp repo once it exists. However we are still a little while from that occurring. More to the point we are probably a year from being able to delete the code from here.

This came in a year ago in this pull: https://github.com/kubernetes/kubernetes/pull/41160 along with agreement from @bgrant0607 that it move out tree (https://github.com/kubernetes/kubernetes/pull/41160#issuecomment-280751115).  At the time there was concern from others about adding GKE specifics to the kube codebase (@ixdy comes to mind here: https://github.com/kubernetes/kubernetes/pull/41160#issuecomment-282180344 and @liggitt here https://github.com/kubernetes/kubernetes/pull/41160#issuecomment-282193742).

It's been a year and it looks like the "temporary" command is lingering here.  What are tasks left to be accomplished to move this google specific controller integration out of tree?

**Comment by mikedanese** [comment]
I think the last thing we were waiting for was a git repository which I don't think is ready. I don't think deleting this from cmd/ needs to wait for that though.

**Comment by roberthbailey** [comment]
The gke-certificates-controller was removed in https://github.com/kubernetes/kubernetes/pull/59933 so I'm going to go ahead and close this PR. 

Thanks for taking the initiative to convert this program to cobra; it caused us to help clean up some technical debt that had been around for quite some time.

**Pull request closed without merging**
