### PR TITLE
fix: Remove dependency on github.com/pkg/errors

### LINKED ISSUE #113627: Remove dependency on github.com/pkg/errors
**Why is this needed?**

The functionality that the package provides is already present in golang's builtin errors (using `%w` in `fmt.Errof`) and the github repo is now read-only.

/kind cleanup
/priority backlog
/good-first-issue

**Notes to people that want to collaborate**

Avoid creating a single PR for the entire repo. Create multiple PRs, each targeting a specific SIG.

Do **not** submit PRs for `cmd/kubeadm`

### PR DESCRIPTION
**Pull request by falser101**
Signed-off-by: jianfei.zhang <jianfei.zhang@daocloud.io>
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:
Fixes #113627

#### Special notes for your reviewer:

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
None
```

### CODE REVIEW

**Comment by falser101** [comment]
@pacoxu

**Comment by falser101** [comment]
@alculquicondor

**Comment by pacoxu** [comment]
> Just a reminder, https://github.com/kubernetes/kubernetes/issues/103043 the issue said "NOTE : Please do not submit PRs for cmd/kubeadm/app though it is listed below." But I have no contextual information...

per https://github.com/kubernetes/kubernetes/pull/110830#issuecomment-1168441058

**Review by neolit123 — COMMENTED** [review]
i am -1 in the change as explained in prior comments

**Comment by falser101** [comment]
> i am -1 in the change as explained in prior comments
what this means

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/pull/110830#issuecomment-1168758529.

**Pull request closed without merging**
