### PR TITLE
Get rid of panics.go in apiserver logs

### LINKED ISSUE #37706: apiserver log lines are printed from the file "panics.go"
This is simple cleanup. It is unnecessarily disconcerting to read through apiserver logs and find every log line is from the file "panics.go". We should adjust the code printing these lines, either by changing the file name, or (ideally) by making it more intelligent about logging the source of the call (e.g., callers--).

### PR DESCRIPTION
**Pull request by nebril**
Displaying the place in which the "real" handler is was discarded as too
big change - it would cause all HTTP handlers need to handle request
logging on their own.

fixes #37706

### CODE REVIEW

**Comment by nebril** [comment]
@k8s-bot verify test this

**Comment by k82cn** [comment]
@nebril , what's different between `panics.go` and `wrap.go`?

**Comment by k82cn** [comment]
@nebril , I'm thinking we should replace `panics.go` with real file of handler.

```
I0103 19:01:23.241094   10246 panics.go:76] POST /apis/rbac.authorization.k8s.io/v1alpha1/clusterroles: (43.950252ms) 201 [[hyperkube/v1.6.0 (linux/amd64) kubernetes/20540df] [::1]:46713]
```

**Comment by nebril** [comment]
@k82cn the problem is that real file of handler is `panics.go`, because the original handler is wrapped by the wrapper in `panics.go`.

If you wanted to put original file handlers there, all handlers would be required to log their request and cause a lot of code duplication, instead of having it handled by the wrapper in `panics.go` (due to how `runtime.Caller` works, unless I missed something that allows you to retrieve filename from function object in `reflect` package). I decided that it's not worth it, hence the much smaller fix :).

**Comment by k82cn** [comment]
Yes, I know this when I try to create a PR. Just not sure the value to change from `panics.go` to `wrap.go` in log.

**Comment by nebril** [comment]
Well, it changes the log content if that's what you are afraid of. Excerpt from logs:

```
I0105 11:29:23.770464      23 wrap.go:75] GET /apis/extensions/v1beta1/namespaces/default/deployments: (582.804µs) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/50e12ff] 172.17.0.1:37144]
I0105 11:29:23.770989      23 wrap.go:75] GET /apis/storage.k8s.io/v1beta1: (64.231µs) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/50e12ff] 172.17.0.1:37148]
I0105 11:29:23.771589      23 wrap.go:75] GET /apis/extensions/v1beta1/namespaces/default/replicasets: (600.597µs) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/50e12ff] 172.17.0.1:37144]
I0105 11:29:23.772294      23 wrap.go:75] GET /api/v1: (561.504µs) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/50e12ff] 172.17.0.1:37148]
```

**Comment by lavalamp** [comment]
The solution I had in mind was to increment the number passed to the runtime function that gets the filename, so that it is more useful. Having all lines logged from the same file isn't ideal, although to be sure "wrap" is a large improvement over "panic" :)

**Comment by nebril** [comment]
@lavalamp I tried it and if having all logs come from golang core `server.go` file (from package net/http) suits you - by all means I will do it like that.

I just thought that it will be more convenient to have logs come from a uniquely named file, especially since we have several `server.go` in our codebase and none of them would actually be the file to look for log source.

**Comment by karsinkk** [comment]
lgtm

**Comment by nebril** [comment]
@lavalamp if that's not ok I can close this PR, let me know if you want to close it or merge it.

**Comment by lavalamp** [comment]
Sorry for slow responses, I still have a pretty huge backlog! If you keep going up the stack do you eventually get something useful to print? If not then renaming the file is not bad, I guess.

**Comment by nebril** [comment]
@lavalamp no problem, I will check out what happens up the stack, maybe there is something that is actually useful.

**Comment by nebril** [comment]
@lavalamp unfortunately all I could find up the stack was: 
panics.go:75]
server.go:1726]
timeout.go:89]
asm_amd64.s:2086]

All these were the same for all logs, so I guess renaming the file is the proper solution for now :(.

**Comment by nebril** [comment]
@k8s-bot gci gke e2e test this

**Comment by nebril** [comment]
@k8s-bot cvm gke e2e test this

**Comment by mbohlool** [comment]
@nebril renaming looks good. But why the new filename is filters.go? I think I like wrap.go or something like util.go is better than filters.go. filters is the name of the package and a file with that name suggests it has the main functionality of the package which I guess it is not here.

**Comment by nebril** [comment]
@mbohlool makes sense, done

**Pull request merged**
