### PR TITLE
Update godeps after addition of LICENSE files

### PR DESCRIPTION
**Pull request by eparis**
https://github.com/tools/godep/commit/dcbe29c7a18887497b4857e64665d25be43f7c7e

Caused godeps to start including the LICENSE file for all vendored deps.
We need to include it now to keep the deps reproducible.

### CODE REVIEW

**Comment by eparis** [comment]
Notice this PR against release-1.1

It is not a cherry-pick of #16794 sa godeps are different between head and 1.1

**Comment by quinton-hoole** [comment]
I don't feel sufficiently knowledgable about the intracacies of our use of godeps and vendoring to do a good job of reviewing this.  @bgrant0607 ?  @thockin ?  Can you find someone?

**Comment by bgrant0607** [comment]
Awesome. Thanks @eparis.

Does this require everyone to update their version of godeps? If so, we should document that, and maybe run some kind of check to verify that the right version of godeps is present for any PR that touches godeps.

cc @lavalamp

**Comment by lavalamp** [comment]
LGTM; in theory the verify-godep script should catch it if people use the wrong version of godep.

**Comment by eparis** [comment]
if someone uses an old version they will likely either include the _test.go files or exclude the LICENSE files. In both cases the test should notice and fail.

**Comment by eparis** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Comment by eparis** [comment]
whoops, i know unit test won't work.  But shippable got it.

**Comment by bgrant0607** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot e2e test this

**Comment by piosz** [comment]
@k8s-bot e2e test this

**Pull request merged**
