### PR TITLE
Add SIG owners to e2e tests

### PR DESCRIPTION
**Pull request by calebamiles**
**What this PR does / why we need it**:

Adds SIG owners to e2e tests in order to support assigning test flakes and general test failures to SIGs rather than relying solely on individuals. Ideally this will help spread the maintenance burden across more This work is part of closing https://github.com/kubernetes/contrib/issues/2389

**Which issue this PR fixes** 

Part of the work to address 
-  https://groups.google.com/forum/#!topic/kubernetes-dev/5kTLRfKId9g

Tracking issue
- https://github.com/kubernetes/contrib/issues/2389

**Special notes for your reviewer**:

None

**Release note**:

 `NONE`.

### CODE REVIEW

**Comment by calebamiles** [comment]
**cc: @ethernetdan, @philips, @pwittrock**

**Comment by pwittrock** [comment]
Seems like a good start

**Comment by calebamiles** [comment]
@kubernetes/kubernetes-build-cops is there anything to look at with the `Jenkins CRI GCE Node e2e — Error waiting for build.` CI error? I added a re-test not required to free up resources since this PR only annotates the `test_owners.csv` with SIG owners

**Comment by ixdy** [comment]
@yujuhong is this ^ expected with recent changes?

we might need to update the list of "required" jobs on the project. @spxtr

**Comment by yujuhong** [comment]
@ixdy I think this happened before you updated prow. It should be fine now. #41614 correctly ran the all jobs.

**Pull request merged**
