### PR TITLE
refactor: move attachdetach controller param validation ahead

### PR DESCRIPTION
**Pull request by pandaamanda**
Code cleanup:
1. move attachdetach controller param `attach-detach-reconcile-sync-period` validation ahead.
2. add fucntion `validateCIDRs` to eliminate duplicated code.

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Is this unit testable?

**Comment by pandaamanda** [comment]
> 

Tks. 
No logic changed, should we add a unit test?

**Comment by pandaamanda** [comment]
> Is this unit testable?

Tks.
No logic changed, should we add a unit test?

**Comment by sttts** [comment]
> No logic changed

How do you know? :)

**Comment by pandaamanda** [comment]
> > No logic changed
> 
> How do you know? :)

IMO.  The change is just code place changed, not related logic. so we should add a ut for param validation or function validateCIDRs or both?

**Pull request merged**
