### PR TITLE
code cleanup: scheduler simplify the check function in NodeLabel.Filter

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

As we can see, `(exists && !presence) || (!exists && presence)` is equivalent to `exists != presence`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by BinacsLee** [comment]
cc @ahg-g @damemi 
Thank you very much! ^-^

**Review by damemi — COMMENTED** [review]
/ok-to-test

**Comment by BinacsLee** [comment]
Nice. It passed all the tests.
 @damemi Could you please merge this PR?

**Review by gavinfish — COMMENTED** [review]
/lgtm

**Pull request merged**
