### PR TITLE
Serialized protobuf should have stable map order

### LINKED ISSUE #47678: protobuf maps aren't order stable, defeating the "no mutate on write" guarantee
Maps are in random order due to Go.

Adding `stable_marshaller_all` to gen-go makes it stable.  Possibly at risk of altering some guarantees of generation.

@kubernetes/sig-api-machinery-pr-reviews 

We have to decide whether to put this in 1.7

### PR DESCRIPTION
**Pull request by smarterclayton**
Leverage `stable_marshaller_all` tag in gogo-protobuf to ensure all of our maps have stable ordering when serialized to protobuf. This preserves the behavior from JSON that we rely on to avoid writing to etcd except when the content has changed.

Will slightly increase allocations (1 slice per non-empty map in an object) during Encode, which has a minor impact on CPU. However, avoiding writes when a client issues a blind put results in significantly less CPU across the whole cluster (avoiding a new etcd version for an Endpoints object might save ~1 core/sec on large clusters).

Fixes #47678 

```release-note
The protobuf serialization of API objects has been updated to store maps in a predictable order to ensure that the representation of that object does not change when saved into etcd. This prevents the same object from being seen as being modified, even when no values have changed.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery-pr-reviews

**Comment by liggitt** [comment]
Fuzz test that serializes multiple times and ensures output is stable would be good

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by liggitt** [comment]
LGTM, though I'm unsure whether we want this for 1.7

**Pull request merged**
