### PR TITLE
cleanup: Replace the deprecated NewMemCacheClient with memory.NewMemCacheClient

### PR DESCRIPTION
**Pull request by togettoyou**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

`NewMemCacheClient` has been deprecated and is still being called in some files. 

change it to the new `k8s.io/client-go/discovery/cached/memory` library.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by togettoyou** [comment]
Hi @HirazawaUi ,  Do you know why `pull-kubernetes-dependencies` always fails?

**Comment by aojea** [comment]
Click on the link to the failed job

image

click on "see stderr for details"

image

**Comment by togettoyou** [comment]
@aojea Thank you

**Comment by aojea** [comment]
/lgtm

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/discovery/cached/legacy.go

/assign @liggitt

**Pull request merged**
