### PR TITLE
Ensure status is not changed during an update of PV, PVC, HPA objects

### PR DESCRIPTION
**Pull request by mqliang**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@liggitt FYI

**Comment by smarterclayton** [comment]
@k8s-bot test this issue IGNORE

**Comment by smarterclayton** [comment]
This needs to be cherry-picked to 1.2 if it's there.

**Comment by smarterclayton** [comment]
This is also a bug on HPA, can you change that one as well?

**Comment by smarterclayton** [comment]
@eparis the bots are arguing with each other

**Comment by roberthbailey** [comment]
@smarterclayton - should we get this merged / cherry picked so that we can get it into the next release?

**Comment by smarterclayton** [comment]
Yes

**Comment by smarterclayton** [comment]
Looks like my comment from last night was lost in the mail - HPA also has this bug and needs to get updated.

**Comment by a-robinson** [comment]
@mqliang - any chance of getting this PR updated to include HPA today/tonight? This is the only cherrypick candidate remaining for the next patch release that isn't ready to be merged.

**Comment by mqliang** [comment]
@a-robinson @smarterclayton HPA included. PTAL.

**Comment by a-robinson** [comment]
Thanks @mqliang. LGTM, but I'll defer to @smarterclayton

**Comment by smarterclayton** [comment]
Lgtm, thanks.

**Comment by roberthbailey** [comment]
@smarterclayton Since we want to cherry pick this PR we should set a release note. Can you update the issue title?

**Comment by roberthbailey** [comment]
Thanks @liggitt!

**Pull request merged**
