### PR TITLE
Clean up petset

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Rename legacy petset to statefulset.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@k8s-bot tell me a joke

**Comment by gmarek** [comment]
Well - LGTM, but you need to find approvers for all those directories.
/lgtm

**Comment by xiangpengzhao** [comment]
@gmarek Thanks Marek !

ping @deads2k @eparis for approve :)

**Comment by gmarek** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
The example changes are fine.  approving it.

**Pull request merged**
