### PR TITLE
Sketch: a third take on defaulting values

### PR DESCRIPTION
**Pull request by thockin**
This still fails round-trip tests.  Ideas there?

ref #1502

### CODE REVIEW

**Comment by dchen1107** [comment]
What is blocking us on making progress of this PR beside rebase?

**Comment by bgrant0607** [comment]
I think this was blocked on a couple fuzzer-related things:
1. how to determine that a round-tripped object is the same after default values have been set
2. how to ensure the conversion and/or defaulting logic in the round-trip process behaves correctly for randomly generated objects

Alternatives for (1) are to apply defaults before round-tripping or to only diff selected fields, as we plan to do in config, such as by keeping track of which fields the fuzzer populates.

I think the only sane thing to do for (2) is to ensure that we round-trip only valid objects. This means they must have defaults applied and must pass validation.

**Comment by lavalamp** [comment]
A solution to 1 is to use the Semantic.DeepEqual I added the other day, or make a separate one that specifically ignores defaults (probably a good idea anyway).

The conversion routines don't have to do correct things on random input, but they must NOT crash. Fuzz testing should continue to be used to verify this property even if we have to do something more fancy to verify the round-trip property. There should be two tests here, not the one we have right now.

**Comment by thockin** [comment]
Main blocker is a person. To work on it.

**Comment by bgrant0607** [comment]
#3854 has been merged. This is obsolete.

**Pull request closed without merging**
