### PR TITLE
Much smaller hyperkube image creation

### PR DESCRIPTION
**Pull request by mikeln**
Improve the Dockerfile that creates the Hyperkube image. 
This will drop the image size from ~200+MB    to ~59MB

### CODE REVIEW

**Comment by erictune** [comment]
add to whitelist

**Comment by erictune** [comment]
I don't have a problem with this improvement.

However, I started to wonder about how to test it, and I noticed that
it won't get much automated test coverage because got GCE, GKE, Vagrant, AWS, etc, we are using different images.  You can see those images being referenced here:
```console
$ grep google_containers -R cluster
...
cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest:    "image": "gcr.io/google_containers/kube-apiserver:{{pillar['kube-apiserver_docker_tag']}}",
cluster/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest:    "image": "gcr.io/google_containers/kube-controller-manager:{{pillar['kube-controller-manager_docker_tag']}}",
cluster/saltbase/salt/kube-scheduler/kube-scheduler.manifest:    "image": "gcr.io/google_containers/kube-scheduler:{{pillar['kube-scheduler_docker_tag']}}",
```

The "Dockerfile" for those images is in `build/common.sh` in function `kube::release::create_docker_images_for_server`. It uses `FROM busybox` instead of `FROM google/debian:wheezy`.


@mikeln how does the size of your slimmed down image compare to these other images, and can you do any magic to make those smaller too?

@brendandburns @ArtfulCoder  Are the images used by salt different for a reason (busybox vs debian, hyperkube vs individual images per binary) or just nobody has gotten around to it?





But I can't seem to find the dockerfiles for those
Those images have dockerfiles here:

**Comment by mikeln** [comment]
@erictune I haven't looked at the other Dockerfiles.   But I will when I have some spare cycles. This was an image we had to build to incorporate some non-released changes to fix it, so as long as we were building it I looked into why the image seemed bloated.  Easy initial fix.  It should be possible to push the sizes down more using alpine.

**Comment by mbforbes** [comment]
This is awesome.

**Comment by mbforbes** [comment]
close/reopen for Shippable

**Comment by mbforbes** [comment]
+cc @ihmccreery for thinking about hyperkube testing

**Comment by mikeln** [comment]
what is up that that error in shippable?

**Comment by erictune** [comment]
@mikeln

Shippable error may be due to issues with us moving the code from GoogleCloudPlatform/kubernetes to kubernetes/kubernetes.  If you rebase, I bet it passes.


Also, I don't think we have any e2e test coverage of hyperkube.  @mbforbes any ideas on how to test this change, if at all?  @mikeln can you describe any testing you did with this change?

**Comment by mikeln** [comment]
No specific testing. Just comparison of our clusters running this version vs running previous discrete kubernetes binaries.  

I would think the real test would be using this image to start whatever test kubernetes cluster is being created for the integ and e2e tests.

**Comment by mbforbes** [comment]
@erictune given we don't have any e2e tests on hyperkube, it doesn't seem like we should block changes to it until we do...though it does seem like we should try to get some ASAP

+@brendandburns or @zmerlynn for a one-over

**Comment by erictune** [comment]
I'm on vacation this week (:house: :mouse:) and will take a look next week.

**Comment by brendandburns** [comment]
needs a rebase.

**Comment by mikeln** [comment]
Well, changing from debian:wheezy 85.04 MB to debian:jessie 125.2 MB obviously adds some size.  It looks like that change was made to allow usage of nsenter.

**Comment by mikeln** [comment]
ARRG! my bad. Not sure why it picked up other stuff.  This was all isolated.

**Comment by mikeln** [comment]
ok, fixed the git issue... looks like it will have to be reclassified XS by hand?

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Pull request merged**
