### PR TITLE
Make updateSnapshot more efficient in scheduler

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Before:
when we add/remove node, we'll mark  updateAllLists to true, that means we'll re-create all the fields, but then we'll still continue the calculating of other flags like `updateNodesHavePodsWithAffinity`, `updateNodesHavePodsWithRequiredAntiAffinity`, `updateUsedPVCSet`, this is not efficient.

Now:
1. when updateAllLists == true, we'll quick return
2. 
```
	if updateAllLists {
		cache.updateNodeInfoSnapshotList(nodeSnapshot)
	} else {
		if updateNodesHavePodsWithAffinity {
			cache.updatePodsWithAffinityAndRequiredAntiAffinityNodeInfoList(nodeSnapshot)
		} else if updateNodesHavePodsWithRequiredAntiAffinity {
			cache.updatePodsWithRequiredAntiAffinityNodeInfoList(nodeSnapshot)
		}
		if updateUsedPVCSet {
			cache.updateUsedPVCSet(nodeSnapshot)
		}
	}
```
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
cc @ahg-g who modified the codes in the file the most recently.

**Comment by ahg-g** [comment]
Before I review in detail, I have two questions:

1. This looks like a significant change to a critical path in the scheduler that in the past was the source of some bugs. This path has been stable with no issues for many releases, is this change really worth the risk?
2. What triggered looking at this piece of code? do you have profiles or perf tests showing that this logic performs poorly in practice?

**Comment by lance5890** [comment]
some clean with this PR https://github.com/kubernetes/kubernetes/pull/120511

**Comment by kerthcet** [comment]
close for now.

**Pull request closed without merging**
