### PR TITLE
Delete the content about priorities.go.

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

Delete the content about priorities.go.

Thanks!

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37542)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by tanshanshan** [comment]
@smarterclayton   Could you tell me how to eliminate the 'do not merge' label  , thanks,

**Comment by smarterclayton** [comment]
These docs have been moved out of tree to kubernetes/community (I think).  There was an email on kubernetes-dev just the other day.  You'll need to reopen this PR there.

**Comment by tanshanshan** [comment]
@smarterclayton 
I present  the same pr [kubernetes/community#133](https://github.com/kubernetes/community/pull/133)

Thanks

**Pull request closed without merging**
