### PR TITLE
Patch release-0.8: Remove image GC.

### LINKED ISSUE #3617: docker btrfs issue caused by kubelet
I've been struggling on a problem over the past week, that a few pods always fail to run.

When I tried to manually run one of those, I got:
```
core@ip-10-237-218-56 ~ $ docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Error pulling image (0.12.1-2.1.5) from kiyoto/fluentd, Driver btrfs failed to get image parent aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: stat /var/lib/docker/btrfs/subvolumes/aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: no such file or directory dd2b67a526996b30: no such file or directory
3c20e07c38ce: Error downloading dependent layers
FATA[0058] Error pulling image (0.12.1-2.1.5) from kiyoto/fluentd, Driver btrfs failed to get image parent aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: stat /var/lib/docker/btrfs/subvolumes/aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: no such file or directory
```
I could succesfully run the image on another os with different docker version and different backend filesystem, so I did many tests, to conclude that the problem is neither with btrfs, nor with docker, nor with coreos.
I could create another aws autoscaling group, reusing the same versions of those tools, but without kubernetes, and I could sucessfully run that image there as well.
I then removed all components from my cloudformation template, and readded them progressively, to notice that pulling this image only fails when the kubelet is running.

I then tried to run the kubelet with different options, but the bare minimum `/opt/bin/kubelet --etcd_servers=http://127.0.0.1:4001` is enough for docker to fail on that image. Looking at the traceback:
```
core@ip-10-237-218-56 ~ $ /opt/bin/kubelet --etcd_servers=http://127.0.0.1:4001
I0120 02:24:41.867394   28317 node.go:52] Connecting to docker on unix:///var/run/docker.sock
I0120 02:24:41.867526   28317 util.go:128] No api servers specified.
I0120 02:24:41.878683   28317 standalone.go:205] Watching for etcd configs at [http://127.0.0.1:4001]
I0120 02:24:41.885479   28317 plugins.go:56] Registering credential provider: .dockercfg
I0120 02:24:41.885661   28317 logs.go:39] etcd DEBUG: get /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.885743   28317 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.885815   28317 logs.go:39] etcd DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false | method GET
I0120 02:24:41.885868   28317 event.go:92] Event(api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"ip-10-237-218-56.ec2.internal", UID:"ip-10-237-218-56.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): status: '', reason: 'starting' Starting kubelet.
I0120 02:24:41.928419   28317 logs.go:39] etcd DEBUG: recv.response.fromhttp://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.928492   28317 logs.go:39] etcd DEBUG: recv.success.http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.928564   28317 logs.go:39] etcd DEBUG: watch /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.928611   28317 logs.go:39] etcd DEBUG: get /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.928660   28317 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381
I0120 02:24:41.928695   28317 logs.go:39] etcd DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381 | method GET
I0120 02:24:41.929632   28317 logs.go:39] etcd DEBUG: recv.response.fromhttp://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381

core@ip-10-237-218-56 ~ $ curl http://127.0.0.1:4001/v2/keys/registry/nodes
{"errorCode":100,"message":"Key not found","cause":"/registry/nodes","index":3422}

core@ip-10-237-218-56 ~ $ curl http://127.0.0.1:4001/v2/keys/registry/
{"action":"get","node":{"key":"/registry","dir":true,"nodes":[{"key":"/registry/services","dir":true,"modifiedIndex":14,"createdIndex":14},{"key":"/registry/minions","dir":true,"modifiedIndex":37,"createdIndex":37}],"modifiedIndex":14,"createdIndex":14}}

core@ip-10-237-218-56 ~ $
```

Does kubelet try to query `registry/nodes` when only `registry/services` and `registry/minions` are available?
I still don't understand what does kubelet has to do with the btrfs error raised by docker, but the evidence is that everytime I stop kubelet, docker has no problem with the image:
```
core@ip-10-237-218-56 ~ $ sudo systemctl stop kube-kubelet
core@ip-10-237-218-56 ~ $ docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Download complete
511136ea3c5a: Download complete
36fd425d7d8a: Download complete
aaabd2b41e22: Download complete
3c20e07c38ce: Download complete
b6ef456c239c: Download complete
b045b0cd49ad: Download complete
7855c14973cc: Download complete
2a24c9b7a5f1: Download complete
c82cadc1856f: Download complete
f0f017241bb0: Download complete
146d795aeab9: Download complete
0f154b063a84: Download complete
c04060062646: Download complete
e1ebcc148e67: Download complete
197ad3ee39c6: Download complete
d8b6573c9c35: Download complete
643b35d35def: Download complete
f2e6d6ac3fb7: Download complete
Status: Downloaded newer image for kiyoto/fluentd:0.12.1-2.1.5
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
```

This issue is a blocker. Since I cannot get the cluster-side logging to work yet (#2918), I'm trying to have a temporary fluentd pod running for application-side logging at first.

Any suggestion?

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #3617,#3611, and #3393.

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @brendandburns

**Comment by dchen1107** [comment]
Since it is a patch to an official release, I am going to run e2e test before merge. Will do a self-merge for this one.

**Comment by brendandburns** [comment]
sgtm.

thanks

**Comment by dchen1107** [comment]
e2e passed:

2015/01/20 15:43:40 Passed tests: basic.sh[1/1] certs.sh[1/1] goe2e.sh[1/1] guestbook.sh[1/1] liveness.sh[1/1] monitoring.sh[1/1] pd.sh[1/1] private.sh[1/1] services.sh[1/1] update.sh[1/1]
2015/01/20 15:43:40 Flaky tests:
2015/01/20 15:43:40 Failed tests:
2015/01/20 15:43:40 Success!

**Pull request merged**
