### PR TITLE
re-register the Node if Node API object removed

### LINKED ISSUE #71398: Kubelet does not restart or reregister in response to removed Node API object
Once a kubelet has started up, if it's Node API object is removed, the kubelet perpetually attempts and fails to update the status on the now-missing Node object.

I would have expected it to do one of the following:
* exit after a period of time or number of retries
* re-register the Node object

/kind bug
/sig node

### PR DESCRIPTION
**Pull request by Pingan2017**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71398 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
One scenario is for StatefulSets. When there is a partition due to a node not responding, we need to delete the pods which have now entered an unknown state. The safe way to do is , delete the Node object and then we can be sure at most one semantics will never be violated. Automatic registration of the node by the kubelet when the node is not found might make that process completely un usable . See more here
https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/

@kubernetes/sig-apps-pr-reviews

**Comment by krmayankk** [comment]
@liggitt @justinsb FYI

**Comment by Pingan2017** [comment]
Maybe it is really not a good idea to re-register the node automatically. :smile:

**Comment by justinsb** [comment]
By all means keep the PR open @Pingan2017 !  We just need to figure out when to register and when not to :-)

**Comment by Pingan2017** [comment]
> By all means keep the PR open @Pingan2017 ! We just need to figure out when to register and when not to :-)

OK! :smile:

**Comment by matthyx** [comment]
Hi @Pingan2017 what's the status of this? Looks like both the issue and the PR have been closed due to inactivity...

**Pull request closed without merging**
