### PR TITLE
[kubeadm]: Bump CoreDNS version to 1.6.7

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Bumps CoreDNS version to 1.6.7
Also updates the [migration library to 1.0.6](https://github.com/coredns/corefile-migration/releases/tag/v1.0.6) which supports coredns v1.6.7

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Kubeadm now includes CoreDNS version 1.6.7
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
See testing-ops for the SIG node e2e test failure, not specific to this PR

**Comment by neolit123** [comment]
thanks
/priority important-longterm
/lgtm
/approve

/retest

**Comment by gjtempleton** [comment]
Worth noting that `1.6.6` includes a metrics regression in the `cache` plugin which we make use of: https://github.com/coredns/coredns/issues/3577 (Users would see `coredns_cache_misses_total` disappearing, potentially causing alerts etc.)

As such I think this'll either need to come with a warning or jump to 1.6.7 instead as it's resolved there: https://github.com/coredns/coredns/pull/3578

**Comment by neolit123** [comment]
@rajansandeep do we want this for 1.18?

**Comment by rajansandeep** [comment]
@neolit123 yes, although I will be updating this PR to have CoreDNS 1.6.7

**Comment by neolit123** [comment]
@rajansandeep ok, thanks.
FYI, code freeze is the 5th of March.

**Comment by neolit123** [comment]
/lgtm
/assign @liggitt 

@rajansandeep should kube-up be bumped as well in a separate PR?

**Comment by rajansandeep** [comment]
> @rajansandeep should kube-up be bumped as well in a separate PR?

Yes, I'll be updating https://github.com/kubernetes/kubernetes/pull/86259 for kube-up

**Comment by liggitt** [comment]
vendor changes lgtm
/approve

**Comment by BenTheElder** [comment]
our favorite test output
Feb 24 23:34:49.035: Unexpected error: <*errors.errorString |
0xc0000dffa0>: { s: "timed out waiting for the condition", } timed out
waiting for the condition occurred /retest

**Pull request merged**
