### PR TITLE
Update default generation for example packages

### PR DESCRIPTION
**Pull request by liggitt**
the example API packages were missing default generation tags, which meant that calls to the generated defaults were not satisfied in cross-build, which regenerates all files

follow-up to https://github.com/kubernetes/kubernetes/pull/62472

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
/test pull-kubernetes-cross
Running a full cross build

**Comment by ixdy** [comment]
to be clear, this wasn't a bazel issue, but a `make release` issue - we explicitly exclude all `zz_generated.*` files from the dockerized build container, and `make generated_files` wasn't building these generated files, so builds failed.

**Comment by cblecker** [comment]
/hold cancel

Tests are green, and manual cross build succeeded.

**Comment by ixdy** [comment]
does
/priority failing-test
still work?

**Comment by cblecker** [comment]
Adding `queue/fix`. A batch just merged, so we aren't invalidating anything.

**Pull request merged**
