### PR TITLE
make NEG tests more resilient to API failures and add more failure lo…

### PR DESCRIPTION
**Pull request by freehan**
Try to fix flaky NEG test by 
- Add resilience in verification
- Add more logging on the exact verification error. 

```release-note
None
```

### CODE REVIEW

**Comment by freehan** [comment]
FYI @spencerhance @cadmuxe 
This should help to eleminate some of the recent flakes. This set of tests will be disabled once ingress/NEG tests are fully ported to ingress-gce

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by freehan** [comment]
make golint happy

**Pull request merged**
