### PR TITLE
Add unit tests for interactive edit command

### PR DESCRIPTION
**Pull request by liggitt**
Before updating edit to use unstructured objects and use generic JSON patching, we need better test coverage of the existing paths. This adds unit tests for the interactive edit scenarios. 

This PR adds:
* Simple framework for recording tests for interactive edit:
  * record.go is a tiny test server that records editor and API inputs as test expectations, and editor and API outputs as playback stubs
  * record_editor.sh is a shell script that sends the before/after of an interactive `vi` edit to the test server
  * record_testcase.sh (see README) starts up the test server, sets up a kubeconfig to proxy to the test server, sets EDITOR to invoke record_editor.sh, then opens a shell that lets you use `kubectl edit` normally
* Adds test cases for the following scenarios:
  - [x] no-op edit (open and close without making changes)
  - [x] try to edit a missing object
  - [x] edit single item successfully
  - [x] edit list of items successfully
  - [x] edit a single item, submit with an error, re-edit, submit fixed successfully
  - [x] edit list of items, submit some with errors and some good, re-edit errors, submit fixed
  - [x] edit trying to change immutable things like name/version/kind, ensure preconditions prevent submission
  - [x] edit in "create mode" successfully (`kubectl create -f ... --edit`)
  - [x] edit in "create mode" introducing errors (`kubectl create -f ... --edit`)
* Fixes a bug with edit printing errors to stdout (caught when testing stdout/stderr against expected output)

### CODE REVIEW

**Comment by pwittrock** [comment]
@liggitt Seems like some of the failures aren't flakes.  Mind taking a look?

**Comment by liggitt** [comment]
> @liggitt Seems like some of the failures aren't flakes. Mind taking a look?

yeah, still WIP

**Comment by pwittrock** [comment]
Ah yes I see.  Thanks.

**Comment by liggitt** [comment]
@jessfraz can you take a look?

**Comment by jessfraz** [comment]
This seems overall sane to me, LGTM plus its all tests :)

**Comment by pwittrock** [comment]
@jessfraz thanks!

**Pull request merged**
