### PR TITLE
Fix golint failures in pkg/registry/authorization/

### PR DESCRIPTION
**Pull request by CaoDonghui123**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:
Fix golint failures :
pkg/registry/authorization/localsubjectaccessreview
pkg/registry/authorization/rest
pkg/registry/authorization/selfsubjectaccessreview
pkg/registry/authorization/subjectaccessreview

**Which issue(s) this PR fixes**:

Part of #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dougsland** [comment]
looks sane
/ok-to-test
/lgtm

**Comment by CaoDonghui123** [comment]
@lavalamp  @nikhiljindal  Could you please take a look?

**Comment by CaoDonghui123** [comment]
Can someone please review, it's a tiny commit.Thanks

**Pull request closed without merging**
