### PR TITLE
Add some docs about the missing node e2e scheduling

### PR DESCRIPTION
**Pull request by sttts**
---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31102)

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot node test this issue: #IGNORE

**Comment by sttts** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by Random-Liu** [comment]
@sttts, just saw this, sorry for the delay.

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
