### PR TITLE
Explicit bool()

### PR DESCRIPTION
**Pull request by zhengguoyong**
i think it better to add a bool type here :)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Doesn't seem necessary, but no harm adding.

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
Thanks for the PR, but I don't think we should do this.  It's not consistent with lots of other code and it's not common practice.

`x := (y == z) is a well-understood idiom.

**Comment by zhengguoyong** [comment]
thanks,
the file buider.go i fixed has no (), so i think i can make another PR to fix it. 
 @thockin

**Pull request closed without merging**
