### PR TITLE
Refactoring: Changed deprecated ioutil functions in favour for os/io 

### PR DESCRIPTION
**Pull request by holgerson97**
#### What type of PR is this?
/kind deprecation
/kind cleanup

#### What this PR does / why we need it:
In this PR deprecated functions are going to removed and exchanged.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by xuzhenglun — COMMENTED** [review]
nice job to remove deprecated `io/ioutil` pkg.  but I can see there are still widely used in other places, would you mind to find some more place like this and do a fully clean up?

**Comment by nilekhc** [comment]
Thanks for your pull request.  However, [trivial](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) changes like this should be avoided as we have very limited resources to handle reviews and approvals.  Focus efforts on fixes that have meaningful impact on end users (bugs, docs, etc).

/close

**Pull request closed without merging**
