### PR TITLE
Make it possible to use kube-cross as non-root

### PR DESCRIPTION
**Pull request by thockin**
The extra TMPDIR was not writable except as root.  This is not the only fix
needed for this goal, but is necessary.

I have not pushed the new-version image

### CODE REVIEW

**Comment by luxas** [comment]
@thockin You need to update `build/common.sh` as well before the build system will use the new image.

**Comment by smarterclayton** [comment]
LGTM, do you need to push the image before merge?

**Comment by luxas** [comment]
Yes, @thockin have to update `common.sh` and push the image before LGTM

**Comment by thockin** [comment]
updated.  I will build and push

**Comment by thockin** [comment]
hmm, are there instructions on building this properly?

**Comment by luxas** [comment]
I don't know if it's documented, actually

**Comment by thockin** [comment]
I think 'make' will do it, but there are no docs on procedures or testing

**Comment by luxas** [comment]
Ah, I thought you meant if the `kube-cross` update method was documented, and I don't think that.

But yes,  there are build documentation.
Running `make release` will mostly do it.

BTW, you don't seem to have pushed the image as CI failed

**Comment by luxas** [comment]
I think the build documentation is here: https://github.com/kubernetes/kubernetes/tree/master/build

**Comment by thockin** [comment]
I am rebuilding the image right now - it is not a fast process, thanks to docker layering.

**Comment by thockin** [comment]
image is built and pushed

**Comment by luxas** [comment]
Okay, great. Lets merge it when green

**Pull request merged**
