### PR TITLE
Automated cherry pick of #65920: pause image should be arch agnostic

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #65920 on release-1.11.

#65920: pause image should be arch agnostic

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubeadm/issues/958

**Review by luxas — APPROVED** [review]
Thanks for the cherrypick!

/lgtm
/approve
/kind bug
/priority important-soon
/status approved-for-milestone
/assign @foxish
/sig cluster-lifecycle
/milestone v1.11

**Pull request merged**
