### PR TITLE
Remove the PersistentVolumeLabel Admission Controller

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubernetes/issues/52617

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove the PersistentVolumeLabel Admission Controller
```

### CODE REVIEW

**Comment by wackxu** [comment]
I  do not know it is time to remove it, we can hold it until we can do it.

**Comment by jberkus** [comment]
Please add this PR to the 1.10 milestone if it is targeted at 1.10, per its attached issue.  Please add other appropriate labels.  Thanks.

**Comment by deads2k** [comment]
@kubernetes/sig-storage-api-reviews 
@childsb @eparis

**Comment by msau42** [comment]
We cannot remove this until gce is migrated to use the new cloud controller.  @cheftako

**Comment by wackxu** [comment]
@msau42 @cheftako So we can hold this until  gce is migrated to use the new cloud controller.

**Comment by dims** [comment]
@wackxu Can you please rebase?

@msau42 @cheftako can we do this in 1.12?

/milestone v1.12

**Comment by msau42** [comment]
I spoke with @cheftako and he said that gce and gke migration to use cloud controller manager by default is still not ready, and may not be for a few more releases.

**Comment by dims** [comment]
/milestone v1.13

Let's move it to next milestone per @msau42 and @cheftako input

**Comment by shubheksha** [comment]
ping @msau42, @cheftako - is this on track for 1.13 or does it have to be pushed?

**Comment by msau42** [comment]
I believe this is still not ready to be removed yet.  @cheftako do you have an estimate on which release we will be ready to remove this?  I think this will also not just depend on gce cloud provider migration, but also aws and azure.

**Comment by shubheksha** [comment]
@msau42, thanks!
@dims/ @nikopen - can we stop tracking this for 1.13 atm?

**Comment by dims** [comment]
yep @shubheksha

**Comment by luxas** [comment]
ping @kubernetes/cloud-provider-gcp-maintainers @kubernetes/sig-cloud-provider-feature-requests 
Can we proceed with this now please?

**Comment by cheftako** [comment]
For those interested in the cloud provider status it may be worth looking at the "Kubernetes SIG Cloud Provider Newsletter" (https://docs.google.com/document/d/1ZsPtRz2glAWH81MP0-9X8tG7sRWYuZPbj0VvZVETa2U/edit?ts=5be04aaa)

**Comment by luxas** [comment]
/remove-lifecycle rotten
/lifecycle frozen

This is still relevant, for a future release

**Pull request closed without merging**
