### PR TITLE
cleanup: simplified some code in /kubectl/pkg

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- use iota to create constants
- use efficient strings.EqualFold(s1, s2) to compare string
- replace manual trimming with strings.TrimPrefix
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
/ok-to-test
Thanks!

**Comment by HecarimV** [comment]
PTAL @KnVerey

**Pull request closed without merging**
