### PR TITLE
Automated cherry pick of #16221

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #16221 upstream release 1.1

cc @bgrant0607 @bprashanth @thockin

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by janetkuo** [comment]
`[Fail] Deployment [It] deployment should delete old pods and create new ones` looks like a flake. 
@k8s-bot test this

**Comment by krousey** [comment]
@thockin @yujuhong merge bot is sad. Is this a good/safe candidate for a manual merge?

**Comment by bprashanth** [comment]
@krousey sad as in just not working (because it looks like all tests passed, or was a failure occluded somehow)? if so, yes it's safe to merge manually.

**Comment by krousey** [comment]
@bprashanth Not making progress due to a flake in e2e on master.

**Pull request merged**
