### PR TITLE
Add KernelDeadlock condition to hollow NPD

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/44701

/cc @wojtek-t @gmarek

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
ref: kubernetes/test-infra#2932

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
