### PR TITLE
Feature gates are being removed: WindowsGMSA and WindowsRunAsUserName

### PR DESCRIPTION
**Pull request by mrmassis**
Feature gates are being removed: WindowsGMSA and WindowsRunAsUserName

### CODE REVIEW

**Comment by marosset** [comment]
@mrmassis We just want this PR to remove the feature gates, not the actual fields in the various APIs.
Please revert the changes to staging/src/k8s.io/api/core/v1/generated.proto, staging/src/k8s.io/api/core/v1/types.go, and the other generated files.

**Comment by mrmassis** [comment]
Could you send me a list of files that i need revert?

**Comment by mrmassis** [comment]
This ocourred because the rebase
how i revert the changes?

**Comment by ehashman** [comment]
/close

in favour of #96531

**Pull request closed without merging**
