### PR TITLE
Deflake TestListResourceVersion0

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

Fixes https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=TestListResourceVersion0

```release-note
NONE
```

/cc @jpbetz @wojtek-t 
/sig api-machinery

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

/hold
@liggitt - feel free to hold cancel, but I'm wondering what if we know why it started flaking couple days ago given it wasn't before?

**Comment by liggitt** [comment]
that's a good question... the PR flake rate looks much more suspect: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-07-01&pr=1&test=TestListResourceVersion0

**Comment by liggitt** [comment]
first recent flake was observed in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91505/pull-kubernetes-integration/1276457193071185921 on https://github.com/kubernetes/kubernetes/pull/91505

**Comment by wojtek-t** [comment]
> that's a good question... the PR flake rate looks much more suspect: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-07-01&pr=1&test=TestListResourceVersion0

to clarify: this is absolutely a valid fix; I'm just wondering why we weren't observing those flakes before.
My guess as things that in theory might have affected it are:
https://github.com/kubernetes/kubernetes/pull/91505 [as something that was touching the semantic]
https://github.com/kubernetes/kubernetes/pull/92503 [as something that may make processing inside watchcache a bit slower]

I think that the later may cause those infrequent flakes between 6/26 and 6/29. But I don't have any hypothesis what happened around 6/29 afternoon...

**Comment by liggitt** [comment]
yeah, https://github.com/kubernetes/kubernetes/pull/91505 merged on 6/27

**Comment by liggitt** [comment]
I looked through commits around 6/29 and don't see anything relevant. I'm going to go with the theory that our often-seen resource-constrained CI nodes got hit with CPU use (which we've seen many times) and made this worse starting on the 29th.

/hold cancel

**Pull request merged**
