### PR TITLE
kubeadm: added tests for preflight checks

### PR DESCRIPTION
**Pull request by dmmcquay**
**What this PR does / why we need it**: There hadn't been much care to add more unit tests as more preflight checks were added. I added tests that increased coverage from ~9% to ~71%

Adding unit tests is a WIP from https://github.com/kubernetes/kubernetes/issues/34136

**Special notes for your reviewer**: /cc @luxas @pires 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dmmcquay** [comment]
@k8s-bot bazel test this

**Comment by dmmcquay** [comment]
@k8s-bot bazel test this

**Comment by dmmcquay** [comment]
@k8s-bot bazel test this

**Comment by dmmcquay** [comment]
@luxas do you have any idea what is happening with the jenkins bazel build test on this PR?

**Comment by luxas** [comment]
@k8s-bot bazel test this

**Comment by dmmcquay** [comment]
@luxas do you have any idea why the bazel build keeps failing?

**Comment by luxas** [comment]
@dmmcquay No, I don't. Very strange...

cc @mikedanese 

@k8s-bot bazel test this

**Comment by luxas** [comment]
@dmmcquay Is this rebased to current master? Maybe that can be an issue?

**Comment by dmmcquay** [comment]
@luxas I rebased, but there weren't any conflicts. Let us see what happens.

**Comment by dmmcquay** [comment]
@luxas what do you suggest we do for this PR.  I tried to reach out on slack to see if anyone knew what was going on but I didn't get a response.

/cc @pires @mikedanese

**Comment by pires** [comment]
@k8s-bot bazel test this

**Comment by dmmcquay** [comment]
@ixdy Do you have an idea what is happening here with Jenkins bazel build details link giving an internal server error?

**Comment by ixdy** [comment]
The output XML is bad, though I don't understand how: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/40878/pull-kubernetes-bazel/4360/artifacts/junit_bazel.xml

**Comment by ixdy** [comment]
Ah, it looks like the ANSI color escape codes are causing the issue. Line 3 is 0x5b 0x1b 0x3b 0x30 0x37 0x33, i.e. [`ESC`;073.

Probably a bug in `test-infra/images/pull_kubernetes_bazel/coalesce.py`, cc @spxtr @rmmh

**Comment by ixdy** [comment]
@k8s-bot bazel test this

**Comment by ixdy** [comment]
OK, Gubernator issue has been fixed. @dmmcquay this looks like a legitimate test failure now.

**Comment by dmmcquay** [comment]
@k8s-bot cvm gce e2e test this

**Comment by dmmcquay** [comment]
@luxas this is finally passing all the tests. Can I get your lgtm?

**Review by pires — APPROVED** [review]

**Comment by dmmcquay** [comment]
@luxas can you take a look please?

**Comment by luxas** [comment]
/approve

Applieg @pires /lgtm

**Pull request merged**
