### PR TITLE
Remove unsupported Windows SAC images from pause image

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Removes Windows SAC releases are no longer supported by Microsoft. This removes the support in k8s pause image and reduces storage space in registry for newer versions of pause image.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Windows Pause no longer has support for SAC releases 1903, 1909, 2004. Windows image support is now Ltcs 2019 (1809), 20H2, LTSC 2022
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows

/cc @claudiubelu @marosset @ravisantoshgudimetla

### CODE REVIEW

**Comment by jsturtevant** [comment]
pod pending timed out
/retest

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

Thank you @jsturtevant

**Comment by marosset** [comment]
Do we need to wait for https://github.com/kubernetes/test-infra/pull/24689 to merge for this PR too?

**Comment by claudiubelu** [comment]
Looking at it again, I think we need to bump the pause image version as well, since 3.6 was already promoted. Additionally, we should add a note about these changes into the pause image Change logs: https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md

> Do we need to wait for [kubernetes/test-infra#24689](https://github.com/kubernetes/test-infra/pull/24689) to merge for this PR too?

I don't think so. The test jobs are running using promoted images. If this gets merged, the postsubmit job will build the image and push it to the staging registry, it's not automatically promoted.

**Comment by dims** [comment]
Yes, please bump to 3.7 https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile#L20

**Comment by dims** [comment]
+1 to use what @claudiubelu said as the rule of thumb, if the TAG has a version that is promoted to the public repository then we need to bump the TAG for any changes that changes the payload of the image.

**Comment by marosset** [comment]
> Yes, please bump to 3.7 https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile#L20

3.7 or 3.6.1?

**Comment by marosset** [comment]
It seems like we are not being consistent w/ pause image versioning.
Sometimes we've bumped the minor version when adding support for new flavors of Windows (3.3 -> 3.4) and other times we've just bumped the patch version (3.4 -> 3.4.1).

**Comment by jsturtevant** [comment]
3.7 makes sense to me, it is a breaking change as we are dropping support not adding additional

**Comment by marosset** [comment]
> 3.7 makes sense to me, it is a breaking change as we are dropping support not adding additional

Works for me!

**Comment by claudiubelu** [comment]
3.7 works for me as well. Don't forget to add a note for the 3.7 image in the pause image's Changelog as well: https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md

Also, in your PR message, in the ``Does this PR introduce a user-facing change?`` Section, you mention ``Ltcs`` images, but it's actually ``LTSC``. AFAIK that section ends up in the release notes, so we should make sure they're correct.

**Comment by jsturtevant** [comment]
> 3.7 works for me as well. Don't forget to add a note for the 3.7 image in the pause image's Changelog as well: https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md
> 
> Also, in your PR message, in the `Does this PR introduce a user-facing change?` Section, you mention `Ltcs` images, but it's actually `LTSC`. AFAIK that section ends up in the release notes, so we should make sure they're correct.

updated, including the Release note section

**Review by marosset — APPROVED** [review]
LGTM

**Pull request merged**
