### PR TITLE
Rename "gcloud-update" jobs to "daily-maintenace" and add Docker cleanup

### PR DESCRIPTION
**Pull request by ixdy**
I'm guessing Jenkins Job Builder won't delete the old job, and we'll need to do that manually?

@spxtr @fejta

### CODE REVIEW

**Comment by ixdy** [comment]
Updated the cleanup to remove both `exited` and `dead` containers.

**Comment by spxtr** [comment]
Looks good, and yes we'll need to delete the old jobs manually, on both post-commit and PR Jenkins.

**Comment by spxtr** [comment]
Lets merge #24068 first :)

**Comment by fejta** [comment]
How about we keep the old name until we automatically expunge jobs not in source control?

**Comment by ixdy** [comment]
What is the motivation for only changing the name later? So we can test the auto-expunger?

**Comment by fejta** [comment]
Our system doesn't presently support renaming jobs very well since it leaves the old ones around, which to me suggests the path with the least probability of error is to leave the name alone until we add this functionality.

**Comment by ixdy** [comment]
Well, IIRC submitting this will create new jobs (but not delete the old ones), so the testinfra on-call will need to clean up the old jobs. Since that's now @spxtr, I'll let him make the call. :)

**Comment by spxtr** [comment]
I don't mind deleting old jobs, it's just a few clicks. Once PR Jenkins is entirely source controlled we'll turn on the flag that deletes untracked jobs.

**Comment by fejta** [comment]
SGTM, but five bucks says we find this job mistakenly left around in a month.

**Comment by spxtr** [comment]
Lets see the YAML diff. @k8s-bot unit test this issue: #IGNORE

**Comment by ixdy** [comment]
We'll probably want to also get this one merged before we re-enable dockerized e2e.

**Comment by spxtr** [comment]
LGTM

**Comment by spxtr** [comment]
> SGTM, but five bucks says we find this job mistakenly left around in a month (humans are naturally error prone).

@fejta I already deleted them :D

**Pull request merged**
