### PR TITLE
Abstract some duplicated code in the iptables proxier

### PR DESCRIPTION
**Pull request by danwinship**
Reorganizes the iptables proxier code so we only have the list of "-A FOO -j KUBE-BAR" rules in one place rather than duplicating the same list in multiple places. Split out from #56164 for ease of review/merging.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
LGTM, THANKS!

BTW, I think IPVS proxier needs a similar cleanup and I am willing to send another PR for IPVS proxier when this PR gets in.

**Comment by danwinship** [comment]
@thockin poke now that everyone's back from holidays...

**Pull request merged**
