### PR TITLE
kubeadm: Add the option to cleaning up all container images for reset

### PR DESCRIPTION
**Pull request by CaffeeLake**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently, "kubeadm reset" does not provide an option to delete container images, so the user must manually delete the images.

This PR provides an option to cleaning up all container images.

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: add the flag "--cleanup-images" for "kubeadm reset". It will cleaning up all container images. The flag is off by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Signed-off-by: CaffeeLake <PascalCoffeeLake@gmail.com>

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
hi, this would delete all images even if the user is using some of them for non-kubeadm tasks. kubeadm only stops k8s containers and not all of them.

can you elaborate why this is needed? users can always call the command on demand.

**Comment by CaffeeLake** [comment]
@neolit123 
Thank you for your review.
You are right, there may not be a demand for it, considering that it can be deleted from the command line.
We will close this PR and open a new PR to remove images for containers that are deleted by "kubeadm reset".

**Comment by neolit123** [comment]
> We will close this PR and open a new PR to remove images for containers that are deleted by "kubeadm reset".

this seems better but there has been no demand for it.
actually i think its problematic because reset has no --config option and it does not know what images to delete.

/cc @chendave

**Comment by CaffeeLake** [comment]
@neolit123, One question.
Since "kubeadm reset" is using "crictl -D=false pods -q" and containers that are not managed by Kubernetes are being deleted?
If not, "crictl -D=false images -q" should remove the "Kubernetes-managed container" images.

https://github.com/kubernetes/kubernetes/blob/4d2128b5236ff3c1d621f6ceb6add16205ff3450/cmd/kubeadm/app/util/runtime/runtime.go#L87

**Comment by neolit123** [comment]
> Since "kubeadm reset" is using "crictl -D=false pods -q" and containers that are not managed by Kubernetes containers are being deleted?

isn't 'pods' ensuring its deleting only containers in k8s pods?

**Comment by chendave** [comment]
> actually i think its problematic because reset has no --config option and it does not know what images to delete. i guess it can fetch the clusterconfig but not sure its worth it.

clusterconfig should have the version available, the build for the image list should be similar with the image pulling in the phase of preflight. I thinks it's doable.

I am fine to cleanup those images pulled by kubeadm,  since it sound like a debt from kubeadm which pulled images firstly. But I want to echo @neolit123 's concerns, how do you know those images are pulled by kubeadm instead of by something else? and do you have seen any problem without the feature? It would be help to justify a change like this?

**Pull request closed without merging**
