### PR TITLE
Increase the node condition status change observation time out to 5 minutes.

### PR DESCRIPTION
**Pull request by madhusudancs**
1 minute is too short.

### CODE REVIEW

**Comment by madhusudancs** [comment]
cc @davidopp

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/17495

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
