### PR TITLE
Promote spiffxp to approver for cluster/

### PR DESCRIPTION
**Pull request by spiffxp**
I've been a reviewer for ~6 months, I think it's time I move on to
approver. My goal is to get more review bandwidth on this dir, and IMO
at least some of it should be coming from sig-testing.

Since I'm going up I'd like to mentor someone behind and am nominating
Katharine as a reviewer

/release-note-none
/kind cleanup
/sig testing
/sig cluster-lifecycle

### CODE REVIEW

**Comment by spiffxp** [comment]
/release-note-none
Is this not picked up in the description?

**Review by BenTheElder — APPROVED** [review]
/lgtm
thank you!

**Pull request merged**
