### PR TITLE
fix: update deployment e2e tests

### LINKED ISSUE #113259: e2e apps: deployment test not working as intended
### What happened?

I started added missing error checks. When adding error checking to this call here, the test started to fail:
https://github.com/kubernetes/kubernetes/blob/e876d63ec2c9ae6b6af9318e909c21d16e90d94e/test/e2e/apps/deployment.go#L402

```
Deployment.apps "test-deployment" is invalid: status.availableReplicas: Invalid value: 2: cannot be greater than readyReplicas
```

### What did you expect to happen?

The test should have continued to work when checking the error.

### How can we reproduce it (as minimally and precisely as possible)?

```
_, err = dc.Resource(deploymentResource).Namespace(testNamespaceName).Patch(context.TODO, testDeploymentName, types.StrategicMergePatchType, []byte(deploymentStatusPatch), metav1.PatchOptions{}, "status")
framework.ExpectNoError(err)
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
master
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by AhmedGrati**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Fix failing tests.

#### Which issue(s) this PR fixes:

Fixes #113259

ping @pohly @soltysh

### CODE REVIEW

**Comment by pohly** [comment]
Please add an explanation why this fixes the problem, ideally in the commit message.

Sometimes a change makes something work, but only via some side effect and the real solution is something else. Therefore the "why this change" is important.

**Comment by AhmedGrati** [comment]
@pohly Done.

Added to that, I executed the whole conformance test, and it passed successfully. I ran:
```go
go test -v ./test/e2e --kubeconfig=$KUBECONFIG  --ginkgo.focus='should run the lifecycle of a Deployment'
```

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Thanks for the commit update. I'll help the next person looking at this test.

**Pull request merged**
