### PR TITLE
kubeadm: Remove the validate phase as it's not needed

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

This validation code was added in v1.4 as a way to remove flakiness between deploying the control plane in Static Pods and deploying kube-discovery as a Deployment.

That isn't the case anymore and we're not experiencing such flakiness, as we're using other methods like checking `/healthz` to determine a healthy control plane before proceeding.

https://github.com/kubernetes/kubernetes/pull/43881 removed this logic from `kubeadm init` to having it as a phase. But that phase isn't needed or used in any way, so now I'm removing it here.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Targets v1.8

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @timothysc @mikedanese

### CODE REVIEW

**Comment by mikedanese** [comment]
This seem like it is still useful. Validating that a cluster deployed correctly seems like a useful phase e.g. something like this:

https://github.com/kubernetes/kubernetes/blob/master/cluster/validate-cluster.sh

Is there something wrong with the current implementation?

**Comment by luxas** [comment]
I think it doesn't add any value really as-is, so better to cleanup.
I'd be very open to a `validate` subcommand though, that would actually test something, like that the network is working, or run e2e tests or the similar.

Basically what we talked about at the Kubernetes Dev Summit 2016, having different layers of smoke/e2e tests as a subcommand of kubeadm. I'm gonna open an issue about that, but in that case I think it should be a top-level command, not a phase command.

@mikedanese Sounds reasonable?

**Comment by timothysc** [comment]
> I think it doesn't add any value really as-is 

>I'd be very open to a validate subcommand though, that would actually test something, like that the network is working, or run e2e tests or the similar.

I think having a meaningful validation step is a good thing to ensure the desired state is reached before moving along seems legit.  

If the code isn't currently doing that, then +1 to remove with a issue link for a mo' betta validation step.

**Comment by luxas** [comment]
@mikedanese Can I get your approval for this as well?
We've made it a new-contributor-issue to add a decent validation phase (https://github.com/kubernetes/kubeadm/issues/313)

**Comment by mikedanese** [comment]
Please open an issue to add a validation phase that actually validates what we want to validate.

/lgtm

**Comment by luxas** [comment]
> Please open an issue to add a validation phase that actually validates what we want to validate

@mikedanese Here it is: https://github.com/kubernetes/kubeadm/issues/313

**Comment by luxas** [comment]
Rebased

**Pull request merged**
