### PR TITLE
Automated cherry pick of #76573: refactor detach azure disk retry operation

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #76573 on release-1.14.

#76573: refactor detach azure disk retry operation

### CODE REVIEW

**Comment by andrewsykim** [comment]
Is this a bug fix or an optimization with retry logic?

**Comment by andyzhangx** [comment]
@andrewsykim the original retry way hold the lock for a very long time, that would cause some unexpected issue. I would say it's a bug fix, thanks.

**Comment by andrewsykim** [comment]
Thanks @andyzhangx 

/approve

**Pull request merged**
