### PR TITLE
Image promoter: Reenable Windows test image building

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind bug
/kind cleanup

/sig windows
/sig testing

**What this PR does / why we need it**:

The build times are a bit high for the image builder (~50 minutes), and it will a bit more when Windows support will be added to the other test images. This commit changes the ``machineType`` to ``N1_HIGHCPU_8``.

Reenables Windows test image building. Added ``DOCKER_CERT_BASE_PATH`` (default value: ``$HOME``), which will contain the path where the certificates needed for Remote Docker Connection can be found.

If a ``REMOTE_DOCKER_URL`` was not set for a particular OS version, exclude that image from the
manifest list. This fixes an issue where, if ``REMOTE_DOCKER_URL`` was not set for Windows Server 1909, the Windows were completely excluded from the manifest list, including for Windows Server 1809 and 1903 which could have been built and pushed.

Sets ``test-webserver`` as the default CMD for ``kitten`` and ``nautilus``. Since they are now based on ``agnhost``, they should be set to run ``test-webserver`` to maintain previous behaviour.

Bumps the ``agnhost`` version to 2.13, as 2.12 has already been promoted. 2.13 will contain Windows support.

Adds Windows support for the ``kitten`` and ``nautilus`` images, so they can promoted together with ``agnhost`` (they were not previously promoted).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by marosset** [comment]
milestone v1.19

**Comment by spiffxp** [comment]
/skip pull-kubernetes-node-e2e-containerd 
ref: https://github.com/kubernetes/kubernetes/issues/89847

**Comment by spiffxp** [comment]
/approve
This seems ok, but I'd like a second pair of eyes on this

/assign @Katharine @fejta 
I'd like an /lgtm from one of you

**Review by fejta — COMMENTED** [review]
Can we get OWNERS in these images? For example,

https://github.com/kubernetes/kubernetes/tree/291527c387f07c3eecae030e48f9bb5ff8254d85/test/images/agnhost

**Comment by spiffxp** [comment]
/override pull-kubernetes-node-e2e-containerd
ref: #89847

**Comment by claudiubelu** [comment]
> 
> 
> Can we get OWNERS in these images? For example,
> 
> https://github.com/kubernetes/kubernetes/tree/291527c387f07c3eecae030e48f9bb5ff8254d85/test/images/agnhost

You mean in the agnhost image, or all of them? Sure, but there those images did not have any OWNER files in them in the first place. Who should the owners be? People who contributed the most to them? And since ~20 images have been centralized into agnhost, I assume that we could add an OWNER file per agnhost subcommand (e.g.: the netexec subcommand OWNERS should be the netxec image OWNERS).

In any case, we could do that in a separate PR, if we're going to add an OWNER file for every image.

**Comment by fejta** [comment]
I do not know anything about these images.
* I'll approve a PR that adds owners to the images.
* I'll approve a PR that both adds owners and improvements to images.
* I cannot approve a PR that only adds improvements to unowned images.

**Comment by claudiubelu** [comment]
@jasonrichardsmith      

> 
> 
> Can we get OWNERS in these images? For example,
> 
> https://github.com/kubernetes/kubernetes/tree/291527c387f07c3eecae030e48f9bb5ff8254d85/test/images/agnhost

Well, I hope this is what you wanted. :) https://github.com/kubernetes/kubernetes/pull/90062

**Comment by jasonrichardsmith** [comment]
@claudiubelu I think you meant to tag @fejta .

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu I think you meant to tag @fejta .

Oups! Sorry, my bad.

**Comment by claudiubelu** [comment]
@mkumatag Please give your ok that you are willing to be the approvers for the nautilus and kitten images.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

I'd love to see multiple owners but this is much better than before, thanks!

**Pull request merged**
