### PR TITLE
Added a new test case for UpdateNewNodeOutOfDiskStatus.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixed part of #40780

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by dashpole** [comment]
just as a heads up @gyliu513, the flag that enables triggering of OutOfDisk is disabled by default in 1.7, and we will be removing the OutOfDisk condition, and the disk manager entirely after the 1.7 release branch is cut.
The recommended condition to use in liu of OutOfDisk is DiskPressure

**Comment by gyliu513** [comment]
Good to know, thanks @dashpole , just noticed that you already mentioned this in mail list: https://groups.google.com/forum/#!searchin/kubernetes-dev/OutOfDisk%7Csort:relevance/kubernetes-dev/R0mTZLppp1Q/sWBKX8JQAQAJ

**Pull request closed without merging**
