### PR TITLE
Made image as required in v1 Container struct.

### LINKED ISSUE #47244: `Container Image` should not be marked as optional in v1 api
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1661-L1662

```
// A single application container that you want to run within a pod.
type Container struct {
	// Name of the container specified as a DNS_LABEL.
	// Each container in a pod must have a unique name (DNS_LABEL).
	// Cannot be updated.
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// Docker image name.
	// More info: https://kubernetes.io/docs/concepts/containers/images
	// +optional
	Image string `json:"image,omitempty" protobuf:"bytes,2,opt,name=image"`
....
}
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47244 

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by markturansky** [comment]
Please unassign me, as I am not an appropriate reviewer for this PR.

**Comment by smarterclayton** [comment]
Very surprising.  Please update the rest of the generated code

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by gyliu513** [comment]
@smarterclayton can we make this 1.7?

**Comment by smarterclayton** [comment]
Documentation change only, correctly conveys to end users that `image` is a required field (which it always has been).

/lgtm

**Comment by bgrant0607** [comment]
@smarterclayton 

This field was intentionally optional.

https://github.com/kubernetes/kubernetes/issues/8702#issuecomment-105707367
https://github.com/kubernetes/kubernetes/issues/1697#issuecomment-202631815

And changing it to required is a non-backward-compatible change in the API. Please revert this.

cc @dchen1107

**Comment by bgrant0607** [comment]
We cannot change what's optional and what's required:
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility

**Comment by gyliu513** [comment]
Thanks @bgrant0607 for pointing this out!

@smarterclayton do we need to revert this or create a new PR? Considering there are some auto-generated files, not sure if a PR is needed?

**Comment by bgrant0607** [comment]
@gyliu513 Please create a new PR, and include a comment that the field is deliberately optional.

**Comment by smarterclayton** [comment]
The underlying validation rule for all containers has always been

```
		if len(ctr.Image) == 0 {
			allErrs = append(allErrs, field.Required(idxPath.Child("image"), ""))
		}
```

**Comment by smarterclayton** [comment]
Note that we do allow single space string in deployments/RS/RC/Templates explicitly, but RS/RC call into `ValidatePodTemplateSpec` which requires a non-empty image.

**Comment by smarterclayton** [comment]
StatefulSet does *not* cal ValidatePodTemplateSpec, but DaemonSet and Deployment do

**Comment by gyliu513** [comment]
I think that we should also validate pod spec for statefulset, there is an issue here https://github.com/kubernetes/kubernetes/issues/47233

More detail, refer to: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L55-L58

**Comment by bgrant0607** [comment]
@smarterclayton Validation that `image` is populated does not imply that it should be considered required by other observers. The intent was for the field to be a member of an inline union/oneOf, once we added other image reference representations. I would also like controllers and Kubelet to deal gracefully with the absence of any image.

**Comment by bgrant0607** [comment]
@erictune @kow3ns I would like the image field in controllers, such as Deployment, to be optional, so that the image field could be left empty and set later by kubectl set image.

**Comment by himikof** [comment]
Seems that this change broke our pre-1.7 workflow. We were using a `image`-less Deployment file in source control for use with `kubectl apply`, and CI called `kubectl set image` during deployment. Now a Deployment without an `image` set fails to pass validation in `kubectl apply`. If this is an API-breaking regression, are there plans to fix it in 1.7.x? #48406 seems to have stalled.

**Pull request merged**
