### PR TITLE
Fix services.sh to swap out broken kubecfg calls

### PR DESCRIPTION
**Pull request by satnam6502**
This test was totally broken because two of the `kubecfg` calls returns the wrong information. I have:
- Changed two of the `kubecfg` calls to `kubectl` calls.
- Made the test use an explicitly tagged Docker image.
- Make the test generate unique names so it can be run back-to-back (needed for my testing).
  @jlowdermilk

### CODE REVIEW

**Comment by satnam6502** [comment]
@zmerlynn @filbranden @roberthbailey

**Comment by satnam6502** [comment]
@jlowdermilk :it would be great if you could convert the other `kubecfg` calls later. Thanks.

**Comment by jlowdermilk** [comment]
LGTM. If this fixes the e2e, feel free to merge on green Travis run.

**Comment by filbranden** [comment]
Looks good to merge as soon as Travis is happy with it.

**Comment by satnam6502** [comment]
Well, this itself is unlikely to fix e2e :-(

**Comment by zmerlynn** [comment]
Can you explain what happened to generate the regression?

**Comment by zmerlynn** [comment]
(I worry that if we don't add something to test-cmd.sh for this case, which
is what we did for other cases like this, we'll regress again. But now
you'll obviously need to make sure that the equivalent kubectl is tested.)

**Comment by satnam6502** [comment]
The call to `kubectl` was returning:
```
Server
    	version
    	(version.Info{Major:"0",
    	Minor:"9+",
    	GitVersion:"v0.9.0-374-gf6b23b10a3b9c4-dirty",
    	GitCommit:"f6b23b10a3b9c4a843ee78fc52cc3be51e98d356",
    	GitTreeState:"dirty"})
    	differs
    	from
    	client
    	version
    	(version.Info{Major:"0",
    	Minor:"9+",
    	GitVersion:"v0.9.0-360-g7feb885c8d2dfc-dirty",
    	GitCommit:"7feb885c8d2dfcb53dac232fff3b02c874d4f9ae",
    	GitTreeState:"dirty"})!
```
rather than a list of pod IDs.

**Comment by zmerlynn** [comment]
I finally read the full error there, sorry, I only skimmed your email
before. That shouldn't happen on Jenkins at all, because it's running a
compiled kubectl against what it just built. It sounds like you need to
kube-push, or disable version checking.

**Comment by filbranden** [comment]
Any objections to merging this one now?

**Comment by satnam6502** [comment]
Not frome!

**Pull request merged**
