### PR TITLE
Cluster upgrade: make command calling stream stdout/stderr.

### PR DESCRIPTION
**Pull request by mbforbes**
@mikedanese did this with logs and I took it out; I should have just replaced it with stdout/stderr. I am the fool.

This will help us debug GCE upgrade failures. If a GCE upgrade fails and the script never returns, we don't see any output because the test framework kills the job, and we don't print stdout/stderr until the call returns. This makes it so we see output as it's produced so we can debug failures better. This was motivated by this exact thing happening on a few Jenkins GCE runs.

Risk: low
Impact: low

I tested this locally and it worked as intended.
- @roberthbailey 
- @quinton-hoole

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by yujuhong** [comment]
@quinton-hoole, is this ok to merge?

**Comment by quinton-hoole** [comment]
Yes, ok-to-merge.  Given the high value and low risk.

**Comment by mikedanese** [comment]
:) LGTm

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
