### PR TITLE
Test device plugin re-registration with new device id

### PR DESCRIPTION
**Pull request by ScorpioCPH**
**What this PR does / why we need it**:

UT try to reproduce https://github.com/kubernetes/kubernetes/issues/55179

**Which issue(s) this PR fixes**

**Special notes for your reviewer**:

@jiayingz @lichuqiang PTAL.

**Release note**:

```release-note
None
```
/sig node

### CODE REVIEW

**Comment by lichuqiang** [comment]
The related unit test has already been updated in #52149, so I we might not need a seperate PR :)

**Comment by ScorpioCPH** [comment]
@lichuqiang Thanks, I have rebase this PR on top of #52149.
I think this PR https://github.com/kubernetes/kubernetes/pull/52149 doesn't cover the corner case completely.
Cloud you take a look at it please?

**Comment by lichuqiang** [comment]
@ScorpioCPH  Well, seems changes in the PR would not take effect, as [commented](https://github.com/kubernetes/kubernetes/pull/52149#issuecomment-344801474) here, manager.Devices() is that of the new endpoint, the test would always succeed.

An available way is to simulate the store in handler, with which the callback func indeed interact.
And I just had it  fixed in #55874 as @jiayingz suggested, together with some refactor/cleanup. It would be nice if you could help review and give some suggestions :)

**Comment by ScorpioCPH** [comment]
@lichuqiang Thanks, I don't notice the comments, SGTM, I will take a look at #55874 later.

**Pull request closed without merging**
