### PR TITLE
Clean up Azure clients

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Follow up of #63278 (Use new Azure SDK APIs for load balancer and public IP operations), clean up all other clients.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow up of #63278

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
ping @andyzhangx @khenidak

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve no-issue

**Pull request merged**
