### PR TITLE
rsync ipvs proxier to HEAD of iptables

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

rsync ipvs proxier to HEAD of iptables.

**Which issue this PR fixes**:

 xref #51679

**Special notes for your reviewer**:

Obviously, @Lion-Wei has done part of this work, ref: #51922. It's fine that let #51922 get in first.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
I would like to review it, but I may not get to it in the next few days.

BTW, @thockin - is this something that can be merged during code freeze? It's more like cleanup so I'm leaning towards that we may do it, but wanted your opinion on it.

**Comment by thockin** [comment]
I think no to code freeze.  I know it is alpha gated, but I don't think
it's worth any risk at all.

**Comment by m1093782566** [comment]
Okay, understand. Thanks all.

**Comment by wojtek-t** [comment]
The changes LGTM.

I'm wondering if we can somehow refactor the code to avoid such a huge duplication between iptables and ipvs.

/lgtm

**Comment by m1093782566** [comment]
> I'm wondering if we can somehow refactor the code to avoid such a huge duplication between iptables and ipvs.

Can't agree more! There are duplication among iptables, ipvs and windows.

**Comment by m1093782566** [comment]
BTW, I have considered doing this, but don't have good idea yet.

**Comment by m1093782566** [comment]
I created an issue #52464, we can discuss it at that thread if possible :)

**Pull request merged**
