### PR TITLE
Backport Calico related fixes to release 1.9

### LINKED ISSUE #65045: Fail to run Calico 3.0+ with existing addon yaml files under cluster/addons/calico-policy-controller/
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

The K8s cluster with NETWORK_POLICY_PROVIDER=calico could not be brought up in GCE when using Calico 3.0+ release. It would complain a number of issues, e.g., missing CRDs, authentication issues, ...

**What you expected to happen**:

K8s cluster can be brought up with Calico 3.0+ release

**How to reproduce it (as minimally and precisely as possible)**:

- Change image versions in cluster/addons/calico-policy-controller/{calico-node-daemonset, typha-depolyment}.yaml to Calico 3.0+ release

- make quick-release

- set ENV vars

export KUBE_CLUSTER_INITIALIZATION_TIMEOUT=3600
export NUM_NODES=1
export KUBE_UP_AUTOMATIC_CLEANUP=true
export KUBE_GCE_ZONE=us-west1-a
export KUBE_GCE_ENABLE_IP_ALIASES=true
export NETWORK_POLICY_PROVIDER=calico

- run cluster/kube-up.sh to spin up a K8s cluster on GCE

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: gce
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jingax10**
**What this PR does / why we need it**:
We need to run Calico 3.0+ on GCP and we need to customize MTU when Calico CNI is used on GCP.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65045 #65067

**Special notes for your reviewer**:

**Release note**:

```release-note
"NONE"
```

### CODE REVIEW

**Comment by dashpole** [comment]
I believe you meant to assign the patch release manager for 1.9
/unassign
/assign @mbohlool

**Comment by mbohlool** [comment]
Please add a release note with related changes in Calico and a link to Calico release note if exists.

**Comment by jingax10** [comment]
Just to clarify. The PR just provides ways to configure Calico, e.g., MTU in CNI Spec. No specific Calico changes tie to this PR.

**Comment by mbohlool** [comment]
I see. A patch to a release with no release note is strange. I means there is no user facing changes (i.e. no users will be affected). Is that the case here?

**Comment by jingax10** [comment]
Yes, no user visible changes.

**Pull request merged**
