### PR TITLE
Fix default value issue for Kublet's StreamingConnectionIdleTimeout, MaxPods, and MaxOpenFiles.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by yujuhong** [comment]
Thanks for the fix! It might be worth explicitly specifying the default value in `NewKubeletServer()`

@aveshagarwal, since you are at it, would you mind fixing other defaults as well? Both MaxPods and MaxOpenFiles have the same issue. They should have defaults defined in `NewKubeletServer()`.

**Comment by aveshagarwal** [comment]
@yujuhong sure, will update it.

**Comment by aveshagarwal** [comment]
@yujuhong Updated PR. PTAL.

**Comment by dchen1107** [comment]
@aveshagarwal  Thanks for fixing the default value for those flags. I think we should create a cherrypick pr for 1.1 patch release.

**Comment by aveshagarwal** [comment]
@dchen1107 no problem I can create a cherrypick PR for 1.1

**Pull request merged**
