### PR TITLE
Update fluent-plugin-elasticsearch (4.1.0) and fluent-plugin-kubernetes_metadata_filter (2.5.2)

### PR DESCRIPTION
**Pull request by Ghazgkull**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

The version of the fluent-plugin-elasticsearch which is currently built in this image results in the following message being printed out every second by fluentd:
```warning: 299 Elasticsearch-7.3.2-1c1faf1 "[types removal] Specifying types in bulk requests is deprecated."```

This PR updates fluent-plugin-elasticsearch to version 4.1.0, which contains a new flag named `suppress_type_name`. This flag will allow clients to fix this problem.

It also updates the fluent-plugin-kubernetes_metadata_filter to version 2.5.2, which contains a fix for 410 Gone errors on its namespace watch.

**Which issue(s) this PR fixes**:

Fixes:
*  https://github.com/kiwigrid/helm-charts/issues/381
* https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/246

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Ghazgkull** [comment]
@monotek Could you please take a look at this one? This is the upgrade that's needed in order to update the Helm chart to address https://github.com/kiwigrid/helm-charts/issues/381

**Comment by Ghazgkull** [comment]
As per my offline discussion with @monotek, I've updated this PR to also bump the kubernetes_metadata_filter plugin. This brings in an additional fix for namespace watches and will result in a more stable image.

**Review by monotek — CHANGES_REQUESTED** [review]
As we're on it anyway, could you please also update fluentd itself and have a look, if there are updates to any of the other gems please?

**Comment by Ghazgkull** [comment]
@monotek Sure thing. Done.

**Comment by Ghazgkull** [comment]
Really?


/test pull-kubernetes-e2e-gce-device-plugin-gpu

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93116/pull-kubernetes-node-e2e/1283806601320337408 flake is #93210

**Comment by Ghazgkull** [comment]
@monotek I think we need your approve and lgtm tags on this one. And we either need to find a way to skip the GPU test or wait for it to be fixed/merged. It's broken currently and won't pass.

**Comment by monotek** [comment]
/lgtm
/approve

The image is now also pushed to the docker registry:
 https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags

**Comment by Ghazgkull** [comment]
@monotek The GPU test won't pass until they get a fix merged. I'm subscribed to the PR and there've been a few commits and some back and forth. Here's the link if you want to subscribe: https://github.com/kubernetes/kubernetes/pull/93207/files/7ef92b80c68ee6e59f614dfac014e0451b698f00..e990698d5fd008b02c323080cd68fb0d0bdabd02

**Comment by monotek** [comment]
Imho you need to rebase: "do-not-merge/contains-merge-commits"

**Comment by Ghazgkull** [comment]
@monotek Okay, I've squashed to a single commit and rebased on origin/master. New commit is pushed. Can you please re-add the approval labels?

**Review by monotek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
