### PR TITLE
Automated cherry pick of #67430: cpumanager: rollback state if updateContainerCPUSet failed #66718: cpumanager: validate topology in static policy.

### PR DESCRIPTION
**Pull request by wanghaibo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

#67430: cpumanager: rollback state if updateContainerCPUSet failed
#66718: cpumanager: validate topology in static policy.

### CODE REVIEW

**Comment by idealhack** [comment]
@wanghaibo Thanks for your contribution! We don't need release note on cherry-pick PRs.

**Comment by wanghaibo** [comment]
@idealhack get it

**Comment by yagonobre** [comment]
Can we get this merged and released?

**Comment by foxish** [comment]
@wanghaibo @idealhack please get someone from the sig to LGTM and Approve this cherrypick

**Comment by idealhack** [comment]
@foxish Sorry, didn't notice this one hasn't been approved.

@kubernetes/sig-node-bugs

**Comment by clkao** [comment]
@foxish @derekwaynecarr @idealhack any chance to get this into v1.11.7?

**Comment by idealhack** [comment]
@clkao As the comment said above, we need to get this approved from sig-node first. I just pinged them on Slack.

also cc @kubernetes/sig-node-pr-reviews

**Comment by idealhack** [comment]
@foxish I think this is now ready for cherry-pick review :)

**Comment by foxish** [comment]
@idealhack - still needs lgtm to merge

**Comment by discordianfish** [comment]
@ConnorDoyle Hi! :) Can you give it a lgtm label?

**Comment by ConnorDoyle** [comment]
@discordianfish yes!
/lgtm

**Comment by discordianfish** [comment]
@ConnorDoyle /ok-to-test ? Before these bots snap completely..

**Comment by foxish** [comment]
Failures here. PTAL.

**Comment by foxish** [comment]
ping @wanghaibo - integration test failures.

**Comment by foxish** [comment]
Going to close this. Please reopen when you update it.

**Comment by dhawal55** [comment]
Why is this issue closed? Are we not check picking this against v1.11 anymore?

**Comment by foxish** [comment]
1.11.10 just went out and it's likely the last release in the 1.11.x branch. The maintenance window is now 1.12...1.14

**Comment by dhawal55** [comment]
Thank you for the update

**Pull request closed without merging**
