### PR TITLE
HPA: Allow customizing scale-forbidden-windows

### PR DESCRIPTION
**Pull request by DirectXMan12**
``` release-note
Allow custom upscale- and downscale-forbidden windows on HorizontalPodAutoscalers.
```

This commit allows customizing scale forbidden windows via annotations
on a HorizontalPodAutoscaler.  This way, users can configured how
"twitchy" their HPA is -- decreasing the window causes the HPA to react
faster to changes, at the expense of potentially scaling for an
unsustained change.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32408)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @kubernetes/autoscaling 

I've had several people ask for this in the interest of making the HPA react faster/more directly to changes.  I went back and forth between making this a config option on the controller manager vs allowing per-HPA configuration via annotations, but I think the per-HPA annotation gives some nice flexibility -- different users and applications might want different behavior.

**Comment by fgrzadkowski** [comment]
API should reflect the real intention of the user. It should not expose any internal algorithms etc. 

AFAIU the problem here is slow reaction time of HPA. There are two basic reasons:
* on each node stats are collected in a slightly different time windows (+-15 sec) so we need to wait some time to avoid double accounting or under accounting of some load
* pods are usually using a different amount of CPU during initialization and it's not representative. 

Yet another practical reason for HPA being slow is https://github.com/kubernetes/kubernetes/issues/30471 where we just don't have usage data. I believe that the solution is improving algorithm itself, not polluting the API.

Maybe just having a flag for the controller would help?

**Comment by DirectXMan12** [comment]
I think my response to this depends largely on the purpose of the forbidden windows (which, AFAICT, was never explicitly stated).  If the purpose is to prevent overwhelming the cluster with creation and deletion of pods, then this should probably be a flag.  If the purpose is to address the deficiencies in the algorithm described below, see below.  If the purpose is split between either of those and helping the user prevent their application from scaling wildly, then I think having it be configurable is reasonable.  See below:

> AFAIU the problem here is slow reaction time of HPA. There are two basic reasons:

> - on each node stats are collected in a slightly different time windows (+-15 sec) so we need to wait some time to avoid double accounting or under accounting of some load.

Assuming the HPA interval is sufficiently greater than the cAdvisor collection interval, this shouldn't be a problem, though.  Plus, the window is 3 or 5 minutes here, which seems high for a delta in time windows of 15 seconds.

> - pods are usually using a different amount of CPU during initialization and it's not representative. 

This is fundamentally a property of a given pod, though.  I don't think we can say that there is a "one-size-fits-all" that isn't *way* too long for some people.  There are two ways I see to solve this:

The quick way (presented here) is to let users customize the forbidden windows for their apps.  Users who care about this probably either know how long their initialization spike lasts or are willing to figure it out.

The longer way to solve this particular point is probably to pay attention to readiness probes -- don't consider the CPU of pods that are not marked as ready, and you won't have the initialization spike messing up your numbers.  Plus, potentially, if you have a bunch of pods which are not yet ready, don't consider scaling.

Those two issues aside, there are other reasons a forbidden window might be beneficial to a user, and a user might want to configure it.  Like I mention in the PR description, the forbidden window can be used to control how quickly the autoscaler is *willing* to scale.  Some might desire a faster scale  in exchange for a more-often-changing replica count, whereas others might be fine with waiting 5 minutes between scale-ups in exchange for a bit more "stability".  Some might want to be quick to scale up, but be cautious about scaling down (low scale-up forbidden window, high scale-down forbidden window), or vice versa.

However, if the forbidden window is *purely* an algorithm detail to compensate for timing issues in the algorithm, then IMO we should consider lowering it significantly and/or fixing the underlying issues and removing it.

**Comment by jszczepkowski** [comment]
As @fgrzadkowski noticed, this PR exposes internal details of HPA algorithm in the API. We cannot expose them, as the algorithm may be changed in the future and may look substantially different. We don't want to engrave internal stuff. New API fields will be no longer relevant and upgrade policy will not be clear.

> However, if the forbidden window is purely an algorithm detail to compensate for timing issues in the algorithm, then IMO we should consider lowering it significantly and/or fixing the underlying issues and removing it.

Can you specify, what values will be acceptable to you?

**Comment by fgrzadkowski** [comment]
I'd say there are multiple reasons for forbidden window. In short I'd say that it's needed to stabilize situation.

With regard to your specific comments:
* The problem with cadvisor scraping is not solved by HPA interval. In HPA we are using average over last minute and we often observe double accounting or under accounting.
* Using readiness probe is a good idea IMO and we should probably go that way. But I'm strongly against exposing some internal of the current non-perfect algorithm on the API level.

I'm fine with adding a flag on the controller level as values here could be potentially configurable by the cluster administrator. With regard to lowering it significantly I believe that if they are too low they will workaround problems described in my earlier reply.

**Comment by DirectXMan12** [comment]
I'm going to close this for the moment, and we can hash out "readiness probe" idea and future directions/potential pitfalls in the next SIG-autoscaling meeting to start out.

**Comment by Dmitry1987** [comment]
Hi, just want to add my 2 cents regarding flexible policies for autoscaling. We're using spotinst, and their amount of possible metrics and flexibility with defining several (unlimited actually) policies is pretty cool. For example, a basic policy: 

image

Allows setting both amount of instances to be scaled up/down and "seconds until the next scaling activity" (forbidden window), among all other options.
It would be useful for K8s HPA to have similar capabilities some day.  For example we have like 30 prod environments (each made of 10+ microservices, one per instance), and every microservice is different in its "load/boot time" and metrics, and needs completely different set of scaling policies. So we have plenty of spotinst groups (pool of ec2 instances with particular settings), and an attempt to migrate those "bare instance" workloads to containers needs our own implementation of scaling logic similar to spotinst, with manual triggers of "resize deployment" action, based on metrics from monitoring system. And while it's pretty cool for me (as a DevOps) to do it myself and implement such a thing, my Boss would be happier if it was out of the box in K8s =) .
Also, I'm ready to try help working on autoscaling capabilities of K8s, it'll take me months to understand the related codebase and improve golang skills, but eventually I might help you to bring the next cool autoscaling mechanisms for all to benefit, including myself :+1:

**Comment by Dmitry1987** [comment]
And this one is CPU based example, same params available, which allows complete control of how autoscaling works, when we combine both CPU and Latency rules... 

image

and there are plenty other metrics too of course, but this is already implemented in K8s as I understand, with custom metrics support. 
BTW, what is the roadmap for further HPA development?  are there currently plans to improve it even more?

**Comment by fgrzadkowski** [comment]
It's obviously personal I find this kind of policies defeat the purpose of autoscaling as they do not define the desired state, rather logic for autoscaling, which might get out of date. In my opinion most of those things should be detected automatically. For example cooldown period will be already support in 1.6 by using "ready" handler (i.e. pods "unready" are still initializing and we should treat them differently). Thanks @DirectXMan12 for that! Logic for how many instances should be added should also be automatic as it highly depends on the load characteristics, which may (and will) change over time.

Having said that, it might make sense to expand our policies, as long as they describe desired state and not the internal of the algorithm

**Comment by Dmitry1987** [comment]
I understand,
thanks @fgrzadkowski

**Comment by gyliu513** [comment]
Still do not understand why making the time windows configurable is exposing the logic of the algorithm? In OpenStack Heat, we already adding a parameter such as `cooldown` to do the similar work https://github.com/openstack/heat-templates/blob/master/contrib/rackspace/RackspaceAutoScale.yaml#L40

**Comment by fgrzadkowski** [comment]
Because we can detect it automatically using existing signals such as readiness probe, which @DirectXMan12  explained earlier. Once we add it, we will not be able to remove it. It's just that someone has to write a PR to properly interpret readiness.

Can you explain your use-case and say why proposed solution wouldn't work?

**Comment by gyliu513** [comment]
I still have concern for this even using `readiness probe`, the `readiness probe` can make sure autoscaler ignore the cpu usage for pods that are not ready, but how to handle the case if the end user want to make scale up more quick? i.e. As an application developer, I want my application can scale up based on cpu usage within 2min, how can we achieve this with current autoscaler? @fgrzadkowski

**Comment by Dmitry1987** [comment]
In addition to what @gyliu513  said, I have a perfect example for when automatic detection of needed scale-up/down size or automatic cooldown period calculation will not work:
lets say we have Elasticsearch nodes, which should scale-up slowly because of their replication (small size clusters, but very active on reads and writes. not above 1tb for example, as from that point replication shouldn't be used but snapshotting/cloning whole volumes between hosts) so cooldown should be like 20 minutes between scales (also logging usually will not strike that fast, it'll slowly rise up all the time if the app\product becomes popular), so it's a must to give fresh ES node to complete replication and "join forces" with other nodes, then cpu usage will slowly go down. (20 minutes\1 hour\2 hours of coodown depends on size. we have 4 clusters for example, 2 of them 100-200gb, one around 4tb, and one approx 32tb, different purposes for each)

and ES is just an example of a "slow loading" slow accelerating service :) .  on the other hand, there are quick nodejs services which have image sizes of 100-200mb (so they start instantly even on fresh empty hosts) and are bound to "1 cpu" (as nodejs should be used with 1 cpu per container, so they're smaaall but there are many of them), and you'd want them to react blazing fast to your traffic (they start, and within 30 seconds you can see CPU metrics across them are normalized, or are not, and it'll need more scale ASAP). so it all depends on workload types - and it's better to have flexibility for "manual control" anyway, no matter how smart the autoscaler default algorithm can be :) .  just my IMHO.
thanks!

**Comment by gyliu513** [comment]
+1 to @Dmitry1987 , I think that the `scale up/down interval` should not belong to the scale algorithm, the algorithm may need to focus on calculating how many pods should be scale up/down.

**Comment by fgrzadkowski** [comment]
I don't how your examples contradicts my proposal. Pod will become ready once it can serve regular traffic and it's done with initialization. For ES it will be 1h, for nodejs it'll be 30s. During initialization phase we will just assume that CPU is not representative and it will not be used for computations of expected number of replicas. 

What I'm basically saying is that we already have in API a way to expose a signal that an application is done with initization. I don't see a reason to duplicate this signal in HPA, especially that it'll be less accurate (1 static number per group vs 1 dynamic per instance).

What am I missing?

**Comment by Dmitry1987** [comment]
You're not missing anything because it doesn't contradict :) , it's an "additional" flexibility option which might be handy together with what you describe. Let's say I want to scale in steps of 5 pods with medium traffic spike, and step of 20 pods for high traffic spike (if I know the pattern of usual spikes on our app for example. if it's by design a product which usually has 50k/rpm, with occasional spikes for 80-90k/rpm few times a day at random time, and rare but devastating spikes of 200-300k/rpm [big news,events,Oscar selfie ;)]).  It can theoretically be done by current HPA algorithm, I don't know, but manual control over quantities of pods can still be useful.

But we can also leave without it - I can't argue :) . 
This can be implemented by own monitoring/alerting with triggers to "deployment scale: XX" API calls, skipping usage of HPA.  Most of the chances we in our environment will need such manual control anyway, with plenty of weird services that we have.. for example the HPA will never know what goes on with our ETL which moves stuff from plenty databases, sorts stuff, creates and uploads stuff, sing and dance, while being close to affect production if it slows down a bit - and the scaling of this weirdo will be done manually fetching plenty metrics from graylog/influxdb/elasticsearch, then triggering scale if needed. And the CPU even can't be a measure for scaling, because it's ok for certain times of day to stay at 100% CPU long time, no rush, but in another occasions only custom metrics from different sources (like SQS queue) might indicate an urgent scale-up need (but which amount of pods - HPA would never guess).

P.S.  if by reading this you realized our services are written by hallucinating junkies, you're right, but I can't help it. what's written is written, and my job is to make it work seamless :D . While more similar junk will be written daily, I need to be ready to handle it, so need all possible tweaking options (or will just implement my logic and use API calls).

I agree on the other hand, that if this feature is not needed by "masses" and can cause issues - it might be smarter to not implement it (but I'm missing what it might cause if exposed?).

**Comment by fgrzadkowski** [comment]
I still don't see why using readiness probe as a signal to know when cool-down period has ended wouldn't work in your case.

**Pull request closed without merging**
