### PR TITLE
[Kubemark] Fixed hollow-npd container command to log to file

### LINKED ISSUE #41802: NPD doesn't write its logs to file in kubemark
The npd in hollow-nodes doesn't write its logs to a file despite having its command as:

```
"/node-problem-detector",
.....other params....,
"1>>/var/log/npd-$(NODE_NAME).log 2>&1"
```

in hollow-node_template.json. I tried changing it to the following:

```
"/bin/sh",
"-c",
"/node-problem-detector ...params...  (both with and without --logtostderr) 1>>/var/log/npd-$(NODE_NAME).log 2>&1"     (here the logfile is created but nothing is written to it)
```

and that makes the container enter crashloop, without providing any way to access logs (I tried looking into /var/log/npd-$(NODE_NAME).log, tried kubectl logs, tried docker logs on the node and also kubectl describe pod, but none of them could give me any useful logs).

@Random-Liu Any idea how to make npd write to log file in hollow node / why it is failing?

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes #41802 

cc @wojtek-t @gmarek @Random-Liu

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM

**Comment by shyamjvs** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this

**Comment by gmarek** [comment]
Actually this should be fixed in NPD itself by adding
```
pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
```
to the main function.

**Comment by shyamjvs** [comment]
That is being done in NPD already (Ref:  https://github.com/kubernetes/node-problem-detector/blob/master/cmd/options/options.go#L111) The problem here was different. It was because of 'sh' not being able to parse the command due to some special (unescaped) character inside the apiserver-override flag.

**Comment by gmarek** [comment]
OK, it's a strange place for that though:)
/lgtm

**Pull request merged**
