### PR TITLE
fix: Fix ListByResourceGroup in azure diskClient mock

### LINKED ISSUE #97341: Incorrect Mock Implementation azure legacy-cloud-provider
**What happened**:
ListByResourceGroup  method in the azure diskClient mock makes a call to Delete

**What you expected to happen**:
ListByResourceGroup  method in the azure diskClient mock should call ListByResourceGroup  

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Rectify ListByResourceGroup mock so that UTs work as expected

**Which issue(s) this PR fixes**:

Fixes #97341

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by nearora-msft** [comment]
Abandoning this PR

**Review by andyzhangx — APPROVED** [review]
/ok-to-test
/lgtm
/approve
/kind bug
/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Thanks @nearora-msft

**Pull request merged**
