### PR TITLE
Refactor csiDriversStore

### PR DESCRIPTION
**Pull request by hoegaarden**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR does a little bit of refactoring in the `pkg/volume/csi` package, there is no external facing change(¹).

With those changes, the mutex handling and initialisation are handled internally and makes them an implementation detail other components do not need to know about and implement.

This is one little stepping stone towards removing any global state in the CSI package. This makes it a bit easier to pass the drivers list around, have it as a member of a struct (`Plugin` and/or `RegistraionHandler`), potentially passing the list around in different functions/methods, ... without needing to care about the mutex.

¹ Exception: More types are exported now (`csi.Diver` & `csi.DriversList`) to enable blackbox testing.

**Special notes for your reviewer**:

We want to remove all globals from `pkg/volume/csi`, we try to split it into as small PRs as we can. This is only the first of a series of PRs.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @vladimirvivien 
@mariantalla

### CODE REVIEW

**Comment by hoegaarden** [comment]
We have some evidence that this will be beneficial from the earlier spikes we did over here:
- https://github.com/kubernetes/kubernetes/pull/70379
- https://github.com/kubernetes/kubernetes/pull/70380
- https://github.com/kubernetes/kubernetes/pull/70381

**Comment by vladimirvivien** [comment]
@hoegaarden since there's no behavior modification, you don't need e2e.

/approve

**Pull request merged**
