### PR TITLE
providers: Remove long-deprecated Instances.List()

### PR DESCRIPTION
**Pull request by anguslees**
This method has been unused by k8s for some time, and yet is the last
piece of the cloud provider API that encourages provider names to be
human-friendly strings (this method applies a regex to instance names).

Actually removing this deprecated method is part of a long effort to
migrate from instance names to instance IDs in at least the OpenStack
provider plugin.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31678)

### CODE REVIEW

**Comment by colemickens** [comment]
Is this actually deprecated? I just implemented it for Azure a few weeks ago and didn't see any indication that it was deprecated.

**Comment by anguslees** [comment]
It isn't used anywhere in kubernetes, and hasn't been so for a long time (~2014) - afaict.

**Comment by dims** [comment]
LGTM 👍

**Comment by anguslees** [comment]
@mikedanese for lgtm-stamping ?

**Comment by anguslees** [comment]
ping any reviewers for lgtm stamping: @colemickens @mikedanese

**Comment by colemickens** [comment]
Didn't realize this was assigned to me.

**Comment by colemickens** [comment]
@k8s-bot ok to test

**Comment by colemickens** [comment]
1. I don't know how to rekick the tests since they appear stuck.

2. I don't know how to label this to remove the need for a release note (don't have permissions, don't know if there's a way to get a bot to do it for me).

CC: @mikedanese Can you unblock us on either of those issues?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@anguslees can you rebase please?

**Comment by mikedanese** [comment]
@k8s-bot test this

**Pull request merged**
