### PR TITLE
fix test/e2e/gke_node_pools.go

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

use log functions of core framework

**Which issue(s) this PR fixes**:

Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by k-toyoda-pi** [comment]
Can you change description from "Fixes #81427" to "Ref #81427". Because, the issue will be closed after this PR is approved even if all files are not modified.

**Comment by hwdef** [comment]
@k-toyoda-pi 
I am sorry about that,and i changed it.

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/lgtm
/approve
/retest

**Pull request merged**
