### PR TITLE
Document formatting

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Apply syntax highlighting to the code described in some documents. This makes the code easier to read.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by daikikatsuragawa** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Is it OK...?

**Comment by neolit123** [comment]
the CLA is not accepted. try contacting the CNCF help desk. also read the bot instructions / links above carefully.

**Comment by neolit123** [comment]
also please squash the commits to one.

**Comment by BenTheElder** [comment]
/assign @neolit123 
/cc @neolit123 
/uncc
thanks for reviewing @neolit123

**Comment by daikikatsuragawa** [comment]
I'm sorry.
I closed it because the operation related to CLA did not go well.

**Pull request closed without merging**
