### PR TITLE
kubectl: remove unreachable code

### PR DESCRIPTION
**Pull request by michaelgugino**
This code cannot be reached and causes some external linters
to fail.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This code cannot be reached and causes some external linters
to fail.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by bhalder — APPROVED** [review]

**Comment by michaelgugino** [comment]
@seans3 PTAL

**Review by soltysh — APPROVED** [review]
/approve
/priority important-longterm

**Pull request merged**
