### PR TITLE
bump(github.com/appc/spec):ab50d12e88f57788bf84b83fef2be236eb1fcc0b

### PR DESCRIPTION
**Pull request by smarterclayton**
To match changes to pkg/api/resource#ParseQuantity

@thockin re last comment in #25243

Still verifying

### CODE REVIEW

**Comment by smarterclayton** [comment]
@jonboulle re: appc depending on pkg/api/resource Quantity - do you want me to use a different commit level than what's here?  This moves Kube forward, but only until it has the ParseQuantity change.

**Comment by thockin** [comment]
LGTM

**Comment by a-robinson** [comment]
@smarterclayton @thockin - do we need to wait on an answer from @jonboulle, or should this go in as soon as tests pass?

**Comment by smarterclayton** [comment]
I don't think so, I do want to sort this out afterwards with him.

**Comment by smarterclayton** [comment]
This moves us forward 6 commits in their history so it's as safe a change as possible.

**Comment by thockin** [comment]
there's literally no code change here.

**Comment by jonboulle** [comment]
for posterity x-ref https://github.com/appc/spec/commit/7da0fdd4dfce6fda81869ac6ecd6ef42247957ea#commitcomment-17654244

**Pull request merged**
