### PR TITLE
Move ownership of core events test to sig-instrumentation

### PR DESCRIPTION
**Pull request by wojtek-t**
I propose that we migrate the ownership of core.Event test to sig-instrumentation.
There isn't a perfect home for it, but sig-instrumentation is definitely better than sig-apimachinery.
And sig-instrumentaiton already owns the new events API.

Ref https://github.com/kubernetes/kubernetes/issues/98326

```release-note
NONE
```

/kind cleanup
/priority important-soon

/assign @ehashman @logicalhan @brancz @dashpole

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
Where is the actual code for events stuff? I don't think we should move the test over to SIG Instrumentation until the actual code is also moved over (i.e. we have approval coverage over those relevant bits) because then we own tests for code that we don't actually own.

**Comment by wojtek-t** [comment]
> Where is the actual code for events stuff? I don't think we should move the test over to SIG Instrumentation until the actual code is also moved over (i.e. we have approval coverage over those relevant bits) because then we own tests for code that we don't actually own.

That's actually great point.
So basically it is:
- the API (and the corresponding registry: https://github.com/kubernetes/kubernetes/tree/master/pkg/registry/core/event)
   [it seems that owners in pkg/registry isn't really well organized for most of APIs]
- the library: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/record

FTR - for the new API, the client library is:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/events
[which also doesn't seem to be clearly owned]

I would be happy to extend this PR by adding sig-instrumentation-reviewers/approvers to OWNERS files for those two client libraries if we would agree that it's the right choice.

**Comment by spiffxp** [comment]
>- the API (and the corresponding registry: https://github.com/kubernetes/kubernetes/tree/master/pkg/registry/core/event)
[it seems that owners in pkg/registry isn't really well organized for most of APIs]
>- the library: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/record
>- for the new API, the client library is:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/events
[which also doesn't seem to be clearly owned]

>I would be happy to extend this PR by adding sig-instrumentation-reviewers/approvers to OWNERS files for those two client libraries if we would agree that it's the right choice.

/assign @lavalamp @deads2k @fedebongio @liggitt 
What does SIG API Machinery think?

**Comment by ehashman** [comment]
(needs rebase, I'll also add this to the SIG Instrumentation agenda for discussion on Thu)

**Comment by lavalamp** [comment]
I'm happy to own less code.

**Comment by metalmatze** [comment]
Hey everyone.
After hearing about this issue on today's SIG Instrumentation meeting I'm happy to help here.
What would people currently prefer? Still doesn't seems perfectly clear to me reading through this.

Should we proceed to updating the OWNERS file or actually move the code entirely?
In case the latter is true, I'd appreciate some guidance of what code to move where. 
Thanks!

**Comment by spiffxp** [comment]
I think this close to code freeze adding targeted OWNERS files is the less disruptive way forward. Moving code around can be a followup for next cycle. Agree @lavalamp ? /hold cancel if yes, and @metalmatze can add OWNERS in a followup PR for your approval

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold

**Comment by wojtek-t** [comment]
I went ahead and updated appropriate OWNERS files.

@spiffxp - can you please re-lgtm?

> I think this close to code freeze adding targeted OWNERS files is the less disruptive way forward. Moving code around can be a followup for next cycle.

I think moving code around (if really needed - that's even unclear to me), definitely shouldn't be done this cycle.

**Comment by metalmatze** [comment]
Sounds good to me. Thanks @wojtek-t :+1:

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
