### PR TITLE
update apiextentions-apiserver integration test key/crt

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

apiextentions-apiserver integration test key/crt will expire very soon. If they expire, the test case will fail.

We should fix it before hand.

regenerate it with a very long expire time, like 100 years.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

We have two choice:
1. remove the certificate 
2. generate a certificate with a very long expire time.
Both is ok, I think.
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Please regenerate with a long expiry date. Low entropy environments (like running tests inside a container) can take a long time to generate certificates

**Comment by hzxuzhonghu** [comment]
make sense

**Comment by sttts** [comment]
100y expiry time. That should be enough.

/lgtm
/approve no-issue

**Pull request merged**
