### PR TITLE
WIP: Remove error channels for non blocking operations

### LINKED ISSUE #84338: Introduce Internal Channels for scheduler
**What would you like to be added**:
The `scheduler` currently has a generic `util` package that stores a lot of common functionalities. Currently the `error_channels` for any errors that may arise in the scheduling framework are present here. W.r.t #71863 which serves as umbrella issue for scheduler cleanup, channels should become an internal package for scheduler.

**Why is this needed**:
The `error_channel` should be a scheduler exclusive package and must not be accessible to other components.

### PR DESCRIPTION
**Pull request by hprateek43**
**What type of PR is this?**

/kind design

**What this PR does / why we need it**:
Removes the error_channel package and introduces native golang `select` and `channels` for non blocking channel operations.

**Which issue(s) this PR fixes**:

Fixes #84338

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hex108 — COMMENTED** [review]
Thanks for it.

Please refer https://github.com/kubernetes/kubernetes/pull/79777 for the context why we use NewErrorChannel.

cc @draveness

**Review by draveness — CHANGES_REQUESTED** [review]
Thanks, but I don't think we are supposed to merge this into the codebase, it just "unwraps" the methods of error channel which provide higher-level abstraction.

**Comment by hprateek43** [comment]
@hex108 @draveness Please refer to this PR on why we are doing this https://github.com/kubernetes/kubernetes/pull/84336. We eventually want to get rid of the util package in scheduler. However, in the mentioned PR we disagreed to allow transitive dependencies into the `/pkg/controllers` to allow making `error_channels` an internal package. `error_channel` is just a wrapper  over non blocking channel reads and writes. If we remove that wrapped and allow `select` calls in the scheduler codebase, it will eventually allow us to remove the util package. @misterikkit Was also of the opinion that probably we can get rid of this by removing the wrapper.

**Review by draveness — COMMENTED** [review]
The first intention to use select is to replace the original mutex approach and @ahg-g propose a pattern to use error channel for readibility. You can see the discussion here https://github.com/kubernetes/kubernetes/pull/79777/files#r302340339

**Comment by hprateek43** [comment]
@draveness https://github.com/kubernetes/kubernetes/pull/84336#issuecomment-559261994 Please go through the discussion in one of the previous discussions in my PR. If we remove this wrapper class, atleast from the `/pkg/controller` we can eventually make the util package private in scheduler

**Comment by ahg-g** [comment]
> @draveness [#84336 (comment)](https://github.com/kubernetes/kubernetes/pull/84336#issuecomment-559261994) Please go through the discussion in one of the previous discussions in my PR. If we remove this wrapper class, atleast from the `/pkg/controller` we can eventually make the util package private in scheduler

I disagree with that comment, I think the error channel wrapper provides value in removing clearly redundant block of code, and reducing the risk of getting that code wrong if we chose to replicate it everywhere.

**Comment by hprateek43** [comment]
> > @draveness [#84336 (comment)](https://github.com/kubernetes/kubernetes/pull/84336#issuecomment-559261994) Please go through the discussion in one of the previous discussions in my PR. If we remove this wrapper class, atleast from the `/pkg/controller` we can eventually make the util package private in scheduler
> 
> I disagree with that comment, I think the error channel wrapper provides value in removing clearly redundant block of code, and reducing the risk of getting that code wrong if we chose to replicate it everywhere.

I was planning to keep it,  but its a transitive dependency for `/pkg/controllers`, and we want to ultimately make the `util` package internal. Hence the only way out is to remove the `errchannel` package and make the `util` package internal post that as we don't want internal transitive dependencies as well. Refer to the old PR for proposed changes and review @liggitt comments.

**Comment by ahg-g** [comment]
> > > @draveness [#84336 (comment)](https://github.com/kubernetes/kubernetes/pull/84336#issuecomment-559261994) Please go through the discussion in one of the previous discussions in my PR. If we remove this wrapper class, atleast from the `/pkg/controller` we can eventually make the util package private in scheduler
> > 
> > 
> > I disagree with that comment, I think the error channel wrapper provides value in removing clearly redundant block of code, and reducing the risk of getting that code wrong if we chose to replicate it everywhere.
> 
> I was planning to keep it, but its a transitive dependency for `/pkg/controllers`, and we want to ultimately make the `util` package internal. Hence the only way out is to remove the `errchannel` package and make the `util` package internal post that as we don't want internal transitive dependencies as well. Refer to the old PR for proposed changes and review @liggitt comments.

Are we going to unroll every internal helper function because we can't address transitive dependencies?

**Comment by hprateek43** [comment]
Not every, but `errchannel` is a peculiar case. Secondly, I don't understand why we care so much if an internal transitive dependency get listed in `.import-restrictions` as the compiler is not going to allow internal imports anyway. The purpose of the tool should be to force developers to list dependencies, and not to force developers to not use transitive internal dependencies.

**Comment by ahg-g** [comment]
>Secondly, I don't understand why we care so much if an internal transitive dependency get listed in `.import-restrictions` as the compiler is not going to allow internal imports anyway. The purpose of the tool should be to force developers to list dependencies, and not to force developers to not use transitive internal dependencies.

Right, that is the question that needs answering.

**Comment by ahg-g** [comment]
I believe we have the transitive dependency because the controller package depends on scheduler/algorithm/predicates: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L53

This will be cleaned up very soon as part of migrating most of the logic in algorithm/predicates to the framework plugins, and the transitive dependency will go away with it. I suggest we just wait until that happens.

**Comment by alculquicondor** [comment]
That specific dependency (controller->predicates->util) will go away, but we will probably have the plugin also depend in the error channel (controller->plugin->util). We are left with the same problem.

In general, we might need a library of helper functions that both in-tree and out-of-tree plugins can use. Maybe we can agree on where should that live?

**Comment by alculquicondor** [comment]
Also, did you file a bug on the "import-restrictions" tool?

**Comment by ahg-g** [comment]
> That specific dependency (controller->predicates->util) will go away, but we will probably have the plugin also depend in the error channel (controller->plugin->util). We are left with the same problem.

It probably will not because not all plugins import the error channel, and I expect the ones that the daemon controller will import do not need it.

> In general, we might need a library of helper functions that both in-tree and out-of-tree plugins can use. Maybe we can agree on where should that live?

+1, but lets wait to see what we will end up with after phase 2 of the migration.

**Comment by alculquicondor** [comment]
sg!

/close

**Comment by alculquicondor** [comment]
@hprateek43 could you create a bug to track the creation of such libraries discussed above?

**Comment by hprateek43** [comment]
@alculquicondor Opening a bug

**Pull request closed without merging**
