### PR TITLE
[1.30][ONLY] Fix broken verify job - Run hack/update-vendor.sh

### PR DESCRIPTION
**Pull request by dims**
/kind failing-test

Looks like some of the golang updates or cherry picks may have triggered a stale go.sum perhaps?

easy fix by running `hack/update-vendor.sh`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
ah, we need https://github.com/kubernetes/kubernetes/pull/126353 picked as well to protect 1.30

**Comment by liggitt** [comment]
I even added 👍 to https://github.com/kubernetes/kubernetes/pull/126353#issuecomment-2255002468 and forgot to do the pick ... mind pulling in that commit as well?

**Comment by BenTheElder** [comment]
> Looks like some of the golang updates or cherry picks may have triggered a stale go.sum perhaps?

How did this merge ..?

The last merged PR to 1.30 passed verify.

**Comment by dims** [comment]
@liggitt @BenTheElder Done! see https://github.com/kubernetes/kubernetes/pull/127307

**Comment by liggitt** [comment]
Thanks, I think the verify fix and this fix have to both go in together or the verify fix won't pass

**Comment by dims** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/127307

**Comment by BenTheElder** [comment]
/remove-sig api-machinery
[removing from triage query]

**Pull request closed without merging**
