### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by SataQiu**
**What this PR does / why we need it**:
fix typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR. please combine it with https://github.com/kubernetes/kubernetes/pull/69410

**Comment by SataQiu** [comment]
@liggitt Thank you! I have combined the commits.

**Pull request closed without merging**
