### PR TITLE
Remove kubelet soft admission

### LINKED ISSUE #125393: Remove Kubelet soft-admission
Kubelet soft admission handlers were created as a way for the Kubelet to block pods that cannot be run for reasons that can be resolved. In practice, this mechanism was only ever used by AppArmor ([here](https://github.com/kubernetes/kubernetes/blob/eef6c6082d4e34fc4a0675a36ec5cc575cd13696/pkg/kubelet/kubelet.go#L912)).

Problems with soft-admission rejection:
1. This is only used by AppArmor, and only for situations that cannot realistically be resolved (host or build does not support apparmor)
2. Pods held in the blocked state must be manually cleaned up. While there they hold reserved capacity from the scheduler and continually retry syncpod.
3. No other features work this way - usually Kubelet hard rejects pods that it knows it cannot run, or the runtime fails to start the pod/container.

This was originally added to prevent controllers from continuously recreating pods that cannot run, but that is a separate problem that should be approached globally, rather than with this 1-off AppArmor solution.

I propose we remove Kubelet soft admission entirely, and move the AppArmor admission handler to the hard-admission list.

/sig node
/milestone v1.31
/kind bug

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR removes kubelet soft admission as its are only ever used by AppArmor. For all other features kubelet will not admit a pod if it cannot run it and this makes the behavior of AppArmor consistent with the others.

#### Which issue(s) this PR fixes:

Fixes #125393

#### Does this PR introduce a user-facing change?

```release-note
kubelet now hard rejects pods with AppArmor if the node does not have AppArmor enabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tallclair** [comment]
/lgtm
/approve

Thanks!

**Comment by dchen1107** [comment]
Can you also add a test to show Kubelet hard rejects the pods with AppArmor but the node doesn't have it enabled? It can be in another pr.

**Comment by vinayakankugoyal** [comment]
> Can you also add a test to show Kubelet hard rejects the pods with AppArmor but the node doesn't have it enabled? Also I am expecting to see the message of why being rejected.
> 
> It can be in another pr.

I was out for a while but e2e_tests were updated to test that if the node does not support AppArmor then we expect hard rejection in [Fix kubelet AppArmor rejection test](https://github.com/kubernetes/kubernetes/commit/2df920120ab8ff2a93bee8bb982bb86320591f4e)

**Pull request merged**
