### PR TITLE
cleanup(scheduler): remove unused function, remove duplicate comment

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

remove unused function, remove duplicate comment, implement interface

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
/lgtm
/approve

Thanks!

**Comment by ahg-g** [comment]
please run ```./hack/update-bazel.sh``` to update the build files.

**Comment by ahg-g** [comment]
/approve cancel
/lgtm cancel 

so that the bot doesn't keep retrying

**Comment by yuzhiquan** [comment]
> please run `./hack/update-bazel.sh` to update the build files.

done, thanks for remind.

**Pull request merged**
