### PR TITLE
performance: cache WithLabelValues calls in sampleAndWaterMarkHistograms

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

As part of https://github.com/k3s-io/k3s/pull/5527#issuecomment-1114376418, we discovered that 24.4% of all CPU time k3s spent during idle load was in this code path.

The goal of this change is to reduce the baseline CPU utilization of kubernetes to make it cheaper to run locally. I only profiled k3s, but I suspect other distribution such as minikube may also benefit from this.

#### Which issue(s) this PR fixes:

n/a

#### Special notes for your reviewer:

Here is a flamegraph generated via a 10 minute profile of an idle k3s process:

166169348-ef415b4f-7da4-447f-87e1-d6a2e9e263ac

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Thanks.  This is one aspect of an even bigger campaign that I am waging, to replace sample-and-watermark histograms with something that does not have to iterate over sampling periods.  See #110104 for the key innovation in that regards; it gets about a 10X reduction in CPU, for the scenario I tested (the factor is, of course, strongly dependent on the frequency of updates from the client).  In #109742 you will also see the caching instead of repeated indexing addressed.  I abandoned that PR because it is too big; I am submitting it in smaller pieces.  I have not yet submitted the piece that uses caching instead of repeated indexing, but it is coming.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
That's amazing, in this case I'll close this MR in favour of the work you are doing. Super happy to hear it's on your radar.

Thanks!

**Comment by MikeSpreitzer** [comment]
This has been covered now.  #110104 is a big part of that.

**Pull request closed without merging**
