### PR TITLE
fix e2e test CPUManagerReconcilePeriod field is not allowed 0

### PR DESCRIPTION
**Pull request by lengrongfu**
#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/127445

#### Special notes for your reviewer:

Because CPUManagerReconcilePeriod should not be set to 0.

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/lgtm

testing using the value 1 second seems legit and valid to me

**Comment by SergeyKanzhelev** [comment]
/assign

for approval

**Comment by kannon92** [comment]
E2eNode Suite: [It] [sig-node] Kubelet Config [Slow] [Serial] [Disruptive] [NodeFeature:KubeletConfigDropInDir] when merging drop-in configs should merge kubelet configs correctly	

is passing so let's get this in!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
