### PR TITLE
add logging for enabled/disabled API Groups

### PR DESCRIPTION
**Pull request by deads2k**
Adds logging to the apiserver to indicate which API groups are enabled and disabled as go through.  This will make it easier to identify what's gone wrong in cases where the API server is down during diagnoses and the config is inaccessible, like in GKE tests.  For example https://github.com/kubernetes/kubernetes/issues/32185#issuecomment-245255700 .

@wojtek-t This may have made the problem more obvious.

``` release-note
Add logging for enabled/disabled API Groups
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32198)

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts straightforward logging.  I figure I'll open this entire pull as a pick into 1.4.1

**Comment by sttts** [comment]
Simple patch, simple one-time logging. Maybe use `V(1).Infof`? Then it can be disabled with `--v=0`. Otherwiese, lgtm.

**Comment by dims** [comment]
@deads2k - did you want "fixup storage examples" commit in this PR or a separate PR?

**Comment by deads2k** [comment]
> @deads2k - did you want "fixup storage examples" commit in this PR or a separate PR?

I had no real preference.  I can do it separately if you like.

**Comment by deads2k** [comment]
> Simple patch, simple one-time logging. Maybe use V(1).Infof? Then it can be disabled with --v=0. Otherwiese, lgtm.

done.

**Comment by saad-ali** [comment]
@deads2k Let's get this cherry-picked to the 1.4 release branch so the examples in the release branch are correct.

@jessfraz This is non-blocking for v1.4.1--it is ok for this to be merged after that release is cut, but we should ensure that it does get merged to the release branch at some point.

**Comment by saad-ali** [comment]
hmm, I can't seem to change the milestone. @jessfraz could you set the `v1.4-nonblocking` milestone

**Comment by jessfraz** [comment]
I think the github api is freaking out

**Comment by saad-ali** [comment]
Someone must've pushed changes and left for the Friday =P

**Pull request merged**
