### PR TITLE
Add since_time parameter to read logs command

### LINKED ISSUE #1351: Add since_time parameter to read_namespaced_pod_log
**What happened (please include outputs or screenshots)**:

The docstring makes reference to both the `sinceSeconds` and `sinceTime` parameters which exist in the CLI, but I see that only the `since_seconds` kwarg is accepted by the Python client

**What you expected to happen**:

I expected the `since_time` kwarg to be accepted

**How to reproduce it (as minimally and precisely as possible)**:

Pass `since_time` attribute to the CoreV1Api method `read_namespaced_pod_log`

**Anything else we need to know?**:

n/a

**Environment**:
- Kubernetes version (`kubectl version`): v1.19.0
- OS (e.g., MacOS 10.13.6): Linux
- Python version (`python --version`) 3.6.10
- Python client version (`pip list | grep kubernetes`) 12.0.0

### PR DESCRIPTION
**Pull request by neelsomani**
**What type of PR is this?**

/kind feature
/kind api-change

**What this PR does / why we need it**:

Adds the since_time parameter to the Kubernetes Python API client for the `read_namespaced_pod_log` function. This parameter already exists for the CLI.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-client/python/issues/1351

**Special notes for your reviewer**: Let me know if there's something else I should do here

**Does this PR introduce a user-facing change?**:

```release-note
Added the since_time parameter for the read_namespaced_pod_log function in the Kubernetes Python client.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [Other doc]: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs
```

### CODE REVIEW

**Comment by yliaog** [comment]
the file api/openapi-spec/swagger.json is automatically generated, it should be not manually edited.

**Comment by neelsomani** [comment]
Thanks @yliaog, so where should I edit so this generated file includes the since_time field?

**Comment by yliaog** [comment]
please take a look at k8s.io/kube-openapi/cmd/openapi-gen/

**Comment by neelsomani** [comment]
Like within this repo? https://github.com/kubernetes/k8s.io

Tried searching for that path and couldn't find anything. A little bit confused how this is not a simple change but might just close this issue + PR.

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/update-openapi-spec.sh is the script to update the swagger.json
https://github.com/kubernetes/kubernetes/blob/master/hack/verify-openapi-spec.sh is the script to verify.

i took another look at the https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4427

it's possible that:

"SinceTime *metav1.Time",

metav1.Time is a struct defined in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go#L31

openapi-gen does not handle the struct type properly.

**Comment by neelsomani** [comment]
Ahh interesting, that does sound non-trivial. I can leave the issue open or edit it to make it more specific to this openapi-gen issue. Let me know either way or if you want to edit / close issues feel free.

**Comment by ehashman** [comment]
/close

Please open a new PR for your updated fixes, thanks!

**Pull request closed without merging**
