### PR TITLE
Self nominate Kevin Hannon for reviewer for job controller

### PR DESCRIPTION
**Pull request by kannon92**
I have  lead the PodReplacementPolicy KEP for alpha and I helped review/fix some issues in beta.  

https://github.com/kubernetes/kubernetes/pulls?q=+is%3Apr+reviewed-by%3Akannon92+label%3Asig%2Fapps+

I have also been an active reviewer and helped GA job tracking last release.  I hope to continue reviewing Job related code.

#### What this PR does / why we need it:

Add kannon92 as a reviewer for the job controller code.

- [x] member for at least 3 months: Been member for 1 year. https://github.com/kubernetes/org/issues/3861
- [x] Primary reviewer for at least 5 PRs to the codebase: https://github.com/kubernetes/kubernetes/pulls?q=+is%3Apr+reviewed-by%3Akannon92+label%3Asig%2Fapps+
- [x] Reviewed or merged at least 20 substantial PRs to the codebase: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Akannon92++label%3Asig%2Fapps
- [x] Knowledgeable about the codebase: Yes.
  - Led PodReplacementPolicy KEP and reviewed the beta promotion
  - Helped GA Job Tracking.
  - Triage Job related issues
  - Helped improve usability of Job in other projects like JobSet   
- [x] Sponsored by a subproject approver: Bringing this up to get approver.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/kind feature

?

**Comment by mimowo** [comment]
SGTM, could you please convert the [reviewer requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1) as a checkbox list here.

**Comment by mimowo** [comment]
+1 for the nomination

**Comment by alculquicondor** [comment]
+1, although you need a sponsor from a different company :)

Thank you for your invaluable contributions!

**Comment by dims** [comment]
i am happy to sponsor! +1 from me.

**Comment by alculquicondor** [comment]
/approve
:D

**Comment by kannon92** [comment]
@dims do you want to give this a milestone 1.29 since its not a code change?

**Comment by dims** [comment]
/approve
/lgtm
/milestone v1.29

(this is just editing an OWNERS file, so we should be safe and not subject to code freeze)

**Comment by kannon92** [comment]
Thank you @alculquicondor and @mimowo!

**Pull request merged**
