### PR TITLE
Update Cluster Autoscaler version to 1.13.2

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
Update Cluster Autoscaler version to 1.13.2. Release notes: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.2
```

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
Looks like the bot isn't updating all the labels: 
- needs-priority (removed it manually since priority was updated),
- cnfc-cla:yes (still missing even though presubmit passed).

cc @krzyzacy @BenTheElder

**Comment by tpepper** [comment]
This seems like something for which it is probably worth adding a release note.

**Comment by losipiuk** [comment]
> This seems like something for which it is probably worth adding a release note.

There is a `release notes` section in the PR desc. Won't it be picked up automatically on the release?

**Review by mwielgus — APPROVED** [review]

**Pull request merged**
