### PR TITLE
Automated cherry pick of #66932 #67433: Include unavailable API services in discovery response, allow failed discovery on initial quota controller start

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #66932 #67433 on release-1.11.

#66932: Include unavailable API services in discovery response
#67433: allow failed discovery on initial quota controller start

```release-note
kube-apiserver now includes all registered API groups in discovery, including registered extension API group/versions for unavailable extension API servers.
kube-controller-manager can now start the quota controller when discovery results can only be partially determined.
```

### CODE REVIEW

**Comment by nilebox** [comment]
> apiserver_test.go:369: Discovery call expected to return failed unavailable service

Hmm, was there some other change post-1.11 in master that affected this behavior?..

**Comment by nilebox** [comment]
In 1.10 this test did succeed, probably some flakiness related to the wait duration.

**Comment by liggitt** [comment]
> In 1.10 this test did succeed, probably some flakiness related to the wait duration.

yeah, 100ms might not be long enough to wait... might consider changing that to a poll in master to get the expected result or fail after N seconds

**Comment by nilebox** [comment]
@liggitt please see PR #67325 fixing the flakiness.

**Comment by nilebox** [comment]
@foxish can you review this cherry pick please? We need it to fix a critical bug in Service Catalog

**Comment by liggitt** [comment]
/assign @deads2k 
for lgtm/approve

**Comment by liggitt** [comment]
/hold

needs to wait for a pick of https://github.com/kubernetes/kubernetes/pull/67433 to allow the controller manager to start correctly in partial discovery cases (since the workload controllers need to be able to start in order to start back up aggregated servers that are down in order to resolve the 503 errors)

**Comment by foxish** [comment]
@liggitt, can someone from api-machinery lgtm/approve this?

**Comment by yagonobre** [comment]
When we will have a `1.11` release?

**Comment by foxish** [comment]
Planned today, but blocked on https://github.com/kubernetes/kubernetes/issues/68372

**Pull request merged**
