### PR TITLE
WIP: cadvisor v047 wip DO NOT MERGE

### PR DESCRIPTION
**Pull request by bobbypage**
- wip: Bump cadvisor
- Remove AcceleratorUsageMetrics from kubelet

Ran

```
$ hack/pin-dependency.sh github.com/google/cadvisor=github.com/bobbypage/cadvisor gomodfixes
```

Attempting to test https://github.com/google/cadvisor/pull/3230

### CODE REVIEW

**Comment by bobbypage** [comment]
Failed with 

```
These modules are pinned to non-canonical repos.
Revert to using the canonical repo for these modules before merge

  github.com/google/cadvisor is replaced with github.com/bobbypage/cadvisor
Removing /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.Akx9Ch
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-vendor.sh	149s
```

so it looks ok

**Comment by liggitt** [comment]
yup, `GODEBUG=gocacheverify=1 go mod tidy` in staging/src/k8s.io/apiserver worked on this PR and fails on https://github.com/kubernetes/kubernetes/pull/114883

this should work fine

**Comment by liggitt** [comment]
/close

main PR merged, this experiment isn't needed any more

**Pull request closed without merging**
