### PR TITLE
Add scheduler predicate to filter for max Azure disks attached

### PR DESCRIPTION
**Pull request by codablock**
**What this PR does / why we need it**: This PR adds scheduler predicates for maximum Azure Disks count. This allows to use the environment variable KUBE_MAX_PD_VOLS on scheduler the same as it's already possible with GCE and AWS.

This is needed as we need a way to specify the maximum attachable disks on Azure to avoid permanently failing disk attachment in cases k8s scheduled too many PODs with AzureDisk volumes onto the same node. 

I've chosen 16 as the default value for DefaultMaxAzureDiskVolumes even though it may be too high for many smaller VM types and too low for the larger VM types. This means, the default behavior may change for clusters with large VM types. For smaller VM types, the behavior will not change (it will keep failing attaching).

In the future, the value should be determined at run time on a per node basis, depending on the VM size. I know that this is already implemented in the ongoing Azure Managed Disks work, but I don't remember where to find this anymore and also forgot who was working on this. Maybe @colemickens can help here.

**Release note**:

```release-note
Support KUBE_MAX_PD_VOLS on Azure
```

CC @colemickens @brendandburns

### CODE REVIEW

**Comment by bsalamat** [comment]
The changes look good to me. Just out of curiosity (and probably unrelated to this particular PR), I wonder why there is no VolumeConflict logic for Azure disks.

**Comment by davidopp** [comment]
@k8s-bot ok to test

**Comment by colemickens** [comment]
cc: @rootfs as the original author of AzureDisk
cc: @anhowe as FYI
cc: @khenidak who is authoring Managed Disk support (though I don't remember seeing this problem addressed in @khenidak's branch...)

Anyway, change looks good to me. Thanks for adding this.

**Comment by davidopp** [comment]
@k8s-bot test this

**Comment by codablock** [comment]
@colemickens @khenidak I found the place where I've seen the code for VM size/max disks handling.

https://github.com/khenidak/kubernetes/commit/43d0686b50be6df5a82cb745d434471604bd2376#commitcomment-20955454

I really would like to reuse this information in the scheduler. But currently I'm not sure if it's even possible to figure out the VM size from inside the scheduler and I would actually not like to introduce this into the scheduler as it is too cloud provider specific. I'd suggest to put this into the cloud provider so that the kubelet can report the maximum allowed disks and somehow write this into the node object or node status. This information could then be reused in the scheduler.

**Comment by rootfs** [comment]
@codablock thanks for getting this done.

**Comment by khenidak** [comment]
@bsalamat + @colemickens  Can you clarify "volume conflict"?

**Comment by bsalamat** [comment]
@khenidak 
Please see https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L111
There is logic to find volume conflicts for GCE, AWS, ..., but there is not such checks for Azure.

**Comment by codablock** [comment]
@bsalamat @khenidak @colemickens Wow, I should have known about the conflict checking a few month earlier :D I struggled a lot with these conflicts on Azure in the past and I solved it with https://github.com/kubernetes/kubernetes/pull/40148, which is still in review.

I always assumed the scheduler did not take double attaching into account, at least it did not do so on Azure and this explains why.

Now I'm not sure how to proceed with https://github.com/kubernetes/kubernetes/pull/40148. It still fixes a race condition (which is not as bad in case scheduler prevents conflicts in advance) and may serve as the last guard against double attaching in situations where we know it will cause trouble.

What do you think? How should we proceed?

**Comment by codablock** [comment]
@colemickens @khenidak As I don't have access to any Azure resources anymore (I'm working for a new client now, not related to Azure) I won't be able to do the fix for the conflict checks...at least not with proper testing. Can one of you take over? Or maybe @rootfs?

**Comment by khenidak** [comment]
I will added as part of the new plugin. Hopefully we can get them all in as one PR.

**Comment by khenidak** [comment]
@bsalamat  thanks for the clarification, I see it now. Will add Azure accordingly.

**Comment by rootfs** [comment]
@khenidak did you mean NoDiskConflict predicate? It is better in a separate PR. Longer PRs take time to merge.

**Comment by khenidak** [comment]
Sure, There are two things other than the plugin. I will be PRing them later. NoDiskConflict and handling Azure specific scheduling (filter-out VMs that has max disk attached).

**Pull request merged**
