### PR TITLE
Add user-specified kubectl arguments to addons start script

### LINKED ISSUE #30371: addon-manager should support user-provided arguments to kubectl
The addon-manager runs various kubectl commands, but does not support user-provided arguments. This is an issue if, for instance, the API server is not on the default hostport. Letting the user specify arguments would resolve this problem.

### PR DESCRIPTION
**Pull request by bbreslauer**
This is a simple way, using the same environment variable paradigm used throughout these scripts, to let a user specify kubectl arguments to the addons script.

fixes #30371

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30372)

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM, @bbreslauer please sign CLA or use your @google.com email address as the author of the commit.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue: #IGNORE

**Comment by mikedanese** [comment]
@k8s-bot ok to smoke e2e test, issue: #IGNORE

**Comment by MrHohn** [comment]
This broke addon manager when `KUBECTL_OPTS` is empty.

Repro as below:
```
$ kubectl '' get Deployment --all-namespaces -o 'go-template={{range.items}}{{.metadata.namespace}}/{{.metadata.name}} {{end}}' -l kubernetes.io/cluster-service=true
error: name cannot be provided when a selector is specified
```
 And because the following `| sed 's/<no value>//g'` command, the error would not be catched by the shell script.

**Pull request merged**
