### PR TITLE
WIP Remove dockershim flags from scripts

### PR DESCRIPTION
**Pull request by hakman**
#### What type of PR is this?
/kind cleanup
Ref:
* https://github.com/kubernetes/kubernetes/pull/106907
* https://github.com/kubernetes/kubernetes/issues/106893

#### What this PR does / why we need it:
As part of the removal of dockershim, remove the deprecated CLI flags that still exist from various scripts.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cyclinder** [comment]
👍👍
1 failling, very close to success

**Comment by hakman** [comment]
@cyclinder This new commit should address the remaining failure.
Seems that there is quite a lot of extra cleanup that has to be done. For example `--container-runtime` should also be removed.

**Comment by cyclinder** [comment]
> @cyclinder This new commit should address the remaining failure. Seems that there is quite a lot of extra cleanup that has to be done. For example `--container-runtime` should also be removed.

I see `hack/local-up-cluster.sh`, there I also remove ``

> 

yeah, I see you marked  `TODO: Remove`,  thanks your job!

**Comment by hakman** [comment]
Looking at the `local-e2e` job, it seems to require Docker. The good news is that, if we don't touch the script, it will not run the test.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/local-e2e.yaml

**Comment by cyclinder** [comment]
> Looking at the `local-e2e` job, it seems to require Docker. The good news is that, if we don't touch the script, it will not run the test. https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/local-e2e.yaml

how can we don't touch the script?

**Comment by hakman** [comment]
> how can we don't touch the script?

Simple, remove all changes to it from the PR and take care of it later.
Will close this PR and continue the discussion in your PR.

**Pull request closed without merging**
