### PR TITLE
build: clean platform envs to prevent cross-contamination

### LINKED ISSUE #37079: `make release` fails on ubuntu 16.04
Similar to #37076 
this is to test the first contributor experience #36655 

`make release` fails on ubuntu 16.04, docker version 1.12.3:

```
...
+++ [1118 11:18:18] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1118 11:18:19] Multiple platforms requested, but available 7G < threshold 11G, building platforms in serial
+++ [1118 11:18:19] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1118 11:18:19] Building go targets for linux/amd64:
    cmd/kubectl
    federation/cmd/kubefed
+++ [1118 11:18:37] Building go targets for linux/386:
    cmd/kubectl
    federation/cmd/kubefed
+++ [1118 11:20:05] Building go targets for linux/arm:
    cmd/kubectl
    federation/cmd/kubefed
+++ [1118 11:20:23] Building go targets for linux/arm64:
    cmd/kubectl
    federation/cmd/kubefed
+++ [1118 11:20:43] Building go targets for darwin/amd64:
    cmd/kubectl
    federation/cmd/kubefed
# runtime/cgo
aarch64-linux-gnu-gcc: error: unrecognized command line option '-m64'
Makefile:79: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:264: recipe for target 'cross' failed
make: *** [cross] Error 1
Makefile:248: recipe for target 'release' failed
make: *** [release] Error 1
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
ubuntu@gobuild:~/go/src/k8s.io/kubernetes$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
ubuntu@gobuild:~/go/src/k8s.io/kubernetes$ uname -a
Linux gobuild 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: As I described in https://github.com/kubernetes/kubernetes/issues/37079#issuecomment-263733509, we are leaking platform compilation envs between build stages for different platforms in the non-parallel dockerized cross build. This PR uses a subshell for the non-parallel build, more closely matching the parallel build.

This also adds some logging, which had it existed previously, may have made the bug more immediately obvious.

**Which issue this PR fixes**: fixes #37079 

cc @sebgoa @iTagir @saad-ali

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37665)

**Comment by ixdy** [comment]
@k8s-bot build this

**Comment by ixdy** [comment]
I tagged on one more commit, passing `KUBE_VERBOSE` into the build container. (It was taking me an extraordinarily long time to figure out why I wasn't seeing the verbose logging line I added.)

**Comment by zmerlynn** [comment]
Hm, I guess I need to `/lgtm cancel` and `/lgtm` to reaffirm before the bot gets back in.

**Comment by ixdy** [comment]
@k8s-bot build this

**Comment by ixdy** [comment]
@k8s-bot gce node e2e test this

**Comment by ixdy** [comment]
@k8s-bot node e2e test this

**Comment by ixdy** [comment]
@k8s-bot test this

**Pull request merged**
