### PR TITLE
aggregator/apiextensions: logs & metrics why OpenAPI spec is regenerated

### PR DESCRIPTION
**Pull request by sttts**
Every OpenAPI spec regeneration is heavy on the CPU, a multi-second one-core operation. In a normal cluster this should happen not so often. If it does, the admin has to know. This PR will add the log output to make the situation actionable.

/kind feature

```release-note
Log when kube-apiserver regenerates the OpenAPI spec and why. OpenAPI spec generation is a very CPU-heavy process that is sensitive to continuous updates of CRDs and APIServices.

Added metrics aggregator_openapi_v2_regeneration_count, aggregator_openapi_v2_regeneration_gauge and apiextension_openapi_v2_regeneration_count metrics counting the triggering APIService and CRDs and the reason (add, update, delete).
```

### CODE REVIEW

**Comment by deads2k** [comment]
Do we have a metric gathering how often we do this, maybe sliced by why?

**Comment by deads2k** [comment]
I'm fine with it in concept, but I'd like a metric attached.

**Comment by roycaihw** [comment]
agree having metricses for aggregator and apiextensions is better

we have workqueue metricses for `crd_openapi_controller` and `APIServiceOpenAPIAggregationConttollerQueue1`, but those aren't exact the same as how many times spec regeneration happened

**Comment by sttts** [comment]
@roycaihw this is less about how often, but more about why.

**Comment by xmudrii** [comment]
@sttts @deads2k @roycaihw Hello! I'm the bug triage lead for the 1.16 release cycle and I'd just like to remind that the code freeze is starting on August 29th EOD PST (about 5 days from now). Once the code freeze starts, only release-blocking PRs will be considered for merging.

**Comment by sttts** [comment]
Rebased.

**Pull request merged**
