### PR TITLE
Adding myself as a reviewer to aws cloud provider

### PR DESCRIPTION
**Pull request by chrislovecnm**
/assign @justinsb 
/release-note-none
/approve no-issue

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@justinsb please remove retest-not-required-docs-only label  ... that I am guessing is wrong.  opening an issue with test-infra

**Comment by chrislovecnm** [comment]
kops e2e is not happy

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57178/pull-kubernetes-e2e-kops-aws/64625/

```
I1214 05:45:40.695] Call:  git clean -dfx
I1214 05:45:40.706] process 21 exited with code 0 after 0.0m
I1214 05:45:40.707] Call:  git reset --hard
W1214 05:45:40.719] error: object file /root/.cache/git/k8s.io/kubernetes/objects/4f/2e567a7dd8cc6b6c59f862e1a66ab7790d9b91 is empty
W1214 05:45:40.720] error: object file /root/.cache/git/k8s.io/kubernetes/objects/4f/2e567a7dd8cc6b6c59f862e1a66ab7790d9b91 is empty
W1214 05:45:40.720] fatal: loose object 4f2e567a7dd8cc6b6c59f862e1a66ab7790d9b91 (stored in /root/.cache/git/k8s.io/kubernetes/objects/4f/2e567a7dd8cc6b6c59f862e1a66ab7790d9b91) is corrupt
E1214 05:45:40.721] Command failed
I1214 05:45:40.721] process 22 exited with code 128 after 0.0m
E1214 05:45:40.721] unexpected error
```

That is special - do we have an issue for the test?

**Comment by justinsb** [comment]
That's git, not kops.

**Comment by chrislovecnm** [comment]
Yah I opened https://github.com/kubernetes/test-infra/issues/5949

**Comment by chrislovecnm** [comment]
@justinsb can you please lgtm

**Pull request merged**
