### PR TITLE
fix golint errors in staging/src/k8s.io/client-go/plugin/pkg/client/a…

### PR DESCRIPTION
**Pull request by tianhongw**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

fix golint errors in staging/src/k8s.io/client-go/plugin/pkg/client/auth/oidc

**Which issue(s) this PR fixes**:

XREF  #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by gavinfish — COMMENTED** [review]
General lgtm, but please do not use `Fixes #issue` in the description which will close it. You can use something like `xref`.

**Comment by tianhongw** [comment]
I signed it

**Comment by tianhongw** [comment]
> General lgtm, but please do not use `Fixes #issue` in the description which will close it. You can use something like `xref`.

Thanks for your suggestion!

**Comment by tianhongw** [comment]
@kubernetes/patch-release-team

**Comment by lavalamp** [comment]
whoa, this is for a release branch?

/lgtm cancel
/approve cancel

Please send this to master.

**Comment by tianhongw** [comment]
@lavalamp  Sorry for that>.< I thought i should cherry pick it to 1.18 branch because of i notice this description in check:

> Not mergeable. Must be in milestone v1.18.

**Comment by lavalamp** [comment]
Yes, that means we're in code freeze--changes to the master branch will
merge when we open back up again.

**Pull request merged**
