### PR TITLE
Volunteer for local-up-cluster related files

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Wish to help with changes to hack/local-up-cluster.sh and any spill over
into other files that affect hack/local-up-cluster.sh.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cblecker** [comment]
I'm okay with this! @dims has helped a lot with this code.

**Comment by cblecker** [comment]
/approve
LGTM to @ixdy

**Comment by dims** [comment]
@ixdy ok with you?

**Pull request merged**
