### PR TITLE
Automated cherry pick of #53239

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #53239 on release-1.7.

#53239: Correct APIGroup for RoleBindingBuilder Subjects

### CODE REVIEW

**Comment by liggitt** [comment]
Check bazel build:

> W0930 19:18:48.755] ERROR: /workspace/k8s.io/kubernetes/pkg/apis/rbac/BUILD:49:1: no such package 'pkg/apis/rbac/v1': BUILD file not found on package path and referenced by '//pkg/apis/rbac:go_default_xtest'

**Comment by wojtek-t** [comment]
Cherrypick approved.

@liggitt - can you please take a look and lgtm it?

**Pull request merged**
