### PR TITLE
allow SERVICE_NODE_PORT_RANGE for kube-up to vagrant provider

### PR DESCRIPTION
**Pull request by bmeck**

### CODE REVIEW

**Comment by thockin** [comment]
Can you clarify why you want to parameterize this?

**Comment by bmeck** [comment]
@thockin we wanted to do local testing of Kubernetes on OSX, so we were using vagrant, but the vagrant provider does not let you configure `SERVICE_NODE_PORT_RANGE`. Some of you services use NodePort outside of the "30000-32767" default range and we were unable to test them in Vagrant. the ubuntu provider does allow this, but none of the other providers do it seems, so we patched it.

**Comment by bmeck** [comment]
@thockin maybe i could have been clearer. We are testing **our** Services on Kubernetes. I don't know of any in the Kubernetes codebase itself that are outside that range.

**Comment by thockin** [comment]
Ahh.  The risk of changing this range is that any Service that uses a
NodePort will get a random assignment from this range.  For example, if you
set it to 1-1000; some service might randomly get port 80 or port 22.  It's
probably OK for Vagrant since it is not a "production" environment really.
NodePort is not really intended to be a user-facing port but instead to
build higher-level ingress.

**Comment by thockin** [comment]
@derekwaynecarr since vagrant

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by thockin** [comment]
CI fail: Found illegal 'flag' usage. If these are false positives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.

**Comment by derekwaynecarr** [comment]
Taking this review, it needs a rebase.  poke when rebased, and look forward to getting merged.

**Comment by thockin** [comment]
This is at risk of being kicked out of the milestone if it is not cleared up soon.

**Comment by wojtek-t** [comment]
@bmeck - please rebase

**Comment by thockin** [comment]
This needs a rebase today or it is not going to make the 1.2.0 release

**Comment by derekwaynecarr** [comment]
I am going to close this, feel free to re-open when rebased.

**Pull request closed without merging**
