### PR TITLE
Interactive filter pods in logs command

### PR DESCRIPTION
**Pull request by kaplanelad**
**What type of PR is this?**

/kind feature

**why we need it:**

In order to get pod logs we need exact name is required and the namespace as well, something like:

1) `kubectl get pods -n <namespace>`

2) `kubectl logs -f <pod name> ...`

This is less efficient and can be done in a more user friendly way.
 
**What this PR does:**

I would like to create a new flag that will allow fuzzy searching of some pod name and see the logs easier.

I have added a new flag (--like) into kubectl logs subcommand, by default the flag is false (to preserve backwards behavior )

**For example:**

This is the result of` kubectl get pods`

image

We want to only access pods of the deployment:  **foo-deployment**

Then:
`kubectl logs --like foo`

The result of the command will present a table with all the pod's that matches the query `-like <query>`

image

**Special notes for your reviewer**:
I have added unit-tests for the new logic, please let me know if further modification are required  

**Does this PR introduce a user-facing change?**:
```release-note
kubectl/logs new flag: --like (off by default) allows for fuzzy search of pods and quick logs access. Action required: upgrade kubectl 

kubectl logs --like foo
```

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hey @tanjunchen,
I’d like to kindly ping you and ask what is the current status of the PR?

**Comment by kaplanelad** [comment]
Hey @liggitt, 
Can you please help me to push this PR?

**Comment by liggitt** [comment]
Thanks for the PR, but it's not clear this approach is desired in kubectl.

> We want to only access pods of the deployment: **foo-deployment**

That can be accomplished with a label selector that makes use of the deployment's selector. For example: `kubectl logs -l app=foo`

> The result of the command will present a table with all the pod's that matches the query -like <query>

kubectl does not currently include interactive flows. If you want to propose changing this approach, discussing it with [sig-cli](https://github.com/kubernetes/community/tree/master/sig-cli#contact) and opening a [proposal](https://github.com/kubernetes/enhancements/tree/master/keps/#kubernetes-enhancement-proposals-keps) would be the best place to start. If this is not accepted within kubectl, you can also build this functionality as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).

/close

**Pull request closed without merging**
