### PR TITLE
Update man page info for advanced kubelet features i.e. config/bootst…

### PR DESCRIPTION
**Pull request by jayunit100**
this should clarify some stuff we need to do for HA deployments.

### CODE REVIEW

**Comment by jayunit100** [comment]
Related to man page updates  #9703 .  Maybe they can be glommed into this PR so they both go in together?

**Comment by dchen1107** [comment]
lgtm

**Comment by satnam6502** [comment]
Please can the formatting in this be fixed?
The use of double quotes is a bit strange. And there should be bullet list of items rather than a code block.

**Comment by jayunit100** [comment]
sure , i can do that.

**Comment by jayunit100** [comment]
hiya satnam...  which *code block* are you talking about?

**Comment by satnam6502** [comment]
The one just after  "There are 3 ways that a container manifest can be
provided to the Kubelet:"

**Comment by jlowdermilk** [comment]
Removing lgtm, reassigning to @satnam6502 for unaddressed comments.

**Comment by jayunit100** [comment]
Okay i tried to redo it again.  like i said happy to close this also if someone else wants to take a stab.

**Comment by jayunit100** [comment]
ok, shall we put this one in @satnam6502 ? or close and someone else redo?

**Comment by satnam6502** [comment]
I am happy to try an review this but I think someone in @dchen1107 's team might be a better pick?

**Comment by jayunit100** [comment]
The content is the same as the one Dawn has LGTM'd already, only diff is i added a few minor changes you suggested/  So if you're ok, i think we're ok :)

**Comment by satnam6502** [comment]
Ah, yes, much better now,

**Comment by a-robinson** [comment]
This needs a rebase before it can be merged.

**Comment by jayunit100** [comment]
ok will do.

**Pull request merged**
