### PR TITLE
AWS: Add docs to volumes.md to describe how to use EBS volumes

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by bprashanth** [comment]
LGTM, jenkins isn't going to test this anyway and shippable is green. This is a doc fix, so we don't need to wait on lgtm from leads, will merge during next widow.

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
@ixdy

```
Build timed out (after 30 minutes). Marking the build as failed.
/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/util.sh:
line 1:  7905 Terminated              sleep 2
Build was aborted
```

**Comment by yujuhong** [comment]
Merging since this is a doc fix, and shippable passed.

**Comment by ixdy** [comment]
It seems like the cluster failed to start up, which is indeed very odd for a doc-only change:

```
Managed instance group pull-e2e-1-minion-group is being created. Operation: operation-1436153949100-51a2ca5fa97e0-aa2ec2f9-6ffed2cf
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 0 out of 2 running. Retrying.
Waiting for minions to run. 1 out of 2 running. Retrying.
MINION_NAMES=pull-e2e-1-minion-lanx pull-e2e-1-minion-to8u
Using master: pull-e2e-1-master (external IP: 104.197.0.237)
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Build timed out (after 30 minutes). Marking the build as aborted.
```

The very next build, an hour later, using the exact same names, passed without issue.

**Pull request merged**
