### PR TITLE
Automated cherry pick of #78012: Upgrade Azure network API version to 2018-07-01

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #78012 on release-1.13.

#78012: Upgrade Azure network API version to 2018-07-01

### CODE REVIEW

**Comment by justaugustus** [comment]
For SIG Azure & SIG Release:
/lgtm
/approve

**Comment by feiskyer** [comment]
@dims Could you help to approve the go modules updates?

**Comment by tpepper** [comment]
/hold

Why is this not a feature?

**Comment by feiskyer** [comment]
> Why is this not a feature? I get the rationale in #78065 for master, but here I'm not as convinced it applies.

it's a bug fix: without this, if users have configure EnableTcpReset on their loadbalancer, then all Kubernetes LoadBalancer services would be stuck in pending state.

**Comment by justaugustus** [comment]
I'm okay with the rationale here, so I'm lifting the hold. This should enable much smaller, concise bug fixes for Azure services once merged.
/hold cancel

**Comment by justaugustus** [comment]
Looks like @dims is not a dep approver on `release-1.13`, so this still needs approval:
/assign @cblecker @thockin @sttts

**Comment by cblecker** [comment]
We really need to get this Azure cloud provider out of tree ASAP. The fact that a load balancer bug fix causes a 19k LOC vendor change isn't sustainable.

Need to review this closely..

/hold

**Comment by feiskyer** [comment]
> We really need to get this Azure cloud provider out of tree ASAP. The fact that a load balancer bug fix causes a 19k LOC vendor change isn't sustainable.

There's still much work to do before out-of-tree cloud provider. And most of those changes are vendor update, so I think it's ok for cherry picking.

**Comment by cblecker** [comment]
Still thinking about this, but I'm gonna take a look after 1.15's code freeze on Thursday. So either Friday or early next week. Thanks for your patience, just need to prioritize.

**Comment by feiskyer** [comment]
ping @cblecker

**Comment by tpepper** [comment]
I'm uncomfortable with this change similar to Jordan's comment at https://github.com/kubernetes/kubernetes/pull/78066#issuecomment-498691090 but also for the reasons listed there (isolation to Azure and their emphasis on this as critical fix) I'm going to grudgingly approve this.

**Pull request merged**
