### PR TITLE
Bump github.com/google/certificate-transparency-go to v1.0.21

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Bump github.com/google/certificate-transparency-go to v1.0.21 to pull in https://github.com/google/certificate-transparency-go/commit/37a384cd035e722ea46e55029093e26687138edf. This fixes a typecheck error on this library.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Fixes this typecheck failure:
```
2018/10/03 22:56:45 Code for OpenAPI definitions generated
ERROR(windows) vendor/github.com/google/certificate-transparency-go/x509/root_windows.go:112:20: cannot use uintptr(unsafe.Pointer(sslPara)) (value of type uintptr) as syscall.Pointer value in struct literal
exit status 1
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
```

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by ixdy** [comment]
It looks like this dep was added in #60373 to update cfssl to be compatible with go1.10.
cc @sttts

**Pull request merged**
