### PR TITLE
CHANGELOG: fix hyperlink failure for issue

### PR DESCRIPTION
**Pull request by 249043822**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/ok-to-test
/release-note none
/sig release

**Comment by 249043822** [comment]
/ assgin @saschagrunert @cpanato

**Comment by saschagrunert** [comment]
We probably should fix those in the release notes draft rather than here:
https://github.com/kubernetes/sig-release/blob/master/releases/release-1.20/release-notes-draft.md

**Comment by 249043822** [comment]
Hi @saschagrunert  Should 1.18 and 1.19 release-notes be fixed here?  only 1.20 draft

**Comment by saschagrunert** [comment]
> Hi @saschagrunert Should 1.18 and 1.19 release-notes be fixed here? only 1.20 draft

Yep, since 1.20 is the only one which is work in progress for now.

**Comment by 249043822** [comment]
@saschagrunert I have updated the change in this pr.

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
