### PR TITLE
Fix GCE typo in test output

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix GCE typo in test output

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by zouyee — APPROVED** [review]

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
