### PR TITLE
remove useless code in podautoscaler

### PR DESCRIPTION
**Pull request by bonowang**
**What this PR does / why we need it**:
code optimization,remove some useless code.

**Special notes for your reviewer:**
My first Kubernetes PR，please let me know if anything wrong on this one.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
please fix the release note field and actually put a PR body in place.

**Comment by bonowang** [comment]
Do you mean i need fix this in release 1.7? sorry ,this is my first PR, i dont konw your mean very well. @DirectXMan12

**Comment by bonowang** [comment]
@DirectXMan12 Hi, release note field and PR body is done，please check.

**Comment by bonowang** [comment]
Hi,is there anything else I should to do for this PR？ @DirectXMan12 @jszczepkowski

**Comment by bonowang** [comment]
@shiywang hi shiywang, Can you help me to check this PR? This PR is total same as previous one, and commits are squashed. Thanks

**Comment by bonowang** [comment]
Hi, pull-kubernetes-e2e-kops-aws is test failed two times,now is even get stuck
image
Is there anything else  i can do now? Thanks
@shiywang

**Comment by xiang90** [comment]
why the error at line 252 is ignored?

**Comment by bonowang** [comment]
> why the error at line 252 is ignored?
func GetMetricUtilizationRatio only for some math calculations,has no error return.

**Comment by xiang90** [comment]
@bonowang 

Right. Looks good to me then.

**Comment by bonowang** [comment]
the check finally complete, can you please add lgtm label if the PR is looks good to you 

@shiywang

**Comment by bonowang** [comment]
/assign @bprashanth @deads2k  for approve 

This is a small bug fix, is it possible to get an /approve no-issue on this PR?

**Comment by bonowang** [comment]
@deads2k @bprashanth 
Hi , can you help to approve this PR? Thanks

**Comment by bonowang** [comment]
Thank you all the help for my frist PR.

**Pull request merged**
