### PR TITLE
Rolling Updates: Add support for --rollback.

### LINKED ISSUE #4140: Gracefully fail a rolling update?
I accidentally created an entry in the new replication controller to pull an image that doesn't exist.

The rolling update is killing the known good containers and stuck trying to pull down the nonexistent image.

Is there a way to gracefully fail a rolling update if an image can't be pulled?

### PR DESCRIPTION
**Pull request by brendandburns**
@ghodss @jlowdermilk @deads2k @ironcladlou 

Fixes #4140

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Looks good, though I would prefer `--rollback` as the flag name. `kubectl rolling update --abort` doesn't do a good job of conveying "do a rolling update but in reverse". Will see what others think.

**Comment by bgrant0607** [comment]
I also am not a fan of abort. I believe @thockin feels similarly.

**Comment by bgrant0607** [comment]
Fixes #4140

**Comment by bgrant0607** [comment]
Previous discussion:
https://github.com/GoogleCloudPlatform/kubernetes/pull/6713#discussion_r28818999

**Comment by brendandburns** [comment]
I don't super care.  If the preference is for ```--rollback``` I will switch this PR, and update the docs.  Please let me know, I'd like to get this merged.

**Comment by bgrant0607** [comment]
I'm fine with either --abort or --rollback, and will accept the consensus. When talking about it, I'm sure I'll continue to say "rollback". 

Additionally, FWIW, a reasonably common pattern internally is for teams to leave the old template around until the next rollout, to facilitate easy rollback. I'd like to expose the "preserve" cleanup policy and would like to support rollback/abort in the scenario where the rollout actually completed but the old RC was not deleted. Don't know if that changes your opinion about which is more appropriate or not.

**Comment by ironcladlou** [comment]
Thinking about this feature in the context of #1743, what effect would this feature have on the proposed monotonic revision number for deployments?

**Comment by brendandburns** [comment]
@ironcladlou I don't think it should have any effect.  At the API level, this is actually a roll-forward to the old version.

That said, maybe you actually want the revision number to rewind?

Can we have a vote on --rollback vs. --abort?  I'd like to get this PR merged.

**Comment by ironcladlou** [comment]
Allow me to cast my vote for...

**--rollback**

**Comment by derekwaynecarr** [comment]
--rollback

**Comment by pmorie** [comment]
--rollback (fwiw)

**Comment by brendandburns** [comment]
Switched to ```--rollback``` by popular opinion.  Updated docs to match.

ptal
Thanks!
--brendan

**Comment by jlowdermilk** [comment]
lgtm. will merge on green if no objections

**Comment by bgrant0607** [comment]
There's no test. Did you at least try this? 

The rename cleanup policy is the default. Does that make sense in this case?

**Comment by brendandburns** [comment]
Yes, this has been manually tested.  Without a better test framework in place this is tricky to test in an automated way.  I could probably get something going in test-cmd.sh if that is required.

Thanks
--brendan

**Comment by jlowdermilk** [comment]
lgtm, but you should probably change the commit description

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
The commit description does still refer to --abort

**Comment by brendandburns** [comment]
Changed the commit description.

Thanks!
--brendan

**Pull request merged**
