### PR TITLE
pod format refactor in kubelet util

### PR DESCRIPTION
**Pull request by qingwave**
Signed-off-by: qingwave <isguory@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Make function [PodWithDeletionTimestamp] (https://github.com/kubernetes/kubernetes/blob/5323d9213a8c68f9279b3b73fc65c663febcfe16/pkg/kubelet/util/format/pod.go#L46) more clearer in `pkg/kubelet/util/format/pod.go` and fix typo

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@qingwave Thank you for your PR!

Is `PodWithDeletionTimestamp` used anywhere except of its own test?

**Comment by qingwave** [comment]
> @qingwave Thank you for your PR!
> 
> Is `PodWithDeletionTimestamp` used anywhere except of its own test?

Hi @bart0sh, seems the function is used just in the test, I cannot find other references. Should we remove this function?

**Comment by bart0sh** [comment]
Yes, I think it makes sense to remove it and its test. And please try to find more pieces of unused code to add to this PR.
See [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) for more details.

**Comment by bart0sh** [comment]
@qingwave btw, it probably makes sense to close this PR and open new one.

**Comment by qingwave** [comment]
> btw

okay

**Pull request closed without merging**
