### PR TITLE
Move pkg/kubectl/util/deployment to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/util/deployment` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util/deployment.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
@seans3 this needs rebase

**Comment by seans3** [comment]
> Sean Sullivan this needs rebase

Every single one of the `kubectl/util` to `staging` PR's will need a rebase. We've ordered the merges in the document. Just so I don't have to rebase multiple times, I'm going to wait until it is the turn of this PR.

**Comment by apelisse** [comment]
/approve

For `vendor/modules.txt`

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
