### PR TITLE
fix typo in kubectl doc

### PR DESCRIPTION
**Pull request by mookjp**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

* `newName` is the collect key to be configured

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mookjp** [comment]
@seans3 @neolit123 Sorry for my many attempts around tets but could you review this? Thanks!

**Comment by mookjp** [comment]
@mengqiy @juanvallejo Could you review it? Thanks in advance.

**Comment by mookjp** [comment]
@seans3 @mengqiy @juanvallejo Sorry for mentioning you in several times but could you check it again?

**Comment by eddiezane** [comment]
Thanks for this PR and apologies for the delay!

We'll be merging https://github.com/kubernetes/kubernetes/pull/89086 instead as it fixes another typo.

/close

**Pull request closed without merging**
