### PR TITLE
Container bridge salt fix

### PR DESCRIPTION
**Pull request by brandonsdavis**
A recent change to Salt, [22080](https://github.com/saltstack/salt/issues/22080), broke the container_bridge.py script. This updates the module and method name that were changed.

### CODE REVIEW

**Comment by thockin** [comment]
AFAIK we don't need this file at all anymore - right Dawn?

@dchen1107

**Comment by ocsbrandon** [comment]
@thockin, @dchen1107 It might not be needed. I was debugging another issue in my setup and came across the error in /var/log/salt/minion on the master. It didn't fix my issue, but thought I would send it over anyway.

**Comment by thockin** [comment]
Appreciate it.  I don't find any reference to it anywhere else in the
codebase.

**Comment by dchen1107** [comment]
@thockin Yes, we don't need this python script to configure cbr0 and iptables anymore. Now they all are handled by kubelet. I will send pr to remove this from our source base shortly.

@ocsbrandon Thanks for your pr. If you sync your source tree to HEAD, you will find no cloud providers today require this script at boot time anymore. Thanks.

**Comment by zmerlynn** [comment]
Thanks for the submission! I'll take a PR that removes the file. Right now, your branch is cluttered with commits that aren't your own, probably because it looks like you're trying to push a merge commit - which is generally a bad idea.

**Comment by dchen1107** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/10558

**Comment by dchen1107** [comment]
I am going to close this pr. Thanks for helping us improving our system, and looking forward to hearing from you more.

**Pull request closed without merging**
