### PR TITLE
Automated cherry pick of #15287 to upstream release 1.1

### PR DESCRIPTION
**Pull request by davidopp**
Automated cherry pick of #15287 to upstream release 1.1

@mikedanese

### CODE REVIEW

**Comment by dalanlan** [comment]
Thank you so much for this :)
Also I was wondering whether common contributors could send a pr to ask for a cherry pick or not.

**Comment by davidopp** [comment]
The process for creating a cherrypick PR is described here
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

Contributors are welcome to propose cherrypicks of PRs they authored by using the above tool, though probably it's better to just request it in the original PR and one of the maintainers will do it.

**Comment by dalanlan** [comment]
Yeah i'm fully aware of that. Yet I didn't get any response of #11727 for such a long time and couldn't help asking. Thanks again.

**Comment by davidopp** [comment]
Sorry about that. I think you just got unlucky with #11727. You should always feel free to ping again if you don't get a response. You can also ping the support oncall by adding @k8s-support-oncall  to an issue. (Don't worry, even though this is called an oncall, nobody gets paged.)

**Pull request merged**
