### PR TITLE
move pkg/storage to apiserver

### PR DESCRIPTION
**Pull request by deads2k**
Mechanical move of `pkg/storage` (not sub packages) to `k8s.io/apiserver`.

@sttts

### CODE REVIEW

**Comment by deads2k** [comment]
approved based on https://github.com/kubernetes/kubernetes/issues/40363

**Comment by deads2k** [comment]
@apelisse looks like commenting causes my pull to enter the submit queue

**Comment by deads2k** [comment]
like it somehow triggers the bot to recheck status

**Comment by apelisse** [comment]
@deads2k Indeed, updating the pull-requests triggers a recheck. I know where this is coming from, not sure exactly why though.

**Comment by deads2k** [comment]
trigger bot

**Comment by deads2k** [comment]
Kick bot

**Comment by smarterclayton** [comment]
Bot has left the room.

**Comment by sttts** [comment]
@kubernetes/kubernetes-build-cops submit queue doesn't see this PR. It's not picked up and it is not visible in the PR overview.

**Comment by sttts** [comment]
Ok, disregard. Not-updated github tab in the browser. It got merged last night.

**Pull request merged**
