### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Fix some typos

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by idealhack** [comment]
Please combine multiple typo fixes in one PR to save reviewers time.

**Comment by xichengliudui** [comment]
How do I remove the 'needs-kind' label?

**Pull request merged**
