### PR TITLE
remove todo use AddGeneratorFlags replace other generator commands flags

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
/unassign
/assign fabianofranz

You know what I think of generators.  Not sure what the current state in the sig is.

**Comment by zjj2wry** [comment]
@deads2k Is user don't has generator can select？and we will not use generator add command？

**Pull request closed without merging**
