### PR TITLE
Remove extraneous curl, pods, etc from privileged pod test

### PR DESCRIPTION
**Pull request by bowei**
Removing unneeded dependencies that hopefully will reduce test noise.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37647)

**Comment by bowei** [comment]
Relates to https://github.com/kubernetes/kubernetes/issues/37641

@dchen1107 @saad-ali

**Comment by dchen1107** [comment]
LGTM

**Comment by bowei** [comment]
@saad-ali

**Pull request merged**
