### PR TITLE
Save integration test results in junit-style XML report on Shippable

### PR DESCRIPTION
**Pull request by ixdy**
This is basically a follow-on to #13114. It appears to work correctly locally.

cc @kubernetes/goog-testing

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Shippable looks like a flake, probably due to insufficient shippable resources (again).

=== RUN TestWatch
--- FAIL: TestWatch (2.00s)
	resttest.go:977: unexpected timeout from result channel

I reran shippable.

**Comment by quinton-hoole** [comment]
GCE e2e test failure was probably due to #13534 which is now fixed. Rerunning to hopefully trigger auto-merge by the merge-bot.
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
e2e failure is due to github fetch failing, seemingly due to github closing the connection.  Retrying...

```Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
Another shippable flake.  I kicked her again.

**Comment by ixdy** [comment]
Looking at the shippable results, I realized that it's no longer saving the test report in the correct place. Working on a fix now...

**Comment by ixdy** [comment]
I replaced `$(pwd)` with `${SHIPPABLE_REPO_DIR}`, which should hopefully do the right thing now.

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Pull request merged**
