### PR TITLE
tweak a list to a watch verb when requested

### PR DESCRIPTION
**Pull request by deads2k**
Related to https://github.com/kubernetes/kubernetes/pull/41774

@wojtek-t does this do what's needed?

### CODE REVIEW

**Comment by deads2k** [comment]
Confirmed that `curl http://localhost:8080/api/v1/pods?watch=true` produces "WATCH".

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by deads2k** [comment]
pod autoscaler

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by liggitt** [comment]
@wojtek-t were you going to revert https://github.com/kubernetes/kubernetes/pull/41774 once this merges?

**Comment by wojtek-t** [comment]
@liggitt - sure will do

**Pull request merged**
