### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Update vendor/sigs.k8s.io/structured-merge-diff

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
I ended-up re-merging master in this branch because verify failed because of swagger being removed. And then I realized that I messed-up the last merge with master so I've had conflicts everywhere. Anyways, it should mostly be good now ...

**Review by Rajat-0 — COMMENTED** [review]
Why we are removing the json files?

**Comment by apelisse** [comment]
The swagger json are removed because they have all been removed with the swagger in master.

**Comment by apelisse** [comment]
@BenTheElder CLA's failing on this one, not exactly sure why ... can we bypass somehow?

**Comment by bgrant0607** [comment]
This is a limitation of the CLA bot when sending a PR that includes comments from a large number of users. I think it's fine to merge this merge into the branch and then diff the branch with master again to validate that it's what is expected.

**Comment by bgrant0607** [comment]
We used to have this problem when bulk-merging commits from the master branch into the release branch, but I didn't see a case where we've done that recently.

**Comment by BenTheElder** [comment]
Sounds reasonable to me :+1: 
Note this will not merge just by applying the CLA label now, we have GitHub branch merge protections enabled that require passing tests for blocking presubmits including `cla/linuxfoundation`. I beleive the options for that are either:
- a repo admin uses the prow command `/override status-name` to bypass this (so comment `/override cla/linuxfoundation`) https://prow.k8s.io/command-help
- a repo admin uses their permissions to bypass the protections and manually merge -- Not recommended, my clash with the merge robot and leave us in a conflicted state code-wise

Generally we discourage both of these, but I think this is the situation that calls for `/override`. Only GitHub repo administrators may use this command.

**Comment by apelisse** [comment]
My understanding is that we're trying to merge back a commit from `Anago GCB <nobody@k8s.io>` whose address clearly doesn't map to an actual user. 

[Example](https://github.com/kubernetes/kubernetes/pull/73042/commits/3287dec0725e65bb93f5598c0d07acbc4dff42eb) of such a commit in this pull-request.

I found this commit by carefully going through the list of commits on github until I could find a user that didn't have a picture. Since github only shows 250 commits, I'm glad that his one was being displayed in the list (otherwise, I could have found it).

**Comment by apelisse** [comment]
OK, I'm looking for a repo admin to run ...

/override cla/linuxfoundation

@thockin @cblecker maybe?

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/community/tree/master/github-management#github-administration-team

**Comment by grodrigues3** [comment]
> Note this will not merge just by applying the CLA label now, we have GitHub branch merge protections enabled that require passing tests for blocking presubmits including

With the understanding that this will not merge immediately,


/override cla/linuxfoundation

**Comment by BenTheElder** [comment]
`override` is now enabled for this repo specifically (https://github.com/kubernetes/test-infra/pull/10843)

**Comment by cblecker** [comment]
Okay, let's try this..
/override cla/linuxfoundation

**Comment by cblecker** [comment]
/hold
Looks like it worked. Is this ready to actually merge @apelisse?

**Comment by cblecker** [comment]
ohhh.. hmm.. the CLA context updates anytime someone comments >_<

**Comment by cblecker** [comment]
well.. looks like tide decided to merge it anyways!

**Comment by apelisse** [comment]
Perfect, it was ready yes :-)

**Comment by cblecker** [comment]
Great! Let me know if you run into any problems.

cc: @kubernetes/owners

**Pull request merged**
