### PR TITLE
WIP: Add a non-preempting PriorityClass

### LINKED ISSUE #67671: Non-preempting PriorityClass
As of Kubernetes 1.11, [Pod priority and preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) is a beta feature. In the existing version, any Pod could possibly preempt other Pods if it has higher priority than the preemption victims and the cluster does not have enough capacity to run it.
We would like to add a new feature that allows certain PriorityClasses to be defined as non-preempting priority. When a Pod has non-preempting priority, it won't cause preemption when the cluster does not have capacity to run it, but it is still ordered by its priority in the scheduling queue. So, it has a higher chance of getting scheduled than other pending pods with lower priority.

One common use-case for such non-preempting priorities is batch processing. Typical batch jobs run to completion (as opposed to services that keep running). In batch processing, if preemption happens, all the work done by the preemption victim will be lost. As a result, it is often not desired to preempt the existing workload, but priority is still needed to ensure that when new workloads are created those with higher priority go in front the queue and are scheduled ahead of other lower priority workloads when the cluster has more free resources, for example, after currently running workloads are finished.

**Implementation:**
We can add a new field, called `non-preempting` to [PriorityClass](https://github.com/kubernetes/kubernetes/blob/7749eeaf3f1eddd0796a4d61e545a90e7d9d59b0/staging/src/k8s.io/api/scheduling/v1beta1/types.go#L29). When a pod is unschedulable, the scheduler checks this field of its corresponding PriorityClass and starts the preemption process when the field is empty or false. Several points to be considered:
1. All PriorityClasses are considered `preempting` by default. If the filed is missing, the PriorityClass is a preempting one.
2.  A PriorityClass may be deleted after Pod creation. If scheduler cannot find the PriorityClass of a Pod, it assumes that it has `preempting` priority.
3. A Pod may not have any PriorityClass. In that case, its priority is resolved to a defined or implicit default priority. When a Pod priority class is empty, its priority is considered as `preempting`.

To summarize the above rules: "A Pod has `preempting` priority, unless its PriorityClass is found and the `non-preempting` field of the PriorityClass is set to true".

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

/ref #64843
/sig scheduling

### PR DESCRIPTION
**Pull request by vllry**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds a NonPrempting field to the PriorityClass. If set on a class, it will continue to be prioritized above queued pods of a lesser class, but will not preempt running pods.

This PR takes another WIP (#67742), and is an attempt to fix the tests.

See #67671 for more.
**Which issue(s) this PR fixes**:
Fixes #67671

**Special notes for your reviewer**:
This is still a WIP

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by bsalamat** [comment]
Thanks, @vllry! Looks like build is fine now.

**Comment by bsalamat** [comment]
> Yep, now to chase down the next issue. Looks like most things are experiencing scheduling errors.

I wouldn't expect this PR to impact any of our existing tests. It looks like our integration and most of our e2e tests pass. The issue must be something else.

**Comment by vllry** [comment]
I'm suspicious that some of these errors are flake/infra related, but I did replicate the scheduling issues  locally with kind and kubetest. Lots of critical pods can't start in this branch - haven't managed to determine why yet.

**Comment by vllry** [comment]
@bsalamat I tried re-generating files, but there's no changes. fa147f2 definitely introduced the problem, but it contains a number of non-autogenerated changes by the look of it. I'll probably try manually reverting some of those, since I haven't made headway with just reading cluster/test output.

**Comment by vllry** [comment]
Made a useful discovery: the scheduler is having access errors for PriorityClasses.

````{"log":"E0130 04:13:33.032807       1 reflector.go:134] k8s.io/client-go/informers/factory.go:132: Failed to list *v1beta1.PriorityClass: priorityclasses.scheduling.k8s.io is forbidden: User \"system:kube-scheduler\" cannot list resource \"priorityclasses\" in API group \"scheduling.k8s.io\" at the cluster scope\n","stream":"stderr","time":"2019-01-30T04:13:33.033238697Z"}```

Indicates a missing RBAC binding.

**Comment by bsalamat** [comment]
Good catch, @vllry! You also need to run the bootstrap policy again to update the expected policies. You should be able to do that by running:
`UPDATE_BOOTSTRAP_POLICY_FIXTURE_DATA=true make test WHAT=./plugin/pkg/auth/authorizer/rbac/bootstrappolicy`

**Comment by vllry** [comment]
Still working on the field mutation happening in TestRoundTripTypes.

**Comment by vllry** [comment]
Work is continuing in another branch/PR, closing.

**Pull request closed without merging**
