### PR TITLE
Clean up pre-ControllerRef compatibility logic

### LINKED ISSUE #43323: Clean up pre-ControllerRef compatibility logic
As of 1.6, most workload controllers respect [ControllerRef](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md) to avoid interfering with each other. However, kubectl 1.6 still had to support talking to a 1.5 server, so client-side compatibility logic was introduced in #43114 and #43239.

According to the [version skew guidelines](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#supported-releases-and-component-skew), we no longer need to support talking to 1.5 servers as of the **v1.7** milestone. At that time, the added compatibility functions (ending in `V15`) can be removed and replaced with calls to the normal 1.6+ functions (without the suffix).

### PR DESCRIPTION
**Pull request by wanghaoran1988**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #43323 

**Special notes for your reviewer**:
No
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by enisoc** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/controller/deployment/util/deployment_util.go, line 592 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgoiOQ3nUXvRSn0KVjq:-KgoiOQ3nUXvRSn0KVjr:ba2qsu7) ([raw file](https://github.com/kubernetes/kubernetes/blob/b72a3575ae4265dcd3358adb0fbe09b62bf2eda1/pkg/controller/deployment/util/deployment_util.go#L592)):*
> ```Go
> // ListReplicaSetsInternal is ListReplicaSets for internalextensions.
> // TODO: Remove the duplicate when call sites are updated to ListReplicaSets.
> func ListReplicaSetsInternal(deployment *internalextensions.Deployment, getRSList func(string, metav1.ListOptions) ([]*internalextensions.ReplicaSet, error)) ([]*internalextensions.ReplicaSet, error) {
> ```

The body of this function should be updated too. It used to be a copy of `ListReplicaSetsV15()` but with internal types. Now it should be a copy of `ListReplicaSets()` but with internal types.

---

*[pkg/kubectl/stop.go, line 366 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgokqRRDHSv0TU544JT:-KgokqRRDHSv0TU544JU:bg1kplx) ([raw file](https://github.com/kubernetes/kubernetes/blob/7543bac56342fddaaadcfe555ad500a19dabf611/pkg/kubectl/stop.go#L366)):*
> ```Go
> 		// that do use ControllerRef.
> 		controllerRef := controller.GetControllerOf(pod)
> 		if controllerRef != nil && controllerRef.UID != ss.UID {
> ```

Removing this check would actually take us back from transitional logic to the pre-ControllerRef logic. Since we no longer need to be compatible with talking to a v1.5 server, we can instead move to full post-ControllerRef logic.

That is, we can require the ControllerRef to both exist and point to the given StatefulSet, in order to consider it as belonging to the StatefulSet.

I think that should look like this:

```go
// Ignore Pod if it's an orphan or owned by someone else.
if controllerRef == nil || controllerRef.UID != ss.UID {
  continue
}
```

---

*[test/e2e/upgrades/deployments.go, line 59 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgonHhQUpurcsSITFkt:-KgonHhQUpurcsSITFku:b9hrpr) ([raw file](https://github.com/kubernetes/kubernetes/blob/b72a3575ae4265dcd3358adb0fbe09b62bf2eda1/test/e2e/upgrades/deployments.go#L59)):*
> ```Go
> 	// Wait for it to be updated to revision 1
> 	By(fmt.Sprintf("Waiting deployment %q to be updated to revision 1", deploymentName))
> 	err = framework.WaitForDeploymentRevisionAndImage(c, ns, deploymentName, "1", nginxImage)
> ```

Hm I just realized if we remove the compatibility logic from the upgrade test, we may hit #42738 again **if** we run automated upgrade tests from v1.5 to v1.7. I don't know whether we do automated upgrade testing for the 2 minor version bump.

Even if we do test v1.5 to v1.7 upgrade, it may be worth it to let the Deployment test fail there as a known issue, so we don't have to keep all this otherwise useless compatibility code around. It's really more of a test framework issue that the automated upgrade test is effectively violating the "one minor version" skew between client and server.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942)*

**Comment by wanghaoran1988** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/controller/deployment/util/deployment_util.go, line 592 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgoiOQ3nUXvRSn0KVjq:-Kgx1emOUZhzHMZeYd5y:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/b72a3575ae4265dcd3358adb0fbe09b62bf2eda1/pkg/controller/deployment/util/deployment_util.go#L592)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

The body of this function should be updated too. It used to be a copy of `ListReplicaSetsV15()` but with internal types. Now it should be a copy of `ListReplicaSets()` but with internal types.
</blockquote></details>

Done.

---

*[pkg/kubectl/stop.go, line 366 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgokqRRDHSv0TU544JT:-Kgx4xtnXgzlUWHDb3Ct:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/7543bac56342fddaaadcfe555ad500a19dabf611/pkg/kubectl/stop.go#L366)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

Removing this check would actually take us back from transitional logic to the pre-ControllerRef logic. Since we no longer need to be compatible with talking to a v1.5 server, we can instead move to full post-ControllerRef logic.

That is, we can require the ControllerRef to both exist and point to the given StatefulSet, in order to consider it as belonging to the StatefulSet.

I think that should look like this:

```go
// Ignore Pod if it's an orphan or owned by someone else.
if controllerRef == nil || controllerRef.UID != ss.UID {
  continue
}
```
</blockquote></details>

Done.

---

*[test/e2e/upgrades/deployments.go, line 59 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgonHhQUpurcsSITFkt:-Kgx4jX-VovLwqtJL-T-:bho55t5) ([raw file](https://github.com/kubernetes/kubernetes/blob/b72a3575ae4265dcd3358adb0fbe09b62bf2eda1/test/e2e/upgrades/deployments.go#L59)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

Hm I just realized if we remove the compatibility logic from the upgrade test, we may hit #42738 again **if** we run automated upgrade tests from v1.5 to v1.7. I don't know whether we do automated upgrade testing for the 2 minor version bump.

Even if we do test v1.5 to v1.7 upgrade, it may be worth it to let the Deployment test fail there as a known issue, so we don't have to keep all this otherwise useless compatibility code around. It's really more of a test framework issue that the automated upgrade test is effectively violating the "one minor version" skew between client and server.
</blockquote></details>

Agree, so let's remove the compatibility logic.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942)*

**Comment by enisoc** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/controller/deployment/util/deployment_util.go, line 603 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-Kh4GiyrhfY2IJygP3T1:-Kh4GiyrhfY2IJygP3T2:bjguuel) ([raw file](https://github.com/kubernetes/kubernetes/blob/6383f4dd14d8ddd7fb27e4e0831c46f8163ded4c/pkg/controller/deployment/util/deployment_util.go#L603)):*
> ```Go
> 		return nil, err
> 	}
> 	// Since this function maintains compatibility with v1.5, the objects we want
> ```

Update the comment as well since this is no longer the compatibility version.

---

*[test/e2e/upgrades/deployments.go, line 59 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-KgonHhQUpurcsSITFkt:-Kh4HtE2JGsiW30imkkH:bh9jw48) ([raw file](https://github.com/kubernetes/kubernetes/blob/b72a3575ae4265dcd3358adb0fbe09b62bf2eda1/test/e2e/upgrades/deployments.go#L59)):*
<details><summary><i>Previously, wanghaoran1988 (Haoran Wang) wrote…</i></summary><blockquote>

Agree, so let's remove the compatibility logic.
</blockquote></details>

In that case, let's add to the comment for this `Setup()` function to explain that this calls into client code, and therefore should not be expected to work against a cluster more than one minor version away from the current version.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942)*

**Comment by janetkuo** [comment]
@k8s-bot ok to test

**Comment by wanghaoran1988** [comment]
@enisoc Comments addressed, PTAL

**Comment by enisoc** [comment]
/lgtm

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43942#-:-KhNorgPc36UXXNCV-Zy:b-8ks5qa)*

**Comment by wanghaoran1988** [comment]
@janetkuo Nag, need you approve.

**Review by janetkuo — APPROVED** [review]
Thanks @wanghaoran1988! LGTM

**Pull request merged**
