### PR TITLE
[v1.16.1] informer-gen: allow package names containing dots

### PR DESCRIPTION
**Pull request by nikhita**
xref https://github.com/kubernetes/code-generator/issues/77
xref https://github.com/kubernetes/kubernetes/issues/82860

Before https://github.com/kubernetes/kubernetes/commit/73dc5a96de2836bd7a7fab57241810af47c7e3ee (https://github.com/kubernetes/kubernetes/pull/80440), informer-gen calculated the effective
package name by using the first segment of the groupName.

After the commit, the package name is calculated directly from the
PackageName specified, without any normalizations. This means that if
the actual PackageName contains dots, the effective package name
can now contain dots too. However, this doesn't work well while
parsing files. This also introduced a regression since dots can no longer
be specified in package names.

To fix this, this commit introduces the same normalizations on the
PackageName i.e. the effective package name now uses the first segment
of PackageName.

/assign @sttts @munnerz 

**Does this PR introduce a user-facing change?**:

```release-note
Resolves regression generating informers for packages whose names contain `.` characters
```

### CODE REVIEW

**Comment by munnerz** [comment]
This seems reasonable to me, although it'd be great to see an additional test case added under `_examples` to validate the change, and also explain what it's doing 😄

**Comment by munnerz** [comment]
This *is* also a regression that can't be worked around currently, that was introduced in 1.16 (and is not present in 1.15).

For that reason, it'd be *great* if we can get this merged in for 1.16 to avoid 1.16 being a 'bad version' for some users of code-generator.

The actual impact of this change should be nil for Kubernetes core (as demonstrated by this PR 😄)

**Comment by nikhita** [comment]
Updated with tests. However, I had to rename `example2` to `example2.io` instead of adding a `example3.io` because the `groupGoName` tag doesn't work well if more than two groups have the same prefixes (`example` in this case).

We should look into fixing that, but IMHO that's orthogonal to the current issue and shouldn't be a blocker for this one.

If we use `group3.io`, it leads to a weird generated code, something like:

```diff
--- a/staging/src/k8s.io/code-generator/_examples/apiserver/informers/internalversion/generic.go
+++ b/staging/src/k8s.io/code-generator/_examples/apiserver/informers/internalversion/generic.go
@@ -58,6 +58,14 @@ func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource
                return &genericInformer{resource: resource.GroupResource(), informer: f.Example().InternalVersion().TestTypes().Informer()}, nil
 
                // Group=example.test.apiserver.code-generator.k8s.io, Version=internalVersion
+       case example2.SchemeGroupVersion.WithResource("testtypes"):
+               return &genericInformer{resource: resource.GroupResource(), informer: f.ThirdExample().InternalVersion().TestTypes().Informer()}, nil
+       case example2.SchemeGroupVersion.WithResource("testtypes"):
+               return &genericInformer{resource: resource.GroupResource(), informer: f.ThirdExample().InternalVersion().TestTypes().Informer()}, nil
+
+               // Group=example.test.apiserver.code-generator.k8s.io, Version=internalVersion
+       case example2.SchemeGroupVersion.WithResource("testtypes"):
+               return &genericInformer{resource: resource.GroupResource(), informer: f.SecondExample().InternalVersion().TestTypes().Informer()}, nil
        case example2.SchemeGroupVersion.WithResource("testtypes"):
                return &genericInformer{resource: resource.GroupResource(), informer: f.SecondExample().InternalVersion().TestTypes().Informer()}, nil

```

**Review by aanm — APPROVED** [review]
Thank you @nikhita!

**Comment by sttts** [comment]
Is this is now the same behaviour that client-gen has? I.e. support for GroupName and GroupGoName.

**Comment by liggitt** [comment]
please add to the known issues list for for v1.16.0 (https://github.com/kubernetes/kubernetes/issues/81930) if this will not be resolved until v1.16.1

**Comment by yue9944882** [comment]
Fixes: #82860

**Comment by liggitt** [comment]
can we also ensure the fix is in its own commit for picking to 1.16.1 in case the example changes do not pick cleanly?

**Comment by liggitt** [comment]
is the fix contained to f90c04abb12ee037c8cc7552d7ea9ca71c983893?

looks like a legitimate verify CI error

**Comment by liggitt** [comment]
bumping priority since this breaks consumers of 1.16-level generation tools

**Comment by nikhita** [comment]
Sorry for the delay here, just back from vacation.

Updated with a new example so that even they can be picked cleanly, if needed.

> Is this is now the same behaviour that client-gen has? I.e. support for GroupName and GroupGoName.

Yes. The new example uses `+groupName=example.dots.apiserver.code-generator.k8s.io` (same `example` prefix as before) and `+groupGoName=ThirdExample` (example2 uses SecondExample as groupGoName).

> is the fix contained to f90c04a?

Yes. Fwiw all changes (including the examples) are picked cleanly.

> looks like a legitimate verify CI error

The error was because of updating the current example. Added a new example, so this shouldn't occur anymore.

**Comment by nikhita** [comment]
> please add to the known issues list for for v1.16.0 (#81930) if this will not be resolved until v1.16.1

https://github.com/kubernetes/kubernetes/pull/83023

**Comment by nikhita** [comment]
Err...I didn't know PRs could be closed like that.

**Comment by liggitt** [comment]
pick open at https://github.com/kubernetes/kubernetes/pull/83077

**Pull request merged**
