### PR TITLE
CHANGELOG/OWNERS: Add simcard0000 as reviewer

### PR DESCRIPTION
**Pull request by pmmalinov01**
Signed-off-by: Pavel Malinov <pmmalinov01@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This finalized release note team members:

- Org membership [2683](https://github.com/kubernetes/org/issues/2683) for @simcard0000 has been resolved by PR [2690](https://github.com/kubernetes/org/pull/2690O) and should be added to reviewers

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Damans227 — APPROVED** [review]
\lgtm

**Comment by pmmalinov01** [comment]
@justaugustus You approved the last change in [101754](https://github.com/kubernetes/kubernetes/pull/101754) Can you do the same for this one :)

**Review by justaugustus — APPROVED** [review]
/retitle CHANGELOG/OWNERS: Add simcard0000
/lgtm
/approve

**Pull request merged**
