### PR TITLE
Track ready pods in Job status

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind feature
/kind api-change
/sig apps

#### What this PR does / why we need it:

Add field .status.ready to track the number of ready pods in a Job.

The feature is guarded by feature gate JobReadyPods. To reduce the number of Job status updates that this new tracking might cause, Pod updates are batched in intervals of 0.5s.

#### Which issue(s) this PR fixes:

Ref kubernetes/enhancements#2879

#### Special notes for your reviewer:

First commit has the API changes.

I couldn't find a significant difference in the runtime of the integration tests between different batch periods. I'm leaving this at 0.5s to be conservative. We can reconsider when going to beta.

#### Does this PR introduce a user-facing change?

```release-note
Track the number of Pods with a Ready condition in Job status. The feature is alpha and needs the feature gate JobReadyPods to be enabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2879-ready-pods-job-status
```

### CODE REVIEW

**Comment by fedebongio** [comment]
Consensus that this is mostly sig apps
/remove-sig api-machinery

**Review by soltysh — APPROVED** [review]
/triage accepted
/priority backlog
/lgtm
/approve
for both controller and cli bits

**Review by roycaihw — COMMENTED** [review]
API review: Please add validation for this new field: it cannot be negative. Looks good in general

**Review by alculquicondor — COMMENTED** [review]
Also added validation for non-negative ready field.

**Comment by liggitt** [comment]
`staging/src/k8s.io/api/testdata/v1.22.0/batch.v1.Job.after_roundtrip.pb` shouldn't have a diff now that the field is a pointer

**Comment by alculquicondor** [comment]
Removed the roundtrip file

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
