### PR TITLE
Allow to use an existing subnet when IP aliases are enabled on GCE.

### PR DESCRIPTION
**Pull request by jingax10**
**What this PR does / why we need it**:

Without this PR, we are not able to create a K8s cluster with IP alias on an existing subnet (with secondary ranges) on GCE.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
"NONE"
```

### CODE REVIEW

**Comment by bowei** [comment]
Don't we also need to turn off subnetwork creation? (Isn't there code for that as well?)

**Comment by jingax10** [comment]
My change would automatically bypass subnetwork creation as subnet will not be NULL in line 1902. Instead, it will check whether 2 secondary ranges exist if IP alias is enabled in the else branch.

**Comment by bowei** [comment]
hey -- how does this skip the subnetwork creation logic?

**Comment by jingax10** [comment]
> hey -- how does this skip the subnetwork creation logic?

$SUBNETWORK will be initialized in detect-subnetwork if there is any.

Given $SUBNETWORK is assigned, we populate its value to $IP_ALIAS_SUBNETWORK. As a result, $subnet will be non-empty when describing the $IP_ALIAS_SUBNETWORK and the subnet creation will be skipped.

**Pull request closed without merging**
