### PR TITLE
Fix some golint errors for packages in `pkg/kubectl`

### PR DESCRIPTION
**Pull request by idealhack**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes some parts of #68026

**Special notes for your reviewer**:

Since I’m not very familiar with these packages, I didn't fix those missing comments.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuansisi** [comment]
@idealhack please squash the commits into one.

**Comment by idealhack** [comment]
@yuansisi I don't see any reasons to do so. These commits are fixes by packages.

**Comment by idealhack** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Review by soltysh — APPROVED** [review]
The changes lgtm but like mentioned before, please squash into a single commit. This is all fixing the same thing golint, no need for separate commits.

**Comment by idealhack** [comment]
I think those reviews are here because of my reviews on their PRs, fair enough though.

@soltysh PTAL

**Review by dixudx — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
