### PR TITLE
Upgrade to blang/semver/v4 v4.0.0

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This upgrades blang/semver to blang/semver/v4 v4.0.0, which is the first version to be fully go-mod-compatible (and is the latest published version).

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This does change the external API of `component-base/metrics`, does that count as a user-facing change? It will require any dependencies (_e.g._ `openshift/library-go`) to update their arguments to `Create()`.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @liggitt Jordan, there's a question about this causing a change in how folks use `component-base/metrics`

**Comment by liggitt** [comment]
The go change is fine. I would like to see our dependencies update to this first, so we can drop the `github.com/blang/semver@v3.5.x` version (this PR adds v4 but doesn't drop v3). It looks like that's github.com/google/cadvisor and k8s.io/system-validators

**Comment by skitt** [comment]
> The go change is fine. I would like to see our dependencies update to this first, so we can drop the `github.com/blang/semver@v3.5.x` version (this PR adds v4 but doesn't drop v3). It looks like that's github.com/google/cadvisor and k8s.io/system-validators

Thanks, I was waiting for feedback on the general value of this before pushing upstream changes. I’ve got the system-validators PR ready, I’ll look into cadvisor.

**Comment by skitt** [comment]
It turns out that the cAdvisor bump isn’t needed, upgrading system-validators is sufficient to get rid of the old semver dependency. I’ll update this PR once system-validators is released.

**Comment by neolit123** [comment]
system validators bump:
https://github.com/kubernetes/kubernetes/pull/108988

**Comment by skitt** [comment]
> looks like [google/cadvisor#3078](https://github.com/google/cadvisor/pull/3078) is still not merged.

Yes, but it’s not necessary to get rid of the semver 3.5.1 references.

**Comment by neolit123** [comment]
> Yes, but it’s not necessary to get rid of the semver 3.5.1 references.

are you sure? cadvisor would continue using 3.5.x and we are vendoring cadvisor.

**Comment by liggitt** [comment]
> It turns out that the cAdvisor bump isn’t needed, upgrading system-validators is sufficient to get rid of the old semver dependency. I’ll update this PR once system-validators is released.

the old semver version is still in our graph and still in go.mod:

```
go mod graph | grep " github.com/blang/semver@"
github.com/google/cadvisor@v0.43.0 github.com/blang/semver@v3.5.1+incompatible

grep github.com/blang/semver go.mod
	github.com/blang/semver/v4 v4.0.0
	github.com/blang/semver => github.com/blang/semver v3.5.1+incompatible
	github.com/blang/semver/v4 => github.com/blang/semver/v4 v4.0.0
```

**Comment by liggitt** [comment]
as an intermediate step, this can be ok, but we do need to bump cadvisor to stop depending on the old semver library

**Comment by skitt** [comment]
> > It turns out that the cAdvisor bump isn’t needed, upgrading system-validators is sufficient to get rid of the old semver dependency. I’ll update this PR once system-validators is released.
> 
> the old semver version is still in our graph and still in go.mod:

Ah yes, the package dependency is gone, but the module dependency is still present, and that will only go away with the cAdvisor bump.

**Comment by skitt** [comment]
@liggitt I’ve rebased the PR.

**Pull request merged**
