### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by mnagy**
This causes failure to compile (1.4.2)

### CODE REVIEW

**Comment by ashcrow** [comment]
go1.5.1 works with and without this patch. Since ```tokenName``` isn't directly used in the test this makes sense.

Looks good to me!

**Comment by mnagy** [comment]
I signed it!

**Comment by ashcrow** [comment]
@ixdy any clue if there is something up with @googlebot and CLA verification?

**Comment by ixdy** [comment]
@mnagy does https://cla.developers.google.com/clas show you covered by the RedHat corporate agreement?

**Comment by ixdy** [comment]
Also, do you have your RedHat email address added to your GitHub profile?

**Comment by mnagy** [comment]
@ixdy it does not ("We don't have any individual agreements on file for you."). And yes, I have my RH address in my profile.

**Comment by mnagy** [comment]
@smarterclayton can you help out?

**Comment by ixdy** [comment]
@mnagy ok, you probably need to be added to the RedHat group, then - https://cla.developers.google.com/clas should show you covered by that corporate agreement.

**Comment by mnagy** [comment]
I signed it!

**Pull request merged**
