### PR TITLE
Improve deleteOptions doc

### PR DESCRIPTION
**Pull request by tengqm**
**What this PR does / why we need it**:
This PR improves the doc of the 'PropagationPolicy' property of the DeleteOptions struct.
The said field is a string. It is very important a field for people who invoke a delete API.
For example, direct invocation of the deployment-delete API using the python client will have the replicaset and pods left behind. However, this field was not well documented. When people wanted to try different options, they have to dig into k8s source code to find out the acceptable values.

**Which issue this PR fixes**: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by brendandburns** [comment]
Please run hack/update-generated-protobuf.sh

**Comment by tengqm** [comment]
@brendandburns all checks passed now, PTAL.

**Comment by tengqm** [comment]
em ... robot is too smart.

**Comment by tengqm** [comment]
this is a rebase due to merge conflict.
I have also split the patch into two commits for easy of review.

**Comment by k82cn** [comment]
/retest

Seems the errors are not related to this PR, just retest them.

**Comment by tengqm** [comment]
rebased to try if pull-kubernetes-bazel-build is happy.

**Pull request merged**
