### PR TITLE
dockershim: bump the minimum supported docker version to 1.11

### PR DESCRIPTION
**Pull request by yujuhong**
Drop the 1.10 compatibilty code.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
No release note? :)

**Comment by yujuhong** [comment]
> No release note? :)

Docker 1.10 was not mentioned in the 1.9 release note as a compatible version. This is more of a code cleanup.

**Comment by dims** [comment]
ack thanks!

**Pull request merged**
