### PR TITLE
fix a regression that TestValidateNodeIPParam never actually works

### LINKED ISSUE #91498: UT TestValidateNodeIPParam does not really tests validateNodeIP
**What happened**:

UT TestValidateNodeIPParam does not really tests `validateNodeIP`.
The first IP and interface are always 127.0.0.1 and lo and will break the loop.  So `successTest` will never be appended into `tests`.
https://github.com/kubernetes/kubernetes/blob/87473a5d27e52f8eb86575898cd6e6d8b8e881be/pkg/kubelet/kubelet_node_status_test.go#L1904-L1912

**What you expected to happen**:

`validateNodeIP` gets tested correctly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by lo24**
**What type of PR is this?**

/kind bug
/kind failing-test

**What this PR does / why we need it**:

Fix UT TestValidateNodeIPParam.

**Which issue(s) this PR fixes**:

Fixes #91498

**Special notes for your reviewer**:
Thanks for review.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lo24** [comment]
/cc @mattjmcnaughton @dims
ptal, thanks

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/lgtm
/assign @derekwaynecarr

Thanks for this fix!

Do you mind updating your commit message to describe the actual bug that you fixed? (i.e. break was being used instead of continue). Thanks!

**Comment by lo24** [comment]
ping @mattjmcnaughton , commit message updated, please take another look, thanks.
/assign @dchen1107

**Pull request merged**
