### PR TITLE
fix: remove conflict comment of taint "Value"

### PR DESCRIPTION
**Pull request by willise**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove one of the conflict comments.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the PR, but it's not clear why this change is being made. If this is a change that should be made (if the field is actually required in all uses), the omitempty should be removed as well, and generated files would need to be updated (with `make update`)

**Comment by willise** [comment]
> 
> 
> Thanks for the PR, but it's not clear why this change is being made. If this is a change that should be made (if the field is actually required in all uses), the omitempty should be removed as well, and generated files would need to be updated (with `make update`)

**Comment by willise** [comment]
@liggitt Thanks for the reply, I will recheck it.

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

I _believe_ this diff was updated since the comments... in my eyes, the current iteration makes sense. We are removing an aspect of a comment that no longer makes sense.

I'm not positive if, given we are only updating a comment, we still need to update docs, etc... I think running the test suite will inform us.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/retest

I defer to @thockin on the final API sign-off, but AFAIK should be good to go.

**Review by thockin — COMMENTED** [review]
Taint values are validated as label values, which are allowed to be empty, so I guess This is OK.  That said, it's not really explained here what happens when the value is not provided ("" by Go's default).

If we want to change this, perhaps we should do it properly and explain that?

/lgtm
/approve

**Comment by willise** [comment]
@thockin Thanks for the mention. It seems other types don't explain why the property is optional, so is it a conventional  rule?

**Pull request merged**
