### PR TITLE
Create heapster node first

### PR DESCRIPTION
**Pull request by wojtek-t**
This should help with mitigating failures like this:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/127/build-log.txt

### CODE REVIEW

**Comment by shyamjvs** [comment]
@wojtek-t Btw - I'm not sure if this will necessarily help. As it might be that the heapster node failed to be created because of creating the earlier 5000 nodes and so lack of resources :)
If you're now creating it first, then probably the error would be seen during last MIG creation. Wdyt?

**Comment by wojtek-t** [comment]
? @wojtek-t Btw - I'm not sure if this will necessarily help. As it might be that the heapster node failed to be created because of creating the earlier 5000 nodes and so lack of resources :)
If you're now creating it first, then probably the error would be seen during last MIG creation instead. Wdyt?

Not necessary. Heapster node is bigger (8 cores? 16 cores?) so it is in theory much easier to find space for it before occupying the next 5000 cores than after that.
I.e. it's much easier to find 1 free core, than find 8 free cores on one machine.
Obviously depends on scheduling algorithm, but this for sure won't make things worse.

**Comment by shyamjvs** [comment]
You're right. Scheduling larger machines is harder is the case I was also thinking about (we've seen issues with that in past for master machine).

**Pull request merged**
