### PR TITLE
Make Mounter interface exportable

### PR DESCRIPTION
**Pull request by mxpv**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

In current implementation it's not possible to implement Mounter interface
from a different package because of `canSafelySkipMountPointCheck` is private.
So when attempting to implement it, Go will fail:

```
Type cannot implement 'mount.Interface' as it has a non-exported method and is defined in a different package
```

This change would allow providing alternative mounter implementations via `Dependencies` structure.

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
No

### CODE REVIEW

**Comment by jingxu97** [comment]
/approve

@jsafrane could you help review?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by mxpv** [comment]
Fixed CI tests.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
