### PR TITLE
 Add `snapfactor` storageclass parameter for GlusterFS provisioner.

### PR DESCRIPTION
**Pull request by humblec**
This patch add a new parameter called `snapfactor` to glusterfs
    storageclass. This is an optional parameter and value should
    fall into the range of 1-100. When set the thin pool calculation
    respect this snapfactor and create a thinpool accordingly.
    

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm

I would remove the change in examples/ and post a PR against https://github.com/kubernetes/examples

**Comment by jsafrane** [comment]
Failed pull-kubernetes-bazel-test  looks like a legitimate error.

**Comment by humblec** [comment]
Thanks Jan, sure I will segregate the PR and also will look into the bazel failure.

**Comment by humblec** [comment]
@jsafrane I have removed example update from this PR , also corrected and added test cases for new parameter.  Please review! Thanks

**Comment by jsafrane** [comment]
/lgtm
This needs an e2e test!

**Pull request merged**
