### PR TITLE
Update docker/libnetwork to tag v0.6.0-rc1

### LINKED ISSUE #79234: Update vendored dependencies to a released version instead of random SHA(s)
Algorithm:
- Look at go.mod, look for dependencies with [Pseudo-versions](https://golang.org/cmd/go/#hdr-Pseudo_versions)
- Look at the github repo of the dependencies, find a released tag closest to the SHA (but higher than the SHA)
- Look at the commits in the range and review with the [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/godep.md#justifications-for-an-update) in mind
- NOTE that the version bump suggestions below are just that ("suggestions"), please try to find a closer or better match of release tags based on the guidelines above.

Here's the situation as of June 20, 2019 using [some scripts](https://gist.github.com/dims/c0857b86441442b15852a4c2355db130) to highlight possibilities
- [x] github.com/codedellemc/goscaleio ( filed https://github.com/kubernetes/kubernetes/pull/80321 )
- [ ] github.com/docker/libnetwork ( [from a9cd636e3789 to possibly v0.6.0-rc1 or newer](https://github.com/docker/libnetwork/compare/a9cd636e3789...v0.6.0-rc1) )
- [ ] github.com/gogo/protobuf ( [from 342cbe0a0415 to possibly v1.0.0 or newer](https://github.com/gogo/protobuf/compare/342cbe0a0415...v1.0.0) )
- [x] github.com/gophercloud/gophercloud( [from c818fa66e4c8 to possibly v0.2.0 or newer](https://github.com/gophercloud/gophercloud/compare/c818fa66e4c8...v0.2.0) )
- [x] github.com/heketi/heketi ( [from 558b29266ce0 to possibly v9.0.0 or newer](https://github.com/heketi/heketi/compare/558b29266ce0...v9.0.0) )
- [ ] github.com/libopenstorage/openstorage ( [from 093a0c388875 to possibly v8.0.0 or newer](https://github.com/libopenstorage/openstorage/compare/093a0c388875...v8.0.0) )
- [ ] github.com/opencontainers/runc ( [from f000fe11ece1 to possibly v0.1.1 or newer](https://github.com/opencontainers/runc/compare/f000fe11ece1...v0.1.1) )
- [ ] github.com/prometheus/common ( [from 4724e9255275 to possibly v0.6.0 or newer](https://github.com/prometheus/common/compare/4724e9255275...v0.6.0) )
- [x] github.com/seccomp/libseccomp-golang ( [from 1b506fc7c24e to possibly v0.9.1 or newer](https://github.com/seccomp/libseccomp-golang/compare/1b506fc7c24e...v0.9.1) )
- [ ] github.com/vishvananda/netlink ( [from b2de5d10e38e to possibly v1.0.0 or newer](https://github.com/vishvananda/netlink/compare/b2de5d10e38e...v1.0.0) )
- [ ] google.golang.org/api ( [from 583d854617af to possibly v0.6.0 or newer](https://google.golang.org/api/compare/583d854617af...v0.6.0) )
- [x] github.com/docker/distribution (filed https://github.com/kubernetes/kubernetes/pull/80721)

### PR DESCRIPTION
**Pull request by alok87**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR updates the docker/libnetwork dependency to v0.6.0-rc1 tag.
There is a work in progress https://github.com/kubernetes/kubernetes/issues/79234 to update vendor dependencies to use release tags instead of random SHA.

This updates the libnetwork to a one release up. Here is the code diff https://github.com/docker/libnetwork/compare/a9cd636e3789...v0.6.0-rc1

Fixes #
fix https://github.com/kubernetes/kubernetes/issues/79234

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alok87** [comment]
@dims updating the vendor is deleting the package all together. I was using pin-dependecy.sh script. What am i doing wrong?

**Comment by dims** [comment]
this won't work. this is removing ipvs :( let's try what's in https://github.com/kubernetes/kubernetes/pull/80290

/close

**Pull request closed without merging**
