### PR TITLE
Replace "minion" with "node" in bunch of places.

### PR DESCRIPTION
**Pull request by wojtek-t**
Followup from #9176

cc @thockin

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin - friendly ping

**Comment by wojtek-t** [comment]
@thockin - can you please take a look or delegate?

**Comment by thockin** [comment]
wise to tackle the easy one first :)

**Comment by wojtek-t** [comment]
>
wise to tackle the easy one first :)

:-)
Partially, it's because some people (e.g. @davidopp ) had some doubts whether we should do it and IIUC, this wasn't about all places. The places I've changed are those where we were mixing "node" and "minion" which is the worst case...
@davidopp - can you please clarify what doublt did you have about replacing "minion" with "node"?

**Pull request merged**
