### PR TITLE
test: Add e2e node test to check for unknown pods

### PR DESCRIPTION
**Pull request by bobbypage**
#### What this PR does / why we need it:

Unknown pods are pods which are unknown pods to the kubelet, but are still running in the container runtime. If kubelet detects a pod which is not in the config (i.e. not present in API-server or static pod), but running as detected in container runtime, kubelet should aggressively terminate the pod.

This situation can be encountered if a pod is running, then kubelet is stopped, and while stopped, the manifest is deleted (by force deleting the API pod or deleting the static pod manifest), and then restarting the kubelet. Upon restart, kubelet will see the pod as running via the container runtime, but it will not be present in the config, thus making the pod a "unknown pod". Kubelet should then proceed to terminate these unknown pods.

Add two tests that ensure that unknown pods will be terminated (1) static pods and (2) API pods. The test will start a pod, stop the kubelet, force delete the pod (by deleting the manifest or force deleting the pod), and then restarting the kubelet. The container runtime is then queried to ensure the containers are terminated by kubelet.

Signed-off-by: David Porter <david@porter.me>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
related to https://github.com/kubernetes/kubernetes/pull/113145

**Comment by bobbypage** [comment]
```
W0201 23:46:56.048]   Latency metrics for node n1-standard-2-ubuntu-gke-2204-1-25-v20230130-7ea6d60e
W0201 23:46:56.048]   [1mSTEP:[0m Destroying namespace "unknown-pods-3995" for this suite. [38;5;243m@ 02/01/23 22:50:40.084[0m
W0201 23:46:56.048]   [38;5;243m<< Timeline[0m
W0201 23:46:56.048] 
W0201 23:46:56.048]   [38;5;9m[FAILED] Timed out after 120.000s.
W0201 23:46:56.048]   Expected
W0201 23:46:56.048]       <bool>: false
W0201 23:46:56.048]   to be true[0m
```
Logs show that the pod was deleted in CRI, but it took a bit longer:

Delete at 22:52:30

```
Feb 01 22:48:35 n1-standard-2-ubuntu-gke-2204-1-25-v20230130-7ea6d60e containerd[1222]: time="2023-02-01T22:48:35.920714511Z" level=debug msg="generated id for sandbox name \"unknown-test-pause-pod-964eabaf-2c54-4baf-a314-7b1c4fa07df9_unknown-pods-3995_2106d62c-4299-4f0c-a466-b24724680914_0\"" podsandboxid=7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b
...
Feb 01 22:52:30 n1-standard-2-ubuntu-gke-2204-1-25-v20230130-7ea6d60e containerd[1222]: time="2023-02-01T22:52:30.811726646Z" level=info msg="RemovePodSandbox \"7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b\" returns successfully"
```

But it looks like delete came because the kubelet was later restarted by another test. The original kill failed due to CRI error, but it was not retried. https://github.com/kubernetes/kubernetes/pull/113145 aims to address this:

```
I0201 22:48:40.223084  124816 kubelet_pods.go:2008] "Orphaned pod found, removing pod cgroups" podUID=2106d62c-4299-4f0c-a466-b24724680914
I0201 22:48:40.223122  124816 kubelet.go:2286] "SyncLoop (housekeeping) end"
I0201 22:48:40.244875  124816 manager.go:1027] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7.scope" (aliases: [f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7 /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7.scope], namespace: "containerd")
I0201 22:48:40.244908  124816 handler.go:325] Added event &{/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7.scope 2023-02-01 22:48:40.244901432 +0000 UTC m=+2.210192513 containerDeletion {<nil>}}
I0201 22:48:40.246083  124816 cgroup_manager_linux.go:504] "Cgroup manager encountered error scanning cgroup path" path="/sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7.scope" err="lstat /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7.scope: no such file or directory"
I0201 22:48:40.246328  124816 pod_container_manager_linux.go:161] "Attempting to kill process from cgroup" pid=124759 cgroupName=[kubepods besteffort pod2106d62c-4299-4f0c-a466-b24724680914]
I0201 22:48:40.246360  124816 pod_container_manager_linux.go:161] "Attempting to kill process from cgroup" pid=124793 cgroupName=[kubepods besteffort pod2106d62c-4299-4f0c-a466-b24724680914]
I0201 22:48:40.246377  124816 pod_container_manager_linux.go:131] "Process no longer exists" pid=124793
I0201 22:48:40.246394  124816 pod_container_manager_linux.go:170] "Successfully killed all unwanted processes from cgroup" cgroupName=[kubepods besteffort pod2106d62c-4299-4f0c-a466-b24724680914]
I0201 22:48:40.247811  124816 manager.go:1027] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b.scope" (aliases: [7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b.scope], namespace: "containerd")
I0201 22:48:40.247843  124816 handler.go:325] Added event &{/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice/cri-containerd-7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b.scope 2023-02-01 22:48:40.247837789 +0000 UTC m=+2.213128868 containerDeletion {<nil>}}
I0201 22:48:40.277295  124816 manager.go:1027] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice" (aliases: [], namespace: "")
I0201 22:48:40.277337  124816 handler.go:325] Added event &{/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2106d62c_4299_4f0c_a466_b24724680914.slice 2023-02-01 22:48:40.277330609 +0000 UTC m=+2.242621689 containerDeletion {<nil>}}
I0201 22:48:40.338966  124816 kuberuntime_container.go:720] "Container exited normally" pod="unknown-pods-3995/unknown-test-pause-pod-964eabaf-2c54-4baf-a314-7b1c4fa07df9" podUID=2106d62c-4299-4f0c-a466-b24724680914 containerName="pause" containerID="containerd://f4dfe7424fae517bc6b89af79b232966cc585e4708d8cef69e90232f07a84ee7"
E0201 22:48:40.345267  124816 remote_runtime.go:203] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to stop sandbox container \"7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b\" in \"SANDBOX_READY\" state: failed to kill sandbox container: ttrpc: closed: unknown" podSandboxID="7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b"
E0201 22:48:40.345322  124816 kuberuntime_manager.go:965] "Failed to stop sandbox" podSandboxID={Type:containerd ID:7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b}
E0201 22:48:40.345384  124816 kubelet.go:1871] failed to "KillPodSandbox" for "2106d62c-4299-4f0c-a466-b24724680914" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop sandbox container \"7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b\" in \"SANDBOX_READY\" state: failed to kill sandbox container: ttrpc: closed: unknown"
I0201 22:48:40.345415  124816 kubelet.go:1872] "syncTerminatingPod exit" pod="unknown-pods-3995/unknown-test-pause-pod-964eabaf-2c54-4baf-a314-7b1c4fa07df9" podUID=2106d62c-4299-4f0c-a466-b24724680914
E0201 22:48:40.345457  124816 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"2106d62c-4299-4f0c-a466-b24724680914\" with KillPodSandboxError: \"rpc error: code = Unknown desc = failed to stop sandbox container \\\"7b2146e9d614d383c02d427c74aa53bcebb41781ecbd1b2e637c7e1ef995c26b\\\" in \\\"SANDBOX_READY\\\" state: failed to kill sandbox container: ttrpc: closed: unknown\"" pod="unknown-pods-3995/unknown-test-pause-pod-964eabaf-2c54-4baf-a314-7b1c4fa07df9" podUID=2106d62c-4299-4f0c-a466-b24724680914
```

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
