### PR TITLE
Config resource in env vars

### PR DESCRIPTION
**Pull request by pmorie**
Depends on #18712

### CODE REVIEW

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by bgrant0607** [comment]
Makes sense for the same person to review this as #18298

**Comment by pmorie** [comment]
@erictune ready for review; PTAL

**Comment by erictune** [comment]
LGTM

**Comment by erictune** [comment]
feel free to reapply LGTM after rebase.

**Comment by pmorie** [comment]
@erictune thanks for the review! :fist:

**Comment by pmorie** [comment]
@erictune thanks again for the tune-up

**Comment by erictune** [comment]
:musical_note: :arrow_up:

**Comment by pmorie** [comment]
> :musical_note: :arrow_up: 

I lol'd

**Pull request merged**
