### PR TITLE
add test/conformance/gen-conformance-docs.sh

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it: 

Enables generating `conformance.md` for https://github.com/cncf/k8s-conformance/tree/master/docs without bazel.

xref: #99549 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Output goes to `_output/conformance.md` next to the existing `_output/conformance.yaml`. This target isn't actually used in this repo and the output is not expecting to be checked in here currently, unlike `conformance.yaml`, so this isn't wired to verify etc unlike the yaml output.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @hh

**Comment by BenTheElder** [comment]
conformance-image-test flakes on building the conformance image, not related to this PR.
/retest

**Comment by BenTheElder** [comment]
/cc @spiffxp @dims 
lack of a target for this is a minor regression vs the BUILD file we had here before. we didn't include this when migrating the rest to `make verify` / `hack/update-conformance-yaml.sh`

**Comment by dims** [comment]
/approve
/lgtm

thanks @BenTheElder !

**Pull request merged**
