### PR TITLE
Remove deprecated --etcd-quorum-read flag

### PR DESCRIPTION
**Pull request by liggitt**
**What this PR does / why we need it**:
Removes the deprecated `--etcd-quorum-read` flag. This flag was defaulted to true (#53717) and deprecated in 1.9 (#53795).

Setting it to false causes bugs in controllers because of stale reads.

Those bugs can lead to runaway controllers (creating too many objects), stuck controllers (not acting on latest state), and controllers breaking invariants (reacting to objects in different parts of their lifecycle than they are actually in).

Quorum reads performed badly on etcd2, which was the only reason this flag was not removed sooner, but perform well on etcd3. Etcd2 support is dropped in 1.13 in #69310

**Special notes for your reviewer**:

**Release note**:
```release-note
kube-apiserver: the deprecated `--etcd-quorum-read` flag has been removed, and quorum reads are always enabled when fetching data from etcd.
```

@kubernetes/sig-api-machinery-pr-reviews

### CODE REVIEW

**Comment by liggitt** [comment]
fixed up gofmt for 1.11, fixed up unit test store construction, retagging

**Comment by liggitt** [comment]
third time's the charm, removed reference from one more unit test

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/features/issues/622 for the etcd2 drop

**Comment by spiffxp** [comment]
/lgtm cancel
To stop fejta-bot from spamming, this is a failure, not a flake

**Comment by liggitt** [comment]
ok, ok. fourth time was the charm. so many unit tests.

**Pull request merged**
