### PR TITLE
Add support for CronJob to kind_visitor

### PR DESCRIPTION
**Pull request by mahdix**
Fixes https://github.com/kubernetes/kubectl/issues/126

### CODE REVIEW

**Comment by mengqiy** [comment]
/ok-to-test
/lgtm
please follow https://github.com/kubernetes/kubernetes/pull/55455#issuecomment-343371366 to update release note to none.

**Comment by mahdix** [comment]
@janetkuo Please advise.

**Comment by mahdix** [comment]
Can someone review and hopefully approve this PR?

**Pull request merged**
