### PR TITLE
Use instance availability zone for AWS EBS

### PR DESCRIPTION
**Pull request by ghost**
This simplifies the volumeID line and makes it similar to the pdName entry for GCE Persistent disks.
@justinsb What do you think of this ?

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@justinsb is this something you'd want for v1 or can it wait?

**Comment by justinsb** [comment]
I think this is a good change; it is much more user-friendly.

This is a breaking change for anyone using volumes also; so it might be better to just treat this as a shortcut: so vol-12345678 is a shortcut for aws:///vol-12345678, which is itself a shortcut for aws://<current-az>/vol-12345678.  That way we don't break any docs / blogs etc.

@swagiaal this is just to be more user-friendly, right (it isn't a correctness issue)?  I think we should still do it if we can accept both forms.

**Comment by swagiaal** [comment]
@justinsb yeah this is just for the purpose of being more user friendly.
I have updated the patch. This should now accept aws://zone/vol-ID and just vol-ID

**Comment by justinsb** [comment]
This is nice; much more user-friendly and doesn't break anything.

LGTM

**Comment by bprashanth** [comment]
This seems pretty isolated to aws, and it sounds like we want it for 1.0 if possible. @quinton-hoole for ok-to-merge.

**Comment by quinton-hoole** [comment]
Yup, ok-to-merge, thanks!

**Comment by sils1297** [comment]
Hey, I think https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/volumes.md#aws-ebs-example-configuration needs an update in this case :)

**Comment by sils1297** [comment]
filed bug at https://github.com/kubernetes/kubernetes/issues/17957

**Pull request merged**
