### PR TITLE
Increase master disk size in large clusters

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #34911

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36486)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #36473

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #36473

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #36473

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #36473

**Comment by saad-ali** [comment]
Looks like this PR was LGTMed after code freeze for 1.5 was in effect. Is this a bug fix?

Removing milestone and adding do-not-merge until verification.

**Comment by wojtek-t** [comment]
@saad-ali - this is bug fix for failing performance tests in 3000-node cluster.

**Comment by saad-ali** [comment]
> @saad-ali - this is bug fix for failing performance tests in 3000-node cluster.

Ack. Approving bug fix for post-code freeze merge. Could you please reference the bug number in this PR.

**Pull request merged**
