### PR TITLE
correct CHANGELOG-1.12

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Pingan2017** [comment]
@thockin  could you help adding a 'ok-to-test' label? Thanks!

**Review by feiskyer — COMMENTED** [review]
lgtm. Thanks for the format fix.

**Pull request merged**
