### PR TITLE
remove deprecated ssh tunneling functionality in API Server

### PR DESCRIPTION
**Pull request by dixudx**
**What type of PR is this?**
/kind api-change
/kind cleanup

**What this PR does / why we need it**:
Flag `--ssh-user` and `--ssh-keyfile`  has been marked as deprecated since v1.9. It's safe to remove them in the following versions.

**Which issue(s) this PR fixes**:

Followup of #54433

**Special notes for your reviewer**:
/cc dims liggitt 

**Does this PR introduce a user-facing change?**:

```release-note
kube-apiserver: remove deprecated `--ssh-user` and `--ssh-keyfile` flag
```

### CODE REVIEW

**Comment by dims** [comment]
/hold 

@dixudx we need https://github.com/kubernetes/enhancements/pull/872 to be implemented i think

cc @cheftako

**Comment by dixudx** [comment]
> kubernetes/enhancements#872 to be implemented

@dims Thanks. I did not notice that.

Actually what I am trying to address is #75329. Seems we've got a better KEP to implement the inner proxies.

**Comment by caesarxuchao** [comment]
/assign @cheftako 
cc @lavalamp

**Comment by lavalamp** [comment]
Yup, came here to say what dims said. The tunnels accidentally added a security property that we need to get in some other way before removing them.

**Comment by cheftako** [comment]
/remove-lifecycle stale
Gated on https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md
Once the above KEP is implemented we can move forward on this.

**Comment by dixudx** [comment]
@cheftako Rebased. PTAL. Thanks.

**Comment by cheftako** [comment]
I agree this work needs to be done. https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md has its beta requirements set and we are actively working towards them. I would prefer that we get the replacement to GA prior to deleting this code. I know that @deads2k and @lavalamp would like this code gone. It would be nice to find a way to turn it off so that it cannot be accidentally used/modified. In short I'm not sure we are ready to make this change yet, however the final call is with the api machinery leads.

**Comment by lavalamp** [comment]
I agree we should delete the lines installing the flags now.

I'd like to leave the rest of the code there until / unless @cheftako confirms that the replacement won't use those code paths?

**Comment by dixudx** [comment]
@lavalamp  @dims @cheftako Rebased. PTAL. Thanks.

**Comment by spiffxp** [comment]
Is there a tracking issue that corresponds to https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md ?

**Comment by spiffxp** [comment]
I think it's https://github.com/kubernetes/enhancements/issues/1281

**Comment by liggitt** [comment]
covered by https://github.com/kubernetes/kubernetes/pull/102297 in 1.22

/close

**Pull request closed without merging**
