### PR TITLE
Fix races in mesos scheduler plugin test

### LINKED ISSUE #10795: Fix shippable flake in contrib/mesos/pkg/scheduler
Example:
https://app.shippable.com/builds/559b0c6a8469020c00c6b9e3

```
ok github.com/GoogleCloudPlatform/kubernetes/examples	2.523s	coverage: 0.0% of statements
I0707 00:02:22.257292 8725 ha.go:132] scheduler process entered standby stage
I0707 00:02:22.259786 8725 plugin.go:439] Watching for newly created pods
I0707 00:02:22.274393 8725 ha.go:154] scheduler process entered master stage
I0707 00:02:22.274682 8725 ha.go:164] driver started successfully and is running
I0707 00:02:22.275120 8725 scheduler.go:301] Scheduler registered with the master: &MasterInfo{Id:*master-id,Ip:*3232235521,Port:*5050,Pid:nil,Hostname:nil,XXX_unrecognized:[],} with frameworkId: &FrameworkID{Value:*kubernetes-id,XXX_unrecognized:[],}
I0707 00:02:22.277224 8725 scheduler.go:777] explicit reconcile tasks
I0707 00:02:22.664044 8725 plugin.go:243] Try to schedule pod pod1
I0707 00:02:22.673593 8725 plugin.go:558] Error scheduling pod1: No suitable offers for pod/task; retrying
I0707 00:02:23.283341 8725 scheduler.go:777] explicit reconcile tasks
I0707 00:02:23.988836 8725 plugin.go:243] Try to schedule pod pod1
I0707 00:02:26.670830 8725 scheduler.go:424] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.7145055a-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
E0707 00:02:26.689211 8725 registry.go:204] received STAGING for task pod.7145055a-243b-11e5-b078-0242ac1145f5 with unexpected source: SOURCE_EXECUTOR
I0707 00:02:26.693439 8725 scheduler.go:424] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.7145055a-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
I0707 00:02:26.697790 8725 registry.go:231] Received running status for pending task: pod.7145055a-243b-11e5-b078-0242ac1145f5
I0707 00:02:26.706267 8725 registry.go:263] received pod status for task pod.7145055a-243b-11e5-b078-0242ac1145f5: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.5 StartTime:<nil> ContainerStatuses:[]}
I0707 00:02:26.706847 8725 scheduler.go:424] task status update "TASK_LOST" from "SOURCE_EXECUTOR" for task "pod.7145055a-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
I0707 00:02:27.090636 8725 plugin.go:243] Try to schedule pod pod2
I0707 00:02:27.093274 8725 scheduler.go:424] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.73e7c9b1-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
E0707 00:02:27.093449 8725 registry.go:204] received STAGING for task pod.73e7c9b1-243b-11e5-b078-0242ac1145f5 with unexpected source: SOURCE_EXECUTOR
I0707 00:02:27.093614 8725 scheduler.go:424] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.73e7c9b1-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
I0707 00:02:27.093761 8725 registry.go:231] Received running status for pending task: pod.73e7c9b1-243b-11e5-b078-0242ac1145f5
I0707 00:02:27.096140 8725 registry.go:263] received pod status for task pod.73e7c9b1-243b-11e5-b078-0242ac1145f5: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.6 StartTime:<nil> ContainerStatuses:[]}
I0707 00:02:27.098349 8725 scheduler.go:424] task status update "TASK_FINISHED" from "SOURCE_EXECUTOR" for task "pod.73e7c9b1-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
I0707 00:02:27.309180 8725 plugin.go:243] Try to schedule pod pod3
I0707 00:02:27.310916 8725 scheduler.go:424] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.740920ba-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
E0707 00:02:27.311029 8725 registry.go:204] received STAGING for task pod.740920ba-243b-11e5-b078-0242ac1145f5 with unexpected source: SOURCE_EXECUTOR
I0707 00:02:27.311147 8725 scheduler.go:424] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.740920ba-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
I0707 00:02:27.311304 8725 registry.go:231] Received running status for pending task: pod.740920ba-243b-11e5-b078-0242ac1145f5
I0707 00:02:27.311970 8725 registry.go:263] received pod status for task pod.740920ba-243b-11e5-b078-0242ac1145f5: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.7 StartTime:<nil> ContainerStatuses:[]}
I0707 00:02:27.320790 8725 scheduler.go:424] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.740920ba-243b-11e5-b078-0242ac1145f5" on slave "h1" executor "executor-id" for reason "none"
E0707 00:02:27.679418 8725 util.go:69] Recovered from panic: runtime.errorCString{cstr:0x1af46fc} (runtime error: index out of range)
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/root/.gvm/gos/go1.3/src/pkg/runtime/panic.c:248
/root/.gvm/gos/go1.3/src/pkg/runtime/panic.c:552
/root/.gvm/gos/go1.3/src/pkg/runtime/panic.c:466
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/stretchr/testify/assert/assertions.go:88
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/stretchr/testify/mock/mock.go:268
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler/mock_test.go:187
<autogenerated>:146
github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler/_test/_obj_test/scheduler.go:178
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler/ha/ha.go:100
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler/ha/ha.go:218
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/proc/proc.go:364
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/proc/proc.go:321
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/proc/proc.go:161
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/proc/proc.go:139
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime/util.go:115
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime/util.go:116
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/proc/proc.go:142
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/runtime/util.go:95
/root/.gvm/gos/go1.3/src/pkg/runtime/proc.c:1445
I0707 00:02:27.819981 8725 plugin.go:243] Try to schedule pod pod4
I0707 00:02:27.820666 8725 plugin.go:558] Error scheduling pod4: No suitable offers for pod/task; retrying
I0707 00:02:29.133035 8725 plugin.go:243] Try to schedule pod pod4
I0707 00:02:29.133329 8725 plugin.go:558] Error scheduling pod4: No suitable offers for pod/task; retrying
I0707 00:02:31.656224 8725 plugin.go:243] Try to schedule pod pod4
I0707 00:02:31.656512 8725 plugin.go:558] Error scheduling pod4: No suitable offers for pod/task; retrying
I0707 00:02:32.978178 8725 plugin.go:243] Try to schedule pod pod4
I0707 00:02:32.978422 8725 plugin.go:558] Error scheduling pod4: No suitable offers for pod/task; retrying
I0707 00:02:34.383310 8725 plugin.go:243] Try to schedule pod pod4
I0707 00:02:34.383583 8725 plugin.go:558] Error scheduling pod4: No suitable offers for pod/task; retrying
I0707 00:02:34.432826 8725 ha.go:141] scheduler process entered fin stage
--- FAIL: TestPlugin_LifeCycle (12.19 seconds)
<autogenerated>:31:
Error Trace:	plugin_test.go:321
plugin_test.go:327
plugin_test.go:507
plugin_test.go:568
Error:	event not received
plugin_test.go:517: timed out waiting for launchTasks
I0707 00:02:34.446136 8725 scheduler.go:394] Offer rescinded &OfferID{Value:*test1,XXX_unrecognized:[],}
I0707 00:02:34.469137 8725 scheduler.go:394] Offer rescinded &OfferID{Value:*test2,XXX_unrecognized:[],}
I0707 00:02:34.469637 8725 scheduler.go:394] Offer rescinded &OfferID{Value:*notExist,XXX_unrecognized:[],}
I0707 00:02:34.470344 8725 scheduler.go:610] Slave &SlaveID{Value:*h1,XXX_unrecognized:[],} is lost
I0707 00:02:34.470561 8725 scheduler.go:610] Slave &SlaveID{Value:*h2,XXX_unrecognized:[],} is lost
I0707 00:02:34.470720 8725 scheduler.go:610] Slave &SlaveID{Value:*notExist,XXX_unrecognized:[],} is lost
I0707 00:02:34.540849 8725 scheduler.go:373] Master disconnected!
I0707 00:02:34.544280 8725 scheduler.go:424] task status update "TASK_RUNNING" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
W0707 00:02:34.544639 8725 registry.go:240] Ignore status TASK_RUNNING because the task test-task-001 is discarded
E0707 00:02:34.544984 8725 scheduler.go:530] possible rogue pod; illegal task status data for task test-task-001, expected an api.PodStatusResult: missing TaskStatus.Data
I0707 00:02:34.545697 8725 scheduler.go:424] task status update "TASK_RUNNING" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
W0707 00:02:34.546593 8725 registry.go:240] Ignore status TASK_RUNNING because the task test-task-001 is discarded
E0707 00:02:34.546948 8725 scheduler.go:530] possible rogue pod; illegal task status data for task test-task-001, expected an api.PodStatusResult: missing TaskStatus.Data
I0707 00:02:34.549055 8725 scheduler.go:424] task status update "TASK_FAILED" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
FAIL
coverage: 60.1% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler	14.052s
```

### PR DESCRIPTION
**Pull request by sttts**
Fixes #10795

### CODE REVIEW

**Comment by karlkfi** [comment]
Code looks ok, but shippable is failing (on both test permutations):

```
W0711 10:30:47.486131 13715 cmd.go:137] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0711 10:30:47.486436 13715 cmd.go:137] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0711 10:30:47.486515 13715 cmd.go:137] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0711 10:30:47.487168 13715 cmd.go:137] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0711 10:30:47.490081 13715 cmd.go:137] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
--- FAIL: TestRunExposeService (0.05s)
expose_test.go:173: expose-external-service: unexpected output: &api.Service{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string{"svc":"test"}, Annotations:map[string]string(nil)}, Spec:api.ServiceSpec{Ports:[]api.ServicePort{api.ServicePort{Name:"default", Protocol:"UDP", Port:14, TargetPort:util.IntOrString{Kind:0, IntVal:14, StrVal:""}, NodePort:0}}, Selector:map[string]string{"func":"stream"}, ClusterIP:"", Type:"LoadBalancer", DeprecatedPublicIPs:[]string(nil), SessionAffinity:""}, Status:api.ServiceStatus{LoadBalancer:api.LoadBalancerStatus{Ingress:[]api.LoadBalancerIngress(nil)}}}
FAIL
coverage: 55.3% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd	0.846s
```

I don't think we changed that, but it might be affected by the testify update... I can triage on Monday, unless you get to it first, @sttts

**Comment by zmerlynn** [comment]
That's #11105.

**Comment by sttts** [comment]
Rebased to re-enable test.

**Comment by karlkfi** [comment]
LGTM. 
Need a google approval, since this bumps test dependencies used by non-mesos tests.

/cc @davidopp

**Comment by karlkfi** [comment]
Reassigned to @davidopp for review.
This should fix a contrib/mesos unit test that was skipped for being flakey.

**Comment by davidopp** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Pull request merged**
