### PR TITLE
typo fix in deviceplugin protobuf regeneration command

### PR DESCRIPTION
**Pull request by eloyekunle**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

 /kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Typo fix.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for your PR :)

It looks like this typo also exists in `pkg/kubelet/apis/deviceplugin/v1alpha/api.proto`. Mind fixing this typo there as well? If you do update it, feel free to tag me and I'll mark it lgtm again. Alternatively, I can do it in a separate commit :) Whatever you would prefer!

**Comment by eloyekunle** [comment]
Thanks @mattjmcnaughton, I've added the fix.

**Review by mattjmcnaughton — APPROVED** [review]
This looks great to me!

It looks like your branch currently has some merge conflicts, so please rebase :) Lmk if you need any help with that.

/lgtm

**Comment by eloyekunle** [comment]
@mattjmcnaughton I've rebased :)

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/assign @vishh

**Pull request closed without merging**
