### PR TITLE
Federation readonly api

### PR DESCRIPTION
**Pull request by jianhuiz**
Add proxy store that calls cluster client API to get objects from the underlying clusters and aggregate the results.
Implement pods, nodes and replicasets API using proxy store. Other objects will be in separate PRs

Implement #33622
design at: https://docs.google.com/document/d/1H2BkqSKvoCSifi7c8D2gASSJo20ocIEYDMSfNfcylBc/

@kubernetes/sig-federation-pr-reviews  

```release-note
Allow reading kubernetes resources from federation-apiserver by specifying `clusterSelector` for LIST or `clusterName` for GET
```

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Thanks @jianhuiz .  Let me know when this is ready for review.

**Comment by quinton-hoole** [comment]
@jianhuiz This still doesn't compile.  Please do a local successful build before resubmitting.

**Comment by jianhuiz** [comment]
@quinton-hoole Although the currently only List and Get is supported and cluster information were added to ListOptions (clusterSelector) and GetOptions (clusterName).
I'm also trying to make the write apis to work, the major problem is how to pass the cluster info to these APIs.
``` go
type PodInterface interface {
	// use Pod.ClusterName
	Create(*v1.Pod) (*v1.Pod, error)
	// use Pod.ClusterName
	Update(*v1.Pod) (*v1.Pod, error)
	// use Pod.ClusterName
	UpdateStatus(*v1.Pod) (*v1.Pod, error)
	// could add DeleteOptions.ClusterName
	Delete(name string, options *meta_v1.DeleteOptions) error
	// use ListOptions.ClusterSelector, ignore DeleteOptions.ClusterName?
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	// currently use GetOptions.ClusterName
	Get(name string, options meta_v1.GetOptions) (*v1.Pod, error)
	// use ListOptions.ClusterSelector
	List(opts meta_v1.ListOptions) (*v1.PodList, error)
	// use ListOptions.ClusterSelector
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	// HOW?
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Pod, err error)
	PodExpansion
}
```
As you can see the problem is for the apis that operates on single object where the name is given to uniquely identify it. In order to paas `clusterName`, and remain backward compatibility, I am proposing encode cluster name to the resource name segment in the format of `name@cluster`, for the url to locate a resource in the cluster.  
`Get`, `Delete`, `Patch` (and also APIs like `PodExpansion.GetLogs(name string, opts *v1.PodLogOptions)` functions will need the `name` parameter in `name@cluster` format to operate against objects in the clusters. `Update` and `UpdateStatus` can internally build `name@cluster` for the url from the object.

This will need to modify the client-gen and regenerate all the clients (backward compatibility is maintained however).  
This also affect RBAC (some other admission controllers maybe?) because of the url changes of the federation api. Another side effect is this make RBAC rule against cluster objects (partially) possible.

Please advice. @kubernetes/sig-federation-pr-reviews

**Comment by quinton-hoole** [comment]
@jianhuiz Lets get the read (get+list) API's implemented first.  By all means investigate the write API's to ensure that the model for the read API's will work well there, but we can equally well do that as part of the Alpha->Beta stabiliization of the API's.

**Comment by jianhuiz** [comment]
@quinton-hoole I raised this because the write APIs are needed (and implemented) right now and I would like a consistent and back compatible API for all of them. Below are examples of Get (using name@cluster without the need of changing GetOptions, which I believe make more sense) and List (add ClusterSelector to ListOptions)

get Pod `nginx` from cluster `new-york`
```
# kubectl get po nginx@new-york -o custom-columns=CLUSTER:.metadata.clusterName,NAMESPACE:.metadata.namespace,NAME:.metadata.name,STATUS:.status.phase,LABELS:.metadata.labels -v8
...
I0811 19:49:37.523001   65624 round_trippers.go:296] GET http://localhost:8080/api/v1/namespaces/default/pods/nginx@new-york
...
CLUSTER    NAMESPACE   NAME      STATUS    LABELS
new-york   default     nginx     Running   map[name:nginx]
```

list all Pods across all the clusters
```
# kubectl get po -c "federation.beta.kubernetes.io/cluster-name" -o custom-columns=CLUSTER:.metadata.clusterName,NAMESPACE:.metadata.namespace,NAME:.metadata.name,STATUS:.status.phase,LABELS:.metadata.labels -v8
...
I0811 19:52:21.050209   65737 round_trippers.go:296] GET http://localhost:8080/api/v1/namespaces/default/pods?clusterSelector=federation.beta.kubernetes.io%2Fcluster-name
...
CLUSTER       NAMESPACE   NAME                     STATUS    LABELS
new-york      default     busybox-2net             Running   map[name:busybox]
new-york      default     nginx                    Running   map[name:nginx]
new-york      default     nginx-2net               Running   map[name:nginx]
new-york      default     nginx-host               Running   map[name:nginx]
new-york      default     nginx-nonet              Running   map[name:]
santa-clara   default     nginx                    Running   map[name:nginx]
santa-clara   default     nginx-1047703761-mnkpw   Pending   map[run:nginx pod-template-hash:1047703761]
```

**Comment by quinton-hoole** [comment]
Thanks @jianhuiz .  I haven't reviewed this code at all yet, but will try to soon.  In the mean time, is there a design doc for the write API's?  It seems that there are a ton of challenges to be overcome with that at a requirements and design level, over and above the basic API structure.

**Comment by quinton-hoole** [comment]
@jianhuiz Having thought about this a bit, I don't think that embedding name@cluster is a good approach.  For get and list, using GetOptions and ListOptions seems clearly more consistent with the existing API, and more general (in that one can select against any arbitrary set of labels, not just name).

So that leaves the question of what to do regarding cluster selection for the write API's.  And rather than try to answer that question in isolation, I think we need to carefully design the whole federated write API feature.  There is a meeting this week to start to discuss that, and I will make sure that you're invited.

To list just a few questions we will need to answer before being able to choose an appropriate cluster selection mechanism for writes:

1. Are write calls just proxied like reads, or is the desired state persisted in the federation, and propagated asynchronously to the clusters?  It seems like the latter is preferable.
2. Is it possible to perform a write operation across multiple clusters?  It seems like the answer should be yes - one of the major use cases would be for keeping multiple clusters in sync.
3. For which API types should it be possible to perform write operations. For example, one school of thought is that it should not be possible to create pods (or nodes) directly via the federation at all - higher level constructs like ReplicaSet should be used instead.
etc.

So as I mentioned above, I think you should focus on the read operations in this PR.

Q

**Comment by jianhuiz** [comment]
@quinton-hoole there are two kinds of APIs
1. List/Watch/DeleteCollections which operates on a collection of resource objects
2. Get/Delete/Update/UpdateStatus/Patch and Create which operates on a single object.

For 1 we use ListOptions to select the collection and perform operations in k8s, and for federation we add ClusterSelector to select the target clusters and then select the objects on each cluster.

For 2, we need a way to locate the object which means we need to pass the target cluster name.
For Update, UpdateStatus and Create, we can use the ObjectMeta.ClusterName  
For Get and Delete, now is to add ClusterName to both GetOptions and DeleteOptions. However there is an ambiguity of have both DeleteOptions.ClusterName and ListOptions.ClusterSelector for DeleteCollections API.  
For Patch, currently there is noway providing the cluster name without change the client function signature which means we may end up adding a PatchOptions and update all places calling the patch api.  
From my point of view, it's kind of chaotic that have ClusterName in GetOptions (via URL query parameter), DeleteOptions (via DELETE body, and ListOptions via qeury parameter) and PatchOptions (via query parameter)  
Therefor the case of locating a single object, I think use "name@cluster" to have a unique URL for the object to operate on, would be more consistent (and restful), not only for Get, Delete and Patch, but for Update, UpdateStatus and the expansion APIs as well

**Comment by jianhuiz** [comment]
@quinton-hoole in terms of the implementation of writing APIS themselves:
1. I prefer the proxy way which avoids the storage duplicating and syncing
2. write across clusters would be only on DeleteCollection, Create/Update/UpdateStatus/Patch are all on single object, like it now in k8s. Batch writes across clusters are better through a controller like what we have for deployment, replicaset, etc., not at the API level.
3. Currently we would like the federation control plane to be (in some extend) interchangeable with a k8s cluster

**Pull request closed without merging**
