### PR TITLE
small code improvements and fix some typos

### PR DESCRIPTION
**Pull request by bruceauyeung**
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>

**What this PR does / why we need it**:

1. eliminate unnecessary extra scale up limit calculation
2. eliminate unnecessary extra pods length computation
3. fix some typos

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by jszczepkowski** [comment]
@k8s-bot test this

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this

**Pull request merged**
