### PR TITLE
Revert "LimitRange updates for Resource Requirements Requests"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#12492

### CODE REVIEW

**Comment by piosz** [comment]
Jenkins is broken and this change may the cause.

cc @davidopp @derekwaynecarr @yujuhong

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by derekwaynecarr** [comment]
Was it the cause and is there anyway I can see the Jenkins results to
address?

**Comment by piosz** [comment]
I'm pretty sure it was not the cause, however we decided to revert all non trivial PRs merged once Jenkins started failing (so this one together with #13246 and #13247). Should be re-revert once Jenkins becomes stable.

**Comment by derekwaynecarr** [comment]
Who is doing the re-revert when the root cause is determined?

**Comment by yujuhong** [comment]
@k8s-oncall to re-revert.

**Comment by derekwaynecarr** [comment]
Was the root cause determined?

**Pull request merged**
