### PR TITLE
fix link on root README.md

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by bgrant0607** [comment]
I thought there was another PR on this -- other links are broken in this file, too....

**Comment by mikedanese** [comment]
There was #11295 but #11352 went in first with all the fixes from that PR. These are the remaining broken links and were not fixed in either of those PRs

**Comment by bgrant0607** [comment]
OK. LGTM. Thanks for fixing the overview link.

**Pull request merged**
