### PR TITLE
[DO NOT MERGE]: Add an e2e test for the pod sandbox changed scenario

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?
/kind bug
/kinde regression

#### What this PR does / why we need it:

This adds an e2e test to ensure that a pod should restart its containers in right order after the pod sandbox is changed.

#### Which issue(s) this PR fixes:

Fixes #
ref: #120247 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Was this merged correctly? The title and the label is weird for a merged PR.
`do-not-merge/release-note-label-needed` is still there.

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/pull/120281/commits

I think github considers that this is merged because the commit in here and #120281 are the same.

**Comment by pacoxu** [comment]
Got it. #120281 shared the same commit.

**Pull request merged**
