### PR TITLE
[DO NOT MERGE] This PR is to let us test the feature-serverside-apply branch

### PR DESCRIPTION
**Pull request by lavalamp**
DO NOT MERGE
DO NOT MERGE
DO NOT MERGE

We can write `/test` commands below to verify the feature branch continues to work. Leave this PR open indefinitely.

### CODE REVIEW

**Comment by apelisse** [comment]
Each rebase like this should show exactly how we've diverged from master. I think it's useful. Thanks!

**Comment by BenTheElder** [comment]
hmm yeah, so I mentioned this offline to @lavalamp but:
GitHub APIs have us reporting results to *commits* rather than PRs, so the best place to see test results from this at the moment is https://k8s-gubernator.appspot.com/pr/62554

**Comment by BenTheElder** [comment]
lol, looks like @k8s-merge-robot needs CLA :joy:

**Comment by liggitt** [comment]
can this be closed now?

**Pull request closed without merging**
