### PR TITLE
Remove master-log-dump.sh

### PR DESCRIPTION
**Pull request by tosi3k**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This script is not used anywhere now as its usage has been removed from kubetest in https://github.com/kubernetes/test-infra/pull/19773.

**Which issue(s) this PR fixes**:
No issue is opened for that.

**Special notes for your reviewer**:
/sig scalability
/assign @jkaniuk 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
N/A

### CODE REVIEW

**Comment by jkaniuk** [comment]
Older kubekins  images could point to this, right?

I would suggest waiting for 1.20 branch before merging this to master.

**Comment by tosi3k** [comment]
> Older kubekins images could point to this, right?

That's right, but all Kubemark jobs (at least the ones I see in k8s.io/test-infra/config repo subdirectory) use a sufficiently new `kubekins-e2e` image.

> I would suggest waiting for 1.20 branch before merging this to master.

Strong +1 - we will have much more freedom when the code freeze is over ;).

**Comment by jkaniuk** [comment]
OK
/lgtm
/hold
for creation of 1.20 branch before merging this to master.

**Comment by wojtek-t** [comment]
This won't be merged anyway now, because we're already in code freeze. This should go with 1.21.

/approve

**Comment by tosi3k** [comment]
1.20 is out.

/hold cancel

**Pull request merged**
