### PR TITLE
[WIP] Add etcd-operator to kubeadm

### PR DESCRIPTION
**Pull request by jamiehannaford**
**What this PR does / why we need it**:

Adds HA etcd to kubeadm. 

**Which issue(s) this PR fixes**:

https://github.com/kubernetes/kubeadm/issues/277

**Special notes for your reviewer**:

This is just a strawman PR, several changes still need to made, specifically to the operator to allow using node IPs rather than hostnames for etcd members. 

**Release note**:
```release-note
HA etcd now supported using the etcd-operator
```

/cc @luxas @timothysc @hongchaodeng

### CODE REVIEW

**Comment by luxas** [comment]
Thanks @jamiehannaford! Let me know if I should review this now or later. Ping me when I should.

**Comment by timothysc** [comment]
@jamiehannaford please ping me if/when you want me to review.

**Comment by errordeveloper** [comment]
@jamiehannaford is this still in progress?

**Comment by jamiehannaford** [comment]
@errordeveloper Kinda. I've been on vacation recently and I've started a new job, so not much time. The missing piece so far relates to https://github.com/coreos/etcd-operator/pull/1662#issuecomment-346501816 (ensuring members in etcd cluster use Pod IPs since kubeadm does not deploy a DNS server). Should get cycles in coming week or so.

**Comment by timothysc** [comment]
Per conversion from last week, we're going to close this given upstream pullback on the operator itself.

**Pull request closed without merging**
