### PR TITLE
improve code coverage for pkg/admission/attributes.go

### PR DESCRIPTION
**Pull request by NickrenREN**
improve code coverage for pkg/admission for #39559 .

@resouer  @k82cn 

[combined-coverage.gz](https://github.com/kubernetes/kubernetes/files/710324/combined-coverage.gz)

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by davidopp** [comment]
@timothysc

**Comment by timothysc** [comment]
So, I don't have a problem with this... but, lets try to be a bit more strategic and aim for meaningful coverage and behavior verification over just increasing our numbers.

**Comment by cmluciano** [comment]
@NickrenREN did you mean to close this?

**Comment by NickrenREN** [comment]
@cmluciano  yes

**Pull request closed without merging**
