### PR TITLE
Fix typo and generate specs, so docs can be regenerated.

### PR DESCRIPTION
**Pull request by steveperry-53**
**What this PR does / why we need it**:
This PR is a second attempt at something I tried to do in #57525. I have revised the process according to guidance from @mbohlool.  
The purpose of this PR is for me to learn the process of updating the [Kubernetes API reference documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/), and then to document that process. I'm working on getting the process documented in [PR 6366](https://github.com/kubernetes/website/pull/6366) in the kubernetes/website repository. Here's a [preview of the new topic](https://deploy-preview-6366--kubernetes-io-master-staging.netlify.com/docs/home/contribute/generated-reference/kubernetes-api/).

In the docs, I would like to refer to this PR as an example. So I have kept the change simple: fix one typo.

Related issues:
https://github.com/kubernetes/website/issues/921
https://github.com/kubernetes/website/issues/922

**Special notes for your reviewer**:
In the future, we might want to make the doc generation process a bit more automatic. But for now I think it's important to get the current process documented.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by steveperry-53** [comment]
@mbohlool According to your description of the process, I separated this into two commits and made master the target branch.

**Comment by cblecker** [comment]
@steveperry-53 Needs a `hack/update-api-reference-docs.sh`

**Pull request merged**
