### PR TITLE
Change kubelet flag --max-pods default value to 40 to match v1.0 roadmap

### PR DESCRIPTION
**Pull request by dchen1107**
Sent this one separately from #11027 since allow-privileged is still under debate, but I really want to include this one for v1.0. 

cc/ @bgrant0607 @davidopp @thockin 

cc/ @timstclair for density tests.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by davidopp** [comment]
Worth noting that we chose 40 to allow 30 user pods plus a generous number of cluster addon pods.

**Comment by davidopp** [comment]
LGTM

ok to merge once tests pass

**Comment by mikedanese** [comment]
can we update https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubelet.md

**Pull request merged**
