### PR TITLE
[doc]:Fix the Kustomize kind of resource mistakes in the documantion.

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind documentation

**What this PR does / why we need it**:

When I was reading the resources of Kustomize https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html, I found there was a mistake. The kind of Kustomize resource name should be `bases`, not `base`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Aisuko** [comment]
Hi, @deads2k  Any feedback with this small change?

**Comment by Aisuko** [comment]
ping @soltysh @smarterclayton

**Comment by Aisuko** [comment]
@ash2k Hello sir, I saw there may require an `approved` label

**Comment by ash2k** [comment]
@Aisuko Yes, but I don't have permissions to approve, sorry.

**Comment by Aisuko** [comment]
bad robot

**Review by soltysh — APPROVED** [review]
/approve
/priority backlog

**Pull request closed without merging**
