### PR TITLE
Add a link to liggitt's deflake docs in Flake template

### PR DESCRIPTION
**Pull request by MushuEE**
We could have prow bot link comment the link but I think this should be enough to increase visibility to the doc when people encounter a flake

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Increases visibility of @liggitt 's wonderful deflake document

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @spiffxp @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md might be a more canonical page. I'd like to see useful bits hoisted from the presentation into that page.

**Comment by MushuEE** [comment]
@liggitt thanks, I don't mind updating that as well unless you feel strongly about how it gets organized with your updates
/label tide/merge-method-squash

**Review by hasheddan — APPROVED** [review]
/lgtm
/retest

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Review by nikhita — APPROVED** [review]
/approve

**Pull request merged**
