### PR TITLE
fix default CONTAINER_RUNTIME_ENDPOINT for docker

### LINKED ISSUE #91990: [Failing Test] gce-device-plugin-gpu-master (ci-kubernetes-e2e-gce-device-plugin-gpu)
**Which jobs are failing**:

`gce-device-plugin-gpu-master (ci-kubernetes-e2e-gce-device-plugin-gpu)`

**Which test(s) are failing**:

`Up`

**Since when has it been failing**:

`06-09-20 16:31 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

**Reason for failure**:

```
W0610 14:13:28.065] 2020/06/10 14:13:28 process.go:155: Step './hack/e2e-internal/e2e-down.sh' finished in 6m37.239818042s
W0610 14:13:28.065] 2020/06/10 14:13:28 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0610 14:13:28.065] 2020/06/10 14:13:28 main.go:312: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1
W0610 14:13:28.066] Traceback (most recent call last):
W0610 14:13:28.067]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 720, in <module>
W0610 14:13:28.067]     main(parse_args())
W0610 14:13:28.067]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 570, in main
W0610 14:13:28.068]     mode.start(runner_args)
W0610 14:13:28.068]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0610 14:13:28.069]     check_env(env, self.command, *args)
W0610 14:13:28.069]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0610 14:13:28.069]     subprocess.check_call(cmd, env=env)
W0610 14:13:28.069]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0610 14:13:28.070]     raise CalledProcessError(retcode, cmd)
W0610 14:13:28.070] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-project-type=gpu-project', '--gcp-zone=us-west1-b', '--test_args=--ginkgo.focus=\\[Feature:GPUDevicePlugin\\] --minStartupPods=8', '--timeout=180m')' returned non-zero exit status 1
```

**Anything else we need to know**:

/sig testing
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

### PR DESCRIPTION
**Pull request by dims**
Made a mistake, container runtime endpoint should be the dockershim sock file!!

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #91990

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

/retest

**Comment by spiffxp** [comment]
followup to https://github.com/kubernetes/kubernetes/pull/91684

**Pull request merged**
