### PR TITLE
fix kubectl run output

### LINKED ISSUE #40440: kubectl run --dry-run --output=yaml produces unusable YAML
```
> kubectl run nginx --image=nginx --restart=Always --expose --port=80 --output=yaml --dry-run
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
status:
  loadBalancer: {}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
>
```

This should be a `kind: List` or a YAML multidoc. The JSON version is arguable more usable...

### PR DESCRIPTION
**Pull request by xilabao**
fixes https://github.com/kubernetes/kubernetes/issues/40440

### CODE REVIEW

**Comment by eparis** [comment]
I tend to agree this is only a half fix. Should I be able to do

kubectl run ... | kubectl create -f -

?  Does that work here with the --- or do we just stop parsing there?

**Comment by xilabao** [comment]
@eparis It could be work with "---".
```
#kubectl run nginx --image=nginx --restart=Always --expose --port=80 --output=yaml --dry-run | kubectl create -f -
service "nginx" created
deployment "nginx" created
```

```
#kubectl run nginx --image=nginx --restart=Always --expose --port=80 --output=json --dry-run | kubectl create -f -
service "nginx" created
deployment "nginx" created
```

**Comment by xilabao** [comment]
ping @eparis

**Comment by xilabao** [comment]
@eparis kindly ping

**Comment by eparis** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by xilabao** [comment]
@brendandburns need to get your approval.

**Comment by xilabao** [comment]
@k8s-bot bazel test this

**Pull request merged**
