### PR TITLE
Added 'mounterPath' to Mounter interface in 'mount_unsupported.go'.

### LINKED ISSUE #35257: kubernetes-cross-build: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-cross-build/1167/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by k82cn**
fixes #35257 .

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35271)

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by wojtek-t** [comment]
I'm merging manually to fix the build.

**Comment by jingxu97** [comment]
@k82cn @wojtek-t  Thank you very much for the fix!

**Pull request merged**
