### PR TITLE
Added 'uid' flag to kubectl run command.

### PR DESCRIPTION
**Pull request by xingzhou**
This is the first PR for #33065.

The following changes are included in this patch:
    1. Provided a new '--uid' flag for kubectl run comman
    2. Enabled docker cri interface to support running co
       with a specific uid parameter.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35678)

### CODE REVIEW

**Comment by vishh** [comment]
Why is this PR needed?

**Comment by xingzhou** [comment]
@vishh, we submitted this PR to enhance ```kubectl run``` command, this will help the user to select specific uid rather than the default user defined in the container when running a pod. There are some details in ticket #33065. Thanks for your time, any other comments, please let me know, I'm now working on the following PRs to support uid for rkt runtime and gid flag for the same ticket.

**Comment by xingzhou** [comment]
@vishh, would you please help review this patch? please let me know if you have any comments on the patch, and there are following patches prepared for adding gid flag for docker runtime/gid & uid flag support for rkt runtime. thanks!

**Comment by xingzhou** [comment]
@vishh, not sure if you have time to review this patch? if so, I would like to rebase the patch then.

**Comment by pwittrock** [comment]
@vishh Is this something we want in kubelet?

**Comment by derekwaynecarr** [comment]
I am not convinced we need or want this in the kubectl run command.  docker run supports a lot of options we don't expose.  how common is this?

**Comment by vishh** [comment]
I'm not convinced we need this feature. I'd suggest waiting for enough +1s on https://github.com/kubernetes/kubernetes/issues/33065 before adding this. 
I suspect @thockin thinks this is useful. May be he has some solid arguments for wanting this feature.

**Comment by thockin** [comment]
My arguments for this were that it seems natural and obvious.  We provide that control via YAML, it seems to fit the CLI.  I'm not going to fight hard for it, but I'd probably use it.

**Pull request closed without merging**
