### PR TITLE
Deleting federation-util-14.go that is not being used anywhere

### PR DESCRIPTION
**Pull request by nikhiljindal**
We have the same code in federation-util.go

cc @mwielgus @madhusudancs

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Its a simple PR. Good one for @shashidharatd to get started as a reviewer :)

**Comment by shashidharatd** [comment]
Thanks @nikhiljindal, the changes LGTM.

**Review by shashidharatd — APPROVED** [review]
The changes LGTM

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this
OpenAPI failure is a known flake

**Comment by nikhiljindal** [comment]
@shashidharatd you need to add the LGTM label for the PR to be officially LGTM'd and picked up by the merge bot.

Am adding the label myself this time.

**Comment by shashidharatd** [comment]
Thanks @nikhiljindal for letting me know :)
I was waiting for bot, thinking it will apply lgtm label, if we used LGTM in comment.

**Comment by nikhiljindal** [comment]
Sam flake.
 @k8s-bot unit test this

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this

**Pull request merged**
