### PR TITLE
kubeadm: cleanup UnknownCRISocket

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- skip CRI detection for `kubeadm upgrade diff` (CRI socket is not used at all)
- cleanup `UnknownCRISocket` for unit tests
- remove unused constant `UnknownCRISocket`

#### Which issue(s) this PR fixes:

Ref #117614

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
why not include all these changes in a single PR?

**Comment by SataQiu** [comment]
The remaining one is about `runDiff()`, I'll check if the CRI detection can be skipped for it.

```sh
# grep UnknownCRISocket -r cmd/kubeadm
cmd/kubeadm/app/cmd/upgrade/diff_test.go:kubernetesVersion: %[3]s`, kubeadmapiv1.SchemeGroupVersion.String(), constants.UnknownCRISocket, currentVersion))
cmd/kubeadm/app/constants/constants.go: // UnknownCRISocket defines the undetected or unknown CRI socket
cmd/kubeadm/app/constants/constants.go: UnknownCRISocket = "unix:///var/run/unknown.sock"
cmd/kubeadm/app/phases/uploadconfig/uploadconfig_test.go:                       cfg.NodeRegistration.CRISocket = kubeadmconstants.UnknownCRISocket
```

/hold

**Comment by SataQiu** [comment]
All the references to `UnknownCRISocket` have been cleaned up from kubeadm codebase.
/hold cancel

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Pull request merged**
