### PR TITLE
Fix golint issue in pkg/kubelet/prober

### PR DESCRIPTION
**Pull request by kaleocheng**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Fix golint failures of pkg/kubelet/prober

**Which issue(s) this PR fixes**:
Ref https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — APPROVED** [review]
/ok-to-test
/priority backlog
/lgtm

**Review by mattjmcnaughton — COMMENTED** [review]
Is this failing with the most recent version of `golint`?

Fwiw, I'm not seeing this failure when I run `golint ./pkg/kubelet/prober/...`, even after running `go get -u golang.org/x/lint/golint`.

**Comment by kaleocheng** [comment]
@mattjmcnaughton  not sure why you didn't get it but  I got this error  whether running `golint` directly or running `./hack/verify-golint.sh`


```bash
$ go version 
go version go1.12.6 darwin/amd64
$ go get -u golang.org/x/lint/golint
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'

$ golint ./pkg/kubelet/prober/
pkg/kubelet/prober/prober_manager_test.go:40:18: should omit type *v1.Probe from declaration of var defaultProbe; it will be inferred from the right-hand side
```

```bash
$ ./hack/verify-golint.sh 
installing golint from vendor
Errors from golint:
pkg/kubelet/prober/prober_manager_test.go:40:18: should omit type *v1.Probe from declaration of var defaultProbe; it will be inferred from the right-hand side

Please review the above warnings. You can test via "golint" and commit the result.
If the above warnings do not make sense, you can exempt this package from golint
checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
```

**Comment by mattjmcnaughton** [comment]
On Sat, Jun 22, 2019 at 07:56:15AM -0700, Kaleo wrote:
Whoops, I think I just needed to fetch the most recent source. I'm seeing it now
:)

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by kaleocheng** [comment]
I have no idea about the failed test above, is it related to my change?

**Comment by sjenning** [comment]
@kaleocheng no, the failures do not have to do with your changes.  flakes in the integration tests
```
k8s.io/kubernetes/test/integration/scheduler	
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration/conversion
```
xref https://github.com/kubernetes/kubernetes/issues/79177
/retest

**Pull request closed without merging**
