### PR TITLE
bump corecontroller statefulset to appsv1beta2

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
xref #51049

**Special notes for your reviewer**:
/assign @janetkuo
/cc @liyinan926

**Release note**:

```release-note
bump corecontroller statefulset to appsv1beta2
```

### CODE REVIEW

**Comment by liyinan926** [comment]
@dixudx Thanks for doing this! FYI, I'm currently working on moving DaemonSet controller and @crimsonfaith91 is working on moving Deployment.

**Review by kow3ns — APPROVED** [review]

**Comment by deads2k** [comment]
Doing this means that your controller will not be able to run against older servers.  Are you sure this is really what you want to do?

**Comment by dixudx** [comment]
@deads2k Yes, part of #51049.

**Comment by deads2k** [comment]
/approve

the kube-controller-manager changes.  I'll leave the review to janet who is better suited to the area.

**Comment by dims** [comment]
@dixudx Are we trying to get this into 1.9? please rebase if so

**Comment by divyenpatel** [comment]
@dixudx  Can we get this in? We have statefulset e2e test which is getting panicked with version `apiVersion: apps/v1beta2`.

Changes made in this PR is required for our test to run successfully. We are utilizing `statefulset_utils.go`.

**Comment by dixudx** [comment]
@divyenpatel Updated. PTAL. Sorry for the delay.

**Comment by dixudx** [comment]
ping @janetkuo @dims PTAL. Thanks.

**Comment by dims** [comment]
@dixudx looks like we need to wait for @janetkuo or @lavalamp

**Comment by dixudx** [comment]
/close

in favor of #55792.

StatefulSet controller has been bumped to apps/v1.

@divyenpatel FYI.

**Pull request closed without merging**
