### PR TITLE
Add myself, Micah to reviewers

### PR DESCRIPTION
**Pull request by nckturner**
**Release note**:
```release-note
NONE
```

Signed-off-by: Nick Turner <nic@amazon.com>

### CODE REVIEW

**Comment by jsafrane** [comment]
Note that the [official process](https://github.com/kubernetes/community/blob/master/community-membership.md) expects that contributors slowly graduate from "outside community" through "member" and "reviewer" states in order to reach "approver". We can speed up the process of course, people with deep AWS knowledge are always welcome, however approvers really should know Kubernetes processes by heart and block PRs that break e.g. backward/forward compatibility expectations or API conventions.

**Comment by nckturner** [comment]
@jsafrane Yeah that totally makes sense.  Our goal here was to provide help with the migration out of tree for the AWS cloud provider.  We are interested primarily in bug fixes and at some point, stopping feature work here and migrating it to the out of tree repository.

**Comment by justinsb** [comment]
/retest

But: Can you change it to start as reviewers only (not approvers) for now - the process just helps everyone calibrate, and I'd rather just stick to the process for fairness.  We don't need as much of a strict ladder any more, but I think the sequencing does have value.

**Pull request merged**
