### PR TITLE
Remove garbage characters (^M) under test/*

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Just happened to notice `test/e2e/framework/.import-restrictions` is full of garbage characters.

(You can run `vi -b test/e2e/framework/.import-restrictions` to display those characters)

image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
Other `.import-restrictions` files look good.

/sig testing

**Comment by Huang-Wei** [comment]
@spiffxp Could you take a look? Thanks.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
