### PR TITLE
Delegate cgroup exists to systemd and libcontainer

### PR DESCRIPTION
**Pull request by odinuge**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

When systemd cgroup driver is used, systemd is responsible for ensuring
the correct controllers are propagated. If we try to propagate a
controller controlled by systemd, it can remove it for us, creating a
mess.

This fixes issues when `burstable.slice` exists, but systemd removes the cpuset controller since it isn't in use. In this case, trying to recreate the slice will cause a fatal error in kubelet.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by odinuge** [comment]
Still WIP and testing, but;

/cc @harche

**Comment by kolyshkin** [comment]
By the way, since https://github.com/opencontainers/runc/pull/2338/commits/9087f2e827d971ad2e5b5b6a57048a3d211776ee all runc/libcontainer's cgroup controllers have Exists() method which might be used here. The difference though is the libcontainer Exists do not check the presence of all the controllers, assuming that if Apply() was called, they all either do or do not exist.

If it is possible to relax the "exists" check in here, this might result in removing a lot of code :)

**Comment by kolyshkin** [comment]
I would also audit all the uses of `Exists` (there are 6, excluding tests) and maybe drop some of them.

Say, calling `Exists` before `Create` does not make much sense as `Create` is relatively fast and (AFAICS) repeated `Create` is won't break anything, while `Exists` (before this PR at least) is somewhat heavy.

Calling `Exists` before `Update` does not make much sense either -- if cgroup does not exists, `Update` will return an error anyway.

**Comment by odinuge** [comment]
> By the way, since opencontainers/runc@9087f2e all runc/libcontainer's cgroup controllers have Exists() method which might be used here. The difference though is the libcontainer Exists do not check the presence of all the controllers, assuming that if Apply() was called, they all either do or do not exist.

Ahh, I see. I just saw this issues https://github.com/opencontainers/runc/issues/1440 and thought it wasn't fixed.

> Say, calling Exists before Create does not make much sense as Create is relatively fast and (AFAICS) repeated Create is won't break anything, while Exists (before this PR at least) is somewhat heavy.

Well, it kinda depends. Calling `create` in case the systemd slice/scope already exists results in an error that is fatal to kubelet. This is essentially whan happen in case of a kubelet restart. In case of cgroupfs we could probably just use `Create` anyways, since that will ensure all controllers are enabled.

> Calling Exists before Update does not make much sense either -- if cgroup does not exists, Update will return an error anyway.

Well, yeah. If we want to create it, we would of course need to verify if we should run create or update.

**Comment by ehashman** [comment]
/priority backlog
/triage accepted

Tests appear to still be failing, which tests should be fixed by this PR?

**Comment by odinuge** [comment]
> Tests appear to still be failing, which tests should be fixed by this PR?

Well, this fixes an issue with k8s where we try to create `kubepods.slice` when it exists, causing kubelet to fail startup. When we delegate cgroup things to systemd, we should not interfere with it ourselves (with some exceptions ofc.)

```
"Failed to start ContainerManager" err="failed to initialize top level QOS containers: failed to create top level Burstable QOS cgroup : error while starting unit \"kubepods-burstable.slice\" with properties [{Name:Description Value:\"libcontainer container kubepods-burstable.slice\"} {Name:Wants Value:[\"kubepods.slice\"]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]: Unit kubepods-burstable.slice already exists.
```



This is evident in `pull-kubernetes-node-kubelet-serial-crio-cgroupv2`, but this change does not fix the _whole_ test suite, but it makes the test suite able to continue running. You can see one run here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-kubelet-serial-crio-cgroupv2/1398253094348787712

**Comment by kolyshkin** [comment]
> > Tests appear to still be failing, which tests should be fixed by this PR?
> 
> Well, this fixes an issue with k8s where we try to create `kubepods.slice` when it exists, causing kubelet to fail startup. When we delegate cgroup things to systemd, we should not interfere with it ourselves (with some exceptions ofc.)
> 
> ```
> "Failed to start ContainerManager" err="failed to initialize top level QOS containers: failed to create top level Burstable QOS cgroup : error while starting unit \"kubepods-burstable.slice\" with properties [{Name:Description Value:\"libcontainer container kubepods-burstable.slice\"} {Name:Wants Value:[\"kubepods.slice\"]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]: Unit kubepods-burstable.slice already exists.
> ```

Alas, there is a regression in runc rc94 which will be fixed in 1.0 -- https://github.com/opencontainers/runc/pull/2997.

Now, 1.0 should be released Real Soon Now, but if we can't wait, I can remove `[DNM]` from https://github.com/kubernetes/kubernetes/pull/102508 (which I have just updated), it contains the above fix.

**Comment by odinuge** [comment]
> Alas, there is a regression in runc rc94 which will be fixed in 1.0 -- opencontainers/runc#2997.

Ahh, I see. So this regression was introduced in k8s in https://github.com/kubernetes/kubernetes/pull/102147 and backported in https://github.com/kubernetes/kubernetes/pull/102196? I am I understanding it right then?

> Now, 1.0 should be released Real Soon Now, but if we can't wait, I can remove [DNM] from #102508 (which I have just updated), it contains the above fix.

That's up to the dependency people I guess. We should probably create an issue in k8s to track this issue properly so that people are aware of it, since it is a new regression (soon to be released). Can you do that @kolyshkin? 

/cc @dims @liggitt

**Comment by dims** [comment]
+1 to wait for runc 1.0.0

**Comment by odinuge** [comment]
> +1 to wait for runc 1.0.0

Agree

**Comment by kolyshkin** [comment]
> We should probably create an issue in k8s to track this issue properly so that people are aware of it, since it is a new regression (soon to be released). Can you do that @kolyshkin?

Done: https://github.com/kubernetes/kubernetes/issues/102676.

**Comment by ehashman** [comment]
/hold

while we wait for runc 1.0.0

**Comment by odinuge** [comment]
Test failures are btw. because those test suites have a huuuge amount of failing tests (that we are still working on). This one helps a bit on the overall health.

/skip

**Comment by voigt** [comment]
Hi (@bobbypage, @yujuhong, @harche, @dims)
Bug-Triage here:
we are already past code freeze, so I suggest moving this PR to `milestone v1.23`. WDYT?

**Comment by georgyo** [comment]
> Hi (@bobbypage, @yujuhong, @harche, @dims)
> Bug-Triage here:
> we are already past code freeze, so I suggest moving this PR to `milestone v1.23`. WDYT?

This regression affects me. Since it is a regression I don't think it should be affected by the code freeze. During a code freeze, bug fixes can still go in.

**Comment by liggitt** [comment]
if this is fixing a release-blocking regression, that should be linked prominently in the PR description so it doesn't get bumped from the release incorrectly

**Comment by ehashman** [comment]
> Hi (@bobbypage, @yujuhong, @harche, @dims)
> Bug-Triage here:
> we are already past code freeze, so I suggest moving this PR to `milestone v1.23`. WDYT?

I believe we may end up closing this PR in favour of https://github.com/kubernetes/kubernetes/pull/103743. As @liggitt pointed out the description is a bit coy, this addresses a serious issue.

**Comment by ehashman** [comment]
/milestone clear

from SIG Node CI subgroup today, this isn't release-critical -- we will handle this via the runc bump

**Comment by dims** [comment]
@ehashman @odinuge do we still need this?

**Pull request closed without merging**
