### PR TITLE
More node describe, and 'kubectl describe' tests for all resources

### PR DESCRIPTION
**Pull request by deyuanix**

### CODE REVIEW

**Comment by jlowdermilk** [comment]
LGTM. Test failures look like flakes, kicked both.

**Comment by jlowdermilk** [comment]
Integration test still failing. You may want to rebase to HEAD to pick up fix from #5775.

**Comment by ddysher** [comment]
Rebased

**Comment by jlowdermilk** [comment]
lgtm. Shippable green; merging.

**Pull request merged**
