### PR TITLE
doTestPlugin func delete para path in nfsvolume

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
in doTestPlugin func there has two para equal mounter.GetPath(),so delete one!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
PTAL @brendandburns @sjenning

**Comment by sjenning** [comment]
It actually looks like the correct thing to do here is simply remove the `volumePath := mounter.GetPath()` on line 123 as it derefs mounter before ensuring it is non-nil.

**Comment by jianglingxia** [comment]
thanks,but I want to know that For some reason I deleted the original repository and cloned a new one, now the branch has become unknown repository，so how can I update the pr in the branch?

**Comment by jianglingxia** [comment]
reopen #54031  because of some reason that the branch become unknown repository,so commit a new pr and then close The original pr，thanks！

**Comment by jianglingxia** [comment]
yes,you are right,before ensuring it is non-nil and then Assign a value to a variable！ @sjenning thanks

**Pull request closed without merging**
