### PR TITLE
Correct bandwitdh value passed to bandwidth CNI

### PR DESCRIPTION
**Pull request by dongjun666**
**What this PR does / why we need it**:
In bandwidth CNI, rate unit is bps and burst unit is bits that the rate value applied to tbf is one of 1000 of expected.
Another issue, passing 0 to burst value is not permitted when rate value is set.

/sig network

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dongjun666** [comment]
CLA signature

**Comment by dcbw** [comment]
cc @squeed

**Comment by dongjun666** [comment]
Related patch revising misleading unit description for containernetworking/plugins:
https://github.com/containernetworking/plugins/commit/6a12a375cd1f27a6a5b5253fdb275658a60c3a5d

**Review by xiaoxubeii — APPROVED** [review]

**Review by squeed — APPROVED** [review]
Confirmed that the annotation is expected to be in bits per second.

**Comment by GhostComputing** [comment]
I think the default burst should be larger than typical device MTU plus protocol header length, which is **1540 bytes (in most typical environment)**. 

If the burst is smaller than MTU size, once the packet size larger than burst and the kernel don't support TSO, it will just drop the packet and continue dropping. For example, if you set egress rate is 1Mbit/s and the burst is 1250, it cannot limit bandwidth.

You can check the [4.18 kernel code](https://github.com/torvalds/linux/blob/v4.18/net/sched/sch_tbf.c#L190). 
@dongjun666

**Comment by dongjun666** [comment]
> I think the default burst should be larger than typical device MTU plus protocol header length, which is **1514 bytes (in most typical environment)**.
> 
> If the burst is smaller than MTU size, once the packet size larger than burst and the kernel don't support TSO, it will just drop the packet and continue dropping. For example, if you set egress rate is 1Mbit/s and the burst is 1250, it cannot limit bandwidth.
> 
> You can check the [4.18 kernel code](https://github.com/torvalds/linux/blob/v4.18/net/sched/sch_tbf.c#L190).
> @dongjun666

Sorry for the late reply. You are right, thanks. I merged the burst modification of master into this patch and it works.

**Comment by mmack** [comment]
Any update on this?

**Review by m1093782566 — APPROVED** [review]
LGTM

**Review by johscheuer — COMMENTED** [review]
This is already in master (see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L411), so I assume this PR can be closed ?

**Pull request closed without merging**
