### PR TITLE
Remove pvc update events from volume restriction

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We use PersistentVolumeClaimVolumeSource as the VolumeSource in the pod, only need the claimName field
ref: https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/staging/src/k8s.io/api/core/v1/types.go#L186-L198

And pvc's AccessModes can't be changed, so we can't update pvc's AccessModes to make the pod schedulable.
ref: https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/apis/core/validation/validation.go#L2372-L2375
This means that the update event of the PVC has no effect on the scheduling of the pod.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/approve

It requires the attention from sig-storage.

@kubernetes/sig-storage-feature-requests leave `/lgtm` for you.

**Comment by HirazawaUi** [comment]
/close
We have resolved it in #125280.

**Pull request closed without merging**
