### PR TITLE
Automated cherry pick of #56759: Fix NLB icmp permission duplication

### PR DESCRIPTION
**Pull request by micahhausler**
Cherry pick of #56759 on release-1.9.

#56759: Fix NLB icmp permission duplication

### CODE REVIEW

**Comment by mbohlool** [comment]
please add:
- release note
- test (or justification for lack of)
and ask for usual lgtm/approvals.

**Comment by mbohlool** [comment]
/hold

This will not get into 1.9.8 patch release. Please contact me if you think it should be otherwise it will be included in next patch release.

**Comment by justinsb** [comment]
This one is trickier than #63738 - it's a less trivial code change, but because the feature is still alpha we merged it into master with fewer tests than a stable feature would require.  However I think @mbohlool is right to hold us to a higher bar for cherry-picks.

Maybe we should have a higher standard for alpha features even in master - I'm not really sure.

**Comment by mbohlool** [comment]
@micahhausler any update on this?

**Comment by mbohlool** [comment]
I am going to close this PR for inactivity. If you still need this, please re-open.

**Pull request closed without merging**
