### PR TITLE
Godeps: bump go-oidc to fix the race in tests.

### PR DESCRIPTION
**Pull request by yifan-gu**
Bump the go-oidc version as https://github.com/coreos/go-oidc/pull/27 has landed.

@liggitt How can I also verify the race in kubernetes is also fixed? Or can you help me on this?

related to https://github.com/kubernetes/kubernetes/pull/13838

### CODE REVIEW

**Comment by mikedanese** [comment]
@yifan-gu 
```
oidc_test.go:381: #3: Expecting: oidc: JWT claims invalid: invalid claim value: 'aud'..., but got: oidc: JWT claims invalid: invalid claims, 'aud' claim and 'client_id' do not match, aud=client-bar, client_id=client-foo
```

**Comment by yifan-gu** [comment]
@mikedanese Thank you, updated the error message in the tests, should pass this time.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by mikedanese** [comment]
```
+++ [1210 09:06:44] Placing binaries
hack/verify-flags-underscore.py
hack/verify-godeps.sh master
Starting to download all kubernetes godeps. This takes a while
Download finished
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Looks like travis would give godeps more time if it would print out a period every so often to indicate it wasn't stalled. cc @eparis

**Comment by yifan-gu** [comment]
Not sure if it's stalled, will take a look today.

**Comment by wojtek-t** [comment]
@yifan-gu - it may not be your fault (given that Jenkins unit/integration is passing). Maybe we should increase timeout?

**Comment by timothysc** [comment]
works for me on change... thx. 

ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc	9.300s

Do we have an eta on this, it always taints my local testing.

**Comment by wojtek-t** [comment]
I would like to have this in ASAP (= as soon as travis passes).

@eparis - what do you suggest - I think there are 2 possibilities:
- increasing timeout
- make the verify-godeps somehow smarter (e.g. what @mikedanese suggested above - printing period once per some time)

**Comment by eparis** [comment]
So at that point (based on the output) it is running `godep save ./...` which shouldn't take 10 minutes...

**Comment by eparis** [comment]
I'm looking at this right now.

**Comment by wojtek-t** [comment]
@eparis - thanks!
Note, that we have a bunch of different issues in Travis where many things are running muuuuuuch longer that when running locally...

**Comment by yifan-gu** [comment]
Saw the same issue as https://github.com/tools/godep/issues/359 when running locally, both on master branch and this branch:
```
hack/verify-godeps.sh 
Starting to download all kubernetes godeps. This takes a while
godep: error restoring dep (github.com/Sirupsen/logrus): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.9G0wU0/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/boltdb/bolt): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.9G0wU0/src/github.com/boltdb/bolt
godep: error restoring dep (github.com/docker/docker/pkg/jsonmessage): Unable to find dependent package github.com/Azure/go-ansiterm/winterm in context of /tmp/gopath.9G0wU0/src/github.com/docker/docker/pkg/term
godep: error restoring dep (github.com/docker/docker/pkg/term): Unable to find dependent package github.com/Azure/go-ansiterm/winterm in context of /tmp/gopath.9G0wU0/src/github.com/docker/docker/pkg/term
godep: error restoring dep (github.com/docker/libcontainer): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.9G0wU0/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/api): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/http): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/manager): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/pages): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/validate): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
!!! Error in hack/verify-godeps.sh:65
  '"${GODEP}" restore' exited with status 1
Call stack:
  1: hack/verify-godeps.sh:65 main(...)
Exiting with status 1
Removing /tmp/gopath.9G0wU0
Makefile:44: recipe for target 'verify' failed
make: *** [verify] Error 1
```

**Comment by yifan-gu** [comment]
Waiting on #18671

**Comment by eparis** [comment]
I just self merge #18671   please rebase.

**Comment by yifan-gu** [comment]
travis is green.

**Comment by wojtek-t** [comment]
Awesome thanks - LGTM

**Comment by timothysc** [comment]
@wojtek-t, @yifan-gu  - Even post merge I still get unit-test failures 

https://paste.fedoraproject.org/302341/37395614/

**Comment by yifan-gu** [comment]
@timothysc Is that go 1.5?

**Comment by timothysc** [comment]
@yifan-gu 1.5.1 on fedora 23. 
http://koji.fedoraproject.org/koji/buildinfo?buildID=693253

**Comment by yifan-gu** [comment]
Interesting,  I run with 1.5.2 on my ubuntu 15.04, it passed.
```
$ go version
go version go1.5.2 linux/amd64
yifan@yifan-coreos:~/kubernetes$ hack/test-go.sh plugin/pkg/auth/authenticator/token/oidc/
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [1217 10:06:07] Running tests without code coverage
ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc	7.945s
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: kubernetes.io/registry
+++ [1217 10:06:20] Running tests without code coverage
ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc	8.723s
$ go version
go version go1.5.2 linux/amd64
yifan@yifan-coreos:~/kubernetes$ hack/test-go.sh plugin/pkg/auth/authenticator/token/oidc/
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [1217 10:06:07] Running tests without code coverage
ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc	7.945s
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: kubernetes.io/registry
+++ [1217 10:06:20] Running tests without code coverage
ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc	8.723s
```

**Comment by yifan-gu** [comment]
1.5.1 also passed. Hmm

**Comment by yifan-gu** [comment]
@timothysc Is that flaky, or you consistently get the error?

**Comment by timothysc** [comment]
@yifan-gu appears to flake.

**Comment by yifan-gu** [comment]
@timothysc Thanks, will take a look.

**Comment by timothysc** [comment]
I still see it on my 1.5.2 update. 
/cc @liggitt

**Comment by yifan-gu** [comment]
@timothysc Will take a look today. Seems like this is not the same issue this PR fixes.

**Comment by yifan-gu** [comment]
@timothysc Can you provide more logs, like  `hack/test-go.sh plugin/pkg/auth/authenticator/token/oidc/ -v` ?
I am curious which test fails. There are more than one tests

**Comment by timothysc** [comment]
@yifan-gu as requested : https://paste.fedoraproject.org/302387/45038157/

**Comment by wojtek-t** [comment]
hmm - it's strange that I've run all tests with go 1.5.2 version 10+ times and I didn't see this failure even once...

**Comment by timothysc** [comment]
I wonder if this is touching the patent restriction issue. I may dig a bit today.

**Comment by yifan-gu** [comment]
@timothysc The logs shows at least the first 5 test cases in TestOIDCAuthentication passed. I also noticed that there are goroutines for oidc provider sync are leaking during tests. (normally it's not a problem as the authenticator is not intended to be closed) I can send a PR to fix that, but not sure if that fixed the failures.

**Comment by wojtek-t** [comment]
I've just seen this: https://github.com/kubernetes/kubernetes/issues/18928
The failure comes from exactly this test, but seems to be related to httptest.Server ??

**Pull request merged**
