### PR TITLE
Actually fix local-cluster-up on 1.5 branch

### LINKED ISSUE #38847: hack/local-up-cluster.sh broken on latest 1.5 branch
local cluster failed to start in the latest 1.5 branch (commit 09cb1a9df8455c87c4e0f204e0f4e05284e7cf28):

```console
$ hack/local-up-cluster.sh                                                                                                                                  
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
+++ [1215 15:40:40] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:40:40] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:40:44] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [1215 15:40:52] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:40:52] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:40:55] Building go targets for linux/amd64:
    cmd/libs/go2idl/defaulter-gen
+++ [1215 15:41:02] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:02] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:06] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
+++ [1215 15:41:14] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:14] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:17] Building go targets for linux/amd64:
    cmd/libs/go2idl/openapi-gen
make[1]: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
+++ [1215 15:41:26] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:26] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:29] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
make: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Detected host and ready to start services.  Doing some housekeeping first...
Using GO_OUT /usr/local/google/home//go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64
Starting services now!
Starting etcd
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.XV5AbQKB0n --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
+++ [1215 15:42:46] On try 2, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
Waiting for apiserver to come up
!!! [1215 15:42:56] Timed out waiting for apiserver:  to answer at https://localhost:6443/version; tried 10 waiting 1 between each
Cleaning up...
```

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #38847 (for real)

### CODE REVIEW

**Comment by saad-ali** [comment]
Worth adding a release note?

**Comment by janetkuo** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
