### PR TITLE
Move post processing/backward compatibility of openapi out of generic package

### PR DESCRIPTION
**Pull request by mbohlool**
Post processing step was put into generic package and was the same for both k8s api server and federation api server. They have different backward compatibility list of types. This PR move that step out of generic package and put it in each server's file.

### CODE REVIEW

**Comment by deads2k** [comment]
Not super happy with the location, I'd put them in their own files, but this gets the package dependencies right and we need that.

**Comment by mbohlool** [comment]
@deads2k I wanted to put them in their own file, but nothing came to my mind for naming those files other than openapi and I have enough of those around :) I didn't spend more than a moment on it though because I think fixing the dependency was more important.

**Pull request merged**
