### PR TITLE
Update godoc to match

### PR DESCRIPTION
**Pull request by MHBauer**
**What this PR does / why we need it**:
comments don't match the code. I can also just remove them.

**Which issue this PR fixes**
golint if it was run, but it is nice to have comments that appear to be relevant to the code.

**Special notes for your reviewer**:
docs only

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42016#-:-KdhDLs0E6S2ZhsQmOJu:bb6ywmx)*

**Comment by MHBauer** [comment]
From what I understand about the purpose of non-nil maps (avoiding nil deref), perhaps the text should be edited to say they are factory functions to generate the aforementioned classes with sane defaults.

**Comment by mikedanese** [comment]
approving trivial docs change.

**Comment by cblecker** [comment]
@k8s-bot kops aws e2e test this (https://github.com/kubernetes/kubernetes/issues/43017#issuecomment-286303401)

**Comment by cblecker** [comment]
@k8s-bot kops aws e2e test this

**Comment by cblecker** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
