### PR TITLE
vendor: update cAdvisor to v0.38.7

### PR DESCRIPTION
**Pull request by gjkim42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR is needed to bump the cAdvisor version to v0.38.7 which fixes an issue that the kubelet cannot start on BtrfS

cadvisor PR: https://github.com/google/cadvisor/pull/2752

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/94335

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug that the kubelet cannot start on BtrfS.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
This is missing the vendored changes.

The general process to vendor is following, I'm guessing you also need to run `hack/update-vendor.sh`

```
$ hack/pin-dependency.sh github.com/google/cadvisor ${NEW-CADVISOR_VERSION_TAG}
$ hack/update-vendor.sh
$ hack/lint-dependencies.sh # should come back empty, if not run hack/pin-dependency.sh for each listed dep and re-vendor
$ hack/verify-vendor.sh
```

**Comment by gjkim42** [comment]
fixed the vendored changes!

**Comment by ehashman** [comment]
Hi @gjkim42,

This PR is currently targeted at release-1.20 without first bumping the dependency in the master branch, which is backwards. 

First, please open a PR to bump the version of cadvisor on master. Then you can backport that change to release-1.20. We don't want the branches getting out of sync.

#98015 needed to bump the version just slightly and is far behind the development HEAD which is why I marked that one ok-to-test, although I'm not sure what our policy is right now for bumping deps in patch releases.

**Comment by gjkim42** [comment]
opend the PR on master

**Comment by bobbypage** [comment]
Thanks @ehashman, agree we should get fix in master first. For context we've bumped deps in patch release semi-frequently for cAdvisor bug fixes that affect kubelet, e.g. see #97176 as recent example

**Comment by gjkim42** [comment]
Maybe flake https://github.com/kubernetes/kubernetes/issues/98039
/retest

**Comment by gjkim42** [comment]
@tosi3k
https://github.com/kubernetes/test-infra/pull/20476 merged
/retest

**Comment by tosi3k** [comment]
Yup, I ran it after the merge but apparently it needed a few more minutes to soak in ;). Some other PRs I retested passed already.

**Review by ehashman — APPROVED** [review]
/lgtm

thanks for submitting the master PR!

**Comment by bobbypage** [comment]
/lgtm
/assign @dims for deps approval

(This is a cherrypick of https://github.com/kubernetes/kubernetes/pull/98042 to `release-1.20`)

**Comment by gjkim42** [comment]
cc: @kubernetes/release-managers for cherry-pick review

**Comment by gjkim42** [comment]
cc: [@kubernetes/release-managers](https://github.com/orgs/kubernetes/teams/release-managers), [@kubernetes/release-engineering](https://github.com/orgs/kubernetes/teams/release-engineering) for cherry-pick review

**Comment by gjkim42** [comment]
For the cherry-pick review
/cc @hasheddan @justaugustus

**Comment by ehashman** [comment]
@gjkim42 RT usually does one pass per week for cherry-picked, but let me just make sure it has All The Labels

/triage accepted
/priority important-soon

**Review by hasheddan — APPROVED** [review]
/lgtm

Waiting for deps approval on 1.19 variant https://github.com/kubernetes/kubernetes/pull/98015 then we can get these in :+1:

**Pull request merged**
