### PR TITLE
e2e: Add test to pd that disk contents are preserved

### PR DESCRIPTION
**Pull request by justinsb**
Issue #11012 reported that disk contents may be lost (sometimes).

We should have an e2e test to verify this is not happening.

(If it is happening, we should then fix it!)

### CODE REVIEW

**Comment by justinsb** [comment]
Doing a WIP PR to get results from GCE while I concurrently test with AWS

**Comment by thockin** [comment]
thanks!  Much needed

**Comment by justinsb** [comment]
Tweaked to change the image to busybox so we get /bin/sh, and I think this will pass on AWS now.  (Worked when I ran the test directly using hack/e2e.go, and now trying a full-run).   However, because GCE e2e passed before, I don't think GCE e2e is actually running this test, perhaps the Github runner doesn't but the full test suite does though (?)

I'm going to try running directly on GCE.

The good news (I guess) is that this didn't immediately show a problem, so hopefully #11012 is caused by something else.

**Comment by justinsb** [comment]
@k8s-bot test this please

(seemingly unrelated failure in `should serve a basic endpoint from pods`)

**Comment by justinsb** [comment]
No longer WIP;  passes for me on AWS & GCE (when run directly for GCE).  I'm not sure why this test is skipped on GCE (if it indeed is); it seems fairly important that this work reliably!  Maybe whatever flake it is that causes us to skip it on GCE is in fact the scenario which causes data loss in #11012 (I've asked for clarification there in the hope of getting a clue as to what could be going wrong).

In terms of merging: Low risk, because only e2e tests, and I think it is important to test this, but given that it hasn't (yet) shown a problem I don't think there's any urgency in merging this pre v1.  I'm going to keep it on my integration branch anyway for AWS.

**Comment by thockin** [comment]
Saad, do you have time for this one?  Not critical for 1.0 (test only)

**Comment by saad-ali** [comment]
Yep, I'll take a look.

**Comment by saad-ali** [comment]
LGTM Thanks @justinsb!

**Pull request merged**
