### PR TITLE
Increase etcd test server up timeout and disallow returning nil server 

### LINKED ISSUE #25047: Integration test failure: deployment/etcd
[test artifacts](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24804/kubernetes-pull-test-unit-integration/23757/)

>
FAIL	k8s.io/kubernetes/pkg/registry/deployment/etcd	15.668s

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #25047

[Analytics]()

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot node e2e test this issue: #26385

**Comment by janetkuo** [comment]
@k8s-bot test this issue: #26385

**Comment by kargakis** [comment]
cc: @wojtek-t

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by lavalamp** [comment]
Thanks!

**Comment by wojtek-t** [comment]
Thanks @janetkuo - we will see if that helps, but it's definitely useful.

**Pull request merged**
