### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by mikedanese**
fixes #61817
fixes #62360
```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
I expect this isn't going to work as is.

**Comment by mikedanese** [comment]
no OWNERS in pkg/generated...

**Comment by yujuhong** [comment]
Uh....sorry for breaking it and thanks for fixing the godep issue.

**Comment by mikedanese** [comment]
bazel is having networking issues, I saw a "failed to lookup host" and now:
```
 WARNING: Some artifacts failed be downloaded from the remote cache: Connection reset by peer
```

**Comment by ixdy** [comment]
@BenTheElder ^

**Comment by BenTheElder** [comment]
>  WARNING: Some artifacts failed be downloaded from the remote cache: Connection reset by peer

This is fine, it's just a warning. Network issues are not just Bazel, in general we have some network issues on the test cluster.

**Comment by BenTheElder** [comment]
Garbage collector tests :(
/retest

**Pull request merged**
