### PR TITLE
Dont throw error if network is already torn down when deleting container

### LINKED ISSUE #40474: Eviction Manager races with Housekeeping loop and evicts extra pods
cc: @kubernetes/sig-node-bugs @derekwaynecarr @vishh 
Investigating [this flake](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/70) revealed that the eviction manager "fails" to evict a pod, and evicts the next pod as well.

It fails with the following error:
`eviction_manager.go:338] eviction manager: pod container-inode-hog-pod_e2e-tests-inode-eviction-test-2gkfm(a8c62e56-e2b7-11e6-9bd7-42010a800012) failed to evict failed to "TeardownNetwork" for "container-inode-hog-pod_e2e-tests-inode-eviction-test-2gkfm" with TeardownNetworkError: "Failed to teardown network for pod \"a8c62e56-e2b7-11e6-9bd7-42010a800012\" using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/1909/ns/net\": no such file or directory"`

I spoke with @freehan, who suggested it may be a race between the eviction manager killing the pod, and another goroutine trying to clean up pods.

I discovered that this had occurred after eviction was initiated, but before it had completed: 
`kubenet_linux.go:743] Removing e2e-tests-inode-eviction-test-2gkfm/container-inode-hog-pod from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:90ea6c21dd048b4764555613e32939185e20351b9e873b18c2ff7183e181b167 NetNS:/proc/1909/ns/net IfName:eth0 Args:[]}`
This indicates that the network was successfully torn down prior to the eviction manager failing to evict.

Just before the above statement, i saw this:
`kubelet_pods.go:877] Killing unwanted pod "container-inode-hog-pod"`
This indicates the pod was sent to the kubelet's kl.podKillingCh.

This must have come from kubelet_pods.go:HandlePodCleanups(), as it is the only place where pods are placed in that channel.
HandlePodCleanups is part of the syncloop.

**TL;DR, The garbage collection of pods through HandlePodCleaups in the syncloop is racing with the eviction manager's attempts to kill a pod, and causing it to fail and evict the next pod as well.**

I see a couple possible solutions:

- Killing a pod should not fail if parts of the pod (networking, for example) are already deleted.  We would need to handle errors related to this properly.
- Limit calls to containerRuntime.KillPod() to a single goroutine to prevent concurrent deletions.  However, this could increase latency for eviction because it would involve a queue or locks.
- Modify the eviction manager to not immediately evict the next pod, but rather keep track of pods that it has "failed" to evict, and wait until the next synchronize to evict the next pod (assuming pressure still exists).

I personally prefer the first solution, but it may be difficult to enumerate all of the errors that can occur due to trying to kill a dead pod.
Thoughts?

### PR DESCRIPTION
**Pull request by dashpole**
Fixes #40474.  @kubernetes/sig-node-pr-reviews

### CODE REVIEW

**Comment by freehan** [comment]
Actually, I am also fixing this in another PR. https://github.com/kubernetes/kubernetes/pull/39903

**Comment by dashpole** [comment]
Oh, cool.  @freehan should I close this one then?

**Comment by freehan** [comment]
see https://github.com/kubernetes/kubernetes/pull/39903/files#diff-4df925f5ace9ef618b2650b1d3f740c1

**Comment by freehan** [comment]
yeah please

**Comment by dashpole** [comment]
Closed via #39903

**Pull request closed without merging**
