### PR TITLE
[Do Not Merge] Add evict subresource for pod

### PR DESCRIPTION
**Pull request by jiangyaoguo**
#24321
This pr only implement `DELETE /pods/xxx/evict` api call, not including internal logic. Just for reference. 
`curl -X DELETE  http://master/api/v1/namespaces/default/pods/xxx/evict`  will delete pod xxx.

@mml @davidopp

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24460)

### CODE REVIEW

**Comment by jiangyaoguo** [comment]
@HaiyangDING @hurf

**Comment by lavalamp** [comment]
@mml Did we settle on a subresource? I thought we had talked about just adding options? I can't remember now.

**Comment by mml** [comment]
@lavalamp adding options doesn't work if we want this to fail when you try to do the operation on an api server that doesn't support it.  I believe that's something we desire, so it needs to be a subresource.

**Comment by lavalamp** [comment]
Ah right, of course.

**Comment by davidopp** [comment]
I'm going to close this since @mml has taken it over.

**Pull request closed without merging**
