### PR TITLE
Update Kind details for DRA e2e

### LINKED ISSUE #118616: DRA: Running e2e tests with king for Dynamic Resource Allocation locally fails with latest Kind 0.19 release
### What happened?

`Kind` uses containerd for worker nodes by default, and latest release of [kind 0.19](https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0) uses by default base-image with containerd 1.6 for worker node. Unfortunately, CDI was merged into containerd 1.7, and CI at the moment uses `kind` binary from unreleased build 0.20-alpha. So running e2e tests locally for [Dynamic Resource Allocation](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/dra) is failing unless when building node image a parameter is used with base-image that has 1.7 containerd. The need  needs to be mentioned in DRA e2e README.md.

### What did you expect to happen?

Dynamic Resource Allocation e2e work locally when running them according to the instruction.

### How can we reproduce it (as minimally and precisely as possible)?

Run DRA e2e with kind 0.19.

### Anything else we need to know?

The fix is coming shortly.

### Kubernetes version

1.27, 1.28-alpha

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by byako**
CI uses unreleased binary of [Kind](https://github.com/kubernetes-sigs/kind) from main branch to have Containerd 1.7 in e2e tests, This PR fixes documentation for Dynamic Resource Allocation e2e tests to reflect the need of newer base-images for older versions of Kind, and replaces the outdated / obsolete script that was version agnostic with the one-line build instruction in the documentation.

/sig NODE

#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:
Fixes #118616

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by BenTheElder** [comment]
There will probably be a kind release later this week with various cgroups fixes to go with the patch releases scheduled on 2023-06-14.

It might make more sense to just recommend staying on the latest sources for developing k8s @ HEAD or else v0.20

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by pohly — APPROVED** [review]
/approve

**Pull request merged**
