### PR TITLE
Cleanup borrowed conversion functions.

### PR DESCRIPTION
**Pull request by erictune**
In pkg/apis/extensions/v1beta1/conversion.go,
some conversion code was copied from the
legacy api because Pod conversions cannot be
automatically generated because of something
about deprecatedServiceAccount.

This PR fixes two problems due to that copying.

First, the copied code could drift from its source
To fix that, I replaced the Convert_api_ and Convert_v1
implementations with a call to the original function.
I left a wrapper in case something needed to have
a package-local function name.

Second, the copied Convert_\* functions, were copied,
in a way that they refer to other conversion functions
that aren't in the current package.  This prevented
genconverion from working from a clean start
(no conversion_generated.go).  Perhaps the person
who wrote this in the first place had copied
the conversion_generated.go file from legacy,
so it worked.   So, I added the v1
package name to calls to Convert_\* functions.
So, when someone Cargo-Cult copies the conversion.go
file, like I did, they now will not have to
wonder why genconversion complains about missing
Convert_ functions.

Deleted the conversion_generated.go and reran genconversion
and it worked, no diffs old vs new conversion_generated.go.

### CODE REVIEW

**Comment by erictune** [comment]
Fixes #12977

**Comment by erictune** [comment]
@soltysh @nikhiljindal since you were on #12977 you would be good reviewers.

**Comment by erictune** [comment]
@lavalamp this is the issue we just hit IRL.

**Comment by lavalamp** [comment]
This looks good. Copying that code was a maintenance problem anyway, I don't think many of us would have realized we needed to fix that in multiple places. @wojtek-t may also be interested.

**Comment by lavalamp** [comment]
The local functions are needed so that the conversion generator will find them.

In theory you could do `var Convert_x_y = v1.Convert_x_y`, but I'm not sure the converter is smart enough to find that.

**Comment by erictune** [comment]
That was my intuition.

**Comment by nikhiljindal** [comment]
Thanks for fixing this!

**Comment by erictune** [comment]
@k8s-bot please e2e test this

**Pull request merged**
