### PR TITLE
Automated cherry pick of #50470

### PR DESCRIPTION
**Pull request by nicksardo**
Cherry pick of #50470 on release-1.7.

#50470: GCE: Specify alpha in annotation key, deprecate lower case of
**Release note**:
```release-note
GCE: Internal load balancer is enabled with annotation value "Internal" instead of "internal".
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Maybe worth to point out the new annotation key (`alpha.cloud.google.com/load-balancer-backend-share`) in release note as well?

**Comment by nicksardo** [comment]
The annotation is purposely not documented anywhere. It's an experiment that will probably not survive a couple of releases.

**Pull request merged**
