### PR TITLE
removing -z option to curl, it was leaving an empty file

### LINKED ISSUE #8094: download of kube-register producing empty file
https://github.com/kelseyhightower/kube-register/issues/19

### PR DESCRIPTION
**Pull request by rljohnsn**
fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/8094

### CODE REVIEW

**Comment by nikhiljindal** [comment]
It was added a few days ago in https://github.com/GoogleCloudPlatform/kubernetes/pull/7887
@elsonrodriguez @brendandburns

**Comment by brendandburns** [comment]
Hrm, in theory that is supposed to ensure that we don't overwrite a newer file with an older file.  To be honest, I'd rather that we had explicit versions, but @kelseyhightower would need to support that in the kube-register project.

Were you trying to overwrite a newer version of the binary?

**Comment by rljohnsn** [comment]
@brendanburns Nope found it doing that when I started debugging register service errors after first clean install. Even after fixing the file manually successive runs would empty the file again.

**Comment by brendandburns** [comment]
Ok, that's odd.  I will try to repro myself and merge if I see problems too.

**Comment by elsonrodriguez** [comment]
This is caused by a bug in curl 7.42.0

https://github.com/bagder/curl/issues/237

I've filed a bug with CoreOS to update their curl version (https://github.com/coreos/bugs/issues/367), but this does in fact break the walkthrough.

Options are to take the pull request or wait for CoreOS.

**Comment by elsonrodriguez** [comment]
CoreOS updated curl.

I don't know when that makes it into Core though.

**Comment by brendandburns** [comment]
This was merged into CoreOS (https://github.com/coreos/portage-stable/pull/198), I'm going to close this bug, I'd prefer to see it fixed in Coreos.

**Pull request closed without merging**
