### PR TITLE
WIP: RFC2: Remove restriction on probes successThreshold

### PR DESCRIPTION
**Pull request by thockin**
Building on #106025 to see if I can de-share the Probe type

### CODE REVIEW

**Comment by thockin** [comment]
I know this won't pass tests, but I did "enough" conversion to hopefgull show how it would look

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by thockin** [comment]
As much as I prefer this approach to #106025, it's a breaking change and without a v2 pod, we can't do it.

**Pull request closed without merging**
