### PR TITLE
RFC: Let the default scheduler be ResourceVersion aware

### PR DESCRIPTION
**Pull request by mitake**
**What this PR does / why we need it**:

Currently the default scheduler doesn't care about version number of nodes in its scheduling. IIUC, if a scheduler doesn't care about it, other schedulers cannot detect the update of resource usages and the quality of their scheduling decision would be degraded.

This commit lets the default scheduler specify their assumed `ObjectMeta.ResourceVersion` of the target nodes. According to [this article](https://research.google.com/pubs/pub44843.html), the field is intended to be used for OCC between schedulers.

**Special notes for your reviewer**:
This PR is not ready to be reviewed seriously: related test cases aren't updated and the abort path for OCC in the default scheduler isn't implemented yet. I want to know this idea is acceptable or not. If I can have your comments about the idea, it is great.

### CODE REVIEW

**Comment by bsalamat** [comment]
@mitake I am not sure if we need this PR. Default scheduler has an event handler for node updates which is invoked when there is any updates to the node objects. Scheduler updates its cached information about the node upon receiving such events. Other scheduler are also expected to have a similar mechanism. Have you run into any issue that node updates are not reflected properly?

**Comment by mitake** [comment]
@bsalamat thanks a lot for your comments. I'm still not seeing serious problems related to it. However, if the `Bind()` call of the default scheduler doesn't specify `ResourceVersion`, the binding can be processed successfully even the scheduling decision was made on an obsolete cluster state. Even the binding request can be issued direct after of the refreshing, other schedulers have a chance for updating the state.

Of course this gap can be solved after the scheduling by moving pods after refreshing the cached information. Or the gap can be accepted if it is small enough. I just thought if the binding based on the obsolete state can be failed, predicting behaviour of schedulers would be a little bit easier (of course I would be missing something).

**Comment by bsalamat** [comment]
In case of multiple scheduler or sudden changes in the amount of allocatable resources of nodes, there would be a race condition and scheduler could possibly make incorrect decision based on stale data, but that's fine because if the chosen node does not have the resources that the pod requires, kubelet of the node will reject the binding.

**Comment by mitake** [comment]
@bsalamat if the conflicting scheduling can be failed, it is fine as you say. But I'm caring about situation like this: two schedulers (say `s1` and `s2`) are trying to bind one of their pods (say `p1` and `p2`) and they have two nodes suitable for it (say `n1` and `n2`). `n1` and `n2` are not executing any pods so both of them are identical as a candidate. If both `s1` and `s2` select `n1` for the node of `p1` and `p2`, `n2` will be under utilized and the parallelism of `p1` and `p2` will be sacrificed. If one of the `Bind()`s from `s1` or `s2` can be failed and either of them retries, `n2` can be selected.

I thought it is helpful for capacity planning because admins can have an assumption that the under utilized nodes by the scheduling conflicts won't happen thanks to the OCC. Of course typical deployments would have only one default scheduler, so it can be implemented as an optional mechanism. Or is this unacceptable at all?

**Comment by k82cn** [comment]
I think pod info will be updated instead of node info when scheduler calls `Bind()`. Both kubelet and NodeController will update `Node`, so I think we can not account on `ResourceVersion` of Node :).

**Comment by mitake** [comment]
OK. Anyway I'm not seeing real problems related to concurrency control between multiple schedulers. I'm closing this for now.

**Pull request closed without merging**
