### PR TITLE
feat(scheduler): graduate ScheduleDaemonSetPods to GA

### LINKED ISSUE #82702: Graduate ScheduleDaemonSet to GA
/sig scheduling
/cc @k82cn @ahg-g
/assign

This feature has been in Beta since 1.12, we can now graduate it to GA in 1.17.

- [x] KEP for graduating schedule daemonset pods https://github.com/kubernetes/enhancements/pull/1299
- [x] Performance concern before the graduation of ScheduleDaemonSetPods #83829
- [x] Graduate ScheduleDaemonSetPods to GA #82795
- [x] Remove suspenedDaemonPods which handles Pod deleted on the nodes. https://github.com/kubernetes/kubernetes/pull/84323
- [x] Refactor nodeShouldRunDaemonPod to remove useless return values
- [x] Update the feature state in the documentation https://github.com/kubernetes/website/pull/17350

+ https://github.com/kubernetes/enhancements/issues/548

### PR DESCRIPTION
**Pull request by draveness**
/sig scheduling
/sig apps
/priority important-soon
/kind feature

**What this PR does / why we need it**:

Graduate ScheduleDaemonSetPods to GA

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/82702

**Does this PR introduce a user-facing change?**:

```release-note
Graduate ScheduleDaemonSetPods to GA. (feature gate will be removed in 1.18) action required.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by k82cn** [comment]
@draveness , that'll be great to list what we're going to do for graduating ScheduleDaemonSetPods to GA, e.g. removing `suspendedDaemonPods` in DS controller.

**Comment by draveness** [comment]
> @draveness , that'll be great to list what we're going to do for graduating ScheduleDaemonSetPods to GA, e.g. removing `suspendedDaemonPods` in DS controller.

Could you elaborate on that? This PR just removes the feature gate from the codebase and bumps the stage and lock it to default.

**Comment by k82cn** [comment]
> Could you elaborate on that? This PR just removes the feature gate from the codebase and bumps the stage and lock it to default.

I would suggest to check history of this features; for example, we use to add `suspendedDaemonPods` to handle Pod deleted on the nodes. We do not need to handle all of them in this PRs, but it's better to list sub-tasks in #82702 .

**Comment by draveness** [comment]
> > Could you elaborate on that? This PR just removes the feature gate from the codebase and bumps the stage and lock it to default.
> 
> I would suggest to check history of this features; for example, we use to add `suspendedDaemonPods` to handle Pod deleted on the nodes. We do not need to handle all of them in this PRs, but it's better to list sub-tasks in #82702 .

Thanks for the input, I'll check the history.

**Comment by draveness** [comment]
Hi @k82cn, can you help to review this PR? thanks

**Comment by liggitt** [comment]
can you elaborate on the concern in https://github.com/kubernetes/kubernetes/issues/83829?

**Comment by liggitt** [comment]
/lgtm
/approve

needs rebase

**Comment by draveness** [comment]
/retest

pull-kubernetes-node-e2e-containerd is flaky.

**Comment by liggitt** [comment]
as a follow-up, the daemonset controller dependency on scheduler packages (except maybe the scheduler/api package) should be able to be removed now (so that controllers don't depend on scheduler internal packages as is being added in https://github.com/kubernetes/kubernetes/pull/84193)

**Comment by draveness** [comment]
These tests are failing, and they don't look relevant. https://github.com/kubernetes/kubernetes/pull/84011 has the same failing tests.

**Comment by ahg-g** [comment]
> as a follow-up, the daemonset controller dependency on scheduler packages (except maybe the scheduler/api package) should be able to be removed now (so that controllers don't depend on scheduler internal packages as is being added in #84193)

It will still depend on the scheduler: https://github.com/kubernetes/kubernetes/pull/82795/files#diff-3af9d435092399b4bf3ef61e0387eb36R1404

**Pull request merged**
