### PR TITLE
fix staticcheck:pkg/volume/cinder

### PR DESCRIPTION
**Pull request by yuxiaobo96**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:#81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by msau42 — COMMENTED** [review]
These fields are still used. Maybe there's something wrong with the static checker?

**Review by msau42 — COMMENTED** [review]
I am also puzzled how compiling is still working

**Comment by msau42** [comment]
Nevermind, I see, it's duplicated twice in `cinderVolume` and `cinderVolumeMounter`
/lgtm
/approve
/retest

**Comment by yuxiaobo96** [comment]
@msau42 
Thanks for your review.

**Comment by yuxiaobo96** [comment]
/assign @liggitt  for /hack approval.
Thanks.

**Pull request merged**
