### PR TITLE
Fix link to Azure docs

### PR DESCRIPTION
**Pull request by johndmulhausen**
This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24308)

### CODE REVIEW

**Comment by thockin** [comment]
LGTM.  Are we manually merging this repo or do we have a bot up?

**Comment by thockin** [comment]
NM, wrong repo question

**Comment by wojtek-t** [comment]
@thockin - it seems bot doesn't like this PR. We should probably merge it manually if we want it.

**Comment by thockin** [comment]
@johndmulhausen is it your intent to change this in the old repo?

**Comment by wojtek-t** [comment]
ping - do we want to do something with this PR?
If not - can we close it?

**Comment by brendandburns** [comment]
I think we can close this due to old docs?  @johndmulhausen re-open if that's wrong.

**Pull request closed without merging**
