### PR TITLE
convert Duration into seconds by go library function

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
Here we try convert time.Duration  into int64 seconds. I think it's better to use golang library function,
https://golang.org/pkg/time/#Duration.Round

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@deads2k PTAL

**Comment by WanLinghao** [comment]
@soltysh PTAL

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
