### PR TITLE
remove azure load balancer workaround, upgrade azure sdk to bugfixed version

### LINKED ISSUE #40332: azure: loadbalancers are broken in 1.5.2
**Kubernetes version** (use `kubectl version`): `v1.5.2`

**Environment**:
- **Cloud provider or hardware configuration**: Azure / Azure Container Service
- **OS** (e.g. from /etc/os-release): Xenial
- **Kernel** (e.g. `uname -a`): latest lts
- **Install tools**: kubelet + static manifests
- **Others**: n/a

**What happened**:
I created a Service (type=LoadBalancer). The load balancer did not complete provisioning and security group was not updated, so the LB that is there doesn't work.

**What you expected to happen**:
Azure load balancer is created, external IP field is populated (doesn't show as "Pending")

**How to reproduce it** (as minimally and precisely as possible):
Try it.

**Anything else do we need to know**:
No.

There is an issue opened against the repo that caused this problem: https://github.com/Azure/go-autorest/issues/112

This was reported here: https://github.com/Azure/acs-engine/issues/194#issuecomment-274472969

CC: @codablock @brendandburns

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**:

* Reverts the (workaround) commit from this PR: #40405 (cc: @codablock)
* Bump `github.com/Azure/{go-autorest,azure-sdk-for-go}` in Godeps
* Updates `vendor/` per the Godeps bump to a release that does not contain the strict readonly constraint

**Which issue this PR fixes**: fixes #40332

**Special notes for your reviewer**: n/a

**Release note**:

```release-note
Fix failing load balancers in Azure (proper fix, remove workaround)
```

I've tested the load balancer, routes and ACR integration after this change.

This build is on Docker Hub pre-built as well: `docker.io/colemickens/hyperkube-amd64:cmpr-bump-azure-deps`

cc: @codablock @brendandburns

### CODE REVIEW

**Comment by colemickens** [comment]
@k8s-bot unit test this

**Comment by colemickens** [comment]
(the last bot comment is wrong, the last unit test run finished successfully)

**Comment by colemickens** [comment]
ping @lavalamp for review

ping @brendandburns for approval

**Comment by colemickens** [comment]
ping @lavalamp for review

ping @brendandburns for approval

Note, this fixes another regression that exists in 1.5.3 around folks who have a subnet and routetable but do not have them configured correctly. It would be great if this were merged so I can get it cherry-picked for 1.5.4. Thanks!

**Comment by edevil** [comment]
So what is the current status of Kubernetes on Azure?

I have a 1.5.1 cluster that's running fine, but was thinking of upgrading to 1.5.4 because it solves #41641. However, it seems there is still some regression in 1.5.3/1.5.4: "folks who have a subnet and routetable but do not have them configured correctly". Can you give some details of this bug to see if I'm affected? @colemickens 

Thanks.

**Comment by colemickens** [comment]
In `1.5.4`, since this wasn't merged, users must ensure the routetable is set on the subnet correctly. If not, the route creation will fail whenever it tries to add teh routetable to the subnet due to the verification checks in the SDK.

This should be merged to potentially fix in 1.5.5, but I can't get any attention on it, and it will go away in 1.6 (2-3 weeks) because that code has been removed.

**Comment by lavalamp** [comment]
/lgtm
/approve

sorry for delay

**Comment by colemickens** [comment]
This should just be abandoned. Plus I hear rumor of someone else updating them.

**Pull request closed without merging**
