### PR TITLE
Recover pod worker manage loop from crash

### PR DESCRIPTION
**Pull request by uzuku**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When worker loop breaks unexpectly (like panic), HandleCrash catches it and handles it gracefully,
and the worker exits silently without cleaning up the entry in podUpdates,
which causes updates of the pod cannot be processed anymore.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Thanks for your pr @uzuku !

I'm wondering, how difficult would it be for you to provide automated testing (preferably unit) which demonstrates how this change protects against the error conditions you discussed? I think such testing could help reviewers visualize and fully understand the ramifications of the proposed change.

**Comment by uzuku** [comment]
> /ok-to-test
> 
> Thanks for your pr @uzuku !
> 
> I'm wondering, how difficult would it be for you to provide automated testing (preferably unit) which demonstrates how this change protects against the error conditions you discussed? I think such testing could help reviewers visualize and fully understand the ramifications of the proposed change.

Yeah i've written a unit test case to cover it, and with the test it seems my original fix does't work...
 I'll try to figure it out.

**Comment by uzuku** [comment]
@mattjmcnaughton I've updated the fix and added a unit test for it, PTAL. Thanks!

**Review by mattjmcnaughton — COMMENTED** [review]
Thank you for the test case @uzuku!

I'd love another member of sig-node to serve as the main reviewer here... I'm afraid I don't have a ton of understanding around the failure cases to which you're referring, nor the ramifications of such failures occurring.

Lmk if you don't hear from any other sig-node members in the next week or so and I can try and help you ping someone :) With KubeCon, the 1.17 release, and Thanksgiving for folks in the US, its a busy time, so just a heads up that it might take a little while longer than normal. Thanks for your patience.

**Comment by uzuku** [comment]
@mattjmcnaughton Oh I see, thanks for your kind tip!
I'll keep an eye on this.

**Pull request closed without merging**
