### PR TITLE
Bumped Heapster to v0.18.5 to fix issue with nil pointer panic

### LINKED ISSUE #19986: Reboot tests fail for kubernetes-e2e-gke-ci-reboot (node doesn't come back after reboot)
```
Reboot [Disruptive] each node by triggering kernel panic and ensure they function upon restart

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:102 Jan 22 00:17:06.634: Test failed; at least one node failed to reboot in the time given.


Reboot [Disruptive] each node by ordering unclean reboot and ensure they function upon restart

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:96 Jan 22 00:24:12.487: Test failed; at least one node failed to reboot in the time given.
```

### PR DESCRIPTION
**Pull request by piosz**
Should fix #19986, #19896 and possibly other issues where crash-looping Heapster is the root cause.

should be cherry-picked to release-1.1

cc @dchen1107 @mwielgus @vishh @yujuhong

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by zmerlynn** [comment]
LGTM as well. @k8s-oncall: please merge on green

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by zmerlynn** [comment]
(though I'm sure irrelevant)

**Comment by zmerlynn** [comment]
I'm merging this without unit/integration finishing just so we can see if it'll get gke-ci back by EOD

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/20108 is going to printout the heapster container log, and hope that tell us more why heapster in bad state if current pr doesn't help.

**Comment by roberthbailey** [comment]
@piosz / @zmerlynn - Any reason we didn't create a cherry pick PR for this 29 days ago when it was merged to master? It just missed the 1.1.8 tag because @vishh sent the cherry pick PR this morning. :/

**Comment by piosz** [comment]
Apologies for that. I don't know how but I missed it:(

**Pull request merged**
