### PR TITLE
[Federation] Make federation namespace e2e tests parallelizable.

### PR DESCRIPTION
**Pull request by madhusudancs**
Because deleteAllTestNamespaces deleted all the e2e namespaces it interefered with other federation namespace tests running in parallel. This change should mitigate the problem and make the tests runnable in parallel.

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/federated-namespace.go, line 210 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41241#-KcbnOkWg_2XIxq5dJ_z:-KcbnOkWg_2XIxq5dJa-:b-kyjz71) ([raw file](https://github.com/kubernetes/kubernetes/blob/c29e0753ace13b835f3db6429c6b5cc4d04bb604/test/e2e_federation/federated-namespace.go#L210)):*
> ```Go
> 			return false, err
> 		}
> 		return true, nil
> ```

I think, we might prematurely exit polling, if err == nil returned by getter, and the namespace might be still out there. i think we should explicitly wait for errors.IsNotFound to confirm namespace is deleted.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41241)*

**Comment by madhusudancs** [comment]
@shashidharatd addressed your comment. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/federated-namespace.go, line 210 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41241#-KcbnOkWg_2XIxq5dJ_z:-KcdbhqjnimunulqBTjO:b-t3wy0d) ([raw file](https://github.com/kubernetes/kubernetes/blob/c29e0753ace13b835f3db6429c6b5cc4d04bb604/test/e2e_federation/federated-namespace.go#L210)):*
<details><summary><i>Previously, shashidharatd (Shashidhara T D) wrote…</i></summary><blockquote>

I think, we might prematurely exit polling, if err == nil returned by getter, and the namespace might be still out there. i think we should explicitly wait for errors.IsNotFound to confirm namespace is deleted.
</blockquote></details>

Oops, you are right. I did this above in `deleteNamespace()` and forgot to do the same here.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41241#-:-KcdcKWZGQ8KKSyRdHSb:b-w49am1)*

**Comment by shashidharatd** [comment]
Thanks @madhusudancs, the changes LGTM.
/lgtm

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41241#-:-KcefQqoc8Zi_m0OfOuC:b-5ketlp)*

**Pull request merged**
