### PR TITLE
Update aws-sdk-go to v1.0.x

### PR DESCRIPTION
**Pull request by tpounds**
Updates AWS cloud provider to use the v1.0.x release which is now officially supported for production use.

see: https://aws.amazon.com/blogs/aws/now-available-version-1-0-of-the-aws-sdk-for-go/

### CODE REVIEW

**Comment by tpounds** [comment]
cc @justinsb

**Comment by quinton-hoole** [comment]
ok to test

**Comment by quinton-hoole** [comment]
LGTM.  @justinsb FYI

**Comment by quinton-hoole** [comment]
LGTM

**Comment by wojtek-t** [comment]
@tpounds 

hack/verify-godeps.sh fails for you PR

Can you please fix that?

**Comment by tpounds** [comment]
@wojtek-t, looks like I missed part of the go-jmespath dependency. Should be fixed now.

**Comment by quinton-hoole** [comment]
LGTM.  @justinsb FYI.

**Comment by quinton-hoole** [comment]
@tpounds Still a few minor things to sort out.
```
godep: error restoring dep (github.com/google/btree): found packages btree.go (btree) and btree_mem.go (main) in /tmp/gopath.qu4017/src/github.com/google/btree
godep: error restoring dep (github.com/miekg/dns): found packages client.go (dns) and types_generate.go (main) in /tmp/gopath.qu4017/src/github.com/miekg/dns
godep: error restoring dep (golang.org/x/tools/imports): found packages fix.go (imports) and mkindex.go (main) in /tmp/gopath.qu4017/src/golang.org/x/tools/imports
!!! Error in hack/verify-godeps.sh:65
  '"${GODEP}" restore' exited with status 1
Call stack:
  1: hack/verify-godeps.sh:65 main(...)
Exiting with status 1
Removing /tmp/gopath.qu4017
make: *** [verify] Error 1
The command "make verify BRANCH=$TRAVIS_BRANCH" exited with 2.
Done. Your build exited with 1.
```

**Comment by tpounds** [comment]
@quinton-hoole I've rebased my branch again but It's not obvious to me how to get my branch to build cleanly with the verify-godeps.sh script. Is there a trick to getting my local build to reliable reproduce the  Travis CI failures?

**Comment by tpounds** [comment]
@quinton-hoole AFAICT, the issue was related to a godep behavior change which was resolved by pining the version in #18671.

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
@k8s-bot test this

**Comment by quinton-hoole** [comment]
@tpounds This needs a rebase, then it should be good to merge.

**Comment by tpounds** [comment]
@quinton-hoole I've rebased again.

**Comment by quinton-hoole** [comment]
The unit test failure looks like a flake, unrelated to this PR. Rerunning...

```
FAIL	k8s.io/kubernetes/pkg/registry/generic/etcd	3.236s
```

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this

**Comment by justinsb** [comment]
(I just wanted to say thank you @tpounds for persisting with this!)

**Comment by tpounds** [comment]
@justinsb No problem!

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this

**Comment by quinton-hoole** [comment]
Same old unit test flakes, being tracked elsewhere.  Try again.

@k8s-bot unit test this

```
==================
WARNING: DATA RACE
Write by goroutine 72:
  sync.raceWrite()
      /tmp/workdir/go/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
  net/http/httptest.(*Server).Close()
      /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
  k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).Terminate()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:151 +0x138
  k8s.io/kubernetes/pkg/registry/generic/etcd.TestEtcdDeleteCollectionWithWatch()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd_test.go:558 +0x97a
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous read by goroutine 74:
  sync.raceRead()
      /tmp/workdir/go/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 72 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/registry/generic/etcd/_test/_testmain.go:72 +0x20f

Goroutine 74 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
--- PASS: TestEtcdDeleteCollectionWithWatch (0.17s)
=== RUN   TestEtcdWatch
==================
WARNING: DATA RACE
Write by goroutine 53:
  sync.raceWrite()
      /tmp/workdir/go/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
  net/http/httptest.(*Server).Close()
      /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
  k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).Terminate()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:151 +0x138
  k8s.io/kubernetes/pkg/registry/generic/etcd.TestEtcdWatch()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd_test.go:612 +0xb5f
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous read by goroutine 114:
  sync.raceRead()
      /tmp/workdir/go/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 53 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/registry/generic/etcd/_test/_testmain.go:72 +0x20f

Goroutine 114 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
--- PASS: TestEtcdWatch (0.32s)
PASS
Found 2 data race(s)
FAIL	k8s.io/kubernetes/pkg/registry/generic/etcd	3.080s
```

**Comment by tpounds** [comment]
@quinton-hoole I've rebased again to pick up flake test fixes.

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this

**Comment by quinton-hoole** [comment]
Good gracious, this is like giving birth to barbed wire. 
The e2e test that failed is clearly flaky, as it's failed 2 out of 7 of it's most recent runs. 
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22451/testReport/junit/(root)/Kubernetes%20e2e%20suite/Deployment_deployment_should_support_rollover/history/
Besides that, all of the changes in this PR are not exercised by any of our e2e tests which run on GCE, not AWS.  I'm going to merge this PR manually before it drives us all mad.

**Comment by therc** [comment]
So how do we get 1.0.7 now? :-) I tried, but I'm stuck in godep hell (camlistore has recently deleted pkg/errorutil and godep doesn't fetch the version that was pinned in Godeps.json).

**Comment by tpounds** [comment]
@therc Do you have an open PR to upgrade the SDK to v1.0.7? If not, I can take a look a bit later today to see what it will take to upgrade to the latest version.

**Comment by therc** [comment]
I *think* I might have figured it ten seconds ago. I'll file a PR in a few hours.

**Comment by therc** [comment]
@tpounds  It's #19351

**Pull request merged**
