### PR TITLE
fix_translation_zh_CN

### PR DESCRIPTION
**Pull request by vonsago**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it:**

fix translation in translations/kubectl/zh_CN/

**Which issue(s) this PR fixes:**

None

**Does this PR introduce a user-facing change?:**

None

### CODE REVIEW

**Comment by nikhita** [comment]
@vonsago Apologies for the late response on this! :bowing_woman: 

/cc @kubernetes/sig-docs-zh-reviews 
/sig cli
/priority important-longterm 
/release-note none

**Review by idealhack — APPROVED** [review]
/lgtm
/ok-to-test

thanks!

**Comment by nikhita** [comment]
/assign @seans3 
for approval

**Comment by idealhack** [comment]
@vonsago this needs a rebase since we can't merge a PR with merge commits

**Comment by vonsago** [comment]
@idealhack Thanks,I have rebase this

**Review by chenrui333 — APPROVED** [review]
/lgtm
/approve

**Comment by idealhack** [comment]
I'm guessing we are missing something here, maybe https://github.com/kubernetes/kubernetes/tree/master/translations can help.

**Comment by vonsago** [comment]
I tried to run `./hack/update-translations.sh` and `./hack/generate-bindata.sh` according to the [document](https://github.com/kubernetes/kubernetes/tree/master/translations), but there are still some checks that can't go.

**Pull request closed without merging**
