### PR TITLE
Wait for cloud-init to finish before starting tests.

### LINKED ISSUE #46889: e2e_node tests on cos-beta-59-9460-20-0 image are failing
e2e_node tests on cos-beta-59-9460-20-0 image use GPUs. To install the NVIDIA drivers, we have to disable loadpin which requires a restart. This results in the runner losing connection with the instance which results in the tests failing/erroring.

One way to fix this is to make sure that cloud-init has finished before starting the tests.

Something like:
```
diff --git a/test/e2e_node/runner/remote/run_remote.go b/test/e2e_node/runner/remote/run_remote.go
index 8a1d38daa9..78a5865c9e 100644
--- a/test/e2e_node/runner/remote/run_remote.go
+++ b/test/e2e_node/runner/remote/run_remote.go
@@ -588,6 +588,13 @@ func createInstance(imageConfig *internalGCEImage) (string, error) {
                        err = fmt.Errorf("instance %s not running docker daemon - Server not found: %s", name, output)
                        continue
                }
+               var finished string
+               finished, err = remote.SSH(name, "ls", "/var/lib/cloud/instance/boot-finished")
+               if err != nil {
+                       err = fmt.Errorf("instance %s has not finished cloud-init script: %s", name, finished)
+                       continue
+               }
                instanceRunning = true
        }
        return name, err
```

We need to make sure that we only do this for images which use cloud-init.

### PR DESCRIPTION
**Pull request by rohitagarwal003**
This fixes #46889.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mindprince** [comment]
cc - @vishh

**Comment by mindprince** [comment]
This PR + https://github.com/kubernetes/kubernetes/pull/46810 will fix the e2e_node tests on COS image.

**Comment by cmluciano** [comment]
@k8s-bot ok to test

**Comment by mindprince** [comment]
/retest

@vishh Is there a command to run e2e_node tests for this PR? This affects those tests and I want to run those in the CI before merging this.

**Comment by cmluciano** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by mindprince** [comment]
@cmluciano There seems to be an actual bug in pull-kubernetes-node-e2e introduced by this PR, fixing it now. :)

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by vishh** [comment]
@dchen1107 FYI. This should fix the serial node e2es

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by fejta** [comment]
hey @k8s-merge-robot what's up?

**Comment by mindprince** [comment]
[`ci-kubernetes-node-kubelet-serial`](https://k8s-testgrid.appspot.com/sig-node#kubelet-serial-gce-e2e) is now [green](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1471). Yay!

**Pull request merged**
