### PR TITLE
Delete volumes in pv_recycle_controller

### PR DESCRIPTION
**Pull request by bprashanth**
The dynamic provisioner offloads volume deletion to the recycle controller, which appears to just drop delete events. 

@kubernetes/sig-storage maybe I'm missing the motivation to not do this? eitherway it was easy enough to upload this pr.

### CODE REVIEW

**Comment by jsafrane** [comment]
@bprashanth, deletion of a persistent volume is not "interesting" event for this controller. We recycle/delete PVs when a *claim* that binds to it is deleted, not when the *PV* object itself is deleted. When someone deletes a PV, the controller does nothing about it.

The reasoning behind this is that we may miss this *PV deleted* event (e.g. the controller was down at this moment). The controller has no persistent internal database of PVs to reconcile current PVs in etcd/API server with it. On the other hand, when we miss "claim deleted" event, we periodically check all bound PVs that appropriate claim still exists and recycle/delete the PV if not.

**Comment by bprashanth** [comment]
So I can delete a pvc, then immediately delete the pv, and the volume would leak?

**Comment by markturansky** [comment]
>
> So I can delete a pvc, then immediately delete the pv, and the volume
> would leak?
>
>
Yes. The recycler controller is the intended actor that removes from
volumes the infrastructure.

They volumes in AWS/GCE are *named* the same as the PV. That can help find
the leaked volumes.

**Comment by bprashanth** [comment]
Right, but you need this change for the happy case of no dropped events no? 
Or are you saying "that's yet to be implemented,and here's how we would implement it"?

**Comment by markturansky** [comment]
I suppose a watch event for "deleted PV" could check to see if the volume exists and attempt to remove it from the provider. If the controller restarts, there would be no "delete" event and the volume would still be orphaned in the provider.

**Comment by bprashanth** [comment]
IMO the delete event should get handled like all delete events. There should be an additional GC handler that recreates the names of volumes from the CP and matches them to existing volumes, but that should be a catching net that runs, eg: every minute or something.

**Comment by bprashanth** [comment]
@saad-ali @jsafrane @markturansky turns out I already checked this one line in by mistake, apologies (https://github.com/kubernetes/kubernetes/commit/6bc3052551550aa2bd7306daed44c8b293221ff0#diff-5b07a7e4f40bed89c6aa62cec121f90aR120). So we should either get this change in (more logs), or use this change to revert that one line. 

That said, I think deleting the volume on delete is strictly better than not, unless it's considered unsafe for some reason.

**Comment by saad-ali** [comment]
> So we should either get this change in (more logs), or use this change to revert that one line.

@markturansky and @jsafrane (who is working on refactoring all this code) are most familiar with the recycler behavior. I'll leave it to him to decide.

**Comment by markturansky** [comment]
@bprashanth I think your addition in that commit won't ever actually go through, but will fail gracefully if/when it does.

The recycler checks the `shouldRecycle` func before attempting to reclaim the volume.  If PV.Status != Released, it will be skipped.

The binder is the only actor today that sets the PV to Released.  The watch in the recycler gets that change in the Update handler and the volume is then deleted.

On delete, your addition to the recycler should fail because the volume should already be gone.

**Comment by thockin** [comment]
@jsafrane, given the major refactor, should we just close this?

**Comment by bprashanth** [comment]
Yeah I need to debug what I saw anyway.

> @bprashanth I think your addition in that commit won't ever actually go through, but will fail gracefully if/when it does.
The recycler checks the shouldRecycle func before attempting to reclaim the volume. If PV.Status != Released, it will be skipped.
The binder is the only actor today that sets the PV to Released. The watch in the recycler gets that change in the Update handler and the volume is then deleted.
On delete, your addition to the recycler should fail because the volume should already be gone.

Ah, so I think this is the race I observed then:
binder releases
user deletes
recycler gets update of the releae
pv doesn't exist so this fails: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_recycler_controller.go#L165
Pd is leaked

I can keep an eye out for when it happens again and follow up

**Pull request closed without merging**
