### PR TITLE
Formatting json makes it more beautiful and readable

### PR DESCRIPTION
**Pull request by clarklee92**
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>

**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
When I read the json file, I found that most of the indentation and writing of json was hard to read and even ugly. So I've formatted all of the json in a standard format and it looks more readable.

**Which issue(s) this PR fixes**:

>Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR, but this is changing many files which are already formatted (just differently), and are also generated (so cannot be changed to an arbitrary different format). See the CI test failures for examples.

/close

**Comment by clarklee92** [comment]
> thanks for the PR, but this is changing many files which are already formatted (just differently), and are also generated (so cannot be changed to an arbitrary different format). See the CI test failures for examples.
> 
> /close

Yep, I noticed that and it's ok to close this. 
Good morning 😁, I left you a message on slack.

**Pull request closed without merging**
