### PR TITLE
Report node.Ready == false until cbr0 is configured correctly

### PR DESCRIPTION
**Pull request by cjcullen**

### CODE REVIEW

**Comment by cjcullen** [comment]
This should address #8758 & #8581.

@justinsb @roberthbailey @lavalamp

**Comment by saad-ali** [comment]
Marking this for v1.0 milestone since it fixes test instability. Assigning @lavalamp

**Comment by roberthbailey** [comment]
LGTM.

**Comment by lavalamp** [comment]
Awesome, thanks!

**Pull request merged**
