### PR TITLE
cleancode replica_set_utils.go

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot ok to test

**Review by NickrenREN — APPROVED** [review]
/lgtm

**Comment by jianglingxia** [comment]
the pr has lgtm label @k8s-merge-robot @NickrenREN

**Comment by kargakis** [comment]
Can you also update the [RC counterpart](https://github.com/kubernetes/kubernetes/blob/04387ac0d05a2e7b7d79992df9e3f5382b65a247/pkg/controller/replication/replication_controller_utils.go#L153)?

**Comment by jianglingxia** [comment]
I checkout the branch and update the  RC counterpart，then test it in my local environment ,but show undefined: sort.SliceStable the error ,is the branch not the lastest that conflict the master ? @kargakis

**Comment by jianglingxia** [comment]
i have rebase  it and update it! thanks @k8s-merge-robot

**Comment by jianglingxia** [comment]
I have recommit the pr to #49619 and update it,so I close it,thanks!

**Pull request closed without merging**
