### PR TITLE
Remove 'system' prefix from Metadata Agent rbac configuration

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does / why we need it**:
Remove 'system' prefix from Metadata Agent rbac configuration.

**Release note**:
```release-note
Remove 'system' prefix from Metadata Agent rbac configuration
```

### CODE REVIEW

**Review by igorpeshansky — APPROVED** [review]
LGTM :shipit:

**Comment by ericchiang** [comment]
/lgtm cancel

Will re-approve once `pull-kubernetes-e2e-gke` has stopped flaking.

**Comment by kawych** [comment]
@ericchiang 
Looks like the flake went away, PTAL

**Pull request merged**
