### PR TITLE
Build etcd image of v3.5.15

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
etcd is now released in [v3.5.15](https://github.com/etcd-io/etcd/releases/tag/v3.5.15)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by pacoxu** [comment]
ping @serathius and @ahrtr 
Should we include this in Kubernetes v1.31?
- https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v3515-2024-07-19

**Comment by ahrtr** [comment]
> ping @serathius and @ahrtr Should we include this in Kubernetes v1.31.0 ?
> 
> * https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v3515-2024-07-19

Yes, I think so. It's always recommended to bump the latest etcd patch.

I see Kubernetes v1.31 Code Freeze is now in effect, but etcd 3.5.15 contains CVE fixes, and also a couple of bug fixes.

**Comment by bzsuni** [comment]
/assign @dims 
For approval please

**Comment by bzsuni** [comment]
> /milestone v1.31

For approval please

**Comment by dims** [comment]
/approve

Does not change anything in k8s itself, just what version of etcd we test with.

**Pull request merged**
