### PR TITLE
Cleanup: fix golint failures in pkg/kubelet/{cri, cm}

### PR DESCRIPTION
**Pull request by ESWZY**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures under package `pkg/kubelet{cri, cm, api}`.

**Which issue(s) this PR fixes**:

Ref: #68026 [Fix golint failures](https://github.com/kubernetes/kubernetes/issues/68026)

Break up: #93222 [Cleanup: fix linting failures](https://github.com/kubernetes/kubernetes/pull/93222)

**Special notes for your reviewer**:

Change some var names to avoid golint failures, like `Cpu -> CPU`

Also simplifyied some variable name to avoid:

```
xxx.go:X:6: type name will be used as remote.RemoteRuntimeService by other packages, and that stutters; consider calling this RuntimeService
```

If that causes ambiguity, please tell me to revert that.

To break up another PR, I reverted some of commits. Sorry for a long commit log.

Thanks for your review! If you have any reply, I will respond as soon as possible!

### CODE REVIEW

**Review by kikisdeliveryservice — COMMENTED** [review]
@ESWZY can you please update your commit message be more informative/reflect the title and purpose of this PR?

**Comment by ESWZY** [comment]
> @ESWZY can you please update your commit message be more informative/reflect the title and purpose of this PR?

Updated. 😀

**Comment by ehashman** [comment]
This PR has needed a rebase for a few months. I am going to close it. Please feel free to reopen once you've had the chance to look at it!

/close

**Pull request closed without merging**
