### PR TITLE
services must listen on port 443 for aggregation

### PR DESCRIPTION
**Pull request by deads2k**
If a clusterIP service isn't listening on port 443, don't mark it as available.

@mfojtik you've got an issue, right?
@kubernetes/sig-api-machinery-bugs 
/assign @sttts 

/kind bug

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
What happens now? We serve the handler in the aggregator and then notice the port is missing and return 500?

**Comment by mfojtik** [comment]
/lgtm

@sttts the GC breaks and the server will report the error forever.

**Pull request merged**
