### PR TITLE
Replace nginx image with agnhost in sig-node pods tests

### PR DESCRIPTION
**Pull request by adelina-t**
Part of a continued effort to replace test images with Agnhost where possible.

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/assign @derekwaynecarr
/lgtm

Assuming the test suite passes, this change makes sense to me. Agree it makes sense to use the simplest possible container in our test cases, provided nothing in the test requires anything more complex.

**Comment by PatrickLang** [comment]
/milestone v1.17

pinging @derekwaynecarr - can you review this test simplification?

**Comment by josiahbjorgaard** [comment]
/milestone v1.18

(code freeze v1.17)

**Pull request merged**
