### PR TITLE
Improve error logging in glusterfs provisioner

### PR DESCRIPTION
**Pull request by jsafrane**
- log `err` if it is known
- unify log message style

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35615)

### CODE REVIEW

**Comment by rootfs** [comment]
LGTM.

Along the line, I think a code style guide for error formatting and logging [here](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md) is helpful. @bgrant0607 ?

**Comment by humblec** [comment]
Thanks @jsafrane . LGTM

**Comment by jsafrane** [comment]
rebased

**Comment by rootfs** [comment]
/lgtm

(see if it works)

**Comment by jsafrane** [comment]
It works! However, merge must wait until after code freeze.

**Pull request merged**
