### PR TITLE
revert "refactor: simplify RunScorePlugins for readability + performance"

### LINKED ISSUE #119440: Performance degradation on scoring
### What happened?

/sig scheduling
/kind regression

#118606 caused a performance degradation in the 5k nodes scalability tests
image

The PR changed how to split the load among parallel threads. Previously, we would parallelize over the number of nodes. The PR does it over the number of plugins, which is much smaller.

### What did you expect to happen?

Performance to improve or remain the same

### How can we reproduce it (as minimally and precisely as possible)?

https://perf-dash.k8s.io/#/?jobname=kubemark-5000Nodes-scheduler&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=Score&TestName=pod-anti-affinity

### Anything else we need to know?

_No response_

### Kubernetes version

1.28

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind regression

#### What this PR does / why we need it:
This pr simply reverts the changes in https://github.com/kubernetes/kubernetes/pull/118606  (https://github.com/kubernetes/kubernetes/commit/a7eb7ed5c6a364ba815e5dd32c1ba598b19cdb57)
#### Which issue(s) this PR fixes:

Fixes #119440

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
why not just revert it (https://github.com/kubernetes/kubernetes/pull/118606/commits/a7eb7ed5c6a364ba815e5dd32c1ba598b19cdb57)? I cannot see any special reason for the diff with the revert.

For any reason, I'd suggest you to reference the original PR so that more context can be revealed.

**Comment by AxeZhan** [comment]
> why not just revert it (https://github.com/kubernetes/kubernetes/commit/a7eb7ed5c6a364ba815e5dd32c1ba598b19cdb57)? I cannot see any special reason for the diff with the revert.

This pr reverts the parallizer over plugins while keeping the change from map to slice, although it might help a little. You're suggesting it's better to just revert all?

**Comment by AxeZhan** [comment]
> This pr reverts the parallizer over plugins while keeping the change from map to slice.

I separate these two changes to show more clearly

**Comment by chendave** [comment]
> You're suggesting it's better to just revert all?

I am not suggesting to revert all of them, but just asking is that slice changing is necessary.

**Comment by AxeZhan** [comment]
> I am not suggesting to revert all of them, but just asking is that slice changing is necessary.

Hmmm, I think it's better. But I don't expect a major impact for it. We can let others decide.

**Comment by sanposhiho** [comment]
Sorry, I'm a bit late for this and thanks @AxeZhan for handling.
I agree with @chendave, please just revert a7eb7ed5c6a364ba815e5dd32c1ba598b19cdb57 in this PR and have another separated PR for the slice change.

@alculquicondor Does this PR deserve to get merged soon while breaking the code freeze?

**Comment by sanposhiho** [comment]
@AxeZhan Also, please put the link for https://github.com/kubernetes/kubernetes/pull/118606 somewhere in the PR description

**Comment by kerthcet** [comment]
/retitle revert "refactor: simplify RunScorePlugins for readability + performance"
@sanposhiho I saw a second commit in your original PR, I think it's unrelated, right?

**Comment by sanposhiho** [comment]
Yes, that's something we still need. So, the reverting target is only a7eb7ed5c6a364ba815e5dd32c1ba598b19cdb57

**Comment by chendave** [comment]
> breaking the code freeze?

that is just feature freeze, the bug fixing like this should be okay to get into 1.28.

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
