### PR TITLE
Double container probe timeout

### PR DESCRIPTION
**Pull request by liggitt**
in some environments, we see a combination of start latency
and the corresponding effect on sync pod latency causing status
manager to fail to report within the 2 minute window.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/sig testing
@kubernetes/sig-testing-pr-reviews

**Comment by fejta** [comment]
LGTM but can we get someone from the relevant sig -- api-machinery or networking?? -- to review this?

**Comment by smarterclayton** [comment]
Right now about 2 minutes is the longest i've seen, so i think 3 is a good rule of thumb (a slow pull with heavily contended low CPU node without high IOPS)

**Comment by smarterclayton** [comment]
Generally I would expect any latency issues to be caught by the sig-scalability tests that measure for this that are more controlled environments (a high parallelism e2e is not controlled since multiple conflicting workloads can vary wildly in scope).

**Pull request merged**
