### PR TITLE
check function return err

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
check function return err

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE

```

### CODE REVIEW

**Comment by zouyee** [comment]
gentle ping @jsafrane

**Comment by zouyee** [comment]
gentle ping @jsafrane would you like LGTM?

**Comment by jsafrane** [comment]
/lgtm
Sorry it took so long

**Pull request merged**
