### PR TITLE
Use small letter var definition

### PR DESCRIPTION
**Pull request by zhengguoyong**

### CODE REVIEW

**Comment by ashcrow** [comment]
Jenkins failure is a flake.

Overall this looks good to me as the constants in question are only used within their package.

@zhengguoyong one nit: would you mind making the commit message a bit more specific of the change? Something closer to ```kubelet: runonce constants no longer exported```?

**Comment by zhengguoyong** [comment]
@k8s-bot test this please

**Comment by bgrant0607** [comment]
LGTM, thanks

**Comment by ArtfulCoder** [comment]
manually merging since k8s-bot is blocked on scaliability test failure.

**Pull request merged**
