### PR TITLE
Cherry pick of #105188 and #98350 to release 1.21

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #105188 on release-1.21.

#98530: aggregate errors when putting vmss
#105188: fix: consolidate logs for instance not found error

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
aggregate errors when putting vmss
fix: consolidate logs for instance not found error
```

### CODE REVIEW

**Comment by nilo19** [comment]
/sig cloud-provider
/area provider/azure
/priority critical-urgent
/triage accepted
/kind bug
cc @feiskyer

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
This one is lacking approval (cc @cheftako @andrewsykim)

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
