### PR TITLE
Add Kubernetes 1.6 support to Juju charms

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This adds Kubernetes 1.6 support to Juju charms.

This includes some large architectural changes in order to support multiple versions of Kubernetes with a single release of the charms. There are a few bug fixes in here as well, for issues that we discovered during testing.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Thanks to @marcoceppi, @ktsakalozos, @jacekn, @mbruzek, @tvansteenburgh for their work in this feature branch as well!

**Release note**:

```release-note
Add Kubernetes 1.6 support to Juju charms
Add metric collection to charms for autoscaling
Update kubernetes-e2e charm to fail when test suite fails
Update Juju charms to use snaps
Add registry action to the kubernetes-worker charm
Add support for kube-proxy cluster-cidr option to kubernetes-worker charm
Fix kubernetes-master charm starting services before TLS certs are saved
Fix kubernetes-worker charm failures in LXD
Fix stop hook failure on kubernetes-worker charm
Fix handling of juju kubernetes-worker.restart-needed state
Fix nagios checks in charms
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
@k8s-bot ok to test

**Comment by marcoceppi** [comment]
@k8s-bot verify test this

**Comment by Cynerva** [comment]
Pushed updates to hacks/verify-flags/exceptions.txt to cover the new stuff in kubernetes_worker.py.

**Comment by chuckbutler** [comment]
@smarterclayton @liggitt Could either of you two take a quick look at this PR? It seems that the k8s bot didn't tag anyone from the owners file of the HACK dir which is holding things up here as we're pending a /approve /lgtm.

**Comment by chuckbutler** [comment]
@k8s-bot non-cri e2e test this

**Pull request merged**
