### PR TITLE
refactor: extract describeContainer function which gocyclo result is …

### PR DESCRIPTION
**Pull request by oulinbao**
**What this PR does / why we need it**:
refactor describeContainers function and decrease gocyclo result 

**Special notes for your reviewer**:
None

**Release note**:
None

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36032)

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot ok to test.

**Comment by oulinbao** [comment]
@brendandburns, why this PR didn't test automatically? What should I do next?

**Comment by brendandburns** [comment]
@k8s-bot test this please issue: IGNORE

tests are pending for too long, something bad must have happened.

**Comment by brendandburns** [comment]
@oulinbao tests are failing: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36032/pull-kubernetes-unit/4745/

Do they pass in your dev. environment?

Thanks
--brendan

**Comment by oulinbao** [comment]
@brendandburns, thanks for your reminding. I will fix it right now.

**Comment by oulinbao** [comment]
rebase wrong here, change to another PR.

**Comment by oulinbao** [comment]
pls review https://github.com/kubernetes/kubernetes/pull/36732, thanks.

**Comment by oulinbao** [comment]
func (this *PrefixWriter) Write(level int, format string, a ...interface{}) {
	levelSpace := "  "
	prefix := ""
	for i := 0; i < level; i++ {
		prefix += levelSpace
	}
	fmt.Fprintf(this.out, prefix+format, a...)
}

@brendandburns, I found the reason that test-cmd failed. Because I forgot three points after parameter a.
a -> a... 
But the UT passed when I forgot the "...", I will fix it on new PR #36732.

**Pull request closed without merging**
