### PR TITLE
sort when `len(objs)` >=2

### PR DESCRIPTION
**Pull request by xmh19936688**
sort when `len(objs)` >=2

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rikatz** [comment]
Hello,

can you please explain why this change is necessary? What triggers this error? What's the behavior pre and post this PR?

Thanks!

**Comment by xmh19936688** [comment]
`return nil` when `len(objs) == 0` or `len(objs) == 1`, so it's `<2`. It don't need sort in such situation.

**Comment by rikatz** [comment]
OK but why this should return nil if len(objs) == 1? Why not keep the current behavior? Is there an issue associated with this?

**Comment by dougsland** [comment]
> OK but why this should return nil if len(objs) == 1? Why not keep the current behavior? Is there an issue associated with this?

+1

**Comment by rikatz** [comment]
@xmh19936688 instead of replacing the len(objs) == 0, I would suggest:

* On line 62, do an early verification like this:
`if meta.IsListType(obj) && meta.LenList(obj) > 1 {`

* Remove the if len(objs) == 0 from sortObj function, as this is early validated by the && meta.LenList on the outer function

**Comment by xmh19936688** [comment]
> OK but why this should return nil if len(objs) == 1? Why not keep the current behavior? Is there an issue associated with this?

It don't need to sort if len(objs) == 1, so return early.

**Pull request closed without merging**
