### PR TITLE
Fix codegen for older bash

### LINKED ISSUE #116094: Unable to run hack/update-codegen.sh
### What happened?

I am working on a PR where I am removing some legacy code from a API.  

I believe I have to run some scripts to generate code.

When I run `make update`

I get the following error:

```
Running update-codegen
go version go1.20.1 linux/amd64
/home/ec2-user/Work/GIT/kubernetes-kevin/hack/update-codegen.sh: line 1008: flags_to_pass[@]: unbound variable
```

### What did you expect to happen?

I expect the script to work and run without error.

### How can we reproduce it (as minimally and precisely as possible)?

Run hack/update-codegen.sh or run `make update`

### Anything else we need to know?

I am on the latest build.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by thockin**
Fixes #116094 
@kannon92 

Waiting for confirmation from someone with old bash available.

/kind bug
```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
Unfortunately my build environment is in a bad state. I am able to get to the different code gen steps with this patch so I think it’s probably good.  

Before I was getting a quick failure when passing in arguments

**Comment by liggitt** [comment]
I don't know how to review this, but CI is happy, I tried it locally and my dev env is happy with it, and it sounded like it unblocked the linked issue, so...
/lgtm

**Comment by thockin** [comment]
This is a known technique - not being plagued with old bash, I didn't think
to use it.  My confidence is high that this is necessary but it may not be
sufficient - I need an old-bash user to confirm, and I am happy to sprinkle
some more of this abomination elsewhere if needed (I didn't see ee any
obviously necessary places, but ... Bash)

**Pull request merged**
