### PR TITLE
Automated cherry pick of #67825: Fix VMWare VM freezing bug by reverting #51066

### PR DESCRIPTION
**Pull request by nikopen**
Cherry pick of #67825 on release-1.11.

#67825: Fix VMWare VM freezing bug by reverting #51066

### CODE REVIEW

**Comment by divyenpatel** [comment]
@nikopen @gnufied @SandeepPissay 

This is the behavior on 1.11 branch with this change.


Created deployment deployment.
Pod scheduled on `kubernetes-node4` and volumes got attached to this node.

```
# kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
wordpress-mysql-56647d4597-nvq46   1/1       Running   0          1m
```

```
# kubectl describe pod wordpress-mysql-56647d4597-nvq46 | grep Node:
Node:           kubernetes-node4/10.192.91.105
```

```
# kubectl get nodes     
NAME                STATUS                     ROLES     AGE       VERSION
kubernetes-master   Ready,SchedulingDisabled   <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node1    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node2    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node3    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node4    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
```

Powered off the node `kubernetes-node4`, on which the Pod is running.
New Pod is spawned on the Node - `kubernetes-node2`.

```
# kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
wordpress-mysql-56647d4597-hp4rv   1/1       Running   0          7m
```

```
# kubectl describe pod wordpress-mysql-56647d4597-hp4rv | grep Node:
Node:           kubernetes-node2/10.192.71.62
```

Powered Off Node is removed from the API server.

```
# kubectl get nodes
NAME                STATUS                     ROLES     AGE       VERSION
kubernetes-master   Ready,SchedulingDisabled   <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node1    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node2    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node3    Ready                      <none>    2h        v1.11.3-beta.0.57+28b2e1799fea17
```

After 6 minutes, volumes successfully attached to new node `kubernetes-node2` but did not detached from the powered off node.

Attempt to power on node `kubernetes-node4` will fail with error - `File system specific implementation of OpenFile[file] failed`.

Attempt to stop kubelet on the node `kubernetes-node2 `.

```
root@kubernetes-node2 [ ~ ]# systemctl stop kubelet.
```

Node status changed to `NotReady`.
```
# kubectl get nodes
NAME                STATUS                     ROLES     AGE       VERSION
kubernetes-master   Ready,SchedulingDisabled   <none>    3h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node1    Ready                      <none>    3h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node2    NotReady                   <none>    3h        v1.11.3-beta.0.57+28b2e1799fea17
kubernetes-node3    Ready                      <none>    3h        v1.11.3-beta.0.57+28b2e1799fea17
```

```
# kubectl get pods
NAME                               READY     STATUS              RESTARTS   AGE
wordpress-mysql-56647d4597-hp4rv   1/1       Unknown             0          31m
wordpress-mysql-56647d4597-lmppg   0/1       ContainerCreating   0          45s
```
new pod is spawned on node `kubernetes-node1`.

```
# kubectl describe pod wordpress-mysql-56647d4597-lmppg | grep Node:
Node:           kubernetes-node1/10.192.93.102
```

new pod `wordpress-mysql-56647d4597-lmppg` remains in to `ContainerCreating` state. volumes could not detached from `kubernetes-node2` and attached to new node `kubernetes-node1`.

```
# kubectl get pods 
NAME                               READY     STATUS              RESTARTS   AGE
wordpress-mysql-56647d4597-hp4rv   1/1       Unknown             0          40m
wordpress-mysql-56647d4597-lmppg   0/1       ContainerCreating   0          10m
```

This is the same behavior as mentioned for 1.9 branch at https://github.com/kubernetes/kubernetes/pull/68056#issuecomment-417738568 and https://github.com/kubernetes/kubernetes/pull/68056#issuecomment-417743543

**Comment by foxish** [comment]
Cherrypick approved. cc/ @saad-ali for LGTM and approval.

**Comment by redbaron** [comment]
@foxish,  is this regression enough to justify new 1.11.4 release?  We've been hit by it, but would also benefit from other bugfixes in 1.11.3.

**Comment by nikopen** [comment]
@redbaron it didn't make it to 1.11.3 in time...

as a workaround you can compile a custom kube-controller-manager with the related lines removed, this is a good guide: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/compiling-kubernetes-binaries

**Pull request merged**
