### PR TITLE
Follow up for https://github.com/kubernetes/kubernetes/pull/47003

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:
This is addressing left comments for https://github.com/kubernetes/kubernetes/pull/47003#discussion_r120888982

/cc @aveshagarwal 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by k82cn** [comment]
@kubernetes/sig-api-machinery-bugs  , please help to review this PR; this is a api-machinery enhancement/cleanup :).

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-verify test this

**Pull request merged**
