### PR TITLE
Recognize watch operations via ?watch param

### PR DESCRIPTION
**Pull request by liggitt**
@deads2k @smarterclayton

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36070)

### CODE REVIEW

**Comment by deads2k** [comment]
Do we still care about the distinction?

**Comment by liggitt** [comment]
In https://github.com/kubernetes/kubernetes/pull/36064 I'd like to use actual parsed verbs and subresources for read/write and long-running determinations (instead of regexes against the URL path), so yes.

**Comment by liggitt** [comment]
reassigning, @lavalamp is out

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
flake #33987
@k8s-bot node e2e test this

**Pull request merged**
