### PR TITLE
test case for pkg/kubelet/cri/remote/utils.go

### PR DESCRIPTION
**Pull request by changshuchao**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/ok-to-test
/priority important-longterm
/triage accepted

**Comment by changshuchao** [comment]
@feiskyer hi，could you please review this pr? thanks

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by changshuchao** [comment]
@feiskyer  can this pr be merged？

**Pull request merged**
