### PR TITLE
Add node update method to client interface

### PR DESCRIPTION
**Pull request by deyuanix**
@derekwaynecarr @smarterclayton

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Godoc appears to have inconsistent use of minion and node terminology.

**Comment by ddysher** [comment]
Updated

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
derek, any other comment?

**Comment by ddysher** [comment]
@derekwaynecarr Any further comment?

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by ddysher** [comment]
Thanks for stamping.  @smarterclayton Can you take another look and merge the PR?  I think derek doesn't have write permission .

**Comment by smarterclayton** [comment]
Re-running travis then will merge

**Pull request merged**
