### PR TITLE
cleanup: Remove out-of-support Windows 20H2 images

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Windows Server, Version 20H2 is out of support so we shouldn't be building container images for that version anymore.

Note: This is the last SAC (18 month support) of Windows Server we supported in K8s. From now on only LTSC (5 year support) versions of Windows server will be supported here.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removing Windows Server, Version 20H2 flavors from various container images
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows

### CODE REVIEW

**Comment by marosset** [comment]
/milestone v1.26
/assign @claudiubelu @jsturtevant 
For SIG-Windows review

**Comment by dims** [comment]
```
INFO Validating zeitgeist options...              
ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that registry.k8s.io/pause should be at version 3.8, but the following files didn't match: build/pause/Makefile 
FATA Dependencies are not in sync 
```

**Comment by claudiubelu** [comment]
LGTM for the test image changes. With this, there are no 20H2 references in this project.

**Comment by marosset** [comment]
> > ```
> > INFO Validating zeitgeist options...              
> > ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that registry.k8s.io/pause should be at version 3.8, but the following files didn't match: build/pause/Makefile 
> > FATA Dependencies are not in sync 
> > ```
> 
> Let me update this

Updated

**Comment by jpbetz** [comment]
/approve
for etcd changes

**Comment by marosset** [comment]
> changes look good to me, Do we need to update the change log here https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md?

I can do that.
Since that md references the PRs there is a chicken-and-egg problem :-/

**Comment by marosset** [comment]
> > changes look good to me, Do we need to update the change log here https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md?
> 
> I can do that. Since that md references the PRs there is a chicken-and-egg problem :-/

Added

**Pull request merged**
