### PR TITLE
describe pod: add unit test for Node

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

Add unit test for "describe pod" in order to get node info.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Review by resouer — APPROVED** [review]
code lgtm

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
ping @deads2k

**Pull request merged**
