### PR TITLE
kubeadm: Migrate cert and PKI helpers to ClusterConfiguration

### PR DESCRIPTION
**Pull request by rosti**
**What this PR does / why we need it**:

This PR is the second in a series, targeting the replacement of InitConfiguration with ClusterConfiguration, when the former is not needed. Please, review only the last commit.

This PR migrates cert and PKI helper APIs to use ClusterConfiguration (and away from InitConfiguration).
    
The certificate and PKI related helper APIs used InitConfiguration. With the introduction of ClusterConfiguration it became more viable to use that instead (in most cases in combination with NodeRegistrationOptions).
    
This change will allow us to avoid the use of InitConfiguration outside of kubeadm init

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
refs kubernetes/kubeadm#963

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/kind enhancement
/assign @luxas
/assign @timothysc
/assign @fabriziopandini
/cc @stealthybox 

Depends on:
- [X] #67441
- [ ] #67503 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
@rosti please wait until the config file reworking is completed in order to avoid unnecessary reworks. E.g we are going to move advertise address out of ClusterConfiguration -> this might require to revert some changes in this pr

**Comment by rosti** [comment]
@fabriziopandini I can see your point here and I agree with the hold. 
I did the PR thinking, that even if API server advertise address moves, it will likely be a move somewhere inside `ClusterConfiguration` as opposed to external. Thus, changing the interface to a combo of `ClusterConfiguration` and `NodeRegistrationOptions` looked safe to me.

**Comment by timothysc** [comment]
We are going to need to lock down the config for 1.12 and punt the rest of the shuffling to try and make a complete push to beta in 1.13.

**Comment by rosti** [comment]
Not in this form and certainly this should not have a high priority. I'll close this for now. 

/close

**Pull request closed without merging**
