### PR TITLE
Change sort function of the scheduling queue to avoid starvation

### PR DESCRIPTION
**Pull request by bsalamat**
**What type of PR is this?**
/king bug

**What this PR does / why we need it**:
Addresses scenario #2 of #71486

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes part of #71486

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix scheduling starvation of pods in cluster with large number of unschedulable pods.
```

### CODE REVIEW

**Comment by hex108** [comment]
Thanks! We also observed this problem in our cluster. The patch lgtm.

Maybe the performance issue is caused by adding another compare(pod time compare)? How about solving the problem by using `map[priority]PodArray` instead of `heap`?  In the `PodArray`, pods are appended by `createTime` or `LastTransitionTime`(if scheduler every tried to schedule it).

**Review by Huang-Wei — APPROVED** [review]
/lgtm

Thanks @bsalamat.

**Comment by bsalamat** [comment]
@hex108 PodArray does not work. The highest priority pods must be in front of the ActiveQ. We need a heap for that.

**Comment by hex108** [comment]
@bsalamat we could use another structure to record priorities and get the highest priority, then get corresponding PodArray. I could make a prototype in anther PR if it makes sense.

**Review by resouer — APPROVED** [review]
/lgtm

**Comment by resouer** [comment]
@hex108 We need to make sure it's `activeQComp` related first, mind to do a quick benchmark?

**Comment by bsalamat** [comment]
> we could use another structure to record priorities and get the highest priority, then get corresponding PodArray. I could make a prototype in anther PR if it makes sense.

@hex108 If I understand correctly, you want to have two separate arrays for holding pods. One array has pods sorted by `LastTransitionTime` and another array that holds pods sorted by their priority. How do you want to merge these two while keeping high performance? Please note that sometimes a large group of pods may be created and added to the queue. Also, a large number of pods may go from unschedulable queue to the active queue. These operations should be fast.
Finally, I don't think comparing times would be CPU intensive and is unlikely to cause performance issues. Time comparison involves several integer comparison which should be quick.
I would first try running benchmarks to find whether the current approach causes performance issues before trying a different data structure instead of heap.

**Comment by hex108** [comment]
@bsalamat Yes, heap will be better if it is OK :)

-----------------
The following is just an idea for optimization. 

Only one array for holding pods for each priority. Use `highestPriority int`  to record the highest pod priority, and `podMap map[int][]*Pod` to record pods for each priority, the array `[]*Pod` acts like FIFO queue. When we append a pod to it, the pod is usually one of following two cases: 

**a**. Its creation time is usually(not strict, because we do not get pods ordered by their creation time ) after the pods in the array. 

**b**. It has been tried to be scheduled, but failed, so it could be put to the tail of the array.

When add/pod a pod, we need update `highestPriority`, then we could always get highest priority  pod and almost earliest time pod from the head of `podMap[higestPriority]`.

In this way, we could avoid compare.

**Comment by AishSundar** [comment]
@bsalamat would it be possible for you to attend the [10am release burndown today](https://zoom.us/j/611312756 ) where we can discuss this a bit more before making a Go-NoGo for 1.13 thanks.

**Comment by bsalamat** [comment]
@hex108 I know understand your solution better. It may work, but please keep in mind that when the highest priority array gets empty, you will need to traverse the map to find the next high priority queue. This may happen frequently.
I think we should measure the performance impact of your solution. If I recall correctly, we didn't see any meaningful performance change after switching from a FIFO to the current scheduling queue which is a lot more sophisticated. I believe there are two reasons: 1. placing pods in the active queue (heap) happens in event handlers which are executed in separate threads in parallel to the main scheduling thread, 2. the main scheduling thread mostly does Pop(). Popping the queue is such a small portion of the whole scheduling cycle. It doesn't impact the scheduler's performance.
All that being said, please feel free to try your idea. If you can show performance improvement, we will be happy to replace the current mechanism.

**Comment by AishSundar** [comment]
/remove milestone

Removing milestone for now. @aleksandra-malinowska @tpepper this is a critical candidate for 1.13.1. Is there a timeline for it yet?

**Comment by aleksandra-malinowska** [comment]
Really looking forward to this fix as we tend to hit the edge cases in scheduling way more frequently with autoscaling. Are there any plans to also handle the case where higher priority unschedulable pod blocks lower priority pods, or to prioritize pods with nominated node name? 

@tpepper I'm in favor of releasing earlier with fewer cherry-picks, assuming CI signal is good. Let's discuss it later today if possible

**Comment by bsalamat** [comment]
@aleksandra-malinowska Yes, there are two other PRs, #57057 and #71551, to address a higher priority pod blocking head of the queue.

**Pull request merged**
