### PR TITLE
Support for running e2e tests in CircleCI

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by zmerlynn** [comment]
This pull relies on #4321, waiting on that to quiesce and merge.

**Comment by zmerlynn** [comment]
@justinsb: I merged #4321, watching our Jenkins today. If you want to pursue this one again, seems like a good time.

**Comment by piosz** [comment]
Is this PR active? If not please close it according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/pull-requests.md

**Comment by piosz** [comment]
Closing according to the mentioned policy.

**Pull request closed without merging**
