### PR TITLE
Promote KEP-2681 to beta in 1.29

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #

Test fix by #121429

#### Does this PR introduce a user-facing change?

```release-note
Promote PodHostIPs condition to beta.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2681
- [Usage]: <link>
- [Other doc]:
```

### CODE REVIEW

**Comment by dims** [comment]
/milestone v1.29

Do we want to do this @thockin @aojea ? is it ready ?

**Comment by hailkomputer** [comment]
Hello, bug triage team lead here. I want to check the status and remind that the the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03), as we want to ensure that each PR has a chance to be merged.
Are we still targeting the 1.29 release?

**Comment by pacoxu** [comment]
/priority important-soon

https://github.com/kubernetes/kubernetes/pull/121429 changed the case to run serialized as the node e2e tried to restart kuebelet. And it will skip if the FG is not enabled.(The current node e2e doesn't support it well, so the current workaround is just to check the default one. THere is a WIP PR https://github.com/kubernetes/kubernetes/pull/120139 on this)

**Comment by wzshiming** [comment]
Test has been updated in #121429, #121479 and this PR is ready to be merge.

**Comment by thockin** [comment]
I have not had time to re-review this, and as long as tests are failing it's stuck.

**Comment by aojea** [comment]
> I have not had time to re-review this, and as long as tests are failing it's stuck.

@thockin tests should be good now, this is good to go

**Pull request merged**
