### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Fix typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
@xichengliudui thanks for the fix!

/kind cleanup
/ok-to-test

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
