### PR TITLE
Remove legacy files when stop the cluster

### PR DESCRIPTION
**Pull request by alfred-huangjian**
When we deploy the kubernetes using Ubuntu's script. 
1. First we set the roles "ai i i" and NUM_MINIONS=3, it runs as expected.
2. Then we stop the cluster and change the roles to "a i i" and NUM_MINIONS=2, it will run with errors:
Waiting for 2 ready nodes. 3 ready nodes, 3 registered. Retrying.

It's because there are history files left on the previous deployment. 
This commit will delete the files when stop the cluster.

### CODE REVIEW

**Comment by gmarek** [comment]
@WIZARD-CXY - the change LGTM, but you're more familiar with Ubuntu setup. Shouldn't be overwrite those files in the first place?

**Comment by alfred-huangjian** [comment]
@WIZARD-CXY - Can you help to take a look at this issue? Thanks.

**Comment by WIZARD-CXY** [comment]
@alfred-huangjian Sorry for the late reply. I think you can leave `~/kube` alone If you do not want a very very clean.In fact you can remove `/var/lib/kubelet`  also for a clean teardown.

**Comment by alfred-huangjian** [comment]
@WIZARD-CXY Yes, you are right. I need to remove the /var/lib/kubelet folder also in order to have a clean teardown. For the ~/kube, I perfer to keep removing that in order to have a clean environment. However, the new k8s version will copy to this folder again during next deployment. How about your ideas?

**Comment by WIZARD-CXY** [comment]
LGTM

**Pull request merged**
