### PR TITLE
fix: remove duplicated code in image-util.sh due to merge conflict

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**

- removed duplicated code due to merge conflict between #95567 and #77269.
- appended `local` in front of variables pointing to function arguments (e.g. `$1`, `$2`) to avoid naming conflicts. In `build()`, if the test image has an `ALIAS` file, the variable `image` will be changed to the content in the `ALIAS` file. This will cause `push()` to `pushd` the incorrect directory, leading to an incorrect tag being used when constructing the manifest list.
- fixed indentation

/sig testing
/kind cleanup
/priority important-soon
/cc @claudiubelu 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@chewong please ping me after @claudiubelu reviews this

/hold
/assign

**Comment by claudiubelu** [comment]
Indeed, the code got duplicated because of 2 PRs containing the same "alias" logic in both of them, which is the bigger issue since it'll then try to ``pushd`` twice.

After applying this PR, I can build the ``httpd-new`` image which contains an alias.

We're also going to have to merge this: https://github.com/kubernetes/kubernetes/pull/98831 . PHP tends to update their release links, so they can become invalid in time. We can use the archives links instead.

/lgtm

**Pull request merged**
