### PR TITLE
Remove pullLock from Kubelet.

### PR DESCRIPTION
**Pull request by vmarmol**
The lock was only ever used to grab a read lock before container pulls.

### CODE REVIEW

**Comment by dchen1107** [comment]
We eventually need to add this lock back for a real image garbage collection on building our own internal reference to a image. But I am ok to remove it now for the sake of code readability. LGTM.

**Comment by vmarmol** [comment]
Agree @dchen1107. Self-merging since it's green.

**Comment by wojtek-t** [comment]
Thanks for this change @vmarmol

**Pull request merged**
