### PR TITLE
fix some spelling error

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Thanks for this fix :)

**Comment by mysunshine92** [comment]
ping @sig-cli-maintainers

**Comment by mysunshine92** [comment]
ping @yujuhong

**Comment by mysunshine92** [comment]
ping @vishh

**Comment by mysunshine92** [comment]
cc @vishh 
please add an approved label,thanks.

**Pull request merged**
