### PR TITLE
Fix detection of docker cgroup on RHEL

### PR DESCRIPTION
**Pull request by ncdc**
Check docker's pid file, then fallback to pidof when trying to determine the pid for docker. The
latest docker RPM for RHEL changes /usr/bin/docker from an executable to a shell script (to support
/usr/bin/docker-current and /usr/bin/docker-latest). The pidof check for docker fails in this case,
so we check /var/run/docker.pid first (the default location), and fallback to pidof if that fails.

@kubernetes/sig-node @kubernetes/rh-cluster-infra

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM.

/cc @vishh - we need to ensure that the unit for `docker.service` on systemd machines has Memory and CPU accounting enabled per here: https://github.com/kubernetes/kubernetes/pull/17688#issuecomment-220447268

otherwise, runtime stats are not accurate for docker runtime (it will default to / as the cgroup).

**Comment by derekwaynecarr** [comment]
Fore reference:
https://access.redhat.com/solutions/907283

**Comment by dchen1107** [comment]
LGTM Thanks for fixing this.

**Comment by vishh** [comment]
LGTM. @derekwaynecarr If metrics are not available, we will be returning `0` value today I think.

**Comment by derekwaynecarr** [comment]
Today it returns runtime stats for root cgroup.  Confirmed today.

**Pull request merged**
