### PR TITLE
Test whether auto-generated conversions weren't manually edited

### PR DESCRIPTION
**Pull request by wojtek-t**
Part of #6800 

cc @smarterclayton @lavalamp @fgrzadkowski

### CODE REVIEW

**Comment by wojtek-t** [comment]
Note: Please do NOT merge #7556 and this PR at the same time - they need to be rebased before merging the other one.

**Comment by smarterclayton** [comment]
Can this be merged first?

**Comment by wojtek-t** [comment]
>
Can this be merged first?

Yes - any order is fine

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
