### PR TITLE
Log more verbose when DisruptionController doesn't start.

### PR DESCRIPTION
**Pull request by mml**
To help with debugging #45706

### CODE REVIEW

**Comment by deads2k** [comment]
> To help with debugging #45706

As a general API point, would it be better if the init function returned a `(string, error)` so you could return back a structured message to display in the warning?

**Comment by mml** [comment]
> As a general API point, would it be better if the init function returned a (string, error) so you could return back a structured message to display in the warning?

Are you talking about `func startDisruptionController(ctx ControllerContext) (bool, error)`?  Not sure which `init` you mean.

**Comment by deads2k** [comment]
> Are you talking about func startDisruptionController(ctx ControllerContext) (bool, error)? Not sure which init you mean.

Yeah, that conforms to an interface.

**Comment by mml** [comment]
@deads2k Sorry, got sidetracked from this PR.  I don't feel strongly one way or the other.  I think it's OK for the init function to just do its own logging for the moment, and it would also be OK if it returned the string.  But in that case the same exact thing is going to happen: it gets glog'd.  Downside is we're limited to a single line and no diagnostics around that line that might explain how we got to that part of the logic.

So actually I think we're better off this way.

**Comment by deads2k** [comment]
> So actually I think we're better off this way.

I disagree, but I'm not prepared to wire new plumbing at the moment.

/lgtm

**Comment by mml** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
