### PR TITLE
Revert "Avoid mounting ssl volumes for heapster container."

### PR DESCRIPTION
**Pull request by piosz**
This reverts commit c08ad6b7c1076e7a7f70aa9dd5774866bf59b406.

### CODE REVIEW

**Comment by vishh** [comment]
LGTM. Can you make this change in heapster repo as well?

**Comment by piosz** [comment]
The Heapster is crashlooping when monitoring level is set to google. Unfortunately https://github.com/GoogleCloudPlatform/heapster/pull/382 is not fixed. Sorry for confusion in #11998.

@dchen1107 @mikedanese

**Comment by piosz** [comment]
Sure. I'll do it

**Comment by mikedanese** [comment]
Thanks. I'm looking into it.

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
