### PR TITLE
Modify some error words

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm
/approve

**Comment by pacoxu** [comment]
/remove-lifecycle stale
/approve
typo fix
/assign @smarterclayton

**Pull request merged**
