### PR TITLE
approval from any sig to merge change in .golint_failures and other dot files

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

There are lists in this folder that are intended to track compliant components. PRs fixing code compliance in specific folder needs two approvals - one from component owner and another from the `hack` folder owner. It is unnecessary slowdown for PRs like these: https://github.com/kubernetes/kubernetes/pull/91867 https://github.com/kubernetes/kubernetes/pull/91970 https://github.com/kubernetes/kubernetes/pull/91181

**Which issue(s) this PR fixes**:

Fixes # NONE

**Special notes for your reviewer**:

I copied all `foo-approvers` and `foo-reviewers` from `OWNERS_ALIASES`. Didin't copy `foo-maintainers`.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold

So many things could go wrong since this approval is not just for .golint_failures ... i'd be happy to be pinged on .golint_failures changes

**Comment by SergeyKanzhelev** [comment]
@dims I moved it to separate subfolder. So this subfolder can hold lists only. Just want to make your life easier =)

**Comment by SergeyKanzhelev** [comment]
fell free to close the PR if you don't think it's a good idea. I thought I'd submit a PR to explain the idea - faster than explaining it in the issue.

**Comment by dims** [comment]
@SergeyKanzhelev no worries. we should probably find a better name than `lists` :) and we should probably move all the `.` files too? (need to think this through, just a quick feedback for now)

**Comment by SergeyKanzhelev** [comment]
updated. LMK if the name `.hack-components` for the folder works. It stutters a bit `hack/.hack_components`, but I think looks better than `lists`.

**Comment by SergeyKanzhelev** [comment]
@dims so what do you think?

**Pull request closed without merging**
