### PR TITLE
[minor] E2e lib minimal minor cleanup

### PR DESCRIPTION
**Pull request by jayunit100**
Please **IGNORE THIS UNTIL AFTER #19476 MERGES** 

cc @ixdy .

For efficiency I've bundled some other nits in here.

### CODE REVIEW

**Comment by ixdy** [comment]
Given that the merge queue is backed up, maybe just merge this into ##19476?

I'd originally hoped to get #19476 merged quickly so you could iterate, but that's clearly not happening...

**Comment by ixdy** [comment]
Er, by #19476 I really mean #19624.

**Comment by jayunit100** [comment]
sure . good idea

**Comment by jayunit100** [comment]
PERMANANTLY CLOSED :) .

**Pull request closed without merging**
