### PR TITLE
Add kube2sky  parameter kube-master-url  the k8 master api

### PR DESCRIPTION
**Pull request by cclient**

### CODE REVIEW

**Comment by luxas** [comment]
The master is automatically found by using `ServiceAccounts`, sorry

**Comment by thockin** [comment]
This flag is not needed in the general case of having service accounts working properly.

**Comment by thockin** [comment]
Thanks for the PR, though. :)  I didn't mean to be rude..

**Comment by testark** [comment]
@thockin I believe I have service accounts working, as I have set up the cluster according to the manual, but I'm facing the same problem here—I had to manually provide `--kube-master-url` in `skydns-rc.yaml` because `kube2sky` wasn't starting otherwise. This was what I was getting:

```
I0515 22:50:29.085545       1 kube2sky.go:456] [Attempt: 1] Attempting access to etcd after 5 second sleep
I0515 22:50:34.092326       1 kube2sky.go:462] Etcd server found: http://127.0.0.1:4001
E0515 22:50:35.094389       1 config.go:239] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I0515 22:50:35.094466       1 kube2sky.go:529] Using https://10.254.0.1:443 for kubernetes master
I0515 22:50:35.094475       1 kube2sky.go:530] Using kubernetes API <nil>
I0515 22:50:35.094672       1 kube2sky.go:598] Waiting for service: default/kubernetes
I0515 22:50:35.097261       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.
I0515 22:50:36.099457       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.
I0515 22:50:37.101580       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.
```

I'm fairly new to Kubernetes, though, so I would like to ask whether I am overlooking something here.

**Comment by thockin** [comment]
Did you follow this:

https://github.com/GoogleCloudPlatform/kubernetes/issues/10265#issuecomment-117267504

**Pull request closed without merging**
