### PR TITLE
NodeName should stay in k8s

### PR DESCRIPTION
**Pull request by justinsb**
It is specific to the k8s API, not part of our generic apiserver

```release-note
NONE
```

### CODE REVIEW

**Comment by justinsb** [comment]
@lavalamp or @liggitt 

While I slog through this refactor, do you agree that types.NodeName should not be in apimachinery?   I believe it is tightly associated with a k8s Node, so moving it into apimachinery would be like moving `Node` into apimachinery.

Is that right?

**Comment by justinsb** [comment]
Actually @deads2k it looks like you're also involved in the great reshuffle?  Can you comment on whether NodeName should stay?

**Comment by deads2k** [comment]
> Actually @deads2k it looks like you're also involved in the great reshuffle? Can you comment on whether NodeName should stay?

I agree that it doesn't belong in API machinery.  It was in a package that got pulled in via fanout primariliy for `.UID`.  Moving this back makes sense.  It probably belongs in `pkg/api` or thereabouts.

**Comment by lavalamp** [comment]
Yeah NodeName probably belongs in the same place that Node is defined.

**Comment by wojtek-t** [comment]
@justinsb @lavalamp - are we going to proceed with this PR?

**Pull request closed without merging**
