### PR TITLE
Automated cherry pick of #82624: Upgrade stackdriver-logging-agent image to 1.6.17 to fix

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #82624 on release-1.13.

#82624: Upgrade stackdriver-logging-agent image to 1.6.17 to fix

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
/release-note-none
as per parent PR

**Review by jszczepkowski — APPROVED** [review]
LGTM

**Comment by qingling128** [comment]
@bowei @yujuhong @tpepper @mwielgus - Anyone knows if the `pull-kubernetes-e2e-gce-device-plugin-gpu` test was broken on 1.13 branch? I thought it was a flaky test. But after retrying multiple times, it's still failing.

**Comment by yujuhong** [comment]
> @bowei @yujuhong @tpepper @mwielgus - Anyone knows if the `pull-kubernetes-e2e-gce-device-plugin-gpu` test was broken on 1.13 branch? I thought it was a flaky test. But after retrying multiple times, it's still failing.

The test job is not "required", so you can ignore the failure.

**Comment by qingling128** [comment]
@yujuhong Good to know. How can I get this merged then?

**Comment by yujuhong** [comment]
You need a package owner to approve the PR, and a patch release manager to approve the cherrypick.

**Comment by yujuhong** [comment]
Applying the approval label based on https://github.com/kubernetes/kubernetes/pull/82894#pullrequestreview-290994983

**Comment by yujuhong** [comment]
@kubernetes/patch-release-team 
for approval

**Comment by qingling128** [comment]
Hmm... Why does this PR still request:

```
Needs approval from an approver in each of these files:
cluster/gce/OWNERS
```

after @jszczepkowski approved it? Am I missing anything?

Also, how can I figure out who is on the `kubernetes/patch-release-team`? The @kubernetes/patch-release-team link returns 404.

I found this page https://github.com/kubernetes/sig-release/blob/master/releases/release-1.13/release_team.md that says:

```
Patch Release Managers | Aleksandra Malinowska (@aleksandra-malinowska), Tim Pepper (@tpepper)
```

@tpepper @aleksandra-malinowska Could any of you help with this one?

**Comment by idealhack** [comment]
@qingling128 

1. I guess that's because GitHub approvals like https://github.com/kubernetes/kubernetes/pull/82894#pullrequestreview-290994983 do not count as GitHub events. However, if you write `/approve` or `/lgtm`, it does count like normal comments?

2. The page of a GitHub team is only available to org members, which you can apply to join by following https://git.k8s.io/community/community-membership.md

3. The up-to-date information about patch releases and patch release team is at https://git.k8s.io/sig-release//releases/patch-releases.md and https://git.k8s.io/sig-release/release-managers.md#patch-release-team

**Comment by qingling128** [comment]
Thanks @idealhack ! That's very helpful info.

Hi @jszczepkowski - Could you help approve this one again with `/lgtm` and `/approve`? The bot did not pick up the previous comment at https://github.com/kubernetes/kubernetes/pull/82894#pullrequestreview-290994983.

**Comment by qingling128** [comment]
@tpepper - Friendly ping?

**Pull request merged**
