### PR TITLE
Fix the bullet list is broken by white space normalization

### PR DESCRIPTION
**Pull request by resouer**
**What this PR does / why we need it**:

The bullet list is broken since sig-azure, which makes the  CHANGELOG-1.12.md look very wired ...

**Special notes for your reviewer**:

**Release note**:
-->
```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
@lathama I am not very sure if it's right way to fix typo CHANGELOG, please let me know if there's other process.

**Comment by lathama** [comment]
@resouer my change to CHANGELOG took 40+ days so don't get in any hurry. I would update your description to mention "white space normalization" or "correct white spacing"

**Comment by resouer** [comment]
@lathama Just fixed the description.

**Comment by lathama** [comment]
@nikhita this is an easy win if you have a moment

@resouer I do not have the rights to approve or review, for that list please see https://github.com/kubernetes/kubernetes/blob/master/OWNERS

**Comment by nikhita** [comment]
/sig release
/kind cleanup

/lgtm
/cc @nickchase @marpaia 

/hold
I don't think this really deserves a release note. @resouer Can you remove the release note? Feel free to remove the hold after that.

**Comment by nikhita** [comment]
/assign @thockin 
for approval

**Comment by nikhita** [comment]
/lgtm cancel

Looks like https://github.com/kubernetes/kubernetes/pull/69199 is a similar PR but has some other fixes as well. I'll let the release team tag the labels.

**Comment by lathama** [comment]
@resouer it appears that 69199 proceeds and covers this fix. You can likely close this and watch that issue.

**Pull request closed without merging**
