### PR TITLE
Include BGPConfiguration

### PR DESCRIPTION
**Pull request by satyasm**
Needed for calico 2.x to 3.x upgrade.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Cherry pick PR #71868  into 1.12 branch

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Include CRD for BGPConfigurations, needed for calico 2.x to 3.x upgrade.
```

### CODE REVIEW

**Comment by satyasm** [comment]
/assign @caseydavenport 
/cc @jingax10 

Cherrypick into 1.12 branch, needs ok-to-test

**Comment by satyasm** [comment]
/assign @tpepper 

@tpepper can you help approve this for 1.12 branch?

**Comment by feiskyer** [comment]
cherry pick approved

**Pull request merged**
