### PR TITLE
refactor: move configurations for leader migration.

### PR DESCRIPTION
**Pull request by jiahuif**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR moves all configurations for Leader Migration to a separate group `leadermigration.config.k8s.io` because they do not fit in `controllermanager.config.k8s.io`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190422-cloud-controller-manager-migration.md
```

/sig cloud-provider
/priority important-soon

### CODE REVIEW

**Comment by jiahuif** [comment]
@lavalamp Would you approve changes under `api` and `build`? Other changes are about cloud provider.
 
Summary: 
- There is one less exception in `api/api-rules/violation_exceptions.list`, due to the violation being resolved.
- There is one new package created in `build/kazel_generated.bzl`

**Comment by jiahuif** [comment]
/assign @lavalamp Would you approve changes under `api` and `build`? Other changes are about cloud provider.
 
Summary: 
- There is one less exception in `api/api-rules/violation_exceptions.list`, due to the violation being resolved.
- There is one new package created in `build/kazel_generated.bzl`

**Comment by jiahuif** [comment]
/assign @lavalamp 
Would you approve changes under `api` and `build`? Other changes are about cloud provider.
 
Summary: 
- There is one less exception in `api/api-rules/violation_exceptions.list`, due to the violation being resolved.
- There is one new package created in `build/kazel_generated.bzl`

**Comment by jiahuif** [comment]
/assign @liggitt 
Could you review the change under `api`? There is one less exception in api/api-rules/violation_exceptions.list, due to the violation being resolved.

Thank you very much!

**Comment by jiahuif** [comment]
/assign @BenTheElder 
Could you take a look at the change under `build/`? There is one new package created in `build/kazel_generated.bzl`.

Thank  you very much!

**Comment by BenTheElder** [comment]
I will defer to @liggitt 🙃

**Comment by jiahuif** [comment]
/close
closing in favor of 96133

**Pull request closed without merging**
