### PR TITLE
add unit test for /staging/src/k8s.io/kubectl/pkg/util/fieldpath

### PR DESCRIPTION
**Pull request by zhoumingcheng**
Signed-off-by: zhoumingcheng <zhoumingcheng@beyondcent.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
add unit test for /staging/src/k8s.io/kubectl/pkg/util/fieldpath
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Thank you！
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ardaguclu** [comment]
Thanks for these unit tests @zhoumingcheng 

/ok-to-test

**Comment by ardaguclu** [comment]
@zhoumingcheng pull-kubernetes-verify failure is real

**Comment by zhoumingcheng** [comment]
> @zhoumingcheng pull-kubernetes-verify failure is real

thanks

**Comment by ardaguclu** [comment]
That looks good to me;

/lgtm

**Comment by brianpursley** [comment]
So first of all, there is a TODO comment saying this package should be moved to apimachinery, but it is 4 years old, so I'm guessing that might never happen.  
https://github.com/kubernetes/kubernetes/blob/27dc8a9b631240b4e96956ee6545714f25347a7c/staging/src/k8s.io/kubectl/pkg/util/fieldpath/fieldpath.go#L28

Second, I see there is already a test file for the other copy of this file, located here: [pkg/fieldpath/fieldpath_test.go](https://github.com/kubernetes/kubernetes/blob/40f3f3bd0e086f935f7ae617bf77ba5d5a16d630/pkg/fieldpath/fieldpath_test.go)

I think it might make sense to just copy this test file over to kubectl's copy of fieldpath instead of writing new, different tests.  Thoughts?

**Comment by brianpursley** [comment]
@zhoumingcheng thank for you the tests by the way, we always need more tests.

If there are cases you identified that should be included, I think it would be good to include them both in this copy of fieldpath_test.go and also in the copy located at [pkg/fieldpath/fieldpath_test.go](https://github.com/kubernetes/kubernetes/blob/40f3f3bd0e086f935f7ae617bf77ba5d5a16d630/pkg/fieldpath/fieldpath_test.go)

To rephrase my previous comment, I think both copies should be kept in sync, but if there are more test cases to be added, that is good

**Comment by brianpursley** [comment]
This is probably yak shaving, but does it make sense to go ahead and do what they TODO comment says and move this (and the associated unit tests) to apimachinery?  I wonder how many dependencies would need to be updated?

**Comment by zhoumingcheng** [comment]
> This is probably yak shaving, but does it make sense to go ahead and do what they TODO comment says and move this (and the associated unit tests) to apimachinery? I wonder how many dependencies would need to be updated?

thanks，I think maybe the unit test here is redundant, so I will turn off this pr.

**Pull request closed without merging**
