### PR TITLE
gce: extend CLOBBER_CONFIG to support known_tokens.csv

### PR DESCRIPTION
**Pull request by mikedanese**
Helps with #49895

### CODE REVIEW

**Comment by cjcullen** [comment]
@liggitt FYI

**Comment by cjcullen** [comment]
I think it is reasonable to extend the meaning of the recently introduced `METADATA_CLOBBERS_CONFIG` variable to include the tokens file.

**Comment by liggitt** [comment]
Sure, the concern was always about things depending on existing on disk config. If metadata is authoritative, it's authoritative.

**Pull request merged**
