### PR TITLE
fabiano no longer a thing

### PR DESCRIPTION
**Pull request by fabianofranz**
**What this PR does / why we need it**: Removes me from lists of reviewers and approvers.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@pwittrock @kubernetes/sig-cli-misc

**Comment by pwittrock** [comment]
Thanks for cleaning up @fabianofranz

**Comment by fabianofranz** [comment]
@bgrant0607 for approval.

**Pull request merged**
