### PR TITLE
Automated cherry pick of #95150: DNS should support configurable pod

### PR DESCRIPTION
**Pull request by chewong**
Cherry pick of #95150 on release-1.19.

#95150: DNS should support configurable pod

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

ref: #99369

### CODE REVIEW

**Comment by jsturtevant** [comment]
thanks! Any idea why it just started failing on 2/19?

**Comment by chewong** [comment]
> thanks! Any idea why it just started failing on 2/19?

Looks like it's caused by https://github.com/kubernetes/kubernetes/pull/99220.

**Comment by jsturtevant** [comment]
@kubernetes/release-managers could you take a look at this cherry-pick for a sig-windows only test that started failing due to https://github.com/kubernetes/kubernetes/pull/99220 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-19-windows-containerd/1366493930933194752

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
