### PR TITLE
Updating kubectl expose to extract ports from the service being cloned

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/11392

Running:

```
$ kubectl.sh expose service frontend --name=frontend2
```

Before:

```
error: couldn't find port via --port flag or introspection: cannot extract ports from Service
see 'kubectl expose -h' for help.
```

Now creates the service.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
So the error message was fine?

**Comment by bgrant0607** [comment]
Nevermind. Saw the other PR.

**Comment by jlowdermilk** [comment]
Needs rebase, but LGTM.

**Comment by nikhiljindal** [comment]
Rebased

**Comment by nikhiljindal** [comment]
Rebased

**Comment by bgrant0607** [comment]
TestTokenCreation failed in both builds. Is that failing in head?

**Comment by nikhiljindal** [comment]
Yes https://github.com/GoogleCloudPlatform/kubernetes/pull/11705 is fixing it

**Comment by vishh** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test.
Shippable's second run passed. The first one timed out. Rerunning.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@nikhiljindal please rebase to fix shippable

**Comment by nikhiljindal** [comment]
Rebased

**Pull request merged**
