### PR TITLE
fix: typo in the log

### PR DESCRIPTION
**Pull request by weizhoublue**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
some spelling error in the log

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Namanl2001 — APPROVED** [review]
/lgtm

Thanks!

**Comment by weizhoublue** [comment]
rebase the main branch and fix the conflict

**Comment by ibihim** [comment]
Thanks for your pull request.  However, [trivial](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) changes like this should be avoided as we have very limited resources to handle reviews and approvals.  Focus efforts on fixes that have meaningful impact on end users (bugs, docs, etc).

/close

**Pull request closed without merging**
