### PR TITLE
GCE Windows: Only create NPD kubeconfig when the file path is defined.

### PR DESCRIPTION
**Pull request by jeremyje**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
GCE Windows nodes may fail to come up if the kubeconfig file path for NPD is not defined. This should not be required for 1.22 yet.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig windows
/priority important-soon
/triage accepted

### CODE REVIEW

**Comment by jeremyje** [comment]
/hold
Fix is being validated.

**Review by mcshooter — APPROVED** [review]
lgtm

**Review by ibabou — APPROVED** [review]

**Pull request merged**
