### PR TITLE
Fix handling lists in kubectl convert

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes https://github.com/kubernetes/kubernetes/issues/36722

When handling multiple objects in `kubectl convert` (for example in `kubectl convert -f .` with multiple files in current directory) the objects must be managed as a list instead of individually, otherwise `-o yaml|json` will generate invalid format (just multiple json/yaml objects concatenated) which can't be fed to `kubectl create` like in `kubectl convert -f . | kubectl create -f -`.

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36603)

### CODE REVIEW

**Comment by fabianofranz** [comment]
@metral ptal?

**Comment by fabianofranz** [comment]
@k8s-bot verify test this

**Comment by metral** [comment]
LGTM 👍

**Comment by pwittrock** [comment]
@fabianofranz We are in feature freeze mode so we should be clear that this is about fixing a bug.  I know it is a pain, but would you create an issue to reference and update the description to indicate that this is a bug-fix.

@saad-ali FYI

**Comment by saad-ali** [comment]
> @fabianofranz We are in feature freeze mode so we should be clear that this is about fixing a bug. I know it is a pain, but would you create an issue to reference and update the description to indicate that this is a bug-fix.
> @saad-ali FYI

Thanks @pwittrock

**Comment by fabianofranz** [comment]
>  would you create an issue to reference and update the description to indicate that this is a bug-fix

@pwittrock absolutely, issue created and referenced in the PR description. tks!

**Pull request merged**
