### PR TITLE
restart pod when probe error

### PR DESCRIPTION
**Pull request by jiangyaoguo**

### CODE REVIEW

**Comment by mikedanese** [comment]
Probe error != unhealthy. I don't think this is correct....

**Comment by timstclair** [comment]
Yes, I agree with what @mikedanese said. Also, this logic is getting removed in https://github.com/kubernetes/kubernetes/pull/15275, which should land soon.

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by jiangyaoguo** [comment]
@mikedanese When error occurs, should we do nothing? Usually Probe return error with status Probe.failure or Probe.Unknown. I see @timstclair left a TODO to handle error. What are we going to do to handle error?

**Comment by timstclair** [comment]
Yes. A probe error should indicate a problem in the kubelet, not the probed container. We don't want to restart the container in this case, so in my implementation I leave the state unchanged (whatever the last non-error probe returned). My TODO was more for moving the logging out of the prober component.

**Comment by jiangyaoguo** [comment]
should we log this error at least？

**Comment by timstclair** [comment]
We already log the error in the prober: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L99

**Comment by jiangyaoguo** [comment]
I see your point. Since your pr is coming，I'll close this.

**Pull request closed without merging**
