### PR TITLE
update azure_pulibipclient log

### PR DESCRIPTION
**Pull request by lovebaby979**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
update azure_publicipclient info log
```

### CODE REVIEW

**Comment by nilo19** [comment]
the legacy cloud provider in k/k only allows bug fixes now, could you please do it in the out-of-tree cloud provider azure repo?

**Comment by feiskyer** [comment]
let's avoid changing legacy codes since it is not a bug fix.

/close

**Pull request closed without merging**
