### PR TITLE
Convert - to _ for protobuf package names

### PR DESCRIPTION
**Pull request by ncdc**
Convert - to _ for protobuf package names to allow protobuf code generation
support for go packages that have - in their names.

@smarterclayton @deads2k @liggitt @sttts @lavalamp @nikhiljindal @kubernetes/sig-api-machinery

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35432)

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Comment by sttts** [comment]
lgtm

**Comment by smarterclayton** [comment]
Did you verify the imports worked correctly during generation?  That was the blocker before.

**Comment by smarterclayton** [comment]
You may have to change the generator to add additional include directories to the invocation of `protoc` - otherwise protoc can't find those relative files.  Before we merge this you'll need to test it against a new group.

**Comment by ncdc** [comment]
I will verify and report back

**Comment by ncdc** [comment]
I used this patch to update the proto files in openshift/kube-projects [here](https://github.com/openshift/kube-projects/pull/9/commits/510f3be1a41e9c31d56d1fa494fdf42674e792b6) and it generated without error.

**Comment by smarterclayton** [comment]
It may be that import of that package breaks, but we'll see.  In the
meantime, LGTM.

**Comment by ncdc** [comment]
Upstream gengo PR: https://github.com/kubernetes/gengo/pull/16

**Comment by ncdc** [comment]
Reapplying lgtm as the changes were a rebase to head and updates for bazel and test owners.

**Comment by ncdc** [comment]
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35432/pull-kubernetes-e2e-gce-etcd3/1826/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:158
Oct 28 08:29:48.020: Failed to setup provider config: Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError
```

@k8s-bot gce etcd3 e2e test this

**Pull request merged**
