### PR TITLE
Start running v1 tests on travis and shippable

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
LGTM. Thanks!

**Comment by bgrant0607** [comment]
Encountered a flaky test. Rerunning tests.

**Comment by bgrant0607** [comment]
Tests passed

**Comment by nikhiljindal** [comment]
@krousey Can I haz a merge, please?

**Pull request merged**
