### PR TITLE
[go1.16] Update to go1.16.8

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng security

#### What this PR does / why we need it:

Update Kubernetes to go1.16.8 for release 1.22 branch

Tracking issue: https://github.com/kubernetes/release/issues/2238

/assign @dims @liggitt @justaugustus 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.16.8
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
/assign @dims @liggitt @justaugustus
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
The bots are having one today...
/area dependency release-eng security

**Comment by justaugustus** [comment]
> hmm good call!, looks like we need to build one image for 1.21
> 
> @justaugustus summoning you here to double-check this, if that is needed I will work on that right away

The image content will effectively be the same, but yes, let's do this for consistency with the branch name/release version (as that was the reason for the tag nomenclature change).

**Comment by cpanato** [comment]
> > hmm good call!, looks like we need to build one image for 1.21
> > @justaugustus summoning you here to double-check this, if that is needed I will work on that right away
> 
> The image content will effectively be the same, but yes, let's do this for consistency with the branch name/release version (as that was the reason for the tag nomenclature change).

will start on those now! and will do the same for 1.19/1.20 as well

**Comment by justaugustus** [comment]
> will do the same for 1.19/1.20 as well

I'd hold off on 1.19/1.20. They're using an unsupported version of Golang (go1.15.15), so I don't expect updates to them anytime soon.

**Pull request merged**
