### PR TITLE
expose: Re-use labels in case none was specified

### PR DESCRIPTION
**Pull request by 0xmichalis**
Forked from #7765

cc: @jlowdermilk @bgrant0607

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Is `hack/verify-gendocs.sh` passing for you? Shippable is still complaining about gendoc differences.

**Comment by bgrant0607** [comment]
Maybe rebase?

**Comment by kargakis** [comment]
I regenerated the docs and rebased on top of the current master, hope it'll be fine now.

**Comment by kargakis** [comment]
Btw `hack/verify-gendocs.sh` is not complaining on me.

**Comment by jlowdermilk** [comment]
From shippable:
```
--- FAIL: TestRunExposeService (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47f520]
```

Are you able to repro that failure locally with `hack/test-go.sh`?

**Comment by kargakis** [comment]
I was. Now it's fixed.

**Comment by jlowdermilk** [comment]
LGTM. Shippable is green, so merging.

**Pull request merged**
