### PR TITLE
Stop putting env vars into BoundPods.

### PR DESCRIPTION
**Pull request by erictune**
They will still show up in etcd.  They never were available
through the API.

A subsequent PR(s) will rip out all BoundPods code.
Working in small increments.

This PR will cause users on lagging cloud providers
to not get env vars in their pods if they update to this code.
They have already been warned via email.

Removed unit tests of BasicBoundPodFactory.
There is adequate coverage in pkg/kubelet/kubelet_test.go.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

So nice.

**Comment by thockin** [comment]
Do the Red Hat folks have concerns?

@smarterclayton

**Comment by smarterclayton** [comment]
None.

**Comment by erictune** [comment]
not sure why  integration test failed on go1.4 on travis.  Works for me and shippable and travis+1.3

**Comment by saad-ali** [comment]
@erictune Could you rebase please

**Comment by erictune** [comment]
@saad-ali rebased

**Comment by zmerlynn** [comment]
Does this close #4176?

**Comment by erictune** [comment]
no

**Comment by erictune** [comment]
and by "no" I mean yes.

**Pull request merged**
