### PR TITLE
Update npd from v0.8.19 to v0.8.20

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
[npd-release-0.8.20](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.20)
#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
cc @pacoxu @dims

**Comment by pacoxu** [comment]
Check the testgrid https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci once this is merged.

**Comment by kannon92** [comment]
Adding a lgtm since dim has already approved.

/lgtm

**Pull request merged**
