### PR TITLE
daemon not deamon

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
daemon not deamon

### CODE REVIEW

**Comment by jbeda** [comment]
@k8s-bot ok to test
/lgtm
/approve

**Comment by jbeda** [comment]
@k8s-bot unit test this
@k8s-bot kubemark e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by jbeda** [comment]
@timchenxiaoyu If you could batch changes like this in to a single PR it would help relieve some pressure on our test infrastructure and make it easier to review.

**Comment by timchenxiaoyu** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
