### PR TITLE
Change some code place to void useless caller

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Change some code place to void useless caller

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
@k82cn  PTAL thanks.

**Comment by cwdsuzhou** [comment]
gentle ping @k82cn

**Comment by k82cn** [comment]
thanks for the contribution :)

**Pull request merged**
