### PR TITLE
Switch to the documented json-patch module

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

json-patch 5.6.0 is available as a properly-defined module; the documented name for the module is gopkg.in/evanphx/json-patch.v5. This switches from github.com/evanphx/json-patch to that.

For now this duplicates the module in vendor; the old module will go away once kustomize is updated in the same way (https://github.com/kubernetes-sigs/kustomize/pull/5197).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@skitt can it wait till we bring in kustomize?

**Comment by skitt** [comment]
> @skitt can it wait till we bring in kustomize?

Of course!

**Comment by neolit123** [comment]
note bumping to v5 was already attempted >=2 times
https://github.com/kubernetes/kubernetes/pull/113092#issuecomment-1282320927

**Comment by skitt** [comment]
> note bumping to v5 was already attempted >=2 times [#113092 (comment)](https://github.com/kubernetes/kubernetes/pull/113092#issuecomment-1282320927) [#113092 (comment)](https://github.com/kubernetes/kubernetes/pull/113092#issuecomment-1285866437)

@neolit123 and it was done with https://github.com/kubernetes/kubernetes/pull/118384 (perhaps unintentionally).

**Comment by skitt** [comment]
The kustomize PR has been merged; this will need a bump to the next release of `kustomize/api` and `kustomize/kustomize/v5` once they’re published, to actually get rid of the old `json-patch` in `vendor`. (As of today, the resulting overall stats are 1335 insertions and 571 deletions.)

**Pull request closed without merging**
