### PR TITLE
Revert resource limits priority function

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Revert limits priority function for 1.13
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/70592

**Review by bsalamat — APPROVED** [review]
/lgtm

Thanks, @ravisantoshgudimetla !

**Comment by AishSundar** [comment]
Thanks @ravisantoshgudimetla @bsalamat

**Comment by AishSundar** [comment]
@ravisantoshgudimetla @bsalamat who can help add the approved label?

**Pull request merged**
