### PR TITLE
[Do Not Merge] Test CoreDNS image 1.3.0

### PR DESCRIPTION
**Pull request by rajansandeep**
**What this PR does / why we need it**:
Test CoreDNS version 1.3.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
No review required. Test PR only.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/hold

### CODE REVIEW

**Review by timothysc — CHANGES_REQUESTED** [review]
needs the kubeadm changes too.

**Comment by chrisohaver** [comment]
@rajansandeep, can you close this PR?

**Pull request closed without merging**
