### PR TITLE
OWNERS_ALIASES/sig-scheduling: move adtac to emeritus list

### PR DESCRIPTION
**Pull request by adtac**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Hi everyone, my commitments have recently changed, so I think now is a good time to move myself off the SIG scheduling reviewers list. However, I'll still be working on Kubernetes-related things, so always feel free to ping me on slack for anything :)

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

cc @ahg-g @alculquicondor @Huang-Wei 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig scheduling

### CODE REVIEW

**Comment by alculquicondor** [comment]
/approve

Thanks a lot for all your contributions @adtac!

**Comment by Huang-Wei** [comment]
Thanks @adtac for your contributions! I hope our paths cross again in the future.

**Comment by pacoxu** [comment]
close per  #107076
/close

**Pull request closed without merging**
