### PR TITLE
doc: fix typo in cluster

### PR DESCRIPTION
**Pull request by halfcrazy**
**What this PR does / why we need it**:
fix typo in cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by halfcrazy** [comment]
ok-to-test?

**Comment by coffeepac** [comment]
@halfcrazy we need to get someone from the clusters/OWNERS file to approve.  PR is g2g otherwise.

**Comment by coffeepac** [comment]
thanks @jbeda !

**Pull request merged**
