### PR TITLE
Make socket address parsing work on FreeBSD.

### PR DESCRIPTION
**Pull request by EdSchouten**
**What this PR does / why we need it**:

I am currently in the process of porting Kubernetes to work on FreeBSD. What is interesting is that I am not interested in using Kubernetes to run Docker containers in this case. I happen to be the author of CloudABI, a sandboxing framework that is available on FreeBSD (and other systems). I want to have a cluster management tool for scheduling these sandboxed processes.

Anyway, right now `kubelet` crashes on startup when passing in CRI command line flags, for the reason that it's not able to parse `unix:...` socket addresses. This change fixes this by making the respective Linux-only source file work on FreeBSD as well.

### CODE REVIEW

**Comment by brendandburns** [comment]
/approve no-issue

Needs a rebase.

**Comment by EdSchouten** [comment]
I suspect this may be a transient issue, unrelated to the change at hand?
/retest

**Pull request merged**
