### PR TITLE
Fixed code issues related to hasty test refactor

### PR DESCRIPTION
**Pull request by markturansky**
@saad-ali

### CODE REVIEW

**Comment by markturansky** [comment]
@erictune 

sorry for the hasty refactor.  just trying to get this flake put to bed and got sloppy.

**Comment by saad-ali** [comment]
This fails with:
```
# k8s.io/kubernetes/test/integration
_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:119: watch.Deleted undefined (type watch.Interface has no field or method Deleted)
FAIL	k8s.io/kubernetes/test/integration [build failed]
!!! Error in /usr/local/google/home/saadali/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/test-go.sh:217
  'return ${rc}' exited with status 2
```

**Comment by markturansky** [comment]
Yes, i'm on it

**Comment by markturansky** [comment]
Sorry for the confusion.  integration tests compiling and running locally.  the latest commit should fix all.

**Comment by saad-ali** [comment]
Thanks @markturansky 
Could you squash the changes.
We'll merge on green

**Comment by saad-ali** [comment]
Oh ya, and LGTM

**Comment by markturansky** [comment]
squashed.

**Comment by saad-ali** [comment]
Since it's passing locally, I'm going to manually merge to stop the bleeding.

**Comment by markturansky** [comment]
I saw a Go 1.3 error in Shippable but it was unrelated to PV.  It was a different flake.

**Comment by saad-ali** [comment]
Our Jenkins build shows green after this was merged, so looking good.

**Pull request merged**
