### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by mmaquevice**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by coffeepac** [comment]
I think the github instability knocked the labels a bit sideways here.  going to see if I can sheperd it along.

**Comment by coffeepac** [comment]
@crassirostris any idea how to get rid of the do-not-merge label?  no other informational labels and all other CI tests pass

**Comment by crassirostris** [comment]
@coffeepac No idea, but everything seems good to me, so removing the label. Probably that's b/c I lgtm'd without applying ok-to-test first

**Pull request merged**
