### PR TITLE
dependencies: bump CSI to v1.6.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The main difference is that GetCapacityResponse.MaximumVolumeSize is no longer
marked as "alpha". Technically this does not make a difference.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Rebased because of a conflict in vendor/modules.txt.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
