### PR TITLE
e2e: Specify RestartPolicy=Never in empty_dir test

### LINKED ISSUE #8745: e2e test for tmpfs must specify RestartPolicy: RestartPolicyNever
In test/e2e/empty_dir.go, we run a pod that basically runs once and logs status about the mounts, which we then validate.

In the test, we start the pod, wait for it to exit, and then get the logs.

But, we don't specify a restart policy.  The default is restart always.  So it will keep restarting.  So testContainerOutputInNamespace, which calls waitForPodSuccessInNamespace, will never exit: `ci.State.Termination` will be nil, though `ci.LastTerminationState.Termination` is getting set.

I will propose a PR that sets RestartPolicy to never for the empty_dir test.  But there is a deeper issue - how did this test _ever_ pass?  How would it ever happen that State.Termination would be set, with RestartPolicy: Always?

(I am hoping it is the other bug I found with kubelet restart, but I don't know that I entirely believe that)

### PR DESCRIPTION
**Pull request by justinsb**
This should fix #8745, at least the surface issue.  This does not fix the deeper issue (how this ever passed)

### CODE REVIEW

**Comment by pmorie** [comment]
I too am surprised this ever work. I wrote this test originally so this was
an oversight on my part.

**Comment by justinsb** [comment]
Added the same thing on host_path test.

**Comment by lavalamp** [comment]
Is checking the pod status as mentioned in the issue important? Or should we just merge this. It LGTM.

**Comment by pmorie** [comment]
We should merge this.

**Comment by pmorie** [comment]
Will do another review and tag.

**Comment by justinsb** [comment]
Are we OK to merge?   I think this makes e2e tests a little faster, if you need a carrot :-)

**Comment by pmorie** [comment]
My bad @justinsb.

**Pull request merged**
