### PR TITLE
Automated cherry pick of #54013

### PR DESCRIPTION
**Pull request by vladimirvivien**
Cherry pick of #54013 on release-1.8.

#54013: ScaleIO - API source code update

```release-note
ScaleIO persistent volumes now support referencing a secret in a namespace other than the bound persistent volume claim's namespace; this is controlled during provisioning with the `secretNamespace` storage class parameter; StoragePool and ProtectionDomain attributes no longer defaults to the value `default`
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
@liggitt 
Here is the cherry-pick we discussed last week.  Your help here is appreciated!

**Comment by liggitt** [comment]
I'm in favor of this. This addresses a security gap that required copying ScaleIO mount credentials into every ScaleIO PVC namespace, making it unusable for clusters that cannot allow namespace-scoped users to see those ScaleIO mount credentials

@kubernetes/sig-storage-api-reviews for approval of the storage API change

@kubernetes/api-reviewers for second on pick of an API change to a release branch

@kubernetes/sig-api-machinery-api-reviews for thoughts on impact on client-go tagging

**Comment by vladimirvivien** [comment]
Thanks @liggitt !

**Comment by rootfs** [comment]
kind/bug

**Pull request merged**
