### PR TITLE
change psp AllowedHostPath api to be more extensible

### PR DESCRIPTION
**Pull request by jhorwit2**
**What this PR does / why we need it**:

AllowedHostPaths is a new feature in 1.7. I realized today that the current implementation is not friendly to future checks, like ensuring the path is ReadOnly. The change proposed in this PR doesn't change the functionality of the original proposal; however, it does change the API so this feature can easily be extended in the future w/o breaking api changes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

cc @liggitt 

Original PR: https://github.com/kubernetes/kubernetes/pull/43946

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jhorwit2** [comment]
cc @smarterclayton @ericchiang @php-coder

**Comment by php-coder** [comment]
> I had a realization today that the current implementation is not friendly to future checks, like ensuring the path is ReadOnly.

Is it a real use-case? Do we have plans to deal with that? Otherwise, I'd say that this is a premature generalization.

**Comment by jhorwit2** [comment]
@php-coder I'd actually like this feature for 1.7 which is why I thought of it, but realize it's kinda late to submit that addition.

**Comment by jhorwit2** [comment]
use case: lets say you want to host volume /etc/ssl into containers. If that's not read only you just gave access to any container with that volume to inject a malicious cert onto the host for other containers to use.

**Comment by ericchiang** [comment]
This is a breaking API change to a beta API while we're well into code freeze. At this point I think reverting https://github.com/kubernetes/kubernetes/pull/43946 before 1.7 is cut is the only realistic outcome if we're note satisfied with the API and adding this to 1.8.

@kubernetes/sig-auth-api-reviews does that sound about right?

**Comment by smarterclayton** [comment]
I'm fine with revert

**Comment by jhorwit2** [comment]
Same if it's too late for the api change.

**Comment by liggitt** [comment]
agree there's not time to vet this properly before 1.7. reverting #43946 as well and revisiting in 1.8 seems ok

**Comment by ericchiang** [comment]
@jhorwit2 master is open again if you want to rebase.

**Comment by ericchiang** [comment]
@jhorwit2 I know there were a few people interested in getting this in for 1.8. I'm happy to pick this PR up if you're limited on time.

**Comment by jhorwit2** [comment]
Sorry, i was on vaca most of july. I was planning to get to it this weekend (maybe sooner). That work?

**Comment by ericchiang** [comment]
@jhorwit2 perfect!

**Comment by jhorwit2** [comment]
@ericchiang closing this in favor of a single Pr that includes the revert + updated API. https://github.com/kubernetes/kubernetes/pull/50212

**Pull request closed without merging**
