### PR TITLE
Update Web UI table formatting

### PR DESCRIPTION
**Pull request by bcbroussard**
- Condense table styling
- Default table size to 50
- Make all columns sortable
- Rename service portalIP to clusterIP
- Allow default descending table ordering

Also addresses @bgrant0607's comment in #8270 about adding information density.

### CODE REVIEW

**Comment by bcbroussard** [comment]
Low risk change, ok for v1

**Comment by preillyme** [comment]
@lavalamp can you merge this as well?

**Comment by bcbroussard** [comment]
Rebased

**Comment by bgrant0607** [comment]
LGTM

**Comment by zmerlynn** [comment]
Needs rebase.

**Comment by bcbroussard** [comment]
@zmerlynn rebased

**Comment by bprashanth** [comment]
Waiting on @lavalamp ok-to-merge and green on shippable (the close/open trick didn't work for some reason)

**Comment by bgrant0607** [comment]
Restarted shippable. Looked like a flake.

**Comment by lavalamp** [comment]
I will try to remember to build & push a new container when this gets merged. We may or may not launch that new container by default.

**Pull request merged**
