### PR TITLE
Fix broken link to the CronJob proposal

### PR DESCRIPTION
**Pull request by viren-nadkarni**
**What this PR does / why we need it**: Fixes a broken link to the CronJob (prev. ScheduledJob) proposal

**Special notes for your reviewer**: This is a minor change to the documentation

### CODE REVIEW

**Comment by viren-nadkarni** [comment]
signed it

**Comment by viren-nadkarni** [comment]
I signed it!

**Comment by viren-nadkarni** [comment]
.

**Comment by brendandburns** [comment]
Please see See http://kubernetes.io/editdocs/ for information about editing docs about updating docs.

Thanks!

**Pull request closed without merging**
