### PR TITLE
Fix hack/update-api-reference-docs.sh script

### PR DESCRIPTION
**Pull request by wojtek-t**
This is fixing problems introduced by #18473

@smarterclayton - FYI

### CODE REVIEW

**Comment by wojtek-t** [comment]
Merging manually to fix the existing problem.

**Comment by deads2k** [comment]
Worked for me.  Thanks.

**Comment by wojtek-t** [comment]
And our internal tests are fixed again.

**Comment by smarterclayton** [comment]
Weird, how did this get through the merge queue?

**Comment by wojtek-t** [comment]
I have no idea...

@eparis - any thoughts?

**Pull request merged**
