### PR TITLE
Fix missing conformance metadata forAPI Chunking tests

### PR DESCRIPTION
**Pull request by wojtek-t**
```release-note
NONE
```

/sig api-machinery
/kind feature
/priority important-soon

### CODE REVIEW

**Comment by Riaankl** [comment]
/test pull-kubernetes-node-e2e-containerd
/test pull-kubernetes-unit


Unreleated flake
```
[FAIL] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] init container [It] The containers terminated by OOM killer should have the reason set to OOMKilled
```
```
 --- FAIL: TestManifestFilesAreEqual/manifests_are_not_equal (0.00s)
=== FAIL: cmd/kubeadm/app/util/staticpod TestManifestFilesAreEqual/manifests_are_not_equal_for_adding_new_defaults (0.00s)
```

**Comment by Riaankl** [comment]
> /assign @jpbetz @Riaankl

/lgtm

**Review by jpbetz — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
