### PR TITLE
Remove support for containerized-kubelet in local-up-cluster.sh

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I3435b02fbe052a88f6b88d5517de2d68ff636a66

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Please see https://github.com/kubernetes/kubernetes/issues/74148

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
/hold

all related jobs are removed right?

**Comment by dims** [comment]
@krzyzacy yep! removed them https://github.com/kubernetes/test-infra/pull/11338/files

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
