### PR TITLE
Use log functions of core framework on test/e2e/upgrades

### PR DESCRIPTION
**Pull request by clarklee92**
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>

**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
This makes sub packages of e2e test upgrades to use log functions
of core framework instead for avoiding circular dependencies.

**Which issue(s) this PR fixes**:

Ref: #81427 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by alejandrox1 — COMMENTED** [review]
@clarklee92 thank you for working on this!

/lgtm
/ok-to-test
/priority important-soon
/area e2e-test-framework

/assign @oomichi @timothysc @andrewsykim
for final approval

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/approve
/retest

**Comment by alejandrox1** [comment]
@clarklee92 could you please remove the `Fixes #81427` from your PR message ?
/hold

**Comment by clarklee92** [comment]
> @clarklee92 could you please remove the `Fixes #81427` from your PR message ?
> /hold

Already updated, thanks.

**Comment by oomichi** [comment]
Thanks for updating

/hold cancel

**Pull request merged**
