### PR TITLE
add method symmetric difference in sets.String

### PR DESCRIPTION
**Pull request by weilaaa**
#### What this PR does / why we need it:
add method symmetric difference in sets.String

### CODE REVIEW

**Review by MikeSpreitzer — CHANGES_REQUESTED** [review]
This is generated code.  See https://github.com/kubernetes/apimachinery/blob/v0.24.3/pkg/util/sets/string.go#L17

**Comment by MikeSpreitzer** [comment]
See https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator/cmd/set-gen , which uses https://github.com/kubernetes/gengo/tree/master/examples/set-gen ; that is where the change would go.

**Comment by MikeSpreitzer** [comment]
BTW, while you are at it: I have sometimes needed to compute both intersection and difference.  I know both are available, but it is more efficient to compute both together, so maybe there should be a function that does this.  The tricky part is that there are four variants that make sense for the difference part: left minus right, right minus left, both of those, and symmetric difference.  A few boolean parameters, or one of an enumerated type, could say which is desired.

Note also that if we had a side-effecting `AddDifference` method the symmetric difference could be more efficiently computed as `NewEmptySet().AddDifference(left, right).AddDifference(right, left)`.

**Comment by weilaaa** [comment]
> 

I'm not sure I understand "A few boolean parameters, or one of an enumerated type, could say which is desired". Why do we use new functions to combine operations on sets, instead of using existing methods, is to make it clearer?

`NewEmptySet().AddDifference(left, right).AddDifference(right, left)` also can be implement by existing methods `NewEmptySet().Insert(left.Diffenrence(right)).Insert(right.Diffencence(left))`.

By the way, consider if we should rewrite `set` package as go generic rather than using code generator?

**Comment by MikeSpreitzer** [comment]
As I indicated in my remark, the motivation is efficiency.  It was just a suggestion.

I expect that at some point there will be adoption of Go generics for many things, including the set utilities.  But I am not sure when or how that decision will get made.

**Comment by weilaaa** [comment]
Hey @MikeSpreitzer, did I do things in right place? https://github.com/kubernetes/gengo/pull/231

**Comment by weilaaa** [comment]
@MikeSpreitzer Hi.

**Review by MikeSpreitzer — COMMENTED** [review]
I can't fully vouch for the go.mod changes, but the rest looks good to me.

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Comment by weilaaa** [comment]
cc @wzshiming

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
