### PR TITLE
CRI: move SELinuxOption to be a sandbox property

### PR DESCRIPTION
**Pull request by jonboulle**
Primary motivations for this change are that i) there are various
implementation issues with SELinux labels being a container-level
property and heterogeneous within a pod, and ii) there's a need for a
sandbox to have an SELinux context (which is not possible with the
current CRI API).

Fuller context/discussion in
https://github.com/kubernetes/kubernetes/issues/33139

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34329)

### CODE REVIEW

**Comment by yifan-gu** [comment]
@k8s-bot ok to test

**Comment by feiskyer** [comment]
@jonboulle  Related codes at kuberuntime/dockershim should also be updated to pass the compilation.

**Comment by euank** [comment]
My concern is that if we currently technically allow containers in a given pod to have different SELinux contexts (is this actually ever possible?) then we have to just add it to pod and support both for as long as the API allows expressing that.

Should we be deprecating the `v1.Container.SecurityOptions.SeLinuxOptions` field first and then, once that's totally gone, remove it from this interface as well?

After reading the previous issue, I'm not sure I understand the full implications of this, and a bit more explanation about what actually happens when two containers in a pod have different selinux contexts, what happens when container and pod options are set, and what we're comfortable with in terms of api semantic changes.

**Comment by yujuhong** [comment]
@yifan-gu I lost track of the discussions in #33139 (will go read again). Last I checked there wasn't a concrete conclusion drawn from the discussions since the current k8s api still allows container-level SELinux options. Did I miss anything?

**Comment by yifan-gu** [comment]
@jonboulle I am not sure removing the app level selinux option as a whole will be backward compatible.

It seems today if the containers in a pod have host IPC namespace, then they can have different selinux context.

Maybe just adding the pod level selinux context for now to fix https://github.com/kubernetes/kubernetes/issues/33139#issuecomment-251847279 ?

/cc @pmorie

**Comment by pmorie** [comment]
We do need to retain the container level SELinux content. Will review this PR today, sorry for the delay

**Comment by jonboulle** [comment]
Feel free to hold off reviewing until I rework it to re-add container level
ones..

**Comment by feiskyer** [comment]
Just opened another PR to add PodSecurityContext to sandbox config, which includes SELinuxOption. PTAL.

**Comment by jonboulle** [comment]
@feiskyer perhaps you could link it

**Comment by feiskyer** [comment]
@jonboulle Sorry for missing links. Updated.

**Comment by pmorie** [comment]
@jonboulle I think #34811 supercedes this one, do you agree?

**Comment by jonboulle** [comment]
yes, sorry it's taken me a while to circle back here

**Pull request closed without merging**
