### PR TITLE
fix golint

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
Fix golint, don't use underscores in variable
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

For future approvers, we can not remove `pkg/kubelet/dockershim/network/testing` from the `hack/.golint_failures`, because a significant number of golint errors exist in other files in that package. However, given how rare it is for someone to use `snake_case` in Go, I'm not particularly worried about this specific linting failure being reintroduced.

@JieJhih if you want to try and address all of the failures listed by `golint ./pkg/kubelet/dockershim/network/testing/...`, feel free :) Then, we could remove the whole package from `hack/.golint_failures`. But, no pressure! It could also be done as a separate diff if you want to keep this diff small and focused.

**Comment by JieJhih** [comment]
> /lgtm
> 
> For future approvers, we can not remove `pkg/kubelet/dockershim/network/testing` from the `hack/.golint_failures`, because a significant number of golint errors exist in other files in that package. However, given how rare it is for someone to use `snake_case` in Go, I'm not particularly worried about this specific linting failure being reintroduced.
> 
> @JieJhih if you want to try and address all of the failures listed by `golint ./pkg/kubelet/dockershim/network/testing/...`, feel free :) Then, we could remove the whole package from `hack/.golint_failures`. But, no pressure! It could also be done as a separate diff if you want to keep this diff small and focused.

Thanks! I'll work on that. Since the failures are more than five,  I think it would be better separating PRs.

**Comment by mattjmcnaughton** [comment]
On Thu, Nov 07, 2019 at 06:36:07AM -0800, JieJhih wrote:
> > /lgtm
> > 
> > For future approvers, we can not remove `pkg/kubelet/dockershim/network/testing` from the `hack/.golint_failures`, because a significant number of golint errors exist in other files in that package. However, given how rare it is for someone to use `snake_case` in Go, I'm not particularly worried about this specific linting failure being reintroduced.
> > 
> > @JieJhih if you want to try and address all of the failures listed by `golint ./pkg/kubelet/dockershim/network/testing/...`, feel free :) Then, we could remove the whole package from `hack/.golint_failures`. But, no pressure! It could also be done as a separate diff if you want to keep this diff small and focused.
> 
> Thanks! I'll work on that. Since the failures are more than five,  I think it would be better separating PRs.
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/84866#issuecomment-551105347

Yeah, +1 that a separate PR is appropriate here. Thank you for your continued
work on fixing these Golint errors.

**Pull request closed without merging**
