### PR TITLE
kubeadm: Remove `kubeadm config upload`

### LINKED ISSUE #988: kubeadm config upload replacement
info from #987:
> kubeadm config upload was introduced back in v1.8 to manually upload kubeadm init configuration.
As this is done automatically on init and upgrade ever since v1.8 and given the fact, that the command itself has a bit of an awkward interface, it is probably time to consider its deprecation and eventual removal.

As mentioned in #987 , `kubeadm config upload` has awkward interface, which cannot be changed easily since it's in beta.
The problem there is, that there are two sub-commands:
- `from-file` - uploads configuration from kubeadm init config file (InitConfiguration/MasterConfiguration)
- `from-flags` - uses default configuration which is partially overridden by command line flags (the same ones used in `kubeadm init`)

As per #906 we need to provide a command line interface that allows loading the config from a file and then partially overriding it via command line flags. Therefore a new command should be introduced or an old one upgraded to support this.
We can easily upgrade `kubeadm alpha phase upload-config` by adding support for flags and flag override in it.

/area UX
/kind design
/kind documentation
/cc @luxas @timothysc @fabriziopandini

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

`kubeadm config upload` is a GA command that has been deprecated and scheduled
for removal since Kubernetes 1.15 (released 06/19/2019). This change will
finally removed it in Kubernetes 1.19 (planned for August 2020).

The original command has long since been replaced by a GA init phase:
`kubeadm init phase upload-config`

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#988

**Special notes for your reviewer**:

Original deprecation PR by @Klaven is #77946

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-longterm
/assign @fabriziopandini @neolit123

**Does this PR introduce a user-facing change?**:

```release-note
action required: The 'kubeadm config upload' command is finally removed after a full GA deprecation cycle. If you still use it, please, use 'kubeadm init phase upload-config' instead
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by abdennour** [comment]
this is not clear 
i tried: `kubeadm init phase upload-config --config=myconfig.yaml` but i got :

```console
unknown flag: --config
To see the stack trace of this error execute with --v=5 or higher

```

My reference was: https://v1-20.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-upload-config

**Pull request merged**
