### PR TITLE
Set delete propagation policy to background when removing jobs and its dependents 

### LINKED ISSUE #71772: Cronjob leaves behind pods after jobs are deleted
**What happened**:

There seems to be a regression after 1.13 release. A Cronjob with default settings does not clean up completed pods. The job themselves are getting deleted as expected, but the pods are left behind. This seems to be related to https://github.com/kubernetes/kubernetes/pull/70872 @juanvallejo 

**What you expected to happen**:

Expected the pods for now non-existent child jobs  of a cronjob to be cleaned up. This is the way it used to work prior to 1.13/

**How to reproduce it (as minimally and precisely as possible)**:

run `kubectl apply` on this manifest:

```yaml
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cjtest
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cjtest
          labels:
            app: cjtest
        spec:
          restartPolicy: "Never"
          containers:
          - name: cjtest
            image: hello-world
```
Wait, more than 3 minutes, observe, that while only 3 successful jobs are present, the pods from now deleted jobs are left behind and never get deleted.

**Anything else we need to know?**:

@liggitt pointed out the following relevant places in the code base:

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/batch/job/strategy.go#L53
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/injection.go#L121

>deleting a job orphans pods by default and the cronjob controller doesn't do anything different than the default when deleting

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.0
- Cloud provider or hardware configuration: ubuntu VM in vSphere
- OS (e.g. from /etc/os-release): 16.04.5 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-135-generic 
- Install tools: kubeadm

/kind bug

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #71772

**Special notes for your reviewer**:
/assign @liggitt @juanvallejo 

**Does this PR introduce a user-facing change?**:
```release-note
Fixes pod deletion when cleaning old cronjobs
```

### CODE REVIEW

**Comment by soltysh** [comment]
/sig apps
/priority critical-urgent

/assign @aleksandra-malinowska @tpepper 
for 1.13 approval

**Comment by liggitt** [comment]
/lgtm

this fixes a regression in the cronjob controller in 1.13

**Comment by soltysh** [comment]
> Is there any reason this can't be an automated cherry-pick of #71801?

When I was fixing those I've opened manual PRs for both by cherry-picking PRs. Automatic works only after you have a PR open. Is that a problem?

**Comment by soltysh** [comment]
Iow. I did `git cherry-pick` locally.

**Comment by aleksandra-malinowska** [comment]
@soltysh I'm familiar with making both automated and manual cherry-picks, thanks. I was under the impression that there was a policy for using automated if possible (i.e. unless the PR doesn't go to master at all, or there are conflicts, etc.), but I can't find the source, so maybe it's just that (some) past branch managers required of (some) contributors.

@tpepper LMK if you're OK with skipping the automated cherry-pick process in this case.

**Comment by tpepper** [comment]
When PR'ing directly manually against the branch, there is increased risk that we merge a patch that is different than what ultimately merged to master.  After reviewing this one, I'm OK with going ahead with merging as it is in sync.

While the workflow may seem equivalent, or even slightly annoying versus straight manual git for those familiar with that, a very beneficial aspect of the cherry pick automation is that we as patch maintainers automatically know that the patch is the same as what went into master.  This is important for us to know as a cohesive project that we don't have slight accidental variations across branches.

I will work to update the documentation to be more clear that manual cherry picks should be exceptional to deal with some emergent situation that requires the action ahead of PR'ing to master.

**Pull request merged**
