### PR TITLE
Automated cherry pick of #71522: Use Node-Problem-Detector v0.6.0

### PR DESCRIPTION
**Pull request by wangzhen127**
Cherry pick of #71522 on release-1.13.

#71522: Use Node-Problem-Detector v0.6.0

### CODE REVIEW

**Comment by wangzhen127** [comment]
Patch release managers, PTAL
/assign @tpepper
/assign @aleksandra-malinowska

**Comment by aleksandra-malinowska** [comment]
Looks good to me. @tpepper I think you mentioned some doubts regarding the release notes - anything that prevents it from merging? If not, let's do it today to get some CI signal over the weekend.

**Comment by wangzhen127** [comment]
To clarify, the purpose is to make debugging the cluster easier. Node-problem-detector runs on the worker nodes and does not change kubernetes cluster's behavior. What it does is to monitor the node health and report if anything wrong happens.

**Pull request merged**
