### PR TITLE
Automated cherry pick of #65367: make sure delete waiting doesn't re-evaluate the resource

### PR DESCRIPTION
**Pull request by deads2k**
Cherry pick of #65367 on release-1.11.

#65367: make sure delete waiting doesn't re-evaluate the resource

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
@jberkus for 1.11 approval

**Comment by liggitt** [comment]
fixes Fixes #65366

**Comment by jberkus** [comment]
cleared for 1.11

**Pull request merged**
