### PR TITLE
Fix error reporting during vagrant provisioning

### PR DESCRIPTION
**Pull request by ivan4th**
`release_not_found` shell function can be used both while running
`provision-master.sh` and `privision-node.sh` (it's used by `install-salt`
function in `provision-utils.sh`, but it was defined in `provision-master.sh`.
Because of this, one of my colleagues got the following diagnostic:

```
==> master: Succeeded: 52 (changed=8)
==> master: Failed:     0
==> master: -------------
==> master: Total states run:     52
==> node-1: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> node-1: flag to force provisioning. Provisioners marked to run always will still run.
==> node-1: Running provisioner: shell...
    node-1: Running: /tmp/vagrant-shell20160726-19144-hahnl1.sh
==> node-1: Prepare package manager
==> node-1: Provisioning network on node
==> node-1: Network configuration verified
==> node-1: /tmp/vagrant-shell: line 134: release_not_found: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

... which is rather confusing.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29610)

### CODE REVIEW

**Comment by jellonek** [comment]
Bump up.

**Comment by derekwaynecarr** [comment]
Thanks for the fix.

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/29992

**Comment by ivan4th** [comment]
Hmm, obviously e2e test failures have nothing todo with vagrant provisioning here...

**Comment by ivan4th** [comment]
@derekwaynecarr (ping) can we re-test this? The e2e test failure doesn't involve vagrant provider at all

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/30124

**Pull request merged**
