### PR TITLE
[Federation] Move sync controller

### PR DESCRIPTION
**Pull request by marun**
This PR moves the sync controller to its own package in support of parallel efforts to use it for more types than just secrets.

The secret controller unit tests have been retained for now.  Once good unit test coverage exists for the sync controller, the existing secret controller unit testing can go away.

cc: @kubernetes/sig-federation-pr-reviews @perotinus

### CODE REVIEW

**Comment by perotinus** [comment]
LGTM.

@nikhiljindal Can you take a look and give the official LGTM?

**Comment by marun** [comment]
rebased

**Comment by marun** [comment]
@k8s-bot bazel test this

**Comment by marun** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
Then visit: http://prow.k8s.io/?type=presubmit&pull=44217&job=pull-kubernetes-federation-e2e-gce
Shouldn't affect e2e, i'll wait for green then lgtm

**Comment by marun** [comment]
rebased

@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by marun** [comment]
@csbell e2e is green: http://prow.k8s.io/?type=presubmit&pull=44217&job=pull-kubernetes-federation-e2e-gce

**Comment by marun** [comment]
rebased

@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by marun** [comment]
@csbell Rebase is also green.

**Pull request merged**
