### PR TITLE
remove unused code in kubeadm/app/cmd/reset_test.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
remove unused code in kubeadm/app/cmd/reset_test.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks
/lgtm

**Comment by fabriziopandini** [comment]
@hanxiaoshuai thanks for the cleanup!
/approve
/lgtm

**Pull request merged**
