### PR TITLE
Refactoring unused parameter

### PR DESCRIPTION
**Pull request by HyunSu1768**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Removed unused parameters from prober.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by bart0sh** [comment]
@HyunSu1768 If you're fixing this, can you also look at the rest of the cases in pkg/kubelet?
hint:
```
$ golangci-lint run --disable-all --enable unparam ./pkg/kubelet/... | grep unparam | wc -l
48
```

**Comment by HyunSu1768** [comment]
> @HyunSu1768 If you're fixing this, can you also look at the rest of the cases in pkg/kubelet? hint:
> 
> ```
> $ golangci-lint run --disable-all --enable unparam ./pkg/kubelet/... | grep unparam | wc -l
> 48
> ```

Okay! I will delete unused parameters and commit.

**Comment by HyunSu1768** [comment]
> @HyunSu1768 If you're fixing this, can you also look at the rest of the cases in pkg/kubelet? hint:
> 
> ```
> $ golangci-lint run --disable-all --enable unparam ./pkg/kubelet/... | grep unparam | wc -l
> 48
> ```

I tried this, but there are countless changes, so it seems difficult to do in that pr. Can we solve it step by step in another pr?

**Comment by bart0sh** [comment]
@HyunSu1768
> I tried this, but there are countless changes, so it seems difficult to do in this pr. Can i solve it step by step in another pr?

Sure, you can solve them step by step, but why not to start with this PR? Just include a couple of other directories to decrease amount of future PRs.

**Comment by HyunSu1768** [comment]
> @HyunSu1768
> 
> > I tried this, but there are countless changes, so it seems difficult to do in this pr. Can i solve it step by step in another pr?
> 
> Sure, you can solve them step by step, but why not to start with this PR? Just include a couple of other directories to decrease amount of future PRs.

All right. Let's fix it in a way that doesn't have a big impact.

**Pull request closed without merging**
