### PR TITLE
e2e: node: kubelet restart improvements

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup
/kind failing-test
/kind flake

#### What this PR does / why we need it:
Improve the handling of kubelet restarts, making the error clearer and improving the `restartKubelet` function.

#### Which issue(s) this PR fixes:
See comments

#### Special notes for your reviewer:
TBD

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by fromanirh** [comment]
```

=== Failed
=== FAIL: pkg/registry/core/configmap/storage TestWatch (3.97s)
W1007 13:36:02.005369   61197 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {localhost:34747 localhost <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:34747: connect: connection refused". Reconnecting...
W1007 13:36:02.411942   61197 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {localhost:45257 localhost <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:45257: connect: connection refused". Reconnecting...
W1007 13:36:02.807162   61197 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {localhost:40391 localhost <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:40391: connect: connection refused". Reconnecting...
W1007 13:36:03.254004   61197 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {localhost:44465 localhost <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:44465: connect: connection refused". Reconnecting...
W1007 13:36:03.319669   61197 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {localhost:34757 localhost <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:34757: connect: connection refused". Reconnecting... 
```

**Review by endocrimes — COMMENTED** [review]
lgtm on first pass at least - there's a few places where we need to clean up lifecycle management

**Comment by fromanirh** [comment]
> @fromanirh looks like you missed a restartKubelet call
> 
> ```
> W1007 17:02:40.251] # k8s.io/kubernetes/test/e2e_node [k8s.io/kubernetes/test/e2e_node.test]
> W1007 17:02:40.252] test/e2e_node/podresources_test.go:734:18: not enough arguments in call to restartKubelet
> W1007 17:02:40.252] 	have ()
> W1007 17:02:40.252] 	want (bool) 
> ```

thanks. rebase glitch: this is the test I was working on and which drove this PR :\

**Comment by fromanirh** [comment]
/hold
let me see if I can narrow down the restart woes a bit more

**Review by ehashman — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
