### PR TITLE
simplify regexp with raw string

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Simplify regular expression with raw string, avoid using redundant backslash. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendotjs** [comment]
/assign @dixudx @eparis 
ptal, thanks

**Review by dixudx — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by chendotjs** [comment]
/assign @eparis
PTAL, thank you

**Comment by chendotjs** [comment]
/assign @eparis 
Would you please take a look? :)

**Pull request merged**
