### PR TITLE
Typos and englishify pkg/cloudprovider + pkg/dns + pkg/kubectl

### PR DESCRIPTION
**Pull request by pigmej**
**What this PR does / why we need it**: Just fixed some typos + "englishify" in pkg/cloudprovider + pkg/dns + pkg/kubectl

**Which issue this PR fixes** : None

**Special notes for your reviewer**: It's just fixes typos

**Release note**: `NONE`

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31773)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31773#-:-KQWSEiEYlB76HdK-p0p:bnfp4nl)*

**Comment by jlowdermilk** [comment]
lgtm, but please squash to a single commit.

**Comment by pigmej** [comment]
@jlowdermilk squashed (though bot removed label about retest :( )

**Comment by jlowdermilk** [comment]
Thanks

**Comment by pigmej** [comment]
@jlowdermilk can we merge that in 1.4 cycle?

**Pull request merged**
