### PR TITLE
Fix grammatical errors and repeat words

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Fix grammatical errors and repeat words

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@xichengliudui Thanks for this cleanup!
/approve
/lgtm

**Comment by xichengliudui** [comment]
cncf-cla ?

**Comment by xichengliudui** [comment]
I signed it

**Comment by xichengliudui** [comment]
ci checkout this

**Comment by xichengliudui** [comment]
I have signed CNCF. Why is there no cncf-cla label

**Pull request merged**
