### PR TITLE
changeLog-Fixtypo

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
changeLog-Fixtypo

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by heqg** [comment]
when this pr is merged ,I will close another similar pr https://github.com/kubernetes/kubernetes/pull/97519

**Review by hasheddan — APPROVED** [review]
/lgtm
/ok-to-test

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
