### PR TITLE
[Test] Revert "Fix:[Flake] [sig-node] Restart [Serial] [Slow] [Disruptive] K…

### PR DESCRIPTION
**Pull request by adisky**
…ubelet should correctly account for terminated pods after restart"

This reverts commit 572360c5a5f48932556c806c70a74cb260df3adb.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/115045

**Comment by adisky** [comment]
@bobbypage @SergeyKanzhelev Do we want to revert or try to fix? I was just testing if this commit was actual cause of failure so didn't tag anything

**Comment by bobbypage** [comment]
The test is not failing in the pull run above (`pull-kubernetes-node-kubelet-serial-containerd`).

This test is resulting in the [cos-cgroupv2-containerd-node-e2e-serial|cos-cgroupv1-containerd-node-e2e-serial] testgrids being red, +1 on doing the revert.

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial
https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

**Review by SergeyKanzhelev — APPROVED** [review]
let's do revert for now

**Comment by bart0sh** [comment]
@bobbypage 
> This test is resulting in the [cos-cgroupv2-containerd-node-e2e-serial|cos-cgroupv1-containerd-node-e2e-serial] testgrids being red, +1 on doing the revert.

It doesn't seem to be the case as both tests were failing after this revert is merged. https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial is still failing.

**Comment by adisky** [comment]
@bart0sh none of the oomscore tests got failed after 24th Jan, This PR was not going to fix the whole job it was only targeting to oomscore tests

**Pull request merged**
