### PR TITLE
[1.12] Automated cherry pick of #76334: proxy: Take into account exclude CIDRs while deleting legacy

### PR DESCRIPTION
**Pull request by namreg**
Cherry pick of #76334 on release-1.12.

#76334: proxy: Take into account exclude CIDRs while deleting legacy real servers

/sig network
/area ipvs

### CODE REVIEW

**Comment by feiskyer** [comment]
/ok-to-test

@m1093782566 Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.


/assign @m1093782566

**Comment by m1093782566** [comment]
/lgtm

/approve

Thanks @feiskyer

**Comment by feiskyer** [comment]
@namreg Could you add a release note in the original PR?

**Comment by namreg** [comment]
@feiskyer There is no release notes.

**Comment by feiskyer** [comment]
@namreg OK

/check-cla

**Pull request merged**
