### PR TITLE
Delete the two same if in func TestPlugin

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
Delete the two same if in func TestPlugin
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign @andyzhangx @jingxu97 
thanks

**Comment by andyzhangx** [comment]
/approve no-issue
/lgtm
looks like these unit test code is copied from one place.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by jianglingxia** [comment]
thanks @andyzhangx 
for approve @jingxu97

**Comment by jianglingxia** [comment]
/cc @jsafrane 
thanks

**Comment by jsafrane** [comment]
/approve no-issue

I'd appreciate if submit all changes in one PR next time. This is the same as #60370

**Comment by jianglingxia** [comment]
ok,thanks for your advice,because of review this code not in one time.@jsafrane

**Pull request merged**
