### PR TITLE
Remove update-storage-objects.sh

### LINKED ISSUE #69299: Remove cluster/update-storage-objects.sh and hack/test-update-storage-objects.sh
The cluster/update-storage-objects.sh are not maintained. It will be replaced by https://github.com/kubernetes/community/pull/2524.

We still run the hack/test-update-storage-objects.sh. Its invocation will be removed in https://github.com/kubernetes/kubernetes/pull/67678. We can remove the script.

/sig api-machinery
/assign

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As #69299 stated, cluster/update-storage-objects.sh is subsumed by kubernetes/community#2524

**Which issue(s) this PR fixes**:
Fixes #69299

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Though the storage migrator is not ready yet, these scripts are outdated and not useful, so removing them lgtm.

/lgtm
/approve

**Comment by dims** [comment]
Thanks @caesarxuchao! for making my review easier :)

/approve

**Comment by superbrothers** [comment]
@tedyu @caesarxuchao 

> Though the storage migrator is not ready yet, these scripts are outdated and not useful, so removing them lgtm.

So, how we update storage objects instead? You said the kube-storage-version-migrator is not ready yet. :thinking:

**Pull request merged**
