### PR TITLE
Jenkins gke e2e: don't use sudo with gsutil cp

### PR DESCRIPTION
**Pull request by ixdy**
@quinton-hoole @jlowdermilk @kubernetes/goog-testing

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm, thanks for fixing my break :)

**Comment by ixdy** [comment]
Context: this creates a `repo` directory in the workspace owned by root. Originally, the Jenkins configurations also ran `sudo rm -rf ~/repo`, but that's now missing. Since the directory is owned by root, the cleanup plugin can't delete it, bails, and our Jenkins instance soon runs out of disk.

It seems like there's no reason to have any of this even run through `sudo` in the first place, so removing.

**Comment by zmerlynn** [comment]
LGTM as well.

**Comment by ixdy** [comment]
@jlowdermilk can we skip the submit queue and get this merged now? I'd like to stop breaking Jenkins. :)

**Pull request merged**
