### PR TITLE
Job: Stop unnecessary string casts in validations

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Since https://github.com/kubernetes/kubernetes/pull/120592, the `field.NotSupported` supported generics.
So, we can directly use aliased string vars without casts.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tenzen-y** [comment]
No relevant error happend
/test pull-kubernetes-e2e-gce

**Review by kannon92 — COMMENTED** [review]
/lgtm
/assign @alculquicondor

**Review by alculquicondor — COMMENTED** [review]
/approve
:)

**Comment by kannon92** [comment]
/retitle Job: Stop unnecessary string casts in validations

**Comment by tenzen-y** [comment]
@smarterclayton doesn't seem to have enough time for this PR. So, let me also assign it to other API reviewers.
/assign @deads2k @liggitt

**Pull request merged**
