### PR TITLE
Update calico to v2.4 and enable health checks

### PR DESCRIPTION
**Pull request by gunjan5**
**What this PR does / why we need it**:
- Updates Calico to `v2.4`
  - Calico/node to `v2.4`
  - Calico CNI to `v1.10.0`
  - Typha to `v0.3.1`
- Enable health check endpoints
  - Add Readiness probe for calico-node and Typha
  - Add Liveness probe for calico-node and Typha
 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NA

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
This includes the fix for https://github.com/projectcalico/k8s-policy/issues/113

@dnardo @wojtek-t Can we get this added to the v1.7 milestone as a bugfix?

/lgtm

**Comment by gunjan5** [comment]
Closing this since we have a new PR https://github.com/kubernetes/kubernetes/pull/51237  which is a superset of this one

**Pull request closed without merging**
