### PR TITLE
Remove kubectl book

### PR DESCRIPTION
**Pull request by seans3**
* Removes `kubectl book` documentation, since it is not being served anymore.

/sig cli
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by KnVerey** [comment]
/approve 
/unhold
This content has all been migrated to the new site

**Review by eddiezane — APPROVED** [review]
Gotta love a -14k line diff :)

I think the dns for this is already cleaned up?

**Comment by seans3** [comment]
> /approve
> /unhold
> This content has all been migrated to the new site

Wherever the new site is, we should make sure the Dockerfile does not do a `curl | <bash>` to build the image. This is a security vulnerability.

**Comment by eddiezane** [comment]
@seans3 looks like it does.

https://kustomize.sigs.k8s.io/installation/kustomize/binaries/

https://github.com/kubernetes-sigs/cli-experimental/blob/3598424d6bc6e8145e278398417265b6fc67d156/site/content/en/installation/kustomize/binaries.md

How does the security team feel about curl pipe to gpg key import? There's a few of those as well.

https://github.com/kubernetes-sigs/cli-experimental/search?p=1&q=curl

**Comment by seans3** [comment]
> Sean Sullivan looks like it does.
> 
> https://kustomize.sigs.k8s.io/installation/kustomize/binaries/
> 
> https://github.com/kubernetes-sigs/cli-experimental/blob/3598424d6bc6e8145e278398417265b6fc67d156/site/content/en/installation/kustomize/binaries.md
> 
> How does the security team feel about curl pipe to gpg key import? There's a few of those as well.
> 
> https://github.com/kubernetes-sigs/cli-experimental/search?p=1&q=curl

I'm believe both of those are security vulnerabilities. I think we can modify the `cli-experimental` repo easily and without significant repercussions.

**Comment by sftim** [comment]
/sig docs
The new (experimental?) book is https://kubectl.docs.kubernetes.io/ or https://github.com/kubernetes-sigs/cli-experimental/ in source control.

**Pull request merged**
