### PR TITLE
Remove unneeded deps

### LINKED ISSUE #54711: [job failure] ci-kubernetes-verify-master
/priority critical-urgent
/priority failing-test

/sig release
/sig testing
because I'm taking a guess at who owns this job, [it doesn't have an owner right now](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L8915)

This job is on the release-master-blocking dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify

Last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/15486
First bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/15487
Suspect commit range: https://github.com/kubernetes/kubernetes/compare/7914aed80...aabfc5555

```
I1027 01:25:33.138] Godeps Verify failed.
I1027 01:25:33.138] If you're seeing this locally, run the below command to fix your directories:
I1027 01:25:33.138] patch -p0 < vendordiff.patch
I1027 01:25:33.139] (The above output can be saved as godepdiff.patch if you're not running this locally)
I1027 01:25:33.139] (The patch file should also be exported as a build artifact if run through CI)
I1027 01:25:33.139] Copying patch to artifacts..
I1027 01:25:33.139] Leaving /tmp/gopath.zr6T52 for you to examine or copy. Please delete it manually when finished. (rm -rf /tmp/gopath.zr6T52)
I1027 01:25:33.139] FAILED   hack/make-rules/../../hack/verify-godeps.sh	677s
```

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Removes unneeded deps that were left behind when the federation code was removed in #53816. This is causing `ci-kubernetes-verify-master` to fail.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54711

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
```
I1027 19:57:07.082] SUCCESS  hack/make-rules/../../hack/verify-godeps.sh	638s
```
Verify job passing now

/cc @spiffxp @BenTheElder @marun 
Can one of you review and lgtm? :)

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/lgtm
thx for the quick turnaround @cblecker

**Pull request merged**
