### PR TITLE
collapse into one factory

### PR DESCRIPTION
**Pull request by deads2k**
We've stripped enough out of the factory that we can strip down to a single factory instead of ringed set.

@kubernetes/sig-cli-maintainers 

Nothing else should be added to the factory.  Instead we should build particular constructors atop the RESTClientGetter and structure commands with clear wiring stages and execution stages to simplify the unit testing for each piece.  See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/wait/wait.go  .  It is easily unit testable with "standard" mocks and constructs as compared to using the factory as an injector an retesting a builder to act as a surrogate API server using a different client mocking mechanism.

@soltysh @juanvallejo I'm fine with this after your currently open snips.

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
This lgtm, feel free to tag when the other bits are in.

**Comment by deads2k** [comment]
> This lgtm, feel free to tag when the other bits are in.

rebased, tagging

**Pull request merged**
