### PR TITLE
Add ability to enable patch conversion detector

### PR DESCRIPTION
**Pull request by wojtek-t**
Will rebase and fix once #41326 is merged.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot non-cri gce test this, issue: #IGNORE

**Comment by smarterclayton** [comment]
Can't tell if this is an actual error.

**Comment by wojtek-t** [comment]
I had the same suite failing in other PRs with completely unrelated changes. So I'm pretty sure it's a flake.

@k8s-bot non-cri gce test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot non-cri e2e test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
@smarterclayton PTAL

**Comment by wojtek-t** [comment]
@gmarek - can you please take a look?

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-bazel test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-verify test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wojtek-t** [comment]
Trivial rebase - reapplying label.

**Pull request merged**
