### PR TITLE
Bump golang.org/x/oauth2 to v0.4.0

### PR DESCRIPTION
**Pull request by lucacome**
#### What type of PR is this?

/kind cleanup 

#### What this PR does / why we need it:

Bumps golang.org/x/oauth2 from `v0.0.0-20220223155221-ee480838109b` to `v0.4.0`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/pull/114943/files#r1065805223.

**Comment by bart0sh** [comment]
@lucacome please rebase and fix failing CI tests to proceed further with this PR.

**Comment by liggitt** [comment]
actually, it's not worth the effort to keep this rebased until we have https://github.com/kubernetes/kubernetes/issues/113366 resolved... it can't merge ahead of that anyway

/close

**Pull request closed without merging**
