### PR TITLE
Update to go 1.12.6

### PR DESCRIPTION
**Pull request by tao12345666333**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

go1.12.6 (released 2019/06/11) includes fixes to the compiler, the linker,
the go command, and the <code>crypto/x509</code>, <code>net/http</code>, and
<code>os</code> packages. See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.6">Go 1.12.6 milestone</a> on our issue tracker for details.

https://github.com/golang/go/compare/go1.12.5...go1.12.6

update to go 1.12.6

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update to use go 1.12.6
```

### CODE REVIEW

**Comment by tao12345666333** [comment]
```
W0618 03:38:20.320] Step 1/16 : FROM k8s.gcr.io/kube-cross:v1.12.6-1
W0618 03:38:20.320] manifest for k8s.gcr.io/kube-cross:v1.12.6-1 not found
```

we need wait for `k8s.gcr.io/kube-cross:v1.12.6-1` image published.
cc @javier-b-perez

**Comment by javier-b-perez** [comment]
I'm building now... will post here when the image is ready

**Comment by listx** [comment]
FYI there is work going on to try to remove Googlers from the critical path (of publishing images for the community) here: https://github.com/kubernetes-sigs/k8s-container-image-promoter. Hopefully it lands for k8s.gcr.io soon.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
