### PR TITLE
make StringSet.Delete accept multiple items

### PR DESCRIPTION
**Pull request by deads2k**
Adds DeleteAll method to StringSet.

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton ptal.  It's small, but it adds utility to the type.

**Comment by thockin** [comment]
Why is this better than assignment from an empty set?  What's the use case?

I don't mean to be overly rough, I am just fighting my natural tendency to add "obvious" APIs that nobody really uses and that have reasonable alternatives.

**Comment by smarterclayton** [comment]
Why not have Reset if you don't want to reuse memory (which fits other go conventions for reusable objects).  However, I don't know that this type is going to benefit from that since when you throw away a map you're going to lose all the chains so you don't save much GC pressure.

----- Original Message -----

**Comment by deads2k** [comment]
`DeleteAll` is not a `Reset`,  the name mirrors `HasAll`.  It deletes all the items passed in, but does not clear the entire set.  This is useful for building sets where I want to include everyone from column A, unless they appear in column B.  For example:

```
usersWithAccess := util.StringSet{}

for _, allowRule := range allowAccessRules{
    usersWithAccess.Insert(allowRule.users...)
}
for _, denyRule := range allowAccessRules{
    usersWithAccess.DeleteAll(denyRule.users...)
}

// usersWithAccess now holds all the users from any allow rule that were not explictly denied.
```

The alternative is 
```
for _, denyRule := range allowAccessRules{
    for _, deniedUser := range denyRule.users{
        usersWithAccess.Delete(deniedUser)
    }
}
```

`DeleteAll` is just more convenient.

**Comment by smarterclayton** [comment]
Subtract(), but why not make it a new set?

----- Original Message -----

**Comment by thockin** [comment]
I mis-parsed this PR the first time, I apologize.

I am OK with this behavior, but why not make Delete() take plural items, as Insert() does?

**Comment by deads2k** [comment]
> why not make Delete() take plural items

I can do that.

Don't tell @smarterclayton, but it was because I was used to: http://docs.oracle.com/javase/6/docs/api/java/util/Collection.html#removeAll(java.util.Collection)....

**Comment by thockin** [comment]
It'll be our secret.  Poke me when you are done.

**Comment by deads2k** [comment]
StringSet.Delete now accepts multiple items

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
