### PR TITLE
feat: return early when found scheduler error

### LINKED ISSUE #75635: genericScheduler#findNodesThatFit should return from parallel work early if there is any error
**What would you like to be added**:
In genericScheduler#findNodesThatFit, workqueue.ParallelizeUntil evaluates all checkNode.
Afterwards, if there is any err, the func would return.

We can add variant of ParallelizeUntil which takes errs (an error map - map[string]int).
```
                                select {
                                case <-stop:
                                        return
                                default:
                                        doWorkPiece(piece)
                                }
```
We can add a new case above where once errs map is non-empty, return early.

**Why is this needed**:
This addition would allow node evaluation to finish sooner if there is any error.

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Return from parrelel work early when we found scheduler error in generic scheudler

Related to https://github.com/kubernetes/kubernetes/issues/75635

**Which issue(s) this PR fixes**:

Fixes #75635 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
@draveness actually the behavior that gathers all scheduling failures and return is intentional. And that info can be displayed when running `k describe pod <pending pod>`.

**Comment by draveness** [comment]
> @draveness actually the behavior that gathers all scheduling failures and return is intentional. And that info can be displayed when running `k describe pod <pending pod>`.

That makes sense, and we need to clarify and close #75635 to avoid more PRs. Thanks for the time to check this out.

**Comment by Huang-Wei** [comment]
@draveness Sure. This is a good PR, in golang's perspective though :)

**Pull request closed without merging**
