### PR TITLE
clean up *.properties files

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/kubernetes/issues/62754

to double check, is any of the node config yaml files are still being used outside of CI? I'll make a follow up one to clean them up as well.

/assign @Random-Liu @mindprince @yujuhong

### CODE REVIEW

**Comment by mindprince** [comment]
Can you edit the description to link to their replacement?

**Comment by krzyzacy** [comment]
they all becomes, the args are all moved to https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L11143-L11151 and then get kicked off in kubetest like https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L582-L595

**Pull request merged**
