### PR TITLE
support short name for flowschema and prioritylevelconfiguration

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
 `Flowschema` and `prioritylevelconfiguration` resources support short name `fs` and `plc`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

original release note (dropped with revert in https://github.com/kubernetes/kubernetes/pull/117993)
```
 The short names fs and plc were introduced for the resources flowschemas and prioritylevelconfigurations, respectively
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
/cc @MikeSpreitzer 
for any thoughts on shortnames on these API kinds

**Comment by MikeSpreitzer** [comment]
Yes, I think this is a great idea.

Since it is a user-visible change, it deserves  a release note, right?

/release-note-edit ```The short names fs and plc were introduced for the resources flowschemas and prioritylevelconfigurations, respectively```

/lgtm

**Comment by MikeSpreitzer** [comment]
BTW, my attempt to update the release note failed; @kkkkun could you please update the opening comment to state the release note?

**Comment by kkkkun** [comment]
/release-note-edit The short names fs and plc were introduced for the resources flowschemas and prioritylevelconfigurations, respectively

**Comment by kkkkun** [comment]
/release-note-edit 
The short names fs and plc were introduced for the resources flowschemas and prioritylevelconfigurations, respectively

**Comment by kkkkun** [comment]
> BTW, my attempt to update the release note failed; @kkkkun could you please update the opening comment to state the release note?

Done. Thanks.

**Comment by liggitt** [comment]
xref discussion in https://github.com/kubernetes/kubernetes/pull/117742#issuecomment-1545945336 about whether new shortnames for built-in resources are a good idea

**Pull request merged**
