### PR TITLE
Revert "Update node status even if cloudprovider API dies"

### PR DESCRIPTION
**Pull request by thockin**
Reverts kubernetes/kubernetes#13417

We're experiencing a lot of flaky tests in this space starting around the time this PR went in.  Sorry for the chaos, but this is being rolled back. 

@quinton-hoole

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by quinton-hoole** [comment]
The merge bot is stalled as scalability tests are currently failing.  Manually merging this for now.

http://submit-queue.k8s.io/

**Comment by thockin** [comment]
@jfoy care to try again?

**Comment by jfoy** [comment]
@thockin Yes -- is the implication that this change caused the test flakiness, or was this just rolled back as part of returning to a known-stable state?

**Comment by quinton-hoole** [comment]
@jfoy Anecdotally this PR increases test flakyness, specifically nodes intermittently stop reporting in.  Since rolling this back, we've not seen such failures, but that's still somewhat inconclusive.  I'll leet you know as soon as we know conclusively either way.

**Comment by quinton-hoole** [comment]
@jfoy At this point we've had about 40 clean test runs since reverting #13417.  Prior to reverting it, we would see the failure I describe at least once in every 5 runs. So I think we can consider it fairly conclusive that #13417 is the cause of the failures.

It should be fairly straightforward for you to reproduce the error locally - just run the e2e tests about 5 to 10 times in succession, and you should see a bunch of tests fail at least once as described in #14211.  If you need any help debugging, just let me know.

Running the e2e tests is described in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#end-to-end-tests

e.g. something like this for you:

```
# Build the binaries and bring up a test cluster
go run hack/e2e.go --build --up
# Run all tests a few times
for ((i=0;i<5;i++)) ; do go run hack/e2e.go --test ; done
```  

Good luck...

**Comment by thockin** [comment]
We're still seeing the occasional NodeNotReady error in e2e-gce - please do
investigate this PR, but we'll keep looking elsewhere too.

**Pull request merged**
