### PR TITLE
AWS: Support default value for ExternalHost

### LINKED ISSUE #33563: AWS: Implement default external host
We should just be able to add an `|| options.CloudProvider == "aws"`

https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/config.go#L417-L418

### PR DESCRIPTION
**Pull request by justinsb**
Fix #33563

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33568)

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this

**Comment by justinsb** [comment]
Rebased ... this is now even smaller @smarterclayton  :-)

**Comment by smarterclayton** [comment]
LGTM

**Comment by justinsb** [comment]
@k8s-bot node e2e test this issue #34990

**Comment by justinsb** [comment]
@k8s-bot cvm gce e2e test this

**Comment by saad-ali** [comment]
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Adding 1.5 milestone to let it gets merged after code freeze.

**Pull request merged**
