### PR TITLE
Update go mod hcsshim version to fix the kube-proxy issue cannot access service by self nodeip:port  on windows

### LINKED ISSUE #79515: The kubernetes 1.15 kube-proxy report  "Unable to find HNS Network specified by cbr0"  on windows  node
**What happened**:

When i upgrade my kubernetes cluster windows node  to 1.15,the windows node kube-proxy cannot work properly.  My  windows deployment cannt access by Nodeip:Port on this node but it can access by  the same cluster other nodes with  Nodeip:Port 

When i rollback my windows node  to 1.14.1 .  the kube-proxy works good, everything is ok

The kube-proxy logs  Loop Report that.

```
E0628 16:57:08.673912    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:08.673912    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
E0628 16:57:09.679372    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:09.679372    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
```

* 1.15.0

image

At this version , i cannot access my application by current node ip and the port

image

---------

* 1.14.1
image

At this version , i can access my application by current node ip and the port

image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows server 2019 (10.0.17763.134)
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel host-gw
- Others:
@feiskyer @andyzhangx

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix the kube-proxy issue cannot access service by self nodeip:port on windows

**Which issue(s) this PR fixes**:
Fixes #79515

Reopen of https://github.com/kubernetes/kubernetes/pull/80116 by @wawa0210

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fixes kube-proxy bug accessing self nodeip:port on windows
```

/cc @PatrickLang 
cc wawa0210
/sig network windows

### CODE REVIEW

**Comment by wawa0210** [comment]
@BenTheElder Can you approve again , the same pr https://github.com/kubernetes/kubernetes/pull/80116

**Comment by BenTheElder** [comment]
@wawa0210 this PR is already approved :+)

**Comment by wawa0210** [comment]
> @wawa0210 this PR is already approved :+)

But it is still in the open state, has not been merged?

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by wawa0210** [comment]
> /priority important-soon
I am very excited that this pr was merged into the master branch. Since I found the problem in version 1.15, do I need to launch cherry-pick to 1.15 and 1.16?

**Comment by liggitt** [comment]
> Since I found the problem in version 1.15, do I need to launch cherry-pick to 1.15 and 1.16?

You are welcome to open the cherry-pick, and it is up to @kubernetes/sig-windows-bugs and @kubernetes/patch-release-team to determine severity of the issue being fixed, and risk of the backport.

**Comment by wawa0210** [comment]
> > Since I found the problem in version 1.15, do I need to launch cherry-pick to 1.15 and 1.16?
> 
> You are welcome to open the cherry-pick, and it is up to @kubernetes/sig-windows-bugs and @kubernetes/patch-release-team to determine severity of the issue being fixed, and risk of the backport.

Thx , Done !

**Pull request merged**
