### PR TITLE
Jenkins: Clean up even if we can't bring cluster up

### PR DESCRIPTION
**Pull request by zmerlynn**
We're gathering all the cluster logs, go ahead and clean up the
resources.

### CODE REVIEW

**Comment by zmerlynn** [comment]
@spxtr: Sorry, it actually needs to override the exit code, too, of course. :)

**Comment by zmerlynn** [comment]
@spxtr: PTAL, had to rebase across a change that moved the exit route off to a function.

**Comment by zmerlynn** [comment]
@k8s-bot node e2e test this, issue #IGNORE (flaky) @pwittrock

**Comment by spxtr** [comment]
@k8s-bot test this again issue: #25138

**Pull request merged**
