### PR TITLE
fix file premission issue

### PR DESCRIPTION
**Pull request by daixiang0**
config file shoule be 644.

### CODE REVIEW

**Comment by daixiang0** [comment]
any update?

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
Actually this is being cherry picked onto 1.12...?  This is not the actual release rpms.  

Closing this cherry pick as these are not the canonical location of artifacts.

**Comment by daixiang0** [comment]
@timothysc do you mean only accept PR about rpms to approve?
I think if no change, it still need to correct file permission when 1.12 release.

**Pull request closed without merging**
