### PR TITLE
Revert "expose prometheus.Registerer so that we can hook into this from external sources"

### PR DESCRIPTION
**Pull request by logicalhan**
This reverts commit 07f262b2cc7230cce063dc733fca7cee1d8d286f.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Reverts a change which made it into the release branch.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
this was inadvertently merged. let's roll it back.

/approve
/lgtm
/milestone v1.26

**Comment by liggitt** [comment]
/lgtm
/approve

thanks for the quick rollback, can revisit for 1.27 and 1.26.1

**Comment by dims** [comment]
/triage accepted
/priority critical-urgent

(as a matter of policy!)

**Comment by liggitt** [comment]
looks like that test job went ~solid red this morning - https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e

**Pull request merged**
