### PR TITLE
Modify the wrong comment for controller_util.go

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by mysunshine92** [comment]
@deads2k @cheftako would you like to review it？

**Comment by mysunshine92** [comment]
cc @liggitt  @deads2k @derekwaynecarr @janetkuo can help to add /approve label, thanks.

**Pull request merged**
