### PR TITLE
fix scheduler extender example

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

Fix scheduler extender example , refer to [kubernetes/plugin/pkg/scheduler/api/types.go](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/api/types.go)

Thanks!
**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37785)

**Comment by bgrant0607** [comment]
@ravigadde: could you please review this?

**Comment by ravigadde** [comment]
LGTM, thanks for fixing this @tanshanshan

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
