### PR TITLE
Update crictl to v1.11.1.

### PR DESCRIPTION
**Pull request by Random-Liu**
Update `crictl` to v1.11.1 to fix several bugs. Release note: https://github.com/kubernetes-incubator/cri-tools/releases/tag/v1.11.1

@kubernetes/sig-node-pr-reviews @kubernetes/sig-cluster-lifecycle-pr-reviews 
@kubernetes/sig-gcp-pr-reviews 
Signed-off-by: Lantao Liu <lantaol@google.com>

```release-note
Update crictl to v1.11.1.
```

### CODE REVIEW

**Comment by feiskyer** [comment]
lgtm
/retest

**Review by luxas — CHANGES_REQUESTED** [review]
/hold
@Random-Liu please update the community debs/rpms as well. Both here in build/ and in k8s/release
cc @chuckha

**Comment by Random-Liu** [comment]
@luxas Thanks for pointing out! Will do.

**Comment by Random-Liu** [comment]
@luxas Do we need to build `build/debs/BUILD`? I feel like as long as `crictl` is `>=1.11.0`, it should be fine.

**Comment by chuckha** [comment]
What luxas is saying is that this bazel build process is not being used, but we keep it up to date. The real debs are built out of [kubernetes/release](https://github.com/kubernetes/release/issues/576). That's an entirely different way of building debs & rpms so you'll have to make the change there in addition to here.

We keep these synchronized hoping that one day we can transition to bazel entirely and not use kubernetes/release.

**Comment by Random-Liu** [comment]
@luxas @chuckha Done. :)

**Comment by yujuhong** [comment]
/assign @luxas 
/assign @chuckha 
for build/debs approval

**Review by luxas — COMMENTED** [review]
@random-liu the cri-tools deb exists in `build/debs/BUILD` file and the rpm in `build/rpms` similarily. Please bump the actual package, not the dependency on the package. Sorry I know it's a bit confusing

**Comment by chuckha** [comment]
@luxas I'm a little confused, the dependency requirement is >= 1.11.0 and since this is commit would build 1.11.1, I think it's ok to leave the dependency requirement as is. Why do you think we need to bump the dependency requirement?

**Comment by Random-Liu** [comment]
@luxas @chuckha I asked this above, whether we need to bump up the requirement. https://github.com/kubernetes/kubernetes/pull/66152#issuecomment-404901702

Based on https://github.com/kubernetes/kubernetes/pull/66152#pullrequestreview-137089083, it seems that I'm supposed to update `build/`.

Anyway, I'll remove the dependency bump up.

**Comment by luxas** [comment]
Finally, I got access to a computer and can link to the location that needs to change in k8s/k8s as well (what I meant earlier but described very vaguely): https://github.com/kubernetes/kubernetes/blob/master/build/workspace.bzl#L15. Please bump that version and then this LGTM :+1:

**Comment by chuckha** [comment]
Need to update RPM as well because of some technical debt as commented https://github.com/Random-Liu/kubernetes/blob/fc003179f053551a261d70ad2d00e3a5d6210ac6/build/rpms/cri-tools.spec#L14

[This was my failed attempt](https://github.com/kubernetes/kubernetes/pull/65281) at cleaning up the duplication of version. It would be great to get something like this incorporated.

**Comment by foxish** [comment]
Waiting for lgtm and approval on this one.

**Comment by Random-Liu** [comment]
@luxas @chuckha Ping for LGTM. :)

@dchen1107 Can you help me approve this PR? Thanks! /cc @yujuhong

**Review by luxas — APPROVED** [review]
/lgtm
/approve
Thanks a lot @random-liu! Now for the next time we have a reference PR and doesn't have to go through all of this back and forth again ;)

**Comment by Random-Liu** [comment]
@foxish Ping for cherrypick approval.

**Pull request merged**
