### PR TITLE
e2e ginkgo timeouts: simplify code

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is in preparation of https://github.com/kubernetes/kubernetes/pull/112923: all changes that introduced `ginkgo.DeferCleanup` were pulled out of that PR into a separate commit. Same with some manual changes to `context.WithCancel`.

Some of the initial commits are cleanups that could also get merged via separate PRs.

This PR is an improvement by itself (for example, more informative test timeline that shows when cleanup operations start) but ultimately the main goal is to simplify that other PR.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/assign @aojea

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve

Mostly mechanical changes moving `defer` functions used to cleanup to the corresponding `ginkgo.DeferCleanup` hook.
Some fixes on the e2e
Some code plumbs the new context in the cleanup and other not, some cleanup use the new helper "IgnoreNotFound", but in general is ok, we are going to do it later anyway, and these chunks are manageable

/lgtm
/approve

/hold

in case @spiffxp or @BenTheElder want to take a look, we can unhold tomorrow EU morning that there is less churn on the CI and have some time with signal

**Comment by aojea** [comment]
/retest

/lgtm cancel

legit failures??? https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114425/pull-kubernetes-e2e-gce-csi-serial/1602313418314878976/

```
I1212 15:28:59.391]     Test Panicked
I1212 15:28:59.391]     In [DeferCleanup (Each)] at: /usr/local/go/src/reflect/value.go:440
I1212 15:28:59.391] 
I1212 15:28:59.391]     reflect: Call using testsuites.topologyTest as type *testsuites.topologyTest
I1212 15:28:59.391] 
I1212 15:28:59.391]     Full Stack Trace
I1212 15:28:59.391]       reflect.Value.call({0x68891c0?, 0xc001650780?, 0x0?}, {0x75ce9e6, 0x4}, {0xc004df88a0, 0x2, 0x0?})
I1212 15:28:59.392]       	/usr/local/go/src/reflect/value.go:440 +0x1abf
I1212 15:28:59.392]       reflect.Value.Call({0x68891c0?, 0xc001650780?, 0x0?}, {0xc004df88a0?, 0x0?, 0x0?})
I1212 15:28:59.392]       	/usr/local/go/src/reflect/value.go:368 +0xbc
```

**Comment by pohly** [comment]
> legit failures???

Yes. I filed [an issue](https://github.com/onsi/ginkgo/issues/1094) and avoided the issue by [explicitly passing a pointer](https://github.com/kubernetes/kubernetes/compare/5fa35e0e3b626be64979a69284ffda61205bc7d8..d4729008ef02e109c561c56ae95c8c10cf68f091).

What we gain in flexibility with `DeferCleanup` we pay for with a loss of compile-time checking. This isn't a problem for tests that run the modified code (it will fail reliably) but it may be a problem for modified tests that only run in some obscure job that no-one pays attention to. OTOH, perhaps such tests then also are less important?

/retest

"Cluster failed to initialize within 300 seconds."

**Comment by pohly** [comment]
/retest

Clusters still fail to come up.

**Comment by pohly** [comment]
However, the failure in pull-kubernetes-e2e-gce-csi-serial is gone.

@aojea can we merge now?

**Comment by aojea** [comment]
> However, the failure in pull-kubernetes-e2e-gce-csi-serial is gone.
> 
> @aojea can we merge now?

/hold cancel
/lgtm

🤞

**Comment by pohly** [comment]
/hold cancel

The bot seems to be a bit deaf right now...

**Pull request merged**
