### PR TITLE
WIP: Add stateful set test reproducing issue with Failed pods

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This is an e2e that demonstrates that fails occasionally for Failed pods, demonstrating that the functionality is broken also for pods which end with Failed phase. Even though it was observed for pods ending in Succeeded phase here: https://github.com/kubernetes/kubernetes/issues/120700.

Here is an example failed run from my local kind: https://gist.github.com/mimowo/0e6e874ca36cf18f0d57aed3f956d81f. The failure rate is around 1/10.

The fix for this flaky test is the same as for: https://github.com/kubernetes/kubernetes/pull/120731. 

We may consider adding an integration test as well to fail 100% times.  

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mimowo** [comment]
/sig apps
FYI @aleksandra-malinowska @adilGhaffarDev @soltysh

**Comment by mimowo** [comment]
Reproduced the same fail on 1.27.0: https://gist.github.com/mimowo/4f3de1c34e2909c428667f6f48dec5ad

**Comment by aleksandra-malinowska** [comment]
@mimowo one more idea (not sure if feasible) - can we manually transition pod to the `Failed` state in test? I know this is not supposed to happen, but would it help with the timing compared to kubelet transitioning pod phase?

**Comment by mimowo** [comment]
> @mimowo one more idea (not sure if feasible) - can we manually transition pod to the `Failed` state in test? I know this is not supposed to happen, but would it help with the timing compared to kubelet transitioning pod phase?


Yes, I used this approach and reproduced it on 1.26.6 using the approach of setting `Failed` on the pod. Here I have a watch on the StatefulSet, and when `.Status.UpdatedReplicas=2` (we have processed pod-2 and pod-1), then I set the phase `Failed` on pod-0. 

The list of options to force pod to be failed prior to 1.27 when `restartPolicy: Always` is quite limited, and these are OOMKill, node pressure eviction, node shutdown, potentially some more, but controlling timings of such events is hard in e2e tests, so setting the phase explicitly for now. Next, I plan to plan earlier versions, but I think the bug was always there, just harder to hit.

**Comment by mimowo** [comment]
Reproduced on 1.25.11: https://gist.github.com/mimowo/f8693625730127207aba6f3b4b107fad

**Comment by mimowo** [comment]
> Reproduced on 1.25.11: https://gist.github.com/mimowo/f8693625730127207aba6f3b4b107fad

Using the same approach / test I was able to reproduce the failure in 1.23 and 1.24, at the rate roughly 1/10 fails.

I could not reproduce it in 1.22 despite 40 retries. I think the difference is that in 1.22 if pod creation fails, then there is no status update after `completeRollingUpdate`. I suspect this is the PR which exposed the bug: https://github.com/kubernetes/kubernetes/pull/112084. Still, it is not clear 100% to me at the moment if this issue can or cannot be reproduced on 1.22, but if it can, then it is very rare.

Given that 1.22 is EOL already I think we wouldn't patch it anyway.

**Comment by mimowo** [comment]
In https://github.com/kubernetes/kubernetes/pull/120921/commits/8548802a601d7d04c2fb1cc93cec362808f88caf I've added a finalizer to the pod0 under test. With this trick I induce 409 on the pod creation (after being removed). This reproduced the issue consistently (I've got 100% failures in around 10 repeats on different versions). So far tested on 1.23.17, 1.26.6, and master. So, it seems we have a reproducible test that demonstrates the issue in old versions. This test will not reproduce the issue on 1.22 as on 1.22 we would not call `completeRollingUpdate` if pod creation fails.

**Comment by mimowo** [comment]
/close
The fix is already merging

**Pull request closed without merging**
