### PR TITLE
Automated cherry pick of #75269: gce: configure: validate SA has storage scope

### PR DESCRIPTION
**Pull request by javier-b-perez**
Cherry pick of #75269 on release-1.14.

#75269: gce: configure: validate SA has storage scope

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @tpepper @aleksandra-malinowska 
/kind bug
/priority critical-urgent
(?)

**Comment by javier-b-perez** [comment]
hi @tpepper @aleksandra-malinowska
can you approve this cherry-pick please?

**Pull request merged**
