### PR TITLE
Remove unused functions in pkg/util/taints/

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove unused functions in `pkg/util/taints/`

ref https://github.com/kubernetes/kubernetes/pull/108332#discussion_r907717831
ref https://github.com/kubernetes/kubernetes/pull/108332#discussion_r968948564

I looked at the source code. In the past, kubectl would use these methods, but then kubectl needs to remove the dependency on the k8s internal library and copy the taints functions to the kubectl  command directory. Since then, these functions have not been used anymore.
xref: 
- https://github.com/kubernetes/kubectl/issues/80
- https://github.com/kubernetes/kubernetes/pull/69446  

The same function as the deleted code exists here in kubectl:
https://github.com/kubernetes/kubernetes/blob/657776e52ba527d8ff04187be4e8743e62909c07/staging/src/k8s.io/kubectl/pkg/cmd/taint/utils.go#L128-L177

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
@mengjiao-liu Thanks for doing this, nice cleanup.

/triage accepted
/lgtm

**Comment by alculquicondor** [comment]
/lgtm
but I don't have approval rights for this

**Comment by oomichi** [comment]
Hello @dims

Could you take a look at this cleanup pr?

**Comment by oomichi** [comment]
Thanks @dims :-)

/test pull-kubernetes-unit

**Comment by alculquicondor** [comment]
Can you please create an issue for the flaky test?

**Pull request merged**
