### PR TITLE
Automated cherry pick of #76988: add shareName param in azure file storage class

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #76988 on release-1.14.

#76988: add shareName param in azure file storage class

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by tpepper** [comment]
I'm worried about the state of azure/storage patch backports. This one is at least smaller than the other size/xl one on the menu right now, but also feels feature-like.

But this one too was set to cherry pick to multiple branches 1.1[234] and is merged in master (1.15)  and 1.12, so it would be really odd to not merge in 1.13 and 1.14. :(

**Comment by andyzhangx** [comment]
hi @tpepper, this PR is a little feature like although it fixed the error issue when original file share exists. Based on the fact that it's already merged into v1.12, can we make it into v1.13, 1.14? 
I think this could be also the reason why k8s would like to move all cloud providers code out of k/k since different cloud provder has different strategy for backport, thanks for understanding.

**Pull request merged**
