### PR TITLE
Updating EndpointSlice validation to match Endpoints validation

### PR DESCRIPTION
**Pull request by robscott**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
This updates EndpointSlice IP validation to match Endpoints validation.

#### Does this PR introduce a user-facing change?
```release-note
Fixes a regression in 1.17 so that EndpointSlice IP validation now matches Endpoints IP validation.
```

/sig network
/priority important-soon
/cc @freehan
/assign @thockin

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by cjcullen** [comment]
https://github.com/kubernetes/kubernetes/issues/102106

**Pull request merged**
