### PR TITLE
pkg/apis: fix staticcheck warning

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
fix staticcheck warning
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
can this package be removed from the staticcheck exceptions list now? we typically fix all staticcheck issues in a package at once and remove the exception to prevent regressions

**Comment by hwdef** [comment]
@liggitt 
Thanks for your suggestion.
I changed it, but I am not sure if it is correct.
Cloud you please review the change

**Pull request merged**
