### PR TITLE
move KEP-3178 IPTablesOwnershipCleanup to GA

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Bump `IPTablesOwnershipCleanup` to GA, remove legacy code, deprecated the now-unused kubelet iptables command-line flags/options

#### Does this PR introduce a user-facing change?
```release-note
The IPTablesOwnershipCleanup feature (KEP-3178) is now GA; kubelet no longer
creates the KUBE-MARK-DROP chain (which has been unused for several releases)
or the KUBE-MARK-MASQ chain (which is now only created by kube-proxy).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3178
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by danwinship** [comment]
sorry, forgot to delete unit test of the deleted code

**Pull request merged**
