### PR TITLE
Fix grammar: have -> has

### PR DESCRIPTION
**Pull request by terrytangyuan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by terrytangyuan** [comment]
I signed it!

**Comment by terrytangyuan** [comment]
This is a simple change. Is there anything I can do to move this forward?

**Review by mortent — APPROVED** [review]
/lgtm

**Comment by terrytangyuan** [comment]
Could anyone merge this now that it's approved? Thanks.

**Comment by mortent** [comment]
It still needs approval from @tnozicka

**Pull request merged**
