### PR TITLE
[DO NOT MERGE] Kubenet allow podcidr change

### PR DESCRIPTION
**Pull request by dcbw**
PR for discussion; if we want to cleanly teardown old pods with previous CIDRs, I think we have to cache the network config the pods were setup with so that CNI's host-local can release the IP from the right store.

See https://github.com/kubernetes/kubernetes/issues/32900

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33132)

### CODE REVIEW

**Comment by dcbw** [comment]
@thockin @bprashanth Allowing podcidr change isn't a technical issue, it's more about deciding what's acceptable when dealing with old pods.  Theoretically you could increase the CIDR range from eg 192.168.1.0/29 -> 192.168.1.0/24 and the old pods would still work just fine (assuming there were no conflicts within the cluster), but obviously 192.168.x -> 10.x will break connectivity for old pods.

**Comment by thockin** [comment]
I still think it would be better to not start pods until we get a node.spec.podCIDR

**Comment by dcbw** [comment]
> I still think it would be better to not start pods until we get a node.spec.podCIDR

@thockin that's already done; there are checks in the Add call to return an error if "plugin.netConfig == nil".  The netConfig is only generated when we have a podCIDR.  What this PR does is allow the podCIDR to change from something -> something else.

**Comment by thockin** [comment]
We already disallow node.podCIDR to change, don't we?  So the issue is
between --pod-cdir (which is documented as standalone mode) and
node.podCIDR (which is not-standalone mode).

**Comment by freehan** [comment]
> So the issue is between --pod-cdir (which is documented as standalone mode) and
node.podCIDR (which is not-standalone mode).

Yeah. Master on GCE gets stuck in the middle. It gets `node.podCIDR` and network route, but it is using `pod-cidr`.  

I feel like allowing podCIDR to change is too complicated. I propose an alternative approach: 

1. For registered master like on GCE, master use the assigned podCIDR and no network route. (Do we expect pods on master to be routable?) 
2. Modify kubenet to unblock kubelet for running hostnetwork pods. This can solve the chicken-egg problem. Master component will start up and assigned itself a podCIDR range. Then the nonhostnetwork pods like fluentd can come up.

Thoughts?

**Comment by dcbw** [comment]
> We already disallow node.podCIDR to change, don't we? So the issue is between --pod-cdir (which is documented as standalone mode) and node.podCIDR (which is not-standalone mode).

@thockin @freehan ok, seems there's two separate issues here, maybe we move back to #32900 for a bit to separate them?

**Comment by dcbw** [comment]
> We already disallow node.podCIDR to change, don't we? So the issue is between --pod-cdir (which is documented as standalone mode) and node.podCIDR (which is not-standalone mode).

@thockin --pod-cidr is documented as such, but nothing in kubelet code stops you from passing --pod-cidr and then listening to the apiserver for changes too.  Perhaps kubelet should exit if --pod-cidr and --api-servers are both given?  Either that or we should make them work with each other like this PR does.

**Comment by justinsb** [comment]
> For registered master like on GCE, master use the assigned podCIDR and no network route. (Do we expect pods on master to be routable?)

I think we _do_ want pods to be routable - for example we would like fluentd to run as a daemonset, but to send logs to elasticsearch running as a k8s service.

> Modify kubenet to unblock kubelet for running hostnetwork pods. This can solve the chicken-egg problem. Master component will start up and assigned itself a podCIDR range. Then the nonhostnetwork pods like fluentd can come up.

I think this sounds like the cleanest and least surprising solution.   Though it is "so obvious" I worry why we didn't do it in the first place (i.e. what are we missing - why did we introduce the fake PodCIDR on the master?)

**Comment by justinsb** [comment]
Tried implementing your idea @freehan and it seems to work well: https://github.com/kubernetes/kubernetes/pull/33347

**Comment by dcbw** [comment]
I think I'm going to close this in favor of https://github.com/kubernetes/kubernetes/pull/33347

**Pull request closed without merging**
