### PR TITLE
Verify generated files

### LINKED ISSUE #33751: hack/verify-codegen.sh should fail if openapi model is not generated correctly
Right now on head (24031f50d6610dc9f695398893d3e6459957ee6e) if you run 

```
make generated_code
```

it will end up having a modified pkg/generated/openapi/zz_generated.openapi.go file. This happened because some type has been changed and this file should have been generated before commit, and verification should have failed but they didn't.

### PR DESCRIPTION
**Pull request by thockin**
Fixes #33751 

Once I un-check-in generated files, this becomes moot again.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33819)

### CODE REVIEW

**Comment by mbohlool** [comment]
I've tried this on 24031f50d6610dc9f695398893d3e6459957ee6e and I expected it to fail but it didn't. When I run 

```
make clean_generated generated_files
```

it will end up having pkg/generated/openapi/zz_generated.openapi.go changed and  

```make verify_generated_files ```

(before or after or on a clean checkout) will succeed.

**Comment by mbohlool** [comment]
interesting, on the same commit, "make verify" fails with the exact failure I expected, but make verify_generated_files won't fail. is that expected?

**Comment by thockin** [comment]
make verify just calls verify_generated_files - show me later?

**Comment by thockin** [comment]
New commit added - PTAL

**Comment by thockin** [comment]
DO NOT COMMIT - I found a bug

**Comment by mbohlool** [comment]
@thockin Any updates on this?

**Comment by thockin** [comment]
I have not had time to circle back.  The bug is that recursive MAKE
triggers `.todo` files to be removed.

**Comment by thockin** [comment]
PTAL, we'll see how CI handles it.

**Comment by mbohlool** [comment]
Look like this one is working, /lgtm

**Comment by thockin** [comment]
@k8s-bot node e2e test this

**Comment by thockin** [comment]
rebased

**Pull request merged**
