### PR TITLE
Fix some typo

### PR DESCRIPTION
**Pull request by max8899**
**What this PR does / why we need it**:
Fix some error strings in files

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

Signed-off-by: Lei Gong <lgong@alauda.io>

### CODE REVIEW

**Comment by mengqiy** [comment]
These are not typos. 
/close
Some explanation: https://www.englishpage.com/articles/a-vs-an.htm

**Comment by max8899** [comment]
@mengqiy so can you explain why? For an url is the correct grammar

**Comment by mengqiy** [comment]
You only need to use `an` when a word starts with a vowel sound (not letter).

An example is in [wikipedia](https://en.wikipedia.org/wiki/URL). You will find `a url`.

**Comment by max8899** [comment]
@mengqiy it's ok to close, actually, the `u` pronounced with `y` first

**Pull request closed without merging**
