### PR TITLE
Add a flag that will make test gather metrics from all running components after the test finishes.

### PR DESCRIPTION
**Pull request by gmarek**
Builds on top of #19058. Please review only last commit.

cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
Generally looks good - I will take one more look once the other PR is merged and this one is rebased.

**Comment by gmarek** [comment]
Previous PRs are merged. @wojtek-t PTAL

**Comment by wojtek-t** [comment]
LGTM

**Comment by gmarek** [comment]
`ERROR: Error fetching remote repo 'origin'`

@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
