### PR TITLE
Deleting OperationHandler for handling /operation endpoint on server

### PR DESCRIPTION
**Pull request by nikhiljindal**
Part of https://github.com/GoogleCloudPlatform/kubernetes/issues/3644

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks.

I had been assuming that we would not break compatibility in v1beta1/2. However, if nobody is really using /operations, we could. Not sure how to figure that out -- I haven't found anything useful via web search. For now, we could start by making /operations registration optional, and disable it in v1beta3.

Also, we shouldn't return operations, either, then. Otherwise, users won't have any way to find out the statuses of their requests. This is probably the first thing we have to do. We need to deprecate the `sync` parameter and force all requests to be synchronous:
https://github.com/GoogleCloudPlatform/kubernetes/blob/24e59de06e4da61f5dafd4cd84c9340a2c0d112f/pkg/apiserver/resthandler.go#L152

Status would then only be returned for errors.

I assume Go's mux handles requests concurrently by default, so "long" running requests shouldn't block other requests.

Once we no longer need operations, then we can rip out the handler registration, and the actual operations code:
https://github.com/GoogleCloudPlatform/kubernetes/blob/24e59de06e4da61f5dafd4cd84c9340a2c0d112f/pkg/apiserver/resthandler.go#L311
https://github.com/GoogleCloudPlatform/kubernetes/blob/9b40c52c249fc6ed5e523af0442c25e2c0f02b0b/pkg/apiserver/operation.go#L97

The current operations behavior could be effectively be replaced by events: #3692.

Useful waiting behavior would be replaced by new "reification" events and/or watching status fields: #1899.

/cc @smarterclayton

**Comment by smarterclayton** [comment]
We probably don't need to even leave backwards compat, because the only way you get an operation is to get one from a response.  The server already makes a decision whether to delay you for a real response, so every request has the potential to return a response immediately, so clients not handling that would be broken today.  We could leave the operation endpoints, but merely have them return empty.  Everything else can simply be ripped out wholesale (I think).

The muxes are concurrent.

**Comment by nikhiljindal** [comment]
ok. Thanks for the detailed explanation.
I will send a different PR then, which first forces all requests to be synchronous so that we do not return operations to clients.
Once that is submitted, then we can come back to this PR to remove the handler registration.

**Comment by nikhiljindal** [comment]
I messed up in merging/rebasing.
This branch seems corrupted beyond repair. Will send this PR again.

**Pull request closed without merging**
