### PR TITLE
kubeadm: use T.Run API in test/cmd

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Used [T.Run API](https://golang.org/pkg/testing/#T.Run) for kubeadm tests in cmd/kubeadm/test/cmd/

This should improve testing output and make it more visible
which test is doing what.

**Special notes for your reviewer**:

This is a first PR of a series aiming to usage of [T.Run API](https://golang.org/pkg/testing/#T.Run)  in all kubeadm tests. If this is accepted I'll send more PRs of this kind. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — APPROVED** [review]
Thanks @bart0sh 
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh thanks for this cleanup!
/approve
/lgtm

**Pull request merged**
