### PR TITLE
Implement FakeVolumePlugin's ConstructVolumeSpec method according to interface expectation.

### LINKED ISSUE #45803: kubelet unit test flake
here is one such instance where kubelet unit tests are failing
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45798/pull-kubernetes-unit/30523/

### PR DESCRIPTION
**Pull request by rohitagarwal003**
This fixes #45803 and #46204.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@k8s-bot ok to test

**Comment by msau42** [comment]
Will this actually fix the underlying problem of the volume reconstruction picking up a volume from a different test?  Could the tests still flake if they detect some volume that shouldn't be there?

Maybe we also need to add directory cleanup as part of the setup so that we don't pick up leftover volumes.

**Comment by mindprince** [comment]
The failures seem unrelated.

@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by mindprince** [comment]
@msau42 This will fix the current reason behind the failing tests.

If the tests still flake after this, we will hopefully get a better error message which would help in debugging which tests are leaving artifacts behind. We can fix those tests then.

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by mindprince** [comment]
Not going to retry `pull-kubernetes-federation-e2e-gce`, just saw that it hasn't passed in most of the last runs: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-federation-e2e-gce

`pull-kubernetes-e2e-gce-etcd3` is also failing around half the time: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-etcd3

**Comment by msau42** [comment]
It could potentially cause false positives as well.  If the tests use the same pod and volume names, then picking up a stale volume from a previous test and thinking it's a volume for the current test could mask bugs.

**Comment by mindprince** [comment]
Updated the PR to add `Cleanup()` call to couple of tests which were missing it.

**Comment by mindprince** [comment]
`pull-kubernetes-node-e2e` started failing from 31905 and hasn't had a green build yet (till 31952), https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e

:(

**Comment by jingxu97** [comment]
I think you need approve from kubelet owner like @yujuhong

**Comment by mindprince** [comment]
I need approval from a `kubelet` owner and a `volume/testing` owner.

**Comment by saad-ali** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by saad-ali** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by mindprince** [comment]
@saad-ali @msau42 Can we cherry-pick this to 1.6 branch as well? There were flakes in `ci-kubernetes-test-go-release-1.6` job as well because of this.

**Pull request merged**
