### PR TITLE
scheduler: remove import pkg/api/v1/pod.GetPodPriority

### PR DESCRIPTION
**Pull request by yiyang5055**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref: #89930 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by yiyang5055** [comment]
sig/scheduling

**Review by wgliang — APPROVED** [review]
/ok-to-test
/lgtm

**Review by damemi — CHANGES_REQUESTED** [review]
I see that the only other place `GetPodPriority` is used is from `pkg/kubelet/eviction/helpers.go` in the `priority` function. Could you update this package to call the new scheduler util function directly?

**Comment by damemi** [comment]
Actually, I see that this package is already covered by https://github.com/kubernetes/kubernetes/pull/90039. In that case we might close this as a dupe if we can get that merged, but thank you for your contribution @yiyang5055

**Comment by yiyang5055** [comment]
> Actually, I see that this package is already covered by #90039. In that case we might close this as a dupe if we can get that merged, but thank you for your contribution @yiyang5055

That's unfortunate!  I close this PR

**Pull request closed without merging**
