### PR TITLE
docs/reference: Fix typo GroupPriorityMinimum

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the contribution. This is generated from the types.go files containing the type definitions. You'll need to find/replace the typo in those source files as well.

**Comment by qingsenLi** [comment]
$ bash hack/update-generated-docs.sh
!!! [1110 11:27:22] Unsupported host OS.  Must be Linux or Mac OS X.
/close
Sorry,windows system unsupport to update,close this PR.
Others can help to fix the typo.

**Pull request closed without merging**
