### PR TITLE
Automated cherry pick of #48854

### PR DESCRIPTION
**Pull request by seanknox**
Cherry pick of #48854 on release-1.7.

#48854: azure: msi: add managed identity field, logic

### CODE REVIEW

**Comment by seanknox** [comment]
FYI @wojtek-t, per @colemickens's commit, this allows kubelet to use tokens from Azure instead of the previous hard-coded, user-specified credentials. cc @brendandburns @jdumars

**Comment by wojtek-t** [comment]
@seanknox - this seems more like a feature than bug fix to me. We generally don't want to backport features - patch releases are restricted to bug fixes.

**Comment by jdumars** [comment]
@brendandburns did you have more context to add on this?

**Comment by brendandburns** [comment]
@wojtek-t this is sort of a feature, but it definitely is more of a "take advantage of new platform capabilities", rather than an all-up new feature.

there are several equivalent PRs for gcp already in the branch, e.g.:
   * https://github.com/kubernetes/kubernetes/commit/01aabbf2fa6a4d59d5ac372da84f480f2e2a1509
   * https://github.com/kubernetes/kubernetes/commit/420e421c2a21470d8e10b929068e5a18b1e42764

I guess I never thought the cherry-pick bar was "bug fix only", I thought it was: low-risk quality improvements we want for our mainline "stable" release.  Since the cadence is 3 months, restricting to bug fix only really slows the roll out of safe, small improvements to a "stable" release, and doesn't match my recollection of processes in the past.

thanks
brendan

**Comment by wojtek-t** [comment]
>  I thought it was: low-risk quality improvements

Agree with that. If you believe it's in this category, I'm fine with that.

**Comment by wojtek-t** [comment]
@brendandburns - I approved cherrypick. Please LGTM it to have it merged.

**Comment by brendandburns** [comment]
/lgtm

thx!



________________________________

**Pull request merged**
