### PR TITLE
Clean up nits in delete cascade flag parsing

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR is a little clean up to previous commit to address the comments:
https://github.com/kubernetes/kubernetes/pull/93384#discussion_r479438005
https://github.com/kubernetes/kubernetes/pull/93384#discussion_r494396372
https://github.com/kubernetes/kubernetes/pull/93384#discussion_r494400309

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/assign @soltysh

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
