### PR TITLE
Changing ─ (U+2500) to ASCII hyphen in describe command

### LINKED ISSUE #17364: "kubect describe jobs" include garbage charactor
# kubectl describe jobs/pi
Name:           pi
Namespace:      default
Image(s):       perl
Selector:       app in (pi)
Parallelism:    1
Completions:    1
Labels:         app=pi
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen     LastSeen        Count   From    SubobjectPath   Reason                  Message
  鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€   鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€        鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€    鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€鈹€鈹€    攢鈹€鈹€鈹€鈹€鈹€鈹€
  3m            3m              1       {job }                  SuccessfulCreate        Created pod: pi-jw7q9

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #17364

@janetkuo ptal

### CODE REVIEW

**Comment by soltysh** [comment]
Looking into the failures...

**Comment by soltysh** [comment]
I haven't seen those failures locally, closing and reopening the PR.

**Comment by janetkuo** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
cc @kubernetes/rh-ux

**Pull request merged**
