### PR TITLE
Add PodAntiAffinity predict to kubelet Admit

### LINKED ISSUE #65257: Antiaffinity pods scheduled to the same node during scheduler leader-election
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Two pods with AntiAffinity label are scheduled to the same node.

**What you expected to happen**:
Two pods with AntiAffinity label are scheduled to different nodes.

**How to reproduce it (as minimally and precisely as possible)**:
na

**Anything else we need to know?**:
The bug is caused by scheduler during leader switch.
Here is what happened:
Suppose there are two schedulers, **SA(active), SB(standby)**. Two pods with antifinity **PA, PB**. Two nodes **NA, NB**. 
1. SA failed to renew the lease.
2. SB became active scheduler.
3. SA's main thread didn't quit ontime, it scheduled PA to NA and then quited. 
4. SB scheduled PB to NA because it didn't know PA has already been scheduled.
5. The final state is that PA and PB were both on node NA.

Here is the log of SA:
SA: tw-node2221, SB: tw-node2222.
SA lost election at **16:03:35** but continued to schedule pods until found conflicts in cache and then quited.
image

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.5.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
4.4.64-1.el7.elrepo.x86_64
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by DylanBLE**
**What this PR does / why we need it**:
Scheduler may assign pods with AntiAffinity to the same node.
See issue #65257 
By adding PodAntiAffinity Predict to kubelet Admit, kubelet will prevent such AntiAffinity error.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65257 

**Special notes for your reviewer**:
Add 
**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yastij** [comment]
cc @resouer @bsalamat

**Comment by DylanBLE** [comment]
cc @Random-Liu @derekwaynecarr

**Comment by resouer** [comment]
Thanks, but I would prefer the original issue been fixed by leader select side patch. Adding more predicates in kubelet admit is definitely not what we'd like to see.

**Comment by resouer** [comment]
@DylanBLE There're cases that Pods been created even without scheduler is running, e.g. static pods, and that explains a predicate should be "general" in order to be included in node side.

**Comment by DylanBLE** [comment]
@resouer Got it, thanks.

**Comment by dims** [comment]
/close

please reopen if needed

**Pull request closed without merging**
