### PR TITLE
Automated cherry pick of #101118 upstream release 1.21 

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #103697

```release-note
NONE
```

/kind bug
/priority important-soon
/sig cloud-provider

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers 

this is needed to make 1.21 → 1.22 upgrade test jobs pass again... if possible, it should be included in the 1.21 patch release

**Review by cpanato — APPROVED** [review]
from RelEng:
/lgtm

**Pull request merged**
