### PR TITLE
Export PrintOptions struct

### LINKED ISSUE #19865: cannot register print handler function with non-exported printOptions param
In resource_printer.go, printers for additional types can be registered. However, the signature of the function must include a `printOptions` parameter. This type is not exported, which means other packages cannot register printers.

This should be exported (along with the fields, so called printer functions can use the options):
```
type printOptions struct
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #19865

### CODE REVIEW

**Comment by liggitt** [comment]
@jlowdermilk PTAL

**Comment by liggitt** [comment]
@k8s-bot test this please

**Comment by jlowdermilk** [comment]
@k8s-bot e2e test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
@k8s-bot e2e test this

**Pull request merged**
