### PR TITLE
[WIP] [Do Not Checkin] L7 loadbalancing

### PR DESCRIPTION
**Pull request by bprashanth**
This pr is meant to short-circuit questions about implementation brought up on the l7 proposal. I don't intend to check it in as is.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Is this API proposal up to date?

**Comment by alfred-huangjian** [comment]
@bprashanth 
We have finished most of the api code except validation till now. And we need to add more test-cases on that. The first cut are all supposed to be finished soon and ready for back and forth.

Current Code is at https://github.com/alfred-huangjian/kubernetes/commits/l7-rebased
It works now：
<pre>
$ kubectl get ingresspoints
NAME      HOST      DOMAIN         PATH      SERVICE:NAME   SERVICE:NAMESPACE   SERVICE:PORT
echomap   echo      foo.echo.com   /x/*      echoheadersx   default             80
echomap   echo      foo.echo.com   /y/*      echoheadersy   default             80
echomap   echo      bar.echo.com   /x/*      echoheadersx   default             80
</pre>

As the other pr/commit depends on the API Type Definition. So next step, I will create a new PR to kubernetes for api type review first?

**Comment by bprashanth** [comment]
@alfred-huangjian great! yep lets do that, get a wip up with what you have and we can iterate. 

If multiple people handled different chunks, they can each get a wip up, or we can do a single one with many commits, really upto you. As long as it's clear which ones need to go in first so we don't end up with a broken tree in between.

**Comment by bprashanth** [comment]
@alfred-huangjian fyi since the new resource will be experimental to begin with https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/tXktpK0TUXg/4FZbW45DAgAJ

Also I'd encourage you to get the basic apiobject uploaded as a wip asap, so we can get more eyes on it.

**Comment by alfred-huangjian** [comment]
@bprashanth OK, I will bring up the a PR with the basic api type first.

**Comment by wojtek-t** [comment]
@bprashanth - what's the status of this PR? Can we close it?

**Comment by bprashanth** [comment]
Yeah sorry, this is already in as an L7 controller in contrib

**Pull request closed without merging**
