### PR TITLE
Automated cherry pick of #14626 upstream release 1.1

### PR DESCRIPTION
**Pull request by j3ffml**
Pick #14626. Somewhat manual to regen docs and fix merge conflict.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@jackgr pls comment "I signed it" to appease mergebot.

**Comment by jackgr** [comment]
I signed it

**Comment by jlowdermilk** [comment]
Hmmm. seems the apply kubectl command doesn't handle retries. @k8s-bot test this

**Comment by bgrant0607** [comment]
@jlowdermilk Please file an issue re. retries.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
cc @brendandburns

**Pull request merged**
