### PR TITLE
Support input streams being returned by the APIserver

### PR DESCRIPTION
**Pull request by smarterclayton**
Sets proper mime types on the response, sets the stage for transforming
query parameters into a structured object.

Extracted from #5763

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
minor go doc nits, but otherwise LGTM

**Comment by derekwaynecarr** [comment]
kick travis or shippable

**Comment by derekwaynecarr** [comment]
Failure on go 1.4 for travis and shippable

**Comment by smarterclayton** [comment]
I think the failure was a flake caused by a timeout that was too short for travis (when its cpu loaded).  Bumped that timeout, will see if it reflakes.

**Comment by derekwaynecarr** [comment]
All green.

**Pull request merged**
