### PR TITLE
start k8s master by pod for ubuntu scripts

### PR DESCRIPTION
**Pull request by wangzhezhe**
Just as @resouer mentioned in  [#23241](https://github.com/kubernetes/kubernetes/issues/23241#issuecomment-232616567), this pr add the capability to start the kube-controller-manager and kube-scheduler in a pod for ubuntu scripts. 
if set the env STARTING_BY_CONTAINER=true the kube-controller-manager and kube-scheduler will started by a pod when the node identity is ai , if set the env STARTING_BY_CONTAINER=false, the component will be started in original upstart way.

```
$ export KUBE_VERSION=1.3.0
$ export FLANNEL_VERSION=0.5.0
$ export ETCD_VERSION=2.2.0
$ export nodes="parallels@10.211.55.5"
$ export role="ai"
$ export NUM_NODES=${NUM_NODES:-1}
$ export SERVICE_CLUSTER_IP_RANGE=192.168.3.0/24
$ export FLANNEL_NET=172.16.0.0/16
$ export STARTING_BY_CONTAINER=true
$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

...

Validating parallels@10.211.55.5parallels@10.211.55.5's password: 
parallels@10.211.55.5's password: 
parallels@10.211.55.5's password: 

Using master 10.211.55.5
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/parallels/.kube/config
... calling validate-cluster
Found 1 node(s).
NAME          STATUS    AGE
10.211.55.5   Ready     38s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://10.211.55.5:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.


# ./kubectl get pod
NAME                     READY     STATUS    RESTARTS   AGE
k8s-master-10.211.55.5   2/2       Running   2          3m
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29180)

### CODE REVIEW

**Comment by resouer** [comment]
ok to test

**Comment by resouer** [comment]
I think there' no reason to keep the upstart way, it makes scripts hard to maintain, and can not be used on newer Ubuntu. I hope this PR can narrow down the scope of deploy scripts to focus on maintaining kubelet, and also works on Ubuntu 15.

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
@dalanlan

**Comment by eparis** [comment]
@jainvipin

**Comment by eparis** [comment]
I thought we had said 'no new features in `/cluster`' All work was moving to https://github.com/kubernetes/kube-deploy/ is that still the case @luxas

**Comment by jainvipin** [comment]
I share the view that for multi-host installation, using ansible/salt or equivalent is more suitable. The scripts as @resouer pointed out wouldn't work for newer versions of ubuntu where upstart has been deprecated and things are systemd based. `contrib` https://github.com/kubernetes/contrib is the place where all those are kept. If there is a need we should simplify those and/or make it easy to use.

**Comment by luxas** [comment]
@eparis Yes, no new features should be allowed to `/cluster`.

@kubernetes/sig-cluster-lifecycle is working on a totally "new" way of bootstrapping a cluster, and things will be a lot different hopefully already in v1.4, but even better in v1.5, when we've come up to speed.

So, @wangzhezhe what's really the difference between:
a) docker-multinode vs this ubuntu deployment
b) kubernetes-anywhere vs this ubuntu deployment

I think they're quite similar. If there is something that Kubernetes really needs; it's fewer deploments and a more streamlined and focused effort. Can you investigate the differences and see if we can merge this ubuntu setup with docker-multinode or kubernetes-anywhere; or if we should just move the whole ubuntu deployment to kube-deploy.
WDYT?

**Comment by wangzhezhe** [comment]
The start-up sequence and configuration for major components are quite similar for the scripts you mentioned above except the start way(docker, upstart or systemd)
Maybe it is  appropriate to merge the ubuntu scripts with docker-multinode way just as @resouer  said, It will be more convenient to maintain this script in the long term.@luxas

**Comment by wangzhezhe** [comment]
It's better to start a new pr to do this.

**Pull request closed without merging**
