### PR TITLE
pkg/controller: Replace deprecated func usage from the `k8s.io/utils/pointer` pkg

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/pull/111585 and https://github.com/kubernetes/kubernetes/pull/111585#issuecomment-1214203495.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm
(I'm not an approver for this package)

**Comment by ialidzhikov** [comment]
@soltysh, I now rebased the PR.

**Comment by soltysh** [comment]
> @soltysh, I now rebased the PR.

Well that was fast - thx!

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
