### PR TITLE
Automated cherry pick of #79412: fix KubeletConfiguration apiVersion

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #79412 on release-1.15.

#79412: fix KubeletConfiguration apiVersion

### CODE REVIEW

**Comment by BenTheElder** [comment]
@neolit123 this isn't super important but [`godoc`](https://godoc.org/golang.org/x/tools/cmd/godoc) locally will serve bad docs without this when looking at the release 1.15 branch. 

I'm not sure who else does this, but I use this to browse old API docs when making sure kind supports old kubeadm config. Especially since even "the same apiversion" may have differences between releases...

**Comment by neolit123** [comment]
we discussed at some point potential ways of serving godocs for older branches, but one of the solutions had issues. i forgot what it was but @fabriziopandini 

we also had a tracking issue but i can't find it.

> I'm not sure who else does this, but I use this to browse old API docs when making sure kind supports old kubeadm config. Especially since even "the same apiversion" may have differences between releases...

i think the other k/k APIs serve godocs on master only too.

**Comment by BenTheElder** [comment]
Right, but you can serve godoc from your local sources which at least _works_. For a more convenient solution we probably need to generate static content and serve per-kubernetes vesrion in k/website

I've found in practice I need to look at the old types etc to make sure I'm only using what exists for that release.

**Comment by neolit123** [comment]
it is definitely a problem. when v1alpha3 got removed from master the docs for it were gone too, so any potential users were left without docs. yet oddly i don't think we got any complains, maybe people moved to v1beta1 fast enough.

we just don't have a way to serve godocs for the old branches right now, and we haven't spoken with sig-docs about it.

> Right, but you can serve godoc from your local sources which at least work

i don't think we have users that do that. maybe there are...

i'm +1 on this but will defer to Fabrizio who is back next week, as we blocked backporting godoc fixes before.

/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
@BenTheElder thanks for the cherry pick
/lgtm
/approve

@neolit123 the issue was https://github.com/kubernetes/kubeadm/issues/1307
Best chance here IMO is the work on godoc/version upstream. I think it is also doable to document @BenTheElder approach to get an old local sources to serve documents

**Pull request merged**
