### PR TITLE
Deprecate PredicateMetadata

### LINKED ISSUE #86290: Deprecate PredicateMetadata [Migration Phase 2]
/assign @ahg-g 
/sig scheduling
/priority important-soon

Part of #85822

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Deprecates PredicateMetadata since it is now completely replaced with PreFilters.

**Which issue(s) this PR fixes**:
Fixes #86290

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @Huang-Wei

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
LGTM. Will /lgtm when #86284 gets merged.

**Comment by ahg-g** [comment]
> LGTM. Will /lgtm when #86284 gets merged.

rebased.

**Comment by hectorj2f** [comment]
@ahg-g We are using predicates in cluster-autoscaler, what would you recommend as a replacement for those ?

**Comment by haosdent** [comment]
@hectorj2f could refer to https://github.com/kubernetes/autoscaler/issues/2645

**Comment by hectorj2f** [comment]
oh! I totally missed it, thanks @haosdent

**Pull request merged**
