### PR TITLE
Automated cherry pick of #11329

### PR DESCRIPTION
**Pull request by brendandburns**
@zmerlynn @a-robinson @thockin @davidopp

### CODE REVIEW

**Comment by a-robinson** [comment]
LGTM, but @zmerlynn is the cherry-pick guru so assigning to him

**Comment by zmerlynn** [comment]
Cross-link #11329

**Comment by zmerlynn** [comment]
Shippable is stuck. :P

**Comment by thockin** [comment]
LGTM

**Comment by zmerlynn** [comment]
Cool, just wanted to see Shippable pass. Merging.

**Pull request merged**
