### PR TITLE
Informer: should not mix error with non-exist case

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by davidopp** [comment]
reassigning to @lavalamp

**Comment by lavalamp** [comment]
What is the motivation for this change?

**Comment by hongchaodeng** [comment]
I'm confused by the code. If `Get` returns error, instead of returning the error, the logic slides into `Update`, which looks inappropriate.

**Comment by lavalamp** [comment]
I can't recall totally at this point, but I think that's quite possibly intentional. Given how much we rely on this code, I'm hesitant to change this unless it's actively causing a problem. If you can provide a unit test illustrating the difference, that would be helpful.

**Comment by hongchaodeng** [comment]
I would like to provide some test. But I'm working on other stuff atm.
Closing this right now. I would come back to this as part of etcd work.

**Pull request closed without merging**
