### PR TITLE
Upgraded heapster to v0.18.1, influxDB to v0.8.9, and Grafana to v2.0.

### PR DESCRIPTION
**Pull request by vishh**
#14105

### CODE REVIEW

**Comment by vishh** [comment]
cc @jszczepkowski @piosz @mwielgus

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
ok to test

**Comment by vishh** [comment]
@dchen1107: Marking this PR as a WIP until I get the e2e to pass.

**Comment by jszczepkowski** [comment]
@k8s-bot test this again

**Comment by jszczepkowski** [comment]
Monitoring e2e test is failing, because RC for influxdb/grafana is not created, because it has an illegal name "monitoring-influxDB-grafana-v2":

Monitoring
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:49
  should verify monitoring pods and all cluster nodes are available on influxdb using heapster. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:48

  Expected error:
      <*errors.errorString | 0xc208407760>: {
          s: "expected to find one replica for RC with label influxGrafana but got 0",
      }
      expected to find one replica for RC with label influxGrafana but got 0
  not to have occurred

**Comment by jszczepkowski** [comment]
Renaming monitoring-influxDB-grafana-v2 -> monitoring-influxdb-grafana-v2 didn't helped and e2e monitoring test is still failing when run on my private e2e cluster. This time InfluxDB container is crash-looping silently (without giving any reasons in docker logs).

@vishh If we will not manage to sort this PR out today, we are going to bump only the heapster version (PR #14105 or similar, w/o influxdb & graphana) as we badly need model API to be turned on.

**Comment by vishh** [comment]
I will get this PR through today.

**Comment by dchen1107** [comment]
LGTM

I re-run the shippable for this PR. Will merge once it is green.

**Comment by vishh** [comment]
Thanks @dchen1107 for the quick merge!

**Comment by jszczepkowski** [comment]
@vishh Great thanks for finishing this!

**Pull request merged**
