### PR TITLE
audit: fix fuzzer

### LINKED ISSUE #51908: TestRoundTrip flakes
possibly related to https://github.com/kubernetes/kubernetes/pull/51797 or https://github.com/kubernetes/kubernetes/pull/51719

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51904/pull-kubernetes-unit/51796/artifacts/junit_f7172f2cb122b44f1a8919fff68dd59e6d916b66_20170904-152944.stdout

```
	roundtrip.go:216: 	round tripping to audit.k8s.io/v1alpha1, Kind=Event v1alpha1.Event
	roundtrip.go:332: Event: diff: 
		object.ObjectRef.APIGroup:
		  a: "ÃˆÇ·Ã‘Ê¢è–‹t:éƒˆé¸ç¤Ä+hÆº"
		  b: "ÃˆÇ·Ã‘Ê¢è–‹t:éƒˆé¸ç¤Ä+hÆº/bÉªsÄå·«å©ç•²æ±žæ…‰Ê„ç‘†Å¬&"
		object.ObjectRef.APIVersion:
		  a: "bÉªsÄå·«å©ç•²æ±žæ…‰Ê„ç‘†Å¬&/"
		  b: ""
		Codec: &versioning.codec{encoder:(*json.Serializer)(0xc4202ea940), decoder:(*recognizer.decoder)(0xc42029d880), convertor:runtime.unsafeObjectConvertor{Scheme:(*runtime.Scheme)(0xc4202ea1c0)}, creater:(*runtime.Scheme)(0xc4202ea1c0), copier:(*runtime.Scheme)(0xc4202ea1c0), typer:(*runtime.Scheme)(0xc4202ea1c0), defaulter:(*runtime.Scheme)(0xc4202ea1c0), encodeVersion:schema.GroupVersions{schema.GroupVersion{Group:"audit.k8s.io", Version:"v1alpha1"}}, decodeVersion:runtime.internalGroupVersioner{}}
		Source:
		
		"(*audit.Event){TypeMeta:(v1.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(v1.ObjectMeta){Name:(string)RÉ‰È©È.o_V GenerateName:(string)!gÇ‰Ç”ÄæªŽæ¼“ç¹Žè‚²)ç†¦Ã˜æ¨æœ³Ã‘7_J Namespace:(string) SelfLink:(string)Ã¼èˆŠæ²ŠÉ“ UID:(types.UID)åšº ResourceVersion:(string)13176268021741830527 Generation:(int64)0 CreationTimestamp:(v1.Time){Time:(time.Time){sec:(int64)0 nsec:(int32)0 loc:(*time.Location)<nil>}} DeletionTimestamp:(*v1.Time)<nil> DeletionGracePeriodSeconds:(*int64)<nil> Labels:(map[string]string)<nil> Annotations:(map[string]string)<nil> OwnerReferences:([]v1.OwnerReference)<nil> Initializers:(*v1.Initializers)<nil> Finalizers:([]string)<nil> ClusterName:(string)} Level:(audit.Level)é¤–ÉƒvÃƒÈ±{ç¼®Ã…Xåž¯Ã‚Å“]Ç”dÈžé´» Timestamp:(v1.Time){Time:(time.Time){sec:(int64)78415064999 nsec:(int32)0 loc:(*time.Location){name:(string)Local zone:([]time.zone)[{name:(string)UTC offset:(int)0 isDST:(bool)false}] tx:([]time.zoneTrans)[{when:(int64)-9223372036854775808 index:(uint8)0 isstd:(bool)false isutc:(bool)false}] cacheStart:(int64)-9223372036854775808 cacheEnd:(int64)9223372036854775807 cacheZone:(*time.zone){name:(string)UTC offset:(int)0 isDST:(bool)false}}}} AuditID:(types.UID) Stage:(audit.Stage)è™žæ‘³å²˜è®¡ RequestURI:(string)æµ³Hç°¿fÈ’sÆ‹Âª<é»µ'QÊƒå„µ#/cäº²G Verb:(string)k_Ê–lÈƒå jå½“EÂ¡Ã  User:(audit.UserInfo){Username:(string)è•‰é’ªÅ¸vRÃ‚æ¤¥å¬¶Æ˜ç£¡{ç°¸È²Å¬Ç£BnÈ¬è¸½ UID:(string)å’¿é‹°éŸ‚ÅÅŠÈ½\\ä¼¶é‰–nÉ·OÈšéäºµÃ„ Groups:([]string)<nil> Extra:(map[string]audit.ExtraValue)map[Ç„8é±0KÉ‡hÊ”É É”È”Ã´Å²É–æ©ŒY:[è®‰æ˜¸8OÆ¿Â¯ç¬’^ç©wé›·o,uÅŠÄ´d]]} ImpersonatedUser:(*audit.UserInfo)<nil> SourceIPs:([]string)<nil> ObjectRef:(*audit.ObjectReference){Resource:(string)/Ã›ç«bÃˆçœ¾ç…›èŽ¹2Çªé¸·Ç·f Namespace:(string)èµ‹ÈÈ‚vÃ‹>^ÇX)rÉµÊ­ Name:(string)Â¤ÇŒÄ•æ“¢å²˜ UID:(types.UID)Çå¯æ±±Ç¹ÊŽ APIGroup:(string)ÃˆÇ·Ã‘Ê¢è–‹t:éƒˆé¸ç¤Ä+hÆº APIVersion:(string)bÉªsÄå·«å©ç•²æ±žæ…‰Ê„ç‘†Å¬&/ ResourceVersion:(string)æŸ¼ÃŸ Subresource:(string)è†³æŽ„4Ã½eQPæ±¸B15Æ 3ugÈ©é›‘Ä£} ResponseStatus:(*v1.Status)<nil> RequestObject:(*runtime.Unknown){TypeMeta:(runtime.TypeMeta){APIVersion:(string) Kind:(string)} Raw:([]uint8)[123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 34 44 34 107 105 110 100 34 58 34 80 111 100 34 44 34 115 111 109 101 75 101 121 34 58 34 115 111 109 101 86 97 108 117 101 34 125] ContentEncoding:(string) ContentType:(string)application/json} ResponseObject:(*runtime.Unknown){TypeMeta:(runtime.TypeMeta){APIVersion:(string) Kind:(string)} Raw:([]uint8)[123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 34 44 34 107 105 110 100 34 58 34 80 111 100 34 44 34 115 111 109 101 75 101 121 34 58 34 115 111 109 101 86 97 108 117 101 34 125] ContentEncoding:(string) ContentType:(string)application/json}}"
		
		Encoded:
		
		{"kind":"Event","apiVersion":"audit.k8s.io/v1alpha1","metadata":{"name":"RÉ‰È©È.o_V","generateName":"!gÇ‰Ç”ÄæªŽæ¼“ç¹Žè‚²)ç†¦Ã˜æ¨æœ³Ã‘7_J","selfLink":"Ã¼èˆŠæ²ŠÉ“","uid":"åšº","resourceVersion":"13176268021741830527","creationTimestamp":null},"level":"é¤–ÉƒvÃƒÈ±{ç¼®Ã…Xåž¯Ã‚Å“]Ç”dÈžé´»","timestamp":"2485-11-15T18:29:59Z","auditID":"","stage":"è™žæ‘³å²˜è®¡","requestURI":"æµ³Hç°¿fÈ’sÆ‹Âª\u003cé»µ'QÊƒå„µ#/cäº²G","verb":"k_Ê–lÈƒå jå½“EÂ¡Ã ","user":{"username":"è•‰é’ªÅ¸vRÃ‚æ¤¥å¬¶Æ˜ç£¡{ç°¸È²Å¬Ç£BnÈ¬è¸½","uid":"å’¿é‹°éŸ‚ÅÅŠÈ½\\ä¼¶é‰–nÉ·OÈšéäºµÃ„","extra":{"Ç„8é±0KÉ‡hÊ”É É”È”Ã´Å²É–æ©ŒY":["è®‰æ˜¸8OÆ¿Â¯ç¬’^ç©wé›·o,uÅŠÄ´d"]}},"objectRef":{"resource":"/Ã›ç«bÃˆçœ¾ç…›èŽ¹2Çªé¸·Ç·f","namespace":"èµ‹ÈÈ‚vÃ‹\u003e^ÇX)rÉµÊ­","name":"Â¤ÇŒÄ•æ“¢å²˜","uid":"Çå¯æ±±Ç¹ÊŽ","apiVersion":"ÃˆÇ·Ã‘Ê¢è–‹t:éƒˆé¸ç¤Ä+hÆº/bÉªsÄå·«å©ç•²æ±žæ…‰Ê„ç‘†Å¬\u0026/","resourceVersion":"æŸ¼ÃŸ","subresource":"è†³æŽ„4Ã½eQPæ±¸B15Æ 3ugÈ©é›‘Ä£"},"requestObject":{"apiVersion":"","kind":"Pod","someKey":"someValue"},"responseObject":{"apiVersion":"","kind":"Pod","someKey":"someValue"}}
		
		
		Final:
		
		"(*audit.Event){TypeMeta:(v1.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(v1.ObjectMeta){Name:(string)RÉ‰È©È.o_V GenerateName:(string)!gÇ‰Ç”ÄæªŽæ¼“ç¹Žè‚²)ç†¦Ã˜æ¨æœ³Ã‘7_J Namespace:(string) SelfLink:(string)Ã¼èˆŠæ²ŠÉ“ UID:(types.UID)åšº ResourceVersion:(string)13176268021741830527 Generation:(int64)0 CreationTimestamp:(v1.Time){Time:(time.Time){sec:(int64)0 nsec:(int32)0 loc:(*time.Location)<nil>}} DeletionTimestamp:(*v1.Time)<nil> DeletionGracePeriodSeconds:(*int64)<nil> Labels:(map[string]string)<nil> Annotations:(map[string]string)<nil> OwnerReferences:([]v1.OwnerReference)<nil> Initializers:(*v1.Initializers)<nil> Finalizers:([]string)<nil> ClusterName:(string)} Level:(audit.Level)é¤–ÉƒvÃƒÈ±{ç¼®Ã…Xåž¯Ã‚Å“]Ç”dÈžé´» Timestamp:(v1.Time){Time:(time.Time){sec:(int64)78415064999 nsec:(int32)0 loc:(*time.Location){name:(string)Local zone:([]time.zone)[{name:(string)UTC offset:(int)0 isDST:(bool)false}] tx:([]time.zoneTrans)[{when:(int64)-9223372036854775808 index:(uint8)0 isstd:(bool)false isutc:(bool)false}] cacheStart:(int64)-9223372036854775808 cacheEnd:(int64)9223372036854775807 cacheZone:(*time.zone){name:(string)UTC offset:(int)0 isDST:(bool)false}}}} AuditID:(types.UID) Stage:(audit.Stage)è™žæ‘³å²˜è®¡ RequestURI:(string)æµ³Hç°¿fÈ’sÆ‹Âª<é»µ'QÊƒå„µ#/cäº²G Verb:(string)k_Ê–lÈƒå jå½“EÂ¡Ã  User:(audit.UserInfo){Username:(string)è•‰é’ªÅ¸vRÃ‚æ¤¥å¬¶Æ˜ç£¡{ç°¸È²Å¬Ç£BnÈ¬è¸½ UID:(string)å’¿é‹°éŸ‚ÅÅŠÈ½\\ä¼¶é‰–nÉ·OÈšéäºµÃ„ Groups:([]string)<nil> Extra:(map[string]audit.ExtraValue)map[Ç„8é±0KÉ‡hÊ”É É”È”Ã´Å²É–æ©ŒY:[è®‰æ˜¸8OÆ¿Â¯ç¬’^ç©wé›·o,uÅŠÄ´d]]} ImpersonatedUser:(*audit.UserInfo)<nil> SourceIPs:([]string)<nil> ObjectRef:(*audit.ObjectReference){Resource:(string)/Ã›ç«bÃˆçœ¾ç…›èŽ¹2Çªé¸·Ç·f Namespace:(string)èµ‹ÈÈ‚vÃ‹>^ÇX)rÉµÊ­ Name:(string)Â¤ÇŒÄ•æ“¢å²˜ UID:(types.UID)Çå¯æ±±Ç¹ÊŽ APIGroup:(string)ÃˆÇ·Ã‘Ê¢è–‹t:éƒˆé¸ç¤Ä+hÆº/bÉªsÄå·«å©ç•²æ±žæ…‰Ê„ç‘†Å¬& APIVersion:(string) ResourceVersion:(string)æŸ¼ÃŸ Subresource:(string)è†³æŽ„4Ã½eQPæ±¸B15Æ 3ugÈ©é›‘Ä£} ResponseStatus:(*v1.Status)<nil> RequestObject:(*runtime.Unknown){TypeMeta:(runtime.TypeMeta){APIVersion:(string) Kind:(string)} Raw:([]uint8)[123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 34 44 34 107 105 110 100 34 58 34 80 111 100 34 44 34 115 111 109 101 75 101 121 34 58 34 115 111 109 101 86 97 108 117 101 34 125] ContentEncoding:(string) ContentType:(string)application/json} ResponseObject:(*runtime.Unknown){TypeMeta:(runtime.TypeMeta){APIVersion:(string) Kind:(string)} Raw:([]uint8)[123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 34 44 34 107 105 110 100 34 58 34 80 111 100 34 44 34 115 111 109 101 75 101 121 34 58 34 115 111 109 101 86 97 108 117 101 34 125] ContentEncoding:(string) ContentType:(string)application/json}}"
	roundtrip.go:216: 	round tripping to audit.k8s.io/v1beta1, Kind=Event v1beta1.Event
	roundtrip.go:137: finished group "audit.k8s.io"
FAIL
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/install	0.918s
```

### PR DESCRIPTION
**Pull request by sttts**
Fixes #51908.

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the quick turnaround

**Comment by liggitt** [comment]
gce flake was https://github.com/kubernetes/kubernetes/issues/51910

**Review by soltysh — APPROVED** [review]

**Comment by CaoShuFeng** [comment]
Thanks for fixing this bug import by me.

**Pull request merged**
