### PR TITLE
e2e: accept context from Ginkgo

### PR DESCRIPTION
**Pull request by pohly**
Every ginkgo callback should return immediately when a timeout occurs or the test run manually gets aborted with CTRL-C. To do that, they must take a ctx parameter and pass it through to all code which might block.

This is a first automated step towards that: the additional parameter got added with

    sed -i 's/\(framework.ConformanceIt\|ginkgo.It\)\(.*\)func() {$/\1\2func(ctx context.Context) {/' \
        $(git grep -l -e framework.ConformanceIt -e ginkgo.It )
    $GOPATH/bin/goimports -w $(git status | grep modified: | sed -e 's/.* //')

log_test.go was left unchanged.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is in preparation for https://github.com/kubernetes/kubernetes/pull/112923.

Merging it now will make that other PR smaller.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve

Thanks for your patience

**Comment by dims** [comment]
/approve

looks like mostly mechanical changes.

**Pull request merged**
