### PR TITLE
Update github.com/aws/aws-sdk-go

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
A new AWS region `eu-central-2` was launched this week -ref https://aws.amazon.com/blogs/aws/a-new-aws-region-opens-in-switzerland/.
Currently CCM cannot run against the new region:
```
I1113 17:18:49.979775       1 aws.go:1279] Building AWS cloudprovider
could not init cloud provider "aws": not a valid AWS zone (unknown region): eu-central-2a
```

This PR should fix this issue by updated to github.com/aws/aws-sdk-go@v1.44.136 that supports the eu-central-2 region.

#### Which issue(s) this PR fixes:

See above.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/milestone v1.27

let's land this after 1.26 goes GA. if necessary we can back port then.

**Comment by ialidzhikov** [comment]
@dims , I had to rebase.

**Pull request merged**
