### PR TITLE
Add comment on beta status for APIPriorityAndFairness feature gate

### PR DESCRIPTION
**Pull request by danielhelfand**
APIPriorityAndFairness reached beta status and is enabled by default in v1.20

https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Added comment above `APIPriorityAndFairness featuregate.Feature = "APIPriorityAndFairness"` like other constants under kube_features.go.

#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

Good catch!
Thanks.

**Comment by danielhelfand** [comment]
Thanks @MikeSpreitzer.

@aojea Anyone you can recommend to assign this to for approval?

**Comment by aojea** [comment]
this is a comment so I don't think we require anybody in particular
@liggitt or @dims use to handle all these things

**Pull request merged**
