### PR TITLE
Switch to index rather than copy indexing.

### PR DESCRIPTION
**Pull request by brendandburns**
This was 17% of all allocations on a recent profile.

@davidopp @wojtek-t @gmarek

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by brendandburns** [comment]
@k8s-bot test this please
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
Really?
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
