### PR TITLE
move the discovery and dynamic clients

### PR DESCRIPTION
**Pull request by deads2k**
Moved the dynamic client, discovery client, testing/core, and testing/cache to `client-go`.  Dependencies on api groups we don't have generated clients for have dropped out, so federation, kubeadm, and imagepolicy.

@caesarxuchao @sttts 

approved based on https://github.com/kubernetes/kubernetes/issues/40363

### CODE REVIEW

**Comment by deads2k** [comment]
Also now moving `client/testing`

**Comment by deads2k** [comment]
@sttts how about an ok in principle while I hunt down the controller problem.

**Comment by spxtr** [comment]
@k8s-bot test this

**Comment by deads2k** [comment]
and another rebase conflict.

**Comment by sttts** [comment]
+1,535 −21,250 – impressive. /lgtm

**Comment by deads2k** [comment]
> +1,535 −21,250 – impressive. /lgtm

yeah, it actually got me to look.  thockin is a code slayer: `1,159,704 ++ / 1,233,091 --`

**Comment by deads2k** [comment]
@k8s-bot bazel test this: issue #40526

**Comment by spxtr** [comment]
@k8s-bot bazel test this
#40526

**Comment by deads2k** [comment]
@k8s-bot verify test this

**Comment by deads2k** [comment]
@k8s-bot gci gke e2e test this

**Comment by caesarxuchao** [comment]
The numbers are impressive :) By "move", do you mean make client-go authoritative for these packages? I guess staging/copy.sh doesn't work anymore after these moves?

**Comment by deads2k** [comment]
> The numbers are impressive :) By "move", do you mean make client-go authoritative for these packages? I guess staging/copy.sh doesn't work anymore after these moves?

I'm keeping `staging/copy.sh` up to date with every move, running at the beginning and at the end.  It's significantly simplified the file and we're still moving forward.

**Pull request merged**
