### PR TITLE
Automated cherry pick of #115966: make MixedProtocolNotSupported public

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #115966 on release-1.25.

#115966:  don't process unsupported loadbalancers with mixed protocols #115966

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

/kind bug

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
@apelisse `PatchType is not supported` error on the failing tests can be related to server side apply not available in 1.25 and 1.24?

**Comment by apelisse** [comment]
Server-side apply has been GA since 1.22. That being said, I know the OpenAPI wasn't necessarily properly wired in all tests before.

**Comment by apelisse** [comment]
I wouldn't expect this failure though, I would rather expect a panic.

**Comment by liggitt** [comment]
This is a unit test, right? Is this using the fake client? Did that get changed in newer releases to "support" apply patches?

**Comment by apelisse** [comment]
Not that I know of?

**Comment by liggitt** [comment]
it did, in https://github.com/kubernetes/kubernetes/commit/fea883687feafc597591e15773f8c6f491b35d08#diff-5e284010fb4c5f529014f3aad4e3d05969574187d878fb9cd3802b3147cda9c3

it just treats apply patches as client side SMP patches... that's not good

**Comment by apelisse** [comment]
I'm in the process of adding testability to unit-tests, and it's far from easy, definitely not a one line change.

**Comment by liggitt** [comment]
> I'm in the process of adding testability to unit-tests, and it's far from easy, definitely not a one line change.

agreed... I'd be inclined to revert that change at HEAD once master opens for 1.28... that's way more misleading than helpful, IMO

**Comment by liggitt** [comment]
commented at https://github.com/kubernetes/kubernetes/pull/113304#discussion_r1144111578#113304 

@apelisse, you mind filing an issue so we don't lose track of dropping this bit in client-go until we actually have support for apply testing?

**Comment by liggitt** [comment]
@aojea, for your unit test, you can add a commit with a reactor to the fake client that handles the apply patch the way we expect the server to (you can narrowly assert you get the apply patch you expect, then add the condition in your reactor, return the updated object, etc)

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/116851 for testing client issue with SSA support

**Comment by liggitt** [comment]
I'll defer to thockin's review, since he looked at the master PR

**Comment by aojea** [comment]
ping @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
/assign @andrewsykim 
for cloudprovider

**Comment by aojea** [comment]
ping @kubernetes/release-managers 

it seems it slipped through 🤷

**Comment by thockin** [comment]
ping @kubernetes/release-managers

**Pull request merged**
