### PR TITLE
remove the extra word

### PR DESCRIPTION
**Pull request by qingsenLi**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qingsenLi** [comment]
@dims @timothysc @soltysh 
PTAL

**Review by timothysc — APPROVED** [review]

**Comment by timothysc** [comment]
Please combine your spell-check PRs into a single PR.

**Comment by qingsenLi** [comment]
The change point has been deleted on the master branch, close the PR.

**Pull request closed without merging**
