### PR TITLE
Drop portworx in tree plugin

### PR DESCRIPTION
**Pull request by dims**
Final PR for removing portworx in-tree plugin. Please see the previous ones that touched the feature gate etc:
- https://github.com/kubernetes/kubernetes/pull/110411
- https://github.com/kubernetes/kubernetes/pull/125016

#### What type of PR is this?

/kind cleanup
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The in-tree Portworx plugin "kubernetes.io/portworx-volume" is now removed in this release. Users should install the Portworx CSI Driver (https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/csi/enable/) and start using that directly for any new volumes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @gohilankit 

/assign @xing-yang @msau42

**Comment by xing-yang** [comment]
@dims We need to move it to GA first before removing portworx in-tree plugin.  We can target to move it to GA in 1.33.

**Comment by xing-yang** [comment]
Screenshot 2024-12-10 at 9 35 38 AM

**Comment by dims** [comment]
thanks @xing-yang - slack thread - https://kubernetes.slack.com/archives/C09QZFCE5/p1733841374019959?thread_ts=1727122117.209089&cid=C09QZFCE5

**Pull request closed without merging**
