### PR TITLE
Implement Kubelet support for HostNetwork by pod source

### PR DESCRIPTION
**Pull request by vmarmol**
This implements support on the Kubelet only. The apiserver changes are left as a TODO.

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @thockin

**Comment by ArtfulCoder** [comment]
LGTM

**Comment by vmarmol** [comment]
Thanks @dchen1107!

**Comment by smarterclayton** [comment]
Maybe I missed it, when did pod.Spec.HostNetwork get added?  This would be something that would need to be controlled by the security context, so trying to find that.

**Comment by vmarmol** [comment]
@smarterclayton this was added in #5814. I am not familiar with security context, happy to make sure it works well with it.

**Comment by smarterclayton** [comment]
Not a big deal now - just that security context will probably have some relevance to namespaces and capabilities so I wanted to make sure I understood the context for the changes.

----- Original Message -----

**Comment by vmarmol** [comment]
Sounds good, we followed the same pattern as `--priviledged` and integrated into `pkg/capabilities` both should use the same mechanism for allow/disallow. Today, the Kubelet only accepts NetHost=true from the sources specified in a flag. Valid sources: apiserver, http, and file. By default the only allowed source is file.

**Pull request merged**
