### PR TITLE
Use a strong type for UID fields

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
It compiles, so I assert it works.  e2e run is in progress

**Comment by lavalamp** [comment]
LGTM

**Comment by smarterclayton** [comment]
As a side note, `util` has now become the stereotypical util package - filled with tens of unrelated things that depend on most of the packages in the standard library.  We should try to more aggressively prod people to subset the util package set (`pkg/util/uid`)

**Comment by thockin** [comment]
I was contemplating pkg/types for simple type aliases and flag-wrappers and
the sort.

**Comment by lavalamp** [comment]
pkg/types sounds like a better home for this.

**Comment by smarterclayton** [comment]
pkg/flagtypes for flag wrappers? :)  Time might be good to split, set is data types, hash+diff is object comparison.  I guess I don't care *that* much :)



----- Original Message -----

**Comment by lavalamp** [comment]
I think StringSet might be a good candidate for "go generate"-- then we could have pkg/util/set with types String, Int, etc... So you'd use set.String instead of util.StringSet. Could be nice, not worth much effort at this point.

**Comment by thockin** [comment]
That (StringSet) would be a great change.

I'll send a quick change to move UID to pkg/types.  we can argue about flag
wrappers as a second order.

**Pull request merged**
