### PR TITLE
cinder volume test

### PR DESCRIPTION
**Pull request by NickrenREN**
add function to test GetDeviceMountPath func

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37078)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@dims   GKE smoke e2e fail： issue has been raised (Cannot bring up GCI GKE e2e cluster: "cluster_api_version not found" #35913).

**Comment by NickrenREN** [comment]
@dims checks passed

**Comment by NickrenREN** [comment]
@k8s-merge-robot   noone was assigned

**Pull request closed without merging**
