### PR TITLE
Add flag to node e2e test specifying location of ssh privkey

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: in CI, the ssh private key is not always located at `$HOME/.ssh`, so it's helpful to be able to override it.

@krzyzacy here's my resurrected change. I'm not sure why I neglected to follow-through on it originally.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
I knew I should've built before pushing...
`bazel build //test/e2e_node/...` passes now.

**Comment by ixdy** [comment]
I think this actually works now.

**Comment by ixdy** [comment]
@k8s-bot cvm gke e2e test this

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot unit test this

**Comment by Random-Liu** [comment]
@ixdy Sorry...Missed this. Will review now.

**Comment by ixdy** [comment]
needing separate approval for `hack/verify-flags/exceptions.txt` is kinda dumb.

@apelisse @grodrigues3 is there some way to ignore certain files or directories?

**Comment by ixdy** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by ixdy** [comment]
@k8s-bot verify test this

**Pull request merged**
