### PR TITLE
Add chendave to sig-scheduling REVIEWERS

### PR DESCRIPTION
**Pull request by chendave**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind documentation

**What this PR does / why we need it**:
Add @chendave to sig-scheduling reviewers, based on the guide on the community-membership, and the expectation that I could be more deeply involved in sig-scheduling,  my current contribution to K8S as well as sig-scheduling, 

- Member of K8S at least 3 months (since Oct. 9, 2019)
- Primary reviewer for at least 5 PRs to the codebase 
    - [review list](https://github.com/kubernetes/kubernetes/pulls?q=label%3Asig%2Fscheduling+reviewed-by%3Achendave)
- Reviewed or merged at least 20 substantial PRs to the codebase
   - [review list](https://github.com/kubernetes/kubernetes/pulls?q=label%3Asig%2Fscheduling+reviewed-by%3Achendave)
   - [pr list with scheduling tag](https://github.com/kubernetes/kubernetes/pulls?q=label%3Asig%2Fscheduling+author%3Achendave)
   - [pr list in K8S repo](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Achendave+)
   - [pr list in perf test](https://github.com/kubernetes/perf-tests/pulls?q=is%3Apr+author%3Achendave+)
   - [issue list opened by chendave](https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Achendave+)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/lgtm

Thanks for the contributions to sig-scheduling!

**Comment by alculquicondor** [comment]
/lgtm

Thanks a lot for your contributions!

**Review by damemi — COMMENTED** [review]
+1!

**Comment by ahg-g** [comment]
/lgtm  based Aldo and Wei's recommendation

Looking forward for more substantial contributions.

**Comment by chendave** [comment]
thanks guys! Jordan could you pls take a look?
/assign @liggitt

**Pull request merged**
