### PR TITLE
Update vendor spf13/cobra to fix completion error in bash 3

### LINKED ISSUE #121: Autocomplete issues with --from-file and --from-literal
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube
- **OS** (e.g. from /etc/os-release): macOS Sierra, 10.12.6
- **Kernel** (e.g. `uname -a`): `Darwin WDFM31654402A 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`
- **Install tools**: n/a
- **Others**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)`

**What happened**:
I was following along the Kubernetes Up & Running book and found that autocomplete for some of the configmaps and secrets examples doesn't work as expected.

**What you expected to happen**:
I was expecting the autocomplete to work for the `--from-file` and `--from-literal` parameters, however, I got some bash errors.

**How to reproduce it** (as minimally and precisely as possible):
* Type:
```
kubectl create configmap my-config --from-file=<tab>
```
Result:
```
kubectl create configmap my-config --from-file=--from-file= (instead of a list of files in the local directory)
```
* Type:
```
kubectl create configmap my-config --from-file=my-config.txt --from-li<tab>
```
Result (my-config.txt should of course exist in the local directory):
```
kubectl create configmap my-config --from-file=my-config.txt --from-li-bash: --from-file=: syntax error: operand expected (error token is "=")
```

Similar behavior for `kubectl create secret`.

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**: This PR updates vendor spf13/cobra to fix completion error in bash 3.

/ref spf13/cobra#628
/cc @eparis 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubectl#121, kubernetes/kubernetes#29322, kubernetes/kubernetes#32676.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by eparis** [comment]
Aren't there more fixes for bash3 completions in a later commit?  fd32f09af19efc9b1279c54e0d8ed23f66232a15

**Comment by superbrothers** [comment]
@eparis I updated this PR.

**Comment by eparis** [comment]
/assign @cblecker 
for an update in Godeps

**Comment by cblecker** [comment]
@superbrothers Would you mind squashing the commits? Thanks!

**Comment by superbrothers** [comment]
@cblecker I squashed the commits.

**Pull request merged**
