### PR TITLE
Update to latest docker client

### PR DESCRIPTION
**Pull request by pweil-**
This would be required for implementation of https://github.com/GoogleCloudPlatform/kubernetes/pull/6287

In particular this gives access to the `SecurityOpt` configuration https://github.com/GoogleCloudPlatform/kubernetes/blob/fb633704515e51fdd318adc79e64db56e3b07a98/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go#L419

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM. Can you run e2e test before merge?

**Comment by pweil-** [comment]
Will do.  Thanks!

**Comment by pweil-** [comment]
@dchen1107 - I have a clean gce run of most of the e2e tests.  For some reason the MasterCerts spec hangs for me.  I can run the same gcloud ls command in another window and see it return with all the files the test should be looking for.

```
[pweil@localhost kubernetes]$ go run hack/e2e.go -v -test -test_args="-t Docker Containers -t Pods -t PD -t Networking -t Cadvisor -t emptyDir -t Events -t ReplicationController -t Services"

<snip>

Ran 24 of 39 Specs in 548.645 seconds
SUCCESS! -- 24 Passed | 0 Failed | 0 Pending | 15 Skipped I0413 17:38:49.167678   21765 driver.go:114] All tests pass
```

**Comment by dchen1107** [comment]
Thanks!

**Pull request merged**
