### PR TITLE
[local-up-cluster] Use the kubectl we built and wait for node to be ready

### PR DESCRIPTION
**Pull request by dims**
#### What type of PR is this?
/kind cleanup

We should explicitly use the `kubectl` we built. Otherwise `kubectl.sh` is likely to pick something else.

Also noticed that the e2e tests sometimes started even before the node is ready, so added an additional wait for the condition.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig testing
/sig architecture

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by pohly — APPROVED** [review]
Worked for me (and that's what matters, right?).

/approve

**Comment by aojea** [comment]
> Worked for me (and that's what matters, right?).

lol,

**Comment by aojea** [comment]
I think the CI has a different opinion @pohly 😄 

> pull-kubernetes-local-e2e — Job failed.

**Comment by dims** [comment]
LOL. i will be filing follow ups to stabilize pull-kubernetes-local-e2e  again

**Comment by pohly** [comment]
The job fails because some tests don't pass on a local-up cluster, but the change itself is okay (cluster comes up fine, also for me locally).

**Comment by aojea** [comment]
didn't check the failures sorry, I just thought was funny

**Pull request merged**
