### PR TITLE
Add options for build container rsync optimization

### PR DESCRIPTION
**Pull request by ivan4th**
KUBE_RSYNC_COMPRESS env var sets rsync compression level.
KUBE_RSYNC_GENERATED_TO_BUILD_CONTAINER env var disables rsyncing
generated files to build containers.

Why KUBE_RSYNC_COMPRESS is needed -- from rsync manual on `--compress` option (implied by non-zero `--compress-level`):
> Note that this option typically achieves better compression ratios than can be achieved by using a compressing remote shell or a compressing transport because it takes advantage of the implicit information in the matching data blocks that are not explicitly sent over  the connection.

Use case for `KUBE_RSYNC_GENERATED_TO_BUILD_CONTAINER`: when you sometimes build stuff locally (e.g. `make WHAT=cmd/kubectl`) and sometimes do it on remote docker (`build-tools/run.sh make WHAT=cmd/hyperkube`), local builds touch generated files which causes them to be rsynced to the build data container, which may slow down the builds. Still, I'm not sure whether local->remote rsync of generated files is useful (e.g. someone may want to edit generated files for debugging purposes?), so I made not rsyncing these files an option instead of forcing such behavior.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36361)

### CODE REVIEW

**Comment by ivan4th** [comment]
@k8s-bot gci gce e2e test this

**Comment by ivan4th** [comment]
@k8s-bot gci gce e2e test this

**Comment by zmerlynn** [comment]
Sorry for the slow response. I'm inclined to push back on this because it's a set of knobs for the build system that are unlikely to be tested in any continuous integration setting. Unless they have a lot of value being changed by default (which e.g. compression may), I don't think we need more knobs here.

cc @jbeda

**Comment by ivan4th** [comment]
Does it make sense to copy locally generated files to the build container then? Maybe if knobs aren't acceptable, we may just always skip copying these files? As of compression, I suspect it doesn't add that much overhead and we can enable it by default, wdyt? It helps if you use remote docker that's indeed quite remote. Although if that's problematic I can remove this part & just use ssh compression in such cases, as rsync port is forwarded anyway.

**Comment by jbeda** [comment]
I'm cool with the "compress" option. It is semantically identical and can make sense when you have a remote docker daemon that you are pushing to.  Compression should be off, by default as it will slow down the local docker case.  It is worth measuring though.  Note that right now there is no ssh compression by default as we are doing rsync over the rsync protocol, not via ssh.  You'd get ssh compression if you are using a remote daemon with an ssh tunnel, but rsync doesn't know about that.

As for copying the generated files back to the build container -- we should probably never do that.  I'm okay with changing this so that we only copy generated files FROM the build container and never TO the build container.

**Comment by ivan4th** [comment]
@jbeda updated the PR, now it always ignores generated files when rsyncing to the container. As of compress option, yes, it's off by default.

**Comment by ivan4th** [comment]
Hmm looks like not copying generated files to the container is not going to work, let me see

**Comment by ivan4th** [comment]
There was a problem with `staging/` - generated files from there need to be rsynced to the container anyway because `make` doesn't re-generate them. Fixed the filter, should work now

**Comment by ivan4th** [comment]
Flake similar to (3) from https://github.com/kubernetes/kubernetes/issues/35935#issuecomment-257462440

@k8s-bot cri node e2e test this

**Comment by ivan4th** [comment]
@k8s-bot bazel test this

**Comment by ivan4th** [comment]
ping...

**Comment by jbeda** [comment]
/lgtm

Sorry for dropping this.  Was waiting for the test issues to be figured out.

**Pull request merged**
