### PR TITLE
【Placeholder】make sure everything done and Promote sysctls to GA version

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup
/kind feature

#### What this PR does / why we need it:
/sig node
graduates sysctls to GA
refer to the KEP
A summary of this feature is in https://github.com/kubernetes/enhancements/issues/34#issuecomment-782553906

#### Which issue(s) this PR fixes:
implement https://github.com/kubernetes/enhancements/issues/34

#### Special notes for your reviewer:
GA checklist:
- [x] #72974 kubelet: add allowed sysctl to KubeletConfiguration
- [x] e2e tests are added https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/sysctl.go
- [x] PodSecurityPolicy related(skip due to its deprecation) .
- [x] lock to true in this pr.
More details can be found in KEP loop. A simple summary before doing it is on [google doc](https://docs.google.com/document/d/1FbThdQQVNPISNjK4IEqfliuRCA6pLbUiayb3OASOXHA/edit?usp=sharing)

#### Does this PR introduce a user-facing change?
```release-note
Feature gate sysctls is now GA and locked to true
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]:  https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/34-sysctl-fields
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/kind cleanup
/kind feature
/sig node
/hold cancel
/priority important-soon
/triage accepted
/retitle Promote sysctls to GA version 

@wgahnagl I complete the PR base on yours #99158 and add you as co-author in the commit.

**Comment by ehashman** [comment]
/close

@pacoxu I'm going to continue working with @wgahnagl to get the original PR merged, it is her first contribution to k8s.

**Comment by pacoxu** [comment]
@ehashman ok to me.
ping me if anything that I can help.

**Comment by ehashman** [comment]
We're pairing on cherry-picking your commit as we speak!

**Pull request closed without merging**
