### PR TITLE
fix request typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix request typo

### CODE REVIEW

**Comment by timchenxiaoyu** [comment]
NONE

**Comment by timchenxiaoyu** [comment]
cc @saad-ali

**Comment by techtonik** [comment]
This is safe to be merged without testing.

**Comment by techtonik** [comment]
@timchenxiaoyu why not merge all typos in one PR together? https://github.com/kubernetes/kubernetes/pull/42462

**Comment by timchenxiaoyu** [comment]
I hava close #42462

**Comment by timchenxiaoyu** [comment]
cc @saad-ali please check this pr

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Pull request merged**
