### PR TITLE
Removed align_stats flag from Heapster config

### PR DESCRIPTION
**Pull request by piosz**
The flag caused inaccuracy in compute cpu/usage_rate metric

### CODE REVIEW

**Comment by vishh** [comment]
cc @afein

**Comment by afein** [comment]
LGTM
Is this flag used at all anymore? If not, we could deprecate it

**Comment by vishh** [comment]
Should we revert https://github.com/kubernetes/heapster/pull/394 @piosz ?

**Comment by piosz** [comment]
Why not. It should be reverted together with https://github.com/kubernetes/heapster/pull/423. I can do it tomorrow.

**Comment by vishh** [comment]
LGTM in that case.

**Pull request merged**
