### PR TITLE
Add dryrun to kubectl apply

### LINKED ISSUE #6284: kubectl diff command
It'd be great if user could diff current configuration with the one in a file. I imagine output to be a regular smart diff of JSON files (ignoring version, status etc).

### PR DESCRIPTION
**Pull request by fraenkel**
fixes #6284

It's a start. Not exactly sure how we want the output to look.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31892)

### CODE REVIEW

**Comment by dims** [comment]
ok to test

**Comment by fraenkel** [comment]
@dims This isn't exactly how I envision this, but it's a starting point for further discussion.

**Comment by dims** [comment]
@fraenkel ack :)

**Comment by janetkuo** [comment]
Thanks. I played around with it. Here are a few suggestions:

When the file to be applied is not found, `apply` will create it instead. `--dry-run` should show what'll be created, not the "not found" error. 

```console
$ kubectl apply -f hack/testdata/deployment-revision2.yaml --dry-run 
Error from server: error when retrieving current configuration of:
&{0xc8202ca780 0xc820282230 default nginx hack/testdata/deployment-revision2.yaml &Deployment{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:nginx,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{name: nginx-undo,},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:DeploymentSpec{Replicas:*3,Selector:&LabelSelector{MatchLabels:map[string]string{name: nginx-undo,},MatchExpressions:[],},Template:k8s_io_kubernetes_pkg_api_v1.PodTemplateSpec{ObjectMeta:ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{name: nginx-undo,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:PodSpec{Volumes:[],Containers:[{nginx gcr.io/google-containers/nginx:1.7.9 [] []  [{ 0 80  }] [] {map[] map[]} [] nil nil nil   nil false false false}],RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[],Hostname:,Subdomain:,},},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,RollbackTo:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,},} &TypeMeta{Kind:,APIVersion:,}  false}
from server for: "hack/testdata/deployment-revision2.yaml": deployments.extensions "nginx" not found
```

Directly printing the diff patch is a bit hard to read:
```console
$ kubectl apply -f hack/testdata/deployment-revision1.yaml --dry-run 
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"Deployment\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"nginx\",\"creationTimestamp\":null,\"labels\":{\"name\":\"nginx-undo\"}},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"name\":\"nginx-undo\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"name\":\"nginx-undo\"}},\"spec\":{\"containers\":[{\"name\":\"nginx\",\"image\":\"gcr.io/google-containers/nginx:test-cmd\",\"ports\":[{\"containerPort\":80}],\"resources\":{}}]}},\"strategy\":{}},\"status\":{}}"},"creationTimestamp":null},"spec":{"template":{"spec":{"containers":[{"image":"gcr.io/google-containers/nginx:test-cmd","name":"nginx"}]}}}}
```

**Comment by fraenkel** [comment]
@janetkuo Will fix the not found issue.
I did mention that I wasn't sure about the output. Normally I would have piped it to jq to make it look pretty. I am open to suggestions and we can strip some of what is there but ultimately it comes down to how we expect people to use --dry-run.

**Comment by fraenkel** [comment]
@janetkuo Looking closer it seems the above happens whether you are doing --dry-run or not. The question is how errors should bubble up when doing --dry-run?  Right now I am just letting the default error handling be used and only in the case of a successful patch do you see the "lovely" json.

Errors go to stderr and the patch goes to stdout.

**Comment by janetkuo** [comment]
On second thought, `--dry-run` in other commands means "print the final result", but this PR wants it to only "print the diff". Would this be surprising to the users?

**Comment by fraenkel** [comment]
--dry-run normally means to perform the actions you would normally take but don't execute them. In the case of apply, that is what it does. It creates a diff and would normally send that.  There is really no way to print the final result unless dry-run became a server side option which is really weird.

**Comment by AdoHe** [comment]
@fraenkel please rebase, I would like to get this in.

**Comment by fraenkel** [comment]
@adohe This should just be closed out.
--dry-run was added with https://github.com/kubernetes/kubernetes/commit/63e0279d93da0f44319ae38c36d697e4fd706042

**Pull request closed without merging**
