### PR TITLE
Fix the service proxy to re-poll on watch closure no matter what.

### PR DESCRIPTION
**Pull request by brendandburns**
Should stop the bleeding on #3216

### CODE REVIEW

**Comment by lavalamp** [comment]
This doesn't seem like an improvement-- the old code should offer the possibility of watching without listing every time, but degrade gracefully to polling if the watches all fail. The new code seems to only remove the former nice case. Am I missing something?

**Comment by brendandburns** [comment]
The only time the watch exits is on some sort of communication failure.  In
that case, I'd argue the sane thing to do is re-poll, especially given what
we have empirically seen.

It is feasible to add a separate thread to do the polling, but that seems
like a more invasive change.

If you'd prefer a separate go routine that does periodic polling, I suppose
we could do that instead.  My main goal is to fix this bug asap.

Brendan

**Comment by brendandburns** [comment]
Also, it doesn't degrade to polling after the first poll, because resource
version is essentially a global that is passed in as a string from outside
the go routine and we only poll when resource version is empty string,
which only happens the first time through.

**Comment by brendandburns** [comment]
s/string/string pointer/

**Comment by lavalamp** [comment]
Ah, OK, I missed the "if" there at the beginning.

OK. Your change is still removing the (hopefully most common) case where the connection times out and it's totally fine to re-watch with the last known resourceVersion.

So let me suggest an alternate fix: when the watch closes, if the error is not EOF, set resourceVersion to "" to force a re-list.

**Comment by brendandburns** [comment]
Ok, comment addressed, ptal.

**Comment by lavalamp** [comment]
LGTM, thanks! There are more places that will need this change, we should think about some way to make it automatic...

**Comment by brendandburns** [comment]
I think that everywhere else that we watch the API server, we also have an
explicit polling loop, but I will audit and double check.

I think we should consider augmenting our Watch API so that we have
something akin to what the service proxy has with a notion of "Operations"
where one operation can be "Set" complete state, vs "Add"/"Delete"
incremental update.

This is very akin to the notion of keyframes and delta encodings in
audio/video streaming, it's a good way to have a robust, yet efficient,
stream.

--brendan

**Comment by smarterclayton** [comment]
Moved upstream discussion to https://github.com/coreos/etcd/issues/2048, I will track that.  We would refresh the connection on the api server and hide *most* scenarios where this exists.  It's still potentially a problem so the loops still benefit from this change

**Pull request merged**
