### PR TITLE
Migrate schedulerapi.HostPriority to framework.NodeScore in priorities

### LINKED ISSUE #83241: [migration] Refactor priorities to use NodeScore/NodeScoreList
**What would you like to be added**:
Refactor priorities to use [NodeScore/NodeScoreList](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/interface.go#L35-L44) instead of [HostPriority/HostPriorityList](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/api/types.go#L337-L345)

**Why is this needed**:
The next step for migration is to implement Priorities as Score plugins. In phase 1 of the migration, we want to do that by calling the priorities functions directly from the score plugins instead of actually moving the code. 

Currently priorities return HostPriority/HostPriorityList, and so to avoid converting that to NodeScore/NodeScoreList when those are called from Score plugins, we should just refactor priorities to use NodeScore/NodeScoreList directly. This should be straightforward since NodeScore and HostPriority have one to one mapping of parameters.

/sig scheduling
/help
/priority important-soon

### PR DESCRIPTION
**Pull request by damemi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This changes usages of `schedulerapi.HostPriority` by scheduler priorities to instead use `framework.NodeScore`, as part of the scheduler framework migration. This helps move priorities to plugins.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/83241

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@damemi You have to update the bazel files.

**Comment by Huang-Wei** [comment]
@damemi A kind reminder (you're doing great right now) that only internal logic which doesn't interact with Extender should be renamed. Thanks for this PR.

**Comment by damemi** [comment]
@Huang-Wei ah, thanks. And I originally wasn't touching anything with the extender, but ran into some build errors without updating it. Should I revert the changes and look at it again?

**Comment by Huang-Wei** [comment]
> but ran into some build errors without updating it

Can you be more specific? I guess somewhere the legacy HostPriority interacts with NodeScore? Let me take a look.

**Comment by damemi** [comment]
@Huang-Wei I run into problems around PriorityFunctions. In [extender_test](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/extender_test.go#L81), it expects a PriorityFunction https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/types.go#L43, but many of the priorities also use this interface. So, from there is where I think the need to update extender usage starts to fall into place... but I will continue looking into it

**Comment by Huang-Wei** [comment]
@damemi I managed to resolve all the errors in #83262. Let's whether CI is green.

**Comment by damemi** [comment]
So we can close this then?

**Pull request closed without merging**
