### PR TITLE
Remove GA featuregate about ProbeTerminationGracePeriod in 1.29

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Remove GA featuregate about ProbeTerminationGracePeriod in 1.29
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Comment by bzsuni** [comment]
Is e2e need it?
Could you please ok-test for this pr? Thanyou very much. @swatisehgal

**Comment by swatisehgal** [comment]
/ok-to-test

> Does e2e need it?
I would expect e2e tests to be written with the assumption that the feature gate is locked to ON by default so don't expect any changes to e2e but we should make sure that all the tests pass. If there are jobs specifically for this feature we should enable them here.

**Comment by bzsuni** [comment]
@swatisehgal Could you please re-review this PR? The CI has passed，thank you very much

**Comment by bzsuni** [comment]
/assign @liggitt 
Could you please review this pr?
And this is the issue for my membership application: https://github.com/kubernetes/org/issues/4509
Would you be willing to sponsor or support my membership request? Thanks.

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by swatisehgal** [comment]
/assign @dims
for `features` approval

**Pull request merged**
