### PR TITLE
Revert container hash value changing

### PR DESCRIPTION
**Pull request by dixudx**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
PR #124220 introduced a breaking change on calculating container hash.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
We should introduce a gentle way to mitigate this hash problem, rather than introducing a completely new algorithm.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dixudx** [comment]
I think at least we should introduce a gentle way to mitigate this hash problem, rather than introducing a completely new  algorithm.

    Am I the only one who thinks this might need a gate, so if something unforeseen goes wrong, a user can disable this?

_Originally posted by @thockin in https://github.com/kubernetes/kubernetes/issues/124220#issuecomment-2080012559_

Agree with @thockin . We should have an opt-in way.

**Comment by thockin** [comment]
Is there more information on the problem?  This was merged 8 months ago, why is it being reverted?

**Comment by liggitt** [comment]
/hold

We're two releases into this change. If there are issues, reverting it will cause those same issues in the opposite direction.

I'd be interested to know if there are issues, but I suspect all issues will be of the variety "people are doing minor kubelet upgrades in place without draining running containers", which is explicitly not supported.

**Comment by liggitt** [comment]
The change in https://github.com/kubernetes/kubernetes/pull/124220 is not breaking, the hash calculation is internal to the kubelet and not guaranteed stable between minors.

**Comment by liggitt** [comment]
/close

let's gather discussion in https://github.com/kubernetes/kubernetes/issues/129385 about whether to modify the current behavior or not. A straight revert definitely would not do what we want.

**Pull request closed without merging**
