### PR TITLE
remove flag '--skip-preflight-checks' deprecated info

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:
the flag `--skip-preflight-checks` has been removed
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
cc @xiangpengzhao 
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/lgtm

It's safe to remove this, which conforms with our deprecation policy.

**Comment by Pingan2017** [comment]
@luxas Could you take a look? Thank u

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
