### PR TITLE
fix the pkg/proxy/ipvs/proxier.go can not check the config from a statically compiled kernel

### LINKED ISSUE #108579: The code proxier.go failed to check  kernel module when the folder  /proc/module is not exsit
### What happened?

When the kernel is statically compiled and statically loaded, and the folder /proc/modules is not exsit. In the kubernetes, use the ipvs. The code proxier.go failed to check  /proc/module  when it is not exsit. In the line 628, the err is not nil. But when  the folder /proc/modules is exsit, it go to the line 639. 
The question is that, how the code runs to 614 line?

### What did you expect to happen?

In the kubernetes, use the ipvs. the kernel is statically compiled and statically loaded. It check out the config in the folder /boot, such as /boot/config-****

### How can we reproduce it (as minimally and precisely as possible)?

If you choose an arm64 machine,  config the kernel config , set CONFIG_MODULES=no, compile statically the kernel. Join the node into k8s's cluster. So you will see this in the pod kube-proxy***.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
There is not a cloud provider. This is for myself.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux armk1101 4.9.216-q4_2107u2

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by robinchia**
…tically compiled kernel

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #108579

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by uablrek** [comment]
X-ref to https://github.com/kubernetes/kubernetes/pull/109937 which is a very similar PR

**Comment by robinchia** [comment]
> X-ref to #109937 which is a very similar PR

@uablrek 
Thanks for the reference. I write some words here:
It is a method to check the ipvs, but it's not a good way. The file /proc/net/ip_vs will not exist when the item is CONFIG_IP_VS=m in the config of the kernel. And the test do not verifies  the submodules ip_vs_rr, ip_vs_wrr, ip_vs_sh from the /proc/net/ip_vs. 
It is meaningless to set CONFIG_IP_VS_RR=y, CONFIG_IP_VS_WRR=y and CONFIG_IP_VS_SH=n, but in fact you can.
So it need do something additional to verify.

**Comment by uablrek** [comment]
> It is a method to check the ipvs, but it's not a good way. 

I agree, that's why I [did not approve it](https://github.com/kubernetes/kubernetes/pull/109937#issuecomment-1123218857).

My proposal is here `https://github.com/kubernetes/kubernetes/issues/108579#issuecomment-1125675626.

**Comment by robinchia** [comment]
> > It is a method to check the ipvs, but it's not a good way.
> 
> I agree, that's why I [did not approve it](https://github.com/kubernetes/kubernetes/pull/109937#issuecomment-1123218857).
> 
> My proposal is here [#108579 (comment)](https://github.com/kubernetes/kubernetes/issues/108579#issuecomment-1125675626).

@uablrek 
Thanks.
I read it, and make my comments.

**Pull request closed without merging**
