### PR TITLE
[rbac] remove unused file

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

remove unused code file plugin/pkg/auth/authorizer/rbac/subject_locator.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k @enj thoughts on this?

**Comment by deads2k** [comment]
> @deads2k @enj thoughts on this?

This provides a reverse lookup of action to subject which is the basis for a future ResourceAccessReview using logic similar to the SubjectRulesReview.  I don't think we should remove it.

**Comment by liggitt** [comment]
agree

**Comment by hzxuzhonghu** [comment]
@deads2k Sorry, I do not know.

**Pull request closed without merging**
