### PR TITLE
Remove bgrant from owners since he has plenty to do.

### PR DESCRIPTION
**Pull request by pwittrock**
@bgrant0607 FYI

[Analytics]()

### CODE REVIEW

**Comment by janetkuo** [comment]
Other owners file I found:
```console
$ grep -r bgrant0607 --include=OWNERS
pkg/OWNERS:  - bgrant0607
pkg/kubectl/OWNERS:  - bgrant0607
pkg/api/OWNERS:  - bgrant0607
pkg/apis/OWNERS:  - bgrant0607
examples/OWNERS:  - bgrant0607
docs/OWNERS:  - bgrant0607
```

**Comment by bgrant0607** [comment]
@pwittrock Please also remove me from pkg/OWNERS. I can be left in the others for now, until we identify more appropriate sets of owners.

**Comment by pwittrock** [comment]
@bgrant0607 Done

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
