### PR TITLE
Fix the equality checks for numeric values in cluster/gce/util.sh.

### LINKED ISSUE #37385: Manual upgrade testing on GCE is leaking resources
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): upgrade test leak

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5 beta

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh

**What happened**: While doing manual upgrade testing, found that I couldn't start a new cluster as the existing firewall rules and external master ip address reservation where preventing kube-up from succeeding after running kube-down

**What you expected to happen**: kube-down to clean up all cluster related resources

**How to reproduce it** (as minimally and precisely as possible):

```
$ git co upstream/release-1.4
$ make clean; make release
$ ./cluster/kube-up.sh
$ git co upstream/release-1.5
$ ./cluster/gce/upgrade.sh -M v1.5.0-beta.1
$ git co upstream/release-1.4
$ ./cluster/kube-down.sh
```

### PR DESCRIPTION
**Pull request by roberthbailey**
**What this PR does / why we need it**: This PR fixes an error in the gce shell scripts that results in inconsistent/incorrect behavior. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #37385

**Special notes for your reviewer**: This needs to be backported to 1.5 and 1.4. 

@jszczepkowski

### CODE REVIEW

**Comment by roberthbailey** [comment]
@saad-ali @jessfraz

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37638)

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jszczepkowski** [comment]
LGTM

**Comment by roberthbailey** [comment]
@dims is there a magic incantation to re-run just the jenkins verification tests (which appear to have stalled out)?

**Comment by dims** [comment]
Here's my cheat sheet @roberthbailey :) 
https://gist.github.com/dims/c8d51bf8debf0d77448fde318232c012

**Comment by dims** [comment]
@k8s-bot verify test this

**Comment by roberthbailey** [comment]
Can we move your cheat sheet into a document?

**Comment by roberthbailey** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
I assigned myself so we remember to cherry-pick for 1.4

**Comment by roberthbailey** [comment]
@k8s-bot verify test this

**Comment by rmmh** [comment]
@k8s-bot test this issue kubernetes/test-infra#1253 (also, deleting spurious failure comments)

**Comment by roberthbailey** [comment]
@jessfraz - cherry pick for 1.4 is https://github.com/kubernetes/kubernetes/pull/37780 (assigned to you)

**Comment by roberthbailey** [comment]
@saad-ali - cherry pick for 1.5 is https://github.com/kubernetes/kubernetes/pull/37781 (assigned to you)

**Comment by jbeda** [comment]
Sorry I missed this.  An alternative for doing math in bash (and we can assume bash at this point) is to use the `((..))` construct.  See http://www.tldp.org/LDP/abs/html/testconstructs.html.

**Pull request merged**
