### PR TITLE
update CodecFor for GroupVersion

### PR DESCRIPTION
**Pull request by deads2k**
Updates CodecFor for GroupVersion.  More cleanup.  The edges are starting to knit together. :)

ref https://github.com/kubernetes/kubernetes/issues/17216

@caesarxuchao @liggitt

### CODE REVIEW

**Comment by caesarxuchao** [comment]
> The edges are starting to knit together. :)

Great!

Do you want to me to review this one? I've taken a quick pass, sgtm.

**Comment by liggitt** [comment]
I got stalled 95% of the way through... LGTM

**Comment by deads2k** [comment]
timeout

@k8s-bot unit test this please

**Comment by deads2k** [comment]
@k8s-bot unit test this please

**Comment by deads2k** [comment]
@k8s-bot unit test this please

**Comment by deads2k** [comment]
@k8s-bot unit test this please

**Pull request merged**
