### PR TITLE
Turning on pod autoscaler on GCE.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Implemented optional turning on of pod autoscaler in kube-up script for GCE.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
This PR was originally merged as #13547 and the rolled-back in #13824 due to probelms in GKE. This PR fixes GKE problems.

**Comment by piosz** [comment]
cc @jlowdermilk

**Comment by piosz** [comment]
LGTM

**Comment by jszczepkowski** [comment]
Merging manually as I want to check if GKE is passing and roll-back if not.

**Comment by jlowdermilk** [comment]
[Passing](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci/8337/) on GKE. Thanks!

**Comment by jszczepkowski** [comment]
Part of #12087.

**Pull request merged**
