### PR TITLE
Bind  kube-dns containers to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:

Bind  kube-dns containers to linux nodes to avoid Windows scheduling, because the kube-dns container based on linux container not windows container

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Bind kube-dns containers to linux nodes to avoid Windows scheduling
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wawa0210** [comment]
ping @bowei

**Comment by bowei** [comment]
cc: @kubernetes/sig-windows-misc 
It would be good to get a sign off from someone on sig-windows.

**Comment by wawa0210** [comment]
> cc: @kubernetes/sig-windows-misc
> It would be good to get a sign off from someone on sig-windows.

@liggitt  @PatrickLang  

Hi guys, can you help review this pr. My mistake, the submission of months ago, has not been followed up

**Review by pires — APPROVED** [review]
/lgtm

**Comment by wawa0210** [comment]
@feiskyer  Can you help reivew this pr ?

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by wawa0210** [comment]
@bowei Can you approve this pr ? thanks so much

**Comment by wawa0210** [comment]
https://github.com/kubernetes/kubernetes/pull/83364

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
