### PR TITLE
[Federation] Remove redundant e2e

### PR DESCRIPTION
**Pull request by marun**
Now that federation of replicasets and deployments is implemented with the sync controller, the previous crud e2e duplicates coverage provided by the crudtester integration and e2e testing.

cc: @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by marun** [comment]
Rebased on #48621 to avoid having the unit job flake.

**Comment by perotinus** [comment]
/lgtm

Thanks, Maru!

**Comment by perotinus** [comment]
@marun Do you have an issue you can associate with this PR?

**Comment by marun** [comment]
@perotinus No, should be possible to ``/approve no-issue``.

**Comment by perotinus** [comment]
@csbell Can you `/approve no-issue`?

**Pull request merged**
