### PR TITLE
Refactor describe.go with PrefixWriter

### PR DESCRIPTION
**Pull request by oulinbao**
**What this PR does / why we need it**:
 refactor describeContainers function and decrease gocyclo result

**Special notes for your reviewer**:
the new PR for 36032
https://github.com/kubernetes/kubernetes/pull/36032

**Release note**:
```release-note
```NONE

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36732)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by pwittrock** [comment]
@ymqytw Would you review this?

**Comment by pwittrock** [comment]
@k8s-bot gci gke e2e test this

**Comment by pwittrock** [comment]
@oulinbao FYI, we are in feature freeze and will not merge this until after master is re-opened.

**Comment by ymqytw** [comment]
> @ymqytw Would you review this?

@pwittrock I will review it today.

**Comment by pwittrock** [comment]
@ymqytw Thanks

**Comment by oulinbao** [comment]
@pwittrock, @ymqytw, thanks for your review.
I will try to find other issue to contribute :-)

**Comment by ymqytw** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kubectl/describe.go, line 852 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_qOMpgbTBJ3AlL2Sw:-KW_qOMpgbTBJ3AlL2Sx:b-m0nmge) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L852)):*
> ```Go
> }
> 
> const (
> ```

Leave a comment here to show each level has 2 spaces.

---

*[pkg/kubectl/describe.go, line 859 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_raQ_Oje2GBtjDSKq:-KW_raQ_Oje2GBtjDSKr:b-93rbg3) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L859)):*
> ```Go
> )
> 
> // TODO: Do a better job at indenting, maybe by using a prefix writer
> ```

I think we can remove this comment.

---

*[pkg/kubectl/describe.go, line 888 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_mYcq3R-yUZPz2CMf:-KW_mYcrn0FDPioeSa38:bh667ky) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L888)):*
> ```Go
> 		none = "<none>"
> 	}
> 	writer.Write(LEVEL_0, "%s%s: %s\n", space, label, none)
> ```

There will be one additional space here. Not identical as before. May move the space to `none`.

---

*[pkg/kubectl/describe_test.go, line 365 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_sqUMktPx4dmoNPZa:-KW_sqUMktPx4dmoNPZb:bdmioja) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe_test.go#L365)):*
> ```Go
> 		describeContainers("Containers", pod.Spec.Containers, pod.Status.ContainerStatuses, EnvValueRetriever(&pod), out, "")
> 		output := out.String()
> 		if strings.Contains(output, "%!s(MISSING)") {
> ```

Maybe I miss something. But why we need this?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by ymqytw** [comment]
@oulinbao Overall looks good.
There are some other functions that need your `prefixWriter`, such as describeStatus etc.
Can you make the change in this PR or in a follow up PR which is based on this PR. Thanks

**Comment by oulinbao** [comment]
@ymqytw, thanks for your review. I will improve it today.

**Comment by oulinbao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kubectl/describe.go, line 852 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_qOMpgbTBJ3AlL2Sw:-KWeiu--VwQRbn-dJ_XA:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L852)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Leave a comment here to show each level has 2 spaces.
</details>
Done.

---

*[pkg/kubectl/describe.go, line 859 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_raQ_Oje2GBtjDSKq:-KWej-5-3Z6qKb1fqsWO:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L859)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> I think we can remove this comment.
</details>
Done.

---

*[pkg/kubectl/describe.go, line 888 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_mYcq3R-yUZPz2CMf:-KWej4q9mU9OViXotyj2:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe.go#L888)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> There will be one additional space here. Not identical as before. May move the space to `none`.
</details>
Done.

---

*[pkg/kubectl/describe_test.go, line 365 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_sqUMktPx4dmoNPZa:-KWejSxVRy3dpCvt1kt3:b-kb4rzy) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe_test.go#L365)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Maybe I miss something. But why we need this?
</details>
This PR test failed in test-cmd.sh but ut is passed at first time. Because in new function PrefixWrite.Write(), I forgot "..." after variable a as a parameter to a...Interface{}.
	fmt.Fprintf(this.out, prefix+format, a...)
So, some parameters were not transfered to function but only the first one. The result of this mistake caused "%!s(MISSING)" printed out.
I think UT didn't cover this sinario, do you have a better ideal?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/describe_test.go, line 365 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_sqUMktPx4dmoNPZa:-KWfGmy9qVKeEMWGi1bj:b-aoa1xp) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe_test.go#L365)):*
It is actually an error message from [`fmt`](https://golang.org/pkg/fmt/#pkg-overview) package. 
It is called: `Too few arguments: %!verb(MISSING)`

> "%!s(MISSING)"

I prefer not to use this to catch the error. I think we can modify or add new test case to cover this scenario. 
An idea is targeting format that has two verb e.g. `%s:\t%s\n`

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by oulinbao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kubectl/describe_test.go, line 365 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KW_sqUMktPx4dmoNPZa:-KWfsnak9LXIIE1hxhvS:bme7c17) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e513e8110a7980abf7d21c0bcfdf9f6cac0b9d1/pkg/kubectl/describe_test.go#L365)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> It is actually an error message from [`fmt`](https://golang.org/pkg/fmt/#pkg-overview) package. 
> It is called: `Too few arguments: %!verb(MISSING)`
> 
> > "%!s(MISSING)"
> 
> I prefer not to use this to catch the error. I think we can modify or add new test case to cover this scenario. 
> An idea is targeting format that has two verb e.g. `%s:\t%s\n`
</details>
The normal output is
Containers:
  test:
    Container ID:	
    Image:	image
    Image ID:	
    Port:	
    Steate:	Running
      Started:	Wed, 16 Nov 2016 14:34:08 +0800
    Ready:	True
    Restart Count:	7
    Volume Mounts:	<none>
    Environment Variables:	<none>

and when forget ..., it prints:

[ Containers ]%!s(MISSING):%!s(MISSING)
  [ test]%!v(MISSING):
    Container ID:	[]
    Image:	[image]
    Image ID:	[]
    Port:	[]
    [State]:	Running
      Started:	[Wed, 16 Nov 2016 14:36:44 +0800]
    Ready:	[True]
    Restart Count:	[7]
    Volume Mounts:[	<none>]
    Environment Variables:[	<none>]

If we only check the filed value existed or not, I think it's useless. Because the parameters are converted to array and printed out with '[]'.
I also checked that why test-cmd.sh can find this error, because UT and IT used different output method separately.
I will delete the change in test.go and depend on IT only.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by oulinbao** [comment]
@ymqytw, PTAL, thanks.

**Comment by ymqytw** [comment]
@oulinbao I will review it later today.

**Comment by ymqytw** [comment]
@oulinbao Why some code still using `Printf()` if we have `LEVEL_0`. IMO we can use your prefix writer everywhere possible in `describe.go`.
#35295 or your PR will need rebase, depends on which one merges first.

**Comment by ymqytw** [comment]
And please change the title, since we are touching code beyond describing containers.

**Comment by oulinbao** [comment]
OK, there will be many replacing work to do. I will change it today.
And thanks for your reminding with the rebase.

**Comment by oulinbao** [comment]
@ymqytw, I have finished the modification, but CI failed. Maybe something wrong with CI, I can't get details information with the hyper-link. Please have a look, thanks.

**Comment by ymqytw** [comment]
>Also, I found some statements printed out with only one prefix white space, such as DescribeResourceQuotas. Could I change it to LEVEL_1?

I won't do that. I will change each `LEVEL` from 2 white spaces to 1. And I believe it will make it even more flexible for others that need odd number of white spaces.

It seems that you have touched the files other than `describe.go` and `describe_test.go`. I'm sorry for not being very clear.
I think we should keep the `PrefixWriter` used only in `describe.go` and `describe_test.go`, since this PR is refactoring `describe`. If you want to use it else where, we can open new PRs for that. :)

**Comment by ymqytw** [comment]
@k8s-bot bazel test this

**Comment by ymqytw** [comment]
*[pkg/kubectl/describe.go, line 880 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KX97EBQN237I0woCFyd:-KX97EBQN237I0woCFye:b-oj0z44) ([raw file](https://github.com/kubernetes/kubernetes/blob/08098dbc7c0d498918a59078a0162cef1cf3a138/pkg/kubectl/describe.go#L880)):*
> ```Go
> }
> 
> func (this *PrefixWriter) Write(level int, format string, a ...interface{}) {
> ```

nit: I think in golang we usually don't use `this`. Considering using something like `pwriter` or `pw`or `prefixWriter`?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by ymqytw** [comment]
@k8s-bot bazel test this

**Comment by ymqytw** [comment]
@k8s-bot bazel test this

**Comment by oulinbao** [comment]
Do you mean we should not modify the declaration of DescribePodTemplate and tabbedString?
1) func DescribePodTemplate(template *api.PodTemplateSpec, out io.Writer)
2) func tabbedString(f func(io.Writer) error) (string, error)

Only these two functions need to change other files. But if we didn't modify the function tabbedString, I will make a PrefixWriter instance in every location which tabbedString is called. If you still insist on your opinion, I will change it back.

**Comment by oulinbao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/kubectl/describe.go, line 880 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KX97EBQN237I0woCFyd:-KX9jZEuKXcnxnnJMi-7:b32w0x) ([raw file](https://github.com/kubernetes/kubernetes/blob/08098dbc7c0d498918a59078a0162cef1cf3a138/pkg/kubectl/describe.go#L880)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> nit: I think in golang we usually don't use `this`. Considering using something like `pwriter` or `pw`or `prefixWriter`?
</details>
OK

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by oulinbao** [comment]
Do you mean we should not modify the declaration of DescribePodTemplate and tabbedString?
1) func DescribePodTemplate(template *api.PodTemplateSpec, out io.Writer)
2) func tabbedString(f func(io.Writer) error) (string, error)

Only these two functions need to change other files. But if we didn't modify the function tabbedString, I will make a PrefixWriter instance in every location which tabbedString is called. If you still insist on your opinion, I will change it back.

**Comment by oulinbao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/kubectl/describe.go, line 880 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KX97EBQN237I0woCFyd:-KX9jltgwF8A3JY3bGNA:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/08098dbc7c0d498918a59078a0162cef1cf3a138/pkg/kubectl/describe.go#L880)):*
<details><summary><i>Previously, oulinbao (欧林宝) wrote…</i></summary>
> OK
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by oulinbao** [comment]
@ymqytw, BTW, I don't know how to finished reviewable discussion. I have responded "Done" but not useless. Is that mean you should confirm and close it? 
Thank you for teaching so much. :)

**Comment by ymqytw** [comment]
@oulinbao Don't worry about the comments in reviewable, they will not block merging.

**Comment by oulinbao** [comment]
@ymqytw, I have rolled back the modification with other files. PTAL.
BTW, I'm sorry for making so many commit items, I have tried to squash but failed because collision.

**Comment by oulinbao** [comment]
git rebase -i HEAD~2

**Comment by ymqytw** [comment]
Hmm. In your case, you have 14 commits now.
Please try `git rebase -i HEAD~14`
And use `pick` mode for the first one and `fixup` mode for the others.
Please let me know if this works.

**Comment by ymqytw** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pkg/kubectl/describe.go, line 313 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIJrTgV9mgNKPquU5U:-KXIJrTgV9mgNKPquU5V:b-3pyltk) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L313)):*
> ```Go
> func DescribeLimitRanges(limitRanges *api.LimitRangeList, w *PrefixWriter) {
> 	if len(limitRanges.Items) == 0 {
> 		w.Write(LEVEL_0, "%s", "No resource limits.\n")
> ```

Why we using `%s` for some of the command?
We should make it consistent.

---

*[pkg/kubectl/describe.go, line 326 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK4sJLF-pBHxrI8o1:-KXIK4sJLF-pBHxrI8o2:bb73xfv) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L326)):*
> ```Go
> func DescribeResourceQuotas(quotas *api.ResourceQuotaList, w *PrefixWriter) {
> 	if len(quotas.Items) == 0 {
> 		w.Write(LEVEL_0, "%s", "No resource quota.\n")
> ```

Same

---

*[pkg/kubectl/describe.go, line 331 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK7h7zloT8Au76mf2:-KXIK7h7zloT8Au76mf3:bb73xfv) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L331)):*
> ```Go
> 	sort.Sort(SortableResourceQuotas(quotas.Items))
> 
> 	w.Write(LEVEL_0, "%s", "Resource Quotas")
> ```

Same

---

*[pkg/kubectl/describe.go, line 350 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK90MQ9XFJ5r9kXk7:-KXIK90MQ9XFJ5r9kXk8:bb73xfv) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L350)):*
> ```Go
> 
> 		w.Write(LEVEL_0, " Resource\tUsed\tHard\n")
> 		w.Write(LEVEL_0, "%s", " --------\t---\t---\n")
> ```

Same

---

*[pkg/kubectl/describe.go, line 531 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIKbh342-NAZ1NEEpy:-KXIKbh342-NAZ1NEEpz:bb73xfv) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L531)):*
> ```Go
> 		describeContainers("Containers", pod.Spec.Containers, pod.Status.ContainerStatuses, EnvValueRetriever(pod), w, "")
> 		if len(pod.Status.Conditions) > 0 {
> 			w.Write(LEVEL_0, "%s", "Conditions:\n  Type\tStatus\n")
> ```

Same

---

*[pkg/kubectl/describe.go, line 533 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIKcg9lS-jNJKeZ5cs:-KXIKcg9lS-jNJKeZ5ct:b7auo3j) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L533)):*
> ```Go
> 			w.Write(LEVEL_0, "%s", "Conditions:\n  Type\tStatus\n")
> 			for _, c := range pod.Status.Conditions {
> 				w.Write(LEVEL_1, "  %v \t%v \n",
> ```

Additional white spaces left.

---

*[pkg/kubectl/describe.go, line 1384 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINYiHqWcy5yQi0DKl:-KXINYiHqWcy5yQi0DKm:bb73xfv) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1384)):*
> ```Go
> 	for i, job := range jobs {
> 		if i != 0 {
> 			w.Write(LEVEL_0, "%s", ", ")
> ```

Same

---

*[pkg/kubectl/describe.go, line 1541 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINhRzorOFY9H02V6J:-KXINhRzorOFY9H02V6K:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1541)):*
> ```Go
> 		}
> 		w.Write(LEVEL_0, "%s", "Rules:\n  Host\tPath\tBackends\n")
> 		w.Write(LEVEL_1, "%s", "----\t----\t--------\n")
> ```

Same these two

---

*[pkg/kubectl/describe.go, line 1886 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINylspzNZgnbJNdHY:-KXINylspzNZgnbJNdHZ:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1886)):*
> ```Go
> 		if len(node.Status.Conditions) > 0 {
> 			w.Write(LEVEL_0, "%s", "Conditions:\n  Type\tStatus\tLastHeartbeatTime\tLastTransitionTime\tReason\tMessage\n")
> 			w.Write(LEVEL_1, "%s", "----\t------\t-----------------\t------------------\t------\t-------\n")
> ```

Same these two

---

*[pkg/kubectl/describe.go, line 2128 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOAm_Sqxk8XWL-cYz:-KXIOAm_Sqxk8XWL-cZ-:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2128)):*
> ```Go
> 	w.Write(LEVEL_0, "Non-terminated Pods:\t(%d in total)\n", len(nodeNonTerminatedPodsList.Items))
> 	w.Write(LEVEL_1, "%s", "Namespace\tName\t\tCPU Requests\tCPU Limits\tMemory Requests\tMemory Limits\n")
> 	w.Write(LEVEL_1, "%s", "---------\t----\t\t------------\t----------\t---------------\t-------------\n")
> ```

Same these two

---

*[pkg/kubectl/describe.go, line 2150 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOHZ_Hu-VG5QEWBIJ:-KXIOHZ_Hu-VG5QEWBIK:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2150)):*
> ```Go
> 
> 	w.Write(LEVEL_0, "%s", "Allocated resources:\n  (Total limits may be over 100 percent, i.e., overcommitted.\n  CPU Requests\tCPU Limits\tMemory Requests\tMemory Limits\n")
> 	w.Write(LEVEL_1, "%s", "------------\t----------\t---------------\t-------------\n")
> ```

Same these two

---

*[pkg/kubectl/describe.go, line 2258 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIONCXKPSG0Lgt6XIt:-KXIONCXKPSG0Lgt6XIu:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2258)):*
> ```Go
> 		if len(d.Status.Conditions) > 0 {
> 			w.Write(LEVEL_0, "%s", "Conditions:\n  Type\tStatus\tReason\n")
> 			w.Write(LEVEL_1, "%s", "----\t------\t------\n")
> ```

Same these two

---

*[pkg/kubectl/describe.go, line 2422 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOQKMDqJRuOgcksq4:-KXIOQKMDqJRuOgcksq5:b-340mue) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2422)):*
> ```Go
> 		if len(cluster.Status.Conditions) > 0 {
> 			w.Write(LEVEL_0, "%s", "Conditions:\n  Type\tStatus\tLastUpdateTime\tLastTransitionTime\tReason\tMessage\n")
> 			w.Write(LEVEL_1, "%s", "----\t------\t-----------------\t------------------\t------\t-------\n")
> ```

Same these two

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732)*

**Comment by ymqytw** [comment]
@k8s-bot gci gce e2e test this

**Comment by ymqytw** [comment]
Please remember to reword your commit message. It's so ugly now.

**Comment by oulinbao** [comment]
I have rebased and ammend commit log.

---

Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/kubectl/describe.go, line 313 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIJrTgV9mgNKPquU5U:-KXJLFKtLJUuYsJOGhoX:b-5qf909) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L313)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Why we using `%s` for some of the command?
> We should make it consistent.
</details>
I have removed it.

---

*[pkg/kubectl/describe.go, line 326 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK4sJLF-pBHxrI8o1:-KXJLJ0xKDN6uPpqNeCh:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L326)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same
</details>
Done.

---

*[pkg/kubectl/describe.go, line 331 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK7h7zloT8Au76mf2:-KXJLJQlxkbgnDjJMxqj:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L331)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same
</details>
Done.

---

*[pkg/kubectl/describe.go, line 350 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIK90MQ9XFJ5r9kXk7:-KXJL259STUt1NVzo7cy:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L350)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same
</details>
Done.

---

*[pkg/kubectl/describe.go, line 531 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIKbh342-NAZ1NEEpy:-KXJL3aRlR3gEXsjeiAd:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L531)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same
</details>
Done.

---

*[pkg/kubectl/describe.go, line 533 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIKcg9lS-jNJKeZ5cs:-KXJL4Ey-Pw5OxouFUKD:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L533)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Additional white spaces left.
</details>
Done.

---

*[pkg/kubectl/describe.go, line 1384 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINYiHqWcy5yQi0DKl:-KXJL5hFf70DYLLHTMjp:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1384)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same
</details>
Done.

---

*[pkg/kubectl/describe.go, line 1541 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINhRzorOFY9H02V6J:-KXJL6jEIJF3rkQKRL3J:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1541)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---

*[pkg/kubectl/describe.go, line 1886 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXINylspzNZgnbJNdHY:-KXJL7d_uxjpOpGKbx9a:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L1886)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---

*[pkg/kubectl/describe.go, line 2128 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOAm_Sqxk8XWL-cYz:-KXJL8TetVCI9H82AVUB:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2128)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---

*[pkg/kubectl/describe.go, line 2150 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOHZ_Hu-VG5QEWBIJ:-KXJL9HSoCvNx6g4S3EK:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2150)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---

*[pkg/kubectl/describe.go, line 2258 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIONCXKPSG0Lgt6XIt:-KXJLA5tNh1DaT34951u:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2258)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---

*[pkg/kubectl/describe.go, line 2422 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-KXIOQKMDqJRuOgcksq4:-KXJLAnsZ9_HaF2j8D0L:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/15da5eb9c94991ca88eafda8ad9ca55cf91833a1/pkg/kubectl/describe.go#L2422)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Same these two
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36732#-:-KXJLNv4fxXf9UHFhQGY:b-jovi6m)*

**Comment by oulinbao** [comment]
@ymqytw, I have rebased and pushed, why this PR still prompts "This branch has conflicts that must be resolved"?

**Comment by ymqytw** [comment]
> @ymqytw, I have rebased and pushed, why this PR still prompts "This branch has conflicts that must be resolved"?

I guess this is because there are new changes merged into `pkg/kubectl/describe.go` after you rebased last time. Please rebase again. Sorry about that.

**Comment by ymqytw** [comment]
/lgtm
Thanks.

**Comment by ymqytw** [comment]
@k8s-bot cvm gke e2e test this

**Comment by oulinbao** [comment]
@ymqytw, thanks for your guidance. 
BTW, are you in MountainView? Do you review contributes' code on spare time, or work time? The person who works in Google is my idol, haha.

**Comment by ymqytw** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
