### PR TITLE
Assign label to pod when exec 'kubectl run' command with flags "--expose=true" and "--restart=Never"

### LINKED ISSUE #40503: kubectl run: doesn't assign label to pod
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:31:07Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Self-Hosted
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
When create pod with this command: `kubectl run go-http-test -it --rm --port 5000 --expose=true --image=tanapolsh/go-http-test --restart=Never`, pod don't have label `run=go-http-test` which doesn't matched with service's selector causing cannot use service to pod

**What you expected to happen**:
Every pod that is created with `kubectl run` should be assigned with label `run=${run_name}`

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
As the title says and issue #40503 mentioned.
cc @tanapoln 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #40503

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by fabianofranz** [comment]
@k8s-bot bazel test this
@k8s-bot unit test this

**Comment by xiangpengzhao** [comment]
I will check the failure.

**Comment by xiangpengzhao** [comment]
@k8s-bot kubemark e2e test this

**Comment by fabianofranz** [comment]
Thanks @xiangpengzhao, sorry about the delay
/lgtm
/approve

**Pull request merged**
