### PR TITLE
Remove explicit initialization and unwanted code block in pv_controller.go

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by humblec** [comment]
@msau42 PTAL :)

**Comment by humblec** [comment]
@thockin need your blessing here :)

**Comment by jsafrane** [comment]
I'd like to keep pv_controller.go as it is, as explicit as possible:

https://github.com/kubernetes/kubernetes/blob/71a4289af29aee92231594964853e3acfb7dc082/pkg/controller/volume/persistentvolume/pv_controller.go#L64-L66

It needs to be super crystal clear and without shortcuts.

**Comment by humblec** [comment]
>I'd like to keep pv_controller.go as it is, as explicit as possible:

Sure @jsafrane .. Thanks for the reference, closing this PR based on above comment..

**Pull request closed without merging**
