### PR TITLE
Copy annotations from StatefulSet to owned ControllerRevisions

### LINKED ISSUE #50158: DaemonSet and StatefulSet controllers should be consistent in annotation propagation to ControllerRevisions
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line: 
/kind bug
> /kind feature

**What happened**:
Currently both the `DaemonSet` and `StatefulSet` controllers create `ControllerRevision` objects. The `DaemonSet` controller propagates annotations in a `DeamonSet`’s metadata to the `ControllerRevision` objects it owns. The `StatefulSet` controller, however, does not do so to the `ControllerRevision` objects it owns.

**What you expected to happen**:
The `DaemonSet` and `StatefulSet` controllers should do annotation propagation consistently. Either they both do it or none of them does it.

**How to reproduce it (as minimally and precisely as possible)**:
N/A.

**Anything else we need to know?**:
@kow3ns @janetkuo 

**Environment**: 
N/A.

### PR DESCRIPTION
**Pull request by liyinan926**
**What this PR does / why we need it**:
This PR starts copying annotations from a `StatefulSet`'s metadata to the `ControllerRevision`s it owns. `DaemonSet` controller copies the annotations from a `DaemonSet`s metadata to the `ControllerRevision`s it owns. One of the annotation copied is `kubernetes.io/change-cause`, which is used in `DaemonSetHistoryViewer` to fill in the `CHANGE-CAUSE` column of revision history of a `DaemonSet`.

For consistency, the `StatefulSet` controller should do the same, i.e., copy annotations in a `StatefulSet`'s metadata to the `ControllerRevision`s it owns for consistency. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50158.

**Special notes for your reviewer**:
/assign @kow3ns 

**Release note**:
```release-note
Copy annotations from a StatefulSet's metadata to the ControllerRevisions it owns
```

### CODE REVIEW

**Review by kow3ns — APPROVED** [review]

**Comment by liyinan926** [comment]
@kow3ns need a lgtm label. Thanks!

**Comment by liyinan926** [comment]
@kow3ns Now need your approval again after the lgtm was added. Thanks!

**Pull request merged**
