### PR TITLE
Call master-branch e2e-runner.sh from release-1.1 e2e.sh

### PR DESCRIPTION
**Pull request by spxtr**
ref #18981

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM

**Comment by ixdy** [comment]
@k8s-bot e2e test this

**Comment by spxtr** [comment]
Different flakes each time:
```
[Fail] Kubectl client Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance] 
```
```
[Fail] Kubectl client Update Demo [It] should scale a replication controller [Conformance] 
```

@k8s-bot e2e test this again please

**Comment by spxtr** [comment]
Manual merge to watch Jenkins.

**Pull request merged**
