### PR TITLE
Add fluentd.log to the list of rotated files in salt-based deployments

### PR DESCRIPTION
**Pull request by crassirostris**
Fix https://github.com/kubernetes/kubernetes/issues/43772

/cc @piosz

### CODE REVIEW

**Comment by crassirostris** [comment]
@roberthbailey Please take a look

**Comment by roberthbailey** [comment]
If you aren't running fluentd on the salt node, what happens?

**Comment by crassirostris** [comment]
> If you aren't running fluentd on the salt node, what happens?

Whoops, you're correct, we don't set up missingok is the salt logrotate config. Thanks, nvm this pr then, I have several reasons already to revert back to sending logs to the stdio instead of a separate file

**Comment by crassirostris** [comment]
PR to fix the issue instead this one: https://github.com/kubernetes/kubernetes/pull/47860

**Pull request closed without merging**
