### PR TITLE
    Add Alicloud Provider support which include SLB with https http h…

### PR DESCRIPTION
**Pull request by aoxn**
## Alicloud Provider

Alicloud provider enbales you with AlibabaCloud SLB capability. It support the most recent CloudProvider interface. And it is convenient in shifting to the newly controller based cloudprovider model.
You can create kubernetes service with SLB support. Through kubernetes annotation, you can define the SLB behavior by yourself, like supporting https ,health checking, bandwidth, address type .etc.
Storage support is in progress.

#### Cloud config
Suppose configuration file located in ```/root/alicloud.conf```

```
{
    "global": {
     "accessKeyID": "replace with your own access key id",
     "accessKeySecret": "replace with your own access key id",
     "kubernetesClusterTag": "hangzhou-kube",
     "region": "cn-hangzhou"
   }
}
```

* ```accessKeyID``` and ```accessKeySecret``` must be provided for SLB creation matters.
* ```region``` must be provided if you are in classic network. If your ECS located in VPC network, ```region``` won`t be nesscery. Thus, driver will detect it automatically.
* Finally, set ```kubelet```, ```controller-manager```, ```api-server``` start parameters with ```--cloud-provider=alicloud --cloud-config=/root/alicloud.conf```

#### Service configuration

See a demo with https LB.  Suppose service filename is ```service.yml```.

* First, set service ```type:LoadBalancer``` ; 
* Second, set SLB to use ```https:443``` protocol and port by annotate the service with ```"service.beta.kubernetes.io/alicloud-loadbalancer-ProtocolPort":"https:443"```. Remember, enable https feature needs cert file. You need to upload an certificate to [AlibabaCloud](https://slbnew.console.aliyun.com/#/certificate/) first before you can use it. Once certificate has been uploaded, you can designate ```CertID``` with annotation ```"service.beta.kubernetes.io/alicloud-loadbalancer-CertID" : "1694972343341318_1593a66ec58"```. 
* Third, Adjust you SLB behavior with other annotation, like Bandwidth, AddressType,HealthCheckFlag.
* Finally, ``` kubectl apply -f service.yml```. Once finished, your service file would look like something below.

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service",
        "annotations": {
			   "service.beta.kubernetes.io/alicloud-loadbalancer-ProtocolPort" : "https:443",
			   "service.beta.kubernetes.io/alicloud-loadbalancer-Bandwidth" : "60",
			   "service.beta.kubernetes.io/alicloud-loadbalancer-CertID" : "1694972343341318_1593a66ec58",
			   "service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckFlag": "on",
			   "service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckInterval": "10"
		}
    },
    "spec": {
        "selector": {
            "app": "my-nginx"
        },
        "ports": [
            {
                "name": "http",
                "protocol": "TCP",
                "port": 443,
                "targetPort": 80
            }
        ],
        "type": "LoadBalancer"
    }
}
```

Enjoy you roll!

#### Annotations

Alicloud Provider support SLB with planty of features through annotations. Pls note for it is case sensitive.

Annotation          | Description           | Default     |
----------------------------------------|---------------------------------------|----------|
service.beta.kubernetes.io/alicloud-loadbalancer-ProtocolPort|comma separated pair like "https:443,http:80"|none|
service.beta.kubernetes.io/alicloud-loadbalancer-AddressType|Be "internet" or "intranet"|"internet"|
service.beta.kubernetes.io/alicloud-loadbalancer-ChargeType|Be "paybytraffic" or "payby bandwidth"|"paybybandwidth"|
service.beta.kubernetes.io/alicloud-loadbalancer-Region|Which region this SLB in||
service.beta.kubernetes.io/alicloud-loadbalancer-Bandwidth|SLB bandwidth| 50 |
service.beta.kubernetes.io/alicloud-loadbalancer-CertID| certification id on AlibabaCloud, you need to upload first| ""|
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckFlag|"on" or "off"| "off" tcp no need for this mark because it default to "on" |
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckType|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckURI|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckConnectPort|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthyThreshold|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-UnhealthyThreshold|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckInterval|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckConnectTimeout|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||
service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckTimeout|see [HealthCheck](https://help.aliyun.com/document_detail/27594.html?spm=5176.doc27593.6.638.VwvEYu)||

### CODE REVIEW

**Comment by bgrant0607** [comment]
@thockin Are we adding new in-tree cloudproviders at this point?

**Comment by thockin** [comment]
Hi @spacexnice - thanks for the PR.  I am super excited to get alicloud on-board, but we're not taking new in-tree providers right now.  We're in the process of moving all of the CloudProvider code out of the main repository and into separate per-provider binaries.  As such, we can not merge this PR.

If you have any free time to help, I am sure @wlan0 could use some help - he's driving the very large refactoring needed to make this happen.  In the mean time, you can run almost all of this as a set of standalone controllers, rather than being plugged into the main controller loops.  This is how everyone (even Google Cloud) will operate in the future.

**Comment by spacexnice** [comment]
@thockin Pretty much thanks!  @wlan0 Is there anything i can do to help?

**Comment by Crazykev** [comment]
Hi @thockin @wlan0 Is there any open issue or discussion about where these separate CloudProvider codes should be? I also want to bring AliCloud other feature support to kubernetes.
>We're in the process of moving all of the CloudProvider code out of the main repository and into separate per-provider binaries.

Is this done already? If there is anything I can help, please let me know.

**Comment by Crazykev** [comment]
Hi @spacexnice are you still working on this? Very glad to help.

**Comment by spacexnice** [comment]
@Crazykev  https://github.com/AliyunContainerService/kubernetes   here is Alibaba Cloud Provider fork.  we will try to make a pr when K8s refactor has been finished.  You are welcome to make PR to ```https://github.com/AliyunContainerService/kubernetes``` repository.

**Comment by Crazykev** [comment]
@spacexnice Thanks, I'll check if I can do anything with it.

**Pull request closed without merging**
