### PR TITLE
Log if PV is still in use trying to delete it

### PR DESCRIPTION
**Pull request by sky-philipalmeida**
Similar to what we have in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L181
The objective is to have a easy way to monitor if a PV will enter in Terminating state due to a failed removal when still in use.
This way we can capture the PV log and alert according.
The code is not tested.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sky-philipalmeida** [comment]
I have sign it!

**Comment by sky-philipalmeida** [comment]
Not sure what is failing can you please help.
I have compile it with the code changes no errors there :)

**Comment by sky-philipalmeida** [comment]
Failing job pull-kubernetes-e2e-gce-csi-serial seems not related to the code been tested.
Seems to be a failure on the test suit itself.

**Comment by xing-yang** [comment]
Can you squash your commits?

**Comment by sky-philipalmeida** [comment]
sdfa

**Comment by sky-philipalmeida** [comment]
> Can you squash your commits?

Sorry I messed up the squash .
I think it is ok now can you please review @xing-yang  ?

**Comment by xing-yang** [comment]
The change looks good.  Waiting for CI to pass.

**Comment by sky-philipalmeida** [comment]
@xing-yang do I need to to anything else?
The CI process seems to be pending for a long time.
I have riend to trigger a retest but still see pending 16.

**Comment by coderanger** [comment]
@sky-philipalmeida If the goal is to expose this to end users, maybe we should set up a counter metric for it too? Would make it easier to watch on large fleets.

**Comment by sky-philipalmeida** [comment]
> @sky-philipalmeida If the goal is to expose this to end users, maybe we should set up a counter metric for it too? Would make it easier to watch on large fleets.

Yes that would be the best approach as we could also monitor it via Prometheus.
But this should aslo be applied to [PVC](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L181)

Atm I do not have the required knowledge to implement this to be honest, I know maybe kube-state-metrics integration would be the way to go.

**Comment by coderanger** [comment]
Please feel free to reach out to SIG-Instrumentation on Slack if you'd like help setting up a metric :)

**Pull request merged**
