### PR TITLE
Update fake_controller_source.go

### PR DESCRIPTION
**Pull request by wenjun93**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/ok-to-test

Can you please update your pr description and commit message with why its safe to remove this?

**Comment by yliaog** [comment]
the List method could be used today by code outside k8s/k8s, it could be useful in the future tests. it's better to keep it.

**Comment by wenjun93** [comment]
sorry for the mistake, closed this one

**Pull request closed without merging**
