### PR TITLE
kubeadm: enhance encryption algorithm support in v1beta4

### LINKED ISSUE #3003: Provide options to use at least 3072-bits RSA to meet German federal BSI Technical Guideline TR-02102-2
EDIT: neolit123

latest proposal was outlined as a feature for v1beta4 here:
https://github.com/kubernetes/kubeadm/issues/3003#issuecomment-1917467330

PR to merge:
- https://github.com/kubernetes/kubernetes/pull/123054

v1beta4 tracking issue:
https://github.com/kubernetes/kubeadm/issues/2890

----

## What keywords did you search in kubeadm issues before filing this one?

rsa

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`): main

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

This would have been a feature request, but as of 2024/1/1 this is now a bug. Germany's BSI (Federal Office for Information Security) requires government systems to use at least 3000 bit RSA keys since 2024/1/1. This means that kubeadm cannot meet federal security standards as the 2048-bit RSA key length is hardcoded.

>3000 bit keys are considered good until 2030.

Recommend changing the default to 3072-bits. This should have no impact on existing clusters.

## What you expected to happen?

To have keys defaulted to >3000-bits, or have the option to do so.

## How to reproduce it (as minimally and precisely as possible)?

N/A

## Anything else we need to know?

Guidelines are at https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.pdf?__blob=publicationFile&v=10 

No other deltas found against standards.

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Previous v1beta4 work added support for
ClusterConfiguration.EncryptionAlgorithm, however the possible values were limited to just "RSA" (2048 key size) and "ECDSA" (P256).

Allow more arbitrary algorithm types, that can also include key size or curve type encoded in the name:
"RSA-2048" (default), "RSA-3072", "RSA-4096" or "ECDSA-P256".

Update the deprecation notice of the PublicKeysECDSA FeatureGate as ideally it should be removed only after v1beta3 is removed.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3003
see https://github.com/kubernetes/kubeadm/issues/3003#issuecomment-1917467330

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

(intentionally none)

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold for review
/triage accepted
/priority important-soon
(1.30)

**Review by SataQiu — APPROVED** [review]
/lgtm
/approve

**Review by neolit123 — COMMENTED** [review]
/hold cancel

**Comment by sftim** [comment]
Which PR has the changelog entry for this?

**Comment by neolit123** [comment]
> Which PR has the changelog entry for this?

none yet, when we are about to release v1beta4 we will push a PR with a bug release note that has all the new features in this API
https://github.com/kubernetes/kubernetes/pull/123054/files#diff-5c925db27fad81e7d11666a4fe0012055a00ebf625f2e7327b20f846ef54d586

**Pull request merged**
