### PR TITLE
Automated cherry pick of #94367: Update CNI plugins to v0.8.7

### PR DESCRIPTION
**Pull request by xmudrii**
Cherry pick of #94367 on release-1.19.

#94367: Update CNI plugins to v0.8.7

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by xmudrii** [comment]
This is required for the upcoming patch releases.

/assign @justaugustus 
cc: @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by spiffxp — APPROVED** [review]
/approve

**Comment by cpanato** [comment]
/kind cleanup
from parent PR

**Pull request merged**
