### PR TITLE
Add comments in several hack/*.sh

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Add or update the comments for the following scripts.

hack/ginkgo-e2e.sh
hack/grab-profiles.sh
hack/install-etcd.sh
hack/lint-dependencies.sh
hack/list-feature-tests.sh
hack/local-up-cluster.sh
hack/pin-dependency.sh
hack/print-workspace-status.sh
hack/run-in-gopath.sh
hack/test-go.sh
hack/test-integration.sh

**Which issue(s) this PR fixes**:
ref:#86597

**Special notes for your reviewer**:
/cc @fejta

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by hase1128** [comment]
/assign @spiffxp 
Would you please review this PR?
Fejta seems to be offline recently.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
