### PR TITLE
bazel: kubelet deb package postinstall step

### PR DESCRIPTION
**Pull request by rdodev**
**What this PR does / why we need it**:
Presently bazel build .deb (kubelet.deb specifically) does not auto-restart after installation. Adding a postinst control file fixes this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
kubernetes/kubeadm#944
**Special notes for your reviewer**:

@chuckha  

```release-note
bazel deb package bugfix: The kubeadm deb package now reloads the kubelet after installation
```

### CODE REVIEW

**Comment by rdodev** [comment]
I'm at a loss how to fix these tests. Can they be safely ignored? 

// @chuckha

**Comment by chuckha** [comment]
confirmed this works as expected

/lgtm

**Comment by chuckha** [comment]
@rdodev looks like you've got some trailing whitespace

**Comment by chuckha** [comment]
cc @luxas

**Comment by rdodev** [comment]
Trailing white space removed.

**Comment by rdodev** [comment]
Maybe @timothysc can :eyes: and /approve given luxas isn't available today?

**Review by luxas — APPROVED** [review]
/lgtm
/approve

Thanks @rdodev!

**Comment by luxas** [comment]
I'd consider cherrypicking this
cc @timothysc

**Comment by timothysc** [comment]
@ixdy - So these packaging macros don't really support idiomatic deb packages. https://salsa.debian.org/debian/kubernetes/blob/master/debian/kubernetes-node.kubelet.init  

I'd almost prefer to have the directory structure under build and just call the packaging tools as a separate step vs. some 1/2 baked generation.  

Thoughts?

**Comment by luxas** [comment]
@timothysc open up an issue with your thoughts on that?

/hold
oh, wait, shouldn't this be for the kubeadm postinstall process vs the kubelet's? Or maybe for both would make sense?

**Comment by ixdy** [comment]
@timothysc I don't understand what you mean by "idiomatic deb packages", along with linking to https://salsa.debian.org/debian/kubernetes/blob/master/debian/kubernetes-node.kubelet.init.

**Comment by luxas** [comment]
@rdodev can you make this be in the kubeadm postinst instead to mirror the k8s/release debs please?

**Comment by rdodev** [comment]
@luxas sure can. Give me a few minutes.

**Comment by rdodev** [comment]
@luxas done. Retesting under way.

**Comment by rdodev** [comment]
@luxas I'm pretty sure this failure is unrelated.

**Review by luxas — APPROVED** [review]
/lgtm
/hold cancel
/retest
Thanks for fixing!

**Comment by luxas** [comment]
> I'm pretty sure this failure is unrelated.

yup it's unrelated indeed

**Pull request merged**
