### PR TITLE
Add support for deletecollection operation on services

### PR DESCRIPTION
**Pull request by astefanutti**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR adds support for the `deletecollection` operation on services.

**Does this PR introduce a user-facing change?**:

```release-note
Add support for the `deletecollection` operation on services
```

### CODE REVIEW

**Comment by liggitt** [comment]
This introduces a bug by which deletecollection on services bypasses all the service-specific logic in the overridden Delete method. Before this can be done, all of that logic needs to be moved to a finalizer and the custom Delete method removed.

/hold

**Comment by liggitt** [comment]
Additionally, the fact that no tests failed means that this did not add tests exercising the new function sufficiently.

**Comment by astefanutti** [comment]
@liggitt thanks a lot for your quick feedback. You're right about the issue that the the service-specific logic is by-passed. I'll work on adding the finalizer and add some tests ASAP. If you have some guidelines on what's the best approach to add the finalizer, that'd be great. Otherwise I'll try to find my way in the codebase. Thanks again.

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/pull/65912 for previous attempts
cc @jhorwit2 @kubernetes/sig-network-pr-reviews 
/sig network

**Comment by astefanutti** [comment]
@liggitt thanks a lot for the pointer. I think that gives me enough context. I'll work on it ASAP.

**Comment by liggitt** [comment]
unassigning myself, feel free to reassign once prereq issues are resolved and this is updated (with tests added)

**Comment by cmluciano** [comment]
@astefanutti Are you still working on the adjustments mentioned?

**Comment by astefanutti** [comment]
@cmluciano I still plan to work on it ASAP. Let me know if you prefer I close this PR and re-open a new one when it's ready.

**Comment by cmluciano** [comment]
@astefanutti I can help if this is something that you would benefit from

**Comment by astefanutti** [comment]
@cmluciano sorry for the late reply. It's not urgent for us at the moment. I still plan to tackle it at some point, and I'll be happy to have your guidance. Thanks.

**Comment by cmluciano** [comment]
> @cmluciano sorry for the late reply. It's not urgent for us at the moment. I still plan to tackle it at some point, and I'll be happy to have your guidance. Thanks.

@astefanutti No problem, feel free to ping me on here when you're ready.

**Pull request closed without merging**
