### PR TITLE
Use apimachinery util/rand instead of math/rand

### PR DESCRIPTION
**Pull request by ash2k**
**What this PR does / why we need it**:
`math/rand` is [initialized with seed = 1](https://github.com/golang/go/blob/release-branch.go1.11/src/math/rand/rand.go#L288). That means any code that uses `math/rand` may get a sequence of values that are not so random if the RNG is not seeded.
- Kubernetes codebase seeds `math/rand` in all `main()` functions but not all `TestMain()` functions (I'll fix that in a follow up PR). So quite a few (not all) tests have the issue described above.
- Bits of Kubernetes are exported into numerous repositories and are consumable as libraries. A lot of people are not aware that they need to seed the RNG in their `main()` and don't do it. How many hard to debug bugs does this cause?

Package `k8s.io/apimachinery/pkg/util/rand` [seeds the RNG with current time](https://github.com/kubernetes/kubernetes/blob/f5e9c0473c37bdef951238de63f35db5af176acd/staging/src/k8s.io/apimachinery/pkg/util/rand/rand.go#L30) when it is initialized and hence does not need any extra seeding from the user. This PR changes all `math/rand` usages in the codebase to `k8s.io/apimachinery/pkg/util/rand` to solve the issues outlined above. `math/rand` still need to be seeded because 3rd party libraries are relying on it.

This is a follow up for https://github.com/kubernetes/kubernetes/pull/69670.

**Release note**:
```release-note
NONE
```
/sig api-machinery
/kind bug

### CODE REVIEW

**Comment by awly** [comment]
Why doesn't `k8s.io/apimachinery/pkg/util/rand` seed `math/rand` via func init? And then alias all the functions instead of implementing wrappers?

Also, how can we prevent anyone from using math/rand again? Can there be a PR check catching this? I think that would need to happen first, before cleaning up.

**Comment by lavalamp** [comment]
I really hate that we copied math/rand :(

**Comment by yliaog** [comment]
what are your thoughts on the comment https://github.com/kubernetes/kubernetes/pull/69930#issuecomment-430723420 ?

**Comment by ash2k** [comment]
I forgot to answer, sorry.

> Why doesn't k8s.io/apimachinery/pkg/util/rand seed math/rand via func init?

1. I think mutating state in another package via `init()` is arguably a bad idea?
2. Would be hard to find out if a binary is safe because it transitively uses this package or not safe because it does not. Whereas if `math/rand` is seeded in `main()` + k8s.io/apimachinery/pkg/util/rand is used everywhere there is no such uncertainty.
3. Also nothing guarantees that a program that imports kube libraries is using `k8s.io/apimachinery/pkg/util/rand` and hence we'd still need to make the change to use it throughout codebase instead of `math/rand`. i.e. initializing in `init()` does not guarantee safety for 3rd party code.

> And then alias all the functions instead of implementing wrappers?

I'm not sure what you are suggesting. Something like `var Intn = rand.Intn` on package level? That makes those "functions" mutable/overridable and hence someone might mutate them e.g. in tests, compromising system. Immutable package functions feel safer.

> Also, how can we prevent anyone from using math/rand again?

There are plenty of verifying scripts in this repo. I'm sure something can be done.

> Can there be a PR check catching this? I think that would need to happen first, before cleaning up.

There can be, I think. I'll see if I can find an example that I can adapt. I'm not a bash expert, so please don't expect a new sophisticated script from me that ticks all the boxes. One potential complication is that there is code that uses `math/rand` in a few files but it does so "hermeticly" - it initializes a private instance of `Rand` and uses it. I decided not change it.

**Comment by awly** [comment]
> I think mutating state in another package via init() is arguably a bad idea?
Would be hard to find out if a binary is safe because it transitively uses this package or not safe because it does not. Whereas if math/rand is seeded in main() + k8s.io/apimachinery/pkg/util/rand is used everywhere there is no such uncertainty.
Also nothing guarantees that a program that imports kube libraries is using k8s.io/apimachinery/pkg/util/rand and hence we'd still need to make the change to use it throughout codebase instead of math/rand. i.e. initializing in init() does not guarantee safety for 3rd party code.

If you use it in conjunction with wrapper funcs, `k8s.io/apimachinery/pkg/util/rand` is always imported and required instead of `math/rand`.

> I'm not sure what you are suggesting. Something like var Intn = rand.Intn on package level? That makes those "functions" mutable/overridable and hence someone might mutate them e.g. in tests, compromising system. Immutable package functions feel safer.

Sorry, i thought we could do `func Intn = rand.Intn`, type-alias style. But that doesn't work.
But it could still do `func Intn() int { return rand.Intn() }`, instead of being a synchronized method on custom type.

I think we should put in a verifying script first to avoid doing another such cleanup later.

**Comment by awly** [comment]
By guess is: other Go projects are less gigantic and complex and can rely on humans to seed their RNGs when they use them. Also I bet they don't really suffer from unseeded RNGs.

My preference is:
- binaries: wrap up all common initialization (rand seeding, logs, etc) in one function and call it
- crypto tests: use crypto/rand
- fuzzing tests: use math/rand and seed it; it's a small subset and authors should know to do this
- other tests: doesn't matter if RNG is seeded

@ash2k have there been actual issues caused by lack of seeding? I want to make sure the extra complexity is justified.

**Comment by ash2k** [comment]
@awly 
> have there been actual issues caused by lack of seeding? I want to make sure the extra complexity is justified.

No, I just noticed some cleanups that could be done (see #69670) and then I decided to check the bigger picture. Things like how seeding is done, where new rands are constructed, how fuzzing tests seed rngs (most of them use fixed value! does not sound right to me, not much fuzzing), how integration tests that are started via `TestMain()` seed rng (many/most don't), how `main()` functions do seeding (many don't).

To be clear, I'm fine with dropping that change and only leaving the cleanups in this PR (or new PR) if the consensus is that this is not justified.

**Comment by awly** [comment]
A comprehensive should include preventing recurrence. That would be some kind of PR check, maybe part of pull-kubernetes-verify.
But if that's being done, could the check just detect un-seeded `math/rand`? If yes, it would be nice to drop this math/rand wrapper entirely. The wrapper just feels like a complex way to temporarily clean up the codebase.

I'll leave the decision to people who maintained the full k8s codebase for longer, my experience on this is insufficient.

**Comment by ash2k** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/71170.

**Pull request closed without merging**
