### PR TITLE
add "initializerconfiguration" as kubectl valid resource

### LINKED ISSUE #51088: kubectl does not support getting "initializerconfiguration"
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig cli

**What happened**:

The `apiserver` has already supported fetching `initializerconfiguration`, which has not been enabled in `kubectl`.

**What you expected to happen**:
Enable in `kubectl`

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Depends on #51865

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51088

**Special notes for your reviewer**:
/assign @sig-cli-maintainers
/cc @caesarxuchao @ahmetb 

**Release note**:

```release-note
add "initializerconfiguration" as kubectl valid resource
```

### CODE REVIEW

**Comment by ahmetb** [comment]
I'm not sure why this is necessary. `kubectl get initializerconfiguration` has been working for me. This also doesn't add a formatter for the `kubectl get` response, so we still dump the full Go object representation.

**Comment by caesarxuchao** [comment]
You'll have to add [printers](https://github.com/kubernetes/kubernetes/tree/master/pkg/printers) for `initializerconfiguration` to make this change useful. I don't think this is high priority. You might want to discuss the format with sig-cli member like @mengqiy before implement the printer.

**Comment by mengqiy** [comment]
@dixudx I'm not the best person for printer stuff. I will suggest @fabianofranz or @juanvallejo who are more familiar with printer codebase.

**Comment by ahmetb** [comment]
@dixudx PolicyType doesn't look good. (1) it should be named FailurePolicy (2) it is per initializer and not one per initializerconfiguration. Also I heard there might be plans to get rid of a configurable failure policy so it may not even be there in the beta.

I think it's still a bit early to create a printer for initializerconfiguration. Ideally, I'd love to see all the resources it initializes, cross-matched with the resources available on the API categorized by the initializer name (but this might be more suitable for `describe` output)

e.g.

```
Initializers:
      addsidecar.mycompany.com:
          v1.ReplicationController
          apps/v1beta1.Deployment
      checksomething.mycompany.com:
          v1.Secret
          v1.ConfigMap
```

**Comment by caesarxuchao** [comment]
> Also I heard there might be plans to get rid of a configurable failure policy so it may not even be there in the beta

Yes, I convinced @lavalamp on getting rid of the failure policy. I'll send a PR soon.

**Comment by juanvallejo** [comment]
@ahmetb 
>  Ideally, I'd love to see all the resources it initializes, cross-matched with the resources available on the API categorized by the initializer name (but this might be more suitable for describe output)

Agree, this sounds like it would fit best as part of a describe output. Maybe we could list the resource groups, or just total number of resources that are initialized, as part of the printer output

**Comment by ahmetb** [comment]
@juanvallejo agreed. let's add the printer, describe can be done later.

**Comment by mengqiy** [comment]
@dixudx Please update https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-overview.md#resource-types as well. Thanks.

**Comment by liggitt** [comment]
We should stop adding to this hard coded list, provide a command to list valid resources and short names for the current server instead (e.g. https://github.com/kubernetes/kubernetes/pull/42873)

If we implemented a table printer server side, would the kubectl change be needed?

**Comment by ahmetb** [comment]
I say we close this for now. It's not immediately needed for this feature to become beta. We can revisit later.

**Comment by dixudx** [comment]
Yeah. Close it now. Will reopen it if needed.

**Pull request closed without merging**
