### PR TITLE
Cleanup kubectl describe code

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does**:
- move all `tabbedString` into separate functions to keep same style
- delete unused functions

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by adohe** [comment]
@k8s-bot bazel test this

**Comment by adohe** [comment]
@k8s-bot verify test this

**Comment by xiangpengzhao** [comment]
Jenkins verification failed due to many unrelated errors:
```
W0407 19:33:36.882] I0407 19:33:36.881769   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/trace.go:139:30: cannot use (traceBufHeader literal) (value of type traceBufHeader) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
W0407 19:33:36.883] I0407 19:33:36.881919   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/trace.go:139:7: array length 64 << 10 - unsafe.Sizeof((traceBufHeader literal)) (value of type uintptr) must be constant
W0407 19:33:36.883] I0407 19:33:36.882119   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/mgcwork.go:285:37: cannot use (workbufhdr literal) (value of type workbufhdr) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
W0407 19:33:36.883] I0407 19:33:36.882164   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/mgcwork.go:285:7: array length (_WorkbufSize - unsafe.Sizeof((workbufhdr literal))) / sys.PtrSize (value of type uintptr) must be constant
W0407 19:33:36.884] I0407 19:33:36.882804   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/chan.go:21:28: cannot use (hchan literal) (value of type hchan) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
W0407 19:33:36.884] I0407 19:33:36.882881   13026 parse.go:394] type checker error: /usr/local/go/src/runtime/chan.go:21:66: cannot use (hchan literal) (value of type hchan) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
```

@adohe @fabianofranz

**Comment by xiangpengzhao** [comment]
@k8s-bot verify test this
@k8s-bot non-cri e2e test this

**Comment by xiangpengzhao** [comment]
@k8s-bot verify test this
@k8s-bot non-cri e2e test this

**Comment by xiangpengzhao** [comment]
@k8s-bot verify test this
@k8s-bot non-cri e2e test this

**Comment by zhangxiaoyu-zidif** [comment]
好无奈的测试。╮(╯▽╰)╭

**Comment by mengqiy** [comment]
@k8s-bot non-cri e2e test this

**Comment by mengqiy** [comment]
Please run hack/update-bazel.sh

**Comment by xiangpengzhao** [comment]
Updated. Thanks @mengqiy !

**Comment by fabianofranz** [comment]
@xiangpengzhao mind squashing the commits?

**Comment by xiangpengzhao** [comment]
@fabianofranz squashed. PTAL.
@soltysh please relabel lgtm.
ping @janetkuo or @smarterclayton for approve.
Thanks!

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
