### PR TITLE
Add inline JSON patching to kubectl update ...

### PR DESCRIPTION
**Pull request by brendandburns**
Builds on https://github.com/GoogleCloudPlatform/kubernetes/pull/3508  Please only review the second commit (1485c92)

@bgrant0607 @smarterclayton @ghodss

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'm going to rewrite update.go completely in a short period of time to make it resource.Builder aware, so I'd be ok if you left the hack in.

**Comment by brendandburns** [comment]
Comments addressed.  ptal.

Thanks!
--brendan

**Comment by smarterclayton** [comment]
LGTM

**Comment by brendandburns** [comment]
Done.  ptal.

Thanks
--brendan

**Comment by brendandburns** [comment]
Comment addressed, ptal.

**Comment by bgrant0607** [comment]
Know how to unstick Travis? It's been wedged for a couple hours.

**Comment by smarterclayton** [comment]
Kicked.  If you're a committer you should be able to log into Travis with your GitHub id and restart/cancel builds.

**Comment by bgrant0607** [comment]
Did that several times, to several builds. Didn't seem to make any difference.

**Comment by smarterclayton** [comment]
Maybe Travis finally gave up the ghost

**Pull request merged**
