### PR TITLE
Convert PrefixWriter to an interface

### PR DESCRIPTION
**Pull request by ncdc**
Convert PrefixWriter to an interface to allow other packages to create instances. This is needed for downstream projects such as OpenShift.

cc @sttts @smarterclayton @oulinbao @deads2k @liggitt @kargakis @soltysh @kubernetes/sig-cli-pr-reviews

### CODE REVIEW

**Comment by ncdc** [comment]
@k8s-bot unit test this #41892

**Comment by ncdc** [comment]
@k8s-bot kops aws e2e test this

**Comment by soltysh** [comment]
@k8s-bot kops aws e2e test this

**Comment by soltysh** [comment]
LGTM as well

**Comment by ncdc** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
Is there a followup pull which makes the PrefixWriter an interface?  Seems like exposing it as a struct with private fields was an accident and either the intent was to expose the fields or create an interface and this does neither.

**Comment by ncdc** [comment]
I don't see anything wrong with this. I agree an interface would be nicer, but this gets the job done.

**Comment by ncdc** [comment]
Working on switching to an interface.

**Comment by ncdc** [comment]
@deads2k @sttts updated

**Comment by ncdc** [comment]
@k8s-bot kops aws e2e test this

**Comment by deads2k** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
