### PR TITLE
[test-only] Remove retry in TestSubresourcePatch

### PR DESCRIPTION
**Pull request by kevindelgado**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Removes a retry loop in apiextensions-apiserver TestSubresourcePatch

Now that SSA no longer considers spec fields in patches submitted to /status (#99661), there is no managedFields timestamp update race.

#### Which issue(s) this PR fixes:

https://github.com/kubernetes/kubernetes/issues/75564#issuecomment-675104958 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kevindelgado** [comment]
assign @liggitt

**Comment by liggitt** [comment]
per test-freeze guidelines:

> Test Freeze
> The date after which no more tests may be added (or promoted to Conformance), unless there are release-blocking or other Exception-related reasons. Before this date, it is acceptable to improve test coverage of existing code. After this date, the goal is to fix, revert, or remove tests that are failing.

/milestone v1.21

**Pull request merged**
