### PR TITLE
Revert "Once again, use native Ginkgo test runner instead of cmd/e2e."

### PR DESCRIPTION
**Pull request by ixdy**
This change broke compilation on go 1.3 and running e2e tests on OS X. Details in #8357.
This reverts commit 86b023fdd6386a3c2a15d6bde38868b450647c6c.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Integration tests failed on shippable but unit tests and test-cmd.sh both passed.

**Comment by mbforbes** [comment]
Kicking shippable

**Comment by mbforbes** [comment]
-- said everyone always

**Comment by mbforbes** [comment]
Cool.

**Pull request merged**
