### PR TITLE
 Add domain field in NetworkPolicyPeer

### PR DESCRIPTION
**Pull request by chenchun**
**What this PR does / why we need it**:
Currently network policy supports setting ipBlock to manage ingress or egress traffic which is not a very convenient under such scenario:

I'm running a kubernetes cluster on qcloud offering my customers a public machine learning platform. They share this cluster by running machine learning pods in their own namespace. I don't want malicious tenant to disrupt my platform, so I'd like to make use of network policy to isolate each customer's pods. But their pods may make use of cloud services such as database, cloud storage, yum repo. Most of these cloud services are available via DNS names such as mirrors.tencentyun.com, tencent-distribute.com. I have to manually dig these DNS names to get ips and write them into network policy yaml. What if the backend ip changes ?

So I'd like network policy to support specify DNS domains as ingress or egress peer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
 Add domain field in NetworkPolicyPeer
```

### CODE REVIEW

**Comment by chenchun** [comment]
@kubernetes/sig-network-pr-reviews

**Comment by m1093782566** [comment]
@chenchun 

Thanks for your PR but I would suggest filing a document on your user cases and design first, especially for the API changes.

**Comment by cmluciano** [comment]
Related https://github.com/kubernetes/kubernetes/issues/50453#issuecomment-321669652 

cc @caseydavenport @thockin @danwinship I think DNSSelector was not on our roadmap & might not be possible without an HTTP proxy

**Comment by danwinship** [comment]
Can probably close this PR; if we're doing the feature, it needs design first, and might not end up being done this way. (Eg, we might want the DNS bits to be part of ipBlock so you can mix and match DNS and CIDRs.)

> might not be possible without an HTTP proxy

In theory you can do this without a proxy if you know where the pod is getting its DNS from. In particular, you could have a CoreDNS plugin where the network plugin tells it that it wants to monitor certain DNS names, and then any time a pod requests one of those names, the CoreDNS plugin gives the result to the network plugin first so that it can update itself before the pod has a chance to use the new IP addresses.

**Comment by chenchun** [comment]
Based on my scenario, I don't think there is a need of a HTTP proxy. My network plugin figures out the ips to the dns names by performing a dig on kubelet node.

What is the case of needing a HTTP proxy ?

**Comment by shreya-bhatnagar** [comment]
> Based on my scenario, I don't think there is a need of a HTTP proxy. My network plugin figures out the ips to the dns names by performing a dig on kubelet node.
> 
> What is the case of needing a HTTP proxy ?

@chenchun which network plugin are you using ? I also want to implement network policy based on domain name or wildcard characters so that domain names (FQDN/DNS) can be used to allow access from a pod or set of pods. You have some suggestion as to how you solved this problem in kubernetes ?

**Pull request closed without merging**
