### PR TITLE
Adding swagger UI to kubernetes.io

### PR DESCRIPTION
**Pull request by nikhiljindal**
This is to provide up-to-date documentation on kubernetes.io.

Future things to do:
1. Write a script to automate the process of copying swagger-spec.
2. UI improvements: Remove the "Try it out!" buttons, swagger search bar at the top.

This is how it looks right now:
image

@vmarmol: Is there a way to start a demo server and test this?
@bgrant0607

### CODE REVIEW

**Comment by vmarmol** [comment]
You can test with a simple file webserver:

```
package main

import (
	"log"
	"net/http"
)

func main() {
	// Simple static webserver:
	log.Fatal(http.ListenAndServe(":8080", http.FileServer(http.Dir("."))))
}
```

This will only serve static content. I think that's enough for this. What's supposed to be the main page for this content btw? It just seems like a bunch of JSON.

**Comment by nikhiljindal** [comment]
Yes I did that and it worked fine on my local webserver.
I was wondering if we can test it with kubernetes.io code.

third_party/swagger-ui/index.html is the main file.

**Comment by vmarmol** [comment]
Not without a [Jekyll](http://jekyllrb.com/) web server. We may need to get a test setup of that as we push more to the site. We're okay for now IMO. Since these files are disjoint from the main site this is okay to merge.

**Comment by vmarmol** [comment]
LGTM, anything else you want to try or are we okay to merge?

**Comment by nikhiljindal** [comment]
Thanks! Good to go from my end.
I will wait for Brian to have a look before merging.

**Comment by bgrant0607** [comment]
LGTM.

Future improvements:
* Document why json files are index.html
* Try to figure out a way to display the json from the main branch, such as using github API to retrieve them.

**Comment by nikhiljindal** [comment]
Thanks!
Verified that http://kubernetes.io/third_party/swagger-ui/ renders the Swagger UI as expected!

**Pull request merged**
