### PR TITLE
WIP: Begin versioning client

### PR DESCRIPTION
**Pull request by lavalamp**
See here for context: https://github.com/GoogleCloudPlatform/kubernetes/issues/4874#issuecomment-121401567

This doesn't work yet. Opening it anyway for feedback.

### CODE REVIEW

**Comment by mikedanese** [comment]
Please reassign when this is no longer WIP.

**Comment by krousey** [comment]
I think we may have to version `pkg/api/errors` to `pkg/api/v1/errors` to have an error for each version of `api.Status`. Why does the `errors` package even exist? Why isn't this part of the `api` package?

**Comment by krousey** [comment]
Or maybe the client shouldn't depend on that errors package and just have it's own.

**Comment by lavalamp** [comment]
> I think we may have to version pkg/api/errors to pkg/api/v1/errors to have an error for each version of api.Status. 

There are certain types that are (or will be) common across all versions, i.e. we've essentially agreed to never change them. api/resource.Quantity is one, TypeMeta will be another, and errors plausibly are in this category as well.

**Comment by pmorie** [comment]
Omg, +100

**Comment by krousey** [comment]
@lavalamp would it make sense to keep api.Status unchanged as well?

**Comment by deads2k** [comment]
@smarterclayton I'm OOO next week, can you reassign?  Also, do you know if there's a way to give the kubebot a vacation calendar?

**Pull request closed without merging**
