### PR TITLE
kubectl: display ready replicas in 'get {rs,rc}'

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/7483

@kubernetes/kubectl @janetkuo @bgrant0607

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30858)

### CODE REVIEW

**Comment by kargakis** [comment]
@janetkuo PTAL

**Comment by AdoHe** [comment]
@kargakis LGTM.  Please fix the failed unit tests.

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/31083

**Comment by kargakis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by kargakis** [comment]
applying lgtm

**Pull request merged**
