### PR TITLE
[WIP] Revert bump of DynamicKubeletConfig metrics deprecation to 1.23

### LINKED ISSUE #104041: Revert bump of DynamicKubeletConfig metrics deprecation to 1.23
This shipped in 1.22 as deprecated in 1.22. As a hacky fix to unbreak tests on 1.23 dev, I bumped the deprecation policy one release: https://github.com/kubernetes/kubernetes/pull/103980#issuecomment-888510879

We will need to revert that before 1.23 ships and figure out a better solution.

/kind cleanup
/milestone v1.23
/sig node

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Revert bump of DynamicKubeletConfig metrics deprecation to 1.23

#### Which issue(s) this PR fixes:

Fixes #104041

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
reverting of this will require allowing end-to-end tests to be configured to allow hidden metrics. Just reverting it back wouldn't work

/hold

**Comment by kerthcet** [comment]
> reverting of this will require allowing end-to-end tests to be configured to allow hidden metrics. Just reverting it back wouldn't work
> 
> /hold

yep, at first I thought I can handle all these cases inside the `beforeFunc` and the àfterFunc`, but the teardown cases with nil `configSource` broke my idea, for if we run the test cases with nil `configSource`, default kubelet configuration will take effect and fail the testcases with no metrics. Now I try to handle this with each case.  on the way right now.

**Comment by kerthcet** [comment]
/retitle Revert bump of DynamicKubeletConfig metrics deprecation to 1.23

**Comment by kerthcet** [comment]
@SergeyKanzhelev help to review the pr.  Some tests failed, but i don't think it's relate with my changes.

**Comment by yuzhiquan** [comment]
My pr is stuck in here, @kerthcet do you still working on this now?

**Comment by kerthcet** [comment]
> My pr is stuck in here, @kerthcet do you still working on this now?

as the pr described https://github.com/kubernetes/kubernetes/issues/105047, we'll remove the feature in release 1.23, so I think I'll close the pr. reopen it if necessary.

**Comment by yuzhiquan** [comment]
> > My pr is stuck in here, @kerthcet do you still working on this now?
> 
> as the pr described #105047, we'll remove the feature in release 1.23, so I think I'll close the pr. reopen it if necessary.

SG, thanks.

**Pull request closed without merging**
