### PR TITLE
kubeadm: use t.Run in app/phases

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Used T.Run API for kubeadm tests in app/phases/*

This should improve testing output and make it more visible
which test is doing what.

**Special notes for your reviewer**:

This is the latest PR in the series of around 10 similar PRs

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
thanks @bart0sh!
/approve

**Review by dixudx — APPROVED** [review]
Nice cleanup!

/lgtm

**Pull request merged**
