### PR TITLE
Add support for shared burstable pod resource limits

### LINKED ISSUE #84340: We need resource request/limit in the pod level
**What would you like to be added**:
Now, one of our usecases, we need to attach network NICs/ENIs into Pod. The number of NICs on a node is limited, so we create a device plugin to represent such a resource and calculate NICs requirement in scheduler. The problem is, we don't know where to put `request`/`limit` into the Pod spec. We don't think the container level is the right place, because network namespace and NICs are shared across containers in the same Pod. As a common question, do we need a way to represent resource requirement in Pod level?
 
**Why is this needed**:
See above

### PR DESCRIPTION
**Pull request by liorokman**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR enhances the `Burstable` QoS level for pods by allowing deployments to define resource limits which are enforced on the Pod level, rather than only on the Container level. 

While the current `Burstable` QoS level allows creating a resource limit for each containers, it doesn't allow defining a pod with an enforced resource limit that can be shared between multiple containers.  Enforcing a limit on the pod level means that developers can decide the overall amount of resources assigned to a pod without having to micro-manage the split of resources between containers in the pod. This allows supporting a more dynamic range of applications.

This PR offers this new functionality as an opt-in feature. In order to use it, the `PodSpec` must set the `ShareBurstableLimits` to true. When this is done, the pod level cgroup is set to the sum of all the container limits which were actually defined. Pods can then:
1. Define specific limits for those containers that really need them
1. Limit the overall pod resource limits for those containers that don't define explicit limits.

**Which issue(s) this PR fixes**:

Fixes #84340 , #87365, #60834

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
Yes.

```release-note
Allow Pod in the `Burstable` QoS class to define resource limits on the pod level, which are shared by multiple containers in the pod.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[KEP]: https://github.com/liorokman/enhancements/blob/f33d45643fe50649852e6f15ce1c1f44fa250c76/keps/sig-node/20200303-shared-pod-limits.md
```

### CODE REVIEW

**Comment by liorokman** [comment]
This PR replaces #88722. (I made the mistake of merging instead of rebasing)

**Comment by dashpole** [comment]
You should open the KEP as a PR to kubernetes/enhancements first so we can discuss.  I would also highly recommend putting this on the agenda for the weekly sig-node meeting.

/hold

**Comment by liorokman** [comment]
> You should open the KEP as a PR to kubernetes/enhancements first so we can discuss. 

Here's the PR: https://github.com/kubernetes/enhancements/pull/1592 

> I would also highly recommend putting this on the agenda for the weekly sig-node meeting.

How do I do this?

**Comment by JiaminZhu** [comment]
This is a very useful feature, looking forward to see this feature get released!

**Pull request closed without merging**
