### PR TITLE
add client-go watch example

### PR DESCRIPTION
**Pull request by xichengliudui**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

help users better use client-go

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/triage accepted

It's in my queue.

**Comment by caesarxuchao** [comment]
Hi @xichengliudui,

Thanks for the PR. Have you checked the existing workqueue [example](https://github.com/kubernetes/client-go/blob/master/examples/workqueue/main.go)? It covers the basic informer usage as well.

**Comment by xichengliudui** [comment]
I didn't see it, so I submitted the PR and I will close it
/close

**Pull request closed without merging**
