### PR TITLE
Remove unused api-rate and api-burst params.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Remove unused api-rate and api-burst params.

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @kubernetes/goog-csi

**Comment by zmerlynn** [comment]
Apologies for delay, @k8s-merge-robot doesn't respect vacation calendars. Reassigning to @wojtek-t so I can get out of email debt.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@aveshagarwal thanks for the cleanup

**Pull request merged**
