### PR TITLE
Private mount propagation

### LINKED ISSUE #62397: MountPropagation breaks Kubernetes on macOS
/kind bug

There is no way you can run the mount --make-rshared / in Docker VM and the shared folders use fuse.osxfs and are dynamically mounted into containers.

Adventurous macOS users must run Kubernetes with `MountPropagation=false` flag. This is OK for now, but the flag will be removed when the feature reaches GA.

There are few options we can do:

* Detect `darwin` in kubelet and turn off the feature silently, even after removal of MountPropagation feature.
* Rework the feature to default to `private` mount propagation, either everywhere or on `darwin`. All pods would run until user runs a pod with explicitly enabled slave or shared mount propagation and he/she would get clear error in this case.

/sig storage
/sig node

### PR DESCRIPTION
**Pull request by jsafrane**
This PR changes the default mount propagation from "rslave" (newly added in 1.10) to "private" (default in 1.9 and before). "rslave" as default causes regressions, see below.

Value `"None"` has to be added to `MountPropagationMode` enum in API ("I don't want any propagation at all"), which translates to "private" on Linux. [We did not have use cases for it](https://github.com/kubernetes/community/pull/659#discussion_r131454319), but we have them now.

**Which issue(s) this PR fixes**
Fixes #62397, fixes #62396

**Special notes for your reviewer**:
CRI already has an option for private mount propagation in volumes, however it's called "PRIVATE", while Kubernetes API value is "None". I did not change PRIVATE to NONE to keep the interface stable. See `kubelet_pods.go`.

**Release note**:
```release-note
Default mount propagation has changed from "HostToContainer" ("rslave" in Linux terminology) to "None" ("private") to match the behavior in 1.9 and earlier releases. "HostToContainer" as a default caused regressions in some pods.
```

/sig storage
/sig node

### CODE REVIEW

**Comment by jsafrane** [comment]
@thockin, please look at the API.

@tallclair, can I ask you to look at kubelet changes? Thanks! FYI, the ultimate plan is to cherry-pick it to 1.10.x, i.e. we're changing the default behavior in patch release. I consider it to be a bugfix.

**Comment by saad-ali** [comment]
/lgtm
/approve

For API review:
/assign @thockin

**Comment by saad-ali** [comment]
@thockin is on vacation. Can we get @smarterclayton to review/approve API changes?

**Comment by jsafrane** [comment]
@liggitt, as @thockin is on PTO these days, would you mind approving the API change and validation?

**Comment by liggitt** [comment]
@kubernetes/sig-storage-api-reviews

**Comment by liggitt** [comment]
IIUC, this API field was added in 1.10, and this is adding an additional allowed value that matches the default behavior in 1.9, and making it the default when the field is unspecified?

do you plan to pick this to 1.10.x as well?

**Comment by jsafrane** [comment]
> IIUC, this API field was added in 1.10, and this is adding an additional allowed value that matches the default behavior in 1.9, and making it the default when the field is unspecified?

Yes

> do you plan to pick this to 1.10.x as well?

Yes! That's the goal.

**Review by derekwaynecarr — APPROVED** [review]
/approve

**Pull request merged**
