### PR TITLE
Remove etcd-empty-dir-cleanup image

### PR DESCRIPTION
**Pull request by wojtek-t**
With etcd v2 no longer being supported for quite some time already, we can safely remove it now.

```release-note
NONE
```

### CODE REVIEW

**Comment by jpbetz** [comment]
Thanks for removing!

/lgtm

**Comment by jpbetz** [comment]
Looks like there is a reference to the Makefile from somewhere:

```
2020/06/04 07:21:04 error opening file cluster/images/etcd-empty-dir-cleanup/Makefile : open cluster/images/etcd-empty-dir-cleanup/Makefile: no such file or directory
```

**Review by justaugustus — CHANGES_REQUESTED** [review]
> Looks like there is a reference to the Makefile from somewhere:
> 
> ```
> 2020/06/04 07:21:04 error opening file cluster/images/etcd-empty-dir-cleanup/Makefile : open cluster/images/etcd-empty-dir-cleanup/Makefile: no such file or directory
> ```

That error is coming from https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml.

You'll need to:
- cleanup the various files that reference the `etcd-empty-dir-cleanup` image, before:
- removing entries in `build/dependencies.yaml`

EDIT: you can test with:
```shell
./hack/verify-external-dependencies-version.sh
```

/hold

**Comment by wojtek-t** [comment]
Done; PTAL

**Comment by justaugustus** [comment]
Nice cleanup!
/lgtm
/approve
/hold cancel

**Pull request merged**
