### PR TITLE
Exclude terminal pods from Daemonset e2e tests

### LINKED ISSUE #118928: [Flaky test] Conformance - GCE - master - kubetest2
### Which jobs are failing?

master-blocking
- Conformance - GCE - master - kubetest2

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance] [Changes](https://github.com/kubernetes/kubernetes/compare/3c380199e...470889278?)
- ci-kubernetes-gce-conformance-latest-kubetest2.Overall [Changes](https://github.com/kubernetes/kubernetes/compare/3c380199e...470889278?)
- kubetest2.Test [Changes](https://github.com/kubernetes/kubernetes/compare/3c380199e...470889278?)

Screenshot from 2023-06-28 15-01-46

### Since when has it been failing?

2023-06-27 16:43 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

### Reason for failure (if possible)

Kubernetes e2e suite: [It] [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance] 
```
{ failed [FAILED] unexpected pod daemon-set-lmdd2 be restarted In [It] at: test/e2e/apps/daemon_set.go:500 @ 06/28/23 07:35:29.181 }
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig cloud-provider
/sig apps
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

Terminal pods will not be restarted, so they can be excluded from calculations.
Starting from k8s 1.27, kubelet transitions every pod to a terminal phase (Failed, Succeeded) before deleting it from the store.

#### Which issue(s) this PR fixes:

Fixes #118928

#### Special notes for your reviewer:

This is a follow up to #118716

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce-serial
/assign @soltysh 

This job should exercise the test IIRC

**Comment by aojea** [comment]
> /test pull-kubernetes-e2e-gce-serial

are we good to go @alculquicondor ?

**Comment by alculquicondor** [comment]
yes
/assign @smarterclayton

**Comment by alculquicondor** [comment]
Agreed :)

**Comment by alculquicondor** [comment]
No test has run with the change yet

**Pull request merged**
