### PR TITLE
Automated cherry pick of #23746 upstream release 1.2

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Ref #23746 

/cc @kubernetes/sig-node

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @bgrant0607 this is the one I mentioned in today's tactics meeting for 1.2.2 release.

**Comment by dchen1107** [comment]
LGTM

**Comment by bgrant0607** [comment]
e2e failed, though I can't see the reason

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/23321

**Pull request merged**
