### PR TITLE
Replace pkg/util/file with k8s.io/utils/path

### PR DESCRIPTION
**Pull request by andrewsykim**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes internal dependencies to pkg/util/file. Follow up from https://github.com/kubernetes/utils/pull/51. 

**Which issue(s) this PR fixes**:
Part of https://github.com/kubernetes/kubernetes/issues/69585

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mcrute** [comment]
This lgtm. There is [this reference](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_helper.go#L91-L104) but it looks like the implementation is a little different so maybe a patch for the future.

/lgtm

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
