### PR TITLE
Automated cherry pick of #67169: Fix Proto Generator to not assign types to packages they don't belong to

### PR DESCRIPTION
**Pull request by sttts**
This produces correct protobuf dependencies. Without, everybody basing custom types onto k8s.io/api and who uses protobuf, will run into arbitrary dependencies on apiextensions-apiserver and others.

```release-note
Fix protobuf dependencies in k8s.io/api.
```

### CODE REVIEW

**Comment by sttts** [comment]
@smarterclayton this needs your top-level approval. The issue breaks us in github.com/openshift/api.

**Comment by mfojtik** [comment]
LGTM

**Comment by sttts** [comment]
/assign @calebamiles

This is critical for external consumers of k8s.io/api.

**Comment by sttts** [comment]
@calebamiles lgtm'ed and approve. Can we get this into the next minor release?

**Comment by sttts** [comment]
/assign @krzyzacy 

@calebamiles gently ping

**Comment by krzyzacy** [comment]
/unassign
/unassign @calebamiles 
/assign @foxish 
assign to patch release manager instead since me/Caleb doesn't manage release branches after the 1.0 release.

**Pull request merged**
