### PR TITLE
Update document of security context

### PR DESCRIPTION
**Pull request by janetkuo**
@bgrant0607 @caesarxuchao @krousey @nikhiljindal

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@nikhiljindal ok to merge?

**Comment by nikhiljindal** [comment]
Isnt LGTM enough for docs only changes?
Or do I need to add the ok-to-merge label?

**Pull request merged**
