### PR TITLE
Moved node/testutil to upper dir.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
Moved node/testutil to upper directory (`pkg/controller`); it's used by several controllers, and we need to test some helper func in `pkg/controller`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: part of #49522

**Release note**:

```release-note
N/A
```

### CODE REVIEW

**Comment by gmarek** [comment]
@k82cn - please fix golint.

**Comment by gmarek** [comment]
@k82cn - golint still fails

**Comment by k82cn** [comment]
ops, failed again :(. I will check the detail when proxy is up (golint is ok in my laptop.).

**Comment by gmarek** [comment]
That's exactly the problem:
```
[0;31mFAILED[0m   hack/make-rules/../../hack/verify-golint.sh	61s
I0807 11:44:52.007] Verifying hack/make-rules/../../hack/verify-govet.sh
W0807 11:44:52.108] Some packages in hack/.golint_failures do not exist anymore. Please remove them.
W0807 11:44:52.108] 
W0807 11:44:52.108]   pkg/controller/node/testutil
```
:)

**Comment by k82cn** [comment]
aha, green now !

**Pull request merged**
