### PR TITLE
Add a timeout to allow replacement pod to become ready

### LINKED ISSUE #37259: [k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should recreate pods scheduled on the unreachable node AND allow scheduling of pods on a node after it rejoins the cluster {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-serial/65/

Failed: [k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should recreate pods scheduled on the unreachable node AND allow scheduling of pods on a node after it rejoins the cluster {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:314
Nov 21 17:31:17.321: Node gke-bootstrap-e2e-default-pool-38dac485-wru5 did not become ready within 2m0s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:291
```

### PR DESCRIPTION
**Pull request by foxish**
Hopefully fixes https://github.com/kubernetes/kubernetes/issues/37259

```
I0314 04:26:02.562] Mar 14 04:26:02.562: INFO: Pod my-hostname-net-1bgrj still exists
I0314 04:26:22.491] Mar 14 04:26:22.491: INFO: Waiting for pod my-hostname-net-1bgrj to disappear
I0314 04:26:22.496] Mar 14 04:26:22.495: INFO: Pod my-hostname-net-1bgrj no longer exists
I0314 04:26:22.496] STEP: verifying whether the pod from the unreachable node is recreated
I0314 04:26:22.498] Mar 14 04:26:22.498: INFO: Pod name my-hostname-net: Found 3 pods out of 3
I0314 04:26:22.499] STEP: ensuring each pod is running
I0314 04:26:22.499] STEP: trying to dial each unique pod
I0314 04:26:22.579] Mar 14 04:26:22.579: INFO: Controller my-hostname-net: Got expected result from replica 1 [my-hostname-net-5jrdb]: "my-hostname-net-5jrdb", 1 of 3 required successes so far
I0314 04:26:22.642] Mar 14 04:26:22.642: INFO: Controller my-hostname-net: Got expected result from replica 2 [my-hostname-net-mjf3c]: "my-hostname-net-mjf3c", 2 of 3 required successes so far
I0314 04:31:22.645] Mar 14 04:31:22.644: INFO: Controller my-hostname-net: Failed to Get from replica 3 [my-hostname-net-rf46s]: Get https://35.184.87.178/api/v1/namespaces/e2e-tests-network-partition-s5gqt/pods/my-hostname-net-rf46s/proxy/: context deadline exceeded
```

The issue appears to be that we have a race between the pod being "running + ready" and being accessible via the APIServer proxy.

cc @kow3ns @bowei @davidopp

### CODE REVIEW

**Comment by bowei** [comment]
where does the 1 minute come from :-)

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (165/150 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:46110)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1cnrai-0003ql-Ch
	for dev@imwiz.com; Tue, 14 Mar 2017 12:54:46 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xKdojmPm9HF4SQR85hvOuRp1lnU=; b=DzzidikdrGp454Ev
	Nniktj3OlZvooS3SIlbq7TTRekgbbLgCtZv7Y0vcd8qDsBDFjgMl1TsiWdMytaca
	qt5AOfTgdulMRUPaROb/sJliuKoy8XyetaJwV5BSi7/7h2otE/E0BNDJ8SfjJYlW
	cmR5/NCWc715gPszdkigKAzN9Bo=
Received: by filter0556p1mdw1.sendgrid.net with SMTP id filter0556p1mdw1-18343-58C83C0F-6B
        2017-03-14 18:53:03.85947795 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id pOkxO79nSr2wQNikxOjFTQ
	for <dev@imwiz.com>; Tue, 14 Mar 2017 18:53:03.562 +0000 (UTC)
Date: Tue, 14 Mar 2017 11:53:03 -0700

**Comment by foxish** [comment]
Purely arbitrary because I have no way of knowing how long after the pod becomes "ready", it is accessible via the apiserver proxy. 1 minute looks like a reasonable amount of time, or the apiserver-proxy has issues. The other way around this may be just retrying on failure and giving up after N attempts.

**Comment by foxish** [comment]
@bowei I'm not sure that this fixes the issue, but it seems worth a shot. If it does work, I can modify the fix to use a retry loop at a later stage.

**Comment by bowei** [comment]
I don't know how time constrained you are on this, but I prefer a minimal retry loop there at least with logging so we make forward progress towards figuring out what the issue is...

**Review by bowei — APPROVED** [review]

**Comment by bowei** [comment]
@kubernetes/release-team -- added debug logging for flake

**Pull request merged**
