### PR TITLE
Allow kubectl set image/env on a cronjob

### PR DESCRIPTION
**Pull request by soltysh**
@kubernetes/sig-cli-pr-reviews  ptal

**Release note**:
```release-note
Allow kubectl set image|env on a cronjob
```

### CODE REVIEW

**Comment by Hashfyre** [comment]
Hi, can anyone confirm if this fix is in `v1.9.x`

**Comment by soltysh** [comment]
@Hashfyre no, it's not.

**Comment by base698** [comment]
Nooooooo.

**Comment by sonu27** [comment]
What version on k8s is this on?

I'm still getting an error on 1.10

**Comment by sonu27** [comment]
It's in v1.10, you can manually get kubectl here https://storage.googleapis.com/kubernetes-release/release/v1.10.4/bin/darwin/amd64/kubectl

Hopefully the update cloud sdk soon

**Pull request merged**
