### PR TITLE
[WIP] Fix the util package contains too much codes

### PR DESCRIPTION
**Pull request by resouer**
Ref #15634

Leave `resource_container_linux` to next PR since this one already has too much refactoring.

kindly ping @thockin  for review

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/19283)

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot test this please

**Comment by lavalamp** [comment]
I started looking at this, but it's really big. I think it would be a lot easier to review if you made a separate PR for each new sub-package you want to make. Thank you for cleaning this up!

**Comment by resouer** [comment]
@lavalamp I agree with you, I did not expect it grows to such a big PR (especially due to some generated code and docs), so I will split it into some small PR according to my commits.

**Comment by davidopp** [comment]
ping @resouer Are you still working on this? If not, please close.

**Comment by resouer** [comment]
@davidopp Yeah, I'm continue working on this, but I have split this into small PRs, will close this one, sorry for noise.

**Pull request closed without merging**
