### PR TITLE
Limit iops per container

### LINKED ISSUE #70364: Limiting blkio with cgroups by annotation
**What would you like to be added**:
We hope that kubernetes support limiting blkio resources.
We use the annotation of kubernetes to pass the parameters of the cgroup to control the container blkio. The current features apply only to the Linux devmapper environment.

**Why is this needed**:
In my production environment, multi-tenancy shares a storage device, we must isolate the io of each tenant to ensure that the tenants do not interfere with each other. CRI does not provide an interface for IO resource isolation.

/kind feature
/sig node

### PR DESCRIPTION
**Pull request by Avanpourm**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
I need to limit the read and write iops of rootfs
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70364

**Special notes for your reviewer**:
Thankyou !!！

**Does this PR introduce a user-facing change?**:

```release-note
Use the annotation of kubernetes to pass the parameters of the cgroup to control the container blkio
Specifying the device path as "rootfs" indicates that you specify limiting rootfs
For example:
io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sda1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}]"device_write_iops":[{"device":"rootfs","value":"300"}]}'

```
### Parameter
| parameter | type | default value | means | parameter range | example | corresponds to Cgoup |
| --- | --- | --- | --- | --- | --- | --- |
| weight | Uint16 | 0 | Weight value for all devices | 10-1000 | 1 |   |
| weight_device | Array | nil | Weight value for all devices | - |  |  |
| weight_device.[*].device | String |  | The absolute path of the device |  | /dev/sda1 |  |
| weight_device.[*].value | String |  | Weight value of the device|10-1000  |  |  |
| device_read_bps | Array | nil | A device reads the maximum number of bytes per second |  |  |  |
| device_read_bps.[*].device | String |  | The absolute path of the device. You can use "rootfs" for the specified root directory|  |  |  |
| device_read_bps.[*].value | String |  |Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state | >1k | 1M |  |
| device_write_bps | Array | nil | Maximum number of bytes per second allowed to write to the device |  |  |  |
| device_write_bps.[*].device | String |  | The absolute path of the device. You can use "rootfs" for the specified root directory |  |  |  |
| device_write_bps.[*].value | String |  |Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state | >1k |  |  |
| device_read_iops | Array | nil | Max IOPS |  |  |  |
| device_read_iops.[*].device | String |  | The absolute path of the device. You can use "rootfs" for the specified root directory |  |  |  |
| device_read_iops.[*].value | String |  | Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state | >5 |  |  |
| device_write_iops | Array | nil | Max IOPS |  |  |  |
| device_write_iops.[*].device | String |  | The absolute path of the device. You can use "rootfs" for the specified root directory|  |  |  |
| device_write_iops.[*].value | String |  | Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state | >5 |  | |

### Deployment Example

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iops-app
  name: iops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iops-app
  template:
    metadata:
      labels:
        app: iops-app
      annotations:
        io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sad1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}],"device_write_iops":[{"device":"rootfs","value":"300"}]}'
    spec:
      nodeSelector:
        kubernetes.io/hostname: szdc-k8sm-2-2.meitu-inc.com
      containers:
      - image: docker.io/centos:7
        command: ["/bin/sh","-c"]
        args: ["while(true);do /bin/sleep 10;done"]
        name: iops-app
        resources:
          requests:
            memory: "200Mi"
            cpu: 1
          limits:
            memory: "200Mi"
            cpu: 1
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
```

### CODE REVIEW

**Comment by wenjun93** [comment]
If blkio limit is set at container level, for general purpose, should this change go through CRI instead?

**Comment by Avanpourm** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        CRI's design may consider adding IO limit support, but it requires an abstraction of the interface, not just a simple implementation of docker's blkio limit. Most of the time we don't know the device of the physical machine, but we need to limit IO to the container, such as rootfs,emptyDir, and so on.
            
        
    
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zmpbbg
                            
                    
                        
                            
                                    zmpbbg@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/21/2018 15:22，wenjun<notifications@github.com> wrote： 


If blkio limit is set at container level, for general purpose, should this change go through CRI instead?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lovejoy** [comment]
@Avanpourm Would you please request this pr to master branch ？

**Comment by Avanpourm** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    yea
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zmpbbg
                            
                    
                        
                            
                                    zmpbbg@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 12/11/2018 17:18，lovejoy<notifications@github.com> wrote： 


@Avanpourm Would you please request this pr to master branch ？



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by feiskyer** [comment]
@Avanpourm  Thanks for contributing. For new features, please send PRs to master branch instead.

**Comment by feiskyer** [comment]
Please create a new PR targeted at master branch. stable branches are only for bug fixes, not for new features.

/close

**Comment by cuericlee** [comment]
@Avanpourm did you get chance to request to merge this PR to master branch?

**Pull request closed without merging**
