### PR TITLE
Switch cronjob controller to batch/v1

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This promotes `CronJob` controller to use `batch/v1` based on https://github.com/kubernetes/enhancements/issues/19 and complete description from https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable 

#### Special notes for your reviewer:
This builds on top of https://github.com/kubernetes/kubernetes/pull/98965 so only the last commit matters. 

/assign @deads2k @liggitt 

#### Does this PR introduce a user-facing change?
```release-note
Promote CronJobs to batch/v1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable 
```

### CODE REVIEW

**Review by alaypatel07 — APPROVED** [review]
+1, lgtm

**Comment by liggitt** [comment]
lgtm as well

**Comment by liggitt** [comment]
* API review done in https://github.com/kubernetes/kubernetes/pull/98965
* Controller review in https://github.com/kubernetes/kubernetes/pull/99423 (this PR)
* e2e switch to v1 in https://github.com/kubernetes/kubernetes/pull/99197

/lgtm
/approve

Split https://github.com/kubernetes/kubernetes/pull/99197 into two PRs:
* one that switches the e2e to use v1
* one that promotes the test to conformance

Once this merges, we'll merge the "switch e2e to v1" PR and let the "promote to conformance" PR soak for two weeks before merging

**Pull request merged**
