### PR TITLE
Sort slices before comparing in deployment util test

### LINKED ISSUE #42021: flake: deployment_util_test.go TestFindOldReplicaSets failure
`/pkg/controller/deployment/util:go_default_test`

```
--- FAIL: TestFindOldReplicaSets (0.00s)
	deployment_util_test.go:605: In test case "Get old ReplicaSets with two new ReplicaSets, only the oldest new ReplicaSet is seen as new ReplicaSet", expected []*v1beta1.ReplicaSet{(*v1beta1.ReplicaSet)(0xc420204a80), (*v1beta1.ReplicaSet)(0xc420204380)}, got []*v1beta1.ReplicaSet{(*v1beta1.ReplicaSet)(0xc420204380), (*v1beta1.ReplicaSet)(0xc420204a80)}: <nil>
FAIL
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42009/pull-kubernetes-bazel/7072/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42010/pull-kubernetes-bazel/7035/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38676/pull-kubernetes-bazel/7030/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41351/pull-kubernetes-bazel/7004/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38924/pull-kubernetes-bazel/6988/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41234/pull-kubernetes-bazel/6982/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38676/pull-kubernetes-bazel/6962/

### PR DESCRIPTION
**Pull request by janetkuo**
Follow up #41851, should sort the slice before comparing them 

Fixes #42021

@kargakis @mwielgus

### CODE REVIEW

**Review by 0xmichalis — COMMENTED** [review]
/lgtm

**Comment by kargakis** [comment]
@janetkuo you need to update bazel

**Comment by janetkuo** [comment]
Updating bazel, reapplying tag

**Comment by janetkuo** [comment]
"Jenkins overloaded. Please try again later." - reopen PR to try again

**Comment by janetkuo** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
All checks have passed

```
15 successful checks
```

Manually merging to fix flaky test.

**Pull request merged**
