### PR TITLE
Drop unused golang/template package and funcs

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Drops unused package and unused funcs

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/milestone v1.25

### CODE REVIEW

**Comment by liggitt** [comment]
cc @MushuEE

**Comment by MushuEE** [comment]
/lgtm

The place it is used is `client-go` [here](https://github.com/kubernetes/client-go/blob/master/util/jsonpath/jsonpath.go#L544-L556)

**Pull request merged**
