### PR TITLE
Bump cAdvisor to v0.49.0

### PR DESCRIPTION
**Pull request by bobbypage**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Bump to the latest cAdvisor release v0.49.

Changelog - https://github.com/google/cadvisor/compare/v0.48.1...v0.49.0
Release notes - https://github.com/google/cadvisor/releases/tag/v0.49.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Bump cAdvisor to v0.49.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
cc @dims @kannon92 @mrunalp

**Comment by pacoxu** [comment]
/hold
for https://github.com/kubernetes/kubernetes/pull/123603

**Pull request merged**
