### PR TITLE
[WIP] use our forked version of docker/distribution repository

### PR DESCRIPTION
**Pull request by dims**
Just testing an idea/experiment - please see https://github.com/kubernetes/k8s.io/issues/3307

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
do we need to use this cross-repo? or else we can use an actual `internal/third_party/` path?

**Comment by thockin** [comment]
Ben's comment is interesting.  While we are playing with repo paths and orgs, we can do anything we like.  We could make an omnibus internal/third_party repo, or we could make a k8s-internal-3rd-party or and use many repos under there....

**Comment by dims** [comment]
@BenTheElder one of my concerns is how do we preserve history when we do this?

**Comment by BenTheElder** [comment]
@dims I think one easy option is just to include "added from upstream $commit" in the commit message, and to track back from there you have to switch repos (kubernetes has done this sort of thing to ourselves before as I recall...)

**Comment by dims** [comment]
@BenTheElder yes that's definitely a good choice

**Comment by dims** [comment]
we'll need to find another way. closing this for now.

**Pull request closed without merging**
