### PR TITLE
Updating swagger datafile as per latest swagger-ui code

### PR DESCRIPTION
**Pull request by nikhiljindal**
PR generated by running hack/build-ui.sh

Deletes about 30k lines.
Original number of lines: 48528
New number of lines:      17139

Should help with https://github.com/GoogleCloudPlatform/kubernetes/issues/11852

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Great!

Did you look at the test failures?

**Comment by nikhiljindal** [comment]
The test failures are unrelated.

We do not have any test for swagger-ui

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by krousey** [comment]
How am I supposed to review this? It's automatically generated and huge right?

**Comment by nikhiljindal** [comment]
Yes its autogenerated

**Comment by krousey** [comment]
@nikhiljindal You need to rebase to pick up the new Shippable configuration. It should run fine then.

**Comment by nikhiljindal** [comment]
Rebased

**Comment by krousey** [comment]
So um... I guess this is LGTM so long as tests pass...

**Pull request merged**
