### PR TITLE
Change DeepEqual to use Equal in time_test.go

### PR DESCRIPTION
**Pull request by jian-he**
**What this PR does / why we need it**:
This PR changes reflect.DeepEqual to use Equal because reflection is not required in this case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jian-he** [comment]
@k8s-bot I signed!

**Comment by jian-he** [comment]
CLA signed.

**Comment by jian-he** [comment]
CLA signed.

**Comment by liggitt** [comment]
is there a problem with the test as it is? I have a slight preference for keeping it using DeepEqual just because it is easy to understand and consistent with other tests

**Pull request closed without merging**
