### PR TITLE
remove some unused functions in validation.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
remove some unused functions in validation.go
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
/assign @deads2k @sttts
cc @hzxuzhonghu

**Comment by deads2k** [comment]
/lgtm

Want to chase the usage of other functions that are nothing but pass through calls?

**Comment by hanxiaoshuai** [comment]
@deads2k  Just get rid of some useless functions.

**Comment by sttts** [comment]
/assign @smarterclayton 

for approval.

**Pull request merged**
