### PR TITLE
Replace Mutex with RWMutex increase read efficiency of package `pkg/controller`

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

Replace Mutex with RWMutex increase read efficiency of package `pkg/controller`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
/cc @janetkuo @bowei @jsafrane

PTAL

**Comment by thockin** [comment]
Do you have a benchmark or something that shows this a) to be true and b) to matter?

**Comment by wgliang** [comment]
@thockin 
What do you want to test, Mutex vs RWMutex? 
(Mainly because RWMutex has better read performance than Mutex)

**Comment by thockin** [comment]
Yet we don't generally replace all mutexes with RW mutextes because they are more complicated to reason about.  Can you show me a test or even a benchmark that this change matters?  What *actual* problem does it solve?

**Comment by thockin** [comment]
If you can show a reason why we should do this, please reopen.

**Pull request closed without merging**
