### PR TITLE
Switch to pause 3.7 for Kubernetes 1.24

### PR DESCRIPTION
**Pull request by dims**
We merged a change https://github.com/kubernetes/kubernetes/pull/107056 to drop some unsupported Windows SAC images from pause. So let's make sure we test this new version and ship it with 1.24

Looks like someone forgot to switch the image from 3.6->3.7 afrer the #107056 landed

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
missed a step! - https://github.com/kubernetes/k8s.io/pull/3564

**Comment by dims** [comment]
Asked the sig-windows folks to validate the image - https://kubernetes.slack.com/archives/C0SJ4AFB7/p1648586350126609

**Comment by ehashman** [comment]
That's a weird test failure:

```
Kubernetes e2e suite: [sig-api-machinery] ServerSideApply should work for subresources
{ Failure test/e2e/apimachinery/apply.go:165 Mar 29 21:44:42.854: Failed to Apply Status using Apply patch: failed to create manager for existing fields: failed to convert new object (apply-93/test-pod; /v1, Kind=Pod) to smd typed: .status.hostIPs: element 0: associative list without keys has an element that's a map type vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113}
```

**Review by ehashman — COMMENTED** [review]
/triage accepted
/lgtm

**Pull request merged**
