### PR TITLE
Remove empty dirs in aws directories Godeps workspace

### PR DESCRIPTION
**Pull request by colemickens**
Fixes: #19808

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@pmorie Can you take a look when you have a moment.  You seem to have context on #19808 that this fixes.

**Comment by pmorie** [comment]
@colemickens I apologize, I've been out for much of the last week prepping for / recovering from a minor surgery.  This LGTM, but it looks like the verify scripts fail -- suggest you run hack/verify-all.sh locally.

**Comment by colemickens** [comment]
@pmorie Yeah, I noticed the godep verification failed. I didn't really understand how my changes led to the diff that it reported. I'll restart and try again and see if I'm more successful.

**Comment by pmorie** [comment]
@colemickens is this still active?

**Comment by colemickens** [comment]
I'm not sure if it's needed any more. I've not been using the local-up script but I've been able to build successfully without this or any other patches.

**Comment by pmorie** [comment]
@colemickens Okay, I'll close this out.

**Pull request closed without merging**
