### PR TITLE
Fix infinte loop in federated ingress controller

### PR DESCRIPTION
**Pull request by mwielgus**
Previously ingress controller was constantly scheduling reconcilation, even if no updates were needed. That behavior creates a big mess in the logs and consumes resources. 

This pr also fixes the stop function for federated ingress controller.

cc: @nikhiljindal @madhusudancs

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37572)

### CODE REVIEW

**Comment by madhusudancs** [comment]
LGTM! Please feel free to apply the label once @saad-ali approves this PR.

@saad-ali this is a bug fix specific to federation and the risk of destabilizing things outside federation is close to zero. Also the bug this PR is fixing in is an alpha feature in federation.

**Comment by mwielgus** [comment]
@k8s-bot gci gke e2e test this

**Comment by mwielgus** [comment]
@k8s-bot cvm gke e2e test this

**Comment by mwielgus** [comment]
@k8s-bot  e2e test this

**Comment by mwielgus** [comment]
@k8s-bot gce e2e test this

**Comment by mwielgus** [comment]
@k8s-bot gce e2e test this

**Comment by mwielgus** [comment]
Adding lgtm, this will have to be cherry-picked to the 1.5 branch.

**Comment by eparis** [comment]
removing priority label. this is an alpha feature and a normal 1.5 bug fix. It should not skip ahead of all other 1.5 PRs. (it will skip 1.6 PRs based on the milestone)

**Comment by rmmh** [comment]
@k8s-bot kubemark test this

**Comment by saad-ali** [comment]
> @saad-ali this is a bug fix specific to federation and the risk of destabilizing things outside federation is close to zero. Also the bug this PR is fixing in is an alpha feature in federation.

Ack. Thanks!

**Pull request merged**
