### PR TITLE
cluster/*: Renaming coreos to container-linux in necessary places.

### PR DESCRIPTION
**Pull request by yifan-gu**
Renaming CoreOS to Container Linux as the later becomes the official name for the Linux distro.

cc @philips @euank @mikedanese @roberthbailey

### CODE REVIEW

**Comment by euank** [comment]
I would prefer to merge #33965 first for the simple reason that it deletes a couple of these occurrences and is the more complex change to rebase I believe.

**Comment by philips** [comment]
+1 to merging #33965 first

**Comment by MHBauer** [comment]
Is [this](https://coreos.com/blog/tectonic-self-driving.html) the announcement?

**Comment by philips** [comment]
@MHBauer yes, you can see the new logo and name used in the docs now: https://coreos.com/os/docs/latest/

**Comment by roberthbailey** [comment]
This needs a release note - can you use the template in the first PR entry?

**Comment by philips** [comment]
lets please close this and focus on https://github.com/kubernetes/kubernetes/pull/33965 instead.

**Comment by philips** [comment]
@yifan-gu we can now do this now that #33965 has been merged. Can you try again?

**Comment by yifan-gu** [comment]
@philips Looks like https://github.com/kubernetes/kubernetes/pull/35249 is still on the fly.
@euank Do we want to rename before or after that PR?

**Comment by euank** [comment]
@yifan-gu before, that one still has a few more iterations before it's ready for review, and I'll be fine for rebasing on it.

**Comment by yifan-gu** [comment]
@euank SGTM, I will update reopen a PR for this.

**Pull request closed without merging**
