### PR TITLE
hack/boilerplate/bolierplate.py: format python file according to PEP8…

### PR DESCRIPTION
**Pull request by keerthigd**
… guidelines

**What type of PR is this?**

> /kind cleanup
adde a few newlines between functions according to PEP8 guidelines: https://www.python.org/dev/peps/pep-0008/

**What this PR does / why we need it**:
This would help maintain the official formatting guidelines for python files.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
```

### CODE REVIEW

**Comment by keerthigd** [comment]
How do I add release note label?

**Comment by keerthigd** [comment]
cc: @nikhita

**Review by fejta — APPROVED** [review]

**Comment by nikhita** [comment]
@fejta we don't have the github approval == lgtm/approve turned on in k/k yet :)

/sig testing
/kind cleanup
/ok-to-test

**Pull request merged**
