### PR TITLE
azure disk: restrict length of name

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**:
Fixes dynamic disk provisioning on Azure by properly truncating the disk name to conform to the Azure API spec.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
n/a

**Special notes for your reviewer**:
n/a

**Release note**:
```release-note
azure disk: restrict name length for Azure specifications
```

cc: @rootfs

### CODE REVIEW

**Comment by rootfs** [comment]
LGTM

**Comment by brendandburns** [comment]
fwiw, we should consider adding an admission controller to test for this. If two names happen to truncate to the same first 75 letters it's going to give some pretty hard to track errors.

**Comment by colemickens** [comment]
(Not that I disagree, but I don't think this changes increases chances of collision though. The thing that winds up truncated here is the prefix, and it's the same for the entire cluster anyway.)

**Comment by colemickens** [comment]
@saad-ali Are you in charge of cherry-picks for 1.5.x? Can this be marked as a cherry-pick?

**Comment by codablock** [comment]
@colemickens Which behavior/bug does this PR fix? Complete failure to mount or something related to the time needed for attach/deatch? I'm asking because I may also want to cherry-pick this into my custom built branch for our deployments.

**Comment by colemickens** [comment]
@codablock Without this patch, if the clustername is too large, the PV created will have a Name that is longer than 79 character. The attach operation fails repeatedly in this case as the PUT is rejected.

**Comment by colemickens** [comment]
ping @saad-ali for a 1.5.x cherry-pick.

**Pull request merged**
