### PR TITLE
Move pkg/kubectl/metricsutil to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/metricsutil` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/metricsutil.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @nikhita 

for `staging/publishing`

**Comment by seans3** [comment]
/assign @BenTheElder 

for `hack/.golint_failures`

**Comment by dims** [comment]
/approve

(hack and publishing)

**Comment by seans3** [comment]
Thanks @dims 

:)

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
Needs another rebase :grimacing:

**Comment by nikhita** [comment]
/lgtm cancel

to stop retesting

**Comment by dims** [comment]
/lgtm

re-add lgtm from @BenTheElder

**Comment by BenTheElder** [comment]
needs rebase

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
