### PR TITLE
Juju: Disable anonymous auth on kubelet

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This disables anonymous authentication on kubelet when deployed via Juju.

I've also adjusted a few other TLS options for kubelet and kube-apiserver. The end result is that:
1. kube-apiserver can now authenticate with kubelet
2. kube-apiserver now verifies the integrity of kubelet

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/219

**Special notes for your reviewer**:

This is dependent on PR #41251, where the tactics changes are being merged in separately.

Some useful pages from the documentation:
* [apiserver -> kubelet](https://kubernetes.io/docs/admin/master-node-communication/#apiserver---kubelet)
* [Kubelet authentication/authorization](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/)

**Release note**:

```release-note
Juju: Disable anonymous auth on kubelet
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
@k8s-bot ok to test

**Comment by chuckbutler** [comment]
I ran some preliminary testing on this and encountered a weird race condition during the turnup.

```
Feb 22 21:36:08 juju-58c337-2 systemd[1]: Stopped Kubernetes API Server.
Feb 22 21:36:08 juju-58c337-2 systemd[1]: Starting Kubernetes API Server...
Feb 22 21:36:09 juju-58c337-2 kube-apiserver[13937]: F0222 21:36:09.187162   13937 universal_validation.go:84] Validate server run options failed: No --service-cluster-ip-range specified
Feb 22 21:36:09 juju-58c337-2 systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=255/n/a
Feb 22 21:36:09 juju-58c337-2 systemd[1]: Failed to start Kubernetes API Server.
```

it looks like start_master was invoked before the auth was setup with these refactors. Attached is the unit artifact from juju-crashdump.

[kubernetes-master_0.tar.zip](https://github.com/kubernetes/kubernetes/files/794974/kubernetes-master_0.tar.zip)

**Comment by Cynerva** [comment]
> it looks like start_master was invoked before the auth was setup with these refactors.

Thanks @chuckbutler. Looks like that's the case - it's a race condition I didn't hit, my bad!

I've amended this PR with a fix for that, by adding the `authentication.setup` state as a prereq to `start_master` [here](https://github.com/kubernetes/kubernetes/pull/41919/commits/d1e55e2fa3b954b86b1f7485e94858f56e525fa5#diff-e6f5b987d0e976d7b76acd341abc74c0R197).

**Comment by chuckbutler** [comment]
+1 confirmed this works as expected. 

Thanks for the quick turnaround on the fix @Cynerva   

/approve

**Comment by Cynerva** [comment]
Thanks @chuckbutler and @eparis!

Looks like the tests are the only thing left, so lemme try to get those running...

@k8s-bot node e2e test this
@k8s-bot non-cri node e2e test this
@k8s-bot non-cri e2e test this

**Comment by Cynerva** [comment]
Verification failed in hack/verify-flags-underscore.py due to a conflict with #41971 - a new flag was introduced, and an exception added for us, but this PR happens to change that line of code. Oops!

I've rebased to origin/master and updated the exceptions file accordingly.

**Comment by marcoceppi** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot cvm gce e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot non-cri e2e test this

**Comment by Cynerva** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by Cynerva** [comment]
Looks like the test reruns passed. @eparis could you give this another look and /lgtm? Thanks!

**Comment by calebamiles** [comment]
PR had `lgtm` before code freeze, added to 1.6 milestone.

**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

**Pull request merged**
