### PR TITLE
test/integration: rename package and files name from master to controlplane

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup
/wg naming
/area test

#### What this PR does / why we need it:

xref #94407

test/integration: rename package and files name from master to controlplane

#### Which issue(s) this PR fixes:

Part of #94900

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
ping @BenTheElder @timothysc
Please take a look, because it is close to the time point of code freeze.
https://github.com/kubernetes/kubernetes/issues/94900#issuecomment-794170474

**Comment by mengjiao-liu** [comment]
PTAL @neolit123  
Close to the point where the code freezes.

**Comment by BenTheElder** [comment]
> ping @BenTheElder @timothysc
> Please take a look, because it is close to the time point of code freeze.

Sorry but I was both unavailable (on holiday) with github status marked busy, and not assigned to this PR, so I've only just seen it.
In theory the robot should auto suggest an approver who is not marked unavailable.

**Pull request merged**
