### PR TITLE
clarify the description of the metric apiserver_storage_objects

### PR DESCRIPTION
**Pull request by machine424**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:
https://github.com/kubernetes/website/issues/43012

#### Does this PR introduce a user-facing change?
Doc at https://kubernetes.io/docs/reference/instrumentation/metrics/ will be updated

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by dgrisonnet — APPROVED** [review]
/lgtm

/assign @logicalhan

**Comment by dgrisonnet** [comment]
@machine424 could you please run `./hack/update-generated-stable-metrics` to update the description of the metric in the file used for static analysis?

**Comment by machine424** [comment]
Was waiting for some tests to fail :)
Done.

**Review by logicalhan — COMMENTED** [review]
Have you run the unit tests? I suspect they're going to fail due to the change in the HELP text.

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

I guess we don't test this metric in our unit tests.

**Comment by dgrisonnet** [comment]
@machine424 would you perhaps be interested in covering the unit test gap for this metric in a follow-up PR?

**Comment by dgrisonnet** [comment]
The stable metrics verification is just a static check. You can find the unit tests here: https://github.com/machine424/kubernetes/blob/084deb7a7cf147bbafd131ab1a36852a79f08a64/staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics_test.go

But as Han mentioned before, there are none for this metric yet.

**Comment by machine424** [comment]
Thanks, I’ll try to add them then.

**Comment by machine424** [comment]
Opened a PR here https://github.com/kubernetes/kubernetes/pull/120827

**Pull request merged**
