### PR TITLE
Bump runc to v1.1.9

### PR DESCRIPTION
**Pull request by dims**
Switching CI jobs to latest in 1.7.x series in https://github.com/kubernetes/test-infra/pull/30567

Given v1.1.9 is the preferred version of `runc` in this version of containerd https://github.com/containerd/containerd/blob/v1.7.5/script/setup/runc-version let's please switch to this version of runc.

for the record differences are as follows:
the https://github.com/opencontainers/runc/compare/v1.1.7...v1.1.9

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
I reviewed the commits list. Everything looks good

/lgtm
/approve

**Comment by BenTheElder** [comment]
xref: https://github.com/opencontainers/runc/releases

nothing jumps out, no new v1 controllers 🙃

**Pull request merged**
