### PR TITLE
Fix a typo and a misnamed field in CHANGELOG-1.26.md

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix two typos in CHANGELOG-1.26.md

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
/approve

**Comment by sftim** [comment]
/retitle Fix a typo and a misnamed field in CHANGELOG-1.26.md

**Pull request merged**
