### PR TITLE
Remove kubectl delete hack that handles DaemonSet deletion

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: follow up #64847

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**: 
/cc @liggitt @soltysh 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adohe** [comment]
@janetkuo overall lgtm. please help fix conflict issue

**Comment by jimangel** [comment]
@janetkuo does this PR need docs for the 1.12 release?

**Comment by janetkuo** [comment]
@jimangel no, this doesn't need docs.

**Pull request merged**
