### PR TITLE
Automated cherry pick of fix for #77733 (NodeLifecycleController is overloading kube-apiserver) into release-1.15

### PR DESCRIPTION
**Pull request by mborsz**
Cherry pick of #81416 #81839 #82489 #82884 #83248 #83320 #83780 #84445 #81167 on release-1.15.

#81416: removing redundant code
#81839: moving podInformer to node controller scope
#82489: adding lock to node data map
#82884: eviction processing refactor
#83248: adding fakeGetPodsAssignedToNode
#83320: adding pods to DeletePods parameters
#83780: using pod pointers in node lifecycle controller
#84445: MarkPodsNotReady retry fix
#81167: adding pods lister

While the number of PRs is quite high, most of them are quite trivial. (#81167 is the main one)

Context: This is a cherry pick of fixes for #77733 (many nodes becoming unhealthy can overload kube-apiserver making master unavailable).

The risk of not cherry picking is that if 5-50 nodes (actual number depends on number of pods in the system) will become unhealthy in the same time (e.g. network outage), this will overload kube-apiserver and etcd making all of the nodes unavailable. In my opinion this is a critical issue we should address also in the past releases.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix the problem where couple nodes becoming NotReady at the same time could cause master instability or even complete outage in large enough clusters.
```

/kind bug

### CODE REVIEW

**Comment by wojtek-t** [comment]
@kubernetes/patch-release-team - can you please take a look?

**Comment by mborsz** [comment]
pull-kubernetes-kubemark-e2e-gce-big is failing with
```
W0311 08:36:56.700] E0311 08:36:56.697732   83464 clusterloader.go:191]   Errors: [measurement call TestMetrics - TestMetrics error: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@:22: 'dial tcp :22: connect: connection refused'"}]
```

clusterloader is not able to determine master ip address (usually passed as MASTER_IP env or --master-ip flag) and is using empty string as a host to ssh which obviously fails.

I don't think this is caused by this PR. I will take a look what happened there.

**Comment by mborsz** [comment]
Since https://github.com/kubernetes/test-infra/pull/16452 we set MASTER_IP only if --deployment=gce but this flag is not set in our tests.

I'm not sure if this flag should bet set

**Comment by mborsz** [comment]
--deployment=gce flag was never set (in fact it's incorrect value of that flag).

So it looks like kubernetes/test-infra#16452 has a bug that prevents MASTER_IP from being set in gce kubemark.

**Comment by wojtek-t** [comment]
The new kubetest image should be released now.

/retest

**Pull request merged**
