### PR TITLE
Automated cherry pick of #107565: upgrade sigs.k8s.io/structured-merge-diff/v4 to v4.2.1

### PR DESCRIPTION
**Pull request by jiahuif**
Cherry pick of #107565 on release-1.23.

#107565: upgrade sigs.k8s.io/structured-merge-diff/v4 to v4.2.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

/kind feature
/sig api-machinery

```release-note
kube-apiserver: when merging lists, Server Side Apply now prefers the order of the submitted request instead of the existing persisted object
```

### CODE REVIEW

**Comment by jiahuif** [comment]
Could you take a look at the backports too?
/assign @apelisse @liggitt

**Comment by jiahuif** [comment]
We intend to backport the fix for #104641 to `1.23`, `1.22`, and `1.21`, omitting `1.20` to avoid breakage. Could you take a look?
cc @kubernetes/release-managers
cc @cpanato

**Comment by puerco** [comment]
Thank you @jiahuif 
/lgtm

**Pull request merged**
