### PR TITLE
fix backoff manager timer initialization race

### LINKED ISSUE #90287: regression: wait.Forever runs twice immediately since 1.18
I noticed that this code:

```
	go wait.UntilWithContext(ctx, func(ctx context.Context) {
		now := time.Now()
		refreshAfter := now.Add(-s.refreshInterval)
		var count int
		for _, obj := range s.store.List() {
			comments := obj.(*BugComments)
			if comments.RefreshTime.Before(refreshAfter) {
				s.queue.Add(comments.Name)
				count++
			}
		}
		klog.V(5).Infof("Refreshed %d comments older than %s", count, s.refreshInterval.String())
	}, s.refreshInterval/4)
```

was printing 

```
I0419 16:20:13.714551  976723 comments.go:122] Refreshed 0 comments older than 15m0s
I0419 16:20:13.714603  976723 comments.go:122] Refreshed 0 comments older than 15m0s
```

which should not happen.  Also occurs in wait.Forever.

I suspect that fc8a39d439ea08b006fb7ea1db1058175cc7adf5 in https://github.com/kubernetes/kubernetes/pull/87829 regressed this as that was the most recent major update and I only started seeing this on a recent apimachinery bump.

### PR DESCRIPTION
**Pull request by zhan849**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix backoff manager timer initialization so the operation don't run twice immediately
added real clock test to backoff manager

**Which issue(s) this PR fixes**:
Fixes #90287

```release-note
Fixed a 1.18 regression in wait.Forever that skips the backoff period on the first repeat
```

/sig api-machinery
/cc @liggitt @lavalamp @smarterclayton 
/assign @wojtek-t 
/priority important-soon

### CODE REVIEW

**Comment by liggitt** [comment]
/ok-to-test

Fix looks good to me. Did the tests fail reliably on master?

**Comment by zhan849** [comment]
fixed a gofmt issue. bazel build and ipv6 look like glitches

**Comment by liggitt** [comment]
@zhan849 please cherry-pick this to the release-1.18 branch using `hack/cherry_pick_pull.sh`

**Comment by zhan849** [comment]
done: https://github.com/kubernetes/kubernetes/pull/90495

```bash
$ bash hack/cherry_pick_pull.sh upstream/release-1.18 90476
+++ Updating remotes...
Fetching upstream
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 30 (delta 18), reused 21 (delta 15), pack-reused 1
Unpacking objects: 100% (30/30), done.
From https://github.com/kubernetes/kubernetes
   4efb43e1f57..7f744be14e2  master     -> upstream/master
Fetching origin
+++ Creating local branch automated-cherry-pick-of-#90476-upstream-release-1.18-1587859578
Updating files: 100% (3545/3545), done.
Branch 'automated-cherry-pick-of-#90476-upstream-release-1.18-1587859578' set up to track remote branch 'release-1.18' from 'upstream'.
Switched to a new branch 'automated-cherry-pick-of-#90476-upstream-release-1.18-1587859578'
+++ Downloading patch to /tmp/90476.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /tmp/90476.patch

Applying: fix backoff manager timer initialization race

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-#90476-upstream-release-1.18-1587859578:automated-cherry-pick-of-#90476-upstream-release-1.18

+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] y
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 12 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 1.50 KiB | 139.00 KiB/s, done.
Total 11 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8), completed with 8 local objects.
remote:
remote: Create a pull request for 'automated-cherry-pick-of-#90476-upstream-release-1.18' on GitHub by visiting:
remote:      https://github.com/zhan849/kubernetes/pull/new/automated-cherry-pick-of-%2390476-upstream-release-1.18
remote:
To https://github.com/zhan849/kubernetes.git
 * [new branch]              automated-cherry-pick-of-#90476-upstream-release-1.18-1587859578 -> automated-cherry-pick-of-#90476-upstream-release-1.18

+++ Creating a pull request on GitHub at zhan849:automated-cherry-pick-of-#90476-upstream-release-1.18
github.com password for zhan849 (never stored):
https://github.com/kubernetes/kubernetes/pull/90495

+++ Returning you to the harry/fix-backoff-manager-first-run branch and cleaning up.
```

**Pull request merged**
