### PR TITLE
Promote `ingressclass.kubernetes.io/is-default-class` annotation to networking/v1

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
According to KEP, this annotation  `ingressclass.kubernetes.io/is-default-class` should have been updated to `networking/v1` in version 1.20.

Ref https://github.com/kubernetes/enhancements/issues/1453
Ref #43214
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1453-ingress-api
```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
PTAL @derekwaynecarr

**Comment by mengjiao-liu** [comment]
Can you take a look? @liggitt Or do you know who can  review this PR？

**Comment by robscott** [comment]
Had to double check, but the string value is the same for v1 and v1beta1. Thanks for updating this @mengjiao-liu!

/lgtm

**Comment by robscott** [comment]
For anyone curious:

* [v1beta1](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1beta1/well_known_annotations.go#L24)
* [v1](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1/well_known_annotations.go#L24)

**Comment by mengjiao-liu** [comment]
ping @deads2k
for approval

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
