### PR TITLE
Create PersistentVolume and PersistentVolumeClaim

### PR DESCRIPTION
**Pull request by dgofman**
Create and configure a persistent volume storage
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Create a persistent volume using the kubectl create command line:
- Select volume size
- Permission to access volume
- Create PersistentVolume and PersistentVolumeClaim in the same manifest.

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubectl/issues/914

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by dgofman** [comment]
**kubectl create pv simple --storage 1Gi** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: simple
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /
status: {}
```

**kubectl create persistentvolume pvHostPath -r 1Gi --hostPath /Volumes/Data** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pvHostPath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Volumes/Data
status: {}
```

**kubectl create persistentvolumes pvHostPath -r 1Gi -p /Volumes/Data --storageClass manual** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pvHostPath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Volumes/Data
  storageClassName: manual
status: {}
```

**kubectl create pv mypv -r 1Gi -p /Volumes/Data -c manual --accessMode ReadOnlyMany -m ReadWriteMany** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: mypv
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /Volumes/Data
  storageClassName: manual
status: {}
```

**kubectl create pv myvol --storage 1Gi --hostPath /Volumes/Data --namespace default --claim** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: myvol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Volumes/Data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: myvol
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
```

**Comment by dgofman** [comment]
related to https://github.com/kubernetes/kubernetes/pull/112716

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
as discussed during Oct 5th SIG-CLI call (https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.bcbxqkuom4wh) this will not be accepted since we're planning to move forward with https://github.com/kubernetes/kubectl/issues/914 which will be targeted replacement for new create sub-commands.

**Pull request closed without merging**
