### PR TITLE
Remove unused code in pkg/api/,pkg/apis/

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:
Remove unused code in pkg/api/,pkg/apis/

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by rata — APPROVED** [review]
Great, thanks a lot for the patch! LGTM

It seems bazel is complaining, have you run `hack/update-bazel.sh`? Probably doing it, and amend the commit does the trick! :)

It will probably need to be LGTM again if you change stuff (and also LGTM by some other person), but just to test :)

**Comment by rata** [comment]
@islinwb check the user (and commit message ;)) of your second commit, that the cla/linuxfoundation check failing because of missing GitHub user. And let me know if I can help you to make bagel happy.

Thanks!

**Comment by islinwb** [comment]
@rata Many thanks! Had some problems in my side before.

**Comment by rata** [comment]
@islinwb great, thanks again!

**Comment by rata** [comment]
@wojtek-t I think this is ok to `/approve no-issue` but is the first PR I review, so let me know if there is some other criteria or something. Thanks!

**Pull request merged**
