### PR TITLE
MESOS: use annotations rather than labels for roles

### PR DESCRIPTION
**Pull request by s-urbaniak**
xref https://github.com/mesosphere/kubernetes-mesos/issues/697
xref https://github.com/kubernetes/kubernetes/pull/18348

### CODE REVIEW

**Comment by sttts** [comment]
An update of the docs is missing.

**Comment by s-urbaniak** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/690

**Comment by s-urbaniak** [comment]
@sttts correct, will be done in conjunction with https://github.com/mesosphere/kubernetes-mesos/issues/690

**Comment by wojtek-t** [comment]
@s-urbaniak - please rebase

**Comment by s-urbaniak** [comment]
@jdef PTAL

**Comment by jdef** [comment]
lgtm. needs rebase after #18348 is merged

**Pull request merged**
