### PR TITLE
fix shellcheck failures on health-monitor.sh

### PR DESCRIPTION
**Pull request by xichengliudui**
/kind cleanup
/priority backlog
/kind cleanup
/sig testing

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by cblecker** [comment]
Actually, #76694 is already open for this file.
/close

**Pull request closed without merging**
