### PR TITLE
Allow privileged containers in local cluster

### PR DESCRIPTION
**Pull request by pmorie**
I'm not sure who really uses this except for me :)

If people don't want this for local clusters, I can make it optional.

### CODE REVIEW

**Comment by pmorie** [comment]
@vmarmol @derekwaynecarr shot out of a cannon

**Comment by vmarmol** [comment]
This seems fine to me :) I will leave for a few hours before merging in case anyone thinks it's a bad idea.

The only concern I can think of is that if users use this to kick the tires, they may expect the functionality to be on by default when they bring up a real cluster. Not sure if the setup diverges between both already.

**Comment by pmorie** [comment]
I'll make you have to set `ALLOW_PRIVILEGED` for it work

**Comment by vmarmol** [comment]
@pmorie SGTM

**Comment by pmorie** [comment]
Should be good now @vmarmol

**Comment by vmarmol** [comment]
LGTM, thanks @pmorie!

**Pull request merged**
