### PR TITLE
clean todo

### PR DESCRIPTION
**Pull request by mouuii**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
// TODO(juanvallejo): update all subcommands to work with genericiooptions.IOStreams
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/uncc
not the right person to review this :-)
a kubectl owner should review this

**Comment by mpuckett159** [comment]
Nice, yes, god this has needed to happen for a while thanks. You're going to need to update all the unit test files as well because of the updated functions.

**Comment by mouuii** [comment]
> Nice, yes, god this has needed to happen for a while thanks. You're going to need to update all the unit test files as well because of the updated functions.

@mpuckett159 fixed, PTLA

**Comment by mouuii** [comment]
@mpuckett159 fixed, PTLA

**Pull request closed without merging**
