### PR TITLE
Don't add duplicate Hostname address

### LINKED ISSUE #36234: Problems with duplicate Node Hostname records
codablock on slack reported an issue regarding  https://github.com/kubernetes/kubernetes/pull/25532

(paraphrasing) "When used in combination with the Azure cloud provider, I get errors about Node.Status.Addresses being duplicated"

Looking at the code, the Azure cloudprovider returns a HostName address, but then a HostName address is also added by the kubelet code itself.

### PR DESCRIPTION
**Pull request by justinsb**
If the cloudprovider returned an address of type Hostname, we shouldn't
add a duplicate one.

Fixes #36234

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36231)

### CODE REVIEW

**Comment by justinsb** [comment]
cc @colemickens

**Comment by justinsb** [comment]
Fix #36234

**Comment by justinsb** [comment]
See meta-discussion here: https://github.com/kubernetes/kubernetes/issues/36234#issuecomment-258443317

**Comment by yujuhong** [comment]
I won't have time to review this today. Since the issue is marked 1.5, assigning to @dchen1107 to review or delegate

**Comment by liggitt** [comment]
added in https://github.com/kubernetes/kubernetes/pull/25532, this LGTM

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
