### PR TITLE
upgrade release-1.13 to go1.11.13

### PR DESCRIPTION
**Pull request by warmchang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
upgrade release-1.13 to go1.11.13

Ref: https://github.com/kubernetes/kubernetes/issues/79912#issuecomment-521064733, https://github.com/kubernetes/kubernetes/issues/73286

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/75780

**Special notes for your reviewer**:
@cblecker 

**Does this PR introduce a user-facing change?**:

```release-note
upgrade release-1.13 to go1.11.13
```

### CODE REVIEW

**Comment by warmchang** [comment]
/hold

Until the image "k8s.gcr.io/kube-cross:v1.11.13-1" generated:

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-cross?gcrImageListsize=30

**Comment by cblecker** [comment]
/hold
Do not build. The bazel stuff needs to be fixed up first.

**Comment by warmchang** [comment]
> /hold
> Do not build. The bazel stuff needs to be fixed up first.

/area release-team release-eng
/priority important-soon

Who can help to make & upload "kube-cross:v1.11.13-1" image? Thanks.

**Comment by cblecker** [comment]
@warmchang This PR is incomplete (bazel hasn't been updated/fixed). Unfortunately, due to release timelines we need to get this fixed. @BenTheElder and I are working on this in #81542.

Thank you for wanting to help. If we had more time, I would try to guide you through the changes required.

/close

**Pull request closed without merging**
