### PR TITLE
WIP: Rkt trust

### PR DESCRIPTION
**Pull request by yifan-gu**
In this PR, I:
1, Add a flag to pass container runtime configuration file to kubelet/contianer runtime.
2, Add some functions to enable rkt to read and parse the config file, and import the trusted keys.
3, Add an example for the config file for rkt, and add tests(wip).

This PR initially tries to address #8351 . And I found it might be more flexible to define a more generic container runtime config file instead of just trusted_keys.json 

I know we are going to freeze for 1.0, just put up the PR for discussion and iteration :)

/cc @erictune @vmarmol @philips

### CODE REVIEW

**Comment by yifan-gu** [comment]
@k8s-bot Don't test this...

**Comment by saad-ali** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release.  Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0.  We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why.  We're currently accepting changes that meet any of the following criteria:
1. Changes [directly related to v1.0 issues](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0)
2. Changes [addressing P0 bugs](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0)
3. Changes to supported platforms to bring them up to par with the primary development platforms
4. Docs, user experience, and test related fixes

**Comment by mikedanese** [comment]
Is this still WIP? Please rebase.

**Comment by yifan-gu** [comment]
@mikedanese Rebased. WIP is in regards to tests. 

For docs about `rkt trust`, can be found [here](https://github.com/coreos/rkt/blob/master/Documentation/commands.md#rkt-trust)

**Comment by ashcrow** [comment]
@yifan-gu would you mind rebasing?

**Comment by kelseyhightower** [comment]
@yifan-gu Is this still a work in progress? If so any plans to rebase?

**Comment by yifan-gu** [comment]
@kelseyhightower Not working on it now. Promise will clean this up after I got k8s/gce working on coreos :)

**Pull request closed without merging**
