### PR TITLE
Automated cherry pick of #68253: Update GCE PD CSI Driver to run by default and automatically

### PR DESCRIPTION
**Pull request by davidz627**
Cherry pick of #68253 on release-1.12.

#68253: Update GCE PD CSI Driver to run by default and automatically

```release-note
NONE
```

### CODE REVIEW

**Comment by davidz627** [comment]
/hold
until https://github.com/kubernetes/kubernetes/pull/69109 merges

**Comment by feiskyer** [comment]
Please add release notes in the original PR

**Comment by msau42** [comment]
This is an e2e test change, does it need a release note?

**Comment by davidz627** [comment]
ping @feiskyer

**Comment by feiskyer** [comment]
> This is an e2e test change, does it need a release note?

Sorry, didn't notice this. cherry pick approved now.

**Pull request merged**
