### PR TITLE
Update go-openapi to v0.20.0

### PR DESCRIPTION
**Pull request by howardjohn**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: Update go-openapi to a version with https://github.com/go-openapi/spec/issues/138 fixed, so init() times of any importer of Kubernetes libraries is not slow

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
-->
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by howardjohn** [comment]
I think this might break due to the kustomize dependency being super old

**Comment by apelisse** [comment]
> I think this might break due to the kustomize dependency being super old

Can you elaborate on that?

/ok-to-test

**Comment by howardjohn** [comment]
> > I think this might break due to the kustomize dependency being super old
> 
> Can you elaborate on that?

I am super confused. I was playing around with a similar update in another repo and noticed this line: https://github.com/kubernetes-sigs/kustomize/blob/v2.0.3/pkg/transformers/config/factorycrd.go#L31 won't work with v0.2.0 of go-openapi since they changed some function interface.

I then ran `hack/update-vendor.sh`, and it somehow produce this diff in the vendor:
```diff
diff --git a/vendor/sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go b/vendor/sigs.k8s.io/kustomize/pkg/transformers/config/f
actorycrd.go
index 66a24dc8688..2cd9ec2ae13 100644
--- a/vendor/sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go
+++ b/vendor/sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go
@@ -28,7 +28,7 @@ import (
        "sigs.k8s.io/kustomize/pkg/ifc"
 )

-type myProperties map[string]spec.Schema
+type myProperties = spec.SchemaProperties
 type nameToApiMap map[string]common.OpenAPIDefinition

 // LoadConfigFromCRDs parse CRD schemas from paths into a TransformerConfig
@@ -68,7 +68,7 @@ func makeNameToApiMap(content []byte) (result nameToApiMap, err error) {
 func makeConfigFromApiMap(m nameToApiMap) (*TransformerConfig, error) {
        result := MakeEmptyConfig()
        for name, api := range m {
-               if !looksLikeAk8sType(api.Schema.SchemaProps.Properties) {
+               if !looksLikeAk8sType(spec.SchemaProperties(api.Schema.SchemaProps.Properties)) {
                        continue
                }
                tc := MakeEmptyConfig()
```

Which is oddly the exact fix that is needed, but does not seem to match the go.mod? The go.mod says its using v2.0.3, but the code in v2.0.3 is different: https://github.com/kubernetes-sigs/kustomize/blob/v2.0.3/pkg/transformers/config/factorycrd.go#L31

So where did the diff come from?

**Comment by gautierdelorme** [comment]
I would recommend to hold off on this change since we are trying to move away from `go-openapi/spec`. See https://github.com/kubernetes/kubernetes/issues/96303. The work is being done at https://github.com/kubernetes/kube-openapi/compare/master...gautierdelorme:add_non_schema_types_to_validation_spec and is currently blocked on the `kustomize` upgrade in `kubernetes/kubernetes` (after its upgraded to a recent version we need to change https://github.com/kubernetes-sigs/kustomize/blob/a6f65144121d1955266b0cd836ce954c04122dc8/pkg/transformers/config/factorycrd.go#L24).

**Comment by gautierdelorme** [comment]
And the `kustomize` upgrade is being done at https://github.com/kubernetes/kubernetes/pull/98946. So this should be fixed soon.

**Comment by soltysh** [comment]
Given previous comments and the overall direction, I'm going to close this.
/close

**Pull request closed without merging**
