### PR TITLE
support fieldSelector status.hostIP

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

Add fieldSelector support for `status.hostIP`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
add fieldSelector support for status.hostIP
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendotjs** [comment]
/assign @liggitt @wojtek-t 
ptal :)

**Comment by liggitt** [comment]
is there an issue or description for why this field should be promoted to a field selector?

**Comment by chendotjs** [comment]
In some case when we want to filter out all hostNetwork pods on a specific node, `--field-selector="spec.nodeName=<NodeName>,status.podIP!=<NodeIP>"` works, but `--field-selector="status.hostIP=<NodeIP>,status.podIP!=<NodeIP>"` might be more convenient since we only have to know NodeIP.
Or the best approach is to support hostNetwork field selector, but will add more complexity. @liggitt

**Pull request closed without merging**
