### PR TITLE
Bump kube-openapi

### LINKED ISSUE #356: PuerkitoBio/urlesc is archived
https://github.com/kubernetes/kube-openapi/blob/10e5f0effbd23ac351f8da2138292759505a93a8/go.mod#L34

follow up of https://github.com/kubernetes/kubernetes/pull/114912

### PR DESCRIPTION
**Pull request by olivierlemasle**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update `k8s.io/kube-openapi` to include https://github.com/kubernetes/kube-openapi/pull/344, in order to update `github.com/go-openapi/jsonreference`.

Fixes https://github.com/kubernetes/kube-openapi/issues/356

Remove `k8s.io/kube-openapi` from the exceptions in `hack/unwanted-dependencies.json`.

#### Which issue(s) this PR fixes:

Follow-up of #114912

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @apelisse
/hold

### CODE REVIEW

**Comment by apelisse** [comment]
Thanks,
/lgtm
/approve

**Comment by liggitt** [comment]
/test pull-kubernetes-dependencies
to run check added in https://github.com/kubernetes/kubernetes/pull/114952

**Comment by olivierlemasle** [comment]
Had to rebase to fix a merge conflict

**Pull request merged**
