### PR TITLE
kubeadm: revert CoreDNS to 1.3.1

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
the CoreDNS upgrade faced some complications since the required Corefile mutations did a huge dependency update.

Revert the CoreDNS version in kubeadm back to 1.3.1, until the problems are resolved.
The 1.5.0 version bump can happen in https://github.com/kubernetes/kubernetes/pull/78033

**Which issue(s) this PR fixes**:

xref:
https://github.com/kubernetes/kubernetes/pull/78030
https://github.com/kubernetes/kubernetes/pull/78033

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: revert the CoreDNS version to 1.3.1
```

/assign @fabriziopandini @chrisohaver @rajansandeep 
/kind cleanup
/priority critical-urgent

### CODE REVIEW

**Review by chrisohaver — APPROVED** [review]

**Comment by chrisohaver** [comment]
FWIW, I refactored the coredns migration library to have zero deps. If #78033 is updated to use the latest commit, it should drop the added dependencies to one (just the migration library itself)

**Comment by rajansandeep** [comment]
/hold
after rebasing and updating the vendor dep in #78033

**Comment by chrisohaver** [comment]
@neolit123,  This revert is missing the version bumps to `cluster/addons/dns/coredns/` from #78030.

**Comment by neolit123** [comment]
@chrisohaver it was unclear whether the /cluster bump is going to make it in or not, detached from the kubeadm bump.

**Comment by moonek** [comment]
I have identified the issue below.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#known-issues
https://github.com/coredns/coredns/issues/2629

Is it ok to use k8s 1.15.1 and coredns 1.3.1 together?

**Comment by neolit123** [comment]
it might work for you on a new cluster, but it requires special actions during upgrade.
we are moving to coredns 1.6.0 for k8s 1.16 hopefully.

https://github.com/kubernetes/kubernetes/pull/78302

**Comment by chrisohaver** [comment]
> Is it ok to use k8s 1.15.1 and coredns 1.3.1 together?

Yes, 1.3.1 is the recommended version to use with Kubernetes 1.15.X.  Newer versions will also work, but may require manual updating of the coredns configuration file to remove/replace deprecated options.
A workaround for the [coredns 1.3.1 API crash issue](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#known-issues)  is to mount `/tmp` to an empty directory in the coredns pods. see: https://github.com/coredns/deployment/pull/138.

**Comment by Davidrjx** [comment]
@chrisohaver what you said is not working for me for "1.3.1 is the recommended version to use with Kubernetes 1.15.X.". Recently, i have not found out why?  Just some suspicious logs from apiserver and coredns.

**Pull request merged**
