### PR TITLE
eviction: Deflake TestStart

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind flake
/sig node

#### What this PR does / why we need it:

TestStart was previously flaky. In approx 100_000 local runs, it failed
70% of the time, and has been mentioned as a flaky unit test several times in
the past.

This flake was due to a race condition with the logic as written and the
go scheduler. UpdateThreshold calls `notifier.Start(events)` in a new Go
Routine, which is not guarunteed to be called immediately.

This meant that if `m.Start()` was called before `notifier.Start()`, the
test would fail, as the notifier would not have been started before the
4 events were processed and lock released.

Here, we update the test to more closely match the intended application
behaviour, and have events passed to the channel when `Start` is called
on the notifier.

This ensures that -Start gets called and additionally validates
that the correct channel is provided to the notifier.

Stop was never called previously, as it only gets called on a subsequent
call to UpdateThreshold. `AnyTimes()` hid that this did not occur.

#### Which issue(s) this PR fixes:

Related to: https://github.com/kubernetes/kubernetes/issues/107708

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm
tested

**Review by adisky — COMMENTED** [review]
/lgtm

**Comment by adisky** [comment]
/assign @klueska @dchen1107 @derekwaynecarr 
(for approval)

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
27 test failures (1 today) look like [link](https://storage.googleapis.com/k8s-triage/index.html?text=TestStart#85e101ea7912e3da847f)[search github](https://github.com/search?type=Issues&q=org:kubernetes%2085e101ea7912e3da847f)[file bug](https://storage.googleapis.com/k8s-triage/index.html?text=TestStart#)

It is still one of the top flakes in http://storage.googleapis.com/k8s-metrics/flakes-latest.json.

**Comment by dims** [comment]
/approve

thanks @endocrimes

**Pull request merged**
