### PR TITLE
Use protobufs by default in e2e test clients

### PR DESCRIPTION
**Pull request by wojtek-t**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33637)

### CODE REVIEW

**Comment by gmarek** [comment]
cc @kubernetes/test-infra-maintainers - this change will impact all tests, as all the clients will start talking in protobuf if not explicitly set to sth else. I'll monitor tests to see if it won't break anything and I'll try to disable protobufs in tests that will.

**Comment by wojtek-t** [comment]
@kubernetes/test-infra-admins @gmarek - this shouldn't break anything - our components are already communicate with protobufs (this includes controller-manager, scheduler, kubelet and kube-proxy)

**Comment by ixdy** [comment]
Do we want to have some test to make sure non-proto communication doesn't break?

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by spiffxp** [comment]
Agree with @ixdy maybe one of the example tests a-la Guestbook could use non-proto, since I expect that's what most end users experience today?

**Comment by gmarek** [comment]
+1, someone should configure the suite.

**Pull request merged**
