### PR TITLE
Use nodeutil.GetHostIP consistently when talking to nodes

### PR DESCRIPTION
**Pull request by justinsb**
Most of our communications from apiserver -> nodes used
    nodutil.GetNodeHostIP, but a few places didn't - and this meant that the
    node name needed to be resolvable _and_ we needed to populate valid IP
    addresses.

``` release-note
The apiserver now uses addresses reported by the kubelet in the Node object's status for apiserver->kubelet communications, rather than the name of the Node object.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33718)

### CODE REVIEW

**Comment by justinsb** [comment]
The first commit is https://github.com/kubernetes/kubernetes/pull/29011 , which was LGTM-ed but needed a rebase.

This works in my testing on AWS and passes e2e above (though we are still using NodeNames that are resolvable, so this may not be complete - but still a step in the right direction IMO!)

**Comment by justinsb** [comment]
(removed WIP)

**Comment by justinsb** [comment]
Issue #18525
Issue #9451
Issue #9728
Issue #17643
Issue #11543
Issue #22063
Issue #2462
Issue #22109
Issue #22770
Issue #32286

**Comment by justinsb** [comment]
@k8s-bot gke e2e test this

**Comment by liggitt** [comment]
switching from DNS to IP for master->kubelet connections has implications for deployments that validate the kubelet's serving certs. I am not aware of merge-queue tests that cover that scenario, so don't assume that green tests mean this will not break existing deployments.

**Comment by justinsb** [comment]
We have decided though: https://github.com/kubernetes/kubernetes/issues/22063#issuecomment-189582125

@bgrant0607 can you confirm?

**Comment by liggitt** [comment]
> We have decided though: https://github.com/kubernetes/kubernetes/issues/22063#issuecomment-189582125
> 
> @bgrant0607 can you confirm?

I don't disagree that decoupling the resolution from the nodeName is desired. I'm just looking to keep continuity for currently working clusters, while giving deployers the tools they need to decouple as appropriate to their environment. https://github.com/kubernetes/kubernetes/pull/25532 seems closer to achieving that goal.

**Comment by bgrant0607** [comment]
ref #2462

**Comment by bgrant0607** [comment]
@liggitt This and #25532 don't seem incompatible. Applying type checking to nodeName seems useful in order to avoid future regressions. We have time before cutting 1.5.

cc @cjcullen

**Comment by bgrant0607** [comment]
@liggitt What changes does this PR need in order to be merged?

**Comment by liggitt** [comment]
> @liggitt What changes does this PR need in order to be merged?

if there's general agreement to record more types of addresses in node status (#25532 or #34259 or similar) and to allow selecting which address types to use for apiserver->kubelet communications (#34259 or similar) by 1.5, I'm fine with this as-is

**Comment by liggitt** [comment]
LGTM, will follow up with #25532 and #34259

**Comment by kkirsche** [comment]
With this PR merged, does limitation 3 on https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/kubeadm.md#limitations need to be removed?

**Comment by resouer** [comment]
@liggitt Have we cherry picked this into latest release? Some people are asking for this. 

ref: https://github.com/kubernetes/kubernetes.github.io/issues/1453

**Comment by liggitt** [comment]
> @liggitt Have we cherry picked this into latest release? Some people are asking for this. 

No, picking just this into 1.4 could break clusters that are currently working with secured node names as DNS names. More changes are needed in the kubelet and apiserver to allow both DNS-based and IP-based modes of operation.

**Comment by luxas** [comment]
> With this PR merged, does limitation 3 on https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/kubeadm.md#limitations need to be removed?

ping @justinsb Does this PR fix that issue?

@kkirsche We can't remove it until v1.5 is released (which has this patch)

**Comment by kkirsche** [comment]
@luxas noted. Thank you for answering and clarifying that. I wasn't sure if hot fix / cherry picking was ever done for that type of thing. Thanks for everyone'a hard work!

**Comment by roeyazroel** [comment]
Hi,

Which version include GetNodeHostIP fix?
I'm using the following:

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Thanks,
Roey

**Comment by dkoshkin** [comment]
Looks like this was merged in `v1.5.0-alpha.1` https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v150-alpha1, I'm using that version and no longer see this issue.

**Pull request merged**
