### PR TITLE
Remove unneeded directory

### PR DESCRIPTION
**Pull request by wojtek-t**
Exactly the same function are living under: `staging/src/k8s.io/client-go/tools/ref`

```release-note
Remove GetReference() and GetPartialReference() function from pkg/api/ref, as the same function exists also in staging/src/k8s.io/client-go/tools/ref
```

### CODE REVIEW

**Comment by roycaihw** [comment]
Could you add a release note and point to the same function in client-go in the message?

Do we know if anyone can accidentally depend on this package? Should we have a deprecation period, or do we think this is low risk?

**Comment by wojtek-t** [comment]
> Could you add a release note and point to the same function in client-go in the message?

Done

> Do we know if anyone can accidentally depend on this package? Should we have a deprecation period, or do we think this is low risk?

I don't think it's needed - if someone depends on the code they need to update their dependency anyway, so at that point they can also switch to call a different one. It's not an API of k8s cluster.

**Comment by roycaihw** [comment]
@wojtek-t Sounds good

/lgtm

**Pull request merged**
