### PR TITLE
apiserver/pkg/storage/utils: remove unused EverythingFunc

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
since we don't provide compatibility guarantees for the storage package it is okay to simply remove unused function.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm

**Comment by wojtek-t** [comment]
/lgtm
/approve

[But let's merge it after code-freeze]

**Pull request merged**
