### PR TITLE
Add missing dependency to zookeeper-install

### LINKED ISSUE #73184: zookeeper-install image doesn't work (bash is missing)
**What happened**: The [zookeeper-installer](https://github.com/dims/kubernetes/tree/3e56e3c1c6b994f5b40a49f674e8c37a4c0dbf22/test/images/pets/zookeeper-installer) image used in the Statefulset e2e tests: https://github.com/kubernetes/kubernetes/blob/e4ef6079bc2c38ef7c741c6d253baa3f6fcad12f/test/e2e/apps/statefulset.go#L846 doesn't work because `bash` is missing in the image and the entrypoint is a bash script (`install.sh`).

**What you expected to happen**: The image should be able to execute the entrypoint.

**How to reproduce it (as minimally and precisely as possible)**:

Run the image with the same args as used in the manifests: https://github.com/kubernetes/kubernetes/blob/e4ef6079bc2c38ef7c741c6d253baa3f6fcad12f/test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml#L18-L22 
```
$ docker run -it gcr.io/kubernetes-e2e-test-images/pets/zookeeper-installer:1.2 --install-into=/opt --work-dir=/work-dir
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

**Anything else we need to know?**:

Can fix the issue by adding `bash` to the install command: https://github.com/dims/kubernetes/blob/3e56e3c1c6b994f5b40a49f674e8c37a4c0dbf22/test/images/pets/zookeeper-installer/Dockerfile#L21

and building a new image:

```
$ make -C test/images WHAT=pets/zookeeper-installer all-container
...
Successfully built adaa6bfab882
Successfully tagged gcr.io/kubernetes-e2e-test-images/pets/zookeeper-installer-arm64:1.2
...
$ docker run -it gcr.io/kubernetes-e2e-test-images/pets/zookeeper-installer-amd64:1.2 --install-into=/opt
installing config scripts into /work-dir
installing zookeeper-3.5.0-alpha into /opt
zookeeper-3.5.0-alpha supports dynamic reconfiguration, enabling it
copying nc into /opt
```

But I don't know if this is the right way since I don't fully understand the whole BASEIMAGE infrastructure and what's supposed to go where.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig testing

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug
/sig testing

**What this PR does / why we need it**:

The `zookeeper-install` image should be able to execute the entrypoint.

**Which issue(s) this PR fixes**:

Fixes #73184 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
let us update the VERSION number in https://github.com/kubernetes/kubernetes/blob/master/test/images/pets/zookeeper-installer/VERSION

**Comment by mkumatag** [comment]
Not really sure what got changed which is causing this issue. bash is used in https://github.com/kubernetes/kubernetes/blob/master/test/images/pets/redis-installer/install.sh as well.

**Comment by danielqsj** [comment]
@mkumatag  I found this peer-finder also install bash in dockerfile: https://github.com/kubernetes/kubernetes/blob/5c4b536f48b548b124dd6548e01c993870d6262e/test/images/pets/peer-finder/Dockerfile#L19

**Comment by mikkeloscar** [comment]
The version should also be bumped here somehow ro fix the e2e test: https://github.com/kubernetes/kubernetes/blob/5c4b536f48b548b124dd6548e01c993870d6262e/test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml#L18

Maybe this has to be done in a separate PR after the image is build from this PR being merged?

**Comment by danielqsj** [comment]
@ixdy @luxas if you have time, can you help review this? Thanks

**Comment by jrake-revelant** [comment]
would be great to see this merged soon

**Pull request merged**
