### PR TITLE
Move Job to batch/v1/job

### PR DESCRIPTION
**Pull request by lavalamp**
Taking over from #20551

### CODE REVIEW

**Comment by lavalamp** [comment]
Unit and integration tests pass. test-cmd.sh does not pass yet, presumably kubectl needs some help still.

@erictune

**Comment by lavalamp** [comment]
Status: I'm still making all the generators work.

**Comment by lavalamp** [comment]
@erictune this now passes all the tests locally, but there's still some issues.

**Comment by lavalamp** [comment]
@wojtek-t can you tell why codecgen is mad at me? It passes on my local system.

**Comment by lavalamp** [comment]
@erictune I think everything is working now. If you could give it a try that would be great.

**Comment by erictune** [comment]
Awesome.  Trying.

**Comment by erictune** [comment]
I can create a job with extensions/v1beta1 and I can get it back as batch/v1, but I cannot yet create one via kubectl from a file with `apiVersion: batch/v1`.  I get these errors:
```
$ ./kubectl create -f ./job3.yaml 
error validating "./job3.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
$ ./kubectl create -f ./job3.yaml --validate=false
unable to connect to a server to handle "jobs": unable to get RESTClient for resource 'jobs'
```

I'll keep working on it, but if you happen to know the issue off the top of you head... just sayin'.

**Comment by erictune** [comment]
Interesting.  I successfully posted a job using `curl` but then when I tried to get it back, the apiserver returned a 500.
```
I0210 04:26:18.107485       6 handlers.go:130] GET /apis/batch/v1/namespaces/default/jobs: (1.32393ms) 500
goroutine 25923 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc20871d110, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20871d110, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc209a8f500, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:236 +0xba
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f387c561af8, 0xc20836a000, 0x0, 0x0, 0x0, 0x0, 0x7f387c3a3d50, 0xc20a2548c8, 0xc208fb3860, 0x1f4, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:362 +0x174
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x7f387c55b4f8, 0xc208b04280, 0x7f387c561af8, 0xc20836a000, 0x0, 0x0, 0x0, 0x0, 0x7f387c3a3d50, 0xc20a2548c8, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:374 +0xdd
k8s.io/kubernetes/pkg/apiserver.logStackOnRecover(0x7f387c561af8, 0xc20836a000, 0x15a0de0, 0xc20a1170e0, 0x7f387c3a3d50, 0xc20a2548c8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:207 +0x4d7
k8s.io/kubernetes/pkg/apiserver.func·003(0x15a0de0, 0xc20a1170e0, 0x7f387c3a3d50, 0xc20a2548c8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:186 +0x56
github.com/emicklei/go-restful.func·005()
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:183 +0x80
reflect.Value.assignTo(0x1b0eea0, 0xc208ac9400, 0xd9, 0x1d4b490, 0xb, 0x1b0f6e0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/reflect/value.go:2125 +0x368
reflect.Value.Set(0x1b0f6e0, 0xc20a508c68, 0xd9, 0x1b0eea0, 0xc208ac9400, 0xd9)
        /usr/src/go/src/reflect/value.go:1298 +0x96
reflect.Append(0x156e560, 0xc20a208d00, 0x57, 0xc208c66ed8, 0x1, 0x1, 0x [[curl/7.43.0] 73.231.2.62:38176]
```

**Comment by erictune** [comment]
```
E0210 04:26:18.107319       6 apiserver.go:201] recover from panic situation: - reflect.Set: value of type v1.Job is not assignable to type extensions.Job^M
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:183^M
    /usr/src/go/src/runtime/asm_amd64.s:401^M
    /usr/src/go/src/runtime/panic.go:387^M
    /usr/src/go/src/reflect/value.go:2125^M
    /usr/src/go/src/reflect/value.go:1298^M
    /usr/src/go/src/reflect/value.go:1773^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_helper.go:428^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_helper.go:471^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/cacher.go:284^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:193^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:175^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:313^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:100^M
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249^M
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95^M
    /usr/src/go/src/net/http/server.go:1265^M
    /usr/src/go/src/net/http/server.go:1541^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:392^M
    /usr/src/go/src/net/http/server.go:1265^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:47^M
    /usr/src/go/src/net/http/server.go:1265^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101^M
    /usr/src/go/src/net/http/server.go:1265^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101^M
    /usr/src/go/src/net/http/server.go:1265^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:160^M
    /usr/src/go/src/runtime/asm_amd64.s:2232^M
```

**Comment by erictune** [comment]
`reflect.Set: value of type v1.Job is not assignable to type extensions.Job`

**Comment by lavalamp** [comment]
Sounds like we need some unit tests.

**Comment by erictune** [comment]
I am writing a e2e test that makes this fail.

I'm also happy to write a unit test.   Can you point me to an existing unit test that uses kubectl to create then get an object on a real apiserver?

**Comment by lavalamp** [comment]
I think actually an integration test is best, along the lines of your auth test.

If you want to actually use the kubectl binary, hack/test-cmd.sh is the place for such things.

**Comment by lavalamp** [comment]
@erictune how are you starting your apiserver? What settings for KUBE_API_VERSIONS and --storage-versions?

**Comment by lavalamp** [comment]
I also need to get hack/test-go.sh back into the habit of testing with different api versions on.

**Comment by erictune** [comment]
Just the defaults with cluster/kube-up.sh on GCE.
No --storage-versions flag.
No KUBE_API_VERSIONS flag.

**Comment by lavalamp** [comment]
OK. The defaults are actually wrong, sigh, but I'm not sure that explains what you see.

**Comment by erictune** [comment]
Should wrong defaults cause a panic, though?

**Comment by krousey** [comment]
Warning, I haven't really looked too closely at this PR, but...

I think this may be the caching in [etcd_helper.go:635](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L635). Group specific versions are cached by key at [etcd_helper.go:443](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L443). The type is determined by the list type being decoded into. Then a second list on the other type will hit the cache at [etcd_helper.go:428](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L428), and panic when it tries to append the first type to the second. I think...

@erictune You should be able exact mirror error by reversing the order/types of your experiment.

**Comment by erictune** [comment]
@krousey I think that is it too.  Can you suggest a fix?

**Comment by krousey** [comment]
Umm... Either cache the raw data and decode every time, or dynamically detect the type mismatch and try to convert.

**Comment by lavalamp** [comment]
I think something is just configured wrong.

**Comment by erictune** [comment]
I wrote tests which repro the problem.  I just made PR #21028 which has all these commits plus the new tests.

**Comment by lavalamp** [comment]
OK so the first problem is that there's separate registries installed in the extensions & batch handers, with different storage versions.

**Comment by derekwaynecarr** [comment]
please update namespace_controller_utils to ensure we don't regress job deletion.  right now, it gates deleting jobs based on extensions content.

**Comment by erictune** [comment]
@derekwaynecarr job controller is going to keep using extensions in 1.2.
I think namespace_controller_utils can also do that?

**Comment by lavalamp** [comment]
OK, I figured out that all the test files don't use the logic in the apiserver setup code. So either have to duplicate this or refactor. Still deciding.

**Comment by lavalamp** [comment]
OK I think I found part of my major problem...

**Comment by lavalamp** [comment]
OK... test-go passes, test-integration passes with one exception, it can't find the swagger spec to validate batch/v1/job. Getting very close.

@nikhiljindal Do you know how to make the validation code find the swagger spec for batch/v1?

```
--- FAIL: TestKubectlValidation (0.30s)
        kubectl_test.go:75: case 5: unexpected error: the server could not find the requested resource
```

**Comment by lavalamp** [comment]
I fixed it enough that I found the cacher problem again. Hopefully I can find it quickly now...

**Comment by lavalamp** [comment]
OK, the codec has been defective the whole time, it fails to make batch/v1/job into extensions/__internal/job. Will probably just need to make a shim.

**Comment by lavalamp** [comment]
OK, I know the problem...

**Comment by lavalamp** [comment]
OK, have a fix for decode side. Checking for corresponding problem on encode side...

**Comment by lavalamp** [comment]
I need to squash this down some to manage a rebase.

**Pull request closed without merging**
