### PR TITLE
Switch to k8s-1.10 branch of the installer in release-1.10 branch.

### PR DESCRIPTION
**Pull request by rohitagarwal003**
```release-note
NONE
```

/assign jiayingz vishh MaciekPytel

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/hold
Hold until 1.10.1 is released.

**Comment by aleksandra-malinowska** [comment]
Shouldn't it also be updated here: https://github.com/kubernetes/kubernetes/blob/release-1.10/test/e2e/framework/gpu_util.go#L35:2 ? If these are intended to be different, which one should we use in autoscaling tests?

**Pull request merged**
