### PR TITLE
quick fix to test script

### PR DESCRIPTION
**Pull request by adohe-zz**
add a quick fix to #39922 , @deads2k ptal, I am not a bash expert.

### CODE REVIEW

**Comment by k82cn** [comment]
@deads2k , another PR on `make check` at #39859 , PTAL; seems a typo here :).

**Comment by tanshanshan** [comment]
I found the same problem , and  solved it through this way . Thanks.

**Comment by tanshanshan** [comment]
> Didn't work. Make sure any fix still run the unit tests from staging/src/k8s.io/apimachinery symlinked to vendor/k8s.io/apimachinery

And ,  I also   
staging/src/k8s.io/client-go  symlinked to  vendor/k8s.io/client-go 
staging/src/k8s.io/apiserver  symlinked to /vendor/k8s.io/apiserver

**Comment by lavalamp** [comment]
I responded on the issue. I don't think we need a code change for this.

**Pull request closed without merging**
