### PR TITLE
Set resource limit for both heapster and influxdb container based on

### LINKED ISSUE #10256: Set resource limits on Heapster
#5880 provides a resource profile for heapster.
Heapster containers have to be restricted to 0.5 CPU cores and 2GiB of memory, based on the resource usage patterns in a loaded 100 node cluster.

cc @dchen1107 @saad-ali

### PR DESCRIPTION
**Pull request by dchen1107**
data collected by #5880 

Fixed #10256

cc/ @vishh and @saad-ali

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @davidopp and @roberthbailey Can I have two TLs' lgtm here :-)

**Comment by davidopp** [comment]
LGTM

**Comment by dchen1107** [comment]
@quinton-hoole Can you have your precious lgtm then?

**Comment by vishh** [comment]
LGTM. Thanks for the PR @dchen1107

**Comment by quinton-hoole** [comment]
LGTM. OK to merge.

**Comment by eparis** [comment]
@derekwaynecarr So it looks to me like vagrant has influxdb as the default
```
vagrant/config-default.sh:ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-influxdb}"`
```
but only 1G per node:
```
$vm_minion_mem = (ENV['KUBERNETES_MINION_MEMORY'] || ENV['KUBERNETES_MEMORY'] || 1024).to_i
```

So effectively this change broke vagrant, right?

**Comment by derekwaynecarr** [comment]
I typically did not run with that add-on, but yes, it would cause an issue.  I will look more on Monday

**Pull request merged**
