### PR TITLE
Modify kubectl exec help to set -c CONTAINER as optional

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
lgtm, thanks

**Comment by roberthbailey** [comment]
@k8s-bot retest this please

**Comment by roberthbailey** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
The jenkins failure is

```
• Failure [112.623 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:952
  should be able to up and down services [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:277

  Expected error:
      <*errors.errorString | 0xc208474600>: {
          s: "Only 0 pods started out of 3",
      }
      Only 0 pods started out of 3
  not to have occurred
```

**Comment by roberthbailey** [comment]
Seems unrelated (wanted to paste for posterity / flake chasing). 

@k8s-bot test this

**Pull request merged**
