### PR TITLE
Kubeadm: Use fmt.Println instead of fmt.Printf

### PR DESCRIPTION
**Pull request by MalloZup**
> /kind cleanup

**What this PR does / why we need it**:
Refactoring minor print statement.

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — APPROVED** [review]
Thanks @MalloZup 
Can you change the release note to NONE?

**Comment by MalloZup** [comment]
thx done

**Review by neolit123 — APPROVED** [review]
/retest

**Pull request merged**
