### PR TITLE
Add bsalamat to sig-scheduling-maintainers

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:
Adds bsalamat to sig-scheduling-maintainers.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Release note**:

```release-note
NONE
```

@kubernetes/sig-scheduling-pr-reviews @davidopp @timothysc @k82cn @wojtek-t

### CODE REVIEW

**Comment by k82cn** [comment]
+1

/lgtm

**Comment by timothysc** [comment]
@bsalamat You may need to update some other owners files, b/c aliases may not be leveraged in all places.

**Comment by bsalamat** [comment]
@timothysc I looked at the /plugin/pkg/scheduler, /test/e2e/scheduling, and /test/integration/scheduler. They all use the alias. Is there anywhere else that I should check?

**Comment by timothysc** [comment]
plugin/cmd/kube-scheduler
test/integration/scheduler_perf

**Comment by bsalamat** [comment]
Ah, thanks, @timothysc! I changed one to use aliases and added myself to the other one.

**Comment by k82cn** [comment]
Updated milestone to get this merged :).

**Pull request merged**
