### PR TITLE
Remove all _test.go files from Godeps

### PR DESCRIPTION
**Pull request by eparis**
Done with

```
godep restore
rm -rf Godeps
godep save ./...
```

Previously you had to do `godep save -t ./...`

### CODE REVIEW

**Comment by eparis** [comment]
I like how a PR can remove 221777 lines of code and be "XS"

**Comment by pweil-** [comment]
LGTM - all deletes and all *_test.go files in godeps (except for a few things in a testdata directory) :+1:

**Comment by ncdc** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by jimmidyson** [comment]
LGTM. Would love to see this merged ASAP as it's holding up some required godep updates for cadvisor & libcontainer (#15612).

**Comment by jimmidyson** [comment]
@dchen1107 @eparis Can we get this cherry-picked into 1.1 branch too? Annoyingly failing godep bumps without this.

**Comment by jimmidyson** [comment]
Submitted #16260.

**Pull request merged**
