### PR TITLE
update pkg/errors to v0.8.1

### PR DESCRIPTION
**Pull request by tariq1890**
/kind feature

This version provides the method `errors.WithMessagef`. We use errors.Wrapf when we want to annotate errors with contextual information. Over-wrapping leads to bloating of the error stack. This PR allows for a more lightweight annotation of errors.

```release-note
NONE
```

### CODE REVIEW

**Comment by tariq1890** [comment]
So `/hack/update-vendor.sh` fails with exit status 9 when I run locally.

**Comment by apelisse** [comment]
> So /hack/update-vendor.sh fails with exit status 9 when I run locally.

What's the output?

cc @liggitt

**Comment by lavalamp** [comment]
Where will this be used?

**Comment by tariq1890** [comment]
@apelisse This is my output

```
++ grep -qe '-o errexit'
++ set +o xtrace
!!! Error in hack/update-vendor.sh:312
  Error in hack/update-vendor.sh:312. 'hack/update-vendor-licenses.sh >> "${LOG_FILE}" 2>&1' exited with status 9
Call stack:
  1: hack/update-vendor.sh:312 main(...)
Exiting with status 1
!!! Error in ./hack/verify-vendor.sh:61
  Error in ./hack/verify-vendor.sh:61. 'hack/update-vendor.sh' exited with status 1
Call stack:
  1: ./hack/verify-vendor.sh:61 main(...)
Exiting with status 1

```

**Comment by tariq1890** [comment]
@lavalamp There are several places where we use `errors.Wrap`. In some areas, `errors.WithMessage` could be used for the sake of avoiding error stack bloating.  

Also if you feel this is unnecessary, I can close this PR. I do understand the concerns with dealing with the dependencies.

**Pull request closed without merging**
