### PR TITLE
Prep for not checking in generated, part 2/2

### PR DESCRIPTION
**Pull request by thockin**
This PR is extracted from #25978 and build on #28578 - it is just the conversion related parts. All the Makefile stuff is excluded.

@wojtek-t this is literally branched, a bunch of commits deleted, and a very small number of manual fixups applied. If you think this is easier to review (and if it passes CI) you can feel free to go over it again. I will follow this with a conversion-related PR to build on this.

Or if you prefer, just close this and let the mega-PR ride.

@lavalamp

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin - an you please rebase?

**Comment by thockin** [comment]
@wojtek-t part 1 is in, this is now rebased onto it.

**Comment by wojtek-t** [comment]
Yes - I've seen part 1 is in. Will look into this one in few minutes.

**Comment by thockin** [comment]
You're awesome!  I owe you a drink or a meal or something :)

**Comment by wojtek-t** [comment]
LGTM

**Comment by thockin** [comment]
rebased twice in 24 hours.  Making p2.

**Pull request merged**
