### PR TITLE
remove rate limiter metric as it is not in use

### LINKED ISSUE #113023: rate_limiter_use metric uses a dynamic subsystem
### What happened?

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/component-base/metrics/prometheus/ratelimiter/rate_limiter.go#L48 uses a dynamic `ownerName` as a part of the metric name. This should instead be a label of a generic metric. 

### What did you expect to happen?

`ownerName` should be a label for the metric.

### How can we reproduce it (as minimally and precisely as possible)?

You can curl the metrics endpoint on the apiserver. 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# v1.22.12-gke.2300
```

</details>

### Cloud provider

This part doesn't matter.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by logicalhan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This metric has not been in use for many years. This PR just cleans up the unused code.

Fixes #113023 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

Note: here is where the metric is actually **not** doing anything:

https://github.com/kubernetes/kubernetes/blob/release-1.25/staging/src/k8s.io/component-base/metrics/prometheus/ratelimiter/rate_limiter.go#L63-L76

### CODE REVIEW

**Comment by lavalamp** [comment]
If this metric was supposed to be tracking the client-side rate limiting, can you make an issue that that needs a metric?

**Comment by logicalhan** [comment]
> If this metric was supposed to be tracking the client-side rate limiting, can you make an issue that that needs a metric?

Sure, filed https://github.com/kubernetes/kubernetes/issues/113072

**Pull request merged**
