### PR TITLE
[DO NOT MERGE] node authorizer tracing

### PR DESCRIPTION
**Pull request by liggitt**
adds tracing to the node authorizer PR... seeing an odd 1 second delay on the local pod watch (the kubelet watch sees the pod binding in ~.01 seconds, the local watch via a shared informer feeding the authorizer sees it in ~1 second), which makes the first couple requests for secrets from the node get forbidden

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek

**Comment by liggitt** [comment]
combined apiserver (pid 5) / kubelet (pid 3577) log for a relevant flow:
```
│I0605 04:05:52.296277       5 graph_populator.go:67] updatePod > e2e-tests-horizontal-pod-autoscaling-2tk8z/rc-light-ctrl-9dn0q for node e2e-34292-minion-group-4vk7                                                                                                        ┤
│I0605 04:05:52.296325       5 graph_populator.go:70] updatePod < e2e-tests-horizontal-pod-autoscaling-2tk8z/rc-light-ctrl-9dn0q for node e2e-34292-minion-group-4vk7                                                                                                        ┤
│I0605 04:05:52.416579       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002: (22.316587ms) 200 [[e2e.test/v1.8.0 (linux/amd64) kubernetes/1b90c35] 104.155.148.195:33721]                       ┤
└I0605 04:05:52.418495       5 wrap.go:42] POST /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002/binding: (22.314927ms) 201 [[kube-scheduler/v1.8.0 (linux/amd64) kubernetes/1b90c35/leader-election] [::1]:55638]  ┤
┌I0605 04:05:52.423455    3577 config.go:415] Receiving a new pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                                  ┤
│I0605 04:05:52.423546    3577 kubelet.go:1857] SyncLoop (ADD, "api"): "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                             ┤
│I0605 04:05:52.423759    3577 kubelet_pods.go:1177] Generating status for "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                         ┤
└I0605 04:05:52.427685    3577 volume_manager.go:340] Waiting for volumes to attach and mount for pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                              ┤
◆I0605 04:05:52.517429       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002: (45.535157ms) 200 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                          ┤
┌I0605 04:05:52.616688    3577 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242a┤
└I0605 04:05:52.616749    3577 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-nvtz5" (UniqueName: "kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5") pod "downwardapi-volume-4403044c-49┤
◆I0605 04:05:52.646758       5 wrap.go:42] PUT /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002/status: (70.195816ms) 200 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                   ┤
┌I0605 04:05:52.651615    3577 kubelet.go:1870] SyncLoop (RECONCILE, "api"): "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                       ┤
│I0605 04:05:52.659669    3577 status_manager.go:453] Status for pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)" updated successfully: (1, {Phase:Pending Conditions:[{Type:Initialized Status:┤
│I0605 04:05:52.717098    3577 reconciler.go:257] operationExecutor.MountVolume started for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002" (UID: "441┤
│I0605 04:05:52.718493    3577 reconciler.go:257] operationExecutor.MountVolume started for volume "default-token-nvtz5" (UniqueName: "kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac┤
│I0605 04:05:52.718547    3577 secret.go:186] Setting up volume default-token-nvtz5 for pod 441026a3-49a4-11e7-91d5-42010a800002 at /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~secret/default-token-nvtz5                              ┤
│I0605 04:05:52.718749    3577 empty_dir.go:257] pod 441026a3-49a4-11e7-91d5-42010a800002: mounting tmpfs for volume wrapped_default-token-nvtz5                                                                                                                             ┤
│I0605 04:05:52.718771    3577 mount_linux.go:118] Mounting cmd (mount) with arguments ([-t tmpfs tmpfs /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~secret/default-token-nvtz5])                                                        ┤
│I0605 04:05:52.717338    3577 downwardapi.go:176] Setting up a downwardAPI volume podinfo for pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 at /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~down┤
│I0605 04:05:52.724938    3577 atomic_writer.go:145] pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 volume podinfo: write required for target directory /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.┤
│I0605 04:05:52.725079    3577 atomic_writer.go:160] pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 volume podinfo: performed write of new data to ts data directory: /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volum┤
└I0605 04:05:52.725174    3577 operation_generator.go:472] MountVolume.SetUp succeeded for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002" (UID: "4410┤
┌I0605 04:05:52.794006       5 node_authorizer.go:117] NODE DENY: node e2e-34292-minion-group-qd22 cannot get unknown secret e2e-tests-projected-02sxz/default-token-nvtz5                                                                                                   ┤
│I0605 04:05:52.796271       5 rbac.go:114] RBAC DENY: user "system:node:e2e-34292-minion-group-qd22" groups ["system:nodes" "system:authenticated"] cannot "get" resource "secrets" named "default-token-nvtz5" in namespace "e2e-tests-projected-02sxz"                    ┤
└I0605 04:05:52.796437       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/secrets/default-token-nvtz5: (2.710873ms) 403 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                                                            ┤
┌E0605 04:05:52.804885    3577 secret.go:201] Couldn't get secret e2e-tests-projected-02sxz/default-token-nvtz5: User "system:node:e2e-34292-minion-group-qd22" cannot get secrets in the namespace "e2e-tests-projected-02sxz".: "no path found to object" (get secrets defa┤
│E0605 04:05:52.805052    3577 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5\" (\"441026a3-49a4-11e7-91d5-42010a800002\")" failed. No retries permitted until 2017-06-05 04:05:53.305022401 ┤
└I0605 04:05:52.805391    3577 server.go:353] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-projected-02sxz", Name:"downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002", UID:"441026a3-49a4-11e7-91d5-42010a800002", APIVersion:"v1", ResourceVersion:"2536"┤
┌I0605 04:05:52.831424       5 graph_populator.go:67] updatePod > e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 for node e2e-34292-minion-group-qd22                                                                                     ┤
│I0605 04:05:52.831479       5 graph_populator.go:70] updatePod < e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 for node e2e-34292-minion-group-qd22 
```

1. 04:05:52.296325 graph_populator finishes processing last watch notification prior to the pod update we're interested in
2. 04:05:52.416579 pod downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 is bound
3. 04:05:52.423455 kubelet receives the notification of the pod binding
4. 04:05:52.796437 kubelet makes GET call to fetch secret to mount (gets denied by node and rbac authorizers)
5. 04:05:52.831424 graph_populator is notified of the pod binding

I'm really surprised the kubelet receives the watch event in .01 seconds, and the in-process watch receives it in .42 seconds

**Comment by coderwangke** [comment]
> combined apiserver (pid 5) / kubelet (pid 3577) log for a relevant flow:
> 
> ```
> │I0605 04:05:52.296277       5 graph_populator.go:67] updatePod > e2e-tests-horizontal-pod-autoscaling-2tk8z/rc-light-ctrl-9dn0q for node e2e-34292-minion-group-4vk7                                                                                                        ┤
> │I0605 04:05:52.296325       5 graph_populator.go:70] updatePod < e2e-tests-horizontal-pod-autoscaling-2tk8z/rc-light-ctrl-9dn0q for node e2e-34292-minion-group-4vk7                                                                                                        ┤
> │I0605 04:05:52.416579       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002: (22.316587ms) 200 [[e2e.test/v1.8.0 (linux/amd64) kubernetes/1b90c35] 104.155.148.195:33721]                       ┤
> └I0605 04:05:52.418495       5 wrap.go:42] POST /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002/binding: (22.314927ms) 201 [[kube-scheduler/v1.8.0 (linux/amd64) kubernetes/1b90c35/leader-election] [::1]:55638]  ┤
> ┌I0605 04:05:52.423455    3577 config.go:415] Receiving a new pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                                  ┤
> │I0605 04:05:52.423546    3577 kubelet.go:1857] SyncLoop (ADD, "api"): "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                             ┤
> │I0605 04:05:52.423759    3577 kubelet_pods.go:1177] Generating status for "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                         ┤
> └I0605 04:05:52.427685    3577 volume_manager.go:340] Waiting for volumes to attach and mount for pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                              ┤
> ◆I0605 04:05:52.517429       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002: (45.535157ms) 200 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                          ┤
> ┌I0605 04:05:52.616688    3577 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242a┤
> └I0605 04:05:52.616749    3577 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-nvtz5" (UniqueName: "kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5") pod "downwardapi-volume-4403044c-49┤
> ◆I0605 04:05:52.646758       5 wrap.go:42] PUT /api/v1/namespaces/e2e-tests-projected-02sxz/pods/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002/status: (70.195816ms) 200 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                   ┤
> ┌I0605 04:05:52.651615    3577 kubelet.go:1870] SyncLoop (RECONCILE, "api"): "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)"                                                                       ┤
> │I0605 04:05:52.659669    3577 status_manager.go:453] Status for pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002_e2e-tests-projected-02sxz(441026a3-49a4-11e7-91d5-42010a800002)" updated successfully: (1, {Phase:Pending Conditions:[{Type:Initialized Status:┤
> │I0605 04:05:52.717098    3577 reconciler.go:257] operationExecutor.MountVolume started for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002" (UID: "441┤
> │I0605 04:05:52.718493    3577 reconciler.go:257] operationExecutor.MountVolume started for volume "default-token-nvtz5" (UniqueName: "kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac┤
> │I0605 04:05:52.718547    3577 secret.go:186] Setting up volume default-token-nvtz5 for pod 441026a3-49a4-11e7-91d5-42010a800002 at /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~secret/default-token-nvtz5                              ┤
> │I0605 04:05:52.718749    3577 empty_dir.go:257] pod 441026a3-49a4-11e7-91d5-42010a800002: mounting tmpfs for volume wrapped_default-token-nvtz5                                                                                                                             ┤
> │I0605 04:05:52.718771    3577 mount_linux.go:118] Mounting cmd (mount) with arguments ([-t tmpfs tmpfs /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~secret/default-token-nvtz5])                                                        ┤
> │I0605 04:05:52.717338    3577 downwardapi.go:176] Setting up a downwardAPI volume podinfo for pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 at /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.io~down┤
> │I0605 04:05:52.724938    3577 atomic_writer.go:145] pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 volume podinfo: write required for target directory /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volumes/kubernetes.┤
> │I0605 04:05:52.725079    3577 atomic_writer.go:160] pod e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 volume podinfo: performed write of new data to ts data directory: /var/lib/kubelet/pods/441026a3-49a4-11e7-91d5-42010a800002/volum┤
> └I0605 04:05:52.725174    3577 operation_generator.go:472] MountVolume.SetUp succeeded for volume "podinfo" (UniqueName: "kubernetes.io/downward-api/441026a3-49a4-11e7-91d5-42010a800002-podinfo") pod "downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002" (UID: "4410┤
> ┌I0605 04:05:52.794006       5 node_authorizer.go:117] NODE DENY: node e2e-34292-minion-group-qd22 cannot get unknown secret e2e-tests-projected-02sxz/default-token-nvtz5                                                                                                   ┤
> │I0605 04:05:52.796271       5 rbac.go:114] RBAC DENY: user "system:node:e2e-34292-minion-group-qd22" groups ["system:nodes" "system:authenticated"] cannot "get" resource "secrets" named "default-token-nvtz5" in namespace "e2e-tests-projected-02sxz"                    ┤
> └I0605 04:05:52.796437       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-projected-02sxz/secrets/default-token-nvtz5: (2.710873ms) 403 [[kubelet/v1.8.0 (linux/amd64) kubernetes/1b90c35] 35.192.55.161:59407]                                                            ┤
> ┌E0605 04:05:52.804885    3577 secret.go:201] Couldn't get secret e2e-tests-projected-02sxz/default-token-nvtz5: User "system:node:e2e-34292-minion-group-qd22" cannot get secrets in the namespace "e2e-tests-projected-02sxz".: "no path found to object" (get secrets defa┤
> │E0605 04:05:52.805052    3577 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/441026a3-49a4-11e7-91d5-42010a800002-default-token-nvtz5\" (\"441026a3-49a4-11e7-91d5-42010a800002\")" failed. No retries permitted until 2017-06-05 04:05:53.305022401 ┤
> └I0605 04:05:52.805391    3577 server.go:353] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-projected-02sxz", Name:"downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002", UID:"441026a3-49a4-11e7-91d5-42010a800002", APIVersion:"v1", ResourceVersion:"2536"┤
> ┌I0605 04:05:52.831424       5 graph_populator.go:67] updatePod > e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 for node e2e-34292-minion-group-qd22                                                                                     ┤
> │I0605 04:05:52.831479       5 graph_populator.go:70] updatePod < e2e-tests-projected-02sxz/downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 for node e2e-34292-minion-group-qd22 
> ```
> 
> 1. 04:05:52.296325 graph_populator finishes processing last watch notification prior to the pod update we're interested in
> 2. 04:05:52.416579 pod downwardapi-volume-4403044c-49a4-11e7-9d06-0242ac110002 is bound
> 3. 04:05:52.423455 kubelet receives the notification of the pod binding
> 4. 04:05:52.796437 kubelet makes GET call to fetch secret to mount (gets denied by node and rbac authorizers)
> 5. 04:05:52.831424 graph_populator is notified of the pod binding
> 
> I'm really surprised the kubelet receives the watch event in .01 seconds, and the in-process watch receives it in .42 seconds
> 
> I don't see evidence of a slow reader on the shared informer (as far as I know, the node authorizer is the only reader), and I don't see evidence of lock contention updating the graph (all graph writes are taking between ~1 and ~.1 ms)

Is there a conclusion to this question?

**Pull request closed without merging**
