### PR TITLE
Update etcd packages to v3.5.4

### PR DESCRIPTION
**Pull request by dims**
in e9e8be304c9b9abc4e16a38e4be6da10ce2d7b06 we updated etcd server
components to 3.5.4, here let's update the vendor/ as well to match

/kind cleanup

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What this PR does / why we need it:

Match the vendored etcd client to v3.5.4 just like the server components!

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Some of the packages are going from 3.5.0 to 3.5.4, differences are:
https://github.com/etcd-io/etcd/compare/v3.5.0...v3.5.4

Others are going from 3.5.1 to 3.5.4, differences are:
https://github.com/etcd-io/etcd/compare/v3.5.1...v3.5.4

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt @thockin 
(for root OWNERS approval)

cc @ahrtr

**Comment by ahrtr** [comment]
The PR looks good to me. 

All the etcd binaries and image versions have already been bumped to 3.5.4. So this PR only needs to bump the package versions in go.mod.

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
