### PR TITLE
Return error from NodeGetInfo

### PR DESCRIPTION
**Pull request by xing-yang**
**What this PR does / why we need it**:
This PR checks if NodeGetInfo returns error. If so, it returns
the error.

Without this change, it always returns no error (nil)
regardless of whether NodeGetInfo returns error.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Returns error if NodeGetInfo fails.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@verult Please take a look.

**Comment by neolit123** [comment]
thanks!
/kind cleanup
/ok-to-test

**Comment by vladimirvivien** [comment]
/lgtm

Thanks @xing-yang

**Pull request merged**
