### PR TITLE
Removed diplicated info row in v1.12.7

### LINKED ISSUE #79653: Duplicate rows in Changelog for v1.12.7
**What happened**:
There is a duplicate row in the Changelog for v1.12.7

**How to reproduce it (as minimally and precisely as possible)**:
[CHANGELOG-1.12](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#changelog-since-v1127) the first and the fourth row are exactly the same.

/sig docs

### PR DESCRIPTION
**Pull request by ilchebedelovski**
**What type of PR is this?**
> documentation

**What this PR does / why we need it**:
It provides fix in the Changelog by removing duplicate information for v1.12.7

**Which issue(s) this PR fixes**:
Fixes #79653

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by ilchebedelovski** [comment]
I signed it

**Review by nikhita — APPROVED** [review]
@ilchebedelovski Good catch! :)

/kind cleanup
/sig release
/release-note-none
/priority backlog
/ok-to-test
/lgtm

**Comment by nikhita** [comment]
/assign @liggitt 
for approval

**Pull request merged**
