### PR TITLE
move internal apps API types out of extensions package

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
related to https://github.com/kubernetes/kubernetes/issues/43214

**Special notes for your reviewer**:
* removes unused CustomMetricTarget types
* moves internal API types, fuzzing, validation, and conversion from extensions to apps
* stops generating GetScale/UpdateScale for internal clients (since it doesn't work correctly)

The main commits that need review:
* `Change registration and custom conversion from extensions to apps`
* `fixup extensions->apps references`

The "move ..." commits are pure moves, no internal changes.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @kow3ns 
@kubernetes/sig-apps-pr-reviews

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by caesarxuchao — COMMENTED** [review]
/lgtm

Fix the nits if you have to rebase anyway.

**Comment by liggitt** [comment]
nits fixed, retagging

need /approve from @caesarxuchao for replication controller package and @timothysc for kubeadm package

**Comment by timothysc** [comment]
/approve 

from the kubeadm side.

**Pull request merged**
