### PR TITLE
Remove redundant api registration

### PR DESCRIPTION
**Pull request by drivebyer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The kube-aggregator related apis already registered by `install.Install(Scheme)`. This PR make code clean and remove redundant function call.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by drivebyer** [comment]
I have signed CLA.

**Comment by drivebyer** [comment]
PTAL，@caesarxuchao @cheftako

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
