### PR TITLE
Promote DS max surge to GA

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Promote DaemonSet MaxSurge to GA. This means `--feature-gates=DaemonSetUpdateSurge=true` are not needed on kube-apiserver and kube-controller-manager binaries and they'll be removed soon following policy at https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1591
- [Usage]: Promote DaemonSet MaxSurge to GA. This means `--feature-gates=DaemonSetUpdateSurge=true` are not needed on kube-apiserver and kube-controller-manager binaries and they'll be removed soon following policy at https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation 
- [Other doc]: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec
```

### CODE REVIEW

**Comment by atiratree** [comment]
looks good

also we also want to promote this test to conformance once this merges right? https://github.com/kubernetes/kubernetes/blob/ff20035ef8d305e5bec3866670b515d0c5c6a1c0/test/e2e/apps/daemon_set.go#L502-L503

**Comment by sftim** [comment]
For the changelog entry, please link to https://github.com/kubernetes/enhancements/issues/1591 and not the PR associated with it.

**Comment by smarterclayton** [comment]
/approve

API changes look good to me, the enhancement is in good order, and the docs will be a separate PR.

Are there any changes to tests planned beyond what was described in the KEP?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
from sig-apps pov
/hold 
for additional feedback

**Comment by ravisantoshgudimetla** [comment]
> Are there any changes to tests planned beyond what was described in the KEP?

@smarterclayton - As of now nothing the units are pretty exhaustive. But if you have something in mind, please let us know, and we can add more tests 

@sftim - Addressed your comment. PTAL and remove hold if that is what you wanted.

**Comment by soltysh** [comment]
Having heard no objections
/hold cancel

**Pull request merged**
