### PR TITLE
Modify tag to namespace and index it

### PR DESCRIPTION
**Pull request by xuejipeng**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
update fluent-plugin-elasticsearch to 3.1.0
add fluent-plugin-rewrite-tag-filter plugin
distinguish the index by namespace，be more friendly for EFK users

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The base image I'm using is debian, not debian:stretch-slim. 
**Does this PR introduce a use r-facing change?**:

```release-note
The logstash-%y%m%d index will no longer be created, otherwise the index format of <namespace>-%y%m%d will be used.
```

### CODE REVIEW

**Comment by monotek** [comment]
* Please sign the cla.
* Image tag in Makefile needs to be raised. 

I'm also not completely sure if we want this as currently used Kibana dashboards which reli on the index name would likely break. 

Opinions @coffeepac @piosz ?

**Comment by xuejipeng** [comment]
If there is only one index, then it has too many filed, and there are 150+ filed in my environment. This is painful when I check the logs, and I believe that there are not many users with only one logstash index in the production environment. more is to classify the index, At least system log and application logs should be in different indexes, I believe this will also push more people to use the namespace more standardly.

**Review by cosmo0920 — CHANGES_REQUESTED** [review]

**Comment by monotek** [comment]
@xuejipeng 
As @cosmo0920 posted a workaround i tend to close this issue ad i'd like to keep the docker image as minimal as possible.

**Comment by coffeepac** [comment]
@xuejipeng welcome and thanks for the PR!

as noted by @monotek this would be a very disruptive change for a lot of kibana users who assume the default logstash index naming format will be followed.  however, I do like the the idea of pre-pending namespace to the index name.  This will not only, as you say, help with keeping system logs separate but could also aid in general multi tenancy concerns.  

As @cosmo0920 noted, there is already a way to achieve your goal without a new plugin.  Would you be interested in converting this PR from a code change to a documentation update to talk about why using namespace as the first segment in the index is a good idea and how to alter the configmap to do it?

**Comment by xuejipeng** [comment]
@coffeepac I think your idea is perfect, and I'll add this update as a document.

**Comment by cosmo0920** [comment]
> some logs that do not have namespace will not be indexed, like docker, kernel and kubernetes components.

Oh. I didn't notice about it.
Yep, chunk_keys on buffer section expects to exist namespace within a record.
Intsead, in this situation, fluent-plugin-rewrite-tag-filter just passes through without it.

**Comment by monotek** [comment]
We could also use some prefix to workaround this problem:

`logstash_prefix logstash-${$.kubernetes.namespace_name}`

So "logstash-" would work as catchall...

Not so nice to have the "-" at the end but should work.

I'll have a look later if we can do something like setting a default if the namespace var is empty...

**Comment by desaintmartin** [comment]
Should this feature go into a comment or a paragraph in the readme? I am not sure it would fit to a majority of use cases.

**Comment by xuejipeng** [comment]
What I want is for users to have the flexibility to customize their index
I think the  fluent-plugin-rewrite-tag-filter  plugin should be added to the image and give some examples in readme or configmap to tell users how to customize the index。

**Pull request closed without merging**
