### PR TITLE
Automated cherry pick of #104991: Fix workqueue memory leak

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/104991 into release-1.22.

@hzxuzhonghu , can you cherry-pick the tests from https://github.com/kubernetes/kubernetes/pull/105031?
Can this change be cherry-picked into release-1.21 and release-1.20 as well?

/kind bug

/cc @yliaog

**Comment by hzxuzhonghu** [comment]
close in favor of #106582

**Pull request closed without merging**
