### PR TITLE
Upgrade etcd client to v3.5.16

### PR DESCRIPTION
**Pull request by serathius**
/kind cleanup
```release-note
Upgrade etcd client to v3.5.16
```
/cc @dims @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
update looks fine, verify vendor looks unhappy... maybe need to rerun?

**Comment by serathius** [comment]
./hack/update-vendor.sh doesn't fix things on my laptop :( looks like will needed to rerun it on my workstation.

**Comment by serathius** [comment]
ping @liggitt

**Pull request merged**
