### PR TITLE
Automated cherry pick of #68609: Fix potential panic when getting azure load balancer status

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #68609 on release-1.11.

#68609: Fix potential panic when getting azure load balancer status

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by jdumars** [comment]
@foxish PTAL for 1.11
/approve

**Comment by feiskyer** [comment]
ping @foxish for approval

**Review by jdumars — APPROVED** [review]

**Comment by jdumars** [comment]
@foxish any ETA on this?

**Pull request merged**
