### PR TITLE
Add completion for `kubectl config set-context`

### LINKED ISSUE #106738: Missing completion of `kubectl config set-context`
### What happened?

The `kubectl config set-context` command does not automatically complete the existing contexts.

### What did you expect to happen?

The contexts are automatically listed when the tab is pressed.

### How can we reproduce it (as minimally and precisely as possible)?

kubectl config set-context <TAB>

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T02:34:11Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kebe7jun**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add completion for `kubectl config set-context`

#### Which issue(s) this PR fixes:

Fixes #106738

#### Does this PR introduce a user-facing change?

```release-note
Add completion for `kubectl config set-context`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by marckhouzam** [comment]
I agree such completion would help users modify an existing context.  However from my understanding `kubectl config set-context` does not limit itself to existing contexts but accepts new context names as well.

I wonder if having completion of existing context may mislead users in what this command supports?  But in truth I'm still leaning towards your solution, I just wanted to mention this little point in case someone had a suggestion.

**Comment by pacoxu** [comment]
/lgtm
/priority important-longterm
/triage accepted
Fixes https://github.com/kubernetes/kubectl/issues/1161
/assign @eddiezane @soltysh 
Is there any special reason that we don't support the completion here?

**Comment by eddiezane** [comment]
Thanks for adding this!

/approve

**Pull request merged**
