### PR TITLE
bump(ugorji/go): 4a79e5b7b21e51ae8d61641bca20399b79735a32

### PR DESCRIPTION
**Pull request by liggitt**
Picks up fix for https://github.com/ugorji/go/issues/119 where `{"foo":[]}` would be decoded as `{"foo":nil}` for fast path decodes.

### CODE REVIEW

**Comment by liggitt** [comment]
@wojtek-t PTAL

**Comment by liggitt** [comment]
I could bump closer to `master`, but wanted to increment as little as possible while picking up that fix

**Comment by wojtek-t** [comment]
@liggitt - thanks for the fix.

LGTM

**Comment by liggitt** [comment]
rebased, regenerated

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
rebased, regenerated

**Comment by wojtek-t** [comment]
@liggitt can you please rebase again?

**Comment by liggitt** [comment]
I've been rebasing 2-3 times a day... I'll probably wait until this is close to the top of the queue

**Comment by liggitt** [comment]
hope springs eternal. rebased and regenerated

**Comment by wojtek-t** [comment]
@liggitt - thanks for you patience :)

**Pull request merged**
