### PR TITLE
Fix kubeadm preflight checks for existing dirs

### LINKED ISSUE #136: Error initializating kubeadm nodes with not empty dirs
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
OS: Ubuntu 16.04.01

When registering a new node into the master it fails with a non-empty dir notice:

root@node3:~t# kubeadm join --token=5e73c6.8b81f739e409b296 192.168.122.101
[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] Some fatal errors occurred:
	/var/lib/kubelet is not empty
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`

But these dirs, /var/lib/kubelet/plugins and /var/lib/kubelet/pods, are automatically created (empty) by the kubelet service as soon as it starts.

### PR DESCRIPTION
**Pull request by GheRivero**
**What this PR does / why we need it**: On some occasions, kubelet startup script will create the 'plugins' and 'pods' dirs inside /var/lib/kubelet before dying when installed. This will make the kubeadm preflight checks to fail

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes kubernetes/kubeadm#136

**Special notes for your reviewer**:

**Release note**: 

```NONE
```

### CODE REVIEW

**Comment by dgoodwin** [comment]
@GheRivero was this using a dpkg distro? Does it sound like: https://github.com/kubernetes/release/issues/171 ?

Can you verify that you're sure kubelet is terminating after launching and creating these dirs?

Slightly nervous we might be ignoring kubelet is running, and other files might slip in here and cause problems. Deleting /var/lib/kubelet seems safest to me.

**Comment by GheRivero** [comment]
Yes. It's related to that issue. I didn't see it (checked in kubernetes and kubeadm projects issues). Will add more info on that issue.

It's a dpkg installation (ubuntu 16.04) but it's kubelet the one causing the problem.

**Comment by dgoodwin** [comment]
Ok so I'm not sure this is how we should fix, to me this is a packaging bug, Debian packages should not be starting kubelet before the systemd drop-in is laid down telling it to wait for config before running.

**Comment by GheRivero** [comment]
I just reviewed all the systemd configs for debian and rpm packages, and none of them have a systemd check for the config file to exists before starting the service (ConditionPathExists=).

Will work on this approach later today as it seems the correct way to address it. Then, we can discard this PR.

**Comment by dgoodwin** [comment]
@GheRivero that would be a great solution in the kubeadm case but unfortunately we aimed to be able to install just kubelet package without kubeadm, and have it be usable including without any config file, in which case kubelet comes up with some default settings. This was why we had to do the kubeadm specific part (a kubelet argument indicating to wait for config) as a systemd drop-in rather than in the base systemd service file.

If there's a way to do ConditionPathExists and keep the above goal that would be great but I fear it means a drop-in, which would leave us in the same situation. :(

**Comment by GheRivero** [comment]
This is a first attemp to address all this: kubernetes/release#256

The  ConditionPathExists is on the systemd kubeadm drop-in, so installing the kubelet package alone has no change of behavior. 

Since, in deb distros, all packages are expanded before the postint phase, when kubeadm and kubelet are installed together, the drop-in is in place before kubelet starts.

And, looking into this, I also PRed kubernetes/kubernetes#40716 : kubeadm was trying to start the kubelet service, in the preflight phase, before generating the kubelet config file.

**Comment by GheRivero** [comment]
No need to keep this open. The origin of this issue was the dpkg workflow. 
Fixed in: kubernetes/release#256

**Pull request closed without merging**
