### PR TITLE
Rename default DNS domain to cluster.local

### PR DESCRIPTION
**Pull request by thockin**
This is WIP - still bringing up a cluster and need to run e2e

### CODE REVIEW

**Comment by thockin** [comment]
@smarterclayton @vishh

**Comment by smarterclayton** [comment]
LGTM barring e2e

**Comment by vishh** [comment]
Question: Why do we have two segments, "cluster" and "local"?

**Comment by thockin** [comment]
A trailing .local is reserved in DNS for link-local usage.  We would not want to repeat the same mistake we make with services and not carve out a namespace for ourselves.  kubernetes.local is unambiguously reserved.  cluster.local is a bit more ambiguous, but maybe not egregiously so.

Still, you would not want mysvc.myns.svc.local because we'd be polluting the top-level namespace.

I'm open to something less generic than cluster, if people feel strongly.  The reason I didn't use that at the beginning was the genericness.

kcluster.local ?

kluster.local ?

k8s.local ?

ctr-cluster.local ?

container-cluster.local ?

**Comment by thockin** [comment]
BTW e2e passed:

Ran 38 of 43 Specs in 1453.988 seconds
SUCCESS! -- 38 Passed | 0 Failed | 1 Pending | 4 Skipped I0512 09:36:14.223586   18027 driver.go:96] All tests pass

**Comment by thockin** [comment]
I kind of like kluster.local  but it's still kubernetes centric

**Comment by vishh** [comment]
Talked to @thockin offline. "cluster.local" SGTM.

**Comment by vishh** [comment]
Tim, is this safe to merge?

**Comment by thockin** [comment]
If everyone is OK with "cluster" as opposed to "kluster" or something
else.  Merge at will.

**Comment by brendandburns** [comment]
I'm pretty sure this broke GKE e2e...  (not sure why) paging @roberthbailey

**Comment by roberthbailey** [comment]
Investigating...

**Pull request merged**
