### PR TITLE
Promote v1alpha1 meta to v1beta1

### LINKED ISSUE #53224: Promote alternate API representations to beta
This is to track a discussion around promoting alternate API resource representations (https://github.com/kubernetes/kubernetes/pull/33900, https://github.com/kubernetes/community/pull/123) to beta. More specifically, the `PartialObjectMetadata` type via `Accept` header media type parameters is important for:

* Garbage collector optimization (https://github.com/kubernetes/kubernetes/issues/49718, https://github.com/kubernetes/kubernetes/issues/30180)
* Efficient object count quota support (https://trello.com/c/ayBfZlz8, Kubernetes issue forthcoming)

It's not entirely clear to me if there's a single PR, issue, or commit to reference in service of the promotion, so I've collected a list of what I think are relevant historical links:

* https://github.com/kubernetes/kubernetes/pull/44685
* https://github.com/kubernetes/community/pull/363
* https://github.com/kubernetes/kubernetes/commit/f203e42cb98ed4bac7ad8ebbed717d3bd42f55b6
* https://github.com/kubernetes/kubernetes/pull/40848

/kind feature
@kubernetes/sig-api-machinery-feature-requests

### PR DESCRIPTION
**Pull request by smarterclayton**
No code changes, just renames. We can discuss if there are any field / naming changes here or in a follow-up

Parent #58536
Fixes #53224
Prereq to #55637

@kubernetes/sig-api-machinery-pr-reviews @deads2k

```release-note
The `meta.k8s.io/v1alpha1` objects for retrieving tabular responses from the server (`Table`) or fetching just the `ObjectMeta` for an object (as `PartialObjectMetadata`) are now beta as part of `meta.k8s.io/v1beta1`.  Clients may request alternate representations of normal Kubernetes objects by passing an `Accept` header like `application/json;as=Table;g=meta.k8s.io;v=v1beta1` or `application/json;as=PartialObjectMetadata;g=meta.k8s.io;v1=v1beta1`.  Older servers will ignore this representation or return an error if it is not available.  Clients may request fallback to the normal object by adding a non-qualified mime-type to their `Accept` header like `application/json` - the server will then respond with either the alternate representation if it is supported or the fallback mime-type which is the normal object response.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
I expect any bugs / gaps to be identified by #55637 and subsequent changes.

**Comment by deads2k** [comment]
Looks like a straight sed.  You don't want to keep the alpha level too for an easier transition for clients?

**Comment by smarterclayton** [comment]
Figure that we're going to kill it anyway this release, so it was easier to
completely move.

**Comment by sttts** [comment]
sgtm

**Pull request merged**
