### PR TITLE
Bumping up etcd dep to fix data race

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: https://github.com/kubernetes/kubernetes/pull/23694

What this PR does
- Bumping up the godep of etcd to fix data race in etcd watcher.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
It seemed like etcd master dropped support for go 1.4 and adds some http2 related things.
We will try to fix and update it again.

**Comment by eparis** [comment]
I assigned the PR to you. You should 'unassign' the PR when you are ready. Or ping me/re-assign to me.

**Comment by hongchaodeng** [comment]
Blocked on #22149

**Comment by hongchaodeng** [comment]
Rebased after the merged Go 1.6 PR.
I'm just bumping up the godep of etcd. But I'm adding the watcher commit here to test if the data race is fixed. Will remove it after the build pass.

/cc @wojtek-t @gmarek @xiang90

**Comment by gmarek** [comment]
@hongchaodeng please squash commits.

**Comment by ixdy** [comment]
Should probably be explicitly noted somewhere that this PR ratchets us into Go 1.6+, assuming I'm understanding correctly.

**Comment by Random-Liu** [comment]
This PR build failed because
```
Godeps/_workspace/src/github.com/coreos/etcd/client/cancelreq.go:13: req.Cancel undefined (type *http.Request has no field or method Cancel)
```
The `Cancel` field is added after go 1.5 (See [here](https://github.com/golang/go/blob/release-branch.go1.5/src/net/http/request.go#L233)), while it's not there in go 1.4 (See [here](https://github.com/golang/go/blob/release-branch.go1.4/src/net/http/request.go#L228)).

**Comment by ixdy** [comment]
OK, though due to #20656 Kubernetes basically doesn't support go 1.5.

**Comment by ixdy** [comment]
My basic worry is thus: we just merged the Go 1.6 PR yesterday, and we've been seeing some failures in CI that we can't fully explain away yet. I'm hesitant to lock us into Go 1.5+ until we're sure that things are not broken and we're not going to roll back.

cc @kubernetes/goog-testing

**Comment by hongchaodeng** [comment]
Closing this to transfer discussion to #23915.

Once go version is resolved, will open up another PR.

**Comment by wojtek-t** [comment]
@ixdy - one point from me about Go 1.6 to note - we don't observe any performance issues with it, so from performance perspective the upgrade is fine.

**Comment by ixdy** [comment]
all Google-run Jenkins VMs should be using Go 1.6 now.

**Pull request closed without merging**
