### PR TITLE
Fix shellcheck failures in test/cmd

### PR DESCRIPTION
**Pull request by xychu**
Including files after test/cmd/n*

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Part of #72956
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This is a follow-up pr of #74639 and it is part of fixes under test/cmd/*.sh
**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by xychu** [comment]
@BenTheElder thanks for your quick review, and seems need the `ok-to-test` label to rerun the failed test.

**Pull request merged**
