### PR TITLE
Changed all links in initial-resources proposal to be relative

### PR DESCRIPTION
**Pull request by piosz**
As @bgrant0607 requested in https://github.com/kubernetes/kubernetes/pull/12472/files#r38141323

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by bgrant0607** [comment]
Please review the whole doc. I'm not going to point out every instance.

**Comment by piosz** [comment]
@bgrant0607 I explained in https://github.com/kubernetes/kubernetes/pull/12472/files#r38183381 why I'm changing only this instance:
>The reason why I don't use relative link in lines 42, 50, 55 is that the links point to specific lines in the code in other documents. The content of those lines will probably change many times so that it's hard to guarantee that they will point to what I originally wanted.

If you think I should also change mentioned lines I'm happy to do it.

**Comment by bgrant0607** [comment]
For the types.go link:

You could help to update the design doc and reference the appropriate subsection instead, using a relative link:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md#resource-specifications

At least update the org from GoogleCloudPlatform to kubernetes in all links.

**Comment by wojtek-t** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Pull request merged**
