### PR TITLE
Automated cherry pick of #67691: Bump versions of components with latest security patches.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #67691 on release-1.10.

#67691: Bump versions of components with latest security patches.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@loburm Who would be the right reviewer for this? Since those are security fixes I'd really like this merged in time for 1.10.8.

**Comment by piosz** [comment]
/approve

Please find a reviewer.

**Comment by MaciekPytel** [comment]
@mikedanese You've reviewed #67691, can you review this one as well? Since this is a security fix I'd really like to get it in 1.10.8, which is planned for Wednesday. Ideally it should merge today, so there is enough time to get a few serial tests runs before release.

**Pull request merged**
