### PR TITLE
Adding logging and fix test race

### PR DESCRIPTION
**Pull request by bprashanth**
Fixes https://github.com/kubernetes/kubernetes/issues/31552, adds clarity for https://github.com/kubernetes/kubernetes/issues/29449

Janet for the job e2e and girish for services. P1 for flake.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31923)

### CODE REVIEW

**Comment by girishkalele** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by girishkalele** [comment]
Reviewed 1 of 3 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by girishkalele** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/controller/endpoint/endpoints_controller.go, line 437 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923#-KQbxc_8UxVgBnbnRIen:-KQbxc_9exYi9AownvVS:b4lj1zc) ([raw file](https://github.com/kubernetes/kubernetes/blob/5dac1122b48ec4b5f4efa965d016a8de100a8223/pkg/controller/endpoint/endpoints_controller.go#L437)):*
> ```Go
> 					Ports:     []api.EndpointPort{epp},
> 				})
> 				readyEps++
> ```

This if case is for both tolerateUnready and isReady cases - do you want the readyEps to be incremented in both cases ?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by girishkalele** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by bprashanth** [comment]
*[pkg/controller/endpoint/endpoints_controller.go, line 437 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923#-KQbxc_8UxVgBnbnRIen:-KQbydkixogqD8nmoS21:b-z3tbb7) ([raw file](https://github.com/kubernetes/kubernetes/blob/5dac1122b48ec4b5f4efa965d016a8de100a8223/pkg/controller/endpoint/endpoints_controller.go#L437)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> This if case is for both tolerateUnready and isReady cases - do you want the readyEps to be incremented in both cases ?
</details>
Yeah, with tolerateUnredy it'll show up as an ep without even passing the probe. I just want a count of the endpoints that show up in something like kubectl get ep, to know if the ep_controller is slow to update the list when apiserver restarts

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by girishkalele** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923)*

**Comment by girishkalele** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31923#-:-KQc-yYex2NFEsV6bJjS:bnfp4nl)*

**Comment by bprashanth** [comment]
Did you mean to apply the lgtm label or are you waiting for Janet to do a pass?

**Comment by girishkalele** [comment]
I don't know when/why Reviewable will apply the Github LGTM label (or maybe it never can ?).

@janetkuo LGTM to me, would you like me to LGTM it ?

**Comment by janetkuo** [comment]
LGTM as well.

**Pull request merged**
