### PR TITLE
publishing-bot rules for the new release-1.27 branch

### LINKED ISSUE #116912: Go modules are not tagged for v0.27.0-rc.0
### What happened?

After https://github.com/kubernetes/kubernetes/releases/tag/v1.27.0-rc.0 release, Go modules are not tagged for 0.27.0-rc.0.

See e.g. https://pkg.go.dev/k8s.io/api@v0.27.0-beta.0?tab=versions

### What did you expect to happen?

Go modules to be tagged with the release

### How can we reproduce it (as minimally and precisely as possible)?

```
$ go get k8s.io/api@0.27.0-rc.0
go: k8s.io/api@v0.27.0-rc.0: reading k8s.io/api/go.mod at revision v0.27.0-rc.0: unknown revision v0.27.0-rc.0
```

### Anything else we need to know?

See also #113951, #109565

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dims**
Duh! someone missed a step. We need these rules populated when we cut a new branch.

/kind bug

#### Which issue(s) this PR fixes:

Fixes #116912

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
was this generated with the rules tool? I remember we did this by hand for 1.26 and messed it up a little

**Comment by cici37** [comment]
Thank you @dims ! We plan to do it today and you beat us on speed^^ 
cc @gracenng @ramrodo 
/lgtm
/approve

**Comment by dims** [comment]
> was this generated with the rules tool? I remember we did this by hand for 1.26 and messed it up a little

yep i tried a bit by hand, it was getting hard :) then used 

```
_output/update-rules -branch release-1.27 -go 1.20.2 -o /tmp/rules.yaml -rules /Users/davanum/go/src/k8s.io/kubernetes/staging/publishing/rules.yaml
```

**Comment by cici37** [comment]
Just fyi we also have `docker run -t gcr.io/k8s-staging-publishing-bot/publishing-bot:latest /update-rules` for such work. :)
/lgtm

**Pull request merged**
