### PR TITLE
Release 1.2 cherry pick batch

### PR DESCRIPTION
**Pull request by eparis**
Cherry picks! Cherry picks!
#21899: Bump Spark / Zeppelin to 1.5.2 / 0.5.6 tags
#22940: Heapster sizing adjustments
#22746: add user-agent defaulting for discovery
#22956: Generate API docs for new groups
#22951: Reduce namespace deletion test flakes
#22959: Conformance Test for DNS
#22899: AWS e2e: don't try to build a full cloudprovider in e2e
#22958: test kubectl run with default args
#22971: Trusty: Fix node kubelet pod-cidr flag
#22989: Fix non-masquerade CIDR
#22942: Allow up to 39 PVs attached to AWS node
#22969: Disable kubectl validation for upgrade e2e
#22993: Bumped Heapster to stable version 1.0.0
#22948: Separate GetOldRS and GetNewRS in deployment controller (get and mutate) and deployment util (get only)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. Will merge once tests pass.

**Comment by eparis** [comment]
I self LGTM and will let the submit-queue do it, if brian doesn't come back first.

**Comment by bgrant0607** [comment]
Thanks, yes, LGTM

**Comment by bgrant0607** [comment]
Merging

**Comment by bgrant0607** [comment]
@eparis Any idea why the cherrypick labels were only removed from about half of the PRs?

**Comment by eparis** [comment]
no....

**Comment by eparis** [comment]
but I'm going to do some testing on https://github.com/kubernetes/kubernetes/pull/22942

**Comment by eparis** [comment]
I think they didn't get unlabeled because they didn't get picked!  It seems like I missed somehow (not sure how scripts can miss)

#22989: Fix non-masquerade CIDR
#22942: Allow up to 39 PVs attached to AWS node
#22969: Disable kubectl validation for upgrade e2e
#22993: Bumped Heapster to stable version 1.0.0
#22948: Separate GetOldRS and GetNewRS in deployment controller (get and mutate) and deployment util (get only)

So incoming with another PR

**Pull request merged**
