### PR TITLE
Merge pull request #46101 from sttts/sttts-crd-core-names

### PR DESCRIPTION
**Pull request by PengTaoWW**
https://github.com/kubernetes/kubernetes/issues/46321

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@PengTaoWW It seems like there was something wrong with your git operations. Could you please change the PR title and git message and clean up your commit?

And it would be better to split your own commit into two, one with manually modified files and one with auto generated files. Then it will make the PR easy to review.

**Comment by PengTaoWW** [comment]
@xiangpengzhao ok I will submit a version that does not contain the auto-generated code

**Comment by xiangpengzhao** [comment]
@PengTaoWW okay:) To be clear, I meant one PR with two commits, one with manually modified files and one with auto generated files.

**Comment by PengTaoWW** [comment]
@xiangpengzhao 
 I follow this document
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
in git commit will run hook ，hook can auto-generated some code
can i miss hook to submit?

**Comment by xiangpengzhao** [comment]
IMO, you can skip the pre-commit hook. K8S CI will verify and test your PR. It covers all the checks in pre-commit. Of course, if you run pre-commit hook, it will help you check your fix in your local dev env, such as gofmt.

**Comment by yujuhong** [comment]
Closing this PR in favor of #46426

**Pull request closed without merging**
