### PR TITLE
Cherrypick #95981 to 1.19, Enables HTTP/2 health check

### PR DESCRIPTION
**Pull request by caesarxuchao**
Manually cherrypicking #95981 and #96549, per https://github.com/kubernetes/kubernetes/pull/95981#issuecomment-730571182.

#96549 updated two vendored modules, so I manually ran the hack/pin-dependency.sh and the hack/update-vendor.sh instead of cherrypicking the commit.

/kind bug
/sig api-machinery
/assign @lavalamp @liggitt 

```release-note
HTTP/2 connection health check is enabled by default in all Kubernetes clients. The feature should work out-of-the-box. If needed, users can tune the feature via the HTTP2_READ_IDLE_TIMEOUT_SECONDS and HTTP2_PING_TIMEOUT_SECONDS environment variables. The feature is disabled if HTTP2_READ_IDLE_TIMEOUT_SECONDS is set to 0.
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@cpanato can you approve the cherry pick? Thank you.

**Comment by Nebulazhang** [comment]
Hi, we also meet this issue in out cluster (1.16.8),so we want cherry-pick and fix it. But why we both need #96549 and  #95981?  If we only cherry-pick #95981 , has any problem?

**Pull request merged**
