### PR TITLE
Fix transient flannel etcd

### LINKED ISSUE #26062: Docker failed to start on 1500/2000 machines on flannel cluster
The reason is a crashloop with the error:
```
time="2016-05-23T10:44:11.175272386Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually"
```

If I'm not mistaken `cbr0` should have been created by Kubelet.

@kubernetes/sig-node @dchen1107

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #26062

@bprashanth

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot test this issue: #26131

**Comment by gmarek** [comment]
AFAICT it's working - I successfully started 1000 Node flannel cluster. Flannel's etcd is crashlooping though, but at least one of the problems is fixed.

**Comment by wojtek-t** [comment]
Something doesn't work for me - I will take a look and get back here.

**Comment by wojtek-t** [comment]
OK - that was a different issue that I faced.

It seems to work correctly with this change.

@gmarek - please take a look

**Comment by bprashanth** [comment]
I'm fine with this, but emptydir should give you an anon volume that doesn't change for the life of a pod. More specifically, if you have a pod with uid=foo, you will get a host path of: `/var/lib/kubelet/pods/foo/volumes/kubernetes.io~empty-dir/` for your emptydir. If this changed mid-way then something unexpected has happened (pod changed uid, machine rebooted etc). Did anything like this occur?

**Comment by wojtek-t** [comment]
@bprashanth - definitely machine was ok for the whole time (no reboots, failures, etc.)
Regarding changing of the pod uid - I think it didn't change, because the whole pod was alive for the whole time - we were only restarting the etcd container because of some reasons.

But clearly etcd lost its data...

**Pull request merged**
