### PR TITLE
Make generated build tag parameterizable for go2idl

### PR DESCRIPTION
**Pull request by smarterclayton**
Downstream generators that want to reuse the upstream generated types
need to be able to define a different ignore tag (so that they can see
the already generated types).

@wojtek-t allows third parties to reuse conversions in api/v1 (for instance) because otherwise they are hidden when go2idl parses the dependency packages.

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks @smarterclayton ! However, please fix verify:

Verifying ./hack/../hack/verify-flags-underscore.py
Found flags in golang files not in the list of known flags. Please add these to hack/verify-flags/known-flags.txt
build-tag
FAILED   ./hack/../hack/verify-flags-underscore.py

**Comment by smarterclayton** [comment]
Sigh, I always forget about that one.

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by smarterclayton** [comment]
Fixes #27918

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Comment by smarterclayton** [comment]
Found two bugs while testing this - not using the generated build tag name in header of each file, and we were improperly ignoring public conversion functions.

I also noticed that set gen creates types that are inefficiently copied (the `Empty struct{}` confuses map copy), but I'll file a follow up for that.

**Comment by smarterclayton** [comment]
Needs re-review

**Comment by wojtek-t** [comment]
@smarterclayton - sorry, was on vacation; looking now.

**Comment by wojtek-t** [comment]
lgtm

**Pull request merged**
