### PR TITLE
Fix typo in command_headers_test.go

### PR DESCRIPTION
**Pull request by eltociear**
#### What type of PR is this?

Typo fixed.

```
propogated -> propagated
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
Thanks for catching this!
/lgtm

**Comment by soltysh** [comment]
/close
Appreciate your diligence, but I'd prefer this is fixed alongside other bits in this file.

**Pull request closed without merging**
