### PR TITLE
Dump Windows version information during cluster bringup.

### PR DESCRIPTION
**Pull request by pjh**
/kind cleanup

Dumps Windows version information as Windows nodes are joined to clusters running in GCE.

Example output in Windows VM's serial log:
```
Windows version:

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

Installed hotfixes:

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
KUBERNETES... Update           KB4483452     NT AUTHORITY\SYSTEM  2/26/2019 12:00:00 AM
KUBERNETES... Security Update  KB4470788     NT AUTHORITY\SYSTEM  2/26/2019 12:00:00 AM
KUBERNETES... Security Update  KB4487044     NT AUTHORITY\SYSTEM  2/26/2019 12:00:00 AM
```

```release-note
NONE
```

### CODE REVIEW

**Comment by pjh** [comment]
Updated to also dump the GCE Windows image name, which requires fetching a special value from the metadata server.

**Comment by yujuhong** [comment]
/lgtm
/approve
Thanks!

**Comment by pjh** [comment]
/retest

pull-kubernetes-e2e-gce-100-performance failed because of this unrelated kube-up.sh failure:
W0301 02:01:28.407]  - The resource 'projects/k8s-presubmit-scale/zones/us-east1-b/instances/e2e-74762-95a39-master' was not found

pull-kubernetes-e2e-gce seems to have hit a few different failures, none obviously connected to this PR.

**Pull request merged**
