### PR TITLE
Automated cherry pick of #16894

### PR DESCRIPTION
**Pull request by alexhersh**
Cherry pick of #16894 on release-1.1.

### CODE REVIEW

**Comment by yujuhong** [comment]
Uh..you need to change the imported package name.

```
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1344: undefined: kubepod
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/runonce.go:118: undefined: kubetypes
```

**Comment by alexhersh** [comment]
Yep taken care of. (I think)

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@alexhersh - it seems that this doesn't compile correctly:

    06:14:43 _output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:256: too many arguments in call to WaitFor

Can you please fix it?

**Comment by yujuhong** [comment]
@wojtek-t, this PR doesn't touch pkg/util/wait at all. I think the release-1.1 branch is broken. You can see similar failures in other cherry-pick PRs too, e.g., #17712

**Comment by yujuhong** [comment]
Fix is underway #17693

**Comment by wojtek-t** [comment]
@yujuhong - ok thanks

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by alexhersh** [comment]
Thank you all for pushing this through!

**Pull request merged**
