### PR TITLE
Add a timeout to waitForPodRunning

### PR DESCRIPTION
**Pull request by zmerlynn**
- Add a timeout, convert the function to return an error (which gives
  a reasonable status message for callers).
- Start converting glog to By.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @filbranden @satnam6502

**Comment by satnam6502** [comment]
Great! I look forward to getting insight into what is happening during these timeouts.

**Comment by satnam6502** [comment]
Our rule is to not merge during the weekend for various reasons. I wonder if it is worth making an exception for fixes to the e2e test framework because:
* We should not be merging code during the weekend anyway...
* Working on e2e improvements which can be disruptive can be done with lower impact...
* We can monitor and understand the effect of e2e changes without other interference.

**Comment by zmerlynn** [comment]
I'm somewhat torn on that policy question. On the one hand, I would've loved to see this go in to see what the bullets would be like when I looked this morning. OTOH, I've had the shit hit the fan too many times when I did something wrong with e2es.

My suspicion is that you're about to see several tests go unstable with a 60s timeout. I may be a little ungenerous at a minute. Personally, though, I think we need to rewrite the tests (use less beefy images to pull, for instance) if that can't be the case, though, because a minute to schedule a pod is an eternity.

So yeah ... I think I'm fine with people merging test infrastructure stuff on a weekend *with a caveat*: I think the burden of ownership suddenly shifts to the merger. The PR writer isn't necessarily expecting it.

**Comment by zmerlynn** [comment]
Actually, after a few more runs, my local e2es are a bit too flaky even for my taste with one minute. I'm going to bump this to 5m and we'll fight the good fight later.

**Comment by zmerlynn** [comment]
I'm self-merging on LGTM. We're in the pipe, 5x5 now :)

**Pull request merged**
