### PR TITLE
Automated cherry pick of #95971: E2E stress test suite for VolumeSnapshots

### PR DESCRIPTION
**Pull request by annapendleton**
Cherry pick of #95971 on release-1.19.

#95971: E2E stress test suite for VolumeSnapshots

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/approve

This is backporting only optional e2es for increased test coverage.

**Comment by cpanato** [comment]
/hold for discussions

This looks like adding a new feature, but it is for the testing part.
I did not see but this is not adding as conformance tests, right? @annapendleton @msau42 


I think this might be good to cherry pick, but I would like to hear other comments from @kubernetes/release-managers @saschagrunert @hasheddan

**Comment by annapendleton** [comment]
@cpanato correct, no new conformance tests are added. This change is adding optional testing on a pre-existing feature.

**Comment by msau42** [comment]
We asked about this in the slack channel and got OK from release managers since this is test-only, non-blocking, and non-conformance: https://app.slack.com/client/T09NY5SBT/C2C40FMNF/thread/C2C40FMNF-1607720902.163600

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
