### PR TITLE
add options for EmptyDirVolumeSource to enable set size for medium of…

### PR DESCRIPTION
**Pull request by ailusazh**
**What this PR does / why we need it**:
Enable set size for memory medium of emptydir.
For example, we set memory size to 3G when creating a pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: centos6.6
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: ram-disk
      mountPath: /export/ram
  volumes:
  - name: ram-disk
    emptyDir:
      medium: "Memory"
      options:
        size: "3G"
```
When the container becomes running, execute the command of ”df -lh“ in the container, then the result will be like this:
```shell
[root@test /]# df -lh
Filesystem      Size  Used Avail Use% Mounted on
                        .
                        .
                        .
tmpfs           3.0G     0  3.0G   0% /export/ram
                        .
                        .
                        .
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This will be useful in production environment,  otherwise it can only be set to the default value: half of the physical machine memory.
Actually only three files were modified, pkg/api/types.go, pkg/api/v1/types.go, pkg/volume/empty_dir/empty_dir.go, others were automatically updated.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by deads2k** [comment]
@kubernetes/sig-storage-api-reviews @kubernetes/sig-storage-feature-requests Is this a new feature you are talking about?

**Comment by vishh** [comment]
@jingxu97 is already working on adding `Limits` for emptydir volumes

**Comment by jingxu97** [comment]
@ailusazh thank you very much for your PR. Right now we are adding a new API field "sizeLimit" in emptyDir to set the limit for storage. For  memory medium of emptydir case, @vishh also has a PR doing the same thing. So the feature implemented here will be available after API change #44785 and mount option change in PR #43823 get merged. Please let us know if you have any questions/comments

**Comment by ailusazh** [comment]
@vishh @jingxu97 ok, thank you for informing, just ignore this pr.

**Pull request closed without merging**
