### PR TITLE
PDB checks should not be done for terminal pods while evicting

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Signed-off-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>

**What this PR does / why we need it**:
As of now, while evicting terminal pods, we are checking pod disruption budgets for them where as we don't need to check pdbs for them as they already have caused disruption.
/cc @derekwaynecarr 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Pod disruption budgets shouldn't be checked for terminal pods while evicting
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@ravisantoshgudimetla thank you for following up on this!

/lgtm

**Comment by deads2k** [comment]
/approve

This can prevent draining, but I don't think it is a regression (@ravisantoshgudimetla correct me if I'm mistaken).  We should backport for 1.12.1.

**Review by bsalamat — APPROVED** [review]
I am fine with this change. We must also ensure that the caller which requests the eviction checks the status of the pod and not request it for terminated pods.

/lgtm

**Pull request merged**
