### PR TITLE
code Optimization and remove unused code 

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
1、code Optimization
2、remove unused function.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
cc @kubernetes/sig-cli-maintainers 

/unassign

**Comment by stewart-yu** [comment]
cc @sig-cli-maintainers

**Pull request closed without merging**
