### PR TITLE
fix the anchor link

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
fix the anchor links about "kubectl rolling-update" and "kubectl delete", they did not work at present.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/lgtm
/release-note-none

**Comment by thockin** [comment]
@k8s-bot cvm gce e2e test this

**Comment by cblecker** [comment]
Commenting to drop from PR dashboard.

**Pull request merged**
