### PR TITLE
Include nltest in the windows busybox image

### LINKED ISSUE #99669: [sig-windows] [Feature:Windows] GMSA Kubelet [Slow] kubelet GMSA support when creating a pod with correct GMSA credential specs passes the credential specs down to the Pod's containers
#### Which jobs are failing:
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-staging-serial-slow
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-containerd-serial-slow

#### Which test(s) are failing:
[sig-windows]  [Feature:Windows] GMSA Kubelet [Slow] kubelet GMSA support when creating a pod with correct GMSA credential specs passes the credential specs down to the Pod's containers

[sig-windows] [Feature:Windows] GMSA Full [Serial] [Slow] GMSA support works end to end
****

#### Reason for failure:
pause image using in image was transitioned to the official pause image which no longer has nltest.exe in the image

#### Anything else we need to know:

related to #99363

/sig windows
/triage accepted

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
Includes nltest.exe in the Windows busybox image for failing tests:

https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-staging-serial-slow
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-containerd-serial-slow

#### Which issue(s) this PR fixes:

Fixes #99669 #99363

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows
/triage accepted 

/cc @chewong @claudiubelu

### CODE REVIEW

**Review by chewong — CHANGES_REQUESTED** [review]
Could you bump the image version from 1.29 to something like 1.29-1 in:
- `test/images/busybox/VERSION`
- `test/images/busybox/Dockerfile`
- `test/images/busybox/Dockerfile_windows`

**Comment by claudiubelu** [comment]
I've tried this PR as well, nltest.exe seems to be working: https://paste.ubuntu.com/p/Ryf46dF5Db/

**Pull request merged**
