### PR TITLE
Kube-proxy cleanups

### PR DESCRIPTION
**Pull request by thockin**
Add comments.

Clarify flag help.

Rename ExternalTrafficPolicy from "Global" to "Cluster", to not imply federation tie-ins.

Release Note:
```release-note
When switching from the `service.beta.kubernetes.io/external-traffic` annotation to the new
`externalTrafficPolicy` field, the values chnag as follows:
  * "OnlyLocal" becomes "Local"
  * "Global" becomes "Cluster".
```

### CODE REVIEW

**Comment by thockin** [comment]
@MrHohn do we have real docs on traffic policy?

**Comment by MrHohn** [comment]
> @mrhohn do we have real docs on traffic policy?
 
No yet, all existing docs is about beta annotations. I will be soon working on updating those docs to reflect the new fields.

**Review by MrHohn — APPROVED** [review]

**Comment by MrHohn** [comment]
LGTM, please run below scripts :)
- hack/update-federation-openapi-spec.sh
- hack/update-federation-swagger-spec.sh
- hack/update-staging-client-go.sh
- hack/update-swagger-spec.sh

**Comment by thockin** [comment]
re-pushed, self-lgtm

**Comment by MrHohn** [comment]
pull-verify job is still complaining :)
```
/go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
```

**Comment by MrHohn** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

/lgtm

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by MrHohn** [comment]
This is weird, validation.go is already updated to use "Cluster" instead of "Global" in PR, but from the test failures we could still see "Global" is inused:
```
E0602 09:57:08.854925       1 servicecontroller.go:518] Failed to execute updates for e2e-tests-federated-service-tgk83/federated-service: Service "federated-service" is invalid: spec.externalTrafficPolicy: Invalid value: "Cluster": ExternalTrafficPolicy must be empty, Global or Local
```

Triggering test again to verify.

@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shashidharatd** [comment]
@MrHohn, maybe the already deployed k8s clusters are not updated with the change you are mentioning. probably will be fixed after federation k8s clusters are recycled.

**Comment by MrHohn** [comment]
@shashidharatd Thanks, I see the problem now. The changes I mentioned are made in this PR, so they will never be deployed to federation clusters for testing if this PR is not in yet...

**Comment by MrHohn** [comment]
Wouldn't this model (_existing clusters_ v.s. _updated federation server_) block all this kind of changes?

**Comment by shashidharatd** [comment]
Yes that's a problem we need to address.
For now federation pre-submit will be made merge non-blocking soon and these kind of changes can ignore the test failures.

cc @madhusudancs, @csbell

**Comment by madhusudancs** [comment]
@MrHohn @shashidharatd federation presubmits won't be made non-blocking for now. We need to figure out what to do for PRs like this. Let me think. I am fine manually merging this PR for now.

**Comment by thockin** [comment]
OK, I will manually merge this.

**Comment by madhusudancs** [comment]
@thockin thanks!

**Pull request merged**
