### PR TITLE
Subtract inactive_file from usage when setting memcg threshold

### LINKED ISSUE #51745: Memory Eviction Memcg notifications are not effective.
While debugging https://github.com/kubernetes/kubernetes/issues/51717#issuecomment-326433510, we found that despite memcg notifications waking up the eviction manager, the eviction manager was unable to take action before a system oom ~6 seconds later.  The following sequence of events occurred:
1. Memory threshold crossed.
2. Memcg notifications triggers synchronize call in eviction manager
3. Eviction manager gets summary stats (~10 seconds old)
4. Eviction manager determines there is no pressure (because stats are old)
5. Repeat steps 1-4 a couple times (for ~6 seconds)
6. System OOM

cc @derekwaynecarr @sjenning @dchen1107 @vishh @yguo0905 
/sig-node

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
Implements solution for #51745, proposed in  https://github.com/kubernetes/community/pull/1451.
This is a prerequisite to fixing https://github.com/kubernetes/kubernetes/issues/57901.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #51745

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```
/sig node
/priority important-longterm
/kind bug

/assign @sjenning @derekwaynecarr @dchen1107

### CODE REVIEW

**Comment by dashpole** [comment]
This can wait until after code freeze, and should give it plenty of time to soak before 1.11

**Comment by dashpole** [comment]
I changed this PR to implement the stop channel separately, because calling close() multiple times on the same channel can cause a panic (which could happen in the previous implementation).  The new implementation uses sync.Once to ensure close() is only called once.

**Comment by sjenning** [comment]
This PR does a lot more than the title suggests.  Can you break out the stopch plumbing into a separate PR?  Or a least a separate commit?

**Comment by dashpole** [comment]
@sjenning sure

**Comment by dashpole** [comment]
@sjenning done.  The first commit deals with the stop channel implementation, and makes the eviction manager refresh the threshold at most every 10 seconds.
The second commit actually makes the change to how we set the threshold.

The reason we need the extra stop channel implementation is because we need to ensure close() is only called once (using a sync.Once) on the channel.  Otherwise the eviction manager could panic in a rare race condition.  An alternative to the `InitialStopCh` would be to simply close the initial stop channel immediately, but this seemed cleaner.

**Comment by dashpole** [comment]
Thinking about this a bit more, I think there is still an issue with the current implementation.  We can race creating the next ThresholdStopCh, meaning we will leak memcg threshold notifiers over time.  I'll work on a solution to this next week.

**Comment by derekwaynecarr** [comment]
@dashpole poke when you are ready for a review.

**Comment by dashpole** [comment]
this is ready for review

**Comment by derekwaynecarr** [comment]
the changes look good, lets merge this early in 1.11

**Comment by ddongchen** [comment]
If there are much pages in "inactive_file" state, is there possible that "memcgThreshold.Add(*inactiveFile)" is bigger than “limit”, that's “memory.usage_in_bytes” can never exceed.
inactiveFile :=summary.Node.Memory.UsageBytes - summary.Node.Memory.WorkingSetBytes
capacity := summary.Node.Memory.AvailableBytes + summary.Node.Memory.WorkingSetBytes
memcgThreshold := capacity.DeepCopy()
memcgThreshold = memcgThreshold - evictionThresholdQuantity
                             = summary.Node.Memory.AvailableBytes + summary.Node.Memory.WorkingSetBytes
                                 - evictionThresholdQuantity
memcgThreshold = memcgThreshold + inactiveFile
                             =  summary.Node.Memory.AvailableBytes + summary.Node.Memory.WorkingSetBytes 
                                 - evictionThresholdQuantity + summary.Node.Memory.UsageBytes 
                                 - summary.Node.Memory.WorkingSetBytes
                            = summary.Node.Memory.AvailableBytes + summary.Node.Memory.UsageBytes 
                               - evictionThresholdQuantity 
Both "summary.Node.Memory.UsageBytes" and "summary.Node.Memory.AvailableBytes" are including "inactive_file", so it's possible that the "memcgThreshold" is too high, and the "memory.usage_in_bytes" can never exceed

**Comment by dashpole** [comment]
@ddongchen that is true.  The fact that inactive_file is so high means that there is likely plenty of evictable memory for the kernel to reclaim, making an OOM unlikely.  

As an optimization, we could set it to something reasonable (limit - threshold /2) or something.  But other than extremely sudden large memory spikes, this should catch most OOMs.

**Comment by ddongchen** [comment]
If there is plenty of evictable memory,  I think is less useful for watching the event signal form "memory.usage_in_bytes".  

Should we watch the signal from "memory.oom_control"(disable oom for memory cgroup), besides we have set the "memory.limit_in_bytes" for "memory/kubepods".

If we have watched the oom event, we could increase "memory.limit_in_bytes" for temporary, and trigger the eviction manager. After evicting the pod, we recover the "memory.limit_in_bytes".

**Comment by dashpole** [comment]
This is catching system-level OOMs, so we can't change the limit.  I don't think we can trust the kubelet to be available to respond.  We need the OOMKiller as a backup in the case where the kubelet is unresponsive, down, etc.

**Comment by ddongchen** [comment]
Yes，I agree that we can not trust the kubelet to be available to respond from cgroup event. While it could provide us an extension way to notify that there may be less memory, and the eviction controller will have a check.

**Comment by ddongchen** [comment]
I signed it!

**Pull request merged**
