### PR TITLE
Revert "slice mirroring controller mirror annotations"

### PR DESCRIPTION
**Pull request by aojea**
The integration test is flake

This reverts commit c421e22e2c6aa4d3fbe3abd7feb0035361539d22.

/kind flake
/release-note none
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
```
go test -count 30  ./test/integration/endpointslice -run TestEndpointSliceMirroringUpdates
ok      k8s.io/kubernetes/test/integration/endpointslice        254.653s
```

**Comment by robscott** [comment]
Also getting the same results, have not been able to reproduce this locally.

**Comment by aojea** [comment]
hold

**Comment by aojea** [comment]
/hold cancel
I can't find the weird interaction here, let's not stop other people

**Comment by robscott** [comment]
Quick update, this test looks like it is running into an issue that both EndpointSlice controllers struggle with. We've worked around this in other tests by checking for at least 1 EndpointSlice instead of exactly 1, but that does not seem appropriate here. Here's what can happen:

1. Controller gets event that triggers sync for Service
2. Controller syncs and creates EndpointSlice
3. Controller gets event that triggers sync for same Service
4. Controller syncs and creates EndpointSlice (the slice created in 2 has not made it to the cache yet)

This is a difficult problem to solve. The EndpointSlice tracker helps for a lot of these issues, but not this one. We can't wait to sync because the informer cache does not have an EndpointSlice the tracker thinks we should. If we did that, we would not be able to appropriately respond to real EndpointSlice deletions. I'm still thinking about appropriate mitigations for this, but until I'm able to fix the root cause, it might be sufficient to restructure this test to be less likely to run into this flake.

**Comment by aojea** [comment]
> Quick update, this test looks like it is running into an issue that both EndpointSlice controllers struggle with. We've worked around this in other tests by checking for at least 1 EndpointSlice instead of exactly 1, but that does not seem appropriate here. Here's what can happen:
> 
> 1. Controller gets event that triggers sync for Service
> 2. Controller syncs and creates EndpointSlice
> 3. Controller gets event that triggers sync for same Service
> 4. Controller syncs and creates EndpointSlice (the slice created in 2 has not made it to the cache yet)
> 
> This is a difficult problem to solve. The EndpointSlice tracker helps for a lot of these issues, but not this one. We can't wait to sync because the informer cache does not have an EndpointSlice the tracker thinks we should. If we did that, we would not be able to appropriately respond to real EndpointSlice deletions. I'm still thinking about appropriate mitigations for this, but until I'm able to fix the root cause, it might be sufficient to restructure this test to be less likely to run into this flake.

https://github.com/kubernetes/kubernetes/pull/100027

**Pull request closed without merging**
