### PR TITLE
kmsv2: enable KMSv2KDF feature gate by default

### LINKED ISSUE #119911: kmsv2: enable KDF by default in v1.29
/triage accepted
/sig auth
/assign
/milestone v1.29
/priority important-soon

### PR DESCRIPTION
**Pull request by enj**
/kind feature
/assign aramase
/triage accepted
/milestone v1.29 

Fixes #119911

```release-note
Changed the `KMSv2KDF` feature gate to be enabled by default.
```

```docs
TODO link to docs PR
```

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by enj** [comment]
/assign liggitt

For feature gate change approval.

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Changed the `KMSv2KDF` feature gate to be enabled by default.
```

**Pull request merged**
