### PR TITLE
kubelet: DRA: add TestParallelPrepareResources test

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This unit test was created while trying to reproduce https://github.com/kubernetes/kubernetes/issues/123474
Although it doesn't reproduce the issue, it makes sense to keep it in the codebase as it can help catching race conditions when `PrepareResources` API is called in parallel.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
Looks like the unit test is reporting a data race and failing.

**Comment by bart0sh** [comment]
@kannon92 
> Looks like the unit test is reporting a data race and failing.

Thanks for pointing out. It should be fixed now, PTAL.

**Comment by kannon92** [comment]
LGTM but I’ll leave labels for @pohly and @klueska

**Comment by bart0sh** [comment]
/close 
in favour of #124284

**Pull request closed without merging**
