### PR TITLE
Make net plugins build on non-unix

### PR DESCRIPTION
**Pull request by thockin**
@cjcullen build/release.sh is running now

### CODE REVIEW

**Comment by zmerlynn** [comment]
Except someone was a jerk and reverted the #5678 first, sorry. :)

**Comment by thockin** [comment]
thanks Obama.

**Comment by thockin** [comment]
Whew, should be settled now
sorry for the noise.  We have to get CI to do multi-platform builds.  I will internalize this lesson.  Again

**Comment by mrunalp** [comment]
Thanks for fixing @thockin . @rajatchopra and I knew that we had to do this but forgot and build did not catch it earlier.

**Pull request merged**
