### PR TITLE
use sysctl to write sysfs

### PR DESCRIPTION
**Pull request by benjamin-yanh**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
use sysctl to write sysfs，Can make the code more concise

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Zhongya-Yan** [comment]
I signed it

**Review by dougsland — COMMENTED** [review]
looks a good cleanup
/ok-to-test

**Comment by Zhongya-Yan** [comment]
@dougsland  can help me,trigger test

**Comment by Zhongya-Yan** [comment]
> you can check your patch is breaking kube-proxy
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/105562/pull-kubernetes-e2e-gce-ubuntu-containerd/1448554121291370496/artifacts/e2e-68b7bdb686-a7d53-minion-group-3pxp/kube-proxy.log
> 
> 1014 08:16:08.698610 1 server.go:659] "Version info" version="v1.23.0-alpha.3.318+aea02cf9a5bafe"
> I1014 08:16:08.698629 1 oom_linux.go:66] attempting to set "/proc/self/oom_score_adj" to "-998"
> I1014 08:16:08.702393 1 proxier_health.go:107] starting healthz on 0.0.0.0:10256
> I1014 08:16:08.703099 1 server.go:808] "GetConntrackMax: using conntrack-min"
> I1014 08:16:08.704286 1 conntrack.go:49] "Setting nf_conntrack_max" nf_conntrack_max=131072
> F1014 08:16:08.704316 1 server.go:501] open /proc/sys/sys/module/nf_conntrack/parameters/hashsize: no such file or directory
> 
> /hold
okay okay , i am new bird, i try

**Comment by Zhongya-Yan** [comment]
> 😄 , no worries, you'll get used ;)
I found the bug and have fixed it, can you help review it and retest?

**Comment by aojea** [comment]
despite the good intentions, this doesn't seem to add more value

**Comment by Zhongya-Yan** [comment]
> despite the good intentions, this doesn't seem to add more value

The last commit, I was just wondering why he always failed, including I reset the file and it still did

**Pull request closed without merging**
