### PR TITLE
Remove docs directory

### PR DESCRIPTION
**Pull request by spzala**
Since k8s.github.io is the primary docs repository for more than a year, we
shouldn't need docs directory any more. The changes requires to update
k8s.github.io and community repos and related PRs are,
kubernetes/kubernetes.github.io#3996
kubernetes/community#689

**What this PR does / why we need it**: Fixes a broken link. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # Straightforward changes so no issue was created.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by cblecker** [comment]
pinging @brendandburns / @smarterclayton for manual merge, as as old docs are prohibited from auto merge

**Comment by spzala** [comment]
Thanks @cblecker !!

**Comment by brendandburns** [comment]
@cblecker I don't have the right permissions to merge, not sure who does...

**Comment by cblecker** [comment]
@kubernetes/kubernetes-build-cops can someone give us a hand here? :)
Wondering out loud.. do we need to prohibit old-docs changes from auto merging? Considering they need approval anyways from a very small `docs/OWNERS` file, I'm not sure this is needed atm.

**Comment by ixdy** [comment]
I'm not sure what the policy here should be. @kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
Links to the official docs in https://kubernetes.io should be updated. So in this case, the link should probably be updated to https://kubernetes.io/docs/getting-started-guides/ubuntu/ Otherwise, there's no point in updating the old docs in kubernetes/kubernetes because the official docs live in kubernetes/kubernetes.github.io

Which auto-merging are we talking about? There are only a limited number of things we are pulling from kubernetes/kubernetes into kubernetes/kubernetes.github.io, e.g. api ref and kubectl.

**Comment by spzala** [comment]
@chenopis thanks Andrew! That was my initial thought when I made changes as we are redirecting the link but the same time since doc says 'calico' I thought good to keep it to the link with 'calico' in name as it was expected to have it as part of redirection. But it sounds good, I will update it. Thanks!

**Comment by spzala** [comment]
My very first thought was actually to remove the calico specific file since seems like we aren't doing anything specific to calico but I guess for backward compatibility we might want to keep it alive. Thanks!

**Comment by cblecker** [comment]
@chenopis the auto-merging I'm talking about is the submit queue for kubernetes/kubernetes. If a change is reviewed and approved by the right people, the bot does the merging. However, there are certain docs paths (listed here: https://github.com/kubernetes/test-infra/blob/master/mungegithub/block-path.yaml) that are prohibited to auto merge.

Most of the docs in https://github.com/kubernetes/kubernetes/tree/master/docs are stubs with links to the right place (mostly kubernetes.github.io or kubernetes/community). Right now docs in that block path list will refuse to merge and need manual attention from a kubernetes/kubernetes admin (instead of just an approval from a [docs/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/docs/OWNERS) approver.

**Comment by chenopis** [comment]
@cblecker Ah, ok. Thanks for clarifying.

**Comment by mikedanese** [comment]
Can we delete the docs/ directory at this point or is there some SEO reason for leaving them around?

**Comment by chenopis** [comment]
I think the k8s.io SEO would be better if we did delete the docs/ directory here.

**Comment by cblecker** [comment]
+1 on deleting the docs directory.
@thockin @brendandburns @smarterclayton (from docs/OWNERS).. thoughts?

**Comment by chenopis** [comment]
Ok, let's double check this.
@ahmetb @devin-donnelly Is there anything in the kubernetes/kubernetes `docs/` directory that we need to keep, or can we blow that away?

**Comment by thockin** [comment]
Would be happy to see it go.  docs/api-reference does seem to be referenced
from pkg/kubectl/cmd/patch.go and pkg/kubectl/cmd/replace.go, has a few
update scripts, and some of the same files exist in the docs repo, but I
don't know whence.

**Comment by ahmetb** [comment]
The reason docs/ exists is because there are probably many places linking to it. However at this point, the docs have been moved for >1 year ago. So I think we should try deleting it now.

It looks like we accepted PRs into `docs/` even after they're migrated to their own repo.  Here's the user-guide directory: https://github.com/kubernetes/kubernetes/commits/master/docs/user-guide It has quite many changes.

> I think the k8s.io SEO would be better if we did delete the docs/ directory here.

I think we already disabled the website: https://kubernetes.io/kubernetes so I don't think there's a SEO concern?

**Comment by chenopis** [comment]
Even though https://kubernetes.io/kubernetes has been disabled, the kubernetes/kubernetes GH repo itself is crawled, so I want to minimize the chance of anyone accidentally ending up in the docs directory here since it is stale.

**Comment by thockin** [comment]
I am 100% in favor of removing.  The API definitions.html and
reference.html are among the most contended files (causing rebases).  All
because of the damned timestamp.

**Comment by spzala** [comment]
Good discussion everyone, thanks!! So seems like the consensus is to delete /docs directory, and I guess we can just delete the directory without worrying too much? If we run into anything later on that is not working, broken links etc we take care of it in kubernetes.github.io? Removing /docs seems has edge on any possible disadvantages considering it will be a big maintenance relief and providers clear one place for docs in kubernetes.github.io. Does that sounds good? 

@thockin hi, fyi to your above comment, I don't see any reference.html - it might be gone already? As you pointed there are several definitions.html though. Do we need to worry about how to handle definitions.html if we remove /docs directory? I see few definitions.html in kubernetes.github.io/docs API and wondering if that already replaces (to large extent) definition.html of kubernertes/docs. 

Thanks !!

**Comment by thockin** [comment]
we need to be 100% sure the code doesn't link back to those docs and
nothing in the docs repo does either.

**Comment by spzala** [comment]
I have "tried" :) removing docs directory here with following two patches in kubernetes.github.io and community, 
kubernetes/kubernetes.github.io#3996
kubernetes/community#689
I see reference for definitions.html in pkg/generated/bindata.go but I believe the changes in patch.go should take care of generated files. 
Thanks!

**Comment by cblecker** [comment]
Most of the static content was removed in https://github.com/kubernetes/kubernetes/pull/46813. Right now what's left is the auto-generated content, and that needs a bit of a bigger plan if it's worth moving somewhere else

**Comment by thockin** [comment]
Should we close this until we figure out how to regen docs into docs repo instead of here?

**Comment by spzala** [comment]
@thockin I am fine closing it but I guess since we have only removed docs static content, may be good idea to keep this open to keep us reminded about the needed changes for generating docs? But you decide :-) Thanks!!

**Comment by thockin** [comment]
Unless it is actually in progress, we should close it - just for noise reasons.  We have tooooooo many open PRs :)

**Pull request closed without merging**
