### PR TITLE
Lowers the default nodelocaldns denial cache TTL

### LINKED ISSUE #74092: node-local-dns caching negative responses too long
**What happened**:
node-local-dns caches negative queries, causing things that do polling for orchestration to fail (like operators with StatefulSets).

**What you expected to happen**:
Have a minimal TTL for negative responses (alternatively just disable caching by setting the cache size to 0) that follows what was done for kube-dns: https://github.com/kubernetes/kubernetes/pull/53604

**How to reproduce it (as minimally and precisely as possible)**:
With node-local-dns cache deployed, in my cluster it was the https://github.com/coreos/etcd-operator that failed to create clusters because the cached entry didn't expire before it had exhausted all of it's retries.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.6
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): any
- Kernel (e.g. `uname -a`): any

### PR DESCRIPTION
**Pull request by blakebarnett**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Similar to `--no-negcache` on dnsmasq, this prevents issues which poll DNS for orchestration such as operators with StatefulSets. It can also be very confusing for users when negative caching results in a change they just made seeming to be broken until the cache expires. This assumes that 5 seconds is reasonable and will still catch repeated AAAA negative responses. We could also set the denial cache size to zero which should effectively fully disable it like dnsmasq in kube-dns but testing shows this approach seems to work well in our (albeit small) test clusters.

**Which issue(s) this PR fixes**:

Fixes #74092

**Does this PR introduce a user-facing change?**:
```release-note
Reduces the cache TTL for negative responses to 5s minimum.
```

### CODE REVIEW

**Comment by chrisohaver** [comment]
In case negative responses in the _cluster dns domain_ is the primary concern here, these negative responses default to a TTL of 5 as of CoreDNS 1.3.1.

e.g. 

```
dnstools# dig notthere.default.svc.cluster.local. A

; <<>> DiG 9.11.3 <<>> notthere.default.svc.cluster.local. A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 34026
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;notthere.default.svc.cluster.local. IN	A

;; AUTHORITY SECTION:
cluster.local.		5	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1549979885 7200 1800 86400 5

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Feb 14 20:15:31 UTC 2019
;; MSG SIZE  rcvd: 168
```

**Comment by blakebarnett** [comment]
Thanks!

I was unaware, I verified we've been testing against a build using CoreDNS v1.2.5, I'll update and test again now.

**Comment by blakebarnett** [comment]
Ah, seems the latest published image is still only v1.2.6. @prameshj is upgrading to 1.3.1 and publishing an image viable?

**Comment by chrisohaver** [comment]
CoreDNS 1.3.1 is already in the k8s.gcr.io repo: k8s.gcr.io/coredns:1.3.1.

These negative response originates from the cluster dns, not the node local dns.  The version of the node local dns should not make a difference. IIUC

**Comment by prameshj** [comment]
> CoreDNS 1.3.1 is already in the k8s.gcr.io repo: k8s.gcr.io/coredns:1.3.1.
> 
> These negative responses originate from the cluster dns, not the node local dns. The version of the node local dns should not make a difference. IIUC

Yes, that's how I understand it too, clusterDNS is setting the TTL on the record. If we use coreDNS as cluster dns, this TTL on the record will be 5s. So no need to use any TTL on the cache side.
However, with kube-dns, the default TTL is 30s.

**Comment by blakebarnett** [comment]
Ah, we've not moved to CoreDNS yet, so in this case I suppose this change is still needed.

**Comment by blakebarnett** [comment]
GKE is still defaulting to kube-dns also AFAIK (at least when we built our 1.11.5 cluster)

**Comment by prameshj** [comment]
In this change, the cache size for success and denial is specified as 10000, but it will be rounded down to nearest multiple of 256 = 9984, which is the default cache size value if nothing is specified.
https://github.com/coredns/coredns/tree/master/plugin/cache

So the only change here is specifying a lower TTL for denial, that looks good to me.

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
