### PR TITLE
Undo 1.28 shortname additions for now

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup
/kind api-change

#### What this PR does / why we need it:

Undoes unreleased shortname additions made in https://github.com/kubernetes/kubernetes/pull/116208 and https://github.com/kubernetes/kubernetes/pull/117535 until discussion in https://github.com/kubernetes/kubernetes/pull/117742#issuecomment-1545945336 is resolved. We don't want API changes we're unsure of sitting in master.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @thockin @smarterclayton

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/hold

holding in case you opened for discussion, unhold if not

**Comment by MikeSpreitzer** [comment]
@kkkkun 
@MikeSpreitzer

**Comment by kkkkun** [comment]
> @kkkkun @MikeSpreitzer

LGTM

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by BenTheElder** [comment]
> @BenTheElder, did kind change config recently?

Yes. Though I'm not sure that failure is related.

**Comment by BenTheElder** [comment]
@liggitt which job was it? there's two things in flight:
1) some jobs are moving to use the EKS cluster
2) kind is overhauling how we build and patch the base image with containerd etc.

**Comment by liggitt** [comment]
https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=117993

pull-kubernetes-e2e-kind - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117993/pull-kubernetes-e2e-kind/1658142561430147072

**Comment by BenTheElder** [comment]
ACK, that one shows `cluster: k8s-infra-prow-build` which is still the GKE cluster.

**Comment by smarterclayton** [comment]
lgtm as well

**Pull request merged**
