### PR TITLE
replace package realClock impl. with clock.RealClock

### LINKED ISSUE #104994: Cleanup admission/eventratelimit to use clock.RealClock
#### What happened:
While working on https://github.com/kubernetes/kubernetes/pull/104578, I realized that https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/eventratelimit/clock.go implements another `realClock` rather than using the one already implemented in https://github.com/kubernetes/apimachinery/tree/master/pkg/util/clock. 

I'm not sure why this was re-implemented, but if we can migrate to using `clock.RealClock` itself, then the code in the `flowcontrol` package can be cleaned up significantly (as part of https://github.com/kubernetes/kubernetes/pull/104578).

#### What you expected to happen:
I expect areas of the codebase that make use of a real clock to consistently use `clock.RealClock` instead of re-implementing it

#### How to reproduce it (as minimally and precisely as possible):
NA

#### Anything else we need to know?:
Another (slightly) related issue: https://github.com/kubernetes/kubernetes/issues/94738

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR replaces the `realClock` implementation in admission/eventratelimit to use the [`clock`](https://github.com/kubernetes/utils/tree/master/clock) package.

This will also help refactor code in the `flowcontrol` package. Please see: https://github.com/kubernetes/kubernetes/pull/104578

Aligning the codebase to use a single clock package also aligns with the goals of https://github.com/kubernetes/kubernetes/issues/94738

#### Which issue(s) this PR fixes:

Fixes #104994

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/priority backlog

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
/lgtm
/approve

**Comment by MikeSpreitzer** [comment]
Looks good to me too, but that's not what we need now.  We need approval from @deads2k or @derekwaynecarr .

**Comment by MadhavJivrajani** [comment]
@deads2k, small typo in `/appove` :)

**Pull request merged**
