### PR TITLE
Upgrade to azure-sdk v40.2.0

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Upgrade to azure-sdk v40.2.0, this is the first step to support Azure Shared disk feature
Note: 
this PR uses original api-version 2019-07-01, and it works, let's merge this PR first, and then I will try to use api-version 2019-11-01 for disks client in another PR

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
commands I have used:
```
hack/pin-dependency.sh github.com/Azure/azure-sdk-for-go v40.2.0+incompatible	
hack/pin-dependency.sh github.com/Azure/go-autorest/autorest v0.9.6
hack/pin-dependency.sh github.com/Azure/go-autorest/autorest/adal v0.8.2
hack/pin-dependency.sh github.com/Azure/go-autorest/autorest/mocks v0.3.0
hack/update-vendor.sh
# cd staging/src/k8s.io/legacy-cloud-providers/azure
# sed -i 's/2019-07-01/2019-12-01/g' *.go
# sed -i 's/2019-07-01/2019-12-01/g' BUILD
# sed -i 's/2019-07-01/2019-12-01/g' ./clients/*/*.go
# sed -i 's/2019-07-01/2019-12-01/g' ./clients/*/BUILD
# sed -i 's/2019-07-01/2019-12-01/g' ./mockvmsets/*.go
# sed -i 's/2019-07-01/2019-12-01/g' ./mockvmsets/BUILD
# sed -i 's/2019-07-01/2019-12-01/g' ./clients/*/*/*.go
# sed -i 's/2019-07-01/2019-12-01/g' ./clients/*/*/BUILD
# sed -i 's/2019-07-01/2019-12-01/g' ./test/e2e/framework/providers/azure/azure.go
```

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade to azure-sdk v40.2.0
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
API version '2019-12-01' is too new, not supported on all Azure regions:
```
  Warning  ProvisioningFailed  5s (x2 over 13s)  persistentvolume-controller  Failed to provision volume with StorageClass "hdd": Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus2' and API version '2019-12-01' for type 'disks'. The supported api-versions are '2016-04-30-preview, 2017-03-30, 2018-04-01, 2018-06-01, 2018-09-30, 2019-03-01, 2019-07-01, 2019-11-01'. The supported locations are 'southeastasia, eastus2, centralus, westeurope, eastus, northcentralus, southcentralus, westus, northeurope, eastasia, brazilsouth, westus2, westcentralus, ukwest, uksouth, japaneast, japanwest, canadacentral, canadaeast, centralindia, southindia, australiaeast, australiasoutheast, koreacentral, koreasouth, westindia, francecentral, southafricanorth, uaenorth, australiacentral, switzerlandnorth, germanywestcentral, norwayeast, eastus2euap, centraluseuap'."}}
```

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
@BenTheElder @liggitt could you approve? Thanks.

**Pull request merged**
