### PR TITLE
Fixed port in Heapster liveness probe

### LINKED ISSUE #31955: Heapster is being restarted due to unhealthy status
liveness probe was introduced in #31878

Heapster seems to work correctly so we should either fix it or revert liveness probe.

### PR DESCRIPTION
**Pull request by piosz**
fix #31955

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31961)

### CODE REVIEW

**Comment by piosz** [comment]
@pwittrock this should be cherry-picked to 1.4 branch

**Comment by wojtek-t** [comment]
lgtm

**Comment by piosz** [comment]
@k8s-bot unit test this issue: #31300

**Comment by piosz** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by piosz** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
Already in the 1.4 release. Removing candidate label.

**Pull request merged**
