### PR TITLE
Handle ambiguous fields in applyconfiguration-gen

### LINKED ISSUE #126982: Code Generation Produces Ambiguous Fields and Duplicate Methods
### What happened?

The changes introduced in https://github.com/kubernetes/kubernetes/pull/121439 require that all types used with the generated clients implement both `runtime.Object` and `meta.Object`. In order to comply with this, we started embedding `metav1.ObjectMeta` in our API types that were missing it. However, we noticed that, for some of our types, the generator generates code with ambiguous fields and duplicate methods.

For example, consider the following case where both `metav1.ObjectMeta` and `MyEmbeddedType`, which are embedded in `MyType`, contain a `Namespace` field:

```
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MyType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	MyEmbeddedType `json:"myEmbeddedType"`
}

type MyEmbeddedType struct {
	Namespace string `json:"namespace"`
}
```

This will generate code like:

```
func (b *MyTypeApplyConfiguration) WithNamespace(value string) *MyTypeApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}
```

Here, `b.Namespace` is invalid because that field is present in both embedded types.

### What did you expect to happen?

Generator should be able to handle non-conflicting top-level fields.

### How can we reproduce it (as minimally and precisely as possible)?

In this branch [1] I pushed 2 commits that will help visualize this issue better. Just pull it and run:

```
$ cd staging/src/k8s.io/sample-controller
$ go build -o sample-controller
# k8s.io/sample-controller/pkg/generated/applyconfiguration/samplecontroller/v1alpha1
pkg/generated/applyconfiguration/samplecontroller/v1alpha1/mytype.go:85:4: ambiguous selector b.Namespace
pkg/generated/applyconfiguration/samplecontroller/v1alpha1/mytype.go:207:36: method MyTypeApplyConfiguration.WithNamespace already declared at pkg/generated/applyconfiguration/samplecontroller/v1alpha1/mytype.go:83:36
pkg/generated/applyconfiguration/samplecontroller/v1alpha1/mytype.go:209:4: ambiguous selector b.Namespace
```

[1] https://github.com/bertinatto/kubernetes/tree/reproducer-generator-ambiguous-fields

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
v1.31.0
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

With embedded structs, objects can end up with conflicting members: members with the same name in different structs (embedded or not). These aren't ambiguous in Go, but applyconfiguration-gen's generated functions ignore this possibility and produce ambiguous member accesses and duplicate methods.

This resolves the problem by qualifying embedded member accesses with their types when appropriate, and by memoizing generated function names to avoid duplicates. When conflicting members are encountered, functions are generated for the first one; this is assumed to produce correct results.

For applyconfiguration-gen, a more correct approach would be to only generate With... and Get... functions for the specific members the generator is interested in; but that would be a breaking change for any client code relying on the other With... functions.

#### Which issue(s) this PR fixes:
Fixes #126982

#### Does this PR introduce a user-facing change?
```release-note
applyconfiguration-gen no longer generates duplicate methods and ambiguous member accesses when types end up with multiple members of the same name (through embedded structs).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
The fix looks good.

I think it's OK to enable apply configurations for the sample API server and add an embedded type there, but can we incorporate it more cleanly into the "sample" since is a sample apiserver intended to show how an api server should be built (and not a server intended to be used solely for test purposes)?

**Comment by skitt** [comment]
> I think it's OK to enable apply configurations for the sample API server and add an embedded type there, but can we incorporate it more cleanly into the "sample" since is a sample apiserver intended to show how an api server should be built (and not a server intended to be used solely for test purposes)?

I was ambivalent about that, I think it would be better to add an example in applyconfiguration-gen itself — adding a proper apply configuration example to the sample API server would indeed represent a bit more work than I intended here (and requires a different type of review).

**Comment by jpbetz** [comment]
/approve

Ready to LGTM once go.mod delta is cleared

**Comment by skitt** [comment]
@jpbetz would this qualify for cherry-picking to 1.31? (Given that the `ObjectMeta` requirement introduced in `client-gen` in 1.31 causes this to be a problem in practice...)

**Comment by jpbetz** [comment]
Current policy is to limit cherry picks to regressions or critical fixes.  I don't think this qualifies ☹️

**Pull request merged**
