### PR TITLE
Fluentd: concatenate long logs

### LINKED ISSUE #52444: Supporting docker log splitting in Kubernetes logging integrations
Follow-up of https://github.com/kubernetes/kubernetes/issues/52433

Docker 1.13 introduced a change into the logging mechanism (https://github.com/moby/moby/pull/22982), that split the log lines longer than 16K into chunks of no more than that. Current default logging integrations (fluentd-gcp and fluentd-es addons) do not support that and this might result in broken ingestion, i.e. when JSON parsing is broken for entries longer than 16K.

One possible solution is introducing a fluentd plugin to the configuration to concat such entries in the similar way https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions does it (assuming there is one out there, cc @tagomoris @repeatedly @edsiper for that)

/cc @igorpeshansky @fgrzadkowski @piosz

### PR DESCRIPTION
**Pull request by desaintmartin**
**What this PR does / why we need it**:

- Fluentd: concatenate long logs (>16KB) which have been splitted by Docker into several lines.
- Add fluentd-plugin-concat to fluent Docker image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #52444 

**Special notes for your reviewer**:

- This fix uses fluentd-plugin-concat, but maybe there are better solutions out there.
- This fix does not use the "partial_message" feature in the upcoming Docker release

**Release note**:
```
Fluentd: concatenate long logs (>16KB) which have been splitted by Docker into several lines, using fluentd-plugin-concat plugin.
```

### CODE REVIEW

**Comment by desaintmartin** [comment]
Up?
Using this in production for about a month. Although it might add some CPU usage for fluentd, it works well.

**Comment by desaintmartin** [comment]
@neolit123 all test are passing, are you interested in reviewing?

**Comment by neolit123** [comment]
@desaintmartin 
LGTM, but it's up to sig-instrumentation to merge.
you can try pinging them in the slack channel (#sig-instrumentation) if this stalls on reviews.

**Comment by neolit123** [comment]
might be a good idea to add a release note under `Release note:` as this is a bug fix.

**Comment by desaintmartin** [comment]
Good suggestion, thanks.

**Comment by coffeepac** [comment]
@desaintmartin thanks for your contribution!  please up the patch level for the following versioned items:
- fluentd-es-config (currently 0.1.5, should be 0.1.6)
  - need to up the patch level in fluentd-es-ds as well
- fluentd-es-ds (currently 2.2.0, should move to 2.2.0)

**Comment by desaintmartin** [comment]
@coffeepac Thanks! isn't the versions in the `fluentd-es-ds.yaml` file tied to the used image which is still v2.2.0?

**Comment by coffeepac** [comment]
@desaintmartin often the same but not necessarily.  the version for the daemonset spec is for the entire spec and any versioned resources in it.  I expect them to align again when the image revs a minor version.

**Comment by desaintmartin** [comment]
@coffeepac okay then, I amended the commit!

**Comment by coffeepac** [comment]
@desaintmartin you also need to update the version of the configmap that is referenced in the ds spec.

**Comment by desaintmartin** [comment]
@coffeepac Am I doing something wrong or is it OK that this test does not pass?

**Comment by coffeepac** [comment]
that test is required to pass.  I will take a quick look.

**Comment by desaintmartin** [comment]
May I rebase from master to see if the test is passing?

**Comment by desaintmartin** [comment]
It finally passes.

**Comment by coffeepac** [comment]
it takes a village.

**Comment by desaintmartin** [comment]
Thanks. Should someone generate a new version of gcr.io/google-containers/fluentd-elasticsearch ?

**Comment by coffeepac** [comment]
@desaintmartin yes.

I will submit a PR and go ping the appropriate person in the next few minutes.

**Comment by mmacfadden** [comment]
@desaintmartin Thanks for this, this has been kicking my butt! One question. I noticed that the concat filter was put in the output section right before going to elasticsearch. We are using the json parser like this for one of our containers that exports logs as JSON:
```
    # This configuration handles the filtering of the Convergence Server
    <filter **.some-kubernetes-tags>
      @type parser
      key_name log
      reserve_data false

      <parse>
        @type json
      </parse>
    </filter>
```

The parser has been failing because the JSON log message has been split by the 16k limitation that this PR is addressing. However, it seems like the rejoining of the logs is going to happen after this filter, which means this filter will likely still fail.

Am I correct in my assumption? Would there be a way to move the concat plugin up in the chain?

**Comment by mmacfadden** [comment]
@desaintmartin

Yes, I think that would work. That is what I was planning on doing. I just wanted to see if I was crazy in my assumption. Thanks for your help.

**Pull request merged**
