### PR TITLE
Fetch gke-exec-plugin license file along with the binary

### PR DESCRIPTION
**Pull request by awly**
**What this PR does / why we need it**: pull the combined LICENSE file for gke-exec-auth-plugin.
Plugin itself and the license are installed by downloading from GCS for legacy reasons. In the future they will be included in OS image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dchen1107** [comment]
/approve

I approved this PR with small nits:

1) Please add a TODO in the code to make sure the binary will be included in OS images itself. Downloading such binary might slow down the node startup latency. 
2) Please update PR description to explain why including such binary.

**Comment by awly** [comment]
@dchen1107 thanks, addressed comments. PTAL.

**Comment by awly** [comment]
@dchen1107 could you also LGTM?

**Pull request merged**
