### PR TITLE
Fix golint failure in e2e/common/util.go

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:
- test/e2e/common/util.go

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dashpole** [comment]
/priority backlog
/lgtm
/assign @vishh 
for approval

**Comment by k-toyoda-pi** [comment]
/assign @yujuhong
for approval

**Comment by k-toyoda-pi** [comment]
@dashpole @yujuhong Thanks for reviewing. I rebased this PR contains only common/util.go. Because, other files were already fixed with other PR. Could you review again?

**Pull request merged**
