### PR TITLE
Automated cherry pick of #32627

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #32627 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32689)

### CODE REVIEW

**Comment by yujuhong** [comment]
@smarterclayton @ncdc @pwittrock

**Comment by ncdc** [comment]
LGTM

**Comment by yujuhong** [comment]
ok. @pwittrock updated me on the new cherry pick policy. Closing this PR.
https://groups.google.com/forum/#!topic/kubernetes-dev/gJWTebsXXl0

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/32717

**Pull request closed without merging**
