### PR TITLE
Remove mounter flags from cri test configs

### PR DESCRIPTION
**Pull request by yujuhong**
The flags are no longer needed.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36478)

### CODE REVIEW

**Comment by yujuhong** [comment]
One of the flag no longer exits (due to a recent change). Need to change the test config to fix the cri builds.

cc @saad-ali

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by Random-Liu** [comment]
I'm a little confused by the flags, they come and go silently, like ghosts. :)

**Comment by yujuhong** [comment]
> I'm a little confused by the flags, they come and go silently, like ghosts. :)

Hopefully this is the last time we have to do this :-(

**Pull request merged**
