### PR TITLE
[WIP] CRI: add stop_signal to LinuxContainerConfig

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**What this PR does / why we need it**:

Currently docker takes care of stopping containers with whatever stop signal is defined for the container image. For instance, a container running systemd inside must have a stop signal of `SIGRTMIN+3`.

In the CRI, especially when using OCI runtimes (like in CRI-O), there's no way to get that information since OCI images aren't storing that field anywhere (since really, it doesn't belong to an image).

This PR adds a `stop_signal` to the protobuf API for `LinuxContainerConfig` when creating a container. CRI servers can store that value somewhere and use it when stopping the container.

I'm sure I didn't cover everything that must be changed in order to support this field in the CRI. Any suggestion on what to do is really appreciated (like, should  this be a flag in `kubectl run`? are there any other place I should configure and add this to the config sent from the CRI?)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@yujuhong @feiskyer ping

**Comment by yujuhong** [comment]
/cc @kubernetes/sig-node-feature-requests @kubernetes/sig-node-api-reviews 

@mrunalp @runcom, do you intend to let user specify the signal in kubernetes? The only way to do that right now is adding this information to the pod spec.

**Comment by runcom** [comment]
> @mrunalp @runcom, do you intend to let user specify the signal in kubernetes? The only way to do that right now is adding this information to the pod spec.

I mean, how could we do that otherwise - I'd love to have a way but right now, only docker does embed a stop signal in the container_config field for an image json. There's no such thing in OCI and we're pretty lost w/o this for containers running systemd for instance which requires a weird signal to be killed.

**Comment by yujuhong** [comment]
@runcom you PR adds the field but didn't use it at all, so I was trying to figure out how this could be used. One option is to return the "stop_signal" from the image, so that kubelet can pass that on to the runtime. Is that what you want to do?

**Comment by runcom** [comment]
No, sorry for not making it clear, you were actually right, we need a way to set this field in the PodSpec. Otherwise we cannot use it at all since OCI images aren't defining this field (since it's a runtime thing apparently). Let me know if changing the PodSpec is OK and I'll fix it.

**Comment by runcom** [comment]
just to be sure, I raised a question in OCI https://github.com/opencontainers/image-spec/issues/541

**Comment by lucab** [comment]
I think the original usecase of this is intertwined with https://github.com/kubernetes/community/pull/207, as the "custom signal for systemd" case seems to be coming from pid1 kernel semantics plus customary sighandlers arrangement for init.

**Comment by runcom** [comment]
@lucab right, that's the main use case for us

**Comment by runcom** [comment]
OCI/image-spec is taking care of this with https://github.com/opencontainers/image-spec/pull/544 and I don't see the need for the CRI to have this _now_. Since the stop signal is in the image, anyone can derive it _from_ the image after pulling it.
Having said that, it might be still ok to add this field in the CRI, though, I'd rather not at this point.

**Comment by yujuhong** [comment]
> OCI/image-spec is taking care of this with opencontainers/image-spec#544 and I don't see the need for the CRI to have this now. Since the stop signal is in the image, anyone can derive it from the image after pulling it.
> Having said that, it might be still ok to add this field in the CRI, though, I'd rather not at this point.

Once this is defined properly in the oci image spec, I think it'll make sense to add it in CRI

**Comment by runcom** [comment]
@yuanying sounds good. The image should however describe the stop signal for that image. Not sure how useful will be to override the stop signal in the CRI. We'll see.

**Comment by yujuhong** [comment]
@runcom even if we don't override the signal specified in the image, it's good for kubelet to get this information from the image service and pass it to the runtime service when running the containers.

**Pull request closed without merging**
