### PR TITLE
Revert node status manager

### LINKED ISSUE #14211: e2e flaky tests: Multiple tests failing with "Kubelet stopped posting node status."
For example: 

/job/kubernetes-e2e-gce-parallel/7979

 Node e2e-test-parallel-minion-5mr3 condition 1/1: type: Ready, status: Unknown, reason: "NodeStatusUnknown", message: "Kubelet stopped posting node status.", last transition time: 2015-09-18 15:10:00 -0700 PDT

### PR DESCRIPTION
**Pull request by yujuhong**
This is an attempt to fix #14211.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM and wait for the tests.

**Comment by yujuhong** [comment]
Removing the lgtm label because I (almost surely) ruled out this in #14211

**Comment by dchen1107** [comment]
I am closing this PR.

**Comment by yujuhong** [comment]
@k8s-bot  ok to test

**Comment by dchen1107** [comment]
A little bit updates on the PR from @yujuhong: There was a deadlock introduced through refactory:
There are locks guarding kl.podCIDR and kl.networkConfigured, and there is a race condition where nodeManager and syncNetworkStatus may deadlock.

**Comment by dchen1107** [comment]
Kicked out shippable for this one. Will manually merge it once it is green to stop e2e flakiness.

**Comment by dchen1107** [comment]
Re-run shippable again

**Comment by dchen1107** [comment]
ok to test

**Comment by yujuhong** [comment]
@dchen1107, I think we should merge this to stop e2e flakes. shippable failures are unrelated after all.

**Comment by dchen1107** [comment]
Yes, that is my plan. My early concern is that I cannot even view the failure logs from shippable. Since this pr is manual revert, I don't introduce more issues. Shippable is still failed due to TestPersistentVolumeClaimBinder which @saad-ali is looking at.

**Comment by dchen1107** [comment]
cc/ @gmarek, @wojtek-t @@fgrzadkowski 

We expected this revert PR fixes #14211, and get rid of the yellow builds on kubernetes-e2e-gce caused by "Kubelet stopped posting node status"

**Pull request merged**
