### PR TITLE
Fix copylock vet errors in component-base metrics

### PR DESCRIPTION
**Pull request by dashpole**
#### What type of PR is this?

/kind bug
/priority important-soon
/milestone 1.24

#### What this PR does / why we need it:

Fixes copylock vet errors discovered in https://github.com/kubernetes/kubernetes/issues/109197.

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109197

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/assign @liggitt @logicalhan

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve
Thanks for fixing this!

**Comment by liggitt** [comment]
/lgtm
/approve

thanks for the quick fix

**Comment by dashpole** [comment]
/hold
let me try and fix the additional failures I found in the test: https://github.com/kubernetes/kubernetes/issues/109197#issuecomment-1084724519

**Comment by liggitt** [comment]
I'd rather let this proceed to unblock the release

We can fix test-only issues until test freeze

**Pull request merged**
