### PR TITLE
Add release notes to the body of the pull request on create cherry-pick.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
When we create a [cherry-pick](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#steps) by [hack/cherry_pick_pull.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh) it generates a pull request with an empty `release-note` message. We have to manually update this message every time. This change automates the process.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
@saschagrunert what do you think of this change?

**Review by thockin — COMMENTED** [review]
Parsing the message is a bit sketchy, but it seems correct to me.

/lgtm
/approve

**Pull request merged**
