### PR TITLE
Added --service_address_override to the apiserver #6572

### PR DESCRIPTION
**Pull request by rrati**

### CODE REVIEW

**Comment by thockin** [comment]
Can you explain why?  I *just* refactored this to be simpler and have less confusing flags, what use case needs this?

**Comment by rrati** [comment]
If you have multiple apiservers running in a load balanced setup they fight against what the endpoint address should be for the kubernetes[-or] services.  Each apiserver is expecting the endpoint address to be its ip, and you can't use the existing settings (when I first looked, haven't looked at the refactoring) because they are used other places to actually perform a bind.  Without a way to set a constant address for the endpoing the apiservers will continually duel.  Additionally when you are running multiple apiserver you probably want to redirect all traffic to those services are load-balanced like other apiserver requests.

**Comment by rrati** [comment]
I'm open to a new/different option name if that is the concern

**Comment by thockin** [comment]
Ahh, yes, I saw this as I did multi-port support.  If you do this change
then the master service is not HA - you'll only have one master in the
endpoints, unless I misunderstand?

The real fix is to make the master services actually hold both/all master
IPs

**Comment by rrati** [comment]
It depends on what that ip is.  It could be the ip of a specific master or it could be the ip of a proxy that load balances the requests to all masters in the system.  The simplest route to take to allow multiple apiservers in the system for load-balancing/ha seems to be having a proxy (haproxy) actually handing the work distribution.  You could point everything at the proxy, including the cluster service endpoints, and let it distribute to the apiservers/masters.

We could decide on a more complicated ha scheme at some point where we make sure all apiservers know about each other etc.  That would be a more impactful change.  This should allow us to start heading down the load-balancing/ha path.

**Comment by thockin** [comment]
Who runs this haproxy?  Is it a pod or some other external thing?  It's a
plausible answer, but it needs some design

**Comment by thockin** [comment]
Can we take this to an issue for discussion?  I don't think we want a PR of this form.  Closing to try to keep my queue size down :)

filed #6672

**Comment by lavalamp** [comment]
Can we revert this PR? I haven't had a chance to look carefully yet because I just discovered it, but I think we had a totally different solution to this problem in mind when we wrote this stuff in the first place.

**Comment by lavalamp** [comment]
That was pre-coffee. I am totally blind, this was closed, not merged, haha.

**Pull request closed without merging**
