### PR TITLE
WIP: kubelet/rkt: Support rkt for container runtime. (Splitted into other PRs)

### PR DESCRIPTION
**Pull request by yifan-gu**
Let's use this PR to track the missing functions for experimental rkt support in k8s:
(Expected version of rkt: 0.5.4)
- [x] Privilege container (though for now, containers by default have CAP_SYS_ADMIN in rkt, see (https://github.com/coreos/rkt/issues/576)
- [x] Exec/RunInContainer
- [x] Get Container Logs (Only pod level logs for now)
- [x] Image pull with credentials
- [x] Garbage collection
- [x] Host network
- [x] More status, including PID (Now we have PID, exitcode)
- [x] <del> Unify the container image format, let's assume it's docker images for now. </del>I decided to abort this for now, let's just do `docker://` for now until we get a solution for #7208 
- [x] Portforwarding

What I am missing? @vmarmol @dchen1107 @jonboulle 

Update:
- [ ] Get container info

### CODE REVIEW

**Comment by yifan-gu** [comment]
#7202

**Comment by dchen1107** [comment]
PR description SGTM. Is PR itself ready for review?

**Comment by yifan-gu** [comment]
@dchen1107 No... I will remove WIP and split the commits once ready :)

**Comment by smarterclayton** [comment]
@pweil- please be aware of this w.r.t. security context so that the changes you are making are appropriately abstractable for Yifan

**Comment by pmorie** [comment]
We also need to accommodate rocket with pre-start hooks

**Comment by bcbroussard** [comment]
@yifan-gu thanks for the rkt support. I was experimenting with rkt on k8s through a privileged docker container a few days ago. Nice to see it coming in as a first class citizen. 

Are you planning to accommodate per namespace trusted keys, maybe through secrets or some other means?

**Comment by smarterclayton** [comment]
Cc @liggitt re: pull secrets - the delivery method for pull secrets to the kubelet will differ between rocket and docker unless rocket supports .dockercfg.  I think we can let supporting pull secrets be a follow on for the rocket plugin.

**Comment by bcbroussard** [comment]
Sounds good, thanks @smarterclayton

**Comment by pweil-** [comment]
@smarterclayton - will read through this today.  Thanks for the heads up

**Comment by vmarmol** [comment]
btw can we get the Godeps merged first as a separate PR? GitHub chokes trying to review such a large change and doesn't let us see the important parts of this PR.

**Comment by pmorie** [comment]
D you expect to use secrets for credentials for image pull?

**Comment by yifan-gu** [comment]
> btw can we get the Godeps merged first as a separate PR? GitHub chokes trying to review such a large change and doesn't let us see the important parts of this PR.

Good idea. Will do after one more commit (trying to get pid, exit code in status)

**Comment by dchen1107** [comment]
+1 on separate PR on Godeps. Thanks!

**Comment by yifan-gu** [comment]
@pmorie Good question. I haven't plan for using secrets in this PR. I'm not sure what's the plan for secrets for image pulling. Are we going to add a credential provider for secret volumes ??

**Comment by pmorie** [comment]
@yifan-gu excellent question. We definitely need to support secrets from a
service account, but I don't think you should have to make a volume in a
pod for a secret used for pull.

**Comment by smarterclayton** [comment]
The plan is no, at this moment - pull secrets are outside of the volumes (because they are managed outside of the containers)

**Comment by yifan-gu** [comment]
Got it, thanks! @smarterclayton @pmorie

**Comment by pmorie** [comment]
@yifan-gu @vmarmol Is the plan still to use `ContainerRuntime` as the interface to docker/rkt from kubelet?

**Comment by vmarmol** [comment]
@pmorie yes, it may take some time to do completely though.

**Comment by yifan-gu** [comment]
@vmarmol @dchen1107 I have most the missing functions implemented. Will do a cleanup and rebase.
I will try to group related functions in separate files for easy review.

Note that `get container log` now mixed up all container's logs within a pod. We are working on that.

Also a few functions' signature needs to sync with runtime.

**Comment by yifan-gu** [comment]
Splitted into:

#7605
#7599 
#7589 
#7555 
#7553 
#7550 
#7549 
#7545 
#7543 
#7526

The tests requires host to have `rkt` and `systemd`. So I think we need to put it off for now.

Closing!

**Pull request closed without merging**
