### PR TITLE
feat: convert selector spread priority to score plugin

### LINKED ISSUE #84829: [migration phase 1] SelectorSpread as Score plugin
**What would you like to be added**:

Add a Score plugin that calls into SelectorSpread priority. Plugin name should be "DefaultPodTopologySpread"

**Why is this needed**:

Part of  #83554

/sig scheduling
/assign @draveness 
/priority important-soon

### PR DESCRIPTION
**Pull request by draveness**
/kind feature
/sig scheduling
/assign @ahg-g 

Fix #84829 

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by ahg-g** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
