### PR TITLE
RFC: kube-bootstrap

### PR DESCRIPTION
**Pull request by justinsb**
I'm looking for feedback on this idea, because I think it could be a nice way to get from bare-machine to Kubernetes across clouds, not just on AWS.

This proposal adds a program called kube-bootstrap.  It is called as part of the instance startup scripts, and parses a JSON file containing configuration.  It currently performs just two small tasks that are needed for AWS master bootstrapping - attaching a master volume and setting up a route.  The "need" here is that this would allow for running the master in an Auto-Scaling Group on AWS, so that if it crashed the system would auto-recover.

There are a few big-picture ideas here:
- The bootstrap code is written in Go, not bash & salt.  Eventually it could take on more of the functionality that currently lives in bash & salt, in the hopes of making the instance-startup code more reliable & more portable across clouds.  (And also easier to move into e.g. kubelet)
- We store configuration in a JSON object, with a schema backed by Go code.  Again this is hopefully more reliable, and should also allow for dynamic reconfiguration in future.  Ideally this JSON object would live in the API eventually.
- We reuse the existing cloud providers, so we get e.g. much more robust attach-volume code than we would otherwise have - and we get it "for free"
- In the particular case of the master volume, we can treat attaching the volume as a sort of mutex.  So we could have a hot-standby machine ready to take over the master volume at all times; it would just spin until it was able to mount the master volume.  Or we could have 3 volumes and 3 masters (in an ASG) and get HA master.

All feedback is welcome. 

Related to #5472

### CODE REVIEW

**Comment by justinsb** [comment]
@thockin is this in your wheelhouse?  It feels like it's more about kube-up / salt than the stuff (I believe) you typically focus on.  And I bug you enough on that stuff as it is...

**Comment by thockin** [comment]
I don't have a wheelhouse, or at least it doesn't have walls. :)  I'll take
a look, but I'm a little buried with 1.1 prep today :)

**Comment by bgrant0607** [comment]
Ref #5754

**Comment by mikedanese** [comment]
I think this can be closed

**Pull request closed without merging**
