### PR TITLE
e2e/framework: remove direct imports to pkg/api/v1/pod

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e2e/framework: remove direct imports to pkg/api/v1/pod

**Which issue(s) this PR fixes**:

Ref #74352

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
/approve
using the package from kubectl SGTM.

**Review by andrewsykim — COMMENTED** [review]
/lgtm

I think duplicating would have been okay as well, `IsPodReady` is not overly complicated.

**Pull request merged**
