### PR TITLE
Added support for network policies in client-go -- as per client-go i…

### PR DESCRIPTION
**Pull request by FlorianOtel**
…ssue nr. 57

**What this PR does / why we need it**:

Adds support for Network Policies in client-go -- See https://github.com/kubernetes/client-go/issues/57

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Replaces PR #39155 (could not be amended, closed) 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by FlorianOtel** [comment]
@caesarxuchao @deads2k  Closed #39155 since (late ?) fixup of the two commits (as instructed) broke the build.  Submitted as single commit in this PR instead.  Sorry for the hassle.

**Comment by deads2k** [comment]
lgtm, but I because of the severity of https://github.com/kubernetes/kubernetes/pull/39807 I think we should hold this on its generator updates.  It's just waiting for godep verify to be working again.

**Comment by FlorianOtel** [comment]
@deads2k FWIW: Even in my case the godep restore before hack/update-staging-client-go.sh required quite a bit of "massaging" in terms of what packages I had locally.

Also the main reason I closed #39155 and reopened the PR here was the Jenkins build failing (caveat: not 100% sure it was the same issue and now the Jenkins build job(s) log are gone). 

Looking fwd for updates.

**Comment by FlorianOtel** [comment]
@deads2k Ping. Any ETA / updates ?

**Comment by deads2k** [comment]
thanks for the reminder.

**Comment by FlorianOtel** [comment]
@deads2k @lavalamp  Confused about the build breaking... The PR consist of autogenerated code only: 

- added // +genclient=true to pkg/apis/extensions/v1beta1/types.go for NetworkPolicy
- ran hack/update-codegen.sh ; hack/update-staging-client-go.sh ; hack/update-bazel.sh  

That's it. 

Have I missed something ? Any way to verify the same checks as above on my side (my tests looked OK)

TIA for the help.

**Comment by deads2k** [comment]
@FlorianOtel You're getting caught in the great code migration of 2017.  `client-go` is becoming authoritative and code duplication is being eliminated, but it means that the generators are change to reflect authoritative packages so downstream projects (like service catalog) can use them.

I think you did everything right and a non-conflicting conflict bit you.  I'd try again after https://github.com/kubernetes/kubernetes/pull/40449

**Comment by FlorianOtel** [comment]
@k8s-bot bazel test this

@k8s-bot unit test this

@k8s-bot gci gke e2e test this

@k8s-bot kubemark e2e test this

@k8s-bot gce etcd3 e2e test this

@k8s-bot cvm gce e2e test this

@k8s-bot gci gce e2e test this

@k8s-bot kops aws e2e test this

@k8s-bot cvm gke e2e test this

@k8s-bot node e2e test this

@k8s-bot cri node e2e test this

@k8s-bot verify test this

**Pull request closed without merging**
