### PR TITLE
Improved some more bash script variable definitions

### PR DESCRIPTION
**Pull request by rlenferink**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Another set of bash syntax improvements

**Which issue(s) this PR fixes**:
#73082 is used for tracking the progress of these PRs.

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @fejta @ixdy @BenTheElder 
/sig testing
/priority important-longterm

### CODE REVIEW

**Comment by oomichi** [comment]
Most part looks good to me, just one question.
Do we still need to keep these files on hack/.shellcheck_failures ?

**Comment by rlenferink** [comment]
> Most part looks good to me, just one question.
> Do we still need to keep these files on hack/.shellcheck_failures ?

We are working towards an empty `hack/.shellcheck_failures` file (see #72956). This is done with incremental PRs to keep reviewing doable and to make sure we're not accidentally breaking anything.

Good question 😃

**Comment by oomichi** [comment]
Thanks for your explanation, I got it :-)

/lgtm

**Pull request merged**
