### PR TITLE
Update core node e2e

### PR DESCRIPTION
**Pull request by vishh**
For #28192

cc @dubstack

### CODE REVIEW

**Comment by dubstack** [comment]
@vishh @yifan-gu Could not pre-pull image gcr.io/google_containers/nginx-slim:0.7 exit status 1 output:  Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Any idea why this might be happening?

**Comment by yifan-gu** [comment]
Looking into that.

**Comment by yifan-gu** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by yifan-gu** [comment]
Created a new image with jenkins added to the docker group. Can any of you guys try this? Thank you!
https://storage.googleapis.com/node-e2e-images/test-e2e-node-coreos-alpha-1068-20160707-cgroupfs.tar.gz

@vishh @dubstack

**Comment by dubstack** [comment]
@yifan-gu Thanks. I will take over this patch.

**Comment by dubstack** [comment]
Closing this. Taken over by #28661

**Pull request closed without merging**
