### PR TITLE
fix golint error make test error checking more readable in test/e2e/node

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup
/sig testing

**What this PR does / why we need it**:

in test/e2e/node:
1. fix golint error
2. make test error checking more readable

**Which issue(s) this PR fixes**:

Part of #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
This is a port of https://github.com/kubernetes/kubernetes/issues/68026 not https://github.com/kubernetes/kubernetes/issues/77706

Please fix the PR message for the reference.

**Comment by spiffxp** [comment]
/hold
Please address @oomichi's concern, otherwise this looks good
/priority backlog

**Comment by danielqsj** [comment]
>This should be a part of #68026 not #77706

Addressed. Thanks.

**Pull request merged**
