### PR TITLE
Fix: Typos in apiclient util.

### PR DESCRIPTION
**Pull request by taesunny**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
> This file has typos (initalTimeout -> initialTimeout) to 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by taesunny** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

**Comment by taesunny** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

I signed it

**Comment by neolit123** [comment]
thank you for the PR.
please replace the release note `Fix: Typos in apiclient util` with `NONE` in the PR description.
also try resolving the CLA issue with the CNCF help desk if needed.

**Comment by taesunny** [comment]
> thank you for the PR.
> please replace the release note `Fix: Typos in apiclient util` with `NONE` in the PR description.
> also try resolving the CLA issue with the CNCF help desk if needed.

Thank you so much!

**Comment by taesunny** [comment]
I signed it

**Comment by neolit123** [comment]
doesn't seem to work, or maybe hasn't updated yet. please, try the notes here: https://github.com/kubernetes/kubernetes/pull/88359#issuecomment-588636757

**Comment by taesunny** [comment]
> doesn't seem to work, or maybe hasn't updated yet. please, try the notes here: [#88359 (comment)](https://github.com/kubernetes/kubernetes/pull/88359#issuecomment-588636757)

I will contact CNCF help desk. Thanks

**Pull request merged**
