### PR TITLE
Upgrade to etcd 3.3.16 client

### PR DESCRIPTION
**Pull request by jpbetz**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Cherrypick fixes for two major issues with the etcd 3.3 client to 1.16:
- etcd client does not parse IPv6 addresses correctly when members are joining
- failover on multi-member etcd cluster fails certificate check on DNS mismatch

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/83550 via https://github.com/etcd-io/etcd/pull/11211 (backported to etcd 3.3.16 via https://github.com/etcd-io/etcd/pull/11216)
Fixes https://github.com/kubernetes/kubernetes/issues/83028 via https://github.com/etcd-io/etcd/pull/11184 (backported to etcd 3.3.16 via https://github.com/etcd-io/etcd/pull/11215)

**Special notes for your reviewer**:

Kubernetes master branch is being upgraded to the etcd 3.4.2 client, so we are patching release-1.16 directly rather than applying to master and then cherrypicking.

We typically also upgrade the etcd server to the same version to keep them in sync. I'll create a separate PR to upgrade 1.16 to use the etcd 3.3.16 server shortly.

**Does this PR introduce a user-facing change?**:
```release-note
Upgrade to etcd client 3.3.16 to fix bug where etcd client does not parse IPv6 addresses correctly when members are joining, and to fix bug where failover on multi-member etcd cluster fails certificate check on DNS mismatch
```

/sig api-machinery
/area etcd
/priority critical-urgent

### CODE REVIEW

**Comment by jpbetz** [comment]
cc @liggitt

**Comment by jpbetz** [comment]
We're upgrading to the etcd 3.4.2 client on master. But for later cherrypicks merges to this release branch, do we first need to commit this to master and then cherrypick?

**Comment by liggitt** [comment]
> do we first need to commit this to master and then cherrypick?

I think we should bump master and allow some soak period (at least monitor various post-submits and scale tests) before merging to 1.16.x.

**Comment by liggitt** [comment]
Are any new tests required in k8s or are we covered by the upstream tests added with these fixes in etcd?

**Pull request closed without merging**
