### PR TITLE
remove the flaky mark in deployment e2e test

### PR DESCRIPTION
**Pull request by mqliang**
@janetkuo

### CODE REVIEW

**Comment by janetkuo** [comment]
LGTM

**Comment by janetkuo** [comment]
@mqliang actually, this test is kind of flaky when I test it locally. Do you mind taking a look?

```
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {default-scheduler } Scheduled: Successfully assigned nginx-controller-f5u6e to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {kubelet 127.0.0.1} Pulling: pulling image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {kubelet 127.0.0.1} Pulled: Successfully pulled image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {kubelet 127.0.0.1} Created: Created container with docker id 80c7021dd353
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {kubelet 127.0.0.1} Started: Started container with docker id 80c7021dd353
Jan 14 16:50:43.853: INFO: event for nginx-controller-f5u6e: {kubelet 127.0.0.1} Killing: Killing container with docker id 80c7021dd353: Need to kill pod.
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {default-scheduler } Scheduled: Successfully assigned nginx-controller-n4v05 to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {kubelet 127.0.0.1} Pulling: pulling image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {kubelet 127.0.0.1} Pulled: Successfully pulled image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {kubelet 127.0.0.1} Created: Created container with docker id c7a6f514bbce
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {kubelet 127.0.0.1} Started: Started container with docker id c7a6f514bbce
Jan 14 16:50:43.853: INFO: event for nginx-controller-n4v05: {kubelet 127.0.0.1} Killing: Killing container with docker id c7a6f514bbce: Need to kill pod.
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {default-scheduler } Scheduled: Successfully assigned nginx-controller-z5vvs to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {kubelet 127.0.0.1} Pulling: pulling image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {kubelet 127.0.0.1} Pulled: Successfully pulled image "nginx"
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {kubelet 127.0.0.1} Created: Created container with docker id 8458aaa829b1
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {kubelet 127.0.0.1} Started: Started container with docker id 8458aaa829b1
Jan 14 16:50:43.853: INFO: event for nginx-controller-z5vvs: {kubelet 127.0.0.1} Killing: Killing container with docker id 8458aaa829b1: Need to kill pod.
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulCreate: Created pod: nginx-controller-f5u6e
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulCreate: Created pod: nginx-controller-n4v05
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulCreate: Created pod: nginx-controller-z5vvs
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulDelete: Deleted pod: nginx-controller-n4v05
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulDelete: Deleted pod: nginx-controller-z5vvs
Jan 14 16:50:43.853: INFO: event for nginx-controller: {replication-controller } SuccessfulDelete: Deleted pod: nginx-controller-f5u6e
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-gwz5j: {default-scheduler } Scheduled: Successfully assigned redis-deployment-3-io8ah-gwz5j to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-gwz5j: {kubelet 127.0.0.1} Pulling: pulling image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-gwz5j: {kubelet 127.0.0.1} Pulled: Successfully pulled image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-gwz5j: {kubelet 127.0.0.1} Created: Created container with docker id 169f1a863593
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-gwz5j: {kubelet 127.0.0.1} Started: Started container with docker id 169f1a863593
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-mzt95: {default-scheduler } Scheduled: Successfully assigned redis-deployment-3-io8ah-mzt95 to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-mzt95: {kubelet 127.0.0.1} Pulling: pulling image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-mzt95: {kubelet 127.0.0.1} Pulled: Successfully pulled image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-mzt95: {kubelet 127.0.0.1} Created: Created container with docker id 3173680b59fa
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-mzt95: {kubelet 127.0.0.1} Started: Started container with docker id 3173680b59fa
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-wfoti: {default-scheduler } Scheduled: Successfully assigned redis-deployment-3-io8ah-wfoti to 127.0.0.1
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-wfoti: {kubelet 127.0.0.1} Pulling: pulling image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-wfoti: {kubelet 127.0.0.1} Pulled: Successfully pulled image "redis"
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-wfoti: {kubelet 127.0.0.1} Created: Created container with docker id 808f7a9b408a
Jan 14 16:50:43.853: INFO: event for redis-deployment-3-io8ah-wfoti: {kubelet 127.0.0.1} Started: Started container with docker id 808f7a9b408a
Jan 14 16:50:43.854: INFO: event for redis-deployment-3-io8ah: {replication-controller } SuccessfulCreate: Created pod: redis-deployment-3-io8ah-gwz5j
Jan 14 16:50:43.854: INFO: event for redis-deployment-3-io8ah: {replication-controller } SuccessfulCreate: Created pod: redis-deployment-3-io8ah-wfoti
Jan 14 16:50:43.854: INFO: event for redis-deployment-3-io8ah: {replication-controller } SuccessfulCreate: Created pod: redis-deployment-3-io8ah-mzt95
Jan 14 16:50:43.854: INFO: event for redis-deployment-3: {deployment-controller } ScalingRC: Scaled down rc nginx-controller to 0
Jan 14 16:50:43.854: INFO: event for redis-deployment-3: {deployment-controller } ScalingRC: Scaled up rc redis-deployment-3-io8ah to 3
Jan 14 16:50:44.047: INFO: POD                             NODE       PHASE    GRACE  CONDITIONS
Jan 14 16:50:44.047: INFO: nginx-deployment-w97x3-b1vyz    127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:42:09 -0800 PST  }]
Jan 14 16:50:44.047: INFO: nginx-deployment-w97x3-t1fw3    127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:42:05 -0800 PST  }]
Jan 14 16:50:44.047: INFO: nginx-deployment-w97x3-u5a6k    127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:42:07 -0800 PST  }]
Jan 14 16:50:44.047: INFO: redis-deployment-3-io8ah-gwz5j  127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:45:47 -0800 PST  }]
Jan 14 16:50:44.047: INFO: redis-deployment-3-io8ah-mzt95  127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:45:50 -0800 PST  }]
Jan 14 16:50:44.047: INFO: redis-deployment-3-io8ah-wfoti  127.0.0.1  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-14 16:45:48 -0800 PST  }]
```
```  
  Expected error:
      <*errors.errorString | 0xc8201a1d10>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred
```

**Comment by mqliang** [comment]
@janetkuo I am not sure what's going wrong. And could you please kindly tell me why `testRollingUpdateDeployment` and `testRollingUpdateDeploymentEvents` are flaky if I ask?

**Comment by janetkuo** [comment]
@mqliang the cause of those two flakes are because of race condition. Multiple new RCs are created before the rcStore is synced. This flake looks different. I filed #19733 to fix it and you can see details there.

**Comment by ixdy** [comment]
@k8s-bot test this please

**Pull request merged**
