### PR TITLE
Add SELinuxOptions to LinuxPodSandboxConfig

### PR DESCRIPTION
**Pull request by mrunalp**
Without adding this, there is no way that one can set
correct SELinux labels for a pod-infra like container.

@yujuhong PTAL
cc: @rhatdan @yifan-gu @euank @feiskyer 

Signed-off-by: Mrunal Patel mpatel@redhat.com

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34144)

### CODE REVIEW

**Comment by mrunalp** [comment]
@vishh PTAL

**Comment by yujuhong** [comment]
@mrunalp the pod-level SELinux is being discussed in #33139. Would you mind discussing over there first? Thanks!

**Comment by mrunalp** [comment]
@yujuhong Sure.

**Comment by eparis** [comment]
@pmorie

**Comment by feiskyer** [comment]
Just opened another PR to add PodSecurityContext to sandbox config, which includes SELinuxOption. PTAL.

**Comment by yifan-gu** [comment]
Do we want to close this in favor of https://github.com/kubernetes/kubernetes/pull/34811

**Comment by yujuhong** [comment]
Yes, let's handle it in one PR.

**Pull request closed without merging**
