### PR TITLE
test images: Adds label to httpd-new image

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing
/sig windows

/priority important-soon

#### What this PR does / why we need it:

Adds a label to the httpd-new image, so a new SHA gets generated, so it can be pushed to staging.

#### Which issue(s) this PR fixes:

Addresses: https://github.com/kubernetes/test-infra/issues/20884

#### Special notes for your reviewer:

This change was missed here: https://github.com/kubernetes/kubernetes/pull/99609

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mkumatag** [comment]
As of now, it lgtm to me, but can we think of supplying these metadata during the build itself from file spec? especially it will be useful if we have multiple docker files like Linux, windows etc..

/lgtm

**Comment by claudiubelu** [comment]
> 
> 
> As of now, it lgtm to me, but can we think of supplying these metadata during the build itself from file spec? especially it will be useful if we have multiple docker files like Linux, windows etc..
> 
> /lgtm

Good point. We could add an ``ARG`` to the Dockerfiles and then pass it in as an ``--build-arg``.

**Comment by mkumatag** [comment]
> > As of now, it lgtm to me, but can we think of supplying these metadata during the build itself from file spec? especially it will be useful if we have multiple docker files like Linux, windows etc..
> > /lgtm
> 
> Good point. We could add an `ARG` to the Dockerfiles and then pass it in as an `--build-arg`.

that's right, will have to find a way to enhance the existing scripts to do so, and even we can include a couple of more information like git_url, git_commit etc.. for additional information about the image source as well.

**Comment by spiffxp** [comment]
@mkumatag re: https://github.com/kubernetes/kubernetes/pull/99631#issuecomment-788945533 sounds like a great idea, I opened https://github.com/kubernetes/kubernetes/issues/99648 to explore that further

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
