### PR TITLE
Remove kubectl namespace command

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

It removes deprecated `kubectl namespace` command, which `has been superseded by the context.namespace field of .kubeconfig files.  See 'kubectl config set-context --help' for more details`. It was done nearly two years ago, so like `// TODO remove once people have been given enough time to notice` comment says it may be a good time to get rid of it.

**Special notes for your reviewer**:

None ATM.

**Release note**:

``` release-note
Remove kubectl namespace command
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33275)

### CODE REVIEW

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by soltysh** [comment]
@janetkuo actually, I'd expect removal of a command to land in the release notes, so that users are aware it was removed. @maciaszczykm can you update the description with that note?

**Comment by maciaszczykm** [comment]
>@janetkuo actually, I'd expect removal of a command to land in the release notes, so that users are aware it was removed. @maciaszczykm can you update the description with that note?

@soltysh I followed instruction saying, that:

> Enter your extended release note in the below block; leaving it blank means using the PR title as the release note. If no release note is required, just write `NONE`. 

Anyways, I've updated it. Is it okay right now?

**Comment by soltysh** [comment]
> Anyways, I've updated it. Is it okay right now or do we need more precise notes?

That's sufficient, thx. The change itself LGTM. Need final word from @fabianofranz if this doesn't bite us in any way and if not this is good to go.

**Comment by fabianofranz** [comment]
LGTM, good to go.

**Pull request merged**
