### PR TITLE
kubeadm: use t.Run in selfhosting and update phases

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Used T.Run API for kubeadm tests in app/phases/selfhosting and
app/phases/update directories

This should improve testing output and make it more visible
which test is doing what.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — APPROVED** [review]
Thanks @bart0sh 
/lgtm
/priority important-longterm

**Review by neolit123 — APPROVED** [review]
thanks @bart0sh 
/approve

**Pull request merged**
