### PR TITLE
Automated cherry pick of #61080: Detect backsteps correctly in base path detection

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #61080 on release-1.7.

#61080: Detect backsteps correctly in base path detection

### CODE REVIEW

**Comment by liggitt** [comment]
kubemark failure fixed in https://github.com/kubernetes/kubernetes/pull/61116

**Comment by liggitt** [comment]
kubemark failure due to https://github.com/kubernetes/kubernetes/issues/61141

**Comment by liggitt** [comment]
the kubemark failure is persistent... it is trying to rebuild with a go version that won't work. @krzyzacy is working on a fix, but ETA is unknown

**Comment by liggitt** [comment]
> the kubemark failure is persistent... it is trying to rebuild with a go version that won't work. @krzyzacy is working on a fix, but ETA is unknown

I take it back... the job went green!

**Comment by krzyzacy** [comment]
@liggitt the job went green because e2e.go only tries to rebuild kubetest if that's >24h old, and we pushed a new kubetest image last night..

I'll try to get https://github.com/kubernetes/test-infra/pull/7267 in asap today

**Comment by liggitt** [comment]
> @liggitt the job went green because e2e.go only tries to rebuild kubetest if that's >24h old, and we pushed a new kubetest image last night..

oh... well... we should merge quickly, then :)

**Pull request merged**
