### PR TITLE
avoid sharedIndexInformer run more than once, avoid more cache and me…

### PR DESCRIPTION
**Pull request by kitianFresh**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

avoid the informer to be run more than once by return explict error or by some check

#### Which issue(s) this PR fixes:
following code has some bug, because the nodeInformer will start more than once, then there will be two reflectors, two DeltaFIFOs, and two goroutines to list watch nodes data, and it can run normally but it will consume more resources.

we should avoid the informer to be run more than once by return explict error or by some check

```
	podInformer := NewPodInformer(kubeClient, 0)
	informerFactory := informers.NewSharedInformerFactory(kubeClient, 0)
	nodeInformer := informerFactory.Core().V1().Nodes()
	....
	rc.ScheduledPodsHasSynced = podInformer.Informer().HasSynced
	// scheduled pod cache
	podInformer.Informer().AddEventHandler(
		cache.FilteringResourceEventHandler{
			FilterFunc: func(obj interface{}) bool {
				switch t := obj.(type) {
				case *v1.Pod:
					return assignedNonTerminatedPod(t)
				case cache.DeletedFinalStateUnknown:
					if pod, ok := t.Obj.(*v1.Pod); ok {
						return assignedNonTerminatedPod(pod)
					}
					runtime.HandleError(fmt.Errorf("unable to convert object %T to *v1.Pod in %T", obj, rc))
					return false
				default:
					runtime.HandleError(fmt.Errorf("unable to handle object in %T: %T", rc, obj))
					return false
				}
			},
			Handler: cache.ResourceEventHandlerFuncs{
				AddFunc:    rc.addPodToCache,
				UpdateFunc: rc.updatePodInCache,
				DeleteFunc: rc.deletePodFromCache,
			},
		},
	)

	nodeInformer.Informer().AddEventHandler(
		cache.ResourceEventHandlerFuncs{
			AddFunc:    rc.addNodeToCache,
			UpdateFunc: rc.updateNodeInCache,
			DeleteFunc: rc.deleteNodeFromCache,
		},
	)

	rc.NodeLister = nodeInformer.Lister()
	rc.PodLister = podInformer.Lister()
	go podInformer.Informer().Run(stopCh)
	go nodeInformer.Informer().Run(stopCh)
	rc.InformerFactory.Start(stopCh)
	...
```

#### Does this PR introduce a user-facing change?
NO

### CODE REVIEW

**Comment by aojea** [comment]
is not the intention of the user to run 2 informers on your example?

/assign @wojtek-t @deads2k

**Comment by pacoxu** [comment]
/remove-sig api-machinery
for bot bug

**Comment by kitianFresh** [comment]
> is not the intention of the user to run 2 informers on your example?

I think we should avoid the user to run the informer more than once because some times the user maybe use the informer by wrong way, we should avoid this condition. if we do not, the informer may run many times but the program is ok,  but the resource consume and program is not ok, you can not found the reason.

**Comment by wojtek-t** [comment]
/release-note-none

/lgtm
/approve

Thanks!

**Comment by kitianFresh** [comment]
> /release-note-none
> 
> /lgtm
> /approve
> 
> Thanks!

Thanks for reviewing.

**Pull request merged**
