### PR TITLE
Fix non-enum CSR condition field, omit enums from static openapi snapshot

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind feature

#### What this PR does / why we need it:

Follow-up to https://github.com/kubernetes/kubernetes/pull/108639

1. Fixes an incorrectly marked enum field on CSR conditions
2. Omits enums from the static openapi snapshot being used to generate clients 

xref #109177

#### Does this PR introduce a user-facing change?
```release-note
Omit enum declarations from the static openapi file captured at https://git.k8s.io/kubernetes/api/openapi-spec. This file is used to generate API clients, and use of enums in those generated clients (rather than strings) can break forward compatibility with additional future values in those fields. See https://issue.k8s.io/109177 for details.
```

/sig api-machinery
for openapi snapshot

/sig auth
for CSR API

### CODE REVIEW

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/109182 flake

/retest

**Comment by aojea** [comment]
```
k8s.io/kubernetes/test/integration/apiserver/apply: TestDroppingSubresourceField expand_more	2m26s
k8s.io/kubernetes/test/integration/auth: TestRBAC expand_more	0s
k8s.io/kubernetes/test/integration/client: TestApplyWithApplyConfiguration expand_more	0s
k8s.io/kubernetes/test/integration/controlplane: TestOpenAPIDelegationChainPlumbing expand_more	2m24s
k8s.io/kubernetes/test/integration/controlplane/transformation: TestSecretsShouldBeTransformed expand_more	2m24s
k8s.io/kubernetes/test/integration/cronjob: TestCronJobLaunchesPodAndCleansUp expand_more
```

/retest

**Comment by liggitt** [comment]
rebased after https://github.com/kubernetes/kubernetes/pull/109195 merged

**Comment by jiahuif** [comment]
The affected types are not actually enums. Currently, we do not have support for types that can be either enum or any value. As a result, we have to unmark these types as enum and thus undo the generated comments from them.

**Comment by liggitt** [comment]
> Could I advocate for a changelog entry that is more clear about what has happened to the OpenAPI spec as a result of this PR? (I don't think I'd have understood that entry without context).

updated the changelog

**Comment by sftim** [comment]
I also filed https://github.com/kubernetes/kubernetes/issues/109463 to cover the new gap in our API docs

**Pull request merged**
