### PR TITLE
Use framework.ExpectNotEqual()

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**

/kind cleanup
Keep code readable

**What this PR does / why we need it:**
e2e: Use framework.ExpectNotEqual() for test/e2e/storage

**Which issue(s) this PR fixes:**

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?:**

NONE

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/release-note-none

**Comment by ZP-AlwaysWin** [comment]
New errors were introduced

**Pull request merged**
