### PR TITLE
Log Health Check failure at Verbosity Level - 4

### PR DESCRIPTION
**Pull request by dims**
Our default recommendation as well as our CI default is 4, so we should
be able to see the health check errors at the same level 4 itself.

Change-Id: I388f945d3522d1f63f0a85f35e765c2d4f2c548a

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
We have failures in our CI like this one - https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72617/pull-kubernetes-integration/40248/  - but since the logging verbosity default is 4 and not 6, we never see anything relevant and see instead the cryptic `etcd failed: reason withheld` only...

**Comment by liggitt** [comment]
logging the specific failure seems reasonable to me, especially if the obscured summary is already being logged

/lgtm
/approve

**Pull request merged**
