### PR TITLE
Automated cherry pick of #25519 #25537

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #25519 #25537 on release-1.1.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
This fixes the kubectl logs test which is currently broken on 1.1 (similar cherrypick was already done for 1.2).

**Comment by jlowdermilk** [comment]
Failing test is the guestbook test that has been broken on 1.1 for over a week. So this does fix the logs test, at least.

**Comment by spxtr** [comment]
Do we even worry about fixing broken 1.1 tests anymore?

**Comment by spxtr** [comment]
I think you should just force merge. 1.1 e2e are super flaky.

**Comment by jlowdermilk** [comment]
The failing e2e test is fixed by #27139. I'll wait until that is in to verify it's all green with both changes.

**Comment by jlowdermilk** [comment]
Change was just rebase to pick up #27139. Re-adding lgtm.

**Comment by jlowdermilk** [comment]
@k8s-bot e2e test this issue: #27153

**Comment by jlowdermilk** [comment]
@k8s-oncall manually merging to fix 1.1 test (should not affect head/prerelease).

**Pull request merged**
