### PR TITLE
disable flaky PD test

### PR DESCRIPTION
**Pull request by lavalamp**
This test is failing often enough to block the merge queue. Moving to flaky.

### CODE REVIEW

**Comment by lavalamp** [comment]
@saad-ali to revert this when it's fixed.

**Comment by girishkalele** [comment]
LGTM

**Comment by lavalamp** [comment]
btw @girishkalele as build cop, this is the sort of thing you could consider merging manually.

**Comment by girishkalele** [comment]
@lavalamp Ah, feels good to use my buildcop superpowers !

**Comment by lavalamp** [comment]
You might need to manually resolve one more of these before this takes
effect...

**Pull request merged**
