### PR TITLE
Fix ipv6 ip allocation method for standard lb

### PR DESCRIPTION
**Pull request by aramase**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
In azure, standard loadbalancers require ipv6 public ip allocation method to be static. This PR checks the loadbalancer SKU and sets the allocation method based on the SKU.

Ref doc - https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-public-ip-address#create-a-public-ip-address

```
 If you select IPv6 for the IP version, the assignment method is Dynamic. If you select Standard for SKU, the assignment method is Static.
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
This LGTM, but I'll leave Pengfei or Andy to do final review.
/assign @feiskyer @andyzhangx 
/retest

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
