### PR TITLE
Re-enable node problem detector by default

### PR DESCRIPTION
**Pull request by Random-Liu**
Re-enable node problem detector started in gce cluster by default.

For now, in the master node, the node problem detector will be started and do nothing (see https://github.com/kubernetes/node-problem-detector/pull/13).

But in fact, in my test cluster, the master has no extra cpu to run the node problem detector, so node problem detector is started on all nodes except master, which is what we want but not expected...

@dchen1107 
/cc @kubernetes/sig-node 
/cc @andyzheng0831 for the gci script change.

[Analytics]()

### CODE REVIEW

**Comment by andyzheng0831** [comment]
The gci script change lgtm. To be safe, I suggest you to create a cluster and ssh into master for further verification. By default, the master will be running on gci image.

**Comment by Random-Liu** [comment]
@andyzheng0831 Thanks! I've checked the master node, the node-problem-detector manifest is indeed in `/etc/kubernetes/addons`. :)

**Comment by Random-Liu** [comment]
To avoid the `OutOfCPU` problem, I've updated the cpu request to `20m` and memory request to `10m`, which should be fine for normal case according to the benchmark result: https://github.com/kubernetes/node-problem-detector/issues/2#issuecomment-220255629.
Both cpu and memory are burstable.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@Random-Liu you can apply LGTM label once the test passed.

**Comment by Random-Liu** [comment]
Apply LGTM based on https://github.com/kubernetes/kubernetes/pull/26827#issuecomment-223724887.

**Pull request merged**
