### PR TITLE
fix updateJob scheduling of resync

### LINKED ISSUE #66071: oldJob create by curInterface
https://github.com/kubernetes/kubernetes/blob/82c986ecbcdf99a87cd12a7e2cf64f90057b9acd/pkg/controller/job/job_controller.go#L323

Here should be ` oldJob: = old. (* batch Job) `?

### PR DESCRIPTION
**Pull request by liggitt**
fixes #66071 

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @soltysh 
for approval

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
