### PR TITLE
Use a sane timeout for experimental upgrade jobs, and skip v1.1 tests

### PR DESCRIPTION
**Pull request by ikehz**
@spxtr Can you please make sure this hack actually builds/works?  😄

### CODE REVIEW

**Comment by spxtr** [comment]
Okay, the YAML tester is in. @k8s-bot unit test this issue: #IGNORE

**Comment by spxtr** [comment]
Looks good.

**Comment by ihmccreery** [comment]
@k8s-oncall please consider merging this manually.

**Comment by mikedanese** [comment]
I'll keep an eye on this but waiting for the build to unbreak right now.

**Pull request merged**
