### PR TITLE
delete unused code in proxy_server.go

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
/cc @deads2k @soltysh
for approval.

**Comment by qingsenLi** [comment]
/cc @deads2k @soltysh
thanks

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
