### PR TITLE
Change the gce constant for session affinity to have the capitalization shown in the documentation

### LINKED ISSUE #18347: GCE services type LoadBalancer
Hi, I have a problem with my GCE cluster about LoadBalancer type Services
```
Name:            us-colorcast
Namespace:        default
Labels:            app=us-colorcast
Selector:        app=us-colorcast
Type:            LoadBalancer
IP:            10.219.249.72
Port:            <unnamed>    3000/TCP
NodePort:        <unnamed>    31672/TCP
Endpoints:        10.216.1.6:3000
Session Affinity:    None
Events:
  FirstSeen    LastSeen    Count    From            SubobjectPath    Reason                Message
  ─────────    ────────    ─────    ────            ─────────────    ──────                ───────
  4m        4s        48    {service-controller }            CreatingLoadBalancer        Creating load balancer
  4m        3s        48    {service-controller }            CreatingLoadBalancerFailed    Error creating load balancer (will retry): Failed to create load balancer for service default/us-colorcast: failed to create target pool ab7db312f9da611e59dba42010af0006: googleapi: Error 400: Invalid value for: None is not a valid value, invalid
```

It's creating a lot of unused static external IP on the google network of my project
the cluster is running kubernetes v1.1.2.

Tried restarting nodes, tried destroy/recreate of the entire cluster.

### PR DESCRIPTION
**Pull request by roberthbailey**
(hopefully) Fixes #18347

/cc @a-robinson @thockin @zmerlynn

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
need a prio merge or ok to queue?

**Comment by a-robinson** [comment]
LGTM

**Comment by zmerlynn** [comment]
@thockin: Not yet. I can slap it in if needed, but we're trying to get the picky service changed first.

**Comment by lavalamp** [comment]
@thockin, I would say let's merge ASAP, I think that may be the fastest way to run all the tests against it.

@k8s-oncall

**Pull request merged**
