### PR TITLE
Update copyright date to trigger test/images build

### PR DESCRIPTION
**Pull request by hh**
/area testing

### CODE REVIEW

**Comment by mkumatag** [comment]
/hold
I'm not really convenienced with this approach, are there any other ways of triggering the build?

@claudiubelu @listx 

And what is the need for this trigger?

**Comment by claudiubelu** [comment]
> 
> 
> /hold
> I'm not really convenienced with this approach, are there any other ways of triggering the build?
> 
> @claudiubelu @listx
> 
> And what is the need for this trigger?

It's a postsubmit job which triggers whenever changes to ``kubernetes/test/images/*`` were made.

Merging a PR will create a **new** job. Alternatively, we can simply rerun one of the previous jobs in prow.

**Comment by hh** [comment]
My initial ask was to have @test-infra-oncall run the job manually:

https://kubernetes.slack.com/archives/C7J9RP96G/p1604941812107400

> Can I get someone from @test-infra-oncall to run this postsubmit when convenient. It's been broke for a while but I think it may be fixed now.
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images

**Comment by mkumatag** [comment]
> Can I get someone from @test-infra-oncall to run this postsubmit when convenient. It's been broke for a while but I think it may be fixed now.
> https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images

I see this job is failing since 2020-09-15, I can't really make out whats the problem looking at the logs, is there a way to look at the failure of the image build? @claudiubelu

**Comment by claudiubelu** [comment]
> 
> 
> > Can I get someone from @test-infra-oncall to run this postsubmit when convenient. It's been broke for a while but I think it may be fixed now.
> > https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images
> 
> I see this job is failing since 2020-09-15, I can't really make out whats the problem looking at the logs, is there a way to look at the failure of the image build? @claudiubelu

It seems this question fell of my radar, my bad.

So, that job as been split into multiple jobs, making them more atomic. There's now a job for each image, including the ones that were not included before in the ``all-conformance`` target. You can see all of them here: [1].

As for the job failing, indeed, there was an issue with docker buildx and the gcb image we were using to build the test images as it didn't have QEMU installed, meaning that it would fail to build images for arch types other than amd64. That has been fixed since then with a newer image, and I've also been tracking any other failures that have been happening and fixed them as I saw them.

Anyways, this PR will no longer trigger the image building job. As I've mentioned, the jobs are more atomic, and so is their trigger regex: the job for the image X will trigger when a change in the X image folder is made. I think it would be a good idea to trigger all the jobs since we haven't had all of them run since the split,

[1] https://testgrid.k8s.io/sig-testing-images

**Comment by claudiubelu** [comment]
all of the images have been rebuilt, and most of them have been promoted. We can close this now.

/close

**Pull request closed without merging**
