### PR TITLE
Update fluentd-gcp addon to 1.21.1

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: updates fluentd-gcp specs to use versions with a newer ubuntu base image. Functionally I expect no changes.

**Special notes for your reviewer**: it's infeasible to follow the regular cherry-pick process for this, since master is using a much newer version of fluentd-gcp, and we don't want to upgrade versions here.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by timstclair** [comment]
I don't think we need a release note for each one of these updates, but lets make sure the overall update is included in the release notes.

**Comment by ixdy** [comment]
builds for this PR should pass after #39765 is merged.

we need one more cherry-pick PR to update the kube-proxy base image.

**Comment by ixdy** [comment]
@k8s-bot test this

**Pull request merged**
