### PR TITLE
Clean up TODO around running test as sudo

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Re the TODO, this command no longer needs to be prefixed by `sudo`, as
the test is already running as `root`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by tanjunchen** [comment]
ref:https://github.com/kubernetes/kubernetes/issues/86756
@mattjmcnaughton  There are some TODO , we can deal with some of them.

**Comment by mattjmcnaughton** [comment]
cc @Random-Liu - mind taking a quick look when you get the chance? thanks :)

**Comment by derekwaynecarr** [comment]
A quick check appears that we skip running this test on existing PR checkers (unless I am mistaken), but the change generally looks good to me.  I will defer to @Random-Liu for final approve.

/lgtm

**Comment by mattjmcnaughton** [comment]
/assign @ConnorDoyle @klueska 

mind taking a quick look? This diff has been open for a while, and I'd love to get it closed. I haven't had much luck pinging the author of the TODO, but I think the change should be fairly non-controversial. Thanks!

**Comment by tanjunchen** [comment]
/cc @liggitt 
PTAL.Thanks

**Comment by mattjmcnaughton** [comment]
On Fri, Feb 14, 2020 at 04:33:05AM -0800, Kevin Klues wrote:
> /approve
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/87355#issuecomment-586269399

Thanks Kevin!

**Pull request merged**
