### PR TITLE
deep-copies: Structs cannot be nil

### PR DESCRIPTION
**Pull request by 0xmichalis**
@deads2k @wojtek-t

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.  I assume you've tried this downstream and it works?

**Comment by kargakis** [comment]
> lgtm. I assume you've tried this downstream and it works?

Yep.

**Comment by thockin** [comment]
What real issue is this fixing?  Isn't nil the zero-vale for most types, making this redundant?

**Comment by deads2k** [comment]
> What real issue is this fixing? Isn't nil the zero-vale for most types, making this redundant?

Given 
```go
type MyType struct{
    Subjects []ObjectReference
}
```

This generates code that attempts to assign `MyType.Subjects[i] = nil`, which causes compile errors.  That makes the generated deep-copies fail compilation.

**Comment by deads2k** [comment]
I should say, the existing code (before this fix) generates the broken code.  This fix stops it from doing that.

**Comment by kargakis** [comment]
> What real issue is this fixing? Isn't nil the zero-vale for most types, making this redundant?

The zero value for a struct is an empty struct of that kind. I was trying to generate deep copies in OpenShift and was getting compiler errors because ... structs cannot be nil:)

https://github.com/openshift/origin/pull/4663#issuecomment-142875205

**Comment by deads2k** [comment]
@thockin bump

**Comment by thockin** [comment]
@lavalamp who is looking at this code for a non-reflect rewrite.

**Comment by lavalamp** [comment]
I tend to think that if the set to nil is needed in some cases, then the correct fix is to set to the zero value for the struct? (my new stuff will make a change like that much easier, I hope)

**Pull request merged**
