### PR TITLE
move authoritative client-go util out of pkg

### PR DESCRIPTION
**Pull request by deads2k**
Move `client-go/pkg/util` which are authoritative to `client-go/util` to make it easier to reason about what comes from where.

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton @lavalamp I'll need approval for this and several other as we split out the repos.  If I haven't tested yet, but I can get general approval for the idea and simply apply the tag directly to the related pulls?  This is going to get really annoying for all of us if I can't.

**Comment by deads2k** [comment]
@sttts we talked about this.  Look good to you?

**Comment by deads2k** [comment]
experimenting with the approval tag

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by sttts** [comment]
lgtm. The only general question about dir structure of the client: I would prefer to have a clear distinction what is an API for the user and what is internal. What can we easily change without requiring another major client-go version? Otherwise, people will start using all the nice utils we move into the package. /cc @lavalamp @caesarxuchao

**Comment by deads2k** [comment]
> lgtm. The only general question about dir structure of the client: I would prefer to have a clear distinction what is an API for the user and what is internal. What can we easily change without requiring another major client-go version? Otherwise, people will start using all the nice utils we move into the package. /cc @lavalamp @caesarxuchao

I think we should probably claim only the API and client packages as compatible.  Someone ought to write an auto-versioning tool which detects changes to kick versions.  Once you have semantic versioning, that's a thing you need.

**Comment by deads2k** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
