### PR TITLE
Service Injection API Server

### PR DESCRIPTION
**Pull request by deads2k**
Create an API server for serving ServiceInjection resources.  This is a separate API server, from scratch, built against the generic apiserver library.  It includes:

 1. all storage binding options
 2. authentication
 3. authorization
 4. API types
 5. aggregatable

I've split it out in the commits I used as I built it.

@pmorie since you asked for a simple example of an API server
@jessfraz since your pull inspired this.
@pwittrock you're active in the pull.

### CODE REVIEW

**Comment by deads2k** [comment]
I used 

 1. `hack/local-up-cluster.sh`
 2. `nice make WHAT=cmd/kube-service-injection/`
 3. `./cmd/kube-service-injection/hack/build-image.sh`
 4. `kubectl create -n kube-system -f cmd/kube-service-injection/artifacts/static/static-pod.yaml --validate=false`
 5. `kubectl --username=foo --password=bar --server=https://localhost:9443 --insecure-skip-tls-verify get serviceinjections`
 6. `kubectl --username=foo --password=bar --server=https://localhost:9443 --insecure-skip-tls-verify create -f /home/deads/workspaces/kube/src/k8s.io/kubernetes/cmd/kube-service-injection/artifacts/example/example.yaml`
 7.  `kubectl --username=foo --password=bar --server=https://localhost:9443 --insecure-skip-tls-verify get serviceinjections`

**Comment by deads2k** [comment]
Added a commit to demonstrate how to run client, informer, and lister gen.  I didn't run though, since it would drown out this pull in generated artifacts.

**Comment by pwittrock** [comment]
@deads2k Thanks for this.  I am not clear on how this injects the information into Pods.  Is that part of this PR?  Would that be done with initializers?  Something else?

**Comment by deads2k** [comment]
> @deads2k Thanks for this. I am not clear on how this injects the information into Pods. Is that part of this PR? Would that be done with initializers? Something else?

You can write an admission plugin that reads these and drop it into kube.  The import ordering is a little odd for the short term, but at least the API server topology would be correct.

**Comment by pwittrock** [comment]
@deads2k Is it weird to have an AC compiled into the core k8s distro that requires an extension apiserver to be installed?  Or are you suggesting something else?

**Comment by deads2k** [comment]
> @deads2k Is it weird to have an AC compiled into the core k8s distro that requires an extension apiserver to be installed? Or are you suggesting something else?

It's a little weird, but its for an alpha feature and the structure would better position us moving forward.

**Comment by pwittrock** [comment]
@deads2k Been taking a closer look at this.  Seems like 2/3 of the code is boiler plate.  I am reading this correctly?  If so, do you think it is possible for us to factor out all the BP into a library?

**Comment by pwittrock** [comment]
cc @pmorie @lavalamp @duglin

@deads2k Thank you for this example.  It is giving me a much better picture of the state of the world.

I've spent an hour trying to reproduce the first commit, but have not been successful.  Am I simply trying to copy 200 lines boilerplate code spread across 3 different files in order to launch an apiserver that does effectively nothing, or is there something more to this?  This seems like it should be doable in 2-5 lines - a single function call in a main.go + an import statement for the k8s libraries.  *Optional* customization could be passed into the function using a struct without forcing a user to learn, understand, and hand-code all of the wiring upfront.

Some of the problems I am running into:

- The pkg/genericapiserver does not appear to exist in the [main repo on the master branch](https://github.com/kubernetes/kubernetes/tree/master/pkg).  This is making it pretty challenging to reproduce your example.  Running glide create / glide install fails because it can't find any of the libraries that it is supposed to.
- I finally just copied the glide file present in https://github.com/kubernetes-incubator/service-catalog/ which *IS* able to find the genericapiserver stuff.  However your example is slightly different then the service-catalog example.  For instance, it uses different uuid libraries.  This is resulting in compilation failures that I am trying to track down.  We need to standardize on how we instruct folks to set this stuff up if we are going to offer this as the solution for extending k8s.

Is there a reason the UX can't allow someone to incrementally specify the parts they require as they become needed?  e.g.:

- Step 1: create a main.go that runs an api-server: 2-5 lines
  - Have a working api server that can be run
- register new types.go - no validation, no defaulting, no subresources: 1-2 lines + types.go
  - Have a working api server that can persist resources
- add validation for types.go types - 1-2 lines + validation code
  - Everything above + validates resource values
- add defaulting for types.go  -  1-2 lines + defaulting code
  - Everything above + defaults resource field values
- add sub-resource - 1-2 lines + implementation of subresource
  - Everything above + implements subresources - e.g. scale
- add resource controller - 1-2 lines + an fn that accepts a resource as an argument
  - Everything above + control loop logic

I suspect this might be possible with some minimal refactoring.  If we add in code generation, we may be able to autowire everything together without forcing the user to add the 1-2 lines proposed above, and instead just put a comment directive in the types.go file.

Perhaps I am the only one having trouble with this?  Or maybe this is the direction we are already headed, but just haven't gotten there yet?

**Comment by pwittrock** [comment]
Looks like some packages got moved out of the main repo.  Seeing if I can get it working by referencing those.

**Comment by deads2k** [comment]
> @deads2k Been taking a closer look at this. Seems like 2/3 of the code is boiler plate. I am reading this correctly? If so, do you think it is possible for us to factor out all the BP into a library?

Much of it, yes.  It's not that we're unaware of the opportunities for making the code even easier to use, but in 1.5 there were correctness challenges and in 1.6 we've been dealing with dependency hell.

@sttts and myself are actively working in the area.  The eventual goal is to bring your Scheme and a default server can just wire through.

**Comment by deads2k** [comment]
> Perhaps I am the only one having trouble with this? Or maybe this is the direction we are already headed, but just haven't gotten there yet?

Yes.  The distance from 1.4 to there was too great to travel in even two releases.

**Comment by thockin** [comment]
I'm a poor reviewer for this for lack of context - can someone suggest a better reviewer?

I took a quick look, and the most immediate question is why this is in kubernetes/kubernetes?

**Comment by deads2k** [comment]
> I'm a poor reviewer for this for lack of context - can someone suggest a better reviewer?
> 
> I took a quick look, and the most immediate question is why this is in kubernetes/kubernetes?

It's just a sample API server implementation for a different proposal.  I think @pwittrock can consider it.

**Comment by deads2k** [comment]
> I took a quick look, and the most immediate question is why this is in kubernetes/kubernetes?

Also, that hit the nail on the head.  It's why I created this.

**Comment by kris-nova** [comment]
So I am also running into the same issues that @pwittrock is hitting

> The pkg/genericapiserver does not appear to exist in the main repo on the master branch.

He is right.. the genericapiserver package was moved out of package.. what gives?

> Looks like some packages got moved out of the main repo. Seeing if I can get it working by referencing those.

Anyway wondering if you could give some insight @deads2k onto how you are getting the `k8s.io/kubernetes/pkg/genericapiserver` package building on your end, and more importantly why are we referencing a package that no longer exists?

Cheers

**Comment by sttts** [comment]
@pwittrock @kris-nova it was just bad timing: genericapiserver got moved to `staging/src/k8s.io/apiserver` on friday. So @deads2k has to rebase and update the imports.

**Comment by deads2k** [comment]
I'm building a straight example server to use in integration tests as a separate repo to give people an example to copy that will stay up to date.

**Comment by pmorie** [comment]
We're not going to use this, so there is no need to rebase it.

**Comment by liggitt** [comment]
example server is live as well

**Pull request closed without merging**
