### PR TITLE
Add mattjmcnaughton as sig-node-reviewer

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Re discussions with dims@, dchen1107@, and derekwaynecarr@.

I meet the qualifications listed in
https://github.com/kubernetes/community/blob/master/community-membership.md.

**Special notes for your reviewer**:
cc @dchen1107 @dims @derekwaynecarr

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Thanks for stepping up @mattjmcnaughton 👍

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
