### PR TITLE
kubectl: correctly resolve whether options exist

### PR DESCRIPTION
**Pull request by zc2638**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
```
For example, `Root Command` may not set the run method, and the options resolution here will deviate
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by KnVerey** [comment]
Hi @zc2638 -- thanks for the PR! Could you please add more information about the problem this fixes? E.g. what does the end user of kubectl experience before/after this PR?

**Comment by zc2638** [comment]
> Hi @zc2638 -- thanks for the PR! Could you please add more information about the problem this fixes? E.g. what does the end user of kubectl experience before/after this PR?

`kubectl` is built with `cobra`,`cobra` is a nice tool, and some duplicate codes should be cleaned up(e.g. Run method of kubectl command),but it relies on the 'Runnable' attribute, resulting in some deviation in the display content after cleaning. It is suggested to use the correct judgment here to determine whether options are included.
@KnVerey

**Comment by pacoxu** [comment]
> what does the end user of kubectl experience before/after this PR?

I think you should provide how to reproduce it if it is a bug🤔.

**Comment by zc2638** [comment]
Thanks, it's not some very important modification, I won't spend more time on it.
@dims

**Pull request closed without merging**
