### PR TITLE
Default the --enable-cadvisor-endpoints flag to disabled

### PR DESCRIPTION
**Pull request by dims**
As part of #68522, Switching off the cAdvisor v1 Json API that we expose
directly. These include /stats/, /stats/container, /stats/{podName}/{containerName},
and /stats/{namespace}/{podName}/{uid}/{containerName}

**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
--enable-cadvisor-endpoints is now disabled by default. If you need access to the cAdvisor v1 Json API please enable it explicitly in the kubelet command line. Please note that this flag was deprecated in 1.15 and will be removed in 1.19.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @dashpole @derekwaynecarr 
cc @liggitt

**Comment by liggitt** [comment]
also note in the release note the planned timeframe for complete removal

**Comment by liggitt** [comment]
lgtm, but will defer to node reviewers

**Review by mattjmcnaughton — COMMENTED** [review]
Small nit: Could you please make it clear that the `--enable-cadvisor-endpoints flag is disabled by default`? Currently, the release note doesn't include the default, which is slightly confusing.

Also, re deleting `test/e2e/instrumentation/monitoring/cadvisor.go` - can you share more about the rationale for deleting the e2e test, as opposed to updating it so that it first turns cadvisor on? In other words, I'm wondering if there's benefit to keeping the `cadvisor` tests until the feature is completely deleted?

**Comment by liggitt** [comment]
> as opposed to updating it so that it first turns cadvisor on

Generally, e2e tests do not have the ability to modify cluster configuration in the already-running cluster. I suppose it could detect if the endpoints are available, and skip the test if they aren't.

**Comment by dims** [comment]
@mattjmcnaughton tweaked the release note description. In addition to what @liggitt said, we are going to drop this code in 1.19 and folks are not supposed to be using this :)

**Comment by brancz** [comment]
@dashpole can you make sure we follow up on the other 1.18 documented in #68522? Just so we can make sure that in 1.19 we can actually remove it?

/lgtm

**Comment by mattjmcnaughton** [comment]
On Wed, Jan 22, 2020 at 05:41:33AM -0800, Davanum Srinivas wrote:
> @mattjmcnaughton tweaked the release note description. In addition to what @liggitt said, we are going to drop this code in 1.19 and folks are not supposed to be using this :) 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/87440#issuecomment-577186758

Ok, that makes sense to me!

**Comment by Simwar** [comment]
Hey everyone, sorry to jump on this now but: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ is also outdated now.

Can someone update it (not sure about the process here) to specify that `--enable-cadvisor-json-endpoints` is set to false by default?

Thanks

**Pull request merged**
