### PR TITLE
Automated cherry pick of #43259

### PR DESCRIPTION
**Pull request by thockin**
Cherry pick of #43259 on release-1.5.

#43259: Fix polarity of a test in NodePort allocation

### CODE REVIEW

**Comment by thockin** [comment]
I don't understand the demands of the bot WRT cherrypicking.  Can someone clarify?  @grodrigues3  ?

**Comment by yujuhong** [comment]
> I don't understand the demands of the bot WRT cherrypicking. Can someone clarify? @grodrigues3 ?

Your original PR #43259 needs to have the "release-note" label. The point is that anything that's worth cherrypicking probably should have a release note.

> @mwielgus Are you the cherrypicker for 1.5?

@saad-ali is the right person to approve the cherrypick.

**Comment by thockin** [comment]
I added relnote, Saad said Marcin was "it" :)

**Comment by thockin** [comment]
ping @mwielgus

**Comment by mwielgus** [comment]
@thockin  The PR is missing LGTM.

**Comment by thockin** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
