### PR TITLE
Updating scripts to use v1 instead of v1beta3

### PR DESCRIPTION
**Pull request by nikhiljindal**
ref https://github.com/GoogleCloudPlatform/kubernetes/issues/10501

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Assigned to @lavalamp for another LGTM

**Comment by nikhiljindal** [comment]
Shippable is green and e2e passed as well!
@lavalamp Can you please take a look?

**Comment by lavalamp** [comment]
Every change in this looks good, but I did not read the entirety of every object to check for changes that may have been missed. Should I do that?

**Comment by nikhiljindal** [comment]
Extra eyes are always great :)

But I have gone through all of them. Hopefully Brian has too.
All the tests pass as well :)

**Comment by lavalamp** [comment]
lgtm

**Pull request merged**
