### PR TITLE
Automated cherry pick of #29881

### PR DESCRIPTION
**Pull request by fabioy**
Cherry pick of #29881 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30891)

### CODE REVIEW

**Comment by fabioy** [comment]
@dagnello Can you provide consent for the cla? Thanks.

**Comment by mikedanese** [comment]
@fabioy we don't need cla for cherry-picks of code already in the master branch

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue: #IGNORE

**Comment by timstclair** [comment]
@k8s-bot test this, issue: #IGNORE

**Comment by timstclair** [comment]
Promoting to P1 to get this in v1.3.6.

**Pull request merged**
