### PR TITLE
migrate logs to structed logging

### PR DESCRIPTION
**Pull request by fancc**
Migrate some logs to structured logging

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Ref:

[keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)
[Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Does this PR introduce a user-facing change?:**:
```
Migrate some log messages to structured logging
````

### CODE REVIEW

**Comment by bowei** [comment]
Change LGTM 

/lgtm

**Comment by wzshiming** [comment]
https://github.com/kubernetes/kubernetes/pull/98634/files#diff-e0f52066245ab5d2809127b194ca76f57481f345db0cbc8e6b6b510eb7790190L195

It seems that some logs have not changed?

**Comment by bowei** [comment]
cc: @rahulkjoshi

**Comment by adisky** [comment]
@fancc If you migrate logs of one package in one go then it would be quite easier for reviewers to review it.  see this https://github.com/kubernetes/kubernetes/pull/98643

**Pull request closed without merging**
