### PR TITLE
Switch queueset to operate on int64 time

### LINKED ISSUE #104831: Potential loss of precision in progress meter in queueSet
#### What happened:
This is nothing new, just something we have not yet gotten around to being fully careful about.  In the regular QueueSet implementation for API Priority and Fairness there is a progress meter called "virtual time" in most of the code, `R(t)` in the original fair queuing paper.  The current code represents this using a `float64` with units of seat-seconds.  There is a potential issue with loss of precision.  Each queueSet has an accumulator of seat-seconds that is incrementally updated at mutex entry, by adding the product of (real seconds since last update) X (dR/dt).  The latter factor is the allocation of seats that each queue gets,  which is abstractly a rational number that can be more or less than one.  It is less than one when the number of non-empty queues is greater than the total number of seats that the queueSet is allowed to occupy.  Hopefully it does not spend much time far below 1; even when it is not so tiny, we would like the floating-point number to be a reasonable approximation of the ideal rational number.

Consider an example scenario.  IIRC a `float64` has about 53 bits of precision.  As far as the Go `time` types are concerned, the seconds since last update can be as small as 10 ^ -9, or about 30 bits.  Consider a server that has been up for 2 ^ 20 seconds, about 12 days.  Suppose the queueSet is allocated 512 seats, 9 bits, and the queueSet has had at least that many non-empty queues that whole time.  That leaves us with 2 bits for the fractional part of dR/dt.  This is tight --- but the example is unrealistically aggressive.  What is less clear is what can be relied on.

#### What you expected to happen:
A queueSet should not run out of precision.  Well, that's a bit squishy, because there is the issue of how precisely to represent the rational numbers.  But you get the idea.

One approach would be to switch from 64 bits of floating-point to 64 bits of fixed-point.  That will help, but not firmly banish the problem.

A comprehensive solution would be to recognize that progress meter can be reset at any time, as long as we adjust all the readings that have been taken from the meter.  That means adjusting not only the queueSet's R meter, but the "virtual start time" (i.e., R(next dispatch time)) of each queue.  The resets would only need to be done very infrequently, to prevent loss of precision.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18 to current.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix https://github.com/kubernetes/kubernetes/issues/104831

```release-note
NONE
```

/sig api-machinery
/priority important-soon
/kind bug

/assign @MikeSpreitzer 

/cc @tkashem

### CODE REVIEW

**Comment by tkashem** [comment]
LGTM

I will rebase #104831 on top if it.

**Comment by wojtek-t** [comment]
Thanks!

I will wait for @MikeSpreitzer to also take a look.

**Comment by MikeSpreitzer** [comment]
The quantity in question is not "time", it is "work".

It looks like this PR proposes to use fixed point, seat-seconds X `10^9`.  As noted in #104831, that particular scale factor may not be our best use of bits.

I will have more to say later.

**Comment by wojtek-t** [comment]
> It looks like this PR proposes to use fixed point, seat-seconds X 10^9. As noted in #104831, that particular scale factor may not be our best use of bits.

@MikeSpreitzer  No - it's seat-microseconds - so seat-second x 10^6. This should address your bit concerns.

**Comment by MikeSpreitzer** [comment]
Oh, right, I overlooked the last part of

>  	qs.virtualTime += time.Duration(float64(nanosecondsSinceLast) * qs.getVirtualTimeRatioLocked()).Microseconds()

The bits crunch that I referenced is for a IEEE 64 bit float.  If we use unsigned int, then I am more sanguine about 30 bits of fraction.  We could spend 10 bits on seats (which would be a lot, since we only ever calculate the seat-seconds figure per queue) and still have 24 bits for seconds (roughly half a year).  OTOH, if we spend 20 bits on fraction, 10 bits on seats, that leaves 34 bits for seconds --- far more than we could possibly need.  But using only 20 bits for fraction worries me.  A microsecond is a long time nowadays.  I would rather spend 30 bits on fraction and planning dropping the other shoe (adding code to move the epoch forward when needed) in another PR.  Still another option would be to use an intermediate number of fraction bits.  But not dropping that other shoe requires us to make some pretty firm statement about how long a server can run or how fast the code can run.  I would rather just use a generous amount of fraction bits and implement epoch adjustment.

**Comment by MikeSpreitzer** [comment]
I also think that we should isolate the choice of the scale factor to just one place in the code.  Introduce something like

```
type SeatSeconds uint64 // fixed point with some fraction bits

func (ss SeatSeconds) String() string {...}

func SeatsTimesSeconds(seats float64, seconds float64) SeatSeconds {...}

func SeatsTimesDuration(seats float64, duration time.Duration) SeatSeconds {...}
```

**Comment by wojtek-t** [comment]
> But using only 20 bits for fraction worries me. A microsecond is a long time nowadays.

@MikeSpreitzer - as I mentioned in some of the bugs - I've never seen a request taking less than hundreds of microseconds.
So we have two orders of magnitude between our granularity.
Do you have any data or some kind of argument showing that "microsecond-seat" will not give us enough granularity?
Based on all data that I have - I just don't believe we need more granularity.

OTOH - I've seen servers that were running for more than half-an-year without restart. So I'm reluctant for going to "nanosecond-seat" precision. Maybe "10ns-seat or 100ns-seat" would work - but that's somewhat counterintuitive.


> Introduce something like the following so that the rest of the code does not care.

Introuducing a dedicate type makes sense, though I'm not sure how to interpret what you wrote above..

> type SeatSeconds uint64 // fixed point with some fraction bits

I don't understand it - uint64 doesn't have fraction. So it would be "Seat-Microseconds", or sth like that anyway...
So I think we should first converge on the first point before making this change.

**Comment by MikeSpreitzer** [comment]
The time intervals that are relevant here are not the time to serve a request but the time between method calls on the same queueset.

I will draft an example of a datatype for seat-seconds.

**Comment by MikeSpreitzer** [comment]
dR/dt can be C / numNonemptyQueues, which can be well under 1.

**Comment by wojtek-t** [comment]
> I will draft an example of a datatype for seat-seconds.

OK - let's proceed with your PR - I commented on that (and I'm closing this one).

**Pull request closed without merging**
