### PR TITLE
Improve fluentd parsing of etcd.log files (including severity)

### PR DESCRIPTION
**Pull request by boeboe**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by crassirostris — CHANGES_REQUESTED** [review]
SGTM, thanks a lot for you contribution!

Could you please also bump the image version? You can take a look at, for example, https://github.com/kubernetes/kubernetes/pull/41407. I will build an image once you're changed the version

It will be obsolete with time, but for now it's necessary to keep track of all the changes

**Comment by boeboe** [comment]
Done... version bumped

**Comment by Crassirostris** [comment]
@boeboe Thanks! LGTM, please rebase and squash commits

BTW, do you want to update the config for fluentd-gcp also? (`cluster/addons/fluentd-gcp/fluentd-gcp-image/fluent.conf`)

**Review by crassirostris — APPROVED** [review]

**Comment by boeboe** [comment]
@Crassirostris 

Image also updated for gcp...

**Comment by Crassirostris** [comment]
@boeboe Last nit: you also need to change `cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml`, as mentioned at the beginning of the `fluentd-gcp-ds.yaml`

Other than that, everything looks fine :)

**Comment by boeboe** [comment]
@Crassirostris

saltbase updated as well

**Comment by Crassirostris** [comment]
@boeboe Built and pushed new images, tests should pass now

Squash commits please and I will LGTM

**Comment by Crassirostris** [comment]
@boeboe Do you need any help?

**Comment by boeboe** [comment]
@Crassirostris  commits should be squashed now (had some problems, not realizing I had to use --force to push squashed commits)

**Comment by Crassirostris** [comment]
@boeboe you should also run `git rebase upstream/master` (if `upstream` is the name of the `kubernetes/kubernetes` repo), because some files were changed in the repo meanwhile

**Comment by boeboe** [comment]
Rebase done

**Comment by Crassirostris** [comment]
@boeboe I'm very sorry to slow you down on this, but could you please rename your commits to have a meaningful name?

Here's a great doc about workflow and a reasoning behind squashing commits: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#when-to-retain-commits-and-when-to-squash

**Comment by ethernetdan** [comment]
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by Crassirostris** [comment]
@boeboe Please rebase it once https://github.com/kubernetes/kubernetes/pull/42126 and https://github.com/kubernetes/kubernetes/pull/42130 are merged. Now that we moved configuration out of the image, for fluentd-gcp it's enough to change two files: ConfigMap and a static pod spec in salt.

**Comment by crassirostris** [comment]
@boeboe Do you need more help with this PR?

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by crassirostris** [comment]
@spiffxp Why? :)

**Comment by spiffxp** [comment]
@crassirostris trying to remove friction, PR's are more likely to be reviewed if they've been tested (though I agree, in this case the author hasn't been active, and it needs rebasing... but every little bit helps)

**Comment by crassirostris** [comment]
@spiffxp Oh, sure, I see, thanks for making this clear to me :)

To explain myself, I didn't remove the label before because these changes used to require the image build/push prior to the test runs. I'm extremely sorry if it discouraged the author, I will be more aware in the future!

**Comment by marun** [comment]
This doesn't appear to need to target v1.7, moving to v1.8.

**Pull request closed without merging**
