### PR TITLE
Revert to Go 1.4.2

### PR DESCRIPTION
**Pull request by zmerlynn**
Reverts #19985, see #20400 for context.

cc @brendandburns @wojtek-t @gmarek 
cc @luxas (this will block #19769 until 1.3)

### CODE REVIEW

**Comment by luxas** [comment]
@zmerlynn I don't think #19769 has a hard dependency on `go1.5`, I think it's just easier. Will test it though. Would really like #19769 merged before `v1.2`

**Comment by zmerlynn** [comment]
@luxas: That's fine, just a heads up. :)

**Comment by zmerlynn** [comment]
Travis is currently borked and I'd like to get this in before Poland wakes up so we can see if #20400 is fixed. @k8s-oncall, mind a hand merge?

**Comment by saad-ali** [comment]
Will do

**Comment by wojtek-t** [comment]
@zmerlynn @saad-ali - thanks a lot for it!

**Comment by lavalamp** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/20656-- we have to
understand this, we can't stay on go1.4.2 forever.

**Pull request merged**
