### PR TITLE
Kubelet event logging is classified as V(3)

### PR DESCRIPTION
**Pull request by smarterclayton**
Important, but not strictly required for normal operation V(2)

### CODE REVIEW

**Comment by pmorie** [comment]
@smarterclayton Do we have a rubric for what each level should be?

**Comment by smarterclayton** [comment]
`docs/devel/logging.md`

----- Original Message -----

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
Unless @pmorie has any concerns

**Comment by saad-ali** [comment]
Curious, what the primary driver for this is? Logs getting too big?

**Comment by smarterclayton** [comment]
Almost all events are represented elsewhere, and if they fail they are usually logged as well.  At default levels the kubelet was spitting out tons of logs, instead of only meaningful logging.

**Comment by saad-ali** [comment]
SGTM

**Comment by satnam6502** [comment]
No issue, milestone or risk level, but given the small nature of the change I will merge anyway.

**Comment by satnam6502** [comment]
But I think this needs a rebase first.

**Pull request merged**
