### PR TITLE
Add special tag for disabling ESIPP and HPA-related tests on large clusters

### PR DESCRIPTION
**Pull request by shyamjvs**
As discussed offline, this would help improve accountability for tests needing some love from scalability perspective.

/cc @porridge 
fyi - @MrHohn @MaciekPytel @mwielgus @crassirostris 

@kubernetes/sig-scalability-misc

### CODE REVIEW

**Review by porridge — COMMENTED** [review]
/lgtm
I'm assuming the other part is in `test-infra`?
Also, do we still need `SkipUnlessNodeCountIsAtMost`?

**Comment by shyamjvs** [comment]
> I'm assuming the other part is in test-infra?

Yes - https://github.com/kubernetes/test-infra/pull/5527

> Also, do we still need SkipUnlessNodeCountIsAtMost?

I've removed wherever we were using it earlier for our purpose. But it's still being used at one other place, but that seems unrelated (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/disruption.go#L148).

**Comment by shyamjvs** [comment]
Ref issues https://github.com/kubernetes/kubernetes/issues/54637, https://github.com/kubernetes/kubernetes/issues/52495

**Pull request merged**
