### PR TITLE
OpenStack updates

### PR DESCRIPTION
**Pull request by anguslees**
This is a mash of several unrelated commits, that I really should split up - but wanted to make other people aware of before we duplicate work.

Essentially:
- Some updates to the openstack provider that no-one will care about
- Updates to reach nodes via .Status.HostIP rather than assuming .Name is resolvable
- Fix races between image pull and image garbage collection

### CODE REVIEW

**Comment by bgrant0607** [comment]
Is this PR still active?

**Comment by anguslees** [comment]
Good question.  Let me pull out the non-openstack parts to make this easier to approve...

**Comment by nikhiljindal** [comment]
Any update?

**Comment by anguslees** [comment]
@googlebot: My employer (Rackspace) has signed the Google CLA on my behalf.

**Comment by anguslees** [comment]
I've removed/separated the controversial bits that were in the original comment, and this is now just the boring OpenStack bits.

**Comment by brendandburns** [comment]
LGTM, merging.

**Comment by brendandburns** [comment]
ugh, needs a rebase.  Sorry!

**Comment by nikhiljindal** [comment]
@anguslees : Can you please rebase?

**Comment by anguslees** [comment]
Rebased.  I've also included a (non-legacy) NodeAddresses implementation in the last commit.

**Comment by bgrant0607** [comment]
LGTM

**Review by rjkmurray — COMMENTED** [review]
Nodes are coming clean, did you map the sequence of events, I wouldn't be able to recreate that set of specific parameters again. Probably  a critical  update for years down the road releas4

**Pull request merged**
