### PR TITLE
automated-cherry-pick-of-#74789-upstream-release-1.13

### LINKED ISSUE #74790: ￼Kubectl shows last<invalid> if pv, pod or pvc is terminating using kubectl describe pv xxx
**What happened**:
 ￼Kubectl describe pv xxx  shows last<invalid> if pv is terminating
image

I found pvc and pod  have the same issue

**What you expected to happen**:
Terminating (lasts 10s)
**How to reproduce it (as minimally and precisely as possible)**:
1 create  a pv, pvc or pod is terminating
2 using kubectk describe xxx
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
#74789 Bugfix: kubectl shows last<invalid> if pv, pod, pvc is terminating
 fix #74790

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74790

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the pick, but I don't think this is a severe/critical enough issue to warrant a cherrypick

**Comment by cwdsuzhou** [comment]
> thanks for the pick, but I don't think this is a severe/critical enough issue to warrant a cherrypick

Yes, it's not a severe/critical enough issue, but currently pod `terminanting` may be common. It will interfere with judging if a pod is deleted normally, especially when `TerminationGracePeriodSeconds` and `Prestop action` are set.

**Pull request closed without merging**
