### PR TITLE
clean unused variables on serviceaccounts_controller_test.go

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
this patch simply removes unused variables 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@thockin PTAL

**Review by MrHohn — APPROVED** [review]
/lgtm

**Pull request merged**
