### PR TITLE
Curating Owners: cmd/kubeadm

### PR DESCRIPTION
**Pull request by apelisse**
cc @jbeda @mikedanese @luxas @errordeveloper

In an effort to expand the existing pool of reviewers and establish a
two-tiered review process (first someone lgtms and then someone
experienced in the project approves), we are adding new reviewers to
existing owners files.

If You Care About the Process:
------------------------------

We did this by algorithmically figuring out who’s contributed code to
the project and in what directories.  Unfortunately, that doesn’t work
well: people that have made mechanical code changes (e.g change the
copyright header across all directories) end up as reviewers in lots of
places.

Instead of using pure commit data, we generated an excessively large
list of reviewers and pruned based on all time commit data, recent
commit data and review data (number of PRs commented on).

At this point we have a decent list of reviewers, but it needs one last
pass for fine tuning.

Also, see https://github.com/kubernetes/contrib/issues/1389.

TLDR:
-----

As an owner of a sig/directory and a leader of the project, here’s what
we need from you:

1. Use PR https://github.com/kubernetes/kubernetes/pull/35715 as an example.

2. The pull-request is made editable, please edit the `OWNERS` file to
remove the names of people that shouldn't be reviewing code in the future in
the **reviewers** section. You probably do NOT need to modify the **approvers**
section. Names asre sorted by relevance, using some secret statistics.

3. Notify me if you want some OWNERS file to be removed.  Being an
approver or reviewer of a parent directory makes you a reviewer/approver
of the subdirectories too, so not all OWNERS files may be necessary.

4. Please use ALIAS if you want to use the same list of people over and
over again (don't hesitate to ask me for help, or use the pull-request
above as an example)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36393)

### CODE REVIEW

**Comment by apelisse** [comment]
his name is missing from the list, but consider adding "AdoHe"

**Comment by luxas** [comment]
This LGTM, but we're gonna split kubeadm out of this repo soon so I don't see it as critical

cc @kubernetes/sig-cluster-lifecycle opinions on who should be in the reviewers list?

**Comment by jbeda** [comment]
Kubeadm won't be split out until we figure out a multi-repo release process.  That is still in process, as far as I know.

I'm okay with this list as a start -- we can always add more later.  I'm going to tag folks here and give this a day or two before approve as I don't want to sign anyone up until they are ready.

@errordeveloper @luxas @mikedanese @justinsb @pires @lukemarsden @dgoodwin 

@apelisse -- any ideas why we have OWNERS at both `kubeadm` and `kubeadm/app`?  I'm assuming this stuff was hierarchical and having at the base is enough.

**Comment by pires** [comment]
Count me in.

**Comment by apelisse** [comment]
@jbeda Most of this has been automatically generated, I'd be more than happy to remove what is useless though. I'll remove `kubeadm/app/OWNERS`. Thanks for letting me know that it's useless :-)

**Comment by jbeda** [comment]
@apelisse -- I suspect it is redundant but I'm not 100% sure.  Do you know where the code is for the bots that interpret this stuff?

**Comment by apelisse** [comment]
@jbeda It's being written at this time. If it's reasonable that `kubeadm/` and `kubeadm/app` should have the same list of people (and I suspect they do), then it makes more sense to just remove the latter `OWNERS` file.

**Comment by dgoodwin** [comment]
I would be happy to help.

**Comment by mikedanese** [comment]
Please remove the second file. I agree that it's redundant.

**Comment by apelisse** [comment]
@mikedanese Removed the second file. Please LGTM if it's OK. Thanks!

**Pull request merged**
