### PR TITLE
Automated cherry pick of #97764 upstream release 1.18: ignore cgroup driver check in windows node upgrade

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
cherry-pick of #97764 for kubernetes-sigs/sig-windows-tools#138

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet should ignore cgroup driver check on Windows node.
```

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
/priority important-soon
/triage accepted
/assign @mrunalp 

@kubernetes/release-managers

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
