### PR TITLE
prune's xml files to display only top level tests and failed sub-tests

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Instead of https://github.com/kubernetes/kubernetes/pull/117029

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Previously reviewed in https://github.com/kubernetes/kubernetes/pull/117029#pullrequestreview-1444360343 and now also enables the pruning by default.

**Comment by Rajalakshmi-Girish** [comment]
@pohly when does the merge happen?

**Comment by pohly** [comment]
When moving to a different PR you lost the `approved` tag from https://github.com/kubernetes/kubernetes/pull/117029#issuecomment-1563262184. I don't have approval rights for it.

What you can do is re-open that other PR, then force push the content of [Rajalakshmi-Girish:prune-junit-xml1](https://github.com/Rajalakshmi-Girish/kubernetes/tree/prune-junit-xml1) to [Rajalakshmi-Girish:prune-junit-xml](https://github.com/Rajalakshmi-Girish/kubernetes/tree/prune-junit-xml). I can LGTM there and it should merge.

`git push <your remote> +prune-junit-xml1:prune-junit-xml` should work.

**Comment by Rajalakshmi-Girish** [comment]
> git push <your remote> +prune-junit-xml1:prune-junit-xml

Thanks, I did what you said.
Can you please check https://github.com/kubernetes/kubernetes/pull/117029

**Pull request closed without merging**
