### PR TITLE
Mark kubelet's master-service-namespace flag deprecated

### PR DESCRIPTION
**Pull request by mtaufen**
This flag is already deprecated in the API server:
- https://kubernetes.io/docs/admin/kube-apiserver/
- https://kubernetes.io/docs/admin/federation-apiserver/

It doesn't really make sense to adjust this on the Kubelet if you can't change it on the API server anymore.

```release-note
Marks the Kubelet's --master-service-namespace flag deprecated
```

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM
@mtaufen PR needs rebase.

**Comment by mtaufen** [comment]
Rebased

**Comment by mtaufen** [comment]
@wojtek-t please see for approval

**Pull request merged**
