### PR TITLE
AWS: Some images require volume mounts on /dev/xvdX

### PR DESCRIPTION
**Pull request by justinsb**
It seems impossible to determine from outside.  Thankfully we're running
the attachment from inside the instance, so can check for /dev/sdX or
/dev/xvdX.

More modern images seem to be moving to /dev/xvdX

### CODE REVIEW

**Comment by bprashanth** [comment]
@iterion for review, assigned to CJ from a blame on the corresponding gce file

**Comment by thockin** [comment]
LGTM - self contained, at least

**Comment by cjcullen** [comment]
LGTM.
@mohr or @robertbailey for a final rubber stamp.

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
