### PR TITLE
allow the scheduler to read it's config from a configmap

### PR DESCRIPTION
**Pull request by mikedanese**
WIP
cc @davidopp

### CODE REVIEW

**Comment by davidopp** [comment]
From
docs/admin/kube-scheduler.md
it looks like this isn't finished yet -- is that correct?

**Comment by davidopp** [comment]
ping

**Comment by mikedanese** [comment]
Brian says he doesn't want this. He wants the components to just read a file.

**Comment by davidopp** [comment]
Wait, we're getting rid of the entire idea of having Kubernetes components read their config from ConfigMap?

**Comment by mikedanese** [comment]
@davidopp no, the scheduler will use a configmap but it will be configured in the pod manifest. The config will be mounted into the pod and the scheduler will read it from disk. This assumes the scheduler is running in some sort of pod (which is usually true nowadays).

**Comment by smarterclayton** [comment]
I kind of agree in general - it's one less point of variation.  Would
Kubelets be a special case then?

**Comment by derekwaynecarr** [comment]
+1 to read from file that is sourced from a config map rather than the
config map itself.

**Pull request closed without merging**
