### PR TITLE
Fix GKE kube-up to correctly find an IGM from a multi-zone cluster

### PR DESCRIPTION
**Pull request by a-robinson**
I've confirmed that this successfully brings up a cluster, fixing the immediate issue with the new e2e test. Sorry about not properly vetting it in the original PR (#24075).

This does cause a warning message to be printed based on the handling of the NUM_NODES variable though, which I could fix if you guys think it's worth it:

```
Detected 6 ready nodes, found 6 nodes out of expected 3. Found more nodes than expected, your cluster may not behave correctly.
```

@quinton-hoole

### CODE REVIEW

**Comment by a-robinson** [comment]
Never mind about the warning message I mentioned initially, I've gone ahead and hacked up a small fix for it.

**Comment by jlowdermilk** [comment]
This lgtm as far as validating cluster is functional. Does the e2e test for nodes in expected zones?

**Comment by a-robinson** [comment]
No, kube-up doesn't error out if the number if nodes is too high, it just prints a warning.

The important part of this PR is the added grep on ZONE, which keeps the script from choking on trying to get an IGM that isn't in ZONE.

**Comment by a-robinson** [comment]
@k8s-oncall request for a manual merge. This fixes a bug in the repeatedly failing kubernetes-e2e-gke-multizone test suite.

**Pull request merged**
