### PR TITLE
Optimize code for SetDefaults_NodeResourcesBalancedAllocationArgs

### PR DESCRIPTION
**Pull request by xiaomudk**
#### What type of PR is this?
/kind cleanup
/kind flake

#### What this PR does / why we need it:
Remove unnecessary code and improve execution efficiency

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by xiaomudk** [comment]
@kerthcet  `ok-to-test` is spelled wrong, can you resend it, thanks!

**Comment by kerthcet** [comment]
This `Additional documentation` should be blank if the pull request does not require a release note, you can add it to `What this PR does` instead

**Comment by xiaomudk** [comment]
@kerthcet I have edited, thanks for the reminder 🙏

**Comment by kerthcet** [comment]
Thanks @xiaomudk

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
