### PR TITLE
test: Fix node e2e shutdown test flake

### LINKED ISSUE #116318: Test failure: graceful-node-shutdown (GracefulNodeShutdown [Serial] [NodeFeature:GracefulNodeShutdown] [NodeFeature:GracefulNodeShutdownBasedOnPodPriority] when gracefully shutting down with Pod priority should be able to gracefully shutdown pods with various grace periods) - Failure cluster [3ee80f0d...]
##### Error text:
```
[FAILED] Timed out after 10.000s.
Expected success, but got an error:
    <*errors.errorString | 0xc0019c4be0>: {
        s: "pod (graceful-node-shutdown-2936/period-a-5-f099b778-08ba-40f0-a543-0f4d20bafdd5) should be shutdown, reason: ",
    }
    pod (graceful-node-shutdown-2936/period-a-5-f099b778-08ba-40f0-a543-0f4d20bafdd5) should be shutdown, reason: 
In [It] at: test/e2e_node/node_shutdown_linux_test.go:539 @ 03/04/23 06:06:13.522

```
#### Recent failures:
[3/6/2023, 11:34:56 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1632826614901379072)
[3/6/2023, 11:21:00 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1632823595031859200)
[3/6/2023, 10:20:47 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1632808440537550848)
[3/6/2023, 9:47:47 AM ci-cos-cgroupv1-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-serial/1632800135534612480)
[3/6/2023, 7:35:45 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1632766161345056768)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by bobbypage**
Bump the timeout as the previous timeout was sometimes too short, resulting in the pod status update not sent. Also, fixed a typo in previous refactor (https://github.com/kubernetes/kubernetes/pull/115693)

#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #116318

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
Ran locally, test passed on 5 runs - https://gist.github.com/769a19aa44aebc9d3305945f77b55434

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
