### PR TITLE
Automated cherry pick of #33796

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #33796 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34557)

### CODE REVIEW

**Comment by jingxu97** [comment]
@saad-ali This is the fix for AWS issue. PTAL.

**Comment by jingxu97** [comment]
@k8s-bot gce e2e test this

**Comment by jingxu97** [comment]
@k8s-bot cvm gce e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cvm gce e2e test this

**Comment by saad-ali** [comment]
@k8s-bot bootstrap gce e2e test this

**Comment by saad-ali** [comment]
@k8s-bot kubemark e2e test this

**Pull request closed without merging**
