### PR TITLE
cherry-pick: #51768 Delete the federation namespace from fcp instead of individual objects

### PR DESCRIPTION
**Pull request by shashidharatd**
Ref #51768
-->
```release-note
NONE
```

/assign @madhusudancs

### CODE REVIEW

**Comment by dims** [comment]
@calebamiles @jdumars - Can you please push this along? ( cc @kubernetes/kubernetes-release-managers ) 

`PR is missing CLA label; needs one of cla: yes, cncf-cla: yes or cla: human-approved`

**Comment by shashidharatd** [comment]
not sure why `cncf-cla: yes` label is not applied to this PR and also remove do-not-merge/cherry-pick-not-approved. @madhusudancs, can you do that?
Thanks in advance. :)

**Comment by madhusudancs** [comment]
Release-bound PRs must be approved by the release team. 

@kubernetes/kubernetes-release-managers can you please take a look?

Also, @kubernetes/sig-contributor-experience-bugs could you please look at the CLA issue. @shashidharatd has been working on Kubernetes for more than a year now. He is also in the OWNERs files as both reviewer and approver. I am not entirely sure why `cla: yes` is not being applied to this PR.

**Comment by dims** [comment]
/retest

@shashidharatd we still need this right?

**Comment by csbell** [comment]
@dims: Yes, we leak pvc resources in our test jobs without this.

**Comment by dims** [comment]
Thanks @csbell Darn 2 jobs seem stuck, will run retest

/retest

**Comment by csbell** [comment]
Bazel build issues seem to be resolved based on my reading of #sig-testing 
/test pull-kubernetes-e2e-gce-bazel

**Comment by csbell** [comment]
@wojtek-t Can you merge this PR into release-1.7 so we stop leaking PVC and keep green lawns like 1.8 and head.

**Pull request merged**
