### PR TITLE
partially cleanup hack/jenkins/...

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Removes dead / unused scripts, updates the jenkins docs to reflect the current state (as of at least a year ago...)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @spiffxp

### CODE REVIEW

**Comment by BenTheElder** [comment]
The remaining scripts in this directory still appear to be actively used by CI. 

**For follow up:**

We should consider if we care enough to move this to a `hack/ci` or similar in the future (maybe move the scripts, add stubs in the old locations, update CI, remove the stubs?) /shrug

We should also consider if we even need the integration and verify scripts versus the make target(s) ...

**Comment by spiffxp** [comment]
/lgtm
I looked with cs.k8s.io and the most I could find referencing these were out-of-date comments

**Comment by spiffxp** [comment]
>We should also consider if we even need the integration and verify scripts versus the make target(s) ...

That's sort of where I'm at after looking at these.  They're not referenced in the repo at all.  They seem like they should be part of the CI job rather than in this repo, or the CI jobs should be updated to invoke these targets the same way developers would

**Pull request merged**
