### PR TITLE
Refactor git repo volume to separate builder and cleaner

### LINKED ISSUE #9139: Volume plugins Builder/Cleaner can be type-asserted incorrectly
For many of the volume plugins, we do something like:

```
func NewBuilder(...) volume.Builder {
  return &whatever {
      name: ...
      type: ...
      path: ...
  }
}

func NewCleaner(...) volume.Cleaner {
  return &whatever {
      name: ...
  }
}
```

Specifically we return the same type but only partially filled in (since we only have partial info at Cleaner time).  Unfortunately, Go will let you type-assert a Cleaner to a Builder in this case.  But calling Builder methods WILL NOT WORK.

Instead, we should have distinct types for whateverBuilder and whateverCleaner that embed a common core which implements volume.Plugin.

@markturansky

### PR DESCRIPTION
**Pull request by pmorie**
Resolves #9139 for git repo volumes.

@thockin

### CODE REVIEW

**Comment by mikedanese** [comment]
Needs rebase

**Comment by thockin** [comment]
LGTM

**Comment by mikedanese** [comment]
@pmorie please rebase

**Comment by pmorie** [comment]
@mikedanese @thockin Rebased

**Comment by mikedanese** [comment]
```
!!! 'gofmt -s' needs to be run on the following files:
./pkg/volume/git_repo/git_repo.go

**Comment by pmorie** [comment]
@mikedanese how embarrassing

**Comment by mikedanese** [comment]
:) fyi @lavalamp all green

**Pull request merged**
