### PR TITLE
Bump go-openapi/jsonpointer and go-openapi/jsonreference versions

### LINKED ISSUE #75653: ci-kuberentes-verify and pull-kubernetes-verify are failing in master, 1.13, 1.14
**Which jobs are failing**:
`ci-kubernetes-verify-beta`

**Which test(s) are failing**:
`verify.godeps` [kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647)

**Since when has it been failing**:
Test has been failing since 3/24, at 9:19

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#verify-1.14

**Reason for failure**:
Error during `hack/verify-godeps.sh`:
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-03-25 02:24:42.529814436 +0000
+++ /tmp/gopath.tmXTzL/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-03-25 03:08:44.614866981 +0000
@@ -1758,12 +1758,12 @@
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonpointer",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonreference",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "8483a886a90412cd6858df4ea3483dce9c8e35a3"
 		},
 		{
Godeps Verify failed.
If you're seeing this locally, run the below command to fix your Godeps.json:
patch -p0 < godepdiff.patch
(The above output can be saved as godepdiff.patch if you're not running this locally)
(The patch file should also be exported as a build artifact if run through CI)
Copying patch to artifacts..
Leaving /tmp/gopath.tmXTzL for you to examine or copy. Please delete it manually when finished. (rm -rf /tmp/gopath.tmXTzL)
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-godeps.sh	825s
```
Due to release v0.19.0 of
[go-openapi/jsonpointer/releases](https://github.com/go-openapi/jsonpointer/releases)
and [go-openapi/jsonreference/releases](https://github.com/go-openapi/jsonreference/releases)
the morning of 3/23.

/milestone v1.14
/kind failing-test
/priority critical-urgent

/cc @smourapina @mariantalla @kacole2 @mortent @spiffxp @nikopen

### PR DESCRIPTION
**Pull request by alejandrox1**
xref: #75653

Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Bump github.com/go-openapi/jsonpointer and github.com/go-openapi/jsonreference from v0.18.0 to v0.19.0 to fix test failures in 1.14-blocking dashboard, xref: #75653

**Which issue(s) this PR fixes**:

Fixes #75653

**Special notes for your reviewer**:
Note that this PR is directly to master, unlike #75656 which is to the 1.14 branch.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/assign @spiffxp @mariantalla
/priority critical-urgent
/sig testing
/milestone v1.14

### CODE REVIEW

**Comment by alejandrox1** [comment]
Failure on [pull-kubernetes-verify#126863](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/75659/pull-kubernetes-verify/126863) seems weird since it seems to have passed before this commit so i'll give it another try just to make sure.

/test pull-kubernetes-verify

**Comment by mariantalla** [comment]
/hold
for now, see comment: https://github.com/kubernetes/kubernetes/issues/75653#issuecomment-476132119

**Comment by mariantalla** [comment]
Because of: https://github.com/kubernetes/kubernetes/issues/75653#issuecomment-476144680, I'm comfortable with this merging, at least in `master`.

/hold cancel
/lgtm

**Comment by liggitt** [comment]
doesn't this need to be changed in all Godeps.json files that reference that sha?

```
$ grep -R ef5f0afec364d3b9396b7b77b43dbe26bf1f8004 Godeps staging
Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/sample-cli-plugin/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/cli-runtime/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/apiserver/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json:			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
```

**Comment by alejandrox1** [comment]
I thought so, but for example, the `pull-kubernetes-verify` job seems to run the same as `verify.godeps` in master-blocking and 1.14-blocking, and it successfully passed for this PR https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/75659/pull-kubernetes-verify/126875

**Comment by cblecker** [comment]
We strip comments in the staging godeps files when we generate them, so they won't have this line.

I don't understand why upstream is retagging the same commit with new version numbers..
@casualjim: is there a reason behind doing this?

That said, this is safe.

/lgtm
/approve

**Comment by liggitt** [comment]
> We strip comments in the staging godeps files when we generate them, so they won't have this line.

ah.

> I don't understand why upstream is retagging the same commit with new version numbers..
> @casualjim: is there a reason behind doing this?

it's a collection of associated repositories, and they tag them all at each release of the overall project (similar to the published kubernetes staging repos)

**Comment by cblecker** [comment]
> it's a collection of associated repositories, and they tag them all at each release of the overall project (similar to the published kubernetes staging repos)

Ohhhh. Okay that makes sense (although painful in this case).

**Pull request merged**
