### PR TITLE
Add 5-minute sleep in GKE for dead tunnels to be removed

### LINKED ISSUE #19491: e2e tests failing on GKE due to "use of closed network connection"
There are 2 `EmptyDir` tests and a `Secrets` test failing on GKE right now:

**EmptyDir volumes should support (root,0666,tmpfs) [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir.go:69 "perms of file \"/test-volume/test-file\": -rw-rw-rw-" in container output Expected : to contain substring : perms of file "/test-volume/test-file": -rw-rw-rw-

**EmptyDir volumes should support (root,0644,tmpfs) [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir.go:65 "perms of file \"/test-volume/test-file\": -rw-r--r--" in container output Expected : to contain substring : perms of file "/test-volume/test-file": -rw-r--r--

**Secrets should be consumable from pods [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/secrets.go:99 "content of file \"/etc/secret-volume/data-1\": value-1" in container output Expected : to contain substring : content of file "/etc/secret-volume/data-1": value-1

### PR DESCRIPTION
**Pull request by ikehz**
Fixes #19491.

### CODE REVIEW

**Comment by cjcullen** [comment]
I hate that this is our best option, but LGTM.

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please

**Comment by saad-ali** [comment]
Manually merging to fix broken `kubernetes-e2e-gke-ci` suite. Not waiting for unit/integration test run to finish since this change doesn't affect unit tests and GCE e2e is green.

**Comment by lavalamp** [comment]
This extra sleep time is making tests time out.

...also, isn't this papering over a legitimate system bug? Will anyone object strongly if I revert this?

**Comment by lavalamp** [comment]
Hm, I guess reverting this will start some other tests flaking again.

**Comment by cjcullen** [comment]
The legitimate system bug will get some help from #19314, but GKE doesn't have a good way (that I could think of) to guarantee tunnel health without being very heavy-handed (tunneling on-demand or health-checking on every proxy access). I think it comes down to how much we value tunnel reliability in the resize/reboot case vs. tunnel-overhead/latency in the steady-state case. Or maybe we can find a better way to proxy without ssh-tunnels...

**Comment by ihmccreery** [comment]
I think this is making explicit a known behavior that we've decided is okay, not papering over a bug (per @cjcullen's comment).  If we want to drive on making it better, we can, but that should come before we start letting tests fail.

**Pull request merged**
