### PR TITLE
Make order of fun consistent

### PR DESCRIPTION
**Pull request by zhengguoyong**
Fix: #16439
@liggitt,  please review, thanks.

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM consistency is good here.

**Comment by liggitt** [comment]
+1, I want to check out the branch and sweep referrers for my own satisfaction :)

**Comment by liggitt** [comment]
All the touched functions look good, can you also fix these:

ValidateIngressUpdate
ValidateThirdPartyResourceUpdate
ValidateThirdPartyResourceDataUpdate

**Comment by zhengguoyong** [comment]
done,  please review again , thanks  
@liggitt

**Comment by liggitt** [comment]
LGTM, thanks

**Pull request merged**
