### PR TITLE
Be more lenient when deriving the node tag from a node name on GCE

### PR DESCRIPTION
**Pull request by a-robinson**
Helps with one of the issues in #13073.

@cjcullen

### CODE REVIEW

**Comment by cjcullen** [comment]
LGTM

**Comment by roberthbailey** [comment]
Does this need to be patched into the release branch?

**Comment by a-robinson** [comment]
It's not strictly needed for anything, but it'd be good to pull in, along with #12438. I'll open the cherry-pick PR.

**Comment by roberthbailey** [comment]
Thanks.

**Pull request merged**
