### PR TITLE
Fix user fuzzer to avoid round trip flake

### LINKED ISSUE #42651: k8s.io/kubernetes/pkg/api TestRoundTripTypes
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42346/pull-kubernetes-unit/21773/

@deads2k

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #42651

### CODE REVIEW

**Comment by smarterclayton** [comment]
Wow the probability of this has to be shockingly low.

/approve

**Comment by liggitt** [comment]
> the probability of this has to be shockingly low

yeah, @kargakis wins

**Comment by kargakis** [comment]
\o/

**Pull request merged**
