### PR TITLE
fix staticcheck errors in pkg/volume/hostpath.

### PR DESCRIPTION
**Pull request by 928234269**
Signed-off-by: Sakura <longfei.shang@daocloud.io>
clean remaining static check errors in pkg/volume/hostpath.

**What type of PR is this?**
> /kind bug
> /kind cleanup

**What this PR does / why we need it**:
cleanup staticcheck errors, it says as below:

**Which issue(s) this PR fixes**:
Ref:#81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by php-coder — APPROVED** [review]
Thanks!

/lgtm
/kind cleanup

**Comment by 928234269** [comment]
@php-coder I just wanted to hire someone for approval, and you've done it, it's amazing speed.

**Comment by 928234269** [comment]
@liggitt I added new changes and fixed unused fields, please approve them.

**Comment by php-coder** [comment]
> @liggitt I added new changes and fixed unused fields, please approve them.

@928234269 approved label doesn't get removed with new changes, so technically your PR is already approved. JFYI.

**Comment by 928234269** [comment]
> > @liggitt I added new changes and fixed unused fields, please approve them.
> 
> @928234269 approved label doesn't get removed with new changes, so technically your PR is already approved. JFYI.



> > @liggitt I added new changes and fixed unused fields, please approve them.
> 
> @928234269 approved label doesn't get removed with new changes, so technically your PR is already approved. JFYI.

thanks!

**Pull request merged**
