### PR TITLE
Etcd listens on localhost for GCE

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#5962

Will roll out the change to other cloud providers after GCE.
#5011

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
Running e2e tests.

**Comment by zmerlynn** [comment]
LGTM. Thanks!

**Comment by zmerlynn** [comment]
Ha, sorry. Just saw the "Running e2e."

... hopefully that works. :)

**Comment by ArtfulCoder** [comment]
yes :)
will track the e2e jenkins run as well.

**Comment by ArtfulCoder** [comment]
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/4142/consoleFull


All tests, except 1 passed.
Will look at the failing test but I doubt it is related to my change.

Summarizing 1 Failure:

[Fail] ReplicationController [It] should serve a basic image on each replica with a private image 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:151

Ran 31 of 35 Specs in 1107.520 seconds
FAIL! -- 30 Passed | 1 Failed | 0 Pending | 4 Skipped F0403 12:55:29.517718   24805 driver.go:112] At least one test failed
2015/04/03 12:55:29 Error running Ginkgo tests: exit status 255

**Comment by ArtfulCoder** [comment]
Per Quinton's test summary email today, it is a flaky test with a 70% stability.

This PR should be good.

**Comment by ArtfulCoder** [comment]
@dchen1107

**Comment by ArtfulCoder** [comment]
@brendanburns @zmerlynn Can I make changes for  "etcd on localhost" on all providers ?
Or do you forsee any issues ?

GCE seems to be doing well, e2e and manual tests passed.

**Comment by zmerlynn** [comment]
I'm actually fine with that. I nearly changed it once before, but the change it was in was wide enough already.

**Comment by ArtfulCoder** [comment]
Created PR #6422

**Pull request merged**
