### PR TITLE
Remove pkg/client/unversioned

### LINKED ISSUE #25442: Deprecate pkg/client/unversioned/
Components should be using the generated clientset instead.

Unfortunately, it cannot be removed yet, at least kubectl still relies on it. We should stop people using/updating the package. Maybe adding a deprecation warning message in each file?

@krousey @lavalamp @nikhiljindal @janetkuo @kubernetes/sig-api-machinery

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
This is removing unused package, and moves the used bits into appropriate placeholders. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #25442

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

/assign @deads2k 
/assign @sttts

### CODE REVIEW

**Review by adohe-zz — APPROVED** [review]

**Comment by soltysh** [comment]
I fixed the missing bits, should be good now.

**Comment by deads2k** [comment]
needs rebase

**Comment by soltysh** [comment]
@deads2k ptal, it's all green
@smarterclayton for approval

**Pull request merged**
