### PR TITLE
Spelling fixes inspired by github.com/client9/misspell

### PR DESCRIPTION
**Pull request by laushinka**

### CODE REVIEW

**Comment by bgrant0607** [comment]
ok to test

**Comment by eparis** [comment]
This PR needs rebased.
You also need to run `hack/update-generated-docs.sh` to fix up the docs based on some of the spelling fixes...

**Comment by laushinka** [comment]
@eparis: Thanks! I rebased and regenerated the docs. I also fixed one more spelling mistake in one of the source files that would have propagated back into the docs again.

**Comment by laushinka** [comment]
Hmm, the Jenkins unit/integration failed with this apparently:

```
+ ./hack/install-etcd.sh
curl: (18) transfer closed with 5946210 bytes remaining to read
```

Not sure if this is related to my changes?

**Comment by laushinka** [comment]
Fixed more spelling mistakes that were the source of some autogenerated swagger docs and caused some of the tests to fail.

**Comment by laushinka** [comment]
@eparis: Sorry, I had to rebase again on top of latest changes - needs another LGTM.

**Comment by laushinka** [comment]
@eparis: how long after LGTM and all tests pass should the PR be merged? Should it happen automatically? Just trying to avoid more and more conflicts because this PR touches so many files (sorry!)

**Comment by eparis** [comment]
@laushinka http://submit-queue.k8s.io show the queue of PRs.

@bgrant0607 it is LGTM to me, any problem if I bump it to the front of the queue to get off the rebase wagon, or would you rather we just go post 1.2 and then bump to the head of the line.

**Comment by eparis** [comment]
(or maybe i'll just e2e-not-required, that's probably the right thing to do)

**Comment by bgrant0607** [comment]
Thanks!

**Comment by bgrant0607** [comment]
@johndmulhausen This PR fixed a lot of spelling issues in docs in master.

**Pull request merged**
