### PR TITLE
Add SOCKS5 proxy support for kubectl exec [based on #84205]

### LINKED ISSUE #104005: `kubectl exec` was failed when use socks5 proxy
#### What happened:
```
❯ k exec --tty sleep-64d7d56698-bct4r -n sample -c sleep -- sh
error: error sending request: Post "https://9881A2BCF1B7A06ABFBDAA4EC92FFAC3.sk1.ap-east-1.eks.amazonaws.com/api/v1/namespaces/sample/pods/sleep-64d7d56698-bct4r/exec?command=sh&container=sleep&stderr=true&stdout=true": EOF
```

#### What you expected to happen:
Not fail.

#### How to reproduce it (as minimally and precisely as possible):
To create a socks5 proxy though ssh tunnel or another way.
And add config in ~/.kube/config, for example;
```
clusters:
- cluster:
   certificate-authority-data: *****
   proxy-url: socks5://127.0.0.1:9999
   server: ****
```
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Patrick0308**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
To support executing `kubectl exec` command via a SOCKS5 proxy. This pr base on #84205.

#### Which issue(s) this PR fixes:

Fixes #104005

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Patrick0308** [comment]
@caesarxuchao Plz see it. Some work dependent on this.

**Comment by shuker85** [comment]
Any progress on this one?

**Comment by caesarxuchao** [comment]
Sorry for dropping the ball. #105632 is a more recent attempt to revive #84205, let's move the discussion to that PR.

**Comment by enj** [comment]
Closing per https://github.com/kubernetes/kubernetes/pull/104056#issuecomment-946215356

/close

**Pull request closed without merging**
