### PR TITLE
staging/copy.sh: don't strip tags anymore with k8s.io/api

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
@caesarxuchao can you take a quick look? This stop us from generating deepcopy code in staging/src/k8s.io/client-go/tools/clientcmd/config.go.

**Comment by caesarxuchao** [comment]
@lavalamp @smarterclayton for approval.

**Comment by sttts** [comment]
/assign @lavalamp 

This needs approval.

**Comment by sttts** [comment]
copy.sh does not exist anymore. Closing.

**Pull request closed without merging**
