### PR TITLE
Embed cadvisor http handlers in kubelet if cadvisor port is disabled

### PR DESCRIPTION
**Pull request by jimmidyson**
This PR would enables serving the cadvisor API & web pages under the `/cadvisor` path in the kubelet if `cadvisor-port` is set to 0. This would enable direct connection to raw cadvisor stats without running cadvisor http on a separate port, a potential for unsecured info leakage. Right now, disabling cadvisor port means no access to raw cadvisor info, which can be very useful. Also moves us a bit closer to being able to disable the read-only port (see #12968), although that still requires work to fix authorization properly.

The cadvisor bump is to pull in https://github.com/google/cadvisor/commit/a059975c63f6901e545275f3dead58feea2661ac to fix cadvisor static content being served under a subdirectory.

/cc @vishh

### CODE REVIEW

**Comment by vishh** [comment]
#12483 is expected to replace the existing kubelet stats APIs. cAdvisor APIs work on cgroups and containers. That is not what the rest of kubernetes exposes. 
I see the need for this PR as of now. Can we rename the API to be `/deprecated/cadvisor`, which will convey our intent to remove this endpoint as soon as an alternative API is available?

**Comment by vishh** [comment]
Overall code LGTM.

**Comment by jimmidyson** [comment]
A kubelet isn't necessarily run in the context of a kubernetes cluster (standalone kubelets are pretty useful things in their own right) so I think this endpoint is valid going forward.

**Comment by vishh** [comment]
A kubelet even in a standalone mode exposes pods and nodes, not really
cgroups and containers. What if the kubelet is run with a VM ([hyper](
https://hyper.sh/)) based runtime for example? We can get metrics similar
to what cadvisor exports, but the current cadvisor abstractions based on
cgroups doesn't work in such cases.

**Comment by jimmidyson** [comment]
Fair point. I still don't like the `/deprecated` in the path. Not sure it really adds anything - we can just agree it's deprecated & remove once a better stats api is available.

**Comment by jimmidyson** [comment]
@vishh Any more discussion on this? Would like to get this in.

**Comment by jimmidyson** [comment]
Rebased.

@vishh any comments?

**Comment by vishh** [comment]
@jimmidyson: Sorry for the delay. When we add any APIs, users might end up building on top of it. The reason for adding a prefix like `experimental` is to explicitly convey our intent for replacing this API soon.

**Comment by jimmidyson** [comment]
@vishh Disagree, but think this is worth getting in so changed to `/deprecated/cadvisor` path.

**Comment by vishh** [comment]
I'm fine with `experimental` too. I can send a PR once this gets merged to switch over to `experimental`. 

I discussed this with @dchen1107 and she was also weary of exposing the API directly.

**Comment by jimmidyson** [comment]
@vishh Rebased & switched cadvisor to `/experimental/' as you suggested.

**Comment by jimmidyson** [comment]
@vishh Any chance of another quick review? e2e failure is a flake... again.

**Comment by jimmidyson** [comment]
Closing this PR. Will reopen one with just a cadvisor bump without exposing the cadvisor endpoint.

**Pull request closed without merging**
