### PR TITLE
kubelet: clean inefficient var statements

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Removed 2 not needed variable declarations.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bart0sh** [comment]
/cc @RenaudWasTaken @vishh @vikaschoudhary16 

Rebased on top of master, please review

**Review by RenaudWasTaken — APPROVED** [review]
/lgtm

**Comment by bart0sh** [comment]
Kindly ping reviewers and approvers to look at this. It's tiny simple PR. Why is it sitting under review for 4 months? If you don't need please close with the explanation. That would be better than ignoring it.

**Pull request closed without merging**
