### PR TITLE
Graduating EndpointSlice API and Controllers to GA

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind feature
/kind api-change

**What this PR does / why we need it**:
This graduates the EndpointSlice API and feature gate (controllers) to GA. It adds a new beta EndpointSliceTopology feature gate to keep the `topology` field at beta.

**Does this PR introduce a user-facing change?**:
```release-note
EndpointSlice API and controllers are now GA. The EndpointSlice topology field is now guarded by a beta EndpointSliceTopology feature gate that is enabled by default. The discovery.k8s.io/v1alpha1 API is deprecated.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/752

/cc @bowei @freehan
/assign @thockin
/sig network
/priority important-soon

### CODE REVIEW

**Comment by robscott** [comment]
This PR definitely still needs work, but I think I'm getting relatively close. I wanted to make sure this PR got in this week so there was at least some time to review it before code freeze. Here are some questions I've had along the way:

- Should EndpointSliceMirroring controller GA be separate? Do we need a separate feature gate for it? Maybe it stays beta and eventually is turned off by default?
- Should we continue to support deprecated IP address type in EndpointSlice validation?
- What kind of conformance tests do we need?
- Should I get rid of v1alpha1 everywhere?
- Should I leave controllers and other consumers of the EndpointSlice API consuming the v1beta1 API in case of version skew?

**Comment by robscott** [comment]
I talked with @thockin about my questions above, here's a quick summary:

- _Should EndpointSliceMirroring controller GA be separate? Do we need a separate feature gate for it? Maybe it stays beta and eventually is turned off by default?_
No need. Endpoints aren't going away, we'll need it long term.

- _Should we continue to support deprecated IP address type in EndpointSlice validation?_
No, it's been deprecated since the API went beta in 1.17. I'll add a test to ensure the controller properly converts an IP EndpointSlice to IPv4 and/or IPv6 EndpointSlices.

- _What kind of conformance tests do we need?_
Start with existing e2e tests. I'll follow up with @johnbelamaric to see if we need more. 

- _Should I get rid of v1alpha1 everywhere?_
No, but add a deprecation notice to the release notes for this change.

- _Should I leave controllers and other consumers of the EndpointSlice API consuming the v1beta1 API in case of version skew?_
Shouldn't be any need to do this since control plane components talk to API in localhost and nodes have to trail control plan version, but I should verify with @liggitt to be sure.

**Comment by neolit123** [comment]
to @robscott 's question here:
https://github.com/kubernetes/kubeadm/issues/2271#issuecomment-724201477

> @neolit123 This issue came up as I'm working on graduating the EndpointSlice API to GA (kubernetes/kubernetes#96318). I'm trying to determine if it's safe to also upgrade consumers like kube-proxy or kube-controller-manager to also use the v1 API in the same release. If I'm understanding this issue correctly, making that change in upstream could potentially result in issues here when version skew exists. Do you think this will be resolved in time for the 1.20 release cycle?

first of all, thanks for bringing that up at the kubeadm issue tracker.
i  guess this is primarily related to this Q/A:

>> Should I leave controllers and other consumers of the EndpointSlice API consuming the v1beta1 API in case of version skew?

> Shouldn't be any need to do this since control plane components talk to API in localhost and nodes have to trail control plan version,

kubeadm runs the kube-controller-manager, kube-scheduler and kube-apiserver on the same host for control-plane nodes. in 1.19 kubeadm started linking its kube-controller-manager and kube-scheduler to the local API server. prior to that, these components talked to an LB endpoint where they could reach N and N-1 kube-apiservers. this created upgrade issues when APIs get removed for particular leader election scenarios.

given the components in question have been talking to localhost since 1.19, i do not see a problem here.
but if the kubelet is also relevant to this topic, then we have a problem because the kubeadm control-plane kubelets still talk to the LBs. this required some re-design and is not doable for 1.20.

please let me know if this answers your questions.

**Comment by robscott** [comment]
Thanks for the quick response @neolit123! It sounds like this will likely not be an issue. The key components involved will either talk to apiserver on localhost (controllers) or be on nodes that will not exceed the version of any control plane (kube-proxy). With that said, how does kubeadm deploy kube-proxy? Is it a daemonset where the version is tied to controlplane version or something that is tied to node version?

**Comment by neolit123** [comment]
in kubeadm, kube-proxy is deployed as a deamon-set with the spec from [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L54)
the version of kube-proxy that kubeadm deploys is the same as the version of the kube-apiserver, kube-scheduler and kube-controller-manager and is treated as the "kubernetes version".

one caveat is that today's kubeadm upgrade process does not comply with the version skew of kube-proxy:
https://kubernetes.io/docs/setup/release/version-skew-policy/#kube-proxy
(i don't think this section of the doc existed when kubeadm's mutable upgrade code was written).
kube-proxy is upgraded after one control-plane node is upgraded, but before all the control-plane components in an HA setup have been upgraded, so there is a period of time when the kube-proxy version n the DS is ahead of some components.

but this should be temporary. unless the user explicitly sets kube-proxy to a custom version it should not be ahead of the control-plane version, in general.

**Comment by robscott** [comment]
>kube-proxy is upgraded after one control-plane node is upgraded, but before all the control-plane components in an HA setup have been upgraded, so there is a period of time when the kube-proxy version n the DS is ahead of some components.

That's good to know - thanks! That is a significant point and will likely cause issues with kube-proxy updates in the future. For now I'll leave kube-proxy consuming the v1beta1 API for one more release to avoid this potential problem.

**Comment by neolit123** [comment]
> That's good to know - thanks! That is a significant point and will likely cause issues with kube-proxy updates in the future. For now I'll leave kube-proxy consuming the v1beta1 API for one more release to avoid this potential problem.

that seems like the safer bet, indeed. thank you!
FWIW, kubeadm has done this type of wrong upgrade sequence for around ~12 versions (or since `kubeadm upgrade` existed), since i think the kube-proxy skew policy was defined only recently in https://github.com/kubernetes/website/issues/12322

**Comment by liggitt** [comment]
> i think the kube-proxy skew policy was defined only recently in [kubernetes/website#12322](https://github.com/kubernetes/website/issues/12322)

That was added in https://github.com/kubernetes/website/pull/11060, which formalized the policies already in place in places like https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

kube-proxy was traditionally deployed as a static pod matching the node version, and fell under the "Nodes may lag masters components by up to two minor versions but should be at a version no newer than the master" portion of that original policy.

If we want to expand that support statement, I would expect tests demonstrating kube-proxy 1.n works against a 1.n-1 API server.

**Comment by neolit123** [comment]
> That was added in kubernetes/website#11060, which formalized the policies already in place in places like https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

i did not know about this, thanks for the link.

here is a new issue to track kubeadm's mutable upgrade problem of kube-proxy.
https://github.com/kubernetes/kubeadm/issues/2346

one potential problem with the existing policy is around:
> kube-proxy must be the same minor version as kubelet on the node.

i'm not sure how one can synchronize the version upgrade of the kubelet binary and the kube-proxy image in the DS podspec, to not have a minor drift for a period of time. given both a kubelet and kube-proxy runs on all nodes, they are likely to upgrade either the kubelets or those nodes or kube-proxy first.

**Comment by robscott** [comment]
Follow up on my questions from above:

- _What kind of conformance tests do we need?_
Confirmed with @johnbelamaric that existing tests would be a good starting point as part of this PR. Have upgraded the existing EndpointSlice e2e tests to conformance. 

- _Should I get rid of v1alpha1 everywhere?_
Deprecation notice has been added to release note above as requested.

- _Should I leave controllers and other consumers of the EndpointSlice API consuming the v1beta1 API in case of version skew?_
I've verified with @liggitt that this is generally safe, but he rightly pointed out that the kubeadm upgrade flow could run into issues here. After discussion above with @neolit123, I've left kube-proxy using v1beta1 API. All control plane components have been upgraded to use v1 API. 

I think I've addressed everything at this point, may need to do a bit more work to get tests passing but this is ready for a full review whenever anyone has time.

**Comment by robscott** [comment]
The failing GA only conformance tests caught an important detail. Since I've hidden topology fields behind the beta `EndpointSliceTopology` feature gate, the controllers can't set them in a GA only environment. Importantly topology is the only place we store the all important node name on EndpointSlices. That is not an issue _yet_, but it will become an issue when we want `EndpointSliceProxying` to go GA. Kube-Proxy relies on this information to determine if an endpoint is local to a node. We'll need a better solution for node name before that point or to simply graduate `EndpointSliceTopology` to GA at the same time.

**Comment by aojea** [comment]
> * _Should I leave controllers and other consumers of the EndpointSlice API consuming the v1beta1 API in case of version skew?_
>   I've verified with @liggitt that this is generally safe, but he rightly pointed out that the kubeadm upgrade flow could run into issues here. After discussion above with @neolit123, I've left kube-proxy using v1beta1 API. All control plane components have been upgraded to use v1 API.

If we can leave with kube-proxy in beta one release I recommend it too, unfortunately seems that (some) users upgrade kube-proxy before control-plane nodes, with the "first" dual stack, kube-proxy "paniced" due to this, and as consequence,  users open issues in Github, we point them to the skew policy, a new user find the same issue or file a duplicate one, we close it, the blaming/criticism starts, ... :shrug: 
I think that was Jordan who mentioned this before somewhere :smile:   https://imgs.xkcd.com/comics/workflow.png

**Comment by aojea** [comment]
dual stack is one of the main consumers of slices, since is the only way they can have dual-stack endpoints
@johnbelamaric another important client of slices is CoreDNS, @chrisohaver just implemented them recently, we'll need that feedback too

/test pull-kubernetes-e2e-iptables-azure-dualstack
/test pull-kubernetes-e2e-azure-dualstack
/test pull-kubernetes-e2e-kind-dual-canary
/test pull-kubernetes-e2e-kind-ipvs-dual-canary

**Comment by aojea** [comment]
> Since I've hidden topology fields behind the beta `EndpointSliceTopology` feature gate

@robscott just curious, why do have to keep the topology field in beta? is that it may change in the future?
I think that if the we know that field is not going to change we can graduate it to GA, no?

**Comment by aramase** [comment]
@aojea We updated the name for the presubmit ipvs job in https://github.com/kubernetes/test-infra/pull/19720

/test pull-kubernetes-e2e-ipvs-azure-dualstack

**Comment by robscott** [comment]
Unfortunately that `topology` field has ended up being a compelling enough roadblock to push the v1 graduation back to 1.21. I'm going to close this PR and work on a much smaller update for 1.20. 

The core issue is that `topology` has very little purpose now and leaving it in as the API graduates would mean we'd be stuck with it forever. The latest plans for topology aware routing rely on grouping endpoints for each zone into EndpointSlices, not per-endpoint topology information. If we need to communicate the zone or region of endpoints, a much more efficient approach would be to group slices with endpoints from the same zone/region and use top level topology labels. Leaving that field in the API adds a lot of weight to EndpointSlice objects for data that can be expressed in cleared and more efficient ways.

With that said, topology does currently include the important concept of a node name. I think it makes the most sense to pull that out and move it to it's own `nodeName` field (similar to the Endpoints API). 

I think the most sensible changes for 1.20 are:
- Add a deprecation notice on the topology field
- Introduce a new alpha `nodeName` field for each EndpointSlice endpoint
- Formally remove the IP address type (was supposed to be done in 1.18)

Then early in the 1.21 cycle we can reuse the majority of this PR to graduate the API to GA.

I've discussed all of the above with @liggitt and @thockin just to ensure this updated approach actually makes sense. I was really hoping to find a way to do this all safely in 1.20, but that does not seem to exist. Leaving GA for 1.21 seems to be our safest approach at this point.

Definitely don't hesitate to let me know if this approach doesn't make sense or if there are any other areas we should be revisiting before we reach GA.

/close

**Pull request closed without merging**
