### PR TITLE
adding configs path to kubelet

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**:
Refer to https://github.com/kubernetes/kubernetes/pull/33630. Here we create an new endpoint for the path `/configs` to kubelet.

**Special notes for your reviewer**:
We may need someone from sig-auth to ensure parity with security considerations given to `/metrics` endpoint.

**Release note**:

``` 
None
```

### CODE REVIEW

**Comment by alejandroEsc** [comment]
@lavalamp please have a look, it is related to the proposal and your comment.

**Comment by lavalamp** [comment]
I would prefer to get more buy-in on your proposal before making code changes. @dchen1107 is the person you'll need to sign off on this.

**Comment by jbeda** [comment]
From #33630 it looks like putting this endpoing on the kubelet is not super controversial.  @dchen1107 -- would love to get your thoughts.

**Comment by countspongebob** [comment]
@lavalamp... we've had quite a bit of conversation about this in the home SIG for this PR, which is Sig Scale, including input from @jbeda , @wojtek-t , @timstclair , and others. We've worked pretty hard to get consensus on the approach. We'll certainly work with Dawn on it, as you suggest, as well. Would be very happy to have you and/or @dchen1107  attend the Sig Scale meeting for an extended review if you think that is needed. Failing that, maybe a f2f discussion at kubecon?

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
Can someone elaborate a little bit more on the use case with the feature?

I personal love this change, and can think of many use cases utilizing this feature. Instead of dumping the entire componentconfig, if we support query string of a given config, that would be even better to me. For example, to rolling out a new feature guarded by a config without binary update to a large cluster, the admin can easily retrieve that config's value for monitoring.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@k8s-bot verify test this

**Comment by spiffxp** [comment]
@dchen1107 we're hitting what appears to be an unrelated node-e2e flake, I don't know if there's an issue for this, but noticing it hit #35481 today as well

**Comment by alejandroEsc** [comment]
@k8s-bot gci gke e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot cvm gke e2e test this

**Comment by alejandroEsc** [comment]
@dchen1107 

Im in the process of updating  [33630](https://github.com/kubernetes/kubernetes/pull/33630) , but the general idea is we would like to get access to configs at the component level, and add to componentconfigs any further configurations including flags that relate to that component. Componentconfigs are a good place to have these since they will not contain secrets. Additionally, and why kubelet is a good start, is that we are using the same mechanism as /metrics endpoint since security concerns are addressed there. 

As for your querying specific configurations, that sounds like a great idea! I would suggest this for a future change that I will personally be responsible for and add it into future section of the proposal.

Finally, seems like i fixed the test but the tests:  `gci gke e2e test` and `cvm gke e2e test` seemed to be flaking out a bit? tried retesting, if it doesnt do so could you initiate it? Thank you!

**Comment by alejandroEsc** [comment]
@dchen1107 all green, waiting on an LGTM.

**Comment by alejandroEsc** [comment]
@k8s-bot unit test this

**Comment by alejandroEsc** [comment]
@k8s-bot node e2e test this

**Comment by dims** [comment]
@k8s-bot test this

**Comment by dims** [comment]
@dchen1107 : this does not seem to be a priority (cc @alejandroEsc), moving it to 1.6. please reverse if you disagree

**Comment by alejandroEsc** [comment]
@dchen1107 @dims  I have rebased 4 times now and each time a different unrelated test fails. Suggestions for next steps?

**Comment by alejandroEsc** [comment]
@k8s-bot gci gke e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot gci gce e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot cri e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot cri e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot gci gke e2e test this

**Comment by alejandroEsc** [comment]
@k8s-bot gci gke e2e test this

**Comment by fejta** [comment]
ref https://github.com/kubernetes/test-infra/issues/1561
@k8s-bot cri node e2e test this
@k8s-bot node e2e test this

**Comment by alejandroEsc** [comment]
@dchen1107 could we get another look?

**Comment by alejandroEsc** [comment]
Closing PR. Determined new approach to take, I will be referencing to this later.

**Pull request closed without merging**
