### PR TITLE
Correct the checking of robinIndex

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR addresses the comment:
https://github.com/kubernetes/kubernetes/pull/85192#discussion_r346113455

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM

**Comment by MikeSpreitzer** [comment]
This fixes a typo that came in with fresh code in #85192

**Comment by lavalamp** [comment]
/lgtm
/approve

This should have created a bias for some queue. I think tests need to be improved.

**Pull request merged**
