### PR TITLE
Fix an else branch in configure-helper.sh

### LINKED ISSUE #37257: cluster/gce/upgrade.sh taking a long time to run
This is for manual upgrade testing:

I am running the upgrade.sh script on the release-1.5 branch and the script has been running for a long time now (>40mins) with no sign of completion. 
Has anyone experienced a similar issue or has been successfully able to run the upgrade script ?

Command I ran: cluster/gce/upgrade.sh -M v1.5.0-beta.1

`Output`

rkouj@rkouj0:~/go/src/k8s.io/kubernetes$ cluster/gce/upgrade.sh -M v1.5.0-beta.1
== Pre-Upgrade Node OS and Kubelet Versions ==
name: "kubernetes-master", osImage: "Google Container-VM Image", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd-dirty"
name: "kubernetes-minion-group-7593", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd-dirty"
name: "kubernetes-minion-group-bigx", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd-dirty"
name: "kubernetes-minion-group-q5uf", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd-dirty"
Your active configuration is: [default]

Project: rkouj-test1
Zone: us-central1-b
INSTANCE_GROUPS=kubernetes-minion-group
NODE_NAMES=kubernetes-minion-group-7593 kubernetes-minion-group-bigx kubernetes-minion-group-q5uf
== Upgrading master to 'https://storage.googleapis.com/kubernetes-release/release/v1.5.0-beta.1/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==
Trying to find master named 'kubernetes-master'
Looking for address 'kubernetes-master-ip'
Using master: kubernetes-master (external IP: 104.197.149.96)
Deleted [https://www.googleapis.com/compute/v1/projects/rkouj-test1/zones/us-central1-b/instances/kubernetes-master].
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/rkouj-test1/zones/us-central1-b/instances/kubernetes-master].
NAME               ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
kubernetes-master  us-central1-b  n1-standard-1               10.128.0.2   104.197.149.96  RUNNING
== Waiting for new master to respond to API requests ==
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

### PR DESCRIPTION
**Pull request by roberthbailey**
**What this PR does / why we need it**: bug fix for upgrade.sh needed in 1.5

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #37257

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37358)

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

Thanks for the fix!

**Comment by jszczepkowski** [comment]
@k8s-bot gce etcd3 e2e test this
issue #37213

**Comment by jszczepkowski** [comment]
@k8s-bot gci gce e2e test this
issue #37361

**Comment by dims** [comment]
LGTM 👍

**Comment by jszczepkowski** [comment]
@k8s-bot gce etcd3 e2e test this
jenkins problem: build still running

**Pull request merged**
