### PR TITLE
fix endpointslice recreate after garbage controller deleted.

### PR DESCRIPTION
**Pull request by llhhbc**
Signed-off-by: Longhui.li <lilonghui123456@163.com>

**What type of PR is this?**

/kind bug

Optionally add one or more of the following kinds if applicable:
/kind controller-manager/endpointslice-controller

**What this PR does / why we need it**:
Fix endpointslice recreate after garbage controller delete it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
Hey @llhhbc, thanks for the PR! I think we've actually already fixed this bug with https://github.com/kubernetes/kubernetes/pull/91311, but I should work on cherry-picking that back into 1.18, thanks for the reminder. I'm going to go ahead and close this but feel free to reopen if I misunderstood the purpose of this PR.

/close

**Comment by llhhbc** [comment]
> Hey @llhhbc, thanks for the PR! I think we've actually already fixed this bug with #91311, but I should work on cherry-picking that back into 1.18, thanks for the reminder. I'm going to go ahead and close this but feel free to reopen if I misunderstood the purpose of this PR.
> 
> /close

Thanks. We are use 1.18, thanks for cherry-picking that back into 1.18.

**Comment by llhhbc** [comment]
@robscott Can you cherry-picking  #91311 to  k8s 1.18?

**Comment by robscott** [comment]
Hey @llhhbc, thanks for following up with this! That fix was cherry picked to 1.18 with https://github.com/kubernetes/kubernetes/pull/94253. That was released with 1.18.9: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#bug-or-regression-5.

**Comment by llhhbc** [comment]
> Hey @llhhbc, thanks for following up with this! That fix was cherry picked to 1.18 with #94253. That was released with 1.18.9: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#bug-or-regression-5.

Thanks.

**Pull request closed without merging**
