### PR TITLE
[federation][e2e] Distinguish local vars and global vars

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot ok to test

**Comment by shashidharatd** [comment]
@FengyunPan, can you please check the failing test case in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45062/pull-kubernetes-federation-e2e-gce/2486/

**Comment by shashidharatd** [comment]
@k8s-bot unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
@shashidharatd I will check it.
The same as:https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44483/pull-kubernetes-federation-e2e-gce/2410/

**Comment by shashidharatd** [comment]
@k8s-bot unit test this

**Comment by FengyunPan** [comment]
@shashidharatd  Hi, can I ask a question? Is cluster.clientSet equivalent to cluster.Extensions()? The cluster is a cluster of fedframework.ClusterSlice.

**Comment by shashidharatd** [comment]
@k8s-bot unit test this

**Comment by shashidharatd** [comment]
The ingress tests are failing due to bug in ingress, This PR will fix it #45079
The current PR has no link to ingress tests. we can wait until #45079 is passed as i find this PR is not so critical and just so that all tests pass before accepting merge. Anyway i have already done LGTM.
Thanks @FengyunPan !

**Comment by FengyunPan** [comment]
I have fixed it:  #44810 
http://prow.k8s.io/?type=presubmit&pull=44810&job=pull-kubernetes-federation-e2e-gce

**Comment by shashidharatd** [comment]
@FengyunPan, I am little unfamiliar with ingress tests. @madhusudancs can you confirm please if the PR #44810 fixes the ingress test failures. Thanks

**Comment by shashidharatd** [comment]
@k8s-bot unit test this

**Comment by FengyunPan** [comment]
@k8s-bot kubemark e2e test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
Federation presubmit passed - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45062/pull-kubernetes-federation-e2e-gce/3043/

**Comment by FengyunPan** [comment]
@k8s-bot kops aws e2e test this

**Comment by FengyunPan** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
