### PR TITLE
Bump up etcd dependency to fix data race

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: https://github.com/kubernetes/kubernetes/pull/23694

What this PR does
- Bumping up the godep of etcd to fix data race in etcd watcher. Without this change, watcher PR builds will fail in race detection.
- Small changes to fix builds after upgrade

### CODE REVIEW

**Comment by hongchaodeng** [comment]
/cc @wojtek-t @timothysc @xiang90 

This is prereq to the watcher implementation. 
It also provides the API of event types as requested by Tim.

**Comment by timothysc** [comment]
Looks like the tests are green, but just so I'm clear this change to the server looks to affect both clients, and is this an officially released version of etcd?  

We typically only bump the dep on sanctioned releases.

**Comment by xiang90** [comment]
> and is this an officially released version of etcd?

This is not. Hongchao is working on v3 so he was tracking the master.

**Comment by timothysc** [comment]
k, then we should either close this pull or mark as WIP to revisit at a later date.

**Comment by hongchaodeng** [comment]
The v2 client change just remove the outdated code because we are not using go1.4 anymore.

The changes include:
- https://github.com/coreos/etcd/commit/25e47db4163505461ee51242d31342dcfe063405
- https://github.com/coreos/etcd/commit/6e6d64fb9b3d57eeb105c71e16a28e1c3ac7d5ef
- Some docs update

**Comment by hongchaodeng** [comment]
@timothysc 
I think the changes are pretty minor, actually good for go1.6. Do you still have any concern I can help answer?

**Comment by timothysc** [comment]
@lavalamp @wojtek-t ping on policy here?  
Do we want to allow godep from non-released versions?

**Comment by lavalamp** [comment]
I don't care that much about the client as long as it works. This doesn't change the version of etcd that we run, which I do care about. However it also changes the version of etcd that we build for kube2sky (?maybe? @ArtfulCoder). However we're going to stop doing that in the near future anyway.

I guess my only concern would be if this causes our tests to test something that is not the same as what we run against in production.

**Comment by hongchaodeng** [comment]
I want to point out that we ensure it is as close to production env as possible by using real binaries in testing, i.e. e2e and integration testing.

etcd also runs a bunch of CI to ensure API behavior doesn't change, including regression, of both v2 and v3.

**Comment by hongchaodeng** [comment]
Something seems have changed in godep licenses. Updated

**Comment by hongchaodeng** [comment]
Can you help re-add 'lgtm' label?
@timothysc @mikedanese @yifan-gu

**Comment by hongchaodeng** [comment]
@k8s-bot unit test this please github issue: #24298

**Pull request merged**
