### PR TITLE
 kubectl helpers test: remove core dependencies

### PR DESCRIPTION
**Pull request by seans3**
* Removes dependency on core testapi.
* Removes dependency on core testing library.
* Replaces internal Pod and Service resource with external/corev1 resources.
* Various other small cleanups.

Helps address:
https://github.com/kubernetes/kubectl/issues/83

```release-note
NONE
```

### CODE REVIEW

**Review by apelisse — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
