### PR TITLE
Make kube-proxy's MetricsBindAddress configurable via flag

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**: From #48600, `MetricsBindAddress` used to be configurable through flag (coupled with `HealthzBindAddress`). But this functionality went away after #44968 separated healthz server from metrics server. This PR adds that functionality back.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:
/assign @ncdc 
cc @bowei @r0bj

**Release note**:

```release-note
The IP address and port for kube-proxy metrics server is now configurable via flag `--metrics-bind-address`
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Thanks!

/ssign @thockin 
for approval.

**Comment by MrHohn** [comment]
Sorry, updated bazel BUILD files.

**Comment by alexbrand** [comment]
It seems like the reference configuration is missing the `--metrics-bind-address` option.

https://kubernetes.io/docs/admin/kube-proxy/

**Comment by MrHohn** [comment]
@alexbrand Thanks for reporting. I opened https://github.com/kubernetes/kubernetes.github.io/issues/5618 for tracking.

**Comment by alexbrand** [comment]
Awesome! Thanks @MrHohn

**Pull request merged**
