### PR TITLE
Fixed resetting last scale time in HPA status.

### LINKED ISSUE #16275: Horizontal pod autoscaler is not stable
Horizontal pod autoscaler makes decision to scale down after 1 minute from the previous scale down, although downscaleForbiddenWindow is 5 minutes. This causes flakiness of hpa e2e tests with stability checks:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/1496/consoleFull

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed resetting last scale time in HPA status. Fixes #16275.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @piosz

**Comment by wojtek-t** [comment]
lgtm

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Pull request merged**
