### PR TITLE
Fix some typo

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Fix some typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
Is that ok?

**Comment by xichengliudui** [comment]
ci check this

**Comment by neolit123** [comment]
@xichengliudui 
needs ./hack/update-gofmt.sh

make sure you have golang-1.11 installed.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/69730/pull-kubernetes-verify/109537/#verify-gofmt

**Comment by xichengliudui** [comment]
@neolit123  Thanks!
I resubmitted these fix.

**Pull request merged**
