### PR TITLE
Automated cherry pick of #18256

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #18256 on release-1.1.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
I signed it!

**Comment by andyzheng0831** [comment]
@caesarxuchao
@dchen1107

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by andyzheng0831** [comment]
@k8s-bot test this

**Pull request merged**
