### PR TITLE
Fix description errro for client-certificate option

### PR DESCRIPTION
**Pull request by hurf**
From "client key file" to "client certificate file".

### CODE REVIEW

**Comment by hurf** [comment]
@janetkuo - Needs lgtm:-)

**Comment by hurf** [comment]
When translating the docs, found some small issues. Will continue summit small fixes in this branch.

**Comment by janetkuo** [comment]
LGTM. You may want to update the commit message (errro --> error).

**Comment by hurf** [comment]
Ah sorry, it's merged before I saw the comment.

**Pull request merged**
