### PR TITLE
Don't rewrite relative URLs when proxying HTTP content.

### PR DESCRIPTION
**Pull request by timstclair**
Fix for issue #9756

### CODE REVIEW

**Comment by davidopp** [comment]
Looking forward to two Tim* St. Clair's on the project!

**Comment by lavalamp** [comment]
@k8s-bot ok to test

**Comment by lavalamp** [comment]
This looks good to me, let's make sure the proxy e2e test I just added still passes. Shippable looks like a flake.

**Comment by timstclair** [comment]
Thanks. Do I need to rerun the e2e tests locally, or will the jenkins build handle it?

**Comment by lavalamp** [comment]
Jenkins is happy. I think this is a bug fix and we should accept this change; @davidopp do you agree?

**Comment by davidopp** [comment]
Yeah, definitely. Shippable is failing, I've seen the same error a couple of times but it always goes away on re-running so it's a flake. I'll file an issue for it and then re-run shippable on this PR.

**Comment by lavalamp** [comment]
@davidopp I'm sure there's already an issue for this flake-- I think I'll try and fix it today, it's super annoying.

**Pull request merged**
