### PR TITLE
Fix staticcheck for etcd-version-monitor

### PR DESCRIPTION
**Pull request by erain**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:
Fix static check for cluster/images/etcd-version-monitor

**Which issue(s) this PR fixes**:

Ref #81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/lgtm
/ok-to-test

Thanks!

**Comment by BenTheElder** [comment]
/approve
For hack/

**Pull request closed without merging**
