### PR TITLE
add kubectl subcommand to issue/revoke keystone tokens

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

For keystone v3 basic authentication (using username and password), we need to pass `DomainID` or `DomainName` to get authenticated (see [keystone.go#L43](https://github.com/kubernetes/apiserver/blob/master/plugin/pkg/authenticator/password/keystone/keystone.go#L43)). PR #37669 provides an alternative to concatenate username with domain name. 

While if using token-based authentication, no other credentials are provided except a token id.
 PR #25391 has already implemented this.

This PR provides a way to issue new tokens or revoke existing tokens.

cc @liggitt @kfox1111

```
add kubectl subcommand to issue/revoke keystone tokens
```

### CODE REVIEW

**Comment by liggitt** [comment]
Is this actually doing anything related to kubernetes, or just calling keystone urls directly? At first glance, it doesn't seem like a tool that belongs in kubectl.

**Comment by dixudx** [comment]
This cmd will help generate/revoke keystone token by calling keystone directly. By setting this token in `$HOME/.kube/config`, kubectl can get authenticated together with [keystone token based authentication #25391](https://github.com/kubernetes/kubernetes/pull/25391).

**Comment by liggitt** [comment]
A token management tool like this could certainly be useful, but I don't think it belongs in kubectl

**Comment by liggitt** [comment]
@kfox1111 @kubernetes/sig-cli-pr-reviews opinion on whether this belongs in kubectl?

**Comment by smarterclayton** [comment]
Generally this would be a command outside of Kubernetes.  We've discussed extensions that allow login providers to support something like `kubectl login --keystone`, but that's not on the near term roadmap.

**Comment by kfox1111** [comment]
I was kind of thinking it should function similarly to all other openstack commands. there is no explicit login, but the cli asks for a new token when needed, automatically.

In this ps, I'm not really seeing where the token is captured. Does it just print it out?

**Comment by dixudx** [comment]
@kfox1111 Yes, currently I just print it out.

**Comment by AdoHe** [comment]
this could be a good example of kubectl binary extension :) we would like to support this in the next phase.

**Comment by adohe** [comment]
refer #37499 for example usage.

**Comment by liggitt** [comment]
> @kfox1111:
> I was kind of thinking it should function similarly to all other openstack commands. there is no explicit login, but the cli asks for a new token when needed, automatically.

That's what I was expecting as well, implemented as an auth provider (more along the lines of https://github.com/kubernetes/kubernetes/pull/39587)

> @smarterclayton:
> Generally this would be a command outside of Kubernetes. We've discussed extensions that allow login providers to support something like kubectl login --keystone, but that's not on the near term roadmap.

I agree. Embedding an openstack token management command into kubectl isn't really the direction we want. Either the auth provider route (e.g. #39587) or a binary plugin (e.g. https://github.com/kubernetes/community/pull/122) could make sense for an openstack token integration.

**Pull request closed without merging**
