### PR TITLE
Add a link to the kubeadm changelog from the main k8s changelog

### PR DESCRIPTION
**Pull request by luxas**
@spiffxp @idvoretskyi @mikedanese @saad-ali A small addition to the changelog

### CODE REVIEW

**Comment by idvoretskyi** [comment]
Commit itself LGTM.

@saad-ali are we able to merge it to the "released" changelog?

**Comment by luxas** [comment]
I think it should be pretty safe, I've seen other changes to the changelog post-release as well.
This is also ok, because it just redirects users to the kubeadm-specific changelog if they are interested

**Comment by saad-ali** [comment]
> @saad-ali are we able to merge it to the "released" changelog?

Yes that's fine.

**Pull request merged**
