### PR TITLE
Unregister some metrics

### PR DESCRIPTION
**Pull request by NickrenREN**
delete some registered metrics since they are not observed

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by mtaufen** [comment]
How do we know that nobody uses these? Just curious.

**Comment by NickrenREN** [comment]
We need to let Summary/SummaryVec call Observe(...) to get accurate data. Here these just register and are not called so we can not get info we want. 
Correct me if my understanding is wrong.

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by mtaufen** [comment]
Ah, I see. 

When these metrics are exported, will a name appear somewhere for a registered but unobserved metric? Could someone be depending on this, and could the disappearance of that name break them? Do we care? What sort of API guarantees do we make for these metrics?

**Comment by NickrenREN** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/monitoring_architecture.md

**Comment by dashpole** [comment]
can you also remove these from test/e2e/framework/kubelet_stats.go, and any tests that use them?

**Comment by NickrenREN** [comment]
@dashpole I have already removed them from test/e2e/framework/kubelet_stats.go, and can not find anywhere use them.

**Comment by dashpole** [comment]
Oh, sorry.  I completely missed that you had already removed them.
/lgtm

**Comment by NickrenREN** [comment]
Thanks @dashpole

**Comment by derekwaynecarr** [comment]
Were these metrics ever observed?
Do you know when they were no longer observed?  If not, I would like to understand that before approving.

**Comment by NickrenREN** [comment]
I do not think they are observed but i can not find when they were no longer observed

**Comment by dashpole** [comment]
a little digging shows that SyncPodsLatency was added back when SyncPods was a function... #4905

**Comment by NickrenREN** [comment]
ping @kow3ns  for approval

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Pull request merged**
