### PR TITLE
Automated cherry pick of #83027: Update go mod hcsshim version to fix the kube-proxy issue

### LINKED ISSUE #79515: The kubernetes 1.15 kube-proxy report  "Unable to find HNS Network specified by cbr0"  on windows  node
**What happened**:

When i upgrade my kubernetes cluster windows node  to 1.15,the windows node kube-proxy cannot work properly.  My  windows deployment cannt access by Nodeip:Port on this node but it can access by  the same cluster other nodes with  Nodeip:Port 

When i rollback my windows node  to 1.14.1 .  the kube-proxy works good, everything is ok

The kube-proxy logs  Loop Report that.

```
E0628 16:57:08.673912    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:08.673912    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
E0628 16:57:09.679372    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:09.679372    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
```

* 1.15.0

image

At this version , i cannot access my application by current node ip and the port

image

---------

* 1.14.1
image

At this version , i can access my application by current node ip and the port

image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows server 2019 (10.0.17763.134)
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel host-gw
- Others:
@feiskyer @andyzhangx

### PR DESCRIPTION
**Pull request by wawa0210**
Cherry pick of #83027 on release-1.16.

#83027: Update go mod hcsshim version to fix the kube-proxy issue cannot access service by self nodeip:port on windows

**What type of PR is this?**
/kind bug

**What this PR does / why we need it:**
fix the kube-proxy issue cannot access service by self nodeip:port on windows

**Which issue(s) this PR fixes:**
Fixes #79515

**Does this PR introduce a user-facing change?:**
```release-note
Fixes kube-proxy bug accessing self nodeip:port on windows
```
/sig network windows

@feiskyer @liggitt @BenTheElder @PatrickLang @dims

### CODE REVIEW

**Comment by tpepper** [comment]
/priority important-soon
/ok-to-test

@wawa0210 can you edit this PR's description to include the same note from https://github.com/kubernetes/kubernetes/pull/83027 as per https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md.

Also please in the future use the lastest https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh for cherry picks to insure the most up to date automation is creating the PR.

**Comment by wawa0210** [comment]
> /priority important-soon
> /ok-to-test
> 
> @wawa0210 can you edit this PR's description to include the same note from #83027 as per https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md.
> 
> Also please in the future use the lastest https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh for cherry picks to insure the most up to date automation is creating the PR.

Thx, done .

**Comment by liggitt** [comment]
/approve
for vendoring

**Pull request merged**
