### PR TITLE
Remove wrapper around base LeaderElectionConfiguration

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

The wrapper was a leftover from previous overrides we had on the type.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/assign @Huang-Wei 
for first pass

**Review by damemi — APPROVED** [review]
/lgtm

**Review by Huang-Wei — COMMENTED** [review]
/approve

**Comment by alculquicondor** [comment]
/priority important-soon

This will simplify v1beta1

**Comment by alculquicondor** [comment]
friendly ping @lavalamp

**Pull request merged**
