### PR TITLE
[Kubelet] Delay deletion of pod from the API server until volumes are deleted

### PR DESCRIPTION
**Pull request by dashpole**
Previous PR that was reverted: #40239.

To summarize the conclusion of the previous PR after reverting:
- The status manager has the most up-to-date status, but the volume manager uses the status from the pod manager, which only is as up-to-date as the API server.
- Because of this, the previous change required an additional round trip between the kubelet and API server.
- When few pods are being added or deleted, this is only a minor issue.  However, when under heavy load, the QPS limit to the API server causes this round trip to take ~60 seconds, which is an unacceptable increase in latency. Take a look at the graphs in #40239 to see the effect of QPS changes on timing.
- To remedy this, the volume manager looks at the status from the status manager, which eliminates the round trip.

cc: @vishh @derekwaynecarr @sjenning @jingxu97 @kubernetes/sig-storage-misc

### CODE REVIEW

**Comment by dashpole** [comment]
Dark Grey = Kubelet receives deletion request in syncloop
Red = Kubelet processes container exited PLEG event
Light Grey = Volume is torn down
Purple = Pod is deleted from the API server
screenshot from 2017-02-07 14 31 42

Notice that there is now very little delay between red and light grey, as a result of the change in the volume manager in this PR.
The gradual slope of the purple line is due to QPS limits, and is expected.

**Comment by dashpole** [comment]
I also just ran all node-e2e tests on this PR on all images that we test on, and it passed all tests without any flakes.

**Comment by dashpole** [comment]
And just for reference, this is what the profile looked like before this change.  The difference is that previously volume teardown (light grey) occurred after deletion finished (purple).  Now volume teardown happens immediately after the containers are terminated.
screenshot from 2017-02-07 15 24 51

**Comment by dashpole** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by vishh** [comment]
Can you squash the last two commits as it will make reverts easy via git?

**Comment by vishh** [comment]
squash the commits and I will approve it

**Comment by dashpole** [comment]
wanted to make it easier to review, as the last two commits are the only changes from the previous PR

**Comment by dashpole** [comment]
@vishh rebasing removed the lgtm...

**Comment by ncdc** [comment]
@dashpole I'm not sure if this is the culprit, but since this PR merged, 5 out of the 6 runs of https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/ have failed waiting for a pod to be deleted. WDYT?

**Comment by ncdc** [comment]
Or is that what #41157 is trying to address?

**Comment by dashpole** [comment]
Yes

**Comment by dashpole** [comment]
@ncdc with regards to the node-kubelet tests, I am surprised that it failed so often on those runs compared with [the node-e2e testgrid runs](https://k8s-testgrid.appspot.com/google-node#kubelet), which have only flaked occasionally...

**Pull request merged**
