### PR TITLE
test images: use recently promoted images

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**

Based on #87607.
Part of [kubernetes/k8s.io#1522](https://github.com/kubernetes/k8s.io/issues/1522), #96770.

This PR uses test images promoted in https://github.com/kubernetes/k8s.io/pull/1558 and https://github.com/kubernetes/k8s.io/pull/1566.

/sig testing
/sig windows
/kind cleanup
/priority important-soon
/cc @claudiubelu @jsturtevant 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
This is consistent with what I was testing in my PR: https://github.com/kubernetes/kubernetes/pull/87607

There are a few other images that have been promoted since then. We could bump those later if needed:

- apparmor-loader
- metadata-concealment
- echoserver
- resource-consumer

**Comment by chewong** [comment]
With https://github.com/kubernetes/k8s.io/pull/1566 merged, I included the following promoted test images in my latest commit:
- `k8s.gcr.io/e2e-test-images/apparmor-loader:1.3`
- `k8s.gcr.io/e2e-test-images/echoserver:2.3`
- `k8s.gcr.io/e2e-test-images/redis:5.0.5-alpine`

I did not include the following images in this PR:
- `k8s.gcr.io/e2e-test-images/metadata-concealment:1.6` - in the process of being promoted by https://github.com/kubernetes/k8s.io/pull/1577. WIP PR: https://github.com/kubernetes/kubernetes/pull/98336.
- `k8s.gcr.io/e2e-test-images/resource-consumer:1.8` I'd prefer to have Windows support for this test image before introducing it here so we won't break jobs like https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd. PR to add Windows support for resource-consumer: https://github.com/kubernetes/kubernetes/pull/92719.

/assign @spiffxp

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
