### PR TITLE
Improved event message for ServiceController.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Improved event message for ServiceController. Follow up of #13992.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Cherry-pick of #14822.

**Comment by erictune** [comment]
See my comment on original on why this might not be a good idea.

**Comment by zmerlynn** [comment]
Sorry, scanning cherry picks and this looks like the script mis-fired. Were you a victim of a "hub" command issue?

**Comment by jszczepkowski** [comment]
Closing as this cherry-pick is of very low priority and of arguable value.

**Pull request closed without merging**
