### PR TITLE
Automated cherry pick of #14566

### PR DESCRIPTION
**Pull request by erictune**
Cherry pick of #14566 on release-1.1.

### CODE REVIEW

**Comment by mikedanese** [comment]
might want to cherrypick #15045 with this or release branch e2e won't run on GKE.

**Comment by a-robinson** [comment]
@erictune can you also please cherrypick #15045, as suggested by @mikedanese?

**Comment by jlowdermilk** [comment]
Might be easier to close this and rerun cherrypick script.

**Comment by erictune** [comment]
I tried to pick both with one command, and for reasons I don't understand, there are 83 commits on the PR: https://github.com/kubernetes/kubernetes/pull/15161

I suggest you merge this PR and then I'll send the follow-on PR with #15045 right after.

**Comment by erictune** [comment]
Okay, closing in favor of https://github.com/kubernetes/kubernetes/pull/15162

**Pull request closed without merging**
