### PR TITLE
Fix the logic around the AWS instance test

### PR DESCRIPTION
**Pull request by justinsb**
We test that when we get instances with the same name that we get an error

### CODE REVIEW

**Comment by justinsb** [comment]
I'm a little perplexed here, because I don't see how this test could ever have passed

**Comment by erictune** [comment]
yeah.  It looks like you are generating an error anytime there is more than 1 host.  Possibly it is a bug in the mockInstancesResponse or FakeEC2

**Comment by erictune** [comment]
The fix you have is certainly necessary, but I'll leave this open while you debug a little more.

**Comment by justinsb** [comment]
Aha:  the EC2 instance filter is not applied by mockInstancesResp, so we always see all the instances.  In the patch where I actually found this, I also implemented a sanity-check filter on PrivateIpAddress.

I will rework this patch, so that we apply the filter in mockInstancesResp, I think.  Then this change should be required.

**Comment by justinsb** [comment]
Implemented EC2 filter in a testable way.  Tests should fail.  Then I will re-push with the instance2 -> instance1 patch, and tests should pass again.

**Comment by justinsb** [comment]
As expected, failed with:

```--- FAIL: TestIPAddress (0.00s)
	aws_test.go:152: Should error when multiple instances found
FAIL
```

Push the fix to the test now!

**Comment by justinsb** [comment]
Passing again :-)

Feel much happier about this now.  I think the extra abstraction is probably a step forwards ... I can see us replacing goamz when the official Amazon golang client is officially released, and this gets us a little closer to that.

**Comment by erictune** [comment]
thanks for figuring out the discrepancy!

**Pull request merged**
