### PR TITLE
Remove item from taint manager workqueue on completion

### PR DESCRIPTION
**Pull request by liggitt**
fixes a memory leak observed in the controller manager when creating/deleting pods containing tolerations

xref #65325

```release-note
fixes a memory leak in the kube-controller-manager observed when large numbers of pods with tolerations are created/deleted
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-scheduling-bugs 
/assign @wojtek-t

**Comment by kj187** [comment]
Thanks! Is this just fixed for kubernetes v1.11.x ? 
Not v1.9.x or 1.8.x ?

**Comment by liggitt** [comment]
fixes are in:
* 1.8.x in https://github.com/kubernetes/kubernetes/pull/65365
* 1.9.x in https://github.com/kubernetes/kubernetes/pull/65364
* 1.10.x in https://github.com/kubernetes/kubernetes/pull/65363

**Pull request merged**
