### PR TITLE
improve and modify log

### PR DESCRIPTION
**Pull request by zdj6373**
1, the content of a unified writing, compared to the following line of failure (314th lines)
2, “instance” should be “node”

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36051)

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@zdj6373 kindly sign the CLA

**Comment by zdj6373** [comment]
@vishh Has signed CLA, thank you

**Comment by zdj6373** [comment]
@k8s-bot cvm gke e2e test this

**Comment by zdj6373** [comment]
GKE smoke e2e fail： issue has been raised (Cannot bring up GCI GKE e2e cluster: "cluster_api_version not found" #35913).
My changes will not cause test problems.

**Comment by zdj6373** [comment]
@vishh ，Need to add labels to ok-to-merge and release-note-none?

**Comment by saad-ali** [comment]
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Adding 1.5 milestone to let it gets merged after code freeze.

**Pull request merged**
