### PR TITLE
job controller: Make sure the number of succeeded and failed never decrease

### LINKED ISSUE #81227: Job controller should remember number of completion
**What happened**:
When a `Completed` pod is deleted, `Job` controller decreases the number of completions and schedule new pods.

```
kubectl get job backfill --watch
NAME          COMPLETIONS   DURATION   AGE
backfill   30/36         41h        41h
backfill   29/36         41h        41h
backfill   28/36         41h        41h
backfill   27/36         41h        41h
backfill   26/36         41h        41h
backfill   27/36         41h        41h
backfill   28/36         41h        41h
backfill   29/36         41h        41h
backfill   30/36         41h        41h
backfill   31/36         41h        41h
backfill   32/36         41h        41h
```

**What you expected to happen**:
Completed is completed for good. Logically speaking, a completed task cannot be "uncompleted". 
So, when a `Completed` pod is deleted, `Job` controller should not decrease the number of completions.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a batchjob with `.spec.completions=X`.
2. When there are Y pods reaches `Completed` phase, you should see `Y/X` in `COMPLETIONS` column when you `kubectl get job`
3. Manually delete some completed pods
4. You should now see number of completions decreases and new pods will be scheduled.

**Anything else we need to know?**:
In our environment, we have a cluster autoscaler that kills idling nodes. When the node is terminated, all the `Completed` pods on it will be gone. That's when I notice this behavior.
I looked into the Job controller's code and it seems like the controller is stateless and is completely rely on the result of listing pods to determine the status of the job.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.8
- Cloud provider or hardware configuration: AWS

### PR DESCRIPTION
**Pull request by hainesc**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Recently, job controller calculates the number of succeeded and failed from pods that maintained by that job. However, when the user delete some pods(any reason), the number of succeeded or failed decreases. 

Completed is completed for good. Logically speaking, a completed task cannot be "uncompleted".
So, when a Completed pod is deleted, Job controller should not decrease the number of completions.

**Which issue(s) this PR fixes**:
Fixes #81227

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

Thanks!

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews PTAL.

Thanks!

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @sig-apps-reviewers for review.

**Comment by hainesc** [comment]
ping @cheftako @deads2k for review, thanks.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-pr-reviews for review.

**Comment by hainesc** [comment]
ping @kubernetes/sig-apps-bugs

**Comment by hainesc** [comment]
ping @deads2k @cheftako @janetkuo @derekwaynecarr @mikedanese Please...

**Comment by mikedanese** [comment]
This is working as intended, and this change likely breaks all tests. Controllers cannot use the status of an object to compute the next status of an object. Jobs checkpoint their progress using succeeded pod objects.

**Comment by hainesc** [comment]
@mikedanese Thanks for your response.
> Jobs checkpoint their progress using succeeded pod objects.

Sorry for the wrong using of status.
Please see #81227, Just for clarify, When a completed pod is deleted, Job controller decreases the number of completions and schedule new pods, and as the reporter said
> Completed is completed for good. Logically speaking, a completed task cannot be "uncompleted".
So, when a Completed pod is deleted, Job controller should not decrease the number of completions.

Is that working as intended? If true, I will close this PR.

**Comment by cheftako** [comment]
> @mikedanese Thanks for your response.
> 
> > Jobs checkpoint their progress using succeeded pod objects.
> 
> Sorry for the wrong using of status.
> Please see #81227, Just for clarify, When a completed pod is deleted, Job controller decreases the number of completions and schedule new pods, and as the reporter said

Status should never be a source of truth, it should be derivable from the actual source of truth. (Essentially what Mike said). Using completed pod objects as the source of truth follows this principle but unfortunately acts as a memory leak until the job completes. So the system was adjusted to prevent the memory leak.

> > Completed is completed for good. Logically speaking, a completed task cannot be "uncompleted".
> > So, when a Completed pod is deleted, Job controller should not decrease the number of completions.
> 
> Is that working as intended? If true, I will close this PR.

It is technically working as intended but I think many of us would prefer a better solution. However we should not be using the status to track completed/failed occurrences. Similarly we should not be using spec as it is only meant to contain the goal state and the current state is not the goal state.

**Pull request closed without merging**
