### PR TITLE
Automated cherry pick of #75349: Daemon Set Conformance test fails in CI process using ci-kubernetes-c…

### PR DESCRIPTION
**Pull request by tnozicka**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
backport conformance fix https://github.com/kubernetes/kubernetes/pull/75349

probably just forgotten in https://github.com/kubernetes/kubernetes/pull/75349#issuecomment-475472318

```release-note
NONE
```

/cc @kubernetes/sig-apps-pr-reviews @smarterclayton @sjenning

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/assign @tpeper 
for cherry-pick approval

**Comment by tnozicka** [comment]
@kubernetes/patch-release-team for cherry-pick approval

**Comment by smarterclayton** [comment]
Also approve, conformance tests have a high bar and this impacts conformant
distributions.

**Pull request merged**
