### PR TITLE
Fix normal request metric verb correctly

### PR DESCRIPTION
**Pull request by kkkkun**
Signed-off-by: kkkkun <scuzk373x@gmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When a request which is getting logs comes to apiserver，it is labeled as `CONNECT` in `apiserver_longrunning_gauge`,  but it is labeled as `GET` in `apiserver_request_duration_seconds_bucket`. We should label all to `CONNECT`  verb correctly.

# before:
```
kubectl  get  --raw="/metrics" |  grep log 
# HELP apiserver_audit_requests_rejected_total [ALPHA] Counter of apiserver requests rejected due to an error in audit logging backend.
apiserver_longrunning_gauge{component="apiserver",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.005"} 8
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.01"} 22
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.02"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.03"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.04"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.05"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.1"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.15"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.2"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.25"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.3"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.35"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.4"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.45"} 25
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.5"} 28
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.6"} 31
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.7"} 31
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.8"} 31
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="0.9"} 32
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="1"} 33
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="1.25"} 33
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="1.5"} 33
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="1.75"} 36
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="2"} 36
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="2.5"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="3"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="3.5"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="4"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="4.5"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="5"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="6"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="7"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="8"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="9"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="10"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="15"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="20"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="25"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="30"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="40"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="50"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="60"} 39
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1",le="+Inf"} 39
apiserver_request_duration_seconds_sum{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1"} 17.326923664000002
apiserver_request_duration_seconds_count{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1"} 39
apiserver_request_total{code="200",component="apiserver",contentType="text/plain",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1"} 18
apiserver_request_total{code="500",component="apiserver",contentType="application/json",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="GET",version="v1"} 21
```
# after
```
kubectl  get  --raw="/metrics" |  grep log 
# HELP apiserver_audit_requests_rejected_total [ALPHA] Counter of apiserver requests rejected due to an error in audit logging backend.
apiserver_longrunning_gauge{component="apiserver",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.005"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.01"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.02"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.03"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.04"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.05"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.1"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.15"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.2"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.25"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.3"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.35"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.4"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.45"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.5"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.6"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.7"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.8"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="0.9"} 3
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="1"} 3
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="1.25"} 3
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="1.5"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="1.75"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="2"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="2.5"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="3"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="3.5"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="4"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="4.5"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="5"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="6"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="7"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="8"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="9"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="10"} 6
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="15"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="20"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="25"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="30"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="40"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="50"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="60"} 9
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1",le="+Inf"} 9
apiserver_request_duration_seconds_sum{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1"} 42.375272964
apiserver_request_duration_seconds_count{component="apiserver",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1"} 9
apiserver_request_total{code="200",component="apiserver",contentType="text/plain",dry_run="",group="",resource="pods",scope="resource",subresource="log",verb="CONNECT",version="v1"} 9
```

#### Which issue(s) this PR fixes:
Fixes # 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
this is a follow up on https://github.com/kubernetes/kubernetes/pull/111988 , right?

**Comment by kkkkun** [comment]
> this is a follow up on #111988 , right?

Yes, it's imported by #111988.

**Comment by wojtek-t** [comment]
Heh... - thanks for catching this.

/lgtm
/approve

**Pull request merged**
