### PR TITLE
Use `--oom-score-adj` flag for kube-proxy

### LINKED ISSUE #51083: kube-proxy manifest should use `--oom-score-adj` flag (?)
In cluster/saltbase/salt/kube-proxy/kube-proxy.manifest, we have this:

```
    command:
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj && kube-proxy {{api_servers_with_port}} {{kubeconfig}} {{cluster_cidr}} --resource-container="" {{params}} 1>>/var/log/kube-proxy.log 2>&1
```

But kube-proxy also has a `--oom-score-adj` flag.  Is there a reason to use the `echo` approach instead of using the flag?

cc @vishh as you wrote the code, in https://github.com/kubernetes/kubernetes/pull/41700

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Replace `echo -998 > /proc/$$$/oom_score_adj` with `--oom-score-adj` flag for kube-proxy.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51083

**Special notes for your reviewer**:
/assign @justinsb @vishh 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Humm..Just noticed we got:
```
I0823 21:29:22.085533       5 server.go:621] setting OOM scores is unsupported in this build
```

**Comment by MrHohn** [comment]
Seems like it's because kube-proxy is built statically and we set `CGO_ENABLED=0` for static builds:
https://github.com/kubernetes/kubernetes/blob/470eb922abf0061c1e4a7f14ab4b866ff65f3372/hack/lib/golang.sh#L507-L542

And we put `cgo` build flag in oom_linux.go, which makes it unusable for kube-proxy:
https://github.com/kubernetes/kubernetes/blob/470eb922abf0061c1e4a7f14ab4b866ff65f3372/pkg/util/oom/oom_linux.go#L1

Checked the oom package and its dependency, didn't find anything that calls C code. Likely someone already removed that dependency.

I'm adding a second commit to remove the cgo build flag on oom package.
+cc @kubernetes/sig-node-pr-reviews in case I missed something.

**Comment by MrHohn** [comment]
Seems it works:
```
I0824 03:47:35.989349       5 oom_linux.go:65] attempting to set "/proc/self/oom_score_adj" to "-998"
```

From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51221/pull-kubernetes-e2e-gce-etcd3/49523/artifacts/e2e-49523-minion-group-03tm/kube-proxy.log

**Comment by MrHohn** [comment]
Rebased. Made changes on kube-proxy daemonset as well.

**Comment by justinsb** [comment]
/lgtm

But the cgo changes are something I have no knowledge of...

**Comment by MrHohn** [comment]
Thanks!

@Random-Liu Do you think the cgo change makes sense?

**Comment by MrHohn** [comment]
> @random-liu Do you think the cgo change makes sense?

Discussed with @Random-Liu offline, we believe this is reasonable.

/assign @thockin 
for approval.

**Pull request merged**
