### PR TITLE
Spelling mistakes: an to a conversions

### LINKED ISSUE #99002: [e2e tests] Typo in logs
https://github.com/kubernetes/kubernetes/blob/4364ef62062d3d18b0a0cec117af9620f8a896ff/test/e2e/kubectl/kubectl.go#L1393

### PR DESCRIPTION
**Pull request by sbeginCoveo**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Lots of spelling errors. 
Only changed comments, markdown and some descriptions/logs. Should not have any impact other than aesthetic

Fixes #99002

### CODE REVIEW

**Comment by apelisse** [comment]
How did you do that?

**Comment by sbeginCoveo** [comment]
> How did you do that?

By find-and-replace using regex and reviewing the resulting changes.
Some combinations took longer to review, for example:
```
A secure shell client
An SSH client
```

**Comment by apelisse** [comment]
@sftim Do you have an opinion on this kind of PRs?

**Comment by sftim** [comment]
This looks hard to review! @sBeginCoveo it looks like you've included proposed changes to `vendor` and other parts of Kubernetes that are copies elsewhere. Could you narrow this to just primary copies? I suggest you pick a small area first and then widen it once you're happy with the approach.

**Comment by neolit123** [comment]
/approve
for /test and /cmd/kubeadm
/triage accepted
/priority backlog
/ok-to-test

**Comment by neolit123** [comment]
> changes to vendor and other parts of Kubernetes that are copies elsewhere

/vendor should be exlcuded, i did not notice that.

**Review by pacoxu — APPROVED** [review]

**Comment by sbeginCoveo** [comment]
@sftim @neolit123 
If there are other folders to exclude, please mention them and I'll make the change

**Comment by sftim** [comment]
@sbeginCoveo could you squash this down so that the changes to `/vendor` aren't part of the PR? I recommend that. Merge conflicts with vendored code aren't something we want to risk.

**Comment by SergeyKanzhelev** [comment]
> pull-kubernetes-bazel-test — Job failed.

Instead of updating test/conformance/testdata/conformance.yaml  manually, use instruction from here: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/README.md

**Pull request closed without merging**
