### PR TITLE
Added getting started guide for CentOS

### PR DESCRIPTION
**Pull request by coolsvap**
Added getting started guide to setup one minion
setup using CentOS

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM.
Thanks for the PR @coolsvap!

**Comment by nikhiljindal** [comment]
It should not be due to your change, but travis is failing for Go 1.3 with the following error:
"panic: runtime error: index out of range"

Will wait for it to be resolved before merging this.

**Comment by coolsvap** [comment]
Oh, I was not aware, thanks @nikhiljindal

**Comment by nikhiljindal** [comment]
Travis is green now. Merging.

**Comment by thockin** [comment]
Was just scanning this - my understanding is that CentOS does not have iptables, but kubernetes NEEDS iptables or else service proxying will not work.

**Comment by derekwaynecarr** [comment]
This reminds me that I would like to make an option in our vagrant setup to use CentOS 7 box at some point as an alternative to Fedora 20.  Any chance you want to look at seeing what issues may arise by using a different box?  Advantage being that you could reuse the networking setup ideally there as well. Either way, this PR LGTM.

**Comment by derekwaynecarr** [comment]
CentOS has iptables.  

http://wiki.centos.org/HowTos/Network/IPTables

**Comment by thockin** [comment]
Hmm, I was helping someone out today and saw many pages that said CentOS7
uses firewalld and does not install iptables by default...

**Comment by derekwaynecarr** [comment]
I could be mixing up 6 vs 7.  Will look in morning.

**Pull request merged**
