### PR TITLE
Remove GetClientsetForCluster()

### PR DESCRIPTION
**Pull request by FengyunPan**
The newClusterClientset() has insteaded of GetClientsetForCluster(),
and GetClientsetForCluster() run wrong. Let's remove it.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
Thanks @FengyunPan 
I'm happy to remove this function if it's truly unused, but a quick search suggests that it's still being referenced?

https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=GetClientSetForCluster&type=

**Comment by FengyunPan** [comment]
Sorry, I can't find where it's still being referenced.
And the 'if err != nil && clusterConfig != nil' is wrong, it should be 'if err == nil && clusterConfig != nil'

**Comment by FengyunPan** [comment]
@k8s-bot bazel test this
@k8s-bot cvm gce e2e test this

**Comment by quinton-hoole** [comment]
@FengyunPan Did you try the link I posted above.  The function is referenced in:

federation/pkg/federation-controller/util/federated_updater_test.go
federation/pkg/federation-controller/util/federated_informer.go
federation/pkg/federation-controller/util/federated_updater.go
federation/pkg/federation-controller/util/cluster_util.go

**Comment by quinton-hoole** [comment]
@FengyunPan never mind, I see that those are not real references to the function that you're removing. 

/lgtm

**Comment by FengyunPan** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
