### PR TITLE
fix data races in scheduler unit tests

### LINKED ISSUE #88327: Data races in scheduler unit tests
**Which jobs are flaking**:
pull-kubernetes-bazel-test

**Which test(s) are flaking**:
pkg/scheduler/internal/queue

**Testgrid link**:

**Reason for failure**:
```
WARNING: DATA RACE
Write at 0x00c000337268 by goroutine 49:
  k8s.io/kubernetes/pkg/scheduler/internal/heap.(*data).Pop()
      pkg/scheduler/internal/heap/heap.go:107 +0x130
  container/heap.Pop()
      GOROOT/src/container/heap/heap.go:64 +0xb0
  k8s.io/kubernetes/pkg/scheduler/internal/heap.(*Heap).Pop()
      pkg/scheduler/internal/heap/heap.go:200 +0x5b
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).flushBackoffQCompleted()
      pkg/scheduler/internal/queue/scheduling_queue.go:338 +0x23f
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).flushBackoffQCompleted-fm()
      pkg/scheduler/internal/queue/scheduling_queue.go:325 +0x41
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x6f
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb3
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x145
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x5a
Previous read at 0x00c000337268 by goroutine 48:
  k8s.io/kubernetes/pkg/scheduler/internal/queue.TestPriorityQueue_MoveAllToActiveOrBackoffQueue()
      pkg/scheduler/internal/heap/heap.go:239 +0x427
  testing.tRunner()
      GOROOT/src/testing/testing.go:909 +0x199
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-02-19&pr=1&text=WARNING%3A%20DATA%20RACE&job=bazel
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86476/pull-kubernetes-bazel-test/1229849536218796032
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88105/pull-kubernetes-bazel-test/1229183151083884546

/sig scheduling
/assign @ahg-g

### PR DESCRIPTION
**Pull request by Ye-Tian-Zero**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Fix data races in scheduler unit tests.

**Which issue(s) this PR fixes**:

Fixes #88327 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by wgliang — APPROVED** [review]
Thanks for your PR.

And you can run test local.

`make test KUBE_RACE="-race" WHAT=./pkg/scheduler/internal/queue`

/lgtm

**Comment by ahg-g** [comment]
I think there are other instances in this test file where the heaps (both activeQ and backoffQ) are accessed without locking.

**Comment by skilxn-go** [comment]
Right, I will fix them.

**Review by ahg-g — COMMENTED** [review]
wish we can wrap all those calls instead of doing lock/unlock all over the file. perhaps a follow up PR?

/lgtm
/approve

**Comment by skilxn-go** [comment]
Sure, I had thought about it. This pr is a quick fix, and I'll append one commit for the wrapper work.

**Pull request merged**
