### PR TITLE
Fix golint errors in pkg/controller/namespace

### PR DESCRIPTION
**Pull request by ghost**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint errors in `pkg/controller/namespace` (part of broader golint effort).

**Which issue(s) this PR fixes**:

Ref https://github.com/kubernetes/kubernetes/issues/68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/lgtm

I think avoiding the stutter here makes sense.

**Review by cheftako — COMMENTED** [review]
/lgtm

**Review by SataQiu — COMMENTED** [review]
Thanks @cristiandima 
/lgtm
/approve

**Pull request closed without merging**
