### PR TITLE
Automated cherry pick of #105509: Fix PreferNominatedNode test

### PR DESCRIPTION
**Pull request by chendave**
Cherry pick of #105509 to release-1.22. The feature is enabled by default in 1.22.

Once the node gets deleted, the nodelifecycle controller
is racing to update pod status and the pod deletion logic
is failing causing tests to flake. This commit moves
the testContext creation to within the test loop and deletes nodes,
namespace within the test loop. We don't explicitly call the node
deletion within the loop but the `testutils.CleanupTest(t, testCtx)`
call ensures that the namespace, nodes gets deleted.

#### What type of PR is this?

/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @ravisantoshgudimetla

### CODE REVIEW

**Comment by alculquicondor** [comment]
Was there no integration test in 1.21?

**Comment by alculquicondor** [comment]
If there is flakiness in the testgrid, we should backport it, regardless of alpha state.

**Comment by chendave** [comment]
> If there is flakiness in the testgrid, we should backport it, regardless of alpha state.

Done, pls see: https://github.com/kubernetes/kubernetes/pull/105665

**Comment by chendave** [comment]
cc: @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
