### PR TITLE
migrate proxy/winuserspace/proxier.go logs to structured logging

### PR DESCRIPTION
**Pull request by JornShen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

part of https://github.com/kubernetes/enhancements/issues/1602

**Which issue(s) this PR fixes**:

[keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)

[Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
