### PR TITLE
feat: support proxy protocol for kube-proxy healthchecks

### PR DESCRIPTION
**Pull request by aslafy-z**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR adds support for Haproxy Proxy Protocol to kube-proxy health checks.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kube-proxy: add proxy protocol support to healthchecks
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
can you expand on why do we need to support the haproxy proxy protocol?

**Comment by aslafy-z** [comment]
When you attach a Private Link Service with proxy-protocol enabled to a LB on azure, all the probes now are emitted using proxy-protocol. I want to use kube-proxy ProxyTerminatingEndpoint feature, so I need my LB to query kube-proxy endpoint. Since it does not support proxy-protocol, requests from my probes fails. It's unlikely that Azure changes this in the future. Do you see an other way around?

**Comment by aojea** [comment]
> ProxyTerminatingEndpoint feature, so I need my LB to query kube-proxy endpoint.

you have to use externalTrafficPolicy = Local and poll the HealthCheckNodePort not the kube-proxy endpoint

**Comment by aslafy-z** [comment]
Isn't healthCheckNodePort handled by kube-proxy?

**Comment by aojea** [comment]
> Isn't healthCheckNodePort handled by kube-proxy?

I see, once you enable PROXY protocol is it also enabled for the healthcheck https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview, I didn't understand what one was related to the other.

> HTTP/TCP health probes from host to the backend virtual machines

My reading of these docs https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview
is that the probes will probe the backend directly , not the kube-proxy healtcheck, have you tested that the probes fails on the kube-proxy listeners or is your intuition ?

Bear in mind this is not likely to merge, we already discarded similar PRs in other components https://github.com/kubernetes/kubernetes/pull/96452

**Comment by aslafy-z** [comment]
@aojea The thing is I WANT the probes to query the kube-proxy healthcheck for ProxyTerminatingEndpoint feature to be usable. I tested it, I confirm the probes fails when trying to query kube-proxy. Check the note on this page: https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/, it explains it explicitly.

**Comment by aojea** [comment]
> Check the note on this page: https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/, it explains it explicitly.

Ok, this information is new, so the cloud-provider can make its own choices

> hen service’s externalTrafficPolicy is set to Local, health probe depends on kube-proxy’s [health check service](https://github.com/kubernetes/kubernetes/blob/15a1f9a39db95a7f83ce5463a328566411d99d51/pkg/proxy/healthcheck/service_health.go#L187) which does not accept proxy protocol and all health probes fail

this sentence is confusing, kube-proxy provides two healtcheck signals to the external infrastructure, and neither of both support the proxy protocol,  

* if externalTrafficPolicy: Cluster, kube-proxy exports a healtcheck on the port 10256 by default https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/cmd/kube-proxy/app/server.go#L637-L638
* if externalTrafficPolicy: Local , then it allocates a NodePort that will return the number endpoints running on that node https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
 
any loadbalancer provider can use whatever signal they consider and is an implementation detail of this provider of using the proxy protocol for the healtcheck, so it seems that is more reasonable to ask cloud-provider-azure to support the existing implementation of Kubernetes , that was this way since the beginning

**Comment by aslafy-z** [comment]
Sure, I'm am already working with my contact at Microsoft for them to reconsider this Private Link Service with LB health probes behavior. I'd love to see some news on their side. I will close this PR. Thank you for your feedback!

**Comment by aojea** [comment]
> e to see some news on their side. I will close this PR. Thank you for your feedback!

no worries, if you have another ideas or there is something less "invasive" that can help don't hesitate to share, opening an issue for discussion or attending SIG Network meetings are good places for these conversations

**Pull request closed without merging**
