### PR TITLE
updating github.com/go-bindata/go-bindata to v3.1.1

### LINKED ISSUE #79229: Move from jteeuwen/go-bindata to go-bindata/go-bindata
https://github.com/jteeuwen/go-bindata is now archived by its owner. Contributors have created a new org and are working there https://github.com/go-bindata/go-bindata

So we should switch to code from the new repo.

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I66c047a4e5e72632042f43a9f4b33ab9f5bf7ef1

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
https://github.com/jteeuwen/go-bindata is now archived by its owner. Contributors have created a new org and are working there https://github.com/go-bindata/go-bindata

So we should switch to code from the new repo.

**Which issue(s) this PR fixes**:

Fixes #79229

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @thockin @liggitt 

(for root approval as we touch go.* files)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
