### PR TITLE
Automated cherry pick of #75515: godeps: update vmware/govmomi to v0.20 release

### PR DESCRIPTION
**Pull request by rhockenbury**
Cherry pick of #75515 on release-1.14.

#75515: godeps: update vmware/govmomi to v0.20 release

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
/lgtm

**Comment by liggitt** [comment]
this is a huge cherry-pick. is this in support of a new feature?

**Comment by dougm** [comment]
@liggitt it's just a bug fix, but required godeps update of the vmware/govmomi package.  And the majority of the govmomi update is in the `govmomi/simulator` package which is only used in `*_test.go`

The bug fix itself is this commit: https://github.com/kubernetes/kubernetes/pull/75742/commits/fdd0a452324a25fabffff14d5cffeb11368a599b

**Comment by dougm** [comment]
Increases the binary size by about 70K.  Before the change:

```console
% git show
commit b0158cea1616f8b1748a9bbc1afef425244963f7 (HEAD)
Merge: 753a6edc37 a7f9ffd39f
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Mar 26 12:34:03 2019 -0700

    Merge pull request #75399 from sttts/sttts-initial-bulk-openapi-merge
    
    apiextensions: merge OpenAPI specs once after cache sync

% ls -l --block-size=K ./_output/local/go/bin/hyperkube                                                   
-rwxrwxr-x 1 dougm dougm 206127K Mar 26 14:56 ./_output/local/go/bin/hyperkube*
```
After:
```console
% git show
commit 9c973c6d2c33e88521ebcebec2fdd9cbddccd857 (HEAD)
Merge: b0158cea16 85907f6947
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Mar 26 12:34:17 2019 -0700

    Merge pull request #75515 from dougm/vsphere-token-auth
    
    vSphere: add token auth support for tags client

% ls -l --block-size=K ./_output/local/go/bin/hyperkube
-rwxrwxr-x 1 dougm dougm 206199K Mar 26 15:04 ./_output/local/go/bin/hyperkube*
```

**Comment by rhockenbury** [comment]
@dims @thockin @sttts  Can we get an approval?

**Comment by dims** [comment]
/assign @aleksandra-malinowska @tpepper 

@rhockenbury pinging the patch release managers... we still need to get an ok from @liggitt (for his concern above)

**Comment by liggitt** [comment]
concerns about the size are mostly allayed, since it doesn't impact build/binary size.

I'll defer to the component owners on the feature vs bug characterization, just wanted to ask the question.

**Comment by rhockenbury** [comment]
@dims Would you be willing to approve now?

**Comment by dims** [comment]
/approve

(not that my approval will mean much ... @aleksandra-malinowska @tpepper have to approve cherry pick)

**Pull request merged**
