### PR TITLE
Fix imagePullSecrets in ServiceAccount lack of patchStrategy

### LINKED ISSUE #72475: Missing/inconsistent merge patch strategy for ServiceAccount imagePullSecrets
The `imagePullSecrets` array on `ServiceAccounts` does not specify a patch strategy of 'merge', so when you try to 'stategic' or 'merge' patch in a new Secret name, any existing Secret names all get removed/replaced. It seems like a merge patch strategy would be appropriate for this array, and indeed the `imagePullSecrets` array for `Pods` already specifies a merge patch strategy. This seems like an oversight or bug that the `imagePullSecrets` array on `ServiceAccounts` is not handled in a consistent and appropriate manner. This is also not consistent with the `secrets` array in `ServiceAccounts` which does merge patch strategy.

**What happened**:

When you try to 'stategic' or 'merge' patch to add a new `Secret` name in the `imagePullSecrets` list on a `ServiceAccount`, and existing `Secret` name(s) get removed/replaced.

**What you expected to happen**:

I expected the `imagePullSecrets` array on `ServiceAccounts` to use a merge patch strategy consistent with `imagePullSecrets` array on `Pods` (which does specify and use a merge patch strategy), and to add the new `Secret` name to the `imagePullSecrets` array.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl patch serviceaccount default --type strategic --patch '{"imagePullSecrets":[{"name":"test1"}]}'
kubectl patch serviceaccount default --type strategic --patch '{"imagePullSecrets":[{"name":"test2"}]}'
kubectl get serviceaccount default -o yaml
````
Note that 'test2' has replaced 'test1', rather than being merged into the `imagePullSecrets` list.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
- name: test2
secrets:
-name: default-token-abcde
```
**Anything else we need to know?**:

`imagePullSecrets` in a `PodSpec` is configured and behaves as expected, merging new secret names into the list.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#podspec-v1-core
```
imagePullSecrets
LocalObjectReference array
patch strategy: merge
patch merge key: name
```

In contrast `imagePullSecrets` in a `ServiceAccount` is missing this behavior/specification

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#serviceaccount-v1-core
```
imagePullSecrets
LocalObjectReference array
```

Yet the `secrets` array in a `ServiceAccount` does have a merge strategy.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#serviceaccount-v1-core
```
secrets
ObjectReference array
patch strategy: merge
patch merge key: name
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): GCE COS
- Kernel (e.g. `uname -a`): GCE COS (Linux 4.14.65+ #1 SMP Thu Oct 25 10:42:50 PDT 2018 x86_64) GNU/Linux
- Install tools: GCE
- Others: N/A

/kind bug

### PR DESCRIPTION
**Pull request by tossmilestone**
Signed-off-by: He Xiaoxi <xxhe@alauda.io>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix imagePullSecrets in ServiceAccount lack of patchStrategy

**Which issue(s) this PR fixes**:

Fixes #72475 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix imagePullSecrets in ServiceAccount lack of patchStrategy.
```

### CODE REVIEW

**Comment by liggitt** [comment]
unfortunately, changing the merge patch strategy is not backwards compatible with existing API usage. this cannot be changed in v1

/close

**Comment by surajssd** [comment]
@liggitt 

>unfortunately, changing the merge patch strategy is not backwards compatible with existing API usage. this cannot be changed in v1

Is this documented somewhere that this is a gotcha and be aware of it? In the docs is https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/ or https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ the right place to update it? because it talks a great length about various merge strategies.

**Comment by liggitt** [comment]
> Is this documented somewhere that this is a gotcha and be aware of it? In the docs is https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/ or https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ the right place to update it? because it talks a great length about various merge strategies.

that doc has the following note:

> Note: Which of the above strategies is chosen for a given field is controlled by the patchStrategy tag in types.go If no patchStrategy is specified for a field of type list, then the list is replaced.

**Pull request closed without merging**
