### PR TITLE
Fix kubectl apply skew test with extra properties

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Corrects one of the kubectl apply skew tests. See https://testgrid.k8s.io/sig-cli-master#skew-cluster-latest-kubectl-stable1-gce&width=5

**Special notes for your reviewer**:
* Fixes a bug in the test that was not setting up the test CRDs correctly
* Fixes a bug in the "arbitrary properties" skew test that expected success even when passing bogus data with a published schema

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @sttts @roycaihw 
/sig cli
/sig api-machinery
/priority critical-urgent
/milestone v1.15

### CODE REVIEW

**Comment by roycaihw** [comment]
SGTM. Reading the code now

the thing that concerns me the most is that this should not just fail for version-skew test (old kubectl). I'm not aware of any related change in 1.15 kubectl, so I'd expect new kubectl to fail as well, but we aren't getting release-blocking signal from CI.

(off-topic: this reminds me of the cleanup item in https://github.com/kubernetes/kubernetes/issues/74976. We haven't moved the `schemaFoo`s to a util package yet. Currently the `schemaFoo`s haven't differed yet)

**Comment by liggitt** [comment]
> the thing that concerns me the most is that this should not just fail for version-skew test (old kubectl). I'm not aware of any related change in 1.15 kubectl, so I'd expect new kubectl to fail as well, but we aren't getting release-blocking signal from CI.

that's because this test incorrectly changed to not assign the schema to the CRD in the CreateTestCRD functions (also fixed in this PR). with the correct schemas in the CRDs, the test failed as expected.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/74931 flake
/retest

**Comment by liggitt** [comment]
flaked on https://github.com/kubernetes/kubernetes/issues/78776

/retest

**Pull request merged**
