### PR TITLE
minor fix type missing

### PR DESCRIPTION
**Pull request by wenjun93**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by jianhuiz — APPROVED** [review]

**Comment by wenjun93** [comment]
@saad-ali

**Comment by wenjun93** [comment]
@smarterclayton

**Pull request merged**
