### PR TITLE
NetworkPolicy e2e: use ClientSet and update to CoreV1 and NetworkingV1 apis.

### PR DESCRIPTION
**Pull request by bcreane**
**What this PR does / why we need it**:
Update NetworkPolicy e2e test: use the public ClientSet and update to CoreV1 and NetworkingV1 apis.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bcreane** [comment]
cc: @nikhiljindal

**Comment by bcreane** [comment]
Hi @dcbw, can you take a look? 
/assign @dcbw

**Comment by cmluciano** [comment]
Should this wait until v1 is the default and the extensions code is removed for 1.10?

**Comment by bcreane** [comment]
Hi @cmluciano - at a minimum, I'd like to get rid of `InternalClientset` and replace with `ClientSet`. I can back out the api updates (`NetworkPolicyV1` and `CoreV1`) if we think we want to continue to test against the deprecated apis. WDYT?

**Comment by cmluciano** [comment]
s/InternalClientSet/ClientSet sounds reasonable to me. My only reason for a potential halt on the latter is for https://github.com/kubernetes/kubernetes/pull/51955 to merge. TBH though, both apis have the same types, so I suppose it shouldn't matter anyway.

**Comment by bcreane** [comment]
These all look like flakes - mostly unable to pull docker images. Going to retry the simplest:
/test pull-kubernetes-verify

**Comment by bcreane** [comment]
@cmluciano - it looks like linking against `"k8s.io/api/networking/v1"` fails w/K8s checks (works locally). I'm curious if you have any insight into whether there's a separate change, e.g. build change, to get this working?

**Comment by cmluciano** [comment]
I'll try to replicate this locally.

**Comment by cmluciano** [comment]
@bcreane Running `./hack/update-bazel.sh` updates the build file locally. That should fix some of the failing jobs.

**Comment by bcreane** [comment]
@cmluciano - very nice, thanks for the information. looks like builds have succeeded!

**Comment by cmluciano** [comment]
awesome, can you please squash the commits "reorder import" and "move import" into your first commit?

**Comment by bcreane** [comment]
@cmluciano - done.

**Comment by cmluciano** [comment]
this LGTM, @caseydavenport anymore comments?

**Comment by caseydavenport** [comment]
This LGTM - thanks @bcreane and @cmluciano!

/lgtm
/approve no-issue

**Pull request merged**
