### PR TITLE
Fix shellcheck failures in test-dockerized.sh and upload-to-gcs.sh

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref: https://github.com/kubernetes/kubernetes/pull/75912

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
/assign @BenTheElder  @spiffxp 
because #75912 caused confusion, I had to close it and open the new #76121

**Comment by SataQiu** [comment]
thanks @xichengliudui 
/priority important-soon
/sig testing
LGTM

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Review by BenTheElder — APPROVED** [review]
/approve

**Comment by BenTheElder** [comment]
@xichengliudui needs a rebase for `hack/.shellcheck_failures`

**Comment by xichengliudui** [comment]
I checked all the pr about shellcheck. nobody modified the same content as me in `hack/.shellcheck_failures` file.

**Comment by BenTheElder** [comment]
@xichengliudui please do a `git fetch upstream && git rebase upstream/master`, we won't be able to merge until you rebase:
image

**Pull request closed without merging**
