### PR TITLE
Add an e2e test suite for multi-zone GKE clusters.

### PR DESCRIPTION
**Pull request by a-robinson**
Plus environment variable support for creating multi-zone GKE clusters.

@jlowdermilk @spxtr @quinton-hoole 

This can't be submitted quite yet since the new gcloud build isn't ready. Jeff, can you help me figure out how to determine when it is?

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM.  @a-robinson Feel free to add LGTM label when the gcloud build on which it depends is ready.

**Comment by a-robinson** [comment]
@k8s-oncall any qualms about manually merging to get this new e2e test running? It's a non-critical build so won't affect the submit queue, and I'd like to get some mileage on it ASAP. I'll babysit its results for a while to make sure it's working.

**Comment by a-robinson** [comment]
@k8s-bot e2e test this please: #19997

**Comment by a-robinson** [comment]
@k8s-bot test this issue: #19997

**Pull request merged**
