### PR TITLE
kernel_validator: amend kernel config check paths

### PR DESCRIPTION
**Pull request by mythi**
**What this PR does / why we need it**:
Clear Linux Project for Intel Architecture uses its own path
to store kernel build artifacts. This PR amends the path to kernel validator's 
config check paths.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```
e2e_node:  add new kernel config check paths
```

### CODE REVIEW

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60791)

**Comment by derekwaynecarr** [comment]
i have no objection to the change, but i think you will need to get cla bot happy for this to merge.

**Comment by mythi** [comment]
@derekwaynecarr I'm working with LF to fix the CLA issue.

**Comment by mythi** [comment]
(my CLA is OK but the check fails for some reason)

**Comment by xiangpengzhao** [comment]
/ok-to-test
It's strange that the CLA check is still failing...

**Comment by mythi** [comment]
@xiangpengzhao yes, very strange and I'm already getting frustrated.

**Comment by mythi** [comment]
test comment (per LF request to get the cla plugin triggered)

(ignore please)

**Comment by mythi** [comment]
rebased + re-pushed to get the tests triggered

**Comment by BenTheElder** [comment]
looks like `cla/linuxfoundation` is still giving us issues :(

**Comment by BenTheElder** [comment]
FWIW I checked out this and https://github.com/kubernetes/kubernetes/pull/60304 from GitHub and I see your public @intel.com email on your commit in both. I would expect `cla/linuxfoundation` to be working... :/

**Comment by mythi** [comment]
@BenTheElder Thanks for your help with this!

**Comment by mythi** [comment]
test comment (per LF request to get the cla plugin triggered)

(ignore please)

**Comment by mythi** [comment]
@derekwaynecarr is this OK to you now?

**Comment by mythi** [comment]
/assign derekwaynecarr

ready for 1.11?

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
