### PR TITLE
TopologyAwareHints: fix getHintsByZone bug

### PR DESCRIPTION
**Pull request by llhuii**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Fixes a bug that could result in the EndpointSlice controller unnecessarily updating EndpointSlices associated with a Service that had Topology Aware Hints enabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
@llhuii thanks for catching this! Do you mind adding a release note/user-facing change text? If I'm understanding the impact correctly, I think it could be something like this:

```
Fixes a bug that could result in the EndpointSlice controller unnecessarily updating EndpointSlices associated with a Service that had Topology Aware Hints enabled.
```

**Comment by llhuii** [comment]
> @llhuii thanks for catching this! Do you mind adding a release note/user-facing change text? If I'm understanding the impact correctly, I think it could be something like this:
> 
> ```
> Fixes a bug that could result in the EndpointSlice controller unnecessarily updating EndpointSlices associated with a Service that had Topology Aware Hints enabled.
> ```

Done, I have also added this information to the commit message.

**Comment by llhuii** [comment]
> @llhuii: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-integration	[528cd30](https://github.com/kubernetes/kubernetes/commit/528cd3014544c9ae7f97fa5315fe10f069e57f48)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105267/pull-kubernetes-integration/1442657091704590336)	true	`/test pull-kubernetes-integration`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=105267). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Allhuii). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

/retest-required
Many "resource quota evaluation timed out" errors:
```json
{"Time":"2021-09-28T01:35:34.691341433Z","Action":"output","Package":"k8s.io/kubernetes/test/integration/quota","Test":"TestQuota","Output":"ome/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x46b\\nnet/http.HandlerFunc.ServeHTTP(0x4df48c0, {0x7f46546bd7a0, 0xc0087574e8}, 0xc003e023c0)\\n\\t/usr/local/go/src/net/http/server.go:2046 +0x2f\\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1()\\n\\t/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x99\\ncreated by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\\n\\t/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:94 +0x2d1\\n\" addedInfo=\"\\nlogging error output: \\\"{\\\\\\\"kind\\\\\\\":\\\\\\\"Status\\\\\\\",\\\\\\\"apiVersion\\\\\\\":\\\\\\\"v1\\\\\\\",\\\\\\\"metadata\\\\\\\":{},\\\\\\\"status\\\\\\\":\\\\\\\"Failure\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"Internal error occurred: resource quota evaluation timed out\\\\\\\",\\\\\\\"reason\\\\\\\""}
```

**Comment by robscott** [comment]
The actual code for this LGTM, do you mind adding some test cases that would catch this so we don't end up with a similar mistake in the future?

**Comment by llhuii** [comment]
OK
/hold

**Comment by llhuii** [comment]
@robscott some tests are added for `getHintsByZone`, PTAL.

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
