### PR TITLE
staing/apimachinery: replace json.NewEncoder to jsoniter

### PR DESCRIPTION
**Pull request by denverdino**
Signed-off-by: Li Yi <denverdino@gmail.com>

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

In a large cluster, we found the high CPU consumption on the 
"k8s.io/apimachinery/pkg/runtime/serializer/json/Encode" impl for JSON output

I replace the json.NewEncoder to caseSensitiveJsonIterator.NewEncoder for better performance 

**Which issue(s) this PR fixes** 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Comment by nikhita** [comment]
Makes sense to me.

> I replace the json.NewEncoder to caseSensitiveJsonIterator.NewEncoder for better performance

For the record, benchmark tests for this exist [here](https://github.com/kubernetes/kubernetes/blob/8307fb2fb3ddd48cd8447e54978166f0c1123583/pkg/api/testing/serialization_test.go#L587-L613).

/release-note-none
/kind bug
/priority important-longterm
/ok-to-test

/assign @liggitt

**Comment by roycaihw** [comment]
@nikhita Sounds good. I wonder if it's okay for us to change every `json.NewEncoder` to `caseSensitiveJsonIterator.NewEncoder` or `jsoniter.ConfigCompatibleWithStandardLibrary.NewEncoder` in our code base. 

Found a similar PR https://github.com/kubernetes/kubernetes/pull/63242 which claimed to have incompatibility issue.

/cc @wojtek-t

**Comment by denverdino** [comment]
In the ```func (s *Serializer) Encode(obj runtime.Object, w io.Writer) error```, it is already using the caseSensitiveJsonIterator for JSON/YAML serializing and pretty print, but not for default JSON encoding.

**Comment by wojtek-t** [comment]
@roycaihw @denverdino - yes, there are still some incompatibilities (it seems upgrade of the dependency doesn't fix all of them). Once tests are passing, I'm fine with this PR.

**Comment by smarterclayton** [comment]
Before this PR gets merged I want to see before and after memory allocation profiles with

```
go test ./vendor/k8s.io/apiserver/pkg/endpoints/ -test.bench='Benchmark(Get|WatchHTTP)' -test.run=XXX -benchmem -test.memprofile=/tmp/mem2 -test.benchtime 5s
```

In casual testing this was a 2x regression in memory allocations during watch.

**Comment by liggitt** [comment]
/hold
until https://github.com/kubernetes/kubernetes/pull/70574#issuecomment-476370725 is resolved

**Pull request closed without merging**
