### PR TITLE
e2e: minor changes to network/service testing utils

### PR DESCRIPTION
**Pull request by yujuhong**
Add more logging to help debug. Also refactor several functions to improve
reusability.

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks!

/lgtm

**Comment by yujuhong** [comment]
/assign @bowei 
for approval

**Comment by yujuhong** [comment]
@spiffxp no test/OWNERS (except you) approved the PR yet. Feel free to remove your "approved" label if you'd like

**Pull request merged**
