### PR TITLE
Change default value of deleting-pods-burst to 1

### PR DESCRIPTION
**Pull request by gmarek**
Fix. #27413

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

Thanks!

**Comment by piosz** [comment]
This PR probably broke gce-serial and gce-serail suites. Both fail with:
```
[k8s.io] DaemonRestart [Disruptive] Kubelet should not restart containers across restart
```
Reverting it.

**Comment by gmarek** [comment]
I'm investigating. I found a problem with graceful deletion of Pods on a Kubelet side (run 1500):
```
...
I0615 21:20:04.025942   10821 kubelet.go:2516] SyncLoop (UPDATE, "api"): "daemonrestart10-b1b0f766-3335-11e6-8a92-0242ac110002-g4icu_e2e-tests-daemonrestart-u5hdb(6636171a-333e-11e6-9d07-42010af00002):DeletionTimestamp=2016-06-15T21:20:34Z"
...
I0615 21:20:12.560890   10821 kubelet.go:2516] SyncLoop (UPDATE, "api"): "daemonrestart10-b1b0f766-3335-11e6-8a92-0242ac110002-g4icu_e2e-tests-daemonrestart-u5hdb(6636171a-333e-11e6-9d07-42010af00002):DeletionTimestamp=2016-06-15T21:20:42Z"
...
```

I.e. deletion timestamp is updated in every "step". Those logs seem correlated with DELETE calls from namespacecontroller:
```
...
I0615 21:20:04.054745       5 handlers.go:165] DELETE /api/v1/namespaces/e2e-tests-daemonrestart-u5hdb/pods: (11.206196ms) 200 [[kube-controller-manager/v1.4.0 (linux/amd64) kubernetes/6209b1b/namespace-controller] 127.0.0.1:60266]
...
I0615 21:20:12.586205       5 handlers.go:165] DELETE /api/v1/namespaces/e2e-tests-daemonrestart-u5hdb/pods: (53.886941ms) 200 [[kube-controller-manager/v1.4.0 (linux/amd64) kubernetes/6209b1b/namespace-controller] 127.0.0.1:60358]
```

I have no idea how default value bump might cause something like this. I suspect another PR that was merged in that time: #26801 @saad-ali @caesarxuchao @yujuhong

**Comment by gmarek** [comment]
I still don't know why this change might have this effect, but I found a problem with graceful deletion code (I'll send a fix in a sec), that should solve this particular problem. It's kind of strange that it didn't bit us earlier.

The problem itself appeared now because for some reason pods we scheduled didn't finish when received SIGTERM from Kubelet. It earlier runs all daemons were deleted quickly, so there were no SIGKILLs required. Now pods refuse to die (which I think is regression - possibly caused by #26801) - @saad-ali to verify - and the bug in graceful deletion logic prevented Kubelet from issueing SIGKILL.

**Comment by yujuhong** [comment]
Without reading the details, the daemonrestart test is failing because of the new behavior introduced by #26801. The explanations are in the comments of https://github.com/kubernetes/kubernetes/issues/26290

**Comment by wojtek-t** [comment]
We should revert that PR then to unblock submit-queue.
@lavalamp @k8s-oncall ^^

**Pull request merged**
