### PR TITLE
Bump github.com/mitchellh/mapstructure

### PR DESCRIPTION
**Pull request by hiyosi**
**What this PR does / why we need it**:

This PR bump revision of github.com/mitchellh/mapstructure.
The library is required by Gophercloud, also they has passed tests with the newer revision.
So, since Gophercloud is update, please also renew this library.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jbeda** [comment]
@k8s-bot ok to test

**Comment by jbeda** [comment]
@hiyosi -- I don't think this does what you think it does.  You need to actually bring the new code in. See https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md.

**Comment by hiyosi** [comment]
@jbeda I'm sorry for my mistake. I've retried it.

**Comment by dims** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
