### PR TITLE
Add myself to client-go reviewers

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Given the ongoing work on generifying client-go, it might make sense for me to be a reviewer (at least to keep better track of changes being made before they go in).

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by skitt** [comment]
This was prompted by https://github.com/kubernetes/kubernetes/pull/125314 which I completely missed!

**Comment by aojea** [comment]
/lgtm

 Stephen has authored all the generification of client-go  and having more reviewers is always good IMHO

**Pull request merged**
