### PR TITLE
Pin kube-openapi vendor to 30be4d16710a

### PR DESCRIPTION
**Pull request by yue9944882**
this will fix the failing test in https://github.com/kubernetes/kubernetes/pull/84708

/sig api-machinery
/cc @sttts @apelisse 

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
weird, I'm a dep approver, I should be able to approve this ...

**Comment by apelisse** [comment]
@BenTheElder am I missing something?

**Comment by liggitt** [comment]
> @BenTheElder am I missing something?

dep-approvers doesn't cover the go.mod file in the root :-/

/approve

**Pull request merged**
