### PR TITLE
bump(github.com/docker/spdystream): 449fdfce4d962303d702fec724ef0ad181c92528

### PR DESCRIPTION
**Pull request by ncdc**
Ref #19014

### CODE REVIEW

**Comment by ncdc** [comment]
cc @yujuhong FYI this, along with #22802 should hopefully resolve the goroutine leaks related to spdystream in #19014

**Comment by ncdc** [comment]
@liggitt care to review?

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by lavalamp** [comment]
LGTM, is there a test for this behavior in the dependency?

**Comment by ncdc** [comment]
Yes, there is a test - see the most recent merged pull there.

**Comment by ixdy** [comment]
@k8s-bot unit test this please, issue #22834

**Comment by ixdy** [comment]
@k8s-bot unit test this, issue #22843

**Comment by eparis** [comment]
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.

**Pull request merged**
