### PR TITLE
 /cluster: remove juju

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

/kind cleanup
/priority backlog

Juju changed home and was cleaned up in 422a7ec49.
Remove the "provider" leftover in /cluster/juju and entries in .gitignore.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/sig instrumentation
?

**Comment by BenTheElder** [comment]
/approve
for cluster/
/lgtm

**Pull request merged**
