### PR TITLE
Fix: Correct spelling mistakes in cmd/kubeadm/app/cmd/phases/workflow/runner_test.go

### PR DESCRIPTION
**Pull request by wppzxc**
…/runner_test.go

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Correct a spelling mistakes.
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wppzxc** [comment]
/cc @fabriziopandini @neolit123 @SataQiu @pacoxu @RA489
Please reivew the PR, thanks!

**Comment by pacoxu** [comment]
/priority backlog
/lgtm
/triage accepted
/release-note-none

https://github.com/kubernetes/community/blob/01647f33e3525516613cd0acf1f428ab2b4d826a/contributors/guide/pull-requests.md?plain=1#L509-L525

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
