### PR TITLE
fix race of podRecords during different relist period

### LINKED ISSUE #88779: Panic in kubelet Run does not exit, creates multiple parallel Run goroutines
If the kubelet Run method panics (e.g. https://github.com/kubernetes/kubernetes/pull/88915)  Run gets called multiple times:

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/server.go#L1131-L1134

That would start multiple goroutines calling relist() concurrently

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/kubelet.go#L1450-L1451

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/pleg/generic.go#L129-L132

From a PR that doesn't touch the PLEG (but might stress it?), panic in kubelet from pleg:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-kind/1234952132935815168

```
Mar 03 19:21:03 kind-worker2 kubelet[88624]: fatal error: concurrent map read and map write
Mar 03 19:21:03 kind-worker2 kubelet[88624]: goroutine 1420 [running]:
Mar 03 19:21:03 kind-worker2 kubelet[88624]: runtime.throw(0x43641ed, 0x21)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc0011f57e8 sp=0xc0011f57b8 pc=0x432682
Mar 03 19:21:03 kind-worker2 kubelet[88624]: runtime.mapaccess2_faststr(0x3ddf9e0, 0xc000706690, 0xc00084f1a0, 0x24, 0xc0004b93c8, 0x1)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         GOROOT/src/runtime/map_faststr.go:116 +0x48f fp=0xc0011f5858 sp=0xc0011f57e8 pc=0x4160cf
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.podRecords.setCurrent(0xc000706690, 0xc001e44600, 0x1d, 0x20)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:464 +0x149 fp=0xc0011f5910 sp=0xc0011f5858 pc=0x3318999
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:214 +0x2c9 fp=0xc0011f5e20 sp=0xc0011f5910 pc=0x3316a89
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist-fm()
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:190 +0x2a fp=0xc0011f5e38 sp=0xc0011f5e20 pc=0x3318cca
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00016fbc0
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-kind/1234916134344462336/artifacts/logs/kind-worker2/kubelet.log

### PR DESCRIPTION
**Pull request by gongguan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes [#88779](https://github.com/kubernetes/kubernetes/issues/88779)

**Special notes for your reviewer**:
fix race of podRecords during different relist period
**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sjenning** [comment]
I think this would fix it but I can't figure out how a concurrent `relist()` even happens :confused: I'll like to figure that out before we just throw a lock around this.

**Comment by sjenning** [comment]
#88779 has been changed to reflect the real issue; the panic recovery logic results in the kubelet calling `Run()` twice, resulting in concurrent execution of non thread safe functions (like this one).  Honestly, I'm surprised that it hasn't caused more issues than this.

**Comment by gongguan** [comment]
> #88779 has been changed to reflect the real issue; the panic recovery logic results in the kubelet calling `Run()` twice, resulting in concurrent execution of non thread safe functions (like this one). Honestly, I'm surprised that it hasn't caused more issues than this.

You're right. it's not root issue.

**Comment by gongguan** [comment]
@sjenning stupid question, if kubelet.Run only called once, will this concurrent write/read occurred between different relist period?

**Comment by sjenning** [comment]
Not that I can see.  There is only one start of the `GenericPLEG` and the `relist` is called by `wait.Until()` with a one second period.

**Pull request closed without merging**
