### PR TITLE
Fail test-cmd when failure occurs

### LINKED ISSUE #39168: kubectl tests pass even if a command failed
kubectl tests seem to be passing even if a command fails.

Debug and fix this.

cc @janetkuo

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #39168.

@nikhiljindal, @ymqytw or @janetkuo ptal

### CODE REVIEW

**Comment by pwittrock** [comment]
@k8s-bot unit test this

**Comment by nikhiljindal** [comment]
Thanks for the PR @soltysh!

* I am not sure why is that `FAIL!` coming up in the output. We should fix it.
* How about checking for the exit code of runTests method? I see that we dont always print "FAIL!", but we seem to be using `exit 1` everywhere, example: https://github.com/kubernetes/kubernetes/blob/e827393fa2335cc7ed89043e7f26ef9b32fc71a9/hack/make-rules/test-cmd-util.sh#L1034
* We need to make the same change in `hack/make-rules/test-federation-cmd.sh`

**Comment by soltysh** [comment]
I've managed to find one problem that is causing all these failures. We can't enable this until #39666 is resolved. I'll try to apply your suggestions.

**Comment by soltysh** [comment]
> I am not sure why is that FAIL! coming up in the output. We should fix it.

It's coming from [if_has_string](https://github.com/kubernetes/kubernetes/blob/e827393fa2335cc7ed89043e7f26ef9b32fc71a9/hack/lib/test.sh#L224)

**Comment by soltysh** [comment]
> How about checking for the exit code of runTests method? I see that we dont always print "FAIL!", but we seem to be using exit 1 everywhere, example: https://github.com/kubernetes/kubernetes/blob/e827393fa2335cc7ed89043e7f26ef9b32fc71a9/hack/make-rules/test-cmd-util.sh#L1034

Funny you mention that line, which I just removed 😉 Generally we'd have to get exit code from every command and bubble it up to `runTests`, for example a couple lines before what you've mentioned, [here](https://github.com/kubernetes/kubernetes/blob/e827393fa2335cc7ed89043e7f26ef9b32fc71a9/hack/make-rules/test-cmd-util.sh#L1029) might fail but we're not getting the output from there. The reason I went with `FAIL!` is that in majority of tests we are using `if_has_string` which prints that. The best we could do is have some global variable being set on every failure, that will probably require least effort. I need to check how ours (openshift's) test-cmd is doing that.

**Comment by soltysh** [comment]
Openshift fails test-cmd as soon as it encounters an error, that might be the simplest approach, @nikhiljindal wdyt?

**Comment by nikhiljindal** [comment]
yes failing as soon as there is an error sgtm.

**Comment by kargakis** [comment]
@soltysh I can't see the failure you are talking about in https://github.com/kubernetes/kubernetes/issues/39666 anywhere in the logs in this PR. Also I tried to reproduce that failure (manually admittedly, didn't run test-cmd) and didn't come across any error... Will look deeper tomorrow.

**Comment by kargakis** [comment]
@k8s-bot unit test this https://github.com/kubernetes/kubernetes/issues/39604

**Comment by soltysh** [comment]
@kargakis I've executed manually those tests and was able to reproduce it locally easily, last time I checked. Let's sync tomorrow about it.

**Comment by nikhiljindal** [comment]
@soltysh Any update?

**Comment by soltysh** [comment]
@nikhiljindal haven't got a chance to look back into it, last time I checked I was blocked by the deployment reaper, although @kargakis checked and it worked for him. I'm planning to re-visit this later this week.

**Pull request closed without merging**
