### PR TITLE
kubelet e2e: run resource monitor only if the actual number of nodes is small

### LINKED ISSUE #83316: [k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness
**Which test(s) are failing**:

[k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.
**Since when has it been failing**:
2019-09-26
**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1177191542352252931

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet.go:308
Sep 29 12:41:34.198: Unexpected error:
    <*errors.errorString | 0xc0000af060>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet.go:321
```
**Anything else we need to know**:

/cc @kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by roycaihw**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix a regression in test config. Resource monitor wasn't supposed to run against large cluster. When it does, it causes the test client to be throttled and timeout. 

**Which issue(s) this PR fixes**:

Fixes #83316

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @cheftako @yujuhong

### CODE REVIEW

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by roycaihw** [comment]
/assign @yujuhong @Random-Liu 
for approval

**Comment by yujuhong** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
