### PR TITLE
Delete kube_features when in 1.30.

### PR DESCRIPTION
**Pull request by yanggangtony**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
All contents of the pr have been removed from master branch.

**Comment by yanggangtony** [comment]
> All contents of the pr have been removed from master branch.

Yes, thanks. closed.

**Pull request closed without merging**
