### PR TITLE
[GCE] VolumeNode nil check

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
specMode is of type VolumeMode * in struct PersistentVolumeSpec (pkg/apis/core/types.go:306) . The correct pointer check is if specMode == nil.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
N/A
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
@neolit123 let me know if anything needed from my side otherwise, can we merge this ? Thanks.

**Comment by neolit123** [comment]
hi, the PR needs review and approval from the maintainers.

/assign @davidz627

**Comment by gaurav1086** [comment]
Thank you @neolit123

**Comment by gaurav1086** [comment]
@davidz627 @neolit123 can we merge this ? Thank you.

**Comment by neolit123** [comment]
@gaurav1086 please try asking in the #sig-storage channel on k8s slack if the PR is not getting review.
thanks

/assign @saad-ali

**Pull request merged**
