### PR TITLE
Update v1.17.0 CHANGELOG to match final draft

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

We merged the final draft too late that our automatism was not able to pick up the right release notes. We now fix this manually with this PR.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Wow, that's a lot more changes than I thought I was going to see.

**Comment by sftim** [comment]
I think:
/priority critical-urgent

**Comment by justaugustus** [comment]
Release Manager approval:
/lgtm
/approve

**Pull request merged**
