### PR TITLE
Protect against nil panic in apply

### PR DESCRIPTION
**Pull request by fabianofranz**
**What this PR does / why we need it**: `kubectl apply` has a potential panic (actually verified in OpenShift in https://github.com/openshift/origin/issues/15017) where a `patcher` calls the `runDelete` function with a nil `resource.RESTClient`, but under some conditions the client is required by that function.

**Release note**:

```release-note
NONE
```

@pwittrock @kubernetes/sig-cli-bugs

### CODE REVIEW

**Comment by liggitt** [comment]
I'd like to see a test that exercises this usage to prevent future regression

**Comment by fabianofranz** [comment]
> I'd like to see a test that exercises this usage to prevent future regression
 
Done, @liggitt PTAL.

**Pull request merged**
