### PR TITLE
test/e2e/framework: remove dependencies to internal APIs

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: andrewsykim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Part of moving the e2e framework to staging (https://github.com/kubernetes/kubernetes/issues/74352).
**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes/kubernetes/issues/74352

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
Oops, I meant to put a hold on this til I got a review from @alejandrox1, pleaes review when you get a chance please

**Comment by tanjunchen** [comment]
oo sorry
/cc @alejandrox1
PLAT

**Pull request merged**
