### PR TITLE
Remove the `host` label from the kubelet http traffic metrics

### LINKED ISSUE #75060: Add monitoring and throttling into kubelet http server
**What would you like to be added**:
1) add metrics into kubelet to monitor [kubelet http server](https://github.com/kubernetes/kubernetes/blob/e330c0120eed4871d518522b3f5c049c36a92464/pkg/kubelet/server/server.go#L83);
2) add throttling to [kubelet http server](https://github.com/kubernetes/kubernetes/blob/e330c0120eed4871d518522b3f5c049c36a92464/pkg/kubelet/server/server.go#L83). 

**Why is this needed**:
Kubelet provides lots of its functionalities through its http server, and currently there is no server-side monitoring and throttling mechanisms. 
Adding metrics into kubelet to monitor its http server will improve its observability and debuggability; adding throttling will prevent kubelet being overloaded from serving too many http requests.

### PR DESCRIPTION
**Pull request by haiyanmeng**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
All the http requests coming into kubelet should have the same `host` info. Therefore, it is not very useful to have the `host` label here.

**Which issue(s) this PR fixes**:

None.

**Special notes for your reviewer**:
The metrics were added in https://github.com/kubernetes/kubernetes/pull/75228.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Thank you for your work on this :)

I'm 99% sure the answer to this question is yes, but just want to confirm that Prometheus will still have some way for us to determine which hosts these metrics come from, even though we are removing the specific `host` label?

Additionally, as a small nit, it feels a little confusing that your PR description describes this as "Fixing 75060". It definitely seems related, but doesn't seem to me to actually address the original goal of that issue.

**Comment by loburm** [comment]
@mattjmcnaughton Prometheus Server is responsible for collecting metadata for node/pod/container. Hostname is a part of node metadata.

**Pull request merged**
