### PR TITLE
fix kubemark, juju, and libvirt-coreos README (from minions to nodes)

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**:
This PR will fix old name(minison) to new name(node) in kubemark README.md.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by nikhita** [comment]
I also notice that the word `minion` is used in https://github.com/kubernetes/kubernetes/blob/master/cluster/libvirt-coreos/README.md and https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/bundles/README.md too.

Can you fix them in this PR too? Thanks!

**Comment by shun-miyoshi-com** [comment]
I added @nikhita suggestion.

**Comment by nikhita** [comment]
@shun-miyoshi-com Can you squash the commits to a single commit? Thanks!

**Comment by shyamjvs** [comment]
@shun-miyoshi-com Could you change the PR title to reflect changes at other places too?

**Comment by shun-miyoshi-com** [comment]
Any task what I should do?

**Comment by shyamjvs** [comment]
@wojtek-t  Could you please approve this PR?

**Pull request merged**
