### PR TITLE
Node network health check utility - performs a quick HTTP GET test

### PR DESCRIPTION
**Pull request by girishkalele**

### CODE REVIEW

**Comment by girishkalele** [comment]
Utility to help diagnosis of nodes with unhealthy download speeds from GCS #26626

**Comment by dchen1107** [comment]
LGTM overall. But can we move this to contrib or node-problem-detector repository? Then we need to change our test infrastructure to make sure this one is the first one to run before any other pods running?

**Comment by girishkalele** [comment]
Ok, makes sense to move to node-problem-detector repository.

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-node

**Comment by Random-Liu** [comment]
@dchen1107 @girishkalele Nice to have this!
Is it possible to generalize this in the future to be a simple network health condition check daemon? Maybe just periodically (every 5 or 10 minutes) test bandwidth with some predefined URLs.

**Comment by girishkalele** [comment]
It is currently designed as a scriptable building block - returns non-zero exit code to indicate a slow network. We can add switches to make it a daemon and return status via other methods.
Is there a format API for a node-problem-detector sub-daemon to report node conditions ?

**Comment by Random-Liu** [comment]
@girishkalele The interface is [here](https://github.com/kubernetes/node-problem-detector/blob/master/pkg/types/types.go).
For 1.3, the only problem daemon in node problem detector is [kernel monitor](https://github.com/kubernetes/node-problem-detector/tree/master/pkg/kernelmonitor), it just report `Status` to problem detector via channel.

After 1.3, we may want to separate problem daemons and node problem detector into different containers, and expose the interface from node problem detector.

**Comment by Random-Liu** [comment]
@girishkalele @dchen1107  Just address that this is only discussing about the future, not now. :)

**Pull request closed without merging**
