### PR TITLE
Enable model API in Heapster

### PR DESCRIPTION
**Pull request by mwielgus**
see: https://github.com/GoogleCloudPlatform/heapster/issues/463#issuecomment-129635265

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @piosz  @jszczepkowski @afein

**Comment by vishh** [comment]
@afein is working on optimizing memory usage for the model. Can we hold off from enabling the model until then (a few more days)? Enabling model now will result in significant memory usage.

**Comment by afein** [comment]
That is correct, when the memory usage is optimized (2 days ETA), the use_model flag should be set to true by default on Heapster, without requiring it to be set explicitly.

**Comment by wojtek-t** [comment]
>
That is correct, when the memory usage is optimized (2 days ETA), the use_model flag should be set to true by default on Heapster, without requiring it to be set explicitly.

Should we close this PR then?

**Comment by vishh** [comment]
Yes. Lets close this.

**Pull request closed without merging**
