### PR TITLE
Start harmonizing AWS kube-up with GCE scripts

### PR DESCRIPTION
**Pull request by justinsb**
The GCE kube-up scripts offer some functionality that the AWS kube-up scripts do not; including kube-push & in-place upgrade.  This PR therefore starts the process of sharing the approach and the code of GCE.  GCE creates a yaml config file which is stored in a separate metadata entry; we can't do that in AWS but we instead create the file inline in the script.

This will also help us with our file size, as I plan on subsequently inserting all these values into the salt grains.

### CODE REVIEW

**Comment by justinsb** [comment]
It's overall a bigger PR, but the individual commits are reasonably small & sensible IMHO

**Comment by justinsb** [comment]
On another branch I have AWS coming up sharing (most of) the GCE script: https://github.com/justinsb/kubernetes/tree/aws_sync_kubeup_gce_2b  All but the retries around apt-get are necessary there as well.  Just working on having that branch use the right storage driver..

**Comment by justinsb** [comment]
@k8s-bot unit test this

Flake: `Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: serviceipallocations "" cannot be updated: the provided resource version does not match`

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/d528312a99b62c9f0751fac0bab3c3fb0f950f49/kubernetes-pull-test-unit-integration/9646/

**Comment by justinsb** [comment]
@brendandburns what are your thoughts on this?  I would _really_ like to get this (and #19799) in to 1.2, because it will allow in-place upgrade, fix a bunch of smaller bugs in the provider up scripts (e.g. I've had reports that rebooting the master hangs often).  Also having AWS & GCE be much closer together makes it easier to pull fixes across, and the GCE scripts have had a lot of work which we can get "for free" in AWS now.

But rebasing is kind of hard, so if you disagree can you let me know?

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
