### PR TITLE
docs: correct container probe comments

### PR DESCRIPTION
**Pull request by sxllwx**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

More accurate annotations can help developers correctly understand the behavior of the system after LivenessProbe/StartupProbe fails. 

BTW, the descriptions of the probes in the comments and [official documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe) are closer together.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/uncc @liggitt @deads2k 

route back to david or I once the content is reviewed by sig-node reviewers

**Comment by sxllwx** [comment]
@SergeyKanzhelev PTAL thx~

**Comment by liggitt** [comment]
/remove-label api-review

once node reviewers lgtm the content, retag for approval

**Review by marquiz — COMMENTED** [review]
Looks alright to me

ping @SergeyKanzhelev

**Pull request closed without merging**
