### PR TITLE
Automated cherry pick of #35272 #37834 #37723 #37668 #37721 #37381 #37944 #37997 #37939 #37990 #37945 upstream release 1.5

### PR DESCRIPTION
**Pull request by saad-ali**
Batch cherry pick PRs #35272 #37834 #37723 #37668 #37721 #37381 #37944 #37997 #37939 #37990 #37945 from master to release-1.5 branch.

PRs #37997 and #37945 had merge conflicts that needed to be resolved (due to large PRs that merged to master but not 1.5, see this for details)

CC PR Authors: @yarntime @ixdy @mtaufen @ymqytw @derekwaynecarr @jszczepkowski @kargakis @foxish @jingxu97 @kad

### CODE REVIEW

**Comment by saad-ali** [comment]
PR #37945 is causing build issues. Looks like it has a dependency that needs to also be cherry picked. Going to close this PR and create a new one minus that PR (that one can be manually cherry picked along with its dependencies).

```
I1202 23:10:03.175] Cannot find go-bindata. Install with
I1202 23:10:03.175]   go get -u github.com/jteeuwen/go-bindata/go-bindata
W1202 23:10:03.175] ../../../../../../test/e2e/framework/gobindata_util.go:19: running "../../../hack/update-bindata.sh": exit status 5
I1202 23:10:03.175]   and make sure GOBIN is in the system PATH
I1202 23:10:03.180] Makefile.generated_files:304: recipe for target '_output/bin/deepcopy-gen' failed
W1202 23:10:03.180] make[2]: *** [_output/bin/deepcopy-gen] Error 1
I1202 23:10:03.181] Makefile:296: recipe for target 'generated_files' failed
W1202 23:10:03.181] make[1]: *** [generated_files] Error 2
I1202 23:10:03.183] Makefile:264: recipe for target 'cross' failed
W1202 23:10:03.183] make: *** [cross] Error 1
I1202 23:10:03.689] Makefile:248: recipe for target 'release' failed
W1202 23:10:03.690] make: *** [release] Error 1
I1202 23:10:03.690] process 30523 exited with code 2
E1202 23:10:03.690] FAIL: pull-kubernetes-kubemark-e2e-gce

```

**Comment by ixdy** [comment]
Yup, you are correct. I've tagged #36964 to get cherry-picked as well.

**Comment by kad** [comment]
I can confirm, cherypicking #36964 passes local build with golang 1.7.4 patch.

**Comment by saad-ali** [comment]
Closed and replaced with https://github.com/kubernetes/kubernetes/pull/38038 and https://github.com/kubernetes/kubernetes/pull/38059

**Pull request closed without merging**
