### PR TITLE
fix status in deployment_rollback response

### PR DESCRIPTION
**Pull request by lichuqiang**
**What this PR does / why we need it**:

fix status in deployment_rollback response

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#51243

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm.

@lichuqiang can you add a unit test for this to avoid potential regression?

**Comment by lichuqiang** [comment]
@xiang90 sure

**Pull request merged**
