### PR TITLE
Update cri-tools to v1.31.1

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Updated cri-tools to the latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated cri-tools to v1.31.0.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @kubernetes/sig-node-pr-reviews

**Comment by dims** [comment]
@saschagrunert do we need to land this for k8s 1.31 release?

**Comment by saschagrunert** [comment]
@dims no it can land later :+1:

**Comment by bart0sh** [comment]
@saschagrunert do we have any e2e jobs (kubeadm?) that use crictl or other tools? If we do, they should be triggered here (preferably automatically).

**Comment by saschagrunert** [comment]
> @saschagrunert do we have any e2e jobs (kubeadm?) that use crictl or other tools? If we do, they should be triggered here (preferably automatically).

kubeadm does not rely on crictl any more. We have 1 node e2e test which can be triggered I guess:

https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/test/e2e/node/crictl.go#L32-L65

This test is already triggered by https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126590/pull-kubernetes-e2e-gce/1821460845050204160

**Comment by saschagrunert** [comment]
Updated to v1.31.1.

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Review by pacoxu — APPROVED** [review]

**Pull request merged**
