### PR TITLE
Chore: Apply to use contextual logging for all loggers in statefulSet

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind cleanup
/sig apps
/assign @pohly 

#### What this PR does / why we need it:

Checking the logics in statefulSet controller and found some escaped loggers.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
I know that pkg/controller/statefulset wasn't fully converted and we had a volunteer assigned to fix that, but they haven't yet.

Can you also remove https://github.com/kubernetes/kubernetes/blob/bce37d089f1d8b8613290b0ed3c3ba0f5cddbc69/hack/logcheck.conf#L53 as part of this PR?

**Comment by kerthcet** [comment]
PTAL @pohly

**Review by pohly — APPROVED** [review]
/lgtm
/assign @soltysh

**Comment by kerthcet** [comment]
cc @kubernetes/sig-apps-leads

**Review by peng2x — APPROVED** [review]
LGTM

**Review by soltysh — APPROVED** [review]
/approve
/priority backlog

**Pull request merged**
