### PR TITLE
Bump the container vm version to the latest build.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by zmerlynn** [comment]
You beat me to it. :)

**Comment by zmerlynn** [comment]
Waiting for Jenkins.

**Comment by dchen1107** [comment]
Yeah, you beat me too. :-)

**Comment by zmerlynn** [comment]
FWIW, LGTM codewise. This passed my local tests, so hopefully the pull request builder likes it.

**Comment by zmerlynn** [comment]
cc @ArtfulCoder

**Pull request merged**
