### PR TITLE
Automated cherry pick of #44645 release 1.6

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #44645 release 1.6

### CODE REVIEW

**Comment by enisoc** [comment]
Is it ok if this waits for v1.6.3 in a few weeks? If it's critical for v1.6.2, we would have to delay the cut to tomorrow to let CI catch up.

**Comment by mikedanese** [comment]
SGTM

**Comment by enisoc** [comment]
@k8s-bot verify test this

**Pull request merged**
