### PR TITLE
Rename devicesIDs -> devices_ids to follow protobuf naming conventions

### PR DESCRIPTION
**Pull request by anguslees**
Rename `devicesIDs` field to `devices_ids`, and use a gogo-specific
option to keep the existing `DevicesIDs` golang name (otherwise it
would generate `DevicesIds`).

The protocol buffer [styleguide] says field names should use
underscore_separated_names.

Code generation tools rely on this convention to split words and
generate language-specific accessors/properties in the local style
conventions (ie: it's more than just a style convention).  For
example, the previous `devicesIDs` name caused Rust proto tools to
generate field names like `devices_i_ds` which is just weird.

[styleguide]: https://developers.google.com/protocol-buffers/docs/style#message-and-field-names

Note this doesn't affect protocol buffer / gRPC wire encoding, which
uses numeric values.

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:

I wouldn't bother, except this is not yet GA so seems a good time for even minor cleanups.

I don't think this requires a "v1beta2" bump, but I'm open to discussion:
- It doesn't affect protobuf wire encoding (peers with and without this change can communicate over gRPC just fine)
- It *does* trivially affect any (non-golang) code using this .proto, since it will likely cause the field name to change.  There isn't anything that automatically consumes this file afaik, so this would have to be explicitly copied in, and code re-generated, etc.  So that seems an acceptable time to also test/notice/rename this field too.
- It *does* affect go code that uses reflection, or go's encoding/json serialisation (see diff to generated go).  Afaik the deviceplugin API is only used over unix-socket gRPC (protobuf) and not HTTP/json or other encodings.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by anguslees** [comment]
(ping reviewers)
/remove-lifecycle rotten

**Comment by anguslees** [comment]
Seeking reviewers:
/assign RenaudWasTaken

**Comment by mrunalp** [comment]
Needs rebase

**Pull request merged**
