### PR TITLE
Update to new release of moby/ipvs

### PR DESCRIPTION
**Pull request by dims**
hack/pin-dependency.sh github.com/moby/ipvs v1.1.0

Here's what got updated:
- https://github.com/moby/ipvs/compare/v1.0.1...v1.1.0

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What this PR does / why we need it:

- go to a fixed tag for `vishvananda/netns`
- no more references to `pkg/errors`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
lgtm

**Review by pacoxu — APPROVED** [review]

**Comment by dims** [comment]
@aojea needs a `/lgtm` :)

**Pull request merged**
