### PR TITLE
Add node authorizer contention benchmark

### PR DESCRIPTION
**Pull request by liggitt**
* Makes the node authorization benchmark run in parallel
* Runs the tests a second time with a background goroutine pushing graph modifications at a rate of 100x per second (to test authorization performance with contention on the graph lock).

Graph modifications come from the informers watching objects relevant to node authorization, and only fire when a relevant change is made (for example, most node updates do not trigger a graph modification, only ones which change the node's config source configmap reference; most pod updates do not trigger a graph modification, only ones that set the pod's nodeName or uid)

The results do not indicate bottlenecks in the authorizer, even under higher-than-expected write contention.

```
$ go test ./plugin/pkg/auth/authorizer/node/ -run foo -bench 'Authorization' -benchmem -v
goos: darwin
goarch: amd64
pkg: k8s.io/kubernetes/plugin/pkg/auth/authorizer/node
BenchmarkAuthorization/allowed_node_configmap-8                                 596 ns/op   529 B/op   11 allocs/op    3000000
BenchmarkAuthorization/allowed_configmap-8                                      609 ns/op   529 B/op   11 allocs/op    3000000
BenchmarkAuthorization/allowed_secret_via_pod-8                                 586 ns/op   529 B/op   11 allocs/op    3000000
BenchmarkAuthorization/allowed_shared_secret_via_pod-8                        18202 ns/op   542 B/op   11 allocs/op     100000
BenchmarkAuthorization/disallowed_node_configmap-8                              900 ns/op   691 B/op   17 allocs/op    2000000
BenchmarkAuthorization/disallowed_configmap-8                                   868 ns/op   693 B/op   17 allocs/op    2000000
BenchmarkAuthorization/disallowed_secret_via_pod-8                              875 ns/op   693 B/op   17 allocs/op    2000000
BenchmarkAuthorization/disallowed_shared_secret_via_pvc-8                      1215 ns/op   948 B/op   22 allocs/op    1000000
BenchmarkAuthorization/disallowed_pvc-8                                         912 ns/op   693 B/op   17 allocs/op    2000000
BenchmarkAuthorization/disallowed_pv-8                                         1137 ns/op   834 B/op   19 allocs/op    2000000
BenchmarkAuthorization/disallowed_attachment_-_no_relationship-8                892 ns/op   677 B/op   16 allocs/op    2000000
BenchmarkAuthorization/disallowed_attachment_-_feature_disabled-8               236 ns/op   208 B/op    2 allocs/op   10000000
BenchmarkAuthorization/allowed_attachment_-_feature_enabled-8                   723 ns/op   593 B/op   12 allocs/op    2000000

BenchmarkAuthorization/contentious_allowed_node_configmap-8                     726 ns/op   529 B/op   11 allocs/op    2000000
BenchmarkAuthorization/contentious_allowed_configmap-8                          698 ns/op   529 B/op   11 allocs/op    2000000
BenchmarkAuthorization/contentious_allowed_secret_via_pod-8                     778 ns/op   529 B/op   11 allocs/op    2000000
BenchmarkAuthorization/contentious_allowed_shared_secret_via_pod-8            21406 ns/op   638 B/op   13 allocs/op     100000
BenchmarkAuthorization/contentious_disallowed_node_configmap-8                 1135 ns/op   692 B/op   17 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_configmap-8                      1239 ns/op   691 B/op   17 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_secret_via_pod-8                 1043 ns/op   692 B/op   17 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_shared_secret_via_pvc-8          1404 ns/op   950 B/op   22 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_pvc-8                            1177 ns/op   693 B/op   17 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_pv-8                             1295 ns/op   834 B/op   19 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_attachment_-_no_relationship-8   1170 ns/op   676 B/op   16 allocs/op    1000000
BenchmarkAuthorization/contentious_disallowed_attachment_-_feature_disabled-8   262 ns/op   208 B/op    2 allocs/op   10000000
BenchmarkAuthorization/contentious_allowed_attachment_-_feature_enabled-8       790 ns/op   593 B/op   12 allocs/op    2000000

--- BENCH: BenchmarkAuthorization
   node_authorizer_test.go:592: graph modifications during non-contention test: 0
   node_authorizer_test.go:589: graph modifications during contention test: 6301
   node_authorizer_test.go:590: <1ms=5507, <10ms=128, <25ms=43, <50ms=65, <100ms=135, <250ms=328, <500ms=93, <1000ms=2, >1000ms=0
PASS
ok     k8s.io/kubernetes/plugin/pkg/auth/authorizer/node   112.616s
```

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-scalability-pr-reviews @kubernetes/sig-auth-pr-reviews 
/assign @mikedanese @wojtek-t

**Comment by wojtek-t** [comment]
@liggitt To clarify - I don't have any proof that node-authorizer is causing us significant performance problems (in fact I think it's not). It's just surprising to me that it is responsible for 15% of cpu-usge of apiserver (and I've seen more examples of profiles like this that is linked in the xref-ed issue).

That said, it might be useful to look into cpu-profile and see why it is the case (from the profile I was looking into it seems to be related to "authorizations", not to "graph updates").

When I know think about it is that, in the test where I'm seeing that we:
- have 5,000 nodes
- create 3,000 pods per namespace, 50 namespaces (150,000 pods in total)
- we generally end up with roughly equal spreading, so let's assume we have 30 pods per node
- let's assume for a moment that pods from a given namespace (3,000 of them) end up on 2,000 nodes [they each share the same namespace service account] and there are pods form 20 namespaces on each of nodes
- since Kubelet is periodically polling for each of its secrets every 5minutes,  this gives 20 * 5,5000 = 100k queries per 5m => 333 QPS

Each of the authorization of each needs to traverse from a secret via its pods (3000) to a correct node. 
So on average that gives 1.500 to go through.
1.500  * 333QPS gives roughly 0.5M of objects to traverse per second

So that CPU may actually be justified.

@liggitt @mikedanese - WDYT about above math?
Do you think we can optimize it? Is that worth it?

[BTW - changes to this benchmark LGTM]

**Comment by liggitt** [comment]
> @liggitt @mikedanese - WDYT about above math?
> Do you think we can optimize it? Is that worth it?

changing the benchmark profile to a single namespace makes the "shared secret" cost go up dramatically
```BenchmarkAuthorization/allowed_node_configmap-8              2000000           713 ns/op         529 B/op          11 allocs/op
BenchmarkAuthorization/allowed_configmap-8                   2000000           864 ns/op         529 B/op          11 allocs/op
BenchmarkAuthorization/allowed_secret_via_pod-8              2000000           853 ns/op         529 B/op          11 allocs/op
BenchmarkAuthorization/allowed_shared_secret_via_pod-8           200       6149900 ns/op       15424 B/op         224 allocs/op```

"run a few really big deployments across a lot of nodes" doesn't seem like too crazy a use case for a big cluster

I'll think about whether there's a straightforward way to accomodate that data profile

**Comment by wojtek-t** [comment]
@liggitt - thanks a lot

Since the benchmark itself is extremely useful, I'm LGTM-ing it to have the PR already merged and useful for everyone interested. We can continue discussion on https://github.com/kubernetes/kubernetes/pull/62892 (BTW - thanks a lot for looking into that)

/lgtm

**Pull request merged**
