### PR TITLE
Fix command field PodExecOptions

### PR DESCRIPTION
**Pull request by csrwng**
Change the command field to an array of strings.

### CODE REVIEW

**Comment by csrwng** [comment]
This change is happening on versioned resources. However, the resources are not yet exposed by the client commands and are not being used yet. @smarterclayton PTAL

**Comment by smarterclayton** [comment]
LGTM.  @bgrant0607 - the initial implementation of the new endpoint params was broken, this corrects it.  No consumers should be affected

**Comment by bgrant0607** [comment]
Ok. As long as you're touching this, please clarify the description text. Command is an argv array? Does it execute in a shell?

**Comment by csrwng** [comment]
@bgrant0607 - thx. Updated description.

**Comment by bgrant0607** [comment]
LGTM

**Comment by mbforbes** [comment]
(Temp assigning Brian until Travis says it's OK—will merge then.)

**Comment by mbforbes** [comment]
Travis green; merging.

**Pull request merged**
