### PR TITLE
Fix link to apiextensions client-go example

### PR DESCRIPTION
**Pull request by nikhita**
Fixes link to client-go example for apiextensions-apiserver.

Fixing #47211.

**Special notes for your reviewer**:

When I run `hack/update-staging-client-go.sh`, I get this error:

```
!!! Error in staging/copy.sh:132
    Error in staging/copy.sh:132. 'git commit -q -m "Snapshot" > /dev/null' exited with status 1
  Call stack:
    1: staging/copy.sh:132 main(...)
  Exiting with status 1
```

What am I missing here?
/cc @caesarxuchao @sttts 

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
This is already being fixed in #47223.

**Comment by nikhita** [comment]
Oh sorry, should have checked before. Closing.

**Comment by nikhita** [comment]
There was a minor typo in #47223. This PR fixes that now.

But I still keep hitting the error while updating the staging area. Any ideas why?

**Comment by caesarxuchao** [comment]
Eh, thanks.

/lgtm

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@nikhita in this PR you don't need to run that script. The script is going to be changed dramatically this week, so i probably won't debug the issue.

**Comment by caesarxuchao** [comment]
This should be cherry-picked to release-1.7

**Pull request merged**
