### PR TITLE
Fix link to moved Docker image

### PR DESCRIPTION
**Pull request by webwurst**
See https://github.com/kubernetes/kubernetes/pull/79390

/kind documentation

### CODE REVIEW

**Review by monotek — APPROVED** [review]
/lgtm

**Comment by webwurst** [comment]
@monotek can you give this another look? i just hit the wrong link again ;D

**Review by monotek — APPROVED** [review]

**Review by ialidzhikov — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@monotek, `/approve` is needed. Could you please finally put it?

@nikhita, or anyone from contributor experience, why it takes ages similar PR to get in?

**Comment by nikhita** [comment]
/release-note-none
/ok-to-test
/priority backlog

@ialidzhikov Thanks for surfacing, I'll follow-up with folks on slack to get this approved.

**Comment by nikhita** [comment]
/retest

Too many flakes :(

**Pull request merged**
