### PR TITLE
Automated cherry pick of #24830

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #24830 on release-1.2.

### CODE REVIEW

**Comment by zmerlynn** [comment]
@david-mcmahon / @eparis: Do you know what's going on with the release note checking here? Why is it looking for only those two labels when the parent has `release-note-none`?

**Comment by eparis** [comment]
At one point we had a rule (I thought) that all cherry-picks had to be release-noted. aka release-note-none was not allowed. The idea was that if something was important enough to warrent a cherrypick it was important enough to release note. It seems that is not the policy any more. I can certainly get the bot to completely ignore `release-note-*` on PRs not against master. Is that what everyone wants?

**Comment by zmerlynn** [comment]
I'd argue we don't care a ton about release-noting test changes, but I can be swayed either way.

**Comment by eparis** [comment]
In which case I kinda like the fact that you, as the branch maintainer, have to take a second to make sure the 'parent' PR is correct. If it really is a -none, you can label the child none. Unreasonable? I'll change the bot, but I personally kinda like what it is doing right now...

**Comment by zmerlynn** [comment]
@eparis: Works for me, just curious. :)

**Comment by yujuhong** [comment]
Travis build timed out: #23611

**Comment by eparis** [comment]
travis is irrelevant.

**Comment by david-mcmahon** [comment]
@eparis, the original intent of the implementation was that the master/parent PR provided the ack in the form of anything other than `release-note-label-needed`.  It only adds additional accounting to the master/cherrypick relationship to further require an ack on the cherrypick PR when the master/parent PR already sets a state.  The doc currently reflects that workflow as well.  Can you make the change when you get a chance?

**Comment by david-mcmahon** [comment]
@eparis, strike that.  Sorry, I pressed 'comment' there before considering the requirement that ALL cherrypicks of course require a release note.  Perhaps the only change here in that case is to update the nag message to something like:
```
All cherrypick PRs must be release noted by labeling the 'parent' PR with either the "release-note" or "release-note-action-required" label.
```
There shouldn't be any other option here, including a release-note-none label on either the master or the cherrypick PR.  The idea is that anything landing on a branch is there for a good enough reason that a release note is always required.

**Pull request merged**
