### PR TITLE
Fix todo: scheduler config.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Fix todo. Make the declaration of `componentbaseconfigv1alpha1.DebuggingConfiguration` same as other fields.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority important-longterm

**Review by draveness — APPROVED** [review]
/lgtm

Thanks!

**Comment by jfbai** [comment]
/assign @bsalamat

PTAL, thanks.

**Comment by jfbai** [comment]
kindly ping @luxas @bsalamat for review, thanks a lot. :)

**Comment by alculquicondor** [comment]
This change might need a KEP, unless there's already one.

/hold

**Pull request closed without merging**
