### PR TITLE
Fix third party

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/25421
Fixes https://github.com/kubernetes/kubernetes/issues/25422

@AdoHe @sjenning @caesarxuchao @lavalamp 

@kubernetes/sig-api-machinery 

[Analytics]()

### CODE REVIEW

**Comment by lavalamp** [comment]
@krousey can you review this? I'm buried today.

**Comment by brendandburns** [comment]
(I'm fixing this unit test...)

**Comment by brendandburns** [comment]
@k8s-bot test this please issue: #25925

**Comment by brendandburns** [comment]
@k8s-bot unit test this please issue: #25925

**Comment by krousey** [comment]
@brendandburns Are you looking to get this in today? It seems there are some interaction issues with the proto encoder.

**Comment by smarterclayton** [comment]
```
(BI0520 13:45:20.316557    2956 kubelet.go:2497] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]]
```

**Comment by brendandburns** [comment]
I sorted out at least one problem, still looking into the e2e...

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this issue: #26385

**Comment by brendandburns** [comment]
@krousey I believe this is ready for review, node e2e is a flake.

**Comment by krousey** [comment]
@brendanburns What was the issue earlier?

**Comment by brendandburns** [comment]
There were two issues:

1) I wasn't handling YAML properly in the IsThirdPartyResource function

2) I wasn't properly determining if an object was third party if the `into` object was a `VersionedObjects` and the `GroupVersionKind` was `nil`

**Comment by krousey** [comment]
This is LGTM, but should there be test cases at least for the `VersionedObjects` case?

**Comment by krousey** [comment]
@brendanburns Friendly ping. Is that a no on the test case?

**Comment by brendandburns** [comment]
@krousey that's a "it was memorial day weekend" ;)

Test case added, please take another look.

**Comment by brendandburns** [comment]
@k8s-bot unit test this please issue: #23879

**Pull request merged**
