### PR TITLE
add e2e test for services with pods hostNetwork: true as backends

### PR DESCRIPTION
**Pull request by aojea**
we were missing tests with backend pods with hostNetwork: true
for services.
This just adds another dimension to current "services regular checks", using the service backend pods with hostNetwork: true

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
the change looks good to me, ideally someone from sig-network should be assigned for review.

**Comment by aojea** [comment]
I messed this up somehow with a wrong rebase and added all the sig and labels, sorry
/hold
using hostNetwork true makes that the tests can not run in parallel because the allocated ports conflict and can not be scheduled

**Comment by aojea** [comment]
let me close this, is spanning all sigs. 
I' ll reopen later
sorry for the noise
/close

**Pull request closed without merging**
