### PR TITLE
Removed broken link to Analytics

### LINKED ISSUE #93949: Analytics link not working in main README.md
The analytics link https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/README.md?pixel embedded in [README.md](https://github.com/kubernetes/kubernetes/blob/master/README.md) is not working now.

If you open https://github.com/kubernetes/kubernetes, scroll down to the bottom, you will get:

image

/kind documentation

### PR DESCRIPTION
**Pull request by avr1254**
**What type of PR is this?**
/kind documentation
/kind cleanup

**What this PR does / why we need it**:
This PR removes nonfunctional links to an obsolete analytics page.
**Which issue(s) this PR fixes**:

Fixes #93949 

**Special notes for your reviewer**:
Hi there! This is my first PR, so please let me know if anything needs to be fixed for next time. Thanks!
**Does this PR introduce a user-facing change?**:

```release-note
  NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MHBauer** [comment]
#93949
/ok-to-test
/lgtm

**Review by tanjunchen — APPROVED** [review]

**Comment by avr1254** [comment]
@tanjunchen  Do you mind approving the changes? I'm not sure if there's anything to do on my end.

**Pull request merged**
