### PR TITLE
Code cleanup: fix some typo

### PR DESCRIPTION
**Pull request by victory460**
#### What type of PR is this?
 /kind cleanup
 
 #### What this PR does / why we need it:
 #### Which issue(s) this PR fixes:
Fix typo :
depenging -> depending
permssion -> permission
 
 #### Does this PR introduce a user-facing change?
```
 NONE
```

### CODE REVIEW

**Comment by victory460** [comment]
/assign @pacoxu @wojtek-t  @ixdy @jimmidyson 
Thanks a lot.

**Comment by pacoxu** [comment]
It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked [`help-wanted`](https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).

/lgtm
anyway

**Review by MrHohn — APPROVED** [review]
Thanks - I don't think I can approve though.
/lgtm
/approve

**Review by monotek — APPROVED** [review]

**Comment by victory460** [comment]
/unassign @MrHohn @pacoxu
/assign @jpbetz @wenjiaswe 
Thanks a lot!

**Pull request merged**
