### PR TITLE
Automated cherry pick of #54687: fix CreateVolume: search mode for Dedicated kind

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #54687 on release-1.7.

#54687: fix CreateVolume: search mode for Dedicated kind

### CODE REVIEW

**Comment by andyzhangx** [comment]
@brendandburns 
I got a customer case that one azure storage account was mistakenly removed by k8s v1.7.7 azure provider, this PR has the fix:
```
-	// if forced (as in one disk = one storage account)
 -	// delete the account completely
 -	if wasForced {
 -		return c.deleteStorageAccount(storageAccountName)
 -	}
```
With this PR, there would be no `deleteStorageAccount` operation in azure cloud provider since it's very dangerous, there is some corner case would lead to this **DATA LOSS** issue.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
