### PR TITLE
Add a function to cluster scripts to obtain the provider specific kubeconfig context of the cluster.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PR #35867 which will be reviewed independently.

Design Doc: PR #34484

cc @kubernetes/sig-cluster-federation @nikhiljindal 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35958)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM. Thanks @madhusudancs

**Comment by dims** [comment]
@saad-ali @quinton-hoole @madhusudancs : is this too late for v1.5?

**Comment by saad-ali** [comment]
> @saad-ali @quinton-hoole @madhusudancs : is this too late for v1.5?

It was LGTM'd in time. If the rebase is not too large, it would be ok

**Comment by madhusudancs** [comment]
I am withdrawing this PR for now. We found an alternative way to do this. I will reopen this if necessary.

However, @dims thanks for looking into this. @saad-ali thanks for the LGTM.

**Pull request closed without merging**
