### PR TITLE
kubeadm: statically default ImagePullPolicy in v1beta3

### LINKED ISSUE #2519: add imagePullPolicy field to kubeadm config print
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.22

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
According to kubernetes/kubernetes#102901 "imagePullPolicy" has be added. So I think we should add this field to output of kubeadm config print init-defaults|join-defaults

## What you expected to happen?
Add to ield to output of kubeadm config print init-defaults|join-defaults

## How to reproduce it (as minimally and precisely as possible)?
kubeadm config print   init-defaults | join-defaults

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

Instead of dynamically defaulting NodeRegistration.ImagePullPolicy,
which is common when doing defaulting depending on host state - e.g.
hostname, statically default it in v1beta3/defaults.go.

- Remove defaulting in checks.go
- Add one more unit test in checks_test.go
- Adapt v1beta2 conversion and fuzzer / round tripping tests

This also results in the default being visible when calling:
"kubeadm config print ...".

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/524
fixes https://github.com/kubernetes/kubeadm/issues/2519

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @pacoxu @wangyysde 
PTAL for LGTM.

/milestone v1.22
/sig cluster-lifecycle
/area kubeadm
/priority important-soon

**Comment by neolit123** [comment]
/kind cleanup
/approve
(?... approve not auto added)

**Review by pacoxu — APPROVED** [review]
LGTM
leave to @wangyysde  to review. 😄

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by neolit123** [comment]
not sure if @wangyysde can review in time, but we should get this LGTM-ed ideally soon (before Thursday).

**Comment by pacoxu** [comment]
/lgtm
😄

**Pull request merged**
