### PR TITLE
GCE provider: Log full contents of long operations

### PR DESCRIPTION
**Pull request by zmerlynn**
[Analytics]()Dump JSON of long running (>1m) GCE operations.

### CODE REVIEW

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this, issue #IGNORE (PR builder flake)

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by zmerlynn** [comment]
Looks like we're blocked on #23545 :(

**Comment by fgrzadkowski** [comment]
@k8s-bot test this issue: #23545

**Comment by zmerlynn** [comment]
@k8s-bot test this, issue #IGNORE (early PR builder flake, fixed now)

**Comment by zmerlynn** [comment]
@k8s-bot node e2e test this issue: #26431

**Comment by zmerlynn** [comment]
This was in the queue for almost a week, and I'd really like it for diagnostics on long-running GCE operations. Requesting cherry-pick.

**Pull request merged**
