### PR TITLE
Deflake node serial tests

### PR DESCRIPTION
**Pull request by ehashman**
Let's see if these two patches together can get the job green.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
two failures from https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103992/pull-kubernetes-node-kubelet-serial/1420487403944022016/
```
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive] update Node.Spec.ConfigSource: 100 update stress test: status and events should match expectations
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive] update Node.Spec.ConfigSource: non-nil last-known-good to a new non-nil last-known-good status and events should match expectations 
```

let's try running it again
/test pull-kubernetes-node-kubelet-serial

**Comment by ehashman** [comment]
Those were a tad flaky before: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&exclude-non-failed-tests=&include-filter-by-regex=update%20Node.Spec.ConfigSource

I think this is a good sign

**Comment by smarterclayton** [comment]
Be sure to drop the revert commit of my change (since it hasn't been shown to impact anything).

**Comment by ehashman** [comment]
https://github.com/kubernetes/kubernetes/pull/103982 is CI without the revert; the serial tests are much, much flakier without it.

**Pull request closed without merging**
