### PR TITLE
Revert Dockerfile changes for kubectl image.

### PR DESCRIPTION
**Pull request by rayandas**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
This PR reverts changes done in https://github.com/kubernetes/kubernetes/pull/119592 because of [master-blocking](https://testgrid.k8s.io/sig-release-master-blocking#build-master) and [master-informing](https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20arm64%20-%20master) failures. 
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rayandas** [comment]
cc: @dims

**Comment by xmudrii** [comment]
I propose keeping this PR on hold until we gather opinion from relevant SIGs.
/hold

**Comment by pacoxu** [comment]
/sig cli
/sig release
Include reviewer in the last PR.
/cc @bart0sh  @BenTheElder @thockin

**Review by saschagrunert — APPROVED** [review]
We may need to adjust the multiarch buildx env somehow in test-infra to let the build pass. I guess we can move forward with the PR and re-evaluate the topic in a new one.

**Comment by xmudrii** [comment]
Based on what @saschagrunert said, let's proceed with this PR.
/lgtm
/approve
/hold cancel

**Comment by rayandas** [comment]
@saschagrunert @xmudrii Should I raise a new WIP PR with the Dockerfile changes and look into the build failure to see if I can find a solution?

**Comment by xmudrii** [comment]
@rayandas However you prefer. We can also use #119567 to discuss how do we want to approach this.

**Pull request merged**
