### PR TITLE
Revert "Remove alpha provisioning"

### PR DESCRIPTION
**Pull request by shyamjvs**
We are seeing a regression starting from run [4748](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/4748) of gci-gke test. There seems to be an issue with the dynamic volume provisioning test. Almost surely this has been caused due to commit https://github.com/kubernetes/kubernetes/commit/8faa9b5d4eabc2b47a598626128194dcd4cacae5 where alpha version for dynamic provisioning seems to be removed.

Reverting the commit should fix it, unless there's something else that can be done (cc @jsafrane)

cc @k8s-oncall @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
Reverts #40000 

cc @thockin @erictune @msau42 @enisoc @jsafrane

**Comment by shyamjvs** [comment]
Merged it based on wojtek's lgtm. Sorry for delay.

**Comment by thockin** [comment]
Jan, Sorry for the mess.  Let me know if you think this isn't right, for
some reason.

**Comment by jsafrane** [comment]
It's perfectly OK to revert it if it breaks tests on GKE, no hard feelings. It would help if you route  https://github.com/kubernetes/kubernetes/issues/41559 to appropriate team/person so I can revert this revert before 1.6 freeze :-).

**Pull request merged**
