### PR TITLE
Moves util/interrupt into kubectl, since its only used there

### PR DESCRIPTION
**Pull request by seans3**
* Moves the core util/interrupt package into kubectl/util, since kubectl is the only place that uses it.

1) [Umbrella Issue: Remove kubectl dependencies on kubernetes/kubernetes](https://github.com/kubernetes/kubectl/issues/80)
2) [Remove Kubectl dependencies on kubernetes/pkg/api and kubernetes/pkg/apis](https://github.com/kubernetes/kubectl/issues/83)

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by smarterclayton** [comment]
/hold

I have a PR moving this into client-go

**Comment by smarterclayton** [comment]
I meant utils 
https://github.com/kubernetes/utils/pull/47

**Pull request closed without merging**
