### PR TITLE
Optimize ExtractInvalidPods testing scenarios

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
 /kind flake

**What this PR does / why we need it**:

Optimize `ExtractInvalidPods` testing scenarios.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zouyee** [comment]
@yujuhong PTAL

**Comment by zouyee** [comment]
@derekwaynecarr gentle ping

**Comment by spiffxp** [comment]
/remove-kind flake
this isn't a flaking test

**Comment by dashpole** [comment]
This looks like it is removing a few test-cases, and adding others.  I'm fine with adding test cases, but prefer not to remove the coverage we already have.

/kind cleanup

**Pull request closed without merging**
