### PR TITLE
Rework automatic doc generation

### PR DESCRIPTION
**Pull request by eparis**
This simplifies (I hope) how we generate automated docs. We create a tmp dir and generate all docs in that tempdir. Before this commit we generated a different tempdir for different types of docs generated. We were also putting files listing the generated docs all over the place. Now we have a single file in the root of the repo for all automatically generated docs.

### CODE REVIEW

**Comment by eparis** [comment]
@mikedanese this is the first part of breaking up #13018

**Comment by zmerlynn** [comment]
Apologies for delay, @k8s-merge-robot doesn't respect vacation calendars. Reassigning to @mikedanese so I can possibly get out of email debt sometime today.

**Comment by eparis** [comment]
@deads2k has been doing a good review in #13614

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
```
@@ -1,3 +1,4 @@
+.generated_docs
 contrib/completions/bash/kubectl
 docs/man/man1/kubectl-annotate.1
 docs/man/man1/kubectl-api-versions.1
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
make: *** [verify] Error 1
The command "make verify BRANCH=$TRAVIS_BRANCH" exited with 2.
```

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot test this. (looks like a bunch of flakes)

**Pull request merged**
