### PR TITLE
Added possibility to overwrite ENABLE_CLUSTER_DNS with env var

### PR DESCRIPTION
**Pull request by piosz**
It's for autoscaling tests purposes and making the config consistent with
other flags like ENABLE_NODE_LOGGING

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by brendandburns** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by zmerlynn** [comment]
@thockin: Weren't we just talking about permanently enabling this one? This is kind of backwards from that. (I mean, it's always been changable in config-default.sh, but it's dubious if you can actually usefully turn it off.)

**Comment by thockin** [comment]
I'm fine with this, but I hope soon it is not an option at all...

**Pull request merged**
