### PR TITLE
Clean up unused openapi-gen cmd

### PR DESCRIPTION
**Pull request by roycaihw**
Follow up of https://github.com/kubernetes/kubernetes/pull/65737#discussion_r201827142

as we switched from `k8s.io/code-generator/cmd/openapi-gen` to `k8s.io/kube-openapi/cmd/openapi-gen`

/release-note-none
/sig api-machinery

### CODE REVIEW

**Comment by sttts** [comment]
/hold

I think this PR is fine. Just double checking with @mvladev for https://github.com/kubernetes/kubernetes/pull/65440.

**Comment by mvladev** [comment]
Thanks for the heads up @sttts. I've a question - if we need to generate OpenAPI definitions in `k8s.io/code-generator` for `_example` folder what will be the correct way to do it? Add it to `third_party`? I can't see how to pinpoint to a specific version.

**Comment by sttts** [comment]
@mvladev we should vendor it in code-generator. Maybe we have to add some artificial dependency to enforce that.

**Comment by sttts** [comment]
@mvladev any update?

**Comment by lavalamp** [comment]
I'd love to merge this, any update?

**Comment by roycaihw** [comment]
@lavalamp Thanks for reminding :) Will do a rebase today

**Comment by roycaihw** [comment]
Rebased. Please take a look.

**Comment by lavalamp** [comment]
@mvladev any objection to merging this?

**Comment by mvladev** [comment]
@lavalamp it looks good.

**Comment by lavalamp** [comment]
argh, already out of date :(

**Comment by roycaihw** [comment]
Rebased again :)

**Comment by roycaihw** [comment]
Rebased the third time. This PR didn't merge because I forgot it still had the `do-not-merge/hold` label.

/hold cancel
(though I don't think PR authors are allowed to unhold :( )

cc @lavalamp

**Pull request merged**
