### PR TITLE
kubeadm: use kubelet bootstrap instead of reimplementing

### PR DESCRIPTION
**Pull request by mikedanese**
@kubernetes/sig-cluster-lifecycle-api-reviews

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
v1.8.x still has to support joining v1.7 kubelets, so we have to exec to `kubelet --version` or something to detect that in the meantime. In the beginning of the next cycle we can remove this completely :tada:

Otherwise LGTM, but we have to update kubernetes/release as well

**Comment by mikedanese** [comment]
This works for 1.7 kubelets.

**Comment by mikedanese** [comment]
Also please point me to where we discuss or document kubeadm compatibility. That was not a skew I knew we supported and I'm not sure we should support.

**Comment by luxas** [comment]
/lgtm retroactively indeed
Don't know where I had left my brain when I wrote that comment :joy:

Re skew support: On the official documentation page, in the upgrades doc and discussed in some of the SIG calls.

**Comment by pipejakob** [comment]
@mikedanese Is there a related PR for making the same changes to the `release` repo? Or for `rpms/10-kubeadm.conf`?

**Pull request merged**
