### PR TITLE
Automated cherry pick of #77224: Upgrade Stackdriver Logging Agent addon image from 1.6.0 to

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #77224 on release-1.12.

#77224: Upgrade Stackdriver Logging Agent addon image from 1.6.0 to

### CODE REVIEW

**Comment by qingling128** [comment]
@MaciekPytel @mwielgus  - Could someone help grant the /ok-to-test flag?

**Comment by qingling128** [comment]
Friendly ping. Could someone help grant the /ok-to-test flag?

**Comment by qingling128** [comment]
Not sure if https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/77247/pull-kubernetes-verify/1125450643486543873 is intermittent.
Rerunning the tests.

@MaciekPytel - Can you approve this as cluster/gce/OWNERS? Seems like that bit is missing. 

@feiskyer - (Found your name in the https://github.com/kubernetes/sig-release/blob/master/releases/release-1.12/release_team.md as the patch release manager). When is the last patch release cut for v1.12.9? We'd like to get this fix in. Wondering if we are still on track.

**Comment by qingling128** [comment]
@MaciekPytel @feiskyer - Friendly ping.

**Comment by qingling128** [comment]
Thanks @MaciekPytel !

@feiskyer - Could you help with the `do-not-merge/cherry-pick-not-approved` label? BTW when is the last patch release cut for v1.12.9?

**Comment by feiskyer** [comment]
> Could you help with the do-not-merge/cherry-pick-not-approved label? BTW when is the last patch release cut for v1.12.9?

cherry pick approved. v1.12.9 would probably be released on next next week.

**Comment by qingling128** [comment]
@feiskyer - Thanks for confirming!

**Pull request merged**
