### PR TITLE
Automated cherry pick of #43972

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #43972 on release-1.6.

#43972: kube-proxy: filter INPUT as well as OUTPUT

```release-note
kube-proxy handling of services with no endpoints now applies to both INPUT and OUTPUT chains, preventing socket leak
```

### CODE REVIEW

**Comment by justinsb** [comment]
@thockin cherry-pick of the second half of the fix, as we briefly discussed earlier.

**Comment by thockin** [comment]
release note?

**Comment by justinsb** [comment]
Added release note: "kube-proxy handling of services with no endpoints now applies to both INPUT and OUTPUT chains, preventing socket leak"  Feel free to edit of course :-)

**Comment by thockin** [comment]
@enisoc Are you merging cherrypicks for 1.6 ?

**Comment by justinsb** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Pull request merged**
