### PR TITLE
Automated cherry pick of #55782

### PR DESCRIPTION
**Pull request by x13n**
Cherry pick of #55782 on release-1.8.

#55782: Bump addon manager version used to 6.5

### CODE REVIEW

**Comment by shyamjvs** [comment]
/approve no-issue
(for the kubemark part)

**Comment by x13n** [comment]
@jpbetz Can we include this in 1.8.4?

**Comment by x13n** [comment]
/kind feature
/priority important-soon
I'm not sure which sig fits best here, probably:
/sig cluster-lifecycle

**Pull request merged**
