### PR TITLE
Update guestbook-go example according to config best practices

### PR DESCRIPTION
**Pull request by linzichang**
related to #11361

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by linzichang** [comment]
@brendandburns Can you show out the GCE e2e fail log. I can't access the test url.

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:524
Oct  5 08:44:49.918: Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.148.195 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/examples/guestbook-go/redis-master-controller.json --namespace=e2e-tests-kubectl-zz854] []  <nil>  the path "/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/examples/guestbook-go/redis-master-controller.json" does not exist
 [] <nil> 0xc2082345a0 exit status 1 <nil> true [0xc208053170 0xc2080531c0 0xc2080531f8] [0xc208053170 0xc2080531c0 0xc2080531f8] [0xc2080531a0 0xc2080531e8] [0x6be060 0x6be060] 0xc2082d1380}:
Command stdout:

stderr:
the path "/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/examples/guestbook-go/redis-master-controller.json" does not exist
```

**Comment by bgrant0607** [comment]
Awaiting resolution of #14256

**Comment by bgrant0607** [comment]
Please apply similar changes as were made in #14256.
cc @jeffmendoza @amygdala

**Comment by linzichang** [comment]
OK.

**Comment by bgrant0607** [comment]
Sorry for the delay. 

cc @kubernetes/examples

**Comment by linzichang** [comment]
Sorry. I have no time to work on this now. Maybe someone can take over this.

**Pull request closed without merging**
