### PR TITLE
Use predefined variable instead of duplicated string

### PR DESCRIPTION
**Pull request by yoongon**
#### What type of PR is this?
/kind cleanup

#### Does this PR introduce a user-facing change?
None

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yoongon** [comment]
pinging @alculquicondor for approval

**Review by alculquicondor — COMMENTED** [review]
/approve

**Pull request merged**
