### PR TITLE
Removed `gc_` prefix for gc admission.

### PR DESCRIPTION
**Pull request by gyliu513**
We should remove the `gc_` prefix for gc admission to keep
consistent with other files under plugin/pkg/admission.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by feiskyer** [comment]
Is this change reasonable? With same file name in different packages, it is very hard to locate the owner of logs.

**Comment by gyliu513** [comment]
@feiskyer The reason that I update it is because all of the `admission` related are named as `admission.go`, I want to update the `gc` to make consistent with others. Also I think it does make sense to update its name as the `gc_admission.go` is already under the folder `gc`, there is no need to add prefix `gc` again for it. comments?

**Comment by feiskyer** [comment]
> Also I think it does make sense to update its name as the gc_admission.go is already under the folder gc, there is no need to add prefix gc again for it. comments?

Although it is under `gc` folder, filename in logs doesn't include folder name.

**Comment by k82cn** [comment]
> Although it is under gc folder, filename in logs doesn't include folder name.

Good point on log :). If can not identify the file by log, I'll grep all files in admission.
I think @gyliu513 's suggestion is to make file names in admission consistent: with or without dir name for all.

@derekwaynecarr , any suggestion on that? Should we add feature (e.g. gc_) names to other admission? or remove it?

**Comment by feiskyer** [comment]
> any suggestion on that? Should we add feature (e.g. gc_) names to other admission? or remove it?

I suggest add folder prefix to all other admissions.

**Comment by gyliu513** [comment]
For troubleshooting, agree to @feiskyer , adding prefix maybe better cc @derekwaynecarr any comments on this? Thanks.

**Comment by derekwaynecarr** [comment]
I am going to close this PR as the goal is not entirely clear.

If we want to improve the logging across all admission plug-ins, I am supportive of that, but I would like something to grep on other than file name, and it should be common across all logs produced in that package.

It seems more reasonable to include the name of the admission plugin in the log output.

**Pull request closed without merging**
