### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by davidxia**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixes a minor typo in a comment.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]

**Comment by masap** [comment]
Hi! Could you fix this typo as well ?

https://github.com/kubernetes/kubernetes/blob/d63dc87ae8b6d568785bd4c532fb16d99a6b7338/test/kubemark/resources/start-kubemark-master.sh#L473

**Comment by davidxia** [comment]
> Hi! Could you fix this typo as well ?
> 
> https://github.com/kubernetes/kubernetes/blob/d63dc87ae8b6d568785bd4c532fb16d99a6b7338/test/kubemark/resources/start-kubemark-master.sh#L473

Thanks, done!

**Comment by masap** [comment]
Thanks !

**Comment by davidxia** [comment]
A merge or next steps would be much appreciated. Thanks

**Comment by davidxia** [comment]
Ha, should I keep retrying the failing test?

**Comment by BenTheElder** [comment]
> [sig-node] Probing container should be ready immediately after startupProbe 
/table-flip
/retest

**Pull request merged**
