### PR TITLE
Cherry pick of anp 0.0.27 for v1.21

### PR DESCRIPTION
**Pull request by rata**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates konnectivity-network-proxy to v0.0.27. This includes a memory leak fix for the network proxy

see: #106922

Cherry-picks of this fix to other release branches:
 * v1.23: https://github.com/kubernetes/kubernetes/pull/107037
 * v1.22: https://github.com/kubernetes/kubernetes/pull/107187
 * v1.21: This PR

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Updates konnectivity-network-proxy to v0.0.27. This includes a memory leak fix for the network proxy
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rata** [comment]
As with #107187 I'd like @cheftako or @jkh52 to take a look, just in case, as this is a bigger version jump.

I didn't test this locally as hack/local-up-cluster in this version doesn't know about env var EGRESS_SELECTOR_CONFIG_FILE to configure konnectivity. I guess there are e2e tests for this, though, right? (A quick grep on tests/ for konnectivity, network-proxy or anp didn't show anything). @cheftako @jkh52 probably you know?

**Comment by jkh52** [comment]
Is it typical to cherry pick to several minor versions at the same time? Or, should release-1.21 be treated more conservative than -1.22 or -1.23?

**Comment by rata** [comment]
@jkh52 It [was requested by @xmudrii](https://github.com/kubernetes/kubernetes/pull/107037#issuecomment-999657281). They said they prefer to merge the same cherry-pick in all branches at the same time. That is why I created these PRs

**Comment by rata** [comment]
@liggitt This is still missing the lgtm label, but you have provided both in this PR for other branches, so maybe you can do the same for this? :)

/assign @liggitt

**Pull request merged**
