### PR TITLE
Automated cherry pick of #15336

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #15336 on release-1.0.

### CODE REVIEW

**Comment by ihmccreery** [comment]
@jlowdermilk Please review with serious skepticism, this was very much not a clean cherrypick.

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please.

**Comment by jlowdermilk** [comment]
Ugh... this is going to require a cherrypicking a bunch more changes to pull missing test scripts into the release branch.

**Comment by ihmccreery** [comment]
This isn't going to happen; too hard.

**Pull request closed without merging**
