### PR TITLE
federation: Start controller-manager after apiserver is running

### LINKED ISSUE #44490: federation: federation-controller-manager is restarted during init
After bringing up federation control plane, most of the time we do see that federation-controller-manager pod is restarted like below:
```
root@s70553-HP-EliteBook-840-G2:~/gopath/src/k8s.io/kubernetes# kubectl --namespace=federation-system get pods
NAME                                            READY     STATUS    RESTARTS   AGE
federation-apiserver-832758761-z1k2p            2/2       Running   0          54s
federation-controller-manager-105127570-15bpq   1/1       Running   1          54s
```
Although there is no issues afterwards, this is just causing few seconds delay in federation-controller-manager becoming operational.

cc @kubernetes/sig-federation-bugs

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**: Fixes the issue mentioned in #44490
If we start apiserver and controller-manager simultaneously, controller-manager panics, as apiserver might not be ready. Instead of starting apiserver and controller-manager together. this pr starts the apiserver and waits until it is running, then it starts the controller-manager

federation controller-manager takes following time to become operational from the time we start `kubefed init`
Before the fix: 37seconds
After the fix: 7seconds 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44490
This also kind of completely removes the flakiness discussed in #26725

**Special notes for your reviewer**:

**Release note**:

```
NONE
```
cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by csbell** [comment]
/assign perotinus
See #42296

**Comment by marun** [comment]
I'm not sure the proposed approach is the right way to address the problem.  Starting controllers serially might be quick on a single node, where the cost of downloading the hyperkube image is shared, but what if the pods are started on separate nodes?  Is there a reason the controller manager shouldn't instead wait for the apiserver for a configurable timeout (default, say, 30s) before failing?

**Comment by shashidharatd** [comment]
Since many of the system components like kube-proxy & kubelet use hyperkube image, i am inclined to think the image would be pre-pulled by one of these components even if the federation pods are started on separate nodes.

**Comment by marun** [comment]
@shashidharatd I'm not sure it makes sense to make assumptions about how kubernetes is deployed.  kube-proxy won't necessarily be running (there are other ways of supporting services), and the kubelet may be deployed from packages rather than an image.

I think the root of the issue you're trying to fix is that the controller manager is not sufficiently tolerant of the apiserver not being available immediately on startup.  Consider that both apiserver and controller manager are managed by deployments which can be redeployed in response to changes or upgrades.  Wouldn't it make more sense to ensure both kubefed and subsequent deployment rollouts are more reliable, rather than just solving the problem for kubefed?

**Comment by shashidharatd** [comment]
@marun, I completely agree with your argument that we need more reliable way to solve this problem.

The reason i feel controller-manager should be started after apiserver is running is also for another reason.
When leaderelection feature for controller-manager lands, there is need for ConfigMap object and its namespace to be created before in apiserver before the controller-manager starts running. Although leaderelection can create a ConfigMap object if it fails to find one, at least the namespace containing the ConfigMap should exist. This is kind of bootstrapping problem.

**Comment by marun** [comment]
@shashidharatd Could your use case be met if the controller manager waited for the configmap object and failed if it didn't find it within the timeout?

**Comment by shashidharatd** [comment]
yes @marun, that would solve my usecase

**Comment by shashidharatd** [comment]
Closing this as the approach was not right as discussed above, we need to fix it within the federation-controller-manager initialization.

**Pull request closed without merging**
