### PR TITLE
Hide deprecated shorthand in man page

### LINKED ISSUE #15593: The deprecated shorthand still shows up in the man page
As we know, a deprecated shorthand will continue to function, but will not show up in help or usage messages. But the deprecated shorthand still shows up in the man page, we should remove it.

### PR DESCRIPTION
**Pull request by feihujiang**
Fix #15593

### CODE REVIEW

**Comment by feihujiang** [comment]
@eparis I know using ```len(flag.ShorthandDeprecated) > 0``` to verify the shorthand is deprecated or not is not very correct, so I add a todo notes.

**Comment by ashcrow** [comment]
Jenkins failure looks unrelated:

```
Probing container
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:101
  with readiness probe should not be ready before initial delay and never restart [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:74

  pod never became ready
  Expected error:
      <*errors.errorString | 0xc20802de60>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:59
```

**Comment by ashcrow** [comment]
@feihujiang in the upstream spf code it looks like```len()``` is used for the same kind of check. However, if you wanted to change it in the kubernetes code you could check to see if ```flag.ShorthandDeprecated``` is anything but an empty string (which would note the shorthand is deprecated).. Personally I think either way is OK.

**Comment by ashcrow** [comment]
I pulled the patch, built ```genman```, and gave it a go and it properly hid ```-c``` just showing ```--client``` and ```-t``` just showing ```--template```.

:+1:

**Comment by feihujiang** [comment]
@ashcrow  Yes, len() is used for the same kind of check. But I mean useing ```len(flag.ShorthandDeprecated) > 0``` to verify a shorthand is deprecated or not is not very correct. When a shorthand is deprecated, maybe we specify an empty message,  so the  flag.ShorthandDeprecated is empty as the shorthand is deprecated. If we don't specify an empty message, it works.

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
This broke `hack/verify-generated-docs.sh`:

```
Verifying ./hack/../hack/verify-generated-docs.sh
+++ [1020 17:02:11] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [1020 17:02:23] Placing binaries
--- /tmp/tmp.vRu3JJG2lD/docs/man/man1/kubectl-autoscale.1	2015-10-20 17:02:29.816835321 -0700
+++ /jenkins-master-data/jobs/kubernetes-test-go/workspace/docs/man/man1/kubectl-autoscale.1	2015-10-19 14:15:26.358816166 -0700
@@ -72,7 +72,7 @@ An autoscaler can automatically increase
     If non\-empty, sort list types using this field specification.  The field specification is expressed as a JSONPath expression (e.g. 'ObjectMeta.Name'). The field in the API resource specified by this JSONPath expression must be an integer or a string.
 
 .PP
-\fB\-\-template\fP=""
+\fB\-t\fP, \fB\-\-template\fP=""
     Template string or path to template file to use when \-o=go\-template, \-o=go\-template\-file. The template format is golang templates [
 \[la]http://golang.org/pkg/text/template/#pkg-overview\[ra]].
 
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in ./hack/../hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
FAILED
```

Autoscale merged yesterday in #15739, which was after the last Travis/Shippable run.

fyi @k8s-oncall

**Comment by JanetKuo** [comment]
@ixdy fixing in #15996

**Comment by ixdy** [comment]
Thanks. I filed https://github.com/kubernetes/contrib/issues/197 regarding the submit queue failure here.

**Pull request merged**
