### PR TITLE
Use fmt.Errorf to replace errors.New

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Use fmt.Errorf to replace errors.New

**Special notes for your reviewer**:
refer to https://github.com/kubernetes/kubernetes/pull/45335

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ash2k** [comment]
As an external observer I'm just curious - what is the motivation for this change? Well, in this particular case it makes sense to use `fmt.Errorf()` to format the string instead of concatenating parts, but the other PR that is referred changes places where a constant string is used. Why change them to a more expensive formatting function?

**Comment by zhangxiaoyu-zidif** [comment]
@ash2k  I think its value is to keep same code style. Even fmt contains the method we need , it is not necessary to import errors. That is my viewpoint. =)

**Comment by zhangxiaoyu-zidif** [comment]
ping @kargakis 
PTAL

**Comment by kargakis** [comment]
Not sure this adds any value. There is no formatting included.

/close

**Pull request closed without merging**
