### PR TITLE
Fix non-ascii characters in  test/e2e/node/pods.go

### PR DESCRIPTION
**Pull request by 928234269**
Signed-off-by: Sakura <longfei.shang@daocloud.io>

**What type of PR is this?**
> /kind bug
> /kind cleanup

**What this PR does / why we need it**:
Fix non-ascii characters which are written accidentally.

**Which issue(s) this PR fixes**:
Ref #87679

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dashpole** [comment]
/ok-to-test

Why shouldn't we include non-ascii characters in comments?

**Comment by 928234269** [comment]
> /ok-to-test
> 
> Why shouldn't we include non-ascii characters in comments?
See #87679.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
Thanks for this fix

**Review by oomichi — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
