### PR TITLE
Kubectl explain with aggregated resources

### PR DESCRIPTION
**Pull request by luksa**
**What this PR does / why we need it**:
Currently, it's not possible to do "kubectl explain" on resources from aggregated API servers (such as the Service Catalog API server, for example):
```
$ kubectl explain clusterservicebroker
error: group servicecatalog.k8s.io has not been registered
```

This PR addresses this problem by removing kubectl explain's unnecessary lookup into `scheme.Registry`, which only contains resource types registered in the kubectl client itself. 

Explaining clusterservicebrokers now works:
```
$ _output/bin/kubectl explain clusterservicebroker
DESCRIPTION:
     ClusterServiceBroker represents an entity that provides
     ClusterServiceClasses for use in the service catalog.

FIELDS:
   apiVersion	<string>
   ...
```

**Which issue(s) this PR fixes** 
There was no existing issue and I did not file one. Should I?

**Release note**:
```release-note
kubectl explain can now be used with resources from aggregated API servers
```

### CODE REVIEW

**Comment by MHBauer** [comment]
/ok-to-test

Seems neat to me.

I've not particularly used `kubectl explain` before.

I am not familiar with the code, but it looks pretty sane. I'd like to see some kind of test, but I'm not sure how to get a aggregated API in the test environment to see.

**Comment by luksa** [comment]
Closing this, as the same changes went in in a different PR: https://github.com/kubernetes/kubernetes/pull/58753

**Pull request closed without merging**
