### PR TITLE
correct the kubeDeps.Cloud instead of kcfg.Cloud

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
default to hostname if kubeDeps.Cloud == nil not kcfg.Cloud
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
/ok-to-test
It's just a comment error
/lgtm

**Comment by jianglingxia** [comment]
/assign @vishh
for /approve no-issue

**Comment by jianglingxia** [comment]
PTAL@vishh
for /approve no-issue

**Comment by jianglingxia** [comment]
/cc @yujuhong
thanks

**Pull request merged**
