### PR TITLE
Update k8s.io/kube-openapi for apimachinery

### PR DESCRIPTION
**Pull request by nghialv**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Related issue: https://github.com/kubernetes/kube-openapi/issues/167

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @sttts

### CODE REVIEW

**Comment by nikhita** [comment]
@nghialv This will need to follow the instructions in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md :)

**Comment by nghialv** [comment]
Hi, after checking again I think this PR will not resolve the root problem ([as this comment](https://github.com/kubernetes/kube-openapi/issues/167#issuecomment-513049233))
So I think you can close this PR.

Thank you.

**Pull request closed without merging**
