### PR TITLE
Automated cherry pick of #91307: CSI: Modify VolumeAttachment check to use Informer/Cache

### PR DESCRIPTION
**Pull request by xing-yang**
Cherry pick of #91307 on release-1.17.

#91307: CSI: Modify VolumeAttachment check to use Informer/Cache

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
/priority important-soon
from parent PR https://github.com/kubernetes/kubernetes/pull/91307

**Comment by xing-yang** [comment]
/hold
Waiting for Parent PR  #91307 to be merged first.

**Comment by dims** [comment]
/approve
/lgtm
/hold cancel 

(#91307 has all approvals and is in merge queue)

**Comment by xing-yang** [comment]
#91307 is merged.

**Comment by liggitt** [comment]
This just merged to master 9 hours ago, and I couldn't tell from the comments at https://github.com/kubernetes/kubernetes/pull/91307#issuecomment-639141621 if that PR introduced correctness issues. Are we sure this is ready to release to a stable branch?

**Comment by dims** [comment]
@liggitt hoping @yuga711 / @saad-ali / @msau42 can chime in. @xing-yang and i have gotten a bunch of internal testing for this patch and it looks good! it reduces the time taken and the load on api server.

**Comment by msau42** [comment]
@liggitt there's a potential race that causes the in-memory state to be off, but the reconciler fixes it in the next loop. It wouldn't cause something to become detached when it shouldn't, which was my main concern.

**Comment by mcristina422** [comment]
We're experiencing this issue after upgrading to 1.17, on a cluster with ~200 nodes and ~500 volumeattachments. Attachments are now extremely slow

**Comment by liggitt** [comment]
/approve
for controller-manager change

**Pull request merged**
