### PR TITLE
Updated auto generated protobuf codes.

### PR DESCRIPTION
**Pull request by k82cn**
Generated by `./hack/update-generated-protobuf-dockerized.sh` in Mac.

### CODE REVIEW

**Comment by liggitt** [comment]
@smarterclayton surprised things were working with proto tags missing on these types before.

**Comment by liggitt** [comment]
I expected a generated proto change under apis/storage/v1

**Comment by liggitt** [comment]
also should probably have a test that ensures external types have proto tags on all their fields

**Comment by k82cn** [comment]
I think that because of protobuf's version:

```
ubuntu@ubuntu-xenial:~/k8s_ws/src/k8s.io/kubernetes$ docker run kube-build:build-3296b8ff4f-5-v1.7.5-2 protoc --version
libprotoc 3.0.0
ubuntu@ubuntu-xenial:~/k8s_ws/src/k8s.io/kubernetes$ protoc --version
libprotoc 3.2.0
```

**Comment by k82cn** [comment]
@k8s-bot kops aws e2e test this

**Comment by smarterclayton** [comment]
Caused by https://github.com/kubernetes/kubernetes/issues/35486

**Comment by k82cn** [comment]
ping @smarterclayton for lgtm :).

**Pull request merged**
