### PR TITLE
Rename logging images to use google_containers

### PR DESCRIPTION
**Pull request by satnam6502**
As discussed in #6229 
@thockin @nikhiljindal @mattmoor @dchen1107 
And for GKE coverage @zmerlynn @a-robinson @roberthbailey

### CODE REVIEW

**Comment by dchen1107** [comment]
I believe you already verified all images are already pushed to gcr.io using google_containers path, right?

LGTM

**Comment by satnam6502** [comment]
I brought up a fresh cluster and observed Elasticsearch working and the Kibana dashboard was showing your kubelet log files being ingested.

```
satnam@satnam-linux kubernetes dedash /$ kubectl get pods
POD                                               IP           CONTAINER(S)            IMAGE(S)                                             HOST                                                                  LABELS                                                              STATUS    CREATED
elasticsearch-logging-controller-1nf93            10.244.1.3   elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.0           kubernetes-minion-94zx.c.kubernetes-satnam.internal/104.197.16.133    kubernetes.io/cluster-service=true,name=elasticsearch-logging       Running   12 minutes
fluentd-to-elasticsearch-kubernetes-minion-0dnn   10.244.0.2   fluentd-es              gcr.io/google_containers/fluentd-elasticsearch:1.3   kubernetes-minion-0dnn.c.kubernetes-satnam.internal/130.211.123.231   <none>                                                              Running   10 minutes
fluentd-to-elasticsearch-kubernetes-minion-94zx   10.244.1.2   fluentd-es              gcr.io/google_containers/fluentd-elasticsearch:1.3   kubernetes-minion-94zx.c.kubernetes-satnam.internal/104.197.16.133    <none>                                                              Running   10 minutes
fluentd-to-elasticsearch-kubernetes-minion-9yxa   10.244.2.2   fluentd-es              gcr.io/google_containers/fluentd-elasticsearch:1.3   kubernetes-minion-9yxa.c.kubernetes-satnam.internal/104.154.78.159    <none>                                                              Running   10 minutes
fluentd-to-elasticsearch-kubernetes-minion-yixp   10.244.3.2   fluentd-es              gcr.io/google_containers/fluentd-elasticsearch:1.3   kubernetes-minion-yixp.c.kubernetes-satnam.internal/104.154.69.40     <none>                                                              Running   10 minutes
kibana-logging-controller-73lpz                   10.244.0.3   kibana-logging          gcr.io/google_containers/kibana:1.1                  kubernetes-minion-0dnn.c.kubernetes-satnam.internal/130.211.123.231   kubernetes.io/cluster-service=true,name=kibana-logging              Running   12 minutes
kube-dns-o1zcz                                    10.244.1.4   etcd                    quay.io/coreos/etcd:v2.0.3                           kubernetes-minion-94zx.c.kubernetes-satnam.internal/104.197.16.133    k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   Running   12 minutes
                                                               kube2sky                gcr.io/google-containers/kube2sky:1.1                                                                                                                                                                    
                                                               skydns                  gcr.io/google-containers/skydns:2015-03-11-001                                                                                                                                                           
monitoring-heapster-controller-ctj00              10.244.3.3   heapster                gcr.io/google-containers/heapster:v0.9               kubernetes-minion-yixp.c.kubernetes-satnam.internal/104.154.69.40     kubernetes.io/cluster-service=true,name=heapster                    Running   12 minutes
monitoring-influx-grafana-controller-d2jtv        10.244.2.3   influxdb                gcr.io/google-containers/heapster_influxdb:v0.3      kubernetes-minion-9yxa.c.kubernetes-satnam.internal/104.154.78.159    kubernetes.io/cluster-service=true,name=influxGrafana               Running   12 minutes
                                                               grafana                 gcr.io/google-containers/heapster_grafana:v0.5                                                                                                                                                           
```

**Comment by satnam6502** [comment]
@thockin : should the fluentd-es and fluentd-gcp per node collectors also get the cluster-services label?

S

**Comment by dchen1107** [comment]
LGTM

**Comment by a-robinson** [comment]
LGTM

**Comment by thockin** [comment]
I think yes  - they are things running in the "default" namespace.

**Pull request merged**
