### PR TITLE
Automated cherry pick of #44058

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #44058 on release-1.7.

#44058: revert 45764

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@liggitt @kargakis could you take a look at this cherry-pick? Thanks.

**Review by janetkuo — APPROVED** [review]

**Comment by caesarxuchao** [comment]
A k8s-bot bug? Janet is an approver.

**Comment by janetkuo** [comment]
@k8s-merge-robot was just slow

**Pull request merged**
