### PR TITLE
adjust admission plugins order 

### LINKED ISSUE #58039: admission-control flag should have a reasonable order
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

In most use case, `NamespaceLifecycle` comes behind `Initializers`.

According to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L69 `NamespaceLifecycle` plugin should be the first one . 

**What you expected to happen**:

 `NamespaceLifecycle` be the first ordered in `--admission-control`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

put `NamespaceLifecycle ` at first of admission-control

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58039

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
ping @eparis @jbeda for approval

**Comment by jbeda** [comment]
/sig api-machinery

What is the impact on users? From what I see, this is a non-mutating admission controller and so there shouldn't be a problem with the order.

But I'm not expert here so someone from api-machinery should verify.

**Comment by hzxuzhonghu** [comment]
@jbeda https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
And `NamespaceLifecycle,Initializers` is the hard coded orders, but current logic orders depend on `--admission-flag`.

according to this `NamespaceLifecycle` should always come first. It admit or deny request at first to prevent `Initializers` do some unavailing work.

**Comment by jbeda** [comment]
Comment at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L65 says "This list is mix of mutating admission plugins and validating admission plugins. The apiserver always runs the validating ones after all the mutating ones, so their relative order in this list doesn't matter."

So.. order here shouldn't matter.  Is there a demonstrable bug?

**Comment by jbeda** [comment]
@liggitt -- It *looks* like the namespace lifecycle plugin doesn't mutate.  Am I reading the description/code wrong?

Also -- if this is so critical, the order should probably be specified in our documentation around this stuff.  There is no talk of required admission controller order at https://kubernetes.io/docs/admin/admission-controllers/.

**Comment by jbeda** [comment]
Regardless -- I'll defer to you @liggitt -- if you need my approve power here (not sure) let me know.

**Comment by liggitt** [comment]
This is a fine change. It likely just makes a more sensible error in the case where there's an issue with both the namespace and initializer. 

There is work in flight as well to remove the need for the user to manually manage the order, which will make this unnecessary long term, but this is good for now. 

/lgtm

**Comment by hzxuzhonghu** [comment]
close, since #58123 already make admission-control orders not matters

**Pull request closed without merging**
