### PR TITLE
Update seccomp runtime/default to docker/default

### PR DESCRIPTION
**Pull request by jpeeler**
The docs are not in alignment with the code and the code is correct:

https://github.com/kubernetes/kubernetes/blob/59caf07228231c7c78aae66f9c1ad60e2c42fc29/pkg/kubelet/dockertools/docker_manager.go#L1191

https://github.com/kubernetes/kubernetes/blob/59caf07228231c7c78aae66f9c1ad60e2c42fc29/pkg/api/validation/validation.go#L2122

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36086)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@pmorie This sounds like a bug in the implementation.

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
@bgrant0607 I agree, this is a bug.

**Comment by pmorie** [comment]
@jpeeler the idea was to be runtime agnostic and support 'runtime/default' as opposed to any specific runtime name.  So, the implementation is in error and should be fixed.

**Comment by dims** [comment]
@jessfraz : your thoughts please.

**Comment by jessfraz** [comment]
LGTM

**Comment by dims** [comment]
@pmorie @jessfraz @bgrant0607 - Guess for 1.5 we fix the documentation and then see what we can do to fix the implementation after that?

**Comment by bgrant0607** [comment]
@dims Is this feature staying alpha in 1.5?

**Comment by dims** [comment]
@bgrant0607 i haven't seen any effort to get this off of alpha. ran into this when i was reviewing PR(s) :)

**Comment by jessfraz** [comment]
this should be able to be merged shouldn't it?

**Comment by jpeeler** [comment]
I don't know what the best way to handle this is currently. It was mentioned earlier to merge this so it would be in 1.5 and then later fix the implementation. But that was way before 1.5 betas were out, so it might be best for me to just close this and file a bug for the implementation.

**Comment by jpeeler** [comment]
Closing now with a community PR to supercede.

**Pull request closed without merging**
