### PR TITLE
fix the typo of Kubernetes Worker

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
fix the typo of Kubernetes Worker that Kubernetes spell error
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```NONE

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign @eparis @jlowdermilk 
thanks!

**Comment by jianglingxia** [comment]
ping @sttts

can you review the pr，thanks！

**Comment by sttts** [comment]
Approved due to triviality.

**Pull request merged**
