### PR TITLE
Allow glusterfs dp volume creation  for empty clusterid parameter in sc.

### PR DESCRIPTION
**Pull request by humblec**
Why this patch is needed? 

The `strings.split()` (https://github.com/kubernetes/kubernetes/pull/37986/files#diff-e97253dd603331ffca81131a4b67264fR700) returns a slice of `single element("empty") ` when the split is attempted on a string. This is expected according to  `https://golang.org/pkg/strings/#Split` and `https://github.com/golang/go/issues/13075`. This make the provisioner to fail, if `clusterid` is not defined in the SCs. This patch make sure the split is attempted only when clusterid is mentioned in the sc parameter.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by rootfs** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@rootfs @jsafrane please review/merge.

**Comment by jsafrane** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Comment by jsafrane** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
