### PR TITLE
Add '/version/' to the system:discovery role, since that's what the spec says.

### PR DESCRIPTION
**Pull request by brendandburns**
See: https://github.com/kubernetes-client/java/issues/153

```release-note
Add the path '/version/' to the `system:discovery` cluster role.
```

### CODE REVIEW

**Comment by brendandburns** [comment]
Friendly ping to @liggitt I'd like to cherry-pick this into 1.9 once merged, since it is breaking clients.

**Comment by liggitt** [comment]
No objection, but do we actually answer subpaths?

**Comment by liggitt** [comment]
We should also fix the openapi spec to not put a trailing slash on the version endpoint url

**Comment by brendandburns** [comment]
@liggitt 
It does work correctly, so we do answer at least '/version/'

**Comment by liggitt** [comment]
Let's just do /version/, then, and fix openapi ASAP

**Comment by brendandburns** [comment]
@liggitt switched to `/version/`

**Pull request merged**
