### PR TITLE
expose: Don't query the server for input objects

### LINKED ISSUE #13173: Auto-create replication cotroller first when using '-f' to expose it.
When using `kubectl expose -f nginx-controller.yaml --port=80 --target-port=8000` to expose an rc, if the rc is not created yet, it will report `Error from server: replicationControllers "nginx-controller" not found
`.
Can we create the rc first instead of throw this error? Since `-f` implies that resource has been passed to the command and `expose` actually does a `create` work.

@kubernetes/kubectl @feihujiang

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes #13173

@kubernetes/kubectl

### CODE REVIEW

**Comment by kargakis** [comment]
can somebody restart Jenkins?

**Comment by smarterclayton** [comment]
ok to test

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
LGTM. Thanks!

**Pull request merged**
