### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ruirlliu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fixed typo 

command

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a 

user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
/lgtm
/approve

**Comment by lavalamp** [comment]
/approve

(I think there's no harm in waiting until after code freeze to merge, so not putting on the milestone label)

**Pull request merged**
