### PR TITLE
remove unused comment

### PR DESCRIPTION
**Pull request by davidstack**
this file has  in k8s.io/api.

### CODE REVIEW

**Comment by nikhita** [comment]
@davidstack Can you squash the commits to a single commit? Thanks!

**Comment by davidstack** [comment]
@nikhita  i have squash these commits.thanks.

**Comment by cblecker** [comment]
@davidstack You have a merge commit (https://github.com/kubernetes/kubernetes/pull/53758/commits/f52ff0760777527458362caef6968fed308edcb6) in this branch. https://github.com/kubernetes/kubernetes/pull/53758/commits/71c6609853765830295f24d76702e9bd5f0e4938 should be rebased on top of master, and have a descriptive commit message.

**Comment by davidstack** [comment]
@cblecker i am sorry for my wrong commits. i creat another commit for this issue #53951  thanks

**Comment by cblecker** [comment]
/close
Closing in favour of #53951.

**Pull request closed without merging**
