### PR TITLE
Update to new cadvisor v0.48.1

### PR DESCRIPTION
**Pull request by dims**
Lots of goodies in new cadvisor: https://github.com/google/cadvisor/compare/v0.47.3...v0.48.1

#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rphillips** [comment]
@dims

```diff --git a/pkg/kubelet/cadvisor/cadvisor_linux.go b/pkg/kubelet/cadvisor/cadvisor_linux.go
index 2c93cfa936f..4c9dc55cee4 100644
--- a/pkg/kubelet/cadvisor/cadvisor_linux.go
+++ b/pkg/kubelet/cadvisor/cadvisor_linux.go
@@ -97,7 +97,7 @@ func New(imageFsInfoProvider ImageFsInfoProvider, rootPath string, cgroupRoots [
        }

        duration := maxHousekeepingInterval
-       housekeepingConfig := manager.HouskeepingConfig{
+       housekeepingConfig := manager.HousekeepingConfig{
                Interval:     &duration,
                AllowDynamic: pointer.Bool(allowDynamicHousekeeping),
        }

```

**Comment by dims** [comment]
@rphillips thanks! adding a commit

**Comment by rphillips** [comment]
Looks like a flake

/test pull-kubernetes-unit

**Comment by rphillips** [comment]
Blocked on https://github.com/kubernetes/kubernetes/pull/121615#issuecomment-1787422650

**Comment by rphillips** [comment]
@dims https://github.com/kubernetes/kubernetes/pull/121647 merged... This PR needs a rebase to latest master.

**Comment by aritraghosh** [comment]
Can this change also be cherry picked to 1.26, 1.27 and 1.28? This change significantly reduces the memory reported on cgroup v2 to match v1. A lot of users have been experiencing memory saturation without this change
[
cgroupv2](url)

**Comment by dims** [comment]
@aritraghosh probably not the entire thing! .. if you all can help find out which small focused update to cadvisor will help then we can entertain doing a `v0.47.4` in cadvisor with that patch which can then be used against stable releases

**Pull request merged**
