### PR TITLE
test: wait until all pods are available for newly created deployment

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/35337

@kubernetes/deployment

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36309)

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@k8s-bot unit test this #36351

**Comment by kargakis** [comment]
@k8s-bot unit test this #36351

**Comment by kargakis** [comment]
@k8s-bot unit test this #36351

**Pull request merged**
