### PR TITLE
Provide reference to impersonation options for kubectl auth can-i command.

### LINKED ISSUE #1082: "kubectl auth can-i" miss documentation for "--as" parameter
**What would you like to be added**: 
- When running`kubectl auth can-i -h`, make mention that the `--as=` parameter is possible.
- When running`kubectl auth can-i -h`, display two examples of the usage of the `--as=` parameter, one for a normal user, and another one for a service account located in a particular namespace.

**Why is this needed**:
- The `--as` parameter is missing in the CLI help doc.
- The usage of  `--as` with a service account is not straight forward for a beginner, given that some prefixes should be mentioned before the actual name of the service account (eg. `--as system:serviceaccount:namespace:name`)

### PR DESCRIPTION
**Pull request by orsenthil**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubectl/issues/1082 - Provide reference to impersonation options in auth can-i command.

#### Does this PR introduce a user-facing change?

```release-note

NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
Thanks!

/ok-to-test

**Review by soltysh — APPROVED** [review]
/triage accept
/lgtm
/approve
/priority important-longterm

**Pull request merged**
