### PR TITLE
Fix up godeps since container/v1beta1 is gone.

### PR DESCRIPTION
**Pull request by brendandburns**
@roberthbailey @cjcullen

### CODE REVIEW

**Comment by eparis** [comment]
did friggin godeps change how the handle licenses AGAIN! argh.

**Comment by eparis** [comment]
@brendandburns should we just fix it in this PR?  Can you update your godep binary to the latest upstream, `godep restore; rm -rf Godeps; godep save ./...` ?

**Comment by roberthbailey** [comment]
This looks like a dupe of https://github.com/kubernetes/kubernetes/pull/17457 except that you changed fewer files....

**Comment by brendandburns** [comment]
ugh, I looked for a similar change and didn't see that PR *sigh*, it has the same godeps problem that @eparis pointed out

**Comment by brendandburns** [comment]
I'll defer this PR in favor of #17457 once that merges I'll remove this.

**Comment by roberthbailey** [comment]
> ugh, I looked for a similar change and didn't see that PR sigh

@quinton-hoole emailed you that PR number this afternoon. Maybe you missed it. :smile:

**Comment by eparis** [comment]
I can work him through that PR, but he has numerous different problems with his and yours is right as it stands...

I guess really fixing the regursive godep license issue should be it's own PR, grumble godeps, grumble.

**Comment by eparis** [comment]
closing, fixed in #17500 which merged.

**Pull request closed without merging**
