### PR TITLE
Automated cherry pick of #69430: Populate ClientCA in delegating auth setup

### PR DESCRIPTION
**Pull request by yue9944882**
Cherry pick of #69430 on release-1.12.

#69430: Populate ClientCA in delegating auth setup

### CODE REVIEW

**Comment by yue9944882** [comment]
it addresses leaky comment by @sttts https://github.com/kubernetes/kubernetes/pull/69430#issuecomment-427272854

**Review by feiskyer — COMMENTED** [review]
cherry pick approved

**Pull request merged**
