### PR TITLE
Remove cloud provider dependency from volume host and volume controllers

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:

The cloud-vendor in-tree volume plugins have completed csi migration, see https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes.

The portworxVolume does not depend on the cloud provider, so removing related codes from volume controllers in the controller manager and volume host in Kubelet is safe.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

KEP: https://github.com/elmiko/kubernetes-enhancements/blob/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md

The DisableCloudProviders and DisableKubeletCloudCredentialProvider feature-gates only impact functionality tied to the --cloud-provider flag, specifically in-tree volume plugins are not covered. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/approve 
(the storage parts)

**Comment by jsafrane** [comment]
@dims please approve if you find it OK

**Comment by carlory** [comment]
/cc @jsafrane 

rebased. please review it again.

**Comment by pacoxu** [comment]
/lgtm
after rebase

**Pull request merged**
