### PR TITLE
fix staticcheck errors in pkg/volume/emptydir.

### PR DESCRIPTION
**Pull request by 928234269**
Signed-off-by: Sakura <longfei.shang@daocloud.io>

**What type of PR is this?**

> /kind bug
> /kind cleanup

**What this PR does / why we need it**:
cleanup staticcheck errors, it says as below:
```
pkg/volume/emptydir/empty_dir.go:175:2: field desiredSize is unused (U1000)
```
**Which issue(s) this PR fixes**:
Ref:#81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rata** [comment]
@928234269 Thanks for the PR. But why did you close it?

**Comment by 928234269** [comment]
@rata  I saw that someone fixed this problem,#87128, but my pr did the same thing as him, the strange thing is that I can't see in my pr that this has been fixed.Can you guide me what should i do.

**Comment by 928234269** [comment]
@rata Should I close this pr? I am very confused.

**Comment by rata** [comment]
@928234269 yes, an identical is merged. I think you might need to rebase on top of latest master to see it.

Thanks again for your patch! :)

**Pull request closed without merging**
