### PR TITLE
WIP: Speed up pod watch by not create map

### PR DESCRIPTION
**Pull request by HardySimpson**
**Help reduce the watch CPU cost**:

Most CPU cost in apiserver's watch is on this [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L190) with pprof test result

```
func PodToSelectableFields(pod *api.Pod) fields.Set {
	// The purpose of allocation with a given number of elements is to reduce
	// amount of allocations needed to create the fields.Set. If you add any
	// field here or the number of object-meta related fields changes, this should
	// be adjusted.
	podSpecificFieldsSet := make(fields.Set, 5)
	podSpecificFieldsSet["spec.nodeName"] = pod.Spec.NodeName
	podSpecificFieldsSet["spec.restartPolicy"] = string(pod.Spec.RestartPolicy)
	podSpecificFieldsSet["status.phase"] = string(pod.Status.Phase)
	return generic.AddObjectMetaFieldsSet(podSpecificFieldsSet, &pod.ObjectMeta, true)
}

```

As `make(fields.Set, 5)` is actually make a map, which is quite slow because there is memory allocation in it. And every time when pod had status change, it will go through this code and make watch slow.

The main way of avoid this cost is focus on the nodeName, if there is only a NodeName selector, don't call PodToSelectableFields and simply compare the pod's nodeName.

we have test that it could save about 20% CPU apiserver cost on over 2000 node in density test.

**Special notes for your reviewer**:

**Release note**:

```
none
```

### CODE REVIEW

**Comment by ncdc** [comment]
cc @jayunit100

**Comment by ncdc** [comment]
@HardySimpson does anything other than test code make use of your new `PodFastPredicate`?

**Comment by jayunit100** [comment]
Seems plausible but Lets paste/measure the performance cost you're talking + add the optimization where something uses the PFP  about before reviewing  this .  its not easy to evaluate as a generic component that is unused ....

**Comment by brendandburns** [comment]
Why are there all of the SelectionPredicate -> SelectionMatcher edits?

That seems unrelated.

**Pull request closed without merging**
