### PR TITLE
Remove api.ListOptions (it was replaced by unversioned.ListOptions)

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #15945

@caesarxuchao @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by smarterclayton** [comment]
@lavalamp So I'm looking at the end result of all this, and I think this
was a mistake.

We have a very clear code path for converting versioned things between
options.  We've replaced the very clear path for controlling that into a
bunch of ugly code in request.go that emulates everything that we have to
do in conversion.  Not only that, we still have to transform and convert
the actual field selectors, which is a responsibility that should be done
in the scheme.  So we've effectively created a shadow copy of
conversion/scheme in request.go, specifically around field transformation
AND the parameter transformation.

I don't want to continue this pattern of shoving things into unversioned.
I am fundamentally opposed to the mindset that there are large swathes of
what we send across the wire than are "effectively unversioned".  I'd like
to institute a very clear process where by we as a group agree that
something is unversioned before we move things into pkg/api/unversioned - I
think we are making a mistake in the rapidity at which we are throwing
things in there.

I want to have a discussion about ListOptions going back into versioned.  I
don't see the clear justification that requires it, and I see the ugly code
that results.

**Comment by wojtek-t** [comment]
@smarterclayton - I mostly agree with what you wrote above (fortunately most of the work around it appeared to be different cleanups to use ListOptions instead of few different parameters in many different places - which is clear gain anyway).

There is just one question - ListOptions is something that shouldn't be part of v1 API, because it logically should belong to all different API groups. So we would need something like "versioned, but un-groupped" or sth like that. Or do you have any other suggestions how to solve it?
[I think that registering objects from v1 API in other api groups is not the best idea].

**Comment by wojtek-t** [comment]
On the other hand - moving those strange conversion functions out of Request, should be doable without getting back to versioned ListOptions.

**Comment by smarterclayton** [comment]
We cross register objects in multiple APIs all the time - the code supports
it, and you control that through normal code interface migration problems.
Making up a new "unversioned" category that you push things into because
cross-registration seems wrong is trying to pretend the problem doesn't
exist.

**Comment by wojtek-t** [comment]
@smarterclayton - can you point me to the example where we register an object from one api group in another api group - I'm not aware of that.

**Comment by smarterclayton** [comment]
All the examples were deleted in Kube when v1beta3 was removed, but we had
several examples.

I would frame it like this. ListOptions is per API group, and versioned per
rev.  When we have 3rd party api servers, each api server is running a
different version of Kube code.  The client library that talks to that Kube
code will also need to be targeted to that server - the ListOptions for
"group1" in client and server is going to have different fields than the
client library for "" group or "extensions".  The APIVersions that are
supported are also different - serializing FieldSelector into group1/v1 is
not the same as group2/v2, and vice versa.  Clients need to know (at
compile time) whether their field is supported.  If I have a versioned
client from each group, and only compilable Go type (in unversioned) that
represents both of those, we've gone back to having to version the code
there.  At the time a client library is generated for a concrete API
version, you know unambiguously what fields are supported.  Leaving those
unsupported fields there means a client library can't trust whether the
field is supported.

**Comment by wojtek-t** [comment]
@smarterclayton - thanks for explanation - I guess I buy the argument why you want to have ListOptions versioned (although I still think that this is orthogonal to e.g. cleaning up request.go code - which we should also do)

However, I still don't really follow what exactly you want to do. From what you wrote above, I think that what we should do is to create:
v1.ListOptions
extensions.ListOptions
componentconfig.ListOptions
...
But from what I understood from previous comments (correct me if I'm wrong), you would like to register v1.ListOptions in every api group. Why?

**Comment by smarterclayton** [comment]
It's cheap and easy, and the code supports it.  We could always copy it - I
don't care either way.

**Comment by wojtek-t** [comment]
@smarterclayton - got it (I'm for copying it). I will try to send you 2 PRs doing this (one server side and one client side) later this week or early next week.

**Comment by lavalamp** [comment]
> We've replaced the very clear path for controlling that into a bunch of ugly code in request.go that emulates everything that we have to do in conversion.

Didn't that already exist?

> Not only that, we still have to transform and convert the actual field selectors, which is a responsibility that should be done in the scheme.

I don't have a good plan for field selector conversion :(

>So we've effectively created a shadow copy of conversion/scheme in request.go, specifically around field transformation AND the parameter transformation.

I agree the client side thing in request.go has got to go, but it already existed before this change, no?

> I don't want to continue this pattern of shoving things into unversioned. ... I'd like to institute a very clear process where by we as a group agree that something is unversioned before we move things into pkg/api/unversioned - I think we are making a mistake in the rapidity at which we are throwing things in there.

Point taken.

> I am fundamentally opposed to the mindset that there are large swathes of what we send across the wire than are "effectively unversioned".

I don't disagree, I think I interpret the name "unversioned" a lot less literally than you. I expect all the things in "unversioned" need new homes eventually. I.e., it means not-versioned-yet, we'll be carrying these things for a long time.

Maybe we can talk about the category of things that are common to more than one group but are versionable/swappable, and where such things should be placed.

ListOptions (and other options) is a bit of a special case, because apiserver needs to understand some of them, but apiserver (the generic library parts) should not have to import our v1 api.

**Comment by smarterclayton** [comment]
On Mon, Jan 4, 2016 at 12:36 PM, Daniel Smith <notifications@github.com>
wrote:

> We've replaced the very clear path for controlling that into a bunch of
> ugly code in request.go that emulates everything that we have to do in
> conversion.
>
> Didn't that already exist?
>

I'm mostly referring to the recent move out, that Wojtek moved back in.


> Not only that, we still have to transform and convert the actual field
> selectors, which is a responsibility that should be done in the scheme.
>
> I don't have a good plan for field selector conversion :(
>
Me either, although we can build maps during traversal for conversion
generation and I think that mostly addresses it.  It's a lot of strings,
however.


> So we've effectively created a shadow copy of conversion/scheme in
> request.go, specifically around field transformation AND the parameter
> transformation.
>
> I agree the client side thing in request.go has got to go, but it already
> existed before this change, no?
>
> I don't want to continue this pattern of shoving things into unversioned.
> ... I'd like to institute a very clear process where by we as a group agree
> that something is unversioned before we move things into
> pkg/api/unversioned - I think we are making a mistake in the rapidity at
> which we are throwing things in there.
>
> Point taken.
>
> I am fundamentally opposed to the mindset that there are large swathes of
> what we send across the wire than are "effectively unversioned".
>
> I don't disagree, I think I interpret the name "unversioned" a lot less
> literally than you. I expect all the things in "unversioned" need new homes
> eventually. I.e., it means not-versioned-yet, we'll be carrying these
> things for a long time.
>
> Maybe we can talk about the category of things that are common to more
> than one group but are versionable/swappable, and where such things should
> be placed.
>

Agreed - everything part of the common implementation should be in
apiserver/common/api/v1/types.go, and we can use it to implement the
initial "we have no plans to version this" - but I still want to surface
that v1 schema into each api scheme.  The things outside the scheme have to
be v1 forever, but it doesn't mean we can't evolve status / list options
within an apiversion.

**Pull request merged**
