### PR TITLE
fix 404 url

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind documentation
/kind bug

#### What this PR does / why we need it:
fix 404 url
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soniasingla — APPROVED** [review]
/lgtm

Thanks @CaoDonghui123 for the PR 🎉

**Comment by CaoDonghui123** [comment]
ping @hasheddan @justaugustus

**Pull request closed without merging**
