### PR TITLE
Record exited container status to event

### LINKED ISSUE #38532: Events stream should include all pod state events
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Looking at http://kubernetes.io/docs/user-guide/pod-states/ we see descriptions like:

**Pod is Running, 1 container, container exits failure**
* Log failure event
* If RestartPolicy is:
    * Always: restart container, pod stays Running
    * OnFailure: restart container, pod stays Running
* Never: pod becomes Failed

However, no event gets created -- we do see an entry in the text logs:

```
I1209 21:23:48.400278    2744 manager.go:324] Container inspect result: {ID:cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223ea1419636976 Created:2016-12-09 21:23:28.18667361 +0000 UTC Path:/bin/bash A
rgs:[] Config:0xc20833e380 State:{Running:false Paused:false Restarting:false OOMKilled:false Pid:0 ExitCode:1 Error: StartedAt:2016-12-09 21:23:28.339306404 +0000 UTC FinishedAt:2016-12-09 21:23:47.40603
9157 +0000 UTC} Image:sha256:4ca3a192ff2a5b7e225e81dc006b6379c10776ed3619757a65608cb72de0a7f6 Node:<nil> NetworkSettings:0xc208bc6200 SysInitPath: ResolvConfPath:/var/lib/docker/containers/234f6db095d8424
a4005daa116a28e0a0aa1f21a4428b931d4b9d07458792906/resolv.conf HostnamePath:/var/lib/docker/containers/234f6db095d8424a4005daa116a28e0a0aa1f21a4428b931d4b9d07458792906/hostname HostsPath:/var/lib/kubelet/p
ods/99f39b1b-be55-11e6-a1d4-0050563039c2/etc-hosts LogPath:/var/lib/docker/containers/cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223ea1419636976/cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223e
a1419636976-json.log Name:/k8s_ubu.9b7609c8_ubu-4125056288-716pr_default_99f39b1b-be55-11e6-a1d4-0050563039c2_0dd3797d Driver:aufs Mounts:[{Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-00505
63039c2/containers/ubu/0dd3797d Destination:/dev/termination-log Driver: Mode: RW:true} {Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-0050563039c2/volumes/kubernetes.io~secret/default-token-
whb42 Destination:/var/run/secrets/kubernetes.io/serviceaccount Driver: Mode:ro RW:false} {Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-0050563039c2/etc-hosts Destination:/etc/hosts Driver:
Mode: RW:true}] Volumes:map[] VolumesRW:map[] HostConfig:0xc2090b58c0 ExecIDs:[] RestartCount:0 AppArmorProfile:}
```

... but nothing appears in "get events".

Note: I see a few seeminly-related tickets, eg #37616 #5927 #6014 -- but as far as I can tell, they all seem to be focused on specific types of errors, and some focus on "get pod" output... I'm not sure there's a ticket to track all pod state events from http://kubernetes.io/docs/user-guide/pod-states/ to appear in the events stream.

### PR DESCRIPTION
**Pull request by resouer**
**What this PR does / why we need it**:

This path added container exit as a event to report.

**Which issue this PR fixes**

Fixes #38532

Ref #37616

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot kops aws e2e test this

**Comment by smarterclayton** [comment]
This doesn't seem unreasonable.

**Comment by smarterclayton** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by yujuhong** [comment]
@resouer how do you make sure that kubelet won't report the same event multiple times?

**Comment by resouer** [comment]
@yujuhong I once thought continually reporting as expected, now I realized I made mistake: user may rely on this event to decide when/how their container exited. 

I once thought about using pleg to drive this event report (may need add an extra flag in runtime.SyncPod() ), is it reasonable?

**Comment by yujuhong** [comment]
> I am thinking about using pleg to drive this event report (will need to pass pleg event to runtime.SyncPod() ), is it reasonable? In the future, we can also use this event to drive container start event etc.

Yes, and I believe there is an old issue about this exactly. There are tricky parts such as that pod workers won't start syncing until the cache is up-to-date (newer than the last sync). You might need to figure out if it's possible to emit events before syncing.

But overall, this PR would not achieve what you want. Maybe we can close this and tackle it a different way (through pleg?) :-)

**Comment by resouer** [comment]
@yujuhong yes, close this since it does not solve the original issue

**Pull request closed without merging**
