### PR TITLE
[Cherry-pick] Validate names in BeforeCreate

### PR DESCRIPTION
**Pull request by liggitt**
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/15975

### CODE REVIEW

**Comment by liggitt** [comment]
@caesarxuchao cherry picked into 1.1 branch, PTAL

**Comment by caesarxuchao** [comment]
Thanks. LGTM. 

Could you run hack/cherry_pick_pull.sh to generate the CP next time? That makes CP easier to generate and easier to find later.

**Comment by liggitt** [comment]
I did run it, and the script did nothing on my repo. I have (as far as I know) a standard setup (upstream -> kubernetes, origin -> my fork, etc)

**Comment by caesarxuchao** [comment]
If you can copy-paste the output it would be helpful :)

**Comment by bgrant0607** [comment]
Shippable was flake. Merging.

**Pull request merged**
