### PR TITLE
remove submit-queue from readme

### PR DESCRIPTION
**Pull request by BenTheElder**
**What this PR does / why we need it**: removes the defunct submit-queue widget from the root README.md

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**: We're on https://prow.k8s.io/tide now :-)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by tao12345666333 — APPROVED** [review]
lgtm

**Comment by cblecker** [comment]
/lgtm
/priority critical-urgent

/assign @bgrant0607 @brendandburns @dchen1107 @jbeda @lavalamp @smarterclayton @thockin @wojtek-t 
for approval

**Pull request merged**
