### PR TITLE
WIP: primaryRepresentation in resource discovery

### PR DESCRIPTION
**Pull request by sttts**
**Based on** https://github.com/kubernetes/kubernetes/pull/41313

Example for cohabitation:
- extensions/jobs:
```json
    {
      "name": "jobs",
      "namespaced": true,
      "kind": "Job",
      "verbs": [
        "LIST",
        "POST",
        "DELETECOLLECTION",
        "WATCHLIST",
        "GET",
        "PUT",
        "PATCH",
        "DELETE",
        "WATCH",
        "LIST",
        "WATCHLIST"
      ],
      "primaryRepresentation": "batch/jobs",
    },
```
- batch/jobs:
```json
{
      "name": "jobs",
      "namespaced": true,
      "kind": "Job",
      "verbs": [
        "LIST",
        "POST",
        "DELETECOLLECTION",
        "WATCHLIST",
        "GET",
        "PUT",
        "PATCH",
        "DELETE",
        "WATCH",
        "LIST",
        "WATCHLIST"
      ],
      "primaryRepresentation": "batch/jobs",
    },
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36904)

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts verbs are an easy/obvious win.  Exposing our storage details through a REST API discovery is less obvious to me.  Can we split them so I can merge one without the other?

**Comment by sttts** [comment]
@deads2k which storage details do you mean?

**Comment by deads2k** [comment]
> @deads2k which storage details do you mean?

Cohabitation is a relic of the storage underlying the two API resources that has created the relationship.  Exposing it through a discovery doc may seem convenient, but I'm not certain that we should do it and I'm likely to have additional comments on its shape (priority list of matches perhaps?).

My only real comment on the verbs is that I want them to match the logical kube verbs: get,list,watch,create,delete,deletecollection,patch,update.  Those verbs are used to create authorization policy rules.

**Comment by liggitt** [comment]
my vote would be to not expose cohabitation details in discovery

**Comment by deads2k** [comment]
@sttts this got superceded for verbs and we decided that exposing our storage details (which resources cohabitate) wasn't strictly necessary, right?

**Comment by sttts** [comment]
@deads2k yes, verbs are done. Not sure about cohabitation. Some controllers will see objects multiple times possibly (namespace, gc?).

**Comment by deads2k** [comment]
> @deads2k yes, verbs are done. Not sure about cohabitation. Some controllers will see objects multiple times possibly (namespace, gc?).

They might run slower, but they ought not break entirely.

**Comment by sttts** [comment]
Yes. Nothing urgent.

**Comment by liggitt** [comment]
I'd prefer to wait on exposing storage destinations in discovery

**Comment by sttts** [comment]
This is not really about storage destination, but about defining one Kind as the primary one and the others as secondary.

**Comment by lavalamp** [comment]
I think we *will* need to expose which resources live in the same namespace (for the GC, so it doesn't have multiple entries in its graph). We don't need to combine that with this, though. And I find "secondaryCohabitent" as a bool very confusing, I would expect something more like `sameKeyspaceAs: "fully/qualified/nameofotherresource"`.

**Comment by sttts** [comment]
@lavalamp to which does `sameKeyspaceAs` point if there are more than 3 cohabitants? To some "primary" cohabitant again? Having a single `sameKeyspaceAs` destination feels underspecified.

**Comment by smarterclayton** [comment]
In all the cases I've had to deal with this (storage migration) I wanted the resource to point me to the object that is the primary (so I could dedup this against other arguments provided by a user).  A user who runs

    oadm migrate --include=cronjob --exclude=scheduledjob

deserves an error.  A user who runs 

    oadm migrate --include=scheduledjob [--exclude cronjob]

(where cronjob is a default exclude) would expect cronjob to be updated.

**Comment by smarterclayton** [comment]
I don't like cohabitant as a term, would suggest something like `primaryRepresentation: gr or gvr` or `alternateRepresentationOf` or something.  One of the resources in all the examples I'm familiar with is the "main dude", and the rest are useful but not the normal endpoint.

**Comment by sttts** [comment]
Both `primaryRepresentation` and `alternateRepresentationOf` sound good, with the invariant that all secondaries point to the same primary and the primary itself does not have set this field.

**Pull request closed without merging**
