### PR TITLE
Remove hyperkube from release artifacts

### PR DESCRIPTION
**Pull request by dims**
Related to https://github.com/kubernetes/kubernetes/issues/81760

Just like what we did with cloud-controller-manager, this serves as a signal for folks that `hyperkube` will go to a new repository and will no longer be available from k/k.

Change-Id: Ie09248d6fc688ffffbeb0271824817a5129346a0

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
hyperkube will now be available in a new github repository and will not be included in the kubernetes release from 1.17 onwards
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/approve

**Comment by jbeda** [comment]
/approve

*sigh* I had dreams for hyperkube but never made it happen.

**Review by cblecker — APPROVED** [review]
/lgtm
/approve
/hold

@kubernetes/release-engineering: FYI -- this will change the release artifacts.

**Comment by dims** [comment]
@justaugustus @tpepper PTAL and remove `/hold` if appropriate.

**Comment by justaugustus** [comment]
Thanks for pouncing on this, @dims!
/lgtm
/approve
/hold cancel

**Comment by tallclair** [comment]
This PR left some hyperkube files behind, notably:

- https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube
- https://github.com/kubernetes/kubernetes/tree/master/build/debian-hyperkube-base

Is it safe to remove those directories now? If not, what is the roadmap for migrating them out?

My interest in the matter is that debian-hyperkube-base is super stale and full of CVEs.

**Comment by justaugustus** [comment]
@tallclair -- Allow me to look into this.

**Comment by justaugustus** [comment]
> Is it safe to remove those directories now? If not, what is the roadmap for migrating them out?

@tallclair -- Dims is working on this in https://github.com/kubernetes/kubernetes/pull/88676

**Pull request merged**
