### PR TITLE
Automated cherry pick of #16287 #16546

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #16287 #16546 on release-1.1.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
This should enable jenkins unit/integration to run on the 1.1 branch. @k8s-bot unit test this

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
Looks like [release-1.1](http://kubekins.dls.corp.google.com/view/CI%201.1/job/kubernetes-build-1.1/) is currently broken. cc @k8s-oncall.

**Comment by krousey** [comment]
Looking in to it

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by jlowdermilk** [comment]
Bleh. Mistake in dockerfile test env. I need to redo.

**Pull request closed without merging**
