### PR TITLE
Ansible rework for Kubernetes cluster deployment

### PR DESCRIPTION
**Pull request by jeffbean**
This PR is an effort to get Kubernetes cluster running with Ansible. 

Added addon services
Added flannel network setup
Updated components with kubeconfig files
Updated defaults to include new configuration options
Fixed minions to nodes

### CODE REVIEW

**Comment by jeffbean** [comment]
@eparis

**Comment by eparis** [comment]
changes are entirely inside contrib/ansible so no 1.0 risk.

**Comment by eparis** [comment]
ok to test

**Comment by roberthbailey** [comment]
@eparis can you comment as to why you removed the cla:no label?

**Comment by eparis** [comment]
Because the only 2 committers were me and jeffbean.  According to the bot both of whom have signed the cla.  Jeff Bean is clearly ok with these commits, since it is his PR. I am also ok. Which means the bots question is resolved and CLA is yes.

**Comment by roberthbailey** [comment]
Thanks for the clarification (sometimes the bot has trouble when a PR has commits from multiple folks).

**Comment by roberthbailey** [comment]
Assigning to @alex-mohr

**Comment by roberthbailey** [comment]
Can you squash your commits?

**Comment by eparis** [comment]
every commit is a clean defined single feature. in fact, he could reasonable send (almost) every single one of these as it's own PR...  Why do we have a policy to squash? It ruins git bisect....

**Comment by roberthbailey** [comment]
@eparis - In the past I've seen PRs with a bunch of commits that are very disorganized. Looking more closely at these commits, I agree that the majority of them stand alone quite well.

**Pull request merged**
