### PR TITLE
Add API version apps/v1, and bump DaemonSet to apps/v1

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: https://github.com/kubernetes/features/issues/484

**Special notes for your reviewer**: @kubernetes/sig-apps-api-reviews 

**Release note**:

```release-note
Add API version apps/v1, and bump DaemonSet to apps/v1
```

### CODE REVIEW

**Comment by janetkuo** [comment]
```
W0928 21:58:04.880]   File "/var/lib/jenkins/workspace/pull-kubernetes-unit/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 111, in <module>
W0928 21:58:04.880]     main(ARGS.branch, ARGS.script, ARGS.force)
W0928 21:58:04.880]   File "/var/lib/jenkins/workspace/pull-kubernetes-unit/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 61, in main
W0928 21:58:04.880]     raise ValueError(branch)
W0928 21:58:04.880] ValueError: feature-workload-ga
E0928 21:58:04.883] Command failed
```
test-infra refuses to run tests against `feature-workload-ga` branch

**Comment by janetkuo** [comment]
Switched the base branch back to `master` just to make sure tests all pass.

**Comment by janetkuo** [comment]
I opened #53278 that targets `master` branch in case this one (targeting features branch) falls through.

**Comment by enisoc** [comment]
If the PR tests pass on the one targeting master, would that be good enough to manually merge this one so we can continue working on the test-infra issues without blocking the feature branch experiment?

**Comment by janetkuo** [comment]
@enisoc the auto-generated codes (the last commit) are not up-to-date.  If we're fine with that we can manually merge this one.  We need to auto-generate codes when merging feature branch to master anyways.  

My only concern is that it's hard to verify if tests pass in each PR in the feature branch now.

**Comment by janetkuo** [comment]
Superseded by #53278

**Pull request closed without merging**
