### PR TITLE
Automated cherry pick of #70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #70954 on release-1.11.

#70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/approve 
For cluster/gce.

**Comment by qingling128** [comment]
Hi @feiskyer, could you help with the  `cherry-pick-not-approved` label?

This PR is about updating a Stackdriver related addon only.

**Comment by feiskyer** [comment]
@foxish should be the right approval for release-1.11.
/unassign
/assign @foxish

**Comment by qingling128** [comment]
Hi @foxish, could you help review this PR when you have a sec?

**Pull request merged**
