### PR TITLE
Bump github.com/docker/go-units dependency

### PR DESCRIPTION
**Pull request by fabianofranz**
**What this PR does / why we need it**: Bump [github.com/docker/go-units](https://github.com/docker/go-units/) to include https://github.com/docker/go-units/pull/22 which improves the precision of human durations ("about an hour ago", "2 days ago", etc).

**Which issue this PR fixes**: Issue detected in OpenShift: https://github.com/openshift/origin/issues/11967

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@kubernetes/kubectl

**Comment by soltysh** [comment]
@k8s-bot test this flake https://github.com/kubernetes/kubernetes/issues/27680

**Comment by soltysh** [comment]
The change itself lgtm.

**Comment by fabianofranz** [comment]
@k8s-bot test this flake https://github.com/kubernetes/kubernetes/issues/27680

**Comment by fabianofranz** [comment]
@k8s-bot kops aws e2e test this

**Comment by fabianofranz** [comment]
@k8s-bot test this flake https://github.com/kubernetes/kubernetes/issues/32947

**Comment by soltysh** [comment]
@k8s-bot node e2e test this

**Pull request merged**
