### PR TITLE
Refactor calculate inter pod affinity priority function

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:
Ref #24246. exactly ref https://github.com/kubernetes/kubernetes/issues/51455, the PR aim to unify priority functions(deprecated) by using map/reduce pattern. 
Previous related PR is https://github.com/kubernetes/kubernetes/pull/51192 (merged)
Previous related PR is https://github.com/kubernetes/kubernetes/pull/56317 (merged)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This is the last PR to fix  issue #24246 or  #51455

**Special notes for your reviewer**:
1) use a global/public data place to save the node score since each node not only computes its own score, and after run Reduce function we will cleanup/reinit the global/public data pointer.
2) change `HostPriorityList `from **slice struct** to **slice \*struct**,  this is  because we can't get the raw correct score for each node  until all nodes finished computing process(Map). exactly at [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L561)
3. add the filtered node list to priority meta data.

**Release note**:

```release-note
None

```

### CODE REVIEW

**Comment by guangxuli** [comment]
hi @wojtek-t this the last PR for issue #51455,  the previous PR #56317 is ready to review if you have time slot.

**Comment by guangxuli** [comment]
@wojtek-t Do you have time to review this, the PR  is the last one for these series. `CalculateInterPodAffinityPriority` is tricky, so the refactor method is different from other ones more or less.

**Comment by guangxuli** [comment]
kindly ping @wojtek-t  do you have time slot to review this PR.

**Comment by guangxuli** [comment]
ping @bsalamat @wojtek-t @k82cn @resouer

**Comment by k82cn** [comment]
sorry for the delay, i will take some time to review this if none has time :)

**Pull request closed without merging**
