### PR TITLE
Use the namespace of the pod when creating the mirror.

### PR DESCRIPTION
**Pull request by brendandburns**
@dchen1107 @yujuhong

### CODE REVIEW

**Comment by thockin** [comment]
LGTM #1

**Comment by brendandburns** [comment]
(Context, this is necessary to move the fluentd pods into a different namespace)

**Comment by dchen1107** [comment]
LGTM and thanks!

**Comment by yujuhong** [comment]
I think this was left out when changing to use non-default namespaces for mirror pods. Thanks for fixing it!

**Pull request merged**
