### PR TITLE
Revert "Parallelize RC deletion in density test"

### PR DESCRIPTION
**Pull request by mborsz**
Reverts kubernetes/kubernetes#67712

2k test has failed because of this: even if we trigger removal in parallel, controller manager is deleting replicacontrollers sequentially:
```
I0823 13:35:41.906] Aug 23 13:35:41.906: INFO: Terminating { ReplicationController} density43650-0-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 1m0.00118401s
I0823 13:36:42.021] Aug 23 13:36:42.020: INFO: Terminating { ReplicationController} density43650-14-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 2m0.00202238s
I0823 13:37:42.056] Aug 23 13:37:42.055: INFO: Terminating { ReplicationController} density43650-8-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 3m0.004624139s
I0823 13:38:42.092] Aug 23 13:38:42.092: INFO: Terminating { ReplicationController} density43650-5-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 4m0.000797258s
I0823 13:39:32.095] Aug 23 13:39:32.095: INFO: Terminating { ReplicationController} density43650-4-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 4m50.000689353s
I0823 13:40:32.206] Aug 23 13:40:32.206: INFO: Terminating { ReplicationController} density43650-11-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 5m50.000731007s
I0823 13:41:32.206] Aug 23 13:41:32.206: INFO: Terminating { ReplicationController} density43650-7-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 6m50.000648956s
I0823 13:42:32.194] Aug 23 13:42:32.194: INFO: Terminating { ReplicationController} density43650-12-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 7m50.001155426s
I0823 13:43:32.282] Aug 23 13:43:32.282: INFO: Terminating { ReplicationController} density43650-10-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 8m50.000739417s
I0823 13:44:16.434] W0823 13:44:16.433780    7517 reflector.go:270] k8s.io/kubernetes/test/utils/pod_store.go:56: watch of *v1.Pod ended with: too old resource version: 624915 (659380)
I0823 13:44:32.282] Aug 23 13:44:32.282: INFO: Terminating { ReplicationController} density43650-9-584f5bb0-a6d6-11e8-b145-0a580a3c6f08 pods took: 9m50.000486689s
I0823 13:44:42.283] Aug 23 13:44:42.282: INFO: Unexpected error occurred: error while waiting for pods to become inactive density43650-2-584f5bb0-a6d6-11e8-b145-0a580a3c6f08: timed out waiting for the condition
I0823 13:44:42.331] Aug 23 13:44:42.331: INFO: Unexpected error occurred: error while waiting for pods to become inactive density43650-1-584f5bb0-a6d6-11e8-b145-0a580a3c6f08: timed out waiting for the condition
I0823 13:44:42.333] Aug 23 13:44:42.332: INFO: Unexpected error occurred: error while waiting for pods to become inactive density43650-6-584f5bb0-a6d6-11e8-b145-0a580a3c6f08: timed out waiting for the condition
I0823 13:44:42.334] Aug 23 13:44:42.333: INFO: Unexpected error occurred: error while waiting for pods to become inactive density43650-13-584f5bb0-a6d6-11e8-b145-0a580a3c6f08: timed out waiting for the condition
I0823 13:44:42.437] Aug 23 13:44:42.436: INFO: Unexpected error occurred: error while waiting for pods to become inactive density43650-3-584f5bb0-a6d6-11e8-b145-0a580a3c6f08: timed out waiting for the condition
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
Instead of reverting I think we can fix this by controlling parallelism. We can still be saving 20% of the time by deleting in batches of 5 RCs, which is safe given that GC throughput is 50 pods/s and timeout for each RC deletion is 10 mins. Wdyt?

**Comment by wojtek-t** [comment]
> Instead of reverting I think we can fix this by controlling parallelism. We can still be saving 20% of the time by deleting in batches of 5 RCs, which is safe given that GC throughput is 50 pods/s and timeout for each RC deletion is 10 mins. Wdyt?

I think the gain is so negligible that it's not really worth it.

/hold cancel

**Comment by shyamjvs** [comment]
It should cut ~15 mins on density test on 5k-node (the whole density test takes ~150 mins) - so that's about 10% of time and lesser waiting :)

**Comment by wojtek-t** [comment]
> It should cut ~15 mins on density test on 5k-node (the whole density test takes ~150 mins) - so that's about 10% of time and lesser waiting :)

How?
From: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/192/build-log.txt:

```
I0810 09:46:01.878] [1mSTEP[0m: Deleting created Collections
...
I0810 10:37:57.982] Aug 10 10:37:57.982: INFO: Terminating { ReplicationController} density116490-38-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000663712s
I0810 10:41:08.177] [AfterEach] [sig-scalability] Density
```

So 9:46 -> 10.47: 51 minutes.

From QPS limitation, you get: 150000pod / 50pods/s = 3000s = 50m.

That will give us 1 minute (or be more more specific: 1m56s in this case).

That is negligible.

**Comment by shyamjvs** [comment]
I don't think so. So look at the following logs:

```
I0810 09:46:01.878] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:47:02.338] Aug 10 09:47:02.337: INFO: Terminating { ReplicationController} density116490-0-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000702399s
I0810 09:47:22.339] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:48:22.974] Aug 10 09:48:22.974: INFO: Terminating { ReplicationController} density116490-1-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.001315661s
I0810 09:48:42.974] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:49:43.412] Aug 10 09:49:43.412: INFO: Terminating { ReplicationController} density116490-2-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000663371s
I0810 09:50:03.413] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:51:03.794] Aug 10 09:51:03.794: INFO: Terminating { ReplicationController} density116490-3-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000605506s
I0810 09:51:23.796] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:52:24.182] Aug 10 09:52:24.181: INFO: Terminating { ReplicationController} density116490-4-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000767084s
I0810 09:52:44.182] [1mSTEP[0m: Cleaning up only the { ReplicationController}, garbage collector will clean up the pods
bla bla..
I0810 09:53:44.569] Aug 10 09:53:44.568: INFO: Terminating { ReplicationController} density116490-5-fccbef4c-9c75-11e8-96ee-0a580a3c08e0 pods took: 1m0.000690482s
```

Notice above that the deletion time for pods of a single RC (of size 3000) is 60s (also what calculations show). However there is an extra 20s constant time overhead, which is coming from [here](https://github.com/kubernetes/kubernetes/blob/7b2fa0a21f2f82dcc9b424d8f0f634e0263cb403/test/e2e/framework/util.go#L3138) which iiuc is waiting for final 'pod object delete' (to be issued by kubelet) and that one is parallelizable.

**Comment by shyamjvs** [comment]
And so, since we'd be saving 20s out of 80s (that's 25%), we should be saving ~13 mins on those 51 mins.

**Pull request merged**
