### PR TITLE
Merge head docs back into the release branch.

### PR DESCRIPTION
**Pull request by brendandburns**
@bgrant0607 @lavalamp @thockin

### CODE REVIEW

**Comment by lavalamp** [comment]
there's some contrib/mesos changes in here still...

**Comment by thockin** [comment]
gendocs fails

**Comment by bgrant0607** [comment]
I don't know how much we care about contrib.

It looks like some files must have been reverted? For example, the following commit is listed but the file it modified is not in the file list:
https://github.com/brendandburns/kubernetes/commit/c5cfc9cb9ef438625c4a2f918f877351481bddb5

gendocs should fail because none of the kubectl changes are here.

**Comment by lavalamp** [comment]
Exclude 914b6fe?

**Comment by lavalamp** [comment]
And exclude eb60bd9

**Comment by lavalamp** [comment]
Yeah, Brendan, if you produced this by reverting stuff you didn't want, that's potentially going to make future cherry picks hell. Please don't do it that way; instead just keep `git rebase -i`ing and removing the changes you don't want from that.

**Comment by lavalamp** [comment]
also exclude 3dad5a0.

It's not the end of the world if these make it in but it would mean that our official release branch has contrib/ in a weird state, which seems bad.

**Comment by lavalamp** [comment]
hm... I gave it a shot myself. lots of merge conflicts. Need to remove the changes that modify the docs in the release branch, then put this stuff in. I'll try that.

**Comment by lavalamp** [comment]
@brendandburns I believe my #11656 is correct, but it needs the versioning change applied to the docs. How did you do that without @nikhiljindal's script?

**Comment by lavalamp** [comment]
OK, #11656 is ready to go, I think. Please use that instead of this.

**Comment by zmerlynn** [comment]
FWIW, Git is pretty tolerant about 3-way merges, so I'm not sure where this is coming from:

|  if you produced this by reverting stuff you didn't want, that's potentially going to make future cherry picks hell

**Comment by zmerlynn** [comment]
Let's go with #11656.

**Pull request closed without merging**
