### PR TITLE
Add creation timestamp as an option for the downward API

### LINKED ISSUE #123519: Consider exposing node metadata.creationTimestamp via downward api
### What would you like to be added?

A pod's metadata.creationTimestamp would be useful information inside a container. This could be accomplished via downward API similar to other metadata currently available.

### Why is this needed?

Consider a cronjob execution. When executed, the cronjob creates a job, and the job creates a pod with container(s). 
If the containers' logic depends on the time the cronjob was scheduled having the pod creationTime would be more useful than simply obtaining the current time.

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add the ability for a user to expose metadata.creationTimestamp as a field for the downward api.
#### Which issue(s) this PR fixes:

Fixes #123519

#### Does this PR introduce a user-facing change?

```release-note
Add creation timestamp as an option for the downward API
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
Tested:

```
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-downwardapi-volume-example
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: client-container
      image: registry.k8s.io/busybox
      command: ["sh", "-c"]
      args:
      - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
          sleep 5;
        done;
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "timestamp"
            fieldRef:
              fieldPath: metadata.creationTimestamp
```
And confirmed that we use the creationTimestamp with this PR.

**Comment by kannon92** [comment]
/hold

Mostly up for discussion if this is valid. Was curious about how we expose fields to downward API.

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Add creation timestamp as an option for the downward API
+Added Pod creation timestamp as data source for the downward API
+(taken from `.metadata.creationTimestamp`)
```

**Comment by sftim** [comment]
If we merge this, remember to update associated docs.

**Comment by thockin** [comment]
Unfortunately, I think we need to treat this as we would any other validation change.  That means a gate (disabled) + "gate-enabled || already-used" checks in validation.

Otherwise a user could use it and then roll back to a version which doesn't allow it, thus failing validation.

**Comment by kannon92** [comment]
@thockin do you think something like CEL could be useful here? It would be nice to allow other metadata fields if someone needs them. But I wonder if one-by-one addition may be a bit much.

Plus I think this probably should use a KEP if we are following skew and support.

**Comment by thockin** [comment]
Yes this needs a KEP.

Yes, if we are going to go thru the pain of adding one, we should see if there are others that _obviously_ make sense.  We don't really want this to be a free-form field-selector (e.g "spec.volumes[3].name") because a) the API is versioned and field-paths are version-specific (so at least we would need users to pass an API version); b) any non-trivial field wants some formatting (e.g. comma-seperated vs newlines); c) speculative APIs always end badly.  We can leave a cleaner path for future, extensions, though.

I don't know what you mean with CEL - do you mean to use it as a template language to format strings?  I don't think CEL can do that.  Or do you mean something else?

Also, see https://github.com/kubernetes/kubernetes/issues/119567 - a well supported sidecar pattern makes all of this irrelevant.

**Comment by kannon92** [comment]
For CEL, @thockin I realize I don't really know what it is. I was thinking that it would be nice to have a custom language in YAML and we support that for downward API. I realize that it is probably impossible as we are changing validation and adding code in a few places so its not likely to be open-ended.

**Pull request closed without merging**
