### PR TITLE
Fix logsForObjectWithClient tests

### PR DESCRIPTION
**Pull request by tnozicka**
**What type of PR is this?**
/kind bug
(for https://github.com/kubernetes/kubernetes/pull/74346 fixing a bug that need this fixed)

/kind cleanup

**What this PR does / why we need it**:
Prereq to https://github.com/kubernetes/kubernetes/pull/74346 but I wanted the test change to go through CI separately proving it works with the existing `GetPodLogs` behaviour before shipping new version of that function which could also change the outputs.

**Special notes for your reviewer**:
We should not test client actions, but the result. Client actions are flake if you use asynchronous processing and properly handle all the watch issues like doing LIST+WATCH. Doing that asynchronously and comparing actions is a flake trap. Also testing the actual resulls seems more correct to me.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @soltysh

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by deads2k** [comment]
ok, I think I follow the chain.  We want a resilient `oc logs`, so we need to make changes, so we need to fix these tests, so we need to fix the the fake client.

/approve
/hold

please squash, then remove the hold.

**Comment by tnozicka** [comment]
squashed 
/hold cancel

**Comment by tnozicka** [comment]
misunderstood which commits to squash, the bazel one is intentionally its own commit because it contains **generated** code

**Comment by deads2k** [comment]
> misunderstood which commits to squash, the bazel one is intentionally its own commit because it contains **generated** code

We don't normally splash the log with bazel commits.  For large enough refactors, it makes sense.  For three lines, it does not.

**Comment by tnozicka** [comment]
I believe even a single line of generated code goes into a separate commit. 

Also I have to separate commit before this one. Putting related BUILD changes correctly to a commit would assume I start sorting parts of the generated code manually to a particular commit that might have caused it or running interactive rebase and regenerating Bazel at every step of the way, every rebase I do while developing it. That seems crazy to do correctly. Rules should not differ by number of commits.

This is worth twice as much for Bazel which isn't deterministic generator and you have to manually reset content of every affected `BUILD` file to the merge-base commit content when cherry-picking it for older branches to be able to regenerate it correctly to match CI. Isn't it much cleaner not to couple commits that are pickable with those that by definition aren't? You may get lucky but process decisions should work in general, not only on happy path. Avoiding conflicts is worth the commit, if people are not doing it regularly they are probably not aware of the complications that can arise for backports, or don't care.

**Pull request closed without merging**
