### PR TITLE
Moves networking e2e tests to test/e2e/network

### PR DESCRIPTION
**Pull request by bowei**
This also adds sig-network-{approvers,reviewers} alias

### CODE REVIEW

**Comment by bowei** [comment]
@grodrigues3

**Comment by xiangpengzhao** [comment]
We also should add prefix `[sig-network]` to all of our tests. See 49161. However, it can be another PR. If you don't have cycles, I can take it after this one merged.

**Comment by grodrigues3** [comment]
@bowei if you rebase, we can have @xiangpengzhao take over the prefix adding part.

**Comment by xiangpengzhao** [comment]
@bowei have any bandwidth to rebase and resolve the conflicts?

**Comment by wojtek-t** [comment]
@bowei - please fix bazel and verify - those seems to be real issues.

**Comment by bowei** [comment]
@wojtek-t yes, fixing :-)

**Comment by xiangpengzhao** [comment]
@bowei The test failure was due to removing `staging/src/k8s.io/sample-apiserver/pkg/registry` from `hack/.golint_failures` in your PR.

We can either move it back or fix the lint error as below.

```
I0722 00:07:41.415] Verifying hack/make-rules/../../hack/verify-golint.sh
W0722 00:08:36.872] Errors from golint:
W0722 00:08:36.873] staging/src/k8s.io/sample-apiserver/pkg/registry/registry.go:36:20: error strings should not be capitalized or end with punctuation or a newline
W0722 00:08:36.873] 
W0722 00:08:36.873] Please review the above warnings. You can test via "golint" and commit the result.
W0722 00:08:36.873] If the above warnings do not make sense, you can exempt this package from golint
W0722 00:08:36.873] checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
W0722 00:08:36.873] 
I0722 00:08:36.974] FAILED   hack/make-rules/../../hack/verify-golint.sh	55s
```

**Comment by bowei** [comment]
@wojtek-t lgtm and approval

**Pull request merged**
