### PR TITLE
Print API latency metrics as perfdata

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by shyamjvs** [comment]
We also need to add "Count" field in the metrics, otherwise this would break the benchmark tool.

**Comment by gmarek** [comment]
Good catch. Added as a label.

**Comment by shyamjvs** [comment]
Also could you do something similar even for pod startup latency (probably verb="pod startup" and resource="")? Just sso we have uniformity.

**Comment by shyamjvs** [comment]
Because IIUC they'll still be printed without units and in the old pattern.

**Comment by gmarek** [comment]
You mean convert PodStartupLatencies type to PerfType? Sure but this is out of scope of this PR.

**Comment by shyamjvs** [comment]
/lgtm

Yes. We can do that in a separate PR.

**Comment by gmarek** [comment]
@kubernetes/test-infra-maintainers - bazel isn't happy today.

**Comment by gmarek** [comment]
There was some regression in the head around openapi. I synced and pushed to try again.

**Pull request merged**
