### PR TITLE
Rename ContainerStatus.ResourcesAllocated to ContainerStatus.AllocatedResources

### PR DESCRIPTION
**Pull request by vinaykul**
#### What type of PR is this?
/kind cleanup
/kind api-change

#### What this PR does / why we need it: 
Renaming ContainerStatus.ResourcesAllocated to ContainerStatus.AllocatedResources makes it consistent with PVCStatus.AllocatedResouces without change of meaning for in-place pod resize.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by vinaykul** [comment]
/skip pull-kubernetes-e2e-gce-cos-alpha-features
Not required, job is unhealthy and failing for other reasons. In-place resize e2e tests passed with containerd/main in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116450/pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2/1634228348827734016

**Comment by vinaykul** [comment]
/assign @ harshanarayana @palnabarun @dims @cici37
Please review CHANGELOG fix

**Comment by vinaykul** [comment]
/assign @harshanarayana @palnabarun @dims @cici37

Please review CHANGELOG fix

**Comment by jeremyrickard** [comment]
@vinaykul  does this need a release note?

**Comment by vinaykul** [comment]
> @vinaykul does this need a release note?

This particular PR? no. 
The main PR https://github.com/kubernetes/kubernetes/pull/102884 this is updating based on an [API review discussion last night](https://kubernetes.slack.com/archives/CJUQN3E4T/p1678401527788819) does need release note, and has placeholder PRs for blog and docs as well.

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
