### PR TITLE
fix: Fix out of index error cause by the thread safe problems in shared_informer.go

### LINKED ISSUE #106003: RingGrowing readable will be negative, which leads `index out of range`
### What happened?

When I restart my pod while the cluster in high load, the restarted pod will panic. 

The stack trace told me the panic was caused by **index out of range** in `k8s.io/utils/buffer/ring_growing.go`

未命名

Then I read the source code of `k8s.io/utils/buffer/ring_growing.go`, and I found the reason.

https://github.com/kubernetes/kubernetes/blob/bb24c265ce725c90f0e82b01e7c1ccbffb695d14/vendor/k8s.io/utils/buffer/ring_growing.go#L19-L43

The comment has pointed out the `RingGrowing` is **not thread safe**.

After I add the lock to `RingGrowing` when read/write, no panic occurs again.

### What did you expect to happen?

The panic should never occur.

### How can we reproduce it (as minimally and precisely as possible)?

We have over 100k(running and completed) pods in our cluster, and it's in high load.
And we use volcano as our default scheduler.
When I restart the volcano-controller, the controller will panic.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
v1.18.2

### Cloud provider

<details>

</details>
self-host

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Zheaoli**
#### What this PR does / why we need it:
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/106003

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
I have a question/theory in https://github.com/kubernetes/kubernetes/issues/106003#issuecomment-964575994 .

**Comment by deads2k** [comment]
is the `Replace RLock by using Lock in sharedProcessor.run` commit enough to resolve this problem?  I'm happy to merge that much if it is.

**Comment by Zheaoli** [comment]
@deads2k I'm not sure if we should concern about if people use `Run` method twice or not. 

I'll update my PR first

**Comment by Zheaoli** [comment]
@deads2k ping

**Comment by dims** [comment]
/ok-to-test
/assign @liggitt 

NOTE: 2 line patch, but tricky!?

**Comment by liggitt** [comment]
While I don't particularly object to changing the RLock to a full Lock, I don't understand the theory proposed in https://github.com/kubernetes/kubernetes/issues/106003#issuecomment-964575994 ... is there a reproducer of the issue this is intending to fix?

(also, this PR needs a squash)

**Pull request closed without merging**
