### PR TITLE
kubectl: deploy generators don't need to impl Generator iface

### PR DESCRIPTION
**Pull request by alexandercampbell**
The `kubectl create deployment` generators do not need to implement the Generator interface, since they are only used as implementations of the StructuredGenerator interface. I was able to delete some tests of their Generator methods as part of this change.

### Considerations for code reviewers

1. Every other StructuredGenerator implementation implements the Generator interface in additional. My change makes the "create deployment" generators a little unusual. I've added a docstring to this effect in `util/factory_client_access.go`.
2. This significantly reduces the maintenance / testing burden for future updates to `kubectl create deployment`.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@kubernetes/sig-cli-maintainers This is a general statement about how we want to build our `kubectl create` subcommands. To my knowledge, we still haven't ever re-used one.

**Comment by mengqiy** [comment]
Overall LGTM.

I suspect if there are any places still use `Generator` interface.
If we don't use `Generator` interface any more, we can remove all related code. It will make kubectl codebase cleaner. 
cc: @pwittrock

**Comment by alexandercampbell** [comment]
I would like to delete the Generator interface because it relies so heavily on the `interface{}` type for every parameter. That said, we can't remove the Generator interface without a huge refactor to `kubectl run`.

**Comment by alexandercampbell** [comment]
Rebased. PTAL. Thanks!

**Comment by alexandercampbell** [comment]
/test pull-kubernetes-e2e-kops-aws
--

**Comment by mengqiy** [comment]
/lgtm
It seems we don't have any test coverage for deployment `StructuredGenerate`.
Anyone from @kubernetes/sig-cli-maintainers want to approve this?

**Comment by alexandercampbell** [comment]
@deads2k would you mind taking a look at this?

**Comment by deads2k** [comment]
> @deads2k would you mind taking a look at this?

I would absolutely merge this, but I have strong, pre-existing feelings about generators and I don't want to force them on sig-cli without a comment from @fabianofranz @pwittrock or @adohe

**Comment by fabianofranz** [comment]
cc @kargakis @soltysh

**Comment by kargakis** [comment]
This is fine.

**Comment by fabianofranz** [comment]
> I would like to delete the Generator interface

Yes please.

> My change makes the "create deployment" generators a little unusual.

Unusual is the new usual.

/approve no-issue

**Pull request merged**
