### PR TITLE
Sync client-go

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by deads2k** [comment]
get it green and squash, then lgtm.

**Comment by deads2k** [comment]
included in https://github.com/kubernetes/kubernetes/pull/40699

**Comment by sttts** [comment]
Why can't I reopen this pull?

**Comment by deads2k** [comment]
> Why can't I reopen this pull?

Oh, I don't care.  I just meant you'd have a shot at resyncing the client several hours before I would.

**Comment by sttts** [comment]
No I mean why can't I technically reopen it in Github? It's greyed out.

Best regards,
   Stefan

**Pull request closed without merging**
