### PR TITLE
Improve error messages and comments in KubeAdm.

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Improve error messages and comments in KubeAdm.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

@cimomo thanks for the contribution!

**Comment by fabriziopandini** [comment]
Thanks!
👍 /lgtm

**Comment by cimomo** [comment]
Thank you @xiangpengzhao and @fabriziopandini for the quick review. Does this need to be assigned to @mikedanese for additional approval?

**Comment by xiangpengzhao** [comment]
@cimomo yes. You can assign any approver listed in cmd/kubeadm/OWNERS for approval.

**Comment by cimomo** [comment]
@xiangpengzhao Thanks! Didn't realize I could do the assignment myself. :)

**Review by luxas — APPROVED** [review]
/approve no-issue

Thank you @cimomo for this contribution!

**Comment by cimomo** [comment]
Thank you @luxas !

**Pull request merged**
