### PR TITLE
Update the Go environment details in README.md

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
It's friendlier to people you don't know

**Comment by neolit123** [comment]
@xichengliudui your ideas is not bad, as often times contributors end up with the wrong version of Go.
but this also means we need to maintain this string in the main readme, while i'm pretty sure that we already print an error message from the build tools if the user uses an old version of Go.

holding for discussion.
/hold
/assign @nikhita @cblecker 
@kubernetes/sig-contributor-experience-feature-requests

**Comment by nikhita** [comment]
@xichengliudui I like the intent, but I don't think we should add this in the README. Details below.

> but this also means we need to maintain this string in the main readme, while i'm pretty sure that we already print an error message from the build tools if the user uses an old version of Go.

:+1: 

The README in this repo is just meant as "here is a quick way to run Kubernetes if you want to, but if you face problems, checkout the developer documentation in the community repo".

If someone gets an error, they should refer the developer documentation that's been linked in the README. We list the complete set of supported versions for Go there: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#go.

/close

**Comment by xichengliudui** [comment]
@nikhita  @neolit123
You're right. I've given too little thought. Thank you

**Pull request closed without merging**
