### PR TITLE
use already defined variable

### PR DESCRIPTION
**Pull request by huiwq1990**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

var reuse

#### Which issue(s) this PR fixes:

none

#### Special notes for your reviewer:

none

#### Does this PR introduce a user-facing change?

none

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
/release-note-none
/priority backlog


Thanks!

**Review by rikatz — APPROVED** [review]

**Review by janetkuo — APPROVED** [review]

**Review by brianpursley — APPROVED** [review]

**Pull request merged**
