### PR TITLE
Add CRI log format support in fluentd.

### PR DESCRIPTION
**Pull request by Random-Liu**
https://github.com/kubernetes/features/issues/286

Without this fluentd will log a lot of errors for each line, because it doesn't recognize the CRI log format.
With this PR, it could support CRI log format now. I've tried with cri-containerd.

The PR is using https://github.com/repeatedly/fluent-plugin-multi-format-parser.
This PR depends on https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/62.

@crassirostris Should I build/push image before the PR is merged? What is our process?

**Release note**:

```release-note
fluentd now supports CRI log format.
```

### CODE REVIEW

**Comment by crassirostris** [comment]
Thanks!

/lgtm
/approve no-issue

> Should I build/push image before the PR is merged?

Yes, that's fine for now

**Comment by Random-Liu** [comment]
The test is failing because the new fluentd image is not built yet. I'll build and push the image.

**Comment by Random-Liu** [comment]
@piosz Ping for approval.

**Comment by crassirostris** [comment]
@Random-Liu PR is approved, Piotr is OOO

**Comment by Random-Liu** [comment]
@crassirostris Ha... I forgot you github handler is not vmik. I checked the OWNER file and didn't see vmik. :P Thanks!

**Comment by runcom** [comment]
Awesome

**Comment by runcom** [comment]
LGTM fwiw

**Comment by mrunalp** [comment]
Nice 👍

**Comment by feiskyer** [comment]
👍

**Comment by sam-github** [comment]
Hi, I found my way here from https://github.com/ubuntu/microk8s/issues/803 via https://github.com/containerd/cri/issues/1339

I'm new to containerd/fluentd/es/kibana, so I might just be misunderstand how this works, but the first branch in this multi_format implies that fluentd can and should recognize JSON log lines.

In the second branch, introduced here, it doesn't work for me when `<log>` is itself JSON, it is just finding the text, and it shows up in elastic search as a string log message, with the string content being JSON, something like `{"level": "info", ...etc}`, but the log message is not recognized as JSON.

Am I missing something? Is there a later stage in the pipeline where CRI formatted output can be parsed into JSON?

**Pull request merged**
