### PR TITLE
code cleanup: Omit redundant nil check

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Omit redundant nil check in type assertion
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by leilajal** [comment]
/assign @yliaog 
Thanks Yu!
/triage accepted

**Comment by yliaog** [comment]
could you please clarify why nil check is redundant? when ok is true, the unk could still be nil

**Comment by HecarimV** [comment]
when ok is true, the conversion object must not be nil. ref https://staticcheck.io/docs/checks#S1020
And I've seen it used in other places without nil check, https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/configfile.go#L48-L56
Please help me to see if my judgment is correct, thanks @yliaog @lavalamp

**Comment by lavalamp** [comment]
> used in other places without nil check

only if the author knows for sure a nil cannot be stored!

> ref https://staticcheck.io/docs/checks#S1020

This is subtly different than what you are doing -- there it claims the outer interface must not be nil if a typecheck succeeds. But you are removing checks about the inner variables, there is no such guarantee about those.

**Pull request closed without merging**
