### PR TITLE
Backfill tests for CSI plugin registration

### PR DESCRIPTION
**Pull request by hoegaarden**
**What this PR does / why we need it**:

Addresses following parts of #69374 

- [x] The `RegistrationHandler.RegisterPlugin` seems to be untested
- [x] The `csiPlugin.Init` seems to be untested
- [x] Implementation pollutes global state ([CSI drivers store](https://github.com/kubernetes/kubernetes/blob/c1ad6e961a3083e109e35da1f60c85adfbbe70ce/pkg/volume/csi/csi_plugin.go#L100) and [node info manager](https://github.com/kubernetes/kubernetes/blob/c1ad6e961a3083e109e35da1f60c85adfbbe70ce/pkg/volume/csi/csi_plugin.go#L102), for example) - which prevents tests from running in isolation/in parallel. This is not 100% a test improvement (i.e. it's change in the source), but we're noting it here as part of backfilling tests/ improving test coverage.

This PR should probably rebased onto https://github.com/kubernetes/kubernetes/pull/69371 if / as soon that's merged.

**Which issue(s) this PR fixes**:

It addresses parts of https://github.com/kubernetes/kubernetes/issues/69374.

**Release note**:

```release-note
NONE
```

/sig storage
/area test
/kind cleanup (?)

/cc @kubernetes/sig-storage-pr-reviews

### CODE REVIEW

**Comment by hoegaarden** [comment]
/assign @vladimirvivien @ixdy 

@vladimirvivien 
We addressed some issues in #69374. We can continue and pushing all the points from the issue in this PR, or we can try to get this PR merged sooner and address the other points in a separate PR. What do you think? In any case: Any feedback is highly appreciated.

@ixdy 
What do you think about the proposed `./hack/generate-mocks.sh`? Is it ok to introduce a dependency on a binary like this? Or should we do something else (e.g. vendor the `counterfeiter` source and build the binary on `./hack/generate-mocks.sh`)?

**Comment by vladimirvivien** [comment]
@hoegaarden I will take a look at this PR.  Wanted to point out that you will need to contact owners (see https://github.com/kubernetes/kubernetes/pull/69462#issuecomment-430286328) in the other areas that you have modified.  

Also, can you modify the PR's description to explain why there is a need for new generator scripts (hack/generate-mock.sh).

**Comment by vladimirvivien** [comment]
@RenaudWasTaken Hi can you take a look at the PluginsWatcher section.

**Comment by vladimirvivien** [comment]
@hoegaarden there are some good changes in this PR. However, I would recommend splitting into several PRs as they deal with independent (though related) issues:
- https://github.com/kubernetes/kubernetes/pull/69371 shall be merged by the time you read this which would make this PR smaller
- Gather all Kubelet-related changes in one PR
- Gather all pkg/volume/csi related changes in another PR. This is of high interest as I have changes I want to introduce on top of the changes I see the csi_plugin.go.
- Add the mock tests for kubelet/csi in a different PR

#### Regarding mocks:
As you probably already know, there are mainly two ways of testing Kubernetes code (unit and e2e, there might be other tests frameworks used that I don't know).  Unit tests are driven by make task `make test WHAT=<package path>`.  The unit tests in this PR must be able to be driven by that make task which is exercised by CI.  I am not aware of other unit tests that use generated code as  pre-requisites (k8s is a large codebase I may be wrong).

Having said that, keep in mind the following:
- I am not the authoritative voice on this matter
- You may be able to set a new trend of using generated code unit test (you will need to convince others, hack script owners)
- You may be able include in the mock-test PR changes to `make test` to include ways to launch the generator

That is why I am suggesting to drive all mock script and related tests be added their own PR.

Again, ping me on slack for quicker responses.

**Comment by hoegaarden** [comment]
@vladimirvivien, thanks for your input! We will split that PR as you suggested.

Regarding mocks:
Yes, we are aware that tests just need to work with the mocks, ideally without a specific generation phase. What we aimed for is committing the mocks, so they won't be any different then a hand-rolled mock (in regards to running the tests and such). However, we wanted to make it super easy for other people to update them. For hand-rolled mocks I'd need to update them by hand, and commit them. For our new mocks one I can just run `~/hack/generate-mocks.sh` and commit.
Eventually we could think about having a verify script which checks if the mocks are up-to-date, but that's for later (if even necessary).

**Comment by ixdy** [comment]
Did `hack/generate-mocks.sh` get accidentally removed from this PR?

**Comment by ixdy** [comment]
The general problem with checking in generated code is that you need to also check in functionality to regenerate the code, as well as a script to verify that the checked-in code is still up-to-date.

**Comment by hoegaarden** [comment]
@ixdy Yeah, sorry about that, as @vladimirvivien suggested, we will move the things regarding the regeneration into a separate PR.

As soon as we have that PR I will ping you, if that's OK with you?

**Comment by dims** [comment]
@hoegaarden this needs rebase ... code freeze is tomorrow! ( https://github.com/kubernetes/sig-release/tree/master/releases/release-1.13 )

**Comment by msau42** [comment]
We are not targeting this PR for 1.13

**Comment by hoegaarden** [comment]
This has been superseded by:
- #70379
- #70380
- #70381 
- #70812

I forgot to close this PR, sorry about that.

**Pull request closed without merging**
