### PR TITLE
Automated cherry pick of #33803

### LINKED ISSUE #33801: Compile darwin binaries with go 1.7.1 so they stop segfaulting
See #32999

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #33803 on release-1.4.

Fixes #33801.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33857)

### CODE REVIEW

**Comment by ixdy** [comment]
cc @luxas @pwittrock @david-mcmahon @liggitt @smarterclayton @jfrazelle @Starefossen @gerred

**Comment by luxas** [comment]
LGTM

**Comment by pwittrock** [comment]
@k8s-bot kubemark e2e test this

**Comment by pwittrock** [comment]
@k8s-bot kubemark e2e test this

**Comment by pwittrock** [comment]
@k8s-bot gci gke e2e test this

**Comment by jbeda** [comment]
LGTM

**Comment by jbeda** [comment]
@k8s-bot kubemark gci gke e2e test this

**Pull request merged**
