### PR TITLE
Extend the sleep time in the NC unit test

### PR DESCRIPTION
**Pull request by gmarek**
Ref. https://github.com/kubernetes/kubernetes/issues/39975#issuecomment-284600278

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot non-cri e2e test this

**Comment by gmarek** [comment]
@k8s-bot non-cri e2e test this

**Comment by liggitt** [comment]
helps with flakiness of this test, but doesn't resolve it fully (so leaving the original issue open)

marking retest-not-required, since it's a unit test with no other interactions

**Pull request merged**
