### PR TITLE
Automated cherry pick of #14525 upstream release 1.1

### PR DESCRIPTION
**Pull request by thockin**
Add an experimental network plugin implementation named "cni" that
uses the Container Networking Interface (CNI) specification for
configuring networking for pods.

https://github.com/appc/cni/blob/master/SPEC.md

### CODE REVIEW

**Comment by brendandburns** [comment]
godeps looks busted on shippable?

**Comment by thockin** [comment]
@eparis what's the status on godeps?  Did all the fixes find their way into the 1.1. release branch?

**Comment by thockin** [comment]
godeps on release branch is suffering but that's unrelated to this PR

**Comment by brendandburns** [comment]
Manually merging to override godeps fail.

**Pull request merged**
