### PR TITLE
Clarify cpu.cfs_period_us default value

### PR DESCRIPTION
**Pull request by paskal**
cpu.cfs_period_us is 100μs by default despite having an "ms" unit for some unfortunate reason. Documentation: https://www.kernel.org/doc/html/latest/scheduler/sched-bwc.html#management

The desired effect of that change is more clarity on the default value so users would be aware that the 10ms custom value would be not 0.1x of the default but 100x of it.

Followup of the #63437, which introduced the ability to customise the value but did not do the job of clarifying the default well enough. Documentation-only counterpart of #111520.

/kind documentation

#### Does this PR introduce a user-facing change? Nope.

```release-note
Clarified the default CFS quota period as being 100µs and not 100ms.
```

### CODE REVIEW

**Comment by paskal** [comment]
cc @bobbypage @liggitt @szuecs for review.

**Comment by paskal** [comment]
Feel free to review now, tests are passing.

**Comment by paskal** [comment]
Gentle ping for approval: @Random-Liu  @dchen1107 @derekwaynecarr @yujuhong @sjenning @mrunalp @klueska.

(I hope it's the right way of doing that, I took the list from the approvers bot message as I don't know who in particular is the right person to ping. Apologies if it's not.)

**Review by endocrimes — APPROVED** [review]
/lgtm
/triage accepted
/priority important-soon

**Comment by paskal** [comment]
I was wrong, and the default value is 100ms and not 100μs: PR #112123 reverts this PR and clarifies the code to prevent mistakes about units of measurement around this feature in the future. I'll try clarifying [linked](https://www.kernel.org/doc/html/latest/scheduler/sched-bwc.html#management) kernel.org documentation as well.

Apologies for added confusion; I got the clarification from the kernel developer about the real state of things (https://github.com/kubernetes/kubernetes/pull/112108#issuecomment-1231542650) only after this was merged.

**Comment by aojea** [comment]
No worries, thanka for clarifying it

**Pull request merged**
