### PR TITLE
Fix for setting kubelet client certificate file path through kubeadm config

### LINKED ISSUE #78075: Setting kubelet client certificate file path through kubeadm config file failed
I want to set kubelet clientCA file path through command:
"kubeadm init --config=./kubeadm.yml --ignore-preflight-errors all"

Genereated kubelet config file(/var/lib/kubelet/config.yaml) always point to /etc/kubernetes/pki/ca.crt for clientCAFile option.
Kubelet process will fail unless i overide with --clientCAFile option through systemd for kubelet.

My kubeadm config file:

apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.64.57
  bindPort: 8443
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: knative
  taints: []

---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
certificatesDir: /var/lib/minikube/certs/
clusterName: kubernetes
controlPlaneEndpoint: 192.168.64.57:8443
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /data/minikube
kubernetesVersion: v1.14.1
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m2s
    enabled: true
  x509:
    clientCAFile: /var/lib/minikube/certs/ca.crt

### PR DESCRIPTION
**Pull request by pcp-dev**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR fixes setting the kubelet client certificate file path through kubeadm config file

**Which issue(s) this PR fixes**:

Fixes #78075

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

No

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Hi @prakashpc 
as @neolit123 said in the other pr it's hardcoded by design.
Let's talk on the issue before change this.

/hold

**Comment by prakashpc** [comment]
```release-note
NONE
```

**Comment by prakashpc** [comment]
> Hi @prakashpc
> as @neolit123 said in the other pr it's hardcoded by design.
> Let's talk on the issue before change this.
> 
> /hold

Hello @neolit123, @yagonobre 
Can you please refer the other PR ? why it has to hardcoded by design?

**Comment by yagonobre** [comment]
@prakashpc https://github.com/kubernetes/kubernetes/pull/78077

**Comment by prakashpc** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

signed CLA

**Comment by prakashpc** [comment]
> > Hi @prakashpc
> > as @neolit123 said in the other pr it's hardcoded by design.
> > Let's talk on the issue before change this.
> > /hold
> 
> Hello @neolit123, @yagonobre
> Can you please refer the other PR ? why it has to hardcoded by design?

@neolit123 , @yagonobre 

In my usecase, certificates are placed in the custom path. l  am using kubeadm config file to refer the  client CA file location for kubelet. I believe it is more easier way than providing the same in the systemd kubelet or kubeadm env file. It also helps me to keep all config in a single file and easy to maintain.

In my solution, still the security-related to kubelet is enforced becoz it needs valid certificate either in the custom path or default path. Anonymous access flag still disabled.

**Comment by SataQiu** [comment]
Ref: https://github.com/kubernetes/kubeadm/issues/1493
How should we deal with `clientCAFile` and `cert-dir`.
By default, `clientCAFile` should be in the `cert-dir`  folder.
If we break this rule, generating and managing certificates may become complicated.

**Comment by neolit123** [comment]
pretty sure in 1.16 we now support this. it prints a warning, but still allows the user to use custom paths.
/close

**Pull request closed without merging**
