### PR TITLE
Update description of resource-consumer version

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update description of resource-consumer version
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
 "NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
/cc @dims I think the version of the resource consumer needs to be updated.
Otherwise we don't know the latest version

**Review by yangjunmyfm192085 — COMMENTED** [review]
/remove-lifecycle stale

**Comment by aojea** [comment]
It seems the latest one is 1.14 https://github.com/kubernetes/kubernetes/blob/master/test/images/resource-consumer/VERSION , can you also please check that those commands work fine?

**Comment by yangjunmyfm192085** [comment]
> It seems the latest one is 1.14 https://github.com/kubernetes/kubernetes/blob/master/test/images/resource-consumer/VERSION , can you also please check that those commands work fine?

It seems that the 1.14 image is not in the registry

**Comment by yangjunmyfm192085** [comment]
image

**Pull request closed without merging**
