### PR TITLE
suggest homebrew when bash is too old on macOS

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**

/kind cleanup
/sig testing

**What this PR does / why we need it**: Helps developers resolve an error meeting development requirements.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
unfortunately the output can still be pretty clunky:
```console
$ make test
ERROR: This script requires a minimum bash version of 4.2, but got version of 3.2
On macOS with homebrew 'brew install bash' is sufficient.
hack/run-in-gopath.sh
ERROR: This script requires a minimum bash version of 4.2, but got version of 3.2
On macOS with homebrew 'brew install bash' is sufficient.
hack/make-rules/build.sh
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
```
(note: I injected an extra `echo $0` here to lazily trace why we were seeing this twice / what the invocations were)

but at least this points to an actionable approach to resolving the issue, there's still other issues on macOS, but I'm poking at those.

**Comment by BenTheElder** [comment]
/retest
hmmm seeing that more often
```
 - containerID: containerd://2372ffea321a2dec129d222dc4b43ee8774b4c0528a2e36d9271c6a51819b35e
    image: gcr.io/k8s-prow/initupload:v20210209-12c3370f77
    imageID: gcr.io/k8s-prow/initupload@sha256:4108bc2d7ddb6a2272d525b060d305edd5f9575430ca022ceef22475140ce713
    lastState: {}
    name: initupload
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: containerd://2372ffea321a2dec129d222dc4b43ee8774b4c0528a2e36d9271c6a51819b35e
        exitCode: 1
        finishedAt: "2021-02-10T07:02:42Z"
        message: |
          iter close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2Flatest-build.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fclone-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout upload error: writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fclone-records.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fbuild-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Ffinished.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout]","file":"prow/cmd/initupload/main.go:45","func":"main.main","level":"fatal","msg":"Failed to initialize job","severity":"fatal","time":"2021-02-10T07:02:42Z"}
        reason: Error
        startedAt: "2021-02-10T06:46:42Z"
        ```
        https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98948/pull-kubernetes-bazel-build/1359393190783750144

**Review by amwat — COMMENTED** [review]
/lgtm

**Pull request merged**
