### PR TITLE
build latest image of fluentd, use it

### PR DESCRIPTION
**Pull request by coffeepac**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
specifies new image that will support log lines truncated by docker.  fix applied in #68012 , this revs image version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by coffeepac** [comment]
@desaintmartin request sent but its late on a Friday so it probably won't get started until Monday at the earliest.

**Comment by desaintmartin** [comment]
Gentle up?

**Comment by coffeepac** [comment]
yeah, didn't think I could lgtm my own PR.  Lemme see if I can find someone to do it.

**Comment by coffeepac** [comment]
@desaintmartin there isn't a great reviewer available other then @piosz.  I will bring up adding someone else at the next sig-inst meeting.  

for now, we'll do this:
- wait until next week to see if people respond
- failing that, I'll get another reviewer added next week so this can be merged and I'll probably move image hosting to quay

**Comment by coffeepac** [comment]
@monotek you cool with closing this in favor of #71180 ?  I've gotten the attention of an engineer on call to build that image.  I can circle back and ask them to build this image as well if we need this image for historical preservation issues.

**Comment by monotek** [comment]
2.3.2 seems already there: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch?gcrImageListsize=30

So yes, lets close it :-)

**Comment by coffeepac** [comment]
work has been superceeded via #71180

**Pull request closed without merging**
