### PR TITLE
Durable data

### PR DESCRIPTION
**Pull request by erictune**
I'm not looking to actually merge this PR, just get some feedback on two possible approaches.

If there is agreement on one approach, then I will code it up, and convert this design document into user documentation.  

I'm inclined to add a new type of REST resource to model Durable local data.  I know new resources are always  controversial, so I've written this doc to compare the alternatives.  Comments welcome from anyone.  I'd particularly like comments from @dchen1107 @bgrant0607 @thockin @brendanburns @jbeda @lavalamp @smarterclayton.

Addresses #598.

### CODE REVIEW

**Comment by erictune** [comment]
I no longer believe that we should implement the durable data concept described in this PR.  Therefore I am going to close this PR. 

I now see that there are two use cases that should be handled separately:
  1. make it easy to run things that want to attach to networked, truly persistent (replicated or tape-backed-up) storage.
  1. make it possible to run things which must have local storage device access.  

Why not handle both cases with one concept?  Because the thing you end up with:
   - has muddled concepts because it is trying to model too many cases
   - adds extra API complexity (e.g. new object which is similar to but not the same as a pod, with own lifetime)
   - adds scheduler complexity (dealing with pairing durable data).
   - an attractive nuisance which reduces pod mobility, which will block lots of things (upgrades, autoscaling, rescheduling, etc.)

For the "easy to run things that want attach to networked storage" case, we should do:
  - each cluster has one or more types of networked storage available, that, to a first degree, are accessible to every minion.
  - use something like  #2598 volumes framework to extension for various networked storage solutions.
  - maybe provide a way to allow admins to export and access control subsets of those network storage soultions to users, along the general lines of #3318 
  - pods are still completely mobile (not bound to specific machines with specific local data.
  - Do some kind of hack to deal with the GCE 1 Writer limitation.
  - nfs and ceph clients are better examples of this category.

For the "possible to run things which must have local storage device access" case, we should do:
  - make a hostDir capability, and perhaps narrower capabilities to use specific file systems or devices.
  - use policy to limit which pods can use those capabilities.  In mature installations, only "infrastructure" pods would typically get that (ones which e.g. implement ceph, cassandra, hdfs, etc servers).

**Comment by erictune** [comment]
@bgrant0607 we talked just now about how I don't think we should do durable data in any of the forms previously discussed.  See my post above.

**Comment by smarterclayton** [comment]
----- Original Message -----
> I no longer believe that we should implement the durable data concept
> described in this PR.  Therefore I am going to close this PR.
> 
> I now see that there are two use cases that should be handled separately:
>   1. make it easy to run things that want to attach to networked, truly
>   persistent (replicated or tape-backed-up) storage.
>   1. make it possible to run things which must have local storage device
>   access.
> 
> Why not handle both cases with one concept?  Because the thing you end up
> with:
>    - has muddled concepts because it is trying to model too many cases
>    - adds extra API complexity (e.g. new object which is similar to but not
>    the same as a pod, with own lifetime)
>    - adds scheduler complexity (dealing with pairing durable data).
>    - an attractive nuisance which reduces pod mobility, which will block lots
>    of things (upgrades, autoscaling, rescheduling, etc.)
> 
> For the "easy to run things that want attach to networked storage" case, we
> should do:
>   - each cluster has one or more types of networked storage available, that,
>   to a first degree, are accessible to every minion.
>   - use something like  #2598 volumes framework to extension for various
>   networked storage solutions.
>   - maybe provide a way to allow admins to export and access control subsets
>   of those network storage soultions to users, along the general lines of
>   #3318
>   - pods are still completely mobile (not bound to specific machines with
>   specific local data.
>   - Do some kind of hack to deal with the GCE 1 Writer limitation.
>   - nfs and ceph clients are better examples of this category.
> 

- Down the road, create a PersistentVolume type that pretends to offer network volume, but is really handled by a ride-along pod that periodically snapshots the volumes to some durable storage, and offer a volume type that inits to latest snapshot or uses what's on disk.

> For the "possible to run things which must have local storage device access"
> case, we should do:
>   - make a hostDir capability, and perhaps narrower capabilities to use
>   specific file systems or devices.
>   - use policy to limit which pods can use those capabilities.  In mature
>   installations, only "infrastructure" pods would typically get that (ones
>   which e.g. implement ceph, cassandra, hdfs, etc servers).

**Comment by erictune** [comment]
@smarterclayton 
with the periodic snapshots idea: if application has other state that is not snapshottable (state on remote services), then on a recovery, it will have skewed local/remote state.  Not sure what fraction of apps would fit be able to use this?

**Comment by smarterclayton** [comment]
At least for the types of networked applications in aware of, the utility of this snapshot is more for simple singleton processes that could potentially tolerate some loss of data (last 10 minutes) in preference to having no data.  An admin team could modify their restart / node replacement processes in order to effectively maintain a possibly reasonable SLA, without the rest of the system being aware.  For instance, but adding a tool that tries to snapshot all the instances of this volume type on a node prior to beginning evacuation.

I'm thinking of things like Git repositories, Jenkins servers, simple Redis cache services, test databases, QA workloads, simple collaboration style apps, etc.  Losing even 15 minutes of state is unlikely to impact those sorts of tools, and most of them are inherently single pod stateful.  There's probably a cost / effort sweet spot for loose consistency of data here.

**Pull request closed without merging**
