### PR TITLE
Update two dependencies

### PR DESCRIPTION
**Pull request by ash2k**
**What this PR does / why we need it**:
github.com/stretchr/testify - main desired update. Old version has bugs. Specifically I encountered https://github.com/stretchr/testify/issues/347 which was fixed a year ago.

github.com/davecgh/go-spew/spew is set to the newest version, a bit
newer than required by testify. Updated from version 6 Nov 2015 to
27 Jun 2017.

github.com/stretchr/objx is not updated - testify uses version
from 27 May 2014 which is older than 28 Sep 2015 used now (latest
actually). In practice there is only a tiny difference - one method was
removed in new version.

**Release note**:

```release-note
NONE
```
/sig testing

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The update looks reasonable to me.

@smarterclayton could you help approve the update?

**Comment by ash2k** [comment]
Build is failing again... I don't know why. I think I'm going to give up on this one - spent too many hours on this already. I'm probably doing it wrong or something.

If I run the verify locally I'm getting this:
```shell
./hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'upstream/master'
Starting to download all kubernetes godeps. This takes a while
Download finished
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /private/var/folders/fh/7zp6kdcj3rgdd_7_nmw439_st0zyrt/T/gopath.XXXXXX.vTWuOUSJ/src/k8s.io/kubernetes
godep: [WARNING]:	$GOPATH: /var/folders/fh/7zp6kdcj3rgdd_7_nmw439_st0zyrt/T/gopath.XXXXXX.vTWuOUSJ:/private/var/folders/fh/7zp6kdcj3rgdd_7_nmw439_st0zyrt/T/gopath.XXXXXX.vTWuOUSJ/src/k8s.io/kubernetes/staging
hack/godep-save.sh: line 55: 31337 Killed: 9               GOPATH=${GOPATH}:${KUBE_ROOT}/staging godep save "${REQUIRED_BINS[@]}"
!!! Error in hack/godep-save.sh:55
  Error in hack/godep-save.sh:55. 'GOPATH=${GOPATH}:${KUBE_ROOT}/staging godep save "${REQUIRED_BINS[@]}"' exited with status 137
Call stack:
  1: hack/godep-save.sh:55 main(...)
Exiting with status 1
!!! Error in ./hack/verify-godeps.sh:100
  Error in ./hack/verify-godeps.sh:100. 'hack/godep-save.sh' exited with status 1
Call stack:
  1: ./hack/verify-godeps.sh:100 main(...)
Exiting with status 1
Removing /var/folders/fh/7zp6kdcj3rgdd_7_nmw439_st0zyrt/T/gopath.XXXXXX.vTWuOUSJ
```

Meta: maybe it is possible to automate the task of updating a specific dependency? It takes too long to do this manually. The whole "downloading the world" (several times?) and copying it (several times?) is very painful. I use glide in other projects and it is way better (though not ideal too).

**Comment by ash2k** [comment]
Output from the failing build:
```
I0713 02:17:21.455] --- /go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/Godeps/Godeps.json	2017-07-13 01:35:15.945410600 +0000
I0713 02:17:21.455] +++ /tmp/tmp.AsbyZ2sb58/go/src/k8s.io/apimachinery/Godeps/Godeps.json	2017-07-13 02:17:21.175472004 +0000
I0713 02:17:21.455] @@ -124,11 +124,11 @@
I0713 02:17:21.455]  		},
I0713 02:17:21.455]  		{
I0713 02:17:21.455]  			"ImportPath": "github.com/stretchr/testify/assert",
I0713 02:17:21.456] -			"Rev": "e3a8ff8ce36581f87a15341206f205b1da467059"
I0713 02:17:21.456] +			"Rev": "f6abca593680b2315d2075e0f5e2a9751e3f431a"
I0713 02:17:21.456]  		},
I0713 02:17:21.456]  		{
I0713 02:17:21.456]  			"ImportPath": "github.com/stretchr/testify/require",
I0713 02:17:21.456] -			"Rev": "e3a8ff8ce36581f87a15341206f205b1da467059"
I0713 02:17:21.456] +			"Rev": "f6abca593680b2315d2075e0f5e2a9751e3f431a"
I0713 02:17:21.456]  		},
I0713 02:17:21.457]  		{
I0713 02:17:21.457]  			"ImportPath": "github.com/ugorji/go/codec",
I0713 02:17:21.656] FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	98s
```

But I've updated godeps in apimachinery...

**Comment by caesarxuchao** [comment]
After rebase i can reproduce the error locally. It's probably caused by Blocked by https://github.com/kubernetes/kubernetes/pull/48497#discussion_r127312690.

**Comment by caesarxuchao** [comment]
I sent https://github.com/kubernetes/kubernetes/pull/48906 which hopefully will unblock this.

**Comment by caesarxuchao** [comment]
@ash2k you need to rebase and update apimachinery's Godeps.json, it now does depends on testify: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/Godeps/Godeps.json#L126-L132

**Comment by ash2k** [comment]
@caesarxuchao ok, thanks for pointing this out! Rebased and fixed. Lets see if it goes green.

**Comment by ash2k** [comment]
ok, all green finally.
PTAL @thockin. Nothing has changed, only several rebases+fixed a place where the dependency is now also referenced which I missed on the first rebase.

Thanks @caesarxuchao!

**Comment by caesarxuchao** [comment]
/lgtm

Thanks @ash2k

**Comment by ash2k** [comment]
PR, go away from my dashboard (https://github.com/kubernetes/test-infra/issues/1576)

**Pull request merged**
