### PR TITLE
fix:Optimize code for else logic

### PR DESCRIPTION
**Pull request by yulng**
if block ends with a return statement, so drop this else and outdent its block

Signed-off-by: yulng <wei.yang@daocloud.io>

### CODE REVIEW

**Comment by yulng** [comment]
@justaugustus 😄😄

**Comment by yulng** [comment]
> @justaugustus 😄😄

> @justaugustus 😄😄

**Comment by oomichi** [comment]
typo..

/release-note-none

**Comment by yulng** [comment]
@dims
@justaugustus

**Comment by yulng** [comment]
@dims 
@justaugustus 
:)

**Pull request merged**
