### PR TITLE
add bentheelder to reviewers

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Adding myself to reviewers for build, hack, and cluster. I've been reviewing these for some time unofficially, especially build + hack, shell scripts in general, cluster log scripts, the images ... 
I am an active member of the relevant SIGs (Testing, Release, Cluster Lifecycle).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig testing

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @ixdy @roberthbailey 
cc @spiffxp

**Comment by spiffxp** [comment]
I can't /approve cluster but I approve of the rest

**Pull request merged**
