### PR TITLE
Adding missing verify-*.sh scripts for autogenerated federation docs

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/41866

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Updated the PR to include all the 3 missing verify scripts

**Comment by nikhiljindal** [comment]
Verified that the scripts pass. Also evident from the verification tests passing on Jenkins.

**Comment by mbohlool** [comment]
Is generated-swagger-docs and api-reference-docs used anywhere?

**Comment by nikhiljindal** [comment]
Yes: https://kubernetes.io/docs/reference/federation/.
Yes we can remove swagger docs once we start generating docs from openapi and have updated kubectl to use openapi instead of swagger.
I remember you had a list @mbohlool right?

**Comment by nikhiljindal** [comment]
In summary: federation uses swagger spec in the same way kubernetes does.
So whenever we are ready to remove it from kubernetes, we should be able to remove it from federation as well.

**Comment by madhusudancs** [comment]
@nikhiljindal no major comments. Could you please fix the minor nits? I will add LGTM after.

---

Reviewed 3 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[hack/verify-federation-api-reference-docs.sh, line 3 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694#-Kjyx3N5mASjhOpmatrQ:-Kjyx3N5mASjhOpmatrR:bb6ht2h) ([raw file](https://github.com/kubernetes/kubernetes/blob/754715480b5ea477295501a7593400d5b648462d/hack/verify-federation-api-reference-docs.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # Copyright 2015 The Kubernetes Authors.
> ```

2017

---

*[hack/verify-federation-generated-swagger-docs.sh, line 3 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694#-KjyxKVUmngTRXfMWbIW:-KjyxKVUmngTRXfMWbIX:bb6ht2h) ([raw file](https://github.com/kubernetes/kubernetes/blob/754715480b5ea477295501a7593400d5b648462d/hack/verify-federation-generated-swagger-docs.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # Copyright 2015 The Kubernetes Authors.
> ```

2017

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694#-:-Kjz06TWqYjK0T391nOQ:b-1c7t2c)*

**Comment by nikhiljindal** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[hack/verify-federation-api-reference-docs.sh, line 3 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694#-Kjyx3N5mASjhOpmatrQ:-Kk7vMPJR8Z5xe0FyDTJ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/754715480b5ea477295501a7593400d5b648462d/hack/verify-federation-api-reference-docs.sh#L3)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---

*[hack/verify-federation-generated-swagger-docs.sh, line 3 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694#-KjyxKVUmngTRXfMWbIW:-Kk7vNsx7heSIVb1PXuH:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/754715480b5ea477295501a7593400d5b648462d/hack/verify-federation-generated-swagger-docs.sh#L3)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45694)*

**Comment by nikhiljindal** [comment]
Thanks for the review @madhusudancs 
Fixed code as per comments.
PTAL

**Comment by nikhiljindal** [comment]
Rebased again and ran update-* scripts again. Tests break on this PR everytime a PR updating the API merges.

**Comment by ahmetb** [comment]
@nikhiljindal it looks like the scripts that create federation content needs to be added to `hack/update-all.sh`, now with this PR merged, #44474 the output of `hack/update-all.sh` is failing on `make verify`. I'm putting together a PR to add the required steps to  `hack/update-all.sh`.

**Pull request merged**
