### PR TITLE
promote PersistentVolumeLastPhaseTransitionTime to beta

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

follow-up #119902

#### Special notes for your reviewer:

ref https://github.com/kubernetes/enhancements/pull/4180

#### Does this PR introduce a user-facing change?

```release-note
promote PersistentVolumeLastPhaseTransitionTime to beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://kep.k8s.io/3762
```

### CODE REVIEW

**Comment by RomanBednar** [comment]
This should not be merged until the KEP is updated to match current implementation and beta graduation criteria is met.

**Comment by carlory** [comment]
/hold

@RomanBednar PTAL https://github.com/kubernetes/enhancements/pull/4180

**Comment by RomanBednar** [comment]
@carlory Beta graduation requires also related changes like test fixes and results of testing required for beta graduation (if any). I've opened the PR with links to test results here: https://github.com/kubernetes/kubernetes/pull/120627

Also, please ask in advance if a contributor is planning to discontinue working on a specific enhancement to see if someone else can take over - this enhancement was never subject for re-assignment. Thank you.

**Pull request closed without merging**
