### PR TITLE
Bump Konnectivity to 0.28.0

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This picks up changes (including bugfixes): https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.2...v0.28.0

#### Which issue(s) this PR fixes:

Notable fixes:
* A fix for nil deref: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513
* Metric bugfix: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/511
* CVE fixes.

Notable features:
* Update genproto dependency to match Kubernetes 1.28: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/508
* proxy-agent: smarter readiness check: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/485

#### Special notes for your reviewer:

Note the new (client-go inspired) version scheme, where 0.28 maps to Kubernetes 0.28. (I will send a subsequent PR to release-1.28 branch).

#### Does this PR introduce a user-facing change?
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
@liggitt is the `pull-kubernetes-dependencies` related to https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/508?

**Comment by liggitt** [comment]
yes, job output was:

```
2023/09/22 19:44:29 Good news! Unwanted module "google.golang.org/genproto" dropped the following dependants:
2023/09/22 19:44:29    sigs.k8s.io/apiserver-network-proxy/konnectivity-client
2023/09/22 19:44:29 !!! Remove those from status.unwantedReferences["google.golang.org/genproto"] in /home/prow/go/src/k8s.io/kubernetes/hack/unwanted-dependencies.json to ensure they don't get reintroduced.
```

**Pull request merged**
