### PR TITLE
Fix a typo in the documentation

### PR DESCRIPTION
**Pull request by dasch**

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
LGTM

@dasch could you please sign CLA?

**Comment by dasch** [comment]
I signed it!

**Comment by piosz** [comment]
Thanks for contribution!

**Comment by alex-mohr** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
