### PR TITLE
Automated cherry pick of #19957

### PR DESCRIPTION
**Pull request by zmerlynn**
Cherry pick of #19957 on release-1.1.

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
hmmm:

`09:20:57 FAIL! -- 107 Passed | 0 Failed | 2 Pending | 63 Skipped ++ [[ -n 104.197.205.166:22-kube-apiserver.log
`

**Comment by roberthbailey** [comment]
Timed out.

**Comment by roberthbailey** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Pull request merged**
