### PR TITLE
Remove hack/e2e.go

### LINKED ISSUE #82448: Deprecating and remove hack/e2e.go
Follow up from @BenTheElder 's comment in https://github.com/kubernetes/kubernetes/pull/82188#issuecomment-526869867

We should change any instances to use kubetest directly, end users can do the same as well

### PR DESCRIPTION
**Pull request by dims**
picking up the commit from @BenTheElder 

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

removes hack/e2e.go which has been a wrapper around k8s.io/test-infra/kubetest for O(years). Please see additional context in:
https://github.com/kubernetes/kubernetes/pull/82458#issue-315222670

**Which issue(s) this PR fixes**:

Fixes #82448

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
/approve
/hold
Thanks for picking this up!
Holding so someone else can review, not sure how much of this was originally my commit ;-)

**Comment by liggitt** [comment]
lgtm
/hold cancel

**Comment by BenTheElder** [comment]
🎉

**Pull request merged**
