### PR TITLE
Pass --keepalive-time 2 to curl to fix unexpected EOF flakes

### LINKED ISSUE #22967: unit/integration flake: curl aborted while installing etcd
http://pr-test.k8s.io/22949/kubernetes-pull-test-unit-integration/18401/
```
+ ./hack/install-etcd.sh
curl: (18) transfer closed with 5587073 bytes remaining to read

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
!!! Error in /workspace/kubernetes/hack/lib/etcd.sh:71
  'tar xzf -' exited with status 18 2
Call stack:
  1: /workspace/kubernetes/hack/lib/etcd.sh:71 kube::etcd::install(...)
  2: ./hack/install-etcd.sh:27 main(...)
Exiting with status 1
!!! Error in /workspace/kubernetes/hack/lib/etcd.sh:68
  '( cd "${KUBE_ROOT}/third_party"; curl -fsSL https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz | tar xzf -; ln -fns "etcd-v${ETCD_VERSION}-linux-amd64" etcd; kube::log::info "etcd v${ETCD_VERSION} installed. To use:"; kube::log::info "export PATH=\${PATH}:$(pwd)/etcd" )' exited with status 1
Call stack:
  1: /workspace/kubernetes/hack/lib/etcd.sh:68 kube::etcd::install(...)
  2: ./hack/install-etcd.sh:27 main(...)
Exiting with status 1
```

Seems like a github.com flake? Could probably retry this, but not sure whether it's worth it.

### PR DESCRIPTION
**Pull request by ixdy**
I hope this fixes #22967.

### CODE REVIEW

**Comment by spxtr** [comment]
Interesting. I don't see any harm in this, but it feels like a bandaid.

**Comment by ixdy** [comment]
I agree. The proper fix (stop `curl`ing everything from github all the time) is much harder, though.

**Comment by fejta** [comment]
@k8s-bot node e2e test this issue #24479

**Comment by ixdy** [comment]
@k8s-bot unit test this, issue #28076

**Pull request merged**
