### PR TITLE
Add descirptions to /kube-aggregator/pkg/apis/apiregistration/*/types.go

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

./staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
./staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go

#### Which issue(s) this PR fixes:

Ref #99675

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/assign @sttts 

Thank you!

/triage accepted

**Comment by CaoDonghui123** [comment]
I rebase it

**Pull request merged**
