### PR TITLE
Update gem versions

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:
Updates the fluentd image gem versions and allow image users to use the configs introduced in the latest versions. For example uken/fluent-plugin-elasticsearch#579 .

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Hm, the `lgtm` label is missing. Any updates?

**Comment by coffeepac** [comment]
/lgtm

apologies for the slow response and thanks for pinging!

**Comment by ialidzhikov** [comment]
@coffeepac , did you managed to push the new `v2.5.2` image?
```
$ docker pull gcr.io/fluentd-elasticsearch/fluentd:v2.5.2
Error response from daemon: manifest for gcr.io/fluentd-elasticsearch/fluentd:v2.5.2 not found
```

https://console.cloud.google.com/gcr/images/fluentd-elasticsearch/GLOBAL/fluentd

**Comment by coffeepac** [comment]
Nuts.  No, will do today unless @monotek beats me to it.

**Comment by coffeepac** [comment]
@ialidzhikov pushed.  sorry for the delay!

**Comment by ialidzhikov** [comment]
@coffeepac , thank you!

**Comment by monotek** [comment]
Thanks! Updated helm chart is also available soon :-)
https://github.com/kiwigrid/helm-charts/pull/104

**Pull request merged**
