### PR TITLE
pkg/volume/azure_dd/

### PR DESCRIPTION
**Pull request by Aresforchina**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:#81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
pkg/volume/azure_dd/azure_common.go:68:2: var winDiskNumFormat is unused (U1000)
```

### CODE REVIEW

**Comment by Aresforchina** [comment]
@matthyx ohh,I have run `hack/verify-statick` when pulled down the local repo.It seemed execute to success at that time.now I would fix this error,thanks.

**Comment by Aresforchina** [comment]
@matthyx  The variable `winDiskNumFormat`  refer to another file `pkg/volume/azure_dd/azure_common_windows.go`,it can not being ignoring as an unused var.If so,I will close this pr.

**Comment by matthyx** [comment]
@Aresforchina it's a bit weird how these 2 files are organized... a proper refactoring should be considered.
To skip this error you can also add a comment like:
`winDiskNumFormat = "/dev/disk%d" //lint:ignore U1000 used in pkg/volume/azure_dd/azure_common_windows.go`

**Comment by Aresforchina** [comment]
It looks like a good solution and I will adopt this maaner,Thanks!

**Comment by Aresforchina** [comment]
@matthyx  it does not skip errors if just add comment in `pkg/volume/azure_dd/azure_common.go`.because this error just appears as an unused variable and the added comment  is useless for skiping error .So I define that var in azure_common_windows.go.please tell me that is this feasible？I am looking forward to your point.

**Comment by matthyx** [comment]
> So I define that var in `azure_common_windows.go`

Makes sense... even it it's weird to have the regex separated from the formatter (probably a smell that both files should merge).

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request closed without merging**
