### PR TITLE
Add word boundary support for GNU sed in zsh completion

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by Copper-Head** [comment]
@sttts this seems to have addressed the error I reported on Friday. Thanks!

**Comment by lisinge** [comment]
@sttts I'm sorry to bring this up in this issue, i understand it's not really the right place but i'm totally lost on how to make your zsh completion work in my zsh, where do i place the zsh and bash completion files and how should i source them?

**Comment by slintes** [comment]
@lisinge https://www.slintes.net/2016/04/20/zsh-and-kubectl/ :)

**Comment by lisinge** [comment]
@slintes Wow, i'm so stupid! Thank you!

**Pull request merged**
