### PR TITLE
Cassandra Cluster Example Add Check for Null Endpoints.

### PR DESCRIPTION
**Pull request by mikeln**
Fix for Issue: Cassandra Cluster Example Custom Seed Cores on First Node #5737

Also note:  for this change to be effective, the following jar must be rebuilt and checked in:

```
kubernetes/examples/cassandra/image/kubernetes-cassandra.jar
```

However, this example does not have any visible java build and testing infrastructure.

### CODE REVIEW

**Comment by mikeln** [comment]
We have a signed CLA: 
Samsung SDS America.  
Google Group: sdsra-google-contributors@googlegroups.com
mikel.n@samsung.com (alternate email: github@mikelnelson.net)

**Comment by mikeln** [comment]
Signed SLA:
Samsung SDS America
sdsra-google-contributors@googlegroups.com
mikel.n@samsung.com ( alternate email: github@mikelnelson.net)

**Comment by mbforbes** [comment]
Thank you for opening the PR, sending the CLA info, and pointing out the need for an updated jar!

Can you please rebase to squash the six commits into a single commit? (The base command is `git rebase -i` and you can, e.g., turn the other commits into "fixups.")

**Comment by mbforbes** [comment]
Assigning to @brendandburns because (I believe) he'll be back on Monday and he is the one who checked in the Cassandra example.

Brendan, I think the last few things to do are:

0. Can you check out whether we have an applicable CLA? I'm not sure where to look for a corporate CLA for Samsung and I can't find and individual CLA for Mikel using our tool.

0. Does the fix make sense?

0. Can you please rebuild the jar with this change or provide instructions for how to do so so that Mikel can include it with this PR?

**Comment by mikeln** [comment]
crud.. sorry, messed up the rebase!

**Pull request closed without merging**
