### PR TITLE
Update to rules_go 0.16.2 and gazelle 0.15.0

### PR DESCRIPTION
**Pull request by ixdy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: updating brings some minor new features and bugfixes, but the most notable thing is not breaking in bazel 0.20+ when the CC API changes.

Updating gazelle also brings in autogazelle, which is not yet being used, but is worth experimentation.

Note that these changes require bazel 0.17.2+. This version of bazel has been out for over a month.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @BenTheElder @thockin 
/sig release testing

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by ixdy** [comment]
fixed the commit messages, since I mixed up the bazel version and rules_go version.

@thockin can I get approval please?

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by ixdy** [comment]
/hold

There's going to be another rules_go release this week with support for go1.11.2.

**Comment by cblecker** [comment]
/approve 
for the deps bump

**Comment by ixdy** [comment]
/hold cancel

This now updates to rules_go 0.16.2, which includes support for go1.11.2.

PTAL?

**Comment by ixdy** [comment]
note that I have not bumped the go version in this PR.

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
LGTM

**Pull request merged**
