### PR TITLE
update dual-stack test description to remove alpha

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- Removes `alphafeature` from the dual-stack test descriptions as it's graduated to `beta` in v1.21

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by aramase** [comment]
I believe kind tests are already using `IPv6DualStack` for ginkgo.focus. I've opened https://github.com/kubernetes/test-infra/pull/21351 to use `IPv6DualStack` in azure dual-stack tests.

**Comment by khenidak** [comment]
thanks
/approve
/lgtm

**Comment by aojea** [comment]
we need a top level approver
/assign @thockin @spiffxp 
whoever comes first XD

**Pull request merged**
