### PR TITLE
Remove ARCH specific image consideration from e2e tests

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I309fec49b030a4d457890f25d2f69e7c641c03fd

**What this PR does / why we need it**:
All e2e test images are now using multi-arch manifests so we should stop
looking up and using images that are specific to runtime.GOARCH

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/38067

**Review by luxas — APPROVED** [review]
Whoa, are every test image a manifest list now? Woot in that case (!!), but if you can show proof of it I'd be happy :wink:

LGTM code-wise

**Comment by mkumatag** [comment]
Well.. some of these volume tests are not fat manifest, infact they are not even converted to support multi arch.. any either way the tests who are using volume images will fail on different platform.. 

I'll submit the different PR to make those remaining images multi arch..

**Comment by dims** [comment]
Latest inventory - http://paste.openstack.org/raw/727759/

**Comment by dims** [comment]
/assign @liggitt 
/assign @spiffxp

@spiffxp @liggitt this one is ready to merge. PTAL

-- Dims

**Review by luxas — APPROVED** [review]
Thanks for the great work @dims @mkumatag :tada:!
/approve

**Comment by liggitt** [comment]
thanks for the work, how do we plan to ensure any new images use manifests and support appropriate platforms?

**Comment by dims** [comment]
@liggitt one idea i had is that ... once we have at least a couple of e2e conformance suites publish to testgrid, we can add checks in the shell scripts to bail out if someone tries to add a container image without the specific architectures that may end up breaking the e2e tests. At the moment we have only one non-amd64 CI which is the ppc64le ( https://k8s-testgrid.appspot.com/sig-node-ppc64le#conformance )

**Pull request merged**
