### PR TITLE
Don't throw error if resource is missing openapi definition

### PR DESCRIPTION
**Pull request by tamalsaha**
xref: #66285

### CODE REVIEW

**Comment by deads2k** [comment]
This looks reasonable to me.  Not having openapi should be allowed.  What's weird is that this field looks to be write only.

@kubernetes/sig-api-machinery-bugs

**Comment by jennybuckley** [comment]
I don't mind this, we might also want to consider requiring that the path is explicitly ignored in the config, something like https://github.com/jennybuckley/kubernetes/commit/b651d8888ed773f9c3f4b2768f162f8e7a1a05ea

**Comment by tamalsaha** [comment]
I don't know enough to form an opinion on proper fix. Please let me know which approach makes more sense. Gotta re-vendor some repos :)

**Comment by tamalsaha** [comment]
@jennybuckley, I looked into this more. I like your approach. Feel free to close this if that makes sense.

**Comment by tamalsaha** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/66512

**Pull request closed without merging**
