### PR TITLE
pkg/controller/disruption:Correct a spelling mistake

### PR DESCRIPTION
**Pull request by caiyixiang**
pkg/controller/disruption:Correct a spelling mistake

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/release-note-none
/ok-to-test
/lgtm

Thanks!

**Comment by caiyixiang** [comment]
@xiangpengzhao The test failed, it should be nothing to do with my PR,
What should we do now?Thanks

**Comment by xiangpengzhao** [comment]
The failures are cause by some issues of test framework. Let me try to retest it.

/retest

**Comment by xiangpengzhao** [comment]
@krzyzacy pull-kubernetes-e2e-gce-gpu still has `Error checking queue status.`

**Comment by krzyzacy** [comment]
@stevekuznetsov is this related to what you are talking on slack? ^^

**Comment by stevekuznetsov** [comment]
@krzyzacy no sorry the queue issues we were having were on another system -- not on the Jenkins for presubmits

**Comment by caiyixiang** [comment]
@xiangpengzhao Can you help me to add a approved label which needed by submit queue

**Comment by xiangpengzhao** [comment]
@caiyixiang sorry, I'm not the owner of the file you touched so I don't have the right to approve :)

ping @derekwaynecarr for approval :)

**Comment by caiyixiang** [comment]
@derekwaynecarr Can you help me to add a approved label which needed by submit queue,thanks

**Pull request closed without merging**
