### PR TITLE
Revert "Fix kubectl Stratigic Merge Patch compatibility"

### PR DESCRIPTION
**Pull request by mengqiy**
Revert PR #37038 

cc: @pwittrock

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37337)

### CODE REVIEW

**Comment by dims** [comment]
@ymqytw Can you please explain why this revert is needed? (And please mark this as 1.5 milestone if appropriate)

**Comment by ymqytw** [comment]
@dims see: https://github.com/kubernetes/kubernetes/pull/35647#issuecomment-262415809
We decided to use another way. Need to rollback.

**Comment by dims** [comment]
Ack thanks @ymqytw

**Comment by ymqytw** [comment]
Also need to revert #36678 #35647
The revert order is:
1) #37038
2) #36678
3) #35647

**Comment by ymqytw** [comment]
Closing this PR since I'm trying to do a combined revert in #37343

**Pull request closed without merging**
