### PR TITLE
Automated cherry pick of #106887: Direct v2betaX users to migrate to HPA v2

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #106887 on release-1.23.

#106887: Direct v2betaX users to migrate to HPA v2

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/release-managers this would be good to get in 1.23.1

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
