### PR TITLE
Modify err output format from %s to %v

### PR DESCRIPTION
**Pull request by lixiaobing1**
t.Errorf err output format should be %v

### CODE REVIEW

**Comment by lixiaobing10051267** [comment]
why fail with the same reason "Connection timed out" as #29253? is that the CI environment wrong?

**Comment by lixiaobing10051267** [comment]
@justinsb can it be re-test directly?

**Comment by lixiaobing10051267** [comment]
@jfrazelle this PR has the same fail reason as #29253, and #29253 has been successful to retest, can be this PR retest?

**Comment by lixiaobing10051267** [comment]
@k8s-bot test this issue: #27663

**Comment by jfrazelle** [comment]
@k8s-bot test this issue #27663

**Comment by jfrazelle** [comment]
thanks @lixiaobing10051267

**Pull request merged**
