### PR TITLE
fix the test issue of node shutdown manager

### LINKED ISSUE #104938: UT Failure: TestRestart data race
##### Error text:
```
=== RUN   TestRestart
E0829 06:18:41.006305   84048 nodeshutdown_manager_linux.go:197] "Ended to watching the node for shutdown events"
==================
WARNING: DATA RACE
Read at 0x00000417c348 by goroutine 92:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).start()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:139 +0x49
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).Start.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:129 +0x152

Previous write at 0x00000417c348 by goroutine 53:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:344 +0x27e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Goroutine 92 (running) created at:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).Start()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:121 +0x230
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux
```
#### Recent failures:
[2021/9/4 上午2:00:19 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433851876134096896)
[2021/9/3 下午8:00:05 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433761222271963136)
[2021/9/3 下午2:00:15 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433670624454119424)
[2021/9/3 上午7:59:43 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433580026854379520)
[2021/9/3 上午1:59:22 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433489204028903424)

/kind failing-test

### PR DESCRIPTION
**Pull request by calvin0327**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The test function will no pass in case of concurrency.

#### Which issue(s) this PR fixes:

Fixes #104938

#### Special notes for your reviewer:
I find the reason for it, but I don't know the solution is suitable, correct me if not.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
similar with #103291
/cc wzshiming bobbypage

**Comment by bobbypage** [comment]
I think long term we should figure out how to refactor the tests so they do not need to modify `systemDBus`. Maybe refactor `Manager` to accept dbus function so that we avoid this issue in first place.

As short term, I think this should fix race, so LGTM

/lgtm

**Comment by pacoxu** [comment]
/triage accepted
/priority important-soon
since it will cause some flakes.

**Comment by calvin0327** [comment]
/assign mrunalp
for approval

**Review by wzshiming — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
