### PR TITLE
Automated cherry pick of #66685: Add KUBE_CUSTOM_CALICO_NODE_DAEMONSET_YAML and

### PR DESCRIPTION
**Pull request by cadmuxe**
Cherry pick of #66685 on release-1.11.

#66685: Add KUBE_CUSTOM_CALICO_NODE_DAEMONSET_YAML and

### CODE REVIEW

**Comment by bowei** [comment]
where is the release note?

**Comment by cadmuxe** [comment]
There is no release note, it's for GKE.
https://github.com/kubernetes/kubernetes/pull/66685

**Pull request merged**
