### PR TITLE
Added lister expansions for DaemonSet, Deployment, ReplicaSet, and StatefulSet for apps/v1beta2

### LINKED ISSUE #50870: Add lister expansions for DaemonSet, Deployment, ReplicaSet, and StatefulSet to apps/v1beta2
As a prerequisite of moving the `DaemonSet`, `Deployment`, `ReplicaSet`, and `StatefulSet` controllers to use the apps/v1beta2 APIs, we need to add list expansions for  `DaemonSet`, `Deployment`, `ReplicaSet`, and `StatefulSet` to `apps/v1beta2`.

### PR DESCRIPTION
**Pull request by liyinan926**
**What this PR does / why we need it**:
This PR copies list expansions for  `DaemonSet`, `Deployment`, `ReplicaSet`, and `StatefulSet` to `apps/v1beta2` from `extensions/v1beta1` and `apps/v1beta1`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50870.

**Special notes for your reviewer**:
@kow3ns @janetkuo 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by kow3ns — APPROVED** [review]

**Comment by liyinan926** [comment]
@caesarxuchao need your approval. PTAL. Thanks!

**Comment by liyinan926** [comment]
@caesarxuchao Need your approval. Could you please take a look? Thanks!

**Pull request merged**
