### PR TITLE
Fix resttest Update action when AllowUnconditionalUpdate is false

### PR DESCRIPTION
**Pull request by soltysh**
Currently our storage Update test assumes that AllowUncoditionalUpdate returns true, and in testUpdateRejectsMismatchedNamespace updates the same object it's passing to create. This results in errors when trying to update that object, due to resourceVersion not being set to a proper value. This patch modifes this so that the update is executed on a stored object, which will have correct values set.

@deads2k ptal
@kubernetes/sig-api-machinery-misc fyi

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Review by liggitt — COMMENTED** [review]
Are we still testing the unconditional update somewhere? I don't want to lose that. Which rest handlers don't allow unconditional update?

**Comment by deads2k** [comment]
> Are we still testing the unconditional update somewhere? I don't want to lose that. Which rest handlers don't allow unconditional update?

Most of ours.  This particular test wasn't focused on unconditional update checks, looks like more of an accident than anything else.  I'm not against testing it, but it will require more plumbing that this harness currently has.  I'd say followup.

**Comment by soltysh** [comment]
@k8s-bot bazel test this

**Pull request merged**
