### PR TITLE
Correct kill logic for pod processes

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Correct the kill logic for processes in the pod's cgroup.  os.FindProcess() does not check whether the process exists on POSIX systems.

### CODE REVIEW

**Comment by RobertKrawitz** [comment]
@sjenning @derekwaynecarr

**Comment by RobertKrawitz** [comment]
Test results (using loop test): 857 passes, min 1, max 15, average 6 (seconds)

**Comment by sjenning** [comment]
This fixes the issue were trying to kill a pid that had already exited resulted in an error from `tryKillingCgroupProcesses()` which blocks cleanup of the cgroup path.

/lgtm
/assign @derekwaynecarr 
/sig node

**Pull request merged**
