### PR TITLE
kubeadm: Enable self-hosting by default

### LINKED ISSUE #371: Make deploying the control plane self-hosted the default
Title says kind of everything :)

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Enables self-hosting as the default way to deploy the control plane.
Marking this as do-not-merge for now as not all prereqs are met in the tracking issue yet: https://github.com/kubernetes/kubeadm/issues/127

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes: https://github.com/kubernetes/kubeadm/issues/371

**Special notes for your reviewer**:

**Release note**:

```release-note
kubeadm: Enable self-hosting by default
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @aaronlevy @diegs

### CODE REVIEW

**Review by timothysc — APPROVED** [review]

**Comment by timothysc** [comment]
Shouldn't we pend on: https://github.com/kubernetes/kubernetes/pull/50984

**Comment by luxas** [comment]
> Shouldn't we pend on: #50984 

@timothysc Yes. And we might even consider _not_ enabling this in v1.8, but instead v1.9 when we are really confident it is working. This is just a straw man to keep track of it and make it easy to LGTM if we decide to do this. In any case, we'll ship the best possible self-hosting solution for v1.8, regardless of enabled by default or not.

**Comment by lukemarsden** [comment]
We decided not to make self-hosting the default by 1.8, we'll gate it behind a feature gate and encourage people to try it out and get us feedback so that we can turn it on by default for 1.9.

**Comment by luxas** [comment]
Due to a number of factors:
 - We didn't announce in v1.7 that self-hosting would become the default
 - Self-hosting hasn't been available in v1.7-
 - Users that upgrade from v1.7->v1.8 will have static pod clusters in any case, we don't want to fragment new users with self-hosting and "old" users with static pods
 - Enabling a new feature directly adds a lot of risk
 - v1.8 is aimed to be a stability release
etc.

We decided to **_not_** enable self-hosting by default in v1.8
It will be the default in v1.9 though, and we'll advertise that very well
Self-hosting is supported on a beta level in v1.8 and can easily be used using `--feature-gates=SelfHosting=true`

**Pull request closed without merging**
