### PR TITLE
Tighten label validation

### PR DESCRIPTION
**Pull request by thockin**
Ensure the LHS is a DNS subdomain
Don't allow uppercase on LHS
Don't allow underscore on LHS
Validate the RHS is < 64 chars
Better error strings

### CODE REVIEW

**Comment by thockin** [comment]
@bgrant0607 as per meeting

**Comment by bgrant0607** [comment]
Please also update labels.md:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md#syntax-and-character-set

**Comment by thockin** [comment]
@smarterclayton any concerns here?

**Comment by smarterclayton** [comment]
No concerns from my end.

**Comment by thockin** [comment]
Updated docs

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
