### PR TITLE
make deps-approvers the approvers of sample-cli-plugin/Godeps

### PR DESCRIPTION
**Pull request by mikedanese**
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Thanks @mikedanese! I'm just testing a patch locally to enforce this for staging repos going forward:
```
diff --git a/hack/update-staging-godeps-dockerized.sh b/hack/update-staging-godeps-dockerized.sh
index 877e43b2d2..64084a8b16 100755
--- a/hack/update-staging-godeps-dockerized.sh
+++ b/hack/update-staging-godeps-dockerized.sh
@@ -120,11 +120,12 @@ for repo in $(ls ${KUBE_ROOT}/staging/src/k8s.io); do
 
   if [ "${DRY_RUN}" != true ]; then
     cp "${TMP_GOPATH}/src/k8s.io/${repo}/Godeps/Godeps.json" "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/Godeps.json"
+    cp "${KUBE_ROOT}/Godeps/OWNERS" "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/OWNERS"
     # Assume Godeps.json is not updated, as the working tree needs to be clean
     # Without this, the script would pause after each staging repo to prompt the
     # user to commit all changes (difficult inside a container). It's safe to
     # ignore this file, as we know it's going to be changing, and we don't copy
     # the git tree back out from the container.
-    git update-index --assume-unchanged "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/Godeps.json"
+    git update-index --assume-unchanged -- "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/Godeps.json" "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/OWNERS"
   fi
 done
```

If it passes, would you mind adding it here, and we get them both taken care of?

**Comment by mikedanese** [comment]
@cblecker done.

**Comment by cblecker** [comment]
@mikedanese Okay, the local run finished, and there's a slight change. We don't need the line 129 change to the git update-index command. Also, there are a couple other OWNERS files that are missing.

Full patch:
```
diff --git a/hack/update-staging-godeps-dockerized.sh b/hack/update-staging-godeps-dockerized.sh
index 877e43b2d2..a0e0e50c37 100755
--- a/hack/update-staging-godeps-dockerized.sh
+++ b/hack/update-staging-godeps-dockerized.sh
@@ -120,6 +120,7 @@ for repo in $(ls ${KUBE_ROOT}/staging/src/k8s.io); do

   if [ "${DRY_RUN}" != true ]; then
     cp "${TMP_GOPATH}/src/k8s.io/${repo}/Godeps/Godeps.json" "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/Godeps.json"
+    cp "${KUBE_ROOT}/Godeps/OWNERS" "${KUBE_ROOT}/staging/src/k8s.io/${repo}/Godeps/OWNERS"
     # Assume Godeps.json is not updated, as the working tree needs to be clean
     # Without this, the script would pause after each staging repo to prompt the
     # user to commit all changes (difficult inside a container). It's safe to
diff --git a/staging/src/k8s.io/kube-proxy/Godeps/OWNERS b/staging/src/k8s.io/kube-proxy/Godeps/OWNERS
new file mode 100644
index 0000000000..3d49f30605
--- /dev/null
+++ b/staging/src/k8s.io/kube-proxy/Godeps/OWNERS
@@ -0,0 +1,2 @@
+approvers:
+- dep-approvers
diff --git a/staging/src/k8s.io/kube-scheduler/Godeps/OWNERS b/staging/src/k8s.io/kube-scheduler/Godeps/OWNERS
new file mode 100644
index 0000000000..3d49f30605
--- /dev/null
+++ b/staging/src/k8s.io/kube-scheduler/Godeps/OWNERS
@@ -0,0 +1,2 @@
+approvers:
+- dep-approvers
diff --git a/staging/src/k8s.io/sample-cli-plugin/Godeps/OWNERS b/staging/src/k8s.io/sample-cli-plugin/Godeps/OWNERS
index 9550e5e8e2..3d49f30605 100644
--- a/staging/src/k8s.io/sample-cli-plugin/Godeps/OWNERS
+++ b/staging/src/k8s.io/sample-cli-plugin/Godeps/OWNERS
@@ -1,3 +1,2 @@
 approvers:
-- juanvallejo
-- soltysh
+- dep-approvers
```

**Comment by mikedanese** [comment]
@cblecker done. If that's not it, feel free to submit an alternative PR :)

**Comment by cblecker** [comment]
/lgtm
Thank you!

**Comment by cblecker** [comment]
/milestone v1.12
/kind cleanup

Approving for milestone as this is an OWNERS fix and won’t impact release.

cc: @tpepper

**Comment by sttts** [comment]
👍

**Pull request merged**
