### PR TITLE
Optimize order description for turning down cluster

### PR DESCRIPTION
**Pull request by lixiaobing1**
Optimize order description for turning down cluster.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30765)

### CODE REVIEW

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
@foxish Any idea why no CLA bot touched this PR?

**Comment by foxish** [comment]
@bgrant0607 No changes from our end in the CLA. Maybe the Google bot missed this webhook when it was fired. 
@willnorris Can you comment?

**Comment by willnorris** [comment]
I'm not sure why CLAs weren't automatically checked here (I'll look into it).  But I've manually confirmed that CLAs look good for this PR.

**Pull request merged**
