### PR TITLE
Add ownership inspection to mount tester image

### PR DESCRIPTION
**Pull request by pmorie**
Dependency of #15352

### CODE REVIEW

**Comment by pmorie** [comment]
@mikedanese @lavalamp

**Comment by pmorie** [comment]
@k8s-oncall would someone hit the button on this and push the images?  It's needed for #15352.

**Comment by jlowdermilk** [comment]
Whoops. Didn't see this has no lgtm. @mikedanese or @lavalamp please take a look and let me know if I need to revert.

**Comment by lavalamp** [comment]
@jlowdermilk I don't have any particular problem with this, but I'm pretty sure @pmorie was asking for a build and image push, not a merge...

**Comment by pmorie** [comment]
@lavalamp I was asking for a build and push, and a merge, so I can take this off my laundry list of things that will result in my death if not completed #safetyfirst

**Comment by lavalamp** [comment]
One out of three is... not so great, I guess. @jlowdermilk, can you do the
build & push?

**Comment by jlowdermilk** [comment]
Done.
```
$ make push
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' ./mt.go
sudo docker build -t gcr.io/google_containers/mounttest:0.5 .
Sending build context to Docker daemon 1.731 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : ADD mt mt
 ---> 9fc8c69b350f
Removing intermediate container 2554924a6113
Step 2 : ENTRYPOINT /mt
 ---> Running in 3cfa1528d896
 ---> 2e96bc32211b
Removing intermediate container 3cfa1528d896
Successfully built 2e96bc32211b
gcloud docker push gcr.io/google_containers/mounttest:0.5
The push refers to a repository [gcr.io/google_containers/mounttest] (len: 1)
Sending image list
Pushing repository gcr.io/google_containers/mounttest (1 tags)
9fc8c69b350f: Image successfully pushed 
2e96bc32211b: Image successfully pushed 
Pushing tag for rev [2e96bc32211b] on {https://gcr.io/v1/repositories/google_containers/mounttest/tags/0.5}
```

**Comment by pmorie** [comment]
Thanks a lot @jlowdermilk

**Pull request merged**
