### PR TITLE
switch some more images to gcr for reliability

### PR DESCRIPTION
**Pull request by brendandburns**
@quinton-hoole @ixdy

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM.  We probably want some hierarchy under gcr.io/google_containers (e.g. to separate the custom Kubernetes-build ones from the generic ones like busybox).  I assume that all of the images in this PR have been uploaded to gcr.io?

**Comment by quinton-hoole** [comment]
Oh, and are all of their dependencies in gcr.io also?

**Comment by thockin** [comment]
Other than the ones we build from code, who is keeping this nginx (for example) up to date?

**Comment by quinton-hoole** [comment]
Agreed.  I discussed this with @brendandburns offline.  Seems we
could/should fix that problem as a separate issue.  Pretty sure it exists
independently of this PR.

**Comment by satnam6502** [comment]
Any idea why this test failed? http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/7046/testReport/junit/(root)/Kubernetes%20e2e%20suite/EmptyDir_volumes_should_support_r_w/

**Comment by quinton-hoole** [comment]
It looks like getContainerOutputInNamespace() failed to get the logs from the container (hence empty string):

Expected
    <string>: 
to contain substring
    <string>: mount type of "/test-volume": tmpfs

I doubt whether that has anything to do with this PR.

**Comment by quinton-hoole** [comment]
Closes #8849

**Pull request merged**
