### PR TITLE
Move node problem detector test into node e2e.

### PR DESCRIPTION
**Pull request by Random-Liu**
Move current NPD e2e test into node e2e.

In fact, current NPD e2e test is only a functionality test for NPD. It creates test NPD pod, sets test configuration, generates test logs and verifies test result.
It doesn't actually test the NPD really deployed in the cluster.

So it doesn't actually need to run in cluster e2e. Running it in node e2e will:
1) Make it easier to run the test.
2) Make it more light weight to introduce this as a pre/post submit test in NPD repo in the future.

Except this, I'm working on a cluster e2e to run some basic functionality test and benchmark test against the real NPD deployed in the cluster. Will send the PR later.

/cc @dchen1107 @kubernetes/node-problem-detector-reviewers

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot test this.

**Comment by Random-Liu** [comment]
@k8s-bot test this.

**Comment by Random-Liu** [comment]
@k8s-bot non-cri e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by dchen1107** [comment]
@kubernetes/release-team @kubernetes/kubernetes-release-managers This pr only moves the tests to node e2e. It shouldn't affect any production, and help with long term testing.

**Comment by Random-Liu** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by ncdc** [comment]
Did this break cross builds?

```
I0302 13:12:41.422] +++ [0302 13:10:35] linux/arm: go build started
I0302 13:12:41.422] # k8s.io/kubernetes/test/e2e_node
I0302 13:12:41.423] test/e2e_node/node_problem_detector.go:395: invalid operation: info.Uptime * int64(time.Second) (mismatched types int32 and int64)
```

from e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-cross-build/1026/build-log.txt

**Comment by ixdy** [comment]
Sure seems like it. :(

**Comment by ncdc** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/42441 and @sjenning is working on a fix

**Comment by ixdy** [comment]
https://golang.org/src/syscall/ztypes_linux_arm.go#L525 is indeed `int32`, not `int64`.

**Comment by sjenning** [comment]
@ixdy nasty.  but nice find.  mind moving this bug investigation to https://github.com/kubernetes/kubernetes/issues/42441

**Pull request merged**
