### PR TITLE
Unroll ScheduleAlgorithm#Extenders() to Scheduler.go

### PR DESCRIPTION
**Pull request by Jerry-Ge**
Signed-off-by: Jerry Ge <jerry.ge@arm.com>

Co-authored-by: Huang-Wei <wei.huang1@ibm.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR is the first part of issue #101135 which will Unroll ScheduleAlgorithm#Extenders() to Scheduler.go

#### Which issue(s) this PR fixes:

Part of #101135

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by Huang-Wei** [comment]
Sorry I missed this. LGTM, could you squash the commits?

@alculquicondor I guess none of us has the approve privileges on `pkg/scheduler/apis/config/*` now?

**Comment by Jerry-Ge** [comment]
Cool! Thanks for the review and I will squash the commits.

**Pull request merged**
