### PR TITLE
scheduler: remove unused random generator

### PR DESCRIPTION
**Pull request by hongchaodeng**
The way scheduler selecting host has been changed to round-robin.
Clean up leftover.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@davidopp @gmarek @xiang90

**Comment by gmarek** [comment]
LGTM

**Comment by gmarek** [comment]
```
plugin/pkg/scheduler/generic_scheduler_test.go:117: unknown genericScheduler field 'random' in struct literal
```

**Comment by hongchaodeng** [comment]
@gmarek 
Can you help apply the labels?

**Comment by hongchaodeng** [comment]
@k8s-bot test this issue: #26187

**Comment by hongchaodeng** [comment]
@k8s-bot e2e test this issue: #26187

**Comment by hongchaodeng** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Pull request merged**
