### PR TITLE
CHANGELOG: Fix kubectl debug KEP link

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190805-kubectl-debug.md is changed
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1441-kubectl-debug/README.md
link return page 404 error
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/unassign 

probably a better review for a sig-release or sig-docs reviewer

**Comment by justaugustus** [comment]
Thanks!

/retitle CHANGELOG: Fix kubectl debug KEP link
/lgtm
/approve
/triage accepted

**Pull request merged**
