### PR TITLE
Fix e2e typos

### PR DESCRIPTION
**Pull request by NathanBaulch**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

Fixes 189 typos in the e2e testing area. This is a subset of the monolithic PR #126623.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/remove-sig api-machinery
Are you scripting this? Should we enhance our spellcheck presubmit check?

**Comment by NathanBaulch** [comment]
No @BenTheElder, I use a combination of the [typos](https://github.com/crate-ci/typos) tool and IntelliJ's built-in language checkers. Automated spell checking can always be improved (and [my PRs](https://github.com/kubernetes/kubernetes/issues?q=author%3ANathanBaulch+typos) could certainly be used as a basis for those improvements) but the false positive and false negative rate is so high that it's always going to be difficult to make it comprehensive without causing friction for contributors.

**Comment by SergeyKanzhelev** [comment]
sig node related typos are lgtm

**Comment by atiratree** [comment]
sig apps related typos are also lgtm

**Comment by pohly** [comment]
I see only very few instances where the typo might ever get visible to an end user and therefore fixing most of those typos has a negative value (see the [evolving policy around this](https://github.com/kubernetes/community/pull/8135)).

Let's not merge this unless it gets stripped down manually to just user-visible typos.

**Pull request closed without merging**
