### PR TITLE
variable 'controller' collides with imported package name

### PR DESCRIPTION
**Pull request by StudyNick**
variable 'controller' collides with imported package name,
 'controller'  modify 'ctrl'

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by sjenning** [comment]
Not sure if we want to "fix" every instance of package shadowing in the code base (definitely not on PR per instance), but this one is harmless enough.

/lgtm
/approve
/release-note-none

@k8s-bot ok to test

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Pull request merged**
