### PR TITLE
Prune reviewers from pkg/cloudprovider

### PR DESCRIPTION
**Pull request by calebamiles**
**What this PR does / why we need it**

Per discussion in https://github.com/kubernetes/kubernetes/pull/36530 the `OWNERS` file for `pkg/cloudprovider` should not contain additional reviewers at this time.

**Special notes for your reviewer**:

Sorry for the extra work in review

**Release note**:

`NONE`

### CODE REVIEW

**Comment by apelisse** [comment]
@k8s-bot gci gke e2e test this

**Comment by calebamiles** [comment]
linked to https://github.com/kubernetes/contrib/issues/1389

**Pull request merged**
