### PR TITLE
DNM: running CI against Laura's PR

### PR DESCRIPTION
**Pull request by thockin**
@lauralorenz - I added just the one diff and did a pretty trivial (but still screw-up-able) rebase to fix conflicts.

I know you logged off for the night, so maybe this will give you signal to move ahead in the AM.

### CODE REVIEW

**Comment by thockin** [comment]
Looks like everything passed except pull-kubernetes-e2e-gce-cos-alpha-features

Closing now.

**Comment by aojea** [comment]
@thockin  this job failed here with an error related to the feaure

> Nov 07 07:30:55.779735 e2e-1b39294611-92f64-master kubelet[2596]: E1107 07:30:55.771619    2596 run.go:72] "command failed" err="failed to validate kubelet configuration, error: invalid configuration: FeatureGate KubeletCrashLoopBackOffMax is enabled, CrashLoopBackOff.MaxContainerRestartPeriod must be set, path: &TypeMeta{Kind:,APIVersion:,}"


https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/128645/pull-kubernetes-e2e-gce-cos-alpha-features/1854420712224198656/artifacts/e2e-1b39294611-92f64-master/kubelet.log

**Comment by aojea** [comment]
@lauralorenz @thockin 

> failed to validate kubelet configuration, error: invalid configuration: FeatureGate KubeletCrashLoopBackOffMax is enabled, CrashLoopBackOff.MaxContainerRestartPeriod 

the "alpha" jobs enable all alphas, the feature should be safe to enable without requiring additional parameters

**Pull request closed without merging**
