### PR TITLE
clean regex strings

### PR DESCRIPTION
**Pull request by Nish60220110anth**
#### What type of PR is this?
Clean regex string, remove deprecated `pointer.BoolPtr`,`pointer.IntPtr`

#### What this PR does / why we need it:
/kind cleanup

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
None

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@Nish60220110anth Can you please run `hack/update-all.sh` so the PR can pass the verify test? :)

**Comment by Nish60220110anth** [comment]
@dinhxuanvu I did run and the results were successful but few json files were generated as a byproduct of running `hack/update-all.sh` in folder `api/openapi-spec/v3`. Do i need to commit those ?

**Comment by dinhxuanvu** [comment]
> @dinhxuanvu I did run and the results were successful but few json files were generated as a byproduct of running `hack/update-all.sh` in folder `api/openapi-spec/v3`. Do i need to commit those ?

I believe so. Otherwise, the verify test will continue to fail.

**Pull request closed without merging**
