### PR TITLE
Remove references to kubernetes.io/grpc appProtocol

### PR DESCRIPTION
**Pull request by LiorLieberman**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
remove `kubernetes.io/grpc` standard appProtocol as it can not be well defined yet. 
We have no clear guidance on how implementations should implement it, for example is is grpc over TLS or over cleartext and as well how should it be different from http2. 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
remove `kubernetes.io/grpc` standard appProtocol
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
`kubernetes.io/grpc` added in  https://github.com/kubernetes/kubernetes/pull/115433

```docs

```
/assign @thockin 
/cc @robscott 
/cc @howardjohn

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @LiorLieberman! I agree that this is not specified clearly enough to include in 1.27, and it's too late to try to build consensus around a tighter definition of the term. Given that, I think the safest approach is to pull this out prior to release.

/lgtm
/assign @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by LiorLieberman** [comment]
Can we add 1.27?

**Comment by salaxander** [comment]
@LiorLieberman @robscott @thockin  - we are a week past code freeze for 1.27, and this was merged today in the middle of a release candidate cut. In the future, please let us know about any PRs that would need to be merged. At this point it should only be release blocking items.

**Comment by thockin** [comment]
That's my fault - I lost track of where we were - if you need to kick
this out to the .1 release, that is fine.

**Pull request merged**
