### PR TITLE
Automated cherry pick of #115978: Tolerate empty discovery response in memcache client

### PR DESCRIPTION
**Pull request by seans3**
Cherry pick of #115978 on release-1.26.

#115978: Tolerate empty discovery response in memcache client

/kind bug

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.26 regression in client-go discovery handling of empty responses
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by kerthcet** [comment]
/kind feature

Seems added on purpose. 🥲

**Pull request merged**
