### PR TITLE
Replace monit with supervisord in documentation.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by dchen1107** [comment]
You beat me on this one. :-) 

LGTM

**Comment by dchen1107** [comment]
But looks like you have to run hack/update-generated-docs.sh

FAIL: changes needed but not made due to --verify
/home/travis/gopath/src/github.com/kubernetes/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1

**Comment by roberthbailey** [comment]
I ran `hack/update-generated-docs.sh` and re-pushed my changes.

**Comment by dchen1107** [comment]
ok to test

**Comment by roberthbailey** [comment]
@ixdy there are some weird jenkins failures on my documentation PR. The jenkins unit tests failed with:

```
17:06:48 + ./hack/verify-all.sh -v
17:06:48 Skipping ./hack/../hack/verify-all.sh
17:06:48 Verifying ./hack/../hack/verify-api-reference-docs.sh
17:06:49 Generating api reference docs at /var/jenkins/workspace/kubernetes-pull-test-unit-integration@4/_tmp/api-reference
17:06:49 Reading swagger spec from: /var/jenkins/workspace/kubernetes-pull-test-unit-integration@4/api/swagger-spec/
17:06:49 docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
17:06:49 !!! Error in ./hack/../hack/verify-api-reference-docs.sh:41
17:06:49   '"./hack/update-api-reference-docs.sh" "${HOST_OUTPUT_DIR}"' exited with status 127
17:06:49 Call stack:
17:06:49   1: ./hack/../hack/verify-api-reference-docs.sh:41 main(...)
17:06:49 Exiting with status 1
17:06:49 FAILED
```

**Comment by ixdy** [comment]
Yup, looking. Apparently the docker-engine package doesn't work correctly on Debian 7.9 or something. Trying with lxc-docker instead.

@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
