### PR TITLE
Repeated err judgment in integration test

### PR DESCRIPTION
**Pull request by chymy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e.g.:
Repeat the code below:
https://github.com/kubernetes/kubernetes/blob/35bc0fbad5cd87f1e67fe1f654e616891afbe997/test/integration/namespace/ns_conditions_test.go#L148

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chymy** [comment]
/assign @aojea 
Thanks.

**Comment by aojea** [comment]
/ok-to-test
/lgtm
/assign @wojtek-t @deads2k 
probably leftovers from a refactor?

**Comment by aojea** [comment]
@chymy there is a problem with the formatting
```
Run ./hack/update-gofmt.sh
```

**Comment by chymy** [comment]
> @chymy there is a problem with the formatting
> 
> ```
> Run ./hack/update-gofmt.sh
> ```

Thanks, fixed.

**Pull request merged**
