### PR TITLE
Remove kubeproxy dependencies from kubernetes repo - Constants and core helper functions

### PR DESCRIPTION
**Pull request by rikatz**
/kind cleanup

#### What this PR does / why we need it: 

This PR is the kickstart of the effort to move kube-proxy from k/k to staging described in issue #92369 

The initial step is to check what sort of internal k/k vendoring kube-proxy does (like helper functions), the impact of moving them and start moving.

This first PR:
* Moves all the helper functions to staging/component-helpers (previous art already exists by sig-scheduling helpers)
* Moves constant only in use by kube-proxy to staging/kube-proxy/config api
* Point files using the old library/functions to the new one

#### Special notes for your reviewer:
* I didn't removed the pkg/apis/core/helpers duplicate functions (with pkg/api/v1/service/util ones) because apparently a bunch of internal parts of the apiserver uses it. It's worth to verify with sig-apimachinery how they want to deal with this cleanup
* There are some other steps that need to be taken in the future, like creating kubeproxy own FeatureGate set (as controller manager already does), moving the ipvs helper functions to somewhere new where everybody can use (staging/network-utils?) and then remove the kube-proxy from the tree
* As this initial step is just a cleanup, I didn't though a KEP would be necessary yet, but as we decide to move, maybe a simple kep should be created

```release-note
NONE
```

/sig network
/sig apimachinery

### CODE REVIEW

**Comment by rikatz** [comment]
/assign @thockin @caseydavenport 
The beginning to move k/proxy out of the tree starts with us moving some helper functions that are spread on the repo to components-helper (previous arts by sig-scheduling)

**Comment by dougsland** [comment]
adding this one in my radar 
/cc @dougsland

**Comment by jayunit100** [comment]
hiya @dims , FYI https://groups.google.com/g/kubernetes-sig-network/c/A2X5oEHolto ...

**Comment by ehashman** [comment]
/remove-sig node

I don't see any node-owned files here, ping us if I'm wrong

**Comment by rikatz** [comment]
@ehashman sig-node was marked because those 4 files changed:

https://github.com/kubernetes/kubernetes/pull/100931/files#diff-8de13df72b684e6c3b032def311c1a8fc6764fc8cbc901695464373ff799e2fe
https://github.com/kubernetes/kubernetes/pull/100931/files#diff-8de13df72b684e6c3b032def311c1a8fc6764fc8cbc901695464373ff799e2fe
https://github.com/kubernetes/kubernetes/pull/100931/files#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0d
https://github.com/kubernetes/kubernetes/pull/100931/files#diff-28a2444beb8180d616b54452cc633120796284b69bb1b227ef40ab1390c25846


But the changes are more related to just pointing the libraries from internal k/k to external component-helper libraries :)

**Pull request closed without merging**
