### PR TITLE
Move scheduler out of plugin directory

### PR DESCRIPTION
**Pull request by misterikkit**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This is but one step toward resolving the referenced issue.
/ref #57579

**Special notes for your reviewer**:

**Release note**:

```release-note
Default scheduler code is moved out of the plugin directory.
plugin/pkg/scheduler -> pkg/scheduler
plugin/cmd/kube-scheduler -> cmd/kube-scheduler
```
/sig scheduling

### CODE REVIEW

**Comment by thockin** [comment]
I love this.  I'd like someone who works on scheduler to ACK that they don't have problems with this.

@kubernetes/sig-scheduling-pr-reviews @bsalamat

**Comment by ConnorDoyle** [comment]
/kind cleanup
+1 for this!

**Comment by resouer** [comment]
Seems need to be with milestone and included into release if we decide to do so.

**Comment by aveshagarwal** [comment]
@misterikkit change LGTM as its mainly path change from kubernetes/plugin/pkg/scheduler to kubernetes/pkg/scheduler.

**Comment by misterikkit** [comment]
Thanks for taking a look. I've fixed bazel and rebased.

**Comment by bsalamat** [comment]
Jonathan spoke with me and I have already given him LGTM on the idea of moving scheduler out of plugins directory.

Please fix the build/tests.

**Comment by brendandburns** [comment]
/lgtm

Given @bsalamat comment above. No harm in LGTM before the tests are green since it won't merge w/o green tests.

**Comment by bsalamat** [comment]
/lgtm
as well. Thanks, @misterikkit!

**Pull request merged**
