### PR TITLE
Re-use podAttachTimeout when waiting for pod readiness

### LINKED ISSUE #87851: [Failing Test] gce-master-scale-correctness: [sig-cli] Kubectl client Simple pod should return command exit codes
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
[sig-cli] Kubectl client Simple pod should return command exit codes 

**Since when has it been failing**:
02/05

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
Feb  5 12:32:40.354: Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.243.250.2 --kubeconfig=/workspace/.kube/config --namespace=kubectl-3790 run -i --image=docker.io/library/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42:\nCommand stdout:\n\nstderr:\nError from server (NotFound): pods \"failure-4\" not found\n\nerror:\nexit status 1",
        },
        Code: 1,
    }
    error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.243.250.2 --kubeconfig=/workspace/.kube/config --namespace=kubectl-3790 run -i --image=docker.io/library/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42:
    Command stdout:
    
    stderr:
    Error from server (NotFound): pods "failure-4" not found
    
    error:
    exit status 1
```

**Anything else we need to know**:

/sig cli

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup
/kind failing-test

**What this PR does / why we need it**:
There was a nasty TODO for wiring a timeout when waiting for a ready pod in `kubectl run` command that was hard coded to 0. This PR re-uses the pod timeout which defaults to 60 and can be extended by a user. 

**Which issue(s) this PR fixes**:
Fixes #87851 #89811

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig cli
/sig scalability 

/assign @seans3

### CODE REVIEW

**Comment by wojtek-t** [comment]
Nice finding!

/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

@kubernetes/ci-signal

**Comment by mm4tt** [comment]
Nice!

**Pull request merged**
