### PR TITLE
Deployment e2e tests to wait for async actions to happen rather than check it immediately

### LINKED ISSUE #22218: Deployment e2e tests should wait for async actions to happen rather than checking it immediately.
https://github.com/kubernetes/kubernetes/issues/22122#issuecomment-189642102

For example, rollback test should wait for status to become equal rather than checking it immediately after pods are observed. 
```go
    // Verify that the required pods have come up.
    err = verifyPods(unversionedClient, ns, "nginx", false, deploymentReplicas)
    if err != nil {
        Logf("error in waiting for pods to come up: %s", err)
        Expect(err).NotTo(HaveOccurred())
    }
    deployment, err = c.Extensions().Deployments(ns).Get(deploymentName)
    Expect(err).NotTo(HaveOccurred())
    // DeploymentStatus should be appropriately updated.
    Expect(deployment.Status.Replicas).Should(Equal(deploymentReplicas))
    Expect(deployment.Status.UpdatedReplicas).Should(Equal(deploymentReplicas))
```

cc @kubernetes/sig-config

### PR DESCRIPTION
**Pull request by janetkuo**
Depends on #22202 (the first commit); fixes #22218

@bgrant0607 @kubernetes/sig-config

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #22244

**Comment by bgrant0607** [comment]
LGTM, thanks!

**Comment by bgrant0607** [comment]
Waiting on #22202 to merge before applying lgtm.

**Comment by bgrant0607** [comment]
Applying lgtm since #22202 is at the front of the submit queue.

**Comment by janetkuo** [comment]
Rebased

**Comment by janetkuo** [comment]
Tests failed to start. Slave went offline during the build. 

@k8s-bot test this issue: #IGNORE

**Pull request merged**
