### PR TITLE
Fix for issue #14466.

### LINKED ISSUE #14466: AWS VPC lookup should not use tag filtering
In the AWS cloud provider's VPC lookup - given the vpc_id is being read directly from metadata from the local instance, there's no need to additionally filter on the KubernetesCluster tag.  Not only is this superfluous, but it prevents sharing a single regional VPC with multiple per-AZ Kubernetes clusters (per best practices).

### PR DESCRIPTION
**Pull request by chris-codaio**
Don't use tag filtering when looking up which VPC an AWS instance (node) is attached to.

cla:yes

Fixes #14466

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @justinsb

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
Nicely surgical. LGTM.  cc: @justinsb 
@chrisleck I assume that you ran the AWS e2e tests against this?

**Comment by chrisleck** [comment]
No, I didn't find any instructions for running AWS e2e tests.  Could you point me in the right direction?

**Comment by chrisleck** [comment]
Thanks, Brian!

**Pull request merged**
