### PR TITLE
kubeadm: clean deps on k8s.io/kubernetes/pkg/registry/core/service/ipallocator

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
kubeadm: clean deps on k8s.io/kubernetes/pkg/registry/core/service/ipallocator
I find that `RangeSize` and `GetIndexedIP` are used more often in kubeadm, so I prefer to copy them into kubeadm.
In order to solve the circle dependency problem(constants -> util -> constants), I put `net.go` into a new package `network`.

**Which issue(s) this PR fixes**:

ref: kubernetes/kubeadm#1600

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
i think that Yassine mentioned that he is working on this already?
/cc @yastij

**Comment by yastij** [comment]
/hold

We should avoid duplicating code. I'm waiting on https://github.com/kubernetes/utils/pull/112/files

**Review by yastij — COMMENTED** [review]
/hold

We should avoid duplicating code. I'm waiting on https://github.com/kubernetes/utils/pull/112

**Comment by SataQiu** [comment]
Alright! Sorry for missing that. @yastij
I will close this.

**Pull request closed without merging**
