### PR TITLE
Renaming strict policy to restricted policy

### PR DESCRIPTION
**Pull request by lmdaly**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Topology Manager based merged design proposal here: kubernetes/community#1680
Issue for tracking PRs: #72828
Strict policy semantics were not well understood, the Restricted policy will fail admission of guaranteed pods where all requested resources are not available on a single NUMA Node.
This PR is renaming the Policy.
PR: https://github.com/kubernetes/kubernetes/pull/81586 adds the logic for this.

**Does this PR introduce a user-facing change?**:
Topology-manager-policy Kubelet flag option strict renamed to restricted

### CODE REVIEW

**Comment by lmdaly** [comment]
@ConnorDoyle @klueska @nolancon

**Comment by ConnorDoyle** [comment]
Could you also create a PR to update the policy name in the KEP, so people don't get confused if they see it?

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/test pull-kubernetes-bazel-test

Confirming no one is actually using this code yet correct? So we don't have to worry about backwards compat?

**Comment by ConnorDoyle** [comment]
/retest

Yes, correct @mattjmcnaughton. However it would be best to get this into 1.16 to avoid making early adopters of this alpha feature switch from `strict` to `restricted` in 1.17

**Comment by mattjmcnaughton** [comment]
On Fri, Aug 23, 2019 at 03:28:40PM -0700, Connor Doyle wrote:
> /retest
> 
> Yes, correct @mattjmcnaughton. However it would be best to get this into 1.16 to avoid making early adopters of this alpha feature switch from `strict` to `restricted` in 1.17
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81787#issuecomment-524481473

Sounds good to me :)

**Comment by lmdaly** [comment]
> Could you also create a PR to update the policy name in the KEP, so people don't get confused if they see it?

@ConnorDoyle Sure! 
PR created https://github.com/kubernetes/enhancements/pull/1222

**Pull request merged**
