### PR TITLE
Fix inconsistency between the comment and the actual feature gate definition

### LINKED ISSUE #127181: Status of APIServingWithRoutine gate
### What happened?

The code says this (staging/src/k8s.io/apiserver/pkg/features/kube_features.go):

```go
	APIServingWithRoutine: {Default: false, PreRelease: featuregate.Alpha},
```

While the comment says this (staging/src/k8s.io/apiserver/pkg/features/kube_features.go):

```go
	// owner: @linxiulei
	// beta: v1.30
	//
	// Enables serving watch requests in separate goroutines.
	APIServingWithRoutine featuregate.Feature = "APIServingWithRoutine"
```

So..., what happened? The feature is still Alpha or it is a Beta?

### What did you expect to happen?

Be consistent about the features we add or change.

### How can we reproduce it (as minimally and precisely as possible)?

Read the code.

### Anything else we need to know?

_No response_

### Kubernetes version

1.30.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Adarsh-verma-14**
Fix inconsistency between the comment and the actual feature gate definition for APIServingWithRoutine in kube_features.go

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #127181

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/ok-to-test
/lgtm
/assign @jpbetz

Per https://github.com/kubernetes/kubernetes/issues/127181, "This feature has been demoted from Beta to Alpha. That is fine. We need to revise the code comment then.". Comment now matches feature status further down in the file.

https://github.com/kubernetes/kubernetes/blob/8f471803cb386c2a227fa61e922822aab168ec95/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L328

**Comment by Adarsh-verma-14** [comment]
> /ok-to-test /lgtm /assign @jpbetz
> 
> Per #127181, "This feature has been demoted from Beta to Alpha. That is fine. We need to revise the code comment then.". Comment now matches feature status further down in the file.
> 
> https://github.com/kubernetes/kubernetes/blob/8f471803cb386c2a227fa61e922822aab168ec95/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L328

Thanks @Jefftree  for adding this!!

**Pull request merged**
