### PR TITLE
Add Support For Kubernetes 0.15.0 On Azure

### PR DESCRIPTION
**Pull request by idoshamun**

### CODE REVIEW

**Comment by idosh** [comment]
I signed it!

**Comment by roberthbailey** [comment]
@idosh Thanks for the PR!

This LGTM but can you squash your commits before I merge?

**Comment by idosh** [comment]
What do you mean by "squash your commits"?

**Comment by roberthbailey** [comment]
Right now your PR history shows 9 commits. I'd like to see 1 instead. You can run something like `git rebase -i HEAD~9` to take your last 9 commits and squash them into a single commit (fixing up your commit message at the same time). For a quick tutorial, see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by idosh** [comment]
I got a little trouble with it, can't push it back to origin.
It says that everything is update.

**Comment by roberthbailey** [comment]
Once you've made your changes locally, you will want to `push -f` to origin to rewrite history. Then github will pick it up and you'll see 1 commit in the web UI.

**Comment by idosh** [comment]
I tried it before and it didn't work...

**Comment by roberthbailey** [comment]
I'm a bit confused as to why your branch is called `crossorigin:master`. On all of the other PRs I see the source branch is `github-id:branch-name` so I would expect your branch to be something like `idosh:azure`. Is your git origin set to https://github.com/crossorigin or https://github.com/idosh?

**Comment by idosh** [comment]
https://github.com/crossorigin
Can you close this one and I'll open a new one with one commit?

**Comment by idosh** [comment]
Just created a new one

**Pull request closed without merging**
