### PR TITLE
Better regexp in cpu manager node e2e test

### PR DESCRIPTION
**Pull request by dims**
Looks like we may find comma(s) as well! 

Snippet from build log [here](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2/1673830473123500032/build-log.txt). This is on an `ubuntu-2204` EC2 node:
```
  Jun 28 00:10:51.660: INFO: Unexpected error: expected log not found in container [non-gu-container] of pod [non-gu-pod]: 
      <*errors.errorString | 0x40014038d0>: 
      failed to match regexp "^0-3\n$" in output "0,3\n"
      {
          s: "failed to match regexp \"^0-3\\n$\" in output \"0,3\\n\"",
      }
  [FAILED] in [It] - test/e2e_node/cpu_manager_test.go:275 @ 06/28/23 00:10:51.661
```

A couple of our markdown files also show comma(s) in `Cpus_allowed_list`
https://cs.k8s.io/?q=Cpus_allowed_list.*%5C%2C&i=nope&files=&excludeFiles=&repos=

[cpuset man pages](https://man7.org/linux/man-pages/man7/cpuset.7.html#:~:text=1%2C%20and%200.-,List%20format,-The%20List%20Format) shows examples with comma(s)

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
This is changing the test I believe.  Maybe its failing for real here?

Current test is to check if it can run on any processor (0-3), where the result you're seeing is that it can only run on 0 & 3.

**Comment by chendave** [comment]
> Current test is to check if it can run on any processor (0-3), where the result you're seeing is that it can only run on 0 or 3.

+1, I doubt that this is a right fix for this.

I tested on ubuntu18 and ubuntu22 respectively, 

- ubuntu18.04
>   lsb_release -a | grep Description
No LSB modules are available.
Description:    Ubuntu 18.04.6 LTS

the test always failed with different errors, 

 >  [FAILED] expected log not found in container [gu-container] of pod [gu-pod]: failed to match regexp "^1,29,57,85\n$" in output "28,56\n"
  In [It] at: /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/cpu_manager_test.go:388 @ 06/28/23 14:35:53.953



- ubuntu22

> lsb_release -a | grep Description
No LSB modules are available.
Description:    Ubuntu 22.04.1 LTS

>  I0628 08:49:03.567751  184967 e2e_node_suite_test.go:269] Tests Finished
> [SynchronizedAfterSuite] PASSED [0.143 seconds]

> Ran 1 of 430 Specs in 883.840 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 429 Skipped
PASS


I think we need someone from sig-node to comments on this.

/assign @SergeyKanzhelev

**Comment by chendave** [comment]
I might not have enough bandwidth on this in the near future, cc @ruquanzhao can you pls check the context of this testcase? particularly the failure msg I hit on ubuntu18.04

**Comment by dims** [comment]
going back to a smaller instance, cleaned up the failures, but i do think we need to open up an issue for sig-node to fix these tests that fail on larger instances.

https://github.com/kubernetes-sigs/provider-aws-test-infra/commit/9af3a1989f7d24309716233165f0721c3be7c9d0

image

(see last 3 rows)

**Comment by chendave** [comment]
> but i do think we need to open up an issue for sig-node to fix these tests that fail on larger instances.

tracked here: https://github.com/kubernetes/kubernetes/issues/118968.

**Pull request closed without merging**
