### PR TITLE
fix shellcheck in csi-api

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fix shellcheck failures in `staging/src/k8s.io/csi-api`

**Which issue(s) this PR fixes**:

work towards #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielqsj** [comment]
@saad-ali @jsafrane @soltysh if you have time, can you help review this? Thanks

**Comment by sttts** [comment]
/assign @jsafrane

Can you approve?

**Comment by danielqsj** [comment]
rebased
@jsafrane can you help review it ?

**Pull request merged**
