### PR TITLE
Customize apiserver serviceName for tracing

### PR DESCRIPTION
**Pull request by AnishMadan**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Currently, all traces are sent out with the same `service.name` of `apiserver`. 

This isn't ideal as I'd like to have a single collector route multiple instances of different kube api servers.

As a result, allowing the user to customize the `service.name` is a potential solution.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by AnishMadan** [comment]
@RainbowMango @soltysh any timeline for review?

**Comment by jiahuif** [comment]
/assign @logicalhan 
For sig instrumentation. Thank you.
/triage accepted

**Comment by AnishMadan** [comment]
@logicalhan any timeline for review?

**Review by logicalhan — COMMENTED** [review]
/assign @dashpole

**Comment by AnishMadan** [comment]
hi @dashpole, customizing a `service.name` should not contradict what is written in the documentation. Specifically, all instances in the scaled application would be running with the same customized `service.name`. 

I'd be happy to try using the `OTEL_RESOURCE_ATTRIBUTES` env variable, is there any documentation in how to utilize this with the kube-apiserver? I'm assuming it will be picked up automatically?

Would it be something like 

`OTEL_RESOURCE_ATTRIBUTES=key=value kube-apiserver ... --tracing-config-file x/y/z`?

**Comment by dashpole** [comment]
You can see the format here: https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_resource_attributes.  It should work as you described.

**Comment by dashpole** [comment]
/close

Feel free to ping me on slack if you have further questions, or open an issue and CC me

**Pull request closed without merging**
