### PR TITLE
Remove all docs which are moving to http://kubernetes.github.io

### PR DESCRIPTION
**Pull request by eparis**
All .md files now are only a pointer to where they likely are on the new site.

All non .md files are removed.

### CODE REVIEW

**Comment by eparis** [comment]
@bgrant0607 @johndmulhausen

**Comment by bgrant0607** [comment]
Cool. We need to make the verification checks ignore these.

**Comment by bgrant0607** [comment]
Hmm. That's not it.

The examples test failed. Please don't remove the non-markdown files yet.

**Comment by eparis** [comment]
Saw that. Do you want me to leave all .yaml, or just move those which are still referenced somewhere to live on? I was planning to move them in the morning. How about .js files? .svg? There's a bunch of stuff in there.

**Comment by eparis** [comment]
@bgrant0607 I am ready to merge this as soon as we fork if you are. I reduced it's scope. Right now all it does it blow away the .mds.  Leaves everything else alone. Working on fixing stuff up in another PR.

**Comment by bgrant0607** [comment]
Heads up: 1.2 branch is cut. Merging this.

**Comment by bgrant0607** [comment]
The docs have been copied and we have a tag where the docs still existed, so I think it's safe for this to be in the release branch at this point.

**Pull request merged**
