### PR TITLE
Refactored files containing whitelist/blacklist to allowlist/denylist…

### PR DESCRIPTION
**Pull request by mgutierrez98**
#### What type of PR is this?
/kind documentation
/sig docs
/wg naming

#### What this PR does / why we need it:
Refactored files containing whitelist/blacklist to allowlist/denylist

#### Which issue(s) this PR fixes:
Fixes #

#### Special notes for your reviewer:
References issue #90277 
Continuation of closed PR #103222 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by mgutierrez98** [comment]
@lavalamp @liggitt Very sorry I closed the last PR. It was a mistaken forced push on my end as I learn Git... I know it's looked down upon and I do apologize.

**Comment by lavalamp** [comment]
>  I know it's looked down upon and I do apologize.

It's really not a big deal, no worries

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
