### PR TITLE
use groupmetafactoryregistry

### PR DESCRIPTION
**Pull request by deads2k**
Switches all groups to the new API registration mechanism.

@ncdc ptal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33017)

### CODE REVIEW

**Review by ncdc — APPROVED** [review]
LGTM

**Comment by ncdc** [comment]
unit/int failure:

```
+ ./hack/test-update-storage-objects.sh
make: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Leaving directory '/go/src/k8s.io/kubernetes'
+++ [0919 08:28:11] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0919 08:28:12] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0919 08:28:12] Building go targets for linux/amd64:
    cmd/kube-apiserver
make: Leaving directory '/go/src/k8s.io/kubernetes'
make: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Leaving directory '/go/src/k8s.io/kubernetes'
+++ [0919 08:28:20] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0919 08:28:20] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0919 08:28:21] Building go targets for linux/amd64:
    cluster/images/etcd/attachlease
make: Leaving directory '/go/src/k8s.io/kubernetes'
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.h44B4IeEq4 --listen-client-urls http://127.0.0.1:2379 --debug > "/workspace/artifacts/etcd.812b76eae983.root.log.DEBUG.20160919-082823.2020" 2>/dev/null
Waiting for etcd to come up.
+++ [0919 08:28:24] On try 1, etcd: : 
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0919 08:28:24] Starting kube-apiserver with KUBE_API_VERSIONS: v1,extensions/v1beta1,v1,extensions/v1beta1,batch/v1,autoscaling/v1
+++ [0919 08:28:24]                            and storage-backend: etcd2
+++ [0919 08:28:24]                         and storage-media-type: application/json
+++ [0919 08:28:24]                             and runtime-config: api/all=false,api/v1,extensions/v1beta1=true,api/v1,extensions/v1beta1,batch/v1,autoscaling/v1=true
+++ [0919 08:28:24]                  and storage-version overrides: batch=extensions/v1beta1,autoscaling=extensions/v1beta1
panic: Group apps is not registered.

goroutine 1 [running]:
panic(0x2ed3c80, 0xc8204eb570)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).GroupOrDie(0xc8204f1e50, 0x3fe1990, 0x4, 0x8)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:294 +0x21e
k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).GroupOrDie-fm(0x3fe1990, 0x4, 0xc82022a680)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:107 +0x34
k8s.io/kubernetes/pkg/apimachinery/announced.(*GroupMetaFactory).RegisterAndEnable(0xc8204cbbf0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apimachinery/announced/group_factory.go:247 +0x102
k8s.io/kubernetes/pkg/apis/apps/install.init.1()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apis/apps/install/install.go:28 +0x1c1
k8s.io/kubernetes/pkg/apis/apps/install.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apis/apps/install/install.go:41 +0x4a
k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/import_known_versions.go:42 +0x94
k8s.io/kubernetes/pkg/volume/util.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/util.go:159 +0x81
k8s.io/kubernetes/pkg/volume.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/volume_linux.go:81 +0x49
k8s.io/kubernetes/pkg/cloudprovider/providers/aws.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/sets_ippermissions.go:146 +0xd3
k8s.io/kubernetes/pkg/cloudprovider/providers.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/providers.go:30 +0x3b
k8s.io/kubernetes/cmd/kube-apiserver/app.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:312 +0x3f
main.init()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:54 +0x4f
```

**Comment by ncdc** [comment]
It looks like if #32897 goes in first, it will clear up this failure

**Comment by nikhiljindal** [comment]
Thanks @deads2k 
cc @lavalamp as FYI

**Comment by lavalamp** [comment]
oh wow, awesome. I was planning on getting https://github.com/kubernetes/kubernetes/pull/31399 in before doing this everywhere but if you're doing it, that's fine by me :) :)

**Pull request merged**
