### PR TITLE
Fix deleting pod failed when it's amounted to emptyDir in case of /var/lib/kubelet is symlink

### LINKED ISSUE #96916: Pods will be deleted failly when they are amounted to emptyDir with the type of medium is "HugePages"
**What happened**:
Pods will be deleted failly when they are amount to emptyDir with the type of medium is "HugePages", while /var/lib/kubelet is symlink.

**What you expected to happen**:
Delete the pods successffuly.

**How to reproduce it (as minimally and precisely as possible)**:
1、deploy a pod and amouting to emptyDir , setting medium to "HugePages", for example,
apiVersion: v1
kind: Pod
metadata:
  name: huge-pages-example
spec:
  containers:
  - name: example
    image: fedora:latest
    command:
    - sleep
    - inf
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      limits:
        hugepages-2Mi: 4Mi
        memory: 20Mi
      requests:
        memory: 20Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages

2. make /var/lib/kubelet  a symlink of other dirs, such as /var/lib/kubelet_bak
image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by lala123912**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix the bug of deleting pod failed when it's amounted to emptyDir setting medium to "HugePages" in the case that the path "/var/lib/kubelet" is symlink.

**Which issue(s) this PR fixes**:
Fixes #96916

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by sjenning** [comment]
Not really sure if we support `/var/lib/kubelet` being a symlink.  I imagine this isn't the only place that will be an issue for the kubelet.
/cc @derekwaynecarr

**Comment by lala123912** [comment]
> Not really sure if we support `/var/lib/kubelet` being a symlink. I've never heard of someone attempting this before. I imagine this isn't the only place that will be an issue for the kubelet.
> 
> What is the use case for doing this?
> 
> /cc @derekwaynecarr

In the case of disk failure， our product will migrate the data to a new disk and set the original path a sysmlink  to the new path to ensure the normal business. @sjenning

**Comment by saad-ali** [comment]
CC @jsafrane @xing-yang @msau42 @pmorie 

Are there any assumptions the existing code makes that might break if `/var/lib/kubelet` is treated as a symlink here? Any security concerns?

**Comment by jsafrane** [comment]
I don't think it can cause security issues - anyone who can modify `/var` or `/var/lib` is IMO powerful enough to break the system in easier ways than symlinks.

Still, we do not test `/var/lib/kubelet` as a symlink and it breaks things on various places, e.g. block volumes in https://github.com/kubernetes/kubernetes/issues/96888

I'd strongly suggest mounts (bind mounts?) instead of symlinks.

**Pull request closed without merging**
