### PR TITLE
Fix all GPUs exposed when the limit of "nvidia.com/gpu" == 0

### LINKED ISSUE #59629: DevicePlugin is not working correct when the limit set to 0
/kind bug
/sig node
/area hw-accelerators
/cc @vishh @jiayingz @vikaschoudhary16 @RenaudWasTaken 

**What happened**:
we can see all GPUs in container (`nvidia-smi`) when the limit of "nvidia.com/gpu" set to 0
also, `ls /dev/nvidia*` in container can see all GPU device files.

**What you expected to happen**:
`ls /dev/nvidia*` in container shows nothing when the limit of "nvidia.com/gpu" set to 0

**How to reproduce it (as minimally and precisely as possible)**:

yaml file:
```
apiVersion: v1
kind: Pod
metadata:
    name: fff
spec:
  containers:
  - name: fff
    image: nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
    resources:
      limits:
        nvidia.com/gpu: "0"
      requests:
        nvidia.com/gpu: "0"
    command: ["/bin/sh", "-c"]
    args: ["sleep 10d;"]
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by pineking**
**What this PR does / why we need it**:
when `nvidia.com/gpu' == 0, an empty allocDevices will pass to RPC calls. this will make the env `NVIDIA_VISIBLE_DEVICES` to an empty string, so the issue can be fixed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59629 

**Special notes for your reviewer**:
1. this PR will cache empty deviceIds in `m.podDevices.insert(podUID, contName, resource, allocDevices`, resp) https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L651, I'm not sure it's OK?

2. According to the doc,  https://github.com/nvidia/nvidia-container-runtime#environment-variables-oci-spec, which is better to the value of `NVIDIA_VISIBLE_DEVICES` for the limit == 0 case, empty of "none"?

/cc @jiayingz @vikaschoudhary16 @RenaudWasTaken 

**Release note**:

```release-note
Fix all GPUs exposed when the limit of "nvidia.com/gpu" == 0
```

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
IMO, this fix should be done in device plugin rather in device manager. Current behavior is valid and this PR does not make sense to me.

**Comment by pineking** [comment]
@vikaschoudhary16 I also thought this should be fixed in `nvidia.com/k8s-device plugin`, so I will close this PR and look forward to someone can fix it in device plugin.  but that's not easy https://github.com/NVIDIA/k8s-device-plugin/issues/27 since the device plugin is not called when the limit == 0 or no GPU request.

**Comment by RenaudWasTaken** [comment]
I wouldn't close it right now, it has some interesting debate elements.

That bug is mostly due to the limitations of the API which doesn't offer a "generic" pre-start hook, and forces us to set the default runtime as NVIDIA.
It also makes sense to expect the device plugin to be called if the resource was specified (even if it equals 0).

On the other hand, if `nvidia.com/gpu` is equal to 0, you can't expect the task to land on a GPU node which I think is the biggest argument against this PR. 

> IMO, this fix should be done in device plugin rather in device manager. 

I think this is what this fix is trying to do, have the device plugin do the work rather than bypass it when the device is equal to 0.

**Comment by vikaschoudhary16** [comment]
I see this as a gap on runc side or on CRI side for not allowing to drop hooks dynamically. Therefore someone else's bill should be charged on Device Manager.

**Pull request closed without merging**
