### PR TITLE
Fix typo in e2e-node-test.sh

### PR DESCRIPTION
**Pull request by aditya-konarde**
Correct 'Makfile' to 'Makefile'

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@aditya-konarde thanks for contribution! please sign your CLA before we can merge your PR :)

**Comment by aditya-konarde** [comment]
bump to verify CLA

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks!

**Pull request merged**
