### PR TITLE
Bump fluentd-gcp to version 2.0.1

### PR DESCRIPTION
**Pull request by timstclair**
Fixes https://github.com/kubernetes/kubernetes/issues/42515

### CODE REVIEW

**Comment by crassirostris** [comment]
@timstclair Thanks! Also `cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml` for hosted masters

**Comment by timstclair** [comment]
Added the master config.

**Comment by Crassirostris** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
