### PR TITLE
ubuntu cluster utils.sh verify-ssh-prereqs

### PR DESCRIPTION
**Pull request by MCyprien**
PR for [#8559](https://github.com/GoogleCloudPlatform/kubernetes/issues/8559)

### CODE REVIEW

**Comment by resouer** [comment]
@MCyprien  Thanks, we'd like to give it a review, but please fix your cla first :)

**Comment by MCyprien** [comment]
ok I signed the CLA, I think

**Comment by MCyprien** [comment]
what about now my sweet googlebot?

**Comment by dchen1107** [comment]
LGTM. Oncall will pick it up and merge it based on our e2e test result. We ran into some issues with our Jenkin e2e tests lately, and tried to control the merge rate a little bit.

**Pull request merged**
