### PR TITLE
Add GCE "Custom" folder 

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
Allows creating clusters with image type custom

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

This will need to be cherrypicked back to the 1.9 branch

/assign @dchen1107 @yguo0905

### CODE REVIEW

**Comment by dchen1107** [comment]
/lgtm

cc/ @filbranden

**Comment by dashpole** [comment]
it will need approve-no-issue

**Comment by dashpole** [comment]
Doesnt look like it was actually cherrypicked... https://github.com/kubernetes/kubernetes/tree/release-1.9/cluster/gce doesnt have the custom folder.
Opened #58099 to cherrypick it.

**Comment by dashpole** [comment]
This needs to be cherrypicked to 1.8 since we are testing on that version as well.

**Pull request merged**
