### PR TITLE
[kube-proxy] Fix for non-blocking updates during min-sync-period

### PR DESCRIPTION
**Pull request by danwinship**
This is a continuation of #37726; i'm just taking the PR over for @timothysc.

This initial push is identical to the current state of the old PR; I still need to address @thockin's comments from https://github.com/kubernetes/kubernetes/pull/37726#discussion_r97859239

### CODE REVIEW

**Comment by thockin** [comment]
Dan,

The biggest problem is that the On*Update functions run sync, but syncRules runs async.  I have a branch that is starting to fix that, could use help (just a bit tedious).

I am ooo today and tomorrow, can we chat Monday maybe and split up the work?  I really want this to get done.

**Comment by thockin** [comment]
Specifically it needs tests to refactor safely :)

**Comment by danwinship** [comment]
@thockin sure, I'm around Monday.

I've just pushed my attempted fix (rebased on top of #39484). It just accumulates the conntrack cleanups and then only deletes the stale records after a successful syncProxyRules().

**Comment by thockin** [comment]
Some of this still applies - is it salvageable?

**Comment by timothysc** [comment]
umm I would hope so, and I would call this release blocker worthy.

**Comment by danwinship** [comment]
yeah... was #41030 going to go in though? Oh, I never finished reviewing that...

**Comment by danwinship** [comment]
or was the idea to merge this first and then that one?

**Comment by thockin** [comment]
#41030 is not done or even completable without a bit more work on
OnServiceUpdate.  It all got side-swiped by the other work to mitigate
no-op changes.

Given the multitude of changes that went into kube-proxy in the last 3
weeks, we should re-assess the urgency of this for 1.6.  We absolutely want
to do something this-ish or #41030 or both, but if the other mitigations
are good, maybe it's OK to delay to 1.6.x ?

**Comment by timothysc** [comment]
> Given the multitude of changes that went into kube-proxy in the last 3
weeks, we should re-assess the urgency of this for 1.6 

So the root issue is manifested in two scenarios: 

- Aggressive loading of services/endpoint updates at modest/large scale (iptables literally consumes core++) 
- Modest service churn @ high scale.  

In either of those two situations without some form of batching, k8s-operators will incur a non-trivial load on their kubelets.  So anyone operating a large cluster the urgency is **HIGH** 

/cc @kubernetes/sig-scalability-bugs @smarterclayton

**Comment by thockin** [comment]
My point was that there were changes to alleviate "phony" updates and to
lessen the cost of "real" updates.  I do not imply that this problem
(scale) doesn't exist, just that it is maybe not as dire as it was.  I'm
bringing up a new cluster to do some poking.

**Comment by ethernetdan** [comment]
Removing issue from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by calebamiles** [comment]
Moving this issue into the 1.7 milestone @danwinship

**cc: @ethernetdan, @timothysc, @thockin, @kubernetes/kubernetes-release-managers**

**Comment by danwinship** [comment]
test failures look like flakes...
@k8s-bot bazel test this
@k8s-bot gce etcd3 e2e test this

**Comment by danwinship** [comment]
more flakes. not sure what's up with the unit test. e2e failure is #36913.
@k8s-bot unit test this
@k8s-bot cvm gce e2e test this

**Comment by thockin** [comment]
We now have a different approach, after all @wojtek-t refactors.

**Pull request closed without merging**
