### PR TITLE
cleanup pkg/controller/replication

### PR DESCRIPTION
**Pull request by knightXun**
**What this PR does / why we need it**:
cleanup useless functions
**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by knightXun** [comment]
ping @mcrute, the test is ok.

**Comment by mcrute** [comment]
This looks ready to merge... adding @caesarxuchao for approval.

/lgtm
/unassign
/assign @caesarxuchao

**Comment by knightXun** [comment]
@mcrute thx, you are handsome

**Comment by mcrute** [comment]
One more try due to GitHub webhook wonkyness... 

This looks ready to merge... adding @caesarxuchao for approval.

/lgtm
/unassign
/assign @caesarxuchao

**Comment by mcrute** [comment]
Maybe GitHub and Prow are talking again... 

This looks ready to merge... adding @caesarxuchao for approval.

/lgtm
/unassign
/assign @caesarxuchao

**Comment by knightXun** [comment]
@caesarxuchao i think this pr can be merged.

**Comment by knightXun** [comment]
@caesarxuchao i think this pr can be merged.

**Pull request closed without merging**
