### PR TITLE
Continue killing containers in case of error

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In kubeGenericRuntimeManager#SyncPod, when error is encountered killing container(s), we should continue killing the remaining running containers in this pod which are not to keep.

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr :)

Do you know why this was originally coded so that we stopped trying to kill running containers as soon as we encountered an error? I just want to confirm this behavior wasn't intentional.

If we do decide to make the change to continue killing containers in the case of error, I think it'd be great to make it clear this behavior is intentional. A couple ways to do so could be:
1. Updating the comment on line 644 to indicate that we will continue killing containers in the case of error.
2. Extract the code from 645-655 into a helper function with a descriptive name (i.e. `killAllContainersIgnoringFailures`).
3. Add a unit test in which killing >= 1 container causes an error, and verify that we still kill the remaining containers.

**Comment by tedyu** [comment]
@feiskyer 
The code under discussion was added by you.

Do you mind shedding some light on why we only kill one container ?

thanks

**Comment by tedyu** [comment]
@feiskyer
Can you take a look ?

**Comment by feiskyer** [comment]
I think it's reasonable to continue kill other containers. Could you add a comment and unit tests for this change?

/remove-lifecycle stale

**Comment by feiskyer** [comment]
cc @Random-Liu @yujuhong

**Comment by tedyu** [comment]
I ran existing tests in kuberuntime_manager_test thru debugger.
```
		for containerID, containerInfo := range podContainerChanges.ContainersToKill {
```
No test got inside the above loop.
Will look for some way to add new test.

**Comment by tedyu** [comment]
Continuing the work over #84416

**Comment by tedyu** [comment]
/assign @Random-Liu

Can you take a look ?

**Pull request closed without merging**
