### PR TITLE
Make e2e-dns test more stable by increasing wait time

### LINKED ISSUE #43264: test [k8s.io] DNS [It] should provide DNS for the cluster [Conformance] failed against a local cluster due to failed to get pod
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
 Unable to read wheezy_tcp@kubernetes.default from pod
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"fa5b52858c06a963ed43bb8837f38cec5540b54d", GitTreeState:"clean", BuildDate:"2017-02-20T22:04:37Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
K8s cluster is deployed via Kargo on OpenStack.
- **OS** (e.g. from /etc/os-release):
Photon
- **Kernel** (e.g. `uname -a`):
Linux k8s-node-0-0a0b0b1e394386e6 4.4.26-esx #1-photon SMP Mon Oct 24 20:09:22 UTC 2016 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
I'm running the Conformance part of the end2end test. Two DNS test cases are failed:
1) 07:47:23 [Fail] [k8s.io] DNS [It] should provide DNS for the cluster [Conformance]
2) 07:47:23 [Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance] 

**What you expected to happen**:
They should pass.

**How to reproduce it** (as minimally and precisely as possible):
Followed the steps to kick off the test as https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#conformance-tests

**Anything else we need to know**:

07:27:45 Mar 13 07:37:23.127: INFO: >>> kubeConfig: /app/data/kubeconfig
07:27:45 
07:27:45 STEP: Building a namespace api object
07:27:45 STEP: Waiting for a default service account to be provisioned in namespace
07:27:45 [It] should provide DNS for the cluster [Conformance]
07:27:45   /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/dns.go:352
07:27:45 STEP: Running these commands on wheezy: for i in `seq 1 600`; do test -n "$$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK > /results/wheezy_udp@kubernetes.default;test -n "$$(dig +tcp +noall +answer +search kubernetes.default A)" && echo OK > /results/wheezy_tcp@kubernetes.default;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/wheezy_udp@kubernetes.default.svc;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/wheezy_tcp@kubernetes.default.svc;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/wheezy_udp@kubernetes.default.svc.cluster.local;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/wheezy_tcp@kubernetes.default.svc.cluster.local;test -n "$$(dig +notcp +noall +answer +search google.com A)" && echo OK > /results/wheezy_udp@google.com;test -n "$$(dig +tcp +noall +answer +search google.com A)" && echo OK > /results/wheezy_tcp@google.com;test -n "$$(getent hosts dns-querier-1.dns-test-service.e2e-tests-dns-pq6wt.svc.cluster.local)" && echo OK > /results/wheezy_hosts@dns-querier-1.dns-test-service.e2e-tests-dns-pq6wt.svc.cluster.local;test -n "$$(getent hosts dns-querier-1)" && echo OK > /results/wheezy_hosts@dns-querier-1;podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".e2e-tests-dns-pq6wt.pod.cluster.local"}');test -n "$$(dig +notcp +noall +answer +search $${podARec} A)" && echo OK > /results/wheezy_udp@PodARecord;test -n "$$(dig +tcp +noall +answer +search $${podARec} A)" && echo OK > /results/wheezy_tcp@PodARecord;sleep 1; done
07:27:45 
07:27:45 STEP: Running these commands on jessie: for i in `seq 1 600`; do test -n "$$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK > /results/jessie_udp@kubernetes.default;test -n "$$(dig +tcp +noall +answer +search kubernetes.default A)" && echo OK > /results/jessie_tcp@kubernetes.default;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/jessie_udp@kubernetes.default.svc;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/jessie_tcp@kubernetes.default.svc;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/jessie_udp@kubernetes.default.svc.cluster.local;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/jessie_tcp@kubernetes.default.svc.cluster.local;test -n "$$(dig +notcp +noall +answer +search google.com A)" && echo OK > /results/jessie_udp@google.com;test -n "$$(dig +tcp +noall +answer +search google.com A)" && echo OK > /results/jessie_tcp@google.com;test -n "$$(getent hosts dns-querier-1.dns-test-service.e2e-tests-dns-pq6wt.svc.cluster.local)" && echo OK > /results/jessie_hosts@dns-querier-1.dns-test-service.e2e-tests-dns-pq6wt.svc.cluster.local;test -n "$$(getent hosts dns-querier-1)" && echo OK > /results/jessie_hosts@dns-querier-1;podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".e2e-tests-dns-pq6wt.pod.cluster.local"}');test -n "$$(dig +notcp +noall +answer +search $${podARec} A)" && echo OK > /results/jessie_udp@PodARecord;test -n "$$(dig +tcp +noall +answer +search $${podARec} A)" && echo OK > /results/jessie_tcp@PodARecord;sleep 1; done
07:27:45 
07:27:45 STEP: creating a pod to probe DNS
07:27:45 STEP: submitting the pod to kubernetes
07:27:45 STEP: retrieving the pod
07:27:45 STEP: looking for the results for each expected name from probers
07:27:45 Mar 13 07:38:13.638: INFO: Unable to read wheezy_tcp@kubernetes.default from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:15.520: INFO: Unable to read wheezy_udp@kubernetes.default.svc from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:17.514: INFO: Unable to read wheezy_tcp@kubernetes.default.svc from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:20.376: INFO: Unable to read wheezy_udp@kubernetes.default.svc.cluster.local from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:22.834: INFO: Unable to read wheezy_tcp@kubernetes.default.svc.cluster.local from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:25.153: INFO: Unable to read wheezy_udp@google.com from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)
07:27:45 Mar 13 07:38:26.956: INFO: Unable to read wheezy_tcp@google.com from pod dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002: the server could not find the requested resource (get pods dns-test-e9b967f1-07bf-11e7-bed3-0242ac110002)

As my investigation, these files are actually generated successfully. But the client can not get the file(pod) at following code in: https://github.com/kubernetes/kubernetes/blob/release-1.5/test/e2e/dns.go

func assertFilesContain(fileNames []string, fileDir string, pod *api.Pod, client clientset.Interface, check bool, expected string){
...
if subResourceProxyAvailable {
				contents, err = client.Core().RESTClient().Get().
					Namespace(pod.Namespace).
					Resource("pods").
					SubResource("proxy").
					Name(pod.Name).
					Suffix(fileDir, fileName).
                                        Do().Raw()

Anything shall I check further?
Your suggestions are very appreciated.

### PR DESCRIPTION
**Pull request by bizhao**
**What this PR does / why we need it**:
In many cases, 60 seconds are not enough for generating all dns results.
Since the probeCmd takes up to 600 seconds, use 600 here too.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #43264, #43094, #43100 

**Special notes for your reviewer**:

**Release note**:

NONE

### CODE REVIEW

**Comment by bizhao** [comment]
I signed it!


________________________________
发件人: k8s-ci-robot <notifications@github.com>
发送时间: 2017年3月21日 11:13
收件人: kubernetes/kubernetes
抄送: bizhao; Author
主题: Re: [kubernetes/kubernetes] Make e2e-dns test more stable by increasing wait time (#43421)


Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA.

[https://avatars3.githubusercontent.com/u/13629408?v=3&s=400]<https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ>

CLA FAQ · kubernetes/kubernetes Wiki · GitHub<https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ>
github.com
kubernetes - Production-Grade Container Scheduling and Management ... How do I sign the CNCF CLA? To sign up as an individual or as an employee of a signed ...



Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.

Instructions for interacting with me using PR comments are available here<https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md>. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra<https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:> repository. I understand the commands that are listed here<https://github.com/kubernetes/test-infra/blob/master/commands.md>.

**Comment by bizhao** [comment]
@kow3ns
Could you help to review?
Thank you.
Binbin

**Comment by janetkuo** [comment]
@k8s-bot ok to test
/release-note-none

**Comment by janetkuo** [comment]
@bowei would you take a look?

**Review by janetkuo — APPROVED** [review]

**Comment by bizhao** [comment]
Anything further I shall do?
It says,
Submit Queue — Milestone is for a future release and cannot be merged

**Comment by runcom** [comment]
This is failing for me locally with 600s - works pretty ok with a 1200s timeout (it can probably be lower though)

**Comment by bizhao** [comment]
Hi Runcom.
What's your k8s version?

**Comment by ashutoshishere04** [comment]
Hello, i'm using kubernetes version 1.12.8 and facing the same issue of timeout, how can I use this change in my existing cluster, (bootstrapping tool : aks-engine)

**Pull request merged**
