### PR TITLE
Adding missing validation in HPA

### LINKED ISSUE #60511: Missing validation in HPA
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
It looks like validation of HPA is insufficient:
- metric name in pods and object metrics should be checked using IsValidPathSegmentName as they're used as part of request to custom metrics API (this is analogous to https://github.com/kubernetes/kubernetes/pull/60433).
- ValidateCrossVersionObjectReference allows for empty apiVersion, leading to non-functional HPA.

### PR DESCRIPTION
**Pull request by Rajat-0**
- Adding  IsValidPathSegmentName  for the name in pods and object metrics 

- Adding validation for APIVersion in ValidateCrossVersionObjectReference

/kind bug
Fixes #60511
/release-note-none

### CODE REVIEW

**Review by mwielgus — COMMENTED** [review]
How was this change tested?

**Comment by Rajat-0** [comment]
@mwielgus  sorry for the late response, I have just tested it with unit tests only. If you have any suggestions regarding its testing please let me know.

**Comment by MaciekPytel** [comment]
@mwielgus @Rajat-0  There was a discussion on https://github.com/kubernetes/kubernetes/issues/60511 about it. My understanding of it is we can't tighten validation on existing types, unless we do it using some extra-clever mechanism like @liggitt's https://github.com/kubernetes/kubernetes/pull/64907. 

I don't think we can merge this the way it is.

**Comment by liggitt** [comment]
> @mwielgus @Rajat-0 There was a discussion on #60511 about it. My understanding of it is we can't tighten validation on existing types, unless we do it using some extra-clever mechanism like @liggitt's #64907.
> 
> I don't think we can merge this the way it is.

correct.

**Comment by mwielgus** [comment]
Based on the comments I infer that we cannot merge the PR without serious changes. The foundation mechanism #64907 is still not merged and it doesn't seem to merge in the near future. Thus I'm closing this PR for now, hoping that one we will be able to get back to the topic.

**Pull request closed without merging**
