### PR TITLE
extensions: remove TPR remnants

### PR DESCRIPTION
**Pull request by nikhita**
The extensions group still had the TPR types + generated client. Having this in the codebase doesn't create any problems but would be good to clean up, especially since TPR access has been removed in 1.8.

**Release note**:

```release-note
NONE
```

/assign @sttts @deads2k

### CODE REVIEW

**Comment by nikhita** [comment]
While running `hack/update-codegen.sh`, I noticed that the generator does not _remove_ any files. Due to this, the following files still exist even after running the script:

- `staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go`
-  `pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/thirdpartyresource.go`
-  `staging/src/k8s.io/client-go/listers/extensions/v1beta1/thirdpartyresource.go`
-  `pkg/client/listers/extensions/internalversion/thirdpartyresource.go`

**Comment by deads2k** [comment]
I'm happy to see it go and our kubectl version skew is only one release, so I think removing this should be fine.

@kubernetes/api-approvers

**Comment by liggitt** [comment]
LGTM
tests are failing because of the leftover generated files. go ahead and remove those as well.

**Comment by bgrant0607** [comment]
Removing TPR is fine. Thanks for doing it.
cc @enisoc

**Comment by liggitt** [comment]
test needs fixup:
```
	etcd_storage_path_test.go:628: ephemeral whitelist does not match the types we saw:
		in ephemeral whitelist but not seen:
		[
			extensions/v1beta1, Resource=thirdpartyresources 
			extensions/v1beta1, Resource=thirdpartyresourcedatas]
		seen but not in ephemeral whitelist:
		[]
```

**Comment by nikhita** [comment]
All green. PTAL, thanks.

**Pull request merged**
