### PR TITLE
fix func comment in helpers.go

### PR DESCRIPTION
**Pull request by carlory**
**What this PR does / why we need it**:
fix func comment in helpers.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE
**Special notes for your reviewer**:
NONE
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Review by MHBauer — APPROVED** [review]
comment matches func name. comment is a more accurate description instead of a copy and paste.
I like it.

**Comment by feiskyer** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
