### PR TITLE
Automated cherry pick of #85043: kubeadm: use the secure ports for kube-scheduler and kcm health checks

### PR DESCRIPTION
**Pull request by SataQiu**
Cherry pick of #85043 on release-1.16.

#85043: kubeadm: use the secure ports for kube-scheduler and kcm health checks

For details on the cherry pick process, see the cherry pick requests page.

Fixes: #93194
Fixes: #93301

```release-note
Fixed a regression in kubeadm manifests for kube-scheduler and kube-controller-manager which caused continuous restarts because of failing health checks
```

### CODE REVIEW

**Comment by neolit123** [comment]
this is a required fix. thanks @SataQiu 
/lgtm
/approve
/priority important-soon

@kubernetes/release-managers

**Comment by hasheddan** [comment]
@SataQiu `pull-kubernetes-e2e-gce-device-plugin-gpu` is failing and will likely continue until https://github.com/kubernetes/kubernetes/pull/93207 is merged. However, it is not required for merge here 👍

**Comment by liggitt** [comment]
> It seems this needed to be backported to v1.16.13 when #92720 was backported.
> 
> * https://github.com/kubernetes/kubernetes/blob/v1.16.13/cmd/kubeadm/app/phases/controlplane/manifests.go#L70
> * #92726
> 
> Clusters provisioned or upgraded with kubeadm v1.16.13 currently produce static manifests with probes for kube-controller-manager and kube-scheduler that always fail.

That could explain why e2e tests that expect quick response from the controller [turned red](https://testgrid.k8s.io/sig-release-1.16-blocking#kind-1.16-parallel&width=20) right after #92726 merged to 1.16

**Comment by liggitt** [comment]
it looks like 1.16.13 was released with this bug

**Comment by liggitt** [comment]
the gpu failure is expected because https://github.com/kubernetes/kubernetes/pull/93207 hasn't been backported to 1.16

the integration failure is because https://github.com/kubernetes/kubernetes/pull/92879 hasn't been backported to 1.16

/skip

**Pull request merged**
