### PR TITLE
Rename fields in ContainerImage object

### PR DESCRIPTION
**Pull request by vishh**
Reference: #18248

### CODE REVIEW

**Comment by vishh** [comment]
cc @bgrant0607 @dchen1107 @yujuhong

**Comment by vishh** [comment]
@k8s-bot test this github issue: #21138

**Comment by bgrant0607** [comment]
LGTM

**Comment by vishh** [comment]
@bgrant0607: Need another LGTM due to a rebase.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@liggitt @deads2k 

Do you have any concerns about putting image names in NodeStatus? It seems like they might contain sensitive information, and it would be unfortunate to have to restrict access to nodes.

**Comment by liggitt** [comment]
is this the name that matches the container image name? if we expect someone to have access to the node API object, but not access to the bound pods for the node, then yes... this exposes a lot more information.

I'd also be concerned about the size of the node records listing every image they contained, especially as frequently as they are updated

**Comment by deads2k** [comment]
> Do you have any concerns about putting image names in NodeStatus? It seems like they might contain sensitive information, and it would be unfortunate to have to restrict access to nodes.

We already restrict access to node resources pretty tightly (cluster-admin sort of roles), so I'm not too concerned about adding this information since its already available on the node itself.

**Comment by deads2k** [comment]
What is the utility is having this information?  I'd be more worried about someone trying to use this for scheduling decisions, which **is** a big security hole if you aren't verifying pull access to local images.

This would allow someone to try to get access to a restricted image, a "smart" scheduler would look for the node that already has that image, schedule it there and bypass the authorization check, thus making a really bad choice.  Hopefully that's either a) not why you're doing this, b) you've considered an solved thsi problem, c) you never have the concept of a private image (unlikely).

**Comment by bgrant0607** [comment]
@deads2k Yes, the information was intended to be used for scheduling.

ImageLocalityPriority:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/priorities.go#L156

Filed #21560 to discuss this type of policy/convention.

**Comment by bgrant0607** [comment]
@deads2k Security-wise, I don't see the difference between starting a set of pods spread across all the nodes (and there are many ways to achieve that) vs. choosing the specific node(s) that contain a particular image.

**Comment by deads2k** [comment]
> @deads2k Security-wise, I don't see the difference between starting a set of pods spread across all the nodes (and there are many ways to achieve that) vs. choosing the specific node(s) that contain a particular image.

I don't see a reason to help user do it, but I will concede that I can get a similar effect by scaling an RC up and down over and over again.  Other than an "always pull policy" (in which case this change does nothing), is anyone looking at a way to secure access to images already on the node?

**Comment by bgrant0607** [comment]
For the scheduling use case, I think a one-way hash of the image names would actually be good enough.

**Comment by bgrant0607** [comment]
@deads2k Re. access to images on nodes: not AFAIK. I'll file an issue.

**Comment by bgrant0607** [comment]
@davidopp @resouer Would obfuscating image names (e.g., using a one-way hash) cause any problems for ImageLocalityPriority?

**Comment by vishh** [comment]
FYI. Image security issue is currently solved using an [admission controller](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/alwayspullimages/admission.go#L25) that overrides the image pull policy to be `PullAlways`.

**Comment by smarterclayton** [comment]
One way hash of image names is actually going to result in inefficient scheduler behavior in a lot of common cases where the same image is present as multiple image repository tags.

Someone who pulls "mysql:latest" and "mysql:5.8" will in all likelihood have the same underlying image digest (mysql@sha256:....).  The hash of the name obscures the commonality of that image.  For Docker based images, if the name on the node is to a digest, we should return the digest as the hash rather than further hashing it.  Anyone using digests (like OpenShift, or some of the other automated systems that use digest) is likely going to not see much benefit from the scheduler work if we do only a hash of the naive name.

Docker 1.10 is much more strongly organized around using digest internally - fairly soon we should have that as the actual image ID on disk.

**Comment by resouer** [comment]
> One way hash of image names is actually going to result in inefficient scheduler behavior in a lot of common cases where the same image is present as multiple image repository tags

+1 for this.

**Comment by bgrant0607** [comment]
I like the digest idea.

**Comment by bgrant0607** [comment]
One challenge with that is that the scheduler doesn't have the digest.

**Comment by smarterclayton** [comment]
The scheduler may have the digest - certainly we do in almost all pods
(openshift transforms tags into digests when the image starts being
tracked).  It just depends on having a lot of good integration with a
registry and the changing tags (to trigger deterministic deployments).

The scheduler would at minimum have to parse the docker image to make that
determination - but it's a fairly low cost opportunistic check.

**Pull request merged**
