### PR TITLE
fix apiserver metrics `RecordsWatchCacheCapacityChange` use watchCacheCapacity as increase total

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
if old less than new, Inc function should be called for `watchCacheCapacityIncreaseTotal` instead of `watchCacheCapacity`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/cc @logicalhan 
Would you mind take a look when have time? Thank you
/triage accepted

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
