### PR TITLE
Revert kubectl wait regression

### PR DESCRIPTION
**Pull request by liggitt**
Reverts a regressing change to `kubectl wait` in https://github.com/kubernetes/kubernetes/pull/122994, adds a test for the `--timeout=0` use

/sig cli

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
/triage accepted

I guess:
/release-note-none

.... Is the release note tooling aware of complex reverts?

**Comment by ardaguclu** [comment]
Thanks for taking care of this possible regression. Once this is merged, I'll reopen re-revert by also applying https://github.com/kubernetes/kubernetes/pull/122994#discussion_r1649204371

**Pull request merged**
