### PR TITLE
Cacher stopLock should be unlocked

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

Cacher.Stop should also unlock stopLock when isStopped. 
Lock & Unlock should be paired in any case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
ping @mml @liggitt @mqliang rebased, please take another look.

**Comment by mbohlool** [comment]
@hzxuzhonghu Can you send a patch for this to 1.9 branch?

**Pull request merged**
