### PR TITLE
List selected pods in service information

### LINKED ISSUE #3623: feature request - REST api - need to be able to get list of relevant pods for each service
Currently there is a selector on each service that based on its query language the service knows which pods are relevant.
However :
1. the query language is not documented, which operators are supported/what's the right syntax.
2. even if the query language is known and clear, the resolving of each service to pods relationship need to be resolved all over again by the clients.

So it will be much better to have a possibility for a REST request to get per each service the list of its relevant pods (or at least their uid or name)

### PR DESCRIPTION
**Pull request by simon3z**
Fixes #3623

### CODE REVIEW

**Comment by bgrant0607** [comment]
I'm sorry, but, no, we are not doing this.

As discussed in #3623 and #3676, we will not put a list of pods nor pod references in services nor in replication controllers. I'd be happy to have links to the pod query and/or to the corresponding endpoints objects. They need to go in the Status, though. See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md.

**Comment by bgrant0607** [comment]
See also #2585 if you have an opinion about the form of the Endpoints API.

**Comment by simon3z** [comment]
@bgrant0607 could this be something optional? e.g.:

  /api/v1beta3/services?pods=true

If you don't think that making it optional is viable, then I'd prefer to have (instead of a link) a way to list the pods through:

 /api/v1beta3/services/service-id/pods

What do you think?

**Comment by bgrant0607** [comment]
@simon3z Could you please describe your use case on #3676, and explain there why you don't want to follow a link?

Also, I'm 95% sure that we're going to break up service in v1beta3 and it won't have a direct relationship to pods.

**Comment by simon3z** [comment]
@bgrant0607 following a link is not a problem per-se, it just seemed more REST-API-like to use the path:

 /api/v1beta3/services/service-id/pods

But that's just a nit. It's not solving my initial problem of needing a single-query server-side api to connect services and pods.

Looping over the services to get links (or paths) to query the pods is both inefficient and inaccurate for its racy nature.

Kubernetes is already doing the selector matching, so why not expose its results? (And it could belong to the services api, or the pods api, or any other entity api, that's just an implementation detail for me)

If in v1beta3 we won't have a direct relationship to pods (why? pod templates?), services will in the end effect pods/pod-templates just as well (correct?) so for our use case of learning what pods/pod-templates are selected by the services we would still need the api.

**Comment by bgrant0607** [comment]
The results are exposed, in Endpoints.

"Single-query" doesn't provide any useful information to me about what you're trying to do or what your constraints are.

Races can be addressed using resourceVersion.

There's nothing that can be done about the fact that the information will always be stale.

Read #2585 if you want to understand where the v1beta3 service API is headed.

**Comment by derekwaynecarr** [comment]
Agree this is a pattern we cannot follow, and it is also a pattern that in OpenShift we are not following, but I want to clarify on the racy comment.  

@simon3z - note this is just as racy as making two calls to apiserver.  There is no transactional context or lock between two etcd calls that are being made to link these two registries.

**Comment by thockin** [comment]
This is a fundamentally async and distributed system.  Almost all
information should be considered 'potentially stale' :)

**Pull request closed without merging**
