### PR TITLE
Fix label mutation in endpoints controller

### LINKED ISSUE #85358: Endpoints controller modifies shared service object labels in memory
bug (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/85350/pull-kubernetes-e2e-kind/1195418121377157121/artifacts/logs/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_63c21485472d3e3590c878f8825a0b65/kube-controller-manager/3.log):
```
2019-11-15T19:34:19.719419941Z stdout F CACHE *v1.Service[50] ALTERED!
2019-11-15T19:34:19.719459914Z stdout F (*v1.Service)(0xc000688fc0)({                                                                                (*v1.Service)(0xc000689200)({
...
2019-11-15T19:34:19.72158974Z stdout F   DeletionGracePeriodSeconds: (*int64)(<nil>),                                                                 DeletionGracePeriodSeconds: (*int64)(<nil>),
2019-11-15T19:34:19.721596923Z stdout F   Labels: (map[string]string) (len=2) {                                                                        Labels: (map[string]string) (len=1) {
2019-11-15T19:34:19.721602856Z stdout F    (string) (len=6) "testid": (string) (len=57) "externalname-service-7038a091-18c4-47df-9370-3c171ca76154",    (string) (len=6) "testid": (string) (len=57) "externalname-service-7038a091-18c4-47df-9370-3c171ca76154"
2019-11-15T19:34:19.721620375Z stdout F    (string) (len=30) "service.kubernetes.io/headless": (string) ""                                             },
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/85350#issuecomment-554506016_

cc @thockin @rikatz 
/sig network
/priority critical-urgent

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/85358

**Special notes for your reviewer**:
Needs backport to 1.16

**Does this PR introduce a user-facing change?**:
```release-note
kube-controller-manager: Fixes bug setting headless service labels on endpoints
```

/cc @thockin 
/sig network
/priority critical-urgent

### CODE REVIEW

**Comment by robscott** [comment]
Thanks for finding and fixing this!

/lgtm

**Comment by rikatz** [comment]
Oh tks and sorry about that @liggitt

**Comment by rikatz** [comment]
And if that’s possible I would like to after KubeCon understand better how can I improve this kind of changes to not happen again

**Pull request merged**
