### PR TITLE
Modify IsInvalidObj name and description

### PR DESCRIPTION
**Pull request by lixiaobing1**
IsInvalidObj  note incorrect, modify it.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30492)

### CODE REVIEW

**Comment by lavalamp** [comment]
ok to test
LGTM

**Comment by lixiaobing10051267** [comment]
@k8s-bot test this issue: [#30561](https://github.com/kubernetes/kubernetes/issues/30561)

**Comment by lavalamp** [comment]
ok to test

**Comment by lavalamp** [comment]
@k8s-bot test this issue #30542

**Pull request merged**
