### PR TITLE
Fix typo in kubectl docs

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Cleanup: fix typo.

```release-note
NONE
```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by nikhita** [comment]
/lgtm cancel

Can you also update the commit message to something like `Fix typo in kubectl describe docs`?

**Comment by hwdef** [comment]
@nikhita 
Thanks for your suggestion.I changed it.

**Comment by nikhita** [comment]
@hwdef Thanks for fixing that so quickly! :)

/lgtm

**Comment by hwdef** [comment]
@bsalamat

**Comment by hwdef** [comment]
@soltysh

**Comment by hwdef** [comment]
@brendandburns

**Comment by hwdef** [comment]
@apelisse
Please add an approved label for me.
Thanks

**Pull request merged**
