### PR TITLE
Release 1.0.5

### PR DESCRIPTION
**Pull request by brendandburns**
- Update cadvisor dependency #12022 (piosz)
- Update Kubernetes cadvisor #13148 (pwittrock)
- Fix vagrant kube-up #12514 (derekwaynecarr)

### CODE REVIEW

**Comment by brendandburns** [comment]
@a-robinson @eparis

**Comment by brendandburns** [comment]
@derekwaynecarr

**Comment by a-robinson** [comment]
LGTM

**Comment by brendandburns** [comment]
Self merging so that I can build the release...

**Comment by thockin** [comment]
I have a kube-proxy change I was hoping to get into 1.0.5 - it's LGTM just
blocked on a clean mergequeue - #13345

**Comment by brendandburns** [comment]
@thockin at this point it's going to have to be 1.0.6 (though we can cut that tomorrow if you want to...)  The tags, etc. are pretty much set at this point...

**Pull request merged**
