### PR TITLE
Fix bug in movePodsToActiveOrBackoffQueue to avoid invalid moveRequest

### PR DESCRIPTION
**Pull request by ping035627**
What type of PR is this?
/kind bug

What this PR does / why we need it:
When podInfoList is nil or add to queue(podBackoffQ or activeQ) failed, it shouldn't set moveRequestCycle, it isn't the real moveRequest.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

/release-note-none
/priority backlog
/triage accepted

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
Quote on the definition of the `moveRequestCycle`, if we agree on this then `moveRequestCycle` should be refreshed as long as the move request is received.

Besides, the failure of the unit test might be related.
> 	// moveRequestCycle caches the sequence number of scheduling cycle when we
	// received a move request. Unschedulable pods in and before this scheduling
	// cycle will be put back to activeQueue if we were trying to schedule them
	// when we received move request.

**Comment by ping035627** [comment]
> Quote on the definition of the `moveRequestCycle`, if we agree on this then `moveRequestCycle` should be refreshed as long as the move request is received.
> 
> Besides, the failure of the unit test might be related.
> 
> > // moveRequestCycle caches the sequence number of scheduling cycle when we
> > // received a move request. Unschedulable pods in and before this scheduling
> > // cycle will be put back to activeQueue if we were trying to schedule them
> > // when we received move request.

For example, “p.getUnschedulablePodsWithMatchingAffinityTerm(pod)” may be empty, then movePodsToActiveOrBackoffQueue do nothing but set “p.moveRequestCycle = p.schedulingCycle”, I think it's unnecessary.

func (p *PriorityQueue) AssignedPodAdded(pod *v1.Pod) {
	p.lock.Lock()
	p.movePodsToActiveOrBackoffQueue(p.getUnschedulablePodsWithMatchingAffinityTerm(pod), AssignedPodAdd)
	p.lock.Unlock()
}

**Review by changshuchao — COMMENTED** [review]
/lgtm

**Comment by kerthcet** [comment]
> Quote on the definition of the `moveRequestCycle`, if we agree on this then `moveRequestCycle` should be refreshed as long as the move request is received.
> 
> Besides, the failure of the unit test might be related.
> 
> > // moveRequestCycle caches the sequence number of scheduling cycle when we
> > // received a move request. Unschedulable pods in and before this scheduling
> > // cycle will be put back to activeQueue if we were trying to schedule them
> > // when we received move request.

+1, `movePodsToActiveOrBackoffQueue` is just a signal that former unscheduled pods may have change to be rescheduled.

Imagine that in current scheduling cycle, we got pod added,  but `AssignedPodAdded() -> p.getUnschedulablePodsWithMatchingAffinityTerm(pod)` got nil, then we ran into `movePodsToActiveOrBackoffQueue`, at that moment, we triggered `AddUnschedulableIfNotPresent`, in this circumstance, we should still move pods to `podBackoffQ` rather than `unschedulablePods`, right? So if we set `moveRequestCycle = schedulingCycle` only when `activated` or `backoffed`, we'll move pod to `unschedulablePods`. It's not right.

**Pull request closed without merging**
