### PR TITLE
fix sporadic failures in cni tests

### LINKED ISSUE #82150: TestCNIPlugin flakes
**Which jobs are failing**:

pull-kubernetes-bazel-test

**Which test(s) are failing**:

//pkg/kubelet/dockershim/network/cni:go_default_test

```
--- FAIL: TestCNIPlugin (0.11s)
    cni_test.go:293: failed to parse reported cni input config /tmp/cni-test548751309/output/test_vendor887.in: (<nil> invalid character 'w' after top-level value)
    cni_test.go:300: mismatch in expected port mappings. expected [map[containerPort:80 hostIP:0.0.0.0 hostPort:8008 protocol:udp]] got []
    cni_test.go:307: mismatch in expected bandwidth. expected map[egressBurst:2.147483647e+09 egressRate:1e+06 ingressBurst:2.147483647e+09 ingressRate:1e+06] got map[]
    cni_test.go:317: mismatch in expected ipRange. expected [[map[subnet:10.0.2.0/24]]] got []
    cni_test.go:341: PASS:	AddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
    cni_test.go:341: PASS:	DelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
```

**Since when has it been failing**:

Unsure, it doesn't appear in triage, but I see it regularly in PRs.

**Testgrid link**:

This package is the top flake currently
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&sort-by-flakiness=

**Reason for failure**:

**Anything else we need to know**:

/sig node
/sig network

### LINKED ISSUE #82280: pkg/kubelet/dockershim/network/cni/cni_test.go heavily flakes
The upper test heavily flakes in master:

```
--- FAIL: TestCNIPlugin (0.12s)\n"}
    cni_test.go:279: Mismatch in expected output for setup hook. Expected 'ADD /proc/12345/ns/net podNamespace podName test_infra_container', got 'VERSION dummy   '\n"}
    cni_test.go:341: PASS:\tAddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)\n"}
    cni_test.go:341: PASS:\tDelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)\n"}
```

### PR DESCRIPTION
**Pull request by mars1024**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix sporadic failures in CNI tests.
CNINetworkPlugin has a 5-seconds periodic syncer for reloading default network, in syncer, **ValidateNetworkList** will be called to check supported version for plugin, this will call fake shell-script plugin and overwrite some necessary files(like input, output, envs) which will be used in tests. If it happens just after **SetUpPod** (**AddNetworkList**) in test process, the overwrite will break the test.
What we should do is make fake shell-script plugin do nothing but echo CNI result when it is called for **Validate**.

Maybe in the future, we will use mock in cni test, it seems a better way.

**Which issue(s) this PR fixes**:
Fixes #82280
Fixes #82150

```release-note
NONE
```

### CODE REVIEW

**Comment by mars1024** [comment]
cc @sttts @squeed @liggitt

**Comment by mars1024** [comment]
/assign @dcbw 
/assign @thockin 
PTAL, thanks !

**Comment by thockin** [comment]
Thanks!

/approve

**Pull request merged**
