### PR TITLE
apiextensions: validate status updates with status schema

### PR DESCRIPTION
**Pull request by alexzielenski**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Currently `ValidateStatusUpdate` validates the entire object against the schema. This PR tries to save some time by validating only the status portion against the status schema.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @sttts

### CODE REVIEW

**Comment by sttts** [comment]
Waiting for tests. Sgtm.

**Comment by sttts** [comment]
Can you check what's going on in the integration test?

**Comment by alexzielenski** [comment]
/hold

has a bug after rebase

**Pull request merged**
