### PR TITLE
Bumps cobra from 1.5.0 to 1.6.0

### PR DESCRIPTION
**Pull request by jpmcb**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This patch bumps `spf13/cobra` from 1.5.0 to 1.6.0. This release carries a number a few fixes for bugs in completions that may be beneficial to https://github.com/kubernetes/kubernetes/issues/74178 and https://github.com/kubernetes/kubernetes/pull/105867

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jpmcb** [comment]
I didn't realize `mousetrap` updated their license to Apache 2.0 - force pushed to add that license via the `update` scripts

/retest

**Comment by dims** [comment]
dang, needs an rebase!

**Comment by jpmcb** [comment]
Rebased! Thanks Dims!!

/retest

**Comment by dims** [comment]
/approve
/lgtm

- no new deps
- license text altered slightly ( but same license as before ) for mousetrap
- about 5 months worth of updates ( https://github.com/spf13/cobra/compare/v1.5.0...v1.6.0 )

**Pull request merged**
