### PR TITLE
Updated COS version to M77

### PR DESCRIPTION
**Pull request by dhuh**
Updated COS version from M73 to M77. The updates from M77 include the following:

- Kernel update from 4.14 to 4.19
- Docker update from 18.09 to 19.03
- Systemd upgrade to 239

### CODE REVIEW

**Comment by yguo0905** [comment]
Here is the log from GPU driver installer

```
+ COS_DOWNLOAD_GCS=https://storage.googleapis.com/cos-tools
+ COS_KERNEL_SRC_GIT=https://chromium.googlesource.com/chromiumos/third_party/kernel
+ COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz
+ TOOLCHAIN_URL_FILENAME=toolchain_url
+ CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk
+ ROOT_OS_RELEASE=/root/etc/os-release
+ KERNEL_SRC_DIR=/build/usr/src/linux
+ NVIDIA_DRIVER_VERSION=418.67
+ NVIDIA_DRIVER_MD5SUM=
+ NVIDIA_INSTALL_DIR_HOST=/home/kubernetes/bin/nvidia
+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia
+ ROOT_MOUNT_DIR=/root
+ CACHE_FILE=/usr/local/nvidia/.cache
+ LOCK_FILE=/root/tmp/cos_gpu_installer_lock
+ LOCK_FILE_FD=20
+ set +x
[INFO    2019-09-18 22:12:04 UTC] Checking if this is the only cos-gpu-installer that is running.
[INFO    2019-09-18 22:12:04 UTC] Running on COS build id 12371.44.0
[INFO    2019-09-18 22:12:04 UTC] Checking if third party kernel modules can be installed
[INFO    2019-09-18 22:12:04 UTC] Checking cached version
[INFO    2019-09-18 22:12:04 UTC] Cache file /usr/local/nvidia/.cache not found.
[INFO    2019-09-18 22:12:04 UTC] Did not find cached version, building the drivers...
[INFO    2019-09-18 22:12:04 UTC] Downloading GPU installer ... 
/usr/local/nvidia /
[INFO    2019-09-18 22:12:05 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/418.67/NVIDIA-Linux-x86_64-418.67.run
/
ls: cannot access '/build/usr/src/linux': No such file or directory
[INFO    2019-09-18 22:12:06 UTC] Kernel sources not found locally, downloading
[INFO    2019-09-18 22:12:06 UTC] Kernel source archive download URL: https://storage.googleapis.com/cos-tools/12371.44.0/kernel-src.tar.gz
/build/usr/src/linux /

real	0m0.782s
user	0m0.246s
sys	0m0.424s
/
/build/usr/src/linux /
/
/build /
[INFO    2019-09-18 22:12:15 UTC] Found toolchain path file locally
[INFO    2019-09-18 22:12:15 UTC] Downloading prebuilt toolchain from https://storage.googleapis.com/chromiumos-sdk/2019/07/x86_64-cros-linux-gnu-2019.07.25.030939.tar.xz

real	0m1.798s
user	0m0.578s
sys	0m1.157s
/
[INFO    2019-09-18 22:13:17 UTC] Configuring environment variables for cross-compilation
[INFO    2019-09-18 22:13:17 UTC] Configuring installation directories
/usr/local/nvidia /
[INFO    2019-09-18 22:13:17 UTC] Updating container's ld cache
/
/build/usr/src/linux /
[INFO    2019-09-18 22:13:18 UTC] Configuring kernel sources
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
/bin/sh: 1: bison: not found
make[1]: *** [scripts/kconfig/zconf.tab.c] Error 127
make: *** [olddefconfig] Error 2
scripts/Makefile.lib:207: recipe for target 'scripts/kconfig/zconf.tab.c' failed
Makefile:529: recipe for target 'olddefconfig' failed
```

**Comment by yguo0905** [comment]
`bison` is not present in the container image referenced here: https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/daemonset.yaml

```
sudo docker run -it gcr.io/cos-cloud/cos-gpu-installer@sha256:652687e88e9a2df8a0d529340ba21bb52a71450b36472c97ebed8c22e902b6c4 bison
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"bison\": executable file not found in $PATH": unknown.
```

@kewu1992, do you have any ideas?

**Comment by wojtek-t** [comment]
This seem to cause the regression in scalability tests - we're reverting this one in https://github.com/kubernetes/kubernetes/pull/83021

From the first glance it seem to be very similar issue that we already had in the past - something like lack of isolation between different disks. I will try to dig up the details tomorrow and follow up on it.

**Comment by yguo0905** [comment]
https://github.com/kubernetes/kubernetes/pull/83974 to update COS again with the fix.

**Pull request merged**
