### PR TITLE
Add label to delegate endpoints control to custom controller

### LINKED ISSUE #87412: Add well-known label for custom endpoint controller as well as "service.kubernetes.io/service-proxy-name"
**What would you like to be added**:

Add well-known label at endpoint/endpointslice controller to delegate endpoint/endpointslice control to custom endpoint/endpointslice controllers.

**Why is this needed**:

kube-proxy has well-known label for custom proxy, ["service.kubernetes.io/service-proxy-name"](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/apis/well_known_labels.go#L22) that delegates service control to custom proxy. With the label, kube-proxy does not generate iptables for the service. However endpoint/endpointslice controller does not have similar label, hence the issue address it.

### PR DESCRIPTION
**Pull request by s1061123**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR introduces new label, "service.kubernetes.io/endpoint-controller-name", to delegate endpoints control to custom controller. 

**Which issue(s) this PR fixes**:
Fixes #87412

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
Hey @s1061123, just trying to make sure I understand the goal here. The corresponding issue compares this to what exists for kube-proxy to tell it to ignore Services with the `service.kubernetes.io/service-proxy-name` label set. This seems to be more focused on instructing the Endpoints controller to ignore Endpoints with the `service.kubernetes.io/endpoint-controller-name` label set? 

If I'm understanding this correctly, we already have a [label that covers this capability for EndpointSlices](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/discovery/v1beta1/well_known_labels.go#L22-L27) (`endpointslice.kubernetes.io/managed-by`). Do we need a similar label for Endpoints? I'm hesitant to make any changes to a stable core API or corresponding controller at this point, especially if the functionality in EndpointSlices is already sufficient.

**Comment by s1061123** [comment]
Hi @robscott,

Thank you for your comments! 

I've looked the code and I suppose there are a little gaps. First, let me clarify the label, `endpointslice.kubernetes.io/managed-by`.

Looking the code (master branch), this label is for endpointslice, added by k8s endpointslice controller and once it is changed to another value, then k8s endpointslice controller ignores only to watch update.

When the Service/Pod are created with service selector, k8s endpointslice controller always creates endpointslice whatever the label is. If we change endpointslice label value,  `endpointslice.kubernetes.io/managed-by` once it created, then k8s endpointslice controller ignores it and k8s endpointslice controller creates another endpointslice after service change. 

I tested it in K8s v1.17.2 and here's the logs. I added nginx service, changed the label and scale the service, then k8s endpointslice controller creates another endpointslice.

https://gist.github.com/s1061123/bfa450cb28a923c8624360ae17e5e522

With custom controller case, I imagined that the following scenario might be reasonable:

1. Pod/Service are created with selector and Service has label for custom controller
1. K8s endpointslice controller ignores the CREATE event and no endpointslice is created
    (For now, k8s endpointslice controller always creates it, actually)
1. Custom controller gets the CREATE events then create endpointslice for that, with `endpointslice.kubernetes.io/managed-by=<custom controller>`
1. When the service is changed (e.g. scale), k8s endpointslice controller ignores the UPDATE event due to different label value, `endpointslice.kubernetes.io/managed-by`, and no endpointslice is created
    (For now, K8s endpointslice controller creates another endpointslice due to label)

I understood that Endpoint will be replaced with EndpointSlice, hence I am okey to use EndpointSlice, however, current `endpointslice.kubernetes.io/managed-by` is not sufficient from custom controller point of view. The label for Service, that k8s endpointslice controller ignores, is required to interworking with custom controller service/endpoints/endpointslice.

I am going to update diffs to support endpointslices.

**Comment by robscott** [comment]
Hey @s1061123, thanks for the additional detail! I'm still not quite sure I'm understanding this proposal correctly though. It sounds like you're hoping to have some kind of label on a Service that would prevent the EndpointSlice controller from creating or managing EndpointSlices for the Service. Right now the only way to accomplish that would be to have an empty selector on the Service itself. 

Currently we have two scenarios covered that seem related to this proposal:
1. Allow other controllers to create/manage EndpointSlices without having the EndpointSlice controller interfere (use `endpointslice.kubernetes.io/managed-by` annotation).
2. Tell the EndpointSlice controller not to create EndpointSlices for a Service (use an empty selector on the Service).

Are you able to accomplish what you want with 1 or 2? If not, it would be helpful to have some more examples of how you'd like this to work and why.

**Comment by s1061123** [comment]
Thank you for your quick reply, @robscott,

> 1. Allow other controllers to create/manage EndpointSlices without having the EndpointSlice controller interfere (use endpointslice.kubernetes.io/managed-by annotation).
> 2. Tell the EndpointSlice controller not to create EndpointSlices for a Service (use an empty selector on the Service).

I would like to use service selector for the service/pod of my custom controller.

**Comment by robscott** [comment]
Hey @s1061123, thanks for clarifying. This kind of addition sounds significant enough that it would likely need an associated [KEP](https://github.com/kubernetes/enhancements/tree/master/keps). In that KEP you could explain why the existing options discussed above are insufficient, and what use cases this proposal would be helpful for.

**Comment by s1061123** [comment]
Thank you for your advice! I am going to write KEP for that.

By the way, should I close this PR, or keep it as WIP?

**Comment by robscott** [comment]
:+1: Sounds good. I think it would be better to close this at least temporarily since our processes tend to bug us about PRs that have gone stale. This could always be reopened after the KEP process.

**Pull request closed without merging**
