### PR TITLE
Add k8s.io/kube-openapi/cmd/openapi-gen dependency on code-generator go.mod

### LINKED ISSUE #125484: Missed k8s.io/kube-openapi/cmd/openapi-gen dependency on code-generator go.mod
### What happened?

We're trying to upgrade `k8s.io/code-generator` to `v1.30.1`  (https://github.com/kubernetes-sigs/kueue/pull/2402) and found the issue on executing `kube::codegen::gen_openapi` (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2402/pull-kueue-verify-main/1800788997593632768). 

```
../kube-openapi@v0.0.0-20240228011516-70dd3763d340/pkg/common/common.go:23:2: missing go.sum entry for module providing package github.com/emicklei/go-restful/v3 (imported by k8s.io/kube-openapi/pkg/common); to add:
	go get k8s.io/kube-openapi/pkg/common@v0.0.0-20240228011516-70dd3763d340
```

The problem is that on go.mod (https://github.com/kubernetes/code-generator/blob/master/go.mod) missed `github.com/emicklei/go-restful/v3` dependency that not allow to install `k8s.io/kube-openapi` (https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh#L330C45-L330C64)

### What did you expect to happen?

No error

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the same what happening on https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh#L325-L330, just execute this command on code-generator folder:
```bash
GO111MODULE=on go install k8s.io/kube-openapi/cmd/openapi-gen
```

### Anything else we need to know?

I think it's happens after this commit https://github.com/kubernetes/kubernetes/commit/1a4450f6ffdad44bfc12fae5911c93e3bd238f0f.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
To fix [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2402/pull-kueue-verify-main/1800788997593632768) issue. For some reason it is using a [commit](https://github.com/kubernetes/kube-openapi/commit/70dd3763d340) from Feb 27. We need to install the latest `k8s.io/kube-openapi/cmd/openapi-gen` dependency on `code-generator` `go.mod`.

#### Which issue(s) this PR fixes:

Fixes #125484 

#### Special notes for your reviewer:
Related issue https://github.com/kubernetes-sigs/kueue/pull/2402

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug that doesn't allow to install k8s.io/kube-openapi dependency on execute kube::codegen::gen_openapi.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
cc @alculquicondor @mimowo

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
It's not clear to me why tools.go imports things from this same module - it looks like that could all be removed, but that's for another day

**Comment by ary1992** [comment]
@thockin Shouldn't we backport this change to earlier version v0.30 as well? We are also facing the same issue while upgrading to v0.30.

**Comment by kannon92** [comment]
@mbobrovskyi We should get a release note for this.

Not sure if it will work after the fact but the cherry-pick bot was yelling that this does not have a release-note.

**Comment by mbobrovskyi** [comment]
/release-note-edit 

```release-note 
Fixed a bug that doesn't allow to install k8s.io/kube-openapi dependency on execute kube::codegen::gen_openapi.
```

**Pull request merged**
