### PR TITLE
Kubelet: do not remove pod directory if any container is still running

### LINKED ISSUE #10571: Kubelet should unmount before trying to remove orphaned pod dirs
Often observed in logs:
```
 Couldn't sync containers: [remove /var/lib/kubelet/pods/189d622a-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/189e2f9e-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/1efbc818-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove 
/var/lib/kubelet/pods/21e75aa3-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/24b47454-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/26582f9c-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/29b63086-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove 
/var/lib/kubelet/pods/2afcf998-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/2d05a2c7-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/2ecfa66b-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/3ec08d37-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove 
/var/lib/kubelet/pods/42ecbd3f-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/4502b6c5-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/4630c404-1e05-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/4718c0dc-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove 
/var/lib/kubelet/pods/4dbd58f2-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/512bab30-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/51ae59e9-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/520978bb-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove 
/var/lib/kubelet/pods/558d5be0-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/588801c2-1e04-11e5-a1b8-
42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/7102cb27-1eb7-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-
token-n6j66: device or resource busy, remove /var/lib/kubelet/pods/721a038a-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/780ab3ea-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/784aa9e6-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/7c80a67c-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/7e1ca5bb-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy, remove /var/lib/kubelet/pods/8597b64f-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss: device or resource busy]
```

However:
```
$ sudo cat /proc/mounts  | grep 189d622a-1e04-11e5-a1b8-42010af09b2c
tmpfs /var/lib/kubelet/pods/189d622a-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss tmpfs rw,relatime 0 0

$ sudo fuser -vm /var/lib/kubelet/pods/21e75aa3-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss
                     USER        PID ACCESS COMMAND
/var/lib/kubelet/pods/21e75aa3-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss:
                     root     kernel mount /var/lib/kubelet/pods/21e75aa3-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss
```

Which probably means we'd be ok unmounting it:
```
$ sudo umount /var/lib/kubelet/pods/189d622a-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss
$ sudo rm -rf /var/lib/kubelet/pods/189d622a-1e04-11e5-a1b8-42010af09b2c/volumes/kubernetes.io~secret/default-token-zlfss
```

This probably also means we don't delete orphaned mirror pods, which is the next step in SyncPods (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1477).

### PR DESCRIPTION
**Pull request by yujuhong**
If there are any running container in the pod, we cannot remove the volume.
Therefore, we should not attempt to remove the pod directory.

This fixes #10571

### CODE REVIEW

**Comment by yujuhong** [comment]
Risk: Medium-low. This PR touches a bit of real code for removing pod directories (but not much).
Value: This prevents kubelet from attempting to remove the pod directories while containers are still running. This often spams the log and causes confusion.

**Comment by zmerlynn** [comment]
Over to @dchen1107

**Comment by yujuhong** [comment]
@k8s-bot ok to test.

**Comment by yujuhong** [comment]
@dchen1107, PTAL, thanks!

**Comment by dchen1107** [comment]
LGTM

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@yujuhong: I think this needs to be rebased and repushed after the great rename in order to clear the Shippable failure (so it'll pick up the new shippable.yml.)

**Comment by zmerlynn** [comment]
Shippable still doesn't like this.

**Comment by nikhiljindal** [comment]
@yujuhong Can you please rebase as @zmerlynn suggested?

**Comment by yujuhong** [comment]
I removed the lgtm tag for now until I have time to rebase.

**Comment by yujuhong** [comment]
Rebased the PR.

@saad-ali, the PD test passed locally with this PR. I will run more times to confirm.

**Comment by saad-ali** [comment]
@yujuhong Awesome, thanks!
#13257 for reference

**Comment by yujuhong** [comment]
This PR should solve most race conditions causing the test failures. I have a follow-up PR to make the directory removal more robust: #13293.

**Pull request merged**
