### PR TITLE
Automated cherry pick of #89002: Fix VMSS cache content

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #89002 on release-1.17.

#89002: Fix VMSS cache content

### CODE REVIEW

**Comment by andyzhangx** [comment]
/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

cc @ArchangelSDY

**Comment by andyzhangx** [comment]
@chewong could you clean up the testing subs, thanks
```
The template deployment 'kubetest-6de1db8b-6399-11ea-a4e1-debe4c375c14' is not valid according to the validation procedure. The tracking id is '87e22d22-0573-4cf7-9f10-b76415097fda'. See inner errors for details." Details=[{"code":"ResourceCountExceedsLimitDueToTemplate","details":[],"message":"Subscription 0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e has a quota of 20 for resources of type PublicIpAddress with sku Basic. Subscription currently has 20 resources and the template contains 1 new resources of the this type which exceeds the quota. Please contact support to increase the quota for resource type PublicIpAddress"}]
```

**Comment by chewong** [comment]
cc @ritazh. With the increase in test coverage, we will need to increase the quota for the upstream subscription.

/retest

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
