### PR TITLE
Support kube-registry-proxy addon in trusty nodes

### PR DESCRIPTION
**Pull request by andyzheng0831**

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@yinghan @roberthbailey @dchen1107 @zmerlynn

**Comment by andyzheng0831** [comment]
I think the current GCE e2e tests do not cover any change to the trusty node settings. So, the failed case may not be related with this change.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Pull request merged**
