### PR TITLE
Automated cherry pick of #70463: Ensure orphan public IPs deleted

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #70463 on release-1.10.

#70463: Ensure orphan public IPs deleted

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by MaciekPytel** [comment]
@feiskyer Can you update release note on https://github.com/kubernetes/kubernetes/pull/70463 to say it's azure-specific?

**Comment by feiskyer** [comment]
@MaciekPytel done.

**Pull request merged**
