### PR TITLE
Fix staticcheck failures in apimachinery

### PR DESCRIPTION
**Pull request by tiloso**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
PR fixes issues found by staticcheck in `test/e2e/apimachinery` and `vendor/k8s.io/apimachinery`
```
test/e2e/apimachinery/garbage_collector.go:70:19: the integer division '8 / 10' results in zero (SA4025)
vendor/k8s.io/apimachinery/pkg/util/json/json_test.go:124:18: in Go, the floating-point literal '-0.0' is the same as '0.0', it does not produce a negative zero (SA4026)
vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:42:2: ineffective assignment to field PatchMeta.patchStrategies (SA4005)
vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:50:2: ineffective assignment to field PatchMeta.patchMergeKey (SA4005)
```

#### Which issue(s) this PR fixes:
Part of #92402

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jpbetz** [comment]
/priority important-longterm
/lgtm

Thanks for fixing PatchMeta.

**Comment by jpbetz** [comment]
@lavalamp would you be willing to approve?

**Comment by jpbetz** [comment]
This needs a rebase

**Comment by tiloso** [comment]
Closing since most fixes have been addressed in https://github.com/kubernetes/kubernetes/pull/106448.

**Pull request closed without merging**
