### PR TITLE
Automated cherry pick of #105839: fix: remove VMSS and VMSS instances from SLB backend pool

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #105839 on release-1.21.

#105839: fix: remove VMSS and VMSS instances from SLB backend pool

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by nilo19** [comment]
/sig cloud-provider
/area provider/azure
/priority critical-urgent
/triage accepted
/kind bug
cc @feiskyer

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by nilo19** [comment]
@cheftako can you help to approve?

**Comment by nilo19** [comment]
kindly ping @cheftako to approve

**Comment by nilo19** [comment]
@cheftako can we merge this? Many users are facing this issue.

**Comment by jackfrancis** [comment]
/assign @andrewsykim @dims

If either of you are around, are you aware of why this (and the 1.20 and 1.22) cherry-picks of this PR aren't yet merged? Are there concerns?

Thanks!

**Comment by nilo19** [comment]
I have a lot of bug fixes/cherry-picks that are pending approval for a very long time.

**Review by andrewsykim — COMMENTED** [review]
/approve

**Comment by bridgetkromhout** [comment]
Hi, @kubernetes/release-managers - please review this cherry-pick! Thanks.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
