### PR TITLE
sig-cli: add Eddie Zaneski as a co-chair

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
@eddiezane is being promoted to sig-cli co-chair so he's gaining privileges for approving sig-cli changes

**Special notes for your reviewer**:
/assign @seans3 @pwittrock 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
/triage accepted
/priority backlog
/sig cli
/hold
for visibility

**Review by hasheddan — COMMENTED** [review]
/retest

**Comment by soltysh** [comment]
The lazy consensus date has passed.
/hold cancel
/assign @thockin

**Review by thockin — COMMENTED** [review]
So say we all

/approve

**Pull request merged**
