### PR TITLE
Update component base SECURITY_CONTACTS

### LINKED ISSUE #92092: Security contacts for component-base not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/component-base/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/SECURITY_CONTACTS) file for the component-base repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by rudy2steiner**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #92092 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rudy2steiner** [comment]
I signed it

**Comment by rudy2steiner** [comment]
I have no idea  why pull-kubernetes-e2e-gce-ubuntu-containerd test failed, this pr only change the document

**Comment by mtaufen** [comment]
Can you also remove @sttts, as he just recently stepped down from the working group.

**Comment by mtaufen** [comment]
/assign @stealthybox 
Please confirm you're ok being a security contact for our WG, per https://github.com/kubernetes/kubernetes/issues/92092.

**Comment by rudy2steiner** [comment]
Ok, once have @stealthybox confirmation and I will remove @sttts by the way

**Comment by fedebongio** [comment]
/assign @lavalamp 
Assigning to you since your name is being added to the list! PTAL
/remove-triage needs-information

**Comment by lavalamp** [comment]
Still waiting for confirmation?

**Comment by rudy2steiner** [comment]
> Still waiting for confirmation?

yes

**Review by Aut0R3V — APPROVED** [review]

**Comment by Aut0R3V** [comment]
I feel like this PR can be approved. @stewart-yu

**Comment by lavalamp** [comment]
We are still waiting for @stealthybox to confirm, no?

**Comment by stealthybox** [comment]
@lavalamp thanks for the ping

/lgtm

**Pull request closed without merging**
