### PR TITLE
Update obsolete links to kubernetes.io/docs/user-guide in Go structs descriptions in autoscaling packages

### PR DESCRIPTION
**Pull request by aerfio**
#### What type of PR is this?
/kind cleanup
/kind documentation
/kind autoscaling

#### What this PR does / why we need it:

Partly supersedes https://github.com/kubernetes/kubernetes/pull/116107

This PR updates the links to http://kubernetes.io/docs/user-guide in various resources/structs' descriptions which are no longer valid, to their new equivalents. Those descriptions are useful because:
- they are part of documentation, duh
- developers that use k8s.io/api structs in their own CRDs "inherit" those docs too
- those links are visible in the output of `kubectl explain`, which is now broken, see example, `rg` used only to highlight the link
image

The issue was found when we were validating the links in the documentation generated from CRD yamls (generated via [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen), and I suspect that a lot of projects generate those docs too, see
- https://github.com/ahmetb/gen-crd-api-reference-docs#current-users
- https://github.com/elastic/crd-ref-docs
- https://doc.crds.dev/
- etc

All of the links have been also updated to use https instead of http.

Those links used to work, but the https://github.com/kubernetes/website/pull/39143 removed those redirects.

#### Special notes for your reviewer:

I used `make update` to regenerate the .proto and openapi files, I hope that's enough. If this PR is too big I can split it into smaller parts

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
one comment otherwise LGTM

**Comment by aerfio** [comment]
@Jefftree I don't see any comment unfortunately 😢 
image

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by Jefftree** [comment]
> @Jefftree I don't see any comment unfortunately 😢 image

oops sorry forgot to publish the comments earlier. Not really a blocking comment so the merge is fine.

**Pull request merged**
