### PR TITLE
Automated cherry pick of #107406: fix: delete non existing disk issue

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #107406 on release-1.23.

#107406: fix: delete non existing disk issue

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by andrewsykim — COMMENTED** [review]
/approve

ack'ing that this is a bug fix

**Comment by cpanato** [comment]
> /cc kubernetes/release-managers

thanks! we will review/cp those after the patch release this week (Jan 19)

**Comment by puerco** [comment]
Thanks @andyzhangx !
/lgtm

**Pull request merged**
