### PR TITLE
	clean unused variables

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
clean unused variables on set.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
/lgtm

@soltysh  for approval

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
