### PR TITLE
Delete examples/examples_test.go

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: past-me was lazy (https://github.com/kubernetes/kubernetes/commit/c4455eeac81cd4482b90ee7e649273179a4a28ff), but getting this test to actually work isn't that difficult. Not running this in CI meant that the test unintentionally broke, so we should try to prevent that from happening in the future.

Note that this test will still fail until #60365 is merged.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @brendandburns

The alternative to fixing this test is just removing it entirely.

**Comment by cblecker** [comment]
I think @ahmetb mentioned that we could just get rid of the tests completely, because `examples/` is being deprecated.

**Comment by ixdy** [comment]
I'm also happy to delete this test, if that's the direction we want to take.

**Comment by ahmetb** [comment]
@ixdy Yes, let's just delete this test. This whole `examples/` directory will be gone in a week or so.

**Comment by ixdy** [comment]
OK, updated to just delete the test. This conflicts with #60365 now.

**Comment by ahmetb** [comment]
/lgtm

please ignore the `do-not-merge/blocked-paths` label in this situation. I'm not sure how to remove/cancel it.

**Comment by ixdy** [comment]
attempting to fix the lint error so the verify job will pass.

**Comment by cblecker** [comment]
@ixdy rebase required

**Comment by ixdy** [comment]
when rebasing, it helps if you actually fetch from the upstream remote.

**Comment by ahmetb** [comment]
/test pull-kubernetes-e2e-gce
--



/test pull-kubernetes-e2e-gce
--

**Review by zouyee — COMMENTED** [review]
Some related config files may to be cleaned.

**Comment by ahmetb** [comment]
Honestly we'll remove this `examples/` directory altogether now (since we finally moved everything to kubernetes/examples repo).

Not sure if we should merge this PR. There's another PR in progress that will `git rm -rf examples/` altogether

**Comment by ixdy** [comment]
@ahmetb do you have a link to the other PR?

**Comment by ixdy** [comment]
(I'm also happy to convert this into a PR that deletes `examples/` entirely.)

**Comment by ixdy** [comment]
the tricky aspect of removing `examples/` is that some kubectl unit tests depend on them, and some e2e tests (particularly the "examples" tests) do too.

**Comment by serathius** [comment]
Hi @ixdy 
related issue https://github.com/kubernetes/kubernetes/issues/60887
I'm currently fighting those tests :P

**Pull request closed without merging**
