### PR TITLE
bazel: update sha256sum on rules_go and io_bazel dependencies

### LINKED ISSUE #52307: bazel build failure: SHA of remote archive changed
I don't see an existing issue, so opening one for tracking.

PR builds are currently failing due to the SHA of a remote archive changing.

https://github.com/kubernetes/kubernetes/pull/52299#issuecomment-328623722

> The sha256sum of that archive apparently changed.
>
> > $ wget https://github.com/bazelbuild/rules_go/archive/82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
...
$ sha256sum 82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
27a13726ff8621cfa4592fbef116b253043c2b093c8814265dc4489a0e67d229  82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
>
> ???

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/test-infra-maintainers 

cc @krzyzacy @ixdy

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: mysteriously the sha256sum for one of the archive tarballs on GitHub changed. I still have no idea why.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52307

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @spxtr

### CODE REVIEW

**Comment by ericchiang** [comment]
cc @kubernetes/kubernetes-release-managers

**Comment by ericchiang** [comment]
bazel build is green

/lgtm

I think the federation e2e blocker is still blocked on https://github.com/kubernetes/kubernetes/pull/52299 which is in turn blocked on this PR. We may need to merge manually.

**Comment by spxtr** [comment]
LGTM, thanks.

**Comment by spxtr** [comment]
Worth asking build cop for a manual merge?

**Comment by lavalamp** [comment]
uh.... sha256's should't change?

**Comment by lavalamp** [comment]
manual merge based on comments here, but @ixdy can you figure out what happened?

**Comment by ixdy** [comment]
See the discussion in #52307, as well as some linked issues there. It seems github changed some of the tar headers in its archive tarballs, but I checked the extracted code and everything looks identical.

**Comment by lavalamp** [comment]
Thanks @ixdy!

**Pull request merged**
