### PR TITLE
[backport release-1.30]: fix(api): make LocalObjectReference.Name and HostAlias.IP required (#124553)

### PR DESCRIPTION
**Pull request by pmalek**
#### What type of PR is this?

/kind bug
/kind api-change

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.30.0 regression in openapi descriptions of imagePullSecrets and hostAliases fields to mark the fields used as keys in those lists as either defaulted or required.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
/cc kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]

**Comment by pmalek** [comment]
When can we expect 1.30.1 to be tagged?

**Comment by Arnavion** [comment]
This was revealed in v1.30.0 because of the `ImagePullSecrets` annotations change, but the underlying fact that `LocalObjectReference.name` and `HostAlias.ip` are required fields is true of older releases too, right?

**Comment by liggitt** [comment]
> the underlying fact that LocalObjectReference.name and HostAlias.ip are required fields is true of older releases too, right?

actual API validation did not change in 1.30, correct

LocalObjectReference.name is not required everywhere it is used, some places tolerate a missing value.

HostAlias.ip is required in validation, this update made the published schema indicate that.

**Pull request merged**
