### PR TITLE
WIP: apiextensions-apiserver: allow non-DNS1123 CR names

### PR DESCRIPTION
**Pull request by sttts**
/kind bug
/kind api-change

```release-note
Allow CustomResource names of non-DNS-1123 names.
```

### CODE REVIEW

**Comment by sttts** [comment]
/assign @deads2k @liggitt 

Was this intentional? 

Changing it is not that simple obviously. What would be a good path forward?

**Comment by liggitt** [comment]
Yes, it was intentional

**Comment by alexanderConstantinescu** [comment]
> Yes, it was intentional

Was there a particular rationale behind it? There could be use cases where someone would like to create a CR representing an IPv6 / MAC address. They don't abide to RFC 1123. It feels a bit restrictive enforcing that all cluster resources have a name respecting DNS standards.

**Comment by sttts** [comment]
> Yes, it was intentional

@liggitt what was the intention and does it still hold?

**Pull request closed without merging**
