### PR TITLE
cluster: cleanup unused scripts

### PR DESCRIPTION
**Pull request by neolit123**
> /kind cleanup

**What this PR does / why we need it**:

Verified with k/k and k/test-infra.

- restore-from-backup.sh
Performs restoration of etcd snapshots and the logic seems valid
on a quick look, but doesn't seem to be used anywhere in our infra.
I suspect this is used on demand for local testing, but /cluster root
doesn't seem like the right place for it at this point.
- test-*.sh
Gikgo related calls but these bash scripts seem unused in the infra.

If we have folks caring about these scripts let's move them to a sub-folder of /cluster for now.

**Which issue(s) this PR fixes**:

xref: https://github.com/kubernetes/kubernetes/issues/78995

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/kind cleanup
/priority backlog
/sig cluster-lifecycle testing api-machinery
?

**Comment by BenTheElder** [comment]
(above CC aiming for a review pass)
/assign @BenTheElder @dims 
(assign for approval)

**Comment by dims** [comment]
/approve

YES PLEASE!

**Pull request merged**
