### PR TITLE
Check static IP postcondition if op fails

### LINKED ISSUE #22244: e2e flake: Failed to create static ip
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22242/kubernetes-pull-build-test-e2e-gce/31096/?debugUI=CLOUD

```
NAME                             NETWORK             SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
e2e-gce-builder-3-3-master-https e2e-gce-builder-3-3 0.0.0.0/0  tcp:443          e2e-gce-builder-3-3-master
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Internal Error
 
Attempt 1 failed to create static ip e2e-gce-builder-3-3-master-ip. Retrying.
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-3-3-master-ip' already exists
 
Attempt 2 failed to create static ip e2e-gce-builder-3-3-master-ip. Retrying.
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-3-3-master-ip' already exists
 
Attempt 3 failed to create static ip e2e-gce-builder-3-3-master-ip. Retrying.
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-3-3-master-ip' already exists
 
Attempt 4 failed to create static ip e2e-gce-builder-3-3-master-ip. Retrying.
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-3-3-master-ip' already exists
 
Attempt 5 failed to create static ip e2e-gce-builder-3-3-master-ip. Retrying.
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-3-3-master-ip' already exists
 
Failed to create static ip e2e-gce-builder-3-3-master-ip 
2016/02/29 18:22:44 e2e.go:278: Error running up: exit status 2
2016/02/29 18:22:44 e2e.go:274: Step 'up' finished in 1m49.20839755s
2016/02/29 18:22:44 e2e.go:140: Error starting e2e cluster. Aborting.
exit status 1
Build step 'Execute shell' marked build as failure
```

@ixdy

### PR DESCRIPTION
**Pull request by thockin**
Fixes #22244 (kind of, more like a workaround for a cleanup bug we haven't nailed).

### CODE REVIEW

**Comment by thockin** [comment]
@ixdy @roberthbailey

**Comment by roberthbailey** [comment]
LGTM.

**Comment by ixdy** [comment]
it isn't really a cleanup bug. it's a gcloud bug.

**Comment by ixdy** [comment]
@k8s-bot test this, issue #22435

**Comment by thockin** [comment]
Maybe, I don't know how we got into the situation.  If glcoud said it was
deleted, and then it wasn't, yeah - gcloud bug.  If gcloud failed the
delete and we didn't rerty, it's our bug.  Regardless: the cleanup routines
should not voluntarily exit until they are sure that any lingering
artifacts are gone.

**Pull request merged**
