### PR TITLE
Fix and cleanup boilerplate_test.py

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

This PR fixes failing boilerplate test and cleans up its code.

#### Special notes for your reviewer:

This is a follow-up PR for #118320

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by liggitt** [comment]
is there a place to see where the test is currently failing, to see that this resolves the issue?

**Comment by bart0sh** [comment]
@liggitt Sure, here is how it fails in current master:
```
ed@devel ~/go/src/k8s.io/kubernetes/hack/boilerplate (master) $ python3 -m unittest boilerplate_test
E
======================================================================
ERROR: test_boilerplate (boilerplate_test.TestBoilerplate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ed/go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate_test.py", line 42, in test_boilerplate
    sys.stdout = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

It passes with the fix:
```
ed@devel ~/go/src/k8s.io/kubernetes/hack/boilerplate (PR130-cleanup-boilerplate_test) $ python3 -m unittest boilerplate_test
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

**Pull request merged**
