### PR TITLE
Add test for staging/src/k8s.io/apimachinery/pkg/version/staging/helpers.go

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add test for staging/src/k8s.io/apimachinery/pkg/version/staging/helpers.go

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @alexzielenski 
@alexzielenski could you review this one?
/triage accepted

**Comment by lavalamp** [comment]
We're in code freeze right now, this will go in when we open for v1.27

**Comment by my-git9** [comment]
> We're in code freeze right now, this will go in when we open for v1.27

ok,thanks

**Pull request merged**
