### PR TITLE
Cleanup systemd related shell out calls with API calls

### PR DESCRIPTION
**Pull request by yifan-gu**
Replace `systemctl --version` and `systemctl reset-failed` with API calls.
Also bumped go-systemd, which is necessary for the change.

cc @euank @philip @kubernetes/sig-node

### CODE REVIEW

**Comment by euank** [comment]
LGTM

**Comment by yifan-gu** [comment]
Rebased

**Comment by yifan-gu** [comment]
Removing the LGTM so we can get #25062 in first when ready to avoid more rebasing.

**Comment by yifan-gu** [comment]
Rebased. Applying LGTM back.

**Comment by yifan-gu** [comment]
Reworking this PR to replace the journalctl with the new getlog api in rkt api service.

**Comment by yifan-gu** [comment]
the rkt's getlogs() API has some issues which causes the api service to panic, so I am not going to include that commit in this PR. cc @euank

**Comment by pskrzyns** [comment]
Waiting for https://github.com/coreos/rkt/issues/2740

**Comment by yifan-gu** [comment]
> Waiting for coreos/rkt#2740

@pskrzyns Hmm, feels like we can make this first, and then send another PR for the getlogs once theissue is fixed?

**Comment by pskrzyns** [comment]
@yifan-gu i should think more before i write comment, i just wanted to make visible connection between those 2 issues

**Comment by pskrzyns** [comment]
LGTM

@yifan-gu yes, we can change getlogs in another PR

**Pull request merged**
