### PR TITLE
Avoid printing some service comments in iptables rules

### PR DESCRIPTION
**Pull request by wojtek-t**
According to some profiles, with large number of endpoints in the system, comments mentioning the service in appropriate iptables rules may be responsible for 40% of all iptables contents.

Given that ~70% of memory usage of kube-proxy seems to be because of generated iptables rules, the overall saving may be at the level of 30% or so.

OTOH, we sacrifise a bit understandability of iptables, but this PR only changes some of iptables that contribute to the most painful rules.

@thockin @danwinship @dcbw - thoughts?

Ref #65441

### CODE REVIEW

**Comment by thockin** [comment]
aww, I use this all the time.

I guess it seems like a reasonable tradeoff...  We probably should add the flag.

**Comment by wojtek-t** [comment]
> aww, I use this all the time.
I guess it seems like a reasonable tradeoff... We probably should add the flag.

Another option that I just came up with is to make it depend on the size of iptables. If they are small, we don't really care. And we can just avoid adding those comments in very large iptables.
Let me do that.

**Comment by wojtek-t** [comment]
@thockin - changed. PTAL if that is acceptable for you.

**Comment by dcbw** [comment]
Just a bit worried about debugability here; when the number of rules is > 1000, how would I match up a given rule with a specific service?

**Comment by wojtek-t** [comment]
> Just a bit worried about debugability here; when the number of rules is > 1000, how would I match up a given rule with a specific service?

With big enough iptables (maybe we should tune this number), I'm not sure they are super debuggable anyway... In the worst case, it's possible to connect pods with services and their ips and probably add those comments offline. Maybe a script for that is what we should also add?

**Pull request merged**
