### PR TITLE
run staging client-go update

### PR DESCRIPTION
**Pull request by deads2k**
Chasing to see what real problems we have in staging-client-go.

@sttts you get similar results?

### CODE REVIEW

**Comment by deads2k** [comment]
@smarterclayton @sttts running this seems to have correctly found the godeps from apimachinery and loaded them.

**Comment by sttts** [comment]
Getting:
```
$ ./copy.sh                                                                          
**PLEASE** run "godep restore" before running this script
creating the tmp directory
copying client packages
generating vendor/
godep: Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
rm -rf /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/staging/src/k8s.io/_tmp
```

**Comment by deads2k** [comment]
@sttts did you run godep restore first?

**Comment by sttts** [comment]
Yes, now I did. But it doesn't help.

**Comment by deads2k** [comment]
cleaning up compilation to deal with packages no longer in client-go

**Comment by deads2k** [comment]
logical conclusion of https://github.com/kubernetes/kubernetes/pull/39814 .  Only the last commit in this one is marginally interesting.  Basically all mechanical of reacting to removed packages.

**Comment by deads2k** [comment]
@k8s-bot verify test this

**Pull request merged**
