### PR TITLE
Fix log timestamps to maintain a fixed width

### LINKED ISSUE #72292: Container logs with timestamp are getting trailing zeroes trimmed
Container logs with timestamp=true display a ragged left edge on 1.11.2 with cri-o:

```
2018-12-22T00:34:33.084862626Z Pushed 5/6 layers, 83% complete
2018-12-22T00:35:03.196483456Z Pushed 5/6 layers, 87% complete
2018-12-22T00:35:33.203214994Z Pushed 5/6 layers, 89% complete
2018-12-22T00:36:03.271229927Z Pushed 5/6 layers, 92% complete
2018-12-22T00:36:33.34432357Z Pushed 5/6 layers, 96% complete
2018-12-22T00:37:03.444918533Z Pushed 5/6 layers, 98% complete
2018-12-22T00:37:36.90513849Z Pushed 6/6 layers, 100% complete
2018-12-22T00:37:41.364784926Z Push successful
```

It looks like when the nano section is written we're dropping the right most precision character (possibly because something is assuming it's a trailing zero, like a format).  Another section shows two missing chars:

```
2018-12-22T00:33:13.638865611Z Spawning worker 0 with 2 pkgs
2018-12-22T00:33:13.6388949Z Spawning worker 1 with 2 pkgs
2018-12-22T00:33:13.638899415Z Spawning worker 2 with 2 pkgs
```

which makes it seem likely that something is stripping trailing zeros off.  We should preserve them or otherwise people will go mad staring at the ragged logs.

@runcom @mrunalp since I'm not sure if this is crio, CRI, or Kubelet

/kind bug

### LINKED ISSUE #91186: Make Log Timestamps Fixed-Width to Ease Log Viewing and Processing
Although it can seem like a minor thing, and has been allowed to go on for a long time, it really does cause significant extra work for operations departments that the default Timestamp is [not fixed width](https://github.com/kubernetes/kubernetes/issues/72292), which leads to log messages not being aligned and frustrates column-oriented operations on logs. Notably, Docker does not have this problem (more below), and it is past time for Kubernetes to fix it.

The root cause is the use of the Go "time" package format RFC3339Nano (documented [here](https://golang.org/pkg/time/#pkg-constants) and [here](https://golang.org/src/time/format.go), see particularly lines 71 and 83). 

This issue goes back at least to 2016 when a [proposal for managing container stdout/stderr streams](https://github.com/kubernetes/community/commit/d4e935fefdbf802b0cbe9cc56ed576d99100fdbf) casually included the statement "The runtime should decorate each log entry with a RFC 3339Nano timestamp prefix". Note that RFC 3339Nano does not exist, but RFC 3339 does and apparently the RFC3339Nano format was created by the Go "time" package authors to create a time format compatible with RFC 3339 that included nanosecond resolution. It does not appear to have been a deeply considered choice, but rather a default choice of the only predefined time format that had nanosecond resolution and reference to a standard like an RFC. The choice of timestamp format was not the focus of the proposal and the author may have even been unaware of the fact that the timestamp format was variable width. 

Even when that proposal was made, Docker was [using](https://github.com/docker/cli/blob/d9cb421d69c79d6e97cfbea72e8e18228a3885e7/command/system/events.go#L80-L85) a fixed-width format dubbed "RFC3339NanoFixed", from the [jsonlog package](https://godoc.org/github.com/gdm85/docker/pkg/jsonlog#pkg-constants). Docker continues to use this format, though it no longer imports the constant from the jsonlog package, it defines the constant locally. 

I believe this can be fixed easily with a few simple changes to the code base.

## Proposed changes

NOTE: I do not want to sign the CNCF CLA for various reasons, and I cannot get `make verify` to succeed, even on released code, but am happy to have someone who has signed the CLA and can run all the tests use all the code and ideas I present here to make a contribution under their name or under section 7 on behalf of me. This is why I have provided patch-format diffs and included the license. 

An important point about formatting versus parsing has been raised in #89156 concerning apimachinery's use of a fixed-width timestamp format they call [RFC3339Micro](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/micro_time.go#L26). The point is that while we want to use a fixed-width format for *formatting* a timestamp, we should use a more lenient variable-width format for *parsing* a timestamp. It is for this reason we cannot globally replace RFC3339Nano. 

Since the name of the format shows up in documentation, I would use the established name RFC3339NanoFixed for the formatting format and copy the current RFC3339Nano format to a new constant named RFC3339NanoLenient for use in parsing, and add these to `pkg/kubelet/types/constants.go`

```
const (
  // fixed width version of time.RFC3339Nano
  RFC3339NanoFixed = "2006-01-02T15:04:05.000000000Z07:00"
  // variable width RFC3339 time format for lenient parsing of strings into timestamps
  RFC3339NanoLenient = "2006-01-02T15:04:05.999999999Z07:00"
)
```

Then, 2 changes to pkg/kubelet/types/types.go, 
<details><summary>Diff of types.go</summary>

```diff
diff --git a/pkg/kubelet/types/types.go b/pkg/kubelet/types/types.go
index 9c8f165ffe6..a840e7de84e 100644
--- a/pkg/kubelet/types/types.go
+++ b/pkg/kubelet/types/types.go
@@ -43,10 +43,10 @@ func NewTimestamp() *Timestamp {
        return &Timestamp{time.Now()}
 }
 
-// ConvertToTimestamp takes a string, parses it using the RFC3339Nano layout,
+// ConvertToTimestamp takes a string, parses it using the RFC3339NanoLenient layout,
 // and converts it to a Timestamp object.
 func ConvertToTimestamp(timeString string) *Timestamp {
-       parsed, _ := time.Parse(time.RFC3339Nano, timeString)
+       parsed, _ := time.Parse(RFC3339NanoLenient, timeString)
        return &Timestamp{parsed}
 }
 
@@ -55,10 +55,10 @@ func (t *Timestamp) Get() time.Time {
        return t.time
 }
 
-// GetString returns the time in the string format using the RFC3339Nano
+// GetString returns the time in the string format using the RFC3339NanoFixed
 // layout.
 func (t *Timestamp) GetString() string {
-       return t.time.Format(time.RFC3339Nano)
+       return t.time.Format(RFC3339NanoFixed)
 }
```
</details>

Finally, a bit more involved with `pkg/kubelet/kuberuntime/logs/logs.go` because we need to split output and input uses.

<details><summary>Diff of logs.go</summary>

```diff
diff --git a/pkg/kubelet/kuberuntime/logs/logs.go b/pkg/kubelet/kuberuntime/logs/logs.go
index 4bff06de2d4..ffb05a6c688 100644
--- a/pkg/kubelet/kuberuntime/logs/logs.go
+++ b/pkg/kubelet/kuberuntime/logs/logs.go
@@ -35,6 +35,7 @@ import (
        "k8s.io/api/core/v1"
        internalapi "k8s.io/cri-api/pkg/apis"
        runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1alpha2"
+       "k8s.io/kubernetes/pkg/kubelet/types"
        "k8s.io/kubernetes/pkg/util/tail"
 )
 
@@ -48,7 +49,8 @@ import (
 
 const (
        // timeFormat is the time format used in the log.
-       timeFormat = time.RFC3339Nano
+       timeFormatOut = types.RFC3339NanoFixed
+       timeFormatIn = types.RFC3339NanoLenient
 
        // logForceCheckPeriod is the period to check for a new read
        logForceCheckPeriod = 1 * time.Second
@@ -128,9 +130,9 @@ func parseCRILog(log []byte, msg *logMessage) error {
        if idx < 0 {
                return fmt.Errorf("timestamp is not found")
        }
-       msg.timestamp, err = time.Parse(timeFormat, string(log[:idx]))
+       msg.timestamp, err = time.Parse(timeFormatIn, string(log[:idx]))
        if err != nil {
-               return fmt.Errorf("unexpected timestamp format %q: %v", timeFormat, err)
+               return fmt.Errorf("unexpected timestamp format %q: %v", timeFormatIn, err)
        }
 
        // Parse stream type
@@ -238,7 +240,7 @@ func (w *logWriter) write(msg *logMessage) error {
        }
        line := msg.log
        if w.opts.timestamp {
-               prefix := append([]byte(msg.timestamp.Format(timeFormat)), delimiter[0])
+               prefix := append([]byte(msg.timestamp.Format(timeFormatOut)), delimiter[0])
                line = append(prefix, line...)
        }
        // If the line is longer than the remaining bytes, cut it.
```
</details>

<details><summary>Diff of logs_test.go</summary>

```diff
diff --git a/pkg/kubelet/kuberuntime/logs/logs_test.go b/pkg/kubelet/kuberuntime/logs/logs_test.go
index 493f2bd968d..25e3bd20e59 100644
--- a/pkg/kubelet/kuberuntime/logs/logs_test.go
+++ b/pkg/kubelet/kuberuntime/logs/logs_test.go
@@ -67,7 +67,7 @@ func TestLogOptions(t *testing.T) {
 }
 
 func TestParseLog(t *testing.T) {
-       timestamp, err := time.Parse(timeFormat, "2016-10-20T18:39:20.57606443Z")
+       timestamp, err := time.Parse(timeFormatIn, "2016-10-20T18:39:20.57606443Z")
        assert.NoError(t, err)
        msg := &logMessage{}
        for c, test := range []struct {
@@ -168,7 +168,7 @@ func TestWriteLogs(t *testing.T) {
                { // timestamp enabled
                        stream:       runtimeapi.Stderr,
                        timestamp:    true,
-                       expectStderr: timestamp.Format(timeFormat) + " " + log,
+                       expectStderr: timestamp.Format(timeFormatOut) + " " + log,
                },
        } {
                t.Logf("TestCase #%d: %+v", c, test)
@@ -189,7 +189,7 @@ func TestWriteLogs(t *testing.T) {
 
 func TestWriteLogsWithBytesLimit(t *testing.T) {
        timestamp := time.Unix(1234, 4321)
-       timestampStr := timestamp.Format(timeFormat)
+       timestampStr := timestamp.Format(timeFormatOut)
        log := "abcdefg\n"
 
        for c, test := range []struct {
```
</details>

---

<details><summary>This contribution is Unlicensed</summary>
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
</details>

### PR DESCRIPTION
**Pull request by stevechuck**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
```release-note
Fixed: log timestamps now include trailing zeros to maintain a fixed width
```

**Which issue(s) this PR fixes**:  
Fixes #91186
Fixes #72292 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
NONE
```

### CODE REVIEW

**Comment by Nuru** [comment]
@iamchuckss Thank you for pushing this forward. Here is a bit extra for you to include if you choose:

- Add: Fixes #72292 (it was closed as rotten, not fixed or dismissed)
- Add release notes:

```release-note
Fixed: log timestamps now include trailing zeros to maintain a fixed width
```

**Comment by dashpole** [comment]
We should probably update the KEP that says we will use the previous timestamp format.  Since the CRI logging format is an API, I consider this to be an API change, although I can't tell if there will be any backwards-compatibility issues here.  It would be helpful to describe what changes would be required for container runtimes (if any), and what changes would be required for log consumers (if any).

/ok-to-test
/kind api-change

**Comment by Nuru** [comment]
@dashpole Not exactly sure what you mean by "the KEP that says we will use the previous timestamp format". Do you mean [this](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md)? That proposal has not been adopted, as you can tell by the fact that logs do not include the Full or Partial indicator being proposed under "Log format", which is also where the timestamp format is proposed. I do not know where else the format is discussed. "RFC3339Nano" is mentioned is some of the documentation, but to be fair, it is not a real standard and Docker claims to output its logs in RFC3339Nano but is actually using the proposed RFC3339NanoFixed. 

>  It would be helpful to describe what changes would be required for container runtimes (if any), and what changes would be required for log consumers (if any).

It would be a very odd piece of software that would be negatively affected by this change. The change consists of keeping rather than trimming/removing trailing zeros in log timestamps. What is currently this:

```log
2020-05-11T00:59:53.112926311Z INFO log output
2020-05-11T00:59:53.11319083Z INFO log ouptput
2020-05-11T00:59:53.262609142Z WARN log output
```
will become this:
```log
2020-05-11T00:59:53.112926311Z INFO log output
2020-05-11T00:59:53.113190830Z INFO log ouptput
2020-05-11T00:59:53.262609142Z WARN log output
```

To the extent any consumer is using timestamps, this increased consistency is likely to be solving problems and fixing hidden bugs rather than creating them. It is a bit hard for me to imagine a system relying on this current behavior. It is possible that a system that tries to compensate for this behavior might be tricked into overcompensating, but that strikes me as unlikely. 


@iamchuckss I do not understand the build failures, but am happy to help if my help is needed/wanted. These appear to be build failures, and since I do not understand the build system and have never been able to get it to work locally, I really do not understand what is going wrong. 

My best guess it that the builder is trying to build `pkg/kubelet/kuberuntime/logs` but does not have the updated `k8s.io/kubernetes/pkg/kubelet/types`. Maybe this will help:

<details><summary>Add "//pkg/kubelet/types:go_default_library" to BUILD deps</summary>

```diff
diff --git a/pkg/kubelet/kuberuntime/logs/BUILD b/pkg/kubelet/kuberuntime/logs/BUILD
index 18b4c8ec45a..42cde17e300 100644
--- a/pkg/kubelet/kuberuntime/logs/BUILD
+++ b/pkg/kubelet/kuberuntime/logs/BUILD
@@ -6,6 +6,7 @@ go_library(
     importpath = "k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs",
     visibility = ["//visibility:public"],
     deps = [
+        "//pkg/kubelet/types:go_default_library",
         "//pkg/util/tail:go_default_library",
         "//staging/src/k8s.io/api/core/v1:go_default_library",
         "//staging/src/k8s.io/cri-api/pkg/apis:go_default_library",
```

</details>

**Comment by dashpole** [comment]
> That proposal has not been adopted, as you can tell by the fact that logs do not include the Full or Partial indicator being proposed under "Log format", which is also where the timestamp format is proposed.

I believe the proposal was implemented? https://github.com/kubernetes/kubernetes/pull/55922.

> To the extent any consumer is using timestamps, this increased consistency is likely to be solving problems and fixing hidden bugs rather than creating them. It is a bit hard for me to imagine a system relying on this current behavior. It is possible that a system that tries to compensate for this behavior might be tricked into overcompensating, but that strikes me as unlikely.

Great.  That is what I was looking for.  The example was helpful.

**Comment by Nuru** [comment]
> > That proposal has not been adopted, as you can tell by the fact that logs do not include the Full or Partial indicator being proposed under "Log format", which is also where the timestamp format is proposed.
> 
> I believe the proposal was implemented? #55922.
> 

@dashpole Sorry, I was a bit confused. The [document](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md) I referred to is a proposal...

> ...to define how container's stdout/stderr log streams should be handled in CRI. The explicit non-goal is to define how (non-stdout/stderr) application logs should be handled. 

While that proposal was partly implemented in #55922, it defines the log format output by the Container Runtime and parsed by kubelet (and fluentd and others). Our PR here does not modify that interface in any way. We have specifically created a separate `timeFormatIn` which is identical to the currently used RFC3339Nano to be used in all input and parsing operations, so while the name of the variable has changed, the value has not. Also, as I have stated previously, Docker, the most commonly use Container Runtime, already outputs logs with fixed-width timestamps. 

Our PR only affects the Pod's [Read Log](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#read-log-pod-v1-core) API, and although it is documented to optionally add "an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output", the fact that RFC3339 and RFC3339Nano reference Go language formats is not made clear, so I think this change is not violating the spirit of the documentation. 

There is no option for choosing between RFC3339 or RFC3339Nano formats so it is already unclear what to expect. RFC 3339 (the standard, not the constant) allows any number of digits for the fractional second representation. Still, I think it is worth updating the documentation.

@iamchuckss 3 more minor changes for you:

<details><summary>Revise documentation of Read Log API</summary>

```diff
diff --git a/pkg/apis/core/types.go b/pkg/apis/core/types.go
index 3944d5dcadc..9418a118eac 100644
--- a/pkg/apis/core/types.go
+++ b/pkg/apis/core/types.go
@@ -4252,7 +4252,7 @@ type PodLogOptions struct {
        // If this value is in the future, no logs will be returned.
        // Only one of sinceSeconds or sinceTime may be specified.
        SinceTime *metav1.Time
-       // If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line
+       // If true, add an RFC 3339 timestamp with 9 digits of fractional seconds at the beginning of every line
        // of log output.
        Timestamps bool
        // If set, the number of lines from the end of the logs to show. If not specified,
```
</details>

<details><summary>Revise documentation of format variables API</summary>

```diff
diff --git a/pkg/kubelet/kuberuntime/logs/logs.go b/pkg/kubelet/kuberuntime/logs/logs.go
index 07f8782d594..e06709e3696 100644
--- a/pkg/kubelet/kuberuntime/logs/logs.go
+++ b/pkg/kubelet/kuberuntime/logs/logs.go
@@ -48,8 +48,9 @@ import (
 // TODO(random-liu): Support log rotation.
 
 const (
-       // timeFormatOut and timeFormatIn are time formats used in the log.
+       // timeFormatOut is the format for writing timestamps to output.
        timeFormatOut = types.RFC3339NanoFixed
+       // timeFormatIn is the format for parsing timestamps from other logs.
        timeFormatIn  = types.RFC3339NanoLenient
 
        // logForceCheckPeriod is the period to check for a new read
```
</details>

<details><summary>Modify test to detect timestamp truncation</summary>

```diff
diff --git a/pkg/kubelet/kuberuntime/logs/logs_test.go b/pkg/kubelet/kuberuntime/logs/logs_test.go
index 25e3bd20e59..f53b93037e6 100644
--- a/pkg/kubelet/kuberuntime/logs/logs_test.go
+++ b/pkg/kubelet/kuberuntime/logs/logs_test.go
@@ -143,7 +143,7 @@ func TestParseLog(t *testing.T) {
 }
 
 func TestWriteLogs(t *testing.T) {
-       timestamp := time.Unix(1234, 4321)
+       timestamp := time.Unix(1234, 43210)
        log := "abcdefg\n"
 
        for c, test := range []struct {
```

**Comment by iamchuckss** [comment]
@Nuru Done!

**Comment by iamchuckss** [comment]
/assign @thockin
for approval

**Comment by Nuru** [comment]
/assign @smarterclayton 

The robot assigned thockin but since this fixes a bug you opened (#72292), perhaps you would be interested in reviewing and approving it

**Comment by Nuru** [comment]
@dashpole Do you want anything more or can we get a LGTM from you?

**Comment by dashpole** [comment]
nope, thanks for the explanation.  This isn't a CRI change, its a kubelet pod logs endpoint change.

/lgtm
for kubelet changes.  I'll leave it to @smarterclayton or @derekwaynecarr to approve the sort-of-api-change.

**Comment by smarterclayton** [comment]
I believe this change is within the spirit of our API guidelines - the precision was variable before, it is unlikely that anyone was successful at hardcoding precision, and while this may change parsing of ReadLog output, it is defined in a broad fashion.  I'm willing to chance a very small number of parsing scripts that were subtly wrong are impacted.

/approve

**Comment by Nuru** [comment]
@smarterclayton Thanks for the approval. What do you think about cherry-picking this back to currently supported releases? I know it is not a critical bug fix, but it is also small and low-risk.

**Comment by Nuru** [comment]
@iamchuckss Thanks for doing this PR. What do you think of proposing [cherry-picks](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick) so we can see this sooner rather than later?

**Comment by iamchuckss** [comment]
@Nuru That's fine with me, I can initiate a cherry pick request.

**Comment by Nuru** [comment]
@iamchuckss Thanks. Would you also please cherry pick to 1.17 and 1.16 (and 1.15 if that is still an option)?

**Pull request merged**
