### PR TITLE
 Fix golint failure in pkg/util/labels

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:

-  pkg/util/labels

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test

**Review by spiffxp — CHANGES_REQUESTED** [review]

**Comment by spiffxp** [comment]
@smarterclayton What's the intent behind `pkg/util/labels/.readonly`? You added it in https://github.com/kubernetes/kubernetes/pull/40178.  This PR is trying to remove it and I'm not sure why, or if it should

**Comment by xichengliudui** [comment]
Please combine multiple submissions into one, thank you

**Comment by ZP-AlwaysWin** [comment]
> Please combine multiple submissions into one, thank you

hi @xichengliudui 
I made a mistake in submitting the PR of others and merged it in. It is estimated that the PR will be abolished this time.

**Comment by spiffxp** [comment]
Please redo this PR so it contains just your commit.
/hold
I'm still unclear what the purposes of the `.readonly` file I mentioned above is, or why you're removing it, and would like that answered before we move forward with touching anything here

**Comment by spiffxp** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/pull/80095

the question about .readonly still stands (ref: https://github.com/kubernetes/kubernetes/pull/80685#issuecomment-516117611)

**Pull request closed without merging**
