### PR TITLE
Fixed several spelling mistakes

### PR DESCRIPTION
**Pull request by Niekvdplas**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fixes several spelling mistakes all throughout the project

#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

N/A

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

**Comment by jiahuif** [comment]
/ok-to-test
Could you avoid changing anything under `vendor/` directly? These changes will fail the vendor verification.

**Comment by jiahuif** [comment]
Seems like `vendor/github.com/google/cadvisor/container/containerd/handler.go` was not reverted. Please squash all commits afterwards.

**Comment by Niekvdplas** [comment]
> Seems like `vendor/github.com/google/cadvisor/container/containerd/handler.go` was not reverted. Please squash all commits afterwards.

Will do, thank you.

**Comment by Niekvdplas** [comment]
> Seems like `vendor/github.com/google/cadvisor/container/containerd/handler.go` was not reverted. Please squash all commits afterwards.

What now?

**Comment by Niekvdplas** [comment]
> /retest

How is it able to fail 3 times in a row? I've not done anything which could cause that 🤔

**Pull request merged**
