### PR TITLE
Disable proxy use in http  probe

### PR DESCRIPTION
**Pull request by WanLinghao**
Disable node's proxy use of http probe

```release-note
disable node's proxy use of http probe
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@smarterclayton This patch is ready, PTAL

**Comment by WanLinghao** [comment]
@smarterclayton friendly ping

**Comment by WanLinghao** [comment]
@smarterclayton  PTAL thanks

**Comment by WanLinghao** [comment]
@smarterclayton  Now unit test added, PTAL

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
@smarterclayton for approval

**Pull request merged**
