### PR TITLE
More assertive borrowing by exempt

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR changes the way that exempt priority levels borrow from non-exempt ones in API Priority and Fairness. Note that the code does not match the KEP on this matter, which is Issue #124125 . This PR shifts the code to a middle position. A companion PR (https://github.com/kubernetes/enhancements/pull/4623) shifts the KEP to the same place.

#### Which issue(s) this PR fixes:

This is the code part of one possible way to addressing #124125 .

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
This change makes sense to me, but we need some tests for it...

**Comment by deads2k** [comment]
Code and test match the objectives.

/lgtm
/approve

**Pull request merged**
