### PR TITLE
Ineffassign fixes for pkg/controller and kubelet

### PR DESCRIPTION
**Pull request by alena1108**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Some places in call had ineffectual assignments. This PR addresses a couple of minor items in `pkg/controller` and `pkg/kubelet`

**Which issue(s) this PR fixes**:

Fixes #

N/A

**Special notes for your reviewer**:

This PR is an offspring of https://github.com/kubernetes/kubernetes/pull/87462 where it was suggested to split the fixes on per package basis

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

cc @lavalamp

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks!

**Comment by alena1108** [comment]
@tanjunchen @mattjmcnaughton the tests are green, let me know if there is anything else needed in order for this pr to be merged

**Comment by mattjmcnaughton** [comment]
/assign @piosz @random-liu

These folks have permissions to sign-off :)

**Pull request merged**
