### PR TITLE
Include PodStatus.Message and PodStatus.Reason when kubectl describe …

### LINKED ISSUE #10324: `kubectl describe pod` should list the reason/message of the status
The reason/message is important when debugging why the pod is in the current non-running state. 

E.g., here is the output from `describe pod`, which only shows the status is failed without giving any explanation.
```
Name:				foo
Image(s):			ubuntu,ubuntu
Node:				e2e-test-yjhong-minion-y38q/
Labels:				<none>
Status:				Failed
IP:				
Replication Controllers:	<none>
Containers:
```

If you do `get pod foo -o json`, you can see the message/reason that explains the status.
```
    "status": {
        "phase": "Failed",
        "message": "Pod was active on the node longer than specified deadline",
        "reason": "DeadlineExceeded",
        "startTime": "2015-06-25T00:02:37Z"
    }
```

Sometimes a relevant event is recorded and shows up in the output of `describe pod`, but sometimes there is no such an event. We also cannot rely on events too much since they will be flushed after sometime. I think we should include the information in `describe pod`

### PR DESCRIPTION
**Pull request by dchen1107**
…pods

Fixed #10324

cc/ @bgrant0607 @yujuhong

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, though I'd flip the order.

**Comment by dchen1107** [comment]
Yes, flipped the order per your request. :-)

**Comment by bgrant0607** [comment]
Thanks, still LGTM. :-)

**Comment by bgrant0607** [comment]
Needs a 2nd LGTM. @brendandburns

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
