### PR TITLE
Remove skip list ENVs, instead rely on labels

### PR DESCRIPTION
**Pull request by ikehz**
Toward #10548.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Changes:

- Running slow in upgrade tests & flannel
- Make `aws` parallel and remove `aws-parallel`, to have it as a smoke test for AWS per @brendandburns 

Otherwise, this should be a no-op.

**Comment by ixdy** [comment]
LGTM

**Comment by ixdy** [comment]
@k8s-bot e2e test this please, issue #IGNORE

**Comment by ihmccreery** [comment]
@k8s-bot test this again please, issue #20031

**Comment by ihmccreery** [comment]
Oops.  @k8s-bot unit test this again please, issue #20031

**Pull request merged**
