### PR TITLE
kubelet: promote OS & arch labels to GA

### LINKED ISSUE #72929: Promote node os/arch label to stable
**What would you like to be added**:
kubelet self labels the node with OS/arch, etc. The labeling was added backed in 1.3. It's time to promote the labels.
```
LabelOS   = "beta.kubernetes.io/os"
LabelArch = "beta.kubernetes.io/arch"
```

**Why is this needed**:
This feature has already been used in multiple places to help schedule pods onto the right nodes.

For the transition, kubelet will need to label itself with both the beta and the GA label to handle the master-node version skew for a few releases.

/cc @kubernetes/sig-node-feature-requests @dchen1107 @derekwaynecarr @liggitt @luxas  
/cc @PatrickLang @pjh @mtaufen

### PR DESCRIPTION
**Pull request by yujuhong**
kubelet now applies both the beta and the GA labels to ensure backward
compatibility.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #72929

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Node OS/arch labels are promoted to GA
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

Thanks!
Please write some docs about this change as well :)

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by derekwaynecarr** [comment]
I’m fine with the change, can we have a follow-up issue so that we don’t forget to remove it in 1.17?

**Comment by derekwaynecarr** [comment]
Per the enhancements process, are we required to have a kep for this that says the plan around deprecation?

**Comment by derekwaynecarr** [comment]
@liggitt is there a general kep around labeling that we can piggyback?

**Comment by yujuhong** [comment]
@derekwaynecarr filed an issue #73084. Will update the documentation next week.

> Per the enhancements process, are we required to have a kep for this that says the plan around deprecation?

Do we need a KEP for everything? :-|

**Comment by bgrant0607** [comment]
The short answer to whether a KEP is needed for everything is yes.

This release note is inadequate. Please read https://github.com/kubernetes/community/issues/484

**Pull request merged**
