### PR TITLE
remove pkg/config/config_test.json

### PR DESCRIPTION
**Pull request by caesarxuchao**
#8087

@nikhiljindal @bgrant0607 @krousey

### CODE REVIEW

**Comment by bgrant0607** [comment]
Why are you removing this rather than replacing it with a v1 test?

config.go and config_test.go still exist.

**Comment by caesarxuchao** [comment]
I removed it because it's not used anywhere. Digging a little bit more, I found it was used to illustrate the format expected by "createall" (see [here](https://github.com/GoogleCloudPlatform/kubernetes/pull/1958#issuecomment-61641862)). I think we don't have createall command anymore, so we can safely remove it.

**Comment by bgrant0607** [comment]
I don't see any obvious uses of this package. Can all of pkg/config be removed?

**Comment by caesarxuchao** [comment]
It passes unit tests and integration tests after pkg/config is removed. I will remove the package in this PR.

**Comment by caesarxuchao** [comment]
I've removed pkg/config

**Comment by nikhiljindal** [comment]
Needs a rebase

**Comment by caesarxuchao** [comment]
Rebased. Thanks.

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Pull request merged**
