### PR TITLE
`kubectl drain` ordered by priority

### LINKED ISSUE #1347: kubectl drain: influencing order of draining Pods
### What would you like to be added?

I would like to be able to influence order in which `kubectl drain` evicts `Pod`s from the node. ~~I did not check whether Graceful Node Shutdown logic is also affected.~~ Graceful Node Shutdown logic is not applicable here as it's closely tied to handling `systemd` shutdown signals (or something in this manner).

#### Proposed solution

The MVP could be a new flag (eg: `--respect-priorities`) that would make `kubectl drain` group `Pod`s by their `.spec.priority` value and then evict from lowest to highest value.

This could be quite easily implemented in either [`DeleteOrEvictPods()`](https://github.com/kubernetes/kubernetes/blob/21184400a4ac185e7e4c6ddb52eb9c25a4cc453f/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L247-L270) or one of it's child functions.

### Why is this needed?

In my concrete use case I'm running single-node `k3s` cluster on a bulky desktop machine that is also my main daily driver and I am unable to properly reboot machine (or just shut down the cluster) using just `kubectl drain` because of evictions of Rook's Ceph OSDs (marked as `system-node-critical` priority) before Pods using Ceph based PVCs (making them perpetualy `Terminating` until OSD comes up again)

The improvement could be more widely employed to:
- cleanly shutting down kubernetes in preparation for node maintenance
- cleanly shutting down whole clusters (eg: for the weekend)

### LINKED ISSUE #109353: kubectl drain: influencing order of draining Pods
### What would you like to be added?

I would like to be able to influence order in which `kubectl drain` evicts `Pod`s from the node. I did not check whether Graceful Node Shutdown logic is also affected.

### Proposed solution

The MVP could be a new flag (eg: `--respect-priorities`) that would make `kubectl drain` group `Pod`s by their `.spec.priority` value and then evict from lowest to highest value.

This could be quite easily implemented in either [`DeleteOrEvictPods()`](https://github.com/kubernetes/kubernetes/blob/21184400a4ac185e7e4c6ddb52eb9c25a4cc453f/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L247-L270) or one of it's child functions.

### Why is this needed?

In my concrete use case I'm running single-node `k3s` cluster on a bulky desktop machine that is also my main daily driver and I am unable to properly reboot machine (or just shut down the cluster) using just `kubectl drain` because of evictions of Rook's Ceph OSDs (marked as `system-node-critical` priority) before Pods using Ceph based PVCs (making them perpetualy `Terminating` until OSD comes up again)

The improvement could be more widely employed to cleanly shutting down the whole clusters.

### PR DESCRIPTION
**Pull request by nazarewk**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Allows grouping Pods by their `.spec.priority` values and draining them in groups: lowest to highest priority similarily to shutdown manager
https://github.com/kubernetes/kubernetes/blob/21184400a4ac185e7e4c6ddb52eb9c25a4cc453f/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L360-L390

As explained in the linked issue allows cleaner shutdown when priority is crucial for pod termination (PVC is handled by Ceph OSDs which blocks on kernel level until OSD is ready again)

#### Which issue(s) this PR fixes:

Fixes kubernetes/kubectl#1347

#### Special notes for your reviewer:

This PR is still a draft and has stuff missing

I am testing it on my NixOS through http://github.com/nazarewk-iac/nix-configs/commit/2b38cb4f

#### Does this PR introduce a user-facing change?

```release-note
- kubectl drain now allows draining pods in waves by their priorities through `--by-priority` flag
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nazarewk** [comment]
FYI: I got it to work just fine on my node then squashed to 1 commit.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by nazarewk** [comment]
I will rebase soon, hopefully at start of next year finally get to talk about it on contributor meeting and finalize

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by nazarewk** [comment]
> @nazarewk, wondering what is the plan of this work? I think this is a very useful feature for a lot use cases.

Some months ago I have attended a SIG meeting talking about this for a few minutes, but still didn't find enough time to follow through with the with more in-depth discussion and the whole proposal process.
If anyone has motivation to get it discussed and merged feel free to do so.

**Pull request closed without merging**
