### PR TITLE
[1.16] Automated cherry pick of #82841: Fixed a scheduler panic on PodAffinity

### PR DESCRIPTION
**Pull request by Huang-Wei**
Cherry pick of #82841 on release-1.16.

#82841: Fixed a scheduler panic on PodAffinity

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by tpepper** [comment]
/sig scheduling
/kind bug
from parent PR.

**Comment by ahg-g** [comment]
The title is not correct, we are not cherry picking the "Benchmark test"

**Comment by Huang-Wei** [comment]
@ahg-g yeap, I think the `hack/cherry_pick_pull.sh` automatically picks up the title of the first commit.

**Review by draveness — COMMENTED** [review]
/lgtm

**Pull request merged**
