### PR TITLE
Add apiserver flowcontrol metric `current_inqueue_seats`

### PR DESCRIPTION
**Pull request by andrewsykim**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This metric is analogous to `current_inqueue_requests` but tracks total seats that are currently inqueued by APF.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Introduce new apiserver metric apiserver_flowcontrol_current_inqueue_seats. This metric is analogous to `apiserver_flowcontrol_current_inqueue_requests` but tracks totals seats as each request can take more than 1 seat. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
@wojtek-t @MikeSpreitzer fixed failing test and removed WIP label, PTAL :)

**Comment by wojtek-t** [comment]
This LGTM, but I will give a chance to @MikeSpreitzer to also take a look.

/approve

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Pull request merged**
