### PR TITLE
Add --norecurse bool to allow mungedocs to process kube root.

### PR DESCRIPTION
**Pull request by david-mcmahon**
In support of https://github.com/kubernetes/kubernetes/pull/23419#discussion_r57271677.

### CODE REVIEW

**Comment by david-mcmahon** [comment]
@eparis This isn't exactly what I want.  I really just need the automatic TOC regeneration.  I'm not sure we want all the other munging for the root level .md files.  Thoughts?

**Comment by eparis** [comment]
I do not like the versioned warnings (anywhere in the repo to be honest). The other changes I'm fine/good with at the root level...

**Comment by david-mcmahon** [comment]
Thanks.  LGTY?

**Comment by david-mcmahon** [comment]
@ixdy @spxtr Any idea what might be wrong with travis here?  I cannot repro.  Something wonky in the env?

**Comment by ixdy** [comment]
@david-mcmahon 
```
Verifying hack/../hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./cmd/mungedocs/mungedocs.go
FAILED   hack/../hack/verify-gofmt.sh	5s
```

**Comment by david-mcmahon** [comment]
@eparis @bgrant0607 Can one of you lgtm this?  Hopefully this last change fixes all of the travis and other checks.

**Comment by bgrant0607** [comment]
@johndmulhausen How would you feel about eliminating the version warnings in docs in kubernetes/master?

**Comment by eparis** [comment]
3, maybe even 4 thumbs up.

**Comment by david-mcmahon** [comment]
@k8s-bot unit test this please, flake #23747

**Comment by fabioy** [comment]
Manually merging.

**Pull request merged**
