### PR TITLE
Add --ip to kubectl proxy

### PR DESCRIPTION
**Pull request by karlkfi**
Needed to allow binding to a non-localhost port.

Use Case: running kubernetes in a VM and running a proxy as an upstart service in the VM that binds to the exposed IP so that the kube-ui can be made available outside of the VM.

### CODE REVIEW

**Comment by lavalamp** [comment]
The kubernetes mechanism for doing this is to make a service (of type LoadBalancer or NodePort). Or you can use the apiserver proxy. Why do those solutions not work for your use case?

**Comment by karlkfi** [comment]
I did eventually get the kube-ui exposed correctly. The problem turned out to be having a dev version of docker 1.7 installed. Once I upgraded to the latest release version of docker 1.7, the dns was properly exposed.

This could still be useful, if you wanted to bind to something other than localhost, but it's not required for the use case I previously had.

**Comment by lavalamp** [comment]
Sorry, my last comment was written because I misread this as changing kube-proxy, not kubectl proxy, which is why it probably didn't make any sense at all. :)

I think we probably don't want kubectl proxy to serve on anything but localhost, because it removes auth and would leave your cluster wide open. @stephenR does that sound reasonable to you?

**Comment by karlkfi** [comment]
In our case, we were using it to make a background daemon running on a local VM (within a network space unaccessible outside of the local host) to deliberately host and expose the static ui files to the local host. While not exactly why we did it, this turned out to be pretty useful if you wanted to make changes to the ui and see changes in real time, without rebuilding and redeploying kube-ui as a pod.

I would agree that the kube-proxy shouldn't allow you to expose yourself to the world, but the kubectl proxy seems like it's mostly for development anyway. Is there some other primary use case I'm missing?

I won't push this too hard. I'm not developing the kube-ui right now. It just seemed potentially useful and worth sharing.

**Comment by stephenR** [comment]
> I think we probably don't want kubectl proxy to serve on anything but localhost, because it removes auth and would leave your cluster wide open. @stephenR does that sound reasonable to you?

Yeah, I think it's dangerous because it will expose the API without any authentication. But if there's a good use case for it, I think it could be fine if it's behind a flag and people are made aware of the risk.

**Comment by lavalamp** [comment]
> I won't push this too hard. I'm not developing the kube-ui right now. It just seemed potentially useful and worth sharing.

I understand. Thanks for the PR; I think for the moment we will not include this, but definitely let us know if you think of another use case.

**Pull request closed without merging**
