### PR TITLE
log response size of a request

### PR DESCRIPTION
**Pull request by weiyuanke**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
log response size 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by weiyuanke** [comment]
I signed it

**Comment by yliaog** [comment]
could you please create an issue to describe why response size is needed, and reference it in this PR?

also please add a test case.

**Comment by dims** [comment]
no response from @weiyuanke for reviewer comment from Oct. please reopen if needed.

/close

**Pull request closed without merging**
