### PR TITLE
Removed non-md files from docs. Moved doc yamls to test/fixtures.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Most of the contents of `docs/` has moved to kubernetes.github.io. Development of the docs and accompanying files has continued there, making the copies in this repo stale.

I've removed everything but the .md files which remain to redirect old links. The .yaml config files in the docs were used by some tests, these have been moved to `test/fixtures/doc-yaml`, and can remain there to be used by tests or other purposes.

Testing of the doc yamls in `examples/examples_test.go` has been removed, as the current yamls (surfaced in the docs) are now tested in the kubernetes.github.io repo

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31452)

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Note: this is _not_ needed for v1.4

**Comment by brendandburns** [comment]
LGTM.  Thanks!

Manually removing the do-not-merge label since this is an exception to the policy.

**Comment by kargakis** [comment]
@jeffmendoza  you also need to update docs in https://github.com/kubernetes/kubernetes.github.io

For example, http://kubernetes.io/docs/admin/resourcequota/walkthrough/

**Comment by jeffmendoza** [comment]
The docs shall now refer to the yamls that are within the doc / website repo. These forked from the yamls in this repo and many have been further developed there alongside the docs.

**Comment by kargakis** [comment]
@jeffmendoza I see, sorry for the noise

**Pull request merged**
