### PR TITLE
Add node problem detector as an addon pod.

### PR DESCRIPTION
**Pull request by Random-Liu**
``` release-note
Introduce a new add-on pod NodeProblemDetector.

NodeProblemDetector is a DaemonSet running on each node, monitoring node health and reporting
node problems as NodeCondition and Event. Currently it already supports kernel log monitoring, and
will support more problem detection in the future. It is enabled by default on gce now.
```

This PR enables NodeProblemDetector as an add-on pod.

/cc @mikedanese @kubernetes/sig-node 

[Analytics]()

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM overall. But have you run feasibility check related test? I am wondering this newly introduced daemonset will break those tests.

**Comment by Random-Liu** [comment]
I run all SchedulerPredicates test just now, and get the following result:
```
Summarizing 6 Failures:

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that InterPodAffinity is respected if matching [Feature:PodAffinity] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:929

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that InterPodAffinity is respected if matching with multiple Affinities [Feature:PodAffinity] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:1117

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that embedding the JSON PodAffinity and PodAntiAffinity setting as a string in the annotation value work 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:1282

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that Inter-pod-Affinity is respected if not matching [Feature:PodAffinity] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:114

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that InterPod Affinity and AntiAffinity is respected if matching [Feature:PodAffinity] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:1220

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that InterPodAntiAffinity is respected if matching 2 [Feature:PodAffinity] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:114

Ran 17 of 298 Specs in 424.268 seconds
FAIL! -- 11 Passed | 6 Failed | 0 Pending | 281 Skipped --- FAIL: TestE2E (424.67s)
```

Looks like the [Feature:PodAffinity] ones are skipped by default. I'll look into this one:
```
validates that embedding the JSON PodAffinity and PodAntiAffinity setting as a string in the annotation value work
```

**Comment by Random-Liu** [comment]
I found the reason why the test failed. It is unrelated with this PR.
These 2 tests:
`validates that embedding the JSON PodAffinity and PodAntiAffinity setting as a string in the annotation value work`
and
`validates that embedding the JSON NodeAffinity setting as a string in the annotation value work
`
They apply node labels `kubernetes.io/e2e-az-name` and `e2e.inter-pod-affinity.kubernetes.io/zone` to a specific node and expect the pod to be scheduled on that node. After the test, they never tried to clean up the labels.

So if I run the test for more than once, there may be more than one nodes be labelled. Then the pod may be scheduled on any of these labelled nodes, which causes the test failure.

We should:
* Cleanup the label after the test if possible.
* Or randomize the label key if possible.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @jlowdermilk @roberthbailey

**Pull request merged**
