### PR TITLE
Prevent deadlock on azure zone fetch in presence of failure

### PR DESCRIPTION
**Pull request by cehoffman**
**What this PR does / why we need it**:

This fixes a bug in the Zone get function for the Azure cloud provider.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix deadlock in azure cloud provider zone fetching
```

### CODE REVIEW

**Comment by cehoffman** [comment]
CLA signed

**Comment by cehoffman** [comment]
Not sure why it is still showing a missing CLA signature. The email address on the commit, in the GPG signature, on my profile, and on the CNCF CLA are all my work email.

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by roberthbailey** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
/retest
@kubernetes/sig-azure-misc

**Comment by jdumars** [comment]
@khenidak PTAL

**Comment by jdumars** [comment]
any idea if this needs to land in 1.9?

**Comment by khenidak** [comment]
Yes we need that. 

Later we probably need to remove the lock all together. I believe we don’t locking

**Comment by jdumars** [comment]
Ok, confirmed this is a must-have for 1.9.

**Pull request merged**
