### PR TITLE
[1.20][go1.15] Update to go1.15.13

### PR DESCRIPTION
**Pull request by thejoycekung**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Update to Go 1.15.13

Tracking issue: https://github.com/kubernetes/release/issues/2107
Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1623076353251200

/assign @cpanato @justaugustus @liggitt @dims 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built using Go 1.15.13
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

thanks for this Joyce! 🎉

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
