### PR TITLE
Robustly cleanup MIG template on GCE teardown

### LINKED ISSUE #11009: GCE doesn't clean up node instance templates after upgrade
An upgrade changes the instance template but `kube-down` doesn't know the name could have changed.

I'm working on a fix now.

### PR DESCRIPTION
**Pull request by mbforbes**
Fixes #11009

To verify this is working, I ran the following and checked that all templates were gone afterwards:

``` bash
$ make release-skip-tests
$ go run hack/e2e.go --up --down --v --test --test_args="--ginkgo.focus=Skipped.*Cluster\supgrade.*upgrade-cluster" --check_version_skew=false
```

### CODE REVIEW

**Comment by mbforbes** [comment]
Possible reviewers:
+cc @roberthbailey has context (I fixed this in GKE...)
+cc @zmerlynn has upgrade context
+ ... ?

**Comment by roberthbailey** [comment]
@mbforbes Have you manually tested this?

**Comment by roberthbailey** [comment]
The bash changes LGTM.

**Comment by zmerlynn** [comment]
LGTM

**Comment by mbforbes** [comment]
@roberthbailey yes! See https://github.com/GoogleCloudPlatform/kubernetes/pull/11018#issue-94161337

**Comment by mbforbes** [comment]
Let's do a round of kicking

**Comment by mbforbes** [comment]
Ugh Jenkins flakes
```
Kubernetes e2e suite.Services should serve a basic endpoint from pods (from (junit_10.xml))

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:134
Timed out waiting for service endpoint-test2 in namespace e2e-tests-service-0-2oyui to expose endpoints map[test1:[80] test2:[80]] (1m0s elapsed)
```

Every time I see one I think *RELEGATE TO THE FLAKE LIST*

Anyway kicking...

**Comment by mbforbes** [comment]
@k8s-bot test this please

**Comment by roberthbailey** [comment]
Bouncing to @alex-mohr for ok-to-merge.

**Comment by mbforbes** [comment]
Well, this is unrelated to this PR, but it appears we have a new failure case for e2e tests; this repeats forever until the build dies:

```
[1] INFO: 9 / 14 pods in namespace 'kube-system' are running and ready (20 seconds elapsed)
[1] INFO: POD                           NODE                    PHASE   CONDITIONS
[1] INFO: kube-ui-v1-bp9s2              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-dk10d              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-eahns              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-zvxka              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: monitoring-heapster-v5-5v5rp  pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: 
[1] INFO: 9 / 14 pods in namespace 'kube-system' are running and ready (20 seconds elapsed)
[1] INFO: POD                           NODE                    PHASE   CONDITIONS
[1] INFO: kube-ui-v1-bp9s2              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-dk10d              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-eahns              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-zvxka              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: monitoring-heapster-v5-5v5rp  pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: 
[1] INFO: 9 / 14 pods in namespace 'kube-system' are running and ready (20 seconds elapsed)
[1] INFO: POD                           NODE                    PHASE   CONDITIONS
[1] INFO: kube-ui-v1-bp9s2              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-dk10d              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-eahns              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: kube-ui-v1-zvxka              pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: monitoring-heapster-v5-5v5rp  pull-e2e-2-minion-yl9w  Failed  []
[1] INFO: 
...
```

@ixdy do you know if this is a flake or a new regression?

**Comment by mbforbes** [comment]
@k8s-bot test this please

**Comment by alex-mohr** [comment]
ok to merge when/if tests seem sane.  oncall, feel free to remove the label and perhaps max can monitor and re-add when they pass?

**Comment by ixdy** [comment]
@mbforbes I think I've seen that failure a few times on the builds in the last day, though I'm not sure if there's a bug tracking it.

Might be a good idea for someone to look at the logs in https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/739cb2f526f15e7c82ef7c476a1458ad68b09fd1/kubernetes-pull-build-test-e2e-gce/2246/_artifacts/ and see if there's anything bug-worthy there.

**Comment by mbforbes** [comment]
My instinct is: "when in doubt, open a bug"

I can look Later&trade;

**Comment by rjnagal** [comment]
The failure looks unrelated to this change. @mbforbes merge this one and you file another issue for the failure?

**Comment by mbforbes** [comment]
@rjnagal sounds good; opening another issue for the above

**Comment by rjnagal** [comment]
restarting shippable to get rid of gendocs failure

**Comment by rjnagal** [comment]
all green, merging.

**Pull request merged**
