### PR TITLE
fix typos lable -> label

### PR DESCRIPTION
**Pull request by yeya24**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
fix a typo
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by AdamDang** [comment]
@yeya24 Thanks for your PR, Please fix all the same typo in this project. That would be more helpful. :)

**Comment by nikhita** [comment]
/assign @k82cn @msau42
for approval

**Pull request merged**
