### PR TITLE
Add multiple dns enteries if public ips are set.

### PR DESCRIPTION
**Pull request by vishvananda**
The automatic dns entries for services use the namespace in the
dns name:

guestbook.default.example.com

If a service has public ips set, it makes sense to use a round
robin and omit the domain name. For example, if there are two public
ips set, there will be two records for the above service:

0.guestbook.example.com
1.guestbook.example.com

guestbook.example.com will be a round robin to both of them.

### CODE REVIEW

**Comment by vishvananda** [comment]
Is this something you guys want to take?

**Comment by piosz** [comment]
Is this PR active? If not please close it according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/pull-requests.md

**Comment by vishvananda** [comment]
I am happy to update it but I was hoping to someone would comment on whether or not it is valuable. There is no point in rebasing if it isn't interesting to people.

**Comment by piosz** [comment]
@thockin could you please take a look or delegate?

**Comment by thockin** [comment]
Sorry, I lost track of this.

DNS is only served intra-cluster.  Can you explain the intent of having the external IPs be name-resolvable inside the cluster?

**Comment by vishvananda** [comment]
@thockin I'm using skydns to also serve dns outside the cluster. This allows external services and clients to discover the services as well. Since external IPs make the service available to external clients, it makes sense to also have a naming/discovery service.

**Comment by thockin** [comment]
The DNS server we deploy today isn't up to the task of serving internal and
external DNS.  We'd need split-horizon or at least different base domains
to serve internal/external.

Integrating with DNS outside of the cluster is on plan, but I don't think
this is the way.

Also, kube2sky has been largely rewritten.  Also the DNS schema is being
retooled right now.  Also public IPs is hopefully getting overhauled. :)

I'd like to come back to this after 1.0 and think about integration to
address this problem.  In the meantime, I think this PR is a dead end
unfortunately.

**Comment by vishvananda** [comment]
Fair enough. Will close then. Thanks.

**Pull request closed without merging**
