### PR TITLE
Automated cherry pick of #53234

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #53234 on release-1.8.

#53234: Fixes a flakiness in GPUDevicePlugin e2e test. Waits till

### CODE REVIEW

**Comment by vishh** [comment]
/approve
/lgtm

Thanks @dims

**Comment by mindprince** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/53353/files is merged. I think we should combine its change in here as well.

/cc @jiayingz

**Comment by vishh** [comment]
Closing and re-open because one of the tests is stuck

**Comment by dims** [comment]
/retest

Thanks @vishh

**Pull request merged**
