### PR TITLE
kubeadm: Make kube-proxy RollingUpgradeable

### LINKED ISSUE #319: The kube-proxy DaemonSet spec should be rolling-upgradeable
There is not much else to say, let's take advantage of cool features :)
Also will make things easier when upgrading
cc @pipejakob

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
Sets the right updateStrategy for kube-proxy.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes: https://github.com/kubernetes/kubeadm/issues/319

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@pipejakob @timothysc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by luxas** [comment]
/approve no-issue
Pretty straightforward

**Comment by luxas** [comment]
@timothysc @pipejakob should this be a non-blocking cherrypick candidate for easier upgrading from v1.7.x to v1.7.y and v1.7.x to v1.8.x?

**Review by dmmcquay — APPROVED** [review]

**Comment by luxas** [comment]
Oops, sorry @dmmcquay seems like I unassigned you and Luke unintentionally from Github's UI...
Race condition between me and the bot I suppose...

**Comment by timothysc** [comment]
> should this be a non-blocking cherrypick candidate for easier upgrading from v1.7.x 

Yes

/lgtm

**Comment by luxas** [comment]
I'm letting this merge now to master, then we'll see about the cherrypick based on a decision from @kubernetes/kubernetes-release-managers

**Comment by luxas** [comment]
I'm not sure why the `cncf-cla` bot stopped reacting to new PRs some time yesterday...

**Comment by caesarxuchao** [comment]
It looks safe to me to be cherrypicked.

cc @dchen1107

**Pull request merged**
