### PR TITLE
 fix typos in interfaces.go

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
 make code kinda more readable

```release-note
 NONE
```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
Nice catch, thanks for the fix! :smile: 

/lgtm

**Comment by AllenZMC** [comment]
Needs approved label @odinuge

**Comment by odinuge** [comment]
Hi @AllenZMC! :smile: 

As the @k8s-ci-robot said in the commont above:

> Needs approval from an approver in each of these files:
>  [staging/src/k8s.io/apiserver/pkg/authorization/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authorization/OWNERS)

I am not an approver, so you will have to wait for some of them to approve the change. `deads2k` is already assigned, so he will probably take a look at it when he has time. Hopefully that makes it a bit clearer. :+1: 

More info can be found here: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process

**Comment by logicalhan** [comment]
This file isn't currently being linted because it is marked as an exception in our [lint-exceptions file](https://github.com/kubernetes/kubernetes/blob/release-1.15/hack/.golint_failures#L454). Would you mind deleting that line from that golint_failures file and cleanup the the remaining failures? Otherwise, we're not really prevented from things like this recurring in this file.

**Comment by AllenZMC** [comment]
Who can assign `approved ` label?

**Comment by alejandrox1** [comment]
Hi @AllenZMC , thank you for the catch!
@logicalhan is the one here who can approve this PR.

The recommendation by @logicalhan was to delete the following line in [/hack/.golint_failures](https://github.com/kubernetes/kubernetes/blob/release-1.15/hack/.golint_failures#L454).
However, running [./hack/verify-golint.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-golint.sh) without it will result in the following error:

```
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:73:6: exported type AuthorizerFunc should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:73:6: type name will be used as authorizer.AuthorizerFunc by other packages, and that stutters; consider calling this Func
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:75:1: exported method AuthorizerFunc.Authorize should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:104:1: exported method AttributesRecord.GetUser should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:108:1: exported method AttributesRecord.GetVerb should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:112:1: exported method AttributesRecord.IsReadOnly should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:116:1: exported method AttributesRecord.GetNamespace should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:120:1: exported method AttributesRecord.GetResource should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:124:1: exported method AttributesRecord.GetSubresource should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:128:1: exported method AttributesRecord.GetName should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:132:1: exported method AttributesRecord.GetAPIGroup should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:136:1: exported method AttributesRecord.GetAPIVersion should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:140:1: exported method AttributesRecord.IsResourceRequest should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:144:1: exported method AttributesRecord.GetPath should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:148:6: exported type Decision should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:155:2: comment on exported const DecisionNoOpinion should be of the form "DecisionNoOpinion ..."
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:19:6: exported type ResourceRuleInfo should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:38:1: exported method DefaultResourceRuleInfo.GetVerbs should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:42:1: exported method DefaultResourceRuleInfo.GetAPIGroups should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:46:1: exported method DefaultResourceRuleInfo.GetResources should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:50:1: exported method DefaultResourceRuleInfo.GetResourceNames should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:54:6: exported type NonResourceRuleInfo should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:67:1: exported method DefaultNonResourceRuleInfo.GetVerbs should have comment or be unexported
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go:71:1: exported method DefaultNonResourceRuleInfo.GetNonResourceURLs should have comment or be unexported
```

A lot of these errors can be fixed by adding comments to exported methods but the following requires more thought and some refactoring throughout k/k:
* type name will be used as authorizer.AuthorizerFunc by other packages, and that stutters; consider calling this Func

This is called in the following places:
```
staging/src/k8s.io/apiserver/pkg/authorization/path/path.go:49:	return authorizer.AuthorizerFunc(func(a authorizer.Attributes) (authorizer.Decision, string, error) {
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:73:type AuthorizerFunc func(a Attributes) (Decision, string, error)
staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go:75:func (f AuthorizerFunc) Authorize(a Attributes) (Decision, string, error) {
pkg/registry/rbac/clusterrole/policybased/storage_test.go:61:	fakeAuthorizer := authorizer.AuthorizerFunc(func(attr authorizer.Attributes) (authorizer.Decision, string, error) {
pkg/registry/rbac/role/policybased/storage_test.go:63:	fakeAuthorizer := authorizer.AuthorizerFunc(func(attr authorizer.Attributes) (authorizer.Decision, string, error) {
test/integration/serviceaccount/service_account_test.go:408:	authorizer := authorizer.AuthorizerFunc(func(attrs authorizer.Attributes) (authorizer.Decision, string, error) {
```

@logicalhan could we approve this PR and tackle the golint fixes in a following PR?

**Comment by alejandrox1** [comment]
ping @logicalhan is there anyway we could get this in an put off fixing the golint errors for another PR? 

/priority backlog
/milestone v1.17

**Comment by kikisdeliveryservice** [comment]
Bug Triage Release Team checking in. Code freeze for the 1.17 release is on November 18. Is this still intended for 1.17? Thanks!

**Comment by alejandrox1** [comment]
@logicalhan @liggitt could you take a look at this one please?

**Comment by kikisdeliveryservice** [comment]
Following up: is this still intended for 1.17 or can it be bumped to 1.18?

-Bug Triage Team

**Comment by kikisdeliveryservice** [comment]
As a reminder, code freeze is tomorrow Nov 14th, 2019.

**Comment by liggitt** [comment]
if we're going to fix lint errors, fix as many as reasonably possible (leave alone the one that requires renaming the widely used type)

/milestone v1.18

**Pull request closed without merging**
