### PR TITLE
remove unused code when build garbageCollector

### PR DESCRIPTION
**Pull request by colin404**
Change-Id: Ib0474a8da6b250315fd400fb30b6a0a8c4e8ace4

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

It is better to remove unsed code to avoide confuse.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/ok-to-test
/release-note-none
look like a remnant from implementing SVM in tree.
/assign @jpbetz

**Comment by Jefftree** [comment]
Please fix the unused import error, thanks!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by Jefftree** [comment]
@thockin There was an unused import error causing the CI to fail before: https://github.com/kubernetes/kubernetes/pull/125814#issuecomment-2207140205. @colin404 hasn't responded in a while, I've created https://github.com/kubernetes/kubernetes/pull/128277 to fix it.

**Pull request closed without merging**
