### PR TITLE
Remove duplicate nodeSelector for kube-dns

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Remove duplicate nodeSelector for kube-dns

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by MrHohn — COMMENTED** [review]
Thanks! Could you do the same for kube-dns.yaml.base?

**Comment by heqg** [comment]
pull-kubernetes-e2e-kind-ipv6

**Comment by heqg** [comment]
> Thanks! Could you do the same for kube-dns.yaml.base?

OK. Thanks! 
Previously, I have missed it.
I will add an pr for kube-dns.yaml.base. and please help to review it.thks. the pr address as shown below:: https://github.com/kubernetes/kubernetes/pull/97666

**Comment by MrHohn** [comment]
> > Thanks! Could you do the same for kube-dns.yaml.base?
> 
> 
> 
> OK. Thanks! 
> 
> Previously, I have missed it.
> 
> I will add an pr for kube-dns.yaml.base. and please help to review it.thks. the pr address as shown below:: https://github.com/kubernetes/kubernetes/pull/97666

Could you re-push the commit to include that change instead of using a new PR? Since they are essentially toward the same goal. Thanks!

**Comment by heqg** [comment]
> > > Thanks! Could you do the same for kube-dns.yaml.base?
> > 
> > 
> > OK. Thanks!
> > Previously, I have missed it.
> > I will add an pr for kube-dns.yaml.base. and please help to review it.thks. the pr address as shown below:: #97666
> 
> Could you re-push the commit to include that change instead of using a new PR? Since they are essentially toward the same goal. Thanks!


previously, due to my operation problem, I was afraid that in the same PR will have two commits, so I submitted another PR.
Currently, another PR has been merged. Can we accept this pr first?  thanks very much.
Then,In the following time, For similar problems,I will pay attention next time. I'm very sorry.

**Comment by MrHohn** [comment]
@heqg No worries, approving this since the other one has been merged. (FWIW for multiple commits, you could squash the fixup commits so the history would be cleaner.)

/lgtm
/approve

**Pull request merged**
