### PR TITLE
Fix client for version

### LINKED ISSUE #3919: kubectl ClientForVersion ignores resource mapping
I stumbled across this while experimenting with kubeconfig load order/merging. There are various helpers constructed from a Factory that use [clients.ClientForVersion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L348), however this always uses the same default ClientConfig because [ClientConfigForVersion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L325) doesn't use the passed in version param:
```go
// ClientConfigForVersion returns the correct config for a server (version never used?)
func (c *clientCache) ClientConfigForVersion(version string) (*client.Config, error) {
	if c.defaultConfig == nil {
		config, err := c.loader.ClientConfig()
		if err != nil {
			return nil, err
		}
		c.defaultConfig = config

		if c.matchVersion {
			if err := client.MatchesServerVersion(config); err != nil {
				return nil, err
			}
		}
	}

	// TODO: have a better config copy method
	config := *c.defaultConfig
	client.SetKubernetesDefaults(&config)
	return &config, nil
}
```
Am I missing something or is this a bug?

/cc @smarterclayton, @deads2k

### PR DESCRIPTION
**Pull request by j3ffml**
Make ClientConfigForVersion actually set the provided version. Closes #3919 

/cc @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can you add a test to prove the bug fix?  We probably don't have enough factory tests

**Comment by jlowdermilk** [comment]
Working on tests now.

**Comment by jlowdermilk** [comment]
Added a test. In the process discovered some cruft to cleanup in the factory. PTAL

**Comment by smarterclayton** [comment]
Looks like something is broke in hack/test-cmd.sh - there's a test in there that validates default version behavior (and maybe that's broken now?)

**Comment by jlowdermilk** [comment]
hack/test-cmd.sh was a legit failure (forcing config version to "" instead of defaulting). I undid the removal of cmd params in factory methods. A test or TODO would be good there, so the next person digging through doesn't mistake it for cruft :)
PTAL

**Comment by smarterclayton** [comment]
Yeah, I have not done a good job of that.  @deads2k you and I need to do a pass through all this code and make sure we document / put tests in place documenting why some things are abstracted.

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
