### PR TITLE
[Federation] Fix removing kube-dns configmap during cluster unjoin

### PR DESCRIPTION
**Pull request by shashidharatd**
Fixes: #42836 

cc @madhusudancs @kubernetes/sig-federation-bugs

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot kops aws e2e test this

**Comment by madhusudancs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[federation/pkg/kubefed/unjoin.go, line 193 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42838#-KeqIvErPcXUb-6y45ny:-KeqIvEsvDW2GjaJQYg7:b-fi5644) ([raw file](https://github.com/kubernetes/kubernetes/blob/f27f9fd8cfe02633665f9c3934a1143a8bb6ba4e/federation/pkg/kubefed/unjoin.go#L193)):*
> ```Go
> 		configMap.Data[util.FedDomainMapKey] = newFedMapValue
> 	} else {
> 		delete(configMap.Data, util.FedDomainMapKey)
> ```

At this point, it really doesn't matter whether `configMap.Data[util.FedDomainMapKey]` exists or is an empty string. You could always set `configMap.Data[util.FedDomainMapKey] = newFedMapValue` and completely get rid of this if-else logic.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42838)*

**Comment by shashidharatd** [comment]
@madhusudancs, Fixed. PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[federation/pkg/kubefed/unjoin.go, line 193 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42838#-KeqIvErPcXUb-6y45ny:-KerDMRG3uKrIa6au5MJ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/f27f9fd8cfe02633665f9c3934a1143a8bb6ba4e/federation/pkg/kubefed/unjoin.go#L193)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

At this point, it really doesn't matter whether `configMap.Data[util.FedDomainMapKey]` exists or is an empty string. You could always set `configMap.Data[util.FedDomainMapKey] = newFedMapValue` and completely get rid of this if-else logic.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42838#-:-KerDP7nDLfEIIHq2PGA:bhyzkv8)*

**Comment by madhusudancs** [comment]
/lgtm
/approve

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42838#-:-KerGzK0Kn1ZGGNNvWXt:b6yv7yi)*

**Comment by shashidharatd** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
