### PR TITLE
tidy up DeleteOptions description

### PR DESCRIPTION
**Pull request by dankenigsberg**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Drop a confusing repetition from the description of `GracePeriodSeconds` delete option. The dropped sentence repeats the content of the two sentences before it.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
/remove-lifecycle stale

@davidopp @soltysh anyone cares to review this tiny doc cleanup?

**Comment by DangerOnTheRanger** [comment]
/test pull-kubernetes-e2e-kind

(the e2e-kind failure looks like a potential test flake to me)

**Comment by dankenigsberg** [comment]
@DangerOnTheRanger  I believe that I'm finally done. Do I now need to ping so many approvers for what is basically a one-liner?

**Comment by DangerOnTheRanger** [comment]
@dankenigsberg `DeleteOptions` is referenced in quite a few places, so the resulting diff is relatively large, unfortunately.

**Comment by ritazh** [comment]
/remove-sig auth
Feel free to add us back if needed.

**Pull request closed without merging**
