### PR TITLE
Use cos-stable-59-9460-64-0 instead of cos-beta-59-9460-20-0.

### PR DESCRIPTION
**Pull request by rohitagarwal003**
Remove dead code that has now moved to another repo as part of #47467

**Release note**:
```release-note
NONE
```

/sig node

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot ok to test

**Comment by dchen1107** [comment]
cc/ @abgworrall Adam has a pending pr to upgrade cos image to another minor version. Can we collaborate together to include all required fixes? 

I am leaving @abgworrall to make the final call here.

**Comment by abgworrall** [comment]
Oops, yes - I have https://github.com/kubernetes/kubernetes/pull/47670 on the go, for cos-stable-59-9460-64-0. It contains an important fix for ipaliasing that @bowei is waiting on. Can we get that merged instead ? (It's failing tests right now, but I aim to get it sorted out by end of day ...)

**Comment by mindprince** [comment]
@abgworrall I can update this PR to use `cos-stable-59-9460-64-0`.

**Comment by mindprince** [comment]
Updated to include #47670

**Comment by abgworrall** [comment]
@bowei , this is now the PR that should precede your tests getting re-enabled.

**Comment by mindprince** [comment]
@abgworrall  Can you add milestone 1.7 to this, so that this gets merged.

**Comment by abgworrall** [comment]
I'm not in kubernetes org either, so I can't help :/

**Comment by dchen1107** [comment]
/lgtm

Ok, I changed my mind. I discussed with @abgworrall earlier to wait for Monday morning to merge this pr since it changes the default COS image which most tests are running on, and there are many pending pr waiting for being merged. But I looked at the testgrid which @abgworrall ran with, cos-stable-59-9460-64-0 looks pretty good. Thanks!

**Pull request merged**
