### PR TITLE
Support local SSDs for GKE and GCE nodes.

### PR DESCRIPTION
**Pull request by vulpecula**
``` release-note
Support local SSDs for GKE and GCE nodes.
```

### CODE REVIEW

**Comment by thockin** [comment]
Does this warrant a release note?  Please adjust the release-note labels and maybe title (which becomes the relnote)

**Comment by fabioy** [comment]
Readding lgtm (release note resolved).

**Comment by fabioy** [comment]
Would like to have this considered to be cherrypicked into the next 1.2.x release.

**Comment by fabioy** [comment]
@k8s-bot test this

**Comment by fabioy** [comment]
@k8s-bot test this issue: #24508

**Comment by andyzheng0831** [comment]
@vulpecula, I will make a change to support this in GCI image. How did you create local SSD to test the change?

**Comment by roberthbailey** [comment]
Removing the cherry pick candidate label, since we are just going to wait for the upcoming 1.3 release.

**Comment by andyzheng0831** [comment]
@vulpecula I asked the question "How did you test it" one month ago, but there is no response. I am making GCI side change. To be safe, I will follow the same way to test it.

cc/ @roberthbailey @fabioy

**Pull request merged**
