### PR TITLE
Clean up kubeadm.

### PR DESCRIPTION
**Pull request by bjhaid**
These are based on recommendation from
[staticcheck](http://staticcheck.io/).

- Remove unused struct fields
- Remove unused function
- Remove unused variables
- Remove unused constants.
- Miscellaneous cleanups

/kind cleanup
/priority backlog

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @bjhaid 
/ok-to-test

**Review by neolit123 — COMMENTED** [review]
thanks for the cleanups @bjhaid 
these seem good to me.
/approve

**Review by yagonobre — COMMENTED** [review]
/lgtm

**Comment by luxas** [comment]
Thanks!

**Pull request merged**
