### PR TITLE
[Depends on 19776] AWS: Reuse more GCE kube-up infrastructure

### PR DESCRIPTION
**Pull request by justinsb**
This continues on from #19776, and probably it is much easier to review that PR first.

We are able to reuse the GCE scripts to remove a huge amount of AWS kube-up code.  Moreover, because kube-up is now much closer to how GCE works, we can now more easily implement kube-push and upgrade.

Important points:
- There is a 16KB metadata limit on AWS.  So we upload just the settings as metadata, along with a brief `wget | sh` of the configure-vm.sh script.  That script is uploaded alongside kubernetes.tar.gz.  We have to gzip the user data to fit under the 16KB limit (cloud-init handles this automatically)
- We currently reuse GCE's configure-vm.sh script, primarily using nasty sed tricks to remove blocks of code between `#+GCE` and `#-GCE`.  I would like to change GCE kube-up also to build configure-vm dynamically, combining common code with provider-specific code as the AWS code does.  I guess I could also just override the functions, but this might be confusing.  Or maybe not?
- This also switches AWS to operate in local-salt mode on the nodes (i.e. the same as GCE)

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by justinsb** [comment]
@k8s-bot test this

Flake:
```
Kubernetes cluster is running.  The master is running at:

  https://104.197.184.109

The user name and password to use is located in /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/.kube/config.

... calling validate-cluster
Waiting for 6 ready nodes. 1 ready nodes, 1 registered. Retrying.
Found 6 node(s).
NAME                              LABELS                                                                                                                                                               STATUS     AGE
e2e-gce-builder-2-1-minion-5h9b   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-5h9b   NotReady   15s
e2e-gce-builder-2-1-minion-835a   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-835a   NotReady   16s
e2e-gce-builder-2-1-minion-8o08   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-8o08   NotReady   14s
e2e-gce-builder-2-1-minion-e278   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-e278   NotReady   14s
e2e-gce-builder-2-1-minion-tlb6   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-tlb6   NotReady   15s
e2e-gce-builder-2-1-minion-x8jn   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/hostname=e2e-gce-builder-2-1-minion-x8jn   NotReady   15s
Validate output:
Unable to connect to the server: dial tcp 104.197.184.109:443: i/o timeout
2016/01/20 17:26:58 e2e.go:309: Error running up: exit status 1
2016/01/20 17:26:58 e2e.go:305: Step 'up' finished in 5m41.800168596s
2016/01/20 17:26:58 e2e.go:141: Error starting e2e cluster. Aborting.
exit status 1
```

**Comment by justinsb** [comment]
Will also retest manually; I do mess with the configuration here (though the API server did come up to answer the `kubectl get nodes` query, but then the next request timed out)

**Comment by justinsb** [comment]
I broke this down into a series of smaller PRs, so closing this one.

**Pull request closed without merging**
