### PR TITLE
Update to latest golang.org/x/oauth2 v0.20.0

### PR DESCRIPTION
**Pull request by dims**
/kind cleanup

latest x/oauth2 drops from unnecessary dependencies in https://github.com/golang/oauth2/commit/3a6776ada799d857cee190d6f517c4afee7c3170 !! ( thanks @liggitt )

https://github.com/golang/oauth2/compare/v0.18.0...v0.20.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

Dims, you are racking up some huge negative LOC numbers :)

**Comment by dims** [comment]
@thockin :) the series of things so far was started a while ago and reflects work by many many folks over time. we still have a big laundry list to get through documented in `hack/unwanted-dependencies.json` unfortunately.  I will take all the wins we can get for sure to get smaller, sustainable, secure etc.. !

**Pull request merged**
