### PR TITLE
Bugfix: Update AddNodeHandler error logs

### PR DESCRIPTION
**Pull request by hardikdr**
**What this PR does / why we need it**: Its simple error log fix. Hope its not too small to be a separate PR.

### CODE REVIEW

**Comment by HardikDR** [comment]
test

**Comment by HardikDR** [comment]
cla test

**Comment by CaoShuFeng** [comment]
Pelease replay: "/release-node-none", to remove the "do-not-merge/release-note-label-needed" label

**Comment by cblecker** [comment]
ping @gmarek

**Comment by HardikDR** [comment]
It's stuck on "Milestone is for a future release and cannot be merged" .
Can anyone help ?

**Comment by CaoShuFeng** [comment]
It's k8s 1.9 release time.
Only necessary changes can be merged now.
This can be merged after 1.9 version.
We should just wait.
:)

**Comment by HardikDR** [comment]
Ah ok, thanks @CaoShuFeng  :)

**Pull request merged**
