### PR TITLE
fix grammar error: the predicate verb should be singular.

### PR DESCRIPTION
**Pull request by liangwenguo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liangwenguo** [comment]
@ liztio @stealthybox can you review mr pr?

**Comment by liztio** [comment]
you're making the verb singular, not in the third person, but it's still correct!

/lgtm

**Comment by nikhita** [comment]
/assign @fabriziopandini 
for approval

**Comment by nikhita** [comment]
@liangwenguo I wouldn't bother retesting for sometime now, the kops test is completely red...

**Comment by liangwenguo** [comment]
@nikhita yep

**Pull request merged**
