### PR TITLE
Move KubeProxy test to GKE_FLAKY

### PR DESCRIPTION
**Pull request by gmarek**
cc @ixdy @mikedanese 

Ref #17781

### CODE REVIEW

**Comment by gmarek** [comment]
@roberthbailey @a-robinson - please note a TODO for creating a project for this suite.

**Comment by wojtek-t** [comment]
LGTM

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by fgrzadkowski** [comment]
Merging this to unblock submit queue. There is a P0 bug assigned to @thockin for further investigation.

**Comment by gmarek** [comment]
FYI: this test was running in GKE-ci suite (which was blocking merge bot) and GCE-slow suite (which was not blocking merge bot). It's a strange situation, so moving it to 'gke-flaky' make this test non-blocking. Other way to go was to add slow suite to blocker.

**Comment by roberthbailey** [comment]
FYI, the gke-flaky suite that you created last week looks like it has never passed. Next time we bump a test out of the main suite because it's flaky we should make sure that the test is passing (at least some of the time) in the new test suite.

**Comment by roberthbailey** [comment]
@wojtek-t / @fgrzadkowski: can you cross-link the P0 issue that was opened to fix this test?

**Comment by wojtek-t** [comment]
@roberthbailey - the issue is: https://github.com/kubernetes/kubernetes/issues/17781

**Comment by gmarek** [comment]
@roberthbailey - sorry for that. It was passing after I created the suite.

**Pull request merged**
