### PR TITLE
Automated cherry pick of #101592: chunk target operatation for aws targetGroup

### PR DESCRIPTION
**Pull request by melnikalex**
Cherry pick of #101592 on release-1.21.

#101592: chunk target operatation for aws targetGroup

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by cpanato** [comment]
@M00nF1sh @pacoxu can you review this PR as well you did a review for the CP for another branch (https://github.com/kubernetes/kubernetes/pull/101814)

**Review by andrewsykim — COMMENTED** [review]
/approve

**Comment by puerco** [comment]
/lgtm
Thanks!

**Pull request merged**
