### PR TITLE
staging/publishing: add release-1.25 branch

### PR DESCRIPTION
**Pull request by jeremyrickard**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Adds publishing config for new 1.25 release branch after RC.0 cut yesterday

#### Special notes for your reviewer:

See this [slack thread](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1660057694134999) for more context

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

cc: @soltysh @dims @Verolop @puerco

### CODE REVIEW

**Comment by dims** [comment]
verified locally using `./hack/verify-publishing-bot.py`

/approve
/lgtm

**Comment by dims** [comment]
/hold

(may have spotted something fishy)

**Comment by dims** [comment]
@jeremyrickard missed a spot!

```
[dims@dims-m1-7728 10:51] ~/go/src/k8s.io/kubernetes ⟩ git diff
diff --git staging/publishing/rules.yaml staging/publishing/rules.yaml
index 20886071d74a..9bdbd7f7be3f 100644
--- staging/publishing/rules.yaml
+++ staging/publishing/rules.yaml
@@ -20,6 +20,11 @@ rules:
     source:
       branch: release-1.24
       dir: staging/src/k8s.io/code-generator
+  - name: release-1.25
+    go: 1.18.5
+    source:
+      branch: release-1.25
+      dir: staging/src/k8s.io/code-generator
 - destination: apimachinery
   branches:
   - name: master
```

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
