### PR TITLE
Revert "Deflake startupProbe e2e test"

### PR DESCRIPTION
**Pull request by aojea**
This reverts commit bcd582030fdb1e3a5ac74c7b01a99fbfd9069a68.

The only evidence I have is that the test started to flake much more since the day this merged  https://github.com/kubernetes/kubernetes/pull/99998 , but it seems the more logical reason

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-e2e-kind&test=immediately%20after%20startupProbe%20succeeds
image

/kind failing-test
/kind flake
```release-note
NONE
```

### CODE REVIEW

**Comment by matthyx** [comment]
Please go ahead, I'm working on a better fix, but it won't be quite ready until Monday.
Thanks for handling it.
/cc @SergeyKanzhelev

**Comment by dims** [comment]
/approve
/lgtm

Cc @SergeyKanzhelev

**Comment by ehashman** [comment]
Thanks @aojea !

**Pull request merged**
