### PR TITLE
Set user info in CertificateSigningRequest.Spec on create

### LINKED ISSUE #30239: certificatesigningrequests should overwrite spec.user info in createstrategy
The API server should overwrite the info in the spec with the info from the context, not allow it to be set by end users

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #30239

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30246)

### CODE REVIEW

**Comment by liggitt** [comment]
@mikedanese PTAL

**Comment by mikedanese** [comment]
@yifan-gu I think this will affect the kubelet tls bootstrap PR.

**Comment by mikedanese** [comment]
this change SGTM. @liggitt @gtank WDYT about changing Username to RequestingUser in the CSR Spec (not in this PR but in a followup)?

cc @kubernetes/sig-api-machinery since we are plumbing context into new places in the registry. Seems reasonable.

**Comment by smarterclayton** [comment]
Passing context into strategy is reasonable to me, although we want to
be careful to prevent abuse in the future (prepare is intended only
for local transformations).

**Comment by gtank** [comment]
@mikedanese That sounds fine to me. It will clarify what the field means.

**Comment by gtank** [comment]
@liggitt Why all the plumbing to move this into PrepareForCreate instead of the storage method I was previously using?

**Comment by liggitt** [comment]
@gtank that storage method isn't called from the API, only the REST handler funcs and the strategy methods are

**Comment by liggitt** [comment]
any other comments?

**Pull request merged**
