### PR TITLE
Fixing address locking in CP fake.

### PR DESCRIPTION
**Pull request by cheftako**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Follow on to https://github.com/kubernetes/kubernetes/pull/65226.
Makes the use of address lock to protect the address field consistent.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/approve

**Comment by andrewsykim** [comment]
Wouldn't be a problem in the first place if we were out-of-tree 😉 

/approve

**Pull request merged**
