### PR TITLE
[WIP] upgrade to ginkgo V2

### PR DESCRIPTION
**Pull request by aojea**
Ref: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta

Test the new features:
```
Serial Decoration
Specs can now be labelled with the Serial decoration. Specs labelled as Serial will never run in parallel with other specs. Instead, Ginkgo will run them on a single test process after all the parallel tests have finished running.

Ordered Decoration
Spec containers (i.e. Describe and Context blocks) can now be labelled with the Ordered decoration. Specs within Ordered containers will always run in the order they appear and will never be randomized. In addition, when running in parallel, specs in an Ordered containers will always run on the same process to ensure spec order is preserved. When a spec in an Ordered container fails, all subsquent specs in the container are skipped.
```

### CODE REVIEW

**Comment by onsi** [comment]
Couple of quick thoughts/questions:

- Ginkgo v2 won't currently let you change the config as is done [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L105-L107).  I'm adding that to the backlog and will cut a new release that will allow you to provide mutated config to `RunSpecs`.

- The [testDetails](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/reporters/testDetails.go) reporter instantiated [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L126-L128) won't be necessary any more as `ginkgo -json-report=report.json` will now take care of generating a JSON formatted report for you.  Note that the JSON format will be different in V2 vs V1 and will include much more detail.
- Similarly you won't need to create your own JUnit reporter (as done [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L111-L119)) - instead `ginkgo --junit-report=report.junit` will generate a JUnit report.  More details [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#generating-machine-readable-reports).
- The [progress](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/reporters/progress.go) reporter is different and a bit trickier.  The new reporting infrastructure doesn't implement `ReportBeforeSuite` which will be necessary to get the total number of tests into a reporter before the tests start.  I can add that but I want to understand what problem the progress reporter is solving first.  Also - as currently written the progress reporter might have some weird behavior when running in parallel as each parallel process will have its own count of failures.

Lastly, I'm not sure how the [ginkgowrapper](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/ginkgowrapper/wrapper.go) library is being used.  All the context being captured by the custom fail handler is captured by Ginkgo and will be part of the JSON reported listed earlier.  If the goal is to emit full stack traces you can use `ginkgo --trace` to get the stack traces emitted by the default reporter.

**Comment by aojea** [comment]
/cc @spiffxp 
Aaron you have more historical context on the e2e framework than me, can you PTAL to last comment?

**Comment by onsi** [comment]
Gentle nudge on this - I'm nearing the finish line on 2.0 and would love to help land the plane on this PR.

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Pull request closed without merging**
