### PR TITLE
E2E & Node E2E: Migrate e2e test into shared directory

### PR DESCRIPTION
**Pull request by Random-Liu**
For https://github.com/kubernetes/kubernetes/issues/29081.
Based on https://github.com/kubernetes/kubernetes/pull/29092.

The first commit is from https://github.com/kubernetes/kubernetes/pull/29092, and the other 6 commits are new.

The first 3 commits of the PR refactored the test framework to prepare for test migration.
The last 3 commits migrate several test into shared directory, including:
- downwardapi_volume.go
- empty_dir.go
- configmap.go
- docker_containers.go
- downward_api.go
- expansion.go
- secrets.go
- pods.go

After this PR, we'll have **92 Specs** totally, **86** of them are non-slow and non-flaky.

I've tested in my desktop. With parallel option on, running all non-slow, non-flaky test took **573.072 seconds**. The pull request node e2e of this PR takes **524.398 seconds**.

There are some other tests could not be shared for now.
Mostly because they are using `kubectl exec`, I'll add exec util into the framework and move those test into shared directory in following PRs.

@vishh @timstclair 
/cc @kubernetes/sig-node

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/29473.

**Comment by Random-Liu** [comment]
Seems like image pulling flake.

@k8s-bot test this issue #IGNORE.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/29633.

**Comment by vishh** [comment]
@Random-Liu  This PR is huge. Can you break it down into several small ones? Ideally each commit of yours could be a separate PR

**Comment by Random-Liu** [comment]
@vishh Sure. Will do that.

**Comment by Random-Liu** [comment]
Close this one. I'll split the PR into several small PRs to help review.
The first one is here #29806. PTAL~ :)

**Pull request closed without merging**
