### PR TITLE
Rearrange glusterfs artifacts to own directory.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs @jsafrane PTAL

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@jsafrane do u have the permission to remove 'releasenote-label-needed' flag?

**Comment by jsafrane** [comment]
Yes, I have, but it's your job. Either fill the release note into the initial comment (see https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md, epecially ` ```release-note` section there) or use /release-note-none

**Comment by humblec** [comment]
@jsafrane Apologies. sure.  I will keep it in mind.

**Comment by jsafrane** [comment]
@humblec thanks!

**Comment by humblec** [comment]
@jsafrane Can you please approve this PR ?

**Comment by jsafrane** [comment]
No, I can't. See examples/OWNERS

**Comment by humblec** [comment]
Thanks @thockin & @jsafrane  !

**Pull request merged**
