### PR TITLE
add roycaihw to reviewers in apiextensions-apiserver

### PR DESCRIPTION
**Pull request by roycaihw**
Add myself to reviewers in apiextensions-apiserver

/sig api-machinery
/cc @sttts @lavalamp 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
👍🏻LGTM!

**Comment by lavalamp** [comment]
/reopen

this just needs a rebase

**Comment by roycaihw** [comment]
/remove-lifecycle rotten

rebased, please take a look @lavalamp

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
