### PR TITLE
getEquivalenceClassInfo no longer exists ,delete from comment

### PR DESCRIPTION
**Pull request by zhangmingld**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:
The func getEquivalenceClassInfo is not used , delete it from the comment 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by resouer — APPROVED** [review]
/lgtm

Thanks for clean up

**Comment by zhangmingld** [comment]
/assign @k82cn it seems the label had something wrong....
Could you help me relabel it ? Thaknyou

**Comment by misterikkit** [comment]
/assign @k82cn 
looks like this needs re-approve.

**Comment by misterikkit** [comment]
@zhangmingld should be easy to merge this after a rebase. :smiley:

**Comment by zhangmingld** [comment]
> @zhangmingld should be easy to merge this after a rebase.

ok, i will commit later , a little busy this month

**Comment by zhangmingld** [comment]
it seems that we don`t need the code in this pr ,close

**Pull request closed without merging**
