### PR TITLE
code cleanup in discovery client

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by thockin** [comment]
@caesarxuchao please get in thehabit of approving when approval is your domain :)

/approve no-issue

**Pull request merged**
