### PR TITLE
generate ReportingInstance and ReportingController in Event

### LINKED ISSUE #116444: events.k8s.io/v1 api does not have changes in place mentioned in the Deprecated API Migration Guide
### What happened?

From the Deprecated API Migration Guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/,  since v1.19, the events.k8s.io/v1 has been using the new reportingController and reportingInstance to replace the decrecated source.component and source.host. But when I checked the Kube events in a cluster with version 1.26.0, those new fields are empty and the supposed to be deprecated fields have not been renamed.

### What did you expect to happen?

Seeing the values in the new fields like reportingController and reportingInstance

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an Kubernetes cluster with version 1.26.0
2. Generate some Kube events
3. Check the Kube events details for the field of reportingController, reportingInstance, source.component, source.host

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-11T00:15:47Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
the reportingController and reportingInstance fields in the event do not have values, which is non-compliant with the Kubernetes API v1.25 specification. Further details can be found at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#event-v125

#### Which issue(s) this PR fixes:

Fixes #116444

#### Does this PR introduce a user-facing change?

```release-note
When retrieving event resources, the reportingController and reportingInstance fields in the event will contain values.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wanlonghenry** [comment]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/ The deprecation guide also mentioned the renames. Should that be fixed as well for now or we want to keep them that way?

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by HirazawaUi** [comment]
@logicalhan could you please help me retest

**Comment by HirazawaUi** [comment]
@dgrisonnet May you help this PR to LGTM again?

**Comment by HirazawaUi** [comment]
@dgrisonnet @dashpole @logicalhan Can we continue reviewing this PR?

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

(from sig inst)

**Comment by aritraghosh** [comment]
Will this be backported to prior Kubernetes versions before 1.28?

**Comment by HirazawaUi** [comment]
> Will this be backported to prior Kubernetes versions before 1.28?

as it should be

**Pull request merged**
