### PR TITLE
make --token-ttl 0 effect

### LINKED ISSUE #53637: kubeadm config "tokenTTL: 0s"  or "--token-ttl 0" config has no effect
**BUG REPORT**:

/kind bug

**What happened**:

When using `kubeadm` with a token generated by `kubeadm token generate` in advance, but also when letting kubeadm create the token, a `tokenTTL` configuration is ignored. The same is true when not using a config file but using `kubeadm init --token-ttl 0`

**What you expected to happen**:

I would expect when providing a tokenTTL of 0s that the token does not expire.

**How to reproduce it (as minimally and precisely as possible)**:

* Generate token

```
kubeadm generate token
0f6863.1e4e2878d4e591c3
```

* Create kubeadm.yml:

```yml
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
token: "0f6863.1e4e2878d4e591c3"
tokenTTL: "0s"
```

* Run kubeadm init:

```
kubeadm init --config kubeadm.yml
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.8.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [n0 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.23.200]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
[apiclient] All control plane components are healthy after 175.529072 seconds
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[markmaster] Will mark node n0 as master by adding a label and a taint
[markmaster] Master n0 tainted and labelled with key/value: node-role.kubernetes.io/master=""
[bootstraptoken] Using token: 0f6863.1e4e2878d4e591c3
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 0f6863.1e4e2878d4e591c3 192.168.23.200:6443 --discovery-token-ca-cert-hash sha256:62ce9d4ed917b015c7bb8bf781cad0a98f0eb1aa091bd633cb135f0a43b8ff0e
````

* Verify the token:

```
TOKEN                     TTL       EXPIRES                     USAGES                   DESCRIPTION                                                EXTRA GROUPS
0f6863.1e4e2878d4e591c3   23h       2017-10-11T09:40:03+02:00   authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token
```
As you can see, the expiry is set to the default of 24 hours.

------------

The same behaviour happens when you let `kubeadm` create the token by using a configuration without _token_ spec like in 

```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
tokenTTL: "0s"
```

------------

`kubeadm init --token-ttl 0` yields the same result.

**Environment**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v1.1.1"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.6.0"
```

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

there is two default function and one is redundant  

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53637

**Special notes for your reviewer**:

`cfg.TokenTTL.Duration`   the default value of this type  is 0 and when we use  --config flag, when we set tokenTTL zero or not set the value, the final value will be the `DefaultTokenDuration = 24 * time.Hour`, is it the design intention?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
cc @luxas Can you have a look at this? Thanks.

**Review by luxas — CHANGES_REQUESTED** [review]
This would break kubeadm to be honest. We need defaulting of the parameters.
Can you think of any other solution to detect this state and act accordingly?

**Comment by wackxu** [comment]
@luxas I think we already set the default value, it is duplicate. https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L106

**Comment by luxas** [comment]
> @luxas I think we already set the default value, it is duplicate. https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L106

That is expected and correct. It first defaults so that the right flag defaults are shown, then defaults again values that the user has submitted.

**Comment by jbeda** [comment]
@luxas You might know this code better than me, but I think that the proposed fix may work. 

If I'm reading the code right, the current flow looks like:
1. Start with uninitialized struct
2. Set defaults into it
3. Configure flags where the defaults for the flags is drawn from the struct
4. Parse flags for the command and potentially write defaults back into the struct
5. Re-apply defaults based on zero values.

I think since we are setting flag defaults based on defaults from struct we can eliminate step 5 and be good.

This is also a serious enough thing we should probably cherry pick it into the release.  There is no way to generate unlimited tokens otherwise.

/cc @mattmoyer

**Comment by wackxu** [comment]
@luxas @jbeda As we know, default value of the type `Duration` in golang is `0` and  we use `0` to indicate that the expire time of token is never, but the default function will cover the value of `0` to `24h`, remove the line 'legacyscheme.Scheme.Default(cfg)' can make ` --token-ttl 0` effect. But it is difficult to detect if user set the token-ttl in the config file, how we resolve it?

**Comment by ncdc** [comment]
If you have a field where you want 0 to mean 0, but you also want to have a non-0 default value if the field is unspecified, then said field **must** be a pointer, and you also must have a defaulting function that checks for `nil` and sets the default accordingly.

**Comment by mattmoyer** [comment]
@ncdc thanks for the tip. I'm working on implementing that strategy now.

**Comment by jbeda** [comment]
New related bug: https://github.com/kubernetes/kubeadm/issues/509

**Comment by mattmoyer** [comment]
@wackxu thanks for taking a shot at this! I think this approach only fixes the CLI flag but not the config file field.

I took a different approach here: https://github.com/kubernetes/kubernetes/pull/54640, please take a look.

**Review by mattmoyer — CHANGES_REQUESTED** [review]
@wackxu thanks for taking a shot at this! I think this approach only fixes the CLI flag but not the config file field.

I took a different approach here: https://github.com/kubernetes/kubernetes/pull/54640, please take a look.

**Comment by wackxu** [comment]
@mattmoyer That is a good job, thanks for your work  and I will close this PR.

**Pull request closed without merging**
