### PR TITLE
touch a file in build to trigger PR testing (release-1.8)

### PR DESCRIPTION
**Pull request by BenTheElder**
**What this PR does / why we need it**:  allows easy triggering of presubmits for testing

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #46662

**Special notes for your reviewer**: please ignore / leave open

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Go away milestone bot :-)

**Comment by ixdy** [comment]
unsubscribe

**Comment by jpbetz** [comment]
Is this PR still needed or can we close it?

**Comment by BenTheElder** [comment]
@jpbetz this is still needed, we still need to try test/infra configurations against 1.8 periodically until it's out of support (post 1.11 release IIRC)

**Comment by BenTheElder** [comment]
We've gotten by on 1.9 and up lately since they were pretty similar but things are starting to diverge more and we have some much bigger infra changes inbound (replacing the now somewhat gnarly bootstrapping script for one)

**Comment by jpbetz** [comment]
@BenTheElder Gotcha. Thanks for explaining.

**Comment by BenTheElder** [comment]
@cjwagner @marun is there a way to make the milestone bot stop spamming dummy PRs that have zero intention of ever being merged? :/

**Comment by cjwagner** [comment]
> is there a way to make the milestone bot stop spamming dummy PRs that have zero intention of ever being merged? :/

Not that I know of. Maybe just add a kind label to satisfy its requirements?
/kind friction
/shrug

**Comment by cjwagner** [comment]
oops, I can't read.
/remove-kind friction
/kind cleanup

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
a little bit longer fejta-bot

**Comment by jpbetz** [comment]
The release-1.8 branch has reached EOL.  Should we close this?

**Comment by BenTheElder** [comment]
We should EOL the test jobs and then close this @cjwagner @amwat

**Comment by BenTheElder** [comment]
We still need better policies about EOL, @spiffxp had some thoughts there.

**Comment by spiffxp** [comment]
I put my thoughts down here, for those following along at home https://github.com/kubernetes/sig-release/issues/244

**Comment by BenTheElder** [comment]
1.8 has been out of support / EOL for a while now.

**Pull request closed without merging**
