### PR TITLE
update google container api

### LINKED ISSUE #17433: Godeps/_workspace/src/google.golang.org/api/container/v1beta1 should be replaced with Godeps/_workspace/src/google.golang.org/api/container/v1
https://godoc.org/google.golang.org/api/container/v1beta1 returns Not found

@eparis

### PR DESCRIPTION
**Pull request by rootfs**
fix #17433

### CODE REVIEW

**Comment by lavalamp** [comment]
thanks!

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by brendandburns** [comment]
LGTM, according to @eparis you may need to update godep and then run:

```sh
godep restore; rm -rf Godeps; godep save ./...
```

**Comment by eparis** [comment]
I note this PR pulled in `Godeps/_workspace/src/google.golang.org/api/gensupport/json_test.go`  which means your godep binary is even more out of date...

**Comment by eparis** [comment]
Actually the travis failure it saying you have invalid/non-reproducable changes in all of the following!
```
google.golang.org/api/container/v1/container-api.json
google.golang.org/api/container/v1/container-gen.go
google.golang.org/api/gensupport/json.go
google.golang.org/api/gensupport/json_test.go
google.golang.org/api/gensupport/params.go
google.golang.org/api/googleapi/googleapi.go
google.golang.org/api/googleapi/types.go
```

How did you make this PR?

**Comment by rootfs** [comment]
@brendandburns your #17478  looks much concise. I'll let  you fix this problem

**Pull request closed without merging**
