### PR TITLE
Fix the output of rbd info in expand

### LINKED ISSUE #88643: Use intree-rbd to expand pvc failed
**What happened**:

When I use intree-rbd to expand a pvc from 20Gi to 30Gi, it has been in the Resizing state for a long time.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
  creationTimestamp: "2020-02-28T02:36:26Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: intree-rbd-pvc
  namespace: default
  resourceVersion: "113553071"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/intree-rbd-pvc
  uid: 1e3887cd-59d3-11ea-b7ad-eeeeeeeeeeee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: intree-rbd-sc
  volumeMode: Filesystem
  volumeName: pvc-1e3887cd-59d3-11ea-b7ad-eeeeeeeeeeee
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-28T02:47:59Z"
    status: "True"
    type: Resizing
  phase: Bound
```

And kube-controller-manager reported this error：

```
E0228 02:48:02.557189       1 nestedpendingoperations.go:267] Operation for "\"1e3887cd-59d3-11ea-b7ad-eeeeeeeeeeee\"" failed. No retries permitted until 2020-02-28 02:48:03.05705946 +0000 UTC m=+327.117830161 (durationBeforeRetry 500ms). Error: "error expanding volume \"default/intree-rbd-pvc\" of plugin \"kubernetes.io/rbd\": rbd info failed, error: parse rbd info output failed: 2020-02-28 02:47:59.305808 7f769ab000 -1 did not load config file, using default settings.\n2020-02-28 02:47:59.320080 7f769ab000 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory\n2020-02-28 02:47:59.321712 7f747ee850  0 -- :/243049777 >> 172.16.2.105:6789/0 pipe(0x1213c9fa0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x1213c7e00).fault\n{\"name\":\"kubernetes-dynamic-pvc-11614948-59d4-11ea-a0dd-eeeeeeeeeeee\",\"size\":21474836480,\"objects\":5120,\"order\":22,\"object_size\":4194304,\"block_name_prefix\":\"rbd_data.b372176b8b4567\",\"format\":2,\"features\":[\"layering\"],\"flags\":[]}, invalid character '-' after top-level value"
I0228 02:48:02.557190       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"intree-rbd-pvc", UID:"1e3887cd-59d3-11ea-b7ad-eeeeeeeeeeee", APIVersion:"v1", ResourceVersion:"113553071", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' error expanding volume "default/intree-rbd-pvc" of plugin "kubernetes.io/rbd": rbd info failed, error: parse rbd info output failed: 2020-02-28 02:47:59.305808 7f769ab000 -1 did not load config file, using default settings.
2020-02-28 02:47:59.320080 7f769ab000 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
2020-02-28 02:47:59.321712 7f747ee850  0 -- :/243049777 >> 172.16.2.105:6789/0 pipe(0x1213c9fa0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x1213c7e00).fault
{"name":"kubernetes-dynamic-pvc-11614948-59d4-11ea-a0dd-eeeeeeeeeeee","size":21474836480,"objects":5120,"order":22,"object_size":4194304,"block_name_prefix":"rbd_data.b372176b8b4567","format":2,"features":["layering"],"flags":[]}, invalid character '-' after top-level value
```

The most important msg is:

```
rbd info failed, error: parse rbd info output failed
```

I found this err:
https://github.com/kubernetes/kubernetes/blob/79377454e8dfa4c9c96f786c2f34e2a6230f7139/pkg/volume/rbd/rbd_util.go#L735

After I read this part of the code, I realized that the output of command "rbd info" is not a struct.

**What you expected to happen**:

Pvc expand successful.

### PR DESCRIPTION
**Pull request by huchengze**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fix the output of rbd info in expand。

**Which issue(s) this PR fixes**:

Fixes #88643

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by jsafrane** [comment]
How do you know that json output is *always* the last line? It does not look robust enough to me.

I don't have RBD cluster at hand, are "-1 auth: unable to find a keyring" and "pipe(0x1213c9fa0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x1213c7e00).fault" sent to standard output or standard error? It could help if the driver did not use `CombinedOutput`, but parsed stdout / stderr separately here: https://github.com/kubernetes/kubernetes/blob/331cd94ccc0cdebced1146d0fdefee3701ff8242/pkg/volume/rbd/rbd_util.go#L707-L708

In addition, any `output` pre-processing should be probably done in `rbdInfo()` instead of `getRbdImageSize()`.

**Comment by huchengze** [comment]
> How do you know that json output is _always_ the last line? It does not look robust enough to me.
> 
> I don't have RBD cluster at hand, are "-1 auth: unable to find a keyring" and "pipe(0x1213c9fa0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x1213c7e00).fault" sent to standard output or standard error? It could help if the driver did not use `CombinedOutput`, but parsed stdout / stderr separately here:
> 
> https://github.com/kubernetes/kubernetes/blob/331cd94ccc0cdebced1146d0fdefee3701ff8242/pkg/volume/rbd/rbd_util.go#L707-L708
> 
> In addition, any `output` pre-processing should be probably done in `rbdInfo()` instead of `getRbdImageSize()`.

Thanks for the explanation, I will try a different way to fix it.

**Pull request closed without merging**
