### PR TITLE
release NodePort correctly

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by thockin** [comment]
Good catch!  I hang my head in shame

**Comment by ArtfulCoder** [comment]
I couldn't spot it quickly enough either :) 
I will cherry-pick this for 1.1

**Comment by thockin** [comment]
SGTM

**Comment by saad-ali** [comment]
All tests passed so manually merging to drain merge queue.

**Comment by thockin** [comment]
now for the cherry pick!

**Pull request merged**
