### PR TITLE
Add default leader election for scheduler and controller manager.

### PR DESCRIPTION
**Pull request by fgrzadkowski**
#21124

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@davidopp @roberthbailey @mikedanese @jszczepkowski @wojtek-t

**Comment by roberthbailey** [comment]
If we want to set this flag as the default, why do it via salt/shell vs. setting the proper default value in the code? I'd rather avoid proliferation of new flags that are "required" but not actually defaulted in the code.

**Comment by mikedanese** [comment]
If that's not considered an API breaking behavior change agree with @roberthbailey

**Comment by fgrzadkowski** [comment]
That's a very good point! It should not be a breaking change because by default we will have a single instance of each such component anyway...

**Comment by mikedanese** [comment]
LGTM

**Comment by fgrzadkowski** [comment]
@mikedanese Can you also add `lgtm` label?

**Pull request merged**
