### PR TITLE
Fix API comment for the FailIndex Job pod failure policy action

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind documentation
/kind api-change

#### What this PR does / why we need it:

Fixes the comment after graduation to Beta.

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/3850

#### Does this PR introduce a user-facing change?

```release-note
Fix API comments for the FailIndex Job pod failure policy action.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs
```

### CODE REVIEW

**Review by liggitt — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
@liggitt can this still get the 1.29 milestone?

**Pull request merged**
