### PR TITLE
[WIP] Refactor pkg/kubelet/cm

### PR DESCRIPTION
**Pull request by dolftax**
Signed-off-by: Jai <jaipradeesh@gmail.com>

**What this PR does / why we need it**: Refactores `pkg/kubelet/cm` into multiple sub-dirs

**Which issue this PR fixes**: fixes # #53170

**Special notes for your reviewer**: WIP. Build files not updated. Tests won't pass. Callers not updated. Only `cm` package has been refactored into sub-dirs. Let me know if I'm headed in thr right direction.

Ref: https://godoc.org/k8s.io/kubernetes/pkg/kubelet/cm
Also, is it okay if the exported methods from cm move into sub-packages? For example: `cm.ConvertCgroupFsNameToSystemd` would be changed into `cgroupmanager.ConvertCgroupFsNameToSystemd`

#### Directory structure: pkg/kubelet/cm

```
.
├── BUILD
├── cgroupmanager
│   ├── BUILD
│   ├── cgroup_manager_linux.go
│   ├── cgroup_manager_linux_test.go
│   ├── cgroup_manager_test.go
│   └── cgroup_manager_unsupported.go
├── containerlifecycle
│   ├── BUILD
│   └── containerlifecycle.go
├── containermanager
├── container_manager.go
├── container_manager_linux.go
├── container_manager_linux_test.go
├── container_manager_stub.go
├── container_manager_unsupported.go
├── container_manager_unsupported_test.go
├── container_manager_windows.go
├── cpumanager
│   ├── BUILD
│   ├── cpu_assignment.go
│   ├── cpu_assignment_test.go
│   ├── cpu_manager.go
│   ├── cpu_manager_test.go
│   ├── fake_cpu_manager.go
│   ├── OWNERS
│   ├── policy.go
│   ├── policy_none.go
│   ├── policy_none_test.go
│   ├── policy_static.go
│   ├── policy_static_test.go
│   ├── policy_test.go
│   ├── state
│   │   ├── BUILD
│   │   ├── state.go
│   │   └── state_mem.go
│   └── topology
│       ├── BUILD
│       ├── doc.go
│       ├── topology.go
│       └── topology_test.go
├── cpuset
│   ├── BUILD
│   ├── cpuset.go
│   ├── cpuset_test.go
│   └── OWNERS
├── deviceplugin
│   ├── BUILD
│   ├── device_plugin_handler.go
│   ├── device_plugin_handler_stub.go
│   └── device_plugin_handler_test.go
├── node_container_manager.go
├── node_container_manager_test.go
├── podcontainer
│   ├── BUILD
│   ├── pod_container_manager_linux.go
│   ├── pod_container_manager_stub.go
│   └── pod_container_manager_unsupported.go
├── qoscontainer
│   ├── BUILD
│   └── qos_container_manager_linux.go
├── types.go
└── util
    ├── BUILD
    ├── helper_linux.go
    ├── helper_linux_test.go
    └── helper_unsupported.go

```

### CODE REVIEW

**Comment by resouer** [comment]
@dolftax Please add a structure of your current sub-dirs in descriptions of this PR. This will help the reviewers a lot.

**Comment by dolftax** [comment]
## Directory structure: pkg/kubelet/cm

```
cm
├── BUILD
├── cgroupmanager
│   ├── BUILD
│   ├── cgroup_manager_linux.go
│   ├── cgroup_manager_linux_test.go
│   ├── cgroup_manager_test.go
│   └── cgroup_manager_unsupported.go
├── containermanager
│   ├── BUILD
│   ├── container_manager.go
│   ├── container_manager_linux.go
│   ├── container_manager_linux_test.go
│   ├── container_manager_stub.go
│   ├── container_manager_unsupported.go
│   ├── container_manager_unsupported_test.go
│   └── container_manager_windows.go
├── cpumanager
│   ├── BUILD
│   ├── cpu_assignment.go
│   ├── cpu_assignment_test.go
│   ├── cpu_manager.go
│   ├── cpu_manager_test.go
│   ├── fake_cpu_manager.go
│   ├── OWNERS
│   ├── policy.go
│   ├── policy_none.go
│   ├── policy_none_test.go
│   ├── policy_static.go
│   ├── policy_static_test.go
│   ├── policy_test.go
│   ├── state
│   │   ├── BUILD
│   │   ├── state.go
│   │   └── state_mem.go
│   └── topology
│       ├── BUILD
│       ├── doc.go
│       ├── topology.go
│       └── topology_test.go
├── cpuset
│   ├── BUILD
│   ├── cpuset.go
│   ├── cpuset_test.go
│   └── OWNERS
├── deviceplugin
│   ├── BUILD
│   ├── device_plugin_handler.go
│   ├── device_plugin_handler_stub.go
│   └── device_plugin_handler_test.go
├── helper
│   ├── BUILD
│   ├── helper_linux.go
│   ├── helper_linux_test.go
│   └── helper_unsupported.go
├── internal_container_lifecycle.go
├── nodecontainer
│   ├── BUILD
│   ├── node_container_manager.go
│   └── node_container_manager_test.go
├── podcontainer
│   ├── BUILD
│   ├── pod_container_manager_linux.go
│   ├── pod_container_manager_stub.go
│   └── pod_container_manager_unsupported.go
├── qoscontainer
│   ├── BUILD
│   └── qos_container_manager_linux.go
├── types
│   ├── BUILD
│   └── types.go
└── util
    ├── BUILD
    ├── cgroups_linux.go
    └── cgroups_unsupported.go
```

**Comment by dolftax** [comment]
@resouer Plese don't run tests now. The work is WIP as mentioned in the description - https://github.com/kubernetes/kubernetes/pull/53258#issue-261693727

**Review by resouer — COMMENTED** [review]
Some comments from my side:
1. Internal container lifecycle is only used by cpu set
2. util and help sub-dir seems duplicated

Please stay tuned and collect feedback from other reviewers, refactoring PR usually need more time. :)

**Comment by dolftax** [comment]
- Internalcontainerlifecycle is being used by containermanager as well. Its better to keep it separate.

```
./pkg/kubelet/kuberuntime/kuberuntime_manager.go:115:	internalLifecycle cm.InternalContainerLifecycle
./pkg/kubelet/kuberuntime/kuberuntime_manager.go:142:	internalLifecycle cm.InternalContainerLifecycle,
./pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go:81:		internalLifecycle:   cm.NewFakeInternalContainerLifecycle(),
./pkg/kubelet/kubelet.go:639:			kubeDeps.ContainerManager.InternalContainerLifecycle(),
./pkg/kubelet/cm/containermanager/container_manager.go:76:	InternalContainerLifecycle() cmcontainerlifecycle.InternalContainerLifecycle
./pkg/kubelet/cm/containermanager/container_manager_stub.go:80:func (cm *containerManagerStub) InternalContainerLifecycle() containerlifecycle.InternalContainerLifecycle {
./pkg/kubelet/cm/containermanager/container_manager_unsupported.go:83:func (cm *unsupportedContainerManager) InternalContainerLifecycle() InternalContainerLifecycle {
./pkg/kubelet/cm/containermanager/container_manager_linux.go:338:func (cm *containerManagerImpl) InternalContainerLifecycle() containerlifecycle.InternalContainerLifecycle {
./pkg/kubelet/cm/cpuset/containerlifecycle.go:27:type InternalContainerLifecycle interface {
./pkg/kubelet/cm/cpuset/containerlifecycle.go:33:// Implements InternalContainerLifecycle interface.
./pkg/kubelet/cm/cpuset/containerlifecycle.go:61:func NewFakeInternalContainerLifecycle() *fakeInternalContainerLifecycle {
./pkg/kubelet/cm/cpuset/containerlifecycle.go:62:	return &fakeInternalContainerLifecycle{}
./pkg/kubelet/cm/cpuset/containerlifecycle.go:65:type fakeInternalContainerLifecycle struct{}
./pkg/kubelet/cm/cpuset/containerlifecycle.go:67:func (f *fakeInternalContainerLifecycle) PreStartContainer(pod *v1.Pod, container *v1.Container, containerID string) error {
./pkg/kubelet/cm/cpuset/containerlifecycle.go:71:func (f *fakeInternalContainerLifecycle) PreStopContainer(containerID string) error {
./pkg/kubelet/cm/cpuset/containerlifecycle.go:75:func (f *fakeInternalContainerLifecycle) PostStopContainer(containerID string) error {
```

- Duplicated? You mean to merge them into one package?

@resouer ☝️

**Comment by resouer** [comment]
Right, I think they can be merged.

**Comment by resouer** [comment]
Em, the current `Directory structure` make sense to me. Please expect more comments from sig-node. @kubernetes/sig-node-pr-reviews

**Comment by dolftax** [comment]
This refactor breaks my head. Heh. Many cyclic imports to be fixed. Let me know if the dir structure makes sense so that I can put some effort to refactor the package.

**Comment by RenaudWasTaken** [comment]
I like the idea of separating device plugin in it's own directory.

This will allow to have a specific module for testing and coverage.
This will also make it clearer what part of the code is related to the device plugin when we split some part of the device_plugin_handler file (e.g: checkpointing for cpu manager, ...)

@jiayingz ^

**Comment by jiayingz** [comment]
@RenaudWasTaken Very agree. With this change, I think we may just move the code currently under pkg/kubelet/deviceplugin/ to pkg/kubelet/cm/deviceplugin/. It is easier to simplify code structure with deviceplugin code living in one directory and we may be able to get rid of some callbacks.

**Comment by jiayingz** [comment]
@dolftax I am wondering whether it would be easier to do this refactoring through a series of PRs instead of through a single big PR. E.g., once we get consensus on this general direction, for the device plugin part, we can have a single PR to move the code.

**Comment by resouer** [comment]
+1 for @jiayingz , please split the PR into smaller ones. And you can start with ones already reach agreement.

**Comment by derekwaynecarr** [comment]
I agree on doing this is a series of PR rather than one.

**Pull request closed without merging**
