### PR TITLE
Fixes code duplication.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by ashcrow** [comment]
Good find @aveshagarwal!

**Comment by ashcrow** [comment]
Known e2e flake:

```
[Fail] Probing container [It] with readiness probe should not be ready before initial delay and never restart [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:59
```

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
