### PR TITLE
Cherry-pick of #16364

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #16364 on release-1.1.

### CODE REVIEW

**Comment by liggitt** [comment]
@caesarxuchao error text from running the cherry pick script:
```
$ GITHUB_USER=liggitt hack/cherry_pick_pull.sh  upstream/release-1.1 16364
+++ Updating remotes...
Fetching upstream
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 26 (delta 17), reused 17 (delta 17), pack-reused 5
Unpacking objects: 100% (26/26), done.
From github.com:kubernetes/kubernetes
   70049d1..d228fd6  master     -> upstream/master
Fetching origin
+++ Creating local branch automated-cherry-pick-of-#16364-upstream-release-1.1-1445999357
Checking out files: 100% (3014/3014), done.
Branch automated-cherry-pick-of-#16364-upstream-release-1.1-1445999357 set up to track remote branch release-1.1 from upstream.
Switched to a new branch 'automated-cherry-pick-of-#16364-upstream-release-1.1-1445999357'
+++ Downloading patch to /tmp/16364.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /tmp/16364.patch

Applying: Add TypeMeta to discovery response objects

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-#16364-upstream-release-1.1-1445999357:automated-cherry-pick-of-#16364-upstream-release-1.1

+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] y
Counting objects: 449, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (94/94), done.
Writing objects: 100% (449/449), 135.20 KiB | 0 bytes/s, done.
Total 449 (delta 363), reused 409 (delta 346)
To git@github.com:liggitt/kubernetes.git
 * [new branch]      automated-cherry-pick-of-#16364-upstream-release-1.1-1445999357 -> automated-cherry-pick-of-#16364-upstream-release-1.1
+++ Creating a pull request on github
invalid argument: -F/tmp/tmp.Twg4i3cTyb

+++ Returning you to the master branch and cleaning up.
```

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Error is probably from trying to auto-make the PR for you and/or deleting your local branch.

**Comment by caesarxuchao** [comment]
I'll compare it with my output next time I make a cherry-pick.

**Comment by liggitt** [comment]
adding tag for @lavalamp

**Comment by caesarxuchao** [comment]
@liggitt, FYI, my output is
```
hub pull-request -F/tmp/tmp.8LqlajZL5q -h caesarxuchao:automated-cherry-pick-of-#16082-upstream-release-1.1 -b kubernetes:release-1.1
```

I can't figure out why it complains "invalid argument" when you run it.

**Comment by liggitt** [comment]
I had a super-old version of hub (1.12.1). Just updated, and we'll see if that helps.

**Pull request merged**
