### PR TITLE
use more-specific arm32v7 instead of deprecated armhf organization

### LINKED ISSUE #50618: The armhf organization is deprecated in favor of the more-specific arm32v7 organizations
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/area release-infra
/sig release

**What happened**:
As stated in [armhf/debian on Docker Hub](https://hub.docker.com/r/armhf/debian/)
> The `armhf` organization is deprecated in favor of the more-specific `arm32v7` and `arm32v6` organizations

**What you expected to happen**:
We should replace current `armhf/*` Docker images to `arm32v7/*`

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50618

**Special notes for your reviewer**:
/assign @mkumatag @ixdy @luxas 

**Release note**:

```release-note
use more-specific arm32v7 instead of deprecated armhf organization
```

### CODE REVIEW

**Comment by dixudx** [comment]
/cc @mkumatag 
PTAL. Thanks

**Review by luxas — COMMENTED** [review]
Please bump the `armel` images in `build/common.sh` as well to `arm32v7`. They should have been `armhf`, I seem to have missed those.

Also look if you can find other `armel` to replace.

**Review by mkumatag — APPROVED** [review]

**Review by mkumatag — CHANGES_REQUESTED** [review]
Will have to regenerate the docker image with new base as `armhf/debian:jessie` is kind of a stale image older than 3 months.

**Comment by dixudx** [comment]
@luxas @ixdy Any comments on the above suggestions from @mkumatag

**Comment by dixudx** [comment]
Bumped a new version in PR #50602.

**Comment by luxas** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/50602

**Pull request closed without merging**
