### PR TITLE
Fix ip-alias testing.

### PR DESCRIPTION
**Pull request by rmmh**
IP aliases are an alpha feature, and node accelerators are a beta
feature. $gcloud determines which is appropriate.

Before, this would try to run "gcloud alpha beta", which is incoherent.

```release-note
NOTE
```

### CODE REVIEW

**Comment by rmmh** [comment]
Example broken test here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ip-alias/1513?log#log

**Comment by vishh** [comment]
/lgtm
/approve

Thanks for the fix @rmmh

**Comment by vishh** [comment]
`P0` because it's fixing a failing test

**Comment by rmmh** [comment]
Priorities aren't read by the SQ anymore, I think critical-fix is the appropriate label for this.

**Comment by vishh** [comment]
@rmmh Ah thanks for the tip

**Comment by rmmh** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
