### PR TITLE
test case for set_resources

### PR DESCRIPTION
**Pull request by suyogbarve**
PR adds basic unit test for set_resources.go

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by suyogbarve** [comment]
@k8s-bot bazel test this

**Comment by suyogbarve** [comment]
@k8s-bot verify test this

**Comment by suyogbarve** [comment]
@k8s-bot bazel test this

**Comment by suyogbarve** [comment]
@k8s-bot verify test this

**Comment by suyogbarve** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by suyogbarve** [comment]
@dims : I am wondering whats going on over here, why are the build job failing?

**Comment by mengqiy** [comment]
Please run hack/update-bazel.sh.

**Comment by suyogbarve** [comment]
@k8s-bot unit test this
@k8s-bot kops aws e2e test this

**Comment by suyogbarve** [comment]
@k8s-bot kops aws e2e test this

**Comment by suyogbarve** [comment]
@k8s-bot verify test this

**Comment by suyogbarve** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by suyogbarve** [comment]
@k8s-bot verify test this
@k8s-bot kops aws e2e test this

**Comment by suyogbarve** [comment]
help @dims whats going on over here? I am clueless why these tests keep failing?

**Comment by suyogbarve** [comment]
@k8s-bot verify test this

**Comment by dims** [comment]
@suyogbarve try rebasing against master?

**Comment by suyogbarve** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by mengqiy** [comment]
cc: @fabianofranz for approval.

**Pull request merged**
