### PR TITLE
Fix file permissions for non executable files

### PR DESCRIPTION
**Pull request by odinuge**
Normal files should have permissions 644 by default,
and does not require the last bit to be
executable

Signed-off-by: Odin Ugedal <odin@ugedal.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
It fixes file permissions for a couple of normal files.

Normal files should have permissions 644 by default,
and does not require the last bit to be
executable

**Which issue(s) this PR fixes**:

`N/A`

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm

Thanks for cleaning that up, @odinuge! :)

**Comment by odinuge** [comment]
from hack/OWNERS
/cc @BenTheElder 

from staging/src/k8s.io/apiserver/OWNERS
/cc @lavalamp

from staging/src/k8s.io/client-go/OWNERS
/cc @caesarxuchao 

from test/OWNERS
/cc @oomichi

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
wonder how these happened :-)

**Comment by oomichi** [comment]
Thanks for fixing

/lgtm

**Pull request merged**
