### PR TITLE
kubefed client.Core()

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
left some place of core
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49765

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
@jianglingxia  Please help to check any other missing places for core client, and fix them together in this PR, which will be better for review. Other group clients has been fixed in PR #49763, you can help to review.

**Comment by jianglingxia** [comment]
ok，thanks，I will fix it in the pr about the core client later！

**Comment by jianglingxia** [comment]
I have rebased it , @ @derekwaynecarr @csbell @krousey @nicksardo
thanks

**Pull request closed without merging**
