### PR TITLE
set the required default value in kubectl

### PR DESCRIPTION
**Pull request by yarntime**
set the required default value in kubectl.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37786)

**Comment by fabianofranz** [comment]
@yarntime Thanks for the PR? Can you please fill the [PR template](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) in your original comment to make it clear what this PR does, which issue it fixes, etc?

**Comment by yarntime** [comment]
Hi @fabianofranz , I just want to set the same default value as in apis/extensions/v1beta1. I'm not sure whether we should change this, if not, I'll close this pr. thanks.

**Comment by fabianofranz** [comment]
> I just want to set the same default value as in apis/extensions/v1beta1. I'm not sure whether we should change this, if not, I'll close this pr.

Doesn't seem needed. @AdoHe opinion?

**Comment by AdoHe** [comment]
I agree with @fabianofranz, not needed. Thanks all the same @yarntime

**Pull request closed without merging**
