### PR TITLE
Revert "scheduler/nodeaffinity: reduce pod scheduling latency"

### PR DESCRIPTION
**Pull request by sanposhiho**
This reverts commit 1d88bf9789bbe27288804b0e226be36884fa374d.

#### What type of PR is this?

/kind bug
/priority critical-urgent
/triage accepted

#### What this PR does / why we need it:

NodeAffinity QueueingHint may miss Node related events that make Pod schedulable because of preCheck.
It's similar to: https://github.com/kubernetes/kubernetes/pull/119177#issuecomment-1820091877

So:
1. Node is added. But, it's filtered out by preCheck (due to node's unready or whatever) and the scheduling queue doesn't receive NodeAdded. (noderesourcefit cannot receive NodeAdded.)
2. Node is updated and ready now. But, this event is NodeUpdated.

In such scenarios, NodeAffinity returns `QueueSkip` to the event due to (2), because (2) is just a taint update, which looks unrelated to NodeAffinity.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L94-L131

#### Which issue(s) this PR fixes:

Temporal fix for #122284

#### Special notes for your reviewer:

@kubernetes/sig-scheduling-leads 
If possible, we have to get this PR in v1.29, but the release date is very close.
The user impact is that sometimes Pods, which was rejected by NodeAffinity, could be stuck in unschedQ during max 5min even though a new Node is created.
Can we somehow include it in v1.29? or do we have to wait for the patch release.

#### Does this PR introduce a user-facing change?

```release-note
QueueingHint implementation for NodeAffinity is reverted because we found potential scenarios where events that make Pods schedulable could be missed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/hold
as https://github.com/kubernetes/kubernetes/pull/122289 is merged.

**Comment by sanposhiho** [comment]
Given https://github.com/kubernetes/kubernetes/pull/122289 is merged, it's OK to revert the change in the patch release.

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

**Comment by sanposhiho** [comment]
/retest

https://github.com/kubernetes/kubernetes/issues/122312

**Comment by alculquicondor** [comment]
Same question:
Why revert the code if the overall feature is disabled?

**Comment by alculquicondor** [comment]
This is removing the entire hint. Is that the only thing we can do to fix the problem? Or is there a more surgical fix that we can cherry-pick?

**Pull request merged**
