### PR TITLE
Support updating config map and secret

### LINKED ISSUE #30558: Support updating config map and secret with --from-file
It is possible to create a config map using `kubectl create configmap foo --from-file bar.txt`.  We support similarly updating the config map using `kubectl update configmap foo --from-file bar.txt`.

### PR DESCRIPTION
**Pull request by mengqiy**
Fixes #30558
cc @pwittrock

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32429)

### CODE REVIEW

**Comment by liggitt** [comment]
this seems like a lot of duplication. also, do we want complete replacement of the entire object, or targeted replacement of one or more keys?

**Comment by ymqytw** [comment]
I have updated the PR. I tried to reduce duplication in the new implementation. In the new implementation, only kubectl replace with "--force" flag will first delete the resource and then create a new one. Other normal replace will reuse the old object and just update the Data field.

**Comment by ymqytw** [comment]
Will break this PR into several small PR for easier review.

**Comment by liggitt** [comment]
Before we create a bunch of PRs with replace subcommands, we should probably create a single prototypical one and decide what the shape should look like. 

cc @fabianofranz @kubernetes/rh-ux

**Pull request closed without merging**
