### PR TITLE
move all create commands and subcommands to a separate package

### LINKED ISSUE #38761: kubectl create should be in its own package
Similar to the rest of our nested commands (set, rollout). Unfortunately a straight move is not possible atm because of create depending on edit (thus introducing cyclic dependencies in kubectl). We should probably move the edit functionality in a common location (eg. the already existing pkg/kubectl/cmd/util/editor) and have the kubectl commands re-use it. I am not sure if we want to do such a thing, just wanted to bring this up

@kubernetes/kubectl @kubernetes/sig-cli thoughts

### PR DESCRIPTION
**Pull request by adohe-zz**
**What this PR does / why we need it**:
fix #38761 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
move all create commands and subcommands to a separate package
```

### CODE REVIEW

**Comment by adohe** [comment]
@kubernetes/kubectl-reviewers @kubernetes/kubectl-maintainers ptal.

**Comment by adohe** [comment]
please give a quick review, tell me what you think about this.

**Comment by deads2k** [comment]
/lgtm

needs to build though :)

**Comment by shiywang** [comment]
@pwittrock I would like to work on @adohe's commit if he is busy.

**Comment by tcharding** [comment]
Woops, I duplicated @adohe's PR (#51242) before I saw it had already been done. Sorry for the noise, I'll close mine and leave this one since it was first.

**Comment by tcharding** [comment]
We may need an entry in `.golint_failures` to quiet the `pull-kubernetes-verify` failures. `kubectl/cmd` has an entry.

**Comment by dims** [comment]
Do we need this for 1.8? please rebase.

**Comment by shiywang** [comment]
@dims I don't think we could ship this into v1.8 @abgworrall could you please help remove the label ? thanks

**Comment by abgworrall** [comment]
Milestone removed.

**Pull request closed without merging**
