### PR TITLE
Make travis run precommits only

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
Travis finished in 4:49 - not great, but better

**Comment by thockin** [comment]
@lavalamp

**Comment by lavalamp** [comment]
Hm, I made https://github.com/GoogleCloudPlatform/kubernetes/pull/11245

...let's see which is faster

**Comment by lavalamp** [comment]
Mine ran in 2 min 46 sec

**Comment by lavalamp** [comment]
You left in an unneeded ```- PATH=$GOPATH/bin:$PATH godep go install ./...```

**Pull request closed without merging**
