### PR TITLE
Bump github.com/Azure/go-autorest/autorest/adal to 0.9.5 and github.c…

### PR DESCRIPTION
**Pull request by patrickshan**
…om/Azure/go-autorest/autorest to v0.11.12

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
similar to #95692 and #97033. This is to bump related libraries inside 1.18 branch.

Fixes #

**Does this PR introduce a user-facing change?**:
No

```release-note
Bump github.com/Azure/go-autorest/autorest/adal to 0.9.5 and github.com/Azure/go-autorest/autorest to v0.11.12
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by liggitt** [comment]
given kubernetes doesn't actually build with the code impacted by the CVE (xref https://github.com/kubernetes/kubernetes/pull/97033#issuecomment-738940122), is this important to backport?

**Comment by patrickshan** [comment]
same as https://github.com/kubernetes/kubernetes/pull/97381

**Pull request closed without merging**
