### PR TITLE
windows pod sandbox , iteration 1

### LINKED ISSUE #93580: Investigate removal of call to generatePodSandboxLinuxConfig for Windows kubelet
**What happened**:
When testing https://github.com/kubernetes/kubernetes/pull/93475, @ravisantoshgudimetla pointed out that invocation of `generatePodSandboxLinuxConfig` is necessary for the Windows pods to come up: https://github.com/kubernetes/kubernetes/pull/93475/files#r463009694 . Skipping the call to `generatePodSandboxLinuxConfig` leads to a CNI error.

**What you expected to happen**:
Windows pods should be able to come up without having to call `generatePodSandboxLinuxConfig`

**How to reproduce it (as minimally and precisely as possible)**:
Remove invocation of `generatePodSandboxLinuxConfig` for Windows paths and test Windows pod bringup.

**Anything else we need to know?**:
Ideally we should be able to accomplish https://github.com/kubernetes/kubernetes/pull/93475/files#r462857857

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jayunit100**
first iteration to fix #93580

### CODE REVIEW

**Comment by jayunit100** [comment]
@ravisantoshgudimetla

**Comment by jsturtevant** [comment]
This logic is being updated in the HostProcess PR: https://github.com/kubernetes/kubernetes/pull/99576/files#diff-2e2d495cb2f6938efb55dfcd758c182922b2f28271f9c237bf710c49cb8a12a7

I think it would be ok to close this and prefer hostprocess updates?

**Comment by marosset** [comment]
OK With me.

**Pull request closed without merging**
