### PR TITLE
Move pkg/kubectl/generate to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/generate` and `pkg/kubectl/generate/versioned` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/generate.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @dims 

for `hack/.golint_failures` and `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
