### PR TITLE
Adding myself as OWNER for vSphere Cloud Provider.

### PR DESCRIPTION
**Pull request by SandeepPissay**
Adding myself and few folks from VMware as owner of vSphere volume provisioner/vSphere cloud provider. Also removing some users as they no longer work on vSphere volume provisioner/vSphere cloud provider.

```release-note
Updating OWNERS list for vSphere Cloud Provider.
```

### CODE REVIEW

**Comment by SandeepPissay** [comment]
@abrarshivani @divyenpatel can you guys approve this PR? Thanks.

**Review by divyenpatel — APPROVED** [review]

**Review by divyenpatel — APPROVED** [review]

**Comment by SandeepPissay** [comment]
@saad-ali Can you approve this?

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by SandeepPissay** [comment]
kind/cleanup

**Pull request merged**
