### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by jorenhehe**
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by jorenhehe** [comment]
Thanks @k82cn . Please help review

**Comment by k82cn** [comment]
/lgtm

No sure whether have the permission for LGTM :).

**Comment by jorenhehe** [comment]
@smarterclayton ptal

**Comment by jorenhehe** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jorenhehe** [comment]
@k8s-bot kops aws e2e test this 
@k8s-bot kubemark e2e test this

**Pull request merged**
