### PR TITLE
kube-proxy: remove port opener

### PR DESCRIPTION
**Pull request by khenidak**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
kube-proxy holds service node ports open (`Listen()` without `Read()/Receive()` pump). The original idea was to stop users from mistakenly create a listener on the node that listens to a node port which would have created debugging problems. It is important to note that if the opener failed we just log and keep going. However port-opener introduced more problems than value. The problems can be be briefly described as the following:
1. We open the port before we commit the forwarding/LB rules, the rules typically take much longer to process before committing. That means if the user connected before rules were set they will indeed connect to kube-proxy not the actual pod backing the service. This usually require restarting the client (be it pod or external proce) or the proxy itself. This is more visible as more nodes get introduced to existing clusters with large number of service (the time between open-port and fwd/lb rules is longer).
2. Port opener also leaves many dangling tcp connections due to this behavior as described here: https://github.com/kubernetes/kubernetes/issues/106713

further discussions can be found here: https://github.com/kubernetes/kubernetes/issues/100643

> a script or a stand alone tool can be built (runs on node) to scan services+node-ports and performs a bind(2) on address for debugging purposes. But the scan loop will not be part of kube-proxy.

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubernetes/issues/100643
https://github.com/kubernetes/kubernetes/issues/106713

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?
```release-note
kube-proxy will no longer hold service node ports open on the node. Users are still advised not to run any listener on node ports range used by kube-proxy. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
N/A 
```
/sig network

### CODE REVIEW

**Comment by khenidak** [comment]
fyi @aojea  @thockin

**Comment by aojea** [comment]
> Kubernetes e2e suite: [sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service expand_more	

/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by khenidak** [comment]
> > Kubernetes e2e suite: [sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service expand_more
> 
> /test pull-kubernetes-e2e-gci-gce-ipvs

other than this (it is a mistake, i will fix) https://github.com/kubernetes/kubernetes/pull/108496/files#diff-1f2043db3a45960023376d03e4dd43762d1382ad7ea94e3f26c956410b749c97L1455 i didn't remove anything that interacts with conntrack.

**Comment by khenidak** [comment]
I will restore ipvs to original state. and just comment out the open port part just to confirm that portOpener does not leave conntrack entries.

**Comment by khenidak** [comment]
/retest

@aojea  i think this one is ready for review now. Thanks.

**Comment by aojea** [comment]
> @aojea i think this one is ready for review now. Thanks.

/hold cancel
LGTM
@thockin deserves the honor , he was persuing for a long time :smile:

**Comment by danwinship** [comment]
> kube-proxy will no longer hold service node ports open on the node. Users are still advised not to run any listener on node ports range used by kube-proxy.

Should we prevent people from extending `--service-node-port-range` to include ranges that are likely to have listening services? (eg, the starting value has to be >= 1024 at a minimum)

Should we add a kube-apiserver option to reject Pods that try to use HostPorts in the NodePort range?

**Comment by danwinship** [comment]
> > Should we prevent people from extending --service-node-port-range to include ranges that are likely to have listening services? (eg, the starting value has to be >= 1024 at a minimum)
> 
> I can not rule out an edge case where a user would want privileged ports. I am not sure if we can assume it

But we're saying that that configuration would no longer be secure.

Right now, `--service-node-port-range 0-65535` is a bad idea, but it's not _completely_ terrible. If we remove the port opener, then in a cluster that uses `--service-node-port-range 0-65535` it would suddenly be possible for any user to intercept ssh / DNS / etc traffic to the node.

I guess we could say that by default we'd reject this, but you can pass `--service-node-port-range-insecure` to tell the apiserver, yes, I want to get hacked.

> > Should we add a kube-apiserver option to reject Pods that try to use HostPorts in the NodePort range?
> 
> That is a good idea. But it is a breaking change. right?

That's why I was saying "add an option". You'd have to opt into it. (Or maybe we can enable it by default because security, and force people to opt out of it?)

**Comment by khenidak** [comment]
@danwinship Thanks for this.

I don't consider port opener to be a security measure. It prevents a debugging nightmare. It is not even that good at it (if port opening failed, we just log and carry on with the rest of the process such as adding iptables entries). 

I do see the security concern. But i don't think an attacker needs a node port for that. It is enough to run a privileged pod or a clever host net pod. I think we need to think about that further.

**Comment by aojea** [comment]
> I don't consider port opener to be a security measure. It prevents a debugging nightmare. It is not even that good at it (if port opening failed, we just log and carry on with the rest of the process such as adding iptables entries).

there is one case, that stops a new process to start on a port that is already used by a nodeport, but the tradeoff is that  we add much noise on the system and waste system resources.

I don't see anybody disagrees with removing them, that doesn't mean that we should not explore new options to protect users
I will put on hold for some time in case I got it wrong and there are opposition to remove them, or just unhold it if we all agree on removing it

/lgtm
/hold

**Comment by aojea** [comment]
> if you're using PodSecurityPolicy / PodSecurityPolicy-replacement, you can use RBAC to block untrusted users from creating privileged pods or pods with hostports (and in fact, both are blocked by default). However, there is no existing way to block users from creating NodePorts because it is assumed that (unlike with HostPorts) NodePorts do not create any security problems.

you can always have admission webhooks, can't you?

**Comment by danwinship** [comment]
Yes, you _can_ use admission webhooks, but _will_ people?

The questions I'm trying to ask here are (1) does the removal of this code make it easier for users to accidentally shoot themselves in the foot? and (2) if so, do we want to _not_ do that?

**Comment by aojea** [comment]
> The questions I'm trying to ask here are (1) does the removal of this code make it easier for users to accidentally shoot themselves in the foot?

Let put the hostPort conversation aside, since that allows you to break any rule and is not solved by this PR

(1) I think that this only prevent a very rare case, if someone launches a process listening on the nodeport AFTER a nodeport is created, the thing is that this method doesn't solve the important problems and causes others

(2) we have several bugs about the open sockets causing issues on users referenced in the description, I don't remember any (doesn't mean it doesn't exist) about nodeport security issues ... 

> Yes, you can use admission webhooks, but will people?

I think that our defaults are safe, but nobody stops people of doing `sudo rm -rf /` :smile: , if you put your node-port range on 0-1024 you are doing a conscious decision

**Comment by khenidak** [comment]
> The questions I'm trying to ask here are (1) does the removal of this code make it easier for users to accidentally shoot themselves in the foot? and (2) if so, do we want to not do that?

for 1: the code removed does not prevent accidents. it logs if it found that port was already open. It is important to understand that once node port is used traffic is routed to service endpoints even if there was a listener somewhere on the node (iptables fires in the lower parts of the stack. userspace listeners are way up in the stack).  IOW the current code is kind of pointless and causing more pain than gain (see ref-ed issues).

for 2: Since it does not. But the behavior is a debugging nightmare and we should help users avoid it. We can have a scanner that identifies if there is a listener, maybe as part of node problem detector project but not as part of the proxy.

**Comment by thockin** [comment]
> If we remove the port opener, then ... it would suddenly be possible for any user to intercept ssh_

It's already possible in that case - kube-proxy will log that :22 was in use, but then it will go ahead and capture the port anyway!

**Comment by thockin** [comment]
Oh, I see Kal beat me to it :)

**Review by thockin — COMMENTED** [review]
Good riddance to bad rubbish!

/lgtm
/approve

**Comment by aojea** [comment]
@danwinship is ok to unhold or do you still have concerns?

**Comment by aojea** [comment]
> I don't see anybody disagrees with removing them, that doesn't mean that we should not explore new options to protect users I will put on hold for some time in case I got it wrong and there are opposition to remove them, or just unhold it if we all agree on removing it
> 
> /lgtm /hold

/hold cancel

let's use silence as no disagreement

**Comment by danwinship** [comment]
> It's already possible in that case - kube-proxy will log that :22 was in use, but then it will go ahead and capture the port anyway!

image

**Pull request merged**
