### PR TITLE
delete unused image hello-kubernetes

### PR DESCRIPTION
**Pull request by mikedanese**
From it's initial commit:

> Add smallest image possible to use for e2e-testing

This shouldn't be in build/

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Are these files used anywhere?  I couldn't find any reference to "hello-kubernetes" across our repo?  Perhaps they can be deleted rather then being renamed?

Barring that comment, LGTM.

**Comment by mikedanese** [comment]
@quinton-hoole I agree. Let's just remove it.

**Comment by quinton-hoole** [comment]
@derekwaynecarr it seems you added this hello-kubernetes image.  It doesn't seem to be used anywhere.  Any objection if we delete it?

**Comment by derekwaynecarr** [comment]
I had wanted a small image to use in e2e but it never was being built on
Docker Hub at the time many months ago.  I am fine removing it.

**Comment by mikedanese** [comment]
@quinton-hoole ping

**Comment by quinton-hoole** [comment]
Ah yes, LGTM!

**Pull request merged**
