### PR TITLE
Automated cherry pick of #45623

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #45623 on release-1.6.

#45623: Don't attempt to make and chmod subPath if it already exists

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by enisoc** [comment]
@wongma7 Are you working on adding a test that would have caught this? That's important to have before cutting the next release so we are sure it's fixed.

**Comment by wongma7** [comment]
@enisoc yes, at the least e2es to catch the original permissions bug then this one as well. We discussed in sig-storage today/yesterday so folks know to help review and such

**Comment by yujuhong** [comment]
/approve

I didn't follow the issue so I'll leave this to the @kubernetes/sig-storage-pr-reviews to lgtm.

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by wongma7** [comment]
@k8s-bot gce etcd3 e2e test this

https://github.com/kubernetes/kubernetes/issues/44226

**Comment by wongma7** [comment]
@k8s-bot verify test this

**Comment by wongma7** [comment]
@enisoc I think 1.6 branch needs some kind of hack/update, this failed twice:

I0515 17:35:41.911] -   "version": "v1.6.5"
I0515 17:35:41.911] +   "version": "v1.6.4"
I0515 17:35:41.911]    },
I0515 17:35:41.911]    "paths": {
I0515 17:35:41.911]     "/api/": {
I0515 17:35:41.911] /go/src/k8s.io/kubernetes/federation/apis/openapi-spec is out of date. Please run hack/update-federation-openapi-spec.sh

thanks
I0515 17:35:41.915] FAILED   hack/make-rules/../../hack/verify-federation-openapi-spec.sh	131s

**Comment by wongma7** [comment]
@k8s-bot verify test this

**Comment by wongma7** [comment]
Probably we need this in 1.6 too: https://github.com/kubernetes/kubernetes/pull/45861

**Comment by enisoc** [comment]
I'm working on fixing the branch so verify passes.

**Comment by enisoc** [comment]
@k8s-bot verify test this

**Comment by wongma7** [comment]
@k8s-bot kubemark e2e test this

https://github.com/kubernetes/kubernetes/issues/40139

**Comment by wongma7** [comment]
@k8s-bot verify test this
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot kubemark e2e test this
"I0516 16:52:27.451] ServiceException: 409 Bucket kubernetes-release-pull already exists."

**Pull request merged**
