### PR TITLE
unittests: Adds Windows unittests

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug

/sig windows
/sig testing
/priority important-soon
/milestone v1.25

#### What this PR does / why we need it:

Adds unit tests for a few functions that are not covered.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by encodeflush** [comment]
Hi @claudiubelu
Bug triage team here!
It looks like this PR has the pending review.
Just checking in to see if this is still on track for K8s 1.25.

**Comment by marosset** [comment]
/lgtm 
Looks good from SIG-Windows.
Since this mostly adds unit test coverage we should try and get this merged in v1.25 still

**Comment by claudiubelu** [comment]
This PR only affects Windows unit tests. This PR has been included in this PR https://github.com/kubernetes/kubernetes/pull/110981, in which we've ran the ``pull-ci-kubernetes-unit-windows`` job, in which we can see that these tests pass.

**Pull request merged**
