### PR TITLE
when without port specified, the heapster proxy request will fall

### PR DESCRIPTION
**Pull request by mintzhao**
**What this PR does / why we need it**:
I'm testing HPA Resources Metrics, but always got ```"no endpoints available for service \"http:heapster:\""```， so the commit ```// use the first exposed port on the service``` at **k8s.io/kubernetes/pkg/controller/podautoscaler/metrics/legacy_metrics_client.go** is wrong.So I fixed it with default port 80.

**Special notes for your reviewer**:
none

**Release note**:

```release-note
fix HPA legacy metrics client communicate with heapster by add default port 80
```

### CODE REVIEW

**Comment by mintzhao** [comment]
I have a CLA

**Comment by fgrzadkowski** [comment]
That's weird as I think we are using this default configuration. @mwielgus can you please take a look?

**Comment by mintzhao** [comment]
controller-manager communicate with heapster using service through ProxyGet. Is this can work without kube-proxy instance or flannel network on the master node? Based on my testing, It won't work.

**Pull request closed without merging**
