### PR TITLE
kubeadm: Control plane config moved to substructs

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:

In v1alpha3's, control plane component config options were nested directly into the ClusterConfiguration structure. This is cluttering the config structure and makes it hard to maintain. Therefore the control plane config options must be separated into different substructures in order to graduate the format to beta.

This change does the following:

- Introduces a new structure called ControlPlaneComponent, that contains fields common to all control plane component types. These are currently extra args and extra volumes.

- Introduce a new structure called APIServer that contains ControlPlaneComponent and APIServerCertSANs field (from ClusterConfiguration)

- Replace all API Server, Scheduler and Controller Manager options in ClusterConfiguration with APIServer, ControllerManager and Scheduler fields of APIServer and ControlPlaneComponent types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Refs kubernetes/kubeadm#911

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/assign @luxas
/assign @timothysc
/assign @fabriziopandini

This will be followed by a PR that introduces an API server timeout option (as discussed at office hours on Oct 24th.

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: Control plane component configs are separated into ClusterConfiguration sub-structs.
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks @rosti

**Review by fabriziopandini — CHANGES_REQUESTED** [review]
@rosti thanks for this PR!
I have no strong opinion on the usage of a shared struct vs dedicated struct.
Everything else seems ok

Only one question. The Change about HostPathMount.Writable to ReadOnly is going to be addressed in another PR?

**Review by timothysc — APPROVED** [review]
/approve 

LGTM but will defer to @fabriziopandini for final call

**Comment by timothysc** [comment]
This appears to be blocking a number of your other PRs.

**Comment by fabriziopandini** [comment]
@rosti please rebase and then ping me for lgtm

**Pull request merged**
