### PR TITLE
Bump Konnectivity to v0.0.35 in release-1.24

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Supports new metrics, logging improvements, and trivial fixes only (no major changes).

#### Special notes for your reviewer:

Essentially identical to https://github.com/kubernetes/kubernetes/pull/114929

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
