### PR TITLE
use subtest for table units (pkg/scheduler/testing)

### LINKED ISSUE #63267: scheduler: Update tests to use subtest
Go 1.7 added the [subtest feature](https://golang.org/doc/go1.7#testing) which can make table-driven tests much easier to run and debug. Many table-driven tests in `pkg/scheduler` and `test/integration/scheduler` are not using this feature.

As an example, https://github.com/kubernetes/kubernetes/pull/56940 converts some tests to use a sub-benchmark.

Further reading: [Using Subtests and Sub-benchmarks](https://blog.golang.org/subtests)

/kind cleanup
/sig scheduling

### PR DESCRIPTION
**Pull request by xchapter7x**
**What this PR does / why we need it**: Update scheduler's unit table tests to use subtest

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
breaks up PR: https://github.com/kubernetes/kubernetes/pull/63281
/ref #63267

**Release note**:

```release-note
This PR will leverage subtests on the existing table tests for the scheduler units.
Some refactoring of error/status messages and functions to align with new approach.

```

### CODE REVIEW

**Comment by misterikkit** [comment]
This one frightens me. I think we need to take a harder look at this package in general.

**Comment by xchapter7x** [comment]
@misterikkit , 
Could you unpack the comments on what frightens you?
Is it the attempts in the commit to DRY up the test and the table set or is there something pre-existing and more fundamental about the tests that are concerning to you?

**Comment by misterikkit** [comment]
> Could you unpack the comments on what frightens you?

I think all of these seemed like code smells to me,
- use of the `TestGroup` type
- global called `Test` of that type
- local variables called `TestGroup` copying the value of `Test`
- nontrivial `init()` in util.go

Given that, the test names being generated did not seem descriptive. Putting a loop index in the name almost defeats the purpose, and the group version is not unique.

**Pull request closed without merging**
