### PR TITLE
Fix kubectl create secret docker-registry --from-file

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:
The logic for flag validation is moved to:https://github.com/kubernetes/kubernetes/blob/7937aa60a3dcc2d447e06847ae68fe1d9319630c/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret.go#L210-L218
after this [PR](https://github.com/kubernetes/kubernetes/pull/60806).

So these two lines of code is duplicated.

If we still mark `docker-username` and `docker-password` as required at begining, then it's not possible to use`--from-file` flag.
Before this PR:
```
[root@master ~]# kubectl create secret docker-registry test --from-file=.dockerconfigjson=docker
Error: required flag(s) "docker-password", "docker-username" not set
```
After this PR:
```
[root@master ~]# ./kubectl create secret docker-registry test --from-file=.dockerconfigjson=docker
secret/test created
```

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/90945

**Special notes for your reviewer**:
/assign @juanvallejo

**Does this PR introduce a user-facing change?**:

```release-note
Fix kubectl create secret docker-registry --from-file not usable
```

### CODE REVIEW

**Comment by mcristina422** [comment]
I think you should add tests similar to https://github.com/kubernetes/kubernetes/blob/5bda0c1b3b3b3f9cbfc65255d7258fe4b441410e/test/cmd/core.sh#L825

**Comment by zhouya0** [comment]
> I think you should add tests similar to
> 
> https://github.com/kubernetes/kubernetes/blob/5bda0c1b3b3b3f9cbfc65255d7258fe4b441410e/test/cmd/core.sh#L825

Great suggestion! Thanks!

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
