### PR TITLE
Fix NFS related CI failures

### PR DESCRIPTION
**Pull request by dims**
xref: https://github.com/kubernetes/kubernetes/issues/123236

it was indeed related to `ulimit` .. `rpc.statd` was failing with `clnt_dg_create: out of memory`

Let's reduce the ulimit to something that used to work well before.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
65536 seems very popular in nfs related code/scripts - https://github.com/search?type=code&q=%2Fulimit+-n+65536%2F+%2Fnfs%2F&p=2

**Comment by jsafrane** [comment]
> it was indeed related to ulimit .. rpc.statd was failing with clnt_dg_create: out of memory

@dims Out of curiosity, where did you see this error?

**Comment by dims** [comment]
@jsafrane kubectl log on nfs-server pod showed the issue. i then kubectl exec'ed into the server pod and tried some of the commands in the run_nfs.sh with different numbers for `ulimit -n` to verify the problem/fix.

**Pull request merged**
