### PR TITLE
fix typo: e.g.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
fix typo: e.g.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
You have several typo pulls:

 1. https://github.com/kubernetes/kubernetes/pull/43904
 1. https://github.com/kubernetes/kubernetes/pull/44708
 1. https://github.com/kubernetes/kubernetes/pull/45327
 1. https://github.com/kubernetes/kubernetes/pull/45395
 1. https://github.com/kubernetes/kubernetes/pull/45592

Can you please combine them into a single pull?

**Comment by rootfs** [comment]
Though I am used to `e.g.`, I am hesitant to say `eg` is a typo. Sources (such as https://en.wiktionary.org/wiki/eg) say `eg` is an alternative form of `e.g.`

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k 
#43904 : I can't solve the test failed. I don't know why.
#44708: I miss cla label. But I signed it.
#45327 : This only one can be gathered.
#45395:  I can't solve the test failed. I don't know why.
#45592: The latest one I pull request.
In fact, that's all.

**Comment by zhangxiaoyu-zidif** [comment]
@rootfs Thanks, I will close it and meanwhile I will close all the related typo PRs.

**Comment by zhangxiaoyu-zidif** [comment]
@rootfs I do not use wik-dict yet.
I use https://www.merriam-webster.com/dictionary/Eg instead. I think merriam-webster would be much more professional.

**Pull request closed without merging**
