### PR TITLE
Replace all deprecated rolling-update command by rollingupdate

### PR DESCRIPTION
**Pull request by etiennetremel**
Replace all deprecated rolling-update command by rollingupdate in the documentation, commented code and example.

### CODE REVIEW

**Comment by etiennetremel** [comment]
I signed it!

**Comment by bgrant0607** [comment]
Thank you for the PR, but actually it's rollingupdate that was deprecated. rolling-update was just added. Is the deprecation message wrong or confusing? Could you paste the text here that made you think that rolling-update was deprecated?

@ghodss

**Comment by bgrant0607** [comment]
Note the comment in pkg/kubectl/cmd/rollingupdate.go at line 50:
```
// rollingupdate is deprecated.
```

**Comment by ghodss** [comment]
Also at line 68:

```
	if os.Args[1] == "rollingupdate" {
		printDeprecationWarning("rolling-update", "rollingupdate")
	}
```

**Comment by bgrant0607** [comment]
Yes, the deprecation message looks right to me.

**Comment by etiennetremel** [comment]
Hum..  ok, I was seeing this message when using the kubectl command, maybe I was using an older version of the build. Thanks, I'm closing the PR :)

**Pull request closed without merging**
