### PR TITLE
Move resource quota doc from user-guide to admin

### PR DESCRIPTION
**Pull request by derekwaynecarr**
`ResourceQuota` is an administrative concern and should be in admin section.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@kubernetes/goog-ux

**Comment by bgrant0607** [comment]
Thanks. I agree this makes sense.

@RichieEscarez Do we need to worry about forwarding links/references, such as by leaving a page with a link to the new one?

**Comment by bgrant0607** [comment]
Did you check whether the examples test or other tests referenced this?

**Comment by bgrant0607** [comment]
Yeah, examples_test failed -- see Shippable results.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - updated examples_test, was just letting Shippable tell me if there was an error ;-)

**Comment by RichieEscarez** [comment]
Yes, we need to redirect them and I think creating/leaving a page in its previous spot with a pointer to where it has moved is our only** option right now (for the version that gets published in Github Pages). 

ie. "This page has moved to: *url_here*"

** *Github pages does have a [redirect feature/gem](https://help.github.com/articles/redirects-on-github-pages/) that can be added to a site, but I dont think we can use it because our front matter (a template that includes only the layout and title) is added to our files with a script.*

**Comment by derekwaynecarr** [comment]
@RichieEscarez @bgrant0607 - updated the PR and left a breadcrumb per guidance to the new location.

**Comment by RichieEscarez** [comment]
LGTM. I think the commits need to be squashed though, right @bgrant0607?

**Comment by derekwaynecarr** [comment]
@RichieEscarez - I need separate commits because when I squashed git got confused by the mv and deleted my placeholder.

**Pull request merged**
