### PR TITLE
embed DRA test manifests in conformance binary

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

DRA e2e tests using the conformance container image currently fail with an error like this:
```
    [FAILED] reading manifest file: Test file "test/e2e/testing-manifests/dra/dra-test-driver-proxy.yaml" was not found.
    The following files are embedded into the test executable:
        test/e2e/testing-manifests/cluster-dns/dns-backend-rc.yaml
        ...
        test/e2e/testing-manifests/flexvolume/attachable-with-long-mount
        ...
        test/e2e/testing-manifests/guestbook/agnhost-primary-deployment.yaml.in
        ...
```

This PR adds the test manifests defined at https://github.com/nojnhuh/kubernetes/tree/523c88b33d1bb6c3b660fafc6930697f9287b961/test/e2e/testing-manifests/dra to compiled conformance test binaries in order to run DRA tests with the conformance container image.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

I've done some local testing using CAPZ that shows this change works as expected.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

There's a fallback which loads non-embedded files. That's how it worked before.

**Comment by nojnhuh** [comment]
Thanks @pohly! Is this a change that's fair to cherry-pick to the release-1.31 branch?

**Comment by pohly** [comment]
Probably not. I've tried cherry-picking fixes for DRA to 1.31 and was (correctly) pointed towards the cherry-pick guidelines which explicitly call out alpha features as not eligible for backporting.

**Comment by nojnhuh** [comment]
Makes sense, thanks!

**Pull request merged**
