### PR TITLE
ResourceQuota add object count support for secret and volume claims

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Since the introduce of a ResourceQuota, two new namespace scoped objects were added.

This PR supports limiting the total number of secrets and volume claims that a namespace may have.

/cc @markturansky @pmorie

### CODE REVIEW

**Comment by markturansky** [comment]
LGTM wrt PVC.  Thanks for adding this.  I had a follow-up task to do this.

I see this limits the number of volumes a namespace can have.  Would this be the appropriate place to also restrict the size of volumes a user can have?

**Comment by pmorie** [comment]
@markturansky I believe this doesn't impose a limitation on the number of PVs a namespace can have a priori, just adds some examples of how to do it.  @derekwaynecarr correct me if I'm wrong.

LGTM re: secrets

**Comment by derekwaynecarr** [comment]
We need to add support for computing aggregate storage on ResourceQuota the way we do for CPU and memory. 

We also should have the ability on a LimitRange to restrict the size of a volume a claim can reference.  

Restricting the count is easier hence the quick PR here.  The other are for you to follow up and I can assist.

**Comment by derekwaynecarr** [comment]
@pmorie - Correct.  Just gives a namespace administrator ability to limit the number of secrets to X and volume claims to Y in a particular namespace.

**Comment by markturansky** [comment]
@derekwaynecarr thanks for the clarification.  I will follow up with you on those tasks.

**Comment by brendandburns** [comment]
@derekwaynecarr needs rebase, then I'm happy to merge.

**Comment by derekwaynecarr** [comment]
@brendandburns - rebased now.  should be good to merge.

**Comment by derekwaynecarr** [comment]
rebased on latest and travis is happy again.

**Pull request merged**
