### PR TITLE
fixed typo in cockroachdb-statefulset.yaml

### PR DESCRIPTION
**Pull request by caarlos0**
**What this PR does / why we need it**:

typo, the syntax was invalid.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by a-robinson** [comment]
Thanks @caarlos0! Looks like a mistake from https://github.com/kubernetes/kubernetes/pull/45322, so cc @gyliu513.

/lgtm

@k8s-bot ok to test

**Comment by gyliu513** [comment]
Thanks @caarlos0! /lgtm

**Pull request merged**
