### PR TITLE
Promote no-longer flaky tests to gce suite

### PR DESCRIPTION
**Pull request by wojtek-t**
cc @quinton-hoole @ixdy @davidopp

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @gmarek

**Comment by wojtek-t** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
Ah, I wasn't here yet in my email and you didn't reference the bug. 

But no, #10720. Flaky test still flaky.

**Comment by zmerlynn** [comment]
Nor did you, as I asked in the original commit, CC me to take it off the GKE list.

**Comment by wojtek-t** [comment]
@zmerlynn - sorry I missed the fact that should cc-ed you. Sorry for that.

Regarding flakiness - yes you're right it's still flaky.

@gmarek - since you wrote this test, can you please take a look?

**Comment by zmerlynn** [comment]
@wojtek-t: No worries, it was buried in a random commit comment and not necessarily easy to see in "git blame". Not sure there's an easy way to broadcast, and we just need to move the GKE config in there, too.

**Comment by wojtek-t** [comment]
Rebased - PTAL

**Comment by wojtek-t** [comment]
Tests on Jenkins didn't started - I'm rerunning them now.

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by davidopp** [comment]
@wojtek-t can you clarify whether you think these tests are still flaky? Your last comment was "Regarding flakiness - yes you're right it's still flaky."

**Comment by wojtek-t** [comment]
@davidopp - sorry, this comment was about MaxPods which I initially also wanted move out of flaky. However, since it's still flaky, we should leave it.
So I'm only moving "Addon" test to non-flaky (the Nodes network partition is not catching any test :P)

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
