### PR TITLE
Replace the ioutil by the os and io for the pkg/util

### PR DESCRIPTION
**Pull request by saltbo**
Signed-off-by: saltbo <saltbo@foxmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #None 

#100367

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by pacoxu** [comment]
The unit test case below needs an update. 
https://github.com/kubernetes/kubernetes/blob/140502af8cbe4de0b78265f4ba025a5ada805849/pkg/kubelet/kubeletconfig/checkpoint/store/fsstore_test.go#L653-L654
/hold

**Comment by saltbo** [comment]
I want to join the k8s org, can you sponsor me?  @pacoxu @thockin

**Pull request merged**
