### PR TITLE
Remove 0,1,3 from rand.String to avoid 'bad words'

### LINKED ISSUE #49543: Pod suffix is b0110ck5
/kind feature

**What happened**:

In playing with the nginx ingress controller deployment, I noticed the following pod name:
nginx-ingress-controller-1449474453-c0ck5
I figure we should possibly put something in place to prevent accidental l33t profanity ;-).

**What you expected to happen**:

The following pod name:
nginx-ingress-controller-1449474453-r0ck5

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

Remove 0,1,3 from the runes to prevent accidental bad words profanity

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49543

**Special notes for your reviewer**:
/cc @mml  @jamesawebb1  @spiffxp 

**Release note**:

```release-note
Remove 0,1,3 from rand.String, to avoid 'bad words'
```

### CODE REVIEW

**Comment by deads2k** [comment]
I feel like I should require a good story every time someone wants to remove items from the list.  The "I was demo-ing to customer X and this one popped up" must be awesome.

**Comment by dixudx** [comment]
@deads2k Because it generated some offensive string like `nginx-ingress-controller-1449474453-c0ck5`.

**Comment by mml** [comment]
/lgtm

Thanks!

**Comment by deads2k** [comment]
> @deads2k Because it generated some offensive string like nginx-ingress-controller-1449474453-c0ck5.

Heh.  That's an unlucky demo. :)

/approve

**Comment by tedyu** [comment]
@dixudx 
Can you show me a bad string consisting of '3' ?

Thanks

**Comment by tedyu** [comment]
@dixudx @liggitt 
I plan to open PR which brings '3' back into the alphanums string.

**Comment by mml** [comment]
@tedyu see https://github.com/kubernetes/kubernetes/issues/49543#issuecomment-319813522

**Comment by tedyu** [comment]
@mml
I don't see bad word example in that comment.

**Comment by liggitt** [comment]
> I don't see bad word example in that comment.

"3xt3nd" was an example of how the number 3 makes words readable as english.

> We should also be aware of performance implication w.r.t. removal of digits.

has that been demonstrated to be a problematic hotspot in a profile?

**Comment by 2rs2ts** [comment]
Sorry to necro this. I was wondering if we should also remove `4`, since that's often used as a substitute for `A` in leetspeak, in the same way that `0` subs for `O`, `1` for `I`, and `3` for `E`. I was going to open an issue about this instead, but it didn't seem like it fit into any of the issue categories (not a bug, there's no KEP for it, etc...)

**Pull request merged**
