### PR TITLE
Added the missing exception handling

### PR DESCRIPTION
**Pull request by dipankardas011**
test
|---e2e_node
|     |---gcp
|     |     |----gke_environment_test.go
|     |     |

Signed-off-by: DipankarDas <dipsonu10@hotmail.com>

#### What this PR does / why we need it:

it is having an unhandled exception 

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by dipankardas011** [comment]
Nothing of that sort, just thought that exception handling might be needed / it is missing in that place

**Comment by SergeyKanzhelev** [comment]
/close 

this is a trivial change https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits and common pattern in many other places.

**Comment by SergeyKanzhelev** [comment]
thank you for your contribution, please consider looking in active issues to find idea for the next contribution

**Comment by dipankardas011** [comment]
Okay, thank you for your time

**Pull request closed without merging**
