### PR TITLE
Cherry pick: Remove gcloud components update from e2e.sh

### PR DESCRIPTION
**Pull request by spxtr**
#18846

### CODE REVIEW

**Comment by spxtr** [comment]
Reassigned since @jlowdermilk is out. This is a cherry pick of #18897.

**Comment by ihmccreery** [comment]
LGTM.

**Comment by spxtr** [comment]
@k8s-bot test this please

**Comment by spxtr** [comment]
@k8s-bot e2e test this please

**Comment by spxtr** [comment]
Five failures! Something is very wrong with PR Jenkins if it's so consistently failing e2e tests.

**Comment by spxtr** [comment]
@k8s-bot e2e test this please

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
```
07:38:08 Summarizing 3 Failures:
07:38:08 
07:38:08 [Fail] DNS [AfterEach] should provide DNS for services 
07:38:08 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:93
07:38:08 
07:38:08 [Fail] PreStop [AfterEach] should call prestop when killing a pod 
07:38:08 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:93
07:38:08 
07:38:08 [Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
07:38:08 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69
```

**Comment by spxtr** [comment]
Very likely flakes.

@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by spxtr** [comment]
This PR shouldn't affect e2e tests at all. The fact that it's reliably failing on 1.0 indicates that something bad is going on.

@k8s-bot e2e test this again please

**Comment by wojtek-t** [comment]
I agree - we had exactly the same problems when we were cherry-picking something else to 1.0 branch.
Merging manually.

**Pull request merged**
