### PR TITLE
Up timeout for gke-reboot; fixes #19539

### LINKED ISSUE #19539: kubernetes-e2e-gke-ci-reboot timing out
Will up the timeout; looks like it was probably caused by #19513.

### PR DESCRIPTION
**Pull request by ikehz**
cc @k8s-oncall

### CODE REVIEW

**Comment by ihmccreery** [comment]
Fixes #19539

**Comment by spxtr** [comment]
Any idea why it's taking 15 minutes longer than usual lately?

**Comment by lavalamp** [comment]
@spxtr What are you referring to?

**Comment by spxtr** [comment]
The last few successful runs looked like they were taking an hour and 40 minutes ish. Is it just general GKE latency that drove it up to two hours?

**Comment by lavalamp** [comment]
Ah, yeah, I'm not sure. I'm trying to figure out why gce-parallel is broken right now...

**Pull request merged**
