### PR TITLE
Revert 109706 + 111691

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

This reverts #109706 and #111691 which caused https://github.com/kubernetes/kubernetes/issues/112793

A fix PR is up (#112798), but this part of Kube is...well, complicated and does not have a very broad set of E2E tests. So doubts are expressed as to how exhaustive the fix really is, hence why this PR is up. 

#### Which issue(s) this PR fixes:

Fixes #112798

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.25 regression syncing load balancers for ExternalTrafficPolicy=Local incorrectly under certain conditions by reverting https://github.com/kubernetes/kubernetes/pull/109706 and https://github.com/kubernetes/kubernetes/pull/111691 which caused https://github.com/kubernetes/kubernetes/issues/112793.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @thockin 
/cc @swetharepakula 
/cc @panslava

### CODE REVIEW

**Comment by swetharepakula** [comment]
/lgtm

Thanks for making the PR so quickly!

/cc @bowei @liggitt

**Comment by panslava** [comment]
/lgtm

Thank you for really quick involvement on this!

**Comment by liggitt** [comment]
lgtm (I verified this takes the sync logic of this controller back to 1.24-state)

will defer to @bowei @thockin for approval

**Comment by thockin** [comment]
Sorry to lose this from the release, but I concur

/lgtm
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
the commits this is reverting in release-1.25 never got reverted in master ... can you link to the later commits in master that resolved this issue?

**Comment by alexanderConstantinescu** [comment]
> can you link to the later commits in master that resolved this issue?

This merged on 1.26 during the feature cycle and fixed the bug: https://github.com/kubernetes/kubernetes/pull/111663

**Pull request merged**
