### PR TITLE
Add j-griffith as cinder reviewer

### PR DESCRIPTION
**Pull request by j-griffith**
Volunteering to help out here, happy to approve as
well after I've been around for a while.

**Adds j-griffith to reviewers for Cinder**:

### CODE REVIEW

**Comment by j-griffith** [comment]
Just signed the CLA

**Comment by jsafrane** [comment]
I really appreciate a new volunteer, especially former Cinder lead. Should be a new owner also member of Kubernetes organization first?

https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by rootfs** [comment]
@j-griffith need rebase

**Pull request closed without merging**
