### PR TITLE
Add short name "netpol" for networkpolicies

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Add short name for `networkpolicies` in kubectl command for good user experience.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None

**Special notes for your reviewer**:
None

**Release note**:

```release-note
Add short name "netpol" for networkpolicies
```

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/sig-cli-api-reviews

**Comment by kargakis** [comment]
@kubernetes/sig-network-api-reviews

**Comment by xiangpengzhao** [comment]
Thanks @kargakis !

Should we also add short names for other resources e.g. `clusterrolebindings` ?

```
    * certificatesigningrequests (aka 'csr')
    * clusters (valid only for federation apiservers)
    * clusterrolebindings
    * clusterroles
    * componentstatuses (aka 'cs')
    * configmaps (aka 'cm')
    * daemonsets (aka 'ds')
    * deployments (aka 'deploy')
    * endpoints (aka 'ep')
    * events (aka 'ev')
    * horizontalpodautoscalers (aka 'hpa')
    * ingresses (aka 'ing')
    * jobs
    * limitranges (aka 'limits')
    * namespaces (aka 'ns')
    * networkpolicies (aka 'np')
    * nodes (aka 'no')
    * persistentvolumeclaims (aka 'pvc')
    * persistentvolumes (aka 'pv')
    * pods (aka 'po')
    * poddisruptionbudgets (aka 'pdb')
    * podsecuritypolicies (aka 'psp')
    * podtemplates
    * replicasets (aka 'rs')
    * replicationcontrollers (aka 'rc')
    * resourcequotas (aka 'quota')
    * rolebindings
    * roles
    * secrets
    * serviceaccounts (aka 'sa')
    * services (aka 'svc')
    * statefulsets
    * storageclasses
    * thirdpartyresources
```

**Comment by xiangpengzhao** [comment]
Oh, just find @gyliu513 posted an issue talking about short names for some other resources https://github.com/kubernetes/kubernetes/issues/42129

Guangya, are you working on these resources?

**Comment by gyliu513** [comment]
@xiangpengzhao I think that you can cover all of those issues here, I will try to close my issue if you can cover all of the short names, comments?

Just some proposal for short names

```
    * statefulsets  (aka 'ss')
    * storageclasses  (aka 'sc')
    * thirdpartyresources  (aka 'tpr')
```

**Comment by kargakis** [comment]
StatefulSet alias is being discussed in https://github.com/kubernetes/kubernetes/pull/37099

**Comment by thockin** [comment]
@smarterclayton There was some concern about new shortcut names - what's the current thinking?

**Comment by smarterclayton** [comment]
Just that we be very judicious and actually think through how often they will be used, because they become part of the public CLI API (can't change them without breaking scripts).  Any time we still a two letter alias, we are preventing ourselves from using it in the future.  The bar for getting an alias is inversely proportional to how long it is and how often it is used (we shouldn't add short aliases for rarely used classes).

Most cluster scoped resources aren't going to be accessed that often.  We have tab completion, so I'd lean towards no shortcut for rarely accessed resources.

**Comment by thockin** [comment]
I agree.  NetworkPolicy is long and unwieldy and user-facing (namespaced).
 "np" is pretty short.  What about netpol ?

**Comment by xiangpengzhao** [comment]
From a user's perspective, my first reaction is thinking the first letters of the full name of a resource as its shortcut name. If using `netpol` or something else, users may have to try several times to find the right shortcut:) On the other hand, using `np` will keep the same style with the most existing shortcuts.

**Comment by smarterclayton** [comment]
How many users will ever type np often enough to need the shortcut?  If we
measured the number of times various resources are used, I'd be willing to
bet that it's a long tail like:

pods
replication controllers
replica sets
deployments
services
persistent volume claims
secrets
configmap
namespace
.... a gap
nodes
.... a very large gap
everything else

**Comment by xiangpengzhao** [comment]
Reasonable. These resources are indeed not used so often. Then should we close this PR or just merge it and leave other resources without shortcuts as they are now?

**Comment by thockin** [comment]
I would be OK with netpol, but np is too vague.

**Comment by xiangpengzhao** [comment]
Addressed, but not sure if it's still necessary to merge this according to @smarterclayton 's reason :)

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
@k8s-bot gci gce e2e test this

**Comment by kargakis** [comment]
@k8s-bot cvm gce e2e test this https://github.com/kubernetes/kubernetes/issues/43466

**Pull request merged**
