### PR TITLE
Fixes to get AWS tests to run

### PR DESCRIPTION
**Pull request by justinsb**
They don't pass (yet), but they at least run!

There are actually a number of fixes in here; LMK if I should split these out.

It's definitely not complete - e.g. the gcloud ssh line is still in there!

### CODE REVIEW

**Comment by roberthbailey** [comment]
Justin, it looks like this PR needs a rebase.

**Comment by zmerlynn** [comment]
I'll shepherd this for now.

**Comment by justinsb** [comment]
Thanks ... rebasing right now

**Comment by brendandburns** [comment]
LGTM, looks like this got dropped.  I kicked Travis again.  When it's green, I'll merge.

**Pull request merged**
