### PR TITLE
Fix device plugin re-registration

### LINKED ISSUE #62773: [deviceplugin] allocatable resource remains 0 after device-plugin restart
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig node

**What happened**:
i register device by my deviceplugin. It works good. Then i stopmy plugin, k8s mark resources Unhealthy as expect. But when i restart plugin. The resource does not recover, remain allocatable  0.

**What you expected to happen**:
Resource turns healthy when plugin restart.

**How to reproduce it (as minimally and precisely as possible)**:
1. start k8s
2. start device plugin
3. stop device plugin
4. restart device plugin

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
While registering a new endpoint, device manager copies all the devices from the old endpoint for the same resource and then it stops the old endpoint and starts the new endpoint.

There is no sync between stopping the old and starting the new. While stopping the old, manager marks devices(which are copied to new endpoint as well) as "Unhealthy".

In the endpoint.go, when after restart, plugin reports devices healthy, same health state (healthy) is found  in the endpoint database and endpoint module does not update manager database.

Solution in the PR is to mark devices as unhealthy before copying to new endpoint. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62773

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix issue where on re-registration of device plugin, `allocatable` was not getting updated. This issue makes devices invisible to the Kubelet if device plugin restarts. Only work-around, if this fix is not there, is to restart the kubelet and then start device plugin.
```
/cc @jiayingz @vishh @RenaudWasTaken @derekwaynecarr

### CODE REVIEW

**Comment by RenaudWasTaken** [comment]
Sorry I didn't have a lot of time to look at this issue in detail.

Looking a bit more at the code it seems to me like the "device state" and "API server state" are not really separated which leads in this case to working on the "device state" to fix an "API server state" issue.

"device state" = devices stored in the endpoint
"API server state" = devices stored in the manager which will be fed to the API server in Capacity and Allocatable

What do you think if we fixed the issue as following:
- When creating an endpoint use the devices from the "API server state" (devices will necessarily be in Unhealthy state if the endpoint was lost)
- Move the "stop time" to the "API server state"
- Make the endpoint's lifetime be as short as the gRPC connection

**Comment by vikaschoudhary16** [comment]
> Make the endpoint's lifetime be as short as the gRPC connection

can you please explain more this point?

**Comment by RenaudWasTaken** [comment]
Instead of keeping the endpoint around when its gRPC connection is closed you delete it.
The data needed later should be kept and retrieved from the "API server state"

**Pull request merged**
