### PR TITLE
Show labels information when kubectl describe ingress

### LINKED ISSUE #103808: When kubectl describe ingress, there is no information about labels
#### What happened:
When command 'kubectl describe ing'

-----------------------------------------
Name:             test-ing
Namespace:        practice
Address:          10.10.01.10
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  test terminates
Rules:
  Host                             Path  Backends
  ----                             ----  --------
  test.test-testpractice.com
                                   /   test-svc:80 (<none>)
Annotations:                       kubernetes.io/ingress.class: nginx
Events:                            <none>

----------------------------------------

Result has no information about labels. 

But Pod, Deployment, Service resources has label information like below.

----------------------------------------
Name:         test-room-test-mjsbz
Namespace:    test
Priority:     0
Node:         aks-test-test-test/22.22.222.
Start Time:   Fri, 09 Jul 2021 05:45:26 +0000
Labels:       app=test
                  pod-template-hash=test
                  role=mediatest
---------------------------------------

Why ingress has no information about labels? 
Actually when delete ingresss with labels is working correctly.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18.14
- Cloud provider or hardware configuration: AKS (Azure)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig

### PR DESCRIPTION
**Pull request by kabab**
#### What type of PR is this?
/king bug

#### What this PR does / why we need it:
display information about labels when kubectl describe ingress

#### Which issue(s) this PR fixes:
Fixes #103808 

```release-note
Display Labels when kubectl describe ingress
```

### CODE REVIEW

**Review by brianpursley — CHANGES_REQUESTED** [review]
Can you create a unit test for ingress with labels, or change one of the existing to include labels?

**Comment by kabab** [comment]
@brianpursley I've updated an existing test to include Labels, thanks

**Comment by rikatz** [comment]
/priority backlog
@brianpursley from my side lgtm :) (also the tests!)

/lgtm

**Review by brianpursley — APPROVED** [review]

**Comment by eddiezane** [comment]
Do we want to add annotations as well? Looks like a mixed bag of what resource outputs what.

**Comment by kabab** [comment]
@eddiezane annotations already exist I think.

**Comment by eddiezane** [comment]
> @eddiezane annotations already exist I think.

You're right! It's further down.

Thanks for the PR!

/approve

**Pull request merged**
