### PR TITLE
Automated cherry pick of #62465 upstream release 1.10 

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #62465 on release-1.10.
#62465 : Fix PodStore to wait for being initialized

### CODE REVIEW

**Comment by wojtek-t** [comment]
@krzyzacy - why that doesn't consider me as a top-level owner for this repo?

**Comment by krzyzacy** [comment]
cc @cjwagner for the approval question

**Comment by cjwagner** [comment]
@wojtek-t The top level OWNERS file isn't valid yaml right now and can't be parsed. Fix is here: https://github.com/kubernetes/kubernetes/pull/62555

**Pull request merged**
