### PR TITLE
obselete SecurityContextDeny related code

### PR DESCRIPTION
**Pull request by tukwila**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR delete all SecurityContextDeny admission plugin related functions and tests because it's going to be removed.  See https://github.com/kubernetes/kubernetes/issues/111516.
https://github.com/kubernetes/test-infra/pull/29361

#### Which issue(s) this PR fixes:

This is step two of https://github.com/kubernetes/kubernetes/issues/111516.

#### Does this PR introduce a user-facing change?

```
The SecurityContextDeny admission plugin is going deprecated and will be removed in future versions.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
- [KEP]: https://github.com/kubernetes/enhancements/issues/3785
- [Other doc]: https://k8s.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny
- [Issue]: https://github.com/kubernetes/kubernetes/issues/111516
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@tukwila can you please fix tests

**Comment by tukwila** [comment]
> @tukwila please fix CI failures, thanks.
> 
> `SecurityContextDeny` is used in the [sig-autoscaling jobs](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes/sig-autoscaling) in the test-infra repo. Should we remove it from there first?

Answer: yes, I have submitted PR as well, please see https://github.com/kubernetes/test-infra/pull/29361

**Pull request closed without merging**
