### PR TITLE
Use native Ginkgo test runner instead of cmd/e2e (attempt N)

### PR DESCRIPTION
**Pull request by ixdy**
I kept my fixes for Go 1.3 and OS X in a separate commit from the revert commit so that you can see what changed. I can squash the two commits if desired.

I will run `hack/e2e-from-release.sh` using both the go:1.3 and go:1.4 docker images to verify that it works properly in both places. I don't have an OS X machine handy, but the change I originally introduced which broke OS X has been reverted.

cc @quinton-hoole @zmerlynn

### CODE REVIEW

**Comment by ixdy** [comment]
The Elasticsearch test failed on Go 1.3, but that's a known flaky test. Everything else otherwise passed.

Testing Go 1.4 now.

**Comment by zmerlynn** [comment]
LGTM

**Comment by quinton-hoole** [comment]
It's not at all clear to me what's been changed relative to the previous unsuccessful attempts and why, but I'm OK with getting this working correctly locally and on Jenkins, and then doing a second cleanup pass, as part of #8321 

LGTM, can merge once test against go 1.4 is confirmed a success.

**Comment by ixdy** [comment]
https://github.com/ixdy/kubernetes/commit/35c4b92e92d14d9479296b831d098ba1aed3a2b7 shows the changes vs. last Friday's attempt.

**Comment by ixdy** [comment]
All e2e tests passed on Go 1.4.

**Pull request merged**
