### PR TITLE
convert deployment controller to shared informers

### LINKED ISSUE #27687: Deployment controller should deep-copy before mutating its caches
Right now the deployment controller mutates both replica sets and pods from its caches. It should deep-copy before mutating, otherwise it should not use shared caches.

@kubernetes/deployment

### PR DESCRIPTION
**Pull request by deads2k**
Converts the deployment controller to shared informers.

@kargakis I think you've been in here.  Pretty straight forward swap.

Fixes #27687

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34349)

### CODE REVIEW

**Comment by kargakis** [comment]
You need to make sure [LabelPodsWithHash](https://github.com/kubernetes/kubernetes/blob/160adc38649f61d9db397163c4ee4bc03cc41de0/pkg/controller/deployment/sync.go#L180) deep-copies before it will mutate pods.

https://github.com/kubernetes/kubernetes/blob/160adc38649f61d9db397163c4ee4bc03cc41de0/pkg/controller/deployment/util/deployment_util.go#L580

**Comment by krmayankk** [comment]
@deads2k what does this change mean ? Why is this needed ? Does this fix a bug ?

**Comment by deads2k** [comment]
> @deads2k what does this change mean ? Why is this needed ? Does this fix a bug ?

It collapses the code down to a shared cache which reduces CPU both controller and API server-side by eliminating extra list/watches and their associated deserialization/serialization on the server and extra deserialization controller-side.

**Comment by kargakis** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/27687

**Comment by deads2k** [comment]
@kargakis I think it actually does a live lookup before mutation: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/pod/pod.go#L51

**Comment by deads2k** [comment]
Along with always waiting before taking action, not using a "normal" backoff to avoid re-colliding with other controllers, avoiding re-use of an already watched cache.....

**Comment by deads2k** [comment]
@kargakis found https://github.com/kubernetes/kubernetes/issues/34458 on my to passing tests.  Any other comments on this one?

**Comment by kargakis** [comment]
Open an issue about fixing the pod utility so I won't forget about it.

This LGTM, thanks

**Pull request merged**
