### PR TITLE
fix: function name typos

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
function name typos

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @alexzielenski 
Alex could you take a look? Thanks
/triage accepted

**Review by alexzielenski — APPROVED** [review]
```dropMatchLabelKeysFieldInPodAff(i)nityTerm```

took me a second to see it

/lgtm

**Pull request closed without merging**
