### PR TITLE
Mark reason for lint errors about generated code

### PR DESCRIPTION
**Pull request by lianghao208**
Mark reason for lint errors in:
pkg/controller/nodelifecycle/config/v1alpha1,
pkg/controller/podautoscaler/config/v1alpha1,
pkg/controller/nodeipam/config/v1alpha1

because those underscores are automatically generated.
I closed [PR#95606](https://github.com/kubernetes/kubernetes/pull/95606) and open this new PR because of the commit issue.

**What type of PR is this?**
/kind cleanup

**Which issue(s) this PR fixes**:

Fixes [#68026](https://github.com/kubernetes/kubernetes/issues/68026)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lianghao208** [comment]
@MHBauer 
I added a mention that these underscores are automatically generated from gengo in commit comments.

**Comment by lianghao208** [comment]
Hi, @MHBauer 
 What else can I do to get this PR merged? Since this PR has been opened for a long time. Any suggetions?

**Comment by ehashman** [comment]
@lianghao208 adding these comments is good, but fixing the actual linting errors would be higher priority, and is more likely to receive approver attention :)

**Pull request closed without merging**
