### PR TITLE
Promote e2e verifying service update from one type to another

### PR DESCRIPTION
**Pull request by mgdevstack**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Promotes following e2e to Conformance as they veify important functional behavior of changing service from one type to another and ability to expose same service port for different protocol for a NodePort type service -

1. [sig-network] Services should be able to update NodePorts with two same port numbers but different protocols
2. [sig-network] Services should be able to change the type from ExternalName to NodePort
3. [sig-network] Services should be able to change the type from ClusterIP to ExternalName
4. [sig-network] Services should be able to change the type from NodePort to ExternalName

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
- All above e2e has execution time ~6.410 seconds.
- No flakes found on `Kind` cluster. (Testgrid flake links would be added in comment after few days of observation)

**Does this PR introduce a user-facing change?**:

```release-note
None
```
/area conformance
/sig testing
@kubernetes/sig-node-pr-reviews
@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg

### CODE REVIEW

**Comment by mgdevstack** [comment]
Tracking this PR under: https://github.com/kubernetes/kubernetes/issues/76345

**Comment by bclau** [comment]
Those tests are not even creating pods, so basically it's a noop for Windows anyways. LGTM.

**Comment by johnbelamaric** [comment]
/lgtm

These are OK, they test the API and validate there are no errors. Ultimately we should also be testing whether those service types actually function as intended, rather than just that the API returned no errors. But this adds some additional coverage immediately.

**Comment by mgdevstack** [comment]
My apologies to the reviewers. My mistake, I ran branch deletion command which led to closing the PR.

**Pull request closed without merging**
