### PR TITLE
Transition "e2e/common/runtime.go" table based tests to individual tests

### LINKED ISSUE #68339: Failure to promote non-string-literal e2e tests to Conformance
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Table-based e2e tests are not getting updated to [golden conformance list](https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.txt) leading to the following error- ( mentioned in https://github.com/kubernetes/kubernetes/pull/67612#issuecomment-418616392)
```
INFO: From Listing all conformance tests. //test/conformance:list_conformance_tests:
ERROR at test/e2e/common/runtime.go:232:29: framework.ConformanceIt() called with non-literal argument
ERROR: non-literal argument &{0xc42038d2e0 9790 [0xc42038d300 0xc42038d360] 0 9858} at test/e2e/common/runtime.go:232:29
ERROR at test/e2e/common/runtime.go:355:29: framework.ConformanceIt() called with non-literal argument
ERROR: non-literal argument &{0xc42038b7a0 17397 + 0xc42038b7c0} at test/e2e/common/runtime.go:355:29
Target //test/conformance:list_conformance_tests up-to-date:
  bazel-genfiles/test/conformance/conformance.txt
INFO: Elapsed time: 11.206s, Critical Path: 10.55s
```
framework.ConformanceIt() requires the first parameter to be `string literal` and [table based e2e tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L204) are associated with `string formation` at runtime based on different cases/test-scenarios.

**What you expected to happen**:
Either disapprove the use of table-based e2e tests or suggestion on an alternative approach to add such tests to Conformance.

**How to reproduce it (as minimally and precisely as possible):**
1. Add framework.ConformanceIt() to [table-based e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L204).
2. Run ```bazel build //test/conformance:list_conformance_tests```

/area conformance
@kubernetes/sig-testing
cc @brahmaroutu

### PR DESCRIPTION
**Pull request by mgdevstack**
**What type of PR is this?**
/kind cleanup
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind design
> /kind cleanup
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Transition "e2e/common/runtime.go" table based tests into individual tests.

Table based tests could not be promoted to Conformance suite due to [use of non-string literal ](https://github.com/kubernetes/kubernetes/issues/68339) inside `It()` context. In order to overcome this issue, [these approaches](https://github.com/kubernetes/kubernetes/issues/68339#issuecomment-423678023) can be followed. To move forward a PR #69414 is filed which allows adding table based tests to Conformance golden list but it [seems](https://github.com/kubernetes/kubernetes/pull/69414#issuecomment-428261172) more easy and convenient way to transition table based tests to individual tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68339

**Special notes for your reviewer**:
Hope transitioning these table based tests to individual tests are more efficient than including them inside single It() context as they are verifying TerminationMesaages and Container Image Pull feature for different user scenarios.

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```
/sig testing
/area conformance

### CODE REVIEW

**Comment by mgdevstack** [comment]
Very strangely code execution is failing under "pull-kubernetes-node-e2e" job. 

**_Expected Behaviour:_**
Container's Termination Message MUST match "Done" with expected value "Done" _without newline_  when Pod is in failing state ([Ref](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L175))
Note: On local cluster test case executes successfully with [this commit](https://github.com/kubernetes/kubernetes/commit/18955111db6ab843859e981b356e761fe811f24f#diff-0dc16dc0a015699e53bda03495adc49eR171) but failing for "pull-kubernetes-node-e2e" expecting "Done\n"
Test execution output on local cluster (
```
[k8s.io] Container Runtime blackbox test on terminated container
  should report termination message from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance]
  test/e2e/common/runtime.go:163
[BeforeEach] [k8s.io] Container Runtime
  test/e2e/framework/framework.go:153
STEP: Creating a kubernetes client
Nov  1 07:37:06.231: INFO: >>> kubeConfig: /var/run/kubernetes/admin.kubeconfig
STEP: Building a namespace api object, basename container-runtime
STEP: Waiting for a default service account to be provisioned in namespace
[It] should report termination message from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance]
  test/e2e/common/runtime.go:163
STEP: create the container
STEP: wait for the container to reach Failed
STEP: get the container status
STEP: the container should be terminated
STEP: the termination message should be set
Got: DONE ---- Expected: &{DONE}STEP: delete the container
[AfterEach] [k8s.io] Container Runtime
  test/e2e/framework/framework.go:154
Nov  1 07:37:07.297: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "e2e-tests-container-runtime-k2nwv" for this suite.
Nov  1 07:37:13.308: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
Nov  1 07:37:13.337: INFO: namespace: e2e-tests-container-runtime-k2nwv, resource: bindings, ignored listing per whitelist
Nov  1 07:37:13.362: INFO: namespace e2e-tests-container-runtime-k2nwv deletion completed in 6.063699587s

• [SLOW TEST:7.132 seconds]
[k8s.io] Container Runtime
test/e2e/framework/framework.go:694
  blackbox test
  test/e2e/common/runtime.go:37
    on terminated container
    test/e2e/common/runtime.go:133
      should report termination message from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance]
      test/e2e/common/runtime.go:163
------------------------------
```

**_Observed Behaviour in [gubernator](https://gubernator.k8s.io/builds/kubernetes-jenkins/pr-logs/pull/70492/pull-kubernetes-node-e2e/)_**
1. Container Terminates with Message "Done" when passing matching value "Done\n" [[Ref commit](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/70492/pull-kubernetes-node-e2e/109567/)]
2. Container Terminates with Message "Done\n" when passing matching value "Done" [[Ref commit](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/70492/pull-kubernetes-node-e2e/109565/)]
Note: Container's Termination Message MUST remain "DONE" in any scenarios w.r.t [container's command](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L175).

**Comment by spiffxp** [comment]
verify is failing because you need to `Run ./hack/update-bazel.sh`

**Comment by k-toyoda-pi** [comment]
Tests with your commit were successful on my local cluster.
runtime.go tests did not work properly without it.

**Comment by mgdevstack** [comment]
@k-toyoda-pi Yes, commit is supposed to run successful under "pull-kubernetes-node-e2e" job but unfortunately it passing only on local cluster but failing in testgrid.

I'm still surprised, why container's termination message is not consistent. An detailed explaination is added in #70990 issue summary. Once again I'm starting to debug this issue but community help is highly valuable here.

**Comment by pontiyaraja** [comment]
@spiffxp this PR is good to approve now

**Comment by mgdevstack** [comment]
@kubernetes/sig-node-pr-reviews, This PR is good to go in v1.14 milestone. #67609 is awaiting for this PR to get merged.

**Comment by spiffxp** [comment]
/approve
needs rebase

**Pull request merged**
