### PR TITLE
code cleanup: modify apiserver to make the validation clearer

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

Use `validateMasterCount` to make the validation clearer.

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by BinacsLee** [comment]
/assign @lavalamp 

Thanks

**Comment by BinacsLee** [comment]
cc @liggitt @logicalhan @pacoxu 
Thanks a lot ^-^

**Comment by pacoxu** [comment]
/ok-to-test
seems to be a small refactor/

**Comment by BinacsLee** [comment]
@pacoxu thank!
All tests have been paased

**Comment by BinacsLee** [comment]
@pacoxu thanks!
All tests have been paased

**Comment by lavalamp** [comment]
It's not obvious to me that this makes it clearer? I think the string makes it very obvious what is going on?

**Comment by BinacsLee** [comment]
Hi @lavalamp , Thanks for your review!
Let me see, a better description should be: 
maintain the same style as [other parts of the validation](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/validation.go#L168-L181) ^-^

**Pull request closed without merging**
