### PR TITLE
Add docker 1.12 in node e2e.

### PR DESCRIPTION
**Pull request by Random-Liu**
Add docker 1.12 image in node e2e (including regular node e2e and cri node e2e).

@dchen1107 @yujuhong 
/cc @kubernetes/sig-node-misc

### CODE REVIEW

**Comment by Random-Liu** [comment]
Let's wait for the test result to see whether the image is enabled and whether test can pass on the new image.

**Comment by yujuhong** [comment]
What's the complete version number (1.12.3)?

**Comment by yujuhong** [comment]
Docker 1.12.4 gets IO fixes: https://github.com/docker/docker/pull/29095

**Comment by Random-Liu** [comment]
@yujuhong It's 1.12.4.

```
$ sudo docker version
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Mon Dec 12 23:50:16 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Mon Dec 12 23:50:16 2016
 OS/Arch:      linux/amd64
```

**Comment by Random-Liu** [comment]
@yujuhong Updated the PR to add specific docker version in the comment.

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Pull request merged**
