### PR TITLE
Automated cherry pick of #122285: Revert "scheduler/nodeaffinity: reduce pod scheduling

### PR DESCRIPTION
**Pull request by sanposhiho**
Cherry pick of #122285 on release-1.29.

#122285: Revert "scheduler/nodeaffinity: reduce pod scheduling

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
QueueingHint implementation for NodeAffinity is reverted because we found potential scenarios where events that make Pods schedulable could be missed.
```

### CODE REVIEW

**Comment by sanposhiho** [comment]
@kerthcet @alculquicondor Can you check?

**Comment by alculquicondor** [comment]
This is removing the entire hint. Is that the only thing we can do to fix the problem? Or is there a more surgical fix that we can cherry-pick?

**Comment by kerthcet** [comment]
It's the safest way, I think there's no easy way here because we need to change the total logic.

**Comment by alculquicondor** [comment]
Sounds good. Just FYI, this means that we will not cherry-pick any future implementation of the hint.

**Review by kerthcet — COMMENTED** [review]
Definitely.
/lgtm
/approve

**Comment by kerthcet** [comment]
cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
