### PR TITLE
Automated cherry pick of #65739: Add priority to defaultOn plugins list

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #65739 on release-1.11.

#65739: Add priority to defaultOn plugins list

### CODE REVIEW

**Comment by liggitt** [comment]
/hold
for https://github.com/kubernetes/kubernetes/pull/65717
/sig scheduling
/milestone v1.11
/kind bug
/status approved-for-milestone
/priority critical-urgent

**Review by bsalamat — APPROVED** [review]
/lgtm

**Comment by foxish** [comment]
#65717 has been approved and will merge shortly

**Comment by liggitt** [comment]
will rebase once that merges and rerun tests

**Comment by foxish** [comment]
Is this a bug wherein we missed turning on the admission plugin by default in 1.11.0?

**Comment by liggitt** [comment]
> Is this a bug wherein we missed turning on the admission plugin by default in 1.11.0?

yes

**Comment by liggitt** [comment]
rebased, retagging

**Comment by liggitt** [comment]
/assign @deads2k 
for admission approval

**Comment by liggitt** [comment]
ping @foxish for cherry-pick approval

**Pull request merged**
