### PR TITLE
provide standard iostream struct for commands

### PR DESCRIPTION
**Pull request by deads2k**
Commands usually need some kind of iostream.  For consistency, delegation, and testability this pull introduces a standard struct to embed in every set of command options.  It also starts the plumbing so that the benefits of standardization for all three of those cases become clear.

@kubernetes/sig-cli-maintainers 
@soltysh @juanvallejo 

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by juanvallejo — APPROVED** [review]

**Comment by deads2k** [comment]
batch indicates consistent failure.  reproducing here

**Pull request merged**
