### PR TITLE
fix: flaky TestPrepareCandidate

### LINKED ISSUE #128689: [Flaking Test] unit TestPrepareCandidate
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1854630377990131712

### Which tests are flaking?

- https://k8s.io/kubernetes/pkg/scheduler/framework: preemption TestPrepareCandidate

### Since when has it been flaking?

11-08

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
{Failed;Failed;  === RUN   TestPrepareCandidate/two_victims_without_condition,_one_passes_successfully_and_the_second_fails_(Async_preemption_enabled:_false)
    preemption_test.go:749: expected deleted pods [victim2], got []
--- FAIL: TestPrepareCandidate/two_victims_without_condition,_one_passes_successfully_and_the_second_fails_(Async_preemption_enabled:_false) (30.11s)
;=== RUN   TestPrepareCandidate
--- FAIL: TestPrepareCandidate (34.78s)
```

### Anything else we need to know?

recent change: https://github.com/kubernetes/kubernetes/pull/128170 
- /cc @sanposhiho 

### Relevant SIG(s)

/sig scheduling

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

At `TestPrepareCandidate`, in the test case `two victims without condition, one passes successfully and the second fails`, 
currently, we're expecting `victim2` pod is always removed after all,
but the first victim could fail before the deletion of the second victim happens,
which results in the second victim not being deleted.

#### Which issue(s) this PR fixes:

Fixes #128689

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/cc @alculquicondor @pacoxu 

Please put a tag on it to include it in the release.

**Comment by sanposhiho** [comment]
Let me see if I have the right.

/milestone v1.32

**Comment by AxeZhan** [comment]
/lgtm
This feels weird though, I feel like we should find a way to defer the `failed patch` after the deletion.
But as code freeze is close soon, let's fix the flake first and leave this as a follow-up?

**Comment by AxeZhan** [comment]
>  I feel like we should find a way to defer the failed patch after the deletion.

This seems simple than I thought, we can just defer the change for `patchFailure`
```
					if action.(clienttesting.PatchAction).GetName() == "fail-victim" {
						go func() {
							<-deleteComplete
							mu.Lock()
							patchFailure = true
							mu.Unlock()
						}()
						return true, nil, fmt.Errorf("patch pod status failed")
					}
```
```
				cs.PrependReactor("delete", "pods", func(action clienttesting.Action) (bool, runtime.Object, error) {
					<-requestStopper
					dMu.Lock()
					defer dMu.Unlock()
					name := action.(clienttesting.DeleteAction).GetName()
					if name == "fail-victim" {
						deletionFailure = true
						return true, nil, fmt.Errorf("delete pod failed")
					}
					deletedPods.Insert(name)
					close(deleteComplete)
					return true, nil, nil
				})
```

This way we block the patch error until delete completed.
@sanposhiho  Up to you.

**Comment by sanposhiho** [comment]
Well, I prefer the current one.

**Comment by sanposhiho** [comment]
I don't want to make the reactor more complicated than the current state.

**Comment by AxeZhan** [comment]
/hold cancel

Let's get this merged then.

**Comment by sanposhiho** [comment]
also, I believe the current one is closer to the real situation (we don't know whether the other victim gets deleted or not, that depends on the timing.)

**Comment by sanposhiho** [comment]
Yeah, thanks

**Comment by pacoxu** [comment]
As the code freeze and test freeze has started together this time, I am not sure if this needs an [exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md).

The flake rate seems to be not that high, but it is a UT flake.
- once today: https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

/cc @liggitt @aojea

**Comment by aojea** [comment]
let's consult with the release people, I'm in favor of merging this, addresses a clear issue and the patch is very specific and only impact the unit test

**Comment by aojea** [comment]
Consuled with sig release folks https://kubernetes.slack.com/archives/C2C40FMNF/p1731051664580809 and we agreed this should be merged because is low risk of regression and solves an important issue like CI flakes

/milestone v1.32

**Comment by sanposhiho** [comment]
Thanks @aojea @pacoxu!

**Comment by aojea** [comment]
@sanposhiho did you run this with the `stress` tool to verify it does not keep flaking



/hold

just for proof it solves the flake

**Comment by sanposhiho** [comment]
No, I just ran several times and confirmed. Which tool do you mean by "`stress` tool"?

**Comment by sanposhiho** [comment]
Okay, this one: https://pkg.go.dev/golang.org/x/tools/cmd/stress
Let me try it and get back here

**Comment by aojea** [comment]
give me one min and I show you,

**Comment by aojea** [comment]
The tools is this

https://pkg.go.dev/golang.org/x/tools/cmd/stress

You have more detailed instructions here https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md#deflaking-unit-tests


```
# build the test binary
 go test -c -race ./pkg/scheduler/framework/preemption
# stress it
stress ./preemption.test -test.run TestPrepareCandidate
5s: 0 runs so far, 0 failures
10s: 48 runs so far, 0 failures

/tmp/go-stress-20241108T080146-454971119
E1108 08:01:56.736843 2266386 preemption.go:190] "Tried to preempted pod" err="delete pod failed" pod="fail-victim" preemptor="preemptor"
E1108 08:01:56.736894 2266386 preemption.go:540] "Error occurred during async preemption" err="delete pod failed"
E1108 08:01:57.350339 2266386 preemption.go:184] "Could not add DisruptionTarget condition due to preemption" err="patch pod status failed" pod="fail-victim" preemptor="preemptor"
E1108 08:01:57.350388 2266386 preemption.go:540] "Error occurred during async preemption" err="patch pod status failed"
E1108 08:01:57.657284 2266386 preemption.go:184] "Could not add DisruptionTarget condition due to preemption" err="patch pod status failed" pod="fail-victim" preemptor="preemptor"
E1108 08:01:57.657358 2266386 preemption.go:531] "Error occurred during async preemption" err="patch pod status failed"
--- FAIL: TestPrepareCandidate (5.64s)
    --- FAIL: TestPrepareCandidate/no_victims_(Async_preemption_enabled:_true) (1.03s)
        framework.go:399: I1108 08:01:55.704274] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":null,"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":null,"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}
        preemption_test.go:703: expected preempting map map[preemptor:{}], got map[]
FAIL


ERROR: exit status 1

15s: 57 runs so far, 1 failures (1.75%)
20s: 96 runs so far, 1 failures (1.04%)
25s: 144 runs so far, 1 failures (0.69%)
```

it is still flaking

**Comment by aojea** [comment]
> expected preempting map map[preemptor:{}], got map[]

sees you have a check that does want nil and you receive empty

**Comment by sanposhiho** [comment]
Fixed another flake, and confirmed that the test goes successfully 200+ times.

```
$ stress go test -timeout 30s -run ^TestPrepareCandidate$ k8s.io/kubernetes/pkg/scheduler/framework/preemption --count=1
5s: 0 runs so far, 0 failures, 12 active
10s: 0 runs so far, 0 failures, 12 active
15s: 0 runs so far, 0 failures, 12 active
20s: 5 runs so far, 0 failures, 12 active
25s: 11 runs so far, 0 failures, 12 active
30s: 12 runs so far, 0 failures, 12 active
35s: 17 runs so far, 0 failures, 12 active
40s: 20 runs so far, 0 failures, 12 active
45s: 27 runs so far, 0 failures, 12 active
50s: 30 runs so far, 0 failures, 12 active
55s: 33 runs so far, 0 failures, 12 active
1m0s: 37 runs so far, 0 failures, 12 active
1m5s: 42 runs so far, 0 failures, 12 active
1m10s: 46 runs so far, 0 failures, 12 active
1m15s: 51 runs so far, 0 failures, 12 active
1m20s: 55 runs so far, 0 failures, 12 active
1m25s: 61 runs so far, 0 failures, 12 active
1m30s: 67 runs so far, 0 failures, 12 active
1m35s: 69 runs so far, 0 failures, 12 active
1m40s: 73 runs so far, 0 failures, 12 active
1m45s: 79 runs so far, 0 failures, 12 active
1m50s: 81 runs so far, 0 failures, 12 active
1m55s: 84 runs so far, 0 failures, 12 active
2m0s: 91 runs so far, 0 failures, 12 active
2m5s: 95 runs so far, 0 failures, 12 active
2m10s: 98 runs so far, 0 failures, 12 active
2m15s: 103 runs so far, 0 failures, 12 active
2m20s: 110 runs so far, 0 failures, 12 active
2m25s: 112 runs so far, 0 failures, 12 active
2m30s: 118 runs so far, 0 failures, 12 active
2m35s: 123 runs so far, 0 failures, 12 active
2m40s: 127 runs so far, 0 failures, 12 active
2m45s: 131 runs so far, 0 failures, 12 active
2m50s: 138 runs so far, 0 failures, 12 active
2m55s: 142 runs so far, 0 failures, 12 active
3m0s: 145 runs so far, 0 failures, 12 active
3m5s: 151 runs so far, 0 failures, 12 active
3m10s: 154 runs so far, 0 failures, 12 active
3m15s: 158 runs so far, 0 failures, 12 active
3m20s: 163 runs so far, 0 failures, 12 active
3m25s: 168 runs so far, 0 failures, 12 active
3m30s: 170 runs so far, 0 failures, 12 active
3m35s: 173 runs so far, 0 failures, 12 active
3m40s: 178 runs so far, 0 failures, 12 active
3m45s: 184 runs so far, 0 failures, 12 active
3m50s: 187 runs so far, 0 failures, 12 active
```

**Comment by aojea** [comment]
/hold cancel
/lgtm

Thanks

**Comment by aojea** [comment]
/lgtm cancel

```
Failed;Failed;  === RUN   TestPrepareCandidate/no_victims_(Async_preemption_enabled:_true)
==================
WARNING: DATA RACE
Read at 0x00c00114c4b0 by goroutine 111:
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.TestPrepareCandidate.func1.3()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption_test.go:739 +0x155
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/loop.go:87 +0x6f
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/loop.go:88 +0x337
  k8s.io/apimachinery/pkg/util/wait.PollUntilContextTimeout()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/poll.go:48 +0xe4
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.TestPrepareCandidate.func1()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption_test.go:735 +0x228f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Previous write at 0x00c00114c4b0 by goroutine 130:
  runtime.mapdelete_faststr()
      /usr/local/go/src/runtime/map_faststr.go:321 +0x0
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.(*Evaluator).prepareCandidateAsync.func2()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption.go:517 +0x1124

Goroutine 111 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1743 +0x825
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.TestPrepareCandidate()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption_test.go:622 +0x403e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44

Goroutine 130 (finished) created at:
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.(*Evaluator).prepareCandidateAsync()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption.go:489 +0x789
  k8s.io/kubernetes/pkg/scheduler/framework/preemption.TestPrepareCandidate.func1()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/preemption/preemption_test.go:703 +0x1a84
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1743 +0x44
==================
    testing.go:1399: race detected during execution of test
--- FAIL: TestPrepareCandidate/no_victims_(Async_preemption_enabled:_true) (0.31s)
;=== RUN   TestPrepareCandidate
--- FAIL: TestPrepareCandidate (4.98s)
```

there is a race now :)

**Comment by aojea** [comment]
use the -race flag , that will detect this in your local testing

**Comment by aojea** [comment]
also, I think is better if you build the binary and use stress on the generated binary ... I'm not sure the way you are running it is doing what we are thinking is doing 🤔  , it seems is running the go test command multiple times, but is not what we want

**Comment by sanposhiho** [comment]
I already left the desk today, but will make a fix in the weekend before flying for Kubecon..

I _suppose_ my command also does because I could reproduce the test failure at the master branch with.

**Comment by aojea** [comment]
> I _suppose_ my command also does because I could reproduce the test failure at the master branch with it.

maybe is the machine, I was basing my assumption in my run was faster, so it may compile a different binary for test each time?
I had 48 runs in 10 seconds, and your example there were no runs , or maybe is that is not cascading the test filter flag, ??

> 10s: 48 runs so far, 0 failures
> 10s: 0 runs so far, 0 failures, 12 active


👍

**Comment by aojea** [comment]
@sanposhiho are we good now?

**Comment by sanposhiho** [comment]
Yes, no more data race is detected.

**Comment by aojea** [comment]
/lgtm
```
8m35s: 3637 runs so far, 0 failures
8m40s: 3678 runs so far, 0 failures
8m45s: 3706 runs so far, 0 failures
8m50s: 3741 runs so far, 0 failures
8m55s: 3781 runs so far, 0 failures
9m0s: 3819 runs so far, 0 failures
```

**Pull request merged**
