### PR TITLE
Add-On manager should not be creating kube-system namespace #75567

### LINKED ISSUE #75567: Add-On manager should not be creating kube-system namespace
**What happened**:
Add-on manager uses kubectl apply to create the kube-system namespace at start-up. 
This is redundant because the kube-apiserver creates the namespace in NewBootstrapController. 
This is a problem because if someone uses apply to make changes to the kube-system namespace, the add-on manager will wipe out these changes. 

**What you expected to happen**:
Kube-APIServer has the sole responsibility of creating the kube-system namespace.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply a label to the kube-system namespace.
restart the add-on manager.
Note the labels have been removed.

**Anything else we need to know?**:
/sig api-machinery

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rightblank**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #75567 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
addon-manager: don't automatically create the kube-system namespace
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by MrHohn** [comment]
Some places needed to be cleaned up if we are removing this:

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/namespace.yaml
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/Dockerfile
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md

**Comment by neolit123** [comment]
/hold
@rightblank please change the release note in the first comment from
`No`
to
`addon-manager: don't automatically create the kube-system namespace`

thanks

**Comment by rightblank** [comment]
@neolit123 the release note has been updated, sorry for the delay

**Comment by neolit123** [comment]
please also take a look at this comment:
https://github.com/kubernetes/kubernetes/pull/75769#issuecomment-481791237

**Pull request closed without merging**
