### PR TITLE
kube-openapi Marshal v2 for spec.Swagger

### PR DESCRIPTION
**Pull request by apelisse**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update kube-openapi to use https://github.com/kubernetes/kube-openapi/pull/325/. And call the right function where needed.

#### Which issue(s) this PR fixes:
Doesn't really as much fix a bug but a performance issue. Related to https://github.com/kubernetes/kube-openapi/issues/324.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
Updated with newest changes, should be ready to merge once the kube-openapi PR merge this tiem.

**Comment by apelisse** [comment]
/retest

Also, @liggitt, looks like check dependency is failing again to notice that this imports a local change?

**Comment by liggitt** [comment]
> /retest
> 
> Also, @liggitt, looks like check dependency is failing again to notice that this imports a local change?

thanks, opened https://github.com/kubernetes/kubernetes/pull/113978 to fix that

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by apelisse** [comment]
We definitely want this, no need to rebase yet though, this is waiting for a fix in a dependency. I'll care for this once the fix is in, thanks!

**Comment by apelisse** [comment]
We actually merged that recently, this isn't needed anymore.

**Pull request closed without merging**
