### PR TITLE
Automated cherry pick of #26418

### PR DESCRIPTION
**Pull request by adohe-zz**
Cherry pick of #26418 on release-1.2. @bgrant0607 ptal.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. LGTM.

**Comment by bgrant0607** [comment]
@janetkuo Please help shepherd this cherrypick.

The e2e failure was:
```
â€¢ Failure [115.429 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1200
  Kubectl rolling-update
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1030
    should support rolling-update to same image [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1029

    Expected error:
        <*errors.errorString | 0xc2083a0900>: {
            s: "Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.107.48 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config rolling-update e2e-test-nginx-rc --update-period=1s --image=gcr.io/google_containers/nginx:1.7.9 --image-pull-policy=IfNotPresent --namespace=e2e-tests-kubectl-uyuh7] []  <nil> Error updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 3 secondsError updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 9 secondsError updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 81 seconds Error from server: pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again\n [] <nil> 0xc208561300 exit status 1 <nil> true [0xc2083b6460 0xc2083b6480 0xc2083b64a0] [0xc2083b6460 0xc2083b6480 0xc2083b64a0] [0xc2083b6478 0xc2083b6498] [0x968650 0x968650] 0xc208393a40}:\nCommand stdout:\nError updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 3 secondsError updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 9 secondsError updating pod (pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 81 seconds\nstderr:\nError from server: pods \"e2e-test-nginx-rc-9s4g5\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again\n\nerror:\nexit status 1\n",
        }
        Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.107.48 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config rolling-update e2e-test-nginx-rc --update-period=1s --image=gcr.io/google_containers/nginx:1.7.9 --image-pull-policy=IfNotPresent --namespace=e2e-tests-kubectl-uyuh7] []  <nil> Error updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 3 secondsError updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 9 secondsError updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 81 seconds Error from server: pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
         [] <nil> 0xc208561300 exit status 1 <nil> true [0xc2083b6460 0xc2083b6480 0xc2083b64a0] [0xc2083b6460 0xc2083b6480 0xc2083b64a0] [0xc2083b6478 0xc2083b6498] [0x968650 0x968650] 0xc208393a40}:
        Command stdout:
        Error updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 3 secondsError updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 9 secondsError updating pod (pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again), retrying after 81 seconds
        stderr:
        Error from server: pods "e2e-test-nginx-rc-9s4g5" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
        
        error:
        exit status 1
        
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1593
```

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by LEW21** [comment]
It has happened, the AI has decided to kill all humans by global warming!

**Comment by AdoHe** [comment]
@bgrant0607 the GCE e2e failed because:
```
hudson.plugins.git.GitException: Could not checkout 366cd53ac37d814afbca4200cd8ff46eda60ec62
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1992)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to agent-pr-40(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy64.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1135)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 366cd53ac37d814afbca4200cd8ff46eda60ec62" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 366cd53ac37d814afbca4200cd8ff46eda60ec62
```
what can I do about this? The robot is gone to kill my mail box. So annoying :(

**Comment by eparis** [comment]
Removing LGTM to shut up the bot.
@lavalamp I think the bot is angry, likely because verification isn't run on the release-1.2 branch?

**Comment by eparis** [comment]
@roberthbailey you probably want to merge this by hand....

**Comment by eparis** [comment]
@spxtr @ixdy @kubernetes/sig-testing 
What are the `No test results found.` complaints? Is that because this is for the release-1.2 branch?

**Comment by jayunit100** [comment]
Looks like https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-31103 some kinda weird Jenkins SHA limit thingy?

**Comment by lavalamp** [comment]
Maybe #27685 is the culprit?

**Comment by fabioy** [comment]
I think we need to merge this to to get the "kubernetes-test-go-release-1.2" Jenkins working again. Manual merge?

**Comment by ixdy** [comment]
No idea what happened here. @kubernetes/test-infra-maintainers did we break PR Jenkins for 1.2 somehow?

**Comment by eparis** [comment]
So the merge-bot is angry because 'Jenkins verification' is never run on `release-1.2`.

That's a merge-bot problem, but it doesn't explain the k8s-bot responses. That's a different bot problem for the test-infra team.

**Comment by roberthbailey** [comment]
@fabioy kubernetes-test-go-release-1.2 failed on the run after this PR was merged into the release branch. Any other ideas of how to fix that test on the release branch?

**Pull request merged**
