### PR TITLE
Address last-minute requested changes for inplace update feature testing in scheduler

### PR DESCRIPTION
**Pull request by wangchen615**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This is a follow-up PR for a merged [PR#102884](https://github.com/kubernetes/kubernetes/pull/102884) to address [comments related to scheduler testing](https://github.com/kubernetes/kubernetes/pull/102884#pullrequestreview-1314425652).

#### Special notes for your reviewer:
Just for scheduler testing changes requested by @Huang-Wei 

#### Does this PR introduce a user-facing change?
No

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

```docs

```

### CODE REVIEW

**Comment by wangchen615** [comment]
/assign @Huang-Wei 

cc @vinaykul

**Comment by vinaykul** [comment]
Ref: https://github.com/kubernetes/kubernetes/pull/102884#issuecomment-1444878141
/assign @ahg-g @endocrimes @SergeyKanzhelev

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
