### PR TITLE
Execution retry and timeout of lifecycle hooks

### PR DESCRIPTION
**Pull request by PengTaoWW**
**What this PR does / why we need it**:
I have an improvement on Kubernetes, in our production environment, run perstop hook when removing pod, but no matter how quickly the result of this pod is removed, my improvement is that when Perstop fails, it will retry until the execution succeeds, or the timeout is removed. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@PengTaoWW - please split all the auto-generated changes to a separate commit.

**Comment by PengTaoWW** [comment]
@wojtek-t  I follow this document
 https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
in git commit will run hook ，hook can auto-generated some code 
can i miss hook to submit?

**Comment by PengTaoWW** [comment]
@wojtek-t this is clean code version https://github.com/kubernetes/kubernetes/pull/46426 is that ok?

**Comment by ncdc** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by resouer** [comment]
Thanks @ncdc for reference!

Thanks @PengTaoWW for picking this up, as first time contributor, here some "boring" things to do:
1. Split auto generated files into separate commit, you can just reset them and run `./hack/update-all.sh` and commit them separately.

2. sign the CLA

3. ping one of the reviewers or assignees on the top right list to review once all those nits are fixed & CI passed, they will approve your PR.

**Comment by resouer** [comment]
@k8s-bot ok to test

**Pull request closed without merging**
