### PR TITLE
Update Calico to v3.15.2

### PR DESCRIPTION
**Pull request by lmm**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR updates Calico to v3.15.2 which includes numerous features and fixes since v3.8.4.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Calico to v3.15.2
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by anfernee** [comment]
@bowei can you approve this? I've also tested it locally.

**Comment by bowei** [comment]
Please take a look at https://groups.google.com/g/kubernetes-dev/c/YXGBa6pxLzo

**Comment by caseydavenport** [comment]
Based on that, I think this is in a merge-able state and so the right action is:

/milestone v1.20

**Pull request merged**
