### PR TITLE
Fix number of retries for Job with restartPolicy OnFailure

### LINKED ISSUE #95433: Number of Job retires is different for restartPolicy of OnFailure and Never
**What happened**:
Submitting a job with the same value of `backoffLimit` (as long as `backoffLimit` > 0) will cause different number of retries with different values of `restartPolicy`.
For `restartPolicy=Never` the number of retires is equal to `backoffLimit`. 
For `restartPolicy=OnFailure` the number of retires is equal to `backoffLimit-1`.

**What you expected to happen**:
Both policies should have the same number of retires for the same `restartPolicy`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a job with `restartPolicy=OnFailure` with the following .yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-1
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["bash", "-c"]
        args:
        - sleep 300 && command-that-doesnt-exist
      restartPolicy: OnFailure
```

After 5 minutes the job will have the following status:

```
status:
    conditions:
    - lastProbeTime: "2020-10-09T08:14:47Z"
      lastTransitionTime: "2020-10-09T08:14:47Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    startTime: "2020-10-09T08:09:41Z" 
```

According to the `startTime` and `lastTransitionTime` that the job had failed after ~5 minutes, the pod was deleted after 5 minutes.

2. Create a job with `restartPolicy=Never` with the following .yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-2
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["bash", "-c"]
        args:
        - sleep 300 && command-that-doesnt-exist
      restartPolicy: Never

```
After 10 minutes the job will have the following status:

```
- lastProbeTime: "2020-10-09T08:18:45Z"
    lastTransitionTime: "2020-10-09T08:18:45Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 2
  startTime: "2020-10-09T08:08:18Z"
```

According to the `startTime` and `lastTransitionTime` that the job had failed after ~10 minutes, 2 pods were created and deleted during the 10 minutes).

**Anything else we need to know?**:
This was tested with the fix of: https://github.com/kubernetes/kubernetes/pull/93779 so the number of failures for `restartPolicy=Never` is stable.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8

### PR DESCRIPTION
**Pull request by yodarshafrir1**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
When running a Job with `restartPolicy=OnFailure` and `backoffLimit > 0` the number of retry attempts until considering the job as Failed is currently `backoffLimit-1`.
According to docs the value of `backoffLimit` specifies the number of retries before considering a Job as failed.
This PR sets the max number of retires to equal to `backoffLimit` for `restartPolicy=OnFailure`.

**Which issue(s) this PR fixes**:

Fixes #95433

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: 

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig apps

### CODE REVIEW

**Review by janetkuo — CHANGES_REQUESTED** [review]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apps/job.md#backoff-policy-and-failed-pod-limit:
> For `Never` we count actual pod failures (reflected in `.status.failed` field). With `OnFailure`, we take an approximate value of pod restarts (as reported in `.status.containerStatuses[*].restartCount`). 

Current implementation works as designed.

**Comment by yodarshafrir1** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apps/job.md#backoff-policy-and-failed-pod-limit:
> `BackoffLimit` is set by default to 6 and BackoffSeconds to 10s. This will result in the following `retry` sequence: 10s, 20s, 40s, 1m20s, 2m40s, 5m20s. After which the job will be considered failed.
...
>All of the above fields will be optional and will apply when restartPolicy is set to Never on a PodTemplate. With restart policy `OnFailure` only `BackoffLimit` `applies`.

From my understanding `BackoffLimit` should have the same number of retries for both policies. 
It's also mentioned that for `BackoffLimit=6` there should be `6 retries`.


With the current implementation there would be:
- Only 5 retries for `restartPolicy=OnFailure` (6 attempts to run the pod).
- 6 retries for `restartPolicy=Never` (7 attempts to run the pod).

@janetkuo

**Comment by yodarshafrir1** [comment]
@janetkuo @soltysh Could you please review this PR?

**Comment by sftim** [comment]
/retitle Fix number of retries for Job with restartPolicy OnFailure

**Pull request closed without merging**
