### PR TITLE
e2e_node: Cleanup old unused jenkins scripts/config

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind cleanup
/sig node

#### What this PR does / why we need it:

Removes some old scripts and configuration that are no longer used by the Kubernetes project. I couldn't find any references to these that weren't old vendor/ directories with cs.k8s.io/

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by matthyx** [comment]
Indeed very old...
/lgtm
/triage accepted
/priority backlog

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
