### PR TITLE
Add config examples for haproxy and rsyslog

### PR DESCRIPTION
**Pull request by verb**
This also includes a script to generate secrets configuration to support
these examples until #4822 is resolved.

### CODE REVIEW

**Comment by bprashanth** [comment]
@verb interested in integrating this with the serviceloadbalancer instead? It is more general purpose, but currently stores the config template (https://github.com/kubernetes/contrib/tree/master/service-loadbalancer) in the image. I've been meaning to make it more dynamic.

**Comment by bprashanth** [comment]
Also FYI some form of that controller will probably make it into main tree as a cluster addon that uses the Ingress resource soon

**Comment by verb** [comment]
@bprashanth Sure, I'd be happy to do that. I guess it's a matter of goals.

When I first starting using Kubernetes I had (have?) trouble divining design intentions and best practices. I wanted to contribute some examples to:

1. Get feedback from the project on assumptions I've made when building my configs.
2. Document some best practices in the form of examples so that others won't have to make assumptions
3. Contribute config for real services that will be useful without modification (as much as possible, @zmerlynn and @aronchick have better vision in this space).

Goal 1 has been effective so far because I didn't know about serviceloadbalancer. I chose haproxy more or less arbitrarily as a means to an end. Serviceloadbalancer completely obviates the haproxy configuration I wrote, though. Integrating it with serviceloadbalancer doesn't make any sense since SLB does the same thing but better.

As a way forward, I'll propose that I remove haproxy from this PR completely leaving the rsyslog example (which is interesting in that it uses PVCs and the currently required 1:1 mapping of RCs to volumes -- which I should make more obvious, come to think of it). Then I'll follow up with some other example that can make use of SLB.

I'd like to help further refine `examples/`, but I'm struggling with what it should be, so I'll also find (or create) a github issue to get consensus around the direction of examples.

Thoughts?

**Comment by ashcrow** [comment]
Shippable error looks unrelated

```
FAIL	k8s.io/kubernetes/pkg/storage/etcd	9.121s
```

**Comment by bprashanth** [comment]
@verb SGTM, sorry for the delay was wrapping up 1.1 stuff

> Integrating it with serviceloadbalancer doesn't make any sense since SLB does the same thing but better.

Hmm, transporting the config via secret which is a nice feature actually. Currently to specify a new/different template someone has to rebuild the base image, would be nice if they could instead just deploy the base image after creating a secret, and the haproxy in the pod would use the mounted cfg from secret. 

> I'd like to help further refine examples/, but I'm struggling with what it should be, so I'll also find (or create) a github issue to get consensus around the direction of examples

If you're looking to just get involved you can write a better nginx Ingress controller :D (https://github.com/kubernetes/contrib/tree/master/Ingress/controllers)

Let me know when you've done your proposed changes

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by bgrant0607** [comment]
@pmorie This looks like a use case for ConfigMap.

**Comment by bprashanth** [comment]
Please re-open when/if we decide to do something along https://github.com/kubernetes/kubernetes/pull/16515#issuecomment-155195281

**Pull request closed without merging**
