### PR TITLE
fix nodecontroller race

### PR DESCRIPTION
**Pull request by deyuanix**
#5535 introduces event recorder/broadcaser
#6155 starts recording event in node probe

Not sure if this fixes the problem... let's see

### CODE REVIEW

**Comment by ddysher** [comment]
Looks like both are failing for different reasons.

**Comment by davidopp** [comment]
What do you mean "Looks like both are failing for different reasons" ?

**Comment by ddysher** [comment]
whoops, sorry for the confusion. By both, I mean "travis" and "shippable".

Last time I checked, travis is failing due to #6045; and shippable is failing due to shippable's internal server error.

**Comment by davidopp** [comment]
Will send a PR to remove event generation from NodeController shortly.

**Comment by ddysher** [comment]
@davidopp SGTM.  As a stop-bleeding solution, we can remove event generation

What are we going to do about this fix?  Close it?   We'll eventually generate events in nodecontroller, so I'd at least want to know what's causing the race.

**Comment by davidopp** [comment]
I merged PR #6443 yesterday which removes event generation from NodeController. Maybe we should just re-name this issue to "add events back to NodeController" so we don't lose the history?

**Comment by davidopp** [comment]
Sorry, I mean rename #6199, not rename this issue (this isn't an issue, this is your PR).

**Comment by rjnagal** [comment]
@davidopp @ddysher do we still need this fix?

**Comment by davidopp** [comment]
Nope, this is fixed by #6443.

**Pull request closed without merging**
