### PR TITLE
fix azure load balancer update dns label issue

### LINKED ISSUE #67813: Azure - PIP dns label will not change while updating the service
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Azure will not update the DNS label of the public IP, when update the service **only** changing the annotation of the DNS label from empty.

	annotations:

->
	
	annotations:
		service.beta.kubernetes.io/azure-dns-label-namel: "to-update"

**What you expected to happen**:
It should update the dns label of the assigned public IP

**How to reproduce it (as minimally and precisely as possible)**:
It probably caused when applying function 'getPublicIPAddress' in azure_loadbalancer.go.
This function returns a bool 'existsPip' to judge the public ip existence.  When only the annotations changed, the existsPip still returns true. Then, the reference in _line 553_ and _line 446_ step into this bug.

	pip, existsPip, err := az.getPublicIPAddress(pipResourceGroup, pipName)
	if err != nil {
		return false, err
	}
	if !existsPip {
		return true, nil
	}

- Firstly, in _line 554_, it will make function 'isFrontendIPChanged' return false, and then will not run 'ensurePublicIP' in _line 691_.
- Secondly, even if 'ensurePublicIP' in _line 691_ runs, it will detect the public ip exists and make no update to the DNS label in _line 446_.

**Environment**:
- Kubernetes version (use `kubectl version`):  c927968
- Cloud provider or hardware configuration:  Azure

### PR DESCRIPTION
**Pull request by levimm**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix for azure load balancer when updating service's "service.beta.kubernetes.io/azure-dns-label-name" annotation, the public ip's dns label is set accordingly.

**Which issue(s) this PR fixes**:

Fixes #67813

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix azure load balancer update dns label issue
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig azure
/sig cloud-provider

### CODE REVIEW

**Comment by levimm** [comment]
I signed it

**Comment by feiskyer** [comment]
@levimm Thanks for the PR. Could you add unit tests and fix existing test errors?

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
