### PR TITLE
Automated cherry pick of #18000

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #18000 on release-1.1.

### CODE REVIEW

**Comment by ixdy** [comment]
x-ref #17998

@fabioy @karlkfi

**Comment by ixdy** [comment]
integration test flake.

@k8s-bot unit test this please

**Comment by brendandburns** [comment]
LGTM.

**Comment by karlkfi** [comment]
Manually merging to fix cherry-pick queue

**Comment by fabioy** [comment]
Thanks for the cherrypick. I was detained with family stuff.

**Pull request merged**
