### PR TITLE
remove unused func deprecatedAlias

### PR DESCRIPTION
**Pull request by Pingan2017**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
following #70728
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by Pingan2017** [comment]
ping @soltysh 
PTAL, fix a test err.
Thanks.

**Pull request merged**
