### PR TITLE
Don't allow services to get stuck on an intermediate bad state

### PR DESCRIPTION
**Pull request by lavalamp**
I'll kick off an e2e run shortly.

@uruddarraju

Ref #9382

### CODE REVIEW

**Comment by mikedanese** [comment]
Can you reassign when this is not a WIP?

**Comment by lavalamp** [comment]
OK, this seems to pass tests. Past me thought it was worth making. This service controller code could stand to switch over to informers, but this should be fixed before then, probably. @bprashanth for review.

**Comment by bprashanth** [comment]
LGTM, though the serviceloadbalancer should also not requeue if the create failed because the service doesn't exist  (https://github.com/GoogleCloudPlatform/kubernetes/blob/185eb5e26ab6aecf4c49f461723f8f58c56ac4f0/pkg/cloudprovider/servicecontroller/servicecontroller.go#L295)

**Comment by lavalamp** [comment]
Yeah let's deal with that separately-- is there an issue filed, or maybe you can extend #9382?

**Comment by bprashanth** [comment]
Alright, everything passed so I'm merging

**Pull request merged**
