### PR TITLE
NetworkPolicy cherry-pick 1.3

### PR DESCRIPTION
**Pull request by caseydavenport**
- Enable NetworkPolicy by default
- NetworkPolicy related docs autogen

CC @thockin @fabioy

### CODE REVIEW

**Comment by fabioy** [comment]
@k8s-bot test this #IGNORE

**Comment by thockin** [comment]
LGTM but it needs a rebase, sorry @caseydavenport

**Comment by fabioy** [comment]
@k8s-bot test this issue #ignore

**Comment by thockin** [comment]
/go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh

/go/src/k8s.io/kubernetes/api/swagger-spec is out of date. Please run hack/update-swagger-spec.sh

**Comment by fabioy** [comment]
@caseydavenport Can you fix the issues Tim found and rebase the PR? Thanks.

**Comment by caseydavenport** [comment]
@fabioy @thockin Yep, sorry about that.  Just re-ran the auto-gen so hopefully all is good now.

**Comment by fabioy** [comment]
Argh, silly Github plugin error. Manually merging.

**Pull request merged**
