### PR TITLE
Minor cleanup in kubeadm.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
```release-note
NONE
```

### CODE REVIEW

**Review by jamiehannaford — APPROVED** [review]
lgtm

**Comment by fabriziopandini** [comment]
@xiangpengzhao thanks for the cleanup!
/lgtm

**Review by luxas — APPROVED** [review]
/approve

Great, thanks :+1:
Sorry for noticing this PR late in the game, thanks @jamiehannaford and @fabriziopandini for reviewing!

**Pull request merged**
