### PR TITLE
Validate --storage-backend type.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Validate --storage-backend type as early as possible.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47517
This PR is as per https://github.com/kubernetes/kubernetes/pull/47517/files#r121975646

**Special notes for your reviewer**:
/cc @justinsb 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/approve
/lgtm

We may want to rethink this in the future but this is at least an improvement on the current state.

**Comment by xiangpengzhao** [comment]
Thanks @lavalamp!

Since there is no direct associated issue for this PR, it needs your `/approve no-issue` :)

**Comment by xiangpengzhao** [comment]
Set #47517 as associated issue (actually not) to stop bot complaining.

**Pull request merged**
