### PR TITLE
apimachinery: cleanup code and comments

### PR DESCRIPTION
**Pull request by ccding**
fix golint issues

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by idealhack** [comment]
@ccding Thanks for your work! Could you squash these 5 commits to 3 by keeping the two code-fix as it is? In that way it’s LGTM.

**Comment by ccding** [comment]
> Could you squash these 5 commits to 3 by keeping the two code-fix as it is? In that way it’s LGTM.

Done, PTAL

**Review by idealhack — APPROVED** [review]

**Pull request merged**
