### PR TITLE
Enable update staging client in master.

### PR DESCRIPTION
**Pull request by k82cn**
Enable update staging client in master.

### CODE REVIEW

**Comment by deads2k** [comment]
Removing this from the merge queue until https://github.com/kubernetes/kubernetes/pull/39099 is settled.

**Comment by deads2k** [comment]
@caesarxuchao This enables auto-updating.  I think this should wait until we sort out how to handle client-go vendoring.  I think it should be done as part of a sync to client-go.

**Comment by deads2k** [comment]
I think we need to split the copy script into a script that copies the API types from k8s.io/kubernetes and a script that generates the client directly into client-go.  After that, we do NOT run the vendoring step in kubernetes.  Instead, there should be a client-go sync script like we have for apimachinery. If a bot were to sync all repos against the same kubernetes, the vendor dir could be built during that step and it would always have a matching set and we have no cycles.

**Comment by caesarxuchao** [comment]
The process you proposed will work if there are only api/ and apis/ under [client-go/pkg/](https://github.com/kubernetes/client-go/tree/master/pkg). Otherwise staging/client-go will not compile because these other packages under staging/client-go/pkg/ can be out of date.

I will write an alternative approach in https://github.com/kubernetes/client-go/issues/78, let's see if it's more intuitive.

**Comment by k82cn** [comment]
@caesarxuchao / @deads2k , thanks for your comments :). how about juts delete those lines comments?

**Comment by deads2k** [comment]
> The process you proposed will work if there are only api/ and apis/ under client-go/pkg/. Otherwise staging/client-go will not compile because these other packages under staging/client-go/pkg/ can be out of date.

Using `go list` you'd be able to pick up the dependencies (and transitives) too.

**Comment by caesarxuchao** [comment]
`godep save` under the hood is the same as `go list`.

I'm not too excited about generating clients in the publishing robot, it makes client-go's publishing process different from other repos. I think this [idea](https://github.com/kubernetes/client-go/issues/78#issuecomment-276619494) is easier to think about. (oh I see you commented that idea is good, I'll experiment it and push something tomorrow)

**Comment by caesarxuchao** [comment]
I think mainly I need to update the publishing robot to checkout the latest apimachinary and vendor it before publishing to k8s.io/client-go. I'll code it up tmr. I'll clean up copy.sh as well, but maybe we are not on the same page about copy.sh, we'll see :)

**Pull request closed without merging**
