### PR TITLE
Revert PR #126533 and add a test case for broken case

### PR DESCRIPTION
**Pull request by ah8ad3**
Revert https://github.com/kubernetes/kubernetes/pull/126533 and add a test case for broken case that mentioned in the https://github.com/kubernetes/kubernetes/pull/126533#issuecomment-2467805064. Which is a part of https://github.com/kubernetes-sigs/cluster-api/blob/f495466327aa340ad8c36182eb4e2797e7e35bef/config/crd/bases/cluster.x-k8s.io_machinedrainrules.yaml#L89

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Revert a broken change in `kubectl explain`

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

<!--
This section can be blank if this pull request does not require a release note.

When adding links which point to resources within git repositories, like
KEPs or supporting documentation, please reference a specific commit and avoid
linking directly to the master branch. This ensures that links reference a
specific point in time, rather than a document that may change over time.

See here for guidance on getting permanent links to files: https://help.github.com/en/articles/getting-permanent-links-to-files

### CODE REVIEW

**Comment by ah8ad3** [comment]
Seems unrelated
/retest

**Comment by fabriziopandini** [comment]
@ah8ad3 Thanks for this PR and for adding CAPI example as unit test, really appreciated!

**Pull request merged**
