### PR TITLE
Cherry pick of #92599: Delete default load balancer source range (0.0.0.0/0) to prevent redundant network security rules. 

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #92599 on release-1.16.

#92599: Delete default load balancer source range (0.0.0.0/0) to prevent redundant network security rules.

/kind bug
/area provider/azure
/sig cloud-provider
/priority important-soon

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
/retest

**Review by feiskyer — APPROVED** [review]
looks good. @nilo19 could you add a release note?

/retest

**Comment by nmiodice** [comment]
Do we know when this will be rolled out? Which version should I look out for?

**Pull request merged**
