### PR TITLE
Revert "Delay deletion of pod from the API server until volumes are deleted"

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Reverts kubernetes/kubernetes#40239

It seems it broke e2e tests:

```
I0126 14:45:08.027] • Failure [101.065 seconds]
I0126 14:45:08.027] [k8s.io] Pods Extended
I0126 14:45:08.027] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:656
I0126 14:45:08.028]   [k8s.io] Delete Grace Period
I0126 14:45:08.028]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:656
I0126 14:45:08.028]     should be submitted and removed [Conformance] [It]
I0126 14:45:08.028]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:192
I0126 14:45:08.028] 
I0126 14:45:08.028]     Failed to observe pod deletion
I0126 14:45:08.028] 
I0126 14:45:08.028]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:180
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/3651/?log#log

### CODE REVIEW

**Comment by wojtek-t** [comment]
@dashpole @derekwaynecarr @vishh - FYI

**Comment by aleksandra-malinowska** [comment]
@k8s-bot ok to test

**Comment by aleksandra-malinowska** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
Merging to see if that helps with blocked merge queue.

**Comment by dashpole** [comment]
Interesting that the rate of flaking was so much higher in the [Kubelet node-e2e test suite](https://k8s-testgrid.appspot.com/google-node#kubelet) than in the [kubelet conformance-gce-node-e2e test suite](https://k8s-testgrid.appspot.com/google-node#kubelet-conformance-gce-e2e).  @vish, the deletion timeout for deletion during the container lifecycle hook tests is currently set at 2 minutes.  Should we increase that?

**Comment by yujuhong** [comment]
> [APPROVALNOTIFIER] This PR is APPROVED
> 
> The following people have approved this PR: wojtek-t
> 
> Needs approval from an approver in each of these OWNERS Files:
> 
> pkg/kubelet/OWNERS [wojtek-t]
> pkg/kubelet/volumemanager/OWNERS [wojtek-t]
> You can indicate your approval by writing /approve in a comment
> You can cancel your approval by writing /approve cancel in a comment

Huh... @wojtek-t you are not in these OWNER files. Did you do anything special get the PR approved? I wonder how this works...

**Comment by wojtek-t** [comment]
@yujuhong - I'm in the top leve owners file (pretty much to have someone outside US timezone be able to approve PRs). It's for situations like this when we need to revert something (I hope that indeed this was this PR and it fixed the problem).

**Comment by yujuhong** [comment]
> @yujuhong - I'm in the top leve owners file (pretty much to have someone outside US timezone be able to approve PRs). It's for situations like this when we need to revert something (I hope that indeed this was this PR and it fixed the problem).

Ah..I see. Didn't traverse the entire OWNERS tree. Thanks for answering.

**Pull request merged**
