### PR TITLE
use log funcs of core framework in the scalability and cloud package

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind cleanup
/kind testing 

**What this PR does / why we need it**:

use log funcs of core framework 

```
test/e2e/scalability/*.go
test/e2e/cloud/nodes.go
```

**Which issue(s) this PR fixes**:

refer #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by carlory** [comment]
ping @dims @cheftako @gmarek 

It's ready for review. Could you take a quick look at it?

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by cheftako** [comment]
Given code freeze, does this need to go into 1.16?

**Comment by carlory** [comment]
@cheftako @oomichi

The following /hold is for free merge pool bandwidth for 1.16-targeted PRs as #82108 (comment)
We need to wait for making these high priority PRs merged first.

/hold

**Comment by carlory** [comment]
as https://kubernetes.slack.com/archives/C2C40FMNF/p1567190475094100

/hold cancel

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/lgtm
/approve

**Comment by alejandrox1** [comment]
/hold
we should get consensus in testing-commons

**Pull request merged**
