### PR TITLE
kubeadm: clean up exited containers and network checkpoints

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
Not very important, but just some extra cleanup.

By the way, the cleanup logic heavily depends on kubelet's internal implementation. I'd suggest moving away from that in the future if possible (yes, I know it's not easy...). 

/cc @jbeda @mikedanese

**Comment by luxas** [comment]
@yujuhong Cool, thanks. I noticed this issue yesterday during KubeCon when the kubelet started reporting unready status some mins after init after not being able to delete old networks that don't exist anymore. Not sure if that's a bug or feature.

However, for kubeadm this patch is critical for v1.6.1, can you make a cherrypick ASAP, please?

**Comment by yujuhong** [comment]
> kubelet started reporting unready status some mins after init after not being able to delete old networks that don't exist anymore

I don't think this should happen. kubelet shouldn't become unready just because some pods/containers can't be cleanup. If you can reproduce it, feel free to file a bug.

I won't say this PR is critical, but it's always good to make sure you have a clean slate after running `reset`. I'll make a cherrypick PR.

**Pull request merged**
