### PR TITLE
Rename EnvVarSource.FieldPath -> FieldRef and add example

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by pmorie** [comment]
@bgrant0607 PTAL

**Comment by smarterclayton** [comment]
fieldPath: fieldPath?  Really?

**Comment by pmorie** [comment]
@smarterclayton Really.

**Comment by smarterclayton** [comment]
Ugh.... wasn't that supposed to be reference fieldPath?

**Comment by pmorie** [comment]
@smarterclayton I had thought @bgrant0607 explicitly wanted fieldPath for both.  I'll go back and read through the comments again.

**Comment by pmorie** [comment]
@smarterclayton https://github.com/GoogleCloudPlatform/kubernetes/pull/6739#issuecomment-95675877

**Comment by smarterclayton** [comment]
Hrm, I think seeing it in the actual API makes me think it was a bad decision.  We can revisit later but I'm not a fan of redundant redundancy.

----- Original Message -----

**Comment by pmorie** [comment]
@smarterclayton Yeah, I felt the same thing -- I'm trying to think of better names but coming up empty.

**Comment by bgrant0607** [comment]
ObjectFieldSelector.FieldPath needs to stay FieldPath in order to match ObjectReference.

Other possibilities for EnvVarSource.FieldPath:
* Field
* FieldRef
* ObjectFieldRef

**Comment by bgrant0607** [comment]
FieldRef makes the most sense to me.

**Comment by smarterclayton** [comment]
Agreed

**Comment by pmorie** [comment]
Alrighty, I will change it.

**Comment by pmorie** [comment]
@smarterclayton updated, PTAL

**Comment by smarterclayton** [comment]
LGTM, may need to regenerate docs as well (put them in their own commit).

**Comment by pmorie** [comment]
@smarterclayton I got no real diffs from regenerating

**Comment by smarterclayton** [comment]
Sorry, I meant swagger, not docs.

**Comment by pmorie** [comment]
@smarterclayton It's a lot of changes for the swagger spec -- do you want it in this PR?

**Comment by smarterclayton** [comment]
Separate commit.

**Comment by bgrant0607** [comment]
LGTM

**Comment by smarterclayton** [comment]
Will merge on green travis

**Comment by bgrant0607** [comment]
I recommend postponing the swagger updates to a separate PR. Unrelated changes are causing the validation test to fail when the swagger is updated.

**Comment by pmorie** [comment]
@bgrant0607 fine with me.

**Comment by smarterclayton** [comment]
It doesn't matter because travis will never give you a green

**Comment by bgrant0607** [comment]
What do you mean @smarterclayton? Shippable failed on this PR, apparently due to the swagger update.

cc @nikhiljindal

**Comment by smarterclayton** [comment]
It's been waiting for a good 4-5 hours to start

**Comment by bgrant0607** [comment]
Also, the generated swagger still contains fieldPath rather than fieldRef.

**Comment by pmorie** [comment]
@bgrant0607 Removed the swagger commit, I will look into that separately as a follow-up.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
It looks like we need to update go-restful again to get the `*int64` fix:
https://github.com/emicklei/go-restful/commit/63c8f08adbec998bb7b77d518d6df398499a8950

**Comment by bgrant0607** [comment]
Rerunning Shippable.

**Pull request merged**
