### PR TITLE
Update the COS kernel sha for node e2e gpu installer

### PR DESCRIPTION
**Pull request by vishh**
cc @mindprince

Relevant COS image - https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/image-config-serial.yaml#L19

### CODE REVIEW

**Comment by vishh** [comment]
cc @dchen1107

**Comment by mindprince** [comment]
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by vishh** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by Amey-D** [comment]
/lgtm

Confirmed that the kernel sha1 corresponds to image version cos-beta-59-9460-20-0.

**Comment by mindprince** [comment]
/retest
This is so incredibly frustrating!

**Comment by vishh** [comment]
@mindprince you can ignore the federation tests. They are known to be broken and do not affect merging.

**Comment by mindprince** [comment]
@vishh Submit Queue says: "Required Github CI test is not green: pull-kubernetes-federation-e2e-gce"
Can you manually merge it and then ok-to-test #46899

**Pull request merged**
