### PR TITLE
Fix summary_test.go ARM build

### PR DESCRIPTION
**Pull request by timstclair**
Fixes https://github.com/kubernetes/kubernetes/issues/33761

/cc @ixdy @luxas

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33778)

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot build this

**Comment by luxas** [comment]
This should be ok for me

**Comment by timstclair** [comment]
@k8s-bot gke e2e test this, issue: https://github.com/kubernetes/kubernetes/issues/33672

**Comment by ixdy** [comment]
LGTM assuming cross-build is happy

**Review by ixdy — APPROVED** [review]

**Comment by timstclair** [comment]
@k8s-bot gke e2e test this, issue: #33672

**Pull request merged**
