### PR TITLE
fix_translation_zh_CN

### PR DESCRIPTION
**Pull request by vonsago**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> /kind bug

**What this PR does / why we need it**:
fix_translation_zh_CN
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by xichengliudui** [comment]
The content here should be generated.

**Comment by xichengliudui** [comment]
Ref: https://github.com/kubernetes/kubernetes/blob/master/translations/README.md

>## Adding new translations
Edit the appropriate `k8s.po` file, `poedit` is a popular open source tool
for translations. You can load the `translations/kubectl/template.pot` file
to find messages that might be missing.

Once you are done with your `k8s.po` file, generate the corresponding `k8s.mo`
file. `poedit` does this automatically on save, but you can also run
`./hack/update-translations.sh` to perform the `po` to `mo` translation.

We use the English translation as the `msgid`.

**Comment by vonsago** [comment]
@xichengliudui   I read `./hack/update-translations.sh`, and I just fixed the translation of `zh_CN`, so I use this `msgfmt  translations/kubectl/zh_CN/LC_MESSAGES/k8s.po -o translations/kubectl/zh_CN/LC_MESSAGES/k8s.mo` to perform the `po` to `mo` translation.

**Pull request closed without merging**
