### PR TITLE
go-to-protobuf: fix wrong proto import dependencies due to wrong global type handling

### PR DESCRIPTION
**Pull request by sttts**
Before this PR the first occurance of e.g. "*string" will be made global, introducing import dependencies to totally unrelated packages in the produced .proto files.

### CODE REVIEW

**Comment by sttts** [comment]
@smarterclayton can you approve for the global changes of the fixed proto imports?

**Comment by mbohlool** [comment]
This did not fix my problem with cyclic imports. This one did: https://github.com/kubernetes/kubernetes/pull/67169

**Comment by smarterclayton** [comment]
This looks correct to me.  What was the cyclic error?

**Comment by sttts** [comment]
@smarterclayton @mbohlool I have straightened the logic around globals and locals. The result is that of @mbohlool's PR, but the logic is clear:
- register globals only once from their package
- add import when referencing other globals
-

**Pull request closed without merging**
