### PR TITLE
Remove kubectl convert command

### LINKED ISSUE #86536: `kubectl convert` was not removed in v1.17
**What happened**:

In v1.16 release note, `kubectl convert` will be removed in v1.17. However it still exists. Is this forgetting to remove it?

> `kubectl convert`, deprecated since v1.14, will be removed in v1.17.

- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove `kubectl convert` command.

**Which issue(s) this PR fixes**:
Fixes #86536

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
i think the commits can be squashed into one for this cleanup.
the bazel build doesn't seem happy:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86558/pull-kubernetes-verify/1209158065480273921

**Comment by liggitt** [comment]
/hold

See https://github.com/kubernetes/kubernetes/issues/86536#issuecomment-568762795

I expect the command will be moved out of kubectl rather than removed. 

cc @seans3

**Comment by tedyu** [comment]
@seans3 
Let me know if this PR can be reused for the move of the convert command.

**Comment by haosdent** [comment]
> I expect the command will be moved out of kubectl rather than removed.

Become a separate command?

**Comment by liggitt** [comment]
> Become a separate command?

xref https://github.com/kubernetes/kubectl/issues/725

**Comment by tedyu** [comment]
@seans3 
Let me know if I can help with the migration.

**Comment by soltysh** [comment]
/close
not to confuse users.

**Comment by tedyu** [comment]
This one somehow missed my Spring cleaning yesterday.

**Pull request closed without merging**
