### PR TITLE
Remove node object size annotation

### PR DESCRIPTION
**Pull request by lyzs90**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Details : https://github.com/kubernetes/kubernetes/issues/90833#issuecomment-762695597

**Which issue(s) this PR fixes**:

Part of #90833 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold

Shouldn't we first enable image-preloading and only then remove it?

**Comment by mm4tt** [comment]
In https://github.com/kubernetes/kubernetes/pull/97858, @lyzs90 made hollow nodes to pull image list from host nodes. So now the kubemark nodes have exactly the same images are real nodes in gce tests. I believe this allows us to get rid of this whacky "annotate logic" as it's not really needed anymore (assuming its goal of it was to compensate for missing images in the node object). Obviously with the image preload we'll go further - we'll add extra images to better much production setups where number of images is 2-3x of what we currently have. WDYT?

**Comment by wojtek-t** [comment]
1. Is the image-preloading already enabled by default in kubemark tests?

2. This is actually making kubemark tests more light, because we don't have 15kB of additinal images now.

**Comment by lyzs90** [comment]
> In #97858, @lyzs90 made hollow nodes to pull image list from host nodes.

hmm i may be missing something here, the changes I did was to allow hollow nodes to interact with the images on the real nodes. is the actual image pull happening elsewhere?

**Comment by mm4tt** [comment]
> 1. Is the image-preloading already enabled by default in kubemark tests?
> 2. This is actually making kubemark tests more light, because we don't have 15kB of additinal images now.

1. Currently, it's not enabled anywhere
2. True, but on the other hand we got an extra few KBs from the host node images.

**Comment by mm4tt** [comment]
Hmm, "pull" was a wrong word. Your change made the hollow nodes to "use" the host images, didn't it?

**Comment by lyzs90** [comment]
> Hmm, "pull" was a wrong word. Your change made the hollow nodes to "use" the host images, didn't it?

@mm4tt yep thats correct

**Comment by wojtek-t** [comment]
> Currently, it's not enabled anywhere

That's my point - let's not disable this one before we enable that one.

**Pull request closed without merging**
