### PR TITLE
update-codegen: rename "base"->"file" for clarity

### PR DESCRIPTION
**Pull request by thockin**
/kind cleanup
/sig architecture
/sig api-machinery

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
hmm
/hold

included in https://github.com/kubernetes/kubernetes/pull/122776

**Comment by thockin** [comment]
We should merge this first, then #122776

**Comment by aojea** [comment]
> We should merge this first, then #122776

why does it matter?

**Comment by thockin** [comment]
It only matter sso we have clean, single-topic  PRs

/retest

**Pull request merged**
