### PR TITLE
golint fixes in pkg/kubectl/cmd/auth

### PR DESCRIPTION
**Pull request by sayanarijit**
**What this PR does / why we need it**:

Refactoring #68176 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by nikhita** [comment]
Closing and reopening to trigger the right labels. This PR was created during a prow outage and so it misses some labels.

/close

**Comment by sayanarijit** [comment]
Closing this I will not be able to follow up on this for some time.

**Pull request closed without merging**
