### PR TITLE
Adding the storage version hash to the discovery API

### PR DESCRIPTION
**Pull request by caesarxuchao**
Extracted the API changes from https://github.com/kubernetes/kubernetes/pull/72942.

Implementing https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/35-storage-version-hash.md.

/sig api-machinery
/assign @caesarxuchao 
Keeping to myself until tests pass.
/kind feature

```release-note
Added alpha field storageVersionHash to the discovery document for each resource. Its value must be treated as opaque by clients. Only equality comparison on the value is valid.
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@liggitt this one needs a API approval. PTAL. Thanks.

**Comment by sttts** [comment]
@liggitt ptal.

**Pull request merged**
