### PR TITLE
updated example apparmor profile

### PR DESCRIPTION
**Pull request by krouser**
updated example apparmor profile from https://github.com/genuinetools/bane/blob/master/docker-nginx-sample

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by krouser** [comment]
> @krouser is all the whitespace changes meaningful?
> 
> If i just hide whitespace here's what i see: image
> 
> If that is good enough, please update the PR without the whitespace changes.

Hi dims, whitespaces removed and i've updated the PR. kindly check

**Comment by dims** [comment]
:( still there

image

**Comment by krouser** [comment]
> :( still there
> 
> image

Those are necessary whitespaces for the apparmor profile readability  :)

**Comment by dims** [comment]
@krouser new lines are ok, there are spaces there too

**Comment by krouser** [comment]
> @krouser new lines are ok, there are spaces there too

Yeah they're not necessary and I've removed them now.

**Comment by mkumatag** [comment]
Removing myself from this PR as I'm not really a SME for this one, @dims wondering if someone else can help us reviewing this PR?!
/uncc @mkumatag

**Pull request closed without merging**
