### PR TITLE
Revert "Adding trace to reflector initialization"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#73071

Given the discussion in https://github.com/kubernetes/kubernetes/pull/73209, this may not be merged immediately, so reverting this one to fix the issue.

/assign @sttts @nikhita 

@krzysied - FYI

### CODE REVIEW

**Comment by nikhita** [comment]
/kind bug
/priority critical-urgent
/lgtm


Thanks for fixing this real quick, @wojtek-t!

**Comment by wojtek-t** [comment]
> Thanks for fixing this real quick, @wojtek-t!

@nikhita - I wouldn't call this a fix... but yeah - no problem.

**Comment by nikhita** [comment]
/hold

Let's hold until we reach consensus in https://github.com/kubernetes/kubernetes/pull/73209 :)

**Comment by nikhita** [comment]
@wojtek-t I'll unhold this here to unblock the publishing-bot. Let's re-iterate on this later. :)

/hold cancel

**Comment by wojtek-t** [comment]
sure - that's fine

**Pull request merged**
