### PR TITLE
Update SECURITY_CONTACTS

### LINKED ISSUE #92090: Security contacts for cluster-bootstrap not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/cluster-bootstrap/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cluster-bootstrap/SECURITY_CONTACTS) file for the cluster-bootstrap repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by SamuelBagattin**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Updates SECURITY_CONTACTS according to https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#chairs
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/92090

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by SamuelBagattin** [comment]
I signed it 😊

**Comment by joelsmith** [comment]
To those being added to `SECURITY_CONTACTS`, plase drop a comment saying whether you agree to be listed as a security contact for cluster-bootstrap. Security contacts should agree to abide by the embargo policy the PSC uses (see https://git.k8s.io/security/private-distributors-list.md#embargo-policy).
/cc @justinsb
/cc @neolit123
/cc @timothysc
/cc @fabriziopandinic

**Comment by neolit123** [comment]
i'm sure at some point in time the SIG CL leads have made them self familiar with https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy
but getting them to LGTM here might be a bit difficult without pings on slack.

in any case LGTM on my side.

**Comment by SamuelBagattin** [comment]
I don't understand why e2e and integration tests are failing.
It is only documentation no ?
How can i fix it ?
/retest

**Comment by neolit123** [comment]
looks like the tests passed.
normally you just type the `/retest` command unless there is a related problem in the logs.

> Not mergeable. Must be in milestone v1.19.

we are in code freeze so this should merge after code-freeze is lifted in August.

but there is also discussion whether we can change the SECURITY_CONTACTS mechanic:
https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/0MUJBDGf3jg

**Comment by SamuelBagattin** [comment]
Hello,
any updates on the state of this PR ?
Is it still necessary to update security contacts ?

**Comment by neolit123** [comment]
Hi, on the kubernetes-dev mailing list there was a discussion that these files will be removed at some point so no need to update them.

We can close this and similar PRs. Sorry for the delayed response.

/close

**Pull request closed without merging**
