### PR TITLE
Skips Windows unrelated tests

### LINKED ISSUE #69871: Windows incompatible tests should be skippable
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig testing
/sig windows

**What happened**:

There are plenty of tests which cannot pass using Windows nodes due to various reasons. Those are some of them:

- seLinuxOptions are not supported on Windows.
- Running as an UID / GID is not supported on Windows.
- file permissions work differently on Windows, and they cannot be set in
  the same manner as on Linux.
- individual files cannot be mounted in Windows Containers.
- Cannot create container using Linux image (alpine) on Windows.

These kinds of tests should be skippable by passing the ``--node-os-distro=windows`` ginkgo argument.

**What you expected to happen**:

The tests fail when using Windows nodes, and they are not skipped when the ``node-os-distro`` is set to ``windows``.

Ideally, future tests will take into account if they should also pass on Windows nodes, and if not, they should be skipped.

**How to reproduce it (as minimally and precisely as possible)**:

Run the tests using Windows nodes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-rc.2
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Windows Server 1803 nodes
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others:

### PR DESCRIPTION
**Pull request by claudiubelu**
**What this PR does / why we need it**:

Some of the tests cannot pass using Windows nodes due to various reasons:

- seLinuxOptions are not supported on Windows.
- Running as an UID / GID is not supported on Windows.
- file permissions work differently on Windows, and they cannot be set in
  the same manner as on Linux.
- individual files cannot be mounted in Windows Containers.
- Cannot create container using Linux image (alpine) on Windows.

These kinds of tests should be skippable by passing the --node-os-distro=windows ginkgo argument.

/kind bug
/sig testing
/sig windows

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69871

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
SGMT, thank you for the PR @bclau 
waiting on approval by the maintainers.

/ok-to-test

**Review by feiskyer — COMMENTED** [review]
LGTM

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by spiffxp** [comment]
/hold
I hate to hold this but I feel like the question of whether these are allowed to be conformance and also skip has yet to be answered by sig architecture.  There was discussion of tainting nodes and running these tests in a hybrid cluster such that these would pass on valid *nix nodes, in which case I don't think this approach would work?  My impression is that TestContext.NodeOSDistro is something that is passed in via flags

**Comment by bclau** [comment]
Any updates regarding this PR?

**Comment by jingxu97** [comment]
cc @yujuhong 
Should we continue to hold it due to the comments https://github.com/kubernetes/kubernetes/pull/69872#issuecomment-434531044 or we can first approve this and then fix the issue? Thanks!

**Comment by bgrant0607** [comment]
I think this should be closed in favor of #73204

**Comment by neolit123** [comment]
> I think this should be closed in favor of #73204

+1
@bclau do you agree?

**Comment by bclau** [comment]
@neolit123 Sure, that's why this is now closed.

**Comment by neolit123** [comment]
duh, missed the closed icon.

**Pull request closed without merging**
