### PR TITLE
Reboot e2e test made more robust by using nohup.

### LINKED ISSUE #9062: Reboot e2e test is flaky
Two cases of Reboot e2e are flaky on Jenkins: unclean reboot (echo b | sudo tee /proc/sysrq-trigger) and kernel panic (echo c | sudo tee /proc/sysrq-trigger). They reboot only one node, while reboot of the second doesn't happen and causes test timeout:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-reboot/123/console
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-reboot/120/console

### PR DESCRIPTION
**Pull request by jszczepkowski**
Reboot e2e test made more robust by using nohup in ssh commands. Fixes #9062. Follow-up of #8784.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
What are the 'sleep 10's for?

**Comment by jszczepkowski** [comment]
To prevent race, one process is waiting for SSH connection to finish, the other is doing something nasty with the machine. So, I wanted to give some time to the first process to finish the session.

**Comment by jszczepkowski** [comment]
@quinton-hoole PTAL

**Comment by quinton-hoole** [comment]
You should rather explicitly wait on the condition that you require to be true (e.g. the previous SSH session closing, or whatever).  And fail with an explicit error if that does not occur within the timeout (e.g. 10 sec).  Otherwise you're inviting both flakiness and long delays in e2e tests, because we'll never know quite how much time to sleep, and it will inevitably be extended every time we see flakiness.

**Comment by quinton-hoole** [comment]
In fact looking a bit deeper, rebootNode() already does the checks for you.  So I don't believe that you need to sleep at all.

https://github.com/jszczepkowski/kubernetes/blob/e2e-nodes/test/e2e/reboot.go#L217

**Comment by jszczepkowski** [comment]
The check in rebootNode is checking if pods are running. My sleep is not related to pods, but to ssh session. The bash command issued by nohup may be started immediately, before ssh session is closed. But we don't want reboot/network partition to start before the ssh session is closed, so that the session will be cleanly closed (we have a check for this in rebootNode). So, the sleep makes this race much less likely.

Making this condition explicit will be really complicated and will obscure the test. I think the sleep is good enough.

**Comment by quinton-hoole** [comment]
Fair enough, but please put the above explanation in as a comment in the code for the benefit of the next person who has to some along and debug.  Thanks.  Then LGTM.

**Comment by jszczepkowski** [comment]
I've added the comments. The PR should be ready now.

**Pull request merged**
