### PR TITLE
OWNERS: add "reviewers" across the tree

### PR DESCRIPTION
**Pull request by calebamiles**
**What this PR does / why we need it**:

Expanding the group of people who are able to review PRs is important for the growing community of Kubernetes contributors. This change uses git commit history to calculate a list of possible reviewers for various parts of the project. 

**Which issue this PR fixes**
 `fixes #1422,#1389` 

**Release note**

The list of reviewers to OWNERS files has been updated using tooling [contributed by CoreOS](https://github.com/coreos/findowner) Thanks @hongchaodeng! 

**Overview**

This patch adds a set of reviewers to OWNERS files across various
packages in Kubernetes. The big idea is to maintain this list of people
who have worked on parts of the Kubernetes code base who can potentially
help with code reviews. This list will be consumed by bots that will
automatically ask people to review code and assign PRs for review.

Discussions:
- https://github.com/kubernetes/contrib/issues/1422
- https://github.com/kubernetes/contrib/issues/1389
- https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/EEEyMisp0M4

**Selected Reviewers**

There are 269 people being volunteered for the role of pkg level
reviewer based on their work in various packages. Of course if anyone
wishes to not be on this list they can comment on this PR to opt-out:

@03cranec, @249043822, @7ing, @AdoHe, @AlainRoy, @ArtfulCoder, @CodeJuan, @HaiyangDING, @JorgenG, @MHBauer, @MikeJeffrey, @MikeSpreitzer, @PiotrProkop, @Q-Lee, @Random-Liu, @WeixuZhuang, @ZhangZhenhua, @aanm, @aaronlevy, @abithap, @abrarshivani, @adityakali, @aknuds1, @alban, @aledbf, @alexhersh, @amygdala, @andreykurilin, @andronat, @andyzheng0831, @anish, @arun-gupta, @asalkeld, @ashcrow, @atombender, @aveshagarwal, @azell, @bbreslauer, @bigeasy, @bobbyrullo, @bparees, @bprashanth, @brendandburns, @bryk, @caesarxuchao, @caseydavenport, @chakri-nelluri, @childsb, @chrisleck, @chrislovecnm, @chuckbutler, @ciwang, @cjcullen, @clasohm, @colemickens, @colhom, @copejon, @coufon, @csrwng, @ctrlaltdel, @daizuozhuo, @dalanlan, @danwinship, @darron, @david-mcmahon, @davidopp, @dcbw, @dchen1107, @deads2k, @derekparker, @derekwaynecarr, @dims, @dlorenc, @dshulyak, @elsonrodriguez, @eosrei, @eparis, @epc, @epixa, @ericchiang, @erictune, @errm, @errordeveloper, @euank, @fabianofranz, @fabioy, @feihujiang, @feiskyer, @fejta, @fgrzadkowski, @foxish, @fraenkel, @freedev, @freehan, @fwalker, @gertipoppel, @ghodss, @girishkalele, @gmarek, @goltermann, @gouyang, @gtank, @gyuho, @harryge00, @hodovska, @hongchaodeng, @huang195, @huangyuqi, @humblec, @hurf, @hw-qiaolei, @imkin, @ingvagabund, @invenfantasy, @ivan4th, @ivant, @ixdy, @jackgr, @janetkuo, @jayunit100, @jcrugzz, @jdef, @jeffmendoza, @jeffvance, @jfchevrette, @jfrazelle, @jhadvig, @jiangyaoguo, @jianhuiz, @jijun2, @jimmidyson, @jingxu97, @jlowdermilk, @joe2far, @johscheuer, @jonboulle, @joshix, @jpiccari, @jsafrane, @jszczepkowski, @justinsb, @jvalencia, @k82cn, @kargakis, @karlkfi, @keegancsmith, @kennethkalmer, @keontang, @kevin-wangzefeng, @koep, @kolyshkin, @krousey, @kshafiee, @laushinka, @lavalamp, @liggitt, @linzichang, @liubin, @lixiaobing10051267, @luebken, @lukaszo, @luxas, @maciaszczykm, @madhusudancs, @magicwang-cn, @maisem, @mamikonyana, @markturansky, @marun, @mattf, @matthewdupre, @matthewrudy, @mattmoor, @matttproud, @mattyw, @mbforbes, @mbohlool, @mbruzek, @mdshuai, @metral, @mfanjie, @mfojtik, @mikebrow, @mikedanese, @mksalawa, @mlafeldt, @mml, @mnshaw, @mqliang, @mvdan, @mwielgus, @mzupan, @nagarjung, @ncdc, @nebril, @nhlfr, @nikhiljindal, @ohtake, @olegshaldybin, @olivierlemasle, @onorua, @oszi, @paralin, @philips, @ping035627, @piosz, @pires, @pmorie, @porridge, @pweil-, @pwittrock, @quinton-hoole, @rajdeepd, @rata, @rbuskens, @resouer, @rhcarvalho, @rmmh, @robdaemon, @roberthbailey, @rombie, @ronnielai, @rootfs, @saad-ali, @screeley44, @sdminonne, @shaunparker, @simon3z, @simonswine, @sjenning, @sjpotter, @smarterclayton, @soltysh, @spothanis, @spxtr, @sroze, @stefwalter, @sttts, @swagiaal, @tgraf, @therc, @thockin, @thomasfricke, @timothysc, @timstclair, @tmrts, @tschottdorf, @tummychow, @tyangliu, @uluyol, @ursuad, @victorgp, @vishh, @wfhartford, @wojtek-t, @wongma7, @wstrange, @xelalexv, @xiangpengzhao, @yehuis4, @yifan-gu, @ysh7, @yujuhong, @yuvipanda, @zenly, @zhengguoyong, @zhouhaibing089, @zmerlynn, @zreigz

You may opt-out in two different ways:
1. Remove permanently; your GitHub handle will be added to a blacklist
2. Remove from a single package; your GitHub handle will be added to a
   pkg blacklist and removed from this patch

Please comment on this issue if you want to opt-out. See the patch for
the pkgs you are in.

**Implementation**

The basic algorithm:
- Walk directories of "pkg" and gather up commit history
- It selects top N (default is 3) committers for each directory. If there are more than N people having the same number of commits, it outputs them all.
- It ranks people (identified by GitHub handle) by the number of commits they made.
- The commits are pulled from past 1 year history excluding "merge" commits.

https://github.com/coreos/findowner

_Implementation Notes_
- It has a depth limit (default is 3). For example, given depth limit 3, "./pkg/apis/apps" is allowed, while "./pkg/apis/apps/install" isn't.
- It has an excluded list. See "./main.go" excludedDirList variable.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31567)

### CODE REVIEW

**Comment by philips** [comment]
@calebamiles Hrm, this didn't page everyone @calebamiles. I guess there must be some limit to the number of people that can be pinged with a single message. I guess we just shard by copy/pasting the unlinked ones into the comments section with "cc"?

**Comment by lavalamp** [comment]
so we have "assignees" and "reviewers"? I thought one of those was supposed to be "approvers"?

**Comment by calebamiles** [comment]
I believe you're correct @lavalamp. I'll update this PR.

**Comment by davidopp** [comment]
How does one patch the Git commit into one's local client? That seems to be the only way to view this change, since Github won't show the whole commit because it has too many files.

**Comment by asalkeld** [comment]
@davidopp try this

```bash
curl https://github.com/calebamiles/kubernetes/commit/2c8cb0b12655691e4d0b67f13df890dcdfeb4dcb.patch | patch -p1
```

**Comment by asalkeld** [comment]
there seems to be a "-" file getting generated, is this correct?

**Comment by grodrigues3** [comment]
See also https://github.com/kubernetes/contrib/pull/1429.

**Comment by philips** [comment]
STATUS: waiting on @bkeepers to find out from GitHub support how we ping everyone on this issue without hitting the arbitrary 50 notification limit.

**Comment by MHBauer** [comment]
Opt out of `cluster/photon-controller/`. I would not mind reviewing bash scripts in general.

**Comment by brendandburns** [comment]
Let's at the very least discuss this at community meeting.  I would kind of rather gradually bring people in rather than bulk add 260+ people.

**Comment by smarterclayton** [comment]
I don't think a year is enough - there is code that is 2 years old that the owners are not actively contributing to, just reviewing.

**Comment by philips** [comment]
@smarterclayton so you would like to see 2 years vs 1 year? @calebamiles do you think you could generate that and see how much churn there would be in the patch?

**Comment by vishh** [comment]
We should probably not auto-nominate a contributor as a reviewer unless they opt-in for reviewing. Otherwise we risk PRs becoming stale without timely reviews.

**Comment by philips** [comment]
@vishh reviewers will be rotated and @calebamiles will be emailing everyone to opt-out if they wish to. We all agree we don't want to have people who don't want to do it and latency is bad. So, I think the only thing we are debating is opt-in vs opt-out; and it is sort of a coin flip. So, we are going with opt-out. This will also be discussed on the Thursday meeting.

**Comment by calebamiles** [comment]
I apologize to the robots and the wonderful humans who edit their assigned labels but I had to create a new PR for this work: https://github.com/kubernetes/kubernetes/pull/31752

I have expanded the commit history search to two years @smarterclayton. I will be reaching out to the potential pool of reviewers @vishh and I'll update the PR as people express their preference for participating in the reviewer process. I have also addressed the discussion of promoting the current reviewers to approvers which was brought up in sig-contribx. We will likely be discussing this approach to expanding the pool of reviewers at an upcoming [k8s community meeting](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.en8cy6hno0c6) for interested parties.

**Pull request closed without merging**
