### PR TITLE
Automated cherry pick of #43642

### PR DESCRIPTION
**Pull request by enisoc**
Cherry pick of #43642 on release-1.6.

#43642: Update a few regex patterns to support release candidates

### CODE REVIEW

**Comment by enisoc** [comment]
@ixdy The tests here are still failing with `Version doesn't match regexp` even though it passed on `master`. Any idea why?

**Comment by ixdy** [comment]
Oh, get-kube.sh is [embedded in the e2e-image](https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L64). We'll need to merge the fix in master and then rebuild the e2e-image.

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
oh, gross, I need to bump the image tag in another file, but apparently [I can't](https://github.com/kubernetes/test-infra/blob/master/jenkins/dockerized-e2e-runner.sh#L33-L35)?

@fejta @krzyzacy I need a new kubekins-e2e image for PR testing to work against 1.6. how do I resolve this?

**Comment by fejta** [comment]
Use the head image

**Comment by fejta** [comment]
Aka migrate to --json with all the other jobs. Or keep using the existing image

**Comment by ixdy** [comment]
I don't have the time to migrate the PR jobs to use --json.

I'm going to checkout the test-infra repo at 331e93f3 and then build/push a new `v20170324-331e93f3` image, which should still work with the PR jobs, but will have a newer get-kube.sh.

**Comment by krzyzacy** [comment]
update the tag in dockerized-e2e-runner.sh for pr jobs...

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
