### PR TITLE
Automated cherry pick of #63770: Implement Skip() for ingress upgrade test

### PR DESCRIPTION
**Pull request by MrHohn**
Cherry pick of #63770 on release-1.10.

#63770: Implement Skip() for ingress upgrade test

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Cherrypicking to fix https://k8s-testgrid.appspot.com/google-gke-staging#gke-staging-1-9-1-10-upgrade-cluster.
/assign @rramkumar1 @MaciekPytel 
cc @liyinan926

**Comment by MaciekPytel** [comment]
@kubernetes/test-infra-maintainers Both @MrHohn and @rramkumar1 are approvers in test. Why does the bot think it's not approved? Some bug?

**Comment by MrHohn** [comment]
Both @rramkumar1 and I were added to the approver list after 1.10. The robot might look at the OWNER file in 1.10 branch since this is cherrypick...

/assign @bowei 
for approval.

**Comment by stevekuznetsov** [comment]
Yes, we recently changed to look at OWNERS in the branch being targeted AFAIR.

**Comment by MrHohn** [comment]
/ki/nd bug
/priority important-soon
/sig network

**Comment by MrHohn** [comment]
@MaciekPytel Thanks!

**Pull request merged**
