### PR TITLE
fix typo: its

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
fix typo: change its to it's

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by cblecker** [comment]
@k8s-bot ok to test
/lgtm
/release-note-none

**Comment by cblecker** [comment]
Hmm.. this PR is missing the CLA label. @zhangxiaoyu-zidif looks to have signed the CLA previously.
https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr%20author%3Azhangxiaoyu-zidif

@Random-Liu if it doesn't add automatically after this comment, could you add the right CLA label?

**Comment by cblecker** [comment]
@k8s-bot verify test this

**Comment by Random-Liu** [comment]
@cblecker Could you try "I signed it"?

If not working, I could manually add it. :)

**Comment by Random-Liu** [comment]
Ah, it's not your PR.

**Comment by zhangxiaoyu-zidif** [comment]
I signed it

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot I signed it

**Comment by zhangxiaoyu-zidif** [comment]
@Random-Liu 
it doesn't work. could you manually add it=)
Thanks a lot.

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot bazel test this
@k8s-bot kops aws e2e test this
@k8s-bot unit test this

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by deads2k** [comment]
You have several typo pulls:

 1. https://github.com/kubernetes/kubernetes/pull/43904
 1. https://github.com/kubernetes/kubernetes/pull/44708
 1. https://github.com/kubernetes/kubernetes/pull/45327
 1. https://github.com/kubernetes/kubernetes/pull/45395
 1. https://github.com/kubernetes/kubernetes/pull/45592

Can you please combine them into a single pull?

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k 
#43904 : I can't solve the test failed. I don't know why.
#44708: I miss cla label. But I signed it.
#45327 : This only one can be gathered.
#45395:  I can't solve the test failed. I don't know why.
#45592: The latest one I pull request.
In fact, that's all.

**Comment by zhangxiaoyu-zidif** [comment]
I can't solve the label missing. so I close it.

**Pull request closed without merging**
