### PR TITLE
Update Dashboard UI addon to v1.0.0

### PR DESCRIPTION
**Pull request by bryk**
Release details:
https://github.com/kubernetes/dashboard/releases/tag/v1.0.0

### CODE REVIEW

**Comment by bryk** [comment]
@piosz Can you review this?

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by piosz** [comment]
from failed travis:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Pull request merged**
