### PR TITLE
Kubelet read pods from file

### PR DESCRIPTION
**Pull request by wojtek-t**
This PR is the continuation of #5598
There are two separate commits, since the first one is just a refactoring to allow code sharing.

cc @vmarmol @yujuhong

### CODE REVIEW

**Comment by wojtek-t** [comment]
I've just run e2e tests - all tests are passing:
Ran 28 of 30 Specs in 1582.130 seconds
SUCCESS! -- 28 Passed | 0 Failed | 2 Pending | 0 Skipped I0320 12:51:24.240236   21632 driver.go:89] All tests pass

**Comment by vmarmol** [comment]
LGTM minus the move to default. I'm okay merging as-is if you've gone home for the day.

**Comment by wojtek-t** [comment]
If possible, I would prefer to do it in a separate PR. But decision is up to you.

**Comment by vmarmol** [comment]
SGTM, merging. Thanks @wojtek-t!

**Comment by wojtek-t** [comment]
Thanks!

**Comment by erictune** [comment]
Document this somewhere.

**Comment by yujuhong** [comment]
I believe both integration and e2e tests use manifest files only (since kubelet could not read pods before). Could you add some more tests for reading pods? Eventually all tests should use pods, but I am not sure when we're going to deprecate container manifests.

**Comment by bgrant0607** [comment]
We are in the process of wrapping up and enabling v1beta3 now. @nikhiljindal is working on running tests using v1beta3 as well as v1beta1. We should do the same for the file-based pods -- run both formats for now.

**Comment by wojtek-t** [comment]
I did some checking and it seems that none of the e2e tests is using Kubelet mechanism to read pods from http/file. IIUC, currently the only existing test for it (except from unit tests) are integration tests. I'm going to change them to test both Pod & ContainerManifest format.

**Comment by erictune** [comment]
That sounds good.  Suggest you write a standalone integration test in the
style of test/integration/client_test.go instead adding to the one big
monolithic integration test, cmd/integration/integration.go.  That one does
not scale in terms of debug.

**Pull request merged**
