### PR TITLE
cherry pick of #84802: Ensure health probes are created for local traffic policy UDP

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #84802 on release-1.14.

#84802: Ensure health probes are created for local traffic policy UDP

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

**Does this PR introduce a user-facing change?**:

```release-note
Ensure health probes are created for local traffic policy UDP services on Azure
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by justaugustus** [comment]
@nilo19 -- This cherry pick needs to include the release note from the original PR: https://github.com/kubernetes/kubernetes/pull/84802

**Comment by nilo19** [comment]
> @nilo19 -- This cherry pick needs to include the release note from the original PR: #84802

Got it. Thank you @justaugustus.

**Comment by justaugustus** [comment]
For CP approval: @kubernetes/patch-release-team

**Pull request merged**
