### PR TITLE
Golint pkg/auth/authorizer/abac

### PR DESCRIPTION
**Pull request by jlucktay**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix `golint` failures in the `pkg/auth/authorizer/abac` package.

**Which issue(s) this PR fixes**:
ref: #68026

**Special notes for your reviewer**:
It looks like my git-fu needs work; I let a merge commit in somehow. 😔

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fejta** [comment]
For auth approval:
/assign erictune liggitt deads2k

/lgtm
/ok-to-test
/approve

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @jlucktay 
please squash the commits into one and force push

/kind cleanup
/priority backlog

**Comment by jlucktay** [comment]
Just had a go at squashing my commits down to one, and then force-pushed, thank you @neolit123 😃 
Please let me know if that looks OK now.

**Comment by jlucktay** [comment]
When I looked through the TestGrid and Velodrome links on [the flaky tests page](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md), the `pull-kubernetes-e2e-gce` test that failed showed up right at the top of the leaderboards. 🙁 

/retest

**Pull request merged**
