### PR TITLE
[release-1.25] [go] Bump images, versions and deps to use Go 1.20.8

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.20.8

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3242

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Go 1.20.8
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

Note: this also bumped the protoc version in response to  https://github.com/kubernetes/release/pull/3147 which bumped the protoc version in the cross image. If we need to roll that version back, we need to revert this or roll forward to a new set of cross images. 

/assign @saschagrunert @xmudrii  @puerco @Verolop @liggitt @dims 
cc @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
