### PR TITLE
Add support for 3rd party objects to kubectl label

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/24583

@kubernetes/rh-ux

### CODE REVIEW

**Comment by liggitt** [comment]
does the same applies to `annotate`?

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by AdoHe** [comment]
@liggitt @brendandburns I think we should also apply this to `annotate` cmd.

**Comment by janetkuo** [comment]
Suggest adding a test

**Comment by brendandburns** [comment]
@janetkuo refactored to make testing easier, and test added, ptal.

thanks!
--brendan

**Comment by brendandburns** [comment]
@janetkuo friendly Monday ping on this one.

Thanks!

**Comment by brendandburns** [comment]
@janetkuo ping on this one, thanks.

**Comment by AdoHe** [comment]
LGTM.

**Comment by janetkuo** [comment]
Sorry, needs a rebase now.

**Comment by brendandburns** [comment]
@k8s-bot unit test this please issue: #25645

**Comment by janetkuo** [comment]
Please squash and this need another rebase now.

**Comment by brendandburns** [comment]
squashed and rebased

**Comment by brendandburns** [comment]
@k8s-bot unit test this issue: #26181

**Pull request merged**
