### PR TITLE
Fix flaky 'shouldn't trigger additional scale-ups during processing scale-up' test

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
NONE
```

### CODE REVIEW

**Comment by losipiuk** [comment]
priority critical/urgent

**Comment by losipiuk** [comment]
@mwielgus could you set milestone 1.13 on this one for me.

**Comment by AishSundar** [comment]
@losipiuk @mwielgus @bskiba is there a issue this PR actually addresses? We are in code for 1.13 and master is closed for any changes except really critical fixes. I see this PR had a really short turnaround and missed the release team's radar. Can you provide a reasoning for why this PR is critical in 1.13?

/cc @jberkus @nikopen 
/cc @kubernetes/sig-autoscaling-bugs

**Comment by nikopen** [comment]
/lgtm

@AishSundar seems like it's sig-autoscaling fixing a CI failing test. AFAIK there doesn't need to be an 'issue' ticket necessarily. depending on CI and other factors PRs normally continue to get merged until the last days of when the window closes.

**Comment by AishSundar** [comment]
@nikopen  I would still like to know which test this PR is addressing. at this point in the release cycle we only allow critical fixes that are needed for release stability and will affect 1.13 if not addressed. Test flakes dont qualify for that bar. Also

**Comment by losipiuk** [comment]
@AishSundar sorry for not waiting a bit with the merge. My impression is we were less strict on freeze when it came to test-only changes during previous releases. With that said I am fine with being more strict with that actually and will give release team more time to react on subsequent changes.

As to your questions about the change.

The test fixed is:
`[sig-autoscaling] Cluster size autoscaling [Slow] shouldn't trigger additional scale-ups during processing scale-up [Feature:ClusterSizeAutoscalingScaleUp]`
from https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling.

Strictly speaking it is not 1.13 critical, yet it improves world, allowing us to better asses if we introduced bug in CA or not. We are yet to send out an CA alpha release candidate for 1.13 branch and with flaky tests it is harder to assess if it is actually working with K8S release being cut out or not.

**Comment by aleksandra-malinowska** [comment]
>  at this point in the release cycle we only allow critical fixes that are needed for release stability and will affect 1.13 if not addressed. Test flakes dont qualify for that bar.

The problem here is that while Cluster Autoscaler is an optional addon, both e2e tests for it and default GCE deployment config live in this repository.

These tests aren't K8s release blocking, but they're critical for Cluster Autoscaler release. We'll still have to build it just before 1.13 and send another PR to update the version here. This also means that cherry-picks that aren't merged to master are sometimes necessary to either fix tests, or update version (to the next patch release, e.g. 1.3.0 -> 1.3.1). 

I believe the unofficial practice so far was stricter rules for core code changes than for e2e tests and GCE config (under /test and /cluster/gce).

Long-term, we could probably limit the number of PRs by moving tests out of here, which is already the case for VPA. As for the default GCE config living under /cluster/gce, this is a broader problem and I don't know if we can avoid PRs for updating versions unless it changes.

**Pull request merged**
