### PR TITLE
Make sure the previous symlink file is deleted before trying to create a new one

### LINKED ISSUE #49105: Transient /var/lib/docker prevents correct container log symlink
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

I have a transient local disk mounted under /var/lib/docker in order to take advantage of faster IO on Azure VMs. This means that all that data is lost when a reboot occurs, but the rest of the data outside that mountpoint persists. After the reboot, the existing pods are relaunched, and kubelet is unable to create the log file symlinks because they already exist, but they are pointing to an invalid place, that container no longer exists. Here are the relevant log lines:

```
Jul 18 09:54:41 node-2-vm kubelet-wrapper[773]: E0718 09:54:41.752901     773 remote_runtime.go:203] StartContainer "b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35" from runtime service failed: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log" to the container log file "/var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log" for container "b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35": symlink /var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log /var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log: file exists
Jul 18 09:54:41 node-2-vm kubelet-wrapper[773]: E0718 09:54:41.752978     773 kuberuntime_manager.go:719] container start failed: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log" to the container log file "/var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log" for container "b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35": symlink /var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log /var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log: file exists: Start Container Failed
Jul 18 09:54:41 node-2-vm kubelet-wrapper[773]: E0718 09:54:41.753007     773 pod_workers.go:182] Error syncing pod f4c0303476d69c6f78ffd13253de3723 ("kube-proxy-node-2-vm_kube-system(f4c0303476d69c6f78ffd13253de3723)"), skipping: failed to "StartContainer" for "kube-proxy" with rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log" to the container log file "/var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log" for container "b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35": symlink /var/lib/docker/containers/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35/b27338f68b9fff70a321f0887bceb45707fe4375e948201c0ea19ac087b64f35-json.log /var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log: file exists: "Start Container Failed"
Jul 18 09:55:32 node-2-vm kubelet-wrapper[773]: E0718 09:55:32.418162     773 remote_runtime.go:203] StartContainer "c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424" from runtime service failed: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log" to the container log file "/var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log" for container "c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424": symlink /var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log /var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log: file exists
Jul 18 09:55:32 node-2-vm kubelet-wrapper[773]: E0718 09:55:32.418212     773 kuberuntime_manager.go:719] container start failed: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log" to the container log file "/var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log" for container "c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424": symlink /var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log /var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log: file exists: Start Container Failed
Jul 18 09:55:32 node-2-vm kubelet-wrapper[773]: E0718 09:55:32.418253     773 pod_workers.go:182] Error syncing pod d700822b-6aff-11e7-80e8-000d3a2a0829 ("omsagent-8npxv_kube-system(d700822b-6aff-11e7-80e8-000d3a2a0829)"), skipping: failed to "StartContainer" for "omsagent" with rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log" to the container log file "/var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log" for container "c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424": symlink /var/lib/docker/containers/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424/c87d32fd34acbb11486b28a8eaaee2553dd83516c2ebe7552662599046300424-json.log /var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log: file exists: "Start Container Failed"
```

The old symlinks are there:
```
# ls -l `find /var/log/pods/ -name *.log`
lrwxrwxrwx. 1 root root 165 Jul 17 14:56 /var/log/pods/d700822b-6aff-11e7-80e8-000d3a2a0829/omsagent_0.log -> /var/lib/docker/containers/1488f596179a3a6da1b818cc658b975c37aa4346beceef2158af82a89b3de84a/1488f596179a3a6da1b818cc658b975c37aa4346beceef2158af82a89b3de84a-json.log
lrwxrwxrwx. 1 root root 165 Jul 17 14:44 /var/log/pods/f4c0303476d69c6f78ffd13253de3723/kube-proxy_0.log -> /var/lib/docker/containers/8cafac3d554bd13d858a7843aed1f51a02ec125291d89209d9407e31fd2b010b/8cafac3d554bd13d858a7843aed1f51a02ec125291d89209d9407e31fd2b010b-json.log
```

**What you expected to happen**:

The correct symlinks should overwrite the old ones.

**How to reproduce it (as minimally and precisely as possible)**:

Erase /var/lib/docker between reboots with existing pods.

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: Azure VMs
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1409.6.0 (Ladybug)
- Kernel (e.g. `uname -a`): Linux node-2-vm 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux
- Install tools: https://github.com/edevil/kubernetes-deployment

### PR DESCRIPTION
**Pull request by edevil**
**What this PR does / why we need it**:

It deletes possibly existing symlinks to container log files.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #49105

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by yujuhong** [comment]
I'm ok with this change, but as kubelet/dockershim writes more things to the disk, manually deleting some states (e.g., containers) is likely to cause problems.

/lgtm

**Comment by yujuhong** [comment]
@k8s-bot  ok to test

**Comment by fejta** [comment]
/retest
I suspect this is PR doesn't build anymore?

**Comment by edevil** [comment]
The error in the test does not seem related to this PR...

**Comment by edevil** [comment]
The error from the test seems related to OAuth credentials having expired:
```
I0719 20:47:11.369] Your "OAuth 2.0 Service Account" credentials are invalid. Please run
I0719 20:47:11.370]   $ gcloud auth login
I0719 20:47:11.370] Type position out of range
I0719 20:47:24.519] CommandException: 1 file/object could not be transferred.
I0719 20:47:24.631] FAILED
```

**Comment by yujuhong** [comment]
> The error from the test seems related to OAuth credentials having expired:

Looks like a test-infra issue.

/retest

**Comment by edevil** [comment]
The tests are green.

**Comment by yujuhong** [comment]
Failed due to #49320

/retest

**Comment by edevil** [comment]
Can/should this be backported to 1.7?

**Pull request merged**
