### PR TITLE
Remove CNI in kubeet

### PR DESCRIPTION
**Pull request by yanghesong**
CNI is useless as dockershim is removed

Signed-off-by: yanghesong <hesong.yang@foxmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Dockershim has been removed, refer to #97252. CNI will never be used by kubelet.
#### Which issue(s) this PR fixes:

Fixes #97252

#### Special notes for your reviewer:
CNI will never be used by kubelet.
#### Does this PR introduce a user-facing change?

```release-note
No
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adisky** [comment]
It is already covered in this PR https://github.com/kubernetes/kubernetes/pull/106907/files

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc yanghesong

**Comment by sftim** [comment]
/hold

We still want networking in Kubernetes. I don't understand the motivation for removing CNI support. Were you confusing CNI support with dockershim @yanghesong ?

**Comment by SergeyKanzhelev** [comment]
> It is already covered in this PR https://github.com/kubernetes/kubernetes/pull/106907/files

/close

**Pull request closed without merging**
