### PR TITLE
Remove unused cadvisor/storage/bigquery package

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by vmarmol** [comment]
Did godep recommend this change?

**Comment by kargakis** [comment]
> Did godep recommend this change?

I didn't run godep so I guess the answer is no but the package in question cannot be found in the json file and by grepping I din't see it used anywhere in the code.

**Comment by vmarmol** [comment]
The cAdvisor package as a whole is brought in "github.com/google/cadvisor/..." some of that code does depend on this package (although I know it to be unused, it may affect the build). I'm also not sure this won't be brought back by godep when we update the package.

**Comment by vmarmol** [comment]
Instead of this, we can update the cAdvisor oauth2 to the new one. I don't think removing this will work unfortunately.

**Comment by kargakis** [comment]
> Instead of this, we can update the cAdvisor oauth2 to the new one. I don't think removing this will work unfortunately.

I have submitted a PR there about this: https://github.com/google/cadvisor/pull/610

**Comment by kargakis** [comment]
@vmarmol are you ok with reopening this PR and bumping cadvisor from here?

**Comment by vmarmol** [comment]
@kargakis SGTM

**Comment by kargakis** [comment]
@vmarmol should I bump the whole cadvisor or just the bigquery package? Also there is no latest tag that I can bump to.

**Comment by vmarmol** [comment]
One the other PR goes in feel free to bump all of cAdvisor so it is in a consistent version. We'll need to tag a new release this week and update the dep.

**Pull request closed without merging**
