### PR TITLE
kubelet: add support for reverse-proxying metrics from CRI

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Currently, the Kubelet relays cAdvisor's Prometheus metrics that are collected for containers. One piece of this relaying is these metrics are propegated through the kubelet's HTTP endpoint. This endpoint has a number of quality of life aspects: there is authentication, and proxying by the kube API. As we move to the CRI implementation broadcasting these metrics, it would be best if those QOL aspects aren't lost.

Do this by introducing a new CRI endpoint: MetricsEndpoints, which allows the CRI implementation to specify endpoints that it wishes the kubelet to broadcast on its behalf. Then, on server registration, Kubelet can query the CRI to ask for these, and do the relaying.
 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Add Kubelet support for MetricsEndpoints CRI call. This allows a CRI implementation (CRI-O/containerd) to specify a metrics endpoint it wants the kubelet to reverse proxy. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2371
```

### CODE REVIEW

**Comment by haircommander** [comment]
Note: since we don't have support in CRI implementations yet, and this is just at alpha stage, I have not dropped the corresponding relaying from cAdvisor for `/metrics/cadvisor`. That will be done for beta.

**Comment by bobbypage** [comment]
Thanks @haircommander for your work on this!

As part of the CRI-stats effort it will definitely be important to have a place to redirect /metrics/cadvisor calls. 

I would prefer that the endpoint would be provided via kubelet config instead of the CRI. This would allow the prometheus endpoint to be decoupled from the CRI implementation, for example you could imagine a separate component that would fetch the stats from the CRI and convert it to Prometheus format. By having it as a separate component, it decouples the Prometheus exporting of these metrics from the core CRI implementation.

**Comment by haircommander** [comment]
Fair enough! While I'd prefer to use the CRI to allow for atomic updates to the location (if the kubelet queries the CRI, then it can change the host/port without a corresponding kubelet config change). However, I'm sympathetic to the idea that it could be done by a plugin instead of in-tree of the CRI.

Here's an alternative: https://github.com/kubernetes/kubernetes/pull/111357

**Comment by mikebrow** [comment]
either way works for me.. noting at some point it would be preferable to reduce proxies and format conversions for metrics and logs where possible.

**Comment by haircommander** [comment]
> either way works for me.. noting at some point it would be preferable to reduce proxies and format conversions for metrics and logs where possible.

I agree. I believe this should only be used to preserve the proxying behavior kubelet already does for cadvisor (for a user curling the kubelet endpoint). I think the runtime (or plugin) should report the metrics directly to promethus to avoid the extra hop

**Comment by haircommander** [comment]
we've opted for a different approach https://github.com/kubernetes/enhancements/pull/3559

**Pull request closed without merging**
