### PR TITLE
Fix race condition between Pop and Close FIFO queue

### LINKED ISSUE #90581: Racy usage of sync.Cond in client-go/tools may cause goroutine leaks
**What happened**:
Race conditions found on 2 usages of sync.Cond in client-go/tools/cache.DeltaFIFO and client-go/tools/watch/eventProcessor.  I don't know how harmful they are since the buggy interleaving is hard to trigger. They may lead to goroutine leaks to my understanding. They have similar causes and I put them in one issue here for ease of triage. 

1. DeltaFIFO

When `(*DeltaFIFO).Pop()` and `(*DeltaFIFO).Close()` are invoked concurrently on an empty queue, the `f.cond.Wait()` in `(*DeltaFIFO).Pop()` may miss the signal from `(*DeltaFIFO).Close()`.

The `f.cond.Wait()` is guarded by the for-loop below. It appears that `f.cond.Wait()` should not be called if the FIFO queue is already closed, hence the `f.IsClosed()` check at line 475.

https://github.com/kubernetes/kubernetes/blob/961a5ed144cf0f2f4e2d858beb8cc0cfdd822c1b/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L467-L480

However, the `f.IsClosed()` check above may race with `f.Close()`:

https://github.com/kubernetes/kubernetes/blob/961a5ed144cf0f2f4e2d858beb8cc0cfdd822c1b/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L206-L211

Specifically, when the queue is empty and not closed, `f.Pop()` will reach the `f.cond.Wait()`. Between the `f.IsClosed()` check and `f.cond.Wait()`, another goroutine can call `f.Close()` and the broadcast on `f.cond` will be missed. Consequently, `f.cond.Wait()` may block indefinintely and miss the broadcast on `f.cond` from `f.Close()`.

Note that `f.Pop()` holds `f.lock` while `f.Close()` and `f.IsClosed()` hold `f.closedLock`. So `f.Close()` can interleave with `f.Pop()`.

Here is a stack trace found by our tool while running `TestMetadataSharedInformerFactory`. The tool is based on the Go race detector.
```
(*sync.Cond).Broadcast/Signal() at 0x00c00009c028 by goroutine 17:
  k8s.io/client-go/tools/cache.(*DeltaFIFO).Close()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go:210 +0xa8
  k8s.io/client-go/tools/cache.(*controller).Run.func1()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:128 +0x67

(*sync.Cond).Wait() at 0x00c00009c028 by goroutine 10:
  k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go:479 +0xbc
  k8s.io/client-go/tools/cache.(*controller).processLoop()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:179 +0x83
  k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:177 +0x41
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb3
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x10d
  k8s.io/apimachinery/pkg/util/wait.Until()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4cc
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:410 +0x7b1

Goroutine 17 (running) created at:
  k8s.io/client-go/tools/cache.(*controller).Run()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:126 +0xbe
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:410 +0x7b1

Goroutine 10 (running) created at:
  k8s.io/client-go/metadata/metadatainformer.(*metadataSharedInformerFactory).Start()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/metadata/metadatainformer/informer.go:90 +0x282
  k8s.io/client-go/metadata/metadatainformer.TestMetadataSharedInformerFactory.func7()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/metadata/metadatainformer/informer_test.go:141 +0x718
  testing.tRunner()
      /Users/yahuis/lab/go-exp/go/src/testing/testing.go:954 +0x1eb
```

I did some research and found #37137 introduced the bug while trying to fix exactly the issue: "stop controller when the stop channel is closed and the queue is empty". The fix doesn't appear to solve the issue completely.

One suggested fix: use `f.lock` in `f.Close()` and `f.IsClosed()` instead of `f.closedLock`. This would enforce atomicity between the `f.IsClosed()` check and `f.cond.Wait()` in `f.Pop()`.

2. eventProcessor

This is similar to DeltaFIFO. In between `!e.stopped()` and `e.cond.Wait()`:

https://github.com/kubernetes/kubernetes/blob/961a5ed144cf0f2f4e2d858beb8cc0cfdd822c1b/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go#L59-L65

Another goroutine can call `e.stop()`:

https://github.com/kubernetes/kubernetes/blob/961a5ed144cf0f2f4e2d858beb8cc0cfdd822c1b/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go#L98-L101

This would cause the signal on `e.cond` to be missed by the above `e.cond.Wait()`, leading to the goroutine being blocked unexpectedly.

Stack trace from `TestRotateCertWaitingForResultError`:
```
(*sync.Cond).Broadcast/Signal() at 0x00c000355410 by goroutine 33:
  k8s.io/client-go/tools/watch.(*eventProcessor).stop()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:100 +0x74
  k8s.io/client-go/tools/watch.NewIndexerInformerWatcher.func4()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:147 +0xef

(*sync.Cond).Wait() at 0x00c000355410 by goroutine 32:
  k8s.io/client-go/tools/watch.(*eventProcessor).takeBatch()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:64 +0x142
  k8s.io/client-go/tools/watch.(*eventProcessor).run()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:51 +0x38

Goroutine 33 (running) created at:
  k8s.io/client-go/tools/watch.NewIndexerInformerWatcher()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:143 +0x5ec
  k8s.io/client-go/tools/watch.UntilWithSync()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/until.go:130 +0x91
  k8s.io/client-go/util/certificate/csr.WaitForCertificate()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/csr/csr.go:98 +0x462
  k8s.io/client-go/util/certificate.(*manager).rotateCerts()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go:449 +0x73d
  k8s.io/client-go/util/certificate.TestRotateCertWaitingForResultError()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager_test.go:501 +0x4a0
  testing.tRunner()
      /Users/yahuis/lab/go-exp/go/src/testing/testing.go:954 +0x1eb

Goroutine 32 (running) created at:
  k8s.io/client-go/tools/watch.NewIndexerInformerWatcher()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go:140 +0x580
  k8s.io/client-go/tools/watch.UntilWithSync()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/tools/watch/until.go:130 +0x91
  k8s.io/client-go/util/certificate/csr.WaitForCertificate()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/csr/csr.go:98 +0x462
  k8s.io/client-go/util/certificate.(*manager).rotateCerts()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go:449 +0x73d
  k8s.io/client-go/util/certificate.TestRotateCertWaitingForResultError()
      /Users/yahuis/lab/go-exp/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager_test.go:501 +0x4a0
  testing.tRunner()
      /Users/yahuis/lab/go-exp/go/src/testing/testing.go:954 +0x1eb
```

One suggested fix: use mutex to protect `close(e.done)` in `(*eventProcessor).stop()`.

**What you expected to happen**:

No race condition.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`): Darwin
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

This is my first issue filed. Please let me know if I can provide further information.

### PR DESCRIPTION
**Pull request by dopelsunce**
Fixes: kubernetes#90581 (the first part)

When `Close()` is invoked on an empty queue, the control loop inside `Pop()` has a small chance of missing the signal and blocks indefinitely due to a race condition. This PR eliminates the race and allows the control loop inside any blocking `Pop()` to successfully exit after Close() is called.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #90581

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dopelsunce** [comment]
I signed the CLA

**Comment by spiffxp** [comment]
This may have caused https://github.com/kubernetes/kubernetes/issues/91316

**Comment by caesarxuchao** [comment]
The performance regression is fixed by https://github.com/kubernetes/kubernetes/pull/91337.

**Pull request merged**
