### PR TITLE
Updated check if a node is master.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Updated check if a node is master.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36219)

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @fgrzadkowski

**Comment by gmarek** [comment]
Required for HA

**Comment by jszczepkowski** [comment]
@k8s-bot node e2e test this
issue #35089

**Comment by jszczepkowski** [comment]
Part of https://github.com/kubernetes/features/issues/48

**Pull request merged**
