### PR TITLE
Add explain for TaintTolerationPriority function

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
This PR is a TODO.
Add explain about TaintTolerationPriority function.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bsalamat** [comment]
Please hold to this PR until after code freeze.

**Comment by stewart-yu** [comment]
I'm have reopened a one PR.@zhangxiaoyu-zidif@resouer@k82cn

**Pull request closed without merging**
