### PR TITLE
cleancode: graph_builder.go

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
It make the code clean and light.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@lavalamp 
Hope for your approving.

**Comment by zhangxiaoyu-zidif** [comment]
Hi, @janetkuo. could you approve it?

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot kops aws e2e test this

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
