### PR TITLE
Remove deprecated master certs test

### PR DESCRIPTION
**Pull request by mbforbes**
Avoid having to maintain this config in GKE Jenkins code.

### CODE REVIEW

**Comment by roberthbailey** [comment]
I think we should delete this test all together. We no longer use gcloud ssh to pull kubectl certs from the master when creating a cluster. So there's no need to verify that the certs exist there (and we can stop putting them there as well).

**Comment by mbforbes** [comment]
```go
{"kubecfg.key", "kubecfg.crt", "ca.crt"}
```

Are those all `kubectl` certs? Could we change this to check for others instead? The master needs _some_ certs, right?

**Comment by mbforbes** [comment]
Robby has enlightened me that we don't need to check for other (non-`kubectl`) certs because if other certs didn't exist, the cluster just wouldn't work at all (nodes couldn't join). This test, which was originally a "don't break GKE" test, is really completely inapplicable at this point.

We should delete this test then take out the config code that plumbs these certs to the master.

**Comment by mbforbes** [comment]
I've updated the PR description and content to reflect the discussion above—we're just removing the master certs test because it's now deprecated. PTAL.

**Comment by mbforbes** [comment]
Ugh; Jenkins failure just even trying to get the repo—snippet from the build log:

```
...
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/GoogleCloudPlatform/kubernetes +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: The requested URL returned error: 403 while accessing https://github.com/GoogleCloudPlatform/kubernetes/info/refs
fatal: HTTP request failed
...
```

@ixdy seen this before?

**Comment by mbforbes** [comment]
@k8s-bot test this please

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
