### PR TITLE
Flag gate node exclusion for service load balancers.

### PR DESCRIPTION
**Pull request by brendandburns**
@thockin @jdumars 

```release-note
Add a new feature gate for enabling an alpha annotation which, if present, excludes the annotated node from being added to a service load balancers.
```

Issue: https://github.com/kubernetes/kubernetes/issues/54743

Notes:
The original PR for this feature was: https://github.com/kubernetes/kubernetes/pull/53146

Which didn't include a gate (or the alpha label).

This was refined to add the `alpha` label in:
https://github.com/kubernetes/kubernetes/pull/53678

Then in the cherry-pick review:
https://github.com/kubernetes/kubernetes/pull/53656#issuecomment-335693646

@thockin requested a gate for an alpha feature, which is this PR.

### CODE REVIEW

**Review by luxas — APPROVED** [review]
Thanks!

/lgtm

**Review by luxas — COMMENTED** [review]
Oh, wait, I think you need to add the feature gate to the default feature gate list: https://github.com/brendandburns/kubernetes/blob/b8bc30e836a45da2e5ddc9225d3b1a966d6745ab/pkg/features/kube_features.go#L215

**Comment by luxas** [comment]
I assume you want this to get into v1.8.x?
I added a release-note, edit if incorrect or you want a rewording.

I think this needs an associated issue describing what this is used for etc. and why we ended up here from previous discussions on PR threads (hence I'm not gonna `approve no-issue` this)

**Comment by brendandburns** [comment]
@luxas Thanks for the quick review. I addressed your comments.

**Review by luxas — APPROVED** [review]
/lgtm
/retest

**Comment by jpbetz** [comment]
Removing cherry-pick labels since this has been manually cherrypicked in #54955

**Comment by oriff** [comment]
Thank you @brendanburns  for this nice feature this is exactly what i needed, it was in the right time in the right place, in my case i needed to build separated group of node/minions in order to run on them some stateful sets that consume lots resources and i didn't want to impact any incoming traffic through nginx-ingress, your feature allow me to achieve it perfectly.

**Pull request merged**
