### PR TITLE
Update e2e-runner.sh so it can fetch multiple types of Trusty images

### PR DESCRIPTION
**Pull request by wonderfly**
Trusty beta images now work with k8s 1.2.

@spxtr, @andyzheng0831 Can you review this?

### CODE REVIEW

**Comment by andyzheng0831** [comment]
Should we convert "trusty" to "gci", in both the PR title and code? "Trusty" is meaningless for us after we made GCI public in last week.

**Comment by wonderfly** [comment]
That'll come in a follow-up PR.

**Comment by andyzheng0831** [comment]
LGTM, leave further check to @spxtr

**Comment by spxtr** [comment]
Could you remake the job config changes against the kubernetes/test-infra repo? Otherwise looks fine to me.

**Comment by wonderfly** [comment]
@spxtr Done. See https://github.com/kubernetes/test-infra/pull/7.

This PR now only includes the changes to `e2e-runner.sh`.

**Comment by spxtr** [comment]
LGTM. This needs to go in at the same time as the other PR, right?

(Eventually we'll move e2e-runner.sh over as well, thanks for putting up with the bother)

**Comment by wonderfly** [comment]
> LGTM. This needs to go in at the same time as the other PR, right?

Yes, but do we have control over that? Manual merge?

**Comment by spxtr** [comment]
LGTM

@k8s-oncall this needs to go in manually to sync with a change in another repo. Mind merging?

**Comment by wonderfly** [comment]
Ping?

**Comment by spxtr** [comment]
@k8s-oncall this is an easy, safe hand merge if you're looking to cut down on the queue size :)

**Pull request merged**
