### PR TITLE
fix PVC resource limits not validated #106637

### LINKED ISSUE #106637: PVC resource limits not validated
### What happened?

PVC never supported setting capacity limits. However, it looks like in validation, we never enforced it: https://github.com/kubernetes/kubernetes/blob/a5622f3f6e1f5d5ffd066d799204ea0c6d1a49e2/pkg/apis/core/validation/validation.go#L2124

This means that it's possible PVC.spce.resource.limits could have garbage values in them. 

### What did you expect to happen?

Validation should have rejected PVC setting resource.limits. 

If we want to tighten validation, we would need to think about how to do it carefully for existing objects. Also, we should consider if we want to support limits.

### How can we reproduce it (as minimally and precisely as possible)?

Create a PVC and set resource.limits

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jlsong01**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
PVC resource limits not validated
The tighten validation would be added, which means, if spec.Resources.Limits[core.ResourceStorage] is present, no matter what value in them, the validation will failed with error indication.

#### Which issue(s) this PR fixes:

Fixes #106637

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jlsong01** [comment]
@sttts @yujuhong Hi folks, can you please review this pr, thanks.

**Comment by jlsong01** [comment]
/assign @sttts @yujuhong 
ping @sttts @yujuhong PTAL. Thanks.

**Comment by sttts** [comment]
This needs a look from @kubernetes/sig-storage-bugs.

**Comment by jingxu97** [comment]
cc @jingxu97

**Comment by mattcary** [comment]
IIUC, with this change, any existing objects that have set limits will fail to validate, and so will be unable to be changed? I think that's not going to work from a backward-compatibility perspective.

I see that you outlined your implementation on the bug (thanks!) but we never got back to you on that (sorry!). Let's continue the discussion there before doing anything more on this PR. 

API validation is really tricky, I'm afraid the discussion will dwarf the code change.

**Comment by jan-safranek** [comment]
Here is Jodan's generic guidance how to tighten validation of existing objects: https://github.com/kubernetes/kubernetes/pull/103024#issuecomment-874846127

It's not hard, just tedious. Please do not forget decent amount of unit tests.

**Comment by jlsong01** [comment]
@mattcary @jan-safranek Thanks for your comments. Here is my work plan, could you please take a look?

The tightened validation: If spec.Resources.Limits[core.ResourceStorage] is present, no matter what value in them, the validation will fail

- [ ] add this tightened validation on create

- [ ] add this tightened validation on update where the old PersistentVolumeClaimSpec passed this validation 

- [ ] skip this tightened validation on update where the old PersistentVolumeClaimSpec fails this validation

Unit test will be handled acoordingly.

**Comment by jlsong01** [comment]
This pr was closed somehow, let's continue discussion in https://github.com/kubernetes/kubernetes/issues/106637
I will raise another PR if needed

**Pull request closed without merging**
