### PR TITLE
Test UDP timeout

### LINKED ISSUE #1274: Kube-proxy tests does not test UDP timeouts
Depends on #1273 

UDP clients have a timeout (so we don't leak connections forever), but the test does not cover this.

To do this, we probably need to track active connections, and plumb that all the way down to the goroutines spawned by the ProxyLoop routines.  This is probably something we want to do anyway to be able to monitor.

### PR DESCRIPTION
**Pull request by jiangyaoguo**
fix #1274
Add a test for UDP timeout for kube-proxy.

### CODE REVIEW

**Comment by jiangyaoguo** [comment]
@thockin

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot test this please

**Pull request merged**
