### PR TITLE
Code Indent and typo fix

### PR DESCRIPTION
**Pull request by vjdhama**
**What this PR does / why we need it**:

Fixes example code indent and a typo.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes N/A

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by nikhita** [comment]
@vjdhama can you fix the commit message and PR title to say something like "Fix code formatting in v1.12 CHANGELOG"

**Comment by tpepper** [comment]
@vjdhama I agree with @nikhita 's request above.

Also this commit is going to conflict with https://github.com/kubernetes/kubernetes/pull/68889.  

Otherwise, this is actually a useful fixup to get in.

**Comment by marpaia** [comment]
As we spoke about in #68889, this doc is going to be overwritten with a copy-edited set of the release notes. It is on my not-so-long-term wish list to get the tool that generates and commits this notes file when tags are cut (anago) more integrated with the process that we use for generating the release notes document but the branch manager role (and the tool that they use) is currently in a lot of flux.

**Pull request closed without merging**
