### PR TITLE
Add protobuf documentation

### PR DESCRIPTION
**Pull request by smarterclayton**
First commit is in another PR, @wojtek-t review

### CODE REVIEW

**Comment by wojtek-t** [comment]
Second commit LGTM

**Comment by wojtek-t** [comment]
@smarterclayton - can you get rid of the first commit from this PR? And them feel-free to self-apply lgtm label.

**Comment by smarterclayton** [comment]
Will do

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
