### PR TITLE
cleanup lingering bazel related scripts/references

### LINKED ISSUE #105925: Do we still need {verify,update}-bazel.sh ?

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fixes https://github.com/kubernetes/kubernetes/issues/105925 and some associated cleanup, now that release 1.19 is no longer supported (confirmed with SIG release today).

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/105925

#### Special notes for your reviewer:

See: https://github.com/kubernetes/enhancements/issues/2420

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
There's still some more in this repo I'm investigating:
- The publishing robot is still configured for v1.19, once that's done we can remove the recursive delete config
- There's some lingering calls to bazel build in `test/e2e_kubeadm/runner/local/run_local.go`, I think this tool is clearly unused and should probably be removed but I will file a separate PR and get confirmation from the kubeadm owners. The contents of this PR as-is should otherwise be uncontroversial.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
