### PR TITLE
Add Unit test for endpointslice API

### LINKED ISSUE #110963: Add Unit test for endpointslice API
### What would you like to be added?

Add Unit test for endpointslice API. 

### Why is this needed?

Improve unit test coverage for endpointslice API.

### PR DESCRIPTION
**Pull request by ttakahashi21**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Improve unit test coverage for endpointslice API

#### Which issue(s) this PR fixes:

Fixes #110963

#### Special notes for your reviewer:
/sig testing
/sig network
@robscott

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
@ttakahashi21 not sure I understand the purpose of this. Do we have similar tests for other APIs?

**Comment by ttakahashi21** [comment]
@robscott 
Thank you for replay

[Purpose] 
https://github.com/kubernetes/enhancements/blob/c0fd7bb634f293038bf3b328eaf129f293f7c667/keps/sig-api-machinery/3285-subresource-finalizers/README.md#unit-tests

The above KEP needs to improve the unit test coverage.

> pkg/registry/discovery/endpointslice/storage : 2022/6/20 -

I have created test code because no test code have been created at this time.

[Answer]
>  Do we have similar tests for other APIs?

Yes.
For example:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/networking/ingress/storage/storage_test.go

**Comment by robscott** [comment]
OK that makes sense, thanks @ttakahashi21! I think you still need to get your CLA worked out, but will review once that's in place.

/ok-to-test

**Comment by ttakahashi21** [comment]
@robscott 
I am truly sorry about my late response.  I have completed signing the CLA.
Could you reopen the review?

**Comment by robscott** [comment]
Thanks @ttakahashi21!

/lgtm
/test pull-kubernetes-e2e-gce-ubuntu-containerd
/assign @lavalamp

**Comment by lavalamp** [comment]
Can you show a hypothetical bug that this unit test would catch that other unit tests would not already catch?

**Comment by ttakahashi21** [comment]
@lavalamp I think it will prevent degradation. We can notice when "registry/discovery/endpointslice" behaves as intended. Currently, we may not notice when the behavior changes because we don't have test code.

**Comment by lavalamp** [comment]
I'm asking for a demonstration -- e.g., make a code change which causes this test to fail but no other unit tests?

**Comment by dims** [comment]
@ttakahashi21 closing this for now as there has been no response since Sep 13. please reopen if needed.

/close

**Pull request closed without merging**
