### PR TITLE
cherry pick pr #111557 to 1.23 :update smd to 4.2.3

### LINKED ISSUE #111819: k8s apiserver write big custom object timeout, apiserver high cpu
### What happened?

A timeout occurred when writing a large object

schema.yaml content size 180k
```
✦ ➜ kubectl apply -f schema.yaml
Error from server (Timeout): error when creating "schema.yaml": Timeout: request did not complete within requested timeout - context deadline exceeded
```

k8s apiserver log:
```
{"level":"warn","ts":"2022-08-12T12:54:22.608Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0166e5dc0/#initially=[https://[::1]:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
E0812 12:54:22.608199       1 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 52.630776167s, panicked: false, err: context deadline exceeded, panic-reason: <nil>
```

But it is normal when I test writing directly with etcdctl
```
cat schema.yaml | ./etcdctl --endpoints=https://[::1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/apiserver-etcd-client.crt --key=/etc/kubernetes/pki/apiserver-etcd-client.key put /test
```

### What did you expect to happen?

normal

### How can we reproduce it (as minimally and precisely as possible)?

Write large objects normally

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
✦ ➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux xxxxx 5.4.119-1-tlinux4-0009.3 #1 SMP Thu Apr 28 09:35:59 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aojea**
/kind bug

#### What this PR does / why we need it:

Fixes #111819

```release-note
Fix performance issue when creating large objects using SSA with fully unspecified schemas (preserveUnknownFields).
```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

the test didn't merge on master https://github.com/kubernetes/kubernetes/pull/111912
it needs to be backported to 1.24 too

**Comment by liggitt** [comment]
/retest

/approve
for dependency update

/hold for @apelisse lgtm / review / confirmation this patch release is safe for previous release branches

**Comment by apelisse** [comment]
Good, same comment as for the other branch. Includes an extra fix that won't hurt (we probably should have cherry-picked  it so good).
/unhold

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by xmudrii** [comment]
@aojea This PR and #111915 are missing the LGTM label. Also, we're currently past the cherry-pick deadline, so we can approve those PRs only after cutting the upcoming patch releases (and after the LGTM label is applied).

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by saschagrunert** [comment]
We're beyond the cherry-pick deadline which was last Friday. We can continue approving them from the beginning of next week if every release got completed successfully.

**Comment by aojea** [comment]
ping https://github.com/orgs/kubernetes/teams/release-managers

ping @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]

**Comment by aojea** [comment]
I'm starting to see many flakes on the integration job lately, but this is 1.23 🤔 

> k8s.io/kubernetes/test/integration/job: TestFinalizersClearedWhenBackoffLimitExceeded 


/test pull-kubernetes-integration

**Comment by aojea** [comment]
hmm same test failure, this is definitively something to investigate

**Comment by aojea** [comment]
> > k8s.io/kubernetes/test/integration/job: TestFinalizersClearedWhenBackoffLimitExceeded

@alculquicondor @saschagrunert @liggitt  seems we have a problem in branch 1.23, this test has been flaking for some time

https://testgrid.k8s.io/sig-release-1.23-blocking#integration-1.23

**Comment by liggitt** [comment]
looks like integration job tests were fixed up in https://github.com/kubernetes/kubernetes/pull/109749 and picked to 1.24 in https://github.com/kubernetes/kubernetes/pull/111664 but not 1.23

**Comment by aojea** [comment]
> looks like integration job tests were fixed up in #109749 and picked to 1.24 in #111664 but not 1.23

it was picked https://github.com/kubernetes/kubernetes/pull/111665 🤔

**Pull request merged**
