### PR TITLE
Expose commonly used ports in the etcd image

### PR DESCRIPTION
**Pull request by oszi**
I'd like to expose ports commonly used by etcd in the etcd docker image.
It does not affect kubernetes in any way but it would make it more convenient to use the image for other purposes, outside of kubernetes.

I also merged the two COPY lines to reduce the number of layers.

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by roberthbailey** [comment]
@dchen1107 since we run the etcd container with `net=host` does this make the container accessible off-host?

**Comment by eparis** [comment]
running with net=host means this is irrelevant, right?

**Comment by luxas** [comment]
This doesn't make any sense, except for documentation purposes
It's only when using `docker run -P`, these values take effect

**Comment by eparis** [comment]
(although doing the copy in one line does save a layer, right? so that is definitely worth it)

**Comment by luxas** [comment]
Yes, the best for us would be to just minimize the layers from two to one and just add a comment about which ports should be open in case of not-`--net=host` :)

**Comment by oszi** [comment]
Indeed, this doesn't do anything for kubernetes. The only use-case of EXPOSE is to make it accessible with links when container to container communication is disabled by default (icc=false).
I'd like that so I can use the same gcr.io/google_containers/etcd image for development purposes
and not have to expose ports manually or use net=host.

With docker networks this may be pointless but still harmless.
I'll rebase and only keep the COPY commit if that's the consensus.

**Comment by eparis** [comment]
I consider it harmless, so have no problem leaving my LGTM and it will (eventually) get merged.

**Pull request merged**
