### PR TITLE
Add enj as reviewer to OWNERS

### PR DESCRIPTION
**Pull request by enj**
Adding myself as a reviewer for the following areas:

- API
- auth
- registry
- storage (etcd)

Signed-off-by: Monis Khan <mkhan@redhat.com>

**Release note**:

```release-note
NONE
```

@kubernetes/sig-api-machinery-pr-reviews
@kubernetes/sig-auth-pr-reviews

### CODE REVIEW

**Comment by mikedanese** [comment]
We should use more sig aliases for this kind of stuff.

**Comment by enj** [comment]
Oh the irony of this flaking on #49423

**Comment by deads2k** [comment]
> We should use more sig aliases for this kind of stuff.

@mikedanese Maybe, though he's picked out a subset of sig-auth and sig-apimachinery.  

/lgtm
/approve no-issue

**Comment by deads2k** [comment]
adding a valid reviewer (not approver) to a subset of api packages he's familiar with.

**Pull request merged**
