### PR TITLE
Fix typo in error message

### PR DESCRIPTION
**Pull request by tshrklr**

### CODE REVIEW

**Comment by tshrklr** [comment]
I signed it!

**Comment by vishh** [comment]
@tshrklr: We don't usually update Godeps manually. This change will have to be made in the cadvisor repo and then pulled in here. Once this change is made in the main repo, I am happy to merge this PR.

**Comment by tshrklr** [comment]
@vishh makes sense. thanks.

**Comment by vishh** [comment]
@tshrklr: Are you still working on this PR? If not, can you close it for now?

**Pull request closed without merging**
