### PR TITLE
moving ShuffleStrings to pkg/proxy

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What type of PR is this?**

/kind cleanup
/sig api-machinery

**What this PR does / why we need it**: this moves the `slice` package to apimachinery repository in order to be able to move some controllers out k/k

**Which issue(s) this PR fixes**: part of #81172

**Special notes for your reviewer**:

/assign @liggitt @dims 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @andrewsykim 
as per https://github.com/kubernetes/kubernetes/issues/81172

@yastij 
there seem to be BUILD related problems in the CI logs, would ./hack/update-bazel.sh solve that?

**Comment by andrewsykim** [comment]
`pkg/util/slice` seems mostly specific to strings, wondering if it makes more sense to add it to `k8s.io/utils/strings`?

**Comment by yastij** [comment]
@andrewsykim - Not against moving this to k/utils. @thockin thoughts on this ?

**Comment by yastij** [comment]
@andrewsykim - this would pull `util/rand`'s apimachinery package into `k/utils`

**Comment by andrewsykim** [comment]
I think `k8s.io/apimachinery/pkg/util/rand` could also belong in `k8s.io/utils` but will let someone from API Machinery comment on that one.

**Comment by liggitt** [comment]
the ShuffleStrings method is only used by pkg/proxy. I'd probably move that one out to the proxy package, drop the utilrand dependency, and move the rest to `k/utils` with no non-stdlib dependencies

**Comment by yastij** [comment]
sgtm

**Comment by thockin** [comment]
I'm not convinced that any of the logic here rises to the level of a new pkg in k/utils.  It's all just trivial stuff.

**Comment by liggitt** [comment]
> I'm not convinced that any of the logic here rises to the level of a new pkg in k/utils. It's all just trivial stuff.

that's fair, too.

**Pull request merged**
