### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ankon**
**What this PR does / why we need it**: Fix trivial typo in comment.

### CODE REVIEW

**Comment by ankon** [comment]
I'm not sure whether/what I'm supposed to do here ... yes, there's a build failure, but I fail to see how this would have anything to do with fixing a comment typo. I'm also sure that running tests again is not going to magically fix things, unless I'm lucky and the underlying issue had been fixed somehow.

Advise please? :)

**Comment by cblecker** [comment]
/assign @erictune
for approval

**Comment by cblecker** [comment]
/assign @erictune 
for approval

**Pull request merged**
