### PR TITLE
Fix broken KEP link for issue #101008

### PR DESCRIPTION
**Pull request by tech-geek29**
## What type of PR is this?
/kind documentation

## What this PR does / why we need it:
This PR fixes following broken links from `[Umbrella] Fix KEP link #101008` :
- CHANGELOG/CHANGELOG-1.8.md:1434:[scalability validation report]
- CHANGELOG/CHANGELOG-1.14.md:943:kubernetes/enhancements: kep

## Which issue(s) this PR fixes:
x-ref #101008

## Special notes for your reviewer:
Does this PR introduce a user-facing change?
`NONE`
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
`NONE`

Release Notes needed:
```release-note
NONE
```

### CODE REVIEW

**Comment by tech-geek29** [comment]
@cici37  , Can you please review this PR?

cc: @wilsonehusin

Context: As @wilsonehusin I have merged the two broken KEP link fixes into one and created a new PR

**Comment by wilsonehusin** [comment]
awesome, thanks for taking care of this!

/ok-to-test
/lgtm
/approve

/remove-kind documentation
/kind cleanup

/priority backlog
/triage accepted

**Pull request merged**
