### PR TITLE
Reduce size of go binaries using upx

### PR DESCRIPTION
**Pull request by aledbf**
Proposal:
Use [upx](http://upx.sourceforge.net/) to compress go binaries in order to reduce the size.

```
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  90857608 ->  27769800   30.56%  linux/ElfAMD   e2e.test
  77157720 ->  25047928   32.46%  linux/ElfAMD   e2e_node.test
 103672208 ->  19476724   18.79%  linux/ElfAMD   federation-apiserver
  59990744 ->  12286324   20.48%  linux/ElfAMD   federation-controller-manager
  57470880 ->  12280380   21.37%  linux/ElfAMD   gendocs
 100985280 ->  18699824   18.52%  linux/ElfAMD   genfeddocs
 105617456 ->  20887456   19.78%  linux/ElfAMD   genkubedocs
  57641528 ->  12331272   21.39%  linux/ElfAMD   genman
   6868376 ->   1879004   27.36%  linux/ElfAMD   genswaggertypedocs
  57446832 ->  12270520   21.36%  linux/ElfAMD   genyaml
  11587168 ->   3347672   28.89%  linux/ElfAMD   ginkgo
 139069888 ->  28648840   20.60%  linux/ElfAMD   hyperkube
 133381768 ->  35406744   26.55%  linux/ElfAMD   integration
 110236528 ->  20747236   18.82%  linux/ElfAMD   kube-apiserver
 100129408 ->  18551436   18.53%  linux/ElfAMD   kube-controller-manager
  50311992 ->  10605672   21.08%  linux/ElfAMD   kube-dns
  51145152 ->  10897296   21.31%  linux/ElfAMD   kube-proxy
  59487192 ->  12253384   20.60%  linux/ElfAMD   kube-scheduler
  57307672 ->  12224796   21.33%  linux/ElfAMD   kubectl
 108098704 ->  21032328   19.46%  linux/ElfAMD   kubelet
 105503432 ->  20294660   19.24%  linux/ElfAMD   kubemark
   8646016 ->   2514108   29.08%  linux/ElfAMD   linkcheck
   4385744 ->   1286348   29.33%  linux/ElfAMD   mungedocs
   8828376 ->   2572748   29.14%  linux/ElfAMD   src
   3581568 ->   1058312   29.55%  linux/ElfAMD   teststale
   --------------------   ------   -----------   -----------
1669409240 -> 364370812   21.83%                 [ 25 files ]
```

Build log https://gist.github.com/aledbf/c300c516841e31bf83eb309309df3a0b

Improvement in the docker images:

| Image | Before | After |
| --- | --- | --- |
| gcr.io/google_containers/hyperkube-amd64 | 416.2 MB | 281.8 MB |
| gcr.io/google_containers/kube-apiserver | 110.7 MB | 21.84 MB |
| gcr.io/google_containers/kube-controller-manager | 100.5 MB | 19.64 MB |
| gcr.io/google_containers/kube-scheduler | 60.04 MB | 13.35 MB |
| gcr.io/google_containers/kube-proxy | 180 MB | 140.3 MB |

### CODE REVIEW

**Comment by zmerlynn** [comment]
I'm OOO, but the concept could be fine.

**Comment by luxas** [comment]
cc

**Comment by thockin** [comment]
What is the goal?  UPX has downsides:

* demand-paging is impossible, resulting in higher overall memory usage
* page-sharing is impossible (e.g. hyperkube), resulting in higher overall memory usage

We should already be compressing the files for download, so this won't make them much (any?) smaller.  In fact, compressing compressed files might make them BIGGER.

So they get smaller on disk, in exchange for being larger in memory and maybe larger in download?

Is there any advantage?

**Comment by aledbf** [comment]
> page-sharing is impossible (e.g. hyperkube), resulting in higher overall memory usage

Right, that is a known downside of upx

> We should already be compressing the files for download, so this won't make them much (any?) smaller. 

Not binaries from storage.googleapis.com 
```
wget https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl
```

> Is there any advantage?

From my use case (bare metal in a datacenter restricted to 10MB for international traffic) any improvement in the download sizes is welcomed. 

Closing. This could be only a "limitation" from my production environment.

**Comment by thockin** [comment]
Sorry, I don't want to be negative-nancy.  If it is a problem, we should
offer those files co MN pressed, too.  @david-mcmahon, can we add that to
the release process?

**Comment by luxas** [comment]
A bit related: #28435

**Comment by david-mcmahon** [comment]
If there is a need to pursue this further, you could produce a parallel set of compressed bits. I don't know how much time that would add to a release but presumably it would be negligible.

**Comment by zmerlynn** [comment]
@aledbf: The individual binaries are for launch processes that aren't launching the whole server tar.gz, which *is* compressed. I don't think it would actually be that hard for e.g. CoreOS to lay down the .tar.gz somewhere either, it just doesn't.

**Pull request closed without merging**
