### PR TITLE
Update staticcheck to include fix for unused functions

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This bumps staticcheck to v2020.1.4 to include a fix that should help
reduce test flakes when checking for unused functions.

https://github.com/dominikh/go-tools/commit/a9480a3ec3bcedcf32d00a67bb464c058ba03281

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

Ref #87807

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
/approve
thanks!

**Comment by hasheddan** [comment]
/retest

Unfortunately this doesn’t help with the timeout 😕

**Comment by BenTheElder** [comment]
Some static check failures need fixing now
/hold

**Comment by hasheddan** [comment]
@BenTheElder thanks for catching that, will address these today :+1:

**Comment by hasheddan** [comment]
This is handled by https://github.com/kubernetes/kubernetes/pull/92438

/close

**Pull request closed without merging**
