### PR TITLE
Remove reference from addon-manager dockerfile

### PR DESCRIPTION
**Pull request by r2d4**
**What this PR does / why we need it**: Removes a reference to nonexisting file in the dockerfile for the addon-manager

This file was deleted with #34513

cc @mikedanese @MrHohn 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35147)

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM thanks.

**Comment by r2d4** [comment]
Friendly ping -  I think this might need a "@k8s-bot ok to test"

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
oops didn't mean to close

**Pull request merged**
