### PR TITLE
Used int64 for range error.

### LINKED ISSUE #46793: ci-kubernetes-cross-build has been failing since May. 31 afternoon
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-cross-build?

```
I0531 02:45:23.530] +++ [0531 02:28:12] linux/amd64: go build started
I0531 02:45:23.531] +++ [0531 02:45:21] linux/amd64: go build finished
I0531 02:45:23.531] +++ [0531 02:28:12] linux/arm: go build started
I0531 02:45:23.531] # k8s.io/kubernetes/pkg/api/validation
I0531 02:45:23.532] pkg/api/validation/validation.go:2196: constant 4294967295 overflows int
I0531 02:45:23.532] pkg/api/validation/validation.go:2584: constant 4294967295 overflows int
I0531 02:45:23.532] !!! [0531 02:34:38] Call tree:
I0531 02:45:23.532] !!! [0531 02:34:38]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:690 kube::golang::build_binaries_for_platform(...)
I0531 02:45:23.532] !!! [0531 02:34:38]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
I0531 02:45:23.533] +++ [0531 02:28:12] linux/arm64: go build started
I0531 02:45:23.533] +++ [0531 02:45:22] linux/arm64: go build finished
I0531 02:45:23.533] +++ [0531 02:28:12] linux/s390x: go build started
I0531 02:45:23.533] +++ [0531 02:45:20] linux/s390x: go build finished
I0531 02:45:23.534] +++ [0531 02:28:12] linux/ppc64le: go build started
I0531 02:45:23.534] +++ [0531 02:45:23] linux/ppc64le: go build finished
```

### PR DESCRIPTION
**Pull request by k82cn**
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46793

```release-note-none
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks @k82cn, though we are going to take https://github.com/kubernetes/kubernetes/pull/46711.

**Comment by k82cn** [comment]
> though we are going to take #46711.

Yes, just leave a comment there; but I think this PR may cover other such kind of issue in future, and no harm :).

**Comment by caesarxuchao** [comment]
Agree. And this function is not in a critical path so using int64 is going to cause any performance issue. So lgtm.

@derekwaynecarr wdyt?

**Comment by k82cn** [comment]
> using int64 is going to cause any performance issue. 

not going to cause any performance?

**Comment by caesarxuchao** [comment]
> not going to cause any performance?

i thought we avoided using int64 because it might be inefficient on some platforms.

**Comment by derekwaynecarr** [comment]
i see no reason to change now that the build is working again.

**Comment by derekwaynecarr** [comment]
closing as i prefer to not make the change unless there is an actual need.

**Comment by k82cn** [comment]
ok, for now.

**Pull request closed without merging**
