### PR TITLE
Automated cherry pick of #86346 #88684 #89319 upstream release 1.17

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
/kind bug
/sig storage
/priority important-soon

**What this PR does / why we need it**:
Cherry pick PRs #86346 #88684 #89319 from master to upstream release 1.17
/assign @liggitt 
CC @SataQiu @andyzhangx @jsafrane @mboersma

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
AzureFile and CephFS use new Mount library that prevents logging of sensitive mount options.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
/test pull-kubernetes-e2e-azure-disk-vmss
test failed because we don't have quota on Azure ...

**Comment by saad-ali** [comment]
I need to redo this and include https://github.com/kubernetes/kubernetes/pull/89444

**Comment by saad-ali** [comment]
Closed in favor of https://github.com/kubernetes/kubernetes/pull/89494

**Pull request closed without merging**
