### PR TITLE
Add UpdateTwice and UpdateApply benchmarks for fieldmanager

### PR DESCRIPTION
**Pull request by apelisse**
I've also moved the deserialization of the object outside the benchmark
since we're not trying to benchmark the yaml parser.

/assign @jpbetz @jennybuckley 

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by apelisse** [comment]
/hold

I've just seen something fishy

**Comment by apelisse** [comment]
/hold cancel

I think we're good

**Comment by jpbetz** [comment]
Nice. I'm going to try this out now. As mentioned offline, `RunParallel` might be appropriate here too, since it's run concurrently in production.

/lgtm

**Comment by apelisse** [comment]
/hold

Let me work on a few improvements.

**Comment by apelisse** [comment]
/hold cancel

We can improve later ;-)

**Pull request merged**
