### PR TITLE
added init containers tests to simplify the sidecar KEP large PR

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind cleanup
/area test
/sig node

cc @gjkim42 @tzneal @matthyx 

#### What this PR does / why we need it:

Added two tests for Init containers. Mostly to simplify the Sidecar KEP large PR: https://github.com/kubernetes/kubernetes/pull/116429/files#diff-13175cdc69ae6aa66d7ff9b6a4dbbd8a71fba471270722b9654e45e385d6f744

```release-note
NONE
```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by tzneal** [comment]
@SergeyKanzhelev Looks like just a  gofmt issue

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev Looks like just a gofmt issue

two newlines... fixed. thank you!

**Comment by matthyx** [comment]
cool 👍

**Pull request merged**
