### PR TITLE
Preserve existing ephemeral containers on update, validate ephemeral containers and overhead unconditionally

### PR DESCRIPTION
**Pull request by liggitt**
Adjusts handling of the new ephemeralcontainers field:
* Preserves existing data on update, even if the feature is disabled
* Makes validation unconditional

Adjusts handling of the new overhead field:
* Makes validation unconditional

See guidelines in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#adding-unstable-features-to-stable-versions

/kind bug
/cc @smarterclayton 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @thockin @tallclair @egernst for overhead validation change

**Comment by smarterclayton** [comment]
Subtle and terrifying

The only thing we could do is rollback tests with populated fields and that’s hard

**Comment by verb** [comment]
ah, ok. I understand now. Sorry I missed this.

/lgtm

**Comment by verb** [comment]
> cc @thockin @tallclair @egernst for overhead validation change

/cc @thockin @tallclair @egernst

**Pull request merged**
