### PR TITLE
Scheduler: enable import-boss check for k/k

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

It is never too early to settle down import-boss check when we decide to avoid unwanted dependencies:
- know what unwanted dependencies left in real time
- Avoid regression with other PRs

But I will leave this to @damemi, feel free to hold on this to avoid rebasing for the current ongoing PRs.

**Which issue(s) this PR fixes**:

Xref #89930

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
Thanks for adding this @gavinfish! This will help the work we are doing

Though I think keeping it at the scheduler root (`pkg/scheduler`) might be too broad for the work we are doing right now, which is just targeted at the framework and plugins `pkg/scheduler/framework/plugins`.

@ahg-g can we have an import-restrictions file at that level? It will be more tuned to our current goals, whereas this one won't be updated for a while

**Comment by ahg-g** [comment]
I think this is fine, as long as the sig have approval on the file things should be ok.

**Comment by damemi** [comment]
My point is that we don't care about restricting imports for `pkg/scheduler`, because we don't plan to externalize core scheduler code. So if this list is in the scheduler's root directory it might just never get updated.

**Comment by ahg-g** [comment]
ok, make sense. But you will need the whole framework pkg because the interface/types lives there.

**Pull request closed without merging**
