### PR TITLE
Change resource "ingress" to "ingresses" in URL path and kubectl

### LINKED ISSUE #16070: kubectl should support ingresses
Forked from #15578

kubectl uses "ingress" for both singular and plural for the ingress resources, whereas it uses plural forms for everything except endpoints AFAIK.

kubectl should support both ingress (singular) and ingresses (plural). At least the following places need to be updated:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/kubectl.go#L111
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L145

cc @bprashanth @thockin

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #16070

Now you can do:

``` console
$ kubectl get ing
$ kubectl get ingress
$ kubectl get ingresses
```

or visit `http://<master>/apis/extensions/v1beta1/ingresses`

cc @bgrant0607 @bprashanth @thockin @kubernetes/kubectl @kubernetes/kube-api

### CODE REVIEW

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
Sorry about failing tests. I broke e2e job trying to add in unit/integration. Should be working now. @k8s-bot test this

**Comment by bprashanth** [comment]
@janetkuo thanks.  I'll let the others apply the LGTM label. Can you please update the godep in contrib when this goes in? (instructions: https://github.com/kubernetes/contrib/blob/master/README.md, let me know if you run into problems)

**Comment by bgrant0607** [comment]
Thanks. LGTM.

We should send an announcement to kubernetes-dev about the API path change.

**Comment by janetkuo** [comment]
Need to cherry-pick #15010 and #15042 in order to cherry-pick this PR.

**Comment by janetkuo** [comment]
@bprashanth I'll update the godep.

**Comment by liggitt** [comment]
> We should send an announcement to kubernetes-dev about the API path change.

Did an announcement get sent? Other clients have their own implementations of KindToResource... changes to that algorithm shouldn't be made lightly

**Comment by liggitt** [comment]
Not to mention downstream API kinds that also use RESTMapper :-/

**Comment by bprashanth** [comment]
Not yet, will do so today

**Pull request merged**
