### PR TITLE
Partially fix incorrect configuration of kubepods.slice unit by kubelet

### PR DESCRIPTION
**Pull request by olegch**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR partially fixes issue #88197 - kubelet configures `kubepods.slice` systemd unit with incorrect `MemoryLimit` when kube-reserved and/or system-reserved is used

**Which issue(s) this PR fixes**:

Refs #88197 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by olegch** [comment]
@mattjmcnaughton @odinuge this PR is created as a replacement for https://github.com/kubernetes/kubernetes/pull/88198 to overcome issue with k8s-robot still considering it a cherry pick

**Comment by odinuge** [comment]
Thanks @olegch. Sorry for the inconvenience, but everything looks good now.  

/lgtm
/ok-to-test
/priority important-soon
/assign derekwaynecarr

**Comment by sjenning** [comment]
wow, we just found this issue independently and @rphillips arrived at the same partial fix
/approve

**Comment by rphillips** [comment]
This still leaves open the gap for updates. opencontainers/runc will need to be updated to incrementally perform an update on the running slice.

**Comment by sjenning** [comment]
i just remembered, the reason that i didn't like this fix was that in the event that the node is already running pods that exceed a potentially more restrictive memory limit, the limit set might fail, being fatal to kubelet start.
fyi @vishh

**Comment by olegch** [comment]
> i just remembered, the reason that i didn't like this fix was that in the event that the node is already running pods that exceed a potentially more restrictive memory limit, the limit set might fail, being fatal to kubelet start.

@sjenning yes, but this is only possible when the kubelet version is updated on the node without restart.
In that regard it is no different from the situation when the kubelet **without fix** is restarted and the node is already running pods that exceed a potentially more restrictive memory limit. It will then still fail to update the limit on the `kubepods.slice` cgroup.

So, this fix does not make the already existing situation worse, only fixes the issue.

**Comment by sjenning** [comment]
@olegch first I forgot to thank finding this issue and submitting a fix :+1: 

It is hard to reason about this since the cgroup manger `Update()` is basically broken for systemd.  Thus we only have one chance at `Create()` time to set the cgroup values reliably.

What if we try to do the create with `capacity-reservations` (this fix) as  the memory limit and, if that fails, reattempt the create with `capacity` (how it is now) which should always work?

@rphillips what do you think?

**Comment by odinuge** [comment]
Not sure if I follow you @sjenning, or if I am missing something.

The slice is created only if the corresponding cgroups don't exists. The check is here: https://github.com/kubernetes/kubernetes/pull/88251/files#diff-5dc6bd6afcca36d1b376b3c78accb0aaR53. So with my reasoning, this fix only change the behavior when the slice, and therefore also the corresponding cgroups, doesn't exist. If the cgroups exits, the `Update` function will be retry until it succeeds: https://github.com/kubernetes/kubernetes/pull/88251/files#diff-5dc6bd6afcca36d1b376b3c78accb0aaL90-L101.

And if the slice doesn't exist, I don't see a problem with using `nodeAllocatable` instead of `capacity` when creating it.

**Comment by sjenning** [comment]
I didn't see the escape hatch before. i guess i would have expected that to be toward the top of the function.  Anyway, in light of this only being done when the kubelet first starts on a node (i.e. when there are no pods running) and not on  kubelet restart, I think this is fine.
/approve

**Comment by odinuge** [comment]
Thanks @sjenning! 

> @rphillips: This still leaves open the gap for updates. opencontainers/runc will need to be updated to incrementally perform an update on the running slice.

and 

> It is hard to reason about this since the cgroup manger Update() is basically broken for systemd. Thus we only have one chance at Create() time to set the cgroup values reliably.

I don't think runc will add code to update the slice, since afaik. they are "immutable" to runc (since runc deals with containers), since you cannot change the resource requests for a container at runtime (but feel free to correct me if I am wrong). Ref. #81774 these resources _can_ in theory change when kubelet is running too, and now we don't do anything about it.

We can, and we should probably too, set the updated unit properties ourselves using dbus. Here is a working WIP of what has to be done: https://github.com/kubernetes/kubernetes/compare/master...odinuge:slice-update-systemd?expand=1

Any thoughts? I'll make a cleanup and open a PR when I get time. Some tests would have been nice too.

**Comment by reegnz** [comment]
Will this fix be cherry-picked to 1.16 and 1.17? I'm wondering because on cloud provider supported versions (EKS, AKS, etc.) this issue is still present. I see that this fix is present only 1.18 onwards.

**Comment by odinuge** [comment]
Hey @reegnz!

Feel free to submit cherry-picks to previous releases (and I agree that this fix can be backported). Here is information about how to do it: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

List of supported versions and patch releases in general can be found here: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Pull request merged**
