### PR TITLE
josnpath allows dot in dict key

### PR DESCRIPTION
**Pull request by daizuozhuo**
As discussed in #23386. We can quote dot as dict key. @AdoHe @timstclair @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, @daizuozhuo. 

@AdoHe PTAL.

**Comment by AdoHe** [comment]
@daizuozhuo I am afraid this can not fix the original issue use case #23386 `kubectl get secrets rails -o "jsonpath={.data['db.conf']}"`, if users have to update the jsonpath template, please document it, or we need to make sure the old template still works.

**Comment by daizuozhuo** [comment]
@AdoHe  When jsonpath is designed, single quote ' means it will evaluate the string, so ".data['db.conf']" will evaluate db.conf and then use it as the key. Double quote " will preserve the string literal so we can write '.data."db.conf"' or '.data["db.conf"' to get the desired value. This may contradict to what linux bash does, but it not break the old template syntax.

**Comment by AdoHe** [comment]
@daizuozhuo thanks for detailed explanation, please make sure the unit tests of package jsonpath can pass. Besides I think you should better document it.

**Pull request closed without merging**
