### PR TITLE
Automated cherry pick of #73435: Updated AWS SDK to v1.16.26 for ECR privatelink support

### PR DESCRIPTION
**Pull request by micahhausler**
Cherry pick of #73435 on release-1.13.

#73435: Updated AWS SDK to v1.16.26 for ECR privatelink support

### CODE REVIEW

**Comment by micahhausler** [comment]
Patch managers @aleksandra-malinowska and @tpepper: (let me know if I have the wrong people)

AWS ECR introduced a backward incompatible change to support PrivateLink (support for non-internet connected VPCs). Is this a change we can get into 1.13?

**Comment by aleksandra-malinowska** [comment]
> AWS ECR introduced a backward incompatible change to support PrivateLink (support for non-internet connected VPCs). Is this a change we can get into 1.13?

What is the impact of this backward incompatibility? Does it break 1.13.2 and earlier?

**Comment by micahhausler** [comment]
The impact is that customers running K8s clusters 1.13.2 and earlier will not be able to use PrivateLink ECR because kubelet calls ECR for credential fetching.

**Comment by tpepper** [comment]
@micahhausler was https://github.com/kubernetes/kubernetes/pull/73435 mis-marked as a feature then?  It does read like these are feature PRs and we're calling it a bug in k8s that something doesn't work, yet it doesn't work because AWS chose to do something not backward compatible?

**Comment by chadlwilson** [comment]
Would be great to get this merged/addressed; so we can move backwards to the 1.12 branch - which just got a bit closer for EKS users - released as supported [a day ago](https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-eks-now-supports-kubernetes-version-1-12-and-cluster-vers/).

**Comment by micahhausler** [comment]
@tpepper Updated as a feature.

**Comment by gyuho** [comment]
@tpepper Can we reopen this? We need this in for 1.13. Thanks!

**Comment by tpepper** [comment]
> @tpepper Can we reopen this? We need this in for 1.13. Thanks!

We don't backport features.

**Pull request closed without merging**
