### PR TITLE
Default resources.requests only for Pod resources

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/kubernetes/kubernetes/issues/14050

cc @bgrant0607

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Looks like I have one other area to fixup.

**Comment by derekwaynecarr** [comment]
@bgrant0607 @markturansky - did the PersistentVolumeClaim stuff depend on resources.requests being defaulted based on resources.limits?  trying to determine if the change here is what induced the flake.  my understanding is that we only wanted resources.requests to be defaulted for pods only.

**Comment by markturansky** [comment]
No, nothing in defaulted for PVC except for Status.Phase = Pending.

resources.requests is a required field for PVC, but I default no value into it.

**Comment by derekwaynecarr** [comment]
@markturansky - it seems to me something depended somewhere on the request being set based on the limit in the integration test unless you have other ideas on why the shippable error is reporting...

**Comment by derekwaynecarr** [comment]
hmm, looks like it may be related to this:

https://github.com/kubernetes/kubernetes/issues/14284

but the reported fix does not appear to fix things, or it exposed another flake.

**Comment by markturansky** [comment]
Attempted fix here:  https://github.com/kubernetes/kubernetes/pull/14356

A quick review and LGTM would help :)    It's a test-only PR.

**Comment by bgrant0607** [comment]
#14356 was merged.

**Comment by bgrant0607** [comment]
@lavalamp

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by vishh** [comment]
LGTM.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Thanks much.

**Pull request merged**
