### PR TITLE
Remove known metrics list

### LINKED ISSUE #26800: v1.2 MetricsGrabber test failing against v1.3 master
This is a v1.2 test.  Repro by turning up a v1.3 cluster and running v1.2 tests against it.

```
08:45:23 MetricsGrabber 
08:45:23   should grab all metrics from API server.
08:45:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:100
08:45:23 [BeforeEach] MetricsGrabber
08:45:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:100
08:45:23 STEP: Creating a kubernetes client
08:45:23 Jun  3 08:45:23.738: INFO: >>> testContext.KubeConfig: /workspace/.kube/config
08:45:23 
08:45:23 STEP: Building a namespace api object
08:45:23 Jun  3 08:45:23.779: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-metrics-grabber-huhgp
08:45:23 Jun  3 08:45:23.819: INFO: Service account default in ns e2e-tests-metrics-grabber-huhgp with secrets found. (40.444628ms)
08:45:23 STEP: Waiting for a default service account to be provisioned in namespace
08:45:23 Jun  3 08:45:23.819: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-metrics-grabber-huhgp
08:45:23 Jun  3 08:45:23.860: INFO: Service account default in ns e2e-tests-metrics-grabber-huhgp with secrets found. (40.340176ms)
08:45:23 [BeforeEach] MetricsGrabber
08:45:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:90
08:45:23 W0603 08:45:23.902311    4669 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
08:45:23 [It] should grab all metrics from API server.
08:45:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:100
08:45:23 STEP: Connecting to /metrics endpoint
08:45:24 W0603 08:45:24.066878    4669 generic_metrics.go:137] Unknown metric authenticated_user_requests{username="admin"} => 19899 @[0]
08:45:24 W0603 08:45:24.066950    4669 generic_metrics.go:137] Unknown metric authenticated_user_requests{username="kube_proxy"} => 296 @[0]
08:45:24 W0603 08:45:24.066969    4669 generic_metrics.go:137] Unknown metric authenticated_user_requests{username="kubelet"} => 39997 @[0]
08:45:24 W0603 08:45:24.066981    4669 generic_metrics.go:137] Unknown metric authenticated_user_requests{username="other"} => 25 @[0]
08:45:24 W0603 08:45:24.066992    4669 generic_metrics.go:137] Unknown metric authenticated_user_requests{username="system:serviceaccount:kube-system:default"} => 4249 @[0]
08:45:24 [AfterEach] MetricsGrabber
08:45:24   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:101
08:45:24 STEP: Collecting events from namespace "e2e-tests-metrics-grabber-huhgp".
08:45:24 Jun  3 08:45:24.177: INFO: POD                                                               NODE                                        PHASE    GRACE  CONDITIONS
08:45:24 Jun  3 08:45:24.177: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-k0ig  gke-jenkins-e2e-default-pool-733837a5-k0ig  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:20 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:42 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:20 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-m9ba  gke-jenkins-e2e-default-pool-733837a5-m9ba  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:25 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:47 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:25 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-pw73  gke-jenkins-e2e-default-pool-733837a5-pw73  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:04:58 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:05:20 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:04:58 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: heapster-v1.1.0.beta2-142973226-faadi                             gke-jenkins-e2e-default-pool-733837a5-k0ig  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:10 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:16 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:10 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: kube-dns-v13-renzr                                                gke-jenkins-e2e-default-pool-733837a5-k0ig  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:06:29 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:07:09 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:06:29 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-k0ig             gke-jenkins-e2e-default-pool-733837a5-k0ig  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:20 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:34 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:20 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-m9ba             gke-jenkins-e2e-default-pool-733837a5-m9ba  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:25 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:47 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:25 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-pw73             gke-jenkins-e2e-default-pool-733837a5-pw73  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:04:58 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:05:16 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:04:58 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: kubernetes-dashboard-v1.1.0-beta1-euaml                           gke-jenkins-e2e-default-pool-733837a5-pw73  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:06:29 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:06:32 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:06:29 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: l7-default-backend-v1.0-oizcz                                     gke-jenkins-e2e-default-pool-733837a5-pw73  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:10 -0700 PDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:12 -0700 PDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:40:10 -0700 PDT  }]
08:45:24 Jun  3 08:45:24.177: INFO: 
08:45:24 Jun  3 08:45:24.215: INFO: 
08:45:24 Logging node info for node gke-jenkins-e2e-default-pool-733837a5-k0ig
08:45:24 Jun  3 08:45:24.254: INFO: Node Info: &{{ } {gke-jenkins-e2e-default-pool-733837a5-k0ig   /api/v1/nodes/gke-jenkins-e2e-default-pool-733837a5-k0ig 5ce7a558-2975-11e6-9c54-42010af00003 20869 0 2016-06-03 03:24:32 -0700 PDT <nil> <nil> map[cloud.google.com/gke-nodepool:default-pool failure-domain.beta.kubernetes.io/region:us-central1 failure-domain.beta.kubernetes.io/zone:us-central1-f kubernetes.io/hostname:gke-jenkins-e2e-default-pool-733837a5-k0ig beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:n1-standard-2 beta.kubernetes.io/os:linux] map[volumes.kubernetes.io/controller-managed-attach-detach:true]} {10.180.2.0/24 6812714922942456959 gce://kube-gke-upg-1-2-1-3-upg-clu/us-central1-f/gke-jenkins-e2e-default-pool-733837a5-k0ig false} {map[memory:{7864135680.000 BinarySI} pods:{110.000 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI} cpu:{2.000 DecimalSI}] map[alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI} cpu:{2.000 DecimalSI} memory:{7864135680.000 BinarySI} pods:{110.000 DecimalSI}]  [{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2016-06-03 03:25:04 -0700 PDT RouteCreated RouteController created a route} {OutOfDisk False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 03:24:32 -0700 PDT KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 03:24:32 -0700 PDT KubeletHasSufficientMemory kubelet has sufficient memory available} {Ready True 2016-06-03 08:45:16 -0700 PDT 2016-06-03 03:25:20 -0700 PDT KubeletReady kubelet is posting ready status. WARNING: CPU hardcapping unsupported}] [{InternalIP 10.240.0.3} {ExternalIP 130.211.140.16}] {{10250}} { 9BA2450E-147D-1FDB-CCB0-763D83EF39E5 5f20b27d-d5aa-4864-adda-2dcb315352f4 3.16.0-4-amd64 Debian GNU/Linux 7 (wheezy) docker://1.9.1 v1.3.0-alpha.5.38+1ad3e11a59dc56 v1.3.0-alpha.5.38+1ad3e11a59dc56} [{[gcr.io/google_samples/gb-frontend:v3] 509707703} {[gcr.io/google_containers/redis:e2e] 419003740} {[gcr.io/google_containers/fluentd-gcp:1.18] 411450900} {[gcr.io/google_containers/kube-proxy:7bdadb0ebfdd73c80cfe5d864838e203] 178177849} {[gcr.io/google_containers/resource_consumer:beta2] 132819513} {[gcr.io/google_containers/heapster:v1.1.0-beta2] 116127080} {[gcr.io/google_samples/gb-redisslave:v1] 109508753} {[gcr.io/google_containers/nginx:1.7.9] 91664166} {[gcr.io/google_containers/kubedns-amd64:1.2] 48915012} {[gcr.io/google_containers/addon-resizer:1.0] 36760898} {[gcr.io/google_containers/nettest:1.8] 25164808} {[gcr.io/google_containers/netexec:1.5] 7358440} {[gcr.io/google_containers/exechealthz-amd64:1.0] 7115733} {[gcr.io/google_containers/dnsmasq:1.1] 5123051} {[gcr.io/google_containers/serve_hostname:1.1] 4522409} {[gcr.io/google_containers/mounttest:0.6] 2084693} {[gcr.io/google_containers/busybox:1.24] 1113554} {[gcr.io/google_containers/pause-amd64:3.0] 746888} {[gcr.io/google_containers/pause:2.0] 350164} {[gcr.io/google_containers/pause:0.8.0] 241656}]}}
08:45:24 Jun  3 08:45:24.254: INFO: 
08:45:24 Logging kubelet events for node gke-jenkins-e2e-default-pool-733837a5-k0ig
08:45:24 Jun  3 08:45:24.293: INFO: 
08:45:24 Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-733837a5-k0ig
08:45:24 Jun  3 08:45:24.415: INFO: heapster-v1.1.0.beta2-142973226-faadi started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.415: INFO: kube-dns-v13-renzr started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.415: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-k0ig started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.415: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-k0ig started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.600: INFO: 
08:45:24 Latency metrics for node gke-jenkins-e2e-default-pool-733837a5-k0ig
08:45:24 Jun  3 08:45:24.600: INFO: 
08:45:24 Logging node info for node gke-jenkins-e2e-default-pool-733837a5-m9ba
08:45:24 Jun  3 08:45:24.637: INFO: Node Info: &{{ } {gke-jenkins-e2e-default-pool-733837a5-m9ba   /api/v1/nodes/gke-jenkins-e2e-default-pool-733837a5-m9ba 479ae09c-2999-11e6-9c54-42010af00003 20868 0 2016-06-03 07:41:38 -0700 PDT <nil> <nil> map[cloud.google.com/gke-nodepool:default-pool failure-domain.beta.kubernetes.io/region:us-central1 failure-domain.beta.kubernetes.io/zone:us-central1-f kubernetes.io/hostname:gke-jenkins-e2e-default-pool-733837a5-m9ba beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:n1-standard-2 beta.kubernetes.io/os:linux] map[volumes.kubernetes.io/controller-managed-attach-detach:true]} {10.180.4.0/24 4724084296971462713 gce://kube-gke-upg-1-2-1-3-upg-clu/us-central1-f/gke-jenkins-e2e-default-pool-733837a5-m9ba false} {map[pods:{110.000 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI} cpu:{2.000 DecimalSI} memory:{7864135680.000 BinarySI}] map[cpu:{2.000 DecimalSI} memory:{7864135680.000 BinarySI} pods:{110.000 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI}]  [{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2016-06-03 07:42:09 -0700 PDT RouteCreated RouteController created a route} {OutOfDisk False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 08:39:53 -0700 PDT KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 07:41:38 -0700 PDT KubeletHasSufficientMemory kubelet has sufficient memory available} {Ready True 2016-06-03 08:45:16 -0700 PDT 2016-06-03 08:39:53 -0700 PDT KubeletReady kubelet is posting ready status. WARNING: CPU hardcapping unsupported}] [{InternalIP 10.240.0.2} {ExternalIP 104.154.40.192}] {{10250}} { 6B629B95-4C5D-5DF5-0857-E3CD1BDC7F3E 252dd347-6f72-41fc-8c8d-3cdaeeb768b8 3.16.0-4-amd64 Debian GNU/Linux 7 (wheezy) docker://1.9.1 v1.3.0-alpha.5.38+1ad3e11a59dc56 v1.3.0-alpha.5.38+1ad3e11a59dc56} [{[gcr.io/google_containers/redis:e2e] 419003740} {[gcr.io/google_containers/fluentd-gcp:1.18] 411450900} {[redis:latest] 184859519} {[gcr.io/google_containers/kube-proxy:7bdadb0ebfdd73c80cfe5d864838e203] 178177849} {[gcr.io/google_containers/resource_consumer:beta2] 132819513} {[gcr.io/google_containers/nginx:1.7.9] 91664166} {[gcr.io/google_containers/nettest:1.7] 24051275} {[gcr.io/google_containers/hostexec:1.2] 13209617} {[gcr.io/google_containers/netexec:1.5] 7358440} {[gcr.io/google_containers/netexec:1.4] 7297019} {[gcr.io/google_containers/test-webserver:e2e] 4534272} {[gcr.io/google_containers/serve_hostname:1.1] 4522409} {[b.gcr.io/k8s_authenticated_test/serve_hostname:1.1] 4522409} {[gcr.io/google_containers/portforwardtester:1.0] 2296329} {[gcr.io/google_containers/mounttest:0.6] 2084693} {[gcr.io/google_containers/mounttest:0.2] 1752375} {[gcr.io/google_containers/mounttest:0.5] 1718853} {[gcr.io/google_containers/mounttest-user:0.3] 1718853} {[gcr.io/google_containers/busybox:1.24] 1113554} {[gcr.io/google_containers/pause-amd64:3.0] 746888} {[gcr.io/google_containers/pause:2.0] 350164} {[gcr.io/google_containers/pause:0.8.0] 241656}]}}
08:45:24 Jun  3 08:45:24.637: INFO: 
08:45:24 Logging kubelet events for node gke-jenkins-e2e-default-pool-733837a5-m9ba
08:45:24 Jun  3 08:45:24.677: INFO: 
08:45:24 Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-733837a5-m9ba
08:45:24 Jun  3 08:45:24.798: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-m9ba started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.798: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-m9ba started at <nil> (0 container statuses recorded)
08:45:24 Jun  3 08:45:24.931: INFO: 
08:45:24 Latency metrics for node gke-jenkins-e2e-default-pool-733837a5-m9ba
08:45:24 Jun  3 08:45:24.931: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:38.840919s}
08:45:24 Jun  3 08:45:24.931: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.049604s}
08:45:24 Jun  3 08:45:24.931: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:12.827438s}
08:45:24 Jun  3 08:45:24.931: INFO: 
08:45:24 Logging node info for node gke-jenkins-e2e-default-pool-733837a5-pw73
08:45:24 Jun  3 08:45:24.970: INFO: Node Info: &{{ } {gke-jenkins-e2e-default-pool-733837a5-pw73   /api/v1/nodes/gke-jenkins-e2e-default-pool-733837a5-pw73 e6fd70ad-297a-11e6-9c54-42010af00003 20870 0 2016-06-03 04:04:11 -0700 PDT <nil> <nil> map[failure-domain.beta.kubernetes.io/zone:us-central1-f kubernetes.io/e2e-caeac20f-2998-11e6-a16b-0242ac110013:42 kubernetes.io/hostname:gke-jenkins-e2e-default-pool-733837a5-pw73 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:n1-standard-2 beta.kubernetes.io/os:linux cloud.google.com/gke-nodepool:default-pool failure-domain.beta.kubernetes.io/region:us-central1] map[volumes.kubernetes.io/controller-managed-attach-detach:true]} {10.180.3.0/24 7627785847550303539 gce://kube-gke-upg-1-2-1-3-upg-clu/us-central1-f/gke-jenkins-e2e-default-pool-733837a5-pw73 false} {map[pods:{110.000 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI} cpu:{2.000 DecimalSI} memory:{7864135680.000 BinarySI}] map[memory:{7864135680.000 BinarySI} pods:{110.000 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{0.000 DecimalSI} cpu:{2.000 DecimalSI}]  [{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2016-06-03 04:04:35 -0700 PDT RouteCreated RouteController created a route} {OutOfDisk False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 07:05:00 -0700 PDT KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2016-06-03 08:45:16 -0700 PDT 2016-06-03 04:04:11 -0700 PDT KubeletHasSufficientMemory kubelet has sufficient memory available} {Ready True 2016-06-03 08:45:16 -0700 PDT 2016-06-03 07:05:00 -0700 PDT KubeletReady kubelet is posting ready status. WARNING: CPU hardcapping unsupported}] [{InternalIP 10.240.0.5} {ExternalIP 104.155.138.199}] {{10250}} { AAFBE8FC-54BB-8778-FB39-1157925BC857 319dfcf0-fae7-428a-9997-7f493f7f8213 3.16.0-4-amd64 Debian GNU/Linux 7 (wheezy) docker://1.9.1 v1.3.0-alpha.5.38+1ad3e11a59dc56 v1.3.0-alpha.5.38+1ad3e11a59dc56} [{[gcr.io/google_samples/gb-frontend:v3] 509707703} {[gcr.io/google_containers/redis:e2e] 419003740} {[gcr.io/google_containers/fluentd-gcp:1.18] 411450900} {[gcr.io/google_containers/jessie-dnsutils:e2e] 190148402} {[redis:latest] 184859519} {[gcr.io/google_containers/kube-proxy:7bdadb0ebfdd73c80cfe5d864838e203] 178177849} {[gcr.io/google_containers/dnsutils:e2e] 141895666} {[gcr.io/google_containers/resource_consumer:beta2] 132819513} {[gcr.io/google_samples/gb-redisslave:v1] 109508753} {[gcr.io/google_containers/nginx:1.7.9] 91664166} {[gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta1] 43632597} {[gcr.io/google_containers/nettest:1.8] 25164808} {[gcr.io/google_containers/hostexec:1.2] 13209617} {[gcr.io/google_containers/defaultbackend:1.0] 7513643} {[gcr.io/google_containers/netexec:1.5] 7358440} {[gcr.io/google_containers/netexec:1.4] 7297019} {[gcr.io/google_containers/goproxy:0.1] 5489816} {[gcr.io/google_containers/porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab] 5010921} {[gcr.io/google_containers/fakegitserver:0.1] 5007469} {[gcr.io/google_containers/update-demo:nautilus] 4555533} {[gcr.io/google_containers/update-demo:kitten] 4549069} {[gcr.io/google_containers/test-webserver:e2e] 4534272} {[gcr.io/google_containers/serve_hostname:1.1] 4522409} {[b.gcr.io/k8s_authenticated_test/serve_hostname:1.1] 4522409} {[gcr.io/google_containers/eptest:0.1] 2970692} {[gcr.io/google_containers/busybox:latest] 2433303} {[gcr.io/google_containers/portforwardtester:1.0] 2296329} {[gcr.io/google_containers/mounttest:0.6] 2084693} {[gcr.io/google_containers/mounttest:0.5] 1718853} {[gcr.io/google_containers/mounttest-user:0.3] 1718853} {[gcr.io/google_containers/busybox:1.24] 1113554} {[busybox:latest] 1112820} {[gcr.io/google_containers/pause-amd64:3.0] 746888} {[gcr.io/google_containers/pause:2.0] 350164} {[gcr.io/google_containers/pause:0.8.0] 241656}]}}
08:45:24 Jun  3 08:45:24.970: INFO: 
08:45:24 Logging kubelet events for node gke-jenkins-e2e-default-pool-733837a5-pw73
08:45:25 Jun  3 08:45:25.010: INFO: 
08:45:25 Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-733837a5-pw73
08:45:25 Jun  3 08:45:25.131: INFO: kubernetes-dashboard-v1.1.0-beta1-euaml started at <nil> (0 container statuses recorded)
08:45:25 Jun  3 08:45:25.131: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-733837a5-pw73 started at <nil> (0 container statuses recorded)
08:45:25 Jun  3 08:45:25.131: INFO: kube-proxy-gke-jenkins-e2e-default-pool-733837a5-pw73 started at <nil> (0 container statuses recorded)
08:45:25 Jun  3 08:45:25.131: INFO: l7-default-backend-v1.0-oizcz started at <nil> (0 container statuses recorded)
08:45:25 Jun  3 08:45:25.295: INFO: 
08:45:25 Latency metrics for node gke-jenkins-e2e-default-pool-733837a5-pw73
08:45:25 Jun  3 08:45:25.295: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:46.752444s}
08:45:25 Jun  3 08:45:25.295: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:46.752444s}
08:45:25 Jun  3 08:45:25.295: INFO: Waiting up to 1m0s for all nodes to be ready
08:45:25 STEP: Destroying namespace "e2e-tests-metrics-grabber-huhgp" for this suite.
08:45:30 
08:45:30 • Failure [6.799 seconds]
08:45:30 MetricsGrabber
08:45:30 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:158
08:45:30   should grab all metrics from API server. [It]
08:45:30   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:100
08:45:30 
08:45:30   Expected
08:45:30       <sets.String | len:1>: {
08:45:30           "authenticated_user_requests": {},
08:45:30       }
08:45:30   to be empty
08:45:30 
08:45:30   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:97
```

View logs and artifacts at https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.3-upgrade-cluster/178

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #26800

### CODE REVIEW

**Comment by ihmccreery** [comment]
Is this a fix for #26800?  Should we close #26887?

**Comment by ihmccreery** [comment]
Fix for #26800?

**Comment by ihmccreery** [comment]
I have pretty much zero context on this; @gmarek is there someone else who'd be a better reviewer?

**Comment by gmarek** [comment]
I don't think so. We added it to have a list of exposed metrics somewhere, but given the amount of pain it causes I don't think it's worth maintaining.

**Comment by ihmccreery** [comment]
Like I said, zero context, but if there are no better reviewers, LGTM.

**Pull request merged**
