### PR TITLE
coreos/azure: Move into a separate repo

### PR DESCRIPTION
**Pull request by errordeveloper**
It's easier to maintain it externally.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23818)

### CODE REVIEW

**Comment by errordeveloper** [comment]
I'll follow-up with an update to docs repo.

**Comment by errordeveloper** [comment]
What is `release-note-label-needed`?

**Comment by errordeveloper** [comment]
xref https://github.com/kubernetes/kubernetes.github.io/pull/314

**Comment by errordeveloper** [comment]
@johndmulhausen ping

**Comment by smarterclayton** [comment]
ok to test

**Comment by errordeveloper** [comment]
Has the build failed as I am missing something in this commit?

**Comment by errordeveloper** [comment]
This is a clean-up, does anyone have concerns about removing this or moving it into a separate repo?

**Comment by smarterclayton** [comment]
Does the link in to this guide need to be changed?  Do you need to leave a breadcrumb to the new location?

**Comment by errordeveloper** [comment]
I have PR for docs repo already.

**Comment by smarterclayton** [comment]
Can you link it here?

**Comment by errordeveloper** [comment]
@smarterclayton I've referenced it already, but it's got lost in the noise. It's the kubernetes/kubernetes.github.io#314.

**Comment by smarterclayton** [comment]
LGTM

**Comment by errordeveloper** [comment]
It doesn't seem to appear on submit queue... should someone remove **`do-not-merge`** label?

**Comment by errordeveloper** [comment]
@johndmulhausen what are we supposed to do here? @k8s-bot keeps adding **`do-not-merge`**.

**Comment by smarterclayton** [comment]
Oh, we have to direct merge.  Oncall should do that on Tuesday.

**Comment by errordeveloper** [comment]
It'd be really great to get this merged soon!

**Comment by pwittrock** [comment]
@errordeveloper rebase and we can merge it

**Comment by errordeveloper** [comment]
@pwittrock rebased.

**Comment by pwittrock** [comment]
@errordeveloper I'll merge this Monday during business hours.

Do we need to do anything to the kubernetes/kubernetes.github.io repo?

**Comment by errordeveloper** [comment]
@pwittrock for the record, docs changes were merged in kubernetes/kubernetes.github.io#314, which I've referenced earlier.

**Pull request merged**
