### PR TITLE
Remove v1alpha1 admissionregistration APIs (ValidatingAdmissionPolicies & ValidatingAdmissionPolicyBindings)

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed support for v1alpha1 version of ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding API kinds.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Remove the v1alpha1 resources ValidatingAdmissionPolicies and ValidatingAdmissionPolicyBindings
+Removed support for v1alpha1 ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding API kinds.
```

**Comment by Jefftree** [comment]
> Changelog suggestion
> 
> ```diff
> -Remove the v1alpha1 resources ValidatingAdmissionPolicies and ValidatingAdmissionPolicyBindings
> +Removed support for v1alpha1 version of ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding API kinds.
> ```

Fixed, thanks!

**Comment by jpbetz** [comment]
/approve
/lgtm

I agree this is an appropriate time for this removal.

**Pull request merged**
