### PR TITLE
[Provider/Azure] cache map remove exists check

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Improve complexity from O(logN) [additional lookup] to O(1) as map deletion doesn't require lookup.
From Efffective Go: To delete a map entry, use the delete built-in function, whose arguments are the map and the key to be deleted. It's safe to do this even if the key is already absent from the map.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
Thanks for the improvements

/area provider/azure
/ok-to-test

**Review by aramase — COMMENTED** [review]
Thank you for the change.

/lgtm

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
