### PR TITLE
Disable verify-bazel on release-1.5.

### PR DESCRIPTION
**Pull request by spxtr**
We're going to make some breaking changes to gazel. We'll ensure that master is happy, but it's a bother to also ensure release-1.5 is happy.

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @saad-ali

**Comment by spxtr** [comment]
This is not a cherrypick, but if I want it to merge do I stick `cherrypick-approved` on it anyway?

**Comment by mikedanese** [comment]
Need to also remove hack/update-bazel.sh

**Comment by saad-ali** [comment]
Ack, thanks for the heads up

**Comment by spxtr** [comment]
Ok done. BTW `/lgtm cancel` works.

**Comment by mikedanese** [comment]
@k8s-bot verify test this

**Pull request merged**
