### PR TITLE
Bugfix: cloud-controller-manager routeController.run() block in WaitForCacheSync

### PR DESCRIPTION
**Pull request by guangyouyu**
**What this PR does / why we need it**:
cloud-controller-manager routeController.run not run in goroutine will block to  wait nodeListerSynced because sharedInformers not started

**Special notes for your reviewer**:

cloud-controller-manager routeController.run  should run in goroutine like the same code in kube-controller-manager,or it will block to  wait nodeListerSynced,but sharedInformers not startd.

```go
//controller-manager.go:197
func StartControllers(s *options.CloudControllerManagerServer, kubeconfig *restclient.Config, rootClientBuilder, clientBuilder controller.ControllerClientBuilder, stop <-chan struct{}, recorder record.EventRecorder, cloud cloudprovider.Interface) error {
	// Function to build the kube client object
	client := func(serviceAccountName string) clientset.Interface {
		return rootClientBuilder.ClientOrDie(serviceAccountName)
	}
	versionedClient := client("shared-informers")
	sharedInformers := informers.NewSharedInformerFactory(versionedClient, resyncPeriod(s)())
ocateNodeCIDRs && s.ConfigureCloudRoutes {
		if routes, ok := cloud.Routes(); !ok {
			glog.Warning("configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.")
		} else {
			routeController := routecontroller.New(routes, client("route-controller"), sharedInformers.Core().V1().Nodes(), s.ClusterName, clusterCIDR)
                       //should run in goroutine
----->		routeController.Run(stop, s.RouteReconciliationPeriod.Duration)
			time.Sleep(wait.Jitter(s.ControllerStartInterval.Duration, ControllerStartJitter))
		}
	} else {
		glog.Infof("Will not configure cloud provider routes for allocate-node-cidrs: %v, configure-cloud-routes: %v.", s.AllocateNodeCIDRs, s.ConfigureCloudRoutes)
	}

---> 	sharedInformers.Start(stop)

	select {}
}



//routecontroller.go:77
func (rc *RouteController) Run(stopCh <-chan struct{}, syncPeriod time.Duration) {
	defer utilruntime.HandleCrash()

	glog.Info("Starting the route controller")
       //will block
--->   	if !cache.WaitForCacheSync(stopCh, rc.nodeListerSynced) {
		utilruntime.HandleError(fmt.Errorf("timed out waiting for caches to sync"))
		return
	}

	go wait.NonSlidingUntil(func() {
		if err := rc.reconcileNodeRoutes(); err != nil {
			glog.Errorf("Couldn't reconcile node routes: %v", err)
		}
	}, syncPeriod, wait.NeverStop)
}
```

### CODE REVIEW

**Comment by guangyouyu** [comment]
signed @k8s-ci-robot

**Comment by guangyouyu** [comment]
I signed  it!

**Comment by guangyouyu** [comment]
I signed it!

**Comment by bulletRush** [comment]
@k8s-ci-robot

**Comment by guangyouyu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44379)*

**Comment by guangyouyu** [comment]
I signed it!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44379#-:-KhW4He8pVgjXHs6T6lU:b-15k642)*

**Comment by guangyouyu** [comment]
I signed it!

**Comment by mikedanese** [comment]
This looks correct as is. I'm worried about silently not starting the route controller after this change.

**Comment by ncdc** [comment]
@mikedanese yeah, we need to go back through all the controllers that wait on caches to sync and clearly log

1. Starting controller x
2. Controller x is waiting on caches to sync
3. Controller x's caches are synced, now ready to perform work

cc @smarterclayton @deads2k

**Comment by mikedanese** [comment]
What happens here if we hit "timed out waiting for caches to sync"? It seems like we just don't start the controller, but it would be preferable to crash as that's much easier to detect.

**Comment by ncdc** [comment]
@mikedanese effectively it will wait forever (until `stopCh` is closed, which afaik only happens at process termination).

**Comment by mikedanese** [comment]
/approve

ok, thanks.

**Comment by thelinuxfoundation** [comment]
bump for CLA check

**Comment by ncdc** [comment]
xref https://github.com/kubernetes/kubernetes/pull/44408 for controller consistency

**Comment by guangyouyu** [comment]
@ncdc  e2e test failed,cloud you please tell me what should i do?

**Comment by ncdc** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
