### PR TITLE
Add centurylink cloud turn-key k8s cluster provisioning

### PR DESCRIPTION
**Pull request by ckleban**
Adding our turnkey scripts to get Kubernetes up and running on
CenturyLink Cloud VMs and Physical Servers.

### CODE REVIEW

**Comment by ckleban** [comment]
Hello, 

Let me know if there is anything I need to do for this or if you have any feedback. 

Thanks
Chris

**Comment by bgrant0607** [comment]
Sorry, this is going to have to wait until after we cut the 1.2 branch.

**Comment by bgrant0607** [comment]
.We have moved getting-started-guide docs to the kubernetes.github.io repo. Could you please move those changes to a PR on that repo, reference this PR, and @bgrant0607?

**Comment by mikedanese** [comment]
Can you submit this to be a subproject of kube-deploy? I think that's the best place for it.

**Pull request closed without merging**
