### PR TITLE
code cleanup: append slice without check

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We don't have to check the length of added element when using `append`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by BinacsLee** [comment]
cc @robscott @bowei 
Thanks a lot!

**Comment by BinacsLee** [comment]
/assign @thockin 
Thanks a lot ^-^

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by BinacsLee** [comment]
@pacoxu  SOS...
'ok-to-test' is needed, could you please do me a favor? Thanks！

**Comment by BinacsLee** [comment]
> /ok-to-test

According to the time zone, I was not sure if you were there. So I pinged another one. Anyway, thank you! ^-^

**Pull request merged**
