### PR TITLE
Move kubelet internal ComponentConfig types to `pkg/kubelet/apis/config`

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
This PR is split out from the main PR of https://github.com/kubernetes/kubernetes/pull/67263, in order to make merging each scoped piece of the puzzle easier and smoother.

This PR simply moves the `k8s.io/kubernetes/pkg/apis/kubeletconfig` as-is to `k8s.io/kubernetes/pkg/apis/config` as agreed in the KEP.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: kubernetes/community#2354

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-node-pr-reviews 
/assign @mtaufen @thockin @liggitt

### CODE REVIEW

**Comment by luxas** [comment]
/test pull-kubernetes-node-e2e
flake

**Comment by mtaufen** [comment]
This needs a gofmt on a couple files.

**Pull request merged**
