### PR TITLE
Update defaultbackend image to 1.4 and deployment apiVersion to apps/v1

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
Update defaultbackend image to 1.4 and deployment apiVersion to apps/v1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```Update defaultbackend image to 1.4 and deployment apiVersion to apps/v1

```

### CODE REVIEW

**Comment by roberthbailey** [comment]
@nicksardo - please lgtm if this change looks ok to you

**Comment by nicksardo** [comment]
cc @aledbf

**Pull request merged**
