### PR TITLE
Fix pkg/kubelet/oom/oom_watcher_linux_test.go

### LINKED ISSUE #77392: [Failing test] //pkg/kubelet/oom failing on bazel-test-master
**Which jobs are failing**:
ci-kubernetes-bazel-test

**Which test(s) are failing**:
//pkg/kubelet/oom

**Since when has it been failing**:
https://github.com/kubernetes/kubernetes/compare/a5a70b4de...ba28e0e0f
1st of May 23:29 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/kubelet/oom:go_default_test
-----------------------------------------------------------------------------
--- FAIL: TestBasic (0.00s)
    oom_watcher_linux_test.go:32: 
        	Error Trace:	oom_watcher_linux_test.go:32
        	Error:      	Received unexpected error:
        	            	open /dev/kmsg: no such file or directory
        	Test:       	TestBasic
FAIL
```

**Anything else we need to know**:
/milestone v1.15
/kind failing-test
/priority critical-urgent
/sig node
/sig api-machinery

cc. @alejandrox1 @jimangel @rarchk @smourapina

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This test is failing because it attempts to access `/dev/kmsg`. It is
slightly unexpected that a unit test would try and access a file like
this. To account for this, we skip the test if either `/dev/kmsg`
doesn't exist or if we don't have permissions to access it.

Another alternative would be making this test an integration/e2e test,
because then we could be more confident w.r.t. the environment its
running in. However, the `oom_watcher` feels like too small a component
to warrant its own integration test, especially because its not
interacting with any other k8s components.

Another option would be addressing the TODO in this test (i.e. mocking
out cadvisor), but it doesn't appear that's possible yet.

**Which issue(s) this PR fixes**:
Fixes #77392 

**Special notes for your reviewer**:
cc @alenkacz

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
cc @bjhaid if you're interested :)

/assign @yujuhong 

thanks :)

**Comment by mattjmcnaughton** [comment]
This passed the `pull-kubernetes-bazel-test`.

**Review by alenkacz — APPROVED** [review]
Elegant way to go around this :-) I would be just a bit scared if we ever run this test then... Because now we can just silently skip it everywhere in the worst case scenario.

Any idea @mattjmcnaughton why it started failing few days ago? Is it maybe connected to the changes around bazel tests?

**Comment by mattjmcnaughton** [comment]
On Sat, May 04, 2019 at 07:17:53AM -0700, Alena Varkockova wrote:
> alenkacz approved this pull request.
> 
> Elegant way to go around this :-) I would be just a bit scared if we ever run this test then... Because now we can just silently skip it everywhere in the worst case scenario.
> 
> Any idea @mattjmcnaughton why it started failing few days ago? Is it maybe connected to the changes around bazel tests?
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/77441#pullrequestreview-233738065

Great questions @alenkacz! I agree this is definitely risky... I think the real
solution is that we should be mocking our `cadvisor` here, but I'm not sure
that's a trivial change to make and I'm hesitant to attempt it while master
remains broken.

As to why it just started failing, I haven't looked into it to be honest. It
passes for me locally even without my fix...

**Comment by alenkacz** [comment]
I'll try to reach out to someone from sig-testing. It's pretty strange that it started failing at one point and now keeps failing all the time. Would be good to know the real cause...

**Comment by alejandrox1** [comment]
Will label the priority as urgent since it is affecting a sig-release master-blocking job. Please change as appropriate.
/priority critical-urgent
/milestone v1.15

**Comment by fejta** [comment]
> why it started failing few days ago? Is it maybe connected to the changes around bazel tests?

This job has not changed, it does not use RBE.

I suspect the issue here is that these tests stopped running in a privileged container, which is the only situation in which /dev/kmsg is available.

Ideally we fix the test to not require running in an insecure container.

The following lines will add back privilege:

 https://github.com/kubernetes/test-infra/blob/fbb2a4056eafebb8ffdcc0bfb356049338bb2fd6/config/jobs/kubernetes/sig-testing/bazel-build-test.yaml#L278-L279

Here is where the master version of this job is defined:
https://github.com/kubernetes/test-infra/blob/fbb2a4056eafebb8ffdcc0bfb356049338bb2fd6/config/jobs/kubernetes/sig-testing/bazel-build-test.yaml#L282-L308

**Comment by fejta** [comment]
Here's where we stopped using privilege for the job: https://github.com/kubernetes/test-infra/commit/8ce3aab15ff8d3ec858992ce014cf7e3667cc1e1#diff-2f6de312af814024dcf50517c2078484

Here's where we added it back for some jobs: https://github.com/kubernetes/test-infra/commit/52943289ea22f953d57369c5cdf30ac0f028970a#diff-2f6de312af814024dcf50517c2078484

**Comment by alenkacz** [comment]
I think we can close this one then... ?

**Review by alenkacz — CHANGES_REQUESTED** [review]
Probably not needed anymore since we found the reason why it stopped working and it got fixed

**Comment by bjhaid** [comment]
@alenkacz this is needed to prevent false errors in local development, it fails when I run `make tests` from my development machine

**Comment by alenkacz** [comment]
@bjhaid but it's also pretty dangerous thing to have in place because it can hide real errors in CI...

**Comment by fejta** [comment]
Is there any way to redesign the test to not require a privileged container?

**Pull request closed without merging**
