### PR TITLE
Revert "Merge pull request #51008 from kubernetes/revert-50789-fix-scheme"

### LINKED ISSUE #51007: [SQ-blocking] All kubemark jobs started failing due to kubelet changes
Ref: https://k8s-testgrid.appspot.com/sig-scalability

@mtaufen - Your PR https://k8s-testgrid.appspot.com/sig-scalability was the only one in the diff, and it seems like it broke hollow-kubelet. I'll try to take a further look into it, but for now I think we should revert it as it is blocking the SQ.

@kubernetes/sig-scalability-misc @wojtek-t

### PR DESCRIPTION
**Pull request by mtaufen**
I'm spinning up a cluster right now to test this fix, but I'm pretty sure this was the problem.
There doesn't seem to be a way to confirm from logs, because AFAICT the logs from the hollow kubelet containers are not collected as part of the kubemark test.

**What this PR does / why we need it**:

This reverts commit f4afdecef85e83e7b83fc8a6d63a220c9a10acc0, reversing
changes made to e633a1604f00908a1dcc898b206c3404db4d82ed.

This also fixes a bug where Kubemark was still using the core api scheme
to manipulate the Kubelet's types, which was the cause of the initial
revert.

**Which issue this PR fixes**: fixes #51007

**Release note**:

```release-note
NONE
```

/cc @shyamjvs @wojtek-t

### CODE REVIEW

**Comment by mtaufen** [comment]
Looks like all of the hollow-kubelets have at least made it to running on my test cluster:
```
NAME                    READY     STATUS    RESTARTS   AGE
heapster-v1.3.0-2cdjg   2/2       Running   0          16m
hollow-node-57fl9       3/3       Running   0          16m
hollow-node-5qhtv       3/3       Running   0          16m
hollow-node-98wxd       3/3       Running   0          16m
hollow-node-b6wd9       3/3       Running   0          16m
hollow-node-kpjvd       3/3       Running   0          16m
hollow-node-pnmlb       3/3       Running   0          16m
hollow-node-qdztk       3/3       Running   0          16m
hollow-node-rq9xx       3/3       Running   0          16m
hollow-node-t5cvw       3/3       Running   0          16m
hollow-node-x7pvg       3/3       Running   0          16m
```

**Comment by shyamjvs** [comment]
That's cool - thanks for fixing it.

**Comment by shyamjvs** [comment]
/lgtm
Let's wait and see if the pr-kubemark job goes green.
I unfortunately couldn't figure out how it passed in your previous PR due to hollow-node logs not being collected (I'll try to fix that).
But it definitely did fail a few times before @fejta-bot's retrying was successful - 
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/50789/pull-kubernetes-kubemark-e2e-gce/
(look at runs starting from 46470 as I think that's the first one after you last pushed a commit into the PR)

**Pull request merged**
