### PR TITLE
update header comment

### PR DESCRIPTION
**Pull request by yiyang5055**
**What type of PR is this?**

**What this PR does / why we need it**:

only update header comment

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

thank you for this fix.

are there any other instances of this header being incorrect that we want to clean up in this diff?

**Comment by yiyang5055** [comment]
@mattjmcnaughton You reminded me that I forgot the same mistake in `deviceplugin/v1alpha/api.proto`, this is my first PR, i don't know what should i do? close this pr and repull request?

**Comment by yiyang5055** [comment]
@jiayingz @mindprince need approved, lgtm

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by yiyang5055** [comment]
pinging @dchen1107

**Pull request closed without merging**
