### PR TITLE
Remove fluentd-gcp image sources

### PR DESCRIPTION
**Pull request by crassirostris**
This PR removes fluentd-gcp image sources from the main kubernetes repo to move it the `contrib`: https://github.com/kubernetes/contrib/pull/2426

Once image is moved, it will be maintained by Stackdriver team (@igorpeshansky, @qingling128 and @dhrupadb)

CC @ixdy @timstclair

### CODE REVIEW

**Comment by piosz** [comment]
#41998 is merged. LGTM
Please fix tests and add an information where the configuration was moved to.

**Comment by piosz** [comment]
I meant as README in the image directory

**Comment by Crassirostris** [comment]
Shouldn't merge until https://github.com/kubernetes/contrib/pull/2426 is merged, to avoid readme pointing to the non-existing location

**Comment by Crassirostris** [comment]
https://github.com/kubernetes/contrib/pull/2426 is merged, removing `do-not-merge` label

**Comment by ethernetdan** [comment]
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by Crassirostris** [comment]
@ethernetdan This is just moving some files out of the repo (it's already there: https://github.com/kubernetes/contrib/pull/2426), not a feature. Can it be counted as a bug?

**Comment by timstclair** [comment]
This is an artifact of the fact that PRs cannot span repos. I suggest treating it as though it were a single PR.

**Comment by ethernetdan** [comment]
@timstclair @Crassirostris sgtm

**Comment by crassirostris** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Comment by crassirostris** [comment]
@k8s-bot node e2e test this

**Comment by crassirostris** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
