### PR TITLE
[WIP] Pass through proxy logs to executor log output

### PR DESCRIPTION
**Pull request by sttts**
Fixes https://github.com/mesosphere/kubernetes-mesos/issues/417

The log output looks like this:

```
I0728 09:38:09.865143     182 service.go:573] proxy: I0728 09:38:09.865111     191 iptables.go:193] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
```

### CODE REVIEW

**Comment by sttts** [comment]
An alternative would be to use https://github.com/natefinch/lumberjack and rotate the proxy.log file.

**Comment by jdef** [comment]
The kubelet-executor launches the proxy internally because it helped keep deployment simpler *for development* at the cost of adding a process lifecycle dependency between the two procs. As ugly side affect of this was the the executor piped the proxy logs to a separate file to keep the log files easier to read. 

Honestly I really don't like the idea of the executor mantaining the lifecycle of the proxy process in a production setting. The processes should be completely independent. We should be aiming to *more closely* align our process lifecycle model after upstream. Piping the logs from the proxy through the executor's stderr stream works against this idea and also further complicates the log files.

Please, let's avoid this approach.

**Comment by sttts** [comment]
I don't disagree. But we really need something simpler than copying around installer tar files, patching the system with bind bind mounds and so.

**Comment by sttts** [comment]
Superseeded by #11928

**Pull request closed without merging**
