### PR TITLE
Automated cherry pick of #103997: Fix: ignore not a VMSS error for VMAS nodes in

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #103997 on release-1.21.

#103997: Fix: ignore not a VMSS error for VMAS nodes in

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by nilo19** [comment]
/triage accepted
/sig cloud-provider
/area provider/azure
/priority critical-urgent
cc @feiskyer
/kind bug

**Review by feiskyer — APPROVED** [review]
/lgtm

Could you also cherry-pick it to 1.22 branch?

**Comment by puerco** [comment]
Thank you @nilo19 !!
/lgtm

**Pull request merged**
