### PR TITLE
Default to no timeout for kubelet streaming-connection-idle-timeout.

### PR DESCRIPTION
**Pull request by cjcullen**
Currently, `kubectl exec` will drop after 5 minutes unattended. I think we should leave that open indefinitely.

No timeout may be a little concerning. If there are legitimate worries about unbounded growth of connections, I could change this to something high but finite.

This is related, but sort of orthogonal to #12179.

@krousey @brendandburns @jlowdermilk

### CODE REVIEW

**Comment by eliaslevy** [comment]
At the very least a timeout command line parameter to `kubectl exec` would be welcomed.  I can't count the number of times I've closed a terminal by error by entering ^D while trying to exit from a shell spawned via `kubectl exec` because the connection had timed out and the ^D was process by the local shell rather than the remote one.

**Comment by ncdc** [comment]
@sdodson @brenton @liggitt what are your thoughts on making the default exec/attach/port-forward timeout infinite i.e. no timeout? It's configurable via a setting on the Kubelet and currently defaults to 5 minutes.

**Comment by liggitt** [comment]
My main concerns are about ephemeral port exhaustion and never cleaning up if we leak a connection

**Comment by sdodson** [comment]
@ncdc seems like what users would expect but not sure how risky it is.

**Comment by cjcullen** [comment]
I don't think sshd would drop my connection if I left my client machine active all night. And I'd expect the port-forwarding case to be able to last longer than 5 minutes.

It'd be nice to try it out, and see if it borks our Jenkins soak cluster :).

**Comment by smarterclayton** [comment]
Port exhaustion is definitely the primary concern on both the kubelet and
the masters.  I don't know of other concerns since the go stack can handle
millions of connections probably.

**Comment by cjcullen** [comment]
I'm going to close this and just roll it into #19314.

I set it to `4*time.Hour` in that PR.

**Pull request closed without merging**
