### PR TITLE
Object r repeat close

### PR DESCRIPTION
**Pull request by foxyriver**
**What this PR does / why we need it**:

Object r repeat close. 
each end of the for loop, the object r has been closed. so omitting defer r.close(), to avoid repeat close.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Thanks @foxyriver. LGTM.

**Comment by foxyriver** [comment]
@caesarxuchao rebase again , the robot removed lgtm , please tag me again

**Comment by caesarxuchao** [comment]
Actually why not removing the r.close() at the end of the function? Otherwise, if the test case returns at `t.Fatal`, then no one is going to close r.

**Comment by lavalamp** [comment]
I think the ideal fix is to use defer, but run what is currently the body of the for loop in an anonymous function. That way it is closed at the right time and also closed if an error case triggers.

**Comment by foxyriver** [comment]
@lavalamp I have modified it as you say, please check it

**Comment by foxyriver** [comment]
@dims @caesarxuchao Please recheck.

**Comment by smarterclayton** [comment]
LGTM but you'll need to rebase

**Comment by foxyriver** [comment]
@lavalamp @smarterclayton rebase again, PTAL

**Pull request merged**
