### PR TITLE
Clarify NetworkPolicy policyTypes in docs

### LINKED ISSUE #69490: Unclear Network Policy's "policyTypes" definition in spec documentation
**Is this a BUG REPORT or FEATURE REQUEST?**: bug report
/kind bug

**What happened**: I was reading the documentation for `NetworkPolicy` as defined [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#networkpolicyspec-v1-networking-k8s-io)

**What you expected to happen**: To have clear documentation

**How to reproduce it (as minimally and precisely as possible)**: Read the following, as seen in the 1.12 docs:
> `policyTypes ` List of rule types that the NetworkPolicy relates to. Valid options are Ingress, Egress, or Ingress,Egress. [...]

**Anything else we need to know?**: Nope

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update the NetWorkPolicy `policyTypes` definition in the spec documentation so its
clear there are only three options: "Ingress", "Egress", and
"Ingress,Egress".

**Which issue(s) this PR fixes**:
Fixes #69490 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/assign @smarterclayton 
thanks :)

**Review by cmluciano — COMMENTED** [review]
/lgtm

**Comment by cmluciano** [comment]
@mattjmcnaughton Not sure what the deal is with open-api since it looks like you did change it. Can you try a ./hack/update-all.sh again to be sure nothing changes?

**Comment by mattjmcnaughton** [comment]
@cmluciano I believe that this is will be fixed with https://github.com/kubernetes/kubernetes/pull/74012. I will track this issue, rebase, and then tag you when we're ready for review again :)

**Comment by mattjmcnaughton** [comment]
@cmluciano I rebased off master, so I think we should be good to go. Mind taking another look? Thanks!

**Pull request merged**
