### PR TITLE
Fix golint failures of e2e/framework/f*.go

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures of the following files:
- test/e2e/framework/flake_reporting_util.go
- test/e2e/framework/framework.go

Ref: #68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
> Needs approval from an approver in each of these files:
> ...
> test/e2e/network/OWNERS

ping:
@kubernetes/sig-network-pr-reviews

**Comment by oomichi** [comment]
@neolit123 Thanks for pinging the corresponding team :-)

@kubernetes/sig-network-pr-reviews

The change of test/e2e/network/networking_perf.go is for passing a golint failure which requires the returning order of error should be last in the returning values.

**Review by neolit123 — COMMENTED** [review]
thanks!
/lgtm
/approve
/priority backlog

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
