### PR TITLE
Return namespace not found error

### LINKED ISSUE #15542: Kubectl get in a namespace that doesn't exist gives an unclear error
For example, 
kubectl get pods counter --namespace=notexist 

The output is:
Error from server: pods "counter" not found

And also kubectl delete has the same problem.

### PR DESCRIPTION
**Pull request by feihujiang**
Fix #15542

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I am not a huge fan of this approach.  I think it may also cause problems when you use policy.  

@deads2k - can you comment?

**Comment by deads2k** [comment]
> I am not a huge fan of this approach. I think it may also cause problems when you use policy.
> 
> @deads2k - can you comment?

I don't think this would leak information.  By the time this code runs, the user has already been authorized to make the request in this particular namespace, so telling him that the namespace doesn't exist isn't leaking any additional information.

**Comment by deads2k** [comment]
> I am not a huge fan of this approach. I think it may also cause problems when you use policy.

This approach doesn't look quite right.  I think you should be looking for a particular kind of error message as opposed to any error.

**Comment by feihujiang** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/errors/etcd/etcd.go#L28 is the particular kind of error message, which is invoked by https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L334, but this is the specific implementation. We could use errors.IsNotFound() function to check whether this is a particular kind of error message .

**Comment by feihujiang** [comment]
The problem I met is how could I verify namespace exists or not. Could you give me some advice please? thanks!

**Comment by derekwaynecarr** [comment]
@feihujiang - so traditionally, we validate existence of a namespace for mutating operations in admission control.  verifying that a namespace existed for subresources on a GET was never a huge priority because the requested object to be fetched already doesn't exist.  

see: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/namespace/lifecycle/admission.go#L81 

i originally had authored something like this when first adding the ```Namespace``` resource and was scolded that constraint checks like this need to be outside of the /apiserver core package handling.  this was why admission control actually came into existence.

for this scenario, I don't think its a poor user experience for the current behavior to tell the user the object they are looking doesn't exist.  if anything was done here, I would say it should be in the client, but even then, I am not sure its worth it.

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra @smarterclayton

**Comment by lavalamp** [comment]
Wouldn't admission control be the ideal place for this check?

**Comment by derekwaynecarr** [comment]
@lavalamp - it would be if we extend admission control to be called on normal GET/LIST, and I had not thought through all the bad things that could or could not be done.

**Comment by liggitt** [comment]
> I am not sure its worth it

+1. This seems expensive to provide a slightly better NotFound error

**Comment by smarterclayton** [comment]
+1

On Oct 13, 2015, at 5:49 PM, Jordan Liggitt <notifications@github.com>
wrote:

I am not sure its worth it

+1. This seems expensive to provide a slightly better NotFound error

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15543#issuecomment-147863850>
.

**Comment by lavalamp** [comment]
Sounds like the verdict on this is no. @feihujiang thanks for the attempt :)

> The problem I met is how could I verify namespace exists or not. Could you give me some advice please? 

You should be able to GET `/api/v1/namespaces/foo` to see if foo exists or not.

**Pull request closed without merging**
