### PR TITLE
staticcheck:test/integration/auth/

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref https://github.com/kubernetes/kubernetes/issues/81657

**Special notes for your reviewer**:

```
test/integration/auth/auth_test.go:463:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:544:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:613:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:665:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:708:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:772:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:797:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:823:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:848:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:929:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:1027:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:1112:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:1176:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/auth_test.go:1226:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/bootstraptoken_test.go:163:4: should check returned error before deferring resp.Body.Close() (SA5001)
test/integration/auth/node_test.go:661:6: func crdFromManifest is unused (U1000)
test/integration/auth/rbac_test.go:81:6: func crdClientsetForToken is unused (U1000)
test/integration/auth/rbac_test.go:725:19: this value of err is never used (SA4006)
test/integration/auth/rbac_test.go:739:24: this value of err is never used (SA4006)
```

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by SataQiu — COMMENTED** [review]
Thanks @tanjunchen 
/approve

**Pull request merged**
