### PR TITLE
make request logs greppable

### PR DESCRIPTION
**Pull request by lavalamp**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Makes apiserver request logs greppable

```release-note
All apiservers log request lines in a more greppable format.
```

### CODE REVIEW

**Comment by deads2k** [comment]
Why did you end up grepping here instead of using an audit log?  Same information is present, so 


/lgtm

**Comment by lavalamp** [comment]
> Why did you end up grepping here instead of using an audit log? Same information is present, so

That's what I said, too (https://github.com/kubernetes/enhancements/pull/1367#discussion_r366084934), and yet here we are...

**Pull request merged**
