### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by HeavenTonight**
Signed-off-by: guiyong.ou <guiyong.ou@daocloud.io>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
code cleanup
#### Which issue(s) this PR fixes:

Fixes #none

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by marosset — APPROVED** [review]

**Comment by oomichi** [comment]
Is it possible to provide some guideline link URL to verify this change?
The CI kicks gofmt as a linter, and that didn’t detect those points.

/cc @oomichi

**Comment by furkatgofurov7** [comment]
Hi @HeavenTonight!

K8s 1.27 Bug Triage Shadow here. FYI, with Code Freeze approaching next week on March 15th, if you would like this PR to be part of the v1.27 release, please make sure it goes in before above mentioned date. Post Code Freeze, we will only be able to accept Release Blockers and Critical issues. Thank you!

**Comment by dims** [comment]
I am not sure which linter was supposed to catch this. but it's not fair to hold this up as we have code freeze in a few days. let's get this in.

next time @HeavenTonight please help with with a lot more info in the PR body, especially around how you found these.

if we don't verify these using a linter, things like this will just keep getting in.

/approve
/lgtm

**Pull request merged**
