### PR TITLE
Revert #99378

### LINKED ISSUE #103727: Revert #99378, StatefulSet autodelete API changes
Tracking bug for the revert so the discussion doesn't get buried in a merged PR.

See discussion on #99378. Root problem is that #99728, the implementation for the API changes, was not able to be merged.

/assign @mattcary 

/cc @palnabarun 
/cc @liggitt 
/cc @kikisdeliveryservice 
/cc @smarterclayton 
/cc @kow3ns

### PR DESCRIPTION
**Pull request by mattcary**
/kind bug

Fixes #103727

#### Does this PR introduce a user-facing change?

```release-note
Revert addition of Add PersistentVolumeClaimDeletePoilcy to StatefulSet API.
```

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Original PR for ref: https://github.com/kubernetes/kubernetes/pull/99378

**Comment by lavalamp** [comment]
I don't have time to review, but here is an

/approve

since I assume this is blocking the release.

**Comment by kikisdeliveryservice** [comment]
Hi all, can we please get final reviews on this?

**Pull request merged**
