### PR TITLE
Automated cherry pick of #14328 upstream release 1.1

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry picking new flocker volume plugin to 1.1 release.

CC @thockin @agonzalezro @mattbates

### CODE REVIEW

**Comment by saad-ali** [comment]
Original PR #14328 for reference.

@agonzalezro as the author of the original PR, can you confirm that you're okay with these commits being contributed to Google for the Kubernetes 1.1 release.

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by agonzalezro** [comment]
I am perfectly fine with it being cherry picking for the 1.1. Thank you very much for your help and support! :)

**Comment by ArtfulCoder** [comment]
@k8s-bot test this please

**Comment by agonzalezro** [comment]
The "Shippable" error doesn't look related with my code, does this need a rebase or just a retry? About the CLA, not pretty sure why it's failing now.

**Comment by a-robinson** [comment]
Kicking shippable. The CLA can be manually updated since you're happy with this being cherry-picked

**Comment by agonzalezro** [comment]
It seems like "Shippable" is hanging. Or is it normal that after 2h didn't move from that step?

**Comment by a-robinson** [comment]
Yes, the shippable issue is unrelated. I'll follow up on that separately

**Pull request merged**
