### PR TITLE
[sig-testing] refactor KubeletSeparateDiskGC nodefeature

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR reflects the comment https://github.com/kubernetes/kubernetes/pull/125417#discussion_r1680712939

I followed the same format here:

https://github.com/kubernetes/kubernetes/blob/8026820562a7d2e552585f3e4d35c9e882f6961e/test/e2e/nodefeature/nodefeature.go#L92-L93

#### Which issue(s) this PR fixes:

Fixes N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://kep.k8s.io/4191
```

### CODE REVIEW

**Comment by bitoku** [comment]
@pohly Can you PTAL?

**Review by Octopusjust — COMMENTED** [review]
/ok-to-test

**Comment by kwilczynski** [comment]
@bitoku, looks very nice!

Can we also put ProcMountType into the proper place (it's not properly sorted now), while we are at it? :smile: 

/cc @sohankunkerkar @haircommander

**Comment by haircommander** [comment]
LGTM

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
thanks @pohly !

**Pull request merged**
