### PR TITLE
test: Add additional test output to checkConfigMetrics

### PR DESCRIPTION
**Pull request by smarterclayton**
The current output is hard to debug

/kind bug

```release-note
NONE
```
```docs

```

/hold

Just debugging so far

### CODE REVIEW

**Review by matthyx — APPROVED** [review]
/lgtm

**Comment by smarterclayton** [comment]
In https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103961/pull-kubernetes-node-kubelet-serial/1420384717345132544/

`E2eNode Suite: [sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive] update Node.Spec.ConfigSource: state transitions: status and events should match expectations`

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/dynamic_kubelet_config_test.go:83
Timed out after 60.001s.
Expected
    <*errors.errorString | 0xc0017d0600>: {
        s: "checkConfigMetrics: case: reset via nil config source\nexpect:kubelet_node_config_active: kubelet_node_config_active{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} 1 @ 0\nkubelet_node_config_assigned: kubelet_node_config_assigned{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} 1 @ 0\nkubelet_node_config_error: kubelet_node_config_error 0 @ 0\nkubelet_node_config_last_known_good: kubelet_node_config_last_known_good{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} 1 @ 0\n\ngot:\n",
    }
to be nil
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/dynamic_kubelet_config_test.go:1193
```

Searching through the dumped "/metrics" content the value `kubelet_node_config_active` never shows up, so pretty confident the metrics are disabled and this is a bug in the impl.

**Comment by matthyx** [comment]
@smarterclayton do you still need this PR open?

**Comment by ehashman** [comment]
I think this can be closed, it was prompted by the disappearing dynamickubeletconfig metrics which we've now worked around.

/close

**Pull request closed without merging**
