### PR TITLE
Wait for GPUs even for AWS kubetest2 ec2 harness

### PR DESCRIPTION
**Pull request by dims**
- skip control plane nodes when looking for GPUs
- fail fast, don't skip when we don't find GPUs
- wait for GPUs for AWS where daemonset is created by the kubetest2-ec2 harness

#### What type of PR is this?
/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Do we know why it flaked even with this PR?

Thanks again for working on both of these jobs dims 🙏

**Comment by dims** [comment]
@BenTheElder `e2epod.GetPodLogs` flaked this time, i want to see how it fares in CI and hence skipped the test.

**Pull request merged**
