### PR TITLE
Restore pre-1.10 openstack instance naming behavior

### PR DESCRIPTION
**Pull request by liggitt**
As noted in https://github.com/kubernetes/kubernetes/pull/61890#issuecomment-377282182 and https://github.com/kubernetes/kubernetes/issues/62295#issuecomment-389374492, the 1.10 changes to the openstack cloud provider node name computation (in #58502, #61000, and #61890) broke existing deployments that provisioned instances with credentials matching their instance names. It also did not account for version skewed kubelets, which can run 1.8 and 1.9 versions against a 1.10 master, and still register based on instance name.

This PR reverts the incompatible changes to restore pre-1.10 behavior.

Further improvements to handle instances with names that cannot be used as node names are tracked in https://github.com/kubernetes/kubernetes/issues/62295

/assign @dims
/sig openstack
/kind bug

```release-note
Restores the pre-1.10 behavior of the openstack cloud provider which uses the instance name as the Kubernetes Node name. This requires instances be named with RFC-1123 compatible names.
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-openstack-pr-reviews

**Comment by dims** [comment]
/hold

i'd like to check on alternative(s) today

**Comment by liggitt** [comment]
> i'd like to check on alternative(s) today

Do you have specific ideas you can share? 

The window for 1.10.3 is rapidly closing (must be merged to release-1.10 by EOD tomorrow). Given the current state, I think we should prioritize fixing the compatibility break in 1.10.x. 

Especially given the skewed kubelet requirement, it seems like attempting to support both old and new approaches simultaneously and compatibly will be larger/more complex, and will almost certainly miss 1.10.3.

**Comment by dims** [comment]
@liggitt looking to see if it could be configurable - "name" / "hostname" / "uuid".

**Comment by dims** [comment]
/hold cancel

May be it's better to go back to the drawing board than try to rush more changes.

**Comment by dims** [comment]
@FengyunPan2 @dixudx @NickrenREN please take a look.

/approve

**Comment by dixudx** [comment]
> broke existing deployments that provisioned instances with credentials matching their instance names. It also did not account for version skewed kubelets, which can run 1.8 and 1.9 versions against a 1.10 master, and still register based on instance name.

This is painful when back porting older versions. But we have to go through this.

Seems it's better to roll back to that older flawed version unless we can find a new backwards compatible way.

/lgtm

**Pull request merged**
