### PR TITLE
Demote Shell.*services e2e test as it cannot be run in parallel yet

### LINKED ISSUE #10127: Flaky e2e: Shell should pass tests for services.sh (Failed 3 times in the last 30 runs. Stability: 90 %)
Master issue is #9312 

Recent failures include:

====

waiting for service3 at 10.0.193.5:80
wget: download timed out
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
testing service3 VIP from container failed
namespaces/services-test-701

===

waiting for service3 at 10.0.110.153:80
Test 7: Bring up another service, make sure it does not re-use IPs.
Starting service 'services-test-15187/service4' on port 80 with 3 replicas
error: could not read an encoded object from STDIN: unable to connect to a server to handle "replicationcontrollers": couldn't read version from server: Get https://173.255.114.153/version: dial tcp 173.255.114.153:443: connection refused

error: no objects passed to create
error: couldn't read version from server: Get https://173.255.114.153/version: dial tcp 173.255.114.153:443: connection refused

====

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10127

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@rjnagal oncall FYI.  Until this merges, all automatic per-PR Jenkins e2e test runs will fail.

**Comment by quinton-hoole** [comment]
@thockin @bgrant0607 or any other early birds to LGTM and merge this fairly urgently please.  It blocks all other merges, as it prevents e2e tests from passing.

**Comment by thockin** [comment]
merging p0

**Comment by wojtek-t** [comment]
@quinton-hoole - thanks for fixing it (and sorry for breaking)

**Pull request merged**
