### PR TITLE
Remove direct references to prometheus from transformation_testcase.go

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

**What type of PR is this?**
 /kind cleanup
/kind feature
**What this PR does / why we need it**:
Remove direct references to prometheus.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
please run `./hack/update-bazel.sh` and include the changes as part of your commit.

**Comment by yuxiaobo96** [comment]
/cc @neolit123 

I have already tested it.
Please help me add the `/ok-to-test` labels.

**Comment by yuxiaobo96** [comment]
/assign @neolit123 

If there is no problem with this pr, please help me approve.
THX.

**Comment by neolit123** [comment]
@yuxiaobo96 
it needs approval for the /test folder.
/assign @oomichi 
PTAL

i think the `legacyregistry` name was approved by sig-apimachinery, who are owners of component-base.

**Comment by oomichi** [comment]
Thanks for doing this.

/approve

**Comment by yuxiaobo96** [comment]
Thank you all.
:)

**Pull request merged**
