### PR TITLE
Fix deadlock in watch cache

### PR DESCRIPTION
**Pull request by wojtek-t**
@bprashanth - this was taken from #20695 (I didn't want to commit that one, because I don't understand the second part of that PR)

### CODE REVIEW

**Comment by wojtek-t** [comment]
Ref #20652

**Comment by thockin** [comment]
Given how bad the PR builder is you might manually push this one

**Comment by wojtek-t** [comment]
@thockin - yes, will do as soon as it will be green.

**Comment by lavalamp** [comment]
Ouch, LGTM

**Comment by lavalamp** [comment]
I am build cop, manually merging.

**Comment by wojtek-t** [comment]
@lavalamp - thanks!

**Comment by justinsb** [comment]
Awesome find.  Anecdotally things are _much_ better now.

Is the a 'go vet' like tool that could have found this for us?  It feels like there's a algorithmic rule here that Locks should always be followed by a defer Unlock, unless the intermediate statements are part of a small whitelisted set of operations (and that whitelist need not be exhaustive, if we had a way to mark false-positives).

**Comment by smarterclayton** [comment]
Agree with Justin - this is right up there with error shadowing as "guaranteed to hurt you"

**Comment by bprashanth** [comment]
> Is there a 'go vet' like tool that could have found this for us? It feels like there's a algorithmic rule here that Locks should always be followed by a defer Unlock, unless the intermediate statements are part of a small whitelisted set of operations (and that whitelist need not be exhaustive, if we had a way to mark false-positives).

the patter is what you'd adopt for cvars:
```
lock
for !condition {
    condLock()
}
unlock
```

And in this case it was ok to hold the lock till the end of the function (it was a rlock anyway), but often one doesn't want a defer (why use a cvar otherwise?).

**Comment by smarterclayton** [comment]
We use defer because otherwise we don't unlock on panic.

**Comment by lavalamp** [comment]
Yeah, one almost always wants a defer (because panics), and one almost always wants it immediately after the lock statement (somewhat protecting against idiots changing your code).

Actually I feel like if you don't want to hold the lock to the end of the function, then you need to make new functions until you do.

**Comment by smarterclayton** [comment]
I agree with that.  I haven't hit a case yet where it wouldn't make the
code clearer.

**Comment by wojtek-t** [comment]
Yes - I also agree with that.

**Pull request merged**
