### PR TITLE
remove unnecessary code in client-go test

### PR DESCRIPTION
**Pull request by qianlei90**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

remove unnecessary code in test file

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
Please run `hack/update-bazel.sh`

**Comment by qianlei90** [comment]
> Please run `hack/update-bazel.sh`
> Edit: sorry I didn't see your other pushes.

Thanks for you reply and plz don't mind this. 

BTW I'm a little confused about those tests. They can be passed at sometime but at the other time they are failed.

**Comment by qianlei90** [comment]
Finally, these tests are all passed. Now waiting for a lgtm label. @matthyx

**Review by matthyx — APPROVED** [review]

**Comment by liggitt** [comment]
/assign @caesarxuchao 
if you have a chance

**Pull request merged**
