### PR TITLE
deprecate state field of eventSeries on Event API

### PR DESCRIPTION
**Pull request by yastij**
**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The `series.state` field in the events.k8s.io/v1beta1 Event API is deprecated and will be removed in v1.18
```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for requesting an API review. Before proceeding, please ensure the [prereq checklist](https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#mechanics) has been completed, especially the items related to getting agreement on the change from the area owners, and having an associated KEP.

This appears to be removing the field outright, rather than marking it as deprecated. Was this discussed and agreed to?

**Comment by wojtek-t** [comment]
> This appears to be removing the field outright, rather than marking it as deprecated. Was this discussed and agreed to?

We were discussing with @bgrant0607 and I think the decision was to deprecate.

**Comment by yastij** [comment]
@wojtek-t @liggitt - I’m fine with this being subject to the depreciation policy, even though this was never really used somewhere. cc @bgrant0607

**Comment by yastij** [comment]
@liggitt - Planned for removal in 1.19 as per our deprecation policy

**Comment by wojtek-t** [comment]
/lgtm

@bgrant0607 - can you please approve it?

**Comment by bgrant0607** [comment]
Technically, according to the letter of our deprecation policy, I believe we can't remove the field. We have to wait for the existing API types to be removed.

Practically, I believe events are reported almost entirely through our client library, which obviously didn't use the field, and the field wasn't displayed in kubectl output. The field was added as part of the new event API, but we decided it wasn't useful.

I recommend removing it according to the beta API policy rather than the GA policy.

On the release note: Please be more specific about the field path, API group, etc., and state that the field was newly introduced but unused.

**Comment by liggitt** [comment]
> I recommend removing it according to the beta API policy rather than the GA policy.

That seems reasonable

**Comment by liggitt** [comment]
can you also update the event API design doc (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/events-redesign.md)? the series aspect was a significant part of the design, and it would be helpful to revise that to reflect the current plans

**Comment by liggitt** [comment]
> > I recommend removing it according to the beta API policy rather than the GA policy.
> 
> That seems reasonable

To clarify, which of the following is being proposed:
* dropping the field now in v1 and events.k8s.io/v1beta1 (as the PR currently does)
* announcing as deprecated, and dropping the field now in v1 and events.k8s.io/v1beta1 in a future release
* dropping the field now in v1 and incrementing to events.k8s.io/v1beta2
* ... something else?

**Comment by wojtek-t** [comment]
@bgrant0607 - can you clarify on Jordan`s question above?

**Comment by bgrant0607** [comment]
@liggitt @wojtek-t 

I was expecting "announcing as deprecated, and dropping the field now in v1 and events.k8s.io/v1beta1 in a future release", where the future release was less than a year from now, since the field wasn't really GA and (we believe) isn't used, and I think leaving the field for the remainder of the lifetime of the v1 Event API would do more harm than good.

Note that there is a gap in our deprecation policy for post-GA API evolutions, due to the round-trip requirement, and the lack of official field-level maturity lifecycle:
https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

**Comment by yastij** [comment]
sgtm

**Comment by wojtek-t** [comment]
@yastij - can you please adjust the PR accordingly to what Brian wrote above?

**Comment by yastij** [comment]
@bgrant0607 @wojtek-t - our serialization test is failing as round tripping of v1 to our internal version, this due to the fact that the storage version is v1 (so we cannot drop it from storage version as we need it to round trip v1beta1).

**Comment by bgrant0607** [comment]
@yastij Yes, sorry, I didn't read the text I copied too carefully. I'm fine with deprecate now and remove in a couple releases.

**Comment by yastij** [comment]
@bgrant0607 - less than year would make us deprecate this in 1.18. would you prefer to deprecate this in 1.19 to respect the deprecation policy ?

**Comment by bgrant0607** [comment]
@yastij I'm fine with 1.18.

**Pull request merged**
