### PR TITLE
hack/local-up-cluster.sh: Allow pre-existing etcd cluster, with optional TLS auth, allow kubelet overridable service IP range.

### PR DESCRIPTION
**Pull request by andrewstuart**
A few things this adds:
- Ability to use pre-existing etcd cluster
- Ability to use an etcd cluster secured by client tls by specifying the cert path in environment variables.
- Symlink etcdctl in addition to existing etcd
- Use etcdctl to check etcd availability
- Ability to specify service IP range
- Kubelet bind address now matches  insecure bind address

### CODE REVIEW

**Comment by andrewstuart** [comment]
This should be ready to go now, after correcting some issues passing the pre-commit hooks which I hadn't hooked up yet.

**Comment by andrewstuart** [comment]
@eparis Anything I'm missing here to get this cleared for testing?

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
Ah yes, I remember this patch.

I didn't like the fact that the default now allows re-use. Is that used by any part of the test infrastructure, that needs to be certain they are getting a clean cluster? I wonder if re-use should be gated on an ENV var.

**Comment by andrewstuart** [comment]
@eparis Yeah, good call. I'll add an environment variable to gate usage of existing etcd clusters.

**Comment by eparis** [comment]
Given that we are playing with etcd here and every failure in the unit/integration test is in an /etcd directory I'm going to leave it to you to debug, rather than believe it is a flake/test failure.......

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #27462

**Pull request closed without merging**
