### PR TITLE
Decrese fluentd cpu request

### LINKED ISSUE #47905: Sum of master component CPU requests > 1
This causes one component on master to fail in our standard test clusters. Usually it's NPD:
```
kubectl get daemonset --namespace=kube-system
NAME               DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR                                 AGE
fluentd-gcp-v2.0   4         4         4         4            4           beta.kubernetes.io/fluentd-ds-ready=true      1h
ip-masq-agent      4         4         4         4            4           beta.kubernetes.io/masq-agent-ds-ready=true   1h
npd-v0.4.0         4         3         3         3            3           <none>                                        1h
```

cc @kubernetes/sig-cluster-lifecycle-bugs

### PR DESCRIPTION
**Pull request by gmarek**
Fix #47905

cc @piosz - this should fix your tests.
cc @dchen1107

### CODE REVIEW

**Comment by gmarek** [comment]
Changed to 90m. @crassirostris

**Comment by crassirostris** [comment]
Fine with me if load tests don't start failing

/lgtm

**Comment by piosz** [comment]
Why fluentd? There was a number of issues with fluentd caused by lack of resources. This change affect all fluentd instances including those running on nodes. I'm fine with decreasing the request on master, but please don't do this for every node. It's not obvious how to do it because fluentd is a manifest pod.

 @dchen1107 I think this change should be reverted in 1.7

**Comment by gmarek** [comment]
@mwielgus

**Pull request merged**
