### PR TITLE
custom-resources: add initializer test

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
@kubernetes/kubernetes-build-cops looks like gce tests are down, e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47252/pull-kubernetes-e2e-gce-etcd3/39203/

**Comment by shyamjvs** [comment]
/retest

@sttts All the tests were broken due to a recent update in testinfra image (https://github.com/kubernetes/test-infra/pull/3380)
Reverted it now. (Though the kubemark e2e test would still fail)

**Comment by sttts** [comment]
@deads2k ptal

**Comment by sttts** [comment]
@deads2k lgty?

**Comment by deads2k** [comment]
Initializers don't work in the separate API server?

**Comment by sttts** [comment]
@deads2k what do you mean? They do in apiextensions-apiserver as this test shows.

**Comment by deads2k** [comment]
I was surprised to see the test in cmd/kube-apiserver instead of in staging/src/k8s.io/apiextensions-apiserver

**Comment by sttts** [comment]
It won't work in apiextensions-apiserver because the `admissionregistration` apigroup is in kube, not `k8s.io/apiserver`. Maybe the later would be a better place.

**Comment by deads2k** [comment]
> It won't work in apiextensions-apiserver because the admissionregistration apigroup is in kube, not k8s.io/apiserver. Maybe the later would be a better place.

This needs to be addressed before moving admissionregistration to beta.

@lavalamp @kubernetes/sig-api-machinery-misc

**Comment by sttts** [comment]
`/ok-to-test` o

**Pull request merged**
