### PR TITLE
go1.19: change some atomic.Value to atomic.Bool

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

go 1.19 introduce https://pkg.go.dev/sync/atomic#Bool, with changing some atomic.Value to atomic.Bool make the code self-document and type safe.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by Abirdcfly** [comment]
/assign @deads2k, serathius

for approval

**Comment by Abirdcfly** [comment]
/assign @deads2k, @serathius

for approval (I guess this assign syntax is correct, Let me try)

**Comment by Abirdcfly** [comment]
/assign @deads2k @serathius

for approval (I guess this assign syntax is correct, Let me try)

**Comment by Abirdcfly** [comment]
/assign @liggitt 
for approval.

**Comment by liggitt** [comment]
/assign @deads2k
/unassign

routing to @deads2k to load-balance per https://github.com/kubernetes/kubernetes/pull/112258#issuecomment-1239013433

**Pull request merged**
