### PR TITLE
WIP - Remove unnecessary kubelet binding

### PR DESCRIPTION
**Pull request by liggitt**
this binding was in place for GKE only. speculative removal, will wait for ack from @mikedanese / @cjcullen (though I'd really like to avoid this binding existing on all kube-up 1.6 GCE clusters)

### CODE REVIEW

**Comment by liggitt** [comment]
@mikedanese @cjcullen do new GKE clusters have the node certs they need to make this unnecessary (and old ones have legacy ABAC policy in place still)?

**Comment by liggitt** [comment]
Apparently not. Is there a way we can limit this binding to GKE?

**Comment by mikedanese** [comment]
@liggitt won't this also be required for upgraded GCE clusters?

**Comment by liggitt** [comment]
They should include the legacy ABAC policy

**Comment by cjcullen** [comment]
I'm worried that "Upgrade your nodes or else RBAC will break you" is not a user-friendly introduction to running things the right way.

I'd like to be able to have a 1.6, RBAC-only master still be functional w/ <=1.5 nodes. I haven't been able to think of a better way to do that than to keep around a binding for the "kubelet" user in all the deployments that created a "kubelet" user. Thoughts?

**Comment by liggitt** [comment]
If we can limit it to an upgrade scenario, I'm less bothered. This creates it in all new clusters as well.

**Comment by liggitt** [comment]
And it's more an "upgrade your nodes if you want to drop your old authorizer" which seems less onerous

**Comment by cjcullen** [comment]
Okay I buy that. It'd be nice to be able to expose this binding as a boolean env var in the scripts or something.

**Pull request closed without merging**
