### PR TITLE
remove PodContainerInfo from api/types.go

### PR DESCRIPTION
**Pull request by caesarxuchao**
#8087

@nikhiljindal @krousey @bgrant0607

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, assuming the tests will pass.

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by saad-ali** [comment]
@nikhiljindal @bgrant0607 Can you verify this is v1.0 approved?

**Comment by nikhiljindal** [comment]
Yes. This is part of https://github.com/GoogleCloudPlatform/kubernetes/issues/8087

**Pull request merged**
