### PR TITLE
Use format instead of awk to extract active account/project

### PR DESCRIPTION
**Pull request by fejta**
gcloud changed the format of the output from `active` to `ACTIVE`

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot node e2e test this issue #30009

**Comment by fejta** [comment]
@k8s-bot e2e test this issue #30009

**Comment by spxtr** [comment]
```
$ git grep "gcloud .* | awk"
build/common.sh:    GCLOUD_ACCOUNT=$(gcloud auth list 2>/dev/null | awk '/(active)/ { print $2 }')
build/common.sh:    GCLOUD_PROJECT=$(gcloud config list project | awk '{project = $3} END {print project}')
examples/openshift-origin/README.md:$ export ZONE=$(gcloud compute instances list | grep "${KUBE_GCE_INSTANCE_PREFIX}\-master" | awk '{print $2}' | head -1)
examples/openshift-origin/create.sh:export ZONE=$(gcloud compute instances list | grep "${KUBE_GCE_INSTANCE_PREFIX}\-master" | awk '{print $2}' | head -1)
$ git grep "gcloud .* | grep"
build/common.sh:  if [[ -n $(gcloud auth list --filter-account $account 2>/dev/null | grep "active") ]]; then
examples/openshift-origin/README.md:$ export ZONE=$(gcloud compute instances list | grep "${KUBE_GCE_INSTANCE_PREFIX}\-master" | awk '{print $2}' | head -1)
examples/openshift-origin/README.md:$ echo "sudo cat /srv/kubernetes/server.key; exit;" | gcloud compute ssh ${KUBE_GCE_INSTANCE_PREFIX}-master --zone ${ZONE} | grep -Ex "(^\-.*\-$|^\S+$)" > ${OPENSHIFT_CONFIG}/serviceaccounts.private.key
examples/openshift-origin/create.sh:gcloud_instances=$(gcloud compute instances list | grep "\-master")
examples/openshift-origin/create.sh:export ZONE=$(gcloud compute instances list | grep "${KUBE_GCE_INSTANCE_PREFIX}\-master" | awk '{print $2}' | head -1)
examples/openshift-origin/create.sh:echo "sudo cat /srv/kubernetes/server.key; exit;" | gcloud compute ssh ${KUBE_GCE_INSTANCE_PREFIX}-master --zone ${ZONE} | grep -Ex "(^\-.*\-$|^\S+$)" > ${OPENSHIFT_CONFIG}/serviceaccounts.private.key
examples/storage/vitess/configure.sh:  project=$(gcloud config list project | grep 'project\s*=' | sed -r 's/^.*=\s*(.*)$/\1/')
hack/make-rules/test-e2e-node.sh:  gcloud compute images list --project="${image_project}" | grep "e2e-node"
hack/make-rules/test-e2e-node.sh:         if [[ $(gcloud compute instances list "${instance_prefix}-$i" | grep $i) ]]; then
test/e2e/restart.go://    output=$(gcloud compute instance-groups managed --zone="${ZONE}" get-operation ${op} | grep status)
```

**Comment by lavalamp** [comment]
[build cop merge to unbreak head]

**Comment by fabioy** [comment]
@fejta I think we'll need this for the 1.3 branch as well. Could you create a cherrypick PR as well? Thanks.

**Comment by ixdy** [comment]
Do we care about building on release-1.2? Cause it's similarly broken.

**Pull request merged**
