### PR TITLE
import util.sh and logging.sh since two functions are unbound

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L389-L390

kube::util::wait-for-job
and kube::log::error
are unbound in this context because i hastily didn't test my bash

**Comment by mikedanese** [comment]
cc @madhusudancs

**Comment by madhusudancs** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test. build keeps timing out

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Pull request merged**
