### PR TITLE
Automated cherry pick of #103385: Ensure proper resource creation

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Cherry pick of #103385 on release-1.21.

#103385: Ensure proper resource creation

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
cc @msau42 @mattcary

**Comment by mattcary** [comment]
@ravisantoshgudimetla Can you add the release note as described above, then ping kubernetes/release-managers to get this cherry pick merged?

**Comment by cpanato** [comment]
@mattcary @ravisantoshgudimetla this looks like the kind of a feature, this is fixing any issue/bug? I did not find an issue that explains this code change. 
Can you please clarify? thanks!

**Comment by mattcary** [comment]
/release-note none

Oh, I spaced this is only fixing e2e test. So no release note is needed.

The root pr for this (#103385) explains the motivation---it makes the e2e tests less flakey.

**Comment by mattcary** [comment]
/kind cleanup

(from #103385)

**Comment by cpanato** [comment]
@mattcary this is needed only in 1.21 or do we need to backport this to 1.20 as well?

**Comment by mattcary** [comment]
It's only touching tests, so is safe to backport. It reduces test flakiness, so would be nice to backport all the way to 1.20. However, since 1.20 is going to be falling off the testgrid soon anyway (IIUC), it's not critical.

**Comment by cpanato** [comment]
thanks @mattcary for the clarifications

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
