### PR TITLE
Ensure directory is created for kubelet configuration

### LINKED ISSUE #64887: [Failing test] kubeadm-gce and kubeadm-gce-selfhosting are failing on release-master-blocking suite
## Failing Jobs
* [kubeadm-gce](https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce&show-stale-tests=)
* [kubeadm-gce-selfhosting](https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-selfhosting&show-stale-tests=)

Error Logs

/kind bug
/priority failing-test
/priority critical-urgent
/milestone v1.11
/assign @luxas 
cc @jberkus @tpepper @timothysc 

Possible breaking change https://github.com/kubernetes/kubernetes/pull/64624 as per offline discussions.

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Ensure directory is present before writing the config file.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64887

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Got a green run! - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64889/pull-kubernetes-e2e-kubeadm-gce/12956/

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by dims** [comment]
whoops. thanks @neolit123

**Pull request merged**
