### PR TITLE
Automated cherry pick of #56648 #56726 #57053 upstream release 1.9

### PR DESCRIPTION
**Pull request by shaominchen**
Cherry pick of #56648 #56726 #57053 on release 1.9.

**Release note**:
```
1. Fix session timeout issue in vSphere Cloud Provider.
2. Fix dynamic volume provisioning iussue when VM is removed from inventory.
3. Compare correct file names for volume detach operation.
```

### CODE REVIEW

**Comment by shaominchen** [comment]
@prashima @abrarshivani please review this PR.

**Review by divyenpatel — APPROVED** [review]

**Comment by mbohlool** [comment]
For cherrypick approval: I don't see any test for these PRs. Are they tested somehow? Who will be impacted by this and how?

**Comment by shaominchen** [comment]
@mbohlool Thanks for taking a look. Yes, these PRs are already tested. These PRs fixed those critical issues related to vSphere Cloud Provider (VCP). We need to crossport these PRs so that the fixes are available in Kubernetes 1.9.1 release. Otherwise, VCP customers will still run into those issues.

I'm just following other cherrypick PRs (https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+%22automated+cherry+pick%22+base%3Arelease-1.9). Please let me know if I missed anything in the PR description.

**Comment by mbohlool** [comment]
@shaominchen As I am not familiar with these, I would like the approver of those PRs also approve/lgtm this cherrypick to make sure changes are good for 1.9 branch.

Also please Add a release note. I kicked off tests too.

**Comment by mbohlool** [comment]
@shaominchen no approver looked at this yet. We are very close to the deadline? is it ok if we move these to 1.9.2 so approvers have time to look at it?

**Comment by divyenpatel** [comment]
@mbohlool I have approved this PR. I am listed in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/OWNERS

I can not add lgtm as I am not the kubernetes community member. 

@mbohlool Can you help merging this PR to 1.9 branch?

**Comment by mbohlool** [comment]
@divyenpate just say "/approve" "/lgtm". it should work.

**Comment by mbohlool** [comment]
also @shaominchen please add release notes.

**Comment by mbohlool** [comment]
Approving on behalf of @divyenpatel

**Comment by shaominchen** [comment]
@mbohlool Sorry for the late response. I've updated the release note part. Hope it's not too late.

**Comment by mbohlool** [comment]
@shaominchen we are good. Thanks.

**Pull request merged**
