### PR TITLE
Add logging to scheduler's event handlers

### LINKED ISSUE #87524: Add logging to scheduler's event handlers
This helps debugging scheduler's behavior, currently we don't have logs that indicate when the scheduler first saw a pod or a node. The log level should be v=3.

/sig scheduling
/cc @Huang-Wei @alculquicondor

### PR DESCRIPTION
**Pull request by Ye-Tian-Zero**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add some logging to scheduler's event handlers for debugging scheduler.

**Which issue(s) this PR fixes**:

Fixes #87524 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/priority backlog

**Review by ahg-g — COMMENTED** [review]
sorry I wasn't clear, I think we only need logs for pods and nodes, and only for add/delete.

**Comment by skilxn-go** [comment]
Thanks, fixing.

**Comment by skilxn-go** [comment]
They‘re fixed, sorry for my misunderstanding.

**Pull request merged**
