### PR TITLE
Switch off KUBE_BUILD_CONFORMANCE to diagnose a ci-cross issue

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Looking at job results, there seems to be some flakiness, let's see if
the PR that added the conformance image is the one to blame.

https://prow.k8s.io/?type=periodic&job=ci-kubernetes-cross-build
https://k8s-testgrid.appspot.com/sig-release-misc#cross-build&graph-metrics=test-duration-minutes&width=20

Change-Id: Ic26431a0e262100dec0444279d94277482972b07

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
/lgtm

thanks @dims, I'll start another alpha.1 build once this has merged.

**Comment by cblecker** [comment]
/approve

Looks like this is a new option that was added in https://github.com/kubernetes/kubernetes/pull/69368, so I'm comfortable turning it off.

**Comment by ixdy** [comment]
It looks like the root cause is that both the hyperkube and conformance image Makefiles are trying to run `docker run --rm --privileged multiarch/qemu-user-static:register --reset` at the same time. If they're called sequentially, there should be no issue, but if they're called at the exact same time, they'll race with each other and (at least) one of them will fail.

**Comment by dims** [comment]
ah wow! that's great bit of analysis @ixdy

**Comment by dims** [comment]
@ixdy we could use flock? (example https://www.msully.net/blog/2015/02/25/parallelizing-compiles-without-parallelizing-linking-using-make/ )

**Comment by ixdy** [comment]
`flock` should work, though I'm not sure if that'd cause problems for macOS builds, since I think `flock` is a linux-specific utility.

**Pull request merged**
