### PR TITLE
When calling kubectl.sh, allow error due to API server bouncing

### PR DESCRIPTION
**Pull request by brosner**
This seems to be the simple fix for #12617.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@brosner can you sign the CLA?

@k8s-bot ok to test

**Comment by brosner** [comment]
@roberthbailey working on getting it signed by my company. The company is Eldarion, Inc. for reference.

**Comment by brosner** [comment]
I signed it!

**Comment by roberthbailey** [comment]
I found Eldarion in the list of Corparate CLA signers, but I'm not sure what the correct procedure is to accept your patch. Assigning to @thockin for help. 

(code change lgtm)

**Comment by thockin** [comment]
Confirmed Eldarion is in the corp CLA list.  I'll try a manual override and merge.

**Comment by thockin** [comment]
@k8s-oncall heads up, doing a manual merge

**Pull request merged**
