### PR TITLE
Set timeout for clients created in e2e tests

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #13485 #18281

@quinton-hoole @ixdy @kubernetes/goog-testing 

Not sure if that helps, but it definitely shouldn't break anything.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
I'm afraid this PR is incorrect, but I still don't understand why...

@krousey - any thoughts?

**Comment by wojtek-t** [comment]
I think I understand what is going on here - it seems that our custom RoundTripper implementations doesn't have CancelRequest() method.

@krousey - is there any reasonable way to achieve what I'm trying to achieve here?
IIRC, when @ixdy did it previously (i.e. before your changes to Transport), it fixed the problems of randomly forever-hanging tests.

**Comment by krousey** [comment]
@wojtek-t Not having a CancelRequest is definitely why timeout is not working. However I'm not sure how this worked before because they never had that method.

**Comment by krousey** [comment]
As far as how to enable this, just add a forwarding method to the 3 roundtrippers in pkg/client/transport/roundtrippers.go, and silently drop it if the lower transport can't type assert to it.

**Comment by wojtek-t** [comment]
>
@wojtek-t Not having a CancelRequest is definitely why timeout is not working. However I'm not sure how this worked before because they never had that method.

@krousey 
I think that before your changes: https://github.com/kubernetes/kubernetes/pull/16126 - we were basically using http.Transport everywhere (IIUC without any decorators), and http.Transport has CancelRequest method implemented. Or am I missing something?

>
As far as how to enable this, just add a forwarding method to the 3 roundtrippers in pkg/client/transport/roundtrippers.go, and silently drop it if the lower transport can't type assert to it.

Yeah - but then we can have CanelRequest() method that simply doesn't work in some cases. Do you think is reasonable to have such methods?

**Comment by krousey** [comment]
> Yeah - but then we can have CanelRequest() method that simply doesn't work in some cases. Do you think is reasonable to have such methods?

Given that you can set the Client timeout and have it not work in some cases now, probably. I don't really expect anyone to call CancelRequest directly. If you wanted to maintain the type-correctness, you could do some type explosion like I did for requests in #10656. There I had 2 orthogonal behaviors to properly type out, so you wouldn't have to do something this bad. You could actually just use 2 wrappers with a function member instead of doing the separate types for each round tripper. It's a little bit more work, more correct, harrier code, and I'm not sure it's all that advantageous. I would be happy with either approach.

**Comment by krousey** [comment]
On another note, it's too bad we hide the underlying HTTP objects. I think the Go team saw that composing RoundTrippers like this was problematic, and also client-wide timeouts aren't fine-grained enough, and added a mechanism to have per request timeouts by adding a Cancel channel to them. The even nested it down in to base transport so it wouldn't matter how you layered RoundTrippers. https://golang.org/src/net/http/transport.go?#L566

**Comment by wojtek-t** [comment]
I'm not sure what happened here:

Ran 115 of 206 Specs in 2461.526 seconds
04:10:14 FAIL! -- 115 Passed | 0 Failed | 2 Pending | 89 Skipped 

@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@krousey - PTAL (I'm not sure if we want to do exactly what I did...)

**Comment by krousey** [comment]
Best effort looks fine to me. FWIW Go Team does this in their context library when the type assertion fails: https://github.com/golang/net/blob/master/context/ctxhttp/cancelreq_go14.go

**Comment by wojtek-t** [comment]
@krousey - thanks! (I can change to exactly the same pattern, but not today - just early tomorrow)

**Comment by krousey** [comment]
@wojtek-t What you have is essentially the same, except you log instead of silently ignore. No need to change it.

**Comment by wojtek-t** [comment]
@krousey - not really, because I'm only casting for http.Transport - if there is another implementation that supports CancelRequest, we will not use it. What you suggested is better.
Anyway - I will fix it in few minutes

**Comment by krousey** [comment]
D'oh. I didn't notice. Yea you should definitely cast to an interface because you could have a UserAgent on top of a BearerToken on top of an http.Transport.

**Comment by wojtek-t** [comment]
@krousey - updated PTAL

**Pull request merged**
