### PR TITLE
Add aggregated discovery v2 types

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/assign @jpbetz 
For API review. Thank you.
/triage accepted

**Comment by deads2k** [comment]
once stale is resolved, this lgtm 

ref https://github.com/kubernetes/kubernetes/pull/122883

**Comment by deads2k** [comment]
types match the v2beta1 as expected.  this doesn't serve the new types, but makes them available for compilation to build out client changes and the like.

/lgtm
/approve

**Comment by liggitt** [comment]
/approve 
for "vendor" change

**Pull request merged**
