### PR TITLE
[kube-proxy]: Cleanup KUBE-NODE-PORT chain in filter table.

### LINKED ISSUE #109286: Kube-proxy fails to cleanup properly in IPVS mode
### What happened?

Before switching the `kube-proxy` modes from `IPVS` to `IPTables` it makes sense to cleanup unnecessary `iptables` rules. This can be done using the `--cleanup` command line option of `kube-proxy`. Unfortunately, this does not work anymore since `KUBE-NODE-PORT` was introduced into the `filter` table with https://github.com/kubernetes/kubernetes/commit/4cd1eacbc1f90e60061818d1b4713f78e78de0f9.

We see the following error when trying to cleanup the `iptables` rules after running in `IPVS` mode:
```
I0902 11:59:06.877204      11 flags.go:59] FLAG: --add-dir-header="false"
I0902 11:59:06.877264      11 flags.go:59] FLAG: --alsologtostderr="false"
I0902 11:59:06.877270      11 flags.go:59] FLAG: --bind-address="0.0.0.0"
I0902 11:59:06.877277      11 flags.go:59] FLAG: --bind-address-hard-fail="false"
I0902 11:59:06.877284      11 flags.go:59] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
I0902 11:59:06.877289      11 flags.go:59] FLAG: --cleanup="true"
I0902 11:59:06.877497      11 flags.go:59] FLAG: --cluster-cidr=""
I0902 11:59:06.877550      11 flags.go:59] FLAG: --config="/var/lib/kube-proxy-config/config.yaml"
I0902 11:59:06.877559      11 flags.go:59] FLAG: --config-sync-period="15m0s"
I0902 11:59:06.877567      11 flags.go:59] FLAG: --conntrack-max-per-core="32768"
I0902 11:59:06.877575      11 flags.go:59] FLAG: --conntrack-min="131072"
I0902 11:59:06.877582      11 flags.go:59] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0902 11:59:06.877588      11 flags.go:59] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0902 11:59:06.877598      11 flags.go:59] FLAG: --detect-local-mode=""
I0902 11:59:06.877606      11 flags.go:59] FLAG: --feature-gates=""
I0902 11:59:06.877636      11 flags.go:59] FLAG: --healthz-bind-address="0.0.0.0:10256"
I0902 11:59:06.877644      11 flags.go:59] FLAG: --healthz-port="10256"
I0902 11:59:06.877650      11 flags.go:59] FLAG: --help="false"
I0902 11:59:06.877656      11 flags.go:59] FLAG: --hostname-override=""
I0902 11:59:06.877661      11 flags.go:59] FLAG: --iptables-masquerade-bit="14"
I0902 11:59:06.877671      11 flags.go:59] FLAG: --iptables-min-sync-period="1s"
I0902 11:59:06.877677      11 flags.go:59] FLAG: --iptables-sync-period="30s"
I0902 11:59:06.877684      11 flags.go:59] FLAG: --ipvs-exclude-cidrs="[]"
I0902 11:59:06.877712      11 flags.go:59] FLAG: --ipvs-min-sync-period="0s"
I0902 11:59:06.877718      11 flags.go:59] FLAG: --ipvs-scheduler=""
I0902 11:59:06.877724      11 flags.go:59] FLAG: --ipvs-strict-arp="false"
I0902 11:59:06.877729      11 flags.go:59] FLAG: --ipvs-sync-period="30s"
I0902 11:59:06.877739      11 flags.go:59] FLAG: --ipvs-tcp-timeout="0s"
I0902 11:59:06.877745      11 flags.go:59] FLAG: --ipvs-tcpfin-timeout="0s"
I0902 11:59:06.877751      11 flags.go:59] FLAG: --ipvs-udp-timeout="0s"
I0902 11:59:06.877757      11 flags.go:59] FLAG: --kube-api-burst="10"
I0902 11:59:06.877762      11 flags.go:59] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0902 11:59:06.877787      11 flags.go:59] FLAG: --kube-api-qps="5"
I0902 11:59:06.877801      11 flags.go:59] FLAG: --kubeconfig=""
I0902 11:59:06.877811      11 flags.go:59] FLAG: --log-backtrace-at=":0"
I0902 11:59:06.877820      11 flags.go:59] FLAG: --log-dir=""
I0902 11:59:06.877826      11 flags.go:59] FLAG: --log-file=""
I0902 11:59:06.877831      11 flags.go:59] FLAG: --log-file-max-size="1800"
I0902 11:59:06.877837      11 flags.go:59] FLAG: --log-flush-frequency="5s"
I0902 11:59:06.877842      11 flags.go:59] FLAG: --logtostderr="true"
I0902 11:59:06.877866      11 flags.go:59] FLAG: --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id"
I0902 11:59:06.877882      11 flags.go:59] FLAG: --masquerade-all="false"
I0902 11:59:06.877888      11 flags.go:59] FLAG: --master=""
I0902 11:59:06.877893      11 flags.go:59] FLAG: --metrics-bind-address="127.0.0.1:10249"
I0902 11:59:06.877899      11 flags.go:59] FLAG: --metrics-port="10249"
I0902 11:59:06.877905      11 flags.go:59] FLAG: --nodeport-addresses="[]"
I0902 11:59:06.877912      11 flags.go:59] FLAG: --one-output="false"
I0902 11:59:06.877918      11 flags.go:59] FLAG: --oom-score-adj="-999"
I0902 11:59:06.877946      11 flags.go:59] FLAG: --profiling="false"
I0902 11:59:06.877980      11 flags.go:59] FLAG: --proxy-mode="ipvs"
I0902 11:59:06.878003      11 flags.go:59] FLAG: --proxy-port-range=""
I0902 11:59:06.878125      11 flags.go:59] FLAG: --show-hidden-metrics-for-version=""
I0902 11:59:06.878169      11 flags.go:59] FLAG: --skip-headers="false"
I0902 11:59:06.878255      11 flags.go:59] FLAG: --skip-log-headers="false"
I0902 11:59:06.878298      11 flags.go:59] FLAG: --stderrthreshold="2"
I0902 11:59:06.878337      11 flags.go:59] FLAG: --udp-timeout="250ms"
I0902 11:59:06.878382      11 flags.go:59] FLAG: --v="2"
I0902 11:59:06.878420      11 flags.go:59] FLAG: --version="false"
I0902 11:59:06.878472      11 flags.go:59] FLAG: --vmodule=""
I0902 11:59:06.878509      11 flags.go:59] FLAG: --write-config-to=""
I0902 11:59:06.879938      11 feature_gate.go:243] feature gates: &{map[]}
I0902 11:59:06.880024      11 feature_gate.go:243] feature gates: &{map[]}
E0902 11:59:07.303847      11 proxier.go:830] Error removing ipset KUBE-HEALTH-CHECK-NODE-PORT, error: error destroying set KUBE-HEALTH-CHECK-NODE-PORT, error: exit status 1(ipset v6.38: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
Set cannot be destroyed: it is in use by a kernel component
)
E0902 11:59:07.671837      11 proxier.go:830] Error removing ipset KUBE-HEALTH-CHECK-NODE-PORT, error: error destroying set KUBE-HEALTH-CHECK-NODE-PORT, error: exit status 1(ipset v6.38: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
Set cannot be destroyed: it is in use by a kernel component
)
F0902 11:59:07.671864      11 server.go:489] encountered an error while tearing down rules
```

Essentially, ipset `KUBE-HEALTH-CHECK-NODE-PORT` could not be deleted as it was still referenced by the `KUBE-NODE-PORT` chain in the `filter` table.

### What did you expect to happen?

Cleanup of `kube-proxy` should not throw any error and completely remove the `iptables` rules it created.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start `kube-proxy` with `IPVS` enabled.
2. Run `kube-proxy --cleanup --proxy-mode=IPVS`

(You may add the configuration provided in the "What happened?" section, but it should fail either way.)

### Anything else we need to know?

The issue can be trivially fixed by adding `{utiliptables.TableFilter, KubeNodePortChain},` to `iptablesCleanupChains` in `pkg/proxy/ipvs/proxier.go`.

### Kubernetes version

<details>

```console
$ kubectl version
v1.21.3
v1.22.5
(probably all newer releases)
```

</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux ip-10-255-11-97.eu-central-1.compute.internal 5.10.0-garden-cloud-amd64 #1 SMP Debian 5.10.93-0gardenlinux1 (2022-01-24) x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
n/a
</details>

### Container runtime (CRI) and version (if applicable)

<details>
n/a
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n/a
</details>

### PR DESCRIPTION
**Pull request by ScheererJ**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:
Cleanup KUBE-NODE-PORT chain in filter table.

When cleaning up iptables rules and ipsets used by kube-proxy in IPVS mode
iptables chain KUBE-NODE-PORT needs to be deleted before ipset
KUBE-HEALTH-CHECK-NODE-PORT can be removed. Therefore, deletion of
iptables chain KUBE-NODE-PORT is added in this change.

#### Which issue(s) this PR fixes:

Fixes #109286

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/kind bug
/retest
/assign @andrewsykim @uablrek 

I don't know if we have already unit tests for this

**Comment by ScheererJ** [comment]
@aojea It is fairly easy to reproduce #109286. I was able to fix it for me with a local build of `kube-proxy` with this additional line. Not sure if this is enough in terms of testing.
There is `TestCleanupLeftovers`, but it will likely not catch this bug as it seems to use mocks instead of real iptables/ipsets.
Please let me know in case I should do anything in addition.

**Review by uablrek — APPROVED** [review]

**Comment by uablrek** [comment]
> as it seems to use mocks instead of real iptables/ipsets.

I would agree. IMHO to unit-test more or less direct actions to the OS is of little value.

**Comment by aojea** [comment]
@saschagrunert what is the rule for merging in this window?
does this bug qualifies or do we have to wait for 1.25 to open?

**Comment by saschagrunert** [comment]
> @saschagrunert what is the rule for merging in this window? does this bug qualifies or do we have to wait for 1.25 to open?

Is this a bug which would be backported to 1.24? If so, then I recommend to put it into the 1.24 milestone.

**Comment by aojea** [comment]
> Is this a bug which would be backported to 1.24? If so, then I recommend to put it into the 1.24 milestone

/assign @thockin

**Comment by uablrek** [comment]
A bug yes, but is only affects those who uninstall kube-proxy=ipvs, so it is not urgent IMHO. And a manual work-around is to delete the chain after `kube-proxy --cleanup`.

**Comment by ialidzhikov** [comment]
+1 for including this PR in 1.24 and backporting to 1.23, 1.22 and 1.21.

**Pull request merged**
