### PR TITLE
api: run hack/update-api-spec.sh

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
/kind cleanup

Fixes the verify job failing on master-blocking: https://testgrid.k8s.io/sig-release-master-blocking#verify-master

Runs hack/update-api-spec.sh

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/assign @liggitt @dims

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve
/milestone v1.29
/hold for @kubernetes/release-managers visibility

this is also required for the release-1.29 branch to pass validation since this API is no longer served in 1.29 either

**Comment by liggitt** [comment]
(normally this would have surfaced at the first beta tag, since that's when APIs no longer served in a release shut off, but we skipped the beta tag for 1.29)

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve
cc @kubernetes/release-team-leads for awareness

**Comment by Priyankasaggu11929** [comment]
/lgtm

(from 1.29 Release Team)

**Pull request merged**
