### PR TITLE
WIP: Add outbound rules for Azure standard loadbalancer

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

With standard load balancer, the outbound connectivity is different from basic LB because of its “secure by default” feature. e.g. with Virtual Machines, 

| **Scenario**                    | **Outbound   connectivity** |
| ------------------------------- | --------------------------- |
| VM   standalone                 | True                        |
| VM   under Internal LB backends | False                       |
| VM   under Public LB backends   | True                        |

While with VMSS, the scenarios are more complicated, 

| **VMSS   model**                  | **Instances   BackendAddressPools**           | **Outbound   connectivity** |
| --------------------------------- | --------------------------------------------- | --------------------------- |
| VMSS   standalone                 | None                                          | True                        |
| VMSS   under Internal LB backends | Same   with VMSS                              | False                       |
| VMSS   under Internal LB backends | None   (means the instance is from old model) | False                       |
| VMSS   under Public LB backends   | Same   with VMSS                              | True                        |
| VMSS under Public LB backends     | None (means the instance is from old model)   | False                       |

With VMSS, most cases are in same behavior with VMs, except the last one. For the last scenario, the instance is not member of any LoadBalancers, but it’s lost outbound connectivity.

Since scaling and upgrading are common in Kubernetes clusters, this PR fixes the outbound connectivity issues by adding outbound rules for the standard load balancer (with option `enableOutboundConnection`, true by default).

It also adds a few options to customize the behavior of outbound rule, e.g. `allocatedOutboundPorts`,` idleTimeoutInMinutes`, and `enableTcpReset`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

References:

* https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-rules-overview
* https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-overview#securebydefault

**Does this PR introduce a user-facing change?**:

```release-note
enableOutboundConnection options is added to enable outbound rules for Azure standard loadbalancer. This is required for node's external connectivity. allocatedOutboundPorts, idleTimeoutInMinutes, and enableTcpReset are also supported to set up the behavior of outbound rule.
```

/kind bug
/sig azure
/priority critical-urgent
/assign @khenidak @brendandburns @andyzhangx

### CODE REVIEW

**Comment by khenidak** [comment]
as we discussed offline. The cloud provider should not create the outbound rule (even if it does not exist). The cluster bootstrap operation should take care of that.. This enables users to choose how they want to configure egress path.

@jackfrancis @ritazh

**Comment by feiskyer** [comment]
> as we discussed offline. The cloud provider should not create the outbound rule (even if it does not exist). The cluster bootstrap operation should take care of that.. This enables users to choose how they want to configure egress path.

Exactly. This should be the job of provisioning tools (e.g. aks-engine).

**Comment by djsly** [comment]
@feiskyer  / @khenidak , I looked in aks-engine and couldn't find the place where the outboundRules are defined. Could you point me in the right location where the outbound was configured for the internal Azure provisioning tool. 

thanks!

**Comment by feiskyer** [comment]
@djsly Sorry for confusing, aks-engine is not using for outbound rules yet. It defines a LoadBalancer service in kube-system to workaround the issue.

> Sku of Load Balancer and Public IP. Candidate values are: basic and standard. If not set, it will be default to basic. Requires Kubernetes 1.11 or newer. NOTE: VMs behind ILB standard SKU will not be able to access the internet without an ELB configured with at least one frontend IP. We have created an external loadbalancer service in the kube-system namespace as a workaround to this issue, as described in the Outbound NAT for internal Standard Load Balancer scenarios doc

See https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md.

**Comment by djsly** [comment]
Thanks @feiskyer , I did in the find that quote.  I will do some tests and open an aks-engine issue if I find that setting the outboundRule OR setting a default publicIP frontend doesn't resolve the use case when Nodes gets added to an existing AS (e.g. cluster expansion) 

So far, we have discovered the following

when using SLB
1) we create an AS with 10 VM, they all get a outbound IP defined by the AS outbound IP.
2) we install kubelet, kubelet starts registering to the ARM API using the public IP (outbound IP)
3) Eventually all nodes are registered in k8s. 
4) A user creates a Service of Type LoadBalancer, the outboundIP if the nodes changes to the frontEnd IP of that LoadBalancer service.
5) Deallocate a VM, the node disappear from the backendpool and become NotReady. It doesn't have an outboundIP defined anymore
6) The VM is started again. The kubelet service gets stuck trying to talk to the ARM API
```
.222271    2413 azure_auth.go:59] azure: using managed identity extension to retrieve access token
.222303    2413 azure.go:219] Azure cloudprovider (read ops) using rate limit config: QPS=25, bucket=200
.222370    2413 azure.go:223] Azure cloudprovider (write ops) using rate limit config: QPS=10, bucket=100
.222483    2413 azure.go:280] Azure cloudprovider using retry backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
```
7) eventually (after 10mins), the kubelet registers again...
```
70    2413 azure.go:223] Azure cloudprovider (write ops) using rate limit config: QPS=10, bucket=100
.222483    2413 azure.go:280] Azure cloudprovider using retry backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
.610218    2413 azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: storage.AccountsClient#ListByResourceGroup: Failure sending request: StatusCode=0 -- Original Err
.610372    2413 server.go:526] Successfully initialized cloud provider: "azure" from the config file: "/etc/kubernetes/azure.json"
.610414    2413 server.go:772] cloud provider determined current node name to be kn-es-11
.661299    2413 bootstrap.go:52] Kubeconfig /var/lib/kubelet/kubeconfig exists and is valid, skipping bootstrap
```
8) after that, the Kube-Controller-Manager, adds the node back to the SLB backendpool. 


Now, if I recall properly, we have the exact same problem when we add new nodes to the cluster, EXCEPT that the node never register even after 10mins. I will have to double check to make sure this is true. Maybe we also have the 10mins delay and I wasn't patient enough. 

Would you know why there is a 10mins delay ?

**Comment by djsly** [comment]
After the 10 mins delay, I see that one particular API call timesout with an IO error

```
azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: storage.AccountsClient#ListByResourceGroup: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/78939fc9-b2b2-455d-bb14-b807142604fd/resourceGroups/i2t/providers/Microsoft.Storage/storageAccounts?api-version=2017-10-01:  dial tcp 52.232.180.115:443: i/o timeout
```
right after that timeout, the azure cloud provide continue and registers properly. 

I'm running `v1.11.5`

**Comment by djsly** [comment]
Thanks @feiskyer , I created some issues in 
https://github.com/kubernetes/cloud-provider-azure

**Pull request closed without merging**
