### PR TITLE
Remove redis-proxy example

### PR DESCRIPTION
**Pull request by klausenbusk**
The docker image is nowhere to be found, so lets remove it.
There have been a request for the Dockerfile here [1], but nobody
seems to care.

[1] https://github.com/kubernetes/kubernetes/issues/4914#issuecomment-77209779
----
**What this PR does / why we need it**:
This PR remove a k8s manifest which use a image which source is nowhere to be found.

```release-note
Remove redis-proxy.yaml sample, as the image is nowhere to be found.
```

### CODE REVIEW

**Comment by stevenaldinger** [comment]
I was really confused by that file and the lack of mentioning it in the README. Is the proxy concept necessary or can we actually just delete it and create a service that talks directly to the redis servers?

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by klausenbusk** [comment]
@k8s-bot unit test this

**Comment by klausenbusk** [comment]
> Is the proxy concept necessary or can we actually just delete it and create a service that talks directly to the redis servers?

That depends. Dummy clients (without sentinel support) would require a proxy, but smarter Redis clients wouldn't.
https://github.com/enriclluelles/redis-sentinel-proxy could be used as a proxy, with a slight code change (resolve of the sentinel addr is currently only done at startup, which would cause problem if the sentinel service is reconfigured).

**Comment by klausenbusk** [comment]
@k8s-bot unit test this

**Comment by klausenbusk** [comment]
@k8s-bot unit test this

**Comment by klausenbusk** [comment]
@thockin all CI lights are green. It required some tweaking of the tests to get CI to pass.

**Pull request merged**
