### PR TITLE
feat(client-go): Update dependencies to v0.29.0

### PR DESCRIPTION
**Pull request by ahsan-n**
Added dependencies w.r.t to v0.29.0 to support k8 v1.29.0 in client-go

### CODE REVIEW

**Comment by aojea** [comment]
/close

This does not work this way, staging repos are symlinks in the vendor folder

**Comment by ahsan-n** [comment]
@aojea thanks for the review and time.
can you help me understand more? that will help me create the correct PR for this and in future too :)

**Comment by aojea** [comment]
these are special repos https://github.com/kubernetes/kubernetes/blob/master/staging/README.md with some special characteristics, definitely not something for new contributors, there are better places for new contributors to try to help 
Thanks for the effort

**Pull request closed without merging**
