### PR TITLE
[WIP] apiserver: add test to verify CORS with multiple origins

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
- Document the current behavior of CORS with multiple origins in the `Origin` header
- Fix the CORS logic, if necessary

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
Bringing the conversation here (from https://github.com/kubernetes/kubernetes/pull/112809#discussion_r1030677747)

> is it accurate that matching one origin in a multi-origin request means we should allow the whole chain? I'm not familiar enough with how multi-origin requests work to know if this is right or wrong, but it seems like this would open the door to an allowed origin of https://good.example.com permitting a multi-origin chain of https://good.example.com https://bad.example.com


After diffing a bit, this is what the RFC says about multiple origins in the Origin header

> In some cases, a number of origins contribute to causing the user
agents to issue an HTTP request. In those cases, the user agent MAY
list all the origins in the Origin header field. For example, if the
HTTP request was initially issued by one origin but then later
redirected by another origin, the user agent MAY inform the server
that two origins were involved in causing the user agent to issue the
request.

So theoretically it is possible to have multiple origins in the Origin header, then I looked at the CORS spec here:
https://www.w3.org/TR/2020/SPSD-cors-20200602/#access-control-allow-origin-response-header

> Access-Control-Allow-Origin = "Access-Control-Allow-Origin" ":" [origin-list-or-null](http://tools.ietf.org/html/rfc6454#section-7.1) | "*"

> In practice the [origin-list-or-null](http://tools.ietf.org/html/rfc6454#section-7.1) production is more constrained. Rather than allowing a space-separated list of [origins](http://tools.ietf.org/html/rfc6454#section-4), it is either a single [origin](http://tools.ietf.org/html/rfc6454#section-4) or the string "null".

> If the response includes zero or more than one [Access-Control-Allow-Origin](https://www.w3.org/TR/2020/SPSD-cors-20200602/#http-access-control-allow-origin) header values, return fail and terminate this algorithm

I can think of the following options if the Origin header contains multiple origins and CORS is enabled:

A: do nothing:
if the regexp matches, the CORS filter will include the matched origin in the Access-Control-Allow-Origin response header, not all the origins. (I am going to write a test to observe this behavior)
if the regexp does not match - did the user expect a certain origin from the Origin header to match the regular expression (today we use req.Header.Get("Origin") and that returns the first origin.
B: if the Origin header has multiple origins we don't send CORS response headers (we can send a Warning to the client)
C: if the Origin header has multiple origins, we run the regular expression(s) against each origin and send the first matching origin via Access-Control-Allow-Origin
depending on how we want to approach it, I will open a separate PR, this PR seems orthogonal to this issue.

**Comment by tkashem** [comment]
> it seems like this would open the door to an allowed origin of https://good.example.com/ permitting a multi-origin chain of https://good.example.com/ https://bad.example.com/

from the help text for `cors-allowed-origins` , can we stipulate that the given regular expression is expected be defined on matching a single origin
https://github.com/kubernetes/kubernetes/blob/d9c371a2c4fd07b45a3e1c5954ae781d5794ae2b/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go#L196-L198

If that's the case, if we change the CORS filter logic to send the first matching origin in `Access-Control-Allow-Origin` then we can avoid permitting not-allowed origins.

**Comment by liggitt** [comment]
unfortunately, I don't really have familiarity with how CORS headers are specified or used in practice to know what recommendation to make here. Are there contacts in sig-security that have a better grasp on what browsers do that can weigh in on the correctness and functionality of this filter?

**Pull request closed without merging**
