### PR TITLE
[Kubelet] Check if kubelet is running as uid 0

### PR DESCRIPTION
**Pull request by vishh**
Related to #30176

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30466)

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@vishh - is this a breaking change?  should this be an OR check?

@smarterclayton @kubernetes/rh-cluster-infra - any concerns here?

**Comment by vishh** [comment]
@derekwaynecarr 
This could be potentially breaking based on the deployment configuration. AFAIK, we have never documented how to run kubelet with uid != 0. 

As for an `OR` check, what is the alternative?

**Comment by ncdc** [comment]
AFAIK we don't have any deployments where the OpenShift node is run with a nonzero UID

**Comment by smarterclayton** [comment]
Same here, we have always required root (and I think we have a
preflight check that verifies a bunch of things that also require
root).

**Comment by dims** [comment]
@vishh as i mentioned on IRC yesterday, 

Note that kubelet is started inside test-cmd.sh and hence we need to run test-cmd.sh as sudo to get past the test failure
https://github.com/kubernetes/kubernetes/blob/e877a23b4bbe26e6bf8f2cd4cf97cadb7a1cc6d1/hack/make-rules/test-cmd.sh#L179

note that the test-cmd.sh is run inside a docker container (where sudo is not available). 
https://github.com/kubernetes/kubernetes/blob/d4691a76ec706235e8a07033cd5989f458213ba7/hack/jenkins/gotest-dockerized.sh#L49

**Comment by dims** [comment]
Oh, another one, Will this (check for uid==0) work for folks running "hyperkube kubectl" (https://github.com/kubernetes/kubernetes/issues/4869) or minikube(?) ?

**Comment by derekwaynecarr** [comment]
Can you not run as uid=0 with dropped capabilities?

**Comment by vishh** [comment]
> Can you not run as uid=0 with dropped capabilities?

I originally had a section in this PR that validated the permitted and effective caps too. But in reality caps do not typically apply to filesystem access. Hence decided to drop it. If you feel strongly that validating caps is useful, I can add it back in.

**Comment by vishh** [comment]
@derekwaynecarr @dims Integration tests seem to run kubelet not as root. I don't have cycles to fix that. For now, I'm throwing an error and reverting @dims changes! If either of you have spare cycles to clean up the integration test infra to allow kubelet to run as root, kindly post a PR.

This PR will now not cause a regression!

**Comment by dims** [comment]
Looks good to me 👍

**Comment by vishh** [comment]
Thanks for the review! Given that this PR is non-intrusive, I'm marking it as LGTM. I'm happy to address comments in a separate PR. This should at-least fix HEAD.

**Comment by derekwaynecarr** [comment]
LGTM as well (logging the error, but proceeding)

**Pull request merged**
