### PR TITLE
Always enable second etcd for events

### PR DESCRIPTION
**Pull request by wojtek-t**
@lavalamp @davidopp @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by lavalamp** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
@ixdy why is k8s-bot not testing @wojtek-t PR ?

**Comment by ixdy** [comment]
@pwittrock is working on bringing up another PR test instance. I thought it wasn't going to spam every open PR, but I was wrong.

**Pull request merged**
