### PR TITLE
Back porting critical vSphere bug fixes to release 1.3

### PR DESCRIPTION
**Pull request by dagnello**
vSphere cloud provider plugin was first introduced in Kubernetes 1.3.0.  The two PRs listed below contain critical volume attach/detach related fixes.  Without these fixes, vSphere in 1.3 lacks the ability to consistently attach/detach volumes correctly especially in a busy cluster.

These changes only affect the vSphere cloud provider.
- https://github.com/kubernetes/kubernetes/pull/29172
- https://github.com/kubernetes/kubernetes/pull/30535

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31993)

### CODE REVIEW

**Comment by brendandburns** [comment]
This cherry-pick looks fine to me, it's entirely in the vsphere provider and thus pretty low risk.  However, it's also pretty much the time that 1.4 is going to be cut, so it's not 100% clear to me we're going to cut another 1.3.x release.

I'm happy to cherry-pick it into the branch in case we do.

Summoning @smarterclayton and @thockin for their opinions.

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
I don't think we should let the existence of 1.4 stop us from cutting fixes
to 1.3.  We know how long 1.3 took to really stabilize.  That said, cutting
and testing releases requires resources...

@fabioy @davidmcmahon

**Comment by dagnello** [comment]
@brendandburns   ./hack/../hack/verify-boilerplate.sh script has failed, it doesn't seem related to this pr:
Error: No such image or container: kube-build-data-f23692ee99

**Comment by smarterclayton** [comment]
@kubernetes/rh-storage

**Comment by dagnello** [comment]
@brendandburns anything else required for this pr?

**Comment by brendandburns** [comment]
This is ok on my side, given that everyone seems ok w/ it.  Cherry-pick approved.

**Comment by brendandburns** [comment]
@dagnello The key error is:
```
Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/attacher_test.go
Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/attacher.go
```

Can you check and see what the diff is?  My guess is that boilerplate changed between 1.3 and head and you're going to need to manually correct it for what 1.3 expects.  (sorry about that)

--brendan

**Comment by dagnello** [comment]
@brendandburns thank you, pr has been updated

**Comment by brendandburns** [comment]
LGTM.

Thanks

**Pull request merged**
