### PR TITLE
Fix bug cluster-subnet logic

### PR DESCRIPTION
**Pull request by gmarek**
This fixes 1.6-1.7 upgrade tests regression https://github.com/kubernetes/kubernetes/pull/48143#issuecomment-311607056
#47513

### CODE REVIEW

**Comment by dchen1107** [comment]
@gmarek, can you create a cherrypick pr for 1.7. 

cc/ @kubernetes/kubernetes-release-managers @caesarxuchao

**Comment by MaciekPytel** [comment]
Merged as build cop to expedite the fix.

**Pull request merged**
