### PR TITLE
[Do not Merge]: Check CoreDNS version 1.6.7

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
Test PR

**What this PR does / why we need it**:
Checks the latest coredns image 1.6.7

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/hold

### CODE REVIEW

**Comment by rajansandeep** [comment]
@oxddr @mm4tt 
I'd like to test the `pull-kubernetes-e2e-gce-large-performance` against this PR.
Would there be any available time-slot to run the test?

**Comment by mm4tt** [comment]
> janluk Matt Matejczyk
> I'd like to test the `pull-kubernetes-e2e-gce-large-performance` against this PR.
> Would there be any available time-slot to run the test?

Hey @rajansandeep, thanks for reaching out! We'll have a slot for you, just ping me when you're ready (I see some of the presubmits are currently failing).

**Comment by oxddr** [comment]
Once `pull-kubernetes-e2e-gce-large-performance` pass successfully I'll
also book a slot to manually run this PR on 5k cluster.

**Comment by rajansandeep** [comment]
@mm4tt you can schedule a slot now. 
The other tests failed due to flakes (unrelated to this PR)
Thank you!

**Comment by mm4tt** [comment]
The project is available as of now

/test pull-kubernetes-e2e-gce-large-performance

**Comment by mm4tt** [comment]
I took a cursory glance at the [pull-kubernetes-e2e-gce-large-performance](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88342/pull-kubernetes-e2e-gce-large-performance/1230477531426066432/) and it looks like apiserver exploded during the test. 

@oxddr, will you be able to find time to debug it a little more?

**Comment by oxddr** [comment]
Sure, but rather not earlier than Tuesday next week. Is that ok?

**Comment by rajansandeep** [comment]
@oxddr @mm4tt 
can this be run again for a definitive result?

**Comment by oxddr** [comment]
I'd like to have a look at the previous run, before we run it once more. I
was swamped with other work this week, but I'll do my best to have a look
tomorrow morning (CEST time) and give a green or red light for further
testing. How does that sound to you?

**Comment by rajansandeep** [comment]
> I'd like to have a look at the previous run, before we run it once more. I was swamped with other work this week, but I'll do my best to have a look tomorrow morning (CEST time) and give a green or red light for further testing. How does that sound to you?

Sounds good!

**Comment by oxddr** [comment]
The test has timed out, so we don't have Prometheus snapshot (I'm going to
open an issue to fix that) also for some reasons we haven't dumped logs
from the master, which is unfortunate (I'll try to understand why). In the
meantime, feel free to re-run the tests.

**Pull request closed without merging**
