### PR TITLE
Remove ioutil from test

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove ioutil from test

#### Which issue(s) this PR fixes:
Related to https://github.com/kubernetes/kubernetes/issues/100367

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@my-git9 Thank you for your PR! Please, consider adding other files. There are only 55 in the test/ and pkg/ directories:
```
$ git grep io/ioutil ./ |grep '\(^pkg\)\|\(^test\)' | wc -l
55
```

See our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) for more information.

**Comment by my-git9** [comment]
> @my-git9 Thank you for your PR! Please, consider adding other files. There are only 55 in the test/ and pkg/ directories:
> 
> ```
> $ git grep io/ioutil ./ |grep '\(^pkg\)\|\(^test\)' | wc -l
> 55
> ```
> 
> See our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) for more information.

These 55 files actually contain more than 200 modifications, and some of them need to be partially refactored if they are modified. It's difficult for me to do this in a PR, sorry

**Comment by bart0sh** [comment]
You don't have to do all of them. Just do all straightforward and easy ones.

**Comment by my-git9** [comment]
> You don't have to do all of them. Just do all straightforward and easy ones.

OK, I will try it later

**Pull request closed without merging**
