### PR TITLE
Automated cherry pick of #62669 upstream release 1.10

### PR DESCRIPTION
**Pull request by immutableT**
**What this PR does / why we need it**:
Required to enable CloudKMS integration in 1.10.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
Based on description of #62669 this seems to be some initial work, but not enough to actually enable the feature. Is that correct? 1.10.2 is right around the corner and that looks a bit scary for a last minute merge, so I'd rather hold this until 1.10.3 if it's not urgent. Are you ok with that @immutableT ?

**Comment by immutableT** [comment]
@MaciekPytel,
This PR is all that is needed from open source to enable this feature in GKE for 1.10 clusters.
1.10.3 will work.

**Comment by MaciekPytel** [comment]
Approved cherrypick. However, I don't know this code very well and I'm not comfortable lgtm-ing. @mikedanese you reviewed original PR, can you lgtm this?

**Pull request merged**
