### PR TITLE
[Failing Test] Fix GPU Device Driver test in kubelet-serial

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind failing-test
/kind cleanup

#### What this PR does / why we need it:

The GPU device plugin tests have been failing for an extended period of time. I've been unable to find a SHA in which they would pass naturally, or the last time they definitely succeeded.

##### Issue 1, GPU Drivers

Fixing this proved to be quite interesting, as there are a few issues at play. The first is that the GPU drivers no longer successfully install on the COS release that is currently used in test-infra for them. it failed to build the driver as the kernel sha was no longer available.

In the process I discovered that the image we used to build those hasn't been rebuilt since 2017, and the code hasn't been in k/k for about as long. [image source](https://github.com/kubernetes/kubernetes/blob/1e77594958e346e26e4d29fa0d018729fdce1d86/cluster/gce/gci/nvidia-gpus/Dockerfile).

After being unable to make that work on newer cos releases either, I moved on to finding an alternative installation mechanism. I settled on [GoogleCloudPlatform/cos-gpu-installer](https://github.com/GoogleCloudPlatform/cos-gpu-installer). This was chosen over the newer [googlesource/cos_gpu_installer](https://cos.googlesource.com/cos/tools/+/refs/heads/master/src/cmd/cos_gpu_installer/) mostly due to documentation. This can be updated later if any Googler's have a chance to update it.

The way this ends up working is a little bit weird, but is documented a little inline.

##### Issue 2, Installing the driver

The driver wasn't being installed by the PodClient, and due to the lack of scheduler in node_e2e, never managed to run. This fixes that by migrating it to use the PodClient, into the test namespace, and automatically assigns the node under test.

##### Issue 3, Behaviour has changed

In older versions of Kubernetes (at least pre-0.19, it's the earliest this test will run unmodified on), Pods that depended on devices could be restarted after the device plugin had been removed. Currently however, this isn't possible, as during ContainerManager.GetResources(), we attempt to DeviceManager.GetDeviceRunContainerOptions() which fails as there's no cached endpoint information for the plugin type.

This change therefore breaks apart the existing test into two:
- One active test that validates that assignments are maintained across restarts
- One skipped test that validates the behaviour after GPU plugins have been removed, in case we decide that this is a bug that should be fixed in the future.

#### Related Issue

https://github.com/kubernetes/kubernetes/issues/104175

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by endocrimes** [comment]
/assign @dchen1107 @Random-Liu 

(@dims suggested that y'all should take a look at this)

/cc @ehashman bc test fixes

**Comment by dims** [comment]
/approve
/lgtm
/hold for additional reviews

@endocrimes feel free to remove hold when you feel ready

**Comment by endocrimes** [comment]
Leaving this until Monday afternoon (european time) and then I'll remove the hold if nobody gets to it before then

**Comment by dims** [comment]
it's better to leave this running in the weekend and revert on monday :) So recommend removing hold when you wrap up for friday @endocrimes

**Comment by endocrimes** [comment]
/hold cancel

:shipit:

**Comment by bsdnet** [comment]
/lgtm

Eventually, we need to migrate to googlesource ones.

**Pull request merged**
