### PR TITLE
fixed the some typo in eviction_manager

### PR DESCRIPTION
**Pull request by lcfang**
**What this PR does / why we need it**:

fixed some wrong typo in `eviction_manager.go`

### CODE REVIEW

**Comment by ncdc** [comment]
The container gc typo fix is covered by #52638, although it's still waiting for approval.

**Comment by lcfang** [comment]
Hi, @ncdc , thanks for your reminder, I'll cancel the modification which is covered by [#52638](https://github.com/kubernetes/kubernetes/pull/52638).

**Comment by lcfang** [comment]
Hi @ncdc , this PR has staying here for a long time, can you add some label for it? Thanks.

**Pull request merged**
