### PR TITLE
rename ReplicationManager-->ReplicationController according to the TODO

### PR DESCRIPTION
**Pull request by NickrenREN**
rename ReplicationManager-->ReplicationController according to the TODO  on ReplicationManager struct

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot unit test this

**Comment by gyliu513** [comment]
Is this duplicate with #41732 ? @NickrenREN

**Comment by NickrenREN** [comment]
@gyliu513  This is 41732

**Comment by gyliu513** [comment]
Sorry, I mean #41459

**Comment by NickrenREN** [comment]
Thank you. @gyliu513 . I am sorry. Close this

**Pull request closed without merging**
