### PR TITLE
Bump Konnectivity to 0.28.2

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Update Konnectivity from 0.28.0 to 0.28.2.

#### Which issue(s) this PR fixes:

CVE fixes only:
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/530
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/533
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/539

Full delta: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.28.0...v0.28.2

#### Special notes for your reviewer:

Note: this bumps the server and agent images from golang 1.19.13 to 1.20.10

#### Does this PR introduce a user-facing change?
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
This can wait until release-1.29 Thaw.

/sig api-machinery
/sig cloud-provider

**Review by liangyuanpeng — APPROVED** [review]

**Comment by jkh52** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/122557

**Pull request closed without merging**
