### PR TITLE
owners: remove euank from sig-node-reviewers

### PR DESCRIPTION
**Pull request by euank**
I'm already in more specific lists for things related to Container Linux
or rkt and my current role doesn't leave me enough cycles to do
sig-node reviewing justice.

Please do still ping me on any specific items.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dchen1107** [comment]
/lgtm

@euank Thanks all your contributions to sig-node team.

**Comment by euank** [comment]
ping @dchen1107 re approval

**Comment by euank** [comment]
Ping again, still missing approval

**Comment by euank** [comment]
ping...

Honestly, this is ridiculous. The OWNERS file being poorly maintained unquestionably results in a worse experience for Kubernetes contributors.

**Comment by calebamiles** [comment]
This PR seems to simply be stuck. Manually merging.

**Pull request merged**
