### PR TITLE
Wait for Scheduler cache empty.

### LINKED ISSUE #68126: TaintNodeByCondition doesn't isolate individual test cases
While lookint into https://github.com/kubernetes/kubernetes/pull/67864, I spent few minutes looking into this test: https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/taint_test.go#L64

And there is a problem that is relatively easy to reproduce.

The problem is that we are running its test cases one by one. But nothing in the meantime is ensuring that the current state that the test assumes is reflected in scheduler.

In particular the problem that I observed couple time is that:
- we finished one test case
- we call cleanupNodes
- [but we don't ensure that scheduler actually cleaned up this node]
- we start the next test case
- we try to schedule a pod that has some toleration (but shouldn't fit on our node)
- by accident the toleration make it fit on to the previous node
- so scheduler schedules it on the node from previous test case

@kubernetes/sig-scheduling-bugs @k82cn

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68126 

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

Thanks!

**Comment by k82cn** [comment]
@Huang-Wei , sorry about that I include your pr here as it’s related :)

**Comment by Huang-Wei** [comment]
> @Huang-Wei , sorry about that I include your pr as part of this issue here because it’s related :)

No worries, my pr only fixes partial of the problem, let me close that.

**Review by Huang-Wei — APPROVED** [review]
/lgtm

Thanks!

**Comment by Huang-Wei** [comment]
oh, just another idea, instead of waiting for cache cleanup, maybe we can add different index to the node and pod name, so scheduler cache doesn't bother - check my latest commit in #68104.

Here is a running time comparison my dev vm - it basically saves 10 seconds.

|  | 1st run | 2nd run | 3rd run |
| --- | --- | --- | --- |
| solution of waiting cache cleanup | 61.88s | 61.79s | 61.86s |
| solution of using unique node/pod name | 51.83s | 51.76s | 51.79s |

**Comment by Huang-Wei** [comment]
> @Huang-Wei , sorry about that I include your pr as part of this issue here because it’s related :)

Never mind :grinning:

**Pull request merged**
