### PR TITLE
records output for function run_initializer_tests

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

records output for function run_initializer_tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubectl/issues/124

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shiywang** [comment]
great, thanks, some command return non-zero, so we need to find those command and reverse that return value.

**Comment by wackxu** [comment]
@shiywang I have try to find more but got none

**Comment by shiywang** [comment]
cool, will label LGTM if all pass

**Comment by mengqiy** [comment]
`run_initializer_tests` is failing.
This test never runs. It's very likely it's not passing.
You will need to fix it.

**Comment by spiffxp** [comment]
/close
Closing due to inactivity
@wackxu Please /reopen if you plan on working on this

**Pull request closed without merging**
