### PR TITLE
Default extensions/v1beta1 Deployment's RevisionHistoryLimit to MaxInt32

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
#66582:  fix extensions/v1beta1 Deployment .spec.revisionHistoryLimit

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by janetkuo — COMMENTED** [review]
Thanks for the PR. Most parts of it look like a copy of https://github.com/kubernetes/kubernetes/pull/66581. Please follow the updated changes made in that PR.

You'll also need to regenerate API docs. Please also update unit test for cleanupDeployment in sync_test.go

**Comment by islinwb** [comment]
@janetkuo Thanks! I've updated it accordingly.

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/assign @smarterclayton 
for approval

**Pull request merged**
