### PR TITLE
Fix stackdriver logging test

### PR DESCRIPTION
**Pull request by serathius**
Fixes https://k8s-testgrid.appspot.com/google-gce#gci-gce-sd-logging

Removes location verification that was used for event-exporter tests.

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
Please add some context to the PR description

/lgtm
/approve no-issue

**Comment by crassirostris** [comment]
I think this should be merged in 1.10 to fix failing e2e tests

**Comment by crassirostris** [comment]
There's some bug with the cla authorizer. Test is green, Marek has submitted PRs in the past, but the label is not applied

Applying it manually

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/6939

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60566)

**Comment by Random-Liu** [comment]
@serathius It seems that this only fixed one of the 2 test failures, another one is still failing.

https://k8s-testgrid.appspot.com/google-gce#gci-gce-sd-logging

**Comment by serathius** [comment]
Looks like second test became flaky.

**Pull request merged**
