### PR TITLE
Automated cherry pick of #23793

### PR DESCRIPTION
**Pull request by mikedanese**
Cherry pick of #23793 on release-1.2.

### CODE REVIEW

**Comment by mikedanese** [comment]
Closes #23825 cc @pmorie

**Comment by pmorie** [comment]
This seems significant enough that there should be a release note for 1.2.1, but I'm not certain whether this issue title is going to be descriptive enough.  Thoughts @mikedanese ?

**Comment by mikedanese** [comment]
@pmorie Release notes should come from the title of the original PR if I'm not mistaken. Is that correct @eparis @david-mcmahon ?

**Comment by david-mcmahon** [comment]
Yes, your original master PR title is the release note - https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes

**Pull request merged**
