### PR TITLE
change cpu  value to 1000

### PR DESCRIPTION
**Pull request by sub-mod**
@bgrant0607 kindly review

### CODE REVIEW

**Comment by bgrant0607** [comment]
Sorry, this is unnecessary. I missed the line that converted CPU to milli-cpu:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/conversion.go#L984

**Comment by bgrant0607** [comment]
@vishh

**Comment by bgrant0607** [comment]
Sorry, this is unnecessary, as explained in the other PR.
@vishh

**Comment by vishh** [comment]
@sub-mod: Your existing v1beta3 examples are fine as is. Sorry about the confusion created in your previous PRs.

**Pull request closed without merging**
