### PR TITLE
makes some error messages helpful in cronjob tests

### LINKED ISSUE #34059: destroy the "Expect(err).NotTo(HaveOccurred())" anti-pattern in e2e tests
I'm getting tired of seeing flake issues like https://github.com/kubernetes/kubernetes/issues/33647 where every single failure is of the form

```
Expected error:
    <*errors.errorString | 0xc820412c10>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

This is about as unhelpful an error message as you can get.

The problem is that we have

``` go
Expect(err).NotTo(HaveOccurred())
```

peppered throughout the code everywhere, and in this form, you can only figure out what failed if you read the Ginkgo error, remember which line has the line number you actually want, and then try to read surrounding code in that file.

Possible improvements given in http://onsi.github.io/gomega/#handling-errors:
- Use `Succeed()`
- Annotate the assertions
- Basically, do anything except just Expect(err).NotTo(HaveOccurred())

cc @kubernetes/sig-testing

### PR DESCRIPTION
**Pull request by war-turtle**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Makes some error messages in cronjob tests helpful.

**Which issue(s) this PR fixes**:

Fixes #34059 

**Special notes for your reviewer**:
This is my very first time contributing to kubernetes. So please let me know if something is wrong!

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fejta** [comment]
Can you please rebase this aka squash it down into a single commit?
/lgtm

https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by fejta** [comment]
/hold
(please `/hold cancel` after this is one commit)

**Comment by war-turtle** [comment]
@fejta 
Please review this again.

**Pull request merged**
