### PR TITLE
remove reference to promhttp in kubelet

### PR DESCRIPTION
**Pull request by wuyafang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
remove reference to promhttp in kubelet

**Which issue(s) this PR fixes**:

Refer https://github.com/kubernetes/enhancements/issues/1238
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks.
/lgtm
/priority important-soon
/assign @random-liu

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for your work here :)

**Comment by wuyafang** [comment]
@feiskyer @dchen1107 thanks

**Comment by RainbowMango** [comment]
/milestone v1.17

Kindly ping @kubernetes/sig-node-pr-reviews

**Comment by yujuhong** [comment]
/approve
Thanks!

**Pull request merged**
