### PR TITLE
Make kubelet-perf 100 pod/node test work with registered master

### PR DESCRIPTION
**Pull request by gmarek**
cc @yujuhong

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by gmarek** [comment]
@k8s-bot test this issue: #18558

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Comment by dchen1107** [comment]
Fixed #22755

**Comment by bgrant0607** [comment]
@dchen1107 "Fix" comments don't help. The PR description needs to be modified.

**Comment by bgrant0607** [comment]
Does this need to be cherrypicked into 1.2?

**Comment by bgrant0607** [comment]
Nvrmd

**Comment by dchen1107** [comment]
Yes, we do for test fixing.

**Comment by bgrant0607** [comment]
Merging to fix e2e. @k8s-oncall

**Comment by eparis** [comment]
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.

**Pull request merged**
