### PR TITLE
Updated example description and instructions

### PR DESCRIPTION
**Pull request by ashish-billore**
Updated the example's description by rewording it and added
instructions to verify the deployment list

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR has updates to the deployment resource's lifecycle example description by rewording it and also has instructions to verify the deployment list.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

This PR has updates to the deployment resource's lifecycle example description by rewording it and also has instructions to verify the deployment list.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ashish-billore** [comment]
Thanks  @yliaog for reviewing this, could you please suggest if there anything I need to do to get this merged?
Thanks again!

**Comment by yliaog** [comment]
@sttts could you review/approve it?

**Comment by ashish-billore** [comment]
@sttts please suggest if this patch looks good to be approved, thanks!

**Comment by ashish-billore** [comment]
@sttts please suggest if this patch looks good to be approved, thanks!

**Pull request closed without merging**
