### PR TITLE
Update addon resizer parameters

### LINKED ISSUE #50599: Addon resizer v2.0 significantly decreases resources for Heapster
Resources assigned to Heapster on 1000 nodes cluster:

with version 1.7
765m
5.6G

with version 2.0
540m
4.6GB

Heapster tends to OOM from time to time with the latter parameters.

### PR DESCRIPTION
**Pull request by x13n**
**What this PR does / why we need it**:
With the new addon resizer algorithm introduced by v2.0, accepted values
are +/-20% from the values provided via command line, while previously
they were treated as the lower bound. This change offsets the original
values so that previous lower bound is preserved.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50599

**Special notes for your reviewer**:

**Release note**:

```release-note
Heapster resource requests were increased to help with out-of-memory issues in bigger clusters.
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
So @x13n started a 1k-node cluster to test this change. I looked into it and heapster pod seems to be running. However from the container logs:

```
E0908 12:46:20.576286       1 influxdb.go:186] InfluxDB write failed: Post http://monitoring-influxdb:8086/write?consistency=&db=k8s&precision=&rp=default: EOF
E0908 12:46:20.578370       1 influxdb.go:190] InfluxDB ping failed: Get http://monitoring-influxdb:8086/ping: dial tcp 10.0.252.138:8086: getsockopt: connection refused
I0908 12:46:20.578386       1 influxdb.go:56] Influxdb connection reset
E0908 12:46:20.598143       1 influxdb.go:175] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.0.252.138:8086: getsockopt: connection refused
E0908 12:46:20.617318       1 influxdb.go:175] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.0.252.138:8086: getsockopt: connection refused
E0908 12:46:20.636750       1 influxdb.go:175] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.0.252.138:8086: getsockopt: connection refused
...
```

it seems like influxdb failed to start. The same issue I reported earlier - https://github.com/kubernetes/kubernetes/issues/51702

@piosz Any idea why this could be happening and/or how to fix it? I can help with the fix itself.

**Comment by piosz** [comment]
As I mentioned offline the configuration you want to test is [stackdriver](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L124).

**Comment by shyamjvs** [comment]
I'll bring up the cluster with stackdriver instead and check. Thanks.

**Comment by piosz** [comment]
@shyamjvs let's sync on this on Monday.

**Comment by shyamjvs** [comment]
Sorry I've gotten busy with some release-related scale experiments. Can this wait for a few days?
If no, I can assist you with setting up a large cluster or find time to do it myself asap.

**Comment by piosz** [comment]
No worries @shyamjvs. We will most likely revert the whole nanny change.

**Comment by piosz** [comment]
cc @fgrzadkowski

**Comment by x13n** [comment]
Tested on 1000 node cluster. Coefficients above don't seem to be enough. Works with the following though:
--cpu=100m
--extra-cpu=0.7m
--memory=175Mi
--extra-memory=6Mi

With default recommendation offset of 10% this results in:

730m
5575Mi

for 1k nodes, which both works & is pretty close to the previous values. I will update this PR with those values.

**Comment by x13n** [comment]
I'm closing this. After giving it some thought, I think the interface of addon resizer 2.0 is not intuitive and should be changed anyway - with parameters being min values, not centers of implicitly defined resource range.

**Pull request closed without merging**
