### PR TITLE
Cache configmaps in kubelet

### LINKED ISSUE #41379: Add a configmap manager to cache duplicate configmaps
Clone of https://github.com/kubernetes/kubernetes/issues/19188 for configmaps

A secret manager was added to the kubelet to reduce duplicate requests for secrets (if a secret was used in multiple volumes, pull secrets, and envvars)

The same should be done for configmaps to keep parity between those two objects.

cc @wojtek-t @yujuhong

### PR DESCRIPTION
**Pull request by fraenkel**
- Add a configmap manager to cache duplicate configmaps

fixes #41379

### CODE REVIEW

**Comment by fraenkel** [comment]
@liggitt Not sure how soon you wanted this to drop in.

**Comment by fraenkel** [comment]
@k8s-bot ok to test

**Comment by fraenkel** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by wojtek-t** [comment]
@shyamjvs - FYI
It seems to be what you are doing - you should sync with @fraenkel

**Comment by shyamjvs** [comment]
Oh it's a shame I re-did it.
@fraenkel Turns out I've made a similar PR (https://github.com/kubernetes/kubernetes/pull/46470). Seems like there are few changes that are missing in this one (like fake_manager for configmap, changes to pkg/volume/projected and relevant build files). If you want to make these changes, I'm happy to close my PR. However it's a bit urgent to have these changes pushed before the code freeze this thursday, so if you don't have time before that I can use mine :)

**Comment by fraenkel** [comment]
@shyamjvs You can go with yours. The fake_manager was not needed since I was using the real one everyone. I find it is safer if possible. It seems the projected is the only thing missing. You are missing the caching support from configmap_manager which was lifted from the secret one anyhow.

**Comment by shyamjvs** [comment]
@fraenkel Thanks a lot for the leads. Yes, the caching manager is not part of that PR and I have a separate ready to be sent as a successor to the current one.

**Pull request closed without merging**
