### PR TITLE
Update dedent to latest release

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, this PR updates the renamed maintainer of `dedent` and bumps it to the latest release.

/kind cleanup

### CODE REVIEW

**Comment by arunvelsriram** [comment]
When I try to use a package, `go mod tidy -v` fails.

```
....
go: finding github.com/docker/docker/pkg latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go: github.com/renstrom/dedent@v1.1.0: parsing go.mod: unexpected module path "github.com/lithammer/dedent"
go: error loading module requirements
```

Any workaround to overcome the error till this PR is merged?

**Comment by lithammer** [comment]
Hi, maintainer here. Is there anything _I_ can do on my end?

**Review by neolit123 — COMMENTED** [review]
/priority important-longterm

let me know we want to run tests on this already?

**Comment by neolit123** [comment]
so this is an interesting situation.

@lithammer 
> Hi, maintainer here. Sorry about the inconvenience. Is there anything I can do on my end?

`https://github.com/renstrom` no longer exists, and even if you probably the owner i wonder how we can prove that? :) 

/assign @dims

**Comment by lithammer** [comment]
>https://github.com/renstrom no longer exists, and even if you probably the owner i wonder how we can prove that? :)

While that no longer seems to work. You can still use the old _project_ URL and it will redirect to me. Is that good enough?

```bash
$ curl -i https://github.com/renstrom/dedent
HTTP/1.1 301 Moved Permanently
...
Location: https://github.com/lithammer/dedent
...

<html><body>You are being <a href="https://github.com/lithammer/dedent">redirected</a>.</body></html>
```

**Comment by dims** [comment]
/assign @cblecker @thockin 

Christoph, Tim, would really like you to poke at this dependency change

**Comment by saschagrunert** [comment]
Hm, is there anything I can do to fix the failing test? :thinking:

**Comment by dims** [comment]
@saschagrunert yes if you see the output of the CI job it has 2 sections.

```
Godeps Verify failed.
If you're seeing this locally, run the below command to fix your Godeps.json:
patch -p0 < godepdiff.patch
(The above output can be saved as godepdiff.patch if you're not running this locally)
(The patch file should also be exported as a build artifact if run through CI)
```

```
Godeps Verify failed.
If you're seeing this locally, run the below command to fix your directories:
patch -p0 < vendordiff.patch
(The above output can be saved as godepdiff.patch if you're not running this locally)
(The patch file should also be exported as a build artifact if run through CI)
```

So, basically apply the diff(s) from
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72923/pull-kubernetes-godeps/1146/artifacts/vendordiff.patch
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72923/pull-kubernetes-godeps/1146/artifacts/godepdiff.patch

and update the PR with the changes from above.

**Comment by cblecker** [comment]
You'll also need to update here: https://github.com/kubernetes/kubernetes/blob/0713f29c289a339fef06647c10fa65d59a169a8d/cmd/kubeadm/.import-restrictions#L166

as well as run `hack/update-bazel.sh`

**Comment by saschagrunert** [comment]
@cblecker Thanks for the hints :+1:

**Comment by cblecker** [comment]
I'm fine with this. No meaningful code changes, just an author name change.

/lgtm
/approve

**Review by neolit123 — APPROVED** [review]

**Comment by neolit123** [comment]
:+1: 
/approve

**Comment by cblecker** [comment]
/assign @thockin 
for approval

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
