### PR TITLE
Fix error printing objects from kubectl get -w

### LINKED ISSUE #42276: kubectl get pods -w does not work
```
$ cluster/kubectl.sh get pods
NAME                     READY     STATUS        RESTARTS   AGE
nginx-4000326355-16f5c   0/1       Terminating   0          1m
[decarr@localhost kubernetes (burstable-cpu-shares)]$ cluster/kubectl.sh get pods -w
error: unable to output the provided object: error: unknown type &unstructured.UnstructuredList{Object:map[string]interface {}{"kind":"PodList", "apiVersion":"v1", "metadata":map[string]interface {}{"selfLink":"/api/v1/namespaces/default/pods", "resourceVersion":"458"}}, Items:[]*unstructured.Unstructured{(*unstructured.Unstructured)(0xc420032058)}}
$ cluster/kubectl.sh get pods -w -o name
pods/nginx-4000326355-4fhq5
```

looks like human readable printer is barfing, but others work.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #42276

### CODE REVIEW

**Comment by liggitt** [comment]
@k8s-bot cvm gce e2e test this

**Comment by liggitt** [comment]
@k8s-bot kops aws e2e test this

**Comment by liggitt** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
/lgtm
/approve

This is a bug in printing that is required for correct behavior and needs to be in 1.6

**Pull request merged**
