### PR TITLE
Automated cherry pick of #108209: increase Azure ACR credential provider timeout

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #108209 on release-1.22.

#108209: increase Azure ACR credential provider timeout

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
