### PR TITLE
Remove the deprecated vagrant kube-up implementation

### PR DESCRIPTION
**Pull request by roberthbailey**
xref #49213

```release-note
Remove deprecated vagrant kube-up.sh. 
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
/assign jbeda

for top level approval to delete the Vagrant file

**Comment by derekwaynecarr** [comment]
For reference, this was the first solution I wrote to support running kubernetes outside of google, but since those early days, far better solutions have come forward.  Happy to see this go now!  It's a sign of community progress.

**Pull request merged**
