### PR TITLE
cAdvisor bump

### LINKED ISSUE #10451: Kubelet taking large amounts of cpu in v0.19.3
Ever since we spun on a new cluster the cpu has been slowly climbing
The cloud monitoring console is showing this climb

This shows the cpu usage increase over the course of 2 days.
![screen shot 2015-06-27 at 11 49 53 am](https://cloud.githubusercontent.com/assets/11711723/8393011/ab28adc2-1cc2-11e5-807c-0624908137fa.png)

On sshing in to the node, I see that kubelet is taking most of the cpu.

```
 PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                                                                                                                                                                                                                                         
 3002 root      20   0  177m  85m  20m S  20.3  5.0 315:19.21 kubelet                                                                                                                                                                                                                                                         
 3765 root      20   0  938m  81m  12m S   9.7  4.8  53:15.97 docker                                                                                                                                                                                                                                                          
 9796 root      20   0  885m  96m 9476 S   1.0  5.6   1:11.19 nodejs                                                                                                                                                                                                                                                          
 3046 root      20   0 80148  16m  11m S   0.3  0.9   5:59.90 kube-proxy           
```

Let me know if you would like traces to investigate this. I can easily restart the kubelet to solve this issue, however I will wait for getting you some traces before I do so.

### PR DESCRIPTION
**Pull request by jimmidyson**
Needed to fix #10451 (high CPU usage caused by `du`) & to add some improvements to prometheus metrics exposition, namely labelling with kubernetes metadata.

/cc @yujuhong @vishh

### CODE REVIEW

**Comment by vishh** [comment]
@jimmidyson: Can we add a tag in cadvisor?

**Comment by jimmidyson** [comment]
@vishh Ooo I can do that now - forgot that ;) Doing it now.

**Comment by jimmidyson** [comment]
@vishh Done - tagged as 0.19.0

**Comment by vishh** [comment]
Won't that tag conflict with an actual 0.19.0 release?

**Comment by jimmidyson** [comment]
That tag can be the 0.19.0 release :)

**Comment by jimmidyson** [comment]
Jenkins flake...

**Comment by jimmidyson** [comment]
@vishh So what do you want me to do? I want to get this on now please.

**Comment by pmorie** [comment]
@vishh @jimmidyson I think we will also need to bump libcontainer at the same time -- the `AdditionalGroups` field in the config schema in kubernetes master is out of date relative to libcontainer master and the version godep'd by cAdvisor.  The change was introduced in this commit and I know of at least one commit to libcontainer that builds upon it:

https://github.com/opencontainers/runc/commit/429752a69d4a224e0aa65e09a4f9c396ee3eaa70

I found this yesterday when preparing a patch for #15352 to OpenShift.  In OpenShift, the problem surfaces to the user as an error status on a container that uses supplemental groups, though the container process is started and runs correctly.  It does not surface in the same way in kube master, which I need to do more digging about today.

So, TLDR: we are using an out of date version of libcontainer for embedding cAdvisor in kube.

**Comment by jimmidyson** [comment]
Travis failure is due to godeps verification failure - should be sorted after #15707 is merged & this is rebased.

**Comment by vishh** [comment]
@pmorie: AFAIK we are only supporting docker versions 1.7+ moving forward. @dchen1107 can probably corroborate that statement.

**Comment by vishh** [comment]
LGTM. Thanks for the PR @jimmidyson!! This should fix the disk related cpu usage issue as well. #10451

**Comment by jimmidyson** [comment]
Annoying bitbucket outage it seems - kills godep verify.

**Comment by jimmidyson** [comment]
Any chance of a retest now bitbucket is back online?

**Comment by jimmidyson** [comment]
@vishh @smarterclayton Any chance of a retest of this & review so we can get this merged soon?

**Comment by pmorie** [comment]
I am a little surprised that `AdditionalGroups` is not changing to a string in libcontainer config.

**Comment by jimmidyson** [comment]
@pmorie So I've locally bumped the libcontainer godep to pull that`AdditionalGroups` change in but that now requires a docker bump as well...

@smarterclayton @vishh I'm not sure of the effect of a docker godep bump on supported versions. Are there integration tests in k8s to check compatibility with various docker versions?

I'd propose getting the cadvisor bump in & then I can try to handle the docker & libcontainer in a separate PR?

**Comment by pmorie** [comment]
@jimmidyson Yep, there's the rub.  I guess my question is where the libcontainer changes in the current state of this PR come from.  Btw, I am going to file some issues re: the `AdditionalGroups` changes today for kube and cadvisor so we can discuss how to handle this.  It's sticky.

**Comment by jimmidyson** [comment]
@pmorie Probably I just messed up the godep bump... oops!

**Comment by vishh** [comment]
@jimmidyon: This needs to be cherrypicked into v1.1 release branch.

**Comment by pmorie** [comment]
@jimmidyson Did a little digging tonight to figure out why `AdditionalGroups` didn't change in this bump.  Turns out that the field has diverged between Docker and cAdvisor:

* [version in cAdvisor](https://github.com/google/cadvisor/blob/master/Godeps/_workspace/src/github.com/docker/libcontainer/configs/config.go#L87)
* [version in Docker](https://github.com/docker/docker/blob/master/vendor/src/github.com/opencontainers/runc/libcontainer/configs/config.go#L148)

This hasn't been an issue so far in Kubernetes because we haven't used the `AdditionalGroups` field in the docker API yet.  I'll open an issue for this -- seems like it is really a cAdvisor issue since cAdvisor has to be able to consume what the system docker puts down.

@vishh @thockin @smarterclayton thoughts?

**Comment by jimmidyson** [comment]
I wasn't actually expecting this to be merged until the libcontainer stuff had been discussed & decided. Should we revert this change to separate out the cadvisor & libcontainer bumps?

**Comment by pmorie** [comment]
@jimmidyson I think it's okay for now -- I meant to mention earlier, you had no errors in your PR.  I think the issue needs to be sorted out in cadvisor.

**Pull request merged**
