### PR TITLE
Automated cherry pick of #64660: Add hierarchy support for plugin directory

### PR DESCRIPTION
**Pull request by figo**
Cherry pick of #64660 on release-1.11.

#64660: Add hierarchy support for plugin directory

### CODE REVIEW

**Comment by RenaudWasTaken** [comment]
Hello!

IMHO we shouldn't backport this patch. I don't see a need to do it. This won't fix any existing bug nor accelerate the graduation of the pluginwatcher feature.

Though I think the code has been thoroughly reviewed and vetted, backporting this still caries the risk of breaking a feature that seems to be working fine right now.

**Comment by figo** [comment]
I agree with you, this does not necessary to be 1.11, i will close the PR if no objection from CSI point of view, @saad-ali could you help on weigh in?

On the other hand, @RenaudWasTaken, @vikaschoudhary16 do you have some idea of target timeframe of pluginWatcher beta?   it will help me or others to plan better to help on pluginWatcher beta,  Thanks

**Comment by RenaudWasTaken** [comment]
I'm planing to open an issue today to discuss what are the objectives for graduating the pluginwatcher to beta. I have a list of things that I think are required and would like to discuss them with the community :)

**Comment by RenaudWasTaken** [comment]
Please take a look at this issue: https://github.com/kubernetes/kubernetes/issues/65773

**Pull request closed without merging**
