### PR TITLE
[WIP] CRI: choose runtime for a sandbox

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**What this PR does / why we need it**:

This PR adds the ability to chose which runtime to be used for an entire pod or per container (if that makes sense). Right now, CRI-O can use whatever OCI runtime is plugged in and multiple runtimes can also be plugged and used simultaneously. Think of this as running certain pods with Clear containers in VMs while other in plain Linux containers with runc.

I'm not really sure we should expose runtimes directly via the CRI - another option would be to expose CRI functionality, let's say "this CRI server (CRI-O) can run virtual machines and containers and you can chose it".

@mrunalp @smarterclayton @mfojtik @feiskyer @vishh PTAL

I marked this WIP meantime as I'm not fully sure on the approach and would appreciate feedback before changing everything.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'm pretty hesitant to add something like this because of our long history of saying this is a detail of the node, not of the cluster.  Schedulers would have to take aspects of this into account, and it would have to be controlled by pod security policy before we allowed it in (some runtimes are insecure).  That said, with CRI in place this is less scary than it was. And the multi network story is starting to look like this as well.  So I'm open to reevaluating.  It might be useful for cluster administrators to define extension CRI that offer additional resource controls.

I'd like this in proposal form with some details about use cases.  This is too important to just be a PR and needs more buy in at a high level.

**Comment by runcom** [comment]
@smarterclayton I'll create a proposal, the scheduler could make decisions based on each node capability (something like using node selectors and use certain nodes just for builds in vms and stuff like this.

BTW, going to leave this open and create a proposal for this (even in this PR, I'll remove the code)

**Comment by thockin** [comment]
I am pretty sure this is NOT something we want to expose, and if we did it would not be at this level of abstraction.  We explicitly ruled out the idea of coordinating between runtimes on a single machine.  If we really want to go here, it would probably be best as an attribute-based intent-oriented statement, which was implemented through policy owned by the cluster admin, as we do with things like storage classes.

A proposal is fine, but I have to be honest, I'm not super excited about this at this point in the project.

**Comment by sameo** [comment]
cc @philips

**Pull request closed without merging**
