### PR TITLE
Make it clear where the `build` scripts are located

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
I think the failure is unrelated.

**Comment by ihmccreery** [comment]
LGTM; thanks @duglin!  It's these little things that can make a big difference in dev experience.

**Comment by duglin** [comment]
is there anything I need to do on this?

**Comment by ihmccreery** [comment]
Nope, sorry; I just forgot to re-add LGTM after merge-bot removed it.

**Comment by ihmccreery** [comment]
@k8s-bot test this again issue: #24991

**Comment by duglin** [comment]
is it possible to get the unit/integration tests re-run?  I'm assuming that's what's causing the delay.

**Comment by ihmccreery** [comment]
@k8s-bot test this again please issue: #25363

**Pull request merged**
