### PR TITLE
Add spec.selector to DaemonSet examples.

### LINKED ISSUE #18130: Failed to create DaemonSet using sample yaml file
I tried to create daemonset using this yaml sample found from daemonset guide: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/daemon.md  and I've changed apiVersion <code>extensions/v1beta1</code> since <code>v1</code> does not work actually. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: datastore
  name: datastore
spec:
  template:
    metadata:
      labels:
        app: datastore-shard
    spec:
      nodeSelector:
        app: datastore-node
      containers:
        name: datastore-shard
        image: kubernetes/sharded
        ports:
          - containerPort: 9042
            name: main
```

But when I try to create it, the error message said

```
kubectl create -f try_daemon.yml  
error validating "try_daemon.yml": error validating data: couldn't find type: v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false
```

Then skip validate and it said
```
kubectl create -f try_daemon.yml  --validate=false
unable to load "try_daemon.yml": json: cannot unmarshal object into Go value of type []v1.Container
```

When I query <code>v1beta1</code> api, 

```
curl http://localhost:8080/apis/extensions/v1beta1                                                                       
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "daemonsets",
      "namespaced": true
    },
    {
      "name": "daemonsets/status",
      "namespaced": true
    },

 curl http://localhost:8080/apis/extensions/v1beta1/daemonsets
{
  "kind": "DaemonSetList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/daemonsets",
    "resourceVersion": "298771"
  },
  "items": []
}
```

Combin different cases also failed.

```
[root@tivsun01 ~]# kubectl create -f try_daemon.yml  --validate=false                                                                       
unable to recognize "try_daemon.yml": no kind named "DaemonSets" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# vim try_daemon.yml                                                                                                       
[root@txxx ~]# kubectl create -f try_daemon.yml  --validate=false
unable to recognize "try_daemon.yml": no kind named "daemonsets" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# vim try_daemon.yml                                                                                                       
[root@xxx ~]# kubectl create -f try_daemon.yml  --validate=false
unable to recognize "try_daemon.yml": no kind named "daemonset" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# 
```

My environment is <code>v1.1.2</code> and here is my <code>kubernetes</code> image version. 

```
gcr.io/google_containers/kube-apiserver                       c23815ed09d218f0f551444927e84053   33b47e12ce09        2 weeks ago         47.94 MB
gcr.io/google_containers/kube-scheduler                       5b511d642ff308c8a4bd0c5c41b068a4   0c0374138b89        2 weeks ago         20.79 MB
gcr.io/google_containers/kube-controller-manager              94b57c6821892f2fffe19c31eed8cf5c   706c30f908dd        2 weeks ago         40.01 MB
```

### PR DESCRIPTION
**Pull request by mml**
Fixes #18130

### CODE REVIEW

**Comment by mikedanese** [comment]
The selector should be defaulted from the template.metadata.labels

**Comment by mikedanese** [comment]
See https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/defaults.go#L32-L46,
 I wonder where this error is coming from

**Comment by mml** [comment]
> I wonder where this error is coming from

I suspect it's related to #18393

**Comment by mml** [comment]
No longer needed.

**Pull request closed without merging**
