### PR TITLE
fix golint errors in pkg/volume/local and pkg/volume/nfs

### PR DESCRIPTION
**Pull request by chrischdi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
There's an umbrella bug for golint failures: #68026
This PR fix golint errors in:

* `pkg/volume/local`
* `pkg/volume/nfs`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mcrute** [comment]
This looks ready to merge... adding @saad-ali @spiffxp for approval.

/lgtm
/assign @saad-ali @spiffxp

**Comment by spiffxp** [comment]
/close
Please /reopen if you plan on rebasing this

**Pull request closed without merging**
