### PR TITLE
AWS: Include friendly tags with ELBs and associated security groups which indicate the origin namespace and Service name.

### PR DESCRIPTION
**Pull request by chris-codaio**
@justinsb PTAL

This addresses issue #16709

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes/18696)

### CODE REVIEW

**Comment by chrisleck** [comment]
@brendandburns PTAL

**Comment by chrisleck** [comment]
Ping ping pingy ping.  Anyone around to look at this?

**Comment by smarterclayton** [comment]
@justinsb can you take a look at this?

**Comment by chrisleck** [comment]
Rebased.

**Comment by chrisleck** [comment]
Hmm - looks like clarifai had basically the same PR submitted for review and merged within 5 days.  
Glad the functionality I want is now present, but what does it take to get attention on PRs in Kubernetes?  This lack of attention makes me not want to contribute. @thockin @brendandburns @justinsb

**Comment by justinsb** [comment]
@chrisleck Sorry for that!  I neglected to label your PR with the aws label, so it fell off my radar.

#20731 did merge quickly (I presume that's the PR you are referring to).  #20731 solved an issue that @thockin had opened because of problems debugging, when there was a difficult-to-track-down e2e flake on a test involving load balancers.  It was also during a big push on e2e testing and eliminating flakes.  In short, it met an immediate and urgent need, and so got attention.

It was my mistake not to realize that your PR also solved the problem.  However, even if I had, I think we would still have merged #20731 over this PR.  Comparing the two PRs, the other PR does one thing and is essentially minimal, and so is very easy to review and LGTM.  There's just not a lot in there to disagree with; and given the issue had been produced by a third party it was clear it should be merged.  This PR includes additional refactorings and changes, so is much harder to review and LGTM.

I think you and I were also having a discussion of the separate security group for load balancers in a separate PR.  So I couldn't merge this one anyway without resolving that question.

I hope you keep contributing to kubernetes, and I suggest that if you produce smaller highly-focused PRs they will be merged.  If they fix an important open issue they will likely be merged very quickly!

Here's a specific PR that I think would be very welcome: This PR is superior in a few ways.  In particular, your PR adds tags to the ELB security group with the service information, whereas we don't do that currently AFAICT.  If you submitted a PR to add that functionality (and assigned it to me), I would be very amenable to merging it.  Doubly so if it was small and highly focused!

As one last small suggestion, I'm not familiar with reviewable, but it isn't our normal review process, so I wouldn't recommend including it.

(We're actually in feature freeze for the next few weeks, so don't be upset if non-bug-fixes don't get merged for these few weeks, until the release 1.2 branch is cut.)

**Comment by chrisleck** [comment]
Thanks, Justin.  Is there a way to get your attention on future PRs so it doesn't fall off your radar?  It feels too difficult at the moment.

**Pull request closed without merging**
