### PR TITLE
Add some unit tests for azure instances...

### PR DESCRIPTION
**Pull request by brendandburns**
Builds on top of #59302

Please only review https://github.com/kubernetes/kubernetes/pull/59305/commits/83597fc47fed777c4e04c9fbf6dd3ad566b19349

kind/cleanup
sig/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
```
I0203 06:44:45.318] +++ Running case: verify.govet 
I0203 06:44:45.320] +++ working dir: /go/src/k8s.io/kubernetes
I0203 06:44:45.322] +++ command: bash "hack/make-rules/../../hack/verify-govet.sh"
W0203 06:48:45.663] pkg/cloudprovider/providers/azure/azure_instances_test.go:177: arg t for printf verb %s of wrong type: *testing.T
W0203 06:48:45.699] exit status 1
I0203 06:50:28.792] Makefile:363: recipe for target 'vet' failed
I0203 06:50:28.802] +++ exit code: 2
I0203 06:50:28.807] +++ error: 1
```

**Review by colemickens — APPROVED** [review]

**Comment by brendandburns** [comment]
govet error fixed...

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by brendandburns** [comment]
self-lgtm because this was a rebase.

**Comment by andyzhangx** [comment]
@brendandburns there are some code changes out of azure scope, is that expected? e.g. pkg/security/podsecuritypolicy/provider_test.go

**Pull request closed without merging**
