### PR TITLE
Fix metric label

### PR DESCRIPTION
**Pull request by rhcarvalho**
Second try to submit this (replacing #7766)

### CODE REVIEW

**Comment by rhcarvalho** [comment]
Sorry for duplicating the PR. I wanted to see if the bot would behave differently towards a fresh one.

I have the commit signed with my `redhat.com` email, have this email verified within Github, I'm on the OpenShift organization, and the company field in my profile says "Red Hat"... still the bot doesn't recognize me. Could anyone please check? What am I missing? Thanks!

**Comment by vmarmol** [comment]
LGTM, I'm fine to merge but let's try to get the CLA stuff working for future easiness. AFAIK there is a Google Group for Red Hat which is what the bot expects. Do you know if you're in that group?

**Comment by rhcarvalho** [comment]
@vmarmol, sorry for the CLA trouble. Unfortunately, I'm not aware of such Google Group for Red Hat :(

**Comment by vmarmol** [comment]
Thanks @rhcarvalho, will merge and followup with some folks when they get in.

**Pull request merged**
