### PR TITLE
use Infof/Errorf instead of Info/Error when klog had format

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
use Infof/Errorf instead of Info/Error when klog had format in pkg/volume/scaleio
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
IMO this PR is useless, `klog.Error` / `Info` replaced here has always a single parameter (output of `log()`) and it's faster than `Errorf` / `Infof` in this context.

**Comment by thockin** [comment]
@jan - all of these have %v sorts of expansions, so they need formatted printing, unless I am missing something?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by davidz627** [comment]
@thockin I believe the reasoning is that the format string with `%v` and related args actually arguments to the `log` function which is an `FprintF` in the implementation (not arguments to the `klog.Error` directly). Although this is definitely not very clear on first glance and could probably be improved (though this PR would do the opposite since it would change these calls to imply that log returns some string that requires formatting substitution).

/hold
until resolved

**Comment by jsafrane** [comment]
> format string with `%v` and related args actually arguments to the `log` function which is an `FprintF` in the implementation

Exactly, there is no `%` expansion in `klog.Info(f)` arguments, everything is expanded by `log()`.

I am not sure it's possible to make it much clearer with go, unless we re-implement half of klog here.

**Comment by jan** [comment]
@thockin That makes sense. Thanks for letting me know.

**Pull request closed without merging**
