### PR TITLE
tests: Replaces images used with agnhost (part 2)

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind feature

/sig testing

**What this PR does / why we need it**:

Quite a few images are only used a few times in a few tests. Thus, the images are being centralized into the agnhost image, reducing the number of images that have to be pulled and used.

This PR replaces the usage of the following images with agnhost:

- net
- netexec
- nettest
- webhook

**Which issue(s) this PR fixes**:

Related: #76342
Depends On: #78390

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
/hold
depends on #78390

**Comment by bclau** [comment]
/cc @listx

Hello, can you build the agnhost:2.1 image and push it to gcr.io?

Thanks!

**Comment by spiffxp** [comment]
```
spiffxp@spiffxp-macbookpro:images (master %)$ make all-container WHAT=agnhost
./image-util.sh build agnhost
Building image for agnhost ARCH: linux/amd64...
../image-util.sh bin agnhost
cmd/go: unsupported GOOS/GOARCH pair linux/linux/amd64
make[1]: *** [bin] Error 2
make: *** [all-container] Error 2
```

The `linux/` prefix should be stripped from `BASEIMAGE` (my bad for missing this on my review of https://github.com/kubernetes/kubernetes/pull/78390)
```
linux/amd64=alpine:3.6
linux/arm=arm32v6/alpine:3.6
linux/arm64=arm64v8/alpine:3.6
linux/ppc64le=ppc64le/alpine:3.6
linux/s390x=s390x/alpine:3.6
```

Can you amend that file as part of this PR?

**Comment by spiffxp** [comment]
Currently having trouble building on my setup with a locally modified BASEIMAGE, will take a look again tomorrow
```
Building image for agnhost ARCH: arm...
../image-util.sh bin agnhost
~/w/kubernetes/kubernetes/_tmp/test-images-build.DPSxLS ~/w/kubernetes/kubernetes/test/images
Registering qemu-*-static binaries in the kernel
No binfmt support in the kernel.
  Try: '/sbin/modprobe binfmt_misc' from the host
make: *** [all-container] Error 1
```

**Comment by bclau** [comment]
> 
> 
> ```
> spiffxp@spiffxp-macbookpro:images (master %)$ make all-container WHAT=agnhost
> ./image-util.sh build agnhost
> Building image for agnhost ARCH: linux/amd64...
> ../image-util.sh bin agnhost
> cmd/go: unsupported GOOS/GOARCH pair linux/linux/amd64
> make[1]: *** [bin] Error 2
> make: *** [all-container] Error 2
> ```
> 
> The `linux/` prefix should be stripped from `BASEIMAGE` (my bad for missing this on my review of #78390)
> 
> ```
> linux/amd64=alpine:3.6
> linux/arm=arm32v6/alpine:3.6
> linux/arm64=arm64v8/alpine:3.6
> linux/ppc64le=ppc64le/alpine:3.6
> linux/s390x=s390x/alpine:3.6
> ```
> 
> Can you amend that file as part of this PR?

Oups, you're right, the linux/ prefix is being introduced in the test images Windows support PRs, and I mistakenly included it in the agnhost BASEIMAGE file. I've added a PR to amend this: https://github.com/kubernetes/kubernetes/pull/79151

The image seems to be building for me now too.

**Comment by spiffxp** [comment]
I had to some hackery to get `make all-container` to work against my Docker for Mac instance, I think https://github.com/kubernetes/kubernetes/pull/69820 assumes docker is on the host running build scripts, and the host is linux.  To the best of my knowledge, Docker for Mac/Windows already has these registered.  I commented out https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh#L91 and ran `make all-push`.  I'm not entirely sure I trust this.

```
Created manifest list gcr.io/kubernetes-e2e-test-images/agnhost:2.1
Pushed ref gcr.io/kubernetes-e2e-test-images/agnhost@sha256:a588e2af1663e5344771eead26ce5cbdf8e261fc0c74310d99658ff3125ae496 with digest: sha256:a588e2af1663e5344771eead26ce5cbdf8e261fc0c74310d99658ff3125ae496
Pushed ref gcr.io/kubernetes-e2e-test-images/agnhost@sha256:cefafab4b873c0fbd629d6a84ef402b81ff8bb04d30b5acfccc0e98a84cf4bba with digest: sha256:cefafab4b873c0fbd629d6a84ef402b81ff8bb04d30b5acfccc0e98a84cf4bba
Pushed ref gcr.io/kubernetes-e2e-test-images/agnhost@sha256:6bae5ceada29d7f8eee7c84c21a16201f418ae236fb9172fa5b85a9f15645316 with digest: sha256:6bae5ceada29d7f8eee7c84c21a16201f418ae236fb9172fa5b85a9f15645316
Pushed ref gcr.io/kubernetes-e2e-test-images/agnhost@sha256:2b179bb57b26b1517b6aac6be63f36988b4d58329d94216ed3b8375146d01447 with digest: sha256:2b179bb57b26b1517b6aac6be63f36988b4d58329d94216ed3b8375146d01447
Pushed ref gcr.io/kubernetes-e2e-test-images/agnhost@sha256:9976428f150746de75ddf830fed77e9482628e975db2c80aff55d24751238178 with digest: sha256:9976428f150746de75ddf830fed77e9482628e975db2c80aff55d24751238178
sha256:39e5d843553c5dfc53d6aa7883218e6b7bfd40f0aaee2a171b59bbc4fd541fdb
```

/retest

**Comment by spiffxp** [comment]
/lgtm
/hold cancel
#78390 has merged and images have been pushed

I haven't been able to automate away my inability to push images from my laptop, but I'm sufficiently confident they work to proceed

**Comment by spiffxp** [comment]
Hit this flake https://github.com/kubernetes/kubernetes/issues/78913

**Comment by BenTheElder** [comment]
> I had to some hackery to get make all-container to work against my Docker for Mac instance, I think #69820 assumes docker is on the host running build scripts, and the host is linux. To the best of my knowledge, Docker for Mac/Windows already has these registered. I commented out https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh#L91 and ran make all-push. I'm not entirely sure I trust this.

pretty sure it only registers arm, and only on recent versions? could be wrong...

**Comment by spiffxp** [comment]
This is by no means conclusive, this is just as far as I got before deciding I'm not going to try solving this rabbit hole
```sh
$ docker run -it --rm --privileged --pid=host justincormack/nsenter1
/ # ls -l /proc/sys/fs/binfmt_misc/
total 0
-rw-r--r--    1 root     root             0 Jun 25 20:37 qemu-aarch64
-rw-r--r--    1 root     root             0 Jun 25 20:37 qemu-arm
-rw-r--r--    1 root     root             0 Jun 25 20:37 qemu-ppc64le
-rw-r--r--    1 root     root             0 Jun 25 20:37 qemu-s390x
--w-------    1 root     root             0 Jun 25 20:37 register
-rw-r--r--    1 root     root             0 Jun 25 20:37 status
```

**Pull request merged**
