### PR TITLE
Promote RunAsGroup e2e test to Conformance

### PR DESCRIPTION
**Pull request by krmayankk**
/area conformance

@kubernetes/sig-architecture-pr-reviews @kubernetes/sig-foo-pr-reviews @kubernetes/cncf-conformance-wg

### CODE REVIEW

**Comment by ehashman** [comment]
/release-note-none
/kind cleanup
/priority important-soon

Looks good from a triage perspective for node, but this is a testing PR so I won't apply the label.

/hold

because this e2e appears to be failing.

**Comment by oomichi** [comment]
Is RunAsGroup already a GA feature?
According to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ it seems a Beta feature since v1.14.
Is that changed recently?

This question comes because of one of conformance requirements `it tests only GA, non-optional features or APIs (e.g., no alpha or beta endpoints, no feature flags required, no deprecated features)` since https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements

/cc @oomichi

**Comment by ehashman** [comment]
@oomichi see #94641

**Comment by oomichi** [comment]
> 
> 
> @oomichi see #94641

@ehashman Thanks for pointing it out.
https://github.com/kubernetes/kubernetes/pull/94641 should be before this as the requirement.

**Comment by dims** [comment]
looks like https://github.com/kubernetes/kubernetes/pull/94641 missed v1.21, we can revisit this next release

**Comment by krmayankk** [comment]
> looks like #94641 missed v1.21, we can revisit this next release

@dims its not clear why you mention #94641 as missing 1.21 since its a code change and code freeze is in march ? The enchancement changes already merged. Am i missing something ?

**Comment by ehashman** [comment]
@dims no, we are graduating RunAsGroup this release, see https://github.com/kubernetes/enhancements/issues/213#event-4312830640

@krmayankk please rebase

**Comment by krmayankk** [comment]
> @dims no, we are graduating RunAsGroup this release, see [kubernetes/enhancements#213 (comment)](https://github.com/kubernetes/enhancements/issues/213#event-4312830640)
> 
> @krmayankk please rebase

done

**Comment by dims** [comment]
@krmayankk @ehashman my apologies, i thought there were some API changes that needed to land as part of the other PR (and then the tests have to merge typically after that)

So i:
- read the KEP : https://github.com/kubernetes/enhancements/pull/1974/files
- reviewed the PR : https://github.com/kubernetes/kubernetes/pull/94641
- Looked through the cri-test that the KEP points to - https://cs.k8s.io/?q=RunAsGroup&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/cri-tools

Since the PR just removes the feature flag and nothing else, i am happy to LGTM this change, please note that we will have to yank this IF the PR does not land in 1.21

thanks!

/approve
/lgtm

**Comment by ehashman** [comment]
/retest
/triage accepted
(for node)

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=RunAsGroup&width=5 flakiness looks good

need to review that these tests adhere to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements

**Comment by spiffxp** [comment]
>it is non-privileged (e.g., does not require root on nodes, access to raw network interfaces, or cluster admin permissions)

Was the only thing that jumped out at me, but my read of these tests and https://github.com/kubernetes/enhancements/issues/213 is that this meets the requirement

**Review by spiffxp — APPROVED** [review]
/lgtm
/approve
/hold cancel
re: https://github.com/kubernetes/kubernetes/pull/98645#issuecomment-771105524 these tests are no longer failing

**Pull request merged**
