### PR TITLE
Turn on kubenet for GCE

### PR DESCRIPTION
**Pull request by freehan**
It is time to turn on kubenet! @dcbw

### CODE REVIEW

**Comment by thockin** [comment]
w00t

**Comment by freehan** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by freehan** [comment]
@k8s-bot test this issue: #25639

**Comment by freehan** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by freehan** [comment]
Thanks! I will be watching the CIs closely.

**Pull request merged**
