### PR TITLE
Use container-storage-interface spec v1.5.0

### PR DESCRIPTION
**Pull request by chrishenzie**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates the container-storage-interface dependency version to [v1.5.0](https://github.com/container-storage-interface/spec/releases/tag/v1.5.0). This version includes support for the `SINGLE_NODE_SINGLE_WRITER` and `SINGLE_NODE_MULTI_WRITER` volume capability access modes, which is a requirement for https://github.com/kubernetes/kubernetes/pull/102028.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @msau42
/assign @xing-yang

### CODE REVIEW

**Comment by liggitt** [comment]
dep update lgtm, tag once this has lgtm from storage reviewer and tests are green

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/issues/102794 storage-slow job seems to flake due to timeouts

**Comment by chrishenzie** [comment]
@liggitt This is ready for merge

**Pull request merged**
