### PR TITLE
change minion to node

### PR DESCRIPTION
**Pull request by zhengguoyong**
#1111

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @thockin @davidopp

**Comment by thockin** [comment]
This is a scary large PR.  I think the best thing to do would be to break it up, perhaps on 2 axes - first, send a PR (or at least a distinct commit) for each cloud-provider (aws, gce, azure, etc).  Second, break those up into one commit that does just variable names and another that does variable values.

If you send them as separate PRs, it will be much easier.

**Comment by zhengguoyong** [comment]
good idea, i will send separate PRs sooner,
thanks again for your advice.
@thockin

**Comment by zmerlynn** [comment]
It looks like this is getting handled as separate PRs? Closing for now, reopen if you need.

**Pull request closed without merging**
