### PR TITLE
fix api reference

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fixing the api reference docs on master.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Can we do a manual merge?

**Comment by ixdy** [comment]
Broken in #19716.

cc @pmorie @thockin

**Comment by ixdy** [comment]
LGTM (but let's see unit/integration pass)

**Comment by ixdy** [comment]
FYI @k8s-oncall

**Comment by pmorie** [comment]
@ixdy sorry about that, but in my defense, there was a bug in the bot that made it merge :)

kubernetes/contrib#422

**Comment by ixdy** [comment]
looks like you lost to ##20300.

**Comment by fabioy** [comment]
Oops, sorry. I noticed the error and merged a PR myself. Apologies for not noticing this.

**Pull request closed without merging**
