### PR TITLE
sync client-go

### PR DESCRIPTION
**Pull request by deads2k**
Our first straight mechanical sync!  `client-go/pkg` looks nice and slim, we're authoritative for all other packages.

@caesarxuchao @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
approved based on https://github.com/kubernetes/kubernetes/issues/40363

**Comment by deads2k** [comment]
I'm tagging this now since its purely mechanical and people get cranky about an out of date client-go.  Hopefully this one will actually only take one day to merge.

**Comment by caesarxuchao** [comment]
pkg/ looks nice! How about pkg/version and pkg/util? We'll keep copying them I guess?

**Comment by deads2k** [comment]
> pkg/ looks nice! How about pkg/version and pkg/util? We'll keep copying them I guess?

`pkg/version` is required for reporting user-agent. I'm ok with a copy
`pkg/util` entries are transitives of the API types.

**Pull request merged**
