### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ravi-mrk**
1st PR - Removing '$' for standardising and for consistency across Kubernetes documentation

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Removing '$' when including commands Shell Style, for standardising and for consistency across Kubernetes documentation
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Trying to make the documentation format consistent. In many README's on the subdirectories, shell commands aren't succeeded by '$'.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
This looks good to me, based on our [docs style guide](https://kubernetes.io/docs/contribute/style/style-guide/#don-t-include-the-command-prompt).

@ravi-mrk Can you please edit the PR body to change the release note to "NONE"? This doesn't require a release note in our change log.

---
/ok-to-test
/priority backlog
/sig docs

**Comment by ravi-mrk** [comment]
@cblecker Thanks for your comments. Made the changes accordingly.

**Comment by cblecker** [comment]
/lgtm
/approve

/assign @liggitt 
for approval

**Pull request merged**
