### PR TITLE
Revert #83735: Update etcd client to 3.3.16

### LINKED ISSUE #83761: checksum mismatch for github.com/coreos/etcd@v3.3.16+incompatible
The publishing bot is broken right now (https://github.com/kubernetes/kubernetes/issues/56876) because of a checksum mismatch while running `go mod download`:

```
verifying github.com/coreos/etcd@v3.3.16+incompatible: checksum mismatch
	downloaded: h1:2eX1BjV6Wfvl41/35OBA5Np4BHezdTJzhIxSMYxOArA=
	go.sum:     h1:hQaR//OAeI1FQ3G5bGRL9VpFOCurqnEHSup4W693Tb4=
```

I also get this error locally while running `go mod download` on k/k.

etcd was updated to 3.3.16 in https://github.com/kubernetes/kubernetes/pull/83735.

From a quick glance, I'm not completely sure what the problem is since the CI was green for the PR, but I noticed that the PR was created ~2:50pm UTC while the tag https://github.com/etcd-io/etcd/releases/tag/v3.3.16 was created around 6pm UTC.

@jpbetz Was the tag deleted and re-pushed by any chance?

We should look into this before cherry-picking it to 1.16.x (https://github.com/kubernetes/kubernetes/pull/83712#issuecomment-540544567).

/cc @dims @liggitt @cblecker @sttts @gyuho 
/sig architecture
/area code-organization

### PR DESCRIPTION
**Pull request by jpbetz**
Revert etcd client upgrade (https://github.com/kubernetes/kubernetes/pull/83735) to fix https://github.com/kubernetes/kubernetes/issues/83761

See #83762 for more discussion.

/kind bug
/priority critical-urgent

```release-note
NONE
```

/sig api-machinery

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
Thanks for the quick PR!

/lgtm

**Comment by nikhita** [comment]
Thank you, @jpbetz! 
/lgtm

/cc @kubernetes/dep-approvers 
/assign @liggitt 

/sig architecture
/area code-organization

**Comment by odinuge** [comment]
See #83762 for more discussion.

**Comment by liggitt** [comment]
Is the plan to release a .17 release of etcd and bump to that as a follow up?

**Comment by liggitt** [comment]
Unhold at will, it wasn't clear if this was still required

**Comment by jpbetz** [comment]
Yep, we still want to merge this. We will release etcd 3.3.17 to replace 3.3.16.

**Comment by liggitt** [comment]
sounds good, this is in the merge queue

**Pull request merged**
