### PR TITLE
remove useless flags from hack/verify-flags/known-flags.txt

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Flags in known-flags.txt is used to check misspelling from "-" to "_" in
workspace, so a flag with out "-" should not show up in this file.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot unit test this

**Pull request merged**
