### PR TITLE
add beta comment for terminating pods and pod replacement policy

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Terminating is part of PodReplacementPolicy and that was beta in 1.29. Comment should be updated to reflect that.

Pod Replacement Policy should also be updated to reflect that the field is beta.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
/lgtm

From 1.29 Release Team

/unhold

**Comment by kannon92** [comment]
I had some troubles with `make update` so I thought I could get away with running `hack/update-codegen.sh`. I always forget about the openapi code. Updated the PR so this should be good to go.

**Comment by mimowo** [comment]
/hold
Can we also update the related podRepalcementPolicy comment: https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/apis/batch/types.go#L408

**Comment by kannon92** [comment]
> /hold Can we also update the related podRepalcementPolicy comment (it also uses JobPodReplacementPolicy flag):
> 
> https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/apis/batch/types.go#L408
> 
> EDIT: feel free to cancel the hold once done

/hold cancel

Done. Updated. PTAL.

**Review by charles-chenzz — COMMENTED** [review]
/lgtm

**Pull request merged**
