### PR TITLE
Remove unused coreos/go-etcd fork from third_party

### PR DESCRIPTION
**Pull request by jonboulle**
The only usage of this was removed via #18635

### CODE REVIEW

**Comment by fabioy** [comment]
@k8s-bot ok to test

**Comment by fabioy** [comment]
@k8s-bot ok to test

**Comment by fabioy** [comment]
@k8s-bot please test

**Comment by jonboulle** [comment]
how do I get this simple patch merged!?

**Comment by jonboulle** [comment]
bump

**Comment by xiang90** [comment]
lgtm

@fabioy Can we get this merged? Thank you!

**Pull request merged**
