### PR TITLE
Kubemark uses kubectl from the repo

### LINKED ISSUE #23670: kubemark-5 e2e test broken for 5 hours
Seemingly all because after creating its resources, it checks whether resources of a different name exist:

```
22:09:50  - The resource 'projects/k8s-jenkins-kubemark/zones/us-central1-f/instances/kubemark-5-kubemark-master' was not found
22:09:51 ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
22:09:51  - The resource 'projects/k8s-jenkins-kubemark/zones/us-central1-f/disks/kubemark-5-kubemark-master-pd' was not found
22:09:51 ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
22:09:51  - The resource 'projects/k8s-jenkins-kubemark/global/firewalls/kubemark-5-kubemark-master-https' was not found
```

The resources that were created are named `kubemark-5-master.*`, not `kubemark-5-kubemark-master.*`. This broke between 4:32pm and 4:56pm today although no changes were checked in around then.

I thought Jenkins configs were under version control -- what went wrong here?
@kubernetes/sig-testing @kubernetes/sig-scalability

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #23670

cc @wojtek-t @a-robinson

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by a-robinson** [comment]
LGTM, thanks!

**Comment by ixdy** [comment]
LGTM, thanks!

**Comment by a-robinson** [comment]
Manually merging so that this makes it in during my shift

**Pull request merged**
