### PR TITLE
Speedup generating selflinks for list and watch requests

### PR DESCRIPTION
**Pull request by wojtek-t**
I've seen profiles, where GenerateSelflink was 8-9% of whole cpu usage of apiserver (profiles over 30s). Most of this where spent in getting RequestInfo from the context and creating the context.

This PR changes the API of the GenerateLink method of the namer which results in computing the context and requestInfo only once per LIST/WATCH request (instead of computing it for every single returned element of LIST/WATCH).

@smarterclayton @deads2k - can one of you please take a look?

### CODE REVIEW

**Comment by smarterclayton** [comment]
Seems ok to me, haven't looked deeply but is reasonable.

**Comment by deads2k** [comment]
lgtm. Tests look cranky.  Please re-mention me if something substantive changes.

**Comment by wojtek-t** [comment]
> Tests look cranky. 

Yeah - sorry. I hope it should be fixed now (to many copy-paste in watch - only watch.go changed).

**Comment by deads2k** [comment]
> Yeah - sorry. I hope it should be fixed now (to many copy-paste in watch - only watch.go changed).

still lgtm

**Comment by wojtek-t** [comment]
@k8s-bot kubemark test this

**Comment by wojtek-t** [comment]
@k8s-bot kubemark e2e test this

**Comment by wojtek-t** [comment]
Tests passing - applying label based on comments above.

**Pull request merged**
