### PR TITLE
Cleanup in topology.go

### PR DESCRIPTION
**Pull request by ahadas**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
1. Find the minimal thread number within a core using a
single loop rather than by sorting the thread numbers.
2. Inline getUniqueCoreID#err and Discover#numCPUs variables.
3. Narrow the scope of Discover#coreID and Discover#err variables.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ahadas** [comment]
Trying to resolve the CLA issue

**Comment by ahadas** [comment]
Seems I've been added to the group of _Authorized CNCF Contributors_ (Red Hat)

**Comment by ConnorDoyle** [comment]
/approve
/lgtm

Thanks!

**Pull request merged**
