### PR TITLE
Move funcs of framework to common runtimeclass.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

ref: https://github.com/kubernetes/kubernetes/issues/84380

Move functions in `framework.go` to module `common`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/assigin @oomichi

### CODE REVIEW

**Comment by hwdef** [comment]
/ok-to-test
LGTM

**Comment by hwdef** [comment]
`PreconfiguredRuntimeClassHandler` is used in test/e2e/node/runtimeclass.go
Is it should be handle?

**Comment by jfbai** [comment]
> `PreconfiguredRuntimeClassHandler` is used in test/e2e/node/runtimeclass.go
> Should it be processed?

@hwdef Thanks a lot, my mistake, according to the slack discussion, I think it should not.

**Comment by oomichi** [comment]
`GetLogToFileFunc()` is not used at all, so at least we can remove the function.

**Comment by jfbai** [comment]
/retest

> `GetLogToFileFunc()` is not used at all, so at least we can remove the function.

@oomichi I updated this PRs, and only unused function is removed.

**Pull request merged**
