### PR TITLE
kubeadm: Don't error out on join with --cri-socket override

### LINKED ISSUE #1495: kubeadm join fails when multiple CRI sockets exist
## What keywords did you search in kubeadm issues before filing this one?

```kubeadm-config```

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"archive", BuildDate:"2019-03-29T16:29:07Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.14.0
- **Cloud provider or hardware configuration**: baremetal
- **OS** (e.g. from /etc/os-release): Clear Linux 
- **Kernel** (e.g. `uname -a`): 4.20
- **Others**:

## What happened?

On a node that has 
``` /var/run/dockershim.sock```, and ```/var/run/crio/crio.sock```, ```kubeadm join --cri-socket /var/run/crio/crio.sock``` fails with an error

```
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
```

Passing ```--cri-socket``` has no effect.

## What you expected to happen?

Passing ```--cri-socket``` would resolve the conflict.

## How to reproduce it (as minimally and precisely as possible)?

Have two CRI runtimes running (crio.sock and dockershim.sock present)

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

In the case where newControlPlane is true we don't go through
getNodeRegistration() and initcfg.NodeRegistration.CRISocket is empty.
This forces DetectCRISocket() to be called later on, and if there is more than
one CRI installed on the system, it will error out, while asking for the user
to provide an override for the CRI socket. Even if the user provides an
override, the call to DetectCRISocket() can happen too early and thus ignore it
(while still erroring out).
However, if newControlPlane == true, initcfg.NodeRegistration is not used at
all and it's overwritten later on.
Thus it's necessary to supply some default value, that will avoid the call to
DetectCRISocket() and as initcfg.NodeRegistration is discarded, setting
whatever value here is harmless.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1495

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority critical-urgent
/assign @neolit123
/assign @fabriziopandini

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: Fix a bug where if couple of CRIs are installed a user override of the CRI during join (via kubeadm join --cri-socket ...) is ignored and kubeadm bails out with an error
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for debugging this @rosti
let me know if you want me to send the cherry pick for 1.14.

/lgtm
/hold

**Comment by rosti** [comment]
@neolit123 we'll have to. I also checked 1.13, but the issue is not present in there.

**Comment by neolit123** [comment]
sent cherry pick: https://github.com/kubernetes/kubernetes/pull/76510

**Comment by SataQiu** [comment]
/lgtm
:+1:

**Pull request merged**
