### PR TITLE
[1.17] Update to Golang 1.13.9

### PR DESCRIPTION
**Pull request by justaugustus**
(Cherry pick of https://github.com/kubernetes/kubernetes/pull/89275)

**What type of PR is this?**
/kind feature cleanup
/area dependency

**What this PR does / why we need it**:
- deps: Update to Golang 1.13.9
- build: Remove kube-cross image building

Accompanying kube-cross bump: https://github.com/kubernetes/release/pull/1200

/assign @BenTheElder @liggitt @cblecker @dims @listx
/milestone v1.17
cc: @kubernetes/release-team @kubernetes/release-engineering 
ref: [quarterly updates](https://github.com/kubernetes/release/issues/1134)

**Does this PR introduce a user-facing change?**:

```release-note
- deps: Update to Golang 1.13.9
- build: Remove kube-cross image building
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
Retesting, but it looks like the last few `pull-kubernetes-e2e-gce` failures have been on PV detach:
```
[sig-storage]  PersistentVolumes GCEPD should test that deleting the Namespace of a  PVC and Pod causes the successful detach of Persistent Disk expand_less | 6m1s
-- | --
test/e2e/storage/persistent_volumes-gce.go:153 Mar 24 08:55:46.073: Unexpected error:     <*errors.errorString \| 0xc0000a1960>: {         s: "timed out waiting for the condition",     }     timed out waiting for the condition occurred test/e2e/storage/persistent_volumes-gce.go:160
```

@kubernetes/sig-storage-bugs -- Can you take a look?

/retest

**Comment by justaugustus** [comment]
(FWIW, these failures did not happen on master or the 1.18, 1.16 branches)

**Comment by msau42** [comment]
The namespace deletion test is due to https://github.com/kubernetes/kubernetes/issues/86417, which got exposed when we removed test flake retries. The test case itself got the [flaky] tag added so it doesn't run in regular pull jobs anymore

**Pull request merged**
