### PR TITLE
fetch cni plugins from GitHub releases

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

Fetch CNI plugins from GitHub releases instead of the k8s-artifacts-cni GCS bucket.

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/k8s.io/issues/7584

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ameukam** [comment]
FYI @kubernetes/release-engineering 

/priority important-soon

**Comment by dims** [comment]
/hold

@upodroid did you really mean 1.32? need this milestone to be applied by the release folks ( cc @fsmunoz )

**Comment by upodroid** [comment]
> did you really mean 1.32? need this milestone to be applied by the release folks ( cc @fsmunoz )

Yes, this change isn't user facing and doesn't affect tests.

**Comment by ameukam** [comment]
@dims @SergeyKanzhelev PTAL for approval.

**Comment by dims** [comment]
/approve
/lgtm

please feel free to remove hold when ready!

**Pull request merged**
