### PR TITLE
Honor --use-service-account-credentials and warn when missing private key

### LINKED ISSUE #50275: User "system:kube-controller-manager" cannot create replicasets.extension
/kind bug

**What happened**:
I'm unable to set up a k8s cluster with RBAC due authorization errors (guessing)

```
$ journalctl -fu kube-controller-manager
-- Logs begin at Mon 2017-08-07 14:42:49 PDT. --
Aug 07 15:24:31 k8s-master kube-controller-manager[18913]: I0807 15:24:31.467604   18913 ttlcontroller.go:269] Failed to change ttl annotation for node k8s-master: User "system:kube-controller-manager" cannot patch nodes at the cluster scope. (patch nodes k8s-master)
Aug 07 15:24:31 k8s-master kube-controller-manager[18913]: E0807 15:24:31.468274   18913 ttlcontroller.go:219] User "system:kube-controller-manager" cannot patch nodes at the cluster scope. (patch nodes k8s-master)
Aug 07 15:24:33 k8s-master kube-controller-manager[18913]: I0807 15:24:33.624584   18913 ttlcontroller.go:269] Failed to change ttl annotation for node k8s-node-2: User "system:kube-controller-manager" cannot patch nodes at the cluster scope. (patch nodes k8s-node-2)
```
Nor set up kube-dns
```
$ kubectl describe deployment -n kube-system
...
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  48m           46m             16      deployment-controller                   Warning         ReplicaSetCreateError   Failed to create new replica set "kube-dns-3143770262": User "system:kube-controller-manager" cannot create replicasets.extensions in the namespace "kube-system". (post replicasets.extensions)
```

**How to reproduce it (as minimally and precisely as possible)**:
Run each component with these options:
```
/usr/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds \
  --advertise-address=FD00::0B \
  --allow-privileged=true \
  --authorization-mode=Node,RBAC \
  --bind-address=0.0.0.0 \
  --cert-dir=/var/run/kubernetes \
  --client-ca-file='/var/lib/kubernetes/ca-k8s.pem' \
  --enable-swagger-ui=false \
  --etcd-cafile='/var/lib/kubernetes/ca-etcd.pem' \
  --etcd-certfile='/var/lib/kubernetes/etcd-k8s-api-server.pem' \
  --etcd-keyfile='/var/lib/kubernetes/etcd-k8s-api-server-key.pem' \
  --etcd-servers=https://[FD00::0B]:2379 \
  --kubelet-certificate-authority='/var/lib/kubernetes/ca-k8s.pem' \
  --kubelet-client-certificate='/var/lib/kubernetes/k8s-kubelet.pem' \
  --kubelet-client-key='/var/lib/kubernetes/k8s-kubelet-key.pem' \
  --kubelet-https \
  --service-cluster-ip-range=FD03::/112 \
  --service-node-port-range=30000-32767 \
  --tls-ca-file='/var/lib/kubernetes/ca-k8s.pem' \
  --tls-cert-file='/var/lib/kubernetes/k8s-api-server.pem' \
  --tls-private-key-file='/var/lib/kubernetes/k8s-api-server-key.pem' \
  --v=2
```

```
/usr/bin/kubelet \
  --allow-privileged=true \
  --cloud-provider= \
  --cluster-dns=FD03::A \
  --cluster-domain=cluster.local \
  --container-runtime=docker \
  --docker=unix:///var/run/docker.sock \
  --kubeconfig=/var/lib/kubelet/kubelet.kubeconfig \
  --make-iptables-util-chains=false \
  --network-plugin=cni \
  --node-ip=FD00::0B \
  --register-node=true \
  --require-kubeconfig=true \
  --serialize-image-pulls=false \
  --v=2
```

```
/usr/bin/kube-controller-manager \
  --cluster-cidr=FD02::C0A8:0000:0:0/96 \
  --cluster-name=kubernetes \
  --configure-cloud-routes=false \
  --kubeconfig='/var/lib/kubernetes/controller-manager.kubeconfig' \
  --leader-elect=true \
  --node-cidr-mask-size 112 \
  --use-service-account-credentials \
  --service-cluster-ip-range=FD03::/112 \
  --v=2
```

```
/usr/bin/kube-scheduler --kubeconfig=/var/lib/kubernetes/scheduler.kubeconfig --v=2
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**:
PRs #43586 and #45551 were patched against `v1.7.3` and kubelet + kube-controller-manager are being executed with those patches in place. Since those patches are IPv6 related, they should not affect the errors I'm seeing.

**Environment**:
- Cloud provider or hardware configuration**: `Vagrant box`
- OS (e.g. from /etc/os-release): `Ubuntu 16.10`
- Kernel (e.g. `uname -a`): `Linux cilium-k8s-master 4.9.17-040917-generic`
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #50275 by logging a warning and failing to start rather than continue to run ignoring the user's specified config

### CODE REVIEW

**Comment by spiffxp** [comment]
/assign @lavalamp 
assigning for approval

**Comment by spiffxp** [comment]
/test pull-kubernetes-e2e-gce-etcd3
😑

**Comment by wlan0** [comment]
@liggitt There seems to be a bug here - shouldn't the check be 

```
if len(s.ServiceAccountKeyFile) == 0 {
```
instead of 
```
if len(s.ServiceAccountKeyFile) > 0 {
```

**Comment by liggitt** [comment]
You're right. It should be flipped to decide whether to print the warning

**Pull request merged**
