### PR TITLE
Include BGPConfiguration

### PR DESCRIPTION
**Pull request by satyasm**
Needed for calico 2.x to 3.x upgrade.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Without this, k8s upgrades that go from older to newer version of calico break.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Include CRD for BGPConfigurations, needed for calico 2.x to 3.x upgrade.
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Looks like a dupe of this guy: https://github.com/kubernetes/kubernetes/pull/71682

:D I'll close mine

**Comment by jankovad1998-sudo** [comment]
923361e58bbed7b102533b3c3e770e69bec0514f

**Pull request merged**
