### PR TITLE
add loging and bump timers to avoid races

### PR DESCRIPTION
**Pull request by aojea**
/kind flake

```release-note
NONE
```

Bump the timers to avoid races and log  errors, the errors are not needed for asserting the test since we are not sending data a, only processing heartbeats, but they can be usefult to troubleshoot flakes like the reported here https://github.com/kubernetes/kubernetes/issues/120684

### CODE REVIEW

**Comment by liggitt** [comment]
thanks, did you run this with -race / stress to make sure this resolved the issue?

/retest

**Comment by pacoxu** [comment]
Did we disable the retest CI bot? I recently found that PR failed for flake CI failure will not be retested automatically by the CI robot anymore.

**Pull request merged**
