### PR TITLE
Use canonical import path in client-gen input-base

### PR DESCRIPTION
**Pull request by roycaihw**
/kind bug

The [parameter](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/client-gen/args/args.go#L80) `--input-base` in client-gen is used to [compose](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/client-gen/args/gvpackages.go#L129) the [full qualified package path](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/client-gen/types/types.go#L47-L48), which is later used with `gengo` to [locate the package source and extract package comments](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go#L282-L283). 

Because `gengo` always [canonicalizes](https://github.com/kubernetes/gengo/blob/c0d492a0f3cab707b841450d5b5919720682da31/parser/parse.go#L854-L862) a package path before [adding it to the universe](https://github.com/kubernetes/gengo/blob/c0d492a0f3cab707b841450d5b5919720682da31/parser/parse.go#L259-L290), the universe doesn't understand non-canonical paths and will [return a empty package](https://github.com/kubernetes/gengo/blob/c0d492a0f3cab707b841450d5b5919720682da31/types/types.go#L267-L285). As a result the package comments were lost and group overrides didn't happen for APIs under `k8s.io/kubernetes/vendor/k8s.io/api`.

It was okay for most APIs because the [old group name](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/hack/update-codegen.sh#L47) (e.g. "**flowcontrol**/v1alpha1") is the same as the [override group name](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go#L285) ("**flowcontrol**.apiserver.k8s.io/v1alpha1"). However, for the StorageVersion API the old group name (**apiserverinternal**/v1alpha1) and the override group name (**internal**.apiserver.k8s.io/v1alpha1) are different (ref https://github.com/kubernetes/kubernetes/pull/93087). This caused error  because other generators like [informer-gen](https://github.com/kubernetes/kubernetes/blob/fbbc3ed3595287cc8daf684a39ad9c26a90ca7eb/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go#L125) honored the package comments. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig api-machinery
/cc @caesarxuchao 
/priority important-soon

### CODE REVIEW

**Comment by caesarxuchao** [comment]
cc @sttts

**Comment by sttts** [comment]
I don't see any fixed output of the generators. Where can I see that?

**Comment by roycaihw** [comment]
> I don't see any fixed output of the generators. Where can I see that?

It doesn't affect most of the existing APIs as I explained in https://github.com/kubernetes/kubernetes/pull/93164#issue-450572649. That's why there is no change in the generated clients.

It affects https://github.com/kubernetes/kubernetes/pull/93087. Here is the difference w/ & w/out this change: https://github.com/roycaihw/kubernetes/compare/storage-version/move-types...roycaihw:storage-version/move-types-without-clientgen-fix

**Comment by liggitt** [comment]
this will be moved back into the milestone as part of the [phased reopen for 1.20 merges](https://docs.google.com/document/d/1yI7o7R2bOB7QtkHUFMHMb5XObiJmzIAnJPuxhdAX-CA/edit)

**Pull request merged**
