### PR TITLE
Adding subresource to swagger route docs

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/7100

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @madhuri-rai07

**Comment by bgrant0607** [comment]
Thanks.

Please capitalize the subresource when generating the nicknames, so the result is camelCase (e.g., Finalize rather than finalize).

Please also do this to the http methods for the connect operations (e.g., Get rather than GET).

**Comment by nikhiljindal** [comment]
Thanks! Done. PTAL.

**Comment by bgrant0607** [comment]
LGTM

**Comment by nikhiljindal** [comment]
@krousey Can I haz a merge, please?

**Comment by krousey** [comment]
@nikhiljindal Sorry. I think I merged a conflict before I got to this. Please rebase.

**Comment by nikhiljindal** [comment]
Rebased

**Pull request merged**
