### PR TITLE
Remove Scale e2e test

### PR DESCRIPTION
**Pull request by gmarek**
Solves #11658

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @rrati @jayunit100

**Comment by gmarek** [comment]
@thockin @ixdy

**Comment by mbforbes** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/11658#issuecomment-123727793 is worth noting here:

> IMO [the scale test] is useless now. In my understanding the reason for [it] was to verify that concurrent RC creation works as expected. This is covered by load.go test right now. [I created] #11691 to remove this test.

**Comment by mbforbes** [comment]
This LGTM but I'd like a stamp from @ixdy too.

**Comment by thockin** [comment]
LGTM

**Comment by wojtek-t** [comment]
LGTM

**Pull request merged**
