### PR TITLE
[go] Bump images, dependencies and versions to go 1.20.2

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.20.2

/assign @liggitt @dims @saschagrunert @ameukam 
cc @kubernetes/release-managers 

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/2948

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.20.2
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/sig release

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
