### PR TITLE
Fix: Cronjob will no longer works when updated

### PR DESCRIPTION
**Pull request by yanhongchang**
when update cronjob after posting a job and before update the status, 
the cronjob status will update failed, but the job has been created, 
the next sync time, will create again and get a job without nothing, 
then the nil job  will update into the cronjob status active list.
the cronjob will do not work any more.  

Fixes # 112092 

Signed-off-by: Hongchang Yan <yanhongchang5@163.com>

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
QQ: why is it closed?

**Comment by yanhongchang** [comment]
> QQ: why is it closed?

move to another issue, please see: https://github.com/kubernetes/kubernetes/pull/112275

**Pull request closed without merging**
