### PR TITLE
[client-go] Fake Dynamic Client

### PR DESCRIPTION
**Pull request by DirectXMan12**
This commit converts `"k8s.io/client-go/dynamic".Client` to an interface, and implements fake versions of both `ClientPool` and `Client`.  This allows components which make uses of these clients to be tested in the same way that clientset-based components can be tested, using the standard `testing.Fake` machinery.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
encountered this while trying to write unit tests for the custom metrics adapter for Prometheus.  I'm still in the progress of writing those tests and making sure this is sufficient, but I think it should be.

**Comment by krousey** [comment]
I don't think dynamic client should return an interface just to enable testing. I think the library that wants to test it's interaction with the dynamic client should assign the return value from `New` to an interface. That being said, I'm going to re-assign this to someone on the api machinery team.

**Comment by DirectXMan12** [comment]
> I don't think dynamic client should return an interface just to enable testing. 

That's what the "normal" clients do.  I was under the impression that it was a pretty well-established pattern.

**Comment by krousey** [comment]
> That's what the "normal" clients do. I was under the impression that it was a pretty well-established pattern.

That's true, it is a pattern. I have the *opinion* that it's a mistake, but not a completely terrible one. As it is the current pattern, it would fit it. I'm also not the reviewer (anymore).

**Comment by soltysh** [comment]
I'd stick with the pattern we already have in place in the generated clientset, where there's a `Interface` and `Client` implements that, (see [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/kubernetes/clientset.go)). Just my $0.02.

**Comment by DirectXMan12** [comment]
> I'd stick with the pattern we already have in place in the generated clientset, where there's a Interface and Client implements that, (see here). Just my $0.02.

I wanted to avoid a mass renaming, and wanted to follow the pattern established with `ClientPool` itself, which was already an interface.

**Comment by DirectXMan12** [comment]
ping @kubernetes/sig-api-machinery-pr-reviews when you get a chance

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref https://github.com/kubernetes/test-infra/pull/2931

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
ref: kubernetes/test-infra#2932

**Comment by sttts** [comment]
> I'd stick with the pattern we already have in place in the generated clientset, where there's a Interface and Client implements that

I agree, Client as struct, Interface as interface.

Usually, the pattern is that consumers take an interface, but producers return concrete structs.

**Comment by DirectXMan12** [comment]
@sttts ok, I've made the interface for `Client` `Interface`, which `ResourceClient` has `ResourceInterface`.  `ClientPool` stays the same as it currently is.  Look better?

**Comment by sttts** [comment]
I like the new shape. It's the same we have for the static clients. @soltysh @krousey any objections?

**Comment by DirectXMan12** [comment]
the bot is getting antsy.  Does anyone else have any comments on this?

**Comment by sttts** [comment]
@smarterclayton approved?

**Comment by DirectXMan12** [comment]
This looks like it might actually be an issue with some code having gotten updated in the mean time.  I'll rebase shortly.

**Comment by DirectXMan12** [comment]
ok, this should fix the test issue -- someone updated the signature of DynamicClient in the mean time ;-).

**Comment by caesarxuchao** [comment]
golint failures:

```
Errors from golint:
W0721 23:23:06.250] staging/src/k8s.io/client-go/dynamic/fake/client.go:36:6: type name will be used as fake.FakeClient by other packages, and that stutters; consider calling this Client
W0721 23:23:06.250] staging/src/k8s.io/client-go/dynamic/fake/client.go:68:6: type name will be used as fake.FakeResourceClient by other packages, and that stutters; consider calling this ResourceClient
W0721 23:23:06.250] staging/src/k8s.io/client-go/dynamic/fake/client_pool.go:30:6: type name will be used as fake.FakeClientPool by other packages, and that stutters; consider calling this ClientPool
W0721 23:23:06.250] staging/src/k8s.io/client-go/dynamic/fake/client_pool.go:34:1: comment on exported method FakeClientPool.ClientForGroupVersionResource should be of the form "ClientForGroupVersionResource ..."
W0721 23:23:06.250] 
W0721 23:23:06.251] Please review the above warnings. You can test via "golint" and commit the result.
W0721 23:23:06.251] If the above warnings do not make sense, you can exempt this package from golint
W0721 23:23:06.251] checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
```

**Comment by DirectXMan12** [comment]
wow, golint is *supremely* nitpicky

**Comment by DirectXMan12** [comment]
I'm adding this to the golint_failures file, since it follows the pattern in other fake clients

**Pull request merged**
