### PR TITLE
Fix typos and grammatical errors in comments and variables

### PR DESCRIPTION
**Pull request by mbssaiakhil**
Fix typo in comment in garbagecollector

### CODE REVIEW

**Comment by liggitt** [comment]
If you have several typos fixed, it's probably best to combine those into a single PR instead of multiple PRs that each touch one file

**Comment by mbssaiakhil** [comment]
@liggitt, closed the other PRs, consolidated all the changes to this PR. Kindly review and merge this PR.

**Comment by liggitt** [comment]
Thanks. go ahead and squash commits as well.

**Pull request merged**
