### PR TITLE
Fix issue template to read more clearly

### PR DESCRIPTION
**Pull request by beeradb**
**What this PR does / why we need it**:

This PR fixes the github issue template. Currently the wording is very awkward.

### CODE REVIEW

**Comment by cblecker** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40614#-:-KbaUNlDNMv6rOYPLvHe:bb6ywmx)*

**Comment by brendandburns** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by brendandburns** [comment]
@k8s-bot unit test this

**Comment by brendandburns** [comment]
@k8s-bot unit test this

**Pull request merged**
