### PR TITLE
Port-forward: use out and error streams instead of glog

### PR DESCRIPTION
**Pull request by csrwng**
Switches use of glog with command out and error streams

### CODE REVIEW

**Comment by csrwng** [comment]
@ncdc ptal

**Comment by wojtek-t** [comment]
@csrwng - what is the motivation for this change?

**Comment by csrwng** [comment]
@wojtek-t 2 reasons: 1) the default glog format includes module and line number which is great for a debug log but not for interactive command output and 2) it makes the portforward command more usable from other commands if those commands can supply the output streams.

**Comment by ncdc** [comment]
@k8s-bot this this

**Comment by ncdc** [comment]
@k8s-bot unit test this

**Comment by eparis** [comment]
@k8s-bot add to whitelist

**Comment by eparis** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Comment by ncdc** [comment]
@csrwng not sure what the exact failures are, given the build log is missing. You may want to download all the individual JUnit test artifacts to search for the failure :-/

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@ixdy this has failed e2e 3 times but there's no build log. Any ideas what's going on?

**Comment by ixdy** [comment]
@ncdc see #17282

**Comment by ncdc** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@csrwng finally got the failure info:

```
• Failure [33.408 seconds]
Port forwarding
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:240
  With a server that expects a client request
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:203
    should support a client that connects, sends data, and disconnects [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:202

    Nov 17 09:11:49.279: Failed to parse kubectl port-forward output: E1117 09:11:49.278868    9382 portforward.go:207] Unable to create listener: Error listen tcp6 [::1]:38007: bind: cannot assign 

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:104
```

Do you think your output changes would cause this? Can you try to run this e2e locally?

**Comment by csrwng** [comment]
@ncdc yes, I'll try it locally later today. Thank you much for getting the log of the failure. And yes, it looks like the e2e test is expecting the old output of the portforward command, so it needs to be fixed.

**Comment by csrwng** [comment]
Fixed the e2e test to expect output on stdout instead of stderr

**Comment by ncdc** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
LGTM. @liggitt care to sanity check?

**Comment by ncdc** [comment]
unit/int flake:

```
F0118 19:52:47.704810    1973 controller.go:84] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: serviceipallocations "" cannot be updated: the provided resource version does not match
!!! [0118 19:54:50] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/healthz; tried 120 waiting 1 between each
!!! Error in ./hack/test-update-storage-objects.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-update-storage-objects.sh:48 startApiServer(...)
  2: ./hack/test-update-storage-objects.sh:123 main(...)
Exiting with status 1
```

@k8s-bot unit test this

**Comment by bgrant0607** [comment]
We need to decide if this is in or out ASAP.

**Comment by ncdc** [comment]
I think this can wait until 1.3. You ok with that @csrwng @liggitt ?

**Comment by liggitt** [comment]
yeah

**Comment by csrwng** [comment]
that's fine with me... will rebase as well

**Comment by fejta** [comment]
Please rebase and push

**Comment by csrwng** [comment]
rebased

**Pull request merged**
