### PR TITLE
Automated cherry pick of #38375

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #38375 on release-1.5.

#38375: Add image cache.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @saad-ali This is the pr I mentioned earlier which should resolve #38373 and https://github.com/kubernetes/kubernetes/issues/38710, and should cherrypicked into 1.5 release.

**Comment by saad-ali** [comment]
Ack. Will merge after 1.5.1 is out

**Pull request merged**
