### PR TITLE
Rollback "validate-cluster.sh" to previous version.

### PR DESCRIPTION
**Pull request by fabioy**
Current version breaks some CI tests. Will roll forward once new release is cut and deployed.

### CODE REVIEW

**Comment by roberthbailey** [comment]
For those following along at home, this breaks our version-skewed e2e tests running against released versions of kubernetes (e.g. 0.15.0) which don't yet have the new component-status API but do still have the /validate endpoint.

**Comment by roberthbailey** [comment]
LGTM. Will merge on green.

**Comment by roberthbailey** [comment]
Shippable passing. Merging.

**Comment by dchen1107** [comment]
I think simply rolling back #7124 will break cluster_validation since I removed fqdn dependency already. I will send a fix shortly. @roberthbailey

**Comment by dchen1107** [comment]
never mind. It works.

**Pull request merged**
