### PR TITLE
Use named custom func

### PR DESCRIPTION
**Pull request by dtaniwaki**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

cobra can handle a custom function name for `__custom_func` as of https://github.com/spf13/cobra/commit/6fd8e29b07d8242ebe2888060fede5766e240c25. We should use it to avoid conflictions with other command line clients w/ the cobra's completion.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

**Special notes for your reviewer**:

I did the following steps to update the cobra revision.

```bash
$ hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/spf13/cobra'
$ hack/run-in-gopath.sh go get github.com/mitchellh/go-homedir
$ hack/run-in-gopath.sh go get -d github.com/spf13/cobra
$ hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/spf13/cobra checkout 6fd8e29'
$ hack/run-in-gopath.sh hack/godep-save.sh
```

**Does this PR introduce a user-facing change?**:

```release-note
Avoid __custom_func conflictions with other cobra completions.
```

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test
/priority backlog
/cc @kubernetes/sig-cli-maintainers @eparis 

This should be reviewed by sig-cil first. Dep bump looks okay.

**Comment by cblecker** [comment]
You can’t manually modify `vendor/`. CI failure is legitimate.

**Comment by dtaniwaki** [comment]
`hack/verify-staging-godeps.sh`, which failed in the CI, succeeds in my local. I will retry the tests.

/retest

**Comment by cblecker** [comment]
@dtaniwaki Try rebasing on master, and rerunning `hack/update-staging-godeps.sh`.

**Comment by dtaniwaki** [comment]
I realized I haven't updated the dependencies in staging by `./hack/update-staging-godeps.sh`. Will do.

**Comment by dtaniwaki** [comment]
@cblecker Thanks for your help. Finally, the CI succeeded!

**Comment by cblecker** [comment]
Looks like this is ready for sig-cli review.

**Comment by dtaniwaki** [comment]
@kubernetes/sig-cli-maintainers Could someone review this PR?

**Comment by dtaniwaki** [comment]
Could you someone review this PR?

**Comment by dtaniwaki** [comment]
I'm closing this issue as it's handled in https://github.com/kubernetes/kubernetes/pull/70470.

**Pull request closed without merging**
