### PR TITLE
Define the ARCH explictly for amd64

### LINKED ISSUE #81920: image tags is not correctly defined on arm paltform
**What happened**:
some of base images support multi-arch,  if no platform specified, the image pulled will actually reflect where the operation is performed, current implementation always assume the default platform is amd64 which make the tags is not correctly defined.

for example,

on arm64 platform, here is what I got after build the image of ipc-utils, 
```
# docker inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
...
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 9732491,
        "VirtualSize": 9732491,
        "GraphDriver": {
  ...
```

**What you expected to happen**:
tag should be defined correctly

**How to reproduce it (as minimally and precisely as possible)**:
on arm64 platform, 
```
cd /test/images.
make all WHAT=ipc-utils
docker image ls | grep ipc-utils
docker image inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: all arch except x86 
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
The change will make sure the image tag is correct on the platform
other than amd64.

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81920

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
For the platforms other than amd64, images built from "test/images" directory which are tagged with "amd64" will be exactly the right images, multi-arch images implicitly inspected from the building platforms will not be used anymore.

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
seems good to me, do we have a reason why we weren't doing that before?

@chendave please add detailed explanation for the change under:
`Does this PR introduce a user-facing change?:`

**Comment by chendave** [comment]
@neolit123 thanks, updated.

**Comment by mkumatag** [comment]
This will not fix the issue, we need this architecture in the docker image otherwise you will end up pulling the host architecture's docker image when you are building that image in some other arch. e.g: if you are building this script on arm then without arch `alpine` image in the amd option will pull arm based alpine image which is wrong.

Hence closing this issue.

/close

**Comment by mkumatag** [comment]
> This will not fix the issue, we need this architecture in the docker image otherwise you will end up pulling the host architecture's docker image when you are building that image in some other arch. e.g: if you are building this script on arm then without arch `alpine` image in the amd option will pull arm based alpine image which is wrong.
> 
> Hence closing this issue.

sorry, I interpreted in a wrong way, I see your need! All these days we just supported cross-building only on amd machine hence we din't had amd explicitly.

/reopen

**Comment by mkumatag** [comment]
Just this change is not good enough to support cross-building these images on non-amd architecture, we may need to modify https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh#L92 to pull proper qemu(right now its pulling only x86 qemu binary which emulates any target arch.)

**Note**: qemu emulation support is not that great on non-amd architectures as of now. I prefer sticking to cross-build these images on amd architecture only to avoid any other unknowns. Just for the sake of completeness, you can work on this PR.

**Comment by chendave** [comment]
@mkumatag , thanks for the comments!

If cross-building on non-amd architectures doesn't support well (which is true for most of case except amd),  it should not end up with an image built successfully while it is actually pulling a wrong base image, just like https://github.com/kubernetes/kubernetes/issues/81920 said,  build ipc-utils for amd64 should fail on arm64 instead of a wrong image with a improper tag given created.

**Comment by listx** [comment]
/remove-lifecycle stale

@chendave @mkumatag Along with https://github.com/kubernetes/kubernetes/pull/82778 are these changes still necessary? I know it's been taking a while to review these changes but let's see if they are still warranted...?

Otherwise feel free to close this and the other one.

**Comment by listx** [comment]
/remove-lifecycle stale

@chendave @mkumatag Along with https://github.com/kubernetes/kubernetes/pull/82778 are these changes still necessary? I know it's been taking a while to review these changes but let's see if they are still warranted...?

Otherwise feel free to close this and the other one.

**Comment by chendave** [comment]
@listx , I'd hope https://github.com/kubernetes/kubernetes/pull/82778 to merged, so that I can close this one.

I will rebase 82778, could you pls review that one after rebasing?

**Pull request closed without merging**
