### PR TITLE
[Do-not-merge] Experiment with increased scheduler concurrency

### PR DESCRIPTION
**Pull request by shyamjvs**
/hold
/do-not-merge
/assign

### CODE REVIEW

**Comment by wgliang** [comment]
This is an interesting experiment and I have tried it. :-)
#59460

**Comment by shyamjvs** [comment]
@wgliang Interesting.. thanks for pointing to that! Could you clarify on what configuration (master size, cluster size, etc) you used for those experiments and what kind of load/tests you ran?

**Comment by shyamjvs** [comment]
Let me close this PR as it has caused screw ups with presubmits due to a blooper. I'll test it manually.

**Pull request closed without merging**
