### PR TITLE
adjust disk usage relative to the request

### PR DESCRIPTION
**Pull request by yingchunliu-zte**
Signed-off-by: yingchunliu-zte <liu.yingchun@zte.com.cn>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
func disk(stats statsFunc, fsStatsToMeasure []fsStatsType, diskResource v1.ResourceName) cmpFunc {
	return func(p1, p2 *v1.Pod) int {
		...
		p1Disk := p1Usage[diskResource]
		p2Disk := p2Usage[diskResource]
		p1Request := v1resource.GetResourceRequestQuantity(p1, v1.ResourceEphemeralStorage)
		p1Disk.Sub(p1Request)
		p2Request := v1resource.GetResourceRequestQuantity(p2, v1.ResourceEphemeralStorage)
		p2Disk.Sub(p2Request)
		...
	}
}
v1.ResourceEphemeralStorage should be replaced by diskResource in the code above

### CODE REVIEW

**Comment by pacoxu** [comment]
It looks valid to me.

https://github.com/kubernetes/kubernetes/commit/db99c20a9a9dc7db82d236e7cc2ff08c65c269ef#diff-7a6f62753a21b26d9fd66a5242810642ea5e30536f1fc44266072da5f067de0cL684-R675
At first, disk() are using `v1.ResourceEphemeralStorage`.

https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/pkg/kubelet/eviction/helpers.go#L957-L971
However, the diskResource now can be `v1.ResourceEphemeralStorage` or `inodes`.
```
	resourceInodes v1.ResourceName = "inodes"
```

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Review by yangjunmyfm192085 — COMMENTED** [review]
/release-note-none

**Comment by yingchunliu-zte** [comment]
> /test pull-kubernetes-e2e-kind

/test pull-kubernetes-e2e-kind

**Pull request closed without merging**
