### PR TITLE
Register metav1.GetOptions with federation APIs.

### PR DESCRIPTION
**Pull request by madhusudancs**
PR #37693 missed a spot.

cc @kubernetes/sig-federation @nikhiljindal

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Fixed the labels. Should be good to merge now

**Comment by nikhiljindal** [comment]
Fixes #38585

**Comment by wojtek-t** [comment]
@nikhiljindal @madhusudancs - thanks for fixing it. And sorry for breakage.

**Comment by madhusudancs** [comment]
@wojtek-t no worries. This shows the urgency for reliable per-PR federation tests. We have one, but that takes too long.

**Comment by wojtek-t** [comment]
> @wojtek-t no worries. This shows the urgency for reliable per-PR federation tests. We have one, but that takes too long.

+100 - having such per-PR would make more people think about federation and would avoid breaking federtion.

**Pull request merged**
