### PR TITLE
fix issue(#50821)Add image check, if image not changed, transform false

### LINKED ISSUE #50820: The rescheduler can not be started up due to the stdout point to a directory
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
when create rescheduler resources with https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest, find the pod started failed due to the rescheduler.log was a directory.

**What you expected to happen**:
The pod should be started and should use -logtostderr to output the log to a file.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #50821: kubectl set image report an error when always set same image
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
```
admindeMacBook-Pro-2:kubectl admin$ ./kubectl set image daemonset test *=nginx:1.9.0
daemonset "test" image updated
admindeMacBook-Pro-2:kubectl admin$ ./kubectl set image daemonset test *=nginx:1.9.0
error: daemonsets/test no kind "DaemonSet" is registered for version "apps/v1beta1"
```
and i found error in ```return runtime.Encode(o.Encoder, info.Object)```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): i use laster master kubectl
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
closes #50821 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@zjj2wry seems you are referring to a wrong bug no?

**Comment by zjj2wry** [comment]
@gyliu513 updated, thanks

**Comment by smarterclayton** [comment]
Please add a test.

**Comment by zjj2wry** [comment]
@smarterclayton i add some cmd test for this. don't know this small enough to you~.~

**Comment by smarterclayton** [comment]
Yes that's sufficient 

/lgtm

**Pull request merged**
