### PR TITLE
Increase waiting time (120s) for docker startup in health-monitor.sh

### PR DESCRIPTION
**Pull request by dchen1107**
Fix the issue of killing docker again when startup takes longer time on overloaded nodes.

### CODE REVIEW

**Comment by yujuhong** [comment]
Would like to see some measurements, but besides that, lgtm

**Comment by vishh** [comment]
Is two minutes adequate?

**Comment by dchen1107** [comment]
Choosing two minutes is based on Daniel's tests: The node has ~100 pods.

**Pull request merged**
