### PR TITLE
Fix golint for kubectl top

### PR DESCRIPTION
**Pull request by horis233**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint issues in staging/src/k8s.io/kubectl/pkg/cmd/top

1. Add comments for exported functions.
2. Remove `Top` prefix in `TopNodeOptions` and `TopPodOptions`.
3. Remove `else` after return.

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zhouya0** [comment]
/ok-to-test
Is this dup of https://github.com/kubernetes/kubernetes/pull/78141?

**Comment by horis233** [comment]
@zhouya0 
Yes, it is duplicate. I will close it.

**Comment by horis233** [comment]
@zhouya0 Reopen this PR, I found the PR #78141 isn't merged.

**Comment by horis233** [comment]
Because the `kubectl top` is updated recently, I will rebase and create a new PR.

**Pull request closed without merging**
