### PR TITLE
Cherry-pick of #110853:  filter out unsatisfied nodes when calling AddPod in PodTopologySpread

### PR DESCRIPTION
**Pull request by kerthcet**
Cherry pick of https://github.com/kubernetes/kubernetes/pull/110853 on release-1.22.

https://github.com/kubernetes/kubernetes/pull/110853: Fix: filter out unsatisfied nodes when calling AddPod in PodTopologySpread

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
Fixed potential scheduler crash when scheduling with unsatisfied nodes in PodTopologySpread.
```

### CODE REVIEW

**Comment by kerthcet** [comment]
/sig scheduling
cc @ahg-g @alculquicondor

**Comment by Verolop** [comment]
@Huang-Wei your lgtm is required to approve the tests changes you requested so we can merge this, along with https://github.com/kubernetes/kubernetes/pull/110853 . Thanks!

**Comment by Huang-Wei** [comment]
/lgtm

@Verolop Good to go now.

**Pull request merged**
