### PR TITLE
Remove packages which aren't relied on by heapster anymore.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Do the TODO:
```
// TODO apimachinery remove this empty package.  Godep fails without this because heapster relies
// on this package.  This will allow us to start splitting packages, but will force
// heapster to update on their next kube rebase.
```

These packages aren't relied on by heapster anymore. This PR removes them. This is a followup of #48410.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: #48386 #48410

**Special notes for your reviewer**:
/cc @deads2k 
/kind cleanup

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/assign @lavalamp
for approval, thanks!

**Comment by luxas** [comment]
Yay! Didn't look deeply into exactly which pkgs you removed here, but I think this is fine.
Anyway, always nice to see PRs of this kind :)

**Comment by xiangpengzhao** [comment]
Thanks, @luxas! :smile:

**Comment by deads2k** [comment]
I'm very happy to see these go.  

@wojtek-t I'm not sure if @lavalamp is back.  Is there a way to double-check the verify-godeps before we merge this?  It's the only risk I know of since it has failed *after* a package was removed before.

/lgtm

**Comment by xiangpengzhao** [comment]
Thanks @deads2k ! 

I ran `hack/verify-godeps.sh` as you mentioned in https://github.com/kubernetes/kubernetes/pull/48410#issuecomment-312639272, it passed. 

I also looked for the importing of two of the removed packages in heapster repo, they are not imported anymore.

I don't know if there are other ways to confirm your concern :)

**Comment by deads2k** [comment]
> I ran hack/verify-godeps.sh as you mentioned in #48410 (comment), it passed.
> 
> I also looked for the importing of two of the removed packages in heapster repo, they are not imported anymore.

That covers it for me.  @wojtek-t is in europe, but I've assigned him for approval.

**Comment by xiangpengzhao** [comment]
Thanks @deads2k !

**Comment by wojtek-t** [comment]
Great - I was waiting for that PR.

/approve

**Pull request merged**
