### PR TITLE
fix vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured staticcheck

### PR DESCRIPTION
**Pull request by habibrosyad**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes `vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured` staticcheck errors.

**Which issue(s) this PR fixes**:

Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by spiffxp** [comment]
/retest
Hm, both of these hit pod scheduling timeout
- pull-kubernetes-e2e-kind 
- pull-kubernetes-integration

**Comment by habibrosyad** [comment]
@lavalamp I suppose you mistyped `/approve`(r)?

**Comment by lavalamp** [comment]
sorry!

/approve

**Pull request merged**
