### PR TITLE
[Manual cherrypick #46197 to 1.7] Fix clusterip for ExternalName service test

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Fix failing 1.7 -> 1.8 upgrade suite. See https://github.com/kubernetes/kubernetes/issues/50274 and https://github.com/kubernetes/kubernetes/pull/52759.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/assign @xiangpengzhao @bowei @@abgworrall

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Manual cherrypick of #46197.

**Comment by abgworrall** [comment]
@MrHohn , can you get lgtm+approval for this, before we label it approved for 1.7 ?

**Comment by MrHohn** [comment]
@abgworrall Ack, will ping you again after lgtmed+approved.

/retest

**Comment by MrHohn** [comment]
@abgworrall LGTMed and approved. Could we now have approval for 1.7? Thanks.

**Comment by xiangpengzhao** [comment]
@MrHohn LGTM, thanks for chrry-picking this. I didn't know we can partially cherry-pick a PR when I created #52759 :)

**Pull request merged**
