### PR TITLE
scheduler: rename metric name of pending pods

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup
/sig scheduling
/sig instrumentation
/assign @brancz 

**What this PR does / why we need it**:

This is a followup of https://github.com/kubernetes/kubernetes/pull/75501#pullrequestreview-225099825.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brancz** [comment]
Thanks a lot for the super quick follow up! :)

/lgtm

**Comment by Huang-Wei** [comment]
Unreasonably this PR can fail the 2 performance CI jobs..

/shrug

**Comment by Huang-Wei** [comment]
@brancz Can you re-lgtm? The CI was flaky yesterday.

**Pull request merged**
