### PR TITLE
cpumanager: drop old custom file backend

### PR DESCRIPTION
**Pull request by ffromani**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Continuation of https://github.com/kubernetes/kubernetes/pull/85387 , which seems to have stalled even though the direction seemed to be good.
Drop the old file-based cpumanager state handling code: it is unused and replaced by the checkpointmanager code.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by klueska** [comment]
@fromanirh Thanks for the updated PR

Looks like your bazel files aren't properly updated with this change. Just run the following command from the top of the kubernetes tree:
```
./hack/update-bazel.sh
```

**Comment by fromanirh** [comment]
> @fromanirh Thanks for the updated PR
> 
> Looks like your bazel files aren't properly updated with this change. Just run the following command from the top of the kubernetes tree:
> 
> ```
> ./hack/update-bazel.sh
> ```

Thanks for your review! I already did the update-bazel.sh step, it seems is not enough. I added back a missing helper, let's see if this fixes. Otherwise I'll dig deeper into bazel and update.

**Comment by klueska** [comment]
`AssertStateEqual()` doesn't feel like a helper function we should need anymore because it compares the state stored in a state file generated by the file backend vs. the checkpoint backend.

I haven't looked into it directly, but does it make more sense to update whatever tests call this so that they don't require this check anymore?

**Comment by fromanirh** [comment]
> `AssertStateEqual()` doesn't feel like a helper function we should need anymore because it compares the state stored in a state file generated by the file backend vs. the checkpoint backend.
> 
> I haven't looked into it directly, but does it make more sense to update whatever tests call this so that they don't require this check anymore?

Fair enough, working to fix this.

**Comment by fromanirh** [comment]
> `AssertStateEqual()` doesn't feel like a helper function we should need anymore because it compares the state stored in a state file generated by the file backend vs. the checkpoint backend.
> 
> I haven't looked into it directly, but does it make more sense to update whatever tests call this so that they don't require this check anymore?

So I had a deeper look. The helper implements a generic deep equal check for `cpumanager/state.States` structs, so it seems worth to be kept around.
It is now used to test the checkpoint save and restore flows, something worth keeping.

It seems (see commit 3991ed5d2f6e93df0bf4aae284afc5aeccde0ed0) that when the checkpoint test was added, the original author just generalized a bit the existing code. This could explain why this generic utility was sitting in an obsolete file.

For these reasons I can't think of a better approach than restore the missing helper, if you think differently I'm open to change but I'll need more details about how to move forward.
Thanks!

**Comment by klueska** [comment]
Got it. Makes sense. Thanks for looking into it deeper.

/lgtm

**Pull request merged**
