### PR TITLE
Use `CreatedByAnnotation` constant

### PR DESCRIPTION
**Pull request by duglin**
A nit but didn't want the strings to get out of sync.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Yay for reuse of constants.

**Comment by smarterclayton** [comment]
This pulls in the controller code to the CLI, which we do not want to do.  If this is supposed to be an API annotation, the definition should be in `pkg/api`, not in `pkg/controller`.

**Comment by duglin** [comment]
@smarterclayton thanks for the info - still learning the components - but clearly cli shouldn't pull in server side stuff.

Hopefully the new location for it makes sense - I tried to find similar types of constants.

**Comment by smarterclayton** [comment]
This looks fine, thanks.  Will merge once we unfreeze from 1.3.

**Comment by duglin** [comment]
rebased

**Comment by duglin** [comment]
would it be possible to get an "ok to test" on this one?

**Comment by smarterclayton** [comment]
Lgtm thanks!

**Pull request merged**
