### PR TITLE
Add kube::util::wait-for-jobs to report status, unlike builtin wait

### PR DESCRIPTION
**Pull request by zmerlynn**
*\* Sigh **

Fixes an additional complaint in #6463

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @justinsb

**Comment by justinsb** [comment]
I wouldn't characterize it as a complaint :-)  Thanks for fixing.

Do I take it that wait only returns the exit code when we pass a pid?  (I can't find the docs, for some reason).  If so LGTM

**Comment by zmerlynn** [comment]
Yeah, this surprised me, too. From [the bash docs](https://www.gnu.org/software/bash/manual/html_node/Job-Control-Builtins.html): "If no arguments are given, all currently active child processes are waited for, and the return status is zero." What!?

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
