### PR TITLE
rkt: Add DNS support

### PR DESCRIPTION
**Pull request by jonboulle**
This supersedes #20302 (it's that PR + fixed unit tests)

### CODE REVIEW

**Comment by jonboulle** [comment]
@dchen1107 @yujuhong

**Comment by jonboulle** [comment]
How can I get the CLA on this? does @yifan-gu need to chime in?

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
> How can I get the CLA on this? does @yifan-gu need to chime in?

Yes. Let's see if the manual override works.

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #20402

**Comment by jonboulle** [comment]
could we get an lgtm please?

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
> could we get an lgtm please?

I was trying to see if I could get the cla bot to give up on the author's consent, but LGTM anyway.

**Comment by yujuhong** [comment]
@k8s-oncall, can we manually merge this? Thanks!

**Comment by jonboulle** [comment]
thanks!!

**Pull request merged**
