### PR TITLE
Added logging to file for cluster autoscaler

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by mwielgus** [comment]
LGTM

**Comment by piosz** [comment]
@kubernetes/test-infra-maintainers
We started collecting cluster autoscaler e2e logs

**Comment by piosz** [comment]
FYI @a-robinson the logs go to `/var/log/cluster-autoscaler.log`

**Comment by a-robinson** [comment]
Thanks @piosz :)

**Comment by a-robinson** [comment]
@piosz, is it expected that this doesn't seem to be running on the master on the kubernetes-e2e-gce suite? I was checking there to verify the contents of the file are as expected.

**Comment by a-robinson** [comment]
Ah, looks like it's probably due to #26197

**Comment by piosz** [comment]
What do you mean? CA is supposed to run on master machine both in GKE and GCE though it's disabled by default. Currently this is enabled only in autoscaling suites (for example kubernetes-e2e-gce-autoscaling).

**Comment by a-robinson** [comment]
That would explain it, thanks. Everything looks good on the master in the k8s-jnks-e2e-gce-autoscaling project.

**Pull request merged**
