### PR TITLE
Reintroduce memory limits removed in #55715

### LINKED ISSUE #55797: Load test metadata-proxy
Offshoot of regression - https://github.com/kubernetes/kubernetes/issues/55695

We are supporting "100 pods per node" in k8s officially (https://kubernetes.io/docs/admin/cluster-large/#support) and need to make sure metadata-proxy allows those many pods to access the metadata service simultaneously.

cc @kubernetes/sig-node-bugs @ihmccreery @cjcullen @loburm

### PR DESCRIPTION
**Pull request by ikehz**
**What this PR does / why we need it**: Reintroduce memory limits removed in #55715, in order to make metadata-proxy QoS be guaranteed.  Xref #55695.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55797

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ihmccreery** [comment]
This may trigger https://github.com/kubernetes/kubernetes/pull/54996 again, though.

Do we need to up the master size?

**Comment by shyamjvs** [comment]
As I mentioned earlier in https://github.com/kubernetes/kubernetes/issues/55695#issuecomment-344287767, increasing resource requests/limits for a node agent reduces node allocatable capacity and can impact small nodes. I'd prefer someone from @kubernetes/sig-node-pr-reviews to take a look into this.

**Comment by ihmccreery** [comment]
Xref https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/11 and https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/12.

/assign @porridge

**Comment by ihmccreery** [comment]
(This won't pass tests until GoogleCloudPlatform/k8s-metadata-proxy#11 is in and pushed.)

**Comment by mikedanese** [comment]
This PR increases the memory dedicated to mds proxy from 32MB to 45MB. Who wants to make the call on that?

**Comment by ihmccreery** [comment]
@porridge agreed to it for beta.

**Comment by porridge** [comment]
Hm, I was under the impression that what I agreed to was "for the time
being, metadata proxy's performance on the level of 100 concurrent
outstanding requests is good enough, but should be improved before GA". :-)

**Comment by yujuhong** [comment]
AFAIK, this is an opt-in Beta feature. The impact of the resource footprint for small nodes and the story for upgrades will be re-visited before GA.

Approving the milestone.

**Comment by yujuhong** [comment]
> AFAIK, this is an opt-in Beta feature. The impact of the resource footprint for small nodes and the story for upgrades will be re-visited before GA.

/cc @dchen1107 @abgworrall

**Comment by ihmccreery** [comment]
Since we're in code freeze, this can wait until v1.9.1.

**Pull request merged**
