### PR TITLE
Remove repeated reviewer's names

### PR DESCRIPTION
**Pull request by houjun41544**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by zhangxiaoyu-zidif — APPROVED** [review]

**Review by brendandburns — APPROVED** [review]

**Comment by cblecker** [comment]
@brendandburns @thockin needs the dash between no and issue

**Comment by zhangxiaoyu-zidif** [comment]
／lgtm

**Pull request merged**
