### PR TITLE
fix test/e2e/apimachinery

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

use log functions of core framework

**Which issue(s) this PR fixes**:

Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by s-ito-ts** [comment]
It is necessary to run ./hack/update-gofmt.sh as the following failed job message said:
```
diff -u ./test/e2e/apimachinery/certs.go.orig ./test/e2e/apimachinery/certs.go
--- ./test/e2e/apimachinery/certs.go.orig	2019-08-28 02:11:29.503651033 +0000
+++ ./test/e2e/apimachinery/certs.go	2019-08-28 02:11:29.503651033 +0000
@@ -23,8 +23,8 @@
 
 	"k8s.io/client-go/util/cert"
 	"k8s.io/client-go/util/keyutil"
-	"k8s.io/kubernetes/test/utils"
 	"k8s.io/kubernetes/test/e2e/framework"
+	"k8s.io/kubernetes/test/utils"
 )
 
 type certContext struct {

Run ./hack/update-gofmt.sh
```

**Comment by hwdef** [comment]
@s-ito-ts 
Thanks for your suggestion.I changed it.

**Review by SataQiu — COMMENTED** [review]
Thanks
/lgtm

**Review by oomichi — COMMENTED** [review]
Thanks for doing this. This is very clean and simple for me.

The following `/hold` is for  free merge pool bandwidth for 1.16-targeted PRs as https://github.com/kubernetes/kubernetes/pull/82108#issuecomment-526207592
We need to wait for making these high priority PRs merged first.

/lgtm
/approve
/hold

**Comment by oomichi** [comment]
as https://kubernetes.slack.com/archives/C2C40FMNF/p1567190475094100

/hold cancel

**Comment by cblecker** [comment]
/lgtm cancel

Needs rebase.

**Pull request closed without merging**
