### PR TITLE
Increase Timeout of Service Affinity e2e Test & Remove kube-proxy Specifics

### PR DESCRIPTION
**Pull request by aauren**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

Adds a flag to the e2e test suite that allows the user to override the kube-proxy specific proxy type detection that is done inside the sig-network services suite.

This fix allows non kube-proxy, proxy implementations to still accurately test that they are implementing proxy affinity correctly.

**More Detail:**

The `should have session affinity timeout work for service with type *` (see: [service.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L2183)) type tests are supposed to test that k8s network implementations are properly respecting `spec.sessionAfinityConfig.clientIP.timeoutSeconds`. This should keep a flow going to a consistent endpoint for the duration of `timeoutSeconds`, and then afterwards it should begin to balance them across all endpoints.

For tests that don't use IPVS, this is statically set to [`15` secondes](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L92) so that the test suite finishes quickly.

However, for IPVS services we have to make a [special exception](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L3897-L3903) to increase the duration to 2 minutes because IPVS has a built-in TCP timeout default of 2 minutes.

This works great, but the problem is that the way that the test suite decides whether or not IPVS is used is [kube-proxy specific](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L4176-L4189). It curls the localhost (via `hostNetwork: true`) on port `10249` with the path `/proxyMode` and then looks for the response `ipvs`. This works fine for kube-proxy, but no other network implementation is going to implement this method of proxy mode detection.

This fixes that problem, by allowing test suites to override this value on a test run specific basis by adding the command-line flag: `--service-proxy-type` so that if they use IPVS as a proxy backend, they are still able to test that they have implemented service affinity correctly.

#### Special notes for your reviewer:

I'll note that I'm not sure if I added test specific flags correctly. There is a [large comment in test_context.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L73-L100) that seems to indicate that there is a new way to do test-specific flags, but I wasn't able to find any examples of other test suites using that convention, so I decided to go with the convention that I saw most prominently in the code.

I have tested that this does what I want pretty thoroughly by running the e2e tests with local binaries. Using the following command:

```sh
$ time kubetest2 noop \
  --test=ginkgo \
  -- \
  --use-binaries-from-path \
  --parallel 1 \
  --ginkgo-args '-v -progress' \
  --focus-regex="should have session affinity timeout work for service with type clusterIP" \
  --test-args "--service-proxy-type=ipvs"
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

Tagging @hakman for review

### CODE REVIEW

**Comment by hakman** [comment]
Any thoughts on this @aojea & @upodroid ?
/cc @aojea @upodroid

**Comment by upodroid** [comment]
LGTM

This test is failing on kops when we use cilium now that we are merging the change that sets `-num-nodes` flag. 

/ok-to-test

**Comment by aojea** [comment]
I prefer to not have flags, we also should not have this autodetection things in the e2e framework .... let's revisit this and see if we can come with a general approach for testing this instead of keep special casing

/assign @aojea
/hold

**Comment by upodroid** [comment]
I know that kube proxy is a core part of the k/k codebase but its functionality can be replaced by CNIs(calico and cilium). Should we explore the idea of treating kube-proxy as Feature, tag its tests accordingly and create specific jobs for it?

**Comment by aojea** [comment]
> I know that kube-proxy is a core part of the k/k codebase but its functionality can be replaced by CNIs(calico and cilium). Should we explore the idea of treating kube-proxy as a Feature, tag its tests accordingly and create specific jobs for it?

exactly, these tests are wrong, tests that run by default should be generic or tagged as you suggest.
We need to fix it, the context is that at one point they were part of conformance, if ipvs has a bug it has to fix it or stop running these tests/

Please, give me some days to gather all the historical data and make the right suggestions so you can progress with this PR, I'll try to come back to this today EOD

Thanks for finding this

**Comment by aauren** [comment]
Thanks everyone for the quick reviews!

I can certainly understand not wanting to make more flags. As an upstream maintainer for kube-router I often try to keep flags to a minimum as well.

> Should we explore the idea of treating kube-proxy as a Feature, tag its tests accordingly and create specific jobs for it?

FWIW my hope behind this PR was that we would be able to keep the service affinity test in the suite, but that we could somehow generalize it to make it not kube-proxy specific. I would really like to use the entire Kubernetes conformance suite to be able to test both kube-router and other network implementations.

> exactly, these tests are wrong, tests that run by default should be generic or tagged as you suggest.
We need to fix it, the context is that at one point they were part of conformance, if ipvs has a bug it has to fix it or stop running these tests/

@aojea  I had a couple of thoughts on how we could proceed from here that might be able to help you get started in your thinking...

**Adjusting IPVS TCPFIN Timeout**

While I haven't completely tested this, I believe that the 2 minute timeout in IPVS is not a bug, but rather a configurable value. I believe that it corresponds to the TCPFIN timeout configuration setting. This can be [set by passing `ipvsadm --set`](https://linux.die.net/man/8/ipvsadm). I don't know if all providers allow this to be set, but I know that this is implemented in [kube-proxy](https://github.com/kubernetes/kubernetes/pull/85517) and it will be exposed in [kube-router soon](https://github.com/cloudnativelabs/kube-router/pull/1590).

By default the TCPFIN setting for IPVS defaults to 120 seconds and this is exactly what I see when I monitor IPVS throughout the test. Essentially, when you run the test and monitor `ipvsadm -l -c` you'll see two different entries related to the test show up in the output.

```sh
ipvsadm -l -c                                                                                                                                                                                                                                               
IPVS connection entries                                                                                                                                                                                                                                                                 
pro expire state       source             virtual            destination                                                                                                                                                                                                                
TCP 00:06  ASSURED     100.96.5.16:0      100.70.25.179:http 100.96.3.19:9376                                                                                                                                                                                                           
TCP 01:51  TIME_WAIT   100.96.5.16:35982  100.70.25.179:http 100.96.3.19:9376
```

The first one, `ASSURED` is what you set as your persistent timeout, however it is also shadowed by the default TCPFIN setting showing up as `TIME_WAIT`. As long as either record is present, the flow for a given quad (source / dest IP, source / dest port) will go to the same endpoint.

So one option here, could be that we have a certain default minimum that we use in the conformance tests and also advocate that network CNIs implement as well that is lower than 2 minutes.

What I don't like about this, is that I don't think that conformance tests should drive CNI configuration. I'm not sure why the default for IPVS is 2 minutes, but I don't like the idea of changing the default for everyone just for conformance tests. On the other side, I don't know if I like changing the default configuration of CNI deployments just so that they pass conformance tests.

**Increase the Default**

Not fully sure of the impact here, but another option would be to just globally increase [AffinityConfirmCount](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L92) so that it is longer than 2 minutes.

TBH 15 seconds for this default seems a little low to me and I'm surprised that it works as well as it does with this setting. There are multiple places where TCP timeouts are longer than that. I believe that the default TCP_WAIT timeout for the Linux kernel is 60 seconds?

This would cause the e2e test suite to run longer, but unless I miss my mark there are quite a few tests that already take multiple minutes to complete in the suite. Maybe it could just be tagged with `[SLOW]` like some of the other ones that I've seen and we call it a day?

**Add a Different Flag**

Rather than making a flag that is super specific about proxy implementations, maybe it would be a good idea to add a flag, but just make it more generic. Rather than it being a proxy implementation flag, maybe we make it something like `--service-tcp-timeout` that would be the number of seconds that we wait for TCP timeout situations.

While I know that we're against making flags, at least this one would probably be more broadly applicable to other tests in the current suite and in the future.

I believe that TCP timeouts are likely finicky things and there are multiple flags both in the application and in the Linux kernel to tune them. A flag like this would make the conformance tests more or less agnostic to this implementation detail and allow the runners of these tests to tune them to what their system is configured for without us having to globally increase the runtime of everyone who runs the e2e suite.

**Comment by aojea** [comment]
The problem is that this test was in conformance, that has some strong requirements, since now has been demoted https://github.com/kubernetes/kubernetes/pull/112806  because of the reasons explained here, is not easy to generalize, we can do some changes

> Increase the Default

+1 yes, ` [SLOW] l` is not needed, IIRC we had some place written Slow > 5 minutes, 

Please make all of us a favor and remove this from the codebase https://github.com/kubernetes/kubernetes/blob/98601e2ec5da64e05251788ea7952e13c2526a43/test/e2e/network/service.go#L4175-L4189

All kube-proxy specific tests should go here https://github.com/kubernetes/kubernetes/blob/98601e2ec5da64e05251788ea7952e13c2526a43/test/e2e/network/kube_proxy.go#L48 , it is working fine this way, so let's not change more things by now, we'll address it later if needed

**Comment by aauren** [comment]
@aojea - I have removed the kube-proxy specific implementation options and increased the default timeout from 15 seconds to 125 (which is what it was set to when in IPVS mode previously).

I have run this against my kube-router based cluster and the 2 session affinity timeout tests now pass correctly.

**Comment by aojea** [comment]
/hold cancel
/lgtm
/approve

Thanks

**Comment by hakman** [comment]
@aauren Could you update the PR title to reflect the final change?

**Comment by aauren** [comment]
>Could you update the PR title to reflect the final change?

Done

**Pull request merged**
