### PR TITLE
Automated cherry pick of #11794 upstream release 1.0

### LINKED ISSUE #12877: kubernetes 1.0.3 kube-up.sh  not functioning
When I attempt to kube-up it gets most of the way completed but then stops and gives
```
./../cluster/libvirt-coreos/../../cluster/common.sh: line 83: user_args[@]: unbound variable
```
Is this just me or has this occurred elsewhere?

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #12877

@rubenv @hiltyj @roberthbailey

### CODE REVIEW

**Comment by zmerlynn** [comment]
Cross-link #11794

@mikedanese: You're using the pre `hub` version of the script that doesn't populate the subject?

**Comment by mikedanese** [comment]
@zmerlynn No :( it get's all the way to creating the branch but then it says my origin remote isn't a github branch:

```
➜  kubernetes git:(master) ✗ export GITHUB_USER=mikedanese && ./hack/cherry_pick_pull.sh upstream/release-1.0 11029
+++ Updating remotes...
Fetching origin
Fetching upstream
+++ Creating local branch automated-cherry-pick-of-#11029-upstream-release-1.0-1440003249
Branch automated-cherry-pick-of-#11029-upstream-release-1.0-1440003249 set up to track remote branch release-1.0 from upstream.
Switched to a new branch 'automated-cherry-pick-of-#11029-upstream-release-1.0-1440003249'
+++ Downloading patch to /tmp/11029.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /tmp/11029.patch

Applying: AWS: Fix race-condition in tagging of security group
Applying: AWS: Fix race in security-group read/create
Applying: Fixes per review

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-#11029-upstream-release-1.0-1440003249:automated-cherry-pick-of-#11029-upstream-release-1.0

+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] y
Counting objects: 18, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (18/18), 3.31 KiB | 0 bytes/s, done.
Total 18 (delta 12), reused 0 (delta 0)
To git@github.com:mikedanese/kubernetes.git
 * [new branch]      automated-cherry-pick-of-#11029-upstream-release-1.0-1440003249 -> automated-cherry-pick-of-#11029-upstream-release-1.0
+++ Creating a pull request on github
Aborted: the origin remote doesn't point to a GitHub repository.

+++ Returning you to the master branch and cleaning up.
```

But:
```
➜  kubernetes git:(master) ✗ git remote -v
origin	git@github.com:mikedanese/kubernetes.git (fetch)
origin	git@github.com:mikedanese/kubernetes.git (push)
upstream	https://github.com/kubernetes/kubernetes.git (fetch)
upstream	no_push (push)
```

So i create the PR from the github web UI. I'm going to look into it.

**Comment by zmerlynn** [comment]
@mikedanese: Are you using ssh for your personal fork? I suspect `hub` doesn't support it. (https fetch/push works just fine)

**Comment by mikedanese** [comment]
@zmerlynn yup. I will give https a shot.

**Pull request merged**
