### PR TITLE
Manual cherry-pick of #35346

### PR DESCRIPTION
**Pull request by bprashanth**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35383)

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM

**Comment by bprashanth** [comment]
@k8s-bot gci gce e2e test this

**Comment by bprashanth** [comment]
@k8s-bot kubemark e2e test this

**Comment by bprashanth** [comment]
@k8s-bot gci gke e2e test this

**Comment by bprashanth** [comment]
@k8s-bot cvm gke e2e test this

**Comment by ixdy** [comment]
GKE PR testing on release-1.3 is broken until https://github.com/kubernetes/kubernetes/pull/35458 merges.

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot cvm gce e2e test this.

**Comment by ixdy** [comment]
@bprashanth the PR kubemark tests are broken on 1.3 - probably need to merge manually.

**Comment by bprashanth** [comment]
Thanks for the heads up, @fabioy ok to merge manually?

**Comment by fabioy** [comment]
Ah, Kubemark...my little red nemesis. 

@bprashanth Change seems safe, merging.

**Pull request merged**
