### PR TITLE
Add expectNoError helper, minor cleanups

### PR DESCRIPTION
**Pull request by zmerlynn**
@roberthbailey complained about the fact that this code was all over. :)

cc @roberthbailey, @filbranden, @rrati

### CODE REVIEW

**Comment by filbranden** [comment]
I'm OK with the two cleanups but I'm not sure I like expectNoError because we're essentially just hiding the framework again... It's not really saving a lot of typing. Do we really need such shallow helpers?

**Comment by zmerlynn** [comment]
The main reason I like it is to be able to create one-liners, and possibly
eliminate lvalues (although I didn't here). I actually find it more
readable than the gomega form.

**Comment by roberthbailey** [comment]
@filbranden It allows us to call functions that only return an error on the same line that we assert that there should be no error. 

Otherwise you end up with the (incomphrehensible)

Expect(waitForPodNotPending(c, ns, podDescr.Name, 60*time.Second)).NotTo(HaveOccurred(), fmt.Sprintf("starting pod %s in namespace %s", podDescr.Name, ns))

which reads like you are waiting for podNotPending to not have occurred rather than an error not to have occurred.

**Comment by filbranden** [comment]
If we hate Gomega so much, should we really have adopted it?

I hate custom small wrappers because it always means you need to go figure out how they were defined to know what they actually do... I'm still -1 on this, am I the minority here?

**Comment by brendandburns** [comment]
I'm fine with this to, as I find "expectNoError" to have such clear semantics that I'm unlikely to look up the definition.

So, given that it's minor and we have 3 in favor, one not, I'm going to merge this...

**Comment by zmerlynn** [comment]
I meant to reply to this but got caught up elsewhere: I've actually worked in plenty of codebases that had plenty of shallow matchers, and didn't find them to be a burden. We did it in C++ and Java both for the last team I was on, and I tended to find it a readability improvement for the tests. *shrug*.

**Comment by lavalamp** [comment]
I'm massively late to the party here but I just saw my first use of this in the wild, and:
* It's confusing (I had to look up the function to see if it's doing the gomega thing or something else)
* It's not much shorter.
* If we feel the need to hide our DSL behind a function *we're doing it wrong*. Arguably the wrong thing is the DSL, but this is a case where two wrongs do not make it right...

**Pull request merged**
