### PR TITLE
Resource gatherer uses RSS memory instead of working set one

### PR DESCRIPTION
**Pull request by gmarek**
Required for #21500

cc @yujuhong @davidopp @wojtek-t

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by gmarek** [comment]
@k8s-bot unit test this issue: #21544

**Comment by gmarek** [comment]
@k8s-bot test this issue: #21467

**Comment by erictune** [comment]
@dchen1107

**Comment by yujuhong** [comment]
lgtm

**Pull request closed without merging**
