### PR TITLE
Propagate KeyLogWriter to rest.Config

### PR DESCRIPTION
**Pull request by espindola**
/kind feature

This makes it easy to log the TLS secrets in order to decrypt it in
wireshark.

### CODE REVIEW

**Comment by espindola** [comment]
This work is covered by the Scylla CLA.

**Comment by espindola** [comment]
Does this need a release note? It is an go API change, but backwards compatible and for debugging only.

**Comment by liggitt** [comment]
/hold
for discussion in https://github.com/kubernetes/kubernetes/issues/94123

**Pull request closed without merging**
