### PR TITLE
Fix parameter for fluentd-gcp-scaler

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does / why we need it**:
Fixes a parameter for fluentd-gcp-scaler

```release-note
NONE
```

### CODE REVIEW

**Review by bmoyles0117 — APPROVED** [review]
LGTM

**Comment by wadadli** [comment]
Is there a work around for this? I have a prod cluster that's generating these logs.

**Comment by x13n** [comment]
This will be fixed in 1.10.8. Meanwhile, the workaround for excessive logging is to filter them out: https://cloud.google.com/logging/docs/exclusions

**Pull request merged**
