### PR TITLE
Fix golint errors in cmd/kube-apiserver

### PR DESCRIPTION
**Pull request by xychu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none

**Comment by cblecker** [comment]
@xychu: Now that the vet errors are fixed, can you add this package to the lined packages list?
```
echo cmd/kube-apiserver/app/preflight >> hack/.linted_packages
LC_ALL=C sort -o hack/.linted_packages hack/.linted_packages
```
Then commit the result.

Thanks!

**Comment by xychu** [comment]
@cblecker thanks for your review, have appended a commit that adds the package to linted packages list.

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by cblecker** [comment]
/lgtm
Over to @caesarxuchao for approval

**Pull request merged**
