### PR TITLE
remove redundant definition of the defaultProvider in the scheduler

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

"DefaultProvider" constant is defined in two places, this PR cleans that up.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @liu-cong

### CODE REVIEW

**Comment by liu-cong** [comment]
This helper method seems unnecessary. Would you like to clean it up too?
https://github.com/kubernetes/kubernetes/blob/9b75e364364981a5a09609017b81085df1ee0b21/pkg/scheduler/scheduler.go#L803-L806

Let me know when you are ready to merge. I will LGTM.

**Comment by ahg-g** [comment]
> This helper method seems unnecessary. Would you like to clean it up too?
> https://github.com/kubernetes/kubernetes/blob/9b75e364364981a5a09609017b81085df1ee0b21/pkg/scheduler/scheduler.go#L803-L806
> 
> Let me know when you are ready to merge. I will LGTM.

can't take the address of a constant, so the function is necessary.

**Pull request merged**
