### PR TITLE
Adding a script to verify that swagger spec is updated

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Thanks. How reliable is update-swagger-spec.sh, and how long does it take?

**Comment by nikhiljindal** [comment]
It is reliable.
Running ./hack/update-swagger-spec on my machine gave me:
```
real    0m2.207s
user    0m0.332s
sys     0m0.239s
```

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
