### PR TITLE
code-of-conduct: provide concrete points of contact

### PR DESCRIPTION
**Pull request by philips**
Provide concrete information about who to contact about CoC issues. Having unambiguous people to contact is important to resolve issues in a timely manner.

### CODE REVIEW

**Comment by philips** [comment]
cc @sarahnovotny

**Comment by sarahnovotny** [comment]
do bots still scrape for email addresses?  would we have less spam traffic with a sarahnovotny at google.com format? or have the bots all gone AI and can parse that now too?

**Comment by philips** [comment]
I assume my email is just so trivially crawleable that it doesn't matter. For example add .patch to a URL on github: https://github.com/kubernetes/kubernetes/commit/e294b23674abdbaf579e7e2340fee697bb256eaf.patch

**Comment by brendandburns** [comment]
Personally I just trust the spam filters at this point and mostly it works out.

If this is ok w/ @sarahnovotny  I will LGTM.

**Comment by sarahnovotny** [comment]
lgtm

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
