### PR TITLE
api: rename internal struct core.ResourceClaim -> ResourceAttachment

### LINKED ISSUE #113771: dynamic resource allocation: simplify type names in API
### What would you like to be added?

Potential changes:
- Reference -> Ref in struct names - might not be consistent with other types then?
- core.ResourceClaim -> ResourceClaimUse, ResourceClaimAttachment, etc. - TBD

This only affects Go code and thus is not an API change.

### Why is this needed?

Simpler and/or less ambiguous code.

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This avoids confusion between resource.Claim and
core.ResourceClaim. ResourceAttachment is a better name because it describes what the struct does ("attach a pod resource to a container").

#### Which issue(s) this PR fixes:

Fixes #113771 

The issue also mentions renaming types like `ResourceClassParametersReference` to `ResourceClassParametersRef`, but that would make them inconsistent with other reference types and therefore I propose that we keep those names.

#### Special notes for your reviewer:

This struct is only used inside Go code, therefore this is not an API change. YAML files work as they did before.

#### Does this PR introduce a user-facing change?
```release-note
k8s.io/api/core/v1: the Go API now uses `ResourceAttachment` as type name instead of `ResourceClaim`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3063
```

### CODE REVIEW

**Comment by klueska** [comment]
As mentioned in the linked issue, I would prefer `ResourceClaimAttachment` over just `ResourceAttachment`. That said, the word "attachment" sounds a little awkward to me. Is there precedent for such a name in the storage world, or is this something new you came up with?

**Comment by pohly** [comment]
ResourceClaimAttachment seems unnecessarily long to me, but I don't care too much.

Volumes are "attached" to nodes, and there is a storage.VolumeAttachment type. I think originally the proposal came from thockin, though, so I don't know whether that is what he had in mind.

**Comment by pohly** [comment]
The directly corresponding type in the v1 API is `VolumeMount`. But resource claims don't get mounted...

**Comment by klueska** [comment]
Can you show an example of how this would be used in go code? Maybe that would help with deciding which name makes the most sense.

**Comment by pohly** [comment]
I don't think it'll be used much in Go code. In Kubernetes, it's used when constructing a pod, for example in https://github.com/kubernetes/kubernetes/pull/114917/files#diff-7ee023b4401073292170227985c8ac98015db0c1980657c277a7cea011c24830

**Comment by pohly** [comment]
Is that an LGTM?

**Comment by bart0sh** [comment]
`ResourceAttachment` name is still confusing to me, especially in the changes like this:
```
-							Claims: []api.ResourceClaim{{Name: "my-claim"}},
+							Claims: []api.ResourceAttachment{{Name: "my-claim"}},
```
So, ResourceAttachment is still a claim, but we want to call this claim an attachment, correct?

**Comment by pohly** [comment]
We want to "attach" a pod resource to a container. For volumes, the corresponding operation is "mount a volume".

The "pod resource" itself is a reference to a resource claim.

If there ever are other kinds of pod resources, `ResourceAttachment` as a name still works. It's not likely, but that it could be done without changing the name IMHO implies that adding `Claim` to it as in `ResourceClaimAttachement` is unnecessarily specific.

**Comment by bart0sh** [comment]
It still looks to me like we're creating a new confusion to avoid another confusion. Again, I think this is confusing:
```
Claims: []api.ResourceAttachment{{Name: "my-claim"}},
```
We put `ResourceAttachement` object into the `Claims` field and name it `my-claim`. Why to call it attachement then?

**Comment by pohly** [comment]
That it's used for `Claims` refutes my argument that it could be generic resource in the future.

So let's use `Claims: []api.ResourceClaimAttachment{{Name: "my-claim"}}` after all? Or do you have some other suggestion?

**Comment by bart0sh** [comment]
ResourceClaimAttachment looks better to me. However, I must notice that I probably don't fully understand a confusion between resource.Claim and core.ResourceClaim. Let's discuss this offline.

**Comment by bart0sh** [comment]
@pohly so, where we are with this?

**Comment by pohly** [comment]
I think I need to change to `api.ResourceClaimAttachment` as there have been no other suggestions.

**Comment by bart0sh** [comment]
Another option was not to rename as far as I remember.

**Comment by pohly** [comment]
@klueska: what do you prefer?

**Comment by pohly** [comment]
Looking at the issue, doing nothing was indeed our conclusion: https://github.com/kubernetes/kubernetes/issues/113771#issuecomment-1383854599

**Comment by pohly** [comment]
/close

I'll reopen if this is needed after all.

**Pull request closed without merging**
