### PR TITLE
Name jobs created by sj deterministically

### PR DESCRIPTION
**Pull request by janetkuo**
``` release-note
Name the job created by scheduledjob (sj) deterministically with sj's name and a hash of job's scheduled time.
```

@erictune @soltysh

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30420)

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM, but you need to update the tests:
```
pkg/controller/scheduledjob/utils_test.go:75: not enough arguments in call to getJobFromTemplate
```

**Comment by janetkuo** [comment]
Fixed the test now

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30420#-:-KOudR2moAb3nwvQK8e1:b-mxjsgo)*

**Comment by janetkuo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30420)*

**Comment by janetkuo** [comment]
Fixed test; applying tag

**Pull request merged**
