### PR TITLE
Test config for gke-1.1 job

### PR DESCRIPTION
**Pull request by j3ffml**
Currently running and [green](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-1.1/).

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by a-robinson** [comment]
Needs a rebase

**Comment by jlowdermilk** [comment]
Rebased. @k8s-bot unit test this.

**Pull request merged**
