### PR TITLE
{WIP} Expose /readyz & /livez in kube-controller-manager

### LINKED ISSUE #118158: Split `/healthz` into `/livez` & `/readyz` for kube-controller-manager
### What would you like to be added?

Quoted from @wojtek-t 's [comment](https://github.com/kubernetes/kubernetes/pull/115754#discussion_r1192068894)

Splitting healthz/ into livez/ and readyz/ 

### Why is this needed?

```
I agree that splitting into livez/ and readyz/ is what we need here:

* livez/ inherits the existing behavior of healthz/ [it just becomes true once the component starts]
* readyz/ is failing when the component isn't initialized (i.e. it's only true after informers are already synced)

Now what we get is:

* non-leader with delayed caching will always be non-ready
* non-leader without delayed caching will be ready as soon as its cache initializes
* leader currently initializing can be distinguished from non-leader using the leader-election metrics
```

### PR DESCRIPTION
**Pull request by nayihz**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Adds a proper liveness and readiness endpoints to the kube-controller-manager.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/118158

#### Does this PR introduce a user-facing change?

```release-note
The kube-controller-manager exposes /livez and /readz for health checks that are in compliance with https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by czybjtu** [comment]
need to add integration test after https://github.com/kubernetes/kubernetes/pull/118148 merged.
/hold

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by linxiulei** [comment]
FYI @nayihz you may resume this PR as https://github.com/kubernetes/kubernetes/pull/118148 was merged.

**Pull request closed without merging**
