### PR TITLE
clean up: put test description in head to clear

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by cblecker** [comment]
ping @brendandburns for approval

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
