### PR TITLE
Update json-patch to v4.9.0 tagged release

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates to a tagged version of json-patch. This is a no-op for k8s.io/kubernetes (no code changes), but ensures that consumers of the k8s.io libraries pick up the desired version (the v0.0.0... version would allow a downstream consumer to use v4.6.0 without realizing it and miss the desired fixes).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig api-machinery
/cc @dims

### CODE REVIEW

**Comment by liggitt** [comment]
lint caught an unused dep that needed removing from modules.txt

**Review by dims — APPROVED** [review]

**Pull request merged**
