### PR TITLE
Remove retry logic in initializer AC's config loader

### PR DESCRIPTION
**Pull request by caesarxuchao**
A piece of https://github.com/kubernetes/features/issues/209. A follow-up of https://github.com/kubernetes/kubernetes/pull/46808.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by smarterclayton** [comment]
Lgtm

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
Thanks.

**Comment by caesarxuchao** [comment]
This PR is a follow-up of https://github.com/kubernetes/kubernetes/pull/46808, which was included by the 1.7 branch yesterday. With #46808, initializer AC have nested retries, which make the code hard to reason. This PR improves the code health, so applying the 1.7 milestone.

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
The gc tests become quite flaky:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47555/pull-kubernetes-e2e-gce-etcd3/36490/
```
[k8s.io] Garbage collector should orphan pods created by rc if delete options say so 5m2s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Garbage\scollector\sshould\sorphan\spods\screated\sby\src\sif\sdelete\soptions\ssay\sso$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:328
Jun 16 15:48:13.674: timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:312
```

**Pull request merged**
