### PR TITLE
replace loops with go idiomatic.

### PR DESCRIPTION
**Pull request by droslean**
Replaces unnecessary loops with go idiomatic way. 
Also removes an unused field with its library.

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
/assign @brendandburns @thockin 

Tim, Brendan, easy to review, this is one of those PRs that ends up needing top level approvers as it touches several files across the board. Though not a rush, we can wait until 1.15 opens for this to merge

Thanks,
Dims

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
