### PR TITLE
fix-typo

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
fix typo

```release-note
None.
```

### CODE REVIEW

**Review by harshanarayana — APPROVED** [review]
/lgtm

**Comment by yanggangtony** [comment]
This pr have been a time for review.
Would you have time to review it?
@harshanarayana @Verolop

**Review by harshanarayana — COMMENTED** [review]
/lgtm

**Comment by harshanarayana** [comment]
assign @aurasinis

**Pull request merged**
