### PR TITLE
Fix 1.5 ip range

### PR DESCRIPTION
**Pull request by bowei**
Change the default CLUSTER_IP_RANGE used by e2e
    
The existing choice intersects with the range reserved for auto
subnets and cannot be used with some GCP features.

see https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309529028 

```release-note
none
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
Should we also fix config-default.sh (the settings used for real clusters rather than test clusters)? And why doesn't this have a release note? We should definitely point this change out on the next patch release on each release branch.

**Comment by dchen1107** [comment]
I approved this for 1.5 branch since 

1) only changed the test code
2) it blocks 1.5->1.7 upgrade tests
3) https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309629694 The same pr into 1.6 is approved the right fix for 1.6->1.7 upgrade tests.

**Pull request merged**
