### PR TITLE
Hack to make godep work again

### PR DESCRIPTION
**Pull request by eparis**
prometheus/client_golang/model disappeared upstream. Thus you can not `go get` that package, thus godeps fails. This is a HACK to make `hack/verify-godeps.sh` work. Users with a fresh download will be unable to run `godeps restore`.
#14159 is an issue about fixing it correctly.

### CODE REVIEW

**Comment by eparis** [comment]
The PR currently has a change to "Godeps.json" just to get the CI to run (and hopefully fail only on that change). If CI works otherwise I will remove that change for this PR and as for merge...

**Comment by eparis** [comment]
WOOOO, https://travis-ci.org/kubernetes/kubernetes/builds/81039714 passed the prometheus problem and failed because I changed Godeps.json.  reverting that change now and we should be GTG.

**Comment by eparis** [comment]
@thockin @piosz

**Comment by thockin** [comment]
What's the real fix?

**Comment by thockin** [comment]
manual merge

**Comment by eparis** [comment]
1) rewrite godeps to check parent dirs with `go get` and then try to use the vcs to get where it needs to be...

2) update our prometheus dependency so we don't use `go get github.com/prometheus/client_golang/model`

**Comment by piosz** [comment]
@eparis thanks a lot!

**Pull request merged**
