### PR TITLE
Add multi cluster services documentation 

### PR DESCRIPTION
**Pull request by bprashanth**
Follow up to #11679. Haven't pushed to gcr.io yet. 

A caveat worth noting is that I observed weird latencies on gce when trying to access services in europe from a us cluster. Maybe it was just a bad day for multi-az.

### CODE REVIEW

**Comment by bprashanth** [comment]
I should probably split make_secret and some portion of this doc into a sharing services example

**Comment by brendandburns** [comment]
LGTM for now.  Feel free to split in the future.  Thanks for doing this!

**Comment by brendandburns** [comment]
Ah, you need to rebase for the grand rename...

**Comment by dchen1107** [comment]
Shippable still failed due to the error:

PATH=$GOPATH/bin:$PATH godep go install ./...
# github.com/GoogleCloudPlatform/kubernetes/contrib/service-loadbalancer
contrib/service-loadbalancer/service_loadbalancer.go:423: main redeclared in this block
previous declaration at contrib/service-loadbalancer/make_secret.go:46
godep: go exit status 2

**Comment by bprashanth** [comment]
Pushed to gcr.io, split out a sharing clusters example.Trap is green, PTAL

**Comment by brendandburns** [comment]
LGTM, thanks.

**Pull request merged**
