### PR TITLE
Fix the wrong link to server-side-apply conflicts

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix the wrong link to server-side-apply conflicts

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @pwittrock please help add lgtm and approved label, thanks.

**Comment by pwittrock** [comment]
@mysunshine92 in the future if you add these to the sig-cli weekly agenda, I'll be sure to take a look.

/lgtm
/approve

**Pull request merged**
