### PR TITLE
Fix AWS default master sizes

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by davidopp** [comment]
cc/ @justinsb

**Comment by davidopp** [comment]
LGTM

**Comment by justinsb** [comment]
This is great thanks!  I presume this is based on real data, which is a big improvement :-)

Now we really can leave #22711 closed...

**Comment by wojtek-t** [comment]
@justinsb - yes - this is supposed to be corresponding to what we have on GCE. I know those machines are huge, but we are going to work on optimizing it in 1.3

**Comment by justinsb** [comment]
I think it is good - there's only one master (for now), so the relative cost isn't that bad.  We should set defaults that optimize for user experience, rather than cost optimizing.  If people want to cost-optimize they can optimize down from the recommendations, rather than having to change our defaults because they want a reliable system :-)

**Comment by eparis** [comment]
This PR is included in #22874 which is slated to be included in the release-1.2 branch.
Please verify that the cherry-pick in that PR looks correct.

**Pull request merged**
