### PR TITLE
Tracing: sample always in `hack/local-up-cluster.sh`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If the feature gate `KubeletTracing` is enabled, then we should default to a sample rate of 1 million per million, which will sample everything:

https://github.com/open-telemetry/opentelemetry-go/blob/aa868d5/sdk/trace/sampling.go#L107-L110

This helps to easier spin-up a cluster with tracing enabled by exporting `FEATURE_GATES="KubeletTracing=true"`.

Related docs: https://k8s.io/docs/concepts/cluster-administration/system-traces/#kubelet-traces

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
cc @sallyom @dashpole 
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
The `pull-kubernetes-local-e2e` seems to fail constantly over several branches :thinking:

**Comment by dims** [comment]
@saschagrunert let's skip that ci job for now

/skip

**Pull request merged**
