### PR TITLE
Requeue replica sets for availability checks

### PR DESCRIPTION
**Pull request by 0xmichalis**
See https://github.com/kubernetes/kubernetes/issues/35355#issuecomment-264746268 for more details

@kubernetes/deployment @smarterclayton

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot kops aws e2e test this

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this https://github.com/kubernetes/kubernetes/issues/37058

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this https://github.com/kubernetes/kubernetes/issues/35658

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this https://github.com/kubernetes/kubernetes/issues/37974

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this #37058

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this #37058

**Comment by janetkuo** [comment]
@k8s-bot kops aws e2e test this

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
@kargakis I am skipping this PR in my batch cherry pick to 1.5 since there is a merge conflict. Please create a separate cherry pick to `release-1.5` (with conflicts resolved) for this PR ASAP if you want it in 1.5.

**Comment by kargakis** [comment]
> @kargakis I am skipping this PR in my batch cherry pick to 1.5 since there is a merge conflict. Please create a separate cherry pick to release-1.5 (with conflicts resolved) for this PR ASAP if you want it in 1.5.

Opened https://github.com/kubernetes/kubernetes/pull/38242

**Pull request merged**
