### PR TITLE
proxy/userspace: suppress "LoadBalancerRR: Removing endpoints" message

### PR DESCRIPTION
**Pull request by dcbw**
Don't print it when there aren't any endpoints getting removed.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1468420
Fixes: https://github.com/kubernetes/kubernetes/issues/48816

```release-note
NONE
```

@eparis @thockin @kubernetes/rh-networking

### CODE REVIEW

**Review by rajatchopra — APPROVED** [review]
Clean. LGTM.

**Comment by dcbw** [comment]
@thockin @bprashanth this one look OK?

**Comment by eparis** [comment]
/retest
/approve no-issue
(don't think I can override...)

**Pull request merged**
