### PR TITLE
Increase the unit test coverage in pkg/util

### PR DESCRIPTION
**Pull request by asalkeld**
These are easy to test, so lets increase coverage.

### CODE REVIEW

**Comment by MHBauer** [comment]
Question: Is the `testify` library the 'blessed' testing library? I am asking to understand if it's a dependency because other dependencies need it, or if it's a dependency because we want to be using it in new tests. Thanks

**Comment by thockin** [comment]
LGTM

testify is already a dep, so it is fine to use.

**Comment by asalkeld** [comment]
what do I need to do to get this to progress? looks like it needs to run the tests...

**Comment by asalkeld** [comment]
@thockin do you know what I need to do to get the GCE test re-run (is there something I can post in here to trigger a re-test, or do you need to do it)? The error is "googleapi: Error 403: Quota 'CPUS' exceeded. Limit: 700.0, quotaExceeded".

**Comment by thockin** [comment]
@k8s-bot test this: github issue #IGNORE

**Pull request merged**
