### PR TITLE
Considering actually used ports on scheduling pod

### PR DESCRIPTION
**Pull request by chenchun**
This PR makes kubelet 
- report used ports on updating node status
- check port when doing predict check on adding pod

And let `PodFitsHostPorts` considering actually used port on checking host ports conflict.

### CODE REVIEW

**Comment by k1-hedayati** [comment]
I'm having this issue, it would be great if it merged sooner

**Comment by krmayankk** [comment]
Any update on this ? Is this being actively being worked on ?


On Nov 28, 2017, at 1:13 PM, Keyvan Hedayati <notifications@github.com>
wrote:

I'm having this issue, it would be great if it merged sooner

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/53963#issuecomment-347664971>,
or mute the thread

**Comment by chenchun** [comment]
I'll rebase shortly.

**Pull request closed without merging**
