### PR TITLE
Update rs conditions

### PR DESCRIPTION
**Pull request by 0xmichalis**
@bgrant0607 keeps replica set conditions consistent with deployment conditions (https://github.com/kubernetes/kubernetes/pull/19343)

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35529)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@kargakis 

Conditions include 2 times:
1. The time the condition status was last checked. In other conditions, this is lastProbeTime or lastHeartbeatTime.
2. The time the condition status last changed. This is always lastTransitionTime.

I meant that lastUpdateTime should replace (1) -- the time the condition was last checked.

Note that due to clock skew, the 2 times should only be compared if they are provided by the same component running on the same machine, which is hard to guarantee across restarts, etc. The way we usually handle this (e.g., in node controller) is by watching for changes to these values, capturing the locally observed time when they change, and comparing the local times. 

Capturing the times for reporting to the user is useful for understanding what is going on, however, even if they aren't used for controller decision-making.

cc @janetkuo

**Comment by kargakis** [comment]
@bgrant0607 regarding lastTransitionTime for replica sets we need to think what conditions will be transitive and we are going to care about both states (before and after the transition). In Pods for example we care about Ready and NotReady, Initialized and Not, etc.. My main use case for replica set conditions is to expose replica failures (that's why we added a ReplicaFailure condition). I also want to surface ImagePullBackOff and crashlooping pods as similar conditions I am just not sure if they should be separate types of conditions though. Anyway, my point is that with rs conditions we don't care about transition from one status to another, we only care about the existense of the condition, thus I don't see how lastTransitionTime is justified here. At least, if we need it down the road, we can easily add it i think.

**Comment by kargakis** [comment]
I don't want to block anymore on the api so I will leave rs conditions as is for now.

**Comment by bgrant0607** [comment]
@kargakis ImagePullBackOff should not be a condition type. ReplicaFailure makes sense -- that explains why the replica count can't match the desired state. I'd expect another condition to reflect why created replicas don't become Ready. Deployment might want to use that for infant-mortality detection. However, we'd need to think about when/how that condition would be triggered. ImagePullBackOff and CrashLoopBackOff probably aren't the only cases we want to surface. Repeated liveness and/or readiness probe failures might also be relevant, but we probably don't want to start every RS/RC with that condition true.

**Comment by kargakis** [comment]
> However, we'd need to think about when/how that condition would be triggered.

@bgrant0607 I was thinking that we should surface ImagePull and CrashLoop as conditions once all of the pods for a replica set have the same failure mode. Then we should be fairly certain that we can abort early a rollout (helps in infant mortality detection as you already said).

**Pull request closed without merging**
