### PR TITLE
fixed the typo causing incorrect comparison with cVer and cVer; now checking against sVer

### LINKED ISSUE #25252: Incorrect comparison in unversioned.MatchesServerVersion
The following code compares cVer.GitTreeState against itself. The RHS should probably use sVer instead:

```
if cVer.GitVersion != sVer.GitVersion || cVer.GitCommit != sVer.GitCommit || cVer.GitTreeState != cVer.GitTreeState {
	return fmt.Errorf("server version (%#v) differs from client version (%#v)!\n", sVer, cVer)
}
```

```
/src/github.com/kubernetes/kubernetes/pkg/client/unversioned/helper.go:117:79: identical expressions on the left and right side of the '!=' operator
```

### PR DESCRIPTION
**Pull request by grodrigues3**
fixes #25252

### CODE REVIEW

**Comment by grodrigues3** [comment]
I signed it! 

Rather, I changed the email address associated with my commit to be my google email.

**Comment by caesarxuchao** [comment]
Fixes #25252

**Comment by caesarxuchao** [comment]
@grodrigues3 Thanks for the PR! LGTM.

Do you mind if I modify your first comment? You put "fixes #25252" in the release note block, which will generate a release note in the change log, but IMO this PR doesn't require that.

**Comment by grodrigues3** [comment]
Awesome.  My first PR!  And no, I don't mind at all if you modify my comment.  I wasn't sure where to put the 'fixes' comment.

**Comment by caesarxuchao** [comment]
Just remove the template and then make your comment, unless you want to make a release note, which will end up in the changelog of each release :)

**Pull request merged**
