### PR TITLE
Extend a timeout to (hopefully) fix a flake.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/12312 (I hope)

[Analytics]()

### CODE REVIEW

**Comment by brendandburns** [comment]
@spxtr friendly monday morning ping...  it's a flake fix ;)

**Comment by spxtr** [comment]
I think it's fine, but I'm wary of bumping up timeouts to (hopefully) fix flakes. Also, it's really funny that `wait.ForeverTestTimeout` isn't long enough.

**Comment by spxtr** [comment]
@k8s-bot unit test this issue: #24704

**Comment by lavalamp** [comment]
ugh, really? Wait forever * 5? I want to merge this because it's short and safe, but I don't know if I can hold my nose.

**Comment by wojtek-t** [comment]
Wait - I think this will NOT fix anything. Basically:

1. the failures from half-an-year-ago+ were from Shippable, which we no longer use. So we can ignore them (Shippable was known to be extremely slow).

2. However, the last failure failed not because of timeout - it failed because we scheduled pod on the unschedulable node, and the other failure were just consequence of that. So increasing timeout will not help at all with that.

So I really vote for closing this PR.

**Comment by spxtr** [comment]
Sounds reasonable to me. @brendandburns can make the call.

**Comment by brendandburns** [comment]
@wojtek-t can you add your debugging to the issue so that we can figure out how to fix this flake.

Once that's there I'm happy to close this PR.

**Comment by spxtr** [comment]
Assigning to @wojtek-t since you know more about what's going on here than me.

**Comment by wojtek-t** [comment]
@spxtr - I don't knwo anything about this test - I just looked into logs pasted in a bug. But sure - I can try to do debug it next week.

**Pull request closed without merging**
