### PR TITLE
dependencies: update to gomega v1.23.0 and ginkgo v2.4.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Gomega adds support for formatting extensions and StopTrying in matchers. Ginkgo enhances DeferCleanup.

I have already tried the new features and would like to see the dependencies updated first while completing these PRs:
- https://github.com/kubernetes/kubernetes/pull/113298
- https://github.com/kubernetes/kubernetes/pull/112923
- https://github.com/kubernetes/kubernetes/pull/113384

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @dims

### CODE REVIEW

**Comment by pohly** [comment]
check-dependency-stats: no changes

**Comment by aojea** [comment]
the deps job is failing 🤔

**Comment by dims** [comment]
yep, for the record

```
{Script Error ScriptError Check all unwanted dependencies and update its status.
These modules are pinned to versions different than the minimal preferred version.
That means that without replace directives, a different version would be selected,
which breaks consumers of our published modules.
1. Use hack/pin-dependency.sh to switch to the preferred version for each module
2. Run hack/update-vendor.sh to rebuild the vendor directory
3. Run hack/lint-dependencies.sh to verify no additional changes are required

golang.org/x/mod
    pinned:    v0.6.0-dev.0.20220419223038-86c51ed26bb4
    preferred: v0.6.0
    hack/pin-dependency.sh golang.org/x/mod v0.6.0
golang.org/x/term
    pinned:    v0.0.0-20210927222741-03fcf44c2211
    preferred: v0.1.0
    hack/pin-dependency.sh golang.org/x/term v0.1.0
All pinned versions of checked dependencies match their preferred version.}
```

**Comment by pohly** [comment]
Dependencies should be completely updated now.

**Comment by pohly** [comment]
It looks like one network-related unit test is failing reliably with the newer dependencies. I've brought that up in https://kubernetes.slack.com/archives/C0EG7JC6T/p1666860843898949

**Comment by pohly** [comment]
@dims: all tests green, can this get merged?

**Pull request merged**
