### PR TITLE
replace bytes.Compare() with bytes.Equal()

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
replace bytes.Compare() with bytes.Equal(), more idiomatic

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by chendotjs** [comment]
/assign @mikedanese @saad-ali 
PTAL, thanks

**Comment by chendotjs** [comment]
/assign @deads2k 
thanks

**Comment by liggitt** [comment]
there are 11 places we do bytes.Compare ... == or !=

can we replace them all?

**Comment by chendotjs** [comment]
thanks for your advice, I have fixed them all. @liggitt

**Pull request merged**
