### PR TITLE
scheduler_perf: show name of one pending pod in log

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If pods get stuck, then giving the name of one makes it possible to search for it in the log output. Without the name it's hard to figure out which pods got stuck.

#### Special notes for your reviewer:

This was used to find https://github.com/kubernetes/kubernetes/pull/120334

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
The log message in the throughput collector doesn't help when init pods don't get scheduled because that step is not being measured. I'll add more log output...

**Comment by pohly** [comment]
I changed where the pending pod is shown: in the failure message instead of each log line. That should be less noisy overall and ensures that the information is there where it is needed.

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
