### PR TITLE
Format json file with proper indentation

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig scheduling

### CODE REVIEW

**Comment by chendave** [comment]
@damemi @adtac  with the change, we can check the result json file directly without the need to parse the file with other tool.

**Review by sanposhiho — COMMENTED** [review]
looks good
/lgtm

**Comment by oomichi** [comment]
The change seems useful to see the output JSON files.
/lgtm
/approve

**Comment by chendave** [comment]
> The change seems useful to see the output JSON files.

yes, thanks @oomichi for the review!

/retest

**Pull request merged**
