### PR TITLE
Removes deprecated label kubernetes.io/cluster-service in yaml files of kubernetes add-ons. Bug fix #72757

### LINKED ISSUE #72757: Document/cleanup the kubernetes.io/cluster-service='true' label
The `kubernetes.io/cluster-service: "true"` label is sprinkled across over 100 yaml files in the kubernetes repo (according to github search). However, I could not find any documentation around the effect of this label.

After searching the code base, it seems that:
1. The label was being used by the addon manager in the past, but it has since been deprecated.
2. The `kubectl cluster-info` command seems to be the only place where this label is used in the code. It is used to display the addresses of the services that contain this label.

Would it make sense to document this label, and also cleanup the instances of this label that exist on manifests that are not `kind: Service`?

/kind cleanup
/kind docs

### PR DESCRIPTION
**Pull request by ramnar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes deprecated labels in kuberenetes add-ons

**Which issue(s) this PR fixes**:

Remove deprecated label kubernetes.io/cluster-service in yaml files of kubernetes add-ons. Ref #72757

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @ramnar 

please replace `Fixes #72757` with `Ref #72757` if it only fixes partially.
otherwise it will close the issue.

/ok-to-test
/priority backlog

**Comment by ramnar** [comment]
Appreciate your review @neolit123. Updated the comment

**Comment by ramnar** [comment]
@DirectXMan12 please review and approve

**Comment by DirectXMan12** [comment]
this needs a more description title than "Ref xyz".  that's fine to have as part of the description, but PR titles and descriptions should be mostly stand-alone.

**Comment by ramnar** [comment]
@DirectXMan12  Thanks for the feedback. Made the requested changes. Please review

**Comment by MrHohn** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by MrHohn** [comment]
Holding this per https://github.com/kubernetes/kubernetes/issues/72757#issuecomment-476435307.
/hold

**Comment by ialidzhikov** [comment]
See https://github.com/kubernetes/kubernetes/issues/72757#issuecomment-487313543. Is there something that I miss?

**Review by neolit123 — COMMENTED** [review]
@ialidzhikov
/lgtm
 for removing the label from manifests.

but for modifying `kubectl cluster-info` it has to be approved by SIG CLI first.

**Comment by neolit123** [comment]
@MrHohn i think we can unhold this PR.

**Comment by MrHohn** [comment]
Yep, unholding as this doesn't touch any `Service` manifest.
/hold cancel

**Pull request merged**
