### PR TITLE
Deduplicate and consolidate contributing information to community repo

### PR DESCRIPTION
**Pull request by monopole**
* Move remaining community stuff out of kubernetes/kubernetes/README and
   CONTRIBUTING (to kubernets/community/README) so that there's only one thing
   to maintain.
 * Put self-contained things into their own MD files.
 * Have other docs point to those files rather than attempt to repeat their content.
 * Make all docs smaller.

This PR is a companion to kubernetes/community#434

Closes kubernetes/community#420

### CODE REVIEW

**Comment by monopole** [comment]
PTAL @grodrigues3 

This PR is a companion to https://github.com/kubernetes/community/pull/434

**Review by ravisantoshgudimetla — APPROVED** [review]

**Review by idvoretskyi — APPROVED** [review]
LGTM

**Comment by bgrant0607** [comment]
@calebamiles This is docs cleanup. It shouldn't affect the release one way or the other, so I'd like to merge it. Ok to add to milestone? Otherwise, I'd need to manually merge it.

**Pull request merged**
