### PR TITLE
dynamic certs: introduce validation for reloaded certificates

### PR DESCRIPTION
**Pull request by stlaz**
#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
The name of `dynamiccertificates.NewDynamicServingContentFromFiles()` is misleading, suggesting that it can only be used for serving certificates even though it can easily be used to handle client certificates as well as proven by its usage in the aggregator code.

#### Which issue(s) this PR fixes:
Fixes None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by stlaz** [comment]
/triage accepted
per @enj - check cert usages

**Comment by stlaz** [comment]
In the latest patchset, I added unit tests for the dynamic certs and the validation as requested. There are some test failures that I still need to revisit before this can be reviewed again.

**Comment by furkatgofurov7** [comment]
@stlaz hi! Bug Triage for 1.28 release cycle here!


This PR has not been updated for some time, so I'd like to check what's the status. The code freeze is starting [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496) (about 3 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.28, is it still planned for this release?

**Comment by furkatgofurov7** [comment]
> /triage accepted per @enj - check cert usages

@enj can you PTAL?

**Comment by furkatgofurov7** [comment]
@stlaz 👋🏼

This is a reminder, as I informed about it already 2 weeks ago, we are in week 9 currently and the code freeze is starting next week (week 10) at [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496).

This PR looks very close to the finish line, so please make sure that it is on track and have sufficient labels in order to make it to release 1.28 before code freeze is in. Also, let me know if you need any help/assistance.

/cc @deads2k @enj hey folks, can you please help reviewing this PR when you get some spare time, thanks!

**Comment by zelenushechka** [comment]
Hello @enj @stlaz ! 👋🏼
Bug triage for the 1.29 release cycle here!
This PR hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the PR is tagged for 1.29, is it still planned for that release?

**Comment by zelenushechka** [comment]
Hello @enj and @stlaz. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and we want to ensure that each PR has a chance to be merged and issues can be addressed.
Is this issue still targeting the 1.29 release?

**Pull request closed without merging**
