### PR TITLE
Fix typo in comments for func GetFullContainerName

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fix typo in comments.

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
ideally, instead of fixing only this export comment, all export comments has to be fixed or added for this file in a single PR:

https://github.com/kubernetes/kubernetes/pull/87072/files#diff-815325f4d4776cc2282858482b77d5f5R39

https://github.com/kubernetes/kubernetes/pull/87072/files#diff-815325f4d4776cc2282858482b77d5f5R41

https://github.com/kubernetes/kubernetes/pull/87072/files#diff-815325f4d4776cc2282858482b77d5f5R73

https://github.com/kubernetes/kubernetes/pull/87072/files#diff-815325f4d4776cc2282858482b77d5f5R96

**Comment by fenggw-fnst** [comment]
@neolit123 Sorry for late reply. Done, PTAL. Thanks!

**Review by neolit123 — COMMENTED** [review]
/lgtm

to get approval try asking in the #sig-node channel on k8s slack.

**Comment by fenggw-fnst** [comment]
/assign @thockin
Could you PTAL? Thanks!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
