### PR TITLE
refactor: use controller.FilterActivePods in test/e2e/framework/util.go

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

use existing filterActivePods to remove code duplication

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm
/approve
/retest
/priority backlog

**Comment by draveness** [comment]
> thanks
> /lgtm
> /approve
> /retest
> /priority backlog

Thank you @neolit123 !

**Pull request merged**
