### PR TITLE
add --all-resources flag to cluster-info dump

### PR DESCRIPTION
**Pull request by neoseele**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:

- Add a new flag: `kubectl cluster-info dump --all-resources`
- Useful to dump all resources in a cluster in one go.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liggitt** [comment]
a few comments:
* cluster-info is sort of a strange place to hang this... isn't this basically `kubectl get -o json`?
* ignoring namespace is unexpected... it would be useful to be able to get all resources just within a namespace
* discovery can return partial success (some resources in some groups were discovered, while others failed)... outputting the errors, and ultimately exiting with non-zero return code, but also dumping the resources you were able to find would be more useful

/unassign
/assign @soltysh @seans3 
cc @kubernetes/sig-cli-pr-reviews

**Comment by neoseele** [comment]
> * cluster-info is sort of a strange place to hang this... isn't this basically `kubectl get -o json`?
> * ignoring namespace is unexpected... it would be useful to be able to get all resources just within a namespace

Basically this is an attempt to get a cluster resources snapshot without thinking to much about namespaces, just dump everything the api server sees. :D (some resources are not name-spaced, i.e. crd, clusterroles)

I decided to hang this to `cluster-info dump` as the snapshot is also a dump, just dumps a bit more. Also adding a flag instead of adding a sub-cmd is much easier.

> * discovery can return partial success (some resources in some groups were discovered, while others failed)... outputting the errors, and ultimately exiting with non-zero return code, but also dumping the resources you were able to find would be more useful

that's a good point! shall mod the code a bit.

**Pull request closed without merging**
