### PR TITLE
Update events page to v1beta3 in web ui

### PR DESCRIPTION
**Pull request by bcbroussard**
Depends on #8304

cc @jackgr @lavalamp @bgrant0607 @brendandburns

### CODE REVIEW

**Comment by thockin** [comment]
rebase please

**Comment by bgrant0607** [comment]
I'd like to get all of the v1beta3-related PRs ASAP, prior to the 0.18 cut. Please rebase.

**Comment by thockin** [comment]
needs rebase now

**Comment by thockin** [comment]
one-by-one rebase needed

**Comment by bcbroussard** [comment]
@thockin rebased

**Pull request merged**
