### PR TITLE
Move expapi to apis/experimental; fix conversion generators

### PR DESCRIPTION
**Pull request by lavalamp**
Part of #13772

### CODE REVIEW

**Comment by lavalamp** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
Thank you. It looks much cleaner now.

Could you also fix the verify-generate-conversions.sh? Shippable is complaining.

**Comment by lavalamp** [comment]
Rebased and I fixed the verify-{deep-copy,conversion}.sh. But I still have to fix the swagger doc generation. I'll have to do that tomorrow.

**Comment by caesarxuchao** [comment]
Thank you @lavalamp! The changes LGTM. Could you also update this file?
https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-swagger-docs.sh#L57

**Comment by lavalamp** [comment]
OK, all tests pass locally now. PTAL

**Comment by caesarxuchao** [comment]
LGTM. Thank you! I'll apply the label after tests pass.

**Comment by bprashanth** [comment]
@lavalamp @caesarxuchao can you update the doc with instructions on how to get experimental resources in? (specific enough that external contributors don't need handholding would be nice, but we're probably not there yet)

I've been helping a coulple of Huawei contributors and they bumped their head a couple of times. I tried to capture that in https://github.com/kubernetes/kubernetes/pull/13771, but it seems like this change requires further modification.

**Comment by lavalamp** [comment]
@bprashanth good call, docs updated. Also I added a section on making new groups which we'll flesh out in the future.

**Comment by lavalamp** [comment]
Test failed because kube-registry-v0 didn't come up. @ixdy is this a known problem? Or a real failure?

**Comment by lavalamp** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
@caesarxuchao PTAL, tests pass.

@k8s-oncall If you could expedite merging this, that'd be great--it's a big pain to rebase.

**Comment by caesarxuchao** [comment]
Thank you @lavalamp for adding the documentation. LGTM except for one nit. Could you squash and rebase after fixing the nit?

**Comment by lavalamp** [comment]
If I sqaush it, it will be basically impossible to rebase. I rebase this by redoing a few of the commits...

**Comment by lavalamp** [comment]
I can squash some parts.

**Comment by lavalamp** [comment]
This is the minimum I can squash it and still be able to rebase.

**Comment by mikedanese** [comment]
I'll merge on green

**Comment by lavalamp** [comment]
Yay, thanks!

**Pull request merged**
