### PR TITLE
Fix typo of invalide in validation_test.go]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Fix typo of invalide in validation_test.go

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by heqg** [comment]
@thockin ,can you  help to leave  an /ok-to-test message. thanks

**Comment by heqg** [comment]
@mikedanese ,can you help to leave an /ok-to-test message. thanks

**Comment by heqg** [comment]
@MrHohn can you help to leave an /ok-to-test message. thanks

**Pull request merged**
