### PR TITLE
Move Statefulset (previously PetSet) to v1beta1

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: #28718

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**: depends on #35663 (PetSet rename)
cc @erictune @foxish @kubernetes/sig-apps 

**Release note**:

``` release-note
v1beta1/StatefulSet replaces v1alpha1/PetSet.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35731)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot cvm gke e2e test this

**Comment by janetkuo** [comment]
@k8s-bot kubemark e2e test this

**Comment by janetkuo** [comment]
@k8s-bot cvm gce e2e test this

**Comment by janetkuo** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by janetkuo** [comment]
@k8s-bot gci gce e2e test this

**Comment by janetkuo** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Comment by janetkuo** [comment]
Not sure why these 4 tests keep failing to build 

```
Jenkins GCE e2e — Build failed.
Jenkins GCE etcd3 e2e — Build failed.
Jenkins GCI GCE e2e — Build failed.
Jenkins Kubemark GCE e2e — Build failed.
```

**Comment by janetkuo** [comment]
> Not sure why these 4 tests keep failing to build....

So these test failures are because of these errors 
```
error: group map[autoscaling:0xc82031df80 certificates.k8s.io:0xc8203d01c0 extensions:0xc8203d0310 policy:0xc8203d0380 storage.k8s.io:0xc8203d0460 apps:0xc82031dd50 authorization.k8s.io:0xc82031df10 authentication.k8s.io:0xc8203
1ddc0 batch:0xc8203d0150 componentconfig:0xc8203d0230 rbac.authorization.k8s.io:0xc8203d03f0 federation:0xc82031d810 :0xc82031dce0] is already registered
error: group map[federation:0xc820327810 authentication.k8s.io:0xc820327dc0 autoscaling:0xc820327f80 componentconfig:0xc8203da230 storage.k8s.io:0xc8203da460 policy:0xc8203da380 rbac.authorization.k8s.io:0xc8203da3f0 :0xc820327c
e0 apps:0xc820327d50 authorization.k8s.io:0xc820327f10 batch:0xc8203da150 certificates.k8s.io:0xc8203da1c0 extensions:0xc8203da310] is already registered
error: group map[federation:0xc820323810 autoscaling:0xc820323f80 componentconfig:0xc8203d8230 rbac.authorization.k8s.io:0xc8203d83f0 extensions:0xc8203d8310 policy:0xc8203d8380 :0xc820323ce0 apps:0xc820323d50 authentication.k8s
.io:0xc820323dc0 authorization.k8s.io:0xc820323f10 batch:0xc8203d8150 certificates.k8s.io:0xc8203d81c0 storage.k8s.io:0xc8203d8460] is already registered
error: group map[federation:0xc820325810 :0xc820325ce0 authentication.k8s.io:0xc820325dc0 autoscaling:0xc820325f80 batch:0xc8203d6150 policy:0xc8203d6380 apps:0xc820325d50 authorization.k8s.io:0xc820325f10 certificates.k8s.io:0x
c8203d61c0 componentconfig:0xc8203d6230 extensions:0xc8203d6310 rbac.authorization.k8s.io:0xc8203d63f0 storage.k8s.io:0xc8203d6460] is already registered
error: group map[certificates.k8s.io:0xc8203d61c0 componentconfig:0xc8203d6230 extensions:0xc8203d6310 policy:0xc8203d6380 federation:0xc820325810 :0xc820325ce0 authorization.k8s.io:0xc820325f10 batch:0xc8203d6150 rbac.authoriza
tion.k8s.io:0xc8203d63f0 storage.k8s.io:0xc8203d6460 apps:0xc820325d50 authentication.k8s.io:0xc820325dc0 autoscaling:0xc820325f80] is already registered
error: group map[rbac.authorization.k8s.io:0xc8203d83f0 apps:0xc820325d50 authorization.k8s.io:0xc820325f10 autoscaling:0xc820325f80 batch:0xc8203d8150 certificates.k8s.io:0xc8203d81c0 extensions:0xc8203d8310 policy:0xc8203d8380
 federation:0xc820325810 :0xc820325ce0 authentication.k8s.io:0xc820325dc0 componentconfig:0xc8203d8230 storage.k8s.io:0xc8203d8460] is already registered
```
ref #35791, it's likely due to third-party resource discovery code:
> TPR discovery code that is trying to identify TPR versions and hacks them into the list of registered APIs.

**Comment by erictune** [comment]
LGTM, but I understand that you are waiting for a fix, so not applying label.

**Comment by janetkuo** [comment]
1. Include #35840 to see if test failures will be fixed by it.
2. Deleted the following comment in types.go: `StatefulSet is currently in alpha and and subject to change without notice.`

**Comment by janetkuo** [comment]
All green :smile:

**Comment by smarterclayton** [comment]
Ready for label?

**Comment by caesarxuchao** [comment]
@smarterclayton mind lgmt https://github.com/kubernetes/kubernetes/pull/35840 first? It's a dependency.

I'm fine with cherry-picking #35840 into this PR, but I'd like to get proper review on #35840 first.

**Comment by janetkuo** [comment]
I'll wait for #35840

**Comment by erictune** [comment]
Ready to rebase.

**Comment by janetkuo** [comment]
Bumping priority since it's been rebased for several times and it's release blocking and it's blocked by other PR for several days.

**Comment by janetkuo** [comment]
@k8s-bot gci gke e2e test this

**Comment by chrislovecnm** [comment]
@janetkuo when we merging this??

**Comment by janetkuo** [comment]
@chrislovecnm hopefully today. Submit queue is blocked now 😢

**Comment by chrislovecnm** [comment]
SGTM /facepalm

**Pull request merged**
