### PR TITLE
ParsePodFullName():code robustness

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

ParsePodFullName():code robustness

if pod name or namespace name is null, the function can handle it.
Meanwhile update unit test 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@Random-Liu PTAL

**Comment by zhangxiaoyu-zidif** [comment]
ping @Random-Liu

**Pull request merged**
