### PR TITLE
Fix kube-push using gcloud compute instance-groups managed set-instance-template

### PR DESCRIPTION
**Pull request by dchen1107**
GCE cluster update / upgrade is broken due to incompatible gcloud command. This pr should fix that. 

Should this one be cherrypicked?

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @brendandburns @roberthbailey

**Comment by roberthbailey** [comment]
@wojtek-t 

This broke in https://github.com/GoogleCloudPlatform/kubernetes/pull/11692, so it should only be cherry picked if that PR was cherry picked.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by wojtek-t** [comment]
@roberthbailey @dchen1107 
The PR that broke it was cherrypicked in #12192 (as requested by @roberthbailey in https://github.com/GoogleCloudPlatform/kubernetes/pull/11692#issuecomment-127329212 )

BTW - sorry for breaking

**Comment by roberthbailey** [comment]
Thanks (I couldn't remember). Dawn, can you cherry pick this one as well?

**Comment by dchen1107** [comment]
@wojtek-t and @roberthbailey: Sure, thanks!

**Comment by wojtek-t** [comment]
Thanks for fixing it @dchen1107 !

**Pull request merged**
