### PR TITLE
Reduce LOC in kubelet tests

### PR DESCRIPTION
**Pull request by pmorie**
Extract method refactor to save some lines in kubelet tests.

@kubernetes/sig-node

### CODE REVIEW

**Comment by pmorie** [comment]
If we pull the `podWith` methods into a test package there are probably 20-30 other sites in test code in kubelet subpackages that could use it.

**Comment by yujuhong** [comment]
> If we pull the podWith methods into a test package there are probably 20-30 other sites in test code in kubelet subpackages that could use it.

A testing package with useful test fixtures will definitely help.

Thanks for cleaning up the unit tests!

**Comment by pmorie** [comment]
@yujuhong k, I will extract into a test util package in a follow-up, how does `pkg/kubelet/util/testutil` sound?

**Comment by yujuhong** [comment]
@pmorie, how about `pkg/kubelet/util/testing`? This seems more consistent with other testing packages in the codebase.

**Comment by pmorie** [comment]
SGTM @yujuhong

**Comment by pmorie** [comment]
@derekwaynecarr can I get away with e2e-not-required on this?  It only changes units...

**Comment by yujuhong** [comment]
```
ok  	k8s.io/kubernetes/pkg/httplog	1.029s
ok  	k8s.io/kubernetes/pkg/kubectl	3.673s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd	2.501s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/config	2.255s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util	3.448s
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util/editor	1.071s
ok  	k8s.io/kubernetes/pkg/kubectl/resource	1.473s
FAIL	k8s.io/kubernetes/pkg/kubelet [build failed]
ok  	k8s.io/kubernetes/pkg/kubelet/client	1.188s
ok  	k8s.io/kubernetes/pkg/kubelet/cm	1.059s
ok  	k8s.io/kubernetes/pkg/kubelet/config	1.321s
```
Failing kubelet unit tests.

**Comment by pmorie** [comment]
omg, I will fix.

**Comment by saad-ali** [comment]
Manually merging low small low risk PRs to drain submit queue

**Pull request merged**
