### PR TITLE
[WIP] Implement TeardownPressure Predicate

### PR DESCRIPTION
**Pull request by poelzi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:

Currently, the scheduler only considers active container resources for node resources, but ignores the io constrain a container under removal causes.

If the workload consists mostly of short lived containers, this additional workload causes problems.
I the container created lots of files that need to be removed, stalls in the docker backend can cause
a runaway effect, in which kubernetes considers a node best choice for scheduling, while in reality,
dozens of container in terminating state have accumulated.

The new predicate counts the number of containers in removing state. If the value reaches the kubelet maximum, it sets NodeTeardownPressureCondition true. The scheduler will not schedule any new containers while the flag is active, preventing node overload.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

* Add maxTeardown kubelet variable. Maximum number of concurrent container removals until a node is considered busy.


```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
Sounds interesting @poelzi !

Is there a KEP or tracking issue that interested community members can look at for more background?

**Comment by poelzi** [comment]
@mattjmcnaughton I did not know of the KEP process, the patch was is basically the third iteration for stabilizing our Kubernetes workload.

We try to stabilize the [elastic.io](https://www.elastic.io/) workload in which we found a serious flaw in the kubernetes scheduler which can easily cause node and cluster unavailability. It very much depends on the volume backend CPU usage etc, but in general following workload crashes Kubernetes:

1. After starting of the container, download a very large archive with 100ks of files.
2. Do something very minor, short lived
3. Exit

If for example the jobs framework is used, as soon as the container exists, a new container is spawned. Docker however is still busy removing the files from the overlay. More and more termination processes start to pile up, we have seen 70 on our test. IO becomes totally congested and the new pods take ages to spawn. Kubernetes scheduler however still finds this node the best fit for the next container, even when another node may have much less load. 

This behavior was also seen in different cloud providers, only very large clusters seem not to suffer total devastation in this workload.

By removing the assumption that container removal is a free operation, each node is now capable of limiting this workload. In my first iterations I transported the number of containers under removal to the scheduler and tried to use it there. This caused lots of increased complexity for a very seldom but serious corner case. Using the Condition framework and a local kubelet limit became the most minimal and flexible solution that should prevent clusters from collapsing on this kind of workload.

**Comment by mattjmcnaughton** [comment]
> @mattjmcnaughton I did not know of the KEP process, the patch was is basically the third iteration for stabilizing our Kubernetes workload.
> 
> We try to stabilize the [elastic.io](https://www.elastic.io/) workload in which we found a serious flaw in the kubernetes scheduler which can easily cause node and cluster unavailability. It very much depends on the volume backend CPU usage etc, but in general following workload crashes Kubernetes:
> 
>     1. After starting of the container, download a very large archive with 100ks of files.
> 
>     2. Do something very minor, short lived
> 
>     3. Exit
> 
> 
> If for example the jobs framework is used, as soon as the container exists, a new container is spawned. Docker however is still busy removing the files from the overlay. More and more termination processes start to pile up, we have seen 70 on our test. IO becomes totally congested and the new pods take ages to spawn. Kubernetes scheduler however still finds this node the best fit for the next container, even when another node may have much less load.
> 
> This behavior was also seen in different cloud providers, only very large clusters seem not to suffer total devastation in this workload.
> 
> By removing the assumption that container removal is a free operation, each node is now capable of limiting this workload. In my first iterations I transported the number of containers under removal to the scheduler and tried to use it there. This caused lots of increased complexity for a very seldom but serious corner case. Using the Condition framework and a local kubelet limit became the most minimal and flexible solution that should prevent clusters from collapsing on this kind of workload.

Thanks for the background @poelzi :) I definitely don't have all the context that you do, but from what I read, it seems like a sensible change worth pursuing. Thanks for all your work in investigating and determining a lighter weight solution.

My guess is that since your proposed change involves changes to public API, you're highly encouraged (or required... not positive) to have an associated KEP. See https://github.com/kubernetes/enhancements for more info about the KEP process.

cc @derekwaynecarr @dchen1107 to confirm on the sig/node end :)

**Comment by poelzi** [comment]
Proposed KEP: https://github.com/kubernetes/enhancements/pull/1168

**Comment by mattjmcnaughton** [comment]
On Wed, Jul 24, 2019 at 10:58:39AM -0700, Daniel Poelzleithner wrote:
> Proposed KEP: https://github.com/kubernetes/enhancements/pull/1168
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/80085#issuecomment-514735852

Thanks!

**Comment by poelzi** [comment]
It is really sad that the kubernetes community does not care about denial of service attacks

**Pull request closed without merging**
