### PR TITLE
Add namespace-{list, create, delete} actions to the kubernetes-master layer

### LINKED ISSUE #43712: Add namespace management actions to kubernetes-master juju layer
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

kubernetes-master layer should include actions for namespace magement. I think we should get:
 * namespace-list
 * namespace-create
 * namespace-delete

I started working on it here:
https://github.com/jacekn/kubernetes/tree/artisinal-1.5.3-namespaces

### PR DESCRIPTION
**Pull request by jacekn**
**What this PR does / why we need it**:

This PR adds namespace-{list,create,delete} actions to the juju kubernetes-master layer.

**Which issue this PR fixes**: fixes #43712

**Special notes for your reviewer**:

Original PR https://github.com/juju-solutions/kubernetes/pull/109

**Release note**:

```
Add  namespace-{list,create,delete} actions to the juju kubernetes-master layer
```

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
tag me when LGTM

**Comment by mbruzek** [comment]
Yes this code looks valid. The tests pass. 
/lgtm

**Pull request merged**
