### PR TITLE
 Test_managerImpl_processShutdownEvent this Test case run failed

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
https://github.com/kubernetes/kubernetes/issues/109848
UT test case error

image

#### Which issue(s) this PR fixes:

https://github.com/kubernetes/kubernetes/issues/109848

#### Special notes for your reviewer:
Only when the set time is short enough, when the pod has not been killed and the time has come, will the following code be entered
case <-timer.C():
klog.V(1).InfoS("Shutdown manager pod killing time out", "gracePeriod", group.ShutdownGracePeriodSeconds, "priority", group.Priority)
}
When I modified it, the execution succeeded
image

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by muyangren2** [comment]
> Hi @muyangren2 can you link your PR with the corresponding issue #109848 ? Also add an empty release-note. I will add this to the triage board for this week... /ok-to-test

Thanks, I didn't find the PR associated with it before, now I've modified it

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm
/release-note-none

**Comment by muyangren2** [comment]
@brianpursley  Can you review it for me? If there is no problem, can you  merge it? thank you very much

**Comment by brianpursley** [comment]
I don't understand how reducing the grace period helps.  Here it is already using fakeClock to simulate 60 seconds inside `killPodFunc`: 
https://github.com/kubernetes/kubernetes/blob/7f55a0bae084eada532227f56b0481420595c045/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L677-L680

Therefore, it seems like grace periods of only 10 or 20 seconds should be sufficient to trigger the timeout, right?  It shouldn't make any difference as long as it is less than 60 seconds.

---

My theory, from looking at the code in `processShutdownEvent`:

This seems more like a race between the go funcs inside the for loop and the timer that is started AFTER the go funcs are initiated.  It is possible for the go funcs to complete, and the associated waitgroups to complete, before the timer is created, so doneCh is already triggered when it reaches the select.

**Comment by bobbypage** [comment]
I agree with @brianpursley in https://github.com/kubernetes/kubernetes/pull/111209#issuecomment-1198721192. I'm not clear how minimizing the time will avoid the race...

**Comment by SergeyKanzhelev** [comment]
/close

this is not being looked at for a long time. Please re-open if you plan to work on this

**Pull request closed without merging**
