### PR TITLE
Support --context flag completion for kubectl

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:

With this PR, `--context` flag completion is supported for kubectl.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov ptal

**Comment by stevekuznetsov** [comment]
Seems reasonable

**Comment by deads2k** [comment]
Thanks @superbrothers this will be a nice improvement.

**Pull request merged**
