### PR TITLE
hack/verify-staging-client-go.sh: fail verbosely if working dir is dirty

### PR DESCRIPTION
**Pull request by sttts**
Fail early and show verbose error message if repository is dirty.

### CODE REVIEW

**Comment by luxas** [comment]
LGTM, thanks a lot! I would really have needed this when debugging https://github.com/kubernetes/kubernetes/pull/41721 and didn't think it was something wrong with my PR due to the error message. However, as you pointed out, it was :), but a very non-obvious problem.
Should be updated now, and with this change this will be easier to spot in the future.

**Comment by sttts** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
