### PR TITLE
skip idleTimeout erros when deleting azure LB

### LINKED ISSUE #75356: kube-controller-manager is stucking in deleting Azure LB because of wrong idle timeout set
**What happened**:

When the Idle Timeout annotation was set to "3" which isn't a supported case, kube-controller-manager is stuck in deleting Azure LB. New service with the same name couldn't be created again even without the annotation.

**What you expected to happen**:

New service should be created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "3"
spec:
  type: LoadBalancer
  loadBalancerIP: "51.145.136.123"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: nginx
```

```sh
kubectl create -f nginx.yaml
kubectl get svc

kubectl delete -f nginx.yaml
kubectl get svc

kubectl create -f nginx.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug

### PR DESCRIPTION
**Pull request by yastij**
**What type of PR is this?**

/kind bug
/priority important-soon

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #75356

**Special notes for your reviewer**:
/assign @feiskyer 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@yastij pls run `hack/update-gofmt.sh` to fix the goftm issue, thanks.

**Review by feiskyer — COMMENTED** [review]
the changes lgtm. could you fix the gofmt errors?

**Comment by yastij** [comment]
cc @feiskyer

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
