### PR TITLE
Add set subcommand to update resource container entrypoint

### PR DESCRIPTION
**Pull request by yland**
**What this PR does / why we need it**:
Adds `entrypoint` set subcommand to enable update for resource container entrypoint command and arguments.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by thockin** [comment]
Assign back to me once it is LGTM'ed and ready for approval.

**Comment by apelisse** [comment]
You need to `Run ./hack/update-bazel.sh`.

Looks like github.com/google/shlex is using "COPYING" as the name for their copyright file. Maybe you should improve the test-infra script that checks for that, since Github is smart enough to find the copyright information.

**Comment by apelisse** [comment]
You also seem to have a bug somewhere while compiling something:
```
W0214 21:18:15.477] # k8s.io/kubernetes/pkg/kubectl/cmd/set
W0214 21:18:15.479] pkg/kubectl/cmd/set/set_entrypoint.go:116:17: cannot use f.PrintSuccess (type func(bool, io.Writer, string, string, bool, string)) as type func(meta.RESTMapper, bool, io.Writer, string, string, bool, string) in assignment
W0214 21:20:01.199] Traceback (most recent call last):
W0214 21:20:01.199]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 170, in <module>
W0214 21:20:01.200]     main(ARGS.branch, ARGS.script, ARGS.force, ARGS.prow)
W0214 21:20:01.200]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 138, in main
W0214 21:20:01.200]     check(*cmd)
W0214 21:20:01.200]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 54, in check
W0214 21:20:01.201]     subprocess.check_call(cmd)
W0214 21:20:01.201]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0214 21:20:01.201]     raise CalledProcessError(retcode, cmd)
```

**Comment by apelisse** [comment]
Yeah, looks like this is fixed somehow. But you have a couple of things to improve in the verify script.

You can run these locally by doing `hack/verify-all.sh` from Kubernetes repo root dir.

**Pull request closed without merging**
