### PR TITLE
rkt: Fix hostnetwork.

### LINKED ISSUE #24235: rktnetes doesn't setup resolv.conf and hosts correctly for hostNetwork pods
Currently we write the same /etc/resolv.conf for every pod based on cluster-dns, this is incorrect, k8s depends on docker's default behavior of essentially mounting in the hosts version of those files.  This prevents master components from working correctly if run under rkt

I've looked at the code and can't seem to figure out how to make it work right,  tried specifying the files on the command line but it didn't work (https://github.com/coreos/rkt/issues/2418)

@yifan-gu

### PR DESCRIPTION
**Pull request by yifan-gu**
Mount hosts' /etc/hosts, /etc/resolv.conf, set host's hostname
when running the pod in the host's network.

Fix #24235 

cc @kubernetes/sig-node

### CODE REVIEW

**Comment by yifan-gu** [comment]
Rebased the master to include #24303

**Comment by yifan-gu** [comment]
@sjpotter Could you take a look please?

**Comment by euank** [comment]
LGTM, though this also might change in the future depending on https://github.com/coreos/rkt/issues/2430

**Comment by yifan-gu** [comment]
@euank I documented that in the code.

**Pull request merged**
