### PR TITLE
update smd to 4.2.3

### LINKED ISSUE #109099: apiserver: Request for a custom resource leads to > 1000% CPU usage increase for more than 10min
### What happened?

We observe a high CPU usage of apiserver replicas while other replicas are idling:

```
$ k top po -l role=apiserver
kube-apiserver-786785f6fc-q2fwc               49m          737Mi
kube-apiserver-786785f6fc-r2bxz               50m          690Mi
kube-apiserver-786785f6fc-tbph4               11387m       898Mi
kube-apiserver-786785f6fc-zjfvj               35m          544Mi
```

After investigations we managed to drill down to a custom resource create/update requests that cause this high CPU usage (See the steps to reproduce for more details). It makes sense to mention that the above `k top po` output is from a single Node cluster.

We observe that after such request, the CPU usage does not cool down in seconds or a minute. We see that an apiserver replica is affected by high CPU usage for 10-20min. So it takes 10-20min until the apiserver replica's CPU usage goes down again to values from before the request.

Note also the huge imbalance between the apiserver replica's CPU usage. The replica that get's the requests from the client that operates on the custom resources vs the other 3 replicas that are simply idling wrt CPU usage.

### What did you expect to happen?

I would expect a create request for a custom resource to do not fail with a timeout after 30 seconds.
I would expect such request to do not cause > 1000% CPU usage increase for the concrete apiserver replica for more than 10min.

### How can we reproduce it (as minimally and precisely as possible)?

Example CRD and CR can be found in https://gist.github.com/ialidzhikov/a27fdcea78bd3a0fe726b25c0dfc53c0.

1. Create the `clusterserviceplans.servicecatalog.k8s.io` CRD

   ```
   $ k create -f https://gist.githubusercontent.com/ialidzhikov/a27fdcea78bd3a0fe726b25c0dfc53c0/raw/244d78024c31b3ebd870319f83fe53455f2b374c/clusterserviceplans-crd.yaml
   ```
   
2. Try to create a CR:

   ```
   $ k create -f https://gist.githubusercontent.com/ialidzhikov/a27fdcea78bd3a0fe726b25c0dfc53c0/raw/244d78024c31b3ebd870319f83fe53455f2b374c/clusterserviceplan-sample.json --dry-run=server
   ```
   
   Make sure that this create requests times out after >30 seconds with:
   ```
   (on K8s 1.21.10)
   Error from server (Timeout): error when creating "clusterserviceplan-sample.json": Timeout: request did not complete within requested timeout context deadline exceeded
   ```
   ```
   (on K8s 1.20.15)
   Error from server (Timeout): error when creating "clusterserviceplan-sample.json": Timeout: request did not complete within requested timeout 34s
   ```
   
3. Make sure that the apiserver replicas CPU usage is increased by 1000%.

   Screenshot 2022-03-29 at 11 38 39
   
   The graph confirms the CPU spike. Before the dry-run create request the apiserver replicas CPU usage was avg. `40-50m`. After the create request it went up to more than `1200m`. And this high CPU usage lasts for around 10-15min and it takes apiserver to cool down such high amount of time. The apiserver container does not have any cpu limits set.
   Note that this graph is from an idling cluster and the graph demonstrates the reflections on the CPU usage of single apiserver replica for ONLY 1 dry-run create request. Now, image the CPU usage on a busy cluster with a controller that operates on such custom resources.

### Anything else we need to know?

Maybe related issue - https://github.com/kubernetes/kubernetes/issues/102749. But we are already running K8s versions that have the fix for this issue.

I am able to reproduce the issue on 1.18.20, 1.19.16, 1.20.15, 1.21.10, 1.22.7 and 1.23.4.
I am NOT able to reproduce on 1.17.17.

### Kubernetes version

<details>

```console
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-02-16T11:18:16Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"
```

I am able to reproduce the issue on 1.18.20, 1.19.16, 1.20.15, 1.21.10, 1.22.7 and 1.23.4.
I am NOT able to reproduce on 1.17.17.
</details>

### Cloud provider

<details>
AWS, but I don't think it really matters for the context of this issue.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Gardener
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alexzielenski**
brings in fixes to exponential recursion bug, adds field level override ability to support another backport effort

Comparison between two versions: https://github.com/kubernetes-sigs/structured-merge-diff/compare/v4.2.1..v4.2.3

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

1. Fixes exponentially expanding recursion bug when first creating an object with a fully deduced type. Details: https://github.com/kubernetes-sigs/structured-merge-diff/pull/222. 

2. Adds ability to override `structType` annotation with field-level references

#### Which issue(s) this PR fixes:

fixes #109099
required for #110495

#### Special notes for your reviewer:

Ran

```
hack/pin-dependency.sh sigs.k8s.io/structured-merge-diff/v4 v4.2.3
hack/update-internal-modules.sh
hack/update-vendor.sh
```

#### Does this PR introduce a user-facing change?

```release-note
Fix performance issue when creating large objects using SSA with fully unspecified schemas (preserveUnknownFields).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @apelisse

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

thanks for the fix!

**Comment by aojea** [comment]
:thinking: 
/lgtm
/approve

**Comment by aojea** [comment]
> @alexzielenski: PR needs rebase.

ahh, it needs rebase, I was surprised the PR didn't pick the approve and lgtm labels from Jordan

**Comment by alexzielenski** [comment]
rebased and also changed 4.2.2 to 4.2.3

**Pull request merged**
