### PR TITLE
Restore cAdvisor prometheus metrics to the main port

### LINKED ISSUE #48483: After upgrading to 1.7.0, Kubelet no longer reports cAdvisor stats
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report.

 /kind bug

**What happened**:

I upgraded a cluster from 1.6.6 to 1.7.0.  Kubelet no longer reports cAdvisor metrics such as container_cpu_usage_seconds_total on its metrics endpoint (https://node:10250/metrics/).  Kubelet's own metrics are still there.   cAdvisor itself (http://node:4194/) does show container metrics.

**What you expected to happen**:

Nothing in the release notes suggests this interface has changed, so I expected the metrics would still be there.

**How to reproduce it (as minimally and precisely as possible)**:

I don't know, but I can reproduce it reliably on this cluster; rebooting or reinstalling nodes doesn't make a difference.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release): CoreOS 1409.5.0
- Kernel (e.g. `uname -a`): Linux staging-worker-710d.c.torchkube.internal 4.11.6-coreos-r1 #1 SMP Thu Jun 22 22:04:38 UTC 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
- Install tools: Custom scripts.
- Others:

### PR DESCRIPTION
**Pull request by smarterclayton**
But under a new path - `/metrics/cadvisor`. This ensures a secure port still exists for metrics while getting the benefit of separating out container metrics from the kubelet's metrics as recommended in the linked issue.

Fixes #48483

```release-note-action-required
Restored cAdvisor prometheus metrics to the main port -- a regression that existed in v1.7.0-v1.7.2
cAdvisor metrics can now be scraped from `/metrics/cadvisor` on the kubelet ports.
Note that you have to update your scraping jobs to get kubelet-only metrics from `/metrics` and `container_*` metrics from `/metrics/cadvisor`
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-instrumentation-pr-reviews

**Comment by brancz** [comment]
While I do agree with the general idea that these two sets of metrics should be separate, this does not restore the previous state. Is that acceptable or considered a breaking change?

**Comment by smarterclayton** [comment]
We don't guarantee backward compatibility for metrics, although we strive.  With this change to gather metrics from a new cluster is just a new scrape job, which while annoying... is not the end of the world.  An admin who hasn't upgraded to 1.7 could reasonably anticipate and set a scrape job ahead of time.

**Comment by fgrzadkowski** [comment]
@kubernetes/sig-instrumentation-bugs @piosz

**Comment by luxas** [comment]
This is a cherrypick candidate for v1.7.3 -- v1.7.2 is already being built today.
@smarterclayton I added a release note that could be used, feel free to modify the wording as you like later today. Added the release note so that this PR could get merged ASAP now that we have approval from sig-instrumentation.

cc @wojtek-t

**Comment by brancz** [comment]
@wojtek-t @luxas @smarterclayton ^ is this being taken care of?

**Comment by wojtek-t** [comment]
@brancz I don't understand your question. What do you mean? If you're asking about removing "cherrypick-candiate" label, this is no longer needed, because this has already been cherrypicked to 1.7 rbanch and will be part of 1.7.3 patch release.

**Comment by brancz** [comment]
Sorry about that, I misread it. All good.

**Pull request merged**
