### PR TITLE
Add properties file for cos-docker-validation test job

### PR DESCRIPTION
**Pull request by kewu1992**
**What this PR does / why we need it**: 
This is forked from test/e2e_node/jenkins/docker_validation/jenkins-validation.properties. It is used for COS docker validation test.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by kewu1992** [comment]
@Random-Liu

**Comment by wonderfly** [comment]
@k8s-bot ok to test

**Pull request merged**
