### PR TITLE
Fix KEP link for issue 101008

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
this fix part of #101008
#### Which issue(s) this PR fixes:

xref #101008

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — CHANGES_REQUESTED** [review]
/kind cleanup
/triage accepted
/priority backlog

There's a few more places that the change needs to be made (e.g. `staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go`)

Can you look at https://cs.k8s.io/?q=runtime-class.md&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes ?

**Comment by lojies** [comment]
> /kind cleanup
> /triage accepted
> /priority backlog
> 
> There's a few more places that the change needs to be made (e.g. `staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go`)
> 
> Can you look at https://cs.k8s.io/?q=runtime-class.md&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes ?

i have changed these files,can you review again, thanks.

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
Some of them are fixed in #99391.

**Pull request closed without merging**
