### PR TITLE
Clarify a few validation messages

### PR DESCRIPTION
**Pull request by thockin**
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Assigning to @BenTheElder since we talked about validation error messages this week :)

**Comment by aojea** [comment]
/lgtm

got it `field.Required` and the messages are redundant

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
neat a panic:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112582/pull-kubernetes-integration/1588993116264730624
/retest

**Comment by aojea** [comment]
those panics should not be there, open a thread in slack #sig-testing , but most probably we need to investigate more

**Comment by BenTheElder** [comment]
yeah, I'd assume not :-)

**Pull request merged**
