### PR TITLE
Automated cherry pick of #52260

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #52260  on release-1.7.
#52260 : fix azure disk mounter issue
@jdumars @rootfs for awareness 

**Release note**:

```
Fix issue of mounting azure disks when kubelet restarts in the meantime.
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@andyzhangx @jdumars - please add a user-friendly release note to the original PR.

**Comment by andyzhangx** [comment]
@wojtek-t I have added release note to the original PR #52260

**Comment by wojtek-t** [comment]
@andyzhangx - sorry, I think I wasn't clear. The release note has to contain user-friendly bug description this PR is fixing.

**Comment by andyzhangx** [comment]
@wojtek-t should be ok now, thx

**Pull request merged**
