### PR TITLE
Support dynamically set log level for kube-controller-manager

### PR DESCRIPTION
**Pull request by borgerli**
For now, the kube-apiserver, kubelet and kube-scheduler components all support dynamically setting log level. 

This function is really helpful and convenient for troubleshooting with production clusters, especially for cases that problems disappear if we change --v parameter and then restart the component.

This PR is for kube-controller-manager.

```release-note
Expose `/debug/flags/v` to allow dynamically setting log level for kube-controller-manager.
```

### CODE REVIEW

**Comment by cici37** [comment]
Hi @borgerli , Thank you for your PR.
I read some discussions in https://github.com/kubernetes/kubernetes/pull/68780, 
https://github.com/kubernetes/kubernetes/pull/83910, https://github.com/kubernetes/kubernetes/pull/63777, https://github.com/kubernetes/kubernetes/pull/64601, and have some questions:
1. Is the concerns raised in https://github.com/kubernetes/kubernetes/pull/68780 be addressed now?
2. Is there security improvement has been made or plan to take regarding with the security concerns?
3. I am not quite understand about the importance/urgent/value of this change as well.

Besides that, it would be awesome if you could put more details on the pr description by following the pr sample. And please also add the release note (something like `Expose `/debug/flags/v` to allow dynamically set glog logging level for kube-controller-manager.`). Thank you

**Comment by borgerli** [comment]
@cici37 Thank for reivew.  For you questions, 
>1. Is the concerns raised in #68780 be addressed now?

This feature could be turned off by setting `--profiling` to false

>2. Is there security improvement has been made or plan to take regarding with the security concerns?

Yes, the simple way to improve security for this feature, is that we could add a boolean `isSecureServing` parameter to `NewBaseHandler` method, and only install the handler  when `isSecureServing` is true.
```
	if c.SecureServing != nil {
		unsecuredMux = genericcontrollermanager.NewBaseHandler(&c.ComponentConfig.Generic.Debugging, checks...)
		handler := genericcontrollermanager.BuildHandlerChain(unsecuredMux, &c.Authorization, &c.Authentication)
		// TODO: handle stoppedCh returned by c.SecureServing.Serve
		if _, err := c.SecureServing.Serve(handler, 0, stopCh); err != nil {
			return err
		}
	}
```

Actually, the merged PR #83910 for scheduler faces the same problem. I suggest that we address this when insecure serving is completely removed from kubernetes components.

>3. I am not quite understand about the importance/urgent/value of this change as well.

This feature is valuable in following situations: 
1) troubleshooting issues in production environment, especially for customer's clusters. Some customers did not allow restarting at all.
2) troubleshooting intermittent issues which go away after process retarted.

**Comment by borgerli** [comment]
@cici37 @jpbetz @andrewsykim Could you please help review this?  Thank you.

**Comment by jpbetz** [comment]
Looks the same as we already do for the other components.

/lgtm

**Comment by borgerli** [comment]
@jpbetz  @andrewsykim  Could you please help review? Thanks.

**Comment by jpbetz** [comment]
I've LGTMd but don't have approval privileges for this code.

@andrewsykim would you approve?

**Comment by borgerli** [comment]
@andrewsykim Could you please help review? Thanks.

**Pull request closed without merging**
