### PR TITLE
Revert "Set resource limit for both heapster and influxdb container b…

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts GoogleCloudPlatform/kubernetes#10260

cc/ @roberthbailey

### CODE REVIEW

**Comment by dchen1107** [comment]
I don't think we have enough time to fix this for v0.20 release by providing better resource requirements based on number of nodes in a cluster since we are cutting it now. I decided to revert this, and re-introduce a proper configuration later. 

cc/ @bgrant0607 @davidopp

**Comment by roberthbailey** [comment]
Waiting for passing tests...

**Comment by dchen1107** [comment]
#10406

**Comment by dchen1107** [comment]
We should include this to v0.20.1 #10409

**Comment by roberthbailey** [comment]
Jenkins e2e passed, so going to merge the revert.

**Pull request merged**
