### PR TITLE
code initiate before use in controller event handler

### LINKED ISSUE #52064: Should initiate before real use in controllers
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
Although  #51633 solve this kind of issue<use some field methods before initiate>. But from coding convention, I think these code should be modified in related controllers. like deployment, daemon, etc 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
from the view of code convention, we should only use variable after initiated, Only this way, no panic will occur. Other way is not very directly perceived.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52064

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
only one of the methods seems to meet the above criteria, but ok

/lgtm

**Comment by bowei** [comment]
You're going to have to find approvers for the other components that you are touching.

**Comment by hzxuzhonghu** [comment]
cc @mikedanese would you take a look?

**Comment by hzxuzhonghu** [comment]
ping @janetkuo @nikhiljindal

**Pull request closed without merging**
