### PR TITLE
[DNM] [WIP] widen device plugin restart timings

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### Which issue(s) this PR fixes:

Related to #106635

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
wanna close this out @endocrimes ?

**Comment by endocrimes** [comment]
yup - need to try something else for this

/close

**Pull request closed without merging**
