### PR TITLE
Automated cherry pick of #73443: update json-patch to pick up bug fixes

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #73443 #73713 #73805 #74000 on release-1.12.

#73443: update json-patch to pick up bug fixes
#73713: Importing latest json-patch.
#73805: Adding a limit on the maximum bytes accepted to be
#74000: Limit the number of operations in a single json patch to be

```release-note
#73805: 
kube-apiserver: a request body of a CREATE/UPDATE/PATCH/DELETE resource operation larger than 100 MB will return a 413 "request entity too large" error.

Custom apiservers built with the latest apiserver library will have the 100MB limit on the body of resource requests as well. The limit can be altered via ServerRunOptions.MaxRequestBodyBytes.

The body size limit does not apply to subresources like pods/proxy that proxy request content to another server.

#74000:
The apiserver, including both the kube-apiserver and apiservers built with the generic apiserver library, will now return 413 RequestEntityTooLarge error if a json patch contains more than 10,000 operations.
```

### CODE REVIEW

**Comment by liggitt** [comment]
these test helpers did not exist in 1.12

**Comment by liggitt** [comment]
/lgtm
/approve

can we set an explicit release note on this PR?

**Comment by caesarxuchao** [comment]
Release notes copied.

**Comment by cjcullen** [comment]
Should we add the explicit release note here and https://github.com/kubernetes/kubernetes/pull/74106 as well?

**Comment by caesarxuchao** [comment]
@feiskyer what else is required for this cherry pick? liggitt has lgtm'ed it. Do I need to get lgtm from sttts as well? Thanks.

**Comment by feiskyer** [comment]
Need top-level approval. Let me do that instead since it's only vendor updates.

**Comment by caesarxuchao** [comment]
Thanks, @feiskyer.

**Pull request merged**
