### PR TITLE
Removed redundant spaces in a comment

### PR DESCRIPTION
**Pull request by plallin**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

This PR removes 2 redundant spaces in `cmd/hyperkube/main.go`

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

N/A

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Comment by PaulineLc** [comment]
I'm removing `[KubeCon PR Tutorial]` as per advice from @roycaihw as this PR is an actual merge candidate :-)

**Comment by nikhita** [comment]
/remove-kind flake
/kind cleanup

/assign @liggitt 
for approval

**Pull request merged**
