### PR TITLE
Update go-jose dependency in apiserver

### PR DESCRIPTION
**Pull request by lachieggg**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR upgrades go-jose to v3 in apiserver to fix some potential DoS attacks 

https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOJOSEGOJOSE-6070736

#### Which issue(s) this PR fixes:
(https://github.com/kubernetes/kubernetes/issues/123252)

#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

### CODE REVIEW

**Comment by enj** [comment]
The specific issue is https://github.com/go-jose/go-jose/commit/65351c27657d58960c2e6c9fbb2b00f818e50568 / https://github.com/go-jose/go-jose/issues/64 which does not impact Kube at all because we have no codepath that uses JWEs.  In order to update this dep, you have to update quite a lot of code in k/k since it is used by go-oidc.  https://github.com/kubernetes/kubernetes/pull/117437#issuecomment-1520735668 and https://github.com/kubernetes/kubernetes/pull/114772#pullrequestreview-1515045221 tried to do that, and failed because the change is non-trivial to review and there isn't any strong motivation to make any changes to these deps (there is no actual security issue).

**Comment by cblecker** [comment]
Closing based off the above
/close

**Pull request closed without merging**
