### PR TITLE
Fix unready endpoints bug introduced in #50934

### LINKED ISSUE #51128: [e2e test failure][sig-network] Proxy version v1 should proxy through a service and a pod [Conformance]
This test has started failing on our e2e test suite, erroring out with "Failed to get endpoints..."

https://k8s-testgrid.appspot.com/release-master-blocking#gce
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce

Example failures

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:276
Expected error:
    <*errors.errorString | 0xc420d7c9d0>: {
        s: "Failed to get endpoints for e2e-tests-proxy-h6zvv/proxy-service-28w55",
    }
    Failed to get endpoints for e2e-tests-proxy-h6zvv/proxy-service-28w55
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:155
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/12667#sig-network-proxy-version-v1-should-proxy-through-a-service-and-a-pod-conformance
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/13134#sig-network-proxy-version-v1-should-proxy-through-a-service-and-a-pod-conformance

cc @kubernetes/release-maintainers 
cc @kubernetes/sig-network-bugs

### PR DESCRIPTION
**Pull request by joelsmith**
**What this PR does / why we need it**:

A pod status change of unready -> ready results in a move from the endpoint's
unready endpoint addresses to its ready addresses so if a pod update contains
an unready -> ready status change, the endpoint needs to be updated. This PR is
needed because one type of shortcut added in #50934 ended up being a shortcut
that can't be taken.

**Which issue this PR fixes**: fixes #51128

**Special notes for your reviewer**:

N/A

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
cc @thockin @eparis

**Comment by derekwaynecarr** [comment]
logic change makes sense to me.

/lgtm

**Comment by derekwaynecarr** [comment]
absent this fix, the queue may be unrealiable, labeling as critical fix.

**Comment by justinsb** [comment]
This fix is plainly needed so feel free to force-merge even if kops continues to flake, but these problems started around the time of #50934, so I think either it's a coincidence or some more fixes may be needed.

I guess the alternative is a revert, but #50934 sure sounds good.

**Comment by eparis** [comment]
It'll ruin a batch but this is easy to see it doesn't make it worse than #50934. So I think I'll hit the button.

**Comment by joelsmith** [comment]
Thanks for merging. FYI, it had passed the flaky test once and was in the merge queue when it got merged, so I'm pretty confident that #51128 is resolved now that you've merged it.

Sorry to all whose PRs were hampered by having this test broken during the last 24 hours!

**Pull request merged**
