### PR TITLE
fix TestManifestFilesAreEqual flake

### LINKED ISSUE #2932: resolve TestManifestFilesAreEqual flakes
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120598/pull-kubernetes-unit/1701530801671245824

```
{Failed;Failed;Failed;  === RUN   TestManifestFilesAreEqual/manifests_are_not_equal
    utils_test.go:832: ManifestFilesAreEqual diff doesn't expected
        manifests are not equal
        	expected diff: 
        - 					"2",
        + 					"1",
        actual diff:   &v1.Pod{
          	TypeMeta:   {Kind: "Pod", APIVersion: "v1"},
          	ObjectMeta: {Name: "etcd", Namespace: "kube-system", Labels: {"component": "etcd", "tier": "control-plane"}},
          	Spec: v1.PodSpec{
          		Volumes:        nil,
          		InitContainers: nil,
          		Containers: []v1.Container{
          			{
          				Name: "",
          				Image: strings.Join({
          					"gcr.io/google_containers/etcd-amd64:3.1.1",
        - 					"2",
        + 					"1",
          				}, ""),
          				Command: nil,
          				Args:    nil,
          				... // 20 identical fields
          			},
          		},
          		EphemeralContainers: nil,
          		RestartPolicy:       "",
          		... // 34 identical fields
          	},
          	Status: {},
          }
    --- FAIL: TestManifestFilesAreEqual/manifests_are_not_equal (0.01s)
;=== RUN   TestManifestFilesAreEqual/manifests_are_not_equal_for_adding_new_defaults
    utils_test.go:832: ManifestFilesAreEqual diff doesn't expected
        manifests are not equal for adding new defaults
        	expected diff: 
        - 		RestartPolicy:                 "Always",
        + 		RestartPolicy:                 "",
        actual diff:   &v1.Pod{
          	TypeMeta:   {Kind: "Pod", APIVersion: "v1"},
          	ObjectMeta: {Name: "etcd", Namespace: "kube-system", Labels: {"component": "etcd", "tier": "control-plane"}},
          	Spec: v1.PodSpec{
          		... // 2 identical fields
          		Containers:                    {{Image: "gcr.io/google_containers/etcd-amd64:3.1.11"}},
          		EphemeralContainers:           nil,
        - 		RestartPolicy:                 "Always",
        + 		RestartPolicy:                 "",
          		TerminationGracePeriodSeconds: nil,
          		ActiveDeadlineSeconds:         nil,
          		... // 32 identical fields
          	},
          	Status: {},
          }
    --- FAIL: TestManifestFilesAreEqual/manifests_are_not_equal_for_adding_new_defaults (0.00s)
;=== RUN   TestManifestFilesAreEqual
--- FAIL: TestManifestFilesAreEqual (0.02s)
;}
```

are we catching the flakynes we are seeing in e2e CI with this?
related to:
https://github.com/kubernetes/kubeadm/issues/2927
?

### PR DESCRIPTION
**Pull request by pacoxu**
/kind flake

Fixes https://github.com/kubernetes/kubeadm/issues/2932

```
go test -c -race   ./cmd/kubeadm/app/util/staticpod -run ^TestManifestFilesAreEqual$ 
stress -p 10  ./staticpod.test 


➜  kubernetes git:(master) ✗ /Users/pacoxu/go/bin/stress -p 10  ./staticpod.test                                  
5s: 117 runs so far, 0 failures
```

```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/priority critical-urgent
as it flakes a lot in presubmit CI

**Review by neolit123 — COMMENTED** [review]
i don't understand why this will fix the flakes?

aren't the flakes because of the internal defaulter code?

**Comment by pacoxu** [comment]
As the diff shows all no-space chars are as expected, I suspect the generated diff sometimes is using '\t'and in some scenarios will be spaces.

**Comment by neolit123** [comment]
> As the diff shows all no-space chars are as expected, I suspect the generated diff sometimes is using '\t'and in some scenarios will be spaces.

hmm, that would be a bug in the google `cmp` package if true. we have used it in other places in kubeadm before and there were no problems.
looking at https://github.com/kubernetes/kubeadm/issues/2932 it seems that the diff has a mixture of tabs and spaces.

doesn't `cmp` have an option to use e.g. only spaces?

**Comment by neolit123** [comment]
> As the diff shows all no-space chars are as expected, I suspect the generated diff sometimes is using '\t'and in some scenarios will be spaces.

i don't think this is true.
`cmp` is used in many places in k8s:
https://github.com/search?q=repo%3Akubernetes%2Fkubernetes%20%22cmp.DIff%22&type=code

**Comment by pacoxu** [comment]
> expected diff: "\n- \t\tRestartPolicy:                 \"Always\",\n+ \t\tRestartPolicy:                 \"\","
>             actual diff: "\u00a0\u00a0&v1.Pod{\n\u00a0\u00a0\tTypeMeta:   {Kind: \"Pod\", APIVersion: \"v1\"},\n\u00a0\u00a0\tObjectMeta: {Name: \"etcd\", Namespace: \"kube-system\", Labels: {\"component\": \"etcd\", \"tier\": \"control-plane\"}},\n\u00a0\u00a0\tSpec: v1.PodSpec{\n\u00a0\u00a0\t\t... // 2 identical fields\n\u00a0\u00a0\t\tContainers:                    {{Image: \"gcr.io/google_containers/etcd-amd64:3.1.11\"}},\n\u00a0\u00a0\t\tEphemeralContainers:           nil,\n-\u00a0\t\tRestartPolicy:                 \"Always\",\n+\u00a0\t\tRestartPolicy:                 \"\",\n\u00a0\u00a0\t\tTerminationGracePeriodSeconds: nil,\n\u00a0\u00a0\t\tActiveDeadlineSeconds:         nil,\n\u00a0\u00a0\t\t... // 32 identical fields\n\u00a0\u00a0\t},\n\u00a0\u00a0\tStatus: {},\n\u00a0\u00a0}\n"
> 

The expected is `\n- \t\tRestartPolicy:                 \"Always\",`.

The actual is `\n-\u00a0\t\tRestartPolicy:                 \"Always\",\n`

The cmp.diff returned `\u00a0` that is the non-breaking space.

**Comment by pacoxu** [comment]
@neolit123  I updated using difflib.

```
➜  kubernetes git:(flake-TestManifestFilesAreEqual) /Users/pacoxu/go/bin/stress -p 10  ./staticpod.test
5s: 196 runs so far, 0 failures
10s: 383 runs so far, 0 failures
```

**Comment by neolit123** [comment]
let's merge
https://github.com/kubernetes/kubernetes/pull/120602
@SataQiu updated earlier.

**Pull request closed without merging**
