### PR TITLE
Remove ListWatchUntil which is not used anymore

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
ListWatchUntil is no longer used.
This PR removes it from k8s

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
LGTM as per the function TODO.
/priority backlog

**Comment by tedyu** [comment]
@neolit123 
Can you take another look ?

Thanks

**Comment by neolit123** [comment]
/retest
try to get the CI signal green using `retest`.
but it's up to the maintainers at this point for approval.

**Comment by neolit123** [comment]
also please squash the commits to 1.

**Comment by tedyu** [comment]
Looking at https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73821/pull-kubernetes-verify/121647 , I don't see the cause for non-zero exit code.

**Comment by tedyu** [comment]
Ping @jpbetz

**Comment by tedyu** [comment]
ping @liggitt

**Comment by tnozicka** [comment]
/hold
@liggitt I think we just want to make it use `Until` instead of `UntilWithoutRetry` given the issues with RV0? We will change the interface a bit, but let's not break the users until we have a replacement, which is now on my todo list after I merge the new `Until`

**Comment by tnozicka** [comment]
- this is external facing
- there is an updated version from https://github.com/kubernetes/kubernetes/pull/67350/commits/603dd254ac91b3581f9b431ff91a95d929a97e04#diff-b7ca7f71d0c92e184f946e29d5734a4eR178
- ListWatchUntil is being directly used in https://github.com/kubernetes/kubernetes/pull/74717

/close

**Pull request closed without merging**
