### PR TITLE
controller: add approvers for rc/rs

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by caesarxuchao** [comment]
lgtm. We need an approver listed in pkg/controller/OWNERS to approve the change. @derekwaynecarr could you help?

**Comment by caesarxuchao** [comment]
cc @grodrigues3 the merge-bot's message has a bug, it should suggest us to find an approver for this PR from pkg/controller/OWNERS

**Comment by kargakis** [comment]
@k8s-bot tell me a joke

**Comment by spxtr** [comment]
@k8s-bot tell me a joke

**Comment by kargakis** [comment]
@janetkuo ptal

**Comment by kargakis** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
