### PR TITLE
fix typo: "inidvidual"-> "individual"

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

**What this PR does / why we need it**:
fix typo: "inidvidual"-> "individual"

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Thanks for your pr :)

**Comment by mattjmcnaughton** [comment]
Also, please uncomment the `/kind cleanup` line and also move the `"fix typo..."` message into the "What this pr does" section. thanks!

**Comment by zgfh** [comment]
@mattjmcnaughton sorry, updated

**Comment by nikhita** [comment]
/kind cleanup

/assign @yujuhong
for approval

**Pull request merged**
