### PR TITLE
kubeadm: updated tests in app/util pkg

### PR DESCRIPTION
**Pull request by dmmcquay**
**What this PR does / why we need it**: Tests did not follow the standard of being table driven. Updated to make future changes (Adding/deleting tests) easier as well as more readable

Adding unit tests is a WIP from #34136

**Special notes for your reviewer**: /cc @luxas @pires 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by pires — APPROVED** [review]

**Comment by dmmcquay** [comment]
@lukemarsden mind reviewing this PR?

**Comment by luxas** [comment]
I think @pires or myself is a better reviewer for this.

@pires can you review this?

**Comment by pires** [comment]
@luxas sure.

**Comment by dmmcquay** [comment]
@pires can I get your lgtm?

**Comment by pires** [comment]
@luxas ping

**Pull request merged**
