### PR TITLE
Add CRD compatibility fixtures

### LINKED ISSUE #79026: Add serialization fixtures for apiextensions (CRD and ConversionReview types)
Follow up from https://github.com/kubernetes/kubernetes/pull/78309

Add compatibility testing for the apiextensions-apiserver APIs (CRD and ConversionReview types)

Some special-case fuzzing will be required for the rawextension fields

/sig api-machinery
/priority important-soon
/assign

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup
/kind test

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/79026

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/assign @apelisse

### CODE REVIEW

**Review by apelisse — COMMENTED** [review]
thanks,
/lgtm

Can we use these types to populate some golden data for the openapi, see #115351

**Comment by liggitt** [comment]
> Can we use these types to populate some golden data for the openapi, see #115351

um.... probably not... these are *only* for testing wire encoding/decoding compatibility, so the values are generated and not actually semantically valid (wouldn't pass validation or be usable as a functional CRD)

**Pull request merged**
