### PR TITLE
Scheduler map reduce 3

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/kubernetes/issues/24246

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32651)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek - PTAL

**Comment by gmarek** [comment]
Few nits.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[plugin/pkg/scheduler/algorithm/types.go, line 36 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSertyduehLbkPgobZP:-KSertyduehLbkPgobZQ:bottdjj) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/types.go#L36)):*
> ```Go
> // final scores for all nodes.
> // TODO: Figure out the exact API of this method.
> type PriorityReduceFunction func(pod *api.Pod, result schedulerapi.HostPriorityList) error
> ```

See my later comment - I don't think it's needed.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 34 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeoTwuJjSHnLZjteU4:-KSeoTwuJjSHnLZjteU5:b1y0pku) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L34)):*
> ```Go
> // the node satisfies and the more the preferredSchedulingTerm that is satisfied weights, the higher
> // score the node gets.
> func CalculateNodeAffinityPriorityMap(pod *api.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (schedulerapi.HostPriority, error) {
> ```

I still don't like the `interface{}` here... Why not *PriorityMetadata? I see only one call to the `Map` and we know the type of meta there. You can always pass `nil` to indicate that this function needs to recompute affinities.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 64 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeps6PLSb2kr37SC-5:-KSeps6PLSb2kr37SC-6:b8lk5r) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L64)):*
> ```Go
> 			}
> 
> 			// TODO: Avoid computing it for all nodes if this becomes a performance problem.
> ```

A thought - I guess in most of the cases there won't be many "kinds" of Nodes in the cluster, where by "kind" I understand the label set. We probably can do label-based-per-node computations on abstraction classes. (Not related to this PR)

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSeqzPTwY60nrKD7fqN:b-gxet2o) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
> ```Go
> 			fScore = 0
> 		}
> 		if glog.V(10) {
> ```

This basically prints scores for all Nodes, so it can be moved to the Map function. Then Reduce won't need to get `*api.Pod`.

---

*[plugin/pkg/scheduler/algorithm/priorities/taint_toleration.go, line 108 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSes6QxZ8uHV_PrahA0:-KSes6QxZ8uHV_PrahA1:bfr14zr) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/taint_toleration.go#L108)):*
> ```Go
> 			fScore = (1.0 - float64(result[i].Score)/maxCountFloat) * 10
> 		}
> 		if glog.V(10) {
> ```

Again - this can be moved to Map.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-:-KSesm1bi-RBfqf01cFh:bakz5rb)*

**Comment by wojtek-t** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[plugin/pkg/scheduler/algorithm/types.go, line 36 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSertyduehLbkPgobZP:-KSexxNcHQEUD0F5GB6u:b-pns57g) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/types.go#L36)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> See my later comment - I don't think it's needed.
</details>
See my later comments - I think it currently is needed.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 34 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeoTwuJjSHnLZjteU4:-KSexkMnV5Si43TaJxXg:bj6hmhy) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L34)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I still don't like the `interface{}` here... Why not *PriorityMetadata? I see only one call to the `Map` and we know the type of meta there. You can always pass `nil` to indicate that this function needs to recompute affinities.
</details>
Discussed offline. I wouldn't like to change this in this PR. I'm adding a TODO to change it after all related PRs are done (this change should be pretty simple).

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 64 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeps6PLSb2kr37SC-5:-KSexKR-yXKcSIKCI24P:b-f35ws1) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L64)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> A thought - I guess in most of the cases there won't be many "kinds" of Nodes in the cluster, where by "kind" I understand the label set. We probably can do label-based-per-node computations on abstraction classes. (Not related to this PR)
</details>
Yeah - there are still a bunch of things in scheduler that we can improve. This is one of those.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSexRKMH3_gLZITn0Ct:bkbb2jd) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> This basically prints scores for all Nodes, so it can be moved to the Map function. Then Reduce won't need to get `*api.Pod`.
</details>
Not really - in Map you don't have full result - after Map phase you have just some numbers, that are then translated to result.

---

*[plugin/pkg/scheduler/algorithm/priorities/taint_toleration.go, line 108 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSes6QxZ8uHV_PrahA0:-KSexhN7T9m7Mo4T4jlq:bkbb2jd) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/taint_toleration.go#L108)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Again - this can be moved to Map.
</details>
Not really - in Map you don't have full result - after Map phase you have just some numbers, that are then translated to result.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by wojtek-t** [comment]
@gmarek - I responded to your comments. PTAL

**Comment by gmarek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSf37oBIL3oXKkR-P0t:b-bppnao) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, wojtek-t (Wojciech Tyczynski) wrote…</i></summary>
> Not really - in Map you don't have full result - after Map phase you have just some numbers, that are then translated to result.
</details>
Can we just add podName to the HostAPIPriority (it's specific to the Pod after all). Passing the pod here breaks the MR abstraction.
If you have it in the HostPriorityList, you can actually do whole Pods x Nodes matrix in a Map function, and reduce would do per-pod aggregation.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by wojtek-t** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSf9EmGE1UdxMBRd8-Z:b-iuvli8) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Can we just add podName to the HostAPIPriority (it's specific to the Pod after all). Passing the pod here breaks the MR abstraction.
> If you have it in the HostPriorityList, you can actually do whole Pods x Nodes matrix in a Map function, and reduce would do per-pod aggregation.
</details>
I'm really against changing HostAPIPriority, because it will have the same pod everywhere (we are prioritizing only a single pod at any time)

And I don't understand why it breaks MR abstraction - breaking MR abstraction would be passing some info about nodes here.

And I don't understand "Pods x Nodes" matrics - there is only one pod always.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by gmarek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSfJ98XFVvP_DggciH_:bhbfbqh) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, wojtek-t (Wojciech Tyczynski) wrote…</i></summary>
> I'm really against changing HostAPIPriority, because it will have the same pod everywhere (we are prioritizing only a single pod at any time)
> 
> And I don't understand why it breaks MR abstraction - breaking MR abstraction would be passing some info about nodes here.
> 
> And I don't understand "Pods x Nodes" matrics - there is only one pod always.
</details>
It's probably not worth arguing about.

In pure MR you generally don't pass side cars to reducers (like the Pod here) - it's not a huge deal though.

If you have multiple Pods to schedule and you'd add a Pod to HostPriorityList, you would be able to parallelize priority computation for all of them.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by wojtek-t** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSfKLXrQH01eGgXx-Ni:blh9rfc) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> It's probably not worth arguing about.
> 
> In pure MR you generally don't pass side cars to reducers (like the Pod here) - it's not a huge deal though.
> 
> If you have multiple Pods to schedule and you'd add a Pod to HostPriorityList, you would be able to parallelize priority computation for all of them.
</details>
Can we leave as is for now, and potentially clean it up in a follow-up?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by gmarek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[plugin/pkg/scheduler/algorithm/priorities/node_affinity.go, line 97 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-KSeqzPTwY60nrKD7fqM:-KSfOwMr79eqxWcZUXfv:bb74ce2) ([raw file](https://github.com/kubernetes/kubernetes/blob/832f4ebc5cf602652e61dd3419c973241a19a3af/plugin/pkg/scheduler/algorithm/priorities/node_affinity.go#L97)):*
<details><summary><i>Previously, wojtek-t (Wojciech Tyczynski) wrote…</i></summary>
> Can we leave as is for now, and potentially clean it up in a follow-up?
</details>
Sure

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651)*

**Comment by gmarek** [comment]
/lgtm

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32651#-:-KSfP0oa9g5NnwOubcD4:b-8ks5qa)*

**Pull request merged**
