### PR TITLE
change the relative links to definition in operations.html

### PR DESCRIPTION
**Pull request by caesarxuchao**
...to satisfy the new directory layout in the kubernetes.io.

This will make the manual changes in https://github.com/kubernetes/kubernetes.github.io/pull/369 persist.

I still need to bump up the gcr.io/google_containers/gen-swagger-docs image version. I'll do that after I get LGTM here.

cc @bgrant0607 @xiangpengzhao

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Thanks, @caesarxuchao

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this, issue #IGNORE

**Comment by caesarxuchao** [comment]
I pushed the image, let's see if the test passes.

**Comment by caesarxuchao** [comment]
Assign to @bgrant0607 for triaging.

**Comment by bgrant0607** [comment]
@johndmulhausen Does this link syntax work?

**Comment by xiangpengzhao** [comment]
@caesarxuchao what should I do if I find other bugs in API docs (e.g. operations.html)? What files do I need to modify? Thanks!

**Comment by caesarxuchao** [comment]
Rebased. 

> RE: @johndmulhausen Does this link syntax work?

The link syntax is the same as the one currently in the kubernetes.github.io repo. This PR just makes the manual changes in kubernetes/kubernetes.github.io#369 persist.

**Comment by caesarxuchao** [comment]
@xiangpengzhao
> 1. What should I do if I want to commit bug-fix in API docs (e.g. operations.html)? 
2. What files do I need to modify? 

The content of the API docs is generated from the comments in the various types.go files in the main repo. The automating script is hack/update-api-reference-docs.sh.

> 3. How to trigger the update time to be updated again? e.g. Last updated 2016-03-15 23:35:46 UTC

Run hack/update-api-reference-docs.sh, or run hack/update-all.sh, which will call the former script.

Feel free to cc me in relating issues.

**Comment by xiangpengzhao** [comment]
Thanks @caesarxuchao !

**Comment by pwittrock** [comment]
@johndmulhausen This look ok?

**Comment by pwittrock** [comment]
@caesarxuchao Would you mind rebasing and making sure the tests pass?

**Comment by caesarxuchao** [comment]
Is it blocking someone? If not I'll do this next week.

**Comment by pwittrock** [comment]
@caesarxuchao Not blocking anyone.  I am just trying to close out open PRs.

**Comment by caesarxuchao** [comment]
@pwittrock I've rebased it. Could you review it? Thanks!

**Comment by caesarxuchao** [comment]
Thanks @pwittrock!

**Pull request merged**
