### PR TITLE
Update parameter for scheduler.md

### PR DESCRIPTION
**Pull request by gyliu513**
Fix issue #18325

### CODE REVIEW

**Comment by karlkfi** [comment]
Need the CLA signed to accept the changes.
Otherwise LGTM.

**Comment by jay-lau** [comment]
@karlkfi  I signed for the CLA last year and already have some patches got merged. Make sense? ;-)

**Comment by karlkfi** [comment]
I have no way to look up CLA status apart from what @googlebot says. So if you didn't commit with a white-listed email address, only a Google employee can sign off.

**Comment by karlkfi** [comment]
Looks like you did a `git pull upstream master` or something and hot a merge commit you don't want. You'll probably need to recreate the branch to fix that so it's just one commit. When you're on a branch, if you do a `git pull upstream master` it will create a merge commit. What you actually want to do is a `git pull --rebase upstream master` to rebase your commit on top of the new changes to master.

If none of that made sense, just make a new branch.

**Comment by jay-lau** [comment]
I created a new pull request here https://github.com/kubernetes/kubernetes/pull/18491

**Comment by karlkfi** [comment]
duplicate now.

**Pull request closed without merging**
