### PR TITLE
Automated cherry pick of #68096: add make targets for building server images

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #68096 on release-1.11.

#68096: add make targets for building server images

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
This would also need to be updated to handle kube-aggregator due to https://github.com/kubernetes/kubernetes/commit/a66e1f089ea95375cc7549660ad951d55a829915#diff-0ee501c7b4b1ab61678579826c6d6534 only being in master post-1.11.

**Comment by foxish** [comment]
@BenTheElder - this needs lgtm and approval

**Comment by BenTheElder** [comment]
sorry for the delay, I think I'm going to abandon cherry picking this

**Pull request closed without merging**
