### PR TITLE
Automated cherry pick of #118150: kubeadm: remove function pointer comparison in phase test

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #118150 on release-1.26.

#118150: kubeadm: remove function pointer comparison in phase test

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by neolit123** [comment]
/release-note-none
/kind failing-test
/priority backlog
/triage accepted
/cc kubernetes/release-managers

this is a backport of a kubeadm unit test fix for GO 1.21.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
@dims the vendor diff fails on these cherry pick prs for some reason:
https://github.com/kubernetes/kubernetes/pull/118169
https://github.com/kubernetes/kubernetes/pull/118168

do you know who can help debug?

**Comment by dims** [comment]
@neolit123 miracles of golang versions ... please run hack/update-vendor.sh in the specific branches to fix them them up?

**Comment by neolit123** [comment]
> @neolit123 miracles of golang versions ... please run hack/update-vendor.sh in the specific branches to fix them them up?

please see
https://github.com/kubernetes/kubernetes/issues/119016#issuecomment-1616378887

**Comment by pohly** [comment]
hack/verify-vendor.sh passes in neolit123:automated-cherry-pick-of-#118150-origin-release-1.26, but it fails after merging into release-1.26.

@neolit123: I think you need to rebase, then `hack/update-vendor.sh` and force-push.

**Pull request merged**
