### PR TITLE
Support AlwaysCheckAllPredicates in the scheduler framework.

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Adds support for AlwaysCheckAllPredicates flag in the scheduling framework.

**Does this PR introduce a user-facing change?**:
```release-note
Adds back support for AlwaysCheckAllPredicates flag.
```

/cc @Huang-Wei

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
LGMT. Just a comment is that we may need at least UT to verify it really works.

**Comment by ahg-g** [comment]
> LGMT. Just a comment is that we may need at least UT to verify it really works.

yeah, I will add a UT in this PR, but first just wanted to check if this approach is ok

**Comment by ahg-g** [comment]
> > LGMT. Just a comment is that we may need at least UT to verify it really works.
> 
> yeah, I will add a UT in this PR, but first just wanted to check if this approach is ok

unit test added

**Comment by Huang-Wei** [comment]
> unit test added

Neat!

/lgtm

**Comment by ahg-g** [comment]
@Huang-Wei fixed a conflict after #86369 got merged.

**Comment by ahg-g** [comment]
/cc @draveness 

Wei is on vacation, please take a look if you have time.

**Review by draveness — APPROVED** [review]
Great, thanks for the work!

/lgtm
/priority important-soon

**Pull request merged**
