### PR TITLE
chore(node/util): add more labels to `deprecatedNodeLabels`

### PR DESCRIPTION
**Pull request by wafuwafu13**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

grep [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) with `deprecated` &  `Used on: All Objects` & `Used on: Node`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
Thanks for your contribution.

/ok-to-test

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
