### PR TITLE
Extract Method for kubeadm

### PR DESCRIPTION
**Pull request by ping035627**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Function 'GetEtcdAltNames' and 'GetEtcdPeerAltNames' are mostly the same. I think we should extract method.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

/release-note-none
/priority backlog

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
Nice cleanup.
/lgtm

**Comment by fabriziopandini** [comment]
Thanks for this PR!
/test pull-kubernetes-e2e-kind
/lgtm

**Pull request merged**
