### PR TITLE
fix Spelling error for supersede in config.go

### PR DESCRIPTION
**Pull request by changshuchao**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by changshuchao** [comment]
@oomichi need approve label

**Comment by oomichi** [comment]
> 
> 
> @oomichi need approve label

I don't have a permission to approve.
It is better to ask approvers from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/OWNERS

/remove-lifecycle rotten
/cc @caesarxuchao

**Pull request closed without merging**
