### PR TITLE
Fix: pkg/apis Typos in comments, function name, error message

### PR DESCRIPTION
**Pull request by taesunny**
**What type of PR is this?**
> /kind cleanup
> /kind api-change

**What this PR does / why we need it**:
> To fix pkg/apis Typos in comments, function name, error message

**Which issue(s) this PR fixes**:

> Fixes #

**Special notes for your reviewer**:
> NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> NONE

### CODE REVIEW

**Comment by taesunny** [comment]
I make an assignment from k8s-ci-robot APPROVALNOTIFIER info.

/assign @smarterclayton

**Comment by sftim** [comment]
I think:
/priority backlog

**Pull request merged**
