### PR TITLE
CoreDNS pull image from gcr.io

### PR DESCRIPTION
**Pull request by rajansandeep**
**What this PR does / why we need it**:
CoreDNS now pulls image from gcr.io
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by rajansandeep** [comment]
Needs milestone tags and labels.
@thockin can you help out?
Thanks!

**Comment by dims** [comment]
/milestone v1.11

(per @thockin on sig-release channel)

**Comment by fturib** [comment]
@dims, @thockin : can one of you ad the needed `status/approved-for-milestone` ? Thanks.

**Comment by jberkus** [comment]
Is this change documented as part of the CoreDNS integration docs somewhere?  Seems worth a single line.

**Pull request merged**
