### PR TITLE
[kubeadm] Print required flags when running kubeadm upgrade plan

### LINKED ISSUE #935: kubeadm upgrade plan output should also print required flags
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions
Upgrading k8s from 1.10.4 to 1.11.0-beta.2

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2.57+8bb1309efed13d-dirty", GitCommit:"8bb1309efed13d572c12bf29397e533e07579b56", GitTreeState:"dirty", BuildDate:"2018-06-12T19:00:36Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

## What happened?
I ran `kubeadm upgrade plan --allow-experimental-upgrades`

and received the line

```
You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.11.0-beta.2

Note: Before you can perform this upgrade, you have to update kubeadm to v1.11.0-beta.2.
```

I then ran `kubeadm upgrade apply v1.11.0-beta.2` and received an error:

```
[upgrade/version] FATAL: The --version argument is invalid due to these errors:

        - Specified version to upgrade to "v1.11.0-beta.2" is an unstable version and such upgrades weren't allowed via setting the --allow-*-upgrades flags
```

## What you expected to happen?
I expected to run the provided command without errors.

## How to reproduce it (as minimally and precisely as possible)?
upgrade to a non-stable release version

### PR DESCRIPTION
**Pull request by xlgao-zju**
**What this PR does / why we need it**:
print required flags when running kubeadm upgrade plan

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Close [kubernetes/kubeadm#935](https://github.com/kubernetes/kubeadm/issues/935)

**Special notes for your reviewer**:
/assign @chuckha 
/assign @neolit123 

**Release note**:

```release-note
kubeadm: print required flags when running kubeadm upgrade plan
```

### CODE REVIEW

**Comment by neolit123** [comment]
thank you @xlgao-zju 
/lgtm

**Comment by neolit123** [comment]
/kind bug
@kubernetes/sig-cluster-lifecycle-pr-reviews 

potential cherry-pick?

**Comment by neolit123** [comment]
@chuckha @xlgao-zju 
i think we should handle `--allow-release-candidate-upgrades` as well?

**Comment by xlgao-zju** [comment]
>i think we should handle --allow-release-candidate-upgrades as well?

@neolit123 I think we can handle RC by using `--allow-experimental-upgrades` too?

```bash
--allow-experimental-upgrades        Show unstable versions of Kubernetes as an upgrade alternative and allow upgrading to an alpha/beta/release candidate versions of Kubernetes.
--allow-release-candidate-upgrades   Show release candidate versions of Kubernetes as an upgrade alternative and allow upgrading to a release candidate versions of Kubernetes.
```

**Comment by neolit123** [comment]
that's true.

if the user types:
```
kubeadm upgrade plan --allow-release-candidate-upgrades
```
to my understanding it would print:
```
You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply <some-RC-version> --allow-experimental-upgrades

```
so it's a question if we want to print the exact `--allow-....`. flag that the user initially entered.
`--allow-experimental-upgrades` would be valid.

**Comment by xlgao-zju** [comment]
Maybe this is better instead of using the user's initial flag?

When the version is RC:
```bash
You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply <some-RC-version> --allow-release-candidate-upgrades
```

when the version is some other unstable version:
```bash
You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply <some-other-unstable-version> --allow-experimental-upgrades
```

**Comment by chuckha** [comment]
@xlgao-zju we should support both flags, I like the idea of printing the correct one based on the suggested version instead of printing the flag the user passed in even though that's the only time we'll see this output.

**Comment by xlgao-zju** [comment]
@chuckha @neolit123 Updated based on:
>the correct one based on the suggested version

PTAL

**Comment by neolit123** [comment]
@xlgao-zju 
thanks, the change seems good.

waiting on @chuckha for confirmation.

**Review by luxas — APPROVED** [review]
/lgtm

**Pull request merged**
