### PR TITLE
kubelet: fix structured logging message in podkiller

### PR DESCRIPTION
**Pull request by rphillips**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This is a trivial change with the structured logging message. Logf should have been a LogS.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
I've seen a few of these lingering. My suggestion is to wait until everything on the board merges, and then we can follow-up with a PR that applies the static analysis tool to catch all of these. See e.g. #99996

**Review by wzshiming — APPROVED** [review]

**Comment by ehashman** [comment]
/close

This was fixed.

**Pull request closed without merging**
