### PR TITLE
Document k8s.gcr.io/etcd image upgrade/downgrade support

### PR DESCRIPTION
**Pull request by jpbetz**
Fixes https://github.com/kubernetes/kubernetes/issues/59221

### CODE REVIEW

**Comment by wenjiaswe** [comment]
lgtm (reviewed with no issue)

**Comment by jpbetz** [comment]
@lavalamp Would you approve? This is just some additional README documentation. @wenjiaswe has reviewed as well.

**Comment by lavalamp** [comment]
/approve

Should this document anything re: backups or HA configurations?

**Comment by jberkus** [comment]
reminder: to get this to merge, please resolve the release-note hold, and add status/approved-for-milestone.

**Pull request merged**
