### PR TITLE
Get rid of unused API type NodeResources

### PR DESCRIPTION
**Pull request by thockin**
This does not seem to be used anywhere and the code is cleaner without it.

/sig node
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
this looks good to me ... looking at https://cs.k8s.io/?q=%5CbNodeResources%5Cb&i=nope&files=&excludeFiles=vendor&repos= but not sure what we will find in the wild though

**Comment by liggitt** [comment]
History:

* https://github.com/kubernetes/kubernetes/commit/39d03948e78eaeda5bfa96208cd1f8e5972c1826 (2014-09-25 / v0.4) - Added and referenced from prerelease v1beta3 Minion API
* https://github.com/kubernetes/kubernetes/commit/156000ef6d7b71ef45617a330964cf0acddf67c4 (2014-11-19 / v0.6.0) - Removed from prerelease Minion API in  in favor of spec / status

---

unreferenced from this point on in API types

---

* https://github.com/kubernetes/kubernetes/commit/bff3cb4df68d699285285c09c1c46be69ef1465a (2016-11-18 / v1.6.0) - Copied to pkg/api/v1/helpers.go
* https://github.com/kubernetes/kubernetes/commit/d4850b6c2b3b367345ef944a12a778d860fdd0db (2017-04-13 / v1.7.0) - Moved from pkg/api/v1/helpers.go to pkg/api/v1/types.go
* https://github.com/kubernetes/kubernetes/commit/58edb6b4851ddab6f620d8af607f58c7f9fe60d9 (2017-04-27 / v1.8.0) - Moved from pkg/api/v1/types.go to staging/src/k8s.io/api/core/v1/types.go

/lgtm
/approve

**Pull request merged**
