### PR TITLE
Automated cherry pick of #74306: Fix scanning of failed targets

### PR DESCRIPTION
**Pull request by redbaron**
Cherry pick of #74306 on release-1.13.

#74306: Fix scanning of failed targets

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
Friendly ping - deadline for merging changes to go into 1.13.4 is EOD today.

**Comment by tpepper** [comment]
@kubernetes/sig-storage-pr-reviews 

This cherry pick is at risk of yet again missing the latest patch release.  Please update the issue ASAP.  If this is not going to merge, please close.

**Pull request merged**
