### PR TITLE
Fix incorrect "whitespaces" plural

### PR DESCRIPTION
**Pull request by sambostock**
/kind documentation

**What this PR does**:

This fixes an incorrect pluralization of "whitespace". It is an uncountable noun, and as such "whitespaces" is invalid.

Alternatively, "whitespace characters" would be correct.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sambostock** [comment]
I have signed the CLA 👍

**Comment by nikhita** [comment]
Lgtm, but looks like the CLA is still not signed. Just to double check...is the CLA signed using the gmail address?

In case you face any troubles with CLA, you can reach out to the Linux Foundation here: https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting. They are usually quick with responses and resolving the CLA problems. :)

**Comment by sambostock** [comment]
Sorry for the confusion @nikhita! Looks like I signed up for the account successfully, but missed the step of actually filling out the CLA. Should be good now 🤞

**Review by nikhita — APPROVED** [review]
Congratulations on getting your first PR into @kubernetes! :rocket: :smile: 

/ok-to-test
/priority backlog

/lgtm
/approve

**Pull request merged**
