### PR TITLE
Convert kubernetes/serve_hostname to gcr.io/google_containers/server_hos...

### PR DESCRIPTION
**Pull request by satnam6502**
...tname

### CODE REVIEW

**Comment by satnam6502** [comment]
Running e2e tests... please do not merge until I verify that everything is OK.
@jlowdermilk @zmerlynn @thockin

**Comment by vmarmol** [comment]
LGTM, will wait for your go-ahead to merge :)

**Comment by satnam6502** [comment]
I've been trying and failing to run e2e tests. I will give up tonight and try again tomorrow.

**Comment by jlowdermilk** [comment]
I think this is eclipsed by #6268 which is now merged.

**Pull request closed without merging**
