### PR TITLE
Enable privileged containers in Trusty nodes

### PR DESCRIPTION
**Pull request by andyzheng0831**
This change also removes an outdated TODO comment.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
cc/ @roberthbailey @yinghan @dchen1107

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
You will also need to cherry pick this into the 1.1 release branch. See https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md.

**Comment by andyzheng0831** [comment]
I follow the instruction to make a cherry-pick PR. Do I need to do anything to get it reviewed and merged, or it is an automatic process? BTW, I don't receive an email for the cherry-pick PR.

**Comment by roberthbailey** [comment]
The cherry pick PR follows the same process as a regular PR. Send it for review against the 1.1 branch.

**Comment by andyzheng0831** [comment]
ok to test

**Comment by andyzheng0831** [comment]
@k8s-bot test this please

**Pull request merged**
