### PR TITLE
Allow swapping NotReady and Unschedulable Taints

### LINKED ISSUE #43444: Node get taint 'node.alpha.kubernetes.io/notReady' when node become 'Unknown' form 'notReady''
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):
v1.7.0-alpha.0.1397+e3f6f14bf0d1af-dirty

**What happened**:
On node stop docker, then node ready conditions will become notready;  then stop kubelet on node, node ready conditions will become 'Unknown', But node only have a taint 'node.alpha.kubernetes.io/notReady'

**What you expected to happen**:
Node should both taint 'node.alpha.kubernetes.io/notReady:NoExecute' & 'node.alpha.kubernetes.io/unreachable:NoExecute'

**How to reproduce it** (as minimally and precisely as possible):
1. Enable 'TaintBasedEvictions' in controller manager
2. Stop container on node
3. Check node taint
4. Stop kubelet on node
5. Check node taint
node detail: http://pastebin.test.redhat.com/466570

**Anything else we need to know**:
If node ready conditions change from 'Ready' to 'Unknown', node have correct taint 'node.alpha.kubernetes.io/unreachable:NoExecute'

### PR DESCRIPTION
**Pull request by gmarek**
Fix #43444

cc @kubernetes/sig-scheduling-pr-reviews @davidopp @aveshagarwal @mdshuai

For cherrypick @ethernetdan 

```release-note
Fix [transition between NotReady and Unreachable taints](https://github.com/kubernetes/kubernetes/issues/43444).
```

### CODE REVIEW

**Comment by gmarek** [comment]
Ping @davidopp @aveshagarwal

**Comment by aveshagarwal** [comment]
@gmarek, will review today, thanks.

**Comment by davidopp** [comment]
Thanks @gmarek !

**Pull request merged**
