### PR TITLE
Few fixes of density test

### PR DESCRIPTION
**Pull request by wojtek-t**
This is a followup from #6459 
1. Change tests to be dependent of the size of the cluster (# of nodes)
2. Fix the problem of incorrect arguments to "It"

cc @fgrzadkowski @rjnagal @jayunit100

### CODE REVIEW

**Comment by jayunit100** [comment]
Thanks ! 
- I see you have differentiated density from launchPods.... seems however that there ir "raw density" and "relative density".  
- Otherwise looks good but i havent tested.  
- Later in a follow on we can rename these vars or add more comments.  

By the way... what was the problem with `It` arguments ?  I didnt notice one....

**Comment by wojtek-t** [comment]
@jayunit100 
I've differentiated them, because those test are pretty different one from the other.
So what names are you suggesting? [I was never good at naming thing so I'm very open on any suggestions]

Regarding the "It" argument - this wasn't your bug - it was introduced by me before (but I didn't observe it). Basically it seems that "It" is not called synchronously so there is a problem of using variables from the outside that can change in the meantime inside "It".

**Comment by jayunit100** [comment]
cool :) ... for names?  I'd suggest `podScalability` and `podDensity` .  That implies that there is a difference between the latter (which launches # pods per minion) and the former (which just launches N pods).

I say lets merge it if you've tested  ... its a good update !

**Comment by wojtek-t** [comment]
Thanks - renaming done.

**Comment by rjnagal** [comment]
Thanks @wojtek-t This looks great.

LGTM

**Pull request merged**
