### PR TITLE
Only log Events starting with log level 4

### PR DESCRIPTION
**Pull request by sylr**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

Only log events starting with log level 4 to allow to reduce the amount of logs produced.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Only log Events starting with log level 4
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Hi @sylr ! Thanks for your pr :)

Could you please add some additional context on the benefits this change would provide?

Particularly, I (think) that when running the k8s binaries (i.e. kubelet), you can control the logging level via an the `-v` argument (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) - I'd be curious to learn more about if that technique could be applicable here.

**Comment by sylr** [comment]
The context is that Event logging generates a certain amount of logs that one could be not interested in. Also it can become costly when you forward all your pods standard outputs to tools like Splunk.

Unless mistaken I believe that Events logging is unaffected by the `--v=n` argument.

Adding `.V(n)` allows whether or not you want Events to be logged by decreasing/increasing log level with `--v=n`.

**Comment by mattjmcnaughton** [comment]
> The context is that Event logging generates a certain amount of logs that one could be not interested in. Also it can become costly when you forward all your pods standard outputs to tools like Splunk.
> 
> Unless mistaken I believe that Events logging is unaffected by the `--v=n` argument.
> 
> Adding `.V(n)` allows whether or not you want Events to be logged by decreasing/increasing log level with `--v=n`.

Interesting - thank you for the additional context.

@derekwaynecarr @gnufied @sttts - do y'all think a KEP could be helpful here? The described change sounds to me like it has a non-negligible impact on how Events are logged in the system.

**Comment by deads2k** [comment]
The log level for these events is already reasonable.  Events are important enough for us to pay the far more expensive cost of an API request to emit the event.  If you want to prune your logs, I recommend filtering before or after sending.

/close

**Comment by sylr** [comment]
> The log level for these events is already reasonable. 

@deads2k What is the current log level for these Events ?

**Comment by deads2k** [comment]
> > The log level for these events is already reasonable.
> 
> @deads2k What is the current log level for these Events ?

It prints the events that are important enough for us to pay a full API call to kube-apiserver out to the log as info.  These events are logically info level event or we wouldn't be sending them to the kube-apiserver.  You can restrict above info level if you like and use vmodule to limit or simply grep out, but these events are info level in importance.

**Pull request closed without merging**
