### PR TITLE
Update etcd godep to fix golang 1.5.1 data race

### PR DESCRIPTION
**Pull request by timothysc**
Pulls in https://github.com/coreos/etcd/pull/3972, for fixing #18437 

xref: #13838

/cc @wojtek-t @xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM if this actually fixes the race detected in k8s.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
LGTM - thanks @timothysc

**Comment by wojtek-t** [comment]
Thanks for merging @piosz !

Manually merged, to check whether it solved all the races in Go 1.5.1.

**Pull request merged**
