### PR TITLE
Rolling back network policy tests

### PR DESCRIPTION
**Pull request by knabben**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Giving more time before delete of old PR

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jayunit100** [comment]
@aojea is this ok with you ? waiting for `pull-kubernetes-e2e-ubuntu-gce-network-policies Pending — Job triggered.` to pass, then i can green light to .

**Comment by jayunit100** [comment]
Ok, so these are the tests....  i see both the old and new ones here. 

```
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce multiple, stacked policies with overlapping podSelectors [Feature:NetworkPolicy]","total":-1,"completed":1,"skipped":12,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Ports [Feature:NetworkPolicy]","total":-1,"completed":2,"skipped":8,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow egress access to server in CIDR block [Feature:NetworkPolicy]","total":-1,"completed":3,"skipped":60,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should deny ingress access to updated pod [Feature:NetworkPolicy]","total":-1,"completed":12,"skipped":170,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should not allow access by TCP when a policy specifies only UDP [Feature:NetworkPolicy] [Feature:UDP]","total":-1,"completed":2,"skipped":30,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should support a 'default-deny-all' policy [Feature:NetworkPolicy]","total":-1,"completed":3,"skipped":87,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce multiple, stacked policies with overlapping podSelectors [Feature:NetworkPolicy]","total":-1,"completed":1,"skipped":17,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce multiple ingress policies with ingress allow-all policy taking precedence [Feature:NetworkPolicy]","total":-1,"completed":12,"skipped":200,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should support allow-all policy [Feature:NetworkPolicy]","total":-1,"completed":6,"skipped":143,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow ingress access from updated pod [Feature:NetworkPolicy]","total":-1,"completed":4,"skipped":68,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Multiple PodSelectors and NamespaceSelectors [Feature:NetworkPolicy]","total":-1,"completed":8,"skipped":78,"failed":0}
{"msg":"PASSED [sig-network] Netpol API should support creating NetworkPolicy API operations","total":-1,"completed":12,"skipped":117,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce multiple egress policies with egress allow-all policy taking precedence [Feature:NetworkPolicy]","total":-1,"completed":3,"skipped":62,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector or NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":2,"skipped":45,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on NamespaceSelector with MatchExpressions[Feature:NetworkPolicy]","total":-1,"completed":6,"skipped":72,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should deny egress from pods based on PodSelector [Feature:NetworkPolicy] ","total":-1,"completed":4,"skipped":65,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic only from a different namespace, based on NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":9,"skipped":113,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on NamespaceSelector with MatchExpressions[Feature:NetworkPolicy]","total":-1,"completed":10,"skipped":110,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":12,"skipped":208,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow egress access on one named port [Feature:NetworkPolicy]","total":-1,"completed":14,"skipped":258,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce multiple egress policies with egress allow-all policy taking precedence [Feature:NetworkPolicy]","total":-1,"completed":12,"skipped":164,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce except clause while egress access to server in CIDR block [Feature:NetworkPolicy]","total":-1,"completed":20,"skipped":170,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policies to check ingress and egress policies can be controlled independently based on PodSelector [Feature:NetworkPolicy]","total":-1,"completed":13,"skipped":138,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policies to check ingress and egress policies can be controlled independently based on PodSelector [Feature:NetworkPolicy]","total":-1,"completed":8,"skipped":158,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic only from a pod in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":30,"skipped":450,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should support a 'default-deny-all' policy [Feature:NetworkPolicy]","total":-1,"completed":9,"skipped":130,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should work with Ingress, Egress specified together [Feature:NetworkPolicy]","total":-1,"completed":14,"skipped":147,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should support a 'default-deny-ingress' policy [Feature:NetworkPolicy]","total":-1,"completed":10,"skipped":117,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":15,"skipped":278,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector or NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":15,"skipped":302,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should work with Ingress,Egress specified together [Feature:NetworkPolicy]","total":-1,"completed":14,"skipped":150,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy]","total":-1,"completed":11,"skipped":216,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic from pods within server namespace based on PodSelector [Feature:NetworkPolicy]","total":-1,"completed":24,"skipped":269,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy API should support creating NetworkPolicy API operations","total":-1,"completed":17,"skipped":336,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should deny ingress access to updated pod [Feature:NetworkPolicy]","total":-1,"completed":13,"skipped":228,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should support allow-all policy [Feature:NetworkPolicy]","total":-1,"completed":23,"skipped":200,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector with MatchExpressions[Feature:NetworkPolicy]","total":-1,"completed":34,"skipped":463,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow egress access to server in CIDR block [Feature:NetworkPolicy]","total":-1,"completed":9,"skipped":162,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic only from a pod in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":19,"skipped":200,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow ingress access from updated namespace [Feature:NetworkPolicy]","total":-1,"completed":7,"skipped":79,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow ingress access from namespace on one named port [Feature:NetworkPolicy]","total":-1,"completed":16,"skipped":258,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Ports [Feature:NetworkPolicy]","total":-1,"completed":15,"skipped":166,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":12,"skipped":242,"failed":0}
100 8698k  100 8698k    0     0  17.1M      0 --:--:-- --:--:-- --:--:-- 17.1M
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow egress access on one named port [Feature:NetworkPolicy]","total":-1,"completed":17,"skipped":262,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce except clause while egress access to server in CIDR block [Feature:NetworkPolicy]","total":-1,"completed":20,"skipped":386,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should stop enforcing policies after they are deleted [Feature:NetworkPolicy]","total":-1,"completed":40,"skipped":545,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector with MatchExpressions[Feature:NetworkPolicy]","total":-1,"completed":20,"skipped":275,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should support a 'default-deny-ingress' policy [Feature:NetworkPolicy]","total":-1,"completed":33,"skipped":440,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should allow ingress access on one named port [Feature:NetworkPolicy]","total":-1,"completed":41,"skipped":548,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce multiple ingress policies with ingress allow-all policy taking precedence [Feature:NetworkPolicy]","total":-1,"completed":21,"skipped":226,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":18,"skipped":264,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce updated policy [Feature:NetworkPolicy]","total":-1,"completed":21,"skipped":381,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow ingress access on one named port [Feature:NetworkPolicy]","total":-1,"completed":21,"skipped":394,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow ingress access from updated namespace [Feature:NetworkPolicy]","total":-1,"completed":20,"skipped":300,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow ingress access from updated pod [Feature:NetworkPolicy]","total":-1,"completed":16,"skipped":180,"failed":0}
{"msg":"PASSED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic only from a different namespace, based on NamespaceSelector [Feature:NetworkPolicy]","total":-1,"completed":17,"skipped":180,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy]","total":-1,"completed":19,"skipped":296,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should support denying of egress traffic on the client side (even if the server explicitly allows this traffic) [Feature:NetworkPolicy]","total":-1,"completed":35,"skipped":406,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should allow ingress access from namespace on one named port [Feature:NetworkPolicy]","total":-1,"completed":16,"skipped":246,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce updated policy [Feature:NetworkPolicy]","total":-1,"completed":23,"skipped":283,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic from pods within server namespace based on PodSelector [Feature:NetworkPolicy]","total":-1,"completed":27,"skipped":318,"failed":0}
{"msg":"PASSED [sig-network] Netpol [LinuxOnly] NetworkPolicy between server and client should stop enforcing policies after they are deleted [Feature:NetworkPolicy]","total":-1,"completed":11,"skipped":118,"failed":0}
```

**Comment by jayunit100** [comment]
Lets wait for @aojea to green light in the AM, otherwise these look correct to me

**Comment by jayunit100** [comment]
thanks for the quick recovery @knabben

**Comment by aojea** [comment]
/lgtm
Thanks
@MrHohn @bowei can you please approve

**Pull request merged**
