### PR TITLE
Update AWS Configs to 1.0.3

### PR DESCRIPTION
**Pull request by feelobot**

### CODE REVIEW

**Comment by mbforbes** [comment]
@brendandburns who is our AWS go-to? I can't assign @justinsb :-(

**Comment by mbforbes** [comment]
@k8s-bot ok to test

**Comment by mbforbes** [comment]
@feelobot this LGTM but I have no idea what I'm looking at :-)

Question: Maybe use 1.0.3? It is the latest release.

Do you know of anyone else using AWS who might be able to review?

**Comment by justinsb** [comment]
I am hoping to get up to speed on CloudFormation soon.  But CoreOS is the primary user of CloudFormation templates (I believe?) so maybe we can ask @philips.

That said, I think this change looks good, though the problems will be if different arguments are required by the newer version, and whether we should in fact be using 1.0.3.

I don't think we should just automatically use the latest, because (1) I think we want these templates to be repeatable, and (2) it could be that 1.0.4 needs a new argument (for example, but maybe we're not doing that any more as part of our 1.0 contract?)

**Comment by mbforbes** [comment]
We aim for patch releases (e.g. 1.0.1 &rarr; 1.0.3) to contain only bug fixes and critical security updates, so doing a breaking change to require a new argument would be a Bad Thing&trade; and shouldn't happen (though is possible). So I agree that automatically using latest probably is less safe than manually pinning to a version, but I also think 1.0.3 is probably good to use.

**Comment by mbforbes** [comment]
Github had a hiccup: https://status.github.com/messages

Re-running shippable...

**Comment by brendandburns** [comment]
LGTM

**Pull request merged**
