### PR TITLE
fix the format

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by justinsb** [comment]
I suspect this was done to follow a code style that avoid go landmine 1 (https://gist.github.com/lavalamp/4bd23295a9f32706a48f).  cc @lavalamp seeing as you're the likely approver?

**Review by luxas — COMMENTED** [review]
Code changes LGTM, but do we have a policy of some kind for style changes like this?

Just wondering...

**Comment by justinsb** [comment]
I think we should, and I think it should be to do the code as it exists today, because of go landmine 1.

But, lavalamp is the one that I think would have the strongest opinion:

/assign @lavalamp

**Comment by jianglingxia** [comment]
I found that most of the k8s code is used this form,so this pr is right or remodify? thanks@justinsb @lavalamp @luxas

**Comment by jianglingxia** [comment]
ok,i will close it,thanks!

**Pull request closed without merging**
