### PR TITLE
Add mitchellh/go-wordwrap as unwanted module

### PR DESCRIPTION
**Pull request by dims**
Let's make sure we don't use `mitchellh/go-wordwrap` any more. We don't need to rush to eliminate it, but we don't want to expand the footprint more than it already is as well.

Related to https://github.com/kubernetes/kubernetes/issues/122399

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
is it unmaintained? it's not in the list of archived repos, right?

**Comment by skitt** [comment]
> is it unmaintained? it's not in the list of archived repos, right?

It’s not in the list, and it’s a very simple and stable library, with no change in the last four years.

**Comment by dims** [comment]
good points, dropping this PR

**Pull request closed without merging**
