### PR TITLE
kubelet: ensure static pod UIDs are unique

### PR DESCRIPTION
**Pull request by bboreham**
**What this PR does / why we need it**:
Fix the issue where pods like kube-proxy, created from the same static manifest across a cluster, all have the same UID. This breaks the concept of a unique ID and [confuses some tools](https://github.com/weaveworks/scope/issues/2931).

The underlying issue is a simple clash of behaviours: kubelet uses a md5 hasher which was changed to reset the hash in `DeepHashObject`.  The fix is to re-order the calls so that one goes first.
This does have the side-effect that all pod UIDs will change.

**Special notes for your reviewer**:
This is a re-opening of #43420. It and the similar #57135 were held up and ultimately abandoned over concerns that all pods would get restarted during upgrade.

Since then, several Kubernetes upgrades have restarted all pods, and there is a statement at #84443 that this is expected behaviour, so this should not be a reason to delay the fix.

```release-note
The calculation of pod UIDs for static pods has changed to ensure each static pod gets a unique value - this will cause all static pod containers to be recreated/restarted if an in-place kubelet upgrade from 1.20 to 1.21 is performed. Note that draining pods before upgrading the kubelet across minor versions is the supported upgrade path.
```

/kind bug
/sig node

### CODE REVIEW

**Comment by bboreham** [comment]
/retest

Failed tests kinda look like storage mount errors so let's see what happens if I roll the dice again.

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr :) Think this bug has a long history :) Trying to tag the folks who have been most involved in the conversation.

cc @tallclair @yujuhong @Random-Liu @dchen1107

**Comment by roffe** [comment]
Another stale copy of this issue?

**Comment by roffe** [comment]
can't we just merge it and be done with it?

**Comment by roffe** [comment]
this is slowly turning into comedy gold

**Comment by dashpole** [comment]
> Change the calculation of pod UIDs so that static pods get a unique value - will cause all containers to be killed and recreated after in-place upgrade.


Does it cause all pods to be restarted, or just static pods?

**Comment by bboreham** [comment]
> Does it cause all pods to be restarted, or just static pods?

Sorry I missed your question.  I believe it's all pods, because the line that moves resets the hasher, so all source information is missing from the pod hash currently, and when we add that in the hash will change.

**Comment by bboreham** [comment]
Rebased on latest main branch

**Comment by bboreham** [comment]
@dashpole @derekwaynecarr could you please approve again after rebase.  Tests passed on last re-run.

**Comment by derekwaynecarr** [comment]
impacts deployments that run control plane as static pods.

/milestone v1.20

**Comment by jeremyrickard** [comment]
> impacts deployments that run control plane as static pods.
> 
> /milestone v1.20

Hey there, just wanted to mention that this was after test freeze and the branch cut. If you’d like this in 1.20, it needs to be cherry picked and the release is tomorrow so this probably won’t make it until 1.20.1

**Comment by jberkus** [comment]
Seems like this is going to have to wait until 1.21, then?  Given that it forces a clusterwide restart.

Also, we can't be sure that no users are (ab)using this bug and treating it as a feature.

**Comment by roffe** [comment]
Milestone indeed. one of the oldest known bugs in Kubernetes has finally been fixed 🎉

**Pull request merged**
