### PR TITLE
Doc changes for nodelocaldns graduating to beta

### PR DESCRIPTION
**Pull request by prameshj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
 /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Documentation about nodelocaldns graduating to Beta.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NodeLocal DNSCache graduating to beta.
```

### CODE REVIEW

**Comment by prameshj** [comment]
do-not-merge/hold

**Comment by MrHohn** [comment]
@prameshj Is this ready for review?

**Comment by prameshj** [comment]
> @prameshj Is this ready for review?

Not yet, this is a placeholder PR.

**Comment by dstrebel** [comment]
Hello! We are starting Code Freeze for 1.15. Is this PR still planned to be included in 1.15?

**Comment by prameshj** [comment]
> Hello! We are starting Code Freeze for 1.15. Is this PR still planned to be included in 1.15?

Yes it is. Since we are adding more documentation in the website, the change in this PR is sufficient for the README.

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
