### PR TITLE
Reorganize vendor licenses again (revert #85220)

### PR DESCRIPTION
**Pull request by thockin**
/kind cleanup

**What this PR does / why we need it**:

Try again to restructure license files for easier review.  This is a revert and
cleanup on top of #85220, which was itself a revert of #76586.

```release-note
NONE

```

### CODE REVIEW

**Comment by thockin** [comment]
@liggitt since you orchestrated the revert - any thoughts on how to get the failing signal to fail/pass BEFORE committing?  Is there a way I can manually trigger those tests?  @BenTheElder too

**Comment by liggitt** [comment]
paging back in what went wrong... I vaguely remember a different install path taken when testing from built CI artifacts rather than building on the fly in the job itself?

https://github.com/kubernetes/kubernetes/issues/85196#issuecomment-553422381
looked like it pointed to
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#L325

which looked like the output was missing a LICENSE file it previously had?

**Comment by thockin** [comment]
Yes, BUT dims@ tried to fix that and it failed differently.   I am trying a different fix, but I need to iterate on kicking those tests off...

**Comment by BenTheElder** [comment]
I wasn't aware that CI vs presubmit was using a different install path on GCE ...
That rabbit hole may take some doing to explore ...

**Comment by BenTheElder** [comment]
cc @amwat @cheftako FYI re: GCE cluster scripts

**Comment by thockin** [comment]
Is there a way I can kick off the gci tests to see how they fare with this PR BEFORE merging?

**Comment by BenTheElder** [comment]
`pull-kubernetes-e2e-gce*` are running with kube-up on GCE (GCI is pretty meaningless at this point). there are a LOT of different things running on GCE with various options though. I don't think anybody knows all of them.

Kicking off periodic / postsubmit jobs from a PR is not something prow supports as far as I know, at best prow supports trying to convert from one type of job to another by hand in the config and having that be optionally triggered.

`gce-cos-master-default` should be the CI version of `pull-kubernetes-e2e-gce` I think.

**Comment by thockin** [comment]
@BenTheElder Let me ask a different question.  The previous attempt at this was rolled back because post-merge tests failed.  How can I be sure this second attempt doesn't fail?  How can I debug-and-iterate?

**Comment by BenTheElder** [comment]
# **Oh that's "easy" with cluster/kube-up and kubetest /s :|**

## For the job mentioned in https://github.com/kubernetes/kubernetes/issues/85196

### First find what we ran in CI

#### Find the logs
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features
=>
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1257476943473807360

#### Find the kubetest invocation
From the logs:

`Run: ('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-project-type=k8s-infra-gce-project', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--runtime-config=api/all=true', '--test_args=--ginkgo.focus=\\[Feature:(ServiceAccountIssuerDiscovery|StorageVersionHash|Audit|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes|RunAsGroup|TTLAfterFinished|NodeLease|VolumeSnapshotDataSource|CSIInlineVolume)\\]|Networking --ginkgo.skip=\\[Feature:(SCTPConnectivity|Volumes|Networking-Performance)\\]|IPv6|csi-hostpath-v0 --minStartupPods=8', '--timeout=180m')`

#### Rewrite it to work locally
=> drop the `Run: (`, drop the trailing `)`, `s#',#'#`, remove the `--gcp-service-account` flag (consumed as a pre-provisioned account for a storage driver test suite IIRC...?), drop `--gcp-project-type` (tells CI to vend a project) and replace it with `--gcp-project=thockin-k8s-dev` (insert your actual project name), drop `--timeout` (only there to prevent CI hang, you can ctrl-c).

#### Rewrite it to use your local sources instead of CI builds
=> to get iteration replace `--extract=ci/latest` with `--build` (and run from k8s checkout).

#### Result
Get:
`kubetest '--dump=/workspace/_artifacts' '--up' '--down' '--test' '--provider=gce' '--cluster=bootstrap-e2e' '--gcp-network=bootstrap-e2e' '--check-leaked-resources' '--gcp-node-image=gci' '--gcp-zone=us-west1-b' '--runtime-config=api/all=true' '--test_args=--ginkgo.focus=\\[Feature:(ServiceAccountIssuerDiscovery|StorageVersionHash|Audit|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes|RunAsGroup|TTLAfterFinished|NodeLease|VolumeSnapshotDataSource|CSIInlineVolume)\\]|Networking --ginkgo.skip=\\[Feature:(SCTPConnectivity|Volumes|Networking-Performance)\\]|IPv6|csi-hostpath-v0 --minStartupPods=8' '--build' '--gcp-project=thockin-k8s-dev'`

**Make a pot of coffee and come back to it after.**

### Better Iteration

Plausibly we don't care much about running the e2e tests.

We can rewrite the "highly intuitive" `--e2e_test` arg to just run one test.
I'll arbitrarily pick `[sig-service-catalog] [Feature:PodPreset] PodPreset should create a pod preset` from testgrid.

Obviously you couldn't just use that, it needs to be a regex an it needs to be escaped, so lazily something like:
`PodPreset.should.create.a.pod.preset`

=>

`kubetest '--dump=/workspace/_artifacts' '--up' '--down' '--test' '--provider=gce' '--cluster=bootstrap-e2e' '--gcp-network=bootstrap-e2e' '--check-leaked-resources' '--gcp-node-image=gci' '--gcp-zone=us-west1-b' '--runtime-config=api/all=true' '--test_args=--ginkgo.focus=PodPreset.should.create.a.pod.preset --ginkgo.skip= --minStartupPods=8' '--build' '--gcp-project=thockin-k8s-dev'`

Still probably going to want a cup of coffee between iterations.
Also I probably missed something.

**Comment by BenTheElder** [comment]
Sorry for the 8 hour delay and the snark. I'm still in the process of attempting to update all of the prows :roll_eyes: 

My best guess as to why the results are different is because presubmit builds with bazel and ~nothing else does.

The pushing / release upload and cluster up (modulo alpha feature enablement) should otherwise be the same as ci/latest between presubmit and this job, as far as I know.

It might be more productive to build both with and without bazel and diff.

**Comment by thockin** [comment]
Wow.  will try that.  So "easy". :)

kubetest could use a `--source` flag - GOPATH is antiquated.

Thanks

**Comment by thockin** [comment]
/bin/sh: 1: exec: /usr/local/bin/kube-scheduler: Permission denied

huh?

**Comment by cheftako** [comment]
> /bin/sh: 1: exec: /usr/local/bin/kube-scheduler: Permission denied
> 
> huh?

OK its not just me. Just pulled head and am seeing this.

**Comment by cheftako** [comment]
> > /bin/sh: 1: exec: /usr/local/bin/kube-scheduler: Permission denied
> > huh?
> 
> OK its not just me. Just pulled head and am seeing this.

Removed https://github.com/kubernetes/kubernetes/pull/90156/files#diff-6e3b476b9225d1213dc6ad13e453fc16R1939 locally and the problem went away. Not sure why we are seeing a problem with this now. (This change merged 2 weeks ago)

**Comment by thockin** [comment]
Debugging a bit I found the same - the binary in the mage is 0750

**Comment by thockin** [comment]
```
$ ls -l _output/release-stage/server/linux-amd64/kubernetes/server/bin/
total 1400936
-rwxr-x--- 1 thockin primarygroup  66753988 May  5 15:42 apiextensions-apiserver
-rwxr-x--- 1 thockin primarygroup  55291788 May  5 15:42 kubeadm
-rwxr-x--- 1 thockin primarygroup 163117499 May  5 15:42 kube-apiserver
-rw-r----- 1 thockin primarygroup        39 May  5 15:42 kube-apiserver.docker_tag
-rw------- 2 thockin primarygroup 217015808 May  5 15:42 kube-apiserver.tar
-rwxr-x--- 1 thockin primarygroup 150784793 May  5 15:42 kube-controller-manager
-rw-r----- 1 thockin primarygroup        39 May  5 15:42 kube-controller-manager.docker_tag
-rw------- 2 thockin primarygroup 204683264 May  5 15:42 kube-controller-manager.tar
-rwxr-x--- 1 thockin primarygroup  59962185 May  5 15:42 kubectl
-rwxr-x--- 1 thockin primarygroup 153948376 May  5 15:42 kubelet
-rwxr-x--- 1 thockin primarygroup  53463690 May  5 15:42 kube-proxy
-rw-r----- 1 thockin primarygroup        39 May  5 15:42 kube-proxy.docker_tag
-rw------- 2 thockin primarygroup 133632000 May  5 15:42 kube-proxy.tar
-rwxr-x--- 1 thockin primarygroup  59801313 May  5 15:42 kube-scheduler
-rw-r----- 1 thockin primarygroup        39 May  5 15:42 kube-scheduler.docker_tag
-rw------- 2 thockin primarygroup 113699840 May  5 15:42 kube-scheduler.tar
-rwxr-x--- 1 thockin primarygroup   2360254 May  5 15:42 mounter
```

```
$ ls -l _output/local/go/bin/kube-scheduler
-rwxr-x--- 1 thockin primarygroup 42491904 May  5 15:56 _output/local/go/bin/kube-scheduler
```

That's new...

**Comment by thockin** [comment]
Go version change?

**Comment by thockin** [comment]
umask

**Comment by cheftako** [comment]
> umask

Seems like there are a couple of options.
1. Relax the execute permissions. (I see you have a PR for that)
2. Revert the ownership change.
3. Finish the ownership change (#90780 is WIP for that change)

**Comment by thockin** [comment]
Thanks to @BenTheElder I am able to repro the problem.  Looking at it now.

**Comment by thockin** [comment]
I have reproduced and fixed the failure in the "gci" tests  There was one errant use of LICENSES that should have been LICENSE.  New push is up, will retitle this.  Ready for review.

**Comment by liggitt** [comment]
pull-kubernetes-e2e-gce failure:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/90575/pull-kubernetes-e2e-gce/1257890293206749186/artifacts/e2e-1f37270234-674b9-master/kube-master-installation.log

```
May 06 04:42:14.712004 e2e-1f37270234-674b9-master configure.sh[755]: mv: cannot stat '/home/kubernetes/kubernetes/ALL_LICENSES': No such file or directory
May 06 04:42:14.712622 e2e-1f37270234-674b9-master systemd[1]: kube-master-installation.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by thockin** [comment]
Dammit, why did my local test not fail.  Will dig more

**Comment by thockin** [comment]
The problem was that the bazel rule for ALL_LICENSES was failing silently (a glob() that matches nothing is still a success).  I expect this round of tests to pass, then I will clean up a squash the fix and will ping it.

**Comment by thockin** [comment]
OK, now I am baffled with Bazel.

@BenTheElder any ideas on why it complains file exists?

**Comment by BenTheElder** [comment]
looking, not off the top of my head, other than vaguely that IIRC the build involves some symlink shenanigans ..

**Comment by thockin** [comment]
Shenanigans indeed, debugging bazel when it fails is WHY we should rip it out with prejudice.

**Comment by thockin** [comment]
I think I got it.  

//build/release-tars:kubernetes-src depends on //:all-srcs depends on //vendor:all-srcs includes glob(**), so depending on the ALL_LICENSES was wrong.

Jeez that was hard to figure out and bazel is all but useless in offering clues.

**Comment by BenTheElder** [comment]
FWIW: +1 ...

**Comment by thockin** [comment]
For the record, running bazel locally to repro

mkdir $HOME/tmp/build_output; docker run   -e USER="$(id -u)"   -u="$(id -u)"  -v /etc/passwd.cache:/etc/passwd:ro -v `pwd`:/src/workspace   -v $HOME/tmp/build_output:/tmp/build_output   -w /src/workspace   l.gcr.io/google/bazel:2.2.0   --output_user_root=/tmp/build_output   build --sandbox_debug --logging=6 --verbose_failures -- //build/release-tars:kubernetes -//vendor/... -//build/... -//_output/... -//_thockin/... -//cluster/images/conformance/... //build/release-tars

**Comment by thockin** [comment]
Dammit, that STILL is not right.

**Comment by thockin** [comment]
OK.  This time I got it, but I am frankly not sure why.  `glob(["ALL_LICENSES/**/*"])` fails with file exists.  `glob(["ALL_LICENSES/**"])` also fails with file exists.  `glob(["ALL_LICENSES/**/LICENSE"])` works.  Why?  :shrug: 

To include a bunch of files in a tar, with a different prefix (aka `cp -R`) I couldn't find a better answer than a tar rule.  Sigh.

WRT the "should we rip out bazel" discussion, I change my vote from "if sig-testing says it is useful, I am ok to keep it" to "I'll PERSONALLY pay a bounty to the person who bring me the head of bazel-in-k/k".

**Comment by thockin** [comment]
I KNEW I should not have tempted fate

**Comment by thockin** [comment]
VICTORY!  CI passes and my manual run of GCI tests pass, too.  Now to clean it up.

/retest

**Comment by thockin** [comment]
Ahh crud.  update-vendor blows away my changes.  More work to do.

**Comment by thockin** [comment]
OK.  I have moved the LICENSES/ dir into the root of the tree (next to vendor/ and LICENSE).  There's a LICENSE file in there that is a copy of /LICENSE but I am out of patience to try to make that better.

Pushing now to test CI, but manual GCI test run passes and bazel build passes, so I have high hopes.  Commits are a mess, will squash and work on commit messages in parallel.

**Comment by thockin** [comment]
OK, it should be human-readable now.  This time I really REALLY got it.  :crossed_fingers:

**Comment by thockin** [comment]
OK, *this* time I got it.

**Comment by thockin** [comment]
BOOYA!

**Comment by liggitt** [comment]
🎉

**Comment by liggitt** [comment]
changes lgtm after commit cleanup

**Comment by liggitt** [comment]
actually, maybe you already did the commit cleanup... in which case

/lgtm

**Comment by thockin** [comment]
For future me:

To test bazel building of the release:
```
mkdir -p $HOME/tmp/build_output
docker run -it \
  -e USER="$(id -u)" \
  -u="$(id -u)" \
  -v /etc/passwd.cache:/etc/passwd:ro \
  -v `pwd`:/src/workspace \
  -v $HOME/tmp/build_output:$HOME/tmp/build_output \
  -w /src/workspace \
  l.gcr.io/google/bazel:2.2.0 \
    --output_user_root=$HOME/tmp/build_output  \
    build \
    --sandbox_debug \
    --logging=6 \
    --verbose_failures \
    -- \
    //build/release-tars
```

Then you can look at the resulting tar files.

To test the GCI build:
```
rm -rf /tmp/workspace
mkdir -p /tmp/workspace/_artifacts
GOPATH=/tmp/go \
nice -n 19 \
kubetest \
  --dump=/tmp/workspace/_artifacts \
  --build --up --test --down \
  --provider=gce \
  --cluster=bootstrap-e2e \
  --gcp-network=bootstrap-e2e \
  --check-leaked-resources \
  --gcp-node-image=gci \
  --gcp-zone=us-west1-b \
  --runtime-config=api/all=true \
  --test_args=--ginkgo.focus=PodPreset.should.create.a.pod.preset \
  --ginkgo.skip= \
  --minStartupPods=8 \
  --build \
  --gcp-project=thockin-dev-2 \
  2>&1 | tee /tmp/workspace/build.log
```
This runs pretty fast since there is only on actual test running.

**Comment by thockin** [comment]
@liggitt or @dims - anyone who has to review deps -- this should make you happy, so I call upon you to review it.  You probably can skim the commit that generates the files themselves

**Comment by liggitt** [comment]
tagged, drop the WIP prefix and it should be all set

**Comment by BenTheElder** [comment]
this has gotten flakier :(
[conntrack / TCP close_wait](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90575/pull-kubernetes-e2e-kind/1258833630487121920) we have a test fix out for, just went back and reviewed that

**Comment by BenTheElder** [comment]
belated
/lgtm
/approve

bash / bazel / ... looks good :+1: 
> Purge almost all memories of godep

unlikely :upside_down_face:

**Comment by liggitt** [comment]
The statefulset flake is root caused and has a fix in the queue as well

**Comment by BenTheElder** [comment]
/retest
teardown / timeout failure for kubemark-e2e-gce-big ...

**Comment by thockin** [comment]
w00t.  I did something useful.  Kind of useful, anyway.

**Comment by dims** [comment]
Kudos Tim!

**Pull request merged**
