### PR TITLE
Remove provisioner config from log message.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: hchiramm <hchiramm@redhat.com>
```
release-note-none

```

### CODE REVIEW

**Comment by wongma7** [comment]
we need to remove also https://github.com/kubernetes/kubernetes/blob/8a5e9ecf8febdfe5ca72d4d99340ce22cbf55cbb/pkg/volume/glusterfs/glusterfs.go#L1174

**Comment by humblec** [comment]
@wongma7 Done. thanks!

**Pull request merged**
