### PR TITLE
Download etcd for local-etcd kupe-up

### PR DESCRIPTION
**Pull request by linzichang**
Libvirt-coreos local-etcd kube-up can't work due to can't find the etcd binary. Because  d2284fee88613c2b108512f95a804b99fd1013a7 remove the etcd download. This commit bring the etcd download back and the local etcd discovery will work again.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@lhuard1A ptal

**Comment by erictune** [comment]
@lhuard1A  is the right person to review this.

**Comment by lhuard1A** [comment]
@linzichang the commit you mention is followed by 3545253 which makes libvirt-coreos use the etcd2 shipped within CoreOS. That’s why there’s no need to download an extra-version of etcd. CoreOS already comes with etcd2 installed.

**Comment by linzichang** [comment]
@lhuard1A Yes, I know that commit. I download etcd2 for local etcd-discover on host. It's not for CoreOS vm. You can see this PR https://github.com/kubernetes/kubernetes/pull/13124 .

**Comment by linzichang** [comment]
@lhuard1A Would you please look at this again?

**Comment by lhuard1A** [comment]
@linzichang I feel that the goal PR #13124 was to remove the dependency on `discovery.etcd.io` which is an extrenal dependency which might not always be reachable (for ex. offline local development.)

Rather than spawning a local etcd instance, I would prefer to completely get rid of the [“discovery” cluster bootstrap mechanism](https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#etcd-discovery) in favor of the [“static” cluster bootstrap mechanism](https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static).

It should be faster and lighter.

I submitted PR #14410 for that.
Could you please review it, check that it suits your needs, that it can replace PR #13124 and that this one is not needed anymore?

**Comment by linzichang** [comment]
@erictune @lhuard1A I have review https://github.com/kubernetes/kubernetes/pull/14410 and it suits my needs. I think this can be closed.

**Pull request closed without merging**
