### PR TITLE
Fix the output of health-mointor.sh

### PR DESCRIPTION
**Pull request by yujuhong**
The script show prints the errors/response of the health check, but not
show the progress of `curl`.

### CODE REVIEW

**Comment by yujuhong** [comment]
@dchen1107 I think we should cherry-pick this back to 1.5. WDYT?

**Comment by dchen1107** [comment]
/lgtm
and 
/approve

**Comment by yujuhong** [comment]
Hold on, I need to fix one more thing.

**Comment by yujuhong** [comment]
Modified the PR so we don't print the response if the health check passes. PTAL again. Thanks!

**Comment by gyliu513** [comment]
lgtm

**Comment by yujuhong** [comment]
@dchen1107 ping!

**Comment by yujuhong** [comment]
GCE e2e failed because the node could not download the network plugin:
```
Feb 17 22:36:08 e2e-gce-agent-pr-81-0-minion-group-wl85 startupscript: [ERROR   ] Unable to manage file: Error reading https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz: [Errno 101] Network is unreachable
Feb 17 22:36:08 e2e-gce-agent-pr-81-0-minion-group-wl85 startupscript: [INFO    ] Completed state [/var/cache/salt/minion/_opt_cni_bin.tar] at time 22:36:08.923045
Feb 17 22:36:08 e2e-gce-agent-pr-81-0-minion-group-wl85 startupscript: [ERROR   ] Unable to manage file: Error reading https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz: [Errno 101] Network is unreachable
Feb 17 22:36:08 e2e-gce-agent-pr-81-0-minion-group-wl85 startupscript: [INFO    ] Completed state [/opt/cni] at time 22:36:08.923768
```

Jenkins non-CRI GCE e2e failed because of GCL flakes (will file a bug). 
None of them are relevant to this PR.

**Comment by yujuhong** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot non-cri e2e test this

**Comment by yujuhong** [comment]
> Jenkins non-CRI GCE e2e failed because of GCL flakes (will file a bug).

#41668

**Pull request merged**
