### PR TITLE
Remove deprecated/dead Jenkins e2e_node tests

### LINKED ISSUE #92674: Cleanup e2e_node/jenkins
There are some leftover test artifacts from the time when e2e tests were executed with Jenkins.
The artifacts can be found here https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node/jenkins

We should look into these files and see
* what do we need to move elsewhere?
* what needs to be updated?
* what can we delete?

/help wanted
/good-first-issue
/sig node

### PR DESCRIPTION
**Pull request by Kappie37**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The test from Jenkins on e2e nodes is deprecated and dead.
#### Which issue(s) this PR fixes:

Fixes #92674

#### Special notes for your reviewer:
Please note any files I deleted wrongfully

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
if no jobs depend on files under the Jenkins folder it is good for me to remove them.
/lgtm

**Comment by cynepco3hahue** [comment]
looks like some files is still using
```
W0419 13:04:10.887] I0419 13:04:10.884712    6067 run_remote.go:404] parsing instance metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
W0419 13:04:10.888] F0419 13:04:10.884747    6067 run_remote.go:789] Failed to read metadata file "test/e2e_node/jenkins/cos-init-live-restore.yaml": open test/e2e_node/jenkins/cos-init-live-restore.yaml: no such file or directory
```

@Kappie37 Can you please re-check it?

**Comment by Kappie37** [comment]
@cynepco3hahue We could only leave the file `cos-init-live-restore.yaml` and delete the rest. I think it is more logical/clean to go to `run_remote.go` and either add the content of `cos-init-live-restore.yaml` (e.g., as a function) or move the file to a more relevant directory. What do you think? I do not know enough to decide what is best. I would say for simplicity, we leave the file in the Jenkins folder for now. We know we can at least delete the rest of the Jenkins folder files.

**Comment by cynepco3hahue** [comment]
You can check all yaml in use here - https://github.com/kubernetes/test-infra/tree/master/jobs/e2e_node
for example https://github.com/kubernetes/test-infra/blob/c3498c0da35fccae2d803a6aa356a638dcb0d6a4/jobs/e2e_node/image-config-serial-cpu-manager.yaml#L13
In general it can be nice to create a PR for the test infra to move all relevant yamls under it, similar to - https://github.com/kubernetes/test-infra/blob/c3498c0da35fccae2d803a6aa356a638dcb0d6a4/jobs/e2e_node/image-config-serial-hugepages.yaml#L8

**Comment by pacoxu** [comment]
After https://github.com/kubernetes/test-infra/pull/23320 is merged, we can retest this PR.

**Comment by endocrimes** [comment]
/hold This breaks `make test-e2e-node` when using REMOTE=true

Currently this passes `metadata="user-data<${KUBE_ROOT}/test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"` by default, unless using another manually specified image config for GPU/device tests.

**Comment by endocrimes** [comment]
> @cynepco3hahue We could only leave the file `cos-init-live-restore.yaml` and delete the rest. I think it is more logical/clean to go to `run_remote.go` and either add the content of `cos-init-live-restore.yaml` (e.g., as a function) or move the file to a more relevant directory. What do you think? I do not know enough to decide what is best. I would say for simplicity, we leave the file in the Jenkins folder for now. We know we can at least delete the rest of the Jenkins folder files.

These are paramaterisable right now, with the default being gci-init. Others are also used however by different E2Es. Splitting this across two repos introduces a higher barrier to entry to folks testing against GCP in their local development while iterating on tests however (as it means that it's harder to test/update trickier e2e's a.la #104606)

**Comment by endocrimes** [comment]
Honestly I'd be more tempted by moving everything to `test/e2e_node/init-configs` or similar, bc they are somewhat more part of the tests than they are generic infra (as tests are written against those configs). Also keeps the cycle for iterating on them fairly fast.

**Comment by SergeyKanzhelev** [comment]
@Kappie37 please re-open if you plan to move this forward. Please see @endocrimes suggestion on what needs to be done to not break remote tests scenario

**Pull request closed without merging**
