### PR TITLE
Automated cherry pick of #44679

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #44679 on release-1.6.

#44679: Update gcr.io/google_containers/porter image to 4524579c0eb935c056c8e75563b4e1eda31587e0

#44638 explains why we need this; the old porter image has a certificate which is invalid with go1.8+; as a result, upgrade tests are failing without this PR.

x-ref #47374

### CODE REVIEW

**Comment by bowei** [comment]
needs approval

**Comment by roberthbailey** [comment]
@enisoc - please approve as the 1.6 branch owner.

**Comment by enisoc** [comment]
@roberthbailey I already did. :)

**Comment by roberthbailey** [comment]
Oh, thanks. I didn't see a comment from you so I'd assumed the /approve from @mikedanese added the label to the PR.

**Pull request merged**
