### PR TITLE
Uses the resource-consumer/controller image instead of resource-consumer-controller

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind bug
/kind failing-test

/sig testing

**What this PR does / why we need it**:

Dockerhub does not support slashes in the image names, so when the tests are
configured to use a dockerhub registry instead of the current
gcr.io/kubernetes-e2e-test-images registry, the tests using the mentioned image
will fail, as the image cannot exist and cannot be pulled.

Original discussion: https://github.com/kubernetes/kubernetes/issues/74134

**Which issue(s) this PR fixes**:

Related #60487
Needed by #73489

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @listx 

Linus, can you please help with this?

**Comment by dims** [comment]
Linus, more context about this is at [1]

[1] https://groups.google.com/d/msg/kubernetes-sig-node/VLwB7zYoflc/f9Xz811WBwAJ

**Comment by listx** [comment]
The promoter today only supports promoting from the 3 registries in https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io:

```
gcr.io/k8s-staging-cluster-api
gcr.io/k8s-staging-coredns
gcr.io/k8s-staging-csi
```

to the destination:

```
{us,eu,asia}.gcr.io/k8s-gcr-prod
```

In order to use the image promotion process as described in this ticket, some things need to happen:

(1) The images need to be pushed up to some staging registry (maybe create a new staging registry, maybe called `gcr.io/k8s-staging-e2e-test-images`).
(2) @bclau needs to be given push access to that new registry.
(3) A new promoter manifest must be created in `https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io`.
(4) The existing Prow jobs must be updated to know about (3).
(6) Because this issue wants to push images to `gcr.io/kubernetes-e2e-test-images`, we need to track that registry as well with the manifest; so we have to (a) create a new Kubernetes secret that has read/write access there, and (b) start tracking all images that already exist there in the new promoter manifest at (3).
(7) As an alternative to step (6), we can just use `gcr.io/k8s-gcr-prod` as the destination if that's acceptable --- maybe `gcr.io/k8s-gcr-prod/e2e-test-images/resource-consumer/controller`?

I would prefer to do step (7), not step (6), because the promoter will most likely loudly complain about images having empty tags and such (the promoter will still work, it's just that the error messages will be a bit erroneous). This is because https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/7 is not yet implemented. Also, https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/15 would help make (3) much faster and less error-prone.

**Comment by dims** [comment]
@thockin WDYT? ( please see last comment from @listx )

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
I am removing LGTM until you get tests to pass.

**Comment by dims** [comment]
@thockin for the job to pass we need to push an updated image named `resource-consumer-controller` instead of the current `resource-consumer/controller` (edited)

**Comment by thockin** [comment]
Who is doing that?

**Comment by listx** [comment]
I just re-read the related links and basically we just need to rename an existing image (I thought that we had to build a new image, but that is not the case). Actually it's not even renaming as the old name will still exist --- it's more like adding a new tag.

I can do that on my end unless someone has objections. For *new* images though, my original comment above still stands (it would be nice to use the new promotion process where we can).

**Comment by listx** [comment]
Actually, I suppose this does require re-building images (with the changes in this Makefile) because there are quite a few images named resource-consumer-controller (with variants created for different archs, etc). I thought it was going to be a case of simply adding a tag here and there, but alas it's not so simple.

I'll have to do the build/push manually to ensure correctness.

**Comment by listx** [comment]
I just pushed up the images.

/retest

**Comment by bclau** [comment]
The tests seems to have passed. I think we can merge this.

**Comment by dims** [comment]
/lgtm

Thanks for your patience @bclau

**Pull request merged**
