### PR TITLE
ignore letter case

### PR DESCRIPTION
**Pull request by foxyriver**
**What this PR does / why we need it**:

ignore letter case when matching keyword

### CODE REVIEW

**Comment by thockin** [comment]
Why?  Is this an actual problem?

**Comment by foxyriver** [comment]
@thockin you are right, it is not an actual problem. I am just used to ignore letter case when matching the error log which depend on the operating system. :)

**Comment by thockin** [comment]
I don't think we need hypotheticals here.  I appreciate the PR, but we'd want to do this in 1000 other places, if we start down this road.  It's a bad pattern in the first place (string comparing errors)

**Pull request closed without merging**
