### PR TITLE
Adding --fail-swap-on=false to hack/local-up-cluster.sh

### PR DESCRIPTION
**Pull request by sbezverk**
After issue #47181 got merged kubelet started failing when
started by local-up-cluster.sh Adding this flag to allow kubelet to
start properly.

### CODE REVIEW

**Comment by sbezverk** [comment]
Closes #50373

**Review by dims — APPROVED** [review]
LGTM +1

**Comment by liggitt** [comment]
Isn't the point of making people opt in because the kubelet doesn't behave as expected when swap is on? It seems better to actually make people opt in to running in this mode

**Comment by liggitt** [comment]
e.g. `KUBELET_FLAGS=--fail-swap-on=false hack/local-up-cluster.sh`

**Comment by dims** [comment]
@liggitt so you are recommending detecting the situation and printing a warning for them to use the command line like that? Sounds good to me!

**Comment by cblecker** [comment]
Yeah, I'm good with that too.
/lgtm cancel

@sbezverk Want to take a crack at a detection/warning message, rather than altering the default?

**Comment by sbezverk** [comment]
@cblecker works for me. I will take a stab at it.

**Comment by fejta** [comment]
/unassign
Happy to delegate to the other participants in this thread

**Comment by cblecker** [comment]
Fixed in #51054
/closed

**Comment by cblecker** [comment]
Fixed in #51054
/close

**Pull request closed without merging**
