### PR TITLE
adding SergeyKanzhelev as SIG Node approver

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind feature
/priority backlog
/sig node

#### Special notes for your reviewer:

I am self nominating as a SIG Node approver. I was involved with SIG Node for
about the 4 years now and was contributing, reviewing, and overseeing numerous
contributions ranging from full cycle of features development to bugs and test
failures investigations.

The following is the list of formal requirements as well as the extended
contributors ladder suggestions from SIG Node.

# Formal requirements

- [x] Reviewer of the codebase for at least 3 months  
- Reviewer for 4 years: [https://github.com/kubernetes/kubernetes/pull/97329](https://github.com/kubernetes/kubernetes/pull/97329)  
- Approver for SIG Node Tests for 3 years: [https://github.com/kubernetes/kubernetes/pull/104183](https://github.com/kubernetes/kubernetes/pull/104183)   
- [x] Primary reviewer for at least 10 substantial PRs to the codebase  
    1. Fix that PodIP field is temporarily removed for a terminal pod [https://github.com/kubernetes/kubernetes/pull/125404](https://github.com/kubernetes/kubernetes/pull/125404/)   
    2. Allow changing pod log directory [https://github.com/kubernetes/kubernetes/pull/112957](https://github.com/kubernetes/kubernetes/pull/112957)   
    3. \[Sidecar Containers\] Sidecar containers finish time needs to be accounted for in job controller [https://github.com/kubernetes/kubernetes/pull/124942](https://github.com/kubernetes/kubernetes/pull/124942)   
    4. Add SidecarContainers feature [https://github.com/kubernetes/kubernetes/pull/116429](https://github.com/kubernetes/kubernetes/pull/116429)   
    5. Allow all probes and lifecycle for restartable init containers [https://github.com/kubernetes/kubernetes/pull/119168](https://github.com/kubernetes/kubernetes/pull/119168) 

    From my reviewer application :-) :

    6. dockershim ExecSync should return context.DeadlineExeceeded on timeout [https://github.com/kubernetes/kubernetes/pull/96495](https://github.com/kubernetes/kubernetes/pull/96495)   
    7. Adding 'Accept' header to HTTP Probe [https://github.com/kubernetes/kubernetes/pull/95641](https://github.com/kubernetes/kubernetes/pull/95641)   
    8. Don't create a new sandbox for pod with RestartPolicyOnFailure if all containers succeeded [https://github.com/kubernetes/kubernetes/pull/92614](https://github.com/kubernetes/kubernetes/pull/92614)   
    9. Cleanup tempfiles [https://github.com/kubernetes/kubernetes/pull/92288](https://github.com/kubernetes/kubernetes/pull/92288)   
    10. fix windows container root validate [https://github.com/kubernetes/kubernetes/pull/92355](https://github.com/kubernetes/kubernetes/pull/92355) 
    

    Over 50 PRs in CRI tools: [https://github.com/kubernetes-sigs/cri-tools/pulls?q=is%3Apr+involves%3A%40me+is%3Aclosed](https://github.com/kubernetes-sigs/cri-tools/pulls?q=is%3Apr+involves%3A%40me+is%3Aclosed) 

    

- [x] Reviewed or merged at least 30 PRs to the codebase  
      Just listing 30 PRs authored in k/k:  
    1. Implement resource health in pod status (KEP 4680\) [https://github.com/kubernetes/kubernetes/pull/126243](https://github.com/kubernetes/kubernetes/pull/126243)  
    2. device plugin failure tests [https://github.com/kubernetes/kubernetes/pull/125753](https://github.com/kubernetes/kubernetes/pull/125753)   
    3. improve logging of pod admission denied [https://github.com/kubernetes/kubernetes/pull/125631](https://github.com/kubernetes/kubernetes/pull/125631)  
    4. added init to image-utils.sh [https://github.com/kubernetes/kubernetes/pull/124449/](https://github.com/kubernetes/kubernetes/pull/124449/)   
    5. allow agnhost to set TLS gRPC [https://github.com/kubernetes/kubernetes/pull/124104](https://github.com/kubernetes/kubernetes/pull/124104)   
    6. added init containers tests to simplify the sidecar KEP large PR [https://github.com/kubernetes/kubernetes/pull/117654](https://github.com/kubernetes/kubernetes/pull/117654)   
    7. change the seccompProfile field description to match the imlpementation [https://github.com/kubernetes/kubernetes/pull/117505](https://github.com/kubernetes/kubernetes/pull/117505)   
    8. added known issue for 1.27 release [https://github.com/kubernetes/kubernetes/pull/116863](https://github.com/kubernetes/kubernetes/pull/116863)   
    9. deprecate ExperimentalHostUserNamespaceDefaulting [https://github.com/kubernetes/kubernetes/pull/116723](https://github.com/kubernetes/kubernetes/pull/116723)   
    10. fix standalone test [https://github.com/kubernetes/kubernetes/pull/116628](https://github.com/kubernetes/kubernetes/pull/116628)   
    11. AppArmor no reevaluation of host is needed [https://github.com/kubernetes/kubernetes/pull/116606](https://github.com/kubernetes/kubernetes/pull/116606)   
    12. Test kubelet standalone mode [https://github.com/kubernetes/kubernetes/pull/116551](https://github.com/kubernetes/kubernetes/pull/116551)   
    13. initialize feature gates in test project [https://github.com/kubernetes/kubernetes/pull/116494](https://github.com/kubernetes/kubernetes/pull/116494)   
    14. Three more lifecycle checks to demonstrate various validation techniques for containers lifecycle checks [https://github.com/kubernetes/kubernetes/pull/116426](https://github.com/kubernetes/kubernetes/pull/116426)   
    15. rename ExperimentalPodPidsLimit to PodPidsLimit [https://github.com/kubernetes/kubernetes/pull/116266](https://github.com/kubernetes/kubernetes/pull/116266)   
    16. GRPCContainerProbe is GA [https://github.com/kubernetes/kubernetes/pull/116233](https://github.com/kubernetes/kubernetes/pull/116233)   
    17. small comment the ephemeral containers are not accounted for the QoS [https://github.com/kubernetes/kubernetes/pull/115485](https://github.com/kubernetes/kubernetes/pull/115485)  
    18. update docs for ContainerStatus fields [https://github.com/kubernetes/kubernetes/pull/115463](https://github.com/kubernetes/kubernetes/pull/115463)   
    19. change the comment in CRI API to point to the correct logs directory [https://github.com/kubernetes/kubernetes/pull/115292](https://github.com/kubernetes/kubernetes/pull/115292)   
    20. Automated cherry pick of \#115143: add custom dialer optimized for probes [https://github.com/kubernetes/kubernetes/pull/115278](https://github.com/kubernetes/kubernetes/pull/115278)   
    21. use a proper regex looking for the restartCount [https://github.com/kubernetes/kubernetes/pull/115273](https://github.com/kubernetes/kubernetes/pull/115273)   
    22. Document versioning of CRI API [https://github.com/kubernetes/kubernetes/pull/114394](https://github.com/kubernetes/kubernetes/pull/114394)   
    23. rotate-certificates is a GA feature now [https://github.com/kubernetes/kubernetes/pull/114379](https://github.com/kubernetes/kubernetes/pull/114379)   
    24. added limit value to the pod validation error to simplify debugging [https://github.com/kubernetes/kubernetes/pull/112925](https://github.com/kubernetes/kubernetes/pull/112925)   
    25. remove DynamicKubeletConfig feature gate from the code [https://github.com/kubernetes/kubernetes/pull/112643](https://github.com/kubernetes/kubernetes/pull/112643)   
    26. remove podOverhead feature gate as a feature is now GA since 1.24  [https://github.com/kubernetes/kubernetes/pull/112579](https://github.com/kubernetes/kubernetes/pull/112579)   
    27. fix the registry configuration [https://github.com/kubernetes/kubernetes/pull/110313](https://github.com/kubernetes/kubernetes/pull/110313)   
    28. fix the image for node performance tests \- model expected tensorflow [https://github.com/kubernetes/kubernetes/pull/109551](https://github.com/kubernetes/kubernetes/pull/109551)   
    29. check for the test duraiton to make NodeProblemDetector test reliable [https://github.com/kubernetes/kubernetes/pull/109396](https://github.com/kubernetes/kubernetes/pull/109396)   
    30. fix the retry logic in ssh in test framework [https://github.com/kubernetes/kubernetes/pull/109314](https://github.com/kubernetes/kubernetes/pull/109314)   
- [x] Nominated by a subproject owner  
- Nominated by @**mrunalp**  
- [ ] With no objections from other subproject owners:  
    - [ ] @Random-Liu  
    - [x] @dchen1107  
    - [x] @derekwaynecarr  
    - [ ] @yujuhong  
    - [ ] @sjenning  
    - [x] @mrunalp  
    - [ ] @klueska

# SIG Node ladder requirements

SIG Node [ladder document](https://github.com/kubernetes/community/blob/master/sig-node/sig-node-contributor-ladder.md) defines additional requirements.

Deep expertise across multiple sub-systems

- [x] Demonstrated impact across multiple sub-systems.  
- Test kubelet standalone mode [https://github.com/kubernetes/kubernetes/pull/116551](https://github.com/kubernetes/kubernetes/pull/116551)   
- Container lifecycle area: new approach of testing container lifecycle [https://github.com/kubernetes/kubernetes/pull/116426](https://github.com/kubernetes/kubernetes/pull/116426)   
- Device plugin area: new device plugin failure tests (new approach for tests of device plugin aligned with DRA): [https://github.com/kubernetes/kubernetes/pull/125753](https://github.com/kubernetes/kubernetes/pull/125753)   
- CRI API: Versioning of CRI API documented [https://github.com/kubernetes/kubernetes/pull/114394](https://github.com/kubernetes/kubernetes/pull/114394)   
- [x] Troubleshooting complex issues that cross-subsystems with deep understanding of tooling and code base.

      Troubleshooting issues as part of GKE support. Example of an issues brought into the upstream:

- Terminated but not GC'd Pods should not be re-admitted on kubelet restart [https://github.com/kubernetes/kubernetes/issues/126341](https://github.com/kubernetes/kubernetes/issues/126341) 

Proficient in features development

- [x] Drive a few major KEPs at all three stages:  
- [x] “alpha” \- design proposal and discussions  
- SidecarContainers: from 0 to Beta: [https://github.com/kubernetes/enhancements/issues/753](https://github.com/kubernetes/enhancements/issues/753)  
- Device Health in Pod Status to alpha: [https://github.com/kubernetes/enhancements/issues/4680](https://github.com/kubernetes/enhancements/issues/4680)  
- gRPC endpoint from 0 to GA: [https://github.com/kubernetes/enhancements/issues/2727](https://github.com/kubernetes/enhancements/issues/2727)   
- [x] “beta” \- initial customer feedback collection  
- SidecarContainers: from 0 to Beta: [https://github.com/kubernetes/enhancements/issues/753](https://github.com/kubernetes/enhancements/issues/753)  
- gRPC endpoint from 0 to GA: [https://github.com/kubernetes/enhancements/issues/2727](https://github.com/kubernetes/enhancements/issues/2727)   
- [x] “GA/deprecation” \- stabilizing feature, following PRRs, or managing deprecation.  
- Deprecated the Dynamic Kubelet Configuration [https://github.com/kubernetes/enhancements/issues/281](https://github.com/kubernetes/enhancements/issues/281)  
- GA of PodOverhead: [https://github.com/kubernetes/enhancements/issues/688](https://github.com/kubernetes/enhancements/issues/688)  
- [x] Demonstrate ability to stage changes and pass PRRs keeping the end user experience and Kubernetes reliability as top priorities.  
- Sidecar containers feature is in beta and used widely  
- [x] Be a reviewer for a few major KEPs and demonstrate meaningful participation in the review process.  
- I am a reviewers of a few KEPs every release cycle. Some latest examples:  
- AppArmor GA: [https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/24-apparmor/kep.yaml\#L19](https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/24-apparmor/kep.yaml\#L19)  
- Cgroup v1 maintanence mode: [https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/4569-cgroup-v1-maintenance-mode/kep.yaml\#L12](https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/4569-cgroup-v1-maintenance-mode/kep.yaml\#L12)   
- Max image GC age: [https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/4210-max-image-gc-age/kep.yaml\#L9](https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/4210-max-image-gc-age/kep.yaml\#L9)  
  See also [https://github.com/search?q=repo%3Akubernetes%2Fenhancements%20SergeyKanzhelev\&type=code](https://github.com/search?q=repo%3Akubernetes%2Fenhancements%20SergeyKanzhelev\&type=code)   
- [x] Give actionable feedback for the KEPs and initial proposals during the SIG node meetings.  
- As a SIG Node chair and often the meeting host gave feedback on proposals during SIG Node meetings. Like a declarative node maintenance or QoS class-based resources, etc.

Active community support

- [x] Be a primary PR reviewer for numerous PRs in multiple areas listed as a requirement for a reviewer.  
    - [x] See the list of PRs above

- [x] Actively triage issues and PRs, provide support to contributors to drive their PRs to completion.  
- SIG Node CI working group lead and often the host to triage bugs and PRs.

Be present 

- [x] Participate in SIG Node meetings by speaking about KEPs or improvements driven, or find some other way to prove the identity behind GitHub handle.  
- As a chair of SIG Node, I often provide the initial feedback on KEP proposals and design reviews.

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
100% support this nomination as a sig-node reviewer

**Comment by mrunalp** [comment]
Thanks for all your work @SergeyKanzhelev. I am very happy to support your role as approver. :+1:

**Comment by bart0sh** [comment]
@SergeyKanzhelev Thank you for your great work! I fully support this nomination.

**Comment by dchen1107** [comment]
Thank you @SergeyKanzhelev for your contribution to SIG Node and K8s community.

**Comment by ffromani** [comment]
I fully support this nomination!

**Comment by aojea** [comment]
+1

**Comment by derekwaynecarr** [comment]
thanks for all your efforts @SergeyKanzhelev , it has been a pleasure.

+1

**Comment by rphillips** [comment]
+1 
/lgtm

**Comment by pacoxu** [comment]
big +1

Thanks for your help in SIG-Node related issues/PRs/enhancements.

**Comment by SergeyKanzhelev** [comment]
> please assign [thockin](https://github.com/thockin) for approval.

/assign @thockin 

as per bot recommendation.

**Comment by thockin** [comment]
/approve

Congratulations and thank you for doing the hard work.

**Pull request merged**
