### PR TITLE
Automated cherry pick of #50673

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #50673 on release-1.8.

#50673: Support German cloud for azure disk mount feature

**Release note**:

```
Support German cloud for azure disk mount feature
```

### CODE REVIEW

**Comment by jpbetz** [comment]
@andyzhangx I found the release note on the cherry picked PR difficult to understand. Would you please update it to be more clear?

**Comment by andyzhangx** [comment]
@jpbetz pls check again, thx

**Pull request merged**
