### PR TITLE
Updated Links to IANA for Service Name and Transport Protocol Port Number Registry

### LINKED ISSUE #106980: Update links to IANA for Service Name and Transport Protocol Port Number Registry
### What happened?

We should make the change in PR https://github.com/kubernetes/kubernetes/pull/105590

### What did you expect to happen?

API reference links to https://www.iana.org/assignments/ should use HTTPS, not HTTP

### How can we reproduce it (as minimally and precisely as possible)?

Visit h
ttps://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/ and look at the IANA hyperlinks

### Anything else we need to know?

Once this fix is made, a PR to [k/website](https://github.com/kubernetes/website/) is needed to update the docs (by autogenerating them). This typically would be deferred until the next Kubernetes release.
### Kubernetes version

v1.23

### Cloud provider

_not applicable_

### OS version

_not applicable_

### Install tools

_not applicable_

### Container runtime (CRI) and and version (if applicable)

_not applicable_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_not applicable_

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR updates links to IANA for Service Name and Transport Protocol Port Number Registry.

#### Which issue(s) this PR fixes:
Fixes #106980 

#### Does this PR introduce a user-facing change?
```
NONE
```

### CODE REVIEW

**Comment by sftim** [comment]
Also
/kind documentation

**Comment by dims** [comment]
bad merge @jayesh-srivastava you may want to open a fresh PR

**Comment by jayesh-srivastava** [comment]
Yes @dims, accidentally fetched and merged commits on my remote repo and all this happened. But I have reset it to the original commit. Will this work now?

**Comment by dims** [comment]
you can't touch vendor/ directory files Jayesh. you will have to update the correct repos first before we can update the copy we have in k/k

**Comment by jayesh-srivastava** [comment]
Oh okay @dims. Understood. Will make a new PR.

**Pull request closed without merging**
