### PR TITLE
Delete the broken Celery+RabbitMQ example

### PR DESCRIPTION
**Pull request by vishh**
The celery container used in the example is broken and does not come up
on most distros. The e2e test that was validating this example was not
detecting the fact the celery pod was crash looping. 
I attempted to fix the celery container, but it proved to be tedious.
The proposed fix is to update the glibc version to >= 2.23. In this case
it requires updating the python docker image and the celery base image.

https://github.com/kubernetes/kubernetes/issues/31456
has more details. 

I'm deleting the example instead of marking it as broken because a user
might overlook the broken warning and it should be trivial to revert
this PR if someone can fix the celery container.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31475)

### CODE REVIEW

**Comment by vishh** [comment]
cc @adityakali

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @pwittrock I am not marking this for 1.4 milestone yet. This pr has no risk at all since it is only deleting a broken example. But I think you, as the release czar should make the final call here. Thanks!

**Comment by vishh** [comment]
P1 since it is fixing a flaky/broken test

**Comment by pwittrock** [comment]
@dchen1107 Thanks!  Anything fixing a flake can go into v1.4 as P0 or P1

**Pull request merged**
