### PR TITLE
Method call 'err.Error()' might lead to a nil pointer dereference for pkg/kubelet/cm/cpumanager/cpu_assignment_test.go

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Method call 'err.Error()' might lead to a nil pointer dereference in `pkg/kubelet/cm/cpumanager/cpu_assignment_test.go` for `TestTakeByTopologyNUMAPacked`
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/triage accepted

**Review by yangjunmyfm192085 — COMMENTED** [review]
/release-note-none

**Review by ehashman — COMMENTED** [review]
/release-note-none
/priority backlog
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
