### PR TITLE
retry salt-call in configure-vm.sh

### LINKED ISSUE #32478: Kubeletes NotReady because of lack of CNI plugin make cluster startup scripts fail.
Noticeably often (#31513) startup of cluster in scalability suite (100) Nodes fail, because 2 Nodes don't have CNI plugins installed:

```
I0910 17:19:59.718154    3719 kubelet.go:2240] skipping pod synchronization - [could not locate kubenet required CNI plugins [bridge host-local loopback] at "/opt/cni/bin" or "/usr/libexec/kubernetes/kubelet-plugins/net/exec/"]
```

which in turn causes tests to fail.

cc @kubernetes/sig-cluster-lifecycle @kubernetes/goog-node @wojtek-t

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #32478

cc @gmarek 

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34509)

### CODE REVIEW

**Comment by mikedanese** [comment]
Fixes #32478

**Comment by gmarek** [comment]
Thanks!

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by gmarek** [comment]
I don't have enough context around setup scripts now. @zmerlynn can you take a look?

**Review by zmerlynn — COMMENTED** [review]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot cvm gke e2e test this

**Comment by wojtek-t** [comment]
Nice - thanks!

**Pull request merged**
