### PR TITLE
Automated cherry pick of #96530: Fixed quantization and made monotic time reversal not panic

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #96530 on release-1.19.

#96530: Fixed quantization and made monotic time reversal not panic

Reason for cherry-pick: fixes https://github.com/kubernetes/kubernetes/issues/96459

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve

**Comment by deads2k** [comment]
This is one worth cherrypicking, especially for dependent projects to avoid people forking unnecessarily.

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
