### PR TITLE
[1.13] Automated cherry pick of #83261: bump gopkg.in/yaml.v2 v2.2.4

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #83261 on release-1.13.

#83261: bump gopkg.in/yaml.v2 v2.2.4

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @BenTheElder for kind failures (I'm not sure it's intended to be running against this branch)

**Comment by liggitt** [comment]
looks like the nvidia GPU tests are red on this branch

**Comment by BenTheElder** [comment]
It's not intended to be running but also shouldn't block.
I'll look at the job definition, IIRC we're skipping branches instead of selecting master, probably we don't skip 1.13...

**Comment by BenTheElder** [comment]
sorry for the noise and thanks for the heads up, filed https://github.com/kubernetes/test-infra/pull/14594 to skip all release branches.

**Pull request merged**
