### PR TITLE
Use proper manifest images

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for using proper manifest images in the yaml/manifests we are using for e2e tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @ixdy @dims

### CODE REVIEW

**Comment by mkumatag** [comment]
@ixdy @dims can you please review this PR?

**Review by dims — APPROVED** [review]
/lgtm

/kind cleanup

**Pull request merged**
