### PR TITLE
move GenericControllerManagerConfiguration and KubeCloudSharedConfigu…

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: andrewsykim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As part of https://github.com/kubernetes/kubernetes/issues/81172, it would be useful to move `GenericControllerManagerConfiguration` and `KubeCloudSharedConfiguration` moved to a staging repo so it can be consumed by both kube-controller-manager and cloud-controller-manager (to be staged).

`k8s.io/component-base/controllermanager` can also be home to some new types introduced in https://github.com/kubernetes/kubernetes/pull/84259 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/milestone v1.19
/sig cloud-provider api-machinery
/priority important-longterm

**Comment by cheftako** [comment]
Hi Andrew. I think we should move this to a staging/controller-manager repo rather than component-base. Working on getting that repo created.

**Review by andrewsykim — COMMENTED** [review]
/close

Closing in favor of https://github.com/kubernetes/kubernetes/pull/91014

**Comment by andrewsykim** [comment]
> staging/controller-manager repo

Did you mean `staging/kube-controller-manage` or to create a new staging repo `controller-manager`?

**Pull request closed without merging**
