### PR TITLE
Fix expired unit test certs

### LINKED ISSUE #102228: Failing Test `vendor/k8s.io/kube-aggregator/pkg/apiserver TestProxyCertReload` due to hardcoded certificate expiration
#### Which jobs are failing:
pull-kubernetes-unit

#### Which test(s) are failing:
vendor/k8s.io/kube-aggregator/pkg/apiserver TestProxyCertReload

#### Since when has it been failing:
May 22, 2021

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92739/pull-kubernetes-unit/1396247373138628608

#### Reason for failure:
Certificate hardcoded on line 853 in unit test[1] has expired today on May 22, 2021.
[1]: https://github.com/kubernetes/kubernetes/blob/96e4e953978416e164e001abd2c607ce357fdd46/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind failing-test

fixes https://github.com/kubernetes/kubernetes/issues/102228

#### What this PR does / why we need it:

Fixes expired test certs that were only valid for 1 year.

Makes them valid for 100 years and adds a generation script to regenerate them if needed.

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
nice touch converting the variables into methods :)

100 years! some fun facts https://www.wolframalpha.com/input/?i=876000+hours

/approve
/lgtm

**Comment by liggitt** [comment]
picks open to 1.19 - 1.21 as well

**Comment by liggitt** [comment]
sigh, fixed shellcheck warning

**Comment by liggitt** [comment]
Reading lgtm after shellcheck fix

**Pull request merged**
