### PR TITLE
Modify balancedResourceScorer to use a weighted standard deviation

### PR DESCRIPTION
**Pull request by kimminw00**
#### What type of PR is this?
kind/feature

#### What this PR does / why we need it:
A weighted standard deviation allows us to apply a weight or relative importance to each resource.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
This has been discussed and proposed before, but we agree the *weight* is not necessary for this plugin. 
https://docs.google.com/document/d/1MT0KVnyeAc4QcKqUsmk-4OvmBhOy6PvBQOGnjugrJ9k/edit#heading=h.7mktt8dyxg66

**Comment by alculquicondor** [comment]
Right... this is about "balance", so not really ok to give more weight to one resource. Do you have any extra justification?

**Comment by JoeyValentine** [comment]
From "Wei Huang et al. An Energy Efficient Virtual Machine Placement Algorithm with Balanced Resource Utilization",
> One efficient way to cut down the energy consumption is to reduce the number of running PMs. As different VMs require different kinds and amounts of resources (e.g., CPU, memory, disk, bandwidth, etc.), when placing VMs on PMs to meet such requirements, a PM cannot host any more VM as long as an arbitrary dimensional resource is exhausted even when all other dimensional resources are sufficient, a phenomenon well-known as bucket effects. Thus, in those fully loaded PMs, all the unutilized resources, referred to as resource fragments, are wasted. So in order to improve the resource utilization such that the number of running PMs is minimized, we have to lower down the number of resource fragments and decrease their sizes as well.
  
BalancedResourceAllocation is an algorithm that uses multiple resources evenly to prevent a situation in which new pods cannot be deployed (bucket effects) even if other resources are sufficient due to the exhaustion of a specific resource. However, the above paper assumes that each resource can be depleted at the same rate. If a resource is less likely to be depleted before others, that resource will contribute less to the bucket effect and may be less balanced than others.  
  
If we balance all our resources to the same level, we will have the same problem as the example below. In this example, let’s assume that pods placed on a node show a resource usage pattern in which CPU and memory saturate before network bandwidth. (Different workloads will have different patterns of resource usage)
  
<p align="center">
  
</p>

<p align="center">
  
</p>

In the above example, CPU and memory usage are similar in node1. In the case of Node2, the difference between CPU and memory usage is larger than that of node1, but the standard deviation value is lower than that of node1. Therefore, if we give the same weight value, BalancedResourceAllocation will place the pod on node2. However, placing that pod on node2 will cause bucket effects because there is a high probability that CPU resources will be exhausted first. There is a high probability that the bucket effect will occur in Node2, but there is no difference between σ_node1 and σ_node2 values, indicating that a standard deviation is inappropriate to be used as a scheduling metric. In other words, the higher the probability that the bucket effect occurs after placing pods on a node, the higher the standard deviation value should be.
  
In the same example, if the weighted standard deviation is calculated by assigning an appropriate weight to each resource, the following result can be obtained.

<p align="center">
  
</p>

By assigning a low weight to a resource that is less likely to be exhausted, and assigning a high weight to a resource that is likely to be exhausted first, the bucket effect can be prevented more effectively. The weight should be set appropriately according to the amount of resources(the number of CPUs, the amount of memory, network bandwidth, etc.) and the resource usage patterns of the pods.

**Comment by alculquicondor** [comment]
cc @Huang-Wei

**Comment by alculquicondor** [comment]
Why not just consider CPU and memory alone in your example?

I just find that the semantics of weight when talking about balance are not very intuitive. But if you absolutely need the feature, I'm not fully opposed, as long as the documentation is clear. And perhaps we can label it "advanced", as most people don't actually need to tweak it and a bad configuration could lead to bad cluster utilization.

**Comment by alculquicondor** [comment]
FYI https://github.com/kubernetes/kubernetes/blob/3aa10a51f5bf04cd5039af466ecb9f663164f262/pkg/scheduler/apis/config/validation/validation_pluginargs.go#L255

**Comment by dims** [comment]
@JoeyValentine did you get a chance to look at the last few comments from @alculquicondor ?

**Pull request closed without merging**
