### PR TITLE
Bump cloud.google.com/go

### PR DESCRIPTION
**Pull request by lucacome**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Ran `./hack/pin-dependency.sh cloud.google.com/go v0.108.0` which replaced `cloud.google.com/go` with `cloud.google.com/go/compute` and `cloud.google.com/go/compute/metadata`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
we can't land this now... see https://github.com/kubernetes/kubernetes/issues/113366 and related PRs/Issues.

cc @liggitt

**Comment by liggitt** [comment]
(just out of curiosity for how that job would see this change)

**Comment by liggitt** [comment]
Yeah, total dependencies go from 285 to 387… oof

**Comment by lucacome** [comment]
Seems like `golang.org/x/oauth2` to `v0.4.0` makes it a little bit better?

**Pull request closed without merging**
