### PR TITLE
remove test_owners

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Removes `test/test_owners.csv` and associated scripts / files / entries. This is wildly out of date and doesn't seem to be used for anything currently.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Holding for any objections, but I'm +1 on this.

**Comment by BenTheElder** [comment]
flake city. we're failing to reach stage a lot, which I suspect is due to prow thrashing I/O on the nodes :/
/retest

**Comment by spiffxp** [comment]
I don't think we should remove this yet, it's currently used by:

a fejta-bot job:
https://github.com/kubernetes/test-infra/blob/476e246b23e2366a9741006efdc9684bc4edcd54/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml#L280

triage:
https://github.com/kubernetes/test-infra/blob/38069797866a890531b69a95e807c13388a558a5/triage/update_summaries.sh#L72

those should be rewritten to derive ownership some other way if we're going to remove this

**Comment by BenTheElder** [comment]
> those should be rewritten to derive ownership some other way if we're going to remove this

ok, 🤔 

I'll have to look more at what they're doing with it, the user entries at least are approximately useless, and I'm not sure that entire concept is even good.

**Comment by BenTheElder** [comment]
It looks like triage is only using these for the SIGs which is a bit more reasonable and would let us drop that last field.

The issue creator on the other hand is assigning users based on this, which we should probably not do.

**Comment by cblecker** [comment]
This was done in #84070

**Pull request closed without merging**
