### PR TITLE
Proper extension for Virtual Clusters

### PR DESCRIPTION
**Pull request by oleg2oleg**
…cs/getting-started-guides/aws.html#cluster-turnup

### CODE REVIEW

**Comment by oleg2oleg** [comment]
add to whitelist

**Comment by oleg2oleg** [comment]
add to whitelist

**Comment by justinsb** [comment]
I'm sorry @oleg2oleg - I don't really understand what you're trying to do here.

I think if you want to set your instances up with a random suffix, you can set KUBE_AWS_INSTANCE_PREFIX  to whatever you want before calling kube-up.

Does that achieve what you're trying to do?

**Comment by justinsb** [comment]
Haven't heard anything on this for a long time; going to close.  Feel free to reopen if you still want it!

**Pull request closed without merging**
