### PR TITLE
fix aws loadbalancer nodePort cannot change issue

### PR DESCRIPTION
**Pull request by M00nF1sh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind bug

**What this PR does / why we need it**:
Fix a bug to handle cases when operators manually change nodePort for existing servicePort within service after service creation.

Regression introduced by https://github.com/kubernetes/kubernetes/pull/74910/commits/1d6fe8c6c2cf3b9db4ac37b5a9eaded616075636

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Existing targetGroups won't be changed since we match targetGroups by nodePort on existing listeners. only new targetGroup created will have this new name.
Test done:
* create 1.15 cluster
* create NLB service
* upgrade 1.15 cluster to use new KCM built with change
* verify NLB service's targetGroup didn't change
* modify NLB service's annotation
* verify NLB service's targetGroup didn't change
* change service's nodePort
* verify NLB service's created new targetGroup

**Does this PR introduce a user-facing change?**:

```release-note
Bug fix for AWS NLB service when nodePort for existing servicePort changed manually.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by erismaster** [comment]
Hi thanks for this. Commenting for increased visibility as we are impacted by this bug.

**Comment by M00nF1sh** [comment]
@erismaster Just curious, what's your use case of change nodePort for a existing servicePort without modify the servicePort itself :D

**Comment by erismaster** [comment]
@M00nF1sh its behavior from https://github.com/banzaicloud/kafka-operator.

**Review by micahhausler — APPROVED** [review]
/LGTM
/approve

Thanks for the tests!

**Pull request merged**
