### PR TITLE
[release-1.28][go1.23] hack: bump go-tools and exclude SA1006

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Backporting https://github.com/kubernetes/kubernetes/pull/126709 and https://github.com/kubernetes/kubernetes/pull/125926

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig architecture testing
/assign @dims @liggitt

### CODE REVIEW

**Comment by dims** [comment]
@MadhavJivrajani legit failure in CI job?

**Comment by saschagrunert** [comment]
v1.28 is EOL, closing

**Pull request closed without merging**
