### PR TITLE
apimachinery e2e: stop usage of gomega.BeTrue/False

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

see https://github.com/kubernetes/kubernetes/pull/122416

#### Which issue(s) this PR fixes:

Related-To: https://github.com/kubernetes/kubernetes/issues/105678

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SD-13** [comment]
Hi @carlory there is already an effort going on here https://github.com/kubernetes/kubernetes/pull/121888. I was inactive for a while, but planning to finish this up soon.

**Comment by carlory** [comment]
sorry, I didn't see it. thanks for you contribution. please go ahead. I'll close this. @SD-13

**Comment by SD-13** [comment]
@carlory No problem :)

**Pull request closed without merging**
