### PR TITLE
Automated cherry pick of #78999: ipvs: fix string check for IPVS protocol during graceful

### PR DESCRIPTION
**Pull request by andrewsykim**
Cherry pick of #78999 on release-1.15.

#78999: ipvs: fix string check for IPVS protocol during graceful

### CODE REVIEW

**Comment by andrewsykim** [comment]
/hold 

Pending approval for https://github.com/kubernetes/kubernetes/pull/78999

**Comment by tpepper** [comment]
/kind bug
/priority critical-urgent
@kubernetes/patch-release-team

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
