### PR TITLE
Add missing RBAC permissions to the sample-apiserver

### LINKED ISSUE #125942: sample-apiserver lacks RBAC permissions
### What happened?

Deployed sample-apiserver into a kind cluster following the instructions in https://github.com/kubernetes/sample-apiserver/blob/master/README.md. 

Checked wardle-server pod logs, found the following error:
```
$ k logs wardle-server-5669dcc765-nxkdt -n wardle | grep -i unhandled
Defaulted container "wardle-server" out of: wardle-server, etcd
E0707 20:25:33.179224       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.0.0-20240707023231-354ed1bc9f1f/tools/cache/reflector.go:243: Failed to watch *v1.ValidatingAdmissionPolicyBinding: failed to list *v1.ValidatingAdmissionPolicyBinding: validatingadmissionpolicybindings.admissionregistration.k8s.io is forbidden: User \"system:serviceaccount:wardle:apiserver\" cannot list resource \"validatingadmissionpolicybindings\" in API group \"admissionregistration.k8s.io\" at the cluster scope"
E0707 20:25:33.179839       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.0.0-20240707023231-354ed1bc9f1f/tools/cache/reflector.go:243: Failed to watch *v1.ValidatingAdmissionPolicy: failed to list *v1.ValidatingAdmissionPolicy: validatingadmissionpolicies.admissionregistration.k8s.io is forbidden: User \"system:serviceaccount:wardle:apiserver\" cannot list resource \"validatingadmissionpolicies\" in API group \"admissionregistration.k8s.io\" at the cluster scope"
...
```

### What did you expect to happen?

No such errors. 

### How can we reproduce it (as minimally and precisely as possible)?

Deployed sample-apiserver into a kind cluster following the instructions in https://github.com/kubernetes/sample-apiserver/blob/master/README.md. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
```

</details>

### Cloud provider

KIND

### PR DESCRIPTION
**Pull request by fxierh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Add missing RBAC permissions to the sample-apiserver. 

#### Which issue(s) this PR fixes:

Fixes #125942

### CODE REVIEW

**Review by pacoxu — COMMENTED** [review]
/lgtm
/ok-to-test 
/cc @xmudrii @Jefftree
/assign @sttts

**Comment by Jefftree** [comment]
LGTM

Thanks!

**Pull request merged**
