### PR TITLE
Partial cherrypick of #71058

### PR DESCRIPTION
**Pull request by verult**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Cherry picks #71058 to 1.12
Fixes https://github.com/kubernetes-csi/external-attacher/issues/126

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig storage
/assign @davidz627 @msau42

### CODE REVIEW

**Comment by davidz627** [comment]
LGTM please fix BUILD, tests, interface (if need be)

**Comment by davidz627** [comment]
/assign @saad-ali 
for approval

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
