### PR TITLE
Change gce cloud provider

### PR DESCRIPTION
**Pull request by bowei**
Changes the GCE cloud provider code to point to the vendored generated code.
This makes it easier to separate out the guts of the implementation of the cloud
provider from the shim that is used to connect the cloud provider with k8s.

NOTE: there are no logic changes, this simply takes the generate code and points it
at the external source.

```release-note
NONE
```

### CODE REVIEW

**Comment by rramkumar1** [comment]
/lgtm
assign @cblecker

**Review by cheftako — APPROVED** [review]
/lgtm

**Comment by freehan** [comment]
`hack/verify-godeps.sh` failed.

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
