### PR TITLE
updated kubernetes daemon man docs

### PR DESCRIPTION
**Pull request by mikedanese**
These man pages are not autogenerated. They are generated from specially formatted
markdown files that need to be updated when flags are changed but nobody knows
about this so it is not enforced. Thus the man page generation is not useful.
For the sake of having up to date docs up to date for v1, I am manually updating
the markdown files and removing the md2man generation (because it doesn't work
with the format I'm updating them to). After v1 we need to gen this man pages with 
the rest of our generated docs in a pre-commit hook so that they are not able to become 
out of date. We can do this by converting our daemons to use cobra cmd like kubectl, or
better, using config objects (from files or etcd) instead of command line opts.

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM
cc @eparis

**Comment by bgrant0607** [comment]
doc change

**Comment by eparis** [comment]
so maybe no man page is better than a bad man page, but why is it so hard to gen the 'right' .md ?

**Comment by mikedanese** [comment]
It was what I could do in 10 minutes with sed. I'm following this up with a PR that will gen this md and the man pages.

**Pull request merged**
