### PR TITLE
update for APIs removed in 1.25

### PR DESCRIPTION
**Pull request by deads2k**
Now updated for a state that is possible to merge. I'll likely pick the test-cmd solution from the PSP admission removal.

/kind cleanup

```release-note
ACTION REQUIRED: Deprecated beta APIs scheduled for removal in 1.25 are no longer served. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25 for more information. 
```

### CODE REVIEW

**Comment by deads2k** [comment]
huh, must have done that wrong.

**Comment by deads2k** [comment]
/hold

need to continue investigation on gce-100-performance

**Comment by deads2k** [comment]
integration looked like infra

/retest

**Comment by deads2k** [comment]
looking at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108797/pull-kubernetes-e2e-gce-100-performance/1524004985635868672, then kube-addon-manager.log from https://gcsweb.k8s.io/gcs/sig-scalability-logs/pull-kubernetes-e2e-gce-100-performance/1524004985635868672/e2e-108797-95a39-master/, I see

> error: no matches for kind "CronJob" in version "batch/v1beta1"

For this job, does someone know where we can find the manifests feeding the kube-addon-manager for gce 100?

**Comment by liggitt** [comment]
[has a build of the addon manager image been done since 1619e8eb953042facabc448bf6cbc67eeb46d5cc merged?](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L232)

**Comment by liggitt** [comment]
also not sure if https://github.com/kubernetes-sigs/cluster-addons/blob/master/bootstrap/app/addon-manager.go#L73 is active but that list is stale

**Comment by deads2k** [comment]
passed on the 100 test

/hold cancel

**Comment by liggitt** [comment]
lgtm... there's a bunch of "remove in 1.25" comments on `legacyBetaEnabledByDefaultResources`... remove those as part of this or in a follow up?

**Comment by deads2k** [comment]
> lgtm... there's a bunch of "remove in 1.25" comments on `legacyBetaEnabledByDefaultResources`... remove those as part of this or in a follow up?

followup.  Let's get these unserved first

**Comment by deads2k** [comment]
> Init container clonerefs not ready: (state: waiting, reason: "PodInitializing", message: "") Init container initupload not ready: (state: waiting, reason: "PodInitializing", message: "") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")

is an infra issue, not a test issue

/retest

**Comment by uablrek** [comment]
This PR breaks functionality for `calico/cni:v3.22.1` which works in K8s v1.24.0. Calico 3.23.0 works according to the [PR above](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2297). While I am aware that this is not a bug, IMHO you should include a warning in the release notes (not "NONE"), unless that is done elsewhere of course.

**Comment by liggitt** [comment]
Deprecations are noted in release notes, in docs at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25, and every use of a deprecated API returns a warning header in the API response (https://kubernetes.io/blog/2020/09/03/warnings/#deprecation-warnings)

I'm happy to update the comment in this PR as well.

**Pull request merged**
