### PR TITLE
remove resource flowschemas and prioritylevelconfigurations from legacyBetaEnabledByDefaultResources in v1.29

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?

/kind cleanup
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note-action-required
The `flowcontrol.apiserver.k8s.io/v1beta2` API version of `FlowSchema` and `PriorityLevelConfiguration` is no longer served in v1.29. Migrate manifests and API clients to use the `flowcontrol.apiserver.k8s.io/v1beta3` API version, available since v1.26. More information is at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#flowcontrol-resources-v129
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
It might be better if the title were a little more specific, this PR is not doing all of what the title says (as indeed it should not).

**Comment by bzsuni** [comment]
> It might be better if the title were a little more specific, this PR is not doing all of what the title says (as indeed it should not).

yes, thanks for your comment. I have modified according to your comment

**Review by liggitt — COMMENTED** [review]
one comment on the test, and I updated the release note to be more helpful to users

/ok-to-test

**Comment by liggitt** [comment]
```
=== FAIL: pkg/controlplane TestStorageVersionHashes (0.67s)
```

unit test failure is due to this PR

**Comment by bzsuni** [comment]
I have made the modification, can you take the time to help rereview?Thanks a lot 
@liggitt

**Pull request merged**
