### PR TITLE
[DO NOT MERGE] [TEST ONLY]

### LINKED ISSUE #167: quick and multiple Ctrl+C interrupt for kubectl logs -f cause konnectivity-agent stuck
Hi team,

I met a strange issue in our product that when I use `kubectl logs -f konnectivity-agent-xxx` to streaming logs, because there are many logs there, I did not wait it to finish and use `Ctrl+C` to interrupt the streaming, since it did not exit immediately like cat big file, I issued `Ctrl+C` at least 3 times as quick as I can. Then the streaming process exit, but konnectivity got stuck. This looks like a random behavior, but after several experiments, it actually can be reproduced in any of my setups.

konnectivity server/client version: v0.0.12
setup: one proxy-server on k8s master vm and one proxy-agent run as pod(one replica deployment).

The logs when `Ctrl+C` issued:
server:
```
I0121 06:53:12.616717       7 server.go:224] proxy request from client, userAgent [grpc-go/1.27.0]
I0121 06:53:12.616941       7 server.go:257] start serving frontend stream
I0121 06:53:12.617098       7 server.go:268] >>> Received DIAL_REQ
I0121 06:53:12.617118       7 backend_manager.go:170] pick agentID=a89e1d16-8908-4f83-bbc1-bea45ba34ea4 as backend
I0121 06:53:12.617168       7 server.go:290] >>> DIAL_REQ sent to backend
I0121 06:53:12.740584       7 server.go:308] >>> Received 24 bytes of DATA(id=195)
I0121 06:53:12.740750       7 server.go:324] >>> DATA sent to Backend
I0121 06:53:12.740818       7 server.go:294] >>> Received CLOSE_REQ(id=195)
I0121 06:53:12.740842       7 server.go:303] >>> CLOSE_REQ sent to backend
I0121 06:53:13.353224       7 server.go:308] >>> Received 24 bytes of DATA(id=194)
I0121 06:53:13.353335       7 server.go:324] >>> DATA sent to Backend
I0121 06:53:13.353347       7 server.go:294] >>> Received CLOSE_REQ(id=194)
I0121 06:53:13.353357       7 server.go:303] >>> CLOSE_REQ sent to backend
I0121 06:53:13.405226       7 server.go:308] >>> Received 24 bytes of DATA(id=189)
I0121 06:53:13.405460       7 server.go:324] >>> DATA sent to Backend
I0121 06:53:13.405484       7 server.go:294] >>> Received CLOSE_REQ(id=189)
I0121 06:53:13.405546       7 server.go:303] >>> CLOSE_REQ sent to backend
I0121 06:53:14.735760       7 server.go:308] >>> Received 24 bytes of DATA(id=192)
I0121 06:53:14.735980       7 server.go:324] >>> DATA sent to Backend
I0121 06:53:14.736004       7 server.go:294] >>> Received CLOSE_REQ(id=192)
I0121 06:53:14.736054       7 server.go:303] >>> CLOSE_REQ sent to backend
I0121 06:53:17.537537       7 server.go:224] proxy request from client, userAgent [grpc-go/1.27.0]
I0121 06:53:17.537740       7 server.go:257] start serving frontend stream
I0121 06:53:17.537861       7 server.go:268] >>> Received DIAL_REQ
I0121 06:53:17.538072       7 backend_manager.go:170] pick agentID=a89e1d16-8908-4f83-bbc1-bea45ba34ea4 as backend
I0121 06:53:17.538320       7 server.go:290] >>> DIAL_REQ sent to backend
```
client:
```
I0121 06:53:12.619855       1 client.go:280] received DIAL_REQ
I0121 06:53:12.680382       1 client.go:271] [tracing] recv packet, type: DIAL_REQ
I0121 06:53:12.680413       1 client.go:280] received DIAL_REQ
I0121 06:53:12.743029       1 client.go:271] [tracing] recv packet, type: DATA
I0121 06:53:12.743058       1 client.go:339] received DATA(id=195)
I0121 06:53:12.743077       1 client.go:271] [tracing] recv packet, type: CLOSE_REQ
I0121 06:53:12.743083       1 client.go:350] received CLOSE_REQ(id=195)
I0121 06:53:12.743088       1 client.go:306] close connection(id=195)
E0121 06:53:12.743274       1 client.go:419] conn write error: write tcp 192.168.113.19:52218->192.168.113.18:10349: use of closed network connection
I0121 06:53:12.743986       1 client.go:384] received 0 bytes from remote for connID[195]
W0121 06:53:12.744018       1 client.go:391] connection read error: read tcp 192.168.113.19:52218->192.168.113.18:10349: use of closed network connection
I0121 06:53:13.355882       1 client.go:271] [tracing] recv packet, type: DATA
I0121 06:53:13.355966       1 client.go:339] received DATA(id=194)
I0121 06:53:13.355997       1 client.go:271] [tracing] recv packet, type: CLOSE_REQ
I0121 06:53:13.356005       1 client.go:350] received CLOSE_REQ(id=194)
I0121 06:53:13.356011       1 client.go:306] close connection(id=194)
I0121 06:53:13.356206       1 client.go:384] received 0 bytes from remote for connID[194]
W0121 06:53:13.356218       1 client.go:391] connection read error: read tcp 192.168.113.19:52216->192.168.113.18:10349: use of closed network connection
E0121 06:53:13.356451       1 client.go:419] conn write error: write tcp 192.168.113.19:52216->192.168.113.18:10349: use of closed network connection
I0121 06:53:13.408583       1 client.go:271] [tracing] recv packet, type: DATA
I0121 06:53:13.408690       1 client.go:339] received DATA(id=189)
I0121 06:53:13.408809       1 client.go:271] [tracing] recv packet, type: CLOSE_REQ
I0121 06:53:13.408885       1 client.go:350] received CLOSE_REQ(id=189)
I0121 06:53:13.409302       1 client.go:306] close connection(id=189)
I0121 06:53:13.409049       1 client.go:413] [connID: 189] write last 24 data to remote
I0121 06:53:13.409572       1 client.go:384] received 0 bytes from remote for connID[189]
W0121 06:53:13.409620       1 client.go:391] connection read error: read tcp 192.168.113.19:52194->192.168.113.18:10349: use of closed network connection
I0121 06:53:14.738572       1 client.go:271] [tracing] recv packet, type: DATA
I0121 06:53:14.738614       1 client.go:339] received DATA(id=192)
I0121 06:53:14.738659       1 client.go:271] [tracing] recv packet, type: CLOSE_REQ
I0121 06:53:14.738665       1 client.go:350] received CLOSE_REQ(id=192)
I0121 06:53:14.738864       1 client.go:306] close connection(id=192)
I0121 06:53:14.739285       1 client.go:384] received 0 bytes from remote for connID[192]
W0121 06:53:14.739373       1 client.go:391] connection read error: read tcp 192.168.113.19:52212->192.168.113.18:10349: use of closed network connection
E0121 06:53:14.739612       1 client.go:419] conn write error: write tcp 192.168.113.19:52212->192.168.113.18:10349: use of closed network connection
I0121 06:53:17.541034       1 client.go:271] [tracing] recv packet, type: DIAL_REQ
I0121 06:53:17.541071       1 client.go:280] received DIAL_REQ
I0121 06:53:17.577462       1 client.go:271] [tracing] recv packet, type: DIAL_REQ
I0121 06:53:17.577503       1 client.go:280] received DIAL_REQ
I0121 06:53:17.890636       1 client.go:271] [tracing] recv packet, type: DIAL_REQ
...
...
```
After client side got stuck, it just print above last 2 lines of logs continuously. I could see there are 4 CLOSE_REQ (195,194,189,192) send through server to client, which looks like just my actions. I am not sure if this is helpful, but anyway the service 192.168.113.18:10349 is Antrea controller, we are using Antrea as CNI.

### PR DESCRIPTION
**Pull request by caesarxuchao**
This is to test if it fixes the flaky *-kubernetes-e2e-gci-gce-network-proxy-grpc test suite.

Trying to fix https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/167.

Real fix was merged as https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/218.

/sig api-machinery
/kind bug
cc @jkh52 @cheftako

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Added more unblocking code.

Also shortened the timeout to 10s.

Let's see if that makes tests more happier.

/test pull-kubernetes-e2e-gce-network-proxy-grpc

**Comment by Jefftree** [comment]
/test pull-kubernetes-e2e-gce-network-proxy-http-connect

Just to confirm that there is no regression in http-connect

**Comment by caesarxuchao** [comment]
We got 1 [green](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-network-proxy-grpc/1395798800085291008) and 1 [red](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102192/pull-kubernetes-e2e-gce-network-proxy-grpc/1395959913284374528/) run so far.

/test pull-kubernetes-e2e-gce-network-proxy-grpc

**Pull request closed without merging**
