### PR TITLE
Upgrade container-storage-interface/spec dependency to v0.3.0

### PR DESCRIPTION
**Pull request by davidz627**
Also updated golang/protobuf to v1.1.0 to satisfy hard requirement of new CSI Spec version

/sig storage
/kind enhancement
/assign @saad-ali

```release-note
Updated Container Storage Interface specification version to v0.3.0
```

### CODE REVIEW

**Comment by cblecker** [comment]
I can approve for the Godep bump, but I need sig-storage to LGTM this first.

**Comment by saad-ali** [comment]
/test pull-kubernetes-e2e-kops-aws
--

**Pull request merged**
