### PR TITLE
remove the support for in-tree volume plugin cephfs

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup
/kind api-change
/kind deprecation

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/118143 deprecated the CephFS plugin in 1.28. In 1.31, we want to remove the support.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED:

CephFS volume plugin ( `kubernetes.io/cephfs`) was removed in this release and the `cephfs` volume type became non-functional. Alternative is to use CephFS CSI driver (https://github.com/ceph/ceph-csi/) in your Kubernetes Cluster. A re-deployment of your application is required to use the new driver if you were using `kubernetes.io/cephfs` volume plugin before upgrading cluster version to 1.31+.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by humblec** [comment]
Adding to the review queue.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
