### PR TITLE
style: correct the sentence

### PR DESCRIPTION
**Pull request by luckymrwang**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

The modal verb 'would' requires the verb's base form.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by luckymrwang** [comment]
@alculquicondor  Hi, how to fix CI `pull-kubernetes-e2e-autoscaling-hpa-cm` failed?

**Comment by alculquicondor** [comment]
The flakiness is reported here: https://github.com/kubernetes/kubernetes/issues/116315

You still need an approver for this PR, though.

**Comment by pbetkier** [comment]
I've flakiness fixed, now need approve from one of the approvers.

**Comment by luckymrwang** [comment]
@alculquicondor @mwielgus please review it.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
