### PR TITLE
fix kubectl apply annotation error

### LINKED ISSUE #378: kubectl reject annotation information without any warning
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
/kind bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
If we use `k create -f <file name> --save-config=true` or `kubectl apply <file name>`, and this file have annotations with type not `map[string]string`, then kubectl will quietly reject those annotations.

For example, you have a yaml described object wich annotation is: 
```yaml
metadata:
  name: test
  annotations:
    a: haha
    b: 1
```
We can see `b: 1` is not a correct annotation type. Then you use `kubectl apply` or `kubectl create --save-config` create this object, you will get an object with annotations like:
```yaml
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"default"}}
```

And if you already have this object with annotations, after the `kubectl apply` command, the annotation will be cleared.

**What you expected to happen**:
In this case, kubectl should error out, with an err `invalid annotation` or something else.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a file with content like:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  annotations:
    a: haha
    b: 1
```
2. Use `k create -f <file name> --save-config=true` or `kubectl apply <file name>` to create this object.
3. Check the new created object annotations.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:
When use `kubectl apply -f` with annotations not a type `map[string]string`. Kubectl will deprecate those annotations, with out any hind or warning.
This bug also happened in ` k create -f --save-config`
This pr is to identify this case and error out.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubectl#378 #61509

**Special notes for your reviewer**:
After this got merged, in the described case, kubectl will error out with information:
```
# k apply -f conf.yml
error: error when retrieving modified configuration from:
Resource: "configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "test", Namespace: "default"
Object: &{map["kind":"ConfigMap" "metadata":map["namespace":"default" "annotations":map["a":"haha" "b":'\x01'] "name":"test"] "apiVersion":"v1"]}
for: "conf.yml": .metadata.annotations accessor error: contains non-string key in the map: 1 is of the type int64, expected string
```

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mengqiy** [comment]
This fix works for annotation. But it doesn't fix all `map[string]string` types, e.g. if I have a label `ver: 123`, if it won't work.
We may need a better approach that works for all `map[string]string` types.

**Comment by apelisse** [comment]
> This fix works for annotation. But it doesn't fix all map[string]string types, [snip]

We don't have to fix them all. It's just that reading the annotations to add the `last-applied` field fail silently. Later in the process we run the validation (based on openapi schema) against everything (and this would fail).

**Comment by soltysh** [comment]
This is changing the behavior of apply command. Since we're currently working on moving that functionality over to the server I'm against merging this fix.
/hold

**Comment by Lion-Wei** [comment]
@soltysh You mean this issue: kubernetes/kubernetes#61471? That sounds grate, but is the `CreateOrUpdateAnnotation` also need be moved to the server? Cause I think this work should in `apply` part, pass a single `LastAppliedConfigAnnotation` to the server is little confusing.

**Comment by soltysh** [comment]
@Lion-Wei I'm talking about this effort https://groups.google.com/forum/#!topic/kubernetes-dev/_A3l8NgKKAw

**Pull request closed without merging**
