### PR TITLE
Switch from obsolete "github.com/scalingdata/gcfg" to "gopkg.in/gcfg.v1"

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by onlyjob** [comment]
I'm not going to sign CLA just yet, sorry. This commit is not copyright-able as it contains zero intellectual property -- I merely switch dependency without introducing even a line of meaningful code. Please apply at you discretion.

**Comment by thockin** [comment]
Before we can look at this, it needs to pass CI - it's currently failing because gofmt was not run.

**Comment by thockin** [comment]
Change overall looks OK.  Please ping this when it passes CI

**Comment by onlyjob** [comment]
@thockin, could you have a look please? I run `gofmt` but now CI fails for the different reason that I do not understand. Thanks.

**Comment by onlyjob** [comment]
@thockin? Ping?

**Comment by eparis** [comment]
You will see that CI is still failing (click the link next to the failed check). How did you update Godeps.json ? By hand? That link shows you the patch of what is wrong between saving the godeps fresh and what your tree looks like.

**Comment by eparis** [comment]
ok to test

**Comment by onlyjob** [comment]
Sorry but I don't understand the problem or how to fix it. Yes I updated `Godeps.json` by hand (how else?); its syntax is valid and the only problem apparently is that your CI system wants to reorder some lines in this file? How am I suppose to fix that?!? By trying to match my commit with diff output? Or should I run something like `gofmt`? Any specifics?

Please take it off my hands, apply it yourself, drop my name from it I don't care as long as this patch is applied in this form or another. I have no time to fiddle with CI quirks. :(

**Comment by thockin** [comment]
try a rebase?

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by eparis** [comment]
@alex-mohr just to be difficult/unpredictable you can't preface the message with "k8s-bot" only put:
ok to test

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
@onlyjob do you want to finish this, or should we close it and redo ourselves?

**Comment by onlyjob** [comment]
I'd appreciate if you could take care of that if you could. This commit is trivial yet there were no progress even after 4 months. I hope you'll have better luck with moving it forward. Thanks.

**Comment by thockin** [comment]
ok, thanks for your effort.

**Pull request closed without merging**
