### PR TITLE
Removing network_policy.go test file

### LINKED ISSUE #97920: Cleanup the networkpolicy tests folder
**What would you like to be added**:
Remove the `test/e2e/networking/networkpolicy` folder in favor of `test/e2e/networking/netpol`.

**Why is this needed**:
With the refactoring from the Netpol validation [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1611-network-policy-validation), the tests from `networkpolicy` folder are deprecated and duplicated at this point. 

Action items:

- [x] <strike>Ensure the same coverage of the old netpol tests</strike>
- [x] [Move SCTP](https://github.com/kubernetes/kubernetes/pull/97897) tests
- [x] [Move Netpol API](https://github.com/kubernetes/kubernetes/pull/97898) tests
- [x] [Delete the `test/e2e/networking/networkpolicy` folder](https://github.com/kubernetes/kubernetes/pull/98341)

### PR DESCRIPTION
**Pull request by knabben**
**What type of PR is this?**
/kind cleanup
/area testing
/sig network

**What this PR does / why we need it**:
Removes `test/e2e/networking/network_policy.go` file in favor of tests migrated to the `test/e2e/networking/netpol` folder.

**Which issue(s) this PR fixes**:
Fixes #97920

**Special notes for your reviewer**:
Wait for https://github.com/kubernetes/kubernetes/pull/97898 get merged.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
build conflict...

**Comment by knabben** [comment]
@bowei, could you PTAL, just rebased again

**Pull request merged**
