### PR TITLE
Moving trace from apiserver to client-go

### PR DESCRIPTION
**Pull request by krzysied**
Moving trace from `staging/src/k8s.io/apiserver/pkg/util/trace` to `staging/src/k8s.io/client-go/util/trace`.

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes client-go dependency to apiserver
https://github.com/kubernetes/kubernetes/pull/73071#issuecomment-456586265

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
This broke publishing. Please either get this in as soon as possible or revert the old change.

**Comment by wojtek-t** [comment]
@krzysied - please squash commits

/assign @sttts @liggitt 
@sttts @liggitt I think that's the right way to fix it, though I'm leaving the decision to you.

**Comment by nikhita** [comment]
Looks like this just needs a `hack/update-staging.sh` run.

**Comment by nikhita** [comment]
+1 for k8s.io/utils.

IMO if it is going to take time to move to k8s.io/utils, we should revert the PR to unblock publishing.

**Comment by wojtek-t** [comment]
+1 for reverting if we don't have full consensus.

> i agree we should move it to k8s.io/utils i don't like either client depending on apiserver or the other way around unnecessarily

apiserver already depends on client-go - I don't fully understand this argument...
Can someone explain this to me?

**Comment by nikhita** [comment]
> apiserver already depends on client-go - I don't fully understand this argument...

I think the idea is mainly that `trace` is a utility package and doesn't depend on other kube dependencies so it seems like a good candidate for `k8s.io/utils`.

:+1: that apiserver already depends on client-go -- though in general, wherever possible it'd be nice to avoid adding packages that add _more_ dependencies between staging repos. :grimacing:

**Comment by dims** [comment]
@wojtek-t `unnecessarily` if there are other things that's fine, we don't want to add more. yes what @nikhita said :)

**Comment by wojtek-t** [comment]
I created https://github.com/kubernetes/kubernetes/pull/73217 for the revert to unblock stuff.

> +1 that apiserver already depends on client-go -- though in general, wherever possible it'd be nice to avoid adding packages that add more dependencies between staging repos. grimacing

Moving it to k8s.io/util would mean that we will introduce a new dependency on k8s.io/util in couple different repos (client, apiserver). I'm not very convinced that it's visibly better (I would agree if we would already have that dependency, but since we don't have it, it's not that clear to me).

**Comment by nikhita** [comment]
> Moving it to k8s.io/util would mean that we will introduce a new dependency on k8s.io/util in couple different repos (client, apiserver). 

I'm confused....trace doesn't depend on client-go or apiserver, right? How would k8s.io/util depend on them? Maybe I'm missing something here.

**Comment by wojtek-t** [comment]
> I'm confused....trace doesn't depend on client-go or apiserver, right? How would k8s.io/util depend on them? Maybe I'm missing something here.

Sorry, I wasn't clear.
Yes - trace doesn't depend on anything pretty much :-)
But currently neither client-go nor apiserver don't depend on k8s.io/util. Once we move it there, they will start depend on it.
Does that make more sense now?

**Comment by nikhita** [comment]
>  Does that make more sense now?

Yes :)

I didn't realize they didn't depend on `k8s.io/utils`. Personally, `k8s/utils` feels "intuitive" to me since its a utility package and doesn't depend on other kube dependencies...but we should definitely reach consensus from everyone here. :)

I've added a hold on https://github.com/kubernetes/kubernetes/pull/73217 until we do so.

**Comment by dims** [comment]
@wojtek-t would you object to get trace.go into `k8s.io/utils`?

**Comment by wojtek-t** [comment]
> @wojtek-t would you object to get trace.go into k8s.io/utils?

It's not that I'm objecting. I just want to understand why this is really better than moving to client-go.
For now I'm not really convinced, because we would introduce a brand new dependency that we don't have at all (vs adding it to client-go, which all other repositories that would need trace already depend on).

I guess what I'm saying is that in client-go there is already a couple different things in util/ directory, that may easily be moved to k8s.io/util too.
Just to name two most simple examples:
util/buffer and util/integer - those aren't client-specific at all.
So I personally would recommend:
1. put the trace to util/trace in client-go for now (that won't introduce a new dependency)
2. if we decide that that introducing dependency on k8s.io/util is not a big deal and we agree that it's the right way to do (which is probably true), move not just this one, but a bunch of stuff in one shot

Thoughts?

**Comment by sttts** [comment]
> It's not that I'm objecting. I just want to understand why this is really better than moving to client-go.
> For now I'm not really convinced, because we would introduce a brand new dependency that we don't have at all (vs adding it to client-go, which all other repositories that would need trace already depend on).

I don't see what is client specific in klog tracing of long operations. I could see it in k8s.io/utils or even in klog itself.

**Comment by dims** [comment]
@wojtek-t that's fair. i'll move `util/buffer`and `util/integer` and `util/trace` over to that repo

**Comment by wojtek-t** [comment]
> @wojtek-t that's fair. i'll move util/bufferand util/integer and util/trace over to that repo

Thanks a lot @dims !
Apparently, this has already happened. So this PR no longer makes any sense.
Closing this one.

**Pull request closed without merging**
