### PR TITLE
Revert "Add random interval to nodeStatusReport interval every time after an actual node status change

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit d6e17ad808c71a03f1e17ee9728ba4845dd8c1c0.

Introduced unit test flakes, seen in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128190/pull-kubernetes-unit/1854263632594997248

When run with stress / race, that test fails 60% of runs locally

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/approve

@mengqiy plaase re-send your PR with the fixed tests

**Comment by mengqiy** [comment]
Created https://github.com/kubernetes/kubernetes/pull/128636 to fix the flaky test.

**Comment by mengqiy** [comment]
It seems the tests in https://github.com/kubernetes/kubernetes/pull/128636 started a few minutes earlier than the e2e test rerun in this PR.
I wonder if it's easier to merge https://github.com/kubernetes/kubernetes/pull/128636 directly.

/hold

**Comment by mengqiy** [comment]
@SergeyKanzhelev Can you please take a look at this one line PR: https://github.com/kubernetes/kubernetes/pull/128636

**Comment by mengqiy** [comment]
If https://github.com/kubernetes/kubernetes/pull/128636 don't have approved when the e2e test finishes in this PR, please feel free to remove hold and let this PR merge and unblock others.

**Comment by kannon92** [comment]
/hold cancel

We usually avoid fixing forward a test. Since this was causing some flakes, it would be best to add back your PR with your one-line change.

**Comment by mengqiy** [comment]
Fair enough! Thank you!

**Comment by mengqiy** [comment]
>@mengqiy plaase re-send your PR with the fixed tests

Created https://github.com/kubernetes/kubernetes/pull/128640 to attempt this change again with fixed test.

**Pull request merged**
