### PR TITLE
Fix `make release` breaking due to incorrect etcd version

### PR DESCRIPTION
**Pull request by aaronlevy**
`make release` fails with `etcd version 3.0.4 or greater required` when attempting to run integration tests.

Looks like etcd version was bumped in: https://github.com/kubernetes/kubernetes/pull/30508 (also once prior to that as well), but the kube-cross image version was not bumped in `build/build-image/cross/VERSION`

I did a manual check and and it looks like a `gcr.io/google_containers/kube-cross:v1.6.3-3` already exists and it does contain etcd v3.0.4

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32245)

### CODE REVIEW

**Comment by ixdy** [comment]
> I did a manual check and and it looks like a gcr.io/google_containers/kube-cross:v1.6.3-3 already exists and it does contain etcd v3.0.4

That's interesting. Wonder who pushed an updated image without checking it in?

**Comment by ixdy** [comment]
cc @timothysc @wojtek-t 

No idea where the v1.6.3-3 tag came from, but without fully understanding its origin, I'd prefer to skip to -4.

Also, we should probably not be running integration tests inside the cross-build image, but that's a different issue entirely.

**Comment by aaronlevy** [comment]
Should I go ahead changing to `-4`? Then what is the process for getting that image built/pushed?

**Comment by timothysc** [comment]
this is gce/gke tooling so I'm not certain all the touch points on your release process.

**Comment by aaronlevy** [comment]
I'm curious if `make release` is even used? With this fix, I'm still seeing other (unrelated) failures as well.

**Comment by ixdy** [comment]
@aaronlevy we use `make release`

**Comment by ixdy** [comment]
@aaronlevy we use `make release`, but we usually set `KUBE_RELEASE_RUN_TESTS=n`, so we don't run the unit/integration tests inside the cross-build container. (This is why we hadn't noticed this was broken.)

Please bump this to `v1.6.3-4`. I'll push a new image with that version, and then we can merge.

Separately, we should probably stop running tests inside this container.

**Comment by aaronlevy** [comment]
@ixdy bumped

**Comment by ixdy** [comment]
v1.6.3-4 pushed.
@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
@lavalamp is going to push a -5 in #32321.

**Comment by lavalamp** [comment]
I'm going to push a new version anayway for #32321-- closing this so I don't get a rebase conflict :)

**Comment by lavalamp** [comment]
@apelisse @eparis TIL the bot can merge closed PRs...

**Comment by apelisse** [comment]
That's pretty gross ... We should create an issue.

**Comment by lavalamp** [comment]
Yes, but with us or with github support?

**Comment by apelisse** [comment]
Let's do the right thing: both :-)

**Comment by ixdy** [comment]
How does the merge actually happen? Are we using some API on GitHub, or are we just pushing to the upstream branch?

**Comment by lavalamp** [comment]
We are using a github api.

**Comment by foxish** [comment]
Should this be cherrypick-candidate for the 1.4 branch? @lavalamp @ixdy @aaronlevy

**Comment by pwittrock** [comment]
@lavalamp Should this be cherrypicked into 1.4?

**Comment by lavalamp** [comment]
@pwittrock this is superceded by my change so no.

**Comment by lavalamp** [comment]
(though it's harmless if that makes the cherrypick easier)

**Comment by eparis** [comment]
Did we open an issue against the bot? I don't really know if I blame the github API here...

**Pull request merged**
