### PR TITLE
removed the deprecated `azureFile` in-tree storage plugin

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
removed the deprecated `azureFile` in-tree storage plugin

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
removed the deprecated `azureFile` in-tree storage plugin
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
removed the deprecated `azureFile` in-tree storage plugin
```

### CODE REVIEW

**Comment by sftim** [comment]
My suggestion for the changelog:
```markdown
removed the deprecated `azureFile` in-tree storage plugin
```

Do we want to mention CSI drivers here?

**Comment by jsafrane** [comment]
I'll revert this PR tomorrow. @andyzhangx, we need to wait for one more release.

**Comment by andyzhangx** [comment]
this is the reverted PR: https://github.com/kubernetes/kubernetes/pull/118388

**Pull request merged**
