### PR TITLE
Kubelet: Add rkt as a runtime option

### PR DESCRIPTION
**Pull request by vmarmol**
Sadly, as I finished this I realized we need to add built-time labels...so I'm gonna do that :)

/cc @yujuhong @dchen1107 @yifan-gu @jonboulle

### CODE REVIEW

**Comment by vmarmol** [comment]
This is now ready for review, PTAL @yujuhong @dchen1107

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM.

**Comment by yifan-gu** [comment]
LGTM

**Comment by yujuhong** [comment]
Filed a bug for the shippable failure: #7788

**Comment by yujuhong** [comment]
Shippable passed. Merging.

**Comment by zmerlynn** [comment]
I believe this broke the standard GCE-Debian build. Or, at least, this or #7343. I'm rolling this one back first, sorry.

**Comment by vmarmol** [comment]
No problem @zmerlynn! Let us know when the coast is clear and we'll retry. I'd be surprised if this PR is the cause, but there is always a first :)

**Pull request merged**
