### PR TITLE
Add ipvs support of Maglev load distribution method to kube-proxy

### PR DESCRIPTION
**Pull request by sondinht**
#### What type of PR is this?

/kind feature
/sig network
/area ipvs
/area kube-proxy

#### What this PR does / why we need it:

This new load distribution offers a network load balancing method based on hashing the source IP and source port. Unlike the "source hashing" distribution method, the Maglev algorithm keeps the hash table of worker nodes identical regardless of changes in endpoint availability. Because the hash table is consistent across worker nodes, ipvs can keep forwarding connections to the same pods even when the connections fail over from one worker node to another.

None of the existing load distribution methods can retain the endpoint of an existing connection after the connection is re-distributed to another worker node due to the failure of the original worker node.

#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:

The scheduler can be examinated with

```
TCP  192.168.1.4:32000 mh (mh-port)
  -> 11.0.1.3:5001                Masq    1      0          2
  -> 11.0.2.3:5001                Masq    1      0          3
  -> 11.0.3.3:5001                Masq    1      0          4
  -> 11.0.4.3:5001                Masq    1      0          3
TCP  12.0.111.131:7001 mh (mh-port)
  -> 11.0.1.3:5001                Masq    1      0          0
  -> 11.0.2.3:5001                Masq    1      0          0
  -> 11.0.3.3:5001                Masq    1      0          0
  -> 11.0.4.3:5001                Masq    1      0          0
```

#### Does this PR introduce a user-facing change?

In proxy-mode=ipvs the scheduler can be configured in the KubeProxyConfiguration manifest as follows (for instance)

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: "mh"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [Other doc]: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md
```

### CODE REVIEW

**Comment by uablrek** [comment]
> Because the hash table is consistent across worker nodes, ipvs can keep forwarding connections to the same pods even when the connections fail over from one worker node to another.
>
> None of the existing load distribution methods can retain the endpoint of an existing connection after the connection is re-distributed to another worker node due to the failure of the original worker node.

I suppose this similar to the case I have tested in https://github.com/kubernetes/kubernetes/issues/114619#issuecomment-1362617444? The traffic from an external source is for some reason re-directed to another node.

As @mcarbonneaux pointed out in https://github.com/kubernetes/kubernetes/issues/114619#issuecomment-1374977038, this will not work because of masq (SNAT). When traffic enters another node, the source address will be different even if traffic is directed to the same pod as before.

Also there is no coordination between ipvs instances on different nodes. Now it could happen to be that the configs will be the same "by accident" since they get the same data. But I think they will diverge after some re-configs, re-starts, updates, etc, and if so they will not become the same again.

**Comment by uablrek** [comment]
The main reason no one have triaged your PR is because only **issues** are scanned and triaged on the bi-weekly sig/network meetings. A "orphan" PR is very likely to go unnoticed.

The correct way would be to write an issue, like https://github.com/kubernetes/kubernetes/issues/114619 **and** a PR.

**Comment by uablrek** [comment]
The `FlagSourceHash` is a good addition. Thanks for finding it :+1: I suppose some kernel digging was involved.

**Comment by uablrek** [comment]
If it's OK I suggest further discussions about the usage of mh is taken in https://github.com/kubernetes/kubernetes/issues/114619 so we have them in one place.

**Comment by sondinht** [comment]
> If it's OK I suggest further discussions about the usage of mh is taken in #114619 so we have them in one place.

It's fine to have all discussions about the "mh" load distribution in #114619 as the issue is actually discussing about adding all supported ipvs load distribution methods to kube-proxy

**Comment by sondinht** [comment]
> The main reason no one have triaged your PR is because only **issues** are scanned and triaged on the bi-weekly sig/network meetings. A "orphan" PR is very likely to go unnoticed.
> 
> The correct way would be to write an issue, like #114619 **and** a PR.

Thanks for your useful information and tip.

**Comment by sondinht** [comment]
Closing the PR as discussed in the comment https://github.com/kubernetes/kubernetes/issues/114619#issuecomment-1376617860 related to adding support of all ipvs load distribution methods (including "mh") to `kube-proxy`.

Part of this commit will be moved to another PR linked to a separate issue that adds "FlagSourceHash" support to the `mh` and `sh` method after PR #114878 is merged.

**Pull request closed without merging**
