### PR TITLE
Whitelisting *.pkg.dev for the GCP credential provider

### PR DESCRIPTION
**Pull request by Gridasov**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR is whitelisting for GCP credential provider the new *.pkg.dev host pattern.
Also it adds tests for the new and existing patterns.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE 

/cc @lindsayismith @thockin

### CODE REVIEW

**Comment by mikedanese** [comment]
lgtm. Can you squash the commits?

**Comment by Gridasov** [comment]
Thank you! Done

**Comment by Gridasov** [comment]
/test pull-kubernetes-e2e-kind
--

**Pull request merged**
