### PR TITLE
CHANGELOG: Fix release note for snapshot controller update to 3.0.0

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by mysunshine92** [comment]
cc @tpepper

**Pull request merged**
