### PR TITLE
[WIP] Add ability to exclude pods from AlwaysPullImages admission controller

### PR DESCRIPTION
**Pull request by jfchevrette**
**What this PR does / why we need it**:

This adds the ability for a cluster admin using the `AlwaysPullImages` admission controller to allow users to opt-out of the policy by adding an annotation to their pod definitions. This permits a secure default while allowing some flexibility for such times where you may want to prevent having to pull a pod image.

**Which issue(s) this PR fixes**
N/A

**Special notes for your reviewer**:
This is my first PR on the code base itself. I'd appreciate any comments on the code and suggestions on how to improve the PR. I am also unsure if I did the new APIs right - I've mostly copied these from another admission controller that implemented admission plugin configs. 

I'm also unsure about the release notes format. Docs do not suggest any specific format. PTAL.

Updated docs PR at kubernetes/website#10476

**Release note**:
```release-note
- Adds a `enableExcludeAnnotation` configuration option to the `AlwaysPullImages` admission controller.
- Pods can now be opt-out of the `AlwaysPullImages` admission controller, if the cluster admin allows it, by adding the following annotation to their pods: `alwayspullimages.admission.kubernetes.io/exclude: "true"`
```

### CODE REVIEW

**Comment by jfchevrette** [comment]
Updated docs PR at kubernetes/website#10476

**Comment by deads2k** [comment]
/hold

The point of this admission plugin is to ensure that images are always set to be pulled.  There are good policy reasons for this to be uniformly enforced in the cluster.  If you want the invariant enforced in your cluster, wanting to allow people to opt-out seems unlikely.

**Comment by deads2k** [comment]
This goes against the intent of this admission plugin.  A cluster-admin who sets this may as well disable the plugin instead.

/close

**Comment by garagatyi** [comment]
@deads2k even though this addmission was intensionally re-pulling images each time performance still can be improved without making it less secure. I don't understand why can't we add this feature and allow administrator decide whether to enable this performance improvement or not.

**Pull request closed without merging**
