### PR TITLE
Replace fmt.Print with printer in upgrade plan code and fix configVersions are not printed when output is json or yaml

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

```
root@kind-control-plane:/# kubeadm upgrade plan -ojson
[upgrade] Running cluster health checks
I0223 06:41:31.158831    1526 version.go:256] remote version is much newer: v1.29.2; falling back to: stable-1.28
{
    "kind": "UpgradePlan",
    "apiVersion": "output.kubeadm.k8s.io/v1alpha2",
    "components": [
        {
            "name": "kubelet",
            "currentVersion": "1 x v1.28.0",
            "newVersion": "v1.28.7"
        },
        {
            "name": "kube-apiserver",
            "currentVersion": "v1.28.0",
            "newVersion": "v1.28.7"
        },
        {
            "name": "kube-controller-manager",
            "currentVersion": "v1.28.0",
            "newVersion": "v1.28.7"
        },
        {
            "name": "kube-scheduler",
            "currentVersion": "v1.28.0",
            "newVersion": "v1.28.7"
        },
        {
            "name": "kube-proxy",
            "currentVersion": "v1.28.0",
            "newVersion": "v1.28.7"
        },
        {
            "name": "CoreDNS",
            "currentVersion": "v1.10.1",
            "newVersion": "v1.10.1"
        },
        {
            "name": "etcd",
            "currentVersion": "3.5.9-0",
            "newVersion": "3.5.9-0"
        }
    ],
    "configVersions": null
}
root@kind-control-plane:/# kubeadm upgrade plan -ojson | jq .
parse error: Invalid numeric literal at line 1, column 9
^C
```

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubeadm/issues/494

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fix a bug where "kubeadm upgrade plan -o yaml|json" includes unneeded output and was missing component config information.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
CI errors need to be fixed, but LGTM
works locally too.

/triage accepted
/priority backlog
/approve

**Comment by neolit123** [comment]
> Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

you can remove the text under the box, it's not needed for this PR.

**Review by neolit123 — COMMENTED** [review]
/lgtm
to unblock https://github.com/kubernetes/kubernetes/pull/123461

**Comment by sftim** [comment]
Changelog suggestion
```diff
-kubeadm: fix a bug where "kubeadm upgrade plan -o yaml|json" includes unneeded output and was missing component config information.
+kubeadm: fixed a bug where `kubeadm upgrade plan -o yaml|json` included unneeded output,
+and was missing component config information.
```

**Pull request merged**
