### PR TITLE
Remove SIG Scheduling approvers from reviewers

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

/sig scheduling

We currently have 4 approvers and 8 reviewers (including the 4 approvers)

I propose:
- To remove the approvers from the reviewers list (this PR)
- Any PR should be reviewed by a reviewer before being assigned to the approver. Reviewers are assigned automatically.
- If it's a hotfix, the PR can be assigned to an approver directly.

I hope this accomplishes the following:
- Lower review burden from approvers
- Encourage our reviewers to take more responsibility and build their reputation.
- Encourage new contributors to seek the reviewer status.

Original proposal https://groups.google.com/g/kubernetes-sig-scheduling/c/1JD2w1w48uo/

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by damemi — APPROVED** [review]
+1, good idea to get more reviewers active. Thanks Aldo!

**Comment by denkensk** [comment]
+1

**Comment by liggitt** [comment]
/approve
per acks from scheduling leads

**Pull request merged**
