### PR TITLE
Automated cherry pick of #116506: generate ReportingInstance and ReportingController in Event

### PR DESCRIPTION
**Pull request by HirazawaUi**
Cherry pick of #116506 on release-1.27.

#116506: generate ReportingInstance and ReportingController in Event

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
When retrieving event resources, the reportingController and reportingInstance fields in the event will contain values.
```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
/release-note-edit When retrieving event resources, the reportingController and reportingInstance fields in the event will contain values.

/assign logicalhan

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
