### PR TITLE
fixing docker file, and bumping cassandra version

### PR DESCRIPTION
**Pull request by chrislovecnm**
- had issue with current v9 build.  `cassandra.yaml` was not editable by the cassandra user, chown and chmod is now correct
- rebuild jar against 3.5 cassandra version and bumped C\* version

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@jeffmendoza @bprashanth this should fix the v9 image issue.  Want to keep the version the same since v9 is broken anyways.  Can we push the image, let me test, then merge??

**Comment by chrislovecnm** [comment]
@thockin this fixes https://github.com/kubernetes/kubernetes/pull/26022

So we don't have a repeat, can you push and image up, let me test, and then merge? 

I just put in https://github.com/kubernetes/kubernetes/issues/26023 so we can figure out how to not have a repeat

**Comment by chrislovecnm** [comment]
@jeffmendoza - I will test. Thanks

**Comment by chrislovecnm** [comment]
@jeffmendoza I know I am being super careful with this, but can you do a docker push up to gcr.io again for me?  Just want to test from gcr.io.  Found a couple of permission issue, and retested locally.  Locally looks good, but until e2e is improved really cannot verify.

Thanks for your help!!

**Comment by jeffmendoza** [comment]
@chrislovecnm Re-pushed with the latest commits

**Comment by chrislovecnm** [comment]
@jeffmendoza woop ... that did the trick!

@thockin when you have a chance, and the builds pass, ready to merge!

**Comment by chrislovecnm** [comment]
@thockin can I get a LGTM and a merge ;) Pretty please

**Comment by chrislovecnm** [comment]
@jeffmendoza are you able to approve this PR?

**Comment by jeffmendoza** [comment]
Hi, nope, but @pwittrock or @janetkuo might be able to help

**Comment by chrislovecnm** [comment]
@thockin @bgrant0607 is this making it into 1.3?

**Comment by bgrant0607** [comment]
@chrislovecnm Examples aren't part of our releases. We haven't created the 1.3 release branch yet, so it will be in the release branch.

**Pull request merged**
