### PR TITLE
Call push-ci-build.sh from the kubernetes/release repo.

### PR DESCRIPTION
**Pull request by david-mcmahon**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32013)

### CODE REVIEW

**Comment by ixdy** [comment]
Maybe also delete `build/push-ci-build.sh` in this PR?

That way nobody will think making changes to it has any effect.

**Comment by ixdy** [comment]
(I'm assuming you've confirmed this works, right?)

**Comment by david-mcmahon** [comment]
Yes this has been working fine for the test jobs.  Of course My intention is not to check this in today or over the weekend.  Hold off on the LGTM label, but feel free to give it a lgtm comment.

**Comment by spxtr** [comment]
Has this been tested on PR Jenkins? I think it should still work, since you honor `KUBE_GCS_RELEASE_BUCKET`, but we should be sure to watch closely after merging.

Also, for now the release repo is super small, but is there any reason to not do a shallow clone? I'm worried about GitHub flaking on us or rate-limiting us.

LGTM though.

**Comment by david-mcmahon** [comment]
It has been tested using https://github.com/kubernetes/test-infra/pull/513 which has been working.

Re: cloning.  I assumed that with the move to split up the repo we'd soon have a facility to clone all of the repos we needed upfront in some consistent way?  I'm a bit loathe to overoptimize this one-off clone.

I'll be monitoring this very closely when it goes in of course.

**Comment by ixdy** [comment]
I still think we should probably delete `build/push-ci-build.sh` at the same time.

**Comment by david-mcmahon** [comment]
@ixdy I have #24629 doing all of the cleanup.  I want to stage this out.

**Comment by spxtr** [comment]
> Re: cloning. I assumed that with the move to split up the repo we'd soon have a facility to clone all of the repos we needed upfront in some consistent way? I'm a bit loathe to overoptimize this one-off clone.

Sounds reasonable, and yes, we're working on it.

**Comment by david-mcmahon** [comment]
Carrying forward verbal LGTM to label and upping priority so we can get this in today with time to watch.

**Comment by ixdy** [comment]
fyi @rmmh @k8s-oncall

**Pull request merged**
