### PR TITLE
fix cluster/images/etcd/migrate staticcheck

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fix staticcheck 

**Which issue(s) this PR fixes**:

Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
According to static check, this file should now be removed from `staticcheck_failures`:

```
Some packages in hack/.staticcheck_failures are passing staticcheck. Please remove them.

  cluster/images/etcd/migrate
```

**Comment by hwdef** [comment]
@jpbetz 
Thanks for you suggestion. I fixed it.

**Pull request closed without merging**
