### PR TITLE
scheduler: a small refactor for generic scheduler

### PR DESCRIPTION
**Pull request by xiang90**
1. add comment for schedule function
2. do the fit length checking early for readability.

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Needs rebase

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@xiang90 - can you please rebase?

**Comment by xiang90** [comment]
@wojtek-t Rebased. PTAL.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Pull request merged**
