### PR TITLE
fix a bug of wrong parameters which could cause token projection failure

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
a parameter wrong order bug
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
:( tested this with system:serviceaccount:default:default

/lgtm

**Comment by tallclair** [comment]
Please add a test.
/milestone v1.11
/sig auth
/priority critical-urgent

**Comment by mikedanese** [comment]
/hold

@WanLinghao can you add a test? If not, i'm happy to help.

**Comment by WanLinghao** [comment]
@mikedanese  ok，please add a test since you are more familiar with this module

**Comment by mikedanese** [comment]
I'm going to add a test in a followup

/retest
/hold cancel

**Pull request merged**
