### PR TITLE
kubeadm use output/v1alpha3 version to print objects

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: use output/v1alpha3 to print structural output for the commands "kubeadm config images list" and "kubeadm token list".
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/cc @neolit123 

should we mark `output/v1alpha2` as deprecated or remove it?

**Comment by neolit123** [comment]
looks like we missed enabling v1alpha3 everywhere.

> should we mark `output/v1alpha2` as deprecated or remove it?

it already is deprecated
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/output/v1alpha2/doc.go#L26

+1 to remove it in a new PR for 1.31
cc @SataQiu @pacoxu  commnents?

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: use output/v1alpha3 to print structural output for the commands "kubeadm config images list" and "kubeadm token list". 
```

**Review by neolit123 — COMMENTED** [review]
/triage accepted
/priority important-longterm
/approve

**Review by SataQiu — COMMENTED** [review]
thanks
/lgtm
/approve

**Comment by SataQiu** [comment]
@neolit123 
> +1 to remove it in a new PR for 1.31

I agree with you. It is safe to remove the `alpha` version API

**Pull request merged**
