### PR TITLE
[1.16] Update to json-patch 4.9.0

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Includes the same version bump as #94147 on master.

Does not change code, but ensures go module consumers pick up the correct version of json-patch containing fixes.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @dims

### CODE REVIEW

**Comment by liggitt** [comment]
lint caught an unused dep I needed to drop

**Comment by fedebongio** [comment]
@liggitt curious why does not show cherrypick in the title?

**Comment by liggitt** [comment]
it was manually done, dependency updates don't cherry-pick cleanly

**Pull request merged**
