### PR TITLE
Automated cherry pick of #32374 #32632

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #32374 #32632 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33225)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
This is fine to hold for a 1.4.1. Test code only, purpose is to unblock testing petset on providers other than gce.

**Comment by jlowdermilk** [comment]
cc @bprashanth @soltysh

**Comment by soltysh** [comment]
:+1: on my side

**Comment by jlowdermilk** [comment]
@k8s-bot gke e2e test this issue #33672

**Pull request merged**
