### PR TITLE
The latest Docker CE Edge release is 18.09.

### PR DESCRIPTION
**Pull request by PauloFerreira25**

### CODE REVIEW

**Comment by neolit123** [comment]
hi @PauloFerreira25 
thank you for the PR. you need to sign the CLA to be able to submit PRs.

i don't think we are going to do that in 1.13.
/kind cleanup

/assign @timothysc 
for priority label decision.

**Comment by timothysc** [comment]
It's way too late in the 1.13 cycle for this

**Comment by luxas** [comment]
It's @kubernetes/sig-node-pr-reviews that should be reviewing this

**Comment by chuckha** [comment]
closing since a separate PR has already merged with this change:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/system/docker_validator.go#L41

/close

**Pull request closed without merging**
