### PR TITLE
Continue adding APIService to sync

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR would add all eligible APIService's to sync.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
@caesarxuchao
Can you take a look ?

**Comment by tedyu** [comment]
@mikedanese
Can you review ?

**Comment by jpbetz** [comment]
I don't follow why this is needed. The code looks for CRDs that match the given group/version, and if it finds any, it calls `AddAPIServiceToSync` with that group/version. Why call that more than once?

/hold

**Comment by tedyu** [comment]
@jpbetz 
Is there possibility that more than one match of the given group/version is found ?
If so, should we consider the subsequent matches as error ?

**Comment by jpbetz** [comment]
> @jpbetz
> Is there possibility that more than one match of the given group/version is found ?
> If so, should we consider the subsequent matches as error ?

It's matching against CRDs, which can certainly share a group/version. I don't see anything wrong with that.

**Pull request closed without merging**
