### PR TITLE
kubectl: remove unnecessary internal->external conversion before PrintObj

### PR DESCRIPTION
**Pull request by seans3**
* Removes `AsDefaultVersionedOrOriginal` function
* Removes all calls to `AsDefaultVersionedOrOriginal` function
* This function is no longer necessary since the objects are guaranteed to be external versions of the resource.

Helps fix:
https://github.com/kubernetes/kubectl/issues/80

/kind cleanup
/assign
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by apelisse** [comment]
/lgtm

I'm fine with that

**Pull request merged**
