### PR TITLE
Remove deadcode

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove deadcode in

> pkg/scheduler/framework/plugins/noderesources/requested_to_capacity_ratio.go pkg/controller/volume/attachdetach/reconciler/reconciler_test.go

#### Which issue(s) this PR fixes:

ref #99243

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by chrishenzie — APPROVED** [review]
/lgtm

**Comment by Huang-Wei** [comment]
/approve
for scheduler side.

**Pull request merged**
