### PR TITLE
Fix RBD Go field names

### LINKED ISSUE #9083: RBD json tags don't match field names
There may be others but I saw this today...

```
type RBDVolumeSource struct {
    // Required: CephMonitors is a collection of Ceph monitors
    CephMonitors []string `json:"monitors"`
    // Required: RBDImage is the rados image name
    RBDImage string `json:"image"`
    // Required: Filesystem type to mount.
    // Must be a filesystem type supported by the host operating system.
    // Ex. "ext4", "xfs", "ntfs"
    // TODO: how do we prevent errors in the filesystem from compromising the machine
    FSType string `json:"fsType,omitempty"`
    // Optional: RadosPool is the rados pool name,default is rbd
    RBDPool string `json:"pool"`
    // Optional: RBDUser is the rados user name, default is admin
    RadosUser string `json:"user"`
```

I think that, in general we want field names and JSON tags to match unless there's a good reason for them not to.  I see no good reason here.  Probably field names should change, leaving tags (the API) untouched.

@markturansky @rootfs

### PR DESCRIPTION
**Pull request by roycaihw**
**What this PR does / why we need it**:
Go field names that were not correct for JSON names. This is a followup of #57665 and an attempt to fix part of existing Go field names (see full list in https://github.com/kubernetes/kubernetes/pull/65737) that do not follow the [API convention](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#naming-conventions): 

"Go field names must be CamelCase. JSON field names must be camelCase. Other than capitalization of the initial letter, the two should almost always match. No underscores nor dashes in either".

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9083, fixes #57665

**Release note**:

```release-note
Action required: 
The following API Go field names are renamed to match JSON field names:
(in format of package,type,"field")
rename k8s.io/api/core/v1, RBDVolumeSource, "CephMonitors" to "Monitors";
rename k8s.io/api/core/v1, RBDVolumeSource, "RBDImage" to "Image";
rename k8s.io/api/core/v1, RBDVolumeSource, "RBDPool" to "Pool";
rename k8s.io/api/core/v1, RBDVolumeSource, "RadosUser" to "User";
rename k8s.io/api/core/v1, PhotonPersistentDiskVolumeSource, "PdID" to "PDID".
```

### CODE REVIEW

**Comment by roycaihw** [comment]
/cc @rootfs 
Please review the api change.

cc @thockin

**Comment by roycaihw** [comment]
Also 
/cc @luomiao

on photon_pd api change.

**Comment by roycaihw** [comment]
cc @kubernetes/sig-storage-api-reviews

**Comment by rootfs** [comment]
for rbd changes
/approve

**Comment by jsafrane** [comment]
/lgtm
for the code

/assign @liggitt 
for API approval, not sure if such changes are allowed

**Comment by liggitt** [comment]
can you also remove the lines this is fixing from the violations txt file?

**Comment by liggitt** [comment]
```
W0810 14:19:18.901] make[1]: *** [pkg/generated/openapi/zz_generated.openapi.go] Error 1
W0810 14:19:18.903] make: *** [generated_files] Error 2
I0810 14:19:19.004] 16a17,24
I0810 14:19:19.004] > API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,CephMonitors
I0810 14:19:19.004] > API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RBDImage
I0810 14:19:19.004] > API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RBDPool
I0810 14:19:19.005] > API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RadosUser
I0810 14:19:19.005] > API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,CephMonitors
I0810 14:19:19.005] > API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RBDImage
I0810 14:19:19.005] > API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RBDPool
I0810 14:19:19.005] > API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RadosUser
I0810 14:19:19.006] Error: API rules check failed. Reported violations "_output/violations.report" differ from known violations "api/api-rules/violation_exceptions.list". Please fix API source file if new violation is detected, or update known violations "api/api-rules/violation_exceptions.list" if existing violation is being fixed. Please refer to api/api-rules/README.md and https://github.com/kubernetes/kube-openapi/tree/master/pkg/generators/rules for more information about the API rules being enforced.
```

**Comment by liggitt** [comment]
> for API approval, not sure if such changes are allowed

changing go structs does not change wire format, but does affect client-go and api consumers. it's a judgement call whether the benefit outweighs the cost of change to those consumers. @kubernetes/api-reviewers, opinion on that?

**Pull request closed without merging**
