### PR TITLE
remove old ip checks.

### PR DESCRIPTION
**Pull request by JaredTan95**
Signed-off-by: JaredTan95 <jian.tan@daocloud.io>

#### What type of PR is this?
/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by wzshiming** [comment]
Please fix the unit test https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100879/pull-kubernetes-unit/1379792810051375104

**Comment by JaredTan95** [comment]
CC @wzshiming

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by enj** [comment]
/remove-sig auth

I do not know why the bot decided this was SIG Auth.

**Review by thockin — COMMENTED** [review]
/lgtm

**Pull request merged**
