### PR TITLE
Enable default HugePages limit and request per namespace

### LINKED ISSUE #60782: HugePages should be restricted via LimitRange
/kind feature
See: #53672

It should be possible to set default hugepages limit and request per namespace as it is possible for [memory](https://kubernetes.io/docs/tasks/administer-cluster/memory-default-namespace/).

### PR DESCRIPTION
**Pull request by Creatone**
**What this PR does / why we need it**: By default LimitRange plugin disable setting default limit per namespace for HugePages. Now it's possible to set this limit.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60782

**Special notes for your reviewer**: 
Tests haven't yet been written.

**Release note**:

```release-note
HugePages: LimitRange support.
```

### CODE REVIEW

**Comment by iwankgb** [comment]
@flyingcougar could you enable testing, please?

**Comment by derekwaynecarr** [comment]
can you comment on the motivation behind defaulting on this resource?  i suspect applications that consume hugepages are heavily tuned and would most likely set the value explicitly rather than fall back to defaulting.

**Pull request closed without merging**
