### PR TITLE
Add testcases for cmd/kubeadm/app/util/net.go and version.go

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The test scenarios are incomplete.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve
/triage accepted
/priority backlog

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by SataQiu** [comment]
pull-kubernetes-verify failed, please run `./hack/update-gofmt.sh` @Octopusjust

**Comment by Octopusjust** [comment]
> pull-kubernetes-verify failed, please run `./hack/update-gofmt.sh` @Octopusjust

OK

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

**Review by yangjunmyfm192085 — COMMENTED** [review]
/release-note-none

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
