### PR TITLE
[cherry-pick #70980] Limit iops per container

### LINKED ISSUE #70364: Limiting blkio with cgroups by annotation
**What would you like to be added**:
We hope that kubernetes support limiting blkio resources.
We use the annotation of kubernetes to pass the parameters of the cgroup to control the container blkio. The current features apply only to the Linux devmapper environment.

**Why is this needed**:
In my production environment, multi-tenancy shares a storage device, we must isolate the io of each tenant to ensure that the tenants do not interfere with each other. CRI does not provide an interface for IO resource isolation.

/kind feature
/sig node

### PR DESCRIPTION
**Pull request by pacoxu**
Per @Avanpourm ’s pull request is to release-1.12, rebase to master https://github.com/kubernetes/kubernetes/pull/70980

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
> I need to limit the read and write iops of rootfs.

**Which issue(s) this PR fixes**:
Fixes #70364

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

> Use the annotation of kubernetes to pass the parameters of the cgroup to control the container blkio
> Specifying the device path as "rootfs" indicates that you specify limiting rootfs
> For example:
> io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sda1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}]"device_write_iops":[{"device":"rootfs","value":"300"}]}'

```release-note
Use the annotation to pass the parameters of the cgroup to control the container blkio for rootfs or other device path.
```

> ### Parameter
> parameter	type	default value	means	parameter range	example	corresponds to Cgoup
> weight	Uint16	0	Weight value for all devices	10-1000	1	
> weight_device	Array	nil	Weight value for all devices	-		
> weight_device.[*].device	String		The absolute path of the device		/dev/sda1	
> weight_device.[*].value	String		Weight value of the device	10-1000		
> device_read_bps	Array	nil	A device reads the maximum number of bytes per second			
> device_read_bps.[*].device	String		The absolute path of the device. You can use "rootfs" for the specified root directory			
> device_read_bps.[*].value	String		Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state	>1k	1M	
> device_write_bps	Array	nil	Maximum number of bytes per second allowed to write to the device			
> device_write_bps.[*].device	String		The absolute path of the device. You can use "rootfs" for the specified root directory			
> device_write_bps.[*].value	String		Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state	>1k		
> device_read_iops	Array	nil	Max IOPS			
> device_read_iops.[*].device	String		The absolute path of the device. You can use "rootfs" for the specified root directory			
> device_read_iops.[*].value	String		Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state	>5		
> device_write_iops	Array	nil	Max IOPS			
> device_write_iops.[*].device	String		The absolute path of the device. You can use "rootfs" for the specified root directory			
> device_write_iops.[*].value	String		Value ,like: 1[ K M G ]. Limit the minimum to prevent the process from entering a D state	>5		
> ### Deployment Example
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   labels:
>     app: iops-app
>   name: iops-app
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: iops-app
>   template:
>     metadata:
>       labels:
>         app: iops-app
>       annotations:
>         io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sad1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}],"device_write_iops":[{"device":"rootfs","value":"300"}]}'
>     spec:
>       nodeSelector:
>         kubernetes.io/hostname: szdc-k8sm-2-2.meitu-inc.com
>       containers:
>       - image: docker.io/centos:7
>         command: ["/bin/sh","-c"]
>         args: ["while(true);do /bin/sleep 10;done"]
>         name: iops-app
>         resources:
>           requests:
>             memory: "200Mi"
>             cpu: 1
>           limits:
>             memory: "200Mi"
>             cpu: 1
>         volumeMounts:
>         - name: host-time
>           mountPath: /etc/localtime
>       volumes:
>       - name: host-time
>         hostPath:
>           path: /etc/localtime
> ```

```docs
Pod annotation example to limit device iops for containers by cgroup. Example is like below, 'io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sda1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}]"device_write_iops":[{"device":"rootfs","value":"300"}]}'

```

### CODE REVIEW

**Comment by pacoxu** [comment]
include @feiskyer  @cuericlee @derekwaynecarr @pmorie  who are in thread #70980

**Comment by pacoxu** [comment]
close per https://github.com/kubernetes/kubernetes/issues/92287

I think the proposal 2 is better than current pr.

**Comment by bingerambo** [comment]
> close per #92287
> 
> I think the proposal 2 in #92287 is better than current pr.

@pacoxu 
Is the merge request closed for the failed test? 
I have a similar problem to limit the read and write iops of the container or pod.
Is there any new progress about this feature.

**Comment by pacoxu** [comment]
@bingerambo 
https://github.com/kubernetes/kubernetes/issues/92287#issuecomment-654808526 I prefer this proposal
And the KEP kubernetes/enhancements#1907 is under disscussion, however there are some things which is not clear yet.

BTW, I'm not focus on storage in recent period. I will pick this up later once the proposal of the KEP have a proper design which is approved by sig storage team. Then I can move on.

**Pull request closed without merging**
