### PR TITLE
Added default tolerations for new pods.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

Part of https://github.com/kubernetes/kubernetes/issues/67606

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by tpepper** [comment]
/priority critical-urgent

This is likely release blocking.

**Review by janetkuo — APPROVED** [review]

**Review by dougm — COMMENTED** [review]
I'll wait for this to get merged before starting the beta.2 build this afternoon.

**Pull request merged**
