### PR TITLE
fix rootScopeNaming generate selfLink issue

### PR DESCRIPTION
**Pull request by adohe-zz**
quick fix to #37622

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37686)

**Comment by AdoHe** [comment]
@lavalamp ptal.

**Comment by AdoHe** [comment]
@lavalamp kindly ping on this.

**Comment by lavalamp** [comment]
Sorry for delay I have a large backlog at the moment.

Please use path.Join instead of string concatenation.

Please write a test for this.

**Comment by AdoHe** [comment]
@lavalamp ok, I will update this asap.

**Comment by ingvagabund** [comment]
This fixes the issue, tested on Fedora.

**Comment by smarterclayton** [comment]
Rebase please.

**Comment by mbohlool** [comment]
@AdoHe this looks good to me. Assign it back to me please when the rebase is done.

**Comment by AdoHe** [comment]
Thanks @mbohlool , I will do it today

**Comment by liggitt** [comment]
> Please write a test for this.

Agree, needs a test

**Comment by AdoHe** [comment]
I just go back from my Spring Festival Holiday, will update this asap.

**Comment by AdoHe** [comment]
@mbohlool @liggitt please take a look at #41011, I will close this one.

**Pull request closed without merging**
