### PR TITLE
MESOS: Automated cherry pick of #17198 - DCOS getting started guide

### PR DESCRIPTION
**Pull request by sttts**
Cherry pick of #17198 on release-1.1.

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@googlebot I signed it.

**Comment by sttts** [comment]
@googlebot @karlkfi signed it.

**Comment by brendandburns** [comment]
LGTM.

**Comment by karlkfi** [comment]
This is a docs change. It doesn't need unit/integration/e2e tests. The integration test failure must be a flake, as noted in https://github.com/kubernetes/kubernetes/pull/17602#issuecomment-159304109

**Comment by karlkfi** [comment]
This needs to be merged to resolve a 404 on http://kubernetes.io/gettingstarted/ linking to http://kubernetes.io/v1.1/docs/getting-started-guides/dcos.html which was created by #17695 (which was merged a little prematurely).

**Comment by karlkfi** [comment]
@k8s-bot unit test this

**Comment by karlkfi** [comment]
@googlebot I signed it.

**Comment by karlkfi** [comment]
Unit test failure resembling the TestTranslateTimestamp failures mentioned in #17998

**Comment by karlkfi** [comment]
I'm going to go ahead and merge this, because it can't possibly affect unit/integration/e2e tests.

**Pull request merged**
