### PR TITLE
Register metav1 types into samplecontroller api scheme

### LINKED ISSUE #57205: sample-controller errors when starting:  Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report
/kind bug

**What happened**:
I'm following the directions to run the sample controller on https://github.com/kubernetes/sample-controller
When running it as directed, it gives these errors:
$ go run *.go -kubeconfig=$HOME/.kube/config
E1214 10:34:25.188240  177579 reflector.go:205] k8s.io/sample-controller/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"
E1214 10:34:26.188769  177579 reflector.go:205] k8s.io/sample-controller/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"

**What you expected to happen**:
Not to generate these errors.

**How to reproduce it (as minimally and precisely as possible)**:
1) Have a working kube config.
2) checkout kubernetes/sample-controller
3) run it: ~/go/src/k8s.io/sample-controller$ go run *.go -kubeconfig=$HOME/.kube/config

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.845+542486186fd684-dirty", GitCommit:"542486186fd684db939098ffadeb1aa5dcd63498", GitTreeState:"dirty", BuildDate:"2017-10-02T22:37:04Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GKE
- OS (e.g. from /etc/os-release):
my workstation is 14.04.5 LTS, Trusty Tahr
- Kernel (e.g. `uname -a`):
my workstation kernel is 4.4.0-96-generic
- Install tools:
- Others:
go version 1.9

### PR DESCRIPTION
**Pull request by munnerz**
**What this PR does / why we need it**:

Registers metav1 resource types (e.g. ListOptions) with sample-controller scheme.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57205

**Release note**:
```release-note
Fix error message regarding conversion of `v1.ListOptions` to `samplecontroller.k8s.io/v1alpha1`.
```

/cc @sttts @nikhita

### CODE REVIEW

**Comment by G-Harmon** [comment]
awesome, thanks for the quick fix! I'll give it a try today.

**Comment by G-Harmon** [comment]
It gets past the previous error, and looks like it works!

When I create a Foo, I see this Error printed. I don't know if it's significant or not:
E1215 08:08:04.688734  123776 controller.go:236] error syncing 'default/example-foo': Operation cannot be fulfilled on foos.samplecontroller.k8s.io "example-foo": the object has been modified; please apply your changes to the latest version and try again
But kubectl get deployments *does* show the new deployment from this controller, so it may be a benign message.

**Comment by G-Harmon** [comment]
cc @cheftako , who was helping me debug this issue earlier.

**Comment by nikhita** [comment]
:+1: :+1: :+1:

**Comment by nikhita** [comment]
@mbohlool Can this be cherry-picked? Added more details here: https://github.com/kubernetes/kubernetes/pull/62028#issuecomment-377944125.

**Comment by sttts** [comment]
> Can this be cherry-picked?

Would make sense.

**Pull request merged**
