### PR TITLE
Automated cherry pick of #61575: Remove all upstream BUILD, BUILD.bazel, and WORKSPACE #57600: Vendor gazelle #62499: Update kazel to include openapi tag detection fix

### LINKED ISSUE #64925: hack/verify-bazel.sh always fails on release-1.10
/kind bug
/sig testing
/sig release
/priority critical-urgent

```
I0608 15:49:50.952] +++ Running case: verify.bazel 
I0608 15:49:50.954] +++ working dir: /go/src/k8s.io/kubernetes
I0608 15:49:50.956] +++ command: bash "hack/make-rules/../../hack/verify-bazel.sh"
W0608 15:49:59.974] ../../internal/repos/remote.go:29:2: cannot find package "golang.org/x/tools/go/vcs" in any of:
W0608 15:49:59.975] 	/tmp/tmp.QZAPzQQRF1/go/src/github.com/bazelbuild/bazel-gazelle/vendor/golang.org/x/tools/go/vcs (vendor tree)
W0608 15:49:59.975] 	/usr/local/go/src/golang.org/x/tools/go/vcs (from $GOROOT)
W0608 15:49:59.975] 	/tmp/tmp.QZAPzQQRF1/go/src/golang.org/x/tools/go/vcs (from $GOPATH)
W0608 15:49:59.981] !!! [0608 15:49:59] Call tree:
W0608 15:49:59.983] !!! [0608 15:49:59]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
W0608 15:49:59.988] !!! [0608 15:49:59] Call tree:
W0608 15:49:59.990] !!! [0608 15:49:59]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
I0608 15:50:01.032] +++ exit code: 1
I0608 15:50:01.038] +++ error: 1
I0608 15:50:01.065] FAILED   verify-bazel.sh	11s
```

No PRs can be merged into release-1.10. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64848/pull-kubernetes-verify/94899/?log#log

Similar issue: https://github.com/kubernetes/kubernetes/issues/60730

/cc @ixdy

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #61575 #57600 #62499 on release-1.10.

#61575: Remove all upstream BUILD, BUILD.bazel, and WORKSPACE
#57600: Vendor gazelle
#62499: Update kazel to include openapi tag detection fix

This is an alternative to #64928, and would fix #64925.

We can't just cherry-pick #57600, since there was a prerequisite PR and a fixup PR afterwards.

### CODE REVIEW

**Comment by BenTheElder** [comment]
pulling down to test, changes SGTM. this should be preferable to the other PR imo.

**Comment by ixdy** [comment]
This does update gazelle to 0.10.1 (from an untagged version), but I don't think there were any user-visible changes, just some bug fixes we needed.

**Comment by BenTheElder** [comment]
I think this works fine on macOS locally.

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/release-note-none
[we should make this show up on prow's command help, will go fix that](https://www.youtube.com/watch?v=44-RsrF_V_w)

**Comment by ixdy** [comment]
tests are passing, woo!

/assign @thockin for approval

**Comment by BenTheElder** [comment]
@calebamiles looks like you are 1.10 branch manager, can you approve this for cherry pick?

**Pull request merged**
