### PR TITLE
Make kubelet's file source go through conversion

### PR DESCRIPTION
**Pull request by thockin**
See comments for details.  Same problem exists in HTTP source, but I want to
float this for review first.

@bgrant0607 @smarterclayton

### CODE REVIEW

**Comment by thockin** [comment]
tests failed, I will fix those up ASAP

**Comment by thockin** [comment]
Now with HTTP fixed and tests that pass.

**Comment by thockin** [comment]
And test cases that cover this case!

**Comment by thockin** [comment]
This affects all of the cadvisor pods for anyone running from head - I'd like to get it in today, if possible.

**Comment by thockin** [comment]
Do you want me to reassign this review?

**Comment by thockin** [comment]
@dchen1107 want to take over the review on this one?  I want to get it in today.

**Comment by dchen1107** [comment]
Of course, doing it now.

**Comment by dchen1107** [comment]
Can you add a test with "version: v1beta2" too? It should work, but still want to make sure no one would break this in the future.

**Comment by thockin** [comment]
Done

**Comment by dchen1107** [comment]
LGTM. Will merge on green.

**Comment by smarterclayton** [comment]
Sorry, was debugging something else and missed this.

----- Original Message -----

**Comment by thockin** [comment]
@smarterclayton NP - Take a look if you want

**Comment by smarterclayton** [comment]
LGTM - I hate this code.

**Pull request merged**
