### PR TITLE
Revert "Use netlink.SetPromiscOn instead of iproute2 command"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#30346

This PR broke gce-slow and gke-slow suites by breaking test:
"KubeProxy should test kube-proxy [Slow]"

Reverting this PR to unblock merge-queue.

@dshulyak @freehan

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31096)

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
The tests are failing with the following error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:107 Response was:map[responses:[netserver-2 netserver-1 netserver-1 netserver-1 netserver-1 netserver-1 netserver-1 netserver-1 netserver-1 netserver-2 netserver-1 netserver-1 netserver-2 netserver-2 netserver-1 netserver-2 netserver-2 netserver-1 netserver-2 netserver-1 netserver-1 netserver-1 netserver-1 netserver-1 netserver-2] errors:[reading from udp connection failed. err:'read udp 10.180.1.8:44308->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:37810->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:60145->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:57972->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:54243->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:60202->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:40161->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:59809->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:34808->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:48060->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:52873->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:35145->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:44825->10.0.125.50:90: i/o timeout' reading from udp connection failed. err:'read udp 10.180.1.8:47988->10.0.125.50:90: i/o timeout']] Expected : 2 to be == : 3 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:247
```

**Comment by wojtek-t** [comment]
Manually merging to unblock merge-queue.

**Comment by luxas** [comment]
@dshulyak ^

**Pull request merged**
