### PR TITLE
client-gen: use template function declarations for gentype

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Instead of hard-coding gentype in the templates, use template function declarations; this ensures that the package is correctly imported.

This doesn’t change any of the generated code.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by jpbetz** [comment]
Thanks for cleaning this up @skitt

**Pull request merged**
