### PR TITLE
add protobuf for CRD

### PR DESCRIPTION
**Pull request by deads2k**
Adds protobuf encoding to CRD and simplifies loopback initialization.

xref: https://github.com/kubernetes/features/issues/95

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by sttts** [comment]
@smarterclayton approved?

**Comment by deads2k** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
