### PR TITLE
Ensure v1.18.0-alpha.3 tag is reachable via master

### PR DESCRIPTION
**Pull request by liggitt**
Merges the v1.18.0-alpha.3 tag into master to fix `git describe`.

After https://github.com/kubernetes/release/pull/1030, anago always created a release-specific commit for release tags, but when releasing on the master branch, it does not push that commit to master, so the resulting tagged commit does not exist on the master branch.

v1.18.0-alpha.3 was the first affected release like this. It means that `git describe` on master currently thinks we are on the v1.18.0-alpha.2 series:

```
$ git describe master
v1.18.0-alpha.2-663-gdf908c3aad7
```

with this PR merged to master locally:
```
$ git describe master
v1.18.0-alpha.3-302-g99c7caee0e9
```

/hold until the issue with anago tagging master releases off the master branch is resolved (xref https://github.com/kubernetes/release/issues/1080#issuecomment-585207148)

```release-note
NONE
```

/sig release
/cc @justaugustus

### CODE REVIEW

**Comment by liggitt** [comment]
flipping cla bit so the anago commit is happy

**Comment by liggitt** [comment]
runc flake

/retest

**Comment by justaugustus** [comment]
`anago` release commit fix is here: https://github.com/kubernetes/release/pull/1096

/lgtm
/approve
/retest

**Comment by liggitt** [comment]
gpu test failed with stage error:

> error during /go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-gce-device-plugin-gpu --allow-dup (terminated): signal: killed

cc @dims

**Comment by liggitt** [comment]
it's unclear whether the presence of this merge commit will cause problems, given

- https://github.com/kubernetes/test-infra/issues/5376
- https://groups.google.com/forum/#!msg/kubernetes-dev/KmeNarMIyRU/5Z00p2WWCQAJ
- https://github.com/kubernetes/test-infra/issues/5376#issuecomment-342404495

**Comment by liggitt** [comment]
closing in favor of creating a new v1.18.0-alpha.4 tag on a commit reachable from master

**Pull request closed without merging**
