### PR TITLE
Add several validation to persistent volume

### PR DESCRIPTION
**Pull request by liangxia**
**What this PR does / why we need it**:
Add several unit test for persistent volume validation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fejta** [comment]
/assign @bgrant0607 @liggitt @thockin @smarterclayton @lavalamp @erictune 
/unassign

per https://github.com/tianshapjq/kubernetes/blob/005485bf9ba0caf78fa483cd257e21628cb70e9e/OWNERS_ALIASES#L178
per https://github.com/tianshapjq/kubernetes/blob/005485bf9ba0caf78fa483cd257e21628cb70e9e/pkg/api/OWNERS

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-storage-pr-reviews

**Comment by liangxia** [comment]
Rebased and retest passed.

**Comment by jsafrane** [comment]
/assign @thockin @liggitt 
for approval

**Pull request merged**
