### PR TITLE
Fixes various proxy issues.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes erroneous declaration of oomAdjuster.
Fixes duplication of execer, dbus, iptInterface.
Fixes default assignment of SyncPeriod.

### CODE REVIEW

**Comment by thockin** [comment]
Needs a rebase

**Comment by aveshagarwal** [comment]
rebased and pushed updated PR.

**Comment by aveshagarwal** [comment]
Shippable tests seem to be failing, still looking what might be wrong:

I0929 16:39:14.624088   16112 manager.go:1619] Pod infra container looks good, keep it "foo_default"
I0929 16:39:15.212969   16112 config.go:252] Setting pods for source file
I0929 16:39:16.220108   16112 config.go:252] Setting pods for source file
F0929 16:39:16.718927   16112 integration.go:843] FAILED: unexpected endpoints: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:60
  'KUBE_API_VERSIONS="v1,experimental/v1alpha1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:60 runTests(...)
  2: ./hack/test-integration.sh:74 main(...)
Exiting with status 1

**Comment by aveshagarwal** [comment]
rebased again and updated PR.

**Pull request merged**
