### PR TITLE
Support apps.ReplicaSet in kubectl

### LINKED ISSUE #53040: `kubectl set` commands on ReplicaSet and DaemonSet occasionally return version registration errors
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
create  a ReplicaSet then change its image by kubectl set image command. It returns an error ocassionally like 
error: replicasets/gakki-replicaset no kind "ReplicaSet" is registered for version "apps/v1beta1"

**What you expected to happen**:
image changes without error
**How to reproduce it (as minimally and precisely as possible)**:
yaml file as follows:
```
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
```
execute command:
kubectl create -f test.yaml
kubectl set image rs test-replicaset php-redis=nginx:1.7.9 

**Anything else we need to know?**:
the error happens ocassionally, you can make  several tries to observe this error.  
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.51+14cedb9f581d6a-dirty", GitCommit:"14cedb9f581d6a6de367e780e31a8ca1c7b12112", GitTreeState:"dirty", BuildDate:"2017-09-23T08:08:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.281+ba1ab3fd559dd7-dirty", GitCommit:"ba1ab3fd559dd775863477f00a3e8d3bf86583a0", GitTreeState:"dirty", BuildDate:"2017-09-25T11:31:36Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by janetkuo**
Supersedes #53056, ref #53040 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by janetkuo** [comment]
This PR did fix the bug that some kubectl commands (`expose`, `autoscale`, etc) don't recognize apps.ReplicaSet, but it does not fix the bug of occasional errors returned by `kubectl set image`

**Comment by mengqiy** [comment]
> but it does not fix the bug of occasional errors returned by kubectl set image

@janetkuo Do you know the root cause of it? I suspect it's preference order issue.

**Comment by janetkuo** [comment]
I updated my findings in #53040

**Comment by mengqiy** [comment]
/lgtm cancel

Hold on.
Please update func UpdatePodSpecForObject as well.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L236

**Comment by pwittrock** [comment]
@abgworrall Would it be possible to cherrypick this?

**Comment by janetkuo** [comment]
@mengqiy `UpdatePodSpecForObject` is not where the error comes from, and the function checks internal version of resources. Internal version DaemonSet and ReplicaSet are both in extensions (not apps).

**Comment by abgworrall** [comment]
This PR is about to miss 1.8.0; if you want it included, please get it submitted to master by 7pm tonight, and I'll cherrypick it this evening. I won't be cherrypicking anything on the day of release.

**Comment by abgworrall** [comment]
FWIW, cherrypick is over at #53070

**Pull request merged**
