### PR TITLE
Update to json-patch 4.8.0

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Includes fix for https://github.com/evanphx/json-patch/pull/108 and can be picked to 1.16-1.18

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @logicalhan

### CODE REVIEW

**Comment by liggitt** [comment]
/milestone v1.19

needed to fix a regression in json-patch equality comparison introduced in https://github.com/kubernetes/kubernetes/pull/92069

**Comment by liggitt** [comment]
cc @BenTheElder @aojea on network related flake on ipv6 for visibility: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93810/pull-kubernetes-e2e-kind-ipv6/1292121554452221954

/retest

**Comment by aojea** [comment]
> cc @BenTheElder @aojea on network related flake on ipv6 for visibility: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93810/pull-kubernetes-e2e-kind-ipv6/1292121554452221954
> 
> /retest

:eyes: :thinking: 
> 2020-08-08T15:49:56.424709422Z stdout F [ERROR] plugin/errors: 2 nodeport-service.services-6689.svc.cluster.local.c.k8s-prow-builds.internal. A: dial udp 172.18.0.1:53: connect: network is unreachable

**Comment by aojea** [comment]
is this a new cluster? or are more jobs like this running in this cluster with this domain?
`c.k8s-prow-builds.internal`

**Comment by BenTheElder** [comment]
k8s-prow-builds is a cluster in github.com/kubernetes/k8s.io (the full config is there).

**Pull request merged**
