### PR TITLE
chore: loop optimization

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
should replace loop with podSandboxStats.Linux.Containers = append(podSandboxStats.Linux.Containers, podContainerStats...) (S1011)
#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Basically looks good.

But @testwill now that you're it, could you look for similar pattern in the whole codebase? At a quick grep I found e.g. [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/graph.go#L99), there are probably many other

**Comment by testwill** [comment]
Your idea is correct, I have submitted pr according to OWNERS
e.g [this](https://github.com/kubernetes/kubernetes/pull/118429)

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
