### PR TITLE
kubeadm: simplify fuzzing of ClusterConfiguration

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

- Pin the ClusterConfiguration when fuzzing
the internal InitConfiguration that embeds it. Kubeadm includes
separate constructs for this embedding in the internal type
and this round trip is not viable.
- Remove the artificial calls to SetDefaults_ClusterConfiguration()
in v1beta{2|3}'s converters from public to internal InitConfiguration.
- Make sure the internal InitConfiguration.ClusterConfiguration is
defaulted in initconfiguration.go instead.

#### Which issue(s) this PR fixes:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @fabriziopandini 

this change is rather sketchy but i think it might work.
the embedding of internal ClusterConfiguration in InitConfiguration is proving to be quite problematic and we should log an issue about it eventually.

the diff to clean that up would likely be huge...

i remember that `@rosti` had some ideas about a "config palette" that you did not particularly like.

**Comment by fabriziopandini** [comment]
> this change is rather sketchy but i think it might work. according to unit tests this should not be breaking, so let's hope so...

I think that the resulting code is more consistent and predictable, because defaulting for ClusterConfiguration happens in a similar way than for other types, and also conversion/conversion test are now much simpler having removed a very uncommon call to defaulting.

> the embedding of internal ClusterConfiguration in InitConfiguration is proving to be quite problematic and we should log an issue about it eventually.

I'm +1. I don't remember details of previous discussions about this topic, but happy to reconsider

**Comment by fabriziopandini** [comment]
/lgtm
/hold
to give time for other folks to loop in

**Review by pacoxu — APPROVED** [review]
/lgtm
/hold cancel
I can not think out any side effects of this PR. 🤔

**Pull request merged**
