### PR TITLE
Added owners to monitoring and logging related directories

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by Crassirostris** [comment]
@piosz What about fluentd config files in salt?

**Comment by Crassirostris** [comment]
Fluentd static pod specs*

**Comment by piosz** [comment]
@eparis @jbeda @mikedanese @roberthbailey @zmerlynn can one of you approve the change?

**Comment by piosz** [comment]
@Crassirostris done

**Comment by Crassirostris** [comment]
@piosz I'm not sure that's how it should be done, if possible, because there are no OWNERS files in salt. Looking forward to others' feedback

**Comment by eparis** [comment]
@k8s-bot unit test this

**Pull request merged**
