### PR TITLE
Add label area/hack in k8s.io/kubernetes/hack/*

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Automatically adds the label `area/hack` to all PRs that touch `k8s.io/kubernetes/hack/*`. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
This isn't a label we have. What's the need for it?

**Comment by SataQiu** [comment]
@cblecker 
The purpose of adding this tag is to achieve better PR classification.
This should help us triage testing PRs going forward.

**Comment by cblecker** [comment]
I don't think we need this at this time. Thanks though!

/close

**Pull request closed without merging**
