### PR TITLE
WIP Replicate master

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Add logic for replicating master in HA mode.
#21124

@jszczepkowski

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
Unassigning this PR as it's not ready for review yet.

**Comment by justinsb** [comment]
I thought kube-up was in maintenance mode i.e. no new features?  HA seems like a pretty big one!

**Comment by fgrzadkowski** [comment]
We have discussed it with @roberthbailey and the consensus was that we don't want to wait for a new tool for deployment.

**Comment by roberthbailey** [comment]
@justinsb: kube-up isn't in maintenance mode. It's still the default way to deploy k8s in a production manner (certainly on GCE). We are working (in tandem) on a much smoother getting started experience, but I don't have any qualms adding additional features to kube-up to support more complex deployments (like HA) in the mean time.

**Comment by roberthbailey** [comment]
@fgrzadkowski please ping this PR when it's ready to be reviewed.

**Comment by justinsb** [comment]
Looks like we have to update the README then :-)

https://github.com/kubernetes/kubernetes/tree/master/cluster#deprecation-notice-this-directory-has-entered-maintainence-mode-and-will-not-be-accepting-new-providers-please-submit-new-automation-deployments-to-kube-deploy-deployments-in-this-directory-will-continue-to-be-maintained-and-supported-at-their-current-level-of-support

I think it's going to be very difficult to get HA working on AWS with kube-up.  kops does it though, and I'm happy to talk about what is required and what is merely icing - a lot of it carries over to GCE anyway!

I've also been meaning to get GCE working with kops (with HA support).  It's probably still a few days away, but maybe then we can get official e2e running with kops in HA?

**Comment by jszczepkowski** [comment]
Closing in favor of #29995

**Pull request closed without merging**
