### PR TITLE
fix nodenames slices comparison para.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@MrHohn 
PTAL

**Review by MrHohn — APPROVED** [review]
Ah, can't believe we missed this :(
/lgtm

**Comment by MrHohn** [comment]
ref https://github.com/kubernetes/kubernetes/pull/57930

**Comment by thockin** [comment]
good catch!!

**Comment by zhangxiaoyu-zidif** [comment]
@MrHohn 
sorry, that's my faulty. 
Sincerely apology for that.

**Comment by MrHohn** [comment]
@zhangxiaoyu-zidif No worries, glad that you found it before the release :)

**Comment by thockin** [comment]
We all make bugs.  Can you add a test to cover this?

**Comment by zhangxiaoyu-zidif** [comment]
OK， thanks, I add it at once.

**Pull request merged**
