### PR TITLE
federation-apiserver test: Cleaning up clusters after the test is run

### PR DESCRIPTION
**Pull request by nikhiljindal**
The test was not deleting clusters after it completes

cc @kubernetes/sig-cluster-federation @mml

### CODE REVIEW

**Comment by mml** [comment]
Do we need both?  It seems like the AfterEach stanza deletes everything anyway.

**Comment by nikhiljindal** [comment]
Updated the comment to say that we test that delete works.
We also have AfterEach as a fallback in case test fails before that.

**Comment by quinton-hoole** [comment]
nit: I would make the cluster deletion test a separate one (i.e. a separate "It" clause).

Also, I'm slightly confused.  The cluster deletion in the AfterEach() clause has already been added in:

https://github.com/kubernetes/kubernetes/pull/26636/

?

**Comment by nikhiljindal** [comment]
The one in #26636 is for the clusters that federated-service added.
I havent verified it yet, but the hypothesis that @mml and I discussed is that if federated-service test is run after this test (i.e federation-apiserver test), then when it tries to create clusters it should get an error saying this cluster already exists (since federation-apiserver already created those clusters but did not delete them).
This PR is to prevent that error.

**Comment by quinton-hoole** [comment]
@nikhiljindal My apologies, yes, I was confusing two different sets of tests (federation-apiserver and federation-service).  If we moved both of those into the same test file, we could remove all of the duplicate code.  Besides that, the distinction is rather artificial in the context of e2e tests.  e.g. both create services, it just happens that one person wrote one of them to test api server, and the other to test servicecontroller.

Lets put in a followup PR to merge these two sets of tests.

**Comment by nikhiljindal** [comment]
Adding retest not required label since this PR only affects the federation e2e which is not tested by the merge bot anyway.

**Comment by lavalamp** [comment]
Manual build cop merge.

**Pull request merged**
