### PR TITLE
Getting Started Guide - Ubuntu Two Node Cluster

### PR DESCRIPTION
**Pull request by baldwinSPC**
- created a tutorial on how to setup Ubuntu on two Ubuntu nodes.
- create the ubuntu directory
- moved the single node tutorial into the ubuntu directory

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR.  How different is this from the multi-node ubuntu guide.

I worry about confusing users.  It would be great to combine this with the other ubuntu guide(s)

**Comment by baldwinSPC** [comment]
@brendanburns OK, I see the new one at the root of the getting started folder. In this case, I cover a two-node setup specifically, so perhaps a simple rename from 'multi-node' to 'two-node'. My doc doesn't cover setting up Flannel; however, it does give step by step instructions on everything else. I'd have to read through the other contribution to see where differences are. I can cancel this PR and halt the work on the docs if that's desired, too. If someone else is adding these docs I don't want to cause issues with what they're working on.

I think a broader guide around Ubuntu could be put together that covers all three scenarios. This is something I could begin to put together; however, since things are moving rapidly I would hate to put work into it, like I did with this one, to not see anything merged. Thoughts? Is there a specific list (I looked, but didn't find one) for doc contributions versus bug / feature type of contributions?

**Comment by baldwinSPC** [comment]
CLA was just updated.

**Comment by resouer** [comment]
@baldwinSPC  Great to know there's other guys care about running kuber on bare-metal ubuntu cluster!

I read your commits and technically there seems no too much difference between the existing multi-node part. So could u please consider merge your suggestions to the existing doc?

BTW, we use flannel because we'd  like enable user to use overlay network, it is optional.

**Comment by zmerlynn** [comment]
I'm against this commit because it's too duplicative with the existing
getting started guides.

At the 2015/02 meet-up, we also decided that we're going to stop directly
hosting any getting started guides that can't pass conformance tests
(currently our e2es), possibly with documented exceptions for more minor
pieces.

We haven't finalized the guidelines yet, though; expect to see
communication on that soon.

So if you're interested in pursuing this, I'd probably recommend joining
forces with the other ubuntu-bare-metal folks and helping to make sure the
existing multi-node setup falls within guidelines once they're firmed up.

@baldwinSPC <https://github.com/baldwinSPC> Great to know there's other
guys care about running kuber on bare-metal ubuntu cluster!

I read your commits and technically there seems no too much difference
between the existing multi-node part. So could u please consider merge your
suggestions to the existing doc?

BTW, we use flannel because we'd like enable user to use overlay network,
it is optional.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/pull/4831#issuecomment-76513797>
.

**Comment by baldwinSPC** [comment]
@zmerlynn @resouer @brendandburns Thanks for the feedback. I'll go ahead and cancel this PR and will halt contributing anything until Google has straightened out how documentation is going to be handled. Going forward we'll document on this end for our internal needs and seek to contribute if and when things are better organized. 

Why not have a different repo for documentation with guidelines and a mailing list separate from the other one so we can all be abreast of what type of docs each of us are doing? This would save on wasted cycles. 

@resouer I'll check out your document and see if anything I put together is needed in that document.

**Comment by zmerlynn** [comment]
@baldwinSPC: I apologize if I sounded too harsh there. I actually really appreciate all the cycles you put in and your interest in Kubernetes! There's just a really fine line to toe here: We're trying to make sure that the grid we present users isn't too confusing. Right now, if you're just getting started, https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides is somewhat intimidating, even after all the fine work @erictune put into it. We want it to be clear to users what's supported, and at what level (i.e. what will "just work").

FWIW, the k8s meet-up was more than just Google. We had a large contingent from RedHat, and plenty of other valued community members, including the current owners of the vagrant (RedHat), aws, and azure cloud providers.

We did talk about an entirely separate doc repo and rejected it. We want to keep docs together with source because we still value atomic changesets. We have several providers (gce, gke, vagrant, aws, azure, rackspace, etc.) that are automatically deployable, and guides for those providers should be editable at the same time as the source is modified (even if it doesn't happen as often as it should). There are plenty of other docs that we want to modify alongside the source. At the end of the day, we decided that it's easy enough for us to pull the doc tree for a particular release branch out and publish it on a sidebar for that release of kubernetes.io (even if that's not yet done).

We will likely start supporting smaller getting started guides using links on our wiki. (One of the first to be oved there will likely be the single-node ubuntu setup, actually, because we know there's no way it will pass conformance tests.)

**Comment by resouer** [comment]
@zmerlynn We are very willing to pushing kubernetes much easier on bare-metal as "standard" IaaS providers are rare in real market. Especially in container world, people are willing to run Docker on bare-metal servers for some "performance" and cost reason. We'd like to achieve something that real work, instead of can work, a standard and full version of kuber on bare-metal servers.

We are now working on leverage kuber on bare-metal cluster fully automatically (only require addresses  of target servers) based on previous ubuntu-cluster PR. So, could u please give me tips about what we community contributors can do to keep bare-metal setup as part of kuber plan (for example, how to pass e2e tests)?

**Pull request closed without merging**
