### PR TITLE
Add reviewable notes to CONTRIBUTING

### PR DESCRIPTION
**Pull request by thockin**
@kubernetes/contributor-experience

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36634)

### CODE REVIEW

**Comment by thockin** [comment]
ping - simple docs PR

**Comment by apelisse** [comment]
Sorry for the lag.

@grodrigues3 FYI. We may have this section updated when we update the process?

**Comment by derekwaynecarr** [comment]
@thockin -- thanks for capturing this from kubecon.

**Comment by philips** [comment]
LGTM, thanks thockin.

**Comment by philips** [comment]
I still need to record a video cast of reviewing using reviewable, watching Thockin for just a half an hour was too helpful. I imparted knowledge to the wider CoreOS team too.

**Comment by thockin** [comment]
want to get together and prep a good PR and do a live review and record?

**Comment by philips** [comment]
@thockin Sure on the video. But, what do you mean by "good PR"?

**Comment by thockin** [comment]
Find or make a pull-request that will best demonstrate what value
reviewable offers.  Large, many files, several edits, etc.

**Pull request merged**
