### PR TITLE
Automated cherry pick of #59291: Remove validation failure of Pod priority when the feature is disabled

### PR DESCRIPTION
**Pull request by ghost**
Cherry pick of #59291 on release-1.9.

#59291: Remove validation failure of Pod priority when the feature is disabled

### CODE REVIEW

**Comment by mbohlool** [comment]
please add a test

**Comment by vainu-arto** [comment]
@mbohlool Do note that this is a cherrypick of a change that has been merged to master and included in releases. I also had no role in the writing of this code, I'd simply benefit from having it usable in releases other than 1.10.

**Comment by mbohlool** [comment]
@vainu-arto it is fine then. It, however, needs usual lgtm/approvals. Please ping appropriate reviewers. tomorrow is the deadline for the next release. thanks.

**Comment by vainu-arto** [comment]
@bsalamat @liggitt @tallclair Can you check that this is ok to apply to 1.9?

**Pull request closed without merging**
