### PR TITLE
Merge release 0.14.1 to master

### PR DESCRIPTION
**Pull request by zmerlynn**

### CODE REVIEW

**Comment by zmerlynn** [comment]
Git contortions to get the tag to be an ancestor, per @eparis.

**Comment by bprashanth** [comment]
assuming @epairs is ok with the review

**Comment by zmerlynn** [comment]
(github is truly horrible at visualizing this. "Files changed" shows one delta and the commit list is 6 long, which is pretty amusing.)

**Comment by eparis** [comment]
I'd argue github is being awesome visualizing this, it showed you the only changes you actually made to master!  Woo, looks great.

**Pull request merged**
