### PR TITLE
Make discovery summarizer call servers in parallel

### LINKED ISSUE #26704: Parallelize API calls in discovery summarizer
// TODO: We can cache and parallelize the calls to all servers.

### PR DESCRIPTION
**Pull request by nebril**
fixes #26704

### CODE REVIEW

**Comment by nikhiljindal** [comment]
ok to test

**Comment by nikhiljindal** [comment]
ok to test

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
Unit tests failed on Jenkins with the following log:
```
Verifying ./hack/../hack/verify-gofmt.sh
!!! 'gofmt -s -w' needs to be run on the following files: 
./cmd/kubernetes-discovery/discoverysummarizer/discoverysummarizer.go
FAILED   ./hack/../hack/verify-gofmt.sh	9s
Verifying ./hack/../hack/verify-govet.sh
cmd/kubernetes-discovery/discoverysummarizer/discoverysummarizer.go:110: range variable serverAddress captured by func literal
exit status 1
!!! Error in ./hack/../hack/verify-govet.sh:49
  'go vet "${goflags[@]:+${goflags[@]}}" ${targets[@]}' exited with status 1
Call stack:
  1: ./hack/../hack/verify-govet.sh:49 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-govet.sh	260s
```

@nebril Can you please fix?

**Comment by nebril** [comment]
Sure, will fix. Thanks for the help!

**Comment by wojtek-t** [comment]
@nebril - friendly ping; can you please fix it?

**Comment by nebril** [comment]
@wojtek-t yeah, it got stuck in my backlog. Will try to fix tests tomorrow, thanks for the ping!

**Comment by nebril** [comment]
@nikhiljindal fixed!

**Comment by nebril** [comment]
@nikhiljindal can I bother you for lgtm on this before I need to rebase it? :)

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Pull request merged**
