### PR TITLE
Move stats summary types to a new kubelet/api package to avoid unnece…

### PR DESCRIPTION
**Pull request by timstclair**
…ssary dependencies

This is to avoid pulling most of kubernetes into heapster just for the stats API. The `v1alpha1` designation is mostly to demonstrate that we don't intend to support this API indefinitely.

/cc @dchen1107 @vishh

### CODE REVIEW

**Comment by timstclair** [comment]
Forgot the e2e_node test again (fixed)

**Comment by vishh** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Comment by timstclair** [comment]
@k8s-bot e2e test this, issue #IGNORE

**Comment by eparis** [comment]
Why was this self labeled as priority/p1? I see no justification. No bug. No explanation why this is more important than any other PR. I'm moving to p2 to let higher priority bug fixes in first, but I'm not sure why it was labeled at all. We can't just use priority to skip the queue, fixing the flakes works better.

**Comment by timstclair** [comment]
Sorry for not providing any justification: this is blocking a 1.2 feature.

**Comment by dchen1107** [comment]
Yes, we marked this as p1 because it blocks a 1.2 features.

**Pull request merged**
