### PR TITLE
E2E import aliases

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

All E2E framework sub packages should be imported consistently as `e2e<sub package>`, without having to update `hack/.import-aliases` each time a new sub package gets created.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

thanks for fixing this @pohly

**Comment by pohly** [comment]
Are there any plans to apply this tool more widely? Right now it only checks files under test/e2e.

**Comment by dims** [comment]
@pohly https://kubernetes.slack.com/archives/CHGFYJVAN/p1557525053121100 has previous discussion ( thanks @liggitt ) we are gonna hold this to status quo!

**Pull request merged**
