### PR TITLE
Automated cherry pick of #124675: Adding a deprecating featurer gate to fix cost

### PR DESCRIPTION
**Pull request by cici37**
Cherry pick of #124675 on release-1.30.

#124675: Adding a deprecating featurer gate to fix cost

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Added the feature gates `StrictCostEnforcementForVAP` and `StrictCostEnforcementForWebhooks` to enforce the strct cost calculation for CEL extended libraries. It is strongly recommended to turn on the feature gates as early as possible. 
```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @liggitt 
FYI: This is the cherry-pick PR opened for 1.30. Thanks!

**Comment by cici37** [comment]
Updates: I have squashed the commits since the additional changes are only for testing updates between 1.30 and 1.31. Thanks

**Comment by cici37** [comment]
@kubernetes/release-managers 
Would you mind approving the cherry pick so it could get into the next 1.30 minor release? Thank you!

**Comment by cici37** [comment]
Added the release notes.

**Review by Verolop — COMMENTED** [review]
/lgtm
(release managers)

**Pull request merged**
