### PR TITLE
api/authentication: remove omitempty for Authenticated field in TokenReviewStatus

### LINKED ISSUE #118313: Authenticated field in api/authentication/v1beta1TokenReviewStatus object is omitempty when it is needed to be false
### What happened?

Since the field is bool and its tag has 'omitempty', it is impossible to set it to false and perform JSON marshalling. For example, when sending [response](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication) to KubeAPI server from a webhook-token service, if the user is not authorized, 'Authenticated' should be false, but the tag prevents serialization of the field into JSON string.

### What did you expect to happen?

Either 'omitempty' be removed or set Authenticated as *bool instead of bool

### How can we reproduce it (as minimally and precisely as possible)?

Status := v1beta1.TokenReviewStatus{Authenticated: false, User: v1beta1.UserInfo{Username: "test"}}
StrStatus = json.Marshal(Status)
fmt.Println(StrStatus)                    // Authenticated field is omitted due to omitempty

### Anything else we need to know?

k8s.io/api/authentication.k8s.io/v1 also has the same issue

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

M/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

If applied this commit will remove the `omitempty` from the `Authenticated` field in `TokenReviewStatus`

#### Which issue(s) this PR fixes:

Fixes #118313 

#### Does this PR introduce a user-facing change?

```release-note
api/authentication/v1beta1TokenReviewStatus: Authenticated field can be set to false
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
/release-note-edit "api/authentication/v1beta1TokenReviewStatus: Authenticated field can be set to false"

**Comment by liggitt** [comment]
If the field is absent from the serialized content, it is treated as false. Is this fixing a bug or trying to improve usability of the API type? The only question I have is what dropping `omitempty` will do to generated clients... do any of the clients generate in ways that would break if they receive a server response from an old server without that field present?

**Comment by TommyStarK** [comment]
> If the field is absent from the serialized content, it is treated as false. Is this fixing a bug or trying to improve usability of the API type? The only question I have is what dropping `omitempty` will do to generated clients... do any of the clients generate in ways that would break if they receive a server response from an old server without that field present?

I assume this is for trying to improve the usability of the API type. As reported in #118313, the following code will omit the `Authenticated` field:

```go
status := v1beta1.TokenReviewStatus{Authenticated: false, User: v1beta1.UserInfo{Username: "test"}}
b, _  := json.Marshal(status)
fmt.Println(string(b)) // {"user":{"username":"test"}} Authenticated field is omitted due to omitempty
```

Regarding generated clients, I cannot answer at the moment, need to test it. My first guess would be they should be impacted if they are converting the result of json marshalling to a string.

**Pull request closed without merging**
