### PR TITLE
expose etcd wal dir and allow customizing it with kubeadm

### PR DESCRIPTION
**Pull request by chenzhiwei**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:

This PR is used to expose etcd wal directory and allow customizing it.

Some of the enterprise users already have it separated from etcd data dir.

From the Etcd official document: https://github.com/etcd-io/etcd/blob/v3.2.17/Documentation/v2/admin_guide.md#lifecycle

> Having a dedicated disk to store wal files can improve the throughput and stabilize the cluster. It is highly recommended to dedicate a wal disk and set `--wal-dir` to point to a directory on that device for a production cluster deployment.

**Which issue(s) this PR fixes**:

Related issue: https://github.com/kubernetes/kubeadm/issues/683

**Special notes for your reviewer**:

We want to leverage kubeadm in our product, this is a gap we need to fill.

/area kubeadm
sig/cluster-lifecycle

/assign @neolit123
/assign @rosti 

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: allow customizing local Etcd wal(write ahead log) directory
```

### CODE REVIEW

**Review by rosti — COMMENTED** [review]
Hi @chenzhiwei and thanks for your contribution!
Unfortunately we can't add new fields to v1beta1 and adding the proposed field to v1beta2 does look a bit unfeasible to me.
We strive for simplicity and thus are careful not to overpopulate the config format.
In your case, the same result can be achieved by pre-creating the `/var/lib/etcd/member/wal` path and then mount the new volume there or use a symlink if it's already mounted.
After that, you can use kubeadm init/join.

**Comment by chenzhiwei** [comment]
ok, i know there are multiple ways to implement: bindmount or etcd
extraargs.

it will be great if this can be a part of the pre-defined config option.

**Comment by chenzhiwei** [comment]
@rosti separate the wal directory is also a part of CIS compliance, do you still think it is unfeasible?

* Ensure that the `--wal-dir` argument is set as appropriate
* Ensure that the --max-wals argument is set to 0

**Comment by neolit123** [comment]
we had discussions and vote on what new fields can make it in v1beta2:
https://github.com/kubernetes/kubeadm/issues/1439
(i.e. the process is slightly more complex)

maybe it can be discussed for v1beta3, but as far as the CIS compliance goes we are going to have series of reviews over the CIS report. the kubeadm maintainers and some of our affiliate security experts do not exactly agree with parts of the CIS report.

**Comment by chenzhiwei** [comment]
close this now, maybe re-open or re-submit new PRs after discussion of v1beta2.

**Pull request closed without merging**
