### PR TITLE
Don't make kubelet systemd service depend on Docker

### LINKED ISSUE #10379: Circular dependency between kubelet <- docker <- cbr0 <- kubelet on systemd
On systemd, Docker depends on cbr0:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/docker/docker-defaults#L5

cbr0 is now created by kubelet (after https://github.com/GoogleCloudPlatform/kubernetes/pull/10312)

But kubelet depends on Docker: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kubelet/kubelet.service#L5

I'm a bit confused about how to break this loop (if it is even a loop).  What I'm seeing is that Docker can't start, but then kubelet fails to start because of the docker dependency.

### PR DESCRIPTION
**Pull request by justinsb**
Fixes #10379 

This also requires a modified Docker systemd unit file, which attempts to restart indefinitely.  I'm doing that as part of #9381

### CODE REVIEW

**Comment by roberthbailey** [comment]
@dchen1107 @thockin The referenced bug isn't part of the 1.0 milestone so I've marked it as 1.0-candidate. Please take a look.

**Comment by dchen1107** [comment]
@roberthbailey I moved that one to 1.0. This extra dependency creates a circular dependencies at node bootup time for systemd node. It doesn't affect GCE / GKE with debian image, but definitely breaks some other cloud providers.

**Comment by dchen1107** [comment]
LGTM

**Comment by zmerlynn** [comment]
LGTM, seems like the right dep to break.

**Comment by roberthbailey** [comment]
Thanks @dchen1107. Assigning to @alex-mohr to take a look and give ok-to-merge.

**Comment by roberthbailey** [comment]
Shippable seems to have failed for this PR (again).

**Comment by alex-mohr** [comment]
Shippable is completely broken for last N hours: https://app.shippable.com/

**Comment by alex-mohr** [comment]
(Or at least our project's build on shippable, that is.)

**Comment by derekwaynecarr** [comment]
I have not been able to follow the full issue here, but if Docker is not running, I assume the Kubelet does not error?  Also is the Kubelet now stopping or starting Docker, or only when it creates a bridge if requested to do so?  I thought at one point we had code that waited for Docker to be available at Kubelet startup.  Maybe I am misremembering, but if we do will that code wait forever?

**Comment by dchen1107** [comment]
Ahh, we should patch our v0.20.1 with this pr too; otherwise systemd node is broken.

**Comment by alex-mohr** [comment]
@dchen1107 Too late for 0.20.1.  Presumably could be a 0.20.2 -- perhaps tomorrow? #10409 to track.

**Pull request merged**
