### PR TITLE
remove statefulset scaling down before scale up test

### LINKED ISSUE #47376: Test Failure: Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait
Test: Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed

[jenkins log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-scaling-down-before-scale-up-is-finished-should-wait-until-current-pod-will-be-running-and-ready-before-it-will-be-removed)  (search for test string)

[history](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/)

/sig scalability
/assign @lavalamp

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**: This PR skips v1.6 test named "Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed" to ensure the 1.6-1.7 upgrade test passes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47376 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kow3ns** [comment]
\approve

**Review by kow3ns — APPROVED** [review]
/lgtm

**Comment by kow3ns** [comment]
@dchen1107 we need a cherry pick approval to merge against the release

**Comment by crimsonfaith91** [comment]
@kow3ns noted! thanks for the approvals :)

**Pull request merged**
