### PR TITLE
Bump DynamicKubeConfig metric deprecation to 1.23

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Bumps the deprecation of these metrics one release so our tests stop failing because there is no way to specify unhiding of metrics in node-e2e tests currently. See https://github.com/kubernetes/kubernetes/issues/103879#issuecomment-888429606

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by ehashman** [comment]
/assign @smarterclayton 
PTAL

**Comment by SergeyKanzhelev** [comment]
it looks like this is a problem in master as failures started around the time of [this tag creation](https://github.com/kubernetes/kubernetes/releases/tag/v1.23.0-alpha.0). See: https://kubernetes.slack.com/archives/C0BP8PW9G/p1627491145256600

So it would be great to merge this in master as a temporary fix, but not cherry-pick to 1.22.

**Pull request merged**
