### PR TITLE
Automated cherry pick of #44590

### PR DESCRIPTION
**Pull request by cjcullen**
Cherry pick of #44590 on release-1.6.

#44590: When changing basic auth creds, just delete the whole

### CODE REVIEW

**Comment by gmarek** [comment]
Ugh.. I guess asking for sqashing commits on cherry pick is considered wrong?
@k8s-bot verify test this

**Comment by gmarek** [comment]
@cjcullen it seems that `verify-federation-openapi-spec.sh` is really unhappy. Please fix.

**Comment by ihmccreery** [comment]
```
I0515 23:06:47.999] /go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh
```

**Comment by ihmccreery** [comment]
> Ugh.. I guess asking for sqashing commits on cherry pick is considered wrong?

Yeah, sorry about that.  Still getting reacquainted with the GitHub workflow.

**Comment by enisoc** [comment]
@k8s-bot verify test this

**Pull request merged**
