### PR TITLE
fix typo (succesfulJobs -> successfulJobs)

### PR DESCRIPTION
**Pull request by tedli**
**What this PR does / why we need it**:

fix typo, for ones who are willing to do further contributions have a better understanding of the code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

NONE

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tedli** [comment]
cla signed

**Comment by tedli** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

cla signed

**Comment by soltysh** [comment]
@tedli thank you for you contribution, but I'd prefer this change by accompanied by an actual code change (a fix) or test addition.

**Comment by tedli** [comment]
> @tedli thank you for you contribution, but I'd prefer this change by accompanied by an actual code change (a fix) or test addition.

Thanks for reply, I see, I will try to add some nontrivial test case。

**Pull request closed without merging**
