### PR TITLE
api: fix ValidatingAdmissionPolicyList json tag

### LINKED ISSUE #1593: kubectl returns kind: ValidatingAdmissionPolicyList for empty list of policies
### What happened?

There is a cosmetic inconsistency of `kubectl get validatingadmissionpolicies -o yaml` output for empty and non-empty list of validating admission policies.

If there are no policies:
```yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingAdmissionPolicyList
  metadata:
    resourceVersion: "3817"
kind: List
metadata:
  resourceVersion: ""
```

If there is at least one policy:
```yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingAdmissionPolicy
  ...
kind: List
metadata:
  resourceVersion: ""
```

### What did you expect to happen?

If there are no validating admission policies, `kubectl get validatingadmissionpolicies -o yaml` is expected to output:

```
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
```

### How can we reproduce it (as minimally and precisely as possible)?

Run `kubectl get validatingadmissionpolicies -o yaml` provided that there are no validating admission policies in the cluster.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>
bare-metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8s-control-plane-1 5.15.0-50-generic kubernetes/kubernetes#56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd=1.6.12-0ubuntu1~22.04.3
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.27.0
</details>

### PR DESCRIPTION
**Pull request by xyz-li**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Change the output  when validatingadmissionpolicies is empty.
kubectl get --raw /apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies  
```
{
  "kind": "ValidatingAdmissionPolicyList",
  "apiVersion": "admissionregistration.k8s.io/v1",
  "metadata": {
    "resourceVersion": "30603"
  }
}
```
kubectl get --raw /api/v1/nodes 
```
{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "30721"
  },
  "items": []
}
```

#### Which issue(s) this PR fixes:

Fixes [#1593](https://github.com/kubernetes/kubectl/issues/1593)
#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug in the API server where empty collections of ValidatingAdmissionPolicies did not have an `items` field.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-This change make api-server not omity the field `item` of ValidatingAdmissionPolicyList when ValidatingAdmissionPolicy is empty.
+Fixed a bug in the API server where empty collections of ValidatingAdmissionPolicies did not have an `items` field.
```

**Comment by sftim** [comment]
BTW, the response to a **list** is formally a _collection_.

**Comment by cici37** [comment]
Would you mind making it consistent for all version like v1alpha1 and v1beta1? Thanks

**Comment by xyz-li** [comment]
kindly ping @cici37

**Comment by xyz-li** [comment]
https://github.com/kubernetes/kubectl/issues/1593#issuecomment-2172929184

**Comment by liggitt** [comment]
@deads2k @jpbetz this looks like an opportunity for a follow-up that adds a systemic test to catch / prevent this in the future

**Comment by liggitt** [comment]
verify job flagged generated bits that need updating, `hack/update-codegen.sh` and maybe others

**Comment by liggitt** [comment]
/lgtm
/approve

this seems worthwhile to pick to 1.30 if you can open a PR

**Comment by xyz-li** [comment]
> @deads2k @jpbetz this looks like an opportunity for a follow-up that adds a systemic test to catch / prevent this in the future

How about this? #126286 126286

**Pull request merged**
