### PR TITLE
Mount master-pd in kubemark

### LINKED ISSUE #35020: Kubemark is not mounting master disk
While running kubemark tests we are facing "no space left on device" problems, because master-disk is not mounted in kubemark.

### PR DESCRIPTION
**Pull request by gmarek**
Fix #35020

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35024)

### CODE REVIEW

**Comment by wojtek-t** [comment]
lgtm

**Comment by wojtek-t** [comment]
@gmarek - kubemark tests failed; this seems related. Can you please take a look?

**Comment by gmarek** [comment]
ugh. no logs...

**Comment by gmarek** [comment]
@k8s-bot kubemark gce test this issue: #IGNORE
I need to have a running test to debug this.

**Comment by gmarek** [comment]
@k8s-bot kubemark test this issue: #IGNORE
I need to have a running test to debug this.

**Comment by gmarek** [comment]
Kubemark failure was:
```
F1018 09:50:51.887536    2954 client_builder.go:163] unable to get token for service account: error watching
```
which IIUC is the problem with metadata server.

**Comment by gmarek** [comment]
@k8s-bot gci gke test this issue: #IGNORE
full metadata in the project

**Pull request merged**
