### PR TITLE
Automated cherry pick of #76923: fix validation message: apiServerEndpoints ->apiServerEndpoint

### PR DESCRIPTION
**Pull request by SataQiu**
Cherry pick of #76923 on release-1.14.

#76923: fix validation message: apiServerEndpoints -> apiServerEndpoint

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @SataQiu 

/lgtm
/priority important-soon

**Review by neolit123 — COMMENTED** [review]
we only approved the backport to 1.14.

/lgtm
/approve
/milestone 1.14
/assign @tpepper 

@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by SataQiu** [comment]
@neolit123 @yagonobre  @timothysc This PR has been waiting for a long time. 
Can it be merged now ? And what else do I need to do?

**Comment by neolit123** [comment]
@SataQiu 
cherry picks are slower. it has a milestone and the correct labels so it should be picked at some point.

**Pull request merged**
