### PR TITLE
scheduler remove init method

### LINKED ISSUE #29255: kube-scheduler can remove the healthz.DefaultHealthz()
@davidopp IIUC, the [init](https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/scheduler.go#L30) could be removed, `healthz.DefaultHealthz()` is useless here actually.

### PR DESCRIPTION
**Pull request by adohe-zz**
Fix #29255 , @davidopp ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29606)

### CODE REVIEW

**Comment by dims** [comment]
Looks good to me 👍

**Comment by AdoHe** [comment]
@davidopp kindly ping.

**Comment by AdoHe** [comment]
@davidopp kindly ping on this, if this is not ok, I can close it.

**Comment by davidopp** [comment]
Can you explain the reason for removing it?

**Comment by AdoHe** [comment]
@davidopp as I explained in this issue #29255, ptal.

**Comment by AdoHe** [comment]
@davidopp shall we close this?

**Comment by dims** [comment]
@AdoHe : let's wait for @davidopp's input

**Comment by davidopp** [comment]
Reassigning to @wojtek-t as I don't know if this code is actually necessary or not.

**Comment by AdoHe** [comment]
Thanks @davidopp.

**Comment by AdoHe** [comment]
@wojtek-t ptal.

**Comment by wojtek-t** [comment]
@AdoHe - to be honest, you didn't explain __why__ it can be removed in the issue. Anyway, this PR is correct, as health endpoint is registered here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/app/server.go#L102

@AdoHe - please rebase this PR and I will apply lgtm label.

**Comment by AdoHe** [comment]
```
to be honest, you didn't explain why it can be removed in the issue.
```
@wojtek-t my fault, sorry about this.

**Comment by AdoHe** [comment]
@wojtek-t rebased, ptal.

**Comment by AdoHe** [comment]
@k8s-bot kops aws e2e test this

**Comment by wojtek-t** [comment]
@AdoHe - kops is broken and is not required by merge bot.

**Pull request merged**
