### PR TITLE
simplify logic around LB deletion for servicecontroller

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**: simplify logic around LB deletio

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: discovered when aswering to #50299

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by yastij** [comment]
ping @bowei

**Review by MrHohn — APPROVED** [review]

**Comment by MrHohn** [comment]
Thanks for the PR :)

/ok-to-test
/lgtm

**Comment by yastij** [comment]
@derekwaynecarr @deads2k or @mikedanese PTAL when you have time, needs approval, thanks !

**Pull request merged**
