### PR TITLE
AWS: Change default networking for kube-up to kubenet

### PR DESCRIPTION
**Pull request by zmerlynn**
**What this PR does / why we need it**: Fixes AWS bring-up. Again.

There's a kubelet bug that prevents NETWORK_PROVIDER=none from working right now, and we should migrate AWS to `kubenet` anyways.

Working on reproing the `none` issue on GCE, then I'll file a bug on the main issue. But this fixes AWS, so quick tactical fix.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32239)

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM

**Comment by justinsb** [comment]
@k8s-bot test this #IGNORE

**Comment by pwittrock** [comment]
@zmerlynn Does this fix the aws tests?  Please provide a risk assessment for this and perform manual QA in the first beta that contains it.

**Comment by pwittrock** [comment]
1.  Please provide a risk assessment in the description

2. How critical is this?  blocking / important / best effort?  We have dozens of cherrypick requests and each one creates a lot of overhead because large batches introduce a high-risk of destabilizing the tests in a way that is hard to track down.   We have to break them up into smaller batches and monitor the tests to catch issues early on and track them back to their root cause.

**Pull request merged**
