### PR TITLE
Pipe clusterID into gce_loadbalancer_external.go

### LINKED ISSUE #48002: Make gce_loadbalancer_external and gce_loadbalancer_internal more consistent
Recently there was a great refactoring that separates GCE ELB and ILB codes (https://github.com/kubernetes/kubernetes/pull/46663). It constructed GCE cloud provider package in a much better way, but meanwhile some inconsistencies need to be cleaned up. For instance, we should pipe in clusterID in [some places](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_loadbalancer.go#L134-L139):
```
...
			switch existingScheme {
			case schemeInternal:
				err = gce.ensureInternalLoadBalancerDeleted(clusterName, clusterID, svc)
			default:
				err = gce.ensureExternalLoadBalancerDeleted(clusterName, svc)
			}
...
```

/assign
/area platform/gce
/sig network

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**: Small cleanup for GCE ELB codes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48002

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Oops, forgot to assign.
/assign @nicksardo

**Comment by nicksardo** [comment]
Awesome. 
/lgtm

**Comment by MrHohn** [comment]
Thanks!

/assign @bowei 
for approval.

/unassign @fabianofranz @derekwaynecarr

**Comment by bowei** [comment]
Is this part of a bigger change? I don't the clusterID actually being used anywhere.

/approve

**Comment by MrHohn** [comment]
@bowei Thanks. Nope, clusterID is already used in couple places like https://github.com/MrHohn/kubernetes/blob/be6bb318aae036eacee3cb1d97f911b893314054/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L240 and https://github.com/MrHohn/kubernetes/blob/be6bb318aae036eacee3cb1d97f911b893314054/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L282 :)

**Pull request merged**
