### PR TITLE
kube-controller-manager: finish conversion to contextual logging

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Migrate pkg/controller/podgc to structured and contextual logging and clean up some left-over log calls in other controllers.

#### Which issue(s) this PR fixes:

Related-to: https://github.com/kubernetes/enhancements/issues/3077

#### Does this PR introduce a user-facing change?
```release-note
Migrated the podgc controller and some other remaining log calls within `kube-controller-manager` to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging). `kube-controller-manager` is now converted completely.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
-[KEP]: https://github.com/kubernetes/enhancements/issues/3077
```

### CODE REVIEW

**Comment by pohly** [comment]
WIP because https://github.com/kubernetes/kubernetes/pull/119147 needs to be merged first.

**Comment by mengjiao-liu** [comment]
contextual logging migration is almost LGTM.

pull-kubernetes-verify CI job failed and needs to fix it.
```
E0712 09:35:53.270251  204511 main.go:41] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kubernetes/cmd/cloud-controller-manager":
the following imports did not match any allowed prefix:
  k8s.io/kubernetes/test/utils/ktesting
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-import-boss.sh	179s
```

**Comment by mengjiao-liu** [comment]
> WIP because #119147 needs to be merged first.

#119147 has been merged, so you can rebase this PR.

**Comment by pohly** [comment]
@mengjiao-liu: Rebased, please review.

**Comment by mengjiao-liu** [comment]
`./hack/verify-import-boss.sh` script run to report the above error(https://github.com/kubernetes/kubernetes/pull/119250#issuecomment-1632217804) when I run locally.
Waiting for CI job  pull-kubernetes-verify result.

**Review by shivanshuraj1333 — APPROVED** [review]
LGTM, thanks!

**Comment by shivanshu1333** [comment]
/assign soltysh for approval.
@soltysh can you please take a look?
thanks!

**Comment by shivanshu1333** [comment]
/assign @soltysh  for approval.
@soltysh can you please take a look?
thanks!

**Review by soltysh — APPROVED** [review]
/approve

**Comment by pohly** [comment]
/assign @thockin 

For approval of https://github.com/kubernetes/kubernetes/pull/119250/files#diff-726841cc847bdab9e67cd536b0fdce756b0da0d9028347c2fe9f70d73d9951ab

**Review by andrewsykim — COMMENTED** [review]
/approve

For cmd/cloud-controller-manager

**Pull request merged**
