### PR TITLE
Fix cassandra ready-probe.sh

### PR DESCRIPTION
**Pull request by sergeydobrodey**
**What this PR does / why we need it**: 
Cassandra container status check reports confusing info

**Release note**: 
```release-note
NONE
```

### CODE REVIEW

**Comment by sergeydobrodey** [comment]
I signed it!

**Review by chrislovecnm — APPROVED** [review]
LGTM

**Review by chrislovecnm — CHANGES_REQUESTED** [review]
We are going to need to bump the container version as well to get these changes in. Documentation as well. Please update the examples, docs and container version in the Makefile

**Comment by chrislovecnm** [comment]
So the changes looks great the container needs to be updated as well though.  @bgrant0607 who can update the container in gcr.io?

**Comment by sergeydobrodey** [comment]
I signed it!

**Comment by sergeydobrodey** [comment]
I've updated the container version.

**Comment by sergeydobrodey** [comment]
What's wrong? I've run bazel-test and all(464) test cases passed

**Comment by chrislovecnm** [comment]
@erictune @bgrant0607 @viglesiasce who can assist building and uploading the v12 Cassandra container version into gcr.io?

**Comment by chrislovecnm** [comment]
@sergeydobrodey we need to get the image into gcr.io, and then we need to run e2e.

**Comment by sergeydobrodey** [comment]
@chrislovecnm thank you for the clarification.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@zmerlynn can you push the images for this?

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by zmerlynn** [comment]
@chrislovecnm: Let me see if I have access to `gcr.io/google-samples`.

**Comment by chrislovecnm** [comment]
@sergeydobrodey really appreciate your patience with this!  Upon @zmerlynn building the container we have determined that we need an overhaul on the Dockerfile.  We cannot get the current container to build since it is dated.  

Have opened this as a blocker https://github.com/kubernetes/kubernetes/issues/40435

**Comment by sergeydobrodey** [comment]
It's nice that my minor improvements identified another problem

**Comment by zmerlynn** [comment]
@chrislovecnm: Ping me when the dependent bug is resolved.

**Comment by chrislovecnm** [comment]
@sergeydobrodey just pushed https://github.com/kubernetes/kubernetes/pull/42113 with our changes.  Should we close this?

**Comment by sergeydobrodey** [comment]
ok

**Pull request closed without merging**
