### PR TITLE
Disable guestbook test for non-gce|gke due to "createExternalLoadBalancer": true

### PR DESCRIPTION
**Pull request by timothysc**
Another disable as I work through the tests. 
cc @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
Where are you running the e2e tests? This may work on other providers (e.g. AWS). /cc @justinsb

**Comment by timothysc** [comment]
bare-metal test cluster 
provider = local

**Comment by timothysc** [comment]
@roberthbailey I grok'd through cloudprovider and it didn't appear so atm.

**Comment by roberthbailey** [comment]
SGTM. I'll let other cloud providers re-add this test once it's working for them.

**Pull request merged**
