### PR TITLE
update Feature:NodeLease in kube_features.go

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind documentation

**What this PR does / why we need it**:
update the Feature:NodeLease information in kube_features.go

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for helping keep documentation up to date.

Could you please point me to the Changelog entry for this feature graduating to beta? I can't find any record of this in the 1.14 changelog.

If it has migrated to beta, should we also update https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/?

**Comment by mysunshine92** [comment]
> 
> 
> Thanks for helping keep documentation up to date.
> 
> Could you please point me to the Changelog entry for this feature graduating to beta? I can't find any record of this in the 1.14 changelog.
> 
> If it has migrated to beta, should we also update https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/?

please look at this PR: https://github.com/kubernetes/kubernetes/pull/72096
Promote NodeLease to Beta and enable by default.
i will update 1.14 changelog, and this document:https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by mysunshine92** [comment]
cc @derekwaynecarr

**Comment by mattjmcnaughton** [comment]
> > Thanks for helping keep documentation up to date.
> > Could you please point me to the Changelog entry for this feature graduating to beta? I can't find any record of this in the 1.14 changelog.
> > If it has migrated to beta, should we also update https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/?
> 
> please look at this PR: #72096
> Promote NodeLease to Beta and enable by default.
> i will update 1.14 changelog, and this document:https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Sounds good :)
/lgtm

**Comment by wojtek-t** [comment]
/approve

Thanks!

**Pull request merged**
