### PR TITLE
add unit tests

### PR DESCRIPTION
**Pull request by nilskch**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR adds some unit tests.

#### Special notes for your reviewer:
I love k8s and I cloned the repo today for the first time and had a first look on the code. I would love to really contribute in the future, but this is my first contribution to a big open source project ever. Please accept my PR :)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@nilskch please, [sign the CLA](https://github.com/kubernetes/community/blob/master/CLA.md) to proceed further with this PR.

Also, please consider reading [contributors guide](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md) to get familiar with the project, thanks.

**Comment by nilskch** [comment]
`/easycla`

**Comment by nilskch** [comment]
@bart0sh I signed the CLA but the commands to check the CLA seem to not work. What should I do next?

**Comment by bart0sh** [comment]
Another idea is to rebase this PR branch and push it again. This should re-trigger all checks including EasyCLA one.

**Comment by nilskch** [comment]
@bart0sh I am really sorry, my local git config was wrong. I opened a new PR and committed the same code with the correct local git config. Please have a look on this PR: https://github.com/kubernetes/kubernetes/pull/116306

**Pull request closed without merging**
