### PR TITLE
Remove some unnecessarily gendered pronouns in comments

### PR DESCRIPTION
**Pull request by liztio**
**What this PR does / why we need it**:

A bunch of comments are unnecessarily gendered. I've changed them to gender-neutral they/theirs.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/approve

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
