### PR TITLE
In cluster size autoscaling tests, use allocatable instead of capacity for node memory

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
This makes cluster size autoscaling e2e tests use node allocatable resources when computing how much memory we need to consume in order to trigger scale up/prevent scale down. It should fix failing tests in GKE.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
This is definitely the right thing to do and we should merge it, but on GKE it used to be that capacity == allocatable. Has that changed?

**Comment by aleksandra-malinowska** [comment]
@MaciekPytel Yes, it changed recently (at least in test env.) From failing test log:

```
I0917 20:05:28.334]                 "allocatable": {
I0917 20:05:28.334]                     "cpu": "1930m",
I0917 20:05:28.334]                     "memory": "5784880Ki",
I0917 20:05:28.334]                     "pods": "110"
I0917 20:05:28.334]                 },
I0917 20:05:28.334]                 "capacity": {
I0917 20:05:28.335]                     "cpu": "2",
I0917 20:05:28.335]                     "memory": "7664944Ki",
I0917 20:05:28.335]                     "pods": "110"
I0917 20:05:28.335]                 },
```

**Comment by MaciekPytel** [comment]
@aleksandra-malinowska Cool, good stuff.

**Comment by wasylkowski** [comment]
Note that there are other tests that would benefit from this changes, such as https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/autoscaling_timer.go

**Comment by aleksandra-malinowska** [comment]
Adding `retest-not-required` as this only affects one non-blocking autoscaling test suite.

**Pull request merged**
