### PR TITLE
Automated cherry pick of #37263 upstream release 1.5

### PR DESCRIPTION
**Pull request by saad-ali**
Automated cherry pick of #37263 from master to  release-1.5 branch to unblock automated upgrade tests

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37709)

**Comment by smarterclayton** [comment]
You beat me by 10 minutes.

**Comment by saad-ali** [comment]
All tests are green except for `Jenkins kops AWS e2e` which won't start due to infrastructure issues. 

```
Jenkins CRI GCE Node e2e — Build succeeded.
Jenkins GCE Node e2e — Build succeeded.
Jenkins GCE etcd3 e2e — Build succeeded.
Jenkins GCI GCE e2e — Build succeeded.
Jenkins GCI GKE smoke e2e — Build succeeded.
Jenkins GKE smoke e2e — Build succeeded.
Jenkins Kubemark GCE e2e — Build succeeded.
Jenkins unit/integration — Build succeeded.
Jenkins verification — Build succeeded.
Jenkins kops AWS e2e — Error starting build.
```

Manually merging to unblock automated upgrade testing. @krousey @roberthbailey

**Comment by dims** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
