### PR TITLE
Do not use ifupdown commands

### PR DESCRIPTION
**Pull request by chrisglass**
**What this PR does / why we need it**:
The ifupdown commands (ifup and ifdown) are not useful on many modern
distributions. Instead, the "ip link set" set of commands are standard
linux utilities and should be available everywhere (see
http://baturin.org/docs/iproute2/).

ipupdown utilities have the added quirk that they return 0 on failure,
which makes the changed line fail silently in case ifdown didn't bring
the network down.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yguo0905** [comment]
/lgtm

@bowei, can you please take a look?

**Comment by soltysh** [comment]
I'll defer to @kubernetes/sig-network-pr-reviews for review.
/unassign

**Comment by yguo0905** [comment]
@bowei, can you please take a look? 

This is to fix the tests like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntustable2-k8sbeta-reboot/24

**Comment by chrisglass** [comment]
I have squashed my commits - sorry for not doing it earlier on.

**Pull request merged**
