### PR TITLE
fix golint failures for test/e2e/ui

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures under `test/e2e/ui`.

ref: #68026

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by danielqsj** [comment]
@fejta PR rebased. PTAL

**Pull request merged**
