### PR TITLE
fix a typo in Ubuntu getting started guide

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
fix a typo in Ubuntu getting started guide: 
1. According to the table of contents, the style of tag `Starting a Cluster` should be h2 instead of h3 (the same with `Introduction` and `Prerequisites`);
2. And the style of related sub tags should be h3 instead of h4.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
cc @WIZARD-CXY @resouer

**Comment by resouer** [comment]
@jlowdermilk minor fix, so lgtm

**Comment by WIZARD-CXY** [comment]
lgtm, @kevin-wangzefeng , you must be chunvzuo, lol

**Comment by kevin-wangzefeng** [comment]
@WIZARD-CXY I'm just doing some document works these days, XD

**Pull request merged**
