### PR TITLE
extend the attachlease command with paths to certificates

### PR DESCRIPTION
**Pull request by ingvagabund**
Needed for secured etcd cluster

### CODE REVIEW

**Comment by ingvagabund** [comment]
@k8s-bot verify test this

**Comment by ingvagabund** [comment]
@k8s-bot unit test this

**Comment by ingvagabund** [comment]
@k8s-bot unit test this

**Comment by ingvagabund** [comment]
@wojtek-t any plans to make it part of the etcdctl migrate command itself?

**Comment by sdodson** [comment]
@smarterclayton seems similar to the auth tokens issue that was raised today

**Pull request closed without merging**
