### PR TITLE
Logf() failures for nicer logs

### PR DESCRIPTION
**Pull request by thockin**
@ixdy What do you think?  This makes logs easier to see by putting the failure line in the main flow.

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot e2e test this please, issue #PRJENKINSGOBOOM

**Comment by ixdy** [comment]
@eparis @brendandburns ^^ this munger is really annoying.

**Comment by eparis** [comment]
I get it, it is annoying, but was it wrong? Was there a flake we should have filed a flake for?

**Comment by ixdy** [comment]
@eparis no, the issue was that the Jenkins PR plugin broke itself again, so everything needs to be retested.

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
