### PR TITLE
Fix for travis CI link.

### PR DESCRIPTION
**Pull request by thereallukl**
Fix for travis CI link.

### CODE REVIEW

**Comment by gmarek** [comment]
Can you please sign the CLA?

**Comment by lleszczu** [comment]
@gmarek I work for Intel, we are supposed to have CLA signed. Do I need to be present on any special list ?

**Comment by wojtek-t** [comment]
There is probably a github organization (owned by Intel) that has the CLA assigned - you should be member of that.

**Comment by wojtek-t** [comment]
Also note, that there is already a PR in flight fixing that - see #12759

**Comment by roberthbailey** [comment]
Closing in favor of the pre-existing fix in https://github.com/kubernetes/kubernetes/pull/12759.

**Pull request closed without merging**
