### PR TITLE
Try looking up the pod IP via HNS.

### LINKED ISSUE #70279: Windows GotPodNetworkStatus assumes addToNetwork is idempotent, it's not
**What happened**:

On Windows, CNI plugins always get called twice (or more) with command ADD when a pod is created.

The issue is that `cni_windows.go:GetPodNetworkStatus()` calls `plugin.addToNetwork` to check the status, but this triggers a new add.

**What you expected to happen**:

Only a single ADD since ADD is not idempotent.

As per the (current, at least) CNI spec: 

> A runtime must not call ADD twice (without a corresponding DEL) for the same (network name, container id, name of the interface inside the container). This implies that a given container ID may be added to a specific network more than once only if each addition is done with a different interface name.

**How to reproduce it (as minimally and precisely as possible)**:

Network a pod on windows, will see two copies of this log:
```
I1023 16:05:18.098116    7176 cni.go:275] About to del CNI network k8s-pod-network ...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by fasaxc**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Alternate implementation of `GetPodNetworkStatus()` on Windows.  Look up the HNS interface by name, assuming the name contains the container ID.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70279

**Special notes for your reviewer**:

It's a bit of a hack that relies on the naming used by the currently-known CNI plugins, but it does make the call idempotent.  Putting it up as an RFC.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fasaxc** [comment]
Thanks @benmoss.  That looks like what I need

**Comment by benmoss** [comment]
@fasaxc it looks like @madhanrm has good reasons to not want to expose that on endpoints (https://github.com/Microsoft/hcsshim/pull/361#issuecomment-436401633), so your approach seems like it might be the best for now. It sounds like in the future there should be a better workaround.

**Comment by fasaxc** [comment]
@madhanrm @benmoss How about this alternative approach that maintains the exisitng structure of the hack but adds a hint to the CNI plugin: https://github.com/kubernetes/kubernetes/pull/70804

Feels like that'd be the path of least disruption until the CRI/namespace stuff is done.

**Pull request closed without merging**
