### PR TITLE
Implement kubectl get controllerrevisions

### PR DESCRIPTION
**Pull request by janetkuo**
Before:
```console
$ kubectl get controllerrevisions 
error: unknown type &apps.ControllerRevision{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{....}...}
```
After:
```console
$ kubectl get controllerrevisions 
NAME          CONTROLLER       REVISION   AGE
foo-2312378   DaemonSet/foo    1          2d
```

**Release note**:

```release-note
```

@kubernetes/sig-apps-pr-reviews @kubernetes/sig-cli-maintainers

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

/approve

Merge when green

**Comment by janetkuo** [comment]
Updated bazel and gofmt

**Comment by janetkuo** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by janetkuo** [comment]
All green, applying tag based on review

**Comment by kargakis** [comment]
@janetkuo can you fill in the release note? Not sure though if this PR warrants one.

**Comment by janetkuo** [comment]
If I leave the release block blank, PR title will be used as release note. The title is enough I think

**Comment by kargakis** [comment]
Didn't know that, OK

**Pull request merged**
