### PR TITLE
Use apps/v1 APIs in integration, explicitly enable all resources for print/etcd/scale tests

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
* continued work to prep for https://github.com/kubernetes/kubernetes/pull/70672
* explicitly enable deprecated resources for integration tests that intend to sweep all resources
* switch to use apps/v1 resources for integration tests that don't care

**Which issue(s) this PR fixes**:
xref #43214

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
#71696 failure
/retest

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
