### PR TITLE
Automated cherry pick of #125502: fix pod index label name

### PR DESCRIPTION
**Pull request by mas9612**
Cherry pick of #125502 on release-1.28.

#125502: fix pod index label name

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
from sig-apps pov

**Comment by mimowo** [comment]
/lgtm
/cc kubernetes/release-managers
Adding Marko as already in context after the main PR discussion
/cc @xmudrii

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by xmudrii — APPROVED** [review]
For cherry-pick approval

**Pull request merged**
