### PR TITLE
using util package function waitPoll  replace internal timeout check

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
using util package function waitPoll  replace internal timeout check

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE

```

### CODE REVIEW

**Comment by dims** [comment]
cc @vladimirvivien

**Comment by zouyee** [comment]
Gentle ping @saad-ali , PTAL! thank you.

**Comment by rootfs** [comment]
the mechanism looks reasonable
cc @vladimirvivien

**Comment by zouyee** [comment]
close as duplicate

**Pull request closed without merging**
