### PR TITLE
Let port forwarding e2e tests timeout on kubectl calls

### PR DESCRIPTION
**Pull request by sttts**
Fixes https://github.com/kubernetes/kubernetes/issues/15431

On the mesos/docker cluster the slaves do not have nsenter and socat (compare https://github.com/mesosphere/docker-containers/pull/30). The kubelet actually does not do the port-forwarding and the test conainter never gets a connection. Hence, the test container does not terminate and the `kubectl logs -f` hangs infinitely.

This PR put a timeout around `kubectl logs -f`.

### CODE REVIEW

**Comment by sttts** [comment]
@ncdc: have you had a chance to look at this?

**Comment by ncdc** [comment]
@sttts sorry, I've been swamped with other things. I can look today.

**Comment by ncdc** [comment]
@sttts any chance you could either add nsenter+socat to your nodes, or skip this test in your test suite?

**Comment by pmorie** [comment]
+1 to skipping this test for mesos provider.

**Comment by sttts** [comment]
@ncdc we are still working on the mesos part. This PR only adds the timeouts for the moment such that e2e tests don't block forever. There will be a followup PR for the Mesos issue.

**Comment by ncdc** [comment]
@sttts what about using this pattern instead: http://onsi.github.io/ginkgo/#asynchronous-tests?

**Comment by ncdc** [comment]
I'm not sure if this is better or not, but it seemed like an interesting approach.

**Comment by sttts** [comment]
@ncdc with that "trick" the timeout will cover the whole test, i.e. including spawning the pods. Don't like that in this case because due to docker-pulls the later might take more time and our "infinite timeout" is something like 30 sec.

**Comment by eparis** [comment]
I must be confused. If the test is testing something that isn't actually used in mesos it seems like the answer is to not run the test on mesos. Even with a timeout, you are just going to fail this test every time, right?  Better to not run it...

If there is value in a timeout outside of mesos then we shouldn't be using an infinite timeout, right?

**Comment by eparis** [comment]
Either the timeout has value to everyone and you should make it something 'sane', or this is mesos specific and is solving the problem incorrectly...

**Comment by sttts** [comment]
@eparis the PR is not actually about Mesos, but about introducing a timeout around a call which might block infinitely otherwise. Of course, in Mesos it is still red (we have a patch to provide nsenter and socat on the nodes, but don't like that; in fact, DCOS will not allow us to do so), but at least the whole e2e test suite does not timeout anymore, being blocked somewhere in the middle. Having one red test is better than a test run that stops after the first 7 tests.

And of course, it's not actually infinite, but `ForeverTestTimeout = time.Second * 30`.

About the follow-up Mesos fix: we might distribute nsenter+socat in our executor before the kubelet is launched. This is still in the works.

**Comment by derekwaynecarr** [comment]
@sttts - when running the tests on mesos, do you set a value here:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e_test.go#L67

we have precedent in other areas of skipping tests based on provider, so that is one possible option as well.

**Comment by sttts** [comment]
@derekwaynecarr in the conformance case we don't, in normal e2e tests we do of course. Our focus is the first right now.

**Comment by derekwaynecarr** [comment]
That said, personally, I hate waiting forever for something, and the point of ```ForeverTestTimeout``` is to define a value that is long enough to equate to forever in a testing scenario.  This seems reasonable to me.

**Comment by eparis** [comment]
I think @stts problem is best solved by not running the test instead of putting socat and friends into your system (since you aren't using this functionality), but agree, a forever freeze if I forgot to install those in my local distro is a bad experience.

**Comment by stts** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

keliong@naver.com 님께 보내신 메일 <Re: [kubernetes] Let port forwarding e2e tests timeout on kubectl calls (#15445)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sttts** [comment]
As background: before the new shiny [Conformance] test tags this test was actually considered as conformance test. Hence, skipping it was impossible back then. Now of course we could easily skip it. But we have higher goals of supporting port-forwarding ;-)

**Comment by ncdc** [comment]
Should we consider creating a helper method to run kubectl logs that all e2e tests must/should use? There are a few other tests that call it w/o any timeout.

**Comment by sttts** [comment]
Do they log with "-f"? I had the impression we wanted to wait for pod termination this way here. If there are other doing the same, your suggestion makes sense of course.

**Comment by sttts** [comment]
Looked through the kubectl invocations in e2e. None other has `-f` for log as far as I can see.

**Comment by ncdc** [comment]
I put in `-f` because I was seeing some flakiness where the call to `kubectl logs` would return nothing, but if I then manually inspected the container's logs, they were in fact not empty and contained the expected data. We could try taking `-f` out but I really don't want flakes...

**Comment by sttts** [comment]
`-f` makes complete sense here to synchronize with the pod output.

**Pull request merged**
