### PR TITLE
Add GetKubernetesHandler for FrameworkHandle

### LINKED ISSUE #79972: Add an interface in FrameworkHandle to get Kubernetes client related info
**What would you like to be added**:

Add an interface in FrameworkHandle to get Kubernetes client(`kubernetes.Interface`) and a list of listers(e.g. `PodLister`). I find [PluginFactoryArgs](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory/plugins.go#L37) might be an appropriate struct for it, however there is no Kubernetes client in it, we could add it later? 

**Why is this needed**:

Our new plugin need these client to get some information(e.g. it needs Kubernetes client to get/write some CRDs), and this interface has also been planned in the KEP [20180409-scheduling-framework.md#frameworkhandle](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#frameworkhandle).

/sig scheduling
/kind feature
/assign
ref/ kubernetes/enhancements#624

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:

Add `GetKubernetesHandler` for `FrameworkHandle` to get kubernetes client and a set of informers.

At first glance, [PluginFactoryArgs](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory/plugins.go#L37) is appropriate for getting kubernetes resource list. However there is some cons:

* It does not contains kubenetes client that is useful.
* It is a little confusing used for this new scheduler framework(e.g. the name `PluginFactoryArgs` is confusing), it has some useless filed(e.g. `HardPodAffinitySymmetricWeight`)

So I add a new struct `KubernetesHandler`. It contains a client set and a set of resource informers that plugins could use directly. These informers are same as scheduler's informers. Plugins could use them to add event handler or get resource lister.

**Which issue(s) this PR fixes**:

Fixes #79972 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add `GetKubernetesHandler` for `FrameworkHandle` to get kubernetes client and a set of informers.
```

### CODE REVIEW

**Review by bsalamat — CHANGES_REQUESTED** [review]
While I see why exposing informers and other internal structures of the scheduler to plugins may be useful, I strongly feel that we need to provide a limited interface for plugins to interact with these structures instead of exposing them.
We should study these in a case by case basis and add the interfaces as needed. We should not rush adding these in 1.16 unless it is proven necessary for converting our predicate and priority functions.

**Comment by hex108** [comment]
> While I see why exposing informers and other internal structures of the scheduler to plugins may be useful, I strongly feel that we need to provide a limited interface for plugins to interact with these structures instead of exposing them.
> We should study these in a case by case basis and add the interfaces as needed. We should not rush adding these in 1.16 unless it is proven necessary for converting our predicate and priority functions.

@bsalamat  Our plugins need kubernetes client and some informers. Since all these informers/listers have been used by plugins, I think it might be needed by new plugins too.  And `case by case basis` could not cover all the cases. So it might be safe and worth to add them?

**Comment by Adirio** [comment]
I was checking how could we convert some of the current logic into PreFilter plugins. I've seen 3 PreFilter plugin candidates.

1. Check the pod deletion timestamp: https://github.com/kubernetes/kubernetes/blob/c7c89f8c6140e0639dc8ba2d8dcdd6fdbd5409ae/pkg/scheduler/scheduler.go#L524-L528
2. Check the persisten volume claims (existance and deletion timestamp): https://github.com/kubernetes/kubernetes/blob/c7c89f8c6140e0639dc8ba2d8dcdd6fdbd5409ae/pkg/scheduler/core/generic_scheduler.go#L193-L195 https://github.com/kubernetes/kubernetes/blob/c7c89f8c6140e0639dc8ba2d8dcdd6fdbd5409ae/pkg/scheduler/core/generic_scheduler.go#L1218-L1241
3. Check there is at least 1 node: https://github.com/kubernetes/kubernetes/blob/c7c89f8c6140e0639dc8ba2d8dcdd6fdbd5409ae/pkg/scheduler/core/generic_scheduler.go#L203-L206

I think all those should be turned into PreFilter plugins.

1. The first one doesn't need anything as it will just need to return an error. It accesses the Redorcer directly as it is found inside the scheduler and not the generic_scheduler but that should not be an issue as returning an error has the same behavior after all.
2. The second one requires a `PVCLister`. I think providing access to listers to the framework should be safe.
3. The third one requires the cache. Providing the whole cache may not be a good idea, but providing the Snapshot of the cache some additional behavior (such as being also a NodeLister) would make it safe and would be enough for this usecase.

Providing the whole client may be unsafe as @bsalamat says. What do you need the whole client for?

**Comment by hex108** [comment]
@Adirio Yes, as @bsalamat suggested, we'll add these listers/informers/... if needed when we convert existing functions to default plugins.

However case by case basis could not cover all the cases, e.g. we could not cover use cases for out-of-tree plugins.

**Comment by Adirio** [comment]
> However case by case basis could not cover all the cases, e.g. we could not cover use cases for out-of-tree plugins.

I do understand your concern about out-of-tree plugins but @bsalamat seems to be concerned about the freedom to modify the internal cluster state that we are giving to those plugins, if I understood him right. He asked not to rush to add everything unless it is needed for transforming existing ones. That's the reason I listed the ones that should be transformed at the PreFilter hook, with their requirements.

**Comment by cofyc** [comment]
another use case is volume binder library builtin in the scheduler.

**Pull request closed without merging**
