### PR TITLE
interactive kubectl pod filter

### PR DESCRIPTION
**Pull request by kaplanelad**
**What type of PR is this?**

/kind feature

**why we need it:**

In order to SSH into a pod the exact name is required and the namespace as well, something like:

1) `kubectl get pods -n <namespace>`

2) `kubectl exec -it <pod name> ...`

This is less efficient and can be done in a more user friendly way.
 
**What this PR does **:

I would like to create a new flag that will allow fuzzy searching of some pod name and ssh easier.

I have added a new flag (--like, -l) into kubectl exec subcommand, by default the flag is false (to preserve backwards behavior )

**For example,  :**

This is the result of` kubectl get pods`

image

We want to only access pods of the deployment:  **foo-deployment**

Then:
`kubectl exec -it --like foo sh`

The result of the command will present a table with all the pod's that matches the query `-like <query>`

image

**Special notes for your reviewer**:
I have added unit-tests for the new logic, please let me know if further modification are required  

**Does this PR introduce a user-facing change?**:
```release-note
kubectl/exec new flag: --like (off by default) allows for fuzzy search of pods and quick SSH access. Action required: upgrade kubectl 


kubectl exec -it --like foo sh
```

Thank you for taking the time and reviewing this PR.

### CODE REVIEW

**Comment by kaplanelad** [comment]
CNCF approval

**Comment by Isan-Rivkin** [comment]
That's cool, you can do it for `kubectl logs` as well

**Comment by tanjunchen** [comment]
cool
/ok-to-test

**Comment by kaplanelad** [comment]
@tanjunchen, this for open the PR for test (all of them pass).
Should i wait now to the reviewers? (this is my first PR)

**Comment by tanjunchen** [comment]
@kaplanelad Sure,Wait.
/assign @mengqiy
/cc @neolit123

**Comment by kaplanelad** [comment]
@tanjunchen, thanks.  
commits squashed.

**Comment by kaplanelad** [comment]
Hi @smarterclayton  ,I know you're super busy. I’d like to kindly ping you and ask what is the current status of the PR? maybe there is something missing?
Thanks!
FYI, #85715  is the same but for logs  subcommand

**Comment by liggitt** [comment]
Thanks for the PR, but it's not clear this approach is desired in kubectl. kubectl does not currently include interactive flows or fuzzy matching. If you want to propose changing this approach, discussing it with [sig-cli](https://github.com/kubernetes/community/tree/master/sig-cli#contact) and opening a [proposal](https://github.com/kubernetes/enhancements/tree/master/keps/#kubernetes-enhancement-proposals-keps) would be the best place to start.

If this is not accepted within kubectl, you can also build this functionality as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).

/close

**Pull request closed without merging**
