### PR TITLE
Danuk1982 patch 1

### PR DESCRIPTION
**Pull request by danuk**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by coffeepac** [comment]
@danuk1982 did you want to use the new image you are building?  the version strings are hardcoded in the pod specs

**Comment by danuk1982** [comment]
@coffeepac Now I'm using a custom version for my purposes. This commit I made to help other users, because the current version contains errors.

**Comment by coffeepac** [comment]
@danuk1982 sorry, I meant to be more explicit. Can you please update the versions that are used by the pod specs?  I think this is a fine change and we should, by default, be using it.

**Comment by coffeepac** [comment]
@piosz can you build these images and push them?

**Comment by danuk1982** [comment]
@coffeepac Unfortunately I don't know where it needs to be updated yet

**Comment by coffeepac** [comment]
@danuk1982 you okay with closing this PR in favor of https://github.com/kubernetes/kubernetes/pull/64372 ?  it pushed fluentd to 1.2.1 instead of 1.1.3

the location to update the image tag:  https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml#L79 and then everywhere else in that file with `version: v2.0.4`

**Comment by danuk1982** [comment]
@coffeepac yep, https://github.com/kubernetes/kubernetes/pull/64372 newer than mine. This regvest can be closed.

**Comment by coffeepac** [comment]
@danuk1982 thanks mate!   we're in a code freeze right now but as soon as that's lifted I'll get to pushing these through.

**Pull request closed without merging**
