### PR TITLE
Refactor probe.Result enumeration

### PR DESCRIPTION
**Pull request by tmrts**
Refactors the usage of `iota` in `probe` package.

### CODE REVIEW

**Comment by a-robinson** [comment]
@tmrts this is failing a test
```
# k8s.io/kubernetes/pkg/apiserver
_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/validator_test.go:92: test.expectedStatus.String undefined (type probe.Result has no field or method String)
_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/validator_test.go:92: status.String undefined (type probe.Result has no field or method String)
FAIL	k8s.io/kubernetes/pkg/apiserver [build failed]
```

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Comment by tmrts** [comment]
@a-robinson 
```go
if status != test.expectedStatus {
	t.Errorf("expected %s, got %s", test.expectedStatus.String(), status.String())
}
```
usage is wrong, since errorf calls `String() string` method for the values.
I've committed a fix for it.

**Comment by a-robinson** [comment]
Thanks @tmrts!

**Comment by a-robinson** [comment]
The shippable failure is an integration test flake

**Pull request merged**
