### PR TITLE
While updating NodeStatus, only first get served from cache

### LINKED ISSUE #37725: Retry loops should only read from the cache the first iteration
Specifically, this code https://github.com/kubernetes/kubernetes/blob/5e1adf91dfbe6ec9f96950e9b4e28523b8d3ccd8/pkg/kubelet/kubelet_node_status.go#L325 reads from the cache every time, so it will keep failing as long as the cache is stale, which could be arbitrarily long.

@wojtek-t

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #37725

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37788)

**Comment by gmarek** [comment]
lgtm

**Comment by dchen1107** [comment]
LGTM, but I will leave this to @lavalamp to make the final call. Thanks!

**Comment by lavalamp** [comment]
/lgtm

thanks for quick fix!!

**Comment by saad-ali** [comment]
This PR has merge conflicts, I will not pick it up in my batch cherry pick to 1.5 branch. Please prepare a separate cherry pick. See "About Cherrypicks" section in https://groups.google.com/forum/#!topic/kubernetes-dev/mvIXrgEyHPY for help.

**Comment by wojtek-t** [comment]
@saad-ali - sure. On it.

**Comment by wojtek-t** [comment]
@saad-ali - opened https://github.com/kubernetes/kubernetes/pull/37927

**Comment by saad-ali** [comment]
Ack

**Pull request merged**
