### PR TITLE
Fix test order staging/src/k8s.io/component-base/logs/json/json_test.go

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Per https://pkg.go.dev/github.com/stretchr/testify/assert#Equal expected goes before actual:

func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Fixes tests asserting that the expected values were the actual ones, when they were not. just like
https://github.com/kubernetes/kubernetes/pull/102611
https://github.com/kubernetes/kubernetes/pull/102615
#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I noticed that `assert.Equal` is heavily used in `k8s.io/component-base`, can you help to confirm if it is the only case in `k8s.io/component-base`? I mean we can fix all the similar mistakes by this PR.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @muyangren2 You can find mistakes elsewhere and fix them together

**Comment by muyangren2** [comment]
> I noticed that `assert.Equal` is heavily used in `k8s.io/component-base`, can you help to confirm if it is the only case in `k8s.io/component-base`? I mean we can fix all the similar mistakes by this PR.

ok i will check all and fix it ,thanks

**Comment by muyangren2** [comment]
> I noticed that `assert.Equal` is heavily used in `k8s.io/component-base`, can you help to confirm if it is the only case in `k8s.io/component-base`? I mean we can fix all the similar mistakes by this PR.

I carefully checked `k8s.io/component-base` This component is only this one,  no other

**Comment by RainbowMango** [comment]
> I carefully checked k8s.io/component-base This component is only this one, no other
Thanks.

/ok-to-test

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks.

**Pull request merged**
