### PR TITLE
Fix cluster up failures by cleaning docker build dirs (sigh)

### PR DESCRIPTION
**Pull request by zmerlynn**

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @ixdy

**Comment by ixdy** [comment]
LGTM

**Comment by zmerlynn** [comment]
Clarification on what's happening: On cluster boot, the leftover directories in the tar are causing the "cp" command during the install script to fail because we're doing a plain, non-recursive cp. The litter in the tar is bad.

**Comment by zmerlynn** [comment]
Merging to stop bleeding.

**Comment by justinsb** [comment]
This fixed AWS also - thanks (and sorry for not spotting this originally!)

**Pull request merged**
