### PR TITLE
fix handling of nil times in managedFields sorting

### PR DESCRIPTION
**Pull request by kwiesmueller**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
follow-up to fix issues addressed in https://github.com/kubernetes/kubernetes/pull/74721#discussion_r262752109

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig api-machinery
/cc @apelisse @jennybuckley @tedyu 
/wg apply

### CODE REVIEW

**Comment by jennybuckley** [comment]
Is ntime the current time? I'm not aware what `time.Time{}` turns into

/test pull-kubernetes-e2e-gce-alpha-features

**Comment by kwiesmueller** [comment]
It turns into the Golang origin time.
https://golang.org/pkg/time/#Time

**Pull request merged**
