### PR TITLE
E2E: Update kubectl.go - remove default NS and use idiomatic namepsace l...

### PR DESCRIPTION
**Pull request by jayunit100**
Its me again with another namespaces update ! This time cleaning up kubectl. 

Tested, and  works for me...  I used cluster/kubectl.sh and removed that right before issuing the PR.

```
• [SLOW TEST:10.763 seconds]
kubectl
/home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:121
  update-demo
  /home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:100
    should create and stop a replication controller
    /home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:73
------------------------------
SSSSSSSSSSSSSSS
Ran 4 of 41 Specs in 67.640 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 37 Skipped I0429 22:50:07.214832    6664 driver.go:96] All tests pass
```

### CODE REVIEW

**Comment by jayunit100** [comment]
one second before merging - i have to add `AfterEach`, will ping in a second.

**Comment by jayunit100** [comment]
ping the usual e2e suspects @satnam6502 @roberthbailey @wojtek-t  @quinton-hoole

**Comment by wojtek-t** [comment]
LGTM

**Comment by pmorie** [comment]
Looks like a shippable flake.  This change LGTM.

**Pull request merged**
