### PR TITLE
Customizable vagrant rsync args and excludes

### PR DESCRIPTION
**Pull request by jistr**
**What this PR does / why we need it**:

There are some annoyances with Vagrant+rsync currently.

When using rsync file synchronization with Vagrant, the whole kubernetes
repo directory is copied over into the virtual machine. This includes
the _output directory, which tends to be gigabytes in size, while often
just _output/release-tars (a few hundred MB) would be enough.

Furthermore, if the some of the directories contains a recursive
symlink, rsync with the default args will keep descending and copying
files endlessly until filling up the VM disk.

**The improvement**:

Making the rsync args and excluded dirs/files customizable via
KUBERNETES_VAGRANT_RSYNC_ARGS and KUBERNETES_VAGRANT_RSYNC_EXLUDE,
respectively, allows the developer to prevent the issues mentioned
above. A new KUBERNETES_VAGRANT_USE_RSYNC variable is also added to
control whether Vagrant should force usage of rsync as the file
synchronization backend. The args/exclude customizations only take
effect when KUBERNETES_VAGRANT_USE_RSYNC is 'true'.

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36740)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Review by errordeveloper — APPROVED** [review]

**Comment by jistr** [comment]
Can this get labeled with `release-note-none`? Also it got labeled with `cla: no` but i think it should be `cla: yes`? See the `cla/linuxfoundation` CI job.

**Comment by rmmh** [comment]
@k8s-bot test this

**Pull request merged**
