### PR TITLE
Update all CHANGELOG file

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Something is missing at the bottom of the CHANGELOG file, starting at 1.10.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@xichengliudui thanks for the PR
i personally don't see the great need for this change, but will leave it to SIG Release to decide.

@kubernetes/sig-release

**Comment by liggitt** [comment]
thanks for the PR, but changelogs are added to programmatically by release scripts. adding footers we then have to strip out isn't particularly useful

/close

**Pull request closed without merging**
