### PR TITLE
Automated cherry pick of #87630: add a flag in azure auth module to omit spn: prefix in

### PR DESCRIPTION
**Pull request by weinong**
Cherry pick of #87630 on release-1.16.

#87630: add a flag in azure auth module to omit spn: prefix in

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by weinong** [comment]
/sig cloud-provider
/area provider/azure
/sig cli
/kind bug

this cherry pick is to address a bug in Azure AD auth module (#86410) which results in a claim with `spn:` prefix that is incompatible with AAD On-Behalf-Of flow among many other things described in #86410. To avoid breaking change to existing k8s customers using Azure AD (#87541), a flag in auth provider config is added.

**Comment by liggitt** [comment]
generally features are not backported to release branches

**Comment by tpepper** [comment]
At this point this cherry pick is gated by OWNERS giving approval, not patch release team.

**Comment by liggitt** [comment]
closing per discussion in https://github.com/kubernetes/kubernetes/pull/87985#issuecomment-606768195

**Pull request closed without merging**
