### PR TITLE
Rewrite garbage-collection.md page

### PR DESCRIPTION
**Pull request by kelcecil**
The garbage-collection.md page was a little difficult to read, so I rewrote the page try to improve readability. I included almost everything from the old page (dropping one line about files in the containers that I thought was obvious) and double checked that the kubelet flags are still the correct flag names.

### CODE REVIEW

**Comment by kelcecil** [comment]
I rebased this against the head of master!

**Comment by pwittrock** [comment]
@kelcecil Sorry that this hasn't been reviewed already.  I really like your changes and appreciate you taking the time to improve the readibility of the docs.  Would you be willing to rebase another time, and then I will review it again?

**Comment by pwittrock** [comment]
@kelcecil Thanks for your changes.  Would you be willing to rebase?

**Comment by kelcecil** [comment]
Sure. I'll try to get it this today.

**Comment by kelcecil** [comment]
@pwittrock I rebased and reviewed the conflicts between head and what I wrote. I think everything is good.

**Comment by pwittrock** [comment]
Thanks.  Taking a look now.

**Comment by pwittrock** [comment]
ok to test

**Comment by pwittrock** [comment]
Looks good, will let the merge bot take care of it.

**Pull request merged**
