### PR TITLE
Running etcd 2.0.5 in a pod on master

### PR DESCRIPTION
**Pull request by ArtfulCoder**
With #6200  The kube-addons come up now since retry logic is added to create kube-addons.
This PR should work now robustly.

### CODE REVIEW

**Comment by zmerlynn** [comment]
I think something is wrong with your tree here? That "merge" commit is bogus.

**Comment by zmerlynn** [comment]
Rather, even if this is a merge, I'd *much* rather merge a PR that's a clean commit than a merge commit. I just worked out that this PR is a merge commit, so we'd be merging a merge commit.

**Comment by ArtfulCoder** [comment]
yes, I am going to just close this PR and create a new one.

**Comment by zmerlynn** [comment]
You probably could've cleaned out your branch and still pushed to this PR, but either way. :)

**Comment by ArtfulCoder** [comment]
created #6221

**Comment by dchen1107** [comment]
Why not simply revert previous revert one? Just curious here.

**Pull request closed without merging**
