### PR TITLE
Automated cherry pick of #72682: Add `metrics-port` to kube-proxy cmd flags.

### PR DESCRIPTION
**Pull request by whypro**
Cherry pick of #72682 on release-1.13.

#72682: Add `metrics-port` to kube-proxy cmd flags.

### CODE REVIEW

**Comment by whypro** [comment]
ping @lavalamp @thockin

**Comment by aleksandra-malinowska** [comment]
Friendly ping - this didn't make it into 1.13.3, if you want to merge this before 1.13.4, please get approval from SIG

**Comment by MrHohn** [comment]
/assign @thockin 
for sig approval.

**Pull request merged**
