### PR TITLE
Need something tag when use minikube

### PR DESCRIPTION
**Pull request by Asuforce**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

When using minikube, you need to specify the tag.

**Which issue(s) this PR fixes**:

ref: https://github.com/kubernetes/client-go/pull/771

**Special notes for your reviewer**:

non

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```release-note

```

### CODE REVIEW

**Comment by jpbetz** [comment]
@Asuforce this will need a release note "NONE" section in the PR description:

\`\`\`release-note
NONE
\`\`\`

**Comment by Asuforce** [comment]
@jpbetz done

**Comment by jpbetz** [comment]
/assign @sttts

Would you approve? This is a doc change.

**Comment by Asuforce** [comment]
@sttts ping

**Comment by nikhita** [comment]
/assign @caesarxuchao 
for approval

**Pull request closed without merging**
