### PR TITLE
delete unused functions in pkg/kubelet directory

### LINKED ISSUE #115088: Cleanup dead code in the codebase
https://github.com/kubernetes/kubernetes/pull/111654 started here but it got big (shocking!) and the contributor got busy.  There are a lot of potential cleanups in there, though, and I hate wasting work.

I see it as an opportunity for someone to rack up some PRs and net-negative LOCs (the best kind!) - just take over that PR, break it up into a bunch of smaller PRs, and send them our way!

A very eager beaver might automate this, but there's a lot of manually-identified low-hanging fruit, I think.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

xref #115088

#### Special notes for your reviewer:
This PR follows the content of #111654, the purpose is to split #111654 into many small PRs, this PR only modifies the pkg/kubelet directory
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
@HirazawaUi I think you can clean more if you check https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115101/pull-kubernetes-verify/1614896976925560832

**Comment by HirazawaUi** [comment]
> @HirazawaUi I think you can clean more if you check https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115101/pull-kubernetes-verify/1614896976925560832

I fixed this error and run `/hack/verify-golangci-lint.sh`, everything works fine, can you help me to retest?

**Comment by matthyx** [comment]
> can you help me to retest?

tests are already running

**Comment by thockin** [comment]
This seems OK to me - it's all dead code.

@bobbypage or @SergeyKanzhelev or @mrunalp - any objections?

**Comment by thockin** [comment]
/approve
/hold

remove the hold if we're confident in it.

**Comment by dims** [comment]
LGTM. we are early enough in the 1.27 timeline, so we can add things back if needed.

/hold cancel

**Pull request merged**
