### PR TITLE
Fix shellcheck failures of cluster/gce/gci/shutdown.sh

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix shellcheck failures of cluster/gce/gci/shutdown.sh

**Which issue(s) this PR fixes**:

Ref #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority important-soon

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by SataQiu** [comment]
@neolit123 
I have updated the code. Can you LGTM again?

**Pull request merged**
