### PR TITLE
Fix quotes in documentation

### PR DESCRIPTION
**Pull request by bobrik**
`”` are rendered as `'?`

image

### CODE REVIEW

**Comment by bobrik** [comment]
@ixdy 4 messages from @k8s-bot in a row do not look right.

**Comment by jfrazelle** [comment]
Hi @bobrik !!!!

**Comment by jfrazelle** [comment]
So I think you need to update this on master, then it will go to gh-pages?

**Comment by bobrik** [comment]
Hello!

Fun thing is: docs don't seem to live in `master`, but there are some leftovers in `gh-pages`.

```
bobrik@whatever: ~/projects/kubernetes on master
$ fgrep 'command: ["/bin/echo' -r *

bobrik@whatever: ~/projects/kubernetes on master
$ git checkout gh-pages
Switched to branch 'gh-pages'
Your branch is up-to-date with 'origin/gh-pages'.

bobrik@whatever: ~/projects/kubernetes on gh-pages
$ fgrep 'command: ["/bin/echo' -r *
_v1.0/docs/user-guide/configuring-containers.md:    command: ["/bin/echo","hello”,”world"]
_v1.0/docs/user-guide/configuring-containers.md:    command: ["/bin/echo"]
_v1.0/docs/user-guide/configuring-containers.md:    command: ["/bin/echo"]
_v1.1/docs/user-guide/configuring-containers.md:    command: ["/bin/echo","hello”,”world"]
_v1.1/docs/user-guide/configuring-containers.md:    command: ["/bin/echo"]
_v1.1/docs/user-guide/configuring-containers.md:    command: ["/bin/echo"]
```

Looks like these docs now live in https://github.com/kubernetes/kubernetes.github.io. I suggest removing `gh-pages` from this repo to avoid confusion.

What would be even greater is a github link on every doc page so I can just jump to Github. Elasticsearch got it right with "edit" buttons all over their docs:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html

You can fix typos without leaving your browser that way. Great stuff!

**Comment by jfrazelle** [comment]
Good call :)

**Comment by ixdy** [comment]
> @ixdy 5 messages from @k8s-bot in a row do not look right

I agree. Unfortunately the bug in the Jenkins plugin (https://github.com/jenkinsci/ghprb-plugin/issues/292) continues to receive no attention.

**Pull request closed without merging**
