### PR TITLE
Validate volume paths do not have ':'

### LINKED ISSUE #21681: We should sanitize mountPath
A user made an error setting their mountPath - they set a docker-style mountpath `mountPath: /data/ldap/db:/var/lib/ldap`

However, the error that they got (and inspection of the code) indicates that we just passed that straight through to docker (`API error (500): invalid mode for volumes-from: /var/lib/ldap`).  Docker treats the 3rd argument as a mode flag.

We should sanitize the input, both to help users when they make mistakes, but also because if Docker allowed other options in its mounts this could become a security issue.

### PR DESCRIPTION
**Pull request by thockin**
Fixes #21681

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM.  Thanks for fixing - will avoid a lot of confused users :-)

**Comment by rhatdan** [comment]
This change is causing problems with SELinux and other changes in docker.  Basically you are now blocking the passing of the :Z and :z flags to docker to setup proper labeling of content volume mounted into an image.  There are other flags that are passed in to docker volumes that this will block also

:ro for readonly containers
:shared,:private,:slave  for mount propagation 

I think you patch should look for the sequence of

`:/` And drop that, not just for `:`

**Comment by eparis** [comment]
@rhatdan no, I think that we should expose the docker options as real kubernetes concepts, not as some string passed straight from users...    kube should already be handling the `z` and `Z` I thought. @pmorie would know, but he's out for a couple days.

Mount propogation will be added, there is another PR for that.

I don't know if we support `:ro`....

**Comment by rhatdan** [comment]
I am fine with that, but until these primitives are added, we are breaking openshift.

**Comment by thockin** [comment]
We have selinux and reaonly support, but as actual fields, not "stringly
typed" values.  what exactly is breaking?

**Comment by rhatdan** [comment]
@thockin Just have a bugzilla where someone had been doing it the other way and an update to k8s blew up their config.  I will try to find it again and tell them to use the alternate mechanism that K8s implements.

Sorry for the noice.

**Comment by thockin** [comment]
Thanks.  It's an interesting point that I didn't consider.  I don't think
we want to endorse that way of operating, but I admit I did not consider it.

Cheers.

**Pull request merged**
