### PR TITLE
isolate the resource quota full sync in a separate queue

### LINKED ISSUE #122483: Faster ResourceQutoa Replenishment
### What would you like to be added?

An enhancement to make the resource quota replenishment faster when resources are updated or deleted. 

### Why is this needed?

The resource quota controller does full sync of resource quotas periodically. And the resource update/delete events are put into the same queue which handles the full sync objects. In a cluster with large amount of namespaces and resource quota objects, the queue becomes too long and makes the quota replenishment slow.

### PR DESCRIPTION
**Pull request by leoyang02**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR isolates the resource quota full sync in a separate queue which makes the resource quota replenishment faster when resources are updated or deleted.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/122483

#### Does this PR introduce a user-facing change?

```release-note
End users will experience reduced latency of resource quota replenishment.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Could we have a benchmark with it to estimate the performance benefit and cost of cpu/memory?

**Comment by sftim** [comment]
> #### Does this PR introduce a user-facing change?
> 
> ```
> NONE
> ```

I think this change would be something end users would notice. I've based this on the issue context: end users want reduced update latency.

I'd add a changelog entry.

**Comment by leoyang02** [comment]
> Could we have a benchmark with it to estimate the performance benefit and cost of cpu/memory?

Environment: 
A cluster with 50,000 namespaces and 200,000 resource quotas

Before:
Quota replenishment duration: 15 minutes
Controller cpu utilization: 6
Controller memory usage: 35GB

After:
Quota replenishment duration: 2 seconds
Controller cpu utilization: 6
Controller memory usage: 35GB

This change basically separate the full sync cases with other cases. The consumption of CPU/memory from all the other cases can be considered negligible comparing with the full sync.

**Comment by leoyang02** [comment]
All tests passed. @deads2k @derekwaynecarr @soltysh could you help to review?

**Comment by leoyang02** [comment]
Is there anything else needed from my side for this PR to get reviewed and merged? @pacoxu @deads2k @derekwaynecarr @soltysh

**Comment by pacoxu** [comment]
/cc @janetkuo @alculquicondor 
for review

**Comment by alculquicondor** [comment]
isn't this pretty much equivalent to doubling the number of workers?

Can you run the benchmark without the change, but with double the workers?

**Comment by leoyang02** [comment]
> isn't this pretty much equivalent to doubling the number of workers?
> 
> Can you run the benchmark without the change, but with double the workers?

We tried that but it didn't help. Because the overall speed is limited by --max-requests-inflight and --max-mutating-requests-inflight. By using a dedicated queue for full sync, the other cases will not have to wait for the full sync objects.

**Comment by leoyang02** [comment]
I put 2 charts to illustrate the solution:
Before:
before
After:
after

**Comment by alculquicondor** [comment]
Thanks for the clarification. I'm ok with the change then, but I'm not an approver for this package :)

**Comment by aojea** [comment]
but then you may be processing duplicate events , no?

There are places to do these tests in integration https://github.com/kubernetes/kubernetes/blob/821c0ef61e5397954658d92b9042dbfae9186415/test/integration/quota/quota_test.go#L399

**Comment by leoyang02** [comment]
> but then you may be processing duplicate events , no?
> 
> There are places to do these tests in integration
> 
> https://github.com/kubernetes/kubernetes/blob/821c0ef61e5397954658d92b9042dbfae9186415/test/integration/quota/quota_test.go#L399

Hi @aojea, sorry for replying late. There may be duplicated events since they are now put into different queues. But the purpose is to accelerate the replenishment of the quota when resources are deleted. It is somewhat similar with the idea of the missingUsageQueue.

**Comment by leoyang02** [comment]
@aojea @soltysh @deads2k @derekwaynecarr @alculquicondor @janetkuo 
Sorry to bother you, any other questions about this PR?

**Comment by dims** [comment]
@leoyang02  please rebase!

**Pull request closed without merging**
