### PR TITLE
Add backoff retries and client config for Azure cloud provider

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind feature
/sig cloud-provider
/area provider/azure
/priority important-soon

**What this PR does / why we need it**:

Continue of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/247. This PR adds a new ClientConfig and backoff retry for Azure cloud provider:

* Add a new ClientConfig so that new Azure clients could import it without unnecessary dependencies
* Add backoff retry and implements autorest.SendDecorator interface. The new backoff retry would be used in the following Azure ARM clients
* Switch to new ClientConfig in Azure cloud provider so that the changes won't break existing codes

**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/247

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @andyzhangx

### CODE REVIEW

**Review by cblecker — APPROVED** [review]
/approve

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
