### PR TITLE
godep bump: github.com/evanphx/json-patch

### LINKED ISSUE #26890: PATCH API requests don't handle path escaping as per RFC 6901
tl;dr JSON Patch paths should have `/` & `~` escaped with `~1` & `~0` respectively, see http://tools.ietf.org/html/rfc6901#section-4 for more details on what's required.

I've submitted a [PR](https://github.com/evanphx/json-patch/pull/27) to evanphx/json-patch with the fix - will need to update vendored dependencies once that's merged (hopefully soon).

Would like to see this fix in 1.3 unless it's too late?

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #26890

### CODE REVIEW

**Comment by jimmidyson** [comment]
Unrelated flake - `[Fail] [k8s.io] Kubelet metrics api when querying /stats/summary [It] it should report resource usage through the stats api`

**Comment by eparis** [comment]
looks like a dupe of #25866 which should we take? Do we need for 1.3?

**Comment by jimmidyson** [comment]
Sorry didn't see the other PR. They're both just bumps of json-patch, this one latest version which includes a fix for rfc 6901 compliant encoded property paths, fixing #26890. I'd take this one.

**Comment by jimmidyson** [comment]
And yes I would say this is a good candidate for 1.3 as it's a  bug that prevents rfc compliant json patch requests from being handled correctly.

**Comment by jimmidyson** [comment]
Sorry this needs another bump after evanphx/json-patch#28 is merged - missed another possible path encoding.

**Comment by evanphx** [comment]
@jimmidyson json-patch has been updated

**Comment by jimmidyson** [comment]
@evanphx Thanks!

@deads2k This is ready for review now.

**Comment by eparis** [comment]
@k8s-bot node test this issue #IGNORE

it looks like it passed, but maybe didn't report results?

**Comment by jimmidyson** [comment]
Hmm again tests seemed to pass but no feedback into Github PR status - any ideas @eparis?

**Comment by eparis** [comment]
@ixdy can you help figure out what's up with Node e2e or tell us who could?

**Comment by eparis** [comment]
@spxtr maybe you know how to help or what up with the node e2e

**Comment by ixdy** [comment]
cc @fejta

**Comment by jimmidyson** [comment]
Any ideas on why this isn't reporting back?

**Comment by fejta** [comment]
Yes, it didn't run because the trigger phrase is: (?is).*@k8s-bot\s+node\se2e\s+test\s+this.*|(?is).*@k8s-bot test node e2e experimental

**Comment by fejta** [comment]
@k8s-bot node e2e test this issue #IGNORE

**Comment by eparis** [comment]
Doesn't explain what happened the first time, but thanks.

**Pull request merged**
