### PR TITLE
Support autoscale deployments

### LINKED ISSUE #17143: Support autoscale deployments
Follow up #15739 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L298

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #17143 

Now you can do `kubectl autoscale deployment foo ...`

cc @kubernetes/autoscaling @kubernetes/kubectl

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Is there actually no further work to do besides adding it to the switch in factory? If so lgtm, but a unit test would be good.

**Comment by janetkuo** [comment]
Added tests in `test-cmd.sh`.

**Comment by piosz** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by smarterclayton** [comment]
@kargakis

On Nov 13, 2015, at 8:22 PM, Janet Kuo <notifications@github.com> wrote:

Fixes #17143 <https://github.com/kubernetes/kubernetes/issues/17143>

Now you can do kubectl autoscale deployment foo ...

cc @kubernetes/autoscaling
<https://github.com/orgs/kubernetes/teams/autoscaling> @kubernetes/kubectl
<https://github.com/orgs/kubernetes/teams/kubectl>
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/kubernetes/kubernetes/pull/17269
Commit Summary

   - Support autoscale deployments

File Changes

   - *M* docs/man/man1/kubectl-autoscale.1
   <https://github.com/kubernetes/kubernetes/pull/17269/files#diff-0> (8)
   - *M* docs/user-guide/kubectl/kubectl.md
   <https://github.com/kubernetes/kubernetes/pull/17269/files#diff-1> (4)
   - *M* docs/user-guide/kubectl/kubectl_autoscale.md
   <https://github.com/kubernetes/kubernetes/pull/17269/files#diff-2> (10)
   - *M* pkg/kubectl/cmd/autoscale.go
   <https://github.com/kubernetes/kubernetes/pull/17269/files#diff-3> (8)
   - *M* pkg/kubectl/cmd/util/factory.go
   <https://github.com/kubernetes/kubernetes/pull/17269/files#diff-4> (3)

Patch Links:

   - https://github.com/kubernetes/kubernetes/pull/17269.patch
   - https://github.com/kubernetes/kubernetes/pull/17269.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/17269>.

**Comment by kargakis** [comment]
looks good

**Pull request merged**
