### PR TITLE
Bump CoreDNS version to 1.3.1

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Bumps the CoreDNS version to 1.3.1

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
CoreDNS is now version 1.3.1
   - A new `k8s_external` plugin that allows external zones to point to Kubernetes in-cluster services.
   - CoreDNS now checks if a zone transfer is allowed. Also allow a TTL of 0 to avoid caching in the cache plugin.
   - TTL is also applied to negative responses (NXDOMAIN, etc).
   - Also provides a deprecation notice for `upstream` where the upstream directive used in various plugin will start to default to the CoreDNS process itself. 
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by MrHohn** [comment]
> CoreDNS is now version 1.3.1

May be worth to update release note with what is new in version 1.3.1?

**Review by neolit123 — APPROVED** [review]
/approve
/priority important-longterm
@kubernetes/sig-cluster-lifecycle-pr-reviews 

let's hold for a day to give time for others to see the change.
/hold

**Comment by neolit123** [comment]
> May be worth to update release note with what is new in version 1.3.1?

or at least an one line summary?

**Comment by rajansandeep** [comment]
@MrHohn @neolit123 I've updated the release notes.

**Comment by neolit123** [comment]
thanks @rajansandeep !
@MrHohn if the `cluster` folder needs this ASAP please free to hold cancel.

**Comment by MrHohn** [comment]
> @MrHohn if the cluster folder needs this ASAP please free to hold cancel.

I don't think that is the case so let's wait a bit on this.

**Comment by neolit123** [comment]
ok, let's unhold.
/hold cancel

**Pull request merged**
