### PR TITLE
using wait.Interrupted instead of deprecated wait.ErrWaitTimeout for utils

### PR DESCRIPTION
**Pull request by wlq1212**
…utils

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
using wait.Interrupted instead of deprecated wait.ErrWaitTimeout for utils

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/pull/107826

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
