### PR TITLE
Update fluentd-gcp configuration

### PR DESCRIPTION
**Pull request by crassirostris**
Related to #32762

Though it's not a final solution to the fluentd OOM problems, it increases number of logs that can be handled without losses by
- switching to the file buffering, making buffering mechanism more resilient
- decreasing size of the buffer, decreasing the amount of memory needed
- decreasing number of threads handling the load, since number of chunks is lower than previous number of threads

which results in decrease in theoretical throughput. Tests to confirm cases covered by this change will follow.

cc @piosz @edsiper @repeatedly please take look and confirm that all of these changed are meaningful.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35618)

### CODE REVIEW

**Comment by repeatedly** [comment]
`num_threads` change looks good.

When all input plugins are in_tail case, `block` action is bit safer than `in_forward` mixed case. But you know `block` action is not good for streaming.
If `exception` doesn't cause any CPU / memory usage problem, using `exception` is better. `in_tail` re-emits same events at every seconds.

Assumed traffic is 2-MB per 5 seconds, right?
If so, `buffer_chunk_limit 2MB` and `flush_interval 5s` seems enough.

**Comment by Crassirostris** [comment]
@repeatedly Thanks for comments

>If exception doesn't cause any CPU / memory usage problem, using exception is better. in_tail re-emits same events at every seconds.

I think we're on the edge already, this additional load can be harmful

I increased number of chunks in containers output plugin to 6, because 2 MB per 5 seconds seems too little. I also introduced changes to the Dockerfile, to use td-agent which includes modern version of libjemalloc.

PTAL on the whole picture. I will follow up with the PR which uses this new image.

**Comment by piosz** [comment]
@igorpeshansky will you find some time to take a look?

**Comment by piosz** [comment]
@igorpeshansky will you find some time to take a look?

**Comment by piosz** [comment]
@edsiper @repeatedly could you please take a look into the second commit also?

**Comment by repeatedly** [comment]
I'm not sure the differences between td-agent and google-fluentd, maybe bundled plugins?, but installation steps seem no problem.

**Comment by piosz** [comment]
LGTM, Thanks!

**Comment by codablock** [comment]
@Crassirostris Is there a reason why this was only changed for fluentd-gcp and not for fluentd-elasticsearch?

**Comment by Crassirostris** [comment]
@codablock Most changes are not needed in the elasticsearch image anyway. As to the config changes, we didn't have any complains to be a reference point for these kind of changes, contrary to fluentd-gcp.

**Pull request merged**
