### PR TITLE
Bump agnhost version to 2.13, and bump up depending images.

### PR DESCRIPTION
**Pull request by fedepaol**
Kitten / nautilus depend on agnhost.

Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:
In https://github.com/kubernetes/kubernetes/pull/87926 we added SCTP support to the `agnhost` image, but we did not promote it nor used the new version.
This PR is the first step to promote and use the new version.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

NONE

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by fedepaol** [comment]
This is the first step for handling https://github.com/kubernetes/kubernetes/issues/89782

**Comment by aojea** [comment]
/ok-to-test
@liggitt seems you've approved the last bump to agnost image, who can review this PR?

**Pull request merged**
