### PR TITLE
Remove pods along with jobs when Replace ConcurrentPolicy is set

### LINKED ISSUE #30442: When running ScheduledJob with ConcurencyPolicy Replace the pods are left behind
I've created a ScheduledJobs as follows:
```yaml
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: test
spec:
  schedule: "*/1 * * * ?"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: test
        spec:
          containers:
          - name: test
            image: gcr.io/google_containers/busybox:1.24
            command: ["sleep", "300"]
          restartPolicy: Never
```
This should replace an existing job with a new one upon next run, so it does the old job is being removed but not its pod. So after a while I have only one job (correct) and two pods (incorrect), one running the old job, the other the new one. I assume this is due to lack of server side deletion (#19054), since currently the job deletion logic is in [JobReaper](https://github.com/kubernetes/kubernetes/blob/7bd2db47f9f70a57fa5ae31a2aabc5cc3f168e94/pkg/kubectl/stop.go#L317). 

@janetkuo depending on timing either you or me need to fix this.
@erictune fyi

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #30442

This builds on #30327 and needs a bit more love in tests.

@janetkuo @erictune fyi

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30451)

### CODE REVIEW

**Comment by janetkuo** [comment]
@soltysh is this one ready for review?

**Comment by soltysh** [comment]
@janetkuo not yet, currently working on fixing tests. But the controller part can be reviewed.

**Comment by soltysh** [comment]
@janetkuo now it's good for review. Although I must admit that the SJ controller needs tighter test than what we have currently, but let's leave it for the stabilization phase.

**Comment by janetkuo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/controller/scheduledjob/controller.go, line 231 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451#-KP-yRF2e_OPOCaozZiq:-KP-yRF3WhcZrRA1eBuf:b-8xaq0r) ([raw file](https://github.com/kubernetes/kubernetes/blob/c40039b7c7f13d21bc0ffe60d6fb1fb109a8304b/pkg/controller/scheduledjob/controller.go#L231)):*
> ```Go
> 					}
> 				}
> 			}
> ```

JobReaper deletes a job by:
1. scale the job to 0
2. delete the job's pods (using selector)
3. delete the job 

Should we follow the same pattern here?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451)*

**Comment by janetkuo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451)*

**Comment by soltysh** [comment]
> JobReaper deletes a job by:
> 1. scale the job to 0
> 2. delete the job's pods (using selector)
> 3. delete the job
> 
> Should we follow the same pattern here?

Yeah, I was struggling with the idea, but I guess you're right. I'll update the PR.

**Comment by soltysh** [comment]
@janetkuo updated, ptal

**Comment by soltysh** [comment]
@k8s-bot test this issue #30261.

**Comment by janetkuo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/controller/scheduledjob/controller.go, line 216 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451#-KP6Ip-XaWV5uxmy9qGP:-KP6Ip-XaWV5uxmy9qGQ:b-w39as8) ([raw file](https://github.com/kubernetes/kubernetes/blob/361cd60bd330bb1c1c8bcd8ee0e2b25a09a807fc/pkg/controller/scheduledjob/controller.go#L216)):*
> ```Go
> 			zero := int32(0)
> 			job.Spec.Parallelism = &zero
> 			job, err = jc.UpdateJob(job.Namespace, job)
> ```

Check the job's Spec.Parallelism before updating it 

---

*[pkg/controller/scheduledjob/controller.go, line 226 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451#-KP6If40RjXYIK652PCF:-KP6If40RjXYIK652PCG:b-5iv66g) ([raw file](https://github.com/kubernetes/kubernetes/blob/361cd60bd330bb1c1c8bcd8ee0e2b25a09a807fc/pkg/controller/scheduledjob/controller.go#L226)):*
> ```Go
> 			podList, err := pc.ListPods(job.Namespace, options)
> 			if err != nil {
> 				recorder.Eventf(&sj, api.EventTypeWarning, "FailedDelete", "Deleted job-pod: %v", err)
> ```

The event should be about listing pods?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30451)*

**Comment by janetkuo** [comment]
Only nits, LGTM otherwise

**Comment by soltysh** [comment]
Nits addressed, applying lgtm label.

**Pull request merged**
