### PR TITLE
AWS kube-up: collect logs from e2e

### PR DESCRIPTION
**Pull request by justinsb**
By implementing detect-node-names, we are able to collect the logs from
nodes.

### CODE REVIEW

**Comment by justinsb** [comment]
The hope is that this will enable log collection from e2e.  Sadly I don't really have a practical way to actually test this.  But as it stands this should be harmless (at worst).

**Comment by justinsb** [comment]
Not proposing cherry-picking to 1.2 (certainly not until it actually works for the 1.3 branch, and then only if we need it).  cc @bgrant0607

**Comment by bgrant0607** [comment]
cc @ixdy @fejta

**Comment by bgrant0607** [comment]
Yes, it's impossible to debug anything without the test artifacts

**Comment by bgrant0607** [comment]
We could cherrypick this after cutting the release, once we know it's working

**Comment by ixdy** [comment]
Can you spin up a cluster on AWS and call `cluster/log-dump.sh` to test it?

**Comment by justinsb** [comment]
@ixdy - thanks (doh!).  For some reason I was only thinking about this in the context of e2e.  I'll try it out.

**Comment by justinsb** [comment]
Tested and fixed a bunch more problems.  Also rebased against the latest code (which introduced scp), which meant I had to add an ssh helper.  On AWS kube-up, the "name" of the master is the "Name" tag, but the "name" of the nodes is their instance-id.  Not great, but more confusing than problematic.

Not sure if it's going to be possible to cherry-pick this to 1.2 now we have the scp changes also.  I guess we could cherry-pick them back too..  But let's start by collecting 1.3 logs!

**Comment by ixdy** [comment]
cc @spxtr

**Comment by spxtr** [comment]
LGTM

**Comment by ixdy** [comment]
Now getting logs from AWS clusters, yay!
https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-aws/176/artifacts/

**Pull request merged**
