### PR TITLE
Use legacyscheme's types rather than testapi ones in serialization test

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
~~https://github.com/kubernetes/kubernetes/pull/83671 added flowcontrol type, although we run alpha tests it should be also registered in the testapi.~~

/assign @deads2k @liggitt 
/cc @sallyom @p0lyn0mial 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sallyom** [comment]
/lgtm

thanks @soltysh

**Review by sallyom — APPROVED** [review]

**Comment by liggitt** [comment]
Is there a bug this is fixing?

I would *strongly* prefer we not add more things to the testapi package, and instead continue trimming out uses of it. We have alternate methods of getting a scheme with all known types registered to it via the legacy scheme. Can we switch to using that instead?

**Comment by liggitt** [comment]
/lgtm
/approve
/hold cancel

FYI, follow up will remove the testapi package entirely in https://github.com/kubernetes/kubernetes/pull/86256

**Comment by liggitt** [comment]
pull-kubernetes-node-e2e-containerd failure is unrelated and non-blocking

**Comment by liggitt** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/86256 got in first

/close

**Pull request closed without merging**
