### PR TITLE
kubeadm: remove the deprecated "--cri-socket" flag for "upgrade apply"

### LINKED ISSUE #1356: Deprecate and remove --cri-socket flag from kubeadm upgrade apply
For historical reasons `kubeadm upgrade apply` accepts a `--cri-socket` flag.
This is no longer needed, because the CRI socket of the node is stored in the NodeRegistrationOptions of the node at the cluster.
During `kubeadm upgrade apply` it is much safer and less error prone to fetch the CRI socket from the cluster, rather than rely on the user to supply the same value as upon `kubeadm init` or `kubeadm join`.

Timeline:
1. Mark the flag as deprecated (in 1.14).
- [X] kubernetes/kubernetes#69366
2. Remove the flag (+3 releases from deprecation - from 1.17 on wards)
- [ ] https://github.com/kubernetes/kubernetes/pull/85044

/kind cleanup
/lifecycle active
/assign
/priority important-longterm
/cc @fabriziopandini

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

Remove the flag "--cri-socket" from the "kubeadm upgrade apply"
command. It has been marked as deprecated since 1.14.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1356

**Special notes for your reviewer**:
Are we OK removing this given the `--config` situation for `upgrade apply`?

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: remove the deprecated "--cri-socket" flag for "kubeadm upgrade apply". The flag has been deprecated since v1.14.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @rosti @yastij 
/priority important-longterm
/kind cleanup
/hold

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/lgtm

**Comment by ereslibre** [comment]
I'm +1 for removing this flag.

/lgtm

Leaving hold cancel to @rosti.

**Review by fabriziopandini — APPROVED** [review]
+1 from my side

**Comment by neolit123** [comment]
unholding tomorrow afternoon UTC.

**Review by rosti — APPROVED** [review]
Thanks @neolit123 !
/lgtm
/hold cancel

**Pull request merged**
