### PR TITLE
GCE: skip updating and deleting external loadbalancer if service is managed by ingress-gce

### PR DESCRIPTION
**Pull request by panslava**
GCE: skip updating and deleting external load balancer if service is managed by ingress-gce
External load balancer services managed by ingress-gce should be annotated and use special finalizer.

What type of PR is this?
/kind bug

What this PR does / why we need it:
GCE: skip updating and deleting external load balancer if service is managed by ingress-gce
Otherwise service controller prints errors and has race condition with new Ingress-GCE controller
With this PR we avoid misleading error log line and API call to GCE.

Which issue(s) this PR fixes:
None, we noticed the issue internally

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by cezarygerard — APPROVED** [review]
/lgtm

**Comment by nckturner** [comment]
/approve
This is a bug fix.

**Pull request merged**
