### PR TITLE
Move upgrade jobs to version control

### LINKED ISSUE #17263: Build sustainable, reasonable upgrade and version-skewed test infrastructure
#14778 got us through the v1.1 release, but it didn't go very smoothly and should be better for v1.2.

### PR DESCRIPTION
**Pull request by ikehz**
Move upgrade jobs to version control.

Part of #18122; fixes #17263.  Woohoo!

### CODE REVIEW

**Comment by spxtr** [comment]
Have you tested this since you made the changes today?

**Comment by ihmccreery** [comment]
Generates XML no problem:

```
INFO:jenkins_jobs.builder:Number of jobs generated:  65
INFO:jenkins_jobs.builder:Job name:  jenkins-gcloud-update
INFO:jenkins_jobs.builder:Job name:  jenkins-gcloud-update-all
INFO:jenkins_jobs.builder:Job name:  kubernetes-build
INFO:jenkins_jobs.builder:Job name:  kubernetes-build-1.0
INFO:jenkins_jobs.builder:Job name:  kubernetes-build-1.1
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-autoscaling
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-flaky
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-flannel
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-parallel
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-parallel-flaky
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-reboot
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-scalability
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gce-slow
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gke-ci
INFO:jenkins_jobs.builder:Job name:  kubernetes-e2e-gke-ci-reboot
INFO:jenkins_jobs.builder:Job name:  kubernetes-update-jenkins-jobs
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-1.1-master-step7-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gce-stable-current-release-step7-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-current-release-step7-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.0-master-step7-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-1.1-master-step7-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step1-deploy
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step2-kubectl-e2e-new
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step3-upgrade-master
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step4-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step5-upgrade-cluster
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step6-e2e-old
INFO:jenkins_jobs.builder:Job name:  kubernetes-upgrade-gke-stable-current-release-step7-e2e-new
```

**Comment by spxtr** [comment]
Looks good. Mind squashing?

**Comment by ihmccreery** [comment]
Done.

**Comment by spxtr** [comment]
@k8s-bot test this again please

**Comment by spxtr** [comment]
@k8s-bot unit test this again please

**Comment by ihmccreery** [comment]
@k8s-oncall I'd like to merge this by hand so I can watch Jenkins.

**Pull request merged**
