### PR TITLE
Add an explicit variable to indicate whether an instance is master or not

### PR DESCRIPTION
**Pull request by cjcullen**

### CODE REVIEW

**Comment by cjcullen** [comment]
@ArtfulCoder

**Comment by cjcullen** [comment]
Also @zmerlynn who was working on this previously.

**Comment by zmerlynn** [comment]
Should we just go ahead and make it an explicit variable?

**Comment by roberthbailey** [comment]
+1 for explicit variable (now that we are past the 0.18.0 cut).

**Comment by cjcullen** [comment]
Fiiiiiine. I added an explicit variable. PTAL.

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
