### PR TITLE
fix patch for anonymous struct fields

### PR DESCRIPTION
**Pull request by deads2k**
cherry-pick for https://github.com/kubernetes/kubernetes/pull/14985

@lavalamp This is my first cherry-pick for kube.  Is this the correct branch?

Fixes https://github.com/kubernetes/kubernetes/issues/14998

### CODE REVIEW

**Comment by lavalamp** [comment]
Yes, thank you-- I think we're trying to have an issue explaining every cherry pick, so if you could make a tracking issue & reference this and #14985 that would be great.

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/kubernetes/issues/14998

**Comment by lavalamp** [comment]
Thanks-- this is LGTM but I think we should wait for #14985 to merge before applying the label.

**Comment by lavalamp** [comment]
LGTM, but shippable is red

**Comment by deads2k** [comment]
jenkins looks like infrastructure failure
```
 > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/14997/*:refs/remotes/origin/pr/14997/* --prune
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/14997/*:refs/remotes/origin/pr/14997/* --prune" returned status code 128:
```

**Comment by deads2k** [comment]
shippable failed on `k8s.io/kubernetes/pkg/kubelet/network/cni`.  Rekicking.

**Comment by ixdy** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@lavalamp is there anything else I need to do for a cherry-pick PR?

**Comment by lavalamp** [comment]
@krousey Nope, just verify that there's an issue for tracking, that it seems like a good idea to cherry-pick, and that the original PR is merged...

**Pull request merged**
