### PR TITLE
Update 1.18 changelog with entries from v1.18.11

### PR DESCRIPTION
**Pull request by puerco**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

This PR updates the Kubernetes 1.18 changelog with  the release notes entries originally destined for v1.18.11.
ref: https://github.com/kubernetes/sig-release/issues/1329, https://groups.google.com/g/kubernetes-dev/c/nJix1xLQvZE

Thanks for [reporting](https://kubernetes.slack.com/archives/C2C40FMNF/p1605217001381000), @brandond! 

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

```docs

```
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
Aarggh github mobile interface 😡

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
/priority critical-urgent

because need to fill the missing changelog

**Comment by cpanato** [comment]
/milestone v1.20

always miss the v :)

**Review by saschagrunert — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
