### PR TITLE
Using inherited context in utils

### PR DESCRIPTION
**Pull request by kerthcet**
This PR focus on utils in scheduler. When to patch pod status or delete pod,
it is better to use an inherited context.
Although this does not take a big effect in preventing goroutine leaks, but it is a better practice.

Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109962

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
👍 

/lgtm

**Comment by kerthcet** [comment]
kindly ping @Huang-Wei

**Comment by kerthcet** [comment]
PTAL @alculquicondor

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Please note that reviewer's availability is limited around freezes

**Pull request merged**
