### PR TITLE
update aws sdk to v1.13.6

### LINKED ISSUE #59409: AWS SDK should be update to support `cn-northwest-1` region
Recently AWS released `cn-northwest-1` region in China, and the vendored AWS SDK by kubernetes is not updated to the latest official version, so the volume function can't used in `cn-northwest-1` region.

### PR DESCRIPTION
**Pull request by liubin**
**What this PR does / why we need it**:

Mainly to fixes #59409 .

**Special notes for your reviewer**:
Used these commands to update the deps:

```
hack/run-in-gopath.sh hack/godep-restore.sh
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/aws/aws-sdk-go'
hack/run-in-gopath.sh go get -d github.com/aws/aws-sdk-go
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/aws/aws-sdk-go checkout v1.13.6'
hack/run-in-gopath.sh hack/godep-save.sh
hack/run-in-gopath.sh hack/verify-godeps.sh

```
**The staging directory updated by  these commands, dose this matter? Should I restore these files?**

**Release note**:

```release-note
Update aws-sdk-go to v1.13.6
```

### CODE REVIEW

**Comment by liubin** [comment]
Hi @jdumars , test pull-kubernetes-verify has failed, it seems that the network had some trouble, can you start a restest ?

Thanks.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60578)

**Pull request closed without merging**
