### PR TITLE
Fix PDB by percentages for StatefulSet pods

### LINKED ISSUE #39125: PodDisruptionBudget by percentage doesn't work with StatefulSets
Is it intentional that the disruption controller isn't aware of StatefulSets? They appear to work together when the budget is configured with a static minimum number of pods, but not when configured with a percentage because the controller `finders` don't include StatefulSets:
https://github.com/kubernetes/kubernetes/blob/f49442d4331052c3141c47a3f9701da7082ebcff/pkg/controller/disruption/disruption.go#L204
https://github.com/kubernetes/kubernetes/blob/f49442d4331052c3141c47a3f9701da7082ebcff/pkg/controller/disruption/disruption.go#L557

The events for the disruption budget resource show the error message from the second link ("Failed to calculate the number of expected pods: asked for percentage, but found no controllers for pod "cockroachdb-0"), leaving it with no idea how many pods are expected.

This is with client and server both at v1.5.1.

@foxish @erictune

### PR DESCRIPTION
**Pull request by foxish**
Previously, PDBs defined in terms of percentages would error out with StatefulSet as they did not know how to find the scale associated.
This change teaches the disruption controller to also look at StatefulSets and their scale.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/39125

**Release note**:
```release-note
Fix issue with PodDisruptionBudgets in which `minAvailable` specified as a percentage did not work with StatefulSet Pods.
```

cc @a-robinson @kow3ns @kubernetes/sig-apps-misc

### CODE REVIEW

**Comment by a-robinson** [comment]
Thanks @foxish!

**Comment by davidopp** [comment]
Thanks a lot for fixing this, @foxish !

@mwielgus can you please review it?

**Comment by foxish** [comment]
@saad-ali, can we cherrypick this fix into the next 1.5.x release?

**Comment by foxish** [comment]
If this is cherrypicked, so should https://github.com/kubernetes/kubernetes/pull/39544

**Pull request merged**
