### PR TITLE
release lib archive docker image name for releases should not have amd64

### PR DESCRIPTION
**Pull request by javier-b-perez**
The docker image name for amd64 is an special case, it is not using the arch in the name, as the rest.
We need to update the release lib to make sure that releases (when KUBE_DOCKER_REGISTRY and KUBE_DOCKER_IMAGE_TAG are defined) follow the same naming convention.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Release archive should be consistent with default container tags.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by javier-b-perez** [comment]
Example (kube-proxy):
KUBE_DOCKER_IMAGE_TAG=v1.13.9-beta.0.59_c00becd203d4ea
KUBE_DOCKER_REGISTRY=gcr.io/my-project

manifest.json:
"RepoTags":["k8s.gcr.io/kube-proxy:v1.13.9-beta.0.59_c00becd203d4ea","gcr.io/my-project/kube-proxy-**amd64**:v1.13.9-beta.0.59_c00becd203d4ea"]

**Comment by BenTheElder** [comment]
why is it a special case? normally we publish a manifest image that combines all of the specific arch ones

**Comment by javier-b-perez** [comment]
> why is it a special case? normally we publish a manifest image that combines all of the specific arch ones

when we do docker save here it is not a manifest, that come later with the release script in k8s/release

**Comment by cblecker** [comment]
is it "better" to fix the other references, and have the arch be explicit?

**Comment by javier-b-perez** [comment]
> is it "better" to fix the other references, and have the arch be explicit?

you mean, have "amd64" in the name for both? the default name and release name?
I think it should be consistent, but not sure what things we can break if we do it.
@thockin might have an idea

I could add a third tag for "amd64" that includes the arch in the name, so the docker tarfile will have 2 or 3 tags (for release). Then eventually we remove this special case. What do you think?

**Comment by cblecker** [comment]
It was a genuine question.. you currently have your hands on these images. I'm okay with keeping as is for now, or trying to move the needle towards a better solution. Interested in your opinion :)

**Comment by javier-b-perez** [comment]
/hold
I will create a new PR to actually drop the special case for amd64 and see what breaks.
Here is some tests:
make quick-release
kube-proxy/manifest.json
"RepoTags":["k8s.gcr.io/kube-apiserver:v1.16.0-alpha.0.2067_794f4a0aaf6a6c","k8s.gcr.io/kube-apiserver-amd64:v1.16.0-alpha.0.2067_794f4a0aaf6a6c"]

export KUBE_DOCKER_IMAGE_TAG=v1.12.99
export KUBE_DOCKER_REGISTRY=gcr.io/my-project
make quick-release
kube-proxy/manifest.json
"RepoTags":["k8s.gcr.io/kube-proxy:v1.16.0-alpha.0.2067_794f4a0aaf6a6c","gcr.io/my-project/kube-proxy:v1.12.99","k8s.gcr.io/kube-proxy-amd64:v1.16.0-alpha.0.2067_794f4a0aaf6a6c"]

**Comment by javier-b-perez** [comment]
I will drop this in favor of https://github.com/kubernetes/kubernetes/pull/80047 to remove the special case for amd64

**Comment by cblecker** [comment]
#80047 merged

/close

**Pull request closed without merging**
