### PR TITLE
Remove pods from the assumed pod list when they are deleted

### PR DESCRIPTION
**Pull request by lavalamp**
Scheduler factory needs a test that constructs a scheduler and tests it. Really this change should be tested there. Thinking about that...

### CODE REVIEW

**Comment by lavalamp** [comment]
@bprashanth @davidopp @abhgupta 

Partial resolution for #6023;

**Comment by bprashanth** [comment]
random nitty comments

**Comment by lavalamp** [comment]
Updated. PTAL

**Comment by lavalamp** [comment]
OK, and test added (yes, the test fails the old behavior). PTAL. Would like to get this in ASAP.

**Comment by bprashanth** [comment]
LGTM

**Comment by abhgupta** [comment]
Is this PR now ready for a merge?

**Comment by bprashanth** [comment]
Not sure if @lavalamp is waiting on/finished e2e, otherwise it should be

**Comment by lavalamp** [comment]
This should be good to go!

**Pull request merged**
