### PR TITLE
Automated cherry pick of #97206: clean up executing request on panic

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #97206 on release-1.20.

#97206: clean up executing request on panic

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by tkashem** [comment]
`pull-kubernetes-bazel-test` will fail until https://github.com/kubernetes/kubernetes/pull/97464 gets merged.

**Comment by MikeSpreitzer** [comment]
This is not going to pass the new test until #97464 merges, right?

**Comment by tkashem** [comment]
> This is not going to pass the new test until #97464 merges, right?

@MikeSpreitzer yes, `pull-kubernetes-bazel-test` will timeout due to the deadlock.

**Comment by MikeSpreitzer** [comment]
No need to retest yet, see https://github.com/kubernetes/kubernetes/pull/97463#issuecomment-750407570

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
