### PR TITLE
[WIP] Add Service objects for Scheduler and ControllerManager

### PR DESCRIPTION
**Pull request by gmarek**
Ref. #18212

cc @wojtek-t @lavalamp @thockin

### CODE REVIEW

**Comment by thockin** [comment]
Why?

**Comment by lavalamp** [comment]
This is not the approach I had in mind. I was thinking you can just make ordinary yaml files and create them on startup, with our other add-on type things. The point of my suggestion was to avoid changing apiserver code :)

**Comment by gmarek** [comment]
OK, I understood why it was a problem for me to understand. I'm using `config-test.sh`, which does not register masters kubelet, and there's no way to create 'normal' service for stuff running there. If we register kubelet, we can proxy to scheduler/controller-manager (well - we still need to listen on 0.0.0.0) without a need of any service. We probably can create those as well.

So first thing is to get #18338 in, and then change interfaces/create services for scheduler/controller-manager.

I'll leave this PR open in case it'll turn out that for some reason we shouldn't depend on Masters Kubelet being registered.

**Comment by lavalamp** [comment]
Registering the master kubelet in GCE seems like the way to go. However,
you'll also need to make it work with unregistered master kubelet if you
want it to work in GKE.

**Comment by gmarek** [comment]
This probably means that I'll need some version of this PR, as I don't think we can point services to something that's not a pod (or am I missing something?).

**Comment by lavalamp** [comment]
You can generate custom endpoints for the service.

**Pull request closed without merging**
