### PR TITLE
Add get permission of "/" to discovery role

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This allows users with discovery role (all authenticated users) to discover known paths.

For https://github.com/kubernetes/kubernetes/issues/122220

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Add get permission of `/` to `system:discovery` role to allow root discovery by authenticated users.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by enj** [comment]
/hold

Expanding access to cluster metadata for all authenticated users isn't something we should do without a very good reason, and since everything is working fine as-is without this today, I can't think of any good enough reason to expand this.

**Comment by enj** [comment]
> > Expanding access to cluster metadata for all authenticated users isn't something we should do without a very good reason, and since everything is working fine as-is without this today, I can't think of any good enough reason to expand this.
> 
> Authenticated users already has access to cluster metadata via the current `system:discovery` role:
> 
> https://github.com/kubernetes/kubernetes/blob/89dfbebe2e823bd0b13e4b65b8460a058c7258a3/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L206-L215
> 
> I think the response of "/" just provides visibility for API discovery in another form, i.e. a flat list.
> 
> @sttts could you share your opinion on this? Is it still worth to add it?

I am aware of what access they have, because it is the minimum required for clients like `kubectl` to work.  `/` isn't required for those use cases, and thus is not appropriate to be granted to all authenticated users.

**Comment by sttts** [comment]
> and since everything is working fine as-is without this today, I can't think of any good enough reason to expand this.

I tend to agree with Mo (and @liggitt who commented similarly elsewhere). Technically, the root path permission, while clearly not a risky operation, is not needed by the system as of today in our libraries and binaries. Keeping the API surface small has merit. While the returned info is clearly for discovery, without a clear usecase we have no reason to change the current permissions.

**Comment by tnqn** [comment]
@enj @sttts Thanks for your inputs. Closing as suggested.

**Pull request closed without merging**
