### PR TITLE
Remove unused kubelet event reasons

### PR DESCRIPTION
**Pull request by houjun41544**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Pingan2017** [comment]
/ok-to-test
/lgtm
/assign @derekwaynecarr @vishh 
  for approval, Thanks!

**Comment by derekwaynecarr** [comment]
/approve
/lgtm

Apologies for losing track of this.

**Pull request merged**
