### PR TITLE
Move "-s -w" flags to GOLDFLAGS as an overridable default.

### PR DESCRIPTION
**Pull request by dims**
Co-Authored-By: @Chenditang <chendt.fnst@cn.fujitsu.com> 
 
If GOLDFLAGS is set, whether it is empty or not, we should honor it.
Only if the GOLDFLAGS is totally not set, then we use "-s -w"

See Parameter Expansion section in the urls below:

https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash/16753536
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

Change-Id: I826c34efc63c77f0e3e9677fff30a3eb2219a377

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
GOLDFLAGS can be specified when compiling, so it is better to set "-s -w" as the overridable default value of GOLDFLAGS.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Following up from the comments in https://github.com/kubernetes/kubernetes/pull/70276/files#r232376981

**Comment by dims** [comment]
seems to work?

```
[dims@dims-mac 09:54] ~/go/src/k8s.io/kubernetes ⟩ env | grep GOLDFLAGS
[dims@dims-mac 09:54] ~/go/src/k8s.io/kubernetes ⟩ echo $GOLDFLAGS

[dims@dims-mac 09:54] ~/go/src/k8s.io/kubernetes ⟩ echo ${GOLDFLAGS="-s -w"}
-s -w
[dims@dims-mac 09:54] ~/go/src/k8s.io/kubernetes ⟩ export GOLDFLAGS=
[dims@dims-mac 09:55] ~/go/src/k8s.io/kubernetes ⟩ echo ${GOLDFLAGS="-s -w"}

[dims@dims-mac 09:55] ~/go/src/k8s.io/kubernetes ⟩ export GOLDFLAGS="-a -b"
[dims@dims-mac 09:55] ~/go/src/k8s.io/kubernetes ⟩ echo ${GOLDFLAGS="-s -w"}
-a -b
```

**Comment by dims** [comment]
/priority important-soon
/sig release
/hold

( holding for review by @ixdy / @cblecker )

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by BenTheElder** [comment]
@dims if you want to wait for them go ahead, AFAICT this change is good, otherwise feel free to `/hold cancel` :-)

**Comment by dims** [comment]
/hold cancel

thanks! @BenTheElder

**Pull request merged**
