### PR TITLE
Kubelet: Add the docker semver back.

### LINKED ISSUE #28221: dockermanager: semver is not parsed correctly
History class:

1) docker [api]version retrieval refactored, removing the semver support [1], 
2) support for semver reverted by [2],
3) support for semver removed again by [3],
4) no support for semver by docker/engine-api [4],

W.r.t to 2), the semver parser was implemented by calling NewVersion of go-semver [5] repository which (as a side effect) thrown away everything after ``-`` character (including) from the version string.

Using engine-api as the semver parser does not provide such a side effect.

Currently, the semver parsing does not return any error. However, it does not work properly for semantic versions due to ``ParseInt`` (alias of ``Atoi``) behaviour [6]. Semver ``1.10.4-28.gitf476348.fc23`` is parsed as ``1.10.0`` instead of expected ``1.10.4``. So the comparison like ``dockerVersion("1.10.3").Compare("1.10.4-28.gitf476348.fc23")`` returns actual ``1`` instead of ``-1``.

[1] https://github.com/kubernetes/kubernetes/pull/19675
[2] https://github.com/kubernetes/kubernetes/pull/20020
[3] https://github.com/kubernetes/kubernetes/pull/23907
[4] https://github.com/docker/engine-api/blob/master/types/versions/compare.go#L10
[5] https://github.com/coreos/go-semver
[6] https://golang.org/pkg/strconv/#ParseInt

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes #28221.
This PR:
1) Add the semver back https://github.com/kubernetes/kubernetes/pull/20020
2) Remove the code in https://github.com/kubernetes/kubernetes/pull/20827, because docker 1.8 is not officially supported now, and we want to deprecate it. https://github.com/kubernetes/kubernetes/pull/27208
3) Add a test for docker version comparison.

XRef https://github.com/kubernetes/kubernetes/pull/28223

@yujuhong 
/cc @ingvagabund 

[Analytics]()

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

(Sorry, temporarily broke Jenkins.)

**Comment by yujuhong** [comment]
```
Verifying ./hack/../hack/verify-govet.sh
pkg/kubelet/dockertools/docker_manager.go:980: arg v for printf verb %q of wrong type: *k8s.io/kubernetes/vendor/github.com/docker/engine-api/types.Version
```

**Comment by Random-Liu** [comment]
@yujuhong That was a mistake. Thanks, :)

**Comment by ingvagabund** [comment]
Assuming the API version is in ``d+.d+`` form, the side effect of semver is back.

@Random-Liu Thanks, closing my PR in favor of yours.

**Comment by Random-Liu** [comment]
The original node e2e test failure is not about this issue, and the kubelet.log is empty with
```
Running as unit kubelet-173886880.service.
```
@k8s-bot test this issue #IGNORE

**Comment by yujuhong** [comment]
> The original node e2e test failure is not about this issue, and the kubelet.log is nearly empty with

What image is this?

**Comment by Random-Liu** [comment]
@yujuhong coreos. :) Seems like unregister_device, but there is no kernel log.

**Comment by yujuhong** [comment]
> @yujuhong coreos. :) Seems like unregister_device? But there is no kernel log.

When did it fail? I'm too lazy to go dig out the logs for the failed build ;) Just wanted to know if it's before or after the fix for #27498 went in.

**Comment by Random-Liu** [comment]
It failed yesterday evening. :)

**Comment by yujuhong** [comment]
> It failed yesterday evening. :)

Oh that's fine. Thanks! Let me know if you see any new failures with the unregister_netdevice message.

**Comment by Random-Liu** [comment]
The test failed because the docker hub was temporarily down.
```
Failed: Failed to pull image "alpine:3.1": Tag 3.1 not found in repository docker.io/library/alpine
```

@k8s-bot test this issue #IGNORE.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #28250.

**Pull request merged**
