### PR TITLE
Fix license verification script

### PR DESCRIPTION
**Pull request by dims**
get `kubernetes-verify-go-licenses-periodical` back on its feet

https://testgrid.k8s.io/sig-testing-misc#kubernetes-verify-go-licenses-periodical&width=20

- Avoid the `print` and then grep, seems to be unreliable, just do it from a file
- Collect intermediate artifacts and the error logs for further analysis

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
will defer to @ameukam's review and lgtm, but is there a way to see this run green before merge, since I assume failures are not blocking or surfacing in presubmits by default?

**Comment by dims** [comment]
@liggitt this script doesn't run in presubmits and does not block anything. It's now green 🟩 

https://testgrid.k8s.io/sig-testing-misc#kubernetes-verify-go-licenses-periodical&width=20

**Pull request merged**
