### PR TITLE
Update comment for garbagecollector

### PR DESCRIPTION
**Pull request by FengyunPan**
Update comment for garbagecollector, update not exist func.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Probably the metrics can be inferred from the workqueue metrics, i.e., we can infer processing time from the job arrival rate and average queue length. @FengyunPan do you agree?

I'll take a closer look after 1.7 release.

**Comment by FengyunPan** [comment]
@caesarxuchao Yeah, it is better to infer processing time from the job arrival rate and average queue length, I will look it too. Thank you.

**Comment by caesarxuchao** [comment]
@FengyunPan i think those metrics ("job arrival rate" and "average queue length") are already published with the workqueue metrics, see https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go. Thus the metrics added in this PR seems unnecessary.

**Comment by FengyunPan** [comment]
@caesarxuchao Ok, I see. So I split this pr, just update comment for garbagecollector, update not exist func.

**Comment by caesarxuchao** [comment]
> On the other hand, "garbagecollector/metrics.go" seems useless. Do you think so? Do it need to be clean up?

Agree, it can be deleted.

**Comment by caesarxuchao** [comment]
Could you update the PR title, then lgtm. Thanks.

**Comment by FengyunPan** [comment]
@caesarxuchao I have created a PR to remove  "garbagecollector/metrics.go", #48525

**Comment by caesarxuchao** [comment]
Thanks @FengyunPan

**Comment by caesarxuchao** [comment]
I'm manually adding the approved label since it's only doc change in gc.

**Pull request merged**
