### PR TITLE
Optimizes calculating stats when only CPU and Memory stats are returned from Kubelet stats/summary http endpoint. 

### PR DESCRIPTION
**Pull request by krzysztof-jastrzebski**
**What this PR does / why we need it**:
PR optimizes calculating stats when only CPU and Memory stats are returned from Kubelet stats/summary http endpoint. After this PR is submitted only CPU and memory stats will be calculated instead of calculating all stats and removing them from response.

**Release note**:
```release-note
Optimizes calculating stats when only CPU and Memory stats are returned from Kubelet stats/summary http endpoint. 
```

### CODE REVIEW

**Comment by yujuhong** [comment]
/assign @dashpole 

@dashpole is working on core metrics and probably have more opinions on this part of the code.

**Comment by dashpole** [comment]
/lgtm
This is basically a copy of the existing `Get()` function stack, but with the unused parts removed.  It copies a lot of code, but given https://github.com/kubernetes/kubernetes/pull/67829#discussion_r215462126, I think this is a decent approach.

**Comment by krzysztof-jastrzebski** [comment]
Could you give approve?

**Comment by yujuhong** [comment]
/approve
based on @dashpole's lgtm

**Pull request merged**
