### PR TITLE
Change the PEM block type to use the constant

### PR DESCRIPTION
**Pull request by jcbsmpsn**

### CODE REVIEW

**Comment by jsafrane** [comment]
Please fix the unit test:
```
W0309 17:26:38.735] # k8s.io/kubernetes/vendor/k8s.io/client-go/util/cert
W0309 17:26:38.736] vendor/k8s.io/client-go/util/cert/csr_test.go:55: undefined: CertificateeRequestBlockType
```

**Comment by jcbsmpsn** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jcbsmpsn** [comment]
@k8s-bot bazel test this

**Comment by jcbsmpsn** [comment]
@jsafrane Ok to go now?

**Comment by jsafrane** [comment]
@k8s-bot kubemark e2e test this

**Comment by jcbsmpsn** [comment]
cc @caesarxuchao

**Pull request merged**
