### PR TITLE
Use `git archive` to produce kubernetes-src.tar.gz when git tree is clean

### LINKED ISSUE #56246: version information missing from kubernetes-src.tar.gz
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: after https://github.com/kubernetes/kubernetes/pull/55353 + related changes to anago, the version information is no longer included in the `kubernetes-src.tar.gz` source tarball produced by `build/lib/release.sh` in releases.

The source tarball from github (which uses `git archive`) is correct, since https://github.com/kubernetes/kubernetes/pull/55353 was designed for that scenario.

/assign
/cc @david-mcmahon 
/sig release

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: uses `git archive` to embed version information in the kubernetes source tarball produced in releases. Due to recent changes, the version information was missing from the source tarball, causing builds from these source tarballs to potentially fail.

This also includes a fix inspired by #56216, since the ld flags in `hack/lib/version.sh` are not space-safe.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56246

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @david-mcmahon 
/priority urgent-soon
/sig release
cc @mrueg

### CODE REVIEW

**Comment by ixdy** [comment]
Tested by running `make quick-release` in a regular git repo with this change, then extracted the resulting `kubernetes-src.tar.gz` into a new directory, and ran `make quick-release` there.

I'm now attempting a build using the `kubernetes-src.tar.gz` from the archive'd build, but I expect it to work as well.

**Comment by jberkus** [comment]
/priority critical-urgent

/remove-priority important-soon

adjusting priorities for code freeze.

**Pull request merged**
