### PR TITLE
Fix flaky test - when gracefully shutting down with Pod priority should be able to gracefully shutdown pods with various grace periods

### LINKED ISSUE #106664: [Flaky test] [sig-node] when gracefully shutting down with Pod priority should be able to gracefully shutdown pods with various grace periods
Flaked a couple of times on serial lane with the same error.

Test is relatively new.

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&exclude-non-failed-tests=20&width=5

This run only has the single test flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1462855916385734656

/sig node
/kind flake
/cc @wzshiming @bobbypage

##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:276
Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc000b83400>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"period-c-5\" is forbidden: no PriorityClass with name custom-class-c was found",
            Reason: "Forbidden",
            Details: {Name: "period-c-5", Group: "", Kind: "pods", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 403,
        },
    }
    pods "period-c-5" is forbidden: no PriorityClass with name custom-class-c was found
occurred
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:99
```
#### Recent failures:
[11/24/2021, 2:55:12 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1463461165735612416)
[11/22/2021, 10:50:10 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1462855916385734656)

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/sig node
/kind flake

#### Which issue(s) this PR fixes:

Fixes #106664

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by wzshiming** [comment]
The log is that PriorityClasses does not seem to exist when the Pod is created, I added a wait after creating PriorityClasses to check whether the creation is really successful

**Comment by dims** [comment]
/retest

this is waiting on @bobbypage review

**Review by matthyx — APPROVED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/approve
/skip
/lgtm

**Comment by wzshiming** [comment]
It seems that the `/test pull-kubernetes-node-kubelet-serial` command can no longer be executed.
Should I rebase it to skip this case?

**Comment by SergeyKanzhelev** [comment]
let me try to close and re-open

/close

**Comment by SergeyKanzhelev** [comment]
I'm out of ideas why this stuck on `pull-kubernetes-node-kubelet-serial`, the job doesn't even exist.

@wzshiming try rebasing or closing this one and sending it as a separate PR?

/skip

**Pull request merged**
