### PR TITLE
Automated cherry pick of #68757: e2e/framework: update kubernetes-anywhere path

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #68757 on release-1.12.

#68757: e2e/framework: update kubernetes-anywhere path

### CODE REVIEW

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubeadm/issues/1224#issuecomment-437515015

/sig cluster-lifecycle
/kind bug
/priority critical-urgent
/release-note-none
/assign @timothysc @feiskyer

without this change 1.12 branch based upgrade tests are broken for the `master-upgrade` test.
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

**Comment by feiskyer** [comment]
ping @timothysc for approval

**Review by timothysc — APPROVED** [review]
This is pretty janky
/lgtm 
/approve

**Pull request merged**
