### PR TITLE
ensuring that logic is checking for differences in listener

### PR DESCRIPTION
**Pull request by frankgreco**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Part of the code for the `ensureLoadBalancer` method for `AWS` checks to see if a listener has changed. If so, it will delete and recreated it. However, this logic is flawed and will result in the lister being deleted/recreated every time even if it hasn't changed. This PR fixes that logic.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Relevant Slack conversation [here](https://kubernetes.slack.com/archives/C718BPBQ8/p1554494840015700).

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

cc @mcrute @andrewsykim

### CODE REVIEW

**Comment by mcrute** [comment]
Thanks for the contribution @frankgreco 

/approve

**Comment by liggitt** [comment]
thanks for the PR, can you add unit tests exercising this so it doesn't regress?

**Comment by frankgreco** [comment]
@liggitt Yes, I'll create a separate PR with unit tests for `EnsureLoadBalancer()`. It's kind of scary that as big as this method is, no unit tests/assertions have ever existed for this method. Given the size of this method, it'll take me a little bit to think through and provide decent tests that provide adequate coverage. cc @mcrute

**Comment by andrewsykim** [comment]
Adding unit tests for `EnsureLoadBalancer` will be difficult for sure. Alternatively you can break the listener sync logic (extracting additions & deletions) into it's own function and just unit test that. Specificall this [block of code](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L1100-L1145) can probably go into it's own function

**Pull request merged**
