### PR TITLE
[FEATURE BRANCH] Pick flow schema updated

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
This is progress on the initial development of the priority and fairness feature (see KEP ref below).  This PR adds an apiserver-local controller to digest configuration API objects, adds an implementation for matching requests against FlowSchema objects, and updates some other plumbing.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is intended to be an update to PR #81224, which currently seems to need updates to the generated swagger and openapi.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[KEP] https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md
```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/test pull-kubernetes-bazel-test
That's a known flake, #81100

**Comment by liggitt** [comment]
flake was fixed in master by https://github.com/kubernetes/kubernetes/pull/80236, fyi

**Comment by MikeSpreitzer** [comment]
With that change,
```
$ kubectl get ns foobarley
```
causes the apiserver to log
```
E0815 22:33:17.639821    2541 reqmgmt.go:59] No User found in context &context.valueCtx{Context:(*context.valueCtx)(0xc0099d6e10), key:0, val:(*request.RequestInfo)(0xc008a0e4d0)} of request &http.Request{Method:"GET", URL:(*url.URL)(0xc00a7c3980), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json"}, "Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"kubectl/v0.0.0 (linux/amd64) kubernetes/$Format"}}, Body:http.noBody{}, GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Host:"localhost:8080", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"127.0.0.1:59148", RequestURI:"/api/v1/namespaces/foobarley", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.valueCtx)(0xc0099d6e40)}

I0815 22:33:17.639961    2541 handler.go:153] kube-aggregator: GET "/api/v1/namespaces/foobarley" satisfied by nonGoRestful

I0815 22:33:17.639992    2541 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/foobarley" satisfied by prefix /api/

I0815 22:33:17.640025    2541 handler.go:143] kube-apiserver: GET "/api/v1/namespaces/foobarley" satisfied by gorestful with webservice /api/v1

I0815 22:33:17.641497    2541 httplog.go:90] GET /api/v1/namespaces/foobarley: (1.687296ms) 404 [kubectl/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:59148]
```

**Comment by MikeSpreitzer** [comment]
That was when accessing the insecure port.

When accessing the secure port with a useful kubeconfig, it gets better:
```
I0815 22:38:37.267662    2541 reqmgmt.go:74] Serving RequestInfo=&request.RequestInfo{IsResourceRequest:true, Path:"/api/v1/namespaces/nothere", Verb:"get", APIPrefix:"api", APIGroup:"", APIVersion:"v1", Namespace:"nothere", Resource:"namespaces", Subresource:"", Name:"nothere", Parts:[]string{"namespaces", "nothere"}}, user.Info=&user.DefaultInfo{Name:"system:admin", UID:"", Groups:[]string{"system:masters", "system:authenticated"}, Extra:map[string][]string(nil)} after queuing

I0815 22:38:37.267754    2541 handler.go:153] kube-aggregator: GET "/api/v1/namespaces/nothere" satisfied by nonGoRestful

I0815 22:38:37.267770    2541 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/nothere" satisfied by prefix /api/

I0815 22:38:37.267782    2541 handler.go:143] kube-apiserver: GET "/api/v1/namespaces/nothere" satisfied by gorestful with webservice /api/v1

I0815 22:38:37.268933    2541 httplog.go:90] GET /api/v1/namespaces/nothere: (1.618421ms) 404 [kubectl/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:60952]
```

**Comment by MikeSpreitzer** [comment]
@81224 merged, this is not needed.

**Pull request closed without merging**
