### PR TITLE
return all errors from RESTStorage registration

### PR DESCRIPTION
**Pull request by deads2k**
If there is an error while registering RESTStorage for any resource only the first error is returned.  This change makes sure that the error is reported to the caller, but error messages are provided for every failing type.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by smarterclayton** [comment]
If a resource can't get registered... Why does the server continue starting up?  Why is this necessary?  Just debugging?

**Comment by deads2k** [comment]
Allowing most of the application to come up and continue working seems to be a better option than completely disabling it.  This is already accepted in concept, since we allow start up to continue even in cases where the app doesn't have the rights to modify iptables rules.  Services will not function properly without those rights, but it is more useful to allow start up with hobbled functionality than to not start up at all.  I view this as a similar situation, functionality may be hobbled by missing resource availability, but it's generally more useful to have something working than nothing.

The caller can still decide to fall over if they want to, but they are no longer forced to fail hard.

**Comment by derekwaynecarr** [comment]
Looked to me it still fails to start, just lets you get the full list of errors instead of doing whack a mole.

**Comment by derekwaynecarr** [comment]
I want app to fail, but give aggregate error.

**Comment by deads2k** [comment]
> I want app to fail, but give aggregate error.

That's what kubernetes does https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L372.  By not failing until after the container.add call in InstallREST, callers now have a choice: detect the error and fail or detect the error and continue hobbled.

**Comment by smarterclayton** [comment]
There is no case I can imagine in which I want the service to start up with partial RESTStorage.  That's a critical prod hole waiting to happen.  But I'm fine with aggregate error (use []error and return errors.NewAggregate).

**Comment by deads2k** [comment]
Renamed the commit and the pull request to more accurately describe what it does

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
