### PR TITLE
Update api.pb.go

### PR DESCRIPTION
**Pull request by Chihoon-Sung**
**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:

For correct spelling.

**Special notes for your reviewer**:

This is my first full request. Please let me know if there is anything wrong with the method or guideline.

### CODE REVIEW

**Comment by Chihoon-Sung** [comment]
i signed a Contributor License Agreement (CLA).

**Comment by hwdef** [comment]
/ok-to-test
LGTM

**Comment by hwdef** [comment]
/hold
Vendor folder does not need modify.

**Comment by Chihoon-Sung** [comment]
> / hold
> 공급 업체 폴더는 수정할 필요가 없습니다.

Thanks for your reply! Is the reason why it wasn't accepted is because it was trivial?

**Comment by hwdef** [comment]
@Chihoon-Sung 
Because this folder is the third party code, it is not the code of k8s. 
If you really want modify this, you should submit a PR in `github.com/libopenstorage/openstorage` repository

**Pull request closed without merging**
