### PR TITLE
Additional mount comments

### PR DESCRIPTION
**Pull request by codenrhoden**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In https://github.com/kubernetes/utils/pull/100, @thockin asked for additional clarification on these methods.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @msau42 
/assign @saad-ali

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm cancel

Where we last left off, we wanted to remove the Exec interface from the mounter library

**Comment by codenrhoden** [comment]
> Where we last left off, we wanted to remove the Exec interface from the mounter library

I have been working on that this week. Two issues around it have cropped up. One is just around testing when using `k8s.io/utils/exec`, and I am blocked by a PR help out with that: https://github.com/kubernetes/utils/pull/118.

The second is whether or not the mount containers feature is still in use. Basically this code [here](https://github.com/kubernetes/kubernetes/blob/46dd075babbd90be86a4c3ccd8cd9a4bf2707e7d/pkg/kubelet/volume_host.go#L306-L343). This is a special exec implementation for when the mount utilities are actually running in a container in a pod. There's no specific "problem" here, but moving to `k8s.io/utils/exec` means I have to make that `containerExec` piece implement the full interface found  in `k8s.io/utils/exec`. not hard, just a good bit of unnecessary code that won't be used. I've gotten some feedback from @msau42 and @jsafrane that the container mount feature is not needed any more... But I'm not sure about how the deprecation policy applies to that alpha feature.

**Comment by msau42** [comment]
> I'm not sure about how the deprecation policy applies to that alpha feature.

alpha features can be removed immediately: https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation

**Comment by codenrhoden** [comment]
> alpha features can be removed immediately: https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation

Since the removal of exec mount would vastly simplify things, I'm happy to take this on. Since it's an alpha feature gate, sounds like we can just remove it. But do we need to do anything like lazy-consensus via k-dev first? Or should I just open a PR? :)

**Comment by msau42** [comment]
I think a courtesy email to sig storage is sufficient

**Comment by codenrhoden** [comment]
/assign @cofyc 
@cofyc here is an additional change to the comments for `GetMountRefs` I had queued up. I wanted to make sure it made sense to you in addition to your change in #84413 

@msau42 I removed the change to comments for the `Exec` interface since that's about to go away completely, and then this PR won't have to rebased. :)

@saad-ali I think this should be good to go for you to take a look at.

**Comment by cofyc** [comment]
/hold
pathname cannot be “device”, please remove it
It is not supported yet (no use cases), see the ref link in #84413

**Comment by codenrhoden** [comment]
> pathname cannot be “device”, please remove it
> It is not supported yet (no use cases), see the ref link in #84413

Thanks @cofyc ! I missed that link in your PR description. I've removed `"device"` from the comment.

**Review by saad-ali — APPROVED** [review]
/approve
/lgtm
/milestone v1.17

**Pull request merged**
