### PR TITLE
[DO NOT MERGE] | debugging pull-kubernetes-e2e-gci-gce-ipvs flakes

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
This PR is to debug pull-kubernetes-e2e-gci-gce-ipvs failures

#### What this PR does / why we need it:
/kind flake

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aroradaman** [comment]
Attempt - **1**
**ExternalTrafficPolicyLocal** 
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 2
ExternalTrafficPolicyLocal
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675091838416982016
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 3
ExternalTrafficPolicyLocal
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675103325311209472
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 4
ExternalTrafficPolicyLocal
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675115194759516160
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 5
ExternalTrafficPolicyLocal
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675146341463887872
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 6
ExternalTrafficPolicyLocal
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675175655643287552
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
6/6 All test cases passed after setting external traffic policy to local

**Comment by aroradaman** [comment]
Attempt - 1
ExternalTrafficPolicyRemote
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675187519697719296
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 2
ExternalTrafficPolicyRemote
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675187519697719296
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 1
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675187519697719296
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 2
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675222862312509440
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 3
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675237306702761984
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 4
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675250267920011264
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 5
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675339357520662528
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
Attempt - 5
ExternalTrafficPolicyCluster
Link - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1675393374334488576
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
4/6 test cases passed on current kubernetes master

**Comment by aojea** [comment]
> 6/6 All test cases passed after setting external traffic policy to local

so there should be some race condition when is cluster, can we know the scenarios when it happens?
I mean, it may be possible that is happening only when the LB sent the traffic to a node where there is no pod, and the node bounced back the packet to another node

**Comment by aroradaman** [comment]
@uablrek @aojea interesting thing I observed in kube-proxy logs.
I was experimenting with kind/metallb and running a udp lb service backed by a deployment with single replica. On deleting the pod I saw conntrack entries being cleared up before the endpoint/real-server was removed from ipvs destinations.

**syncProxyRules**  was called twice, in the first call conntrack entry is deleted and second one programs the ipvs.
Possible race condition in EndpointsMapUpdate ? Should I follow this direction ?

```
I0705 18:55:57.036193       1 config.go:133] "Calling handler.OnEndpointSliceUpdate"
I0705 18:55:57.036324       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:tcp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.036339       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:udp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.036354       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:tcp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.036360       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:udp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.036374       1 endpoints.go:434] "Deleted endpoint may have stale conntrack entries" portName="default/test:udp" endpoint="10.244.2.11:80"
I0705 18:55:57.036388       1 proxier.go:947] "Syncing ipvs proxier rules"
I0705 18:55:57.090660       1 iptables.go:423] "Running" command="iptables-restore" arguments=["-w","5","-W","100000","--noflush","--counters"]
I0705 18:55:57.189145       1 cleanup.go:63] "Deleting conntrack stale entries for services" IPs=[]
I0705 18:55:57.189212       1 cleanup.go:69] "Deleting conntrack stale entries for services" nodePorts=[]
I0705 18:55:57.189304       1 conntrack.go:66] "Clearing conntrack entries" parameters=["-D","-p","udp","--dport","31111","--dst-nat","10.244.2.11"]
I0705 18:55:57.203745       1 conntrack.go:66] "Clearing conntrack entries" parameters=["-D","--orig-dst","10.96.27.104","--dst-nat","10.244.2.11","-p","udp"]
I0705 18:55:57.211994       1 conntrack.go:66] "Clearing conntrack entries" parameters=["-D","--orig-dst","172.18.255.200","--dst-nat","10.244.2.11","-p","udp"]
I0705 18:55:57.216988       1 conntrack.go:71] "Conntrack entries deleted" output=<
	conntrack v1.4.6 (conntrack-tools): 1 flow entries have been deleted.
	udp      17 119 src=172.18.0.1 dst=172.18.255.200 sport=54321 dport=80 src=10.244.2.11 dst=10.244.2.1 sport=80 dport=60123 [ASSURED] mark=0 use=1
 >
I0705 18:55:57.217011       1 proxier.go:938] "syncProxyRules complete" elapsed="180.723941ms"







I0705 18:55:57.217020       1 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 0s, periodic in 30s
I0705 18:55:57.494001       1 config.go:133] "Calling handler.OnEndpointSliceUpdate"
I0705 18:55:57.494181       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:tcp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.494223       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="default/test:udp" endpoints=["10.244.2.11:80"]
I0705 18:55:57.494261       1 proxier.go:947] "Syncing ipvs proxier rules"
I0705 18:55:57.529704       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="10.96.27.104:80/TCP/10.244.2.11:80"
I0705 18:55:57.529722       1 graceful_termination.go:169] "Trying to delete real server" realServer="10.96.27.104:80/TCP/10.244.2.11:80"
I0705 18:55:57.529756       1 graceful_termination.go:183] "Deleting real server" realServer="10.96.27.104:80/TCP/10.244.2.11:80"
I0705 18:55:57.529861       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="172.18.255.200:80/TCP/10.244.2.11:80"
I0705 18:55:57.529871       1 graceful_termination.go:169] "Trying to delete real server" realServer="172.18.255.200:80/TCP/10.244.2.11:80"
I0705 18:55:57.529905       1 graceful_termination.go:183] "Deleting real server" realServer="172.18.255.200:80/TCP/10.244.2.11:80"
I0705 18:55:57.530006       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="10.244.2.1:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530015       1 graceful_termination.go:169] "Trying to delete real server" realServer="10.244.2.1:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530053       1 graceful_termination.go:183] "Deleting real server" realServer="10.244.2.1:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530150       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="172.18.0.3:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530157       1 graceful_termination.go:169] "Trying to delete real server" realServer="172.18.0.3:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530190       1 graceful_termination.go:183] "Deleting real server" realServer="172.18.0.3:31111/TCP/10.244.2.11:80"
I0705 18:55:57.530281       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="10.96.27.104:80/UDP/10.244.2.11:80"
I0705 18:55:57.530287       1 graceful_termination.go:169] "Trying to delete real server" realServer="10.96.27.104:80/UDP/10.244.2.11:80"
I0705 18:55:57.530320       1 graceful_termination.go:183] "Deleting real server" realServer="10.96.27.104:80/UDP/10.244.2.11:80"
I0705 18:55:57.530404       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="172.18.255.200:80/UDP/10.244.2.11:80"
I0705 18:55:57.530410       1 graceful_termination.go:169] "Trying to delete real server" realServer="172.18.255.200:80/UDP/10.244.2.11:80"
I0705 18:55:57.530436       1 graceful_termination.go:183] "Deleting real server" realServer="172.18.255.200:80/UDP/10.244.2.11:80"
I0705 18:55:57.530507       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="10.244.2.1:31111/UDP/10.244.2.11:80"
I0705 18:55:57.530512       1 graceful_termination.go:169] "Trying to delete real server" realServer="10.244.2.1:31111/UDP/10.244.2.11:80"
I0705 18:55:57.530543       1 graceful_termination.go:183] "Deleting real server" realServer="10.244.2.1:31111/UDP/10.244.2.11:80"
I0705 18:55:57.530617       1 proxier.go:1952] "Using graceful delete" uniqueRealServer="172.18.0.3:31111/UDP/10.244.2.11:80"
I0705 18:55:57.530623       1 graceful_termination.go:169] "Trying to delete real server" realServer="172.18.0.3:31111/UDP/10.244.2.11:80"
I0705 18:55:57.530651       1 graceful_termination.go:183] "Deleting real server" realServer="172.18.0.3:31111/UDP/10.244.2.11:80"
I0705 18:55:57.532940       1 ipset.go:171] "Successfully deleted legacy ip set entry from ip set" ipSetEntry="10.244.2.11,udp:80,10.244.2.11" ipSet="KUBE-LOOP-BACK"
I0705 18:55:57.533693       1 ipset.go:171] "Successfully deleted legacy ip set entry from ip set" ipSetEntry="10.244.2.11,tcp:80,10.244.2.11" ipSet="KUBE-LOOP-BACK"
I0705 18:55:57.544361       1 iptables.go:423] "Running" command="iptables-restore" arguments=["-w","5","-W","100000","--noflush","--counters"]
I0705 18:55:57.745801       1 proxier.go:1455] "Network programming" endpoint="default/test" elapsed=0.745727376
I0705 18:55:57.746209       1 cleanup.go:63] "Deleting conntrack stale entries for services" IPs=[]
I0705 18:55:57.746236       1 cleanup.go:69] "Deleting conntrack stale entries for services" nodePorts=[]
I0705 18:55:57.746254       1 proxier.go:938] "syncProxyRules complete" elapsed="252.130096ms"
```

**Comment by uablrek** [comment]
> syncProxyRules was called twice, in the first call conntrack entry is deleted and second one programs the ipvs.
Possible race condition in EndpointsMapUpdate ? Should I follow this direction ?

If this is on a delete of a POD it doesn't explain why the _firsts_ connect fails, which seem to be the most common case. I checked the code (https://github.com/kubernetes/kubernetes/pull/118844#issuecomment-1608269856) and IMO it is correct, ipvs is configured first and conntrack cleared afterwards. Last in your log there is a "Deleting conntrack stale entries...", I think that should catch any incorrect entries introduced caused by packets in the gap.

**Comment by aroradaman** [comment]
/test pull-kubernetes-e2e-gci-gce-ipvs

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1676985323847946240

**Comment by aroradaman** [comment]
>  ipvs is configured first and conntrack cleared afterwards. Last in your log there is a "Deleting conntrack stale entries...", I think that should catch any incorrect entries introduced caused by packets in the gap.

@uablrek yes ipvs is configured first in the proxier and conntrack cleared afterwards but in this log it looked like conntrack was cleared before programming ipvs and once the conntrack is cleared the [state will be lost](https://github.com/kubernetes/kubernetes/issues/112604#:~:text=When%20syncProxyRules%20runs,been%20lost%20forever) , hence the log lines "Deleting conntrack stale entries..." won't be doing anything

I'm aware of the flow in ipvs proxier, maybe this has something to do with endpoint tracker, a race condition perhaps ?

Same thing can also happen when the first pod doesn't receive traffic, what if the conntrack entries which could blackhole traffic were removed before programming the service/endpoints leaving the same window open ?

**Comment by aroradaman** [comment]
<RETESTING>

**Comment by aroradaman** [comment]
[1] - /test pull-kubernetes-e2e-gci-gce-ipvs

**Pull request closed without merging**
