### PR TITLE
Add PR #89069 Action Required to 1.19 release notes

### PR DESCRIPTION
**Pull request by dekkagaijin**
Semi-automated cherry pick of https://github.com/kubernetes/kubernetes/pull/94261

/kind documentation
/kind bug
/priority critical-urgent

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/approve

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

**Comment by dekkagaijin** [comment]
ping @kubernetes/release-managers

**Comment by justaugustus** [comment]
Sorry @dekkagaijin! I thought this was already merged :/

**Comment by dekkagaijin** [comment]
@justaugustus water under the branch

**Pull request merged**
