### PR TITLE
Use the core client with explicit version

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
Use the core client with explicit version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```
NONE

```

### CODE REVIEW

**Comment by zouyee** [comment]
ping @jingxu97

**Comment by rootfs** [comment]
@zouyee can you update the rest of the plugins as well (looks azure_file, rbd, iscsi, and storageos all have some left overs from commit 4c8539cec)

**Comment by zouyee** [comment]
@rootfs ok, I will update the rest.

**Comment by zouyee** [comment]
closed

**Pull request closed without merging**
