### PR TITLE
Clean up and remove blank lines

### PR DESCRIPTION
**Pull request by jiatongw**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Clean up e2e framework code. Referred issues:  #76206  (parent issue #75601 )

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jiatongw — COMMENTED** [review]
This file is pretty clean. Removed some blank lines. 
Just one concern: to use [ExpectNoErr()](https://github.com/kubernetes/kubernetes/blob/df2072dd19812a8c16b27c68e97c27a382210787/test/e2e/framework/gpu_util.go#L52) here or `klog.Errorf()`? The previous one seems to use more memory
cc @andrewsykim @neolit123

**Comment by andrewsykim** [comment]
Thoughts on moving this file into it's own package `test/e2e/framework/gpu`?

**Comment by SataQiu** [comment]
Thanks @jiatongw 
I agree with @andrewsykim. 
It is better to put `gpu_utils.go` into it's own logical package.
/cc @SataQiu

**Review by neolit123 — COMMENTED** [review]
/approve
/ok-to-test
/kind cleanup
/priority backlog

**Review by SataQiu — APPROVED** [review]

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Pull request merged**
