### PR TITLE
Ensure docker daemon opts are in effect before docker login

### PR DESCRIPTION
**Pull request by kwmonroe**
**What this PR does / why we need it**:
Make sure the kubernetes-worker charm is using the configured `docker-opts` daemon options prior to running the `docker-logins` handler.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/juju-solutions/layer-docker/issues/112
**Special notes for your reviewer**:

**Release note**:

```release-note
Fixed charm issue where docker login would run prior to daemon options being set. 
```

### CODE REVIEW

**Comment by ktsakalozos** [comment]
I am a bit sceptical about this PR. Let's suppose we are on a fresh deployment and the user changes the docker login configuration. We will go into the docker_logins_changed() and since it is the first time we call data_changed('docker-opts',...) we will do an early exit. Reactive will think 'config.changed.docker-logins' was handled and we will not retry the docker_logins_changed method.

**Comment by kwmonroe** [comment]
@ktsakalozos thanks for the review.  The reactive loop would actually re-execute the config-changed handler because it would notice the `docker.restart` flag change, but this was not obvious, and would probably drive future maintainers crazy.

I've split the logic into 2 handlers so it's more obvious what/how things are working. Please have another look.

**Comment by ktsakalozos** [comment]
Thank you @kwmonroe

**Pull request merged**
