### PR TITLE
Fixed indent for some statefulset for e2e test.

### LINKED ISSUE #45526: ci-kubernetes-e2e-gce-statefulset failed
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Please refer to https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-statefulset/5669 for detail.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/statefulset.go:540
Expected error:
    <*errors.errorString | 0xc420121f10>: {
        s: "yaml: line 23: did not find expected key",
    }
    yaml: line 23: did not find expected key
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:76
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:
Make sure the e2e test passed for statefulset.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #45526

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by gyliu513** [comment]
I also did some test as following:

```
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl create -f test/e2e/testing-manifests/statefulset/mysql-galera/statefulset.yaml
statefulset "mysql" created
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl delete -f test/e2e/testing-manifests/statefulset/mysql-galera/statefulset.yaml
statefulset "mysql" deleted
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl create -f test/e2e/testing-manifests/statefulset/redis/statefulset.yaml
statefulset "rd" created
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl delete -f test/e2e/testing-manifests/statefulset/redis/statefulset.yaml
statefulset "rd" deleted
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl create -f test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml
statefulset "zoo" created
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl delete -f test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml
statefulset "zoo" deleted
```

**Comment by rmmh** [comment]
/lgtm

Thanks!

**Pull request merged**
