### PR TITLE
#24028 - kube-down delete dhcp resources

### PR DESCRIPTION
**Pull request by ajohnstone**
#24028 - kube-down delete dhcp resources

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24081)

### CODE REVIEW

**Comment by brendandburns** [comment]
@justinsb since this is deep in the weeds of AWS

**Comment by justinsb** [comment]
I agree with deleting the DHCP option set, particularly it is tagged with the cluster.

But is there a reason for the xargs approach, vs the loop-based approach we use (for example) immediately above your change?

**Comment by ajohnstone** [comment]
@justinb the loop based examples felt a little verbose and as an example could be collapsed. Most of the kube-down function is simply loop and delete the particular item.

I deliberately used echo and xargs to avoid incompatibility for the option, no-run-if-empty as that's not available on all distros and secondly aws cli does not support multiple arguments for many of the delete options.

**Comment by justinsb** [comment]
I think it's nice, but I'd rather not introduce another idiom here.  Can we just use a loop?

**Pull request closed without merging**
