### PR TITLE
Automated cherry pick of #45201 upstream release 1.6

### PR DESCRIPTION
**Pull request by divyenpatel**
Cherry pick of #45201 on release-1.6.

#45201 : Same internal and external ip for vSphere Cloud Provider.

@BaluDontu @tusharnt

### CODE REVIEW

**Comment by enisoc** [comment]
@k8s-bot ok to test

**Comment by divyenpatel** [comment]
@enisoc Can you help to merge this PR to release 1.6?

**Comment by divyenpatel** [comment]
@k8s-bot kubemark e2e test this

**Comment by divyenpatel** [comment]
@k8s-bot unit test this

**Pull request merged**
