### PR TITLE
[Federation][(Un)join-01] Add a shell join command to kubectl.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PRs #35153 and #35155 which will be reviewed independently.

cc @kubernetes/sig-cli @pwittrock @kubernetes/sig-cluster-federation @nikhiljindal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35154)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Generally we do proposals for changes of this size - i would at least appreciate being pointed to a proposal that describes future "join" commands and why this deserves a top level command (I cannot find any discussion of this prior to this PR)

**Comment by madhusudancs** [comment]
@smarterclayton The proposal is here - https://github.com/kubernetes/kubernetes/pull/34484. And SIG-CLI was cc'ed.

**Comment by liggitt** [comment]
>> This takes the current user's credentials and uploads them to the federation server?
>
> Yes

That seems improper (and unexpected). I would expect to set up a service account credential for the federation server to use.

**Comment by madhusudancs** [comment]
@liggitt 

> That seems improper (and unexpected). I would expect to set up a service account credential for the federation server to use.

Yeah. That's the direction that we are likely going. This is just emulating the existing flow. Hard to solve two independent problems at once. @nikhiljindal is working on federation auth design. And this workflow will be upgraded to whatever mechanism we decide in that design. Also, `kubectl join federation` will be labelled alpha in v1.5, so it's not like it is set in stone.

**Comment by liggitt** [comment]
let's not ship something that uploads user credentials by default, even as alpha

**Comment by madhusudancs** [comment]
@liggitt That's how it already works today.

Happy to discuss the details. I will see if I can find an issue or I will open a separate one for it.

**Comment by madhusudancs** [comment]
@liggitt here is the issue - https://github.com/kubernetes/kubernetes/issues/35254. Let's discuss the details there.

**Comment by liggitt** [comment]
that issue does not cover how you join a cluster to the federation server. I am specifically objecting to kubectl uploading the current user's credentials as a secret.

**Comment by madhusudancs** [comment]
@liggitt that issue is one of the reasons why we need credentials in the federation. To operate on the clusters, on behalf of users. 

We also need federation to access clusters for health checking purposes and for that we need something akin to service accounts, but the way we need that is to have a service account created in host cluster H (or federation API server) for each cluster in federation C1, C2, ... Cn. Do we support service accounts outside the cluster today? If there is, could you please point me to the documentation? If not, what are the alternatives?

**Comment by liggitt** [comment]
This command is giving the federation server a credential to use to connect to just this one cluster C1? Why not make that credential a service account token recognized by C1? Uploading the current user's credentials to a secret in the federation cluster without them specifically requesting that is not something we should do.

**Comment by madhusudancs** [comment]
@liggitt 

> This command is giving the federation server a credential to use to connect to just this one cluster C1? Why not make that credential a service account token recognized by C1?

That's one alternative. Another alternative is to use the new certificates API where federation makes a CSR to C1 and someone (admin) approves the CSR on C1. We are evaluating the possibilities.


> Uploading the current user's credentials to a secret in the federation cluster without them specifically requesting that is not something we should do.

I do not disagree with that. And I also agree that using the service account is a far better alternative. However, we are not uploading without specially requesting. User is running this command, so they are requesting it.

**Comment by madhusudancs** [comment]
@liggitt btw, just a heads up. I am closing this PR soon since we are creating a new CLI tool for federation which will include this functionality. That's one of the reasons why I am trying really hard to move this discussion off this PR.

**Comment by nikhiljindal** [comment]
Filed https://github.com/kubernetes/kubernetes/issues/35482 to discuss the secrets issue

**Comment by madhusudancs** [comment]
Superseded by PR #35495.

**Pull request closed without merging**
