### PR TITLE
Fix the kube-scheduler binary's description of the --config parameter is inaccurate.

### PR DESCRIPTION
**Pull request by changshuchao**
Signed-off-by: changshuchao <chang.shuchao1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This will give users better guidance.
**Which issue(s) this PR fixes**:

Fixes #
Fix the kube-scheduler binary's description of the --config parameter is inaccurate.

**Special notes for your reviewer**:
After my test, when the --config parameter is set, the following parameters are invalid in the command line: --port, --address, --profiling, --contention-profiling, --kubeconfig,- -kube-api-content-type, --kube-api-qps, --kube-api-burst, --lock-object-namespace, --lock-object-name, --use-legacy-policy-config , --Hard-pod-affinity-symmetric-weight, --leader-elect, --leader-elect-lease-duration, --leader-elect-renew-deadline, --leader-elect-resource-lock,- -leader-elect-resource-name, --leader-elect-resource-namespace, --leader-elect-retry-period.

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by changshuchao** [comment]
@alculquicondor

**Comment by changshuchao** [comment]
/assign @liu-cong @wgliang hi,After my test, when the --config parameter is set, the following parameters are invalid in the command line: --port, --address, --profiling, --contention-profiling, --kubeconfig,- -kube-api-content-type, --kube-api-qps, --kube-api-burst, --lock-object-namespace, --lock-object-name, --use-legacy-policy-config , --Hard-pod-affinity-symmetric-weight, --leader-elect, --leader-elect-lease-duration, --leader-elect-renew-deadline, --leader-elect-resource-lock,- -leader-elect-resource-name, --leader-elect-resource-namespace, --leader-elect-retry-period. so i alert the command line prompt.

Related pr : https://github.com/kubernetes/kubernetes/pull/92531#issuecomment-762879948

**Review by damemi — COMMENTED** [review]
/ok-to-test
This might be a misinterpretation though. You said:
> when the --config parameter is set, the following parameters are invalid in the command line...

But the flag description says
> The following flags can overwrite fields in this file..

This means that for example, passing `--kubeconfig` with `--config` should work (with `--kubeconfig` overwriting the value in the --config file). But `--use-legacy-policy-config` should not work, because it shouldn't overwrite any values

Is it the case that these flags *don't* work when passing `--config` or that they *do* work?

**Comment by alculquicondor** [comment]
I'm leaving this one to Mike :)

**Comment by changshuchao** [comment]
@damemi  sorry,i just made a mistake. i have already alert the command line prompt , wish you review :)

**Pull request closed without merging**
