### PR TITLE
Automated cherry pick of #125690: Fixed metrics missing issue for metrics reference page

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Cherry pick of #125690 on release-1.30.

#125690: Fixed metrics missing issue for metrics reference page
> Once this PR is merged, we can cherry-pick this PR to release-1.30, regenerate the metrics reference file, and copy the metrics reference file to k/website.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
Fixes #https://github.com/kubernetes/website/issues/46818

/kind bug
/cc @richabanker @dims

**Comment by mengjiao-liu** [comment]
Run `./test/instrumentation/update-documentation.sh` script again to regenerate the metrics reference file base `release-1.30`.

**Review by richabanker — APPROVED** [review]

**Comment by mengjiao-liu** [comment]
ping @serathius

**Comment by mengjiao-liu** [comment]
PTAL @logicalhan  @dashpole @serathius 
for approval

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
