### PR TITLE
[1.17] base-images: Update to kube-cross:v1.13.9-5

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Unblocks releases. Tracking issue: https://github.com/kubernetes/release/issues/1281**

~Enables gcloud SDK for stage/release jobs.~

~In https://github.com/kubernetes/release/pull/1258, we moved to using kube-cross for staging/releasing Kubernetes. We need to pull in the latest kube-cross image (`v1.13.9-4`) which includes the necessary packages (`gcloud`, `gsutil`).~

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

(Cherry pick of https://github.com/kubernetes/kubernetes/pull/90963)
ref: https://github.com/kubernetes/release/pull/1279
/assign @cblecker @dims @BenTheElder 
cc: @kubernetes/release-engineering 
/sig release
/area release-eng dependency
/priority critical-urgent

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
base-images: Update to kube-cross:v1.13.9-5
```

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

https://github.com/kubernetes/kubernetes/issues/90963#issuecomment-626504443

**Comment by justaugustus** [comment]
/hold cancel
(since the fixup in kubernetes/release#1279 addresses @cblecker's concerns)

**Comment by fejta** [comment]
BTW what is dependencies.yaml?
/approve

**Pull request merged**
