### PR TITLE
Fix docker root dir detection.

### LINKED ISSUE #18815: kubelet can not detect docker root correctly when using devicemapper
First, kubelet's option `--docker-root` does not help because it is actually a cadvisor option at https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/google/cadvisor/container/docker/factory.go#L42

I find kubelet detects docker root by contact docker runtime when NewDockerManager is called. 
```go
	// Work out the location of the Docker runtime, defaulting to /var/lib/docker
	// if there are any problems.
	dockerRoot := "/var/lib/docker"
	dockerInfo, err := client.Info()
	if err != nil {
		glog.Errorf("Failed to execute Info() call to the Docker client: %v", err)
		glog.Warningf("Using fallback default of /var/lib/docker for location of Docker runtime")
	} else {
		driverStatus := dockerInfo.Get("DriverStatus")
		// The DriverStatus is a*string* which represents a list of list of strings (pairs) e.g.
		// DriverStatus=[["Root Dir","/var/lib/docker/aufs"],["Backing Filesystem","extfs"],["Dirs","279"]]
		// Strip out the square brakcets and quotes.
		s := strings.Replace(driverStatus, "[", "", -1)
		s = strings.Replace(s, "]", "", -1)
		s = strings.Replace(s, `"`, "", -1)
		// Separate by commas.
		ss := strings.Split(s, ",")
		// Search for the Root Dir string
		for i, k := range ss {
			if k == "Root Dir" && i+1 < len(ss) {
				// Discard the /aufs suffix.
				dockerRoot, _ = path.Split(ss[i+1])
				// Trim the last slash.
				dockerRoot = strings.TrimSuffix(dockerRoot, "/")
				glog.Infof("Setting dockerRoot to %s", dockerRoot)
			}

		}
	}
```

This is the info output on my host using the devicemapper driver (docker 1.7.1). There is no key word like "Root Dir" in "DriverStatus". So `dockerRoot` is still "/var/lib/docker" but the actual root is "/data/docker".
```json
{
    "Containers": 81, 
    "CpuCfsPeriod": true, 
    "CpuCfsQuota": true, 
    "Debug": false, 
    "DockerRootDir": "/data/docker", 
    "Driver": "devicemapper", 
    "DriverStatus": [
        [
            "Pool Name", 
            "docker-8:4-99876867-pool"
        ], 
        [
            "Pool Blocksize", 
            "65.54 kB"
        ], 
        [
            "Backing Filesystem", 
            "extfs"
        ], 
        [
            "Data file", 
            "/dev/loop0"
        ], 
        [
            "Metadata file", 
            "/dev/loop1"
        ], 
        [
            "Data Space Used", 
            "2.96 GB"
        ], 
        [
            "Data Space Total", 
            "107.4 GB"
        ], 
        [
            "Data Space Available", 
            "104.4 GB"
        ], 
        [
            "Metadata Space Used", 
            "8.446 MB"
        ], 
        [
            "Metadata Space Total", 
            "2.147 GB"
        ], 
        [
            "Metadata Space Available", 
            "2.139 GB"
        ], 
        [
            "Udev Sync Supported", 
            "true"
        ], 
        [
            "Deferred Removal Enabled", 
            "false"
        ], 
        [
            "Data loop file", 
            "/data/docker/devicemapper/devicemapper/data"
        ], 
        [
            "Metadata loop file", 
            "/data/docker/devicemapper/devicemapper/metadata"
        ], 
        [
            "Library Version", 
            "1.02.89-RHEL6 (2014-09-01)"
        ]
    ], 
    "ExecutionDriver": "native-0.2", 
    "ExperimentalBuild": false, 
    "HttpProxy": "", 
    "HttpsProxy": "", 
    "ID": "454Y:2EOR:BVLI:BVY7:EFCM:W5QD:JRQK:CYAX:HUTI:UFXA:BTGU:ZTG6", 
    "IPv4Forwarding": true, 
    "Images": 128, 
    "IndexServerAddress": "https://index.docker.io/v1/", 
    "InitPath": "/usr/libexec/docker/dockerinit", 
    "InitSha1": "5ebdf15aa01ed2e6fed430918bcec40ed2e72afe", 
    "KernelVersion": "2.6.32-504.16.2.el6.x86_64", 
    "Labels": null, 
    "LoggingDriver": "json-file", 
    "MemTotal": 50495332352, 
    "MemoryLimit": true, 
    "NCPU": 24, 
    "NEventsListener": 0, 
    "NFd": 103, 
    "NGoroutines": 155, 
    "Name": "centos", 
    "NoProxy": "", 
    "OomKillDisable": true, 
    "OperatingSystem": "<unknown>", 
    "RegistryConfig": {
        "IndexConfigs": {
            "docker.io": {
                "Mirrors": null, 
                "Name": "docker.io", 
                "Official": true, 
                "Secure": true
            }
        }, 
        "InsecureRegistryCIDRs": [
            "127.0.0.0/8"
        ]
    }, 
    "SwapLimit": true, 
    "SystemTime": "2015-12-17T17:00:34.98412255+08:00"
}
```

Right now there is no impact except the container logs are not correctly linked under `/var/log/containers`

### PR DESCRIPTION
**Pull request by vishh**
Fixes #18815

### CODE REVIEW

**Comment by dchen1107** [comment]
Can I have some test to cover the issue?

**Comment by vishh** [comment]
Shall I add a test to our new node test suite?

**Comment by vishh** [comment]
ping @dchen1107

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
