### PR TITLE
Fixing spacing in documentation comments

### PR DESCRIPTION
**Pull request by akramer**
There was some ugly spacing in the 'kubectl exec' documentation comments, I've fixed it and wrapped it to 80 chars.

### CODE REVIEW

**Comment by akramer** [comment]
I signed it! Not really, but I did expose my e-mail address.

**Comment by jlowdermilk** [comment]
Thanks for the fix @akramer!

@k8s-bot ok to test this

**Comment by jlowdermilk** [comment]
Oh, shippable is complaining you need to run the tool to regenerate docs. `hack/run-gendocs.sh` from repo root.

**Comment by jlowdermilk** [comment]
LGTM

**Pull request merged**
