### PR TITLE
fix the identifer error

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
more file spell the identifer  error and fix identifier
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign yujuhong
PTAL,thanks!

**Comment by yujuhong** [comment]
/lgtm
/approve no-issue

My lgtm is pretty useless here. You need @thockin's approval

**Comment by thockin** [comment]
The test fail is real.  Need to run a bunch of updaters, can't just change some.

**Comment by jianglingxia** [comment]
/test pull-kubernetes-verify
@fejta-bot  why always failed?

**Comment by fejta** [comment]
/lgtm cancel

Does not pass testing. Please push a common with fixes

**Comment by yujuhong** [comment]
@jianglingxia please do not keep retesting until you fix the errors.
```
I0804 07:06:41.065] [0;31mFAILED TESTS[0m
I0804 07:06:41.065] ========================
I0804 07:06:41.065] [0;31mhack/make-rules/../../hack/verify-api-reference-docs.sh[0m
I0804 07:06:41.065] [0;31mhack/make-rules/../../hack/verify-federation-api-reference-docs.sh[0m
I0804 07:06:41.065] [0;31mhack/make-rules/../../hack/verify-federation-openapi-spec.sh[0m
I0804 07:06:41.066] [0;31mhack/make-rules/../../hack/verify-generated-protobuf.sh[0m
I0804 07:06:41.066] [0;31mhack/make-rules/../../hack/verify-openapi-spec.sh[0m
I0804 07:06:41.066] [0;31mhack/make-rules/../../hack/verify-staging-godeps.sh[0m
I0804 07:06:41.066] [0;31mhack/make-rules/../../hack/verify-swagger-spec.sh[0m
I0804 07:06:41.066] Makefile:126: recipe for target 'verify' failed
W0804 07:06:41.167] make: *** [verify] Error 1
```

**Comment by thockin** [comment]
Please re-assign this to me when you've fixed tests.

**Comment by jianglingxia** [comment]
sorry, in my env cannot download the image :gcr.io/google_containers/gen-swagger-docs:v8
image
so I commit it in another pr ,I will close the PR, thanks very much @thockin

**Pull request closed without merging**
