### PR TITLE
Automated cherry pick of #42859

### PR DESCRIPTION
**Pull request by krzyzacy**
Cherry pick of #42859 on release-1.4.

#42859: Change the junit file name format to

### CODE REVIEW

**Comment by Random-Liu** [comment]
@krzyzacy Several questions:
* Why do we need to cherrypick this?
* Does this only affect test infra?
* Could we cherrypick PRs because of test infra change?

:)

**Comment by krzyzacy** [comment]
@Random-Liu I made a temporary change to https://k8s-testgrid.appspot.com/google-node#kubelet-1.4, which looks funny now because OS name contains the thread id. This is to address https://github.com/kubernetes/test-infra/issues/544, I want to make 1.4 tab looks correct before populate it to all node tabs.

**Comment by krzyzacy** [comment]
@mwielgus @saad-ali do I ask for 1.5 cherry-pick approvals from one of you?

**Comment by krzyzacy** [comment]
@k8s-bot kubemark e2e test this

**Comment by dchen1107** [comment]
Justification for cherrypick: The node e2e test against 5 different images (os distro, different docker versions, etc.) This pr only changes the test result's junit name format, so that it can integrate well with test-infra and testgrid dashboard. No functionalitiy change, no test change.

**Comment by feiskyer** [comment]
@Random-Liu @dchen1107 help removing the do-not-merge label?

**Pull request closed without merging**
