### PR TITLE
kubeadm: Update versions for 1.20

### PR DESCRIPTION
**Pull request by AkhileshK8y**
Signed-off-by: Kommireddy Akhilesh <akhileshkommireddy2412@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR specifies minimum control plane version,
kubelet version and current K8s version for v1.20.

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubeadm/issues/2277

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks!

/ok-to-test
/priority important-soon
/remove-kind cleanup
/kind feature

**Review by neolit123 — COMMENTED** [review]
/milestone v1.20
/approve

**Comment by neolit123** [comment]
@Akhilesh2412 under the line:

```
20: "3.4.13-0",
```

please also add:

```
21: "3.4.13-0",
```

this acts like a placeholder, once the release-1.20 branch is created.
this also solves the "[TODO] Add etcd version for 1.x and placeholder for 1.x+1" task in https://github.com/kubernetes/kubeadm/issues/2277

**Comment by Akhilesh2412** [comment]
> @Akhilesh2412 under the line:
> 
> ```
> 20: "3.4.13-0",
> ```
> 
> please also add:
> 
> ```
> 21: "3.4.13-0",
> ```
> 
> this acts like a placeholder, once the release-1.20 branch is created (solves some issues around release-1.20 -> master upgrades).
> this also solves the "[TODO] Add etcd version for 1.x and placeholder for 1.x+1" task in [kubernetes/kubeadm#2277](https://github.com/kubernetes/kubeadm/issues/2277)

Done.

**Comment by neolit123** [comment]
thanks
/lgtm

**Pull request merged**
