### PR TITLE
reduce code for NewSchedulerCommand func

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
reduce code for NewSchedulerCommand func
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
reduce code for NewSchedulerCommand func
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/triage accepted

**Review by cndoit18 — APPROVED** [review]
LGTM

**Pull request merged**
