### PR TITLE
Fix broken link.

### PR DESCRIPTION
**Pull request by d-kuro**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind documentation

**What this PR does / why we need it**:

Fix broken link for sample-controller README.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by munnerz** [comment]
Thanks 😄

/ok-to-test
/priority backlog
/lgtm
/approve

**Comment by lachie83** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Pull request merged**
