### PR TITLE
Release 1.6

### PR DESCRIPTION
**Pull request by zhihuawu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Several such "Release 1.6" PRs recently. It looks like these were all created by mistake...
#45396 #45205 #44823 #44183 #43733 #43547 #42857

**Comment by xiangpengzhao** [comment]
@zhihuawu FYI: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

**Comment by deads2k** [comment]
@zhihuawu What is this pull trying to do?

**Comment by mwielgus** [comment]
Looks like some kind of cherry-pick mistake. No description, insane commit list. Closing.

**Pull request closed without merging**
