### PR TITLE
Jsonpath like template language 

### PR DESCRIPTION
**Pull request by daizuozhuo**
As discussed in #4348 we need a JSONPath like template language, this is the first feature.

The first week of google summer of code is coming. I implemented the dict and nested dict selection function. For example:
given template：hello ${.jq.title}
and struct: {jq: {title: "world"}}
we will get: hello world

I add quote "" function so that user can input string will not be evaluated:
expression: hello ${"${"}
output: hello ${

I also write unit tests for all files I added. Since this is the first time I participate opensource project, I still have some questions. For this package, how often should I submit the pull request? One feature one pull request? Or one pull request per week to check my process? Thanks!

Please state the features you want here.

### CODE REVIEW

**Comment by erictune** [comment]
Thank you for pointing out that you borrowed code.  That is fine.  However:

If you borrow code from golang, it has to have the Go license on it.
If code has a different license, then it has to go into the third_party
directory.

**Comment by erictune** [comment]
One PR per feature is good.

**Comment by erictune** [comment]
Don't merge until Go license issues resolved.

**Comment by thockin** [comment]
Eric are you the GSOC mentor for this?

**Comment by daizuozhuo** [comment]
@erictune Thanks. I am not familiar with the license problem. By seeing the Go license, I think I should place the Go license on the top of lex.go and parse.go file since I borrow it. 
And for jq.go and the unit test files,  I write it by myself so I put the kubernetes apache license. I think I would not borrow Go code any more for this package.
So in this case, where should I put this package?

**Comment by erictune** [comment]
No.  I'm the guy who one time figured out how to deal with license issues
around code that was copied from Go project.

**Comment by erictune** [comment]
Probably better to assign to the mentor

**Comment by erictune** [comment]
you need to make two packages, one for code you wrote entirely yourself,
and one for any code that you borrowed.
The former can import the latter.
You put the borrowed code under third_party/go/
There are already license files in that directory so you should not modify
the header for the files you borrowed.

**Comment by daizuozhuo** [comment]
I have moved the borrowed code to third_party.

**Comment by bgrant0607** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release.  Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0.  We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why.  We're currently accepting changes that meet any of the following criteria:
1. Changes [directly related to v1.0 issues](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0)
2. Changes [addressing P0 bugs](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0)
3. Changes to supported platforms to bring them up to par with the primary development platforms
4. Docs, user experience, and test related fixes

**Comment by bgrant0607** [comment]
@daizuozhuo We're going to need to hold off merging for now. We need to evaluate whether we're happy with this template language, anyway.

@brendandburns volunteered to be your mentor, but others may want to chime in on the template language, also: @ghodss @jlowdermilk @deads2k

**Comment by daizuozhuo** [comment]
@bgrant0607 Do you mean I should not submit the pull request until v1.0 released, then I submit a "big" pull request?

**Comment by bgrant0607** [comment]
@daizuozhuo No, smaller pull requests are easier to review. Actually, looking at this PR, I think we could merge the code in util and third_party. I suggest creating a standalone tool for now, for testing and evaluation, and don't touch kubectl or other core code at this time.

When we integrate this into kubectl, I think we'll probably add new output formats (e.g., jq, jqfile), and not change or remove the existing template format.

**Comment by daizuozhuo** [comment]
Since People like jsonpath more, I modified my code and changed the pull request title.

**Comment by daizuozhuo** [comment]
@brendandburns when will this pull request be merged? I'm afraid I will commit too many functions in this pull request.

**Comment by thockin** [comment]
We are in a feature freeze right now.  You should be building up your
feature as distinct PRs (branches) or even just distinct commits on one
branch.

**Comment by brendandburns** [comment]
hey @daizuozhuo 

I have created a special gsoc branch, can you do a different PR against that branch?  We can merge your code in there until after freeze.

Thanks!
--brendan

**Pull request closed without merging**
