### PR TITLE
correct the name of the script to generate swagger doc

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**: The name of the script to generate swagger doc is not correct, this PR is to fix it.

**Which issue this PR fixes**: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by supereagle** [comment]
@spxtr  for /approve

**Comment by spxtr** [comment]
/approve no-issue

grumble

**Pull request merged**
