### PR TITLE
Add grammar rules in UnsafeGuestkindToResource function

### LINKED ISSUE #101974: UnsafeGuestkindToResource returns a wrong plural
#### What happened:
When I wrote the unit test, I call the NewSimpleClientset function and use the ObjectTracker.Add method then the Add method call the UnsafeGuestkindToResource function, and I found that there were some problems with the plural generated by the UnsafeGuestkindToResource function.
For example,  the kind is gateway, the function generated "gatewaies".
#### What you expected to happen:
the gateway should have been gateways,
#### Anything else we need to know?:

I considered that this function can not cover all the grammar rules, but it should conform to some of the most common and basic grammar rules.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by ha5ky**
#### What type of PR is this?

/kind bug
/sig api-machinery

#### What this PR does / why we need it:
When I wrote the unit test, I call the NewSimpleClientset function and use the ObjectTracker.Add method then the Add method call the UnsafeGuestkindToResource function, and I found that there were some problems with the plural generated by the UnsafeGuestkindToResource function. For example, the gateway should have been gateways, but the function generated "gatewaies".
I considered that this function can not cover all the grammar rules, but it should conform to some of the most common and basic grammar rules.

#### Which issue(s) this PR fixes:

Fixes #101974

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/unassign
/assign @deads2k 

I personally am not in favor of this code existing at all :)

I think changing it risks version skew issues?

**Comment by ha5ky** [comment]
> /unassign
> /assign @deads2k
> 
> I personally am not in favor of this code existing at all :)
> 
> I think changing it risks version skew issues?

thanks for your view. I thought about the significance of the code in the beginning, I konw UnsafeGuessKindToResource is a heuristic and default match, but I think it should conform to some of the most common and basic grammar rules just like the other code.
And I don't konw why changing it will risks version skew issues?

**Pull request closed without merging**
