### PR TITLE
Revert "Revert "Revert "Bump cadvisor godep"""

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#13296

Reason: it seems to cause e2e test failures - see https://github.com/kubernetes/kubernetes/issues/13236 for more details.

cc @yujuhong @gmarek @lavalamp

### CODE REVIEW

**Comment by piosz** [comment]
cc @jimmidyson

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
merging to confirm if that's the reason for e2e test failures.

**Comment by jimmidyson** [comment]
It looks likely to be the cause - I'm investigating now to try to understand why.

**Comment by wojtek-t** [comment]
@yujuhong @lavalamp - FYI - reverting it seems to help

**Comment by jimmidyson** [comment]
I'm sure you weren't going to but please don't revert this revert of that revert ;) The original PR had some problems & I'll put in an updated one instead.

**Pull request merged**
