### PR TITLE
update vendor for ipvs graceful termination

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:
For now, ipvs proxy mode don't support graceful termination, when a pod be deleted, the connection will be lost immediately, Which my lead to serious problem in some case. 
For more detail, see this issue. #57841 

I raised a pr to solve this problem, for the sake of review, split vendor part here. 
The complete pr is: #66012

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
xref: #57841 

**Special notes for your reviewer**:
Update `github.com/docker/libnetwork/ipvs` and related deps for ipvs support graceful termination. 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
/assign @m1093782566 @sttts 
Please take a look. Hope this can be fixed ASAP.

**Comment by m1093782566** [comment]
/lgtm

Can someone approve this?

**Comment by matthias50** [comment]
Is there a plan to cherry pick this back to 1.12 and/or 1.11 any time soon?

**Comment by matthias50** [comment]
@Lion-Wei , do you know if this is going to be cherry picked back to 1.12 or 1.11?

**Pull request merged**
