### PR TITLE
Fix e2e autoscaling namespace error

### LINKED ISSUE #94809: e2e test failure: error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io "e2e-test-cluster-admin-binding" already exists
##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:54
Sep 15 04:05:10.238: Failed to set up: error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.227.151.106 --kubeconfig=/workspace/.kube/config --namespace=horizontal-pod-autoscaling-8880 create clusterrolebinding e2e-test-cluster-admin-binding --clusterrole=cluster-admin --user=pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com:
Command stdout:

stderr:
error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io "e2e-test-cluster-admin-binding" already exists

error:
exit status 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:264
```
#### Recent failures:
[9/15/2020, 3:31:33 AM ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1305771124411338752)
[9/15/2020, 3:20:00 AM ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa/1305768225241305090)
[9/15/2020, 2:59:54 AM ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1305763192298803200)
[9/15/2020, 2:49:00 AM ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa/1305760424309821440)
[9/15/2020, 2:28:55 AM ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1305755390901751810)

/kind failing-test

/sig autoscaling

Looks like it just started happening today (@ 2020-09-15 03:54:19 +0000 UTC)
image

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
With change of https://github.com/kubernetes/kubernetes/pull/94609.
Parameter namespace in `RunKubectl` will have a actully effect, it will add `--namespace` in command
```
	if tk.Namespace != "" {
		defaultArgs = append(defaultArgs, fmt.Sprintf("--namespace=%s", tk.Namespace))
	}
```
But cases like `Create adapter` it will :
1. create a `clusterrolebinding`.
2. create resources from file which there's namespaces in the file.

In both cases, we don't need `--namespace` flag in the command.

**Which issue(s) this PR fixes**:

Fixes #94809

**Special notes for your reviewer**:
/assign @soltysh 
/assign @neolit123 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
the change looks good to me, thanks.

/approve
/hold for another set of eyes to review
/priority important-soon

**Review by brianpursley — APPROVED** [review]

**Pull request merged**
