### PR TITLE
s:code.google.com/p:github.com/scalingdata:

### PR DESCRIPTION
**Pull request by freeformz**
Because code.google.com is going away. Probably #1 of several.

### CODE REVIEW

**Comment by alex-mohr** [comment]
Travis complains:
$ ./hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./pkg/cloudprovider/aws/aws.go
./pkg/cloudprovider/gce/gce.go
./pkg/cloudprovider/openstack/openstack.go
./pkg/cloudprovider/ovirt/ovirt.go
./pkg/cloudprovider/rackspace/rackspace.go
The command "./hack/verify-gofmt.sh" exited with 1.

Can you please run gofmt?

**Comment by freeformz** [comment]
@alex-mohr Done. Sorry about that. So used to my editor automatically do that ... and these were more mechanically changed.

**Comment by freeformz** [comment]
I rebased this on top of master.

**Comment by erictune** [comment]
ok to test

**Comment by freeformz** [comment]
What do I need to do to get this or an updated version merged?

**Comment by alex-mohr** [comment]
@freeformz Sorry for letting my review fall through the cracks, Edward.  Marked LGTM, but needs yet another rebase -- my apologies!

**Comment by freeformz** [comment]
@alex-mohr rebased again.

**Comment by alex-mohr** [comment]
@k8s-bot please test this

**Comment by alex-mohr** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
closing and re-opening to ping shippable.

**Comment by alex-mohr** [comment]
@freeformz Looks like everything's green, so @k8s-merge-robot should pick it up during its next run.

**Comment by freeformz** [comment]
@brendandburns @k8s-merge-robot doesn't seem to like it anymore?

**Pull request merged**
