### PR TITLE
V0.21.0 merge to master

### PR DESCRIPTION
**Pull request by zmerlynn**
Branch point v0.20.2-470-gdaafc5b

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @alex-mohr @eparis @thockin @roberthbailey

**Comment by thockin** [comment]
LGTM

**Comment by eparis** [comment]
and the release-0.21 branch will start at 708f3a9 ?

**Comment by eparis** [comment]
Or 75fb18a ?  Since we'll need to do the doc dance again every time

**Comment by zmerlynn** [comment]
I'm about to push 708f3a9b557211cb533182cf59fcd7396334e963 as `release-0.21`

**Comment by zmerlynn** [comment]
The revert should only be on master, so if people browse the branch it looks branch-y, and if they check it out, etc.

**Comment by eparis** [comment]
right, but how will you do the revert on 0.21.1 ?  agreed, release-0.21 should be  708f3a9  just thinking about what we wrote this morning and how that relates to 0.21.1

**Comment by eparis** [comment]
/me is thinking we should abandon the backmerge (that I pressed for) and HEAD just always has a .0 patch level.

**Comment by eparis** [comment]
but the backmerge is obviously absolutely essential on .0 (as you did here)

**Comment by eparis** [comment]
This PR LGTM. I don't want anyone seeing my thoughts/discussion to think there is anything at all wrong with this PR.  merge it.

**Comment by zmerlynn** [comment]
The script picks up the commit it just applied and reverts it on a release-looking branch before the actual backmerge.

No complaints about abandoning the backmerge soon. Can we discuss that outside of this PR, though? I'd like to cut 0.21 soon.

**Comment by zmerlynn** [comment]
Cool. Damn the torpedoes, merging.

**Comment by zmerlynn** [comment]
... on green-ish.

**Comment by thockin** [comment]
+1 to killing back-merge insanity in favor of something simpler.

**Comment by zmerlynn** [comment]
I have thoughts on fixing it up, but at this point it would take some retooling.

**Comment by zmerlynn** [comment]
Jenkins has made it past the point where this would break, if it would die in a flaming heap.

**Pull request merged**
