### PR TITLE
Clarify ExternalNames are hostnames

### LINKED ISSUE #52266: Clarify ExternalNames are hostnames not DNS names
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The documentation claims that `ExternalNames` should be DNS names, but stricter RFC-1123 hostname validation is enforced.

**What you expected to happen**:
The documentation should either specify that they need to be valid RFC-1123 hostnames, or the code should not reject valid DNS names.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `Service` with an `externalName` of `db_eu.example.com`, it throws the following error:

```
The Service "db-eu" is invalid: spec.externalName: Invalid value: "db_eu.example.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2

### PR DESCRIPTION
**Pull request by adnavare**
Updates the types documentation for ExternalName to clarify
that they adhere RFC-1123 hostname and are not DNS names.

Fixes #52266 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/release-note-none
/ok-to-test

I guess you need to run some scripts in "hack/" to update docs. `pull-kubernetes-verify` job failure will tell you what scripts to run :)

**Comment by adnavare** [comment]
@xiangpengzhao : Looking at pull-kubernetes-verify job fails, i think this "./hack/jenkins/verify-dockerized.sh" file is returning non-zero status. But, it is showing "hack/make-rules/../../hack/verify-gofmt.sh" test failed.

**Comment by steveperry-53** [comment]
@pmorie @dchen1107 @pwittrock Can one of you help @adnavare understand why some of the Jenkins tests are failing. Thanks.

**Comment by xiangpengzhao** [comment]
@adnavare for the current `pull-kubernetes-verify` failure, this is just a gofmt error. Running `gofmt -s -w pkg/api/types.go` in your workspace can fix it.
```
I1031 03:32:03.733] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I1031 03:32:17.247] diff -u ./pkg/api/types.go.orig ./pkg/api/types.go
I1031 03:32:17.247] --- ./pkg/api/types.go.orig	2017-10-31 03:32:11.066516293 +0000
I1031 03:32:17.248] +++ ./pkg/api/types.go	2017-10-31 03:32:11.066516293 +0000
I1031 03:32:17.248] @@ -2917,7 +2917,7 @@
I1031 03:32:17.248]  	// ExternalName is the external reference that kubedns or equivalent will
I1031 03:32:17.248]  	// return as a CNAME record for this service. No proxying will be involved.
I1031 03:32:17.248]  	// Must be a valid RFC-1123 hostname (https://tools.ietf.org/html/rfc1123)
I1031 03:32:17.249] -        // and requires Type to be ExternalName.
I1031 03:32:17.249] +	// and requires Type to be ExternalName.
I1031 03:32:17.249]  	ExternalName string
I1031 03:32:17.249]  
I1031 03:32:17.250]  	// ExternalIPs are used by external load balancers, or can be set by
I1031 03:32:17.250] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	14s
```

For the `pull-kubernetes-unit` failure, I believe it's a test flake.
/test pull-kubernetes-unit

**Comment by xiangpengzhao** [comment]
You also need to modify the below file as you did in the current file. Then you may also need to run `hack/update-codegen.sh` in your workspace. (I'm not so sure which script is. You can try this one or let the `pull-kubernetes-verify` job tell you)

https://github.com/kubernetes/kubernetes/blob/bd28e6d0eaf9d519efacf9ab5925b742e0bfb10c/staging/src/k8s.io/api/core/v1/types.go#L3289-L3293

**Comment by adnavare** [comment]
Thanks @xiangpengzhao : I ran "gofmt" to fix go-lang formatting issues. Do i have to run them everytime on each file i modify to make sure it meets go-lang formatting? Is there tool to run this check just like what we do with tox on all the files in a repo?

**Comment by steveperry-53** [comment]
cc @mbohlool

**Comment by mbohlool** [comment]
The file changed in this PR is an internal type not the one exported to document generators. If you want this change to reflect in OpenAPI spec and in consequence generated documents, you need to find the right type file (probably in /v1 folder) and when you change that, run the `hack/update-openapi-spec.sh` to make sure your change is reflected in OpenAPI spec.

**Comment by xiangpengzhao** [comment]
I think this change need to reflect in OpenAPI spec and in consequence generated documents. @adnavare you can modify the file `kubernetes/staging/src/k8s.io/api/core/v1/types.go` as I mentioned in my last comment, and run the script as @mbohlool said.

**Comment by xiangpengzhao** [comment]
As for gofmt,you can run `hack/update-gofmt.sh` (it will check all files, this may cost minutes). You can also setup your IDE to gofmt automatically on save.

**Comment by adnavare** [comment]
@xiangpengzhao : Yes I will submit a new revision after modifying "kubernetes/staging/src/k8s.io/api/core/v1/types.go". I was confused exactly what is internal type doc and external type document but after chatting with @mbohlool I understood. Thanks

**Comment by xiangpengzhao** [comment]
```
I1102 21:11:20.179] FAILED TESTS
I1102 21:11:20.180] ========================
I1102 21:11:20.180] hack/make-rules/../../hack/verify-generated-protobuf.sh
I1102 21:11:20.180] hack/make-rules/../../hack/verify-staging-godeps.sh
I1102 21:11:20.180] hack/make-rules/../../hack/verify-swagger-spec.sh
```

@adnavare These verification failed. Please run below scripts to update.

```
hack/update-generated-protobuf.sh
hack/update-staging-godeps.sh
hack/update-swagger-spec.sh
```

**Comment by adnavare** [comment]
@xiangpengzhao : Thanks for pointing. Yes i am facing some downloading dep errors when running update-staging-godeps.sh. I am debugging and will submit the new PR once fixed.

**Comment by xiangpengzhao** [comment]
@adnavare please rebase and fix the conflict.

**Comment by adnavare** [comment]
I actually ran "update-swagger-spec.sh" still
seeing this  FAILED TESTS
I1111 00:03:42.473] ========================
I1111 00:03:42.473] hack/make-rules/../../hack/verify-staging-godeps.sh
I1111 00:03:42.473] hack/make-rules/../../hack/verify-swagger-spec.sh

verify-swagger-spec.sh shows success in my environment

**Comment by cblecker** [comment]
@adnavare from the log:
```
I1111 00:49:19.416] Note: This assumes that the 'types_swagger_doc_generated.go' file has been
I1111 00:49:19.416] updated for all API group versions. If you are unsure, please run
I1111 00:49:19.416] hack/update-generated-swagger-docs.sh first.
```

Please try:
```
hack/update-generated-swagger-docs.sh
hack/update-swagger-spec.sh
```
and then `git add . && git commit --amend --no-edit`

**Comment by adnavare** [comment]
I am abandoning this PR because i wrongly rebased this branch that made many commits from other folks to get included in this. New PR is here https://github.com/kubernetes/kubernetes/pull/55741

**Pull request closed without merging**
