### PR TITLE
Less demanding test cases in TestUniformDistribution

### LINKED ISSUE #98322: APF: shufflesharding unit tests time out (flake)
**Which test(s) are flaking**: //staging/src/k8s.io/apiserver/pkg/util/shufflesharding

**Testgrid link**: https://testgrid.k8s.io/sig-release-1.20-blocking#bazel-test-1.20&include-filter-by-regex=shufflesharding

While there aren't any visible failures in the above testgrid link, we've observed flaky timeouts downstream.

**Reason for failure**: Test times out

**Anything else we need to know**:

We don't have full logs for failed unit tests, so it's hard to pinpoint exactly which test is timing out, but I believe the offending function is this:

https://github.com/kubernetes/kubernetes/blob/1bb010857445fc9b8b35e9e36a9fbbbdd80694b3/staging/src/k8s.io/apiserver/pkg/util/shufflesharding/shufflesharding_test.go#L201-L211

You will see that the test iterates `hashMax` times:

https://github.com/kubernetes/kubernetes/blob/1bb010857445fc9b8b35e9e36a9fbbbdd80694b3/staging/src/k8s.io/apiserver/pkg/util/shufflesharding/shufflesharding_test.go#L227

Summing up the hashMax for all four subtests, we see that the function iterates ~34 million times. While the test takes just ~9 seconds on my machine to complete, the CI is probably struggling with it (other tests are running in parallel and iterating 34 million times over a non-trivial loop is very CPU hungry). A successful execution of the unit test on CI takes ~3-4 minutes on average. The test doesn't have any of the usual suspects that can cause a timeout (like <-chan receive, i/o reads, wait.Poll(), time.Sleep(), etc.), so I suspect the large number of iterations to be the culprit.

I propose making the unit test smaller and quicker to complete. Hopefully someone who understands shufflesharding better than me can take over :)

/sig api-machinery
/cc @MikeSpreitzer @lavalamp @liggitt

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**

/kind bug
/kind failing-test

**What this PR does / why we need it**:
This PR makes the test cases in TestUniformDistribution in `k8s.io/apiserver/pkg/util/shufflesharding` less demanding, because issue #98322 suggests that they are currently so demanding as to sometimes cause timeouts.

Also fixed a bug in the evaluation section of that test.

**Which issue(s) this PR fixes**:

Fixes #98322

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
/cc @yue9944882 
@lavalamp 
@adtac

**Comment by MikeSpreitzer** [comment]
@tkashem

**Review by yue9944882 — COMMENTED** [review]
LGTM

**Pull request merged**
