### PR TITLE
-Concurrent execution of all predicateFuncs

### PR DESCRIPTION
**Pull request by wgliang**
Signed-off-by: Wang Guoliang <iamwgliang@gmail.com>

**What this PR does / why we need it**:
Concurrent execution can improve performance

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
None
**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jayunit100** [comment]
Can we short circuit all predicates if one predicate fails - is there an issue asssociated ?

**Comment by jayunit100** [comment]
Since this is a major change just need to cc @sig-scheduling also

**Comment by wgliang** [comment]
@jayunit100 #48186  already mentioned the issues you said. 

We are also using the scheduler ourselves, when doing podFitsOnNode, we wil not continues checking when predicate failed can increase performance by nearly 40%, but will not be able to collect status of its cluster at one time(We do not think this is important). But perhaps we can not convince the community to improve on this feature. HiHi...

So I think we can perform the check concurrently.I have tested, concurrent execution predicates can also bring about 20% performance increase, this PR.

**Comment by jayunit100** [comment]
Ok. Scheduler_perf test results would be great :). Ping @ravisantoshgudlimeta

**Comment by davidopp** [comment]
> Can we short circuit all predicates if one predicate fails

If we add that, I think it should be  controlled by a scheduler config flag. I think some people will want to see all the failure reasons.

**Comment by wgliang** [comment]
@davidopp Yeah,you are right. I think we can add a switch to control it, maybe some scenes do not need to know all the causes of failure, but also can get a great performance improvement; if you need to fully understand the reasons for the failure, and accept the current performance requirements, can maintain the current logic. I think we should expose this switch to the user.

**Comment by wgliang** [comment]
I restarted the new #56926 and I will close this PR.

**Pull request closed without merging**
