### PR TITLE
Remove third_party/go-srcimporter

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:
Removes go-srcimporter as https://github.com/kubernetes/kubernetes/pull/92212 will remove the last consumption of go-srcimporter. 

/kind cleanup

cc @nikhita 

/hold 

Wait till https://github.com/kubernetes/kubernetes/pull/92212 is merged

### CODE REVIEW

**Comment by nikhita** [comment]
/ok-to-test
This isn't ready for merge and might require a rebase later, but to test if removing this breaks anything else

/release-note-none

**Comment by nikhita** [comment]
@ykakarap you'll need to run `hack/update-bazel.sh` for the tests to pass :)

**Comment by nikhita** [comment]
/hold cancel
https://github.com/kubernetes/kubernetes/pull/92212 has merged

Needs rebase though

**Comment by ykakarap** [comment]
Will work on it today.

**Comment by nikhita** [comment]
/lgtm

/assign @thockin 
for approval

**Comment by nikhita** [comment]
fyi @dims

**Pull request merged**
