### PR TITLE
[WIP] Remove SSH Tunneling functionality in API Server

### PR DESCRIPTION
**Pull request by dims**
Change-Id: Ibe317e71a2e242cc324dcffd5967932cc2b98e03

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by lavalamp** [comment]
/assign @cheftako 

When does the year expire? We were expecting this change in 1.13.

**Comment by dims** [comment]
/hold

@lavalamp was just prepping it. Not targetting this for 1.12 for sure.

**Comment by dims** [comment]
we are probably not ready for this yet ...

**Pull request closed without merging**
