### PR TITLE
Update GPC logging sidecar to use latest gem

### PR DESCRIPTION
**Pull request by satnam6502**
@a-robinson @mr-salty

### CODE REVIEW

**Comment by a-robinson** [comment]
LGTM, but not merging yet due to #8534

**Comment by a-robinson** [comment]
The freeze is over and this doesn't affect tests or builds.

**Comment by filbranden** [comment]
Not sure if you guys realized that this went into a branch called "sidecar" and not to master... Was that intended?

https://github.com/GoogleCloudPlatform/kubernetes/branches/active

**Comment by satnam6502** [comment]
Oh, no. Let's fix that.

**Pull request merged**
