### PR TITLE
test: Update nvidia-driver-installer used in gce-device-plugin-gpu job

### PR DESCRIPTION
**Pull request by bobbypage**
xref: https://github.com/kubernetes/kubernetes/issues/101558

This installer image should be compatible with COS-M85 images,
specifically `cos-85-13310-1041-9`

Image update is done in k/test-infra in https://github.com/kubernetes/test-infra/pull/22009

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig node
/sig testing

### CODE REVIEW

**Comment by bobbypage** [comment]
Tested with kubetest using the [default GCI version](https://github.com/kubernetes/kubernetes/blob/50e319767cc4aad5c6ff56a8d002c406cdcc3e0e/cluster/gce/config-default.sh#L89) (cos-85-13310-1041-9) running the [gce-device-plugin-gpu job](https://github.com/kubernetes/test-infra/blob/145342dbdd2178b2e3ba7d176e595e2b0487d179/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gpu-gce.yaml#L30-L47) as follows:

```
$ NODE_ACCELERATORS=type=nvidia-tesla-k80,count=2 KUBE_CONTAINER_RUNTIME=docker kubetest \
--dump /tmp/kubetest_out/ \
--build --up --test --provider=gce  \
--cluster=bootstrap-e2e gcp-network=bootstrap-e2e \
--gcp-project=porterdavid-gke-dev-2 \
--gcp-zone=us-central1-c \
--gcp-node-image=gci \ 
'--test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8' 2>&1 | tee -i "/tmp/kubetest_out/build-log.txt"
```

and test passed, [build log](https://gist.githubusercontent.com/bobbypage/a3f6ebb2b3cc1a4c40c34cfe63dfe2ca/raw/0ccc1a85a6b1229892481cfcfa6b17cfe629be34/build-log.txt)

**Review by ruiwen-zhao — APPROVED** [review]

**Comment by dims** [comment]
@bobbypage how does one (non-googler) discover this info next time it goes stale? Is this doc'ed somewhere public that we can refer to? i f so, please leave a comment to the link or doc.

**Comment by bobbypage** [comment]
> @bobbypage how does one (non-googler) discover this info next time it goes stale? Is this doc'ed somewhere public that we can refer to? i f so, please leave a comment to the link or doc.

It's not super well documented publicly currently but the COS GPU installer and the repro with some docs are hosted here: https://cos.googlesource.com/cos/tools/+/refs/heads/master/src/cmd/cos_gpu_installer/

The COS release notes mention which version of COS is using what version of the gpu installer and any updates.

For example, for COS-M85 release notes: https://cloud.google.com/container-optimized-os/docs/release-notes#cos-85-13310-1209-3 mentions using `v2.0.3`:

> * Updated cos-gpu-installer to v2.0.3 in cos-extensions. Fixed an issue in
      which installing GPU drivers was failing due to loading GPU kernel modules
      in incorrect order.

This is the version that I updated to in the test. I used the sha256 instead of the tag (`v2.0.3`) to be explicit, i.e. `gcr.io/cos-cloud/cos-gpu-installer@sha256:1cf2701dc2c3944a93fd06cb6c9eedfabf323425483ba3af294510621bb37d0e`

```
$ gcloud container images describe gcr.io/cos-cloud/cos-gpu-installer:v2.0.3
image_summary:
  digest: sha256:1cf2701dc2c3944a93fd06cb6c9eedfabf323425483ba3af294510621bb37d0e
  fully_qualified_digest: gcr.io/cos-cloud/cos-gpu-installer@sha256:1cf2701dc2c3944a93fd06cb6c9eedfabf323425483ba3af294510621bb37d0e
  registry: gcr.io
  repository: cos-cloud/cos-gpu-installer
```

I will update the PR with some of this info so it's less of a mystery :)

**Comment by pacoxu** [comment]
/lgtm

BTW, as https://github.com/kubernetes/test-infra/pull/21949 is merged,
we may move to cos-89 later, and is there a cos-89 image for this?

**Comment by bobbypage** [comment]
Updated PR with a comment with some details about COS GPU installer and mapping between GPU installer and COS version.

**Comment by bobbypage** [comment]
> /lgtm
> 
> BTW, as [kubernetes/test-infra#21949](https://github.com/kubernetes/test-infra/pull/21949) is merged,
> we may move to cos-89 later, and is there a cos-89 image for this?

nice, I believe this same version should work COS-m89 as well.

I tested/pinned this on COS m85 in https://github.com/kubernetes/test-infra/pull/22009 since it's currently the default GCI version used in the tests: https://github.com/kubernetes/kubernetes/blob/50e319767cc4aad5c6ff56a8d002c406cdcc3e0e/cluster/gce/config-default.sh#L89

**Comment by bobbypage** [comment]
/hold

holding since until both this PR and https://github.com/kubernetes/test-infra/pull/22009 are approved since we need both changes.

**Comment by dims** [comment]
/approve
/lgtm

please feel free to remove hold as needed

**Comment by dims** [comment]
thanks a ton for the additional info!

**Pull request merged**
