### PR TITLE
Pass context to client calls in scheduler/volumebinding tests

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109962

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/lgtm

**Comment by kerthcet** [comment]
kindly ping @Huang-Wei

**Comment by kerthcet** [comment]
PTAL @alculquicondor

**Comment by alculquicondor** [comment]
/retitle Pass context to client calls in scheduler/volumebinding tests

**Comment by alculquicondor** [comment]
/approve
/hold
please squash

**Pull request merged**
