### PR TITLE
Don't include pending pods in metrics calculations

### LINKED ISSUE #21540: HPA should skip getting metrics for pending pods
Otherwise it cannot scale down.
cc: @piosz @fgrzadkowski

### PR DESCRIPTION
**Pull request by mwielgus**
Fixes #21540

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
LGTM

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please; issue #21467

**Comment by fgrzadkowski** [comment]
This is a fix for a blocker for 1.2

**Comment by mwielgus** [comment]
Merging manually per @davidopp request.

**Pull request merged**
