### PR TITLE
MUNGE generated table of contents should strip all symbols

### LINKED ISSUE #11316: MUNGE generated table of contents won't work when there's a symbol in the headline
If the title/headline contains symbols like `'` or `?`, the generated TOC link won't work. 

For example, the generated TOC link of the headline `### It doesn't work` will be `#it-doesn't-work`
but the link should be `#it-doesnt-work`; if the headline is `### How to do this?`, the link should be `#how-to-do-this` instead of `#how-to-do-this?`

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #11316 

cc @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks! Could you do `&` also?

**Comment by JanetKuo** [comment]
I'll remove `.` `*` `(` `)` `&` `#` and `

**Comment by mikedanese** [comment]
I think "[^A-Za-z-]" works best. ()_: are not allowed and used in some bookmarks

**Comment by JanetKuo** [comment]
Thanks for the suggestion! We should allow numbers tho... so I'll use [^A-Za-z0-9-]

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by bgrant0607** [comment]
Please run this on all the docs, as was done in #11430.

**Comment by bgrant0607** [comment]
Shippable failed because gendocs didn't match.

**Comment by JanetKuo** [comment]
PTAL

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
