### PR TITLE
Update Cluster Autoscaler to 1.15.2.

### PR DESCRIPTION
**Pull request by krzysztof-jastrzebski**
Update Cluster Autoscaler to 1.15.2
 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.2

```release-note
Update Cluster Autoscaler to 1.15.2 (https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.2)
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/approve

**Comment by tpepper** [comment]
Do we have a rationale for cherry-picking this? What's 1.15.2's advantage over 1.15.0?

**Comment by losipiuk** [comment]
This is a bugfix release. See linked release notes + release notes of 1.15.1

**Comment by tpepper** [comment]
@losipiuk does this need a release note?

**Comment by losipiuk** [comment]
We typically put something like
```
Update Cluster Autoscaler to 1.15.2 (https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.2)
```
as release notes in k/k. (I would edit the PR message yet I do not have permissions to do that).

**Comment by tpepper** [comment]
> as release notes in k/k. (I would edit the PR message yet I do not have permissions to do that).

I've updated it to reflect your suggestion.

**Pull request merged**
