### PR TITLE
Automated cherry pick of #102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

### PR DESCRIPTION
**Pull request by ahg-g**
Cherry pick of #102306 #102465 on release-1.21.

#102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

Part of #102305

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ahg-g** [comment]
@kubernetes/release-managers

**Comment by puerco** [comment]
@ahg-g  I see that you are planned on cherry picking this to 1.20 & 1.21:
https://github.com/kubernetes/kubernetes/issues/102305#issuecomment-848333948

Will you send a cherry-pick for 1.19 or is it not required?

**Pull request merged**
