### PR TITLE
Check if Docker for MacOS underutilizing memory

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

By default, the Docker for MacOS virtual machine has access to 2GB of
memory, regardless of the total amount of memory available on the
machine. This low default value can cause Dockerized options to be
slower than they need to be. For example, if a Mac had 16GB of memory
(enough to parallelize builds), the Docker VM could only access 2GB,
causing builds to occur sequentially.

Add a check whenever the user uses Docker for MacOS which sees if they
are underutilizing memory, and outputs a indicator if so.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by x1957** [comment]
nice work.
This problem wasted me one day.

**Comment by spxtr** [comment]
/ok-to-test
/unassign

I have no mac :(

**Comment by mattjmcnaughton** [comment]
@jbeda just wanted to put this on your radar for whenever you get the chance :) Thanks so much!

**Comment by mattjmcnaughton** [comment]
/assign @lavalamp 

Hope its ok I'm adding you as a reviewer, in case @jbeda doesn't have the time to look at this. Thanks :)

**Comment by lavalamp** [comment]
Sorry, maybe try blame to look for a good reviewer.

**Comment by mattjmcnaughton** [comment]
/assign @zmerlynn 

If you get a second to look at this, that'd be great. Also, if there isn't interest in this, I'm happy to abandon the pr.

**Comment by mattjmcnaughton** [comment]
I'm going to go ahead and close this because it doesn't seem like there's a ton of interest - happy to reopen at a later date if it'd be helpful :)

**Pull request closed without merging**
