### PR TITLE
Remove unused federation docs

### LINKED ISSUE #56958: No need federation docs anymore
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup
/sig docs

**What happened**:
Federation docs are already in project [federation](https://github.com/kubernetes/federation).
And /hack/generate-docs.sh here do not generate federation docs right now.
So it's time to remove these docs.

**What you expected to happen**:
Remove unused docs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by danielqsj**
**What this PR does / why we need it**:

Federation docs are already in project [federation](https://github.com/kubernetes/federation).
And /hack/generate-docs.sh here do not generate federation docs right now.
So it's time to remove these docs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56958 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test

@danielqsj Can you please change the release note to "NONE"? This doesn't need a release note.

**Comment by danielqsj** [comment]
@cblecker Thanks. Done.

**Pull request merged**
