### PR TITLE
Limit the list of scheduling maintainers to active members of the sig

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @k82cn 
cc @davidopp @timothysc @aveshagarwal

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 
/hold

**Comment by bsalamat** [comment]
Since @davidopp may not check his github notifications, I let him know about this and he said he was fine with it.

**Comment by timothysc** [comment]
timeout 

/hold cancel 

godspeed sig-scheduling!

**Comment by bsalamat** [comment]
Hmm... not sure why this is not getting merged. In fact not all the tests run.
@spiffxp Do you know why?

**Comment by spiffxp** [comment]
/retest
No I'm not entirely clear why, retriggering to see if this helps

**Comment by spiffxp** [comment]
/test all
Doesn't seem like /retest had any effect

**Comment by spiffxp** [comment]
OK that kicked them off.  TIL, use /test if the things are claiming "Pending - Job triggered" but they're actually dirty liars.

**Pull request merged**
