### PR TITLE
Move all constants to a single `const (`

### LINKED ISSUE #1400: Move all constants to a single `const (`
Move all `const` on file `cmd/kubeadm/app/cmd/options/constant.go` to a single `const (`

i.e:
```diff
- // APIServerAdvertiseAddress flag sets the IP address the API Server will advertise it's listening on. Specify '0.0.0.0' to use the address of the default network interface.
- const APIServerAdvertiseAddress = "apiserver-advertise-address"

- // APIServerBindPort flag sets the port for the API Server to bind to.
- const APIServerBindPort = "apiserver-bind-port"
+ const (
+    // APIServerAdvertiseAddress flag sets the IP address the API Server will advertise it's listening on. Specify '0.0.0.0' to use the address of the default network interface.
+    APIServerAdvertiseAddress = "apiserver-advertise-address"
+
+    // APIServerBindPort flag sets the port for the API Server to bind to.
+    const APIServerBindPort = "apiserver-bind-port"
+)
```

/kind cleanup
/priority backlog
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by rumshenoy**
[#1400]

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR cleans up the constants.go file in which multiple constants were defined in different const's. 

**Which issue(s) this PR fixes**:
Fixes kubernetes/kubeadm#1400

**Special notes for your reviewer**:
Moved all constant into one single `const`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @rumshenoy, can you use 4 spaces for ident?
/ok-to-test
/lint

**Review by neolit123 — APPROVED** [review]
thanks for the PR @rumshenoy 

a couple of requests:

1)
please change this
`Fixes https://github.com/[kubernetes/kubeadm/issues/1400]`
to
`Fixes kubernetes/kubeadm#1400`

this will properly close the related issue.

2) run `./hack/update-gofmt.sh` and merge the changes into the same commit.

/approve
/hold

**Review by neolit123 — COMMENTED** [review]
the indentation looks fine now. thanks.
/lgtm

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve
/hold cancel

**Pull request merged**
