### PR TITLE
Update CHANGELOG-1.28.md for KMSv2KDF

### PR DESCRIPTION
**Pull request by enj**
Tweaked change log per https://github.com/kubernetes/kubernetes/pull/118828#issuecomment-1649433462

/kind cleanup

```release-note
NONE
```

cc @sftim

### CODE REVIEW

**Review by sanchita-07 — APPROVED** [review]
/lgtm
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by whyrass — APPROVED** [review]

**Comment by enj** [comment]
Uh is the CLA bot broken?

**Pull request merged**
