### PR TITLE
One lock among PodNominator and SchedulingQueue

### LINKED ISSUE #115762: scheduler: data race between PodInfo.Update and PriorityQueue.AddNominatedPod
### What happened?

As part of adding support for dynamic resource allocation to `test/integration/scheduler_perf`, I ran `go test -race`. With DRA, scheduling failures occur, and that led to a race report:

```
$ go test -v -timeout=0 -bench=.*/SchedulingWithInlineResourceClaims/ -race ./test/integration/scheduler_perf

WARNING: DATA RACE
Write at 0x00c000baafc0 by goroutine 25750:
  k8s.io/kubernetes/pkg/scheduler/framework.(*PodInfo).Update()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/framework/types.go:216 +0xd2e
  k8s.io/kubernetes/pkg/scheduler/internal/queue.updatePod()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go:903 +0x5a4
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).Update()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go:620 +0x582
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInSchedulingQueue()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/eventhandlers.go:140 +0x359
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInSchedulingQueue-fm()
      <autogenerated>:1 +0x6d
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:246 +0x8b
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate()
      <autogenerated>:1 +0x29
  k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:311 +0xf7
  k8s.io/client-go/tools/cache.(*FilteringResourceEventHandler).OnUpdate()
      <autogenerated>:1 +0x8d
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:973 +0x21e
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x48
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xce
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x10d
  k8s.io/apimachinery/pkg/util/wait.Until()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x78
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:969 +0x18
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +0x39
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:75 +0x73

Previous read at 0x00c000baafc0 by goroutine 25981:
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*nominator).add()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go:1024 +0xda4
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*nominator).AddNominatedPod()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go:841 +0x58
  k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).AddNominatedPod()
      <autogenerated>:1 +0x63
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).handleSchedulingFailure()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/schedule_one.go:916 +0x1a34
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).handleSchedulingFailure-fm()
      <autogenerated>:1 +0xcc
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/schedule_one.go:97 +0x962
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne-fm()
      <autogenerated>:1 +0x4d
  k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:190 +0x4c
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x48
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xce
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x10d
  k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:190 +0xaa
  k8s.io/apimachinery/pkg/util/wait.UntilWithContext()
      /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:101 +0x52
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).Run.func1()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:357 +0x5a
```

It can also be reproduced with the [current master and existing tests](https://github.com/kubernetes/kubernetes/pull/115777#issuecomment-1460501108).

### What did you expect to happen?

No race...

### How can we reproduce it (as minimally and precisely as possible)?

None of the current testcases seem to trigger it. I'll make my changes available soon in a PR.

### Anything else we need to know?

_No response_

### Kubernetes version

master

### Cloud provider

none

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The PodNominator stores the same `*QueuedPodInfo` objects as the `*SchedulingQueue`, while having each their own lock.
Given that `QueuedPodInfo` objects can be updated due to Pod changes while a scheduling cycle access the PodNominator, we should share the lock among them. This happens in the preemption path.

#### Which issue(s) this PR fixes:

Fixes #115762 

#### Special notes for your reviewer:

This needs to be cherry-picked to all supported versions.

#### Does this PR introduce a user-facing change?

```release-note
Fixed data race in `kube-scheduler` when preemption races with a Pod update.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold
/assign @Huang-Wei 


@pohly do you mind testing this patch against DRA?

**Review by Huang-Wei — COMMENTED** [review]
LGTM. Thanks Aldo.

BTW: the current perf-test still reports racing, but it's on the perf-test code itself: https://gist.github.com/Huang-Wei/cfe4986459be3d27be91c73cc70657e7

**Comment by pohly** [comment]
> BTW: the current perf-test still reports racing, but it's on the perf-test code itself: https://gist.github.com/Huang-Wei/cfe4986459be3d27be91c73cc70657e7

I think I am fixing that in https://github.com/kubernetes/kubernetes/pull/116207/commits/2440c9af776c40871cf361555e871e29ddd04e19

**Comment by pohly** [comment]
At first glance it looks like the race is gone. But I have problems running the test reliably because sometimes some of the background informer goroutines are reported as leaked,  which causes the test to fail.

**Comment by pohly** [comment]
With this fix, the test passes reliably: https://github.com/kubernetes/kubernetes/pull/116435

As far as I am concerned, this PR can be merged.

**Comment by alculquicondor** [comment]
@Huang-Wei PTAL at cherry-picks, referenced above

**Comment by rjsadow** [comment]
/release-note-edit

```release-note Fixed data race in `kube-scheduler` when preemption races with a Pod update.```

**Pull request merged**
