### PR TITLE
Removes pkg/registry/core/secret/storage from golint failures

### PR DESCRIPTION
**Pull request by guineveresaenger**
**What type of PR is this?**

> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Adds comment to REST packache in secret/storage

**Which issue(s) this PR fixes**:
Part of #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
:disappointed: 
tracking these failures.

**Comment by justinsb** [comment]
Nice - another package under linter enforcement!  Thanks @guineveresaenger 
 
/approve
/lgtm

**Comment by BenTheElder** [comment]
/approve
for hack :-)

**Comment by guineveresaenger** [comment]
@deads2k can I have a quick approve?

**Pull request merged**
