### PR TITLE
Clean up for qos.go

### LINKED ISSUE #39148: Dead code in qos.go?
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
VM running on OpenStack KVM with 8GB RAM.
- **OS** (e.g. from /etc/os-release):
Centos7.0
- **Kernel** (e.g. `uname -a`):
3.10.0-229.el7.x86_64
- **Install tools**:

- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
Seems we are not using any of those functions. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #39148

**Release note**:

```release-note
A small clean up to remove unnecessary functions.
```

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@k8s-bot test this please!

**Comment by jayunit100** [comment]
If this is needed, it needs a unit test.
If its not needed, makes sense to delete.

**Comment by sjpotter** [comment]
seems faily straight forward, as it just removed functions.  If it passes e2e tests seems fine.

**Comment by jayunit100** [comment]
@k8s-bot test this please.

**Comment by jayunit100** [comment]
@k8s-bot ok to test.

**Comment by feiskyer** [comment]
Looks reasonable. Waiting for CI green.

@k8s-bot ok to test

**Comment by jayunit100** [comment]
I'm seeing unit test failures here........?  @ravisantoshgudimetla if you see these to i guess this code is needed after all :).
```
--- FAIL: TestRefetchSchemaWhenValidationFails (0.09s)
        factory_test.go:311: expected 1 schema request, saw: 0
--- FAIL: TestValidateCachesSchema (0.07s)
        factory_test.go:360: expected 1 schema request, saw: 0
        factory_test.go:368: expected 1 schema request, saw: 0
        factory_test.go:379: expected 1 schema request, saw: 0
        factory_test.go:390: expected 1 schema request, saw: 0
FAIL
FAIL    k8s.io/kubernetes/pkg/kubectl/cmd/util  1.44
```

**Comment by ravisantoshgudimetla** [comment]
So, I am kind of confused here for 2 reasons.

- Why is another file's unit-test making a call to the function in another package altogether.
- I just looked at those files and it seems they are making a APIServer call(a fake one) and no where related to code changes that I made.

I may be wrong in any of those assumptions and the tests could be simply flakes. Can we run the unit tests only again to see, if there are some failures? 

In fact, the same test failed for my other PR as well:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45018/pull-kubernetes-unit/28128/

**Comment by jayunit100** [comment]
@k8s-bot test this

**Comment by jayunit100** [comment]
@k8s-bot unit test this

**Comment by ravisantoshgudimetla** [comment]
This is flake again.

**Comment by jayunit100** [comment]
@k8s-bot unit test this

**Comment by jayunit100** [comment]
I assume woj might know why the predicate has an `error` return that isn't ever used.

**Comment by yujuhong** [comment]
@vishh @derekwaynecarr, is it ok to remove the functions or are they going to be used in the near future?

**Comment by jayunit100** [comment]
iirc general policy is that we don't have dead code in the codebase.  obviously its ok to defer to vish and derek here but, IMO we should remove deadcode as a policy unless there is an obvious note in the source not to `TODO: we will use this in the near future for XYZ`.

**Comment by ravisantoshgudimetla** [comment]
ping @vishh @derekwaynecarr

**Comment by ravisantoshgudimetla** [comment]
Seems to be an infra error. I cannot ask the bot to test it again. Can someone do it?

**Comment by vishh** [comment]
@k8s-bot ok to test

**Pull request merged**
