### PR TITLE
AWS: recognize us-east-2 region

### PR DESCRIPTION
**Pull request by justinsb**
The newly announced region must be added to our list of known regions.

```release-note
AWS: recognize us-east-2 region
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35013)

### CODE REVIEW

**Comment by justinsb** [comment]
This is needed to run in us-east-2, otherwise we get

```
Oct 18 03:39:04 ip-172-20-58-230 kubelet[2850]: error: failed to run Kubelet: could not init cloud provider "aws": not a valid AWS zone (unknown region): us-east-2a
```

We could maybe skip this check when we get the region from the AWS metadata itself, but that's a separate issue...

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this

**Comment by chrislovecnm** [comment]
@k8s-bot gci gke e2e test this

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this

**Comment by chrislovecnm** [comment]
Did it pass? OMG

**Review by errordeveloper — APPROVED** [review]
LGTM

**Comment by justinsb** [comment]
@erictune I marked this P1 because without it k8s won't run in the new us-east-2 region.  Will follow up with a cherry-pick to 1.4

**Comment by paultyng** [comment]
Will there be a cherry pick to 1.3?

**Comment by chrislovecnm** [comment]
@paultyng with the SSL bug, everyone needs to upgrade that, but yes we should have it

**Comment by chrislovecnm** [comment]
TLS cert issue that is in 1.3

**Comment by justinsb** [comment]
ping @erictune

**Comment by paultyng** [comment]
Any ability to escalate this? Its very minor, and actively holding up using 1.3 on the AWS region.  1.4 at least has the work around to ignore region validation.

**Comment by chrislovecnm** [comment]
@justinsb can u tag this with a P0. @erictune paging @erictune 

@paultyng this is assigned to a lead, and I asked to have this bumped to a P0

**Comment by erictune** [comment]
lgtm

**Comment by chrislovecnm** [comment]
@erictune can we get this back ported into 1.4?

**Comment by paultyng** [comment]
@justinsb I think that label needs to be reapplied with the milestone?

This is still an issue for me.  There is the config to override region checking, but it doesn't seem to apply for dynamic volume provisioning, so any chart using dynamic volumes on 1.4 will not work in us-east-2.

That's what I've found so far at least.

**Comment by chrislovecnm** [comment]
@paultyng which version of K8s?

**Comment by justinsb** [comment]
@paultyng can you open an issue with what you're seeing?  AFAIK this is the only place we list zones.

**Comment by jessfraz** [comment]
cherry-picked in https://github.com/kubernetes/kubernetes/pull/37140

**Comment by justinsb** [comment]
Thanks @jessfraz - I guess I finally figured out the magic cherry-pick labels!

**Comment by paultyng** [comment]
@justinsb I'll try to repro tomorrow at work.  This was in 1.4.6, and I believe its going through this code as well, but for some reason not respecting the config value when this code is hit via the dynamic volume provisioning.  But I'll try to get some extra info for you.  Thanks for the cherry pick.

**Pull request merged**
