### PR TITLE
Upgrade the release version info in CHANGELOG.md

### PR DESCRIPTION
**Pull request by warmchang**
**What this PR does / why we need it**:
Upgrade the release version info in CHANGELOG.md

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/release-note-none
/kind cleanup

### CODE REVIEW

**Comment by neolit123** [comment]
thanks

/ok-to-test
/lgtm

**Comment by nikhita** [comment]
/assign @thockin 
for approval

**Pull request merged**
