### PR TITLE
Add UT for ipvs proxy netlink

### LINKED ISSUE #54126: Should add UTs for ipvs proxy netlink stuff
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Add UT for ipvs proxy netlink

**Which issue this PR fixes**: 

fixes #54126

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by freehan** [comment]
Test looks good. Please fix the failures.

**Comment by m1093782566** [comment]
@freehan 

From the test result:

```
--- FAIL: TestAddressBindAndUnbind (0.00s)
	netlink_linux_test.go:36: Unexpected error when try to create dummy device, error: error creating dummy interface "test-dummy": executable file not found in $PATH: 
	netlink_linux_test.go:47: Unexpected error when try to bind IP address: 1.2.3.4 to dummy device, error: error get interface: test-dummy, err: Link not found
	netlink_linux_test.go:47: Unexpected error when try to bind IP address: 2001:db8::1:1 to dummy device, error: error get interface: test-dummy, err: Link not found
	netlink_linux_test.go:57: Unexpected error when try to bind an existing IP address: 1.2.3.4 to dummy device, error: error get interface: test-dummy, err: Link not found
	netlink_linux_test.go:60: Unexpected IP address: 1.2.3.4 is not bound to dummy device: test-dummy
	netlink_linux_test.go:57: Unexpected error when try to bind an existing IP address: 2001:db8::1:1 to dummy device, error: error get interface: test-dummy, err: Link not found
	netlink_linux_test.go:60: Unexpected IP address: 2001:db8::1:1 is not bound to dummy device: test-dummy
	netlink_linux_test.go:67: Unexpected error when try to unbind IP address: 1.2.3.4 from dummy device, error: error get interface: test-dummy, err: Link not found
	netlink_linux_test.go:67: Unexpected error when try to unbind IP address: 2001:db8::1:1 from dummy device, error: error get interface: test-dummy, err: Link not found
FAIL
```

Seems unable to use the `ip` command - failed to acquire the `root` privilege. Any comments?

**Comment by cmluciano** [comment]
Any reason to close this @m1093782566 ?

**Comment by m1093782566** [comment]
@cmluciano 

That's because the test requires root privilege. It seems that UT can't obtain the root privilege.

**Pull request closed without merging**
