### PR TITLE
Link to static API reference instead of swagger UI (which doesn't work).

### PR DESCRIPTION
**Pull request by bgrant0607**
cc @lavalamp

### CODE REVIEW

**Comment by bgrant0607** [comment]
Actually, let me fix the link on the gettingstarted page, also

**Comment by bgrant0607** [comment]
Updated

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
cc @RichieEscarez

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
