### PR TITLE
Move core API to pkg/apis/core

### LINKED ISSUE #55304: Move core api types from pkg/api to pkg/apis/core
Follow-up of https://github.com/kubernetes/kubernetes/issues/44065

Internal API types live in pkg/apis/<group>, with the exception of the core group which traditionally lives in pkg/api. In contrast, with the [move of the external types to k8s.io/api](https://github.com/kubernetes/features/issues/282), the external core types were aligned with the other groups, forming a k8s.io/api/core package. The internal core types though were kept in our unicorn pkg/api package.

### Motivation

The package pkg/api served long as a catch-all package for everything around the api. There is no clear distinction between the core types and the kube-apiserver plumbing around or the helpers only used by controllers. To continue our code layering efforts, moving the core types to pkg/apis/core removes a big part of pkg/api out and makes further refactoring of pkg/api much easier and much more obvious.

Mid-term, one of the goals of the code layering efforts is to cut out the kube-apiserver with all its dependencies. This PR is one step into that direction, turning pkg/apis into a self-contained entity in the code-base, distinct from plumbing them into an apiserver or using them in controllers. Clear dependencies will allow us to split apart the code base on api group boundaries much easier.

### PR DESCRIPTION
**Pull request by sttts**
Fixes https://github.com/kubernetes/kubernetes/issues/55304.

This moves the types in pkg/api and most of pkg/api/v1 to pkg/apis/core to match the other api groups, following-up on what https://github.com/kubernetes/kubernetes/pull/44784 did for the external types.

It's a nearly 100% mechanical package move with a number of trivial fixups in code-generators and in tests which do string comparisons of types via reflection.

**Most importantly:**

- group names are unchanged
- apimachinery semantics are unchanged
- the outside api is unchanged.

Note that some packages for helpers are left in pkg/api/v1. Splitting them into helpers which belong tightly to the api and those which are not is left to follow-ups.

@kubernetes/sig-api-machinery-pr-reviews

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts  This one fell through the cracks.  Are you still actively pursuing it?

**Comment by sttts** [comment]
@deads2k yes, trying to get it green when blocked on other stuff.

**Comment by sttts** [comment]
@deads2k rebased again. ptal. Would like to get this in sooner than later. Every rebase takes quite some time.

**Comment by sttts** [comment]
@smarterclayton is this approved?

**Comment by deads2k** [comment]
@kubernetes/sig-api-machinery-pr-reviews this moves the internal types to mirror their external counterparts here: https://github.com/kubernetes/api/tree/master/core/v1

**Comment by smarterclayton** [comment]
Update the description to point back to the design doc / work items that led to this.  Also can you prep an email to the mailing list so people know this is coming?

Just verifying - group name is preserved?

**Comment by sttts** [comment]
> Update the description to point back to the design doc / work items that led to this. Also can you prep an email to the mailing list so people know this is coming?

Will do.

> Just verifying - group name is preserved?

Nothing changes to the outside or to the apimachinery mechanics. It's a package move only.

**Pull request merged**
