### PR TITLE
Revert "Remove [Slow] from statefulset basic tests"

### PR DESCRIPTION
**Pull request by janetkuo**
Ref #37184, to unblock the submit queue 
This reverts commit 0744033d8c2a3bf3d46dbdefd5ae665bf10eca69.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37387)

### CODE REVIEW

**Comment by dims** [comment]
+1 @janetkuo Let's try this. LGTM

**Comment by dims** [comment]
@k8s-oncall Can you please merge this manually? Need to unblock submit queue (stuck for 10 hours now)

**Comment by piosz** [comment]
Merged manually to unblock submit queue.

**Comment by dchen1107** [comment]
@piosz and @janetkuo Thanks for reverting the pr. I am just about do it. This should fix ci-kubernetes-e2e-gci-gke  breakage.

**Comment by saad-ali** [comment]
As @foxish mentioned, this just "shifts" the test suite. The real issue is that StatefulSets is not enabled for GKE: https://github.com/kubernetes/kubernetes/pull/37389

**Comment by foxish** [comment]
We should un-revert this change after the fix is verified.

**Comment by janetkuo** [comment]
> We should un-revert this change after the fix is verified.

Yes I'll do that

**Comment by janetkuo** [comment]
Filed #37412 so we don't forget to revert this

**Pull request merged**
