### PR TITLE
WIP: Fork go std lib json for improved memory usage

### PR DESCRIPTION
**Pull request by lavalamp**
This is a fork of https://go.dev/cl/455776 to see what it does to k8s memory usage. Since it will take at least ~7? more months for that to appear in a go release.

/kind feature
/sig api-machinery

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
> This is a fork of https://go-review.git.corp.google.com/c/go/+/455776/10 to see what it does to k8s memory usage. Since it will take at least ~7? more months for that to appear in a go release.

@lavalamp that is an internal link 🙃

**Comment by lavalamp** [comment]
😰 Does https://golang.org/cl/455776 work?

**Comment by lavalamp** [comment]
I looked at the .pprof files -- there's apparently still callers of the go std lib json encode, this doesn't hit everything. And I think our e2e tests may not exercise the case this optimizes very well.

**Comment by dims** [comment]
cc @MadhavJivrajani

**Pull request closed without merging**
