### PR TITLE
Cleaner aggregate errors API

### PR DESCRIPTION
**Pull request by thockin**
@smarterclayton could you be talked into splitting the filter and flatten logic into two calls?  This feels like a more generic API.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Sure, I only did it as one because of the complexity of flatten already (filter reduced the space).

**Comment by smarterclayton** [comment]
I like this.

**Comment by thockin** [comment]
Does that count as LGTM?

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Thanks, rebased and everything is golden.

----- Original Message -----

**Pull request merged**
