### PR TITLE
Automated cherry pick of #114863: Use label selector for filtering out resources when pruning.
#115571: Add integration test for diff --prune --selector

### PR DESCRIPTION
**Pull request by nathanmartins**
Cherry pick of #114863 #115571 on release-1.24.

#114863: Use label selector for filtering out resources when pruning.
#115571: Add integration test for diff --prune --selector

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Make kubectl diff --prune behave correctly with the --selector/-l flag
```

### CODE REVIEW

**Comment by KnVerey** [comment]
/ok-to-test
/triage accepted
/approve
/cc kubernetes/release-managers

/release-note-edit

```release-note
Make kubectl diff --prune behave correctly with the --selector/-l flag
```

**Comment by Verolop** [comment]
@KnVerey @nathanmartins can we get a a LGTM from any of the original reviewers? thank you!

**Comment by nathanmartins** [comment]
@ardaguclu @danlenar can you guys approve this, please?

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
