### PR TITLE
correct the ConstructVolumeSpec func path value

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
the path value is incorrect
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign @jsafrane
thanks

**Comment by msau42** [comment]
/lgtm

It looks like all cephfs teardown does is unmount the kubelet pod volume directory.

**Comment by jianglingxia** [comment]
thanks@msau42
for approve @jsafrane

**Pull request merged**
