### PR TITLE
fix typo annotation key notes.

### PR DESCRIPTION
**Pull request by yanggangtony**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix typo notes.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by r0b2g1t — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
/sig api-machinery
/assign @liggitt 

(typos in comments that are under api review)

**Comment by yanggangtony** [comment]
> /sig api-machinery /assign @liggitt
> 
> (typos in comments that are under api review)

Thanks for review.

**Pull request merged**
