### PR TITLE
fix wrong error return

### PR DESCRIPTION
**Pull request by Crazykev**
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

**What this PR does / why we need it**: The err return here is wrong, correct it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by Crazykev** [comment]
@madhusudancs Do you mind add a test label to this?

**Comment by Crazykev** [comment]
ping @resouer

**Comment by resouer** [comment]
@k8s-bot ok to test

**Pull request merged**
