### PR TITLE
[WIP] Server-Side Apply: Implement managedFields wiping

### LINKED ISSUE #75564: server-side apply takes ownership of fields that don't get set due to status wiping
The API server wipes status changes on calls to the normal endpoints (not /status) at the storage registry layer (right next to etcd).  This means that calls to `<resource>/<name>` can't change status.  However, if you send a server-side apply patch, the server-side apply logic still takes ownership of any fields you *try* to set, despite the fact that they don't get set.

Reproduced on HEAD (8af1bf313efeeafb94c01ce04965ad8fe9cea21a).

Reproducer: 
- Send a server-side apply patch setting any field in status to `/api/v1/namespaces/<ns>/pods/<name>`
- Observe that ownership of that field has been taken
- Observe that the field isn't set

cc #73723 
cc @jennybuckley @apelisse

### PR DESCRIPTION
**Pull request by kwiesmueller**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The changes in this PR will wire storage strategies into the FieldManager.
On Update and Apply requests, the incoming object will then be converted and run through the PrepareForCreate/Update methods to extract which fields will be reset at storage.
Those fields will then be removed from the managedFields using the changes in this PR https://github.com/kubernetes-sigs/structured-merge-diff/pull/178/commits

This is another (and hopefully the last :pray:) take on https://github.com/kubernetes/kubernetes/pull/92809

Implements https://github.com/kubernetes/enhancements/pull/1123

**Which issue(s) this PR fixes**:

Fixes #75564

**Does this PR introduce a user-facing change?**:

```release-note
FieldManager no longer owns fields that get reset before the object is persisted (e.g. "status wiping").
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/pull/1123
```

/sig api-machinery
/wg api-expression
/assign @apelisse

### CODE REVIEW

**Comment by kwiesmueller** [comment]
Note that right now this PR still has the structured-merge-diff dependency pinned on my fork.
Once https://github.com/kubernetes-sigs/structured-merge-diff/pull/178/commits merges I'll bump the dependency in a separate PR and then rebase this PR to make it easier for review.
Also adding a todo for this, to track it:

- [ ] Bump smd in a separate PR and rebase

**Comment by kwiesmueller** [comment]
Also several strategies can not be accessed right now, as they do not implement the GenericStore interface.
We need to make them expose their strategies or get another way to access them.
The resources currently not implementing the interface are tracked [here](https://docs.google.com/spreadsheets/d/14ObbdXN9yDOOEgNI5m4qAXTm5M-Wd9cJiCUkMHNjEHE/edit?usp=sharing) and are currently printed in the log.

- [ ] Implement the GenericStore interface for all (sub)-resources

- [ ]

**Comment by apelisse** [comment]
/close
We fixed that!

**Pull request closed without merging**
