### PR TITLE
vendor: bump cAdvisor to v0.39.3

### LINKED ISSUE #107284: request: backport cadvisor v0.40.0 to older branches
### What happened?

I'm running k3s with kube `1.21.x` and I am currently impacted by google/cadvisor/pull/2868 which was fixed in cadvisor `v0.40.0`. All maintained branches are currently running cadvisor `v0.39.0` except `1.23.x` which is under the latest cadvisor.

### What did you expect to happen?

Bump all supported branches of Kubernetes to cadvisor > `0.40.0`.

### How can we reproduce it (as minimally and precisely as possible)?

* Deploy the [Concourse Helm chart](https://github.com/concourse/concourse-chart)
* Deploy a test pipeline using the [concourse tutorial](https://concoursetutorial.com/)
* Introspect the metric endpoint `kubectl get --raw /api/v1/nodes/${NODE}/proxy/metrics/cadvisor`
* Container metrics will disappear after few minutes and `container_scrape_error` will start emit `1`.

Concourse workers run a lots of short lived containers using containerd. They causes cadvisor to cache miss when pulling latest container metrics and hence, completely interrupt the metric gathering.

The kubelet logs will start tracing this logs when the problem occurs:
```
W0101 23:17:43.322433    3000 prometheus.go:1856] Couldn't get containers: partial failures:
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="k3OS"
VERSION="k3OS v0.21.5-k3s2r1"
ID=k3os
ID_LIKE=alpine
PRETTY_NAME="k3OS v0.21.5-k3s2r1"
VERSION_ID="v0.21.5-k3s2r1"
HOME_URL="https://k3os.io/"
SUPPORT_URL="https://k3os.io/"
BUG_REPORT_URL="https://github.com/rancher/k3os/issues"
ISO_URL="https://github.com/rancher/k3os/releases/download/v0.21.5-k3s2r1/k3os-amd64.iso"

$ uname -a
Linux k3os-22970 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bobbypage**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bump cAdvisor to v0.39.3 to pick up google/cadvisor#3038 to fix #107284

Also pick up fixes made from v0.39.0 -> v0.39.3 (mostly cgroupv2 bug fixes) -- https://github.com/google/cadvisor/compare/v0.39.0...v0.39.3

#### Which issue(s) this PR fixes:

Fixes #107284

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
@liggitt can you review this one as well as you did for https://github.com/kubernetes/kubernetes/pull/107355

**Comment by liggitt** [comment]
/approve
for dep update

**Comment by puerco** [comment]
Thank you @bobbypage !
/lgtm

**Pull request merged**
