### PR TITLE
fix pkg/volume/util static checks

### PR DESCRIPTION
**Pull request by lala123912**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fixes pkg/volume/util static checks 

**Which issue(s) this PR fixes**:
Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by lala123912** [comment]
I signed it

**Comment by lala123912** [comment]
I signed it

**Comment by oomichi** [comment]
[hack/.staticcheck_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures) is the list of what we need to fix but the list doesn't contain this `pkg/volume/util`.

/cc @oomichi

**Comment by lala123912** [comment]
> [hack/.staticcheck_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures) is the list of what we need to fix but the list doesn't contain this `pkg/volume/util`.
> 
> /cc @oomichi

**Comment by lala123912** [comment]
> [hack/.staticcheck_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures) is the list of what we need to fix but the list doesn't contain this `pkg/volume/util`.
> 
> /cc @oomichi

I got some problems with running the cmd of "make verify WHAT=staticcheck", so installing stackcheck local and use "static ./..." to scan the code instead. The version of stackcheck I used is  v0.0.1-2020.1.5.

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
