### PR TITLE
Fix for host path test case

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
- if err!=nil,plug may be nil, so need finish test case
- replace string with const variable

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/priority backlog

### CODE REVIEW

**Comment by jsafrane** [comment]
The code looks OK, however, can you please change the commit message to something like

> Fixed potential nil dereference in hostpath unit test
>
> And fixed an error message when at it.

Btw, using two commits would be perfectly OK here.

**Comment by yuzhiquan** [comment]
Respond.

**Comment by yuzhiquan** [comment]
@jsafrane should this pr add milestone tag, or wait for code freeze finished?

**Comment by jsafrane** [comment]
I think we can wait for 1.20. It should be open soon.

**Comment by yuzhiquan** [comment]
> I think we can wait for 1.20. It should be open soon.

Why still stuck in `Must be in milestone v1.19.` after 1.19 released? or just lack milestone label?

**Comment by yuzhiquan** [comment]
@justaugustus Hi,Stephen, can you  addres 1.20 label for this pr?

**Comment by justaugustus** [comment]
Sure thing!
/milestone v1.20
/test pull-kubernetes-e2e-kind-ipv6

**Comment by yuzhiquan** [comment]
> Sure thing!
> /milestone v1.20
> /test pull-kubernetes-e2e-kind-ipv6

Thanks for so quickly reply!

**Pull request merged**
