### PR TITLE
Set some kube-proxy parameters for local-up-cluster.sh

### PR DESCRIPTION
**Pull request by dims**
Suggestions from @aojea to avoid some issues in local-up-cluster.sh.

kube-proxy tries to set some sysctl options which fail in some circumstances (say when running local-up-cluster.sh in a docker container on macos, we should avoid having to set some of these options):
https://cs.k8s.io/?q=nf_conntrack_max%7Cnf_conntrack_tcp_timeout_established%7Cnf_conntrack_tcp_timeout_close&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

Note that we are borrowing this from a PR in kind:
https://github.com/kubernetes-sigs/kind/pull/1935/files#diff-1e5fea907b390b2fe568c10ed0b138b9fa155a79b4b0b140bbd1daf6562da6c3R392-R399

/kind bug

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
the credit goes for @AkihiroSuda https://github.com/kubernetes-sigs/kind/pull/1935/files#diff-1e5fea907b390b2fe568c10ed0b138b9fa155a79b4b0b140bbd1daf6562da6c3R392-R399 
:)

**Comment by dims** [comment]
どうもありがとう @AkihiroSuda - san!

**Comment by liggitt** [comment]
> Suggestions from @aojea to avoid some issues in local-up-cluster.sh

details about the issues we're avoiding would be helpful to include in comments in the config

**Comment by dims** [comment]
the 2 failures are being fixed in:
- https://github.com/kubernetes/kubernetes/pull/100550
- https://github.com/kubernetes/kubernetes/pull/100569

**Comment by dims** [comment]
@kubernetes/release-managers @kubernetes/release-team-leads this is a fix for broken test, please consider merging this early

**Pull request merged**
