### PR TITLE
remove note E2eScheduling

### PR DESCRIPTION
**Pull request by lixiaobing1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
E2eScheduling has been removed, so remove the note.

**Which issue(s) this PR fixes**:
No

**Special notes for your reviewer**:
No

**Does this PR introduce a user-facing change?**:
No

```release-note
   NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
No

### CODE REVIEW

**Comment by oomichi** [comment]
@lixiaobing1 Can you remove `remove note E2eScheduling` from the PR message to avoid putting it on the release note?

/kind cleanup
/cc @oomichi

**Comment by lixiaobing1** [comment]
> @lixiaobing1 Can you remove `remove note E2eScheduling` from the PR message to avoid putting it on the release note?
> 
> /kind cleanup
> /cc @oomichi

@oomichi ok, release note has been removed :)

**Comment by oomichi** [comment]
Thanks for updating.

/lgtm

**Pull request closed without merging**
