### PR TITLE
 fix translations location in update-translations.sh

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind cleanup
/sig cli

#### What this PR does / why we need it:

- fixes translations location in update-translations.sh for a new option -k introduced in https://github.com/kubernetes/kubernetes/pull/102072
- also update translations

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
@soltysh 
I am sorry I made a mistake during rebasing of https://github.com/kubernetes/kubernetes/pull/102072

**Comment by soltysh** [comment]
/ok-to-test
/priority backlog
/triage accepted
/milestone v1.22
@atiratree can you rebase this on top of https://github.com/kubernetes/kubernetes/pull/103524 when that merges?

**Comment by atiratree** [comment]
@soltysh rebased and updated the translations. 

One thing to consider is that with each small change, a lot of translations are commented out. For example adding/removing a `.` from a sentence (https://github.com/kubernetes/kubernetes/pull/103524). 

Not 100% sure, but it might save time to fix these non language specific changes (for most languages) at the same time in the translations as well. 

Currently there is quite a lot of commented out translations. Is there somebody who is maintaining them?

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/milestone v1.22

**Pull request merged**
