### PR TITLE
Support upgrade/downgrade in etcd image.

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #22448 #20504

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34009)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@lavalamp - these are changes necessary to support upgrade/downgrade in etcd image. However, this is not yet tested at all, thus not yet ready for review. But hopefully should be ready tomorrow (but I need https://github.com/kubernetes/kubernetes/pull/34004 to be approved first).

**Comment by wojtek-t** [comment]
@mml - FYI

**Comment by wojtek-t** [comment]
The errors I'm getting are strange (I'm not getting them locally). I'm trying to debug them.

**Comment by wojtek-t** [comment]
OK - I figured it out. This is now ready for review.

**Comment by mml** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 31 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRP1f1PO0ByANuH27l:-KTRP1f2ebSZMpjyWpdH:b-2osy5g) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L31)):*
> ```Shell
> # - 2.2.1/etcd2 -> 2.3.7/etcd2
> # - 2.3.7/etcd2 -> 3.0.10/etcd2
> # - 3.0.10/etcd2 -> 3.0.10/etcd3
> ```

Add note here and in the Makefile that the versions in the image and the versions in this script must be kept in sync.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 39 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRP9uarmCsACJnGgYj:-KTRP9uarmCsACJnGgYk:bf0sgp8) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L39)):*
> ```Shell
> 
> if [ -z "${TARGET_STORAGE:-}" ]; then
>   echo "TARGET_USAGE variable unset - skipping migration"
> ```

s/USAGE/STORAGE

---

*[cluster/images/etcd/migrate-if-needed.sh, line 62 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRPPr1TnML46kJfVIe:-KTRPPr1TnML46kJfVIf:bfj1whl) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L62)):*
> ```Shell
> CURRENT_VERSION="2.2.1"
> if [ -e "${DATA_DIRECTORY}/${VERSION_FILE}" ]; then
>   VERSION_CONTENTS="$(cat ${DATA_DIRECTORY}/${VERSION_FILE})"
> ```

Add a comment showing sample output so that the reader understands the 'cut' invocations below.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 100 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRUUwSNC2bjONmJ7qx:-KTRUUwSNC2bjONmJ7qy:bgwn1fb) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L100)):*
> ```Shell
>   done
>   echo "Timeout while waiting for etcd on port ${ETCD_PORT}"
>   return 1
> ```

We don't actually check the return code of start_etcd and do anything with it.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRUec7YzYGG8hRplTo:-KTRUec8pvNNQXgvdix9:bs148y4) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L167)):*
> ```Shell
>     if [ "$(ls -A ${DATA_DIRECTORY})" ]; then
>       echo "Performing etcd3 -> etcd2 rollback"
>       ${ROLLBACK} --data-dir "${DATA_DIRECTORY}"
> ```

Is there any error checking we can do here?  Does the tool exit nonzero if there are problems?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009)*

**Comment by wojtek-t** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 31 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRP1f1PO0ByANuH27l:-KTTMaLXWg9UZFJn5Nln:bb6un1j) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L31)):*
<details><summary><i>Previously, mml (Matt Liggett) wrote…</i></summary>
> Add note here and in the Makefile that the versions in the image and the versions in this script must be kept in sync.
</details>
Done

---

*[cluster/images/etcd/migrate-if-needed.sh, line 39 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRP9uarmCsACJnGgYj:-KTTMdv0BZ5ASQ2DxUa4:bb7f2mf) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L39)):*
<details><summary><i>Previously, mml (Matt Liggett) wrote…</i></summary>
> s/USAGE/STORAGE
</details>
done

---

*[cluster/images/etcd/migrate-if-needed.sh, line 62 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRPPr1TnML46kJfVIe:-KTTN5MYgYR_c693vWTP:bb7f2mf) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L62)):*
<details><summary><i>Previously, mml (Matt Liggett) wrote…</i></summary>
> Add a comment showing sample output so that the reader understands the 'cut' invocations below.
</details>
done

---

*[cluster/images/etcd/migrate-if-needed.sh, line 100 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRUUwSNC2bjONmJ7qx:-KTTQCIUTN14Bl1GZaEv:bt2vr1b) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L100)):*
<details><summary><i>Previously, mml (Matt Liggett) wrote…</i></summary>
> We don't actually check the return code of start_etcd and do anything with it.
</details>
Fixed.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRUec7YzYGG8hRplTo:-KTTMjdq-QGvxURSFqhE:ba0v9qp) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L167)):*
<details><summary><i>Previously, mml (Matt Liggett) wrote…</i></summary>
> Is there any error checking we can do here?  Does the tool exit nonzero if there are problems?
</details>
Yes - if rollback fails, it will return with non-0 exit code.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009)*

**Comment by wojtek-t** [comment]
Commends applied. @mml - PTAL

**Comment by mml** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cluster/images/etcd/migrate-if-needed.sh, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-KTRUec7YzYGG8hRplTo:-KTWH_TnWPsXf2FH6HGn:bp0h8qo) ([raw file](https://github.com/kubernetes/kubernetes/blob/f769d38a8701ac4b948064ec88555b1240aa4a39/cluster/images/etcd/migrate-if-needed.sh#L167)):*
<details><summary><i>Previously, wojtek-t (Wojciech Tyczynski) wrote…</i></summary>
> Yes - if rollback fails, it will return with non-0 exit code.
</details>
OK.  We should check the exit code and print an error if it's not 0.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009)*

**Comment by mml** [comment]
LGTM once you address the error checking after we run ${ROLLBACK}.  Feel free to apply label yourself.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34009#-:-KTWHlr62xWrPlAYimVi:bop05ff)*

**Comment by wojtek-t** [comment]
@mml - thanks!

I added checking for exit code from rollback. Adding lgtm label based on the above comment.

**Pull request merged**
