### PR TITLE
fix spelling errors its

### PR DESCRIPTION
**Pull request by mysunshine92**
**What this PR does / why we need it**:
fix spelling errors its

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
we are in code slush now and only things specifically targeted at the milestone merge. this can wait until master reopens.

**Comment by mysunshine92** [comment]
@liggitt  would you like to add a approved label? thank you

**Comment by mysunshine92** [comment]
@liggitt  can you help to add a approved label,  thank you.

**Pull request merged**
