### PR TITLE
Add unit tests for cluster, context, and user command line completion functions

### PR DESCRIPTION
**Pull request by brianpursley**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Add unit tests for cluster, context, and user completions.

#### Which issue(s) this PR fixes:
n/a

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by marckhouzam** [comment]
This looks like #107142 but with tests.  We definitely want to the tests as well.

**Comment by brianpursley** [comment]
> This looks like #107142 but with tests. We definitely want the tests as well.

Oh wow, I didn't see that PR.  Thanks, @marckhouzam .  It wasn't my intention to take over someone else's work.  :thinking: 

Maybe the right thing to do would be accept the first PR, and then this one can be to add the tests...

**Comment by brianpursley** [comment]
I went ahead and lgtm'd and approved #107142.  Since the code was almost identical to what I had.  I'll convert this PR into unit tests only

/hold

**Comment by brianpursley** [comment]
OK, this PR is ready for review now...

Removed the code change (since it was duplicated with another PR), but left the unit tests.

/unhold

**Review by marckhouzam — APPROVED** [review]
This is nice!  I hadn't figured out how to write these tests.

**Review by eddiezane — APPROVED** [review]
/lgtm

**Pull request merged**
