### PR TITLE
Automated cherry pick of #103865: Add e2e testing manifest bundle to e2e_node test suite

### PR DESCRIPTION
**Pull request by palnabarun**
Cherry pick of #103865 on release-1.22.

#103865: Add e2e testing manifest bundle to e2e_node test suite

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm
/kind cleanup
/release-note-none

**Pull request merged**
