### PR TITLE
Incomplete coverage of test scenarios

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The test scenarios are incomplete.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i think we can go without these additional test cases because if the kubelet changes its version output format our e2e tests will probably break right away.

but no harm adding them.

/lgtm
/approve

**Comment by Octopusjust** [comment]
> i think we can go without these additional test cases because if the kubelet changes its version output format our e2e tests will probably break right away.
> 
> but no harm adding them.
> 
> /lgtm /approve

Got it , thanks.

**Pull request merged**
