### PR TITLE
Move serve_hostname testing image to k8s test/images from contrib/for…

### PR DESCRIPTION
**Pull request by pwittrock**
…-demos

### CODE REVIEW

**Comment by pwittrock** [comment]
@bprashanth is there any process for pushing the new image besides:

- `make container`
- run the container locally + test the result sending an http request
- `make push`

**Comment by bprashanth** [comment]
you can usually push to your private registry (make all PREFIX=pwittrock), and modify the test that uses it to use your new image, and run that locally.
This is the outline https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/RELEASES.md

**Comment by pwittrock** [comment]
Tested with an image built in my private repo in PR #22538
Let me know if I am good to build and push the real image.

**Comment by bprashanth** [comment]
LGTM but i'm not sure we're taking non-1.2 prs into HEAD right now

**Comment by pwittrock** [comment]
makes sense.  I haven't seen a lot of instances of the flake occurring and it is only marked p1, so I think it can wait.

**Comment by pwittrock** [comment]
It seems like we are taking non-1.2 PRs into head now.

**Comment by bprashanth** [comment]
Thanks

**Pull request merged**
