### PR TITLE
Fix data race in PVC Run/Stop methods

### LINKED ISSUE #30775: kubernetes-test-go: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/15877/

Run so broken it didn't make JUnit output!

### LINKED ISSUE #30947: Integration test flake: Data race in k8s.io/kubernetes/pkg/controller/volume/persistentvolume
I got the following failure in the unit test of k8s.io/kubernetes/pkg/controller/volume/persistentvolume.
```
==================
WARNING: DATA RACE
Read by goroutine 156:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).Stop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_base.go:471 +0xc0
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.TestControllerSync()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_test.go:204 +0x39b2
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Previous write by goroutine 173:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_base.go:461 +0x2d4

Goroutine 156 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/pkg/controller/volume/persistentvolume/_test/_testmain.go:90 +0x210

Goroutine 173 (finished) created at:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.TestControllerSync()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_test.go:178 +0x32ad
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30913/kubernetes-pull-test-unit-integration/40492/

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #30947
Fixes #30775

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31082)

### CODE REVIEW

**Comment by liggitt** [comment]
changes PVC controller to take a stop channel, fixes a data race when calling `go Run()` then `Stop()`

**Comment by liggitt** [comment]
@jsafrane PTAL

**Comment by liggitt** [comment]
matching issue priority

**Comment by jsafrane** [comment]
lgtm

**Pull request merged**
