### PR TITLE
Fix typo in kubelet kuberuntime container test

### PR DESCRIPTION
**Pull request by verb**
Changes "Expetected" to "Expected"

**What this PR does / why we need it**: Fixes a typo in a test

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by verb** [comment]
I think this probably doesn't need a first-level review. Assigning to approver.

/assign @yujuhong

**Comment by yujuhong** [comment]
/approve no-issue

:-(

**Pull request merged**
