### PR TITLE
job_controller: Add test for SuccessCriteriaMet=False

### PR DESCRIPTION
**Pull request by kaisoz**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR adds a test to ensure that the `SuccessCriteriaMet` condition is ignored when `Status=False`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kaisoz** [comment]
/assign @mimowo 

Thanks!

**Review by soltysh — APPROVED** [review]
/approve

**Comment by tenzen-y** [comment]
Thank you!

**Pull request merged**
