### PR TITLE
AWS: Allow to configure ip and network for master and services

### PR DESCRIPTION
**Pull request by miry**
Fixed script for case when need to setup cluster
in an exists VPC and subnet with ip mask example: 10.0.0.0/8.
And the IP 10.0.0.9 is already reserved.

### CODE REVIEW

**Comment by miry** [comment]
Tested for next cases:

1. Create a new cluster without SUBNET_ID
2. Create a new cluster in existen SUBNET_ID with same Network as default

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
This looks ok to me. @justinsb may want to take a look as well.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
@miry FYI this PR needs a rebase.

**Comment by miry** [comment]
@roberthbailey I rebased and need to test it again, because it seems a lot of good changes happen and covered this changes.

**Comment by roberthbailey** [comment]
@miry -- sounds good. 

Please ping this PR if you still would like for these changes to be reviewed. If your problem has been fixed in the mean time please go ahead and close this PR.

**Comment by roberthbailey** [comment]
@miry - Do you want to move forward with this PR or is it no longer needed?

**Comment by miry** [comment]
@roberthbailey sorry for delay. I verified some cases during this week. Need to finish last one test. will be ready in 1 hour.

**Comment by miry** [comment]
@roberthbailey I found small issue related to reserved ip: https://github.com/miry/kubernetes/commit/9d707ee83bfed7fff44629b5aede702ca8bdc20e Should I create a separate PR for it?

**Comment by roberthbailey** [comment]
@miry Just squash your commits into this same PR.

**Comment by miry** [comment]
@roberthbailey done

**Comment by roberthbailey** [comment]
LGTM. 

@justinsb FYI

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: #20418

**Pull request merged**
