### PR TITLE
Job: Replace deprecated workqueue function with supported one

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
In Job, I replaced the deprecated workqueue library with the supported one:

Deprecated: `NewRateLimitingQueueWithDelayingInterface`

https://github.com/kubernetes/kubernetes/blob/6e0cb243d57592c917fe449dde20b0e246bc66be/staging/src/k8s.io/client-go/util/workqueue/rate_limiting_queue.go#L92-L99

New: `NewRateLimitingQueueWithConfig`

https://github.com/kubernetes/kubernetes/blob/6e0cb243d57592c917fe449dde20b0e246bc66be/staging/src/k8s.io/client-go/util/workqueue/rate_limiting_queue.go#L62-L82

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/assign @alculquicondor 
I would just suggest replacing "library" with "function" in the title

**Comment by tenzen-y** [comment]
> I would just suggest replacing "library" with "function" in the title

SGTM

/retitle Job: Replace deprecated workqueue function with supported one

**Comment by alculquicondor** [comment]
/approve
/hold cancel
(It's not going to merge until the code-freeze is over)

**Pull request merged**
