### PR TITLE
goaway_test: replace slice of channels with channel buffer

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Cleanup: Use a buffered channel instead of an external slice of channels. Currently goroutines would have to block over a single channel.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I haven't done any benchmark testing on this.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
This is test code and this change isn't obviously safe (does it still wait for every goroutine to finish?), so I'm definitely a -1 on this.

**Comment by gaurav1086** [comment]
> This is test code and this change isn't obviously safe (does it still wait for every goroutine to finish?), so I'm definitely a -1 on this.

@lavalamp thanks for the guidance and the review comment. Made slight modifications. Please review.

Here's an example of simulating a similar scenario: https://play.golang.com/p/jqbrwiKE-8L

Let me know your thoughts.

**Comment by gaurav1086** [comment]
closing as not needed.

**Pull request closed without merging**
