### PR TITLE
client-go: share the same transport for generated clientsets

### LINKED ISSUE #91913: kubectl output flooded with warnings about aws-iam-authenticator
**What happened**:
`kubectl -A describe pods`

Results in a flood of messages like:
`W0608 10:47:22.221620   25245 exec.go:203] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 3825 clients constructed calling "aws-iam-authenticator"`

**What you expected to happen**:

No warnings.

**How to reproduce it (as minimally and precisely as possible)**:
In an EKS environment where aws-iam-authenticator is used to get tokens:
```
users:
- name: myuser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - dev
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: dev
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): macos
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.5.0

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind cleanup

Until now, when creating a Kubernetes Clientset, a new RESTClient was created per group/version. Since RESTClient transport can not be cached in some occasions, i.e. when using a custom transport, this has the consequence that each group/version had an independent TCP connection to the API server.

Since the Transport, of the RESTClient can be shared when creating a global Kubernetes Clientset, this PR adds a new RESTClient constructor `RESTClientForConfigAndClient` to allow to generate clientsets using the same http client.

Fixes #91913, #103225

```release-note
client-go uses the same http client for all the generated groups and versions, allowing to share customized transports for multiple groups versions.
```

### CODE REVIEW

**Comment by aojea** [comment]
I''l follow up tomorrow, these errors happened before because of the timeout option

**Comment by aojea** [comment]
/retest 
👀 
> kubernetes/pkg/kubelet: TestUpdatePodWithTerminatedPod expand_less0s=== RUN   TestUpdatePodWithTerminatedPod     pod_workers_test.go:314: podWorker state should not be marked terminated for a running pod --- FAIL: TestUpdatePodWithTerminatedPod (0.00s) | kubernetes/pkg/kubelet: TestUpdatePodWithTerminatedPod expand_less | 0s | === RUN   TestUpdatePodWithTerminatedPod     pod_workers_test.go:314: podWorker state should not be marked terminated for a running pod --- FAIL: TestUpdatePodWithTerminatedPod (0.00s)
> -- | -- | -- | --
> kubernetes/pkg/kubelet: TestUpdatePodWithTerminatedPod expand_less | 0s
> === RUN   TestUpdatePodWithTerminatedPod     pod_workers_test.go:314: podWorker state should not be marked terminated for a running pod --- FAIL: TestUpdatePodWithTerminatedPod (0.00s)
> k8s.io/kubernetes/pkg/kubelet/eviction: TestStart expand_less0s=== RUN   TestStart I1009 00:12:42.750086   57400 memory_threshold_notifier.go:74] "Eviction manager: created memoryThresholdNotifier" notifier="hard memory eviction threshold"     controller.go:266: missing call(s) to *eviction.MockCgroupNotifier.Start(is equal to 0xc000183200) /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/memory_threshold_notifier_test.go:177     controller.go:266: aborting test due to missing call(s) --- FAIL: TestStart (0.00s) | k8s.io/kubernetes/pkg/kubelet/eviction: TestStart expand_less | 0s | === RUN   TestStart I1009 00:12:42.750086   57400 memory_threshold_notifier.go:74] "Eviction manager: created memoryThresholdNotifier" notifier="hard memory eviction threshold"     controller.go:266: missing call(s) to *eviction.MockCgroupNotifier.Start(is equal to 0xc000183200) /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/memory_threshold_notifier_test.go:177     controller.go:266: aborting test due to missing call(s) --- FAIL: TestStart (0.00s)
> k8s.io/kubernetes/pkg/kubelet/eviction: TestStart expand_less | 0s
> === RUN   TestStart I1009 00:12:42.750086   57400 memory_threshold_notifier.go:74] "Eviction manager: created memoryThresholdNotifier" notifier="hard memory eviction threshold"     controller.go:266: missing call(s) to *eviction.MockCgroupNotifier.Start(is equal to 0xc000183200) /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/memory_threshold_notifier_test.go:177     controller.go:266: aborting test due to missing call(s) --- FAIL: TestStart (0.00s)
>

**Comment by liggitt** [comment]
flaking unit test was just introduced, tracking in https://github.com/kubernetes/kubernetes/issues/105589

**Comment by liggitt** [comment]
changes look reasonable to me

https://github.com/kubernetes/kubernetes/pull/105490#issuecomment-938986612 is still outstanding

**Comment by liggitt** [comment]
> where should I do it for ` your own custom clientset` ?

if it's in the clientset generator, that's sufficient

**Pull request merged**
