### PR TITLE
[WIP][IGNORE ME]Testing GCE external cloud provider

### PR DESCRIPTION
**Pull request by dims**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@aojea recreating the scenario i mentioned in https://github.com/kubernetes/kubernetes/pull/117503#issuecomment-1703667872

**Comment by aojea** [comment]
some findings on `pull-kubernetes-e2e-gci-gce-ingress	`

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/cloud-controller-manager.log

I0903 11:55:35.780107       9 serving.go:348] Generated self-signed cert in-memory
W0903 11:55:36.225875       9 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
Error: unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"




https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/glbc.log

F0903 11:47:38.434213       1 main.go:119] Failed to ensure BackendConfig CRD: timed out waiting to Get BackendConfig CRD: timed out waiting for the condition


https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/kube-addon-manager.log

/opt/kube-addons.sh: line 136: generate_prune_allowallowlist_flags: command not found
INFO: == Generated kubectl prune allowlist flags:  ==
INFO: == Kubernetes addon manager started at 2023-09-03T11:29:18+00:00 with ADDON_CHECK_INTERVAL_SEC=60 ==
Error from server (NotFound): serviceaccounts "default" not found
WRN: == Error getting default service account, retry in 0.5 second ==
Error from server (NotFound): serviceaccounts "default" not found
WRN: == Error getting default service account, retry in 0.5 second ==


https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/kube-controller-manager.log

I0903 11:52:20.982174       9 controllermanager.go:612] "Started controller" controller="deployment-controller"
I0903 11:52:20.982218       9 controllermanager.go:583] "Starting controller" controller="node-ipam-controller"
E0903 11:52:20.982233       9 controllermanager.go:586] "Error starting controller" err="--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured" controller="node-ipam-controller"
E0903 11:52:20.982241       9 controllermanager.go:240] "Error starting controllers" err="--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured"



https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/kube-scheduler.log

I0903 11:28:51.682873       9 flags.go:64] FLAG: --write-config-to=""
I0903 11:28:54.305350       9 serving.go:380] Generated self-signed cert in-memory
W0903 11:29:05.217370       9 authentication.go:368] Error looking up in-cluster authentication configuration: Get "https://localhost:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": net/http: TLS handshake timeout
W0903 11:29:05.217421       9 authentication.go:369] Continuing without authentication configuration. This may treat all requests as anonymous.
W0903 11:29:05.217432       9 authentication.go:370] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I0903 11:29:11.313932       9 configfile.go:94] "Using component config" config=<
	apiVersion: kubescheduler.config.k8s.io/v1


https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ingress/1698290219729555456/artifacts/bootstrap-e2e-master/kube-master-configuration.log

Sep 03 11:29:13.651308 bootstrap-e2e-master configure-helper.sh[11963]: [cloud.kubernetes.monitoring.proto.SerialportLog] {"cluster_hash":"get-metadata-value-error","vm_instance_name":"bootstrap-e2e-master","boot_id":"997bec0dc3454ead8dd2ba338fae095d","timestamp":"2023-09-03T11:29:13.637850333Z","bootstrap_status":{"step_name":"UpdateLegacyAddonNodeLabels","status":"COMPLETED","status_reason":"","latency":"1.09272s"}}
Sep 03 11:29:22.451598 bootstrap-e2e-master configure-helper.sh[12215]: error: the server doesn't have a resource type "volumesnapshotclasses"
Sep 03 11:29:32.658286 bootstrap-e2e-master configure-helper.sh[12413]: error: the server doesn't have a resource type "volumesnapshotclasses"
Sep 03 11:29:42.828917 bootstrap-e2e-master configure-helper.sh[12515]: error: the server doesn't have a resource type "volumesnapshotclasses"

**Comment by aojea** [comment]
@dims https://github.com/kubernetes/kubernetes/pull/120389

**Comment by dims** [comment]
We don't really need `pull-kubernetes-e2e-gce-canary` so removing it here:
https://github.com/kubernetes/test-infra/pull/30598/files

**Comment by dims** [comment]
- `pull-kubernetes-e2e-gce-canary` will remove in https://github.com/kubernetes/test-infra/pull/30598/files
- `pull-kubernetes-node-e2e-containerd` is an existing flake

**Comment by dims** [comment]
All the other CI jobs are progressing well  (for a while!) - currently in `Running Suite`

**Comment by dims** [comment]
@upodroid if you want to fix `pull-kubernetes-e2e-gce-cos-kubetest2` or drop it entirely ... your call

**Pull request closed without merging**
