### PR TITLE
Add the pod with the specified nodename to the schedule life cycle.

### PR DESCRIPTION
**Pull request by mikechengwei**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Now pod specify `nodename` field will skip schedule phase , it will cause the volume binding to not be executed and the pod failed to start. 
I think we shouldn't skip plugins running phase, we can give the feasibleNodes directly at `findNodesThatFitPod` method by `nodename` field:

https://github.com/kubernetes/kubernetes/blob/363c3b89f570142da5c43b1ccbd99629f03e0ee0/pkg/scheduler/core/generic_scheduler.go#L259

I think this is a friendly method to incorporate the specified nodename schedule into the current schedule life cycle.

**Which issue(s) this PR fixes**:
#93145 

#89953

**Special notes for your reviewer**:
My design is giving the feasibleNodes directly  in findNodesThatFitPod method  when we specify `nodename` field.

I think although we specified `nodename`, we can't skip the predicate stage, checking node info by `nodename` field   is also required. 

Therefore, the pod started by the specified node name can also be added to the schedule life cycle.

**Does this PR introduce a user-facing change?**:
None

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
None

### CODE REVIEW

**Comment by mikechengwei** [comment]
@liu-cong  Do  you have time to  help me review this pr?

**Comment by ahg-g** [comment]
Unfortunately this PR is not correct. The scheduler by design doesn't insert pods with `pod.Spec.NodeName` set into the queue, those are considered scheduled pods. Use node affinity rather than setting the `NodeName` directly If you want the scheduler to handle the pod.

**Comment by zhouya0** [comment]
@ahg-g I saw there's `nodeName` plugin in filter plugin, like you said, is it really needed? 
https://github.com/kubernetes/kubernetes/blob/1fdd8fb213e0361e8f18b1dd152dddb4c88ad183/pkg/scheduler/algorithmprovider/registry.go#L98

**Comment by ahg-g** [comment]
> @ahg-g I saw there's `nodeName` plugin in filter plugin, like you said, is it really needed?
> https://github.com/kubernetes/kubernetes/blob/1fdd8fb213e0361e8f18b1dd152dddb4c88ad183/pkg/scheduler/algorithmprovider/registry.go#L98

This plugin is a re-write of an old predicte. It is likely not needed, but I would rather keep it in case it addressed race conditions related to updating the NodeName by another controller while the pod is being scheduled.

**Pull request closed without merging**
