### PR TITLE
Revert "Kubelet: Use RepoDigest for ImageID when available"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#33014

This completely broke all Kubemark suites.

@DirectXMan12 @yujuhong @ncdc @derekchiang

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34386)

### CODE REVIEW

**Comment by wojtek-t** [comment]
There were issues in PR kubemark testing project. I hopefully fixed it, so retesting now (regular post-submit kubemark tests were broken by this PR).

@k8s-bot kubemark test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-oncall FYI

**Comment by wojtek-t** [comment]
@k8s-bot kubemark test this, issue: #IGNORE (I fixed the problems with the project)

**Comment by wojtek-t** [comment]
```Jenkins Kubemark GCE e2e — Build succeeded.```

Since all kubemark runs are now red, I'm manually merging it.

**Comment by deads2k** [comment]
@derekwaynecarr fyi

**Comment by wojtek-t** [comment]
@derekwaynecarr @deads2k - the PR that will make kubemark presubmit blocking PR merges is already in:
https://github.com/kubernetes/contrib/pull/1849
@apelisse will hopefully push it soon, so in the future we shouldn't be force to revert anything because of kubemark.

**Comment by eparis** [comment]
@wojtek-t I'm going to request that everyone post something about what broke before/shortly after all reverts. What are the original authors supposed to do with this report? I get that reverts need to be done quickly. But they need to immediately be followed with something the original author can use to move forward.

**Comment by gmarek** [comment]
@eparis - the problem is that it's a lot harder for build-cop to understand what exactly broke, than for the PR author and it should be his/hers responsibility. OTOH I agree that we should add links to failures to make it easier to find.

**Comment by eparis** [comment]
@gmarek where a link to the failure? Somehow it was realized this PR was the problem. Hopefully in the future we can put the info that lead to that realization in the revert PR. I'm not suggesting the reverter fix it or anything, but what info does the original PR author have to see what went wrong?

**Comment by gmarek** [comment]
Quite often it's pretty clear which PR breaks stuff, as there's only a small number of PRs that touch each part of the system, and we know which part is causing failures. Also from time to time it's just a binary search that indicates which PR is causing breakage. As I wrote - I agree that we should add logs from the failure (it wasn't here, but it should be pretty straightforward to get them from testgrid), but I'll strongly oppose adding more responsibilities for build cops.

**Comment by ncdc** [comment]
Somebody other than the author of the reverted PR has to provide at least a link to the failing build. Any disagreement there?

**Comment by gmarek** [comment]
Nope - that we all agree.

**Comment by gmarek** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6582

**Comment by DirectXMan12** [comment]
is there a way to see the hollow-node logs from the run?

**Pull request merged**
