### PR TITLE
Revert "Add self anti-affinity to kube-dns pods"

### LINKED ISSUE #54164: Kube-dns pods coming up super slowly in large clusters
Our 5k-node cluster jobs recently started failing even before the e2e tests start. The reason is the step which checks that all kube-system pods are running is timing out:

```
I1018 07:27:06.071] Oct 18 07:27:06.070: INFO: Waiting up to 10m0s for all pods (need at least 8) in namespace 'kube-system' to be running and ready
I1018 07:27:09.904] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-24tgk is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2cb7g is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2hn22 is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2vdpq is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
...
```

cc @kubernetes/sig-scalability-misc @wojtek-t @porridge

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#57683

Fixes https://github.com/kubernetes/kubernetes/issues/54164

/cc @wojtek-t 
cc @bsalamat @misterikkit @bowei @MrHohn

### CODE REVIEW

**Comment by shyamjvs** [comment]
Wrt release-note, I'm not sure what's the policy here for a PR reverting a PR having a release-note.

**Comment by wojtek-t** [comment]
@MaciekPytel - FYI

> Wrt release-note, I'm not sure what's the policy here for a PR reverting a PR having a release-note.

Remove "releate-note" label from the original PR.

/lgtm
/approve no-issue

**Comment by wojtek-t** [comment]
@davidopp - FYI

**Comment by eseliger** [comment]
I know it's not a really clean solution but having a service target the core-dns pods would make kubernetes try to spread the pods across nodes, without having the problem of not scheduling them on one node at all (the case where only one node is available).. maybe it's a starting point to figure out what else might call this behavior on the apiserver 🤔

**Pull request merged**
