### PR TITLE
Update GO address link

### PR DESCRIPTION
**Pull request by LJTian**
Resubmit PR, the old PR is  #112473

update go address link
golang.org -> go.dev

What type of PR is this?
/kind documentation

What this PR does / why we need it:
I feel like this is forgotten content and needs to be revised.

Special notes for your reviewer:
Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/ok-to-test

You need to edit the PR description to include the release note (NONE).

**Comment by LJTian** [comment]
Special notes for your reviewer:
Does this PR introduce a user-facing change?
```
NONE
```

**Comment by lavalamp** [comment]
You have to edit that into the [OP](https://github.com/kubernetes/kubernetes/pull/112966#issue-1403891047)

**Comment by LJTian** [comment]
I'm not sure if I'm modifying in the right place?

**Comment by lavalamp** [comment]
I edited it for you, look at what it is now for next time.

/approve
/lgtm

**Comment by lavalamp** [comment]
We just rearranged OWNERS, you need someone in dep approvers or sig-arch approvers for this readme now.

/sig arch

**Comment by LJTian** [comment]
ok

/cc @dims 
/cc @johnbelamaric 
/cc @derekwaynecarr

**Pull request merged**
