### PR TITLE
Add flags for etcd machines and tls

### PR DESCRIPTION
**Pull request by vishvananda**

### CODE REVIEW

**Comment by thockin** [comment]
LGTM but needs a rebase

@rsokolowski for inclusion

**Comment by vishvananda** [comment]
it isn't really compatible with the new code that adds a flag for a single server. I could rename the flag from etcd_server to etcd_servers and then modify the retry code to loop through the supplied servers during the reconnect loop. Does that sound appropriate?

**Comment by piosz** [comment]
Is this PR active? If not please close it according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/pull-requests.md

**Comment by piosz** [comment]
Closing according to the mentioned policy.

**Comment by thockin** [comment]
Sorry I lost track of this PR - is this because you want to use kube2sky outside of the current context?  We'll probably be moving away from using etcd as the backend for skydns (now that it is abstracted in skydns code)

**Comment by vishvananda** [comment]
This was part of making skydns and kube2sky  highly available yes. I was using an etcd cluster for this, but if there is an alternative in the works I won't bother to update the pr. Thanks!

**Comment by thockin** [comment]
Thanks, then.  We'll leave it closed.

**Pull request closed without merging**
