### PR TITLE
Fix enormous-startup test config

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by ixdy** [comment]
Oops. Good catch. @ihmccreery 

LGTM

**Comment by lavalamp** [comment]
LGTM

**Comment by ixdy** [comment]
wait, no

**Comment by ixdy** [comment]
Doesn't the `startup` job start the cluster, with the other job running tests against this cluster? In that case, they should use the same name.

**Comment by ixdy** [comment]
Or I guess maybe these are different jobs? Am I understanding correctly that the `startup` job is just there to independently verify that you can start and tear down a large cluster?

**Comment by lavalamp** [comment]
@ixdy I think they are in different zones. So they must be different jobs.

**Comment by gmarek** [comment]
Those are different tests. One allows some notready nodes, other do not. Can buildcop merge it? @spxtr

**Comment by lavalamp** [comment]
I only haven't LGTMd because the e2e test is failing, I'm assuming this must be a flake.

@k8s-oncall

**Comment by lavalamp** [comment]
Yeah, flake is #21463

LGTM

**Comment by gmarek** [comment]
@k8s-bot test this issue: #21463

**Pull request closed without merging**
