### PR TITLE
Automated cherry pick of #27741

### PR DESCRIPTION
**Pull request by zmerlynn**
Cherry pick of #27741 on release-1.2.

### CODE REVIEW

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this, issue #IGNORE (release-1.2 isn't up to date on de-flake)

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this, issue #IGNORE (@kubernetes/test-infra-maintainers, that last failure was bizarre?)

**Comment by spxtr** [comment]
#27462. It's been cropping up more often than before, and I'm starting to think it's not entirely caused by force pushes anymore.

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this, #15713

**Comment by zmerlynn** [comment]
@spxtr: Yeah, this definitely wasn't a force push on the base branch.

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: #27462

**Pull request merged**
