### PR TITLE
node: test file use k8s.io/utils/clock instead

### PR DESCRIPTION
**Pull request by jonyhy96**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

replace `k8s.io/apimachinery/pkg/util/clock` with `k8s.io/utils/clock`  since [kubernetes/utils#221](https://github.com/kubernetes/utils/pull/221) has been merged

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
Please hold till changes are vendored in :)
/hold

**Comment by MadhavJivrajani** [comment]
You'll probably just have to change the test files once the changes are merged in.

**Comment by wojtek-t** [comment]
I will approve once the original PR is merged and this PR is rebased.

**Comment by MadhavJivrajani** [comment]
@jonyhy96 please rebase the PR and this should be good to go :)

**Comment by jonyhy96** [comment]
> @jonyhy96 please rebase the PR and this should be good to go :)

Thx :). Will work on that soon

**Pull request merged**
