### PR TITLE
Fix Node soft-lockup

### PR DESCRIPTION
**Pull request by gmarek**
Ref. #37853

After those two reverts I can't reproduce kernel soft lockup using kubemark experiments.

cc @smarterclayton @mtaufen @vishh @sjenning @derekwaynecarr @smarterclayton @jeremyeder @timothysc @kubernetes/sig-node @fgrzadkowski @wojtek-t

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by eparis** [comment]
The decision was made last night to gate this behind a flag if it turned out to be tickling the kernel bug. Not to revert. Remember, this patch is fine, so we need a path forward when the kernel gets fixed.

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/38258

**Comment by timothysc** [comment]
shouldn't we just flag this as do-not-merge?

**Pull request closed without merging**
