### PR TITLE
Common auth plugins should always be available

### PR DESCRIPTION
**Pull request by dims**
Whether `providerless` is present or not, the OIDC plugin
should be available. please see the following PR:
https://github.com/kubernetes/kubernetes/pull/100606

Eagle eyes of @coderanger caught this :) thanks a ton!

Also does this mean we have no tests for this?

/kind bug
/sig auth
/priority important-soon
/assign @liggitt @palnabarun 

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by palnabarun** [comment]
/milestone v1.21

(since this is fixing an unintended removal)

**Comment by liggitt** [comment]
> Also does this mean we have no tests for this?

we have unit tests for the oidc provider, but apparently none that ensure that kubectl always links in that provider.

**Pull request merged**
