### PR TITLE
Add FeatureGates field to KubeletConfiguration

### PR DESCRIPTION
**Pull request by mtaufen**
This threads the `--feature-gates` flag through the `KubeletConfiguration` object and also allows setting feature gates via dynamic Kubelet configuration. 

/cc @jlowdermilk

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31556)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Interesting bootstrapping mechanism, couple questions:
* Is dynamic config loaded once at kubelet startup? If so, what happens if a node is restarted and now loads a different feature-gate value than what it previously? That may cause some interesting breaks.
* What happens if dynamic config's feature-gates doesn't match the created feature-gates? Having different values between master/node components may result in unexpected behavior.

Overall I like the idea of having feature-gates loaded from dynamic config. I think a nice end goal is feature-gates specified only on the apiserver, and propagated via dynamic config to *all* other components. In the meantime tho, having some components get it via flag and others via dynamic sounds like a recipe for deployment headaches.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/kubelet/app/server.go, line 346 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ84mWMGPLOI37WX_T-:-KQ8-JSk3VfOJEHxiMTT:b-dn0h66) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/cmd/kubelet/app/server.go#L346)):*
> ```Go
> 				}
> 				// Update feature gates from the new config
> 				err = utilconfig.DefaultFeatureGate.Set(s.KubeletConfiguration.FeatureGates)
> ```

I'm surprised this works, given `Set` is not declared in `FeatureGate`. Either way should be added to the interface definition if you're going to use it outside the package.

---

*[pkg/util/config/feature_gate.go, line 210 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ80C1j1evGAS3SYodq:-KQ80C1j1evGAS3SYodr:bv4alhi) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/pkg/util/config/feature_gate.go#L210)):*
> ```Go
> // the flag value to another location before parsing it into the FeatureGate object, but still want
> // the known features reported in the usage string.
> func (f *featureGate) AddStringFlag(fs *pflag.FlagSet, target *string) {
> ```

This doesn't do what the comment claims; after calling AddStringFlag, fs.Parse() will only store the string var, not update the object. If you want to both store the flag value at the passed in location and parse/generate the FeatureGate object, you'll need to e.g. save the pointer in a field and conditionally set its value in `featureGate.Set`.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQ82f6h2Ak8RrFdwVbB:bso00b1)*

**Comment by mtaufen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/kubelet/app/server.go, line 346 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ84mWMGPLOI37WX_T-:-KQ87VYsuy9yBDUxKMbd:btohrsg) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/cmd/kubelet/app/server.go#L346)):*
<details><summary><i>Previously, jlowdermilk (Jeff Lowdermilk) wrote…</i></summary>
> I'm surprised this works, given `Set` is not declared in `FeatureGate`. Either way should be added to the interface definition if you're going to use it outside the package.
</details>
`DefaultFeatureGate` is a `featureGate` struct, which implements `Set` in order to implement `pflag.Value`. If you would like to expose `Set` on the `FeatureGate` interface as well for consistency, I think that makes sense.

---

*[pkg/util/config/feature_gate.go, line 210 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ80C1j1evGAS3SYodq:-KQ881HkLapsu5w3wLD9:bsrdz8y) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/pkg/util/config/feature_gate.go#L210)):*
<details><summary><i>Previously, jlowdermilk (Jeff Lowdermilk) wrote…</i></summary>
> This doesn't do what the comment claims; after calling AddStringFlag, fs.Parse() will only store the string var, not update the object. If you want to both store the flag value at the passed in location and parse/generate the FeatureGate object, you'll need to e.g. save the pointer in a field and conditionally set its value in `featureGate.Set`.
</details>
By "in case you want to direct the flag value to another location before parsing it" I don't mean to imply that `AddStringFlag` sets something up to parse it for you. I updated the comment to clarify.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556)*

**Comment by vishh** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQ8AIrrfXEHAxTPogyX:bnfp4nl)*

**Comment by vishh** [comment]
cc @dchen1107 @pwittrock since this is a v1.4 bug.

**Comment by mtaufen** [comment]
Yes, Kubelet attempts to get KubeletConfiguration from the API server on startup, falls back to flags if it can't, and restarts when it finally sees new config from the API server. 

If you try to use dynamic config with feature gates and feature gates from flags, you should definitely be careful to ensure your nodes are configured the way you want. If you either (a) just use dynamic config, or (b) make sure the dynamic config's feature gates match the ones you set in flags you should be fine. 

That said, you will have to keep in mind, for case (a), that any gated features will be set to their default values until the dynamic config gets pulled down. This extends to the node-restart case, your Kubelet uses whatever it got from it's startup flags until the dynamic config gets pulled down.

If there is a mismatch, dynamic config's feature gates will override the feature gates from flags. 

In general, you are correct, one needs to be careful. Given that all gated features are currently alpha, including dynamic configuration, how big a concern is this? It won't ever come up in production, correct?

I can certainly see this being a bigger concern down the road, once we're also gating beta features, etc. I could change this PR to populate `DefaultFeatureGate` from the dynamic config *only* when no feature gates were set via flags, which forces the use of only one or the other (or neither). Does that sound ok?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQ89mj8s3MlUduZzDj9:bs9lqdb)*

**Comment by mtaufen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/config/feature_gate.go, line 210 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ80C1j1evGAS3SYodq:-KQ8EtPY6F74MPPOC4o4:bcg1r8j) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/pkg/util/config/feature_gate.go#L210)):*
<details><summary><i>Previously, jlowdermilk (Jeff Lowdermilk) wrote…</i></summary>
> In that case, I don't think this is useful to add. Just use AddFlag and only call `DefaultFeatureGate.Set` if an override value is provided in dynamic config.
</details>
I thought it would be nice to report the known features in the usage string. Would you be ok with adding `KnownFeatures()` to the `FeatureGate` interface?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556)*

**Comment by jlowdermilk** [comment]
We're already gating beta features, and some alpha features will be enabled by default in production (enabled in previous release, grandfathered in). Given that dynamic config is itself alpha, I'm ok with it.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/kubelet/app/server.go, line 346 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ84mWMGPLOI37WX_T-:-KQM91A9L4L88aQFtWlB:bi85br5) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/cmd/kubelet/app/server.go#L346)):*
<details><summary><i>Previously, mtaufen (Michael Taufen) wrote…</i></summary>
> `DefaultFeatureGate` is a `featureGate` struct, which implements `Set` in order to implement `pflag.Value`. If you would like to expose `Set` on the `FeatureGate` interface as well for consistency, I think that makes sense.
</details>
Yes please to exposing Set on FeatureGate for clarity.

---

*[pkg/util/config/feature_gate.go, line 210 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ80C1j1evGAS3SYodq:-KQM821paV2fbbM8F1XR:b-5qgvm8) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/pkg/util/config/feature_gate.go#L210)):*
<details><summary><i>Previously, mtaufen (Michael Taufen) wrote…</i></summary>
> I thought it would be nice to report the known features in the usage string. Would you be ok with adding `KnownFeatures()` to the `FeatureGate` interface?
</details>
Adding `KnownFeatures()` to interface sgtm.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQM8Qci0ePUFzU-y_lZ:b-lqoo6b)*

**Comment by mtaufen** [comment]
Ok, sgtm. We will still have to figure out what to do when dynamic config moves out of alpha. We might choose to just document this sharp edge in a very obvious way, or force a choice between remote gates and gates from flags, or something else. I will make a note to review this when the time comes to graduate dynamic config to beta. 

---

Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/kubelet/app/server.go, line 346 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ84mWMGPLOI37WX_T-:-KQMQH1PfVcVR4UUuyQC:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/cmd/kubelet/app/server.go#L346)):*
<details><summary><i>Previously, jlowdermilk (Jeff Lowdermilk) wrote…</i></summary>
> Yes please to exposing Set on FeatureGate for clarity.
</details>
Done.

---

*[pkg/util/config/feature_gate.go, line 210 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-KQ80C1j1evGAS3SYodq:-KQMQI6VyXOZ2TzNnHHy:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/d7ee8f75232e3f9a4679c0abad0a514ca45866fc/pkg/util/config/feature_gate.go#L210)):*
<details><summary><i>Previously, jlowdermilk (Jeff Lowdermilk) wrote…</i></summary>
> Adding `KnownFeatures()` to interface sgtm.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQMTTwn46bcWGgEerp4:bxugxh4)*

**Comment by mtaufen** [comment]
@jlowdermilk good to go with this?

**Comment by jlowdermilk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31556#-:-KQOd2Ej6iJtjegZrO8C:bnfp4nl)*

**Comment by dchen1107** [comment]
cc/ @pwittrock release czar?

**Comment by mtaufen** [comment]
I will get back on top of this next week.

**Comment by mtaufen** [comment]
@k8s-bot gci gce test this issue #IGNORE

**Pull request merged**
