### PR TITLE
remove unused code in kubeadm error.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
remove unused code in kubeadm error.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rosti — APPROVED** [review]
Looks OK to me

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

Thank you for the cleanup!

**Review by luxas — APPROVED** [review]
/lgtm
for me as well, thanks!

**Pull request merged**
