### PR TITLE
Updating go-restful to the latest version

### LINKED ISSUE #4083: swagger json is invalid
does not validate with swagger-tools CLI tool: https://github.com/apigee-127/swagger-tools/blob/master/docs/CLI.md#validate

### PR DESCRIPTION
**Pull request by nikhiljindal**
Lots of great new stuff.
- We now have ServiceErrorHandler which can be used for https://github.com/GoogleCloudPlatform/kubernetes/issues/4347
- https://github.com/emicklei/go-restful/pull/173 fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/4083
- https://github.com/emicklei/go-restful/commit/358e2483dac774992c858945b509f560547c07ba should fix our problem of swagger spec rearranging each time we run hack/update-swagger-spec

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Awesome. Build fails though.
```
# github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation/schema.go:129: invalid operation: fieldDetails.DataTypeFields.Items[0] (type *swagger.Item does not support indexing)
!!! Error in /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:305
```

**Comment by nikhiljindal** [comment]
Thanks! Updated the code to fix that.
Verified that hack/test-go passes on my local machine.

**Comment by bgrant0607** [comment]
LGTM.

**Pull request merged**
