### PR TITLE
code cleanup around the load balance timeout variables

### PR DESCRIPTION
**Pull request by chendave**
- remove the comment about the internal ticket number.
- fix the typo, the method is `GetServiceLoadBalancerCreationTimeout` instead of `GetServiceLoadBalancerCreateTimeout`.

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig testing

### CODE REVIEW

**Comment by aojea** [comment]
@chendave this doesn't add much net value?
can we skip it?

**Comment by chendave** [comment]
> can we skip it?

sure, this indeed not a must have but just a cleanup.

**Pull request closed without merging**
