### PR TITLE
Fix federated ingress ip propagation

### PR DESCRIPTION
**Pull request by ghost**
Right now the loadbalancer IP address allocation, which is exposed as loadbalancer status on cluster-level ingress objects is not correctly propagated 'upwards' to the status of the federated ingress object.

The cause of this is that the Update() method in our golang API silently ignores status updates ( UpdateStatus() rather than Update() should be used).  See https://github.com/kubernetes/kubernetes/issues/33493 for more details.

Still busy doing final e2e manual testing on this.  As soon as those are passing consistently, I'll clean up for code review. 

cc @kubernetes/sig-cluster-federation FYI

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33502)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
OK, federated ingress e2e tests are all passing now. Some final manual testing and cleanup to come, but a preliminary review would be useful.

The results below are from a local test run.  The two Federated Service failures are because I don't have DNS set up correctly on my local test clusters, so ignore them.

Summarizing 2 Failures:
[Fail] [k8s.io] [Feature:Federation] Federated Services DNS [It] should be able to discover a federated service 
/home/quinton/code/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/federation-util.go:450
[Fail] [k8s.io] [Feature:Federation] Federated Services DNS non-local federated service [It] should be able to discover a non-local federated service 
/home/quinton/code/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/federation-util.go:450
Ran 18 of 407 Specs in 2088.185 seconds
FAIL! -- 16 Passed | 2 Failed | 1 Pending | 388 Skipped --- FAIL: TestE2E (2088.20s)

**Comment by quinton-hoole** [comment]
@k8s-bot Federation gce e2e test this

**Comment by nikhiljindal** [comment]
@quinton-hoole the "F" needs to be small in federation :)

@k8s-bot federation gce e2e test this

**Comment by nikhiljindal** [comment]
Code changes LGTM. Can merge if tests pass

**Comment by quinton-hoole** [comment]
Thanks @nikhiljindal .  Checking out test failures.  I actually split this PR up into 5 separate ones (one per commit). So that we can merge them/roll them back independently.   But I will first figure out what's failing here.  The tests all passed locally.

**Comment by quinton-hoole** [comment]
Only the federated ingress failed to get an external IP.  Everything else passed. Might be a quota issue on the test project.  Checking it out (and in the mean time re-rerunning to check whether it's a flake).

**Comment by quinton-hoole** [comment]
For posterity, the logs of the failure:

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/33502/kubernetes-pull-build-test-federation-e2e-gce/58

**Comment by quinton-hoole** [comment]
@k8s-bot Federation gce e2e test this

**Comment by quinton-hoole** [comment]
@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
Sorry, please ignore https://github.com/kubernetes/kubernetes/pull/33502#issuecomment-250033403  This is one of the 5 PR's I mentioned.

**Comment by nikhiljindal** [comment]
ok cool. Code changes LGTM. Feel free to self apply the label to all of them once you have got the tests to pass

**Comment by quinton-hoole** [comment]
Same failure again, so it's not just an infrequent flake.  I'll have to debug harder :-)

```
Sep 27 18:11:49.234: INFO: Ingress failed to acquire an IP address within 15m0s
```

**Comment by quinton-hoole** [comment]
I've confirmed that the Jenkins Federation GCE e2 test is failing due to exhausted quota of backend-services in GCE in the project used to run per-PR tests.  That is in turn at least partially addressed by #33787.  So the problem is not in this PR.

As per in-person discussion with @nikhiljindal , and his comments above, I'm going to merge the 5 commits comprising this PR, each in a separate PR, on the basis that they are all strictly improvements over the consistently failing e2e test that we currently have.

**Comment by quinton-hoole** [comment]
Split into separate PR's #33605, #33607, #33608, #33609. #33610 .  Closing this one as duplicate.

**Pull request closed without merging**
