### PR TITLE
[release-notes] DefaultHostNetworkHostPortsInWorkloads -> DefaultHostNetworkHostPortsInPodTemplates

### PR DESCRIPTION
**Pull request by dims**
feature name got changed but release-notes has the old name.

See:
- https://github.com/kubernetes/kubernetes/pull/117696/files#diff-71e3b98f9a6bbf5b8421e26a7ba0c079f397cd8d49abacdad943c66a4f44f03dR222
- https://cs.k8s.io/?q=DefaultHostNetworkHostPortsInPodTemplates&i=nope&files=&excludeFiles=&repos=

#### What type of PR is this?
/kind bug
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/117696

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/hold
For @kubernetes/release-team-leads and @kubernetes/release-team-release-notes to ACK this change

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Comment by sanchita-07** [comment]
They will get reflected in the CHANGELOG.md once [this](https://github.com/kubernetes/sig-release/pull/2296/files#diff-d7f5705b1a6f61c7bb81089eb94f0bf632d1e729d26e8a2731cfdc8520f992d0) gets merged.

**Pull request merged**
