### PR TITLE
Cleanup deprecated Forever function

### PR DESCRIPTION
**Pull request by 0xgj**
Since util.Forever function has been deprecated, we should cleanup these
pieces of code.

### CODE REVIEW

**Comment by mikedanese** [comment]
This still does not compile. You should also delete the function Forever if it is no longer used.

**Comment by invenfantasy** [comment]
Ok, i will do that.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
Jenkins test flakes.

@k8s-bot test this please

**Comment by wojtek-t** [comment]
LGTM

**Comment by mikedanese** [comment]
@invenfantasy Thanks!

**Comment by invenfantasy** [comment]
@mikedanese, @wojtek-t, @yujuhong  thank you.

**Pull request merged**
