### PR TITLE
Fix function comment to consistent with its name

### PR DESCRIPTION
**Pull request by ping035627**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it: **
Fix function comment to consistent with its name.

**Which issue(s) this PR fixes** (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?:**

release-note
NONE

### CODE REVIEW

**Review by maheshwarigagan — APPROVED** [review]

**Comment by ping035627** [comment]
@yliaog Excuse me, can this pr be merged? Need approved label. Thanks.

**Comment by ping035627** [comment]
@justinsb Excuse me, can this pr be merged? Need approved label. Thanks.

**Comment by ping035627** [comment]
@k82cn the approve label doesn't work, can you help to see what's going on?

**Comment by ping035627** [comment]
@lavalamp Excuse me, can this pr be merged? Need approved label. Thanks.

**Comment by ping035627** [comment]
@deads2k hi, can you review this pr? Need approved label. Thanks.

**Pull request merged**
