### PR TITLE
Revert "Gracefully delete pods from the Kubelet"

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Reverts GoogleCloudPlatform/kubernetes#8641

After merging #8641 latency metrics spiked from ~2s to ~16s during density e2e test. I have verified locally that reverting this PR solves the problem. It seems that the problem begins when we try to delete RC. All metrics suddenly spike to O(seconds). This includes simple operations like updating a node:

```
INFO: WARNING Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:16.170251s}
INFO: WARNING Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:11.774167s}
INFO: WARNING Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:5.656098s}
INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:3.197476s}
INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:2.425735s}
```

Please merge it ASAP to fix jenkins e2e scalability job.

@bgrant0607 @smarterclayton @wojtek-t

### CODE REVIEW

**Comment by bgrant0607** [comment]
e2e is failing, also.

**Comment by smarterclayton** [comment]
If the density tests are spiking it may be a result of the use of TTL (and an issue on the etcd side), an issue with the design of the density test (graceful deletion means deletes take longer), or an unexpected server interaction.

How do I run the density e2e test directly?  If there's not an obvious fix I'm probably out of time to devote to this issue (and the risk is probably larger than we expected), so we'll probably have to drop it from 1.0z

**Comment by smarterclayton** [comment]
The other option (which I like better) is to set the default to 0 (on the apiserver) and the minimum on the kubelet to 30s, which lets us selectively test this (opt in).  The increase in minimum on the nose may result in larger numbers of failed pods (scheduler is more likely to double schedule a constrained resource or to cause OOMs on restart.  Feature flagging the behavior would make it easier to validate any etcd problems as well.

**Comment by smarterclayton** [comment]
If TTL is the culprit I think that this will push this feature out of 1.0 as well - switching to create a graceful expiration controller is too large a change.

**Comment by smarterclayton** [comment]
Although...

**Pull request merged**
