### PR TITLE
Remove deprecated API definitions to make the spec valid

### LINKED ISSUE #54815: Kubernetes 1.8 OpenApi Spec is invalid
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I pass the 1.8 OpenAPI spec to Swagger's validator, I get an error that looks like:

```
# swagger-codegen validate -i openapi_kubernetes_1.8.json
attribute definitions.io.k8s.kubernetes.pkg.api.v1.PersistentVolume.description is unexpected
...
Exception in thread "main" io.swagger.codegen.cmd.ValidateException
	at io.swagger.codegen.cmd.Validate.run(Validate.java:34)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

The full output is at https://gist.github.com/ceridwen/a0007517d5410bdca0ae1653f136646f.

**What you expected to happen**:

I expected validation to pass.  Validation on the 1.6 and 1.7 specs passes.

**How to reproduce it (as minimally and precisely as possible)**:

Download https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.8/api/openapi-spec/swagger.json and run swagger-codegen version 2.2.3  on it.

**Environment**:
- Kubernetes version (use `kubectl version`): I noticed this issue on minikube v0.23.
- OS (e.g. from /etc/os-release): Mac OS X 10.12.6
- Kernel (e.g. `uname -a`): Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
- Others: swagger-codegen 2.2.3.

### PR DESCRIPTION
**Pull request by ceridwen**
**What this PR does / why we need it**:
This removes the deprecated API definitions that makes the current OpenAPI spec not conform to the standard.

**Which issue(s) this PR fixes** 
Fixes  #54815

**Special notes for your reviewer**:
As request, this is the same pull request as #55832 only against master.

**Release note**:

```release-note
Remove deprecated API definitions to make the spec valid
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/ok-to-test
/sig api-machinery

/unassign
I know nothing about OpenAPI spec

**Comment by caesarxuchao** [comment]
This file is generated, so please don't change the file directly.

**Comment by caesarxuchao** [comment]
Also it seems there is no consensus in #54815 yet.

**Comment by yliaog** [comment]
please either fix the source, or fix the generator.

**Comment by ceridwen** [comment]
Where is this file generated?  Is there documentation that explains?

**Comment by yliaog** [comment]
http://blog.kubernetes.io/2016/12/kubernetes-supports-openapi.html

https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md

have some related info.

**Comment by yliaog** [comment]
"The make generated_files will also regenerate the zz_generated.deepcopy.go, zz_generated.defaults.go, and api/openapi-spec/swagger.json."

as mentioned in https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md

**Comment by mbohlool** [comment]
As mentioned by Chao, this file is auto-generated and should not be edited. Also as far as I can tell, #54815  is about extra description fields that are considered invalid in some OpenAPI validators but swagger-codegen is OK with it. And about the deprecated definitions, while they should be valid according to spec, they will be removed in 1.10. We need to keep them for backward compatibility.

**Pull request closed without merging**
