### PR TITLE
[go] Bump images, dependencies and versions to go 1.22

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/hold

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.22

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/3280

/assign @MadhavJivrajani @liggitt @puerco @xmudrii  
cc @kubernetes/release-managers 

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.22
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
```
ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that registry.k8s.io/distroless-iptables: dependents should be at version v0.5.1, but the following files didn't match: test/utils/image/manifest.go 
```

lgtm other than that

**Comment by cpanato** [comment]
> ```
> ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that registry.k8s.io/distroless-iptables: dependents should be at version v0.5.1, but the following files didn't match: test/utils/image/manifest.go 
> ```
> 
> lgtm other than that

fixed

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by puerco — APPROVED** [review]

**Comment by humblec** [comment]
Thanks @cpanato !

**Comment by dims** [comment]
/hold cancel

we have enough approvals!!

**Pull request merged**
