### PR TITLE
Changed code to improve output for files under test/e2e/kubectl

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?
Enhancement

#### What this PR does / why we need it:
For better (more informative) output for developers when test fails. Changed files are under test/e2e/kubectl for this PR.
#### Which issue(s) this PR fixes:

Part of #105678

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by NikhilSharmaWe** [comment]
@pohly PR needs approval.

**Comment by NikhilSharmaWe** [comment]
@pohly PR needs approval.

**Review by dougsland — COMMENTED** [review]
/lgtm

**Comment by aojea** [comment]
/kind cleanup
/assign @pohly @soltysh 
for approval

**Review by pohly — APPROVED** [review]
/approve

**Review by soltysh — APPROVED** [review]
/approve
/priority backlog
/triage accepted

**Pull request merged**
