### PR TITLE
use '_' in nodelabel plugin for unused parameters

### PR DESCRIPTION
**Pull request by july2993**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
use '_' in nodelabel plugin for unused parameters

this help code readability
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by binacs — COMMENTED** [review]
/ok-to-test

**Review by damemi — COMMENTED** [review]
/approve
@july2993 you'll need to add `NONE` to the release-note block

**Pull request merged**
