### PR TITLE
chore(scheduler): refactor import package ordering in scheduler

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- refactor import package ordering for scheduler
#### Which issue(s) this PR fixes:

Fixes # None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by googs1025** [comment]
@sanposhiho 
can you help this? :)

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by sanposhiho** [comment]
@googs1025 Can you check and fix all the other files of SIG-Scheduling area? (cmd/kube-scheduler, pkg/scheduler, test/integration/scheduler, test/integration/scheduler_perf, test/e2e/scheduling)

(You can use any formatting tool that you want.)

**Comment by googs1025** [comment]
> @googs1025 Can you check and fix all the other files of SIG-Scheduling area? (cmd/kube-scheduler, pkg/scheduler, test/integration/scheduler, test/integration/scheduler_perf, test/e2e/scheduling)
> 
> (You can use any formatting tool that you want.)

got this. i will fix this tonight.

**Comment by googs1025** [comment]
> @googs1025 Can you check and fix all the other files of SIG-Scheduling area? (cmd/kube-scheduler, pkg/scheduler, test/integration/scheduler, test/integration/scheduler_perf, test/e2e/scheduling)
> 
> (You can use any formatting tool that you want.)

fixed.

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve
/unhold

**Comment by sanposhiho** [comment]
/assign @x13n @gjtempleton 

just a cleanup

**Comment by googs1025** [comment]
@gjtempleton. /PTAL :) thanks  
friendly ping

**Pull request merged**
