### PR TITLE
[WIP][Draft] Kubectl can do smart things with partial name

### PR DESCRIPTION
**Pull request by shiywang**
Trying to fix issues https://github.com/kubernetes/kubernetes/issues/17144, still have some questions, see my  comment in this issues
it's a simple version change, for now, only a draft, not sure I'm doing the right way, the `kubectl logs` result  now looks like:
```console
[shiywang@dhcp-140-33 amd64]$ ./kubectl logs nginx
No pod named nginx, do you mean? nginx-6w00h, nginx-l6isv, nginx-v7tfx
[shiywang@dhcp-140-33 amd64]$ ./kubectl logs ruby
[1] Puma starting in cluster mode...
[1] * Version 3.4.0 (ruby 2.2.2-p95), codename: Owl Bowl Brawl
[1] * Min threads: 0, max threads: 16
[1] * Environment: production
[1] * Process workers: 2
[1] * Phased restart available
[1] * Listening on tcp://0.0.0.0:8080
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 19) booted, phase: 0
[1] - Worker 1 (pid: 23) booted, phase: 0
[shiywang@dhcp-140-33 amd64]$ ./kubectl logs pod-no-exist
Error from server (NotFound): pods "pod-no-exist" not found
[shiywang@dhcp-140-33 amd64]$ ./kubectl logs pod-no-exist -lapp=nginx
error: only a selector (-l) or a POD name is allowed
See 'kubectl logs -h' for help and examples.
[shiywang@dhcp-140-33 amd64]$ ./kubectl get pods
NAME              READY     STATUS             RESTARTS   AGE
nginx-6w00h       0/1       CrashLoopBackOff   295        1d
nginx-l6isv       0/1       CrashLoopBackOff   295        1d
nginx-v7tfx       0/1       CrashLoopBackOff   295        1d
ruby-ex-1-kz3gu   1/1       Running            0          1d
[shiywang@dhcp-140-33 amd64]$ 
```

@pwittrock @fabianofranz PTAL

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by resouer** [comment]
Did not look it deeply, but since you changed `LogsOptions` and it caused `TestLog` panic, you should check if you happened to forget filling those new added fields in all cases.

**Comment by shiywang** [comment]
@resouer hi, thanks for this, but I checkout an new branch base on master, and only change [one line](https://github.com/shiywang/kubernetes/commit/44839a65f1d8a5ae99d9c11f7ee8e4e9b1b12f49), still got panic, I guess it maybe relate to misuse of function `ResourceTypeOrNameArgs`, will countinue dig into this construction process of REST requests

**Comment by shiywang** [comment]
@AdoHe @fabianofranz @pwittrock really wired, still can not figure out what happened, could you guys help to take a look on this ? Many thanks !!!

**Comment by AdoHe** [comment]
@shiywang could you paste the panic info here? Thanks

**Comment by shiywang** [comment]
@AdoHe 
> shiywang@dhcp-140-33 kubernetes (kubectl_do_smart_things) $   make test WHAT=./pkg/kubectl/cmd
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1alpha1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1alpha1,storage.k8s.io/v1beta1,federation/v1beta1
+++ [0117 22:17:48] Running tests without code coverage
pod "pod0" deleted
pod "pod1" deleted
pod "pod2" deleted
pod "pod3" deleted
pod "pod4" deleted
pod "pod5" deleted
pod "pod6" deleted
pod "pod7" deleted
--- FAIL: TestLog (0.00s)
	logs_test.go:64: v1 - pod log: unexpected request: &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"localhost", Path:"/namespaces/test/pods", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
		&http.Request{Method:"GET", URL:(*url.URL)(0xc42035ad00), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}}, Body:io.ReadCloser(nil), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Host:"localhost", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc975aa]

goroutine 156 [running]:
panic(0x1506fa0, 0xc4200121c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4206ddb00)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x1506fa0, 0xc4200121c0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
net/http.(*Client).doFollowingRedirects(0xc4201f1c50, 0xc42010c960, 0x17c7118, 0x3, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:538 +0x62a
net/http.(*Client).Do(0xc4201f1c50, 0xc42010c960, 0xc42066b270, 0x7ed7eb, 0x0)
	/usr/local/go/src/net/http/client.go:184 +0x1ea
k8s.io/kubernetes/pkg/client/restclient/fake.(*RESTClient).Do(0xc42053cbe0, 0xc42010c960, 0x0, 0x20, 0x0)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/restclient/fake/fake.go:124 +0x64
k8s.io/kubernetes/pkg/client/restclient.(*Request).request(0xc42067a4e0, 0xc42074b3a8, 0x0, 0x0)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/restclient/request.go:806 +0x264
k8s.io/kubernetes/pkg/client/restclient.(*Request).Do(0xc42067a4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/restclient/request.go:880 +0xb7
k8s.io/kubernetes/pkg/kubectl/resource.(*Helper).List(0xc420028b80, 0x16b1495, 0x4, 0x16b024a, 0x2, 0x219a480, 0xc420677380, 0x0, 0x14f16e0, 0xc42066b640, ...)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/helper.go:73 +0xf3
k8s.io/kubernetes/pkg/kubectl/resource.(*Selector).Visit(0xc420028b00, 0xc4201c05a0, 0x0, 0x410f6e)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/selector.go:50 +0x128
k8s.io/kubernetes/pkg/kubectl/resource.VisitorList.Visit(0xc4204ccec0, 0x1, 0x1, 0xc4201c05a0, 0x1, 0xc4201c05a0)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:186 +0x5b
k8s.io/kubernetes/pkg/kubectl/resource.(*VisitorList).Visit(0xc4206773c0, 0xc4201c05a0, 0x0, 0x17bd005)
	<autogenerated>:123 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2189d80, 0xc4206773c0, 0xc420028ac0, 0xc420028b40, 0xc4204cce01, 0xc420028b40)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:417 +0x94
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc4206773e0, 0xc420028b40, 0x10, 0x10)
	<autogenerated>:138 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2189d40, 0xc4206773e0, 0xc420677420, 0x3, 0x4, 0xc4204ccee0, 0x2189c01, 0xc4204ccee0)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:325 +0xd6
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc4201c0570, 0xc4204ccee0, 0xc420677420, 0xc420677400)
	<autogenerated>:158 +0x78
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Infos(0xc4202cb730, 0xc4202cb730, 0xc42066baf8, 0x1, 0x1, 0xc42066bbe0)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:110 +0xfd
k8s.io/kubernetes/pkg/kubectl/cmd.(*LogsOptions).Complete(0xc420257a20, 0x21a4460, 0xc420677020, 0x21815c0, 0xc4202cb570, 0xc42042b680, 0xc4204ccde0, 0x1, 0x1, 0x10, ...)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go:200 +0x7a8
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdLogs.func2(0xc42042b680, 0xc4204ccde0, 0x1, 0x1)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go:98 +0xaf
k8s.io/kubernetes/pkg/kubectl/cmd.TestLog(0xc4206ddb00)
	/home/shiywang/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/logs_test.go:75 +0x70b
testing.tRunner(0xc4206ddb00, 0x17c4aa8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd	3.250s
Makefile:160: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by pwittrock** [comment]
@jbeda had some comments about this, and thinks there may be better ways to address the same problem.

**Comment by shiywang** [comment]
@pwittrock @jbeda just watch the meeting record, totally agree that we should improve the experience for both user and contributors(especially for a newbie like me). I'll keep learning code and the mechanism of cli part, keep contributing this part in my spare time. @jbeda @pwittrock @fabianofranz @AdoHe @resouer  thank you all guys !!!

**Comment by shiywang** [comment]
I think I may understand the reason build failed, thank for you all, For now, the only thing we're not sure is using glob or prefix or sth else?

**Comment by shiywang** [comment]
hi, I just fix this testing failed issue, and now it should works well, about the glob thing, @jbeda thinks it's a bad idea, so how about still using prefix like `describe` did. if it's ok, I'll continue working on change other command to support prefix match.

**Pull request closed without merging**
