### PR TITLE
[WIP] Experiments with containerd/runc DO NOT MERGE -- Another containerd commit (b26e6abe)

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/hold

### CODE REVIEW

**Comment by BenTheElder** [comment]
comparing this version against https://github.com/kubernetes/kubernetes/pull/91746

**Comment by dims** [comment]
/retitle [WIP] Experiments with containerd/runc DO NOT MERGE -- Another containerd commit (gb26e6abe)

**Comment by BenTheElder** [comment]
`[sig-cli] Kubectl client Simple pod should support inline execution and attach ` is still flaky @aojea, maybe the 5s sleep is too short?

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91786/pull-kubernetes-e2e-gce-ubuntu-containerd/1268630319737606145/
[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container 
/retest

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91786/pull-kubernetes-e2e-gce-ubuntu-containerd/1268654227417206785/
[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container 
/retest

**Comment by dims** [comment]
```[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container ```

**Comment by dims** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91786/pull-kubernetes-e2e-gce-ubuntu-containerd/1268954707661950978/

```
[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container expand_more
```

**Pull request closed without merging**
