### PR TITLE
Moves left networking e2e tests to test/e2e/network

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
#48784 forgot to move some networking e2e tests. This PR moves them.

It also move the networking tests from within `test/e2e/common/networking.go` to  `test/e2e/network/networking.go`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Associated PR #48784
Umbrella issue #49161

**Special notes for your reviewer**:
/assign @wojtek-t @bowei 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cmluciano** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
Tests in `test/e2e/common` are shared by the node and the cluster e2e suites. Migrating the tests off will reduce the test coverage for networking in the node e2e suite.
I'd suggest not doing this unless the reduced test coverage is intended. /cc @freehan

**Comment by bowei** [comment]
@xiangpengzhao I would remove the common stuff from this PR (as per @yujuhong's comment above)

**Comment by xiangpengzhao** [comment]
@yujuhong I didn't notice that. Thanks for pointing it out!

Reverted. And renamed `no-snat.go` to `no_snat.go` because it didn't pass `hack/verify-flags-underscore.py`

PTAL @bowei @yujuhong

**Comment by xiangpengzhao** [comment]
Seems like the PR can't retest unless it has an `/ok-to-test` instead of `@k8s-bot ok to test` :)

**Comment by xiangpengzhao** [comment]
Thanks @cmluciano !

**Review by bowei — COMMENTED** [review]
/lgtm

**Comment by cmluciano** [comment]
/assign @gmarek 

for hack/ approval

**Pull request merged**
