### PR TITLE
Update Azure API versions in go imports

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
/kind feature

**What this PR does / why we need it**:
Fast-follow to https://github.com/kubernetes/kubernetes/pull/79574, updating the Azure API versions in go imports

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
@feiskyer @andyzhangx @khenidak -- tests pass now, so this is ready for review/approval.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
For top-level review and `/approve`:
/assign @brendandburns @liggitt @thockin

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by thockin** [comment]
Conflict.

**Comment by thockin** [comment]
Thanks!

/approve

**Review by andyzhangx — APPROVED** [review]
on Azure part:
/lgtm
/approve

**Pull request merged**
