### PR TITLE
Remove failure policy from initializer configuration

### PR DESCRIPTION
**Pull request by caesarxuchao**
A few reasons:
* Implementing fail open initializers increases complexity a lot
* We haven't seen strong use cases
* We can always add it back

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

/approve

Will wait for one more voice.

**Review by cheftako — APPROVED** [review]
/lgtm

**Comment by caesarxuchao** [comment]
Was fixing a compile error. Adding back the lgmt.

**Pull request merged**
