### PR TITLE
Revert sigs.k8s.io/structured-merge-diff/v4 to v4.1.2

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Reverts structured-merge-diff to 4.1.2 to avoid incomplete merge order changes in 1.23

xref https://github.com/kubernetes/kubernetes/issues/104641#issuecomment-976947921

/cc @apelisse @jiahuif 

```release-note
Fix 1.23 regression in kube-apiserver to make Server Side Apply merge order match v1.22 behavior until http://issue.k8s.io/104641 is resolved.
```

### CODE REVIEW

**Comment by liggitt** [comment]
/milestone v1.23
/priority critical-urgent

milestoning to avoid shipping a partial API change in 1.23

**Comment by liggitt** [comment]
/retest
openapi failure fixed in https://github.com/kubernetes/kubernetes/pull/106657

**Comment by apelisse** [comment]
/lgtm
/approve

Totally the right call, let's take our time and fix it the right way.

**Comment by justaugustus** [comment]
/hold cancel
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1637779136309300?thread_ts=1637777541.303800&cid=CJH2GBF7Y

**Comment by liggitt** [comment]
```
I1124 20:32:11.075] [Fail] [sig-network] Proxy version v1 [It] A set of valid responses are returned for both pod and service ProxyWithPath [Conformance] 
I1124 20:32:11.075] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:314
```

sigh

**Comment by pacoxu** [comment]
Why this is tagged as `1.24` by ci-robot？ 🤔

**Pull request merged**
