### PR TITLE
fix msg in /test/e2e/apps/daemon_set.go

### PR DESCRIPTION
**Pull request by dengyufeng2206**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
"daemonset", not "deamonset"
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aimuz** [comment]
Thank you for your contribution

**Comment by dengyufeng2206** [comment]
> 

thanks for your review :)

**Pull request merged**
