### PR TITLE
e2e.go --isup should also check the version

### LINKED ISSUE #18667: e2e.go --isup should test version skew
Right now, running `e2e.go --isup` may return `0`, but a `--test` run following will complain that the cluster is not up due to version skew.

These execution paths should be consistent, and `--isup` should test version skew.

cc @krousey

### PR DESCRIPTION
**Pull request by asalkeld**
Just move the setenv up to include --isup

fixes #18667

### CODE REVIEW

**Comment by lavalamp** [comment]
Not sure this fixes the problem, the problem might be that the second invocation builds and therefore introduces the version skew?

**Comment by asalkeld** [comment]
@lavalamp thanks, I'll check that out and get back.

**Comment by asalkeld** [comment]
@lavalamp some debug/proof for you:

With a clean tree I did a ./hack/local-up-cluster.sh
```
go run hack/e2e.go -v --check_node_count=false --isup
2016/07/19 10:45:26 e2e.go:212: Running: get status
Local doesn't need special preparations for e2e tests
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.200+5c3eea15eb2053-dirty", GitCommit:"5c3eea15eb20535a9afe69908cce572047462e22", GitTreeState:"dirty", BuildDate:"2016-07-19T00:38:07Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.200+5c3eea15eb2053-dirty", GitCommit:"5c3eea15eb20535a9afe69908cce572047462e22", GitTreeState:"dirty", BuildDate:"2016-07-19T00:38:07Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
2016/07/19 10:45:26 e2e.go:214: Step 'get status' finished in 37.704573ms
2016/07/19 10:45:26 e2e.go:84: Cluster is UP
```
As expected all good, client and server at the same commit.

Then I made a commit (debug and a new line in a go file), note the local cluster still up.
```
git top
commit 9759778ecbc9d01c5c47542b25b35f9054aeb602
Author: Angus Salkeld <asalkeld@mirantis.com>
Date:   Tue Jul 19 10:43:45 2016 +1000

    *random

 hack/lib/golang.sh           | 1 +
 pkg/api/validation/events.go | 1 +
 2 files changed, 2 insertions(+)
```
Now if I try isup or test, nothing changes as only --build rebuilds the code. At this
point I did a manual "make all".

check isup
```
go run hack/e2e.go -v --check_node_count=false --isup
2016/07/19 10:55:57 e2e.go:211: Running: get status
Local doesn't need special preparations for e2e tests
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.201+9759778ecbc9d0-dirty", GitCommit:"9759778ecbc9d01c5c47542b25b35f9054aeb602", GitTreeState:"dirty", BuildDate:"2016-07-19T00:46:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.200+5c3eea15eb2053-dirty", GitCommit:"5c3eea15eb20535a9afe69908cce572047462e22", GitTreeState:"dirty", BuildDate:"2016-07-19T00:38:07Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
2016/07/19 10:55:58 e2e.go:213: Step 'get status' finished in 37.010028ms
2016/07/19 10:55:58 e2e.go:82: Cluster is UP
```
Note: the client and server commits are *different*, but is says "cluster is up"
Now let's try, --test 

```
go run hack/e2e.go -v --check_node_count=false --test --test_args="-host=http://127.0.0.1:8080 -ginkgo.dryRun=true -ginkgo.focus=Deployment"
2016/07/19 10:54:58 e2e.go:212: Running: get status
Local doesn't need special preparations for e2e tests
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.201+9759778ecbc9d0-dirty", GitCommit:"9759778ecbc9d01c5c47542b25b35f9054aeb602", GitTreeState:"dirty", BuildDate:"2016-07-19T00:46:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
error: server version (&version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.200+5c3eea15eb2053-dirty", GitCommit:"5c3eea15eb20535a9afe69908cce572047462e22", GitTreeState:"dirty", BuildDate:"2016-07-19T00:38:07Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}) differs from client version (version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.201+9759778ecbc9d0-dirty", GitCommit:"9759778ecbc9d01c5c47542b25b35f9054aeb602", GitTreeState:"dirty", BuildDate:"2016-07-19T00:46:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"})!
2016/07/19 10:54:58 e2e.go:218: Error running get status: exit status 1
2016/07/19 10:54:58 e2e.go:214: Step 'get status' finished in 35.939248ms
2016/07/19 10:54:58 e2e.go:189: Testing requested, but e2e cluster not up!
```

Now, with my patch:
```
go run hack/e2e.go -v --check_node_count=false --isup
2016/07/19 11:00:17 e2e.go:212: Running: get status
Local doesn't need special preparations for e2e tests
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.201+9759778ecbc9d0-dirty", GitCommit:"9759778ecbc9d01c5c47542b25b35f9054aeb602", GitTreeState:"dirty", BuildDate:"2016-07-19T00:46:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
error: server version (&version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.200+5c3eea15eb2053-dirty", GitCommit:"5c3eea15eb20535a9afe69908cce572047462e22", GitTreeState:"dirty", BuildDate:"2016-07-19T00:38:07Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}) differs from client version (version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.201+9759778ecbc9d0-dirty", GitCommit:"9759778ecbc9d01c5c47542b25b35f9054aeb602", GitTreeState:"dirty", BuildDate:"2016-07-19T00:46:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"})!
2016/07/19 11:00:17 e2e.go:218: Error running get status: exit status 1
2016/07/19 11:00:17 e2e.go:214: Step 'get status' finished in 35.398567ms
2016/07/19 11:00:17 e2e.go:86: Cluster is DOWN
exit status 1
```

**Comment by spxtr** [comment]
This seems fine to me, but it's very confusing that it says the cluster is down when there's a version skew.

**Comment by asalkeld** [comment]
@spxtr somewhat agree, but maybe that can be fixed in a separate bug/PR?

**Comment by spxtr** [comment]
Sounds good.

**Pull request merged**
