### PR TITLE
Move kubectl cp back to k/k

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We need to temporarily move `kubectl cp` back to k/k repository. 

**Special notes for your reviewer**:
/assign @liggitt 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
> bazel failure is legitimate, allowed imports need update

Yeah, I'm on it.

**Review by tnozicka — APPROVED** [review]
@liggitt's comment is addressed
/lgtm

**Pull request merged**
