### PR TITLE
fully verify client-gen in verification tests 

### PR DESCRIPTION
**Pull request by mikedanese**
Is this broken for me or everyone?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32720)

### CODE REVIEW

**Comment by mikedanese** [comment]
@caesarxuchao looks like this is not verified.

**Comment by mikedanese** [comment]
@k8s-bot e2e  test this please, issue: #32548

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue: #32548

**Comment by caesarxuchao** [comment]
Thanks. LGTM!

**Pull request merged**
