### PR TITLE
[FEATURE BRANCH] 20190814 Rebase feature rate limiting w/ master

### PR DESCRIPTION
**Pull request by yue9944882**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by warmchang** [comment]
What does this feature-rate-limiting branch do? It contains too many commits. 🤷‍♂

**Comment by neolit123** [comment]
/remove-area kubeadm
(removing from watched PRs)

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by yliaog** [comment]
is there any manual change? are they any conflict? not sure how to review these many commits / files, guess i can focus on the manual changes only.

**Comment by MikeSpreitzer** [comment]
Why is the CI robot complaining about CLA (https://github.com/kubernetes/kubernetes/pull/81409#issuecomment-521154531) ?  @yue9944882 has made many successful PRs.

**Comment by yue9944882** [comment]
idk probably somebody quits CLA after the commits' in

**Comment by yue9944882** [comment]
it's the test-infra failing yesterday.. closing this

**Pull request closed without merging**
