### PR TITLE
Deployment controller clean old rs by revision

### LINKED ISSUE #82570: cleanupDeployment should sort ReplicaSet with revision rather than createTimeStamp
**What happened**:
when deployment controller cleans up old ReplicaSet, it sorts all old ReplicaSets by createTimeStamp and delete the oldest one, which may cause Deployment roll back to a wrong version.

```
        sort.Sort(controller.ReplicaSetsByCreationTimestamp(cleanableRSes))
	glog.V(4).Infof("Looking to cleanup old replica sets for deployment %q", deployment.Name)

	for i := int32(0); i < diff; i++ {
		rs := cleanableRSes[i]
		// Avoid delete replica set with non-zero replica counts
		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
			continue
		}
		glog.V(4).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
		if err := dc.client.ExtensionsV1beta1().ReplicaSets(rs.Namespace).Delete(rs.Name, nil); err != nil && !errors.IsNotFound(err) {
			// Return error instead of aggregating and continuing DELETEs on the theory
			// that we may be overloading the api server.
			return err
		}
	}
```

**How to reproduce it (as minimally and precisely as possible)**:
Suppose we set the revisionHistoryLimit of a Deployment to 3, and currently we have 3 Replicas: r1, r2, r3 (the createTimeStamp and Revision both are r3 > r2 > r1); if we upgrade and roll back 3 times continuously, there will be an expected case:

upgrade: 
&nbsp; ReplicaSet will be: r4, r3, r2 
&nbsp; createTimeStamp: r4 > r3 > r2
&nbsp; reversion: r4 > r3 > r2
rollback:  should rollback to v3
&nbsp; ReplicaSet will be: r4, r3, r2 
&nbsp; createTimeStamp: r4 > r3 > r2
&nbsp; reversion: r3 > r4 > r2

upgrade: 
&nbsp; ReplicaSet will be: r5, r4, r3 
&nbsp; createTimeStamp: r5 > r4 > r3 
&nbsp; reversion: r5 > r3 > r4
rollback: should rollback to v3
&nbsp; ReplicaSet will be: r4, r3, r2 
&nbsp; createTimeStamp: r5 > r4 > r3 
&nbsp; reversion: r3 > r5 > r4

upgrade: 
&nbsp; ReplicaSet will be: r6, r5, r4 
&nbsp; createTimeStamp: r6 > r5 > r4 
&nbsp; reversion: r6 > r5 > r4
rollback: should rollback to r3, but instead, we rollbacked to r5, and this may cause error.

**What you expected to happen**:
when deployment controller cleans up old ReplicaSet, it should sort old ReplicaSets by Revision

### PR DESCRIPTION
**Pull request by ricky1993**
Change-Id: I6ae86829fdbe7846c9ce3bb4daa66a222eb3611d

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #82570

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/approve

The change looks good to me. Just need another reviewer to lgtm it.

**Comment by ricky1993** [comment]
ping @smarterclayton ~ PTAL

**Comment by smarterclayton** [comment]
Please add a unit test for this scenario

**Pull request closed without merging**
