### PR TITLE
Measure event_handling and QHints duration metrics in scheduler_perf

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

It enables collecting two metrics in scheduler_perf benchmark: `scheduler_queueing_hint_execution_duration_seconds` and `scheduler_event_handling_duration_seconds`. Next PRs will introduce new test cases that will focus on utilizing these metrics. 

#### Which issue(s) this PR fixes:

Part of #124566

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
/approve
/hold
(just because it looks like you are trying to rerun the tests a few times? Feel free to unhold anytime)

**Pull request merged**
