### PR TITLE
Updating kubectl to use POST instead of GET for port-forward and exec

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/10366

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @smarterclayton @bgrant0607 @lavalamp 

@smarterclayton You said that we need to test this with HAProxy and an F5 proxy in front of our exec/portforward endpoints.
Can you please point me to how can I test it or can you test it?

Verified that e2e tests basic exec and port-forward: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/kubectl.go#L155

**Comment by smarterclayton** [comment]
I believe @ncdc did some quick testing.

On Jul 1, 2015, at 11:03 PM, Nikhil Jindal <notifications@github.com> wrote:

cc @smarterclayton <https://github.com/smarterclayton> @bgrant0607
<https://github.com/bgrant0607> @lavalamp <https://github.com/lavalamp>

@smarterclayton <https://github.com/smarterclayton> You said that we need
to test this with HAProxy and an F5 proxy in front of our exec/portforward
endpoints.
Can you please point me to how can I test it or can you test it?

Verified that e2e tests basic exec and port-forward:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/kubectl.go#L155

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/pull/10654#issuecomment-117888841>
.

**Comment by zmerlynn** [comment]
@jlowdermilk loves `exec`.

**Comment by ncdc** [comment]
I tested adding support for exec and port forwarding to use http_proxy/https_proxy env vars to be able to use a proxy to reach the master, as they currently don't. That worked against squid (I didn't test proxy auth though). I didn't test this with a reverse proxy in front of the master.

**Comment by jlowdermilk** [comment]
LGTM. Don't know about the ha/f5 proxy, but jenkins green is good enough for me.

**Comment by smarterclayton** [comment]
This is fine since we continue to support GET.  LGTM

On Thu, Jul 2, 2015 at 12:53 PM, Jeff Lowdermilk <notifications@github.com>
wrote:

> LGTM. Don't know about the ha/f5 proxy, but jenkins green is good enough
> for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/10654#issuecomment-118091548>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by nikhiljindal** [comment]
@bgrant0607 for the final ok-to-merge

**Comment by nikhiljindal** [comment]
Maybe @zmerlynn or @thockin can give me a second LGTM?

**Comment by lavalamp** [comment]
Did you manually test? I didn't think there was an e2e test that covered this stuff. (If there is, then consider this an LGTM)

**Comment by nikhiljindal** [comment]
Yes there is an e2e test: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/kubectl.go#L155

I wasnt able to test it locally, since it required some additional softwares to be installed.

**Comment by bprashanth** [comment]
@lavalamp please apply ok-to-merge if you're fine with the test coverage

**Comment by thockin** [comment]
LGTM

Does the serve accept either POST or GET?  Or is it currently broken?

**Comment by nikhiljindal** [comment]
Server accepts both POST and GET for now: https://github.com/GoogleCloudPlatform/kubernetes/pull/10509
Eventually, we will stop supporting GET: https://github.com/GoogleCloudPlatform/kubernetes/issues/10366

**Comment by bgrant0607** [comment]
LGTM
ok to merge

**Pull request merged**
