### PR TITLE
Change rootCertPool to use SystemCertPool

### PR DESCRIPTION
**Pull request by Oats87**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR changes the CertPool used for `client-go/transport` to use the `SystemCertPool` rather than starting with an empty CertPool, as Golang now provides a method for retrieving the SystemCertPool.

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/client-go/issues/1002

#### Does this PR introduce a user-facing change?

```release-note
Utilize SystemCertPool properly when processing custom CA data in client-go
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

this breaks compatibility with the documented behavior of the configuration. If we want an "also include system roots" behavior, that needs to be opted into. Is contacting a server using a mix of explicit roots and system roots a typical use case?

**Comment by enj** [comment]
> Is contacting a server using a mix of explicit roots and system roots a typical use case?

Note that this is impossible on platforms such as Windows that do not have a concept of a system roots pool (you have to ask the OS itself to do the TLS verification).

---

This is an invalid change IMO as we should not trust roots outside of the provided bundle if it is given.

**Comment by Oats87** [comment]
> > Is contacting a server using a mix of explicit roots and system roots a typical use case?
> 
> Note that this is impossible on platforms such as Windows that do not have a concept of a system roots pool (you have to ask the OS itself to do the TLS verification).
> 
> This is an invalid change IMO as we should not trust roots outside of the provided bundle if it is given.

One of the (albeit rare) use cases that I've run into that would benefit from this behavior is a split-horizon DNS setup where an API server cluster is exposed internally and externally using TLS certificates signed by differing CAs, but wanting to be able to use only one kube config context. While it's possible to tweak the root bundle provided to include all CAs, in certain cases, one of the load balancers exposing the API servers may be automatically gathering signed TLS certificates from a public authority (i.e. using cert-manager) which makes things slightly more complicated for pre-population of the bundle.

That being said, upon giving retrospective thoughts to this PR, I agree that if this behavior were to be changed it should likely be "opt-in" which would be a whole other rabbit hole to achieve. I am closing this PR as I do not believe this behavior should be changed in this manner, at least as drastically as proposed.

**Pull request closed without merging**
