### PR TITLE
Add dims to conformance-behavior-approvers

### PR DESCRIPTION
**Pull request by dims**
volunteer to help with updates to conformance.yaml 

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Hi @dims, I am open to this but not sure if you have been doing conformance reviews? There are a bunch of special rules/things we look for as documented in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md - have you done some of those reviews?

**Comment by spiffxp** [comment]
/hold
I would like to see some data on your participation in conformance-related PR reviews (both test authorship and promotion), and participation in the conformance meeting.

I get that there remains an /approve bottleneck, and you are always awesome at helping out to remove bottlenecks, but we want to be very careful about precedents these /approves set.

I am very open to you acting as a pre-approver to help accelerate things, aka give it an honest look and then assign / ping me directly for approve.  This is generally how things worked for me when it was just clayton and brian

**Comment by dims** [comment]
@spiffxp works! thanks.

**Comment by dims** [comment]
/close

will reopen with enough data :)

**Pull request closed without merging**
