### PR TITLE
Fix the network policy tests.

### PR DESCRIPTION
**Pull request by lzang**
This is a cherrypick of the following commit
https://github.com/kubernetes/kubernetes/pull/74290/commits

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by bowei** [comment]
/retest

looks like godeps failed

**Comment by lzang** [comment]
/assign @tpepper
for 1.13 patch release

**Comment by tpepper** [comment]
following the original PR...
/release-note-none

**Comment by lzang** [comment]
The latest several tests failed at dependency update timeout. 

I0319 02:27:14.920] +++ [0319 02:27:14] Restoring kubernetes godeps
I0319 02:27:14.984] +++ [0319 02:27:14] Using /go/src/k8s.io/kubernetes/_output/dockerized/go/bin/godep
I0319 02:27:14.988] +++ [0319 02:27:14] Downloading dependencies - this might take a while
I0319 02:36:23.662] +++ [0319 02:36:23] Done
I0319 02:36:23.923] +++ [0319 02:36:23] Updating godeps for k8s.io/api
I0319 02:36:34.212] +++ [0319 02:36:34] Updating godeps for k8s.io/apiextensions-apiserver
I0319 02:38:01.653] +++ [0319 02:38:01] Updating godeps for k8s.io/apimachinery
I0319 02:38:05.027] +++ [0319 02:38:05] Updating godeps for k8s.io/apiserver
I0319 02:39:08.920] +++ [0319 02:39:08] Updating godeps for k8s.io/cli-runtime
I0319 02:39:20.348] +++ [0319 02:39:20] Updating godeps for k8s.io/client-go
I0319 02:39:43.691] +++ [0319 02:39:43] Updating godeps for k8s.io/cloud-provider
I0319 02:39:59.075] +++ [0319 02:39:59] Updating godeps for k8s.io/cluster-bootstrap
I0319 02:40:01.101] +++ [0319 02:40:01] Updating godeps for k8s.io/code-generator
I0319 02:40:02.881] +++ [0319 02:40:02] Updating godeps for k8s.io/csi-api
I0319 02:40:10.509] +++ [0319 02:40:10] Updating godeps for k8s.io/kube-aggregator
I0319 02:40:48.830] +++ [0319 02:40:48] Updating godeps for k8s.io/kube-controller-manager
I0319 02:40:50.780] +++ [0319 02:40:50] Updating godeps for k8s.io/kube-proxy
I0319 02:40:52.424] +++ [0319 02:40:52] Updating godeps for k8s.io/kube-scheduler
I0319 02:40:54.367] +++ [0319 02:40:54] Updating godeps for k8s.io/kubelet
I0319 02:40:56.237] +++ [0319 02:40:56] Updating godeps for k8s.io/metrics
I0319 02:41:03.944] +++ [0319 02:41:03] Updating godeps for k8s.io/sample-apiserver
I0319 02:41:39.329] +++ [0319 02:41:39] Updating godeps for k8s.io/sample-cli-plugin
I0319 02:41:46.692] +++ [0319 02:41:46] Updating godeps for k8s.io/sample-controller
I0319 02:41:54.314] Terminate 670 on timeout
E0319 02:41:54.416] Build timed out
E0319 02:41:54.416] Command failed
I0319 02:41:54.416] process 670 exited with code -15 after 74.0m
E0319 02:41:54.417] FAIL: pull-kubernetes-verify

**Comment by tpepper** [comment]
> The latest several tests failed at dependency update timeout.

Yes.  They're failing in different places, due to timeout.  All I can guess is network congestion?  The periodic tests on master are flaking about 30% of the time lately, though are on a relatively green stretch just at the moment.

/shrug

**Pull request merged**
