### PR TITLE
Update aws-sdk-go dependency to v1.28.2

### PR DESCRIPTION
**Pull request by SaranBalaji90**
**What type of PR is this?**
/kind bug
/kind feature

**What this PR does / why we need it:**
Updating aws go sdk dependency to address following two issues:

1) Kubelet retrieves ECR credentials through instance metadata. If users wants Kubelet to use different role similar to capabilities that controller manager has (kubernetes/kubernetes@3b99e1b) then we need similar fix for [aws_credentials.go]() as well. But since credential-provider package doesn't have access to cloud provider config file, this might be hacky fix to export profile names through environment variable. Another possible solution is updating aws-sdk-go version which supports credential source and chaining credentials. This change also helps further restrict the EC2 instance role permissions.

2) Current aws-go-sdk doesn't have support for STS regional endpoints. More details on why STS regional endpoints is recommended is documented here - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html. With this change it's easier to enable regional sts endpoints for ECR image pull.

**How is this PR generated?**
PR is generated by running the following two commands:

./hack/pin-dependency.sh github.com/aws/aws-sdk-go v1.28.2
./hack/update-vendor.sh

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt @smarterclayton 

Jordan, Clayton,
Dependency update needs root approval. Does not touch any other dependency other than `aws-sdk-go`. PTAL

**Comment by SaranBalaji90** [comment]
Looks like e2e test runs doesn't cover AWS related tests. I will update here, once I execute aws related tests.

**Comment by liggitt** [comment]
> Looks like e2e test runs doesn't cover AWS related tests. I will update here, once I execute aws related tests.

can unhold once aws-related tests are green (link to the results, if possible)

**Comment by SaranBalaji90** [comment]
> > Looks like e2e test runs doesn't cover AWS related tests. I will update here, once I execute aws related tests.
> 
> can unhold once aws-related tests are green (link to the results, if possible)

aws related tests passed - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87253/pull-kubernetes-e2e-kops-aws/1218368884587892736/

Will do manual testing for NLB.

**Comment by dims** [comment]
@liggitt looks like the AWS tests passed.

**Pull request merged**
