### PR TITLE
Automated cherry pick of #30940

### PR DESCRIPTION
**Pull request by madhusudancs**
Cherry pick of #30940 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31483)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
lgtm, thanks
Added the 1.3 milestone.

**Comment by madhusudancs** [comment]
@k8s-bot test this please issue: #IGNORE

**Comment by madhusudancs** [comment]
@k8s-bot unit test this

**Comment by madhusudancs** [comment]
k8s-bot smoke test this issue: #IGNORE

**Comment by madhusudancs** [comment]
@fabioy @timstclair what does this k8s-cherrypick-bot message mean? Does that require any action on my part?

> Commit found in the "release-1.3" branch appears to be this PR. Removing the "cherrypick-candidate" label. If this is an error find help to get your PR picked.

**Comment by timstclair** [comment]
That just means it was already cherrypicked, so this PR no longer needs to be cherrypicked (hence removal of the label). See your commit [here](https://github.com/kubernetes/kubernetes/commits/release-1.3). No action required.

**Comment by madhusudancs** [comment]
@timstclair Ok cool. Thanks for confirming.

**Pull request merged**
