### PR TITLE
fix Version not found in docker.ENV in fakeDockerClient

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref #20011 

I'm submitting a duct tape fix to the problem so that we could have Kubemark experiment recovered. More design   consideration should be taken so that such inconsistent change wouldn't happen again. Let's raise the discussion in sig scale and/or node.

@davidopp @gmarek @xiang90 @yifan-gu

### CODE REVIEW

**Comment by timothysc** [comment]
lgtm - 
requires @gmarek | @wojtek-t  to apply 

xref: #20020

**Comment by lavalamp** [comment]
LGTM, thanks!

**Comment by davidopp** [comment]
+1 -- thanks a lot for looking into it and fixing it!

**Pull request merged**
