### PR TITLE
[scheduler] When the hostname and nodename of a node do not match, ensure that pods carrying PVs with nodeAffinity are scheduled correctly.

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Currently, the scheduler assumes that the hostname and nodename of a node are the same when evaluating nodeAffinity for local PVs.
https://github.com/kubernetes/kubernetes/blob/6b73cccb07de30c7793370e1d5c3f8766d975d20/pkg/volume/util/util.go#L582
Node name and hostname are distinct and are definitively known to be different in some clusters.
And this will make the pod scheduled to a wrong node or failed scheduling.
#### Which issue(s) this PR fixes:

Part of #125336

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug when the hostname label of a node does not match the node name, pods bound to a PV with nodeAffinity using the hostname may be scheduled to the wrong node or experience scheduling failures.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
@AxeZhan can you add a release note? 
/lgtm
/hold
/assign @msau42 @Huang-Wei

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Please prepare cherry-picks for all supported versions.

**Comment by gnufied** [comment]
@AxeZhan let me know if you are interested in making the necessary cherry picks. This bug is also important for some of our clusters, so we are trying to get backporting fixes expedited if possible.

**Comment by AxeZhan** [comment]
@gnufied Hi gnufied!
Yes, I will prepare the cherry-picks.
Normally, we'll cherry-pick the bugfix to n-3 releases. But it seems this bug is introduced in V1.27, so I will try cherry-pick this pr to release V1.27-V1.31.
May I know what's the version of your cluster? I assume it is included?

**Pull request merged**
