### PR TITLE
test/e2e: fix upgrade test to not run describe cross version

### PR DESCRIPTION
**Pull request by jessfraz**
**What this PR does / why we need it**:
Better fix for #31642 replaces #31987

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32143)

### CODE REVIEW

**Comment by lavalamp** [comment]
This LGTM. I guess the only question is, do we want to test anything cross version? Like, kubectl describe should still work with differing kubectl & server versions. The problem with this test is that it's testing a 1.3 kubectl against 1.4 kubectl output, which is not a property we're interested in testing. (We should only test things like that if people are going to script against them, and people should use templates instead of describe if they want to script.)

**Comment by lavalamp** [comment]
Maybe the best thing to do is run this test if the version matches, and run a super simple check otherwise (like, does the replication controller name turn up in the output somewhere, or does the kubectl process exit success).

**Comment by jfrazelle** [comment]
this makes sense, I will update :) thanks!

**Comment by jfrazelle** [comment]
this fix isnt going to work, because the server version and kubectl version are 1.4 just the tests are built for 1.3, so I think my original fix is actually the better one

**Pull request merged**
