### PR TITLE
Update grpc to 1.0.1-GA

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
The current version is `v1.0.0-183-g231b4cf`, and the latest version is `v1.0.5`. This PR updates the version to `v1.0.1-GA`, which is the latest version I could update to without breaking our vendored packages.

The packages that will break with a newer version (they need to re-generate the go code):
```
# k8s.io/kubernetes/vendor/github.com/coreos/rkt/api/v1alpha
vendor/github.com/coreos/rkt/api/v1alpha/api.pb.go:844: undefined: grpc.SupportPackageIsVersion3
# k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb
vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2082: undefined: grpc.SupportPackageIsVersion3
```

**Comment by yujuhong** [comment]
@Random-Liu, could you try running the benchmark with this PR and see if there is any difference?

**Comment by yujuhong** [comment]
Assigning to myself to decide whether the upgrade is necessary.

**Comment by Random-Liu** [comment]
> @Random-Liu, could you try running the benchmark with this PR and see if there is any difference?

Sure. I'll write a simple script to make the benchmark automated.

**Comment by Random-Liu** [comment]
Since 1.0.0 is only beta. Should we all upgrade to newer grpc version (maybe v1.0.5) in both rkt and etcd? @yifan-gu @xiang90

**Comment by yujuhong** [comment]
> Since 1.0.0 is only beta. Should we all upgrade to newer grpc version (maybe v1.0.5) in both rkt and etcd? @yifan-gu @xiang90

Duh...I tried changing the versions too many times, and didn't even notice that this update doesn't include any real code change.

We'll have to upgrade to a newer version for testing :\

**Comment by feiskyer** [comment]
It seems no actually codes are changed, only a version changed in vendor:

```diff
-	primaryUA = "grpc-go/0.11"
+	primaryUA = "grpc-go/1.0"
``` 

Maybe some dependent vendors missing?

**Comment by yifan-gu** [comment]
Seems rkt and etcd need to bump grpc version, and revender here, right?
cc @hongchaodeng @euank

**Comment by yifan-gu** [comment]
Assigned myself, I will try to bump rkt's grpc version to unblock this.

**Comment by hongchaodeng** [comment]
grpc breaks the protocol after 1.0 , unfortunately.
If we want to bump up grpc as mentioned, we will need to bump etcd to 3.1 branch.

**Comment by yujuhong** [comment]
@yifan-gu there is no difference between grpc 0.11 and 1.0.1, so this PR is moot. We should go through the go-grpc changes and see if any newer version is worth upgrading to.

**Pull request closed without merging**
