### PR TITLE
storage: document csi.storage.k8s.io/ephemeral also for internal type

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This was added to staging/src/k8s.io/api/storage/v1beta1/types.go but
unintentionally left out for the internal type. Both docs should
better match because it is uncertain which one will be looked at by
developers.

The original "iff" for "if and only if" is unnecessary because the
comment about "otherwise false" avoids ambiguity.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig storage

### CODE REVIEW

**Comment by liggitt** [comment]
@msau42 feel free to assign me once the text has been reviewed for API approval

/remove-label api-review

**Comment by msau42** [comment]
The updated text lgtm. It is copying what was already there in the v1beta1 types.go.

/lgtm
/assign @liggitt

**Pull request merged**
