### PR TITLE
Cleanup json serializer

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by liggitt** [comment]
Test failures seem legitimate

**Comment by wojtek-t** [comment]
> Test failures seem legitimate

Yeah - I've seen that. Didn't yet have chance to look.
I'm wondering if this is a bug in library or somewhere else (in principle, I think that change should work).

**Comment by wojtek-t** [comment]
@liggitt - should hopefully be fixed now

**Comment by liggitt** [comment]
looks like serialization is different (trailing newline vs none)

**Comment by ash2k** [comment]
`encoding/json` adds a trailing new line. jsoniter library version we use does not. It has been fixed upstream https://github.com/json-iterator/go/pull/188 though.

**Comment by wojtek-t** [comment]
@ash2k - thanks!

We should probably update the jsoniter library and then proceed with this PR then.

**Comment by ash2k** [comment]
@wojtek-t hm, actually it is already on the latest commit. Was updated 3 days ago - I checked the version a few days earlier and it was old. See https://github.com/kubernetes/kubernetes/pull/63059.

**Comment by ash2k** [comment]
I've actually been working on a refactoring in this area. Just opened https://github.com/kubernetes/kubernetes/pull/63284 to show what I've got so far. I'd be happy to incorporate changes from this PR into mine to avoid any merge conflicts.

**Comment by wojtek-t** [comment]
> I've actually been working on a refactoring in this area. Just opened #63284 to show what I've got so far. I'd be happy to incorporate changes from this PR into mine to avoid any merge conflicts.

Your PR is definitely step in the right direction.
I think that those PRs are (as of now) slightly independent.
Proceeding with this one requires bumping jsoniter godeps (which we should try doing in a separate PR). 
But if you want to incorporate those changes into your PR, I'm fine.

@ash2k - my suggestion regarding your PR is to avoid building gigantic PR. I think that your PR as of now already makes a bunch of sense and we should try merging it as soon as it compiles.

**Comment by wojtek-t** [comment]
/hold

There is problem with incompatibility with this PR.

**Comment by thockin** [comment]
@wojtek-t Do we want to revisit this or let it expire?

**Comment by rickypai** [comment]
@thockin @wojtek-t I'm interested in this work and can take it on if there's bandwidth concern

**Comment by wojtek-t** [comment]
> @wojtek-t Do we want to revisit this or let it expire?

I would like to see this cleanup in, though I'm not sure when I will have time to get back to it.

> @thockin @wojtek-t I'm interested in this work and can take it on if there's bandwidth concern

@rickypai - if you have bandwidth, it would be great. I'm happy to review it when it will be ready.

**Comment by thockin** [comment]
I am unassigning this for now - I don't really know what it does (no PR comment).  @rickypai if you pick this up, feel free to assign to me.

**Comment by smarterclayton** [comment]
In my testing jsoniter.NewEncoder allocates a lot more per call - probably not feasible to use in the mode it's intended.  I looked at pooling and was still seeing high use.  The encoding serializer needs to be reorganized to support pooling across many calls to Encode and that hasn't happened yet.

In particular, watch performance needs to be carefully examined, even a single allocation can cause profile regressions.

**Comment by liggitt** [comment]
closing due to lack of activity, feel free to reopen as needed

**Pull request closed without merging**
