### PR TITLE
[WIP] Image catalog for multiarch images

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for creating docker image catalog for multi architecture, whoever is referring any images can use this catalog which will provide proper image in runtime based on architecture it is running on. Main consume of this catalog will be tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE```

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by ixdy** [comment]
Do you have a proposal to go along with this PR for how it would be used? I'm not sure whether it makes sense to put this in the main kubernetes repo, at least not under `pkg/util`. What makes busybox and ubuntu special?

**Comment by luxas** [comment]
@ixdy What we really like here is manifest lists, but gcr.io doesn't support v2 schema 2...
So we'll have to workaround that until Google fixes it.

Not saying the workaround will look exactly as this, but I'll come up with a proposal soon-ish for how to proceed. But I REALLY would like to solve it the real way with GCR instead.

**Comment by mkumatag** [comment]
@luxas looking forward to see your proposal.

**Comment by mkumatag** [comment]
Will be taken care part of  - https://github.com/kubernetes/kubernetes/pull/49457

**Pull request closed without merging**
