### PR TITLE
[Provider/Vmware] Capture the iterator variable in the goroutine stack for better readability.

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind bug
/kind cleanup

**What this PR does / why we need it**:
Capture the iterator variable in the goroutine stack for readability.

Because a local variable was declared and initialized inside the loop with n := node this code does not actually cause data race. For example, see the output of this snippet: https://play.golang.org/p/mjh0cscyOjJ . However, I think this change improves readability, since maintainers will not need to think as much about scoping rules when looking at function arguments.

Explanation:
When a go loop launches goroutines, it is a common mistake to assume
that the routines can reference the loop value from their specific loop
iteration. Actually, all goroutines share the same reference to the loop
veriable, and they typically all see the last value. To correct this, the loop variable must be captured as a parameter to the anonymous func.

**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
> it is a common mistake to assume
that the routines can reference the loop value from their specific loop
iteration

Yes, it is a common bug, however, in this particular code, there is this code that makes sure it won't happen:

```
n := node
```

Every go routine has its own copy of `n` in its closure.

**Comment by gaurav1086** [comment]
@jsafrane , true. Would it be better to pass this variable in the goroutine rather than create a local copy in the caller's stack to avoid confusion ?

func caller(.....) {
    for _, node := range nodeList.Items {
        **// n := node**
        **go func(node interface{}) {** // pass arg in the closure
             .............
        **}(node)**
     }
}

**Review by misterikkit — APPROVED** [review]
Because a local variable was declared and initialized inside the loop with `n := node` this code does not actually contain the race described in this PR. For example, see the output of this snippet: https://play.golang.org/p/mjh0cscyOjJ

However, I think this change improves readability, since maintainers will not need to think as much about scoping rules when looking at function arguments. Maybe just change the commit message and PR description?

**Comment by gaurav1086** [comment]
@misterikkit thanks for the review. Yes this code doesn't improve any functionality. Updated the PR and the commit message.

**Pull request closed without merging**
