### PR TITLE
Fix golint failures in kg/kubelet/dockershim/network/kubenet/...

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
```
Errors from golint:
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:51:2: exported const BridgeName should have comment (or a comment on this block) or be unexported
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:100:1: exported function NewPlugin should have comment or be unexported
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:207:7: don't use ALL_CAPS in Go names; use CamelCase
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:207:7: exported const NET_CONFIG_TEMPLATE should have comment or be unexported
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:251:3: should replace cidr.IP[len(cidr.IP)-1] += 1 with cidr.IP[len(cidr.IP)-1]++
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:322:21: error strings should not be capitalized or end with punctuation or a newline
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:326:21: error strings should not be capitalized or end with punctuation or a newline

Please review the above warnings. You can test via "golint" and commit the result.
If the above warnings do not make sense, you can exempt this package from golint
checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
```

looks like actual failures to me, not a flake.

**Comment by xichengliudui** [comment]
Sorry for forgetting this file, I will resubmit these, thank you.

**Pull request closed without merging**
