### PR TITLE
Fix golint errors for pkg/cmd/annotate

### PR DESCRIPTION
**Pull request by lauchokyip**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixed golint issues in `pkg/cmd/annotate`

**Which issue(s) this PR fixes**:
Part of #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dougsland** [comment]
@lauchokyip do you mind to share the errors/warnings you are fixing in a comment?

**Comment by lauchokyip** [comment]
@dougsland Sure. The warning I found is
```
Errors from golint:
staging/src/k8s.io/kubectl/pkg/cmd/annotate/annotate.go:46:6: type name will be used as annotate.AnnotateOptions by other packages, and that stutters; consider calling this Options
```

Should I change it to other name?

**Comment by dougsland** [comment]
> @dougsland Sure. The warning I found is
> 
> ```
> Errors from golint:
> staging/src/k8s.io/kubectl/pkg/cmd/annotate/annotate.go:46:6: type name will be used as annotate.AnnotateOptions by other
> packages, and that stutters; consider calling this Options

Thanks for sharing. It helps the reviewers and owners.

> 
> 
> Should I change it to other name?

I don't think so but the owner of the module can suggest changes if required.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request closed without merging**
