### PR TITLE
Use map to represent defaultGroupVersions

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
For restmapper, currently defaultGroupVersions is expressed in slice.
This is not efficient for sorting.

This PR changes defaultGroupVersions to map where value is the ordinal from the input default GroupVersion.
During comparison for sorting, linear lookup is replaced with O(1) lookup.
Also made the short circuit case for rhsIndex prominent.

Memory consumption is on par with current formation.

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @deads2k 
to verify this is equivalent

please demonstrate the need for this improvement with a benchmark at typical API group counts

**Comment by tedyu** [comment]
Closing this before benchmark is presented showing the benefit

**Pull request closed without merging**
