### PR TITLE
WIP - Make resource.List a standard type

### PR DESCRIPTION
**Pull request by smarterclayton**
Currently each version has its own ResourceList, which prevents us from performing a fast copy during conversion of the map. Also, since we have to round the types down, we're having to assign each value back to the map (which is a 64 byte memcpy).

This PR creates new standard types in `pkg/api/resource` - `resource.Name` and `resource.List` - that can be used from multiple API versions.  The one outstandard challenge is that we add helper methods onto ResourceList today for CPU, pods, memory, and nvidia GPU resources, which requires the names of those resources to be in pkg/api/resource as well.  For now I copied them, but I plan on refactoring them out.

This change will net another 10% cpu reduction and a lot of cache thrashing during decode.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@wojtek-t I think this is too much to change for 1.3, but this is another 10% off conversions that have quantities because it avoids an expensive map copy (Quantities as values).  However, post 1.3 I i think we should change to make resource.List a type that can be reused by other packages.  This would continue to be backward compatible even if we made the change to protobuf because the serialization would be the same.

**Comment by wojtek-t** [comment]
@smarterclayton - I did a quick look into this PR. IIUC, this 10% off is because we are not copying the whole maps now in conversions, just a pointer to them, right?

If that's try, two questsions:
- can you please rebase?
- would it be possible to split the auto-generated code to a separate commit? It would be so much easier to review it :)

Thanks!

**Comment by wojtek-t** [comment]
@smarterclayton - will you find time to rebase this one?

**Comment by smarterclayton** [comment]
I think my unsafe pointer changes make this unnecessary.  The factoring here is useful in the long run, but not worth it now.

**Pull request closed without merging**
