### PR TITLE
Return missing ClusterID error instead of ignoring it

### PR DESCRIPTION
**Pull request by ghost**
This fixes issue #57382. In the cases I'm aware of kubelet cannot function if it can't detect the cluster it is running in, so the error should be passed up to the caller preventing initialization when kubelet would fail. This way the error can be detected and kubelet startup attempted again later (giving AWS time to apply the tags).

```release-note
On AWS kubelet returns an error when started under conditions that do not allow it to work (AWS has not yet tagged the instance).
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @justinsb 
Will it break something?

**Comment by vainu-arto** [comment]
If there is a case where kubelet is running on AWS and not having instance tags is expected and ok, this change will break that use case.

**Comment by jberkus** [comment]
reminder: we are now in Code Slush.  This PR needs priority/ kind/ and status/approved-for-milestone labels in order to merge into 1.10.  Thanks!

**Comment by chrislovecnm** [comment]
We need e2e with spot instances ....

**Comment by chrislovecnm** [comment]
> If there is a case where kubelet is running on AWS and not having instance tags is expected and ok, this change will break that use case.

There is a use case for this?

@justinsb added the comment around the time of adding support for shared tags, so I am not certain what this change would break.

**Comment by chen-anders** [comment]
Would we be able to cherry-pick this bug fix into 1.8/1.9? We had 2 clusters that were severely affected by this when we had upgraded to 1.8.

**Comment by mbohlool** [comment]
/hold

why this is not an automatic cherrypick?

**Comment by rphillips** [comment]
Is there an upgrade path for Kubernetes clusters running on AWS that do not set the KubernetesCluster or the modern `kubernetes.io/cluster/[clusterID]` tags?

**Comment by justinsb** [comment]
@rphillips not sure I understand - you have to set one of the tags, I'm afraid.  Is that a problem for your use case?

**Comment by rphillips** [comment]
Tags were never set on older versions of bootkube. I have fixed that going forward, but I suspect if other users of kubernetes had never set any tags, then upgrades are going to fail. I didn't see a warning in the release notes regarding this.

**Comment by jsravn** [comment]
> Tags were never set on older versions of bootkube. I have fixed that going forward, but I suspect if other users of kubernetes had never set any tags, then upgrades are going to fail. I didn't see a warning in the release notes regarding this.

The 1.5->1.6 upgrade deletes your nodes when they reboot or kubelet is restarted. No mention in the CHANGELOG about requiring a tag - prior to 1.6 it wasn't necessary, at least unofficially. I made https://github.com/kubernetes/kubernetes/issues/50915 for it a while ago.

**Pull request merged**
