### PR TITLE
Fix re-enable serving the storage.k8s.io/v1beta1 API version of CSIStorageCapacity

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The storage.k8s.io/v1beta1 API version of CSIStorageCapacity will no longer be depreciated in v1.27. It should be re-enable serving in both v1.27 and v1.28 when `--runtime-config=api/all=true` or `--runtime-config=api/beta=true`.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

kubernetes is v1.27.2

```
[root@master kubernetes]# kubectl api-versions | grep storage
storage.k8s.io/v1
```

#### Does this PR introduce a user-facing change?

```release-note
Fix re-enable serving the storage.k8s.io/v1beta1 API version of CSIStorageCapacity
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
test output:

```
[root@master ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.2.88+23fe3a1c6f075a", GitCommit:"23fe3a1c6f075a2c5a6aa8312911539012c5ddd4", GitTreeState:"clean", BuildDate:"2023-06-14T14:33:36Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

[root@master ~]# kubectl api-versions | grep storage
storage.k8s.io/v1
storage.k8s.io/v1beta1

[root@master ~]# kubectl get csistoragecapacity.v1beta1.storage.k8s.io
Warning: storage.k8s.io/v1beta1 CSIStorageCapacity is deprecated in v1.27+, unavailable in v1.29+; use storage.k8s.io/v1 CSIStorageCapacity
No resources found in default namespace.
[root@master ~]# kubectl get csistoragecapacity.v1.storage.k8s.io
No resources found in default namespace.
```

**Comment by pacoxu** [comment]
When reviewing this PR, I find #116574, and can you take a look if that is  a valid change?

**Comment by carlory** [comment]
> When reviewing this PR, I find #116574, and can you take a look if that is a valid change?

Yes.

Unfortunately, the modification is incorrect, I have commented.

**Review by Tusenka — APPROVED** [review]

**Comment by msau42** [comment]
@carlory can you point to the issue that explains why we need to re-enable serving? 1.27 has already been released so I am unaware of any decisions to roll that back.

**Comment by carlory** [comment]
@msau42 

According to @liggitt https://github.com/kubernetes/kubernetes/pull/117667#discussion_r1180637400, the storage.k8s.io/v1beta1 API version of CSIStorageCapacity can re-enable serving in both v1.27 and v1.28.

FYI: https://kubernetes.io/docs/reference/using-api/#api-versioning, 

```
Built-in beta API versions have a maximum lifetime of 9 months or 3 minor releases (whichever is longer) from introduction to deprecation, and 9 months or 3 minor releases (whichever is longer) from deprecation to removal.
```

**Comment by liggitt** [comment]
This PR is incorrect. Defaulting this off in 1.27 was working as expected. 

The "last chance" re-enablement of a deprecated and now-off-by-default beta API is by setting KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE=true envvar, not by extending the deprecation deadline.

/close

**Comment by carlory** [comment]
Thanks for your review!  You're right.

**Pull request closed without merging**
