### PR TITLE
Automated cherry pick of #55796

### PR DESCRIPTION
**Pull request by humblec**
Issue##37625, #49108

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs @saad-ali Can you please approve this cherry pick?

**Comment by humblec** [comment]
@jdumars @saad-ali Can you please approve this cherry pick?

**Comment by jdumars** [comment]
@jpbetz PTAL

**Pull request merged**
