### PR TITLE
set kubectl path

### LINKED ISSUE #16838: Validation workflow need to be updated in ubuntu.md
The current scripts did not print `Cluster validation succeeded`:

```

Kubernetes cluster is running.  The master is running at:

  http://10.10.102.153:8080

Using master 10.10.102.153
It looks as if you don't have a compiled kubectl binary

If you are running from a clone of the git repo, please run
'./build/run.sh hack/build-cross.sh'. Note that this requires having
Docker installed.

If you are running from a binary release tarball, something is wrong. 
Look at http://kubernetes.io/ for information on how to contact the 
development team for help.

```
I guess some validation steps are actually un-needed in ubuntu workflow? maybe we need to remove that line in the doc (at least)? @dalanlan

### PR DESCRIPTION
**Pull request by dalanlan**
Set valid path for `kubectl` when deploying on ubuntu. Fix #16838
/cc @resouer

### CODE REVIEW

**Comment by resouer** [comment]
Do you think "the current directory" is a proper location for all the stuff? (e.g. binaries, tar.gz) Can we make usage of the `_output`dir?

I don't know how other providers deal  with this, so do you mind to take a look? :)

**Comment by dalanlan** [comment]
The binaries that locate _output are built locally, which would be awkward to use in this case. Since we are biased to use one from release tarball, it should be stored somewhere else other than _output.


Thursday, November 5, 2015, 21:52 +0800 from Harry Zhang  <notifications@github.com>:

**Comment by resouer** [comment]
You also need to add this line in `cluster/ubuntu/deployAddons.sh`.

**Comment by dalanlan** [comment]
Comments addressed.

**Comment by roberthbailey** [comment]
Will mark as lgtm once @resouer is satisfied.

**Comment by resouer** [comment]
@roberthbailey I'm OK with this. Thanks @dalanlan :)

**Pull request merged**
