### PR TITLE
move crlf to kubectl/util

### PR DESCRIPTION
**Pull request by mengqiy**
move crlf from pkg/util/crlf to pkg/kubectl/util/crlf

Ref: https://github.com/kubernetes/kubernetes/issues/48209

```release-note
NONE
```
/assign @apelisse @monopole 

cc: @pwittrock

### CODE REVIEW

**Comment by apelisse** [comment]
Awesome Mengqi!

/lgtm

**Comment by mengqiy** [comment]
Fix go fmt.

**Pull request merged**
