### PR TITLE
Check server version when running scheduled job e2e tests

### PR DESCRIPTION
**Pull request by soltysh**
@janetkuo this is the promised followup to #30575 which is checking minimal server version when running ScheduledJob e2e's.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31957)

### CODE REVIEW

**Comment by janetkuo** [comment]
@soltysh this is reverted because alpha resources are disabled by default on GKE and this blocked the submit queue.

**Comment by soltysh** [comment]
@janetkuo so generally the previous solution was much better, since it was actually checking the resource being enabled. Maybe I should create a framework helper just for that purpose, since more objects are not enabled by default, wdyt?

**Comment by dims** [comment]
@soltysh or just use `framework.SkipIfProviderIs("gke")`?

**Comment by soltysh** [comment]
@dims not quite, because hopefully SJ will run on gke and I want them running there as soon as they are enabled. Besides others not using gke but disabling batch/v2alpha1 might trip over this, and I don't want to cause problems to them.

**Comment by dims** [comment]
Thanks @soltysh !

**Comment by janetkuo** [comment]
@soltysh that sounds good! For now it seems that scheduledjob is the only resource needing this.

**Comment by soltysh** [comment]
Since #32233 fixed the problem I've just re-applied this PR in #32284.

**Pull request merged**
