### PR TITLE
Code improve: use constants instead of hard coding

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Use constants instead of hard coding.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @SataQiu 
/lgtm
/priority backlog

**Review by neolit123 — COMMENTED** [review]
thanks

/lgtm
/approve

**Pull request merged**
