### PR TITLE
 Structured Logging migration: modify cmd/kubelet and pkg/kubelet/kub…

### PR DESCRIPTION
**Pull request by lunhuijie**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Structured Logging migration: modify server_windows part logs of kube-proxy.
xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
Capitalize the first word at the beginning of the sentence.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
part of kubernetes/enhancements#1602
As it is related to log, change the log here to structured log.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
triage/accept

**Comment by ehashman** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Pull request closed without merging**
