### PR TITLE
Revert "add node shutdown taint"

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Reverts kubernetes/kubernetes#59323

Node becomes unready, but is never removed. I've found the following in [kube-controller-manager.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling/6055/artifacts/bootstrap-e2e-master/cluster-autoscaler.log) from test run for one such node:

`E0216 01:14:27.084923       1 node_lifecycle_controller.go:686] Error determining if node bootstrap-e2e-minion-group-01b1 shutdown in cloud: failed to get instance ID from cloud provider: instance not found`

This goes on for the rest of the run (~6h). Looks like the node is stuck in Unready state because of this check: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L684. Previously, there was no such check and the node was removed.

Reverting as this would affect all users attempting to resize their node groups on GCE.

```release-note
NONE
```

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
> @k8s-ci-robot k8s-ci-robot requested review from anguslees, brendandburns, davidopp, jingxu97, thockin and zmerlynn a minute ago

No idea why the bot added so many people - sorry for the noise.

**Comment by zetaab** [comment]
/approve

like i wrote in that PR

@aleksandra-malinowska, right its bug. Here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L685 here we ignore only cloudprovider.NotImplemented error. However, there can be other errors as well which should be ignored https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/util/node/controller_utils.go#L199

so lets revert this and modify that little bit

**Comment by zetaab** [comment]
possible fix https://github.com/zetaab/kubernetes/commit/682be319a3b941a49ced9b5d53e65ca353d4e5c2 but not sure can this be allowed

**Comment by aleksandra-malinowska** [comment]
@zetaab Thanks for quick response. Let's proceed with the revert then.

**Comment by yastij** [comment]
cc @gmarek @jingxu97

**Review by yastij — APPROVED** [review]

**Comment by yastij** [comment]
cc @timothysc

**Comment by gmarek** [comment]
@smarterclayton - can you approve this?

**Comment by timothysc** [comment]
Only someone with higher cross directory OWNER privs can approve this one. 

/cc @smarterclayton @wojtek-t

**Comment by Random-Liu** [comment]
Possibly related to https://github.com/kubernetes/kubernetes/issues/59994?

**Pull request merged**
