### PR TITLE
use klog.Info instead of klog.V(0).Info

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qingsenLi** [comment]
/assign @caseydavenport
PTAL

**Comment by caseydavenport** [comment]
@qingsenLi could you provide some context for this PR? What is the motivation?

**Comment by qingsenLi** [comment]
@caseydavenport klog.Info default level is 0, I think that is redundant to add V (0).

**Comment by caseydavenport** [comment]
I think we shouldn't make this change, since it doesn't make a functional difference, and explicitly setting the log verbosity increases readability for people who don't know the implicit defaults. 

This document suggests the `klog.V(0)` is a reasonable verbosity to use: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by qingsenLi** [comment]
@caseydavenport thanks for review
/close

**Pull request closed without merging**
