### PR TITLE
[v1.21] bump konnectivity-client@v0.0.30

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bumps sigs.k8s.io/apiserver-network-proxy/konnectivity-client to v0.0.30, which includes two patches to fix goroutine leaks in kube-apiserver:
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/328
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/337
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/339

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Bump sigs.k8s.io/apiserver-network-proxy/konnectivity-client to v0.0.30, fixing goroutine leaks in kube-apiserver.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rata** [comment]
@kubernetes/release-managers can you please approve the cherry-pick?

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
