### PR TITLE
[Federation] Remove redundant e2e for secret and daemonset

### PR DESCRIPTION
**Pull request by marun**
Federation of daemonset and secret types is now implemented by the sync controller, and e2e testing for each type is provided via crud lifecycle e2e tests.  This renders the legacy e2e tests for these types redundant, and this commit removes those tests.

The secret wait and delete functions required by the ingress e2e tests have been retained and moved to ingress.go.

cc: @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by marun** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot kops aws e2e test this

**Comment by csbell** [comment]
While trying to make sure we cover everything in integration, I noticed that the OrphanDependents=false capability is missing from crud_test.go. Other than that, I agree both of these APIs can move to integration only.

**Comment by marun** [comment]
@csbell OrphanDependents=false is the default, and that path is validated for each type.  true and nil are only validated for secrets because the path is common across all types.

**Comment by shashidharatd** [comment]
As @csbell suggested we could also test when `OrphanDependents=false` delete test case.
I could only see 2 delete testcases https://github.com/kubernetes/kubernetes/blob/master/test/integration/federation/crud_test.go#L55
other than that LGTM.

**Comment by marun** [comment]
@shashidharatd As per my previous comment, the lifecycle crud check is validating that case:

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federatedtypes/crudtester/crudtester.go#L72

This is called in integration:

https://github.com/kubernetes/kubernetes/blob/master/test/integration/federation/crud_test.go#L43

And in e2e:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_federation/crud.go#L49

**Comment by shashidharatd** [comment]
@marun, sorry i missed that.
/lgtm

**Pull request merged**
