### PR TITLE
Kubeadm marshal tests

### LINKED ISSUE #802: Need unit tests for `cmd/kubeadm/app/util/marshal.go`
We need to write unit tests for all the functions in `cmd/kubeadm/app/util/marshal.go`, as well as round-trip unit tests (object -> marshal -> unmarshal should preserve everything)

@liztio you're working in this area right now, can you help here?

### PR DESCRIPTION
**Pull request by liztio**
**What this PR does / why we need it**:

Adds tests for the marshalling utilities in kubeadm.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: kubernetes/kubeadm#802

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@liztio 
probably best to merge the two commits under `Tests for kubeadm marshal utilities`.

`pull-kubernetes-e2e-gce-device-plugin-gpu`
^ my arch enemy.

/test pull-kubernetes-e2e-gce-device-plugin-gpu
/test pull-kubernetes-bazel-test

**Comment by liztio** [comment]
@neolit123 doesn't the mergebot automatically squash commits anyway? @timothysc said seperate commits for artefacts were preferred

**Review by luxas — APPROVED** [review]
/lgtm

**Pull request merged**
