### PR TITLE
Re-org of the openstack cloud provider

### PR DESCRIPTION
**Pull request by joe2far**

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot verification test this please, issue: #IGNORE

**Comment by mikedanese** [comment]
LGTM after quick skim but @kubernetes/sig-openstack for final review

**Comment by anguslees** [comment]
lgtm.  I've verified that the new files are unmodified copies of the content from the original openstack.go, fwiw.

@joe2far: Thanks!  This has been a needed-refactor for quite some time...

**Comment by mikedanese** [comment]
LGTM

**Pull request merged**
