### PR TITLE
kubelet: plumb context for log requests

### LINKED ISSUE #64315: Following container logs can leave processes running and open inotify watches
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:
If a container log is followed using kubectl or other API client, when the client disconnects, the process watching for changes in the logs does not die.

The process only dies when a new log line is received from the container (which may not happen) and the log process tries to send it to the client and then fails.  Furthermore, a inotify watch is also left open, which can potentially cause the OS to run out of watches and eventually results in `failed to create fsnotify watcher: too many open files` when the next container log is followed.

**What you expected to happen**:
When the client disconnects, the process watching the logs should die within a short time, and the inotify watch should be closed.

**Anything else we need to know?**:

**How to reproduce it (as minimally and precisely as possible)**:
This is simplest to reproduce using a single node instance of K8S e.g. minikube
Steps:

1. Create a pod that does not constantly produce log output e.g.
```
kubectl run log-test --image ubuntu:xenial --command sh -- -c 'date; sleep infinity'
```
2. With `kubectl` watch the pod logs (for the pod just created) and leave running:
```
kubectl logs log-test-78ddcd7d6f-7p7hr  -f
```
3. On the node that has the pod check the number of inotify watches from kubelet
```
 sudo lsof -p `pidof kubelet`  2> /dev/null | grep inotify | wc -l
```
4. Press ctrl-c to kill the `kubectl` watch started in (2)
5. Check the number of inotify watchers again by repeating (3).  The number has not decreased, and will never decrease until either the kubelet is restarted, a log line is received from the pod or the pod terminates.

**Anything else we need to know?**:
I believe the problem lies in how the `ReadLogs` function works here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L269
Unfortunately this has no way of knowing if the client has disconnected until it tries to send a new log line via the `writer`, which will then fail, close the inotify watcher (via the `defer`) and exit.

A container producing no log output will therefore leave the process running.

**Environment**:
- Kubernetes version: both 1.9.7 and 1.10.3
- Cloud provider or hardware configuration: VMWare
- OS (e.g. from /etc/os-release): Ubuntu Xenial
- Kernel (e.g. `uname -a`): 4.4.0-122-generic

### PR DESCRIPTION
**Pull request by yujuhong**
This allows kubelets to stop the necessary work when the context has
been canceled (e.g., connection closed), and not leaking a goroutine
and inotify watcher waiting indefinitely.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially fixes #64315

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix kubelet to not leak goroutines/intofiy watchers on an inactive connection if it's closed
```

### CODE REVIEW

**Comment by yujuhong** [comment]
This doesn't fully address the issue because the context is not canceled in most cases...

As it is today, even when the apiserver is completely gone, kubelet doesn't detect the closed connection...
If we add TCP keep-alive timeout in kubelet, when apiserver is down, at least kubelet can detect the closed connections and reclaim the resources (with this fix).

I'm not sure how the proxy connection is handled in the apiserver, but it seems like to fully resolve the issue, changes are needed in both kubelet and the apiserver.

**Comment by yujuhong** [comment]
I didn't look into the streaming request (exec/port-forward/attach) as they are handled differently.

/cc @Random-Liu @MHBauer

**Comment by MHBauer** [comment]
Yes, I concur with the observance of the context not being cancelled. This makes it difficult to rely on for other purposes.

**Review by MHBauer — APPROVED** [review]
looks plumbed to me
/lgtm

**Pull request merged**
