### PR TITLE
[go1.17] Update to go1.17.5

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng release-eng/security security

#### What this PR does / why we need it:

Update Kubernetes to go1.17.5 on release-1.23 branch

Tracking issue: https://github.com/kubernetes/release/issues/2349

/assign @dims @liggitt @justaugustus 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.17.5
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
/hold for https://github.com/kubernetes/kubernetes/pull/106835

not sure if we want to close the other in favor of this one, but if we merge https://github.com/kubernetes/kubernetes/pull/106835 I will rebase this after

**Comment by justaugustus** [comment]
> not sure if we want to close the other in favor of this one, but if we merge #106835 I will rebase this after

https://github.com/kubernetes/kubernetes/pull/106835#issuecomment-992150825

**Comment by cpanato** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/106835

/close

**Pull request closed without merging**
