### PR TITLE
[WIP] Server-side Apply: Track ownership for scale subresource for Deployments

### LINKED ISSUE #82046: Server-side Apply: Ownership not tracked for scale subresource
Whenever someone sends a scale sub-resources request, the managed fields are not changed for that specific request, which means that the scale will typically not grab the ownership of the "replicas" field. This is obviously a bug, but we don't exactly know how to fix it for now.

### PR DESCRIPTION
**Pull request by julianvmodesto**
**What type of PR is this?**
/kind bug
/wg apply

**What this PR does / why we need it**: 
Track the owner for `.spec.replicas` for the Deployment scale subresource.

Not sure if this will actually work, or if we'll have to fix scale somehow.

**Which issue(s) this PR fixes**:

Fixes #82046

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
This is a good start, but I think it might be difficult to implement the necessary logic to update the managedfields for scale here, since the code for parsing it and encoding it is defined in [k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal).

I had an idea for how to get around that, let me know if you think it makes sense. The idea is to create a "scale fieldmanager" (that only understands how to update the scale field's ownership of an object), in the k8s.io/apiserver/.../fieldmanager package, and add it to the scale request scope, so it gets passed into [ScaleRest.Update](https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/pkg/registry/apps/deployment/storage/storage.go#L275) by the scale subresource handler automatically as a transformer for the updatedObjectInfo.

To wire this from the subresource to the main resource, autoscaling.v1/Scale already has a [metadata field]( https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/staging/src/k8s.io/api/autoscaling/v1/types.go#L118) which includes managedFields. We could use that to adjust the managedfields, by modifying [scaleFromDeployment](https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/pkg/registry/apps/deployment/storage/storage.go#L355) to populate that field, then the transformer to the [updatedObjectInfo](https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/pkg/registry/apps/deployment/storage/storage.go#L287) which we passed in earlier would update the ownership for us, and we just need to make sure we also [copy back](https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/pkg/registry/apps/deployment/storage/storage.go#L308-L309) the value from the scale's managedFields into the deployment object.

The "scale fieldmanager" would operate on objects of type autoscaling.v1/Scale, but with managedFields representing field management on the underlying resource. Then, it just needs to know what fieldpath in the underlying resource corresponds to Scale.spec.replicas, in deployment's case it would be the same fieldpath, but I think CRD can define the path [themselves](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go#L401), so we would have to construct the scale field manager with that path as an argument.

**Comment by jennybuckley** [comment]
Another option is to pass in a Deployment FieldManager into the sub-update as a transformer [here](https://github.com/kubernetes/kubernetes/blob/6327be942f5677a3ff212a8af949839bc7faf815/pkg/registry/apps/deployment/storage/storage.go#L313)

**Comment by julianvmodesto** [comment]
@jennybuckley oh nice! Thank you, this makes sense! I'll give it a shot

**Comment by kwiesmueller** [comment]
@jennybuckley would your suggestion mean, that we would have to have a fieldManager for every subresource?

**Pull request closed without merging**
