### PR TITLE
Remove unused ClusterName from NodeController

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by cjcullen** [comment]
You can get rid of it in the NodeController, but #8164 depends on the flag being there in the controller-manager.

**Comment by gmarek** [comment]
@cjcullen - Why do you need ClusterName there? IIUC you just need it to generate "more readable" route names, as node UIDs assure uniqueness, am I right? Maybe you can use project name for this, or something else, as using something that's not used anywhere else isn't probably the best idea.

To be clear - I'm OK with keeping this flag there for you, I'm just not sure that it's the best thing to do.

**Comment by cjcullen** [comment]
I use the cluster name to know whether a route belongs to a cluster on clean-up/reconciliation. It is a bit redundant, as I also check that the route is inside the cluster CIDR range.

You can rip it out here and leave the burden of proof on me to show that I need it in #8164 :).

**Comment by gmarek** [comment]
We can always reintroduce this flag if it turn out that sth like it is necessary.

**Comment by jszczepkowski** [comment]
LGTM

**Comment by gmarek** [comment]
I'll ping you when I have e2e results.

**Comment by gmarek** [comment]
e2e is green

**Pull request merged**
