### PR TITLE
Adding OWNERS file for test/integration/federation

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes/issues/40705

File copied from federation/OWNERS.

Existing pending PRs for this diectory:
https://github.com/kubernetes/kubernetes/pull/42278 and https://github.com/kubernetes/kubernetes/pull/42225

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by deads2k** [comment]
It flaked on #39471

**Comment by nikhiljindal** [comment]
@deads2k Can I get an LGTM as well?

**Pull request merged**
