### PR TITLE
Automated cherry pick of #33143 upstream release 1.4

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #33143 upstream release 1.4

Note that I resolved a merge conflict in `test/e2e/disruption.go` while creating this 
cc @mml

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33209)

### CODE REVIEW

**Comment by janetkuo** [comment]
Not sure if we need to cherrypick this one, since it looks related to #33133, which I don't think we need to cherrypick, see https://github.com/kubernetes/kubernetes/pull/33133#issuecomment-248744307

**Comment by mml** [comment]
@janetkuo the behavior change in the disruption controller is important.

**Comment by mml** [comment]
@janetkuo in order to get this to apply cleanly to release-1.4, I think we'll need to grab kubernetes@138647e329dcb3c4acaf24d9a6bd9479891a17a6 as well

**Comment by pwittrock** [comment]
@mml I didn't read the comments and I am reverting this.  This probably won't go into 1.4.0 as it isn't in a state to be merged into the branch, and after tonight I am not taking any other changes besides those that stabilize the build.

**Pull request merged**
