### PR TITLE
Add -A as a shorthand for --all-namespaces

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

This has been annoying me for a long time ;)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add -A as a shorthand for --all-namespaces
```

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot cvm gke e2e test this

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by fabianofranz** [comment]
I personally like having uppercase flags meaning a "bigger/broader/full version of the related lowercase flag". 

In that sense, I'd suggest `-N` which semantically translates to "all `-n`", or "all namespaces".

**Comment by kargakis** [comment]
There is https://github.com/kubernetes/kubernetes/pull/34355 which does what @fabianofranz suggests.

**Comment by janetkuo** [comment]
From https://github.com/kubernetes/kubernetes/pull/34355#issuecomment-252357197:

> Honestly having any shorthand flag that goes across all namespaces is concerning to me

I second this, whichever char we choose. Also, according to [kubectl conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#flag-conventions), we should use short flags sparingly, only for the most frequently used options

**Comment by luxas** [comment]
Yep, understand. Hadn't seen that other PR.
I'm closing this, that argument is totally fine, no worries.

But we're gonna have to train our typing muscles then :)

**Pull request closed without merging**
