### PR TITLE
Automated cherry pick of #45181 #45569 upstream release 1.6

### PR DESCRIPTION
**Pull request by divyenpatel**
Cherry pick of #45181 #45569 on release-1.6.

#45181: Filter out IPV6 addresses from NodeAddresses() returned by vSphere
#45569:  Fixing VolumesAreAttached and DisksAreAttached functions in vSphere

@BaluDontu @luomiao  @tusharnt

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot test this

**Comment by divyenpatel** [comment]
@k8s-bot verify test this

**Comment by divyenpatel** [comment]
@enisoc Jenkins verification failure is not related to the change.

**Comment by enisoc** [comment]
I'm working on fixing the branch so verify passes. https://github.com/kubernetes/release/issues/326

**Comment by enisoc** [comment]
@k8s-bot verify test this

**Pull request merged**
