### PR TITLE
Update Windows image patch version

### PR DESCRIPTION
**Pull request by jingxu97**
Update Windows image version to the latest one. This one includes a fix
for unix domain socket

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR update Windows image patch version to the latest one. It includes a fix
for unix domain socket use for Windows.

**Which issue(s) this PR fixes**:

Fixes # https://github.com/kubernetes/kubernetes/issues/95199

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

<!--
This section can be blank if this pull request does not require a release note.

When adding links which point to resources within git repositories, like
KEPs or supporting documentation, please reference a specific commit and avoid
linking directly to the master branch. This ensures that links reference a
specific point in time, rather than a document that may change over time.

See here for guidance on getting permanent links to files: https://help.github.com/en/articles/getting-permanent-links-to-files

### CODE REVIEW

**Comment by pjh** [comment]
Please edit the PR description and either fill in the appropriate fields or remove the text if it's not needed.

> What type of PR is this?
> 
> What this PR does / why we need it:
> 
> Which issue(s) this PR fixes:
> 
> Fixes #
> 
> Special notes for your reviewer:
> 
> Does this PR introduce a user-facing change?:
> 
> NONE
> Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

**Comment by jingxu97** [comment]
cc @mtaufen PTAL

**Pull request merged**
