### PR TITLE
Revert "Updated gRPC vendoring to support Keep Alive"

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#50531

Ref - https://github.com/kubernetes/kubernetes/issues/51099

/cc @wojtek-t @RenaudWasTaken

### CODE REVIEW

**Comment by shyamjvs** [comment]
@kubernetes/test-infra-maintainers The kops-aws job seems to be continuously failing. Could you PTAL?

**Comment by krzyzacy** [comment]
`289 Passed | 1 Failed | 0 Pending | 387 Skipped ` I think the job is just flaky, and I see it's passing on other PRs.

/retest

**Comment by RenaudWasTaken** [comment]
I believe #51154 should fix the original problem :)
Merging might cause rebase issues for #51154 though :D

**Comment by shyamjvs** [comment]
@RenaudWasTaken Oops.. The merge happened already. Anyway, I think that it's a good idea here to revert the faulty PR and then fix it in a separate one for 2 reasons:
- If the fix is also faulty, then we'll have to revert both PRs. Now we just have to revert your fix (if faulty)
- Reverting the faulty one quickly makes sure the test goes green again (which is important to catch regressions), rather than waiting for the fix to be reviewed and merged (which can take more than a day).

**Comment by RenaudWasTaken** [comment]
No worries working on updating the PR

**Pull request merged**
