### PR TITLE
Add targets for PHONY in Makefile

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Add targets for PHONY in Makefile and keep the same style between rules and PHONY

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31228)

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@jbeda PTAL
Thanks!

**Comment by jbeda** [comment]
Sorry for the delay!  This got missed.

**Comment by jbeda** [comment]
@k8s-bot ok to test

**Comment by yuexiao-wang** [comment]
@k8s-ci-robot 
Issue: https://github.com/kubernetes/kubernetes/issues/33528

**Pull request merged**
