### PR TITLE
[release-1.30] [go] Bump images, dependencies and versions to go 1.22.4 and distroless iptables/setcap/debian-base

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.22.4 and distroless iptables/setcap/debian-base

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/3628

/assign @MadhavJivrajani @liggitt @xmudrii @puerco    
cc @kubernetes/release-managers 

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.22.4
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
forgot to promote one image 🤦  https://github.com/kubernetes/k8s.io/pull/6874

**Comment by humblec** [comment]
@cpanato can you please confirm this go bump is going to be part of June patch release which is expected today?

**Comment by MadhavJivrajani** [comment]
@humblec yes, this is for the June patches :)

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
