### PR TITLE
use framework.GetClusterZones() instead of getZoneNames()

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:
fix todo: 
use framework.GetClusterZones() instead of getZoneNames()
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ravisantoshgudimetla — APPROVED** [review]
Thanks @tanshanshan for the PR.

/lgtm

**Review by bsalamat — APPROVED** [review]
/lgtm

**Pull request merged**
