### PR TITLE
do not merge: looking for DRA test flake

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

Hoping to prove that a test flake observed in https://github.com/kubernetes/kubernetes/pull/127904 is already reproducible against master branch.

Said test flake:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127904/pull-kubernetes-kind-classic-dra/1843362682007195648

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
I'm about to prepare a PR which removes classic DRA. The KEP update for it was already merged.

**Comment by jackfrancis** [comment]
> I'm about to prepare a PR which removes classic DRA. The KEP update for it was already merged.

Should I assume the "classic-dra" test will go with it? :)

**Comment by pohly** [comment]
Yes.

**Comment by jackfrancis** [comment]
no need to dig into classic-dra test flakes due to impeding deletion

**Pull request closed without merging**
