### PR TITLE
Improve TLS unit test reporting in bazel

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

Rather than skipping the test when we can't inspect go source (which is the case in bazel environments), check that we're running the version of go we expect and print a message describing how to manually verify the TLS constants.

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/kubernetes/issues/78982

**Special notes for your reviewer**:
This test is a hack but go doesn't provide a better way to enumerate the available ciphers/tls versions

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @dims

### CODE REVIEW

**Comment by BenTheElder** [comment]
> Rather than skipping the test when we can't inspect go source (which is the case in bazel environments)

Note: you can set the source as a data dependency and make this work (see the various all sources filegroups) if it needs the whole source tree though this basically eliminates any hope of caching...

**Comment by makoscafee** [comment]
Hello! @liggitt  I'm a bug triage shadow for the 1.16 release cycle I'd like to check it's status. The code freeze is starting 29th August (about 2 weeks from now) and while there is plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.16, is it still planned for this release?

**Comment by liggitt** [comment]
> you can set the source as a data dependency and make this work (see the various all sources filegroups) if it needs the whole source tree though this basically eliminates any hope of caching...

does that allow referencing go stdlib source? would that allow caching (assuming we're not changing the go version we build with)?

**Comment by BenTheElder** [comment]
Should be possible somehow. Not sure off the top of my head.

Shouldn't be a problem for caching since it wouldn't change often.

**Comment by liggitt** [comment]
looks like this info might be made available in go1.14

will continue to keep an eye on this manually for now (worse case is a new cipher in a new go version is not noticed, someone reports an issue, and we add it)

**Pull request closed without merging**
