### PR TITLE
add integration test for apiserver hsts

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:

add integration test for #96502

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

typecheck failure is legitimate

**Comment by 249043822** [comment]
> /hold
> 
> typecheck failure is legitimate

@liggitt need rebase, re-push a moment later

**Pull request merged**
