### PR TITLE
Api server extra args

### LINKED ISSUE #760: Ensure ExtraArgs take precedence over generated args
https://github.com/kubernetes/kubernetes/pull/61705 from @jstangroome fixed a minor error in management of extra args for scheduler; we should implement a similar fix for the API server as well

### PR DESCRIPTION
**Pull request by chuckha**
**What this PR does / why we need it**:

This PR will correctly override the APIServer command with the values found in APIServerExtraArgs. If none are passed in a default set of flags will be used.

This also includes cleaning up tests by using `t.Run` and naming test cases so we know what they are doing. `t.Run` also provides better testing output when coupled with a name.

At some point we stopped using the k8s version to generate this command. It is trivial to add back if we need it later, but since we don't use it now it's best for it to go. This also exposed several test that were identical. Those have been removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#760

**Special notes for your reviewer**:
I split this into two commits since it's a bit easier to think about like that, but would be fine squashing.

**Release note**:

```release-note
NONE
```

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by chuckha** [comment]
also cc @fabriziopandini

**Review by fabriziopandini — APPROVED** [review]
@chuckha Thanks for this PR!
/lgtm

**Review by timothysc — CHANGES_REQUESTED** [review]
please squash commits.

**Comment by chuckha** [comment]
@timothysc fixed

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
