### PR TITLE
fix n to nodeInfo easy to understand

### PR DESCRIPTION
**Pull request by lixiaobing1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Var "n" is not easy to understand, so modify it to "nodeInfo".

**Which issue(s) this PR fixes**:
No

**Special notes for your reviewer**:
No

**Does this PR introduce a user-facing change?**:
No

```release-note
   NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
No

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
Looks like you changed the permissions on this file too, did you intend that? `100644 → 100755`

**Comment by damemi** [comment]
Also, since this isn't user facing it doesn't need a release note :)
/release-note none

**Review by qiutongs — APPROVED** [review]

**Comment by lixiaobing1** [comment]
> Looks like you changed the permissions on this file too, did you intend that? `100644 → 100755`
@damemi, yeah, has been recovered to 644.

**Review by damemi — COMMENTED** [review]
/lgtm
@lixiaobing1 could you also change the release note to `NONE`?

**Comment by lixiaobing1** [comment]
> /lgtm
> @lixiaobing1 could you also change the release note to `NONE`?

@damemi, ok has been set NONE :)

**Pull request merged**
