### PR TITLE
remove todo:add jobdescriber and ingressdescriber to event test

### LINKED ISSUE #24731: Missing unit-tests for HorizontalPodAutoscalerDescriber, IngressDescriber and JobDescriber
When running pkg/kubectl/describe_test.go, there are three objects that has no unit-tests at all:
- HorizontalPodAutoscalerDescriber
- IngressDescriber
- JobDescriber.

I could not found proper fake client for them. It looks like all three needs the same fake client.

Related to https://github.com/kubernetes/kubernetes/issues/24239 to finish testing of `kubectl describe --events=true|false`.

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
Fixes #24731

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
cc @kubernetes/sig-cli-pr-reviews

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
ptal @ingvagabund @soltysh

**Comment by zjj2wry** [comment]
ping @@ingvagabund @soltysh

**Comment by zjj2wry** [comment]
/unassign @ericchiang 
/backlog
@liggitt Do you know the test code? seems soltysh is busy recently... thanks

**Comment by ingvagabund** [comment]
@zjj2wry cool, thanks for the PR

**Review by soltysh — APPROVED** [review]

**Comment by soltysh** [comment]
@kubernetes/sig-cli-maintainers for approval

**Review by ingvagabund — APPROVED** [review]

**Comment by deads2k** [comment]
We don't guarantee the stability of describer output.  I fear that adding a test like this will increase momentum and debt for future changes in the describer are.  Is there some tricky code in these describers that we're trying to test (that isn't obvious from the test which appears to be trying to pin output)?  If so, please link it through.

**Comment by zjj2wry** [comment]
> We don't guarantee the stability of describer output. I fear that adding a test like this will increase momentum and debt for future changes in the describer are. Is there some tricky code in these describers that we're trying to test (that isn't obvious from the test which appears to be trying to pin output)? If so, please link it through

I think the situation of instability will only appear when there is an array or map in your describer output. Although I did not find there is some tricky code, but my original intention was to test that they worked just as well as other resources. jobDescriber and ingressDescriber missing test, so I think we should add it.

**Pull request closed without merging**
