### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by porridge**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixes typos.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by nikhita** [comment]
/sig api-machinery

/assign @deads2k 
for approval

**Comment by porridge** [comment]
friendly ping @deads2k

**Comment by porridge** [comment]
> friendly ping @deads2k

ping again

**Pull request merged**
