### PR TITLE
Moved start-kubemark-master.sh from test/kubemark/ to test/kubemark/resources/

### PR DESCRIPTION
**Pull request by shyamjvs**

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37676)

**Comment by gmarek** [comment]
@foxish @caniszczyk - any idea why CLA bot might be unhappy here?

**Comment by shyamjvs** [comment]
Closing this PR and reopening a new one with the right author commits.

**Comment by shyamjvs** [comment]
Closing this PR and reopening a new one having commits with the right author. Sorry for the inconvenience.

**Comment by shyamjvs** [comment]
Sorry for this issue with the CLA. It was because the author for the commit
was set to my workstation user, instead of the email-id that was authorized
through the CLA. Fixed this issue now in a new PR.

**Pull request closed without merging**
