### PR TITLE
kubeadm: Use the v1.9 branch by default

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
As per https://github.com/kubernetes/kubeadm/blob/master/docs/release-cycle.md, bump the default Kubernetes version to use in kubeadm right before v1.9.0-rc.1 (or maybe rc.0 ?) is cut.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: https://github.com/kubernetes/kubernetes/pull/47440 https://github.com/kubernetes/kubernetes/pull/52085

**Special notes for your reviewer**:
/cc @luxas @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/kubernetes-release-managers

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by jamiehannaford — APPROVED** [review]
/lgtm

**Review by luxas — APPROVED** [review]
/approve

@enisoc this PR must be merged right before you cut the release candidate

**Comment by luxas** [comment]
/hold

This should be merged right before the release candidate is cut

**Comment by enisoc** [comment]
@luxas Can you elaborate on why this can't be merged now?

**Comment by luxas** [comment]
@enisoc Sure! Well, technically it can indeed, but the issue is that `dl.k8s.io/release/stable-1.9.txt` doesn't exist until v1.9.0 is cut, so we'd like to minimize the time `kubeadm init` at HEAD doesn't work out-of-the-box (as it tries to use a v1.9 version although there aren't any).

Makes sense to you?

**Comment by xiangpengzhao** [comment]
ping for Milestone update.

**Comment by luxas** [comment]
Let's merge this as we're getting close to releasing v1.9.0 :)

/hold cancel

**Pull request merged**
