### PR TITLE
cleanup: Removes duplicate utils code

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The utils found in ``pkg/kubelet/cri/remote/utils`` are the same as the ones in ``pkg/kubelet/utils``, with the difference that the latter have had a few improvements recently.

This PR removes the duplicated code.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alexzielenski** [comment]
For completeness I ran a diff to see the differences between the two folders as of c679fee12911ed7eec03c02cb7fa0d60257d57b6:

```diff
❯ diff pkg/kubelet/util/ pkg/kubelet/cri/remote/util                                                                                                                                                       informer*​​ ⇕≡
Only in pkg/kubelet/util/: boottime_util_darwin.go
Only in pkg/kubelet/util/: boottime_util_freebsd.go
Only in pkg/kubelet/util/: boottime_util_freebsd_test.go
Only in pkg/kubelet/util/: boottime_util_linux.go
Only in pkg/kubelet/util/: boottime_util_linux_test.go
Only in pkg/kubelet/util/: cache
Only in pkg/kubelet/util/: doc.go
Only in pkg/kubelet/util/: format
Only in pkg/kubelet/util/: ioutils
Only in pkg/kubelet/util/: manager
Only in pkg/kubelet/util/: nodelease.go
Only in pkg/kubelet/util/: queue
Only in pkg/kubelet/util/: sliceutils
Only in pkg/kubelet/util/: store
Only in pkg/kubelet/util/: util.go
Only in pkg/kubelet/util/: util_test.go
diff pkg/kubelet/util/util_unix.go pkg/kubelet/cri/remote/util/util_unix.go
104c104
<                       klog.InfoS("Using this endpoint is deprecated, please consider using full URL format", "endpoint", endpoint, "URL", fallbackEndpoint)
---
>                       klog.InfoS("Using this format as endpoint is deprecated, please consider using full url format.", "deprecatedFormat", endpoint, "fullURLFormat", fallbackEndpoint)
131,139d130
< // LocalEndpoint returns the full path to a unix socket at the given endpoint
< func LocalEndpoint(path, file string) (string, error) {
<       u := url.URL{
<               Scheme: unixProtocol,
<               Path:   path,
<       }
<       return filepath.Join(u.String(), file+".sock"), nil
< }
< 
diff pkg/kubelet/util/util_unix_test.go pkg/kubelet/cri/remote/util/util_unix_test.go
137,182d136
< 
< func TestGetAddressAndDialer(t *testing.T) {
<       tests := []struct {
<               endpoint     string
<               expectError  bool
<               expectedAddr string
<       }{
<               {
<                       endpoint:     "unix:///tmp/s1.sock",
<                       expectError:  false,
<                       expectedAddr: "/tmp/s1.sock",
<               },
<               {
<                       endpoint:     "unix:///tmp/f6.sock",
<                       expectError:  false,
<                       expectedAddr: "/tmp/f6.sock",
<               },
<               {
<                       endpoint:    "tcp://localhost:9090",
<                       expectError: true,
<               },
<               {
<                       // The misspelling is intentional to make it error
<                       endpoint:    "htta://free-test.com",
<                       expectError: true,
<               },
<               {
<                       endpoint:    "https://www.youtube.com/",
<                       expectError: true,
<               },
<               {
<                       endpoint:    "http://www.baidu.com/",
<                       expectError: true,
<               },
<       }
<       for _, test := range tests {
<               // just test addr and err
<               addr, _, err := GetAddressAndDialer(test.endpoint)
<               if test.expectError {
<                       assert.NotNil(t, err, "expected error during parsing %s", test.endpoint)
<                       continue
<               }
<               assert.Nil(t, err, "expected no error during parsing %s", test.endpoint)
<               assert.Equal(t, test.expectedAddr, addr)
<       }
< }
diff pkg/kubelet/util/util_windows.go pkg/kubelet/cri/remote/util/util_windows.go
106c106
<               return "", "", fmt.Errorf("Using %q as endpoint is deprecated, please consider using full url format", endpoint)
---
>               return "", "", fmt.Errorf("using %q as endpoint is deprecated, please consider using full url format", endpoint)
112,116d111
< // LocalEndpoint empty implementation
< func LocalEndpoint(path, file string) (string, error) {
<       return "", fmt.Errorf("LocalEndpoints are unsupported in this build")
< }
< 
diff pkg/kubelet/util/util_windows_test.go pkg/kubelet/cri/remote/util/util_windows_test.go
23d22
<       "fmt"
28,29d26
<       "reflect"
<       "runtime"
38,118d34
< func TestGetAddressAndDialer(t *testing.T) {
< 
<       // Compare dialer function by pointer
<       tcpDialPointer := reflect.ValueOf(tcpDial).Pointer()
<       npipeDialPointer := reflect.ValueOf(npipeDial).Pointer()
<       var nilDialPointer uintptr = 0x0
< 
<       tests := []struct {
<               endpoint      string
<               expectedAddr  string
<               expectedDial  uintptr
<               expectedError bool
<       }{
<               {
<                       endpoint:      "tcp://localhost:15880",
<                       expectedAddr:  "localhost:15880",
<                       expectedDial:  tcpDialPointer,
<                       expectedError: false,
<               },
<               {
<                       endpoint:      "npipe://./pipe/mypipe",
<                       expectedAddr:  "//./pipe/mypipe",
<                       expectedDial:  npipeDialPointer,
<                       expectedError: false,
<               },
<               {
<                       endpoint:      "npipe:\\\\.\\pipe\\mypipe",
<                       expectedAddr:  "//./pipe/mypipe",
<                       expectedDial:  npipeDialPointer,
<                       expectedError: false,
<               },
<               {
<                       endpoint:      "unix:///tmp/s1.sock",
<                       expectedAddr:  "",
<                       expectedDial:  nilDialPointer,
<                       expectedError: true,
<               },
<               {
<                       endpoint:      "tcp1://abc",
<                       expectedAddr:  "",
<                       expectedDial:  nilDialPointer,
<                       expectedError: true,
<               },
<               {
<                       endpoint:      "a b c",
<                       expectedAddr:  "",
<                       expectedDial:  nilDialPointer,
<                       expectedError: true,
<               },
<       }
< 
<       for _, test := range tests {
<               expectedDialerName := runtime.FuncForPC(test.expectedDial).Name()
<               if expectedDialerName == "" {
<                       expectedDialerName = "nilDial"
<               }
<               t.Run(fmt.Sprintf("Endpoint is %s, addr is %s and dialer is %s",
<                       test.endpoint, test.expectedAddr, expectedDialerName),
<                       func(t *testing.T) {
<                               address, dialer, err := GetAddressAndDialer(test.endpoint)
< 
<                               dialerPointer := reflect.ValueOf(dialer).Pointer()
<                               actualDialerName := runtime.FuncForPC(dialerPointer).Name()
<                               if actualDialerName == "" {
<                                       actualDialerName = "nilDial"
<                               }
< 
<                               assert.Equalf(t, test.expectedDial, dialerPointer,
<                                       "Expected dialer %s, but get %s", expectedDialerName, actualDialerName)
< 
<                               assert.Equal(t, test.expectedAddr, address)
< 
<                               if test.expectedError {
<                                       assert.NotNil(t, err, "Expect error during parsing %q", test.endpoint)
<                               } else {
<                                       assert.Nil(t, err, "Expect no error during parsing %q", test.endpoint)
<                               }
<                       })
<       }
< }
< 
122c38
<               expectedError    bool
---
>               expectError      bool
129c45
<                       expectedError:    true,
---
>                       expectError:      true,
164c80
<                       expectedError:    true,
---
>                       expectError:      true,
167,168c83,84
<                       endpoint:      "a b c",
<                       expectedError: true,
---
>                       endpoint:    "a b c",
>                       expectError: true,
175c91
<               if test.expectedError {
---
>               if test.expectError {
186c102
<       generatePipeName := func(suffixLen int) string {
---
>       generatePipeName := func(suffixlen int) string {
189c105
<               b := make([]rune, suffixLen)
---
>               b := make([]rune, suffixlen)
```

/lgtm

**Review by wzshiming — APPROVED** [review]
/lgtm

/assign @feiskyer

**Comment by claudiubelu** [comment]
> For completeness I ran a diff to see the differences between the two folders as of [c679fee](https://github.com/kubernetes/kubernetes/commit/c679fee12911ed7eec03c02cb7fa0d60257d57b6):
> ...

Those differences were introduced here (https://github.com/kubernetes/kubernetes/pull/110075), improving the unix Sockets on Windows.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
