### PR TITLE
add rolereaper and clusterrolereaper

### PR DESCRIPTION
**Pull request by xilabao**
add rolereaper and clusterrolereaper to kubectl. When delete a role object (`kubectl delete roles/clusterroles`), delete the related rolebinding/clusterrolebinding object.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37480)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by AdoHe** [comment]
@xilabao some verification failed, please fix it. I will take a look when back to office.

**Comment by xilabao** [comment]
@AdoHe PTAL

**Comment by AdoHe** [comment]
@xilabao could you link the original issue here? I am out of the context.

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by deads2k** [comment]
I don't want to encourage more reapers.  How about changes that make use of garbage collection instead.

**Comment by soltysh** [comment]
@deads2k reapers is about every resource deletion, GC is for pod, iiuc. Maybe you meant server-side resource deletion?

**Comment by soltysh** [comment]
If you ask - yes, I need to add CronJob reaper 😉

**Comment by kargakis** [comment]
> @deads2k reapers is about every resource deletion, GC is for pod, iiuc. Maybe you meant server-side resource deletion?

No, GC is for every object that has a parent. It's merely implemented only for Pods now.

**Comment by xilabao** [comment]
the original issue : https://github.com/kubernetes/kubernetes/issues/37595

**Comment by AdoHe** [comment]
```
GC is for every object that has a parent
```
what `parent` means here? For pods, if created by controller, we can say the controller is the parent, but for role and rolebinding, not in this relationship, seems GC cannot handle this, then the reaper is necessary.

**Comment by kargakis** [comment]
The binding is owned by the role.

**Comment by AdoHe** [comment]
@kargakis thanks for explanation, then we should leave this to GC controller.

**Comment by AdoHe** [comment]
```
I don't want to encourage more reapers. How about changes that make use of garbage collection instead.
```
SGTM. we should leave this to GC controller.

**Comment by kargakis** [comment]
I don't think there is a controller for roles and rolebindings atm. We would need one that adds owner references in role bindings. Or maybe we could add the owner reference as part of defaulting?

**Comment by deads2k** [comment]
> I don't think there is a controller for roles and rolebindings atm. We would need one that adds owner references in role bindings. Or maybe we could add the owner reference as part of defaulting?

@liggitt our first case of "does the power to create imply the power to delete".  I think I'd allow it, thought the choice of defaulting versus `PrepareForCreate` isn't as obvious.  Doing it as a prepare only on create would allow you to disconnect it if you wished to.

Alternatively, we could force you to specify and just the `kubectl create rolebinding` set up the link.

**Comment by liggitt** [comment]
forcing an ownerref in the resthandler is unusual, but I think it's a correct representation of the relationship

**Comment by xilabao** [comment]
Thanks for the comments.  I will update it.

**Comment by deads2k** [comment]
I was expecting a pull which updated `metadata.ownerReferences`

**Comment by AdoHe** [comment]
@xilabao 
```
I was expecting a pull which updated metadata.ownerReferences
```
ptal

**Comment by xilabao** [comment]
@AdoHe @deads2k  PTAL

**Comment by soltysh** [comment]
@xilabao have a look at https://github.com/kubernetes/kubernetes/pull/35676 for how this should be implemented.

**Comment by xilabao** [comment]
@soltysh @deads2k @AdoHe ... PTAL

**Comment by kargakis** [comment]
I thought we agreed on doing this as part of defaulting and not a separate controller. @deads2k suggested [PrepareForCreate](https://github.com/kubernetes/kubernetes/blob/9a0a72431313292b1f1c1480b51519ec875d4207/pkg/registry/rbac/rolebinding/strategy.go#L61).

**Comment by xilabao** [comment]
@kargakis @deads2k I tied to get the uid of role for ownerReferences. But `func (strategy) PrepareForCreate(ctx api.Context, obj runtime.Object)` doesn't have a way to get role object. Did I make a mistake？

**Comment by kargakis** [comment]
@xilabao the role binding already holds a reference to the role it binds: https://github.com/kubernetes/kubernetes/blob/f8b708385e521494c762c4579740a199df9ab5bc/pkg/apis/rbac/v1alpha1/types.go#L131

Also you will need to do the same thing for clusterrolebindings.

**Comment by xilabao** [comment]
@kargakis Yes, I can get the role name from the reference of rolebinding, but I didn't find a way to get the detail of the role. Because the ownerReferences need the uid, so I tried to get it. Is there a way to get the role object?

**Comment by mikedanese** [comment]
> add rolereaper and clusterrolereaper to kubectl. When delete a role object (kubectl delete roles/clusterroles), delete the related rolebinding/clusterrolebinding object.

why wouldn't we use the garbage collector controller?

**Comment by mikedanese** [comment]
Looks like that was already suggested. I can approve this once it uses the garbage collection controller.

**Comment by xilabao** [comment]
> I was expecting a pull which updated metadata.ownerReferences

> I thought we agreed on doing this as part of defaulting and not a separate controller. @deads2k suggested PrepareForCreate.

If we want to use metadata.ownerReferences in `PrepareForCreate`.  we might need to use LoopbackClientConfig to get role.UID.  Do we want to add LoopbackClientConfig for authorization  in `PrepareForCreate` ? 

> Looks like that was already suggested. I can approve this once it uses the garbage collection controller.

I agree.

Need your experience. @kargakis @deads2k @mikedanese @kubernetes/kubectl

**Pull request closed without merging**
