### PR TITLE
Fix sort-by regression

### LINKED ISSUE #71753: `kubectl get pods --sort-by` no longer sorts correctly
**What happened**:
`kubectl get pods --sort-by=.metadata.creationTimestamp` seems to have regressed and no longer sorts by creation timestamp.

**What you expected to happen**:
`kubectl get pods --sort-by=.metadata.creationTimestamp` should sort by creation timestamp.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ for i in {1..5}; kubectl create deployment foobar-$i --image=nginx; sleep 5; done
deployment.apps/foobar-1 created
deployment.apps/foobar-2 created
deployment.apps/foobar-3 created
deployment.apps/foobar-4 created
deployment.apps/foobar-5 created

$ kubectl get pods --sort-by=.metadata.creationTimestamp
NAME                        READY   STATUS    RESTARTS   AGE
foobar-1-859fd647ff-72jgp   1/1     Running   0          32s
foobar-2-89d4d78b6-4tt5h    1/1     Running   0          27s
foobar-3-8b74c8cb9-w77c9    1/1     Running   0          22s
foobar-4-5c6b995944-dmx5v   1/1     Running   0          17s
foobar-5-7f79d8957f-vghlc   1/1     Running   0          12s

$ kube delete po foobar-3-8b74c8cb9-w77c9
pod "foobar-3-8b74c8cb9-w77c9" deleted

$ kubectl get pods --sort-by=.metadata.creationTimestamp
NAME                        READY   STATUS        RESTARTS   AGE
foobar-1-859fd647ff-72jgp   1/1     Running       0          47s
foobar-2-89d4d78b6-4tt5h    1/1     Running       0          42s
foobar-4-5c6b995944-dmx5v   1/1     Running       0          32s
foobar-3-8b74c8cb9-wmr4h    1/1     Running       0          3s   <-- !!! BUG !!!
foobar-5-7f79d8957f-vghlc   1/1     Running       0          27s

$ brew switch kubectl 1.12.3
Cleaning /usr/local/Cellar/kubernetes-cli/1.13.0
Cleaning /usr/local/Cellar/kubernetes-cli/1.12.3
203 links created for /usr/local/Cellar/kubernetes-cli/1.12.3

$ kubectl get pods --sort-by=.metadata.creationTimestamp
NAME                        READY   STATUS    RESTARTS   AGE
foobar-1-859fd647ff-72jgp   1/1     Running   0          1m
foobar-2-89d4d78b6-4tt5h    1/1     Running   0          1m
foobar-4-5c6b995944-dmx5v   1/1     Running   0          51s
foobar-5-7f79d8957f-vghlc   1/1     Running   0          46s
foobar-3-8b74c8cb9-wmr4h    1/1     Running   0          22s
```

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:14:37Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-gke.18", GitCommit:"35471a6a3958f610351c67208de0f3824c4e8b3d", GitTreeState:"clean", BuildDate:"2018-11-14T05:27:44Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

* Fixes sort-by regression for table sorter introduced in https://github.com/kubernetes/kubernetes/pull/70629
* Makes table sorter behave consistently with normal sorter when fields are missing from objects
* Adds missing unit tests for TableSorter

**Which issue(s) this PR fixes**:
Fixes #71753

**Does this PR introduce a user-facing change?**:
```release-note
kubectl: fixes regression in --sort-by behavior
```

/assign @soltysh

### CODE REVIEW

**Comment by liggitt** [comment]
fixed handling of empty lists and added a covering test. PTAL

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
