### PR TITLE
Update Cluster Autoscaler to 1.13.4

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
Update Cluster Autoscaler to 1.13.4
 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.4 
 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.3
```

### CODE REVIEW

**Comment by tpepper** [comment]
Could we get a little more detail on why this version is being changed?  What does .4 bring versus prior?

Also the release note:  The commit shows a change from .2 to .4 but the release note mentions .3 and .4 which is a little strange.

**Comment by losipiuk** [comment]
> Could we get a little more detail on why this version is being changed? What does .4 bring versus prior?

The .3 updates the base docker image used for CA to mitigate security vulnerabilities and fixes some bugs in AWS/AKS cloud providers.
The .4 fixes one more bug in AWS cloud provider.

> Also the release note: The commit shows a change from .2 to .4 but the release note mentions .3 and .4 which is a little strange.

Why so? The sum of release notes for .3 and .4 is what is actually changing when when we move from CA .2 to .4.

**Comment by tpepper** [comment]
> Why so? The sum of release notes for .3 and .4 is what is actually changing when when we move from CA .2 to .4.

OOOOooooh I see what you're trying to indicate.  I take it as implied that a given point version includes content from prior point versions.  :shrug:

Security updates are definitely something for which we'd pull in an image patch version.

Please make sure the merge criteria are met and we will cherry-pick-approve.

**Comment by tpepper** [comment]
/lgtm
to make up for typo in https://github.com/kubernetes/kubernetes/pull/77065#issuecomment-486639827

**Pull request merged**
