### PR TITLE
kubeadm: tolerate whitespace when validating user CA PEMs

### LINKED ISSUE #1991: Sanitizing certificate input for proper validation required?
**What happened**:
CA validation code fails for a valid input file while trying to initialize a new cluster with an external CA by running kubeadm init.

**What you expected to happen**:
No error.

**How to reproduce it (as minimally and precisely as possible)**:
Prepare an external CA for a new cluster (https://kubernetes.io/docs/setup/best-practices/certificates/).

Create the admin certificate. Place a newline in front of the pem encoded text of your ca file (/etc/kubernetes/pki/ca.crt).  Generate admin.conf:

```
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-cluster defaul-cluster --server=https://myip:6443 --certificate-authority /etc/kubernetes/pki/ca.crt --embed-certs
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-credentials default-admin --client-key admin-certificate.key --client-certificate admin-certificate.crt --embed-certs
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-context default-system --cluster default-cluster --user default-admin
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config use-context default-system
```

Try `kubeadm init`

You will see a message like "admin.conf does not exist or is invalid". Running

`kubeadm init phase certs ca`

will give you more details:

> W1229 01:50:57.406710     684 validation.go:28] Cannot validate kube-proxy config - no validator is available
> W1229 01:50:57.406775     684 validation.go:28] Cannot validate kubelet config - no validator is available
> the admin.conf file does not exists or it is not valid: a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has got the wrong CA cert

The errors is thrown in kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go line 236 (1.17).

Removing the newline fixes the problem. The responsible code should parse the certificate and compare the certificates properties or at least compare a sanitized string version.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7.7.1908
- Kernel (e.g. `uname -a`): 3.10.0-1062.el7.x86_64
- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others: -

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

The function validateKubeConfig() can end up comparing
a user generated kubeconfig to a kubeconfig generated by kubeadm.

If a user kubeconfig has a CA that is base64 encoded with whitespace,
if said kubeconfig is loaded using clientcmd.LoadFromFile()
the CertificateAuthorityData bytes will be decoded from base64
and placed in the v1.Config raw. On the other hand a kubeconfig
generated by kubeadm will have the ca.crt parsed to a Certificate
object with whitespace ignored in the PEM input.

Make sure that validateKubeConfig() tolerates whitespace differences
when comparing CertificateAuthorityData.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1991

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: tolerate whitespace when validating certificate authority PEM data in kubeconfig files
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @fabriziopandini 
/kind bug
/priority backlog

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
for review

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
@neolit123 thanks for the PR!
Have you considered to use `bytes.TrimSpaces` so we can avoid the conversion to string?

**Comment by neolit123** [comment]
> Have you considered to use bytes.TrimSpaces so we can avoid the conversation to string?

i must have forgotten about this function. will update.

**Comment by neolit123** [comment]
updated to use `bytes.TrimSpace()`
/hold cancel

**Comment by fabriziopandini** [comment]
thanks @neolit123!
/lgtm
/approve

**Pull request merged**
