### PR TITLE
add validation for fed-apiserver and apiserver run options

### LINKED ISSUE #50552: Apiserver run options have no validation
See https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go

I think it's the last file that has no validation in pkg `k8s.io/apiserver/pkg/server/options`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Add validation for fed-apiserver and apiserver run options

**Which issue this PR fixes** 

fixes #50552

**Special notes for your reviewer**:

This is a follow-up of #50135

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@nikhiljindal approved?

**Review by tengqm — APPROVED** [review]

**Comment by m1093782566** [comment]
Thanks all :)

**Pull request merged**
