### PR TITLE
Stop supporting TRACE proxy requests

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/9893

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@smarterclayton @bgrant0607

**Comment by saad-ali** [comment]
Needs v1.0 triage

**Comment by smarterclayton** [comment]
LGTM

**Comment by saad-ali** [comment]
Marked associated issue for v1-candidate triage

**Comment by nikhiljindal** [comment]
cc @madhuri-rai07

**Comment by nikhiljindal** [comment]
@saad-ali https://github.com/GoogleCloudPlatform/kubernetes/issues/9893 was just marked v1, so this is now ready to be merged.

**Pull request merged**
