### PR TITLE
Change shippable to Go 1.4 and 1.5

### PR DESCRIPTION
**Pull request by thockin**
Let's see what happens.

Objections?

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM :-)

**Comment by resouer** [comment]
watching /sub

**Comment by mikedanese** [comment]
This needs to be accompined with workarounds for the outstanding known flakes in 1.5. See https://github.com/kubernetes/kubernetes/pull/13838#issuecomment-139822248. Also you need to switch shippable to use gimme instead of gvm.

**Comment by ashcrow** [comment]
```
go1.5 is not installed. Install it by running 'gvm install go1.5'
```

**Comment by thockin** [comment]
Use #13838 instead

**Pull request closed without merging**
