### PR TITLE
Promote three equivalence cache e2e tests to Conformance

### PR DESCRIPTION
**Pull request by akremsa**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**
Promotes the following E2E tests to Conformance:

> test/e2e/scheduling/equivalence_cache_predicates.go: "validates GeneralPredicates is properly invalidated when a pod is scheduled"
> test/e2e/scheduling/equivalence_cache_predicates.go: "validates pod affinity works properly when new replica pod is scheduled"
> test/e2e/scheduling/equivalence_cache_predicates.go: "validates pod anti-affinity works properly when new replica pod is scheduled"

These tests cover important functionality and are good to be promoted.

**Does this PR introduce a user-facing change?:**
```release-note
NONE
```

/area conformance
/area test

@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg
@kubernetes/sig-network-pr-reviews

### CODE REVIEW

**Comment by akremsa** [comment]
I signed it

**Comment by yastij** [comment]
/hold

@resouer @bsalamat - IIRC we never enabled the equivalence cache feature gate due to performance overhead right ?

**Comment by bsalamat** [comment]
As @yastij pointed, equivalence cache is not enabled and is actually removed from our code base. I don't think these tests need equivalence cache to pass. If I am not wrong, the filename is misleading and we should change it.

**Comment by bsalamat** [comment]
I took a closer look at the tests. These tests do not need equivalence cache to pass, but they check that , if equivalence cache (EC) existed, the outdated cached results would not be influencing scheduling scheduling decisions. When no EC exists, there wouldn't be any cached results and the tests pass. So, these tests are not particularly useful when equivalence cache does not exist. Since equivalence cache is removed, we should no longer promote these to conformance.

We have been thinking about adding a [different implementation](https://github.com/kubernetes/kubernetes/pull/72677)/design of the equivalence cache. Whether we should delete these tests or keep them depends on the decision to move forward with the new design or drop it.

**Comment by mgdevstack** [comment]
@kubernetes/cncf-conformance-wg Is there any centralised place other than codebase comment where we can keep these [[1](https://github.com/kubernetes/kubernetes/pull/79600#issuecomment-507460868)] important aspects about E2E and their conformance promotion notes, be documented?

Adding Conformance Doc with a Description mentioning `Candidate for Conformance: No` with reason may workout but its good keep fixed keywords, if any conformance tooling is build in near future.
```
/*
    Release : v1.16
    Testname: GeneralPredicates, invalidate
    Description: Candidate for Conformance: No
    Equivalence Class has been removed (k/k #71013) and would have redesigned implementation.
    This E2E checks that the outdated cache would not influence scheduling decision when eCache exists and test would pass when eCache doesn't exists.
*/
```

Note: _This is much needed to save other community member's effort on reanalysing E2E and things documented in Conformance perspective._ Promotion of existing E2E subset are tracked in [Conformance Efforts](https://docs.google.com/spreadsheets/d/1U9WK22vqxOeF_Ve1UhmL7woHowi0_YA1HJt_OebFBtw/edit#gid=2056506603) and many e2e are remaining because of not-simple nature as candidate for promotion.

**Comment by k82cn** [comment]
IMO, conformance test should focus on behavior instead of performance; performance enhancements, e.g. equivalence cache, are implementation binding which should not promote to conformance test :)

**Comment by johnbelamaric** [comment]
@bsalamat are these tests useful at all now or should they just be removed altogether?

@mgdevstack go ahead and create a PR (in e2e or conformance metadata description docs) to add a metadata field to indicate that a test has been considered and excluded from conformance intentionally. Just a key word like `NotConformance:` (or something better) with a description as to why should avoid extra work for people.

**Comment by bsalamat** [comment]
@johnbelamaric I tried to explain in my previous comment that these test could be useful only if we add the new implementation of the equivalence cache. In other words, they are not useful for our current code-base. I think we should remove them and add them back later if we add the new equivalence cache.

**Pull request closed without merging**
