### PR TITLE
Automated cherry pick of #75176: make describers of different versions work properly when

### PR DESCRIPTION
**Pull request by mars1024**
Cherry pick of #75176 on release-1.13.

#75176: make describers of different versions work properly when

### CODE REVIEW

**Comment by mars1024** [comment]
@yue9944882 helps for testing !

**Comment by mars1024** [comment]
ref [https://github.com/kubernetes/kubectl/issues/568](https://github.com/kubernetes/kubectl/issues/568)

/assign @soltysh

**Comment by yue9944882** [comment]
/ok-to-test
/kind bug
/assign @tpepper @aleksandra-malinowska

this pull fixes kubernetes/kubectl#568

**Pull request merged**
