### PR TITLE
Network Performance Benchmark Tests

### PR DESCRIPTION
**Pull request by girishkalele**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28136)

### CODE REVIEW

**Comment by girishkalele** [comment]
@bprashanth 

This is the old netperf tests PR rewritten in Go.

**Comment by fejta** [comment]
Assigning to @thockin and @bprashanth to delegate review

**Comment by girishkalele** [comment]
Looks like the precommit hooks on the client side are less restrictive. They all passed but then failed here in verify-govet.sh

```
SUCCESS  ./hack/../hack/verify-gofmt.sh	8s
Verifying ./hack/../hack/verify-govet.sh
test/benchmarks/netperf/launch.go:93: possible formatting directive in Println call
exit status 1
!!! Error in ./hack/../hack/verify-govet.sh:49
```

**Comment by girishkalele** [comment]
Maybe this benchmark directory belongs in the contrib repo.

**Comment by girishkalele** [comment]
cc @justinsb

**Comment by thockin** [comment]
Did this never get merged?  Oh crap...

**Comment by thockin** [comment]
@girishkalele Do you want to fix the boilerplate error and merge this?  I'm LGTM on it.

**Comment by thockin** [comment]
or I can pick it up if you're fed up with it :)

**Comment by girishkalele** [comment]
I was thinking it doesn't belong in the main repo and should be moved to its own repo.

**Comment by thockin** [comment]
Ahh, OK.  I nixed teh LGTM, then, but I don't want to see this die.

**Comment by girishkalele** [comment]
Would kubernetes-incubator be the org for the new repo ?

**Comment by thockin** [comment]
I guess so, unless we can shoehorn this in with the kubemark testing, which
I sense some distaste for...

**Comment by girishkalele** [comment]
Created new PR for this in the perf-tests repo

https://github.com/kubernetes/perf-tests/pull/1

**Pull request closed without merging**
