### PR TITLE
Rename controller issue #17648

### PR DESCRIPTION
**Pull request by ReneSaenz**
**What this PR does / why we need it**:

Rename controller pkg/registry/core/controller to pkg/registry/core/replicationcontroller
This will clarify the purpose of the controller since intent is replicationcontroller

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Please refer to 
https://github.com/kubernetes/kubernetes/issues/17648

**Special notes for your reviewer**:

NONE

**Release note**:

```none
```

### CODE REVIEW

**Comment by ReneSaenz** [comment]
@lavalamp I am still getting the message saying CLA is not signed. I already did that. Please see attachment. Am I missing something?

[CNCF_Individual_Contributor_License_Agreement.pdf](https://github.com/kubernetes/kubernetes/files/724316/CNCF_Individual_Contributor_License_Agreement.pdf)

**Comment by ncdc** [comment]
@ReneSaenz I'd recommend rebasing against master. You have 47 commits in this PR that it appears you're trying to merge, when I bet you really only have 1 😄

**Comment by ReneSaenz** [comment]
screen shot 2017-01-23 at 1 51 59 pm
screen shot 2017-01-23 at 1 52 17 pm

**Comment by ncdc** [comment]
I'm working with @ReneSaenz to fix the branch so it only has the correct commits

**Comment by lavalamp** [comment]
@ReneSaenz you've got a bunch of extra commits here that you didn't author, which is probably why the bot is upset. Usually when people send PRs that look like this it's because they e.g. started working on a release branch and sent a PR to master branch, or something like that.

**Comment by ReneSaenz** [comment]
Please refer to new PR

https://github.com/kubernetes/kubernetes/pull/40393

**Pull request closed without merging**
