### PR TITLE
Drop hack/verify-govet-levee

### LINKED ISSUE #122592: go-flow-levee is abandoned and semi-broken
Our ./hack/verify-govet-levee.sh calls github.com/google/go-flow-levee which has not been updated in years.

Importantly, it does not support generics (https://github.com/google/go-flow-levee/issues/323) which leads to a spew of warnings:

```
# k8s.io/kubernetes/test/e2e/framework
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
```

Does this tool serve any purpose today, or should we just get rid of it?

### PR DESCRIPTION
**Pull request by dims**
Fixes #122592

This verify script is no longer helpful as it does not support generics and has not been updated for a couple of years.

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
LGTM but I have no context on the actual usefulness of this tool.

**Comment by BenTheElder** [comment]
This tool was supposed to catch logging info leaks w/ data source annotations, but it's useless without https://github.com/google/go-flow-levee/issues/323 which has seen no response and the repo hasn't merged anything in 2 years now ...

+1 to drop at this point

**Pull request merged**
