### PR TITLE
endpoints: remove obsolete ServiceSelectorCache

### PR DESCRIPTION
**Pull request by howardjohn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Since https://github.com/kubernetes/kubernetes/pull/112648, we can
efficiently handle selectors from pre-existing `map[string]string`,
making the cache obsolete.

Benchmark:

```
name                         old time/op    new time/op    delta
GetPodServiceMemberships-48     189µs ± 1%     193µs ± 1%  +2.10%  (p=0.000 n=10+10)

name                         old alloc/op   new alloc/op   delta
GetPodServiceMemberships-48    59.0kB ± 0%    58.9kB ± 0%  -0.09%  (p=0.000 n=9+9)

name                         old allocs/op  new allocs/op  delta
GetPodServiceMemberships-48     1.02k ± 0%     1.02k ± 0%    ~     (all equal)
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by howardjohn** [comment]
/assign @robscott 

This is a draft since it builds on a PR that isn't yet merged due to the freeze. Once that lands I'll rebase and open this up

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by aojea** [comment]
/assign @wojtek-t 

LGTM but it may be better if someone with more historical context review

**Comment by robscott** [comment]
Thanks!

/approve

**Pull request merged**
