### PR TITLE
Replica set is enabled by default now, so it is not necessary to explicitly enable it in the test config script.

### PR DESCRIPTION
**Pull request by madhusudancs**
This PR is based on #21130. Only last commit needs review here.

cc @bgrant0607 @janetkuo @kargakis

### CODE REVIEW

**Comment by bgrant0607** [comment]
Why does this include all the other commits?

**Comment by madhusudancs** [comment]
> Why does this include all the other commits?

@bgrant0607 I included them intentionally to (semi-)enforce merge order. I was in a dilemma. If this PR merges before the other PRs on which it pseudo-depends (#20517 and #21130), when we look at the commit in this PR in the future it will look weird because it removes replica set line and the associated comment. If we don't remove that comment here, we might leave it hanging and forget to remove it.

But anyway, removed the dependencies. PTAL.

**Comment by bgrant0607** [comment]
LGTM

**Comment by madhusudancs** [comment]
@k8s-bot test this issue: #20923

**Comment by madhusudancs** [comment]
@k8s-bot test this issue: #18708

**Comment by madhusudancs** [comment]
@k8s-bot test this issue: #21188

**Comment by madhusudancs** [comment]
Just rebased, adding LGTM back.

**Comment by bgrant0607** [comment]
This was done by #21130

**Pull request closed without merging**
