### PR TITLE
Fixes issue #18721 by introducing longer period for lost pod polling

### LINKED ISSUE #18721: two very different uses for containerPollTime in Mesos executor.go
In contrib/mesos/pkg/executor/executor.go, there is a local constant named containerPollTime that is put to two very different uses --- waiting for a pod to come up, and recovering from pods getting "lost".  The former needs to be very responsive, but the latter does not (but is still costly when the number of pods grows).  The value is currently set to one second, and that makes both things happen frequently.  It would be better if there were two different constants, so the monitoring for lost pods can be less frequent.

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
Fixes #18721

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
There seems to be some confusion between my Google accounts.  I have one based on my IBM email address, and another based on my gmail address (which is the first one I created and the one that is chosen automatically in circumstance I can not find how to control).  Can somebody please tell me how to untangle this mess?  My Google account based on my IBM email is in https://groups.google.com/forum/#!forum/ibm-kubernetes-contributors, and my IBM email is in my github.com account.  Yes, you see above, the proper connection was not made.

**Comment by MikeSpreitzer** [comment]
This is to resolve issue #18721

**Comment by ncdc** [comment]
FYI if you want this PR to automatically close 18721 when it's merged, you'll need to put something like "Fixes ..." in the description, instead of a comment

**Comment by MikeSpreitzer** [comment]
A little more piontedly: my company has signed the CLA and put my work email address (mspreitz@us.ibm.com) in its list of authorized contributors.  So there *should* not be a CLA problem.  I do not know why googlebot is complaining about the CLA.  The email address listed in https://patch-diff.githubusercontent.com/raw/kubernetes/kubernetes/pull/18906.patch is the email address on my company's list of authorized contributors (https://groups.google.com/forum/#!forum/ibm-kubernetes-contributors).  Can somebody please explain how to remove this confusion and avoid it in the future?

**Comment by jdef** [comment]
lgtm

**Comment by jdef** [comment]
thanks for the PR! please squash and re-push

**Comment by jdef** [comment]
to resolve your CLA issue: squash and amend the single resulting commit w/ the email that applies to the CLA that was signed.

**Comment by MikeSpreitzer** [comment]
@jdef: I am trying to do as you suggested, but I am not sure I understand precisely what you are suggesting.  What do you mean by "squash and amend the single resulting commit", and how do I control the email address involved?  I have had `user.email=mspreitz@us.ibm.com` in my git config from the start.

**Comment by jdef** [comment]
well something changed, the google CLA bot is happy again. not sure what happened. if you squash this I'll get it merged.

**Comment by MikeSpreitzer** [comment]
Now the problem is only "Submit Queue — Github CI tests are not green".  How do I find out which tests are not green and why?

**Comment by MikeSpreitzer** [comment]
BTW, I am not yet familiar with the development process here. What are the exact steps to do the sort of squash mentioned above?

**Comment by jdef** [comment]
squashing git commits, e.g. https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jdef** [comment]
@k8s-bot ok to test

**Comment by MikeSpreitzer** [comment]
Regarding that squashing: sorry I am still missing something.  I got the message --- from that blog post, the git documentation, and common sense --- that I do not want to squash out a commit that has been shared.  So I am not clear on what you are suggesting I squash with what.  Are you just trying to suggest a rebase on HEAD?

**Comment by MikeSpreitzer** [comment]
Also, I just noticed that the mysterious "Github CI tests are not green" is counted as pending rather than failed, so I suppose waiting is the right course of action for that one.

**Comment by jdef** [comment]
you have multiple commits in this PR. they should be squashed into a single
commit prior to merge. there are few exceptions to this rule (e.g. godeps
changes go into their own commit). you'll have to force-push after
squashing your two commits into a single commit - that's ok, just how
things are done here.

**Comment by MikeSpreitzer** [comment]
I have done the squash (i.e., a rebase -i onto the base commit).  How exactly do i do the force-push in this case?

**Comment by jdef** [comment]
usually something like `git push --force <remote-name> <branch-name>`

e.g. `git push --force origin my-feature-branch`

**Comment by jdef** [comment]
@k8s-bot test this please

**Comment by MikeSpreitzer** [comment]
Yes, I have gotten false failures from that same test in the past.

**Comment by jdef** [comment]
failing e2e test is unrelated

**Pull request merged**
