### PR TITLE
client-go: allow insecure oidc auth provider

### PR DESCRIPTION
**Pull request by hunshcn**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

support insecure oidc auth provider

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by enj** [comment]
/hold

We will not support any form of insecure TLS configuration with OIDC on the client or server.

xref #88449

**Comment by hunshcn** [comment]
My mistake, I didn't find this related issue, close it.

**Pull request closed without merging**
