### PR TITLE
Ensure panic_on_oom disabled

### PR DESCRIPTION
**Pull request by dchen1107**
cc/ @derekwaynecarr  @vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM. @dchen1107 I was told to use the cherrypick script for changes against the release branch - `hack/cherry_pick_pull.sh`

**Comment by dchen1107** [comment]
@vishh That is exact what I had done here.

**Comment by vishh** [comment]
Hmm. That script adds a `Automated cherry pick of` prefix in the subject.
Sorry for the noise!

**Comment by zmerlynn** [comment]
@vishh: The `hub` command probably bailed and she hallucinated the rest. (Probably an invalid `push` URL? Or she hasn't updated and it's the password bug I just fixed. But the branch name is correct.)

**Comment by vishh** [comment]
I wonder if 2-factor auth was the roadblock here. Our script does not
mention how to handle 2-factor auth explicitly.

**Comment by zmerlynn** [comment]
I should have fixed hub auth in #15497. People changing their push URLs are another story, though.

**Pull request merged**
