### PR TITLE
Enhancement: Add custom GPU Manager runtime

### PR DESCRIPTION
**Pull request by mYmNeo**
Signed-off-by: thomassong <thomassong@tencent.com>

**What this PR does / why we need it**:
The current code base about GPU management is kind of simple, it's not topology awareness. So we want to introduce a runtime like CRI, to enhance the GPU Manager.This PR, I think, is a part of [proposal V1](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/gpu-support.md)

### CODE REVIEW

**Comment by mYmNeo** [comment]
ping @vishh, some ideas?

**Comment by cmluciano** [comment]
I think we should halt on this until after the Node f2f next week. This changes solidifies an API that does not have consensus.

**Comment by mYmNeo** [comment]
@cmluciano , yes, I've been waiting for the API for a long time. And I'm looking forward to hearing the results.:smiley:

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by vishh** [comment]
The kubernetes community met from 5/1-5/3 to identify a long term strategy for handling GPUs, topology, drivers, runtimes, etc. I'd expect design docs to be published in the v1.8 timeline based on discussions from that meeting. 
Adding a special runtime for GPUs was not the solution that was identified. So, I will suggest closing this PR for now until a more formal system design is posted for integrating nvidia GPUs.

**Comment by mYmNeo** [comment]
@vishh, SGTM, I'll close this PR and look forward to the final design.:smile:

**Pull request closed without merging**
