### PR TITLE
Small fix to remove dependency on internal version of resource

### PR DESCRIPTION
**Pull request by seans3**
* Removes dependency on internal version of resource

Helps address:
  1) [Umbrella Issue: Remove kubectl dependencies on kubernetes/kubernetes](https://github.com/kubernetes/kubectl/issues/80)
  2) [Remove Kubectl dependencies on kubernetes/pkg/api and kubernetes/pkg/apis](https://github.com/kubernetes/kubectl/issues/83)

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by juanvallejo — APPROVED** [review]

**Comment by soltysh** [comment]
This actually ensure this command works at all, previously it could not due to the check that's performed in `logsForObjectWithClient` which expects the options to be `corev1.PodLogOptions`. Bumping priority.

**Pull request merged**
