### PR TITLE
Automated cherry pick of #29139

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #29139 on release-1.3.

### CODE REVIEW

**Comment by adityakali** [comment]
LGTM. Thanks!

**Comment by fabioy** [comment]
@bprashanth Could you rebase this? Thanks.

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this

**Comment by fabioy** [comment]
@bprashanth NVM about the rebase -- misread the checks. Thanks.

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this, issue #IGNORE

**Comment by zmerlynn** [comment]
Adding retest-not-required after SQ reboot.

**Pull request merged**
