### PR TITLE
Automated cherry pick of #16746

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #16746 on release-1.1.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
cc @brendandburns

**Comment by roberthbailey** [comment]
LGTM.

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
Closing this in favor of #16864 to pick up all (I think) needed e2e changes for 1.1

**Pull request closed without merging**
