### PR TITLE
Wordpress Example: clarify GCE zone

### LINKED ISSUE #8825: Clarify origin of $ZONE in MySQL Wordpress PD example
Example talks about the definition of $ZONE, but doesn't clarify where the default comes from or how to find it via querying your project. This can significantly slow down the execution of the example.

Suggestion: link to the [default file for GCE](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/config-default.sh)

### PR DESCRIPTION
**Pull request by jeffmendoza**
Fixes  #8825

### CODE REVIEW

**Comment by jeffmendoza** [comment]
oops, editing in github is using a different email

**Comment by jeffmendoza** [comment]
yep, will do

**Comment by jeffmendoza** [comment]
@krousey updated =)

**Comment by krousey** [comment]
LGTM

**Pull request merged**
