### PR TITLE
use subtest for table units (pkg/scheduler/*)

### PR DESCRIPTION
**Pull request by eloyekunle**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update scheduler's unit table tests to use subtest

**Special notes for your reviewer**:
Original Issue: #63267

Packages:
- `pkg/scheduler/algorithmprovider/defaults`
- `pkg/scheduler/internal/cache`
- `pkg/scheduler/api/compatibility`
- `pkg/scheduler/util`
- `pkg/scheduler/nodeinfo`

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@eloyekunle Can you move the changes of #81357 into this one? Basically, we don't need multiples PRs for similar cleanups.

And could you do a thorough search to include other cases here?

/ok-to-test

**Comment by eloyekunle** [comment]
Okay. As it stands now, there are 5 open PRs for 5 packages. I'll merge them all into this one later today.

**Comment by eloyekunle** [comment]
@Huang-Wei I have merged the PRs into this.

**Review by Huang-Wei — COMMENTED** [review]
My bad. Not sure why the pending comments weren't sent out. Some nits:

**Pull request closed without merging**
