### PR TITLE
Store validating admission as beta

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Switches the storage version for validating admission policies / bindings to beta. This should have happened when the feature was promoted to beta, but got missed.

This PR also updates the etcd data test to catch this in the future (if a non-alpha version is available, expect the storage version to be non-alpha).

#### Does this PR introduce a user-facing change?
```release-note
ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding objects are persisted in etcd using the v1beta1 version. Remove alpha objects or disable the alpha ValidatingAdmissionPolicy feature in a 1.27 server before upgrading to a 1.28 server with the beta feature and API enabled.
```

cc @jpbetz @cici37

### CODE REVIEW

**Comment by liggitt** [comment]
I think we should pick this back to 1.28.1 to minimize alpha data we persist while the feature is in beta

**Comment by jpbetz** [comment]
/lgtm
/approve
Thanks for improving the detection and messaging!

**Comment by jpbetz** [comment]
I support backporting this to 1.28.1

**Comment by jiahuif** [comment]
cc @cici37 
/triage accepted

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/119723 flake
/retest

**Comment by alexzielenski** [comment]
This change was in the original beta promotion PR but was reverted due to comment during review concerned with rollback:

https://github.com/kubernetes/kubernetes/pull/118644#discussion_r1258879310

**Comment by liggitt** [comment]
> This change was in the original beta promotion PR but was reverted due to comment during review concerned with upgrade interactions:
> 
> [#118644 (comment)](https://github.com/kubernetes/kubernetes/pull/118644#discussion_r1258879310)

Hmm... storing alpha data in etcd for a beta feature is unfortunate. It means that someone who never enabled the alpha would still be exposed to alpha data and reliance on alpha types. It's not *as* big a deal since the beta API is not enabled by default, so maybe we can limit this change to master and not backport it.

**Pull request merged**
