### PR TITLE
Move pkg/kubectl/util to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/util/*.go` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @BenTheElder 

for `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/approve

**Pull request merged**
