### PR TITLE
Move tnozicka to SIG-Apps emeritus

### PR DESCRIPTION
**Pull request by tnozicka**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
I've switched jobs and and I am no longer able to dedicate the time for reviews and contributions in the extent expected of SIG-Apps approvers.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

/assign @soltysh @kow3ns @janetkuo
/sig apps

It was great working with you all :wave:

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/lgtm
/approve

Thanks @tnozicka!

**Comment by soltysh** [comment]
Thanks a ton Tomas :1st_place_medal: 
/assign @thockin 
for approval

**Review by thockin — COMMENTED** [review]
/approve

**Pull request merged**
