### PR TITLE
Include API calls in apiserver logs for tests

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/62468

/cc @wojtek-t 

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
/hold
Until I verify from the presubmit that this works.

**Comment by shyamjvs** [comment]
Ok, that seems to work - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/62535/pull-kubernetes-e2e-gce-100-performance/1439/artifacts/e2e-1439-8af947-master/kube-apiserver.log

/hold cancel
@wojtek-t Could you lgtm?

**Comment by shyamjvs** [comment]
Btw - from the apiserver flags also, it's clear the config is WAI:

```
I0413 12:10:40.686895       1 flags.go:27] FLAG: --v="2"
I0413 12:10:40.686917       1 flags.go:27] FLAG: --vmodule="httplog=3"
```

**Comment by shyamjvs** [comment]
cc @kubernetes/test-infra-maintainers @krzyzacy @BenTheElder 

Wojtek points that there seems to be sth wrong with the bot as it's not approving the above PR even though he is a root-level owner of the repo.
Could one of you PTAL why the behavior changed?

**Comment by shyamjvs** [comment]
For now, I manually added the label.

**Comment by cjwagner** [comment]
@shyamjvs The root level OWNERS file is currently broken. The YAML is invalid and can't be parsed. The fix is here: https://github.com/kubernetes/kubernetes/pull/62555

**Pull request merged**
