### PR TITLE
Fix wrong command in e2e agnhost utility function

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

The `Command` will cause the container process not starting correctly,
so we now use the `Args` to end up running `/agnhost pause` as intended.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

Fixes the failing e2e test in CRI-O: https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/cri-o_cri-o/2759/test_pull_request_crio_e2e_fedora/6861/#kubernetes-e2e-suite-sig-network-services-should-preserve-source-pod-ip-for-traffic-thru-service-cluster-ip-linuxonly

If you wonder why it does not fail on docker, that's because the test does not report the error correctly but fails the same way.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mrunalp** [comment]
Thanks! This is breaking cri-o e2e CI.

**Comment by derekwaynecarr** [comment]
/milestone v1.16

This is needed to pass runtime testing.

**Comment by liggitt** [comment]
> the test does not report the error correctly but fails the same way.

Should the test be fixed as a follow up to report correctly so we know it works in master blocking jobs?

**Comment by saiyan86** [comment]
@saschagrunert thx for the fix!

**Pull request merged**
