### PR TITLE
add prerelease lifecycle tags to storage.k8s.io

### PR DESCRIPTION
**Pull request by deads2k**
This adds the lifecycle annotation tags matching https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/1635-prevent-permabeta/README.md 

The clock is set for removal of beta levels in 1.22.  The v1 APIs have been around beyond the compatibility window for kubelets.

/kind cleanup
/kind deprecation
/priority important-soon
@kubernetes/sig-storage-api-reviews 

```release-note
storage.k8s.io/v1beta1 is deprecated in favor of storage.k8s.io/v1
```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm

Side question, should we clean up v1alpha as well?

**Comment by deads2k** [comment]
> /lgtm
> 
> Side question, should we clean up v1alpha as well?

The enhancement only covers beta cleanup.  There were comments about alpha levels as well, but since alpha levels are opt-in, most alpha APIs end up unserved by default.

**Pull request merged**
