### PR TITLE
Automated cherry pick of #38167

### PR DESCRIPTION
**Pull request by ericchiang**
Cherry pick of #38167 on release-1.5.

#38167: rework oidc client auth provider

### CODE REVIEW

**Comment by ericchiang** [comment]
I've gone ahead and added release notes to the original PR.

**Comment by liggitt** [comment]
LGTM
to @saad-ali for cherrypick approval

**Comment by calebamiles** [comment]
@saad-ali this is a 1.5 cherry pick candidate to pick up.

**Comment by saad-ali** [comment]
@k8s-bot cri e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cri node e2e test this

**Pull request merged**
