### PR TITLE
Remove unnecessary if judgment braces

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

This PR removes unnecessary braces.

```go
if currentReadyCondition == nil { ..
    continue
}
if currentReadyCondition != nil { .. // to remove
}
```

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yastij** [comment]
cc @jhorwit2 @wlan0

**Comment by yue9944882** [comment]
/meow

A polite bump in this thread

**Pull request closed without merging**
