### PR TITLE
Automated cherry pick of #32926

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #32926 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33118)

### CODE REVIEW

**Comment by vishh** [comment]
cc @fabioy @dchen1107

**Comment by fabioy** [comment]
@k8s-bot gce e2e test this

**Comment by dchen1107** [comment]
The builds failed with the error:
```
# k8s.io/kubernetes/test/e2e_node
test/e2e_node/kubelet_test.go:85: undefined: uuid in uuid.NewUUID
test/e2e_node/kubelet_test.go:86: undefined: podClient in podClient.Create
test/e2e_node/kubelet_test.go:106: undefined: podClient in podClient.Get
test/e2e_node/kubelet_test.go:125: undefined: podClient in podClient.Delete
```

The node e2e test infrastructure has a lot of refactory, you might have to fix the test separately.

**Comment by fabioy** [comment]
@vissh Can you take a look at the failed tests? Thanks.

**Comment by fabioy** [comment]
@vishh Argh, wrong alias. Vish, could you take a look at the failed tests? Thanks.

**Comment by vishh** [comment]
@fabioy Yeah. This PR fell through the cracks. I will wrap it in a couple of hours. Thanks for the reminder.

**Comment by vishh** [comment]
Fixed this patch. Tested manually. 

```sh
root@kubernetes-minion-group-357a:/home/vishnuk# grep . /proc/`pidof kubelet`/oom*
/proc/3525/oom_adj:-16
/proc/3525/oom_score:0
/proc/3525/oom_score_adj:-999
root@kubernetes-minion-group-357a:/home/vishnuk# grep . /proc/`pidof docker`/oom*
/proc/3216/oom_adj:-16
/proc/3216/oom_score:0
/proc/3216/oom_score_adj:-999
root@kubernetes-minion-group-357a:/home/vishnuk# kubelet --version
Kubernetes v1.3.8-beta.0.16+6bf6cbb5e657af-dirty
root@kubernetes-minion-group-357a:/home/vishnuk# grep . /proc/`pidof docker-containerd`/oom*
/proc/3222/oom_adj:-16
/proc/3222/oom_score:0
/proc/3222/oom_score_adj:-999
```

**Comment by fabioy** [comment]
@k8s-bot gke e2e test this

**Comment by fabioy** [comment]
@k8s-bot gci gce e2e test this

**Comment by fabioy** [comment]
@k8s-bot kubemark e2e test this

**Comment by fabioy** [comment]
@k8s-bot kubemark gci e2e test this

**Comment by fabioy** [comment]
@vishh Can you take a look at the GCI test failures? (Are they new?)

**Pull request merged**
