### PR TITLE
Make scheduler to watch PodSpec.Host instead Status.Host

### PR DESCRIPTION
**Pull request by wojtek-t**
This is part of #5207.

cc @jszczepkowski @bgrant0607

### CODE REVIEW

**Comment by wojtek-t** [comment]
I've run e2e tests, however 3 of them are currently failing in head - so please do NOT merge this PR before they are fixed and I will rerun e2e tests.

**Comment by bgrant0607** [comment]
Please rebase and try e2e again.

**Comment by wojtek-t** [comment]
Running now - will paste results when finished.

**Comment by wojtek-t** [comment]
e2e tests passed:

Ran 25 of 26 Specs in 1402.894 seconds
SUCCESS! -- 25 Passed | 0 Failed | 1 Pending | 0 Skipped I0312 16:02:11.729263   27014 driver.go:89] All tests pass

**Comment by jszczepkowski** [comment]
It seems that PR also addresses watching Spec.Host in kubelet, as getHostFieldLabel method is used by  apiserver watch.

**Comment by bgrant0607** [comment]
LGTM.

**Pull request merged**
