### PR TITLE
Bump sample-apiserver to latest version (1.29.1)

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Bump sample-apiserver to latest version (1.29.1). Allows us to build and test with the latest image.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mkumatag** [comment]
post submit job failed to push this image, log [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-sample-apiserver-test-images/1754983111487131648?rerun=gh_redirect), retriggered the job, lets see how it goes.

**Comment by Jefftree** [comment]
It seems like all the runs have failed, unsure of what the problem is

**Comment by Jefftree** [comment]
@mkumatag I noticed you have access to the gcr.io/k8s-staging-e2e-test-images cloud build logs (https://github.com/kubernetes/k8s.io/blob/0687d1c2858e7d9fcdbad8a4f53668f8f602b88a/groups/sig-testing/groups.yaml#L53), would you be able to see what went wrong in the logs?

**Comment by mkumatag** [comment]
> post submit job failed to push this image, log [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-sample-apiserver-test-images/1754983111487131648?rerun=gh_redirect), retriggered the job, lets see how it goes.

@Jefftree you can see those logs here, error is not that clear! unfortunately its failing for every image :(

**Pull request merged**
