### PR TITLE
Fix Daemonset controller role missing 'update pod' permission

### PR DESCRIPTION
**Pull request by Shuanglu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Adds an `update` permission for the `pod` resource to the daemon-set-controller cluster role when below is invoked.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/update.go#L375
#### Which issue(s) this PR fixes:

Fixes # N/A

#### Special notes for your reviewer:
In KCM, there was error 
*daemon_controller.go:320] kube-system/calico-node failed with : failed to construct revisions of DaemonSet: pods "xxxx" is forbidden: User "system:serviceaccount:kube-system:daemon-set-controller" cannot update resource "pods" in API group "" in the namespace "kube-system"*
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/cc
How to reproduce this problem?

**Comment by Shuanglu** [comment]
> /cc
> How to reproduce this problem?

I didn't find an approach to reproduce the error. When we noticed the issue, we found the DS didn't create the pod on new nodes and found the error message from KCM. After we following the error message to mitigate the issue, we noticed all existing pods were updated and one controllerrevision which has different 'controller-revision-hash' value was deleted

**Comment by Shuanglu** [comment]
Update: this looks like related with "velero". when the "velero" restores something, it creates ds and the "controllerrevision" as well which is different from the new "controllerrevision" dsc creates.

My concern is that as the dsc has such mechanism to cleanup the controllerrevision it should be granted the permission it requires.

**Pull request closed without merging**
