### PR TITLE
Vendor in k8s.io/utils Changes

### PR DESCRIPTION
**Pull request by RaghavRoy145**
Signed-off-by: Raghav Roy <raghavroy145@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Vendors in k8s.io/utils upto changes made by https://github.com/kubernetes/utils/pull/235
#### Does this PR introduce a user-facing change?

```release-note
[k8s.io/utils/clock]: IntervalClock is now deprecated in favour of SimpleIntervalClock
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
Thanks @RaghavRoy145 ❤️ 
@MikeSpreitzer - fyi

**Comment by dims** [comment]
/approve
/lgtm

when CI jobs are green please assign to @\liggitt or @\thockin

**Pull request merged**
