### PR TITLE
the lockfile should be handled after function return

### PR DESCRIPTION
**Pull request by guangxuli**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32559)

### CODE REVIEW

**Comment by guangxuli** [comment]
@dchen1107 PTAL,thanks.

**Comment by guangxuli** [comment]
@dchen1107 can you take a look for this PR? thanks.

**Comment by dchen1107** [comment]
@k8s-bot ok to test

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
