### PR TITLE
cmd/kubelet: replace KEP link with the documentation one as it is available now

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
cmd/kubelet: replace KEP link with the documentation one as it is available now

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/kind documentation
/priority backlog
/triage accepted
/lgtm

**Comment by SataQiu** [comment]
Hi @thockin 
This is just a small documentation patch. Could you help take a look and approve it?

**Pull request merged**
