### PR TITLE
kube-proxy-test: fix goroutine leak

### PR DESCRIPTION
**Pull request by gaurav1086**
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
the channel errch need to be buffered to prevent the goroutine in from hanging indefinitely
when the select statement reads something other than the one the goroutine sends on. i.e. timeouts
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
xref: #5316
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
I think we can merge this ?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
