### PR TITLE
Allow resource.Builder commands to take arguments by type/name

### LINKED ISSUE #5579: Enhance kubectl return messages.
When I was using kubectl commands, I found whether I'm using `create` or `delete`, they return same message, that is only the pod id.  I think we can enhance the messages to provide more information to users.

### PR DESCRIPTION
**Pull request by smarterclayton**
Will allow xarg behavior to fetch resources across multiple types.

Fixes #5579 and follow up to #1905

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
$ kubectl create -f examples/walkthrough/
pods/pod-with-healthcheck
pods/www
pods/storage
replicationControllers/nginx-controller
services/nginx-example
```

**Comment by smarterclayton** [comment]
Ready for review.

**Comment by smarterclayton** [comment]
Added actual tests this time.

**Comment by bprashanth** [comment]
I'm not really the kubectl goto but reading through https://github.com/GoogleCloudPlatform/kubernetes/issues/5579 this LGTM. @jlowdermilk might have more thoughts. Maybe add a test into test-cmd?

**Comment by jlowdermilk** [comment]
LGTM. Pretty please add a test or two to [hack/test-cmd.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/test-cmd.sh) to exercise `kubectl get resource/name`?

**Comment by smarterclayton** [comment]
Yeah, found a nasty bug in resource builder while adding tests.  Should be ready soon.

----- Original Message -----

**Comment by smarterclayton** [comment]
Ready with more tests.

----- Original Message -----

**Comment by smarterclayton** [comment]
One passed, one failed with what *might* come from https://github.com/GoogleCloudPlatform/kubernetes/pull/5687

**Comment by smarterclayton** [comment]
Trap is green.

**Comment by smarterclayton** [comment]
Rerunning travis then will merge (unless anyone has any other comments)

**Pull request merged**
