### PR TITLE
Fix list-features script

### PR DESCRIPTION
**Pull request by liggitt**
Find features in nested test directories and run on OS X as well as linux

### CODE REVIEW

**Comment by eparis** [comment]
/lgtm
I never trust that bash on mac supports things like `**` but jordan says it is working for him.

**Comment by liggitt** [comment]
> I never trust that bash on mac supports things like ** but jordan says it is working for him.

```sh
$ /bin/bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

$ hack/list-feature-tests.sh 
[Feature:Audit]
[Feature:ClusterAutoscalerScalability1]
[Feature:ClusterAutoscalerScalability2]
[Feature:ClusterAutoscalerScalability3]
[Feature:ClusterAutoscalerScalability4]
[Feature:ClusterAutoscalerScalability5]
[Feature:ClusterAutoscalerScalability6]
[Feature:ClusterDowngrade]
[Feature:ClusterSizeAutoscalingScaleDown]
[Feature:ClusterSizeAutoscalingScaleUp]
[Feature:ClusterUpgrade]
[Feature:ComprehensiveNamespaceDraining]
[Feature:Downgrade]
[Feature:Empty]
[Feature:EtcdUpgrade]
[Feature:ExperimentalResourceUsageTracking]
[Feature:FSGroup]
[Feature:FlexVolume]
[Feature:GPU]
[Feature:HAMaster]
[Feature:Ingress]
[Feature:Initializers]
[Feature:LabelSelector]
[Feature:LocalPersistentVolumes]
[Feature:MasterUpgrade]
[Feature:NetworkPolicy]
[Feature:NoSNAT]
[Feature:NodeAuthorizer]
[Feature:NodeUpgrade]
[Feature:OpaqueResources]
[Feature:Reboot]
[Feature:ReclaimPolicy]
[Feature:Seccomp]
[Feature:SecurityContext]
[Feature:ServiceLoadBalancer]
[Feature:StatefulSet]
[Feature:StatefulUpgrade]
[Feature:Upgrade]
[Feature:Volumes]

```

**Pull request merged**
