### PR TITLE
kubelet: move all api.Node related methods to a separate file

### PR DESCRIPTION
**Pull request by yujuhong**
The methods for registering a node and syncing node status to the apiserver
have grown large enough that it makes sense for them to live in a separate
place. This change adds a nodeManager to handle such interaction with the
apiserver.

Also move node-watching and GetNodes() methods to nodeManager.

### CODE REVIEW

**Comment by yujuhong** [comment]
There are way too many lines of code in kubelet. I wanted to move something out and "node status" related methods seem isolated enough. This should improve both readability and testability.
No real functional change. Unit tests are migrated and adapted to use the new components.

@kubernetes/goog-node for suggestions/objections.

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
@vishh, @dchen1107, anyone wants to review?

**Comment by dchen1107** [comment]
Ok, I am taking this one.

**Comment by dchen1107** [comment]
LGTM. Thanks for cleanup the code.

**Comment by thockin** [comment]
I suspect this PR might be contributing to flakiness in e2e tests.

See kubekins kubernetes-e2e-gce/8540

I'm sort of grasping, but this PR went in a few hours before the first such failure, and the failure is intermittent with hours of success between flakes.  I'm considering a rollback of this PR.

**Comment by thockin** [comment]
This would have to be a manual rollback, I'll see if I can piece it together later today

**Comment by quinton-hoole** [comment]
As per email thread (copied below), I agree @thockin 

=== snip snip ==

Q


On Sat, Sep 19, 2015 at 9:37 AM, Quinton Hoole <quinton@google.com> wrote:
Yup, I think you may be right.  Good sleuthing!

Also beware that between:
job/kubernetes-e2e-gce/8515/
and
job/kubernetes-e2e-gce/8519/
inclusive, all tests were being accidentally skipped (due to a bug I introduced and then fixed in #14141 )

So you should ignore all those green dots - they're completely bogus.

Q

=========

OK, having stared at Jenkins a bit more I'm fairly confident that you're right Tim.  What I suggest is:

1. Roll back https://github.com/kubernetes/kubernetes/pull/14090 .  That's the PR merged at http://kubekins.dls.corp.google.com/job/kubernetes-build/4832/

2. If that gets rid of all of the "Not ready nodes" errors for say 10  runs, consider rolling back https://github.com/kubernetes/kubernetes/pull/14218 (i.e. rolling forward #13417, that we rolled back last night, potentially in error).

It's not yet clear to me whether or not both of the above PR's might in fact be at fault.  There definitely seems to be data to suggest that rolling back #13417 reduced the error rate in e2e-gce-parallel very substantially.

Quinton

**Pull request merged**
