### PR TITLE
Remove unused func in pkg k8s.io/pkg/kubelet/cm

### PR DESCRIPTION
**Pull request by surajssd**
This commit removes the function getDockerAPIVersion which is not
exported neither used anywhere.

```release-note
NONE
```

### CODE REVIEW

**Comment by surajssd** [comment]
@pmorie how do I fix this test, it seems to be failing always!

**Comment by surajssd** [comment]
Finally all tests passed!

@sjpotter can you PTAL ?

**Comment by surajssd** [comment]
@pmorie can you PTAL ?

**Comment by surajssd** [comment]
@pmorie can you PTAL ?

**Comment by surajssd** [comment]
@vishh can you also add `/approve no-issue` ?

**Comment by BenTheElder** [comment]
cross is broken due to #56002, it won't pass until #56003 is in.

**Comment by surajssd** [comment]
ping @vishh

**Pull request closed without merging**
