### PR TITLE
Use runtime.NumCPU() instead of a fixed value for parallel scheduler threads

### PR DESCRIPTION
**Pull request by bsalamat**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Uses the same number of parallel threads as the number of available cores. This should give us a slight performance benefit in larger clusters which use large machines with many cores for their master nodes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/sig scheduling
/priority important-longterm

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bsalamat** [comment]
There are some data races which are not caused by this change. I am trying to address them in #73943.

**Comment by wgliang** [comment]
Emm... I don't really agree with this, I have previously discussed the related issue #59460. We will have performance loss on machines with less number of CPU  if the default use runtime.NumCPU(). 

`This should give us a slight performance benefit in larger clusters which use large machines with many cores for their master nodes.` But it also brings uncertainty.

If we want to achieve this effect, I prefer the scheduler to have the ability to adjust itself, for example, 16 by default, if runtime.NumCPU()>16 uses runtime.NumCPU().

**Comment by wgliang** [comment]
In addition, I once found that setting runtime.NumCPU()*2+4 in a production environment can get better performance than runtime.NumCPU().

**Comment by bsalamat** [comment]
@wgliang My own past experience, plus a bunch of other research works, show that it is hard to find a single formula for the number of parallel threads based on the number of available CPU cores. The best number of threads depends on the workload (I/O heavy, memory heavy, lock contentions, etc) and also the number of cores, amount of cache, cache pollution, and memory bandwidth to name a few.
So, I don't think that `NumCPU() * 2 + 4` is necessarily the best formula. I am pretty sure it won't work well for machines which have a large number of cores (say a 96 core machine).
I think the best is to use the same number as the number of cores plus a small fixed number. WDYT?

**Comment by wgliang** [comment]
> So, I don't think that `NumCPU() * 2 + 4` is necessarily the best formula.

Yes, `NumCPU() * 2 + 4 `is just the conclusion I got in a certain scenario, it is not representative and versatile. I want to explain that NumCPU() is not necessarily the best default value.

> I think the best is to use the same number as the number of cores plus a small fixed number.

Looks like a viable option.

**Comment by wgliang** [comment]
In addition, I think we'd better have the performance data comparison before and after the change as the basis for our changes. :)

**Comment by bsalamat** [comment]
> And will we consider exposing it to the user as an optional parameter?

No, not really. If only 0.1% of the users understand what a config option does and even those 0.1% prefer not to change the option, then the config option shouldn't exist. That's my opinion, of course. I feel this would have been such a config option and as a result shouldn't exist. Instead, we should use a value that works best in almost all cases.

> In addition, I think we'd better have the performance data comparison before and after the change as the basis for our changes.

I totally agree. The only problem is that my own dev machine has 12 cores. The effect of this change should be much more visible on machines that have more than 16 cores, ideally larger than 24 cores to make a bigger difference. If I find such a machine, I will try to run the benchmarks and will send results, but at this point I am not so optimistic that I will find such a machine soon.

**Comment by denkensk** [comment]
@bsalamat  I recently borrowed a 40-core machine, and I think I can help you with the performance data comparison this weekend. ^_^

**Comment by bsalamat** [comment]
@denkensk That would be great! Thanks!

**Comment by denkensk** [comment]
It‘s the data comparison with a 40-core machine. I hope these data will help you. @bsalamat 

BenchmarkScheduling/5000Nodes/1000Pods-40  10000

parallel-scheduler-threads
16                        12952500 ns/op
24                        12933301 ns/op
30                        12534872 ns/op
32                        12105945 ns/op
36                        12002382 ns/op（Best）
runtime.NumCPU()        12274877 ns/op
runtime.NumCPU()*2        12763429 ns/op
runtime.NumCPU()*2+4    12741054 ns/op
runtime.NumCPU()*3        12859483 ns/op
runtime.NumCPU()*4        13240901 ns/op

**Comment by wgliang** [comment]
@denkensk Cool,thanks. It seems that the performance improvement is small.

**Comment by wgliang** [comment]
@denkensk Cool,thanks. It seems that the performance improvement is small.

**Comment by bsalamat** [comment]
Thanks, @denkensk for running the benchmarks with various configurations.
According to the results, using `NumCPU()` threads vs 16 threads (which is what the scheduler uses today) improves performance by 5%. 5% is not a large improvement, but given that we can achieve it by a trivial change, I think we should take advantage of it.

**Comment by wgliang** [comment]
@bsalamat I noticed that the CI test shows the presence of a DATA RACE.
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73934/pull-kubernetes-bazel-test/75466/#pkgschedulerinternalqueuego_default_test.

**Comment by bsalamat** [comment]
Yes, that data race is fixed. It should be fine now.

/retest

**Comment by bsalamat** [comment]
This change has reduced Scheduler's throughput in real 5000 node clusters. Given that the only purpose of this change was to improve performance, there is no point in having it. I will revert it.

**Pull request merged**
