### PR TITLE
Fixed passing RUNTIME_CONFIG flag

### PR DESCRIPTION
**Pull request by soltysh**
Currently it fails passing eg. `RUNTIME_CONFIG="experimental/v1=true"` to the server.

@smarterclayton ptal

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
You're getting failures because of the underscores - the verify flag mechanism is flawed, and someone needs to fix it.  Whoever fixed this last time may have broken it.

**Comment by soltysh** [comment]
@smarterclayton right, I've updated `hack/local-up-cluster.sh` but forgot about `hack/verify-flags/exceptions.txt` which is exceptions for underscore check that. Should be fixed now.

**Comment by bgrant0607** [comment]
cc @eparis re. verify-flags

**Comment by eparis** [comment]
@soltysh yup, that's the right fix.

**Comment by caesarxuchao** [comment]
close and reopen to trigger shippable.

**Pull request merged**
