### PR TITLE
update docs/secrets.md to v1beta3

### PR DESCRIPTION
**Pull request by caesarxuchao**
update docs/secrets.md to v1beta3

@nikhiljindal

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by pmorie** [comment]
Thanks for doing this! Lgtm

**Comment by caesarxuchao** [comment]
Because the original syntax doesn't work (see #8362 ), I have updated the the secrets and pods to use the "list" syntax. Could you take another look at [them](https://github.com/caesarxuchao/kubernetes/blob/secrets-doc/docs/secrets.md#use-case-pods-with-prod--test-credentials)? Thanks.

**Comment by caesarxuchao** [comment]
ref #8087

**Pull request merged**
