### PR TITLE
Rename **/manager.go for better logging

### PR DESCRIPTION
**Pull request by timstclair**
Rename `pkg/kubelet/*/manager.go` to `pkg/kubelet/*/*_manager.go`.

**Justification:** Our current logging library, [glog](https://github.com/golang/glog), logs the filename where the log was generated, but not the full path. Ex:

```
I0608 00:28:25.116905    2847 manager.go:1024] Started watching for new ooms in manager
```

We have too many files named `manager.go`, which makes it difficult to identify log messages originating from them:

``` console
$ find . -name "manager.go"
./pkg/kubelet/status/manager.go
./pkg/kubelet/dockertools/manager.go
./pkg/kubelet/eviction/manager.go
./pkg/kubelet/pod/manager.go
./pkg/kubelet/prober/manager.go
./vendor/github.com/vmware/govmomi/session/manager.go
./vendor/github.com/google/cadvisor/manager/manager.go
./vendor/github.com/coreos/go-oidc/key/manager.go
```

/cc @kubernetes/sig-node This change will probably invoke rebase hell, but now seems like a reasonable time for it (with less churn leading up to release).

### CODE REVIEW

**Comment by ncdc** [comment]
Oy, but +1 😄

**Comment by feiskyer** [comment]
+1

**Comment by yujuhong** [comment]
LGTM. I scanned the larger v1.3 PRs in the queue, and this doesn't seem to affect them.

@timstclair, thanks for the PR!

**Comment by yujuhong** [comment]
> @timstclair PR needs rebase

This is sooner than I expected..

**Comment by timstclair** [comment]
Haha, done.

**Comment by timstclair** [comment]
Trivial rebase. Adding back LGTM.

**Comment by timstclair** [comment]
Trivial rebase, reapplying LGTM.

**Comment by yifan-gu** [comment]
+1

**Comment by goltermann** [comment]
@timstclair, can you rebase soon if this is needed for v1.3?

**Comment by yujuhong** [comment]
@timstclair is OOO. I think this is nice to have for 1.3, but not necessary. Let's remove the v1.3 milestone for now.
@timstclair, if you find time to rebase this, feel free to reapply the 1.3 milestone.

**Comment by timstclair** [comment]
Trivial rebase; reapplying LGTM

**Comment by yujuhong** [comment]
@timstclair do you want this in v1.3? Submit queue is merging only v1.3 PRs.

**Comment by timstclair** [comment]
I'm not up-to-date on the 1.3 release status... This is not a critical issue, but would be nice-to-have from a debugging perspective. What is the status of the 1.3 release? Are we in cherrypick-only mode yet?

**Comment by yujuhong** [comment]
> What is the status of the 1.3 release? Are we in cherrypick-only mode yet?

I don't think so. Let's add this to v1.3 for debuggability.

**Pull request merged**
