### PR TITLE
code cleanup: pkg/api simplify the if-condition

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Code cleanup.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by BinacsLee** [comment]
cc @deads2k @smarterclayton 
Thanks!

**Comment by caesarxuchao** [comment]
I think the original code is easier to read actually. Concatenating all the conditions in one line makes the code harder to read.

/remove-sig api-machinery
/sig api

**Comment by BinacsLee** [comment]
Hi @caesarxuchao .
Thanks for review!

Here are some of my personal thoughts.
**Eg:**
At first I wanted to modify it like this:
```diff
func hasExpansionSecrets(oldPVSpec *api.PersistentVolumeSpec) bool {
 	if oldPVSpec == nil || oldPVSpec.CSI == nil {
 		return false
 	}

- 	if oldPVSpec.CSI.ControllerExpandSecretRef != nil {
- 		return true
- 	}
- 	return false

+ 	return oldPVSpec.CSI.ControllerExpandSecretRef != nil
 }
```
Then I realized that the previous `if-condition` was always to check the pointer in advance.
That is to say, the ultimate goal of the function is to check `oldPVSpec.CSI.ControllerExpandSecretRef != nil`.
In another way, the precheck `if-condition` and final check `sth != nil` are highly relevant, so I write them in one line.

**Comment by caesarxuchao** [comment]
@BinacsLee I understand that the one-liners are also correct, I'm arguing that the original code is easier to read, especially if the one-liners are long.

**Comment by BinacsLee** [comment]
> @BinacsLee I understand that the one-liners are also correct, I'm arguing that the original code is easier to read, especially if the one-liners are long.

Considering that the function is very simple and the name of the function indicates what it does, can we not pay attention to the details of the function's implementation? This is feasible to write in one line.

**Comment by liggitt** [comment]
Thanks for the PR, but I agree that the current form is easier to read

/close

**Pull request closed without merging**
