### PR TITLE
TestCreateInvokeAdmissionControl: remove unnecessary goroutine in sequential processing

### PR DESCRIPTION
**Pull request by gaurav1086**
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
A minor optimization/cleanup: Since its sequential processing, we can avoid the overhead of spawning/waiting for a goroutine.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
A minor optimization.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
/ok-to-test

/lgtm

**Comment by lavalamp** [comment]
FWIW, the goroutine overhead is almost certainly completely inconsequential compared to the network call. This is not a meaningful performance improvement.

It is a readability improvement, so still accepting it.

/lgtm
/approve

**Pull request merged**
