### PR TITLE
Move some docs from docs/ top-level into docs/{admin/,devel/,user-gui…

### PR DESCRIPTION
**Pull request by davidopp**
…de/}.

The ones that remain fell into one of two categories
(1) Should not exist on their own -- should be merged into other docs and then deleted (kube-apiserver.md, kube-controller-manager.md, kubelet.md, services-firewall.md)
(2) Geuinely feel like they belong at top-level (api.md, glossary.md, roadmap.md, troubleshooting.md)

I will merge docs/devel/{README.md,developer-guide.md} in a follow-up PR.

This is a redo of #11272.

@bgrant0607 @erictune @lavalamp

### CODE REVIEW

**Comment by bgrant0607** [comment]
Ah, right, you're not moving services-firewalls.md. That simplifies things.
LGTM
cc @thockin

**Comment by bgrant0607** [comment]
The architecture diagrams really belong in docs/design if you'd be willing to move them in this PR. They are only referenced by docs/design/architecture.md

**Comment by thockin** [comment]
If this goes green, I'm merging :)

**Comment by thockin** [comment]
Bombs away

**Comment by davidopp** [comment]
I'll send a followup PR for moving the diagrams. I agree they should be moved.

**Comment by bgrant0607** [comment]
Thanks

**Pull request merged**
