### PR TITLE
fix comment in controller_policy.go

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind cleanup
/sig api-machinery

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign liggitt

NOTE: just about 4 lines of comments, quick review.

**Comment by liggitt** [comment]
Thanks for the PR, but the comments are fine as-is. A role binding can be cluster-scoped (`ClusterRoleBinding`) or namespace-scoped (`RoleBinding`).

/close

**Pull request closed without merging**
