### PR TITLE
Automated cherry pick of #48182

### PR DESCRIPTION
**Pull request by gmarek**
Cherry pick of #48182 on release-1.7.

#48182: Add generic NoSchedule toleration to fluentd in gcp config as

```release-note
Add generic NoSchedule toleration to fluentd in gcp
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
What's the relationship of this PR to https://github.com/kubernetes/kubernetes/issues/48190? The latter is going to be merged in 1.7.1. Can this PR wait for 1.7.1?

**Comment by gmarek** [comment]
It's already in 1.6.7, so for consistency we should put it into 1.7.1. @caesarxuchao

**Comment by caesarxuchao** [comment]
Thanks. Added the label.

**Pull request merged**
