### PR TITLE
Maintain an IP address independent of the forwarding rule for GCE plus bug fixes

### PR DESCRIPTION
**Pull request by a-robinson**
Pulling @brendandburns' work from #13335 here so that I can add a fix for the bug in it that was causing it to fail the e2e tests. They're not quite done running yet, but so far it looks like all the services e2e tests now pass locally.

This not only fixes the issue in that PR, but two other bugs, including one that has likely been causing target pool leaks in our e2e tests, so this needs to get in for 1.1. Description copied from my commit message:

```
This code was in rough shape, so I've fixed the issues with the original
PR as well as a few other changes:
1. Clarify the error messages related to the "gce Addresses" to make it
   clear we're talking about static IP addresses
2. Fix the bug in the original PR, which was a nil pointer dereference
   from passing op to waitForRegionOp when the address doesn't exist.
3. Rearrange the steps of EnsureTCPLoadBalancerDeleted to be the reverse
   of EnsureCreated, which mostly just seems like good practice to me.
   This is also supported by the following two bugs I found :(
4. Fix an independent bug of returning too early if the target pool
   doesn't exist, effectively stranding the firewall. This was likely
   introduced because target pools used to be the last thing deleted,
   so it was previously safe to return there.
5. Fix an independent bug of not returning an error waiting for the
   target pool to be deleted failed. This was very possibly causing
   target pool leaks in our e2e tests. This was similarly due to
   assuming that the target pool was the last thing deleted in the
   function, then having the firewall deletion stuck in after it.
```

@thockin @wojtek-t

### CODE REVIEW

**Comment by a-robinson** [comment]
There's still on failure (`should be able to change the type and nodeport settings of a service`), and it looks like it's not a flake. Checking into it...

**Comment by a-robinson** [comment]
Although that test is marked as flaky in jenkins, so perhaps it is a flake. Checking regardless

**Comment by thockin** [comment]
Change LGTM - let me know about the e2e

**Comment by a-robinson** [comment]
Additional testing was successful, so flake seems the most likely conclusion. I'll continue looking at it, but I think this is ok to merge.

The modified commit I just pushed only differs in a few of the error messages that were misordered after my shuffle and inconsistent to begin with.

**Comment by a-robinson** [comment]
cc @quinton-hoole @ixdy since this should reduce target pool (but not forwarding rule) leaks. We weren't retrying target pools deletions that failed since back before https://github.com/kubernetes/kubernetes/pull/10974

**Comment by bgrant0607** [comment]
I'm going to revert this to see if it helps. Since around the time I merged this we've been hitting static IP quota limits.

**Comment by thockin** [comment]
I am SURE this contributes to static IP quota problems on GCE.  We knew
that going in.

With this, every load-balancer gets a static IP, requiring quota.

Without this, any UPDATE operation to a load-balancer Service can cause the
IP to be released

**Pull request merged**
