### PR TITLE
Restore in-tree credential plugins for 1.25

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Reverts https://github.com/kubernetes/kubernetes/pull/110013 to avoid regressions from migrating to exec auth (https://github.com/kubernetes/kubernetes/issues/111911, https://github.com/kubernetes/kubectl/issues/1128)

Additional commits:
* formatted with go1.19
* adjusted the removal warning to 1.26, according to the plan at https://github.com/kubernetes/kubernetes/issues/111911#issuecomment-1219783870

#### Does this PR introduce a user-facing change?
```release-note
The `gcp` and `azure` auth plugins have been restored to client-go and kubectl until https://issue.k8s.io/111911 is resolved in supported kubectl minor versions.
```

/sig auth
/milestone v1.25
/cc @enj

### CODE REVIEW

**Comment by cici37** [comment]
/lgtm 
from release team. Thank you for the PR!

**Comment by enj** [comment]
/lgtm
/approve

image

**Comment by enj** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/111911#issuecomment-1219852463

**Pull request merged**
