### PR TITLE
pkg/apis: Replace deprecated pointer function

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will replace the deprecated `(Int32|Int64|Bool)Ptr` function by `Int32|Int64|Bool`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
I already saw this test failing in other open PRs that I have.

```
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver: TestRemoveAPIService 
{Failed  === RUN   TestRemoveAPIService
I0109 13:56:34.552335   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0109 13:56:34.554316   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0109 13:56:34.554485   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ȵʭ洒$\' to ResourceManager
I0109 13:56:34.554608   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 壊3囜n繊ŀ槉@ to ResourceManager
I0109 13:56:34.554720   84044 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º Hľȋ?{ə%ĺ誟ǀ還N儮 to ResourceManager
I0109 13:56:34.554811   84044 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º ǭȐÿ to ResourceManager
I0109 13:56:34.554898   84044 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 闀8ǿ滃 to ResourceManager
I0109 13:56:34.554992   84044 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 覒ęȽ鉹鏪_败>ŵx¤蕰 to ResourceManager
I0109 13:56:34.555499   84044 handler_discovery.go:403] Starting ResourceDiscoveryManager
I0109 13:56:34.588796   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0109 13:56:34.592680   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0109 13:56:34.592935   84044 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
    handler_discovery_test.go:203: expected to find no groups after service deletion (got 1 groups)
--- FAIL: TestRemoveAPIService (0.12s)
}
```
May I consider it as flaky and try to deflake it ?

**Comment by alculquicondor** [comment]
flaky #114438

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
