### PR TITLE
Added UndeltaStore.

### PR DESCRIPTION
**Pull request by erictune**
This will be used to connect Reflector to kubelet update channel.

### CODE REVIEW

**Comment by erictune** [comment]
hold on this needs some work.

**Comment by pmorie** [comment]
@erictune I added a store in openshift that does something similar but haven't gotten to pushing it upstream yet.  Could this be of use to you?

https://github.com/openshift/origin/blob/master/pkg/client/cache/eventqueue.go

**Comment by erictune** [comment]
This thing also calls a callback when there is a change.  It doesn't look like eventqueue does that?

**Comment by erictune** [comment]
Now in #3366

**Pull request closed without merging**
