### PR TITLE
Refactor cacher.ListerWatcher code structure

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #109831

```release-note
NONE
```

/kind cleanup
/priority important-longterm
/sig api-machinery

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
`gofmt` unhappy, otherwise LGTM:

```
diff ./staging/src/k8s.io/apiserver/pkg/storage/cacher/lister_watcher_test.go.orig ./staging/src/k8s.io/apiserver/pkg/storage/cacher/lister_watcher_test.go
--- ./staging/src/k8s.io/apiserver/pkg/storage/cacher/lister_watcher_test.go.orig
+++ ./staging/src/k8s.io/apiserver/pkg/storage/cacher/lister_watcher_test.go
@@ -33,7 +33,7 @@
 	"k8s.io/apiserver/pkg/storage/value/encrypt/identity"
 )
 
-func newPod() runtime.Object     { return &example.Pod{} }
+func newPod() runtime.Object { return &example.Pod{} } 
```

**Comment by wojtek-t** [comment]
@stevekuznetsov - fixed now :)

**Comment by wojtek-t** [comment]
Just did a trivial rebase - reapplying the label.

**Pull request merged**
