### PR TITLE
Update duplicate env var warning

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

Clarifies the warning around duplicate env var entries that duplicates can be dropped when using apply

xref https://github.com/kubernetes/kubernetes/issues/58477

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig api-machinery
/assign @apelisse

### CODE REVIEW

**Comment by pacoxu** [comment]
UT needs an update to make CI happy.

**Comment by liggitt** [comment]
fixed unit test

**Review by pacoxu — APPROVED** [review]
/lgtm

**Pull request merged**
