### PR TITLE
GZip openapi schema if accepted by client

### LINKED ISSUE #48375: openapi: Simplify gzip encoding for openapi endpoint
The current implementation of the openapi listener takes a different path for gzip entries. Let's read the `Accept-Encoding: gzip` http header from the client to decide if we need to gzip or not.

### PR DESCRIPTION
**Pull request by apelisse**
**What this PR does / why we need it**: Uses gzip "Accept-Encoding" flag rather than specific path to download gzipped openapi schema.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48375

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mbohlool** [comment]
We definitely want to add this to release note. Also we cannot just remove .gz file from 1.8 as we have it in 1.7 and a user can reply on it so I suggest we keep the file for one release and deprecate it in 1.9 unless you feel strongly about this, in that case we can discuss it.

**Comment by apelisse** [comment]
Let's keep the link. PTAL

**Comment by apelisse** [comment]
@deads2k Can you have a look?

**Comment by thockin** [comment]
This needs an issues and a `closes #12345` in the FIRST COMMENT, or the approval won't stick.

**Pull request merged**
