### PR TITLE
refactor: use findFirstUnhealthyPod instead in statefulset control

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
assign @foxish @enisoc @janetkuo @kow3ns @smarterclayton @tnozicka

**Comment by tnozicka** [comment]
I don't find it appropriate to ping 7 maintainers on a PR extracting few lines into a function. Unfortunately this is not the first such PR I am seeing today.

Extracting a code into a function without a good reason doesn't add any value, has possibility for bugs, cost infra and review time.

If you want to contribute please try to address some of the issues but refactoring code into functions for the sake of the refactor seems meaningless.

/close

**Pull request closed without merging**
