### PR TITLE
LB resources should be deleted when the service is deleted

### PR DESCRIPTION
**Pull request by duanjiong**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When the finalizers are cleared for some reason, and then the service is deleted, the corresponding LB resources should also be cleared.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by duanjiong** [comment]
I signed it

**Comment by MrHohn** [comment]
@duanjiong Trying to understand the use case better - why would the loadbalancer-cleanup finalizer be removed by others? Service controller relies on that finalizer to fulfill resource finalization and it expects ownership on that finalizer.

**Comment by duanjiong** [comment]
> @duanjiong Trying to understand the use case better - why would the loadbalancer-cleanup finalizer be removed by others? Service controller relies on that finalizer to fulfill resource finalization and it expects ownership on that finalizer.

Yes, you're talking about the ideal situation, but user input is not always what is expected. Like the case I encountered, when the user applies service resources, the finalizer is deleted by mistake, and the service controller has already cached the service information, shouldn't we try to delete the lb resources when we delete the service?

**Pull request closed without merging**
