### PR TITLE
apiextensions: wire structural schema into server-side-apply

### PR DESCRIPTION
**Pull request by sttts**
Based on @jennybuckley's https://github.com/kubernetes/kubernetes/pull/77354 and includes https://github.com/kubernetes/kubernetes/pull/74133.

TODO:
- [x] reject server-side-apply requests for non-structural CRDs
- [x] test that server-side-apply patches are reject for non-structural CRDs

```release-note
CustomResourceDefinition with structural schema get support for server-side apply.
```

### CODE REVIEW

**Comment by sttts** [comment]
@jennybuckley fyi, started with this now. Still WIP based on your PR.

**Comment by josiahbjorgaard** [comment]
Hello! I'm a bug triage shadow for the 1.16 release cycle and considering this PR has not been updated for a long time, I'd like to check it's status. The code freeze is starting 29th August (about 2 weeks from now) and while there is plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.16, is it still planned for this release?

**Comment by liggitt** [comment]
was this replaced by https://github.com/kubernetes/kubernetes/pull/77354?

**Comment by liggitt** [comment]
> was this replaced by #77354?

spoke offline, this isn't needed after #77354

/close

**Pull request closed without merging**
