### PR TITLE
Update structured-merge-diff dependency to v3

### LINKED ISSUE #82042: Serialization of fieldsets in managedFields should always be the same
**What happened**:
The serialization of managedFields field sets can change, resulting in an otherwise no-op update causing a write to etcd. The issue arises when a fieldset like this
```
"k:{\"name\":\"test-container-a\"}": {
    ".": {},		
    "f:image": {},
    "f:name": {}
}
```
is decoded and re-encoded as part of a modifying request, which causes it to become
```
"k:{\"name\":\"test-container-a\"}": {
    "f:image": {},
    "f:name": {}
    ".": {},		
},
```

This isn't too serious, as it only seems to happen on the first update after a new list item is added, but we should try to understand this better and fix it.

**What you expected to happen**:
The fieldset serialization should be unaffected by round tripping through the internal structured-merge-diff type.

/sig api-machinery
/wg apply
/priority help-wanted
/cc @lavalamp @apelisse

### PR DESCRIPTION
**Pull request by jennybuckley**
**What type of PR is this?**
/kind bug
/sig api-machinery
/wg apply
/cc @liggitt @apelisse 
/priority important-soon

**What this PR does / why we need it**:
Update smd to pull in https://github.com/kubernetes-sigs/structured-merge-diff/pull/145 which should fix https://github.com/kubernetes/kubernetes/issues/82042 and allow us to revert https://github.com/kubernetes/kubernetes/pull/87196

Also had to update the kube-openapi dependency for this, but the change in kube-openapi does nothing besides bump it's smd dependency to v3 (https://github.com/kubernetes/kube-openapi/pull/183)

**Which issue(s) this PR fixes**:
Fixes #82042

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jpbetz** [comment]
This matches how I did the v2 upgrade when experimenting locally.

/lgtm

**Comment by apelisse** [comment]
105 files changed, that's too many, please remove 2.

**Comment by liggitt** [comment]
please open a tracking issue in release-1.18 to make sure we tag v3.0.0 and bump to that before releasing kube

**Comment by jennybuckley** [comment]
/retest
a lot of flakes :/

**Comment by liggitt** [comment]
The runc bug causing those is on its way through the pipeline… hopefully our CI envs will pick it up shortly

**Pull request merged**
