### PR TITLE
Mark NodeNotReady if it goes to unknown state regardless of its previous state in case of failure

### PR DESCRIPTION
**Pull request by akankshakumari393**
Fixes #112733 

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@akankshakumari393 can you please add tests for this?

**Comment by akankshakumari393** [comment]
@SergeyKanzhelev what kind of test would you like me to add there? I am a new contributor, do not have much experience with the repo.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev what kind of test would you like me to add there? I am a new contributor, do not have much experience with the repo.

First you need to ensure that the existing tests are not failing. This may give an idea what other tests might be needed. In general every functionality that is being fixed needs to have a test that would fail if this fix doesn't present. This ensures that the bug will not happen again

**Pull request closed without merging**
