### PR TITLE
remove TODO: Use return type string instead of []string and update func

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup
 

**What this PR does / why we need it**:

remove TODO: Use return type string instead of []string and update func in  test/e2e/framework/node/resource.go

**Which issue(s) this PR fixes**:

 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/unassign 
I don't have enough context to evaluate the impact of this change.
@tanjunchen if there is a lag in the review (after holidays), ping me again and I will do my best to investigate the topic

**Review by SataQiu — COMMENTED** [review]
/lgtm
/cc @oomichi

**Comment by tanjunchen** [comment]
ping @fabriziopandini for long time :))

**Comment by neolit123** [comment]
/uncc fabriziopandini 

@tanjunchen fabriziopandini already said:
> I don't have enough context to evaluate the impact of this change.

this is on @oomichi for approval.

**Comment by tanjunchen** [comment]
/cc @oomichi
sorry to bother you

**Comment by oomichi** [comment]
Nice cleanup

/approve

**Pull request merged**
