### PR TITLE
Token review endpoint

### PR DESCRIPTION
**Pull request by deads2k**
Unrevert of #28788, which was rolled back because of https://github.com/kubernetes/kubernetes/issues/29375

@cjcullen @wojtek-t I'd like to remerge if possible.  Have we gotten the field checking mentioned here relaxed? https://github.com/kubernetes/kubernetes/pull/28788#discussion_r71918442

### CODE REVIEW

**Comment by wojtek-t** [comment]
@deads2k - I wasn't involved in fixing it, to please don't block on me at all.

**Comment by cjcullen** [comment]
@deads2k We're still working on the actual relaxation of field checking. As a workaround, I can shove all of the added fields into our server's expected request body, but that's really gross. I know this is holding you guys up right now, so I'll have an answer early next week.

**Comment by deads2k** [comment]
> I know this is holding you guys up right now, so I'll have an answer early next week.

Thanks.  I suspect we'll have a similar problem in https://github.com/kubernetes/kubernetes/pull/20573 when I rebase that one.

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #28713

**Comment by deads2k** [comment]
kicking tests now that https://github.com/kubernetes/kubernetes/issues/29375 is resolved.

**Comment by deads2k** [comment]
GKE tests look to be fixed, smoke test passed with matching levels, https://github.com/kubernetes/kubernetes/pull/28788 was already tagged, so applying the tag here.

**Comment by cjcullen** [comment]
Sorry @deads2k this is still broken on our side. I'm trying to get the fix pushed out today, but GKE smoke tests still don't quite test the same config as gke-ci.

**Comment by deads2k** [comment]
> Sorry @deads2k this is still broken on our side. I'm trying to get the fix pushed out today, but GKE smoke tests still don't quite test the same config as gke-ci.

*Yikes!*  Is there another issue I can watch?  I saw the existing one get resolved.

**Comment by cjcullen** [comment]
https://github.com/kubernetes/test-infra/pull/332

**Comment by deads2k** [comment]
> kubernetes/test-infra#332

Thanks, once that's merged, I just have to rekick the tests and this and https://github.com/kubernetes/kubernetes/pull/20573 will be safe?

**Comment by cjcullen** [comment]
Now that that's merged, the GKE smoke tests should fail for both this and #20573...

Once I get my GKE server side change rolled out (hopefully soonish today), then GKE smoke tests will start passing for you and I can get out of your way :smiley:

**Comment by cjcullen** [comment]
@k8s-bot: e2e test this issue #IGNORE

**Comment by cjcullen** [comment]
This should be unblocked on our end now. I just manually tested a kubernetes CI build with this change ( 1.4.0-alpha.1.564+8ead63f1270455)  and confirmed that authentication is working.

I'm attempting to kick GKE smoke tests just to verify.

**Comment by cjcullen** [comment]
@k8s-bot: e2e test this: issue #IGNORE

**Comment by cjcullen** [comment]
@k8s-bot e2e test this issue #IGNORE

**Comment by cjcullen** [comment]
Our 6:00 PM automatic deployment pushed a slightly too-old build to our test endpoint, so this is going to appear to have broken things again until I get a fixed build back live... 😒

**Comment by wojtek-t** [comment]
@cjcullen - it seems that we hit this also in staging:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/67/console

When do you think it will be fixed?

**Comment by cjcullen** [comment]
@wojtek-t :disappointed: I didn't realize we had any CI running against our staging endpoint. I'll work on getting an updated build pushed out to staging today.

**Pull request merged**
