### PR TITLE
Updated wording from minion to node in cluster/centos according to #1111

### PR DESCRIPTION
**Pull request by zhengguoyong**
#1111

### CODE REVIEW

**Comment by zhengguoyong** [comment]
@eparis 
hi eparis, can you help me make a review for this PR please ?  
thanks very much.

**Comment by ashcrow** [comment]
@zhengguoyong The changes look good to me as it's ```s/minion/node/g``` for ```cluster/centos/util.sh```

**Comment by ashcrow** [comment]
Shippable 1.4 passes but 1.3 failed. I have a feeling it's totally unrelated to this change.
```
!!! Error in ./hack/test-integration.sh:60
  'KUBE_API_VERSIONS="v1,experimental/v1alpha1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
```

**Comment by zhengguoyong** [comment]
thanks for your review , i changed.
please review again, thanks so much.
@ashcrow

**Comment by ashcrow** [comment]
@zhengguoyong Sure! I still think updating the description will help people take a look :smile:. People tend to overlook PR's and issues with just a link or no description as it requires extra work to figure out what the PR/issue is about. I recommend a simple description like:

"Updated wording from minion to node in cluster/centos according to #1111"

Other than that it looks good to me. /cc @eparis

**Comment by zhengguoyong** [comment]
Get it.
thank you!!
@ashcrow

**Comment by ashcrow** [comment]
@eparis mind taking a quick look at this one?

**Comment by eosrei** [comment]
@zhengguoyong My PR #17024 fixed all capitalized instances of MINION. The still open #17844 handles the kube-util helper functions. If you rebase this PR, it'll now be much smaller and easier to review. FWIW I'm using the following format for the commit messages: `Minion->Name rename: Vagrant cluster/docs, excludes SaltStack minions`

**Comment by wojtek-t** [comment]
It seems that it was already done as part of other PRs (there is no "minion", "MINION", "Minion", etc. in this file any longer). Closing.

**Comment by eosrei** [comment]
#15300 did it.

**Pull request closed without merging**
