### PR TITLE
Automated cherry pick of #107406: fix: delete non existing disk issue

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #107406 on release-1.20.

#107406: fix: delete non existing disk issue

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Friendly ping @andrewsykim

**Comment by bridgetkromhout** [comment]
Hi, @ialidzhikov - per https://groups.google.com/a/kubernetes.io/g/dev/c/ZzDEAu0DpuM/m/99BmiqsjCgAJ this cherry-pick may not be accepted, as 1.20 is in maintenance mode. @cpanato will have more insight.

**Review by andrewsykim — COMMENTED** [review]
/approve

(approving code changes but defer to release team for whether v1.20 cherry-picks are still supported)

**Comment by bridgetkromhout** [comment]
Per @cpanato on [January 13th, 2022](https://groups.google.com/a/kubernetes.io/g/dev/c/ZzDEAu0DpuM/m/99BmiqsjCgAJ?utm_medium=email&utm_source=footer&pli=1): "1.20 branch is in maintenance mode and most likely be the last patch release for 1.20. 
For the February cycle, only critical or blocker issues will be merged."

So @ialidzhikov, please be aware this cherry-pick might not be merged. If you believe it is critical or blocker, please speak with the release team about it.

**Pull request closed without merging**
