### PR TITLE
Revert "[Kubelet] Optionally consume configuration from <node-name> named config maps"

### PR DESCRIPTION
**Pull request by lavalamp**
Reverts kubernetes/kubernetes#30090

Kubelet test is red, merge queue is blocked.

@mikedanese (build cop)

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31287)

### CODE REVIEW

**Comment by luxas** [comment]
Hmm, first see if https://github.com/kubernetes/kubernetes/pull/31282 fixes it

**Comment by Random-Liu** [comment]
The test in the PR should be run in serial test suite instead of kubelet-gce-e2e-ci.
We've sent a PR to mark the test as serial and has been merged https://github.com/kubernetes/kubernetes/pull/31282.

**Comment by mikedanese** [comment]
I manually restarted the jenkins build and am watching it. All looks good so far.

**Comment by Random-Liu** [comment]
It seems that there is still something wrong here:
```

13:39:27 I0823 13:39:27.083507    5572 run_e2e.go:559] Deleting instance "tmp-node-e2e-519dfbc3-coreos-alpha-1122-0-0-v20160727"
13:39:27 E0823 13:39:27.257592    5572 run_e2e.go:562] Error deleting instance "tmp-node-e2e-519dfbc3-coreos-alpha-1122-0-0-v20160727": googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-coreos-alpha-1122-0-0-v20160727' was not found, notFound
13:39:27 ================================================================
13:39:27 Failure Finished Host  Test Suite
13:39:27 
13:39:27 unable to create gce instance with running docker daemon for image coreos-alpha-1122-0-0-v20160727.  googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-coreos-alpha-1122-0-0-v20160727' was not found, notFound
13:39:27 ================================================================
13:39:27 I0823 13:39:27.348859    5572 run_e2e.go:559] Deleting instance "tmp-node-e2e-519dfbc3-gci-dev-54-8711-0-0"
13:39:27 I0823 13:39:27.479226    5572 run_e2e.go:559] Deleting instance "tmp-node-e2e-519dfbc3-e2e-node-ubuntu-trusty-docker9-v1-image"
13:39:27 E0823 13:39:27.509008    5572 run_e2e.go:562] Error deleting instance "tmp-node-e2e-519dfbc3-gci-dev-54-8711-0-0": googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-gci-dev-54-8711-0-0' was not found, notFound
13:39:27 ================================================================
13:39:27 Failure Finished Host  Test Suite
13:39:27 
13:39:27 unable to create gce instance with running docker daemon for image gci-dev-54-8711-0-0.  googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-gci-dev-54-8711-0-0' was not found, notFound
13:39:27 ================================================================
13:39:27 I0823 13:39:27.545837    5572 run_e2e.go:559] Deleting instance "tmp-node-e2e-519dfbc3-e2e-node-containervm-v20160321-image"
13:39:27 E0823 13:39:27.630538    5572 run_e2e.go:562] Error deleting instance "tmp-node-e2e-519dfbc3-e2e-node-ubuntu-trusty-docker9-v1-image": googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-e2e-node-ubuntu-trusty-docker9-v1-image' was not found, notFound
13:39:27 ================================================================
13:39:27 Failure Finished Host  Test Suite
13:39:27 
13:39:27 unable to create gce instance with running docker daemon for image e2e-node-ubuntu-trusty-docker9-v1-image.  googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-e2e-node-ubuntu-trusty-docker9-v1-image' was not found, notFound
13:39:27 ================================================================
13:39:27 E0823 13:39:27.701175    5572 run_e2e.go:562] Error deleting instance "tmp-node-e2e-519dfbc3-e2e-node-containervm-v20160321-image": googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-e2e-node-containervm-v20160321-image' was not found, notFound
13:39:27 ================================================================
13:39:27 Failure Finished Host  Test Suite
13:39:27 
13:39:27 unable to create gce instance with running docker daemon for image e2e-node-containervm-v20160321-image.  googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-519dfbc3-e2e-node-containervm-v20160321-image' was not found, notFound
```

**Comment by mikedanese** [comment]
I kicked the build again.

**Comment by mikedanese** [comment]
Is this possibly related?

**Comment by Random-Liu** [comment]
@mikedanese Hm, may be.

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/issues/31296

**Pull request closed without merging**
