### PR TITLE
ran hack script for 0.0.26

### PR DESCRIPTION
**Pull request by jdnurme**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Bump KNP version to 0.0.26, includes various bugfixes

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jdnurme** [comment]
Initially I did not pin the dependencies for grpc on this PR. The dependencies test failed and told me to pin for grpc version 1.42. I made this change, and further tests failed. I also attempted to run the hack/vendor-update.sh script after pinning the new grpc version, and it made an extremely large set of changes that seemed obviously incorrect. Does anyone have experience in merging versions that are paired with another vendored release? I'm unsure of how to proceed with merging this PR.

**Comment by Jefftree** [comment]
We have a PR here to bump straight to 0.0.27: https://github.com/kubernetes/kubernetes/pull/106922

**Comment by liggitt** [comment]
already bumped master to 0.0.27

**Pull request closed without merging**
