### PR TITLE
Update deprecated flags for "make test-cmd"

### PR DESCRIPTION
**Pull request by CaoShuFeng**
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by eparis** [comment]
@k8s-bot ok to test
/lgtm

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-verify test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
