### PR TITLE
create RBAC intent driven API for binding roles to subjects

### PR DESCRIPTION
**Pull request by deads2k**
Adds an `AddRoleRequest` API which allows a caller to express the intent of binding a subject to a role.  It does the:
1. find existing rolebinding
2. create new if necessary
3. merge subjects
4. issue update
5. retry on conflict

on the caller's behalf.  This will eventually be paired with a `RemoveRoleRequest` which has to be a separate object since binding information that isn't directly mappable to names must be provided.

This structure also allows for easy inclusion in lists of items to express an intent to add a permission without having to have prior knowledge of the available rolebinding names.

@kubernetes/sig-auth

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31441)

### CODE REVIEW

**Comment by ericchiang** [comment]
Looks cool. I can volunteer to write the controller if you haven't already started on that.

**Comment by deads2k** [comment]
> Looks cool. I can volunteer to write the controller if you haven't already started on that.

I chose to implement this by wiring up the RESTStorage directly, so that a 200 means "role bound".  I think that obviated the need for a controller and helped limit the number of secondary authorization checks.

**Comment by ericchiang** [comment]
> I chose to implement this by wiring up the RESTStorage directly, so that a 200 means "role bound". I think that obviated the need for a controller and helped limit the number of secondary authorization checks.

Ah, yes. I see that in the third commit.

**Comment by erictune** [comment]
Can you give a concrete example of how this would be used?

**Comment by deads2k** [comment]
> Can you give a concrete example of how this would be used?

Sure.  Right now in order to add a role to a subject, you have to:
 1. list the available role bindings and search for one with the right ref
 2. if it doesn't exist, start a new role
 3. search the list of subjects to avoid adding duplicates
 4. add your subject
 5. issue a create or an update

This object lets you simply say, "bind this role to these subjects" and all the those details managed for you.

There are two common cases where you're trying to deal with it.
 1. I have a `List`, a `Template` (these are coming), or a directory of resource files.  These files are supposed to create an application in a given namespace, but I have to grant permissions to a service account in order for my app to work (CI integration like Jenkins as a for instance).  I need to bind a role that SA, but I can't express it as an object you create without creating a large list of generated rolebindings which become progressively harder to manage as you start trying to handle both adds and removes.
 2. Management consoles.  Any client that tries to manage these has to have all that mutation logic built in, but what the consoles really want to do is "add role to subject", "remove role from subject", and "remove all roles from subject".  There ends up being a lot of glue code to hold it all together.

**Comment by erictune** [comment]
I see the desire for item 1.  This same need comes in Helm Charts.  However, I want Helm Charts to work on other Authorizers.  So, for that, I'd want something that is similar to AddRoleBinding, but which could also cause a role to be added to a user on GKE as well, and on other authorizers, as those become more popular.  So, I want an AddRoleBinding API that is separate from RBAC group, I think.

**Comment by deads2k** [comment]
> I see the desire for item 1. This same need comes in Helm Charts. However, I want Helm Charts to work on other Authorizers. So, for that, I'd want something that is similar to AddRoleBinding, but which could also cause a role to be added to a user on GKE as well, and on other authorizers, as those become more popular. So, I want an AddRoleBinding API that is separate from RBAC group, I think.

That make sense.  I think we'd probably want a generic API that delegates calls out other discovered authorizers that provide their own implementations, rather than trying to gather knowledge of all authorizers in one location.  That way, discovery could be used to determine what's available.

This would be the implementation for the rbac authorizer and we can use its `v1alpha1` state to try to make sure we're happy with the shape.

**Comment by erictune** [comment]
Is it an alternative to just make a new roleBinding each time you want to bind a subject to a role?  That would remove the need for this function.  That pattern would allow you to for example tie a single roleBinding to a single "reason".   

I assume this is imperative like SubjectAccessReview, meaning the object disappears after you delete it?  I'll note that this is the first example of an imperative mutating API, which seems like a big deal to me.  Would like other API reviewers/stakeholders to review.

Since there are no resource versions involved, if there are Adds and Deletes happening near in time, then there is no way to guarantee that they are ordered a particular way.  So an Add and then a Delete could result in the binding still existing, which is unexpected.  In certain pessimal scenarios, this could happen even if the client thinks the Adds and Deletes are happening "far apart in time".

**Comment by deads2k** [comment]
> Is it an alternative to just make a new roleBinding each time you want to bind a subject to a role? That would remove the need for this function. That pattern would allow you to for example tie a single roleBinding to a single "reason".

I was actually hoping to go in the other direction and force each role to have a single binding, perhaps by giving it a pinned/matching name.  I think that would help any client trying to build a console.  "Who is bound to this role?  Just look up the rolebinding with that name (or resource:name).".

This also pairs nicely with a `RemoveRole`.  



> Since there are no resource versions involved, if there are Adds and Deletes happening near in time, then there is no way to guarantee that they are ordered a particular way. So an Add and then a Delete could result in the binding still existing, which is unexpected. In certain pessimal scenarios, this could happen even if the client thinks the Adds and Deletes are happening "far apart in time".

I think the behavior is very similar to patch.  The patch API behaves the same way when handling conflicting patches, but it can't handle the case of actually performing the remove for rolebindings.

**Comment by erictune** [comment]
> I was actually hoping to go in the other direction and force each role to have a single binding, perhaps by giving it a pinned/matching name. I think that would help any client trying to build a console. "Who is bound to this role? Just look up the rolebinding with that name (or resource:name).".

That doesn't work for ClusterRoles.  A client in a namespace is not necessarily permitted to see all of the names of other users who are bound to the role.

**Comment by deads2k** [comment]
> That doesn't work for ClusterRoles. A client in a namespace is not necessarily permitted to see all of the names of other users who are bound to the role.

You're talking about the situation where someone is bound to a `ClusterRole` via a `ClusterRoleBinding` as opposed to a `RoleBinding`?  I think that its reasonable for a project-admin (user who manages permissions inside of a namespace) to see all `RoleBindings` and in that case, having a deterministic mapping from `Role` to `RoleBinding` resolves problems.

A project-admin wouldn't be able to see the `ClusterRoleBinding`, but having a similar mapping between `ClusterRole.Name` and `ClusterRoleBinding.Name` provides similar value to the cluster-admin.

**Comment by erictune** [comment]
What about add and delete ordering?

**Comment by deads2k** [comment]
> What about add and delete ordering?

I see the ordering problem as essentially the same problem as the `PATCH` API we have today.  Patch has a semantic of "Do X against the current state.  If you have a conflict, pull the new API object and try again".  If another actor is trying to add at about the same time that you're trying to delete, I don't think we have to be overly concerned with which actor's change happens last.

If we pinned the names of `RoleBindings` to their `Roles`, we could return the resource version from the update.  I think that gives enough information to reason about racing changes.  "Delete from all Roles" (a common thing to want), would have to return multiple, but I think that manageable.

@liggitt @ericchiang I've drifted a little bit with @erictune here.  Opinions on pinning `RoleBinding.Name` to `<RoleRef.Kind>:<RoleRef.Name>`?

**Comment by erictune** [comment]
Does putting this on the server side allow for anything that cannot be done if it were a client library?

**Comment by deads2k** [comment]
> Does putting this on the server side allow for anything that cannot be done if it were a client library?

No, a client library could perform all these actions.  However, we have multiple clients (three web clients that I know of and two CLI clients) and these actions are integral to how you use the API.  Every client would be reproducing the logic to make this work.

**Comment by liggitt** [comment]
>> Does putting this on the server side allow for anything that cannot be done if it were a client library?
>
> No, a client library could perform all these actions.

it allows binding roles in a resource List that could be used with `kubectl create -f`

**Comment by deads2k** [comment]
> it allows binding roles in a resource List that could be used with kubectl create -f

Right, I forgot that one again.  Use-case one from here: https://github.com/kubernetes/kubernetes/pull/31441#issuecomment-242713808

**Comment by deads2k** [comment]
Spoke with @erictune and we agreed that this API is acceptable, but we need avoid a slippery-slope of convenience APIs for "patch this object in a handy way".  This one meets the somewhat subjective bar of client-side difficulty and overall utility because it can't be expressed using a `PATCH` operation, it is one the top actions performed by clients, it can't be done as effectively in template for simple creation flows without this, and there is some aggregation/deduping/conflict resolution code.

We also decided that we cannot force the name of a rolebinding to match a role, because it becomes overly onerous for users to handle simply creation/deletion flows with the GC controller, label selection, or direct naming in a list.

**Comment by erictune** [comment]
@deads2k This is the scenario we talked about on the call, but I've modified it a bit.

We talked about what if charts want to create service accounts and bind those to roles as part of their installation.

Scenario:

 I want to create chart "mysql" in namespace foo.  It needs its own service account `serviceAccounts/mysql-1` in the namespace.  Then I need to give that service account permission to read secrets (somewhat contrived example, but suppose it needs to read a secret directly from the api). 

Option 1: the chart creates:
- a Deployment
- a Service
- a serviceAccount called `serviceAccounts/mysql-1`
- and an AddRoleRequest, to bind `serviceAccounts/mysql-1` to `roles/secretReader`

Does this work?  Sort of.  Except that if the`AddRoleRequest` fails, then there will be no retry.  And there is no way to modify the binding in the case of an upgrade.  And there is not a good way for the Chart to know that it should do a `DeleteRoleRequest` to reverse the `AddRoleRequest`.  

Note: If there were a second instance of mysql in the namespace, created by a second invocation of `helm install`, that should create its own `serviceAccounts/mysql-2`, so that when the first chart is deleted, the second still has a service account.

Option 2: the chart creates:
- a Deployment
- a Service
- a serviceAccount called `serviceAccounts/mysql-w`
- and a new RoleBinding from `serviceAccounts/mysql-w` to `roles/secretReader` 

The difference between 1 and 2 is that 1 uses AddRoleRequest while 2 creates a `RoleBinding`.

In 2, the RoleBinding can be cleaned up by helm by deleteing all the objects it originally created.
Also, we can use `owner-ref` to clean up all objects created by the chart.

Based on that analysis, I am okay with adding this API because it is useful for simple clients.  But, we should not force `roles` be 1:1 with `roleBindings` (something that was mentioned as a possibility by David), and we should not encourage use of this API for clients that need to garbage collect their role bindings.

**Comment by erictune** [comment]
The Subjects array of RoleBinding and ClusterRoleBinding should have struct tags: `patchStrategy:"merge" patchMergeKey:"name"`.

That way, users can use [StrategicMergePatch](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#strategic-merge-patch) on RoleBindings.  Let's add that in the beta API. 

I'm not sure this PR meets the bar once that change is made?

**Comment by liggitt** [comment]
`name` isn't an unambiguous patch key, is it? I think the key has to be name+kind+apigroup, right?

**Comment by deads2k** [comment]
> name isn't an unambiguous patch key, is it? I think the key has to be name+kind+apigroup, right?

Correct, I was about to say that :)

**Comment by liggitt** [comment]
even with an unambiguous patchKey, clients would still need to search existing rolebindings for one that referenced their desired role (or pre-fetch a rolebinding to make sure they weren't redefining an existing rolebinding to reference a different role), which means bindings still couldn't be included in a generic resource `List`

**Comment by erictune** [comment]
That could be corrected by splitting `subjects` into 3 arrays called `users`, `groups`, and `serviceAccounts`, with the following schemas:

```
type User struct {
        // Name of the object being referenced.
        Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
}
type Group struct {
        Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
}
type ServiceAccount struct {
        Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
        Namespace string `json:"namespace,omitempty" protobuf:"bytes,2,opt,name=namespace"`
}
```

This makes the yaml less verbose if there are many items, and makes clear that you cannot namespace a user or a group, and that you do namespace a service account.

**Comment by deads2k** [comment]
@erictune I'd like to keep the subjects unified and eventually loosen restrictions to make them more like object references.  Given kube's lack of opinion on user names, I suspect that we'll want to allow object references to actual user objects stored in a federated API server, or at least provide that option.

**Comment by kans** [comment]
@ericchiang asked me to comment here 

I work at CoreOS on our console.  Ideally, granting a user some permission would not require multiple API calls to upsert unwieldy, binding objects. `AddRoleRequest` and `RemoveRoleRequest` would be greatly appreciated.

**Comment by deads2k** [comment]
rebased

**Comment by liggitt** [comment]
I still think we need this or something like it

**Comment by ericchiang** [comment]
@liggitt Did we ever address @erictune's comments? It's been a while and the only thing I see in the sig auth notes is "Declarative vs imperative"

**Comment by ethernetdan** [comment]
Removing issue from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by liggitt** [comment]
direction seems to be fixed-name bindings for now

**Pull request closed without merging**
