### PR TITLE
Increased timeout while waiting for namespace deletion

### PR DESCRIPTION
**Pull request by piosz**
Removed waiting for namespace to be deleted in Density and Load e2e tests

### CODE REVIEW

**Comment by piosz** [comment]
@smarterclayton @roberthbailey

**Comment by piosz** [comment]
follow-up #12874, which broke e2e tests

**Comment by wojtek-t** [comment]
Thanks @piosz 

FYI: for scalability tests it takes ~30 minutes to delete namespace. There is already a work being done on #7372 to fix that, but now we can't do much about it (it's mostly deleting events, since there are ten of thousands of events in those tests, and we are rate-limited there).
The reason I didn't want to wait for the whole namespace deletion with those tests is because thanks to the fact that I'm waiting for previous namespace deletion at the beginning of the test (I know it's hacky), I'm able to save 30 minutes per run of deleting the last namespace at the end of the test (after that we're downing the whole cluster).

**Comment by smarterclayton** [comment]
With graceful pod deletion you will potentially have pods still on the nodes.  If that's ok for your tests (not running out of capacity) you should be fine it this.  Although I think the behavior of not cleaning up the last run deserves to be documented

**Pull request merged**
