### PR TITLE
Create a feature flag for Server-side Apply

### PR DESCRIPTION
**Pull request by apelisse**
This feature is described in https://features.k8s.io/555.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
failure above is just some typical `[sig-api-machinery] Garbage collector` flakes
/retest

**Comment by apelisse** [comment]
So I guess now we need to know how this gets merged :-)

**Comment by BenTheElder** [comment]
it's queue now, we'll still need to look at branch protection and the cla for this branch. not sure what happened with the latter.

**Comment by apelisse** [comment]
> the cla for this branch.

Might have missed a hook. Unlikely, but might have happened.

Otherwise, yes, that green button really wants to be clicked, doesn't it?

**Comment by BenTheElder** [comment]
> Otherwise, yes, that green button really wants to be clicked, doesn't it?

Yeah, we should *at least* get the CLA context required on this branch...

**Comment by apelisse** [comment]
It does. Submit-queue was complaining before I added the human-approval for cla.

**Comment by BenTheElder** [comment]
> It does. Submit-queue was complaining before I added the human-approval for cla.

the submit-queue is requiring it, but github is not.

**Comment by apelisse** [comment]
Looks like the bot is not going to pick it up.

**Comment by lavalamp** [comment]
I'm merging this, the delay is unnecessary and we've got a lot to do.

**Comment by BenTheElder** [comment]
@cjwagner. submit-queue is not working for feature branch, PRs never reach the top of the queue. If we're not ready to retire the submit-queue for k/k soon I'm inclined to patch it to fix this in the meantime...

**Comment by cjwagner** [comment]
Sure, Tide on k/k is probably going to take another week or two. 🤞
We still need to make sure token usage isn't a concern (probably using the github-cache), add docs, confirm that the proposed release process changes are acceptable, and announce the switch to kubernetes-dev.

**Pull request merged**
