### PR TITLE
Updated link to sysdig cloud for k8s specific page

### PR DESCRIPTION
**Pull request by KnoxAnderson**
---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30389)

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot ok to test

@KnoxAnderson we need a CLA signed.  Otherwise LGTM.

**Comment by brendandburns** [comment]
Also, can you clean up the top-level comment on this PR to remove the boilerplate.

**Comment by brendandburns** [comment]
Ping @KnoxAnderson this needs a signed CLA.

**Comment by KnoxAnderson** [comment]
@brendandburns sorry about that this got funneled into a different folder. I've signed the CLA, let me know if you need anything else.

**Pull request closed without merging**
