### PR TITLE
Migrate OWNERS file to apply the area/provider/gcp label

### LINKED ISSUE #85919: Migrate OWNERS file to apply the area/provider/gcp label, not sig/gcp
Some owners files attempt to auto apply the no longer existing `sig/gcp` label, which is now `area/provider/gcp`:

https://github.com/kubernetes/test-infra/pull/13677

This is present in 4 owners files:

https://github.com/kubernetes/kubernetes/search?q=%22sig%2Fgcp%22&unscoped_q=%22sig%2Fgcp%22

/assign @MrHohn @tallclair @x13n @mtaufen 

/area oncall-hotlist

```yaml
{
 insertId: "f9t4b6g2q7sd4z"  
 jsonPayload: {
  author: "pjh"   
  component: "hook"   
  event-GUID: "2efce600-16e1-11ea-9d2c-aeed2c99d7e8"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:119"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["sig/gcp"]"   
  org: "kubernetes"   
  plugin: "owners-label"   
  pr: 85466   
  repo: "kubernetes"   
  url: "https://github.com/kubernetes/kubernetes/pull/85466"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-12-04T22:00:00.566786830Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T21:59:55Z"  
}
```

### PR DESCRIPTION
**Pull request by MrHohn**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
`sig/gcp` label no longer exists.

**Which issue(s) this PR fixes**:

Fixes #85919

**Special notes for your reviewer**:
/assign @tallclair @x13n @mtaufen
/cc @fejta

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve
Thanks!!

**Comment by MrHohn** [comment]
/remove-lifecycle stale
Checking if anyone else can help approve this.
/cc @yujuhong @yliaog @pjh

**Pull request merged**
