### PR TITLE
Update Kubernetes logo usage guidelines

### PR DESCRIPTION
**Pull request by dankohn**
Based on advice from The Linux Foundation's trademark counsel.

Cc @bgrant0607 @thockin @sarahnovotny @brendandburns @philips @jbeda

### CODE REVIEW

**Comment by thockin** [comment]
This appears to have 2 effects, both of which I disagree with.

First, the logo was designed to be modifiable - many creative riffs have been made, including the KubeCon logo, which would be disallowed, by my reading.

Second, this appears to imply hat only unmodified code and binaries produced by "upstream" can use the logo, which would rule out thing s like OpenShift or even GKE, should we ever want to carry a patch.

Can we discuss he intentions?

**Comment by dankohn** [comment]
@thockin We can certainly discuss the intentions, though there may be a certain latency as I check with counsel on things.

My read on your second issue is that OpenShift and GKE will still be allowed to use the logo under the "your compliant implementation" wording. Of course, the real fix is for the K8s conformance [working group](https://ponymail.cncf.io/thread.html/Zaw9xi4cg7fx9v6) to fully define conformance and an associated branding program, but the changes proposed here were not intended to change the status quo around existing commercial use of the Kubernetes logo.

On the first point, you are correct that the wording change would prevent "mashups" of the Kubernetes logo. In particular, the LF trademark [guidelines](https://www.linuxfoundation.org/trademark-usage), under which the Kubernetes logo already falls, state that:

>A trademark should not be altered or amended in any way.... A logo should not be displayed with color variations, or with other elements superimposed on top of the logo.... A trademark should not be incorporated into your company's logos or designs.

I agree that the [KubeCon logo](http://events.linuxfoundation.org/events/cloudnativecon-and-kubecon-north-america) would probably otherwise be disallowed, but since CNCF owns both the Kubernetes and KubeCon trademarks, we can continue to use it.

Similarly, the K8s conformance working group can propose any sort of Kubernetes-related brand extensions (hopefully more original than Kubernetes inside or powered by Kubernetes) and the CNCF Governing Board can then approve those for use by conformant implementations. 

The main change our counsel was recommending that we address here was the ability for implementations to modify the logo.

**Comment by thockin** [comment]
Why is a logo mashup a bad thing?  The Linux penguin is famously used in
all sorts of mashups...

**Comment by dankohn** [comment]
[Tux](https://lmi.linuxfoundation.org/) the Penguin is an image created by Larry Ewing, and is not owned by The Linux Foundation. More generally, I am not aware of any company or foundation that encourages "mashups" of trademarked logos, out of fear that consumers might no longer associate the mark with just one source (i.e., it might cease to function as a trademark).

**Comment by thockin** [comment]
On Sat, Apr 15, 2017 at 8:57 PM, Dan Kohn <notifications@github.com> wrote:
>
> Tux the Penguin is an image created by Larry Ewing, and is not owned by The Linux Foundation. More generally, I am not aware of any company or foundation that encourages "mashups" of trademarked logos, out of fear that consumers might no longer associate the mark with just one source (i.e., it might cease to function as a trademark).

I ACK the concern, but I also want to point out that, while CNCF owns
KubeCon *now* it didn't always.  There have been a number of creative
uses of the base logo - can we find some way to allow it while
addressing the concerns?


https://www.google.com/imgres?imgurl=https%3A%2F%2Fraw.githubusercontent.com%2Ffabric8io%2Fkansible%2Fmaster%2Fdocs%2Fimages%2Flogo.png&imgrefurl=https%3A%2F%2Fgithub.com%2Ffabric8io%2Fkansible&docid=1KiPMiHrBSZ-VM&tbnid=hodbRPZPfjRUuM%3A&vet=10ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhEKAwwDA..i&w=800&h=800&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhEKAwwDA&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fd13yacurqjgara.cloudfront.net%2Fusers%2F681306%2Fscreenshots%2F2446192%2Fberlin-k8s_1x.png&imgrefurl=https%3A%2F%2Fdribbble.com%2Fshots%2F2446192-Berlin-Kubernetes-Meetup-Logo&docid=jzIiHMFygY_s0M&tbnid=8lNXwyuGPgCxFM%3A&vet=10ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwheKBwwHA..i&w=400&h=300&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwheKBwwHA&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fd13yacurqjgara.cloudfront.net%2Fusers%2F681306%2Fscreenshots%2F2345061%2Fnyc-k8s_1x.png&imgrefurl=https%3A%2F%2Fdribbble.com%2Fshots%2F2345061-New-York-Kubernetes-Meetup-Logo&docid=tSRH5uCSMUEiEM&tbnid=LEWgUDT2I4yabM%3A&vet=10ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhbKBkwGQ..i&w=400&h=300&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhbKBkwGQ&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=http%3A%2F%2Fblog.arungupta.me%2Fwp-content%2Fuploads%2F2016%2F09%2Fminikube-logo.jpg&imgrefurl=http%3A%2F%2Fblog.arungupta.me%2Ftag%2Fkubernetes%2F&docid=BWod8WvGIr5Q4M&tbnid=jEx2qkTHNlqJeM%3A&vet=10ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhnKCUwJQ..i&w=1044&h=296&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwjF45zn6arTAhUJzWMKHRBAAs8QMwhnKCUwJQ&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fraw.githubusercontent.com%2FInVisionApp%2Fkit%2Fmaster%2Fmedia%2Fkit-logo-horz-sm.png&imgrefurl=http%3A%2F%2Fblog.kubernetes.io%2F2016%2F09%2Fdeploying-to-multiple-kubernetes-with-kit.html&docid=qEngLwYl6sClgM&tbnid=_DWlVQ6SZt8wLM%3A&vet=10ahUKEwj357yH6qrTAhVQ4mMKHWdwB8o4ZBAzCB8oHDAc..i&w=256&h=142&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwj357yH6qrTAhVQ4mMKHWdwB8o4ZBAzCB8oHDAc&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FC1ucnN9WQAEC529.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Ffabric8io&docid=-v9uNSdpc83BbM&tbnid=v61ZsGK5XOXZQM%3A&vet=10ahUKEwj357yH6qrTAhVQ4mMKHWdwB8o4ZBAzCGYoYjBi..i&w=793&h=570&safe=off&bih=701&biw=1526&q=kubernetes%20logo&ved=0ahUKEwj357yH6qrTAhVQ4mMKHWdwB8o4ZBAzCGYoYjBi&iact=mrc&uact=8

**Comment by spxtr** [comment]
@k8s-bot ok to test

**Comment by philips** [comment]
I want to +1 @thockin's concern that the Kubernetes community, rightfully, feels some level of ownership over the Kubernetes logo at this point and we should figure out a way to accommodate. Where can we discuss this and come to a conclusion?

**Comment by dankohn** [comment]
We're still investigating some (possibly Phippy-related) solutions.

**Comment by dankohn** [comment]
Still chasing down poor, little Phippy (but some progress is being made). When Phippy is liberated, I'll have an iteration on this proposal.

**Comment by dankohn** [comment]
Please keep this open a little longer. I am expecting movement a resolution soon.

**Comment by dankohn** [comment]
I'm still working on this, please.

**Comment by bgrant0607** [comment]
Is this tied to the conformance effort now?

**Comment by dankohn** [comment]
Nope, it's orthogonal. The origin of this PR is advice from CNCF's trademark attorney to not allow modification of the Kubernetes trademark by users. As a trademarked logo, it should be used unmodified to avoid diluting the mark. 

Separately, the CNCF Governing Board can authorize any other usage. For example, the KubeCon logo is a derived work of the Kubernetes logo. Similarly, we're planning to kick off a Certified Kubernetes logo design process in the conformance WG, and the GB will need authorize the end result.

**Comment by thockin** [comment]
@dankohn Any updates on this?

**Comment by dankohn** [comment]
Still hoping for a Phippy-related resolution. Please give it another month or so.

**Comment by thockin** [comment]
I'm happy to let this sit in perpetuity :)

Second best would be to find language the lawyers can accept. :)

**Comment by thockin** [comment]
Dan, re-open when we're ready to have this discussion again?

**Pull request closed without merging**
