### PR TITLE
test/e2e/framework/service/:simplify function CreateTCPService and remove repeat const

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by aojea** [comment]
maybe use a different commit for each change?

**Comment by tanjunchen** [comment]
> maybe use a different commit for each change?

I think it should be OK to put them together

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
