### PR TITLE
Automated cherry pick of #67562: Prevent resourceVersion updates for custom resources on no-op writes

### PR DESCRIPTION
**Pull request by nikhita**
Cherry pick of #67562 on release-1.11.

#67562: Prevent resourceVersion updates for custom resources on no-op writes

### CODE REVIEW

**Comment by nikhita** [comment]
Currently, resourceVersion is incremented even for no-op writes for custom resources. This occurs because [metadata accessors](https://github.com/kubernetes/kubernetes/blob/e9de06d4dfd9ed6fd1524bab6d2c5a84eb0583dd/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L214) for `Unstructured` objects do not respect `omitempty` semantics for `ObjectMeta` fields.

Combined with ObjetMeta pruning (which respects `omitempty` semantics), this led to different bytes each time a custom resource was written to. Due to different bytes, resourceVersion was incremented.

Instead of updating the accessors (which could be a breaking change), we are making sure that we don't set the field in `BeforeUpdate` if it has the zero value. I will update the accessors in another PR against master.

More details in https://github.com/kubernetes/kubernetes/pull/67562, https://github.com/kubernetes/kubernetes/issues/67541#issuecomment-414051270.

/assign @foxish 
for cherry-pick approval

**Comment by nikhita** [comment]
/hold
until https://github.com/kubernetes/kubernetes/pull/67562 is merged

**Comment by nikhita** [comment]
Updated to reflect changes in  #67562.

**Comment by nikhita** [comment]
/hold cancel
https://github.com/kubernetes/kubernetes/pull/67562 has merged

**Comment by nikhita** [comment]
The labels are messed up because of https://github.com/kubernetes/test-infra/pull/9128. We need a prow bump to fix this.

**Comment by nikhita** [comment]
Closing and opening the PR to trigger prow to remove the `do-not-merge/cherry-pick-not-approved`.

**Comment by cjwagner** [comment]
Take 2 now that the plugin is actually enabled.
/assign
/close

**Comment by cjwagner** [comment]
Woohoo!
/unassign

**Pull request merged**
