### PR TITLE
[dependencies] update prometheus/client_golang v1.14.0 to v1.16.0

### PR DESCRIPTION
**Pull request by bzsuni**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
This PR is supposed to update prometheus/client_golang v1.14.0 to v1.16.0

This PR picks up https://github.com/prometheus/client_golang/pull/1278 which includes process start time in a header, which allows scraping clients to immediately start streaming and processing metrics rather than load the entire payload into memory first (since metrics are lexically ordered and process_start_time_seconds starts with a p and is therefore late in the payload.

Fixes # none

### CODE REVIEW

**Comment by dims** [comment]
/sig instrumentation

cc [@dgrisonnet](https://github.com/dgrisonnet)) [@brancz](https://github.com/brancz) ([@logicalhan](https://github.com/logicalhan)) for any inputs

**Comment by dims** [comment]
Differences for the main `go.mod` updates are:

- https://github.com/prometheus/common/compare/v0.37.0...v0.42.0
- https://github.com/prometheus/procfs/compare/v0.8.0...v0.10.1
- https://github.com/kubernetes/community/tree/master/sig-instrumentation

**Comment by logicalhan** [comment]
> Differences for the main `go.mod` updates are:
> 
> * [prometheus/common@v0.37.0...v0.42.0](https://github.com/prometheus/common/compare/v0.37.0...v0.42.0)
> * [prometheus/procfs@v0.8.0...v0.10.1](https://github.com/prometheus/procfs/compare/v0.8.0...v0.10.1)
> * https://github.com/kubernetes/community/tree/master/sig-instrumentation

We need this bump actually. There is a new feature in the prometheus golang client which we require in our of our KEPs.

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by logicalhan** [comment]
> @bzsuni @logicalhan can you please call out what the new functionality is in the PR body?

It includes this PR: https://github.com/prometheus/client_golang/pull/1278 which includes process start time in a header, which allows scraping clients to immediately start streaming and processing metrics rather than load the entire payload into memory first (since metrics are lexically ordered and `process_start_time_seconds` starts with a `p` and is therefore late in the payload.

**Comment by logicalhan** [comment]
I cannot modify the PR body, I do not have the perms.

**Comment by dims** [comment]
@logicalhan i can take care of that. thanks!

**Comment by dgrisonnet** [comment]
This is quite surprising that we can now bump prometheus/common, it used to blocked by https://github.com/kubernetes/kubernetes/issues/113366, when we tried it before in https://github.com/kubernetes/kubernetes/pull/114943.

**Comment by dims** [comment]
/assign @thockin 

(for api/ directory go.mod/sum updates)

**Review by thockin — COMMENTED** [review]
I was surprised to see no vendor/... changes outside of prometheus, but investigated and it is OK.

* golang.org/x/sync v0.1.0 vs v0.2.0 is test files only: https://github.com/golang/sync/compare/8fcdb60..1ea3257

* https://github.com/matttproud/golang_protobuf_extensions/tags v1.0.2 vs v1.0.4 is literally the same commit (??)

/lgtm
/approve

**Pull request merged**
