### PR TITLE
Use pflags string slice instead of internal util.StringList

### PR DESCRIPTION
**Pull request by eparis**
Simplifies our data structures and provides consistency with other command flags. Reduces (our) code too!

### CODE REVIEW

**Comment by pmorie** [comment]
+1 to this, killing `util.StringList` is reason enough to do this.

**Comment by eparis** [comment]
ok to test

**Comment by thockin** [comment]
LGTM

**Comment by dchen1107** [comment]
You have to rebase the pr first to get this merged. Sorry for the inconvenience.

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
rebasing AGAIN because of s|github.com/GoogleCloudPlatform|k8s.io/kubernetes|  blasted rebases!

**Comment by dchen1107** [comment]
Sorry, looks like you have to rebase it again.

**Comment by brendandburns** [comment]
PR changed after LGTM, removing LGTM.

**Comment by dchen1107** [comment]
This one is at the top of my merging queue.

**Pull request merged**
