### PR TITLE
hack: update logtools to v0.4.1

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Contains some bug fixes, for example allowing some additional functions when enforcing contextual logging.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/pull/111155#issuecomment-1380366174

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Looks like a lot of keys need to be updated before the stricter linting passes... :cry:

**Comment by knelasevero** [comment]
:cry: 

Can you add those in this PR?

**Comment by knelasevero** [comment]
@pohly 

I talked with @gustavomfc and he wanted to contribute to k8s, and I think this logtools update + key changes could be taken care by him. Do you mind if he would for these changes and submit his own PR?

**Comment by pohly** [comment]
I have updated the keys already, so let's focus on finishing the work in this PR. I asked for reviewers in #wg-structured-logging.

**Comment by serathius** [comment]
/lgtm
/approve

Great job on the linting!

**Comment by pohly** [comment]
> Great job on the linting!

@yangjunmyfm192085 deserves the credit for [tightening the checks](https://github.com/kubernetes-sigs/logtools/pull/6).

/assign @thockin 

For approval.

**Comment by pohly** [comment]
> conflict: hack/tools/go.mod

I had to rebase and thus lost the LGTM.

**Comment by pohly** [comment]
> conflict: pkg/controller/cronjob/utils.go

And one more rebase.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by pohly** [comment]
Looks like master added another non-compliant key - will fix on Monday.

**Comment by pohly** [comment]
I had to rebase to fix this change in master:
```
staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go:178:3: Key positional arguments "encObject.KeyID" are expected to be alphanumeric and start with either one lowercase or two uppercase letters. Please refer to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments. (logcheck)
		klog.V(2).InfoS("observed different key IDs when encrypting content using kms v2 envelope service", "uid", uid, "encObject.KeyID", encObject.KeyID, "statusKeyID", statusKeyID)
```

**Pull request merged**
