### PR TITLE
ran hack script upgrade for knp 0.0.27

### PR DESCRIPTION
**Pull request by jdnurme**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates knp to v0.0.27. This includes a memory leak fix for the network proxy

see: https://github.com/kubernetes/kubernetes/pull/106922

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Updates konnectivity-network-proxy to v0.0.27. This includes a memory leak fix for the network proxy
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
Please adjust the images in cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml and cluster/gce/manifests/konnectivity-server.yaml to match.

**Comment by rata** [comment]
Oh, sorry, didn't see this PR when I opened https://github.com/kubernetes/kubernetes/pull/107187. That one does update the manifests, but if you prefer to update this PR with that, I can close it :)

**Comment by cpanato** [comment]
@jdnurme @jkh52 @rata this CP is needed in this branch? or it is missing anything, I saw similar CP PRs for the other branches and those are already merged, should we move forward with this one or close it?
thanks!

**Pull request closed without merging**
