### PR TITLE
Automated cherry pick of #76656: Switch to instance-level update APIs for Azure VMSS loadbalancer operations

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #76656 on release-1.14.

Depends on #76753.

#76656: Switch to instance-level update APIs for Azure VMSS loadbalancer operations

Previously, VMSS API doesn't support configurations for each instance. Hence, Azure cloud provider upgrades manually for all instances whenever loadbalancer backend pools need to be updated. This would cause all instances restarted if there're also some other VMSS model changes.

To fix this issue, the PR switches to instance-level update APIs for Azure VMSS loadbalancer operations. It also upgrades Azure SDK to v21.4.0.

/kind bug
/priority critical-urgent
/sig azure

### CODE REVIEW

**Comment by justaugustus** [comment]
For SIG Azure & Release:
/lgtm
/approve

For deps:
/assign @sttts @cblecker

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Commented on the flake issue opened here: https://github.com/kubernetes/kubernetes/issues/73105#issuecomment-486914764
/test pull-kubernetes-kubemark-e2e-gce-big

**Comment by feiskyer** [comment]
ping @tpepper

**Comment by tpepper** [comment]
I'm worried about the state of azure/storage patch backports. And this one is a good example of why I'm not happy about this. This is a size/XL patch that feels like a new feature enabling as much or more than a critical bug fix.

But it was set to cherry pick to all branches 1.1[1234] and is merged in master (1.15) and 1.11 and 1.12, so it would be really odd to not merge in 1.13 and 1.14. :(

**Comment by feiskyer** [comment]
Rebased because of conflicts.

@tpepper The cherry pick fixes a critical bug of VMSS: all nodes may be rebooted at the same time on some conditions (see details in #71594). We need this change to ensure that doesn't' happen. Could you help to get this approved for 1.14?

**Comment by feiskyer** [comment]
@justaugustus @andyzhangx Need lgtm again because of rebase.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by jgsqware** [comment]
Do you know if this will be release in a 1.14 patch version?

**Comment by feiskyer** [comment]
@jgsqware yep, this cherry pick should be included in v1.14.2

**Comment by jgsqware** [comment]
Nice and any tip when it will go out?

**Comment by justaugustus** [comment]
@jgsqware -- you can find up-to-date information on patch releases here: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by jgsqware** [comment]
Excellent thank you!

**Pull request merged**
