### PR TITLE
kubeadm: UnversionedKubeletConfigMap is GAed in v1.25

### PR DESCRIPTION
**Pull request by pacoxu**
/kind cleanup
https://github.com/kubernetes/kubeadm/issues/2726

### CODE REVIEW

**Comment by neolit123** [comment]
/priority important-soon
/lgtm
/approve
/triage accepted
/milestone v1.25

thanks, closing my PR
https://github.com/kubernetes/kubernetes/pull/111151

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
@neolit123, would this change benefit from a release note?

**Comment by neolit123** [comment]
the release note was in the previous PR.

**Pull request merged**
