### PR TITLE
bump(fsouza/go-dockerclient): 42d06e2b125654477366c320dcea99107a86e9c2

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
i'm a redhat employee and my email should be in the commit.

@deads2k @smarterclayton ptal.

**Comment by derekwaynecarr** [comment]
I just recently bumped.  What new feature is this bringing out of curiosity?

**Comment by bparees** [comment]
So basically I was bumping s2i which meant I wanted to bump openshift
(since s2i is an openshift dep) which meant I got told to bump k8s. S2I was
way behind. It's possible I could just move s2i up to what openshift and
k8s have (I needed updated support for the current docker cfg), I didn't
look carefully at where that support went in, but I figured if i'm going to
bump, might as well get current.

**Comment by derekwaynecarr** [comment]
This lgtm once we get the cla issue worked out.

**Comment by bparees** [comment]
@derekwaynecarr anything i need to do on my side?

**Comment by bparees** [comment]
@googlebot i have signed the cla.

**Comment by ncdc** [comment]
FYI we're going to need to bump again because the snapshot of go-dockerclient in this PR breaks interactive TTY exec sessions (`kubectl exec -it ...`). It was broken by https://github.com/fsouza/go-dockerclient/commit/2acca39f3f43888c137219bff632db3c41fb3a5e and fixed by https://github.com/fsouza/go-dockerclient/commit/9702534da348f2aeafce8010d28a87d400cb724e.

I'll prep a new bump PR.

**Comment by ncdc** [comment]
New bump PR is #13324

**Pull request merged**
