### PR TITLE
fix time.Now()

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
fix  time.Now().Sub(startTime)   -->time.Since(startTime)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
Can't follow this:
> fix time.Now().Sub(startTime) -->time.Since(startTime),because startTime := time.Now()

**Comment by jianglingxia** [comment]
sorry I can not understand you point it that the change error or the note error？thanks @CaoShuFeng

**Comment by CaoShuFeng** [comment]
This change is code simplify which seems good to me.
But I can't understand the note:
> fix time.Now().Sub(startTime) -->time.Since(startTime),because startTime := time.Now()

Because because startTime := time.Now(), so we need this change?

**Comment by jianglingxia** [comment]
sorry，I just copy the line  startTime := time.Now() maybe want to reviewer know the assignment，I change the note it，thanks very much! @CaoShuFeng

**Comment by jianglingxia** [comment]
PTAL @derekwaynecarr   @kow3ns

**Comment by jianglingxia** [comment]
PTAL @derekwaynecarr thanks

**Review by xiangpengzhao — CHANGES_REQUESTED** [review]
Should revert the change on the header of one of the files. See the inline comment.

**Comment by xiangpengzhao** [comment]
/lgtm
/assign @derekwaynecarr
for approval.

**Comment by jianglingxia** [comment]
@derekwaynecarr 
thanks for approve

**Comment by jianglingxia** [comment]
for approve @derekwaynecarr  @deads2k 
thanks

**Pull request closed without merging**
