### PR TITLE
Remove unnecessary override of /etc/init.d/docker on containervm image.

### PR DESCRIPTION
**Pull request by dchen1107**
This was introduced by #20307 to change docker -d to docker daemon. It should be removed once we upgraded to the new containervm image, but obviously this one fall off the radar. 

I believe this one is causing a rare race which makes two docker daemons running on the master node of GKE.

cc/ @cjcullen @jlowdermilk

### CODE REVIEW

**Comment by davidopp** [comment]
@zmerlynn

**Comment by yujuhong** [comment]
Change LGTM since the override was meant to be a temporary solution. However, I am not sure what the race was and how it caused the failure...

**Comment by bgrant0607** [comment]
Every cherrypick needs a release note.

**Comment by bgrant0607** [comment]
Please create a cherrypick PR.

**Pull request merged**
