### PR TITLE
Optimize test cases cmd/kubeadm/app/cmd/upgrade/apply_test.go

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Review by yangjunmyfm192085 — COMMENTED** [review]
please execute goimports

**Review by neolit123 — COMMENTED** [review]
i don't see benefit of doing this optimization. the regular compare suffices here.

**Comment by muyangren2** [comment]
> i don't see benefit of doing this optimization. the regular compare suffices here.

I think it's a simplification, I'll close it if not, thanks

**Comment by muyangren2** [comment]
> 



> please execute goimports

yes ,i will do it,thanks

**Comment by neolit123** [comment]
/close
let's keep the old variant.

**Pull request closed without merging**
