### PR TITLE
Revert "Make MASTER_IP_RANGE master-only"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#13213

### CODE REVIEW

**Comment by piosz** [comment]
Jenkins is broken and this change may be the cause.

cc @roberthbailey @mbforbes  @yujuhong

**Comment by mbforbes** [comment]
Do we have any evidence?

This is only used in the master role by salt. It shouldn't even be on the nodes.

**Comment by piosz** [comment]
Nope, but we can't find the cause so we decided to revert all non-trivial changes from builds 4390, 4391, 4392 which causes fails for gce Job starting from run 8230. Will try to re-revert once the Jenkins will green again

**Comment by wojtek-t** [comment]
@mbforbes - Jenkins is red for ~12 hours now. We're not sure what happen so we are reverting all suspects right now. Once we're back to green we will try to re-revert it.

**Pull request merged**
