### PR TITLE
kubeadm UpdateMasterRoleLabelsAndTaints should not use recursion

### LINKED ISSUE #33913: kubeadm UpdateMasterRoleLabelsAndTaints should not use recursion

### PR DESCRIPTION
**Pull request by kenan435**
kubeadm UpdateMasterRoleLabelsAndTaints should not use recursion but iteration instead. 

Fixes #33913 

cc @kubernetes/sig-cluster-federation

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36497)

### CODE REVIEW

**Comment by kenan435** [comment]
@k8s-bot<https://github.com/k8s-bot> ok to test

**Comment by kenan435** [comment]
I signed it!

**Comment by xialonglee** [comment]
I think this PR #36625 has done this, you can take a look.

**Comment by kenan435** [comment]
@xialonglee agree. looks good.

**Pull request closed without merging**
