### PR TITLE
When prompting for passwords, don't echo to the terminal

### PR DESCRIPTION
**Pull request by brendandburns**
@deads2k 
@kubernetes/kubectl

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31586)

### CODE REVIEW

**Comment by jwforres** [comment]
cc @fabianofranz

**Comment by brendandburns** [comment]
@k8s-bot test this please issue: #23634

**Comment by fabianofranz** [comment]
@brendandburns We are just using `DisableEcho` from `docker/pkg/term` like [in here](https://github.com/openshift/origin/blob/master/pkg/cmd/util/terminal.go#L44). Other than masked input does `gopass` add anything that Docker's `term` doesn't provide? Looks pretty solid, it's just that I never heard of it before.

**Comment by brendandburns** [comment]
@fabianofranz it masks the characters, so that you get:

```
Enter Password: *******
```

Instead of
```
Enter Password:
```

Given that we don't currently vendor that Docker library, and that feature I'd just as soon use this library.

Thanks!
--brendan

**Comment by deads2k** [comment]
> Given that we don't currently vendor that Docker library, and that feature I'd just as soon use this library.

Ok.

**Comment by deads2k** [comment]
lgtm.

@fabianofranz we should probably be consistent downstream.  If tag an issue in origin `kind/post-rebase` it ought to percolate up after the next kube rebase.

**Comment by fabianofranz** [comment]
@brendandburns works for me, thanks! LGTM

@deads2k definitely, added https://github.com/openshift/origin/issues/10737

**Pull request merged**
