### PR TITLE
obselete SecurityContextDeny related code

### PR DESCRIPTION
**Pull request by tukwila**
What type of PR is this?

/kind cleanup

What this PR does / why we need it:

This PR delete all SecurityContextDeny admission plugin related functions and tests because it's going to be removed. See https://github.com/kubernetes/kubernetes/issues/111516.

and this PR is related to PR in test-infra:
https://github.com/kubernetes/test-infra/pull/29361

Which issue(s) this PR fixes:
This is step two of https://github.com/kubernetes/kubernetes/issues/111516.

Does this PR introduce a user-facing change?
```
The SecurityContextDeny admission plugin is going deprecated and will be removed in future versions.
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
- [KEP]: https://github.com/kubernetes/enhancements/issues/3785
- [Other doc]: https://k8s.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny
- [Issue]: https://github.com/kubernetes/kubernetes/issues/111516
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/ok-to-test

**Comment by cici37** [comment]
/sig auth
/remove-sig api-machinery
Is this PR a cleanup or deprecation? Extra info: we will use the label in the PR for CHANGLOG updates.

**Comment by tzneal** [comment]
I *think* this is blocked on the docs PR and identifying/reaching out to users.

/cc @mtardy

**Comment by mtardy** [comment]
> I _think_ this is blocked on the docs PR and identifying/reaching out to users discussed in #111516
> 
> /cc @mtardy

ah wow just discovered this PR. I have been working for months to finally create this very PR 🥲... I can/would love take over the cleanup if you want.

**Comment by mtardy** [comment]
Hey @tukwila I think it's nice you wanted to help but I was planning to do that and merge that in a few versions (1.28 or later). To be very honest, It's the most satisfying part of that "project" and I would have loved to handle and write that PR 😔. I don't really know what is the usual way to "claim" a PR in k8s but I was still working on the earlier items...

**Comment by tukwila** [comment]
> Hey @tukwila I think it's nice you wanted to help but I was planning to do that and merge that in a few versions (1.28 or later). To be very honest, It's the most satisfying part of that removal surely and I would have loved to handle and write that PR! However if you really wanted to do that I could help, it does not really matter in the end!

Hi, @mtardy  i hope that i really helped on your discussion. i also checked test-infra. Pls review them all. Thank you :-)

**Comment by enj** [comment]
> > I _think_ this is blocked on the docs PR and identifying/reaching out to users discussed in #111516
> > /cc @mtardy
> 
> ah wow just discovered this PR. I have been working for months with discussion to finally be able to create this very PR 🥲...

@tukwila thanks for the PR; however, I am going to close this and let @mtardy handle this work since he brought it to SIG Auth and has carried it through.  Please coordinate with the folks organizing the work before making a PR in the future.  Thank you!

/close

**Pull request closed without merging**
