### PR TITLE
Use CEL EagerlyValidateDeclarations to improve compilation performance

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR is a replay of https://github.com/kubernetes/kubernetes/pull/108954 which be reverted from 1.24

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
I raised this pr as we talked earlier this morning. Would you mind to take a look when have time? Thank you :) @jpbetz

**Comment by jpbetz** [comment]
/lgtm

This looks like the previous PR,  I don't see any issues with reapplying it now that CEL is bumped to latest version.

**Comment by jpbetz** [comment]
@liggitt would you approve if this looks okay to you? This looks to be an accurate replay of https://github.com/kubernetes/kubernetes/pull/108954

**Pull request merged**
