### PR TITLE
Fix followups from #31033

### PR DESCRIPTION
**Pull request by mml**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31194)

### CODE REVIEW

**Comment by mml** [comment]
I'll rebase this after #31033 merges.

**Comment by mml** [comment]
@davidopp this should be good to go.

**Comment by goltermann** [comment]
@mml @davidopp Can you get a review/LGTM soon if this is to go in 1.4?

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
