### PR TITLE
Add hack/lib to kubernetes release tarball

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Add hack/lib to kubernetes release tarball, to fix an issue with https://get.k8s.io/ script introduced in #42748.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/pull/42748#issuecomment-295412268

**Special notes for your reviewer**:
I'm new to bazel, so hopefully I'm not off-base here :)

**Release note**:

```release-note
NONE
```

cc: @ixdy @dcbw @smarterclayton

### CODE REVIEW

**Comment by ixdy** [comment]
Thanks! Because we currently have two ways of doing things ( :( ) we need to update `kube::release::package_final_tarball` in `build/lib/release.sh`, too.

**Comment by cblecker** [comment]
@ixdy updated

**Comment by ixdy** [comment]
/lgtm

thanks!

**Pull request merged**
