### PR TITLE
WIP: "kubectl explain" can display fields by categories

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**
/kind documentation

KEP: https://github.com/kubernetes/enhancements/pull/1156

**What this PR does / why we need it**:

"kubectl explain" displays the fields of an object by alphabetic order.

It would be easier for beginners to see the most important fields first, and also to categorize the fields, and display them by category.

**Does this PR introduce a user-facing change?**:

```release-note
kubectl explain display fields by category instead of by alphabetic order (when available)
```

## Categorize
To categorize the fields of a structure, it is necessary to add comment lines to fields: 
```
// +k8s:openapi-gen=x-kubernetes-explain-category:1.category-name
```
where the number helps to order the categories.

It is also possible to order the fields without introducing categorie names, for example in smaller objects, or for the first fields of a big object:
```
// +k8s:openapi-gen=x-kubernetes-explain-category:1.
```

## Recursively expanding

To recursively display an object field, you can mark it with this annotation:
```
// +k8s:openapi-gen=x-kubernetes-explain-expand:1.
```

### CODE REVIEW

**Comment by jbeda** [comment]
Interesting idea! Thoughts: 
* We want to make sure that this doesn't get overloaded to play double duty in other contexts like kubectl display. Perhaps out "doc" in the annotation name?
* Do we perhaps want to specify what should be recursively expanded by default too? That way we could have the right mix of full docs and the right subobjects. 

Would love to hear Tims thoughts.

**Comment by feloy** [comment]
@jbeda, yes I agree with the first proposition, and find the second very interesting. I'll make some changes to test it.

**Comment by apelisse** [comment]
I think you should write a KEP for this. The format of the fields would become part of the API (both for kubectl and potentially to generate docs, etc). Thanks.

**Comment by liggitt** [comment]
Thanks for the review request, will tag once the KEP is accepted.

https://go.k8s.io/api-review#mechanics:
> The goal of the proposed change has agreement from the appropriate sub-project owners and/or SIG leads

/remove-label api-review

**Pull request closed without merging**
