### PR TITLE
Tag storage windows tests with [Feature:Windows] instead of [sig-windows]

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/kubernetes/issues/98326

Based on discussion in https://github.com/kubernetes/kubernetes/issues/98326#issuecomment-784507891

```release-note
NONE
```

/kind cleanup
/priority important-longerm

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold 

To ensure it will be lgtm-ed by both storage and windows folks.

**Comment by msau42** [comment]
/lgtm
/approve
cc @jingxu97

**Comment by marosset** [comment]
/lgtm
Let's verify the tests run in the pull-kubernetes-e2e-aks-engine-windows-containerd I just triggered before removing the hold :)

**Comment by wojtek-t** [comment]
@marosset - where is the job to compare against?
Looking into: https://testgrid.k8s.io/sig-windows-signal#aks-engine-azure-windows-master-containerd I don't see either of those tests being run even without this PR...

**Comment by marosset** [comment]
Hmm, it looks like these tests were tagged with vSphere and don't run on the Azure clusters I triggered the PR job for.
@jayunit100, @ddebroy, @jingxu97 do we have PR jobs we can trigger to verify any of these jobs still run after the rename?

```
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (ntfs)][sig-windows] volumes should store data
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Inline-volume (ntfs)][sig-windows] volumes should allow exec of files on the volume
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Inline-volume (ntfs)][sig-windows] volumes should store data
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Pre-provisioned PV (ntfs)][sig-windows] volumes should allow exec of files on the volume
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Pre-provisioned PV (ntfs)][sig-windows] volumes should store data
```

**Comment by wojtek-t** [comment]
@marosset - so given it doesn't seem to regress, can we maybe merge this?

/assign @spiffxp  [for thoughts]

**Comment by marosset** [comment]
> @marosset - so given it doesn't seem to regress, can we maybe merge this?

Sounds good to me

**Comment by wojtek-t** [comment]
Thanks!

/hold cancel

**Pull request merged**
