### PR TITLE
properly skip cadvisor proxy test

### PR DESCRIPTION
**Pull request by krzyzacy**
xref https://github.com/kubernetes/kubernetes/issues/64158

per https://github.com/kubernetes/kubernetes/issues/64158#issuecomment-393229314

/assign @liggitt @AishSundar

### CODE REVIEW

**Comment by krzyzacy** [comment]
cc @luxas @dixudx

**Comment by liggitt** [comment]
/lgtm

sorry for steering you wrong before

**Review by luxas — APPROVED** [review]
Thanks @krzyzacy, LGTM!

**Comment by krzyzacy** [comment]
gah, fixed gofmt

**Comment by krzyzacy** [comment]
for cherrypick approval

**Pull request merged**
