### PR TITLE
Fix wrong indentation in shell

### PR DESCRIPTION
**Pull request by hainesc**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix a wrong indentation in shell script

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/sig testing
/ok-to-test
/priority backlog

**Comment by hainesc** [comment]
ping @neolit123 PTAL.
Thanks.

**Pull request merged**
