### PR TITLE
Spark example

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by preillyme** [comment]
@mattf — This is Spark workers using Spark's [standalone mode](http://spark.apache.org/docs/latest/spark-standalone.html) correct?

**Comment by mattf** [comment]
@preillyme that's correct

**Comment by jayunit100** [comment]
https://github.com/mattf/docker-spark/blob/master/worker/start.sh <-- i snooped around and found the dockerfiles for this that you're useing :) ... I think you will want you're containers to *not* tail the logs as the final line, as this would dupe kube into thinking that the process is running even if it fails.     Its not a show stopper, but you might want to mention this as a warning in you're README, because if a container fails, it would be confusing for kube

**Comment by jayunit100** [comment]
also, does this work when master_ip != service_ip ?  iirc we had that akka issue where the reverse resolution got rejected from master?

**Comment by timothysc** [comment]
Hats off to @mattf and Armbrust on the akka trick.

**Comment by jayunit100** [comment]
I did some tests of this, for fun :) 
- *killing all the slaves* doesnt bring the cluster down.  they come back online and seem to work okay. 
- From my tests, it seems that *killing the master* generally causes some problems.   i didnt dig too deep, but just something to note which might be a good next iteration, is confirming resiliency of the local_ip trick.

In any case, its a great   patch ! please just add the links to your dockerfiles repo to the README and I think otherwise, i can certainly say its tested and works.

**Comment by pires** [comment]
LGTM just need pointers to the Dockerfiles and other sources used in the example!

**Comment by mattf** [comment]
@pires i used the docker hub auto build system so that all the build information is trivially discoverable without having to duplicate it in the example. there's no extra effort required and nothing about the build is hidden or concealed.

**Comment by pires** [comment]
@mattf but you could point to your repo in the documentation, much like I did in the `examples/hazelcast`.

**Comment by mattf** [comment]
@pires how's that?

**Comment by pires** [comment]
@mattf nevermind, it's there. Thanks

**Comment by cjcullen** [comment]
@mattf this is great. Can you squash commits?

**Comment by preillyme** [comment]
I agree with and :+1: what @timothysc said well done @mattf

**Comment by mattf** [comment]
@cjcullen i had to force it, how's that? generally i dislike losing history. what's the motivation?

**Comment by cjcullen** [comment]
Motivation is just to keep the commit history as clean (readable) as possible on master. This looks great. Thanks.

**Comment by ihmccreery** [comment]
@mattf This is great, thanks for making this contribution.  I think it would also be great to get documentation on Spark's end about this, maybe linked to from their [Cluster Mode Overview](https://spark.apache.org/docs/latest/cluster-overview.html).  Is that something you've considered or are pursuing?

Thanks again for your contributions.

**Comment by mattf** [comment]
@ihmccreery i wasn't planning on it. you should feel free to. if you do, ping me and i'll help review the pr.

**Pull request merged**
