### PR TITLE
Updating OWNERS_ALIASES for SIG-Windows

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates sig-windows-api-reviewers and feature-approvers in owners aliases file.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig windows
/triage accpted

### CODE REVIEW

**Comment by jsturtevant** [comment]
@marosset could you rebase this?

**Comment by dims** [comment]
/test all
/skip
/assign @liggitt @thockin 

Jordan, Tim, this has sig-windows updating their roster, please approve

**Comment by liggitt** [comment]
matches https://github.com/kubernetes/community/tree/master/sig-windows#leadership

/approve

**Pull request merged**
