### PR TITLE
WIP: test images: Replace pause image usage with agnhost

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by kbruner** [comment]
Hello from the bug triage team! This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting June 25th (about 4 from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.19, is it still planned for this release?

**Comment by kbruner** [comment]
@claudiubelu @kubernetes/sig-windows-misc There has been no activity on this PR in two months. Should it still be in the v1.19 milestone?

**Comment by michmike** [comment]
@adelina-t or @claudiubelu can you please comment on this?
thanks!

**Comment by claudiubelu** [comment]
Indeed, I've talked about this with a few other people, and they were saying that it's still a good idea to keep the Pause image for testing purposes, making sure that newly built and release pause images are ok.

**Pull request closed without merging**
