### PR TITLE
Automated cherry pick of #128305: Ensure that a node's CIDR isn't released until the node is deleted

### PR DESCRIPTION
**Pull request by adrianmoisey**
Cherry pick of #128305 on release-1.31.

#128305: Ensure that a node's CIDR isn't released until the node is deleted

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.31 regression where PodCIDR was released before node was deleted
```

Fixes https://github.com/kubernetes/kubernetes/issues/127792

### CODE REVIEW

**Comment by adrianmoisey** [comment]
> If you **didn't cherry-pick** this change to [**all supported release branches**](https://k8s.io/releases/patch-releases), please leave a comment describing why other cherry-picks are not needed to speed up the review process.

This bug was first discovered in Kubernetes 1.31, so only cherry-picked into that branch.

/kind bug

**Comment by adrianmoisey** [comment]
Apologies to anyone who saw the noise of me struggling to make a cherry-pick PR, turns out my personal fork was forked back in 2017 and I was using an old copy of `hack/cherry_pick_pull.sh`

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by xmudrii** [comment]
We're already past the cherry-pick deadline for the November patch releases, but we'll make sure to merge this for the December patch releases.

@aojea Is this only affecting v1.31 or prior releases are affected as well?

**Comment by adrianmoisey** [comment]
> We're already past the cherry-pick deadline for the November patch releases, but we'll make sure to merge this for the December patch releases.
> 
> @aojea Is this only affecting v1.31 or prior releases are affected as well?

From the bug report (https://github.com/kubernetes/kubernetes/issues/127792) it's only affecting v1.31 onwards

**Comment by xmudrii** [comment]
@adrianmoisey Thanks for the information. I'll keep an eye on this cherry-pick and merge it after releases are done.

**Comment by adrianmoisey** [comment]
Thank you!

**Comment by aojea** [comment]
@adrianmoisey if you added the Fixes: thing to the description the bot will close https://github.com/kubernetes/kubernetes/issues/127792 once it merges

**Comment by adrianmoisey** [comment]
> @adrianmoisey if you added the Fixes: thing to the description the bot will close #127792 once it merges

I did do that here: https://github.com/kubernetes/kubernetes/pull/128305#issue-2610587050

I assume I pasted the whole URL and not the issue number, which is why it didn't work.

**Comment by aojea** [comment]
you have to add it to this description, the one in this PR, the issue got reopened for the backport

**Comment by adrianmoisey** [comment]
Whoops, my reading skills are lacking again. Thanks

**Comment by aojea** [comment]
@xmudrii the linter job is something we are going to ignore in this case, since is a backport and the test will assert later on a condition that will not happen if this method fails

> ERROR: pkg/controller/nodeipam/ipam/range_allocator_test.go:929:27: Error return value of `rangeAllocator.syncNode` is not checked (errcheck)
ERROR: 			rangeAllocator.syncNode(tCtx, tc.nodeKey)
ERROR: 			                       ^

I can not find the issue but we already discussed that this behavior is not desired, as code was working but not linter existing at that time, it gets modified but the commit needs to be reverted, the revert now fails the linter

**Review by xmudrii — APPROVED** [review]
Thanks @aojea! For RelEng:
/lgtm
/approve

**Comment by adrianmoisey** [comment]
> @xmudrii the linter job is something we are going to ignore in this case, since is a backport and the test will assert later on a condition that will not happen if this method fails
> 
> > ERROR: pkg/controller/nodeipam/ipam/range_allocator_test.go:929:27: Error return value of `rangeAllocator.syncNode` is not checked (errcheck)
> > ERROR: 			rangeAllocator.syncNode(tCtx, tc.nodeKey)
> > ERROR: 			                       ^
> 
> I can not find the issue but we already discussed that this behavior is not desired, as code was working but not linter existing at that time, it gets modified but the commit needs to be reverted, the revert now fails the linter

I made https://github.com/kubernetes/kubernetes/pull/128856 to fix this going forward. It never made it into the original PR, hence why it's missing from the back port.

**Pull request merged**
