### PR TITLE
upgrade Azure/go-autorest/autorest to v0.11.27

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
upgrade Azure/go-autorest/autorest to v0.11.27
This PR has fix: https://github.com/Azure/go-autorest/pull/669, also increases the timeout value from 0.5s to 2s which fixes the slow IMDS response issue in some cases.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
/kind bug
/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted

#### Does this PR introduce a user-facing change?

```release-note
upgrade Azure/go-autorest/autorest to v0.11.27
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
upgrade Azure/go-autorest/autorest to v0.11.27
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/assign @thockin @smarterclayton 

(for root owner approval)

**Review by thockin — COMMENTED** [review]
vendor/github.com/Azure/go-autorest/autorest/adal/README.md says "This module will go out of support by March 31, 2023.  For authenticating with Azure AD, use module [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) instead"

What's the plan there?

/approve

**Comment by andyzhangx** [comment]
> vendor/github.com/Azure/go-autorest/autorest/adal/README.md says "This module will go out of support by March 31, 2023. For authenticating with Azure AD, use module [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) instead"
> 
> What's the plan there?
> 
> /approve

Hi @thockin, this is related to [Credential provider extraction plan](https://github.com/kubernetes/enhancements/pull/1406), once we use the standalone Credential provider out of k/k, we don't need this lib anymore. And btw, we don't upgrade this lib regularly unless we found some bugs, and this PR is for fixing one timeout setting issue.

**Pull request merged**
