### PR TITLE
Update flag-dash whitelist

### PR DESCRIPTION
**Pull request by eparis**
PRs older than the verifier landed in HEAD.  So update the whitelist

### CODE REVIEW

**Comment by krousey** [comment]
cc @brendandburns

**Comment by thockin-cc** [comment]
Are we keeping the whitelist forever?  It's sort of annoying...

**Comment by brendandburns** [comment]
Agree, we should do a better job of figuring out what is a flag and what isn't.  (seems like we should only look for `flags.<foo>`

**Comment by eparis** [comment]
It was actually really hard to add a new flags.*Var("flag_name") and the normalization function would complain at compile time. Its the docs, scripts, examples, etc that had problems.  And figuring out what is a flag and what isn't in those files is the hard ?impossible? part...

**Comment by eparis** [comment]
I do have a thought on how to make the regex better to trim down false positives (and thus a shorter whitelist)  I'll give it a shot, but I know there will still be quite a few.  Especially places where say the salt stack uses `flag_name` as the variable it is going to pass to `flag-name`

**Comment by brendandburns** [comment]
strikes me that looking for a leading '-' or '--' in the variable might be a decent start ;)

**Pull request merged**
