### PR TITLE
Changed udpIdleTimeout to 1 second from 10 seconds

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
Helps with #12144
Verified manually that dig calls work

for i in $(seq 1 15000); do dig @10.0.0.10 kubernetes.default.svc.cluster.local | grep ";; Query time:" | cut -d " " -f 4; done

**Comment by alex-mohr** [comment]
@artfulcoder please pick a reviewer?

**Comment by thockin** [comment]
lgtm

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
