### PR TITLE
Add link to `CHANGELOG.md`

### PR DESCRIPTION
**Pull request by guyzyl**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The current `CHANGELOG.md` file references the `CHANGELOG/README.md` file, but doesn't link to it.
This PR adds a link to `CHANGELOG/README.md` from  `CHANGELOG.md`, making it easier to navigate to it.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by guyzyl** [comment]
This is a very small change, @derekwaynecarr
 or @johnbelamaric can you please look it over?

**Comment by zhsj** [comment]
hi, this PR breaks the symlink.

It's a symlink, not a real markdown file. So you shouldn't change the content manually.

image

**Comment by aimuz** [comment]
This change may need to be rolled back

**Pull request merged**
