### PR TITLE
Update import-boss restrictions - pkg/kubemark

### LINKED ISSUE #68201: Upate import-boss restrictions
`hack/verify-import-boss.sh` is a tool we use to reduce technical debt around rampant interdepencies between packages in the main k/k repository.

The tool uses a file `.import-restrictions` in some directories that verify-import-boss.sh then uses to check. The syntax for the file is here:
https://github.com/kubernetes/code-generator/blob/master/cmd/import-boss/main.go#L32-L52

We currently have the following `.import-restrictions` in the main k/k repository:
```
[dims@dims-mac 19:00] ~/go/src/k8s.io/kubernetes ⟩ find  . -name .import-res*
./cmd/kubeadm/.import-restrictions
./pkg/.import-restrictions
./pkg/api/testing/.import-restrictions
./pkg/client/clientset_generated/.import-restrictions
./pkg/controller/.import-restrictions
./pkg/kubectl/.import-restrictions
./pkg/kubemark/.import-restrictions
./pkg/printers/.import-restrictions
./pkg/printers/internalversion/.import-restrictions
./staging/src/k8s.io/apiserver/.import-restrictions
./staging/src/k8s.io/code-generator/cmd/lister-gen/.import-restrictions
```
What needs to be done?
- Open up the `.import-restrictions` file, check if `AllowedPrefixes` under different `Rules` are correct. 
  - The packages listed are still being used in the code under the pacakge
  - If there are outside packages that are used, but not listed under `AllowedPrefixes` then add those packages
- Possibly add new .import-restrictions for different directories under `/staging/src/k8s.io/` so we can be sure each directory under that is self-contained.
- If the .import-restrictions looks correct, then leave a comment in this issue so others don't duplicate the work. If you want to work on a specific file, leave a note so others don't spend their time on the same work.

Prior art (see how we did this in earlier PRs):
- https://github.com/kubernetes/kubernetes/pull/35148
- https://github.com/kubernetes/kubernetes/pull/53458
- https://github.com/kubernetes/kubernetes/pull/63740

/good-first-issue

### PR DESCRIPTION
**Pull request by mrajashree**
**What this PR does / why we need it**:
This PR updates the import-restrictions in pkg/kubemark

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Refs #68201

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by mrajashree** [comment]
I have just now signed the CLA as per this comment https://github.com/kubernetes/kubernetes/pull/68307#issuecomment-418899556

**Comment by mkenigs** [comment]
Not sure if it's correct but I used go list -f '{{ join .Deps  "\n"}}'

**Comment by dims** [comment]
@mrajashree this needs a rebase and a broken CI job (please look at the logs of the verify job)

**Pull request closed without merging**
