### PR TITLE
Enable update tests in federated namespace controller

### PR DESCRIPTION
**Pull request by mwielgus**
Previously it was disabled because of flakiness.

cc: @nikhiljindal @madhusudancs

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37659)

**Comment by madhusudancs** [comment]
@saad-ali this uncomments a test. I have added the `cherrypick-candidate` label but it is not critical for v1.5.0. It can be cherrypicked after the v1.5.0 release. But PTAL.

**Comment by dims** [comment]
@madhusudancs looks like this stays on 1.5 milestone

**Comment by saad-ali** [comment]
> @saad-ali this uncomments a test. I have added the cherrypick-candidate label but it is not critical for v1.5.0. It can be cherrypicked after the v1.5.0 release. But PTAL.

What is the original PR this is cherry picking?

**Comment by saad-ali** [comment]
@k8s-bot unit test this

**Comment by saad-ali** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cvm gce e2e test this

**Comment by saad-ali** [comment]
@k8s-bot kops aws e2e test this

**Comment by madhusudancs** [comment]
kops failure seems legitimate, but unrelated to this PR. 

@mwielgus may be rebase the PR?

**Comment by mwielgus** [comment]
@k8s-bot test this

**Pull request merged**
