### PR TITLE
Automated cherry pick of #47731

### LINKED ISSUE #47597: Endpoint removal delayed when pod is deleted (1.6)
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):
No
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
endpoints stale removed
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.6.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux ip-10-10-10-10 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

3 node etcd cluster with quorum reads on.

**What happened**:
We observe transient connection failures between pods when they are being destroyed. Upon further investigation, we discovered endpoints are not being removed when the pod is deleted. In cases of failures, the endpoint was not removed at all during termination time, until the pod finally completed (after about 10s). In other non-fatal cases we observed endpoint removal delays of several seconds. It's still not clear yet whether it's just slow to update or whether it simply doesn't remove the endpoint for some reason.

**What you expected to happen**:
Endpoint should be removed immediately, or shortly after (<1s), when running `kubectl delete pod my-pod`.

**How to reproduce it** (as minimally and precisely as possible):
1. Observe endpoints with `kubectl get ep my-eip -o go-template='{{ range (index .subsets 0).addresses }} {{ .ip }} {{ end }}'`.
2. Delete the oldest pod, wait for replicaset controller to scale up a new one.
3. Wait a few seconds
4. Repeat 2.

We observe the stale endpoints with kubectl, as well as directly on nodes themselves by observing iptables.

**Anything else we need to know**:

This only started happening to us recently, in the last few weeks after we upgraded to 1.6 from 1.4. It could also be related to the fact we enabled quorum reads, as we were experiencing similar types of problems with stale kube-proxy updates that we were unable to pinpoint, and thought that would help.

Other notes:
* Using etcd2.3.7, 3 node cluster
* About 240 services/endpoints in this cluster, spread across 7 16 core nodes (pretty small, I think)
* Using leader election / multi master

### PR DESCRIPTION
**Pull request by jsravn**
Cherry pick of #47731 to fix #47597.

```release-note
Improve time to update endpoints by reducing number of API calls.
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@jsravn - please squash commits in this PR.
Also, we need user-friendly release note for it (sth like improve performance of endpoint controller by reducing number of API calls or sth like that).

**Comment by jsravn** [comment]
@wojtek-t done.

**Pull request merged**
