### PR TITLE
Automated cherry pick of #78012: Upgrade Azure network API version to 2018-07-01

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #78012 on release-1.14.

#78012: Upgrade Azure network API version to 2018-07-01

### CODE REVIEW

**Comment by justaugustus** [comment]
For SIG Azure & SIG Release:
/lgtm
/approve

though I will echo the sentiment from #78012 that we need to ensure we make a concrete plan to minimize the size of our cherry picks moving forward.

**Comment by feiskyer** [comment]
@dims Could you help to approve the godep updates?

**Comment by tpepper** [comment]
/hold

Why is this not a feature? I get the rationale in #78065 for master, but here I'm not as convinced it applies.

**Comment by feiskyer** [comment]
> Why is this not a feature? I get the rationale in #78065 for master, but here I'm not as convinced it applies.

it's a bug fix: without this, if users have configure EnableTcpReset on their loadbalancer, then all Kubernetes LoadBalancer services would be stuck in pending state.

**Comment by justaugustus** [comment]
I'm okay with the rationale here, so I'm lifting the hold. This should enable much smaller, concise bug fixes for Azure services once merged.
/hold cancel

**Comment by cblecker** [comment]
Similar to #78065, I want to review this more closely before merge.

/hold

**Comment by feiskyer** [comment]
ping @cblecker

**Comment by liggitt** [comment]
> it's a bug fix: without this, if users have configure EnableTcpReset on their loadbalancer, then all Kubernetes LoadBalancer services would be stuck in pending state.

Is `EnableTcpReset` a new feature in Azure? I'm wondering why this bug was not reported previously.

reasons to merge:
* it is fixing a bug
* the impact on kubernetes code is negligible
* the risk is contained to the azure provider and cloud environment

Cons:
* as far as I can tell, it is not fixing a regression

I'm slightly in favor of merging, especially if the Azure team considers this bug important enough to bear the risk of the dependency bump.

**Comment by tpepper** [comment]
I'm uncomfortable with this change similar to Jordan's comment at https://github.com/kubernetes/kubernetes/pull/78066#issuecomment-498691090 but also for the reasons listed there (isolation to Azure and their emphasis on this as critical fix) I'm going to grudgingly approve this.

**Comment by feiskyer** [comment]
@liggitt @tpepper thanks.

> Is EnableTcpReset a new feature in Azure? I'm wondering why this bug was not reported previously.

Yep, it's a new feature in new Azure API. And it's not backward compatible when users set this option on LB.  Hence, in cloud provider, we need to upgrade API versions to not break this feature.

**Comment by liggitt** [comment]
> Yep, it's a new feature in new Azure API. And it's not backward compatible when users set this option on LB. Hence, in cloud provider, we need to upgrade API versions to not break this feature.

That doesn't make sense to me. I would not expect patch releases to enable new cloud provider features.

**Comment by liggitt** [comment]
Knowing this is making older versions of kubernetes work with a new cloud provider feature, I am now solidly of the opinion that this should not have been backported.

**Comment by cblecker** [comment]
Wait, this was supposed to be a bug, not a new feature.

I agree, @liggit. This should not have been backported.

**Comment by feiskyer** [comment]
> That doesn't make sense to me. I would not expect patch releases to enable new cloud provider features.

To be clear, it's a new Azure feature, not cloud provider feature. When users are using this new feature on Azure, because cloud provider is using old api version, the original cloud provider feature would be broken.

**Comment by liggitt** [comment]
> Sorry, maybe I'm not clear about this new feature. It's a new Azure feature, not cloud provider feature. Cloud provider won't enable this feature for users, but users could use it from Azure's portal (or other clients).

Right. In general, I would not expect patch releases in kube to fix interactions with new features introduced in a cloud provider's environment (especially when those are opt in features)

**Pull request merged**
