### PR TITLE
Set weight of PodTopologySpread Score to 2

### LINKED ISSUE #88174: Increase the default weight of pod topology spread
**Problem:**
Preferred pod/node affinity and preferred PodTopologySpread may not be respected because of conflicts with other scoring functions, like node utilization or image locality.

Scheduler Scoring functions have weights, by default they are all set to 1 (apart from one): https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithmprovider/registry.go#L118-L125. Having equal weights is problematic because of the way we score: each Scoring plugin returns a score [0, MaxScore], which get multiplied by the configured weight of the plugin, and a node score is the sum over all scores. Therefore, even if the user explicitly indicates that they prefer to place pod x on node y, this preference may not be respected and the scheduler may decide to place the pod on node z because it has lower usage and the container that the pod is requesting.

**Proposed Solution:**
Scoring functions that allow users to explicitly express preference should have higher weights than generic scoring functions. This includes: inter-pod affinity, node affinity, taint/toleration and pod topology spread.

This issue is proposing to change the default behavior of the scheduler, I am not sure how k8s deprecation policy applies here, although I would argue that this change should help the scheduler make decisions closer to users expectations.

We will start with pod topology pod spread since as of creating this issue, the feature is still in beta.

/sig scheduling

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Double weight of PodTopologySpread Score, because:

- This is a score coming from user preference.
- It makes its signal comparable to NodeResourcesLeastAllocated.

**Which issue(s) this PR fixes**:

Fixes #88174

**Does this PR introduce a user-facing change?**:

```release-note
Weight of PodTopologySpread scheduling Score is doubled.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Fixed test

**Comment by alculquicondor** [comment]
cc @pavithrar

**Comment by alculquicondor** [comment]
cc @prameshj

**Comment by Huang-Wei** [comment]
LGTM. Glad to see this happen.

/retest

**Comment by spiffxp** [comment]
This may have caused https://github.com/kubernetes/kubernetes/issues/91316

**Pull request merged**
