### PR TITLE
Add cloud-controller-manager to the CI/release builds

### PR DESCRIPTION
**Pull request by luxas**
@thockin @wlan0 @roberthbailey

### CODE REVIEW

**Comment by thockin** [comment]
LGTM but needs to pass

**Comment by luxas** [comment]
@k8s-bot cvm gke e2e test this

**Comment by luxas** [comment]
@k8s-bot gci gke e2e test this

**Comment by luxas** [comment]
@thockin Flakes you know ;)

May I/could you apply the label?

**Comment by thockin** [comment]
How dare you imply that our glorious tests are flaky?!

label applied

**Comment by luxas** [comment]
Well, you know, I did never ever say that your tests are flaky. It's the media that are against me!! You must have heard me saying that from fake news :smile:

Ok, seriously ;) The glorious tests have been failing all week btw, do you know who's oncall?
I hoped that a PR of mine would merge over the weekend, but it seems like Godeps is broken.

@thockin Have a great next week!! :+1:

**Pull request merged**
