### PR TITLE
kubeadm: add datapolicy tags for v1beta3 token/key fields

### LINKED ISSUE #2339: add datapolicy tags to v1beta3 token/key fields
see the following KEPs:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1753-logs-sanitization
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1933-secret-logging-static-analysis

this PR showcases some tags that we should add to v1beta3 fields that include keys/tokens:
https://github.com/kubernetes/kubernetes/pull/95991

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
kubeadm: add datapolicy tags for v1beta3 token/key fields

#### Which issue(s) this PR fixes:

Fixes:  kubernetes/kubeadm#2339

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-security/1753-logs-sanitization
```

/sig instrumentation security
/priority important-soon
/milestone v1.22

### CODE REVIEW

**Comment by neolit123** [comment]
> Ref kubernetes/kubeadm#2339

this can be `fixes ...`

**Comment by neolit123** [comment]
/hold

i think we can still include this change in the changelog in v1beta3/doc.go even if its not user facing.
something like the following:

> - Include "datapolicy" tags on fields that hold secrets. These fields would then be omitted when structures are printed with klog.

**Comment by SataQiu** [comment]
> /hold
> 
> i think we can still include this change in the changelog in v1beta3/doc.go even if its not user facing.
> something like the following:
> 
> > * Include "datapolicy" tags on fields that hold secrets. This would result in the field values to be omitted when API structures are printed with klog.

Thanks @neolit123 
The changeLog has been added.

**Pull request merged**
