### PR TITLE
promote simple daemonset test out of flaky

### PR DESCRIPTION
**Pull request by mikedanese**
This unmatches 'Daemon set should run and stop simple daemon'

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
@mikedanese the simple daemonset test last failed 4 days ago, and 3 more times just before that:

job/kubernetes-e2e-gce-flaky/5768/

That's 4 days after the PR that we hoped would fix it merged.

Is there another PR in the past 4 days that we think has fixed this test?

**Comment by quinton-hoole** [comment]
Oh, the PR I referred to above is #14909

**Comment by mikedanese** [comment]
@quinton-hoole this test has not failed since #15335 was merged

**Comment by quinton-hoole** [comment]
@mikedanese awesome!  LGTM.

**Pull request merged**
