### PR TITLE
Longer PV Sync period

### PR DESCRIPTION
**Pull request by markturansky**
10s sync is too frequent.  Once per minute is sufficient. 

@smarterclayton mind LGTM'ing this?

@liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is fine but I'd be ok even with 10 minutes.

**Comment by markturansky** [comment]
bumped to 10.

**Comment by smarterclayton** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
