### PR TITLE
[WIP] Rebase pause image to distroless

### PR DESCRIPTION
**Pull request by yuwenma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This is part of the effort described in KEP kubernetes/enhancements#900
"pause" image is broadly used by e2e tests (test-infra/kubetest) and tooling under ./hack. Rebasing "pause" to distroless helps improving the test coverage and aligning the developing env with the release environment.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
> "pause" image is broadly used by e2e tests (test-infra/kubetest) and tooling under ./hack. Rebasing "pause" to distroless helps improving the test coverage and aligning the developing env with the release environment.

I might be wrong but I'm not really convinced that going from scratch to anything is an improvement in this case. Am I missing something?

**Comment by yuwenma** [comment]
> > "pause" image is broadly used by e2e tests (test-infra/kubetest) and tooling under ./hack. Rebasing "pause" to distroless helps improving the test coverage and aligning the developing env with the release environment.
> 
> I might be wrong but I'm not really convinced that going from scratch to anything is an improvement in this case. Am I missing something?

:man_facepalming: I changed this PR to WIP yesterday after I asked myself the same question... (but looks like it still catches people' eye)

To answer the question about this change: When I used kubetest to bring up a cluster, I realized the containers (kube-apiserver, kube-scheduler, etc) are not generated from the base image defined in /build/common.sh (where the released containers' base images come from) but some "pause" image. To make the dev environment same as the actual released environment, I think the dev env should use the same env as the release version.

Still working on this PR. Will provide more details after I do further research on the kubetest workflow. Please take a look later on.

**Comment by cblecker** [comment]
I'm interested in this too. I know the KEP talks about things like resolv.conf and ca-certificates, but don't know how much that impacts the pause image.

**Comment by BenTheElder** [comment]
The pause image runs a tiny static c binary that exists to:
- hold the namespace for pods
- reap zombie PIDS if PID namespace sharing is on

It doesn't do any networking itself or contain any other binaries, so I wouldn't expect this image to ever need to change unless we find a problem in the pause binary.

**Comment by BenTheElder** [comment]
> To answer the question about this change: When I used kubetest to bring up a cluster, I realized the containers (kube-apiserver, kube-scheduler, etc) are not generated from the base image defined in /build/common.sh (where the released containers' base images come from) but some "pause" image. To make the dev environment same as the actual released environment, I think the dev env should use the same env as the release version.

I'm not sure I understand this part, kube-apiserver should be built on `debian-base`, not `pause`?

https://github.com/kubernetes/kubernetes/blob/9e83e6d1cda83839d0a829d701efa56b090304c2/build/BUILD#L37-L38

https://github.com/kubernetes/kubernetes/blob/9e83e6d1cda83839d0a829d701efa56b090304c2/build/common.sh#L98

**Comment by yuwenma** [comment]
> > To answer the question about this change: When I used kubetest to bring up a cluster, I realized the containers (kube-apiserver, kube-scheduler, etc) are not generated from the base image defined in /build/common.sh (where the released containers' base images come from) but some "pause" image. To make the dev environment same as the actual released environment, I think the dev env should use the same env as the release version.
> 
> I'm not sure I understand this part, kube-apiserver should be built on `debian-base`, not `pause`?
> 
> [kubernetes/build/BUILD](https://github.com/kubernetes/kubernetes/blob/9e83e6d1cda83839d0a829d701efa56b090304c2/build/BUILD#L37-L38)
> 
> Lines 37 to 38 in [9e83e6d](/kubernetes/kubernetes/commit/9e83e6d1cda83839d0a829d701efa56b090304c2)
> 
>  "kube-apiserver": { 
>      "base": "@debian-base-{ARCH}//image", 
> [kubernetes/build/common.sh](https://github.com/kubernetes/kubernetes/blob/9e83e6d1cda83839d0a829d701efa56b090304c2/build/common.sh#L98)
> 
> Line 98 in [9e83e6d](/kubernetes/kubernetes/commit/9e83e6d1cda83839d0a829d701efa56b090304c2)
> 
>  kube-apiserver,"k8s.gcr.io/debian-base-${arch}:${debian_base_version}"

when building the released version ("make release"), the base image is using the one in build/common.sh
when using bazel to build the .tar, the build/BUILD is used.
(Correct me if I'm wrong) These are two different approaches building the kube images. Does "kubetest up" use either one of them? I tried to explain it [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md#for-core-master-images). Let me know if anything's unclear/incorrect. I was very confusing to me.

**Comment by BenTheElder** [comment]
[I explained in more detail and higher bandwidth offline back on the 12th]

going to close this for now
/close

**Pull request closed without merging**
