### PR TITLE
[TOB-K8S-025] Incorrect docker daemon process name in container manager

### LINKED ISSUE #81139: TOB-K8S-025: Incorrect docker daemon process name in container manager
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
The container manager used in kubelet checks for docker daemon process either via pidfile or process name. While the pidfile points to the docker daemon process PID, the dockerProcessName constant stores a docker cli name (docker) instead of docker daemon name (dockerd).

```
const (
      // (...)
	dockerProcessName     = "docker"
	dockerPidFile         = "/var/run/docker.pid"
      // (...)
)
```
Figure 30.1: Constants in pkg/kubelet/cm/container_manager_linux.go file.

**Recommendation**
Correct the docker process name to dockerd.

**Anything else we need to know?**:

See #81146 for current status of all issues created from these findings.

The vendor gave this issue an ID of TOB-K8S-025 and it was finding 31 of the report.

The vendor considers this issue Informational Severity.

To view the original finding, begin on page 77 of the [Kubernetes Security Review Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Environment**:

- Kubernetes version: 1.13.4

### PR DESCRIPTION
**Pull request by dims**
The container manager used in kubelet checks for docker daemon process either via pidfile
or process name. While the pidfile points to the docker daemon process PID, the
dockerProcessName constant stores a docker cli name ( docker ) instead of docker daemon
name ( dockerd ).

Found by Trail of Bits folks and documented [here](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81139

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for fixing @dims :) 

For my understanding, what are the actual ramifications of this being wrong? (i.e. I get that this is undesirable - I'm just not sure I see how its a security issue :) )

**Comment by dims** [comment]
@mattjmcnaughton kubelet finds any process(es) with that name and does things like move it into cgroups / adjust oom score etc, so this combined with other things may end up being problematic. (so basically we should fix it anyway)

**Comment by mattjmcnaughton** [comment]
On Thu, Aug 08, 2019 at 12:24:56PM -0700, Davanum Srinivas wrote:
> @mattjmcnaughton kubelet finds any process(es) with that name and does things like move it into cgroups / adjust oom score etc, so this combined with other things may end up being problematic. (so basically we should fix it anyway)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81083#issuecomment-519654452

Thanks for the additional info! Yeah, definitely something that should be fixed
regardless :)

**Comment by disconnect3d** [comment]
> For my understanding, what are the actual ramifications of this being wrong? (i.e. I get that this is undesirable - I'm just not sure I see how its a security issue :) )

If the pidfile (`/var/run/docker.pid`) would not exist for some reason the kubelet would look for `docker` processes "on the host" (whatever that means, heh) and taking into account an other problematic part here - a race condition when the pid is moved to cgroup - it is possible to get a container escape.

Though this requires an unprivileged process on the host, a process in container spawned by root and a luck with winning the race condition and triggering a PID-reuse attack.

Some more details can be find in https://github.com/kubernetes/kubernetes/issues/81124 and the other issue (the toctou one).

**Pull request merged**
