### PR TITLE
Fix SSA for APIService

### LINKED ISSUE #89264: Server-side apply doesn't work for APIService
It looks like the openapi is not routed properly to set-up the apiservice so apply requests will fail because the fieldmanager is not set-up properly.

/cc @jennybuckley @liggitt 
/sig api-machinery
/priority important-soon
/kind bug

### PR DESCRIPTION
**Pull request by kevindelgado**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
It removes the code to nil out the OpenAPIConfig on the aggregator server so that SSA requests are routed properly for the apiservices resource.

**Which issue(s) this PR fixes**:

Fixes #89264

```release-note
Fixes using server-side apply with APIService resources
```

### CODE REVIEW

**Comment by kevindelgado** [comment]
/assign @apelisse 
/assign @liggitt 

Please take another look, I had to update the generated proto and needed to create a new PR to change the branch.

**Comment by Liujingfang1** [comment]
@kevindelgado  Thanks for fixing this issue. I came across it when switching our controller to server-side apply. Is there any plan to backport this fix to k8s versions like 1.18, or 1.17? Our controllers need to work on clusters with those versions.

**Comment by kevindelgado** [comment]
@Liujingfang1 I've made an issue to track it and will try to look into backporting it shortly. https://github.com/kubernetes/kubernetes/issues/99046

**Pull request merged**
