### PR TITLE
Update the get command to follow more conventions of commands

### PR DESCRIPTION
**Pull request by smarterclayton**
Pure code movement, builds on top of #54446 and only the last commit is new. Will make refactoring get easier.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@fabianofranz

**Comment by fabianofranz** [comment]
@juanvallejo PTAL

**Comment by fabianofranz** [comment]
@smarterclayton LGTM

**Review by juanvallejo — APPROVED** [review]

**Pull request merged**
