### PR TITLE
Drop Azure/go-autorest from pkg/controller

### PR DESCRIPTION
**Pull request by dims**
We already have helper methods in k8s.io/utils, we should just use that

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/milestone v1.16

cc @liggitt @neolit123

**Comment by neolit123** [comment]
/lgtm
looks trivial :+1:

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
