### PR TITLE
Fix golint failure in pkg/quota/v1/evaluator/core

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:

- pkg/quota/v1/evaluator/core

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None
```

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
> /lgtm

hi @cheftako
Can you approve this pr?

**Comment by ZP-AlwaysWin** [comment]
> /cc @fejta

Thansk your reviews

**Comment by ZP-AlwaysWin** [comment]
Hi @fejta

please help me to review the pr
Best Wishes

**Review by SataQiu — APPROVED** [review]

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
