### PR TITLE
Fix the scripts to handle master/minion salt setups (e.g. AWS)

### PR DESCRIPTION
**Pull request by brendandburns**
@mikedanese @zmerlynn 

Ref: #18037

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by mikedanese** [comment]
LGTM, but i'd like to move aws to masterless soon.

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Pull request merged**
