### PR TITLE
support cherry pick commits instead of a whole PR

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Currently the script only supports cherry-picking PRs. Sometimes we may only need a single commit in a PR.

This PR does enhance this script to support cherry-picking commits automatically.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
xref #55457 

**Special notes for your reviewer**:
/assign @ixdy @mkumatag @luxas 

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
Looking at the history here @david-mcmahon @jessfraz @zmerlynn might be good approvers for this
/assign @david-mcmahon @jessfraz @zmerlynn 

/unassign
I'm not super familiar with this code, but seems ok in general

**Comment by ixdy** [comment]
How would someone use this new functionality? What's the advantage of using the script over just calling `git cherry-pick`?

**Comment by dixudx** [comment]
> How would someone use this new functionality?

Just add `IS_COMMIT=true` to indicate a single commit when running `./hack/cherry_pick_pull.sh`. Other params are exactly the same with the old behavior.

> What's the advantage of using the script over just calling git cherry-pick?

Just make it automatic, like what we are doing to cherry-pick a PR.

**Pull request closed without merging**
