### PR TITLE
Automated cherry pick of #32814

### PR DESCRIPTION
**Pull request by fabioy**
Cherry pick of #32814 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33190)

### CODE REVIEW

**Comment by foxish** [comment]
@fabioy the PR needs rebase, before we can merge the cherrypick.

**Comment by janetkuo** [comment]
@foxish looks like it's merged before rebase, is that okay?

**Comment by fabioy** [comment]
@foxish, @janetkuo Please let me know if you want this rolled back. Thanks.

**Comment by foxish** [comment]
@janetkuo @fabioy It appears to have merged correctly and seems okay. Not sure what happened here, but there doesn't seem to be a need to rollback that I can see.

**Comment by fabioy** [comment]
@foxish Cool, thanks.

**Pull request merged**
