### PR TITLE
Fixed comment to refer to the right int accessor for Quantity

### PR DESCRIPTION
**Pull request by booxter**
It's AsInt64() not Int64().

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by soggiest** [comment]
Hello! Code Freeze is just about on us. We'll be entering into Freeze tomorrow, May 31st. Is this still planned to land in 1.15?

**Comment by josiahbjorgaard** [comment]
Hello! I'm a bug triage shadow for the 1.16 release cycle and considering this PR has not been updated for a couple of months, I'd like to check it's status. The code freeze is starting 29th August (about 2 weeks from now) and while there is plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.16, is it still planned for this release?

**Comment by booxter** [comment]
@lavalamp I've rebased and pushed to the forked branch but I don't see this PR reflect it. Is it a github bug? Ideas?

**Pull request merged**
