### PR TITLE
Check IP of Ingress blank before append

### LINKED ISSUE #101679: Server logs flooded with Skipping invalid IP
Originally post on project https://github.com/k3s-io/k3s/issues/3255

**Environmental Info:**
K3s Version: v1.21.0+k3s1

Node(s) CPU architecture, OS, and Version: Linux 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 

Cluster Configuration: 1 server & 3 agents

**Describe the bug:**
I use an external cloud controller manager to manage load balancing and services exposition. But on my services spec, I have no ```status.loadBalancer.ingress.IP``` field but  a ```status.loadBalancer.ingress.hostname``` instead. Everything works fine but server logs are flooded with entries like ```utils.go:288] Skipping invalid IP:```

**Steps To Reproduce:**

- Installed K3s: 
- Use an external CCM which only  provide a hostname to expose service 

**Expected behavior:**
No more logs like ```utils.go:288] Skipping invalid IP:```

**Actual behavior:**
Server logs are flooded with entries like ```utils.go:288] Skipping invalid IP:```

**Additional context / logs:**

Should it be a good idea to test consistency of IP here : https://github.com/kubernetes/kubernetes/blob/f235adc4d271c30c4e3b32f48196ae812a6c7100/pkg/proxy/service.go#L204 or here ? https://github.com/kubernetes/kubernetes/blob/f235adc4d271c30c4e3b32f48196ae812a6c7100/pkg/proxy/util/utils.go#L279

### PR DESCRIPTION
**Pull request by fenngwd**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes flooding logs

#### Which issue(s) this PR fixes:

Fixes #101679

#### Special notes for your reviewer:
Since this pr just fix flooding log, there is no additional documentation.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/ok-to-test

**Comment by fenngwd** [comment]
@hwdef @andrewsykim @freehan please have a look at this pr.

**Review by hwdef — COMMENTED** [review]
/sig network

**Comment by hwdef** [comment]
I don't know why adding tags fails.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
Suggest we cherry-pick back to prev releases.

**Pull request merged**
