### PR TITLE
Graduate EfficientWatchResumption feature to GA

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/enhancements/issues/1904

```release-note
NONE
```

/sig api-machinery
/kind feature
/priority important-soon

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold cancel
KEP updated was merged: https://github.com/kubernetes/enhancements/pull/3062

/assign @deads2k 
@deads2k - would you mind reviewing this PR - it's super small

**Comment by dims** [comment]
/approve
/lgtm

NOTE: this change looks good to me! congrats on getting this to graduation!

/hold
( if you still need @deads2k to look. if not please remove hold )

**Comment by wojtek-t** [comment]
> ( if you still need @deads2k to look. if not please remove hold )

Given how simple this change is and given David is the one who approve KEP (so he is conceptually ok with it), I will just go ahead and remove hold.

/hold cancel

**Pull request merged**
