### PR TITLE
Updated ubuntu-calico.md for v1.1

### PR DESCRIPTION
**Pull request by caseydavenport**
Docs update in preparation for v1.1
- Updated to use Kubernetes v1.1
- Updated to use latest Calico
- Updated to use containerized master services

### CODE REVIEW

**Comment by thockin** [comment]
Is this still WIP?  time running.

**Comment by caseydavenport** [comment]
@thockin - Planning on one more test, then it should be good to go by noon today.  I'll report back.

**Comment by caseydavenport** [comment]
@thockin - No longer a WIP.

**Comment by caseydavenport** [comment]
Ran hack/update-generated-docs.sh - tests should hopefully pass this time.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
