### PR TITLE
Replacing 'HTTP' by 'HTTPS' for securing kubernetes links

### PR DESCRIPTION
**Pull request by longkb**
Currently, when we access **kubernetes.io/community** with **HTTP**, it is
redirected to **HTTPS** automatically. So this commit aims to
replace **http://kubernetes.io/community/** by **https://kubernetes.io/community/**
for security.

Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
For secure accessibility in **kubernetes.io/community**
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/release-note-none
/priority backlog
/sig storage

**Comment by longkb** [comment]
@neolit123 : thanks for your reviewing :)

**Comment by longkb** [comment]
@neolit123 : It seems that all of the test already passed. Could you please put Approved label to my PR :)
Thank you very much!

**Comment by neolit123** [comment]
hi, thanks for the update!
it's up to the maintainers to approve.

**Comment by longkb** [comment]
> 
> 
> hi, thanks for the update!
> it's up to the maintainers to approve.

Thanks @neolit123 
@wojtek-t : Could you help me to review my PR :)
Thanks

**Pull request closed without merging**
