### PR TITLE
Removes unnecessary SELinuxOptions from test case

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

The test "should run with the expected status" passes with and without
the set SELinuxOptions, but removing it will ensure that the test will
be able to run and pass on Windows nodes as well.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/lgtm
/approved
FYI @kubernetes/cncf-conformance-wg

**Comment by nikhita** [comment]
/assign @liggitt 
for approval

**Comment by liggitt** [comment]
cc @kubernetes/cncf-conformance-wg

**Comment by liggitt** [comment]
@aveshagarwal can you comment on the original reason this was added, whether it is a fundamental requirement, whether it is still necessary, and in what environments?

**Comment by aveshagarwal** [comment]
> @aveshagarwal can you comment on the original reason this was added, whether it is a fundamental requirement, whether it is still necessary, and in what environments?

Though its been a long time since i looked into them, but for sure, these (node e2es) were failing in a selinux-enabled environment like on rhel. Have we made sure if the tests continue working in an selinux-enabled environment?

**Comment by liggitt** [comment]
> Have we made sure if the tests continue working in an selinux-enabled environment?

are there CI tests for that type of node?

cc @derekwaynecarr

**Comment by aveshagarwal** [comment]
> are there CI tests for that type of node?

yes we had a job for testing that long back. Though not sure what is the current status.

**Comment by liggitt** [comment]
> yes we had a job for testing that long back. Though not sure what is the current status.

can you check if it is still active, and whether it is pre-submit or post-submit? if post-submit, let's make sure this PR passes against it prior to merge via a manual run, if possible

**Comment by aveshagarwal** [comment]
> can you check if it is still active, and whether it is pre-submit or post-submit? if post-submit, let's make sure this PR passes against it prior to merge via a manual run, if possible

Yes trying to find more information about it internally. @ingvagabund set that up so waiting for his response as he might be having better information i think.

**Comment by ingvagabund** [comment]
@liggitt it's a periodic job running every 2 hours on the HEAD of master branch, non-blocking

**Comment by dims** [comment]
@ingvagabund so we merge this then see if that fails? :)

**Comment by ingvagabund** [comment]
> @ingvagabund so we merge this then see if that fails? :)

yes, sir :)

**Comment by dims** [comment]
Let's ship it! ™️ 

/lgtm

**Comment by spiffxp** [comment]
/approve
@ingvagabund which job should we be watching?

**Pull request merged**
