### PR TITLE
Correct the name of parameter

### PR DESCRIPTION
**Pull request by ghost**
The right parameter is `--schedule-config`

### CODE REVIEW

**Comment by wojtek-t** [comment]
@klaus1982 - thanks for the change!

However, to merge it, we need to you sign the CLA - please take a look into instructions above.

@k8s-bot ok to test

**Comment by klaus1982** [comment]
@wojtek-t Signed the CLA just now :).

**Comment by wojtek-t** [comment]
@klaus1982 - great thanks!

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by sttts** [comment]
lgtm, thanks @klaus1982

**Pull request merged**
