### PR TITLE
cache: Avoid reallocs in Index

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by alex-mohr** [comment]
No CLA label.  Does @googlebot help?

**Comment by smarterclayton** [comment]
Michail you need to change your email on GitHub to include your redhat address

**Comment by kargakis** [comment]
I've changed both my e-mails (Github, Git) but it doesn't seem to work...

**Pull request merged**
