### PR TITLE
add kubelet config validation test for RegisterWithTaints

### PR DESCRIPTION
**Pull request by nayihz**
#### What type of PR is this?
/kind cleanup
/area kubelet
/area test

#### What this PR does / why we need it:
add kubelet config validation test for RegisterWithTaints
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
ref: https://github.com/kubernetes/kubernetes/pull/105437#discussion_r750780496
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
waiting on @ehashman, please add api approvers for approval after lgtm.

**Comment by matthyx** [comment]
/lgtm
@dims why do we need api approval for a test?

**Comment by dims** [comment]
@matthyx please see the OWNERS file below:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/OWNERS#L4-L5

This was to force the API approvers to look at the changes in this directory

https://github.com/kubernetes/kubernetes/pull/94196

**Review by mrunalp — APPROVED** [review]

**Comment by matthyx** [comment]
> /assign @thockin

we can try with Jordan too:
/assign @liggitt

**Pull request merged**
