### PR TITLE
fix where typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix where typo

### CODE REVIEW

**Comment by timchenxiaoyu** [comment]
@k8s-bot node e2e test this
@k8s-bot non-cri node e2e test this

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this
@k8s-bot non-cri node e2e test this

**Comment by justinsb** [comment]
@k8s-bot kops aws e2e test this

(We were hitting AWS rate limits the other day)

**Pull request merged**
