### PR TITLE
update cluster/ approvers

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
- Adds bentheelder to cluster/ approvers, I've been a reviewer for a year now and very active
- Moves inactive (as far as I can tell!) @zmerlynn @eparis to emeritus_approvers

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/sig cluster-lifecycle
/sig testing
/priority backlog
cc @fejta @cheftako @zmerlynn @eparis 
/cc @spiffxp @dims

**Review by fejta — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88747/pull-kubernetes-e2e-gce/1234581783354281984/
[k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s. expand_more	2m25s
[k8s.io] [sig-node] Mount propagation should propagate mounts to the host expand_more
/retest

**Pull request merged**
