### PR TITLE
Enhance error message from kubectl when 'kind' is empty

### PR DESCRIPTION
**Pull request by feihujiang**
#8401

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by bgrant0607** [comment]
Why does DataVersionAndKind not return the error?  @smarterclayton

**Comment by bgrant0607** [comment]
@vmarmol Beware that adding new error cases to kubectl sometimes causes e2e failures.

**Comment by smarterclayton** [comment]
Kind should never be empty if err is nil.

**Comment by bgrant0607** [comment]
Could MultiObjectTyper be invoked there?

**Comment by smarterclayton** [comment]
Maybe, although generally that's only in OpenShift.  I suspect something else is broken if you're seeing empty string, and we should fix that instead (since it's a programmer error for err to be nil and kind to be empty).

**Comment by bgrant0607** [comment]
Agree.

**Comment by vmarmol** [comment]
Reassigning to @bgrant0607, you know better than me the correct thing to do here :)

**Comment by feihujiang** [comment]
@smarterclayton  @bgrant0607    I created a pod using kubectl, the template without 'kind' field in it, I printed err and kind after version, kind, err := m.DataVersionAndKind(data) and found they are both nil. I think DataVersionAndKind don't return the error.  

then I dig into the DataVersionAndKind method, json.Unmarshal don't return error if kind is not set in data. so I think  We should disallow 'kind' to be empty and make the error message more clear.
        findKind := struct {
		APIVersion string `json:"apiVersion,omitempty"`
		Kind       string `json:"kind,omitempty"`
	}{}
	err = json.Unmarshal(data, &findKind)

**Comment by feihujiang** [comment]
@bgrant0607  I updated the code, Could you please review it again?

**Comment by smarterclayton** [comment]
I see why there is the confusion.  DecodeInto relies on being able to check DataVersionAndKind empty for an error and infers the target kind and version from the provided object when it is empty.  Given that, we probably do not want to change DataVersionAndKind's behavior at the lower level conversion object.  I'm a bit concerned about having runtime.Scheme and conversion.Scheme having different behavior, because of the potential for mistaken use of DataVersionAndKind.

I'm starting to think that we need to assess each location where DataVersionAndKind is used and determine whether it should check for empty string (like you originally had it).  Sorry to send you down this rathole - we need to correct the Godoc on both runtime.Scheme and conversion.Scheme as well.

**Comment by feihujiang** [comment]
@smarterclayton  I assess each location where DataVersionAndKind is used, one is the place I commit. and the other one I am not sure is MultiObjectTyper, so I didn't commit it, what's your point?  and  Godoc on both runtime.Scheme and conversion.Scheme is "DataVersionAndKind will return the APIVersion and Kind of the given wire-format encoding of an API Object, or an error." ,  I think this is right. what should we correct?

**Comment by smarterclayton** [comment]
MultiObjectTyper is correct as you have it (if two typers have different schemes, and can be totally certain the fields aren't there, they should return error rather than empty).  I'll take a todo to come back to this code post 1.0.

Thanks, LGTM

**Comment by smarterclayton** [comment]
I just remember we are in a merge closed window and had to revert this.  Sorry to do that to you - can you reopen the pull and then I'll merge once we open master back up?

**Comment by smarterclayton** [comment]
No need to reopen, my revert of a revert is linked and will get merged when it goes green.

**Pull request merged**
