### PR TITLE
Versioned busybox docker image

### LINKED ISSUE #53942: Recycle always failed on non x86 platform
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

 /kind bug

> /kind feature

**What happened**:

```
[root@ ibm1046 hp]# cat pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1
  persistentVolumeReclaimPolicy: Recycle
```
```
[root@ ibm1046 hp]# cat pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-clai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Use the above two files create one PV and PVC, then delete the PVC, the PV will become failed but not released.

```
root@ibm1046:~/gyliu/hp# kubectl -s 127.0.0.1:8888 get pv | grep local-pv-1
local-pv-1                               20Gi       RWO           Recycle         Failed    default/example-local-clai
```

```
root@ibm1046:~/gyliu/hp# kubectl -s  127.0.0.1:8888 describe pv local-pv-1
Name:		local-pv-1
Labels:		type=local
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"local-pv-1","namespace":""},"spec":{"access...
		pv.kubernetes.io/bound-by-controller=yes
StorageClass:
Status:		Failed
Claim:		default/example-local-clai
Reclaim Policy:	Recycle
Access Modes:	RWO
Capacity:	20Gi
Message:	Recycle failed: pod failed, pod.Status.Message unknown.
Source:
    Type:	HostPath (bare host directory volume)
    Path:	/tmp/data/pv-1
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  1m		1m		1	persistentvolume-controller			Warning		VolumeFailedRecycle	Recycle failed: pod failed, pod.Status.Message unknown.
  1m		15s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: Successfully assigned recycler-for-local-pv-1 to 9.42.76.16
  1m		14s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: MountVolume.SetUp succeeded for volume "default-token-x8llz"
  1m		14s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: MountVolume.SetUp succeeded for volume "vol"
  1m		13s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: pulling image "gcr.io/google_containers/busybox"
  1m		13s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: Successfully pulled image "gcr.io/google_containers/busybox"
  1m		13s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: Created container
  1m		12s		45	persistentvolume-controller			Normal		RecyclerPod		Recycler pod: Started container
```

The busybox recycler never succeed for power.

/sig storage

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53942

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
> Production images MUST NOT use unversioned images, since it is impossible to do a staged rollout.

@tallclair @yujuhong I don't think pod `pv-recycler` needs to support rollout, since the main purpose of such a pod is to simply run `"rm -rf"` on a volume and test for emptiness.

For versioned images, I am open. Just a little concern, we need to keep it updated with `busybox` in DockerHub, when a new version is bumped. Is it really necessary?

Waiting for @jsafrane @luxas to chime in.

**Comment by tallclair** [comment]
> For versioned images, I am open. Just a little concern, we need to keep it updated with `busybox` in DockerHub, when a new version is bumped. Is it really necessary?

It may feel like overkill in this case, but it's not good practice as it moves control away from whoever is managing cluster. Eventually we hope to remove this code, so it won't be a burden for long.

/lgtm

**Comment by luxas** [comment]
@tallclair Personally, I would not have merged this so quickly I think. If we're gonna be that strict with versions -- have we checked that this image actually is ok to use? Will we do a new k8s release if it turns out this image has a vuln, etc.?

To be clear -- if we have an official policy, let's follow it. Or are things decided on a case-to-case-level?

**Pull request merged**
