### PR TITLE
Automated cherry pick of #124572: tag TrafficDistribution tests to avoid running on

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #124572 on release-1.30.

#124572: tag TrafficDistribution tests to avoid running on

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @soltysh @liggitt @thockin 

Discussed with Maciej offline, this is impacting Openshift CI (that we know of, as others CIs running tests on multiple zones will have the same problem) and also in Maciej words

> if someone does kubectl explain on that field to get that info about that field being alpha

**Comment by liggitt** [comment]
/lgtm
/approve

for API doc addition of the alpha field gate

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
