### PR TITLE
golang: Update to go1.18rc1

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Part of https://github.com/kubernetes/release/issues/2307.

- golang: Update to go1.18rc1
- [go1.18] Bump golang.org/x/... dependencies
- generated: Run hack/lint-dependencies.sh and hack/update-vendor.sh

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes in now built with go1.18rc1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
For Golang pre-releases, the `go-canary` variant for kubekins/krte needs to be built ahead of the `master` variant to enable testing go canary presubmits.
PR for that is here: https://github.com/kubernetes/test-infra/pull/24704

**Comment by dims** [comment]
@justaugustus - policy question : will we ship a 1.23 (or any other release for that matter) with a beta version of the golang compiler?

**Comment by justaugustus** [comment]
> @justaugustus - policy question : will we ship a 1.23 (or any other release for that matter) with a beta version of the golang compiler?

We don't have a [policy](https://github.com/kubernetes/sig-release/blob/master/release-engineering/handbooks/go.md), but I'd say we should only consider release candidates. I'm personally fine w/ using a beta version, but wholesale requiring it for k/k contributors might not be a reasonable expectation.

For example, in the instance of go1.18beta1, there's a [staticcheck issue](https://github.com/dominikh/go-tools/issues/1107) which would block linting.

**Comment by justaugustus** [comment]
(I'm usually opening this PRs well ahead of the Golang official release to get some initial feedback/provide an anchor to link back to in various places. I _think_ this is the first time we've gotten the PR open at beta; usually it's opened for RC.)

**Comment by justaugustus** [comment]
Canary presubmits have been bumped to go1.18rc1 (ref: https://github.com/kubernetes/test-infra/pull/25349)

/test pull-kubernetes-dependencies-go-canary
/test pull-kubernetes-integration-go-canary
/test pull-kubernetes-unit-go-canary
/test pull-kubernetes-verify-go-canary

**Comment by justaugustus** [comment]
Ready for review:
/assign @liggitt @dims @cpanato @puerco 
cc: @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
nice
/lgtm

**Comment by justaugustus** [comment]
???
/override pull-kubernetes-verify-go-canary

**Comment by justaugustus** [comment]
> > ??? /override pull-kubernetes-verify-go-canary
> 
> the error are lint failures and thing related to dependencies between modules ... related to golang toolchain for sure

> Will take anything remaining as follow-ups!

Agreed. The confusion was about the test override not sticking. The default presubmits are not on go1.18 yet, so this won't block other PRs, but the fact that the context is not required, yet blocking the PR from the merge pool is odd.

(Possibly because the jobs were in progress before I overrode them.)

**Review by saschagrunert — APPROVED** [review]

**Comment by wojtek-t** [comment]
It seems that this PR has visibly increase memory usage of at least kube-apiserver (10% on 10th-percentile, even more on higher percentiles):
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-apiserver-gce-scale-cluster-master%2Fkube-apiserver&Resource=memory

We should understand to what extent this is expected and can we somehow mitigate this.

**Comment by wojtek-t** [comment]
@liggitt @kubernetes/sig-scalability @marseel @mborsz ^^

**Comment by wojtek-t** [comment]
OTOH - it's interesting to see how much it helps pod startup time:
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadPodStartup&Metric=pod_startup

**Comment by liggitt** [comment]
@wojtek-t can we file an issue to golang so they're aware as we investigate? do we have any pprof info to help narrow down *where* the memory increase is?

**Comment by wojtek-t** [comment]
We're following up with golang team about that. @tosi3k is looking into them and started the conversation with golang folks.

**Comment by justaugustus** [comment]
> @liggitt @wojtek-t do we want to open a blocker issue in k/k for tracking the problem above?

Opened here: https://github.com/kubernetes/kubernetes/issues/108357
Folks, please keep @kubernetes/release-engineering looped in on the various upstream issues that may crop up :)

**Pull request merged**
