### PR TITLE
base-images: Update to kube-cross:v1.13.9-5

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Unblocks releases. Tracking issue: https://github.com/kubernetes/release/issues/1281**

~Enables gcloud SDK for stage/release jobs.~

~In https://github.com/kubernetes/release/pull/1258, we moved to using kube-cross for staging/releasing Kubernetes. We need to pull in the latest kube-cross image (`v1.13.9-4`) which includes the necessary packages (`gcloud`, `gsutil`).~

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

ref: https://github.com/kubernetes/release/pull/1279
/assign @cblecker @dims @BenTheElder 
cc: @kubernetes/release-engineering 
/sig release
/area release-eng dependency
/priority critical-urgent

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
base-images: Update to kube-cross:v1.13.9-5
```

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

Why are we expanding what goes into this image? If it’s not needed to build kubernetes, it probably should be a separate image. You have the “FROM” be kube-cross (like kube-build does) without ballooning a bunch of extra utilities (like gcloud).

Let’s talk about this tomorrow.

**Comment by justaugustus** [comment]
@cblecker -- See PR description in https://github.com/kubernetes/release/pull/1258 for details.
/retest

**Comment by justaugustus** [comment]
`pull-kubernetes-verify` [ran successfully](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90963/pull-kubernetes-verify/1260099438517424128) against the staging image.

I've dropped that staging test commit now that the new kube-cross images have [been promoted](https://github.com/kubernetes/k8s.io/pull/860).

**Comment by justaugustus** [comment]
/hold cancel
(since the fixup in https://github.com/kubernetes/release/pull/1279 addresses @cblecker's concerns)

**Pull request merged**
