### PR TITLE
Remove resource specifications from CRI until further notice

### PR DESCRIPTION
**Pull request by tmrts**
See #29871 for the discussion issue.

cc @dchen1107 @vishh @yujuhong @euank @yifan-gu @feiskyer

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30517)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM and thanks!

**Comment by yujuhong** [comment]
Thanks! I was thinking about removing this file completely, now that we have proto files, and the [internal services interface](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/api/services.go).

**Comment by tmrts** [comment]
@yujuhong I'll remove it then :+1:

**Comment by yujuhong** [comment]
@tmrts sounds good. Thanks!

I also posted another PR to remove podsandbox resource from the proto: #30521

**Comment by vishh** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/kubelet/container/interface.go, line 330 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30517#-KP-2lw20HTdxeGYSRNP:-KP-2lw20HTdxeGYSRNQ:b-73evjh) ([raw file](https://github.com/kubernetes/kubernetes/blob/16c71aad4a2266ebc32998ba94172e3ed6a960fe/pkg/kubelet/container/interface.go#L330)):*
> ```Go
> type LinuxContainerConfig struct {
> 	// Resources specification for the container.
> 	Resources *LinuxContainerResources
> ```

Why are we removing container resources as well?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30517)*

**Comment by dchen1107** [comment]
@vishh Good catch!

**Comment by yujuhong** [comment]
*[pkg/kubelet/container/interface.go, line 330 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30517#-KP-2lw20HTdxeGYSRNP:-KP-4MR_Sjde7F-yhd8X:b-z1p3fe) ([raw file](https://github.com/kubernetes/kubernetes/blob/16c71aad4a2266ebc32998ba94172e3ed6a960fe/pkg/kubelet/container/interface.go#L330)):*
<details><summary><i>Previously, vishh (Vish Kannan) wrote…</i></summary>
> Why are we removing container resources as well?
</details>
No, we shouldn't remove the container resources.

I didn't read the PR closely, since I think we should remove the file completely now that has served its purpose and we have api/services.go and api/v1alpha1/runtime/* files. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30517)*

**Comment by tmrts** [comment]
@vishh thanks, we'll remove the file, but its good to know :+1:

**Comment by yujuhong** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30517#-:-KP-9Mg6eUK_uUnP9UtQ:bnfp4nl)*

**Comment by yujuhong** [comment]
@tmrts I think your other PR (fixing a typo in the file) went in first.

**Comment by tmrts** [comment]
@yujuhong thanks rebased now

**Comment by tmrts** [comment]
e2e flake?

**Comment by yujuhong** [comment]
Summary:

This PR deletes the `container/interface.go` file.`container/interface.go` has served its purpose to gather reviews and served as the base of the first version of the CRI. Now that we have [`api/v1alpha1/runtime/api.proto`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto) (with the [generated go file](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go)) and the internal interfaces in [`api/services.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/services.go), we should deprecate and remove `container/interface.go` to avoid confusion.

Note that  [`api/services.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/services.go) doesn't have internal types yet, which we can add once we have more than one (v1alpha1) version. 

/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
node e2e flakes on gci, again.
`etcd binary not found`
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/29932.

**Pull request merged**
