### PR TITLE
Create a docker image for the cloud controller manager

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

If you want to test the cloud-controller-manager our currently, you have to grab the binary from the CI or the release builds, put it in a Dockerfile, build the image and possibly upload the image to a registry, only to be able to test the new cloud stuff out. This is overly complex and should just work like any other component like the core controller manager that has its own docker image pushed automatically for it.

This PR makes the release scripts create an image for the cloud controller manager.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Create and push a docker image for the cloud-controller-manager
```

cc @thockin @wlan0 @roberthbailey @mikedanese

### CODE REVIEW

**Comment by thockin** [comment]
@wlan0, you ok with this at this stage?

**Comment by wlan0** [comment]
@thockin absolutely, yes

**Comment by ixdy** [comment]
@luxas can you update the bazel rules too, please? thanks!

**Pull request merged**
