### PR TITLE
Add `kubectl get -f file.json --latest=false`

### PR DESCRIPTION
**Pull request by smarterclayton**
Allows someone to convert an object on disk to the newest format
without that resource being on the server.

For instance, read all of the JSON files in the directory "foo"
and convert them to version v1beta3

```
$ kubectl get -f foo/ --latest=false -o json > newfile.json
```

Makes it much easier to convert old resources to new resources.

Adds -f to kubectl get as well.

@brendandburns @bgrant0607

### CODE REVIEW

**Comment by eparis** [comment]
does this pass hack/verify-gendocs.sh ?

**Comment by bgrant0607** [comment]
I find get --latest=false to not be a very intuitive way to do this, and I'm not keen on permanently baking in the object conversions in ordinary kubectl operations (#3955).

I've previously proposed --dry-run for all operations, but that would still typically contact the server.

I wouldn't mind adding a conversion command that would subsume the standalone conversion tool:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cluster_management.md#switching-your-config-files-to-a-new-api-version

cc @lavalamp

**Comment by smarterclayton** [comment]
So at worst, you've created a file that doesn't validate to the server.  I think that's outweighed by the benefits of offline conversion.  Also, at some point you have to ask "which server" when you look to an authoritative conversion.  I don't know that I consider any particular server more authoritative than another in this use case, so the CLI is really just helping you get converted.

A conversion command just seems like a subset of get - for instance, get from a server and pipe to create on another server doesn't feel much different from get from a file and pipe to a create on another server.  

We have to have conversions in kubectl commands somehow in order to do --output-version, and we may very well support v1 conversions for a very long time, even after the server stops responding to v2.  Does a user have to dig up an older version of a client binary in order to do that conversion?

**Comment by smarterclayton** [comment]
Part of the reason why I made this part of get is that the code for a standalone "convert" is going to look exactly the same as get, and I thought get would be a natural place to go to convert things from the server to disk for import into another server.  I understand the desire to split out the behavior, but it does take "convert" out of the common verb space for use later.

**Comment by eparis** [comment]
/hack/verify-gendocs.sh failed  :-(

**Comment by smarterclayton** [comment]
Yeah, I'm waiting for approval of the pattern, which isn't clear.

----- Original Message -----

**Comment by eparis** [comment]
While not what the flag is currently used for, from an user PoV they won't know the difference, so I like

kubectl get -f foo/ --api-version=v1beta3

**Comment by derekwaynecarr** [comment]
I like the feature in kubectl because I had this exact need this week and my initial reaction was that kubectl should do it.

I prefer something closer to @eparis stated.

$ kubectl get -f foo/ --output-api-version=<version | latest>

**Comment by smarterclayton** [comment]
--latest isn't the API version.  It's telling "get" not to fetch the object from the server before converting it.

**Comment by lavalamp** [comment]
I would prefer a new verb; get already means something, it's weird to make it also mean "don't get". Perhaps 'translate'?

Does this do anything that kube-version-convert doesn't?

**Comment by smarterclayton** [comment]
I'm fine with a new verb if it will have a purpose beyond get - for instance, export / remove immutable / unsettable fields.  But I also don't want to design that unless we're ready for it.

**Comment by smarterclayton** [comment]
The other use case for this action is to format an object you previously captured using a template (json to yaml).  That's something a generic convert command would do as well, so maybe a separate command would be better.  If we are ready to commit to a verb.

**Comment by eparis** [comment]
I think it's pretty clear that -f means "get from the file, not the server".  What else could it mean?

From a users PoV --api-version already does exactly what is needed.  It gives me an object in the version I asked for.

So -f + --api-version seems like a perfect fit.

I'm ok with another verb, but it seems like overkill. I'd suggest we think about what makes sense/obvious to a user, not what keeps the code the most 'technically clean.'

Either way I'm against --latest=false :)

**Comment by smarterclayton** [comment]
> On May 1, 2015, at 9:41 AM, Eric Paris <notifications@github.com> wrote:
> 
> I think it's pretty clear that -f means "get from the file, not the server". What else could it mean?
> 
Because you probably want to get the latest copy of that object from the server, like the other get calls do.  So you can "refresh" against the server and see status and resource version.

**Comment by lavalamp** [comment]
I would have assumed that get -f means "use this file to identify the object to get from the server".

**Comment by eparis** [comment]
Well, I think you're both nuts, but since you both think that way, it must be me who is nuts  :)

In which case, color me convinced for a new verb.

**Comment by smarterclayton** [comment]
Do we like "convert"?  "Export" is a strict subset of convert, as is "transform"

**Comment by smarterclayton** [comment]
Going to rebuild this as a convert/export hybrid.

**Comment by bgrant0607** [comment]
+1 to a new verb.

I agree that we also need a way to generate clean config files from objects, item 17 of the CLI roadmap:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md

And some way to populate a template with commonly used fields, for the edit mode.

**Pull request closed without merging**
