### PR TITLE
Automated cherry pick of #68874: update vendor #66012: ipvs support graceful termination #69268: fix bugs introduced by ipvs graceful termination

### PR DESCRIPTION
**Pull request by Lion-Wei**
Cherry pick of #68874 #66012 #69268 on release-1.12.

#68874: update vendor
#66012: ipvs support graceful termination
#69268: fix bugs introduced by ipvs graceful termination

### CODE REVIEW

**Comment by feiskyer** [comment]
@Lion-Wei @m1093782566 @sttts  Please get the PR approved (with both `lgtm` and `approved` label) by end of Tuesday, Oct 23th. Or else, it will miss v1.12.2.

**Comment by m1093782566** [comment]
@feiskyer 

Thanks for your reminder.

/lgtm
/approve

@ping @sttts for cherry-pick approval.

**Comment by m1093782566** [comment]
@feiskyer 

Thanks for your reminder.

/lgtm
/approve

ping @sttts for cherry-pick approval.

**Comment by m1093782566** [comment]
@feiskyer 

Thanks for your reminder.

/lgtm
/approve

ping @sttts for cherry-pick approval.

**Comment by Lion-Wei** [comment]
/assign @lavalamp @sttts 
PTAL, thanks.

**Comment by Lion-Wei** [comment]
@dghubble Actually it's not like a new feature, cause if kube-proxy don't support graceful termination, then   if we delete a pod, will immediately lost the connection, that's kind of bug, I think.
> Isn't this a new feature being cherry-picked into a point release?

**Pull request merged**
