### PR TITLE
Remove the legacy Nginx testcases

### PR DESCRIPTION
**Pull request by chendave**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
/release-note-none
/sig testing
/sig network

this is alternative to https://github.com/kubernetes/kubernetes/pull/108326

@aojea  I haven't embed the ingress manifest in this pr. Some of the testcase like `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should be able to switch between IG and NEG modes` still need the file in that directory, but consider those testcases can only run with "gce", "gke", maybe we can just let it be.

**Comment by danwinship** [comment]
You should probably split off the `error`→`err` fix into a separate PR since neither of the two commits here depends on the other, and they require different approvers because they're in different parts of the tree.

I can approve the network parts if someone else confirms that we actually do want to do this... it sounds like we're undecided about this vs https://github.com/kubernetes/kubernetes/pull/108326 right now

**Comment by aojea** [comment]
> You should probably split off the `error`→`err` fix into a separate PR since neither of the two commits here depends on the other, and they require different approvers because they're in different parts of the tree.
> 
> I can approve the network parts if someone else confirms that we actually do want to do this... it sounds like we're undecided about this vs #108326 right now

discussion is here,
https://github.com/kubernetes/kubernetes/issues/108324#issuecomment-1059063409

nginx ingress has its own CI and nobody is maintaining these tests, when ingress deprecated beta I had to disable them because the project didn't supported the v1 API :shrug:

**Comment by aojea** [comment]
:eyes: 

/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aojea** [comment]
ahh, the ingress job passed

pull-kubernetes-e2e-gci-gce-ingress — Job succeeded.                     BaseSHA:f10cd679eb5f5805cb6bdf1fabc19d918affac80

/lgtm
/approve

Thanks

**Comment by jefferycline1** [comment]
Renovate scheduling automatic. 5 pm everyday.

**Pull request merged**
