### PR TITLE
Accept both 'No events.' and 'Events:'

### LINKED ISSUE #19304: e2e flake: Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
I can see two failures out of the past approx 100 runs.  Both failures look the same. Logs below:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22348/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_describe_should_check_if_kubectl_describe_prints_relevant_information_for_rc_and_pods__Conformance_/
```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:606
Jan  4 18:55:18.483: Failed to find Events: in Name:		redis-master
Namespace:	e2e-tests-kubectl-i7zpo
Image(s):	redis
Selector:	app=redis,role=master
Labels:		app=redis,role=master
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22471/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_describe_should_check_if_kubectl_describe_prints_relevant_information_for_rc_and_pods__Conformance_/

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:606
Jan  5 22:16:22.752: Failed to find Events: in Name:		redis-master
Namespace:	e2e-tests-kubectl-6cabg
Image(s):	redis
Selector:	app=redis,role=master
Labels:		app=redis,role=master
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #19304.

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM

**Comment by lavalamp** [comment]
Flake is #18980, rerunning.

**Comment by lavalamp** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
@k8s-oncall this is a flake fix, you might consider merging it manually.

**Pull request merged**
