### PR TITLE
Fix windows build by altering go-ansiterm version

### LINKED ISSUE #48887: windows/amd64 cross-build is broken: vendor/github.com/docker/docker/pkg/term/windows
The windows/amd64 cross-build has been failing since yesterday morning.
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/2320:
```
I0712 10:13:02.637] +++ [0712 10:11:46] windows/amd64: go build started
I0712 10:13:02.637] # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/term/windows
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:139: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:146: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.DWORD
I0712 10:13:02.638] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:226: undefined: winterm.DWORD
```

It looks like #47140 is the culprit. The Azure dependencies were updated, but docker wasn't updated to support the changes until 1.12, and we vendor 1.11.

/assign @brendandburns  
/cc @krousey @kubernetes/sig-windows-bugs

### PR DESCRIPTION
**Pull request by karataliu**
**What this PR does / why we need it**:
An attempt to fix windows build break in #48887, moves `github.com/Azure/go-ansiterm` to https://github.com/Azure/go-ansiterm/commit/70b2c90b260171e829f1ebd7c17f600c11858dbe.
We can upgrade to new version when we pick docker 1.12

See also:
https://github.com/moby/moby/pull/22321/commits/fab67ab677e14c908f879e362f8805c8e91570c6#diff-c36e523b64f1ca41293e912113063a92L9

**Which issue this PR fixes**
Fixes #48887 

**Special notes for your reviewer**:

**Release note**:

### CODE REVIEW

**Comment by dims** [comment]
@ixdy @cblecker this PR seems to fix https://github.com/kubernetes/kubernetes/issues/48887 PTAL

**Comment by cblecker** [comment]
Yeah, this looks fine to me.
/assign @brendandburns

**Comment by ixdy** [comment]
looks fine to me but I'd like @brendandburns to confirm

**Comment by brendandburns** [comment]
/lgtm

Thanks for the fix!

**Pull request merged**
