### PR TITLE
Handle container terminated but pod still running in conditions

### PR DESCRIPTION
**Pull request by fabianofranz**
Sometimes when you have a pod with more than one container, and the container runs and terminates really fast, `PodContainerRunning` can go into a state where the pod indicates it's still running, but the container is already terminated. Handle that condition by returning `ErrContainerTerminated` when it happens.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@smarterclayton please review and tag `release-note-none`. Related Origin PR is https://github.com/openshift/origin/issues/10175. Tks!

**Comment by smarterclayton** [comment]
@yujuhong reading through the scenario, I would expect (but not surprised if it doesn't work this way right now) that the kubelet would not send a status update to the master that includes "PodRunning" on a restart=Never pod but has container terminated.  If there were multiple containers, I might expect this, but I would not expect this in a single container pod.

**Comment by yujuhong** [comment]
> @yujuhong reading through the scenario, I would expect (but not surprised if it doesn't work this way right now) that the kubelet would not send a status update to the master that includes "PodRunning" on a restart=Never pod but has container terminated. If there were multiple containers, I might expect this, but I would not expect this in a single container pod.

That's what I'd expect too. If all the containers in the pod have terminated, kubelet should just report that the pod is terminated. 



> Sometimes when you have a pod with more than one container, and the container runs and terminates really fast, PodContainerRunning can go into a state where the pod indicates it's still running, but the container is already terminated. Handle that condition by returning ErrContainerTerminated when it happens.

@fabianofranz, if there is still any running container in the pod, the pod should be considered running.

**Comment by fabianofranz** [comment]
@smarterclayton this was [reported to us](https://bugzilla.redhat.com/show_bug.cgi?id=1360626) in a scenario of pod with more than one container.

**Comment by fabianofranz** [comment]
> if there is still any running container in the pod, the pod should be considered running

Right, but in this func we are targeting one specific container (`PodContainerRunning` func which [takes the container name](https://github.com/fabianofranz/kubernetes/blob/5d78b160b7d46cd98fbafc0bde5145d9967f45d9/pkg/client/unversioned/conditions.go#L205)). So I think it makes sense to have a returning case like "the container you specified was already terminated so the 'running' condition will never be fulfilled").

**Comment by yujuhong** [comment]
> Right, but in this func we are targeting one specific container (PodContainerRunning func which takes the container name). So I think it makes sense to have a returning case like "the container you specified was already terminated so the 'running' condition will never be fulfilled").

I've never read/used this function, but what you said sounds right.

**Comment by smarterclayton** [comment]
Ok, as long as this is only in multi container.  Lgtm

**Comment by fejta** [comment]
@k8s-bot e2e test this issue #29966

**Pull request merged**
