### PR TITLE
Kubelet: Factor out and remove pullImageAndRunContainer

### PR DESCRIPTION
**Pull request by vmarmol**
Depends on #7382 

/cc @dchen1107 @yifan-gu

### CODE REVIEW

**Comment by vmarmol** [comment]
Rebased since #7382 was merged.

**Comment by yifan-gu** [comment]
I imagine we will create a puller interface for kubelet.pullImage, so we can pass kubelet to container runtime? Just the generateRunContainerOptions?

**Comment by vmarmol** [comment]
@yifan-gu I'm not sure we need to. The Kubelet portion is doing all the logic with pulling images before it asks the runtime to pull images. The only case when the runtime pulls an image without going through the Kubelet is for the pod infra container which does not have the pull logic (e.g.: PullPolicy).

Let me know if I am not seeing something :)

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
