### PR TITLE
Remove vsphere support.

### PR DESCRIPTION
**Pull request by erictune**
Vsphere support is not actively supported and has a number of issues against it.

### CODE REVIEW

**Comment by erictune** [comment]
Reasons I am proposing this for deletion:

I do not see that there is person or persons who are active in supporting users of vsphere on irc/slack/email/issues.

Open issues against vsphere, some for several months.
#14368
#17950
#10417
#3630
#14366
#14363

Also, vsphere uses salt in a way inconsistent with our current practices (requires highstate on adding minion to cluster; actually runs salt master, I think).

If this is approved, I will then delete vsphere from the kubernetes.io page.

**Comment by erictune** [comment]
@Symmetric you seem to comment on issues about vsphere often.  How do you feel about the support being deleted?

**Comment by erictune** [comment]
Last change to cluster/vsphere to fix vsphere support was a year ago.  Since then 27 commit have had to touch the vsphere code in cluster/vsphere for reasons unrelated to fixing vsphere.  

Conclusion: it is not working for users, and it is causing friction for devs.

**Comment by zmerlynn** [comment]
LGTM / SGTM. I'm going to give this one 24hr for comments, then you can rebase and poke me for a label. (It might be a waste to do it before then.)

**Comment by Symmetric** [comment]
Every time I've tried to use the vsphere integration it's not worked, and
pushing through the bugs has led to uncovering more bugs. Don't think I've
ever successfully stood up a cluster using it.

It would be great if it was supported and worked, but if nobody is actually
maintaining it then it seems reasonable to nix it.

**Comment by thockin** [comment]
LGTM

**Comment by casualjim** [comment]
We’ve actually been working on getting vsphere to work and will be doing more work to integrate kubernetes and vsphere as cloud provider too.

**Comment by imkin** [comment]
Is this going in right now? I am just starting to fix some of these issues to make sure this integration works.

**Comment by thockin** [comment]
It's blocked on a rebase, so it won't go in until a human does some work.  I'm sure Eric will have more details, but I think we're asking for a real commitment to maintenance to keep a port in the core tree.

**Comment by casualjim** [comment]
I'm setting up a build server on vcloud air next week to ensure the stability of this going forward.

**Comment by erictune** [comment]
Okay.  I'll put this on hold for a month and close it if new contributions to vsphere appear.

**Comment by erictune** [comment]
@casualjim have you had any time to work on vsphere support for Kubernetes in the last month?

**Comment by casualjim** [comment]
Yes we have an outstanding pull request for this. Just chasing down the group to add the email to for the CLA compliance

https://github.com/kubernetes/kubernetes/pull/19489

**Comment by erictune** [comment]
Cool, thanks.

**Pull request closed without merging**
