### PR TITLE
Update prometheus library usage

### LINKED ISSUE #14159: godep restore failing on HEAD
The cause is prometheus/client_golang#173. It fails with the following error:
```
pszczesniak@piosz:~/go/src/k8s.io/kubernetes$ godep restore
package github.com/prometheus/client_golang/extraction: cannot find package "github.com/prometheus/client_golang/extraction" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/extraction (from $GOROOT)
        /usr/local/google/home/pszczesniak/go/src/github.com/prometheus/client_golang/extraction (from $GOPATH)
godep: restore: exit status 1
package github.com/prometheus/client_golang/model: cannot find package "github.com/prometheus/client_golang/model" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/model (from $GOROOT)
        /usr/local/google/home/pszczesniak/go/src/github.com/prometheus/client_golang/model (from $GOPATH)
godep: restore: exit status 1
```

@eparis proposed one of:
1) fix e2e to not use prometheus/golang_client/extraction
2) fix godep to not die in this situation
3) turn of the verification

Follow up of #14113

### PR DESCRIPTION
**Pull request by timstclair**
Fixes #14159 

@eparis @thockin

### CODE REVIEW

**Comment by eparis** [comment]
@timstclair if you take over #14198 I'll take this one.

**Comment by timstclair** [comment]
I think the failures are fixed by #14198

**Comment by eparis** [comment]
what's up with the e2e failure?

**Comment by timstclair** [comment]
No idea... it says everything passed?

**Comment by thockin** [comment]
Travis is complaining about godeps.  Is this another manual override to fix godeps?

**Comment by eparis** [comment]
travis/godeps should be ignored right now.

**Comment by eparis** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
(but i think we still want e2e to pass, this this is about changing e2e tests).  If we get a clean e2e, we should manually merge this PR.

**Comment by gmarek** [comment]
I believe this PR broke integration tests. 2 runs with it failed, 2 runs with it reverted passed.

**Pull request merged**
