### PR TITLE
add myself to cmd/[cloud-]controller-manage reviewer

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
add myself to `cmd/cloud-controller-manage` reviewer

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@stewart-yu did some fantastic work cleaning up all the controller manager startup code and prepare it for a component config move. Having him as a reviewer here would be great.

**Comment by sttts** [comment]
/approve

@luxas are you fine for the cloud ctrl manager?

**Review by luxas — APPROVED** [review]
/approve

Thanks for all your good work @stewart-yu :100: :tada:!

**Pull request merged**
