### PR TITLE
Adding missing UpdateStatus methods to PV/PVC client

### PR DESCRIPTION
**Pull request by markturansky**
@derekwaynecarr missed these important methods last time :)  PTAL?

### CODE REVIEW

**Comment by lavalamp** [comment]
Should perhaps there be some test code that calls these?

**Comment by markturansky** [comment]
will do :)

**Comment by markturansky** [comment]
Tests added, rebased, all green.

**Comment by markturansky** [comment]
@smarterclayton @derekwaynecarr PTAL?  just a few client adds and unit tests to match other client unit tests.

**Comment by derekwaynecarr** [comment]
LGTM

**Pull request merged**
