### PR TITLE
Jenkins: reenable cadvisor related tests for Trusty and Trusty-dev

### PR DESCRIPTION
**Pull request by wonderfly**
Tested in internal Jenkins.
@ixdy @andyzheng0831 @roberthbailey

### CODE REVIEW

**Comment by zmerlynn** [comment]
Please don't propose this to `release-1.1` directly. It should be proposed to `master` then cherry picked.

**Comment by wonderfly** [comment]
@zmerlynn, Later last year @ixdy and @ihmccreery reworked the e2e.sh such that jobs were versioned, and Trusty test jobs fell into release-1.1. Both of them can fill in some background but in the meantime you can take a look at #17734

**Comment by ixdy** [comment]
LGTM

**Comment by zmerlynn** [comment]
I'm so behind. Sorry.

**Comment by zmerlynn** [comment]
How do the master jobs get updates at all, then?

**Comment by wonderfly** [comment]
> How do the master jobs get updates at all, then?

@zmerlynn Same as how non-master jobs are updated - changes will be proposed to the master branch (will not be cherry-picked to other branches though).

**Comment by vishh** [comment]
LGTM

**Comment by ixdy** [comment]
@k8s-bot e2e test this again please

**Comment by ixdy** [comment]
@k8s-bot e2e test this

**Comment by wonderfly** [comment]
I guess @k8s-merge-robot is going to merge this automatically?

**Comment by ixdy** [comment]
No need to wait for merge bot, really.

**Pull request merged**
