### PR TITLE
replace deprecated setoutput

### PR DESCRIPTION
**Pull request by hanxiaop**
#### What type of PR is this?
/kind bug
/kind deprecation

#### What this PR does / why we need it:
Replace deprecated `SetOutput` in kubectl options cmds and tests to `SetOut and/or SetErr`, consistent to all current logics.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by hanxiaop** [comment]
@dougsland @KnVerey Could you please take a look? Any ideas on this?

**Comment by hanxiaop** [comment]
> /release-note-none
> 
> The deprecated pr in cobra [spf13/cobra#822](https://github.com/spf13/cobra/pull/822).
> 
> If I understand correctly, we should replace `cmd.SetOutput(&out)` with
> 
> ```
> 	cmd.SetOut(&out)
> 	cmd.SetErr(&out)
> ```
> 
> like [istio/istio#25084](https://github.com/istio/istio/pull/25084)

@pacoxu Fixed. I was referring to other use cases of `NewTestIOStreams`. However I think set both out and err should be better, which is consistent with the current logic. Thanks.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
