### PR TITLE
Switch bootstrap token authenticator informer to external types

### PR DESCRIPTION
**Pull request by yue9944882**
this pull switches the informer in bootstrap token authenticator to versioned types. once the admission controller's dependency on internal clientset/informer is gone, the authenticator will be the last type needs internal informers.

/sig auth
/sig api-machinery
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
this matches my expectations.

**Comment by jennybuckley** [comment]
cc @yliaog

**Pull request merged**
