### PR TITLE
Automated cherry pick of #60639: Added dashboard banner passthrough to GCE kube-up.

### PR DESCRIPTION
**Pull request by konryd**
Cherry pick of #60639 on release-1.9.

#60639: Added dashboard banner passthrough to GCE kube-up.

```release-note
CUSTOM_KUBE_DASHBOARD_BANNER environment variable will be used to populate notification banner in Kubernetes Dashboard add-on.
```

### CODE REVIEW

**Review by maciaszczykm — APPROVED** [review]

**Comment by mbohlool** [comment]
this look like a user facing change, right? if there is any user impact, there should be a release note for a patch release.

**Comment by mbohlool** [comment]
The branch is frozen. holding this for 1.9.5.

/hold

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60701)

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Pull request merged**
