### PR TITLE
Show restart count for init containers

### PR DESCRIPTION
**Pull request by lukaszo**
Coutner is reset for normal containers.
fixes issue: #26892

### CODE REVIEW

**Comment by lukaszo** [comment]
@sttts @smarterclayton Can you comment?

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by sttts** [comment]
Discussion in #26892 seems reasonable. Patch lgtm.

Node tests seem to be hanging.

**Comment by sttts** [comment]
@k8s-bot node test this issue: #IGNORE

**Comment by sttts** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by smarterclayton** [comment]
LGTM too, thanks

**Pull request merged**
