### PR TITLE
[Federation] Fix a typo in the ReplicaSet E2E test: s/extrace/extract/

### PR DESCRIPTION
**Pull request by perotinus**
```release-note
NONE
```

### CODE REVIEW

**Comment by madhusudancs** [comment]
Thanks!

/lgtm
/approve

**Comment by madhusudancs** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by perotinus** [comment]
@madhusudancs Can you re-lgtm this?

**Pull request merged**
