### PR TITLE
Replace map with sync.map

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**
Replace map with sync.map
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
Replace map with sync.map to improve performance

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by liggitt** [comment]
Is this lock actually contended? How many items are added to this in typical use? The loss of type safety on the map is not ideal if we don't actually need the performance gain.

**Comment by ZP-AlwaysWin** [comment]
> Is this lock actually contended? How many items are added to this in typical use? The loss of type safety on the map is not ideal if we don't actually need the performance gain.

hi @liggitt Thanks for your codereview

sync.Map was proposed because google found that RWLock and the map scheme did not perform well on high-read + multi-core CPUs (see the overview of sync map for details) Therefore, snyc.Map was introduced to improve the performance of multi-core high read and low write.
And this scene is more suitable for use:

- If the key written is stable (rarely)
- If different goroutine access to the key is different

https://www.youtube.com/watch?reload=9&v=C1EtfDnsdDs

And I think this modification makes it more readable, but it depends on your opinion whether it is merged

**Comment by liggitt** [comment]
This utility method is currently used in one place (in the kubelet), where it is written to at most 4 times while initializing the kubelet. The lock is there to prevent races, and is not called with high-frequency. I think the existing type safety checks on the map are preferable, since contention is not an issue.

**Comment by ZP-AlwaysWin** [comment]
> This utility method is currently used in one place (in the kubelet), where it is written to at most 4 times while initializing the kubelet. The lock is there to prevent races, and is not called with high-frequency. I think the existing type safety checks on the map are preferable, since contention is not an issue.

OK, I have a question, is it possible to remove this lock? Because I see that the procedure to initialize Kubelet is a sequential execution, there should be no competition。
The 4 times while initializing the kubelet. process is in the same goroutine, Does it produce races?


```
...
// define file config source
	if kubeCfg.StaticPodPath != "" {
		klog.Infof("Adding pod path: %v", kubeCfg.StaticPodPath)
		config.NewSourceFile(kubeCfg.StaticPodPath, nodeName, kubeCfg.FileCheckFrequency.Duration, cfg.Channel(kubetypes.FileSource))
	}

	// define url config source
	if kubeCfg.StaticPodURL != "" {
		klog.Infof("Adding pod url %q with HTTP header %v", kubeCfg.StaticPodURL, manifestURLHeader)
		config.NewSourceURL(kubeCfg.StaticPodURL, manifestURLHeader, nodeName, kubeCfg.HTTPCheckFrequency.Duration, cfg.Channel(kubetypes.HTTPSource))
	}
...
```

**Comment by liggitt** [comment]
it's easier to reason about with a lock, in case the kubelet startup is parallelized

**Comment by ZP-AlwaysWin** [comment]
> it's easier to reason about with a lock, in case the kubelet startup is parallelized

Thank you very much for your answers

**Comment by gianarb** [comment]
Hello sig-release is looking for owners for this issue that does not have a sig.
if you think this not belong to you feel free to assign to somebody else:

/sig node

**Pull request closed without merging**
