### PR TITLE
Mention kube-aws CLI in various guides

### LINKED ISSUE #21387: AWS docs: update CoreOS link?
Our docs say this:

> A contributed [example](coreos/coreos_multinode_cluster.md) allows you to setup a Kubernetes cluster based on [CoreOS](http://www.coreos.com), using
EC2 with user data (cloud-config).

I think though that example is out of date (?).  We should make sure to point it to the right place.

### PR DESCRIPTION
**Pull request by robszumski**
Documentation updates:
- Update AWS guide "alternative" to point towards a better maintained guide/CLI
- Add CoreOS AWS guide to list of official CoreOS guides

fixes https://github.com/kubernetes/kubernetes/issues/21387
cc: @justinsb

### CODE REVIEW

**Comment by justinsb** [comment]
ok to test

**Comment by justinsb** [comment]
LGTM - thanks!

**Comment by robszumski** [comment]
Not sure what happened with the e2e, but this didn't change any code, so I assume its flaky. Anything I need to do?

**Comment by justinsb** [comment]
I added the e2e-not-required as it is docs only.  I'm not sure what happens now that we've already failed the test though...  we'll see if the submit queue picks it up

**Pull request merged**
