### PR TITLE
Automated cherry pick of #122027: Don't sort under lock

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #122027 on release-1.29.

#122027: Don't sort under lock

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.27 performance regression watchcache to fix kube-apiserver scalability under heavy load of list requests
```

### CODE REVIEW

**Comment by liggitt** [comment]
is this intended to merge or just open for testing? is this resolving a regression?

**Comment by wojtek-t** [comment]
> is this intended to merge or just open for testing? is this resolving a regression?

It's intended to merge. It's kind-of a regression - it regressed as part of https://github.com/kubernetes/kubernetes/pull/113730 in 1.27 [which was added as a correctness fix, but visibly regressed the lock contention under heavy load from list requests].

This is exactly the reason why I would like to merge it - we've seen examples of clusters with heavy list load suffering from significant lock contention that this PR would visibly help with and I believe the very localized small change makes the risk pretty low.

**Comment by wojtek-t** [comment]
@kubernetes/release-managers - for cherrypick approval

**Comment by cpanato** [comment]
@wojtek-t this CP is only required for 1.28/29?

**Comment by wojtek-t** [comment]
> @wojtek-t this CP is only required for 1.28/29?

it's already in 1.30. And with 1.27 going EOL soon I'm not sure it's worth it. So I would say 1.28 and 1.29 is enough.

**Comment by cpanato** [comment]
> > @wojtek-t this CP is only required for 1.28/29?
> 
> it's already in 1.30. And with 1.27 going EOL soon I'm not sure it's worth it. So I would say 1.28 and 1.29 is enough.

thanks!

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
