### PR TITLE
Update cassandra.list

### PR DESCRIPTION
**Pull request by bobintornado**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

[Analytics]()

Upgrade cassandra version from 34x to 35x

### CODE REVIEW

**Comment by bobintornado** [comment]
I signed it!

**Comment by chrislovecnm** [comment]
@bobintornado dumb question but did you test this?  I would rather have this at 3.4 because the seedprovider is built off of 3.4 not 3.5.  If you can get the seedprovider building off of 3.4 I am all game.

**Comment by bobintornado** [comment]
@chrislovecnm oops. Didn't notice that. I thought 3.5 is an odd number so it should contain bug fixes only, didn't really notice that the SeedProvider is built off of 3.4 not 3.5. 

Should revert this PR for now then.

**Comment by thockin** [comment]
Rollback coming.

**Comment by chrislovecnm** [comment]
@bobintornado the good news is I talked with Datastax today and they want to push the provider into the C* code base ;)

**Comment by chrislovecnm** [comment]
@thockin let me know we you want me to close

**Comment by bobintornado** [comment]
@chrislovecnm 🎆 🎉 🎉🎉🎉

**Pull request merged**
