### PR TITLE
Added `kubectl wait` to wait on jsonpath

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>

Added single node JSONPath parser to 

**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:

- Adds feature to allow validation of JSONPath string for `kubectl wait`

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/83094

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rahulchheda** [comment]
cc: @dims 
Please ignore function naming, for now keeping this in WIP mode.

**Comment by rahulchheda** [comment]
Gentle reminder waiting for review, @dims @deads2k

**Comment by jglick** [comment]
Offhand it looks like this could be used to wait for an ingress controller to be initialized?

```bash
kubectl wait -n ingress-nginx --for='jsonpath={.status.loadBalancer.ingress[0].ip}' svc/ingress-nginx-controller
```

**Comment by lauchokyip** [comment]
Hi @rahulchheda , are you still interested in continue working on this?

**Comment by lauchokyip** [comment]
/reopen

Working on this one now

**Pull request closed without merging**
