### PR TITLE
godeps: update go-restful

### PR DESCRIPTION
**Pull request by mikedanese**
To pickup https://github.com/emicklei/go-restful/pull/311

@kubernetes/sig-api-machinery 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30914)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
cc @mbohlool

**Comment by caesarxuchao** [comment]
LGTM. @nikhiljindal @mbohlool do you have comments?

**Comment by lavalamp** [comment]
I'm a bit confused as to whether this is a desirable change or not. If we expect base64 data, reporting that as "string" in swagger is probably unhelpful? @mbohlool to decide :)

**Comment by mikedanese** [comment]
@lavalamp this is part of the golang encoding/json standard. Validation is broken without this.

**Comment by mikedanese** [comment]
E.g. we can't create csrs from kubectl without --validate=false

**Comment by mikedanese** [comment]
The field doc should state that the data is base 64 encoded as is the case for CSR Request field. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/certificates/v1alpha1/types.go#L43

Currently the swagger spec says array of integer for this which is completely wrong. This is a strict improvement.

**Comment by nikhiljindal** [comment]
I agree that string is an improvement over int array :)

@mikedanese You will have to run hack/update-api-reference-docs.sh to update api reference docs based on the swagger spec update.

**Comment by mbohlool** [comment]
What if somebody really means byte array? I guess array of integer could be wrong there too, but it is closer, right?
Another solution to this is to define a "type Something []byte" and customize the swagger type for it. You can follow the model of SchemaFormatHandler for Types.

**Comment by mikedanese** [comment]
@mbohlool In golang the json represntation of a []byte *is* a base64 encoded string. Both encoding/json and ugorji respect this.

From https://godoc.org/encoding/json

> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.

It's not optional. To encode a byte array as an array of ints, you would have to write your own json deserializer.

**Comment by lavalamp** [comment]
That's not the part I'm waffling over-- it's the conflation between
"string" and "base64 encoded data stored in a string", which are not the
same types at all.

**Comment by mbohlool** [comment]
related to this: OAI/OpenAPI-Specification#50

**Comment by mbohlool** [comment]
in open-api/swagger 2.0, this should be represented as type="string", format="byte" to distinct two cases. I guess some swagger 1.2 tools will understand that too.

**Comment by mikedanese** [comment]
> That's not the part I'm waffling over-- it's the conflation between
> "string" and "base64 encoded data stored in a string", which are not the
> same types at all.

I'm all for making this type doc more explicit but swagger validation is expecting an int array right now, which is not even possible to pass in for a []byte since go won't deserialize an int array to a []byte field. Swagger spec generator and golang stdlib json spec have a mismatch between the mapping of go types to json types. This fixes that and fixes a bug that breaks the kubectl experience for an alpha feature we want to release in 1.4 https://github.com/kubernetes/features/issues/43 .

Do you agree that "int array" is worse then "string" in swagger spec to represent "string that is base64 encoded bytes"? Can we improve this doc incrementally so as to fix a bug for the v1.4 release?

**Comment by lavalamp** [comment]
Yes I agree this is at least an improvement.

/lgtm

**Comment by mbohlool** [comment]
I also agree that this is an improvement, I think we should set the type to "byte" too and definitely fix this for swagger 2.0 generation, if it is already an issue. but this PR looks good to me.

**Comment by mikedanese** [comment]
Thanks for review!

**Comment by mbohlool** [comment]
You are welcome. I also meant to set the format to "byte" not the type. The type should stay as string. Thanks for the fix.

**Comment by mikedanese** [comment]
Why is @k8s-merge-robot saying this?

**Pull request merged**
