### PR TITLE
Change the getting started landing page.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by brendandburns** [comment]
@RichieEscarez @mansoorj @MikeJeffrey

**Comment by RichieEscarez** [comment]
My only concern here is that for users who dont yet know what GKE is, this change in the link will now bypass the overview page.

Maybe an alternative is to add a prominent pointer on the GKE overview page, something like "Ready to get started?" and link to the "before you begin" page to push users in that direction?

@MikeJeffrey can you please weigh in here? Is it safe to assume that users are familiar with GKE if they have gotten to the point of reading up on Kubernetes?

**Comment by mansoorj** [comment]
"What is kubernetes" and "Getting started" are two different things though.
Do we really want to use the same landing page for both?

**Comment by wojtek-t** [comment]
@brendandburns what's the plan for this PR? Are we going to proceed with it or can we close it?

**Comment by mansoorj** [comment]
We had an email thread with the documentation folks and decided the "What is Google Container Engine" page is fine for now till we come up with a more tailored getting started flow. That update to the landing page is already live, so I think we should be able to close the PR.

**Pull request closed without merging**
