### PR TITLE
Remove the unused variabe: syncDuration in volumemanager

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove the unused variabe: syncDuration in volumemanager

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

cc @jingxu97 @msau42

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
cc @jingxu97 @msau42

**Comment by davidz627** [comment]
please update `gofmt` with `hack/update-gofmt.sh`

**Comment by cwdsuzhou** [comment]
> please update `gofmt` with `hack/update-gofmt.sh`

@davidz627 Thank you! My mistake ! I have formatted the codes.

**Comment by cwdsuzhou** [comment]
ping @saad-ali

**Pull request merged**
