### PR TITLE
Retry replication controller rolling updates on version mismatch.

### PR DESCRIPTION
**Pull request by ghost**
When kubectl does rolling updates of replication controllers, retry updates that
fail due to version mismatches (caused by concurrent updates by other clients).
These failed rolling updates were causing intermittent e2e test failures
(e.g. issue 5821)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm

**Comment by quinton-hoole** [comment]
Good idea.  Will do.

**Comment by quinton-hoole** [comment]
Hi Prashanth

Refactored as discussed.  PTAL.

Q

**Comment by bprashanth** [comment]
just the one nit about the 4 time fields

**Comment by bprashanth** [comment]
please also update your commit msg no reup, it seems to have unwanted gendocs stuff in it

**Comment by quinton-hoole** [comment]
Thanks for the feedback Prashanth.  All issues addressed.  Ready for merge.

**Comment by bprashanth** [comment]
LGTM, though I don't know if i missed a comment of yours across rebase or you have a use case for specifying 2 pairs of timeouts (one for the wait and one for the general retry)

**Comment by bprashanth** [comment]
LGTM, not sure if you're still waiting on e2e

**Pull request merged**
