### PR TITLE
WIP: first iteration of go2idl

### PR DESCRIPTION
**Pull request by lavalamp**
The goal here is to provide a framework for better auto-generation tools. We need to switch to a system of parsing go files instead of reflection.

This is incomplete so far. I intend to convert the deep copy generator over to it first, extending it as necessary.

We need to do a lot of autogeneration in the future, so it's probably worth it to do well.
- json or other encodings
- conversions
- deep copies
- typed client libraries!!!
- documentation (note this grabs the comments that go with structs & members!)
- go restful setup code?

The type layout here supports generation by writing templates, or generation by writing go code.

(This is adapted from code for a toy project of mine, which is why I'm able to dump such a huge (and working, if incomplete) blob like this.)

### CODE REVIEW

**Comment by lavalamp** [comment]
This won't build until I include a dependency...

**Comment by wojtek-t** [comment]
I will take a look tomorrow.

**Comment by wojtek-t** [comment]
I just looked at the interface so far (I added just few minor comments). Once this will be ready, I'm happy to review it (just let me know it's ready).

**Comment by wojtek-t** [comment]
BTW - I'm obviously happy to rewrite existing generators (deep-copy and conversions) to use this framework once this is ready.

**Comment by lavalamp** [comment]
Thanks for the comments, @wojtek-t! I may or may not get to fix them this week on account of the test fixit.

**Comment by erictune** [comment]
Should this  be its own repo and vendored in.  Seems pretty non-kube
specific.

**Comment by wojtek-t** [comment]
>
Thanks for the comments, @wojtek-t! I may or may not get to fix them this week on account of the test fixit.

Sure - just let me know when it will be ready for review.

**Comment by lavalamp** [comment]
@brendandburns @eparis @thockin the merge robot size computation is drunk, this is not XS

**Comment by lavalamp** [comment]
@erictune Yes, I agree that it should be. I'd like to split it out later. I put it here for lack of a good spot.

**Comment by thockin** [comment]
I intend to give this a thorough try-out ASAP - after promo committees,
though

**Comment by lavalamp** [comment]
I found a little time to work on this. I addressed most of @wojtek-t's comments. There's still a few things it needs, but it's close to usable now, I think.

**Comment by lavalamp** [comment]
@googlebot, why you gotta embarrass me by telling people that I haven't configured git properly on that machine? :(

**Comment by thockin** [comment]
Can you squash this down to 1 for the godeps and 1 for your code?

Is there an example main() I can start at?

**Comment by lavalamp** [comment]
@thockin This isn't quite baked enough for a squash yet. But please take a look at the most recent commit, 9d13979, for an example main().

**Comment by lavalamp** [comment]
OK, I did squash most of it down.

**Comment by wojtek-t** [comment]
@lavalamp - can we move adding dependency to the separate PR? Currently github doesn't show diff, which makes it more difficult to review.

**Comment by lavalamp** [comment]
This is still pretty WIP, although it's getting closer. Don't look at anything but the set-gen example right now! In particular, I just broke the naming system by adding Alias.

**Comment by lavalamp** [comment]
OK, I made the naming systems sensible, and tests pass. Next I'll make one more pass, maybe add another example, and then try to package this into commits that are reviewable.

**Comment by lavalamp** [comment]
Suggestions for what would make a good example? I want something more involved than the set generator, but less involved than, say, deepcopy would be.

**Comment by lavalamp** [comment]
OK, I have three examples now. A 95% working set generator, a 15% working client generator, and a 60% working deep copier. About time for some more squashing.

I need to move the naming stuff out of the parse package. Ideally, we could have a drop-in replacement for the parser that consumed swagger (for the purpose of generating the client(s)).

**Comment by lavalamp** [comment]
OK, cleaned up a bit. Example output (not necessarily intended to be complete or mergable) in separate commits. I think this is actually ready for some review now.

I'M REALLY REALLY REALLY SORRY FOR DUMPING 8k LINES OF CODE ON YOU I OWE YOU A BEER

**Comment by lavalamp** [comment]
I can split into more separate commits if that would be clearer.

**Comment by wojtek-t** [comment]
>
I'M REALLY REALLY REALLY SORRY FOR DUMPING 8k LINES OF CODE ON YOU I OWE YOU A BEER

:-) I will start reviewing it today, but I'm not sure how long it will take me :)

**Comment by wojtek-t** [comment]
@lavalamp - I've added a bunch of comments - I will look into the rest tomorrow.

**Comment by lavalamp** [comment]
split into a new PR so as not to lose your comments on this commit.

**Comment by wojtek-t** [comment]
I believe #15714 is covering the main part of this PR (and should hopefully be merged soon) and #15715 is covering the rest. So I'm closing this PR.

**Pull request closed without merging**
