### PR TITLE
Apply ./hack/update-gofmt.sh

### PR DESCRIPTION
**Pull request by PurelyApplied**
/kind cleanup

**What this PR does / why we need it**:
Correcting a PRs `gofmt` issues with the recommended fix should not produce changes outside the scope of the PR and testing.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/ok-to-test
we enforce that code is gofmt-ed in CI, I'd be somewhat surprised if this code wasn't already being enforced in that way.

gofmt sometimes changes a bit between go versions though, and kubernetes uses a particular go version that may not be the latest (currently it is not, due to some fun stuff :-))

**Comment by PurelyApplied** [comment]
> we enforce that code is gofmt-ed in CI, I'd be somewhat surprised if this code wasn't already being enforced in that way.

That's actually how I got to here.  In another CL, I [ran afoul](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90413/pull-kubernetes-verify/1253439888221540355) of `gofmt`.  But these files were also altered by the recommended fix.

I'd have to dig into it, but I suspect that the check only runs on modified files, but the fix has global scope.  And while that makes sense, it does make the recommended fix a bit awkward.

**Comment by PurelyApplied** [comment]
Failure appears to be #86678.
/retest

**Comment by BenTheElder** [comment]
it's applied to all files, the check is just to `gofmt` and look for a diff.

> But these files were also altered by the recommended fix.

what go version do you have on your host? does it match the go version we use?  (1.13.9?) https://github.com/kubernetes/kubernetes/blob/99cc89b7da32d9c06916deb50b27fdb46934b777/build/root/WORKSPACE#L17

**Comment by PurelyApplied** [comment]
Ooof.  I pushed a bad merge.  I'm going to go ahead and close this one and double-check I was using the right `gofmt` / `go` version.

**Pull request closed without merging**
