### PR TITLE
Automated cherry pick of #104593: fix: ignore the case when updating tags

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #104593 on release-1.20.

#104593: fix: ignore the case when updating tags

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
fix: ignore the case when updating Azure tags
```

### CODE REVIEW

**Comment by nilo19** [comment]
/triage accepted
/sig cloud-provider
/area provider/azure
/priority critical-urgent
/kind bug
cc @feiskyer

**Comment by andyzhangx** [comment]
/hold
azure file test failures are fixed

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
