### PR TITLE
code-gen: output golint compliant 'Generated by' comment

### LINKED ISSUE #56489: code-generator: add "This file is generated" to every generated file
This is a follow-up of https://docs.google.com/a/google.com/document/d/1N1pBov7Odpg_u-kILHcswYh4VO-aMlYQdFIH64DYeek/edit?usp=sharing.

We could even put the complete command line of the generator in that line.

### PR DESCRIPTION
**Pull request by jennybuckley**
New PR instead of reopening #58115 because /reopen did not work.
This won't be ready to merge until the upstream https://github.com/kubernetes/gengo/pull/94 merges. Once that merges, the second commit will be changed to godep-save.sh and update-staging-godeps.sh, and the last commit will be changed to update-all.sh

The failing test is due to the upstream changes not being merged yet

```devel-release-note
Go code generated by the code generators will now have a comment which allows them to be easily identified by golint
```

Fixes #56489

### CODE REVIEW

**Comment by fisherxu** [comment]
[kubernetes/gengo#94](https://github.com/kubernetes/gengo/pull/94) has merged, the work can going on :)

**Comment by thockin** [comment]
/lgtm
/approve

Racking up the big numbers :)

**Comment by sttts** [comment]
Some k8s.io/metrics code has changes in the verify test.

**Comment by jennybuckley** [comment]
@sttts I'll rebase this and see if it fixes it

**Comment by jennybuckley** [comment]
#60442 merged
/test pull-kubernetes-verify

**Comment by sttts** [comment]
Switched the release note to "devel-release-note". This is too much on the development side to be in the generic release notes.

/lgtm

**Comment by sttts** [comment]
🎉

**Pull request merged**
