### PR TITLE
Fixed typo in IPVS documentation

### PR DESCRIPTION
**Pull request by shift**
**What this PR does / why we need it**:
Fixed documentation typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Fixed documentation typo in IPVS README.
```

### CODE REVIEW

**Review by brendandburns — APPROVED** [review]
LGTM.

**Comment by stewart-yu** [comment]
May be the same as [https://github.com/kubernetes/kubernetes/pull/55916](https://github.com/kubernetes/kubernetes/pull/55916)

**Pull request merged**
