### PR TITLE
fix bug that awsSDKGO expect nil instead empty slice for ec2.Describe…

### PR DESCRIPTION
**Pull request by M00nF1sh**
…Instances

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Seems like AWS make an change on their side.
```ec2.DescribeInstances(Filter: []*ec2.Filter{}) will fail with 'InvalidParameter Filter is nil' from cloudTrail logs.```
```ec2.DescribeInstances(Filter: nil) will works fine.```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix bug that AWS ELB fails to register instances.
```

### CODE REVIEW

**Review by micahhausler — APPROVED** [review]
/lgtm
/approve

**Comment by M00nF1sh** [comment]
this bug is hidden for a long time, and trigger by https://github.com/kubernetes/kubernetes/pull/76749/files#diff-5ec11ef6119b4b33f45b5d24d184db1aL4447 🤣

**Comment by jsafrane** [comment]
Adding 1.15 label, it's trivial and fixes a bug.

**Comment by justinsb** [comment]
Not sure why this isn't merging...

/approve
/lgtm

**Comment by M00nF1sh** [comment]
@justinsb 
Thanks for marking the priority 🤣 .
I talked with @alejandrox1 on slack, that this will get in despite code freeze (given that they pass another round of testing) 😄 
Seems tide is under pressure..

**Pull request merged**
