### PR TITLE
Automated cherry pick of #45523

### PR DESCRIPTION
**Pull request by jpoon**
Cherry pick of #45523 on release-1.6.

#45523: azure: loadbalancer: respect svc sessionaffinity

### CODE REVIEW

**Comment by jpoon** [comment]
cc @colemickens @jdumars

**Comment by roberthbailey** [comment]
Assigning to the 1.6 branch owners as per https://github.com/kubernetes/community/wiki

**Comment by enisoc** [comment]
@k8s-bot ok to test

**Comment by jpoon** [comment]
@colemickens any ideas what the test failures mean?

**Comment by jdumars** [comment]
@enisoc could we run the tests on this?  This is an important cherry pick for 1.6.5.

**Comment by enisoc** [comment]
@jpoon It looks like the `verify` test failed because you need to run `hack/update-bazel.sh`. Can you try that and commit the changes?

**Comment by enisoc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by enisoc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by enisoc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by enisoc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by jdumars** [comment]
@colemickens could you give the a once over and LGTM it if it LGTY?

**Comment by jdumars** [comment]
@brendandburns looking for a LGTM on this one if you could take a look.

**Comment by jdumars** [comment]
Happy dance!  Thanks everyone.

**Pull request merged**
