### PR TITLE
Remove redundant code in pkg/volume

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

Remove redundant code in pkg/volume

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mattcary — APPROVED** [review]
/lgtm

Thanks for the cleanup work!

**Comment by CaoDonghui123** [comment]
ping @saad-ali @thockin

**Comment by mattcary** [comment]
is this PR still relevant?

**Comment by CaoDonghui123** [comment]
Let me rebase this PR

**Pull request closed without merging**
