### PR TITLE
Mark v1beta1 EndpointSlice deprecated in favor of v1

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Marks v1beta1 EndpointSlices deprecated in favor of v1.

Leaves removal version at 1.25, so the only change is that users get an extra release of notifications to use v1.

#### Does this PR introduce a user-facing change?
```release-note
discovery.k8s.io/v1beta1 EndpointSlices are deprecated in favor of discovery.k8s.io/v1, and will no longer be served in Kubernetes v1.25.
```

/cc @swetharepakula @robscott

### CODE REVIEW

**Comment by liggitt** [comment]
Noticed this wasn't done when the topology deprecation question came up in https://github.com/kubernetes/website/pull/27032#discussion_r599250656

**Comment by liggitt** [comment]
This should be paired with a docs PR adding v1beta1 EndpointSlice to https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25 and enumerating the field-by-field deltas to v1 EndpointSlices

**Comment by swetharepakula** [comment]
Kubeproxy hasn't switched to using the v1 API. I think we need to wait for that before deprecating v1beta1.

**Comment by liggitt** [comment]
> Kubeproxy hasn't switched to using the v1 API. I think we need to wait for that before deprecating v1beta1.

Deprecation is not removal, just a notification of future removal. Since we know the 1.25 removal release and there's a replacement clients can switch to in 1.21, giving more advance notice to those clients seems like a good idea to me.

**Comment by liggitt** [comment]
/milestone v1.21

needed to ensure consistent surfacing of promoted APIs in 1.21 as replacements for existing beta versions

**Comment by swetharepakula** [comment]
The doc changes will be covered in kubernetes/website#27070

**Comment by aojea** [comment]
I don't fully understand the question, but these are the deprecation policy rules for the APIs https://kubernetes.io/docs/reference/using-api/deprecation-policy/ , maybe that can answer your question

**Pull request merged**
