### PR TITLE
Automated cherry pick of #56690: Disable session affinity for internal kuberntes service

### PR DESCRIPTION
**Pull request by afritzler**
Cherry pick of #56690 on release-1.9.

#56690: Disable session affinity for internal kuberntes service

### CODE REVIEW

**Comment by mbohlool** [comment]
Please add a release note to the parent PR.

**Comment by mbohlool** [comment]
@afritzler a patch PR requires a release-note unless it is a test or not affecting any user. Is this fall into any of those two categories? otherwise please add a release note to the parent PR. also please ping original PR's reviewers/approvers to approve/lgtm this PR. The deadline for next patch release is today.

**Comment by afritzler** [comment]
Sorry for the late response. 

The original PR doesn't have any release notes attached. Btw. this backport has been merged into 1.8 and 1.10 without any release notes.

**Pull request merged**
