### PR TITLE
Autoscaling should be part of clientset.Adaption

### PR DESCRIPTION
**Pull request by smarterclayton**
@mfojtik

### CODE REVIEW

**Comment by deads2k** [comment]
Can you think of a test for parity?  This looks ripe for slippage.

**Comment by smarterclayton** [comment]
It's easily detectable slippage, at least.  The comments on the class are dire.

**Comment by deads2k** [comment]
> It's easily detectable slippage, at least. The comments on the class are dire.

I can't think of a test that would work for me, so this is fine.

Also, I'm betting the "temporary" solution makes it to toddler age :)

**Comment by smarterclayton** [comment]
Hope so.

**Pull request merged**
