### PR TITLE
Fix 1.5 CHANGELOG

### PR DESCRIPTION
**Pull request by xiangpengzhao**
Fix broken `docs` link.

### CODE REVIEW

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Review by saad-ali — APPROVED** [review]

**Comment by saad-ali** [comment]
Will wait until after 1.5.1 ships today before merging this

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
@k8s-bot test this

**Comment by xiangpengzhao** [comment]
Thanks @saad-ali

**Pull request merged**
