### PR TITLE
Issue# 17860 Correct expression of nodecontroller for sync loop in no…

### PR DESCRIPTION
**Pull request by xinxiaogang**
…de.html
1. Remove "creates" from the sentence
2. Add general explaination for nodecontaoller

https://github.com/kubernetes/kubernetes/issues/17860

### CODE REVIEW

**Comment by xinxiaogang** [comment]
Have submitted my CLA using the correct email already.

**Comment by brendandburns** [comment]
This looks good.  You need to have your email in your github account I think.

**Comment by xinxiaogang** [comment]
@brendandburns Yes, I have already add my email in my github account. And with CLA signed. Not sure what to do next?

**Comment by xinxiaogang** [comment]
@brendandburns How should I do next? Any suggestion?

**Comment by brendandburns** [comment]
@xinxiaogang I don't see your email when I look at your profile, so maybe it's not public?

I manually validate the CLA for this PR, but we should figure out why the automation doesn't see it.

Also you need to run:

`hack/update-generated-docs.sh`

**Comment by xinxiaogang** [comment]
@brendandburns I have my email configured in my profile as below:
xnxin@ebay.com Primary Public
Is this correct?

**Comment by brendandburns** [comment]
@xinxiaogang odd, when I look at https://github.com/xinxiaogang

I don't see your mail, but when I look at https://github.com/brendandburns

I see mine, so I think something must not be quite right?

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
