### PR TITLE
MESOS: forward globally declared cadvisor housekeeping flags

### PR DESCRIPTION
**Pull request by jdef**
xref https://github.com/kubernetes/kubernetes/pull/20331#issuecomment-180544965

/cc @linsun

### CODE REVIEW

**Comment by jdef** [comment]
FWIW cadvisor flags are deprecated #19432

**Comment by linsun** [comment]
I think this changes work for me.  Here is how I tried it:

1. rebuild a km docker image with the change in it, plus setting these two flags when launching the scheduler:  **--housekeeping_interval=50s --global_housekeeping_interval=100s**

2. deploy mesos, and kubernetes as a framework on mesos using the km image.   docker exec into the km container:

- check the km scheduler process:
00:00:00 /opt/kubernetes/km scheduler **--housekeeping_interval=50s --global_housekeeping_interval=100s** --address=10.143.197.73 --mesos-master=10.143.197.73:5050 --etcd-servers=http://10.143.197.73:4001 --mesos-user=root --api-servers=10.143.197.73:8888 --cluster-dns=10.10.10.10 --cluster-domain=cluster.local --v=4

- validated in scheduler.log:

I0316 01:50:42.370195      47 service.go:503] prepared executor command "./km" with args '[./km minion --run-proxy=true --proxy-
bindall=false --proxy-logv=0 --proxy-mode=userspace --path-override= --max-log-size=10Mi --max-log-backups=5 --max-log-age=7 --c
onntrack-max=0 --conntrack-tcp-timeout-established=0 --api-servers=10.143.197.73:8888 --v=0 --allow-privileged=false --suicide-t
imeout=20m0s --mesos-launch-grace-period=5m0s --mesos-cgroup-prefix=mesos --cadvisor-port=4194 --sync-frequency=10s --contain-po
d-resources=true --enable-debugging-handlers=true --cluster-dns=10.10.10.10 --cluster-domain=cluster.local **--housekeeping_interv
al=50s --global_housekeeping_interval=1m40s]'**

I'm not sure how to check minion/server.go log, else, I can probably validate this line too:

	log.V(2).Infof("Spawning hyperkube %v with args '%+v'", server, args)

**Comment by jdef** [comment]
you can look at the stderr of the mesos sandbox that's running the
executor, it shows the command lines executed for the kubelet and kube-proxy

**Comment by linsun** [comment]
@jdef, I'm hitting an environmental issue where the executor on the host times out when downloading the km binary... seems the timeout is 1 min.   trying to see if i can increase the network speed or tune the 1 min timeout value.

**Comment by jdef** [comment]
try the `executor_registration_timeout` slave option?

**Comment by linsun** [comment]
Sorry for the delay.  I updated the network speed of the env, and the stderr log looks good:

I0317 03:08:12.063347    2850 task.go:220] starting task process "/opt/ibm/mesos/work/slaves/d58a68eb-5105-4be7-9ae8-577d5b24e9b2-S0/frameworks/d58a68eb-5105-4be7-9ae8-577d5b24e9b2-0001/executors/6d493c88c0ac86b3_k8sm-executor/runs/22ac059b-19ff-4ada-bc4d-65db178f3235/km" with args '[executor --api-servers=10.143.100.223:8888 --v=0 --allow-privileged=false --suicide-timeout=20m0s --mesos-launch-grace-period=5m0s --cadvisor-port=4194 --sync-frequency=10s --enable-debugging-handlers=true --cluster-dns=10.10.10.10 --cluster-domain=cluster.local --hostname-override=10.143.100.238 --kubelet-cgroups= --cgroup-root=/mesos/22ac059b-19ff-4ada-bc4d-65db178f3235 **--housekeeping_interval=50s --global_housekeeping_interval=1m40s**]'
I0317 03:08:12.066579    2850 task.go:257] task started executor

**Comment by jdef** [comment]
great. i'll mark this as mergeable. we missed the 1.2 cutoff, but this can
probably get cherrypicked for 1.2.1

**Comment by bgrant0607** [comment]
@jdef Why would you like this to be cherrypicked into 1.2?

**Comment by jdef** [comment]
Some folks from IBM are doing some performance work and want the ability to
change these settings. We barely missed the cutoff for 1.2. The changeset
is relatively small and is backwards compat.

What's the criteria for getting things cherrypicked into 1.2?

**Pull request merged**
