### PR TITLE
move pkg/util/configz to k8s.io/component-base

### PR DESCRIPTION
**Pull request by cici37**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This PR is part of the issue [here](https://github.com/kubernetes/cloud-provider/issues/29). See [KEP-removing-in-tree-providers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md) for more details.
This PR is to remove CCM's dependency: pkg/util/configz 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
I think k8s.io/component-base/configz might be better as opposed to apiserver, I'll defer to @liggitt @mtaufen on whether it fits there.

**Comment by mtaufen** [comment]
The descriptions says:
> This PR is to remove CCM dependency pkg/util/configz

Is that true? I'd be surprised if configz depends on CCM?

Overall moving configz to component base SGTM. It's the right place for it.
I'll also take this as a moment to remind everyone that configz is currently for debugging only, and is not a production-grade API that any other system should depend on ;).

Since this is just a simple move-to-component-base:
/lgtm

**Comment by cici37** [comment]
@mtaufen  Sorry I should make it more clear on the PR explanation^^ It should be `CCM's dependency`. ^^

**Comment by cici37** [comment]
Hi @mtaufen , I just added a change to `vendor/modules.txt` for vendor verify test. Could you please add back /LGTM when you have time? Thank you

**Comment by liggitt** [comment]
lgtm, though a rebase is needed

**Review by andrewsykim — COMMENTED** [review]
/lgtm

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
