### PR TITLE
Update snapshot CRDs

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updates snapshot CRDs based on the recently merged PR: https://github.com/kubernetes-csi/external-snapshotter/pull/419

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by jberkus** [comment]
Shouldn't this PR actually have a release note?

`Update snapshot-controller to 3.0.2`

**Comment by msau42** [comment]
@jberkus this is only updated for kube-up.sh, which from my understanding is not officially part of the Kubernetes release?

**Pull request merged**
