### PR TITLE
remove bazel BUILD in EXCLUDE_TARGET in makefile

### PR DESCRIPTION
**Pull request by PalanQu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove deprecated BUILD file in makefile

#### Which issue(s) this PR fixes:

Cleanup #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by PalanQu** [comment]
triage/accepted

**Comment by cblecker** [comment]
Thanks @PalanQu !

**Pull request merged**
