### PR TITLE
fix broken link in some files

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix broken link in some files
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by lojies** [comment]
@cheftako @deads2k

**Pull request merged**
