### PR TITLE
Fix Failed to release lock

### LINKED ISSUE #88194: when use leaderelection failed to release lock
**What happened**:
when use leaderelection failed to release lock  
```
E0215 20:05:38.726163   48791 leaderelection.go:307] Failed to release lock: Lease.coordination.k8s.io "example" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0

```
**What you expected to happen**:
release lock success
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
lock type is lease 
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by silenceper**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix Failed to release lock.

fix error  when use leaderelection:
```
E0215 20:05:38.726163   48791 leaderelection.go:307] Failed to release lock: Lease.coordination.k8s.io "example" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0
```

**Which issue(s) this PR fixes**:
fix #88194 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the PR. Please add a test demonstrating the bug this is fixing so we ensure it doesn't regress

**Comment by silenceper** [comment]
> Thanks for the PR. Please add a test demonstrating the bug this is fixing so we ensure it doesn't regress

The reason for this bug is that when the lease object is updated, the fields in the lease object are verified.

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/coordination/validation/validation.go#L39-L52

I want to use fakeclient to build test cases, but the above verification will not be run in fakeclient, making it impossible to create this test case.

**Comment by liggitt** [comment]
@smarterclayton it looks like this capability was added in https://github.com/kubernetes/kubernetes/pull/71490 and never tested against a real server.

**Comment by smarterclayton** [comment]
This capability was added before lease coordination API was added, so the update against a config map or endpoint annotation was allowed (there's nothing validating 0 lease duration seconds).

/lgtm
/approve

**Comment by markusthoemmes** [comment]
/retest

This seems good to go!

**Comment by amrmahdi** [comment]
Hi, any reason why this PR is not merged yet ?

**Comment by whalecold** [comment]
> Hi, any reason why this PR is not merged yet ?

It looks like lacking of the test case.

**Comment by silenceper** [comment]
> > Hi, any reason why this PR is not merged yet ?
> 
> It looks like lacking of the test case.

I do n’t know how to write a test case for this change.

**Comment by wking** [comment]
#91942 is attempting to carry this and add the requested tests.

**Comment by liggitt** [comment]
/hold

https://github.com/kubernetes/kubernetes/pull/80954 is similar, but adds tests and handles the release differently. @smarterclayton which should we proceed with?

**Comment by liggitt** [comment]
/close 
in favor of #80954 which added a test

**Pull request closed without merging**
