### PR TITLE
fix staticchekc failer in apiserver/pkg/endpoints/request

### PR DESCRIPTION
**Pull request by KobayashiD27**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix staticchekc failer in apiserver/pkg/endpoints/request
I deleted the unused parameter "const audiencesKey"
**Which issue(s) this PR fixes**:

Fixes #
part of #92402
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sttts** [comment]
The audiences key moved in https://github.com/kubernetes/kubernetes/pull/69916/commits/817cf70191b73d1ee9f4e7af83089e5854e5131d#diff-1a96858c0f735f22e85ac6d0d2b8b1a2b4802fd6e4193552136d51a71bdf9286R29.

/lgtm
/approve

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
