### PR TITLE
Fix golint failures of pkg/kubelet/status/...

### PR DESCRIPTION
**Pull request by uzuku**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures of pkg/kubelet/status/...

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for tackling this lint errors

/ok-to-test

**Comment by Uzuku** [comment]
ping @vishh 
for review , Thanks!

**Comment by uzuku** [comment]
@liggitt could you help to review this pr? Thanks

**Pull request merged**
