### PR TITLE
Automated cherry-pick of #19600 to upstream release-1.1

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry pick #19600 "Fixed cleanup of persistent volumes" to 1.1 release.

Fixes https://github.com/kubernetes/kubernetes/issues/20734

CC @jsafrane

### CODE REVIEW

**Comment by saad-ali** [comment]
@jsafrane This cherry-picks your PR #19600 from master to the v1.1 branch. Please confirm that you're okay with these commits being contributed to Google, and code review this PR.

**Comment by jsafrane** [comment]
@saad-ali, I'm okay with picking this commit to 1.1.

Who is supposed to backport the patch? It does not even compile.

**Comment by saad-ali** [comment]
> Who is supposed to backport the patch? It does not even compile.

@jsafrane Ideally the patch author. I was hoping this was a quick and easy back port, so I wouldn't have to bug you. But looks like we'll need to pick up multiple patches. Let me know if you have the bandwidth to do this, otherwise I'll take a crack at hunting down all the dependent PRs, and send out a new cherry-pick.

**Comment by jsafrane** [comment]
Whole `client.Interface` was reworked since 1.1, IMO you can't simply cherry-pick it. I backported the patch in this branch: https://github.com/jsafrane/kubernetes/commits/devel/backport-pod-cleanup, see commit https://github.com/jsafrane/kubernetes/commit/bc2770d00b85340b033594eb746036a0f521ab16

**Comment by saad-ali** [comment]
I don't think it's a good idea to write custom code to get 1.1 working--either we should pick up all the dependent PRs or none. Given how much of a pain it will be to get 1.1 up to date, I say we hold off, since the 1.2 branch is being cut soon.

**Pull request closed without merging**
