### PR TITLE
Unify fuzzers and roundtrip tests

### PR DESCRIPTION
**Pull request by sttts**
- reorganize apimachinery/pkg/api/testing package to avoid circular imports
- make fuzzers modular per apigroup
- add roundtrip test for meta types
- add roundtrip test for a couple of staging apigroups

Follow-up:

- split `pkg/api` tests by apigroup

### CODE REVIEW

**Comment by smarterclayton** [comment]
Did a quick pass, made sense to me

**Comment by deads2k** [comment]
/approve no-issue
lgtm

squash bazel.

**Pull request merged**
