### PR TITLE
Resetting maxUnavailable for kubectl rolling update to 0

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/18463

Reverts https://github.com/kubernetes/kubernetes/pull/18616

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @ironcladlou @janetkuo @mqliang

**Comment by bgrant0607** [comment]
LGTM

**Comment by kargakis** [comment]
LGTM

**Comment by nikhiljindal** [comment]
@k8s-bot test this github issue: https://github.com/kubernetes/kubernetes/issues/22300

**Comment by ixdy** [comment]
@k8s-bot test this, issue #22435

**Pull request merged**
