### PR TITLE
Fix some grammar issues in controller code

### PR DESCRIPTION
**Pull request by nkwangleiGIT**
**What this PR does / why we need it**:
Fix some grammar issues in controller code to make it look better

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by resouer — APPROVED** [review]
/lgtm

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60760)

**Comment by resouer** [comment]
@thockin Emmm... are you a bot now?

**Comment by soltysh** [comment]
@nkwangleiGIT thank you for your contribution, but generally we're trying to fix those spelling problems only when fixing some actual code. 
/hold

**Comment by nkwangleiGIT** [comment]
@soltysh thanks for your comments, will take care next time.
I just fixed a minor logging issue this time in this PR, and will try to contribue more actual code later.
Thanks!

**Review by soltysh — CHANGES_REQUESTED** [review]
Sorry, it's still just grammar changes. Please fix some actual code along with it to get it accepted.

**Comment by nkwangleiGIT** [comment]
@soltysh I see, will check if I can deliver more changes later, or will create a new PR, thanks

**Comment by bowei** [comment]
closing
/close

**Pull request closed without merging**
