### PR TITLE
migrate containerd registry endpoint to hosts.toml

### LINKED ISSUE #110312: registry.mirrors conainerd config is deprecated, need to move to hosts.toml based config
In tests and here:
https://github.com/kubernetes/kubernetes/blob/62d9f8ba80f4cc660a88dcc34f56c5c6f7df17ea/cluster/gce/gci/configure-helper.sh#L3086-L3091 containerd config is using deprecated way configuring mirrors. Need to switch to the hosts.toml based approach.

/kind cleanup
/sig node
/area test

### PR DESCRIPTION
**Pull request by matthyx**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
registry.mirrors containerd config is deprecated, need to move to hosts.toml based config

#### Which issue(s) this PR fixes:

Fixes #110312

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
@SergeyKanzhelev any idea how to test this?

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev any idea how to test this?

at a minimum containerd needs to start up. 

It is actually a very good question. Typically it's tested with ssh to the node and running cri pull in verbose mode. It would be nice to have an image available at `https://registry.k8s.io` but not at `https://k8s.gcr.io` and a very simple e2e test that pulls that image

**Pull request closed without merging**
