### PR TITLE
Fix golint failures under test/e2e/framework/metrics

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This just fixes golint failures under test/e2e/framework/metrics

ref: https://github.com/kubernetes/kubernetes/issues/68026

**Does this PR introduce a user-facing change?**:

```release-note-none

```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
thanks!

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by oomichi** [comment]
@BenTheElder Thanks for your review :-)

**Comment by oomichi** [comment]
@cblecker Could you take a look at this?

**Comment by cblecker** [comment]
/approve
for `hack/`

**Pull request merged**
