### PR TITLE
Revert "Update daemonSet status even if syncDaemonSet fails"

### LINKED ISSUE #113036: [Flaky test] k8s.io/kubernetes/test/integration/daemonset
### Which jobs are flaking?

- pr:pull-kubernetes-integration
- ci-kubernetes-integration-master

### Which tests are flaking?

- k8s.io/kubernetes/test/integration/daemonset 
   TestDSCUpdatesPodLabelAfterDedupCurHistories

### Since when has it been flaking?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestDSCUpdatesPodLabelAfterDedupCurHistories
Maybe since 9.30?
image

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580295864935518208

### Reason for failure (if possible)

I didn't find err msg in test files. Instead I found:
```
I1012 19:09:56.872061  102520 event.go:294] "Event occurred" object="one-node-daemonset-test/foo" fieldPath="" kind="DaemonSet" apiVersion="apps/v1" type="Warning" reason="FailedCreate" message="Error creating: Post \"https://127.0.0.1:40641/api/v1/namespaces/one-node-daemonset-test/pods\": context canceled"
E1012 19:09:56.872142  102520 daemon_controller.go:1020] Post "https://127.0.0.1:40641/api/v1/namespaces/one-node-daemonset-test/pods": context canceled
E1012 19:09:56.871741  102520 scheduling_queue.go:982] "Error while retrieving next pod from scheduling queue" err="scheduling queue is closed"
```

12 other tests failed because of `context canceled` these days.
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=context%20canceled

Maybe it's because of bad network? Simple timeout?

### Anything else we need to know?

Some other failed links:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580295864935518208
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580203756920770560
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112219/pull-kubernetes-integration/1580266306991558656

Also, [flakes-latest.json](http://storage.googleapis.com/k8s-metrics/flakes-latest.json) shows this is a flaky test.
```
"pr:pull-kubernetes-integration": {
    "consistency":0.968,
    "flakes":10,
    "test_flakes":{
        "k8s.io/kubernetes/test/integration/daemonset TestDSCUpdatesPodLabelAfterDedupCurHistories":3,
        "test-cmd run_kubectl_apply_tests":2,
        "test-cmd run_exec_credentials_tests":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_non-PDB_violating_pod_is_preempted_despite_its_higher_priority":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_node_without_any_PDB_violating_pods_is_preferred_for_preemption":1,
        "k8s.io/kubernetes/test/integration/volume TestPVCBoundWithADC":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_node_with_fewer_PDB_violating_pods_is_preferred_for_preemption":1,
        "test-cmd run_kubectl_request_timeout_tests":1,
        "test-cmd run_storage_class_tests":1
    }
}
```
```
"ci-kubernetes-integration-master":  {
    "consistency":0.714,
    "flakes":8,
    "test_flakes":{
        "k8s.io/kubernetes/test/integration/daemonset TestDSCUpdatesPodLabelAfterDedupCurHistories":4,
        "test-cmd run_kubectl_server_side_apply_tests":2,
        "test-cmd run_crd_tests":2,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers":1,
        "test-cmd run_kubectl_apply_tests":1,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers/running_pod_with_PodDisruptionConditions_disabled":1,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers/running_pod_with_PodDisruptionConditions_enabled":1
    }
}
```

### Relevant SIG(s)

_No response_

### PR DESCRIPTION
**Pull request by soltysh**
/kind flake
/sig apps

#### What this PR does / why we need it:
This reverts commit 2ee024a4df28086883a148adedc744c5d4925a9b (https://github.com/kubernetes/kubernetes/pull/112127).
We're hours before the freeze and we don't want to block the queue with flakes.

#### Which issue(s) this PR fixes:
Fixes #113036

#### Special notes for your reviewer:
/assign @liggitt 
/cc @gjkim42

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by atiratree** [comment]
I think data from https://github.com/kubernetes/kubernetes/pull/112127#issuecomment-1307271287 shows that https://github.com/kubernetes/kubernetes/pull/113732 should fix the flake

**Comment by gjkim42** [comment]
/hold

@soltysh 

I think it is quite certain that the problem is only a test issue and we have an easy fix for that. Could you reconsider this revert?

```
https://github.com/kubernetes/kubernetes/pull/113733
stress ./daemonset.test -test.run=TestUpdateStatusDespitePodCreationFailure      
5s: 0 runs so far, 0 failures                                                                                                                                                                              
10s: 0 runs so far, 0 failures                                                                                                                                                                             
15s: 0 runs so far, 0 failures                                                                                                                                                                             
20s: 12 runs so far, 0 failures                                                                                                                                                                            
25s: 12 runs so far, 0 failures                                                                                                                                                                            
30s: 12 runs so far, 0 failures                                                                                                                                                                            
35s: 14 runs so far, 0 failures                                                                                                                                                                            
40s: 24 runs so far, 0 failures                                                                                                                                                                            
45s: 24 runs so far, 0 failures                                                                                                                                                                            
50s: 26 runs so far, 0 failures                                                                                                                                                                            
55s: 35 runs so far, 0 failures                                                                                                                                                                            
1m0s: 36 runs so far, 0 failures                                                                                                                                                                           
1m5s: 37 runs so far, 0 failures                                                                                                                                                                           
1m10s: 41 runs so far, 0 failures                                                                                                                                                                          
1m15s: 48 runs so far, 0 failures
...
49m5s: 2133 runs so far, 0 failures
49m10s: 2137 runs so far, 0 failures
49m15s: 2140 runs so far, 0 failures
49m20s: 2144 runs so far, 0 failures
49m25s: 2148 runs so far, 0 failures
49m30s: 2152 runs so far, 0 failures
49m35s: 2156 runs so far, 0 failures
49m40s: 2160 runs so far, 0 failures
49m45s: 2162 runs so far, 0 failures
49m50s: 2166 runs so far, 0 failures
49m55s: 2169 runs so far, 0 failures
50m0s: 2174 runs so far, 0 failures
```

**Comment by soltysh** [comment]
> I think data from https://github.com/kubernetes/kubernetes/pull/112127#issuecomment-1307271287 and https://github.com/kubernetes/kubernetes/pull/112127#issuecomment-1307300214 shows that https://github.com/kubernetes/kubernetes/pull/113732 should fix the flake

let's get the revert merge to unblock queue, and we can bring back the other fix a bit later, and backport it to 1.26 and others

**Comment by soltysh** [comment]
> I think it is quite certain that the problem is only a test issue and we have an easy fix for that. Could you reconsider this revert?

it's easier to handle the fix and bringing back the original PR in separate PR, rather than risking destabilizing the queue hours before the freeze

/hold cancel

**Pull request merged**
