### PR TITLE
bump: upgrade gorilla/websocket from v1.4.2 to v1.5.0

### PR DESCRIPTION
**Pull request by tukwila**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR will update gorilla/websocket from v1.4.2 to v1.5.0.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Gorilla websocket is important lib in k8s long term connection protocol so it should be updated with the newly version.

#### Does this PR introduce a user-facing change?
NONE

```release-note
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/assign @mengjiao-liu
Note that the library in question is not actively maintained.
/triage accepted

**Comment by bart0sh** [comment]
@tukwila please fix CI test failures, thanks.

**Pull request closed without merging**
