### PR TITLE
Automated cherry pick of #20109

### PR DESCRIPTION
**Pull request by vishh**
cc @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: #20757

/cc @saad-ali did the fix to #20757 only get merged to master or did it get back-ported (in which case we should re-open it)?

**Comment by saad-ali** [comment]
@roberthbailey https://github.com/kubernetes/kubernetes/pull/21770#issuecomment-187838974 didn't fail because of #20757.

Looking at the logs, it hit: `Error creating PD`. That was tracked by issue https://github.com/kubernetes/kubernetes/issues/15417 and fixed by PR https://github.com/kubernetes/kubernetes/pull/17747

Both PR https://github.com/kubernetes/kubernetes/pull/17747 and #20757 were not cherry picked in to 1.1 because they fix test issues, not product bugs. Let me know if this reasoning is incorrect, and I will cherry pick my test-only fixes back to the 1.1 branch.

**Comment by roberthbailey** [comment]
I know that @ihmccreery has been cherry picking quite a few test infrastructure fixes back into the release-1.1 branch, but I don't know if he's also been cherry picking flaky test fixes.

**Comment by ihmccreery** [comment]
It's been inconsistent.  Some backported, others not.  Probably depends how severe.

**Comment by roberthbailey** [comment]
@vishh - the unit/integration tests failed -- can you find the flaky issue and re-run them?

**Comment by vishh** [comment]
@k8s-bot test this github issue #IGNORE

**Pull request merged**
