### PR TITLE
improve: reduce function calling number

### PR DESCRIPTION
**Pull request by lowang-bh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

reduce unnecessary function calling

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

NONE

### CODE REVIEW

**Comment by lowang-bh** [comment]
Hi, @kerthcet would you please help to review this pr? thanks.

**Review by kerthcet — COMMENTED** [review]
/lgtm
But I'm not the sig apps approver, so cc @kubernetes/sig-apps-leads

**Comment by lowang-bh** [comment]
Hi, @kow3ns @Huang-Wei would you plz help to review it? thanks.

**Comment by lowang-bh** [comment]
# 10k replicas benchmark compare
```
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
BenchmarkReplicas_10k_Before-8   	    4509	    240424 ns/op	       0 B/op	       0 allocs/op
BenchmarkReplicas_10k_After-8    	  410385	      2918 ns/op	       0 B/op	       0 allocs/op
```

# 1k replicas benchmark compare
```
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
BenchmarkReplicas_1k_Before-8   	   46911	     25067 ns/op	       0 B/op	       0 allocs/op
BenchmarkReplicas_1k_After-8    	 3708330	       324.2 ns/op	       0 B/op	       0 allocs/op
```
# 100 replicas benchmark compare
```
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
BenchmarkReplicas_100_Before-8   	  390878	      2579 ns/op	       0 B/op	       0 allocs/op
BenchmarkReplicas_100_After-8    	23780976	        50.01 ns/op	       0 B/op	       0 allocs/op
```

# 10 replicas benchmark compare
```
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
BenchmarkReplicas_10_Before-8   	 4332030	       271.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkReplicas_10_After-8    	49006929	             23.80 ns/op	       0 B/op	       0 allocs/op
PASS
```

**Comment by kerthcet** [comment]
Hi @soltysh would you like to take a look, we're now approaching code freeze .

**Pull request merged**
