### PR TITLE
More human readable condition for the retry logic

### PR DESCRIPTION
**Pull request by kayrus**
/kind cleanup

**What this PR does / why we need it**:

It changes the if condition to be more human readable, since `not A or not B` equals to `not (A and B)` and we can use an else condition to keep just `A and B`

### CODE REVIEW

**Comment by liggitt** [comment]
/unassign
/assign @deads2k 

I'm pretty sure a tweak to this is in progress to also tolerate connection establishment failure

**Comment by kayrus** [comment]
@liggitt I'm working on `connection establishment failure` in parallel within #82405, see https://github.com/kayrus/kubernetes/blob/ce9f120fb39c282fee6921766ae0587c67fe88fa/staging/src/k8s.io/apimachinery/pkg/util/net/util.go. I don't want to push it, until I'm confident that it works, however feel free to give anearly feedback.

**Pull request closed without merging**
