### PR TITLE
fixed error typo

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@derekwaynecarr PTAL

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks!
LGTM

**Comment by brendandburns** [comment]
closing and re-opening to re-trigger shippable and travis...

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by stevekuznetsov** [comment]
I'm getting that failure in `hack/verify-description.sh` locally as well.

**Comment by stevekuznetsov** [comment]
@brendandburns Removed description from internal types. Remnant of a force-merge?

**Pull request merged**
