### PR TITLE
Add logic to watch for and scroll to anchors in URLs

### LINKED ISSUE #13599: links in kubernetes.io/v1.0/docs/api-reference/operations.html fail
Start here: http://kubernetes.io/v1.0/docs/api-reference/operations.html, then click the "v1.Binding" link, the correct address http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_binding is shown in the address bar, but the browser doesn't take the user to the section.

cc @RichieEscarez

### PR DESCRIPTION
**Pull request by RichieEscarez**
Fixes #13599

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thank you @RichieEscarez ! Have you tested it? Because I had tried a similar fix on my own, but it complained something like "$(hash) is not a valid object". (Probably it was caused by bugs in my code, since I don't know js well)

**Comment by RichieEscarez** [comment]
Sorry @caesarxuchao, I ran to a meeting and didnt push to my fork, ill do that now so that you can test it (it works great in my local build). Give me a few minutes.

**Comment by RichieEscarez** [comment]
@caesarxuchao, PTAL: http://richieescarez.github.io/kubernetes/v1.0/docs/api-reference/operations.html

**Comment by caesarxuchao** [comment]
Thank you very much! Yes, it works. It must had been some other bugs in my attempt.

**Comment by caesarxuchao** [comment]
@k8s-oncall, I don't thinkt he merge robot is capable of testing PR for gh-pages. Could you merge it manually? Thanks.

**Comment by caesarxuchao** [comment]
@RichieEscarez i'm closing this for now as it's driving the merge robot crazy. I'll reopen it tomorrow morning and try to draw @k8s-oncall's attention. Please reopen it if I forget to do so. Thanks.

**Pull request merged**
