### PR TITLE
Refactor cronjob test case with sets.String

### LINKED ISSUE #51396: Refactor unit test case with sets.String to replace string slice
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind feature

**What happened**:
Refactor unit test case with sets.String to replace string slice
To use golang sets.String, that will help check if two groups equal with each other.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Refactor cronjob test case with sets.String

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/51396

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by zhangxiaoyu-zidif** [comment]
Hi, @xiangpengzhao , do you know why me test stoped in pull-kubernetes-e2e-kubeadm-gce?
some test goes wrong?

**Comment by xiangpengzhao** [comment]
IIUC, pull-kubernetes-e2e-kubeadm-gce is not required for merging by now and not running.

**Pull request merged**
