### PR TITLE
Updating winkernel kube-proxy OWNERS file

### PR DESCRIPTION
**Pull request by elweb9858**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Updates the owners and reviewers of Winkernel Proxier.
**Which issue(s) this PR fixes**:

Fixes #
NONE
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by elweb9858** [comment]
fyi @sbangari

**Comment by elweb9858** [comment]
@feiskyer can you add milestone 1.20 to this PR?

**Comment by feiskyer** [comment]
@elweb9858  added. Ready for merge now

**Review by kumarvin123 — APPROVED** [review]

**Pull request merged**
