### PR TITLE
Fix index out of range error when sorting kubectl get

### PR DESCRIPTION
**Pull request by mfpierre**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

There's an unsafe access to the `[0]` element of  `r.objects` which can cause this error to happen:

```kubectl get po -n datadog-system -l app=datadog-agent --sort-by=.metadata.creationTimestamp
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*RuntimeSorter).Sort(0xc0008980f0, 0x0, 0x0)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:320 +0x3bc
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc0002ba540, 0x25fa0c0, 0xc000567e60, 0xc000538280, 0xc0000a12c0, 0x1, 0x6, 0x0, 0x0)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:489 +0x1391
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc000538280, 0xc0000a12c0, 0x1, 0x6)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:161 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000538280, 0xc0000a1260, 0x6, 0x6, 0xc000538280, 0xc0000a1260)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00012b180, 0xc0003a2930, 0x12a05f200, 0xc0007f5f10)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00012b180, 0x248e758, 0x3597a80)
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
    /private/tmp/kubernetes-cli-20180928-18549-oxqbkv/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x150
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fixes a runtime error occuring when sorting the output of `kubectl get` with empty results
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks for the PR @mfpierre 
seems to me like get_test.go would need an update here.

/ok-to-test

**Comment by neolit123** [comment]
@kubernetes/sig-cli-bugs 
/priority important-soon

**Comment by mfpierre** [comment]
@neolit123 just added a unit test case with an empty list of objects

The test is crashing without the fix

**Comment by neolit123** [comment]
@mfpierre thanks for the update.

/ok-to-test

**Comment by mfpierre** [comment]
Looks like trailing some whitespaces caused issues

/retest

**Comment by mfpierre** [comment]
Hey @justinsb thanks for the review, do you think this bug fix can make it into 1.13?

**Comment by liggitt** [comment]
it's not a regression (bug [existed in 1.12](https://github.com/kubernetes/kubernetes/blob/release-1.12/pkg/kubectl/cmd/get/get.go#L320)), but the fix is contained, the risk is low, and I'd consider it a candidate for cherry-pick.

/milestone v1.13
/priority critical-urgent

**Pull request merged**
