### PR TITLE
Remove jobs from kubectl scale.

### PR DESCRIPTION
**Pull request by madhusudancs**
Job does not use Scale subresource and doesn't support kubectl the same way deployments/replica sets/replication controllers support. So removing it for now.

cc @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Tests failed.

**Comment by DirectXMan12** [comment]
Looks like `kubectl run --rm` calls `Reaper().Stop()` (in pkg/kubectl/stop.go), which in turn calls `ScalerFor` (in `pkg/kubectl/scale.go`), which is no longer defined on Jobs

**Comment by bgrant0607** [comment]
Perhaps @pwittrock could take this over?

**Comment by bgrant0607** [comment]
If the scale command actually works on Job currently, I'm inclined to just leave it as is and close this PR.

cc @soltysh

**Comment by soltysh** [comment]
@bgrant0607 scale works, it's responsible for changing parallelism parameter in job. I'd recommend leaving the current behavior as is. So +1 for your ide.

**Comment by erictune** [comment]
Agree we should leave as is.

**Pull request closed without merging**
