### PR TITLE
Fix golint failure in pkg/kubelet/dockershim/network/cni

### PR DESCRIPTION
**Pull request by shufanhao**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:
- pkg/kubelet/dockershim/network/cni/cni.go

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
None
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/lgtm

Thanks for this pr :) Lmk if you need any help signing the CLA.

**Comment by shufanhao** [comment]
> /ok-to-test
> /lgtm
> 
> Thanks for this pr :) Lmk if you need any help signing the CLA.

Hi Matt,
Thank for review my first pull request for k8s. I have created my personal Linux foundation ID, but doesn't receive email from HelloSign. And I create a issue is jira, link: https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-173. But doesn't receive response now. Is it a right direction for fix doesn't sign CLA issue ?

**Review by cmluciano — CHANGES_REQUESTED** [review]
This looks good but the verify tests indicate several other fixes that need to be added

```
Errors from golint:
pkg/kubelet/dockershim/network/cni/cni_test.go:127:123: exported func NewFakeHost returns unexported type *cni.fakeNetworkHost, which can be annoying to use
pkg/kubelet/dockershim/network/cni/cni_test.go:278:4: struct field IpRanges should be IPRanges
pkg/kubelet/dockershim/network/cni/cni_test.go:301:2: var expectedIpRange should be expectedIPRange

Please review the above warnings. You can test via "golint" and commit the result.
If the above warnings do not make sense, you can exempt this package from golint
checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
```

**Comment by shufanhao** [comment]
> This looks good but the verify tests indicate several other fixes that need to be add

Hi cmluciano 
These golint issue belong to package:  pkg/kubelet/dockershim/network/cni/testing, I doesn't remove it from hack/.golint_failures file, does that make sense send a isolated pull request for pkg/kubelet/dockershim/network/cni/testing. Because there is more changes for releated /cni/testing.

**Comment by cmluciano** [comment]
> This looks good but the verify tests indicate several other fixes that need to be add
> 
> Hi cmluciano
> These golint issue belong to package: pkg/kubelet/dockershim/network/cni/testing, I doesn't remove it from hack/.golint_failures file, does that make sense send a isolated pull request for pkg/kubelet/dockershim/network/cni/testing. Because there is more changes for releated /cni/testing.

Yes cni/testing can be a separate PR. The errors I posted are related to cni.go & cni_test.go being part of the cni package. cni/testing is a separate package called mock_cni.

**Comment by shufanhao** [comment]
> > This looks good but the verify tests indicate several other fixes that need to be add
> > Hi cmluciano
> > These golint issue belong to package: pkg/kubelet/dockershim/network/cni/testing, I doesn't remove it from hack/.golint_failures file, does that make sense send a isolated pull request for pkg/kubelet/dockershim/network/cni/testing. Because there is more changes for releated /cni/testing.
> 
> Yes cni/testing can be a separate PR. The errors I posted are related to cni.go & cni_test.go being part of the cni package. cni/testing is a separate package called mock_cni.

Got you point. Thanks for catching it. I updated pull request include cni_test.go fixing golint error.

**Comment by shufanhao** [comment]
> /ok-to-test
> /lgtm
> 
> Thanks for this pr :) Lmk if you need any help signing the CLA.

I have finish signing the CLA. Need you approve again. Thanks.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
@shufanhao can you rebase and repush? Thanks!

**Comment by shufanhao** [comment]
> @shufanhao can you rebase and repush? Thanks!

Have done it, could you review again. Thanks

**Comment by mattjmcnaughton** [comment]
/lgtm

adding label after rebase

**Pull request merged**
