### PR TITLE
Automated cherry pick of #93962: Allow 404 error on lb deletion in azure

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #93962 on release-1.19.

#93962: Allow 404 error on lb deletion in azure

```release-note
Fixed a regression in 1.18+ where loadbalancer deletion gets stuck because of missing resource group #75198
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure
cc @phiphi282

**Comment by phiphi282** [comment]
lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
