### PR TITLE
Add unit test case for Networkpolicy storage

### PR DESCRIPTION
**Pull request by lichuqiang**
**What this PR does / why we need it**:

add unit test for storage of resource Networkpolicy

### CODE REVIEW

**Comment by cmluciano** [comment]
@lichuqiang Was there a reason for closing this?

**Comment by lichuqiang** [comment]
@cmluciano I saw you refered issue #50604, seems that the version of resource neworking would be switched, so I thought the test case might need to be updated accordingly?

**Comment by cmluciano** [comment]
cc @danwinship

**Comment by sttts** [comment]
@liggitt approved?

**Comment by lichuqiang** [comment]
@liggitt Seems need your milestone label to get it merged. Thanks. :)

**Pull request merged**
