### PR TITLE
kubelet podresource: fix GetAllocatableResources metrics

### PR DESCRIPTION
**Pull request by moshe010**
The GetAllocatableResources increase twice the PodResourcesEndpointRequestsTotalCount This PR fix this.

Signed-off-by: Moshe Levi <moshele@nvidia.com>

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/lgtm
(just agreeing here, was already added)

**Comment by swatisehgal** [comment]
/lgtm

/assign @klueska 
for approval

**Pull request merged**
