### PR TITLE
Automated cherry pick of #112956: remove in-tree volume limits test now that CSIMigration is GA

### PR DESCRIPTION
**Pull request by amacaskill**
Cherry pick of #112956 on release-1.25.

#112956: remove in-tree volume limits test now that CSIMigration is GA

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

based on https://github.com/kubernetes/kubernetes/pull/112956#issuecomment-1275296836

**Comment by cici37** [comment]
/lgtm
@kubernetes/release-managers

**Comment by cici37** [comment]
From sig release: We are having a cherry pick deadline previous and it is still in effect now: https://groups.google.com/a/kubernetes.io/g/dev/c/P52OkdIA5jQ.

Thank you

**Comment by cici37** [comment]
I think this one is ready since we are done with patch releases. @Verolop  if you have time^^

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
