### PR TITLE
Add explicit start and end to JSON encoded test data for easier parsing

### PR DESCRIPTION
**Pull request by gmarek**
@davidopp @mikedanese @brendandburns - can one of you review this very small PR?

### CODE REVIEW

**Comment by ixdy** [comment]
This seems like a fair amount of additional log spam... do you have a link to before/after this change to demonstrate how it helps?

**Comment by gmarek** [comment]
2 lines per kind, i.e. up to 6 lines currently is a fair amount?

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot e2e test this

**Pull request merged**
