### PR TITLE
Fixed typo (should be 100 milli CPUs instead of 10)

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by k82cn** [comment]
@luksa , we had moved docs into [kubernetes/community](https://github.com/kubernetes/community/), please re-create this PR at  [kubernetes/communit](https://github.com/kubernetes/community/) for `contributors/design-proposals/resource-qos.md`.

**Comment by luksa** [comment]
In that case, how come the content is still here? Shouldn't it be replaced with a link to the new pages. There are links in the documentation that point to this page.

**Comment by k82cn** [comment]
Some contributor is working to move it, I'm not sure the progress :). please refer to #38581 as an example.

**Comment by luksa** [comment]
OK, cool. Closing this.

**Pull request closed without merging**
