### PR TITLE
Fix Comment for preserveUnknownFields for CustomResourceDefinition Spec

### PR DESCRIPTION
**Pull request by danielhelfand**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

The comment for the preserveUnknownFields points to a broken link. Would be helpful so users can find associated docs for the property.

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

Open to suggestions on whether the link itself can be updated to something else but submitting this with intent to preserve original docs used. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@liggitt any suggestion on a better link? (to fix the broken ones)

**Comment by liggitt** [comment]
maybe https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning ?

**Pull request closed without merging**
