### PR TITLE
Generate OpenAPI definition for inlined types

### PR DESCRIPTION
**Pull request by mbohlool**
Currently OpenAPI definition generator ignores any type's member with an empty json name tag. However, most (if not all) of these types also have "inline" json tag. That means we should inline their members into parent type's OpenAPI definition instead of ignoring them. But current implementation ignores them that resulted in many types missing common parameters such as "Name". It look something serious to me for OpenAPI spec and I suggest we merge and cherry-pick this into 1.5 release branch as soon as possible.

#39465

### CODE REVIEW

**Comment by mbohlool** [comment]
@k8s-robot test this issue IGNORE

**Comment by mbohlool** [comment]
@k8s-bot test this issue IGNORE

**Comment by mbohlool** [comment]
@k8s-bot test this issue #IGNORE

**Comment by lavalamp** [comment]
Yeah this looks important.

**Pull request merged**
