### PR TITLE
Allow for processing stale data in patch operation

### LINKED ISSUE #42644: Patch needs information from GuaranteedUpdate to determine liveness, causes TestPatch flakes
GuaranteedUpdate tries to update with cached data.  Patch needs to know whether its being called with live or stale data to determine the "base" level the patch was issued against.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #42644

@liggitt @deads2k

### CODE REVIEW

**Comment by wojtek-t** [comment]
Do we want this for 1.6?

**Comment by wojtek-t** [comment]
@liggitt - friendly ping

**Comment by wojtek-t** [comment]
@k8s-bot etcd3 test this, issue: #42724

**Comment by wojtek-t** [comment]
@k8s-bot gci gce e2e test this, issue: #42724

**Comment by wojtek-t** [comment]
@k8s-bot kops test this, issue: #42724

**Comment by wojtek-t** [comment]
@k8s-bot non-cri test this, issue: #42724

**Comment by wojtek-t** [comment]
@k8s-bot non-cri e2e test this, issue: #42724

**Comment by calebamiles** [comment]
Moved this issue into the 1.6 milestone.

**cc: @ethernetdan, @kubernetes/release-team**

**Comment by smarterclayton** [comment]
Hrm - I'm not sure how to feel about this.

**Comment by smarterclayton** [comment]
maybeStale isn't quite what I'd have called this.  The name of the variable needs to imply that your update will merge no matter what.

**Comment by wojtek-t** [comment]
> maybeStale isn't quite what I'd have called this. The name of the variable needs to imply that your update will merge no matter what.

I'm not sure I understand this. Currently it's something different (it carries the information that we used a basic object from cache instead of from etcd, and that the next retry may be incompatible with it).

To be honest, I'm not proud of this change, so if you have any suggestions how to make it more cleaner, I'm happy to fix it.

**Comment by wojtek-t** [comment]
@smarterclayton - ping; any suggestions how to make it better? do we want this for 1.6?

**Comment by ethernetdan** [comment]
@smarterclayton @wojtek-t could we come to a resolution on this Today? This is currently blocking 1.6

**Comment by liggitt** [comment]
I think we can slip this to 1.6.1 and see if we can find a cleaner way to fix this

**Comment by liggitt** [comment]
closing in preference to https://github.com/kubernetes/kubernetes/pull/63146

**Pull request closed without merging**
