### PR TITLE
update describe priorityclass format

### LINKED ISSUE #54608: kubectl describe priorityclass show the wrong format for value and GlobalDefault
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

**What happened**:

`kubectl describe priorityclass`  show the wrong format for value and GlobalDefault

```
name:           high-priority
Value:          %!s(int32=1000000)
GlobalDefault:  %!s(bool=false)
Description:    This priority class should be used for XYZ service pods only.
Annotations:    <none>
Events:         <none>
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

kubectl describe priorityclass show the wrong format for value and GlobalDefault

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54608 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
kindly ping @adohe @smarterclayton for approval

**Comment by wackxu** [comment]
kindly ping @adohe @dshulyak for approval

**Comment by wackxu** [comment]
@bsalamat I think it is a small bug about `priorityClass` and can you approval this? Thanks.

**Comment by bsalamat** [comment]
@wackxu This is outside of the scheduler. I don't have approval power for the changed files.

**Comment by adohe** [comment]
@wackxu sorry for my slowness. could you please fix the conflict at first?

**Comment by bsalamat** [comment]
@wackxu Could you please rebase this?

**Comment by bsalamat** [comment]
@wackxu Do you still want to get this in?
If so, please rebase and ping me. I will try to find someone to get this approved.

**Pull request closed without merging**
