### PR TITLE
keep etcd default value for snapshot count in kubernetes the same with etcd community

### LINKED ISSUE #100471: Kubeadm uses deprecated etcd default snapshot count
#### What would you like to be added:
Kubeadm v1.20 has snapshot-count as 10000 in etcd [configuration](https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/phases/etcd/local.go) as default:

This has been changed in etcd 3.1 and since then (current latest version being 3.4) [default](https://github.com/etcd-io/etcd/pull/7160) is 100,000 

#### Why is this needed:
Unless Kubernetes has any performance specific considerations to keep older etcd default value for snapshot count, we should use the one recommended by etcd community.

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
keep etcd default value for snapshot count in kubernetes the same with etcd community
#### Which issue(s) this PR fixes:

Fixes #100471

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@ptabor

**Comment by ptabor** [comment]
@gyuho 

I think etcd snapshots are relatively 'lightweight'. The huge (100k+) value was justified when storev2 has been dumped completely with every snapshot. Currently the snapshots are ~10KB of data, mostly membership information, so 10k is a reasonable number IMHO.  When storev2 is decomissioned (so etcd-3.6), I would consider checkpointing even more frequently (for faster recovery).

**Review by neolit123 — COMMENTED** [review]
thank you for the PR @lojies 

we are in code freeze for 1.21, so if we decide to do this change it can happen when 1.22 opens.

**Comment by neolit123** [comment]
@ptabor given the default of 10,000 and potential consequences of this change on the user side, do you think we should keep this value the way it is and not changing it at all or do you recommend we lower it (and to what value)?

**Comment by zorro786** [comment]
> I think etcd snapshots are relatively 'lightweight'. The huge (100k+) value was justified when storev2 has been dumped completely with every snapshot. Currently the snapshots are ~10KB of data, mostly membership information, so 10k is a reasonable number IMHO. When storev2 is decomissioned (so etcd-3.6), I would consider checkpointing even more frequently (for faster recovery).

With 100k value the snapshots are ~12KB in my cluster.

**Comment by ptabor** [comment]
I would keep this (10k) for now. 
FYI: https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#heading=h.8bdriypllkgh documents what the v2-store snapshot contains.

**Comment by neolit123** [comment]
thanks for the recommendation.

https://github.com/kubernetes/kubernetes/issues/100471#issuecomment-806972376
/close

**Pull request closed without merging**
