### PR TITLE
[KMS] move util from envelope to kms package

### PR DESCRIPTION
**Pull request by aramase**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- Move `envelope/util` to `kms/pkg/util`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aramase** [comment]
Had to run `hack/update-vendor.sh`. Should be good for `lgtm` now.

**Comment by dims** [comment]
/approve

(`/vendor` changes LGTM)

**Pull request merged**
