### PR TITLE
fix pkg/kubelet/container/helpers.go panic

### LINKED ISSUE #95552: pkg/kubelet/container/helpers.go:The function  shouldRecordEvent will panic when the value of input object is nil
**What happened**:
The status of container always stucks in a state of "ContainerCreating".

kubelet log:
E0331 14:06:04.044168   17044 runtime.go:82] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 537686 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x354c360, 0x72a1e40)
	/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x84
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:52 +0x7c
panic(0x354c360, 0x72a1e40)
	/opt/buildtools/godk_arm-0.9.30/goroot/go/src/runtime/panic.go:522 +0x1a0
k8s.io/kubernetes/pkg/kubelet/container.(*innerEventRecorder).shouldRecordEvent(...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/container/helpers.go:193
k8s.io/kubernetes/pkg/kubelet/container.(*innerEventRecorder).Eventf(0x40010508f0, 0x45437c0, 0x0, 0x3d925bb, 0x7, 0x3dc4ed6, 0x16, 0x3de9361, 0x1d, 0x4000c071c0, ...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/container/helpers.go:207 +0x5c
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0x4000c7afc0, 0x4004b5a800, 0x4004a9eea0, 0x73822d8, 0x0, 0x0, 0x4000b1e060, 0x40036daa40, 0x2, 0x2, ...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:719 +0x220c
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0x4000ca0000, 0x0, 0x4004b5a800, 0x2, 0x4004a9eea0, 0x0, 0x0, 0x0, 0x4004fe7938, 0x2e965b4)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1860 +0xc84
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0x4004fe7d50, 0x4000bf0200, 0x40039f5cd8, 0x40008d3c80, 0x400628e280)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:212 +0x3e0
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0x4000bf0200, 0x400535d0e0)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:222 +0xd4
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0x4000bf0200, 0x400535d0e0)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:261 +0x58
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:259 +0x4a0

**What you expected to happen**:
file:pkg/kubelet/container/helpers.go
The function shouldRecordEvent will panic when the value of object is nil and the type is non-nil. For details, see https://golang.org/doc/faq#nil_error. Instead, we can use Reflection to avoid this risk.

**How to reproduce it (as minimally and precisely as possible)**:
deploying a container

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15

### PR DESCRIPTION
**Pull request by lala123912**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix shouldRecordEvent panic

**Which issue(s) this PR fixes**:
Fixes #95552

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@lala123912 this fix https://github.com/kubernetes/kubernetes/pull/95662 might be better as it doesn't use `reflect` and introduces unit tests. Sorry I didn't realize you already had this PR out when submitted mine. Feel free to take code from mine or we can close this one. Either is fine with me, please let me know

**Comment by lala123912** [comment]
> @lala123912 this fix #95662 might be better as it doesn't use `reflect` and introduces unit tests. Sorry I didn't realize you already had this PR out when submitted mine. Feel free to take code from mine or we can close this one. Either is fine with me, please let me know

Yeah, this fix #95662 is better.I will close this one. @SergeyKanzhelev

**Pull request closed without merging**
