### PR TITLE
Staging the legacy Azure Cloud Provider

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Staging the Azure Cloud Provider as part of KEP [20190125-removing-in-tree-providers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md). Staging repo setup here https://github.com/kubernetes/legacy-cloud-providers

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Related: #75910 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@justaugustus is it decided that all cloud provider code will move to staging dir on v1.15?

**Comment by justaugustus** [comment]
@andyzhangx -- Check out the KEP for removing in-tree providers: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md#phase-1---moving-cloud-provider-code-to-staging

I don't believe it's a strict requirement for us to move in 1.15, but given deprecation is coming up in 1.18, I'd like us to be ahead of the curve here.

Tagging Andrew for his thoughts as well:
/assign @andrewsykim

**Comment by andrewsykim** [comment]
> I don't believe it's a strict requirement for us to move in 1.15, but given deprecation is coming up in 1.18, I'd like us to be ahead of the curve here.

Agreed, the move to staging doesn't change any behavior for the provider, only changes the location of the code. I would prefer it move to staging earlier rather than later.

**Comment by justaugustus** [comment]
(because I'm curious now:)
/unassign dep-approvers

**Comment by andrewsykim** [comment]
/lgtm 

Thanks @justaugustus

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Review by feiskyer — COMMENTED** [review]
lgtm

**Pull request merged**
