### PR TITLE
drop release-1.24 rules from publishing-bot

### PR DESCRIPTION
**Pull request by akhilerm**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove publishing-bot rules for inactive release-1.24 branch

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by akhilerm** [comment]
JFYI: We are working on adding a flag to update-rules command, so that the branch rules can be easily removed; just like how it is added. Ref: https://github.com/kubernetes/publishing-bot/issues/377

**Comment by akhilerm** [comment]
/hold cancel
As the jobs for 1.24 has also been removed.

**Pull request merged**
