### PR TITLE
kubectl support for ConfigMap

### PR DESCRIPTION
**Pull request by pmorie**
Depends on #6245

### CODE REVIEW

**Comment by pmorie** [comment]
Adding cla-human-approved tag for now since this PR currently contains commits by more than one primary author.  Will remove once #6245 is merged.

**Comment by pmorie** [comment]
@thockin PTAL, should be ready for review

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
unfortunately this seems to be blocked by #18907

**Comment by pmorie** [comment]
@thockin ready for review when you are

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
@thockin this one is ready for review when you're ready.  After my current in-flight PRs land, I'll move the resource over to the main API.

**Comment by thockin** [comment]
LGTM

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
Unit test failure was a flake

@k8s-bot unit test this

**Comment by pmorie** [comment]
:game_die: :game_die:

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
:tired_face: :snowflake: :game_die: :game_die:

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
For the record, I've verified the flake I seem to continually hit affects master as well.

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Pull request merged**
