### PR TITLE
Add secret protection

### LINKED ISSUE #101130: Protect secret from deletion while it is in-use
#### What would you like to be added:
Protect secret from deletion while it is in-use. 
It could be a similar feature to pv-protection/pvc-protection.

#### Why is this needed:
In the current k8s implementation, secret can be deleted while it is still used by other resources.
This will cause such issues that volume is failed to delete because secret needed for delete the volume is deleted before volume deletion, like [this issue](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/500).

/sig storage

### PR DESCRIPTION
**Pull request by mkimuram**
#### What type of PR is this?
This PR adds secret-protection for protecting secret from deletion while it is in-use.

/kind feature

#### What this PR does / why we need it:
In the current k8s implementation, secret can be deleted while it is still used by other resources.
This will cause such issues that volume is failed to delete because secret needed for delete the volume is deleted before volume deletion.

#### Which issue(s) this PR fixes:

Fixes #101130

#### Does this PR introduce a user-facing change?

```release-note
Deletion of a secret is blocked until all pods and PVs that are using the secret are deleted.   
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mkimuram** [comment]
This initial implementation works for below three cases:
1. Unused case: It should be deleted immediately.
2. Used by pod case: It should block deletion of secret until all pods using the secret are deleted.
3. Used by CSI PV case: It should block deletion of secret until all PVs using the secret are deleted.

We might need to discuss further on what other cases should be covered in issue/KEP, first. However, I'm sharing this working codes to make discussion easier.  

<details>

[Unused case]
It should be deleted immediately.
```
kubectl create secret generic test-secret --from-literal='username=my-app' --from-literal='password=39528$vdg7Jb'
kubectl get secret test-secret -o yaml
kubectl delete secret test-secret
```

[Used by pod case]
It should block deletion of secret until all pods using the secret are deleted.
```
kubectl create secret generic test-secret --from-literal='username=my-app' --from-literal='password=39528$vdg7Jb'
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/inject/secret-pod.yaml
kubectl describe pod secret-test-pod
kubectl delete secret test-secret
kubectl get secret test-secret -o yaml
kubectl delete pod secret-test-pod
kubectl get secret
```

[Used by CSI PV case]
It should block deletion of secret until all PVs using the secret are deleted.
(Below assumes that csi-hostpath driver has already been installed.)
```
kubectl create secret generic test-secret --from-literal='username=my-app' --from-literal='password=39528$vdg7Jb'

cat << 'EOF' | kubectl apply -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc-with-secret
provisioner: hostpath.csi.k8s.io
parameters:
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: test-secret
EOF

cat << 'EOF' | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
spec:
  storageClassName: csi-hostpath-sc-with-secret
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
EOF

kubectl get pv -o yaml | grep -A 5 " csi:"
    csi:
      driver: hostpath.csi.k8s.io
      nodePublishSecretRef:
        name: test-secret
        namespace: default
      volumeAttributes:

kubectl delete secret test-secret
kubectl get secret
kubectl delete pvc test-pv-claim
kubectl get secret
```

</details>

**Comment by mkimuram** [comment]
It is interesting to see `[sig-storage] Projected secret optional updates should be reflected in volume [NodeConformance] [Conformance]` test fails [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/storage/secrets_volume.go#L351). We will need to consider if secrets are actually used this way, and if so, we need to handle such use cases properly.  (Allow force delete or provide ways to opt-in/opt-out this feature for particular secrets with labels/annotations.)

**Comment by sftim** [comment]
If I have an immutable Secret and need to rotate this secret (eg because it has leaked), I think that it's important that I can force removal even if the Secret is in use.
Because of that likely need _somewhere_ and the urgency of carrying it out, I recommend explicitly documenting the process to forcibly remove such a secret well before this change reaches beta (it's not enough to generically document how to forcibly bypass finalizers and hope that readers can solve the puzzle).

**Comment by jsafrane** [comment]
I think this deserves a KEP, with all use cases outlined and discussed on higher level than code.

**Comment by mkimuram** [comment]
/remove-lifecycle rotten

This feature won't be implemented in-tree, but will be implemented as an external controller. However, keeping this open to mark that I'm still working on.

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Pull request closed without merging**
