### PR TITLE
Update etcd-client godep to 3.1.5

### PR DESCRIPTION
**Pull request by timothysc**
This transitively level sets the godeps to yank in the 3.1.5 client.  

Currently WIP, b/c it required some regen and I had some weird local permissions issue. 

xref: #41143

/cc @xiang90 @mml

### CODE REVIEW

**Comment by timothysc** [comment]
I'll revisit this PR once 1.7 opens up.

**Comment by dims** [comment]
@timothysc yay it's 1.7 time :)

**Comment by timothysc** [comment]
@hongchaodeng @xiang90 is there a targeted version for 1.7 release?  I suppose we should stick with the latest minor version + patch to match versioning scheme.  e.g.  3.1.X

**Comment by mml** [comment]
So how does client versioning relate to the version of the server code?  Newer clusters are now using 3.0.17, and some older ones still 2.2.1.  Some users may be doing something different.

But what are the compatibility rules?  Is there anything besides being less out-of-date (not to devalue that -- it's surely valuable) that this gets us?

**Comment by timothysc** [comment]
> But what are the compatibility rules? Is there anything besides being less out-of-date (not to devalue that -- it's surely valuable) that this gets us? 

Yes, a number of performance gains: https://coreos.com/blog/etcd-3-1-announcement.html

**Comment by mml** [comment]
If I read that right, those are advantages of running 3.1 server code.  But this just changes which client code we link in.  (Right?)

**Comment by timothysc** [comment]
We should do both, but yes.

**Comment by mkumatag** [comment]
This one is blocking even migrating k8s to golang1.8.. so we should move to to 3.1.x if we want to adopt golang1.8

**Comment by timothysc** [comment]
I'll update this now.

**Comment by timothysc** [comment]
There might be a weird issue on verify that I'll have to figure out.  There is a symlink that points to nothing, so it's either bazel or verify-godeps that is going to have to give.

**Comment by timothysc** [comment]
@wojtek-t or @mml poke poke... this is ready now.

**Comment by wojtek-t** [comment]
My fear is that as long as we won't solve all the problems with migration of existing clusters to etcd v3 (https://github.com/kubernetes/kubernetes/issues/43600 is the main example I have in my mind), we shouldn't make the 3.1.x an official version to avoid having yet another version to support.
That said, I think that those issues are fixable and we should be able to fix them in the next few weeks to have a clear path for all main setup systems for migration.

But I think that the path that we should recommend is:
- migrate to 3.0.x in v3 mode
- only then (say one release later) upgrade to 3.1.y


That said, I think I'm generally ok with submitting the PR, as we can theoretically live with 3.1.x client and 3.0.y server as this seems to work (which @timothysc pointed that this the configuration in which tests in this PR run).

But I would like to get some comments from @smarterclayton and @lavalamp before merging this one.

**Comment by wojtek-t** [comment]
For completeness, that what Xiang wrote on slack:
"@wojtekt 3.1 client can work with 3.0 server for most basic features (all k8s uses i believe). but high level primitives like lock might not work correctly."

**Comment by Random-Liu** [comment]
@timothysc @wojtek-t This PR is also needed for containerd CRI work because of the grpc version, see https://github.com/kubernetes/kubernetes/issues/43040.

Are we going to merge this anytime soon?

**Comment by timothysc** [comment]
Just let me know when there is a green light and I will rebase.

**Comment by smarterclayton** [comment]
I'm not terribly concerned with 3.1 client against 3.0 etcd as discussed,
so if this has overlap with CRI needs let's move forward.

On Mon, Apr 10, 2017 at 9:23 PM, Timothy St. Clair <notifications@github.com

**Comment by Random-Liu** [comment]
@timothysc @smarterclayton Thanks a lot! :)

**Comment by wojtek-t** [comment]
@lavalamp - any thoughts?

**Comment by wojtek-t** [comment]
BTW, I guess if we merged this within days, I hope that if there will be any problems with 3.0 server + 3.1 client, we will uncover them until 1.7 release.

**Comment by lavalamp** [comment]
This is just the client? I guess that LGTM

**Comment by wojtek-t** [comment]
Seems that noone really objects. 

/lgtm

**Comment by Random-Liu** [comment]
Thanks, everyone! You guys are so fast!

**Pull request merged**
