### PR TITLE
Rename docs snapshot to v1.0

### PR DESCRIPTION
**Pull request by thockin**
As per conversation with Richie

### CODE REVIEW

**Comment by thockin** [comment]
@krousey @RichieEscarez

**Comment by thockin** [comment]
Now with Richie's navigation stuff.

**Comment by thockin** [comment]
This needs to go in before we import new docs

**Comment by RichieEscarez** [comment]
LGTM (only my nav docs really affected, all others were a filename change (which also needs to get pushed into the script we are using to process and copy files from master))

**Comment by thockin** [comment]
rebased

**Comment by thockin** [comment]
This already aligns with Kris's script.

**Pull request merged**
