### PR TITLE
add descriptions to api/extensions/v1beta1/types.go files

### PR DESCRIPTION
**Pull request by wangyysde**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Ref #99675

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lauchokyip** [comment]
@wangyysde Have you run the `hack/update-openapi-spec.sh`? I don't see the ` api/openapi-spec/swagger.json` being updated

**Comment by wangyysde** [comment]
@lauchokyip Thank for your reponse. I have run the three scripts. But I have run git rebase because of hack/.descriptions_failures conflict when I commit the PR.  So I don't know  whether the three scripts must be run again?

**Comment by lauchokyip** [comment]
If I am not mistaken, git rebase will move your commits to the upstream/master HEAD, assuming you use `git rebase upsteam/master` so it wouldn't affect your commits. I had problem running the `hack/update-openapi-spec.sh` but running `make verify` works for me, so you can try that out

**Comment by wangyysde** [comment]
@lauchokyip Sorry, I was mistaken.  The script  had been run incorrectly  because that it outpus the message "etcd must be in your PATH"  when  I am  run it again.  As following direction,  I have run hack/install-etcd.sh script and I  have run the script  again. Could you check it again? Thanks!

**Comment by lauchokyip** [comment]
Looks good to me! You can now wait for others to trigger a test for you and see if anythign needs to be changed

**Comment by yuzhiquan** [comment]
PLZ update pr title, this title now  not clearly.

**Comment by wangyysde** [comment]
@yuzhiquan Thanks . I have update  pr title to add descriptions to api/extensions/v1beta1/types.go files.

**Comment by lauchokyip** [comment]
@wangyysde I think you added too many commits. Check out https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md to learn how to `git rebase`

**Comment by wangyysde** [comment]
@lauchokyip En ,very sorry. I was try to squash when I committed more than 8 times. So I try to run git rebase -i HEAD~3. But I don't know where is wrong , many commits has appeared. I will redo the whole working with following https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md

**Comment by lavalamp** [comment]
Git has a terrible UI, I'm sure this PR isn't in the state you intended. (I'd offer commands to fix it, but I am not quite sure what went wrong here, sorry)

/hold

**Comment by wangyysde** [comment]
@lavalamp Thanks.  I have redone the  working and opened a new PR for it . So I am closing this PR.

**Pull request closed without merging**
