### PR TITLE
Add compatibility fixtures for v1beta2 flowcontrol

### PR DESCRIPTION
**Pull request by liggitt**
This were accidentally omitted when the v1beta2 API was added. xref https://github.com/kubernetes/kubernetes/pull/112306#issuecomment-1248633841

```release-note
NONE
```

/cc @tkashem

### CODE REVIEW

**Comment by cici37** [comment]
Thank you :)

**Comment by tkashem** [comment]
/lgtm

Thanks @liggitt

**Comment by tkashem** [comment]
/hold 

in case you wanted API reviewers to review it, otherwise please feel free to cancel the hold

**Comment by liggitt** [comment]
/hold cancel

this is good to go

**Pull request merged**
