### PR TITLE
Fix staging godeps for k8s.io/metrics and k8s.io/kube-gen

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
#49095 introduced an issue with the formatting of the k8s.io/metrics staging godeps. This fixes that issue, and alters the script to prevent it from happening again.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks @cblecker

**Comment by cblecker** [comment]
/assign @lavalamp 
for approval

**Comment by cblecker** [comment]
@lavalamp @smarterclayton Are either of you around for `staging/` approval? This is a fix to Godeps to ensure the `hack/update-staging-godeps.sh` continues to pass on master.

**Comment by caesarxuchao** [comment]
```
W0722 00:51:36.335] diff: /go/src/k8s.io/kubernetes/staging/src/k8s.io/kube-gen/Godeps/Godeps.json: Not a directory
I0722 00:51:37.079] FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	233s
```

**Comment by cblecker** [comment]
Yeah, the same thing happened in https://github.com/kubernetes/kubernetes/pull/49114 for kube-gen. I'm going to fix that too

**Comment by cblecker** [comment]
@caesarxuchao I did the same change to kube-gen as I did to metrics. Hopefully this will pass now :)

**Comment by cblecker** [comment]
All tests are green again.

**Pull request merged**
