### PR TITLE
Adding Nodeport as a commented option in guestbook example so that ne…

### PR DESCRIPTION
**Pull request by peterlamar**
**What this PR does / why we need it**:

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
```

…w users

have a straight forward hello world experience when testing locally

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33116)

### CODE REVIEW

**Comment by PeterLamar** [comment]
I am the commit author as well and have signed the CLA. Not sure what to do here

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
@PeterLamar says "unrecognized author" on the commit, so the email address on the commit didn't appear to be set correctly. I did find you in the CLA DB, though.

**Comment by jeffmendoza** [comment]
@PeterLamar The commit is showing up in git as:

```
commit 0b715b1f425c4a6257d5996a2c1b90885698d9a2
Author: Peter Lamar <pete@Katelyns-MacBook-Pro.local>
Date:   Tue Sep 20 15:35:37 2016 -0400

    Adding Nodeport as a commented option in guestbook example so that new users
    have a straight forward hello world experience when testing locally
```

I imagine that is not the email you used to sign the CLA. Please set yout email in git (https://help.github.com/articles/setting-your-username-in-git/) and re-author your commit (`git commit --amend --reset-author`). Then force push your commit back to your master branch.

**Pull request closed without merging**
