### PR TITLE
Update `k8s.io/utils` to `ee6ede2d64ed`

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR updates the `k8s.io/utils` dependency to `ee6ede2d64ed` to adopt the following PR - https://github.com/kubernetes/utils/pull/252.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

/approve
/lgtm

/assign @liggitt 
(for root OWNERS approcal)

**Comment by liggitt** [comment]
thanks!

/approve

**Pull request merged**
