### PR TITLE
Automated cherry pick of #15983

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #15983 on release-1.1.

### CODE REVIEW

**Comment by yujuhong** [comment]
Pending the merge of #15983 and the manual check of e2e tests.

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
kubelet.log files from the jenkins run are good. The one failed test is known to be flaky recently. 
@k8s-bot test this please

**Comment by yujuhong** [comment]
Shouldn't we also check at kubelet initialization and fail if version is too old?

**Comment by yujuhong** [comment]
@dchen1107, ping for lgtm

**Pull request merged**
