### PR TITLE
Updating swagger-ui to the latest version

### PR DESCRIPTION
**Pull request by nikhiljindal**
As per the suggestion here: swagger-api/swagger-ui#1455.
But latest version hasnt made it any faster, as far as I can tell.

Verified that the UI works as before.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @vmarmol

**Comment by vmarmol** [comment]
LGTM, will need @bgrant0607's LGTM as well though

**Comment by nikhiljindal** [comment]
Assigning to @bgrant0607 for his LGTM

**Comment by bgrant0607** [comment]
Lgtm

**Pull request merged**
