### PR TITLE
fixed the bad url

### PR DESCRIPTION
**Pull request by lcfang**
**What this PR does / why we need it**:

fixed the bad url which had been moved to another place.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cblecker** [comment]
@lcfang This PR is against a release branch. We don't need to update historical links against release branches. The docs on master have been moved, and any website links on kubernetes.io can be updated at https://git.k8s.io/website.

/close

**Comment by lcfang** [comment]
Hi @cblecker , I know the docs on master have been moved, but there are always so many places using this url on master, so I find the source and fixed it. Do you think it is necessary  to fix them on master?

**Comment by cblecker** [comment]
@lcfang the file you modified (docs/design/service_accounts.md) no longer exists on master, so there is nothing to fix.

**Comment by lcfang** [comment]
hi @cblecker ， the file no longer exists on master, but there are always some typos using the bad link, eg. [https://github.com/kubernetes/kubernetes/blob/afbbd394c125ff443fb711741e6e06f996920ffd/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go#L139](https://github.com/kubernetes/kubernetes/blob/afbbd394c125ff443fb711741e6e06f996920ffd/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go#L139)

**Comment by cblecker** [comment]
Feel free to open a new PR updating that link to https://git.k8s.io/community/contributors/design-proposals/auth/service_accounts.md

**Pull request closed without merging**
