### PR TITLE
Fix hpa status current replicas

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

HPA shows wrong current replicas.
See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L615

currentReplicas is from scale.Spec.Replicas

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L1117:32

but currentReplicas is used for setting currentReplicas in this func

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by arjunrn** [comment]
@cwdsuzhou can you update the description of the PR with why showing `currentReplicas` is wrong and how `status.scale.Replicas` is more correct.

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou can you update the description of the PR with why showing `currentReplicas` is wrong and how `status.scale.Replicas` is more correct.

Updated

**Comment by cwdsuzhou** [comment]
ping @MaciekPytel for review

**Pull request closed without merging**
