### PR TITLE
use instance's Name to attach gce disk

### LINKED ISSUE #40427: failed to attach gce pd to a FDQN node
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.4

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Failed to attach a dynamic PV to the node
```text
21082 attacher.go:89] Error attaching PD "kubernetes-dynamic-pvc-
94d4fcd2-e281-11e6-820f-42010a80000b" to node
"ocp-node.foobar-openshift-sandbox.internal":
googleapi: Error 400: Invalid value
'ocp-node.foobar-openshift-sandbox.internal'.
Values must match the following regular expression:
'[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalidParameter
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

This is a known issue and fixed in #1424, but `AttachDisk` doesn't use canonical instance name [here](https://github.com/kubernetes/kubernetes/blob/v1.4.0/pkg/cloudprovider/providers/gce/gce.go#L2524)

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
fix #40427
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #40427

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rootfs** [comment]
@childsb @jsafrane @gnufied

**Comment by smarterclayton** [comment]
So we had the data, just weren't using it?

**Comment by rootfs** [comment]
@smarterclayton looks so

**Comment by gnufied** [comment]
lgtm

**Comment by gnufied** [comment]
Also `DetachDisk` seems to use correct name and somehow we didn't only use in AttachDisk.

**Review by childsb — APPROVED** [review]

**Comment by jdef** [comment]
lgtm

**Comment by jsafrane** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
