### PR TITLE
Update vendor package github.com/hashicorp/golang-lru

### PR DESCRIPTION
**Pull request by stafot**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
 Part of #69776 involves updating github.com/hashicorp/golang-lru

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
`NONE`

### CODE REVIEW

**Comment by dims** [comment]
@stafot we are now asking for a justification for updating the dependency, can you please see the list and see what will fit here?
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/godep.md#justifications-for-an-update

I've also updated #69776 with the same guidance

**Comment by stafot** [comment]
@dims Thanks, I reopened this PR based on [this](https://github.com/kubernetes/kubernetes/pull/70744#issuecomment-464949869) comment

**Comment by stafot** [comment]
@dims I am not sure that it applies in of the justifications reasons, though before this update kubernetes uses a `pre-release` version of  `hashicorp/golang-lru` while with this it will use the first and also latest available release. If this doesn't justify the upgrade, feel free to close the  PR.

**Comment by dims** [comment]
/ok-to-test
/release-note-none

@stafot thanks! let's see what others say first.

**Comment by dims** [comment]
/assign @thockin @cblecker 

Tim, Christoph, we were using a pre-release version of a library, this PR switches it to a released version. Is that acceptable?

**Comment by thockin** [comment]
This is still tagged as a pre-release (0.5.0).  Do we have evidence of changes that matter to us?  I'm inclined to allow this, since it's better than a random hash, but we should be pushing back on deps that are 0.x when we can.

**Comment by cblecker** [comment]
Test failure is legitimate. Please run `hack/update-staging-godeps.sh` as suggested.

**Comment by cblecker** [comment]
/lgtm
/approve

Yeah, I'm inclined to let this one in too, even if it's prerelease. I don't see any changes of concern.

**Pull request merged**
