### PR TITLE
Fixing kube-up for CVM masters.

### PR DESCRIPTION
**Pull request by maisem**
@roberthbailey @zmerlynn

### CODE REVIEW

**Comment by foxish** [comment]
Labelling this PR as size/S

**Comment by zmerlynn** [comment]
@foxish: Are you running an alternate copy of @k8s-merge-robot but not in dry-run mode?

**Comment by foxish** [comment]
Yes I was :( Sorry.

**Comment by zmerlynn** [comment]
@foxish: No worries, just confusing. :)

**Comment by roberthbailey** [comment]
lgtm. we may want to cherry pick into 1.3 as well so that we can run cvm masters in the 1.3 branch.

**Comment by maisem** [comment]
@roberthbailey - that would require to cherrypick #27961 before this.

**Comment by roberthbailey** [comment]
Good to know. We can cherry pick them as a batch with the script too.

**Pull request merged**
