### PR TITLE
[Pet Set] Refactor return []error to error

### LINKED ISSUE #31695: [Pet Set] Refactor return value from []error to error
I propose refactor return value from `[]error` to error [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet_set.go#L80), for the purpose of simplify code and format error output.

I think we can use `errors.NewAggregate(errorList)` to aggregate `[]error`.

Thanks!

### PR DESCRIPTION
**Pull request by m1093782566**
**Which issue this PR fixes** 

I propose refactor return value from `[]error` to error [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet_set.go#L80), for the purpose of simplify code and format error output.

I think we can use `errors.NewAggregate(errorList)` to aggregate `[]error`.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31698)

### CODE REVIEW

**Comment by m1093782566** [comment]
@bprashanth PTAL

Thanks!

**Comment by bprashanth** [comment]
LGTM, thanks for the cleanup

**Comment by m1093782566** [comment]
@bprashanth 

PR modified to paas CI, would you please review this again?

Thanks!

**Comment by bprashanth** [comment]
ok to test

**Comment by kevin-wangzefeng** [comment]
@k8s-bot test this, issue #GONE.

**Comment by m1093782566** [comment]
integration test failed.

```
k8s.io/kubernetes/test/integration/master TestServiceAlloc 0.51s
go test -v k8s.io/kubernetes/test/integration/master -run TestServiceAlloc$
master_test.go:468: unexpected sucessfrom junit_b7a7a4f8598eab8534d99b562bd139b5a5b100e5_20160905-145743.xml
```

It's about Create Service, but I am suspecting if my updates cause the error.

**Comment by m1093782566** [comment]
well, CI passed :)

**Pull request merged**
