### PR TITLE
Add a couple of benchmarks for the scheduler

### PR DESCRIPTION
**Pull request by brendandburns**
@davidopp @lavalamp @wojtek-t @ncdc

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by davidopp** [comment]
I'm not sure the nodes or pods are complicated enough to really stress the predicate or priority functions.

Related to that, I think you should use all of the defaultPredicates() and defaultPriorities() functions

**Comment by wojtek-t** [comment]
>
I'm not sure the nodes or pods are complicated enough to really stress the predicate or priority functions.

+100
I think that what we should do is take some real-ish pods and use them here.
When I was benchmarking changes e.g. in json marshaling/unmarshaling, the difference between gains in such pods and the real-ish ones (like this one: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod_example.json) was huge.

So we shouldn't create that artificial benchmarks - we should use more real data.


>
Related to that, I think you should use all of the defaultPredicates() and defaultPriorities() functions

+100
Definitely - this benchmark is too artificial.

**Comment by wojtek-t** [comment]
@brendandburns - one more thing.
As I wrote - in clusters with 500-nodes, we have scheduling throughput around 1pod/s.
Here you are simulating 1000-node clusters - what throughput does your benchmark produce? If it is much smaller, then it suggests that the benchmark is too artificial.

**Comment by ncdc** [comment]
@timothysc @jeremyeder @kubernetes/rh-cluster-infra @liggitt @smarterclayton

**Comment by timothysc** [comment]
+1 to @wojtek-t 's comment, this seems fictitious.

**Comment by wojtek-t** [comment]
I'm also working on PR exposing some more data from scheduler in our scalabily tests - will hopefully send something out tomorrow.

**Comment by lavalamp** [comment]
I think this benchmark is net gain, but:

* It doesn't use real pods
* It doesn't use the real scheduler setup

I have added some scheduler benchmarks to the integration test in the past. It's easier to get the real scheduler setup there. In fact you could just try running the benchmark I added there before and after your other change to see if it makes a difference.

(However, that benchmark doesn't pass @wojtek-t's criteria of generating realistic latency numbers, for reasons unclear to me.)

**Comment by HaiyangDING** [comment]
cc @HaiyangDING

**Comment by wojtek-t** [comment]
Yes - I obviously agree that having a benchmark is good (and we should have as many of them as we can). But they need to be realistic.

@lavalamp - I wasn't aware of your benchmark in integration tests - we should definitely look into it.

**Comment by davidopp** [comment]
@brendandburns Do you plan to work on addressing the comments, or should we close this PR and file an issue for someone to extend @lavalamp 's scheduler benchmark in integration tests, taking into account the feedback on this PR?

**Comment by xiang90** [comment]
@lavalamp @davidopp 

> I have added some scheduler benchmarks to the integration test in the past. It's easier to get the real scheduler setup there. In fact you could just try running the benchmark I added there before and after your other change to see if it makes a difference.

We are working on extending that benchmark. Should make some progress soon.

**Comment by xiang90** [comment]
@wojtek-t We are working on the integration test for scheduler.

> I wasn't aware of your benchmark in integration tests - we should definitely look into it.

We have extended the original test to something more useful.

We have made good progress here: https://github.com/coreos/kscale/tree/master/benchmark.

**Comment by wojtek-t** [comment]
@xiang90 - are you planning to upstream your changes to Kubernetes? this would be very useful for us.

**Comment by xiang90** [comment]
@wojtek-t Yes, for sure. We plan to get some meaningful results this week and send a proposal first.

**Comment by wojtek-t** [comment]
@xiang90 - awesome!

**Comment by hongchaodeng** [comment]
We submitted a proposal at #18091 
Let's move the discuss there. Thanks!

**Pull request closed without merging**
