### PR TITLE
fix bug of closing the same channel multiple times

### LINKED ISSUE #37444: Panic maybe happens, since close the same channel multiple times
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): close channel multiple times

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): master

**Environment**: None
- **Cloud provider or hardware configuration**: None
- **OS** (e.g. from /etc/os-release): None
- **Kernel** (e.g. `uname -a`): None
- **Install tools**: None
- **Others**: None

**What happened**:
 Panic maybe happens, since close the same channel multiple times.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

in the file pkg/proxy/config/config.go:
```
func (c *ServiceConfig) Channel(source string) chan ServiceUpdate {
	ch := c.mux.Channel(source)
	serviceCh := make(chan ServiceUpdate)
	go func() {
		for update := range serviceCh {
			ch <- update
		}
		close(ch)
	}()
	return serviceCh
}
```
The function Channel is allowed to be invoked many times with the same source,
for example,
	c.Channel("one")
	...
	c.Channel("one"),
then, it creates only one channel ch, that is, c.mux.sources["one"], while close(ch) will be invoked many times.

So I think it is a bug, although the close(ch) may not be run for ever.

I think discard the code "close(ch)" will be better.

### PR DESCRIPTION
**Pull request by xiaolou86**
**Which issue this PR fixes**: fixes #37444 

**Release note**:None

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37454)

### CODE REVIEW

**Comment by xiaolou86** [comment]
I signed it!

**Comment by xiaolou86** [comment]
I signed it!

**Comment by liggitt** [comment]
Doesn't this leave unclosed channels in place?

**Comment by xiaolou86** [comment]
yes, it does... But, the channel will keep alive because it is collecting the updates all the time.
Do you have any idea, thank you very much.

**Comment by xiaolou86** [comment]
I signed it!

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
I guess this is not a severe leak since the channel should never fail to read anyway, right?  @liggitt are you satisfied?

**Comment by dims** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
> I guess this is not a severe leak since the channel should never fail to read anyway, right? @liggitt are you satisfied?

Yeah, just wanted to check call sites to make sure channels weren't spawned per-request or anything. Should maybe update docs to indicate the channel is left open, but LGTM

**Comment by thockin** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
Does this need to be cherry-picked to 1.5? If so make sure to add `cherrypick-candidate` label

**Comment by saad-ali** [comment]
> Does this need to be cherry-picked to 1.5? If so make sure to add cherrypick-candidate label

Ping

**Comment by liggitt** [comment]
I don't think so. The bug was mostly theoretical based on existing usage as far as I can tell

**Comment by xiaolou86** [comment]
I don't know how to judge pick or not...please help

**Comment by saad-ali** [comment]
> I don't think so. The bug was mostly theoretical based on existing usage as far as I can tell

Ack. Will skip cherry-picking to 1.5 then

**Pull request merged**
