### PR TITLE
error word

### PR DESCRIPTION
**Pull request by StudyNick**
dummyController Struct comment "disonnected " is error word
WaitForCacheSync method comment "contoller" is error word

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by xiangpengzhao** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40055)*

**Review by xiangpengzhao — APPROVED** [review]

**Comment by smarterclayton** [comment]
You'll need to rebase

**Comment by StudyNick** [comment]
@smarterclayton rebase finish!

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by rmmh** [comment]
@k8s-bot test this

**Pull request merged**
