### PR TITLE
Enable restart statefulset clusters in e2e tests

### PR DESCRIPTION
**Pull request by janetkuo**
cc @bprashanth @erictune @foxish @kow3ns @kubernetes/sig-apps

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36910)

### CODE REVIEW

**Comment by bprashanth** [comment]
I think this is overall good, but I fear we will run into site specific failure modes (i.e mysql just doesn't handle restarts well, is that our problem?). That's why I wrote the test and disabled it initially. We can always turn it back off and revisit if it flakes a lot, though.

**Comment by janetkuo** [comment]
Updated: skip restarting mysql

**Comment by foxish** [comment]
I suggest we also remove `terminationGracePeriodSeconds: 0` from each of the examples. We are going to remove them from all PetSet/StatefulSet examples anyway.
That's one of the possible reasons why it might leave the disk in a state such that it can't come back up successfully.

I guess the restart test actually will end up testing the quality of our examples more than some property of StatefulSets, but that's a good thing as well IMO, and flakes should get fixed with the updates we make to examples with v1.5.

**Comment by janetkuo** [comment]
> I suggest we also remove terminationGracePeriodSeconds: 0 from each of the examples. 

Agree. Removed from all statefulset test manifests

**Comment by foxish** [comment]
/lgtm

Thanks!

**Pull request merged**
