### PR TITLE
fix csi ut print

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
fix csi ut print

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@jsafrane
PTAL

**Comment by rootfs** [comment]
cc @vladimirvivien

**Comment by zhangxiaoyu-zidif** [comment]
@vladimirvivien
PTAL

**Comment by vladimirvivien** [comment]
@zhangxiaoyu-zidif thank you. Reviewing.

**Comment by zhangxiaoyu-zidif** [comment]
@vladimirvivien is that okay， this PR just fix the print format.  =)

**Comment by vladimirvivien** [comment]
LGTM

**Comment by zhangxiaoyu-zidif** [comment]
@jsafrane 
could you label `lgtm`  and `approve no-issue`
thanks!

**Pull request merged**
