### PR TITLE
remove unused code of (pkg/controller)

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
/kind cleanup

remove unused code of (pkg/controller)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
looks fine to me.

/approve

**Comment by wgliang** [comment]
/cc @derekwaynecarr 
for lgtm

**Comment by wgliang** [comment]
/ping @derekwaynecarr 
for lgtm

**Comment by wgliang** [comment]
/ping @derekwaynecarr @deads2k 
for lgtm

**Comment by wgliang** [comment]
/ping @derekwaynecarr @deads2k
for lgtm

**Comment by wgliang** [comment]
/ping @derekwaynecarr @deads2k @mikedanese 
for lgtm

**Comment by deads2k** [comment]
This looks to a significant refactor of a storage unit testing.  

@kubernetes/sig-storage-pr-reviews

**Comment by msau42** [comment]
> This looks to a significant refactor of a storage unit testing.

These were changes I made to the tests in 1.12. Not sure why it's showing up as a diff here.  Maybe you need to rebase?
/assign

**Comment by wgliang** [comment]
@msau42 I've rebased it. But didn't see any difference.

**Comment by msau42** [comment]
Looks better now. The volume test changes are not showing up.  Will leave it to the others to review the other components.
/unassign

**Comment by jsafrane** [comment]
> This looks to a significant refactor of a storage unit testing.

There is no storage refactoring now, all changes are in pkg/controller.

**Pull request merged**
