### PR TITLE
Automated cherry pick of #112610: Fix flaky TestStalePodDisruption

### PR DESCRIPTION
**Pull request by alculquicondor**
Cherry pick of #112610 on release-1.25.

#112610: Fix flaky TestStalePodDisruption

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/hold
Just in case because there's 1.25 release in progress.

**Comment by alculquicondor** [comment]
/hold
it looks like the release is out

**Pull request merged**
