### PR TITLE
cloud-controller-manager: remove useless arguments of startControllers

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
remove useless arguments of `startControllers`

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
I assume these are here to be used by future controllers (I am surprised none of the existing ones log events - probably not good).

@cheftako should we nix them now?

**Comment by cheftako** [comment]
Actually I think this is our persistent problem of fixing things in one controller manager and not propagating the change. EventRecorder and KubeConfig have been folded into the CompletedConfig but we missed cleaning up the now unnecessary parameters. This change looks good to me.

**Review by cheftako — APPROVED** [review]
/lgtm

**Pull request merged**
