### PR TITLE
Clean up self-set node labels

### LINKED ISSUE #75050: Finish cleaning up self-set node labels
xref https://github.com/kubernetes/kubernetes/pull/74424

In 1.16:
* change the metadata-proxy addon to use `cloud.google.com/metadata-proxy-ready`
* change the kube-proxy addon to use `node.kubernetes.io/kube-proxy-ds-ready`
* change the masq-agent addon to use `node.kubernetes.io/masq-agent-ds-ready`
* stop setting `beta.kubernetes.io/fluentd-ds-ready`, `beta.kubernetes.io/kube-proxy-ds-ready`, and `beta.kubernetes.io/masq-agent-ds-ready` in kube-up `--node-labels`

### PR DESCRIPTION
**Pull request by paivagustavo**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:
Finishes  the clean up self-set kubelet labels under k8s.io prefixes:

This is related to https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#implementation-timeline
And is the follow up from #74424

**Which issue(s) this PR fixes**:

Fixes #75050

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
* Node labels `beta.kubernetes.io/metadata-proxy-ready`, `beta.kubernetes.io/metadata-proxy-ready` and `beta.kubernetes.io/kube-proxy-ds-ready` are no longer added on new nodes.
* ip-mask-agent addon starts to use the label `node.kubernetes.io/masq-agent-ds-ready` instead of `beta.kubernetes.io/masq-agent-ds-ready` as its node selector.
* kube-proxy addon starts to use the label `node.kubernetes.io/kube-proxy-ds-ready` instead of `beta.kubernetes.io/kube-proxy-ds-ready` as its node selector.
* metadata-proxy addon starts to use the label `cloud.google.com/metadata-proxy-ready` instead of `beta.kubernetes.io/metadata-proxy-ready` as its node selector.
* Kubelet removes the ability to set `kubernetes.io` or `k8s.io` labels via --node-labels other than the [specifically allowed labels/prefixes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal).
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

/assign @liggitt

**Comment by gaorong** [comment]
also need change at here:
https://github.com/kubernetes/kubernetes/blob/bc8ea43277d7ef9596c1d01712729f609e38df34/cmd/kubelet/app/options/options.go#L250-L252

**Comment by paivagustavo** [comment]
Hey @gaorong I've added the changes that you pointed out.

**Comment by rnsv** [comment]
With this change, I see that node-role.kubernetes.io is not allowed.  Is there an alternate label available to set the node role via --node-lables?

**Comment by den-is** [comment]
I second @rnsv qeustion?

What is the best practice to setup node-role `master` during the initial bootstrap (automatically) ?

**Comment by eranreshef** [comment]
I'm joining @rnsv and @den-is question. How can I set node-role during boot?

**Comment by rnsv** [comment]
Created a new issue #85073 .  This seems like an easy fix if we add kubernetes.io/role in https://github.com/kubernetes/kubernetes/blob/939e1e64881c0fc920b75c7489816fbf72806358/pkg/kubelet/apis/well_known_labels.go#L39-L52

Any thoughts?

**Pull request merged**
