### PR TITLE
Make flags accept - or _ between words

### PR DESCRIPTION
**Pull request by thockin**
Updated pflag

Did not convert non-pflag binaries.

Semi-automatic conversion, please audit for any I missed or got wrong

I am trying to push the flag-rewrite loop into pflag, if that works I can remove it here.

This should be STRICTLY COMPATIBLE.

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM but needs to be rebased

**Comment by thockin** [comment]
This is WIP until I get ACK or NAK on putting some support into pflag
itself.

@ghodss

On Fri, Apr 24, 2015 at 4:58 PM, David Oppenheimer <notifications@github.com

**Comment by ghodss** [comment]
Beautiful. :heart_eyes:

**Comment by pmorie** [comment]
--omg_ihate_this_situation

**Comment by thockin** [comment]
Upstream ACKed, merged.  If this is green, it should be good to go.

**Comment by thockin** [comment]
self-commit to get this off the books.  All new flags should use dashes.

**Pull request merged**
