### PR TITLE
add last applied annotation to rbac reconcile

### PR DESCRIPTION
**Pull request by xilabao**
Set the last applied configuration annotation for the default rbac if the default role/rolebinding is updated. It can allow user to get the old configuration when the apiserver is upgrade.
@deads2k @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
What issue is this resolving. I would not expect kubectl apply to be used with these objects

**Comment by xilabao** [comment]
@liggitt  I think there are three benefits.
1. we can know the differences between the old and new version.
2. if downgrade, we can recover the newer default roles/rolebindings.
3. people can recover the old configure if they changed the objects but forget to change `rbac.authorization.kubernetes.io/autoupdate`

**Comment by liggitt** [comment]
I don't think those are a good reason to add the annotation.

1. It only stores one version at a time, so after two upgrade restarts, one set of data would be lost. 

2. Downgrading won't remove permissions… the reconciliation only adds missing permissions. 

3. If they added new permissions, those would not be lost (see earlier comment about reconciliation only adding permissions).

**Comment by xilabao** [comment]
@liggitt thanks for your reply. 
about 1, I think it's just a remedial measure if upgrade. 
about 2, when downgrade. maybe some missing permission should not be added. 
about 3, I think we could let the user to decide which permission they want since the old version is work well.

**Comment by liggitt** [comment]
I think it is confusing to add the annotation to a resource that is not intended to be managed with `kubectl apply`, and inappropriate to do that from an automated reconciliation operation which is not actually applying a configuration for a user.

**Comment by xilabao** [comment]
oh... Could we use another annotation to active it or mention it in the document?  so the users can have the initiative.

**Comment by liggitt** [comment]
I don't think the apply tool is a good match for the resources managed by this reconcile function. If a user wants to use apply with these roles and rolebindings, they already can, but I don't want to encourage it.

**Comment by xilabao** [comment]
ok. Should we tell people the changes by reconcile? add log or event? or something?

**Comment by liggitt** [comment]
> ok. Should we tell people the changes by reconcile? add log or event? or save the patch in the annotation?

logging seems reasonable

**Pull request closed without merging**
