### PR TITLE
Add unit tests for  pkg/registry/authorization/util

### PR DESCRIPTION
**Pull request by shawnhanx**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add unit tests for  pkg/registry/authorization/util
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/triage accepted

**Comment by dims** [comment]
/assign @liggitt 

NOTE: the test case looks good to me!

**Pull request merged**
