### PR TITLE
There is no local etcd, removing 'etcdctl set'.

### PR DESCRIPTION
**Pull request by gosharplite**

### CODE REVIEW

**Comment by brendandburns** [comment]
@kelseyhightower thoughts?

**Comment by rjnagal** [comment]
@kelseyhightower can you take a look?

**Comment by erictune** [comment]
@AntonioMeireles can you take a look at this PR and say if it looks safe?

**Comment by erictune** [comment]
@pires any comment here?

**Comment by erictune** [comment]
@bussyjd this touches the same area as your #6890.  Want to comment on this PR?

**Comment by pires** [comment]
To me it feels like we should have kept the single `etcd` in the master node, where `apiserver` runs and not a cluster like @antoniomeireles implemented.

In this case, removing this line (or the entire entry is OK), because
```
flannel:
    interface: eth1
    etcd_endpoints: http://<master-private-ip>:4001
```

**Comment by bussyjd** [comment]
@erictune If a single master node is the way to go it then makes sense to get rid of this line IMO with @pires 's PR
I am sorry if I bring back an old discussion but running etcd only on the master feels like it might cause some issues in niche cases when the master is not available (flanneld nw conf update for example). It defeats the purpose of etcd's HA.
Now might be the right time to weight the pros and cons if it haven't been done before otherwise It's totally fine to discard https://github.com/GoogleCloudPlatform/kubernetes/issues/6555 and https://github.com/GoogleCloudPlatform/kubernetes/pull/6890 in favor of https://github.com/GoogleCloudPlatform/kubernetes/pull/6281

**Comment by pires** [comment]
@bussyjd @antoniomeireles was the one who brought `etcd` HA to light, since I was in favor of a simpler approach. People here will tell you `etcd` is just an implementation detail that may change in the future and have that said, I am to believe they don't actually care about `etcd` best-practices. And I agree with this idea. So, to me, if you're not happy with a single `etcd` node cluster, perhaps it's time to assemble it outside of Kubernetes?

Anyway, #6281 works for me.

**Comment by bussyjd** [comment]
@pires Thank you for the info.

> So, to me, if you're not happy with a single etcd node cluster, perhaps it's time to assemble it outside of Kubernetes?

Is that in any world a productive answer?

@erictune  It is now clear that case #6281 is the way to go.

**Comment by pires** [comment]
> Is that in any world a productive answer?

@bussyjd I'm sorry if it offended you in some way, but it's actually how I use it in production. Once again, `etcd` is just an implementation detail. How coupled do we want its high-availability to be to Kubernetes?

**Comment by AntonioMeireles** [comment]
[sorry lag, mutitasking too much]

several issues/angles at stake (and now we even have etcd2 to grasp as it is already in latest CoreOS alpha). 

- one approach we could use is the old one were the minions are absolutelly dumb and have no etcd (1, 2, whatever) of any kind, with everything pointing to master. with that approach one will always have to "cheat" one way or another and make sure that in no circunstance the nodes have the chance to *want*/need etcd before master is up. [this is easy to trigger specially in Vagrant with fast boxes/ssds and without `VAGRANT_NO_PARALLEL=true`. 
- another approach that @pires thinks is too much (its is, but handy for testing) is just have a local etcd cluster, spread among master and nodes.
- finally, the last approach is while having a single-node etcd-master running on master having on all the minions etcd in proxy/client mode pointing to master. this way and without further cheating even if they start well in advance the minions will wait orderly that etcd (and whatever deps on it) is up and ready in master. [this is what is being done in this [master](https://github.com/AntonioMeireles/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml)/[node](https://github.com/AntonioMeireles/kubernetes-vagrant-coreos-cluster/blob/master/node.yaml) and works afaict flawlessly.]  Also, from my understanding this approach is the recomended way by upstream of consuming etcd and should cover all use cases.

@pires et all - any objection for a PR that implements last option (IMHO the way to go), plus full etcd2 awareness, plus fixing [kubelet/kube-register interaction in 0.15.x](GoogleCloudPlatform/kubernetes#6851) ? (as afaik this 3 issues are the ones currently affecting this ?]

**Comment by pires** [comment]
@AntonioMeireles I'm OK with depending on `etcd2` (CoreOS 563.0.0) and follow the `proxy` approach.

**Comment by AntonioMeireles** [comment]
@pires can you please when you time hand pick the mods from my tree to yours (now that they are closer again :-) ) for "independent" testing :-) to see if this time we get rid of all corner cases :-). Anyway PR will available for discussion after my lunch :-)

**Comment by pires** [comment]
@AntonioMeireles working on the `proxy` thing right now.

**Comment by pires** [comment]
@AntonioMeireles done and can confirm it's working.

**Comment by AntonioMeireles** [comment]
@pires - thnks - working on PR.

**Comment by AntonioMeireles** [comment]
fellows,

submited GoogleCloudPlatform/kubernetes#6973. the discussion/review should probably jump to there :angel:

**Comment by brendandburns** [comment]
closing this as it appears to be obsoleted by #6973

**Pull request closed without merging**
