### PR TITLE
Automated cherry pick of #10488 on upstream release 0.21

### PR DESCRIPTION
**Pull request by thockin**
Integrate @justinsb changes for Salt+systemd on AWS

### CODE REVIEW

**Comment by thockin** [comment]
Hmm, I wonder what "add them to this pull request" means.  Maybe @justinsb needs to say "I'm okay with these commits being contributed to Google" ?

@derekwaynecarr too

**Comment by zmerlynn** [comment]
Merging. (Assuming consent for cherry-pick.)

**Comment by zmerlynn** [comment]
#10488.

**Comment by justinsb** [comment]
I've already signed the CLA, and consent to this also :-)  Thanks!

**Comment by justinsb** [comment]
This was in response to @thockin's request for me to do this BTW (as a non-Googler).  Some of the oddities may be because of that (CLA issue and I think we had a problem with shippable also?)

**Comment by zmerlynn** [comment]
@justinsb: Yup, don't worry. We're taking the CLA as assumed for cherry picks unless there was some major rework.

**Pull request merged**
