### PR TITLE
add /var/log/startupscript.log to core dump in gce

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by ixdy** [comment]
Are we only interested in this for the master?

**Comment by mikedanese** [comment]
@ixdy yes we are interested in this for the master and the nodes. Is this only run on the nodes?

**Comment by ixdy** [comment]
The change you made will only collect this log on the master. If you want it on the nodes, too, you'll need a similar change a few lines later. (We should probably unify these lists, since 90% of the logs are the same on both master and nodes...)

**Comment by ixdy** [comment]
#22230 will take care of this, I think

**Pull request closed without merging**
