### PR TITLE
provides a controller for dynamically filling parts of RequestHeaderConfig struct

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind feature

**What this PR does / why we need it**: provides a controller for dynamically filling parts of `RequestHeaderConfig` struct. It's used by an extension API server to authenticate requests coming from Kube API.  Before the values were only read at startup time. Now they will be dynamically filled from the config map when they have changed.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: I still need to wire the controller.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
code looks solid. Are you going to be stitching it in later?  You need to make sure that you pass a list/watch of that single configmap.  Not everything

/lgtm
/hold for confirmation that you will wire against a single item list/watch.

**Comment by p0lyn0mial** [comment]
> You need to make sure that you pass a list/watch of that single configmap. Not everything

Yes, I was planning to slightly refactor NewDynamicCAFromConfigMapController and factor out a single item list/watch.

**Comment by p0lyn0mial** [comment]
closing in favour of https://github.com/kubernetes/kubernetes/pull/90548

**Pull request closed without merging**
