### PR TITLE
Put initContainers to PodSpec for some statefulset examples.

### LINKED ISSUE #45405: Put init-containers to PodSpec
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
HEAD

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
The `init container` is [graduated to GA](https://github.com/kubernetes/kubernetes/pull/38382) , so some test YAML templates needs to be updated to not use `annotations`.

The following are the two places that needs update:
1. [cockroachdb](https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-statefulset.yaml)
2. [e2e statefulset test](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/statefulset)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:
Fixed https://github.com/kubernetes/kubernetes/issues/45405

The `init container` is [graduated to GA](https://github.com/kubernetes/kubernetes/pull/38382) , so some test YAML templates needs to be updated to not use `annotations`.

The following are the two places that needs update:
1. [cockroachdb](https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-statefulset.yaml)
2. [e2e statefulset test](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/statefulset)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing-misc will we run 1.7 Kube tests against a 1.5 server?  If so, this PR would cause the test to fail.

**Comment by rmmh** [comment]
@gyliu513 this seems to have broken the statefulset tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-statefulset/5669

**Comment by gyliu513** [comment]
I will take a look, thanks @rmmh

**Pull request merged**
