### PR TITLE
hollow-node.go:delete useless para. and import

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
hollow-node.go:delete useless para. and import

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
Needs a gofmt

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-unit test this

**Comment by wojtek-t** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
