### PR TITLE
Automated cherry pick of #60056: Make advanced audit output version configurable.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #60056 on release-1.10.

#60056: Make advanced audit output version configurable.

### CODE REVIEW

**Comment by loburm** [comment]
/assign @sttts @soltysh 
This change is prerequisite for #60432.

**Comment by sttts** [comment]
Is https://github.com/kubernetes/kubernetes/issues/60432 so important that it gives reason for a cherry-pick? It was original targetted at 1.11 with important-soon. Has that assessment changed https://github.com/kubernetes/kubernetes/issues/60432#issuecomment-374696555 ?

**Comment by loburm** [comment]
Yes I would like to have it in 1.10, as it creates a potential vector attack. For example attacker can put some random noise in annotations or labels to get a huge request body. In such case there is a great chance that logging of this event is going to fail.

**Comment by loburm** [comment]
Discussed with @sttts, we agreed that I'll prepare another cherrypick and remove dependency on this PR from it.

**Pull request closed without merging**
