### PR TITLE
Remove flocker volume plugins from k8s codebase

### PR DESCRIPTION
**Pull request by Jiawei0227**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Flocker storage plugin removed from k8s codebase.

Flocker, an early external storage plugin in k8s, has not been in maintenance and their business is down. As far as I know, the plugin is not being used anymore. This PR removes the whole flocker dependency and codebase from core k8s to reduce potential security risks and reduce maintenance work from the sig-storage community.

The flocker API, per k8s api policy, will not be removed. Whenever user tries to create PV using the inline flocker API, the following event will show in the pod:
```
 Warning  FailedMount  7m35s (x55 over 22m)  kubelet, kubernetes-minion-group-kq16  Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc kube-api-access-22hdk[]: failed to get Plugin from volumeSpec for volume "mypvc" err=no volume plugin matched
```

Context: https://techcrunch.com/2016/12/22/clusterhq-hits-the-deadpool/

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
action required: intree volume plugin flocker support is been completely removed from Kubernetes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig storage
/assign @msau42  @saad-ali @jsafrane @xing-yang

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
I think there's a bit more work to be done here: https://cs.k8s.io/?q=flocker&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

Should it also be removed from the API? cc @kubernetes/api-reviewers 

Generally +1 to removing old, unmaintained code!

/priority backlog
/triage accepted

**Comment by Jiawei0227** [comment]
> I think there's a bit more work to be done here:

I am assuming you are talking about the flocker API in the `api/core/v1/types.go`. I think per the k8s api policy, it is not allowed to remove v1 version API. So maybe we can only leave it there. As I mentioned in the PR descriptions, if the API is used, it will error out in the events.

**Comment by liggitt** [comment]
Yeah, dropping the API fields isn't possible in v1. It would behave like any other unsupported volume plug-in. A warning could be added to the API server to warn if the field is used.

**Comment by msau42** [comment]
I thought we had deprecated flocker but I couldn't find any release note about it in our changelogs. Although I do see it's marked as deprecated in the docs: https://kubernetes.io/docs/concepts/storage/volumes/#flocker.

Given that the flocker project has been inactive and unavailable [since 2017](https://github.com/ClusterHQ/flocker/issues/3017), I highly doubt there are any users today. But we may still want to give at least a cutesy notice.

**Comment by Jiawei0227** [comment]
> But we may still want to give at least a cutesy notice.

Is there any preferable way of doing it. I can certainly write an email to sig-storage. I think no one might be still using it and it is marked as deprecated in our public doc.

**Comment by Jiawei0227** [comment]
> A warning could be added to the API server to warn if the field is used.

@liggitt  Could you show me a pointer where to add the warning?

**Comment by liggitt** [comment]
> @liggitt Could you show me a pointer where to add the warning?

Currently, it's just the helper method `warning.AddWarning(ctx, "", "warning text")`

For something like this, we'd really want it to be handled consistently for all types that embed podspec. I'm working on that in https://github.com/kubernetes/kubernetes/pull/101688 as part of https://github.com/kubernetes/kubernetes/pull/100754. Once that's in, you'll have a clear spot to drop in an additional warning for flocker and scaleIO volume sources

**Comment by Jiawei0227** [comment]
> Once that's in, you'll have a clear spot to drop in an additional warning for flocker and scaleIO volume sources

Sounds great! Is there anything else in this PR and the scaleIO PR I need to change? Or should I wait for your change to be ready and then add warning logs and merge this one?

**Comment by liggitt** [comment]
I'll defer to the storage team on review of these PRs and ordering of the warning bits

**Comment by Jiawei0227** [comment]
/hold
Discussed offline with @msau42 , we think in this release we will create a deprecated notice first and then remove the code in next release.

**Comment by liggitt** [comment]
warnings can now be added about volume plugins at https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/warnings.go#L170-L175

**Comment by humblec** [comment]
The suggested plan looks good to me ! iic, the Mailing LIst notification is still pending.

**Comment by dims** [comment]
@Jiawei0227 do we want to do this for 1.22?

**Comment by Jiawei0227** [comment]
> @Jiawei0227 do we want to do this for 1.22?

We will not delete flocker as we have not send formal deprecation notice. So the plan is to deprecate it this release and remove it in a later release just to be safe.

/close

**Pull request closed without merging**
