### PR TITLE
fix typo in pkg/volume/util/operationexecutor/operation_generator.go

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Cleanup: fix typo.

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by Abirdcfly** [comment]
https://github.com/kubernetes/kubernetes/issues/110658 is opened for the storage-snapshot test failure....

**Comment by HecarimV** [comment]
Thanks, got it

**Comment by HecarimV** [comment]
> #110658 is opened for the storage-snapshot test failure....
thanks, got it

**Pull request closed without merging**
