### PR TITLE
Increase Dashboard UI version to v1.4.0-beta2

### PR DESCRIPTION
**Pull request by bryk**
This is our first beta for 1.4. We started synchronizing versions with
the core.

Release tag:
https://github.com/kubernetes/dashboard/releases/tag/v1.4.0-beta2

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31518)

### CODE REVIEW

**Comment by bryk** [comment]
@pwittrock Can you review this? How can I make sure to cherrypick this to 1.4 branch?

**Comment by bryk** [comment]
@janetkuo Can you review this?

**Comment by bryk** [comment]
ok to test

**Comment by foxish** [comment]
@bryk, it seems to me like this commit is already in release-1.4 at this point. So, I'm removing the cherrypick-candidate label. Please feel free to re-add the label if your intent was different.

**Pull request merged**
