### PR TITLE
kubeadm: Fix kube-proxy regression caused by #46372

### LINKED ISSUE #306: kube-proxy isn't run with `privileged: true` at HEAD
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): HEAD

https://github.com/kubernetes/kubernetes/issues/46372 introduced a regression; it moved `privileged: true` from Container to Pod level SecurityContext, but there isn't a `privileged` option on [PodSecurityContext](https://kubernetes.io/docs/api-reference/v1.6/#podsecuritycontext-v1-core).

kubeadm release blocker for v1.7, the proxy is broken

cc @cmluciano @timothysc @pipejakob

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Fixes: https://github.com/kubernetes/kubeadm/issues/306

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Required for kubeadm v1.7 to work

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @cmluciano

### CODE REVIEW

**Comment by cmluciano** [comment]
ouch, sorry about that

**Comment by luxas** [comment]
Don't worry, luckily I caught it when testing stuff out

**Comment by roberthbailey** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cmluciano** [comment]
failure might be awaiting https://github.com/kubernetes/kubernetes/pull/47610

**Comment by pipejakob** [comment]
/lgtm

Great catch!

**Comment by cmluciano** [comment]
/retest 

fluentd revert is merged

**Pull request merged**
