### PR TITLE
Second attempt at GCE tokens behavior to new format

### PR DESCRIPTION
**Pull request by ikehz**
Round two of #13449.

### CODE REVIEW

**Comment by ihmccreery** [comment]
@cjcullen I'm attempting to guard this on the environment variables passed in, so that we don't have the breakage in CI that we were expecting/got last night.

**Comment by cjcullen** [comment]
I don't think we need to version guard this. That introduces extra cruft that we will immediately want to take out. Let's just manage the coordination a little better :).

**Comment by cjcullen** [comment]
(And by let's, I mostly mean that I shouldn't have left the LGTM on overnight)

**Comment by ihmccreery** [comment]
@cjcullen Ack.

**Comment by cjcullen** [comment]
LGTM.

**Pull request merged**
