### PR TITLE
WIP: combine PV/PVC protection controllers

### PR DESCRIPTION
**Pull request by NickrenREN**
**What this PR does / why we need it**:
PV/PVC controllers share much similar code

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

/cc @pospispa @jsafrane @msau42 @liggitt

### CODE REVIEW

**Comment by pospispa** [comment]
@NickrenREN maybe you have noticed issue https://github.com/kubernetes/kubernetes/issues/60764
Shortly, the root-cause of the issue is that when the `StorageObjectInUseProtection` feature is enabled (it correctly adds finalizers to PVs and PVCs) and afterwards the feature is disabled the finalizers must be removed manually from PVs and PVCs otherwise the PVs and PVCs won't be removed from the system after they are deleted.

The issue https://github.com/kubernetes/kubernetes/issues/60764 was fixed by PR https://github.com/kubernetes/kubernetes/pull/61370 in K8s 1.9 by introducing finalizer removal only mode to `pv/pvc-protection-controllers` in case the feature is disabled.
I've opened PR https://github.com/kubernetes/kubernetes/pull/61324 to fix the root-cause in K8s 1.10 by always starting `pv/pvc-protection-controllers` even though the `StorageObjectInUseProtection` feature is disabled and if the feature is disabled the controllers only remove finalizers from PVs and PVCs, they do not add finalizers.

IMHO, it'd be nice in this PR to introduce the finalizer removal only mode into the `storageobjectinuse-protection-controller` when the `StorageObjectInUseProtection` feature is disabled.

I see that this PR is WIP. Please, let me know when it's ready for review.

**Comment by liggitt** [comment]
I'd actually recommend keeping the controllers separate... they work on different finalizers, and enforce a different object relationship.

**Comment by NickrenREN** [comment]
@pospispa  thanks for your notification, yeah, i will ping you when finished
@liggitt we process PVs and PVCs separately in the protection controller,so we can have different metrics for PV and PVC operations.  Since the existing two protection controllers share much similar code, i just want to merge them to simplify the code, just like `PV controller` does.

**Comment by liggitt** [comment]
> i just want to merge them to simplify the code, just like PV controller does.

I think the PV controller is an example of what we want to avoid. A simpler controller with one job is much easier to understand and maintain.

**Comment by NickrenREN** [comment]
>I think the PV controller is an example of what we want to avoid.

uh... If so, i am ok to keep them separate. btw: the existing storage related controllers seem to both deal with more than one job. `Attach/Detach controller`, `PV controller`

**Comment by jsafrane** [comment]
What I'd like to have is a package / interface that "protects" generic X when Y that refers to X exists. Caller would just add the necessary logic with X and Y e.g. `X=PVC` and `Y=pod  where pod.spec.volumes.* == X`.

Then we would instantiate this code in two controllers, but these controllers would be very simple, they would just send events to the right instance of the interface.

It's probably ok to have two controllers for PV and PVC protection as they are, it would pay off if we had more of them though.

**Pull request closed without merging**
