### PR TITLE
Automated cherry pick of #51039 #51224 #51230 #52057

### PR DESCRIPTION
**Pull request by enisoc**
Cherry pick of #51039 #51224 #51230 #52057 on release-1.7.

These are flakiness fixes that have helped on master.

#51039: StatefulSet: Deflake e2e "Saturate" phase.
#51224: StatefulSet: Deflake e2e "restart" phase.
#51230: StatefulSet: Deflake e2e `kubectl exec` commands.
#52057: StatefulSet: Deflake e2e RunHostCmd.

ref #48031

### CODE REVIEW

**Comment by wojtek-t** [comment]
Thanks @enisoc . LGTM.

/lgtm

**Comment by enisoc** [comment]
@wojtek-t It seems like federation e2e on release-1.7 has not passed in while:

https://k8s-testgrid.appspot.com/release-1.7-all#gce-federation-release-1-7&width=5

**Comment by wojtek-t** [comment]
@kubernetes/sig-federation-bugs - can you please take a look? ^^

**Comment by wojtek-t** [comment]
Since federation presubmit is broken, but this cherrypick is touching only test files and is supposed to deflake those, I'm kicking tests and will merge it manually.

/retest

**Comment by enisoc** [comment]
@wojtek-t Could you re-LGTM? I just pulled in a few lines from #52352 due to a flake seen on this PR.

**Comment by wojtek-t** [comment]
Strange - kops claims "no test failures".

I'm merging it manually to reduce flakiness.

**Pull request merged**
