### PR TITLE
kubectl: add regex syntax support for -o jsonpath

### LINKED ISSUE #72220: Regular expressions not working in json-path
This is a duplicate of #61406, which was closed because it was stale (I couldn't reopen it)

**What happened**:
Trying to use the following json-path expression:
`kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^test$/)].metadata.name}'`
resulted in the following error:
`error: error parsing jsonpath {.items[?(@.metadata.name=~/^test$/)].metadata.name}, unrecognized character in action: U+007E '~'`

**What you expected to happen**:
Getting the list of secret names that match the regular expression.
**How to reproduce it (as minimally and precisely as possible)**:
`kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^default-/)]}'`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- Cloud provider or hardware configuration: Dell PC
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): Linux pwt-test-cluster-master 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind feature

### PR DESCRIPTION
**Pull request by Einsfier**
**What type of PR is this?**
/kind feature
/sig cli

**What this PR does / why we need it**:
- Enables regular expression syntax in `kubectl -o jsonpath`

**Which issue(s) this PR fixes**:
Fixes #72220

**Special notes for your reviewer**:
@liggitt leave a comment in #72220 saying that jsonpath evaluator is also used in server side. Changing may lead to DOS of apiserver.
What does it mean? Catastrophic backtracking? or Is  `--server-print` using jsonpath evaluator?
I would be happy to fix associated issues if someone could explain this.

**Does this PR introduce a user-facing change?**:

```release-note
Added regular expression syntax support for command `kubectl -o jsonpath`

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[Usage]: https://kubernetes.io/docs/reference/kubectl/jsonpath/
```
Docs for `kubectl` jsonpath section should add an example
`kubectl get pods -A -o jsonpath='{.items[?(@.metadata.name=~".*containThis.*")].metadata.name}`
Simply quota the regex with a pair of `"`
For full regex syntax support, refer [https://golang.org/pkg/regexp](https://golang.org/pkg/regexp)

### CODE REVIEW

**Comment by povsister** [comment]
CLA signature updated

**Comment by povsister** [comment]
Remove `sliceKind` to avoid breaking exist comparison error handle logic.

**Comment by liggitt** [comment]
/hold

until question about the standard for jsonpath regex support is answered in https://github.com/kubernetes/kubernetes/issues/72220#issuecomment-624662079

**Comment by povsister** [comment]
/close
See https://github.com/kubernetes/enhancements/pull/1887

**Pull request closed without merging**
