### PR TITLE
Promote TokenReview to v1

### PR DESCRIPTION
**Pull request by liggitt**
Peer to https://github.com/kubernetes/kubernetes/pull/40709

We have multiple features that depend on this API:

- [webhook authentication](https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication)
- [kubelet delegated authentication](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication)
- add-on API server delegated authentication

The API has been in use since 1.3 in beta status (v1beta1) with negligible changes:
- Added a status field for reporting errors evaluating the token

This PR promotes the existing v1beta1 API to v1 with no changes

Because the API does not persist data (it is a query/response-style API), there are no data migration concerns.

This positions us to promote the features that depend on this API to stable in 1.7

cc @kubernetes/sig-auth-api-reviews @kubernetes/sig-auth-misc

```release-note
The authentication.k8s.io API group was promoted to v1
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-api-reviews @kubernetes/sig-auth-misc @cjcullen @deads2k

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
@kubernetes/api-approvers for approval

**Comment by cjcullen** [comment]
Not sure if this needs to be hashed out in this PR, but we were looking at passing through additional headers through the TokenReviewSpec in GKE. It feels wrong and gross, but I'm not convinced there's a nicer way. I talked it through w/ @liggitt earlier today and he told me to bring it up here.

We have a temporary role-grant "token"-ish type thing that we'd like to get passed through to our webhook authorizer, which gets passed in as a "x-goog-iam-authorization-token" header in the request.

Our initial thought was we could extend TokenReview to take an Extra as an input, and then plumb it into the User object (either transparently or with some processing done in the token webhook). Then the authorizer would see the Extra in the SubjectAccessReview, and could use it to make the correct authz decision. This could be done with some kind of `--authentication-webhook-extra-headers` flag (i.e. we would pass `--authentication-webhook-extra-headers="x-goog-iam-authorization-token"` to the apiserver).

Another option is to cut out the authn middleman and pass some headers as "extra" Extra to the SubjectAccessReview (w/ a similar `--authorization-webhook-extra-headers`). I figured the authentication option might be more generic, but I'd love to hear if anybody else would be interested in these.

+@alexblyzn who was looking into this.

**Comment by cjcullen** [comment]
But I don't think my concerns block this from going to v1. We should be able to do what I want (if we decide it's the right thing to do) without breaking compatibility.

**Comment by deads2k** [comment]
I can sort of understand wanting addition information the `TokenReview.Spec` field (I don't know that I'm fully sold, but as you noted, it could be a follow-on).  But the `TokenReview` can return an `Extra` for the specified user that is already provided to the authorization webhook.

**Comment by smarterclayton** [comment]
API looks ok.  If there are no further comments from SIG members or others on this thread this is approved and can merge as an API change.

**Comment by liggitt** [comment]
hearing none, tagging

**Pull request merged**
