### PR TITLE
[docs] Fix: Some grammatical mistakes in documentation

### LINKED ISSUE #112125: some grammatical mistakes in README.md file
### What happened?

I found some grammatical mistakes 
In place of : 
``` Kubernetes, also known as K8s, is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for deployment, maintenance, and scaling of applications. ```

```To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported. ```

### What did you expect to happen?

It should be : 

``` Kubernetes, also known as K8s, is an open-source system for managing containerized applications across multiple hosts. It provides basic mechanisms for the deployment, maintenance, and scaling of applications. ```

``` To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries are not supported. ```

### How can we reproduce it (as minimally and precisely as possible)?

just by browsing the README.md file 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

``` 
Kubernetes v1.25.0
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by vickyaryan7**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
It contains some grammatical errors fix

#### Which issue(s) this PR fixes:

Fixes #112125

#### Does this PR introduce a user-facing change?

```release-note
   NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pwnb0y** [comment]
git rebase

**Review by hwdef — COMMENTED** [review]
please squash your commits

**Comment by pwnb0y** [comment]
ok sure

**Comment by pwnb0y** [comment]
hey, @hwdef I squashed my commits review it again, please. :

**Review by hwdef — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
