### PR TITLE
Re-enable PATCH integration test for v1beta3

### PR DESCRIPTION
**Pull request by ghodss**
Needed to be disabled to fix #6431, but is now fixed and re-enabled.

@bgrant0607

### CODE REVIEW

**Comment by ghodss** [comment]
Travis v1beta3 failed due to #6045.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Restarted tests.

**Comment by bgrant0607** [comment]
Travis passed. v1beta3 on shippable passed, and v1beta1 failed for an unrelated reason. Merging.

**Pull request merged**
