### PR TITLE
Automated cherry pick of #45055

### PR DESCRIPTION
**Pull request by nicksardo**
Cherry pick of #45055 on release-1.5.

#45055: Bump GLBC version to 0.9.3

**Release note**:
```release-note
Bump GLBC version to 0.9.3
```

### CODE REVIEW

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
@mwielgus Thanks. This PR is for the 1.5 branch, but you set milestone 1.6. See #45068 for 1.6

**Comment by mwielgus** [comment]
@nicksardo Yeah, thanks for the heads up. Label reapplied.

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Pull request merged**
