### PR TITLE
Promote ShareProcessNamespace to beta

### PR DESCRIPTION
**Pull request by verb**
**What this PR does / why we need it**: The ability to configure PID namespace sharing per-pod was added as an alpha feature in 1.10. This promotes the feature to beta and makes the feature available by default.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
WIP #1615

**Special notes for your reviewer**:
/assign @yujuhong 

**Release note**:

```release-note
The PodShareProcessNamespace feature to configure PID namespace sharing within a pod has been promoted to beta.
```

### CODE REVIEW

**Comment by yujuhong** [comment]
/lgtm
/retest

cc @kubernetes/sig-node-pr-reviews

**Comment by yujuhong** [comment]
@verb the code should be removed in `DropDisabledAlphaFields` as well.

**Comment by yujuhong** [comment]
Otherwise, lgtm.

**Comment by verb** [comment]
@yujuhong sure thing. I removed the code from DropDisabledAlphaFields and left the check in validation.

**Review by yastij — APPROVED** [review]
/lgtm

**Comment by yastij** [comment]
/hold

Can @kubernetes/api-approvers take a look as we are moving sharedPID to beta ?

**Comment by tallclair** [comment]
> This promotes the feature to beta and enables it by default.

To clarify, this enables _the feature to be used_ by default, it doesn't actually default `ShareProcessNamespace` to true. Right?

**Comment by verb** [comment]
@tallclair Correct. The pod default is unchanged. If `ShareProcessNamespace` is not specified in pod config, isolated process namespaces are still used. This PR makes the feature available unless disabled with `--feature-gate=PodShareProcessNamespace=false`.

Sorry for the confusing wording, I will update the description.

**Comment by verb** [comment]
@liggitt @smarterclayton commented on this in alpha. Can one of you review this for beta?

**Comment by liggitt** [comment]
> @liggitt @smarterclayton commented on this in alpha. Can one of you review this for beta?

I don't have any objections, but don't have a good sense for what feedback we got on this. Will defer to sig-node

**Comment by verb** [comment]
@liggitt deferred to sig-node for api-approvers. Since @dchen1107 gave approval for sig-node I'll go ahead and remove the hold.

/hold cancel

**Pull request merged**
