### PR TITLE
fix azure disk attach failure for disk size bigger than 4TB

### LINKED ISSUE #95465: azure disk attach failure for disk size bigger than 4TB
**What happened**:
there is a disk resize scenario:
In the beginning, it’s 3TiB with cachingMode=ReadOnly, and then disk detached, resized to 4TiB, then user find they could not attach that disk back to any agent node, I think that’s a bug we need to fix.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/assign
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix azure disk attach failure for disk size bigger than 4TB

there is a disk resize scenario:
In the beginning, it’s 3TiB with cachingMode=ReadOnly, and then disk detached, resized to 4TiB, then user find they could not attach that disk back to any agent node, I think that’s a bug we need to fix.

**Which issue(s) this PR fixes**:

Fixes #95465

**Special notes for your reviewer**:
 - debugging logs: 
https://prow.k8s.io/log?container=test&id=1314821802324660224&job=pull-kubernetes-e2e-azure-disk

```
W1010 07:40:37.935223       1 azure_controller_common.go:164] size of disk(/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cfbab79b-0ac5-11eb-afd5-8e94ec80c49c/providers/Microsoft.Compute/disks/kubetest-cfbab79b-0ac5-11eb-afd5-8-pvc-45c22e79-6816-4777-b16d-9a246ae86f52) is 10GB
W1010 07:40:37.935244       1 azure_controller_common.go:169] size of disk(/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cfbab79b-0ac5-11eb-afd5-8e94ec80c49c/providers/Microsoft.Compute/disks/kubetest-cfbab79b-0ac5-11eb-afd5-8-pvc-45c22e79-6816-4777-b16d-9a246ae86f52) is 10GB, bigger than limit(6GB), set as None by default
```

**Does this PR introduce a user-facing change?**:

```release-note
fix azure disk attach failure for disk size bigger than 4TB
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
fix azure disk attach failure for disk size bigger than 4TB
```

/kind bug
/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

/hold a while for tests run

**Comment by andyzhangx** [comment]
this issue is fixed in 1.18.11, 1.19.4, 1.20.0+

**Pull request merged**
