### PR TITLE
make use of simple dynamic client instead of deprecated client pool

### LINKED ISSUE #63182: We should use simple dynamic client everywhere
As #62913 introduced a simple dynamic client, which is easy to use. And in some test, the old ClientPool is still used, So we should change all to the simple one ASAP.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

Use simple dynamic client through all integration test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63182

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Lgtm. Please squash.

**Comment by hzxuzhonghu** [comment]
/assign sttts
squashed

**Comment by hzxuzhonghu** [comment]
fixed a bug in `UpdateStatus`, without encode.
 I got a ` unable to update status: "mygroup.example.com/v1beta1" is not suitable for converting to ""` error if use this instead of `Update`

Also decode is necessary, otherwise a  panic
```
panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured [recovered]
        panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured

goroutine 86 [running]:
testing.tRunner.func1(0xc4200262d0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x16c4f40, 0xc4209034c0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic.(*dynamicResourceClient).UpdateStatus(0xc420abb740, 0xc420970578, 0x1a66738, 0xc42066bf58, 0x2)
        /mnt/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/simple.go:169 +0x39b
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration.TestStatusSubresource(0xc4200262d0)
        /mnt/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration/subresources_test.go:148 +0xdac
testing.tRunner(0xc4200262d0, 0x199f000)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration        1.972s

```

**Pull request merged**
