### PR TITLE
 Update bazelbuild/rules_go, kubernetes/repo-infra, and gazelle dependencies

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: updates our bazelbuild/rules_go dependency in order to bump everything to go1.9.4. I'm separating this effort into two separate PRs, since updating rules_go requires a large cleanup, removing an attribute from most build rules.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Comment by mikedanese** [comment]
:( how many times are we gonna add and remove fields form go_* rules

**Comment by cblecker** [comment]
@ixdy needs rebase

**Comment by ixdy** [comment]
@cblecker of course it does.
@mikedanese I hope this the last one (he says again).

**Comment by cblecker** [comment]
/lgtm
/assign @thockin @brendandburns 
either of you around for an approve?

**Pull request merged**
