### PR TITLE
Fix killing child sudo process in e2e_node tests

### LINKED ISSUE #29211: e2e_node tests leak kube-apiserver processes
The code in #26735 doesn't work for me: `sudo` does not pass on SIGTERM when the caller is in the same process group.

Then the `kill -KILL` knocks out the `sudo` process without giving it a chance to kill its child.

The `Pdeathsig` bit doesn't help: either the `sudo` process has already been killed as above, or it gets killed now with SIGKILL; either way the `kube-apiserver` process is still running.

Oddly, it does work about one time in ten.  I have no explanation for that.

I am running from the command-line like this: `make test-e2e-node FOCUS=Kubelet`, on
4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

CC @timstclair

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #29211.

The context is we are trying to kill a process started as `sudo kube-apiserver`, but `sudo` ignores signals from the same process group. Applying `Setpgid` means the `sudo kill` process won't be in the same process group, so will not fall foul of this nifty feature.

I also took the liberty of removing some code setting `Pdeathsig` because it claims to be doing something  in the same area, but actually it doesn't do that at all.  The setting is applied to the forked process, i.e. `sudo`, and it means the `sudo` will get killed if we (`e2e_node.test`) die.  This (a) isn't what the comment says and (b) doesn't help because sending SIGKILL to the sudo process leaves sudo's child alive.

I didn't use the "hack for linux-only" approach because I think `Setpgid` is available on all platforms that `e2e_node` builds on.

### CODE REVIEW

**Comment by timstclair** [comment]
ok to test

**Comment by timstclair** [comment]
LGTM

**Comment by timstclair** [comment]
@k8s-bot e2e test this. Issue https://github.com/kubernetes/kubernetes/issues/28641

**Comment by timstclair** [comment]
@k8s-bot e2e test this issue: #28641

**Comment by bboreham** [comment]
Looks like the Jenkins test failed trying to check out upstream changes.  Please advise what I can do to move this along.

**Comment by timstclair** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/28021

**Comment by lavalamp** [comment]
This broke the build. Reverting.

**Comment by lavalamp** [comment]
Looks like @fejta beat me to it.

**Comment by bboreham** [comment]
Per Slack discussion I'm submitting a PR to fix.

**Comment by bboreham** [comment]
Nope, too late.

**Pull request merged**
