### PR TITLE
Manual cherry pick of #103318: Bump SMD to v4.1.2 to pick up #102749 fix

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick of #103318 on release-1.21.

Bump SMD to v4.1.2 to pick up #102749 fix

Note that on the main branch the version bump was v4.1.1 to v4.1.2, but on this branch it is v4.1.0 to v4.1.2.

Changes from v4.1.0 and v4.1.2: https://github.com/kubernetes-sigs/structured-merge-diff/compare/v4.1.0..v4.1.2

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

PR created by:

```sh
hack/pin-dependency.sh sigs.k8s.io/structured-merge-diff/v4 v4.1.2
hack/update-vendor.sh
```

```release-note
Fix performance regression in 1.21 for update and apply operations on large CRDs.
```

### CODE REVIEW

**Comment by liggitt** [comment]
yeah, hack/update-internal-modules.sh

**Comment by liggitt** [comment]
> Note that on the main branch the version bump was v4.1.1 to v4.1.2, but on this branch it is v4.1.0 to v4.1.2.

are those extra changes relevant to 1.21 usage? are there any associated risks?

**Comment by liggitt** [comment]
dependency update mechanics lgtm, modulo internal-modules verify fix. would like an ack on the increased delta from a structured-merge-diff-conversant reviewer

**Comment by jpbetz** [comment]
> > Note that on the main branch the version bump was v4.1.1 to v4.1.2, but on this branch it is v4.1.0 to v4.1.2.
> 
> are those extra changes relevant to 1.21 usage? are there any associated risks?

Yes, but they're safe. https://github.com/kubernetes-sigs/structured-merge-diff/pull/192 is the main change in v4.1.1, which disables code (so safe from a performance perspective). The code was for a edge case we found to be problematic. It's REALLY unlikely this will impact anyone, and SSA is still beta in 1.21.

**Comment by jpbetz** [comment]
Ran `./hack/update-internal-modules.sh`

**Comment by liggitt** [comment]
/approve 
for dep bump

**Pull request merged**
