### PR TITLE
Fixed inaccurate comments for Secret and ConfigMap

### LINKED ISSUE #42203: API Comments for ConfigMap and Secret keys is wrong
Comment says `must be a valid DNS_SUBDOMAIN` but the regex is `[-._a-zA-Z0-9]+`

This is a trivial comments-only change that will cause some regenerated docs.  Great contrib opportunity for someone who has time and wants to see how this area works.

### PR DESCRIPTION
**Pull request by chupman**
**What this PR does / why we need it**:
Updates the comments for ConfigMap and Secret in types.go to correspond to the regex used in validation.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #42203
**Special notes for your reviewer**:

**Release note**:

```release-note 
None
```

### CODE REVIEW

**Review by cblecker — CHANGES_REQUESTED** [review]
Hi @chupman --
The comment changes here look great, but there are some scripts that need to be run to ensure that these types are then picked up and put in all the required generated docs.

If you could run these from the root of the repo and commit the docs they generate, that would be fantastic:
```
hack/update-generated-protobuf.sh
hack/update-generated-docs.sh
hack/update-generated-swagger-docs.sh
hack/update-swagger-spec.sh
hack/update-openapi-spec.sh
hack/update-api-reference-docs.sh
hack/update-federation-openapi-spec.sh
```

**Comment by chupman** [comment]
I ran into an error running hack/update-generated-docs.sh. After I hit the issue on my mac I spun up a centos 7 vm and ran into the same error. Not sure if  affected document creation, but the updated files looked ok when I did a git diff.

Output:
+++ [0301 15:24:02] Building go targets for darwin/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    federation/cmd/genfeddocs
E0301 13:38:51.703492   89850 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:51.802755   89851 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:51.905556   89852 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.006674   89853 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.108496   89854 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.193741   89855 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.290928   89856 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.405363   89858 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.512247   89860 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.620767   89861 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.732331   89862 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.839085   89863 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection
E0301 13:38:52.943670   89864 converter.go:87] Couldn't parse '' as bool for unstructured mismatch detection

**Comment by cblecker** [comment]
@chupman --
That warning shouldn't actually impact the script running, but you're right that it is concerning. This has actually been fixed in #42183, so if you rebase against master and run the scripts again this warning should go away.

**Comment by chupman** [comment]
I neglected to squash down to one commit on the rebase. Should I do a remedy that tomorrow?

**Comment by cblecker** [comment]
As it's all one action (fix comments and regen docs to pick it up), it's probably worth squashing :).

**Comment by chupman** [comment]
I realized this morning that I had used spaces instead of tabs on the types.go files. I just fixed it and I think it should be all good now. Let me know if there's anything else I need to do.

**Review by cblecker — APPROVED** [review]
Hi @chupman --
This looks good, although it requires a rebase. As the master branch is in the 1.6 code freeze right now, this won't be eligible for merge until it lifts on March 14, so might as well wait and rebase then.

**Comment by chupman** [comment]
Hi @cblecker 
I just rebased and it should be good. I also wanted to say thanks for all the help.

**Comment by cblecker** [comment]
No problem @chupman !

@mwielgus @erictune -- Can we get an `ok to test`? Thanks!

**Comment by mwielgus** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@chupman --
CI caught the following issues:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42288/pull-kubernetes-verify/22825/
```
I0321 20:11:32.633] /go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
I0321 20:25:44.284]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
```

**Comment by chupman** [comment]
Hi @cblecker I ran hack/update-staging-client-go.sh and then I reran all the hack scripts you originally listed to be safe.

**Comment by cblecker** [comment]
@chupman This needs a rebase.

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by cblecker** [comment]
/assign @lavalamp
Assigning to ensure it hit's @lavalamp's PR dashboard for approval.

**Comment by chupman** [comment]
Hello. Please let me know if I you want me to rebase to fix the "Last Updated" conflict in docs/api-reference/v1/definitions.html again.

**Comment by lavalamp** [comment]
/approve

sorry for delay

**Comment by cblecker** [comment]
/lgtm

Thanks for sticking with this one @chupman !

**Comment by chupman** [comment]
@cblecker FYI. I'm rerunning all the hack scripts and looks like it's changing different files with 1.6. I'm gonna check the diffs and push in a bit, but it'll probably need fresh review.

**Comment by cblecker** [comment]
@chupman Sounds good. I'll re-review once you've got it stable. Just ping me.

**Comment by chupman** [comment]
@k8s-bot non-cri e2e test this

**Comment by chupman** [comment]
@cblecker All tests passed and it's back to the exact same changes as before. It should be good to go.

**Pull request merged**
