### PR TITLE
Update the controller and client to support terminating pods (4/7)

### PR DESCRIPTION
**Pull request by smarterclayton**
Only the last commit is new to this pull.

Extracted from #9165 to make it easier to merge

### CODE REVIEW

**Comment by roberthbailey** [comment]
Assigning to @yujuhong since she reviewed #9165.

**Comment by yujuhong** [comment]
LGTM.

**Comment by erictune** [comment]
@smarterclayton is there a thing that keeps people from setting their termination grace period super high?

**Comment by smarterclayton** [comment]
No, I believe we discussed this in the first iteration and we said an admin
can always --grace-period=0, so it's really just the implications on the
infrastructure.  Even high grace periods don't stick around unless someone
says so.  Terminating pods still are accounted for in the scheduler.

On Fri, Aug 21, 2015 at 2:09 PM, Eric Tune <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> is there a thing that
> keeps people from setting their termination grace period super high?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/12957#issuecomment-133516425>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Pull request merged**
