### PR TITLE
"Add AcceleratorStats to cri_stats_provider for 1.18"

### PR DESCRIPTION
**Pull request by qiutongs**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Backport the fix in https://github.com/kubernetes/kubernetes/pull/96873 to release-1.18

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/pull/96873

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/lgtm
/triage accepted
/priority important-soon
/retitle "Add AcceleratorStats to cri_stats_provider for 1.18"

please add the release note for consistency with other cherry picks. I'm not actually sure it will be used though or just taken from the "original" PR to master.

**Comment by SergeyKanzhelev** [comment]
CC @kubernetes/release-managers this one is ready for merge

**Review by ruiwen-zhao — APPROVED** [review]

**Comment by ehashman** [comment]
@qiutongs @SergeyKanzhelev @dchen1107 supported branches all need to be in sync. Looks like this fix landed in 1.21, can we please also get PRs open for 1.19 and 1.20?

**Comment by SergeyKanzhelev** [comment]
> @qiutongs @SergeyKanzhelev @dchen1107 supported branches all need to be in sync. Looks like this fix landed in 1.21, can we please also get PRs open for 1.19 and 1.20?

this is catch up for 1.18. Already in later branches

**Pull request merged**
