### PR TITLE
Mark Topology Manager Test as non-alpha and NodeFeature

### PR DESCRIPTION
**Pull request by bobbypage**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

In #85093 Topology Manager moved to beta as of 1.18. The test is still marked in alpha and running on testgrid as an [alpha serial test](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial-alpha). Since the feature is no longer alpha, alpha tag should be removed and test will run as part of existing test in [kubelet-serial](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial) and [wg-resource-management](https://testgrid.k8s.io/wg-resource-management#kubelet-serial-gce-e2e-topology-manager)

**Which issue(s) this PR fixes**:

Fixes #

n/a

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
Looks good for me according to https://kubernetes.io/docs/setup/release/notes/#kubernetes-topology-manager-moves-to-beta---align-up

/lgtm
/approve

**Comment by fromanirh** [comment]
I'm late to the party, but since my review was requested, this
/lgtm

**Pull request merged**
