### PR TITLE
Do not clobber KUBERNETES_PROVIDER - fix kubeadm/gce log collection

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

This gets in the way of correct log collection for at least
the kubeadm/gce jobs. Not sure if this piece of code is needed
any more.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
cc @krzyzacy

**Comment by roberthbailey** [comment]
Can we verify if this code is needed before we wrap it in an extra conditional? This is a quite the hack.

**Comment by dims** [comment]
@roberthbailey - yes, i ran a series of experiments in https://github.com/kubernetes/kubernetes/pull/54799 and the result is what you see in this PR. the minimum change required to get the job done.

**Comment by dims** [comment]
@roberthbailey sorry i wasn't very clear. i did try removing that code entirely and other things failed.

**Comment by roberthbailey** [comment]
@shyamjvs - can you take a look at this? 

Dumping logs from different cluster providers is pretty gross and this makes it even more convoluted. Do we have a plan to clean it up? Should we just implement custom log dumpers per provider instead of relying on the bash gymnastics that we have today?

**Comment by shyamjvs** [comment]
/lgtm

> Dumping logs from different cluster providers is pretty gross and this makes it even more convoluted.

I totally agree. We need to factor out the cloud-provider specific stuff or sth.

> Do we have a plan to clean it up?

Not that I'm aware of. Though I remember an earlier discussion on making log-dump part of the kubetest deployer interface - which each provider will implement it's own. @zmerlynn @krzyzacy would know more.

**Comment by shyamjvs** [comment]
I'm seeing it's part of the deployer interface - https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L248-L255
However doesn't still seem like we've gotten rid of the bash totally.

**Comment by krzyzacy** [comment]
@shyamjvs https://github.com/kubernetes/test-infra/blob/master/kubetest/dump.go is a good start

**Comment by roberthbailey** [comment]
I'm going to hold my nose and really hope that https://github.com/kubernetes/test-infra/blob/master/kubetest/dump.go gets finished soon. In the mean time, having logs from kubeadm tests is better than a bit more technical debt in the kube-up scripts. 

/approve

**Comment by dims** [comment]
@roberthbailey - well said. my thoughts exactly!

**Pull request merged**
