### PR TITLE
Fix per golint in kube-controller-manager

### PR DESCRIPTION
**Pull request by jlucktay**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some `golint` failures in the `cmd/kube-controller-manager/app` package.

**Which issue(s) this PR fixes**:
ref: #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
I don't have approval permissions, but LGTM!

**Review by mattjmcnaughton — APPROVED** [review]

**Comment by jlucktay** [comment]
Seems like [this issue](https://github.com/kubernetes/test-infra/issues/12276) has struck the last batch of tests.

/retest

**Comment by jlucktay** [comment]
Current open issue around `pull-kubernetes-kubemark-e2e-gce-big` flaking is: #73105 

/test pull-kubernetes-kubemark-e2e-gce-big

**Pull request closed without merging**
