### PR TITLE
Update daemon.md

### PR DESCRIPTION
**Pull request by brendandburns**
@mikedanese @bgrant0607

### CODE REVIEW

**Comment by mikedanese** [comment]
Shouldn't examples test catch this?

**Comment by brendandburns** [comment]
Maybe we don't scrape across design?

**Comment by bgrant0607** [comment]
It could also be because YAML is in uppercase.

**Comment by nikhiljindal** [comment]
Yes. YAML should be in small case.
Also yaml should be in a separate file (which can be tested by examples_test.yaml and auto converted to a different version) and included in the doc via munger:
```
<!-- BEGIN MUNGE: EXAMPLE datastore-daemon.yaml -->
<!-- END MUNGE: EXAMPLE datastore-daemon.yaml -->
````

**Pull request merged**
