### PR TITLE
Remove internal apis of metrics

### LINKED ISSUE #45210: metrics API shouldn't depend on client-go/pkg/api
client-go/pkg/api will be removed in a coming refactor. Internal types (i.e, pkg/api/types.go) will only exist in k8s.io/kubernetes.

However, the [internal metrics API](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/metrics/pkg/apis) depends on api.ResourceList and api.ObjectReference. @DirectXMan12 why does the metrics API need an internal version? Can we just remove the internal version? If not, can we copy the definition of api.ResourceList and api.ObjectReference to k8s.io/metrics?

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #45210.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@DirectXMan12 i removed the internal types and the install package of the metrics api. All tests are passing. PTAL. Thanks.

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this

**Review by DirectXMan12 — CHANGES_REQUESTED** [review]
Err... this effectively prevents conversions in the metrics API, if we ever introduce a new version, does it not?  Otherwise, we can't follow the "hub-and-spokes" conversion model.

**Comment by caesarxuchao** [comment]
In theory whoever needs the conversion can create the internal types and run generators to generate the conversions. The tools perhaps are not easy to use though. Could you point me to the server code that needs the conversion? I want to see if it's easy to move the internal types to there.

**Comment by DirectXMan12** [comment]
So, there's intentionally no canonical server for custom metrics -- it's intended that consumers write their own on top of their own storage.  There's https://github.com/directxman12/custom-metrics-boilerplate, which is designed to act as a sample/make it easier to get started, but that's just some boilerplate to help people get started.

**Pull request closed without merging**
