### PR TITLE
cleanup: remove `pod_scheduling_duration_seconds`

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

remove `pod_scheduling_duration_seconds`, which is already deprecated.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The deprecated pod_scheduling_duration_seconds metric is removed.
You can migrate to pod_scheduling_sli_duration_seconds.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dom4ha** [comment]
There seem to be a process of removing metrics (Stable metric -> Deprecated metric -> Hidden metric -> Deletion).

Is this change following it?

**Comment by sanposhiho** [comment]
If I understand correctly, Yes. 

> On a subsequent release (when the metric's deprecatedVersion is equal to current_kubernetes_version - 1)), a deprecated metric will become a hidden metric. 

I interpreted this part as the deprecated metric would automatically become the hidden metric. 
We can ask the review from sig-instrumentation to make sure about it..

**Comment by sanposhiho** [comment]
/assign @dashpole 

for the metric part.

**Review by dashpole — APPROVED** [review]
lgtm

**Pull request merged**
