### PR TITLE
WIP: Allow multiple api group prefixes

### PR DESCRIPTION
**Pull request by sttts**
Needed for downstream, compare https://github.com/openshift/origin/pull/11192/files#r83795002.

TODO:
- [ ] add tests with multiple prefixes

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35021)

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot gci gke e2e test this

**Comment by deads2k** [comment]
I already added https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/config.go#L175 and I don't think we want multiple `/apis`

**Comment by sttts** [comment]
Closing, actually not needed by downstream origin.

**Pull request closed without merging**
