### PR TITLE
Fix help msg for kubectl get cmd

### PR DESCRIPTION
**Pull request by andronat**
Refs to GoogleCloudPlatform/kubernetes#7842

I am not sure if this is the right way on solving this. Can someone comment?

(btw, I didn't regenerated the docs. It is just for initializing a discussion. Don't merge)

/cc @mbforbes

### CODE REVIEW

**Comment by jlowdermilk** [comment]
I'm 50/50 on this. I'm generally in favor of autogenerating stuff, but this also seems a bit overkill for keeping a help string up to date, given that we don't add resources that often.

In any case, I don't think this is worth spending time on right now. Let's just update the const help string and look at doing something smarter post v1.0.

**Comment by andronat** [comment]
Ok I will just update the help string

**Comment by andronat** [comment]
done

**Comment by jlowdermilk** [comment]
Thanks, @andronat. LGTM

Fixes #7842

**Comment by thockin** [comment]
Negative on CI

**Comment by jlowdermilk** [comment]
I think this just needs rebase to pick up #8965.

**Comment by andronat** [comment]
rebased and ready

**Pull request merged**
