### PR TITLE
Add user agent string to all client requests

### LINKED ISSUE #2596: Set User-Agent in client library
Forked from #2243.

@smarterclayton wrote: We've used `libname/<deep version>-commit (os: , runtime: )` in the past, and then changed libname to the executable name when used in a binary.  "os" helps catch wierd envs people care about but we didn't think to test, runtime has been useful for error reports, commit catches roll your own folks but won't work for us (since it's a compile time thing).

curl:
```
curl/7.26.0
```

Common browser/tool/bot settings are here:
http://www.useragentstring.com/pages/useragentstring.php

I still think it would be useful to set User-Agent, for monitoring purposes if nothing else, though I'm becoming less sure it could be used to customize default behavior.

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #2596

### CODE REVIEW

**Comment by smarterclayton** [comment]
Removed some unused code in kubectl while i was at it, and fixed hack local up cluster.

**Comment by nikhiljindal** [comment]
Integration test failure seems relevant:
[utils.go:35] unable to connect to etcd for integration testing: 100: Key not found () [2]

**Comment by bgrant0607** [comment]
Cool, thanks.

**Comment by smarterclayton** [comment]
Should be cleaned up across all 3 scripts that use etcd::start

----- Original Message -----

**Comment by nikhiljindal** [comment]
LGTM.
Can you please delete kubectl_test.go and I will merge.

**Comment by smarterclayton** [comment]
Done.

----- Original Message -----

**Comment by nikhiljindal** [comment]
Thanks!

**Pull request merged**
