### PR TITLE
dockershim: remove corrupted sandbox checkpoints

### PR DESCRIPTION
**Pull request by yujuhong**
This is a workaround to ensure that kubelet doesn't block forever when
the checkpoint is corrupted.

This is a workaround for #43021

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gce e2e test this

**Comment by dchen1107** [comment]
lgtm but I want to @thockin's opinion on this one. Thanks!

**Comment by yujuhong** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gce e2e test this

**Pull request merged**
