### PR TITLE
Validate apps/v1 DaemonSet selector immutable on updates

### LINKED ISSUE #54575: [e2e failure] [sig-apps] Daemon set [Serial] Should adopt existing pods when creating a RollingUpdate DaemonSet regardless of templateGeneration
/priority failing-test
/priority critical-urgent
/sig apps

This test case has been failing for a while and affects a number of jobs: [triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-apps%5C%5D%20Daemon%20set%20%5C%5BSerial%5C%5D%20Should%20adopt%20existing%20pods%20when%20creating%20a%20RollingUpdate%20DaemonSet%20regardless%20of%20templateGeneration)

This is affecting multiple jobs on the [release-master-blocking](https://k8s-testgrid.appspot.com/sig-release-master-blocking) testgrid dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22). Is there work ongoing to bring this job back to green?

[triage cluster a39a48487b56c56a97d6](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-apps%5C%5D%20Daemon%20set%20%5C%5BSerial%5C%5D%20Should%20adopt%20existing%20pods%20when%20creating%20a%20RollingUpdate%20DaemonSet%20regardless%20of%20templateGeneration#a39a48487b56c56a97d6)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:435
Expected error:
    <*url.Error | 0xc421c50fc0>: {
        Op: "Get",
        URL: "https://35.188.204.137/api/v1/namespaces/e2e-tests-daemonsets-wvmh7/pods?labelSelector=daemonset-name%3Ddaemon-set",
        Err: {
            Op: "dial",
            Net: "tcp",
            Source: nil,
            Addr: {
                IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 35, 188, 204, 137],
                Port: 443,
                Zone: "",
            },
            Err: {
                Syscall: "getsockopt",
                Err: 0x6f,
            },
        },
    }
    Get https://35.188.204.137/api/v1/namespaces/e2e-tests-daemonsets-wvmh7/pods?labelSelector=daemonset-name%3Ddaemon-set: dial tcp 35.188.204.137:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:553
```

@kubernetes/sig-apps-test-failures

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54575

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by enisoc** [comment]
/lgtm

cc @crimsonfaith91

**Comment by janetkuo** [comment]
/assign @liggitt

@liggitt would you take a look? Thanks!

**Review by kow3ns — APPROVED** [review]
/lgtm

**Comment by crimsonfaith91** [comment]
I think `run_recursive_resources_tests` failure is irrelevant to this PR. I also encountered it in 2 of my PRs.

**Pull request merged**
