### PR TITLE
fix wrong calculation of available pods

### PR DESCRIPTION
**Pull request by Haleygo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Shouldn't calculate 8/10 first because the result will always be 0, and make availablePods 0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
nice catch

/ok-to-test
/triage accepted
/lgtm

**Comment by Haleygo** [comment]
@oomichi Test is ready now, can you review this again, thanks a lot :)

**Comment by liggitt** [comment]
/unassign
/assign @smarterclayton 
per https://github.com/kubernetes/kubernetes/pull/54308/files#diff-a69dabee42c02d59d7ff62edc8c07eb83ef9b43de0d3d9e5d649321778b3abfbR64

it looks like this could bump the number of pods we create in e2e runs... is that affecting the presubmits noticeably?

**Comment by pacoxu** [comment]
Since #54308 was merged, the estimateMaximumPods is changed to 10 since then, the min number. The original is 100.

The func estimateMaximumPods doesn't work at all.  😄

**Comment by Haleygo** [comment]
@smarterclayton @liggitt 
Since there are bounds for availablePods, this pr should just fix the calculation error, can you help review it again？
https://github.com/kubernetes/kubernetes/blob/7bff8adaf683dc7e25b5548e2c16e7393ff8a036/test/e2e/apimachinery/garbage_collector.go#L71-L77

**Comment by Haleygo** [comment]
@liggitt @smarterclayton 
PTAL, thanks :)

**Comment by Haleygo** [comment]
Already fix in https://github.com/kubernetes/kubernetes/pull/106448
/close

**Pull request closed without merging**
