### PR TITLE
Change remove() to removeAll()

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
If some files in this dir, remove() will fail. So use removeAll() will be better.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
ping @saad-ali

**Comment by zhangxiaoyu-zidif** [comment]
ping @saad-ali

**Comment by zhangxiaoyu-zidif** [comment]
ping @jsafrane 
PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@kubernetes/sig-testing-bugs 
after I rebase the code, the `needs-rebase` label still exists.

**Comment by jsafrane** [comment]
> If some files in this dir, remove() will fail. So use removeAll() will be better.

If some files remain in the dir, then something went wrong. Kubernetes was either not able to detect it's a mount point or it has placed some files there. In both cases it may delete user data.

Are you able to hit a condition when `RemoveAll` helps? Do you have a reproducer?

**Comment by zhangxiaoyu-zidif** [comment]
@jsafrane 
we found it by accident. At first , we wanted to keep ceph secret file in the Mount point directory and then did some related test. but we found we can not remove the directory. so we are sure use `removeAll()` will help.

**Comment by zhangxiaoyu-zidif** [comment]
>If some files remain in the dir, then something went wrong. Kubernetes was either not able to detect it's a mount point or it has placed some files there. In both cases it may delete user data.

yes, it will delete user data, I am not sure here, if there is necessary to keep that data when unmount.

**Comment by BenTheElder** [comment]
> after I rebase the code, the needs-rebase label still exists.

Yes, there are some upstream github issues causing needs-rebase not to work. cc @cjwagner 
/test pull-kubernetes-typecheck

**Pull request closed without merging**
