### PR TITLE
Mark deprecated in related workqueue metrics

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/sig instrumentation

**What this PR does / why we need it**:

As discussed [here](https://github.com/kubernetes/kubernetes/pull/72332#issuecomment-451964891), need to add `Deprecated` in the description of deprecated metrics.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Just so I know, we are consistently using `(Deprecated) ` for all metrics we do this to?

**Comment by brancz** [comment]
We are.

**Review by logicalhan — APPROVED** [review]
/lgtm

Thanks for cleaning these up!

**Pull request merged**
