### PR TITLE
Automated cherry pick of #69858: Grant permissions for batch/job to cluster-autoscaler

### PR DESCRIPTION
**Pull request by losipiuk**
Cherry pick of #69858 on release-1.12.

#69858: Grant permissions for batch/job to cluster-autoscaler

### CODE REVIEW

**Comment by spiffxp** [comment]
/kind bug
/lgtm
/assign @mikedanese 
since you're assigned for approval on the PR being cherry-picked

**Comment by losipiuk** [comment]
@feiskyer are you fine with approving this one?
The #69858 was already merged to master.

**Comment by feiskyer** [comment]
@losipiuk done

**Pull request merged**
