### PR TITLE
Add note about etcd v3.5.0 data corruption

### PR DESCRIPTION
**Pull request by serathius**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:
```docs
- [Etcd statement] https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ
```
/cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

@kubernetes/release-managers - for approval

**Comment by serathius** [comment]
I'm trying to figure out how I should update TOC, however looks like the pull-kubernetes-verify passed. 

/retest

**Pull request merged**
