### PR TITLE
Fix resource quota controller panic

### PR DESCRIPTION
**Pull request by ironcladlou**
The pod evaluator used by the resource quota controller made direct calls to an
unsafe pod conversion function which mutates the pod argument. With multiple
resource quota controller workers, concurrent processing of the same pod from a
shared informer can result in a panic when the conversion code attempts to write
to a map field in the pod.

Swap out the direct conversion function call to Scheme.ConvertToVersion, which
copies the input before conversion.

```release-note
Fix a kube-controller-manager crash which can result when `--concurrent-resource-quota-syncs` is >1 and pods exist in the system containing certain alpha/beta annotation keys.
```

Fixes https://github.com/kubernetes/kubernetes/issues/52093.

@kubernetes/sig-api-machinery-bugs 

/cc @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
link to issue?

**Comment by liggitt** [comment]
release note can probably be less detailed

**Comment by liggitt** [comment]
this LGTM

**Comment by caesarxuchao** [comment]
lgtm

**Comment by liggitt** [comment]
@wojtek-t for release approval

**Pull request merged**
