### PR TITLE
Make secret volumes function correctly across reboot

### PR DESCRIPTION
**Pull request by pmorie**
Fix for  #7958

Blocks: #7580

### CODE REVIEW

**Comment by pmorie** [comment]
@thockin @roberthbailey @mbforbes I'm going to test this by pulling in #7580 into my branch and doing an e2e run in gce.  Sufficient?

**Comment by thockin** [comment]
Just reboot the node that runs the DNS server :)

**Comment by thockin** [comment]
LGTM - please confirm testing.  Any way to get unit test coverage for this?

**Comment by thockin** [comment]
I'll commit this once it goes green if you promise to back it up with tests in relatively short order.

**Comment by pmorie** [comment]
@thockin yep, i'm thinking about how best to do unit coverage

**Comment by mbforbes** [comment]
@pmorie huge thanks. Rather than pulling in #7580, which reboots all nodes at some random point during the e2es based on the seed, the best test is probably to create a cluster, `sudo reboot` all the nodes, wait a bit for all nodes & pods to be running / ready, then run the current e2es. But you're probably already mostly done with this, so I defer.

**Comment by pmorie** [comment]
@mbforbes I had problems building an artifact for e2e with #7580 pulled in.  Trying just with this code now, and I'll do a manual test or reboot the node with the dns pods during the e2e.

**Comment by pmorie** [comment]
I'm having problems building for gce deploy: #8197

**Comment by pmorie** [comment]
I'll try it with vagrant but will probably have a little latency.  Open to a testing assist if someone else is in a position to verify this faster than I.

**Comment by pmorie** [comment]
Nevermind, got it sorted, I'm kicking off a gce run now.

**Comment by pmorie** [comment]
My GCE cluster seems to be taking quite a while to pull images, is this typical?  I haven't done a GCE run in a week or two.

**Comment by mbforbes** [comment]
@pmorie could it be #8068? I thought the problem was long pulls until looking closer.

**Comment by pmorie** [comment]
@mbforbes I don't think so -- the pods are scheduled, but the image pulls aren't complete:

```
$ cluster/kubectl.sh get pods
POD                                          IP        CONTAINER(S)            IMAGE(S)                                          HOST                                          LABELS                                                          STATUS    CREATED     MESSAGE
elasticsearch-logging-v9upr                                                                                                      e2e-test-pmorie-minion-rc7w/104.197.111.243   kubernetes.io/cluster-service=true,name=elasticsearch-logging   Pending   8 minutes   
                                                       elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.2                                                                                                                      Waiting               Image: gcr.io/google_containers/elasticsearch:1.2 is not ready on the node
elasticsearch-logging-voqvq                                                                                                      e2e-test-pmorie-minion-h72v/104.197.98.183    kubernetes.io/cluster-service=true,name=elasticsearch-logging   Pending   8 minutes   
                                                       elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.2                                                                                                                      Waiting               Image: gcr.io/google_containers/elasticsearch:1.2 is not ready on the node
kibana-logging-ympqf                                                                                                             e2e-test-pmorie-minion-h72v/104.197.98.183    kubernetes.io/cluster-service=true,name=kibana-logging          Pending   8 minutes   
                                                       kibana-logging          gcr.io/google_containers/kibana:1.3                                                                                                                             Waiting               Image: gcr.io/google_containers/kibana:1.3 is not ready on the node
kube-dns-bcpuy                                                                                                                   e2e-test-pmorie-minion-rc7w/104.197.111.243   k8s-app=kube-dns,kubernetes.io/cluster-service=true             Pending   8 minutes   
                                                       etcd                    gcr.io/google_containers/etcd:2.0.9                                                                                                                             Waiting               Image: gcr.io/google_containers/etcd:2.0.9 is not ready on the node
                                                       kube2sky                gcr.io/google_containers/kube2sky:1.4                                                                                                                           Waiting               Image: gcr.io/google_containers/kube2sky:1.4 is not ready on the node
                                                       skydns                  gcr.io/google_containers/skydns:2015-03-11-001                                                                                                                  Waiting               Image: gcr.io/google_containers/skydns:2015-03-11-001 is not ready on the node
monitoring-heapster-controller-j806h                                                                                             e2e-test-pmorie-minion-rc7w/104.197.111.243   kubernetes.io/cluster-service=true,name=heapster                Pending   8 minutes   
                                                       heapster                gcr.io/google_containers/heapster:v0.11.0                                                                                                                       Waiting               Image: gcr.io/google_containers/heapster:v0.11.0 is not ready on the node
monitoring-influx-grafana-controller-m74bv                                                                                       e2e-test-pmorie-minion-rc7w/104.197.111.243   kubernetes.io/cluster-service=true,name=influxGrafana           Pending   8 minutes   
                                                       influxdb                gcr.io/google_containers/heapster_influxdb:v0.3                                                                                                                 Waiting               Image: gcr.io/google_containers/heapster_influxdb:v0.3 is not ready on the node
                                                       grafana                 gcr.io/google_containers/heapster_grafana:v0.7                                                                                                                  Waiting               Image: gcr.io/google_containers/heapster_grafana:v0.7 is not ready on the node
```

**Comment by mbforbes** [comment]
@pmorie I cherry-pick'd this commit and will run e2es as well.

**Comment by pmorie** [comment]
@mbforbes I've been in meetings this afternoon, I'm going to try to pick through what's actually going on now.

**Comment by pmorie** [comment]
...or maybe in a little bit, since I realized I haven't taken a break today at all, even for lunch.

**Comment by mbforbes** [comment]
Take a break! Eat! It looks like I can't get pods to be 'Running' either, so someone either has a P0 bug or needs one.

**Comment by pmorie** [comment]
@mbforbes Agree re p0.

**Comment by thockin** [comment]
Eating is for slackers.  You're not a slacker, are you, Paul?

**Comment by pmorie** [comment]
@thockin You're right, there's all this food right here in github :tangerine: :poultry_leg: :cake: :fish_cake:

**Comment by thockin** [comment]
Wow, unicode really does have a glyph for everything.

**Comment by pmorie** [comment]
@thockin :bust_in_silhouette: :busts_in_silhouette:

**Comment by mbforbes** [comment]
Opened #8207 to let us get back to work.

In the mean time, going for :coffee:.

**Comment by mbforbes** [comment]
@pmorie #8207 actually isn't an issue for me at head. Could your PR have introduced that regression, someway, somehow?

**Comment by pmorie** [comment]
@mbforbes definitely possible.  I'll be looking tonight.

**Comment by pmorie** [comment]
Ugh, PEBCAK

**Comment by pmorie** [comment]
Okay, the code I have is a little better, but I need to dig into DNS e2e failure after rebooting the minion w/ the skydns pod scheduled onto it.

**Comment by pmorie** [comment]
Will try to get this finished tomorrow AM.  Apologies for the delay.

**Comment by thockin** [comment]
Thanks for digging in.

**Comment by pmorie** [comment]
Okay, I think this works, but I'm seeing some behavior in the GCE cluster I made to test this that is preventing me from being able to say that the following works:

1.  Make cluster, run e2e tests, get green
2.  Reboot minion with skydns pod
3.  Run DNS e2e, get green

It looks like the secrets are laid out correctly after reboot:

```
$ mount | grep tmpfs
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=217595,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=174516k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=349020k)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
tmpfs on /var/lib/kubelet/pods/89d1c949-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/token-system-logging type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/897641cc-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/dns-token type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/8994bb72-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/default-token-3e013 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/89d1c949-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/default-token-3e013 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/89b33e40-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/default-token-3e013 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/897641cc-fa4b-11e4-b942-42010af0d817/volumes/kubernetes.io~secret/default-token-3e013 type tmpfs (rw,relatime)
```

However, the docker daemon isn't starting (at least not right away), so the pod sync fails.

Other than that, it looks to me like this is working.  If anyone wants to pull this patch and test it independently, I would appreciate it.

**Comment by thockin** [comment]
Trying a quick repro of the docker issue

**Comment by thockin** [comment]
I just rebooted and docker came back.  In your case is it dead forever?

**Comment by pmorie** [comment]
My bad, I was doing it wrong in the shell.  Docker just hadn't started yet.

**Comment by mbforbes** [comment]
@pmorie did you determine whether what I was seeing in #8207 was part of your change? Is it a PEBCAK for me as well?

I'm asking because running with this change, now most e2es pass, but the reboot itself doesn't work! All of the pods are in 'Pending' and don't become 'Running' within 2 minutes, which never happened before, and looks just like #8207.

**Comment by pmorie** [comment]
@mbforbes PEBCAK in this case was me misreading entries in the log.  I did notice this morning that the docker daemon seemed to take quite a while to start, and that contributed to some confusion when the DNS e2e didn't work immediately after reboot.

**Comment by mbforbes** [comment]
@pmorie thanks for the response—this time, it turned out to be just a little bit slower than I anticipated (2m6s rather than always < 2m, as previously), which was failing timeouts I hadn't seen before. So, benign overall. Thanks again for the fix!

**Pull request merged**
