### PR TITLE
Update usage guidelines to reflect the donation to CNCF

### PR DESCRIPTION
**Pull request by brendandburns**
@sarahnovotny @jbeda

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34657)

### CODE REVIEW

**Comment by jbeda** [comment]
Looks reasonable to me.

**Review by sarahnovotny — APPROVED** [review]
LGTM

**Comment by brendandburns** [comment]
I'm self LGTM-ing on Sarah's LGTM.

**Comment by dankohn** [comment]
I went in to make this change myself today and was pleased to see that @brendandburns had already done it just as I would have. I would appreciate a cc on trademark and other CNCF-related policy issues in the future.

**Pull request merged**
