### PR TITLE
Update "/stats" endpoint on kubelet.

### PR DESCRIPTION
**Pull request by vishh**
Added 'namespace' as an argument to the '/stats' endpoint.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
Fixes #3204

**Comment by dchen1107** [comment]
LGTM.

**Comment by jbeda** [comment]
I worry that someone might be taking a dependency on this.  This might prevent mixed server/kubelet versions.

We need an API version string on this and make sure we don't make backward incompatible changes. 

cc: @bgrant0607 @lavalamp @brendandburns

**Comment by derekwaynecarr** [comment]
I agree Kubelet needs an API version, but in this case, it looks to me that the support for namespace in url path is additive, and the old pattern that just assumed "default" still worked.

----- Original Message -----

**Comment by dchen1107** [comment]
yeah, this one should be backward compatible. We need to formalize Kubelet API and add versioning too. The first step is taking Pod instead of BoundPod.

**Comment by bgrant0607** [comment]
Yes, the Kubelet needs a real, versioned, documented API with well defined schemas, semantics, error behavior, etc. 

Right now, the API is undocumented and undiscoverable, though, so it would be hard to use.

**Comment by lavalamp** [comment]
Kubelet needs to get a real API.

cc/ @saad-ali

**Pull request merged**
