### PR TITLE
Rename PULL_REQUEST_TEMPLATE to PULL_REQUEST_TEMPLATE.md.

### PR DESCRIPTION
**Pull request by david-mcmahon**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
Failed tests

**Comment by bgrant0607** [comment]
Wild guess (without looking at test results) is that doc verification checks are now running on this since it has a .md extension: boilerplate, analytics, etc.

**Comment by david-mcmahon** [comment]
Good guess @bgrant0607.  Needs lgtm now.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
