### PR TITLE
Improve code coverage for kubectl set

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@soltysh i forget commit and push my code so that before PR losed. can you help me review this continue. and i combined two cases to one. thanks

**Comment by xiangpengzhao** [comment]
please run `hack/update-bazel.sh` to update BUILD file.

**Comment by xiangpengzhao** [comment]
maybe gofmt also

**Comment by zjj2wry** [comment]
@xiangpengzhao thanks

**Comment by zhangxiaoyu-zidif** [comment]
@zjj2wry  why close it？

**Comment by zjj2wry** [comment]
@zhangxiaoyu-zidif this is long history ~.~ and i  no mood see it

**Comment by zhangxiaoyu-zidif** [comment]
@zjj2wry  feel sorry for that.
As same as kubectl translation task.

**Comment by zjj2wry** [comment]
@zhangxiaoyu-zidif i will add this is my another PR. maybe this can not be a commits. because it just test simple validation logic. i will continue translate kubectl. but now it read my system config lang. i will fix that todo before, and let it can convenience switch language.

**Pull request closed without merging**
