### PR TITLE
[Scheduler] Remove error since err is always nil

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

No need to log error since err is always nil.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sakeven** [comment]
Is it ok to test? @timothysc @jayunit100

**Comment by jayunit100** [comment]
Seems like a no-op to me.  I don't mind cleanup but maybe a little broader logging cleanup would be more useful.

**Comment by timothysc** [comment]
@k8s-bot test this

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve no-issue

**Pull request merged**
