### PR TITLE
Automated cherry pick of #23445

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #23445 on on release-1.2.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Progress toward #26594 (I'll have to rebase #26643).

**Comment by ihmccreery** [comment]
cc @ncdc

**Comment by ihmccreery** [comment]
@ncdc Can you please reply that you're "'okay with these commits being contributed to Google"?

**Comment by ihmccreery** [comment]
@k8s-bot unit test this again please issue: #25513

**Comment by ncdc** [comment]
@googlebot I'm okay with these commits being contributed to Google

**Comment by ihmccreery** [comment]
@roberthbailey Do you know the magic label combination to get this merged?

**Pull request merged**
