### PR TITLE
updated fluentd in fluentd-es-image to version 1.2.2

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: Updates fluentd in fluentd-es-image to version 1.2.2.
Also updates all other used gems to most recent versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by coffeepac** [comment]
@monotek you need to update the pod spec to use the new image tag, its not automatic.  can you make the update?

**Comment by coffeepac** [comment]
@monotek I manually rebased this PR onto #62910 and was able to bring up a functioning system.  so, woo!  

I'm going to hold off on giving an LGTM until the other PR goes through so we can keep the built images in sync with the source code.

**Comment by monotek** [comment]
I just updated the pr with current versions and merges from https://github.com/kubernetes/kubernetes/pull/62910

**Comment by coffeepac** [comment]
thanks @monotek !

**Comment by monotek** [comment]
This is the template for the image which has to be build manually by some googler...

**Comment by monotek** [comment]
@Random-Liu & @crassirostris

Could one of you trigger the build for the new container please?

**Comment by coffeepac** [comment]
I have pinged the google team that has write permissions to this repo.  Hopefully we hear back soon.

**Comment by monotek** [comment]
Thanks a lot! :-)

Would be cool this build could be somehow automated...

**Comment by coffeepac** [comment]
Yeah, I'm funemployed right now.  I'm planning on tackling this issue next week.  First cut won't be automated but I will be able to build it at least.

**Pull request merged**
