### PR TITLE
openstack: remove field flavor_to_resource

### PR DESCRIPTION
**Pull request by zhouhaibing089**
I believe there is no usage about `flavor_to_resource`, and I think there is no need to build that information, too.

cc @anguslees 

**Release note:**

```
NONE
```

### CODE REVIEW

**Comment by zhouhaibing089** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by zhouhaibing089** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/10399

**Comment by cblecker** [comment]
cc: @kubernetes/sig-openstack-pr-reviews

**Comment by anguslees** [comment]
/approve

Thanks, this has been unused since e20467afcb48ea7b0002ba2c91cac07ba06b3705 removed `Instances.GetNodeResources()` (2015!)

**Pull request merged**
