### PR TITLE
Automated cherry pick of #10608

### PR DESCRIPTION
**Pull request by stefwalter**
Please cherry-pick #10608 into release 1.0.

This functionality is blocking local use of 'kubectl proxy' on a machine with multiple users.

We would like to use this functionality in Cockpit to authenticate and transport to the Kubernetes API server. See: https://github.com/cockpit-project/cockpit/pull/2463

### CODE REVIEW

**Comment by zmerlynn** [comment]
Need rebase.

**Comment by zmerlynn** [comment]
Also not sure about adding this functionality in a patch release. @jlowdermilk, thoughts?

**Comment by jlowdermilk** [comment]
Seems fine to cherrypick. It's something we wanted to get into 1.0 but didn't make the cut. I'd run it by @bgrant0607 though.

**Comment by bgrant0607** [comment]
Is another 1.0.x release planned? If so, do we have criteria for what should be included? My general preference would be to not cherrypick misc. improvements. That's what 1.1 is for.

OTOH, there are things, like docs and kubectl, that could be released on a more frequent cycle than the rest of the system. Sadly, I doubt we have the manpower to do the necessary testing to pull this off.

@stefwalter What are the consequences of not creating a 1.0.x release containing this feature? It sounds like you've already worked around its absence.

**Comment by stefwalter** [comment]
> @stefwalter What are the consequences of not creating a 1.0.x release containing this feature? It sounds like you've already worked around its absence.

The workaround is to run Cockpit on the same system as the API server and to not get fancy with API server authentication.

This just missed a sprint milestone anyway ... so if 1.1 is released within a realistic timeframe, I wouldn't be against that.

**Comment by zmerlynn** [comment]
@stefwalter: 1.1 is a couple of months away still. 1.0.4 is likely going to be a week or two, but hasn't been scheduled. I'm generally inclined to hold the line on misc improvements as well, and keep the patch releases for what they are, even on the client side.

@bgrant0607: We should really codify it in (versioning)[https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md] or somewhere similar so that we can point people to policy (unless I missed where it's codified already).

**Comment by bgrant0607** [comment]
1.1 is targeted for October.

**Comment by zmerlynn** [comment]
I'm closing this for now, so it doesn't show up on `release-1.0` cherry pick searches (it's currently in need of rebase anyways). I opened #12932 to discuss further.

**Pull request closed without merging**
