### PR TITLE
Automated cherry pick of #46239

### PR DESCRIPTION
**Pull request by mtanino**
Cherry pick of #46239 on release-1.6.

#46239: Log out from multiple portals with iscsi storage plugin

This Cherry pick also includes fix #46968(follow-up fix for #46239)

#46968: iscsi storage plugin: bkpPortal should be initialized beforehand

### CODE REVIEW

**Comment by mtanino** [comment]
@k8s-bot ok to test

**Comment by rootfs** [comment]
/approve
@k8s-bot ok to test

**Pull request merged**
