### PR TITLE
Set MemorySwap to zero on Windows

### PR DESCRIPTION
**Pull request by brendandburns**
Cherry pick of #39005 to fix kubelet + Docker 1.14-dev on Windows.  See https://github.com/kubernetes/kubernetes/issues/39003 for details.

@saad-ali @kubernetes/release-admins @kubernetes/release-reviewers

### CODE REVIEW

**Comment by saad-ali** [comment]
There are comments on the original PR about it breaking cross builds, are those concerns addressed, and if so are those PRs included in this cherry pick?

**Comment by brendandburns** [comment]
@saad-ali thanks for pointing that out. I'll add those PRs.

**Comment by brendandburns** [comment]
@saad-ali cherry-picks added (and a small merge commit too)

Please take another look.

**Comment by brendandburns** [comment]
ping @yujuhong on this one...  I think it's ready to go.

Thanks!

**Comment by yujuhong** [comment]
LGTM. Leaving to @saad-ali to approve the cherry-pick.

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by saad-ali** [comment]
For reference this also cherry-picks PR #39731

**Pull request merged**
