### PR TITLE
Validate service account name in pod spec

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by satnam6502** [comment]
@brendandburns @bgrant0607 what is the milestone for this PR?
i.e. can this be merged now?

**Comment by bgrant0607** [comment]
This is fine.

**Comment by bgrant0607** [comment]
@liggitt spec.ServiceAccount is an object name, correct?

As per https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-102536924, it should be ServiceAccountName in the v1 API.

**Comment by liggitt** [comment]
Correct. Either renaming the field or make it a local object reference, not sure which we're trying to standardize on

**Comment by liggitt** [comment]
Ah, just read the linked comment

**Pull request merged**
