### PR TITLE
Remove the redundant space

### PR DESCRIPTION
**Pull request by SataQiu**
**What this PR does / why we need it**:
Remove the redundant space
/kind cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by SataQiu** [comment]
Dear @liggitt , this PR needs a new `LGTM` label to be merged after the repeated submission.  
I roll back some changes because no approver has approved them after a long time.

**Pull request merged**
