### PR TITLE
Automated cherry pick of #67298: Log real file's name and line

### PR DESCRIPTION
**Pull request by sylr**
Cherry pick of #67298 on release-1.11.

#67298: Log real file's name and line

### CODE REVIEW

**Comment by sylr** [comment]
Ca we go forward with this ? It has been already merged into 1.10 #67821

cc @soltysh @sttts

**Comment by sylr** [comment]
/assign @soltysh @pwittrock

as sig-cli approvers

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/assign @foxish 
for 1.11 approval

**Pull request merged**
