### PR TITLE
fix typo brance -> brace

### PR DESCRIPTION
**Pull request by DylanBLE**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
fix typo brance -> brace

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nikhita** [comment]
@DylanBLE thanks for catching that!

/ok-to-test
/lgtm

/assign @soltysh 
for approval

**Comment by nikhita** [comment]
/retest

@DylanBLE sorry that you are seeing so many flakes on your first contribution :(

**Comment by DylanBLE** [comment]
cc @smarterclayton @soltysh

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
