### PR TITLE
Bump up glbc version to 0.7.1

### PR DESCRIPTION
**Pull request by bprashanth**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30545)

### CODE REVIEW

**Comment by bprashanth** [comment]
Picks up a couple of fixes, would like to get some testing on it asap

**Comment by girishkalele** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30545)*

**Comment by girishkalele** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30545#-:-KP-mleuppbnQRBM_xDn:bnfp4nl)*

**Comment by bprashanth** [comment]
@k8s-bot test this github issue: #30228

**Comment by bprashanth** [comment]
@k8s-bot unit test this github issue: #30228

**Comment by bprashanth** [comment]
Bumping up prio to get test time before potential 1.3 cherrypick

**Pull request merged**
