### PR TITLE
Fix typo in pkg/kubelet/.../helpers_test.go

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Fix typo in kubernetes/pkg/kubelet/apis/config/helpers_test.go

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by lavalamp** [comment]
This should really go to someone in sig node but to avoid any more noise, 

/approve

**Comment by ehashman** [comment]
@lavalamp issue is that the approvers on this OWNERS file are the `api-reviewers`, @mrunalp already approved for Node :/

**Comment by lavalamp** [comment]
oh, I see. thanks!

**Pull request merged**
