### PR TITLE
remove duplicate word in CHANGELOG

### PR DESCRIPTION
**Pull request by xlgao-zju**
``` release-note
remove duplicate word in CHANGELOG
```

Signed-off-by: Xianglin Gao xlgao@zju.edu.cn

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30344)

### CODE REVIEW

**Comment by dims** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30344#-:-KOr8wUd8OBhS5N9X75c:bnfp4nl)*

**Comment by resouer** [comment]
@bgrant0607 This PR is ok to merge :/

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
thanks, lgtm

**Comment by bgrant0607** [comment]
This PR had no assignee due to #29575

**Comment by xlgao-zju** [comment]
"@k8s-bot gke e2e test this, issue: #30344

**Comment by xlgao-zju** [comment]
@k8s-bot gke e2e test this, issue: #IGNORE

**Comment by xlgao-zju** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by xlgao-zju** [comment]
@bgrant0607 I don't know why I get failed in `Jenkins unit/integration`.

**Comment by bgrant0607** [comment]
@k8s-bot unit test this issue: #30462

**Pull request merged**
