### PR TITLE
Add test cases to test the default value of HorizontalPodAutoscaler

### PR DESCRIPTION
**Pull request by yarntime**
Add test cases to test the default value of HorizontalPodAutoscaler.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33534)

### CODE REVIEW

**Comment by yarntime** [comment]
@smarterclayton I added two test cases to test the default value of HorizonPodAutoscaler, please take a moment to verify it, thank you very much.

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by yarntime** [comment]
@k8s-bot verify test this

**Comment by yarntime** [comment]
@smarterclayton  hi smarterclayton , it's my first commit and i have no idea why the jenkins verification is failed, can you help me to fix it? thank you very much.

**Comment by yarntime** [comment]
Hi @smarterclayton, thanks for your kindly reply, and I think it works.

@k8s-bot verify test this

**Comment by yarntime** [comment]
Hi @smarterclayton, it seems that all tests hava passed, can you give the LGTM label? thank you very much.

**Comment by smarterclayton** [comment]
Please squash your commits down to one.

**Comment by smarterclayton** [comment]
LGTM, thanks!

**Pull request merged**
