### PR TITLE
if loadbalancer section is not defined in cloudconfig, do not init support

### LINKED ISSUE #65775: Support enabling BlockStorage but disabling LoadBalancer in cloud provider
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I use [Openstack Block Storage](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#openstack) but my cloud provider doesn't support Openstack LBaaS. Because of the latter I've been using MetalLB instead to get things going. However I keep getting warnings when deploying a `ServiceType: LoadBalancer` when there is no `[LoadBalancer]` configuration defined in `cloud.conf`.  [Reference](https://github.com/google/metallb/issues/269#issuecomment-400727870)

NOTE: `cloud.conf` has only a `[Global]` section - there is no mention no `[LoadBalancer]` section.

**What you expected to happen**:

`service-controller` should not print warning via Openstack LoadBalancer since it doesn't support/can't do anything with it.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure `cloud.conf`

```
[Global]
auth-url=<value>
username=<value>
password=<value>
region=<value>
tenant-name=<value>
tenant-id=<value>
```
- [Install MetalLB](https://metallb.universe.tf/installation/)
- Push a `layer2` [ConfigMap](https://metallb.universe.tf/tutorial/layer2/#configure-metallb)
- Create a [LoadBalancer](https://metallb.universe.tf/tutorial/layer2/#create-a-load-balanced-service)

**Anything else we need to know?**:

See this [issue](https://github.com/google/metallb/issues/269#issuecomment-400727870)

**Environment**:

See this [issue](https://github.com/google/metallb/issues/269#issuecomment-400727870)

### PR DESCRIPTION
**Pull request by zetaab**
**What this PR does / why we need it**: if LoadBalancer section is not defined in cloudconfig, we should not initialize loadbalancer support for openstack cloudprovider.

**Which issue(s) this PR fixes**:
Fixes #65775

**Special notes for your reviewer**:

**Release note**:
```release-note
If Openstack LoadBalancer is not defined in cloud config, the loadbalancer is not initialized any more in openstack. All setups must have some setting under that section
```

### CODE REVIEW

**Comment by zetaab** [comment]
one thing that I am thinking: is there possibility to use openstack lbaas currently with empty config? I tried to look opts in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L93-L105 and for me it looks like at least `LBProvider` should be defined to get it working?

**Review by FengyunPan2 — APPROVED** [review]
/approve

**Comment by neolit123** [comment]
/kind bug
@kubernetes/sig-cloud-provider-pr-reviews

**Pull request merged**
