### PR TITLE
[WIP] Please, don't merge this PR, testing migration of one of the prow jobs to the new cluster #94127

### PR DESCRIPTION
**Pull request by bartsmykla**
As a part of migrating one of the prow job `pull-kubernetes-e2e-gce-network-proxy-grpc` to the new cluster (more info: https://github.com/kubernetes/test-infra/issues/18853) I have to trigger this job to test and observe if everything is working as expected, so I'm opening this PR, please, don't merge it.

/cc @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
Please work on https://github.com/kubernetes/test-infra/issues/18853#issuecomment-678396071

**Comment by bartsmykla** [comment]
It looks like it works. Apologies about not being able to work on https://github.com/kubernetes/kubernetes/pull/94127#issuecomment-682988476 earlier, and I see you fixed it already

**Comment by spiffxp** [comment]
/test pull-kubernetes-e2e-gce-network-proxy-grpc
going to test a time or two more just to get some performance data

**Comment by spiffxp** [comment]
/test pull-kubernetes-e2e-gce-network-proxy-grpc
one last time

**Comment by spiffxp** [comment]
/close
https://github.com/kubernetes/test-infra/issues/18853 is closed.  I think we're done with the testing that we needed this for

**Pull request closed without merging**
