### PR TITLE
should check return err

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
It should check  errors and remove redundancy panic.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ScorpioCPH — COMMENTED** [review]
lgtm.

**Comment by stewart-yu** [comment]
cc @luxas

**Review by luxas — APPROVED** [review]
/lgtm

**Pull request merged**
