### PR TITLE
chore: Update apidiff.sh script description

### PR DESCRIPTION
**Pull request by yongruilin**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
The hack/apidiff.sh description is incorrect. This PR updated it.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Thanks! How surprising that no-one noticed (or cared) about this copy-and-paste.

**Comment by yongruilin** [comment]
> /lgtm /approve
> 
> Thanks! How surprising that no-one noticed (or cared) about this copy-and-paste.

Probably most of them are experts and don't need to read the description like me. XD

**Comment by aojea** [comment]
😅

**Pull request merged**
