### PR TITLE
Remove ioutil from controller-manager

### PR DESCRIPTION
**Pull request by inosato**
Signed-off-by: inosato <si17_21@yahoo.co.jp>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove ioutil from controller-manager.

#### Which issue(s) this PR fixes:

Fixes # NONE
Related to https://github.com/kubernetes/kubernetes/issues/100367

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @andrewsykim 
for approval

**Comment by jiahuif** [comment]
/lgtm

Should've done that a long time ago. Thank you.

**Review by andrewsykim — COMMENTED** [review]
/ok-to-test

**Comment by jiahuif** [comment]
@andrewsykim gentle ping for approval.

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
