### PR TITLE
Revert "Enable containerized storage plugins mounter on GCI"

### PR DESCRIPTION
**Pull request by gmarek**
cc @vishh 

Reverts kubernetes/kubernetes#35350

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35763)

### CODE REVIEW

**Comment by wojtek-t** [comment]
It seems that it broke all kubemark suites (which are blocking now).

The problem why we didn't catch this in presubmit is that in presubmit we are using debian not GCI. The change is already merged: https://github.com/kubernetes/test-infra/pull/945

**Comment by gmarek** [comment]
@k8s-bot kubemark test this issue: #IGNORE
Check if it works.

**Comment by gmarek** [comment]
Merging to unblock the build.

**Comment by vishh** [comment]
How is kubemark different from other e2es? This PR has passed node and cluster e2es.

**Comment by gmarek** [comment]
That's a very good question - I don't know. In kubemark we just create ordinary Pods and Secrets for HollowNodes (this is the only part that can be affected). It's really just a very simple use case of our basic objects.

**Comment by vishh** [comment]
When I tried kubemark, I see CPU availability to be an issue. Could that be
the root cause? Can we increase the node sizes?

**Comment by gmarek** [comment]
If it reduced the amount of available CPU/mem on the machine it can certainly cause kubemark failure - but how exactly this PR causes that (assuming that I understood correctly what you wrote).

**Comment by vishh** [comment]
When I tried the kubemark tests, many of the pods were unable to run due to
lack of CPU. I suspect kubemark tests are packing the nodes with a lot of
pods and thereby causing CPU starvation for the entire node. I was unable
to login to the nodes once the tests started running.

**Comment by gmarek** [comment]
OK, but how this PR affects that?

**Pull request merged**
