### PR TITLE
Manually cherrypick #65034 to 1.10

### LINKED ISSUE #64612: JSON decoders should be case sensitive
Our current json decoders are case-insensitive. Creating a deployment with a field `spec.replicAs: 3` will fail kubectl validation with:

```
error: error validating "deployment.yaml": error validating data: ValidationError(Deployment.spec): unknown field "replicAs" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

If we use `--validate=false`, the deployment configuration is accepted and the json decoder unmarshals it as `spec.replicas: 3`.

IMO we should not allow wrongly named fields even if they differ only in case sensitivity. Also, custom resources validation differs from native resources validation here because the CRD validation specs are case sensitive.

I checked for the current master, 1.10, 1.9 and 1.8. This issue persists for all of them. We started using json-iter instead of ugorji in 1.9 (https://github.com/kubernetes/kubernetes/pull/48287) so it doesn't look related to that.

Go's `json.Unmarshal`, by default, is case insensitive. From https://golang.org/pkg/encoding/json/#Unmarshal,

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. 

I suspect this is the underlying mechanism used in our json decoders which causes it to be case-insensitive. 

Wanted to make sure there is consensus in decoders being case sensitive before attempting a fix.

/cc @liggitt @thockin @sttts 
/sig api-machinery
/kind bug

### PR DESCRIPTION
**Pull request by caesarxuchao**
Manually cherrypicking #65034. Using hack/cherry_pick_pull.sh to cherrypick is difficult because that requires cherrypicking #63059 first.

This PR imported the latest jsoniterator library so that case sensitivity during unmarhsaling is optional. The PR also set Kubernetes json serializer to be case sensitive.

Fix #64612.

```release-notes
Kubernetes json deserializer is now case-sensitive to restore compatibility with pre-1.8 servers.
If your config files contains fields with wrong case, the config files will be now invalid.
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@nikhita @liggitt could you take look? We need the lgtm & approval today if it's getting into 1.10.5. Thanks.

**Comment by nikhita** [comment]
@liggitt can you add `status/approved-for-milestone`?

@MaciekPytel is the cherry pick approved?

**Comment by MaciekPytel** [comment]
/hold 
Freezing branch for 1.10.5

**Comment by MaciekPytel** [comment]
/hold cancel
/retest
Discussed offline with @caesarxuchao and it seems to be a more important fix than I initially thought. Giving this some more time.

**Comment by nikhita** [comment]
/retest

so flaky

**Comment by sttts** [comment]
@maciaszczykm we have a critical follow-up after @caesarxuchao's json PR: https://github.com/kubernetes/kubernetes/pull/65234. Please hold the release of 1.10.5 until we have that ready.

**Comment by nikhita** [comment]
@MaciekPytel ^

**Comment by sttts** [comment]
Turned out to be a false alarm. Those json tags are intentionally missing. We also double checked that we don't have other cases like that where the missing tags is a serious problem.

**Pull request merged**
