### PR TITLE
refactor watch cache metrics so that they are in a single place

### PR DESCRIPTION
**Pull request by logicalhan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Watch cache metrics are both in a subdirectory and in the watch-cache directory, this PR consolidates watch-cache metrics into a single location.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks - was on my todo list for a long time :)

**Comment by fedebongio** [comment]
thank you Han!
/triage accepted

**Pull request merged**
