### PR TITLE
Run Windows kubelet stats e2e tests serially to reduce test flakes

### PR DESCRIPTION
**Pull request by marosset**
/kind failing-test

**What this PR does / why we need it**:
These tests start 10 pods on the same Windows node and some test configs (such as https://k8s-testgrid.appspot.com/sig-windows#aks-engine-azure-windows-master-staging) which run with a high level of parallelism sometimes fail the ready check to ensure all pods are running.

This test case is running fine in test configs that have low or no parallelism.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The test case was added with #74991 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig-windows

### CODE REVIEW

**Comment by marosset** [comment]
/assign @michmike 

I've been speaking with @adelina-t and she is OK with merging with the pull-kubernetes-e2e-aks-engine-azure-windows failures because they are unrelated to this change.

**Review by michmike — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
