### PR TITLE
LoadFromFile  func got error "cert file not found"

### PR DESCRIPTION
**Pull request by xuhuilong**
**What this PR does / why we need it**:
 Fix the issue about "cert file not found" when execute "make test-e2e" ( export KUBERNETES_PROVIDER=local) . 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

if config file (/var/run/kubernetes/admin.kubeconfig) use relative path value in key client-certificate and client-key,  LoadFromFile function cannot work as expect.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xuhuilong** [comment]
@dims  ci tests are passed,  what to do next?

**Comment by fabianofranz** [comment]
@xuhuilong please squash your commits and pick a more descriptive commit message, thanks!

**Comment by xuhuilong** [comment]
@fabianofranz  Done. Would you please check it again?

**Comment by fabianofranz** [comment]
@xuhuilong I still see 2 commits and the previous commit messages, forgot to push?  ;)

**Comment by xuhuilong** [comment]
@fabianofranz  the commit id 63671e4 is clean, ee82256 commit have all changes. Is it ok? seems like I cannot remove the useless commit from current web page.

**Comment by fabianofranz** [comment]
@xuhuilong No, an empty commit is not ok. Try squashing them, it should fix the issue.

**Pull request closed without merging**
