### PR TITLE
Fix shellcheck failures of hack/verify-no-vendor-cycles.sh

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix shellcheck failures of hack/verify-no-vendor-cycles.sh

**Which issue(s) this PR fixes**:

Ref #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority backlog
/kind cleanup
/sig testing

**Review by fejta — COMMENTED** [review]
/approve

**Comment by liggitt** [comment]
revert in https://github.com/kubernetes/kubernetes/pull/77841

**Pull request merged**
