### PR TITLE
dualstack: cleanup IsIPv4 duplicates in favor of k8s/utils functions

### PR DESCRIPTION
**Pull request by cmluciano**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This dependency bump will allow for cleanup of duplicate code in
the dualstack e2e tests.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cmluciano** [comment]
cc @aojea

**Comment by cmluciano** [comment]
/assign @thockin 
Since he approved the [k8s/utils patch](https://github.com/kubernetes/utils/pull/195)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
