### PR TITLE
Update toplogy keyset initialization

### PR DESCRIPTION
**Pull request by peaaceChoi**
#### What type of PR is this?
/sig storage
/kind cleanup

#### What this PR does / why we need it:
Improved code consistency and maintenance.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note 
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by peaaceChoi** [comment]
Hello, Any chances for review?

**Comment by jsafrane** [comment]
/retest
`TestChangeCRD` flake

**Pull request merged**
