### PR TITLE
Move regexp.MustCompile to global variable

### PR DESCRIPTION
**Pull request by sergeylanzman**
Move regexp.MustCompile to global variable.
regexp.MustCompile heavy function and can be run on init app
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Verify error is legitimate. Code needs a gofmt.

**Review by rphillips — APPROVED** [review]

**Comment by cblecker** [comment]
@sergeylanzman PR needs rebase still

**Comment by cblecker** [comment]
@sergeylanzman You need to actually rebase and resolve, not use a merge commit. This will not be mergeable
/hold

**Pull request merged**
