### PR TITLE
Add supported SC parameters to the SC example yaml file.

### PR DESCRIPTION
**Pull request by humblec**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by brendandburns** [comment]
What does this fix?

**Comment by humblec** [comment]
@brendanburns this is just to update the example yaml file with the supported storage class options. This is referred by some and they miss these available options as its not present in the example yaml. The PR try to keep the example yaml updated with the newly/recently added options.

**Comment by brendandburns** [comment]
I'm no expert here, I defer to @eparis I'm happy to approve once it's LGTM'd

**Comment by humblec** [comment]
@brendanburns nw, thanks :). @eparis Can you please review this PR?

**Comment by humblec** [comment]
Thanks Eric!

**Pull request merged**
