### PR TITLE
fix patch compare in sample-controller test

### PR DESCRIPTION
**Pull request by krzyzacy**
/release-note-none
/sig testing
/assign @munnerz @gregory-m

### CODE REVIEW

**Comment by nikhita** [comment]
@krzyzacy Thanks for catching that!

/release-note-none
/kind bug
/retest

/lgtm

/assign @munnerz 
for approval

**Comment by gregory-m** [comment]
@krzyzacy thanks for spotting this. 
 
Despite this is my code I can't approve this because I'am not k8s member. But its /lgtm.

**Pull request merged**
