### PR TITLE
randomize index from where round-robin starts in kube-proxy userspace load-balancer

### PR DESCRIPTION
**Pull request by ArtfulCoder**
If we have clients of kubernetes service that hold a persistent connection, then it is quite likely that the replicas of that client on various cluster nodes will all hit the same endpoint.

This change adds some randomness that should help in such situations

### CODE REVIEW

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/roundrobin.go#L270

How is this different?

**Comment by ArtfulCoder** [comment]
@thockin 
ShuffleStrings is not really random because we don't seed it.
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/slice/slice.go#L42
https://golang.org/pkg/math/rand/#pkg-overview

The cleaner/easier fix would be to have a new implementation a truly random ShuffleStrings function.

**Comment by thockin** [comment]
I think we're assuming that SOMONE seeded it, but we could always re-seed
it, I guess, or keep our own radomizer which we seed in init() or something.

**Comment by ArtfulCoder** [comment]
Yes, it is safest to seed it ourselves.
Also, the seed should be different on every machine. We can use current time in nanoseconds for that.

I can complete this change, but do you care about it given that we are moving to iptables-based version ?

**Comment by thockin** [comment]
If it's an easy fix, go for it, but mostly because this is a generic lib.

**Comment by ArtfulCoder** [comment]
Closing PR. created a new one to take care of this. #13755

**Pull request closed without merging**
