### PR TITLE
Move NodeResourcesFit plugin args validation to apis/config/validation

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Part of: https://github.com/kubernetes/kubernetes/issues/88093

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by Huang-Wei** [comment]
LGTM still.

**Pull request merged**
