### PR TITLE
Remove deprecated stale flags of kube-apiserver

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
These flags have been marked as deprecated for more than two years. This PR removes them.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: #8740

**Special notes for your reviewer**:

**Release note**:

```release-note
action required: Deprecated flags `--portal-net` and `service-node-ports` of kube-apiserver are removed.
```

### CODE REVIEW

**Comment by enj** [comment]
The change seems reasonable but I do not know the process for deleting deprecated flags.

@kubernetes/api-approvers

**Comment by xiangpengzhao** [comment]
@enj FYI: https://kubernetes.io/docs/reference/deprecation-policy/

```
Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:
GA: 6 months or 1 release (whichever is longer)
Beta: 3 months or 1 release (whichever is longer)
Alpha: 0 releases
```

**Comment by xiangpengzhao** [comment]
/assign @liggitt
Thanks!

**Comment by bgrant0607** [comment]
If @mtaufen is fine with this, I am

**Comment by bgrant0607** [comment]
Oops, this is an apiserver one. @lavalamp

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-api-machinery-pr-reviews

**Pull request merged**
