### PR TITLE
Remove obsolete munger on docs

### LINKED ISSUE #29682: Eliminate unversioned document warning
https://github.com/kubernetes/kubernetes/blob/master/cmd/mungedocs/unversioned_warning.go

This warning is no longer necessary. User-facing docs are in kubernetes.github.io.

We should strip the warning from docs in this repo and eliminate the munger.

cc @Kashomon

### PR DESCRIPTION
**Pull request by thockin**
The only docs left in master branch are devel docs.

Fixes #29682

@kubernetes/contributor-experience

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35546)

### CODE REVIEW

**Comment by thockin** [comment]
@mikedanese verify-bazel is failing...

**Comment by jessfraz** [comment]
PRETTY +0 −10,372

**Comment by spxtr** [comment]
Does it still fail after running update_bazel? It has a reference to unversioned_warning in the cmd/mungedocs build file that I think you've changed.

**Comment by bgrant0607** [comment]
cc @grodrigues3 @pwittrock

**Comment by bgrant0607** [comment]
Updated PR to fix #29682

@grodrigues3 Is there still a reason we can't delete the markdown files in docs/user-guide, docs/admin, and docs/getting-started-guides?

**Comment by bgrant0607** [comment]
Also FYI @david-mcmahon

**Comment by mikedanese** [comment]
Hmm looks like you figured it out. was it a real validation error? If not i can look into it.

**Comment by eparis** [comment]
You'll never beat the bot and will have to use the big green merge button (or maybe this kills enough we can turn off the bot...)

**Comment by thockin** [comment]
bazel was because I removed a go file and forgot to update BUILD.  This is
why checking in generated files is a bad idea.

**Comment by thockin** [comment]
just waiting for LGTM.  whoeever LGTMs should just manually merge it.

**Comment by grodrigues3** [comment]
@jeffmendoza When we last spoke about removing user-guide, admin, getting-started-guides directories, I think you had indicated it wasn't a good idea since links may still point at them.  What do we need to do in order to be able to safely remove them?

cc @bgrant0607

**Comment by jeffmendoza** [comment]
@grodrigues3 True, this PR leaves all those with "This file has moved to: ..." Sounds great. I still think there are probably many devel docs that use relative links to link to those docs. Of course we don't know about external sites, historical blog posts, etc. that link to the github docs links in this repo.

**Comment by bgrant0607** [comment]
LGTM. Thanks!!!!

**Comment by bgrant0607** [comment]
@jeffmendoza @grodrigues3 I think it's been long enough that we can declare bankruptcy on the doc placeholders in this repo.

**Pull request merged**
