### PR TITLE
Move celopenapi/model to staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/

### LINKED ISSUE #108346: Move CEL openapi integration code out of third_party/forked/celopenapi/model/registry.go
We've made enough changes to the code in staging/src/k8s.io/apiextensions-apiserver/third_party/forked/celopenapi/model, that it's not really helpful to think of it as forked code.

More practically, having [gofmt disabled](https://github.com/kubernetes/kubernetes/blob/3213a92802b91ed718578f51b14916105fb0c3da/hack/verify-gofmt.sh#L44) make it inconvenient.

I'd like to move it out of third_party and into something like staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model.

### PR DESCRIPTION
**Pull request by mk46**
#### What type of PR is this?
Move `celopenapi/model` to `staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/`

Add one of the following kinds:
/kind cleanup

Optionally add one or more of the following kinds if applicable:

/area code-organization

#### Which issue(s) this PR fixes:

Fixes #108346

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
I'm supportive of this change. We've almost entirely rewritten this code at this point.

@jiahuif Do you have any concerns with this code move? I don't expect it to impact the work you are doing but wanted to double check.

I don't see any particularly obvious problem with the license file changes since we're retaining the same license. But if anyone with expertise on that could weight in, that would be helpful.

**Comment by mk46** [comment]
Getting warning from go-lint

```
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model/schemas.go:45:2: const `minTimeSizeJSON` is unused (unused)                 
        minTimeSizeJSON = 5                                                                                                                           
        ^                                                                                                                                             
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model/types.go:472:22: func `(*RuleTypes).convertToCustomType` is unused (unused) 
func (rt *RuleTypes) convertToCustomType(dyn *DynValue, declType *DeclType) *DynValue { 

```
Should I remove both in order to make go-lint happy?

**Comment by jpbetz** [comment]
> Getting warning from go-lint
> 
> 
> 
> ```
> 
> staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model/schemas.go:45:2: const `minTimeSizeJSON` is unused (unused)                 
> 
>         minTimeSizeJSON = 5                                                                                                                           
> 
>         ^                                                                                                                                             
> 
> staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model/types.go:472:22: func `(*RuleTypes).convertToCustomType` is unused (unused) 
> 
> func (rt *RuleTypes) convertToCustomType(dyn *DynValue, declType *DeclType) *DynValue { 
> 
> 
> 
> ```
> 
> Should I remove both in order to make go-lint happy?

Yes. Linter errors are expected as part of this code move since the linters are disabled for third_party directories. Removing unused unexported code is safe.

**Comment by mk46** [comment]
@jiahuif  @logicalhan Hi, 
      Please take a look.
      Thanks!!

**Comment by dims** [comment]
@mk46 do you still need this? please rebase if so, else we can close it out

**Comment by mk46** [comment]
> @mk46 do you still need this? please rebase if so, else we can close it out

PTAL

**Review by jpbetz — APPROVED** [review]
/lgtm

**Comment by jpbetz** [comment]
@TristonianJones are you okay with this change from an attribution perspective? We're changed it a lot, to the point that it wouldn't be practical to rebase. And moving it out of third_party enables linting, which is desirable.

**Comment by TristonianJones** [comment]
@jpbetz I'm happy that what I did could serve as an inspiration and give an idea that developed into its own full-fledged offering. Please feel free to change the attribution with my blessing. :)

**Comment by jpbetz** [comment]
Thanks @TristonianJones!

/assign @lavalamp

This is ready for approval

**Comment by liggitt** [comment]
> @jpbetz I'm happy that what I did could serve as an inspiration and give an idea that developed into its own full-fledged offering. Please feel free to change the attribution with my blessing. :)

Thanks, looks like there was one additional author on a couple commits in that package in https://github.com/google/cel-policy-templates-go/commits/master/policy/model. It would be good to get their ack as well.

I'm not sure the best way to capture what is effectively re-contributing the same code to this project under the Kubernetes license. At the very least, I'd like to have something captured in the commit itself and not just a github comment.

**Comment by liggitt** [comment]
(mechanical change lgtm)

**Comment by jpbetz** [comment]
@jinmmin would you be willing to add a comment here that it's okay to relicense the contributions you've made to https://github.com/google/cel-policy-templates-go/commits/master/policy/model to the Kubernetes project? We've forked a small section of code from cel-policy-templates. We will add some notes in the commit history to try to retain some attribution. Thanks!

**Comment by jinmmin** [comment]
> @jinmmin would you be willing to add a comment here that it's okay to relicense the contributions you've made to https://github.com/google/cel-policy-templates-go/commits/master/policy/model to the Kubernetes project? We've forked a small section of code from cel-policy-templates. We will add some notes in the commit history to try to retain some attribution. Thanks!

@jpbetz, these commits are part of cel-policy-templates, so if the owner @TristonianJones is fine with the change, I have no objection :).

**Pull request merged**
