### PR TITLE
Create an unversioned client and move everyone to it

### PR DESCRIPTION
**Pull request by krousey**
#4874

Create an unversioned client and move everyone to it so we can create a v1 right next to it and gradually switch everyone over to it.

### CODE REVIEW

**Comment by krousey** [comment]
cc @caesarxuchao @bgrant0607

**Comment by krousey** [comment]
@eparis @thockin @lavalamp @mikedanese 

This doesn't seem right. Shippable and Travis are failing on `hack/verify-generated-docs.sh`. If I run the script, it produces this diff. It seems like `updateLinks` in the munger is discarding links for some reason. Maybe related to @eparis's restructuring? Or maybe when @mikedanese moved the org? Any ideas? Or is this right?

```diff
diff --git a/docs/design/event_compression.md b/docs/design/event_compression.md
index 1187edb..7395982 100644
--- a/docs/design/event_compression.md
+++ b/docs/design/event_compression.md
@@ -60,7 +60,7 @@ Instead of a single Timestamp, each event object [contains](http://releases.k8s.
 
 Each binary that generates events:
  * Maintains a historical record of previously generated events:
-   * Implemented with ["Least Recently Used Cache"](https://github.com/golang/groupcache/blob/master/lru/lru.go) in [`pkg/client/record/events_cache.go`](../../pkg/client/record/events_cache.go).
+   * Implemented with ["Least Recently Used Cache"](https://github.com/golang/groupcache/blob/master/lru/lru.go) in .
    * The key in the cache is generated from the event object minus timestamps/count/transient fields, specifically the following events fields are used to construct a unique key for an event:
      * `event.Source.Component`
      * `event.Source.Host`
diff --git a/docs/proposals/apiserver_watch.md b/docs/proposals/apiserver_watch.md
index a731c7f..5650713 100644
--- a/docs/proposals/apiserver_watch.md
+++ b/docs/proposals/apiserver_watch.md
@@ -172,7 +172,7 @@ the same time, we can introduce an additional etcd event type:
   Thus, we need to create the EtcdResync event, extend watch.Interface and
   its implementations to support it and handle those events appropriately
   in places like
-  [Reflector](../../pkg/client/cache/reflector.go)
+  
 
        However, this might turn out to be unnecessary optimization if apiserver
        will always keep up (which is possible in the new design). We will work
```

**Comment by krousey** [comment]
Nevermind... Files were renamed... need to fix links.

**Comment by bgrant0607** [comment]
Probably some stuff was moved that didn't need to be moved (e.g., clientauth), but I'm ok with moving everything and factoring out common code later.

**Comment by bgrant0607** [comment]
Did the link munger not correctly fix the links?

**Comment by eparis** [comment]
It possible I broke the link munger and it is somehow removing links.  Would be really bad.  Is this reproducible?

**Comment by caesarxuchao** [comment]
The move LGTM.

**Comment by krousey** [comment]
@bgrant0607 The link munger deleted the links to the files that no longer existed (because I moved them). This confused me. Then I realized why and went back and corrected the links so the munger wouldn't try to remove them.

**Comment by bgrant0607** [comment]
LGTM

**Comment by jszczepkowski** [comment]
Please rebase.

**Comment by brendandburns** [comment]
LGTM was before last commit, removing LGTM

**Comment by brendandburns** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by brendandburns** [comment]
Needs rebase.

**Comment by roberthbailey** [comment]
Removing lgtm label until this is rebased. @bgrant0607 please add it back once this has been rebased and you verify that it still looks good.

**Comment by bgrant0607** [comment]
LGTM.

@roberthbailey Please merge this before anything else in order to avoid another rebase.

**Pull request merged**
