### PR TITLE
Automated cherry pick of #62308: Add support to resize Portworx volume

### PR DESCRIPTION
**Pull request by harsh-px**
Cherry pick of #62308 on release-1.10.

#62308: Add support to resize Portworx volume

### CODE REVIEW

**Comment by harsh-px** [comment]
@derekwaynecarr / @rootfs this is a cherry-pick for the approved PR #62308. Can you approve this?

**Comment by harsh-px** [comment]
@rootfs / @saad-ali can you help get this PR approved?

**Comment by MaciekPytel** [comment]
Patch releases are generally limited to fixing bugs, security issues, etc. However, this PR seems to be adding a new feature, rather than fixing anything. @harsh-px Can you provide some context on why do we need to cherry-pick this?

**Comment by harsh-px** [comment]
@MaciekPytel The change was isolated to just the Portworx driver implementation and hence I was hoping to get this cherry picked.

**Comment by brokenmass** [comment]
@MaciekPytel @childsb any updates on this ? i would love to see this land in 1.10

**Comment by MaciekPytel** [comment]
@saad-ali @childsb Can you state your opinion on this so we can merge or close this cherry-pick?

**Comment by harsh-px** [comment]
@saad-ali @childsb Sorry just checking in if you had a chance to review this?

**Comment by venkatpx** [comment]
@saad-ali @childsb can we get help with this and merge it into 1.10 please?

**Comment by saad-ali** [comment]
@harsh-px We normally do not cherry pick PRs adding new functionality to previous branches only bug and security fixes. If we want an exception to this we will have to ask the 1.10 branch owner.

**Comment by MaciekPytel** [comment]
This has failed to get approval for over half a year and with 1.10 support coming to end I'm closing the PR.

**Pull request closed without merging**
