### PR TITLE
remove the disabled dashboard test

### LINKED ISSUE #62709: Failing Test: [sig-ui] Kubernetes Dashboard should check that the kubernetes-dashboard instance is alive
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=ui&test=Kubernetes%20Dashboard%20should%20check%20that%20the%20kubernetes-dashboard%20instance%20is%20alive

Started failing since 4/9. [Commit Changes](https://github.com/kubernetes/kubernetes/compare/68f0fc411...edfef170b)

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @floreks   can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig ui

cc @jberkus @tpepper 

/assign @floreks

### PR DESCRIPTION
**Pull request by krzyzacy**
fixes https://github.com/kubernetes/kubernetes/issues/62709

per https://github.com/kubernetes/kubernetes/issues/62709#issuecomment-382290511, since this is the only test I'm simply remove the entire `ui/` subdir here.

/sig ui
/assign @AishSundar @bryk

### CODE REVIEW

**Comment by krzyzacy** [comment]
humm, @ixdy - why update-bazel does not remove the go library reference here? (aka my 3rd commit)

**Comment by krzyzacy** [comment]
awh nvm there's more dependencies

**Comment by ixdy** [comment]
/hold

The dashboard addon is disabled for GKE, but is it disabled everywhere?

We already skip this test on GKE:
https://github.com/kubernetes/kubernetes/blob/3856891198653566c1c95d94b3fcf7e866f0bb50/test/e2e/ui/dashboard.go#L36-L39
but that change is recent and may not have been backported, hence the upgrade test failures.

**Comment by krzyzacy** [comment]
sounds like a question for @bryk ^^

**Comment by AishSundar** [comment]
/cc @bryk

@bryk can you help clarify @ixdy's ques above

**Comment by MaciekPytel** [comment]
The test is still failing on 1.10, because the test is only skipped on GKE on master. Can we cherry-pick this PR https://github.com/kubernetes/kubernetes/pull/61560 to 1.10? @apelisse @bryk

**Comment by krzyzacy** [comment]
@apelisse so this test is still suppose to run on other providers?

**Comment by apelisse** [comment]
That's my understanding yes.

**Comment by krzyzacy** [comment]
ack, then let's cherrypick #61560

**Pull request closed without merging**
