### PR TITLE
Tighten validation of Name and Namespace

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Gonna break people's examples.... :)

Maybe we should make this land right at the beginning of 0.9?

**Comment by thockin** [comment]
I fixed all the in-tree examples :)

I am fine with letting this sit for a while, but I think that v1b3 should enforce these rules from day 1 (of it's own "real" lifetime).

**Comment by smarterclayton** [comment]
Agreed - can you throw that on 1519?

----- Original Message -----

**Comment by thockin** [comment]
Done

**Comment by derekwaynecarr** [comment]
What would break in actual examples?  We auto-populate namespace from the request context on server side.  Maybe I am missing something.

**Comment by thockin** [comment]
This also changed validation of ReplicationController, which used to allow
bumpyCaps, but now will not.

**Comment by derekwaynecarr** [comment]
Thanks.  Late night code reviews on a phone can cause me to miss that change.

**Comment by bgrant0607** [comment]
We're also still not validating annotations, AFAIK. /cc @markturansky

**Comment by thockin** [comment]
Is there an open issue for validating annotations?  It should be easy to
add, it's just a matter of sprinkling it about and then testing

**Comment by smarterclayton** [comment]
Let me know when you do so I can test it against the openshift annotations... we have some... large... annotations.

----- Original Message -----

**Comment by smarterclayton** [comment]
Random note (not something you have to do here), we should make a validation test util that makes this easier - i.e. a public struct that says runtime.Object, function that invokes validation, errors I expect, and encourage bits of stuff like `ValidateObjectReference(*api.ObjectReference, allowedTypes []string)`.  We also need to do conversion of embedded Kind fields automatically through the rest API (so v1beta1 returns "Minion" for an ObjectReference kind, but v1beta3 returns "Node").  Yet more work to make pod templates right....

**Comment by markturansky** [comment]
@bgrant0607 See #3788.  Sorry, that fell off my radar for no good reason.

**Comment by smarterclayton** [comment]
I'm going to build off this with #3789

**Comment by smarterclayton** [comment]
I'm going to move this inside a new ValidateObjectMeta

**Comment by thockin** [comment]
We will need to expand service and namespace names to make that feasible.

**Comment by thockin** [comment]
Obsolete

**Pull request closed without merging**
