### PR TITLE
Prevent use of ":latest" or untagged gcr.io images 

### PR DESCRIPTION
**Pull request by janetkuo**
Ref #20836
[Analytics]()

### CODE REVIEW

**Comment by fejta** [comment]
This is cool!

It is not clear to me however how we are going to enforce that this doesn't regress?

**Comment by janetkuo** [comment]
@fejta This script will be run by `hack/verify-all.sh` automatically. You can see this check in "Jenkins unit/integration" log: 
```
Verifying ./hack/../hack/verify-test-images.sh
SUCCESS  ./hack/../hack/verify-test-images.sh	0s
```

**Comment by janetkuo** [comment]
@fejta oh, should I add this script explicitly to `hooks/pre-commit`?

**Comment by fejta** [comment]
Nah, if it runs in PR jenkins then things are all good!

**Comment by bprashanth** [comment]
nice!

**Pull request merged**
