### PR TITLE
(WIP) Cassandra cleanup

### PR DESCRIPTION
**Pull request by chrislovecnm**
**What this PR does / why we need it**:

Cleaning up Cassandra examples, and removing older examples.  Moving to a community supported container so that we can update the example w/o having googlers upload the container. 

**Release note**:
None 

**TODO**:

- [ ] more testing
- [ ] update container to a version number and not use latest

### CODE REVIEW

**Comment by thockin** [comment]
You have to fix tests

**Comment by chrislovecnm** [comment]
@thockin fix tests?  More context please.

**Comment by thockin** [comment]
Bazel and Jenkins unit tests both failed.

**Comment by chrislovecnm** [comment]
Yes ... absolutely

**Comment by thockin** [comment]
YOu need toopen an issue that this can close in the first comment, or the approval won't stick.

**Comment by chrislovecnm** [comment]
I am keeping this open to remind me to flip this over to examples repo

**Comment by chrislovecnm** [comment]
Closing because we have https://github.com/kubernetes/examples/pull/13

**Pull request closed without merging**
