### PR TITLE
Fix v1.4.0-alpha.0 tag

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes the v1.4.0-alpha.0 tag.

cc @kubernetes/release-maintainers @lavalamp

### CODE REVIEW

**Comment by eparis** [comment]
/me doesn't understand how a PR with 0 changes fixes something...

**Comment by zmerlynn** [comment]
Hold. This was fine, then I rebased. :P

**Comment by lavalamp** [comment]
Yeah, I don't know if you can put tags in a PR. You might have to push manually...

**Comment by zmerlynn** [comment]
The first commit is actually a merge commit (GitHub is showing it weirdly), so this would go in as a double merge commit.

**Comment by eparis** [comment]
ok, makes sense I guess...  I'll check it out in git.

**Comment by lavalamp** [comment]
I pulled this from the command line, and it doesn't seem to change the tag.

**Comment by eparis** [comment]
The tag is on fd1377a16b5e2e33f24a57848071616c81a7f58f until we move it...   Now fd1377a16b5e2e33f24a57848071616c81a7f58f will show 2 places in the history, but both are going to have the versionized docs...

**Comment by zmerlynn** [comment]
There, that should be good, in theory. If the double-merge messes it up, I can push it manually later. The steps to create this were:

```
git checkout -b fix-1-4-tag upstream/master
git merge "Redo v1.4.0-alpha.0" HEAD v1.4.0-alpha.0
git revert -m1 c7f1485e1b3491e98f102c30e7e342cb53dda818
```

@eparis: fd1377a16b5e2e33f24a57848071616c81a7f58f just isn't in history :/

**Comment by eparis** [comment]
@zmerlynn yup, just checked it, now it shows up once in history. +1 to this PR.

**Comment by zmerlynn** [comment]
@lavalamp: How did you test it, and do you have the `v1.4.0-alpha.0` tag fetched?

```
$ test_pull 27366
From https://github.com/kubernetes/kubernetes
 * [new ref]         refs/pull/27366/head -> test_pull_27366_1465920357
Switched to branch 'test_pull_27366_1465920357'
$ git describe 
v1.4.0-alpha.0-160-gf49c976
```

**Comment by eparis** [comment]
`git fetch --all --tags`

**Comment by lavalamp** [comment]
OK. Tested again. Worked!

**Comment by lavalamp** [comment]
Any reason not to just merge this? (I'm the build cop)

**Comment by eparis** [comment]
click the big green button.  (well, it's red right now, but still)

**Comment by zmerlynn** [comment]
No, I'd go for it. I just glanced at the last PR builder instance that was running, and it tested it as well: `Found Kubernetes version: v1.4.0-alpha.0.161+82a78c8930be2a`

**Comment by zmerlynn** [comment]
So I'd say we have consensus!

**Comment by lavalamp** [comment]
Merged. Thanks @zmerlynn!!

**Comment by zmerlynn** [comment]
Sweet, and fix confirmed after merge. :)

**Pull request merged**
