### PR TITLE
Support gcloud rolling-update command in 'preview' and 'alpha compute'

### PR DESCRIPTION
**Pull request by mbforbes**
Fixes current "Restart" breakage for GKE

### CODE REVIEW

**Comment by mbforbes** [comment]
Notes:
- I tested both the go and bash code locally (where I have the "alpha compute")
- This seemed better than plumbing another arg all the way through the e2e pipeline (and possibly adding it to a bunch of jobs). We can remove this in a week, or keep it around for the alpha/beta, etc. transition(s).
- This raises a few other issues (we shouldn't be running "Restart;" "Restart" itself is currently actually a no-op; we need better debugging) that I'll address soon after this.

+cc @roberthbailey

**Comment by mbforbes** [comment]
Weird failure in Jenkins (seems unrelated to this change):

```
STEP: successfully translated pod names to ips: map[podname1:[100]] -> map[10.245.1.33:[100]] on namespace e2e-tests-service-0-95f1s
STEP: Successfully validated that service multi-endpoint-test in namespace e2e-tests-service-0-95f1s exposes endpoints map[podname1:[100]] (10.053632824s elapsed)
STEP: Adding pod podname2 in namespace e2e-tests-service-0-95f1s
STEP: Waiting up to 1m0s for service multi-endpoint-test in namespace e2e-tests-service-0-95f1s to expose endpoints map[podname1:[100] podname2:[101]]
INFO: Found endpoints &{{ } {multi-endpoint-test  e2e-tests-service-0-95f1s /api/v1/namespaces/e2e-tests-service-0-95f1s/endpoints/multi-endpoint-test 817d84cc-316a-11e5-a554-42010af07df4 2301 0 2015-07-23 11:42:01 -0700 PDT <nil> map[] map[]} [{[{10.245.1.33 0xc2082195e0}] [{portname1 100 TCP}]}]}
INFO: Found IP 10.245.1.33 and port 100
INFO: Found ports by ip map[10.245.1.33:[100]]
INFO: Unexpected number of endpoints: found map[10.245.1.33:[100]], expected map[podname1:[100] podname2:[101]] (23.918242ms elapsed, ignoring for 5s)
INFO: Found endpoints &{{ } {multi-endpoint-test  e2e-tests-service-0-95f1s /api/v1/namespaces/e2e-tests-service-0-95f1s/endpoints/multi-endpoint-test 817d84cc-316a-11e5-a554-42010af07df4 2301 0 2015-07-23 11:42:01 -0700 PDT <nil> map[] map[]} [{[{10.245.1.33 0xc208219d50}] [{portname1 100 TCP}]}]}
INFO: Found IP 10.245.1.33 and port 100
INFO: Found ports by ip map[10.245.1.33:[100]]
INFO: Unexpected number of endpoints: found map[10.245.1.33:[100]], expected map[podname1:[100] podname2:[101]] (5.055159127s elapsed, ignoring for 5s)
INFO: Found endpoints &{{ } {multi-endpoint-test  e2e-tests-service-0-95f1s /api/v1/namespaces/e2e-tests-service-0-95f1s/endpoints/multi-endpoint-test 817d84cc-316a-11e5-a554-42010af07df4 2301 0 2015-07-23 11:42:01 -0700 PDT <nil> map[] map[]} [{[{10.245.1.33 0xc2082b45b0}] [{portname1 100 TCP}]}]}
INFO: Found IP 10.245.1.33 and port 100
INFO: Found ports by ip map[10.245.1.33:[100]]
INFO: Unexpected number of endpoints: found map[10.245.1.33:[100]], expected map[podname1:[100] podname2:[101]] (10.063861312s elapsed, ignoring for 5s)
INFO: Found endpoints &{{ } {multi-endpoint-test  e2e-tests-service-0-95f1s /api/v1/namespaces/e2e-tests-service-0-95f1s/endpoints/multi-endpoint-test 817d84cc-316a-11e5-a554-42010af07df4 2301 0 2015-07-23 11:42:01 -0700 PDT <nil> map[] map[]} [{[{10.245.1.33 0xc2082b4d90}] [{portname1 100 TCP}]}]}
INFO: Found IP 10.245.1.33 and port 100
INFO: Found ports by ip map[10.245.1.33:[100]]
INFO: Unexpected number of endpoints: found map[10.245.1.33:[100]], expected map[podname1:[100] podname2:[101]] (15.075209868s elapsed, ignoring for 5s)
...

• Failure [115.829 seconds]
Services
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:822
  should serve multiport endpoints from pods [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:231

  Timed out waiting for service multi-endpoint-test in namespace e2e-tests-service-0-95f1s to expose endpoints map[podname1:[100] podname2:[101]] (1m0s elapsed)

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:971

```

Either a true regression elsewhere or a flake... let me run again to check against flakes.

**Comment by mbforbes** [comment]
@k8s-bot test this please

**Comment by roberthbailey** [comment]
LGTM and makes me really wish that gcloud did a better job of backwards compatibility while moving commands around. :/

**Comment by mbforbes** [comment]
Ah crap wait, classic bash error

**Comment by mbforbes** [comment]
`exists` &rarr; `"${exists}"`

**Pull request merged**
