### PR TITLE
cassandra: update replica count to 1 to match tutorial text

### PR DESCRIPTION
**Pull request by cgilling**
I noticed that the replica count was wrong (i.e. didn't match the actual text/flow) as I was reading through the tutorial. Hope its okay to make this pull request without and issue first since its just small fix.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bprashanth** [comment]
Can you verify that this yaml isn't used in test-cmd.sh?

**Comment by cgilling** [comment]
I looked through `test-cmd.sh` and didn't see it referenced, the only references to cassandra are in this block: https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L1648, and that is just `cassandra.yaml` and `cassandra-service.yaml`

**Comment by amygdala** [comment]
I think this may have been since addressed -- see if a rebase renders it unnecessary.

**Comment by cgilling** [comment]
You're right, the README.md has been change to use 2 replicas initially and then scale to 4, so this patch is no longer needed

**Pull request closed without merging**
