### PR TITLE
tests: Lowers the number of pods returned by estimateMaximumPods

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind flake

/sig testing
/sig windows
/sig apps

#### What this PR does / why we need it:

The Conformance test "should orphan pods created by rc if delete options say so" is spawning 80% of the Cluster's Pod Capacity (on a 2 node setup, with 30 Pods capacity each, it spawns 48 pods).

Because of this, tests that are running in parallel with this test has a higher chance to flake, causing them to timeout because they didn't get to spawn the necessary Pods within the expected 1 minute time.

Lowering the percentage should reduce the amount of flakes we see.

Sample test failures caused by running in parallel with this test can be seen here: https://github.com/kubernetes/kubernetes/issues/106750

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/issues/106750

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Hi @claudiubelu , thanks for looking into the issue. 

Changing the test to [serial] will affect how often the test is running. A few test suites ignores `[serial]` tests as running them are time consuming. I will avoid making a test `[serial]` if possible.

I haven't verified but I think there are more conformance tests that create a large amount of pods. Why does the test cluster only have 2 nodes and allow only 30 pods per node?

**Comment by claudiubelu** [comment]
> Hi @claudiubelu , thanks for looking into the issue.
> 
> Changing the test to [serial] will affect how often the test is running. A few test suites ignores `[serial]` tests as running them are time consuming. I will avoid making a test `[serial]` if possible.
> 
> I haven't verified but I think there are more conformance tests that create a large amount of pods. Why does the test cluster only have 2 nodes and allow only 30 pods per node?

Hello,

That's the typical setup for the Windows test runs (1 Linux controller + 2 Windows worker nodes) as seen on the many jobs in the sig-windows testgrid [1]. And the issue isn't the 30 pods per node limit, the test will just always spawn 80% of the total capacity (up to 100, as defined in the test itself). So, increasing that pod capacity will result in more pods being spawned, which actually might result in even more flakes (most tests timeout after 1 minute, and spawning Windows pods takes more time than to spawn Linux pods, and the sudden increase of pods that needs to be spawned at the same time doesn't help).

Alternatively, we could lower the number of pods being spawned, to just 40-50% of the total Pod Capacity (which wouldn't prevent flakes from happening, but would make them a lot rarer), or an idea would be to scale up to that number of pods over time (for example, spawning 25% of the pods at a time).

Even if we'd go with the 2nd option, I'd still like to reduce the number of pods a bit. Tests are still being run in parallel, and having them split the remaining 12 Pod Capacity among them can be problematic, especially since some tests spawn 3 or more pods.

[1] https://testgrid.k8s.io/sig-windows

**Comment by caesarxuchao** [comment]
Thanks for the details.

Changing `estimateMaximumPods to return 50% of the max pods sounds ok.

Just curious, do you see other tests that spawn many pods?

**Comment by claudiubelu** [comment]
> 

Looking at the the tests in ``garbage_collector.go`` file, yes, there are a few other Conformance tests that are using the ``estimateMaximumPods`` function. These are all the tests that use that function:

```
should orphan pods created by rc if delete options say so
should keep the rc around until all its pods are deleted if the deleteOptions says so
should not delete dependents that have both valid owner and owner that's waiting for dependents to be deleted
```

All 3 of those tests calls the ``estimateMaximumPods`` function, which will return 80% of the currently allocatable number of pods, so the odds other tests running in parallel with one of those tests is higher than I expected.

Other than that, mostly replicaset / replication controller / stateful set / deployment tests typically spawn more than 1 pod. Then, quite a few networking / DNS tests spawn 3 pods, the guestbook application test spawns 6 pods, some Pod preemption tests spawns multiple pods (for example, ``validates basic preemption works`` spawns 2 pods per node).

Other than that, there are a few other Non-Conformance tests that spawns quite a few pods that we'd have to keep in mind if they're ever promoted to Conformance:

```
[sig-node] kubelet Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.
[sig-node] Kubelet [Serial] [Slow] regular resource usage tracking [Feature:RegularResourceUsageTracking] resource tracking for 100 pods per node
[sig-node] Kubelet [Serial] [Slow] experimental resource usage tracking [Feature:ExperimentalResourceUsageTracking] resource tracking for 100 pods per node
[sig-node] Pod garbage collector [Feature:PodGarbageCollector] [Slow] should handle the creation of 1000 pods
```

**Comment by aojea** [comment]
I didn't dig deeper, but is not the problem that the tests are not taking into consideration the number of pods already scheduled?

It can fluctuate with the number of tests, but a cluster may have a significant amount of pods already running, I think we should:
1. get current number of running pods
2. estimate the number of pods that can run in the cluster
3. obtain the number of the pods for the test based on the remaining capacity + some room (other tests that may run in parallel )

**Comment by claudiubelu** [comment]
> 



> I didn't dig deeper, but is not the problem that the tests are not taking into consideration the number of pods already scheduled?
> 
> It can fluctuate with the number of tests, but a cluster may have a significant amount of pods already running, I think we should:
> 
>     1. get current number of running pods
> 
>     2. estimate the number of pods that can run in the cluster
> 
>     3. obtain the number of the pods for the test based on the remaining capacity + some room (other tests that may run in parallel )


1. Technically, ``estimateMaximumPods``, takes into account the number of allocatable pods on nodes [1], and I think that was supposed to be based on how many pods are currently running on that node, but at least in my env that number doesn't seem to change, no matter how many pods I have on that node, it always remains at the Capacity value. I wonder if there's something wrong in my env, or it's a bug. But yeah, getting a real number pods would help.

2. We can use the already defined Node Pod Capacity for that.

3. Indeed, that's what ``estimateMaximumPods`` already does, and it returns 80% of that capacity. This PR currently proposes to lower the percentage to 50%.

[1] https://github.com/kubernetes/kubernetes/blob/f6243782d0e0ab69e717ac6122991934e60d398e/test/e2e/apimachinery/garbage_collector.go#L60

**Comment by caesarxuchao** [comment]
> All 3 of those tests calls the estimateMaximumPods function

Then even after we lower the percentage to 50%, the windows test clusters can still be easily saturated if these tests run in parallel.

That said, lowering the percentage to 50% is a reasonable change anyway.

/lgtm
/approve

To fix #106750, can we try to increase the number of nodes in the windows test clusters?

**Comment by claudiubelu** [comment]
> > All 3 of those tests calls the estimateMaximumPods function
> 
> Then even after we lower the percentage to 50%, the windows test clusters can still be easily saturated if these tests run in parallel.
> 
> That said, lowering the percentage to 50% is a reasonable change anyway.
> 
> /lgtm /approve
> 
> To fix #106750, can we try to increase the number of nodes in the windows test clusters?

Increasing the number of nodes will also increase the number of pods that are going to be spawned proportionally. All nodes will still spawn the same number of pods each.

**Pull request merged**
