### PR TITLE
Fix a typo in the Power arch keyword

### PR DESCRIPTION
**Pull request by duglin**
s/ppc64el/ppc64le/ (note the "el" vs "le")

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by luxas** [comment]
However crazy this may seem, it's actually correct.
The Golang name for PowerPC 64 Little Endian is `ppc64le`.
The Debian name for the architecture is `ppc64el`, see for example: http://ports.ubuntu.com/dists/xenial/main/binary-ppc64el/

I know it's REALLY confusing, but I don't know we can do anything about it...

**Comment by duglin** [comment]
ok thanks for the explanation

**Pull request closed without merging**
