### PR TITLE
Oops, let's be careful about licensing.

### PR DESCRIPTION
**Pull request by lavalamp**
@sillsm - Is this acceptable?

### CODE REVIEW

**Comment by erictune** [comment]
good catch @lavalamp

**Comment by lavalamp** [comment]
oops, I missed a file-- explains why it built locally. Fixed now.

**Comment by sillsm** [comment]
LGTM

**Comment by rjnagal** [comment]
The test failure is due to node controller data race. I think there's a different issue for that.
This looks good for merging.

**Pull request merged**
