### PR TITLE
WIP: Scheduling algorithms ReplicaSet Controller uses: predicates & priorities

### PR DESCRIPTION
**Pull request by kshafiee**
- Scheduling algorithms are called by ReplicaSet Controller (FRSC)
- They take Federated ReplicaSet (FRS) as input, return Local ReplicaSets (LRS's) and their bindings as output

### CODE REVIEW

**Comment by kshafiee** [comment]
@jianhuiz @deepak-vij

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation
Adding @mwielgus as reviewer

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by mfanjie** [comment]
This PR seems a subset of #29741, and most of the framework related code was dropped, could you help me understand why we need a new PR with the same source code instead of polishing the original PR? Thanks. @kshafiee

**Comment by kshafiee** [comment]
@mfanjie instead of the scheduler, we now have the replicaset controller that calls the scheduling code internally. This PR is the part of your PR that can still be used by the replicaset controller to call the scheduling algorithms. However, the files related to predicate, priorities and default need to be modified to account for the new scheduling algorithms. That's why this is still WIP and I will push the modified code shortly

**Comment by mfanjie** [comment]
Yes, I know the final scheduling algorithms must be very different, as my PR only provides very basic scheduling policy as requested by the time of v1.3. But scheduling algorithms is pluggable, if there are advanced scheduler algorithms, they should be defined as new plugins to register to existing framework PR, instead of duplicate the framework code in different PR.

**Comment by kshafiee** [comment]
@mfanjie 
This work is based on PR #24038 
Based on @mfanjie  discussion with @jianhuiz during the weekend, Jesse does not have the bandwidth to continue the PR on federated replicaset

**Pull request closed without merging**
