### PR TITLE
Automated cherry pick of #68001: apiserver: forward panic in WithTimeout filter

### PR DESCRIPTION
**Pull request by sttts**
Cherry pick of #68001 on release-1.11.

#68001: apiserver: forward panic in WithTimeout filter

### CODE REVIEW

**Comment by sttts** [comment]
Bitbucket http 500 😱

/retest

**Review by dims — APPROVED** [review]

**Comment by sttts** [comment]
/assign @calebamiles @krzyzacy 

Is this approved for the next release?

**Comment by krzyzacy** [comment]
/unassign
/assign @foxish 
assign to 1.11 patch release manager

**Comment by foxish** [comment]
Looks like this missed 1.11.3, will target it for 1.11.4

**Comment by nikhita** [comment]
/kind bug

@foxish can you approve this to go for 1.11.4?

**Comment by foxish** [comment]
Done! Sorry about the delay.

**Pull request merged**
