### PR TITLE
fix todo: use the ServiceTestJig replace of service in e2e/network/service.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fix todo: use the ServiceTestJig replace of service in e2e/network/service.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
cc @dcbw

**Comment by bowei** [comment]
@agau4779 -- could you take a look (review)?

**Comment by hanxiaoshuai** [comment]
cc @liggitt @deads2k

**Comment by hanxiaoshuai** [comment]
cc @agau4779 could you take a look (review) this pr ,Thanks

**Pull request merged**
