### PR TITLE
make consistent receiver name

### PR DESCRIPTION
**Pull request by yanghaichao12**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
receiver name sm should be consistent with previous receiver name serviceMap for ServiceMap

Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

release-note
NONE

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
/ok-to-test

@yanghaichao12 you need to edit the initial comment to put the "NONE" inside a proper release-note block:

    ```release-note
    NONE
    ```

**Comment by yanghaichao12** [comment]
@danwinship hi，thank for your reply.  i'v change it as you said. is it correct?

**Comment by danwinship** [comment]
hm... no, but never mind, someone else used a bot command to fix the release note anyway

**Comment by yanghaichao12** [comment]
@danwinship okay.....thank you!

**Pull request merged**
