### PR TITLE
Automated cherry pick of #31794 #32165 #31655 #31833 #31947 #30105

### PR DESCRIPTION
**Pull request by foxish**
Cherry pick of #31794 #32165 #31655 #31833 #31947 #30105 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32236)

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by rmmh** [comment]
@k8s-bot test this

**Comment by rmmh** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
[Tests passed](https://github.com/kubernetes/kubernetes/pull/32236#issuecomment-245680210), doing a manual merge now, as the testing framework appears to be having issues and the statuses that the submit-queue looks at are red despite the tests having passed.

cc @rmmh @pwittrock

**Pull request merged**
