### PR TITLE
Automated cherry pick of #77426: Remove terminated pod from summary api.

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #77426 on release-1.13.

#77426: Remove terminated pod from summary api.

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by hoegaarden** [comment]
This feels like a significant-enough user-facing change for a release-note. What do you all think?

**Comment by Random-Liu** [comment]
> This feels like a significant-enough user-facing change for a release-note. What do you all think?

The original PR has a release note. This PR is auto generated. Not sure whether I need to manually add a release note.

**Comment by Random-Liu** [comment]
Rebased. @feiskyer Can you take another look?

**Pull request merged**
