### PR TITLE
Refactor KCM volume plugin probe

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Most of the in-tree volume plugins were moved to CSI. Only few of them remain and their initialization in kube-controller-manager was messy:
https://github.com/kubernetes/kubernetes/blob/16f9fdc7057e1f69ff1a44e3dbbcf7b994c3cd29/cmd/kube-controller-manager/app/plugins.go#L45-L46

Refactor the initialization to always initialize all volume plugins, but filter only those that a controller needs - volume expansion controller needs those that implement `ExpandableVolumePlugin`, Attach/Detach  controller needs those that implement `AttachableVolumePlugin` etc.

Add unit tests in the first commit to make sure the results are the same - see how the test are changed in each of the commit.

While reworking the code, I noticed that:
* FibreChannel volume plugin is erroneously added to volume expansion controller. The volume plugin does not implement volume expansion, so remove it.
* Portworx volume plugin is erroneously added to attach/detach controller. The volume plugin does not implement 3rd party attach/detach, so remove it from there.

#### Which issue(s) this PR fixes:
None, but there was a TODO in the code. And it will help https://github.com/kubernetes/kubernetes/pull/128242 that adds a new volume controller to keep sanity.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
Added license to the new `*_test.go` file.

**Comment by deads2k** [comment]
The change looks cleaner

/approve

**Pull request merged**
