### PR TITLE
Mark v1beta1 NetworkPolicy types as deprecated

### PR DESCRIPTION
**Pull request by cmluciano**
**What this PR does / why we need it**:
Deprecates v1beta1 NetworkPolicy in favor of v1. The default storage is now set to v1 in 1.9.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related #56423

**Special notes for your reviewer**:

**Release note**:

```
deprecate NetworkPolicy v1beta1 API in extensions
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@cmluciano I think we need to get this added to v1.9?

**Comment by thockin** [comment]
/approve

@enisoc This is a non-code change - process needed?

**Comment by enisoc** [comment]
@thockin Docs change is ok. Adding milestone.

**Pull request merged**
