### PR TITLE
registry: remove todos about rc/rs label/annotation updates

### PR DESCRIPTION
**Pull request by 0xmichalis**
@bprashanth @madhusudancs PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
@eparis no luck for a cla label even after updating user.name to not use spaces...

**Comment by kargakis** [comment]
@k8s-bot test this issue: #21463

**Comment by kargakis** [comment]
@k8s-bot test this issue: #21463

**Comment by bgrant0607** [comment]
@kargakis What's the motivation? The controller doesn't look at its own labels and annotations, does it?

I'm inclined to just remove the TODO.

cc @janetkuo @mqliang

**Comment by kargakis** [comment]
@bgrant0607 I am adding generation in our DeploymentConfigs, and thought that it would make sense for the generation to bump on these updates, even though it seems that it is used only for scaling purposes in RCs/RSs (so you are right).

I am planning to move generation in Deployments, based on your comment it makes sense there since the controller looks at Deployment annotations/labels, right?

**Comment by bgrant0607** [comment]
@kargakis I don't think bumping generation here will help.

I do agree we should add it to Deployment.

**Comment by kargakis** [comment]
@bgrant0607 updated by removing the todos

**Comment by bgrant0607** [comment]
LGTM, thanks

**Pull request merged**
