### PR TITLE
FakeDockerClient: add creation timestamp

### LINKED ISSUE #42736: CRI: PodSandbox was restarted in hollow node when running kubemark
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/1689/

Pod `density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn` has a restart count 1

FYI, all relevant messages about this pod in the kubelet.log:
https://gist.github.com/yujuhong/b1dc4fecfe835944d1cd5c6f67f006ed

From the sync loop timeline, some containers died.
```
12:44:57.602374       9 kubelet.go:1808] SyncLoop (ADD, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:44:58.787422       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"88d185ba4599ed5e"}
12:44:59.791857       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"40194345840e54d9"}
12:45:00.971051       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"40194345840e54d9"}
12:45:00.971110       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"40194245840e5326"}
12:45:00.971153       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"88d185ba4599ed5e"}
12:49:32.331263       9 kubelet.go:1824] SyncLoop (DELETE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:49:33.104486       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"40194245840e5326"}
12:49:33.104541       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"88d185ba4599ed5e"}
12:49:34.118279       9 kubelet.go:1824] SyncLoop (DELETE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:49:34.121374       9 kubelet.go:1818] SyncLoop (REMOVE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
```

Check the log again:
```
I0308 12:44:57.908490       9 kuberuntime_manager.go:370] No sandbox for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)" can be found. Need to start a new one
I0308 12:44:57.909301       9 kuberuntime_manager.go:549] computePodContainerChanges got {CreateSandbox:true SandboxID: Attempt:0 ContainersToStart:map[0:Container {Name:density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004 Image:gcr.io/google_containers/pause-amd64:3.0 Command:[] Args:
[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[memory:{i:{value:40265318 scale:0} d:{Dec:<nil>} s:40265318 Format:DecimalSI} cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} Volu
meMounts:[{Name:default-token-xl0xh ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityConte
xt:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.] ContainersToKeep:map[] ContainersToKill:map[] InitFailed:false InitContainersToKeep:map[]} for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-
1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
I0308 12:44:57.909490       9 kuberuntime_manager.go:558] SyncPod received new pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", will create a new sandbox for it
I0308 12:44:57.909521       9 kuberuntime_manager.go:567] Stopping PodSandbox for "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", will start new one
I0308 12:44:57.909561       9 kuberuntime_manager.go:613] Creating sandbox for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
I0308 12:44:58.017948       9 kuberuntime_gc.go:133] Removing sandbox "88d185ba4599ed5e"
```

The sandbox was GC'd right after it was created. This led to kubelet killing all the containers in the pod since the sandbox needed to be recreated. 

Need to check whether this was caused by the container state emulated by fakedockerclient, or by a real bug.

/cc @feiskyer @Random-Liu

### PR DESCRIPTION
**Pull request by yujuhong**
This fixes #42736

### CODE REVIEW

**Comment by Random-Liu** [comment]
There seems to be a unit test failure:
```
--- FAIL: TestListContainers (0.00s)
	assertions.go:203: 
                        
	Error Trace:	docker_container_test.go:96
		
	Error:		Not equal: []*runtime.Container{(*runtime.Container)(0xc4201694a0), (*runtime.Container)(0xc4201693e0), (*runtime.Container)(0xc420169320)} (expected)
			        != []*runtime.Container{(*runtime.Container)(0xc420169560), (*runtime.Container)(0xc420169620), (*runtime.Container)(0xc4201696e0)} (actual)
			
			Diff:
			--- Expected
			+++ Actual
			@@ -1,5 +1,5 @@
			 ([]*runtime.Container) (len=3 cap=4) {
			- (*runtime.Container)(0xc4201694a0)(&Container{Id:fdfc05820c316461,PodSandboxId:sandboxid2,Metadata:&ContainerMetadata{Name:sidecar2,Attempt:2,},Image:&ImageSpec{Image:logger:v2,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:0,Labels:map[string]string{abc.xyz: label2,},Annotations:map[string]string{foo.bar.baz: annotation2,},}),
			- (*runtime.Container)(0xc4201693e0)(&Container{Id:bd837aa611586636,PodSandboxId:sandboxid1,Metadata:&ContainerMetadata{Name:sidecar1,Attempt:1,},Image:&ImageSpec{Image:logger:v1,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:0,Labels:map[string]string{abc.xyz: label1,},Annotations:map[string]string{foo.bar.baz: annotation1,},}),
			- (*runtime.Container)(0xc420169320)(&Container{Id:4c1e1e211ef4ba57,PodSandboxId:sandboxid0,Metadata:&ContainerMetadata{Name:sidecar0,Attempt:0,},Image:&ImageSpec{Image:logger:v0,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:0,Labels:map[string]string{abc.xyz: label0,},Annotations:map[string]string{foo.bar.baz: annotation0,},})
			+ (*runtime.Container)(0xc420169560)(&Container{Id:fdfc05820c316461,PodSandboxId:sandboxid2,Metadata:&ContainerMetadata{Name:sidecar2,Attempt:2,},Image:&ImageSpec{Image:logger:v2,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:-6795364578871345152,Labels:map[string]string{abc.xyz: label2,},Annotations:map[string]string{foo.bar.baz: annotation2,},}),
			+ (*runtime.Container)(0xc420169620)(&Container{Id:bd837aa611586636,PodSandboxId:sandboxid1,Metadata:&ContainerMetadata{Name:sidecar1,Attempt:1,},Image:&ImageSpec{Image:logger:v1,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:-6795364578871345152,Labels:map[string]string{abc.xyz: label1,},Annotations:map[string]string{foo.bar.baz: annotation1,},}),
			+ (*runtime.Container)(0xc4201696e0)(&Container{Id:4c1e1e211ef4ba57,PodSandboxId:sandboxid0,Metadata:&ContainerMetadata{Name:sidecar0,Attempt:0,},Image:&ImageSpec{Image:logger:v0,},ImageRef:,State:CONTAINER_RUNNING,CreatedAt:-6795364578871345152,Labels:map[string]string{abc.xyz: label0,},Annotations:map[string]string{foo.bar.baz: annotation0,},})
			 }
		
E0308 18:18:55.712999       6 helpers.go:296] Failed to remove the conflicting container "containerid": container not stopped
E0308 18:18:55.713130       6 helpers.go:296] Failed to remove the conflicting container "containerid": random error
E0308 18:18:55.713182       6 helpers.go:296] Failed to remove the conflicting container "containerid": Error response from daemon: No such container: containerid
--- FAIL: TestListSandboxes (0.00s)
	assertions.go:203: 
                        
	Error Trace:	docker_sandbox_test.go:87
		
	Error:		Not equal: []*runtime.PodSandbox{(*runtime.PodSandbox)(0xc4201d5dc0), (*runtime.PodSandbox)(0xc4201d5940), (*runtime.PodSandbox)(0xc4201d56c0)} (expected)
			        != []*runtime.PodSandbox{(*runtime.PodSandbox)(0xc4201d5f00), (*runtime.PodSandbox)(0xc4201280c0), (*runtime.PodSandbox)(0xc420128300)} (actual)
			
			Diff:
			--- Expected
			+++ Actual
			@@ -1,5 +1,5 @@
			 ([]*runtime.PodSandbox) (len=3 cap=4) {
			- (*runtime.PodSandbox)(0xc4201d5dc0)(&PodSandbox{Id:18601f7115bbb09,Metadata:&PodSandboxMetadata{Name:foo2,Uid:2,Namespace:bar2,Attempt:0,},State:SANDBOX_READY,CreatedAt:0,Labels:map[string]string{label: foo2,},Annotations:map[string]string{annotation: bar2,},}),
			- (*runtime.PodSandbox)(0xc4201d5940)(&PodSandbox{Id:89ff0a41f3c737ca,Metadata:&PodSandboxMetadata{Name:foo1,Uid:1,Namespace:bar1,Attempt:0,},State:SANDBOX_READY,CreatedAt:0,Labels:map[string]string{label: foo1,},Annotations:map[string]string{annotation: bar1,},}),
			- (*runtime.PodSandbox)(0xc4201d56c0)(&PodSandbox{Id:9c5f40c0a5ad48bf,Metadata:&PodSandboxMetadata{Name:foo0,Uid:0,Namespace:bar0,Attempt:0,},State:SANDBOX_READY,CreatedAt:0,Labels:map[string]string{label: foo0,},Annotations:map[string]string{annotation: bar0,},})
			+ (*runtime.PodSandbox)(0xc4201d5f00)(&PodSandbox{Id:18601f7115bbb09,Metadata:&PodSandboxMetadata{Name:foo2,Uid:2,Namespace:bar2,Attempt:0,},State:SANDBOX_READY,CreatedAt:-6795364578871345152,Labels:map[string]string{label: foo2,},Annotations:map[string]string{annotation: bar2,},}),
			+ (*runtime.PodSandbox)(0xc4201280c0)(&PodSandbox{Id:89ff0a41f3c737ca,Metadata:&PodSandboxMetadata{Name:foo1,Uid:1,Namespace:bar1,Attempt:0,},State:SANDBOX_READY,CreatedAt:-6795364578871345152,Labels:map[string]string{label: foo1,},Annotations:map[string]string{annotation: bar1,},}),
			+ (*runtime.PodSandbox)(0xc420128300)(&PodSandbox{Id:9c5f40c0a5ad48bf,Metadata:&PodSandboxMetadata{Name:foo0,Uid:0,Namespace:bar0,Attempt:0,},State:SANDBOX_READY,CreatedAt:-6795364578871345152,Labels:map[string]string{label: foo0,},Annotations:map[string]string{annotation: bar0,},})
			 }
		
FAIL

```

**Comment by yujuhong** [comment]
> There seems to be a unit test failure:

Fixed.

**Comment by Random-Liu** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
