### PR TITLE
Correct pod and namespace deletion specifications

### LINKED ISSUE #30537: API reference has incorrect response schema for many delete calls
The API reference seems to assume a response schema of unversioned.Status for all delete calls, individual or collection. In reality, the response schema differers from resource to resource, and for some it is correct, but for many the response schema is actually an individual or list of the given resource. For example, the delete call for the Pod resource returns a Pod and a PodList for the individual and collection delete calls, respectively.

Short term, we should update the docs to reflect reality. Long term, wouldn't it make sense to unify the API so all the resources behave the same? Currently it is left up to the resource implemenation:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L807-L827

### PR DESCRIPTION
**Pull request by randalloveson**
fixes #30537 (partially)

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30547)

### CODE REVIEW

**Comment by randalloveson** [comment]
I signed it!

**Comment by lavalamp** [comment]
This file is generated, so changing it like this is unlikely to work. @mbohlool can say whether the changes he is working on will cover this.

**Comment by mbohlool** [comment]
My Change will not fix this. This needs to be fixed when we install routes. as @lavalamp said, this is a generated file and it won't work. closing the PR.

**Comment by mbohlool** [comment]
btw, the fix most probably involves changing this file: kubernetes/pkg/apiserver/api_installer.go
(or you can start from there), In case you want to fix routes.

**Pull request closed without merging**
