### PR TITLE
Move informer_factory to staging

### PR DESCRIPTION
**Pull request by cici37**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
We want to create a generic version of ControllerContext(living in k8s.io/controller-manager). InformerFactory would be part of that ControllerContext which requires to be public. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
@BenTheElder Would you please have a look when you have time? Thank you

**Comment by BenTheElder** [comment]
/approve
for vendor/ and test/

**Pull request merged**
