### PR TITLE
Automated cherry pick of #71868: Include BGPConfiguration

### PR DESCRIPTION
**Pull request by satyasm**
Cherry pick of #71868 on release-1.11.

#71868: Include BGPConfiguration

### CODE REVIEW

**Comment by satyasm** [comment]
/assign @caseydavenport 
/cc @jingax10 

cherry pick into 1.11 branch, needs ok-to-test

**Comment by foxish** [comment]
/ok-to-test

@satyasm, please get lgtm+approve from any of the owners.

**Comment by satyasm** [comment]
> @satyasm, please get lgtm+approve from any of the owners.

Yup, waiting on @caseydavenport

**Pull request merged**
