### PR TITLE
Fix AppArmor unloaded profile e2e test

### LINKED ISSUE #107342: [Failing test] [sig-node] AppArmor [Feature:AppArmor][NodeFeature:AppArmor] when running with AppArmor should reject an unloaded profile
##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/apparmor_test.go:58
Unexpected error:
    <*errors.errorString | 0xc00029ada0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/apparmor_test.go:196
```
#### Recent failures:
[1/5/2022, 3:15:54 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1478686668440473600)
[1/5/2022, 3:12:49 AM ci-cri-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e-features/1478685913520279552)
[1/5/2022, 3:10:49 AM ci-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-containerd-node-e2e-features/1478685410392543232)
[1/5/2022, 2:14:54 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1478671317069729792)
[1/5/2022, 2:12:53 AM ci-cri-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e-features/1478670813577089024)

Also appears to be failing on:

- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu
- https://testgrid.k8s.io/sig-node-containerd#containerd-node-features
- https://testgrid.k8s.io/sig-node-containerd#image-validation-node-features

Failures as of 01/05.

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
With the removal of the kubelet AppArmor profile validation in https://github.com/kubernetes/kubernetes/pull/97966 we passed the responsibility of the desired behavior to the container runtime. Therefore we have to change the e2e test which silently broke after the PR merge.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/107342

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review, PTAL

@ehashman @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
this job ^^^ should run the affected test

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

this: `/test pull-kubernetes-node-e2e-containerd-features` has actually run the affected test sucessfully

**Pull request merged**
