### PR TITLE
kubectl: cast notFound error to struct

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/28378 (the 404 flake)

@kubernetes/kubectl @kubernetes/deployment

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31375)

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/31389

**Comment by AdoHe** [comment]
*[pkg/kubectl/stop_test.go, line 774 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31375#-KPyxvUHs1ljqjHha7tL:-KPyxvUHs1ljqjHha7tM:bft3lwu) ([raw file](https://github.com/kubernetes/kubernetes/blob/9667b4723fb8340b24bddef09947ea899c061f23/pkg/kubectl/stop_test.go#L774)):*
> ```Go
> 	reaper := DeploymentReaper{fake, time.Millisecond, time.Millisecond}
> 	err := reaper.Stop(ns, name, 0, nil)
> 	fmt.Println(fake.Actions())
> ```

Please remove this println, and maybe we can simply check actions.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31375)*

**Comment by kargakis** [comment]
Done.

**Comment by AdoHe** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31375#-:-KQ18KOwM8S08tbEnOSE:bnfp4nl)*

**Comment by AdoHe** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31375#-:-KQ18zprJ866x8t1GJlr:bnfp4nl)*

**Comment by kargakis** [comment]
@pwittrock @gmarek this fixes the 404 in https://github.com/kubernetes/kubernetes/issues/28378 (missed from https://github.com/kubernetes/kubernetes/pull/29484). Should we add a 1.4 milestone?

**Comment by wojtek-t** [comment]
That is P1 flake - yes we should. Adding.

**Pull request merged**
