### PR TITLE
fix the url for  author

### PR DESCRIPTION
**Pull request by wyyxd2017**
fix the pr author

### CODE REVIEW

**Review by soniasingla — APPROVED** [review]
Thanks for the PR 🎉

/approve

**Comment by wilsonehusin** [comment]
@wyyxd2017 thanks for the PR! There are something I'd like to say:

- When creating pull requests, please do not remove the template which GitHub has generated. The structure is important for our automation to work in releases. `k8s-ci-robot` has identified those problems in the comments above. 
- We have a community guideline around [trivial edits](https://github.com/kubernetes/community/blob/018effde899c8ed02794fc067bafe5cb9137999c/contributors/guide/pull-requests.md#trivial-edits).
- This is also a PR for Kubernetes 1.10, which [has reached end-of-life 2 years ago](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history). At this point, I would rather not continue maintaining EOL versions since they are no longer supported by the community.

If you'd like to find out ways to contribute on CHANGELOGs and documentations, feel free to reach out to us `#sig-release` on [Kubernetes Slack](https://slack.k8s.io).

/close

**Comment by wyyxd2017** [comment]
> @wyyxd2017 thanks for the PR! There are something I'd like to say:
> 
> * When creating pull requests, please do not remove the template which GitHub has generated. The structure is important for our automation to work in releases. `k8s-ci-robot` has identified those problems in the comments above.
> * We have a community guideline around [trivial edits](https://github.com/kubernetes/community/blob/018effde899c8ed02794fc067bafe5cb9137999c/contributors/guide/pull-requests.md#trivial-edits).
> * This is also a PR for Kubernetes 1.10, which [has reached end-of-life 2 years ago](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history). At this point, I would rather not continue maintaining EOL versions since they are no longer supported by the community.
> 
> If you'd like to find out ways to contribute on CHANGELOGs and documentations, feel free to reach out to us `#sig-release` on [Kubernetes Slack](https://slack.k8s.io).
> 
> /close
tha


> @wyyxd2017 thanks for the PR! There are something I'd like to say:
> 
> * When creating pull requests, please do not remove the template which GitHub has generated. The structure is important for our automation to work in releases. `k8s-ci-robot` has identified those problems in the comments above.
> * We have a community guideline around [trivial edits](https://github.com/kubernetes/community/blob/018effde899c8ed02794fc067bafe5cb9137999c/contributors/guide/pull-requests.md#trivial-edits).
> * This is also a PR for Kubernetes 1.10, which [has reached end-of-life 2 years ago](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history). At this point, I would rather not continue maintaining EOL versions since they are no longer supported by the community.
> 
> If you'd like to find out ways to contribute on CHANGELOGs and documentations, feel free to reach out to us `#sig-release` on [Kubernetes Slack](https://slack.k8s.io).
> 
> /close

ok!

**Pull request closed without merging**
