### PR TITLE
Fix kibana e2e test

### PR DESCRIPTION
**Pull request by crassirostris**
Thanks @Random-Liu for noticing a problem in kibana e2e test!

Fix https://github.com/kubernetes/kubernetes/issues/36402

@piosz

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36506)

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by Random-Liu** [comment]
@Crassirostris After this gets merged, I assume https://k8s-testgrid.appspot.com/google-gce#gce-es-logging will start to fail.

**Comment by piosz** [comment]
According to @Random-Liu comment removed lgtm label.

**Comment by Random-Liu** [comment]
@Crassirostris @piosz The original issue is that `GetServicesProxyRequest` keeps failing, but the test didn't throw out error.

Once this gets merged, the test will start to fail, and the original issue is still not solved.

**Comment by Crassirostris** [comment]
@Random-Liu No, it won't fail, I checked this test locally before sending a PR

In case `GetServicesProxyRequest` does fail, the error will be in `err` variable, that will be asserted to be nil in https://github.com/Crassirostris/kubernetes/blob/05193d5d34c12c118c5115f8e9e2975d0b561e54/test/e2e/kibana_logging.go#L98

**Comment by dims** [comment]
@piosz can you please reapply the lgtm tag?

**Comment by Random-Liu** [comment]
> this test doesn't fail, it's just slow.

@Crassirostris Hm, since you have tried, LGTM. ;)

**Comment by Random-Liu** [comment]
Wait, it success because you are defining a new `err` inside the loop. The outside `err` is never changed, so it's always `nil`.

**Comment by Crassirostris** [comment]
@Random-Liu Thank you for your observation! The code was indeed, wrong, I fixed it, now for sure the `err` inside is the same `err` as outside of the loop scope.

However, test does pass :)

I didn't just run the test, I watched logs from both test and kibana. Here's what you will see in test log

```
Nov 13 00:15:59.768: INFO: After 5m46.184299584s proxy call to kibana-logging failed: an error on the server ("Error: 'dial tcp 10.180.0.2:5601: getsockopt: connection refused'\nTrying to reach: 'http://10.180.0.2:5601/'") has prevented the request from succeeding (get services kibana-logging)
Nov 13 00:16:05.169: INFO: After 5m51.585662323s proxy call to kibana-logging failed: an error on the server ("Error: 'dial tcp 10.180.0.2:5601: getsockopt: connection refused'\nTrying to reach: 'http://10.180.0.2:5601/'") has prevented the request from succeeding (get services kibana-logging)
[AfterEach] [k8s.io] Kibana Logging Instances Is Alive [Feature:Elasticsearch]
```

and in kibana logs

```
{"type":"log","@timestamp":"2016-11-12T23:08:52Z","tags":["info","optimize"],"pid":11,"message":"Optimizing and caching bundles for kibana and statusPage. This may take a few minutes"}
{"type":"log","@timestamp":"2016-11-12T23:16:06Z","tags":["info","optimize"],"pid":11,"message":"Optimization of bundles for kibana and statusPage complete in 434.48 seconds"}
```

As you can see, it really did take 7 minutes for kibana to rebuild it's bundles and only after that test passed, after 5 min of waiting, not 10, which is the test timeout.

**Comment by Crassirostris** [comment]
@k8s-bot node e2e test this

**Comment by Crassirostris** [comment]
@k8s-bot node e2e test this

**Comment by dims** [comment]
@Crassirostris looks like this is almost ready!

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
