### PR TITLE
Update to go 1.12.5

### LINKED ISSUE #75833: API call latencies regressed due to upgrade to golang 1.12
Something has changed between 320 and 321 runs and the request latency has increased significantly.

The graphs below shows request latency (non watch) over time for a single test run:

[320](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/320):
FYrJr3W9WRY

[321](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/321):
vHedLTUA8zO

In my opinion they looks significantly different: in 320 most of the spikes are lower than 0.8s while 321 most of the spikes exceeds 1.6s.

I checked few runs below 320 and have latency pattern similar to 320 and few runs after 321 and they have similar pattern to the 321.

We are seeing similar latency growth in kubemark tests.

The most significant change between 321 and 320 was go 1.11.5 -> 1.12 migration.

/cc @wojtek-t @krzysied

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Updates to go 1.12.5. This fixes a significant API call latency regression

**Which issue(s) this PR fixes**:
Fixes #75833

**Does this PR introduce a user-facing change?**:
```release-note
Update to use go 1.12.5
```

### CODE REVIEW

**Comment by cblecker** [comment]
Next steps:
- Waiting for the docker hub image to publish. The PR is merged, so this should happen shortly.
- Need a new version of the bazel rules_go to be published. (cc: @jayconrod)

**Comment by javier-b-perez** [comment]
I still don't see the new golang image

**Comment by cblecker** [comment]
@javier-b-perez Looks like the images are now published:
```
Digest: sha256:e52f9c9ea80fa182a78bd83a9f9e107d173b8e7fd922dbb0c60c8020a88fb7f6
Status: Downloaded newer image for golang:1.12.5
```

**Comment by wojtek-t** [comment]
@cblecker - can you please update the sha in the PR?

**Comment by cblecker** [comment]
@wojtek-t New rules_go hasn't been released yet: https://github.com/bazelbuild/rules_go/releases

@jayconrod: is there an ETA on the next cut?

**Comment by cblecker** [comment]
/hold cancel

All test are passing. This should be ready to ship. Looking for final review and LGTM.

**Comment by wojtek-t** [comment]
Thanks a lot for this!

**Pull request merged**
