### PR TITLE
move spark images to github.com/kubernetes/application-images/spark

### PR DESCRIPTION
**Pull request by mattf**
the spark images now live in https://github.com/kubernetes/application-images

this pr removes them from the kubernetes repository to avoid duplicate copies

cc @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
I think we should c-p this to 1.1 at least, and also update the docs to mention where image lives. I started a branch to update the docs and just haven't pushed a PR (got distracted by something). Thanks for the PR.

LGTM.

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot e2e test this

**Comment by zmerlynn** [comment]
Actually, before we delete, we really do need to rework the docs to say where they moved (otherwise the example makes no sense). Sorry, just noticed this when I was writing a comment on #19760.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Pull request merged**
