### PR TITLE
Env var to specify custom user-agent

### LINKED ISSUE #13829: Kubectl flag for specifying custom user-agent
The kube-addon-update.sh script that runs on the master periodically uses kubectl to talk to the apiserver. This is fine, but muddies up the kube-apiserver logs with requests from kubectl that aren't actually user-initiated. It's not a big deal, but would be nice if they had a more appropriate user-agent string.

### PR DESCRIPTION
**Pull request by dims**
Fixes #13829

### CODE REVIEW

**Comment by caesarxuchao** [comment]
ok to test

**Comment by caesarxuchao** [comment]
Thank you @dims. Could you fix the kube-addon-update.sh to use the Env var?

@janetkuo do we have any policy on adding env var? Shall the issue be solve by setting the user-agent in kubeconfig, or maybe adding a flag to kubectl?

@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Generally adding the env var would be API review (tagging that here) since it's an API used by the caller and we're cautious about adding new API.  From a naming perspective it's also better to be more explicit than less.

Also, not everything using the kube client is going to be kubernetes itself (i.e. extension controllers, third parties reusing the library) so if there is a more standard "USER_AGENT" env var we should consider that.

**Comment by smarterclayton** [comment]
Git uses GIT_HTTP_USER_AGENT, so I would think we would at least want to be consistent with `KUBERNETES_HTTP_USER_AGENT`.  Long is not a problem since this is frequently set for scripts.

**Comment by smarterclayton** [comment]
@kubernetes/api-review-team

**Comment by dims** [comment]
@kubernetes/api-review-team @smarterclayton @caesarxuchao - Any feedback? Do we let this in?

**Comment by caesarxuchao** [comment]
@kubernetes/api-review-team could you review it?

**Comment by dims** [comment]
@caesarxuchao @smarterclayton Looks like there is no interest in this PR. Closing it for now

**Comment by smarterclayton** [comment]
I think this is just below the side of "a step we aren't comfortable taking
*yet*", but that we need to revisit with a few other env vars all at once
and make a decision on (for things like context, user selection, and server
selection).  If we can make that decision, this becomes easier to
rationalize in that framework.

**Pull request closed without merging**
