### PR TITLE
delete the extra word

### PR DESCRIPTION
**Pull request by timyinshi**
Signed-off-by: timyinshi <shiguangyin@inspur.com>

#### What type of PR is this?
/kind documentation
/kind bug
/sig docs

#### What this PR does / why we need it:
delete the extra word of 'the'

### CODE REVIEW

**Comment by BenTheElder** [comment]
[trying to refresh github statuses]

**Comment by pacoxu** [comment]
/hold

Would you force push the branch again to skip the removed test job `pull-kubernetes-bazel-test `?

**Pull request merged**
