### PR TITLE
Prepare for extracting EtcdHelper interface

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #10475

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @fgrzadkowski

**Comment by lavalamp** [comment]
Is there a reason why the metrics change is lumped in with the interface change? I don't particularly care, it just doesn't seem like they belong together.

LGTM

**Comment by vishh** [comment]
@k8s-bot: ok to test

**Comment by wojtek-t** [comment]
>
Is there a reason why the metrics change is lumped in with the interface change? I don't particularly care, it just doesn't seem like they belong together.

@lavalamp - I will try to make that changes in separate PRs in the future (this was just supposed to be some cleanup and in fact the whole PR is a cleanup, but I agree I could have separated it).

**Comment by wojtek-t** [comment]
Test failure seems to be unrelated:
Kubernetes e2e suite.Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.

Rerunning e2e tests

**Comment by wojtek-t** [comment]
Another flake:
"The test requires two Ready nodes on gce, but found just one."

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
