### PR TITLE
pkg/controller: add SIG label to OWNERS

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
PRs against pkg/controller are missing SIG labels.
update the OWNER file to add sig/apps by default.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
bump
/cc @mikedanese @derekwaynecarr

**Comment by mikedanese** [comment]
Thanks. This makes sense to me for the most part. Certain controllers are not related to sig-apps but the false positives are pretty easily ignored.

/lgtm
/approve.

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
