### PR TITLE
Remove redundent GetObjectKind() defined on types

### PR DESCRIPTION
**Pull request by caesarxuchao**
Embedding TypeMeta is enough.

### CODE REVIEW

**Review by MHBauer — APPROVED** [review]
lgtm for all of those.

`k8s.io/apimachinery/pkg/apis/meta/v1/meta.go` defines GetObjectKind() for `TypeMeta`, which relies on the `schema.ObjectKind` interface which is implemented in the same `meta.go` file by implementing `SetGroupVersionKind()` and ` GroupVersionKind()`.

**Comment by MHBauer** [comment]
only suggestion would be to add something like my comment to the commit message.

**Comment by caesarxuchao** [comment]
@MHBauer Thanks for the comments! I updated the commit message with more details. I didn't mention SetGroupVersionKind() and GroupVersionKind() since they are details of schema.ObjectKind. 
Unfortunately, I can't assign the issue to you, i guess you need to be a member of some reviewer groups.

**Comment by caesarxuchao** [comment]
@lavalamp could you approve this change? Thanks.

**Pull request merged**
