### PR TITLE
 [WIP] [DO NOT MERGE] test apply scalability with static string table and reflector to avoid converting to unstructured

### PR DESCRIPTION
**Pull request by jennybuckley**
Combines #85373 and #85378 so we can re-run the scalability tests

/priority awaiting-more-evidence
```release-note
TODO
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
/cc @apelisse @jpbetz
Lets see if this makes any difference now

**Comment by jennybuckley** [comment]
this looks really promising!
/test pull-kubernetes-e2e-gce-100-performance

**Comment by jpbetz** [comment]
Variance is high. Kicking off more runs.
/test pull-kubernetes-e2e-gce-100-performance

**Pull request closed without merging**
