### PR TITLE
Remove unused parameter from pkg/kubelet/config/file.go::new(...)

### PR DESCRIPTION
**Pull request by bonifaido**
**What this PR does / why we need it**:
This PR removes an unused parameter from the new() function 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bonifaido** [comment]
I signed it!

**Comment by Random-Liu** [comment]
/lgtm
/approve

@bonifaido Sorry for the delay. :p

**Comment by Random-Liu** [comment]
@bonifaido You need to update the unit test as well. For example, https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file_linux_test.go#L57

**Comment by Random-Liu** [comment]
LGTM, please squash the commits. :)

**Comment by bonifaido** [comment]
Rebased.

**Comment by timstclair** [comment]
@k8s-bot ok to test

**Comment by bonifaido** [comment]
This looks like a flaky test.

**Comment by bonifaido** [comment]
Just rebased it on master to check that it still works, and keep it open.

**Pull request closed without merging**
