### PR TITLE
Add ga-beacon analytics to .md files (except Godeps folder)

### PR DESCRIPTION
**Pull request by mansoorj**

### CODE REVIEW

**Comment by dchen1107** [comment]
@mansoorj could you please upload whatever script you are using to generate this big PR first? I do have a concern on how we are going to maintain this for a long run. 

cc/ @bgrant0607

**Comment by bgrant0607** [comment]
Also, the kubectl docs are automatically generated. This must break the gendocs presubmit check.

**Comment by mansoorj** [comment]
Hi Brian,

I'm adding Brendan who can rovide more context around gendocs as I'm
essentially a Noogler trying to help the team out with this PR, but don't
have a lot of in-depth expertise yet.

For the script, I basically did this for every folder (except Godeps)

*for x in */*.md; do echo "" >> $x; echo "" >> $x; echo
"[Analytics](
<https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/$x?pixel)](>)"
>> $x;done*

**Comment by dchen1107** [comment]
Really add @brendandburns here 

@mansoorj There are totally 3 open PR for this, I am going to close other two (#6829, #6715), and leave this. Is that ok with you?

**Comment by mansoorj** [comment]
Yes please. Thanks.

**Comment by bgrant0607** [comment]
Please look at run-gendocs.sh:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/run-gendocs.sh

We need to exclude all generated docs. 

It looks like we generate a list here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/.files_generated
and here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/man/man1/.files_generated

**Comment by mansoorj** [comment]
Closing, resubmitted as #7524.

**Pull request closed without merging**
