### PR TITLE
Add jpbetz and wenjiaswe to cluster/images/etcd OWNERS

### PR DESCRIPTION
**Pull request by jpbetz**
Been maintaining this portion of the code for ~1yr. Adding myself as reviewer and approver and @wenjiaswe is familiar with this code, heavily involved with etcd and will make a valuable reviewer.

/sig api-machinery
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by jpbetz** [comment]
@mikedanese would you be willing to review?

**Comment by jpbetz** [comment]
@roberthbailey would you be willing to approve?

**Comment by wenjiaswe** [comment]
Thanks @mikedanese

**Pull request merged**
