### PR TITLE
fix: register ResourceSlice to allResources

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

register `ResourceSlice` to `allResources`.
Nothing serious, `allResources` is just used for scheduler-perf to get which metrics it has to collect.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
Why hold? I

**Comment by AxeZhan** [comment]
/hold cancel
I checked sth and forgot to cancel here😅.

**Pull request merged**
