### PR TITLE
Revert "Downward api node defaults"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#27303

This probably broke e2e tests on GKE

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
Merging manually to fix e2e tests.

**Comment by derekwaynecarr** [comment]
How did this break tests?  It had to have passed e2e to merge to begin with no?

**Comment by wojtek-t** [comment]
@derekwaynecarr - it seems it broke GKE (which is not part of persubmit)
But we don't know what exactly happened, but it seems that in GKE kubelet is not longer starting any pods on master machine. It may be something different, but tests started failing exactly when this PR was merged.

**Comment by derekwaynecarr** [comment]
@wojtek-t - how should I debug this?  can GKE be debugged separately?  who is going to re-revert?  how can i know it wont cause a problem again?

**Comment by pmorie** [comment]
> how should I debug this? can GKE be debugged separately? who is going to re-revert? how can i know it wont cause a problem again?

I have the same Qs, along with how you could make this inference:

>  tests started failing exactly when this PR was merged.

**Comment by piosz** [comment]
cc @dchen1107 @vishh

**Comment by fgrzadkowski** [comment]
It seems that revert helped.

@dchen1107 Can you (or someone from your team) can help debug the problem?

**Comment by derekwaynecarr** [comment]
I will open a Revert of the Revert PR this afternoon, and would ask that someone at Google can help debug the actual failure on the GKE infrastructure that was caused by that PR as it needs to make kube 1.3.

**Comment by piosz** [comment]
cc @alex-mohr @fabioy @roberthbailey

**Comment by dchen1107** [comment]
I am looking into the original failure. Meanwhile, I have the similar issue as @derekwaynecarr. :-(

**Comment by dchen1107** [comment]
Ok, is there an open issue to track the original problem so that I can dump what I found?

**Comment by mtaufen** [comment]
#27062 might be appropriate, unless we want a separate issue for the test failure.

**Pull request merged**
