### PR TITLE
RFC: Kubelet: a step towards to better encapsulation of docker functions

### PR DESCRIPTION
**Pull request by yujuhong**
We want to stop leaking more docker details into kubelet, and we also want to
consolidate some of the existing docker interfaces/structs. This change creates
DockerManager as the new home of some functions in dockertools/docker.go. It
also absorbs containerRunner. In addition, GetDockerPodStatus is renamed to
GetPodStatus with the entire pod passed to it so that it is simialr to the what
is defined in the container Runtime interface.

Eventually, DockerManager should implement the container Runtime interface, and
integrate DockerCache with a flag to turn on/off caching. Code in kubelet.go
should not be using docker client directly.

### CODE REVIEW

**Comment by yujuhong** [comment]
FYI, I am doing this so it'd be easier for me to work on #6321

**Comment by dchen1107** [comment]
This is totally moving along what we want for runtime abstraction. Will read it in detail.

**Comment by dchen1107** [comment]
LGTM overall. @yfan-gu  any objections?

**Comment by yifan-gu** [comment]
LGTM! thanks @yujuhong !

**Comment by vmarmol** [comment]
Late to the party, but this looks great! Thanks @yujuhong

**Pull request merged**
