### PR TITLE
Update ipvs library to the new repo and upgrade library version

### LINKED ISSUE #89109: Migrate ipvs library from docker/libnetwork/ipvs to moby/ipvs
As suggested by @dims in #sig-network Slack channel, ipvs was extracted out of docker/libnetwork package to its own repo in https://github.com/moby/ipvs and it should be replaced also in the parts of code using ipvs to the new library location.

The idea is to replace the parts using the IPVS library to use github.com/moby/ipvs 

This is related to #85005 

We should analyze the impact and, if this is something simple to do, this issue can be turned into a good-first-issue so someone can get this and open a PR to update the library location.

References: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#adding-or-updating-a-dependency

Where is the library being used in the old location: https://cs.k8s.io/?q=docker.*ipvs&i=nope&files=&repos=kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: This PR moves the location of the library of IPVS from github.com/docker/libnetwork to github.com/moby/ipvs, as this library has been decoupled from its original repo, turning it simple to maintain this only dependency instead of the full github.com/docker/libnetwork dependency

**Which issue(s) this PR fixes**: 
Fixes #89109 

**Special notes for your reviewer**: This is a change suggested by @dims here: https://kubernetes.slack.com/archives/C09QYUH5W/p1584036090129700

Although its said the code is identical, there are some transitive dependencies that needed to be updated as well, so this needs to be double checked if it breaks anything. 

The transitive dependencies that were also updated:

``` 
github.com/pkg/errors
    pinned:    v0.8.1
    preferred: v0.9.1
    hack/pin-dependency.sh github.com/pkg/errors v0.9.1
github.com/vishvananda/netlink
    pinned:    v1.0.0
    preferred: v1.1.0
    hack/pin-dependency.sh github.com/vishvananda/netlink v1.1.0
github.com/vishvananda/netns
    pinned:    v0.0.0-20171111001504-be1fbeda1936
    preferred: v0.0.0-20191106174202-0a2b9b5464df
    hack/pin-dependency.sh github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rikatz** [comment]
/assign @thockin 
/assign @liggitt 

Folks, as this touches a dependency used by other sub projects I think it needs an approval of some of you also

Thanks

**Comment by BenTheElder** [comment]
/assign
for dep review

**Comment by andrewsykim** [comment]
@dims was there a reason to bump netlink to v1.1.0 in https://github.com/moby/ipvs/pull/6 or was it just to use the latest version available?  

> There is one minor change to AddrAdd where it will no longer automatically set a broadcast address when you set a /31 or /32 address 

^ from the netlink v1.1.0 release notes, this seems like a change worth investigating

**Comment by dims** [comment]
@andrewsykim the latter "the latest version available" :) this was part of the issue with the ipvs/ package, no one was taking care of it. hoping folks will help with the new repo now!

**Comment by rikatz** [comment]
I'll dig more into that with the following:
* Create a multinode cluster
* Put kube-proxy in IPVS mode with the old library and check the broadcast address in ipvs interfaces and other interfaces related
* Put the newer kube-proxy version and check if there's some sensitive variation.

I don't know if e2e tests checks ipvs functionality (I think so) so if there's some difference with broadcast address this would cause an error.

IMO, I think this is related with IPVS providing some DSR feature and not announcing/broadcasting that IP anyway. Or, maybe when putting IPVS to work as a single announcer with BGP (like multiple LBs announcing the same IP to a peer router, as an example).

Anyway I don't think we might get impacted by this but I'll double check

**Review by liggitt — COMMENTED** [review]
The vast majority of the changes in this PR come from the github.com/vishvananda/netlink v1.1.0 bump. Would be good to get verification of the changes there and make sure our tests cover ipvs functionality.

**Comment by dims** [comment]
@m1093782566 Are you still interested in the ipvs stuff? can you please try these changes?

**Comment by andrewsykim** [comment]
/assign @lbernail 
cc @cmluciano

**Comment by rikatz** [comment]
Folks, I didn't forget about this, just not having enough cycles in the past week. I'm going on 'vacation' this week so I'll take a careful look into the comments

**Comment by rikatz** [comment]
OK, so comparing the netlink library from v1.0.0 to v1.1.0 (https://github.com/vishvananda/netlink/compare/v1.0.0...v1.1.0) I can see the specified change raised by @andrewsykim and also a lot of internal changes (into how the library deals with kernel stats), a new rdma support, and so on.

So far I can't see anything with huge impact BUT I'm upgrading things here to use this newer version and check wether this netlink change impacts into the ipvs interface mask calculation.

**Comment by rikatz** [comment]
## Tests

* After library update:
```
4: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    inet 10.96.0.1/32 brd 10.96.0.1 scope global kube-ipvs0
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
    inet 10.98.28.197/32 brd 10.98.28.197 scope global kube-ipvs0
    inet 10.102.183.66/32 brd 10.102.183.66 scope global kube-ipvs0
    inet 10.107.164.87/32 brd 10.107.164.87 scope global kube-ipvs0
```
* Updated kube-proxy in all nodes, removed all services from default namespace, and got this result:

```
4: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
    inet 10.96.0.1/32 scope global kube-ipvs0
```
Here, you can see that the DNS service was kept with the broadcast address but the kube-apiserver not. I have an explanation for this not make any difference later

* Re-created all services, now with kube-proxy upgraded
```
4: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
    inet 10.96.0.1/32 scope global kube-ipvs0
    inet 10.102.249.253/32 scope global kube-ipvs0
    inet 10.106.104.182/32 scope global kube-ipvs0
```

Here we can see that the newly created services doesn't contain the broadcast address anymore

## Why broadcast doesn't matter in this case (my opinion)

kube-proxy always set a "/32" (IPv4) or a "/128" (IPv6) mask when dealing with services, as this can be seen [here](https://github.com/kubernetes/kubernetes/blob/v1.18.0/pkg/util/ipvs/ipvs_linux.go#L275-L281)

This does makes sense, as the ClusterIP is to be used by the node and not externally (wait, I know there're some solutions as Calico that exports this using BGP). As the change points to not calculating broadcast with masks bigger than /30 (https://github.com/vishvananda/netlink/compare/v1.0.0...v1.1.0#diff-470999dc2d8d5b58a6624e1c5057478fR137) its enough to have only the IP when dealing with a subnet that can store only 1 or 2 IPs (/31 or /32). 

Remembering that the idea of a broadcast address is to have a single IP that represents the communication/announcement and with the whole network having a subnet with only 1 IP address this actually does not matter (but I might be wrong and have something I cannot see here)

About the impact of this into systems that route the request to ClusterIP, we can make a simple test of adding some 'node' as the router to the ClusterIP to other machine in the network:

```
ip route add 10.96.0.0/12 via 172.16.155.201
```

And with this, the call to the ClusterIP is successful so we can say by 99% of chance that this might not get impact into things relying on the ClusterIP from outside.

**Comment by rikatz** [comment]
> The vast majority of the changes in this PR come from the github.com/vishvananda/netlink v1.1.0 bump. Would be good to get verification of the changes there and make sure our tests cover ipvs functionality.

@liggitt Agree, I've been taking a look into test suites, I can see unit tests from ipvs functions but not tests from kube-proxy using IPVS mode.

The only e2e test I could really figure out that exists is one that checks if iptables rules from kube-proxy got recreated when someone flushes them in the node.

I don't know if this PR is the right place to improve this e2e test suites, if you think so I can move forward and try to figure out where I need to put them. My idea is to put kube-proxy in ipvs mode, create some service objects and check whether they reflect into what we expect them to be in the physical nodes  (ip addr command, check if the interface got exactly what I need it to be, etc). I'm just afraid this might change from system to system and also from kernel version to kernel version and became a flake test :)

Otherwise, I can open an issue and assign it to me to figure out how to improve the e2e tests from kube-proxy + IPVS, and let this PR move. That's up to you :)

Thank you!!

**Comment by liggitt** [comment]
@andrewsykim were you looking into an ipvs e2e?

**Comment by dims** [comment]
@liggitt i resurrected the ipvs CI jobs with @aojea 's help in https://github.com/kubernetes/test-infra/pull/16871 and @andrewsykim filed a presubmit job that is waiting to be merged https://github.com/kubernetes/test-infra/pull/16950

**Comment by rikatz** [comment]
I think then we can wait kubernetes/test-infra#16950 to be merget

/hold

**Comment by andrewsykim** [comment]
We set `skip_report: true` for now, folks can see results in https://k8s-testgrid.appspot.com/sig-network-gce#pull-gci-gce-ipvs in the meantime

**Comment by andrewsykim** [comment]
@rikatz your comment https://github.com/kubernetes/kubernetes/pull/89116#issuecomment-604476398 makes sense to me

**Comment by aojea** [comment]
@andrewsykim seems the bucket to store the results in testgrid is not working,

https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gci-gce-ipvs

> failed to get job history: failed to locate build data: failed to read pr-logs/directory/pull-kubernetes-e2e-gci-gce-ipvs/latest-build.txt: failed to get reader for GCS object: storage: object doesn't exist

we can see the job results here https://prow.k8s.io/?job=pull-kubernetes-e2e-gci-gce-ipvs, the job is not working

/hold
until we have signal,the job definition is missing something 🤔

**Comment by rikatz** [comment]
> @andrewsykim seems the bucket to store the results in testgrid is not working,
> 
> https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gci-gce-ipvs
> 
> > failed to get job history: failed to locate build data: failed to read pr-logs/directory/pull-kubernetes-e2e-gci-gce-ipvs/latest-build.txt: failed to get reader for GCS object: storage: object doesn't exist
> 
> we can see the job results here https://prow.k8s.io/?job=pull-kubernetes-e2e-gci-gce-ipvs, the job is not working
> 
> /hold
> until we have signal,the job definition is missing something thinking

Don't know if this is the case, but it seems to be an extra '--' in the job definition:

https://prow.k8s.io/prowjob?prowjob=c271729e-6ffb-11ea-95ad-1670332cd8c7

**Comment by rikatz** [comment]
@dims I think Antonio is waiting https://github.com/kubernetes/test-infra/pull/16989 to be merged :)

**Comment by andrewsykim** [comment]
Thank you @aojea for fixing the IPVS presubmit :bowing_man:

**Comment by aojea** [comment]
/hold cancel
the 2 failures are known issues reported in https://github.com/kubernetes/kubernetes/issues/89358

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Given E2Es passed (with known test failures) and we've validated the main changes in moby/ipvs (thanks @rikatz) I think this is good to merge. Prefer merging early in the cycle to leave more time for extra validation/testing.

**Comment by liggitt** [comment]
thanks for getting the test signal worked out

/approve

**Pull request merged**
