### PR TITLE
succesful -> successful

### PR DESCRIPTION
**Pull request by x1957**
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixtypo succesful -> successful

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by soltysh** [comment]
@x1957 thanks for your PR! I'm going to close your PR, since it doesn't add any change to the project. You can fix this typo as part of a any other fix to this controller, then I'll be happy to accept this.

**Comment by x1957** [comment]
@soltysh  thanks

**Pull request closed without merging**
