### PR TITLE
updated the IANA link for Service Name and Transport Protocol Port Number Registry

### LINKED ISSUE #29986: Broken link to iana on Service Reference API docs for appProtocol
**This is a Bug Report**

**Problem:**
The link to iana.org is broken in the [Service API Reference docs](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/), in the `ports.appProtocol` section.

This is due to a trailing paren `)` after the link. 

Browsers interpret this link as `https://www.iana.org/assignments/service-names)`, which results in a 404, instead of the intended `https://www.iana.org/assignments/service-names`.

**Proposed Solution:**
Either change the comment that results in this link being generated such that it doesn't end with a paren, or wrap the link with a `<a href ...>` tag so the browser doesn't try and fail to parse it from the text.

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

Confirmed behavior on latest Firefox, Chrome and Safari.

### PR DESCRIPTION
**Pull request by imoisharma**
Signed-off-by: Mohit Sharma <imoisharma@icloud.com>

#### What type of PR is this?
This PR is related to https://github.com/kubernetes/website/pull/29992

#### What this PR does / why we need it:
This PR will update the IANA link for Service Name and Transport Protocol Port Number Registry

#### Which issue(s) this PR fixes:

Fixes: https://github.com/kubernetes/website/issues/29986

#### Does this PR introduce a user-facing change?
Currently, under this Kubernetes doc https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec the `ports.appProtocol (string)` contain a deprecated link with the spacing issue.

```release-note
fix the IANA link for service name
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NA

### CODE REVIEW

**Comment by sftim** [comment]
/ok-to-test

BTW when I've done changes like this, I've done the manual change as a first commit, generated the files that change as a result, and then committed those as a follow-up commit, then made a PR with those 2 commits.

**Comment by sftim** [comment]
@imoisharma I'm not convinced, however, that the updated hyperlink will fix the issue you wanted it to.

This may still be a helpful change, purely through the switch to an HTTPS URL. However I think we should also look at getting folks who are good at the right kind of Go coding to look at the hyperlink handling within https://github.com/kubernetes-sigs/reference-docs/

**Comment by imoisharma** [comment]
can anyone help me with this `vendor verification failed response`?

**Comment by thockin** [comment]
It looks like the referenced bug is fixed, so this change is not needed?  The existing URL is a valid redirect to  HTTPS, so I don't think we need this change?

**Review by sftim — COMMENTED** [review]
@imoisharma you should at a minimum (IMO) revise the PR description to state the correct motivation / what this fixes.

To fix https://github.com/kubernetes/website/issues/29986, either: further change this code to use different spacing, or update the reference doc generator. I suggested one way that might work.

**Comment by thockin** [comment]
ping?

**Comment by thockin** [comment]
Should we close this?  It seems defunct

**Comment by sftim** [comment]
@imoisharma what are your plans to move this PR forward?

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Pull request closed without merging**
