### PR TITLE
Cherry pick azure internal loadbalancer

### PR DESCRIPTION
**Pull request by jdumars**
Backports fixes for Azure load balancer: 
- [Add support for Azure internal load balancer](https://github.com/kubernetes/kubernetes/pull/43510)
- [Add support for bring-your-own ip address for Services on Azure](https://github.com/kubernetes/kubernetes/pull/42034)

**Release note**:
```release-note
Add support for Azure internal load balancer.
```

### CODE REVIEW

**Comment by calebamiles** [comment]
@k8s-bot ok to test

**Comment by colemickens** [comment]
@jdumars was this done using the automated script? It makes the review easier since I can trust the script to pull the cherry-pick across. Also, any consideration of cherry-picking the UDP change that merged a couple days ago as well?

(Also, feel free to ping me on Slack, I'm ignoring GH notifications for a while to stay heads down on other stuff)

**Comment by brendandburns** [comment]
@jdumars thanks for this cherry-pick, but it actually seems to combine two PRs into one cherry-pick, I think we'd rather keep them separate.

And as Cole said, I think we want to use the [cherry-pick tool](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh) to perform the cherry-pick.

Thanks for taking this on!

**Comment by jdumars** [comment]
@brendandburns and @colemickens thank you for the incredibly fast review on this.  I was pairing with @calebamiles on this since it's my very first cherry pick into the project.  I will close this PR and use the tool + 2 separate PRs.  I'm glad to help, and appreciate the patience while I learn how to do this correctly.

**Comment by karataliu** [comment]
For Azure Internal loadbalancer support https://github.com/kubernetes/kubernetes/pull/43510, there is an ongoing PR with some fix plus e2e added in https://github.com/kubernetes/kubernetes/pull/45473 . I'd suggest making those 2 together (https://github.com/kubernetes/kubernetes/pull/43510, https://github.com/kubernetes/kubernetes/pull/45473 ) when porting to v1.6 .

@brendandburns @colemickens  could you please also have a look at PR https://github.com/kubernetes/kubernetes/pull/45473? Thank you.

**Comment by calebamiles** [comment]
Thanks again for the review @colemickens and @brendandburns. I manually downloaded the patch version of both PRs and applied them with `git am` as the [script does](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh) and compared the SHA1 of `azure_loadbalancer.go` in both cases (you'll have to trust me that we started clean from upstream on the 1.6 branch) with the fairly uninteresting result of

```
[caleb@bushidobrown azure]$ pwd
/home/caleb/workspace/kubernetes/pkg/cloudprovider/providers/azure
[caleb@bushidobrown azure]$ git log --oneline | head
c3d0de003e Update message log level for azure_loadbalancer.
3b48ef3cbe Add separate func 'cleanupLoadBalancer' and 'cleanupPublicIP' for Azure.
ef124925d2 Update reconcileSecurityGroup logic for Azure, add tests.
99f988d668 Update EnsureLoadBalancer, EnsureLoadBalancerDeleted for azure.
b70f5d40b1 Add annotation for internal load balancer type in Azure.
ab7b0b36f6 Add support for bring-your-own ip address.
1f83569cf3 Kubernetes version v1.6.4-beta.0
0480917b55 Kubernetes version v1.6.3
1804d5d0d6 Merge pull request #45449 from luxas/automated-cherry-pick-of-#44199-upstream-release-1.6
3b6cae6626 Merge pull request #45297 from vmware/automated-cherry-pick-of-#44124-#44868-K8S-release-1.6
[caleb@bushidobrown azure]$ sha1sum azure_loadbalancer.go
086740f057a8aa0a480b61fb9a7ff97889eed514  azure_loadbalancer.go
```
when cherry picking each commit in the PR individually compared with
```
[caleb@bushidobrown azure]$ pwd
/home/caleb/workspace/kubernetes_manual_script/pkg/cloudprovider/providers/azure
[caleb@bushidobrown azure]$ git log --oneline | head
8a33ecefc3 Update message log level for azure_loadbalancer.
a4f997227b Add separate func 'cleanupLoadBalancer' and 'cleanupPublicIP' for Azure.
c10f898190 Update reconcileSecurityGroup logic for Azure, add tests.
f5e1efca63 Update EnsureLoadBalancer, EnsureLoadBalancerDeleted for azure.
a2fc053abe Add annotation for internal load balancer type in Azure.
8ee5dc840c Add support for bring-your-own ip address.
60f8737078 update-all.sh
1f83569cf3 Kubernetes version v1.6.4-beta.0
0480917b55 Kubernetes version v1.6.3
1804d5d0d6 Merge pull request #45449 from luxas/automated-cherry-pick-of-#44199-upstream-release-1.6
[caleb@bushidobrown azure]$ sha1sum azure_loadbalancer.go
086740f057a8aa0a480b61fb9a7ff97889eed514  azure_loadbalancer.go
```
when using `git am` (the latter example is a later clone of upstream) so at least in this case there doesn't seem to be any difference. After talking with @enisoc he would have preferred the two PRs to be merged into one PR since they hit the same files and actually depend on one another due to refactors.

@karataliu if your e2e test addition cherry picks cleanly onto 1.6 I think it would be fine to add it to this PR or since it seems that there are people waiting for a backport we can cherry pick the e2e PR afterwards.

Regarding the cherry pick tool, is should anyone be concerned that it uses a HTTP vs HTTPS vanity URL? I know very little about security so I thought I'd ask.

The `make verify` failure happens on a fresh checkout (on my machine) so we should probably fix that as a commit here or on a separate PR. What do you think @enisoc? 

Sorry for the trouble on this relatively simple PR but I was excited to cajole @jdumars into pairing because it's been quite awhile since I've had the pleasure of sitting at the command line with another dev.

**Comment by brendandburns** [comment]
I'm ok with the multi-PR in one cherry-pick approach here. Thanks for the explanation @calebamiles

**Comment by enisoc** [comment]
/lgtm

@k8s-bot verify test this

**Comment by jdumars** [comment]
@enisoc it looks like this might be a flake?  Is it possible to re-run the failed test?  We definitely need this in 1.6.4.

**Comment by enisoc** [comment]
@jdumars I'll re-run the test. Regarding 1.6.4, since it's an expedited break-fix release, I'm currently planning that to be a branch off of 1.6.3 that includes only the fix for the subPath issue. If there's some reason this can't wait for the next regularly-scheduled patch release (2-4 week cadence), please explain.

@k8s-bot gce etcd3 e2e test this

**Comment by jdumars** [comment]
@enisoc thank you so much for your work on this!  We don't have to be in 1.6.4 if it's problematic.  The 1.6.5 release is fine.  I assume we'll need to re-run tests etc. before that goes out.  Just let me know if there's anything I can do to help.

**Comment by colemickens** [comment]
@k8s-bot verify test this

**Pull request merged**
