### PR TITLE
apimachinery: fix bugs in a Test function

### PR DESCRIPTION
**Pull request by zxl381**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
There are several goroutine leak problems and `t.Fatalf()` misusage in function `TestConnectionCloseIsImmediateThroughAProxy()`. This PR fixes these bugs.

The change log may look fuzzy because it fixes 2 problems together. In change log, most lines of diff code involving `errCh` are fixing the first problem, and only 2 lines of code involving `serverDone` and `proxyDone` are fixing the second problem.

**The problem about t.Fatalf() misusage**
The test function calls `go runServer()`, and in `runServer()`, `t.Fatalf()` is called if `err != nil`. However, [FailNow (and Fatal, Fatalf) must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test](https://golang.org/pkg/testing). The same misusage happens in `go runProxy()`.

This PR fixes this by adding a channel `errCh` and two `select` to handle error.

**The problem about goroutine leak**
There are other problems even after we fix the misusage of `t.Fatalf()`. 
`t.Fatalf()` will only kill the current goroutine. When it is called in test function, the other goroutines running `runServer()` and `runProxy()` will still be alive, and they will be blocked at the last instruction, which is a send operation to an unbuffered channel.

This PR fixes this by giving 1 buffer to two unbuffered channels (`serverDone` and `proxyDone`), to make sure the send operations will not be blocked. This fix is similar to #84484

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@sanchezl ptal

**Comment by sanchezl** [comment]
@deads2k /lgtm

**Comment by ash2k** [comment]
This makes sense to me.

/lgtm
/retest

**Pull request merged**
