### PR TITLE
CRI: Add fake attach support in CRI.

### PR DESCRIPTION
**Pull request by Random-Liu**
For #31459.

I've tested in my cluster, it works.

@feiskyer @yujuhong

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33815)

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM.

**Comment by feiskyer** [comment]
@k8s-bot gke e2e test this

**Comment by feiskyer** [comment]
@k8s-bot gke e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot gke e2e test this

**Comment by yujuhong** [comment]
LGTM

**Pull request merged**
