### PR TITLE
Renamed ReplicationManager to ReplicationController.

### PR DESCRIPTION
**Pull request by k82cn**
Renamed ReplicationManager to ReplicationController according to TODO comments.

```release-none
Renamed ReplicationManager to ReplicationController
```

### CODE REVIEW

**Comment by kargakis** [comment]
The correct name should be Replicationcontrollercontroller but it's as confusing as ReplicationController.

**Comment by k82cn** [comment]
> The correct name should be Replicationcontrollercontroller but it's as confusing as ReplicationController.

 how about `RCController`?

**Comment by caesarxuchao** [comment]
But we didn't use abbreviation in other controllers, so I'll vote for keeping it as it is.

**Comment by kargakis** [comment]
Yes, as is is the best we can do here I think.

**Comment by k82cn** [comment]
If so, how about removing to TODO comments or refer it to this PR. It'll avoid such kind of PR from others.

**Comment by kargakis** [comment]
Who wrote that comment and how is he/she thinking of fixing this?

**Comment by k82cn** [comment]
It was added at https://github.com/kubernetes/kubernetes/commit/d27ad5b7143995de2cf61315d86d9fb0c57e0ba5#diff-d79787baf9b2ad960d49b76e915c13dfR66 

@gmarek , what's suggestion for that?

**Comment by caesarxuchao** [comment]
@k82cn can we close this pull?

**Comment by gmarek** [comment]
Yeah - it was very long time ago:/ Naming in our controllers is a mess, and RC is particularly bad, but I don't think we can fix it before v2.

**Comment by k82cn** [comment]
@caesarxuchao , @gmarek , sure , I'm ok to close this; but I'm thinking to update comments to avoid  such kind of PR from newbee, e.g. #41732.

**Pull request closed without merging**
