### PR TITLE
Add crassirostris as approver for test/e2e/cluster_logging_*.go

### PR DESCRIPTION
**Pull request by crassirostris**
Adding myself as approver for cluster logging end-to-end tests.

### CODE REVIEW

**Comment by deads2k** [comment]
> Adding myself as approver for cluster logging end-to-end tests.

How about moving the tests to a subfolder?  It would probably be better for general hygiene across the board.

**Comment by crassirostris** [comment]
@deads2k Yes, great idea. I will make it in a separate PR, WDYT?

**Comment by crassirostris** [comment]
I will make another PR after files are moved

**Comment by deads2k** [comment]
> @deads2k Yes, great idea. I will make it in a separate PR, WDYT?

I'd rather not extend approving powers intended for narrow scope across wider scopes.  Not just here, but in general.  I'm certainly supportive of granting you approving powers for the cluster logging tests and reviewer in the test folder if you want it.  If there's a pull that moves the tests and adds an owners file in the sub-dir, I think that serves both our needs.

**Comment by crassirostris** [comment]
@deads2k Oh, yes, definitely! Thanks!

**Pull request closed without merging**
