### PR TITLE
Speculative workaround for #74890

### PR DESCRIPTION
**Pull request by justinsb**
We try using an atomic with a CAS, as a potential workaround for
issue #74890.

Kudos to @neolit123 for the investigation & idea.

This is a speculative workaround - we are really seeing if this is
better; if not we should revert.

If it is better we should file a bug against go 1.12, and then revert!

Issue #74890

/kind failing-test

```release-note
NONE
```

### CODE REVIEW

**Comment by mariantalla** [comment]
Thanks @justinsb & @neolit123 ! We'll keep an eye on this tomorrow.

If it does end up fixing https://github.com/kubernetes/kubernetes/issues/74890, I'm guessing this means we should probably see where this pattern is used elsewhere in the codebase, is that right?

**Review by neolit123 — COMMENTED** [review]
thanks, @justinsb .
if we get a race at least we know we are doing "something"... :[
i did not confirm if go 1.12 caused this and also it's really hard to find when this started...

even if merged this should have at least a couple of runs before making conclusions.

/lgtm
/assign @fejta @spiffxp

**Comment by neolit123** [comment]
@mariantalla 

> Thanks @justinsb & @neolit123 ! We'll keep an eye on this tomorrow.

thanks.

> If it does end up fixing #74890, I'm guessing this means we should probably see where this pattern is used elsewhere in the codebase, is that right?

long term, we need to investigate some sort of real workaround in the code that is flaking (the code that this PR touches).

**Comment by justinsb** [comment]
Yes, the failures seemed to start happening around March 1st, which seems to coincide with moving from 1.11 to 1.12

My 2c:

Hopefully this does not work, and we keep looking and see a mistake somewhere else.

If it does work, I suggest we bring this to the go team, see if they understand the root cause and can either tell us we're doing something wrong, or can repro as a go bug.  Speculation: If it's a go bug, maybe we find out that it's unique to local sync.Once blocks with a defer, in which case we can probably just fix one or two occurrences (I'd guess).  If it's confirmed as a more general problem we'd have to wait for a fix (e.g. go 1.12.1) or revert to the go 1.11 branch.

**Comment by neolit123** [comment]
> Yes, the failures seemed to start happening around March 1st, which seems to coincide with moving from 1.11 to 1.12

ok, so this is concerning and we should get more eyes on it.

> Hopefully this does not work, and we keep looking and see a mistake somewhere else.

i agree.

> If it does work, I suggest we bring this to the go team, see if they understand the root cause and can either tell us we're doing something wrong, or can repro as a go bug. Speculation: If it's a go bug, maybe we find out that it's unique to local sync.Once blocks with a defer, in which case we can probably just fix one or two occurrences (I'd guess). If it's confirmed as a more general problem we'd have to wait for a fix (e.g. go 1.12.1) or revert to the go 1.11 branch.

as far as i know RSC is one of the approvers in the mutex space.
revert to 1.11 does sound like a plan. 1.12 is quite desired for other reasons and if we don't want to be stuck to 1.11 in k8s 1.13 (unless bump it in a patch release).

**Review by BenTheElder — APPROVED** [review]
/approve

**Comment by dims** [comment]
@justinsb @neolit123 seems like a change similar to this was proposed once in
- https://github.com/golang/go/pull/29064/files

See why it was rejected here:
- https://go-review.googlesource.com/c/go/+/152082

for the record it was 
```
The current implementation guarantees that Do only returns after f() returned (either explicitly or by panic'king) but this change does not.

With this change, concurrent calls to Do could return before the call to f() returned (or even started!) which would break most uses of sync.Once.
```

Also, looks like nothing has changed in `once.go` in a while:
https://github.com/golang/go/blame/release-branch.go1.12/src/sync/once.go

**Comment by neolit123** [comment]
> See why it was rejected here:

the reasoning is absolutely valid. our temporary fix is far from ideal.

> Also, looks like nothing has changed in once.go in a while:

that was my observation in the go mutex history as well. the only recent change in our code is this linter fix:
https://github.com/justinsb/kubernetes/commit/6322025d5cfa39112742d014d5c044fa25a9573a#diff-306b2e3f3c8babf6ecd6e4a13ebb9b7e
and i don't see anything breaking here.

so this could simply be a case of resource exhaustion for other unknown reasons, somehow matching the 1.12 switch timing.

**Comment by dims** [comment]
@neolit123 seen this? https://github.com/golang/go/commit/91fd14b82493e592730a3e459ef6610195b854c2 seems like this was backported for https://github.com/golang/go/issues/30470

**Comment by neolit123** [comment]
@dims good find.

a bug in deferred stack allocated closures sounds like a lot of fun,
so technically this can be a problem outside of `Once` too.

one more reason for me to not like passing function objects around in this language (i.e. no root object code symbols).

this link suggests a monthly cadence for PATCH releases:
https://golang.org/doc/devel/release.html#go1.11.minor

**Comment by neolit123** [comment]
posted comment related to the closure bug here:
https://github.com/kubernetes/kubernetes/issues/74890#issuecomment-472479267

**Pull request merged**
