### PR TITLE
Clean cross-build image and update to protoc 3.0.2

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: go1.10 introduced a build cache, which meant we've been shipping an extra few hundred MB with the cross-build image since:
```console
$ docker images | grep cross
k8s.gcr.io/kube-cross            v1.11.1-1    3b1be8db530f    13 days ago         2.25GB
k8s.gcr.io/kube-cross            v1.10.3-1    aeec97de219a    3 months ago        2.08GB
k8s.gcr.io/kube-cross            v1.9.3-2     32285b178de2    8 months ago        1.74GB
```

By adding `go clean -cache`, we can remove this cruft from the image:
```
staging-k8s.gcr.io/kube-cross    v1.11.1-2    d1b229308de8    9 minutes ago       1.7GB
```

Additionally, we've been using a beta version of `protoc` for years (`3.0.0-beta.2`), so I updated this to the corresponding stable release (`3.0.2`). I also switched to using the built release, rather than compiling it.

We could in theory update this to something more recent (e.g. `3.5.1`, which is regularly tested by golang/protobuf and gogo/protobuf), but I'm not sure if it'd have unintended changes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @BenTheElder @cblecker 
cc @thockin I guess?

**Comment by cblecker** [comment]
/kind feature
/sig release
/lgtm
/approve

Great catch!

**Comment by ixdy** [comment]
partial credit to @BenTheElder, who pointed out that the kube-cross image was getting rather large.

**Comment by ixdy** [comment]
The change in time to `make quick-release` on my workstation is basically noise, so I don't believe this has any notable build performance impacts.

**Review by BenTheElder — APPROVED** [review]
/lgtm
tested perf offline, the drop in image size will be welcome :-)

**Comment by cblecker** [comment]
/hold
Pausing retest loop

**Comment by ixdy** [comment]
tests are all passing

**Pull request merged**
