### PR TITLE
emit more info on failure

### PR DESCRIPTION
**Pull request by lavalamp**
help debug #31810

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31833)

### CODE REVIEW

**Comment by rmmh** [comment]
@k8s-bot: test this issue #31838

**Comment by rmmh** [comment]
@k8s-bot test this issue: #31838

**Comment by rmmh** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by lavalamp** [comment]
Changing reviewer. Would like to get this in to make progress debugging this.

**Comment by pwittrock** [comment]
@lavalamp Should this be cherry-picked?

**Comment by lavalamp** [comment]
Might as well. Will help debug tests if they fail on the release branch.

**Pull request merged**
