### PR TITLE
Fix bug in kubectl wait JSONPath expression containing equal sign.

### LINKED ISSUE #1259: kubectl wait doesn't support complex jsonpath
### What would you like to be added?

The JSONPath extension for `kubectl wait` added in kubernetes/kubernetes#105776 naively splits the argument to `--for` into three parts using `=` as the boundary character. That's pretty straightforward, but then I wanted to do this:
```
kubectl wait --for jsonpath='{.status.containerStatuses[?(.name=="my-container-name")].ready}=true'
```
which has five parts using that code. It would be nice to use expressions like this, rather than hard-coding the array index.

Assuming that the RHS doesn't need to be a full JSONPath expression, I think(!) this should be a fairly straightforward change.

### Why is this needed?

The documentation doesn't mention any limitations on what kind of JSONPath expressions may be used, so it's surprising that this is not possible. Indeed, the error message you get back—that the format must be <example>—isn't especially helpful, particularly since my expression did in fact match that format. I assume that it's an oversight that the functionality is not available rather than the documentation is incomplete.

### LINKED ISSUE #111359: kubectl wait doesn't support complex jsonpath
### What would you like to be added?

The JSONPath extension for `kubectl wait` added in #105776 naively splits the argument to `--for` into three parts using `=` as the boundary character. That's pretty straightforward, but then I wanted to do this:
```
kubectl wait --for jsonpath='{.status.containerStatuses[?(.name=="my-container-name")].ready}=true'
```
which has five parts using that code. It would be nice to use expressions like this, rather than hard-coding the array index.

Assuming that the RHS doesn't need to be a full JSONPath expression, I think(!) this should be a fairly straightforward change.

### Why is this needed?

The documentation doesn't mention any limitations on what kind of JSONPath expressions may be used, so it's surprising that this is not possible. Indeed, the error message you get back—that the format must be <example>—isn't especially helpful, particularly since my expression did in fact match that format. I assume that it's an oversight that the functionality is not available rather than the documentation is incomplete.

### PR DESCRIPTION
**Pull request by brianpursley**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Previous code would split on equal sign, but this caused a problem if the JSONPath expression itself contained an equal sign. 

This PR changes the split functionality to only split on the first and last equal sign so that the JSONPath expression can contain any number of equal signs without an error occurring, enabling this to work:

```
kubectl wait pod foo --for jsonpath='{.status.containerStatuses[?(.name=="bar")].ready}'=true
```

#### Which issue(s) this PR fixes:
Fixes kubernetes/kubectl#1259

#### Does this PR introduce a user-facing change?
```release-note
Fixed a bug in kubectl wait where an error would occur if you attempted to wait for a JSONPath condition containing an equal sign
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by brianpursley** [comment]
/hold
for review

**Comment by brianpursley** [comment]
/assign @eddiezane 

Eddie, thoughts on this bug fix?

**Comment by mpuckett159** [comment]
There's something about this that is irking me but I'm struggling to explain why. I think splitting on the `=` is not good. I'm going to do some tests but I think splitting on the `}` would be better than on equals basically. From what I remember I believe that the jsonpath syntax is supposed to wrapped completely in `{...}` which should never show up in the outer syntax of `jsonpath={...}=<string>`. Using curly braces would give us something a bit more unique to split on and be less prone to weird issues like this I think.

**Comment by brianpursley** [comment]
@mpuckett159 I see where your going with that, but I think we have to be careful about including quotes in the split logic.

For example, all of these work the same currently:
```
kubectl wait --for=jsonpath='{.status.phase}'=Running pod/pod1
kubectl wait --for=jsonpath="{.status.phase}"=Running pod/pod1
kubectl wait --for=jsonpath={.status.phase}=Running pod/pod1
```

As an aside, quoting inside the jsonpath expression can work by using a different quote (ie. `'` inside `"`), or escaping (ie `\"` inside `"`).

I think continuing to split on `=` (just doing it more flexibly) ensures that all existing behavior is preserved.

**Comment by mpuckett159** [comment]
Ah yeah, well, rather than write some regex to handle all those cases, I agree splitting and doing those checks works just fine and is more readable, plus we can get some more detailed error messages out of them. In that case this LGTM.

/lgtm

**Comment by andreaskaris** [comment]
This suggested PR and approach doesn't work any more since https://github.com/kubernetes/kubernetes/pull/118160 merged.

I have a suggestion for a fix here that will split on singled "=" but not on "==":
https://github.com/kubernetes/kubernetes/pull/118748

**Comment by brianpursley** [comment]
I'm having difficulty rebasing this PR, and it is because handling equal signs has become much more difficult after https://github.com/kubernetes/kubernetes/pull/118160 was merged.  Now, there may or may not be a value, so we can't assume that there are 3 parts that need to be split.

Specifically, all of these need to be handled correctly:
* `jsonpath='{.status.phase}'=Running`
* `jsonpath='{.status.containerStatuses[?(.name=="foo")].ready}'=True`
* `jsonpath='{.status.containerStatuses[?(.name=="foo")].ready}`

Notice the third example above.

**Comment by andreaskaris** [comment]
@brianpursley  Can you have a look at https://github.com/kubernetes/kubernetes/pull/118748

**Comment by brianpursley** [comment]
> @brianpursley Can you have a look at #118748

Does it have unit tests that cover the three cases I mentioned above?

**Comment by andreaskaris** [comment]
Yes

**Comment by brianpursley** [comment]
Ref https://github.com/kubernetes/kubernetes/pull/118748

**Pull request closed without merging**
