### PR TITLE
Add --dry-run option for label command

### LINKED ISSUE #11488: kubectl --dry-run
kubectl should support a --dry-run option for every mutation to show what it would do, without actually doing it

We might need API changes in order to make this high-fidelity. For instance, if we wanted to know what a pod config would look like after admission control populated defaults, we'd need to execute most of the creation path.

### PR DESCRIPTION
**Pull request by hurf**
Partially fixes:  #11488

With --dry-run option, label command will print the object locally
without update it on server side.

### CODE REVIEW

**Comment by hurf** [comment]
@bgrant0607 - For other mutations like `create` and `delete`, we may need to change the api to accept new params. I'll fix those in following PRs.

**Comment by bgrant0607** [comment]
Mutations with --dry-run should still get the resource from the server and apply their updates to that rather than to the local resource (unless --local were also specified).

cc @kubernetes/kubectl

**Comment by hurf** [comment]
@bgrant0607 - It seems the PR is doing as you described. In this PR, input is kind and name, object is retrieved form server, and then updated, --dry-run just controls whether the updated object will be sent to the server or not.

**Comment by bgrant0607** [comment]
Great, thanks.

**Comment by kargakis** [comment]
LGTM

**Comment by jlowdermilk** [comment]
lgtm. needs rebase

**Comment by jlowdermilk** [comment]
@k8s-bot test this

**Comment by hurf** [comment]
@k8s-bot test this please.

**Comment by quinton-hoole** [comment]
I restarted the Shippable test, as the failure looks like a flake.

**Pull request merged**
