### PR TITLE
Modify setConfigDefaults() in batch_client.go

### PR DESCRIPTION
**Pull request by lixiaobing1**
File "pkg/client/clientset_generated/internalclientset/typed/batch/unversioned/batch_client.go", line 83 :
        //if config.Version == "" {
        copyGroupVersion := g.GroupVersion
        config.GroupVersion = &copyGroupVersion
        //}
Here line 83 and 86 are dead code, can be deleted.

### CODE REVIEW

**Comment by deads2k** [comment]
This code is generated, you'd have to change it in `cmd/libs/go2idl/client-gen/generators/generator_for_group.go`, but I'd like to keep the two commented lines so its obvious what conditional we want to add back in.

**Comment by jfrazelle** [comment]
looks good to me!

**Comment by deads2k** [comment]
> looks good to me!

@jfrazelle Removed the tag. This file is generated, so it shouldn't be modified directly.  The permissions on the file were changed too.  Also, those lines are useful as a reminder for how we want to conditionalize based on the comment.

**Comment by jfrazelle** [comment]
crap my bad

**Pull request closed without merging**
