### PR TITLE
context.Context should be the first parameter of a function in vsphere

### PR DESCRIPTION
**Pull request by yu8833**
**What this PR does / why we need it**:
Change the position of the context.Context parameter.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
golint
**Release note**:

```release-note
```

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36724)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by YuPengZTE** [comment]
@dims PTAL, thanks.

**Comment by dims** [comment]
@YuPengZTE I am not that familiar with this part of the tree. requesting @mikedanese as he is listed as one of the owners of pkg/cloudprovider branch currently

**Comment by BaluDontu** [comment]
@YuPengZTE: Is it a convention to use context information as first parameter always?

**Comment by mikedanese** [comment]
@BaluDontu yes it is convention. Document in godoc.org/context.

**Pull request merged**
