### PR TITLE
[WIP] update heketi to a version that does not vendor kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by sigma**
**What this PR does / why we need it**:

Before this change, heketi vendors kubernetes/kubernetes, at an old
version (1.6.4).
There are a few issues with that:
- 1.6.4 is old, and unsupported, so it's not super useful
- vendoring kubernetes/kubernetes is not supported
- it gets in the way of vgo adoption (see #65683 for details)

This change introduces a new version of heketi that's:
- much more recent (v7.0.0 instead of v4.0.0+)
- uses only kubernetes/{api,apimachinery,...}

As such it should ease vgo transition, and generally cleanup our dependency
graph.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Not ready for merging. Would have to make it to heketi upstream first. Instead, the code currently lives in https://github.com/sigma/heketi/tree/hack/v7-k8s which will make verification fail. I'm more interested in verifying e2e glusterfs tests right now.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
xref  https://github.com/kubernetes/sig-release/issues/223 and https://github.com/kubernetes/steering/issues/57. Not really related to this PR, but I think we want to avoid vendoring heketi/heketi in the future due to licensing issues.

> The component github.com/heketi/heketi is used in four repos. Heketi uses a mix of licenses, but the main issue is that files in heketi/pkg/utils/ can only be used under LGPL-3.0 or GPL-2.0, both of which are likely problematic here. Can the files in heketi/pkg/utils/ be removed, or replaced with an alternative library under a more permissive license? 

fyi @justaugustus

**Comment by nikhita** [comment]
/cc @cblecker @thockin 

this dep update also has license changes.

**Comment by sigma** [comment]
@nikhita thanks for the pointers.

Maybe another possibility would be to get heketi to clarify that heketi/pkg/utils is actually covered by Apache 2?
It seems to me that was the intent since the code was initially living in https://github.com/heketi/utils which is explicitly Apache 2. And also the code in this package is very trivial, so I don't think it's intended to be (L)GPL, rather it was caught in the wholesale re-licensing in https://github.com/heketi/heketi/pull/572 ?
(especially since the client code is explicitly Apache 2, so having a (L)GPL dependency in the repo seems like an oversight)

Finally, the few functions that we actually need from heketi/pkg/utils have almost not changed since they where re-imported from https://github.com/heketi/utils
So worst case, forking the interesting parts and have the fork under a k8s-friendly license seems pretty straightforward, if that's what we want (I'm happy to do it if need be)

Anyway, might be worth exploring.

**Comment by nikhita** [comment]
@sigma just noticed https://github.com/heketi/heketi/issues/1279 and have commented there. Thanks for creating the issue! :)

**Comment by obnoxxx** [comment]
@nikhita @sigma we will fix the licensing in heketi.

**Comment by justaugustus** [comment]
Thanks @obnoxxx. Please ping @nikhita, @sigma, and myself when you have a chance to remedy this. :)

**Comment by obnoxxx** [comment]
@sigma I don't understand how vendoring or not vendoring kubernetes (in the heketi repo) is relevant to this PR. Kubernetes only vendors those pieces of the heketi repo that it uses (client and a few utils). So how can this PR be named "update heketi to not vendor kubernetes/kubernetes"? That does not seem to be what it does (to me). Instead it updates the heketi client to a newer version.

Updating heketi might be useful for picking up some bugfixes, but generally it is not a strict requirement, because the pieces that the kubernetes gluster plugin uses have not really changed significantly. (e.g. the new block-volume feature is not used at all). Still good to update.

Then again, we should think about heketi master using kubernetes master and kubernetes master using heketi master, etc. Without needing to copy into the tree or lock down a specific git hash. For releases versions, we should lock down. Have I mentioned anywhere that dependencies in golang are a real mess? :-)

**Comment by sigma** [comment]
@obnoxxx sorry, the title is indeed slightly misleading. Should be "update heketi to a version that doesn't vendor kubernetes/kubernetes". And the implication is that in particular it doesn't vendor an old and incompatible version of kubernetes, which happens to be the reason why it's a problem for us.

So I guess I'm mixing the remediation and the rationale a little bit in there. Will fix :)

**Comment by dims** [comment]
@sigma Can you please rebase this PR? let's see if we can get this into the next release

**Comment by sigma** [comment]
@dims this PR is blocked pending the merging of heketi/heketi#1272 (which is in turn waiting on heketi/heketi#1373) which will provide the upstream version of heketi that doesn't have those dependencies to k/k

**Comment by dims** [comment]
@sigma ack thanks!

**Comment by dims** [comment]
we can close this out right @sigma ?

**Comment by sigma** [comment]
@dims no I don't think so, we're still waiting on heketi to be in a state where k8s.io/kubernetes is not vendored

**Comment by dims** [comment]
aha! thanks @sigma

**Comment by cblecker** [comment]
/uncc
assign back when ready for review

**Pull request closed without merging**
