### PR TITLE
Remove Feature label from OutOfDisk e2e test

### PR DESCRIPTION
**Pull request by crassirostris**
Fix https://github.com/kubernetes/kubernetes/issues/35722

Related to https://github.com/kubernetes/kubernetes/pull/35551 and https://github.com/kubernetes/kubernetes/pull/36225

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36743)

### CODE REVIEW

**Comment by Crassirostris** [comment]
@piosz

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
@madhusudancs

**Comment by madhusudancs** [comment]
@Crassirostris @piosz thanks!

**Comment by piosz** [comment]
@saad-ali adding milestone 1.5 to let this in. This just enable disabled e2e test.

**Comment by saad-ali** [comment]
> @saad-ali adding milestone 1.5 to let this in. This just enable disabled e2e test.

Ack. Thanks

**Comment by Crassirostris** [comment]
@k8s-bot bazel test this
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
