### PR TITLE
copy ServerAddressByClientCIDR to federation types

### PR DESCRIPTION
**Pull request by jianhuiz**
#24016

copy ServerAddressByClientCIDR to federation types
update generated files

[Analytics]()

### CODE REVIEW

**Comment by nikhiljindal** [comment]
We have so much generated code!
The actual code change is not more than 50 lines. And the PR size is 850 lines :)

lgtm, thanks!

**Comment by nikhiljindal** [comment]
ok to test

**Comment by nikhiljindal** [comment]
`hack/verify-codegen.sh` failed.
Can you please take a look?

**Comment by nikhiljindal** [comment]
@k8s-bot: unit test this issue: https://github.com/kubernetes/kubernetes/issues/23822

@k8s-bot node e2e test this

**Comment by nikhiljindal** [comment]
pkg/offers failed again

@k8s-bot: unit test this issue: #23822

**Comment by nikhiljindal** [comment]
`contrib/mesos/pkg/offers` is failing continuously on this PR.
@jianhuiz Can you please take a look? Does it fail for you locally?

Ref https://github.com/kubernetes/kubernetes/issues/23822

**Comment by jianhuiz** [comment]
@nikhiljindal It doesn't fail for me.
What about I do a rebase?

**Comment by nikhiljindal** [comment]
That is strange. It has failed continuously the last 3 times.
I dont see how rebase will help.
Trying once more.

@k8s-bot: unit test this issue: #23822

**Comment by nikhiljindal** [comment]
Hopefully https://github.com/kubernetes/kubernetes/pull/24916 will be merged soon which fixes  #23822.
We can rebase after that is merged if we do not get a green run until then.

**Comment by nikhiljindal** [comment]
Sigh same failure again.

Feel free to rebase if you think it will help

**Comment by nikhiljindal** [comment]
haha it passed by rebase :)
Adding the LGTM tag, thanks!

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/24620

**Comment by nikhiljindal** [comment]
ok to test

**Comment by jianhuiz** [comment]
rebased

**Comment by nikhiljindal** [comment]
Thanks, readding LGTM

**Pull request merged**
