### PR TITLE
Temporarily disable goroutine calls to testing.T.Logf to avoid race

### LINKED ISSUE #23533: unit flake: TestEventf is racy
WARNING: DATA RACE
Write by goroutine 32:
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:353 +0x1e6
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:366 +0x82
  testing.(*common).Logf-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:351 +0x5f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:216 +0x2a7
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:237 +0x14e

Previous read by main goroutine:
  runtime.convT2E()
      /usr/local/go/src/runtime/iface.go:128 +0x0
  testing.(*T).report()
      /usr/local/go/src/testing/testing.go:538 +0xa18
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:591 +0xbdf
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/pkg/client/record/_test/_testmain.go:70 +0x210

Goroutine 32 (running) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:239 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:217 +0xa5
  k8s.io/kubernetes/pkg/client/record.TestEventf()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:351 +0x3034
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/23527/kubernetes-pull-test-unit-integration/19502/build-log.txt

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #23533.

I'll create an issue to remind us to uncomment the lines after upgrade Go. [Update] #23690

@wojtek-t @ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
:+1:

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by ncdc** [comment]
Once all the tests are green do we want to manually merge this to prevent additional submit queue stoppages stemming from this issue?

**Comment by wojtek-t** [comment]
@ncdc - sure - that makes sense

**Comment by wojtek-t** [comment]
Tests passing - merging manually

**Pull request merged**
