### PR TITLE
Add NodeSelector to the PodTemplate in v1beta1.

### PR DESCRIPTION
**Pull request by brendandburns**
@bgrant0607

### CODE REVIEW

**Comment by brendandburns** [comment]
Addresses at least part of #3801

**Comment by dchen1107** [comment]
Shouldn't you update v1beta2 too?

**Comment by brendandburns** [comment]
Done.  ptal.

Thanks!
--brendan

**Comment by smarterclayton** [comment]
Can you undo the code in api/serialization_test.go that clears NodeSelector from fuzzing, so it is now properly represented in round trip tests?

**Comment by brendandburns** [comment]
Done.  ptal

**Comment by smarterclayton** [comment]
Lgtm

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
