### PR TITLE
Enable cluster autoscaling in e2e tests using gcloud command

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @piosz @fgrzadkowski @jszczepkowski

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by jszczepkowski** [comment]
It will be nice to rewrite also isAutoscalerEnabled method.

**Comment by mwielgus** [comment]
Yes, i will do it once e2e pass with gcloud update. One change at a time :).

**Comment by jlowdermilk** [comment]
@mwielgus this broke the cluster autoscaling tests on GKE: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-autoscaling/815/

**Comment by mwielgus** [comment]
Not really. Enabling cluster autoscaling on gke became somehow significantly slower. I increased the timeout and hopefully the tests would get back to green.

**Comment by mwielgus** [comment]
And unfortunately you were right, @jlowdermilk, there was also a bug in cluster update in gcloud - it skips node pool name and thus cluster autoscaler can be turned on only for the default node pool -> 1 e2e test is failing.

**Pull request merged**
