### PR TITLE
cgroup names created by kubelet should be lowercased

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What this PR does / why we need it**:
This PR modifies the kubelet to create cgroupfs names that are lowercased.  This better aligns us with the naming convention for cgroups v2 and other cgroup managers in ecosystem (docker, systemd, etc.)

See: https://www.kernel.org/doc/Documentation/cgroup-v2.txt
"2-6-2. Avoid Name Collisions"

**Special notes for your reviewer**:
none

**Release note**:
```release-note
kubelet created cgroups follow lowercase naming conventions
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
for reference, i believe future users will view our naming syntax confusing with its use of mixed case.  as a result, i think this is a bug.  there is no issue to reference, as users have not tried integrating or introspecting the cgroupfs yet.

**Comment by smarterclayton** [comment]
Agree this is a bug in that we are potentially causing problems in the future

**Comment by sjenning** [comment]
@derekwaynecarr i think this needs to be updated too

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/pods_container_manager_test.go#L157

or here

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/pods_container_manager_test.go#L64

**Review by vishh — APPROVED** [review]

**Comment by vishh** [comment]
One more option is to have cgroup manager default to lower case names. It might break tests though and could lead to confusion if the defaulting isn't obvious.

**Comment by vishh** [comment]
Will tag once the tests pass.

**Comment by derekwaynecarr** [comment]
everything but the cross build is happy due to node problem detector problems.

**Comment by derekwaynecarr** [comment]
rebased, retagging.

**Comment by derekwaynecarr** [comment]
@k8s-bot kops aws e2e test this

**Comment by derekwaynecarr** [comment]
GCE failure is https://github.com/kubernetes/kubernetes/issues/42597

The other is a federation flake not impacted by this pr.

**Comment by derekwaynecarr** [comment]
@k8s-bot unit test this
@k8s-bot cvm gce e2e test this

**Comment by vishh** [comment]
Uff! Finally it's merged...

**Pull request merged**
