### PR TITLE
Fix indentation/spacing in comments to render correctly in godoc

### LINKED ISSUE #111701: Fix godocs autoformatting from upgrading to go 1.19
### What happened?

Reference Comment: https://github.com/kubernetes/kubernetes/pull/111254#issuecomment-1195794968

Based on the diff: https://github.com/kubernetes/kubernetes/pull/111254/files, there are a couple areas where indentations are turned into paragraphs, indentations are turning regular comments into code blocks, etc.

I think there are a couple things we need to do (could be in separate PRs):

1. Scan the original PR (see above) and fix the indentations in places where a paragraph is not supposed to occur. A good example is https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/cmd/kube-apiserver/app/testing/testserver.go#L96-L99
2. Some indentations should be changed into lists, eg: https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/pkg/apis/core/types.go#L3222-L3226
3. Unrelated to the previous PR, scan the k8s types and reformat bullet points using `*` to use `-`. go1.19 does not recognize `*` as bullet points. For example: https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/staging/src/k8s.io/api/core/v1/types.go#L495-L496
4. Ensure our swagger doc generation properly supports the new list format  https://github.com/kubernetes/kubernetes/pull/111505

I hope this roughly captures the intent of the comment by liggitt.
/cc @liggitt 
/cc @dims 

/help

### What did you expect to happen?

See above

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

Fixes incorrect indentation/line breaks inserted by go1.19 gofmt

Fixes https://github.com/kubernetes/kubernetes/issues/111701

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@liggitt what are you running to fix these back?

**Comment by liggitt** [comment]
Scanned the changes in the original PR and manually fixed wrong ones. 

Gofmt weirdly indented lines that continued and indented a space. I just deleted the blank line it inserted and made the continuation be at the same indent level

**Comment by dims** [comment]
thanks @liggitt ! i can confirm that you indeed did that :)

/approve
/lgtm

**Comment by tengqm** [comment]
Looks like gofmt is attempting to "fix" indentation in comments by inserting TABs. That is a weird behavior.

**Comment by liggitt** [comment]
> Looks like gofmt is attempting to "fix" indentation in comments by inserting TABs. That is a weird behavior.

it is treating the subsequent indented lines as list items or code blocks, and indenting them with a separating line break to set them apart from the preceding text and make it clearer how the comments will actually be interpreted. 

See https://tip.golang.org/doc/go1.19#go-doc and https://tip.golang.org/doc/comment for details

**Pull request merged**
