### PR TITLE
Guarantee watch before action in e2e event observer helper function.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
**What this PR does / why we need it**:

Adds a missing synchronization barrier to an e2e event observation helper function.

- This change should guarantee that in observeEventAfterAction,
  the action is only executed after the informer begins watching
  the event stream.

**Release note**:

```release-note
NONE
```

cc @kubernetes/sig-scheduling-pr-reviews @bsalamat

### CODE REVIEW

**Comment by bsalamat** [comment]
Thanks Connor for fixing this.

**Comment by ConnorDoyle** [comment]
Cc @timothysc

**Comment by timothysc** [comment]
> This change should guarantee that in observeEventAfterAction,
the action is only executed after the informer begins watching
the event stream.

@ConnorDoyle , I'm slightly confused... how could the action be executed prior to the event stream?

**Comment by aveshagarwal** [comment]
@ConnorDoyle Trying to understand here, if this logic is really needed in both functions. 

So you are doing this, i think with the assumption, that when controller.Run is executed, watch might not have started, before in the immediate next step action is executed and it has a chance of missing the event/node update? May be like in nanosecond order.

And then, later down the code, you are polling waiting for the event/node update upto 2 mins (order of mins), with the assumption, that the even/node update might not have appeared upto 2 mins?

**Comment by ConnorDoyle** [comment]
@timothysc and @aveshagarwal, here's an illustration of the before/after scenarios around this PR as I understand it:

Before: no ordering gurarantee between concurrent test and informer goroutines.

```
go test
   |
   |
 go controller.Start ---- controller.Start()
   |                         |
 action()                 f.ClientSet.Core().Events(f.Namespace.Name).Watch(options)
   |                         |
 ...                       ...
```

After: added synchronization to provide ordering guarantee.

```
go test
   |
   |
 go controller.Start ---- controller.Start()
   |                         |
   |                      f.ClientSet.Core().Events(f.Namespace.Name).Watch(options)
   |                         |
   |                      close(informerStarted)
   |
 <-informerStarted
   |
 action()
 ...
```

**Comment by aveshagarwal** [comment]
@ConnorDoyle I think I get that. I was wondering if it brings any real advantage in most (or all practical e2e) scenarios. May be like in a corner case that might not be experienced ever. That said I dont see any harm really in doing this and it LGTM.

**Review by timothysc — APPROVED** [review]

**Comment by timothysc** [comment]
@ConnorDoyle gotcha... I have other comments about some of the logic but we can hold off and revisit, b/c I want to see @bsalamat 's flake patch get in.

**Comment by bsalamat** [comment]
@aveshagarwal as @ConnorDoyle graph shows, there was a clear race condition between starting the watch and performing the action. Please note that the event that we are watching for happens as a result of `action`. Without Connor's change, the action could happen before starting the watch (and therefore missing the event). Connor's change improves reliability of our event watching mechanism.

**Comment by aveshagarwal** [comment]
@bsalamat Thats what I was trying to understand/explain in https://github.com/kubernetes/kubernetes/pull/43107#issuecomment-286781856, what is the probability of that happening, given that the polling code waits for upto 2m?

**Comment by ConnorDoyle** [comment]
@aveshagarwal the race occurs before the test goroutine begins polling. More generally, the point behind the PR that depends on this (#42928) is to rely on causality, not timing in the scheduling e2e tests. The point is to eliminate the need for speculation about probabilities of the various interleavings based on expected timings.

**Pull request merged**
