### PR TITLE
Add missing ppc64le architecture in the get-kube* scripts

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR is for adding the missing architecture in the cluster/get-kube* scripts
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
this may just be the most straightforward PR to cluster/ in a long time :-)
/lgtm
/approve

**Comment by mkumatag** [comment]
@kubernetes/milestone-maintainers can someone help me get the milestone tagged?

**Comment by mkumatag** [comment]
> /milestone v1.19

Thanks for a quick response :)

**Pull request merged**
