### PR TITLE
ignoredResources should contain events.k8s.io events

### LINKED ISSUE #108318: controller-manager gc sync event failed
### What happened?

15:30:38.355384    2136 graph_builder.go:279] garbage controller monitor not yet synced: events.k8s.io/v1, Resource=events

var ignoredResources = map[schema.GroupResource]struct{}{
	{Group: "", Resource: "events"}: {},
}

ignoredResources group miss match with api-resource

events.k8s.io/v1

### What did you expect to happen?

ignore sync event

### How can we reproduce it (as minimally and precisely as possible)?

etcd have event key more than 4 million
restart kube-apiserver or controller-manager

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.20.7
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by niuyueyang1996**
events group fix

#### Which issue(s) this PR fixes:

Fixes #108318 

#### Does this PR introduce a user-facing change?

```release-note
fix ignored resources group for missing events.k8s.io/v1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/retitle ignoredResources should contain events.k8s.io events
/kind bug
/release-note-none

**Comment by ialidzhikov** [comment]
> /release-note-none
I think this PR deserve a release note.

**Comment by pacoxu** [comment]
> I think this PR deserves a release note.

/release-note-edit
```release-note
fix ignored resources group for missing events.k8s.io/v1
```

**Comment by liggitt** [comment]
I'm not sure why events aren't permitted to be owners for garbage collection, but they were ignored from the very beginning. However, this was also paired with a validation rule that forbids setting a v1 Event as an owner: 

https://github.com/kubernetes/kubernetes/blob/422001df8b694f20e7c781808408a470bed3249c/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L39-L41

That ensured no one was confused by setting an ownerReference to an event that apparently doesn't work. Tightening that validation restriction to also forbid events.k8s.io/v1 Events is not a backwards compatible change, and there could already be data persisted that uses owner references that way.

**Comment by niuyueyang1996** [comment]
i think event will be gc by apiserver ttl without gccontroller.
if event more than 4million，gc controller will not start successfully.

**Comment by liggitt** [comment]
/lgtm
/approve

since this can put enormous unintended pressure on the GC watchers

however, we need to follow up to resolve `BannedOwners` not including events.k8s.io events... please open an issue to track adding that validation in a ratcheting way
/hold for follow-up issue

**Comment by ialidzhikov** [comment]
@liggitt how we continue with PR?

**Comment by liggitt** [comment]
> however, we need to follow up to resolve `BannedOwners` not including events.k8s.io events... please open an issue to track adding that validation in a ratcheting way
> /hold for follow-up issue

please open the follow up issue to track adding events.k8s.io Events to BannedOwners to make sure we don't lose track of the other part of this issue

**Comment by dims** [comment]
/lgtm cancel

@niuyueyang1996 this needs a rebase

**Comment by niuyueyang1996** [comment]
i find this problem has been fixed  in master.

**Pull request closed without merging**
