### PR TITLE
e2e/framework: update kubernetes-anywhere path

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
e2e/framework: update kubernetes-anywhere path

was updated here:
https://github.com/kubernetes/test-infra/pull/9205/files#diff-1348bfba2403286944b343e21e901c14R554

failing test because of this:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master/2609#master-upgrade-sig-cluster-lifecycle-master-upgrade

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

/kind failing-test
/cc @BenTheElder @timothysc 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/lgtm
per the referenced links in the description.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
I'm also ok with letting this wait till merge queue opens back up.

**Comment by neolit123** [comment]
look like it didn't fix these type of tests:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master/2643#master-upgrade-sig-cluster-lifecycle-master-upgrade

**Pull request merged**
