### PR TITLE
Automated cherry pick of #70699: Include read access to controllerrevisions for

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #70699 on release-1.10.

#70699: Include read access to controllerrevisions for

### CODE REVIEW

**Comment by MaciekPytel** [comment]
Looks good, but I'd prefer someone with more context to lgtm.

**Comment by liggitt** [comment]
> Looks good, but I'd prefer someone with more context to lgtm.

sounds good

/assign @dims 
as [original lgtm-er](https://github.com/kubernetes/kubernetes/pull/70699#issuecomment-437730288)

**Comment by liggitt** [comment]
@dims is ooo.
/assign @soltysh

**Comment by dims** [comment]
oops! back now :)

/lgtm

**Pull request merged**
