### PR TITLE
Support intermediate certificate in certificate store

### PR DESCRIPTION
**Pull request by jackkleeman**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
Currently the certificate store only write a single certificate into its certificate file, even if Update is provided with a certificate chain. We'd like kubelet rotation to be able to handle intermediates, so we should write the full chain, in order given, into the file, and parse it back out again into a tls Certificate.

**Does this PR introduce a user-facing change?**:

```release-note
client-go certificate manager rotation gained the ability to preserve optional intermediate chains accompanying issued certificates
```

### CODE REVIEW

**Comment by jackkleeman** [comment]
Pushed fixing a typo in comment

**Comment by liggitt** [comment]
from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88744/pull-kubernetes-node-e2e-containerd/1234575403197140992/:
> OCI runtime start failed: container process is already dead: unknown

from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88744/pull-kubernetes-e2e-kind/1234575396477865984:
```
	[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/4.15.0-1044-gke\n", err: exit status 1
I0302 20:35:16.044568     142 checks.go:406] checking whether the given node name is reachable using net.LookupHost
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 4.15.0-1044-gke
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
```

/retest

**Comment by liggitt** [comment]
change matches my expectations

/lgtm
/approve

**Pull request merged**
