### PR TITLE
Pass location parameter to event exporter.

### PR DESCRIPTION
**Pull request by serathius**
**What this PR does / why we need it**:
This PR makes event-exporter export cluster location together with events.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
/ok-to-test
/approve no-issue

You should also modify the `cluster/gce/gci/configure-helper.sh` file

**Comment by crassirostris** [comment]
@roberthbailey Could you please approve?

**Comment by crassirostris** [comment]
@serathius 

```
Jan 10 16:29:36.625662 e2e-14908-master configure-helper.sh[1265]: /home/kubernetes/bin/configure-helper.sh: line 2056: ZONE: unbound variable
```

Replace `${ZONE}` with `${ZONE:-}`

**Comment by serathius** [comment]
@crassirostris all required tests passed.

**Comment by crassirostris** [comment]
@serathius Could you please add test logic to https://github.com/kubernetes/kubernetes/blob/master/test/e2e/instrumentation/logging/stackdrvier/basic.go#L141 to verify that location is set correctly? Expected value should be somewhere in the CloudContext

**Comment by crassirostris** [comment]
/lgtm

Thanks!

**Comment by Random-Liu** [comment]
@crassirostris I guess this PR broke the stack driver test.
https://k8s-testgrid.appspot.com/google-gce#gci-gce-sd-logging

**Comment by serathius** [comment]
@Random-Liu Started investigating

**Pull request merged**
