### PR TITLE
kubelet: check the status of the pod after update

### PR DESCRIPTION
**Pull request by yujuhong**
This PR is for debugging #17656

### CODE REVIEW

**Comment by yujuhong** [comment]
Did not test it myself locally. Will wait to see if e2e passes.

**Comment by timstclair** [comment]
LGTM

**Comment by yujuhong** [comment]
Found the function for testing the equality of status (`isStatusEqual`). Will update PR tomorrow.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by timstclair** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot tst this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
No longer needed.

**Pull request closed without merging**
