### PR TITLE
Automated cherry pick of #37413 #36840 upstream release 1.4

### PR DESCRIPTION
**Pull request by BaluDontu**
Automated cherry pick of #37413 #36840 origin release 1.4

@abrarshivani @pdhamdhere @kerneltime

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37867)

**Comment by BaluDontu** [comment]
@jessfraz: Can you take a look at this please.

**Comment by jessfraz** [comment]
@k8s-bot test this please #IGNORE

**Comment by jessfraz** [comment]
@k8s-bot kubemark e2e test this

**Comment by jessfraz** [comment]
all tests are green so merging manually

**Pull request merged**
