### PR TITLE
fix typo in dns.go

### PR DESCRIPTION
**Pull request by abowloflrf**
**What type of PR is this?**

fix typo 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by cmluciano — COMMENTED** [review]
/ok-to-test

/lgtm

**Comment by dougsland** [comment]
/lgtm
looks pretty straightforward :)

**Pull request merged**
