### PR TITLE
kubeadm: Optimize the logic to override the arguments

### PR DESCRIPTION
**Pull request by chendave**
/kind cleanup

#### Which issue(s) this PR fixes:

related: https://github.com/kubernetes/kubeadm/issues/1601

#### Special notes for your reviewer:
Follow up the comment:
[comment1](https://github.com/kubernetes/kubernetes/pull/119156/files#r1264602015)
[comment2](https://github.com/kubernetes/kubernetes/pull/119156/files#r1264604456)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
/hold

for review

**Review by neolit123 — COMMENTED** [review]
/lgtm
was that the only refactor that is needed?

**Comment by chendave** [comment]
> was that the only refactor that is needed?

I think so.

**Comment by chendave** [comment]
this is a low risk change, if any of the feedback from other reviewers, pls feel free to open a new change.

/unhold

**Pull request merged**
