### PR TITLE
Gen webhook client

### PR DESCRIPTION
**Pull request by Q-Lee**
**What this PR does / why we need it**: generated client for the imagepolicy webhook.

See #22888 #30241 #30631

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31038)

### CODE REVIEW

**Comment by Q-Lee** [comment]
@ecordell @deads2k this is a PR for the generated clientset for the imagepolicy webhook.

**Comment by caesarxuchao** [comment]
I saw you used tag `nomethods` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/imagepolicy/v1alpha1/types.go#L26), and you didn't write any customized expansion methods either, so the client doesn't have any methods. Is this intended?

**Comment by deads2k** [comment]
> I saw you used tag nomethods here, and you didn't write any customized expansion methods either, so the client doesn't have any methods. Is this intended?

I think this is still outstanding.  You can take a look here to see how the generated expansions are used: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/internalclientset/typed/authentication/unversioned/tokenreview_expansion.go

**Comment by goltermann** [comment]
@Q-Lee is this needed for v1.4?  If so, needs a rebase and LGTM soon.

**Comment by deads2k** [comment]
> @Q-Lee is this needed for v1.4? If so, needs a rebase and LGTM soon.

Not needed for 1.4 and still has the issue that @caesarxuchao pointed out.

**Pull request closed without merging**
