### PR TITLE
scheduler: use logger instead of new klog.FromContext(ctx)

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- use logger instead of new klog.FromContext(ctx)
#### Which issue(s) this PR fixes:

Fixes # None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by googs1025** [comment]
@kerthcet If you have time, could you help take a look?

**Comment by ingvagabund** [comment]
Looks good. The replaced `klog.FromContext(ctx)` returns a logger from the same context. By that it needs to return the identical logger.

/lgtm

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
