### PR TITLE
Change the API tests to conformance tests

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
The first commit is going to be merged in https://github.com/kubernetes/kubernetes/pull/123857
After it's landed and stabilized, we need to change it to Conformance test in this PR/

/hold until https://github.com/kubernetes/kubernetes/pull/123857 merged.

History at https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel&width=5&include-filter-by-regex=ValidatingAdmissionPolicy

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @liggitt @jiahuif 
Thanks :)

**Comment by jiahuif** [comment]
/hold cancel
Should be clear after a rebase.

**Comment by cici37** [comment]
/hold 
Putting the hold again so the added tests could be stabilized a bit before moving to conformance tests. :)

**Comment by liggitt** [comment]
/lgtm
/approve

needs conformance approval

I added a link in the description to the run history (though it looks like testgrid prunes after a couple days)

**Comment by liggitt** [comment]
testgrid and https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel show 100% passing rate of the new tests since https://github.com/kubernetes/kubernetes/pull/123857 merged on 3/14

I'd +1 promoting these to conformance at this point

**Comment by liggitt** [comment]
/milestone v1.30
test-only change ahead of test-freeze to keep conformance coverage of GA APIs up

**Pull request merged**
