### PR TITLE
Add --version-json flag to kubelet to get complete information

### LINKED ISSUE #86779: Provide richer output for "kubelet --version"
**What would you like to be added**:
The `kubeadm version` and `kubelet version` output can be controlled by the `-o` argument. This is very nice for automation scripts, which need to read this information. It also contains rich information like buildDate, gitTreeState and others.

It would be nice, if we could get this information also from `kubelet --version`, with json or yaml output.

Question: I assume that is it `kubelet --version` and not `kubelet version` because kubelet is no cli. It this correct?

**Why is this needed**:
I'm implementing (yet another) automated provisioning of kubeadm clusters. To implement the update workflow, I need to get the version of kubeadm, kubectl and kubelet. And kubelet needs to be handled in a special way.

### PR DESCRIPTION
**Pull request by bharaththiruveedula-zz**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:
Add --version-json flag to kubelet to get complete information

**Which issue(s) this PR fixes**:
Fixes #86779

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Adds a new flag --version-json to kubelet binary.

For example:
kubelet --version-json
{
  "major": "1",
  "minor": "18+",
  "gitVersion": "v1.18.0-alpha.1.852+05b6c32886cf52-dirty",
  "gitCommit": "05b6c32886cf522550928de30287806d53e1b293",
  "gitTreeState": "dirty",
  "buildDate": "2020-01-17T12:33:36Z",
  "goVersion": "go1.13.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/assign @dchen1107
/ok-to-test

Thanks for your pr @bharaththiruveedula !

The high-level technical implementation looks sound (I'll do a full review should we decide to move forward from a feature standpoint).

However, in the past I know folks have been hesitant about adding more flags to `kubelet`. So before moving forward with this diff, I'd love us to get consensus that it's desired (either via #sig-node in Slack , at the sig-node meetings, or in the Github Issue/PR).

One helpful way to get consensus on this change could be outlining how adding this flag could help either developers or cluster admins.

Thanks again for your proposal/code :)

**Comment by mattjmcnaughton** [comment]
cc @gprossliner as I see you filed the original issue :)

**Comment by gprossliner** [comment]
Hi folks! Nice to see the progress on this issue. Looks good.

**Comment by marquiz** [comment]
I took a bit different approach in #88122

**Comment by gprossliner** [comment]
Hi Marquiz! The suggested --version=FORMAT has been discussed with the maintainers. There is a link to the google groups discussion in my original issue (#86779).

**Comment by gprossliner** [comment]
@feiskyer / @tallclair  is there any status update for the review? Please let me know, if there is something I may assist you with.

**Pull request closed without merging**
