### PR TITLE
test file should be remove after test over

### PR DESCRIPTION
**Pull request by guangxuli**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33273)

### CODE REVIEW

**Comment by guangxuli** [comment]
@caesarxuchao PTAL,I have merge the PR 33272 with this PR.Thanks.

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
LGTM. Thanks @guangxuli!

**Comment by caesarxuchao** [comment]
@guangxuli could you take care of the test failures? Thanks.

```
!!! 'gofmt -s -w' needs to be run on the following files: 
./pkg/client/restclient/request_test.go
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/33273/kubernetes-pull-verify-all/15490/build-log.txt

**Comment by guangxuli** [comment]
@caesarxuchao thanks so much, I will modify it.

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this, issue #33423

**Comment by caesarxuchao** [comment]
@k8s-bot gci e2e test this, issue #33423

**Pull request merged**
