### PR TITLE
Added 1x1 pixel for ga-beacon analytics

### PR DESCRIPTION
**Pull request by mansoorj**

### CODE REVIEW

**Comment by mansoorj** [comment]
Since the pre-check seems to have failed, I am indeed a googler (mansoorj@google.com) maybe it hasn't trickled through the system yet. Added changes based on guidance from bburns

**Comment by vmarmol** [comment]
Thanks @mansoorj! One comment is that you probably don't want to do this for the .md files in Godeps. Those are third_party ones we don't need to track.

**Comment by lavalamp** [comment]
Yes don't change the ones in third party files.

**Comment by brendandburns** [comment]
agree, let's not track mds in Godeps.  Sorry, I should have mentioned that!

--brendan

**Comment by mansoorj** [comment]
Ok, how should I proceed? Will you reject the entire PR for me to
re-submit, or are you able to specifically reject the godeps folder?

Thanks,
Mansoor

**Comment by vmarmol** [comment]
You can re-push to your fork and it'll reflect the change here.

**Comment by brendandburns** [comment]
Now that I'm back, Let me know if you want git-fu help getting this done.

--brendan

**Comment by dchen1107** [comment]
Close this one in favor of #6826?

**Comment by vmarmol** [comment]
Closing in favor of #6826

**Pull request closed without merging**
