### PR TITLE
Deprecate: use `NewRateLimitingQueueWithConfig` instead of `NewNamedRateLimitingQueue`

### PR DESCRIPTION
**Pull request by Fish-pro**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

`NewNamedRateLimitingQueue` has been deprecated，use `NewRateLimitingQueueWithConfig` instead of it

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pbetkier** [comment]
/test pull-kubernetes-e2e-autoscaling-hpa-cm

this presubmit is flaky (getting fixed)

**Comment by pbetkier** [comment]
/test pull-kubernetes-e2e-autoscaling-hpa-cpu

seems like environment flake

**Comment by Fish-pro** [comment]
> /test pull-kubernetes-e2e-autoscaling-hpa-cpu
> 
> seems like environment flake

@pbetkier 
Thank you for your attention. What do I need to do?

**Comment by pbetkier** [comment]
This is a wider issue that affects other PRs as well, both in k/k and k/test-infra. I'll discuss this with sig-testing and re-run your tests once it's resolved.

I'm in the process of reducing HPA e2e flakiness so that's why I'm interested in your presubmits failing :)

**Comment by pbetkier** [comment]
See https://github.com/kubernetes/test-infra/issues/29622.

**Comment by aojea** [comment]
I don't read this https://github.com/kubernetes/kubernetes/pull/114242 as this constructor is going to be removed

**Review by pbetkier — APPROVED** [review]
/lgtm

**Pull request closed without merging**
