### PR TITLE
remove unused functions in cmd

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
/kind cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by rosti — COMMENTED** [review]
Ok with the kubeadm change

**Comment by wgliang** [comment]
/cc @timothysc @derekwaynecarr @ dchen1107
PTAL,thanks.

**Review by detiber — APPROVED** [review]
kubeadm change lgtm

**Comment by wgliang** [comment]
/ping @dchen1107
for approve.

**Comment by wgliang** [comment]
/ping @dchen1107 @Random-Liu @timothysc
for approve.

**Comment by neolit123** [comment]
@kubernetes/sig-cli-pr-reviews

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by sttts** [comment]
@assign @luxas @Random-Liu

For approval.

**Review by luxas — APPROVED** [review]
/approve

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
This needs a kubelet approver too. 

/cc @kubernetes/sig-node-pr-reviews

**Pull request merged**
