### PR TITLE
Fix typo in ExecCommandParam

### PR DESCRIPTION
**Pull request by verb**
**What this PR does / why we need it**: Makes ExecCommandParam look like all of the other "Param"s

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
Seems not fixed in all places. You could search ExecCommandParamm across the project, and see where it is used.

**Comment by verb** [comment]
@feiskyer whoops, I didn't quite understand the role of the staging directory. I've updated the commit to include every "ExecCommandParamm" included by git grep in the kubernetes repo. Let me know if there are other repos to check. Can I get an ok-to-test?

**Comment by verb** [comment]
@k8s-bot ok to test

**Comment by verb** [comment]
Now that I think about it, I guess "ExecCommandParamm" was released as part of the versioned API. Does that mean we have to keep the typo around indefinitely?

If so I'll fix the typo internally and leave an extra "ExecCommandParamm" constant in types.go

**Comment by feiskyer** [comment]
/assign @lavalamp

cc/ @lavalamp @kubernetes/sig-api-machinery-api-reviews WDYT

**Comment by deads2k** [comment]
fixing a typo in the code (not the exposed value).  approving

**Pull request merged**
