### PR TITLE
bazel: delete deb that doesn't build

### PR DESCRIPTION
**Pull request by mikedanese**
cmd/kube-aggregator is long gone.

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm cancel

I think this should be `//vendor:k8s.io/kube-aggregator` now

**Comment by mikedanese** [comment]
> I think this should be //vendor:k8s.io/kube-aggregator now

We don't produce a docker image for this and we don't publish the deb so it's useless. Do we want to publish it?

**Comment by ixdy** [comment]
I guess we can delete the deb. We're building it in the release tar now, at least.

**Pull request merged**
