### PR TITLE
cidr_set.go :  fix several typo

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
wrong spelling 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Comment by danwinship** [comment]
/lgtm
/approve
/ok-to-test
but you still need to figure out the CLA situation...

**Comment by dims** [comment]
/approve
/lgtm

(just a typo fix in a local method name)

**Pull request merged**
