### PR TITLE
Update update-demo to work for v1, and don't use localhost domain name

### PR DESCRIPTION
**Pull request by ikehz**
Currently, this example doesn't work, because the host field has moved from `spec.host` to `status.hostIP`, (script.js:35).

In addition, I made the `kitten-rc.yaml` create 4 replicas in order to watch the rolling update better, and I removed the `localhost` domain name from the example, so that if someone wants to host the example on one machine and see it on another, they can.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Is the Shippable failure actually a problem?  I can't tell.  It looks like the build is failing at HEAD, but maybe in a different way?  I'm having a hard time finding the signal in the noise.

**Comment by jlowdermilk** [comment]
Shippable is currently flaky for 2 or 3 different reasons. The above failure looks like one of them.

**Comment by jlowdermilk** [comment]
LGTM

**Comment by jlowdermilk** [comment]
Assigning to Brendan for +lgtm, ok-to-merge.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by brendandburns** [comment]
LGTM, thanks for the fix!

**Comment by adyanthaya17** [comment]
My set up is like this: where I have two nodes-one behaving as both master and minion while the other node as a minion. I have my kubernetes environment up and running, able to fetch node state and they read 'Ready'. I'm following the guestbook from 'kubernetes/release-0.19.0/examples/update-demo'.

$ kubectl proxy --www=examples/update-demo/local/
Starting to serve on localhost:8001

but here it doesn't go to another line. If I need to execute another command I have to make use of ctrl+d and if I run the command again it tells the bind address is already in use. Thinking that it has worked I created two replicas:

$ kubectl create -f examples/update-demo/nautilus-rc.yaml
and resized it:
$ kubectl scale rc update-demo-nautilus --replicas=4
and if I check the 'kubectl get pods' I can see them as an when I resize the pods.

The document said the images that were the four pods could be viewed from the web and I'm not sure how it's done as I'm getting 'web page unavailable'.

Adding to this, I'm unable to see the service running when I run 'kubectl get services'.

**Comment by ihmccreery** [comment]
In step 1, where you turn up `kubectl proxy`, you either need to include the `&` at the end of the line to run the proxy in the background, or you need to run it in a separate terminal.  When you `Ctrl+d` out of it, you're terminating the proxy and can't see anything.

Hope that helps.  If you have more questions, I recommend opening a separate issue.

**Pull request merged**
