### PR TITLE
bind metadata proxy to 0.0.0.0

### PR DESCRIPTION
**Pull request by zshihang**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
fix test `pull-kubernetes-e2e-gci-gce-ipvs` failure in https://github.com/kubernetes/kubernetes/pull/92938

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by zshihang** [comment]
add `! -i eth0` to block non-pod and non-local traffic

**Comment by mikedanese** [comment]
> add `! -i eth0` to filter out non-pod and non-local traffic

I don't see how this could hurt, but I though that this was covered by putting the rule in the PREROUTING chain. Presumably this chain is only hit for forwarded packets.

**Pull request merged**
