### PR TITLE
Fix etcd storage_events_received_total metric not being registered

### PR DESCRIPTION
**Pull request by rlsvarinskis**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The etcd metric `storage_events_received_total` was introduced, but never registered

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by serathius** [comment]
Hmm, metrics was introduced in v1.27 and properly registered https://github.com/kubernetes/kubernetes/pull/116128

At some point we lost the registration.

**Comment by rlsvarinskis** [comment]
I see only `EventsReceivedCounter` being registered in #116128, but not `etcdEventsReceivedCounts`

**Comment by cici37** [comment]
Thanks to @benluddy's input: Consider to cherry pick the fix into earlier releases as well?
/sig etcd

**Pull request merged**
