### PR TITLE
update Mount propagation version in comment

### LINKED ISSUE #60657: Mount propagation moved to beta, comment not updated.
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Mount propagation feature was moved to beta in PR https://github.com/kubernetes/kubernetes/pull/59252

However the [API comment](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L1705) was not updated to reflect that it is now beta:

```go
	// mountPropagation determines how mounts are propagated from the host
	// to container and the other way around.
	// When not set, MountPropagationHostToContainer is used.
	// This field is alpha in 1.8 and can be reworked or removed in a future
	// release.
	// +optional
	MountPropagation *MountPropagationMode
```

**What you expected to happen**:

Comment reflects feature is beta.

**How to reproduce it (as minimally and precisely as possible)**:
-

**Anything else we need to know?**:
/assign @jsafrane 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
Mount propagation feature was moved to beta in PR [#59252](https://github.com/kubernetes/kubernetes/pull/59252)， so update the comment.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60657 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@thockin As @saad-ali said this need a milestone.

**Comment by jberkus** [comment]
@thockin can you add 1.10 and status/approved-for-milestone to this PR so it can merge?  Thanks!

**Comment by hanxiaoshuai** [comment]
@thockin can you add 1.10 and status/approved-for-milestone to this PR so it can merge? Thanks!

**Pull request merged**
