### PR TITLE
Followup 112643: remove residual code associated with DynamicKubeletConfig

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Followup #112643: remove residual code associated with DynamicKubeletConfig

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
thank you!

**Comment by SataQiu** [comment]
/assign @klueska 
Would you mind take a look?

**Comment by derekwaynecarr** [comment]
thank you for the cleanup.

/lgtm
/approve

**Pull request merged**
