### PR TITLE
Add docs to the OIDC authentication plugin.

### PR DESCRIPTION
**Pull request by bobbyrullo**
Document usage and configuration of OIDC on the client (kubectl) side.

[Analytics]()

### CODE REVIEW

**Comment by bobbyrullo** [comment]
@cjcullen @erictune @yifan-gu

**Comment by eparis** [comment]
Can someone create an OWNERS file somewhere on this path?

**Comment by eparis** [comment]
ok to test

**Comment by erictune** [comment]
This should go into https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/authentication.md

**Pull request closed without merging**
