### PR TITLE
[1.19][go1.15] Update to go1.15.5

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind feature
/area dependency security

**What this PR does / why we need it**:

Cherry pick of https://github.com/kubernetes/kubernetes/pull/95776.

- Update to go1.15.5
- build: Update to k/repo-infra@v0.1.3 (supports go1.15.5)

Tracking issue: https://github.com/kubernetes/release/issues/1651
Slack thread: https://kubernetes.slack.com/archives/GKEA5EL67/p1607713367023700?thread_ts=1607708476.012700&cid=GKEA5EL67, https://kubernetes.slack.com/archives/C2C40FMNF/p1605129514273400
cc: @kubernetes/release-engineering 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Kubernetes is now built using go1.15.5
- build: Update to k/repo-infra@v0.1.3 (supports go1.15.5)
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
1.15.6? :-)

**Comment by justaugustus** [comment]
> 1.15.6? :-)

Would have to handle on `master` first. 1.15.5 is a security release, so I want to get this one in first 🙃 

/retest

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
belated ... but still want to cast my vote :)

/lgtm
/approve

**Pull request merged**
