### PR TITLE
Allows node to set net conf in master etcd #6555

### PR DESCRIPTION
**Pull request by bussyjd**

### CODE REVIEW

**Comment by bussyjd** [comment]
I signed it!

**Comment by lavalamp** [comment]
@kelseyhightower -- look OK?

**Comment by bussyjd** [comment]
Updated from https://github.com/GoogleCloudPlatform/kubernetes/issues/6598 
Good to go IMO

**Comment by erictune** [comment]
@pires @justinsb either of you want to review this PR?

**Comment by AntonioMeireles** [comment]
humm... at sight this patch is a plain no-op, as the behaviour it achieves is the exact same one that we have already due to the fact that node's etcd is just a proxy to master's one (ecd2 new feature)... (patch would make sense if we hadn't etcd (in proxy mode) in the nodes but since we have i see no point on it - unless it solves some issue i'm not aware of atm.)

**Comment by pires** [comment]
What @AntonioMeireles said. I see no reason for this.

**Comment by erictune** [comment]
Closing.  Feel free to reopen or open new issue if there was a misunderstanding.

**Pull request closed without merging**
