### PR TITLE
replace deprecated ioutil functions

### PR DESCRIPTION
**Pull request by enjoys1994**
Signed-off-by: wangguoyan <717338097@qq.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
some ioutil function is deprecated 

#### Which issue(s) this PR fixes:

Fixes # NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve
for cmd/kubeadm

**Review by neolit123 — COMMENTED** [review]
do we also use other deprecated ioutil functions like WriteFile in kubeadm?

**Comment by wangguoyan** [comment]
> do we also use other deprecated ioutil functions like WriteFile in kubeadm?

in GO1.19 , some ioutil functions  were deprecated 
the  version  for go in kubeadm is  1.16 , and I don't see it using the Iotuil functions

**Comment by neolit123** [comment]
> in GO1.19 , some ioutil functions were deprecated
the version for go in kubeadm is 1.16 , and I don't see it using the Iotuil functions

so kubeadm only uses ioutil.ReadFile and no other deprecated ioutil functions?

**Comment by wangguoyan** [comment]
> 

no any io

**Comment by wangguoyan** [comment]
> > in GO1.19 , some ioutil functions were deprecated
> > the version for go in kubeadm is 1.16 , and I don't see it using the Iotuil functions
> 
> so kubeadm only uses ioutil.ReadFile and no other deprecated ioutil functions?

no any ioutil functions

**Comment by neolit123** [comment]
> no any ioutil functions , no ioutil.ReadFile and just os.ReadFile

ok, but i can only LGTM/approve for cmd/kubeadm here.
you could send a separate PR for pkg/volume.

**Comment by wangguoyan** [comment]
> > no any ioutil functions , no ioutil.ReadFile and just os.ReadFile
> 
> ok, but i can only LGTM/approve for cmd/kubeadm here. you could send a separate PR for pkg/volume and remove the changes from this PR.

Ok, I'll change that. I'm sorry, I misunderstood before. I thought you said Kubeadm is Kubernetes/Kubeadm

**Pull request merged**
