### PR TITLE
Replace tab with eight spaces

### PR DESCRIPTION
**Pull request by cjdrake**
This file only uses spaces for indentation, and my text editor highlighted the one tab.

### CODE REVIEW

**Comment by ihmccreery** [comment]
@david-mcmahon I'm marking this as build-release because we really ought to have some kind of lint check for this.  Or @kubernetes/sig-testing?  @cjdrake Want to file an issue against the repo to lint stuff like this?

LGTM.

**Comment by spxtr** [comment]
I don't think we lint shell scripts. ShellCheck finds many thousands of issues with our scripts, it wouldn't really be feasible to fix them all.

**Comment by cjdrake** [comment]
I find it hard to believe that a whitespace change would trigger a meaningful failure in the build system.

I see this in the log:
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-0-minion-e2e-gce-builder-2-0-http-alt' was not found
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-0-minion-e2e-gce-builder-2-0-nodeports' was not found
Bringing down cluster using provider: gce
...
error: couldn't read version from server: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: getsockopt: connection refused

--------------

I'm thinking maybe this is a flaky test?

**Comment by spxtr** [comment]
You are correct, it's a flake.

@k8s-bot e2e test this issue: #21367

**Pull request merged**
