### PR TITLE
Revert "Remove deprecated and experimental fields from KubeletConfiguration"

### LINKED ISSUE #51856: [SQ-blocking] Kubemark failing to start hollow-kubelet
Seems like kubelet changes breaking kubemark yet again. We've started seeing this at ~16:30 PST yesterday:
https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-kubemark-e2e-gce

cc @jdumars @k8s-oncall @kubernetes/sig-release-members

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#51307

To fix https://github.com/kubernetes/kubernetes/issues/51856

cc @mtaufen @dchen1107 @jdumars

### CODE REVIEW

**Comment by smarterclayton** [comment]
Should not have been removed without an API review sign off.

**Comment by jdumars** [comment]
@smarterclayton thanks for looking at this!

**Pull request merged**
