### PR TITLE
openstack: Support config-drive and improve CurrentNodeName, GetZone

### PR DESCRIPTION
**Pull request by anguslees**
This PR adds support for fetching local instance metadata via config-drive (as well as querying metadata service), and surfaces some additional metadata information (from either source):
- `CurrentNodeName` now returns the OpenStack instance name, rather than the current hostname (they might not be the same)
- `GetZone` includes availability zone label in `FailureDomain`

Thanks to @kiall for a WIP implementation of the latter.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31671)

### CODE REVIEW

**Comment by dims** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31671#-:-KQQP1l8rJNAz_XyWmRu:bnfp4nl)*

**Comment by kiall** [comment]
I've tested a back port of this to 1.3, worked nicely.

**Comment by kiall** [comment]
Any updating on merging? :)

**Comment by anguslees** [comment]
@mikedanese: I think you typed "lgtm" incorrectly above, please retransmit.

**Comment by anguslees** [comment]
ping @mikedanese

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-openstack

**Comment by dagnello** [comment]
thanks @mikedanese

**Pull request merged**
