### PR TITLE
e2e node: remove unused test/e2e_node/gcp

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The test package was not included anywhere and thus just dead code that doesn't need to be maintained anymore.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

wait for Sergey and David please

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
