### PR TITLE
Only provide an oldSelf binding when referenced by a CEL rule.

### PR DESCRIPTION
**Pull request by benluddy**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Some work is required to expose a CEL binding for `oldSelf` in CRD validation rules. If a given part of the CRD schema doesn't reference `oldSelf`, that work can be skipped as an optimization.

```
$ go test -bench WithoutOldSelf
goos: linux
goarch: amd64
pkg: k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel
cpu: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
BenchmarkCELValidationWithAndWithoutOldSelfReference/self.getMonth()_>=_0-20         	  305756	      3825 ns/op	    2154 B/op	      41 allocs/op
BenchmarkCELValidationWithAndWithoutOldSelfReference/oldSelf.getMonth()_>=_0-20      	  309991	      3849 ns/op	    2154 B/op	      41 allocs/op
PASS
```

```
$ go test -bench WithoutOldSelf
goos: linux
goarch: amd64
pkg: k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel
cpu: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
BenchmarkCELValidationWithAndWithoutOldSelfReference/self.getMonth()_>=_0-20         	  396276	      2949 ns/op	    1810 B/op	      36 allocs/op
BenchmarkCELValidationWithAndWithoutOldSelfReference/oldSelf.getMonth()_>=_0-20      	  311095	      3832 ns/op	    2154 B/op	      41 allocs/op
PASS
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
/lgtm
/assign @liggitt 
Would you mind to take a look when you have time? Thank you

**Comment by liggitt** [comment]
thanks for the optimization and benchmark

/approve

**Pull request merged**
