### PR TITLE
golint fixes for AWS cloudprovider

### PR DESCRIPTION
**Pull request by therc**
Among other things, golint doesn't like receivers that are inconsistently named or called "self". Or structs named aws.AWSservices, aws.AWSCloud, etc.

### CODE REVIEW

**Comment by therc** [comment]
cc @justinsb

**Comment by therc** [comment]
Ping? It's large, but mostly cosmetic fixes.

**Comment by justinsb** [comment]
Sorry for the delay.  I propose letting some of the other PRs merge, as this will likely break a lot of PRs, and they bring functional changes.  It's my fault for letting the backlog build up.

But then hopefully once they have merged there will be a relatively simple rebase needed only...

**Comment by therc** [comment]
Yeah, it makes sense. It might be also just easier to redo this from scratch.

**Comment by justinsb** [comment]
Marking this 1.4 - hopefully we can do this & other likely-to-cause-merge-conflict things early in 1.4.

**Comment by justinsb** [comment]
LGTM  - thanks for fixing all of these!

**Pull request merged**
