### PR TITLE
increase timeout in TestCancelAndReadd

### PR DESCRIPTION
**Pull request by liggitt**
the flakes referenced in #51704 were still seen downstream. the current timeout approach is [known to be faulty](https://github.com/kubernetes/kubernetes/issues/51704#issuecomment-328459239), but fixing the tests has not been prioritized. this increases the timeout sufficiently to avoid flakes in the meantime

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
/assign @smarterclayton 
for approval

**Comment by liggitt** [comment]
ping @gmarek for approval

**Pull request merged**
