### PR TITLE
windows: Fixes following container log rotation

### LINKED ISSUE #124443: Windows: Container log rotation may fail if the container logs are followed
### What happened?

The test ``k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs.TestReadRotatedLog`` is failing on Windows [0]:

```
{Failed  === RUN   TestReadRotatedLog
    logs_test.go:276: 
        	Error Trace:	C:/kubernetes/pkg/kubelet/kuberuntime/logs/logs_test.go:276
        	Error:      	Received unexpected error:
        	            	rename C:\Users\azureuser\AppData\Local\Temp\TestReadRotatedLog1957435032\001\logfile2771403626 C:\Users\azureuser\AppData\Local\Temp\TestReadRotatedLog1957435032\001\logfile2771403626.2220240422-035910: The process cannot access the file because it is being used by another process.
        	Test:       	TestReadRotatedLog
        	Messages:   	failed to rotate log "C:\\Users\\azureuser\\AppData\\Local\\Temp\\TestReadRotatedLog1957435032\\001\\logfile2771403626" to "C:\\Users\\azureuser\\AppData\\Local\\Temp\\TestReadRotatedLog1957435032\\001\\logfile2771403626.2220240422-035910"
--- FAIL: TestReadRotatedLog (0.21s)
```

The idea of the test is to check that kubelet still follows and reads the Container Logs after a Log Rotation occured. However, because the followed file is open, it cannot be renamed, and thus, the container logs cannot be rotated.

This issue could be prevented if the file would be opened with the ``FILE_SHARE_DELETE`` flag set [1]: ``Delete access allows both delete and rename operations.``

[0] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1782243642258231296
[1] https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

### What did you expect to happen?

Kubelet should not block container log rotation.

### How can we reproduce it (as minimally and precisely as possible)?

Run the test ``k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs.TestReadRotatedLog`` is failing on Windows.

### Anything else we need to know?

/sig windows

/kind bug
/kind failing-test

### Kubernetes version

latest, master. This unit test has been failing for a while.

### Cloud provider

N/A

### OS version

Windows nodes

</details>

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug
/kind failing-test

/sig windows
/sig testing

#### What this PR does / why we need it:

If we're following a file, that file will remain open, and we continue to read data from it when new data becomes available.

On Windows, this can be an issue if the container logs needs to be rotated. Log rotation is done by renaming the file, but this action may fail if the file is already opened.

Setting the ``FILE_SHARE_DELETE`` flag when opening the file will prevent this issue, as documented: ``"Delete access allows both delete and rename operations"`` [1].

In golang, there's no way to set this flag [2], the ``sharemode`` is always set to: ``sharemode := uint32(FILE_SHARE_READ | FILE_SHARE_WRITE)``

Thus, we need to open the file ourselves with the right flags.

[1] https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN
[2] https://cs.opensource.google/go/go/+/refs/tags/go1.22.2:src/syscall/syscall_windows.go;l=366

#### Which issue(s) this PR fixes:

Fixes #124443
Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
Fixed issue where following Windows container logs would prevent container log rotation.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
All Windows unit tests passed btw. So, this fixed the issue.

**Comment by bart0sh** [comment]
/assign @mrunalp @derekwaynecarr @dchen1107 
for approval

**Review by mrunalp — APPROVED** [review]

**Review by pacoxu — COMMENTED** [review]
/lgtm
last rebase removed only 
https://github.com/kubernetes/kubernetes/commit/96f62df82add5a81fc0154891c2f8710d3a33b87#diff-7d018d78ab77a2b6ef8407b4d5bf20c4bee7f70cc7436a3c39a07d381ccff612L218-L221

**Pull request merged**
