### PR TITLE
Update test/e2e/scheduling/nvidia-gpus to also run cuda10 vector add.

### PR DESCRIPTION
**Pull request by jiayingz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wgliang** [comment]
@jiayingz Do you have any other instructions or issues about this PR?

**Comment by jiayingz** [comment]
@wgliang I don't have an issue associated. Cuda10 has been out for a while and this PR is just to update the gpu test to make sure we test with the latest cuda version.

**Pull request merged**
