### PR TITLE
removed the deprecated azureFile in-tree storage plugin

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

removed the deprecated azureFile in-tree storage plugin

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
removed the deprecated `azureFile` in-tree storage plugin
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1885
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by jsafrane** [comment]
/approve
the storage changes

**Pull request merged**
