### PR TITLE
Document why we use 'tr -d' instead of 'base64 w0'

### PR DESCRIPTION
**Pull request by deyuanix**

### CODE REVIEW

**Comment by roberthbailey** [comment]
This doesn't work on Mac OS X (which I why I had to use the tr hack). The other option is to check the OS and use a different set of flags for Mac vs. Linux.

**Comment by ddysher** [comment]
Ah, didn't see that coming.  I think it's better to just keep it as is.

BTW, I'm working on a registry addon in k8s and need to supply the registry a certificate.  One thing I notice is that in vagrant, I can get the certificate by puting commands in make-ca-cert.sh, and that's what I expect based on salt setup.  However, it seems in gce, that script won't work?   We instead create certs in cilent, put into env vars and use gce startup scripts.  This makes it a little bit hard to reason about the startup process, can't we use the same process for cluster turn up?

**Comment by roberthbailey** [comment]
I originally made this mistake in the other direction (shortly after https://github.com/GoogleCloudPlatform/kubernetes/pull/8071 was merged I sent out https://github.com/GoogleCloudPlatform/kubernetes/pull/8288 to fix it). 

We moved GCE to generating the certs outside of the master because it allows us to distribute certs signed by the same CA onto the nodes as well as the master (giving us client certificates for auth). There isn't currently a mechanism to generate extra certificates after the cluster is up and running. 

How do you intend to use the cert for the registry (server cert or client cert)?

**Comment by ddysher** [comment]
Ok, just checked the vagrant cluster, no certificates under /srv/kubernetes/ in node, so right now only GCE node->master is secured?

For my use case, I'll create a new server cert using the same cluster CA, and distribute to master. Reigstry should be running as an addon, and the cert will be mounted as a secret in a registry Pod.  However, I do need a way to distribute CA certificate to node for docker daemon on node to trust it; but we currently use --insecure-registry so that might not be a problem.

As a minor improvement, I added some comments on the code.

**Comment by roberthbailey** [comment]
> right now only GCE node->master is secured?

I believe that statement is currently true, although @BenTheElder has  https://github.com/GoogleCloudPlatform/kubernetes/pull/9563 out for review that adds it to vagrant as well.

**Comment by roberthbailey** [comment]
We should spin this conversation out into an issue.

Adding some helpful docs here LGTM.

**Comment by BenTheElder** [comment]
Actually my PR just fixes the kubeconfig's being setup on the minions, I did have some code scp'ing the CA to the minions at one point but then i saw this in `cluster/vagrant/provision-master.sh` :
```` 
   # Make a kubeconfig file with the token.
  # TODO(etune): put apiserver certs into secret too, and reference from authfile,
  # so that "Insecure" is not needed.
````
I'm not yet familiar with secrets so I opted to leave the certs alone for now, and just get the kubeconfigs with the tokens synced.
@erictune I believe that's you, correct?

**Pull request merged**
