### PR TITLE
apiserver/util/proxy: Improving test coverage

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will increase the unit tests code coverage of `k8s.io/apiserver/pkg/util/proxy`

- Initial unit tests code coverage

Screenshot 2023-02-08 at 22 46 37

- After changes

Screenshot 2023-02-08 at 22 46 05

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @MikeSpreitzer 
Thank you!
/triage accepted

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Pull request merged**
