### PR TITLE
[1.21] bump runc to 1.0.2

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bumping runc dependency to 1.0.2, fixing a few issues.

For runc release notes, see
* 1.0.2: https://github.com/opencontainers/runc/releases/tag/v1.0.2
* 1.0.1: https://github.com/opencontainers/runc/releases/tag/v1.0.1
* 1.0.0: https://github.com/opencontainers/runc/releases/tag/v1.0.0

#### Which issue(s) this PR fixes:
Fixes: #102676
Fixes: #104280

#### Special notes for your reviewer:

This is a manual partial backport of #104528 to release-1.21 branch, replacing #103746.

#### Does this PR introduce a user-facing change?

```release-note
Fixes a regression in 1.21.2.
Fixed occasional pod cgroup freeze when using cgroup v1 and systemd driver.
Fixed "failed to create container ... unit already exists" when using cgroup v1 and systemd driver.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

**Comment by kolyshkin** [comment]
> were the changes to pkg that accompanied the runc 1.0.1 bump (#103743) required?

@liggitt Do you mean https://github.com/kubernetes/kubernetes/pull/103743/commits/e5b434e990de5f05c41411f07236cb7b2d663a00?

This is more of a cleanup (cosmetic change), not really required (if `SkipDevices` is set, it's ignored).

I decided to not backport it in order to limit the amount of changes (should have mentioned that in PR description). If you want I can add it.

**Comment by liggitt** [comment]
yeah, that's the commit I was referring to. if it's not required, that's fine... I couldn't tell

/approve

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
