### PR TITLE
Remove DockerManager from kubelet

### PR DESCRIPTION
**Pull request by yujuhong**
This commit deletes code in dockertools that is only used by
DockerManager. A follow-up change will rename and clean up the rest of
the files in this package.

The commit also sets EnableCRI to true if the container runtime is not
rkt. A follow-up change will remove the flag/field and all references to
it.

### CODE REVIEW

**Comment by yujuhong** [comment]
I leave this PR "release-note-none", and will add a release note in the PR that removes the flag.

@dchen1107 I marked this do-not-merge until I get the official ok.
/cc @kubernetes/sig-node-pr-reviews @kubernetes/sig-node-proposals (since more people are in this group) @thockin 
@bowei, FYI, once this PR gets merged, there will be no knob to disable CRI anymore for people using various CNI plugins.

**Comment by feiskyer** [comment]
Cool. 

There are still non-CRI tests running (and passed), so they are actually running with dockershim?

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by yujuhong** [comment]
> Cool.
> 
> There are still non-CRI tests running (and passed), so they are actually running with dockershim?

Yes with this PR, but I have a separate PR to remove those tests: https://github.com/kubernetes/test-infra/pull/2363

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by yujuhong** [comment]
@dchen1107 this is ready for review.

**Comment by feiskyer** [comment]
LGTM

**Comment by feiskyer** [comment]
I think https://github.com/kubernetes/test-infra/pull/2363 should be merged first before this PR.

**Comment by dchen1107** [comment]
@yujuhong I think this requires a release-note for 1.7.

**Comment by yujuhong** [comment]
> A follow-up change will remove the flag/field and all references to
> it.

@dchen1107 I plan to add a release note in the follow-up PR, where I will remove the --disable-cri flag as well.

**Comment by dchen1107** [comment]
RE: https://github.com/kubernetes/kubernetes/pull/43884#issuecomment-298408981 

lgtm

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this

**Pull request merged**
