### PR TITLE
Kustomize images docs reference wrong field

### PR DESCRIPTION
**Pull request by tagoro9**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

This PR fixes the kustomize `images` documentation. The `newName` parameter is defined as `nameName`.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tagoro9** [comment]
I signed it

**Review by eddiezane — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm
/priority important-longterm
/retest

**Comment by eddiezane** [comment]
Thanks for this PR and apologies for the delay!

We'll be merging https://github.com/kubernetes/kubernetes/pull/89086 instead as it fixes another typo.

/close

**Pull request closed without merging**
