### PR TITLE
Revert "Merge pull request #49988 from sbezverk/fsgroup_check"

### LINKED ISSUE #51358: cross-build: PR 49988 causing cross build failure
```
I0825 19:05:24.671] +++ [0825 19:04:12] windows/amd64: go build started
I0825 19:05:24.672] # k8s.io/kubernetes/pkg/volume/local
I0825 19:05:24.672] pkg/volume/local/local.go:306: undefined: syscall.Stat_t
```
https://github.com/kubernetes/kubernetes/pull/49988
https://k8s-testgrid.appspot.com/misc#cross-build
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/3054

cc: @kubernetes/sig-storage-bugs @kubernetes/sig-storage-test-failures @sbezverk @msau42 @rootfs @smarterclayton

### PR DESCRIPTION
**Pull request by msau42**
This reverts commit dfd1ca7728a6ff29e7dec9e95bd9880b14211605, reversing
changes made to c04e5163732f8168356b6d9e44ef7374aa4f1260.

**What this PR does / why we need it**:
PR #49988 breaks cross build.  Revert to unblock, and work on the real fix separately.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51358

**Special notes for your reviewer**:

**Release note**:

NONE

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm cancel
I believe @sbezverk is pushing a PR with fix. Holding on merge.

**Comment by msau42** [comment]
Closing since #51366 got merged

**Pull request closed without merging**
