### PR TITLE
Fix data race in APF tests

### LINKED ISSUE #110139: data race in priority and fairness unit test
### What happened?

`TestApfWatchHandlePanic/post-execute_panic` has a data race

```
{Failed  === RUN   TestApfWatchHandlePanic/post-execute_panic
==================
WARNING: DATA RACE
Read at 0x000003a22108 by goroutine 426:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.newApfHandlerWithFilter.func2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:179 +0x584
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x547
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestApfWatchHandlePanic.func3.1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:598 +0xd0
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2916 +0x896
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1966 +0xbaa
  net/http.(*Server).Serve.func3()
      /usr/local/go/src/net/http/server.go:3071 +0x58

Previous write at 0x000003a22108 by goroutine 166:
  sync/atomic.AddInt32()
      /usr/local/go/src/runtime/race_amd64.s:279 +0xb
  sync/atomic.AddInt32()
      <autogenerated>:1 +0x1a
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.7.2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:204 +0x3e
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:436 +0x32
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*fakeWatchApfFilter).Handle()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:415 +0xa6
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.8()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:260 +0x1a4

Goroutine 426 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3071 +0x80c
  net/http/httptest.(*Server).goServe.func1()
      /usr/local/go/src/net/http/httptest/server.go:308 +0xb2

Goroutine 166 (finished) created at:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:228 +0xea5
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.newApfHandlerWithFilter.func2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:177 +0x56c
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x547
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestApfWatchPanic.func3()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:553 +0xd0
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2084 +0x4d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2916 +0x896
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1966 +0xbaa
  net/http.(*Server).Serve.func3()
      /usr/local/go/src/net/http/server.go:3071 +0x58
==================
    priority-and-fairness_test.go:180: Wanted 0 requests executing, got 1
    priority-and-fairness_test.go:595: expected panic, got <nil>
    testing.go:1312: race detected during execution of test
    --- FAIL: TestApfWatchHandlePanic/post-execute_panic (5.05s)
}
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110132/pull-kubernetes-unit/1527377549582143488

### What did you expect to happen?

test should not have data race

### How can we reproduce it (as minimally and precisely as possible)?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110132/pull-kubernetes-unit/1527377549582143488

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind cleanup
/kind flake

#### What this PR does / why we need it:

This PR does:
- it fixes the data race
- It fixes bookkeeping of the in-flight  requests of the fake APF watch handler
- It adds logs for further debugging

#### Which issue(s) this PR fixes:
Fixes #110139

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Comment by liggitt** [comment]
saw a new failure in this test this morning - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126728/pull-kubernetes-unit/1829476917204488192

was this run with stress / race to make sure the updates are not flaky?

**Comment by tkashem** [comment]
my bad, i ran stress on `TestApfWatchHandlePanic` only
```
stress -p=256 ./filters.test -test.run=TestApfWatchHandlePanic
5s: 0 runs so far, 0 failures
10s: 256 runs so far, 0 failures
15s: 285 runs so far, 0 failures
20s: 512 runs so far, 0 failures
...
13m40s: 32615 runs so far, 0 failures
13m45s: 32816 runs so far, 0 failures
13m50s: 33049 runs so far, 0 failures
13m55s: 33229 runs so far, 0 failures
```

It seems this PR has manifested a bug with apf watch handling, I have a https://github.com/kubernetes/kubernetes/pull/127029 in the works, I will share the stress test result that shows the fix

**Pull request merged**
