### PR TITLE
Add/remove kargakis from a couple of places

### PR DESCRIPTION
**Pull request by 0xmichalis**
I've replaced myself in some tests in test_owners with the actual owners of those tests and I've also picked up a bunch of deployment tests. Also due to lack of review bandwidth I am removing myself from sig_cli reviewers.

@janetkuo

### CODE REVIEW

**Comment by kargakis** [comment]
@wojtek-t can you please approve

**Comment by enisoc** [comment]
I'm cleaning out the milestone since we're coming up on the cut. This doesn't seem to be a release-blocker.

**Comment by kargakis** [comment]
@wojtek-t ping

**Comment by wojtek-t** [comment]
/approve

Sorry for delay.

**Pull request merged**
