### PR TITLE
Fix the allow-all example NetworkPolicy

### LINKED ISSUE #28795: broken example in NetworkPolicy proposal
Example 3 in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/network-policy.md#examples is broken: it has an empty list of ingress rules, and consequently means nothing.

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
[Analytics]()

This is a bug fix, no release note required.

Fixes #28795

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
CC @caseydavenport

**Comment by caseydavenport** [comment]
LGTM.

**Comment by MikeSpreitzer** [comment]
What are we waiting for here?

**Comment by smarterclayton** [comment]
ok to test

**Pull request merged**
