### PR TITLE
stop defaulting kubeconfig to http://localhost:8080

### PR DESCRIPTION
**Pull request by soltysh**
This is reviewing https://github.com/kubernetes/kubernetes/pull/62469

This default reflects a discouraged path (http, not https), that hasn't correspond to the default clusters being stood up for years (we changed default to https).

Potential places this might have an impact are insecure servers exposed and used/managed via a local script.  Making this change now provides immediate feedback about a potentially risky situation from a location that will not see a warning added for humans.

If you own one of these legacy clusters, you are *strongly* encouraged to secure your server.  If you cannot secure your server, you can set  `KUBERNETES_MASTER`.

@kubernetes/sig-api-machinery-pr-reviews 
/assign @liggitt @deads2k 

```release-note
action required: `kubectl` no longer defaults to `http://localhost:8080`.  If you own one of these legacy clusters, you are *strongly* encouraged to secure your server.   If you cannot secure your server, you can set `KUBERNETES_MASTER` if you were relying on that behavior and you're client-go user. Set `--server`, `--kubeconfig` or `KUBECONFIG` to make it work in `kubectl`. 
```

### CODE REVIEW

**Comment by liggitt** [comment]
This would seem to fall under https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior

I would expect advance notice and warnings if the default fallback was used during the described deprecation period.

**Comment by deads2k** [comment]
@soltysh need to get test-cmd happy.

**Comment by deads2k** [comment]
This seems reasonable to me. We've been trying to eliminate the usage of insecure kube-apiservers since forever. This default only worked locally for insecure environments and has an easy workaround for people who are impacted and don't want to secure their localhost server (you really should test closer to what you'll use in production).

**Comment by soltysh** [comment]
Yeah, I'm aware, I'm planning to finish it this week.

**Comment by soltysh** [comment]
> This would seem to fall under https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior
> 
> I would expect advance notice and warnings if the default fallback was used during the described deprecation period.

This was deprecated back in https://github.com/kubernetes/kubernetes/commit/a397e30 which dates back to 1.5 so it's been lingering deprecated for more than required in the policy.

**Comment by deads2k** [comment]
> This would seem to fall under https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior
> 
> I would expect advance notice and warnings if the default fallback was used during the described deprecation period.

Internal defaulting for discouraged path (http, not https), that hasn't correspond to the default clusters being stood up for years (we changed default to https), that was deprecate in code for years before that seems like a possible candidate.

To me, this looks a lot like the removal of RBAC policy for unauthenticated users. It reflects the standards of the past years, explicitly breaking past usage, but provides an easy work around (pass the flag).

**Pull request merged**
