### PR TITLE
Add test coverage for throttledImageService

### LINKED ISSUE #91655: Add unit test coverage using throttledImageService
**What would you like to see added?**

Currently, executing the unit tests in `pkg/kubelet/images/...` does not
actually execute the `throttledImageService` as defined in
`pkg/kubelet/images/helpers.go`. For all unit tests, `qps` is set to 0, so we
essentially use a non-throttled image service. Examining the code coverage shows
that all code components "unique" to the throttled image service (i.e. the
actual throttling) are not actually tested.

**Why this is needed?**

We'd like unit test coverage for the business logic that makes the throttling
actually throttle. Furthermore, by default, the image service does use
throttling, so adding this test coverage will help us mirror what happens in
production.

**Extra note**

I think this ticket could be a great candidate for someone who is new to
contributing to sig-node/k8s. **I'd prefer to please give first dibs for picking
this up to any folks who are currently underrepresented in the k8s community**.
Please reach out to @mattjmcnaughton on k8s Slack (or post directly in #sig-node and tag me) if you're interested, and I'll assign you the issue. I'm happy to mentor and be helpful in whatever way I can :)

### PR DESCRIPTION
**Pull request by stevechuck**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

- Increases unit test coverage for `throttledImageService` related functions in
`pkg/kubelet/images/helpers.go` from 33.3% to 100.0%
- Refactored tests in `pkg/kubelet/images/image_manager_test.go` to use subtests

**Which issue(s) this PR fixes**:

Fixes #91655

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iamchuckss** [comment]
/assign @mattjmcnaughton 

@farah I can't seem to add you as a reviewer, could you try assigning yourself?

**Comment by farah** [comment]
@iamchuckss I think you need permission to assign to me, but that's fine. 

Looks pretty solid to me, had something similar in mind. But I like the introduction of the `testName` field rather than relying on the image name for the test cases, definitely a nice improvement imo :).

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Awesome, thanks @farah and @iamchuckss !

**Comment by mattjmcnaughton** [comment]
@dashpole mind remaking w/ lgtm after the changes? thanks :)

**Comment by iamchuckss** [comment]
@dashpole Is there anything else you need for an approve?

**Comment by iamchuckss** [comment]
@dashpole Thank you! :)

**Pull request merged**
