### PR TITLE
[release-1.27] releng/go: Update images, deps and ver to Go 1.20.5

### PR DESCRIPTION
**Pull request by puerco**
Bump go version in release-1.27

#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Update images, dependencies and version to Go 1.20.5

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3099

#### Special notes for your reviewer:

/assign @saschagrunert @cpanato @Verolop  @jeremyrickard @xmudrii 
cc @kubernetes/release-engineering  

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Go 1.20.5
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/triage accepted
/priority important-soon

/lgtm

**Review by thockin — COMMENTED** [review]
Is checking in go.sum still useful ?

/lgtm
/approve

**Pull request merged**
