### PR TITLE
update default translation of annotations

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
```
using the local cluster. the help of kubectl is not corrent
# ./cluster/kubectl.sh
.......
Settings Commands:
  label          Update the labels on a resource
  annotate       Update the annotations on a resourcewatch is only supported on individual resources and resource
collections - %d resources were found
  completion     Output shell completion code for the specified shell (bash or zsh)

Other Commands:
  api-versions   Print the supported API versions on the server, in the form of "group/version"
  config         Modify kubeconfig files
  help           Help about any command
  plugin         Runs a command-line plugin
  version        Print the client and server version information

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).

```
**Which issue this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
ok to test

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
