### PR TITLE
Automated cherry pick of #56557

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #56557 on release-1.8.

#56557: create storage account if necessary when create azure file

### CODE REVIEW

**Comment by jpbetz** [comment]
@andyzhangx please add release note explaining change.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60409)

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Comment by andyzhangx** [comment]
@jpbetz is it ok to get into next v1.8 release?

**Comment by khenidak** [comment]
Does this create a new storage account for each file?

**Comment by jpbetz** [comment]
@andyzhangx This looks ready. I've added some missing labels. It should merge before 1.8.11 later this week.

**Comment by andyzhangx** [comment]
@khenidak Answer is no, this PR only creates a storage account if there is no account in k8s cluster, so for the second azure file, it will use the existing account.
@jpbetz Thanks.

**Pull request merged**
