### PR TITLE
Delete vagrant.md

### PR DESCRIPTION
**Pull request by sc68cal**
http://kubernetes.github.io/docs/getting-started-guides/vagrant/ 404's

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33200)

### CODE REVIEW

**Comment by sc68cal** [comment]
Ok I need to rebase outside of GitHub

**Comment by sc68cal** [comment]
Somehow the GitHub online editor really mucked up what I was trying to accomplish. I must have gotten redirected to the `release-1.4` branch where the file exists.

Anyway, back to the CLI, now fixed.

**Comment by brendandburns** [comment]
Can you fix the cla?  Thanks.

**Comment by sc68cal** [comment]
I've signed the CLA. The only thing I can think of is that for some reason the bot is confused since I used the GitHub editor. I can pull down the commit, `amend` and `--reset-author` and force push it - that's the only thing I can think of as to why the CLA isn't being detected properly.....

**Comment by idvoretskyi** [comment]
LGTM

**Comment by brendandburns** [comment]
Summoning @david-mcmahon or @pwittrock to see if they can force this PR in against the do-not-merge wishes of the doc-bot...

(I'll file an issue on doc-bot to allow delete only changes....)

**Comment by eparis** [comment]
I can force it in. Wondering why the retest keeps getting triggered...

**Comment by eparis** [comment]
```
+++ [0927 09:37:03] Building go targets for linux/amd64:
    cmd/mungedocs
/go/src/k8s.io/kubernetes/docs/devel/running-locally.md
----
md-links:
not printing failed chunk: too many lines
On line 59: "../getting-started-guides/vagrant.md": target not found

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/docs/ is out of date. Please run hack/update-munge-docs.sh
[0;31mFAILED[0m   hack/make-rules/../../hack/verify-munge-docs.sh	7s
```

**Comment by eparis** [comment]
I'll try to remember to come back and merge by hand after the tests pass. Ping me tomorrow if I forget.

**Comment by pwittrock** [comment]
This is great.  Thanks.

**Pull request merged**
