### PR TITLE
Automated cherry pick of #66138: Don't validate HealthzBindAddress in KubeProxyConfiguration

### PR DESCRIPTION
**Pull request by wsong**
Cherry pick of #66138 on release-1.10.

#66138: Don't validate HealthzBindAddress in KubeProxyConfiguration

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/hold
Freezing branch 1.10.7

**Comment by thockin** [comment]
We're getting close to 1.1.2 - why does this need a backport?

**Comment by wsong** [comment]
I just backported this to every branch that had the original issue.

**Comment by thockin** [comment]
I'm in the camp of not backporting unless we have a need for it.

@MaciekPytel do you think this is worth backporting?  I'll approve if you do.

**Comment by nikhita** [comment]
Closing and reopening to retrigger prow to remove the `do-not-merge/cherry-pick-not-approved` label.

/assign

**Comment by nikhita** [comment]
/unassign
/retest

The labels are fixed now. :+1:

**Comment by MaciekPytel** [comment]
@thockin We did cherry-pick it to 1.9 and 1.11, so it is somewhat inconsistent to skip it. That being said it doesn't seem critical at a glance and if you think it's not I'm inclined to agree. It's been open for a while without much pinging, so there doesn't seem to be much interest.

@wsong Can we close this or do you think this is critical after all?

**Comment by wsong** [comment]
It's certainly not critical. I agree that since it got merged into 1.9, however, it should get merged into 1.10

**Pull request merged**
