### PR TITLE
upgrade api-version to fix azure file AuthorizationFailure

### LINKED ISSUE #85354: Azure Files PV AuthorizationFailure when using advanced networking
**What would you like to be added**:
currently this create file share action is also considered as data-path operation that's the reason why it failed since create file share action happens on master node which is not in selected network, in the future, this action will not be handled as data-path operation. 

as confirmed by azure file team, api-version `2019-06-01` supports this functionality, need to upgrade the api-version:

https://github.com/kubernetes/kubernetes/blob/4c50ee993c82c6852eb3b3aa8dfa8ecc4bcfe330/staging/src/k8s.io/legacy-cloud-providers/azure/azure_storage.go#L24

**Why is this needed**:

/assign
/kind bug
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
upgrade api-version to fix azure file AuthorizationFailure

**Which issue(s) this PR fixes**:

Fixes #85354

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix azure file AuthorizationFailure
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

related issue: https://github.com/Azure/AKS/issues/804

/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
cc @chewong `pull-kubernetes-e2e-aks-engine-azure` failed with
```
error building hyperkube error during make -C /go/src/k8s.io/kubernetes/cluster/images/hyperkube push: exit status 2
```

**Comment by chewong** [comment]
> cc @chewong `pull-kubernetes-e2e-aks-engine-azure` failed with
> 
> ```
> error building hyperkube error during make -C /go/src/k8s.io/kubernetes/cluster/images/hyperkube push: exit status 2
> ```

This should be fixed by https://github.com/kubernetes/test-infra/pull/15340.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
/approve
for vendor/

**Comment by BenTheElder** [comment]
how did this not update go.mod / go.sum ?

**Comment by andyzhangx** [comment]
> how did this not update go.mod / go.sum ?

thanks @BenTheElder, about your concern, this PR only updates the api-version, did not change the azure-sdk-for-go version:
https://github.com/kubernetes/kubernetes/blob/57b6b287d4ffa4b14ab93200fe2e67eb9dea7a58/go.mod#L11

**Pull request merged**
