### PR TITLE
Parallelize architectures in both the building and packaging phases of `make release`

### PR DESCRIPTION
**Pull request by zmerlynn**
On my desktop, this took the KUBE_RELEASE_RUN_TESTS=n "make release" down from 172s to 115s.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @quinton-hoole @ixdy 

cc @filbranden for bash fun

**Comment by vmarmol** [comment]
Assigning to @ixdy, feel free to re-assign.

**Comment by zmerlynn** [comment]
@ixdy:

**Comment by quinton-hoole** [comment]
Could you perhaps generate a more succint diff for review?  It seems like most of this is formatting changes - it's difficult to work our what has actually changed.

**Comment by ixdy** [comment]
LGTM. Not sure if @filbranden has any shell commentary.

**Comment by zmerlynn** [comment]
@quinton-hoole: Not really, no. There was a tabbing change because of the sub-shell addition, which causes a large drift.

**Comment by quinton-hoole** [comment]
Apologies for the delay.  There are now merge conflicts. Please rebase and I'll merge.

**Comment by zmerlynn** [comment]
@quinton-hoole: PTAL. The rebase basically forced me to redo golang.sh, so I gave you two commits that are slightly more reviewable for that file (one commit that has the changes, the next that re-tab-ifies the middle block.)

**Comment by derekwaynecarr** [comment]
Awesome!

**Comment by zmerlynn** [comment]
I'm actually rolling this back due to #6346. I played with it for a while, and a have a working version that breaks based on the memory, but I'm now not sure the timing matters much.

**Pull request merged**
