### PR TITLE
Automated cherry pick of #68530: Rewrite finalURLTemplate used only for metrics of dynamic client

### PR DESCRIPTION
**Pull request by wenjiaswe**
Cherry pick of #68530 on release-1.11.

#68530: Rewrite finalURLTemplate used only for metrics because of dynamic client change

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Any chance to get this reviewed?

**Comment by roycaihw** [comment]
/lgtm
/assign @liggitt 
for approval

**Comment by wenjiaswe** [comment]
@calebamiles Would you please help to approve this cherry pick? Thanks!

**Comment by nikhita** [comment]
/assign @foxish
for cherry-pick approval

**Pull request merged**
