### PR TITLE
Stop the bleeding for #6059

### PR DESCRIPTION
**Pull request by lavalamp**
Degrade to a 30 second poll instead of a five minute poll.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM.  Will merge as soon as Travis gets back to us.

**Comment by zmerlynn** [comment]
Thank you for something.

**Comment by zmerlynn** [comment]
... Sorry, that was more tepid than it was supposed to sound. :) YAY. I've been waiting for the blood to slow.

**Comment by quinton-hoole** [comment]
On second thoughts, Travis is not going to tell us anything interesting.  Lets rather merge now and get it out to Jenkins e2e tests to confirm that it stops the bleeding detailed in  #6059 .

**Comment by lavalamp** [comment]
@zmerlynn LOL, thank me only if it works... :)

is 5m -> 30s (10x) speedup even going to be enough?

**Comment by quinton-hoole** [comment]
Yes, I think so.  We'll have to see.  Jenkins should tell us over the next few hours.

**Comment by quinton-hoole** [comment]
Aaaannd... we had our first green Jenkins e2e run in two days :-)  Lets see how it holds up.

**Pull request merged**
