### PR TITLE
[kubectl] componentStatusTableObjBody: fix range iterator issue

### PR DESCRIPTION
**Pull request by gaurav1086**
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Go uses the same address variable while iterating in a range, so use a copy when using its address.
https://play.golang.org/p/wh5_P3NpZXl
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
https://play.golang.org/p/wh5_P3NpZXl
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
cc @liggitt

**Comment by gaurav1086** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
It doesn't actually look like it's used in a problematic way?

**Comment by gaurav1086** [comment]
@lavalamp ah yes, this looks good. Thanks for pointing out.

**Pull request closed without merging**
