### PR TITLE
cleanup after LegacyServiceAccountTokenCleanUp is GA

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

A follow-up of https://github.com/kubernetes/kubernetes/pull/122635

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `LegacyServiceAccountTokenCleanUp`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks, @carlory for this PR.
Tt looks good to me.

/lgtm

**Comment by liggitt** [comment]
please open a corresponding doc update PR against https://github.com/kubernetes/website/tree/dev-1.32 to doc the gate removal

**Comment by carlory** [comment]
@liggitt please review https://github.com/kubernetes/website/pull/47606

**Pull request merged**
