### PR TITLE
Cassandra examples updating images to v9

### PR DESCRIPTION
**Pull request by chrislovecnm**
- this is a version bump for the C\* image
- I also increased the cpu to .5 because .1 is slow like warm death

Who can actually run the build to get the container to the examples repo?

### CODE REVIEW

**Comment by chrislovecnm** [comment]
cc @kubernetes/examples @bgrant0607 

[WIP] because I got some feedback from @pmdcosta

**Comment by jayunit100** [comment]
lgtm thanks!

**Comment by bgrant0607** [comment]
@pwittrock

**Comment by chrislovecnm** [comment]
Would be great if someone could test locally at least one of the examples 😄

**Comment by chrislovecnm** [comment]
@jeffmendoza et al.  Why did these tests fail?  I ran the hack stuff :(

**Comment by chrislovecnm** [comment]
You guys running java unit tests now ... 

> ERROR: Step â€˜Publish JUnit test result reportâ€™ failed: No test report files were found. Configuration error?

That is cool .. but the test pass .. and I have report files as well 😄 

```console
# clove @ clove-mbp in ~/Workspace/src/github.com/kubernetes/kubernetes/examples/cassandra/java/target/surefire-reports on git:cassandra-image-bump o [16:26:08]
$ la -al
total 24
drwxr-xr-x   4 clove  wheel   136B May 15 16:25 .
drwxr-xr-x  10 clove  wheel   340B May 15 16:25 ..
-rw-r--r--   1 clove  wheel   5.6K May 15 16:25 TEST-io.k8s.cassandra.KubernetesSeedProviderTest.xml
-rw-r--r--   1 clove  wheel   288B May 15 16:25 io.k8s.cassandra.KubernetesSeedProviderTest.txt
```

**Comment by jayunit100** [comment]
Looks like a flake maybe ? Check build log it said something about "master not detected"

**Comment by chrislovecnm** [comment]
New to this... How do we run the tests again?

**Comment by jayunit100** [comment]
Look up the flake. If it is a flake record the issue number , then do @ k8s-bot test this please issue: #xyz

**Comment by chrislovecnm** [comment]
@jayunit100 what the heck does this mean:

Found illegal 'flag' usage. If these are false positives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
examples/cassandra/image/run.sh:	cluster_name \
FAILED   ./hack/../hack/verify-flags-underscore.py	28s

Is my bash syntax incorrect?

**Comment by chrislovecnm** [comment]
@bgrant0607 some help good sir ... This was in the jetty logs:

Found illegal 'flag' usage. If these are false positives you should run hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt to update the list.
examples/cassandra/image/run.sh: cluster_name \
FAILED ./hack/../hack/verify-flags-underscore.py 28s

**Comment by bgrant0607** [comment]
@chrislovecnm It looks like one of our verification scripts is not smart enough. That one line (.../run.sh cluster_name) is the diff?

**Comment by chrislovecnm** [comment]
@bgrant0607 correct.  I have never used that script before. Let me know if that txt that I commited it ok.

**Comment by chrislovecnm** [comment]
@jayunit100 we read for a merge?

**Comment by chrislovecnm** [comment]
Read == ready

**Comment by jayunit100** [comment]
Have you validated this in the e2es using gingko.focus=Cassandra? If so I think we can merge it .

The ginkgo e2e doesn't run in examples in the PR regression tests.

**Comment by chrislovecnm** [comment]
You have to provide more information. No idea what e2es is.

**Comment by chrislovecnm** [comment]
I think I figured out vagrant, but I think these tests will fail for multiple reasons.

There has been an issue open that are failing.  https://github.com/kubernetes/kubernetes/issues/20999

@jayunit100 also with the version bump in the yaml ... I am thinking that I need the container pushed to the docker repo to run this test anyways.

In kubernetes/test/e2e/examples.go, if I am tracing through what is going on. 

```golang
framework.RunKubectlOrDie("create", "-f", controllerYaml, nsFlag)
```
Will create the rc, and attempt to pull down gcr.io/google-samples/cassandra:v9.  That image does not exist yet.

**Comment by chrislovecnm** [comment]
@jayunit100 so I was able to get the vagrant tests to run, but as I expected they failed.  I do not know if they failed because of the issues in https://github.com/kubernetes/kubernetes/issues/20999 or because the image does not exist.  I would like to get this PR in ... how do we proceed?

cc: @bgrant0607

**Comment by chrislovecnm** [comment]
For the sake of brevity here are the test results: 

```console
• Failure [65.916 seconds]
[k8s.io] [Feature:Example]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  [k8s.io] Cassandra
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
    should create and scale cassandra [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:257

    Expected error:
        <*errors.errorString | 0xc8203b9dd0>: {
            s: "Failed to get entpoints for e2e-tests-examples-wzf26/cassandra",
        }
        Failed to get entpoints for e2e-tests-examples-wzf26/cassandra
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:237
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [k8s.io] [Feature:Example] [k8s.io] Cassandra [It] should create and scale cassandra
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:237

Ran 1 of 293 Specs in 90.017 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 292 Skipped --- FAIL: TestE2E (90.03s)
FAIL
```

As I mentioned we have known issues with that test, and with the 1.3 product launch coming up, I don't have time currently to address those :(

**Comment by jayunit100** [comment]
thanks for testing!

but :( uhoh.... gcr.io/google-samples/cassandra:v9 isn't up yet.  so we cant merge this.
we need to get someone to push the image 

`docker pull gcr.io/google-samples/cassandra:v9` failed for me

**Comment by chrislovecnm** [comment]
@brendandburns  @bgrant0607 who can push the docker image?

```make
build: kubernetes-cassandra.jar
	docker build -t gcr.io/google_samples/cassandra:${VERSION} .

push: build
	gcloud docker push gcr.io/google_samples/cassandra:${VERSION}
```

```make build && make push```

**Comment by chrislovecnm** [comment]
I just rebased ... Is it happy now?

**Comment by chrislovecnm** [comment]
cc @kubernetes/examples 

Can anyone on the examples group push a new container to gcr.io??  A PR needs a hand from a googler

**Comment by jayunit100** [comment]
LGTM

**Comment by pmdcosta** [comment]
gcr.io/google-samples/cassandra:v9 still needs to be pushed.

**Comment by chrislovecnm** [comment]
@bprashanth if you could do a docker push?

**Comment by jeffmendoza** [comment]
@chrislovecnm Pushed! Sorry I didn't do this earlier.

**Comment by chrislovecnm** [comment]
@jeffmendoza gcr.io/google-samples/cassandra:v9 is up?

**Comment by jeffmendoza** [comment]
yes, should be

**Comment by chrislovecnm** [comment]
@pmdcosta please file an issue if you run into anything.  Feedback is needed 😄

**Comment by chrislovecnm** [comment]
@jeffmendoza something odd perms wise on that build. One of the files cannot be edited by the start script. Of course it worked locally for me :( So the v9 image will not run.

I will be pushing another PR changing order of copy and chmod.

**Comment by chrislovecnm** [comment]
@jeffmendoza FYI https://github.com/kubernetes/kubernetes/issues/26023 ... so in the future we don't have the same problem :(

**Pull request merged**
