### PR TITLE
Update github.com/stretchr/testify rev to 7e4a149

### PR DESCRIPTION
**Pull request by tsenart**
This change set updates the `github.com/stretchr/testify` dependency to stretchr/testify@7e4a149.
Closes https://github.com/mesosphere/kubernetes-mesos/issues/333.
Ref: https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#discussion_r31859106

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by thockin** [comment]
If stretchr is good we should encourage it for all tests.

**Comment by tsenart** [comment]
I agree with that suggestion for the sake of consistency but would also
like to understand what you feel is missing from the stdlib testing package.

On Sunday, June 14, 2015, Tim Hockin <notifications@github.com> wrote:

> If stretchr is good we should encourage it for all tests.
>
> On Mon, Jun 8, 2015 at 1:04 PM, Tomás Senart <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > This change set updates the github.com/stretchr/testify dependency to
> > stretchr/testify@7e4a149
> > <https://github.com/stretchr/testify/commit/7e4a149>.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/GoogleCloudPlatform/kubernetes/pull/9425
> > Commit Summary
> >
> > - Update github.com/stretchr/testify/... rev to 7ea4a14
> > - kubelet: Use assert.EqualValues instead of assert.Equal
> >
> > File Changes
> >
> > - *M* Godeps/Godeps.json
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-0>
> > (6)
> > - *M*
> > Godeps/_workspace/src/github.com/stretchr/testify/assert/assertions.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-1>
> > (115)
> > - *M*
> > Godeps/_workspace/src/
> github.com/stretchr/testify/assert/assertions_test.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-2>
> > (57)
> > - *M* Godeps/_workspace/src/github.com/stretchr/testify/assert/doc.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-3>
> > (10)
> > - *M*
> > Godeps/_workspace/src/
> github.com/stretchr/testify/assert/forward_assertions.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-4>
> > (7)
> > - *M*
> > Godeps/_workspace/src/
> github.com/stretchr/testify/assert/forward_assertions_test.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-5>
> > (19)
> > - *M*
> > Godeps/_workspace/src/
> github.com/stretchr/testify/assert/http_assertions.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-6>
> > (8)
> > - *M* Godeps/_workspace/src/github.com/stretchr/testify/mock/mock.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-7>
> > (134)
> > - *M*
> > Godeps/_workspace/src/github.com/stretchr/testify/mock/mock_test.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-8>
> > (241)
> > - *M* pkg/kubelet/image_manager_test.go
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/pull/9425/files#diff-9>
> > (8)
> >
> > Patch Links:
> >
> > - https://github.com/GoogleCloudPlatform/kubernetes/pull/9425.patch
> > - https://github.com/GoogleCloudPlatform/kubernetes/pull/9425.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GoogleCloudPlatform/kubernetes/pull/9425>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/9425#issuecomment-111788030>
> .
>


-- 
Sent from Gmail Mobile

**Comment by thockin** [comment]
I personally am ambivalent. Initially I missed things like assertEQ,
finding those to be more readable. I have mostly forgotten how good I used
to have it.

As I said, if we (collectively) think stretchr is worthwhile, let's endorse
it. If not, let's purge it. All in or all out.

**Pull request merged**
