### PR TITLE
Fluentd on GCE master should not use ClusterFirst

### PR DESCRIPTION
**Pull request by ArtfulCoder**
Master does not have kube-proxy...

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
CC @a-robinson

**Comment by bprashanth** [comment]
Wait, why did merge-bot unassign me and assign Brendan. That's weird.

Hmm, don't we want the fluents on the node the continue being ClusterFirst? I guess this doesn't really matter as long as they never need to access a service.

**Comment by bprashanth** [comment]
Also this is broken for the non-gcp use case as well right? (which needs to access the ES service)

**Comment by a-robinson** [comment]
Yeah -- as @bprashanth mentions, fluentd-es is useless on the master and should be disabled there. And it would be nice to only set dnsPolicy to Default for fluentd-gcp on the master, but I don't think it's a deal-breaker.

And sorry for testing this improperly before. I was sticking dnsPolicy into the containerSpec instead of the podSpec and didn't see any logs telling me I was dumb...

**Comment by ArtfulCoder** [comment]
@a-robinson Are you sure that fluentd needs cluster dns server ?

**Comment by ArtfulCoder** [comment]
If you are sure, I can disable it on master, otherwise, I will have to investigate if fluentd needs cluster DNS

**Comment by a-robinson** [comment]
fluentd-es does, not fluentd-gcp.

**Comment by bprashanth** [comment]
I believe the non gcp one users the Elastic Search service in the cluster instead of google cloud logging: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/fluentd-es

**Comment by ArtfulCoder** [comment]
then, why should we stop collecting logs from master ?
We would be deviating from the old behavior where logs were collected from the master.

**Comment by ArtfulCoder** [comment]
in other words, this PR has the least impact and keeps the original intent.

**Comment by a-robinson** [comment]
I think we're talking past each other. Let's get this in and I'll update fluentd-es separately.

Before we can check it in, it looks like you'll have to update `docs/getting-started-guides/logging.md`, judging by the travis errors

**Comment by ArtfulCoder** [comment]
yes, We should keep the fluent-es change sepate from this pr.

**Comment by ArtfulCoder** [comment]
i believe head is broken (hack/verify-all.sh fails)
once head is fixed, this PR should be good to go

**Comment by a-robinson** [comment]
I do think you're going to have to update the logging doc because there's a verify script that compares a chunk of yaml in it to the contents of the file you modified. I'll LGTM though and let you sort that out with merge-bot

**Comment by ArtfulCoder** [comment]
updated the logging doc.

**Pull request merged**
