### PR TITLE
Cleanup TODO comment in the Job controller

### PR DESCRIPTION
**Pull request by mimowo**
#### What this PR does / why we need it:

We decided not to do it, see https://github.com/kubernetes/kubernetes/issues/113855, and https://github.com/kubernetes/kubernetes/issues/116858#issuecomment-1908355681.

#### Which issue(s) this PR fixes:

Tracking issue: https://github.com/kubernetes/enhancements/issues/3329

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
/hold
For the discussion related to the same code [here](https://github.com/kubernetes/kubernetes/pull/125994#discussion_r1672417807)

**Comment by mimowo** [comment]
/test pull-kubernetes-integration
overloaded infra: "There are no nodes that your pod can schedule to - check your requests, tolerations, and node selectors"

**Pull request merged**
