### PR TITLE
Bug fix 72757.Removed deprecated label kubernetes.io/cluster-service

### PR DESCRIPTION
**Pull request by ramnar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes deprecated labels in kuberenetes add-ons

**Which issue(s) this PR fixes**:

Remove deprecated label kubernetes.io/cluster-service in yaml files of kubernetes add-ons. Ref #72757

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
Why did you create so many similar PRs?  IMO these PRs contribute to the same goal and should be squashed into one commit within one PR

**Comment by ramnar** [comment]
> Why did you create so many similar PRs? IMO these PRs contribute to the same goal and should be squashed into one commit within one PR

This change was spanning many addons and touching around 50-60 files. I was concerned no reviewer will review so many files. So I created one PR per addon. What is the best practice by the way? I will take care from next time

**Pull request closed without merging**
