### PR TITLE
Fix firewall e2e test for multizone CIs

### LINKED ISSUE #46894: Firewall e2e test is failing frequently in gce-multizone CI
From #46737.

_[k8s.io] Firewall rule should have correct firewall rules for e2e cluster_ is failing frequently in gce-multizone CI with below error:
```
I0602 08:29:07.640] Jun  2 08:28:53.558: INFO: Failed to get instance tags for bootstrap-e2e-gce-mz-minion-group-87c3: googleapi: Error 404: The resource 'projects/k8s-jkns-e2e-gce-ubelite/zones/us-central1-a/instances/bootstrap-e2e-gce-mz-minion-group-87c3' was not found, notFound
```

The firewall e2e test isn't well written --- it doesn't expect instances to run in multiple zones so it always tries to get instances in the zone passed in by flag `--gce-zone` through ginko. But `--gce-zone` only passes in one of the zones, so firewall test will very likely fail when getting instances.

/sig network

/assign

### PR DESCRIPTION
**Pull request by MrHohn**
Fixes #46894.

- Getting node/master tags from config instead of instance.
- Don't assume instance always run in default zone.

/assign @freehan 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by MrHohn** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by MrHohn** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by cmluciano** [comment]
@mrhohn should this be included in the release as a bug fix?

**Comment by MrHohn** [comment]
@cmluciano The firewall test is the only one that is failing in gce-multizone CI. It would be better to include it so that we can have the real error signal.

**Comment by cmluciano** [comment]
cc @dchen1107

**Comment by nicksardo** [comment]
This is causing gke-ingress tests to fail: https://k8s-testgrid.appspot.com/google-gke#gke-ingress

**Pull request merged**
