### PR TITLE
WIP: Group unidentified containers into list of pods

### PR DESCRIPTION
**Pull request by yujuhong**
This PR groups unidentified docker containers into pods and return them through
`GetPods` in the Runtime interface to facilitate image management to be
container runtime-agnostic.
- All kubelet-managed, unidentified containers are grouped into one pod.
- All non-kubelet-managed containers are grouped into one pod. 

This partially addresses #7807.

### CODE REVIEW

**Comment by yujuhong** [comment]
@vmarmol, we had the discussion about whether or not to keep container GC at the kubelet level (or pushed it down to individual runtimes). This is what I had *before* the discussion, which tackles the image manager, but not the container GC part. I think we still need to determine whether kubelet is the best place for container/pod GC. If we decide against it, I'll ditch this PR :)

For the most part of the container runtime interface, we try to abstract away the container details (by making docker handles *pods*). If we want to keep the container GC at the kubelet level, we'd most likely have to instruct rkt to fake containers. For example, all dead rkt pods associated with the same kubelet pod should be listed in the `kubecontainer.Pod` as separate containers. Then the runtime interface needs to support a function to remove certain containers from a pod (e.g. or remove N oldest containers). This way, we may be able to keep most of the container GC code intact.

@yifan-gu, what do you think about this?

**Comment by erictune** [comment]
Grouping them in one pod seems wrong if they don't follow pod semantics:
share Linux namespaces, shared fate.  Pod per container seems better.

**Comment by dchen1107** [comment]
Agreed with @erictune on this. Sorry for not putting my comments on the initial issue first. Grouping same into a single pod might cause a lot of issues in the future for us.

**Comment by vmarmol** [comment]
This is an internal grouping used by the Kubelet. It's true that it doesn't follow the normal semantics of a pod, but it will allow us to better handle these pods without an owner.

Today we have: pods or "external" containers. We are trying to move to a model where we only handle pods. This PR aims to do that by making all "external" containers be in a "pod" from the point of view of the container runtime. It's true that we're trying to jam our current view into the pod abstraction, but at least it is only in the Kubelet <-> Container Runtime API. We can rename it "group" and maybe it solves most of the problems :)

I don't know if we want to go down the route of each "external" container being in its pod since:
- It isn't necessarily true, two containers may share a namespace. We shouldn't need to check that.
- In a thread-per-pod model, this is potentially expensive
- We have many "special" pods instead of just one

**Comment by vmarmol** [comment]
I think either route we go down will cause issues :) I think this route is potentially simpler, am happy to not use the "pod" name in the Runtime API if that helps. Using "external" containers is made more difficult with things like rkt that only speak pod and don't talk about containers like Docker does.

If you both feel strongly against it, we're happy to keep treating "external" containers differently.

**Comment by dchen1107** [comment]
My concern is that over time we are going to add more and more work to pod_worker, including per pod policies. With this change, eventually we might get into several different implementation of pod_worker, then what is the benefit to group them into a pod? 

I understand that rkt can only speak pod. But we also agreed that one container runtime per node. In that case, once the node is allocated to k8s cluster and using rkt, it shouldn't run any other containers except those management ones, right? In this case, I don't think much concerns here.

@yujuhong mentioned that all kubelet-managed, unidentified containers are grouped into one pod. Shouldn't that just one time things when we change our container name schema? We might change name schema later, and run into this issue again, but still don't think this is necessary.

**Comment by yifan-gu** [comment]
Some wild thinking: How about just call it gc unit, it can be pod for rkt or container for docker?

Actually it doesn't make sense to gc one container for rkt now, or gc one pod for docker IMO.

**Comment by yifan-gu** [comment]
What else places will we be interested in grouping the unidentified containers or pods except for GC?

I guess we will report the numbers of those containers/pods in some node status as well?

**Comment by vmarmol** [comment]
Spoke offline with @dchen1107 and @yujuhong. There are 3 types of containers from the point of view of the Kubelet:
- Non-Kubernetes containers: ignore them
- Kubernetes containers that we know of: work with them as per usual
- Kubernetes containers that we don't know of (containers we can't parse into pods): kill them

This change was primarily to better handle the third case. We've seen this once when we renamed our Docker containers. This case is small enough that it is not worth making the fake pod abstraction. We will punt to the runtimes with a `KillUnknownKubernetesContainers()` or the like.

For container and image GC the behavior per runtime is different enough that we will punt those per runtime as well.

Closing this PR, thanks (and sorry for the churn) @yujuhong!

**Comment by yujuhong** [comment]
As @vmarmol said, we've decided to push both image and container GC to individual runtimes. Below are just some responses to the previous comments.

> Non-Kubernetes containers: ignore them
Image manager (for Docker at least) needs to be aware of non-kubernetes containers, so that it doesn't remove the images that are used by other containers. I am not sure how rkt handles images though.

> What else places will we be interested in grouping the unidentified containers or pods except for GC?
> I guess we will report the number of those containers/pods in some node status as well?
I don't believe we need to report the number of containers in node status as long as we can report cpu/mem usage of the current node.

> Actually it doesn't make sense to gc one container for rkt now, or gc one pod for docker IMO.
Yes, it needs some work (faking) for rkt and docker to use the same notion for GC. I guess they are different enough that we should implement GC for them separately. IMO, we should still have some high-level, pod-wise GC policies.

**Comment by yifan-gu** [comment]
Pushing GC to runtime SGTM.

**Pull request closed without merging**
