### PR TITLE
Move Until, Forever, NeverStop and ForeverTestTimeout from util to wait

### PR DESCRIPTION
**Pull request by ingvagabund**
wait package is more suitable for Until, Forever, NeverStop and ForeverTestTimeout. util is too general for it.

### CODE REVIEW

**Comment by ingvagabund** [comment]
@lavalamp this is a simple renaming of qualifiers. Could be worth documenting to use wait.Until instead of util.Until. What do you think? Is there anything else related to util package and working with Until? E.g. documentation, practises?

**Comment by ingvagabund** [comment]
@smarterclayton @timothysc @pmorie @kubernetes/rh-cluster-infra

**Comment by pmorie** [comment]
LGTM, but leave final review to @lavalamp

**Comment by aveshagarwal** [comment]
LGTM

**Comment by ingvagabund** [comment]
I don't think the error in the Mesos tests is related to this PR.

**Comment by lavalamp** [comment]
Moving sounds fine to me, I'm swamped with reviews so giving this to @krousey.

**Comment by smarterclayton** [comment]
I'll take the final review.  Please rebase.

**Comment by ingvagabund** [comment]
PTAL

**Comment by smarterclayton** [comment]
lgtm

**Pull request merged**
