### PR TITLE
Add result check for kubectl cp remote command

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

**What this PR does / why we need it**:
Add result check for kubectl cp remote command
    
This adds a check of the result returned from the check if the remote
file spec is a directory or not. If the test binary was missing, the
code would interpret the crash as a "the remote file spec is not a
directory".
    
This adds a check to see if the return code is 0 (success, is dir), 1
(fail, is not dir) or if there is another error, and then stops the
execution of the copy command.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/sig cli
/priority important-soon

**Does this PR introduce a user-facing change?**:

```release-note
Fix problems related to missing 'test' binary in kubectl cp
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
looks like some actual test failures in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79494/pull-kubernetes-bazel-test/1144360893316861953

**Comment by odinuge** [comment]
Yes @BenTheElder! The tests depending on the old behaviour of not checking the result of the remote command, now fails. I guess this implies that this is indeed a problem with the current implementation. 😄

They fail with: `unexpected error: error when checking if destination is directory: the server could not find the requested resource (get pods pod-name)`, when they previously just carried on thinking that the remote spec was _not_ a directory.

Ill let @apelisse look at this PR, and decide if this approach is ok (also ref. #79075). Either way, i will look at the tests this weekend.

**Comment by apelisse** [comment]
That looks good to me. Ping me when the tests are fixed so that I can  lgtm.

Thanks

**Comment by apelisse** [comment]
gentle ping?

**Comment by odinuge** [comment]
Hi @apelisse 

Sorry that this has taken a bit too long. I have been trying to mock the pod `exec` operations, but I have not found a nice way to do it properly. The current tests `TestCopyToPod` expects the `checkDestinationIsDir` func to return an error, and since it doesn't check what kind it is, it doesn't matter.

I feel kinda bad about throwing out the test, but running an exec in a pod inside a unit test also feels a bit strange. The best would be to write some more e2e tests to properly verify the overall behavior, and writing more specific unit tests (and we already have quite a few).

Any thoughts?

**Pull request closed without merging**
