### PR TITLE
Automated cherry pick of #105213: remove StartedPodsErrorsTotal metrice message

### PR DESCRIPTION
**Pull request by harche**
Cherry pick of #105213 on release-1.22.

#105213: remove StartedPodsErrorsTotal metrice message

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/hold cancel
/test pull-kubernetes-integration
pull-kubernetes-integration fixed via https://github.com/kubernetes/test-infra/pull/23936

**Pull request merged**
