### PR TITLE
Cherrypick: Update defaultbackend to v1.5

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Updates defaultbackend to 1.5
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@bowei Can you add a link to release notes of the new version, or some other indication of what are the changes?

**Comment by MaciekPytel** [comment]
@bowei Do we need this in 1.10.10? If so it needs to be lgtm-ed today.

**Comment by MaciekPytel** [comment]
/hold 
For 1.10.10

**Comment by jonpulsifer** [comment]
@MaciekPytel Ref https://github.com/kubernetes/ingress-nginx/pull/3125 this is the PR that resulted in `defaultbackend-amd:1.5`

tl;dr: placed `/metrics` and `/healthz` behind tcp:10254

in > 1.5 there will be no `/metrics` endpoint

(ps you can find defaultbackend [here](https://github.com/kubernetes/ingress-gce/tree/master/cmd/404-server) now)

**Pull request merged**
