### PR TITLE
Backoff limit per index e2e test

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Part of: https://github.com/kubernetes/enhancements/issues/3850

#### Special notes for your reviewer:

This PR is meant to demonstrate the feature works e2e before graduation to Beta.

It is built on top of the graduation PR: https://github.com/kubernetes/kubernetes/pull/121356, as a new commit just with e2e test. 

It will get merged once the graduation PR is merged and it is rebased.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/approve
/hold
for main PR

**Comment by mimowo** [comment]
/hold cancel
As the main PR is merged: https://github.com/kubernetes/kubernetes/pull/121356

**Comment by mimowo** [comment]
/remove-kind api-change
This label should be removed after rebase

**Comment by mimowo** [comment]
/remove-area code-generation 
/remove-sig api-machinery
This should also be removed after rebase

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
