### PR TITLE
Remove feature gate - DebugContainers

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

We just have a feature gate, with no other code referring to it. So let's remove the gate for now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove unimplemented feature gate for DebugContainers
```

### CODE REVIEW

**Comment by embano1** [comment]
What about this code which was introduced for DebugContainers? https://github.com/kubernetes/kubernetes/commit/ba6f31a6c6

**Comment by dims** [comment]
@embano1 done!

**Comment by verb** [comment]
I'm still actively working on this. I would prefer if you hold off for a few weeks before removing it. If you don't see any progress by then we can remove it.

**Comment by dims** [comment]
ack @verb

**Comment by yujuhong** [comment]
DebugContainer is targeted for 1.12 in sig-node's planning AFAIK. Let's hold on to this for now and track the progress in https://github.com/kubernetes/features/issues/277  :-)

**Comment by dims** [comment]
Thanks @yujuhong @verb 

/close

**Pull request closed without merging**
