### PR TITLE
Automated cherry pick of #117449: e2e: fix flaky test 'should contain OpenAPI V3 for Aggregated

### PR DESCRIPTION
**Pull request by tmilox**
Cherry pick of #117449 on release-1.27.

#117449: e2e: fix flaky test 'should contain OpenAPI V3 for Aggregated

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by TommyStarK** [comment]
@Jefftree backport the fix to 1.27. If there is anything don't hesitate :)

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve

**Pull request merged**
