### PR TITLE
Modify the kubelet document

### PR DESCRIPTION
**Pull request by moricho**
Modify the link to "KEP 14 - Moving ComponentConfig API types to staging repos" which was dead in kubelet README.md

Signed-off-by: moricho <ikeda.morito@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/approve

Thanks @moricho :+1:!

**Comment by moricho** [comment]
@luxas Thank for review!

**Comment by SergeyKanzhelev** [comment]
timeout again...

/test pull-kubernetes-e2e-kind-ipv6

**Pull request merged**
