### PR TITLE
rebuilt kube2sky to use v1 api. new image ver is 1.11

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
@nikhiljindal

**Comment by nikhiljindal** [comment]
Thanks @ArtfulCoder Verified that this fixes the problem.

**Comment by ArtfulCoder** [comment]
@k8s-bot test this please

**Comment by ArtfulCoder** [comment]
Please review..

**Comment by bgrant0607** [comment]
LGTM
ok to merge

**Comment by caesarxuchao** [comment]
subscribe

**Pull request merged**
