### PR TITLE
Implement view command for viewing container images

### LINKED ISSUE #29679: kubectl view commands
We're adding `kubectl set` commands to change specific fields #21648.

Similarly, I think we need `kubectl view` commands (`get` already has a meaning) to extract specific fields without needing jsonpath or Go templates.

| Subcommand | Issue # | PR # | Assignee |
| --- | --- | --- | --- |
| \- [ ] image |  | #51428 | @zjj2wry |
| \- [ ] annotation | #19817 |  |  |
| \- [ ] label | #19817 |  |  |
| \- [ ] env |  |  |  |
| \- [ ] probe |  |  |  |
| \- [ ] volume |  |  |  |
| \- [ ] limits |  |  |  |
| \- [ ] security |  |  |  |
| \- [ ] port |  |  |  |

### PR DESCRIPTION
**Pull request by alexbrand**
**What this PR does / why we need it**:
This PR is an initial implementation of a `kubectl view` command and `kubectl view image` sub-command.
**Which issue this PR fixes** 
fixes #29679

Looking for some feedback before adding more sub-commands.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33034)

### CODE REVIEW

**Comment by ymqytw** [comment]
Please add some test. You can put it in hack/make-rules/test-cmd.sh. For your convenience, you can refer #25509
And please remember to make sure you have updated all the files by using "make check".

---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/kubectl/cmd/util/factory.go, line 156 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3gxmn_1E4DGLuvV_l:-KS3gxmn_1E4DGLuvV_m:bua13mc) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/util/factory.go#L156)):*
> ```Go
> 	// RunIfPodSpecForObject will call the provided function on the pod spec this object supports,
> 	// return false if no pod spec is supported, or return an error.
> 	RunIfPodSpecForObject func(obj runtime.Object, fn func(*api.PodSpec) error) (bool, error)
> ```

I think using name "VisitPodSpecForObject" should be more easier to understand what this function does.

---

*[pkg/kubectl/cmd/view/view.go, line 28 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3FtDnCCJl--Wdme0f:-KS3FtDnCCJl--Wdme0g:ba3yff0) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view.go#L28)):*
> ```Go
> 
> var (
> 	viewLong = dedent.Dedent(`
> ```

Please use snake case to match the others we have in the repo.

---

*[pkg/kubectl/cmd/view/view_image.go, line 38 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3GaKxF4hpAKeYCqLv:-KS3GaKxF4hpAKeYCqLw:b-ocb2ks) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L38)):*
> ```Go
> 
> var (
> 	imageResources = `
> ```

Please use snake case.

---

*[pkg/kubectl/cmd/view/view_image.go, line 41 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3Gaw-pQGq16tlcVJc:-KS3Gaw-pQGq16tlcVJd:b-ocb2ks) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L41)):*
> ```Go
>   pod (po), replicationcontroller (rc), deployment (deploy), daemonset (ds), job, replicaset (rs)`
> 
> 	imageLong = dedent.Dedent(`
> ```

Please use snake case.

---

*[pkg/kubectl/cmd/view/view_image.go, line 46 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3GcezwyEpRM_Sc_0F:-KS3GcezwyEpRM_Sc_0G:b-ocb2ks) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L46)):*
> ```Go
> 		Possible resources include (case insensitive):`) + imageResources
> 
> 	imageExample = dedent.Dedent(`
> ```

Please use snake case.

---

*[pkg/kubectl/cmd/view/view_image.go, line 67 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3ZO_Z__wcGSoaoNih:-KS3ZO_Z__wcGSoaoNii:b-hoh7b1) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L67)):*
> ```Go
> 
> 	usage := "Filename, directory, or URL to a file identifying the resource to get from a server."
> 	cmd.Flags().BoolVar(&options.all, "all", false, "select all resources in the namespace of the specified resource types")
> ```

I recommend creating helper functions that will be used in kubectl set, kubectl view.

---

*[pkg/kubectl/cmd/view/view_image.go, line 69 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3e6_82H9B9wKP4Ac5:-KS3e6_82H9B9wKP4Ac6:bxmwi2s) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L69)):*
> ```Go
> 	cmd.Flags().BoolVar(&options.all, "all", false, "select all resources in the namespace of the specified resource types")
> 	cmd.Flags().StringVarP(&options.selector, "selector", "l", "", "Selector (label query) to filter on")
> 	cmdutil.AddRecordFlag(cmd)
> ```

It seems that you are not using the flag --record. So you don't need to add it.

---

*[pkg/kubectl/cmd/view/view_image.go, line 74 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3GzV3ownkecUc8Ti3:-KS3GzV3ownkecUc8Ti4:b-ieu1cn) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L74)):*
> ```Go
> }
> 
> func (o *imageOptions) run(f *cmdutil.Factory, cmd *cobra.Command, args []string) error {
> ```

Please change name to Run() to match the others we have in the repo.

---

*[pkg/kubectl/cmd/view/view_image.go, line 82 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3jrlYsRR6gk7OIc-2:-KS3jrlYsRR6gk7OIc-3:bwir94i) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L82)):*
> ```Go
> 
> 	pairType := "image"
> 	resources, _, err := cmdutil.GetResourcesAndPairs(args, pairType)
> ```

I don't think you really need to do this. You can pass "args" to func ResourceTypeOrNameArgs(o.all, args...), it should work.

---

*[pkg/kubectl/cmd/view/view_image.go, line 109 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KS3kZyrC4eCDsTGwNWG:b-tlrp0o) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
> ```Go
> 
> 	for _, i := range infos {
> 		f.RunIfPodSpecForObject(i.Object, printImages)
> ```

I recommend writing func printImages nested, if it's used only once.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-:-KS3kpAdaWjI8TTgRwn2:b-mq45rz)*

**Comment by alexbrand** [comment]
@ymqytw Thanks for the thorough review.

Will `make verify` run the tests in `test-cmd.sh`. Want to make sure I run them before submitting.

**Comment by ymqytw** [comment]
No, `make verify` will just check format of everything. If you want to run the tests in `test-cmd.sh`, you can use `make test-cmd`.

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/view/view.go, line 28 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3FtDnCCJl--Wdme0f:-KS8yxhuxvSlxHLx8jlH:b-piryn) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view.go#L28)):*
> snake
this is not very consistent, some commands use snake case, others not.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/view/view.go, line 37 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS8zG-W_3N8FJEGuq6N:-KS8zG-W_3N8FJEGuq6O:b9191l6) ([raw file](https://github.com/kubernetes/kubernetes/blob/4357faebb415d7ffb9c62de5aaa0649f41bee681/pkg/kubectl/cmd/view/view.go#L37)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "view SUBCOMMAND",
> 		Short: "View specific fetures on objects",
> ```

typo. `fields` would be better.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 109 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KS9-INP1ED0QK08DkQE:boq7mf5) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> I recommend writing func printImages nested, if it's used only once.
</details>
Please paste the command output here.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/kubectl/cmd/view/view.go, line 28 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3FtDnCCJl--Wdme0f:-KSEEpHYXB47T7tvzlwh:b1u0gr2) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view.go#L28)):*
<details><summary><i>Previously, AdoHe (TonyAdo) wrote…</i></summary>
> > snake
> this is not very consistent, some commands use snake case, others not.
</details>
You are right. There are some commands that use camelCase. But let's use snake case to be consistent with `kubectl set image`, which is the counterpart of `kubectl view image`.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
@k8s-bot ok to test

**Comment by alexbrand** [comment]
Review status: 0 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/kubectl/cmd/util/factory.go, line 156 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3gxmn_1E4DGLuvV_l:-KSMx5HD9Yfe7IajIiCY:bha1teh) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/util/factory.go#L156)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> I think using name "VisitPodSpecForObject" should be more easier to understand what this function does.
</details>
Updated func name.

---

*[pkg/kubectl/cmd/view/view_image.go, line 109 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KSMy1MRHZ48C1A7mJXq:b-ech21n) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
<details><summary><i>Previously, AdoHe (TonyAdo) wrote…</i></summary>
> Please paste the command output here.
</details>
Command output: 
```
=> ./kubectl view image deployment/nginx-deployment
gcr.io/google-containers/nginx:test-cmd
gcr.io/google-containers/perl
```

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by alexbrand** [comment]
Review status: 0 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/kubectl/cmd/view/view_image.go, line 67 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3ZO_Z__wcGSoaoNih:-KSMyQED_vvPm14o00Z-:b-ev6w7r) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L67)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> I recommend creating helper functions that will be used in kubectl set, kubectl view.
</details>
I am not exactly sure what the helper function would do.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 67 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3ZO_Z__wcGSoaoNih:-KSN9WIgGGF8RHyUIeLD:b-ss3d3f) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L67)):*
<details><summary><i>Previously, alexbrand (Alexander Brand) wrote…</i></summary>
> I am not exactly sure what the helper function would do.
</details>
What I mean is creating a helper function for adding flag `--all` and  `--selector`, which can be called by other commands, e.g, in pkg/kubectl/cmd/set/set_image.go call that function to add flag. The helper function will looks like cmdutil.AddFilenameOptionFlags()
But you can keep what you have now. You don't need to change anything. Ignore this comment.
Maybe we can refactor these in another PR.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 66 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KSNCGgq_4t0VA42whrO:-KSNCGgq_4t0VA42whrP:b2vdolx) ([raw file](https://github.com/kubernetes/kubernetes/blob/195ef644a6b86291a7863242f790d99f8c0a752f/pkg/kubectl/cmd/view/view_image.go#L66)):*
> ```Go
> 	}
> 
> 	usage := "Filename, directory, or URL to a file identifying the resource to get from a server."
> ```

Please remove "Filename, directory, or URL to a file ". 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by alexbrand** [comment]
@ymqytw @AdoHe I'm having a hard time figuring out why the unit/integration build is failing. Any pointers you could provide?

**Comment by ymqytw** [comment]
What is the result of unit test and integration test on your local machine?
You can use `make check` to run all the unit tests and use `make test-integration` to run all the integration tests. You can also run against part of the unit tests by using `WHAT`, e.g. `make check WHAT=pkg/kubectl/cmd`

**Comment by AdoHe** [comment]
@k8s-bot unit test this

**Comment by alexbrand** [comment]
Rebased from master. Looks like the test that was failing in hack/make-rules/test-cmd.sh was updated.

**Comment by alexbrand** [comment]
Turns out what I thought was a failure isn't really one, as it's showing up on other Green test runs from other PRs.
```
message:Error from server (NotFound): pods "abc" not found
has:pods "abc" not found
FAIL!
message:Error from server (NotFound): pods "abc" not found
has not:List
1064 hack/make-rules/test-cmd.sh
```

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 109 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KTAZqbM9axyu1HP2p5e:b-djzt7t) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
I think we should output the image name and who owns the image, since we support flag `--all`.
E.g. if we use `kubectl view image pods --all`, it will make more sense to output:
> pod1 image1
pod2 image1
pod3 image1
pod4 image2
pod5 image2

instead of:
> image1
image1
image1
image2
image2

@AdoHe Does it make sense to you?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 109 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KTMLMVwEwW8M4T_HKa2:b8dv3sq) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> I think we should output the image name and who owns the image, since we support flag `--all`.
> E.g. if we use `kubectl view image pods --all`, it will make more sense to output:
> > pod1 image1
> pod2 image1
> pod3 image1
> pod4 image2
> pod5 image2
> 
> instead of:
> > image1
> image1
> image1
> image2
> image2
> 
> @AdoHe Does it make sense to you?
</details>
yep, that makes sense to me. or even `<type>/<name> <imageName>`, wdyt?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 109 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KTMLkHDHnbcTPugIOy8:bijqe19) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
<details><summary><i>Previously, AdoHe (TonyAdo) wrote…</i></summary>
> yep, that makes sense to me. or even `<type>/<name> <imageName>`, wdyt?
</details>
@alexbrand @ymqytw

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 109 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KS3kZyrC4eCDsTGwNWF:-KTMVUeD0O8Ti96EyXJM:b-su19kn) ([raw file](https://github.com/kubernetes/kubernetes/blob/b021443f0224ab3105c6c9c5a1334e40e1093e1a/pkg/kubectl/cmd/view/view_image.go#L109)):*
> `<type>/<name> <imageName>`

Agree.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by alexbrand** [comment]
Thanks @AdoHe @ymqytw - I'll make this change

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 100 at r11](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KTksEM8lQZ76mQao0fF:-KTksEM96x_E2GExELS1:b-nnipca) ([raw file](https://github.com/kubernetes/kubernetes/blob/15a41faa669c6b52d2b2c5e3ed265fdda58a7e54/pkg/kubectl/cmd/view/view_image.go#L100)):*
> ```Go
> 				var resourceName string
> 				if alias, ok := kubectl.ResourceShortFormFor(i.ResourceMapping().Resource); ok {
> 					resourceName = alias
> ```

Why using a short form resource name here? I think using the full resource name returned by `i.ResourceMapping().Resource` is fine.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by alexbrand** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kubectl/cmd/view/view_image.go, line 100 at r11](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KTksEM8lQZ76mQao0fF:-KTktJI14bFnGRcNt4k2:bbxv311) ([raw file](https://github.com/kubernetes/kubernetes/blob/15a41faa669c6b52d2b2c5e3ed265fdda58a7e54/pkg/kubectl/cmd/view/view_image.go#L100)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Why using a short form resource name here? I think using the full resource name returned by `i.ResourceMapping().Resource` is fine.
</details>
My only reason was consistency with the get command. I can certainly change it if that doesn't make sense here. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 100 at r11](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KTksEM8lQZ76mQao0fF:-KTlSc0IF_PfW2Nazp34:btcyr06) ([raw file](https://github.com/kubernetes/kubernetes/blob/15a41faa669c6b52d2b2c5e3ed265fdda58a7e54/pkg/kubectl/cmd/view/view_image.go#L100)):*
> My only reason was consistency with the get command.
Can you give me an example?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by alexbrand** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kubectl/cmd/view/view_image.go, line 100 at r11](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KTksEM8lQZ76mQao0fF:-KTnuIisYh3C8VpbIxaw:b-m3i9tn) ([raw file](https://github.com/kubernetes/kubernetes/blob/15a41faa669c6b52d2b2c5e3ed265fdda58a7e54/pkg/kubectl/cmd/view/view_image.go#L100)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> > My only reason was consistency with the get command.
> Can you give me an example?
</details>
```
./kubectl get pods --show-kind
NAME                       READY     STATUS              RESTARTS   AGE
po/nginx-701339712-4imx1   0/1       ContainerCreating   0          23s
```

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by ymqytw** [comment]
*[pkg/kubectl/cmd/view/view_image.go, line 100 at r11](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034#-KTksEM8lQZ76mQao0fF:-KToSPsrKFnzQRmPiqm6:b9ovj49) ([raw file](https://github.com/kubernetes/kubernetes/blob/15a41faa669c6b52d2b2c5e3ed265fdda58a7e54/pkg/kubectl/cmd/view/view_image.go#L100)):*
<details><summary><i>Previously, alexbrand (Alexander Brand) wrote…</i></summary>
> ```
> ./kubectl get pods --show-kind
> NAME                       READY     STATUS              RESTARTS   AGE
> po/nginx-701339712-4imx1   0/1       ContainerCreating   0          23s
> ```
</details>
I see. Using short form resource name is OK. But when short form doesn't exist, using "none" doesn't make sense to me. Full name should be fine.
To be consistent with `get`, I think a similar flag  `--no-headers` can added to control if printing header. And we want format like "resourceName/name  containerName  imageName".
Since the printing logic is becoming complicated, maybe you can try to wrap the printing logic into a printer func and put it in pkg/kubectl/resource_printer.go.
@AdoHe WDYT?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33034)*

**Comment by AdoHe** [comment]
@alexbrand as you see, a normal get output is:
```
./kubectl get pods
NAME                       READY     STATUS              RESTARTS   AGE
nginx-701339712-4imx1   0/1       ContainerCreating   0          23s
```
with `show-kind` flag, we add short resource name:
```
./kubectl get pods --show-kind
NAME                       READY     STATUS              RESTARTS   AGE
po/nginx-701339712-4imx1   0/1       ContainerCreating   0          23s
```
I would hope we can follow this rule, also add `no-header` flag sounds good to me.

**Comment by ymqytw** [comment]
@AdoHe Yes, we should follow this role.
Does output format
"shortResourceName/name containerName imageName"
sound good to you?

**Comment by AdoHe** [comment]
@ymqytw sgtm, let's just go ahead.

**Comment by alexbrand** [comment]
Thanks @AdoHe @ymqytw 

To summarize, we will always print with the following format:
`shortResourceName/name containerName imageName`

In terms of the no-header flag, what will this flag do? We are not printing any headers in the output of this command.

I also wonder if we are deviating from the original proposal: https://github.com/kubernetes/kubernetes/issues/29679#issuecomment-242831185, but I don't see a way around this if we'll support printing multiple resources.

**Comment by ymqytw** [comment]
@alexbrand I think we can output something like what `get` does with `--no-head=false`. We can default `--no-header` to `true` if we really don't want the head.

**Comment by ymqytw** [comment]
@alexbrand What is the status now?
FYI: Code freeze in less than 2 weeks away for 1.5. I hope we can get this PR merged before that.

**Pull request closed without merging**
