### PR TITLE
kube-proxy userspace, enable RR if connect endpoint which is session affinity fails

### PR DESCRIPTION
**Pull request by njuicsgz**
for issue #24648

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
Please get the CLA sorted out

**Comment by thockin** [comment]
change looks good, thanks for the test :)

**Comment by njuicsgz** [comment]
updated CLA with this github account 'njuicsgz'.

**Comment by njuicsgz** [comment]
I signed it!

**Comment by zhouhaibing089** [comment]
@njuicsgz you could squash the latest three commits(the author of the first commit does not get CLA). then doing this: `git commit --amend --author '${NAME} <${MAIL_ADDRESS>'`

**Comment by njuicsgz** [comment]
@zhouhaibing089 thanks a lot!

**Comment by thockin** [comment]
```
Verifying ./hack/../hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./pkg/proxy/userspace/roundrobin_test.go
FAILED   ./hack/../hack/verify-gofmt.sh	6s
```

**Comment by thockin** [comment]
please squash the commits and we can LGTM

**Comment by thockin** [comment]
ping?

**Comment by njuicsgz** [comment]
Sorry for late due to we have a vacation in last 3 days.

**Comment by njuicsgz** [comment]
@thockin can you merge this PR since all checks have passed?

**Pull request merged**
