### PR TITLE
Automated cherry pick of #75087: fix smb unmount issue on Windows

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #75087 on release-1.12.

#75087: fix smb unmount issue on Windows

### CODE REVIEW

**Comment by feiskyer** [comment]
/ok-to-test

@jingxu97 Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.

/assign @jingxu97

**Comment by andyzhangx** [comment]
ping @jsafrane @jingxu97 for approval, thanks

**Pull request merged**
