### PR TITLE
Add 'inline' field annotation in protobuf messages.

### PR DESCRIPTION
**Pull request by wojtek-t**
It was requested internally in Google - a project that is using Kubernetes underneath needs to know which protobuf fields translate to "inline' field in json/yaml.

@smarterclayton - what do you think about this PR?

@lavalamp

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30271)

### CODE REVIEW

**Comment by smarterclayton** [comment]
I kind of wish we didn't have to do this (because it introduces an extension, and leaks struct details).  Are they trying to generate our Go structs from our protobuf (which was something we explicitly said we wouldn't support in the original proposal)?

**Comment by smarterclayton** [comment]
Or is this so the native proto -> JSON generates compatible objects?  I'm scared about that as well, since we didn't make that guarantee originally (we will eventually have to do unions and that complicates unioning as well).

Also, technically the "embed" gogo proto extension already does this, and we strip that out of the generated proto so we can have "clean" protos.  I might prefer using embed to inventing our own, although not all "inline" directly translate to "embed".

**Comment by steve-wolter** [comment]
I'm the google internal requester.

This is so that I can convert from proto to compatible JSON/YAML, and back. I need to do that because Cloud Deployment Manager only processes YAML, and Google-internal configuration languages expect to work with proto.

I've already run into the problem that the proto -> JSON conversion is broken for other structs as well (IntOrString is a typical culprit). I'm happy to consider any alternative solutions you might be thinking about, and I'm looking into compiling and calling conversion code from within K8s. Do you have any pointers how to do it better?

**Comment by smarterclayton** [comment]
I think it's a reasonable request, but we explicitly excluded proto -> JSON
transformation in the original proposal for complexity reasons (the correct
proto serialization may not be 1:1 with the correct JSON serialization).
IntOrString, times, optional slices, embedded structs, and raw object are
the five examples right now that are known different (where you'd probably
need data on the proto spec beyond this field to achieve that).

Certainly the internal "parse proto via Kube code -> write YAML" flow is
one we will always keep working.  I think that's something we would want to
do via a command line tool at some point - I'm not at all opposed to there
being an easy to consume library for that.  I would slightly prefer (not
knowing your use case) to push you down this path if you need to transform
kube proto into kube json.

**Pull request closed without merging**
