### PR TITLE
Update debian setup script to match GCI.

### PR DESCRIPTION
**Pull request by dnardo**
Even though this file is deprecated in 1.8 and 1.9, add this for consistency and this will also be cherry picked back to 1.7

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Humm, I wanted to say removing another "flush" but seems like there isn't any in this script.

/lgtm

**Comment by MrHohn** [comment]
@wojtek-t This PR is in fact against the master branch.

**Comment by wojtek-t** [comment]
@MrHohn - yes I know. I'm just marking it as "cherrypick-candidate" which is making me remember that this should be cherrypicked. There are basically two groups of people:
- one marking the original PR as candidate
- second marking the actual cherrypick as candidate
I'm just in the first group :)

**Comment by wojtek-t** [comment]
Ohh - and obviously the third (largest) group that is not adding this label anywhere :)

**Comment by MrHohn** [comment]
@dnardo I just tested this locally, and something went wrong in startup scripts:
```
# tail /var/log/startupscript.log
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: iptables v1.4.14: unknown option "-w"
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Try `iptables -h' or 'iptables --help' for more information.
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: iptables v1.4.14: unknown option "-w"
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Try `iptables -h' or 'iptables --help' for more information.
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: iptables v1.4.14: unknown option "-w"
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Try `iptables -h' or 'iptables --help' for more information.
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Add rules for ip masquerade
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: iptables v1.4.14: unknown option "-w"
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Try `iptables -h' or 'iptables --help' for more information.
Dec 12 20:34:54 e2e-test-*-minion-group-58cx startupscript: Finished running startup script /var/run/google.startup.script

```

**Comment by dnardo** [comment]
@MrHohn  looks like it doesn't support the lock waiting

**Comment by dnardo** [comment]
@MrHohn I've updated the PR to reflect the fact that the --wait isn't supported.  I guess this has to do with the debian image version?
I don't love removing the wait but since this deprecated and we are only doing this to essentially fix the 1.7 tests I think it should be ok.
Thoughts?

**Comment by wojtek-t** [comment]
> I don't love removing the wait but since this deprecated and we are only doing this to essentially fix the 1.7 tests I think it should be ok.
Thoughts?

+1

**Comment by MrHohn** [comment]
Removing the wait SGTM.

/lgtm

**Comment by MrHohn** [comment]
@dnardo Sorry to pop up again, I just found out there is another "flush" command in configure-vm.sh...
https://github.com/kubernetes/kubernetes/blob/2ca9a3185ca23a86b6c40f3a8d9eaea738183459/cluster/gce/configure-vm.sh#L169-L178
It doesn't seem to affect here because at HEAD `remove-docker-artifacts` happens before `config-ip-firewall`.
https://github.com/kubernetes/kubernetes/blob/2ca9a3185ca23a86b6c40f3a8d9eaea738183459/cluster/gce/configure-vm.sh#L872-L873

Though in 1.7 `config-ip-firewall` happens before `remove-docker-artifacts`, we need to be careful :/
https://github.com/kubernetes/kubernetes/blob/87a07f4c261a608077783a423f55b5a999f48125/cluster/gce/configure-vm.sh#L844-L858

**Comment by dnardo** [comment]
@MrHohn Thanks, I suppose we can get rid of the second flush and cherry pick that back to 1.7  Can you think of any reason we cannot just pull it out?  I don't want to worry about ordering down the road (even though this is going away anyway)

**Comment by wojtek-t** [comment]
@MrHohn @dnardo - can you prepare a PR to fix this in 1.7 branch. This is blocking cutting the next 1.7 patch release.

**Comment by MrHohn** [comment]
> MrHohn Thanks, I suppose we can get rid of the second flush and cherry pick that back to 1.7 Can you think of any reason we cannot just pull it out? I don't want to worry about ordering down the road (even though this is going away anyway)

That sounds good.

@wojtek-t We will verify what @dnardo suggested locally and send out the cherrypick first thing tomorrow, is that Okay?

**Comment by wojtek-t** [comment]
> @wojtek-t We will verify what @dnardo suggested locally and send out the cherrypick first thing tomorrow, is that Okay?

Sure - I didn't expect you to do anything now :)

**Comment by dnardo** [comment]
@wojtek-t  @MrHohn Yes sorry for the delay this is my priority this morning.

**Comment by dnardo** [comment]
@wojtek-t @MrHohn I've updated this pr to exclude the other flush

**Comment by wojtek-t** [comment]
@dnardo @MrHohn - so do I understand correctly that we don't want to cherrypick it to 1.8 and 1.9 because debian is deprecated anyway there, right?

**Comment by dnardo** [comment]
That is my understanding yes.  It couldn't hurt to put it in 1.8 and 1.9 if we need to but if we don't test it in those versions that I think it should be fine.

**Pull request merged**
