### PR TITLE
cleanup: fix some error log capitalization

### PR DESCRIPTION
**Pull request by wangyx1992**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some log-lines start with capital letters.

**Which issue(s) this PR fixes**:
Ref #15863

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by matthyx** [comment]
> @wangyx1992: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

ditto... it's a user facing change and therefore requires a note.

**Review by damemi — COMMENTED** [review]
/ok-to-test

**Comment by damemi** [comment]
@wangyx1992 the bot added the `release-note-needed` label because it didn't pick up your release-note block's formatting. In the future, the block needs to be formatted like so (note the `release-note` is on the first line with the opening 3 backticks):
``` 
```release-note
NONE
.``` 
```

This probably isn't significant enough of a user-facing change to require one (we have other PRs with changes like this that don't)

**Comment by SergeyKanzhelev** [comment]
/lgtm
/retest

(failures do not look relevant)

**Comment by wangyx1992** [comment]
> @wangyx1992 the bot added the `release-note-needed` label because it didn't pick up your release-note block's formatting. In the future, the block needs to be formatted like so (note the `release-note` is on the first line with the opening 3 backticks):
> 
> ```
> ```release-note
> NONE
> .``` 
> ```
> 
> This probably isn't significant enough of a user-facing change to require one (we have other PRs with changes like this that don't)

Thanks for your suggestion, I have added the release-note block back.

**Comment by wangyx1992** [comment]
> > @wangyx1992: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.
> 
> ditto... it's a user facing change and therefore requires a note.

Now the release-note block is added back, which was deleted by mistake before. And then, should I add an actual release-node likes "UI change", or "NONE" is enough?

**Review by feiskyer — APPROVED** [review]
/lgtm
/approve

**Comment by wangyx1992** [comment]
/assign @huang-wei
Could you review the change under pkg/scheduler? The changes are to optimize log captialization.

**Comment by Huang-Wei** [comment]
@wangyx1992 Would you mind fixing all similar nits in the scheduler codebase: https://pastebin.com/0pDC8kJJ? I'm fine with either fixing in this PR, or open a separate PR.

**Comment by wangyx1992** [comment]
@Huang-Wei What about opening a separate PR to deal with similar nits in the scheduler codebase: [https://pastebin.com/0pDC8kJJ](url)? We need to check whether any tests require error strings to match or not.

**Comment by Huang-Wei** [comment]
> @Huang-Wei What about opening a separate PR to deal with similar nits in the scheduler codebase: [https://pastebin.com/0pDC8kJJ](url)? We need to check whether any tests require error strings to match or not.

That sounds good to me.

/approve
on scheduling side.

**Pull request merged**
