### PR TITLE
fixed some bad url

### PR DESCRIPTION
**Pull request by lcfang**
**What this PR does / why we need it**:

fixed some bad url

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @liggitt 
for "api change"

**Comment by jsafrane** [comment]
@lcfang: from verify scripts:
```
staging/src/k8s.io/apiserver/pkg is out of date. Please run hack/update-generated-protobuf.sh
```

**Review by MHBauer — APPROVED** [review]
using the new redirects, cool.

**Pull request merged**
