### PR TITLE
Kubelet reports NotReady when Docker is down.

### PR DESCRIPTION
**Pull request by gmarek**
Solves #6285. I looked at unit and integration tests and it doesn't seem straightforward to test this behavior there. Probably some e2e will be a good place.

### CODE REVIEW

**Comment by gmarek** [comment]
e2e "tests that services.sh passes" fails - I'll need to take a look at it.

**Comment by vmarmol** [comment]
@gmarek can we also add a unit test if possible?

**Comment by gmarek** [comment]
Well, it's an integration between Kubelet and Docker, but sure, I can hack some unit test on Monday (we have a long weekend in Poland).

**Comment by vmarmol** [comment]
If the e2e is green we can merge. After looking at our test framework, it'll be a tough test to write.

**Pull request closed without merging**
