### PR TITLE
[kube-proxy] TestConfigChange: fix goroutine leak

### PR DESCRIPTION
**Pull request by gaurav1086**
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
If the goroutine times out then it will block on writing to the channel errCh without a corresponding reader thus causing a leak. To fix this, make it a buffered channel.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
cc @liggitt @sttts

**Comment by gaurav1086** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
Same comment: https://github.com/kubernetes/kubernetes/pull/93008#issuecomment-684957196

**Comment by gaurav1086** [comment]
@lavalamp  thanks for the pointers. However this an old PR. I will close this one and re-open another one with an alternative solution. Thanks.

**Comment by lavalamp** [comment]
Great, thanks!

**Pull request closed without merging**
