### PR TITLE
IsNotFound should check ErrDefault404 and ErrUnexpectedResponseCode

### PR DESCRIPTION
**Pull request by FengyunPan2**
Related to: #60658 #60976
Refer to:
 https://github.com/gophercloud/gophercloud/pull/103/files#diff-e8ad71423a1527851f282515739eecc2R265

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dims — APPROVED** [review]
i like it.

/lgtm

**Comment by dims** [comment]
/hold

( for comments from @anguslees )

**Review by anguslees — APPROVED** [review]
/approve

**Comment by zetaab** [comment]
this fixes also #61100

**Review by zetaab — APPROVED** [review]

**Pull request merged**
