### PR TITLE
Fix go vet issue inside legacy-cloud-provider

### LINKED ISSUE #109229: go vet lostcancel errors in legacy-cloud-providers files
### What happened?

We found go vet issues of `lostcancel` in #109184. (It seems that go vet checks are not running under `/staging` dir.)

```
staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go:190:5: lostcancel: the cancel function is not used on all paths (possible context leak) (govet)
				ctx, cancel := context.WithCancel(context.Background())
				^
staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go:236:3: lostcancel: this return statement may be reached without using the cancel var defined on line 190 (govet)
		}()
```

### What did you expect to happen?

These issues from go vet are fixed.

### How can we reproduce it (as minimally and precisely as possible)?

Running go vet under `staging/src/k8s.io/legacy-cloud-providers/`

### Anything else we need to know?

_No response_

### Kubernetes version

latest master

/cc @lig

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Akshit42-hue**
#### Which issue(s) this PR fixes:
Fixes #109229

#### What this PR does / why we need it:
while running  go vet under staging/src/k8s.io/legacy-cloud-providers/ will result as following error

```
staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go:190:5: lostcancel: the cancel function is not used on all paths (possible context leak) (govet)
				ctx, cancel := context.WithCancel(context.Background())
				^
staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go:236:3: lostcancel: this return statement may be reached without using the cancel var defined on line 190 (govet)
		}()
```

It's because there is one vm == nil case is missing

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
cc @dims @liggitt @sanposhiho

**Comment by dims** [comment]
please add a better title and also explain in the PR body, what you did and why as well.

thanks,

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
If you still need this PR then please remove the merge commits (see bot comment above), if not, please close the PR

**Comment by Akshit42-hue** [comment]
> If you still need this PR then please rebase, if not, please close the PR

Rebase. Thank You!

**Pull request closed without merging**
