### PR TITLE
Automated cherry pick of #52033

### PR DESCRIPTION
**Pull request by aanm**
Cherry pick of #52033 on release-1.8.

#52033: Removed the IPv6 prefix size limit for cluster-cidr.

```release-note
Removed IPv6 prefix size limit (/64) for cluster-cidr
```

### CODE REVIEW

**Comment by m1093782566** [comment]
@aanm 

I believe #52003 is not related to IPv6 stuff. fyi :)

**Comment by aanm** [comment]
@m1093782566 oh I meant #52033. Thanks!

**Comment by jpbetz** [comment]
@aanm Please add a release note.

**Comment by aanm** [comment]
```release-note
Removed IPv6 prefix size limit (/64) for cluster-cidr
```

**Comment by freehan** [comment]
cc: @abgworrall
/lgtm

**Comment by freehan** [comment]
cc @jpbetz

**Pull request merged**
