### PR TITLE
Avoid '*' in file names

### LINKED ISSUE #46958: Master branch cannot be cloned on Windows due to '*' in file names
```
git clone https://github.com/kubernetes/kubernetes.git
Cloning into 'kubernetes'...
remote: Counting objects: 528551, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 528551 (delta 13), reused 13 (delta 11), pack-reused 528504
Receiving objects: 100% (528551/528551), 427.49 MiB | 402.00 KiB/s, done.
Resolving deltas: 100% (354752/354752), done.
fatal: cannot create directory at 'staging/src/k8s.io/apiserver/pkg/server/options/testdata/localhost__127.0.0.1/test.com_*.test.com_': Invalid argument
warning: Clone succeeded, but checkout failed.
```

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

git clone fails on windows when we have '*' in the file name, so
let us avoid having them.

Note that the getOrCreateTestCertFiles used in the test code will
generate what's needed, So we are not really dropping coverage.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #46958

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts test sounds like one you'd've written.

**Comment by ncdc** [comment]
This was @liggitt. I'd rather change the code that generates the file name to replace `*` with something that's safe on all OSes.

**Comment by ncdc** [comment]
@kubernetes/sig-api-machinery-pr-reviews

**Comment by liggitt** [comment]
Oops. Yeah, fix the unit test that generates this file to make a platform safe filename

**Comment by liggitt** [comment]
superceded by https://github.com/kubernetes/kubernetes/pull/46974

**Pull request closed without merging**
