### PR TITLE
Delete all deployments when tear down cluster alive resources

### PR DESCRIPTION
**Pull request by lparam**
Delete all deployments when tear down cluster alive resources.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29716)

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

@lavalamp I'm out of touch, what was the bot up to? Why did it add `do-not-merge` ? What is `retest-not-required-docs-only` and why did it get added and removed?

**Comment by lavalamp** [comment]
@eparis I don't know. @apelisse do you know?

**Comment by apelisse** [comment]
Yes I know. https://github.com/kubernetes/contrib/issues/1445

**Comment by lparam** [comment]
why need linuxfoundation CLA?

**Comment by wojtek-t** [comment]
@k8s-bot test this, issue: #IGNORE (error queueing build)

**Pull request merged**
