### PR TITLE
Automated cherry pick of #60872: purge all the -v references from e2e.go

### PR DESCRIPTION
**Pull request by krzyzacy**
Cherry pick of #60872 on release-1.9.

#60872: purge all the -v references from e2e.go

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm

/assign @mbohlool 
(PRM for 1.9)

**Comment by krzyzacy** [comment]
/assign @ixdy 
also this one

**Comment by liggitt** [comment]
@mbohlool can we get this merged asap, it unblocks CI for the release branch and we have a regression fix we'd like to get signal on

**Pull request merged**
