### PR TITLE
kubeadm: cleanup ExperimentalControlPlane and ExperimentalUploadCerts

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
kubeadm: cleanup `ExperimentalControlPlane` and `ExperimentalUploadCerts`.

**Which issue(s) this PR fixes**:

Ref #79267
Ref kubernetes/kubeadm#1627

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @neolit123 @dixudx

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/lgtm

Thanks @SataQiu

**Review by neolit123 — COMMENTED** [review]
thanks!
let's get this in; it seems that this covers all "experimental" upgrade and HA related commands/flags.

/approve

**Pull request merged**
