### PR TITLE
Automated cherry pick of #17915 upstream release 1.1

### PR DESCRIPTION
**Pull request by brendandburns**
@justinsb @davidopp 

Cherry pick of #17915 into the release 1.1 branch

### CODE REVIEW

**Comment by davidopp** [comment]
Two questions:
1) Did you already cherrypick #16866? If not, I think you need to do that in order for the feature to work on 1.1.
2) Will this work on GCE? I haven't followed all of the ubernetes PRs, but for example do you need an equivalent of #16735 for GCE?

**Comment by davidopp** [comment]
Also I have no idea what the e2e testing plan is; seems hard to set up a multi-zone test but I haven't really thought about it.

**Comment by davidopp** [comment]
@quinton-hoole

**Comment by justinsb** [comment]
@brendandburns I don't think we want to backport this to 1.1, unless I'm unaware of something.

**Comment by quinton-hoole** [comment]
@brendandburns @justinsb Agreed, this should not be back-ported to 1.1.

@davidopp Yes, I have e2e tests in progress for Ubernetes Lite.  They're all referenced from "Multi-zone e2e tests for Ubernetes Lite" #19414

**Comment by quinton-hoole** [comment]
@brendandburns @davidopp @justinsb closing this as incorrect, as per above comment.

**Pull request closed without merging**
