### PR TITLE
Move generators to staging/src/k8s.io/kube-gen

### PR DESCRIPTION
**Pull request by sttts**
Reason number one for people trying the impossible of vendoring kube: reuse of the generators.

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

I'm definitely a fan

**Comment by maleck13** [comment]
@sttts Am i understanding correctly that this would allow us to vendor the generator pkgs in a similar way to the apiserver and apimachinery. If so I love it. Was wondering recently how to keep the versions in sync and it seemed vendoring k8s was the only way.

**Comment by deads2k** [comment]
> @sttts Am i understanding correctly that this would allow us to vendor the generator pkgs in a similar way to the apiserver and apimachinery. If so I love it. Was wondering recently how to keep the versions in sync and it seemed vendoring k8s was the only way.

Yes, that's the intent here.  There is more work to do to make them truly re-usable, but this would be a good first step.

**Comment by lavalamp** [comment]
Is this ready to go? I am happy to approve it

**Comment by sttts** [comment]
@lavalamp looks like some verify errors are left. Will take care of them tomorrow. Feel free to approve it now :)

**Comment by caesarxuchao** [comment]
One question, do we need to set up the publish robot to sync the repo, or are we going to move it its own repo and vendor it back? I think the latter is preferred, since those generators are relatively stable.

**Comment by deads2k** [comment]
> One question, do we need to set up the publish robot to sync the repo, or are we going to move it its own repo and vendor it back? I think the latter is preferred, since those generators are relatively stable.

I don't feel strongly either way, but I do think we have a significant amount of work to do on them to make them re-useable before we move them out of tree.  I suspect they'll be fast moving until we complete the work of making them flag driven instead of hardcoded and I'd want to be certain that they work with kube during that process.

I could even see an argument that says we should never have a level of the kube generators that doesn't generate working code for us and developing them in an authoritative staging repo ensures that.

**Comment by lavalamp** [comment]
Since this already needs a rebase I went ahead and approved #49055.

I'll approve this ahead of time and then you'll just need an lgtm after you rebase.

/approve

**Comment by sttts** [comment]
Fixed the verify issue: `client-gen -t` also needed an output base to find its test group. Otherwise, nothing serious changed.

**Comment by mbohlool** [comment]
Do you plan to keep this in the `staging/` folder forever? As far as I can tell, we can't vendor this in if we plan to develop it in its own repo ([godep does not allow importing main packages](https://github.com/tools/godep/issues/419)).

**Comment by sttts** [comment]
> if we plan to develop it in its own repo

In the worst case we can manually keep the main package in the vendor tree. It's a godep issue, not a vendor-experiment issue. 

I hope we find a way to move to golang/dep in the midterm future. Is this still a problem there?

**Comment by mbohlool** [comment]
Probably yes. Though I didn't give it a try. Problem is for any dependency system, the best way to build dependency tree is import clauses and you cannot import a main package. That is a go thing as far as I understand. Unless there is a way in golang/dep to specify manual dependencies.

**Pull request merged**
