### PR TITLE
Add support for OpenStack cinder to csi-translation-lib

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

in support of csi-migration proposal here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md

Will help with migration of in-tree Cinder storage plugin to Cinder CSI.

Also see https://github.com/kubernetes/enhancements/issues/625

Change-Id: Ic31e8bf1d0c13d099e2eda515b4ad009cc05ff6b

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
cc @flaper87 @adisky @lingxiankong @jichenjc @j-griffith

**Review by j-griffith — APPROVED** [review]
Thanks @dims

**Review by ddebroy — COMMENTED** [review]
Looks good overall. I have a request to align with some in-flight restructuring of the EBS/PD files. Also, you will need an entry here for Cinder: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/csi-translation-lib/translate.go#L27

**Comment by dims** [comment]
@davidz627 @saad-ali @msau42 this PR for supporting cinder csi in the translation for in-tree to csi is ready. @ddebroy has lgtm-ed it as well. Can you please `/approve`

**Comment by davidz627** [comment]
thanks @dims 
/approve

**Pull request merged**
