### PR TITLE
Don't delete affinity when endpoints are empty

### LINKED ISSUE #25314: kube-proxy userspace: session affinity lost when scale rc to 0 or delete/recreate rc
This makes me cannot do rolling update with service unchanged, and must create RC before Service.

**Reproduce steps**
1. create a Service with session affinity = ClientIP
2. create a RC with size=2
==> then you will find session affinity is not work.

```
$for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
     50 gkt-content-web-test-8kc59
     50 gkt-content-web-test-lgbmf
```

3.delete the service, and recreate again
===> then session affinity works.

```
$for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
    100 gkt-content-web-test-lgbmf

```

4.scale RC down to size=0 and then reset to 2.
===> session affinity is also break

```
# kubectl scale rc gkt-content-web-test --replicas=0 --namespace=gkt-content
replicationcontroller "gkt-content-web-test" scaled

root@paas-185 ~/allen/test/nginx_term
# kubectl scale rc gkt-content-web-test --replicas=2 --namespace=gkt-content
replicationcontroller "gkt-content-web-test" scaled

root@paas-185 ~/allen/test/nginx_term
# for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
     50 gkt-content-web-test-fi4tf
     50 gkt-content-web-test-pdcma
```

**Some output**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

$ kubectl describe service gkt-content-service --namespace=gkt-content -
Name:                   gkt-content-service
Namespace:              gkt-content
Labels:                 name=gkt-content-service
Selector:               name=gkt-content-web
Type:                   ClusterIP
IP:                     10.0.10.239
Port:                   <unset> 40001/TCP
Endpoints:              10.10.51.10:8080,10.10.56.10:8080
Session Affinity:       ClientIP
No events.

$ kubectl get 
get po --namespace=gkt-content
NAME                         READY     STATUS    RESTARTS   AGE
gkt-content-web-test-5j9o7   1/1       Running   0          10m
gkt-content-web-test-y3lab   1/1       Running   0          10m
```

### PR DESCRIPTION
**Pull request by thockin**
This only affects the userspace kube-proxy.

Fixes #25314

### CODE REVIEW

**Comment by freehan** [comment]
Please fix the unit test.

**Comment by roberthbailey** [comment]
@thockin what's the status of this PR? If we want a cherry pick into the 1.2 branch it needs to get merged into master.

**Comment by freehan** [comment]
ping

**Comment by thockin** [comment]
Sorry, this ran into a really hard to track bug and I got busy and now I am
on vacation.  If someone has free time, I think the code is
close-to-correct but I was debugging the test failure

**Comment by jingxu97** [comment]
I examined this test failure and found issues as follows

After adding delete in proxier.OnServiceUpdate() which clean up the loadbalancer's services mapping, the workflow of some unit tests (such as TestTCPProxyUpdateDeleteUpdate) in proxier_test no long works. The test's workflow now becomes as follows

  A.  create a RR loadbalancer and call OnEndPointsUpdate() which will update loadbalancer's services map and the endpoints information.
 B.  create a userspace proxier with loadbalancer and call addServiceOnPort() to add the service. In this step, it tries to use a go routine (proxysocket.ProxyLoop) to connect to the endpoints returned from loadbalancer's services status.
  C.  use proxier.OnServiceUpdate() with empty api service to delete the service. In this step, the modified code will also delete service mapping in loadbalancer
**** Here it creates a race condition, the go routine ProxyLoop tries to get the endpoints returned from loadbalancer;s service mapping, but it is deleted by step c.
  D.  use proxier.OnServiceUpdate() with a new api service to add the service. In this step, it will also update loadbalancer's services to add a new service mapping, 
****HOWEVER, the mapping does not has any endpoints information. So it will fail to connect to an endpoint because it is not available in loadbalancer's service status

The following are the fixes I already tried and it works

1. To solve issue in step c's race condition, we can sleep for a period of time before deleting the service
2. To solve issue in step d, we can call the same proxier.OnServiceUpdate() used in step a before step d, so that endpoints will be available in services.

**Comment by erictune** [comment]
@freehan does this still need a cherrypick-candidate label?  Is it in 1.2.5, or is it asking for a 1.2.6 to be made?  If not let me know and I will remove.

**Comment by freehan** [comment]
notification got buried. I will pick up this one later. 

@erictune This is a bug fix. Let us get it in.

**Pull request closed without merging**
