### PR TITLE
Improvements to mustrunas_test.go

### LINKED ISSUE #41990: pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go could be improved
I'm suggesting to do the following improvements to the [pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go](https://github.com/kubernetes/kubernetes/blob/17375fc59fff39135af63bd1750bb07c36ef873b/pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go) file:

- `TestGenerateAdds`: remove unused `requiredDropCaps` member from the struct
- `TestValidateAdds`: remove unused `requiredDropCaps` member from the struct
- `TestValidateDrops`: remove unused `defaultAddCaps` member from the struct
- `TestValidateAdds`, `TestValidateDrops`: instead of using `shouldPass bool` and checking only whether test fails or not, we could check (also) an error message

This refactoring is simple and may be performed by the new contributors (could someone add label `for-new-contributors`?)

### PR DESCRIPTION
**Pull request by roidelapluie**
* Removed unused members from structs
* Compare error messages

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #41990

**Special notes for your reviewer**:

**Release note**:

NONE

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @php-coder repoened with a new assignee

**Comment by php-coder** [comment]
> reopened with a new assignee

@roidelapluie I'd rather ask to reassign in the original PR.

**Comment by roidelapluie** [comment]
ack

**Pull request closed without merging**
