### PR TITLE
Change v1 API to default RC replicas to 1

### LINKED ISSUE #6700: Default ReplicationController replicas count to 1
Forked from #5366.

@rjnagal

### PR DESCRIPTION
**Pull request by thockin**
Fixes #6700
Part of #7018

### CODE REVIEW

**Comment by thockin** [comment]
@bgrant0607 - chipping away at v1 nits

**Comment by bgrant0607** [comment]
LGTM. Thanks much.
cc @rjnagal

**Comment by rjnagal** [comment]
Thanks @thockin. I was just trying to sent this out over bad conf wifi.

The test failure is real but looks unrelated:

**Comment by rjnagal** [comment]
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontext	0.045s	coverage: 62.5% of statements
--- FAIL: TestNoManualChangesToGenerateConversions (0.54s)
	conversion_generation_test.go:129: please update conversion functions; generated: v1.functions.txt; first diff: 
		expected: func convert_api_AWSElasticBlockStoreVolumeSource_To_v1_AWSElasticBlockStoreVolumeSource(in *api.AWSElasticBlockStoreVolumeSource, out *AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
		
		     got: func convert_v1_AWSElasticBlockStoreVolumeSource_To_api_AWSElasticBlockStoreVolumeSource(in *AWSElasticBlockStoreVolumeSource, out *api.AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
FAIL

**Comment by thockin** [comment]
Sorry, didn't know you were on it.

'make test' passes here.  weird.

**Comment by thockin** [comment]
rebased, let's see if that helps.  It looks like it is complaining that the generated code is in a different order, but it passes on my desktop.

@wojtek-t is the conversion code maybe using a map somewhere?

**Comment by wojtek-t** [comment]
this is strange - the code is supposed to sort the result:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/runtime/conversion_generator.go#L243

**Comment by thockin** [comment]
Failed again:

```
--- FAIL: TestNoManualChangesToGenerateConversions (0.70s)
	conversion_generation_test.go:129: please update conversion functions; generated: v1.functions.txt; first diff: 
		expected: func convert_api_ObjectReference_To_v1_ObjectReference(in *api.ObjectReference, out *ObjectReference, s conversion.Scope) error {
		
		     got: func convert_v1_ObjectReference_To_api_ObjectReference(in *ObjectReference, out *api.ObjectReference, s conversion.Scope) error {
```

I can not repro - it passes locally.

**Comment by wojtek-t** [comment]
@thockin: I think the sorting function doesn't make sense (i.e. it's not deterministic). I will create a PR today to fix it).

**Comment by wojtek-t** [comment]
@thockin #8577 that should fix your problems is out for review

**Comment by dchen1107** [comment]
@thockin you have to rebase now. :-(

**Comment by thockin** [comment]
rebased

**Comment by dchen1107** [comment]
@thockin you have to rebase again. Sorry for this.

**Comment by thockin** [comment]
rebased again

**Comment by dchen1107** [comment]
We had e2e failures again after clean some backlogs for last two days. I am looking into those failures, and will merge this one first.

**Comment by thockin** [comment]
No worries.

**Comment by thockin** [comment]
green and mergable :)

**Comment by rjnagal** [comment]
LGTM.

Oncall will merge when the door opens :)

**Comment by dchen1107** [comment]
Yes, sorry for postponing on this. Merging...

**Pull request merged**
