### PR TITLE
Made the cloudformation template work on a VPC

### LINKED ISSUE #2544: Fix AWS CloudFormation template and add VPC support
I note that the CloudFormation template provided [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws-coreos.md) currently has a note saying that it fails to properly configure minions but will be fixed shortly.

I had modified the template to launch in a VPC, which had worked, but I had networking issues where setup-network-environment failed to come up and I didn't have connectivity to the outside world (no nameserver lookup seemingly - although a plain CoreOS instance was fine in the same subnet).

It would be very useful for production deployments for the example template to bring up Kubernetes in a VPC, which is probably best practice for isolation etc.

I could make a pull request against the fixed cloud formation, but am not sure if it will solve the connectivity issues, so perhaps it would be an idea to fix the current template at the same time as adding VPC support (probably no disadvantage to making it VPC-only for that matter). 

For reference here are the relevant changes needed for a VPC (mostly using security group ids not names), I include the resource type and the config KV pairs:

```
"Type": "AWS::EC2::SecurityGroup",
        "VpcId": "vpc-9f2f27fd",

"Type": "AWS::EC2::SecurityGroupIngress",
        "GroupId": { "Fn::GetAtt" : [ "KubernetesSecurityGroup", "GroupId" ] },

"Type": "AWS::EC2::Instance",
        "SubnetId": "subnet-4cbc4515",        
        "SecurityGroupIds": [{ "Fn::GetAtt": [ "KubernetesSecurityGroup", "GroupId" ] }],

"Type": "AWS::AutoScaling::AutoScalingGroup",
        "AvailabilityZones": ["eu-west-1a"],
        "VPCZoneIdentifier": ["subnet-4cbc4515"],

"Type": "AWS::AutoScaling::LaunchConfiguration",
        "SecurityGroups": [{ "Fn::GetAtt": [ "KubernetesSecurityGroup", "GroupId" ] }],


```

### PR DESCRIPTION
**Pull request by silasdavis**
This fixes #2544. Also I note that @kelseyhightower fixed the cloudformation template but there is a still a note on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws-coreos.md that indicates it is broken.

The template updated in this PR allows you to use a VPC by specifying:
- VPC
- Subnet within that VPC
- Availability Zone of the subnet

We could modify this to create the subnet then it would only need need the VPC ID as a parameter (and we could use the default AZ and use a reference to it in the template). However there may be merits to letting users set up the subnet to their liking without making it part of the launch.

### CODE REVIEW

**Comment by silasdavis** [comment]
This has been approved, I'm getting the CLA signed now

**Comment by silasdavis** [comment]
I've submitted the CLA by email.

**Comment by silasdavis** [comment]
@brendanburns any update on this?

**Comment by brendandburns** [comment]
Closing this as I ported it into HEAD with #3848

**Pull request closed without merging**
