### PR TITLE
remove package version while all external dependencies has been removed

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
/cc @roberthbailey  would you like to spent some time to review it? than you!
remove package version while all external dependencies has been remove

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```
remove package version while all external dependencies has been remove

```

### CODE REVIEW

**Comment by zouyee** [comment]
ping @smarterclayton

**Comment by zouyee** [comment]
ping @dixudx

**Comment by roberthbailey** [comment]
@zouyee - do you want to rebase and keep working on this PR or should we close it?

**Comment by lavalamp** [comment]
Sorry for radio silence, I never saw the notification in my email until just now. :(

**Pull request closed without merging**
