### PR TITLE
godeps: update vmware/govmomi

### PR DESCRIPTION
**Pull request by dougm**
**What this PR does / why we need it**:

Update required to continue work on #64021

- The govmomi tag API changed

- Pulling in the new vapi/simulator package for testing the VCP Zones impl

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by frapposelli — APPROVED** [review]
/lgtm

**Comment by dougm** [comment]
@cblecker could you review the vendor updates?  This is follow on work to PR #66795 that you had reviewed.

**Comment by cblecker** [comment]
Bump of existing dep. Adding new packages of existing dep. No licence changes.
/approve

**Pull request merged**
