### PR TITLE
Drop conformance tag for tests that rely directly on kubelet /logs API

### PR DESCRIPTION
**Pull request by dims**
In [caf0d1d61874a2c8687b7deb773eca30ddaee5b6](https://github.com/kubernetes/community/pull/3979) we documented a policy to
ensure that conformance tests should not rely in existence or use of
kubelet apis directly. So based on that we should drop conformance for
the two tests here that use the "/logs" endpoint directly.

@spiffxp spotted them and logged them https://github.com/kubernetes/kubernetes/issues/81052#issuecomment-518907056 but we forgot to disable the tests so far.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Drop some conformance tests that rely on Kubelet API directly
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Ok, but you'll need to regen the conformance yaml.

**Comment by hh** [comment]
Agree with @johnbelamaric

**Comment by spiffxp** [comment]
/approve
/lgtm
good catch, thanks!

**Pull request merged**
