### PR TITLE
Nominate Abdullah Gharaibeh to scheduler reviewers.

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

I would like to add myself as a reviewer of the scheduler pkg. I am familiar with the code base, reviewing  [over 30 PRs](https://github.com/kubernetes/kubernetes/pulls?page=1&q=is%3Apr+reviewed-by%3Aahg-g&utf8=%E2%9C%93).

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @bsalamat @k82cn 
/sig scheduling

### CODE REVIEW

**Review by bsalamat — APPROVED** [review]
/lgtm
/approve

Thanks, @ahg-g for your help. Looking forward to seeing more contributions from you.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
