### PR TITLE
build-image: cross: update make and dockerfile to use args

### PR DESCRIPTION
**Pull request by javier-b-perez**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update makefile and dockerfile to support args in build-image/cross

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@javier-b-perez What's the reason for this? I am concerned about providing avenues to make images that aren't reproducible.

**Comment by BenTheElder** [comment]
@cblecker since this is a `docker build` the steps should be recorded in the image's history metadata anyhow. IIRC this build is not fully reproducible.

**Comment by cblecker** [comment]
But why is this *needed*? I'm okay with the Dockerfile changes, but I don't like the makefile changes that use the local environment to override the build args.

**Comment by javier-b-perez** [comment]
one use case is just to test a new cross build with a different go version, with the args it is easier to change the go version and the destination of the image.
Another use case is an internal one, we use a different go version to build k8s, therefore we need to overwrite these files in the git tree.

For the non-reproducible builds, we should limit who can create (ideally only robots) and automate the build of the official image, which I will work on later, once the registry promoter is ready to be used.

**Comment by cblecker** [comment]
We're already rewriting these files in https://github.com/kubernetes/kubernetes/pull/75058 for cross-arch. I'd rather not make this change.

**Comment by cblecker** [comment]
Okay, so if you're wanting to swap out the golang base image, then #75058 should work for you, if you override the build args locally with a custom build command. We don't need upstream makefile changes for that.

**Comment by javier-b-perez** [comment]
> Okay, so if you're wanting to swap out the golang base image, then #75058 should work for you, if you override the build args locally with a custom build command. We don't need upstream makefile changes for that.

agree, as long as I can use a docker build-arg for the base golang image and the makefile define the value for this, it should work. I see that change is doing more than just the arg, I also see it the other way around, that change could benefit from these PR.

**Comment by cblecker** [comment]
Okay, great. This use case is covered by https://github.com/kubernetes/kubernetes/pull/75058 then, so I'm going to close this PR out. Thanks!

/close

**Pull request closed without merging**
