### PR TITLE
Update cadvisor godeps to v0.28.2

### LINKED ISSUE #55628: Cut and vendor cAdvisor v0.28.1 for the 1.9 release.
This issue tracks progress for the cAdvisor release corresponding to the kubernetes 1.9 release.
Cutting the cAdvisor release is currently targeted for 11/17.
This cAdvisor release should include per-container GPU stats, on-demand metrics, and containerd stats, among other things.

cc @dchen1107 @Random-Liu @derekwaynecarr @abhi @mindprince 
/sig node
/kind feature

### LINKED ISSUE #55909: [Failing Test] [k8s.io] Summary API when querying /stats/summary should report resource usage through the stats api
Summary API node e2e test has started failing after the most recent cAdvisor update: https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet&include-filter-by-regex=Summary
The PR which updated cadvisor Godeps: https://github.com/kubernetes/kubernetes/pull/55188

This issue is most likely not related to GPU metrics, but another change that was included in the cadvisor update.

cc @kubernetes/sig-node-test-failures

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
cAdvisor cuts a release for each kubernetes release.  This cAdvisor release corresponds to cadvisor 1.9.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55909 
Fixes #55628

**Special notes for your reviewer**:
This is also a prerequisite for fixing https://github.com/kubernetes/kubernetes/issues/51745.
This fixes the flaky node_e2e, which is submit queue blocking

**Release note**:
```release-note
Add containerd monitoring support
```

### CODE REVIEW

**Comment by dashpole** [comment]
cc @mindprince @abhi @Random-Liu 
@kubernetes/sig-node-pr-reviews

**Review by rohitagarwal003 — APPROVED** [review]
/lgtm

**Comment by derekwaynecarr** [comment]
@dashpole -- looks like error in verify, but agree this is needed in milestone.

**Comment by dashpole** [comment]
oh darn, I cant use the fake clock

**Comment by Random-Liu** [comment]
@derekwaynecarr Thanks for approve. I don't know who could approve milestones until discussed with dashpole and yuju. :P Sorry about that.

**Comment by dashpole** [comment]
I cut a new cadvisor release which relies on k8s.io/utils/clock (which I added) instead of k8s.io/apimachinery/clock.  I will transition other k8s repositories to use this location after the 1.9 release

**Comment by dashpole** [comment]
@derekwaynecarr this should be all good to go, and needs owners approval for godep changes

**Comment by dashpole** [comment]
cross failure is unrelated.  Has to do with KubeProxy Configuration

**Comment by derekwaynecarr** [comment]
/approve 

you will need @thockin

/assign @thockin

**Comment by dashpole** [comment]
This passed the summary API test 26 times in a row, which confirms that this fixes the current flaky sq blocking errors.

**Comment by dashpole** [comment]
also fixes https://github.com/kubernetes/heapster/issues/690

**Comment by dashpole** [comment]
and also a prerequisite for https://github.com/kubernetes/kubernetes/pull/55810

**Comment by dashpole** [comment]
fixes https://github.com/kubernetes/kubernetes/issues/56122

**Comment by dashpole** [comment]
adding lgtm based on https://github.com/kubernetes/kubernetes/pull/56109#pullrequestreview-77985317 after rebase removed it.

**Pull request merged**
