### PR TITLE
Update cadvisor godeps to v0.30.1 to revert cadvisor#1916

### LINKED ISSUE #64933: Summary API test is flaky
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet

It become too flaky recently since 6/5/2018.

@kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by dashpole**
/sig node
/priority critical-urgent
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64933

**Release note**:

```release-note
Kubernetes depends on v0.30.1 of cAdvisor
```

### CODE REVIEW

**Comment by dashpole** [comment]
/assign @dchen1107 
for lgtm, milestone, and milestone approval

**Comment by thockin** [comment]
Godep changes LGTM
/lgtm
/approve

**Comment by jberkus** [comment]
Wait, if we're updating to 0.30.1, don't we need a release note for that?

**Pull request merged**
