### PR TITLE
Update fluentd-gcp such that exported logs are associated with kubernetes

### LINKED ISSUE #13033: Make it possible to disable collection of kubelet/docker logs
When I run Kubernetes cluster on GKE, it generates a lot of system logs coming from docker and kubelet. Even if my cluster runs just a few pods, I can see dozens or hundreds of log entries per second available in Google Cloud Logging in docker and kubelet logs. This makes the actual logs from my application get lost among them, if I do not set appropriate filter. Also, I am afraid that collecting massive amounts of logs imposes unnecessary workload on fluentd pod in my cluster.

It would be good if I could just disable collection of kubelet/docker logs (and potentially other Kubernetes system logs) assuming that I do not want to have these logs exported.

### PR DESCRIPTION
**Pull request by a-robinson**
This includes a few changes:
- Update fluentd-gcp to map /var/log to /var/log rather than to/varlog, as done by @jimmidyson for the fluentd-es container recently
- Stop installing the unused catch-all configs when we install google-fluentd in our Dockerfile
- Most importantly, update to the latest google-fluentd version, which includes support for Kubernetes metadata from https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/30, https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/31, and https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/6.
- Separate out logs from containers and logs from node components to different output plugins, so that we don't associate things like kubelet and docker logs with kubernetes specifically, but as the normal node logs that they are. This was made possible by https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/34 and fixes #13033 in a way that will keep @vishh happy.

This gets us most of the way to #8001 on the GCP side, with the final step of using the filter_kubernetes_metadata plugin being blocked on the daemon controller being ready so that fluentd can authenticate to the apiserver.

I've verified the new plugin manually, but can't actually build the Docker image until @mr-salty cuts the new google-fluentd release on Monday, so this will fail e2e until I can do so on Monday.

### CODE REVIEW

**Comment by a-robinson** [comment]
PTAL. The new google-fluentd build was made available today, so I've built the image and spun up a new cluster with these changes to verify it. This is now in a functioning, mergeable state.

**Comment by roberthbailey** [comment]
Can you squash your commits?

**Comment by a-robinson** [comment]
They're logically separate changes that I stuck together for less reviewing overhead. I can combine the first two if you'd like since they're both effectively cleanups, but the third is a major functionality change which belongs on its own.

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
