### PR TITLE
📝 output log when server shutdown is failed

### PR DESCRIPTION
**Pull request by kei01234kei**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Log the server shutdown failure to inform users about it.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kei01234kei** [comment]
I'm worried that there might be many errors because some server like controller manger is set shutdownTimout zero.
https://github.com/kubernetes/kubernetes/blob/bf70d289fb3b7deb9b121bbe10e278f12840cfcb/cmd/kube-controller-manager/app/controllermanager.go#L218

**Comment by kei01234kei** [comment]
@deads2k @sttts 
Could u review this pr??

**Comment by sttts** [comment]
/ok-to-test

> I'm worried that there might be many errors because some servers, like the controller manager, have their shutdownTimeout set to zero.

Isn't that only called once and with that only logged once?

/assign @tkashem

**Comment by kei01234kei** [comment]
@sttts 
Thank you for reviewing my code.

**Pull request merged**
