### PR TITLE
unlink test packages from kube-apiserver

### PR DESCRIPTION
**Pull request by mikedanese**
ref #16673

cc @lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
Why isn't `pkg/storage/etcd/etcd_test_util.go` renamed to `pkg/storage/etcd/testing/util.go` - we need to get in the habit of making test-only code go in a wholly distinct package.  Times like this I deaperately miss blaze.

**Comment by timothysc** [comment]
How is the linkage not incremental in this case?  The deps are *only* in the test files?

**Comment by lavalamp** [comment]
Does everything work if we switch the file name to etcd_util_test.go?

**Comment by lavalamp** [comment]
I'm really more curious about why the flag testing didn't catch this.

**Comment by timothysc** [comment]
For my own edification on golang linking : https://groups.google.com/forum/#!topic/golang-nuts/1X7ytOpyEt0 seems pretty awful. 

fwiw brute force checking  `nm * | grep -i test`  detects fairly easily.

**Comment by mikedanese** [comment]
> Does everything work if we switch the file name to etcd_util_test.go?

@timothysc is the etcd_test_util meant to be depended on by other packages to use in testing. If so, the rename approach won't work.

**Comment by lavalamp** [comment]
@timothysc Just importing the testing package registers flags, so they are always "used". That discussion would apply if we were talking about whether the linker retained testing functions.

**Comment by timothysc** [comment]
@mikedanese if you subpackage under pkg/storage/etcd/testing/util.go and only import in relevant tests, how would that not work?

**Comment by mikedanese** [comment]
I'm asking with regards to lavalamps suggestion "Does everything work if we switch the file name to etcd_util_test.go?". Subpackaging would work

**Comment by timothysc** [comment]
Given there would be a circular dependency if we were split into a /testing/utils.go , 

I'm lgtm here... 
@wojtek-t ^?

**Comment by timothysc** [comment]
I've made a PR for the other method we had mentioned https://github.com/kubernetes/kubernetes/pull/16781

**Pull request closed without merging**
