### PR TITLE
Fixing the ingress annotation key in federated ingress controller

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixing a few issues found during debugging https://github.com/kubernetes/kubernetes/issues/36074.

cc @kubernetes/sig-cluster-federation @madhusudancs @bprashanth

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37271)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @saad-ali as FYI for 1.5.
This is a bug fix.

**Comment by madhusudancs** [comment]
Code LGTM! But want to wait for @saad-ali's approval. Please feel free to apply the label once the PR is approved.

**Comment by saad-ali** [comment]
> cc @saad-ali as FYI for 1.5.

Ack. Thanks

**Comment by nikhiljindal** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
