### PR TITLE
Use framework.ExpectNoError() for e2e/lifecycle

### PR DESCRIPTION
**Pull request by atoato88**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

The e2e test framework has ExpectNoError() for readable test code.
This replaces Expect(err).NotTo(HaveOccurred()) with it for e2e/lifecycle.

Ref: #77103

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
/lgtm

**Comment by draveness** [comment]
There are remaining cases which the original cmd does not cover, please run the cmd below to fix it:

```go
ag -l "gomega\.Expect\(err\)\.NotTo\(gomega.HaveOccurred\(\), " test/e2e/lifecycle/*.go  | xargs sed -i '' -e 's/gomega\.Expect(err)\.NotTo(gomega.HaveOccurred(), /framework\.ExpectNoError(err, /g'
```

```
ag "gomega\.Expect\(err\)\.NotTo\(gomega.HaveOccurred\(\), " test/e2e/lifecycle/*.go
test/e2e/lifecycle/addon_update.go
230:		gomega.Expect(err).NotTo(gomega.HaveOccurred(), "Failed to get the master SSH client.")
278:			gomega.Expect(err).NotTo(gomega.HaveOccurred(), "Failed to write file %q at remote path %q with ssh client %+v", p.fileName, temporaryRemotePath, sshClient)
287:		gomega.Expect(err).NotTo(gomega.HaveOccurred(), "Failed to remove remote dir %q with ssh client %+v", destinationDirPrefix, sshClient)
389:	gomega.Expect(err).NotTo(gomega.HaveOccurred(), "Failed to execute %q with ssh client %+v", cmd, client)
``

**Comment by oomichi** [comment]
@draveness Nice catch, yeah these lines contain error message, so we could not detect them with the previous way.

/lgtm cancel

**Comment by atoato88** [comment]
@draveness Thank you for comment! :smiley: 
I've fixed remaining items which commented in previous and also L303 in `addon_update.go`.
It's a irregular case.

**Pull request merged**
