### PR TITLE
Generated new documentation.md for kubernetes metrics reference

### PR DESCRIPTION
**Pull request by Gauravpadam**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
This PR is associated with https://github.com/kubernetes/kubernetes/pull/120350, Which aims to change the generator codes for the kubernetes metrics reference

#### Special notes for your reviewer:
A separate PR for the updated documentation.md

### CODE REVIEW

**Comment by logicalhan** [comment]
squash and i'll happily approve :)

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by Gauravpadam** [comment]
@logicalhan Can you please have a look?

**Review by logicalhan — COMMENTED** [review]
/lgtm

**Comment by Gauravpadam** [comment]
@logicalhan Can we retest the failing one? I'll probably require an ok-to-test to do so

**Comment by Gauravpadam** [comment]
@pacoxu Thanks, And @logicalhan Thanks for being so patient with the PR, Really appreciate that 😃

**Pull request merged**
