### PR TITLE
cri-api: add mappings for volumes

### PR DESCRIPTION
**Pull request by giuseppe**
add the definitions for the ID mappings to use at runtime for the volume mount.  This is supported only on Linux where idmapped mounts are used to perform the runtime mapping.

The new fields are mapped directly to the field in the OCI runtime specs:

https://github.com/opencontainers/runtime-spec/blob/main/config.md#posix-platform-mounts

The CRI runtime will pass the mappings to the OCI runtime as-is.

Related to KEP-127.

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
it adds the definitions for the ID mappings to use at runtime for the volume mount.  This is supported only on Linux where idmapped mounts are used to perform the runtime mapping.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by rata — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by giuseppe** [comment]
is it worth keeping this PR open now that we've opened https://github.com/kubernetes/kubernetes/pull/116377 ?

Should I just close it and move all the discussion there?

**Comment by SergeyKanzhelev** [comment]
makes sense. Let's merge alongside the implementation.

/close

**Pull request closed without merging**
