### PR TITLE
Update docker dependency to v1.9.1

### LINKED ISSUE #16110: Validate docker v1.9.0-rc1 release
.

### PR DESCRIPTION
**Pull request by vishh**
Fixes #16110

### CODE REVIEW

**Comment by vishh** [comment]
cc @zmerlynn

**Comment by vishh** [comment]
@dchen1107: I have updated this PR to upgrade docker version on GCE deployments as well. PTAL

**Comment by dchen1107** [comment]
I am holding this pr because many people reports huge performance regression with docker 1.9.1 release: 

https://github.com/docker/docker/issues/17720

**Comment by timothysc** [comment]
@dchen1107 could you share the details?  Also was the performance issues on 1.9.0 or 1.9.1?

**Comment by vishh** [comment]
@timothysc: https://github.com/docker/docker/issues/17720

**Comment by timothysc** [comment]
@vishh I'm looking for impact on kubernetes, also that issue number says 1.9.0

**Comment by vishh** [comment]
The impact will be delayed container status updates. If you read through
the issue, you will see that it was never fixed in any of the patch
releases.

**Comment by dchen1107** [comment]
@timothysc Both docker 1.9.0 and 1.9.1 are observed the notable performance downgrade. I received the reports the performance downgrade with 1.9.X release from @countspongebob, coreos, mesos etc. I also ran my stress tests against the docker 1.9.0 earlier by keeping create and delete containers, and occasionally (but not very rare) docker ps hang for more than 30s. I didn't run my tests against 1.9.1 though since back then we expected docker release 1.9.2 with the fixes; otherwise docker 1.10.x should be out soon. 

We should reconsider the decision for 1.2 release now since there is no 1.9.2 release anymore and docker 1.10.x won't be out soon.

**Comment by timothysc** [comment]
It would be super-d-duper if we had some report that could be generated.  A regression / conformance analysis.

**Comment by vishh** [comment]
cc @Random-Liu

**Comment by Random-Liu** [comment]
@vishh I'll post the benchmark result these days. Thanks :)

**Comment by dchen1107** [comment]
I am closing this pr. @Random-Liu's benchmark result on 1.8.3 vs 1.9.2 out, we will decide on what is the next step.

**Pull request closed without merging**
