### PR TITLE
Add WindowsContainerResources to UpdateContainerResourcesRequest

### PR DESCRIPTION
**Pull request by katiewasnothere**
Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds WindowsContainerResources and an Annotations field on the UpdateContainerResourcesRequest. This will allow for updating windows containers as well as allow for experimentation of various resources through the annotations field. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Add WindowsContainerResources and Annotations to CRI-API UpdateContainerResourcesRequest
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

Edit: removed API change kind

### CODE REVIEW

**Comment by katiewasnothere** [comment]
@Random-Liu PTAL when you can

**Comment by katiewasnothere** [comment]
@Kevpar @dcantah @ambarve @anmaxvl fyi

**Comment by kevpar** [comment]
@marosset FYI

**Comment by marosset** [comment]
@katiewasnothere can you run hack/update-all.sh and include those changes in the PR?

I would expect some changes to the some generated protobuf files in this PR in addition to the current changes.

**Comment by marosset** [comment]
@feiskyer can you take a look at these CRI changes?

**Comment by kevpar** [comment]
The test failure says this, btw: `Generated container runtime api is out of date. Please run hack/update-generated-runtime.sh`. Presumably running `hack/update-all.sh` as @marosset suggested would also work.

**Review by feiskyer — COMMENTED** [review]
Could you run hack/update-generated-runtime.sh and commit the changes together?

**Comment by katiewasnothere** [comment]
@feiskyer @marosset @kevpar Done :)

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by marosset** [comment]
/milestone v1.20
/assign @dchen1107 @derekwaynecarr 
Hopefully we can this into 1.20 since these changes are minor and additive

**Pull request merged**
