### PR TITLE
Automated cherry pick of #116995: kubelet: Ensure pods that have not started track a

### PR DESCRIPTION
**Pull request by smarterclayton**
Cherry pick of #116995 on release-1.27.

#116995: kubelet: Ensure pods that have not started track a

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Opening this for backport because we can't eliminate the possibility that this causes a severe issue, we just have no evidence that it does *yet*.

@bobbypage

**Comment by bobbypage** [comment]
+1, I agree we should backport this to v1.27. At a minimum it will fix the unexpected metrics and possibly other issues we don't know about yet. 

/lgtm

**Comment by bobbypage** [comment]
/cc @kubernetes/release-managers 

for cherrypick approvals

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
