### PR TITLE
Revert "Merge pull request #47353 from apelisse/http-cache"

### PR DESCRIPTION
**Pull request by liggitt**
Some issues were discovered with the caching merged in #47353:
* uses a disk-based cache that is not safe between processes (does not use atomic fs operations)
* writes get/list responses to disk that should not be cached (like `kubectl get secrets`)
* is vulnerable to partially written cache responses being used as responses to future requests
* breaks uses of the client transport that make use of websockets
* defaults to enabling the cache for any client builder using RecommendedConfigOverrideFlags or DefaultClientConfig which affects more components than just kubectl

This reverts commit fc89743dca6b563063b74728c3b28100cf674d9d, reversing changes made to 29ab38e898988c36e2de34f77fa33be556eb21bd.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @apelisse @mbohlool @pwittrock from original PR

**Comment by apelisse** [comment]
Thanks @liggitt for working on that, and sorry for breaking your use-case. All good points,

Can you clarify what the difference is between:
> uses a disk-based cache that is not safe between processes (does not use atomic fs operations)

and

> is vulnerable to partially written cache responses being used as responses to future requests

Or maybe the question is, would a fix for the first point also fix that second point? If not, can you clarify what you meant for the latter.

**Comment by liggitt** [comment]
> uses a disk-based cache that is not safe between processes (does not use atomic fs operations)

this means that two successful writes by separate processes would stomp on each other (process 1 starts writing, process 2 starts writing, they both write to the file in an interleaved way)

> is vulnerable to partially written cache responses being used as responses to future requests

this means that if a single process fails halfway through writing the file, the half-written file is left in place. a future invocation of the cache will scan existing files to determine what is in cache, and the half-written file gets put in the index of available cached responses.

> would a fix for the first point also fix that second point?

possibly, depending on the fix... if the disk cache changed to always write to a tmp file and only on success do a move to a file that is used to serve future cached responses, I think that would likely address both issues.

**Comment by apelisse** [comment]
> if the disk cache changed to always write to a tmp file and only on success do a move to a file that is used to serve future cached responses, I think that would likely address both issues.

I think we're on the same page then, that's exactly what I had in mind. Thanks

**Comment by smarterclayton** [comment]
/lgtm

Given that this impacts concurrent kubectl clients in unpredictable ways, and also caches secret data on disk.

**Comment by liggitt** [comment]
rebased to fix godep conflict

**Comment by liggitt** [comment]
fixed conflict in staging godep

**Comment by smarterclayton** [comment]
/retest

Neither look related

**Comment by liggitt** [comment]
unit flaked on https://github.com/kubernetes/kubernetes/issues/50022
/retest

**Pull request merged**
