### PR TITLE
Cleanup and add unit test for ShouldContainerBeRestarted

### PR DESCRIPTION
**Pull request by Random-Liu**
This is part of #21224.

Since `Waiting` state needs more thoughts, this one could be merged first. :)

@yujuhong

### CODE REVIEW

**Comment by Random-Liu** [comment]
ok to test

**Comment by Random-Liu** [comment]
There is no failure in unit test. @k8s-bot test this please.

**Comment by Random-Liu** [comment]
Apply lgtm again because I didn't change anything.

**Comment by Random-Liu** [comment]
Change https://github.com/Random-Liu/kubernetes/commit/33280abf426bfd90ccaa5375cff437ffd1fabf05#diff-e281c21e93f01ecc8cf12e4ff535b3e5R57 from `status.State != ContainerStateExited` to `status.State == ContainerStateRunning`.

If container is created but not successfully started, it is in "Created" state, and `GetPodStatus()` will set it to `ContainerStateUnknown`. In the original implementation container in "unknown" state won't be restarted. That is not the expected behavior.

Apply lgtm again, because I only changed one line to fix the unit test.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #21739.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #21995

**Pull request merged**
