### PR TITLE
hack/local-up-cluster.sh: ability to configure auth webhooks

### PR DESCRIPTION
**Pull request by reith**
(this is #82220 which accidentally was closed)

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
I'm using local-up-cluster script to setup a Kubernetes cluster and then test my components based on Kubernetes. One of these components is authentication/authorization web-hook and I found no other way to pass necessary args to api-server.

### CODE REVIEW

**Comment by xichengliudui** [comment]
thanks @reith 
/lgtm
/approve

**Comment by reith** [comment]
I believe failed test is allowed to fail. Am I correct? Or did i miss something?

**Pull request merged**
