### PR TITLE
Enable NFS and GlusterFS test in cluster e2e test

### PR DESCRIPTION
**Pull request by jingxu97**
Enable NFS and GlusterFS in cluster e2e test

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36618)

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this
/lgtm

**Comment by fejta** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Comment by fejta** [comment]
/lgtm cancel

Please fix tests

**Comment by jingxu97** [comment]
Close this PR in favor of #36848

**Pull request closed without merging**
