### PR TITLE
Convert e2e localpv stress tests to integration test .

### LINKED ISSUE #100854: Run scheduler stress tests with pods sharing the same PV
#### What would you like to be added:

https://github.com/kubernetes/kubernetes/pull/74716 added e2e test `Pods sharing a single local PV [Serial]` that creates 50 Pods to test for races in storage topology scheduling. It should be an integration test instead, we don't need to abuse a real kubelet with 50 pods.

/sig storage
/sig scheduling
/assign @cofyc

### PR DESCRIPTION
**Pull request by mikechengwei**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #100854 .

### CODE REVIEW

**Comment by jsafrane** [comment]
I briefly looked at the test and it seems to me it only creates some PVs, PVCs and Pods and then deletes them. It does not **check** anything. Should it run a scheduler and make sure that all pods are scheduled as expected and no race condition was reproduced?

**Comment by mikechengwei** [comment]
> I briefly looked at the test and it seems to me it only creates some PVs, PVCs and Pods and then deletes them. It does not **check** anything. Should it run a scheduler and make sure that all pods are scheduled as expected and no race condition was reproduced?

Okay, let me optimize it.

**Pull request closed without merging**
