### PR TITLE
Update kubedns and nodelocaldns to v1.23.0

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update kubedns and nodelocaldns to [dns v1.23.0](https://github.com/kubernetes/dns/releases/tag/1.23.0)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Update kubedns and nodelocaldns to v1.23.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
@MrHohn for review please

**Comment by bzsuni** [comment]
or review please @kl52752

**Comment by aojea** [comment]
@bzsuni @kl52752  we have to promote the image before updating the manifests

> [gcr.io/k8s-staging-dns/k8s-dns-node-cache:1.23.0](http://gcr.io/k8s-staging-dns/k8s-dns-node-cache:1.23.0) exists, someone should run kpromo to get it promoted

ci is failing now https://testgrid.k8s.io/sig-network-gce#gci-gce-coredns-nodecache since this merged, I'm going to revert until the image is promoted

**Comment by liangyuanpeng** [comment]
Let me try to open a PR to promote images of dns.

**Comment by kl52752** [comment]
thanks @aojea for handling this issue.

**Pull request merged**
