### PR TITLE
Clean up for Memory and Disk predicates

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**Special notes for your reviewer**:

A small clean up for predicates, we were never returning any error in the code.

**Release note**:

```release-note
`NONE`
```

### CODE REVIEW

**Comment by jayunit100** [comment]
- @ First glance this makes sense, but @wojtek-t probably knows why these were originally capable of returning `error`.  
- to make review process easier we might want to consider rolling this in with other cleanups if there are a few around the corner?

**Comment by jayunit100** [comment]
@k82cn ok to test

**Comment by jayunit100** [comment]
@k8s-bot ok to test

**Comment by k82cn** [comment]
@ravisantoshgudimetla , @jayunit100 , I think we can not do this which will break the signature of `FitPredicate`; check build error for more detail.

```
type FitPredicate func(pod *v1.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (bool, []PredicateFailureReason, error)
```

**Comment by ravisantoshgudimetla** [comment]
@k82cn - Thanks for correcting me, I will close this PR now. I was under the impression that CheckNodeDiskPressurePredicate and CheckMemoryPressurePredicate are moved to taints. It seems the PR is still not merged.

**Comment by jayunit100** [comment]
yup that was what i was thinking...

**Pull request closed without merging**
