### PR TITLE
server/config: assing system:apiserver user to system:authenticated group

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
This doesn't change the level of access.  This does correct the user.Info to ensure that things like audit log rules apply as users would expect.  This is a good idea to backport.

/lgtm
/approve

**Comment by jeremyrickard** [comment]
@p0lyn0mial  does this only apply to 1.31?

**Comment by xmudrii** [comment]
@p0lyn0mial Can you please create cherry-picks for other affected versions and link those cherry-picks here? Thanks!

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial Can you please create cherry-picks for other affected versions and link those cherry-picks here? Thanks!

@xmudrii sure, how far back do we want to go? All the way to 1.29?

**Comment by xmudrii** [comment]
@p0lyn0mial Approved, thanks a lot!

**Pull request merged**
