### PR TITLE
Add approver and reviewers for 1.26

### PR DESCRIPTION
**Pull request by ramrodo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adds me as an approver and adds Shadows as reviewers for 1.26

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by leonardpahlke** [comment]
Should we remove 1.21 and 1.22 RN leads since these versions are not getting updates anymore

cc @palnabarun

**Comment by palnabarun** [comment]
Yup. 1.21 for sure. Last patch release of 1.22 is going on. Will the reviewers be needed for this?

**Comment by ramrodo** [comment]
I think it is not necessary to have too many reviewers from past releases.
Maybe we can keep the reviewer of the current cycle and 3 more (of the last 3 releases) only if they are needed for some context in the future patches.

**Comment by leonardpahlke** [comment]
Thank you :)

/lgtm

**Review by leonardpahlke — APPROVED** [review]
/lgtm

**Comment by cici37** [comment]
/approve
Thank you

**Pull request merged**
