### PR TITLE
Don't merge the junit report

### PR DESCRIPTION
**Pull request by chendave**
>   --keep-separate-reports
    If set, Ginkgo does not merge per-suite reports (e.g. -json-report) into one
    monolithic report for the entire testrun.  The reports will remain in their
    respective package directories or in -output-dir if set.

Based on the help txt for the flag.

This only address part of the issue, we still need to trim the report as well, but if the final size of the each xml is relative small, there should be no need to trim the report.

Signed-off-by: Dave Chen <dave.chen@arm.com>

/kind bug

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/111510

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
This might not work, let's just have a try, the flag here doesn't respect the number parallel but the number of test suites.

/hold

**Comment by dims** [comment]
@chendave do you need to set the `output-dir` as well? https://onsi.github.io/ginkgo/MIGRATING_TO_V2#improved-reporting-infrastructure

**Comment by chendave** [comment]
@dims  I tried, `output-dir` doesn't help. 

the size of file generated by `pull-kubernetes-e2e-kind` seems fine.
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/111599/pull-kubernetes-e2e-kind/1554066353067921408/artifacts/

**Comment by BenTheElder** [comment]
I only see one junit https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/111599/pull-kubernetes-e2e-kind/1554066353067921408/artifacts/

**Comment by chendave** [comment]
> I only see one junit

yes, this only works for multiple test suites.

**Comment by chendave** [comment]
Even though this doesn't split the report for one suite, but it will split the report when the multiple suites are run together. 

Do we still need to enable this flag? @aojea

**Comment by aojea** [comment]
I suggest to keep things as they are for now, I'm pretty happy with current status ...

**Comment by chendave** [comment]
per the feedback from @aojea 

/close

**Pull request closed without merging**
