### PR TITLE
Add GetEnvOr() feature to utils Package

### PR DESCRIPTION
**Pull request by nagarjung**
This Patch is a fix for the issue number https://github.com/kubernetes/kubernetes/issues/17727

Moved kubernetes/pkg/volume/flocker/util.go Into general utilities env library (kubernetes/pkg/util/env.go), and add corner cases to the tests (support for parsing strings,ints and floats).

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM

@k8s-bot ok to test

@nagarjung Thanks for the PR!

**Comment by nagarjung** [comment]
Some one please re test

**Comment by nagarjung** [comment]
@k8s-bot 
@brendandburns : Integrations tests are failing, Can you please re run the tests?

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
