### PR TITLE
Indicate endpoint subsets are an optional field

### LINKED ISSUE #59403: [cluster/update-storage-objects.sh] ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I tried to use `cluster/update-storage-objects.sh` and got the following errors:

```
$ ./cluster/update-storage-objects.sh
error: error validating "/tmp/k8s-kube-system-endpoints-kube-controller-manager.json": error validating data: ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "/tmp/k8s-kube-system-endpoints-kube-controller-manager.json": error validating data: ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "/tmp/k8s-kube-system-endpoints-kube-controller-manager.json": error validating data: ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "/tmp/k8s-kube-system-endpoints-kube-controller-manager.json": error validating data: ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "/tmp/k8s-kube-system-endpoints-kube-controller-manager.json": error validating data: ValidationError(Endpoints): missing required field "subsets" in io.k8s.api.core.v1.Endpoints; if you choose to ignore these errors, turn validation off with --validate=false
Error: failed to update endpoints/kube-controller-manager in kube-system namespace after 5 tries
```

These errors occur in k8s > 1.7.

**What you expected to happen**:

I expect that the execution of `cluster/update-storage-objects.sh` succeed.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ minikube start --kubernetes-version v1.8.0
$ git clone --depth 1 -b v1.8.7 https://github.com/kubernetes/kubernetes.git && cd kubernetes
$ make kubectl
$ ./cluster/update-storage-objects.sh
```

**Anything else we need to know?**:

```
$  _output/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-02-06T07:39:44Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl get ep -n kube-system kube-controller-manager -o json
{
    "apiVersion": "v1",
    "kind": "Endpoints",
    "metadata": {
        "annotations": {
            "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"minikube\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2018-02-06T07:14:10Z\",\"renewTime\":\"2018-02-06T07:26:27Z\",\"leaderTransitions\":0}"
        },
        "creationTimestamp": "2018-02-06T07:14:10Z",
        "name": "kube-controller-manager",
        "namespace": "kube-system",
        "resourceVersion": "998",
        "selfLink": "/api/v1/namespaces/kube-system/endpoints/kube-controller-manager",
        "uid": "53f8beeb-0b0d-11e8-871b-0800272240a0"
    },
    "subsets": null
}
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #59403 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/api-reviewers

**Comment by lavalamp** [comment]
What happens if new clients omit this field in requests to old apiservers?

**Comment by liggitt** [comment]
> What happens if new clients omit this field in requests to old apiservers?

 Nothing. The server accept requests without this field today, and persists a null value for that field

**Pull request merged**
