### PR TITLE
promote aggregation API to v1

### PR DESCRIPTION
**Pull request by deads2k**
Finishing https://github.com/kubernetes/features/issues/263 as discussed in apimachinery

The API has been available since 1.6 and beta since 1.7.  Openshift has been using it for about a year and service catalog (@pmorie) and metrics server (@piosz @DirectXMan12) have both been using too.  The feature and the API have both been stable over that time.

@kubernetes/sig-api-machinery-api-reviews @kubernetes/api-approvers 

/assign lavalamp
/assign smarterclayton

```release-note
Promoting the apiregistration.k8s.io (aggregation) to GA
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
No one has any last minute naming changes they want?  I haven't heard any myself.

**Comment by deads2k** [comment]
> No one has any last minute naming changes they want? I haven't heard any myself.

Nor have I.

**Comment by MHBauer** [comment]
I don't care what it's called as long as it works. 

For general use and adoption there needs to be some explicit document describing support and how to set it up. Along with whatever code paths being needed are exposed. We had @DirectXMan12 set it up for us in service-catalog, so I can't comment on whether that does or does not exist outside of our repo.

We set it up once and haven't changed it. Seems to work well enough. Seems stable.

**Comment by DirectXMan12** [comment]
agreed on the documentation front.  Otherwise, huge :+1: from me.

**Comment by smarterclayton** [comment]
Week has passed, discussed in sig-api-machinery, no concrete reason to not go given, reviewers given time...

/approve

**Pull request merged**
