### PR TITLE
Validate pod node selector admission plugin config

### LINKED ISSUE #35506: podNodeSelectorPluginConfig need validation when start
**Kubernetes version** (use `kubectl version`):
 v1.5.0-alpha.1.857+c81816751387a2-dirty

**How to reproduce it** (as minimally and precisely as possible):

```
1. Start kube-apiserver with invalid value for PodNodeSelector admission controller
--admission-control=PodNodeSelector, --admission-control-config-file=admission-control-config-file.cfg

# cat ../admission-control-config-file.cfg
podNodeSelectorPluginConfig:
 clusterDefaultNodeSelector: region#=xyz%
 ns3: os=@#^&*,region=west^&*

2. Create a pod in this env
[root@ip-172-18-6-200 podnodeselector]# kc create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/pod/hello-pod.yaml
Error from server: error when creating "https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/pod/hello-pod.yaml": invalid label key "region#": name part must match the regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9] (e.g. 'MyName' or 'my.name' or '123-abc')

```

**Expected results**
1. Should start failed PodNodeSelector with invalid podNodeSelectorPluginConfig value.

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by aveshagarwal**
**What this PR does / why we need it**:
This pr validates pod node selector admission plugin config.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fix #35506 

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1415554

**Special notes for your reviewer**:

**Release note**:

```release-note
```

@kubernetes/rh-cluster-infra @derekwaynecarr

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36395)

### CODE REVIEW

**Comment by aveshagarwal** [comment]
Another thing this PR does is that it improves the performance of this plugin as previously there was conversion and validation of cluster level selector and whitelists from label string to label maps on each admission request, but now it happens only once at the plugin initialization.

**Comment by aveshagarwal** [comment]
yes please keep it open.

**Comment by aveshagarwal** [comment]
please keep it open.

**Comment by derekwaynecarr** [comment]
@aveshagarwal -- we should probably update this in 1.7 milestone and use versioned config...

**Comment by aveshagarwal** [comment]
@derekwaynecarr sounds good.

**Comment by aveshagarwal** [comment]
please keep open.

**Comment by derekwaynecarr** [comment]
just poke when you move to versioned config, and i will look then.

**Comment by marun** [comment]
Given that this PR has been inactive for some time, I'm assuming it's not intended to land in v1.7.

**Pull request closed without merging**
