### PR TITLE
Revert "rev ES and allow anonymous access to kibana"

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit aba965b559899091cad0392d8274500719ad2bba.

Anonymous permissions granted by default are not expected in the addons dir.

#### What type of PR is this?

/kind bug

```release-note
NONE
```

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Sorry for the inconvenience approving: https://github.com/kubernetes/kubernetes/pull/100169

Could we please just remove the rbac part and keep the image update and so on?

**Comment by liggitt** [comment]
> Could we please just remove the rbac part and keep the image update and so on?

that's fine, can you open a PR dropping the RBAC changes?

/hold

**Comment by monotek** [comment]
Sure, will do :)

**Comment by monotek** [comment]
Done in: https://github.com/kubernetes/kubernetes/pull/102018

**Comment by liggitt** [comment]
/close

in favor of https://github.com/kubernetes/kubernetes/pull/102018

**Pull request closed without merging**
