### PR TITLE
remove deprecated initresource admission plugin

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

xref https://github.com/kubernetes/kubernetes/pull/55375#issuecomment-360329586

**Special notes for your reviewer**:
/assign @piosz @deads2k 

**Release note**:

```release-note
remove deprecated initresource admission plugin
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
The plugin is deprecated.

/ok-to-test
/approve
/lgtm

**Comment by derekwaynecarr** [comment]
this will need a rebase, thank you for the PR.

**Comment by wackxu** [comment]
@derekwaynecarr Rebased， PTAL

**Comment by wackxu** [comment]
@deads2k @piosz PTAL

**Comment by deads2k** [comment]
/assign @derekwaynecarr 

I don't remember what this does.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/58784)

**Comment by derekwaynecarr** [comment]
sorry for delay.

/approve
/lgtm

**Comment by derekwaynecarr** [comment]
/kind cleanup
/priority important-soon

its deprecated, so better to remove it than have it stay around any longer.

**Comment by deads2k** [comment]
approval is getting stuck on a generated bazel file.  Changes are in the admission package that derek and I are owners for.  manually labeling.

**Pull request merged**
