### PR TITLE
Switch serviceaccounts controller to generated shared informers

### PR DESCRIPTION
**Pull request by ncdc**
Originally part of #40097 

cc @deads2k @sttts @liggitt @smarterclayton @gmarek @wojtek-t @timothysc @kubernetes/sig-scalability-pr-reviews

### CODE REVIEW

**Comment by luxas** [comment]
@ncdc Is this a dependency for https://github.com/kubernetes/kubernetes/pull/41281? cc @ericchiang

**Comment by ncdc** [comment]
@luxas not that I know of? I'm methodically working my way through most of the code that isn't using shared informers and converting them to use the generated shared informers.

**Comment by ncdc** [comment]
@k8s-bot unit test this

**Pull request merged**
