### PR TITLE
Revert "Bump DynamicKubeConfig metric deprecation to 1.23"

### LINKED ISSUE #104041: Revert bump of DynamicKubeletConfig metrics deprecation to 1.23
This shipped in 1.22 as deprecated in 1.22. As a hacky fix to unbreak tests on 1.23 dev, I bumped the deprecation policy one release: https://github.com/kubernetes/kubernetes/pull/103980#issuecomment-888510879

We will need to revert that before 1.23 ships and figure out a better solution.

/kind cleanup
/milestone v1.23
/sig node

### PR DESCRIPTION
**Pull request by ehashman**
Reverts kubernetes/kubernetes#103980

/sig node
/priority important-soon

We removed the tests so this should be fine now. This needs to be pushed back before we release 1.23.

Fixes https://github.com/kubernetes/kubernetes/issues/104041

```release-note
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
/milestone v1.23
/kind cleanup

This is a (very minor) release blocker, we did not intend to release with this flipped back.

/test pull-kubernetes-node-kubelet-serial

**Review by SergeyKanzhelev — APPROVED** [review]
thank you!
/lgtm

**Comment by ehashman** [comment]
flake https://github.com/kubernetes/kubernetes/issues/106204

/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by ehashman** [comment]
Serial lane passed except for the failing GPU test :ok_hand:  this should be good to go.

/assign @mrunalp

**Review by mrunalp — APPROVED** [review]

**Comment by ehashman** [comment]
(looks like network timeouts)

**Pull request merged**
