### PR TITLE
Cleanup service.Strategy class

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #12207

### CODE REVIEW

**Comment by feihujiang** [comment]
I'm sad, this is duplicate  of #16152, I just reopened that two hours ago.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@feihujiang - sorry I wasn't aware of your change

**Comment by lavalamp** [comment]
@feihujiang got the tests, you got the predicate... let's go with @feihujiang's.

**Comment by wojtek-t** [comment]
@lavalamp The tests were actually moved from one place to the other, so effectively it's the same.

**Pull request closed without merging**
