### PR TITLE
WIP: remove hard-coded resource order in namespace ctrl

### PR DESCRIPTION
**Pull request by sttts**
Based on https://github.com/kubernetes/kubernetes/pull/36909.

**WARNING**: the approach taken does not work as we don't see resources which support `deletecollection` and hence the `ownerGraph` training does not take place.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37685)

**Comment by sttts** [comment]
@deads2k @derekwaynecarr ^^. **Note**: the approach taken does not work, see PR description. How should we approach this?

**Comment by deads2k** [comment]
I would take a different approach.  I'd say that nearly everything be done via GC. Basically all well-behaved resources use it and it is the first namespace finalizer to be processed.  Then this comes along to do final cleanup of "naughty" resources.  That way the order you need works itself out in GC and you still don't lose anything.

Because of the way GC is built, there's no logical "this owns these" information available at a resource level, but anyone who would give you the metadata should already be using GC.  I'm ok hard-coding an order for "known naughty" controllers that don't already use GC, but I don't want a second way to expose the metadata to make this possible.

**Comment by derekwaynecarr** [comment]
I think we can now safely remove the delete pods last, but I don't think we need topological sorting of deletion order in this controller.  The delete pods last need is resolved since namespace controller and garbage collector are no longer clashing with each other (they were confused at the time that was added).

**Comment by sttts** [comment]
The resource deletion order ("pod last") is removed as part of https://github.com/kubernetes/kubernetes/pull/36909.

**Pull request closed without merging**
