### PR TITLE
[1.16] Update CNI to v0.8.6

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency release-eng
/sig network release

**What this PR does / why we need it**:

Update CNI to v0.8.6

cc: @kubernetes/release-engineering @kubernetes/sig-network-misc 
/assign @BenTheElder @yujuhong @tallclair
ref: https://github.com/kubernetes/release/pull/1309

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Update CNI to v0.8.6
- build: Use debian-hyperkube-base@v1.0.0 image
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/hold
Requesting details on why this is being picked back

**Comment by justaugustus** [comment]
Image has been promoted: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-k8sio-cip/1265499696156119040
/hold cancel

**Pull request merged**
