### PR TITLE
[code-generator] align generated builder comments

### PR DESCRIPTION
**Pull request by QuentinBisson**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This  PR aligns the generated comments generated by the applyconfiguration generator as it should either use `can be build` or `can be built` everywhere and not use both.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Do you know how I could regenerate the existing comments  to fix the typo?

**Comment by QuentinBisson** [comment]
@deads2k  maybe you can help? Is there a makefile I should run?

**Comment by QuentinBisson** [comment]
@sttts I know this is only a cosmetic change but I would like to either have this merged or closed. Do you think you could help? I'm not sure what kind of makefile I should run to fix the comments

**Comment by QuentinBisson** [comment]
Is there any value in keeping this PR opened as I did not receive any help/traction?

**Comment by sttts** [comment]
Change seems good to me. But it needs fixes for green tests, i.e. running `hack/update-codegen.sh` and committing the changes.

**Comment by QuentinBisson** [comment]
Thanks I'll run this asap :)

**Pull request closed without merging**
