### PR TITLE
cleanup: remove useless function

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The function is useless

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
we don't use it, but community projects seems to? i see a number of hits
- https://cs.github.com/?scopeName=All+repos&scope=&q=NewSubjectAccessEvaluator
- https://github.com/search?q=NewSubjectAccessEvaluator&type=code

**Comment by Octopusjust** [comment]
> we don't use it, but community projects seems to? i see a number of hits
> 
> * https://cs.github.com/?scopeName=All+repos&scope=&q=NewSubjectAccessEvaluator
> * https://github.com/search?q=NewSubjectAccessEvaluator&type=code

I have not carefully thought out，thanks

**Pull request closed without merging**
