### PR TITLE
Switch k8s on GCE to use GCI by default

### PR DESCRIPTION
**Pull request by vishh**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33353)

### CODE REVIEW

**Comment by vishh** [comment]
master branch (v1.5) was never meant to run container-vm by default. We are ready for wider testing of GCI and running it as the default OS. There are some known issues and they are being tracked and resolved. 
Workaround is to use container-vm

**Comment by vishh** [comment]
@k8s-bot gci test this

**Comment by vishh** [comment]
@k8s-bot unit test this

**Comment by mtaufen** [comment]
LGTM

**Comment by vishh** [comment]
P2 since this is critical for stabilizing GCI and this change was supposed to not even be necessary in the first place.

**Pull request merged**
