### PR TITLE
Revert "Fix the race between configuring cbr0 and restarting static p…

### PR DESCRIPTION
**Pull request by piosz**
Reverts GoogleCloudPlatform/kubernetes#10211

This PR broke network on containers. No container can get out to the internet.

### CODE REVIEW

**Comment by piosz** [comment]
cc @thockin @roberthbailey @dchen1107 @brendandburns

**Comment by wojtek-t** [comment]
I will wait for all the tests to be green and merge it.

**Comment by piosz** [comment]
Also #10211 significantly increased cluster creation time (at least for me) using ```./hack/dev-build-and-up.sh```.

**Comment by dchen1107** [comment]
Thanks for fixing this. Unfortunately our e2e tests passed, and didn't catch the problem at the first place. Sorry about this.

**Pull request merged**
