### PR TITLE
update comment for neweventcorrelator method

### PR DESCRIPTION
**Pull request by likakuli**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

**Comment by likakuli** [comment]
@neolit123 can you approve this pr, thanks

**Comment by neolit123** [comment]
@likakuli hi, this PR can be approved by api-machinery maintainers.
@caesarxuchao should be able to do that.

**Pull request closed without merging**
