### PR TITLE
typo

### PR DESCRIPTION
**Pull request by julienchastang**
typo "allotted" not "alloted"

image

### CODE REVIEW

**Comment by neolit123** [comment]
@julienchastang you'd have to sign the CLA as the bot instructed, before this PR is accepted.

/kind cleanup
/priority backlog

**Comment by julienchastang** [comment]
@neolit123 Signing the CLA is too onerous for various reasons. If possible, can you close this PR and fix the typo? I don't need commit attribution. Thanks.

**Comment by neolit123** [comment]
> Signing the CLA is too onerous for various reasons

you can log an issue in this repository if you'd like and mark it as `/help` for somebody to pick up.
thanks
/close

**Pull request closed without merging**
