### PR TITLE
Decouple k8s.io/kubernetes/pkg/scheduler/framework/plugins from internal k8s.io/kubernetes packages.

### LINKED ISSUE #89930: Clean up scheduler dependencies on k8s.io/kubernetes packages
To make it easier for out-of-tree developers to import the scheduler framework, among other scheduling helpers and constants, we should explore areas that we can remove dependencies on `k8s.io/kubernetes`. Places that could be easily removed are, for example, using internal APIs where not required or importing unrelated packages for simple helpers which can be trivially implemented. This will clean up the dependency tree for importing scheduler code externally. 

This is related to: [Proposal to migrate scheduler code to staging](https://docs.google.com/document/d/1WO-ixERpqkCSEXEq30YtEH_z_G-BoLKeCbkRJcKq3xA/edit). While the proposal includes all scheduler code, we are only focusing on scheduler framework code. However identifying anywhere in the scheduler code that these dependencies can be cleaned up will be helpful as well.

This will probably be an ongoing cleanup effort, and breaking the work into smaller PRs may actually help with review and preventing code breaking in the process.
/kind cleanup
/sig scheduling

PRs opened so far:
* https://github.com/kubernetes/kubernetes/pull/90105 `pkg/apis/core` @xiaoanyunfei 
  * moving the default scheduler name and references to the external api
* ~~https://github.com/kubernetes/kubernetes/pull/90006~~ `pkg/api/core/v1/helper` @gavinfish (part 1)
  * copies `GetPersistentVolumeClaimClass`, which is used in several other areas around pkg/volume
  * replaced by https://github.com/kubernetes/kubernetes/pull/98433
* https://github.com/kubernetes/kubernetes/issues/91782 Overview issue of `pkg/api/core/v1/helper` @ingvagabund 
* ~~https://github.com/kubernetes/kubernetes/pull/90041 `pkg/api/testing` @tanjunchen~~
* https://github.com/kubernetes/kubernetes/pull/90039 ~~`pkg/scheduler/util`~~ `pkg/api/v1/pod` @yuzhiquan 🔹
  *  move `GetPodPriority` to scheduler utils
  * ~~https://github.com/kubernetes/kubernetes/pull/90703 `pkg/api/v1/pod` @yiyang5055 🔹~~
* https://github.com/kubernetes/kubernetes/pull/90046 `pkg/controller/volume/scheduling/metrics` @tanjunchen 
  * copies metrics registration and definitions around volume binding
* https://github.com/kubernetes/kubernetes/pull/90111 `pkg/features` @gavinfish 🔹
  * held on https://github.com/kubernetes/kubernetes/issues/90136 discussion on feature gating for staging components
* ~~https://github.com/kubernetes/kubernetes/pull/90000 `pkg/master/ports` @SataQiu~~
* ~~https://github.com/kubernetes/kubernetes/pull/90040~~ `pkg/util/node` @tanjunchen 🔹
  * copies Node util `GetZoneKey`, which should be moved to external and imported by both
  * replaced by https://github.com/kubernetes/kubernetes/pull/97818
* https://github.com/kubernetes/kubernetes/pull/90008 `pkg/util/parsers` @gavinfish 
  * removes `DefaultImageTag` (":latest") const only used by us and kubelet
* https://github.com/kubernetes/kubernetes/pull/90007 `pkg/volume/util` @gavinfish 
  * still have dependency on VolumeBinder

🔹 = Adds code to `pkg/scheduler/util`, which should be externalized

### PR DESCRIPTION
**Pull request by ikeeip**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This patch make plugins independently importable by external projects. Also it makes a huge step to decouple scheduling framework to reduce dependency tree for custom schedulers.

#### Which issue(s) this PR fixes:

Fixes #89930

#### Special notes for your reviewer:

Some helper functions and their tests from `k8s.io/kubernetes/pkg/apis/core/v1/helper` package moved to `k8s.io/api/core/v1/helper` package:
- IsExtendedResourceName
- IsPrefixedNativeResource
- IsNativeResource
- IsAttachableVolumeResourceName
- TopologySelectorRequirementsAsSelector
- MatchTopologySelectorTerms

Helpers and their tests from `k8s.io/kubernetes/pkg/controller/volume/persistentvolume` package moved to `k8s.io/component-helpers/storage/volume` package:
- IsDelayBindingMode
- GetBindVolumeToClaim
- IsVolumeBoundToClaim
- FindMatchingVolume
- CheckVolumeModeMismatches
- CheckAccessModes
- GetVolumeNodeAffinity

Package `k8s.io/kubernetes/pkg/controller/volume/persistentvolume/testing` moved to `k8s.io/component-helpers/storage/volume/testing`

Also some helpers and their tests from `k8s.io/kubernetes/pkg/volume/util` package moved to `k8s.io/component-helpers/storage/volume` package:
- CheckNodeAffinity
- whole file pkg/volume/util/attach_limit.go
- whole file pkg/volume/util/attach_limit_test.go

All dependencies of VolumeBinding plugin from `k8s.io/kubernetes/pkg/controller/volume/scheduling` package moved to `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding` package:
- whole file pkg/controller/volume/scheduling/scheduler_assume_cache.go
- whole file pkg/controller/volume/scheduling/scheduler_assume_cache_test.go
- whole file pkg/controller/volume/scheduling/scheduler_binder.go
- whole file pkg/controller/volume/scheduling/scheduler_binder_fake.go
- whole file pkg/controller/volume/scheduling/scheduler_binder_test.go

Package `k8s.io/kubernetes/pkg/controller/volume/scheduling/metrics` moved to `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/metrics` because it only used in VolumeBinding plugin and (e2e) tests.

All plugins was decoupled from `k8s.io/kubernetes/pkg/features`. Features in plugin tests configured directly for each specific test now.

Constructors for InTreeRegistry and LegacyRegistry plugin now accept feature.Features argument, allowing them to be configured with features directly from `pkg/scheduler/scheduler.go`. All feature flags initialization logic was moved to `pkg/scheduler/features.go`.

Several things left to do (I hope it will be done in other PR's):
- [ ] Merge `k8s.io/kubernetes/pkg/controller/volume/scheduling/OWNERS` into `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/OWNERS`

- [ ] Decouple last dependency from `k8s.io/kubernetes` internal packages in scheduling framework:
    `$ grep -rni `k8s.io/kubernetes` pkg/scheduler/framework/* | grep -v `k8s.io/kubernetes/pkg/scheduler`
    pkg/scheduler/framework/types.go:35:    `k8s.io/kubernetes/pkg/features``

- [ ] Resolve TODO's:
       - Use constants from `k8s.io/component-helpers/storage/volume` package directly and cleanup `k8s.io/kubernetes/pkg/controller/volume/persistentvolume` package from proxy constants
       - Use helpers from `k8s.io/api/core/v1/helper` package directly and cleanup `k8s.io/kubernetespkg/apis/core/v1/helper` package from proxy functions

- [ ] Refactor test helpers in `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding` package:
    - Similar functions at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go`:
       ```golang
        func makePV(name string, className string) *v1.PersistentVolume
       ```
      and at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/scheduler_assume_cache_test.go`: 
       ```golang
       func makePVForAssumeCacheTest(name, version, storageClass string) *v1.PersistentVolume
       ```
    - Similar functions at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go`:
       ```golang
        func makeNode(name string) *v1.Node
       ```
      and at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/scheduler_binder_test.go`: 
       ```golang
       func makeNodeWithLabels(name string, labels map[string]string) *v1.Node
       ```
    - Similar functions at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go`:
       ```golang
        func makePod(name string, pvcNames []string) *v1.Pod
       ```
      and at `k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/scheduler_binder_test.go`: 
       ```golang
       func makePodWithPVC(pvcs []*v1.PersistentVolumeClaim) *v1.Pod
       ```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
this is way to big of a PR. Can you split it in a few independent ones?

Note that similar changes have already faced resistance #101489. I think we should start by getting that PR merged first.

**Comment by ikeeip** [comment]
> this is way to big of a PR. Can you split it in a few independent ones?

Yes, if it will be more comfortable for review I can do this.

> Note that similar changes have already faced resistance #101489. I think we should start by getting that PR merged first.

Oh, I missed it. I took a quick look. Hmm, it seems #101489 was created before a staging repo `k8s.io/component-helpers` created. And I don't understand the idea of using a "container" object to keep only helper functions. And yes, I had the same questions that @ingvagabund asked in https://github.com/kubernetes/kubernetes/issues/91782#issuecomment-642237825. 

FYI, in this PR I kept proxy functions at `pkg/apis/core/v1/helper` package to provide time to migrate related projects to direct usage of `k8s.io/kubernetespkg/apis/core/v1/helper` package if needed. However, I can postpone changes related to `pkg/apis/core/v1/helper`.

**Comment by alculquicondor** [comment]
/close

Please tag us in the partial PRs. However, it would be for 1.23 due to code freeze in effect.

**Pull request closed without merging**
