### PR TITLE
Refactor functions in editoptions.go to use less arguments

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubernetes/kubernetes/issues/45521
/assign @mengqiy 
will rebase pr https://github.com/kubernetes/kubernetes/pull/42256 after this get merged

### CODE REVIEW

**Comment by mengqiy** [comment]
/lgtm
Thanks!

**Comment by mengqiy** [comment]
@pwittrock @fabianofranz Can someone approve this? Minor refactor change.

**Comment by pwittrock** [comment]
/approve

Thanks this is great!

**Pull request merged**
