### PR TITLE
Update Event CRUD tests to use events.k8s.io/v1

### PR DESCRIPTION
**Pull request by chelseychen**
**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

This PR update CRUD tests for new Events API verbs to use events/v1.

**Which issue(s) this PR fixes**:

Ref https://github.com/kubernetes/enhancements/issues/383

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: <https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/383-new-event-api-ga-graduation>
```

### CODE REVIEW

**Comment by chelseychen** [comment]
/assign @wojtek-t @liggitt 
This PR contains two commits from #91645. Once that's merge, I will sync this PR. Right now, the third commit is the new one that needs review. Thanks!

**Comment by wojtek-t** [comment]
/lgtm

@chelseychen - Once this one merges we should open one promoting those tests to conformance.

**Comment by wojtek-t** [comment]
/lgtm
/approve

@chelseychen - Please prepare a PR promoting the test to conformance also.

**Comment by chelseychen** [comment]
@wojtek-t Sorry I made a mistake commit to this PR which caused LGTM label being removed. Could you add the label again? Thanks!

**Pull request merged**
