### PR TITLE
device manager: do not clean admitted pods from the state

### LINKED ISSUE #128443: [Failing Test] [sig-node] [NodeFeature:DevicePlugin] [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)
### Which jobs are flaking?

[pull-kubernetes-node-kubelet-containerd-flaky](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-flaky)

### Which tests are flaking?

E2eNode Suite: [It] [sig-node] Device Plugin [NodeFeature:DevicePlugin] [Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration) [Flaky] 

### Since when has it been flaking?

I've noticed it only once today (Oct 30 2024), but I can see similar failures in other jobs, e.g. https://github.com/kubernetes/kubernetes/issues/128114

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-node-kubelet-containerd-flaky/1851562955540271104

### Reason for failure (if possible)

From the first look the failure could happen because of the bug in the device plugin registration process that prevents it from re-registering after Kubelet reboot. It doesn't happen consistently though.

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind failing-test
/kind regression

#### What this PR does / why we need it:

Reverting part of the https://github.com/kubernetes/kubernetes/pull/127506

The initial fix is part of the #103979. It's reverted by https://github.com/kubernetes/kubernetes/pull/127506/commits/212c4c485172ebda99cd639969f1cc1c32ba6ba7, which resulted in #128443.

See more details in https://github.com/kubernetes/kubernetes/pull/120661, https://github.com/kubernetes/kubernetes/pull/127506 and https://github.com/kubernetes/kubernetes/pull/104577

#### Which issue(s) this PR fixes:

Fixes #128443

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
Pending further investigation, I'd rather rethink the failing test from scratch rather than apply this revert for this code.

**Comment by ffromani** [comment]
> Pending further investigation, I'd rather rethink the failing test from scratch rather than apply this revert for this code.

Back in time, https://github.com/kubernetes/kubernetes/pull/103979 was a quick fix for a issue actually in the pod worker/pod lifecycle code which was later fixed. The device plugin test followed the current behavior, not the desired correct behavior which is not the one after 103979.
Lately, we refactored the pod lifecycle handling code, as pointed out in https://github.com/kubernetes/kubernetes/pull/120661. This means that 103979 is nowaday even more questionable and I'm strongly convinced it's obsolete.

Now: there could be cases on which something like 103979 is still relevant, so we need some degree of extra fix. Those corner cases may very well exist.
But I'm not really happy to revert _just and only_ to keep the device plugin test. I'd rather rethink the test (which I should have time for really soon).

All that said, kudos to @bart0sh for the extensive investigation here.

**Comment by ffromani** [comment]
> [EDIT] Almost forgot: #127506 includes 120661 to make metrics test pass :) so we will have another, albeit less evident, breakage if we revcert it.

...which now passes? worth a deeper look (from yours truly)

**Comment by bart0sh** [comment]
> But I'm not really happy to revert just and only to keep the device plugin test. I'd rather rethink the test (which I should have time for really soon).

Do you think that device assignments shouldn't survive node reboot? I don't know if there such a requirement, but it looks reasonable to me. That's what the  `[NodeFeature:DevicePlugin] [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)` e2e test case tries to ensure, as far as I understand.

**Comment by ffromani** [comment]
> > But I'm not really happy to revert just and only to keep the device plugin test. I'd rather rethink the test (which I should have time for really soon).
> 
> Do you think that device assignments shouldn't survive node reboot? I don't know if there such a requirement, but it looks reasonable to me. That's what the `[NodeFeature:DevicePlugin] [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)` e2e test case tries to ensure, as far as I understand.

The test is worth to be kept, but it has to be rewritten.

The root cause for the test failure is
1. the pod doesn't go running (correct, it races with device plugin re-registration after the reboot)
2. the pod is no longer implicitely retrying admission (because  https://github.com/kubernetes/kubernetes/pull/126343 - correct, but the test predates this change)
3. the pod is not managed by a controller, so is not being retried
4. because of the change reverted on https://github.com/kubernetes/kubernetes/pull/128995/commits/b22a5f9b0e3e55d8379115d189068126cdf5faad#diff-623f1164bd7d648ee0421742187c76b5071b44315aee695f29edc0203b6c762dR556 the container device assignment WAS (correctly) removed, hence the assignment is no longer reported by podresources API, which is what the test used to check the assignment survived reboot

So: my takeaway is
1. the test should be kept, but *running* pods should have their assignment survive the node reboot. This is fair to do and what user expects
2. the _current_ test code is puzzling at best: one can legitmately wonder why the test ensures the pod got admission failure and yet kept its assignment? Does this mean the device is busy forever (no, is not, but this is not obvious to learn) see: https://github.com/kubernetes/kubernetes/blob/v1.32.0-rc.0/test/e2e_node/device_plugin_test.go#L976

**Comment by bart0sh** [comment]
@ffromani Thank you for the detailed explanations! That makes perfect sense to me.

> the test should be kept, but running pods should have their assignment survive the node reboot.

Totally agree. However, https://github.com/kubernetes/kubernetes/pull/129010 changes the test case, so it doesn't check if running application pod survives node reboot. Do we need another test for that?

**Comment by likakuli** [comment]
It's somewhat like two negatives make a positive.

**Comment by ffromani** [comment]
> @ffromani Thank you for the detailed explanations! That makes perfect sense to me.
> 
> > the test should be kept, but running pods should have their assignment survive the node reboot.
> 
> Totally agree. However, #129010 changes the test case, so it doesn't check if running application pod survives node reboot. Do we need another test for that?

Good point. While working on 129010 I realized we can't guarantee this with the current kubelet code. The commit message is so long because tries to elaborate why.

**Comment by swatisehgal** [comment]
Thanks @ffromani and @bart0sh for your effort on this.

I tend to agree with @ffromani here. It makes sense to fix the test rather than reverting device plugin specific code and maintaining `pendingAdmissionPod` to keep track of pods being admitted. We know from https://github.com/kubernetes/kubernetes/issues/107074 that maintaining `pendingAdmissionPod` comes with its fair share of issues as it is never set to nil and continues to hold the last pod that went through admission even if it is deleted.

I think its best to ensure consistent semantics across resource managers when it comes to how they record pods in admission stage.

**Comment by bart0sh** [comment]
@ffromani @swatisehgal 
> > Totally agree. However, #129010 changes the test case, so it doesn't check if running application pod survives node reboot. Do we need another test for that?
> 
> Good point. While working on 129010 I realized we can't guarantee this with the current kubelet code. The commit message is so long because tries to elaborate why.

Just to summarise my thoughts on this. Basically we have 2 ways to proceed from here
- Decide that we can't/don't want to support recovering device assignments after node reboot and stop testing this use case. If so, we should close this PR and accept  https://github.com/kubernetes/kubernetes/pull/129010. This seems to be a preferable way.
- Decide that we shoud upport recovering device assignments after node reboot. If so, we should either support this PR, implement the support differently and either modify the test case or come up with the new one to test this use case correctly.

WDYT?

**Comment by ffromani** [comment]
> @ffromani @swatisehgal
> 
> > > Totally agree. However, #129010 changes the test case, so it doesn't check if running application pod survives node reboot. Do we need another test for that?
> > 
> > 
> > Good point. While working on 129010 I realized we can't guarantee this with the current kubelet code. The commit message is so long because tries to elaborate why.
> 
> Just to summarise my thoughts on this. Basically we have 2 ways to proceed from here
> 
>     * Decide that we can't/don't want to support recovering device assignments after node reboot and stop testing this use case. If so, we should close this PR and accept  [node: e2e: fix device plugin reboot test #129010](https://github.com/kubernetes/kubernetes/pull/129010). This seems to be a preferable way.
> 
>     * Decide that we shoud upport recovering device assignments after node reboot. If so, we should either support this PR, implement the support differently and either modify the test case or come up with the new one to test this use case correctly.
> 
> 
> WDYT?

The summarization seems accurate. Thing is, is the effort to implement option 2 is like 100x the effort to implement option 1 (which pretty much boils down to "merge 129010"). In addition, option 2 is definitely KEP material.

**Comment by bart0sh** [comment]
closed

**Comment by swatisehgal** [comment]
> * Decide that we shoud upport recovering device assignments after node reboot. If so, we should either support this PR, implement the support differently and either modify the test case or come up with the new one to test this use case correctly.

Just want to add my thoughts on this. We **do** support recovery of device assignment after node reboot. That's the reason we introduced https://github.com/kubernetes/kubernetes/pull/116376. The main goal of that PR was to ensure that this recovery happens correctly and in the case where device plugin has got the chance to re-register itself to kubelet before the application pod requesting the device comes up.  If the ordering is not correct (i.e. application pod comes before device plugin pod) then pod failing at admission is the right path. Admitting such a pod when its device requirement cannot be fulfilled leads to issues as described in https://github.com/kubernetes/kubernetes/issues/109595. I don't understand why we need additional changes and a new KEP. Am I missing something here?

Now in the context of this particular test failure, we were seeing devices in spite of admission failure because of the reason explained in https://github.com/kubernetes/kubernetes/pull/129010 (podresource API still captured resources of terminal pods and presence of `pendingAdmissionPod` which incorrectly reported devices allocated to failed pod). Ideally this should have been caught when the test was being contributed and therefore it makes sense to rectify the test.

**Comment by bart0sh** [comment]
> recovery happens correctly and in the case where device plugin has got the chance to re-register itself to kubelet before the application pod requesting the device comes up.

This is unlikely to happen in reality, which means (at least for me) that we don't support device assignments recovery after node reboot. Continuous failures of this test case show that application pod usually starts before the device plugin pod, at least in node_e2e setup.

>  If the ordering is not correct (i.e. application pod comes before device plugin pod) then pod failing at admission is the right path.

This is correct for new pods. However, we're talking about recovery of the running pods that were admitted and running before the node reboot. We shouldn't re-admit those or admission process should be different to support recovery.

**Pull request closed without merging**
