### PR TITLE
Remove the assumption of pod cidr of /24 in the gce window node start…

### PR DESCRIPTION
**Pull request by lzang**
… up script.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Current windows start up script assumes the pod cidr is /24, which is not true when flexible pod cidr is enabled: https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr
The patch extracts the gateways from the actual pod cidr configured.

**Which issue(s) this PR fixes**:
Windows node cannot come up when pod cidr is not /24.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by pjh** [comment]
/lgtm thanks!

Are there any e2e tests that cover the situation where a node's pod CIDR is not a /24 ?

**Comment by pjh** [comment]
priority/important-soon

**Comment by lzang** [comment]
@mtaufen @yujuhong Could you please review this PR? Thanks!

**Comment by yliaog** [comment]
looks good, is there a e2e test case for non /24 cidr?

/lgtm

**Comment by pjh** [comment]
/approve

Do I have this power for this directory?

**Comment by lzang** [comment]
This patch just removes the hard-coding in the script. e2e test for non /24 cidr will be added later.

**Pull request merged**
