### PR TITLE
Test gce disks with mock

### PR DESCRIPTION
**Pull request by hantaowang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds unit testing for AttachDisk, DetachDisk, DisksAreAttached, and BulkDisksAreAttached in the legacy-cloud-providers staging repo.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
This PR is quite large but its mainly all tests. If you want me to break it up into 1 PR for each function to test (which I currently have as separate commits), I can.

This PR depends on https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/21 being merged and then the dependency being updated. Therefore, for now:
/hold

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

@davidz627 @jingxu97 @msau42

### CODE REVIEW

**Comment by hantaowang** [comment]
This unit test annoying requires GoogleCloudPlatform/k8s-cloud-provider to be update to at least 0.18.0, which requires a rather difficult upgrade of GCP's API library. So lets let this PR sit for a while and hopefully in the near future these libraries are updated and it can be merged.

**Comment by hantaowang** [comment]
This unit test annoying requires GoogleCloudPlatform/k8s-cloud-provider to be update to at least 0.18.0, which requires a rather difficult upgrade of GCP's API library. So lets let this PR sit for a while and hopefully in the near future these libraries are updated and it can be merged.
/lifecycle frozen

**Comment by cheftako** [comment]
@hantaowang Are you still working on this or should we close it out?

**Comment by hantaowang** [comment]
Fee free to close it. Thanks.

**Pull request closed without merging**
