### PR TITLE
Rev the Azure SDK for networking.

### PR DESCRIPTION
**Pull request by brendandburns**
```release-note
Rev the Azure SDK for networking to 2017-06-01
```

### CODE REVIEW

**Comment by brendandburns** [comment]
@khenidak @feiskyer ptal.

Thanks!

**Review by khenidak — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
@brendanburns We should cherry-pick this vendor updates to v1.8 for fix https://github.com/Azure/AKS/issues/199

**Comment by feiskyer** [comment]
Hmm, too many changes since v1.8. Let me choose an old version.

**Pull request merged**
