### PR TITLE
remove the create-external-load-balancer flag in cmd/expose.go

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
In cmd/expose.go there is a todo "remove create-external-load-balancer in code on or after Aug 25, 2016.", and now it's been a long time past. So I remove this flag and modify the test cases. 
Please check for this, thanks!

**Release note**:

```
remove the deprecated flag "create-external-load-balancer" and use --type="LoadBalancer" instead.
```

### CODE REVIEW

**Comment by tianshapjq** [comment]
@zmerlynn is it ok to test?

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
I0109 11:11:20.940] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0109 11:11:29.903] !!! 'gofmt -s -w' needs to be run on the following files: 
I0109 11:11:29.904] ./pkg/kubectl/service_test.go


ping when done

**Comment by tianshapjq** [comment]
@thockin gofmt done :)

**Comment by kargakis** [comment]
I think this needs a release note

**Comment by tianshapjq** [comment]
@kargakis release note added.

**Pull request merged**
