### PR TITLE
Stop collecting monit logs via fluentd

### PR DESCRIPTION
**Pull request by a-robinson**
Does supervisord write any log files worth collecting?

@brendandburns @roberthbailey

### CODE REVIEW

**Comment by a-robinson** [comment]
And this isn't even worth bothering to make new image for, since it's harmless to leave in the additional input.

**Comment by gmarek** [comment]
cc @wojtek-t - we were looking at monit logs when trying to figure out reason for Kubelet restarts. They are not super-helpful, but they are also not completely useless. That being said, I'm not sure if we need to put them into fluentd.

**Comment by wojtek-t** [comment]
@a-robinson - why do you want to remove them from fluentd? A potential reason I can see is that we have too many logs written to fluentd, but comparing monit logs to e.g. Kubelet or Dockers logs, they are supoer small (orders of magnitude smaller)

**Comment by a-robinson** [comment]
Monit is being pulled out in place of supervisord. See #12325.

I'm happy to leave this in longer if you'd like, though.

**Pull request merged**
