### PR TITLE
test/framework: psp.go skipper.go remove direct import /k8s.io/kubernetes/pkg

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/74352

**Special notes for your reviewer**:
/cc @alejandrox1 
/cc @oomichi 

test/framework: psp.go skipper.go remove direct import /k8s.io/kubernetes/pkg

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
confirmed these values are the same as the original `kubernetes/pkg/...` ones.

/lgtm

**Comment by oomichi** [comment]
Please rebase this on the latest master.

/lgtm cancel

**Comment by tanjunchen** [comment]
> Please rebase this on the latest master.
> 
> /lgtm cancel

done

**Review by alejandrox1 — COMMENTED** [review]
Thank you for picking this up @tanjunchen !
/approve
/lgtm
/priority important-soon

**Pull request merged**
