### PR TITLE
hack/local-up-cluster: optimze exit when run as daemon

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

When run as daemon, if kill it, would no cleanup.

### CODE REVIEW

**Comment by daixiang0** [comment]
The `set -E` refer to https://stackoverflow.com/questions/35800082/how-to-trap-err-when-using-set-e-in-bash.

**Comment by neolit123** [comment]
/cc @dims @BenTheElder 
last time i checked we were no longer running local-up-cluster in CI, should we instead add a notice in the bash script that it will no longer accept changes?

**Comment by dims** [comment]
@neolit123 we are using it for testing the conformance image. this is still incredibly useful for many folks working with sig-storage. Not ready to get rid of it yet. this change does seem useful.

**Comment by neolit123** [comment]
ack,

/sig testing
/kind feature
/priority backlog

**Comment by daixiang0** [comment]
Remove `chown` line since this [log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91530/pull-kubernetes-local-e2e/1267415392557469696/#1:build-log.txt%3A517).
It seems that `chown` has failed for a long time but no one consider it.

**Comment by dims** [comment]
@daixiang0 please add a if condition to check if the environment variable `CI` is set to `true` then skip that chown that fails. see if this works.

**Comment by daixiang0** [comment]
@dims Hi, since i add `set -E`, so `chown` failure would always lead to cleanup, it is expected.

**Comment by dims** [comment]
/close

let's leave this alone for now. thanks @daixiang0

**Pull request closed without merging**
