### PR TITLE
Use alpine as sample-apiserver base image

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Use alpine as sample-apiserver base image to reduce the image size. With `fedora` as base image the image size is ~300Mb, with `alpine` as base image - ~60Mb. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by matthyx** [comment]
Hello and welcome @ialidzhikov !
Why not https://github.com/GoogleContainerTools/distroless ?
/cc

**Comment by ialidzhikov** [comment]
Yes, sure. `distroless` is also a valid option. I have no strong opinion on that. The base image for the sample-apiserver which is build for tests is `alpine`, I guess. https://github.com/kubernetes/kubernetes/blob/a1364be0126743c5cc032c21f28fb5e41f636253/test/images/sample-apiserver/BASEIMAGE#L1-L5.

I would be nice to have match in the base images used for the tests and the base image in the sample-apiserver repo.

**Comment by matthyx** [comment]
@liggitt what do you think? Personally I would prefer to reduce the image dependencies, if that's possible.
In that case, looks like we just put a go binary, so distroless seems fine...

**Comment by liggitt** [comment]
I'd lean toward distroless, and toward making the image used for tests and in the example consistent

**Comment by matthyx** [comment]
> I'd lean toward distroless, and toward making the image used for tests and in the example consistent

Amen, @ialidzhikov can you change your PR and maybe create an issue to group the various PRs that will be required for the task?

**Comment by ialidzhikov** [comment]
Note the sample-apiserver base images and that there are listed multiple os archs:

https://github.com/kubernetes/kubernetes/blob/a1364be0126743c5cc032c21f28fb5e41f636253/test/images/sample-apiserver/BASEIMAGE#L1-L5

Currently distroless supports only `amd64`. Ref https://github.com/GoogleContainerTools/distroless/issues/406.

```
manifest-tool inspect gcr.io/distroless/base-debian10
gcr.io/distroless/base-debian10: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:732acc54362badaa64d9c01619020cf96ce240b97e2f1390d2a44cc22b9ba6a3
Architecture: amd64
          OS: linux
    # Layers: 2
      layer 1: digest = sha256:cfb92865f5ba0896315e32338a1e96810f87b19ba7703a4a3c4a5b224b6c7e5f
      layer 2: digest = sha256:8dd350b5e0d523fff026145128f80cfa4148e83a33226eae2ee679aeda36dc0b
```




@liggitt, do we need these multiple archs in this file. Can we set only `amd64` for example such as
```
amd64=gcr.io/distroless/base-debian10
```
and ignore the other archs?
If not, I guess we need to fallback to alpine, right?

**Comment by matthyx** [comment]
Hmm, interesting... I didn't think about other architectures!
Maybe we should use distroless wherever possible (amd64) and use alpine otherwise?

Also, for a golang binary, please use `distroless/base` if you need the go runtime lib, or simply `distroless/static` if your executable is statically linked.

**Comment by ialidzhikov** [comment]
> Also, for a golang binary, please use distroless/base if you need the go runtime lib, or simply distroless/static if your executable is statically linked.

I wanted to use `gcr.io/distroless/static-debian10` but the latest tag is missing. Ref GoogleContainerTools/distroless#436.
```
$ docker pull gcr.io/distroless/static-debian10
Using default tag: latest
Error response from daemon: manifest for gcr.io/distroless/static-debian10:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/distroless/static-debian10/manifests/latest".

$ docker pull gcr.io/distroless/static-debian9
Using default tag: latest
Error response from daemon: manifest for gcr.io/distroless/static-debian9:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/distroless/static-debian9/manifests/latest".
```

**Comment by matthyx** [comment]
I always thought using the "latest" tag was a terrible idea because it makes things unreproducible...

**Comment by ialidzhikov** [comment]
@liggitt , @deads2k , any reply to my question from above? Do we require the base image to support multiple archs?

**Comment by liggitt** [comment]
I'm not sure... that's probably a better question for sig-release

**Comment by matthyx** [comment]
@justaugustus what do you think?

**Comment by justaugustus** [comment]
My apologies for missing this!

Main question from me: what's the difference between https://github.com/kubernetes/kubernetes/blob/master/test/images/sample-apiserver/Dockerfile and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-apiserver/artifacts/simple-image/Dockerfile?

It seems like they could serve similar purposes and the former has recently been updated: https://github.com/kubernetes/kubernetes/pull/90963

**Pull request closed without merging**
