### PR TITLE
match value from #38706

### LINKED ISSUE #40459: local-up-cluster.sh not playing nice with ~/.kube/config - causing login error
using ./hack/local-up-cluster.sh and after executing the post completion steps get a login failure:

```
[root@k8dev2 kubernetes]# kubectl get nodes
error: You must be logged in to the server (the server has asked for the client to provide credentials (get .meta.k8s.io))
```

Post Completion Steps:
```
To start using your cluster, open up another terminal/tab and run:

  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/apiserver.crt
  cluster/kubectl.sh config set-credentials myself --username=admin --password=admin
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
```

After speaking with @ncdc he asked me to try the following:

1.  remove the ~/.kube/config  file
2.  remove /var/run/kubernetes
3.  rerun local-up-cluster.sh

After those steps, IF I DO NOT run the post script steps from above where we are setting the config...
I'm able to use kubectl with no issues

```
[root@k8dev2 kubernetes]# kubectl get nodes
NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     10s       v1.6.0-alpha.0.3907+90b5d4cbd8719f
```

However, as soon as I run those steps, I'm back to the error:

```
Cluster "local" set.
User "myself" set.
Context "local" set.
Switched to context "local".

[root@k8dev2 kubernetes]# kubectl get nodes
error: You must be logged in to the server (the server has asked for the client to provide credentials (get .meta.k8s.io))
```

After this, without restarting my cluster, I just simply remove the ~/.kube/config file again and I'm back to a working cluster:

```
[root@k8dev2 kubernetes]# rm -rf ~/.kube/config 

[root@k8dev2 kubernetes]# kubectl get nodes
NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     14m       v1.6.0-alpha.0.3907+90b5d4cbd8719f
```

### PR DESCRIPTION
**Pull request by MHBauer**
- fixes #40459

**What this PR does / why we need it**:
Makes local-up-cluster work again when using the printed out information.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #40459

**Special notes for your reviewer**:
I don't understand how this works. If there's a better way to fix this let me know. @pmorie @deads2k 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
I'd rather go ahead and disable the insecure port entirely and enable anytoken + RBAC by default since we know the roles are correct now.

**Comment by MHBauer** [comment]
@deads2k do you have a detailed suggestion for what I need to do or a replacement PR? I don't know how to do what you are suggesting.

**Comment by deads2k** [comment]
@MHBauer go ahead and start by disabling the insecure port and seeing what falls out.  Suggesting that people use the insecure port is the wrong solution.

**Comment by MHBauer** [comment]
Not sure what to do. I was following the change in #38706. 

#40459 is the immediate result. Leaving kubeconfig blank uses an insecure connection by default on kubectl. Removing the `--insecure` flags on the apiserver start results in the insecure server starting up anyway.

**Comment by MHBauer** [comment]
fixed by #40193

**Pull request closed without merging**
