### PR TITLE
docs: fix docs for #6776

### PR DESCRIPTION
**Pull request by xiang90**
./hack/verify-gendocs.sh fails after https://github.com/GoogleCloudPlatform/kubernetes/commit/2a9141f83a00d8809db3dba21895fd0758c05094 on darwin/amd64.

run `./hack/run-gendocs.sh` to fix it.

Well... After I ran `./hack/run-gendocs.sh` it is fixed on my darwin, but it is broken on linux build...

### CODE REVIEW

**Comment by yifan-gu** [comment]
Strange. It's building on my machine

**Comment by yifan-gu** [comment]
And the commits seems odd, it just moves several lines around...

**Comment by xiang90** [comment]
@yifan-gu It seems to be a darwin thing... 

/cc @dchen1107

**Comment by jlowdermilk** [comment]
This is passing at head, so you probably just need to run `make clean` and try rebuilding.

**Comment by xiang90** [comment]
@jlowdermilk Have you tried it on Darwin? It passes on linux, but not on my mac... wired...

**Comment by erictune** [comment]
Are you sure make clean is working?  Sometimes boot2docker vm is wedged and
make clean does not succeed.

**Comment by jlowdermilk** [comment]
I'm getting the same error on Darwin too:
```
hack/verify-gendocs.sh
+++ [0414 11:12:52] Building go targets for darwin/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
+++ [0414 11:12:53] Placing binaries
diffing /Users/jeffml/kubernetes/docs/ against freshly generated docs
diff -Naupr -I 'Auto generated by' /Users/jeffml/kubernetes/docs/.files_generated /Users/jeffml/kubernetes/docs_tmp/.files_generated
--- /Users/jeffml/kubernetes/docs/.files_generated	2015-04-14 11:12:45.000000000 -0700
+++ /Users/jeffml/kubernetes/docs_tmp/.files_generated	2015-04-14 11:12:55.000000000 -0700
@@ -1,3 +1,4 @@
+kubectl.md
 kubectl_api-versions.md
 kubectl_cluster-info.md
 kubectl_config.md
@@ -16,7 +17,6 @@ kubectl_expose.md
 kubectl_get.md
 kubectl_label.md
 kubectl_log.md
-kubectl.md
 kubectl_namespace.md
 kubectl_port-forward.md
 kubectl_proxy.md
diff -Naupr -I 'Auto generated by' /Users/jeffml/kubernetes/docs/man/man1/.files_generated /Users/jeffml/kubernetes/docs_tmp/man/man1/.files_generated
--- /Users/jeffml/kubernetes/docs/man/man1/.files_generated	2015-04-14 11:12:45.000000000 -0700
+++ /Users/jeffml/kubernetes/docs_tmp/man/man1/.files_generated	2015-04-14 11:12:53.000000000 -0700
@@ -1,14 +1,13 @@
-kubectl.1
 kubectl-api-versions.1
 kubectl-cluster-info.1
-kubectl-config.1
-kubectl-config-set.1
 kubectl-config-set-cluster.1
 kubectl-config-set-context.1
 kubectl-config-set-credentials.1
+kubectl-config-set.1
 kubectl-config-unset.1
 kubectl-config-use-context.1
 kubectl-config-view.1
+kubectl-config.1
 kubectl-create.1
 kubectl-delete.1
 kubectl-describe.1
@@ -26,3 +25,4 @@ kubectl-run-container.1
 kubectl-stop.1
 kubectl-update.1
 kubectl-version.1
+kubectl.1
/Users/jeffml/kubernetes/docs/ is out of date. Please run hack/run-gendocs.sh
```

The problem is that `sort` doesn't behave the same on linux and darwin. @filbranden, any ideas how to make [this line](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/util.sh#L141) do the same thing on darwin/linux? If not, I might just change it to inline python.

**Comment by jlowdermilk** [comment]
cc @eparis

**Comment by filbranden** [comment]
Not sure this is actually the problem (and I don't really have a darwin close by), but when using `sort`, **ALWAYS** use `LC_COLLATE=C sort` since otherwise collation order depends on the environment's locale. I could easily believe the default locale on MacOS X is different from the default one on Linux...

**Comment by filbranden** [comment]
If you have a darwin around, try these two commands and compare their output:

```shell
$ { echo kubectl.1; echo kubectl-api-versions.1; } | sort
kubectl-api-versions.1
kubectl.1

$ { echo kubectl.1; echo kubectl-api-versions.1; } | LC_COLLATE=C sort                                                                                                                      
kubectl-api-versions.1
kubectl.1
```

If the former looks inverted and the latter looks the same, then LC_COLLATE is really what you want here.

**Comment by smarterclayton** [comment]
On my Yosemite build those are in the same order.  But I have LANG="en_US.UTF-8" set.

**Comment by eparis** [comment]
On my linux box:
```
$ { echo kubectl.1; echo kubectl-api-versions.1; } | sort
kubectl.1
kubectl-api-versions.1

$ { echo kubectl.1; echo kubectl-api-versions.1; } | LC_COLLATE=C sort
kubectl-api-versions.1
kubectl.1
```

**Comment by jlowdermilk** [comment]
@filbranden, they look the same on darwin, but they differ on linux:
```
$ { echo kubectl.1; echo kubectl-api-versions.1; } | sort
kubectl.1
kubectl-api-versions.1

$ { echo kubectl.1; echo kubectl-api-versions.1; } | LC_COLLATE=C sort                                                                                                                      
kubectl-api-versions.1
kubectl.1
```

Looks like LC_COLLATE is what we want. @xiang90, can we use this PR to make the change? the command that needs to be updated is [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/util.sh#L141).

**Comment by xiang90** [comment]
@jlowdermilk Sure thing. Wait a moment. need to have lunch right now.

**Comment by filbranden** [comment]
@jlowdermilk Ah yes I forgot that on my Linux I always set `LC_COLLATE=C` so I always get *sane* behavior from `sort` in all cases...

Indeed using `LC_COLLATE=en_US.UTF-8 sort` gives me the wrong sort order as @eparis just confirmed.

In any case, scripts should always force `LC_COLLATE=C sort` if you're using sort for programmatic purposes to isolate from the environment's locale...

Might as well just go through all the `*.sh` scripts in Kubernetes looking for calls to `sort` and fixing them all to do the right thing...

Cheers,
Filipe

**Comment by xiang90** [comment]
@jlowdermilk Hrm... still does not work well after the change.

**Comment by eparis** [comment]
@xiang90 it looks good to me, what's wrong?

**Comment by xiang90** [comment]
@eparis Travis and Shippable failed. :(

**Comment by eparis** [comment]
for a more readable commit, you can git checkout docs/kubectl*.md

@filbranden the man page for sort suggest LC_ALL=C

Is that what we should be using?

**Comment by eparis** [comment]
Note that setting only 'LC_COLLATE' has two problems.
First, it is ineffective if 'LC_ALL' is also set.  Second, it has
undefined behavior if 'LC_CTYPE' (or 'LANG', if 'LC_CTYPE' is unset) is
set to an incompatible value.  For example, you get undefined behavior
if 'LC_CTYPE' is 'ja_JP.PCK' but 'LC_COLLATE' is 'en_US.UTF-8'.

**Comment by filbranden** [comment]
@eparis Yes, I think you're right setting LC_ALL is probably better since it's the strongest.

(I thought of it first, rejected thinking it was using a cannon to kill a fly, but on second thought it makes more sense.)

Let's go with `LC_ALL=C sort ...` and I'd recommend checking all the `*.sh` files in the tree for uses of `sort` and trying to fix them all (probably not in this same PR, or if in this same PR then in a separate commit) since they're potentially all affected.

Cheers,
Filipe

**Comment by xiang90** [comment]
@filbranden @jlowdermilk @eparis Fixed. 

I will try to "fix" all sh in another pr.

**Comment by jlowdermilk** [comment]
lgtm

**Comment by eparis** [comment]
@filbranden I'm not as smart are my last comment, I'm just quoting from the footnotes in `info coreutils 'sort invocation'`

**Comment by filbranden** [comment]
@eparis Which is actually the smart thing to do: RTFM! :-)

**Pull request merged**
