### PR TITLE
Check RegisterMetricAndTrackRateLimiterUsage error when starting controller

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

similar to #53592, fix rest part controller when use RegisterMetricAndTrackRateLimiterUsage 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # complements #53571

**Special notes for your reviewer**:

/assign @deads2k 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
@deads2k Can you take a look at this, I think we should merge this before code freeze. All controller should have consistent action for `RegisterMetricAndTrackRateLimiterUsage`

**Comment by thockin** [comment]
Who is a good reviewer for this?

**Comment by wackxu** [comment]
@deads2k I think this must be merged into release 1.9, as  #53592 has been merged and all controller should have consistent action for  `RegisterMetricAndTrackRateLimiterUsage`

**Comment by deads2k** [comment]
> @deads2k I think this must be merged into release 1.9, as #53592 has been merged and all controller should have consistent action for RegisterMetricAndTrackRateLimiterUsage

I think that 1.9 can go without this.  The consequences aren't awful.

**Pull request closed without merging**
