### PR TITLE
Unittests for horizontal pod autoscaler controller.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Unittests for horizontal pod autoscaler controller.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Please note that this PR is not implementing all the unittests for horizontal pod autoscaler controller that we should have. I'm going to add tests for multiple metrics with different timestamps in a subsequent PR.

**Comment by mwielgus** [comment]
LGTM

**Comment by jszczepkowski** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
Build failed because of:
```
05:11:07 ------------------------------
05:40:24 Build timed out (after 45 minutes). Marking the build as aborted.
05:40:24 Build timed out (after 45 minutes). Marking the build as failed.
05:40:25 
05:40:25 Build was aborted
05:40:25 Recording test results
```

**Comment by mwielgus** [comment]
@k8s-bot test this

**Comment by jszczepkowski** [comment]
Part of #12087.

**Comment by alex-mohr** [comment]
@jszczepkowski "Please note that this PR is not implementing all the unittests for horizontal pod autoscaler controller that we should have. I'm going to add tests for multiple metrics with different timestamps in a subsequent PR."
Kudos for calling out that there aren't enough tests covering this.  I'm somewhat wary of code w/o sufficient test coverage going in, though, especially w/o an issue at sufficiently high priority tracking the work.  Can you please file an issue on your team to ensure it happens?

**Comment by alex-mohr** [comment]
@k8s-bot test this again please (apparent flake due to #13485 unclear build timeout)

**Comment by jszczepkowski** [comment]
@k8s-bot test this again

**Comment by jszczepkowski** [comment]
One of shipable builds fails (on go 1.3) because of some problems in integration tests:
WARNING: DATA RACE
...
k8s.io/kubernetes/test/integration.TestPersistentVolumeRecycler()
/root/workspace/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:212 +0x45

This not related to this PR, as this PR is not touching production code.

**Comment by jszczepkowski** [comment]
@k8s-bot test this

**Comment by jszczepkowski** [comment]
@k8s-bot test this again

**Comment by jszczepkowski** [comment]
Follow-up: opened two issues: #14108 (for more tests) and #14107 (for flaky integration test on shipable).

**Pull request merged**
