### PR TITLE
Changing --use-kubernetes-version to --kubernetes-version for kubeadm beta

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**: to follow-up agreement on SIG-Cluster-Lifecycle on 2017-02-21, flag for `kubeadm init` should be renamed.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: Meeting minutes for SIG-Cluster-Lifecycle 2017-02-21

**Release note**:
```release-note
Flag --use-kubernetes-version for kubeadm init renamed to --kubernetes-version
```

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot ok to test

/lgtm
/approve

I'm ok with this given tests are passing which I think they'll do

**Comment by dmmcquay** [comment]
@kad you also need to update "hack/verify-flags/known-flags.txt"

**Comment by kad** [comment]
@dmmcquay good catch. missed it, updated.

**Comment by mikedanese** [comment]
@kad please squash fixup commits.

**Comment by luxas** [comment]
Squash and sort the known flags file, otherwise it'll fail :(

**Comment by kad** [comment]
squashed and sorted.  known-flags.txt seems to be already not sorted, but let's make it cleaner now :)

**Comment by luxas** [comment]
@k8s-bot unit test this
@k8s-bot verify test this

**Comment by luxas** [comment]
Oh, this is crazy:
```
I0221 12:17:42.811] Found illegal 'flag' usage. If these are false negatives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
I0221 12:17:42.812] federation/deploy/config.json.sample:      "kubernetes_version": "v1.4.0"
I0221 12:17:42.812] federation/deploy/config.json.sample:      "kubernetes_version": "v1.4.0"
I0221 12:17:42.812] federation/deploy/config.json.sample:      "kubernetes_version": "v1.4.0"
I0221 12:17:42.819] FAILED   hack/make-rules/../../hack/verify-flags-underscore.py	62s
```

@kubernetes/sig-testing-bugs Are these known failures? See also: https://github.com/kubernetes/kubernetes/pull/41721#discussion_r102263915

@kad if nothing else works, you have to run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt`, although this amount of extra work is insane when thinking about what you're actually trying to do -- rename a flag :)

**Comment by ixdy** [comment]
I think this is WAI...

**Comment by ixdy** [comment]
Basically, you added a new flag `kubernetes-version`, so the script now thinks any `kubernetes_version` usages were an "old" version of the flag that need to be fixed.

**Comment by kad** [comment]
It's always fun to change something small and dig out places that you can't foresee :)
Updated.

**Comment by kad** [comment]
Looked trough test logs, don't see any reason for this PR to fail: most of errors are about cloud not ready, like network/DNS/scp failures.

**Comment by ixdy** [comment]
/approve
for verify-flags

**Comment by kad** [comment]
cool, flakes are gone. hopefully it will be still merged to 1.6

**Pull request merged**
