### PR TITLE
Long running actions (CRI, GC, Stats) in Kubelet should pass context.Context

### LINKED ISSUE #100219: WaitForAttachAndMount might delay pod terminating.
From comment https://github.com/kubernetes/kubernetes/issues/100047#issuecomment-796980046

syncPod is waiting for volumes to finish mounting. before calling WaitForAttachAndMount, it checks if the pod is terminated before entering. However, if the pod is terminated after that check, then we are stuck in in WaitForAttachAndMount until it times out, a little over 2 minutes.

The call probably needs to be enhanced to return early if the pod is deleted. It doesn't seem like pod deletion is captured as a pod error. In fact, we seem to pop all errors if the pod is deleted.

### PR DESCRIPTION
**Pull request by smarterclayton**
While investigating #105204 we identified areas where cleanup, cancellation, and logging in the Kubelet's core volume/pod loops could reduce spam and improve readability, as well as improve latency of shutdown.  One of the issues is #100219, which previous changes primed us for by adding support for context cancellation in the pod worker to allow the pod worker to cancel a `syncPod` call when the pod was terminated.

To properly leverage that, we'll need to ensure context is propagated to long running actions, especially CRI calls, so that when we cancel the syncPod method we don't simply hang lower in the stack.

This PR ensures the core CRI methods accept a context, and propagates them upward towards the key top level loops in the Kubelet. The first commit is the interfaces changed, the second commit is the boundaries at which propagation stops, the third commit is mechanical propagation between methods and signature changes, and the fourth commit is changes to tests. Propagation was stopped when we hit a method with a context already, when we hit a top level wait loop (using `context.Background()`), or when we hit a significant inter kubelet boundary where propagation was unclear (used `context.TODO()`).

This will set us up to invoke the cancellation on the syncPod method and terminate the volume call, and give us a reasonably good chance of syncPod cancellation terminating syncPod early.

Fixes #100219

Depends on #107845 #107826 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/sig node

Needs an e2e to prove we fixed #100219, so

/hold

**Comment by smarterclayton** [comment]
I may split out a 4th commit which is all the termination points  in the code.

**Comment by smarterclayton** [comment]
Ok, split out so commits 1 and 2 are the important changes (which interfaces i changed, and the transition points where propagation stopped), and 3 and 4 are the mechanical (changing method signatures or simply propagating ctx, and tests).

**Comment by smarterclayton** [comment]
Excellent, the context cancel from early termination showed up in the stress test (exactly as it should).  Will poke the other tests.

**Comment by smarterclayton** [comment]
In https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107829/pull-kubernetes-e2e-kind/1486852342270660608 the test saw cancelled pods exit without error, which means we have a data race in kubelet status when we cancel syncPod (and possibly was always there), debugging with extra commits.

**Comment by smarterclayton** [comment]
With debugging info from last commit:

```
Jan 28 21:06:49 kind-worker kubelet[260]: I0128 21:06:49.529089     260 kubelet_pods.go:1442] "DEBUG: old status of container in pod" pod="pods-193/pod-submit-status-1-13" container={Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2 ImageID: ContainerID: Started:0xc0020d7549}
Jan 28 21:06:49 kind-worker kubelet[260]: I0128 21:06:49.529126     260 kubelet_pods.go:1445] "DEBUG: current status of container in pod" pod="pods-193/pod-submit-status-1-13" container=&{ID:{Type:containerd ID:9546f3e665ae124f3f289abb54f0990f3c75ad5227f209aea1136ace28866d7d} Name:busybox State:created CreatedAt:2022-01-28 21:06:48.560908486 +0000 UTC StartedAt:0001-01-01 00:00:00 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC ExitCode:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2 ImageID:k8s.gcr.io/e2e-test-images/busybox@sha256:c318242786b139d18676b1c09a0ad7f15fc17f8f16a5b2e625cd0dc8c9703daf Hash:1058971626 RestartCount:0 Reason: Message:}
Jan 28 21:06:49 kind-worker kubelet[260]: I0128 21:06:49.529181     260 kubelet_pods.go:1449] "DEBUG: new status of container in pod" pod="pods-193/pod-submit-status-1-13" container={Name:busybox State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:containerd://9546f3e665ae124f3f289abb54f0990f3c75ad5227f209aea1136ace28866d7d,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2 ImageID:k8s.gcr.io/e2e-test-images/busybox@sha256:c318242786b139d18676b1c09a0ad7f15fc17f8f16a5b2e625cd0dc8c9703daf ContainerID:containerd://9546f3e665ae124f3f289abb54f0990f3c75ad5227f209aea1136ace28866d7d Started:<nil>}
Jan 28 21:06:49 kind-worker kubelet[260]: I0128 21:06:49.529201     260 kubelet_pods.go:1455] "Got phase for pod" pod="pods-193/pod-submit-status-1-13" oldPhase=Pending phase=Succeeded
```

if containerd StartContainer is sent a cancelled ctx, PLEG sees the following container status from the runtime:

```
&{ID:{Type:containerd ID:9546f3e665ae124f3f289abb54f0990f3c75ad5227f209aea1136ace28866d7d} Name:busybox State:created CreatedAt:2022-01-28 21:06:48.560908486 +0000 UTC StartedAt:0001-01-01 00:00:00 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC ExitCode:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2 ImageID:... Hash:1058971626 RestartCount:0 Reason: Message:}
```

which is wrong, exit code is definitely 100% not zero.

**Comment by smarterclayton** [comment]
All issues in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107829/pull-kubernetes-unit/1487215967338500096 appeared to be unrelated test flakes

**Comment by smarterclayton** [comment]
Looking at the logs I no longer see mount continuing after termination as expected (since the volume mount wait loop is incremental and terminates easily).  The remaining latency during teardown (p90 ~30s) is due to the single threaded status loop being saturated, which was discussed a while back in https://github.com/openshift/origin/pull/24655/commits/492e33ac1d790bf07f59e1c7b2b69f0abe4ba250

**Comment by smarterclayton** [comment]
I revived the single threaded status work in #107897 (and may test this PR in concert with it)

**Comment by smarterclayton** [comment]
Testing with some additional debugging in OpenShift (where I have better holistic log capture through integrated debugging) I see the latency in https://github.com/openshift/kubernetes/pull/1162 i see the pod start latencies in the "rapid create and then delete test" (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1162/pull-ci-openshift-kubernetes-master-k8s-e2e-gcp/1488660650245754880/artifacts/k8s-e2e-gcp/openshift-kubernetes-e2e-test/build-log.txt in test `[sig-node] Pods Extended [It] should never report success for a pending container`) as:

```
Feb  2 00:58:33.660: INFO: Summary of latencies:
# HELP start_latency 
# TYPE start_latency summary
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq",quantile="0.5"} 3.094219779
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq",quantile="0.75"} 3.891839054
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq",quantile="0.9"} 4.248413422
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq",quantile="0.99"} 4.448583158
start_latency_sum{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq"} 51.69823404999999
start_latency_count{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-a-cjflq"} 16
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9",quantile="0.5"} 3.485017703
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9",quantile="0.75"} 4.176054491
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9",quantile="0.9"} 4.881439665
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9",quantile="0.99"} 7.066718746
start_latency_sum{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9"} 89.81426097500001
start_latency_count{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-b-68fr9"} 25
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw",quantile="0.5"} 3.15469407
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw",quantile="0.75"} 3.45381362
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw",quantile="0.9"} 3.9612036489999998
start_latency{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw",quantile="0.99"} 3.9612036489999998
start_latency_sum{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw"} 13.575080079
start_latency_count{node="ci-op-tf1yj3bs-a2fce-r2q9p-worker-c-c9rxw"} 4
```

This is significantly reduced from the (not quite apples-to-apples of kube upstream kind) ~30s p99 latency we observe, which is a good indication that context cancellation can reduce end to end latency when pods are terminated during setup.

**Comment by smarterclayton** [comment]
Found another place where context cancellation is critical for latency - if you try to start a lot of pods, and some of them hang on image pull failures due to rate limiting or auth or backoff, the syncPod loop blocks on the pull and goes into backoff, which means in the worst case it can be 5 minutes before syncPod exits and your pod gets deleted.

I'll rebase this, but this is a pretty important behavior to fix.

**Comment by aojea** [comment]
> 

another data points to compare 

http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadPodStartup&Metric=pod_startup

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/107829/pull-kubernetes-e2e-gce-100-performance/1498672689978544128/artifacts/PodStartupLatency_CreatePhasePodStartupLatency_load_2022-03-01T15:39:46Z.json

but the p99 there are very high :thinking: , it will be good to run these number by someone from sig-scalability or wojktek, too?
```
      "data": {
        "Perc50": 2217.511581,
        "Perc90": 3296.089837,
        "Perc99": 23734.45666
      },
      "unit": "ms",
      "labels": {
        "Metric": "pod_startup"
      }
```

**Comment by smarterclayton** [comment]
Context cancel shouldn't affect pod startup directly.

**Review by mikebrow — COMMENTED** [review]
partial review only... see comments

note to self might want to add 
``` "%+v", ctx ``` or suitable to the instrumented trace in the container runtimes so we can see who's cancellable, timeouts...

**Pull request closed without merging**
