### PR TITLE
kubeadm: speedup init by 0s or 20s

### PR DESCRIPTION
**Pull request by champtar**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In my setup where the whole system is restricted to 1 core (2 threads), "All control plane components are healthy after" message goes from 25s to 6s.

#### Special notes for your reviewer:
I haven't reviewed other commands like join

#### Does this PR introduce a user-facing change?
```release-note
kubeadm: speedup init by 0s or 20s. kubelet-start phase is now after etcd and control-plane phases, removing a race condition between kubelet looking for static pod manifests and kubeadm writing them.
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
is there an overall startup time improvement ALA `time  kubeadm ...`?

**Comment by champtar** [comment]
> is there an overall startup time improvement ALA `time kubeadm ...`?

Yes, I run kubeadm in a systemd unit and the gain is also around 20s (I can pull the logs on Monday)

My understanding is that by having the static pods manifests when kubelet starts, kubelet starts the pods right away instead of starting lots of goroutine that want to talk to the API and start retry-back-off

**Comment by champtar** [comment]
@neolit123 can you ok-to-test the PR to see if it breaks anything

**Comment by neolit123** [comment]
> > is there an overall startup time improvement ALA `time kubeadm ...`?
> 
> Yes, I run kubeadm in a systemd unit and the gain is also around 20s (I can pull the logs on Monday)
> 
> My understanding is that by having the static pods manifests when kubelet starts, kubelet starts the pods right away instead of starting lots of goroutine that want to talk to the API and start retry-back-off

we generally consider phase order changes as breaking, but if only performance is affected maybe this can go init.

IIRC, for kubeadm join the etcd phase position was quite important

**Review by Tusenka — APPROVED** [review]

**Review by Tusenka — APPROVED** [review]

**Review by Tusenka — APPROVED** [review]

**Review by Tusenka — APPROVED** [review]

**Comment by champtar** [comment]
> > > is there an overall startup time improvement ALA `time kubeadm ...`?
> > 
> > 
> > Yes, I run kubeadm in a systemd unit and the gain is also around 20s (I can pull the logs on Monday)
> > My understanding is that by having the static pods manifests when kubelet starts, kubelet starts the pods right away instead of starting lots of goroutine that want to talk to the API and start retry-back-off
> 
> we generally consider phase order changes as breaking, but if only performance is affected maybe this can go in.
> 
> IIRC, for kubeadm join the etcd phase position was quite important

etcd and control-plane init phases are way simpler, they only generate the static pods manifests
https://github.com/kubernetes/kubernetes/blob/fda4ca0d8a89d6a3636c058433aa8b8a2bc02460/cmd/kubeadm/app/cmd/phases/init/etcd.go#L49
https://github.com/kubernetes/kubernetes/blob/fda4ca0d8a89d6a3636c058433aa8b8a2bc02460/cmd/kubeadm/app/cmd/phases/init/controlplane.go#L68
Also the new ordering makes more sense to me, ie create the config before starting what uses it.

**Comment by neolit123** [comment]
CI seems green.

looking for consensus from other maintainers. i am generally +1 but not clear if we are breaking something.
 
/cc @fabriziopandini @SataQiu @pacoxu @chendave

**Comment by neolit123** [comment]
> kubeadm: speedup init by fixing phases ordering

please include more details in the release note e.g. now phases foo and bar are after phase x.

**Comment by champtar** [comment]
> > kubeadm: speedup init by fixing phases ordering
> 
> please include more details in the release note e.g. now phases foo and bar are after phase x.

Done

BTW I put etcd before control-plane but I can leave the order contol-plane/etcd/kubelet-start if prefered

**Comment by pacoxu** [comment]
/lgtm

This seems to be a better order.
- NewWaitControlPlanePhase is after these phases whose order is changed in this PR.

> I haven't reviewed other commands like join

https://github.com/kubernetes/kubernetes/blob/9e5271e8b33618af0f552a852677ec5a97573961/cmd/kubeadm/app/cmd/join.go#L215-L218

- NewControlPlanePreparePhase: new apiserver/kcm/scheduler static pod yaml
- NewKubeletStartPhase: start kubelet
- NewControlPlaneJoinPhase: new etcd static yaml

Join may has similar problem. But I have not checked if there are some dependencies. There may need more verifications. Probably, we can do it in a new PR.

**Comment by chendave** [comment]
I'd like to test this pr in my next day, feel free to move forward anyway.

**Comment by chendave** [comment]
I did several testing in my side, the improvement is not that consistent and apparent, some times it's even worse.

I tested it on the master branch, 4 cores and 8 threads.

w/o the patch
```
time go run kubeadm.go init --cri-socket unix:///var/run/containerd/containerd.sock

real    0m23.767s
user    0m8.308s
sys     0m1.296s
```

with this change,  I get
```
real    0m22.895s
user    0m8.710s
sys     0m1.326s
```


My questions is, how many time did you try with this change? I read through the code from kueadm and kubelet as well, it's not clear to me how the ordering change improve the performance so dramatically.

kubelet check the presence of manifest file with one second interval, so this would only impact 1 second in theory.
https://github.com/kubernetes/kubernetes/blob/e3db9232d9fffbb809c5e0652f56a9eb819aef98/pkg/kubelet/config/file_linux.go#L51-L67

Kubeadm phase `NewWaitControlPlanePhase` doesn't seems relevant here, the point is when the apiserver is ready, this is not a thing which could be controlled by this phase.


I guess something like networking stability, the image pulling  etc. caused such huge difference.

Can you try more times?

**Comment by neolit123** [comment]
> I did several testing in my side, the improvement is not that consistent and apparent, some times it's even worse.

i was also surprised by the claimed speed up, so it makes sense to collect more evidence before the change.

> kubelet check the presence of manifest file with one second interval, so this would only impact 1 second in theory.

IIRC, the kubelet checked every 20 seconds for file changes in the manifest dir, not every 1 second?

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#synopsis
`--file-check-frequency`

if we somehow miss the first check at 0 seconds, then a claim we catch the second one at 20 could be correct in theory.

**Comment by pacoxu** [comment]
> https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#synopsis
> `--file-check-frequency`

https://github.com/kubernetes/kubernetes/blob/9e5271e8b33618af0f552a852677ec5a97573961/pkg/kubelet/config/file.go#L92-L115

20s is the regular check interval, besides there is a file watch. I prefer to think that the 20s is to make sure no file changes are missed by kubelet. If the file change happened after `kubelet start` and  before the `startWatch()`, then it may have to wait for 20s for the next loop. I just imagined an order without test.(my guess.)

 
- Current: start kubelet at first; then add static pod; wait kubelet watch/for-loop to pick the static pod manifest and start the pod. 
- This PR: add static pod; start kubelet; kubelet will pick up the static pod manifest and start the pod.

No matter 1s speed up or 20s speed up, this would be helpful. 
- It sounds like that this may speed up for 20s in some scenarios and most likely similar. But I still think the change is correct.

**Comment by chendave** [comment]
> IIRC, the kubelet checked every 20 seconds for file changes in the manifest dir, not every 1 second?

nope, it's 1 sec for retry but max retry 20 seconds.

```golang
const (
	retryPeriod    = 1 * time.Second
	maxRetryPeriod = 20 * time.Second
)

backOff := flowcontrol.NewBackOff(retryPeriod, maxRetryPeriod)
```

I checked the log from kubelet, this could be verified by, 

> May 18 13:56:30 a010735 kubelet[2872428]: E0518 **13:56:30.686712 2872428** file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
May 18 13:56:31 a010735 kubelet[2872428]: E0518 **13:56:31.687189 2872428** file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
May 18 13:56:32 a010735 kubelet[2872428]: E0518 **13:56:32.687975 2872428** file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
May 18 13:56:33 a010735 kubelet[2872428]: E0518 **13:56:33.688367 2872428** file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
May 18 13:56:34 a010735 kubelet[2872428]: E0518 **13:56:34.689386 2872428** file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"

**Comment by chendave** [comment]
> No matter 1s speed up or 20s speed up, this would be helpful. The release-note needs an update to make it much clearer.

As long as it's a consistently improvement even by 1 sec, I am +1.

**Comment by champtar** [comment]
Here my logs
<details>
Apr 26 21:51:37 devserver systemd[1]: Starting Install k8s cluster...
Apr 26 21:52:22 devserver k8s-install[3372]: [apiclient] All control plane components are healthy after 28.008099 seconds
Apr 26 21:52:24 devserver systemd[1]: Started Install k8s cluster.
Apr 26 22:41:15 devserver systemd[1]: Starting Install k8s cluster...
Apr 26 22:42:10 devserver k8s-install[3669]: [apiclient] All control plane components are healthy after 28.001730 seconds
Apr 26 22:42:12 devserver systemd[1]: Started Install k8s cluster.
Apr 26 22:58:29 devserver systemd[1]: Starting Install k8s cluster...
Apr 26 22:59:12 devserver k8s-install[2924]: [apiclient] All control plane components are healthy after 24.004788 seconds
Apr 26 22:59:16 devserver systemd[1]: Started Install k8s cluster.
Apr 26 23:16:00 devserver systemd[1]: Starting Install k8s cluster...
Apr 26 23:16:55 devserver k8s-install[3597]: [apiclient] All control plane components are healthy after 27.518135 seconds
Apr 26 23:16:57 devserver systemd[1]: Started Install k8s cluster.
Apr 27 11:04:36 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 11:05:17 devserver k8s-install[2891]: [apiclient] All control plane components are healthy after 24.006740 seconds
Apr 27 11:05:21 devserver systemd[1]: Started Install k8s cluster.
Apr 27 13:05:57 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 13:06:40 devserver k8s-install[2922]: [apiclient] All control plane components are healthy after 24.505860 seconds
Apr 27 13:06:44 devserver systemd[1]: Started Install k8s cluster.
Apr 27 13:13:00 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 13:13:47 devserver k8s-install[2328]: [apiclient] All control plane components are healthy after 24.506081 seconds
Apr 27 13:13:51 devserver systemd[1]: Started Install k8s cluster.
Apr 27 19:21:15 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 19:21:59 devserver k8s-install[3013]: [apiclient] All control plane components are healthy after 25.003998 seconds
Apr 27 19:22:03 devserver systemd[1]: Started Install k8s cluster.
Apr 27 19:54:42 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 19:55:26 devserver k8s-install[6844]: [apiclient] All control plane components are healthy after 24.543501 seconds
Apr 27 19:55:30 devserver systemd[1]: Started Install k8s cluster.
Apr 27 20:06:43 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 20:07:26 devserver k8s-install[2593]: [apiclient] All control plane components are healthy after 25.007681 seconds
Apr 27 20:07:30 devserver systemd[1]: Started Install k8s cluster.
Apr 27 21:10:12 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 21:10:56 devserver k8s-install[5941]: [apiclient] All control plane components are healthy after 24.014920 seconds
Apr 27 21:11:00 devserver systemd[1]: Started Install k8s cluster.
Apr 27 21:21:05 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 21:21:42 devserver k8s-install[2403]: [apiclient] All control plane components are healthy after 25.005279 seconds
Apr 27 21:21:47 devserver systemd[1]: Started Install k8s cluster.
Apr 27 22:06:41 devserver systemd[1]: Starting Install k8s cluster...
Apr 27 22:07:25 devserver k8s-install[7775]: [apiclient] All control plane components are healthy after 24.505124 seconds
Apr 27 22:07:29 devserver systemd[1]: Started Install k8s cluster.
Apr 28 12:30:23 devserver systemd[1]: Starting Install k8s cluster...
Apr 28 12:31:06 devserver k8s-install[7395]: [apiclient] All control plane components are healthy after 23.503801 seconds
Apr 28 12:31:11 devserver systemd[1]: Started Install k8s cluster.
Apr 28 12:46:12 devserver systemd[1]: Starting Install k8s cluster...
Apr 28 12:46:50 devserver k8s-install[2469]: [apiclient] All control plane components are healthy after 24.503590 seconds
Apr 28 12:46:55 devserver systemd[1]: Started Install k8s cluster.
Apr 28 13:26:47 devserver systemd[1]: Starting Install k8s cluster...
Apr 28 13:27:32 devserver k8s-install[6607]: [apiclient] All control plane components are healthy after 25.023921 seconds
Apr 28 13:27:35 devserver systemd[1]: Started Install k8s cluster.
May 01 08:09:13 devserver systemd[1]: Starting Install k8s cluster...
May 01 08:09:50 devserver k8s-install[2458]: [apiclient] All control plane components are healthy after 25.006656 seconds
May 01 08:09:53 devserver systemd[1]: Started Install k8s cluster.
May 02 11:45:37 devserver systemd[1]: Starting Install k8s cluster...
May 02 11:46:22 devserver k8s-install[3171]: [apiclient] All control plane components are healthy after 24.501988 seconds
May 02 11:46:27 devserver systemd[1]: Started Install k8s cluster.
May 02 13:27:54 devserver systemd[1]: Starting Install k8s cluster...
May 02 13:28:38 devserver k8s-install[7536]: [apiclient] All control plane components are healthy after 24.507837 seconds
May 02 13:28:42 devserver systemd[1]: Started Install k8s cluster.
May 02 14:25:26 devserver systemd[1]: Starting Install k8s cluster...
May 02 14:26:10 devserver k8s-install[7343]: [apiclient] All control plane components are healthy after 24.505974 seconds
May 02 14:26:14 devserver systemd[1]: Started Install k8s cluster.
May 02 14:48:54 devserver systemd[1]: Starting Install k8s cluster...
May 02 14:49:38 devserver k8s-install[8025]: [apiclient] All control plane components are healthy after 24.003988 seconds
May 02 14:49:42 devserver systemd[1]: Started Install k8s cluster.
May 03 11:47:10 devserver systemd[1]: Starting Install k8s cluster...
May 03 11:47:55 devserver k8s-install[8531]: [apiclient] All control plane components are healthy after 24.503959 seconds
May 03 11:47:59 devserver systemd[1]: Started Install k8s cluster.
May 03 12:28:26 devserver systemd[1]: Starting Install k8s cluster...
May 03 12:29:11 devserver k8s-install[9014]: [apiclient] All control plane components are healthy after 24.520280 seconds
May 03 12:29:15 devserver systemd[1]: Started Install k8s cluster.
May 03 14:11:42 devserver systemd[1]: Starting Install k8s cluster...
May 03 14:12:24 devserver k8s-install[9616]: [apiclient] All control plane components are healthy after 24.003276 seconds
May 03 14:12:29 devserver systemd[1]: Started Install k8s cluster.
May 03 15:08:16 devserver systemd[1]: Starting Install k8s cluster...
May 03 15:09:00 devserver k8s-install[9599]: [apiclient] All control plane components are healthy after 24.506223 seconds
May 03 15:09:05 devserver systemd[1]: Started Install k8s cluster.
May 04 14:30:57 devserver systemd[1]: Starting Install k8s cluster...
May 04 14:33:55 devserver systemd[1]: Starting Install k8s cluster...
May 04 14:34:45 devserver k8s-install[2531]: [apiclient] All control plane components are healthy after 24.502896 seconds
May 04 14:34:49 devserver systemd[1]: Started Install k8s cluster.
May 05 09:16:13 devserver systemd[1]: Starting Install k8s cluster...
May 05 09:16:57 devserver k8s-install[9008]: [apiclient] All control plane components are healthy after 24.504728 seconds
May 05 09:17:02 devserver systemd[1]: Started Install k8s cluster.
May 05 10:00:49 devserver systemd[1]: Starting Install k8s cluster...
May 05 10:01:28 devserver k8s-install[2955]: [apiclient] All control plane components are healthy after 25.001870 seconds
May 05 10:01:31 devserver systemd[1]: Started Install k8s cluster.
May 08 08:03:00 devserver systemd[1]: Starting Install k8s cluster...
May 08 08:03:42 devserver k8s-install[2941]: [apiclient] All control plane components are healthy after 25.009097 seconds
May 08 08:03:45 devserver systemd[1]: Started Install k8s cluster.
May 09 05:14:53 devserver systemd[1]: Starting Install k8s cluster...
May 09 05:15:35 devserver k8s-install[9609]: [apiclient] All control plane components are healthy after 24.502711 seconds
May 09 05:15:39 devserver systemd[1]: Started Install k8s cluster.
May 09 07:36:40 devserver systemd[1]: Starting Install k8s cluster...
May 09 07:37:36 devserver k8s-install[7072]: [apiclient] All control plane components are healthy after 24.508743 seconds
May 09 07:37:40 devserver systemd[1]: Started Install k8s cluster.
May 09 08:45:29 devserver systemd[1]: Starting Install k8s cluster...
May 09 08:46:10 devserver k8s-install[9617]: [apiclient] All control plane components are healthy after 24.009950 seconds
May 09 08:46:14 devserver systemd[1]: Started Install k8s cluster.
May 09 09:21:47 devserver systemd[1]: Starting Install k8s cluster...
May 09 09:22:30 devserver k8s-install[9617]: [apiclient] All control plane components are healthy after 24.004143 seconds
May 09 09:22:34 devserver systemd[1]: Started Install k8s cluster.
May 09 11:10:33 devserver systemd[1]: Starting Install k8s cluster...
May 09 11:11:13 devserver k8s-install[9610]: [apiclient] All control plane components are healthy after 24.502557 seconds
May 09 11:11:17 devserver systemd[1]: Started Install k8s cluster.
May 09 13:24:27 devserver systemd[1]: Starting Install k8s cluster...
May 09 13:25:10 devserver k8s-install[9629]: [apiclient] All control plane components are healthy after 24.502657 seconds
May 09 13:25:14 devserver systemd[1]: Started Install k8s cluster.
May 10 13:25:59 devserver systemd[1]: Starting Install k8s cluster...
May 10 13:26:42 devserver k8s-install[9606]: [apiclient] All control plane components are healthy after 24.506697 seconds
May 10 13:26:47 devserver systemd[1]: Started Install k8s cluster.
May 12 10:07:32 devserver systemd[1]: Starting Install k8s cluster...
May 12 10:08:16 devserver k8s-install[8113]: [apiclient] All control plane components are healthy after 25.003471 seconds
May 12 10:08:19 devserver systemd[1]: Started Install k8s cluster.
May 12 10:12:46 devserver systemd[1]: Starting Install k8s cluster...
May 12 10:13:30 devserver k8s-install[2543]: [apiclient] All control plane components are healthy after 25.003015 seconds
May 12 10:13:33 devserver systemd[1]: Started Install k8s cluster.
May 12 12:01:08 devserver systemd[1]: Starting Install k8s cluster...
May 12 12:01:30 devserver k8s-install[9596]: [apiclient] All control plane components are healthy after 4.507182 seconds
May 12 12:01:32 devserver systemd[1]: Started Install k8s cluster.
May 12 12:33:49 devserver systemd[1]: Starting Install k8s cluster...
May 12 12:34:04 devserver k8s-install[2523]: [apiclient] All control plane components are healthy after 6.019493 seconds
May 12 12:34:07 devserver systemd[1]: Started Install k8s cluster.
May 12 12:41:07 devserver systemd[1]: Starting Install k8s cluster...
May 12 12:41:27 devserver k8s-install[2603]: [apiclient] All control plane components are healthy after 5.503934 seconds
May 12 12:41:30 devserver systemd[1]: Started Install k8s cluster.
May 12 14:27:26 devserver systemd[1]: Starting Install k8s cluster...
May 12 14:27:45 devserver k8s-install[9630]: [apiclient] All control plane components are healthy after 11.005195 seconds
May 12 14:27:47 devserver systemd[1]: Started Install k8s cluster.
May 12 14:33:49 devserver systemd[1]: Starting Install k8s cluster...
May 12 14:34:12 devserver k8s-install[3057]: [apiclient] All control plane components are healthy after 5.503326 seconds
May 12 14:34:15 devserver systemd[1]: Started Install k8s cluster.
May 13 15:43:56 devserver systemd[1]: Starting Install k8s cluster...
May 13 15:44:17 devserver k8s-install[3155]: [apiclient] All control plane components are healthy after 5.507017 seconds
May 13 15:44:20 devserver systemd[1]: Started Install k8s cluster.
May 15 13:40:58 devserver systemd[1]: Starting Install k8s cluster...
May 15 13:41:20 devserver k8s-install[9637]: [apiclient] All control plane components are healthy after 12.003574 seconds
May 15 13:41:22 devserver systemd[1]: Started Install k8s cluster.
May 15 13:52:18 devserver systemd[1]: Starting Install k8s cluster...
May 15 13:52:39 devserver k8s-install[2972]: [apiclient] All control plane components are healthy after 5.504528 seconds
May 15 13:52:42 devserver systemd[1]: Started Install k8s cluster.
May 15 14:44:59 devserver systemd[1]: Starting Install k8s cluster...
May 15 14:45:20 devserver k8s-install[9616]: [apiclient] All control plane components are healthy after 11.003560 seconds
May 15 14:45:22 devserver systemd[1]: Started Install k8s cluster.
May 16 08:54:27 devserver systemd[1]: Starting Install k8s cluster...
May 16 08:54:48 devserver k8s-install[7570]: [apiclient] All control plane components are healthy after 14.502832 seconds
May 16 08:54:50 devserver systemd[1]: Started Install k8s cluster.
May 16 09:29:29 devserver systemd[1]: Starting Install k8s cluster...
May 16 09:29:50 devserver k8s-install[7355]: [apiclient] All control plane components are healthy after 15.002546 seconds
May 16 09:29:52 devserver systemd[1]: Started Install k8s cluster.
May 16 12:36:05 devserver systemd[1]: Starting Install k8s cluster...
May 16 12:36:26 devserver k8s-install[9638]: [apiclient] All control plane components are healthy after 14.502659 seconds
May 16 12:36:28 devserver systemd[1]: Started Install k8s cluster.
May 16 15:08:01 devserver systemd[1]: Starting Install k8s cluster...
May 16 15:08:21 devserver k8s-install[9641]: [apiclient] All control plane components are healthy after 14.502971 seconds
May 16 15:08:23 devserver systemd[1]: Started Install k8s cluster.
May 18 05:39:46 devserver systemd[1]: Starting Install k8s cluster...
May 18 05:40:05 devserver k8s-install[3201]: [apiclient] All control plane components are healthy after 7.003494 seconds
May 18 05:40:07 devserver systemd[1]: Started Install k8s cluster.
</details>


Some of the boots (the first fast ones) where with a patched kubeadm, now I' using
```
kubeadm init phase certs all --config /tmp/kubeadm.conf
kubeadm init phase kubeconfig all --config /tmp/kubeadm.conf
kubeadm init phase etcd local --config /tmp/kubeadm.conf
kubeadm init phase control-plane all --config /tmp/kubeadm.conf
kubeadm init --config /tmp/kubeadm.conf --skip-token-print \
  --skip-phases=preflight,certs,kubeconfig,etcd,control-plane
```
which also exclude preflight
The registry is local on the same server (small read only registry in golang)

Most boot pull the images again, some don't (last one doesn't).
The work on speedup starts May 12 (clearly visible)
Those boots are with 1.24.10 or 1.24.13.
I want to reiterate that the whole system is forced on 1 core (2 threads) and we are early during the boot with lots of other stuff competing for those 2 threads. The containers are not restricted and can run on the whole machine.

I'll do some tests with 1.26 & 1.27

**Comment by pacoxu** [comment]
I checked the code history, and kubelet related code is not changed recently. Only [fsnotify](https://github.com/kubernetes/kubernetes/issues/112574) is upgraded since v1.26 from v1.4.9 to v1.6.0. However, I cannot find a specific bug that fsnotify fixed. 


> Most boot pull the images again, some don't (last one doesn't).

If this is related to image pull, does the image disk have pressure? If a disk GC was triggered by kubelet before static pods start up, images will be re-pulled.

**Comment by champtar** [comment]
> I checked the code history, and kubelet related code is not changed recently. Only [fsnotify](https://github.com/kubernetes/kubernetes/issues/112574) is upgraded since v1.26 from v1.4.9 to v1.6.0. However, I cannot find a specific bug that fsnotify fixed.
> 
> > Most boot pull the images again, some don't (last one doesn't).
> 
> If this is related to image pull, does the image disk have pressure? If a disk GC was triggered by kubelet before static pods start up, images will be re-pulled.

Nothing to do with disk pressure.
This server is an appliance with ephemeral k8s cluster, ie the cluster is reinstalled at each boot.
When the appliance build version changes, we `rm -rf /var/lib/containerd`, when it's just a normal reboot we just run `crictl rmp -af / crictl rm -af`.
`/etc/kubernetes`, `/var/lib/kubernetes`, `/var/lib/cni`, `/var/lib/etcd` are either tmpfs or cleaned up on boot.
So on first boot after a new build is installed, we pull from localhost and unpack, on next boot the images are already present.

**Comment by champtar** [comment]
Still testing with 1.24.13, if I create /etc/kubernetes/manifests folder empty before running kubeadm I also gain the 20s

The timing is as follow:
- kubelet calls listConfig() and fail
https://github.com/kubernetes/kubernetes/blob/189fe3f3e6d157bc63c2276f79c3de860d7d8c57/pkg/kubelet/config/file.go#L97
```
May 18 09:06:33 devserver kubelet[3597]: E0518 09:06:33.506411    3597 file.go:98] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
```
- kubelet calls startWatch() which also fails
https://github.com/kubernetes/kubernetes/blob/189fe3f3e6d157bc63c2276f79c3de860d7d8c57/pkg/kubelet/config/file.go#L114
 https://github.com/kubernetes/kubernetes/blob/189fe3f3e6d157bc63c2276f79c3de860d7d8c57/pkg/kubelet/config/file_linux.go#L61
```
May 18 09:06:33 devserver kubelet[3597]: E0518 09:06:33.506469    3597 file_linux.go:61] "Unable to read config path" err="path does not exist, ignoring" path="/etc/kubernetes/manifests"
```
- kubeadm write down the static pods less than 1s after
```
May 18 09:06:33 devserver k8s-install[2831]: [control-plane] Using manifest folder "/etc/kubernetes/manifests"
May 18 09:06:33 devserver k8s-install[2831]: [control-plane] Creating static Pod manifest for "kube-apiserver"
```
- the file watcher starts but there are no changes happening now
- the ticker saves us after 20s
https://github.com/kubernetes/kubernetes/blob/189fe3f3e6d157bc63c2276f79c3de860d7d8c57/pkg/kubelet/config/file.go#L102-L103

**Comment by champtar** [comment]
Improved the commit message and the release notes

**Comment by pacoxu** [comment]
> I'll do some tests with 1.26 & 1.27

Any update on new version tests?

**Comment by champtar** [comment]
@pacoxu haven't done them yet. As we now have a good understanding of what is happening not sure they are needed

**Comment by pacoxu** [comment]
> @pacoxu haven't done them yet. As we now have a good understanding of what is happening not sure they are needed

As @chendave pointed out, the behavior is not expected in your env. This is really weird behavior. It would be appreciated if you could do a test with a newer version or with a patch with fsquota-1.6.0 using v1.24.

- If this proves that the `fsquota` bug causes the problem, I would like to cherry-pick it to previous releases to fix it. However, this is not reproducible in my env.

**Comment by champtar** [comment]
> > @pacoxu haven't done them yet. As we now have a good understanding of what is happening not sure they are needed
> 
> As @chendave pointed out, the behavior is not expected in your env. This is a really weird result. It would be appreciated if you could do a test with a newer version or with a patch with fsquota-1.6.0 using v1.24.
> 
>     * If this proves that the `fsquota` bug causes the problem, I would like to cherry-pick it to previous releases to fix it. However, this is not reproducible in my env.

@pacoxu reread my explanation / updated commit message. @chendave is correct that we try to start the watcher every 1s, but the watcher doesn't report existing files, so if kubeadm create the folder after the first listConfig()/doWatch(), we need to wait for the next listConfig() (20s)

**Comment by pacoxu** [comment]
> If the file change happened after kubelet start and before the startWatch(), then it may have to wait for 20s for the next loop. I just imagined an order without test.(my guess.)

So it sounds that this is what happened in your even.

**Comment by champtar** [comment]
What is missing to get this merged ?

**Comment by champtar** [comment]
> @champtar can we do something similar for join? as I mentioned the order there might be more sensitive.

In join `NewControlPlanePreparePhase()` is before `NewKubeletStartPhase()` so we are way less likely to hit the race condition (we need to be exactly between List and Watch), and this race condition needs to be fixed in kubelet IMO

**Comment by neolit123** [comment]
> > @champtar can we do something similar for join? as I mentioned the order there might be more sensitive.
> 
> In join `NewControlPlanePreparePhase()` is before `NewKubeletStartPhase()` so we are way less likely to hit the race condition (we need to be exactly between List and Watch), and this race condition needs to be fixed in kubelet IMO

the etcd manifest is written after kubelet start on join
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L155

which will delay join in theory? not sure how up to date the comment in the above location is, but we had to do it like that in the past.

**Comment by champtar** [comment]
> the etcd manifest is written after kubelet start on join https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L155
> 
> which will delay join in theory? not sure how up to date the comment in the above location is, but we had to do it like that in the past.

`/etc/kubernetes/manifests/` is created before kubelet start, so the watcher will start right away and it'll pick up the etcd manifest instantly when it's written for linux.
For other OS than Linux we don't have the watcher so it'll indeed take ~20s, but I can't really justify to my boss spending time on supporting windows :)
BTW fsnotify supports windows so better fix kubelet than risk regressions in kubeadm

**Pull request merged**
