### PR TITLE
initial subsets before compare

### PR DESCRIPTION
**Pull request by fzu-huang**
**What this PR does / why we need it**:
issue:[#42798](https://github.com/kubernetes/kubernetes/issues/42798)  endpointscontroller calls reflect.DeepEqual(currentEndpoints.Subsets , subsets) always return false because they're one initialized and another not.  
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
issue:[#42798](https://github.com/kubernetes/kubernetes/issues/42798)
**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by fzu-huang** [comment]
@k8s-ci-robot I signed it!

**Comment by deads2k** [comment]
I think you actually want to change the DeepEquals test to `apiequality.Semantic.DeepEqual`

**Comment by deads2k** [comment]
apiequality "k8s.io/apimachinery/pkg/api/equality"

**Comment by fzu-huang** [comment]
@deads2k    That's really what I want!!    I'm now wondering why don't we usethis function (`apiequality.Semantic.DeepEqual`) here?

**Comment by thockin** [comment]
Looking at this codepath - you're changing the "it doesn't exist, so fake it" path - we WANT that to fail the comparison.  Can you explain what actual problem this is causing and how to reproduce it?

**Comment by fzu-huang** [comment]
@thockin  thx for your notice. It seems that I misstook something .  I'll close this PR.

**Pull request closed without merging**
