### PR TITLE
Update nvidia-gpu-device-plugin addon image path

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As part of the [Vanity Domain Flip](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md), the old image registry (`k8s.gcr.io`) is deprecated. This PR moves the image path to a new registry. Note that the new image is still built from the same commit as the old one, so there is no functionality change. 

**Which issue(s) this PR fixes**:

Vanity Domain Flip: https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ruiwen-zhao** [comment]
The error does not seem to be relevant. And there is already effort fixing it: #96274
```
I1105 20:45:26.960] [sig-auth] ServiceAccounts
I1105 20:45:26.960] test/e2e/auth/framework.go:23
I1105 20:45:26.960]   should guarantee kube-root-ca.crt exist in any namespace [It]
I1105 20:45:26.960]   test/e2e/auth/service_accounts.go:860
I1105 20:45:26.961] 
I1105 20:45:26.961]   Nov  5 20:45:19.981: Unexpected error:
      
I1105 20:45:26.961]       <*errors.errorString | 0xc00027c1f0>: {
I1105 20:45:26.961]           s: "timed out waiting for the condition",
I1105 20:45:26.961]       }
I1105 20:45:26.961]       timed out waiting for the condition
I1105 20:45:26.961]   occurred
```

**Comment by BenTheElder** [comment]
> As part of the Vanity Domain Flip, the old image registry (k8s.gcr.io) is deprecated. This PR moves the image path to a new registry. Note that the new image is still built from the same commit as the old one, so there is no functionality change.

Huh? gcr.io/google_containers was deprecated, k8s.gcr.io is the defacto Kubernetes OSS release registry. k8s.gcr.io is NOT deprecated

**Comment by ruiwen-zhao** [comment]
> > As part of the Vanity Domain Flip, the old image registry (k8s.gcr.io) is deprecated. This PR moves the image path to a new registry. Note that the new image is still built from the same commit as the old one, so there is no functionality change.
> 
> Huh? gcr.io/google_containers was deprecated, k8s.gcr.io is the defacto Kubernetes OSS release registry. k8s.gcr.io is NOT deprecated

sorry that was a typo. Yeah gcr.io/google_containers was deprecated but k8s.gcr.io was not.

**Pull request merged**
