### PR TITLE
fix too many pdb update operations when nothing change

### LINKED ISSUE #74240: There are too many pdb update operations even if no changes take place
**What happened**:

There are too many pdb update operations compared with other resources.
image
That is, there are many "Put" operations for pdb periodically in kube-apiserver log.
```
I0212 20:35:05.923317   10957 wrap.go:42] PUT /apis/policy/v1beta1/namespaces/<namespace>/poddisruptionbudgets/<name>/status: (2.618059ms) 200 
...
```

In my view, the amount of pdb operations  is connected with disruption controller's resyncPeriod and pdb's quantity in cluster. 

For example:

disruption-controlle's default resyncPeriod is 30s,  and there are 100 pdbs in cluster.

We can find that the update operation times per minute is  about  200.

The data is reasonable, explanation is as follows: 

According to disruption-controlle's design, there is one  resync every 30s.  One resync means to call updatePdbStatus function for every pdb, so there are 200 times updatePdbStatus.  

Function updatePdbStatus  judges whether the pdb is changed. If changed, call  apiserver to update the pdb' status.

```
func (dc *DisruptionController) updatePdbStatus(pdb *policy.PodDisruptionBudget, currentHealthy, desiredHealthy, expectedCount int32, disruptedPods map[string]metav1.Time) error {
...
if pdb.Status.CurrentHealthy == currentHealthy &&
		pdb.Status.DesiredHealthy == desiredHealthy &&
		pdb.Status.ExpectedPods == expectedCount &&
		pdb.Status.PodDisruptionsAllowed == disruptionsAllowed &&
		reflect.DeepEqual(pdb.Status.DisruptedPods, disruptedPods) &&
		pdb.Status.ObservedGeneration == pdb.Generation {
		return nil
	}
...
}
```
When no eviction happens,  disruptedPods is empty.  In this situation,  disruptedPods is an empty map, but pdb.Status.DisruptedPods is nil, empty map is not equal to nil.
So reflect.DeepEqual(pdb.Status.DisruptedPods, disruptedPods) returns false.

The pdb is thought to has be changed,  then apiserver is called to update the pdb' status.  In fact, there is no change for the pdb when disruptedPods is an empty map and pdb.Status.DisruptedPods is nil.

**What you expected to happen**:
There shouldn't be so many pdb update operations. That is, when pdb has no change,  apiserver shouldn't be called to update its status.

**How to reproduce it (as minimally and precisely as possible)**:
Create some pdbs in cluster,  you will see many "Put" operations for pdb periodically in kube-apiserver log.

**Anything else we need to know?**:

**Environment**:
kubernetes v1.13.2

**Fix suggestions**:
The bug is caused by the mixed usage of empty and  nil for disruptedPods,  the type of which is map[string]metav1.Time. There are two fix suggestions for it:

1. Choose one of empty map and  nil for disruptedPods, use it consistently and refuse to mix empty map and  nil. For example,  when disruptedPods is empty or nil, save it as an empty map in etcd.  Then every client gets pdb from etcd, the pdb.Status.DisruptedPods is an empty map.  

1. After get pdb for etcd,  assign an empty map to it if pdb.Status.DisruptedPods  is nil. 

Maybe the mixed usage of  empty and nil for map is a common problem in k8s design, not just for disruptedPods. I will propose a work around solution for the problem.

If the solution has any problem, please let me know and I can modify the code.

### PR DESCRIPTION
**Pull request by snowplayfire**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:
There are too many pdb update operations even if no changes take place. The PR fix it.

**Which issue(s) this PR fixes**:

Fixes #74240

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by kow3ns — CHANGES_REQUESTED** [review]
Add a comment to indicate why you are setting the map to an empty map rather than nil.

**Comment by mortent** [comment]
This is a good catch. 

Since this change is for fixing the equals check for the disruptedPods maps, could we move the change to where we do the equality check? Maybe implement an new equals function for this line:
https://github.com/kubernetes/kubernetes/blob/c9e14c85f5b826493a2376ab4743499ac834b8ee/pkg/controller/disruption/disruption.go#L698
and just check if both maps has length 0 before doing the regular `reflect.DeepEqual` call. I think it would be more readable that way, and we won't be creating a new empty map every time.

**Comment by snowplayfire** [comment]
I got the relevant issue, ref: #43337.  It is a similar problem which is caused by the equals check for type `slice` in daemonset.

According to https://github.com/kubernetes/kubernetes/issues/43218#issuecomment-287266404, our problem takes place because we can't distinguish between `null` and `map[]` in protobuf which is the root cause.

As what I mentioned in my issue description, it is a common problem in k8s design.

@mortent    Thanks for your good suggestion.  I replaced `reflect.DeepEqual` with `Semantic.DeepEqual` here and updated related test case. Please review it.

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

**Comment by YueHonghui** [comment]
This PR has been hold for almost one month. The bug it resolves affects load of kube-apiserver and etcd obviously in large clusters. Is there anyone deal with this?

**Comment by janetkuo** [comment]
This doesn't need a release note so I removed it. This change LGTM. @snowplayfire would you squash commits into one?

**Review by janetkuo — APPROVED** [review]

**Comment by snowplayfire** [comment]
@janetkuo I have squashed commits into one.

**Comment by snowplayfire** [comment]
@janetkuo  Can you help me with the testing problem?  I get a failed test named "pull-kubernetes-integration" after I squashed commits into one, but that wasn't the case before.

**Comment by janetkuo** [comment]
/lgtm
/approve
/test pull-kubernetes-integration

I see the same failure from other PRs, so it's likely to be a flake.

**Pull request merged**
