### PR TITLE
test image: bump agnhost version to 2.30

### LINKED ISSUE #99470: ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
#### Which jobs are failing:

aks-engine-azure-windows-master-staging

#### Which test(s) are failing:

ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

#### Testgrid link:

https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-staging

#### Reason for failure:

```log
[BeforeEach] [sig-auth] ServiceAccounts
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
ï¿½[1mSTEPï¿½[0m: Creating a kubernetes client
Feb 25 05:02:27.267: INFO: >>> kubeConfig: /root/tmp027536234/kubeconfig/kubeconfig.southcentralus.json
ï¿½[1mSTEPï¿½[0m: Building a namespace api object, basename svcaccounts
ï¿½[1mSTEPï¿½[0m: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in svcaccounts-1159
ï¿½[1mSTEPï¿½[0m: Waiting for a default service account to be provisioned in namespace
[It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:640
Feb 25 05:02:27.709: INFO: created pod
Feb 25 05:02:27.709: INFO: Waiting up to 5m0s for pod "oidc-discovery-validator" in namespace "svcaccounts-1159" to be "Succeeded or Failed"
Feb 25 05:02:27.745: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 36.061638ms
Feb 25 05:02:29.782: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 2.073066085s
Feb 25 05:02:31.820: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 4.110821092s
Feb 25 05:02:33.857: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 6.148285424s
Feb 25 05:02:35.895: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 8.185556908s
Feb 25 05:02:37.932: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 10.222762671s
Feb 25 05:02:39.970: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 12.260916438s
Feb 25 05:02:42.007: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 14.298424022s
Feb 25 05:02:44.044: INFO: Pod "oidc-discovery-validator": Phase="Failed", Reason="", readiness=false. Elapsed: 16.335007708s
Feb 25 05:03:14.044: INFO: polling logs
Feb 25 05:03:14.100: INFO: Pod logs: 
2021/02/25 05:02:37 OK: Got token
2021/02/25 05:02:37 OK: got issuer https://kubernetes.default.svc.cluster.local
2021/02/25 05:02:37 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-1159:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1614229947, NotBefore:1614229347, IssuedAt:1614229347, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-1159", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"673f1367-44d6-4d18-8b06-45aa3e94d57b"}}}
2021/02/25 05:02:37 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": dial tcp: lookup kubernetes.default.svc.cluster.local: no such host
```

#### Anything else we need to know:

/sig windows
/cc @jsturtevant

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

#### What type of PR is this?

Follow-up PR for https://github.com/kubernetes/k8s.io/pull/1809, https://github.com/kubernetes/kubernetes/pull/100359, https://github.com/kubernetes/kubernetes/pull/99860
Fixes https://github.com/kubernetes/kubernetes/issues/99470

/sig windows
/kind failing-test
/priority important-soon
/test pull-kubernetes-e2e-aks-engine-conformance
/test pull-kubernetes-e2e-aks-engine-azure-windows
/test pull-kubernetes-e2e-aks-engine-windows-containerd

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/triage accepted
/approve

(Hope it sticks!)

**Comment by jsturtevant** [comment]
`pull-kubernetes-e2e-aks-engine-azure-windows` was the previously failing test and it passing!  Thanks @chewong!

/milestone v1.21

**Comment by chewong** [comment]
/assign @spiffxp 
for `build/`
Thanks!

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
