### PR TITLE
contrib: add git-sync container

### PR DESCRIPTION
**Pull request by proppy**
git-sync is a command that periodically sync a git repository to a local directory.

It can be used to source a container volume with the content of a git repo.
## Usage

```
usage:
GIT_SYNC_REPO= GIT_SYNC_DEST= [GIT_SYNC_INTERVAL= GIT_SYNC_BRANCH= GIT_SYNC_HANDLER=] \
git-sync -repo GIT_REPO_URL -dest PATH [-interval -branch -handler]"
```

In addition to the periodic pull, it will refresh sync the git repository if a HTTP request is made against `:8080/${GIT_SYNC_HANDLER}`.

### CODE REVIEW

**Comment by bgrant0607** [comment]
What's our bar for contrib?

Anyway, a good starting point would be matching our existing git volume functionality:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/volume/git_repo/git_repo.go

I'd like to eliminate that from our API and just rely on a sidecar container instead.

**Comment by proppy** [comment]
Once key difference with the existing git volume functionality is that it refresh the git repo periodically, would you rather start with a simpler approach that just populate the git repo on startup and address the question of atomic update later?

**Comment by bgrant0607** [comment]
If that would help get this in sooner, yes. :-)

**Comment by proppy** [comment]
PTAL, simplified the logic a lot, no more sync loop. Just initially populate the volume at a given rev.

**Comment by proppy** [comment]
Some notes about offline discussion with @bgrant0607 and @thockin.

There is multiple ways we can approach periodic sync w/ this sidekick container
1. add the sync logic to the git-sync program itself https://github.com/proppy/kubernetes/commit/0003d5d983c1386a697dab19b77d520354dbc840
1. like @thockin suggested make the container sleep before exiting after the git sync and rely on the pod the automatically restart it
https://github.com/GoogleCloudPlatform/kubernetes/commit/5aba5f00c0cf7dbd1b54083d559a49e47f959c53
1. add per container restart policy in pods

Additionally there is multiple ways we can synchronise the side kick with the other containers in the same pod to make sure we don't serve partial data while the first sync is in progress
1. volumes as container #1589
1. container dependencies #1996
1. atomic checkout
https://github.com/proppy/kubernetes/commit/9f37c9d4112a0311f725137b6cd0fba5db4c394d
1. git-sync advertise 'readiness' of the pod over some http endpoint (if multiple containers controls different aspect of readiness, they can advertise it on different endpoint, and another sidekick could multiplex)

I'm happy to file different issues for those ideas, but I think there is some value to discuss them in context first.

**Comment by proppy** [comment]
PTAL, added demo for usage of the container, see the [README](https://github.com/proppy/kubernetes/tree/git-sync/contrib/git-sync/demo#git-blog-demo)

**Comment by proppy** [comment]
Let me know if you'd prefer to have the two in separate PR.

**Comment by bgrant0607** [comment]
Thanks! LGTM. We should merge to make it easier for people to play with.

**Pull request merged**
