### PR TITLE
Fix golint issues in pkg/credentialprovider

### PR DESCRIPTION
**Pull request by hvaara**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint issues in `pkg/credentialprovider`

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:
As far as I can see `FakeKeyring` is no longer used anywhere. It was used in a test in dockertools (#45667)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mcrute** [comment]
Thanks for the cleanup!

/lgtm
/appove

**Comment by hvaara** [comment]
Thanks for the review @mcrute!
@deads2k can you PTAL when you have time?

**Comment by hvaara** [comment]
Looking for someone to review this. I've reached out on Slack, but not been successful so far. If this PR is not helpful, please let me know and we can just close it. Any feedback is highly appreciated! 😃 
/remove-lifecycle stale

**Comment by spiffxp** [comment]
/approve
the hack/ changes

you'll need to rebase and get someone from sig-cloud-provider to review the pkg/ changes

**Comment by hvaara** [comment]
Thanks for the review @spiffxp!
Fixed in #88860

**Pull request closed without merging**
