### PR TITLE
Update go-restful

### PR DESCRIPTION
**Pull request by brendandburns**
@lavalamp @bgrant0607 @kubernetes/goog-csi

### CODE REVIEW

**Comment by bgrant0607** [comment]
Is this to pick up a specific change?

**Comment by lavalamp** [comment]
Yes, why do we need to update? Also shippable is red.

**Comment by brendandburns** [comment]
Yeah, this is to pick up the 'Remove' command I added to go-restful (https://github.com/emicklei/go-restful/pull/226)

Previous to that you could only add services, you could never remove them.

We need it for dynamic APIs

**Comment by brendandburns** [comment]
(and Shippable is a flake, I hit it again)

**Comment by brendandburns** [comment]
(also, I think mostly tracking head on our dependencies is generally a good thing)

**Comment by bgrant0607** [comment]
But so are explanatory PR descriptions. :-)

**Comment by bgrant0607** [comment]
LGTM

**Comment by caesarxuchao** [comment]
Nice feature. Thank you @brendandburns.

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Pull request merged**
