### PR TITLE
Add extensive set of tests for federation API server init TLS generation.

### PR DESCRIPTION
**Pull request by madhusudancs**
This depends on PR #30615. Please review only the last commit here.

cc @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31856)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Does this really depend on https://github.com/kubernetes/kubernetes/pull/30615?
It will be great to have this test merged.
Can you remove all but the last commit from this PR?

**Comment by nikhiljindal** [comment]
Sorry I see now, this is adding unit test so this is closely tied to #30615.
Ignore my last comment.
Did you have a PR adding a similar e2e test as well?

**Comment by nikhiljindal** [comment]
Unassinging myself since we have decided to drop https://github.com/kubernetes/kubernetes/pull/30615 which this PR depends on.
Feel free to assign back to me if that changes

**Comment by madhusudancs** [comment]
This feature is now implemented in `kubefed`. Closing this PR.

**Pull request closed without merging**
