### PR TITLE
Automated cherry pick of #27380

### PR DESCRIPTION
**Pull request by rootfs**
Cherry pick of #27380 on release-1.2.

@maci0 @eparis

### CODE REVIEW

**Comment by eparis** [comment]
@rootfs why did you use the automated cherrypick script, as documented?

**Comment by rootfs** [comment]
@eparis there is a problem with the script, below is the error output. I am using hub 1.12

```console
To https://github.com/rootfs/kubernetes
 * [new branch]      automated-cherry-pick-of-#27380-upstream-release-1.2-1466774226 -> automated-cherry-pick-of-#27380-upstream-release-1.2
+++ Creating a pull request on github
invalid argument: -F/tmp/prtext.1M6U
```

**Comment by eparis** [comment]
ah, yeah, old version shipped in Fedora...

**Comment by maci0** [comment]
thanks :+1: :)

**Pull request merged**
