### PR TITLE
Use v1beta1 for egress selector config

### PR DESCRIPTION
**Pull request by Jefftree**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Network proxy was promoted to beta in 1.18 (https://github.com/kubernetes/kubernetes/pull/88502). Use the beta configuration for network proxy egress selector.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @caesarxuchao

### CODE REVIEW

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by caesarxuchao** [comment]
@cheftako, can you approve? Thanks.

**Pull request merged**
