### PR TITLE
GCE/Windows: ignore stopping errors for stackdriver

### PR DESCRIPTION
**Pull request by yujuhong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yujuhong** [comment]
Sometimes `stop-service stackdriverlogging` failed immediately even with -NoWait. This PR ensures that we ignore the error so that the script doesn't terminate with uncaught exceptions

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority important-longterm

**Comment by yujuhong** [comment]
`neolit123 reviewed an hour from now`

@neolit123 thanks for reviewing from the future!

**Comment by neolit123** [comment]
@yujuhong 

> @neolit123 thanks for reviewing from the future!

any time!
happy to review those PRs from the past! :D

**Comment by neolit123** [comment]
actually, let's try to retrigger the label.
> Pending — Not mergeable. Needs lgtm label.

/lgtm cancel

**Pull request merged**
