### PR TITLE
Move myself(chendave) to the list of emeritus

### PR DESCRIPTION
**Pull request by chendave**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
I was just told I should continue the efforts in the open source community, I will sync with my new boss regarding with the bandwidth and scope.

Hold for more time before leaving.

/hold

**Comment by dims** [comment]
@chendave whew!

**Comment by chendave** [comment]
/unhold

let's get this merged, looking forward to contributing this project in the future.

**Comment by pacoxu** [comment]
/lgtm

v1beta4 PR is merged 🎉 and hopefully it will be released with v1.31.0.

We look forward to the day you return to the community.

**Comment by neolit123** [comment]
thanks @chendave i will send the PR for k/k/test and also for k/kubeadm.

**Pull request merged**
