### PR TITLE
use ingress-gce-glbc v1.23.1 image for CI

### LINKED ISSUE #118295: [Flaky test] gce-master-scale-correctness
### Which jobs are failing?

master-informing
- gce-master-scale-correctness

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-network] Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow]

Screenshot from 2023-06-14 13-16-46

### Since when has it been failing?

2023-05-24 10:01 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Reason for failure (if possible)

Kubernetes e2e suite: [It] [sig-network] Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow] 
```
{ failed [FAILED] timed out waiting for service "net-tiers-svc" to have a new ingress IP: timed out waiting for the condition In [It] at: test/e2e/network/network_tiers.go:150 @ 06/12/23 18:27:38.261 }
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig scalability
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by aojea**
/kind flake
```release-note
NONE
```
FIxes: #118295

### CODE REVIEW

**Comment by aojea** [comment]
the jobs fails because this version removed the flag

```
I0614 10:00:53.429]   unknown flag: --enable-endpoint-slices
```

**Review by MrHohn — APPROVED** [review]
/lgtm

**Pull request merged**
