### PR TITLE
Make a consistent name ( GlusterFS instead of Gluster) in variables a…

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal hchiramm@redhat.com

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35669)

### CODE REVIEW

**Comment by rootfs** [comment]
lgtm
@jsafrane ?

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@jsafrane  @rootfs  Can we retrigger the tests or push to merge queue again ? The failure looks irreleveant to this PR ```W1031 01:52:08.710] E1031 01:52:08.709999   19844 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
W1031 01:52:08.710] W1031 01:52:08.710153   19844 iptables.go:143] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
W1031 01:52:08.710] W1031 01:52:08.710301   19844 iptables.go:143] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH```

**Comment by jsafrane** [comment]
@k8s-bot unit test this

**Comment by humblec** [comment]
Thanks @jsafranek.. The GCE failed with below error ~~~
W1101 02:10:19.165] E1101 02:10:19.165124    1270 remote.go:205] Failed to configured firewall: command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR 104.197.206.3 -- sudo sh -c 'iptables -L INPUT | grep "Chain INPUT (policy DROP)"&&(iptables -C INPUT -w -p TCP -j ACCEPT || iptables -A INPUT -w -p TCP -j ACCEPT)&&(iptables -C INPUT -w -p UDP -j ACCEPT || iptables -A INPUT -w -p UDP -j ACCEPT)&&(iptables -C INPUT -w -p ICMP -j ACCEPT || iptables -A INPUT -w -p ICMP -j ACCEPT)'] failed with error: exit status 1 and output:
~~~

**Comment by jsafrane** [comment]
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Adding 1.5 milestone to let it gets merged after code freeze.

**Pull request merged**
