### PR TITLE
Public read only port is incorrect in master

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes e2e failures caused by #7704

### CODE REVIEW

**Comment by smarterclayton** [comment]
@quinton-hoole @lavalamp this is the bug.

**Comment by smarterclayton** [comment]
My apologies for wasting everyones time with the e2e failures - I should have caught this during the refactor.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Merging-- not waiting for CI

**Pull request merged**
