### PR TITLE
Bump container-vm in 1.2 to container-v1-2-v20160218

### PR DESCRIPTION
**Pull request by zmerlynn**
This is a prerelease `container-vm` image with Docker 1.9.1.

### CODE REVIEW

**Comment by dchen1107** [comment]
Finally we are having prerelease image for testing now! Thanks!

LGTM

@kubernetes/goog-node

**Comment by dchen1107** [comment]
#21086

**Comment by dchen1107** [comment]
@pwittrock Can we have this pr merged manually? I want to kick out the tests against docker 1.9.1 without upgrade through salt as soon as possible, so that I can make the final decision on which docker version to go with 1.2 release. To make the final decision, I need to:

1) rule out the docker checkpoint files corruption issue completely. See https://github.com/kubernetes/kubernetes/issues/20995 for detail. 
2) rule out docker 1.9.X performance downgrade issue: see https://github.com/kubernetes/kubernetes/issues/21261 for detail

This is the last bit I want to check. Meanwhile I want to kick out another round soaking tests with https://github.com/kubernetes/kubernetes/pull/21326 which resolves https://github.com/kubernetes/kubernetes/issues/20096. Since both have the same symptoms, I want to them to run through separate build.

**Comment by pwittrock** [comment]
pr needs  a rebase

**Comment by zmerlynn** [comment]
@pwittrock: Er, not this one?

**Comment by dchen1107** [comment]
yeah, not this one; and e2e tests are passed twice above, even one for merge-bot :-(

**Comment by pwittrock** [comment]
@zmerlynn Yeah, it failed when I tried to merge so I thought that was the issue

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #21467

**Comment by pwittrock** [comment]
Guess the merge failed for some other reason though

**Comment by zmerlynn** [comment]
@pwittrock: I've seen the merge button fail if it races with merges on another PR (like maybe from the submit queue), or it might've been a status update to this PR, etc. It can be twitchy.

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #21522

**Comment by eparis** [comment]
Every time any PR merges github recalculates the mergeability of every single other PR, and the button greys out while it recalculates. We see it all the time in the merge robot, when it happens the bot just sleeps for 2 seconds and asks github if it is mergeable a second time.

**Pull request merged**
