### PR TITLE
Fix up check for min memory for parallel builds

### PR DESCRIPTION
**Pull request by jbeda**

### CODE REVIEW

**Comment by zmerlynn** [comment]
I debated if anyone cared about this fence...

**Comment by zmerlynn** [comment]
LGTM but whatever. :)

**Comment by zmerlynn** [comment]
@roberthbailey for ok-to-merge or out-of-v1

**Comment by roberthbailey** [comment]
This can wait a week.

**Comment by jbeda** [comment]
@zmerlynn I'm using boot2docker and I set it to 8G and then hit this.  Probably doesn't hit anyone building on Linux as they are >8G.

**Comment by zmerlynn** [comment]
@jbeda: Funny, I actually wrote this check because @roberthbailey couldn't build on boot2docker with a smaller footprint.

**Comment by roberthbailey** [comment]
My virtualbox VM has 2G of memory and the parallel builds definitely didn't work.

**Comment by jbeda** [comment]
I gave boot2docker 8.5G via http://stackoverflow.com/questions/24422123/change-boot2docker-memory-assignment.  8G wasn't quite enough as I think some is removed for vram.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
@k8s-bot retest this please.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
ok-to-merge

**Comment by derekwaynecarr** [comment]
This broke me building on a Fedora 21 host.

I have no idea why right now.

This was the log message I was getting with this commit:
https://gist.github.com/derekwaynecarr/7f5e013f5499da0203c8

Moving to use -gt made things work again for me.

**Comment by derekwaynecarr** [comment]
Well, I don't think your PR was the breakage.... if anything 8GB may not be enough on my box to do parallel builds properly.  I have 11GB, but I occasionally get in a state where docker daemon dies.  Either way, this PR is fine, need to debug my issue separate.

**Pull request merged**
