### PR TITLE
go.mod: github.com/Azure/go-autorest/autorest v0.11.25, /adal v0.9.18

### PR DESCRIPTION
**Pull request by thaJeztah**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- Relates to https://github.com/kubernetes/kubernetes/pull/107715
- Follow-up to https://github.com/kubernetes/kubernetes/pull/107715 (only second commit is new)

Including github.com/Azure/go-autorest/autorest/adal v0.9.18, which replaces the
now archived github.com/form3tech-oss/jwt-go package to github.com/golang-jwt/jwt/v4

    go mod graph | grep '/jwt'
    github.com/Azure/go-autorest/autorest/adal@v0.9.13 github.com/form3tech-oss/jwt-go@v3.2.2+incompatible
    github.com/auth0/go-jwt-middleware@v1.0.1 github.com/form3tech-oss/jwt-go@v3.2.2+incompatible
    k8s.io/client-go@v0.0.0 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible
    go.etcd.io/etcd/server/v3@v3.5.0 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible

Unfortunately, there's still two places where the old fork is referenced;

    go mod graph | grep 'form3tech-oss/jwt-go'
    github.com/auth0/go-jwt-middleware@v1.0.1 github.com/form3tech-oss/jwt-go@v3.2.2+incompatible
    go.etcd.io/etcd/server/v3@v3.5.0 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible

- github.com/auth0/go-jwt-middleware removes the dependency in v2 (perhaps the
  switch to the new location could still be included in a v1 patch release though)
- go.etcd.io/etcd/server/v3 removed the dependency in https://github.com/etcd-io/etcd/commit/c10d50c4b31ff300d229323e1361696a97c41dcb,
  which has not yet been released.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

/release-note-none

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dims I tried to do the updates in slightly smaller "chunks"; the first commit is from https://github.com/kubernetes/kubernetes/pull/107715 (which is why I kept this one in draft); I'm also happy to move this out of draft and close https://github.com/kubernetes/kubernetes/pull/107715  if you think they can both be reviewed (and merged) in one go.

**Comment by thaJeztah** [comment]
> go.etcd.io/etcd/server/v3 removed the dependency in https://github.com/etcd-io/etcd/commit/c10d50c4b31ff300d229323e1361696a97c41dcb,
which has not yet been released.

Just checked, but `v3.5.2` of etcd still has the old dependency; https://github.com/etcd-io/etcd/blob/v3.5.2/bill-of-materials.json#L129

**Comment by dims** [comment]
@thaJeztah let's do both together. thanks!

**Comment by thaJeztah** [comment]
works for me! moved it out of draft

**Comment by thaJeztah** [comment]
Rebased, and removed the first commit, as it was superseded by https://github.com/kubernetes/kubernetes/pull/107105

**Pull request closed without merging**
