### PR TITLE
Enabled HPA for deployment e2e

### LINKED ISSUE #15474: Implement e2e tests for horizontal pod autoscaling of deployments
We need to write e2e tests which combines horizontal pod autoscaling with deployments (scale sub-resourcer should point to a deployment object).

The tests should be similar to https://github.com/kubernetes/kubernetes/blob/master/test/e2e/horizontal_pod_autoscaling.go. The library from https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling_utils.go should be extended and allow creation of a resource consumer as a deployment (currently it is always replication controller). The new tests should create a deployment resource consumer and pass a scale-sub-resource to the deployment to autoscaler.

### PR DESCRIPTION
**Pull request by piosz**
fixes #15474

### CODE REVIEW

**Comment by piosz** [comment]
cc @xelalexv

**Comment by jszczepkowski** [comment]
Deployment is an experimental feature turned off by default, it needs to be turned on.

**Comment by piosz** [comment]
enabled deployment

**Comment by jszczepkowski** [comment]
LGTM

**Comment by jszczepkowski** [comment]
CC @xelalexv

**Pull request merged**
