### PR TITLE
Use patched golang1.7.1 for cross-builds targeting darwin

### PR DESCRIPTION
**Pull request by ixdy**
This PR extends #32517 to use the patched go1.7.1 introduced by that PR to build all darwin targets (e.g. kubectl).

This is necessary because binaries built with earlier versions of Go regularly segfault on macOS Sierra (see #32999 and #33070).

This solution is somewhat hacky, but we intend to cherry-pick this to 1.4, and switching all of 1.4 to build with go1.7.1 is very high risk.

I haven't yet pushed the cross build image yet, so this will fail to build. Will test locally and update with results.

First step of fixing #33801.

cc @luxas @pwittrock @david-mcmahon @liggitt @smarterclayton @jfrazelle @Starefossen @gerred

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33803)

### CODE REVIEW

**Comment by gerred** [comment]
@ixdy This is fantastic. Does the gcloud CLI kubectl distrubtion use anything else beyond what's OSS and available? I'd love to ensure this change is upstreamed into that tool as well.

We'll continue providing 1.3.7 binaries at Deis until GKE makes 1.4 GA. Then I don't see a need for my workaround anymore!

**Comment by ixdy** [comment]
@gerred I think the version of `kubectl` distributed by `gcloud` follows the official release supported by GKE, so it will likely update to 1.4.0 at some point in the near future. We'll probably need to cut a 1.4.1 with the go1.7.1 darwin `kubectl`, but I'm not sure how long that might take to make it through the distribution channels.

The current `kubectl` shipped by `gcloud` (1.3.7) is built with go1.6.2, so I imagine it's similarly broken on macOS Sierra right now.

**Comment by ixdy** [comment]
I've built `kubectl` off the master branch locally using this PR and have uploaded the resulting (unofficial) binaries.

Can someone with macOS Sierra test these binaries to see if they work? Based on `strings` I'm pretty sure they used go1.7.1.
http://dl.k8s.io/ci/v1.5.0-alpha.0.1705+1d22e86776bc18-jgrafton/bin/darwin/386/kubectl
http://dl.k8s.io/ci/v1.5.0-alpha.0.1705+1d22e86776bc18-jgrafton/bin/darwin/amd64/kubectl

**Comment by luxas** [comment]
Can someone please manually verify it works?
@gerred maybe?

I do not have a machine to test on

Reapplying the LGTM label... @ixdy feel free to push

**Comment by gerred** [comment]
@luxas Testing now.

**Comment by gerred** [comment]
That binary works perfectly.

**Comment by ixdy** [comment]
`kube-cross:1.6.3-8` pushed.

@k8s-bot test this
@k8s-bot build this

**Comment by pwittrock** [comment]
This failure:

>
Tag v1.6.3-8 not found in repository gcr.io/google_containers/kube-cross

**Comment by luxas** [comment]
@k8s-bot gci gke e2e test this

**Comment by ixdy** [comment]
@pwittrock which build was that from?

for some reason the GCI and Kubemark builds didn't re-trigger on my last comment.
@k8s-bot kubemark e2e test this
@k8s-bot gci gce e2e test this

**Comment by luxas** [comment]
@k8s-bot gci gce e2e test this

**Comment by luxas** [comment]
Haha, race condition between @ixdy and me :)

Let's hope everything's green now

@pwittrock When are you planning to release `v1.4.1`?

**Comment by pwittrock** [comment]
@luxas Original plan was a week from Monday (10/10).  Need to figure out if this warrants accelerating that timeline.  WDYT?

**Comment by ixdy** [comment]
We'll at least have Jenkins-built `kubectl` binaries on gs://kubernetes-release-dev/ci as soon as this gets cherrypicked.

**Comment by pwittrock** [comment]
Nice.  I can add that to the known issues in the release notes.  Anywhere else we can publish it?

**Comment by luxas** [comment]
@pwittrock If possible, I'd prefer the 5th Oct or something like that, given this and the ARM issue. As soon as some other cherrypicks that are pending like #33280, #33520 and #33806 are merged, I think you should release.

Then, already more than 20 commits have been merged since v1.4.0, and that's quite a decent amount already

WDYT about Wednesday?

**Comment by pwittrock** [comment]
@k8s-bot gci gke e2e test this

**Comment by pwittrock** [comment]
@k8s-bot unit test this

**Pull request merged**
