### PR TITLE
Automated cherry pick of #45031

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #45031 on release-1.6.

#45031: Remove too verbose label from fluentd metrics

### CODE REVIEW

**Comment by crassirostris** [comment]
@k8s-bot node e2e test this

**Comment by crassirostris** [comment]
@k8s-bot node e2e test this

**Comment by crassirostris** [comment]
Well I don't know what's wrong with this test, but it's certainly not this PR's fault

@fejta FYI

**Comment by fejta** [comment]
Well the job is definitely failing (and consistently to boot) so I don't see anything for me to do. 

Node suite is node team and namespace issues are api machinery. Contact them if you think the results are wrong? (Dawn or Daniel)

**Comment by crassirostris** [comment]
It's passed in the original PR: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45031/pull-kubernetes-node-e2e/27384/

@dchen1107 @lavalamp Have you seen this issue? Are those just flakes?

**Comment by dchen1107** [comment]
I quickly looked into all failures in #45068, #45121 and #45083, and the all volume related tests failed because volume cannot be gc properly, thus pod cannot be deleted. 

I believe we hit a known issue: https://github.com/kubernetes/kubernetes/issues/43534 which is triggered by bumping to go1.8 (https://github.com/kubernetes/kubernetes/pull/41636)

**Comment by MrHohn** [comment]
@ixdy

**Comment by dchen1107** [comment]
Checked build.log with more detail:

```
W0428 03:59:39.616] Run: ('docker', 'pull', 'gcr.io/k8s-testimages/kubekins-node:1.7-latest')
I0428 03:59:39.989] 1.7-latest: Pulling from k8s-testimages/kubekins-node
I0428 03:59:39.990] Digest: sha256:b3cc9993ddfb862bc7c7075f7cbd37fdbefbf3096df3a94ff2da4c2957517d2c
I0428 03:59:39.990] Status: Image is up to date for gcr.io/k8s-testimages/kubekins-node:1.7-latest
```
kubekins-node:1.7-latest was introduced through PR: https://github.com/kubernetes/test-infra/pull/2521/files

This proves the theory I had at https://github.com/kubernetes/kubernetes/pull/45083#issuecomment-298415541

**Comment by ixdy** [comment]
oops, small bug, easy fix in https://github.com/kubernetes/test-infra/pull/2624.

**Comment by ixdy** [comment]
@k8s-bot node e2e test this

**Comment by crassirostris** [comment]
@dchen1107 @ixdy Thanks a lot!

**Pull request merged**
