### PR TITLE
Network policy test debug and cleanup

### PR DESCRIPTION
**Pull request by jluhrsen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fixes a test bug where we are not getting debug output on failure.

**Which issue(s) this PR fixes**:

Fixes # N/A

**Special notes for your reviewer**:

none

**Does this PR introduce a user-facing change?**:

No

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
I suggest to go with the first commit by now and tackle refactors separately.

**Review by vpickard — COMMENTED** [review]
/lgtm

**Comment by aojea** [comment]
/lgtm
Thanks, nice catch
/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
