### PR TITLE
add azure disk snapshot client in azure cloud provider

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
add azure disk snapshot client in cloud provider, this client is for azure disk CSI driver, **not** for built-in azure disk driver.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
none
```

**Release note**:
```
none
```

/sig azure
/assign @feiskyer  
/priority important-soon

### CODE REVIEW

**Comment by andyzhangx** [comment]
```release-note
NONE
```

**Comment by feiskyer** [comment]
Where will be the clients used? As a lib outside?

**Comment by andyzhangx** [comment]
> Where will be the clients used? As a lib outside?

Let me reclaim this a little, when azure cloud provider is removed out from k8s core repo, it would be serving as a lib, CSI drivers( and also other Azure drivers) could use this lib directly.

https://github.com/csi-driver/azuredisk-csi-driver/blob/master/docs/design.md#implementation-details
To prevent possible regression issues, azuredisk CSI driver use azure cloud provider library. Thus, all bug fixes in the built-in azure disk plugin would be incorporated into this driver.

cc @khenidak @ritazh @justaugustus 
@brendandburns

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
