### PR TITLE
Stop setting a GKE specific version of the kubeconfig file

### PR DESCRIPTION
**Pull request by roberthbailey**
Now that the latest gcloud has been released which uses the canonical location.

/cc @jlowdermilk

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Need to wait on this one. The cloudsdk release for this week was held back.

**Comment by roberthbailey** [comment]
Really? Mine got updated today around noon.

**Comment by roberthbailey** [comment]
I just did another update and went backwards to the prior release (from 0.9.59 -> 0.9.58).

**Comment by roberthbailey** [comment]
Re-pushed with some conditional logic that should allow us to transparently pick up the new gcloud release in jenkins. Once the release is out we should rip out the extra checks and just always use the global kubeconfig location.

**Comment by jlowdermilk** [comment]
lgtm

**Pull request merged**
