### PR TITLE
Create Network Policy

### PR DESCRIPTION
**Pull request by dgofman**
https://kubernetes.io/docs/concepts/services-networking/network-policies/

NetworkPolicies are an application-centric construct which allow you to specify how a pod is allowed to communicate with various network "entities" (we use the word "entity" here to avoid overloading the more common terms such as "endpoints" and "services", which have specific Kubernetes connotations) over the network. NetworkPolicies apply to a connection with a pod on one or both ends, and are not relevant to other connections.

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Create a network policy using the kubectl create command line:
- Prevents all ingress AND egress traffic
- Create AND rules
- Create OR rules

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubectl/issues/914
https://github.com/kubernetes/kubectl/issues/1240

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dgofman** [comment]
https://kubernetes.io/docs/concepts/services-networking/network-policies/

NetworkPolicies are an application-centric construct which allow you to specify how a pod is allowed to communicate with various network "entities" (we use the word "entity" here to avoid overloading the more common terms such as "endpoints" and "services", which have specific Kubernetes connotations) over the network. NetworkPolicies apply to a connection with a pod on one or both ends, and are not relevant to other connections.

#### What type of PR is this?
/kind feature
/kind bug

#### What this PR does / why we need it:

Create a network policy using the kubectl create command line:
- Prevents all ingress AND egress traffic
- Create AND rules
- Create OR rules

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubectl/issues/914
https://github.com/kubernetes/kubectl/issues/1240

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

**Comment by aojea** [comment]
/ok-to-test
/sig network

/assign @thockin @danwinship 
WDYT?

**Comment by dgofman** [comment]
Thanks for testing. It creates a manifest based on the documentation
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by dgofman** [comment]
**kubectl create networkpolicies simple** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: simple
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies policy-np --policy-types=egress** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: policy-np
spec:
  podSelector: {}
  policyTypes:
  - Egress
status: {}
```

**kubectl create networkpolicies podselector --pod-selector=app=nginx** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: podselector
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies and-ingress-np --ingress=ports=udp:53,tcp:53,pod=app:nginx,namespace=kubernetes.io/metadata.name:default** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: and-ingress-np
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies or-ingress-np --ingress=ports=udp:53,tcp:53 --ingress=pod=app:nginx --ingress=namespace=kubernetes.io/metadata.name:default** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: or-ingress-np
spec:
  ingress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: nginx
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}

```
**kubectl create networkpolicies multirules --pod-selector app=nginx --ingress ports=udp:53,tcp:53,pod=app:nginx,app:busybox,namespace=kubernetes.io/metadata.name:default --egress ports=udp:53,pod=app:httpd:2.4-alpine --egress ports=sctp:53,pod=app:busybox** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: multirules
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          app: httpd:2.4-alpine
  - ports:
    - port: 53
      protocol: SCTP
    to:
    - podSelector:
        matchLabels:
          app: busybox
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    - podSelector:
        matchLabels:
          app: nginx
    - podSelector:
        matchLabels:
          app: busybox
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
status: {}

```

**Pull request closed without merging**
