### PR TITLE
Remove NodeAlphaFeature label from sidecar e2e tests

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This removes `NodeAlphaFeature` label from sidecar-related e2e tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers
```

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
