### PR TITLE
Support recovery for anonymous roll outs

### PR DESCRIPTION
**Pull request by brendandburns**
@jlowdermilk @bgrant0607 @smarterclayton @deads2k @ghodss 

Builds off of #7279 please only review the 2nd commit.

### CODE REVIEW

**Comment by bgrant0607** [comment]
What is this PR trying to fix/change?

**Comment by brendandburns** [comment]
Right now, if you cancel a ```---image``` based rollout with a ```ctrl-c``` you can't restart it, since it will attempt to re-create the "next" controller and fail in that attempt.

If you use an "anonymous" roll out (that is one for which the second controller is automatically generated with a hashed name) it may not recover correctly, because it doesn't know the name of the previous "next" controller, so we add an annotation to the "old" controller to make the "next" controller discoverable.

Thanks

**Comment by jlowdermilk** [comment]
Looks good. Will take second look after #7279 is merged.

**Comment by smarterclayton** [comment]
cc @ironcladlou

**Comment by jlowdermilk** [comment]
needs rebase

**Comment by brendandburns** [comment]
It's rebased and good to go (shippable is a flake, and I'm hitting it again)

**Comment by jlowdermilk** [comment]
lgtm

**Pull request merged**
