### PR TITLE
fix message

### PR DESCRIPTION
**Pull request by ruirlliu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fixed message

command

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sjenning** [comment]
/lgtm cancel
Actually, that message is still not great.

Use these:
cleared state should not have information about available cpuset
and
cleared state should not have information about containers

**Comment by louiseveryd** [comment]
/assign @sjenning 
Got it , thanks

**Comment by sjenning** [comment]
/lgtm
thanks!

**Pull request closed without merging**
