### PR TITLE
[KEP-3041]: Drop NodeSpecialFeature and NodeAlphaFeature from e2e-node

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We want to standarize our test labels to be Feature. This PR is dropping NodeSpecialFeature from the repo and a corresponding PR will drop references to this in test-infra.

#### Which issue(s) this PR fixes:

Partial https://github.com/kubernetes/test-infra/issues/33823
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/hold

Lets wait until 1.33 opens for this PR to land.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
