### PR TITLE
Deprecate Service.Spec.LoadBalancerIP

### PR DESCRIPTION
**Pull request by uablrek**
#### What type of PR is this?

/kind documentation
/kind deprecation
/sig network

#### What this PR does / why we need it:

Service.Spec.LoadBalancerIP can't be used for dual-stack services. A plural LoadBalancerIPs was proposed in [PR1992](https://github.com/kubernetes/enhancements/pull/1992). The discussions around that PR revealed that the Service.Spec.LoadBalancerIP field was under-specified and and its meaning varies across implementations. So the final proposal was to deprecate Service.Spec.LoadBalancerIP rather than introducing a plural LoadBalancerIPs.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please read the comments in  [PR1992](https://github.com/kubernetes/enhancements/pull/1992).

#### Does this PR introduce a user-facing change?

```release-note
Deprecate Service.Spec.LoadBalancerIP. This field was under-specified and its meaning varies across implementations.  As of Kubernetes v1.24, users are encouraged to use implementation-specific annotations when available.  This field may be removed in a future API version.
```

### CODE REVIEW

**Comment by aojea** [comment]
@liggitt do we need to add code for adding the warning headers? any pointer?

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by someshmalimath** [comment]
Hello,
Any idea on which version of kubernetes the field would be removed?

**Comment by uablrek** [comment]
No. But this field is not used by K8s, only cloud-providers (and metallb?), so my guess is that it will be lingering around until all cloud-providers agree to not use it, which I think will be a very long time.

**Comment by aojea** [comment]
@thockin @uablrek it seems that this fields is in use by all the cloud providers and the warning about removal is forcing them to move to annotations https://github.com/kubernetes/cloud-provider-gcp/issues/371

I don't know if we can do a breaking change like that of removing it in the future, should we relax the wording ?

**Comment by uablrek** [comment]
> it seems that this fields is in use by all the cloud providers and the warning about removal is forcing them to move to annotations

I think that's the intention. I assume no cloud provider just use the LoadBalancerIP address without other configurations as well, so this really is a cloud provider specific setting and should be an annotation.

**Comment by aojea** [comment]
But I don't think we can remove it without breaking users and keep compatibility with old clients?

```
apiVersion: v1
kind: Service
metadata:
  name:test
  namespace: default
spec:
  nonExistingField: test
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver
  type: ClusterIP
```

```
$ kubectl create -f svc2.yaml
Error from server (BadRequest): error when creating "svc2.yaml": Service in version "v1" cannot be handled as a Service: strict decoding error: unknown field "spec.nonExistingField"
```

@liggitt @thockin is realist we can remove this field without going through a large process of deprecation?
how does it deal with objects that already has the field set?

**Comment by liggitt** [comment]
Agree we would not drop the field, but marking it deprecated is fair game.

**Comment by aojea** [comment]
Just to avoid more confusion on this topic, deprecating API and remove fields on GA APIs has to obey some rules

See API changes

https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-changes

> Elimination of resources or fields requires following the [API deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/).

See the rules

https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

> > Fields of REST resources
> As with whole REST resources, an individual field which was present in API v1 must exist and function until API v1 is removed. Unlike whole resources, the v2 APIs may choose a different representation for the field, as long as it can be round-tripped. For example a v1 field named "magnitude" which was deprecated might be named "deprecatedMagnitude" in API v2. When v1 is eventually removed, the deprecated field can be removed from v2.

**Pull request merged**
