### PR TITLE
Default --ignore-not-found to true for delete --all

### LINKED ISSUE #10828: --ignore-not-found should not be needed for `kubectl delete all`
https://github.com/GoogleCloudPlatform/kubernetes/pull/8628 introduced breaking behavior to `kubectl delete all --all`

It isn't good to require users to specify `--ignore-not-found` in the normal case of deleting all replication controllers (which cascade to pods), then getting NotFound errors on previously resolved pods. Anyone who had previously scripted `kubectl delete all --all` will now get a failure.

I think `--ignore-not-found` should default to true when used with `--all`. Since the user is not specifying a particular resource name, they just want everything found removed, I think ignoring NotFound errors captures the intent.

@jlowdermilk

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #10828

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm

**Comment by yujuhong** [comment]
Needs two team leads to review this PR. /cc @bgrant0607, @thockin @brendanburns

**Comment by yujuhong** [comment]
Hmm..... @bgrant0607 just announced the API/CLI/UI freeze, and only P0 bug fixes will be considered for merge.
@liggitt @jlowdermilk, is this v1.0 blocking? If not, we should move this to post-v1.0.

**Comment by liggitt** [comment]
imo, it makes `kubectl delete all --all` unusable by default

**Comment by jlowdermilk** [comment]
It's a pretty safe change and fixes a regression. I think it should be in v1.0

**Comment by pmorie** [comment]
@liggitt Shippable build failed thusly: https://gist.github.com/pmorie/277bfafde34269899e32

**Comment by liggitt** [comment]
I don't see any interactions with the `delete` command near that failure in test-cmd.sh. Rebased and pushed to let shippable run again.

**Comment by thockin** [comment]
Like so many other changes, as innocuous as this looks, I have a hard time justifying it as P0.  I'm fine if Brian wants to disagree, but I doubt it.

**Comment by thockin** [comment]
Please add this to #10760

**Comment by wojtek-t** [comment]
@liggitt - please rebase

**Comment by liggitt** [comment]
done

**Pull request merged**
