### PR TITLE
duplicate function call

### PR DESCRIPTION
**Pull request by NickrenREN**
When we call the main function app.Run(s),at the beginning, we get the 'genericConfig' by "genericConfig := genericapiserver.NewConfig(). // create the new config
ApplyOptions(s.ServerRunOptions). // apply the options selected
Complete() "
here we call the function "(c *Config) Complete()", and then,we get the struct master by "m, err := config.Complete().New()",in the function config.Complete(),we also call "c.GenericConfig.Complete()".
Maybe we could remove the latter one, is my understanding right?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35095)

### CODE REVIEW

**Comment by mml** [comment]
@k8s-bot ok to test

**Comment by mml** [comment]
@NickrenREN looks like there's a failing unit test.

**Comment by NickrenREN** [comment]
@mml yeah, because unit test' function "TestNew(...)" in "pkg/master/master_test.go" call function "newMaster(...)"  and in function "newMaster(...)" we call "setUp(...)" . And here is the difference, in function "setUp(...)" we get the GenericConfig by "GenericConfig: genericapiserver.NewConfig()" ,we didn't call complete() function as the main function Run(...) in "cmd/kube-apiserver/app/server.go" do.
So maybe we could change the setUp() function. Is my understanding right?

**Comment by NickrenREN** [comment]
@mml  when i change the setUp(...) function as this : 
"GenericConfig: genericapiserver.NewConfig().Complete().Config,"

unit test result as follows：

go test -v k8s.io/kubernetes/pkg/master -run TestNew$
=== RUN   TestNew
2016-10-20 02:57:06.859903 I | integration: launching node7103888227188229389 (unix://localhost:node7103888227188229389.sock.bridge)
2016-10-20 02:57:06.868769 I | etcdserver: name = node7103888227188229389
2016-10-20 02:57:06.869027 I | etcdserver: data dir = /tmp.k8s/etcd312182914
2016-10-20 02:57:06.869351 I | etcdserver: member dir = /tmp.k8s/etcd312182914/member
2016-10-20 02:57:06.869576 I | etcdserver: heartbeat = 10ms
2016-10-20 02:57:06.869853 I | etcdserver: election = 100ms
2016-10-20 02:57:06.870103 I | etcdserver: snapshot count = 0
2016-10-20 02:57:06.870382 I | etcdserver: advertise client URLs = unix://127.0.0.1:21002.6511.sock
2016-10-20 02:57:06.870706 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21001.6511.sock
2016-10-20 02:57:06.870934 I | etcdserver: initial cluster = node7103888227188229389=unix://127.0.0.1:21001.6511.sock
2016-10-20 02:57:06.880901 I | etcdserver: starting member f8bd625c4e09055d in cluster df3fc051d927cc35
2016-10-20 02:57:06.881310 I | raft: f8bd625c4e09055d became follower at term 0
2016-10-20 02:57:06.881901 I | raft: newRaft f8bd625c4e09055d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-10-20 02:57:06.882306 I | raft: f8bd625c4e09055d became follower at term 1
2016-10-20 02:57:06.894949 I | etcdserver: set snapshot count to default 10000
2016-10-20 02:57:06.896071 I | etcdserver: starting server... [version: 3.0.12, cluster version: to_be_decided]
2016-10-20 02:57:06.896831 I | integration: launched node7103888227188229389 (unix://localhost:node7103888227188229389.sock.bridge)
2016-10-20 02:57:06.899310 I | membership: added member f8bd625c4e09055d [unix://127.0.0.1:21001.6511.sock] to cluster df3fc051d927cc35
2016-10-20 02:57:06.973349 I | raft: f8bd625c4e09055d is starting a new election at term 1
2016-10-20 02:57:06.973866 I | raft: f8bd625c4e09055d became candidate at term 2
2016-10-20 02:57:06.974209 I | raft: f8bd625c4e09055d received vote from f8bd625c4e09055d at term 2
2016-10-20 02:57:06.974559 I | raft: f8bd625c4e09055d became leader at term 2
2016-10-20 02:57:06.974962 I | raft: raft.node: f8bd625c4e09055d elected leader f8bd625c4e09055d at term 2
2016-10-20 02:57:06.975902 I | etcdserver: setting up the initial cluster version to 3.0
2016-10-20 02:57:06.976435 I | etcdserver: published {Name:node7103888227188229389 ClientURLs:[unix://127.0.0.1:21002.6511.sock]} to cluster df3fc051d927cc35
2016-10-20 02:57:06.977836 N | membership: set the initial cluster version to 3.0
2016-10-20 02:57:06.978344 I | api: enabled capabilities for version 3.0
2016-10-20 02:57:07.111709 I | integration: terminating node7103888227188229389 (unix://localhost:node7103888227188229389.sock.bridge)
2016-10-20 02:57:07.116578 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.117237 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.117570 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.117859 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.118237 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.118580 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.118863 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.119252 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.119615 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.120347 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.120659 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read unix localhost:node7103888227188229389.sock->@: use of closed network connection
2016-10-20 02:57:07.129949 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken read unix @->localhost:node7103888227188229389.sock.bridge: read: connection reset by peer.
2016-10-20 02:57:07.132562 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node7103888227188229389.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node7103888227188229389.sock.bridge" <nil>}
2016-10-20 02:57:07.133788 I | integration: terminated node7103888227188229389 (unix://localhost:node7103888227188229389.sock.bridge)
--- PASS: TestNew (0.27s)
PASS
ok      k8s.io/kubernetes/pkg/master    0.390s

**Comment by mml** [comment]
Whoops.  @NickrenREN removing the LGTM label until you squash the commits.

Also, the commit should include a more complete description of why you are making this change, much like the one in the PR description.

**Comment by NickrenREN** [comment]
@mml ,so sorry to bother you. I will pay attention next time.
I pull a new PR #35262 thanks a lot

**Pull request closed without merging**
