### PR TITLE
controller: fix the help information format of sorting_deletion_age_ratio metric

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
controller: fix the help information format of `sorting_deletion_age_ratio` metric

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SataQiu** [comment]
@smarterclayton
Would you mind taking a look?  It's just a simple string format bug fix.

**Comment by SataQiu** [comment]
kindly ping @soltysh

**Comment by dims** [comment]
/approve
/lgtm

just adding spaces. looks good.

**Pull request merged**
