### PR TITLE
remove TODO: There is no namespace required for node.

### PR DESCRIPTION
**Pull request by mqliang**
remove TODO: There is no namespace required for node.

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by eparis** [comment]
@ixdy looks like the merge bot found a LGTM on a non-whitelisted user non 'ok to test' PR.  So the bot added `ok to test`.   But the `ok to test` only triggered the Jenkins GCE E2E, not the Jenkins unit/integration.  Now the bot saw e2e but thought that unit/integration had been forgotten, so it went into a tizzy closing/reopening to try to get integration to run.

Seems like the `ok to test` should have told Jenkins to do both...

(To the author of this PR, I'm really really sorry my bot spammed you like CRAZY!)

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@mqliang 

It seems that the following 2 tests are failing with your PR:
integration.TestAuthModeAlwaysAllow
integration.TestAliceNotForbiddenOrUnauthorized

Can you please take a look?

**Comment by mqliang** [comment]
@wojtek-t Sorry, I can not even run unit test(build failed). It seems due to `pkg/api/types.generated.go ` files, but my PR doesn't modify it. I am not sure what's wrong.

Same problem also appeared in https://github.com/kubernetes/kubernetes/pull/17817

```
/usr/local/go/bin/go test -v k8s.io/kubernetes/test/integration -run "^TestAuthModeAlwaysAllow|TestAuthModeAlwaysDeny|TestAliceNotForbiddenOrUnauthorized|TestBobIsForbidden|TestUnknownUserIsUnauthorized|TestAuthorizationAttributeDetermination|TestNamespaceAuthorization|TestKindAuthorization|TestReadOnlyAuthorization$"
Testing started at 10:46 AM ...
# k8s.io/kubernetes/pkg/api
pkg/api/types.generated.go:127: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:140: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:142: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:152: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:165: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:167: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:177: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:190: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:192: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:202: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:202: too many errors
FAIL	k8s.io/kubernetes/test/integration [build failed]
```

**Comment by wojtek-t** [comment]
@mqliang - can you please try rebasing you PR?

**Comment by ixdy** [comment]
@eparis the e2e and unit/integration builds are configured exactly the same. I'm not sure why only one of them triggered. I suspect it may have to do with "ok to test" not being the "trigger phrase"; it usually still triggers builds, but I haven't figured out when it does or doesn't.

Also, closing/reopening the PR will *not* trigger Jenkins; that only triggers Travis and Shippable.

**Comment by mqliang** [comment]
I rebased, but still can not even run unit test due to build failed.

**Comment by ixdy** [comment]
@mqliang you're very likely now running into https://github.com/kubernetes/kubernetes/issues/17998

**Comment by wojtek-t** [comment]
@mqliang - can you please try once again (since #17998 is basically fixed now)?

**Comment by wojtek-t** [comment]
@mqliang - if you rebase your PR, it should work; if that doesn't work, can you please paste your logs (after rebasing)?

**Comment by mqliang** [comment]
@wojtek-t @ixdy 
Unfortunately failed again. It's wired.

```
➜  kubernetes git:(eventValidate) ✗ git remote update
Fetching origin
Fetching upstream
remote: Counting objects: 430, done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 430 (delta 319), reused 282 (delta 175), pack-reused 0
Receiving objects: 100% (430/430), 93.86 KiB | 22.00 KiB/s, done.
Resolving deltas: 100% (319/319), completed with 159 local objects.
From https://github.com/kubernetes/kubernetes
   0ca2182..7644d34  master     -> upstream/master
   d9ba120..3c2177c  release-1.1 -> upstream/release-1.1
➜  kubernetes git:(eventValidate) ✗ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: remove TODO: validate namespace
➜  kubernetes git:(eventValidate) ✗ go test -v k8s.io/kubernetes/test/integration
# k8s.io/kubernetes/pkg/api
pkg/api/types.generated.go:123: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:136: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:138: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:148: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:161: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:163: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:173: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:186: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:188: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:198: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:198: too many errors
FAIL	k8s.io/kubernetes/test/integration [build failed]
```

**Comment by wojtek-t** [comment]
@mqliang - for me it seems like some problem with Godeps. Maybe incorrect GOPATH, or sth like that...

Are you familiar with this:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#using-godep

**Comment by mqliang** [comment]
@thockin Great tanks for your reminding. Build succeed after updating Godeps files.

**Comment by ixdy** [comment]
@mqliang the test failures appear related to your change.

**integration.TestAuthModeAlwaysAllow**
```
auth_test.go:474: error in trying to extract resource version: unexpected error, id not found in JSON response: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "pod a does not have a host assigned",
	  "reason": "BadRequest",
	  "code": 400
	}
auth_test.go:474: error in trying to extract resource version: unexpected error, id not found in JSON response: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "pod a does not have a host assigned",
	  "reason": "BadRequest",
	  "code": 400
	}
auth_test.go:463: case {POST /api/v1/namespaces/default/events?timeout=60s 
	{
	  "kind": "Event",
	  "apiVersion": "v1",
	  "metadata": {
	    "name": "a"
	  },
	  "involvedObject": {
	    "kind": "Node",
	    "namespace": "default",
	    "name": "a",
	    "apiVersion": "v1"
	  }
	}
	 map[201:true]}
auth_test.go:464: Expected status one of map[201:true], but got 422
auth_test.go:465: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "Event \"a\" is invalid: involvedObject.namespace: invalid value 'default', Details: namespace is not required for node",
	  "reason": "Invalid",
	  "details": {
	    "name": "a",
	    "kind": "Event",
	    "causes": [
	      {
	        "reason": "FieldValueInvalid",
	        "message": "invalid value 'default', Details: namespace is not required for node",
	        "field": "involvedObject.namespace"
	      }
	    ]
	  },
	  "code": 422
	}
auth_test.go:463: case {PUT /api/v1/namespaces/default/events/a?timeout=60s 
	{
	  "kind": "Event",
	  "apiVersion": "v1",
	  "metadata": {
	    "name": "a",
	"namespace": "default"
	  },
	  "involvedObject": {
	    "kind": "Node",
	    "namespace": "default",
	    "name": "a",
	    "apiVersion": "v1"
	  }
	}
	 map[200:true]}
auth_test.go:464: Expected status one of map[200:true], but got 422
auth_test.go:465: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "Event \"a\" is invalid: involvedObject.namespace: invalid value 'default', Details: namespace is not required for node",
	  "reason": "Invalid",
	  "details": {
	    "name": "a",
	    "kind": "Event",
	    "causes": [
	      {
	        "reason": "FieldValueInvalid",
	        "message": "invalid value 'default', Details: namespace is not required for node",
	        "field": "involvedObject.namespace"
	      }
	    ]
	  },
	  "code": 422
	}
auth_test.go:463: case {GET /api/v1/namespaces/default/events/a  map[200:true]}
auth_test.go:464: Expected status one of map[200:true], but got 404
auth_test.go:465: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "events \"a\" not found",
	  "reason": "NotFound",
	  "details": {
	    "name": "a",
	    "kind": "events"
	  },
	  "code": 404
	}
auth_test.go:463: case {DELETE /api/v1/namespaces/default/events/a?timeout=60s  map[200:true]}
auth_test.go:464: Expected status one of map[200:true], but got 404
auth_test.go:465: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "events \"a\" not found",
	  "reason": "NotFound",
	  "details": {
	    "name": "a",
	    "kind": "events"
	  },
	  "code": 404
	}
auth_test.go:474: error in trying to extract resource version: unexpected error, id not found in JSON response: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Success",
	  "code": 201
	}
auth_test.go:474: error in trying to extract resource version: unexpected error, id not found in JSON response: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "the server could not find the requested resource",
	  "reason": "NotFound",
	  "details": {},
	  "code": 404
	}
```

**integration.TestAliceNotForbiddenOrUnauthorized**
```
auth_test.go:677: case {POST /api/v1/namespaces/default/events?timeout=60s 
	{
	  "kind": "Event",
	  "apiVersion": "v1",
	  "metadata": {
	    "name": "a"
	  },
	  "involvedObject": {
	    "kind": "Node",
	    "namespace": "default",
	    "name": "a",
	    "apiVersion": "v1"
	  }
	}
	 map[201:true]}
auth_test.go:678: Expected status one of map[201:true], but got 422
auth_test.go:679: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "Event \"a\" is invalid: involvedObject.namespace: invalid value 'default', Details: namespace is not required for node",
	  "reason": "Invalid",
	  "details": {
	    "name": "a",
	    "kind": "Event",
	    "causes": [
	      {
	        "reason": "FieldValueInvalid",
	        "message": "invalid value 'default', Details: namespace is not required for node",
	        "field": "involvedObject.namespace"
	      }
	    ]
	  },
	  "code": 422
	}
auth_test.go:677: case {PUT /api/v1/namespaces/default/events/a?timeout=60s 
	{
	  "kind": "Event",
	  "apiVersion": "v1",
	  "metadata": {
	    "name": "a",
	"namespace": "default"
	  },
	  "involvedObject": {
	    "kind": "Node",
	    "namespace": "default",
	    "name": "a",
	    "apiVersion": "v1"
	  }
	}
	 map[200:true]}
auth_test.go:678: Expected status one of map[200:true], but got 422
auth_test.go:679: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "Event \"a\" is invalid: involvedObject.namespace: invalid value 'default', Details: namespace is not required for node",
	  "reason": "Invalid",
	  "details": {
	    "name": "a",
	    "kind": "Event",
	    "causes": [
	      {
	        "reason": "FieldValueInvalid",
	        "message": "invalid value 'default', Details: namespace is not required for node",
	        "field": "involvedObject.namespace"
	      }
	    ]
	  },
	  "code": 422
	}
auth_test.go:677: case {GET /api/v1/namespaces/default/events/a  map[200:true]}
auth_test.go:678: Expected status one of map[200:true], but got 404
auth_test.go:679: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "events \"a\" not found",
	  "reason": "NotFound",
	  "details": {
	    "name": "a",
	    "kind": "events"
	  },
	  "code": 404
	}
auth_test.go:677: case {DELETE /api/v1/namespaces/default/events/a?timeout=60s  map[200:true]}
auth_test.go:678: Expected status one of map[200:true], but got 404
auth_test.go:679: Body: {
	  "kind": "Status",
	  "apiVersion": "v1",
	  "metadata": {},
	  "status": "Failure",
	  "message": "events \"a\" not found",
	  "reason": "NotFound",
	  "details": {
	    "name": "a",
	    "kind": "events"
	  },
	  "code": 404
	}
```

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by mqliang** [comment]
@k8s-bot ok to test

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by ixdy** [comment]
ok to test

**Comment by wojtek-t** [comment]
LGTM

**Comment by sttts** [comment]
@gmarek with https://github.com/kubernetes/kubernetes/blob/d42030170b2b20cb61cb79dff7d095998b7ee7b1/pkg/client/record/event.go#L289 this PR break all events which have a node as a target, e.g. NodeReady events from the kubelet and NodeRegistered from the node controller.

**Comment by sttts** [comment]
All those events are rejected by the apiserver.

**Comment by gmarek** [comment]
cc @mqliang who wrote this change and @wojtek-t who reviewed this. I only was the one who merged it:)

**Comment by sttts** [comment]
@gmarek all right, so only bad luck :)

**Comment by wojtek-t** [comment]
@sttts - sure - it should be namespace default there; I will send a PR fixing it soon.

**Comment by wojtek-t** [comment]
#18462 - send out for review

**Comment by sttts** [comment]
@wojtek-t thanks a lot for the utlra fast response :+1:

**Comment by sttts** [comment]
Testing with the mesos cluster.....

**Pull request merged**
