### PR TITLE
add --dns-loop-detect option to dnsmasq run by kube-dns

### LINKED ISSUE #67299: Please add --dns-loop-detect option to dnsmasq run by kube-dns
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
If hosts `/etc/resolv.conf` points to a local DNS server, or if it contains the cluster's DNS server (to enable looking up services from host), it'll cause DNS loop which can effectively disable kube-dns or make it very slow. 

**What you expected to happen**:
At least, kube-dns should detect localhost or cluster DNS server entries in resolv.conf and not send queries to them.

**How to reproduce it (as minimally and precisely as possible)**:
Use a system with local cashing DNS server, or add cluster's DNS server address to hosts resolv.conf.

**Anything else we need to know?**:
According to `dnsmasq` documentation, adding `--dns-loop-detect` should make dnsmasq detect that and disable the upstream DNS server which cause the loop. It should prevent DNS from becoming unresponsive in the first case (a better solution is to extract real upstream servers, which probably cannot be done for every configuration); and for the second case it should skip sending queries to itself and send to real upstream servers.

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67299

**Special notes for your reviewer**:
/cc @kubernetes/sig-network-pr-reviews 

**Release note**:

```release-note
add --dns-loop-detect option to dnsmasq run by kube-dns
```

### CODE REVIEW

**Comment by dixudx** [comment]
/kind bug

Kube-dns will still co-exist for several releases according to deprecation policy. We need to fix it.

**Comment by feiskyer** [comment]
LGTM.  @MrHohn could you also take a look?

/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
Did some manual testing this seems to work.

LGTMing per the explanation on https://github.com/kubernetes/kubernetes/issues/67299#issuecomment-412821821.
/lgtm

**Comment by MrHohn** [comment]
@bowei @tuminoid this might fix https://github.com/kubernetes/dns/issues/169 as well.

**Comment by dixudx** [comment]
ping @timothysc @fabianofranz for approval. Thanks.

**Review by timothysc — APPROVED** [review]
/approve 
/lgtm

**Pull request merged**
