### PR TITLE
e2e:remove unused func in /test/e2e/framework/autoscaling/autoscaling…

### PR DESCRIPTION
**Pull request by yuxiaobo96**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove unused func.

**Which issue(s) this PR fixes**:

Ref #86052 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
confirmed `EnsureDesiredReplicas()` has not been used since cb6a8a25644729b6b28db084482eaa33c23abd71

/lgtm

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
