### PR TITLE
remove kube-register and update config-default

### PR DESCRIPTION
**Pull request by doublerr**
Some updates to the Rackspace scripts that will let us run v0.18.1
- generally get things working
- use newer rackspace cloud flavor names (https://github.com/GoogleCloudPlatform/kubernetes/pull/8984 can be closed)
- update coreos (beta) image id
- use NUM_MINIONS instead of RAX_NUM_MINIONS - for the standard validation scripts
- I know scp the known_tokens file to the master. Not ideal but works for the moment.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@doublerr +1 I think we should start leveraging the node registration built into k8s going forward.

**Comment by doublerr** [comment]
@kelseyhightower ya, I removed kube-register from the rackspace cloud config in favor of the self registration. It was pretty painless as long as the nodes have the right tokens, etc. Thanks for the making kube-register though, it definitely helped until self registration was a thing.

This patch only touches the Rackspace coreos cloud config.

**Comment by erictune** [comment]
LGTM.  Thanks for the update!

**Comment by erictune** [comment]
Oncall: this should be safe to merge as it can't affect our e2es

**Comment by quinton-hoole** [comment]
@doublerr we still seem to need a CLA from you.  Is your rackspace email address associated with your github account?

**Comment by quinton-hoole** [comment]
Removing LGTM until CLA is verified.

**Comment by doublerr** [comment]
@quinton-hoole I'm on the CLA as ryan.richard@rackspace.com. I've just added the email to my profile but not sure if it needs to be primary for your scripts to catch it.

**Comment by quinton-hoole** [comment]
Thanks Ryan.  I manually verified your CLA.  To save hassle and make this automatic in future, please remind Rackspace to follow the instructions that they should have received with their CLA (setting up an appropriate Google Group with members etc).

**Pull request merged**
