### PR TITLE
Automated cherry pick of #14493

### PR DESCRIPTION
**Pull request by roberthbailey**
Cherry pick of #14493 on release-1.1.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
Re-assigning from @justinsb -> @brendandburns.

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
self merging this, since the CLA bot doesn't seem to be acknowledging the manual CLA.

**Comment by roberthbailey** [comment]
Release note: "Fix for Invalidation of DeviceMapping Cache when Detaching Volumes on AWS"

**Pull request merged**
