### PR TITLE
fix(HPA): make a difference in SuccessfulRescale  events between the resource metric and the container resource metric

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Currently, we cannot distinguish the scaling up event between type: Resource and type: ContainerResource. Both of them create the event like `memory resource utilization (percentage of request) above target` and we cannot know which is the direct reason.
This PR makes a difference in SuccessfulRescale  events between the resource metric and the container resource metric so that people can distinguish them.

#### Which issue(s) this PR fixes:

Related https://github.com/kubernetes/enhancements/issues/1610
Part of https://github.com/kubernetes/kubernetes/issues/115467

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pbetkier — APPROVED** [review]
/lgtm

**Comment by pbetkier** [comment]
I can see the custom metrics test failing on startup for some reason unrelated to your change, IMO it's safe to ignore the failure.

**Comment by sanposhiho** [comment]
😓 

/retest

**Comment by sanposhiho** [comment]
Weird. It always fails on the same test `Kubernetes e2e suite: [It] [sig-autoscaling] [HPA] [Feature:CustomMetricsAutoscaling] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) with multiple metrics of different types should not scale down when one metric is missing (Pod and Object Metrics)`.

I am guessing it's unrelated because this PR just changes the message. But, I'll look into it later. 🤔 

/retest

**Comment by pbetkier** [comment]
> Weird. It always fails on the same test `Kubernetes e2e suite: [It] [sig-autoscaling] [HPA] [Feature:CustomMetricsAutoscaling] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) with multiple metrics of different types should not scale down when one metric is missing (Pod and Object Metrics)`.
> 
> I am guessing it's unrelated because this PR just changes the message. But, I'll look into it later. 🤔
> 
> /retest

I already had a look, see https://github.com/kubernetes/kubernetes/pull/116045#issuecomment-1450004542. It’s safe to ignore :)

**Comment by gjtempleton** [comment]
I'm slightly wary of merging with a failing test (even if I agree its unrelated to this change), do we have a follow-up issue to chase the flaky test up and get that resolved?

**Comment by sanposhiho** [comment]
Let me open the issue. The hpa e2e has many flaky at the moment like https://github.com/kubernetes/kubernetes/pull/116040, we should track which test is flaky.

**Comment by sanposhiho** [comment]
`/retest` this anyway

/retest

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/issues/116315

**Comment by gjtempleton** [comment]
Ah wait, I'm not currently on the approvers under the pod autoscaler OWNERs, will need a review from @mwielgus, have added it to the SIG agenda for tomorrow along with the other PRs to ensure we get eyes on it ahead of the deadline.

**Comment by sanposhiho** [comment]
> have added it to the SIG agenda for tomorrow along with the other PRs to ensure we get eyes on it ahead of the deadline.

Thanks! 🙇

**Comment by sanposhiho** [comment]
OK, it looks some jobs are broken now... 😓 
https://github.com/kubernetes/test-infra/issues/29003

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
