### PR TITLE
test images: Remove busybox-helper image

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind cleanup

/sig windows
/sig testing

/priority important-soon

**What this PR does / why we need it**:

We cannot have any ``RUN`` commands in the Windows stage when using ``docker buildx``, which is why we were using the ``busybox-helper`` image. The purpose of the image was to contain a few things that we would obtain by running a few commands:

- symlinks for the busybox binary.
- run ``vcredist_x64.exe`` which would also give us the ``vcruntime140.dll`` which is necessary for ``dig`` or ``httpd``.

There are alternatives to the commands above that can be achieved in a Linux stage as well:

- we can create the symlinks in a Linux stage with ln -s. Copying them over to Windows will allow them to work just as well as if they were being copied over from a Windows image. The 'Files\' prefix issue to the symlink target still persists.
- we can download the ``vcruntime140.dll`` directly, allowing us to skip the ``vcredist_x64.exe`` installation.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by spiffxp — CHANGES_REQUESTED** [review]
/triage accepted

Does this require VERSION bumps?

**Comment by claudiubelu** [comment]
> 
> 
> /triage accepted
> 
> Does this require VERSION bumps?

Yep, done.

**Comment by dims** [comment]
@claudiubelu 
```
if you are changing the version of agnhost, make sure all of the following files are updated with the newest version including /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml
then run ./hack/verify-external-dependencies-version.sh
```

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu
> 
> ```
> if you are changing the version of agnhost, make sure all of the following files are updated with the newest version including /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml
> then run ./hack/verify-external-dependencies-version.sh
> ```

Oups, forgot about it, ty. :)

**Comment by justaugustus** [comment]
For `build/`:
/approve

**Pull request merged**
