### PR TITLE
Automated cherry pick of #87630: add a flag in azure auth module to omit spn: prefix in

### PR DESCRIPTION
**Pull request by weinong**
Cherry pick of #87630 on release-1.17.

#87630: add a flag in azure auth module to omit spn: prefix in

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by weinong** [comment]
/sig cloud-provider
/area provider/azure
/sig cli
/kind bug

this cherry pick is to address a bug in Azure AD auth module (#86410) which results in a claim with `spn:` prefix that is incompatible with AAD On-Behalf-Of flow among many other things described in #86410. To avoid breaking change to existing k8s customers using Azure AD (#87541), a flag in auth provider config is added.

**Comment by liggitt** [comment]
generally features are not backported to release branches

**Comment by weinong** [comment]
> generally features are not backported to release branches

@liggitt I personally believe this case is different: there was a bug in azure auth module, and the bug fix has to be implemented by adding a new flag. Does it make sense?

**Comment by weinong** [comment]
> > generally features are not backported to release branches
> 
> @liggitt I personally believe this case is different: there was a bug in azure auth module, and the bug fix has to be implemented by adding a new flag. Does it make sense?

@liggitt would you reconsider this PR based on my comment here?

**Comment by olemarkus** [comment]
We just migrated a bunch of clusters to not use `spn`. Now that this has been reverted, we are once again prevented from upgrading. This one needs to go in soon now.

**Comment by craiglpeters** [comment]
@weinong I had a quick chat with @liggitt on this. While he's skeptical about cherry picking features, he's indicated that the patch release team is responsible for branch stability. So if you can make the case that this is a critical fix that carries no risk to patch release consumers who are not on Azure, then this could be a reasonable thing to do.

**Comment by feiskyer** [comment]
I agree with @weinong, this change actually fixed a bug in azure auth module.
/ok-to-test
/lgtm

**Comment by tpepper** [comment]
At this point this cherry pick is gated by OWNERS giving approval, not patch release team.

**Comment by craiglpeters** [comment]
@liggitt see https://github.com/kubernetes/kubernetes/pull/87985#issuecomment-589455354 - can you approve?

**Comment by weinong** [comment]
> We just migrated a bunch of clusters to not use `spn`. Now that this has been reverted, we are once again prevented from upgrading. This one needs to go in soon now.

@olemarkus I just created a project https://github.com/Azure/kubelogin to use exec credential plugin. with this, you can convert your kubeconfig to exec plugin format and this tool will get AAD token without spn: prefix

**Comment by olemarkus** [comment]
> > We just migrated a bunch of clusters to not use `spn`. Now that this has been reverted, we are once again prevented from upgrading. This one needs to go in soon now.
> 
> @olemarkus I just created a project https://github.com/Azure/kubelogin to use exec credential plugin. with this, you can convert your kubeconfig to exec plugin format and this tool will get AAD token without spn: prefix

Thanks. That actually worked perfectly for me.

**Comment by liggitt** [comment]
> @liggitt see [#87985 (comment)](https://github.com/kubernetes/kubernetes/pull/87985#issuecomment-589455354) - can you approve?

Sorry for the long delay, I'm revisiting pending picks after the 1.18.0 release.

In general, we avoid picking new function back to old releases. The azure auth plugin has proven particularly fragile (with regressions indicating we don't have good test coverage). With pending issues reported even against the 1.18 changes (https://github.com/kubernetes/kubernetes/issues/89663, https://github.com/kubernetes/kubernetes/issues/89672), I don't think it's a good idea to backport new features in this area to release branches.

> @olemarkus I just created a project https://github.com/Azure/kubelogin to use exec credential plugin. with this, you can convert your kubeconfig to exec plugin format and this tool will get AAD token without spn: prefix

I think this is actually a great direction for the azure auth integration. I'd like to see both of the cloud-specific auth plugins (azure and gcp) move to exec-based plugins. The openstack auth plugin already did this in https://github.com/kubernetes/kubernetes/pull/89014. If the external auth plugin can address the need to use spn-less azure credentials on older kubectl releases, I would recommend that and close #87985, https://github.com/kubernetes/kubernetes/pull/87986, and https://github.com/kubernetes/kubernetes/pull/87987

**Comment by olemarkus** [comment]
Makes sense. I am happy with that.

**Comment by weinong** [comment]
@liggitt you can close these cherry picks. we will focus on the exec based plugin

**Comment by liggitt** [comment]
sounds good, thanks

**Pull request closed without merging**
