### PR TITLE
Automated cherry pick of #77282: Bump addon-manager to v9.0.1

### PR DESCRIPTION
**Pull request by MrHohn**
Cherry pick of #77282 on release-1.14.

#77282: Bump addon-manager to v9.0.1 - Rebase image on

```release-note
Bump addon-manager to v9.0.1
- Rebase image on debian-base:v1.0.0
```

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm

**Comment by MrHohn** [comment]
Thanks all for your quick response :)

**Pull request merged**
