### PR TITLE
Cleanup legacy scheduler perf tests

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind cleanup
/sig scheduling
/sig scalability

A follow-up of https://github.com/kubernetes/test-infra/pull/26108#discussion_r859468110

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/hold
for https://github.com/kubernetes/test-infra/pull/26108 to be merged first.

**Comment by wojtek-t** [comment]
This is great - thanks!

/lgtm
/approve

**Comment by sanposhiho** [comment]
We also need to modify this doc as well? 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduler_benchmarking.md

**Comment by Huang-Wei** [comment]
@sanposhiho yup, created https://github.com/kubernetes/community/issues/6634 to track doc changes.

**Pull request merged**
