### PR TITLE
Allow headless services with type LoadBalancer for specialized proxiers

### LINKED ISSUE #115429: Allow type LoadBalancer for Headless service for specialized proxiers
## Feature requested

Allow type LoadBalancer for Headless service for specialized proxiers. A service of type LoadBalancer with clusterIP None is rejected with:

```
# kubectl create -f /etc/kubernetes/svc-headless-lb/svc.yaml 
The Service "alpine" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
```
Even if the [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) label is used.

<details><summary>manifest</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: alpine
  labels:
    service.kubernetes.io/service-proxy-name: kpng-example
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine
  type: LoadBalancer
  clusterIP: None
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: nc
```

</details>

This is just a check, not that anything fails if the combination is allowed.

I want that check removed for specialized proxiers.

## Why?

A specialized proxier using the [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) label may handle external traffic, while it can't handle internal traffic to the `ClusterIP`. For such a service the combination `type:LoadBalancer` and `clusterIP:None` makes perfect sense. Otherwise one must document something like:

> Even though the clusterIP is defined with valid endpoints, **you can't use it** since the specialized proxier don't care about clusterIP.

Access to the service via DNS addresses which (provided for Headless services) is proably something the service _can_ handle, which make this feature _valuable_ and not just a cosmetic thing.

An example has been [discussed](https://github.com/kubernetes/enhancements/pull/2611#issuecomment-819125885) in the "All-IP service" context, and [considered breaking](https://github.com/kubernetes/enhancements/pull/2611#issuecomment-822063553). If the restriction is removed for specialized proxiers only, this will not be a problem.

/kind feature
/sig network

### PR DESCRIPTION
**Pull request by uablrek**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Allow the combination `type: LoadBalancer` + `clusterIP: None` for services if a specialized proxy is used.

This combination is useful for specialized proxiers that only handles external traffic. I believe this to be the most common use-case for specialized proxiers.

#### Which issue(s) this PR fixes:

Fixes #115429

#### Special notes for your reviewer:

The restriction is lifted for _specialized proxiers only_, i.e. for services with the [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) label defined.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
these kind of changes usually require a KEP and a feature gate, since we are changing the validation changes on the API, similar to 

https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1864-disable-lb-node-ports
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1435-mixed-protocol-lb

**Comment by uablrek** [comment]
I altered the issue and this PR to affect _specialized proxiers only_.

**Comment by uablrek** [comment]
Example:
```
# kubectl get svc alpine
NAME     TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
alpine   LoadBalancer   None         fd00::1000    5001/TCP   2m9s
# kubectl exec alpine-65f85598fb-9qxq7 -- nslookup alpine
Server:         192.168.1.1
Address:        192.168.1.1:53

** server can't find alpine.cluster.local: NXDOMAIN

** server can't find alpine.cluster.local: NXDOMAIN

Name:   alpine.default.svc.cluster.local
Address: 1100::102
Name:   alpine.default.svc.cluster.local
Address: 1100::402
Name:   alpine.default.svc.cluster.local
Address: 1100::302
Name:   alpine.default.svc.cluster.local
Address: 1100::202

Name:   alpine.default.svc.cluster.local
Address: 11.0.1.2
Name:   alpine.default.svc.cluster.local
Address: 11.0.4.2
Name:   alpine.default.svc.cluster.local
Address: 11.0.3.2
Name:   alpine.default.svc.cluster.local
Address: 11.0.2.2
```

**Comment by uablrek** [comment]
Closing since the issue is closed.

/close

**Pull request closed without merging**
