### PR TITLE
Update to etcd v3.5.0 client

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

```release-note
NONE
```

/cc @dims

### CODE REVIEW

**Comment by dims** [comment]
/priority important-soon
/triage accepted

/approve
/lgtm

we just merged rc0, this has some bumps of deps, but feels like this should be good!

**Comment by pacoxu** [comment]
Need to fix failures in `pull-kubernetes-verify`

/hold 
to avoid auto-retest

**Pull request merged**
