### PR TITLE
Remove duplicate dependencies from 1.22 changelog

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The dependencies have been added twice because they were already part of
the release notes draft:

https://github.com/kubernetes/sig-release/blob/master/releases/release-1.22/release-notes/release-notes-draft.md

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/release-managers PTAL

**Review by cpanato — APPROVED** [review]
from RelEng:
/lgtm

**Comment by saschagrunert** [comment]
Has to be cherry-picked to release-1.22

**Comment by cpanato** [comment]
@saschagrunert I can cherry pick that, is that ok?

**Comment by saschagrunert** [comment]
> @saschagrunert I can cherry pick that, is that ok?

Sure

**Pull request merged**
