### PR TITLE
Remove hack/e2e-test.sh in favor of hack/e2e.go.

### PR DESCRIPTION
**Pull request by spxtr**
This was only actually called in one place within the codebase, `make e2e_test`. The rest is just updating documentation.

It might be the case that other people are using this script for their CI. It's a simple change to use `make e2e_test` or `go run hack/e2e.go ...` instead, and I think it's valuable to support fewer test entrypoints.

### CODE REVIEW

**Comment by spxtr** [comment]
@k8s-bot unit test this again issue #21257

**Comment by ixdy** [comment]
@kubernetes/sig-testing is anyone using `hack/e2e-test.sh`?

**Comment by spiffxp** [comment]
+1, not using `hack/e2e-test.sh` over here

**Comment by ixdy** [comment]
LGTM

**Comment by spxtr** [comment]
@k8s-bot unit test this issue #21451

**Comment by lavalamp** [comment]
Awesome! \o/

**Pull request merged**
