### PR TITLE
Revert "fix cluster/log-dump/log-dump.sh shellcheck failures"

### PR DESCRIPTION
**Pull request by mm4tt**
This reverts commit 742701622abe36e4e8914db168c1ff926f479da6.

It broke log dumping, see https://github.com/kubernetes/kubernetes/pull/88349#issuecomment-688385378

/kind bug

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
sorry I actually stayed offline yesterday and hadn't heard any reports of anything like this previously :|

**Comment by BenTheElder** [comment]
Thanks for fixing

**Comment by joakimr-axis** [comment]
Possible cause of this issue: https://github.com/kubernetes/kubernetes/pull/88349#issuecomment-689603848

**Comment by joakimr-axis** [comment]
Suggested fix for the issue causing the revert: #94762

**Pull request merged**
