### PR TITLE
fix generator_for_scheme: remove blank new line

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

1. remove new blank line in `AddToScheme`
https://github.com/kubernetes/kubernetes/blob/80e344644e2b6222296f2f03551a8d0273c7cbce/pkg/client/clientset_generated/internalclientset/fake/register.go#L81-L83

2. remove new blank line in `Install`
https://github.com/kubernetes/kubernetes/blob/3d69cea1e589add1d24fc72e9a8c46081664a719/staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/internalclientset/scheme/register.go#L44-L47

**Special notes for your reviewer**:

the first commit changes the code generator for schema register.
https://github.com/kubernetes/kubernetes/commit/c8c9ca77af97381e8d6e0d1592751f6e88ae9780 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
/assign @deads2k @DirectXMan12 

for (trivial) approval of the generated code changes.

**Comment by hzxuzhonghu** [comment]
resolve conflicts
/assign @caesarxuchao

**Pull request merged**
