### PR TITLE
Fix lint on pkg/kubelet/server/...

### PR DESCRIPTION
**Pull request by alculquicondor**
/kind cleanup

**What this PR does / why we need it**:
Fix lint issues on `pkg/kubelet/server` and subpackages  (#68026).

* Add docstrings were appropriate.
* Unexport symbols were appropriate.
* Rename symbols were appropriate, according to https://github.com/golang/go/wiki/CodeReviewComments#initialisms and
https://github.com/golang/go/wiki/CodeReviewComments#package-names

```release-note
NONE
```

/assign @vishh

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @alculquicondor 

/ok-to-test
/priority backlog

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
thanks

**Review by vishh — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
