### PR TITLE
Automated cherry pick of #106455: Add warning about using unsupported CRON_TZ

### PR DESCRIPTION
**Pull request by soltysh**
Cherry pick of #106455 on release-1.22.

#106455: Add warning about using unsupported CRON_TZ

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by soltysh** [comment]
@kubernetes/release-managers for cherry-pick approval

**Comment by puerco** [comment]
Thank you @soltysh !
/lgtm

**Pull request merged**
