### PR TITLE
Kubelet report False runtime status while restart

### PR DESCRIPTION
**Pull request by aoxn**
Fix https://github.com/kubernetes/kubernetes/issues/71839

When we restart kubelet , we found that kubelet post NodeNotReady status imediately. This would result in cloud-controller-manager removing Loadbalancer backend imediately which is not expected.

After go through the kubelet log, we found that kubelet report container runtime is down but actually it is up. That is kubelet report a false container runtime status while restart , and that is not expect.

For now, this has a tremendous impact on our CloudProvider.

After some dig into the code, we found that kubelet detect container runtime status and report the runtime status councurrently. This is the main cause of the false status report.

### CODE REVIEW

**Comment by aoxn** [comment]
@andyzhangx  Is this fixed in somewhere or?  Why is this closed?

**Comment by andyzhangx** [comment]
@aoxn there are 250+ commits in this PR, is this an expected PR?

**Comment by aoxn** [comment]
No, Thanks.

**Pull request closed without merging**
