### PR TITLE
Add Microsoft OMS (Operations Management Suite) monitoring DaemonSet example

### PR DESCRIPTION
**Pull request by OguzPastirmaci**
Adds example to deploy Microsoft OMS monitoring agents using Daemon Sets.

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot ok to test.

**Comment by brendandburns** [comment]
Thanks for this PR. While it's great to have this in the examples, it would be even better to have it in the main site:

https://github.com/kubernetes/kubernetes.github.io

Feel free to do a PR there too and tag me into it.

Thanks!
--brendan

**Comment by OguzPastirmaci** [comment]
Will do that one as well, thanks!

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by zmerlynn** [comment]
/approve

@brendandburns: The parser is still strict, `/approve` has to be on the first line. (But the other order of your comment works.)

**Comment by edevil** [comment]
I've noticed this daemonset example, but is it possible for the oms agent to augment the logging with kubernetes specific information such as pod name, namespace, tags, etc?

A bit like https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter does.

**Pull request merged**
