### PR TITLE
Automated cherry pick of #15427 upstream release 1.1

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
Cherry pick for #15402

**Comment by lavalamp** [comment]
Oh, this doesn't even compile, I need to cherry pick another change, too.

**Comment by lavalamp** [comment]
OK, fingers crossed, I think I have this cherrypick working.

**Comment by lavalamp** [comment]
@brendandburns This was a huge pain to cherry-pick =P

Shippable seems to just not have run, I kicked it.

**Comment by mikedanese** [comment]
After this cherrypick, the controllermanager on release branch is running two DaemonSetsControllers and two JobControllers.

**Pull request merged**
