### PR TITLE
use assertions for scheduler unit tests under predicates package

### PR DESCRIPTION
**Pull request by adshmh**
**What this PR does / why we need it**:
Replaces the checks done in unit tests with assertions, for the package: plugin/pkg/scheduler/algorithm/predicates

Please refer to #43788 for a discussion/list of reasons for using assertions in the unit tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Part of work on #43788

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adshmh** [comment]
CLA should be OK now.

**Comment by adshmh** [comment]
Pushed a signed commit to fix the CLA issue.

**Comment by adshmh** [comment]
Could you please leave the PR open? I fixed the CLA issue.

**Comment by adshmh** [comment]
rebased the PR.

**Comment by jayunit100** [comment]
should we rebase this PR?

**Comment by adshmh** [comment]
@jayunit100 Thanks for updating. I rebased it previously, but got into conflicting status while waiting for review. I will rebase it again.

**Comment by adshmh** [comment]
@jayunit100 sorry for the delay. The PR has been rebased.

**Comment by resouer** [comment]
It's fine to have this, I will give a pass after CI is green.

**Comment by adshmh** [comment]
@resouer Would appreciate it if you could take a look.

**Comment by jayunit100** [comment]
this looks good to me.  these unit testa are way more readable this way.

**Comment by misterikkit** [comment]
@adshmh Thanks for being so patient on this PR. It looks like this needs one more rebase to merge.

**Pull request closed without merging**
