### PR TITLE
fixtypo 

### PR DESCRIPTION
**Pull request by x1957**
**What this PR does / why we need it**:
fix typo seperated -> separated

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/lgtm

**Comment by x1957** [comment]
@k8s-bot unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
ping @dchen1107 for approval

**Comment by x1957** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by x1957** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by x1957** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by x1957** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by cblecker** [comment]
.

**Pull request merged**
