### PR TITLE
Update kube dns

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Updates kube-dns to 1.14.5
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
LGTM for cluster/addons/dns

**Comment by ixdy** [comment]
I don't think the image has been pushed yet, so tests will fail until that's done.

**Comment by thockin** [comment]
/lgtm

@jdumars

**Comment by ixdy** [comment]
This needs the cherry-pick approved label in order to merge.

**Comment by abgworrall** [comment]
Adding retest-not-required; we need to expedit this cherrypick through the backed up submit queue, if we're to cut a release today.

**Comment by luxas** [comment]
Thanks! Where is the release notes for kube-dns BTW so one can check what's changed?

**Pull request merged**
