### PR TITLE
use a stable release for network policies

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup

```release-note
NONE
```

following up on previous comment from BenTheElder, we should not get artifacts from staging for CI

### CODE REVIEW

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-network] Services should create endpoints for unready pods 

/test pull-kubernetes-e2e-gce-network-policies

unrelated failure
/hold cancel

**Comment by dims** [comment]
/approve
/lgtm

+1 to fixing to stable release tag

**Comment by BenTheElder** [comment]
thanks!

**Pull request merged**
