### PR TITLE
capitalize the struct elements comments in componentconfig

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

correct the case-sensitive letters in the comment

### CODE REVIEW

**Comment by justinsb** [comment]
Unclear (to me) whether these are supposed to follow go comment style, or whether we want them to reflect the JSON names.

**Comment by dixudx** [comment]
@justinsb They should explain go struct elements. So they should be in capitalization

**Comment by mikedanese** [comment]
These are supposed to refelect the json names.

**Pull request closed without merging**
