### PR TITLE
Fix linting issues in pkg/kubectl/cmd/version

### PR DESCRIPTION
**Pull request by thesattiraju**
Signed-off-by: ds-ms <desattir@microsoft.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix linting issues in pkg/kubectl/cmd/version

**Which issue(s) this PR fixes**:

Fixes #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ds-ms** [comment]
I have signed the CLA

**Review by neolit123 — COMMENTED** [review]
thank you for the PR @ds-ms 
this change needs approval by SIG CLI.

/ok-to-test
/priority backlog

**Comment by ds-ms** [comment]
Looks like there are some flaky tests, calling retest again. 
/retest

**Comment by spiffxp** [comment]
/approve
for hack/
/lgtm

/assign @seans3 @monopole 
for pkg/kubectl/OWNERS approval

**Comment by ds-ms** [comment]
@seans3 @monopole could you take a look at this PR

**Comment by spiffxp** [comment]
pinged #sig-cli

**Pull request merged**
