### PR TITLE
fix inplace VPA stuck in InProgress when custom resources are specified

### PR DESCRIPTION
**Pull request by LingyanYin**
added unit tests

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

It fixed an issue that when there is custom resources in the spec and ResourceAllocated, the Resize will be always InProgress
Below shows the doc link, and this PR is to fix the 4th item
https://docs.google.com/document/d/1V3DLh3pH3CD-xhhJvAnOq_oWgPyjO-vj6wY6qdew9H0/edit#heading=h.rmrvhjuvstl3

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
@Jeffwan

### CODE REVIEW

**Comment by bart0sh** [comment]
@LingyanYin Thank you for your PR. Please [sign the CLA](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet#signing-the-cla) to proceed further, thanks.

**Comment by LingyanYin** [comment]
> @LingyanYin Thank you for your PR. Please [sign the CLA](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet#signing-the-cla) to proceed further, thanks.

Hi @bart0sh all authors for this PR have signed the CLA via EasyCLA, but it seems it's not working... it still shows Missing CLA Authorization (we even tried to close and reopen the PR), do you happen to know why this happens or how can we make it work?

**Comment by bart0sh** [comment]
@LastNight1997 Usually it works. Please, try to sign the CLA again.

**Comment by bart0sh** [comment]
@LingyanYin did you check [CLA robot response](https://github.com/kubernetes/kubernetes/pull/120145#issuecomment-1690800466) and followed its suggestions?

**Comment by LingyanYin** [comment]
> @LingyanYin did you check [CLA robot response](https://github.com/kubernetes/kubernetes/pull/120145#issuecomment-1690800466) and followed its suggestions?

Sorry, I thought I resolved this email address issue, but it seems I didn't. I just updated it again and now it works! Thanks Ed.

**Review by Jeffwan — APPROVED** [review]
The change looks good to me. We've tested it in downstream distribution and it's working fine.

**Comment by Jeffwan** [comment]
@vinaykul @mrunalp Do you get chance to look at the improvement?

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by vinaykul** [comment]
/lgtm
Please add e2e test for this (can be a follow up PR)

**Comment by vinaykul** [comment]
@mrunalp @SergeyKanzhelev please add 1.29 milestone label, thanks

**Comment by pacoxu** [comment]
/milestone v1.29
approved before code freeze

**Comment by MaryamTavakkoli** [comment]
Hello!
Bug triage for the 1.29 release cycle is here!
The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)). as we want to ensure that each PR has a chance to be merged.

Are we still targeting the 1.29 release?

**Comment by vinaykul** [comment]
> Are we still targeting the 1.29 release?
Yes. The merge was just held up by missing milestone and a hiccup in pull job. I've added it to the description of https://github.com/kubernetes/enhancements/issues/1287

**Comment by Jeffwan** [comment]
@MaryamTavakkoli 

Yes, can we file an exception to include this change?

**Comment by MaryamTavakkoli** [comment]
> @MaryamTavakkoli
> 
> Yes, can we file an exception to include this change?

I think this should be good since it is already merged, but maybe @hailkomputer can confirm.

**Pull request merged**
