### PR TITLE
update comment

### PR DESCRIPTION
**Pull request by goushicui**
#### What type of PR is this?
Update code comments，pod volume path: /pods/{podUid}/volumes/{escapeQualifiedPluginName}/{volumeName}

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Review by SergeyKanzhelev — APPROVED** [review]
this is indeed misleading

/lgtm

**Comment by SergeyKanzhelev** [comment]
oh, this needs a rebase. Please re-open once rebased

/close

**Comment by goushicui** [comment]
@SergeyKanzhelev re-open here https://github.com/kubernetes/kubernetes/pull/114701 thks

**Pull request closed without merging**
