### PR TITLE
Revert/disable the slash syntax for kubectl explain group/version

### PR DESCRIPTION
**Pull request by janetkuo**
Partially fixes - #16039

cc @bgrant0607 @caesarxuchao

### CODE REVIEW

**Comment by bgrant0607** [comment]
Please reconcile with #16054

**Comment by JanetKuo** [comment]
#16054 reverts the support for group/resource in resource builder, and this PR disables/reverts the support for group/resource for `kubectl explain` (it doesn't use resource builder). So we need both PRs. cc @smarterclayton

**Comment by caesarxuchao** [comment]
yes, we need both. Thank you @JanetKuo. LGTM.

**Comment by JanetKuo** [comment]
Just realized that `kubectl explain` isn't in 1.1. So we don't need to cherry-pick this.

**Comment by JanetKuo** [comment]
Just realized that `kubectl explain` isn't in 1.1. So we don't need to cherry-pick this. Just revert it in HEAD.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
