### PR TITLE
cleanup: remove assert libraries

### PR DESCRIPTION
**Pull request by demoManito**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove assert libraries, avoid the use of assert libraries to help your tests, so I want to refactor the tests that are done using assertions

standard: 
https://github.com/golang/go/wiki/TestComments#assert-libraries
https://github.com/golang/go/wiki/TestComments#compare-full-structures

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Because ` gce_loadbalancer_external_test.go`、`gce_loadbalancer_internal_test.go` there are many changes to go. I intend to put the remaining changes to this file in another pr (including the changes to `go.mod` and `go.sum`) for the convenience of codereview.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by feroenmmek — APPROVED** [review]

**Comment by demoManito** [comment]
@feroenmmek Hello, can you assign /lgtm to this PR?

**Comment by demoManito** [comment]
@andrewsykim Please review the PR, thank you

**Review by endocrimes — CHANGES_REQUESTED** [review]
I'd air on the side of closing this, but right now this actually provides less information than we previously got from testify. Testify provides information about _what_ an unexpected result is, which can be useful when triaging and debugging tests.

Otherwise it's mostly change for the sake of change, and a lot of extra verbosity, with no behaviour change - which is relatively unhelpful.

**Pull request closed without merging**
