### PR TITLE
Automated cherry pick of #17392

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #17392 on release-1.1.

### CODE REVIEW

**Comment by ixdy** [comment]
Hoping this fixes #16828.

@kubernetes/goog-testing

**Comment by jlowdermilk** [comment]
lgtm

**Comment by ixdy** [comment]
Accidentally pulled in part of #16269. Removed that, so hopefully things will build now.

**Comment by ixdy** [comment]
Looks like unit tests are broken on 1.1 right now. :(

**Comment by ihmccreery** [comment]
(@ixdy I attempted to add a kubernetes-test-go-release-1.1 to Jenkins last week, but disabled it because it wasn't working.  Maybe worth pursuing?)

**Comment by ixdy** [comment]
@ihmccreery "fixed" the unit test build, also opened #17693 to fix the broken test.

**Comment by wojtek-t** [comment]
Unit tests are failing with the following error:

    11:07:11 _output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:256: too many arguments in call to WaitFor

@ixdy Can you please rebase (it should fix it)

**Comment by ixdy** [comment]
Rebased. After #17750 changes to hack/jenkins/e2e.sh are no longer needed, so that got dropped from the diff.

**Comment by ixdy** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
