### PR TITLE
Fixing federation event e2e test

### LINKED ISSUE #30644: [k8s.io] Federation events [Feature:Federation] Event objects should be created and deleted successfully {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/3002/

Failed: [k8s.io] Federation events [Feature:Federation] Event objects should be created and deleted successfully {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federation-event.go:60
Creating event "federation-event" in namespace "e2e-tests-federation-event-8fasv"
Expected error:
    <*errors.StatusError | 0xc82072e480>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "Event \"federation-event\" is invalid: involvedObject.namespace: Invalid value: \"default\": does not match involvedObject",
            Reason: "Invalid",
            Details: {
                Name: "federation-event",
                Group: "",
                Kind: "Event",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"default\": does not match involvedObject",
                        Field: "involvedObject.namespace",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    Event "federation-event" is invalid: involvedObject.namespace: Invalid value: "default": does not match involvedObject
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federation-event.go:91
```

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/30644

cc @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30725)

### CODE REVIEW

**Comment by madhusudancs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30725#-:-KPLF3yQAn4oM6UjmxzF:bnfp4nl)*

**Comment by madhusudancs** [comment]
@nikhiljindal Thanks!

**Comment by nikhiljindal** [comment]
Making this P1, since it fixes a broken test

**Comment by nikhiljindal** [comment]
@k8s-bot gce e2e test this issue: #IGNORE

**Comment by madhusudancs** [comment]
@k8s-bot gce e2e test this issue: #IGNORE

**Comment by nikhiljindal** [comment]
sigh, nothing seems to be working.
@k8s-bot e2e test this issue: #IGNORE

**Pull request merged**
