### PR TITLE
correct the value of atomicMutatingLen

### PR DESCRIPTION
**Pull request by kdada**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Correct the value of atomicMutatingLen.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kdada** [comment]
@yue9944882 @MikeSpreitzer  PTAL

**Review by MikeSpreitzer — APPROVED** [review]
Yeah, I do not know how this bug lasted this long.

**Comment by MikeSpreitzer** [comment]
Also fixed in #91389 , BTW.

**Comment by kdada** [comment]
> Also fixed in #91389 , BTW.

#91177 

/close

**Comment by yue9944882** [comment]
it's an awkward oversight and yes it implies lacking of test coverage in terms of metrics, however metrics are now test'able via some utilities under component-bsae, prior art:

https://github.com/kubernetes/kubernetes/blob/0e37bcce2cefb3005d10d805bc37b573937c7eda/pkg/kubelet/server/stats/prometheus_resource_metrics_test.go#L189-L193

**Pull request closed without merging**
