### PR TITLE
Minor adjustments to descriptions and example text

### PR DESCRIPTION
**Pull request by bergerhoffer**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Cleans up text so that kubectl command descriptions (long and short) and examples are consistent and for minor grammar changes. For example, updated so that short descriptions and examples do not use ending punctuation, but long descriptions do. (This is the format that is followed in most cases, just updating those that weren't to follow this pattern)

Also added an example for certificate deny/approve commands.

#### Does this PR introduce a user-facing change?

```release-note
Updated command descriptions and examples for grammar and punctuation consistency.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/ok-to-test
/priority backlog
/triage accepted
/assign

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
Thanks for this one @bergerhoffer this is huge :100:

**Comment by dougsland** [comment]
Timeout error, not related to PR.
/retest
/lgtm

**Pull request merged**
