### PR TITLE
Prefer fetched version when determining HPA group version kind

### PR DESCRIPTION
**Pull request by liggitt**
Related to #22484 for `kubectl get <type>` list cases

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, thanks!

We should look closely at other InfoForObject() calls as well and see if we can pass meaningful preferredGVKs. We should return an error if we cant rather than silently choosing a random one.
This is strictly better than the current state since it atleast fixes `kubectl get`.

**Comment by nikhiljindal** [comment]
cc @deads2k

**Comment by liggitt** [comment]
agree that it doesn't close #22484

**Comment by bgrant0607** [comment]
Manually merging.

**Comment by eparis** [comment]
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.

**Pull request merged**
