### PR TITLE
Update cassandra example according to config best practices

### PR DESCRIPTION
**Pull request by linzichang**
related to #11361

### CODE REVIEW

**Comment by bgrant0607** [comment]
Awaiting resolution of #14256

**Comment by bgrant0607** [comment]
@linzichang Please rebase and squash the commits. I'd like to get this in before more significant changes.

**Comment by bgrant0607** [comment]
cc @jeffmendoza @amygdala

**Comment by janetkuo** [comment]
@k8s-bot ok to test

**Pull request merged**
