### PR TITLE
Update AppArmor e2e tests to use both containers[*].securityContext.appArmorProfile field and annotations.

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates the AppArmor e2e tests to use `containers[*].securityContext.appArmorProfile` field in addition to the annotation to test AppArmor support of Kubernetes.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm
/approve

**Comment by tallclair** [comment]
/lgtm

I'd like to see this test replaced by moving [test/e2e/node/apparmor.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/apparmor.go) to common, but this is an OK intermediate step.

**Pull request merged**
