### PR TITLE
Cleanup volume binding leftover

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup
/sig scheduling
/priority important-soon

**What this PR does / why we need it**:

I think some leftover can be cleaned up after #83726.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
yes, this is not necessary anymore

**Comment by ahg-g** [comment]
/hold

Someone asked about having this accessible for out-of-tree plugins IIRC, lets double check first.

**Comment by alculquicondor** [comment]
Any reason why they can't do the same as the in-tree plugin? https://github.com/kubernetes/kubernetes/blob/0f2cccc98c3bf2a512ec55cbeba89dbfe7c768cf/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L187

**Comment by ahg-g** [comment]
> Any reason why they can't do the same as the in-tree plugin?
> 
> https://github.com/kubernetes/kubernetes/blob/0f2cccc98c3bf2a512ec55cbeba89dbfe7c768cf/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L187

May be because they want to look at the shared cache? If that is the case, we need to properly instantiate a shared VolumeBinder as it was before.

Here is the original issue: https://github.com/kubernetes/kubernetes/issues/86906

@skilxn-go do you still have a dependency on VolumeBinder?

**Comment by skilxn-go** [comment]
@ahg-g Yep, my case is, I want to know the assumed volume binding before binding (`reserve`) and after binding failed (`unreserve`). If there is any other solution to get this info after removing the `volumebinder`, I can depend on it, too.

**Comment by alculquicondor** [comment]
The left over object wouldn't do what @skilxn-go needs, as it is a separate cache.

Moving the type back to how it was is not possible, because of the arg.

I think we need to revisit what was stated in #86906. What is the management you need? I have the feeling that a scheduler plugin is not the correct layer to do this, but probably CSI.

**Comment by skilxn-go** [comment]
@alculquicondor We have a disk manager which controls a lot of disks on different machines.
Kubernetes is not the only consumer of those disks, but for elastic, we create local pv on each disk.
So when kubernetes is scheduling pods, we need to reserve the assumed disk for it to avoid it being used by other applications.
And we need to unreserve disks after the pod bind failed, too.

**Comment by ahg-g** [comment]
> @alculquicondor We have a disk manager which controls a lot of disks on different machines.
> Kubernetes is not the only consumer of those disks, but for elastic, we create local pv on each disk.
> So when kubernetes is scheduling pods, we need to reserve the assumed disk for it to avoid it being used by other applications.
> And we need to unreserve disks after the pod bind failed, too.

I think your requirement can be addressed by the new [CSIStorageCapacity](https://github.com/kubernetes/enhancements/pull/1353.) feature. 

Until CSIStorageCapacity is ready, and since all volume binding logic moved to run as a [single plugin](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go), one thing you can do is implement your custom VolumeBinding plugin that replaces the default one. 

Note that the per-cycle VolumeBinder cache you are currently depending on will move in the future to be in the CycleState, at which point you might be able to access it again similar to what you do now, but I don't recommend it.

I think we should go ahead with this PR since there is a reasonable alternative.

**Comment by skilxn-go** [comment]
@ahg-g It sounds good to me.

**Comment by ahg-g** [comment]
Thanks, @Huang-Wei can you please rebase?

/hold cancel

**Comment by Huang-Wei** [comment]
@ahg-g Done.

**Pull request merged**
