### PR TITLE
AWS: Run minions in Auto Scaling Group

### PR DESCRIPTION
**Pull request by justinsb**
Run the minions in an auto-scaling group, to support resizing.  Should only affect AWS.

Depends on #9720 (first two commits are 9720)

### CODE REVIEW

**Comment by iterion** [comment]
Should access to Auto Scaling be added to the IAM policy for either the master or minions? I know there aren't currently any calls to auto scaling commands from kubernetes, but users might run services in their cluster that would expect to be able to scale the ASG?

**Comment by satnam6502** [comment]
Ready to review? Push new version?

**Comment by yujuhong** [comment]
Reassign to people who have more context on the issue.

**Comment by satnam6502** [comment]
Thank you @yujuhong

**Comment by justinsb** [comment]
@iterion Happy to rethink, but my thought was to keep the permissions minimal until we need more permissions.  It's fairly easy for people to change the permission if they want to do more, so until we actually need the permission I don't think we should enable it.

@satnam6502 / @cjcullen : No blockers, so should be OK to merge.  This PR only affects AWS files as well :-)

**Comment by iterion** [comment]
@justinsb Fair enough, agree it's probably best to keep permissions to a minimum. Excited to see this merged, awesome work on getting this into v1!

**Comment by justinsb** [comment]
Rebased to get shippable to run (it was still 'in progress' after 12+ hours.

**Pull request merged**
