### PR TITLE
kubeadm: add chendave as kubeadm reviewer

### PR DESCRIPTION
**Pull request by chendave**
I have been actively contributed to this component for an while, and I'd like to review PRs from now.

Being a member since [Oct. 19.](https://github.com/kubernetes/org/issues/1273),

- [PR list](https://github.com/kubernetes/kubernetes/pulls?q=label%3Asig%2Fcluster-lifecycle++author%3Achendave+) with the label of sig/cluster-lifecycle 
- [issue list](https://github.com/kubernetes/kubeadm/issues?q=is%3Aissue+author%3Achendave) in kubeadm repo.
- [all PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Achendave) targeted for k/k repo.
 
/kind documentation

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
+1 
👍

**Review by neolit123 — COMMENTED** [review]
@chendave asked me on dm and i said +1
thank you for the contributions thus far

/lgtm
/approve
/hold

/cc @SataQiu

**Comment by SataQiu** [comment]
Congratulations @chendave 
I'm +1 👍 
Thanks for your contributions!

/retest

**Comment by neolit123** [comment]
/hold cancel
@chendave please also sync the owner file in k/kubeadm (pr). code in that repo is also our responsibility.

**Comment by aojea** [comment]
+1

**Comment by chendave** [comment]
Huge thanks for your support here, @pacoxu @neolit123 @SataQiu @aojea 👍

**Pull request merged**
