### PR TITLE
Fix incorrect parameters in EndpointsEqualBeyondHash

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

There are two typos in `EndpointsEqualBeyondHash` leading to wrong result.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tnqn** [comment]
/assign @aojea @robscott
I found the issue while working on #108078, think it may be cleaner to merge the fix seperately.

**Comment by robscott** [comment]
Thanks @tnqn! Can you cherry pick this back to previous versions?

**Comment by tnqn** [comment]
@robscott sure, done.

**Pull request merged**
