### PR TITLE
ValidateVolumeAttributesClassUpdate also validates new vac object.

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

ValidateVolumeAttributesClassUpdate also validates new vac object.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

this func has already validate the meta object updates. the parameter and driverName field are immutable. so this changes won't have any effect on user's usage.

#### Does this PR introduce a user-facing change?

```release-note
ValidateVolumeAttributesClassUpdate also validates new vac object.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Is there any way that a user out in the world could have somehow updated a saved object into a bad state that would no longer pass this validation?

**Comment by carlory** [comment]
No, there's no way for users to do that. we have already validate the meta field of the new obj and other fields are immutable. This PR is just to make sure that we don't have any bad data if we add new mutable fields in the future.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
