### PR TITLE
Fixed kind to resource convertion in scale client.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed kind to resource convertion in scale client.

### CODE REVIEW

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by mwielgus** [comment]
LGTM

**Comment by jszczepkowski** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
GCE e2e test failure was due to #13534.  Retry to trigger auto-merge by merge-bot.

@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
Another github network error.  Try again...

@k8s-bot test this again please

```
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/* --prune" returned status code 128:
stdout: 
stderr: error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
```

**Comment by jszczepkowski** [comment]
Part of #12087.

**Pull request merged**
