### PR TITLE
Ipvs kube-proxy

### PR DESCRIPTION
**Pull request by mqliang**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mqliang** [comment]
@boynux @knobunc @smarterclayton  @bprashanth @kubernetes/sig-network

**Comment by luxas** [comment]
Is there a proposal linked to this feature?
What are the benefits for a ipvs proxier vs the iptables one?
Can you line up that as a kubernetes/features issue at least if this is a thing that is aimed to get merged?

**Comment by boynux** [comment]
@luxas  @mqliang  I created  a feature request for this PR. Please review to see if I missed anything

**Comment by resouer** [comment]
It would be helpful if you can provide:

1. benefits comparing to existing iptables proxy (especially if you are only using NAT mode which is essentially the same of iptables rules)
2. design to make sure this works with overlay network (and other cross host networking)
3. a description of your implementation including dependencies involved.

Maybe as @luxas said, a proposal is needed first. 

cc @feiskyer @thockin

**Comment by feiskyer** [comment]
@resouer More discussion is at [sig-net forum](https://groups.google.com/forum/#!topic/kubernetes-sig-network/59HG9SlypBc).

**Comment by leslie-wang** [comment]
@resouer current iptable approaches can not be used for high volume data movement application, such as NFV, media applications. Current kube-proxy has very bad performance for these applications. IPVS direct routing mode is one good solution for that. so this work is really helpful for these applications.

**Comment by thockin** [comment]
NB: IPVS Direct routing does not handle port remapping, so it can't apply
in all cases.

**Comment by mqliang** [comment]
Ok, will write a proposal in couple of days.

**Comment by leslie-wang** [comment]
@thockin I guess we probably need different ipvs LB policies. People can enable what they want. Direct routing mode doesn't work with port mapping, definitely need other mechanisms to enable it. 

@mqliang Seems like current pull doesn't set LB policies. IPVS by default uses direct routing mode. Is it what you want? Considering ipvs node may be not the master node (even on master nodes, which one should run ipvs is another question mark), you probably can consider to use rest instead of direct library call. Maybe you can refer https://github.com/kobolog/gorb.

**Comment by sureshvis** [comment]
@miaoyq any plan for this PR ? we would like to explore ipvs

**Comment by thockin** [comment]
I have not had time to review in depth, but I welcome people to try it and
see how it feels, what works well and what doesn't.  Benchmarks might be
nice too :)

**Comment by quinton-hoole** [comment]
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063

**Comment by thockin** [comment]
@mqliang - OK to close this to fold with #44063?  One Pr is better than 2...

**Pull request closed without merging**
