### PR TITLE
remove import doc comments

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The `// import <path>` comment has been superseded by Go modules. We don't have to remove them, but doing so has some advantages:

- They are used inconsistently, which is confusing.
- We can then also remove the (currently broken) hack/update-vanity-imports.sh.
- Last but not least, it would be a first step towards avoiding the k8s.io domain.

#### Special notes for your reviewer:

Created with:

```bash
sed -i -e 's;^package \(.*\) // import.*;package \1;' $(git grep -l '^package.*// import' | grep -v 'vendor/')
```

`pkg/util/labels` was left unchanged because it is marked as read-only.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/test pull-kubernetes-verify

```
Found pkg/util/labels/.readonly, but files changed compared to "master" branch.
```

Instead of fighting with that check, I took out the changes to `pkg/util/labels`, so that's were we have `// import k8s.io/kubernetes/pkg/util/labels` left.

**Comment by thockin** [comment]
/approve
/lgtm
/retest

How do we ignore the linter hints??

**Comment by pohly** [comment]
> How do we ignore the linter hints??

By doing nothing :smile:

The hints are in a non-blocking job which can be ignored if author and reviewer agree to do so.

**Comment by pohly** [comment]
Hmm, I see now that the bot is triggering retests of the failing, non-blocking `pull-kubernetes-linter-hints`.

/hold

The hold should stop the retesting. Can be lifted once the code freeze is over.

**Comment by BenTheElder** [comment]
> Hmm, I see now that the bot is triggering retests of the failing, non-blocking pull-kubernetes-linter-hints.

because it reports.

BTW few GitHub users / contributors recognize the nuance between "required" and "merely reporting status" even though we use the built in GitHub concept for this.

which is why we rarely use them long term for things that aren't purely by author/reviewer request

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/33900

**Comment by thockin** [comment]
FTR: Go Workspaces is what allows this to work across modules, e.g.:

```
$ go list -f '{{.Module.Path}}' ./staging/src/k8s.io/api/core/v1/ ./pkg/kubelet/ ./staging/src/k8s.io/code-generator
k8s.io/api
k8s.io/kubernetes
k8s.io/code-generator
```

**Comment by jcchavezs** [comment]
Thanks for the interest and the detailed feedback. I still believe the `import` comment is useful as `pkg.go.dev` is not always enough (and even they redirect you to github.com source when you need more details) but I believe we won't get to an agreement.

**Pull request merged**
