### PR TITLE
Proposal: Kubernetes network provider for network segmentation

### PR DESCRIPTION
**Pull request by feiskyer**
Proposal: Kubernetes network provider for network segmentation

**Motivation**

There are many use-cases that current kubernetes's network model does not support as is discussed at [3350](https://github.com/kubernetes/kubernetes/issues/3350)
- Multi-tenant networking
- Bridged/L2-connectivity
- SDN applications
- IPAM integration with current tools

So we proposed a new network model for kubernetes, that is:
- Introduce network segments for kubernetes and associates namespace with network segment. Each namespace is belong to only one network segment, but network segments can be accross different namespaces.
- Instead of full communication between all containers, containers only on the same network are fullly communicated in this network model. Containers on different networks are not communicated directly, but they can communicate with each other via external endpoints.
- Each network segments contains multiple subnets and IPs are unique only within this network segment. There may be same IPs and subnets accross different network segments.
- Introduce network controller to manage kubernetes's network segments and introduce network provider to do real network allocations. Network controller listens to creation/deletion/update events for networks, and tell network provider to configure them.
- There is no requirements of setting each kubelet with different subnets. Instead, kubelet is network segments aware. Kubelet ensures network segments are properly configured.
- Each pod will receive a unique IP address from the network segment, and this IP will be configured for container by kubelet's network plugin, which works together with network controller.
- Since there are many isolated network segments on the same host, kube-proxy will be disabled. Service discovery and load balancing will also be provided by networkprovider.

**Examples of creating a network segment**
- Create network segment using provider's existing network id:

``` yaml
apiVersion: v1
kind: Network
metadata:
  name: net2
spec:
  tenantID: 56064caf8d9b4f7aabab297c7d5409dc
  providerNetworkID: 2bd93771-950f-4ca1-a23c-9de8893ab076
```
- Create network segment by subnets, this will create a provider network automatically:

``` yaml
apiVersion: v1
kind: Network
metadata:
  name: net1
spec:
  tenantID: 56064caf8d9b4f7aabab297c7d5409dc
  subnets:
    subnet1:
      cidr: 192.168.0.0/24
      gateway: 192.168.0.1
```

**Changes to create a namespace**

``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
spec:
  network: net1
```

Note: network is optional; if provided, network_name must be existing before creating namespace.

**Some notices:**
- Network must be existing before creating namespace.
- Service discovery can alo be done by [service loadbalancer](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer).
- To use networkprovider, kube-proxy should be disabled.
- https://github.com/hyperhq/kubestack provides an OpenStack networkprovider for kubernetes.

**TODOs**
- [x] network segment registry
- [x] network segment API and kubectl cmd
- [x] network provider
- [x] remote network provider plugin
- [x] add network spec for namespace
- [x] network controller: listening events of networks and manage them via network provider
- [x] network controller: listening events of pods/services and manage them via network provider
- [x] kubelet network plugin to set up networks for containers (instead of kube-proxy)
- [x] add container runtime type to kubelet network plugin

Any suggestions is welcomed!

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/goog-cluster @kubernetes/rh-networking

**Comment by emaildanwilson** [comment]
+1 Thank you for working on this!

**Comment by bdmesh** [comment]
+1  This is awesome.  Network/subnet isolation is very important to us!

**Comment by dcbw** [comment]
Could you explain the TenantID and ProviderNetworkID more?  The TenantID seems to be a UUID associated 1:1 with a network segment, which already has a name associated with it.  Do we need a TenantID when we already have a unique name?

Also, is the ProviderNetworkID simply an opaque UUID that the network provider creates to associate with a network, if the provider is an external entity?

I gather that how to specify multiple networks is still under huge discussion; on the OpenShift side we're using namespace :: network but that's insufficient for many cases.  Thus, we can't necessarily map a namspace to a network, but we need a more detailed method of associating pods with one or more network segments.

Going a bit deeper, I think we need some mechanism to mark a particular network segment and subnet that a pod is attached to as "primary".  That's a concept that Kubernetes has apparently baked in, and if a pod is connected to multiple network segments and/or subnets one of those must the the primary segment for purposes of IP address reporting and display.

??? On the services and load balancer side, I don't think that should necessarily be disabled and provided by the network provider instead.  We've managed to make services work with OpenShift + OVS while providing network segmentation

I think having a new Kubelet option is confusing.  A network provider should simply be a different plugin that you specify that says it is multinetwork aware.  If the plugin is not multinetwork aware, then Kubernetes should treat networks as belonging to the same segment like it currently does.

Next, we need to harmonize this with the kubelet CNI plugin changes that just went in.  Those are fairly basic and not yet multinetwork aware, but that's blocking on higher-level resolution of how to define pod/network relationships.  In any case, it would be ideal to combine the Kubelet patch in this PR with the CNI plugin functionality, since that already has "remote" functionality.  The CNI stuff still doesn't cover higher level operations like network watching, provider initialization/teardown, etc, but that stuff needs to be done and parts of this could be leveraged to do that.

Should the containerRuntime changes really be part of this PR?  That seems unrelated to anything network related, at least at this point.

In any case, we do really need to keep pushing Kubernetes forward with multinetwork support, so lets keep working on this!

**Comment by feiskyer** [comment]
@dcbw Thanks for suggestions.

> Could you explain the TenantID and ProviderNetworkID more? The TenantID seems to be a UUID associated 1:1 with a network segment, which already has a name associated with it. Do we need a TenantID when we already have a unique name?
> Also, is the ProviderNetworkID simply an opaque UUID that the network provider creates to associate with a network, if the provider is an external entity?

TenantID is designed for supporting multiple tenancy and ProviderNetworkID is simply an unique network ID managed by network provider. TenantID is needed because kubernetes needs to know which tenancy of new network will be created if ProviderNetworkID is null.

> I gather that how to specify multiple networks is still under huge discussion; on the OpenShift side we're using namespace :: network but that's insufficient for many cases. Thus, we can't necessarily map a namspace to a network, but we need a more detailed method of associating pods with one or more network segments.
> 
> Going a bit deeper, I think we need some mechanism to mark a particular network segment and subnet that a pod is attached to as "primary". That's a concept that Kubernetes has apparently baked in, and if a pod is connected to multiple network segments and/or subnets one of those must the the primary segment for purposes of IP address reporting and display.

As what I have known, there is no "primary" pod IP concept in kubernetes and multiple network interfaces is not supported for kubernetes. ( @dcbw If I missed something, please point it out.)

> I think having a new Kubelet option is confusing. A network provider should simply be a different plugin that you specify that says it is multinetwork aware. If the plugin is not multinetwork aware, then Kubernetes should treat networks as belonging to the same segment like it currently does.
> 
> Next, we need to harmonize this with the kubelet CNI plugin changes that just went in. Those are fairly basic and not yet multinetwork aware, but that's blocking on higher-level resolution of how to define pod/network relationships. In any case, it would be ideal to combine the Kubelet patch in this PR with the CNI plugin functionality, since that already has "remote" functionality. The CNI stuff still doesn't cover higher level operations like network watching, provider initialization/teardown, etc, but that stuff needs to be done and parts of this could be leveraged to do that.
> 
> Should the containerRuntime changes really be part of this PR? That seems unrelated to anything network related, at least at this point.

New kubelet option is added because I want to identify explicitly the kubelet is running togather with a network provider. I think reusing current network plugin is ok if there is way to point out this plugin is running with a network provider.

> In any case, we do really need to keep pushing Kubernetes forward with multinetwork support, so lets keep working on this!

Thanks. Let's working together on this.

**Comment by dcbw** [comment]
> TenantID is designed for supporting multiple tenancy and ProviderNetworkID is simply an unique network ID managed by network provider. TenantID is needed because kubernetes needs to know which tenancy of new network will be created if ProviderNetworkID is null.

@feiskyer It seems like the TenantID and ProviderNetworkID overlap somewhat. TenantID is will always have a 1:1 relationship with the Network object right?  Eg, two different network objects will never have the same TenantID, correct?

Also, how does one define a new NetworkSpec, does that happen directly in etcd at the moment, and then is just read by Kubernetes?

> As what I have known, there is no "primary" pod IP concept in kubernetes and multiple network interfaces is not supported for kubernetes. ( @dcbw If I missed something, please point it out.)

There is such a concept though it's not explicitly specified, see https://github.com/kubernetes/kubernetes/pull/12595#issuecomment-130847580 for more detail on that.  I think it's unfortunate, but apparently it exists.  Whatever returns the pod's IP address to the Kube core needs some mechanism to say that one of the possible addresses is primary, otherwise Kube will be forced to simply pick one.  That would imply that if pods can be connected to more than one network, and inside that network more than one subnet, we some way of identifying which of those IP addresses the pod gets will be the primary one for the status callback.

Multiple network interfaces are the responsibility of the kube networking plugin to manage; kubernetes doesn't care much about them at all.  Or at least that's where I'd like things to move.  Kubernetes currently asks docker what the pod's IP address is, but that will go away when we have CNI plugin integration and the plugin will be responsible for telling Kubernetes this info.

> New kubelet option is added because I want to identify explicitly the kubelet is running togather with a network provider. I think reusing current network plugin is ok if there is way to point out this plugin is running with a network provider.

My point is that each network provider should be part of a plugin too :)  As I said above, there are some missing hooks, like plugin init/teardown, notifying the plugin of NetworkSpec/namespace/etc changes, and maybe a few other things.  I think things should go like this:

1. Kubernetes calls the Init() method of the given network plugin
2. Kubernetes sees new NetworkSpec in etcd (or one gets created through some k8s API?)
3. Kubernetes tells the plugin about the new NetworkSpec and receives an instantiated Network object back (?)
5. Pod is started somewhere
4. When a pod wants to be connected to a Network, Kubernetes uses existing CNI plugin mechanism to make that happen.  This step could happen multiple times for a single pod, once for each network the pod wants to use.

It's also important to remember that a plugin may not want to dedicate resources to a network until the first plugin is attached to that network.  There's no point to allocating IP subnets for a network until something actually uses it, for example.  But that's a choice the plugin needs to make, so Kubernetes should be able to handle that.  Eg, it shouldn't expect allocated network resources when the Network object is instantiated, but obviously that must have happened when the first pod is attached.

**Comment by smarterclayton** [comment]
Pod primary IP is the IP that other pods can reach the pod by.  If we need
to tighten the definition, we can say it's the ip that other pods in the
same namespace can reach the pod by.

In practice, it's the ip that other pods that can reference the service the
pod is under can reach it by.  So the service endpoints controller *must*
by able to view a pod and identify the ip that should be used to access the
pod by the services consumers.

Having additional lists of IPs is only useful in how it can enable the
items above - that's what custom service target providers (see component
registration) could enable, a way to identify alternate pod IPs to be
routable and place them under services.  However, I'm skeptical of any
system without a primary pod ip because it complicates the ability of pods
to interconnect (an anti-goal of Kube)

On Oct 1, 2015, at 9:30 PM, Dan Williams <notifications@github.com> wrote:

TenantID is designed for supporting multiple tenancy and ProviderNetworkID
is simply an unique network ID managed by network provider. TenantID is
needed because kubernetes needs to know which tenancy of new network will
be created if ProviderNetworkID is null.

@feiskyer <https://github.com/feiskyer> It seems like the TenantID and
ProviderNetworkID overlap somewhat. TenantID is will always have a 1:1
relationship with the Network object right? Eg, two different network
objects will never have the same TenantID, correct?

Also, how does one define a new NetworkSpec, does that happen directly in
etcd at the moment, and then is just read by Kubernetes?

As what I have known, there is no "primary" pod IP concept in kubernetes
and multiple network interfaces is not supported for kubernetes. ( @dcbw
<https://github.com/dcbw> If I missed something, please point it out.)

There is such a concept though it's not explicitly specified, see #12595
(comment)
<https://github.com/kubernetes/kubernetes/pull/12595#issuecomment-130847580>
for more detail on that. I think it's unfortunate, but apparently it
exists.Whatever returns the pod's IP address to the Kube core needs some
mechanism to say that one of the possible addresses is primary, otherwise
Kube will be forced to simply pick one. That would imply that if pods can
be connected to more than one network, and inside that network more than
one subnet, we some way of identifying which of those IP addresses the pod
gets will be the primary one for the status callback.

Multiple network interfaces are the responsibility of the kube networking
plugin to manage; kubernetes doesn't care much about them at all. Or at
least that's where I'd like things to move. Kubernetes currently asks
docker what the pod's IP address is, but that will go away when we have CNI
plugin integration and the plugin will be responsible for telling
Kubernetes this info.

New kubelet option is added because I want to identify explicitly the
kubelet is running togather with a network provider. I think reusing
current network plugin is ok if there is way to point out this plugin is
running with a network provider.

My point is that each network provider should be part of a plugin too :) As
I said above, there are some missing hooks, like plugin init/teardown,
notifying the plugin of NetworkSpec/namespace/etc changes, and maybe a few
other things. I think things should go like this:

   1. Kubernetes calls the Init() method of the given network plugin
   2. Kubernetes sees new NetworkSpec in etcd (or one gets created through
   some k8s API?)
   3. Kubernetes tells the plugin about the new NetworkSpec and receives an
   instantiated Network object back (?)
   4. Pod is started somewhere
   5. When a pod wants to be connected to a Network, Kubernetes uses
   existing CNI plugin mechanism to make that happen. This step could happen
   multiple times for a single pod, once for each network the pod wants to use.

It's also important to remember that a plugin may not want to dedicate
resources to a network until the first plugin is attached to that network.
There's no point to allocating IP subnets for a network until something
actually uses it, for example. But that's a choice the plugin needs to
make, so Kubernetes should be able to handle that. Eg, it shouldn't expect
allocated network resources when the Network object is instantiated, but
obviously that must have happened when the first pod is attached.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/13622#issuecomment-144823780>
.

**Comment by feiskyer** [comment]
> @feiskyer It seems like the TenantID and ProviderNetworkID overlap somewhat. TenantID is will always have a 1:1 relationship with the Network object right? Eg, two different network objects will never have the same TenantID, correct?

No, they are not 1:1. One tenant may contain multiple networks. 

User may create a network by pass in subnet cidrs, such as:

```yaml
apiVersion: v1
kind: Network
metadata:
  name: net1
spec:
  tenantID: 56064caf8d9b4f7aabab297c7d5409dc
  subnets:
    subnet1:
      cidr: 192.168.0.0/24
      gateway: 192.168.0.1
```

In this way, we need to tell which tenant should these subnets be created in. That's why tenantID is essential. 

>> Also, how does one define a new NetworkSpec, does that happen directly in etcd at the moment, and then is just read by Kubernetes?

Yes, network info is written in etcd. And then this info will be read by network controller.

>> There is such a concept though it's not explicitly specified, see #12595 (comment) for more detail on that. I think it's unfortunate, but apparently it exists. Whatever returns the pod's IP address to the Kube core needs some mechanism to say that one of the possible addresses is primary, otherwise Kube will be forced to simply pick one. That would imply that if pods can be connected to more than one network, and inside that network more than one subnet, we some way of identifying which of those IP addresses the pod gets will be the primary one for the status callback.
>> 
>> Multiple network interfaces are the responsibility of the kube networking plugin to manage; kubernetes doesn't care much about them at all. Or at least that's where I'd like things to move. Kubernetes currently asks docker what the pod's IP address is, but that will go away when we have CNI plugin integration and the plugin will be responsible for telling Kubernetes this info.

Reasonable. So non-primary Ips should leave to network plugin itself and they are transparent to network provider, right? @dcbw @smarterclayton

> My point is that each network provider should be part of a plugin too :) As I said above, there are some missing hooks, like plugin init/teardown, notifying the plugin of NetworkSpec/namespace/etc changes, and maybe a few other things. I think things should go like this:
> 
> Kubernetes calls the Init() method of the given network plugin
Kubernetes sees new NetworkSpec in etcd (or one gets created through some k8s API?)
> Kubernetes tells the plugin about the new NetworkSpec and receives an instantiated Network object back (?)
> Pod is started somewhere
> When a pod wants to be connected to a Network, Kubernetes uses existing CNI plugin mechanism to make that happen. This step could happen multiple times for a single pod, once for each network the pod wants to use.
> It's also important to remember that a plugin may not want to dedicate resources to a network until the first plugin is attached to that network. There's no point to allocating IP subnets for a network until something actually uses it, for example. But that's a choice the plugin needs to make, so Kubernetes should be able to handle that. Eg, it shouldn't expect allocated network resources when the Network object is instantiated, but obviously that must have happened when the first pod is attached.

I think network provider shouldn't be treated as a part of kubelet network plugin. Network provider should be a global network manager and a kubelet network plugin is indeed needed to configure network interface for Pods. But network plugin should ask network provider for which IP belonging to which Pod.

In this way, network provider could preallocate subnet for dedicated network.

@smarterclayton @bdmesh @emaildanwilson @thockin What's your opinion?

**Comment by dcbw** [comment]
On Fri, 2015-10-02 at 07:46 -0700, feisky wrote:
> > @feiskyer It seems like the TenantID and ProviderNetworkID overlap somewhat. TenantID is will always have a 1:1 relationship with the Network object right? Eg, two different network objects will never have the same TenantID, correct?
> 
> No, they are not 1:1. One tenant may contain multiple networks. 
> 
> User may create a network by pass in subnet cidrs, such as:
> 
> ```yaml
> apiVersion: v1
> kind: Network
> metadata:
>   name: net1
> spec:
>   tenantID: 56064caf8d9b4f7aabab297c7d5409dc
>   subnets:
>     subnet1:
>       cidr: 192.168.0.0/24
>       gateway: 192.168.0.1
> ```
> 
> In this way, we need to tell which tenant should these subnets be created in. That's why tenantID is essential. 

@feiskyer I guess what I'm trying to get at is that I think the model of
tenants and providers hardcodes too much information into Kubernetes
that other plugins may not care about.

It seems to me that the tenantID is an extra bit of information that the
*plugin/provider* might care about, but not Kubernetes itself.

Same for ProviderNetworkID; Kubernetes doesn't care about that
internally, except for enforcing that ProviderNetowrkID and Subnets
can't be given at the same time.  Which seems a bit orthogonal; why
couldn't the subnets be stored in Kubernetes but there the network
provider still want to assign a ProviderNetworkID to track other
information?

Also, I think it's a bit premature to add LoadBalancer stuff, let's keep
the PR smaller and focus on the provider/Network object bits and do the
LoadBalancer stuff later...

I feel like the proposed model is a bit more complicated than I think we
need at this point, given where we're at today.  I'd personally like to
do something like:

1) Create Networks as first-class objects - you've done this already (I
think), so great!
2) Let Network objects have Labels, like pods do (you've done this
already I think, so great!)
3) Use Labels on Networks to tag info for network provider/plugin if
required, like TenantID and ProviderNetworkID.  This would be about the
same as we have now, just much more generic and ensures we don't force
various providers/plugins into one specific model.
4) Add a NetworkController interface and fold what we can of the
CNI/plugin interface into it; the CNI plugin stuff is basically what the
networkprovider.Pods interface currently is.  But it would also handle
the networkprovider.Networks interface.
5) Use labels and selectors to map pods to Network objects via the
network UUID and/or name
6) Focus on getting only this stuff reviewed, accepted, and working well
before we take further steps and add more complicated API (eg,
LoadBalancer, UIDs for all the networkprovider objects, SegmentID, etc).

@thockin @rajatchopra thoughts?

**Comment by feiskyer** [comment]
@dcbw Indeed, this PR is too huge. I will summit another PR with only network provider.

**Comment by feiskyer** [comment]
New proposal PR opened at https://github.com/kubernetes/kubernetes/pull/15465

**Comment by feiskyer** [comment]
Close this PR since  #15465 is opened.

**Pull request closed without merging**
