### PR TITLE
Graduate Kubelet plugin registration/watcher to GA

### LINKED ISSUE #70484: Move Kubelet Plugin Registration Watcher to GA
**What would you like to be added**:
This issue is to migrate the Kubelet Plugin Registration/Watcher from Beta -> GA.

**Why is this needed**:
This feature (PluginsRegistrationWatcher) has been a core functionality of other systems such as CSI for a couple of releases now.  Moving from Beta to GA will signal to adopters (such as CSI) that this feature is ready stable and ready for continuing adoption.

**Feature tracking:** https://github.com/kubernetes/enhancements/issues/595 

**Items needed**
- [x] Update feature gate comment to reflect GA 
    - https://github.com/kubernetes/kubernetes/blob/dc1307b82639780334af99936b2e0dbe24c9a552/pkg/features/kube_features.go#L330:2
- [x] Create `v1` package in `pkg/kubelet/apis/pluginregistration`
- [x] Update  imports to point to `v1`
- [x] Create PR - https://github.com/kubernetes/kubernetes/pull/70559
- [ ] Resolve pending issue - https://github.com/kubernetes/kubernetes/issues/69015
- [ ] Present PR to section owners (SIG Node) for review

Related [umbrella] issue - https://github.com/kubernetes/kubernetes/issues/65773

/kind feature

### PR DESCRIPTION
**Pull request by vladimirvivien**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR contains code changes necessary to graduate the Kubelet Plugin Watcher registration mechanism from `Beta` to `GA`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70484

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
The Kubelet plugin registration mechanism used by device plugins and CSI plugins is now GA
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
/sig node

cc @RenaudWasTaken

**Comment by vladimirvivien** [comment]
@tallclair PTAL

**Review by RenaudWasTaken — APPROVED** [review]
/lgtm

Though I'm not sure why the Kubelet struct needed to be reformated?

**Comment by vladimirvivien** [comment]
@RenaudWasTaken thanks for review, not sure why my editor reformatted code after I updated kubelet to point to v1 package.  Will take a look. Thanks.

**Comment by vladimirvivien** [comment]
@vishh PTAL.  Looking for approval for 1.13.

**Comment by vishh** [comment]
Hmm.. Was the switch from alpha->GA discussed early on? What makes us believe that the existing API & behavior is what we'd like to maintain for at-least a year from now?

**Comment by vladimirvivien** [comment]
@vishh Hi. This is to go from Beta -> GA.  This feature has been in used for a while now.  The reference to beta packages were not updated in last previous release.  To answer your other questions: this API has been in used by may CSI drivers (https://kubernetes-csi.github.io/docs/Drivers.html).  As CSI moves to GA this quarter, we feel this is one of the other API that could go GA as well. 

cc @RenaudWasTaken

**Comment by saad-ali** [comment]
> What makes us believe that the existing API & behavior is what we'd like to maintain for at-least a year from now?

This feature defines how CSI drivers are discovered. GA of this feature is a blocker CSI GA (which we are planning for this 1.13 release). It also means that once CSI goes GA the requirements from CSI for this feature are unlikely to change since CSI it self needs to remain backwards compatible and backwards incompatible changes would break CSI).

The existing API has been sufficient for CSI and we haven't changed it since alpha. The only known use cases that we are currently aware of that may require changing the API is adding windows support -- but that so far seems like it won't require any change or only additive change.

**Comment by vishh** [comment]
I was misguided by the [comment](https://github.com/kubernetes/kubernetes/pull/70559/files#diff-84e72664a7cc9add01954d3a7b8cbb45L327) which changed from `alpha` to `GA`. After chatting with @msau42 offline, I learned that the API has been put to use in the CSI world for a release now and @saad-ali is stating that the API has been sufficient since alpha. I'm more comfortable with graduating this API now.
/approve
/lgtm

**Comment by vladimirvivien** [comment]
@vishh Please re-approve. I had to rebase.

**Comment by vladimirvivien** [comment]
@tallclair PTAL, looking for approval for this feature.

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
