### PR TITLE
Update meta.go

### PR DESCRIPTION
**Pull request by knightXun**
i think that's better,just a advise.less code sounds good.

### CODE REVIEW

**Comment by knightXun** [comment]
@k8s-bot node e2e test this

**Comment by knightXun** [comment]
@MrHohn can you review my pr?

**Comment by MrHohn** [comment]
@knightXun Sorry, I'm not the right person to review apimachinery codes :(

**Comment by knightXun** [comment]
@MrHohn  thx ,anyway

**Comment by knightXun** [comment]
@deads2k can you review my pr?

**Comment by apelisse** [comment]
@k8s-bot ok to test

**Comment by knightXun** [comment]
@apelisse can you merge my pr?

**Comment by apelisse** [comment]
I'd rather have someone else give his opinion

**Pull request merged**
