### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by cchord**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some typo: dailer => dialer.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cchord** [comment]
I signed it

**Comment by cchord** [comment]
I signed it

**Comment by cchord** [comment]
i signed it

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve
/retest

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thank you for this fix!

**Pull request merged**
