### PR TITLE
Add missing termination metrics to priority-and-fairness handler

### PR DESCRIPTION
**Pull request by bjrara**
**What type of PR is this?**

/kind regression

**What this PR does / why we need it**:
In maxinflight handler, when the request is terminated by tooManyRequest, it will be added to `apiserver_request_terminations_total` metrics. After migrate to priority-and-fairness handler, this metrics is missing.

**Which issue(s) this PR fixes**:

Fixes #
Missing metrics in the priority-and-fairness handler

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM

**Comment by lavalamp** [comment]
/approve
/milestone v1.19

(looks like a bug fix to me)

Can we get a unit test that exercises this? I really like my metrics to add up :)

**Comment by bjrara** [comment]
> /approve
> /milestone v1.19
> 
> (looks like a bug fix to me)
> 
> Can we get a unit test that exercises this? I really like my metrics to add up :)

Test case added: https://github.com/kubernetes/kubernetes/pull/93877

**Pull request merged**
