### PR TITLE
rbd: initialize ceph monitors slice with an empty value.

### PR DESCRIPTION
**Pull request by humblec**
In translation lib rbd plugin, the monitors slice is nil which
has to be initialized with an empty value. This commit address the same.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note-none

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by humblec** [comment]
Cc @Jiawei0227

**Comment by Jiawei0227** [comment]
/assign @msau42 
for approval

**Comment by msau42** [comment]
/lgtm
/approve

If you want to cherry pick this, please also add a release note.

**Comment by humblec** [comment]
> /lgtm /approve
> 
> If you want to cherry pick this, please also add a release note.

@msau42 sure, opened cherrypick PR .. Thanks a lot !!

**Comment by cpanato** [comment]
@humblec this is only needed for release-1.23 branch? not for 1.22/1.21/1.20

**Comment by humblec** [comment]
> @humblec this is only needed for release-1.23 branch? not for 1.22/1.21/1.20

Thats correct @cpanato , not needed for < 1.23 . The feature is introduced in 1.23 release.

**Pull request merged**
