### PR TITLE
Another attempt to add ga-beacon analytics to .md file (except Godeps folder)

### PR DESCRIPTION
**Pull request by mansoorj**
Redid PR #6826 because it was easier to re-submit than resolving a gazillion conflicts.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@mansoorj This needs a rebase. :/

**Comment by lavalamp** [comment]
You need a script that verifies the presence of this stuff, or it'll get broken in about 10 seconds.

**Comment by bgrant0607** [comment]
Please don't modify any of the files in third_party.

All generated files MUST have the analytics line added to the generator source, not just to the generated output. Otherwise, you won't be able to submit this PR. Run hack/verify-gendocs.sh to find out which files this affects.

**Comment by roberthbailey** [comment]
@mansoorj I think your best bet would be to write a script that verifies that the appropriate include is part of all new .md files. Then new files that get added (even before your changes go in) will have the boilerplate. I think that will also make it easier for you to keep your PR sync'd with head.

**Comment by bgrant0607** [comment]
I think the analytics line could be appended/inserted by the gen-docs script approx. here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/util.sh#L141

cc @jlowdermilk

**Comment by mbforbes** [comment]
@mansoorj It's looking like you'll need to take the approach @roberthbailey and @bgrant0607 described to get this in. I'm assuming you'll do this in a separate PR, so I'm closing this one, but please feel free to re-open if you'd rather do it on the same branch.

**Pull request closed without merging**
