### PR TITLE
use framework.ExpectNoError() for daemon_set.go and deployment.go

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The e2e test framework has ExpectNoError() for readable test code.
This replaces gomega.Expect(err).NotTo(gomega.HaveOccurred()) with it for e2e/apps.

- daemon_set.go
- deployment.go

**Which issue(s) this PR fixes**:
Ref #77103

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig testing

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

**Review by oomichi — COMMENTED** [review]
/lgtm

**Comment by k-toyoda-pi** [comment]
/assign @janetkuo
could you approve this PR?

**Comment by oomichi** [comment]
@k-toyoda-pi Could you rebase this?

**Comment by k-toyoda-pi** [comment]
@oomichi I've done rebase.

**Comment by oomichi** [comment]
@k-toyoda-pi 

> @oomichi I've done rebase.

Thank you so much.

/lgtm

**Comment by oomichi** [comment]
@k-toyoda-pi Could you rebase again? Sorry about that :-(

/lgtm  cancel

**Pull request merged**
