### PR TITLE
update Feature:ScheduleDaemonSetPods in kube_features.go

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
 /kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @k82cn

**Comment by mysunshine92** [comment]
cc @mattjmcnaughton 
please add /ok-to-test ,thanks.

**Comment by mysunshine92** [comment]
cc @k82cn 
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by k82cn** [comment]
@bsalamat , would you help to approve that.

**Comment by mysunshine92** [comment]
@bsalamat , would you help to approve that.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Comment by mysunshine92** [comment]
cc @k82cn
please add an /approve label. thanks.

**Pull request closed without merging**
