### PR TITLE
Fix tests on OS X by re-introducing the old choose host interface

### PR DESCRIPTION
**Pull request by brendandburns**
Old function is a fall back.

### CODE REVIEW

**Comment by erictune** [comment]
@sub-mod

**Comment by markturansky** [comment]
LGTM.

I checked this out and ran the tests successfully on OS X.

**Comment by sub-mod** [comment]
@brendandburns the issue is not with util.go it was an issue with proxy_test.go

**Comment by satnam6502** [comment]
Self assigning since I can't seem to assign this to @markturansky

**Comment by sub-mod** [comment]
@satnam6502 can u pls check 5400

**Comment by markturansky** [comment]
I am currently testing #5400

**Comment by satnam6502** [comment]
I assigned #5400 to @brendandburns but happy to re-assign or take it myself.

**Comment by satnam6502** [comment]
Is this OK to merge?

**Comment by markturansky** [comment]
@satnam6502 not sure if this conflicts with #5400.  both work, though :)

**Comment by sub-mod** [comment]
@satnam6502 this is not the correct fix

**Comment by satnam6502** [comment]
Ah, OK. Should this PR be closed then?

**Comment by sub-mod** [comment]
yes , closed.

**Comment by brendandburns** [comment]
I don't think that #5400 is sufficient.  We should be able to run the proxy on OS X, not just the proxy unit tests.

--brendan

**Comment by sub-mod** [comment]
@brendanburns Ahh ok this i what I wanted to confirm whether we run kube on mac(Unix)

**Comment by brendandburns** [comment]
I would like to be able to run standalone kube w/ boot2docker

--brendan

**Comment by sub-mod** [comment]
@brendanburns can we apply both the PRs.

**Comment by brendandburns** [comment]
fine with me to apply both.

**Comment by sub-mod** [comment]
@satnam6502 fyi

**Comment by satnam6502** [comment]
OK, merging.

**Comment by markturansky** [comment]
@brendanburns Proxy still fails on OS X.  Would you like a PR for it?  This PR fixes the unit tests successfully.

This is my /tmp/kube-proxy.log:

```
I0312 18:36:46.642972   48203 util.go:410] Choosing interface en0 for from-host portals
I0312 18:36:46.643077   48203 util.go:415] Interface en0 = fe80::82e6:50ff:fe0a:981e/64
I0312 18:36:46.643093   48203 proxier.go:327] Setting Proxy IP to fe80::82e6:50ff:fe0a:981e
I0312 18:36:46.643103   48203 proxier.go:328] Initializing iptables
W0312 18:36:46.643164   48203 iptables.go:196] Error checking iptables version, assuming version at least 1.4.11: %vexec: "iptables": executable file not found in $PATH
I0312 18:36:46.643177   48203 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PROXY]
W0312 18:36:46.643692   48203 iptables.go:196] Error checking iptables version, assuming version at least 1.4.11: %vexec: "iptables": executable file not found in $PATH
I0312 18:36:46.643709   48203 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PROXY]
I0312 18:36:46.643744   48203 iptables.go:186] running iptables -F [KUBE-PROXY -t nat]
I0312 18:36:46.643790   48203 iptables.go:186] running iptables -X [KUBE-PROXY -t nat]
I0312 18:36:46.643835   48203 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
E0312 18:36:46.643875   48203 proxier.go:333] Failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exec: "iptables": executable file not found in $PATH: 
F0312 18:36:46.643887   48203 server.go:81] failed to create proxier, aborting
```

**Comment by sub-mod** [comment]
it is choosing ipv6 IP ,
@markturansky pls help me understand when u use boot2docker in mac it basically creates a VM right ? If yes I think /proc should be on that VM (I guess it is an ubuntu VM.)

**Comment by markturansky** [comment]
I'll make a new PR will all my steps, logs, etc.

**Comment by markturansky** [comment]
No need.  There's still this open issue with services on OS X:   https://github.com/GoogleCloudPlatform/kubernetes/issues/2170

**Pull request merged**
