### PR TITLE
typo: delete useless comments

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
typo fix

#### What this PR does / why we need it:
Fix spelling errors
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by googs1025** [comment]
@caesarxuchao @jpbetz /PTAL

**Comment by googs1025** [comment]
@BenTheElder  Can you help me review this PR? thanks a lot. just a typo

**Comment by googs1025** [comment]
@aojea  /PTAL Can you help me review this PR? thanks a lot. just a typo

**Comment by dims** [comment]
this qualifies as a trivial edit https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits please avoid trivial edits next time

/approve

**Pull request merged**
