### PR TITLE
Scheduler called by federated replicaset controller

### PR DESCRIPTION
**Pull request by kshafiee**
The purpose of this PR is to parse user input annotations to specify how many replicas should be allocated to each underlying cluster

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30848)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Ok to test

**Comment by nikhiljindal** [comment]
Reassigned to Marcin.
Cc @kubernetes/sig-cluster-federation

**Comment by kshafiee** [comment]
@deepak-vij

**Comment by quinton-hoole** [comment]
@kshafiee @mwielgus @jianhuiz This PR has been superceded by #29741 now, right?
Closing on that basis for now.  Please re-open if I've got this wrong.

**Pull request closed without merging**
