### PR TITLE
Automated cherry pick of #69828: Make CreatePrivilegedPSPBinding reentrant

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #69828 on release-1.12.

#69828: Make CreatePrivilegedPSPBinding reentrant

### CODE REVIEW

**Comment by BenTheElder** [comment]
This fixes e2e test behavior, without it tests that setup a privileged PSP can fail on the PSP already existing.

/kind bug
/release-note-none

**Comment by BenTheElder** [comment]
/priority important-soon
this is blocking some testing work on excessive test setup flakes.

**Comment by BenTheElder** [comment]
/retest
:/

**Comment by BenTheElder** [comment]
/cc @feiskyer 

PTAL, this shouldn't affect the release but it does prevent (potentially lots of) spurious test failures. 
I'm suprised this wasn't cherry-picked previously.

**Review by feiskyer — APPROVED** [review]
cherry pick approved

**Comment by BenTheElder** [comment]
Thank you all 😀

**Pull request merged**
