### PR TITLE
Add more tests for Azure routes.

### PR DESCRIPTION
**Pull request by brendandburns**
This builds off of #59165 

Please only review https://github.com/kubernetes/kubernetes/pull/59302/commits/a8d0e73234f0dc047966b7c6c660ac5344113780

### CODE REVIEW

**Comment by jdumars** [comment]
@khenidak PTAL

**Comment by brendandburns** [comment]
@feiskyer @andyzhangx @khenidak 

This is ready for review...  Let's get it in before something else changes :)

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
