### PR TITLE
Remove todo from init phase

### PR DESCRIPTION
**Pull request by yagonobre**
**What type of PR is this?**
/kind cleanup
```release-note
NONE
```

/assign @fabriziopandini @neolit123

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/priority backlog
/lgtm
/assign @fabriziopandini 

thanks @yagonobre 
maybe we can batch more changes in the same PR.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by fabriziopandini** [comment]
@yagonobre thanks!
/approve
/lgtm

**Pull request merged**
