### PR TITLE
Correctly attribute some data structures from gotestsum repository

### PR DESCRIPTION
**Pull request by dims**
These data structures represent the xml in the junit format. These would be EXACTLY the same even if i had typed it by hand. In this case i picked up these from the gotestsum repo. We can't vendor these as these are marked "internal" as well. Here's the original:
https://github.com/gotestyourself/gotestsum/blob/main/internal/junitxml/report.go#L18-L63

In this PR we are trying to do the right thing by adding the NOTICE/LICENSE under the third_party directory as we do usually for such code.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/milestone v1.24

@JamesLaverack would you like me to file an exception for this? it's not code that ends up in a kubernetes cluster, it is used in the CI / test harness to cleanup junit xml that is too large. So we should be treating this as a test exception. Happy to do either, just let me know.

**Comment by liggitt** [comment]
CI failure looks legitimate

thanks for the relocate and explicit license addition

**Comment by dims** [comment]
fixed (ran hack/update-vendor.sh) thanks @liggitt

**Comment by liggitt** [comment]
/hold

unit test failing:

```
=== FAIL: cmd/prune-junit-xml TestPruneXML (0.01s)
    prunexml_test.go:65: 
        	Error Trace:	prunexml_test.go:65
        	Error:      	Not equal: 
        	            	expected: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<testsuites>\n\t<testsuite tests=\"3\" failures=\"1\" time=\"271.610000\" name=\"k8s.io/kubernetes/test/integration/apiserver\" timestamp=\"\">\n\t\t<properties>\n\t\t\t<property name=\"go.version\" value=\"go1.18 linux/amd64\"></property>\n\t\t</properties>\n\t\t<testcase classname=\"k8s.io/kubernetes/test/integration/apimachinery\" name=\"TestWatchRestartsIfTimeoutNotReached/group/InformerWatcher_survives_closed_watches\" time=\"30.050000\"></testcase>\n\t\t<testcase classname=\"k8s.io/kubernetes/test/integration/apiserver\" name=\"TestMaxResourceSize/JSONPatchType_should_handle_a_patch_just_under_the_max_limit\" time=\"0.000000\">\n\t\t\t<skipped message=\"[... clipped...]ust_under_the_max_limit (0.00s)&#xA;\"></skipped>\n\t\t</testcase>\n\t\t<testcase classname=\"k8s.io/kubernetes/test/integration/apimachinery\" name=\"TestSchedulerInformers\" time=\"-0.000000\">\n\t\t\t<failure message=\"Failed\" type=\"\">[... clipped...]prometheus/client_metrics.go:160</failure>\n\t\t</testcase>\n\t</testsuite>\n</testsuites>"
        	            	actual  : "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<testsuites></testsuites>"
        	            	
        	            	Diff:
        	            	--- Expected
```

**Comment by dims** [comment]
/hold cancel

fixed the problem with the junit test case with moar! xml annotations on the data structures

**Comment by liggitt** [comment]
verify failure is fixed in https://github.com/kubernetes/kubernetes/pull/109195

**Comment by dims** [comment]
> verify failure is fixed in #109195

thanks @liggitt ! will wait for that to merge

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
thanks!

the integration flakes seem really concerning. I know we're tracking this already.

**Comment by dims** [comment]
@liggitt rebased this again. hoping it will help with flakes (and lost the `lgtm`)

**Comment by pacoxu** [comment]
Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce flake #107414
/test pull-kubernetes-unit

**Pull request merged**
