### PR TITLE
Add RevisionTime to ControllerRevision Object.

### PR DESCRIPTION
**Pull request by xingzhou**
Added RevisionTime to ControllerRevision object to record when revision happens.

Fixed part of #47727

Related to PR #48412

**Release note**:
```
None
```

### CODE REVIEW

**Comment by tallclair** [comment]
Someone from apps should review this.

/unassign

**Comment by dims** [comment]
@xingzhou Can you please rebase?

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by kow3ns** [comment]
@xingzhou 

1. What is the use case for adding revision time?
1. I'm not entirely sure this should be a field and not an annotation. What is the thought behind making this a field?

**Comment by xingzhou** [comment]
@kow3ns, at present, the controller will reuse `ControllerRevision` object to record the revision history and related information. As a result, if we roll back, we can not know the exact revision time for each for the revision (because we only have creation time for `ControllerRevision`). 

I'm open to making this as a field or just an annotation, but to me, making it as a new field can also share this field with `StatefulSet` in the future, if we support `StatefulSet` roll back by using `ControllerRevision` object as well.

**Comment by xingzhou** [comment]
I will rebase this PR later and the reviewers, please let me know your comments so that I can update the code as well.

**Pull request closed without merging**
