### PR TITLE
Update cni-plugins to v1.4.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update CNI plugins to the latest release.

cc @kubernetes/release-managers 
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated cni-plugins to v1.4.0.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@bart0sh `pull-kubernetes-local-e2e` will always fail right now. Ref: https://github.com/kubernetes/kubernetes/issues/122183

**Comment by bart0sh** [comment]
/lgtm

/cc @mrunalp @sergeyevstifeev 
for SIG-Node approval

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by cyclinder** [comment]
```
Waiting for apiserver to come up
+++ [1213 03:12:05] On try 3, apiserver: : ok
clusterrolebinding.rbac.authorization.k8s.io/kube-apiserver-kubelet-admin created
clusterrolebinding.rbac.authorization.k8s.io/kubelet-csr created
Cluster "local-up-cluster" set.
use 'kubectl --kubeconfig=/var/run/kubernetes/admin-kube-aggregator.kubeconfig' to use the aggregated API server
serviceaccount/coredns created
clusterrole.rbac.authorization.k8s.io/system:coredns created
clusterrolebinding.rbac.authorization.k8s.io/system:coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
coredns addon successfully deployed.
Checking CNI Installation at /opt/cni/bin
CNI Installation not found at /opt/cni/bin
Installing CNI plugin binaries ...
754a71ed60a4bd08726c3af705a7d55ee3df03122b12e389fdba4bea35d7dd7e /tmp/local-up-cluster.sh.etRH2O/cni.amd64.tgz
/tmp/local-up-cluster.sh.etRH2O/cni.amd64.tgz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
sha256sum: /tmp/local-up-cluster.sh.etRH2O/cni.sha256: no file was verified
Configuring cni
{
 "cniVersion": "1.0.0",
 "name": "containerd-net",
 "plugins": [
   {
     "type": "bridge",
     "bridge": "cni0",
     "isGateway": true,
     "ipMasq": true,
     "promiscMode": true,
     "ipam": {
       "type": "host-local",
       "ranges": [
         [{
           "subnet": "10.88.0.0/16"
         }],
         [{
           "subnet": "2001:db8:4860::/64"
         }]
       ],
       "routes": [
         { "dst": "0.0.0.0/0" },
         { "dst": "::/0" }
       ]
     }
   },
   {
     "type": "portmap",
     "capabilities": {"portMappings": true},
     "externalSetMarkChain": "KUBE-MARK-MASQ"
   }
 ]
}
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap unless testing NodeSwap feature.
```

754a71ed60a4bd08726c3af705a7d55ee3df03122b12e389fdba4bea35d7dd7e /tmp/local-up-cluster.sh.etRH2O/cni.amd64.tgz
/tmp/local-up-cluster.sh.etRH2O/cni.amd64.tgz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
sha256sum: /tmp/local-up-cluster.sh.etRH2O/cni.sha256: no file was verified

@saschagrunert It seems a checksum has broken.

**Comment by saschagrunert** [comment]
@cyclinder yeah since quite a while as it looks like. Fixed that part of the script.

**Comment by saschagrunert** [comment]
@SergeyKanzhelev the tests fail since a long time, ref https://github.com/kubernetes/kubernetes/issues/122183

/skip

**Pull request merged**
