### PR TITLE
Automated cherry pick of #74301: do not return error on invalid mac address in vsphere cloud

### PR DESCRIPTION
**Pull request by andrewsykim**
Cherry pick of #74301 on release-1.11.

#74301: do not return error on invalid mac address in vsphere cloud

### CODE REVIEW

**Comment by andrewsykim** [comment]
/assign @foxish 

PTAL, this is another patch needed in relation to https://github.com/kubernetes/kubernetes/pull/73721 & https://github.com/kubernetes/kubernetes/pull/74082. Sorry for the trouble with so many PRs, much appreciated!

**Comment by andrewsykim** [comment]
/release-note-none

Leaving release note out because it should fall under the original PR (https://github.com/kubernetes/kubernetes/pull/73825)

**Comment by frapposelli** [comment]
Did this miss 1.11.8?

@imkin @divyenpatel can you PTAL?

**Review by divyenpatel — APPROVED** [review]
/approve

**Comment by frapposelli** [comment]
@foxish can you please PTAL, this is critical for 1.11.8

**Comment by foxish** [comment]
As I mentioned on slack, this is indeed far too late - because it needs to have merged by EOD Tuesday for it to finish CI runs and successfully be released. We can target this for 1.11.9; the branch is already frozen and the 1.11.8 is already being built.

**Pull request merged**
