### PR TITLE
Add default=false to usage of kube-apiserver allow-privileged flag

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Users will be clear about default value of `allow-privileged` flag.

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by xiangpengzhao** [comment]
@k8s-bot non-cri e2e test this

**Comment by xiangpengzhao** [comment]
@k8s-bot non-cri e2e test this

**Comment by xiangpengzhao** [comment]
@k8s-bot non-cri e2e test this

**Comment by smarterclayton** [comment]
The default value should already be printed when you run with --help, why would this be necessary?

**Comment by xiangpengzhao** [comment]
I cleared some hard-coded default values of flags in #44196 because they have already been printed as you mentioned. However, I found that only the flags which have been explicitly initialized can have their default value be printed. As for `allow-privileged` of apiserver, giving a hard-coded default value in help info would be more user-friendly. kubelet also has this flag and hard-code the default value in help info. Of course, another way might be explicitly initializing `allow-privileged` to be `faulse` somewhere.

**Comment by xiangpengzhao** [comment]
keep-open

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by xiangpengzhao** [comment]
ping @brendandburns @smarterclayton for final approval with a `/approve no-issue`

**Comment by xiangpengzhao** [comment]
Thanks @dims! When I created this PR, we hadn't required associated issue yet. So please comment `/approve no-issue` instead :)

**Comment by xiangpengzhao** [comment]
Hmm, seems like  `/approve no-issue` doesn't work...

/cc @spxtr 

ref: https://github.com/kubernetes/kubernetes/issues/48163

**Comment by apelisse** [comment]
@xiangpengzhao looks like dims is not an approver. `/approve no-issue` must be performed by someone that can approve at least one file.

**Comment by xiangpengzhao** [comment]
Thanks @apelisse for clarification! 

But, if that's the case, k8s-merge-robot's comment is confusing...
```
This pull-request has been approved by: brendandburns, dims, xiangpengzhao
```

I might need to send another ping @brendandburns or @smarterclayton for final approval with `/approve no-issue` :)

**Pull request merged**
