### PR TITLE
fix golint errors in test/e2e/storage/utils

### PR DESCRIPTION
**Pull request by endyman**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
Fix golint failures of test/e2e/storage/utils

**Which issue(s) this PR fixes:**
#68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by endyman** [comment]
signed CLA

**Review by fejta — COMMENTED** [review]
/lgtm
/approve
/ok-to-test

**Comment by endyman** [comment]
@fejta ran into a pull-kubernetes-e2e-gce timeout and pulled in latest upstream commits just in case but the timeout seems to be not related to the change as tests pass now but my lgtm lable disappeared.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
