### PR TITLE
Add more network statistics in stats/summary endpoint

### PR DESCRIPTION
**Pull request by Chenditang**
**What type of PR is this?**
> /kind api-change
> /kind feature

**What this PR does / why we need it**:
Add RX/TX packets and dropped statistics in stats/summary endpoint
```
     "interfaces": [
      {
       "name": "eth0",
       "rxBytes": 79241773,
       "rxPackets": 28488,
       "rxErrors": 0,
       "rxDropped": 0,
       "txBytes": 2607875,
       "txPackets": 30382,
       "txErrors": 0,
       "txDropped": 0
      }
     ]
```

**Which issue(s) this PR fixes** *(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged)*:
https://github.com/kubernetes/kubernetes/issues/68522

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by Chenditang** [comment]
@dashpole PTAL

**Comment by dashpole** [comment]
/kind enhancement
I'm not sure we want to add more metrics to the kubelet's summary API.  Can you say a bit more about your use-case and why we want these?

**Pull request closed without merging**
