### PR TITLE
Revert "Bump klog to v0.3.2"

### PR DESCRIPTION
**Pull request by krzysied**
Reverts kubernetes/kubernetes#78465

ref #78734 

```release-note
NONE
```

### CODE REVIEW

**Comment by krzysied** [comment]
/assign @liggitt 
/cc @yuwenma 

Based on bisection results this PR caused gce 5k regression.

**Comment by mborsz** [comment]
I think the potential issue is that in klog 0.3.2 in 'if not l.IsSingleMode()" mode, the klog writes to multiple locations, see:
https://github.com/kubernetes/klog/blob/master/klog.go#L859
e.g. in the current gce 5000 node run I see that it writes to both /var/log/kube-apiserver.log and /tmp/kube-apiserver.gce-scale-cluster-master.root.log.INFO.20190612-080835.1.

This potentially can be the reason of the problem we are seeing (kube-apiserver restarts triggered by log rotate).

**Comment by liggitt** [comment]
Note that the 0.3.2 bump was attempting to fix an issue that required the revert of GCE manifest changes. https://github.com/kubernetes/kubernetes/pull/77904

After 0.3.2 was merged, the GCE manifest change revert was reintroduced. I assume that will now need to be reverted as well?

**Comment by liggitt** [comment]
Actually, it looks like the manifest change didn't merge yet. Left a comment at https://github.com/kubernetes/kubernetes/pull/78466#issuecomment-501244365 noting 0.3.2 was reverted.

**Pull request merged**
