### PR TITLE
Automated cherry pick of #76573: refactor detach azure disk retry operation

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #76573 on release-1.12.

#76573: refactor detach azure disk retry operation

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/retest

**Comment by justaugustus** [comment]
For SIG Azure and Release:
/lgtm
/approve

**Comment by feiskyer** [comment]
@andyzhangx The PR needs rebase

**Pull request merged**
