### PR TITLE
Add go-bindata as development dependency

### PR DESCRIPTION
**Pull request by boeboe**
**What this PR does / why we need it**: 
Small update in the developer notes (a go dependency was missing, which I noticed when setting up my own development environment)

**Which issue this PR fixes**: 
Not applicable

**Special notes for your reviewer**:

**Release note**:
N/A

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31259)

### CODE REVIEW

**Comment by boeboe** [comment]
I signed it!

**Comment by boeboe** [comment]
I signed it!

**Comment by boeboe** [comment]
ok to test

**Comment by brendandburns** [comment]
@k8s-bot ok to test

LGTM

Thanks for the PR!

**Pull request merged**
