### PR TITLE
Add PATCH to supported list of proxy subresource verbs

### PR DESCRIPTION
**Pull request by liggitt**
Follow up to #41421 for the proxy subresources

```release-note
The proxy subresource APIs for nodes, services, and pods now support the HTTP PATCH method.
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@liggitt - it seems you also regenerate some docs.

**Comment by liggitt** [comment]
regenerated swagger

**Comment by wojtek-t** [comment]
It seems that some more things need regeneration:

I0426 22:36:45.984] /go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
I0426 22:36:45.984] FAILED   hack/make-rules/../../hack/verify-api-reference-docs.sh	97s

**Comment by rmanak** [comment]
I am still getting the "MethodNotAllowed" error when sending a PATCH request to the proxy subresource. Here is an example:
```
$~>curl http://localhost:8001/api/v1/namespaces/default/services/rel-aida-ima:80/proxy/live -X GET
{
  "status": "OK"
}
```
```
$~> curl http://localhost:8001/api/v1/namespaces/default/services/rel-aida-ima:80/proxy/live -X POST
{"status": "ERR", "error": {"message": "The method is not allowed for the requested URL.", "code": 405}}
```
(^^^ The error message is coming from the service, so it reaches the service)
```
$~>curl http://localhost:8001/api/v1/namespaces/default/services/rel-aida-ima:80/proxy/live -X PATCH
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}
```
^^^ never reached the server!

Also, `--reject-methods` flag doesn't do anything, I tried all combination, didn't help. 

Here is kubectl version:
```
$~/kubernetes/_output/bin> ./kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.2.422+09747e6bee78fb", GitCommit:"09747e6bee78fb8b71356309d6ede84142aee9eb", GitTreeState:"clean", BuildDate:"2017-04-28T01:03:50Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
You are still running against a v1.5.6 server. This fix was server side

**Comment by rmanak** [comment]
On which version of the server this would be available?

**Comment by liggitt** [comment]
1.7

**Pull request merged**
