### PR TITLE
Increase timeout for federated ingress test.

### PR DESCRIPTION
**Pull request by ghost**
Right now federated ingress e2e takes more than 1 minute, as we need to wait for the first clusters ingress to have an IP address allocated to it before creating the others.  Sometimes this takes a while due to GCE loadbalancer backend delays.

``` release-note
Increase timeout for federated ingress test.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33610)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Applying LGTM as per https://github.com/kubernetes/kubernetes/pull/33502

**Comment by jessfraz** [comment]
oh this seems super reasonable to cherry-pick to me, @quinton-hoole do you want to make the PR to release-1.4

**Comment by quinton-hoole** [comment]
@jessfraz I thought our release scripts did that automatically?

**Comment by jessfraz** [comment]
@quinton-hoole I was under the impression it needed to be cherry-picked but now I'm making sure

**Comment by jessfraz** [comment]
cherry-picked in  #34299

**Pull request merged**
