### PR TITLE
Add some descriptions to these certificates/*/type.go files

### PR DESCRIPTION
**Pull request by CKchen0726**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it:**

**Which issue(s) this PR fixes:**
Ref: #99675

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?**
```release-notes
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```release-notes
NONE
```

### CODE REVIEW

**Review by CaoDonghui123 — COMMENTED** [review]
/lgtm

**Comment by ritazh** [comment]
@CKchen0726 Thanks for the PR! Can you pls rebase?

**Comment by liggitt** [comment]
verify job shows openapi doc needs to be regenerated

**Review by errordeveloper — APPROVED** [review]

**Pull request closed without merging**
