### PR TITLE
WIP Test: Revert "[dependencies] update prometheus/client_golang v1.14.0 to v1.16.0"

### LINKED ISSUE #118751: e2e node test failures due to unexpected metric
There's been a quite a few failures across jobs that query node metrics.

 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features
 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial
 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

The test is `E2eNode Suite.[It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api`

* Last passing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1670540343646359552
* First failing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1670555443560189952

[Diff](https://github.com/kubernetes/kubernetes/compare/1ff1a2642...0004ce868) appears to point to https://github.com/kubernetes/kubernetes/pull/118689 which is bump in prometheus client library. Possibly related?

##### Error text:
```
[FAILED] Timed out after 60.006s.
Expected
    <string>: KubeletMetrics
to match keys: {
."kubelet_pod_resources_endpoint_requests_get_allocatable"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_get_allocatable{server_api_version="v1"} => 1 @[0]
	}
	
."kubelet_pod_resources_endpoint_requests_list"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_list{server_api_version="v1"} => 1 @[0]
	}
	
."kubelet_pod_resources_endpoint_requests_total"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_total{server_api_version="v1"} => 2 @[0]
	}
	
}
In [It] at: test/e2e_node/podresources_test.go:862 @ 06/18/23 23:59:02.19

```
#### Recent failures:
[6/19/2023, 11:55:56 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1670868007628312576)
[6/19/2023, 11:54:56 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1670867755999432704)
[6/19/2023, 7:55:55 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1670807608723771392)
[6/19/2023, 7:54:55 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1670807357292023808)
[6/19/2023, 4:34:55 AM ci-cos-cgroupv1-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-serial/1670757024603836416)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by bobbypage**
Reverts kubernetes/kubernetes#118689

It looks like after merging kubernetes/kubernetes#118689 we started to have some CI errors in node e2e jobs fetching metrics. Reverting the dependency update resolved the test failures, as seen in the presubmit job `pull-kubernetes-cos-cgroupv2-containerd-node-e2e-features` passing on this PR with revert.

Fixes https://github.com/kubernetes/kubernetes/issues/118751

### CODE REVIEW

**Comment by bobbypage** [comment]
The `E2eNode Suite: [It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api` in the `pull-kubernetes-cos-cgroupv2-containerd-node-e2e-features` passed here with the revert, but it is failing currently in the CI job https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features.

**Comment by bobbypage** [comment]
cc @bzsuni

/assign @dims

**Comment by pacoxu** [comment]
I tried to fix it in https://github.com/kubernetes/kubernetes/pull/118754. And not sure if that is a valid fix. （need review or my further investigation）

**Pull request closed without merging**
