### PR TITLE
Add no-negcache flag to kube-dns

### LINKED ISSUE #121: kube-dns never resolves if a domain returns NOERROR with 0 answer records once
tl;dr If a nameserver replies status=NOERROR with no answer section to a DNS A question, kube-dns always caches this result. If the domain name actually gets an A record _after_ it's queried through kube-dns, it never (I waited a few days) resolves from the pods, but does resolve outside the container (e.g. on my laptop) just fine.

#### Prerequisites

- Have a domain name `alp.im` and the nameservers are pointed to CloudFlare.
- Have nslookup/dig installed on your workstation.
- Have a minikube cluster ready on your workstation
    - running kubernetes v1.6.0
    - kube-dns comes by default, running `gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1`

#### Step 1: Domain does not exist, query from your laptop

Note `ANSWER: 0`, and `status: NOERROR`

```
$ dig A z.alp.im

; <<>> DiG 9.8.3-P1 <<>> A z.alp.im
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64978
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;z.alp.im.			IN	A

;; AUTHORITY SECTION:
alp.im.			1799	IN	SOA	ivan.ns.cloudflare.com. dns.cloudflare.com. 2025042470 10000 2400 604800 3600

;; Query time: 196 msec
;; SERVER: 2401:fa00:fa::1#53(2401:fa00:fa::1)
;; WHEN: Thu Jun 29 10:51:35 2017
;; MSG SIZE  rcvd: 99
```

#### Step 2: Domain does not exist, query from Pod on Kubernetes

Start a toolbelt/dig container with shell and run the same query:

> ⚠️ Do not exit this container as you will reuse it later. 

Note the response is the same, `ANSWER: 0` and `NOERROR`.

```
$ kubectl run -i -t --rm --image=toolbelt/dig dig --command -- sh
If you don't see a command prompt, try pressing enter.
/ # dig A z.alp.im

; <<>> DiG 9.11.1-P1 <<>> A z.alp.im
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11209
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;z.alp.im.			IN	A

;; AUTHORITY SECTION:
alp.im.			1724	IN	SOA	ivan.ns.cloudflare.com. dns.cloudflare.com. 2025042470 10000 2400 604800 3600

;; Query time: 74 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Jun 29 17:55:46 UTC 2017
;; MSG SIZE  rcvd: 99
```

(Also note that `SERVER: 10.0.0.10#53` which is kube-dns.)

#### Step 3: Create an A record for the domain

Here I use CloudFlare as it manages my DNS. 

image

#### Step 4: Test DNS record from your laptop

Run `dig` on your laptop (note `;; ANSWER SECTION:` and `8.8.8.8` answer):

```
$ dig A z.alp.im

; <<>> DiG 9.8.3-P1 <<>> A z.alp.im
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37570
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;z.alp.im.			IN	A

;; ANSWER SECTION:
z.alp.im.		299	IN	A	8.8.8.8

;; Query time: 196 msec
;; SERVER: 2401:fa00:fa::1#53(2401:fa00:fa::1)
;; WHEN: Thu Jun 29 10:54:44 2017
;; MSG SIZE  rcvd: 53
```

#### Step 5: Test DNS record from Pod on Kubernetes

Run the same command again:

```
/ # dig A z.alp.im

; <<>> DiG 9.11.1-P1 <<>> A z.alp.im
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45420
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;z.alp.im.			IN	A

;; Query time: 0 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Jun 29 18:00:24 UTC 2017
;; MSG SIZE  rcvd: 37
```

Note the [diff](https://www.diffchecker.com/l2GTkuBd):

- still `ANSWER: 0` and `status: NOERROR` (but it resolves just fine outside the cluster)
- `;; AUTHORITY SECTION:` disappeared and `AUTHORITY:` changed to `0` from the previous time we ran this. 
- `;; Query time: 0 msec` (was 79 ms) –I assume it means it's just a cached response.
    - Query time stays as 0 ms no matter how many times I run the same command.

## What else I tried

- **Try it on GKE**: I tried with k8s v1.5.x and v1.6.4.  &rarr; Same issue. (cc: @bowei)
- **Query from a different pod** on minikube: I started a new Pod and queried from there  &rarr; Same issue.
- **Restart kube-dns Pod** &rarr; This **worked** on GKE, but **not** on minikube.

      $ kubectl delete pods -n kube-system -l k8s-app=kube-dns
      pod "kube-dns-268032401-69xk5" deleted

## Impact

I am not sure why this has not been discovered before. I noticed this behavior while using kube-lego on GKE. Once kube-lego applies for a TLS certificate, it polls the domain name of the service (e.g. `example.com/.well-known/<token>`) before asking Let's Encrypt to validate it. Before I create an Ingress with kube-lego annotation, I don't have the external IP yet so I can't configure the domain, but the kube-lego Pod already picks it up and starts querying my domain in an infinite loop. It never succeeds because first time it looked up the hostname, the A record didn't exist, so that result is cached forever. After I add A record, it still can't resolve. The moment I delete kube-dns Pods and they get recreated, it immediately starts working and resolves the hostname and completes the kube-lego challenge.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Adds the [`--no-negcache`](https://linux.die.net/man/8/dnsmasq) flag to prevent dnsmasq from caching negative (NXDOMAIN) responses. More details on why this is desirable [here](https://github.com/kubernetes/dns/issues/121).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes kubernetes/dns#121

**Special notes for your reviewer**:
Thanks to @rsmitty (https://rsmitty.github.io/KubeDNS-Tweaks/) and @coresolve (https://github.com/kubernetes/dns/issues/121#issuecomment-334045196) for pointing us in the right direction.

**Release note**:
```release-note
Add --no-negcache flag to kube-dns to prevent caching of NXDOMAIN responses.
```

### CODE REVIEW

**Comment by cblecker** [comment]
@bowei Another question.. is this worth picking back to 1.8 and/or 1.7?

**Comment by ahmetb** [comment]
@cblecker the issue is not critical enough, so that pretty much I was the only one noticing it for a while https://github.com/kubernetes/dns/issues/121. I'm not sure if it qualifies for backporting.

**Comment by cblecker** [comment]
Yeah, that makes sense to me. It's a bugfix in the sense that it's correcting unintended behaviour, but you're right, probably not enough reports of it causing problems to pick it backwards.

**Comment by bowei** [comment]
Can you check that kubeadm also gets this update?

**Comment by bowei** [comment]
(should be findable via git grep for mentions of the kube dns image)

**Comment by cblecker** [comment]
Found and added the flag to kubeadm as well.

It also looks like minikube uses it here:
https://github.com/kubernetes/minikube/blob/3acb2a18a9d8e950f51e7bd5bb6d5cc124f2373c/deploy/addons/kube-dns/kube-dns-controller.yaml#L98-L121

and kops uses it here:
https://github.com/kubernetes/kops/blob/7b65c5449de06d585d862314b7905f1786292246/upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template#L150-L172

**Comment by ahmetb** [comment]
`<off-topic>` @cblecker it doesn't sound a great model that we need to update kubeadm/kops every time we update these files. they should be able to pick up these changes from upstream (this repo) `</off-topic>`

**Comment by cblecker** [comment]
100% agree. When I was digging into this, I found there were also some references where kube-dns wasn't bumped up to 1.14.5 (https://github.com/kubernetes/kubernetes/pull/53668 and https://github.com/kubernetes/minikube/issues/2021#issuecomment-335549548). Having a consistent way to define and deploy kube-dns as an addon would be great.

That being said, there is also a proposal to switch to coredns for cluster DNS services (https://github.com/kubernetes/community/pull/1100), so maybe that would be the right time to fix this?

**Comment by bowei** [comment]
@ahmetb -- the update strategy for kubeadm needs to be resolved

**Comment by cblecker** [comment]
from chatter in #sig-testing it looks like the kubeadm job may be broken. if it fails (even though it's non-blocking), we should probably wait until it's fixed to validate this change.

**Comment by cblecker** [comment]
/assign @krousey
for approval

**Comment by cblecker** [comment]
kubeadm test issue tracked in #53570

**Comment by cblecker** [comment]
ping @krousey for approval

**Pull request merged**
