### PR TITLE
Fix first contribution link in pr template

### PR DESCRIPTION
**Pull request by eddiezane**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR fixes a dead link in the GitHub pull request template. The page appears to have been reorganized.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test
/lgtm
/approve

Thank you for this! 🚀

**Comment by spiffxp** [comment]
re: pull-kubernetes-node-e2e-containerd, it's been timing out most of the day, it's non-blocking https://github.com/kubernetes/kubernetes/issues/89847

**Pull request merged**
