### PR TITLE
Kubectl maintenance mode

### PR DESCRIPTION
**Pull request by dshulyak**
Implements two commands for kubectl:
- kubectl maintenance <node> on
  Adds maintenance:NoSchedule taint to a node, and add
  nodeoutage:NoExecute toleration to all pods on same node
- kubectl maintenance <node> off
  Removes mentioned taint and toleration from node and all pods
  on that node

related: #30272

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33939)

### CODE REVIEW

**Comment by dshulyak** [comment]
This PR includes https://github.com/kubernetes/kubernetes/pull/32498

**Comment by dshulyak** [comment]
cc @davidopp @kevin-wangzefeng

**Comment by dshulyak** [comment]
@davidopp @kevin-wangzefeng Hi, i think i am almost done with it. Implemented according to https://github.com/kubernetes/kubernetes/issues/30272#issuecomment-243069603. Added unit tests for all parts of this feature, and one basic e2e test.

 Can I get at least design approval before i will add more destructive e2e tests for taint-based eviction?

**Comment by davidopp** [comment]
I assume only the last commit is relevant here?

For the others, I'm worried about overlap with the work @kevin-wangzefeng is doing. It might be better to wait until he has his PR out. Last I heard he said he would have it ready some time this week.

**Comment by mml** [comment]
Based on the discussion in #30272 there is more design needed and I think this PR can be closed @dshulyak

**Comment by dshulyak** [comment]
@mml sorry, i dont understand what do you mean. this pr is implemented exactly as discussed in #30272 . the only thing is that now it needs to be rebased on top of https://github.com/kubernetes/kubernetes/issues/34825

**Comment by gmarek** [comment]
@davidopp Is this still a thing? I think we should close this PR, as it'll need to be rewritten after ongoing taint/toleration changes are merged.

**Pull request closed without merging**
