### PR TITLE
remove release-notes of reverted PRs

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR removes the release-notes of reverted PRs from 1.32 changelog.
(ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1733991200800589)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve

My fault, I should have detected that during the review of the release note

**Comment by Vyom-Yadav** [comment]
/lgtm 

Pointers for the RT: 

- Next cycle, when updating owners, we also need to update: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/OWNERS

- We also need to update: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.32/release-notes

**Comment by justaugustus** [comment]
Good highlights, @Vyom-Yadav. I've filed https://github.com/kubernetes/sig-release/issues/2695 for that.

/lgtm
/approve

**Pull request merged**
