### PR TITLE
kubectl help xyz should print to stdout not stderr

### LINKED ISSUE #13522: kubectl's help sometimes prints to stderr
Help output should always go to stdout for easy paging. This is particularly important for the client, which is what people will use most. Currently the main help output goes to stdout, but subcommands' help goes to stderr:

```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}
$ ./kubectl help > help-stdout 2> help-stderr
$ ./kubectl help create > help-create-stdout 2> help-create-stderr
$ wc -l help*
  47 help-create-stderr
   0 help-create-stdout
   0 help-stderr
  62 help-stdout
 109 total
```

Further improvements could be to detect if the output is a terminal, and use `$PAGER`, but making it easy to pipe to `$PAGER` is a great first step!

### PR DESCRIPTION
**Pull request by dims**
Make sure that commands like "kubectl help create" print to stdout.

Fixes #13522

### CODE REVIEW

**Comment by eparis** [comment]
I think @fabianofranz fixed this in cobra just recently....

**Comment by dims** [comment]
@eparis : yep @fabianofranz commented on a previous PR (https://github.com/kubernetes/kubernetes/pull/26077#issuecomment-230827619). The test case is still useful i think

**Comment by dims** [comment]
Closing as the spf13 PR has merged already

**Comment by fabianofranz** [comment]
I'm going to PR a new Cobra rebase later today.

**Pull request closed without merging**
