### PR TITLE
examples/hazelcast - pass namespace via env, reduce cpu requirements and inc image version

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @pires

### CODE REVIEW

**Comment by thockin** [comment]
@pires for eyes

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (31/30 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:35259 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZEglt-003wod-A5
	for robin@eikaas.no; Mon, 13 Jul 2015 18:40:05 +0200
Date: Mon, 13 Jul 2015 09:40:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1436805600;
	bh=jf5/GeqTMihToV7yMFNiaYOwkB6k+asV/Ri2HdBOqQk=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lDEg7dFRhndtlnYsRgFuoE0BPitRsnLASy1Kd4Prlg1RglZIP1YX6NWPAKm7YIBTO
	 HM2IPoiYRvMN+CML1zWMtpH0Svae7uP97lLfxbac36ZTvrr/TOhtr+S+otXvHOjOpz
	 7Z5f/+tWQU7tgRKs9Yr/IEVh24ByOGdgF4Yfh4UM=

**Comment by pires** [comment]
This will conflict with https://github.com/GoogleCloudPlatform/kubernetes/pull/11107.

**Comment by pires** [comment]
@mwielgus if you want, you could rebase my PR into your branch and address @thockin comments (from said PR). It would be nice since I'm traveling and will only be able to take care of it on later in the week.

**Comment by pires** [comment]
Just managed to update #11107. @mwielgus your PR LGTM if merged with my PR.

**Comment by mwielgus** [comment]
Fixes  #10731

**Comment by thockin** [comment]
LGTM

**Pull request merged**
