### PR TITLE
[HPA e2e] Calculate more precise consumed CPU usage for N replicas

### PR DESCRIPTION
**Pull request by pbeschetnov**
#### What type of PR is this?
/kind feature
/kind flake

#### What this PR does / why we need it:

With the current HPA e2e tests with behavior setup of:
- pod CPU request = `500m`
- target CPU utilization = `25%`
- usage for single replica = `110m`

and

- usage intended for recommending n pods = `n * {usage for single replica}`

the consumed CPU per n replicas would be

| replicas | recommendation = replicas * usage / request / target |
|---|---|
|1|0.88|
|2|1.76|
|3|2.64|
|4|3.52|
|5|4.4|
|6|5.28|
|7|6.16|
|8|7.04|
|9|7.92|
|10|8.8|

As shown, the usage is more balanced for 4-5 replicas, and skewed for <=3 and >=6 replicas — this leads to flaky tests when consumed CPU by the ResourceConsumer fluctuates and goes over the intended usage. Example:

1. Requesting usage for 2 replicas.
2. RC consumer: sending request to consume 220 millicores.
3. Actual usage: 254 millicores.
4. The recommendation: `254 / 500 / 0.25 = 2.032` — rounding up to 3.
5. Here we correctly recommended 3, but the test setup expected 2, so the test failed.

For >=9 replicas it even produces not enough usage for the intended recommendation.

Instead of using this approach, I suggest calculating the replica usage for `n` pods as if `n - 0.5` replicas consume all CPU matching the target. It would be:

`(replicas - 0.5) * request * targetPercentage / 100%`

The 0.5 replica reduction is to accommodate for the deviation between the actual consumed cpu and requested usage by the ResourceConsumer. HPA rounds up the recommendations. So, if the usage is e.g. for 3.5 replicas, the recommended replica number will be 4.

This will eliminate flakiness in HPA e2e tests with behavior.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pbetkier** [comment]
/ok-to-test
/lgtm

nice idea 👍 , let's see how it helps with flakes

**Comment by pbeschetnov** [comment]
pull-kubernetes-e2e-autoscaling-hpa-cpu logs are gone
/retest

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
