### PR TITLE
use slices library instead of custom function

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

use slices library instead of custom function

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
Are there other opportunities like this "nearby" (same plugin or in the scheduler)?

This is a good change, but it's a bit small by itself.

**Review by pohly — APPROVED** [review]
/lgtm

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
