### PR TITLE
Increase quota-bytes for etcd in v3 mode

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #20504

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36240)

### CODE REVIEW

**Comment by wojtek-t** [comment]
Fixed verify - reapplying label.

**Comment by xiang90** [comment]
4GB is really the dangerous line for etcd (see Chubby's or PaxosDB's limit? I know ZK or Consul wont handle this well). I hope people who run large clusters have good networking + disk...  I might optimize this eventually, but do not expect that we can make this number 40GB. Just a reminder.

**Comment by wojtek-t** [comment]
>
but do not expect that we can make this number 40GB. Just a reminder.

@xiang90 - yes sure; That's completely fine.

**Comment by wojtek-t** [comment]
Also - I would like to reduce this value in the future, but I've seen it happening in large clusters, to increasing it for now. I'm planning to understand this and decrease it in future releases.

**Comment by xiang90** [comment]
> Also - I would like to reduce this value in the future, but I've seen it happening in large clusters, to increasing it for now. I'm planning to understand this and decrease it in future releases.

Awesome. I would love to help.

**Pull request merged**
