### PR TITLE
update node-problem-detector v0.8.9

### PR DESCRIPTION
**Pull request by mcshooter**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
With the recent release in Node-problem-detector, the version needs to be updated to v0.8.9 with updated default sha values.

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Comment by mcshooter** [comment]
cc/ @Random-Liu  @jeremyje

**Comment by Random-Liu** [comment]
This change is safe to me.

However, can you elaborate a bit more about why this can fix the test issue? :)

Thanks a lot for looking into this BTW!

**Pull request merged**
