### PR TITLE
Revert "Test Service creation -> endpoint generation latency"

### PR DESCRIPTION
**Pull request by brendandburns**
Reverts GoogleCloudPlatform/kubernetes#9354

### CODE REVIEW

**Comment by brendandburns** [comment]
@lavalamp

**Comment by brendandburns** [comment]
merging on one green from Shippable...

**Comment by lavalamp** [comment]
Why did we revert this instead of putting it in flaky??

**Comment by lavalamp** [comment]
OK, I see why and I'll have a fix shortly.

**Pull request merged**
