### PR TITLE
Cleanup boilerpate.py

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- reformatted with https://github.com/psf/black
- fixed some of the https://github.com/pylint-dev/pylint warnings
- used f-strings

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by bart0sh** [comment]
/assign @thockin @liggitt @BenTheElder 
Please, review or close if you're not interested.

**Review by pohly — COMMENTED** [review]
Looks good to me, but I am not sure whether it has enough value to justify touching all these code lines.

I'll defer to others about that.

**Comment by bart0sh** [comment]
@pohly The idea was to format and cleanup all Python code in the k/k codebase to look consistent. There are only 7 .py files in the project, so it's not a big work at all to clean them up. I decided to start with one file to see if community likes it or not. So far I don't see much interest in this, so I'm ok to just close it.

**Pull request merged**
