### PR TITLE
Cleanup feature gate check for SelectorIndex

### PR DESCRIPTION
**Pull request by aojea**
The feature is GA since 1.20

https://github.com/kubernetes/kubernetes/blob/522cd18f87d0ffe1bc6d92471a4a2b540e5dcaec/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L142-L148

/kind cleanup
```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

**Comment by liggitt** [comment]
can you drop the SelectorIndex field as well?

**Comment by aojea** [comment]
> can you drop the SelectorIndex field as well?

yep

**Pull request merged**
