### PR TITLE
Avoid explicit mention of glusterfs in error strings.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by rootfs** [comment]
I'd like to keep the message prefix, it makes parsing easy.

**Comment by humblec** [comment]
@rootfs the prefix strings are taken out of plugin by hearing its ugly and add duplicate information as the strings any way have `glusterfs.go` in it. :) , so the attempt here as well.

**Pull request merged**
