### PR TITLE
Update nodelocaldns yaml to use image with custom Stubdomains support

### PR DESCRIPTION
**Pull request by prameshj**
Updated the yaml to use node-cache image that supports custom stubDomains and upstream servers configured in kube-dns config map.
Also changed it to use 2 listen ips - both the link local and the kube-dns service ip address so that the feature can be used without having to update --cluster-dns flag. This was described in the beta KEP - https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#design-details
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#design-details

```docs

```

### CODE REVIEW

**Comment by prameshj** [comment]
cc @MrHohn

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by ghostsquad** [comment]
These variables are unfortunately named. I spent the last several hours looking at related PRs, Issues, and design docs across multiple repos trying to figure out variable values. All to realize that 3 of these are set by the image, the other 2 are something we have to manage. 😢 

Any chance in a future revision, the values that need to be `sed` replaced could be easily identifiable, while the other vars that are managed by the image could be read as such? e.g.

`__CHANGEME__DNS_DOMAIN__` (set by us)
`__MANAGED_BY_IMAGE_DO_NOT_CHANGE__CLUSTER_DNS__` (set by image)

**Comment by prameshj** [comment]
> These variables are unfortunately named. I spent the last several hours looking at related PRs, Issues, and design docs across multiple repos trying to figure out variable values. All to realize that 3 of these are set by the image, the other 2 are something we have to manage. 
> 
> Any chance in a future revision, the values that need to be `sed` replaced could be easily identifiable, while the other vars that are managed by the image could be read as such? e.g.
> 
> `__CHANGEME__DNS_DOMAIN__` (set by us)
> `__MANAGED_BY_IMAGE_DO_NOT_CHANGE__CLUSTER_DNS__` (set by image)

Sorry this wasn't documented clearly, @ghostsquad. I am updating the documentation in https://github.com/kubernetes/kubernetes/pull/84383

**Comment by dmitry-irtegov** [comment]
Hello!  
Am I correct that this PR exports stubDomains only from kube-dns configmap, but not from coredns?

**Comment by prameshj** [comment]
> Hello!
> Am I correct that this PR exports stubDomains only from kube-dns configmap, but not from coredns?

That is correct.. WE can add support for coreDNS stubdomains here as well. As I understand, coreDNS configmap contains the entire coreFIle correct? We will need to parse out the custom stubdomain sections from it. Is there a better way, @johnbelamaric ?

**Comment by johnbelamaric** [comment]
That could be hard, if they are not following some standard way of doing things. I mean, each stub domain can have a separate plugin chain, which may enable things not found in the nodelocaldns coredns image.

Still, it's probably worth the effort, you'll just have to have something that can reject the config if it's not valid for the binary; that is, if it fails to parse. There is a library/tool for helping with Corefile migration on upgrades, it *might* be helpful here: https://github.com/coredns/corefile-migration

**Pull request merged**
