### PR TITLE
Fix filter topology endpoint

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
When NodeLabel is empty, some processing does not meet expectations.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix filter topology endpoint
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @andrewsykim @robscott 
you have this more fresh than anybody ;)

**Comment by robscott** [comment]
@andrewsykim is more familiar with this code, but wanted to let you know that this feature is [deprecated](https://github.com/kubernetes/kubernetes/pull/96736) and will be removed soon. We're working on adding support for a [different approach](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2433-topology-aware-hints/README.md) in 1.21.

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/enhancements/issues/536#issuecomment-843624282 commented, it will be removed in this release cycle of 1.22. 
/cc @robscott

**Review by andrewsykim — COMMENTED** [review]
I agree this is probably not worth doing since we're going to remvoe this in v1.22

**Pull request closed without merging**
