### PR TITLE
clean temporary para for require-kubeconfig

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
delete temporary require-kubeconfig

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
/hold
until I resolve the aws-kops CI.

**Comment by zhangxiaoyu-zidif** [comment]
/cc @liggitt 
the aws-kops CI fixed. =)

**Comment by zhangxiaoyu-zidif** [comment]
/cc @yujuhong  for approve.
thanks~

**Comment by yujuhong** [comment]
Could you also fix the typo in the commit message?

**Comment by zhangxiaoyu-zidif** [comment]
@yujuhong Great， done =）

**Pull request merged**
