### PR TITLE
remove the rest of the non-generated clients from the kubectl code

### PR DESCRIPTION
**Pull request by deads2k**
Die `Client` Die!

It's always bigger than you think.  Last bit @kargakis after this, it's gone.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32316)

### CODE REVIEW

**Comment by kargakis** [comment]
LGTM

**Comment by soltysh** [comment]
I think this change might break Scheduled Jobs and unfortunately there's no test verifying this :fearful:. I'm removing lgtm label until I try this out locally, which I'm doing right now.

**Comment by soltysh** [comment]
Verified manually against SJ, works as expected.

**Comment by soltysh** [comment]
@k8s-bot test this issue #31570.

**Pull request merged**
