### PR TITLE
delete unused para

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
NONE
```release-note
```None

### CODE REVIEW

**Comment by jianglingxia** [comment]
@cblecker @ncdc  can you label the lgtm ? thanks for you very much!

**Comment by cblecker** [comment]
/assign @deads2k 
/unassign

I don't know enough about this file to review this change.

**Comment by deads2k** [comment]
@lavalamp I don't know what this does.  I'd just as soon leave it alone, but maybe you know more.

**Comment by jianglingxia** [comment]
/assign @jsafrane
thanks for you to review

**Comment by jsafrane** [comment]
I don't know anything about third party resources and client-go
/unassign

**Comment by jianglingxia** [comment]
cc @dchen1107 @lavalamp

**Comment by jianglingxia** [comment]
trouble to you @wojtek-t
the pr always leave it nearly one month ，I read the owner file you in it，thanks for your review！

**Comment by wojtek-t** [comment]
I don't know what it is. Maybe @caesarxuchao can help since this is in client-go.
/unassign @wojtek-t
/assign @caesarxuchao

**Comment by jianglingxia** [comment]
/assign @caesarxuchao
thanks for your review

**Comment by jianglingxia** [comment]
/assign @caesarxuchao
thanks for your review

**Comment by cblecker** [comment]
Unless @caesarxuchao or @lavalamp come back with something different in the next day or so, I think we should just close this out as unneeded. These constants are not harming anything that I see by being there.

**Comment by caesarxuchao** [comment]
@jianglingxia, the path suggests that the code is forked from somewhere, so I agree with @cblecker that we'd better just leave it as is. I'm closing the PR.

**Pull request closed without merging**
