### PR TITLE
Remove import of internal api package in generated external-versioned listers

### PR DESCRIPTION
**Pull request by caesarxuchao**
Follow up of https://github.com/kubernetes/kubernetes/pull/44523

One line change in cmd/libs/go2idl/lister-gen/generators/lister.go, and simple changes in pkg/apis/autoscaling/v2alpha1/register.go, other changes are generated.

The internal api package will be eliminated from client-go, so these imports should be removed. Also, it's more correct to report the versioned resource in the error.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this

**Comment by lavalamp** [comment]
/lgtm
/approve

Seems like a clear improvement no matter what you're trying to do :)

**Comment by caesarxuchao** [comment]
Yep. Thanks.

**Pull request merged**
