### PR TITLE
Update influxdb to 0.12

### LINKED ISSUE #27630: Influxdb crash-looping in GCE soak test
Part of the investigation #27374. This is causing multiple failures in the GCE soak tests.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/5764#k8sio-schedulerpredicates-serial-validates-that-nodeaffinity-is-respected-if-not-matching

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:216
Expected error:
    <*errors.errorString | 0xc82146e090>: {
        s: "Not all pods in namespace 'kube-system' running and ready within 2m0s",
    }
    Not all pods in namespace 'kube-system' running and ready within 2m0s
not to have occurred
```

```
I0617 00:17:09.999659    3501 kubelet.go:2661] SyncLoop (PLEG): "monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"c9fcb6cf-325a-11e6-8bfb-42010af00002", Type:"ContainerDied", Data:"195b8ab1a7bac429580729f2a2ed1d1b1b4b73ec754d5656326ef9049bfecc28"}
I0617 00:17:10.010995    3501 manager.go:2303] checking backoff for container "influxdb" in pod "monitoring-influxdb-grafana-v3-duwdw"
I0617 00:17:10.011408    3501 manager.go:2317] Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)
E0617 00:17:10.011504    3501 pod_workers.go:183] Error syncing pod c9fcb6cf-325a-11e6-8bfb-42010af00002, skipping: failed to "StartContainer" for "influxdb" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)"
I0617 00:17:12.529374    3501 server.go:959] GET /healthz: (56.191µs) 200 [[curl/7.26.0] 127.0.0.1:51388]
I0617 00:17:20.789572    3501 container_manager_linux.go:614] Found 59 PIDs in root, 59 of them are not to be moved
I0617 00:17:22.544930    3501 server.go:959] GET /healthz: (25.578µs) 200 [[curl/7.26.0] 127.0.0.1:51392]
I0617 00:17:24.541100    3501 manager.go:2303] checking backoff for container "influxdb" in pod "monitoring-influxdb-grafana-v3-duwdw"
I0617 00:17:24.541233    3501 manager.go:2317] Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)
E0617 00:17:24.541290    3501 pod_workers.go:183] Error syncing pod c9fcb6cf-325a-11e6-8bfb-42010af00002, skipping: failed to "StartContainer" for "influxdb" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)"
I0617 00:17:32.559331    3501 server.go:959] GET /healthz: (34.03µs) 200 [[curl/7.26.0] 127.0.0.1:51397]
I0617 00:17:36.540173    3501 manager.go:2303] checking backoff for container "influxdb" in pod "monitoring-influxdb-grafana-v3-duwdw"
I0617 00:17:36.540340    3501 manager.go:2317] Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)
E0617 00:17:36.540389    3501 pod_workers.go:183] Error syncing pod c9fcb6cf-325a-11e6-8bfb-42010af00002, skipping: failed to "StartContainer" for "influxdb" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=influxdb pod=monitoring-influxdb-grafana-v3-duwdw_kube-system(c9fcb6cf-325a-11e6-8bfb-42010af00002)"
I0617 00:17:42.572727    3501 server.go:959] GET /healthz: (38.284µs) 200 [[curl/7.26.0] 127.0.0.1:51401]
```

Some more context in this comment https://github.com/kubernetes/kubernetes/issues/27374#issuecomment-225969139

@dchen1107 could you find an appropriate owner for this?

cc @kubernetes/sig-node @Random-Liu

### PR DESCRIPTION
**Pull request by piosz**
fix #27630 

``` release-note
Update influxdb to 0.12
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31519)

### CODE REVIEW

**Comment by piosz** [comment]
Bumping priority - this change requires long lasting tests in soak cluster, so we should merge it ASAP so that we can test it properly before 1.4

**Comment by mwielgus** [comment]
lgtm, if all test pass

**Comment by mwielgus** [comment]
```
Godeps Verify failed.
Removing /tmp/gopath.r8uE16
FAILED   hack/make-rules/../../hack/verify-godeps.sh	424s
```

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
