### PR TITLE
[release-1.21] [go] Update Go to 1.16.14

### PR DESCRIPTION
**Pull request by xmudrii**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Update Go to 1.16.14.

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/2425

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Golang 1.16.14
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @cpanato @saschagrunert @palnabarun @puerco @justaugustus
cc @kubernetes/release-engineering

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve
/assign @dims @liggitt

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
