### PR TITLE
Removes TTY flag from etcd image build process

### PR DESCRIPTION
**Pull request by seemethere**
**What this PR does / why we need it**:
etcd image building fails when running without TTY with `the input device is not a TTY`

Related:
- https://stackoverflow.com/q/43099116/5285457

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
@jpbetz - i'm happy to approve if this looks good to you

**Comment by jpbetz** [comment]
@roberthbailey Thanks! Yes, looks good to me.

**Pull request merged**
