### PR TITLE
Trace.Step() performs an unnecessary alloc

### PR DESCRIPTION
**Pull request by smarterclayton**
Showed up in some stress testing profiles.

### CODE REVIEW

**Comment by wojtek-t** [comment]
Nice!

@fgrzadkowski - FYI

**Comment by smarterclayton** [comment]
Actually one more optimization.  I don't think we ever create a trace without allocating.  So I'm going to change to avoid an array resize for the common case.

**Comment by smarterclayton** [comment]
Updated to avoid allocating the step array until we need it, then initialize it to an initial capacity of 6 to avoid ever having to grow it in later steps.

**Comment by wojtek-t** [comment]
Still LGTM

**Pull request merged**
