### PR TITLE
kubeadm: Use the release-1.8 branch by default

### LINKED ISSUE #427: Use the stable version of the release-1.8 branch in kubeadm v1.8
Described in https://github.com/kubernetes/kubeadm/blob/master/docs/release-cycle.md
A similar change to https://github.com/kubernetes/kubernetes/pull/47440 should be made

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

In line with https://github.com/kubernetes/kubeadm/blob/master/docs/release-cycle.md, the default branch for kubeadm to deploy should be bumped right before the `rc.1`.
This can even be manually merged by the someone from the release team.

Adding do-not-merge until we're ready for the release candidate.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes: https://github.com/kubernetes/kubeadm/issues/427

**Special notes for your reviewer**:

**Release note**:

```release-note
kubeadm: Use the release-1.8 branch by default
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/kubernetes-release-managers

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm

**Review by dmmcquay — APPROVED** [review]
/lgtm

**Comment by roberthbailey** [comment]
@abgworrall - ping for review

**Comment by abgworrall** [comment]
/lgtm
@roberthbailey , FWIW I've got this PR in my branch-manager checklist; I plan to manually merge it into master right before I cut the first RC build for 1.8.

**Comment by spiffxp** [comment]
This is going to fail until we actually cut a 1.8 release?
```
=== RUN   TestSubCmdCertsCreateFilesWithFlags
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.8.txt" Status: 404 Not Found
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases	1.510s
```

**Comment by luxas** [comment]
@spiffxp Yes 😞 
I'd like to automatically update things so that `stable-1.8` is updated when the `v1.8.0-rc.1` is cut (`stable` would still be `v1.7.x` at that point), but now `stable-1.8` is created first when `v1.8.0` is cut

**Comment by luxas** [comment]
And oh yeah, thanks for pointing that unit failure out, had missed that.
Will fix so this can get merged before `stable-1.8` exists

**Comment by abgworrall** [comment]
Q: does this PR also need to be fast-forwarded into `release-1.8` prior to `1.8.0-rc.1` is cut ? Or does it merely need to be in master for that rc to work correctly ?

**Comment by luxas** [comment]
All tests are now passing, merge however you like.
(Manual merge is indeed faster if you are in a hurry to cut the rc now)
As also discussed on Slack, you need to forward the release-1.8 branch after this is merged to master

**Pull request merged**
