### PR TITLE
Fix- Broken link with wrong url

### PR DESCRIPTION
**Pull request by vishakhanihore**
fixes https://github.com/kubernetes/website/issues/16476

```release-note
Fixing broken link on production
```

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@kubernetes/patch-release-team Please check

**Comment by vishakhanihore** [comment]
@pwittrock @smarterclayton Please Review

**Comment by vishakhanihore** [comment]
@pwittrock @smarterclayton Please Review

**Comment by idealhack** [comment]
thank you but 1.6 is EOL and not accept patches anymore, see https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#114-and-older, also we only accept bug-fixes, no need for typo cleanups.

**Pull request closed without merging**
