### PR TITLE
Remove shell services test

### LINKED ISSUE #4184: Rewrite services.sh end-to-end in Go
Part of umbrella issue #3130. cc @satnam6502 @filbranden

And @thockin 

Also, definitely good luck to whoever attempts this one.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fixes #4184

After merging #11056 these tests are covered by tests in Go:
- tests 1, 3 and 4 by "should be able to up and down services"
- tests 2 and 5 by "should work after restarting kube-proxy"
- tests 6 and 7 by "should work after restarting apiserver"

These new tests seem to be stable.

cc @brendandburns @zmerlynn @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
woohoo!

**Comment by roberthbailey** [comment]
Assigning to @thockin to verify that the new tests provide sufficient coverage.

**Comment by wojtek-t** [comment]
@thockin - can you please take a look (or delegate)?

**Comment by wojtek-t** [comment]
@thockin - ping (as requested by email)

**Comment by thockin** [comment]
LGTM :'(

**Pull request merged**
