### PR TITLE
There's no need to set moveRequestCycle and do broadcast twice.

### PR DESCRIPTION
**Pull request by lixiang233**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Delete some redundant code,  movePodsToActiveOrBackoffQueue has already set moveRequestCycle and do Broadcast, there's no need to do it in MoveAllToActiveOrBackoffQueue
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/kind cleannup

LGTM to me, let's see if it breaks any tests?

https://github.com/kubernetes/kubernetes/blob/5844bc3b9f055dc006ff1bf128ba4037ded93cff/pkg/scheduler/internal/queue/scheduling_queue.go#L524-L525

**Comment by lixiang233** [comment]
I signed it

**Review by draveness — COMMENTED** [review]
/lgtm

**Pull request merged**
