### PR TITLE
Fix typos under pkg/scheduler

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```
No

### CODE REVIEW

**Comment by denkensk** [comment]
/lgtm 

Thanks @ArangoGutierrez

**Review by Huang-Wei — COMMENTED** [review]
/approve

Thanks @ArangoGutierrez .

**Pull request merged**
