### PR TITLE
add missing comments in staging/src/k8s.io/api/core/v1/types.go

### PR DESCRIPTION
**Pull request by ut-wangbo**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by ut-wangbo** [comment]
@wojtek-t @tallclair

**Comment by thockin** [comment]
You need to rebuild generated docs (`hack/update-codegen.sh`) and run gofmt

**Comment by thockin** [comment]
ping @ut-wangbo do you want someone to take this over?

**Comment by thockin** [comment]
Superseded by https://github.com/kubernetes/kubernetes/pull/128686

**Pull request closed without merging**
