### PR TITLE
Update kube-apiserver flag comments

### PR DESCRIPTION
**Pull request by johscheuer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR updates some of the `kube-apiserver` flag help text to make the usage of `--shutdown-delay-duration` more clear. I stumbled over this when I was working on https://github.com/kubernetes/website/pull/21185.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @logicalhan 
(small comment change, thanks!)

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by ping035627 — APPROVED** [review]

**Pull request merged**
