### PR TITLE
Headless services should not need to declare ports

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
Seems pretty broken :(

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by vishh** [comment]
LGTM.

**Comment by thockin** [comment]
Mike,

Can you remind me what problem this was solving?  I'm trying to figure out if there's any repercussions for DNS SRV records.

We should probably ALSO validate that any ports that are defined on a headless Service have `port` == `targetPort`, since there's no remapping capabilities.

**Comment by mikedanese** [comment]
> Can you remind me what problem this was solving? I'm trying to figure out if
> there's any repercussions for DNS SRV records.

Requiring ports for headless services was not intended. I confirmed this with
Brian. I want to be able to aggregate endpoints using the endpoints controller
with a headless service and to do that now I need to set some bogus ports. Not
sure what that would look like for DNS.

**Comment by jimmidyson** [comment]
@mikedanese As @thockin asked above, what does this mean for the DNS SRV records if a port isn't specified?

**Comment by mikedanese** [comment]
We should not create SRV records for headless services if SRC records require a port.

**Comment by jimmidyson** [comment]
@mikedanese So what do the endpoints of such a service look like?

**Comment by jimmidyson** [comment]
@mikedanese I assume you're manually creating endpoints for this kind of service?

**Comment by mikedanese** [comment]
No. The endpoints are still populated.

**Comment by thockin** [comment]
I think I disagree.  If the user wants to specify a port, we can do
multi-record response for SRV just as well as we can do A.

**Comment by mikedanese** [comment]
@thockin sorry, what statement do you disagree with?

**Comment by thockin** [comment]
> @thockin sorry, what statement do you disagree with?

"We should not create SRV records for headless services if SRC [sic]
records require a port."

**Comment by mikedanese** [comment]
Ok thanks. You are saying if the user provides a port for a headless service we should create a SRV record? And if they do not we create an A record?

**Comment by thockin** [comment]
We always create an A record for the clusterIP (normal services) or for
each backend (headless services).  We should create equivalent SRV records
for any port that the user defines and names (only named ports get SRV) in
the same fashion

**Comment by mikedanese** [comment]
That SGTM and is what we currently do.

> We should not create SRV records for headless services if SRV records require a port.

I misspoke when I said this. I meant to say: We should not create SRV records for headless services _with no specified ports_ if SRV records require a port. Does that sound good?

**Comment by thockin** [comment]
yes, SRV is intrinsically port-centric :)

**Pull request merged**
