### PR TITLE
Adding links to relevant docs from API types.

### PR DESCRIPTION
**Pull request by vmarmol**
Partially addresses #3606.

### CODE REVIEW

**Comment by vmarmol** [comment]
PTAL when you get a chance @bgrant0607. This is for v1beta2, if it looks good I'll do the same for the other two.

My only concern is that this seems brittle in that we may change the API or the docs and break the links. But then again, the API is stable right :)

**Comment by bgrant0607** [comment]
I really wanted the links to show up in the swagger output. For subobjects, the links could be embedded in field descriptions. For top-level objects, we'll need a way to pass the documentation from the registry to the API handler installer. @lavalamp, @smarterclayton, or @nikhiljindal could help with that.

**Comment by bgrant0607** [comment]
Going to merge this as is.

**Comment by nikhiljindal** [comment]
There is https://github.com/GoogleCloudPlatform/kubernetes/issues/3059 filed for including doc links in swagger documentation.

**Pull request merged**
