### PR TITLE
Extract EtcdHelper interface

### LINKED ISSUE #8192: Revert #7567 after it's been in a few versions (July or August 2015)
#7567 adds the ability to migrate etcd keys to a new prefix. This is fine, but it'll be tricky to use once apiserver is HA. We should either document the proper steps (shut down all apiservers, run a single apiserver with the right command to do the migration, shut down that apiserver, start all apiservers again), or (my preference) remove it. IMO it should not have gone in at all; you should use a specific tool to do the migration after shutting down all apiservers. There's no need to build that into apiserver, and in fact, it's dangerous if used incorrectly.

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #10475 

Built on top of #11577 

Fixes #8192

cc @lavalamp @fgrzadkowski

### CODE REVIEW

**Comment by wojtek-t** [comment]
This is purely refactoring PR - it doesn't add any new logic.

**Comment by wojtek-t** [comment]
Reassigned to @lavalamp who already gave me a bunch of comments (in the commit).

**Comment by lavalamp** [comment]
A couple comments on the individual commits.

**Comment by wojtek-t** [comment]
@lavalamp - PTAL

**Comment by lavalamp** [comment]
lgtm, thanks.

**Pull request merged**
