### PR TITLE
Fix broken markdown format in v1.7 CHANGELOG

### LINKED ISSUE #48325: Links in v1.7.0 CHANGELOG are all in bad markdown format
See: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#v170

All the links are shown like below format.

`([#39164](https://github.com/kubernetes/kubernetes/pull/39164), [@danwinship](https://github.com/danwinship))`

/cc @dchen1107 
@kubernetes/kubernetes-release-managers

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
- fix broken markdown format in v1.7 CHANGELOG
- remove those changes which have release notes `NONE`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48325

**Special notes for your reviewer**:
/cc @dchen1107 @caesarxuchao @luxas @idvoretskyi @@calebamiles

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Note that there is a nit which I didn't fix in this PR because I don't have enough context.

In chapter https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#kubectl-cli-1
```
kubectl logs and kubectl attach support specifying a wait timeout with --pod-running-timeout

([#41813](https://github.com/kubernetes/kubernetes/pull/41813), [@shiywang](https://github.com/shiywang))
```
They are two entries. One misses it's link and the other misses it's release note.

It might be a separate PR to fix it.

@shiywang

**Comment by idvoretskyi** [comment]
Let's merge it as-is and have a separate PR to fix `kubectl`section issue.

**Comment by luxas** [comment]
> remove those changes which have release notes NONE

@xiangpengzhao Why? What is this? Which release notes does this affect?
This PR should not remove or add anything, which doesn't seem to be the case (+310/-318)
The release notes that are there should be there, please don't modify this.

I can approve after the -8 diff is explained.

**Comment by idvoretskyi** [comment]
@luxas thanks for noticing. @xiangpengzhao can you explain?

**Comment by xiangpengzhao** [comment]
The sentence "remove those changes which have release notes NONE" might be not so clear. What I meant by this is as below.

Let's take a look at the related PRs of the -8 diff lines. They all have a label `release-note` but the content of their release notes is `NONE` which is meaningless. I guess the authors didn't intend to let these PRs have release notes so they wrote `NONE`, but their reviewers labeled `release-note` to them finally. And then these `NONE`s are collected to CHANGELOG.

```
-* NONE ([#45317](https://github.com/kubernetes/kubernetes/pull/45317), [@ericchiang](https://github.com/ericchiang))

-* NONE ([#45317](https://github.com/kubernetes/kubernetes/pull/45317), [@ericchiang](https://github.com/ericchiang))

-* `NONE` ([#44487](https://github.com/kubernetes/kubernetes/pull/44487), [@resouer](https://github.com/resouer))

-* NONE ([#39768](https://github.com/kubernetes/kubernetes/pull/39768), [@rkouj](https://github.com/rkouj))

-* NONE ([#39768](https://github.com/kubernetes/kubernetes/pull/39768), [@rkouj](https://github.com/rkouj))

-* NONE ([#32229](https://github.com/kubernetes/kubernetes/pull/32229), [@errordeveloper](https://github.com/errordeveloper))

-* NONE ([#32067](https://github.com/kubernetes/kubernetes/pull/32067), [@erikh](https://github.com/erikh))

-* NONE ([#30599](https://github.com/kubernetes/kubernetes/pull/30599), [@therc](https://github.com/therc))
```

I don't think we want to keep these meaningless `NONE`s in CHANGELOG. Users will also be confused by these lines, IMO. So I'd still prefer to remove these lines unless these PRs change their release notes to some meaningful content. I can keep them as-is, but we should fix them anyway.

@luxas @idvoretskyi

**Comment by luxas** [comment]
@xiangpengzhao Absolutely makes sense, thanks for the explanation.
I mis-interpreted your first comment and thought normal relnotes were removed.

Thanks for acting quickly, let's merge this!

/lgtm

**Comment by luxas** [comment]
Based on @idvoretskyi's approve, I'll add the label. sig-pm/release owns this doc, so requiring top-level approvers for this is unnecessary.

**Comment by xiangpengzhao** [comment]
Thanks @luxas !

**Comment by caesarxuchao** [comment]
Thank you!

**Pull request merged**
