### PR TITLE
etcd: Update to version 3.5.10

### PR DESCRIPTION
**Pull request by mzaian**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Update etcd to version 3.5.10 See release: [v3.5.10](https://github.com/etcd-io/etcd/releases/tag/v3.5.10).

**Which issue(s) this PR fixes**:
Fixes NONE #

**Does this PR introduce a user-facing change?**:
NONE

```release-note
etcd: Update to v3.5.10
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/retest
after https://github.com/kubernetes/kubernetes/pull/121567 is merged

**Comment by mzaian** [comment]
> /retest after #121567 is merged

@pacoxu It's merged but the build is failing https://prow.k8s.io/?job=post*etcd

**Comment by pacoxu** [comment]
need to promote the image in kubernetes/k8s.io

**Comment by mzaian** [comment]
> kubernetes/k8s.io

I have a WIP PR already there https://github.com/kubernetes/k8s.io/pull/6032/files but since the image is not available because of the failed build it won't be possible.

**Comment by dims** [comment]
@pacoxu let's ask the etcd folks, we should probably treat this as something that needs an exception from the release team.

note that we are already vendoring in 3.5.10, so this PR would be just update which version of etcd we are testing against and also signal the community to use this new version.
https://github.com/kubernetes/kubernetes/blob/master/go.mod#L70-L72

**Comment by pacoxu** [comment]
/lgtm
/approve
for kubeadm part
/assign @liggitt

**Comment by humblec** [comment]
Thanks for getting this in on time  👍

**Pull request merged**
