### PR TITLE
Automated cherry pick of #23446

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #23446 on release-1.2.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @david-mcmahon

**Comment by dchen1107** [comment]
I will manually merge this once the test passed

**Comment by eparis** [comment]
I believe @bgrant0607 wants to approval all cherry-picks. the bot is going to come back with do-not-merge in a second...

**Comment by dchen1107** [comment]
@eparis Thanks for headup. Will talk to Brian

**Comment by bgrant0607** [comment]
I approved #23446.

**Pull request merged**
