### PR TITLE
Check curl before use it

### PR DESCRIPTION
**Pull request by HackToday**
This check can help user figure out what's the issue during
local cluster setup

### CODE REVIEW

**Comment by brendandburns** [comment]
You also need to sign our CLA, details in CONTRIBUTING.md.

Thanks!
--brendan

**Comment by HackToday** [comment]
I have signed the CLA. pls check. Thanks

**Comment by HackToday** [comment]
Hi, cjcullen, already done it, pls check again. Thanks

**Comment by HackToday** [comment]
Hi, @brendandburns I have signed CLA, Please check, thanks

**Pull request merged**
