### PR TITLE
Automated cherry pick of #32242

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #32242 on release-1.3.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33142)

### CODE REVIEW

**Comment by vaijab** [comment]
Could we have this sorted please? This issue is pretty serious and would be great if it gets merged into 1.3 release.

**Comment by jingxu97** [comment]
@k8s-bot test this issue #32440

**Comment by jingxu97** [comment]
@k8s-bot test this issue #IGNORE

**Comment by jingxu97** [comment]
@k8s-bot test this issue #20576

**Pull request merged**
