### PR TITLE
Add a munger check for files that end in preformat

### PR DESCRIPTION
**Pull request by thockin**
This bug wasted a few hours of my day.

### CODE REVIEW

**Comment by krousey** [comment]
How did it waste a few hours of your day? It's **technically** valid markdown. I'm not opposed to this, I would just like to understand more.

**Comment by krousey** [comment]
Also, this presumably was caused by some markdown that should also be fixed by now?

**Comment by thockin** [comment]
In this case a PR was failing because analytics was always failing.  It
would scan the mungelines, find that there was no analytics, and add the
analytics.  Then travis would fail, so they re-ran update_generated_docs.
The problem was that the macro-block functions ignore pre-formatted
sections, so the newly inserted analytics block would never get found.

I spent an hour plus trying to grok what was happening.  It may be valid
markdown but it's not useful for us.

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by bgrant0607** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by bgrant0607** [comment]
Jenkins is broken due to " - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0".

**Pull request merged**
