### PR TITLE
remove gopkg widget

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removes the gopkg widget from the README.md

The widget implicitly suggests that you should read the godocs for *this* repo, when importing this repo is *not* supported.

Instead, users should read the docs for staging/ repos.

We already have a link to kubernetes.io for general docs.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
for discussion

**Comment by MadhavJivrajani** [comment]
+1

**Comment by BenTheElder** [comment]
/hold cancel
I think we've got enough consensus from contribex and arch / code organization to go ahead remove this one.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
