### PR TITLE
make kubeadm support of alicloud installation

### PR DESCRIPTION
**Pull request by aoxn**
Alibaba use kubeadm to bring up a kubernetes cluster on alibaba cloud.  It would be great help if kubeadm could natively support this.

Signed-off-by: 谢瑶瑶(aoxn) <yaoyao.aoxn@hotmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dixudx** [comment]
ping @luxas 

I'm wondering whether we still need to use flag `cloudProvider`. Seems we only utilize this flag to set specical `admission-control` (adding `PersistentVolumeLabel`) for platforms like `aws` and `gce`.

Shall we deprecate this `cloud-provider` flag and add a new flag to append `PersistentVolumeLabel` to admission control list when needed. WDYT?

**Comment by dixudx** [comment]
@aoxn I think #58259 will help solve your problem.
Close this in favor of #58259.
/close

You can reopen it if needed. Thanks.

**Comment by aoxn** [comment]
Thanks , That`s exactly what i need.  @dixudx

**Pull request closed without merging**
