### PR TITLE
Make sleepOp duration parametrizable in scheduler_perf

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Allow to set sleepOp duration using parameter. It can reduce testing time for smaller workloads.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
/lgtm

**Review by alculquicondor — COMMENTED** [review]
/approve

**Pull request merged**
