### PR TITLE
kubeadm: Let apiserver and controller-manager host-mount /etc/pki when required

### LINKED ISSUE #36150: kubeadm on CentOS mounts incompatible /etc/ssl/certs into controller
**What keywords did you search in Kubernetes issues before filing this one?**
controller /etc/ssl/certs
kubeadm /etc/ssl/certs

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.5 custom built master
I also use a custom built hyperkube image instead of the single app images for apiserver, controller, ...

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): Linux ma-kub8ms0 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: deployed with Azure RM template and ansible

**What happened**:
controller is not able to do https, including calls to the Azure RM API

**What you expected to happen**:
https should work as usual

**How to reproduce it** (as minimally and precisely as possible):
Use kubeadm to install kubernetes on CentOS
exec into the controller and try "curl https://google.com"

**Anything else do we need to know**:
It looks like https://github.com/kubernetes/kubernetes/pull/33681 caused this issue. On CentOS, I see these files on the host OS:
```
[devops@ma-kub8ms0 ~]$ ls -lah /etc/ssl/certs/
total 12K
drwxr-xr-x. 2 root root  112 Oct 26 20:48 .
drwxr-xr-x. 5 root root   76 Oct 26 20:47 ..
lrwxrwxrwx. 1 root root   49 Oct 26 20:47 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root   55 Oct 26 20:47 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
-rwxr-xr-x. 1 root root  610 Sep 27 13:40 make-dummy-cert
-rw-r--r--. 1 root root 2.4K Sep 27 13:40 Makefile
-rwxr-xr-x. 1 root root  829 Sep 27 13:40 renew-dummy-cert
```
I suspect the symlinks to /etc/pki/... being the problem here, as they are not available inside the hyperkube Debian image. 

I also tried to verify this with gcr.io/google_containers/kube-controller-manager-amd64:v1.4.4. It seems to not be based on Debian and thus gives a different error:

```
[devops@ma-kub8ms0 ~]$ docker run -ti --rm -v /etc/ssl/certs:/etc/ssl/certs gcr.io/google_containers/kube-controller-manager-amd64:v1.4.4 sh
/ # wget https://google.de
Connecting to google.de (172.217.21.227:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

I see 2 possible solutions:
1. Instead of host mounting /etc/ssl/certs into the controller pod, the ca certificates could be installed into the image. This is already done for hyperkube and would work out of the box when the host mount would be omitted.
2. kubeadm could try to figure out if /etc/pki should also be host mounted and add this to the controller manifest if required.

I'd be happy to provide a fix by myself, I just need to know which solution you would prefer.

### PR DESCRIPTION
**Pull request by codablock**
#

**What this PR does / why we need it**:
This PR checks if /etc/pki is present on the host machine and adds a host-mount to the apiserver and controller-manager manifest if required.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #36150

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix incompatible host mounts for SSL certificates when deploying on CentOS with kubeadm
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36373)

### CODE REVIEW

**Comment by codablock** [comment]
@errordeveloper Any chance to get this into 1.5? Without this, kubeadm on CentOS will not work properly.

**Comment by kad** [comment]
This might be not so trivial. If host OS is opensuse, cert location might be in different location. 
```console
 /etc/ssl/ca-bundle.pem -> /var/lib/ca-certificates/ca-bundle.pem
```
Probably some code to iterate locations like in  https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go and then mount it to appropriate place would be better, as those are the paths where go programs would be looking for system certs.

**Comment by codablock** [comment]
@kad Is this lookup a go specific thing? I assumed all tools would actually look into /etc/ssl/certs and then follow symlinks.

I could add a list to lookup directories (instead of files) needed to be mounted for ssl certificates. This would for now just include:
/etc/ssl/certs (would probably always be included)
/etc/pki
/var/lib/ca-certificates

Iterating over the files from https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go would not work here, as it would still miss /var/lib/ca-certificates. To be honest, I don't like this solution (my initial + the newly proposed) at all. I'd prefer to add proper certificates to the controller/apiserver images. This is already done for the hyperkube image. But this seems to be more complicated because the non-hyperkube images are currently based on busybox.

**Comment by kad** [comment]
@codablock  it all depends on how tools are compiled.
E.g. on CentOS 7, wget is accessing /etc/pki/tls/cert.pem, and curl is using /etc/pki/tls/certs/ca-bundle.crt.

Go standard library is inteligent enough to search in all places (just tried simple code of calling crypto/x509.SystemCertPool() on top of different host OSes, including SuSE).  So, in short, current code in this PR would work if we talking about majority of OSes and if we only care about Go binaries.
It will solve #36150 to best of my understanding.

Any other additional tool in container might be failing making SSL connections under certain combination of host distros and tools inside containers.

**Comment by codablock** [comment]
At least for the busybox based kubernetes images (e.g. apiserver and controller-manager), no other tools are installed into the images, thus we can ignore that non-Go tools may fail.

**Comment by errordeveloper** [comment]
We already mount `/etc/ssl`, I am not entierly sure which distros use `/etc/ssl` and you are saying `/etc/pki` is used in CentOS... So in any case, I think you once you are adding conditional mount for `/etc/pki`, I think you should ensure the code for `/etc/ssl` is very much the same.

**Comment by codablock** [comment]
@errordeveloper /etc/ssl seems to be used by all distros. But the content is different, debian/ubuntu for example has all that is needed inside /etc/ssl, while CentOS only contains symlinks inside /etc/ssl which point to the real certs /etc/pki.

I think this is PR is safe as it would not influence other distros in a negative way and at least CentOS is fixed. For other distros, maybe /var/lib/ca-certificates needs to be conditionally mounted as well...but these distros won't work with the current code already. Maybe we can provide a new PR later when demand for other distros comes in.

**Comment by errordeveloper** [comment]
@codablock thanks for extra explanation!

> Any chance to get this into 1.5?

I'm sorry for taking so long to review, we've had KubeCon... And now we are subject to code freeze, but I think @luxas has a branch where kubeadm changes are being merged into.

**Comment by kad** [comment]
looks like flake. can someone re-trigger ?

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by rmmh** [comment]
@k8s-bot unit test this

**Comment by luxas** [comment]
I think the unit failure here will be real.

@codablock Please take a look and fix if it fails now...

**Comment by rmmh** [comment]
#36263 adds a kubeadm manifests_test that [fails](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/7846/) when combined with this PR.

**Comment by luxas** [comment]
@rmmh Exactly. But I guess it used a stale commit as base here when it succeeded...

**Comment by rmmh** [comment]
36263 isn't committed yet, but it is ahead of this in the queue.

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by codablock** [comment]
I rebased on master and fixed the failing tests.

My initial commit also changes the name for the /etc/kubernetes volume from "pki" to "k8s", as it would otherwise be confusing. /etc/kubernetes does not only contain pki but also configuration and manifests, so the naming was already not the best. And as I introduces a volume which actually mounts /etc/pki, I decided that renaming pki -> k8s and reusing pki for the new volume would be better fitting.

The tests did still check for the old name, which is fixed now.

**Comment by luxas** [comment]
@k8s-bot test this

**Comment by luxas** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
