### PR TITLE
Link verification

### PR DESCRIPTION
**Pull request by lavalamp**
Many of our docs have broken links. This add link checking and some limited auto-fixing to the cmd/mungedocs. I also fix all broken links.

### CODE REVIEW

**Comment by lavalamp** [comment]
FYI: @thockin @erictune @bgrant0607

**Comment by erictune** [comment]
LGTM.  Very thorough!

**Comment by erictune** [comment]
fixes #10985

**Comment by vmarmol** [comment]
ok-to-merge?

**Comment by thockin** [comment]
I haven't looked at this yet, but I bet we made some overlapping changes.
You published first.

**Comment by thockin** [comment]
LGTM

we did make a bunch of the same changes.  I'll merge onto yours.

**Comment by thockin** [comment]
@zmerlynn Are we going to cut 1.0 from 0.21 or from master?

**Comment by zmerlynn** [comment]
@thockin: Master

**Comment by zmerlynn** [comment]
I just wanted to make sure all the release branch mechanics were working on `release-0.21` first.

**Comment by thockin** [comment]
@lavalamp this fails shippable with "Some changes needed but not made due to --verify=true" :)  I want to get my changes in on top of yours, so waiting patiently.  OK, not-so-patiently

@rjnagal for merge

**Comment by lavalamp** [comment]
Let me fix shippable real quick, I know what's wrong.

**Comment by lavalamp** [comment]
OK, this should stop the oscillation.

**Comment by thockin** [comment]
LGTM, waiting for green

**Comment by lavalamp** [comment]
Trying to get shippable to re-run...

**Comment by lavalamp** [comment]
grr.

**Comment by lavalamp** [comment]
OK, the problem is that the verify script moves all the docs before checking, which of course breaks all the links. fix coming soon.

**Comment by lavalamp** [comment]
Argh, sometimes hack/verify-gendocs prints a load of binary output to my terminal.

**Comment by lavalamp** [comment]
OK, here we go.

**Comment by erictune** [comment]
latest changes LGTM

**Comment by lavalamp** [comment]
...and test updated now. Sigh.

**Comment by rjnagal** [comment]
Do we need to squash the commits?

**Comment by lavalamp** [comment]
I think these are useful separate, but I don't care that much.

**Comment by rjnagal** [comment]
cool, I'd rather not interrupt the e2e tests then :)

**Comment by lavalamp** [comment]
Verify gendocs passed in shippable, so this should be safe to merge now.

**Comment by lavalamp** [comment]
One shippable run passed, the other appears stuck

**Comment by lavalamp** [comment]
@rjnagal can we merge this so folks can use it?

**Comment by bgrant0607** [comment]
I'd like to use it. :-)

**Comment by rjnagal** [comment]
ignoring the other shippable, merging :)

**Comment by zmerlynn** [comment]
This change and subsequent fixes broke `hack/gendocs.sh` for me. I can't generate non-relative links now, so precommits on HEAD are failing for me:

```
zml@zml:~/kubernetes$ ./hack/run-gendocs.sh
+++ [0711 06:35:01] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [0711 06:35:06] Placing binaries
/usr/local/google/home/zml/kubernetes/docs/design/access.md
----
check-links:
contents were modified

[...]
```

Diff:
```
diff --git a/docs/design/access.md b/docs/design/access.md
index 85b9c8e..f0b77f6 100644
--- a/docs/design/access.md
+++ b/docs/design/access.md
@@ -151,7 +151,7 @@ In the Simple Profile:
 
 Namespaces versus userAccount vs Labels:
 - `userAccount`s are intended for audit logging (both name and UID should be logged), and to define who has access to `namespace`s.
-- `labels` (see [docs/labels.md](../../docs/labels.md)) should be used to distinguish pods, users, and other objects that cooperate towards a common goal but are different in some way, such as version, or responsibilities.
+- `labels` (see [/usr/local/google/home/zml/kubernetes/docs/labels.md](../../docs/labels.md)) should be used to distinguish pods, users, and other objects that cooperate towards a common goal but are different in some way, such as version, or responsibilities.
 - `namespace`s prevent name collisions between uncoordinated groups of people, and provide a place to attach common policies for co-operating groups of people.
 
 ```

**Comment by thockin** [comment]
If your path is not a "normal" go path (i.e. no github.com/.../ prefix)
this breaks.  Daniel's 11085 has a fix for this, but needs rebase.  Looking
at your fix next.

**Pull request merged**
