### PR TITLE
E2e test for federated deployment controller

### PR DESCRIPTION
**Pull request by mwielgus**
Based on e2e tests for federated deployment.

cc: @quinton-hoole

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35061)

### CODE REVIEW

**Comment by mwielgus** [comment]
@quinton-hoole ping

**Comment by quinton-hoole** [comment]
@k8s-bot federation gce e2e test this issue #IGNORE

**Comment by mwielgus** [comment]
@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
The opening comment of this PR is a cut 'n paste error, but other than that, awesome code. LGTM, Thanks @mwielgus  !

Q

**Comment by quinton-hoole** [comment]
@k8s-bot Federation GCE e2e test this

**Comment by quinton-hoole** [comment]
@mwielgus Lets verify that this passes Federation GCE e2e tests before merging this.  Feel free to apply the label as soon as it does.

**Comment by quinton-hoole** [comment]
@mwielgus 

W1031 14:38:16.224] test/e2e/federation-deployment.go:49: f.Client undefined (type *framework.Framework has no field or method Client)
W1031 14:38:16.224] test/e2e/federation-deployment.go:62: f.Client undefined (type *framework.Framework has no field or method Client)
W1031 14:38:16.224] test/e2e/federation-deployment.go:82: f.Client undefined (type *framework.Framework has no field or method Client)
W1031 14:38:16.224] test/e2e/federation-deployment.go:197: undefined: "k8s.io/kubernetes/pkg/apis/extensions/v1beta1".LabelSelector

**Comment by quinton-hoole** [comment]
Ping @mwielgus

**Comment by mwielgus** [comment]
Yes, surprisingly the errors were not thrown with godep go build. Fixing right now.

**Comment by mwielgus** [comment]
@k8s-bot unit test this

**Pull request merged**
