### PR TITLE
update uber zap to 1.16.0 to fix a nil pointer exception

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
I ran into a nil point in kubelet log, and after investigation, it was a problem of zap which was fixed.

- zap 1.10.0 (2019 version) https://github.com/uber-go/zap/releases/tag/v1.10.0
- zap 1.16.0 fixed 835: Fix panic in JSON encoder when encoding times or durations without specifying a time or duration encoder.

#### Which issue(s) this PR fixes:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 87459 [running]:
net/http.(*conn).serve.func1(0xc001bb1ae0)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x40021e0, 0x6fd2280)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.(*jsonEncoder).AppendDuration(0xc001762e40, 0x44162b7b)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/json_encoder.go:225 +0x53
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.(*jsonEncoder).AddDuration(0xc001762e40, 0x48cdf0f, 0x7, 0x44162b7b)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/json_encoder.go:123 +0x57
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.Field.AddTo(0x48cdf0f, 0x7, 0x8, 0x44162b7b, 0x0, 0x0, 0x0, 0x0, 0x5008fc0, 0xc001762e40)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/field.go:126 +0x4d6
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.addFields(0x5008fc0, 0xc001762e40, 0xc0009bca80, 0x7, 0x7)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/field.go:199 +0xcf
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.(*jsonEncoder).EncodeEntry(0xc000198d80, 0x0, 0xc0117359a339beff, 0x3dac6ac3a2f, 0x70ea0e0, 0x0, 0x0, 0x48c85d6, 0x4, 0x0, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/json_encoder.go:364 +0x1f2
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.(*ioCore).Write(0xc000198db0, 0x0, 0xc0117359a339beff, 0x3dac6ac3a2f, 0x70ea0e0, 0x0, 0x0, 0x48c85d6, 0x4, 0x0, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/core.go:86 +0xa9
k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001adabb0, 0xc0009bca80, 0x7, 0x7)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.uber.org/zap/zapcore/entry.go:215 +0x12d
k8s.io/kubernetes/vendor/k8s.io/component-base/logs/json.(*zapLogger).Info(0xc000192ea0, 0x48c85d6, 0x4, 0xc000d46540, 0xc, 0xc)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/json/json.go:61 +0x194
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).infoS(0x70ea520, 0x4fd7ee0, 0xc000192ea0, 0x0, 0x0, 0x48c85d6, 0x4, 0xc000d46540, 0xc, 0xc)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:792 +0x8d
k8s.io/kubernetes/vendor/k8s.io/klog/v2.InfoS(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1414
	
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1.1(0xc0002f1030)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0xa5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x4f9b380, 0xc0016edea0, 0xc000a87f00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:92 +0x353
net/http.HandlerFunc.ServeHTTP(0xc000110ac0, 0x4f9b380, 0xc0016edea0, 0xc000a87f00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc0001816d0, 0x4f9b380, 0xc0016edea0, 0xc000a87f00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:932 +0x61c
net/http.serverHandler.ServeHTTP(0xc000d34c40, 0x4f9b380, 0xc0016edea0, 0xc000a87f00)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc001bb1ae0, 0x4f9ef80, 0xc0016a6500)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
","v":0}

```

From k/k side, the message is from https://github.com/kubernetes/kubernetes/blob/v1.20.5/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L89
It uses arg `latency` which is duration:
https://github.com/kubernetes/kubernetes/blob/v1.20.5/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L158-L186

The error is the same with https://github.com/uber-go/zap/issues/784
https://github.com/uber-go/zap/pull/835 fixed it.

> The JSON encoder assumes that encoders for time.Time and
> time.Duration are always specified, which causes nil pointer
> dereference panics.

```
		{
			name:     "duration",
			field:    zap.Duration("bar", time.Microsecond),
			expected: `{"bar": 1000}`,
		},
```

**Another easy fix is to make sure the latency here is not nil.** I opened #100742 to just fix the error message here.
https://github.com/kubernetes/kubernetes/pull/100742/files

The problem test case is like the above.

#### Special notes for your reviewer:

1. update go.mod to 1.16.0 for zap
2. run hack/update-vendor.sh

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
as it is indeed a log problem(json parsing)
/sig instrumentation
/cc serathius

**Comment by serathius** [comment]
Thanks catching this!

Could you add a test in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/json/json_test.go#L36 to prevent future regressions?
/milestone v1.21
/priority critical-urgent

**Comment by serathius** [comment]
/cc @dims 
For dependency change approval

**Review by BenTheElder — APPROVED** [review]
dependency changes lgtm
/approve

it already assigns the entire dependency review team automatically on all PRs that ever touch dependecies ...

**Comment by serathius** [comment]
@BenTheElder  That's awesome.

**Comment by liggitt** [comment]
> Could you add a test in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/json/json_test.go#L36 to prevent future regressions?

+1 to this, merging critical fixes without tests means we're vulnerable to them breaking again

**Comment by liggitt** [comment]
is this issue only encountered when enabling structured logs in kube-apiserver, or by default?

**Comment by serathius** [comment]
> is this issue only encountered when enabling structured logs in kube-apiserver, or by default?
As the bug is in zap encoder, it should affect only clusters with JSON logging enabled. No impact on default.

**Comment by serathius** [comment]
Created https://github.com/kubernetes/kubernetes/issues/100748 to increase test coverage.

**Comment by liggitt** [comment]
> Created #100748 to increase test coverage.

I think the testcase needs to accompany the fix, not be a follow up. Based on the description, it looks possible to do in a pretty contained unit test?

**Comment by serathius** [comment]
This is an e2e tests which should improve coverage of cases, but will not guarantee that cases like this will be triggered. As `klog.InfoS` accepts `interface{}` there is still potential that we miss some types that are not correctly handled by internal implementation (due to zap allowing to pass specific type encoders like for duration).

I think we should add unit test targeting all types that zap considers as special, and possibly later we could switch to argument fuzzying (testing all arguments types available in K8s, for example trying all public structs and types defined in Golang and K8s).

**Comment by pacoxu** [comment]
/hold

When I try to add testcases, I find the duration test case is newly added.

#100013 may fix the issue in another way. My cluster is not updated with the latest kubeket. The PR specified `duration` encode staightforwardly.



```
// encoderConfig config zap encodetime format
var encoderConfig = zapcore.EncoderConfig{
	MessageKey: "msg",

	TimeKey:        "ts",
	EncodeTime:     zapcore.EpochMillisTimeEncoder,
	EncodeDuration: zapcore.StringDurationEncoder,
}
```

I still think we should upgrade zap, but it can be upgrade later in 1.22.

**Comment by serathius** [comment]
Thanks for confirming.
/priority backlog
/milestone cancel

**Comment by pacoxu** [comment]
/retest
/hold cancel
for 1.22 if needed

**Comment by pacoxu** [comment]
test cases were added. I add some case for `time` as well as `duration`.
/assign liggit 
for approval

**Comment by pacoxu** [comment]
test cases were added. I add some test cases for time as well as duration.
/assign liggitt
for approval

**Comment by pacoxu** [comment]
/hold
test seems to fail continuely.
I will look into it next Monday.

**Pull request merged**
