### PR TITLE
Add admission controller API to runtime config and externalize ADMISSION_CONTROL

### LINKED ISSUE #47385: Enable `ADMISSION_CONTROL` can be set as env var in local-up-cluster.sh
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
This is a follow up request for https://github.com/kubernetes/kubernetes/pull/47317

It is better to support `ADMISSION_CONTROL` as an env var so that we do not need to update it every time when a new admission control is added.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Enable the dynamic admission controller registration API by
adding "admissionregistration.k8s.io/v1alpha1" to --runtime-config
to fix problems when starting up local-up-cluster. Also make sure
ADMISSION_CONTROL can be specified externally.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #47385

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@jbeda @cblecker Can you please take a look?

**Comment by cblecker** [comment]
/lgtm
@dims: Can you add the # symbol before the ticket number in your PR body, so that the approval bot picks it up?

**Comment by dims** [comment]
ah thanks @cblecker

**Comment by cblecker** [comment]
/approve
I think the bot picked up that I'm an approver for `hack/` already, so it added the label.

**Pull request merged**
