### PR TITLE
 kubelet: promote OS & arch labels to GA

### LINKED ISSUE #72929: Promote node os/arch label to stable
**What would you like to be added**:
kubelet self labels the node with OS/arch, etc. The labeling was added backed in 1.3. It's time to promote the labels.
```
LabelOS   = "beta.kubernetes.io/os"
LabelArch = "beta.kubernetes.io/arch"
```

**Why is this needed**:
This feature has already been used in multiple places to help schedule pods onto the right nodes.

For the transition, kubelet will need to label itself with both the beta and the GA label to handle the master-node version skew for a few releases.

/cc @kubernetes/sig-node-feature-requests @dchen1107 @derekwaynecarr @liggitt @luxas  
/cc @PatrickLang @pjh @mtaufen

### PR DESCRIPTION
**Pull request by yujuhong**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #72929

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet: OS and Arch information is now recorded in `kubernetes.io/os` and `kubernetes.io/arch` labels on Node objects. The previous labels (`beta.kubernetes.io/os` and `beta.kubernetes.io/arch`) are still recorded, but are deprecated and targeted for removal in 1.18.
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks
cc @liggitt

**Comment by yujuhong** [comment]
/retest

@liggitt are you okay with the change? I'll send a separate PR to update the node controller

**Comment by yujuhong** [comment]
/retest

@liggitt I updated the PR according to your comment, but I'm not sure why we have to wait until 1.18. Kubernetes only supports up to 2 version skews based on the policy https://kubernetes.io/docs/setup/version-skew-policy/   The 1.17 master control plane will only support 1.17, 1.16, and 1.15 nodes.

**Comment by yujuhong** [comment]
KEP as requested: https://github.com/kubernetes/enhancements/pull/792

**Comment by yujuhong** [comment]
Rebased. All the labels have been moved to `staging/src/k8s.io/api/core/v1/well_known_labels.go` in another PR, so I had to force push to not cause a mess.

On the other hand, @dims I'm not sure we really want to move the beta labels to v1 api given that we are deprecating them. Should we move them back?

**Comment by dims** [comment]
@yujuhong +1 to move back just the beta labels

**Comment by liggitt** [comment]
per https://github.com/kubernetes/enhancements/issues/793#issuecomment-459394752

/assign @smarterclayton 
/unassign

**Comment by yujuhong** [comment]
> @yujuhong +1 to move back just the beta labels

Added another commit to move those back to the kubelet package

**Comment by yujuhong** [comment]
Ping @smarterclayton. Do you still want to review this?

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by smarterclayton** [comment]
lgtm as well

**Pull request merged**
