### PR TITLE
Restore kube-proxy --version

### LINKED ISSUE #46026: kube-proxy can no longer print its version
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"kube-proxy version"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.7.0-alpha.3

**Environment**:
- **Cloud provider or hardware configuration**: n/a
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): Linux smc-ubuntu 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: N/A
- **Others**:

**What happened**:

I ran `kube-proxy --version`, got an error instead of the version:
```
kube-proxy --version
W0518 11:35:39.647049   73974 server.go:155] WARNING: all flags other than --config and --cleanup-iptables are deprecated. Please begin using a config file ASAP.
Starting CPU profile
W0518 11:35:39.685089   73974 server.go:314] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.
error: no configuration has been provided
```

**What you expected to happen**:

`kube-proxy` prints its version

**How to reproduce it** (as minimally and precisely as possible):

```
<check out 1.7.0-alpha.3>
make kube-proxy
_output/bin/kube-proxy --version
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by ncdc**
Accidentally removed by #34727.

Fixes #46026

### CODE REVIEW

**Comment by ncdc** [comment]
@fasaxc @dcbw @qiujian16 @cmluciano PTAL

cc @sttts @mikedanese @deads2k

**Review by cmluciano — COMMENTED** [review]
LGTM, tested locally too

**Pull request merged**
