### PR TITLE
DRA: remove support for v1alpha2 kubelet gRPC API

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup
/deprecation

#### What this PR does / why we need it:

Code simplification.

#### Special notes for your reviewer:

The v1alpha2 API is several releases old. No current drivers should still depend on it.

#### Does this PR introduce a user-facing change?
```release-note
ACTION-REQUIRED: DRA drivers using the v1alpha2 kubelet gRPC API are no longer supported and need to be updated.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3063
```

### CODE REVIEW

**Comment by klueska** [comment]
> Open source claims like this seem to be very difficult to prove. Can you share how you found this out? Did we mark v1alpha2 as deprecated?

Traditionally, k8s has required one to ensure both forward-and-backwards compatibility even with `alpha` APIs. When designing the `v1alpha2` API for DRA we pointed out that this requirement is highly restrictive given that the whole point of `alpha` is to be able to iterate quickly and remove code that turned out to be a bad idea across API versions.

For this reason we decided that it made more sense to remove old `alpha` APIs for DRA instead of trying to ensure compatibility for upgrades / downgrades. This was unprecedented at the time, but given the enormity of this feature, @thockin gave his support.

The comments on the following PR that moved us from `v1alpha1` --> `v1alpha2` echo this choice:
https://github.com/kubernetes/kubernetes/pull/116299

**Comment by kannon92** [comment]
Okay. I'm happy with those points if you two are.

**Comment by liggitt** [comment]
A couple more comments for context, referencing https://kubernetes.io/docs/reference/using-api/deprecation-policy/

If an alpha is kept in place, encoding/decoding of that version and conversion to/from the next alpha or beta must work.

> API objects must be able to round-trip between API versions in a given release without information loss

We wouldn't make a change even to an alpha type that would break decoding of data returned in that version from a previous server, we'd rev the alpha to alpha2.

> Once an API element has been added to an API group at a particular version, it can not be removed from that version or have its behavior significantly changed, regardless of track.

When keeping support for a previous alpha is possible and cheap (if there are only small or trivial changes made from the alpha to the next alpha or beta), it's a nice thing to do, but it is definitely not required. Alphas are off by default, and are explicitly allowed to be removed without any deprecation period.

> Alpha API versions may be removed in any release without prior deprecation notice

When the lessons learned from one alpha result in significant changes to the next alpha that make conversion complicated / expensive / difficult / impossible, then I'm a big +1 on dropping the first alpha entirely.

It's also not unprecedented... when admission webhooks graduated v1alpha1, the v1alpha1 version was removed entirely and immediately.

**Comment by pohly** [comment]
> If an alpha is kept in place, encoding/decoding of that version and conversion to/from the next alpha or beta must work.

Note that this is a gRPC API, not an API served by the apiserver. Therefore this part isn't relevant here.

> When the lessons learned from one alpha result in significant changes to the next alpha that make conversion complicated / expensive / difficult / impossible, then I'm a big +1 on dropping the first alpha entirely.

We decided to keep v1alpha2 when adding v1alpha3 because it wasn't hard to remain compatible and it made it possible to provide example drivers that worked across multiple Kubernetes releases.

In 1.31, we will break several DRA APIs (both kubelet and apiserver), so we use this opportunity to clean up. This PR is just a first step...

**Comment by thockin** [comment]
Rip the bandage off.

**Comment by bart0sh** [comment]
retesting as the job has a "Context retired without replacement." status. Should be "Job succeeded"
/test pull-kubernetes-node-e2e-crio-dra

**Comment by klueska** [comment]
/approve

Looks like a rebase is needed before lgtm

**Pull request merged**
