### PR TITLE
add a mechanism for delegated authorization to have a few hardcoded rules

### PR DESCRIPTION
**Pull request by deads2k**
In many clusters there is a metrics scraping program of some kind. This program often has a fixed identity and accesses only /metrics across many pods.  While we cannot make a default rule for this identity (it varies across different cluster deployments), the ability to specify a user who is authorized to access a particular endpoint while delegating authz checks for other accesses reduces SAR checks that aren't necessary on repeatedly accessed endpoints.

This would allow a deployment to specify something like `kube-controller-manager --authorization-direct-access=system:serviceaccount:monitoring:scraper=/metrics`.  By default there would be no change.

Even with authorization caching, a lot of traffic is related to SARs that are essentially hardcoded (we know the identity of the scraper).  These are the options we've come up with.
1, use ABAC.  Potentially taking it to v1.  We kept ABAC around for exactly this purpose.  The format isn't great, but it exists and it would work perfectly for this use-case.  Having gone through the other options, I think this is the best.
2. add an arg for this rule.  It's constrained  (non-resource request) and covers a scraping use-case.  It's ugly and not very expressive.
3. create a way to read RBAC policy from disk and run an RBAC authorizer.  This seems very heavy for a small use-case.
4. Do nothing.  Given the amount of traffic and how it interacts with priority and fairness, I think this is a bad idea for scaping behavior like this where the actors and URLs are known.

/kind feature
/priority important-soon
@kubernetes/sig-auth-feature-requests @kubernetes/sig-api-machinery-feature-requests 
/hold 

holding for discussion, unit tests, probably integration tests.

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
This seems really special purpose. The first alternative that comes to mind is to add a way for a SAR response to state how long it may be cached for, configured via setting a field in an RBAC role or something. I guess that is probably a lot more work :( Maybe we could start by configuring it via file for kube-apiserver and expand if it proves useful. I don't know.

The second alternative that comes to mind is to allow some pre-computed permissions check to be passed e.g. in a header. Like, apiserver signs something (which includes actor, path, and expiration timestamp), and we can stick it in a header, and then the AA can just verify the signature without making a network trip.

**Comment by p0lyn0mial** [comment]
It seems like a natural extension of what we already have. As of today, we can specify `AlwaysAllowGroups` and/or `AlwaysAllowPaths`. With this change, we could additionally specify a user and a path. Seems reasonable.

**Comment by tallclair** [comment]
Related: point 3 in this comment https://github.com/kubernetes/kubernetes/issues/12968#issuecomment-622613486

> 3. Scalability: Authenticating with a SA token will issue 2 additional requests against the API server: a TokenReview and SubjectAccessReview (only the latter with client certificate auth). On large clusters this could add up to significant QPS against the master. There is a scalability-security tradeoff by extending the cache TTL arbitrarily.

**Pull request closed without merging**
