### PR TITLE
 Add e2e tests for resource quota's priority class scope.

### PR DESCRIPTION
**Pull request by aveshagarwal**
This pr is built on top of https://github.com/kubernetes/kubernetes/pull/57963.

@vikaschoudhary16 @sjenning @derekwaynecarr @bsalamat 
@kubernetes/sig-scheduling-pr-reviews 

```release-note
None
```

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
@aveshagarwal I could not find where `LimitedResources` are configured to ensure that covering quota is must for a particular priorityclass.

**Comment by aveshagarwal** [comment]
> @aveshagarwal I could not find where LimitedResources are configured to ensure that covering quota is must for a particular priorityclass.

varying admission plugin config can not be passed to e2e tests, as that would require restarting the cluster whenever the config is changed.

**Comment by aveshagarwal** [comment]
@vikaschoudhary16 updated. PTAL.

**Comment by aveshagarwal** [comment]
> @aveshagarwal We need e2e tests for scopes other than priority class scope with scope selectors. Like these unit tests

> Would you like to extend this PR or in a follow-up PR?

I'd prefer to get this PR going as it is, and for anything else I will submit a new PR.

**Pull request merged**
