### PR TITLE
Added alejandrox1 as test/e2e/framework reviewer

### PR DESCRIPTION
**Pull request by alejandrox1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I have been working with the testing-commons subproject reviewing and drafting PRs and I would like to continue doing more of it :smiley: 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/priority backlog
/assign @timothysc @andrewsykim @oomichi

### CODE REVIEW

**Comment by andrewsykim** [comment]
/retest
/approve
/lgtm

Thanks!

**Review by oomichi — COMMENTED** [review]
Thanks for your contribution @alejandrox1 
big +1

/lgtm

**Review by odinuge — APPROVED** [review]
+1 from me! Thanks for the good work!! 
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm
welcome @alejandrox1

**Comment by BenTheElder** [comment]
+1 :-)

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
