### PR TITLE
Automated cherry pick of #62075: Update GLBC manifest to v1.0.1

### PR DESCRIPTION
**Pull request by nicksardo**
Cherry pick of #62075 on release-1.10.

#62075: Update GLBC manifest to v1.0.1

### CODE REVIEW

**Comment by MaciekPytel** [comment]
pull-kubernetes-e2e-gce consistently fails for this PR with errors that look like something wasn't properly cleaned up after previous run:

```
I0405 05:53:50.724] Checking whether gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.10.1-beta.0.36+900c876a98c38b already exists: - Destination exists. To remove, run:
I0405 05:53:50.736]   gsutil -m rm -r
I0405 05:53:50.738]   gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.10.1-beta.0.36+900c876a98c38b
I0405 05:53:50.756] FAILED
```

This doesn't look like it will sort itself out without some intervention. 
cc: @nicksardo @krzyzacy @kubernetes/test-infra-maintainers

**Comment by nikhiljindal** [comment]
Ran `gsutil -m rm -r gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.10.1-beta.0.36+900c876a98c38b` as per the logs above. Lets see if it helps.

fwiw, this seems to be the only PR that is failing pull-kubernetes-e2e-gce so its not a generic issue

**Comment by ixdy** [comment]
this is unintentional fallout from https://github.com/kubernetes/test-infra/pull/7480. I believe @BenTheElder is working on a fix.

**Comment by MaciekPytel** [comment]
@nicksardo @nikhiljindal It looks like this actually broke ingress tests on release-1.10 branch:

https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gce-ingress-1.10
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gke-ingress-1.10

Can you take a look?

**Comment by nicksardo** [comment]
Thanks for the ping, @MaciekPytel.

After taking a quick look, seems to be a coincidence with longer GCP LB provision times. The tests pass, but pass the 90 minute timeout. The first failure with this behavior happened prior to my cherry-pick. @rramkumar1 will try bumping the timeout, and we'll investigate further.

**Comment by nikhiljindal** [comment]
Verified that the tests are back to green again: https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gce-ingress-1.10

**Pull request merged**
