### PR TITLE
convert replica set controller to shared informer

### PR DESCRIPTION
**Pull request by deads2k**
Switches the replicaset to a shared informer.

@kargakis fyi

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34962)

### CODE REVIEW

**Comment by kargakis** [comment]
Don't you need to deep-copy in `updateReplicaCount`?

**Comment by deads2k** [comment]
> Don't you need to deep-copy in updateReplicaCount?

pre-existing, sigh.  Updated.  Looks like the method always wants to update.  I did the deep copy at the beginning.

**Comment by deads2k** [comment]
> pre-existing, sigh. Updated. Looks like the method always wants to update. I did the deep copy at the beginning.

Oh, I see the check now in the method.  How frustrating.

**Comment by kargakis** [comment]
LGTM

**Comment by deads2k** [comment]
@k8s-bot test this: issue #34986

**Comment by fejta** [comment]
@k8s-bot verify test this

**Comment by kargakis** [comment]
```
I1017 18:08:58.184] FAIL	k8s.io/kubernetes/test/integration/replicaset [build failed]
```
Probably real?

**Comment by deads2k** [comment]
> Probably real?

compile error it says.  Weird.  Rebasing

**Pull request merged**
