### PR TITLE
Use PodTopologySpread for default spreading

### LINKED ISSUE #80639: [Scheduler] Default spreading should be configurable for a topology
By default, the scheduler spreads pods by zone, in order to provide some level of reliability for services.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/selector_spreading.go#L108

**What would you like to be added**:

Cluster operators should be able to change this to a topology label that better fits their need.

This can be done with a flag to the binary that is set to `zone` by default, so that current behavior remains.

**Why is this needed**:

On-prem clusters have different topologies than cloud providers. If the scheduler uses the zone topology for default spreading, on-prem cluster operators don't have another alternative but to abuse the zone label even though that might violate its semantic meaning.

/sig scheduling

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

If the feature gate `DefaultPodTopologySpread` is enabled, uses `PodTopologySpread` plugin to do default spreading, with the following constraints:

```yaml
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: kubernetes.io/hostname
  maxSkew: 3
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 5
```

These default constraints give room for pods with higher spreading needs to use more restrictive constraints.

The feature gate also removes the legacy `DefaultPodTopologySpread` from the default profile, if enabled.

**Which issue(s) this PR fixes**:

Fixes #80639

Ref kubernetes/enhancements#1258

**Special notes for your reviewer**:

## Performance

Our benchmarks show comparable running times for both features:

Legacy:
```
BenchmarkTestSelectorSpreadPriority/100nodes-56         	    4906	    220726 ns/op
BenchmarkTestSelectorSpreadPriority/1000nodes-56        	     792	   1571382 ns/op
```

New:
```
BenchmarkTestDefaultEvenPodsSpreadPriority/100nodes-56         	    4874	    266534 ns/op
BenchmarkTestDefaultEvenPodsSpreadPriority/1000nodes-56        	     838	   1510024 ns/op
```

## Spreading simulation

This is the simulation data supporting the used constants, comparing the score to NodeResourcesLeastAllocated plugin. These experiments assume the changes in #91918

## Scenarios

We simulate the deployment of 9 pods in a cluster with
- 9 nodes in 3 zones (3 nodes each), 9 pods
- 11 nodes in 3 zones (4, 4 and 3 in each), 30 pods
with different initial resource utilization (numbers represent usage in percentage):

```
([[10, 10, 0], [10, 5, 0], [5, 5, 5]], 9)
([[20, 20, 0], [20, 10, 0], [10, 10, 10]], 9)
([[40, 40, 0], [40, 20, 0], [20, 20, 20]], 9)
([[80, 80, 0], [80, 40, 0], [40, 40, 40]], 9)

([[10, 10, 5, 0], [10, 5, 5, 0], [5, 5, 5]], 30)
([[40, 40, 20, 0], [40, 20, 20, 0], [20, 20, 20]], 30)
([[80, 80, 40, 0], [80, 40, 40, 0], [40, 40, 40]], 30)
```

### Legacy default spreading

```
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[0, 0, 3], [0, 1, 2], [1, 1, 1]]
[[0, 0, 3], [0, 0, 3], [1, 1, 1]]

[[2, 2, 3, 3], [2, 3, 3, 3], [3, 3, 3]]
[[1, 0, 3, 6], [0, 3, 3, 5], [3, 3, 3]]
[[0, 0, 1, 9], [0, 1, 1, 9], [3, 3, 3]]
```

### Pod Topology Spreading

Note that weight of the score is doubled #91258

**Using maxSkew 1, 1 for node and zone, respectively**

```
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 0, 2], [0, 1, 2], [1, 1, 1]]

[[2, 2, 3, 3], [2, 3, 3, 3], [3, 3, 3]]
[[2, 2, 3, 4], [2, 3, 2, 3], [3, 3, 3]]
[[1, 1, 3, 5], [1, 3, 2, 5], [3, 3, 3]]
```

We obtain perfect spreading, except at high utilization. Still significantly better than legacy spreading in this case. Using this configuration as default would be too aggressive and wouldn't leave room for Pod overrides.

**Using maxSkew 2, 4 for node and zone, respectively**

```
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 0, 2], [0, 1, 2], [1, 1, 1]]
[[1, 0, 2], [0, 1, 2], [1, 1, 1]]

[[2, 2, 3, 3], [2, 3, 3, 3], [3, 3, 3]]
[[2, 2, 3, 4], [2, 3, 2, 3], [3, 3, 3]]
[[1, 1, 3, 5], [1, 3, 2, 5], [3, 3, 3]]
```

Still too aggressive compared to legacy.

**Using maxSkew 3, 5 for node and zone, respectively**

```
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1, 0, 2], [0, 1, 2], [1, 1, 1]]
[[0, 0, 3], [0, 1, 2], [1, 1, 1]]

[[2, 2, 3, 3], [2, 3, 3, 3], [3, 3, 3]]
[[2, 2, 3, 4], [1, 3, 2, 4], [3, 3, 3]]
[[1, 1, 3, 5], [0, 3, 3, 5], [3, 3, 3]]
```

Less aggressive, but still better than legacy. The difference with (2, 2) configuration can be seen at high utilization.

**Does this PR introduce a user-facing change?**:

```release-note
Enable feature Gate DefaultPodTopologySpread to use PodTopologySpread plugin to do defaultspreading. In doing so, legacy DefaultPodTopologySpread plugin is disabled.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/1258-default-even-pod-spreading
- [Usage]: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints
```

### CODE REVIEW

**Comment by ahg-g** [comment]
I am concerned about the weaker spreading for low number of pods, good spreading in this scenario is relatively more important than when the number of pods is high. I wonder if we should have a separate configurable weight for default spreading, I guess if we set the weight to 1 and maxSkew=1, we will get a behavior similar to the old one, right?

Another thing to clarify in this PR should be performance, can you post how this impact scheduling latency?

**Comment by alculquicondor** [comment]
> I am concerned about the weaker spreading for low number of pods, good spreading in this scenario is relatively more important than when the number of pods is high. I wonder if we should have a separate configurable weight for default spreading, I guess if we set the weight to 1 and maxSkew=1, we will get a behavior similar to the old one, right?

Yes, but we discussed the semantic problems of this already.

Let me put it another way: PodTopologySpread is a new API that has different guarantees. In this case, the guarantee comes from maxSkew. And we can see that the proposed configuration in this PR upholds to it.
If workloads have stronger or weaker needs, they can use the API in the PodSpec.
The feature gate allow us to roll out this change safely giving chance to operators to do necessary changes.

cc @lavalamp any comments?

> Another thing to clarify in this PR should be performance, can you post how this impact scheduling latency?

Done

**Comment by lavalamp** [comment]
Are similar pods counted up near the beginning of the filter execution?

Suppose we counted the number of pods, and then selected the max skews based off of that. Then you could default to maxSkew of 1 if there's, say, < 5 pods, otherwise go to your current settings.

I think this is theoretically sound, spreading is drastically more important when there are fewer pods, as e.g. a node/zone failure can disable a larger fraction of the pods at once.

**Comment by alculquicondor** [comment]
> Suppose we counted the number of pods, and then selected the max skews based off of that. Then you could default to maxSkew of 1 if there's, say, < 5 pods, otherwise go to your current settings.

This is possible here: https://github.com/kubernetes/kubernetes/blob/516c8fbfad3253f7e680ecf5db023944dfa402d4/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L203

However, then we are not upholding to the API. At this point, there is no way to distinguish from a k8s defined default contraint, or operator defined default constraint or workload defined constraint. In theory, we should only apply it only to k8s defined default. However, I guess we could just do it for all defaults, but not workload defined. This is easier to track.

**Comment by alculquicondor** [comment]
Alternatively, we could have an "adaptative" maxSkew, if the value is 0 or something.

**Comment by lavalamp** [comment]
I'm mostly reacting to "The new spreading is weaker than legacy for a low number of pods and where there is low node usage variance"... that seems like the case where you want spreading the most. I don't think it's good to regress in that case.

**Comment by alculquicondor** [comment]
For the sake of a consistent API, we can make all maxSkews adaptative: it will try to uphold a reasonable maxSkew as number of pods increase, until it reaches the configured one.

something like: `adaptativeMaxSkew = min(maxSkew, total_matching_pods / k)` where k is a constant that we can discuss.

**Comment by lavalamp** [comment]
This implies being stricter than requested when the number of pods is small, right? I think that sounds OK and also plausibly leaves the scheduler in an easier position when the Nth pod shows up.

**Comment by ahg-g** [comment]
Keeping a consistent API is my preference as well, so changing the semantics of MaxSkew to help maintain the old behavior of default spreading for small number of pods sounds good to me. MaxSkew impact on scoring has only been introduced in this release, so we can tweak it again.

**Review by Huang-Wei — COMMENTED** [review]
A couple of questions:

1. Should we mark `DefaultPodTopologySpread` as deprecated? I mean just add a comment there, but is still registered until this feature is GA.
1. Pre the discussion that soft `maxSkew` is not always honored depending on the pods number, so how about name the feature as "AdaptivePodTopologySpread", or "TopologyAdaptivePodSpread"?
1. It'd great if we can come up with a doc explaining how soft `maxSkew` works in detail. (I assume there is only some wordings in API doc explaining this in a very high level)

**Comment by alculquicondor** [comment]
/hold
according to discussion.

1. Yes, but it's not very important.
2. Are you proposing a new plugin? As @ahg-g mentioned, using maxSkew in scores is a new behavior so we can still change it.
3. We can document it in generic terms, like saying that the scheduler will try to accomplish smaller skews when the number of pods is low.

**Comment by Huang-Wei** [comment]
@alculquicondor Re 2: nope, just replace current `NewDefaultTopologySpread` feature name.

**Comment by alculquicondor** [comment]
> Aldo Culquicondor Re 2: nope, just replace current `NewDefaultTopologySpread` feature name.

But it wouldn't be exclusive to default spreading. All soft spreading constraints would be treated the same.
As said above, this is in order to keep the API consistent.

**Comment by alculquicondor** [comment]
Honestly, I would have named it just `DefaultPodTopologySpread` if it wasn't the case that it matches the existing plugin name.

I think the adaptativeness is more of an implementation detail (that can be documented as said above). But we can revisit the name of the feature gate once the changes for maxSkew merge.

**Comment by Huang-Wei** [comment]
> Honestly, I would have named it just DefaultPodTopologySpread if it wasn't the case that it matches the existing plugin name.

I have no objection on naming it `DefaultPodTopologySpread`, give that someday we will totally remove the "defaultpodtopologyspread" plugin.

**Comment by alculquicondor** [comment]
> > Suppose we counted the number of pods, and then selected the max skews based off of that. Then you could default to maxSkew of 1 if there's, say, < 5 pods, otherwise go to your current settings.
> 
> This is possible here:
> 
> https://github.com/kubernetes/kubernetes/blob/516c8fbfad3253f7e680ecf5db023944dfa402d4/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L203
> 

Turns out I didn't think this through. We only process the nodes that passed the filters (and nodes that share topologies with them). This is a result of a tradeoff between a 100% accurate score and one that is fast. The end result is that we can't calculate the total number of pods that match the spreading rules to do the adaptative maxSkew.

**Comment by Huang-Wei** [comment]
@alculquicondor can we name the featuregate to `DefaultPodTopologySpread`?

**Comment by lavalamp** [comment]
> The end result is that we can't calculate the total number of pods

It sounds like you get a lower bound, though? Is that good enough? How far off would it be typically?

**Comment by alculquicondor** [comment]
> It sounds like you get a lower bound, though? Is that good enough? How far off would it be typically?

It is possible. But with the current scheduler framework architecture, it would be costly to keep the count.

In any case, we have a solution 😃 #91918

**Comment by alculquicondor** [comment]
Feature Gate name and PR description updated.

**Pull request merged**
