### PR TITLE
CHANGELOG: add a hyperlink to issue 86282

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it: 
/add a hyperlink to issue 86282

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by heqg** [comment]
/assign @damemi 
can you help me to review or approve this pr ?
If it will be merged,  it is much better. 
Thank you very much.

**Review by damemi — COMMENTED** [review]
/unassign
@heqg I am not a changelog reviewer, sorry. Maybe you meant to tag someone else? :)

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
