### PR TITLE
Edge based winuserspace proxy

### PR DESCRIPTION
**Pull request by wojtek-t**
Last PR in the series of making kube-proxy event-based.

This is a sibling PR to https://github.com/kubernetes/kubernetes/pull/45356 that is already merged.
The second commit is removing the code that is no longer used.

### CODE REVIEW

**Comment by freehan** [comment]
This PR looks sane to me. But I do not much context with windows proxy.

**Comment by wojtek-t** [comment]
@brendandburns - can you please take a look - this is refactoring that is supposed to be no-op from functionality perspective, but should improve performance (we did similar thing for userspace proxy (non-windows) in #45356)

**Comment by brendandburns** [comment]
/lgtm

Thanks!

**Comment by brendandburns** [comment]
(though it needs a rebase, feel free to self-lgtm or ping me...)

**Comment by wojtek-t** [comment]
Trivial rebase - reapplying label.

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Pull request merged**
