### PR TITLE
bump debian-hyperkube-base to 0.5 since CNI gets bumped

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
xref [discussion](https://github.com/kubernetes/kubernetes/pull/51250#discussion_r145796595) in #51250

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/assign @ixdy @luxas 

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by dixudx** [comment]
@ixdy @luxas Please help label `milestone v1.9`.

**Review by luxas — APPROVED** [review]
/lgtm

if it's ok for @ixdy

**Comment by dixudx** [comment]
ping @mikedanese Needs your `approval`. Thanks

**Comment by ixdy** [comment]
/lgtm cancel

needs update to `build/root/WORKSPACE` too; standby for sha

**Comment by ixdy** [comment]
`gcr.io/google-containers/debian-hyperkube-base-amd64:0.5` has digest `sha256:d216b425004fcb6d8047f74e81b30e7ead55f73e73511ca53a329c358786b6c9`.

**Comment by dixudx** [comment]
@ixdy Thanks. Already bumped the new sha. PTAL. Thanks.

**Comment by ixdy** [comment]
/lgtm

thanks! just need to find an approver for cluster/images/hyperkube now.

**Comment by dixudx** [comment]
ping @eparis  @roberthbailey Needs your `approval`. Thanks.

**Pull request merged**
