### PR TITLE
generate rc name from deployment name

### LINKED ISSUE #17021: Deployment should give created RCs a similar name
Right now a deployment named `kube-app` creates an rc of name `deploymentrc-{some generated string}`.

The name of the RC should be `kube-app-{some generated string}`.

ref #15313

cc @nikhiljindal @bgrant0607

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #17021

### CODE REVIEW

**Comment by wojtek-t** [comment]
@mikedanese - thanks! it was really uninformative before

LGTM

**Comment by nikhiljindal** [comment]
Thanks, LGTM too.

**Comment by dpratt** [comment]
What are the odds of seeing this get merged into the 1.1.x branch?

**Comment by mikedanese** [comment]
There is pretty close to zero chance. See [patch release](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#patch-releases) doc for the policy. You can always cherry pick it yourself. You only need to update the contoller-manager with this patch.

**Comment by dpratt** [comment]
Thanks - appreciate the heads-up. I have been running my own patched version of k8s in our cluster, but recently switched to the stable 1.1.3 mainline release and was looking forward to seeing this in 1.1.4.

**Comment by geoah** [comment]
Is this in any mainline release yet?

**Comment by mikedanese** [comment]
This will be in 1.2.

**Comment by geoah** [comment]
@mikedanese thank you very much

**Pull request merged**
