### PR TITLE
De-duplication of verb in policy.go

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L224 contains `get` verb. 

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by ericchiang** [comment]
@k8s-bot ok to test

**Comment by ericchiang** [comment]
/lgtm

cc @kubernetes/sig-auth-pr-reviews

**Comment by deads2k** [comment]
@liggitt willing to rebase the node authorizer (https://github.com/kubernetes/kubernetes/pull/46076) on this?

**Comment by liggitt** [comment]
Sure, I'll need at least a squash anyway

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by ericchiang** [comment]
@k8s-bot pull-kubernetes-unit test this #46631

**Pull request merged**
