### PR TITLE
Revert "Skip StatefulSet e2e tests if this resource is not found"

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts kubernetes/kubernetes#37389

The reason of reverting this pr is at: https://github.com/kubernetes/kubernetes/pull/37389#issuecomment-262613914

Once @foxish's fix was checked in, we should merge this one.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37398)

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by foxish** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
@k8s-bot verify test this

**Comment by saad-ali** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
@dchen1107 This branch has conflicts that must be resolved.

**Comment by foxish** [comment]
@saad-ali the conflict should go away once https://github.com/kubernetes/kubernetes/pull/37412#issuecomment-263767417 merges.

**Comment by foxish** [comment]
I was wrong. Looks like this merge conflict should be fixed manually. Ping @dchen1107

**Comment by dims** [comment]
@dchen1107 @foxish @janetkuo : this won't merge as it needs a rebase

**Pull request closed without merging**
