### PR TITLE
Add the Sysdig Platform provider to the list of Custom Metrics Providers

### PR DESCRIPTION
**Pull request by tembleking**
**What this PR does / why we need it**:

Hi everyone, I would like to add the Sysdig Platform provider to the list of implementations for the Custom/External Metrics Provider.

We created a blog post about how to build a Kubernetes Horizontal Pod Autoscaler using custom metrics and our provider if you need more information: 
https://sysdig.com/blog/kubernetes-scaler/

**Does this PR introduce a user-facing change?**:
NONE

/kind documentation

### CODE REVIEW

**Comment by tembleking** [comment]
CLA signed

**Review by hex108 — APPROVED** [review]
/ok-to-test

**Comment by tembleking** [comment]
Hello, is this okay to merge? :slightly_smiling_face:

**Comment by tembleking** [comment]
Hi @lavalamp or @nikhiljindal, please don't forget this PR, if you can take a quick look at it I'd be happy :smiley:

**Pull request closed without merging**
