### PR TITLE
Automated cherry pick of #78294: Removed deprecated --resource-container flag from kube-proxy.

### PR DESCRIPTION
**Pull request by SataQiu**
Cherry pick of #78294 on release-1.15.

/kind bug
Ref: #54967

#78294: Removed deprecated --resource-container flag from kube-proxy.

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by SataQiu** [comment]
ping @kubernetes/patch-release-team

**Comment by tpepper** [comment]
Is this really something we should be cherry picking into the release-1.15 branch half way through its life?

**Comment by tpepper** [comment]
/hold
pending cherry pick justification.

**Comment by thockin** [comment]
Yeah, I think I missed that this was a cherry pick.   I do not think we want to cherry pick this, unless there's a REALLY pressing reason.

**Review by cmluciano — COMMENTED** [review]
@thockin @tpe 

Since 1.15 will still be supported after 1.17, wouldn't we want smaller scoped bug fixes like this to be included? I don't disagree that this is probably not affecting a ton of people but would be great to know what the threshold should be when I'm reviewing cherry-picks like this.

The linked issues include reports of this being a deprecated flag for quite some time and the flag itself was apparently [deprecated in 1.6](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.6.md#node-components)

**Comment by SataQiu** [comment]
Well, I stumbled across the problem and found that it had been fixed in 1.16.
This is a bug that affects multiple versions.
If this patch is not needed for 1.15, I will use the version compiled by myself to solve this problem.
Thanks all @thockin @tpepper @cmluciano 
/close

**Pull request closed without merging**
