### PR TITLE
indent error flow

### PR DESCRIPTION
**Pull request by chenpengdev**
**What this PR does / why we need it**:
indent error flow

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/ok-to-test

**Comment by chenpengdev** [comment]
@dchen1107

**Pull request closed without merging**
