### PR TITLE
Fixing 'targetport' to service 'port' mapping

### LINKED ISSUE #54968: Fix targetport and port in winkernel proxy
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Target port and Ports were interchanged.

**What you expected to happen**: If the target ports and ports are different, they wouldn't work as expected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by madhanrm**
Looks like the order should be reversed for this to work.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #54968 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by thockin** [comment]
Can you please send a PR to add an OWNERS file in that directory with yourself as a `reviewer` and a couple other people who are equipped to review that code?  I (obviously) am not, really.

/lgtm
/approve

**Pull request merged**
