### PR TITLE
Fix volume imports

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, thanks for the super quick fix @yujuhong :)

**Comment by dchen1107** [comment]
#5742 is merged already close this one?

**Comment by yifan-gu** [comment]
Still need this fix... Thanks! @yujuhong

**Comment by yujuhong** [comment]
Let's wait until travis passes for real :)

**Comment by bgrant0607** [comment]
No, build is still broken:
```
pkg/kubelet/container/fake_runtime.go:131: undefined: volume.Interface
pkg/kubelet/container/fake_runtime.go:155: undefined: volume.Interface
pkg/kubelet/container/runtime.go:35: undefined: volume.Interface
pkg/kubelet/container/runtime.go:39: undefined: volume.Interface
```

**Comment by vmarmol** [comment]
@bgrant0607 the latest commit should fix that

**Comment by vmarmol** [comment]
Travis is passing :)

**Pull request merged**
