### PR TITLE
Bump default snap channel to 1.8/stable in juju charms

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This updates the Juju charms to deploy Kubernetes 1.8 by default.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Cynerva** [comment]
/assign @marcoceppi 
/assign @ktsakalozos 

Could one of you have a look and give this a /lgtm? Thanks.

**Comment by marcoceppi** [comment]
Quite exciting!

**Comment by mbruzek** [comment]
It is unlikely this change is breaking kops when to my knowledge they don't use this code.

/retest

**Pull request merged**
