### PR TITLE
Skip CLOSE_WAIT e2e test if server is 1.4.5

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Skip CLOSE_WAIT e2e test if server is 1.4.5
```

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36404)

### CODE REVIEW

**Comment by bowei** [comment]
@jessfraz @bprashanth 

this fixes the current red e2e tests

**Comment by saad-ali** [comment]
LGTM

**Comment by jessfraz** [comment]
LGTM thanks

**Comment by jessfraz** [comment]
Added all the labels

**Pull request merged**
