### PR TITLE
Making error msg for updating resource version more clear

### PR DESCRIPTION
**Pull request by jhadvig**
This is a follow up to https://github.com/GoogleCloudPlatform/kubernetes/pull/9569
@lavalamp thanks for advice PTAL
@smarterclayton thoughts ?

### CODE REVIEW

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
LGTM

**Comment by fabioy** [comment]
Can someone confirm the cla issue is resolved? Thank you.

**Comment by smarterclayton** [comment]
Jakub is a red hatter - I've added him to the system, let me see if it picks him up automatically.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Thanks!

**Pull request merged**
