### PR TITLE
Fix host network flake tests

### LINKED ISSUE #53091: [node-e2e flake] [k8s.io] Security Context when creating a pod in the host network namespace should listen on same port in the host network containers
Failure cluster: https://go.k8s.io/triage#22616c08c9151a6157a1

```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/security_context_test.go:254
Sep 20 08:21:34.986: host-networked container should listening on same port as host
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/security_context_test.go:252
```

This is the most prevalent flake for release-blocking postsubmit kubelet builds, eg:
- [kubelet](https://k8s-testgrid.appspot.com/release-master-blocking#kubelet&exclude-non-failed-tests=&sort-by-flakiness=&width=20)
- [kubelet-1.8](https://k8s-testgrid.appspot.com/release-1.8-blocking#kubelet-1.8&exclude-non-failed-tests=&sort-by-flakiness=&width=20)
- [kublet-1.7](https://k8s-testgrid.appspot.com/release-1.7-blocking#kubelet-1.7&exclude-non-failed-tests=&sort-by-flakiness=&width=20) (notably, it happens far less often here)

ref: #53018 we're probably going to need to ignore kubelet-1.8 for cutting a release

@kubernetes/sig-node-test-failures

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Fix flaky test "Security Context when creating a pod in the host network namespace should listen on same port in the host network containers".

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53091

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yujuhong** [comment]
Thanks for the quick fix!
/lgtm

**Comment by jpbetz** [comment]
Approved the cherry pick of the merge PR #53155

**Pull request merged**
