### PR TITLE
Changed SSH_USER to core instead ubuntu, also applied fixes from #11975

### PR DESCRIPTION
**Pull request by xsamurai**
The default user on coreos is core, ubuntu does not exist.

### CODE REVIEW

**Comment by yujuhong** [comment]
@xsamurai, could you follow @k8s-bot's instructions to sign the CLA? Thanks!

**Comment by xsamurai** [comment]
I signed it

**Comment by xsamurai** [comment]
I signed it

**Comment by xsamurai** [comment]
I signed it

**Comment by yujuhong** [comment]
@xsamurai, your commit is signed by "root". Could you change your commit to use the account that you signed the CLA with? Thank you.

**Comment by xsamurai** [comment]
I signed it

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by rastut** [comment]
When coreOS cluster is launched on aws, by default it will use an ami based on ubuntu, when the user core is used to ssh the master will be impossible to reach it and will keep running a loop failing the creation of the cluster:

https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L250-L269
```
function detect-image () {
case "${KUBE_OS_DISTRIBUTION}" in
  trusty|coreos)
    detect-trusty-image
    ;;
  vivid)
    detect-vivid-image
    ;;
  wheezy)
    detect-wheezy-image
    ;;
  jessie)
    detect-jessie-image
    ;;
  *)
    echo "Please specify AWS_IMAGE directly (distro ${KUBE_OS_DISTRIBUTION} not recognized)"
    exit 2
    ;;
esac
}
```
https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L276-L331
```
function detect-trusty-image () {
  # This is the ubuntu 14.04 image for <region>, amd64, hvm:ebs-ssd
  # See here: http://cloud-images.ubuntu.com/locator/ec2/ for other images
  # This will need to be updated from time to time as amis are deprecated
  if [[ -z "${AWS_IMAGE-}" ]]; then
    case "${AWS_REGION}" in
      ap-northeast-1)
        AWS_IMAGE=ami-93876e93
        ;;

      ap-southeast-1)
        AWS_IMAGE=ami-66546234
        ;;

      eu-central-1)
        AWS_IMAGE=ami-e2a694ff
        ;;

      eu-west-1)
        AWS_IMAGE=ami-d7fd6ea0
        ;;

      sa-east-1)
        AWS_IMAGE=ami-a357eebe
        ;;

      us-east-1)
        AWS_IMAGE=ami-6089d208
        ;;

      us-west-1)
        AWS_IMAGE=ami-cf7d998b
        ;;

      cn-north-1)
        AWS_IMAGE=ami-d436a4ed
        ;;

      us-gov-west-1)
        AWS_IMAGE=ami-01523322
        ;;

      ap-southeast-2)
        AWS_IMAGE=ami-cd4e3ff7
        ;;

      us-west-2)
        AWS_IMAGE=ami-3b14370b
        ;;

      *)
        echo "Please specify AWS_IMAGE directly (region ${AWS_REGION} not recognized)"
        exit 1
    esac
  fi
}
```

You can check that all this images are from Ubuntu in this page:
https://cloud-images.ubuntu.com/releases/14.04/release-20150305/

Also the delete of  `MINION_PRIVATE_IP` var will not fix anything, in the issue  #11975 says that deleting all the vars will do script go ahead but finally will crash because the script can't create the minions

**Comment by yujuhong** [comment]
@rastut, according to your comment, the default user should be "ubuntu", instead of "core"? 

/cc @justinsb

**Comment by rastut** [comment]
@yujuhong yes with the core user will keep looping, you can check in the code that when coreos env var is set it will use the `detect-trusty-image` . Also i have check all the images and are from ubuntu

**Comment by yujuhong** [comment]
Thanks for reporting thi!. Would you like to submit a fix?

**Comment by rastut** [comment]
I will try to submit a fix this weekend. But also i want to fix the minion provisioning loop that is related with #13185 #12273. I have been checking  that if you delete `MINION_PRIVATE_IP` the script will go ahead and will try to deploy  the nodes.

But when nodes are provisioned, and try to start up they will stop automatically. This is because when they are provisioned, there is a mess on the block devices in the autoscaling group. This happens also with the jessie deploy on aws. I don't know if is better a PR for the user and other for aws/util.sh

**Comment by rastut** [comment]
@yujuhong why is used an ami based on ubuntu in order to deploy the master? I don't know why nodes are deployed with ami based on CoreOS and  the master is deployed with Ubuntu.

**Comment by yujuhong** [comment]
> @yujuhong why is used an ami based on ubuntu in order to deploy the master? I don't know why nodes are deployed with ami based on CoreOS and the master is deployed with Ubuntu.

I have no idea why, and I think we need people who are familiar with the AWS setup to chime in...

**Comment by xsamurai** [comment]
Pretty much support for aws coreos kubernetes was/is broken a couple months back and this is semi discussed here https://github.com/kubernetes/kubernetes/issues/13190 .  It wouldnt make sense to launch all the minions with coreos ami and the master as ubuntu, and coreos ami's only log in as core user.  Nonetheless either coreos support is removed from kubernetes or it needs to be fixed so far the community has chosen to ignore it.

**Comment by rastut** [comment]
Well i will try to submit some pull request in order to get it working. I have been fixing the root device mapping that affects jessie and coreos deploy. In fact, i have try all the os that can be deployed on aws and only ubuntu would deploy without any modification, jessie need to modify scripts and coreos is fully broken

**Comment by rastut** [comment]
@xsamurai nowadays there is no check on the minion deploy. It needs to be implemented. You can check it on the `coreos/util.sh` :

```
function check-minion() {
  echo "working"
}
```
This morning i have launch a pr that will fix the mess on the block device ( #18821) and i have another that implements the minion check on the coreos nodes, i will try to send it this night

**Comment by xsamurai** [comment]
@rastut Correct Jessie was broken as well when I last tried.  I have a rather busy week next but I think Jessie would be a lot easier to fix as opposed to Coreos.  If you need help feel free to ping and I can work on some of the issues.

**Pull request merged**
