### PR TITLE
fix golint problem of volume cephfs/iscsi/nfs

### PR DESCRIPTION
**Pull request by jianglingxia**
What type of PR is this?
/kind bug
/kind cleanup

**What this PR does / why we need it**:
fix golint problem
/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:425:21: error strings should not be capitalized or end with punctuation or a newline

/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:191:2: don't use underscores in Go names; struct field secret_file should be secretFile
/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:253:10: if block ends with a return statement, so drop this else and outdent its block
/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:301:2: don't use underscores in Go names; var ceph_opt should be cephOpt
/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:349:2: don't use underscores in Go names; var keyring_file should be keyringFile
/media/B/src/k8s.io/kubernetes/pkg/volume/cephfs/cephfs.go:426:21: error strings should not be capitalized or end with punctuation or a newline
Found 5 lint suggestions; failing.

Found 1 lint suggestions; failing.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/approve

Would you be willing to fix all the other lint errors in these volume plugins and remove them from `hack/.golint_failures`?

**Comment by jianglingxia** [comment]
ok,I really happy to do this,would you lable the pr to milestone v1.13?thanks!

**Comment by jsafrane** [comment]
No, it's too late for 1.13 and this can wait for 1.14.

**Pull request merged**
