### PR TITLE
Fix csi_client_test.go metrics nil pointer dereference

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
Fix csi_client_test.go `TestVolumeHealthEnable` and `TestVolumeHealthDisable` function  to avoid null-pointer calls

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
/retest 
for CI hang

**Comment by humblec** [comment]
lgtm ! Thanks @mengjiao-liu :+1:

**Pull request merged**
