### PR TITLE
update logging-demo to use API v1beta3; modify the way to access Elasticsearch and Kibana services

### LINKED ISSUE #7818: missing public IP in examples/logging-demo
Hi @satnam6502 @nikhiljindal , I followed the instructions in examples/logging-demo, and there was no "external IP" field for elasticsearch-logging or kibana-logging, as shown below:
```json
../../_output/local/bin/linux/amd64/kubectl get services kibana-logging -o json
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "kibana-logging",
        "namespace": "default",
        "selfLink": "/api/v1beta3/namespaces/default/services/kibana-logging",
        "uid": "9dc6f856-f358-11e4-a58e-42010af09a93",
        "resourceVersion": "31",
        "creationTimestamp": "2015-05-05T18:57:45Z",
        "labels": {
            "kubernetes.io/cluster-service": "true",
            "name": "kibana-logging"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "",
                "protocol": "TCP",
                "port": 5601,
                "targetPort": "kibana-port"
            }
        ],
        "selector": {
            "name": "kibana-logging"
        },
        "portalIP": "10.0.188.118",
        "sessionAffinity": "None"
    },
    "status": {}
}
```
I start up my cluster via cluster/kube-up.sh. Did I miss something or is it a bug? Thanks.

### PR DESCRIPTION
**Pull request by caesarxuchao**
update logging-demo to use API v1beta3; modify the way to access Elasticsearch and Kibana services.

Fixes #7818.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@nikhiljindal @mbforbes

**Comment by mbforbes** [comment]
@satnam6502 what do you think?

**Comment by satnam6502** [comment]
The reason I have not updated this yet is that I am furiously working away on the logging blog article and in the process making a lot of changes to our logging setup and examples. We could merge this -- but the changes would be short lived since they are likely to be eclipsed by my work in progress.

**Comment by satnam6502** [comment]
Thank you very much for your help.

**Comment by caesarxuchao** [comment]
No problem : )

**Comment by mbforbes** [comment]
@satnam6502 shall I merge this in for the interim until your overhaul is complete?

**Pull request merged**
