### PR TITLE
Add IPv6 and negative UT test cases for proxier's deleteEndpointConnections

### LINKED ISSUE #53554: IPv6 IPs derived incorrectly in proxier's deleteEndpointConnections
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

/sig network
/area ipv6

**What happened**:
The calculation of endpointIP in the iptables proxier's deleteEndpointConnections() method does not handle endpoints of the form [ipv6-address]:port. The current logic strips off anything after the first colon it finds:
```
endpointIP := epSvcPair.endpoint[0:strings.Index(epSvcPair.endpoint, ":")]
```
so this won't work for IPv6. This can be seen on code inspection. It can also cause problems when running e2e networking tests that include UDP connections, whereby the kube-proxy will crash on a conntrack command, and restart.
 
**What you expected to happen**:
The code needs to derive IPv6 addresses from IPv6 endpoints of the form "[IPv6]:port", as well as deriving IPv4 addresses from IPv4 endpoints of the form "IPv4:port".

**How to reproduce it (as minimally and precisely as possible)**:
Code inspection, or run e2e UDP networking tests on an IPv6-only cluster (and watch for kube-proxy restarts).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Latest master
- Cloud provider or hardware configuration**: VirtualBox cluster, Ubuntu 16.04.1 host, CentOS 7 guests
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by leblancd**
This change adds IPv6 and negative UT test cases for the proxier's deleteEndpointConnections.

Changes include:
- Add IPv6 UT test cases to TestDeleteEndpointConnections.
- Add negative UT test case to TestDeleteEndpointConnections for
  handling case where no connections need clearing (benign error).
- Add negative UT test case to test unexpected error.
- Reorganize UT in TestDeleteEndpointConnections so that the fake
  command executor's command and scripted responses are generated on
  the fly based on the test case table (rather than using a fixed
  set of commands/responses that will need to be updated every time
  test cases are added/deleted).
- Create the proxier service map in real time, based on the test case
  table (rather than using a fixed service map that will need to be updated
  every time test cases are added/deleted).

fixes #53554

**What this PR does / why we need it**:
This change adds IPv6 and negative UT test cases for the proxier's
deleteEndpointConnections.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53554

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leblancd** [comment]
I couldn't figure out why the pull-kubernetes-bazel-test is failing, looks like everything is working until this timeout (don't know if this is normal):
```
W1007 12:44:26.259] TIMEOUT: //cmd/kube-apiserver/app/testing:go_default_test
```
As far as I can tell, the bazel dependencies are okay, so rerunning:

/test pull-kubernetes-bazel-test

**Comment by danehans** [comment]
@justinsb @smarterclayton sig-network is working hard to add IPv6 alpha support in 1.9. This PR is needed for IPv6 e2e testing. When you have a moment, do you mind reviewing this PR?

**Comment by danehans** [comment]
/assign thockin
/assign bowei

This PR is needed for IPv6 support in 1.9.

**Comment by thockin** [comment]
Will we need this same overhaul in the IPVS proxier?  @m1093782566 

/lgtm
/approve

**Comment by m1093782566** [comment]
@thockin 

IPVS proxier doesn't have the `TestDeleteEndpointConnections()` yet. 

I think IPVS proxier also needs this though IPVS proxier and Iptables proxier share the same code block in 

```
func (proxier *Proxier) deleteEndpointConnections(connectionMap map[endpointServicePair]bool) 
```

I can send a trivial PR firstly and then we discuss how to reduce the code duplication later?

**Comment by danehans** [comment]
@bowei @thockin anything else needed to get this PR merged?

**Comment by leblancd** [comment]
The pull-kubernetes-bazel-test gating test is failing for this PR because upstream master is missing the fix proposed in PR #55817 (Issue #55816).
@fejta: Is there a way to disable auto retest for this, at least until PR #55817 gets merged? Thanks.

**Comment by leblancd** [comment]
@fejta: Is there a way to disable auto retest for this, at least until PR #55817 gets merged? Thanks.

**Pull request merged**
