### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by thockin**
This dep is needed by boltdb, but it was not vendored.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this

**Comment by quinton-hoole** [comment]
Travis is complaining:
godep: restore, during download dep "github.com/camlistore/camlistore/pkg/errorutil": exit status 1
!!! Error in hack/verify-godeps.sh:77
  '"${GODEP}" restore' exited with status 1
Call stack:
  1: hack/verify-godeps.sh:77 main(...)
Exiting with status 1

I'll ask her to try again.

**Comment by smarterclayton** [comment]
The camlistore error was fixed yesterday in another issue - all merges that changed godeps were broken until that was resolved.

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this

**Comment by thockin** [comment]
Have to bump godep release - new commit added, lets see if travis is happier.

**Comment by quinton-hoole** [comment]
Still some unit test flakes (apparently):

```
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	300.675s
FAIL	k8s.io/kubernetes/pkg/util/wait	0.126s
```
Lets try again.
@k8s-bot unit test this

**Comment by quinton-hoole** [comment]
Some more details on the unit test failures:

```
I1230 19:21:09.605325    6525 portforward.go:213] Forwarding from [::1]:5000 -> 5000
panic: test timed out after 5m0s

goroutine 82 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive]:
testing.RunTests(0x17f40e0, 0x1e32640, 0x4, 0x4, 0xc820258d01)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc8200c3ef0, 0x4861bf)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	k8s.io/kubernetes/pkg/client/unversioned/portforward/_test/_testmain.go:60 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e537e0)
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/golang/glog.init.1
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ba

goroutine 8 [semacquire]:
sync.runtime_Semacquire(0xc820014f7c)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc820014f70)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
net/http/httptest.(*Server).Close(0xc820014f40)
	/tmp/workdir/go/src/net/http/httptest/server.go:168 +0x81
k8s.io/kubernetes/pkg/client/unversioned/portforward.TestForwardPorts(0xc8200aa240)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:360 +0x1230
testing.tRunner(0xc8200aa240, 0x1e32670)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 11 [chan send]:
k8s.io/kubernetes/pkg/util/httpstream/spdy.(*connection).SetIdleTimeout(0xc82000bb00, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/connection.go:138 +0x9b
k8s.io/kubernetes/pkg/kubelet/server.ServePortForward(0x7fc0f4bd8020, 0xc820270160, 0xc820272540, 0x7fc0f4bd8058, 0xc82000f020, 0x1598378, 0x3, 0x1599e40, 0x3, 0x0, ...)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:796 +0x4b6
k8s.io/kubernetes/pkg/client/unversioned/portforward.fakePortForwardServer.func1(0x7fc0f4bd8020, 0xc820270160, 0xc820272540)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:253 +0x265
net/http.HandlerFunc.ServeHTTP(0xc82000b740, 0x7fc0f4bd8020, 0xc820270160, 0xc820272540)
	/tmp/workdir/go/src/net/http/server.go:1422 +0x48
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc82000edc0, 0x7fc0f4bd8020, 0xc820270160, 0xc820272540)
	/tmp/workdir/go/src/net/http/httptest/server.go:200 +0xff
net/http.serverHandler.ServeHTTP(0xc8200107e0, 0x7fc0f4bd8020, 0xc820270160, 0xc820272540)
	/tmp/workdir/go/src/net/http/server.go:1862 +0x207
net/http.(*conn).serve(0xc8202700b0)
	/tmp/workdir/go/src/net/http/server.go:1361 +0x117d
created by net/http.(*Server).Serve
	/tmp/workdir/go/src/net/http/server.go:1910 +0x465
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	300.675s
```

```
=== RUN   TestPoll
==================
WARNING: DATA RACE
Write by goroutine 15:
  sync/atomic.AddInt32()
      /tmp/workdir/go/src/runtime/race_amd64.s:255 +0xb
  k8s.io/kubernetes/pkg/util/wait.fakeTicker.func1.1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:63 +0xff

Previous write by goroutine 14:
  k8s.io/kubernetes/pkg/util/wait.TestPoll()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:102 +0x631
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 15 (running) created at:
  k8s.io/kubernetes/pkg/util/wait.fakeTicker.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:66 +0x94
  k8s.io/kubernetes/pkg/util/wait.WaitFor()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:90 +0x43
  k8s.io/kubernetes/pkg/util/wait.pollInternal()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:55 +0x97
  k8s.io/kubernetes/pkg/util/wait.TestPoll()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:87 +0x144
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 14 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/util/wait/_test/_testmain.go:64 +0x20f
==================
--- FAIL: TestPoll (0.00s)
	wait_test.go:95: Expected exactly one tick, got 0
	wait_test.go:111: Expected exactly one tick, got 2
```

**Comment by quinton-hoole** [comment]
This time the etcd unit test failed.  Flaky tests... Sigh....
```
FAIL	k8s.io/kubernetes/pkg/storage/etcd	3.474s
```

**Comment by quinton-hoole** [comment]
Another race condition detected:

```
=== RUN   TestWatchEtcdState
==================
WARNING: DATA RACE
Write by goroutine 111:
  sync.raceWrite()
      /tmp/workdir/go/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
  net/http/httptest.(*Server).Close()
      /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
  k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).Terminate()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:151 +0x138
  k8s.io/kubernetes/pkg/storage/etcd.TestWatchEtcdState()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher_test.go:337 +0x125c
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous read by goroutine 63:
  sync.raceRead()
      /tmp/workdir/go/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 111 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/storage/etcd/_test/_testmain.go:110 +0x20f

Goroutine 63 (finished) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
--- PASS: TestWatchEtcdState (0.06s)
=== RUN   TestWatchFromZeroIndex
--- PASS: TestWatchFromZeroIndex (0.09s)
=== RUN   TestWatchListFromZeroIndex
--- PASS: TestWatchListFromZeroIndex (0.08s)
=== RUN   TestWatchListIgnoresRootKey
--- PASS: TestWatchListIgnoresRootKey (0.06s)
=== RUN   TestWatchPurposefulShutdown
--- PASS: TestWatchPurposefulShutdown (0.05s)
=== RUN   TestHighWaterMark
--- PASS: TestHighWaterMark (0.10s)
PASS
Found 1 data race(s)
FAIL	k8s.io/kubernetes/pkg/storage/etcd	3.474s
```

**Comment by thockin** [comment]
ugh, we grew ANOTHER unsatisfied dep.  will fix in this PR

**Comment by thockin-cc** [comment]
pushed with 2 missing deps now.

**Comment by thockin** [comment]
all green!

**Comment by quinton-hoole** [comment]
LGTM!

**Comment by quinton-hoole** [comment]
#18928 strikes again. 

@k8s-bot unit test this

```
WARNING: DATA RACE
Write by goroutine 59:
  sync.raceWrite()
      /tmp/workdir/go/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
  net/http/httptest.(*Server).Close()
      /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
  k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).Terminate()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:151 +0x138
  k8s.io/kubernetes/pkg/storage/etcd.TestWatchListIgnoresRootKey()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher_test.go:448 +0x948
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous read by goroutine 52:
  sync.raceRead()
      /tmp/workdir/go/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 59 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/storage/etcd/_test/_testmain.go:110 +0x20f

Goroutine 52 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
--- PASS: TestWatchListIgnoresRootKey (0.07s)
=== RUN   TestWatchPurposefulShutdown
--- PASS: TestWatchPurposefulShutdown (0.07s)
=== RUN   TestHighWaterMark
--- PASS: TestHighWaterMark (0.07s)
PASS
Found 2 data race(s)
FAIL	k8s.io/kubernetes/pkg/storage/etcd	3.883s
```

**Pull request merged**
