### PR TITLE
e2e: Update GetExternalIP and GetInternalIP method name to make them more explicit.

### PR DESCRIPTION
**Pull request by anggao**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update GetExternalIP and GetInternalIP method name within test/e2e/framework/node/resource.go to make them more explicit. As these methods do not return the IP only but IP concatenated with port 22 for ssh.
Change the method name to make it clear, also did some code cleanup.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/assign @pohly 

Patrick have been reviewing and consolidating all these functions

**Comment by anggao** [comment]
@aojea thank you!

**Comment by pohly** [comment]
Look good to me, but can we please merge this after PR #112923 ?

A rebase will probably be necessary.

**Comment by aojea** [comment]
> Look good to me, but can we please merge this after PR #112923 ?
> 
> A rebase will probably be necessary.

/hold

it has to wait to merge for the dependency PR https://github.com/kubernetes/kubernetes/pull/112923 

/lgtm
/approve

**Comment by anggao** [comment]
> Look good to me, but can we please merge this after PR #112923 ?
> 
> A rebase will probably be necessary.

Sure can do that.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by anggao** [comment]
@dims Yup I will rebase

**Comment by aojea** [comment]
/hold cancel

there is no rist to conflict with other PRs now

**Comment by aojea** [comment]
/retest
lots of failures , if is related it is weird, but better to be on the safe side

**Comment by anggao** [comment]
Thank you!

**Pull request merged**
