### PR TITLE
hairpin: fixing #15187

### PR DESCRIPTION
**Pull request by mcluseau**
First step in fixing #15187

/cc @thockin

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by MikaelCluseau** [comment]
Hopefully, one of the failing tests is:
```
--- FAIL: TestSyncPodWithHostNetwork (0.00s)
Expected: []string{"create", "start", "inspect_container", "inspect_container", "create", "start", "inspect_container"},
Actual:   []string{"create", "start", "inspect_container", "create", "start", "inspect_container"}
```
;) fixing right now.

**Comment by MikaelCluseau** [comment]
Test fixed. I have all the tests passing but have a timeout on this one:
```
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/config	121.711s
```
I hope it will be ok on shippable.

Sorry for still relying on the project's test infrastructure but I had some cgo cleanup after go upgrade to do before being able to run make test again.

**Comment by thockin** [comment]
LGTM, thanks!

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by karlkfi** [comment]
Our first winner!

Compilation error: 
```
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go:1842: pod.Spec.HostNetwork undefined (type api.PodSpec has no field or method HostNetwork)
```

**Comment by MikaelCluseau** [comment]
On 10/07/2015 02:52 PM, Kubernetes Bot wrote:
> GCE e2e test build/test **passed** for commit 5d9cd7c.

On 10/10/2015 01:32 AM, Kubernetes Bot wrote:
> GCE e2e build/test **failed** for commit 5d9cd7c.

On 10/10/2015 10:34 AM, Karl Isenberg wrote:
> Compilation error

```
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "5d9cd7c"=="5d9cd7c"
True
```

At http://stackoverflow.com/a/28792805:
> We check checksums that is considered cryptographically secure. Nobody has been able to break > SHA-1, but the point is, SHA-1 as far as git is concerned, isn't even a security feature. It's purely a > consistency check.

Which is where I don't get how I won :-/

Should I rebase on something?

**Comment by thockin** [comment]
rebase to upstream/master and `make && make test`

**Comment by MikaelCluseau** [comment]
As the first winner of the SecurityContext field introduction and move of the HostNetwork attribute into it, and since the new SecurityContext field is a pointer, I assume it's optional. I also assume that HostNetwork is considered false when the SecurityContext is nil.

Currently fixing the tests.

**Comment by thockin** [comment]
Correct.

**Comment by MikaelCluseau** [comment]
Here you are ;)

**Comment by MikaelCluseau** [comment]
```
F1016 06:01:44.542202   14958 proxy.go:132] listen tcp 127.0.0.1:35468: bind: address already in use
!!! [1016 06:01:57] Timed out waiting for kubectl proxy to answer at http://127.0.0.1:35468/healthz; tried 25 waiting 0.5 between each
```

**Pull request merged**
