### PR TITLE
kubelet: parallelize pod inspection in PLEG

### PR DESCRIPTION
**Pull request by yujuhong**
This should speed up pod startup time for batch pod creation.

Addressing #26394

### CODE REVIEW

**Comment by yujuhong** [comment]
I ran some node benchmark, but couldn't really say whether this helped with the pod batch creation or not. May need more measurement/tuning to see if this actually improves the performance.

/cc @resouer

**Review by yifan-gu — COMMENTED** [review]
nit: Line 182 in the function name : s/updateRelisTime/updateRelistTime

**Comment by yifan-gu** [comment]
@yujuhong LGTM, but I don't understand why we want to reinspect in the same iteration?

**Comment by resouer** [comment]
@yujuhong Actually I also did simple benchmark based on my original work, no significant improvement observed. It seems update cache is not in critical path ...

**Comment by yujuhong** [comment]
> @yujuhong Actually I just also did simple benchmark based on my original work, no significant improvement observed. It seems update cache is not in critical path ...

Yep.......it make sense in my head that this can be one of the bottenecks, but I couldn't get numbers to back it up. Need to start from profiling kubelet to identify the actual bottlenecks. I'll pick it up when I have time to do that. At the meantime, there is no need to review the PR further (@yifan-gu thanks for the review though!)

**Comment by timchenxiaoyu** [comment]
same puzzle with @yifan-gu   why we want to reinspect in the same iteration ?

**Pull request closed without merging**
