### PR TITLE
OWNERS(justaugustus): Prune extraneous reviewer roles

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Taking an opportunity to prune myself from some aliases/review paths
to reduce my workload.

If:
- I am no longer reviewing in an area, prune
- There were under five reviewers, remain
- I was already an approver for the area, prune from review path
- I was a reviewer as part of Release Managers, comment out with
  "approvals only"

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @liggitt @dims @saschagrunert @puerco @cpanato 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
Makes sense :+1: 
/lgtm

**Pull request merged**
