### PR TITLE
Add static pod support to mesos scheduler and executor.

### LINKED ISSUE #221: support for static pods
as per [k8s#6676][1] we need to support static pods in the kubelet-executor:

1. leverage existing support for static pods in the kubelet
  - scheduler must send executor a copy of static pod configuration (via executorInfo.data?)
    - executorInfo.data is only available to the executor upon registration, could be racy w' respect to kubelet startup (and pod source configuration)
1. scheduler needs to account for static pod resource usage upon launching an executor
  - scheduler will parse and eval static pod resource usage requirements
  - executor info resources need to be beefed up (eventually, once executor becomes a parent cgroup for pods)
1. confirm that static pods, that suddenly appear in the apiserver registry (kubelet static pod mirroring), are not picked up by the scheduler for scheduling!

[1]: https://github.com/GoogleCloudPlatform/kubernetes/issues/6676

### PR DESCRIPTION
**Pull request by joerg84**
Closes mesosphere/kubernetes-mesos#221
Depends on GoogleCloudPlatform/kubernetes#8882

Relevant commit "Add static pod support to mesos scheduler and executor." https://github.com/GoogleCloudPlatform/kubernetes/commit/59b9528ec50de4c4f18ff109a9763c53f05da435

### CODE REVIEW

**Comment by joerg84** [comment]
I am covered by the corporate CLA with Mesosphere.

**Comment by erictune** [comment]
ok to test

**Comment by erictune** [comment]
regarding the CLA: you may need to make sure your name is added to the right group within mesosphere, and that your commits were signed with your work email.

**Comment by joerg84** [comment]
Confirm

**Comment by joerg84** [comment]
@erictune two questions: 1) the CLA seems to be ok now, could you remove the label? 2) The Details link of the Build is pointing to some local path and so we unable to check the details. Could you have a look? 

Thank you so much for your effort, time, and help!

**Comment by erictune** [comment]
@joerg84 A robot controls the CLA label.  Can you reply with "I authored these commits" and see if makes the Robot happy?

**Comment by erictune** [comment]
You now need a rebase.

**Comment by erictune** [comment]
Build had this error:
```
+++ [0603 16:47:23] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    contrib/mesos/cmd/k8sm-scheduler
    contrib/mesos/cmd/k8sm-executor
can't load package: package github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-scheduler: cannot find package "github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-scheduler" in any of:
	/usr/src/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-scheduler (from $GOROOT)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-scheduler (from $GOPATH)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-scheduler
can't load package: package github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-executor: cannot find package "github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-executor" in any of:
	/usr/src/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-executor (from $GOROOT)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-executor (from $GOPATH)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/cmd/k8sm-executor
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:355
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 1
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:355 kube::golang::build_binaries_for_platform(...)
  2: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:493 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:28 main(...)
Exiting with status 1
```

**Comment by erictune** [comment]
It looks like one of your commits was authored by tsenart.  Googlebot may be confused about that.

**Comment by erictune** [comment]
Disregard my previous comments about the CLA.  I did some manual checking.  I can't find any record of a CLA for github users tsenart or joerg84.  You'd better have your CLA people talk to our CLA people.

**Comment by joerg84** [comment]
@erictune Thanks for checking! We will rebase right now. 
Regarding the CLA: All commits should signed with x@mesosphere.io and covered by the corporate Mesosphere CLA.

**Comment by tsenart** [comment]
@erictune: Thanks for reviewing this! We're covered by the Mesosphere corporate CLA. Github hides the email address from the their web UI if the emails used in the commits are linked to an SSH key of a Github account. You can verify our email with `$ git show --pretty=fuller staticPodsUpstream`

Regarding the current build failure, it seems like you pulled only the last commit and tested that individually. As described in the PR description, this change set depends on GoogleCloudPlatform/kubernetes#8882 and so includes its commits until it is merged.

For testing it, you need to git checkout the whole branch. If this is what you're already doing please let us know so that we can investigate.

Thanks again for your time on this.

**Comment by joerg84** [comment]
I authored these commits

**Comment by jdef** [comment]
You are correct @davidopp this is not yet hooked into the saltstack scripts. The first phase of the upstream plan (#6676) is to focus on getting the k8s-mesos components building as part of k8s. The second phase of that plan is to integrate with the saltstack scripts. We've proposed this static pods implementation as part of this "upstream PR collection" in preparation for a follow-up phase.

**Comment by davidopp** [comment]
LGTM for commit 54b6759ae99e0a48aa235740cebfd8629147d44b only. I'd feel better if you removed the other two commits from this PR. I realize we can't merge this PR anyway until those are submitted.

**Comment by jdef** [comment]
@joerg84 can you take care of this? removing the first two PR's will break
the build, but I'm OK with that since @davidopp is

**Comment by davidopp** [comment]
Please remove everything except commit 54b6759 from this PR.

**Comment by jdef** [comment]
Will do once #8882 has been merged. The last commit can't be cherry-picked
into its own commit yet since it changes files that are part of #8882.

**Comment by jdef** [comment]
I rebased this because #8882 has been merged. This PR now **only** contains the bits for static pods support.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Please wait to merge this.

**Comment by jdef** [comment]
rebased to latest master now that #9741 has landed

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
