### PR TITLE
Add debugging for delete grace period e2e flake

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind flake

**Which issue(s) this PR fixes**:
debugging for #85762 

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
Seems it need to update the generated code in order to build correctly

**Comment by aojea** [comment]
let's see if we hit it with the ipv6 jobs
/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-conformance-kind-ipv6

**Comment by aojea** [comment]
retrying

/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-e2e-gce

**Review by mattjmcnaughton — COMMENTED** [review]
/uncc

If there's anything you'd like a review on here, lmk and I'm happy to take a look. But from the pr description, looks like this is just for testing/debugging.

**Comment by liggitt** [comment]
#86318 flake
/retest

**Comment by aojea** [comment]
retrying, I only hit this in another PRs :/

/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-e2e-gce

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/issues/86318 flake again
/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-e2e-gce

**Comment by aojea** [comment]
#86318 flake again
/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-e2e-gce

**Comment by liggitt** [comment]
top flake according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

need to get some data on the failures asap or kick this out of conformance and into the flake job

**Pull request merged**
