### PR TITLE
Updating kubemci remove-clusters e2e test to use --force to remove from all clusters

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/173

Updating kubemci remove-clusters e2e test to validate that removing all clusters throws an error. It should succeed with --force=true

cc @G-Harmon

```release-note
NONE
```

### CODE REVIEW

**Comment by G-Harmon** [comment]
a bunch of jobs failed.
e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/62176/pull-kubernetes-bazel-build/36886/

**Comment by nikhiljindal** [comment]
Fixed, should pass now

**Comment by G-Harmon** [comment]
/LGTM
What's the pull-kubernetes-e2e-kops-aws failure?

**Comment by nikhiljindal** [comment]
/assign @madhusudancs for OWNERS approval

@G-Harmon Assume its flaky, the bot will retest and ensure its green before merging

**Review by madhusudancs — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
