### PR TITLE
add workdir in etcd Dockerfile for windows

### LINKED ISSUE #126348: [Flaking Test] post-kubernetes-push-image-etcd  failed
### Which jobs are failing?

[post-kubernetes-push-image-etcd](https://prow.k8s.io/?type=postsubmit&job=post-kubernetes-push-image-etcd) 

### Which tests are failing?

build

### Since when has it been failing?

only 2 runs are available.

### Testgrid link

https://testgrid.k8s.io/sig-k8s-infra-gcb#post-kubernetes-push-image-etcd

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1816299609958387712
```
ERROR: (gcloud.builds.submit) build a6dedce2-dd5a-468e-9a7a-0e50e159bd6f completed with status "FAILURE"


 [33m1 warning found (use --debug to expand):
[0m - InvalidDefaultArgInFrom: Default value for ARG ${RUNNERIMAGE} results in empty or invalid base image name (line 16)
Dockerfile.windows:22
--------------------
  20 |     COPY etcd* etcdctl* /usr/local/bin/
  21 |     COPY migrate-if-needed.bat /usr/local/bin/
  22 | >>> COPY migrate /usr/local/bin/migrate.exe
  23 |     
  24 |     # NOTE(claudiub): docker buildx sets the PATH env variable to a Linux-like PATH,
--------------------
ERROR: failed to solve: mkdir /var/lib/buildkit/runc-overlayfs/cachemounts/buildkit3627953617/usr/local/bin: not a directory
make[1]: Leaving directory '/workspace/cluster/images/etcd'
make[1]: *** [Makefile:132: build] Error 1
make: *** [Makefile:217: sub-push-image-windows-amd64-1809] Error 2
ERROR
ERROR: build step 0 "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240523-a15ad90fc9@sha256:bb04162508c2c61637eae700a0d8e8c8be8f2d4c831d2b75e59db2d4dd6cf75d" failed: step exited with non-zero status: 2
--------------------------------------------------------------------------------
2024/07/25 02:39:53 Failed to run some build jobs: [error running [gcloud builds submit --verbosity info --config 
```

### Anything else we need to know?

The etcd 3.5.15 post CI failed to build the image.
https://github.com/kubernetes/kubernetes/pull/126240 needs to promote the image: [gcr.io/k8s-staging-etcd/etcd:3.5.15-0](http://gcr.io/k8s-staging-etcd/etcd:3.5.15-0)
This is post submit CI for https://github.com/kubernetes/kubernetes/pull/126242.

### Relevant SIG(s)

/sig release etcd

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #126348

#### Special notes for your reviewer:

```release-note
None
```

### CODE REVIEW

**Comment by dims** [comment]
i was able to test this change.

```
docker buildx build \
	--pull \
	--provenance=false \
	--sbom=false \
	--output=type=registry \
	--platform "windows/amd64" \
	-t gcr.io/personal-gcp/etcd:3.5.15-0-windows-amd64-ltsc2022 \
	--build-arg BASEIMAGE=registry.k8s.io/build-image/debian-base:bookworm-v1.0.3 \
	--build-arg RUNNERIMAGE=mcr.microsoft.com/windows/nanoserver:ltsc2022 \
	-f /workspace/tmp.fdFPFE/Dockerfile.windows \
	/workspace/tmp.fdFPFE
#0 building with "modest_shirley" instance using docker-container driver

#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 0.2s done
#1 creating container buildx_buildkit_modest_shirley0
#1 creating container buildx_buildkit_modest_shirley0 0.6s done
#1 DONE 0.7s

#2 [internal] load build definition from Dockerfile.windows
#2 transferring dockerfile: 1.13kB done
#2 WARN: InvalidDefaultArgInFrom: Default value for ARG ${RUNNERIMAGE} results in empty or invalid base image name (line 16)
#2 DONE 0.0s

#3 [internal] load metadata for mcr.microsoft.com/windows/nanoserver:ltsc2022
#3 DONE 0.6s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/5] FROM mcr.microsoft.com/windows/nanoserver:ltsc2022@sha256:cc9f6a1334190c1f18a905f56d285132e562a9a1ce18ff9476cfaf95194aa0b7
#5 resolve mcr.microsoft.com/windows/nanoserver:ltsc2022@sha256:cc9f6a1334190c1f18a905f56d285132e562a9a1ce18ff9476cfaf95194aa0b7 0.0s done
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 0B / 116.77MB 0.2s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 9.44MB / 116.77MB 0.3s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 29.08MB / 116.77MB 0.5s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 50.33MB / 116.77MB 0.6s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 72.35MB / 116.77MB 0.8s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 95.42MB / 116.77MB 0.9s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 116.77MB / 116.77MB 1.1s
#5 sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 116.77MB / 116.77MB 1.3s done
#5 extracting sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b
#5 ...

#6 [internal] load build context
#6 transferring context: 146.03MB 1.7s done
#6 DONE 1.7s

#5 [1/5] FROM mcr.microsoft.com/windows/nanoserver:ltsc2022@sha256:cc9f6a1334190c1f18a905f56d285132e562a9a1ce18ff9476cfaf95194aa0b7
#5 extracting sha256:4f08abc68a60a91547c026d50bc32384338152a95155ab082f6ea8aaf874d94b 2.8s done
#5 DONE 4.2s

#7 [2/5] WORKDIR C:/usr/local/bin
#7 DONE 0.1s

#8 [3/5] COPY etcd* etcdctl* /usr/local/bin/
#8 DONE 0.7s

#9 [4/5] COPY migrate-if-needed.bat /usr/local/bin/
#9 DONE 0.0s

#10 [5/5] COPY migrate /usr/local/bin/migrate.exe
#10 DONE 0.1s

#11 exporting to image
#11 exporting layers
#11 exporting layers 7.6s done
#11 exporting manifest sha256:3f7cd7e9f2c7f157ae75f54ce51454aa1e0acf91949b7412c2e50979793a207b done
#11 exporting config sha256:36cae78b7e1e3af55f4201d98f99f23e6ba9c48efdd3da4f44ca21b0ff92bb85 done
#11 pushing layers
#11 ...

#12 [auth] personal-gcp/etcd:pull,push personal-gcp/gcr.io/etcd:pull token for gcr.io
#12 DONE 0.0s

#11 exporting to image
#11 pushing layers 4.1s done
#11 pushing manifest for gcr.io/personal-gcp/etcd:3.5.15-0-windows-amd64-ltsc2022@sha256:3f7cd7e9f2c7f157ae75f54ce51454aa1e0acf91949b7412c2e50979793a207b
#11 pushing manifest for gcr.io/personal-gcp/etcd:3.5.15-0-windows-amd64-ltsc2022@sha256:3f7cd7e9f2c7f157ae75f54ce51454aa1e0acf91949b7412c2e50979793a207b 0.2s done
#11 DONE 11.9s

```

**Comment by dims** [comment]
/triage accepted
/priority critical-urgent
/milestone v1.31
/approve
/lgtm

cc @kubernetes/release-team

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
thank you!!

**Comment by BenTheElder** [comment]
build is in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1816565679373946880

**Comment by BenTheElder** [comment]
the build passed in CI

**Pull request merged**
