### PR TITLE
[1.24] deps: Bump to cAdvisor v0.44.2

### PR DESCRIPTION
**Pull request by harche**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/118796

#### Does this PR introduce a user-facing change?

```release-note
Updated cAdvisor to v0.44.2 - Fix metrics in cri-o when a container restarts
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wasup-yash — COMMENTED** [review]
why are we doing bump to v0.44.2 as we are doing for [v0.47.2](https://github.com/kubernetes/kubernetes/pull/118797) ?

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
The cherry-pick's needs to be approved before we can merge them.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
