### PR TITLE
Remove ineffective calls in toUnstructured

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In toUnstructured(), there are several calls to Value#Set() which are followed by setting to the same value.

This PR removes the ineffective calls.

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
@liggitt @deads2k

Please review this.

**Comment by liggitt** [comment]
/cc @jpbetz 

/cc @wojtek-t 
do you recall why those were added?

**Comment by jpbetz** [comment]
> /cc @jpbetz
> 
> /cc @wojtek-t
> do you recall why those were added?

I don't know the history, but I'm not satisfied with the testing here. I've opened https://github.com/kubernetes/kubernetes/pull/86794 to fuzz test unstructured conversion for all kubernetes types. Would try it against this PR?

**Comment by jpbetz** [comment]
> > /cc @jpbetz
> > /cc @wojtek-t
> > do you recall why those were added?
> 
> I don't know the history, but I'm not satisfied with the testing here. I've opened #86794 to fuzz test unstructured conversion for all kubernetes types. Would try it against this PR?

Nevermind, I found `k8s.io/pkg/api/testing.TestRoundTrip` which does the same test.

**Comment by wojtek-t** [comment]
> /cc @wojtek-t
do you recall why those were added?

I can't remember it exactly, but I'm fairly sure that I added those to make some tests passing.
If all tests are passing without those now and we are confident about test coverage, I think that's fine.
I will try to dig deeper later today.

**Comment by wojtek-t** [comment]
I'm almost sure that this added to address the test that I added in this (converter_test.go):
staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter_test.go 

So given the test still exists and is passing:
- either I changed the implemention in the meantime (before submitting)
- or someone else fixed that later

But I'm fine with those changes.
@liggitt - does the change look suspicious to you? Or you were asking just to understand the past context?

**Comment by tedyu** [comment]
@liggitt 
Let me know if you have any more question.

**Comment by liggitt** [comment]
Were the referenced unit tests exercising the removed code paths?

**Comment by tedyu** [comment]
```
staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter_test.go
```
I don't see the above file in my k8s workspace.

There is ./staging/src/k8s.io/apimachinery/pkg/conversion/converter_test.go

**Comment by tedyu** [comment]
By placing breakpoints inside the 'dv.NumMethod() == 0' conditions starting:
```
	switch st.Kind() {
	case reflect.String:
		if dt.Kind() == reflect.Interface && dv.NumMethod() == 0 {
			dv.Set(reflect.New(stringType))
```
I was able to verify that pkg/api/testing/unstructured_test.go hits the code touched by this PR.

The test passes with this PR, showing that the special casing is not needed.

**Comment by wojtek-t** [comment]
> staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter_test.go

I meant staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go

> Were the referenced unit tests exercising the removed code paths?

I'm 100% sure they were in the past

Also, based on the above comment that tests are exercising those branches, I think we should be good.

/lgtm
/approve

**Pull request merged**
