### PR TITLE
Fix gofmt errors

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
There were some gofmt errors on master. Ran the following to fix:
```
hack/verify-gofmt.sh | grep ^diff | awk '{ print $2 }' | xargs gofmt -w -s
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: none

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@cblecker , I'm OK with this code clean up, but what's the version of your gofmt? Nothing from `hack/verify-gofmt.sh | grep ^diff | awk '{ print $2 }'`.  Mine is 1.7.3 :).

**Comment by cblecker** [comment]
Ah! And see, that's likely why Jenkins hasn't caught these issues. I'm on 1.8 locally:
```
go version go1.8 darwin/amd64
```

That being said, I don't think any of these format changes would introduce issues with go 1.7.

**Comment by justinsb** [comment]
I thought those were required... it'll be really interesting to see the build results.

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
All tests passed 🎉

**Comment by k82cn** [comment]
Great! That's helpful to the code :).

**Comment by cblecker** [comment]
@justinsb @lavalamp --
Ready for review and approval whenever you get a chance!

**Review by k82cn — APPROVED** [review]

**Comment by cblecker** [comment]
Hopefully that's the last rebase before code freeze is lifted :) *fingers crossed*

**Comment by cblecker** [comment]
@justinsb @lavalamp 
Now that the 1.6 freeze is over, is it possible to get this reviewed and approved? Thank you!

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by cblecker** [comment]
ping @justinsb

**Comment by cblecker** [comment]
over to @lavalamp for approval!
/assign @lavalamp

**Comment by lavalamp** [comment]
We shouldn't make 1.8 gofmt changes until we're ready to switch to 1.8.

**Comment by cblecker** [comment]
@lavalamp Wouldn't this be pre-requisite work to #41636 which will bump everything up to go 1.8 on master? The formatting changes don't break go 1.7.5, but will ensure that master is ready to go when we swap over.

**Comment by lavalamp** [comment]
I guess it doesn't matter if we merge this first. But since the current gofmt doesn't care, we'll probably have to make this change again.

/approve

**Comment by cblecker** [comment]
Commenting to try and get this dropped from my PR dashboard :)

**Pull request merged**
