### PR TITLE
Fixed failed build on Mac.

### PR DESCRIPTION
**Pull request by k82cn**
fixed build error on Mac.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35897)

### CODE REVIEW

**Comment by timstclair** [comment]
What's the error? What part of this doesn't build on mac?

**Comment by k82cn** [comment]
@timstclair , here's the error of build:

```
# k8s.io/kubernetes/test/e2e_node
test/e2e_node/restart_test.go:77: undefined: newTestPods
test/e2e_node/restart_test.go:79: undefined: createBatchPodWithRateControl
test/e2e_node/restart_test.go:80: undefined: deletePodsSync
make: *** [all] Error 1
```

`newTestPods` is defined in `test/e2e_node/resource_collector.go` which is only built on Linux.

**Comment by timstclair** [comment]
None of those methods should be linux specific. I think a better solution is to move those out into a common place.

**Comment by k82cn** [comment]
@timstclair , AFAIK, e2e did not support Mac for now; so is it necessary to move those them out? And I think maybe we should avoid build e2e on Mac. WDYT?

**Comment by timstclair** [comment]
I'd be OK with skipping the e2e build all together on mac, but we should get input from someone with more knowledge of our build system.

/cc @kubernetes/sig-testing @Random-Liu

**Comment by Random-Liu** [comment]
@timstclair When `make release`, we should have already skipped node e2e on mac. https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L136-L142

For `make` I don't know how we could skip based on platform except add `+build` comment.

**Comment by ixdy** [comment]
This is probably fine, but why are you even building node e2e tests for darwin?

**Comment by k82cn** [comment]
@k8s-bot verify test this

**Comment by k82cn** [comment]
@Random-Liu / @timstclair / @ixdy, can we merge this PR firstly? I'd like to open a new issue to remove e2e/e2e_node in `make`.

**Comment by ixdy** [comment]
@k82cn what command are you running that builds this?

**Comment by k82cn** [comment]
@ixdy , run `make` in Kubernetes source code directory directly.

**Comment by ixdy** [comment]
/lgtm

`resource_usage_test.go`, `density_test.go`, and `container_manager_test.go` all already set the `+build linux` tag. Ideally we'd avoid building any of the node e2e test code on !linux, but that's a larger effort, and there's already precedent for what this PR is doing.

**Comment by smarterclayton** [comment]
@saad-ali can we merge this to 1.5 to allow Macs to build?

**Comment by dims** [comment]
@smarterclayton : +1 to mark this milestone v1.5, please let me know if you want me to throw that in

**Comment by k82cn** [comment]
@timstclair / @Random-Liu / @ixdy ,  #36792 was filed to trace the discussion on removing e2e/e2e_node from `make`.

**Comment by Random-Liu** [comment]
Mark v1.5 because this is a relatively small change and fixes build on Mac.
@saad-ali

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by saad-ali** [comment]
> @saad-ali can we merge this to 1.5 to allow Macs to build?

Ack.

**Pull request merged**
