### PR TITLE
Automated cherry pick of #66652: fix cluster-info dump error

### PR DESCRIPTION
**Pull request by juanvallejo**
Cherry pick of #66652 on release-1.11.

#66652: fix cluster-info dump error

**Release note**:
```release-note
fix cluster-info dump error
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
Not a clean pick.

cc @soltysh

**Comment by mkumatag** [comment]
This patch I need badly, can someone please help me get this in? @kubernetes/sig-cli-maintainers

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
@foxish for 1.11 cherry-pick approval

**Pull request merged**
