### PR TITLE
Update etcd client to v3.4.7 in k8s v1.19

### PR DESCRIPTION
**Pull request by jingyih**
**What type of PR is this?**
/kind feature

**Which issue(s) this PR fixes**:
#89779

**Does this PR introduce a user-facing change?**:
```release-note
Update etcd client side to v3.4.7
```

/sig api-machinery

### CODE REVIEW

**Comment by dims** [comment]
@jingyih modifying our use of etcd to include `WithRequireLeader` change will go in separately? (discussion was in https://github.com/kubernetes/kubernetes/issues/89488)

cc @embano1

**Comment by wojtek-t** [comment]
LGTM, but I would prefer someone more familiar with godeps to approve.

**Comment by jingyih** [comment]
> @jingyih modifying our use of etcd to include `WithRequireLeader` change will go in separately? (discussion was in #89488)
> 
> cc @embano1

`WithRequireLeader` is already in etcd clientv3. This version bump includes a bug fix for that. I would prefer the change to include `WithRequireLeader` in k8s codebase to be a separate PR.

**Comment by jingyih** [comment]
> LGTM, but I would prefer someone more familiar with godeps to approve.

Thanks! On my side, I've checked the code changes under vendor folder.

/assign @liggitt for godep related changes.

**Comment by jingyih** [comment]
`pull-kubernetes-node-e2e-containerd` has been failing for all PRs recently.

**Comment by jingyih** [comment]
@liggitt Could you help review the go mod changes in this PR?

**Comment by embano1** [comment]
> WithRequireLeader is already in etcd clientv3. This version bump includes a bug fix for that. I would prefer the change to include WithRequireLeader in k8s codebase to be a separate PR.

Thanks for the clarification, I was about to include the etcd version bump in my PR. Should I wait filing my PR then (would only include the `WithRequireLeader` change) because it has a dependency on this one to be merged?

**Comment by jingyih** [comment]
@embano1 
> I was about to include the etcd version bump in my PR

This is not necessary because the bug fix introduced in this PR did not change API signature `WithRequireLeader`

> Should I wait filing my PR then (would only include the `WithRequireLeader` change) because it has a dependency on this one to be merged?

Please feel free to file your PR. If you want to ensure the bug fix in this PR is merged before k8s codebase incorporates `WithRequireLeader`, you can use `\hold` in your PR. Well this PR is just merged anyway, so this is not needed.

**Pull request merged**
