### PR TITLE
The Gluster PV claims with ROX should have readonly bool set in volume spec

### PR DESCRIPTION
**Pull request by humblec**
Issue # https://github.com/kubernetes/kubernetes/issues/37060

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37061)

### CODE REVIEW

**Comment by humblec** [comment]
@jsafrane @rootfs PTAL .

**Comment by jsafrane** [comment]
* `PVC.Spec.AccessModes` is array that specifies that an user wants a PV that has any of the provided AccessModes. RWO does not need to be the first one.

* What are read-only dynamically provisioned volumes good for? They will be always empty.

**Comment by humblec** [comment]
@jsafrane Thanks !
`
PVC.Spec.AccessModes is array that specifies that an user wants a PV that has any of the provided AccessModes. RWO does not need to be the first one.
`
Yes, I thought it will be always filled with 'one' value based on the 'claim access mode' mentioned in the claim file atleast when it reaches to CreateVolume().

`
What are read-only dynamically provisioned volumes good for? They will be always empty.
`
At present, we set to 'false' regardless of the claim access mode. https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L589

The problem is that, when it comes to the code path which mounts the volume to pod, this value is taken from https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L141  and used in newMounterInternal() which allows the pod to mount the volume as RW by deafult. That is what I am trying to avoid.

**Comment by jsafrane** [comment]
>> PVC.Spec.AccessModes is array that specifies that an user wants a PV that has any of the provided AccessModes. RWO does not need to be the first one. 

> Yes, I thought it will be always filled with 'one' value based on the 'claim access mode' mentioned in the claim file atleast when it reaches to CreateVolume().

No, claim may specify several access modes and unless **all** of them are ROX you should not set ReadOnly flag.

I admit, all the other provisioners do not care about ROX at all and they do not set ReadOnly when they probably should. Again, what is empty read-only volume good for?

**Comment by humblec** [comment]
`
No, claim may specify several access modes and unless all of them are ROX you should not set ReadOnly flag.
`
Ah.. Missed the fact that, a claim can mention more than one access mode.  I completely agree,  it should only set only when 'all' are ROX.  

`what is empty read-only volume good for?`  -> Good question :) , unless  `readOnly` is an SC parameter and some special logic applied by Heketi  to mount a READONLY volume ( which is existing and not empty) from the backend, it does not make sense! 

Final question, do u think atleast for NOT confusing the user when they describe the PV, if all the accessmodes are RO, setting this value in volume spec make sense ?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@jsafrane regardless of its usefulness, I have corrected the volume spec, so that it will not confuse the users or it will not cause any issues in future.

**Comment by jsafrane** [comment]
I think we should solve it globally for all volume plugins, probably somewhere in Kubelet. When a RWO PV or RWO PVC is mounted, it should be mounted as read-only.

**Comment by humblec** [comment]
@jsafrane in this line,  `When a RWO PV or RWO PVC is mounted, it should be mounted as read-only.`, you meant ROX PV or PVC , Isnt it ? Yeah, fixing it in kubelet level would be good , however with this patch I thought of correcting the volume spec for dynamically provisioned volumes. So that there is no confusion for the admin/end user.

**Comment by rootfs** [comment]
@humblec still working on this ?

**Comment by humblec** [comment]
@rootfs yeah, I will rebase the patch soon.

**Comment by humblec** [comment]
@rootfs @jsafrane rebased the patch. Please review.

**Pull request closed without merging**
