### PR TITLE
kubeadm: bump etcd to 3.3.15 in 1.16

### LINKED ISSUE #1726: update etcd to 3.3.15 in 1.16
etcd is seeing a critical backport due to this issue:
https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-521387400

update etcd in kubeadm to 3.3.14 before the 1.16 release!

preliminary PR for adoption:
https://github.com/kubernetes/kubeadm/issues/1726

etcd image / version bump:
https://github.com/kubernetes/kubernetes/pull/82199
https://github.com/kubernetes/kubernetes/pull/82348

TODO: we need to close this ticket after that
https://github.com/kubernetes/kubeadm/issues/1432

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup
/kind feature

**What this PR does / why we need it**:
kubeadm: bump etcd to 3.3.15 in 1.16

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1726

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: bump etcd to 3.3.15 in 1.16
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @SataQiu 
we need to wait for the GCR maintainers to push the 3.3.15 image at GCR:
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/etcd?gcrImageListsize=30

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by xmudrii** [comment]
@SataQiu @dixudx @neolit123 This PR is in the 1.16 milestone with `lgtm` and `approve` labels but is being held. Is there a plan when this PR will be merged? The code freeze has started last night.

**Comment by neolit123** [comment]
@xmudrii this PR is waiting on a etcd 3.3.15 docker image to be pushed to GCR.

**Comment by alejandrox1** [comment]
For reference: we should keep this PR in the 1.16 milestone
From the slack thread that Lubomir added:
> we already updated the etcd client we use to 3.3.15, we need to change the default etcd server as well
/cc @xmudrii

**Comment by neolit123** [comment]
/close
the bump will happen in https://github.com/kubernetes/kubernetes/pull/82199
we need to bump multiple things at once for the tests to pass.

**Pull request closed without merging**
