### PR TITLE
cherry pick of knp 0.0.27

### PR DESCRIPTION
**Pull request by jdnurme**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates konnectivity-network-proxy to v0.0.27. This includes a memory leak fix for the network proxy

see: https://github.com/kubernetes/kubernetes/pull/106922
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Updates konnectivity-network-proxy to v0.0.27. This includes a memory leak fix for the network proxy
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
please update the description and release note referencing the memory leak being fixed (and the `master` PR)

/lgtm
/approve

**Review by rata — APPROVED** [review]
LGTM - Thanks for the backport @jdnurme ! :)

**Comment by rata** [comment]
Who can/should approve the cherry-pick ?

**Comment by aojea** [comment]
> 

ping @kubernetes/release-managers

**Comment by xmudrii** [comment]
Is only 1.23 affected or we should cherry-pick to other branches as well?

**Comment by rata** [comment]
@xmudrii other branches are affected as well. This should also be backported to 1.21 and 1.22 too

@jkh52 did some changes to allow this to be backported as lower as 1.21 (see https://github.com/kubernetes-sigs/apiserver-network-proxy/commit/084136e6f2db15be07928d3e5e92a2a5eaac7e39)

**Comment by xmudrii** [comment]
@rata Thanks for the update! Can you please also create other cherry-picks and get them approved? We tend to prefer to merge cherry-picks fixing the same issue across release branches at the same time.

**Comment by rata** [comment]
@xmudrii thanks, I've just created the others :)

**Comment by rata** [comment]
@jdnurme please take a look if you can you too :)

**Comment by jkh52** [comment]
@jdnurme has a duplicate at https://github.com/kubernetes/kubernetes/pull/107037 but this PR updates the server and agent images to match which is proper per https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/RELEASE.md

I think it's fine to use yours. Same comment for the other release branch PRs.

/lgtm

**Comment by rata** [comment]
@jkh52 who are you talking to? I don't have permissions to do anything in that doc. So, I assume you are talking to @jdnurme ? 

Also, what images are missing update? This PR does update the manifests, and the tags exist in the anp repo (https://github.com/kubernetes-sigs/apiserver-network-proxy/tags). What is missing?

**Comment by jkh52** [comment]
> @jkh52 who are you talking to? I don't have permissions to do anything in that doc. So, I assume you are talking to @jdnurme ?
> 
> Also, what images are missing update? This PR does update the manifests, and the tags exist in the anp repo (https://github.com/kubernetes-sigs/apiserver-network-proxy/tags). What is missing?

Sorry for causing confusion, too many tabs open. I mean that feeback for https://github.com/kubernetes/kubernetes/pull/107069. This PR looks correct.

**Pull request merged**
