### PR TITLE
Fix missing omitempty tag

### PR DESCRIPTION
**Pull request by aanm**
I know this is a "large" commit but the lack of "omitempty" create unnecessary json code.

There is a special case where I don't know if I should keep `json:",inline,omitempty"` or `json:",inline"` so I'm requesting feedback on that one.

Signed-off-by: André Martins aanm90@gmail.com

### CODE REVIEW

**Comment by bgrant0607** [comment]
Hi. What problem are you trying to address?

omitempty is used to indicate optional fields:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#optional-vs-required

It can't be applied to many of the fields where you added it. 

I also don't think it makes sense to add it to inlined fields.

**Comment by aanm** [comment]
Hello.

But if they are empty or nil does it make sense to send an empty value as well?

I'm not trying to address a specific problem I just got failing tests because I was expecting, for example, a struct with `foo="foo", bar="bar"` and when I did an Unmarshal and Marshal I got `foo="foo", bar="bar", foobar=""`. One of them was `ServiceAccountName`.

I can still change the unit test so it can pass ;-)

**Comment by bgrant0607** [comment]
I'm busy trying to wrap up 1.1 and will take another look once it is out the door.

**Comment by bgrant0607** [comment]
cc @markturansky @thockin

**Comment by thockin** [comment]
I feel your pain wrt unmarshalling empty fields, but I don't think that decorating them as optional (when they are not) is the right answer.  Doing an exact JSON comparison is probably not something that we want to focus on.

**Pull request closed without merging**
