### PR TITLE
Multi-port Endpoints

### PR DESCRIPTION
**Pull request by thockin**
This is just another part of multi-port services.  It layers on #4707, which you can see in the commit list.

There are a couple open FIXMEs in there, PTAL.  Specifically - what do we want kubectl output to be now that endpoints are somewhat more complex?

### CODE REVIEW

**Comment by rjnagal** [comment]
@lavalamp assignee it you for review, since you are already at it :)

**Comment by lavalamp** [comment]
Wait-- I confused this with the other PR; does this share some commits?

**Comment by thockin** [comment]
oops.  #4712 = #4707++

**Comment by lavalamp** [comment]
OK, sorry about this. I reverted and will actually read this one now.

**Comment by thockin** [comment]
Shall we revert this, then run with #4707 then revisit this?

**Comment by thockin** [comment]
I'll just re-offer this one

**Pull request merged**
