### PR TITLE
Assign host's IPAddress to podIP when pod shares the host's network

### LINKED ISSUE #10022: Pods that are using host network should still be accessible to other pods via the API semantics
We realized just recently that HostNetwork pods aren't given a pod IP.  I wanted to get agreement on how we can make that pod visible. 

1. The effective ip of the pod is the host ip (which we also set).  
  1. We could set podIP to hostIP when in host networking and all higher level components would work
  2. We could change higher level components like the endpoints controller to look at hostIP instead of podIP in this case
2. The pod should get an ip assigned by the network plugin, but the network plugin makes the decision

We could do both of the above.  i don't know that we've formally stated hostIP is the internal cluster IP - because podIP is guaranteed to work in the cluster I think we would have to formalize that.

I'm looking for a quick decision (if possible) on whether 1.1 or 1.2 are acceptable - if they are, we are considering carrying a patch.

### PR DESCRIPTION
**Pull request by rajatchopra**
Fixes #10022

### CODE REVIEW

**Comment by rajatchopra** [comment]
Attention @dchen1107 @smarterclayton

**Comment by dchen1107** [comment]
LGTM

**Comment by smarterclayton** [comment]
ok to test

**Comment by dchen1107** [comment]
ok to test

There are 3 flaky tests which shouldn't be caused by this pr

**Comment by dchen1107** [comment]
Those flaky tests are caused by bad forwarded rules in testing e2e cluster. 

ok to test

**Comment by satnam6502** [comment]
Does the CIA need to be fixed?

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by smarterclayton** [comment]
Rajat is covered under the red hat CLA, but I need to fix his membership.

**Pull request merged**
