### PR TITLE
Include audit log in master log capture

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by shyamjvs** [comment]
/lgtm
I think it'd add ~15GB of extra gcs storage (per 5k perf-test run) iirc from what I saw earlier - but worth giving a shot.

**Comment by liggitt** [comment]
> I think it'd add ~15GB of extra gcs storage (per 5k perf-test run) iirc from what I saw earlier - but worth giving a shot.

can surface maxsize/maxbackup settings and tune them down for that job if needed

**Comment by shyamjvs** [comment]
SGTM. Can we close this with https://github.com/kubernetes/kubernetes/pull/52998?

**Comment by shyamjvs** [comment]
Maybe let's just let this be, as it's close to being merged.

**Pull request merged**
