### PR TITLE
Remove redundant call to StartLogging in service_controller. Fixes #5…

### PR DESCRIPTION
**Pull request by athampy**
…4339

**What this PR does / why we need it**:
Removes redundant call to StartLogging introduced in 96b48d4#diff-1f7f903e25ab8bcbc514bb1e532e997e

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#54339 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by athampy** [comment]
Signed CLA

**Review by MrHohn — APPROVED** [review]
/lgtm

**Pull request merged**
