### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by metral**

### CODE REVIEW

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
LGTM

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #17998

**Comment by davidopp** [comment]
@bgrant0607  is that what this is? (from e2e)

```

â€¢ Failure [1522.033 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1089
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:509
    should support exec [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:219

    Expected error:
        <*errors.errorString | 0xc208590640>: {
            s: "Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://107.178.221.246 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config exec --namespace=e2e-tests-kubectl-3k1jr -i nginx bash] []  0xc208404778 hi\n  [] <nil> 0xc2085562e0 exit status 2 <nil> true [0xc208404778 0xc2084047e0 0xc208404850] [0xc2084047e0 0xc208404850] [0xc2084047c8 0xc208404848] [0x95bf50 0x95bf50] 0xc20895f2c0}:\nCommand stdout:\nhi\n\nstderr:\n\nerror:\nexit status 2\n",
        }
        Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://107.178.221.246 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config exec --namespace=e2e-tests-kubectl-3k1jr -i nginx bash] []  0xc208404778 hi
          [] <nil> 0xc2085562e0 exit status 2 <nil> true [0xc208404778 0xc2084047e0 0xc208404850] [0xc2084047e0 0xc208404850] [0xc2084047c8 0xc208404848] [0x95bf50 0x95bf50] 0xc20895f2c0}:
        Command stdout:
        hi
        
        stderr:
        
        error:
        exit status 2
        
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1538
```

**Comment by davidopp** [comment]
Also, the integration failure was

```
k8s.io/kubernetes/pkg/kubectl
```

but I didn't see any useful logging.

**Comment by bgrant0607** [comment]
@davidopp No, I cited the kubectl test failure cause. The build was broken by a test that didn't work across the daylight savings time change.

The exec failure is looks like yet another variant of the exec e2e failures (search github for "simple pod should exec")

**Pull request merged**
