### PR TITLE
Bump cadvisor to latest

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by kargakis** [comment]
@vmarmol ping

**Comment by vmarmol** [comment]
LGTM, thanks @kargakis!

**Comment by vmarmol** [comment]
Actually, how come there was no Godep.json update? Did you use godep for the change?

**Comment by kargakis** [comment]
> Actually, how come there was no Godep.json update? Did you use godep for the change?

No, I updated it manually. I don't have most of the imported packages in my $GOPATH and godep yells about it.

**Comment by kargakis** [comment]
Even if I update the json file manually, I won't be able to change the comments so I will have to remove them. Instead of doing that, do you mind closing this and bumping cadvisor?

**Comment by vmarmol** [comment]
@kargakis will do :)

an easy way to update Godeps (at least how I do) is to `godep restore`, update dependency, `godep update <package>`

Closing and will send something soon.

**Comment by vmarmol** [comment]
Sent out #5934

**Pull request closed without merging**
