### PR TITLE
Heapster v0.20.0-alpha3

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @gmarek 
Another attempt to switch to the new Heapster.

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by mwielgus** [comment]
Looks like this attempt succeeded. We have the new version of Heapster (and Influxdb) onboard.

cc: @fgrzadkowski @jimmidyson @timothysc @vishh   

We will try to push a new (v0.20.0-alphaX) release every couple days.

**Comment by jlowdermilk** [comment]
Per https://github.com/kubernetes/kubernetes/pull/20428#issuecomment-178148417, this is the root cause behind failing [kubernetes-e2e-gce-autoscaling](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/) tests.  Any ETA on when we should expect to see them passing again?

**Comment by mwielgus** [comment]
Yes, we are aware of the missing functionality. I'm working on this.

ETA: Tomorrow (Feb 3).

**Comment by alex-mohr** [comment]
I'm confused.  Two questions.

This is a known break of an e2e test suite, for which the  proper response is rollback to make the e2es passing again -- not to leave the e2e broken for 24+ hours.  Why didn't we rollback?

Second question: if this was the second attempt and HPA is a known dependency, why didn't we discover that HPA breaks before this merged instead of after?

**Comment by mwielgus** [comment]
@alex-mohr This change does NOT break HPA. The thing that got broken is a suite with Google-specific cluster node autoscaler which is currently in an alpha state.

**Comment by alex-mohr** [comment]
Sorry, s/HPA/kubernetes-e2e-gce-autoscaling suite/.  Which is currently at least nominally in the critical builds list.

And to be clear, I'm mostly interested in preventing similar situations in the future.  What can we learn from this?

**Comment by piosz** [comment]
>Second question: if this was the second attempt and HPA is a known dependency, why didn't we discover that HPA breaks before this merged instead of after?

I've run HPA tests locally ~10 times before and they passed all time.

**Comment by mwielgus** [comment]
The reason why we wanted to do the upgrade was that we wanted to switch Kubernetes to the new, better Heapster (that actually improves HPA a lot) before the code-complete freeze so that we have enough runs of the code and don't have to do some frantic last-minute changes.

**Comment by piosz** [comment]
kubernetes-e2e-gce-autoscaling suite is not blocking submit queue right now (not sure what do you mean by critical builds).

**Comment by jlowdermilk** [comment]
Jobs in the "critical builds" view on jenkins are (per [docs](https://github.com/kubernetes/kubernetes/wiki/Github-and-Build-Cop-Rotation#build-copping)) buildcop's responsibility to monitor. They don't all block submit queue because some of the tests (including autoscaling) take a long time to run, but they should still stay green.

**Comment by mwielgus** [comment]
Ok then the simplest solution would be removing kubernetes-e2e-gce-autoscaling from jenkins critical builds until we fix the stuff. Sorry for confusion.

**Comment by mwielgus** [comment]
I will do it in ~2.5 h.

**Comment by gmarek** [comment]
@jlowdermilk - IIRC there are some v1.0 and v1.1 suites in the critical build view. Generally I have an impression that suites were very lightly added to this view and currently it's huge. If you really want build cop to monitor those we should limit their number to ones that REALLY have to stay green (I know - everyone thinks that his/her suite should be there) and in addition ones that build cop can actually fix (e.g. have access to corresponding project, which wasn't true for me some time back).

**Comment by vishh** [comment]
@mwielgus: Congrats!!

**Pull request merged**
