### PR TITLE
Delete gotest-dockerized

### PR DESCRIPTION
**Pull request by fejta**
This file moved to kubernetes/test-infra

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36834)

### CODE REVIEW

**Comment by krousey** [comment]
Are the new tests passing yet?

**Comment by fejta** [comment]
This is orthogonal, as nothing uses this file any more. This is also to make sure that https://github.com/kubernetes/test-infra/pull/1068 works for PRs

**Comment by fejta** [comment]
The most recent run failed with:
```
I1115 11:21:48.281] Found illegal 'flag' usage. If these are false negatives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
I1115 11:21:48.282] .gsutil/credstore:        "api_version": "v1"
I1115 11:21:48.289] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-flags-underscore.py	56s
```

which https://github.com/kubernetes/test-infra/pull/1068 should resolve

**Comment by dims** [comment]
@fejta curious about the "do-not-merge" label..

**Comment by fejta** [comment]
I'll take it off once tests pass

**Comment by spxtr** [comment]
As long as the tests look happy...

/lgtm

**Comment by saad-ali** [comment]
Looks like this may have broken [kubernetes-test-go](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-test-go/) and [kubernetes-verify-master](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-verify-master/)

```
+ KUBE_TEST_SCRIPT=./hack/jenkins/verify-dockerized.sh
+ timeout -k 15m 80m ./hack/jenkins/gotest-dockerized.sh
timeout: failed to run command ‘./hack/jenkins/gotest-dockerized.sh’: No such file or directory
```

**Comment by ixdy** [comment]
Is someone reverting this?

**Comment by fejta** [comment]
no

**Comment by ixdy** [comment]
Why not? The fix requires changes in multiple repos, as well as updating the SQ. We're currently merging nothing because all tests are failing.

**Pull request merged**
