### PR TITLE
add test for set image validation

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by zjj2wry** [comment]
@thockin mind give an approval ? I think brendandburns is quite busy recently

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
