### PR TITLE
e2e_node: replace `registry.k8s.io/stress:v1` with agnhost

### LINKED ISSUE #123146: e2e_node: Rebuild `registry.k8s.io/stress:v1` as Schema2 or OCI
https://github.com/kubernetes/kubernetes/blob/244fbf94fd736e94071a77a8b7c91d81163249d4/test/e2e_node/eviction_test.go#L1080-L1086

The image is built as a legacy Schema 1 image and will not work with most runtimes soon:
```console
$ docker pull registry.k8s.io/stress:v1 
v1: Pulling from stress
[DEPRECATION NOTICE] Docker Image Format v1, and Docker Image manifest version 2, schema 1 support will be removed in an upcoming release. Suggest the author of registry.k8s.io/stress:v1 to upgrade the image to the OCI Format, or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

ref: 
- https://github.com/containerd/containerd/pull/6884
- https://github.com/containerd/containerd/pull/9765
- https://github.com/moby/moby/pull/42300

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Replace `registry.k8s.io/stress:v1` (built in 2016) with agnhost, as agnhost now contains the stress functionality
- #123258

#### Which issue(s) this PR fixes:

Fixes #123146

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by kannon92** [comment]
Will undo hold if eviction tests run

**Comment by kannon92** [comment]
/lgtm

/hold cancel
eviction tests passed!

**Comment by dims** [comment]
/approve
/lgtm

724749130d19c225

**Pull request merged**
