### PR TITLE
Added alejandrox1 to test/approvers

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 
/hold 
^ for other approvers

**Review by oomichi — COMMENTED** [review]
Thanks for your continuous contribution @alejandrox1 !

/lgtm

**Pull request merged**
