### PR TITLE
Add spiffxp to OWNERS files in bash-heavy dirs

### PR DESCRIPTION
**Pull request by spiffxp**
I'm comfortable approving changes in hack/, I think I still need
to build up a corpus of reviews in build/ and cluster/ before I'm
comfortable asking for those rights. I'm willing to be voluntold
otherwise if existing approvers feel differently.

Approvers, WDYT?

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/milestone v1.12
SIG Testing Lead, this doesn't change any code, just OWNERS files

**Comment by ixdy** [comment]
/approve

Every new approver must remove at least 100 lines of bash, though.

**Comment by dims** [comment]
@ixdy make that "every week" :)

**Comment by spiffxp** [comment]
/assign @roberthbailey @zmerlynn 
for the /approve

**Pull request merged**
