### PR TITLE
fix test-cmd from file moves

### PR DESCRIPTION
**Pull request by thockin**
File moves broke all sorts of stuff.  Not sure how this got committed.

### CODE REVIEW

**Comment by thockin** [comment]
This is not a complete fix, but self-merging to make progress.

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by bgrant0607** [comment]
Shippable is green now, for the first time all day. What else do you think needs to be fixed?

**Comment by mikedanese** [comment]
Unfortuantely, #11239 was merged way too before it was ready. #11273 had test-cmd fixes and the finishing touches of #11239

**Comment by thockin** [comment]
It was failing on test-cmd for some URL problem.  Weird that it passes now.

**Pull request merged**
