### PR TITLE
fix util_window_test

### PR DESCRIPTION
**Pull request by shubhindia**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — COMMENTED** [review]
It is best to sort the imports

**Comment by shubhindia** [comment]
Closed in favor of https://github.com/kubernetes/kubernetes/pull/117514

**Pull request closed without merging**
