### PR TITLE
Fix kubectl taint's Complete parsing

### LINKED ISSUE #87296: kubectl taint --help example doesn't work
**What happened**:

`kubectl taint --help` says:

```
...
Examples:
   ...
  # Add to node 'foo' a taint with key 'bar' and no value
  kubectl taint nodes foo bar:NoSchedule
```

That doesn't work:

```
$ kubectl taint nodes foo bar:NoSchedule
error: at least one taint update is required
```

It doesn't matter whether there is a node "foo" or not. It doesn't seem to contact the API at all.

**What you expected to happen**:

Examples form the help texts should work.

**Anything else we need to know?**:

Looking at https://github.com/kubernetes/kubernetes/blob/7d15d41eb87f8e6977a8947efe3edf7a75c1d01d/pkg/kubectl/cmd/taint/taint.go#L121-L156, it seems to want either a `=` or `-` in the argument. Indeed, `kubectl taint nodes foo bar=:NoSchedule` does work and does the right thing, i.e. set a taint with key `bar` and no value.

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
$
```

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind bug
/sig cli
/priority backlog

**Which issue(s) this PR fixes**:
Fixes #87296

**Special notes for your reviewer**:
/assign @deads2k

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by zhouya0** [comment]
/lgtm
This is exactly what I want to do. Really thanks for your fix!

**Comment by soltysh** [comment]
/hold
for fixing the test

**Comment by soltysh** [comment]
Fixed the test
/hold cancel

**Pull request merged**
