### PR TITLE
 Add initial brazilian portuguese translations #80650 Open

### PR DESCRIPTION
**Pull request by fgsl**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
For use of Brazilian portuguese speakers.

**Which issue(s) this PR fixes**:
It's not a fix

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by dixudx** [comment]
@fgsl  Please sign your CLA. Thanks for your work.

/unassign @dixudx 
Since I don't understand Portuguese.

**Comment by fgsl** [comment]
Hi, @dixudx . I signed CLA.

**Comment by sftim** [comment]
(I don't speak any dialect of Portuguese)

**Comment by sftim** [comment]
The user-facing change is Portuguese localised help with a Brazilian flavor.

**Comment by fgsl** [comment]
I create another PR: https://github.com/kubernetes/kubernetes/pull/86478

**Pull request closed without merging**
