### PR TITLE
[prometheus addon] Use statefulset for alertmanager

### PR DESCRIPTION
**Pull request by serathius**
This PR changes alertmanager deployment to statefulset
```release-note
NONE
```
/cc @brancz @kawych

### CODE REVIEW

**Comment by brancz** [comment]
I wonder why now the sudden change of mind. In the initial PR I was convinced that the deployment is good enough as it's just for some simple e2e testing purposes. If our intend has not changed I don't think we should be making any changes to the setup if it works.

**Comment by brancz** [comment]
I would very much like us to discuss my comment from above. Changes like these will make it look more like users are actually supposed to use this. I do not want us to convey this. I would only like to accept changes like this if it's actually a problem in the e2e tests.

**Comment by brancz** [comment]
cc @piosz

**Comment by kawych** [comment]
/hold
Sorry, I didn't notice your comment. Putting it on hold until it's answered. The tests are also failing consistently, it may be worth taking a look.

**Pull request closed without merging**
