### PR TITLE
Add tests for equivalence cache

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**:
Add more tests for equivalence cache in scheduler, including `InvalidateCachedPredicateItem` and `InvalidateCachedPredicateItemForPodAdd`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE

### CODE REVIEW

**Comment by resouer** [comment]
/assign 

Thanks, I will review this one.

**Comment by huangjiuyuan** [comment]
ping @resouer

**Comment by huangjiuyuan** [comment]
ping @resouer

**Comment by resouer** [comment]
Thanks, will review soon!

**Comment by bsalamat** [comment]
ping @resouer for review. Thanks!

**Pull request closed without merging**
