### PR TITLE
Allow components to use protobufs while talking to apiserver.

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by smarterclayton** [comment]
> We may want to change comment to say that you can pass "application/vnd.kubernetes.protobuf" as experimental feature. WDYT?

Comment is fine.

> Hmm - I wanted to make this flag work like "preferred contentType". The only a single value makes sense. How do you want this to work?

If I want to rolling update a cluster to support protobuf, do all my components need to upgrade first?  What if there's a bug in protobuf and I don't want to continue using it?  Should we allow a user to say "I *don't* want a content type" (which is what Accept allows), or just say "prefer content type" and be ok if it silently falls over to json?

**Comment by wojtek-t** [comment]
>>
Hmm - I wanted to make this flag work like "preferred contentType". The only a single value makes sense. How do you want this to work?

>
If I want to rolling update a cluster to support protobuf, do all my components need to upgrade first? What if there's a bug in protobuf and I don't want to continue using it? Should we allow a user to say "I don't want a content type" (which is what Accept allows), or just say "prefer content type" and be ok if it silently falls over to json?

So my thinking about it is that we are not changing the flag in any component until apiserver is upgraded, and then we can change it (either in all components on one by one). If there is a bug in protobuf, we are changing the flag back to application/json in all components and they start talking back in json (and stop using protobuf).

I think that "preferred content type" is something completely different that "not allow these content types". Thus I think we shouldn't mix these two things in a single flags. If you think the latter is also necessary, I can add another flags, but I think that mixing those two things is not the best option.

What do you think?

**Comment by smarterclayton** [comment]
Ok, I'm fine with that for now.

**Comment by wojtek-t** [comment]
Thanks - so I will apply other comments tomorrow.

**Comment by wojtek-t** [comment]
Comment applied.
@smarterclayton - PTAL

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
