### PR TITLE
Automated cherry pick of #75234: fix flexvol stuck issue due to corrupted mnt point

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #75234 on release-1.12.

#75234: fix flexvol stuck issue due to corrupted mnt point

### CODE REVIEW

**Comment by rata** [comment]
LGTM, seems the patch is a straight forward backport :)

**Review by rata — APPROVED** [review]

**Review by chakri-nelluri — APPROVED** [review]
/LGTM

**Pull request merged**
