### PR TITLE
correct code comment

### PR DESCRIPTION
**Pull request by zouyee**
fix spelling error: CloudControllerMangerServer

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by cblecker** [comment]
```
W0622 11:05:40.650] Some packages passed golint but are not listed in hack/.linted_packages.
W0622 11:05:40.650] Please add them in alphabetical order:
W0622 11:05:40.650] 
W0622 11:05:40.650]   echo cmd/cloud-controller-manager/app/options >> hack/.linted_packages
W0622 11:05:40.651]   LC_ALL=C sort -o hack/.linted_packages hack/.linted_packages
```
/ok-to-test

**Comment by zouyee** [comment]
@cblecker  PTAL

**Comment by cblecker** [comment]
@zouyee There are failing tests. Please review test results and my last comment.

**Pull request closed without merging**
