### PR TITLE
update pause image references to use 3.6

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig release
/priority important-soon

#### What this PR does / why we need it:

The pause:3.6 image has been published.

Also updates older / incorrect references.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Support for Windows Server 2022 was added to the k8s.gcr.io/pause:3.6 image.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve
for kubeadm / test

> Does this PR introduce a user-facing change?

we have to be clearer in terms of what updates are included in this pause image bump.
we should include a short summary / changelog for pause 3.6 in the release note field.

/retitle update pause image references to use 3.6
/triage accepted

**Comment by claudiubelu** [comment]
> 
> 
> /approve
> for kubeadm / test
> 
> > Does this PR introduce a user-facing change?
> 
> we have to be clearer in terms of what updates are included in this pause image bump.
> we should include a short summary / changelog for pause 3.6 in the release note field.
> 
> /retitle update pause image references to use 3.6
> /triage accepted

That's a good point. We should also update ``build/pause/CHANGELOG.md``. The only notable change since 3.5 is that Windows Server 2022 support was added in 3.6.

**Comment by endocrimes** [comment]
@claudiubelu kubelet serial tests are known-flaky. Looks like no new or unexpected failures happened during the last run.

**Comment by endocrimes** [comment]
/lgtm
(kubelet changes and node-kubelet-serial state)

**Comment by endocrimes** [comment]
@claudiubelu https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial - there hasn't been a clean run of that suite in as long as test grid has history - no need to keep re-testing.

**Review by mrunalp — APPROVED** [review]

**Comment by dims** [comment]
/assign @eddiezane 

(for sig-cli approval)

**Pull request merged**
