### PR TITLE
AWS: Put Master Data on Persistent Disk

### PR DESCRIPTION
**Pull request by iterion**
Updating the AWS kube-up scripts to bring them more in line with how GCE handles data on the master. I was able to bring up a cluster and it seems as if everything started up fine.

@justinsb PTAL

### CODE REVIEW

**Comment by saad-ali** [comment]
@thockin for 1.0 triage

**Comment by thockin** [comment]
We've said that we're willing to take platform changes to bring them up to par, but every change has risk right now.  I'm inclined to shelve this until after 1.0, but I'll let Justin decide, since this is purely AWS

@justinsb

**Comment by justinsb** [comment]
This is really important actually, because otherwise we lose everything if the master dies.  I should have spotted that earlier - thanks @iterion for spotting it.

I would like to see if I can make this work with our existing format-disks.sh script, if that is OK @iterion

**Comment by iterion** [comment]
Absolutely, format-disks.sh is probably a better place for it. Let me know if you need any help.

**Comment by justinsb** [comment]
Actually, I've looked in more detail and I think I like the way this is done.  The idea here (I believe) is that the data survives, although the containers themselves may not.  Also, I don't want to break-sync with GCE if we can avoid it.

I think we should mount this as sdb (and bump the ephemeral mounts up instead).  And I would rather that we created the EBS disk ourselves (or reused an existing one).  But both of these can be fixed later (immediately after this goes in, unless you want to do it).

This does need a rebase though (I think just a matter of surrounding the minion's BLOCK_DEVICE_MAPPINGS with square brackets).

I'm also unsure about having this be under /mnt, when /mnt is sometimes an ephemeral disk.

I'm trying this out on a copy of your branch:

Rebase: https://github.com/justinsb/kubernetes/commit/17ff5b37783c66862ff26964dc7dbddcd3542eab

Mount persistent disk as sdb: https://github.com/GoogleCloudPlatform/kubernetes/commit/f5cfaa56d12dbfae6540d641eefaa08f912f788a

Working on EBS creation & thinking more about the /mnt thing - you know my email if you want to collaborate!

**Comment by iterion** [comment]
I like sdb, that makes more sense esp. on the master.

The problem with creating the EBS separately from the instance was that we couldn't really guarantee that it'd be present at the time the init scripts ran. As far as I could find we can't mount an already existing EBS to a new instance with run-instances (you have to separately attach that EBS after provision). But, It's totally possible I just missed it in the AWS docs.

There is a way to provision a new EBS on a new instance as a snapshot of another EBS, so that seems to be the best way to support provisioning a new master in a situation where the master was lost.

I chose a subdir of /mnt since it seems like a pretty standard place to mount disks, but it does seem strange as it is a subdir of a potentially different mount.  Perhaps we could mount sdb at /data, /master_data or something along those lines. Everything that uses it goes through symlinks, so the change is pretty trivial in setup-master-pd.sh.

**Comment by justinsb** [comment]
Yes, not being able to attach persistent disks does seem like a pretty big omission.  I think we can work around the race condition by waiting in setup-master-pd.sh.  I seem to remember doing this in the past, so I don't think you've missed anything.  

I'm working through these issues and working towards trying them out for real.  I'm hoping that the race condition is mostly theoretical (i.e. that we don't 100% have to fix it right now), and also looking at mounting ephemeral drives under /mnt/ephemeral: https://github.com/justinsb/kubernetes/tree/ebs-for-master-data

**Comment by iterion** [comment]
Nice, your branch makes the master setup much cleaner, concatenating the block device mappings felt really hacky. Hopefully the disk gets attached pretty quickly, it's hard to tell how that sequence of events happens on AWS.

**Comment by thockin** [comment]
If @justinsb thinks we need this for AWS 1.0, I'll allow it.  Justin, LGZTM
it when you're happy and ping me.

**Comment by justinsb** [comment]
@iterion and I collaborated on this in #10403.  I believe that one replaces this one.

**Comment by iterion** [comment]
Yep, closing this one in favor of #10403

**Pull request closed without merging**
