### PR TITLE
save the CA_KEY

### PR DESCRIPTION
**Pull request by mikedanese**
This is a fix for upgrade testing.

### CODE REVIEW

**Comment by krousey** [comment]
looks good to me. @saad-ali ?

**Comment by saad-ali** [comment]
+@mwielgus the new 1.5 branch manager

**Comment by mwielgus** [comment]
@k8s-bot kops aws e2e test this

**Comment by mwielgus** [comment]
@k8s-bot cvm gke e2e test this

**Comment by mikedanese** [comment]
@k8s-bot verification test this

**Comment by krousey** [comment]
@k8s-bot verification test this

**Comment by mwielgus** [comment]
@k8s-bot verification test this

**Comment by krousey** [comment]
@k8s-bot verification test this

**Comment by krousey** [comment]
@mwielgus can we get a manual merge on this if it jenkins keeps failing? This is needed for upgrade tests to work for 1.6.

**Comment by mikedanese** [comment]
I'll watch the build. This is needed to make progress on upgrade testing.

**Pull request merged**
