### PR TITLE
Validate `LabelSelector` for `TopologySpreadConstraints`

### PR DESCRIPTION
**Pull request by chendave**
/kind cleanup

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
address the comments here: https://github.com/kubernetes/kubernetes/pull/111441/files#r933399816

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR, I think this is already in progress in https://github.com/kubernetes/kubernetes/pull/111802

**Comment by chendave** [comment]
/close 

in favor of https://github.com/kubernetes/kubernetes/pull/111802

**Pull request closed without merging**
