### PR TITLE
Split NodeDiskPressure into NodeInodePressure and NodeDiskPressure

### PR DESCRIPTION
**Pull request by dashpole**
Added NodeInodePressure as a NodeConditionType.  SignalImageFsInodesFree and SignalNodeFsInodesFree signal this pressure.  Also added simple pieces to the scheduler predicates so that it takes InodePressure into account.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33218)

### CODE REVIEW

**Comment by dashpole** [comment]
fixed gofmt

**Comment by mtaufen** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

*[pkg/kubelet/kubelet_node_status.go, line 725 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHfwJw2XpfO2B7hF3J:-KSHfwJw2XpfO2B7hF3K:b-9hph8n) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/kubelet_node_status.go#L725)):*
> ```Go
> 
> // setNodeInodePressureCondition for the node.
> // TODO: this needs to move somewhere centralized...
> ```

nit: use `TODO(username):` syntax for TODOs, e.g. `TODO(mtaufen): Make it sing beautiful melodies.`

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 919 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHpClX2gKB8vJ6yxDk:-KSHpClX2gKB8vJ6yxDl:b-by3kgn) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L919)):*
> ```Go
> 
> func TestDiskPressureNodeFsInodes(t *testing.T) {
> 	// TODO: we need to know inodes used when cadvisor supports per container stats
> ```

You might want to assign this and related TODOs to yourself since you're owning this.

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 946 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHpMKUqpbYnbsxcTUM:-KSHpMKUqpbYnbsxcTUN:b-p3xdlb) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L946)):*
> ```Go
> 		return result
> 	}
> 	// TODO: pass inodes used in future when supported by cadvisor.
> ```

ditto this one wrt owning TODOs

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1016 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrlP0L1aLxGOZ5cbE:-KSHrlP1W6vmlh5dhpZx:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1016)):*
> ```Go
> 	manager.synchronize(diskInfoProvider, activePodsFunc)
> 
> 	// we should not have disk pressure
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1018 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHptBv2QXvFWgaryVr:-KSHptBv2QXvFWgaryVs:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1018)):*
> ```Go
> 	// we should not have disk pressure
> 	if manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should not report disk pressure")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1031 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrk_nkc_4ZLisGd0S:-KSHrk_nkc_4ZLisGd0T:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1031)):*
> ```Go
> 	manager.synchronize(diskInfoProvider, activePodsFunc)
> 
> 	// we should have disk pressure
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1033 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHpqunWNOz-0UNSUlA:-KSHpqunWNOz-0UNSUlB:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1033)):*
> ```Go
> 	// we should have disk pressure
> 	if !manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should report disk pressure since soft threshold was met")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1046 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrjKspAUUYdlfBDoE:-KSHrjKspAUUYdlfBDoF:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1046)):*
> ```Go
> 	manager.synchronize(diskInfoProvider, activePodsFunc)
> 
> 	// we should have disk pressure
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1048 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHpvOsIuy4PGoScifE:-KSHpvOsIuy4PGoScifF:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1048)):*
> ```Go
> 	// we should have disk pressure
> 	if !manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should report disk pressure since soft threshold was met")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1073 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHreFiYW2wraAFlUro:-KSHreFiYW2wraAFlUrp:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1073)):*
> ```Go
> 	// we should not have disk pressure
> 	if manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should not report disk pressure")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1083 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrfykyEATV2d6uc3A:-KSHrfykyEATV2d6uc3B:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1083)):*
> ```Go
> 	// we should have disk pressure
> 	if !manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should report disk pressure")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1106 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrnrcKpM4qlhZC55X:-KSHrnrcKpM4qlhZC55Y:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1106)):*
> ```Go
> 	manager.synchronize(diskInfoProvider, activePodsFunc)
> 
> 	// we should have disk pressure (because transition period not yet met)
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1108 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHroWlGnB_0XFNWMPj:-KSHroWlGnB_0XFNWMPk:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1108)):*
> ```Go
> 	// we should have disk pressure (because transition period not yet met)
> 	if !manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should report disk pressure")
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1127 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrpmcDGvPvDGtFVkU:-KSHrpmcDGvPvDGtFVkV:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1127)):*
> ```Go
> 	manager.synchronize(diskInfoProvider, activePodsFunc)
> 
> 	// we should not have disk pressure (because transition period met)
> ```

/s/disk/inode

---

*[pkg/kubelet/eviction/eviction_manager_test.go, line 1129 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHrpJhQeV-f5UxPtXz:-KSHrpJhQeV-f5UxPtY-:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/pkg/kubelet/eviction/eviction_manager_test.go#L1129)):*
> ```Go
> 	// we should not have disk pressure (because transition period met)
> 	if manager.IsUnderInodePressure() {
> 		t.Errorf("Manager should not report disk pressure")
> ```

/s/disk/inode

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates.go, line 1172 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHj8vXUORE4Qxb4CWc:-KSHj8vXUORE4Qxb4CWd:be2wmnn) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1172)):*
> ```Go
> }
> 
> // CheckNodeDiskPressurePredicate checks if a pod can be scheduled on a node
> ```

/s/CheckNodeDiskPressurePredicate/CheckNodeInodePressurePredicate

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates.go, line 1173 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHkHgeIiG7wycq4rUB:-KSHkHgeIiG7wycq4rUC:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1173)):*
> ```Go
> 
> // CheckNodeDiskPressurePredicate checks if a pod can be scheduled on a node
> // reporting disk pressure condition.
> ```

/s/disk/inode

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3050 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHszmwTOUwWFyFLneQ:-KSHszmwTOUwWFyFLneR:b-v1ieze) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3050)):*
> ```Go
> 			Conditions: []api.NodeCondition{
> 				{
> 					Type:   "Ready",
> ```

Use `api.NodeReady` instead of a raw string.

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3051 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHtJdUnZcYqRM3yNGx:-KSHtJdV_KgpqR1UeonU:b32umni) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3051)):*
> ```Go
> 				{
> 					Type:   "Ready",
> 					Status: "True",
> ```

Use `api.ConditionTrue` instead of a raw string.

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3062 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHsmLxadvfxZBvA8QE:-KSHsmLxadvfxZBvA8QF:b-exwtt9) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3062)):*
> ```Go
> 			Conditions: []api.NodeCondition{
> 				{
> 					Type:   "InodePressure",
> ```

Use `api.NodeInodePressure` instead of a raw string.

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3063 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHstKE3KdRm2JUurD4:-KSHstKE3KdRm2JUurD5:b32umni) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3063)):*
> ```Go
> 				{
> 					Type:   "InodePressure",
> 					Status: "True",
> ```

Use `api.ConditionTrue` instead of a raw string.

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3079 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHu-s2ER7Ul4_ssWsW:-KSHu-s2ER7Ul4_ssWsX:byo82kd) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3079)):*
> ```Go
> 			nodeInfo: makeEmptyNodeInfo(noPressureNode),
> 			fits:     true,
> 			name:     "pod schedulable on node without pressure condition on",
> ```

Add something to the name to indicate that this is for inode pressure.

---

*[plugin/pkg/scheduler/algorithm/predicates/predicates_test.go, line 3085 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHu5M58CCISrvhPKCj:-KSHu5M58CCISrvhPKCk:byo82kd) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L3085)):*
> ```Go
> 			nodeInfo: makeEmptyNodeInfo(pressureNode),
> 			fits:     false,
> 			name:     "pod not schedulable on node with pressure condition on",
> ```

Add something to the name to indicate that this is for inode pressure.

---

*[plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go, line 155 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-KSHkjsHHYvrsvrMCC27:-KSHkjsHHYvrsvrMCC28:b-x09map) ([raw file](https://github.com/kubernetes/kubernetes/blob/7420f462fb62bfbe08f1ae9cf8fbcc1fd5f122a3/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L155)):*
> ```Go
> 		factory.RegisterFitPredicate("CheckNodeDiskPressure", predicates.CheckNodeDiskPressurePredicate),
> 
> 		// Fit is determined by node disk pressure condition.
> ```

/s/disk/inode

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218)*

**Comment by dashpole** [comment]
Fixed

**Comment by mtaufen** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33218#-:-KSgXSvIKw1j4jTBdVii:bnfp4nl)*

**Comment by dashpole** [comment]
@k8s-bot gke e2e test this

**Comment by dashpole** [comment]
One of the builds was failing, so I fetched upstream and rebased, hoping that that will fix it...

**Comment by mtaufen** [comment]
@k8s-bot gke test this

**Comment by mtaufen** [comment]
@k8s-bot gci gke test this

**Comment by dashpole** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot gke e2e test this

**Comment by dashpole** [comment]
@k8s-bot gke e2e test this

**Comment by mtaufen** [comment]
@k8s-bot unit test this issue #IGNORE

**Comment by dashpole** [comment]
@k8s-bot unit test this

**Comment by mtaufen** [comment]
I think this is the fix for the `TestNamespaceController` unit test flake: https://github.com/kubernetes/kubernetes/pull/33866

**Comment by dashpole** [comment]
issue: https://github.com/kubernetes/kubernetes/issues/33382

**Comment by dashpole** [comment]
@k8s-bot gci gce e2e test this

**Comment by dashpole** [comment]
@k8s-bot gce e2e test this

**Comment by dashpole** [comment]
@k8s-bot kubemark gce e2e test this

**Comment by dashpole** [comment]
@k8s-bot kube gce e2e test this

**Comment by dashpole** [comment]
@k8s-bot test this issue #IGNORE

**Pull request merged**
