### PR TITLE
azure: stop using deprecated io/ioutil

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This replaces deprecated ioutil variables and functions as follows:

* ioutil.NopCloser -> io.NopCloser
* ioutil.ReadAll -> io.ReadAll
* ioutil.ReadFile -> os.ReadFile

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
https://github.com/kubernetes/kubernetes/pull/122857 it's being deleted

**Comment by skitt** [comment]
> #122857 it's being deleted

That’s great, thanks for the heads-up @nilo19!

**Pull request closed without merging**
