### PR TITLE
Optional maximum etcd page size on every list requests

### LINKED ISSUE #108258: APIServer: Impose optional maximum limit on etcd range queries
### What would you like to be added?

Modify [apiserver/blob/master/pkg/storage/etcd3/store.go list](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/etcd3/store.go#L565-L576) to apply a maximum limit to every etcd range request and issue multiple range requests if necessary to satisfy the original list. Using the ResourceVersion that comes back from the first range request from etcd (or the one user provided) on later requests to ensure a consistent snapshot of resource collections. Here is the drafted [PR](https://github.com/chaochn47/kubernetes/pull/2) for the changes. 

The maximum limit will be a kube-apiserver cmd option. Default value is `0` which means unlimited (It's the current behavior). We will experiment internally with `500` limit in the design first phase like [client-go/tools/pager: const defaultPageSize = 500](https://github.com/kubernetes/client-go/blob/master/tools/pager/pager.go#L31)

The maximum limit will be applied to each resource type. 

### Why is this needed?

The main purpose is to protect etcd from out of memory and prevent its cascading APIServer failures like re-creating gRPC connections to etcd, rebuild all caches and resume internal reconciler which can be expensive. 

[APIListChunking](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks) should be in effect in most APIServer set up, `client-go/tools/pager` and `client-go/informers` are good libraries to use and they follows the pagination rule of thumb to reduce server load. However, there are still some native clients calling server without any limit to get a full list of resource. This created a lot of memory pressure on etcd. 

Carveat
- Setting the maximum limit too low will increase the total round-trip time between APIServer and etcd to breach the default 1 minute request time. This will probably cause APIServer cancelled the client requests prematurely. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ > `--request-timeout duration     Default: 1m0s`
  - We will explore fifo queue to process the list requests, one goroutine to split the request into multiple pages and get the response from etcd. Another goroutine to consume the etcd response and deserialize the response into k8s objects. 
  - Please drop any concerns and comments on this, thanks!

### PR DESCRIPTION
**Pull request by chaochn47**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Part of https://github.com/kubernetes/enhancements/pull/3252

#### Which issue(s) this PR fixes:

Fixes #108258

#### Does this PR introduce a user-facing change?
No

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
https://github.com/kubernetes/enhancements/pull/3252

### CODE REVIEW

**Comment by liggitt** [comment]
before implementation review starts, the proposal should be accepted - https://github.com/kubernetes/enhancements/pull/3252

**Comment by chaochn47** [comment]
Thanks @liggitt I will mark this as `Draft` for now.

**Pull request closed without merging**
