### PR TITLE
[WIP] vendor: update aws-sdk-go to v1.28.2 for release-1.17

### PR DESCRIPTION
**Pull request by gyuho**
```
cd ${HOME}/go/src/k8s.io/kubernetes
./hack/pin-dependency.sh github.com/aws/aws-sdk-go v1.28.2
./hack/update-vendor.sh
sudo ./build/run.sh make test WHAT="k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/aws k8s.io/kubernetes/pkg/credentialprovider/aws k8s.io/kubernetes/pkg/volume/awsebs"
<<COMMENT
ok      k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/aws      5.031s
ok      k8s.io/kubernetes/pkg/credentialprovider/aws    0.022s
ok      k8s.io/kubernetes/pkg/volume/awsebs     0.011s
COMMENT
```

ref. https://github.com/kubernetes/kubernetes/pull/87253

### CODE REVIEW

**Comment by gyuho** [comment]
/sig cloud-provider
@M00nF1sh @micahhausler

**Comment by liggitt** [comment]
we generally only update dependencies on release branches to address bugs; the PR to master referenced additional features this bump enabled, but not bug fixes

**Comment by liggitt** [comment]
see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks for guidance on the types of changes we expect to be picked to release branches

**Comment by gyuho** [comment]
@liggitt @dims Understood. Thanks for the links. Can we keep this PR open for reference (we may keep this as an internal patch)?

/do-not-merge

**Comment by tpepper** [comment]
/kind feature
/priority important-soon
from parent PR.  The PR and commits are still present in GitHub after closing.
/close

**Pull request closed without merging**
