### PR TITLE
Fix build break

### LINKED ISSUE #36454: kubernetes-cross-build: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-cross-build/1549/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by dims**
Problem introduced in #31996

Fixes #36454

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36455)

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot build this

**Comment by dims** [comment]
@k8s-bot build this

**Comment by dims** [comment]
@k8s-bot unit test this

**Comment by mtaufen** [comment]
LGTM

**Comment by mtaufen** [comment]
Elevated to p0 because the cross-build is broken until this goes in.

**Pull request merged**
