### PR TITLE
Fix test failure due to days-in-month check. Issue #17998.

### PR DESCRIPTION
**Pull request by fabioy**

### CODE REVIEW

**Comment by fabioy** [comment]
Fixes #17998. 

Removes the test case for the month check. Will have to be manually merged due to build break.

Thanks.

**Comment by karlkfi** [comment]
LGTM to fix the build. The author should probably find a better way to test months that isn't flakey.

**Comment by karlkfi** [comment]
The Mesosphere Smoke Test failure was an infra issue. Slow internet it seems.

**Comment by karlkfi** [comment]
Unit tests passed on Mesosphere CI (manual runs):
- pull/18000 - https://teamcity.mesosphere.io/viewLog.html?buildId=83130&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_2UnitTests&guest=1
- pull/18000/merge - https://teamcity.mesosphere.io/viewLog.html?buildId=83131&tab=buildResultsDiv&buildTypeId=Oss_KubernetesMesos_2UnitTests&guest=1

**Comment by karlkfi** [comment]
@fabioy please make a cherry-pick PR.

**Comment by karlkfi** [comment]
Looks like @mvdan was the original author of those unit tests.

**Comment by ixdy** [comment]
Cherry-pick to `release-1.1` in https://github.com/kubernetes/kubernetes/pull/18005.

**Comment by ixdy** [comment]
@mvdan just refactored some code. original author is @hurf in #12635.

**Pull request merged**
