### PR TITLE
gce: configure: validate SA has storage scope

### PR DESCRIPTION
**Pull request by javier-b-perez**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Change configure.sh script for GCE to check if System Account has storage scope associated.

**Special notes for your reviewer**:
When the SA doesn't have 'Storage' scope associated and we use the token in the curl headers, we receive a 403.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by zmerlynn** [comment]
@justinsb, @javier-b-perez is looking to get this into 1.14, can you help?

**Comment by justinsb** [comment]
Fixes a regression introduced in 1.14 in 708d7df56198ced35092f801975cf3ce20f1f09d, so marking fix for this milestone

/milestone 1.14

**Pull request merged**
