### PR TITLE
Removed deprecated label kubernetes.io/cluster-service.Bug fix 72757

### PR DESCRIPTION
**Pull request by ramnar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes deprecated labels in prometheus add-on

**Which issue(s) this PR fixes**:

Remove deprecated label kubernetes.io/cluster-service in yaml files of prometheus add-on. Ref #72757

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@ramnar please assign these to @MrHohn 
also i don't think there is a need for multiple PRs...

/assign @MrHohn 
/unassign

**Comment by ramnar** [comment]
/assign @neolit123

> @ramnar please assign these to @MrHohn
> also i don't think there is a need for multiple PRs...
> 
> /assign @MrHohn
> /unassign

sorry about that @neolit123. I will take care from next time

**Comment by MrHohn** [comment]
@ramnar We will have to address https://github.com/kubernetes/kubernetes/issues/72757#issuecomment-504725581 before this.

And as @neolit123 mentioned please combine these PRs since they are essentially doing the same cleanup.

**Pull request closed without merging**
