### PR TITLE
fix some typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix some typo

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Review by xiangpengzhao — APPROVED** [review]

**Comment by timchenxiaoyu** [comment]
cc @Random-Liu, @saad-ali  please give me approve

**Comment by timchenxiaoyu** [comment]
cc @Random-Liu, @saad-ali

**Comment by cblecker** [comment]
ping @timchenxiaoyu for rebase.

**Comment by timchenxiaoyu** [comment]
I have sign the CLA, not set email

**Comment by cblecker** [comment]
@timchenxiaoyu It's because of how you pulled things into your branch. You need to rebase off of master and squash your commit instead of trying to merge master into your branch.

**Comment by timchenxiaoyu** [comment]
sorry .it's my error.I will close this commit,and recommit again！

**Pull request closed without merging**
