### PR TITLE
Improve the performance of map usage

### PR DESCRIPTION
**Pull request by sourcelliu**
#### What type of PR is this?
/kind cleanup
/sig apps

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm

These are usually significative improvements.

@soltysh can we add it to the milestone?

**Comment by alculquicondor** [comment]
actually, this can be refactored

/lgtm cancel

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
cleanups like this in non-test code should probably wait for 1.28

**Comment by alculquicondor** [comment]
I know, but this is a non-functional change that could improve performance significantly. I think it's good ROI.

**Comment by soltysh** [comment]
We've talked about it for a while with Aldo, and we both agreed that the change is small enough, and yet the benefit on big clusters from pre-allocation will be significant, given this method is called on almost every invocation of the `syncHandler`.

**Pull request merged**
