### PR TITLE
Fix link 404

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix linkcheck 404.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chymy** [comment]
/assign @smarterclayton
Thanks

**Comment by dims** [comment]
/assign @liggitt @smarterclayton 

NOTE for Jordan/Clayton: just a URL change, so quick review

**Pull request merged**
