### PR TITLE
Update ubuntu.md

### PR DESCRIPTION
**Pull request by rafael81**
Fix typo

### CODE REVIEW

**Comment by rafael81** [comment]
I signed it!

**Comment by wojtek-t** [comment]
LGTM - thanks for your change.

@k8s-bot ok to test

**Comment by dalanlan** [comment]
@wojtek-t This patch is *not* correct

**Comment by dalanlan** [comment]
We don't *install* `scp` binary at all, we just *use* `scp` command.

**Comment by wojtek-t** [comment]
@dalanlan - sure; I misread the patch

@rafael81 - closing this PR - see above for the explanation.

**Comment by rafael81** [comment]
@wojtek-t I think some "verb" need to be added to this sentence. It's unnatural the people try to understand it.

**Comment by dalanlan** [comment]
@rafael81 I'm comfortable with "The scripts automatically copy binaries and config files to all the machines via `scp` command" if you insist.

**Comment by rafael81** [comment]
@dalanlan It's more comfortable.

**Pull request closed without merging**
