### PR TITLE
[release-1.27] Bump konnectivity-client to 0.1.2

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes memory leaks (affecting proxy-server and proxy-agent).

#### Which issue(s) this PR fixes:

The desired fix: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/467

#### Special notes for your reviewer:

Master branch took this fix in https://github.com/kubernetes/kubernetes/pull/116348.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by jkh52** [comment]
Rebasing.

**Comment by jkh52** [comment]
/cc kubernetes/release-managers

(had LGTM from @cheftako, lost only on rebase).

**Comment by liggitt** [comment]
/approve
based on area review

**Comment by xmudrii** [comment]
@jkh52 @cheftako Is this needed only for 1.27 and 1.26 (#117274) or do we need cherry-picks for earlier release branches as well?

**Comment by jkh52** [comment]
> @jkh52 @cheftako Is this needed only for 1.27 and 1.26 (#117274) or do we need cherry-picks for earlier release branches as well?

See https://github.com/kubernetes-sigs/apiserver-network-proxy#releases

In kubernetes 1.27 and later we use konnectivity-client 0.1.*, and 0.1.2 contains the memory leak fix we want here.

Prior to 1.26 where we use 0.0.*, 0.0.37 contains the same memory leak fix. PRs: https://github.com/kubernetes/kubernetes/pull/117274, https://github.com/kubernetes/kubernetes/pull/117315 and https://github.com/kubernetes/kubernetes/pull/117316.

**Comment by xmudrii** [comment]
@dims @jkh52 Should we have a release note for this change? It kinda feels like we should have it because we're updating a component.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
