### PR TITLE
openstack: Autodetect LBaaS v1 vs v2

### PR DESCRIPTION
**Pull request by anguslees**
``` release-note
* openstack: autodetect LBaaS v1/v2 by querying for available extensions.  For most installs, this effectively changes the default from v1 to v2.  Existing installs can add "lb-version = v1" to the provider config file to continue to use v1.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29726)

### CODE REVIEW

**Comment by anguslees** [comment]
@googlebot: I am also angus.lees@rackspace.com, and that address is in the corp-CLA Rackspace contributors list.

**Comment by anguslees** [comment]
@googlebot: We've done this dance so many times I give up.  I signed it! as an individual contributor too, just so you are able to see one of my other email addresses without having to do anything clever.

**Comment by mikedanese** [comment]
@kubernetes/sig-openstack can someone review this?

**Comment by xsgordon** [comment]
@anguslees I think in the commit message you meant "lb-version = v1" not v2, otherwise the approach makes sense to me given the (too my knowledge) low adoption of v1 (largely because of the issues that resulted in v2 and ultimately Octavia).

**Comment by dims** [comment]
@mikedanese @xsgordon @anguslees LGTM 👍

**Comment by flaper87** [comment]
LGTM too :cake:

**Comment by anguslees** [comment]
@xsgordon: Oops, fixed the commit message.  Thanks :)

**Pull request merged**
