### PR TITLE
build: use the first ip address in 'ip address' list for ALLOW_HOST

### PR DESCRIPTION
**Pull request by booxter**
A build node may have multiple IP addresses matching the grep rules, in
which case the current code passes a multi-line value into
run_build_command_ex which makes it try to run a container with the name
equal to the second ip address from the list, which obviously fails.

For this patch, we just pass the first entry from the list.

I've hit it on a machine that had 4 different IP addresses that matched the filter.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by soggiest** [comment]
Hello! Code Freeze is just about on us. We'll be entering into Freeze tomorrow, May 31st. Is this still planned to land in 1.15?

**Comment by xmudrii** [comment]
@booxter Hello! I'm bug triage lead for the 1.16 release cycle and considering this PR has not been updated for a long time, I'd like to check what's the status of this PR. The code freeze is starting 29th August (about 2.5 weeks from now) and while there is plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.16, is it still planned for this release?

**Comment by booxter** [comment]
@xmudrii I am waiting for anyone to pay attention and merge it if it makes sense. I personally lost hope this ever happens since it's just bumped to the next milestone every release cycle. I am not too invested in getting this in, but the fix helped in my own development when I was working on other kubernetes patches. I hoped others could also make use of it.

**Comment by xmudrii** [comment]
@booxter Thank you for the update! Sadly, I don't think it's possible to get this PR merged for 1.16 considering the code freeze is starting in just a few hours.

**Comment by xmudrii** [comment]
As this issue has no activity for a long time, I'm going to remove it from the milestone.

/milestone clear

cc @justaugustus as it might be related to RelEng

**Comment by BenTheElder** [comment]
not very familiar with the rsync stuff but this seems reasonable. defering to @cblecker

**Comment by jtslear** [comment]
Hello @jbeda, @cblecker, and @zmerlynn 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this PR still intended for milestone 1.18? I see we awaiting reviews currently.

**Pull request closed without merging**
