### PR TITLE
Fix DNS integration

### LINKED ISSUE #6124: Kubelet should keep the original PodStatus.Host when posting the status
I am seeing pod status update failures due to empty `Host` field. This prevents the pod status from being updated in some cases. Kubelet should always keep the original host.

### LINKED ISSUE #6134: DNS integration instructions are broken due to missing Docker images
When following the current instructions
```
Mar 28 12:08:32 node-01 docker[1122]: No such image: gcr.io/google-containers/kube2sky:1.1
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="-job image_inspect(gcr.io/google-containers/kube2sky:1.1) = ERR (1)"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google-containers/kube2sky:1.1"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="HTTP Error: statusCode=404 No such image: gcr.io/google-containers/kube2sky:1.1"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="GET /images/gcr.io/google-containers/skydns:2015-03-11-001/json"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="+job image_inspect(gcr.io/google-containers/skydns:2015-03-11-001)"
Mar 28 12:08:32 node-01 docker[1122]: No such image: gcr.io/google-containers/skydns:2015-03-11-001
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="-job image_inspect(gcr.io/google-containers/skydns:2015-03-11-001) = ERR (1)"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google-containers/skydns:2015-03-11-001"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="HTTP Error: statusCode=404 No such image: gcr.io/google-containers/skydns:2015-03-11-001"
```

### PR DESCRIPTION
**Pull request by pires**
Fixes #6134

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
:+1:

**Comment by AntonioMeireles** [comment]
hum... shouldn't we just do a **sed "s,gcr.io/google-containers,kubernetes,g"** across the whole tree for consistency ? (as this looks like a more general issue ....)

**Comment by pires** [comment]
@thockin PR commit log fixed now.

**Comment by pires** [comment]
I'm going to leave this open, even though it's not yet clear what happened in #6134

**Comment by thockin** [comment]
For sanity of my queue, I am going to close this - if more issues pop up, please scream.

**Pull request closed without merging**
