### PR TITLE
Promote ConfigMap patch test to Conformance

### PR DESCRIPTION
**Pull request by devaips**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Promotes the following e2e test to Conformance: `test/e2e/common/configmap.go: "should patch ConfigMap successfully"`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

Part of umbrella issue https://github.com/kubernetes/kubernetes/issues/80997

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/area conformance
/area test

@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
/hold
this test was just merged, we need some time to confirm whether this is non-flaky etc.

**Comment by neolit123** [comment]
i think the test has a few minor problems.

- `Expect*` calls are not annotated:
  - bad:
    - `framework.ExpectNoError(err)`
  - good:
    - `framework.ExpectNoError(err, "a good description of the error")`

- naming; the test is not patching a ConfigMap object, but rather it's updating it:
https://github.com/kubernetes/kubernetes/pull/81205/files#diff-cfb4fba63c5d60607f76e0c2e1266d77R154
the test should be called `should update ConfigMap successfully`

side note on:
`fmt.Sprintf("Verifying update of configMap`

this tests and unfortunately other tests, seem to not follow standard case naming of API objects e.g. `configmap` vs `configMap` - correct one should be `ConfigMap` in user visible output.

**Comment by devaips** [comment]
@neolit123 thanks for the feedback. I will update the test name to contain "update" instead of "patch". On the other points, can you point me to the documentation for those standards? I'm happy to implement changes based on documented standards, otherwise I'm thinking the suggested changes would be out of scope.

**Comment by neolit123** [comment]
> On the other points, can you point me to the documentation for those standards? I'm happy to implement changes based on documented standards, otherwise I'm thinking the suggested changes would be out of scope.

see:
https://kubernetes.io/docs/contribute/style/style-guide/#use-camel-case-for-api-objects

> Use camel case for API objects

**Comment by devaips** [comment]
> > On the other points, can you point me to the documentation for those standards? I'm happy to implement changes based on documented standards, otherwise I'm thinking the suggested changes would be out of scope.
> 
> see:
> https://kubernetes.io/docs/contribute/style/style-guide/#use-camel-case-for-api-objects

Thanks @neolit123 

What about the `Expect*` annotations? Is that documented somewhere?

**Comment by neolit123** [comment]
> What about the Expect* annotations? Is that documented somewhere?

not sure about that one, but there are ongoing refactors to add annotations to calls that are missing them.

**Comment by spiffxp** [comment]
/close
I'm going to close this promotion PR as it sounds like there is work to be done on the test itself, which should be in a separate PR

**Pull request closed without merging**
