### PR TITLE
update help text for test-e2e-node target

### PR DESCRIPTION
**Pull request by MHBauer**
- document TEST_ARGS used in example
 - Break settings into sections, and move args into appropriate section.
 - update SKIP with default as used in the code

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
add to and update existing developer help text

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by MHBauer** [comment]
only a documentation change so,
/retest

**Comment by justaugustus** [comment]
Yay, documentation!
/test pull-kubernetes-e2e-kind-ipv6
/assign @BenTheElder @cblecker

**Comment by MHBauer** [comment]
clobbered by  #93224 & #93308 which contain much of the same work.
Not sure it's worth rebasing
/close

**Pull request closed without merging**
