### PR TITLE
Automated cherry pick of #89768: fix: update max azure disk max count

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #89768 on release-1.15.

#89768: fix: update max azure disk max count

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve
/retest

**Comment by andyzhangx** [comment]
@chewong need to use different windows config for version < 1.18:
```
Error: validating API model after populating values: CSI proxy for Windows is only available in Kubernetes versions 1.18.0 or greater
Usage:
  aks-engine generate [flags]

Flags:
  -m, --api-model string             path to your cluster definition file
      --ca-certificate-path string   path to the CA certificate to use for Kubernetes PKI assets
      --ca-private-key-path string   path to the CA private key to use for Kubernetes PKI assets
      --client-id string             client id
      --client-secret string         client secret
  -h, --help                         help for generate
      --no-pretty-print              skip pretty printing the output
  -o, --output-directory string      output directory (derived from FQDN if absent)
      --parameters-only              only output parameters files
      --set stringArray              set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)

Global Flags:
      --debug   enable verbose debug logs
```

**Comment by tpepper** [comment]
FYI this patch was not merged as its peers on other branches were not merged due to azure specific test failures (see https://github.com/kubernetes/kubernetes/pull/89850 and https://github.com/kubernetes/kubernetes/pull/89851) which need resolved. We aim to keep the cherry picks in sync across branches.  Now it's past the cherry pick deadline for today's final release 1.15.12 from the release-1.15 branch, so I'm going to close this pull request.

**Pull request closed without merging**
