### PR TITLE
Openapigen should process types in a consistent order

### LINKED ISSUE #42051: hack/update-all.sh is not enough to pass make verify_generated_files
This happened to me in https://github.com/kubernetes/kubernetes/pull/39683.

I've run `hack/update-all.sh` and was hoping that **everything** needed was update. But during checks jenkins invokes `make verify` and that will fail on `make verify_generated_files`. Now running that locally (after all was updated), I'm getting:

```
$ make verify_generated_files 
F0224 15:40:55.035792    8763 main.go:44] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kubernetes/pkg/generated/openapi":
output for "openapi/zz_generated.openapi.go" differs; first existing/expected diff: 
  "apps/v1beta1.Deployment\": {\n\t\t\tSchema: spec.Schema{\n\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\tDescript"
  "extensions/v1beta1.Deployment\": {\n\t\t\tSchema: spec.Schema{\n\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\tDe"

Makefile.generated_files:502: recipe for target 'verify_gen_openapi' failed
make[1]: *** [verify_gen_openapi] Error 1
Makefile:467: recipe for target 'verify_generated_files' failed
make: *** [verify_generated_files] Error 2
```

Now the question is what am I supposed to run to have that generated?

@kubernetes/sig-api-machinery-misc ideas?

### PR DESCRIPTION
**Pull request by soltysh**
This is an updated cherry-pick of #42068. This should fix some API check errors some PR trip on.

@mbohlool fyi

Fixes #42051

### CODE REVIEW

**Comment by soltysh** [comment]
After talking to @sttts we've decided to apply the approve and lgtm labels from based on previous PR and to unblock merge queue.

**Comment by sttts** [comment]
:+1: as this is only a rebase+code-regeneration.

**Comment by soltysh** [comment]
@mbohlool fyi

**Comment by mbohlool** [comment]
not sure why we have to identical PR? #42068

**Comment by soltysh** [comment]
@mbohlool I've opened this earlier today with your changes and refreshed generation with hope it gets merged fast, but it did not 😞

**Comment by mbohlool** [comment]
Is this blocking merge queue? What was the reason we wanted this merged fast?

**Comment by sttts** [comment]
@mbohlool not blocking the queue, but blocking other PRs supposed to go into 1.6. We had hoped to get this in before the big rush on the submit queue. Looks like this didn't work out.

**Comment by soltysh** [comment]
Closing this, since the original PR got merged faster.

**Pull request closed without merging**
