### PR TITLE
Move lease controller to k8s.io/component-helpers/apimachinery

### PR DESCRIPTION
**Pull request by roycaihw**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Follow the convention in `k8s.io/component-helpers`-- each helper is owned by a SIG. Giving it to sig api-machinery instead of sig node because: 
1. the lease controller is used by kubelet, but will be used by kube-apiserver and aggregated servers.
2. moving the code out of k/k was initiated by sig api-machinery (similar to `k8s.io/component-helpers/scheduling` being initiated by sig scheduling and shared by multiple components)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig api-machinery
/sig node
/cc @deads2k @sttts @ingvagabund

### CODE REVIEW

**Comment by ingvagabund** [comment]
`./hack/update-vendor.sh` will take care of `pull-kubernetes-dependencies`

**Comment by ingvagabund** [comment]
@roycaihw can you also squash the commits? The changes are easy to follow.

**Comment by dims** [comment]
@roycaihw looks like one failure in CI remains (legit!)

**Comment by roycaihw** [comment]
Ran `hack/update-vendor.sh` and squashed the commits into one. Thanks for the review!

**Comment by roycaihw** [comment]
/assign @derekwaynecarr
for node approval

**Review by soltysh — APPROVED** [review]
/approve
/priority backog

**Comment by ingvagabund** [comment]
```
$ grep -rn "k8s.io/component-helpers/lease" --include "*.go"
pkg/controlplane/instance.go:84:	"k8s.io/component-helpers/lease"
pkg/kubelet/kubelet.go:58:	"k8s.io/component-helpers/lease"
```

@roycaihw the PR needs to be rebased

**Comment by roycaihw** [comment]
> @roycaihw the PR needs to be rebased

rebased. Thanks!

**Comment by roycaihw** [comment]
test failure related to kubernetes/test-infra#19910

**Comment by roycaihw** [comment]
The test passes. @ingvagabund could you re-tag the PR? Thanks

**Comment by ingvagabund** [comment]
@roycaihw thanks for the quick response!!!

**Pull request merged**
