### PR TITLE
Bump dependency opencontainers/runc@v1.0.0-rc10

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Changelog: https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/retest
/assign @liggitt @dims

For my own context, @odinuge, are we bumping this dependency to bring in specific features or bug fixes? Or just in general trying to use the freshest possible deps?

**Comment by liggitt** [comment]
I'm guessing this is trying to pick up the new runc to help with https://github.com/kubernetes/kubernetes/issues/86312, but if I understand correctly, it's the runc version installed in our CI envs and used by docker/cri/containerd that will actually help, not the version we vendor.

**Comment by BenTheElder** [comment]
I'm not sure what we pull in from runc in k/k, but the `runc` binary used to create containers in our e2e nodes is not coming from this repo, it's up to the deployment tool (KIND ships it's own, COS / kube-up do similar...)

**Comment by odinuge** [comment]
@liggitt & @BenTheElder 

Yes, for the issue you are referring to will not be fixed by updating the dependency here. Most container runtimes use runc, so it _is_ the binary used by the runtime that matters in that case. We do however use `opencontainers/runc/libcontainer/` a few places in the linux implementation of [kubelet](https://github.com/kubernetes/kubernetes/search?q=opencontainers%2Frunc%2Flibcontainer%2F&unscoped_q=opencontainers%2Frunc%2Flibcontainer%2F) to handle things like cgroups (eg. for pods and for the different priorities).

The new release include some small fixes, and the cgroup2 implementation is now split into a separate implementation instead of a unified one. We don't use cgroup2 yet, but I guess it is nice to stay up to date the day we start working with it.

So yes, this is not strictly necessary, but I think keeping it up to date will help us the day we are forced to bump it. We can consider switching to [https://github.com/opencontainers/runtime-tools](https://github.com/opencontainers/runtime-tools) instead, or just writing it ourself, but that is another discussion tho. 

/priority backlog
/assign @derekwaynecarr

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#justifications-for-an-update

**Comment by liggitt** [comment]
@derekwaynecarr do you know what (if any) the implications of the ebpf addition are?

**Comment by dims** [comment]
@liggitt the changes are mainly related to cgroupv2 and the cilium seems to be in the cgroupv2 only as well ( https://github.com/opencontainers/runc/pull/2145 - starting point `LoadAttachCgroupDeviceFilter` )

**Comment by odinuge** [comment]
As a side note, KEP for cgroups2 can be found here: https://github.com/kubernetes/enhancements/pull/1370

**Comment by liggitt** [comment]
does merging this change cgroups v1 support at all? does the kubelet need to change anything in order to continue working as-is with this update (e.g. any of the updates described in https://github.com/kubernetes/enhancements/pull/1370)?

**Comment by odinuge** [comment]
cgroupv1 still works the same way in runc, and will keep doing that, so no changes will be required in kubelet in order to upgrade. As you see here https://github.com/kubernetes/enhancements/pull/1370/files#diff-b8b7ada28664d1c52714060eb5a99abeR82, the runc cgroupv2 hasn't been complete until now (more or less complete now, stuff like hugetlb will not be supported before `linux-5.6`). 

KEP 1370 is still ongoing, and it will probably take quite some times before it is ready. Fedora is already shipping with cgroupsv2 enabled by default (means no support for v1), but I don't believe any other distros does yet.

The version in k/k master has some initial cgroupv2 code, but https://github.com/opencontainers/runc/pull/2169 moves the logic into a separate package in order to don't mix up the code.

**Comment by liggitt** [comment]
/approve
based on https://github.com/kubernetes/kubernetes/pull/87516#issuecomment-579248730 and https://github.com/kubernetes/kubernetes/pull/87516#issuecomment-578952861

**Comment by derekwaynecarr** [comment]
@liggitt from what i saw, cgroupv2 integration was moved under fs2 which we do not use in kubelet yet, but will have to start looking at in future depending on how cgroupsv2 integration proceeds.  the systemd cgroup manager (which kubelet does use) still only references fs and not fs2.

see: https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go

**Comment by liggitt** [comment]
> the systemd cgroup manager (which kubelet does use) still only references fs and not fs2.
> 
> see: https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go

as of this PR, the systemd manager references fs2:
https://github.com/odinuge/kubernetes/blob/runc-rc10/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/unified_hierarchy.go#L17

and the libcontainer one references both fs and fs2:
https://github.com/odinuge/kubernetes/blob/runc-rc10/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go#L16-L17

/hold just to make sure that matches your expectations, @derekwaynecarr can unhold when ready

**Comment by derekwaynecarr** [comment]
@liggitt it is correct that runc added a unified hierarchy manager.

see: https://github.com/odinuge/kubernetes/blob/runc-rc10/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/unified_hierarchy.go#L23

kubelet still uses the legacy manager:
https://github.com/kubernetes/kubernetes/blob/f4db8212be53c69a27d893d6a4111422fbce8008/pkg/kubelet/cm/cgroup_manager_linux.go#L156

which is still supported unchanged in runc:
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L24

As kubelet evolves to support both cgroupv1 and cgroupv2, it will adjust to support either unified hierarchy manager or legacy manager during transition.

**Comment by liggitt** [comment]
thanks for confirming

/hold cancel

**Pull request merged**
