### PR TITLE
X race condition from TestApfExecuteWatchRequestsWithInitializationSignal

### LINKED ISSUE #104692: Data race in TestApfExecuteWatchRequestsWithInitializationSignal
#### Which jobs are flaking:

`pull-kubernetes-unit`

#### Which test(s) are flaking:

`TestApfExecuteWatchRequestsWithInitializationSignal`

#### Testgrid link:

Testgrid doesn't load kubernetes/test-infra#23425

#### Reason for failure:

From: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104666/pull-kubernetes-unit/1432426000020410368

```
WARNING: DATA RACE
Read at 0x00c0008a4044 by goroutine 401:
  runtime.raceread()
      <autogenerated>:1 +0x24
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestApfExecuteWatchRequestsWithInitializationSignal()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:507 +0x844
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Previous write at 0x00c0008a4044 by goroutine 259:
  runtime.racewrite()
      <autogenerated>:1 +0x24
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestApfExecuteWatchRequestsWithInitializationSignal.func4()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:479 +0x64
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.newApfHandlerWithFilter.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:169 +0x30
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2046 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:243 +0x1228
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2046 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.newApfHandlerWithFilter.func2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:176 +0x56c
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2046 +0x4d
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x547
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2046 +0x4d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2878 +0x89a
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1929 +0x12e4
  net/http.(*Server).Serve·dwrap·82()
      /usr/local/go/src/net/http/server.go:3033 +0x58

Goroutine 401 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestMain()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:60 +0x35
  main.main()
      _testmain.go:99 +0x264

Goroutine 259 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3033 +0x847
  net/http/httptest.(*Server).goServe.func1()
      /usr/local/go/src/net/http/httptest/server.go:308 +0xc4
==================
    testing.go:1152: race detected during execution of test
```

/sig api-machinery

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR fixes a unit test to remove a race condition.

#### Which issue(s) this PR fixes:

Fixes #104692 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @tkashem

**Comment by wojtek-t** [comment]
Thanks for fixing it Mike!

/lgtm
/approve

**Pull request merged**
