### PR TITLE
add pod information to device plugin allocate request

### PR DESCRIPTION
**Pull request by yiyang5055**
/sig node
/area kubelet

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
add pod information to device plugin allocate request, and to pass into device plugin, user could use it

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
issue [#82606](https://github.com/kubernetes/kubernetes/issues/82606)

**Does this PR introduce a user-facing change?**:

```release-note
message AllocateRequest {
	repeated string devicesIDs = 1;
        string podUID = 2;
        string podNameSpace = 3
        string podName = 4;
}
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by jiayingz** [comment]
To learn what pod is assigned to what device, would Kubelet's compute-device-assignment endpoint (https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/compute-device-assignment.md) serve that purpose?

**Comment by yiyang5055** [comment]
> To learn what pod is assigned to what device, would Kubelet's compute-device-assignment endpoint (https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/compute-device-assignment.md) serve that purpose?

@jiayingz  
No,  sorry, Maybe my description is not clear, let you understand the mistakes,.

Give an example of user story about GPU.

In scheduler phase, the pod have be allocated GPU and information is stored in annotation by custome scheduler,  for example:
```
apiVersion: apps/v1
kind: Pod
  metadata:
  name: nvidia-deployment
  annotations:
    ## gpu index
    NVIDIA_VISIBLE_DEVICES: 0
spec:
  containers:
    - name: example-container
      resources:
        limits:
          ## a customized resource about gpu memory
          nvidia.com/gpu-mem: 6
```
In pod start phase, when creating containers, kubelet calls the device plugin's `Allocate` function,  just pass deviceID into device plugin, in order to obtain have allocated GPU information by customized scheduler store in annotations, we need **List()**  and **order** pending pod by create timestamp, then select first **`pending pod`**.  finally,  device plugin send a response to allocate  request include `NVIDIA_VISIBLE_DEVICES`  and other customized information such as GPU mem.

According to above step, method of get pod is ugly and not elegant. I think get or update pending pod maybe is a common problem in device plugin's `Allocate` function,  tell device plugin which pod calls `Allocate` function is required, the coder of customized device plugin could do something with pod.

Of course, GPU is just one of the kubernetes support devices, and it is possible that my idea is incorrect.

**Comment by jiayingz** [comment]
@yiyang5055 When we designed the device plugin API, we made it clear that Kubelet takes responsibility of allocating devices to containers. From the above described flow, it feels that you are proposing an underlying implicit API that can implement a different kind of device allocation that may be inconsistent with Kubelet's view. I think this will just open jars of issues when used in production.

**Pull request closed without merging**
