### PR TITLE
Move certificate manager to client.

### PR DESCRIPTION
**Pull request by jcbsmpsn**
Fixes https://github.com/kubernetes/kubernetes/issues/53452

**What this PR does / why we need it**:
Migrate the certificate_manager to a location where it can be shared.

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Just saw this, wanted it.

**Comment by smarterclayton** [comment]
The bot does not want you pull request.

**Comment by jcbsmpsn** [comment]
@smarterclayton I checked on #sig-test and they said ignore the failing `pull-kubernetes-e2e-kubeadm-gce` check. Can you lgtm this and see if it merges?

**Pull request merged**
