### PR TITLE
Automated cherry pick of #126665: Restore honoring --version build ID overrides

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #126665 on release-1.31.

#126665: Restore honoring --version build ID overrides

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
kube-apiserver: Fixes a 1.31 regression that stopped honoring build ID overrides with the --version flag
```

### CODE REVIEW

**Comment by jpbetz** [comment]
/lgtm
/approve

Thanks for fixing!

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
