### PR TITLE
Minor change: delete unused constant from service controller

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Delete unused constant.

**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority backlog

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Review by MrHohn — APPROVED** [review]
Thanks!
/lgtm
/approve

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
