### PR TITLE
We never want to modify the globally defined SG for ELBs

### LINKED ISSUE #50105: When using elbSecurityGroup cloudConfig with AWS, the sg's rules flap
/kind bug

**What happened**:

When setting an elbSecurityGroup in cloud.config for AWS, and deploying multiple services with differing ports, then the security group rules flap in AWS, causing services to become inaccessible (only one will be correctly configured at a time).

**What you expected to happen**:

I expect that the configured elbSecurityGroup's rules will not be touched at all.  It must be pre-configured to permit access.  Alternatively, all ports for all services are queried and managed together.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

Most people are not running large clusters which may hit the AWS limits, so they won't use this option, nor see this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.1
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 4.10.13-1-ARCH
- Install tools: Custom
- Others:

### PR DESCRIPTION
**Pull request by nbutton23**
**What this PR does / why we need it**:
Fixes a bug where creating or updating an ELB will modify a globally defined security group

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50105

**Special notes for your reviewer**:

**Release note**:

```release-note
fixes a bug around using the Global config ElbSecurityGroup where Kuberentes would modify the passed in Security Group.
```

### CODE REVIEW

**Comment by ericchiang** [comment]
cc @lpabon

**Comment by nbutton23** [comment]
Looks like there is an known issue with the `pull-kubernetes-bazel` test https://github.com/kubernetes/kubernetes/issues/49844

**Comment by waldman** [comment]
Any Idea when this will be merged/released?

**Comment by nbutton23** [comment]
@justinsb what do I need to do to get this into the merge Queue?

**Pull request merged**
