### PR TITLE
Cleanup Godeps and make verify-godep.sh run

### PR DESCRIPTION
**Pull request by eparis**
Godep switched to default not include _test.go. So thousands of files gone.

Also was noticed that verify-godeps.sh wasn't checking things right...

### CODE REVIEW

**Comment by eparis** [comment]
@thockin @piosz

**Comment by eparis** [comment]
/me giggles.  43,000 lines removed. Size: XS  (no it's not a mistake)

**Comment by thockin** [comment]
niiiiiiice.  Someone is hooting for top-remover status.

**Comment by davidopp** [comment]
LGTM

I'm just gonna trust you on this one.

**Comment by eparis** [comment]
removing LGTM.  The removed dep definitely needs fixed....

**Comment by eparis** [comment]
```
=== RUN TestMasterProcessMetrics
W0919 20:45:01.918436   18357 master.go:261] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
I0919 20:45:01.918512   18357 master.go:287] Node port range unspecified. Defaulting to 30000-32767.
I0919 20:45:01.918957   18357 master.go:309] Will report 172.17.5.148 as public IP address.
I0919 20:45:02.140485   18357 metrics_test.go:71] Got metric "ssh_tunnel_open_fail_count"
--- FAIL: TestMasterProcessMetrics (0.22s)
```

Shippaple last failed with the above, which seems unrelated...  Rebased...

**Comment by eparis** [comment]
Ahhh, I did have the broken Godeps fixed in #14233  duh.

**Comment by eparis** [comment]
green green green, anyone want to get us out of this godeps verification mess with a LGTM?

**Pull request merged**
