### PR TITLE
optimize the binding logic of bindClaimToVolume

### PR DESCRIPTION
**Pull request by NickrenREN**
extract var shouldSetBoundByController and do not need to judge volumename twice
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
Good catch. Can you please rename `shouldSetBoundByController` to something more appropriate now? `shouldBind`?

**Comment by NickrenREN** [comment]
@jsafrane  Ok, thanks. Done !

**Comment by NickrenREN** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
