### PR TITLE
[WIP] Remove extensions/v1beta1 Job

### LINKED ISSUE #32763: Remove extensions/v1beta1 Jobs
Jobs were introduced in `extensions/v1beta1` in k8s version 1.1. Over the past year we've spent quite amount of time into stabilizing them to finally introduce stable ones in `batch/v1` in version 1.2. 
With that in mind I'm proposing to remove Jobs from `extensions/v1beta1` entirely. We've kept full compatibility between the two aforementioned groups so that users of either endpoint can work transparently with either of them. We're hoping the amount of time (2 versions since 1.2 aka stable Jobs) was sufficient and eventual users using the old group should have a smooth way to migrate to the stable API endpoint.

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #32763.

This is still WIP, mostly because I'm not sure what to do with `pkg/client/clientset_generated/release_1_3/` since it's pointing to `extensions/v1beta1.Job`. Should I just remove everything else but leave the type for that 1.3 client to compile? @kubernetes/sig-api-machinery thoughts?

@janetkuo || @erictune ptal

**Release note**:

``` release-note
Remove support for Job object in extensions/v1beta1 API.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33861)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@soltysh @erictune Have we announced deprecation of the beta version yet, in previous release notes, user docs, or anywhere?

**Comment by soltysh** [comment]
@bgrant0607 I don't recall, but since Jobs migrated to stable in 1.2 I've proposed (#32763) removing it at this point. Especially that when introducing ScheduledJobs we have Job resource available in 3 places: `extensions/v1beta1`, `batch/v1` and `batch/v2alpha`. The former two are even stored under the same key in etcd (see [resource cohabitation](https://github.com/kubernetes/kubernetes/blob/20e764ab5d4b64e39f16a6bb441b52563757e156/cmd/kube-apiserver/app/server.go#L161)). Are you proposing we should wait till 1.6 with that and for now issue warnings in docs (somewhere else?). Actually, we don't have any solution in place for removing such resources (see my problems with 1.3 versioned clients), I somehow feel I'm gonna blaze the trail here, like I did with 2nd api version for batch ;-)

**Comment by soltysh** [comment]
@bgrant0607 @erictune any objections to push it forward or you'd guys prefer to wait for the next release and notify users in this one?

**Comment by bgrant0607** [comment]
@soltysh Let's please just notify users in 1.5 and not actually delete it until later. We should ensure that kubectl convert works for this case and include instructions for how to use it in the notice.

**Comment by soltysh** [comment]
Superseded by #36355, for now at least.

**Pull request closed without merging**
