### PR TITLE
Update one of the diagrams for logging blog article

### PR DESCRIPTION
**Pull request by satnam6502**

### CODE REVIEW

**Comment by erictune** [comment]
@thockin for :art:

I'm guessing he will suggest you convert to svg, but who knows.

**Comment by satnam6502** [comment]
Happy to also check in an SVG version. However, I work on diagrams using Adobe Illustrator so I need the .ai files.

**Comment by thockin** [comment]
interestingly .ai is PDF compatible.  If you rename it to .pdf it should be
fine.  Or at least used to be.

**Comment by satnam6502** [comment]
That's correct -- if you rename the .ai files with .pdf you can view them with a regular PDF viewer.

**Comment by thockin** [comment]
So can you check in a PDF and/or SVG?

**Comment by satnam6502** [comment]
Added SVGs.

**Comment by thockin** [comment]
I'm OK with this - I assume the SVGs are individual layers of the AI?

**Comment by satnam6502** [comment]
I only use 1 layer in the AIs (I think). The SVGs are produced with "Save As..." in Illustrator.

**Comment by thockin** [comment]
How does one AI turn into multiple SVGs?  I don't have AI to look..

**Comment by satnam6502** [comment]
Oh, I saved the SVGs for all the other diagrams in this directory that have
already been committed.

S

**Comment by thockin** [comment]
OH!  Ok.  LGTM

**Comment by satnam6502** [comment]
Please can I have an LGTM label on this so the on-call notices it? Thanks. @mbforbes

**Comment by mbforbes** [comment]
I am not oncall. @jlowdermilk is. Regrettably merge policy has now changed so this might be a bit more hairy.

**Comment by jlowdermilk** [comment]
This counts as docs so merging.

**Pull request merged**
