### PR TITLE
Fix staticcheck failures for vendor/k8s.io/apiserver/pkg/util/webhook

### PR DESCRIPTION
**Pull request by mozillazg**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Part of #92402

```
vendor/k8s.io/apiserver/pkg/util/webhook/certs_test.go:71:5: var badCAKey is unused (U1000)
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mozillazg** [comment]
@sttts ping~

**Comment by tiloso** [comment]
Hey @mozillazg, it looks like `vendor/k8s.io/apiserver/pkg/util/webhook` has already been fixed in https://github.com/kubernetes/kubernetes/pull/101707.

**Comment by mozillazg** [comment]
@tiloso 👌

**Pull request closed without merging**
