### PR TITLE
MESOS: Automated cherry pick of #15735 - Fix minion tasks and profiling

### PR DESCRIPTION
**Pull request by sttts**
Cherry pick of #15735 on release-1.1.

This is part of a set of cherry-picks to fix Mesosphere e2e smoke tests for the release branch.

Fixes https://github.com/mesosphere/kubernetes-mesos/issues/640

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot test this

**Comment by davidopp** [comment]
LGTM

**Comment by sttts** [comment]
Squashed and rebased.

**Comment by sttts** [comment]
Rebased.

**Comment by sttts** [comment]
Rebased once again. Integration tests run fine locally.

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
There is nothing changed in this PR that is running during non-mesos e2e tests.

**Pull request merged**
