### PR TITLE
Honor status.podIP over status.podIPs and node.spec.podCIDR over node.spec.PodCIDRs when mismatched

### LINKED ISSUE #88494: Daemonset pod status PATCH errors after upgrading cluster from 1.14 to 1.16
**What happened**:

The cluster master in a Kubernetes v1.14.10 cluster was upgraded to V1.16.7.  The process of upgrading nodes is under way and has been spread over a week so far.  The cluster owner reported seeing a high percentage of pod status PATCH failures.  The apiserver logs show errors like:
```
I0223 20:40:57.482215       1 httplog.go:90] PATCH /api/v1/namespaces/cache-images-2-10-2/pods/dashdb-daemonset-s4crw/status: (8.261945ms) 500
...
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12b\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1aJconversion Error: v1.PodIP(172.30.147.226) != v1.PodIPs[0](172.30.147.223)\"\x000\xf4\x03\x1a\x00\"\x00"
 [hyperkube/v1.14.5+IKS (linux/amd64) kubernetes/7bc6122 172.16.25.64:65323]
```

The errors are all from the v1.14 nodes and have all been for pods associated with DaemonSets.

We don't yet know why pods' IPs are changing, but it appears that pod status patches that include a changed `PodIP` result in an object where `PodIPs[]` contains the old IP, and `podIP` has the new IP. We believe this is because `PodIPs[]` was introduced in Kubernetes v1.15 and the patch request from a v1.14 node results in both `PodIP=new IP` and `PodIPs = [old IP]` being present in the result.

If you aren't monitoring for request failures it may not obvious that any error is occurring: The pods continue to show their last successfully reported state.  Deleting such pods, however, results in the pod being stuck in a `Terminating` state.

We are only seeing this for DaemonSet pods - I suspect because whatever resulted in pod IPs changing also causes non-DaemonSet pods to be deleted and recreated.

We have a number of cluster still on v1.14 that we expect to upgrade to v1.15 or v1.16.

**What you expected to happen**:

Kubernetes v1.14 nodes should be able to update pod status during the transition from v1.14 to v1.16 even if pod IPs change during that time.

**How to reproduce it (as minimally and precisely as possible)**:

We have recreated this in the IBM Cloud Kubernetes Service by "reloading" nodes.  The reload process leaves the Kubernetes node object in place, and essentially reloads the image with the proper kubeconfig to rejoin the cluster.  The cluster I was debugging does not appear to have had nodes "reloaded" - something else is triggering the pod IP changes.

- Create a v1.14 cluster
- Deploy a DaemonSet (anything with pod networking should suffice)
- Upgrade cluster master to v1.16
- Reload a v1.14 node.

One the node is back up, `crictl inspectp` shows the pod's network IP has changed.  Kubelet and apiserver logs show the errors describe earlier.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.x (nodes) and v1.16.7 (master)
- Cloud provider or hardware configuration: IBM Cloud Kubernetes Service
- OS (e.g: `cat /etc/os-release`): 18.04.4 LTS
- Kernel (e.g. `uname -a`): 4.15.0-76-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind api-change
/kind bug

**What this PR does / why we need it**:

### When status.podIP and status.podIPs[0] do not agree, honor status.podIP as the older API field, rather than failing to convert.

This is required to support Kubelets < 1.16 running against API servers >= 1.16.

Kubelets >= 1.16 set both podIP and podIPs:
https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/kubelet/kubelet_pods.go#L1386-L1396

Kubelets < 1.16 only set podIP:
https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/kubelet/kubelet_pods.go#L1384-L1385

However, since kubelets update pod status with a patch API request, existing unknown fields are preserved. That means a 1.15 kubelet, when trying to modify a podIP, will only update the podIP field and not podIPs.

### When node.spec.podCIDR and node.spec.podCIDRs[0] do not agree, honor node.spec.podCIDR as the older API field, rather than failing to convert.

prior to 1.16, the rangeAllocator and cloudCIDRAllocator controllers updated node.spec.podCIDR using a patch:
https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/controller/nodeipam/ipam/adapter.go#L92-L106

in 1.16+, there are three methods to update node specs, all of which use patch:
* https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/util/node/node.go#L194-L207
* https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/util/node/node.go#L179-L186
* https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/controller/nodeipam/ipam/adapter.go#L94-L106

These patch methods either just set the old node.spec.podCIDR field, or they set both the old and new podCIDR/podCIDRs field (for paths that are multi-CIDR-aware).

**Which issue(s) this PR fixes**:
Fixes #88494

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a regression with clients prior to 1.15 not being able to update podIP in pod status, or podCIDR in node spec, against >= 1.16 API servers
```

/cc @thockin @khenidak 
/sig network

### CODE REVIEW

**Comment by gongguan** [comment]
If honor status.podIP while status.podIP and status.podIPs[0] do not agree, should https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/kubelet/kubelet_pods.go#L1395 be `apiPodStatus.PodIP = pod.Status.PodIP`?

**Comment by gongguan** [comment]
If honor status.podIP while status.podIP and status.podIPs[0] do not agree, should https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/kubelet/kubelet_pods.go#L1395 be `apiPodStatus.PodIP = pod.Status.PodIP`?

**Comment by liggitt** [comment]
> If honor status.podIP while status.podIP and status.podIPs[0] do not agree, should https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/kubelet/kubelet_pods.go#L1395 be `apiPodStatus.PodIP = pod.Status.PodIP`?

No, the kubelet is the writer, and that function is generating the API status it should set. This PR is fixing the API server's treatment of requests made by older kubelets that weren't aware of the PodIPs field

**Comment by liggitt** [comment]
/retest
storage node pod capacity flake

**Review by thockin — COMMENTED** [review]
I'm not sure on this.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md (search for "plural")

```
Upon any mutating API operation:
  * If only the singular field is specified (e.g. an older client), API logic
    must populate plural[0] from the singular value, and de-dup the plural
    field.
  * If only the plural field is specified (e.g. a newer client), API logic must                                                                                  
    populate the singular value from plural[0].
  * If both the singular and plural fields are specified, API logic must
    validate that the singular value matches plural[0].
  * Any other case is an error and must be rejected.
```

Clearly that isn't correct in the face of patch.

This would allow someone to send a PUT with `podIP: X` and `podIPs: [ Y, Z ]` which silently nukes `podIPs`, which seems wrong (I think?).

Would it be saner to do this silent change ONLY when dealing with some sort of patch?  Is that even possible to know?

Either way, the documented bits are incorrect...

**Comment by liggitt** [comment]
patch is indistinguishable from put that left the unpatched fields unmodified. 

if you want to do delta-specific behavior, you need the old object, which means you cannot do it in conversion, and would need to represent both the plural and singular field in the internal type and deal with the logic in the rest handler PrepareForUpdate function

**Comment by thockin** [comment]
@khenidak

Are we OK with the precedent for pluralizing - writes that set `singular`
and do not sync `plural[0]` will cause `plural[]` to be reset

**Comment by liggitt** [comment]
The referenced guidance assumed the ability to detect *change* in a field coming from a client (emphasis added):

> For this purpose "is specified" means the following:
> * On a create or patch operation: the field is present in the user-provided input
> * On an update operation: the field is present _and has changed from the current value_

The place that has visibility to the old and new pod on updates is working with internal objects, at which point the information about the plural/singular field content has been lost in conversion (the internal object only has the plural field). That means we cannot follow that guidance with the internal pod types as they stand today.

Since this impacts upgrades to 1.16, and the fix here will need to be picked back 2 releases, I'm inclined to resolve this bug in favor of old kubelet clients, and make the singular podIP rule in case of mismatch, rather than try to rework the pod internal types and conversion.

**Comment by thockin** [comment]
I guess I don't see a choice.  @khenidak for last confirm

**Comment by thockin** [comment]
/lgtm
/hold

@khenidak PTAL or we will remove the hold .  We'll have to make the same change on `nodeIPs`.  Anywhere else?

**Comment by liggitt** [comment]
looking at our handling of podCIDR/podCIDRs, which looks like it has a similar problem

**Comment by liggitt** [comment]
prior to 1.16, the rangeAllocator and cloudCIDRAllocator controllers updated node.spec.podCIDR using a patch:
https://github.com/kubernetes/kubernetes/blob/89a7468341d588301c6c8be360ed2abb871009e1/pkg/controller/nodeipam/ipam/adapter.go#L92-L106

in 1.16+, there are three methods to update node specs, all of which use patch:
https://github.com/kubernetes/kubernetes/blob/b383807a14c53196d8e66d02853f982ca0da2ada/pkg/util/node/node.go#L194-L207
https://github.com/kubernetes/kubernetes/blob/b383807a14c53196d8e66d02853f982ca0da2ada/pkg/util/node/node.go#L179-L186
https://github.com/kubernetes/kubernetes/blob/b383807a14c53196d8e66d02853f982ca0da2ada/pkg/controller/nodeipam/ipam/adapter.go#L94-L106

These patch methods either just set the old node.spec.podCIDR field, or they set both the old and new podCIDR/podCIDRs field (for paths that are multi-CIDR-aware).

That means our conversion handling of podCIDR/podCIDRs must follow the same approach as podIP/podIPs: if the singular and plural[0] disagree, assume we're dealing with an old client and let the singular rule.

**Comment by liggitt** [comment]
Updated with identical handling and tests for podCIDR/podCIDRs

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by liggitt** [comment]
cherry-picks updated with podCIDR bits as well:
* 1.17: https://github.com/kubernetes/kubernetes/pull/88506
* 1.16: https://github.com/kubernetes/kubernetes/pull/88507

**Comment by thockin** [comment]
I pinged Kal on slack.

If you need to proceed today, LGTM

**Comment by liggitt** [comment]
I'll make sure we have clean CI signal on this and all the cherry-picks, then plan to unhold

**Comment by liggitt** [comment]
picks are green.

/hold cancel

**Pull request merged**
