### PR TITLE
fix kubelet help information about flag logging-format

### PR DESCRIPTION
**Pull request by navist2020**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
image
In the document of kubelet, flags use - connect the words. So we should use the same flags in the code.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ehashman** [comment]
/release-note-none
/priority backlog
/cc @serathius 

Did we fix this? I thought this was fixed elsewhere...

**Comment by ehashman** [comment]
Hey @navist2020, this is a duplicate of #98516.

/close

**Comment by navist2020** [comment]
OK, I see. Thank you for your attention to this PR. @ehashman

**Pull request closed without merging**
