### PR TITLE
Automated cherry pick of #11998 upstream release 1.0

### PR DESCRIPTION
**Pull request by a-robinson**
Updates the version of heapster to include at least one important bug fix (https://github.com/GoogleCloudPlatform/heapster/pull/409). I'm not convinced this is better than cherry-picking the needed fix into a heapster 0.16.1, but @vishh is in favor of this.

@roberthbailey @brendandburns

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.  Let's talk tomorrow about the risk profile here.

Thanks
--brendan

**Comment by ncdc** [comment]
@timstclair @eparis @smarterclayton FYI

**Comment by a-robinson** [comment]
We're going to cherry-pick the heapster fix into a heapster 0.16.1 rather than pulling in 0.17.0, which includes too many changes. Abandoning this PR.

**Comment by timstclair** [comment]
@timothysc

**Pull request closed without merging**
