### PR TITLE
Collect npd log in cluster e2e test.

### PR DESCRIPTION
**Pull request by Random-Liu**
Collect node problem detector log in cluster e2e.

@dchen1107 @kubernetes/node-problem-detector-reviewers

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by Random-Liu** [comment]
@dchen1107 Could you take a look at this? :)

**Comment by Random-Liu** [comment]
With this PR, we are able to collect npd log from nodes in both GCI and CVM cluster e2e.

From the current log output, it seems that fluentd OOM is so frequently, although it's a known issue. Anyway, at least this proves that NPD is working properly.
```
I0223 09:49:01.551168       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:49:00 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 32647 (td-agent) score 2004 or sacrifice child
Killed process 32647 (td-agent) total-vm:1006000kB, anon-rss:201528kB, file-rss:9520kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
I0223 09:49:37.619566       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:49:37 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 3450 (td-agent) score 1993 or sacrifice child
Killed process 3450 (td-agent) total-vm:1267540kB, anon-rss:199040kB, file-rss:9868kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
I0223 09:50:45.865168       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:50:45 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 9249 (td-agent) score 1985 or sacrifice child
Killed process 9249 (td-agent) total-vm:1213884kB, anon-rss:197288kB, file-rss:9868kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
I0223 09:51:46.484050       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:51:45 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 16860 (td-agent) score 2014 or sacrifice child
Killed process 16860 (td-agent) total-vm:1057680kB, anon-rss:203420kB, file-rss:9736kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
I0223 09:53:25.590866       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:53:25 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 21148 (td-agent) score 1984 or sacrifice child
Killed process 21148 (td-agent) total-vm:1216876kB, anon-rss:197176kB, file-rss:9720kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
I0223 09:56:21.656152       5 log_monitor.go:123] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2017-02-23 09:56:20 +0000 UTC Reason:OOMKilling Message:Memory cgroup out of memory: Kill process 23813 (td-agent) score 2014 or sacrifice child
Killed process 23813 (td-agent) total-vm:1051184kB, anon-rss:203172kB, file-rss:9860kB}] Conditions:[{Type:KernelDeadlock Status:false Transition:2017-02-23 09:40:51.808386455 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}]}
```

**Comment by dchen1107** [comment]
LGTM

**Comment by Random-Liu** [comment]
Apply LGTM based on https://github.com/kubernetes/kubernetes/pull/41949#issuecomment-282879137.

**Comment by Random-Liu** [comment]
@k8s-bot test this

**Comment by Random-Liu** [comment]
The kubemark test failure is a fake. Same failure also occurs in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42084/pull-kubernetes-kubemark-e2e-gce/19966

**Comment by Random-Liu** [comment]
@k8s-bot kubemark e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
