### PR TITLE
Automated cherry pick of #75952: tests: Solve backoff tests flakiness Cherry pick of #75952 on release-1.14. #75952: tests: Solve backoff tests flakiness

### PR DESCRIPTION
**Pull request by claudiubelu**
Reason for cherry-picking:

The container status is not constant, and it fluctuates between ``Running``, ``Terminated``, and ``Waiting``, and it is possible for the test to miss any of those transitions, resulting in the test being flaky. This PR eliminates it by treating all the states, rather than just the ``Terminated`` state.

Will help improve stability for: https://testgrid.k8s.io/sig-windows#aks-engine-azure-1-14-windows

### CODE REVIEW

**Comment by tpepper** [comment]
Is there a reason the cherry pick automation was not used:

**Comment by tpepper** [comment]
Looks like this is coming from:
https://github.com/kubernetes/kubernetes/pull/75952
/kind flake
/area conformance
/area test
/sig node
/sig testing
/release-note-none
/priority important-soon

**Comment by bclau** [comment]
> 
> 
> Is there a reason the cherry pick automation was not used
> https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md
> 
> What is the master branch PR / commit from which this is picked?
> 
> /hold

I followed this guide: https://stupefied-goodall-e282f7.netlify.com/contributors/devel/cherry-picks/

I didn't know of any other guide.

**Comment by tpepper** [comment]
@kubernetes/sig-node-pr-reviews looking for lgtm/approve here or close

**Comment by tpepper** [comment]
@kubernetes/sig-testing-pr-reviews also looking for your input

**Pull request merged**
