### PR TITLE
WIP: kms: cancel all RPCs when global context is canceled

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mok@microsoft.com>

/kind cleanup

```release-note
NONE
```

xref: #112050

### CODE REVIEW

**Comment by enj** [comment]
Marking WIP because I want to add some unit tests.

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Pull request closed without merging**
