### PR TITLE
Minor cleanups in pkg/proxy/endpoints.go

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> 
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR contains two minor cleanups in pkg/proxy/endpoints.go

Merge and Unmerge are needlessly exported, they are used only by the unexported apply function

Changed GetLocalEndpointIPs(endpointsMap) to be ean endpointsMap struct method and unexported it

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

**Comment by dcbw** [comment]
/lgtm
@thockin what do you think?

**Comment by dcbw** [comment]
@JacobTanenbaum looks like the testcases need some fixup:
```
/b/f/w/pkg/proxy/endpoints_test.go:1216:3: undefined: UpdateEndpointsMap
/b/f/w/pkg/proxy/endpoints_test.go:1236:13: undefined: UpdateEndpointsMap
/b/f/w/pkg/proxy/endpoints_test.go:1376:13: undefined: UpdateEndpointsMap
```

**Pull request merged**
