### PR TITLE
[wip] kms: use AES-GCM for writes instead of AES-CBC

### PR DESCRIPTION
**Pull request by enj**
Let's see what tests break.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Hi @<name> My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

**Comment by markyjackson-taulia** [comment]
Hi @enj  My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

**Comment by enj** [comment]
> Hi @enj  My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

Yeah we have a few folks actively working on KMS improvements for 1.25 (this being one of the changes).

**Comment by aramase** [comment]
https://github.com/kubernetes/kubernetes/pull/111119 supersedes this PR

**Comment by markyjackson-taulia** [comment]
Hello @enj , with the code freeze approaching, is this still on track for v1.25?

**Comment by aramase** [comment]
@markyjackson-taulia This PR will be superseded by https://github.com/kubernetes/kubernetes/pull/110011#issuecomment-1190836766. The new PR is in review and on track for v1.25.

@enj Can we close this PR?

**Comment by markyjackson-taulia** [comment]
Thank you @aramase

@enj can this be closed? If so, let me know or kindly close.

**Pull request closed without merging**
