### PR TITLE
Create README.md for noting hack/ future status

### PR DESCRIPTION
**Pull request by jayunit100**

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm. shippable is a flake.

**Comment by jlowdermilk** [comment]
Would like confirmation from @thockin and/or @bgrant0607 that we do actually plan to deprecate `hack/` at some point.

**Comment by thockin** [comment]
I'd certainly like to see it at least renamed - @bgrant0607 ?

**Comment by bgrant0607** [comment]
Why is this PR useful? It's certainly not actionable.

Is there an issue with a proposal? Could we put a proposal in this doc? For comparison, see #4851, which contains proposals for restructuring pkg/.

Could we at least explain what's currently in this directory in the README?

**Comment by bgrant0607** [comment]
Closing for now. Open an issue with a restructuring proposal if you'd like to discuss further.

**Pull request closed without merging**
