### PR TITLE
Automated cherry pick of #77661: Kubelet provides an updated and complete status of

### PR DESCRIPTION
**Pull request by mfpierre**
Cherry pick of #77661 on release-1.12.

#77661: Kubelet provides an updated and complete status of

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by feiskyer** [comment]
@Random-Liu @yujuhong Could you help to get this change approved?

Please notice that v1.12.10 will be the last patch release for 1.12 branch. If you think this change is reasonable, please get it merged at the end this Friday (June 28).

**Comment by bzuelke** [comment]
It would be awesome to get this in for the next cut of k8s 1.12, super needed for monitoring.

**Comment by feiskyer** [comment]
Sorry, this cherry pick hasn't approved before the deadline, and the branch-1.12 would be deprecated after next Monday's release.

/close

**Pull request closed without merging**
