### PR TITLE
Remove support for etcd2 from cluster/images/etcd image

### LINKED ISSUE #80036: Remove support for etcd2 from cluster/images/etcd image
Follow up from a previously abandoned PR:
https://github.com/kubernetes/kubernetes/pull/69577#issuecomment-428243906

```
These image also provides basic etcd 3.x minor version downgrade support which is still needed.

We should strip out the etcd2 support instead of deleting this entirely.
```

### PR DESCRIPTION
**Pull request by dims**
Removes etcd2 code and images.
Etcd2 is no longer supported as of 1.13, so rollback and management
tools for etcd2 should not be shipped any longer. If it is still desired
the older versions of the image can be used.

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #80036

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
etcd migration image no longer supports etcd2 version. 
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @jpbetz @liggitt 
cc @wenjiaswe @wojtek-t

**Comment by liggitt** [comment]
/approve

@jpbetz has lgtm

**Comment by wojtek-t** [comment]
LGTM, but I will let @jpbetz to finally lgtm it.

**Comment by jingyih** [comment]
Do we still need the upgrade and downgrade tests that involve etcd2?

https://github.com/kubernetes/kubernetes/blob/318288dae6b0d38b04b5998823543dd9eb1afa2a/cluster/images/etcd/migrate/integration_test.go#L56-L57

https://github.com/kubernetes/kubernetes/blob/318288dae6b0d38b04b5998823543dd9eb1afa2a/cluster/images/etcd/migrate/integration_test.go#L64-L65

**Comment by dims** [comment]
@jingyih fixed. PTAL

**Comment by jingyih** [comment]
lgtm. Thanks!

**Comment by dims** [comment]
@jpbetz @roycaihw can you please `/lgtm` based on the `lgtm` from @jingyih above?

**Pull request merged**
