### PR TITLE
adding support for container.name in downward api

### PR DESCRIPTION
**Pull request by byxorna**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Adds the ability to use the Downward API to inject the `container.name` into a container via ResourceFieldRef. Adding the ability for a container to discover its name through the downward API allows operators to write automation that is aware of where it is running within a Pod.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

Thanks for taking a look at this tiny PR!

**Does this PR introduce a user-facing change?**:

This updates the Downward API with a new field - documentation will need to be updated to accomodate.

### CODE REVIEW

**Comment by matthyx** [comment]
@byxorna can you add a release note, and make a PR to kubernetes/website to document that new field?

**Comment by liggitt** [comment]
/hold

This is introducing an API change to a stable API. This generally requires a [proposal justifying the change](https://github.com/kubernetes/enhancements/tree/master/keps/), and details about how it will be rolled out safely. It would also be good to explain why this is necessary instead of the container name in the envvar or args.

At a minimum, validation-impacting changes need to be rolled out over two releases so that a version N-1 API server does not consider data allowed in by a version N API server to be invalid.

**Comment by byxorna** [comment]
@matthyx Sure thing, I can do that no problem. However, I will address @liggitt's concerns first.

@liggitt thank you for chiming in. I am unsure I follow your comment below:
> It would also be good to explain why this is necessary instead of the container name in the envvar or args.
Unless I have missed another way, this PR seems to be the only way to configure a container to inspect its container's name in k8s without manually setting an environment variable in each container.

Additionally, re: your comment
> At a minimum, validation-impacting changes need to be rolled out over two releases so that a version N-1 API server does not consider data allowed in by a version N API server to be invalid.
This change add to the downward API, and does not remove/change any existing functionality. Does that require a KEP? How would you propose going forward with this small change?

Some background which may help clarify my usecase: 

I built a k8s-aware container init system that run in each container in a pod. Each instance of this tool knows about a global DAG of startup/shutdown dependencies (identified within the DAG by container name) in this Pod. Each instance also needs to be able to identify itsself within the DAG ( by container name). A possible solution, albeit one that requires much container-specific configuration, is to manually parameterize this tool with the name of the container it is running within. This, however, is error prone for operators. A more optimal solution would be to allow k8s to inject each container's name via the downward API into each container that requests it, thus removing any specific pod-topology-awareness from this tool's launch parameters.

I am very open to suggestions for how I should proceed next. Thanks!

**Comment by liggitt** [comment]
> Unless I have missed another way, this PR seems to be the only way to configure a container to inspect its container's name in k8s without manually setting an environment variable in each container.

Is there a reason setting the name in the invocation or in an envvar is burdensome?

> This change add to the downward API, and does not remove/change any existing functionality. Does that require a KEP? How would you propose going forward with this small change?

It changes the API surface by allowing additional values in downward API fields, which requires a proposal. The proposal doesn't need to be extensive, but clear justification for the addition, rationale why the simpler alternatives are not sufficient, and a description of the multi-release rollout of relaxed API validation are among the things that should be considered and described.

> A more optimal solution would be to allow k8s to inject each container's name via the downward API into each container that requests it, thus removing any specific pod-topology-awareness from this tool's launch parameters.

A container name must already be selected when generating the container stanza for the pod spec. Is there a reason placing the container name in an envvar as part of that generation is problematic?

**Pull request closed without merging**
