### PR TITLE
contrib: add go2docker

### PR DESCRIPTION
**Pull request by proppy**
yet another random contribution to contrib.

`go2docker` is a command line tool to create minimal docker images from `SCRATCH` for go packages

```
$ go get -d github.com/golang/example/hello
$ go2docker -image golang/hello github.com/golang/example/hello | docker load
$ docker images | grep hello
golang/hello       latest   e96b9f048cdf            2 seconds ago   1.477 MB
$ docker run golang/hello
Hello, Go examples!
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Very cool

**Comment by thockin** [comment]
This is a really cute hack, but we're not using it anywhere in kubernetes
and it is not kubernetes specific.  Should it be hosted in this repo?

**Comment by proppy** [comment]
@thockin @dchen1107 and @bgrant0607 were thinking it might be useful to run etcd in a pod.

**Comment by thockin** [comment]
Can we sit on this PR until we have a clearer picture of what we want to do
with etcd?  It's a cute idea..

**Comment by bgrant0607** [comment]
@thockin I suggested we host it, for lack of a better place. It may be useful for Dockerizing etcd and/or kubernetes components. We can always remove it later if it turns out not to be useful.

**Comment by proppy** [comment]
Tested with etcd:
```
proppy@noir:~/src/github.com/GoogleCloudPlatform/kubernetes/contrib/go2docker$ go2docker github.com/coreos/etcd | docker load
proppy@noir:~/src/github.com/GoogleCloudPlatform/kubernetes/contrib/go2docker$ docker images | grep go2docker/etcd
go2docker/etcd                                    latest              803f86b03990        6 seconds ago       9.629 MB
proppy@noir:~/src/github.com/GoogleCloudPlatform/kubernetes/contrib/go2docker$ docker run go2docker/etcd
2015/01/30 08:18:14 no data-dir provided, using default data-dir ./default.etcd
2015/01/30 08:18:14 etcd: listening for peers on http://localhost:2380
2015/01/30 08:18:14 etcd: listening for peers on http://localhost:7001
2015/01/30 08:18:14 etcd: listening for client requests on http://localhost:2379
2015/01/30 08:18:14 etcd: listening for client requests on http://localhost:4001
```

**Comment by proppy** [comment]
I wonder if https://github.com/docker/distribution could also be a home for it, along with the registry client that @smarterclayton is working on.

A collection of standalone tools for working with docker images seems desirable for me, maybe we could incubate them inside c ontrib and externalize them if they prove generally useful.

**Comment by bgrant0607** [comment]
We're going to try to use this to Dockerize etcd and possibly the master components.

cc @dchen1107 @ArtfulCoder

**Comment by dchen1107** [comment]
We planned to try go2docker to build our own etc_server image, and push to master node since the final size looks like smaller. But @thockin just mentioned that we could build image based on 0 byte docker image called scratch, which means we could have image same size as etcd binary itself.

**Comment by proppy** [comment]
@dchen1107: yes that's basically what `go2docker` is doing :)

**Comment by bgrant0607** [comment]
Merging to make it easier to play with. We can always remove it later if we decide not to use it.

**Pull request merged**
