### PR TITLE
Automated cherry pick of #35136

### PR DESCRIPTION
**Pull request by jessfraz**
Cherry pick of #35136 on release-1.4.
#35136: updated cadvisor godeps

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35736)

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by jessfraz** [comment]
this is running into the same problems as https://github.com/kubernetes/kubernetes/pull/33806 ping @vishh @timstclair should we just update the transitive dependencies too like cloud.google.com/go?

**Comment by timstclair** [comment]
There are a bunch of problems with this PR, and it can't be cherrypicked as is. Kubernetes master is tracking cAdvisor master, which has diverged from the cAdvisor v0.24 release branch (which is what k8s 1.4 tracks). That's why verify godeps is failing, since the changes in this PR don't include all the other changes in that cAdvisor hash.

Possible resolutions:

1. Continue off the cAdvisor v0.24 branch:
  1. Cherrypick the desired changes from cAdvisor master to the cAdvisor v0.24 branch
  2. Tag the cAdvisor v0.24 branch as `v0.24.2`
  3. Sync k8s 1.4 to cAdvisor v0.24.2, which would mean merging https://github.com/kubernetes/kubernetes/pull/33806, and all the transitive godep updates that PR pulls in
2. Create a new cAdvisor branch
  1. Create a cAdvisor branch from the `v0.24.0` tag (which k8s 1.4 tracks). Call it something like "kubernetes-1.4"
  2. Cherrypick the desired changes into that branch.
  3. Tag it with something sane (`v0.24.0-k8s1.4.XX`)
  4. Update the k8s 1.4 branch godeps to the new cAdvisor branch

Based on the lack of progress on https://github.com/kubernetes/kubernetes/pull/33806, it seems like the second option might be the way to go...

**Comment by jessfraz** [comment]
Number 2 sounds good, does this need to be in 1.4.5 @vishh ? Or can it wait
til we do this, if it's a super priority then maybe number 1 is better

On Oct 27, 2016 17:37, "Tim St. Clair" <notifications@github.com> wrote:

There are a bunch of problems with this PR, and it can't be cherrypicked as
is. Kubernetes master is tracking cAdvisor master, which has diverged from
the cAdvisor v0.24 release branch (which is what k8s 1.4 tracks). That's
why verify godeps is failing, since the changes in this PR don't include
all the other changes in that cAdvisor hash.

Possible resolutions:

   1. Continue off the cAdvisor v0.24 branch:
      1. Cherrypick the desired changes from cAdvisor master to the
      cAdvisor v0.24 branch
      2. Tag the cAdvisor v0.24 branch as v0.24.2
      3. Sync k8s 1.4 to cAdvisor v0.24.2, which would mean merging #33806
      <https://github.com/kubernetes/kubernetes/pull/33806>, and all the
      transitive godep updates that PR pulls in
   2. Create a new cAdvisor branch
      1. Create a cAdvisor branch from the v0.24.0 tag (which k8s 1.4
      tracks). Call it something like "kubernetes-1.4"
      2. Cherrypick the desired changes into that branch.
      3. Tag it with something sane (v0.24.0-k8s1.4.XX)
      4. Update the k8s 1.4 branch godeps to the new cAdvisor branch

Based on the lack of progress on #33806
<https://github.com/kubernetes/kubernetes/pull/33806>, it seems like the
second option might be the way to go...

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/35736#issuecomment-256807793>,
or mute the thread

**Comment by timstclair** [comment]
Whichever solution we decide to go with, let me know tomorrow and I can handle the cAdvisor cherry picks / branching / tagging.

> There are a bunch of problems with this PR

Sorry, that sounded more harsh than I intended. I just meant that this won't work as a cherrypick from k8s master, it needs to be a new PR.

**Comment by jessfraz** [comment]
Option number 2 is ok with me and thanks for doing that!

**Comment by timstclair** [comment]
@dashpole @vishh - Which cAdvisor commits need to be cherrypicked?

**Comment by dashpole** [comment]
@timstclair just this one.  https://github.com/google/cadvisor/pull/1503/files

**Pull request closed without merging**
