### PR TITLE
 pkg/volume/portworx: use libopenstorage/openstorage v2.0.0

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
update the vendored dependency of libopenstorage/openstorage to a tagged release v2.0.0.
this affects the volume/portworx volume driver with minor API changes.

it seems the SHA that we used (093a0c388875) was in between API refactor. v2.0.0 introduces options for a number of API calls.

**Which issue(s) this PR fixes**:

part of: https://github.com/kubernetes/kubernetes/issues/79234
xref: https://github.com/kubernetes/kubernetes/issues/80029

**Special notes for your reviewer**:
- First commit - update the deps.
- Second commit - apply minor API changes. see commit description.

let me know if no need for a release note.

**Does this PR introduce a user-facing change?**:

```release-note
update portworx volumes to use libopenstorage/openstorage v2.0.0
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @dims
@kubernetes/sig-storage-pr-reviews 
/kind cleanup
/sig storage
/priority important-longterm
/area code-organization

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @adityadani 
from https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/portworx/OWNERS

**Comment by jsafrane** [comment]
/assign @lpabon 
@lpabon, do you have anyone on your end to review this?

**Comment by adityadani** [comment]
@neolit123 We do not want the vendor'ed openstorage in Kubernetes to move to v2.0.0 yet.

Was the motivation for this PR to change the vendor from a sha to a tag?

In that case we will like to tag openstorage repo at the current sha and then vendor that tag into kubernetes.

**Comment by neolit123** [comment]
> Was the motivation for this PR to change the vendor from a sha to a tag?

yes.

> @neolit123 We do not want the vendor'ed openstorage in Kubernetes to move to v2.0.0 yet.

could you explain the reasoning behind that? the current SHA that is used seems to be in between API refactors, which is quite odd. 2.0.0 introduces consistency as far as what arguments the API calls accept.

> In that case we will like to tag openstorage repo at the current sha and then vendor that tag into kubernetes.

i guess i have the same question here. this needs explanation - what is so special about the current SHA. does v2.0.0 introduce breaking changes? why is the k/k portworx driver stuck at a such an old version of the openstorage backend?

**Comment by neolit123** [comment]
@adityadani also please take a look at https://github.com/kubernetes/kubernetes/issues/80312

**Comment by lpabon** [comment]
As the maintainer of this code I would like not to add this change. There is no requirement to move the code to 2.0.0 tag. 

We need to focus on the real requirement is, which I think it has to do with moving to go modules. I spoke yesterday with @dims where we thought this required more discussion.

If you want I am welcome to discuss this at the next storage-sig meeting.

Luis

**Comment by neolit123** [comment]
So there is no technical requirement to stay on the commit, or at least i'm
not seeing a meaningful response about this thus far. I find it really odd
to tag this commit specifically for the sake of not moving to an actual
release tag.

Is this only done to rebel against the k8s vendor policy or is there
something else at play here?

Also if you are this driver's maintainers please become members of the k8s
org and add your names to the owners file.

**Comment by neolit123** [comment]
@cblecker PTAL at this dep/tag related discussion.

**Comment by cblecker** [comment]
So the content of the PR actually looks fine to me. That said, I'm curious as to why we shouldn't move to this. Is there functionality that we shouldn't bring in yet?

/hold
for discussion

**Review by lpabon — CHANGES_REQUESTED** [review]

**Comment by neolit123** [comment]
@lpabon 

if you are the unofficial maintainer of this volume driver, by not answering the fairly reasonable questions asked on this PR by contributors of the Kubernetes project, you are violating the [CNCF Code of Conduction](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) due to unethical behavior.

see:
https://github.com/cncf/foundation/blob/master/code-of-conduct.md
> Other unethical or unprofessional conduct.
https://en.wikipedia.org/wiki/Evasion_(ethics)#Question_dodging

given both you and @adityadani are not members of the Kubernetes and Kuberentes-Sigs organizations and correctly defined in the OWNERS file for this driver, i'm inclined to direct the decision making for this change to SIG-Storage tech leads and OWNERS from the parent directory such as @msau42 and @saad-ali.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by lpabon** [comment]
@neolit123 

Hi, no offense was intended and I apologize if any was given.

Let's try this another way.

We do not want to destabilize the code by upgrading it if there is no requirement to do this.

What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

**Comment by neolit123** [comment]
> What is the requirement we are trying to satisfy? If it is to setup a tag, we can provide a tag to match the hash value.

the requirement, as defined by the SIG Architecture code-organization sub-project, is to move vendored libraries to a tagged releases. artificially tagging a commit to comply with this requirement is undesired.

> We do not want to destabilize the code by upgrading it if there is no requirement to do this.

it has been the practice for other vendored libraries already and libopenstorage/openstorage is creating a precedent. ideally, the closes release tag (`v2.0.0`) should be applied and if e2e tests start failing we can revert and rethink the situation.

i can personally invest the time to apply the potential revert and monitor the e2e signal.

**Comment by saad-ali** [comment]
I'm setting up a meeting to discuss what's going on with this PR. Meeting at 2:30 PM PT, 5:30 PM ET today (about 40 min from now). If you want an invite, please email me.

**Comment by dims** [comment]
Several things here. let me enumerate before the call for anyone following along.

none-code-related stuff:
- We need to fix OWNERS file with who ever owns the code
- We need to invite folks who will be in OWNERS files to the kubernetes github org (follow normal process)

code-related-stuff:
- `libopenstorage/openstorage` is EXTREMELY stale. Can we agree on this?
- We are *NOT* asking for a fresh release or tag of `libopenstorage/openstorage`
- No one is trying to place un-necessary burden on developers in `libopenstorage/openstorage` 
- There is a version/tag of  `libopenstorage/openstorage` that is extremely close to what is being used.
- I cannot understand why we would not want to adopt that tag. Reasons would be extremely helpful. 
- There is NO CI AFAICT. Please correct me if i am wrong.
- There is hardly any traffic loooking at the git history for the portworx plugin. Only updates are folks who have to fix things up in imports or whatever.
- Just to nail home the staleness, the closest tag is v2.0.0, this repo has gone all the way to v8.0.0. List of changes to master is [here](https://github.com/libopenstorage/openstorage/compare/093a0c388875...master). 

Why are we not updating this? There has to be a good reason. other than "there is no requirement". What is so special about this SHA?

**Comment by lpabon** [comment]
Results from the meeting:

1. Create a PR to add myself and @adityadani as OWNERS
1. Create a 1.0.0 tag in OpenStorage
1. Create a PR to update the go modules with the new tag
1. Start a conversation in SIG-Storage on how non-cloud storage vendors (NetApp, StorageOS, Portworx, Etc ) can do CI

**Comment by msau42** [comment]
Regarding 4), since 1.14, we have an [external storage test suite](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external) that various vendors are using to test CSI drivers outside of k/k.  The test framework is actually not specific to CSI; it works for in-tree volume types too.  I can present/demo this at the next sig-storage meeting.

**Comment by saad-ali** [comment]
Thanks @lpabon and everyone for jumping on the call on such short notice.

To make sure everyone understands the "why" behind each action items:

1. @lpabon and @adityadani will a) join k8s org if they are not already members and b) add themsleves as OWNERS for the portworx in-tree volume plugin.
    * This will enable Portworx to review and approve changes to their volume plugin in the future.
2. @lpabon @adityadani will create a new tag of `1.0` tag of `libopenstorage/openstorage` and will help update this PR to point to that tag.
    * This will unblock this PR and the wider `Update vendored dependencies to a released version` project by effectively resulting in no change and working around the concern Portworx has around making a potentially destabilizing change to their in-tree volume plugin.
3. @lpabon @adityadani @neolit123 Create a new PR (or update this one) to point the `libopenstorage/openstorage`  dependency to the new tag
3. @lpabon and/or @adityadani will look in to adding k8s tests that run on Portworx infrastructure to validate changes made to the k8s in-tree portworx volume plugin.
    * This will enable changes future changes to be made to the in-tree Portworx volume plugin without fear of breaking customers. As @msau42 mentioned external-storage test suite can be used to run tests against both in-tree and CSI drivers. SIG Test can provide infromation on on how to report those results back to k8s.

Thank you @dims and @neolit123 for the all your work in improving Kubernetes code stability. And thank you @lpabon and @adityadani for working with the community help maintain the high bar.

**Comment by neolit123** [comment]
@saad-ali 
thank you for stepping in and putting your signature on the new v1.0.0 tag for libopenstorage.

> I'm setting up a meeting to discuss what's going on with this PR

i'm sorry but that meeting was well past midnight for me, so i could not attend.

@lpabon @adityadani
please comment on this PR once the v1.0.0 tag is up and i will update the PR.

thanks.

**Comment by adityadani** [comment]
> Thanks @lpabon and everyone for jumping on the call on such short notice.
> 
> To make sure everyone understands the "why" behind each action items:
> 
> 1. @lpabon and @adityadani will a) join k8s org if they are not already members and b) add themsleves as OWNERS for the portworx in-tree volume plugin.
>    
>    * This will enable Portworx to review and approve changes to their volume plugin in the future.
> 2. @lpabon @adityadani will create a new tag of `1.0` tag of `libopenstorage/openstorage` and will help update this PR to point to that tag.
>    
>    * This will unblock this PR and the wider `Update vendored dependencies to a released version` project by effectively resulting in no change and working around the concern Portworx has around making a potentially destabilizing change to their in-tree volume plugin.
> 3. @lpabon @adityadani @neolit123 Create a new PR (or update this one) to point the `libopenstorage/openstorage`  dependency to the new tag
> 4. @lpabon and/or @adityadani will look in to adding k8s tests that run on Portworx infrastructure to validate changes made to the k8s in-tree portworx volume plugin.
>    
>    * This will enable changes future changes to be made to the in-tree Portworx volume plugin without fear of breaking customers. As @msau42 mentioned external-storage test suite can be used to run tests against both in-tree and CSI drivers. SIG Test can provide infromation on on how to report those results back to k8s.
> 
> Thank you @dims and @neolit123 for the all your work in improving Kubernetes code stability. And thank you @lpabon and @adityadani for working with the community help maintain the high bar.

To address action items 2 and 3, I have raised the following PR #80495
This PR also partially addresses action item 1.
@lpabon  and I will start looking out for sponsors to get ourselves added to the k8s org.

**Comment by neolit123** [comment]
> I have raised the following PR #80495

the above PR now has the update for the tag.
thanks.

/close

**Pull request closed without merging**
