### PR TITLE
fixup godep

### PR DESCRIPTION
**Pull request by deads2k**
I applied the patch I got from `hack/verify-godeps.sh`.

@derekwaynecarr @smarterclayton This is blocking the queue.  Can you manually confirm?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33683)

### CODE REVIEW

**Comment by deads2k** [comment]
Size XS is neat.  What's 15 thousand lines between friends....

**Comment by eparis** [comment]
merged by hand to unblock queue

**Comment by mikedanese** [comment]
@eparis please ping @k8s-oncall on these.

**Comment by mikedanese** [comment]
How are both of these commits now in master?
https://github.com/kubernetes/kubernetes/commit/589d70f495cc64bd3925f27b4eb0acfa0f0a80af
https://github.com/kubernetes/kubernetes/commit/8b56981e0ef3a56e41086dbf580e9286f18d551f

**Comment by eparis** [comment]
Why wouldn't they be? They came from a different starting point, they don't conflict...

**Pull request merged**
