### PR TITLE
cluster addons: fluentd-elasticsearch: update gems.

### PR DESCRIPTION
**Pull request by desaintmartin**
/kind flake

**What this PR does / why we need it**:

cluster add-ons: fluentd: update gems.

In particular, update fluent-plugin-kubernetes_metadata_filter to 2.4.5 to solve a potential high apiserver request count.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by desaintmartin** [comment]
Could someone review? This should solve a high apiserver requests issue described at https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/213

Maybe @coffeepac ?
/assign @coffeepac

**Comment by coffeepac** [comment]
@desaintmartin apologies for the delay!   thanks for the patch! 

/approve

**Pull request merged**
