### PR TITLE
fixed typos in kubectl book

### LINKED ISSUE #732: Kubectl Book: typos
There are typos.
https://kubectl.docs.kubernetes.io/pages/kubectl_book/resources_and_controllers.html

> ReplicaSet Controller creates/delete**s** Pods
> Node (Controller) runs Containers specifi**e**d in Pods on the Node

### PR DESCRIPTION
**Pull request by oke-py**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Fixed typos.
https://kubectl.docs.kubernetes.io/pages/kubectl_book/resources_and_controllers.html

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubectl#732

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oke-py** [comment]
Test failure may not be due to this PR.
/retest

**Comment by oke-py** [comment]
I got `lgtm` and `approved` but this PR isn't merged. I don't know why.

**Comment by apelisse** [comment]
Everything's good, you can see the status of the merge robot at [prow.k8s.io/tide](prow.k8s.io/tide)

**Comment by oke-py** [comment]
@apelisse I'm not sure what I should check at prow.k8s.io/tide.
As time passes, this will be merged? In other words, I don't have to do anything?

**Comment by apelisse** [comment]
The website shows your PR as "Queued for retest", which means it's going to get merged eventually. You can work on something else now ;-)

**Comment by oke-py** [comment]
I got it, thanks!

**Pull request merged**
