### PR TITLE
Automated cherry pick of #112243: Revert "Remove unused flags from kubectl run"

### PR DESCRIPTION
**Pull request by brianpursley**
Cherry pick of #112243 on release-1.25.

#112243: Revert "Remove unused flags from kubectl run"

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.25 regression where unused flags in the `kubectl run` command were removed before going through the required deprecation period.
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
@kubernetes/release-managers for cherry-pick approval

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
