### PR TITLE
Remove apps/v1beta1 & apps/v1beta2 from client-go

### LINKED ISSUE #96104: Drop deprecated beta workload APIs in client-go
**What would you like to be added**:

As deprecated beta workload APIs  are dropped serving since 1.16, should we drop support in client-go ?

xref: https://github.com/kubernetes/kubernetes/pull/70672

**Why is this needed**:

### PR DESCRIPTION
**Pull request by victor-timofei**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #96104

**Special notes for your reviewer**:
Still a work in progress, there are some failing tests.

**Does this PR introduce a user-facing change?**:

```release-note
Drop support for apps/v1beta1 & apps/v1beta2 in client-go
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
should we also drop the listers/informers/clients for the extensions/v1beta1 types for these?

/unassign
/assign sttts

**Comment by sttts** [comment]
Do we have a decision on when we remove support in client-go? Obviously, it might make sense to keep the client support longer than in the server for version skew reasons.

**Pull request closed without merging**
