### PR TITLE
Adds kubectl logo images

### PR DESCRIPTION
**Pull request by seans3**
* Adds kubectl logo image (in .png format)
* Adds three different sizes of the image

/kind cleanup
/area kubectl
/sig cli

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
Would be cool to fix the logo in the README as well: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl#kubectl :heart_eyes:

**Comment by seans3** [comment]
> Would be cool to fix the logo in the README as well: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl#kubectl

This PR fixed that issue as well :)

**Pull request merged**
