### PR TITLE
Azure API updates

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind feature

**What this PR does / why we need it**:
- Update azure-sdk-for-go/services/containerregistry to 2018-09-01
- Update azure-sdk-for-go/services/network to 2018-08-01

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Azure API versions (containerregistry --> 2018-09-01, network --> 2018-08-01)
```

### CODE REVIEW

**Comment by feiskyer** [comment]
The changes looks good, let's check what CI would report.

**Comment by justaugustus** [comment]
(Can't tell if this is a flake or not)
/test pull-kubernetes-e2e-aks-engine-azure

**Comment by justaugustus** [comment]
Actually, this job seems to fail pretty consistently on that `Up` step: https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure
We should look into it, but not block on it here.

**Comment by justaugustus** [comment]
Created #79597 to investigate the `pull-kubernetes-e2e-aks-engine-azure` failure.

**Comment by justaugustus** [comment]
For deps:
/assign @cblecker @dims @BenTheElder

**Comment by feiskyer** [comment]
The failure is not related to this change, need to investigate why it's failing again.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Review by BenTheElder — APPROVED** [review]
/approve
for vendor

**Comment by BenTheElder** [comment]
/hold
do we care about the optional e2e failure?
unhold if not :-)

**Comment by justaugustus** [comment]
@BenTheElder -- nope, but thanks for checking! I've opened https://github.com/kubernetes/kubernetes/issues/79597 to track that.
/hold cancel

**Comment by BenTheElder** [comment]
clearing it to make the bots go away :upside_down_face: 
/skip
[may need to be done again when the failure comes back in, but before the bot comments again..]

**Pull request merged**
