### PR TITLE
Use the new name for cassandra-statefulset.yaml in e2e tests.

### LINKED ISSUE #36323: [k8s.io] [Feature:Example] [k8s.io] CassandraStatefulSet should create statefulset {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17200/

Failed: [k8s.io] [Feature:Example] [k8s.io] CassandraStatefulSet should create statefulset {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:317
Expected error:
    <*os.PathError | 0xc420cbd920>: {
        Op: "open",
        Path: "/workspace/kubernetes/examples/storage/cassandra/cassandra-petset.yaml",
        Err: 0x2,
    }
    open /workspace/kubernetes/examples/storage/cassandra/cassandra-petset.yaml: no such file or directory
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:257
```

### PR DESCRIPTION
**Pull request by jimmycuadra**
Fixes #36323.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36418)

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Test failure looks unrelated. Flake?

**Comment by foxish** [comment]
@k8s-bot unit test this

**Comment by foxish** [comment]
@k8s-bot cvm gce e2e test this

**Comment by janetkuo** [comment]
P0 for fixing flakes

**Pull request merged**
