### PR TITLE
fix style of yaml and text

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
The original format is very odd. So I try to fix it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
before:
image

after:
image

**Comment by zhangxiaoyu-zidif** [comment]
cc @luxas

**Comment by luxas** [comment]
I can approve based on a lgtm from @idvoretskyi

**Comment by luxas** [comment]
Thanks @idvoretskyi!
I added the approved label manually

**Pull request merged**
