### PR TITLE
Nominate Abdullah Gharaibeh to scheduler maintainers.

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
I would like to add myself as a reviewer of the scheduler pkg. I am familiar with the code base.

I was the primary reviewer for [three major scheduling features and the secondary for another one](https://github.com/kubernetes/kubernetes/pulls?page=1&q=is%3Apr+reviewed-by%3Aahg-g&utf8=%E2%9C%93).

1) Even pod spreading
2) Pod Overhead
3) Scheduling Framework
4) Scheduling based on capacity ratio of extended resources

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @bsalamat @Huang-Wei 
/sig scheduling

### CODE REVIEW

**Comment by Huang-Wei** [comment]
Throughout Abdullah's current contributions, he has shown his coding skills, comprehensive understanding on the codebase, good taste of code, giving suggestions and spotting issues upon reviewing.

I fully support promoting @ahg-g to be a sig-scheduling maintainer.

**Review by bsalamat — COMMENTED** [review]
+1
Given Abdullah's great engineering judgements and understanding of the code base, I support his nomination to be an approver.

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Review by Huang-Wei — COMMENTED** [review]
/approve no-issue

**Comment by ahg-g** [comment]
assign @liggitt

**Comment by liggitt** [comment]
/approve
per sig-scheduling leads

**Pull request merged**
