### PR TITLE
Automated cherry pick of #11622 #11865 upstream release 1.0

### LINKED ISSUE #12037: mark_new_version.sh STILL can't get past precommits on release-1.0 branch
This is still (now? still?) busted, and is a P(-1), because it's STILL blocking me from #11941. Please, please, can we get the docs working on the release branch?

```
+++ [0730 13:03:26] Building apiserver
+++ [0730 13:03:26] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [0730 13:03:34] Placing binaries
etcd -data-dir /tmp/test-etcd.TQhhZC --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null
Waiting for etcd to come up.
+++ [0730 13:03:36] On try 1, etcd: : 
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0730 13:03:37] Starting kube-apiserver
+++ [0730 13:03:37] On try 2, apiserver: : ok
+++ [0730 13:03:37] Updating 
    build/../hack/../api/swagger-spec
+++ [0730 13:03:37] SUCCESS
+++ [0730 13:03:38] Clean up complete
Checking that it builds... OK

Checking for files that need gofmt... OK

Checking for files that need boilerplate... OK

Checking for API descriptions... OK

Checking for docs that need updating... FAIL: changes needed but not made due to --verify
ERROR!
Some docs are out of sync between CLI and markdown.
To regenerate docs, run:
  hack/run-gendocs.sh

Checking for conversions that need updating... OK

Checking for deep-copies that need updating... OK

Checking for swagger spec that need updating... OK

Aborting commit
```

### PR DESCRIPTION
**Pull request by zmerlynn**
Having #11622 and #11865 in `release-1.0` makes the diff in the `build/` dir smaller.

Fixes #12037

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @thockin @nikhiljindal

**Comment by nikhiljindal** [comment]
Thanks, LGTM

**Comment by zmerlynn** [comment]
Actually, after this cherry-pick, I'm able to run `build/versionize-docs.sh v1.0.1` and `git commit -am "Fixup v1.0.1"` passes precommits.

**Comment by zmerlynn** [comment]
(I tried it on the cherry-pick branch.)

**Comment by zmerlynn** [comment]
Though I can't say it actually looks right:

```
diff --git a/docs/devel/scheduler.md b/docs/devel/scheduler.md
index 68194ac..7fe6f5f 100644
--- a/docs/devel/scheduler.md
+++ b/docs/devel/scheduler.md
@@ -54,6 +54,11 @@ If you want to get a global picture of how the scheduler works, you can start in
 <!-- TAG IS_VERSIONED -->
 
 
+<!-- BEGIN MUNGE: IS_VERSIONED -->
+  <!-- TAG IS_VERSIONED -->
+  <!-- END MUNGE: IS_VERSIONED -->
+
+
```

That looks kind of .. stuttery.

**Comment by thockin** [comment]
Exactly.  give me a few to manually fix up.

**Comment by nikhiljindal** [comment]
That is right.
We can improve it, but thats how it is right now.

**Comment by zmerlynn** [comment]
Can this c-p go in?

**Comment by nikhiljindal** [comment]
Yes. Should be good to go.
Have added the LGTM tag.

**Comment by thockin** [comment]
I think there's a bug in the script, but I can fix that in a followup

**Comment by zmerlynn** [comment]
@thockin: Just fix it everywhere, plz. :)

**Comment by thockin** [comment]
NM, it's not a bug unless you cut-paste it to a commandline (a ! literal embedded in a double-quoted str)

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
Shippable has half-passed. Going ahead with this.

**Pull request merged**
