### PR TITLE
Clean up unit tests using FakeDockerClient

### PR DESCRIPTION
**Pull request by yujuhong**
Add a helper method to set the container map and list at the same time, without
having to specify them separately. This reduces the effort required for
adding/modifying tests as well as making the code more concise.

### CODE REVIEW

**Comment by Random-Liu** [comment]
Wow! Good idea! So that I can add default label in SetFakeDockers() now! :)

**Comment by yujuhong** [comment]
> Wow! Good idea! So that I can add default label in SetFakeDockers() now! :)

Yes, hopefully this would make changes to the docker-related code easier, without having to modify every single one of the tests!

**Comment by Random-Liu** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
