### PR TITLE
Automated cherry pick of #52367

### PR DESCRIPTION
**Pull request by tallclair**
Cherry pick of #52367 on release-1.8.

#52367: Basic GCE PodSecurityPolicy Config

Justification: this is only test & configuration changes. The configuration changes are required for enabling a beta feature on GCE environments.

```release-note
Add support for PodSecurityPolicy on GCE: `ENABLE_POD_SECURITY_POLICY=true` enables the admission controller, and installs policies for default addons.
```

### CODE REVIEW

**Comment by liggitt** [comment]
I expected the follow ups from the master PR to get resolved, so that optional add-ons worked as well, before picking this to a release branch

**Comment by liggitt** [comment]
Also, should update the specific 1.8 test infra jobs to enable this to ensure it is tested before release

**Comment by tallclair** [comment]
I sent https://github.com/kubernetes/test-infra/pull/5345 to enable testing in the 1.8 test suite. I agree we should enable testing prior to cherrypicking this, but I disagree that we should wait for the optional addon PSPs. I think it's valuable to start testing this now, as it should work with the default GCE config.

**Comment by tallclair** [comment]
Oh, this depends on https://github.com/kubernetes/kubernetes/pull/53034

**Pull request merged**
