### PR TITLE
Race condition between listener and client in remote_runtime_test

### LINKED ISSUE #58993: Race condition between listener and client in remote_runtime_test
A race condition between fakeremote.Start() is spawned as a goroutine to listen for connections, and its caller assumes that the listener will immediately be ready to accept connections.  This leads to intermittent test failures if the caller attempts before the fake remote runtime is ready to listen.  The code needs to be refactored so that the fake remote returns from listen, and then spawns the server as a goroutine and returns.

This can be reproduced by running the remote_runtime_test in a loop; it fails periodically.  Failure can be accelerated by putting a time.Sleep(1000*1000*1000) in fake.Start() immediately before the call to util.CreateListener; the failure is then effectively deterministic.

Fix tested by running about 150,000 iterations without observing any failures.

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Fix race condition in remote_runtime_test.
Fixes #58993

### CODE REVIEW

**Comment by sjenning** [comment]
/release-note-none
/ok-to-test
/assign derekwaynecarr
/sig node

@RobertKrawitz looks like you may have not pulled the latest master as a base for this change resulting in the immediate `needs-rebase` label being applied.

**Comment by sjenning** [comment]
Wow, didn't think ok-to-test would bypass needs-rebase as a test blocker.  Ignore the failures.  They are all due to needing to rebase.

**Comment by sjenning** [comment]
@RobertKrawitz almost there.  When you change the imports for a file, you typically have to run `hack/update-bazel` to update the metadata for the build system (bazel).  Just part of the Kubernetes PR incantation.

**Comment by sjenning** [comment]
Just to be clear, this only fixes the test segfaulting on `version` being nil resulting in a nil deref when trying to access the `version.Version`.  It does not fix the race.  Need to fix that in a follow on PR.

Looks like this
```
<autogenerated>:1: 
                          
	Error Trace:	remote_runtime_test.go:66
Error:      	Received unexpected error:
rpc error: code = Unavailable desc = grpc: the connection is unavailable
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17bcc91]

goroutine 20 [running]:
testing.tRunner.func1(0xc42060e0f0)
/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0x1904bc0, 0x24bfc70)
/usr/local/go/src/runtime/panic.go:491 +0x2a2
k8s.io/kubernetes/pkg/kubelet/remote.TestVersion(0xc42060e0f0)
/go/src/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime_test.go:67 +0x181
testing.tRunner(0xc42060e0f0, 0x1aec938)
/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:789 +0x569
FAIL k8s.io/kubernetes/pkg/kubelet/remote	0.646s
```

/lgtm

**Comment by sjenning** [comment]
Nevermind my previous comment.  The change executes `CreateListener()` synchronously and it creates the socket, not `Serve()`. This should fix all the issues.

**Comment by derekwaynecarr** [comment]
lgtm

/approve

**Pull request merged**
