### PR TITLE
Hooks cleanup

### PR DESCRIPTION
**Pull request by thockin**
Switch git hooks to use pre-commit, print progress.

### CODE REVIEW

**Comment by thockin** [comment]
Fixes #8160

**Comment by thockin** [comment]
@lavalamp @brendandburns

**Comment by lavalamp** [comment]
What does it look like when the hooks fail now?

**Comment by thockin** [comment]
@lavalamp pre-commit runs before editing the commit message, so you don't lose it as you were afraid of.

```
$ #make an edit to remove boilerplate
$ git commit -a
Checking for files that need gofmt... OK

Checking for files that need boilerplate... ERROR!
Some files are missing the required boilerplate header
from hooks/boilerplate.txt:
  test/e2e/events.go

Checking for API descriptions... OK

Checking for docs that need updating... OK
```

Was thinking of adding color - what think?

**Comment by lavalamp** [comment]
In that case-- LGTM

Color is fine with me :)

**Comment by thockin** [comment]
In that case, merge at will.

**Pull request merged**
