### PR TITLE
Revert "Updated golang/x/net. Also updated golang.org/x/sys"

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit ec6e2321261b900089183ac61f1ac0040be5fa9c.

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/retest
1 test failed in each job, I think that I saw them failing before, doesn't seem related

**Comment by spiffxp** [comment]
/test pull-kubernetes-node-e2e
oomkilled

**Comment by spiffxp** [comment]
/test integration
```
dryrun_test.go:165: failed to dry-run update resource: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "openshiftwebconsoleconfigs.webconsole.operator.openshift.io": the object has been modified; please apply your changes to the latest version and try again
    --- FAIL: TestDryRun/apiextensions.k8s.io/v1beta1,_Resource=customresourcedefinitions (0.05s)
```
/test pull-kubernetes-integration
```
==================== Test output for //staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource:go_default_test (run 1 of 2):
# ... snip ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a4a466]
```

**Comment by spiffxp** [comment]
/test pull-kubernetes-integration
same failure as before, but I have seen a successful pass against this commit in https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=96108 linked by k8s-ci-robot

can't find existing issues that indicate this is a known flake

**Pull request merged**
