### PR TITLE
Automated cherry pick of #79552: Add support for windows to AWS EBS

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #79552 on release-1.15.

#79552: Add support for windows to AWS EBS

### CODE REVIEW

**Comment by wongma7** [comment]
/cc @leakingtapan
cherry-pick of aws ebs on 1.15. will open one to fix 1.14 as well.

**Comment by leakingtapan** [comment]
@gnufied PTAL and needs your approval

**Comment by tpepper** [comment]
/kind feature
as per the master branch PR.  We don't backport features to the stable release branches.

**Comment by gnufied** [comment]
I think master branch PR was mis-tagged. We already support Windows and this PR actually fixes a bug.

**Comment by leakingtapan** [comment]
@tpepper If we are saying windows support is GA in 1.14. Then this is some bug that deserves fix, otherwise, EBS volume won't work for windows

**Comment by tpepper** [comment]
> @tpepper If we are saying windows support is GA in 1.14. Then this is some bug that deserves fix, otherwise, EBS volume won't work for windows

/area provider/aws

A feature that wasn't fully enabled/tested and is broken seems to me like a feature that hasn't yet been delivered.

@kubernetes/provider-aws-misc and @kubernetes/sig-storage-pr-reviews are ya'll sure this is a valid cherry pick?

**Comment by wongma7** [comment]
@jsafrane do you mind weighing in? If you could review to confirm that this change would only affect aws windows installations also.

**Comment by jsafrane** [comment]
I can confirm it fixes a bug on Windows and does not break Linux.

**Comment by tpepper** [comment]
I've confirmed with SIG Windows that this was a feature not included in the initial GA support, eg:
https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#storage

**Comment by wongma7** [comment]
No, it wasn't on anyone's map for the initial 1.14 release. But that nuance is lost to our users. All they see is their entire class of stateful workloads stuck ContainerCreating on windows, which I don't think is acceptable.

I understand that 'we don't backport features' is something of a rule, but changes to volume plugins blur the line between feature/bug. Differences between volume plugins are abstracted away from users by the PV/PVC API. Like, there is nothing preventing a user from creating a PVC in AWS the same way they do in GCE. Kubernetes components will even log that EBS is an enabled plugin. So users expect AWS EBS PVCs to work or at least to receive a sensible error message.

The change is isolated to the AWS plugin on windows and it doesn't work to begin with, I don't see how it could risk stability.

**Comment by tpepper** [comment]
Discussed with
/sig windows
and @kubernetes/patch-release-team and there is not support for merging this cherry pick.

**Comment by wongma7** [comment]
Thanks, appreciate your effort to reach out to stakeholders and hear our case @tpepper.

**Comment by wongma7** [comment]
Closing again--the behavior of unsupported/partially-supported/broken volume plugins is pretty unpleasant for users, but correcting it does not meet the bar for a "critical bug fix."

**Pull request closed without merging**
