### PR TITLE
auth/gcp: configurable scopes for gcp default credentials

### PR DESCRIPTION
**Pull request by ahmetb**
**What this PR does / why we need it**:

- add `config.scopes` field comma-separated scope URLs, to be used with Google
  Application Default Credentials (i.e. GOOGLE_APPLICATION_CREDENTIALS env)
- users now should be able to set a gserviceaccount key in GOOGLE_APPLICATION_CREDENTIALS
  env, craft a kubeconfig file with GKE master IP+CA cert and should be able to authenticate
  to GKE in headless mode _without requiring gcloud_ CLI, and they can now use the
  email address of the gserviceaccount in RBAC role bindings and _not use Google Cloud IAM at all._
- gcp default scopes now include userinfo.email scope, so authenticating to GKE
  using gserviceaccount keys can now be done without gcloud as well.
- since userinfo.email scope is now a default, users who have existing RBAC bindings
  that use numeric uniqueID of the gserviceaccount will be broken (this behavior was
  never documented/guaranteed). from now on email address of the service account
  should be used as the subject in RBAC Role Bindings.

**Release note**:
```release-note
Google Cloud Service Account email addresses can now be used in RBAC
Role bindings since the default scopes now include the "userinfo.email"
scope. This is a breaking change if the numeric uniqueIDs of the Google
service accounts were being used in RBAC role bindings. The behavior
can be overridden by explicitly specifying the scope values as
comma-separated string in the "users[*].config.scopes" field in the
KUBECONFIG file.
```

/assign @cjcullen 
/sig gcp

### CODE REVIEW

**Comment by ahmetb** [comment]
I think `type gcpAuthProvider` godoc in this file needs updating to talk about this new "scopes" field.
/hold

**Comment by cjcullen** [comment]
FYI @ericchiang 
This only applies to the "old" GCP auth-provider, not the command-based one.

**Comment by cjcullen** [comment]
Can you add a unittest that checks that:
1. No scopes in the gcpConfig produces a google.TokenSource with the correct default scopes.
1. The scopes in the gcpConfig are correctly passed into the google.TokenSource.
1. Scopes in a gcpConfig when useCmd is true results in an error.

**Comment by ahmetb** [comment]
@cjcullen Methods in `gcp.go` were not well testable. So I split it into multiple methods, and wrote tests for them.

Please take a look at ad4fdc7.

> 1. No scopes in the gcpConfig produces a google.TokenSource with the correct default scopes.

See `Test_parseScopes` method.

> 2. The scopes in the gcpConfig are correctly passed into the google.TokenSource.

I'm having trouble inspecting the google.TokenSource, as the method returns `oauth2.reuseTokenSource` which I cannot dig in without using reflection. But I'm now testing the parsing of scopes field. (see `func parseScopes`.)

> 3. Scopes in a gcpConfig when useCmd is true results in an error.

See `Test_tokenSource_cmdCannotBeUsedWithScopes` method.

**Comment by ahmetb** [comment]
@cjcullen test above is flaky but I think it's unrelated. This should be ready to review. Apologies I had to refactor a larger chunk to get the tests done but I think it makes the code better for the future.

**Comment by cjcullen** [comment]
I like the refactor.
/lgtm

**Comment by ahmetb** [comment]
/approve no-issue
(if it doesn't work for me can someone else do it?)

**Comment by mattnworb** [comment]
For anyone else who finds this in the future and is confused like me as to how some gserviceaccount's can successfully be referred to in a `RoleBinding` before this change and some other's can't, I've traced it down to this:

if you use `gcloud container clusters get-credentials` to populate the KUBECONFIG with credentials related to the service account configured in `gcloud`, then if that service account was added to `gcloud` via `gcloud auth activate-service-account`, then the token returned by gcloud seems to already have access to the `userinfo.email` scope. This then allows the token passed by kubectl to a GKE cluster to have the email retrieved for it, which allows the token to be correlated to a gserviceaccount email address in your `RoleBinding`.

If instead the active service account in `gcloud` is the GCE instance's default service account, this does not have access to the `userinfo.email` scope, so the `RoleBinding` (today, before this PR) has to refer to the numeric ID (which can be found via `gcloud iam service-accounts describe <email/ID>`).

**Comment by mattnworb** [comment]
also - @ahmetb thanks for making the behavior consistent going forward 😄

**Comment by ahmetb** [comment]
@mattnworb thanks for the clarification!

Yes, if your [Cluster]RoleBinding object previously used a subject name like `105883778249443408408`, starting from kubectl 1.10, you just need to use the full service account email `foo@PROJECT-NAME.iam.gserviceaccount.com`.

This is a breaking change, if it interrupts you, you can go back to using kubectl 1.9 (or you can use `~/.kube/config` file to manually add a `users[*].config.scopes` field that has value `"https://www.googleapis.com/auth/cloud-platform"`. This way the email won't work and you'll get the old behavior.

The numeric account name behavior was never documented and meant to be used that way, so hopefully addressing this early on before this use case gets popular will prevent us from dealing with this down the road!

**Pull request merged**
