### PR TITLE
k8s.io/code-generator: hide gen test output from go tools

### PR DESCRIPTION
**Pull request by sttts**
The underscore in front of _test makes the go tools (including godep) to
ignore those packages by default. We do not want to create dependencies
to client-go and friends through the _test output.

### CODE REVIEW

**Comment by sttts** [comment]
@mikedanese any idea which the _test packages shows up again in the BUILD file? Where is the vendor_targets list coming from?

```
 W0919 12:11:33.728] ERROR: /go/src/k8s.io/kubernetes/pkg/generated/openapi/BUILD:8:1: no such package 'vendor/k8s.io/code-generator/_test/apis/testgroup/v1': BUILD file not found on package path and referenced by '//pkg/generated/openapi:go_default_library'.
```

**Comment by mikedanese** [comment]
looks like you got it sorted.

**Comment by sttts** [comment]
@mikedanese yes. Looks like the package is included in the list as soon as kazel sees the `+k8s:openapi` tag, even though it was set to `false`. I had to remove the whole tag. We might want to readd it again to have an openapi example. Can we switch kazel to look at the value? Or even to exclude underscore packages?

**Pull request merged**
