### PR TITLE
Manual cherry pick of #90927: remove oom TestStartingWatcher ""unit"" test

### PR DESCRIPTION
**Pull request by spiffxp**
Manual cherry pick of #90927 on release-1.17.

#90927: remove oom TestStartingWatcher ""unit"" test

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

NOTE: This had to be a manual "cherry-pick" because the test went by a different name on this branch, `TestBasic` instead of `TestStartingWatcher`.  It also turned out to be the only test in `oom_watcher_linux_test.go`, so I opted to delete the file.

### CODE REVIEW

**Comment by spiffxp** [comment]
/release-note-none
/priority critical-urgent
Fixes https://github.com/kubernetes/test-infra/issues/18652#issuecomment-683186101

**Comment by spiffxp** [comment]
/cc @liggitt @dashpole 
for the /approve since you were involved with https://github.com/kubernetes/kubernetes/pull/90927

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
no objections to picking this test-only change if it's causing issues

/approve

**Comment by matthyx** [comment]
@justaugustus can you approve the cherry pick, pls?

**Comment by spiffxp** [comment]
FYI @kubernetes/release-managers

**Comment by justaugustus** [comment]
Bah, we missed a kind label on this
/kind cleanup

**Pull request merged**
