### PR TITLE
Remove dockershim comments in kubelet

### PR DESCRIPTION
**Pull request by yanghesong**
Remove dockershim comments in kubelet
Signed-off-by: yanghesong <hesong.yang@foxmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove dockershim comments in kubelet.
Refs kubernetes/enhancements#2221
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
NOTE: just comments are updated in this PR

**Review by endocrimes — APPROVED** [review]
/lgtm
/test pull-kubernetes-e2e-kind-ipv6

**Pull request merged**
