### PR TITLE
e2e: external snapshotter

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

The recently introduced support for testing an external storage driver (PR #72836) had code for testing snapshotting, but that code turned out to be faulty:
- drivers which supported snapshotting skipped a test that should have run
- snapshotting failed because the  snapshotter name was wrong

With this PR, the kubernetes-csi CI script runs the snapshotting test successfully.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig storage
/assign @msau42 
/priority important-soon

### CODE REVIEW

**Comment by pohly** [comment]
@kubernetes-milestone-maintainers: can you add the 1.14 milestone tag for this PR?

It's a fix for a test that is not used at the moment in Kubernetes itself, so changes to this code can't break anything.

**Comment by pohly** [comment]
@kubernetes/kubernetes-milestone-maintainers : can you add the 1.14 milestone tag for this PR?

It's a fix for a test that is not used at the moment in Kubernetes itself, so changes to this code can't break anything.

**Comment by alejandrox1** [comment]
Adding it to the v1.14 milestone since it is CI related
/milestone v1.14

**Pull request merged**
