### PR TITLE
Change default Kubelet NodeStatusUpdateFrequency from 2s to 10s.

### PR DESCRIPTION
**Pull request by davidopp**
To partially address the numerous performance complaints.

### CODE REVIEW

**Comment by davidopp** [comment]
@gmarek @dchen1107

**Comment by dchen1107** [comment]
LGTM except why not defining a set of consts to avoid hardcoding those numbers in many places. I am ok with introducing those consts in a separate pr.

**Comment by davidopp** [comment]
Sure, I can change to consts in a separate PR. Where would you suggest I define the const? I assume I should have one set for Kubelet and one for master, since they are separate binaries?

**Comment by gmarek** [comment]
LGTM

**Comment by quinton-hoole** [comment]
Did anyone run e2e tests on this before merging?

We've seen 2 of 2 complete failures in Jenkins e2e since this merge.  The sadly rather uninformative error message is:

2015/04/07 14:45:57 Error running up: exit status 1
2015/04/07 14:45:57 Error starting e2e cluster. Aborting.
exit status 1

**Comment by quinton-hoole** [comment]
Never mind, the third attempt seems to have succeeded.  I'll keep an eye on it.

**Comment by wojtek-t** [comment]
Thanks @davidopp - LGTM

**Pull request merged**
