### PR TITLE
staging/src/k8s.io/api/core/v1/toleration.go: Improving test coverage

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
add UT
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Comment by Octopusjust** [comment]
@solty @yuj
 please take a review, thanks

**Pull request closed without merging**
