### PR TITLE
Minor fixups to iSCSI example.

### PR DESCRIPTION
**Pull request by ghost**
- Put the link for setting up the target before initiator link.
- Add a comment about removing the partition created in the linked
  tutorial.
- Change the settings in the pod to resemble those you would if you
  follow the tutorial

Signed-off-by: Sami Wagiaalla swagiaal@redhat.com

### CODE REVIEW

**Comment by swagiaal** [comment]
@rootfs what do you think of these changes ?

**Comment by thockin** [comment]
LGTM, @rootfs for confirm

**Comment by rootfs** [comment]
LGTM

**Comment by thockin** [comment]
low risk

**Pull request merged**
