### PR TITLE
Fix the bug of the "removePod" function in node_info.go

### PR DESCRIPTION
**Pull request by ping035627**
It should reduce the resource data after finding the pod in the pods, because perhaps no corresponding pod in the pods of the node, at this time it shouldn't reduce the resource data of the node.

### CODE REVIEW

**Comment by ping035627** [comment]
@davidopp
 fix bug, can test? thanks.

**Comment by ping035627** [comment]
@wojtek-t
 fix bug,  can test? thanks

**Comment by wojtek-t** [comment]
Seems test didn't start

@k8s-bot test this please github issue: #IGNORE

**Comment by ping035627** [comment]
@k8s-bot test this issue: #25936

**Comment by ping035627** [comment]
@wojtek-t
need "ok to test", thanks

**Comment by hongchaodeng** [comment]
Add a test?

**Comment by ping035627** [comment]
Seems test didn't start.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
ok to test

**Pull request merged**
