### PR TITLE
Move node and networking related helpers from pkg/util to component helpers

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This is part of the effort to remove kube-proxy from the tree
#### Which issue(s) this PR fixes:
This PR is the kickstart of the effort to move kube-proxy from k/k to staging described in issue #92369

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig node
/sig network

### CODE REVIEW

**Comment by rikatz** [comment]
/hold
Want to discuss about k/net-utils vs component-helpers for the conntrack case :)

Will ping Tim and Antonio on monday in Slack :)

**Comment by aojea** [comment]
> Want to discuss about k/net-utils vs component-helpers for the conntrack case :)

ah, ok,  since this is no network related  I though it was ok

**Comment by rikatz** [comment]
/hold cancel

Ok, I need to have some rest...I'm confused by my own PRs, I'm not moving the conntrack package here, but removing sysctl from conntrack.go from proxier

Sorry Antonio 😁

**Review by ehashman — COMMENTED** [review]
/lgtm
/priority important-longterm
/triage accepted

**Review by mrunalp — APPROVED** [review]

**Comment by rikatz** [comment]
@ehashman sorry for the long delay! I've completely forgot about this one.

I have rebased and fixed stuff here, hopefully this works to you!

Let me gather someone from sig-network as well to maybe approve this :)

**Review by endocrimes — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
/lgtm
/approve
ping @wojtek-t for scalability

**Pull request merged**
