### PR TITLE
Use correct PodIP

### PR DESCRIPTION
**Pull request by octplane**
Fix Pod IP detection when the Pod is running in hostNetwork.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> 
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fix the PodIp detection for special cases (in my case, when the Pod is using hostNetwork). Code borrowed from the `prober` code.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
@octplane congrats on your first pr :) Could you do me a favor and prefix the title with `[WIP]` until it is ready for review? Just helps those reviewing code know at a glance what code needs review and what code doesn't. Also, let me know if you need help signing the CLA or if there's anything else I can help with :)

**Comment by octplane** [comment]
@mattjmcnaughton working to get added to company's CLA, thanks for the kind intro :)

**Comment by octplane** [comment]
CLA should be ok.

**Comment by mattjmcnaughton** [comment]
> CLA should be ok.

Hmmm unfortunately looks like the bot still isn't considering the CLA to be signed... could be worth filing a ticket with the [Linux Foundation Help Desk]( https://support.linuxfoundation.org/).

**Comment by octplane** [comment]
CLA is set to yes!

**Comment by octplane** [comment]
@mattjmcnaughton please help this PR survive :)

**Comment by mattjmcnaughton** [comment]
/remove-lifecycle-stale

Hi @octplane! Is this diff still WIP? If not, could I trouble you to remove the `[WIP]` from the title?
Alternatively, is there specific feedback you're looking for which will help it transition out of WIP? Thanks :)

**Comment by mattjmcnaughton** [comment]
/ok-to-test

Marking as ok-to-test so we can start getting some CI feedback, in case that's helpful :)

**Comment by octplane** [comment]
I think that if CI goes through, I'm not asking for more feedback on this small change...

**Comment by octplane** [comment]
Hello team 👋 , the PR is ready to be tested/reviewed/whatever, thanks!

**Pull request closed without merging**
