### PR TITLE
Update the go get to k8s.io/sample-controller

### PR DESCRIPTION
**Pull request by rkamudhan**
Referring to the issue: https://github.com/kubernetes/sample-controller/issues/20#issuecomment-398716033

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xmichalis — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
/assign @sttts 
for approval

**Pull request merged**
