### PR TITLE
reenable kubelet auth

### PR DESCRIPTION
**Pull request by mikedanese**
revert #41132 

This reverts commit fd56078298ed5f4f2fbf95d3662196db36beef4a, reversing
changes made to d953402cdf414a877cb537d8db46646db38e7bef.

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot cvm gce e2e test this

**Comment by cjcullen** [comment]
still /lgtm. Hopefully it won't break stuff this time :).

**Comment by mikedanese** [comment]
@k8s-bot cross build this

**Pull request merged**
