### PR TITLE
correction on rbd volume object and defaults

### PR DESCRIPTION
**Pull request by rootfs**
- add `omitempty` to `RBDPool RadosUser Keyring SecretRef ReadOnly`
- move defaults from `pkg/volume/rbd/rbd.go` to `pkg/api/v1/defaults.go`

addressing #18885

### CODE REVIEW

**Comment by rootfs** [comment]
will fix `CephFS` in the same way too.

**Comment by elsonrodriguez** [comment]
I tested this and was able to mount an rbd volume. LGTM

**Comment by pmorie** [comment]
@rootfs will your ebase this and we'll try to get it in to 1.3?

**Comment by rootfs** [comment]
@pmorie rebased, thanks

**Comment by elsonrodriguez** [comment]
@rootfs The k8s bot bumped this again, any chance for a rebase?

**Comment by rootfs** [comment]
@elsonrodriguez thanks

@pmorie PTAL

**Comment by pmorie** [comment]
@rootfs verify script failure, run `hack/update-all.sh`:

```
/go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
FAILED   ./hack/../hack/verify-api-reference-docs.sh	29s
```

**Comment by rootfs** [comment]
@pmorie all green.

**Pull request merged**
