### PR TITLE
Set CONTAINER_RUNTIME default value to 'docker'

### PR DESCRIPTION
**Pull request by yguo0905**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

This PR fixes one of the issues in https://github.com/kubernetes/kubernetes/issues/55189.

**Special notes for your reviewer**:

**Release note**:

```
None
```

/assign @yujuhong, @Random-Liu

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM.

Sorry for this. OSS test is passing, don't know GKE is relying on it. :(

**Comment by dchen1107** [comment]
I am manually merging this pr since it fixes gke-related tests on master branch.

**Pull request merged**
