### PR TITLE
[WIP] Add sampling histogram

### LINKED ISSUE #796: Feature Request: Permit histogram's Observe() method to take an observation count
We had a case where we in theory update a histogram at some frequency. In actuality, we only update it when things are happening, and when nothing is happening, we just count the amount of time that has passed and then update it with that many ~zeros~ [edit: observations] when the next thing happens.

Right now adding a value to a historgram N times takes N calls of Observe(). It would be very nice if we could pass N as a parameter instead, and if I follow the code, it could be done in constant time.

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
In https://github.com/kubernetes/apiserver/blob/master/pkg/util/flowcontrol/metrics/sample_and_watermark.go today there is the abstraction of sampling a variable to populate a histogram.  It has an awkward bit of code: a loop to call the `Observe` method of a Prometheus Histogram a variable number of times.  This led to the suggestion https://github.com/prometheus/client_golang/issues/796 .  The discussion there suggested I create a new Prometheus abstraction, possibly out of (prometheus) tree.  This PR is my start on such a creation, indeed out of the prometheus tree.

There are three bits of tension here:
1. The support for "vectors" of metrics in the Prometheus golang library is not public --- and it is non-trivial.  This makes doing this work out of the prometheus tree problematic.
1. `sampling-histogram_test.go` uses fake clocks.  That's the only reasonable way to get sufficient control in a test that runs quickly.  But the Prometheus tree does not include such clocks, so moving this code into the Prometheus tree would be problematic.
1. `sample_and_watermark.go` traffics in _passive_ clocks (and with good reason: to support event-based testing of API Priority and Fairness code), but k8s.io/utils/clock does not define passive clocks.

**Which issue(s) this PR fixes**:

Fixes https://github.com/prometheus/client_golang/issues/796

**Special notes for your reviewer**:
For the moment I put a personal copyright on the code that could go in either Kubernetes or Prometheus, depending on how the relevant tensions are relaxed.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
This is waiting on https://github.com/prometheus/client_golang/pull/803 to merge.

**Comment by MikeSpreitzer** [comment]
https://github.com/kubernetes/utils/pull/190 is going to be important

**Comment by beorn7** [comment]
https://github.com/prometheus/client_golang/pull/803 is merged now. Sorry for the delay. I'll cut a release v1.8.0 of prometheus/client_golang today so you don't need to lock to a particular commit in your `go.mod` file anymore.

If you need help with what I [said about implementing a more efficient sampling histogram](https://github.com/prometheus/client_golang/issues/796#issuecomment-692218541), let me know. For example, I could create a PR on top of this, once it is merged (or even before, if you prefer that).

**Comment by beorn7** [comment]
As this has gone stale now, let me repeat my offer above to help implementing [my suggestion](https://github.com/prometheus/client_golang/issues/796#issuecomment-692218541). Let me know if that's something you would appreciate.

**Comment by MikeSpreitzer** [comment]
/remove-lifecycle rotten
Yes, @beorn7 , thanks for your offer, I am interested.  Just a little swamped now and slow on getting things done.

**Comment by beorn7** [comment]
OK, I'll try to propose something in the next few days.

**Comment by beorn7** [comment]
@MikeSpreitzer  I created a [PR against your fork](https://github.com/MikeSpreitzer/kubernetes/pull/2) to demonstrate my proposal.

**Pull request closed without merging**
