### PR TITLE
Address an old TODO to make UUID generation lock-less

### PR DESCRIPTION
**Pull request by brendandburns**
@quinton-hoole @wojtek-t @lavalamp

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@brendandburns - it seems that the test doesn't compile:
"_output/local/go/src/k8s.io/kubernetes/pkg/util/uuid_test.go:20: imported and not used: "sync""

Can you please fix it?

**Comment by brendandburns** [comment]
oops, I didn't push with my benchmark changes.  Fixed.  ptal.

thanks!
--brendan

**Comment by wojtek-t** [comment]
Jenkins failure is an unrelated flake:
"Kubectl describe should check if kubectl describe prints relevant information for rc and pods"

@k8s-bot test this please

**Comment by wojtek-t** [comment]
@brendandburns - can you please take a look into Shippable failure? It seems that in Go 1.3 some tests are failing very repeatably.

**Comment by gmarek** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@brendandburns - this PR doesn't work in Go 1.3 - can you please take a look?

**Comment by wojtek-t** [comment]
@brendandburns - this PR doesn't work in Go 1.3 - can you please take a look?

**Comment by erictune** [comment]
What is the scenario where having this PR helps?

**Pull request closed without merging**
