### PR TITLE
Set Dashboard UI version to v1.5.0

### PR DESCRIPTION
**Pull request by rf232**
Updating the dashboard version to v1.5.0

see our release notes at https://github.com/kubernetes/dashboard/releases/tag/v1.5.0

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37684)

**Comment by rf232** [comment]
@bryk: PTAL

**Comment by bryk** [comment]
LGTM

**Comment by bryk** [comment]
@k8s-bot test this

**Comment by bryk** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
