### PR TITLE
Add comments in several hack/verify-*.sh(s-v)

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Add or update the comments for the following scripts. (s-v of verify-XXX.sh)

hack/verify-shellcheck.sh
hack/verify-spelling.sh
hack/verify-staging-meta-files.sh
hack/verify-staticcheck.sh
hack/verify-test-code.sh
hack/verify-test-featuregates.sh
hack/verify-test-images.sh
hack/verify-typecheck-providerless.sh
hack/verify-typecheck.sh
hack/verify-vendor-licenses.sh
hack/verify-vendor.sh

**Which issue(s) this PR fixes**:
ref:#86597

**Special notes for your reviewer**:
/cc @fejta

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by hase1128** [comment]
/assign @spiffxp 
Would you please review this PR?
Fejta seems to be offline recently.

**Review by fejta — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
