### PR TITLE
Removed a period that does not belong (My First PR)

### PR DESCRIPTION
**Pull request by rramkumar1**
**What this PR does / why we need it**:

`Removed a period that does not belong (My First PR)`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by php-coder** [comment]
@rramkumar1 Could you update the PR's title to explain what this PR is doing? Thanks!

**Comment by bowei** [comment]
@php-coder : this is a test commit, feel free to ignore, we are going to close it

**Comment by cblecker** [comment]
/hold
to apply do-not-merge

**Pull request closed without merging**
