### PR TITLE
Fix broken warning image link in docs

### LINKED ISSUE #26357: Warning image link is broken across docs
This includes `podaffinity.md` but effects multiple docs.

### PR DESCRIPTION
**Pull request by joe2far**
fixes #26357

### CODE REVIEW

**Comment by thockin** [comment]
@johndmulhausen This touches "old docs" in the main repo.  As long as those docs exist, we will have this conflict.  Should we leave the old docs broken?  Or should we fix them this one time and override the do-not-merge?  Or should we remove the old docs from the main repo?

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this issue: #26431

**Comment by joe2far** [comment]
@thockin / @johndmulhausen - Can this be merged?
There has been new docs files added over the past few weeks, which contained this broken link.
At the very least the doc header template in "cmd/mungedocs/unversioned_warning.go" should be updated to prevent this... (The latest rebase of this PR also includes fixes for these new docs files)

**Comment by thockin** [comment]
I'm going to manually merge this to bypass the old docs rule.

**Comment by mikedanese** [comment]
heh, this broke verification.

**Comment by joe2far** [comment]
There were a couple of other docs files added (with the existing header) before this got merged.
This was fixed by #29355 (thanks mikedanese)

**Pull request merged**
