### PR TITLE
fix a typo in line 1620 kubernets -> kubernetes

### PR DESCRIPTION
**Pull request by yeya24**
fix a typo in line 1620 kubernets -> kubernetes

What type of PR is this?
/kind typo-fix

What this PR does / why we need it:
fix a typo
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

```release-note
fix a typo in line 1620 kubernets -> kubernetes
```

### CODE REVIEW

**Comment by yeya24** [comment]
What type of PR is this?
/kind typo-fix

What this PR does / why we need it:
fix a typo
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

**Comment by idealhack** [comment]
https://github.com/kubernetes/kubernetes/blob/master/translations/README.md#regenerating-the-bindata-file

**Pull request closed without merging**
