### PR TITLE
fix an param typo of AKS loadbalancer method

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig azure

### CODE REVIEW

**Comment by Huang-Wei** [comment]
Kindly 

/assign @feiskyer.

It's a copy/paste mistake which would be good to be corrected.

**Comment by Huang-Wei** [comment]
Kindly

/assign @feiskyer 

It's a copy/paste mistake which would be good to be corrected.

**Comment by feiskyer** [comment]
@Huang-Wei Thanks for the cleanup.

/lgtm
/approve

**Pull request merged**
