### PR TITLE
test: Fix path to e2e node sample device plugin

### LINKED ISSUE #116241: e2e node test failing - E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive]
### Which jobs are failing?

Serial e2e node jobs, e.g. https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial

### Which tests are failing?

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial

### Since when has it been failing?

Since 03-01

### Testgrid link

_No response_

### Reason for failure (if possible)

Seems related to https://github.com/kubernetes/kubernetes/pull/115107

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by bobbypage**
The existing path is incorrect (missing `sample-device-plugin`) directory and thus causing test failures. The full path should be `test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin.yaml`.

#### What type of PR is this?

/kind failing test

#### Which issue(s) this PR fixes:

Fixes #116241

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
Hold, for results of the serial run `pull-kubernetes-node-kubelet-serial-containerd`

/hold

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by bobbypage** [comment]
serial failure is unrelated, device plugin tests are now passing.

/unhold

**Review by swatisehgal — APPROVED** [review]
/lgtm

Thanks for fixing this so promptly!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
