### PR TITLE
Revert "Containerized mount utilities"

### PR DESCRIPTION
**Pull request by x13n**
Reverts kubernetes/kubernetes#53440

This PR broke pull-kubernetes-cross test.

### CODE REVIEW

**Comment by wojtek-t** [comment]
We should fix "cross build", but since it's non-blocking, there is no need to revert it immediately.

@jsafrane - can you please take a look?
@tallclair - FYI

**Comment by x13n** [comment]
Thanks! Closing in this case.

**Comment by jsafrane** [comment]
It's already fixed by https://github.com/kubernetes/kubernetes/pull/55712

**Pull request closed without merging**
