### PR TITLE
Persistent influxdb data to directory on local host.

### LINKED ISSUE #10497: cluster-monitoring influxdb needs a volume to back its data
While @saad-ali working on #10335, we noticed that influxdb container is killed, and restarted because exceeding its memory limit (the limit is 2Gi, but influxdb is using 3.2Gi at peak on 4 nodes cluster in @saad-ali's test). After influxdb is restarted, we found all data is lost. It turns out there is no volume back up its data at node:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml

### PR DESCRIPTION
**Pull request by dchen1107**
Fixed #10497

cc/ @saad-ali

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @thockin @vmarmol

**Comment by thockin** [comment]
LGTM, I assume that directory means something to influx

**Comment by vmarmol** [comment]
LGTM

**Comment by saad-ali** [comment]
LGTM
@thockin I don't see this documented anywhere in the InfluxDB documentation, but `/opt/influxdb/shared` appears to be the default InfluxDB database storage directory. See [link](http://kgu87.typepad.com/my_weblog/2014/10/moving-influxdb-data-to-another-location.html), for example.

**Comment by thockin** [comment]
I am fine with this change, but I want Dawn to confirm it is working properly and dumping state to this volume and reduces the memory footprint

**Comment by saad-ali** [comment]
Actually it looks like we use a [custom InfluxDB config](https://github.com/GoogleCloudPlatform/heapster/blob/master/influxdb/config.toml#L88) to change the storage dir to `/data/`
@dchen1107 is looking in to it

**Comment by dchen1107** [comment]
Ok, I think this pr is ready to have another review now. /opt/influxdb/shared is the default directory of influxdb for configuration and storage. But our heapster version influxdb's storage is moved to /data/db:

https://github.com/GoogleCloudPlatform/heapster/blob/master/influxdb/config.toml#L88

I manually tested it by restarting influxdb container on the node, and check monitoring-grafana page, and stats before killing are exist.

**Comment by zmerlynn** [comment]
LGTM

**Comment by thockin** [comment]
LGTM

**Comment by zmerlynn** [comment]
Someone should slap the magic label on it so I remember to merge it in the morning. Or I could do it now.

**Comment by thockin** [comment]
done

**Comment by dchen1107** [comment]
Ok, I still observed memory leakage of influxdb. After some research, it is known issue for influxdb 0.8 release which is what we are using here https://github.com/GoogleCloudPlatform/heapster/blob/master/influxdb/Dockerfile#L5.

The issue filed against influxdb and latest update can be found at:  https://github.com/influxdb/influxdb/issues/1228#issuecomment-96829826

But this pr and upcoming one adding resource limit for addons can help with the situation even with memory leakage since most of stats are persistent to the local host, and restarting such docker container will pick up preexisting stats.

cc/ @thockin and @bgrant0607 for TL's lgtm. Thanks!

**Comment by dchen1107** [comment]
@thockin thanks! you are beating me :-)

**Comment by bgrant0607** [comment]
LGTM

**Comment by romanek-adam** [comment]
I just wanted to mention that this change probably led to another issue: #13508.

**Pull request merged**
