### PR TITLE
[WIP] Remove IPv6 limitations using roaring bitmaps 

### LINKED ISSUE #44918: cidr_set bitmap should be compressed
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
latest

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
cidr_set.go in pkg/controller/node currently uses a bitmap to track the subnets allocated.
The current allocation logic assumes a small allocation range. This bitmap could grow very large with the introduction of IPv6.
The v6 code in cidr_set.go currently limits the difference between the cluster mask size and subnet mask size to 16. This restriction could be removed if the bitmap was compressed.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:

   Bitsets, also called bitmaps, are commonly used as fast data structures.
    Unfortunately, they can use too much memory. To compensate,
    we often use compressed bitmaps.
    
    This PR adds a new bitmap implementation based on roaring bitmaps,
    allowing to reduce the memory size.
    
 ```
/usr/local/go/bin/go test -benchmem -run=^$ k8s.io/kubernetes/pkg/registry/core/service/allocator -v -bench ^\(Benchmark.*\)$
goos: darwin
goarch: amd64
pkg: k8s.io/kubernetes/pkg/registry/core/service/allocator
BenchmarkContiguousAllocationBitmap-4                  1        22881513752 ns/op        2084456 B/op        318 allocs/op
BenchmarkRandomAllocationBitmap-4                      1        28557438174 ns/op        2084064 B/op        316 allocs/op
BenchmarkRoaringBitmap-4                         4282317               238 ns/op              32 B/op          2 allocs/op
```

**Which issue(s) this PR fixes**:

Fixes #44918

**Special notes for your reviewer**:

revamping https://github.com/kubernetes/kubernetes/issues/44918

**Does this PR introduce a user-facing change?**:

```release-note
ip allocation use roaring bitmaps to remove restrictions due to the size of the bitmaps
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/pull/1534
```

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-ipv6
failed only 1 test  [sig-cli] Kubectl client Simple pod [It] should support inline execution and attach

**Comment by neolit123** [comment]
bigger changes tend to require KEPs, so not sure this can go without one.
a KEP here can provide the high level overview of the new dependencies (and indirect ones), the choice for `MaxHostsSubnet` etc.

in any case, i like this a lot.

/sig network

**Comment by aojea** [comment]
> bigger changes tend to require KEPs, so not sure this can go without one.
> a KEP here can provide the high level overview of the new dependencies (and indirect ones), the choice for `MaxHostsSubnet` etc.
> 
> in any case, i like this a lot.
> 
> /sig network

Yeah, thanks for the heads up, this will need a KEP for sure, but previously just wanted to understand the code and the pros and cons.

**Comment by liggitt** [comment]
@kubernetes/sig-network-api-reviews 
/remove-sig api-machinery

**Comment by thockin** [comment]
When it comes to review - anythign you can do to break this up will be appreciated.

E.g. refactor in one commit, add interface and implement with current code, add new implementation, remove size limits, etc all as distinct commits :)

**Comment by aojea** [comment]
The benchmark results are really interesting but doesn't seem to solve any problem, let's archive it for now
/close

**Pull request closed without merging**
