### PR TITLE
Automated cherry pick of #76299: Short-circuit quota admission rejection on zero-delta

### PR DESCRIPTION
**Pull request by mansi-a**
Cherry pick of #76299 on release-1.13.

#76299: Short-circuit quota admission rejection on zero-delta

### CODE REVIEW

**Comment by liggitt** [comment]
there are compile errors that need fixing in this cherrypick

not a regression in 1.13.
considered a critical fix because objects with finalizers (notably PVCs) cannot be deleted when using global quota.
this was not encountered previously because the configuration is rare.
this PR adds tests that exercise the scenario positively (ensures quota blocks when appropriate) and negatively (ensures quota does not prevent zero-delta updates and deletions).

/priority critical-urgent
/milestone v1.13
/cc @tpepper @aleksandra-malinowska

**Comment by tpepper** [comment]
Today's the 1.13.6 cherry pick deadline ahead of Wednesday May 8 release.  Please let us know if ya'll are ok with it missing to the next patch release or if we need to watch for it still.

**Comment by liggitt** [comment]
if this doesn't make it until next patch release, that's ok

**Comment by tpepper** [comment]
@liggitt this still needs lgtm/approve but other wise looks ready...

**Pull request merged**
