### PR TITLE
new test case to deviceplugin/endpoint.go

### PR DESCRIPTION
**Pull request by tianshapjq**
new test case to deviceplugin/endpoint.go

### CODE REVIEW

**Comment by tianshapjq** [comment]
@mindprince hi, can this pr be merged?

**Comment by RenaudWasTaken** [comment]
Seems very similar to https://github.com/kubernetes/kubernetes/pull/58941

**Comment by RenaudWasTaken** [comment]
I'm not sure which of the two PR we should choose. 

Though you do have a race in your code. When you call `Allocate` the device plugin might not have registered itself yet.

I'm also not sure about having a special function just for setting the Allocate function. If it's not reused in other tests are we going to need it?

**Comment by tianshapjq** [comment]
another commit has been merged, will close this.

**Pull request closed without merging**
