### PR TITLE
port Addon update test to v1 api

### PR DESCRIPTION
**Pull request by marekbiskup**
@bgrant0607 request in https://github.com/GoogleCloudPlatform/kubernetes/pull/9493#issuecomment-113968051
cc @zmerlynn

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM

**Comment by quinton-hoole** [comment]
LGTM.  OK to merge.

**Comment by mbforbes** [comment]
e2es failed twice—@marekbiskup can you please re-push until this passes? Assigning to @quinton-hoole to re-add `ok-to-merge` when this passes.

**Comment by mbforbes** [comment]
(Closing and opening to get it to run again now.)

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

@mbforbes, in future you can do the above.

**Comment by quinton-hoole** [comment]
The e2e test that failed last time around is a new one, AFAIK, and quite possibly flaky.  I'll check for you now.

**Comment by quinton-hoole** [comment]
Indeed, the test:

"Probing container with readiness probe should not be ready before initial delay and never restart"

is the only test that filed, but it failed about 15% of the time prior to this PR, so you can ignore it here.

Statistically, the next e2e run on this should succeed - lets wait a few minutes for that before merging.

**Comment by quinton-hoole** [comment]
ok-to-merge - all good.

**Pull request merged**
