### PR TITLE
cloudprovider/gce: use golang.org/x/oauth2

### PR DESCRIPTION
**Pull request by ukai**
code.google.com/p/goauth2 is deprecated.
use golang.org/x/oauth2 instead.

hooks/prepare-commit-msg ignore Godeps
for sh's boilerplate check.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@rakyll mentioned in December on #2045 that we should wait on switching as the oauth2 package was undergoing a revamp.

**Comment by ukai** [comment]
code.google.com/p/goauth2 is officially deprecated now.

**Comment by rakyll** [comment]
We highly recommend you to move to the new package now.

**Comment by brendandburns** [comment]
LGTM.  merging.

**Pull request merged**
