### PR TITLE
Revert "add gzip compression to GET and LIST requests"

### PR DESCRIPTION
**Pull request by liggitt**
xref https://github.com/kubernetes/kubernetes/issues/47135

This reverts commit fc650a54d02f358c7fc65fa25b8312028bd4e944 added in https://github.com/kubernetes/kubernetes/pull/45666

After https://github.com/kubernetes/kubernetes/pull/45666 merged, namespace deletion started flaking significantly in e2e runs. 

Disabling the gzip compression and running the problematic suite fixed the issue, though I'm still not sure why. Namespace deletion time dropped significantly with gzip disabled.

### CODE REVIEW

**Comment by liggitt** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by liggitt** [comment]
cc @deads2k @ilackarms

**Comment by ilackarms** [comment]
I wonder what would cause those tests to flake. Is there a way I can try to reproduce this locally?

**Comment by liggitt** [comment]
I wasn't able to pin it down, but some possible ideas:
* differences in behavior with content-length vs chunked encoding when there is sufficient data in the system to exceed the 4k response buffer (the filter isn't doing anything with transfer-encoding or content-length, and is assuming the wrapped handler isn't setting those headers)
* something with the gzip filter causing clients to wait for responses to complete, slowing them down, and stacking namespace deletion handling by the controller
* the gzip filter possibly getting put on subresource GET operations unintentionally (hadn't verified this)

for recreation... I would create a bunch of namespaces (50?) with some number of resources in them, then delete them rapidly and observe the namespace controller's behavior

**Comment by dchen1107** [comment]
/lgtm

cc/ @kubernetes/kubernetes-release-managers @foxish, the build cop

**Comment by liggitt** [comment]
e2e: `SUCCESS! -- 302 Passed | 0 Failed | 0 Pending | 344 Skipped`

**Comment by liggitt** [comment]
unit test failure is known flake (https://github.com/kubernetes/kubernetes/issues/42289)

recommend merging this to fix the gce-e2e job

**Comment by liggitt** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by dchen1107** [comment]
All tests are green. I am going to manually merge the pr for #47135

**Comment by gmarek** [comment]
It sounds like CPU usage issue. gzip is not particularly cheap and thus we shouldn't enable it by default.

**Comment by ilackarms** [comment]
@gmarek working on a PR with feature gating to disable gzip by default
cc @simon3z

**Pull request merged**
