### PR TITLE
remove azure getting kube-ups.

### PR DESCRIPTION
**Pull request by mikedanese**
Haven't been touched in > 7 months. 

@colemickens , i"m going to send out an email about this.

```release-note
Remove Azure kube-up as the Azure community has focused efforts elsewhere.
```

### CODE REVIEW

**Comment by colemickens** [comment]
Was just thinking about this yesterday. I think it's appropriate. CC: @anhowe, @brendandburns 

I don't remember who should be tagged on the `azure-legacy` removal though.

**Comment by brendandburns** [comment]
LGTM, thanks.

**Comment by roberthbailey** [comment]
I've tagged this for the 1.6 branch since we don't want to ship a 1.6 release with broken startup scripts.

**Comment by mikedanese** [comment]
@brendandburns @colemickens is there a link you would like in the release note?

**Comment by colemickens** [comment]
@mikedanese Not particularly. `Remove Azure kube-up as the Azure community has focused efforts elsewhere` ?

**Comment by mikedanese** [comment]
@k8s-bot test this

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
