### PR TITLE
k8s.io/component-base/logs: fix usage through Go flag package

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

api/v1.AddFlags only supports a pflag.FlagSet. The assumption was that code which wants to use flag.FlagSet can use VisitAll to copy the flags. That works, with one caveat: the flag.FlagSet help implementation will call String for the zero value to determine whether the flag has a non-default value. This currently leads to additional warnings at the end of the -help output:

     panic calling String method on zero v1.verbosityLevelPflag for flag v: runtime error: invalid memory address or nil pointer dereference
     panic calling String method on zero v1.vmoduleConfigurationPFlag for flag vmodule: runtime error: invalid memory address or nil pointer dereference

Supporting usage of methods with the zero value is good practice anyway and thus gets added. This then avoids these panics.

#### Special notes for your reviewer:

I'd like to backport this to release-1.26, therefore this is a minimal fix. Adding a AddGoFlags function also would be possible and may still be done later (see https://github.com/kubernetes/kubernetes/pull/114731),

#### Does this PR introduce a user-facing change?
```release-note
k8s.io/component-base/logs: usage of the pflag values in a normal Go flag set led to panics when printing the help message
```

/sig instrumentation
/wg structured-logging

### CODE REVIEW

**Comment by pohly** [comment]
/assign @serathius 

Do you agree that we should only backport this bugfix?

The alternative is to merge and backport PR #114731.

**Comment by pohly** [comment]
/assign @liggitt

For approval. The code in the log API package changes, but not the config API.

**Comment by liggitt** [comment]
is there any sort of test that would demonstrate the issue and prevent regressions in the future?

**Comment by pohly** [comment]
There wasn't, so added one - see new commit. The full comparison of the help output is sensitive to formatting changes, but I suppose those won't occur much with stable packages like pflag and flag.

**Comment by pohly** [comment]
> can we compare the output less strictly or just make sure it doesn't panic?

The panic is caught by the flag package internally, which then gets translated into additional text. Now that we know what that text looks like, we can check for it of course, but that is then still to some extend version dependent (new version might use different wording). At least it would fail with a false negative instead of a false positive.

The problem is that we want to test for "unexpected words" in the output, but we don't know what those are until we see them :cry: 

A regex that matches the right number of lines with some key words in each line might be a reasonable compromise?

**Comment by pohly** [comment]
I changed to a regexp match.

**Comment by liggitt** [comment]
/lgtm
/approve

thanks for the test update

**Pull request merged**
