### PR TITLE
Refactor cachingConfigMapManager

### PR DESCRIPTION
**Pull request by wojtek-t**
This is effectively copy-paste of https://github.com/kubernetes/kubernetes/pull/63539 for configmaps.

### CODE REVIEW

**Comment by liggitt** [comment]
is it possible to collapse this on the secret manager? we're about to have four implementations otherwise, right? ({caching,watch-based}, {configmap,secret})

**Comment by wojtek-t** [comment]
> is it possible to collapse this on the secret manager? we're about to have four implementations otherwise, right? ({caching,watch-based}, {configmap,secret})

I can try doing it (it would be so simple if we would have templates).
However, can we first merge this and do the collapsing in the follow-up PR (I would like to avoid diverging those two things).

**Comment by wojtek-t** [comment]
/hold

> is it possible to collapse this on the secret manager? we're about to have four implementations otherwise, right? ({caching,watch-based}, {configmap,secret})

PTAL at: https://github.com/kubernetes/kubernetes/pull/63857

**Pull request closed without merging**
