### PR TITLE
Correct Keyword name for DisruptionsAllowed in PDB.

### LINKED ISSUE #121585: Correct Keyword name for DisruptionsAllowed in PDB.
When describing a PodDisruptionBudget (PDB) in text, JSON, or YAML format, the keyword used to represent the "Number of pod disruptions that are currently allowed" should ideally be `disruptionsAllowed`. This naming convention is more consistent with the typical JSON/YAML key naming practices. It not only adheres to the convention but also clearly conveys its meaning. Using `disruptionsAllowed` makes it instantly clear that it defines the allowed number of disruptions.

Furthermore, consistent naming practices in JSON and YAML are essential for clarity and maintainability. When key names align with their meaning, it becomes easier for humans and automated systems to understand and work with the data. This consistency helps reduce potential confusion and errors in managing resources like PodDisruptionBudgets in a Kubernetes cluster.

For example, a PodDisruptionBudget configuration in YAML format might look like this:

```yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: my-app
  disruptionsAllowed: 1
 ```
By using `disruptionsAllowed` as the keyword, it is clear that this PDB allows only one disruption while keeping a minimum of two pods available. This naming convention helps maintain readability and understanding in the Kubernetes configuration.

### PR DESCRIPTION
**Pull request by nikhilmaheshwari24**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
This PR proposes a naming convention improvement for PodDisruptionBudget (PDB) configuration in Kubernetes. The key change is related to the `disruptions allowed` field in the PDB configuration. The proposed change is to use `disruptionsAllowed` as the keyword for representing the number of disruptions currently allowed in a PDB.

The reason for this change is to align the key naming in the PDB configuration with typical JSON/YAML key naming practices and improve clarity and maintainability. When key names are consistent with their meaning, it becomes easier for humans and automated systems to understand and work with the data. The `disruptionsAllowed` keyword clearly conveys its meaning and purpose, reducing potential confusion and errors in managing resources like PodDisruptionBudgets in a Kubernetes cluster.

Overall, this PR aims to enhance the naming convention within PDB configurations to provide more transparent and user-friendly documentation for Kubernetes users and operators.
#### Which issue(s) this PR fixes:

Fixes #121585

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

### CODE REVIEW

**Comment by mpuckett159** [comment]
Just to clarify this is just to have the helper text follow the same wording as the existing keyword correct? Since the type is disruptionsAllowed the helper text should be `Disruptions allowed` instead of `Allowed disruptions`?

**Comment by nikhilmaheshwari24** [comment]
Absolutely @mpuckett159 , this PR aims to align the naming convention within the PodDisruptionBudget (PDB) configuration, specifically focusing on the helper text to follow the same wording as the existing keyword. The current type in the configuration is `disruptionsAllowed`, and the proposed change in the helper text is to update it to `Disruptions allowed`, maintaining consistency with the actual type.

This adjustment enhances the clarity and readability of the documentation by ensuring that the helper text precisely mirrors the actual field type. By doing so, it enables users, operators, and automated systems to better understand and interact with the PDB configuration in Kubernetes.

The intention is solely to provide consistency between the naming convention used in the PDB configuration and the corresponding helper text, enhancing the overall usability and maintainability of Kubernetes resources.

**Comment by mpuckett159** [comment]
Cool just making sure I was understanding the change completely. Seems like a good idea to me. Thank you for the PR.

/lgtm

**Pull request closed without merging**
