### PR TITLE
Minor change: move client/unversioned/fake to client/restclient/fake

### PR DESCRIPTION
**Pull request by caesarxuchao**
The fake only contains a fake RESTClient, so move it to client/restclient.
cc @deads2k 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35742)

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Comment by caesarxuchao** [comment]
Rebased.

**Comment by caesarxuchao** [comment]
@k8s-bot node e2e test this, issue #34990

**Comment by caesarxuchao** [comment]
Cherry-picked the commit to https://github.com/kubernetes/kubernetes/pull/34489. It's blocking users of client-go, cannot wait for the submit-queue any longer.

**Pull request closed without merging**
