### PR TITLE
Fix cherry_pick_pull.sh to workaround hub#976

### PR DESCRIPTION
**Pull request by zmerlynn**
A number of people have run across
https://github.com/github/hub/issues/976 when trying to do cherry
picks using this script. Rather than stealing stdin, just create a
tmpfile and give hub full access to stdin, which will let it prompt
for the password it so dearly wants.

Tested by being unauth'd.

### CODE REVIEW

**Comment by zmerlynn** [comment]
This is for all of you that have seen `cherry_pick_pull.sh` crash with:

```
To git@github.com:dchen1107/kubernetes-1.git
 + 3a1ff78...f78c9f7 automated-cherry-pick-of-#12541-upstream-release-1.0-1439397110 -> automated-cherry-pick-of-#12541-upstream-release-1.0 (forced update)
+++ Creating a pull request on github
github.com password for dchen1107 (never stored): inappropriate ioctl for device

goroutine 1 [running]:
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getch(0x4c208000100)
    /usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/nix.go:13 +0x74
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getPasswd(0x0, 0x0, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:18 +0x11f
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.GetPasswd(0x0, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:37 +0x3e
github.com/github/hub/github.(*Config).PromptForPassword(0x4c20801d740, 0x4c2080a420a, 0xa, 0x7fffeb086ceb, 0x9, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/github/config.go:123 +0x1eb
github.com/github/hub/github.(*Config).PromptForHost(0x4c20801d740, 0x4c2080a420a, 0xa, 0x0, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/github/config.go:61 +0xfe
github.com/github/hub/commands.pullRequest(0xa88840, 0x4c208068090)
    /usr/local/src/goproj/src/github.com/github/hub/commands/pull_request.go:93 +0x11e
github.com/github/hub/commands.(*Command).Call(0xa88840, 0x4c208068090, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0x4c208028880, 0xa88840, 0x4c208068090, 0x0, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/commands/runner.go:93 +0x54
github.com/github/hub/commands.(*Runner).Execute(0x4c208028880, 0x0, 0x0, 0x0)
    /usr/local/src/goproj/src/github.com/github/hub/commands/runner.go:85 +0x215
main.main()
    /usr/local/src/goproj/src/github.com/github/hub/main.go:12 +0x40
```

cc @thockin @roberthbailey 

More testing would be appreciated just to make sure I drove the problem off, though I'm pretty satisfied with the testing I did.

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
Unless that issue is the same as https://github.com/github/hub/issues/876, I haven't seen it (I always get the hub error parsing my remote URL). It looks like @yujuhong might be a good person to test this out.

**Comment by yujuhong** [comment]
Renamed ~/.config/hub, checked out this PR, and ran the script. Script successfully prompted me for password.
```
github.com password for yujuhong (never stored): 
```
Thanks for fixing this!

**Pull request merged**
