### PR TITLE
Add ubuntu to gluster and nfs tests

### LINKED ISSUE #50039: Need to test storage plugins on ubuntu
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We will be supporting ubuntu as a node image soon, so the major storage plugins should be validated against it.

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
Enable gluster and nfs tests for ubuntu distro

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50039

**Special notes for your reviewer**:

**Release note**:

/release-note-none
/sig storage

### CODE REVIEW

**Comment by msau42** [comment]
cc @yguo0905

**Comment by msau42** [comment]
@yguo0905 you may also need to add some logic in the gke test config to recognize ubuntu as an image.  See #48286

**Comment by yguo0905** [comment]
Thanks @msau42! I will make relevant changes to  `cluster/gke/config-test.sh` after this PR is merged.

How about the tests for XFS?

**Comment by msau42** [comment]
We don't have any tests that explicitly test filesystems.  I need to add brand new tests for XFS.

**Comment by msau42** [comment]
#49511 for adding xfs tests

**Pull request merged**
