### PR TITLE
Revert "Enable kubecontainer.Cache in kubelet"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#19436

This change probably broke gce e2e suite. After it was merge the suite became very flaky. http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10388/

cc @yujuhong @Random-Liu

### CODE REVIEW

**Comment by gmarek** [comment]
We'll monitor test status to see if it helped.

**Comment by piosz** [comment]
Merging manually to see whether this help.

**Comment by gmarek** [comment]
Tests are behaving much better now.

**Comment by timothysc** [comment]
I have zero visibility in to the error(s) here. 

@gmarek could you please pastebin 

/cc @yujuhong

**Comment by gmarek** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/10388/build-log.txt - @timothysc this should work for you.

**Pull request merged**
