### PR TITLE
cleanup unused function LookForStringInFile

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

cleanup unused function LookForStringInFile

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
Thanks for the cleanup!

For reference, last usage was removed in https://github.com/kubernetes/kubernetes/pull/82812

/lgtm

**Comment by oomichi** [comment]
confirmed this since https://cs.k8s.io/?q=LookForStringInFile&i=nope&files=&repos=

/approve

**Pull request merged**
