### PR TITLE
Typo fix:togather->together

### PR DESCRIPTION
**Pull request by Haleygo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by marpaia** [comment]
This doc is going to be overwritten with a copy-edited set of the release notes. It is on my not-so-long-term wish list to get the tool that generates and commits this notes file when tags are cut (anago) more integrated with the process that we use for generating the release notes document but the branch manager role (and the tool that they use) is currently in a lot of flux.

**Comment by nikhita** [comment]
@HuiWang0025 Sorry for the delay here! Can you rebase? This looks good to be merged.

**Pull request closed without merging**
