### PR TITLE
Remove unused not found and change comment

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:
Avoid to go to the not found logic because it is useless. Then, remove the comment out and change it

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: no

```release-note

```

### CODE REVIEW

**Comment by xichengliudui** [comment]
ok-to-test

**Comment by cwdsuzhou** [comment]
@lichuqiang @thockin  please review code.

**Comment by xichengliudui** [comment]
ok-to-test

**Comment by jsafrane** [comment]
I'd like the way how the original code is explicit. pv_controller.go is pretty complex and I strongly prefer verbose code over following coding guidelines here. See the comment at the top:

https://github.com/kubernetes/kubernetes/blob/61f3d4e92cd13e9b0e0fd525b7e2c79c87adf9ae/pkg/controller/volume/persistentvolume/pv_controller.go#L56-L66

**Comment by cwdsuzhou** [comment]
> ==

@jsafrane Thank you for your comment, and sorry, I have not seen the comment before.

**Pull request closed without merging**
