### PR TITLE
Provide link with e2e guidelines when verity-test-code.sh fails

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind cleanup
/sig testing

#### What this PR does / why we need it:
The link https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md has lots of valuable information what a test looks like and when a failure from `hack/verify-test-code.sh` appears it will be handy for folks who not necessarily know what to do with the failure. 

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
/assign @pohly 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
This verify-test-code.sh is actually fairly old. It's on my backlog to check how much of it is still relevant.

Either way, if it fails the link is definitely useful.

**Comment by soltysh** [comment]
> Either way, if it fails the link is definitely useful.

It still fails and provides value. I scratched my head earlier today what it was complaining about, b/c I remember that gingko marchers are preferred, but then realized I should re-read the doc linked here and I must have missed the part that for errors `framework.ExpectNoError` is actually much more better. So having it there explicitly will help folks not familiar with that doc.

**Comment by pohly** [comment]
Yes, that check is useful. I just think that we now have better tools to do that than a grep on the source code.

**Pull request merged**
