### PR TITLE
Updated COS version to M77 and includes fixes to ensure scalability tests pass

### PR DESCRIPTION
**Pull request by dhuh**
Updated COS version from M73 to M77. The updates from M77 include the following:

Kernel update from 4.14 to 4.19
Docker update from 18.09 to 19.03
Systemd upgrade to 239

### CODE REVIEW

**Comment by yguo0905** [comment]
The previous attempt https://github.com/kubernetes/kubernetes/pull/82766 to update the image failed because it broke the scalability test. This PR contains a new image with the fix.

/release-note-none
/ok-to-test
/kind feature
/priority important-soon
/lgtm
/assign @yujuhong

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
