### PR TITLE
cleanup validation for topologyManager

### PR DESCRIPTION
**Pull request by NoicFank**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

cleanup the validation about `topologyPolicyName != PolicyNone`, since it must be `true`, due to following checks will execute before the validation in this MR.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/topologymanager/topology_manager.go#L136-L140
```go
	// When policy is none, the scope is not relevant, so we can short circuit here.
	if topologyPolicyName == PolicyNone {
		klog.InfoS("Creating topology manager with none policy")
		return &manager{scope: NewNoneScope()}, nil
	}
```
#### Which issue(s) this PR fixes:

Fixes #
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by swatisehgal** [comment]
/assign @klueska @mrunalp @derekwaynecarr
for approval

**Comment by NoicFank** [comment]
@dims @klueska @swatisehgal  PTAL,thanks.

**Pull request closed without merging**
