### PR TITLE
Automated cherry pick of #28697

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #28697 on release-1.3.

### CODE REVIEW

**Comment by thockin** [comment]
@erictune are you gatekeeper for cherry picks?

**Comment by thockin** [comment]
@Random-Liu needs rebase

**Comment by Random-Liu** [comment]
> @Random-Liu needs rebase

@thockin Does this need rebase? I'm not quite familiar with the cherry-pick process. But I tried to cherry-pick this commit to release-1.3 branch myself, and everything worked fine. :)

**Comment by erictune** [comment]
no.  Fabio is gatekeeper.

**Comment by Random-Liu** [comment]
> Fabio is gatekeeper.

@erictune Thanks!
@fabioy PTAL~ :)

**Comment by fabioy** [comment]
@Random-Liu Can you rebase the cherrypick? Thanks.

**Comment by Random-Liu** [comment]
Just did a rebase, apply LGTM again.

**Pull request merged**
