### PR TITLE
Automated cherry pick of #115966: make MixedProtocolNotSupported public

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #115966 on release-1.24.

#115966: don't process unsupported loadbalancers with mixed protocols #115966

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/116851 for testing client issue with SSA support

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by aojea** [comment]
ping @kubernetes/release-managers 

it seems it slipped through 🤷

**Comment by cpanato** [comment]
@aojea the CP is only required for 1.24 and 1.25?

**Comment by aojea** [comment]
> @aojea the CP is only required for 1.24 and 1.25?

no, I just realized that the 1.26 is missing, I thought the original PR merged in 1.26 but it was in 1.27, let me go thhrought all of them again

Thanks Carlos for realizing about this

**Comment by cpanato** [comment]
> > @aojea the CP is only required for 1.24 and 1.25?
> 
> no, I just realized that the 1.26 is missing, I thought the original PR merged in 1.26 but it was in 1.27, let me go thhrought all of them again
> 
> Thanks Carlos for realizing about this

thank you, please ping me when is all ready :) have a great weekend

**Comment by aojea** [comment]
> thank you, please ping me when is all ready :) have a great weekend

https://github.com/kubernetes/kubernetes/pull/118252

**Comment by thockin** [comment]
ping @kubernetes/release-managers

**Pull request merged**
