### PR TITLE
Update conntrack.go regarding port range upper boundary

### PR DESCRIPTION
**Pull request by seantywork**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adds upper boundary check for port range.
The reason we need it is that given the port range is set beween 0 - 65535, only applying the lower boundary check
might confuse other developers/users

#### Which issue(s) this PR fixes:

Not related to fixing anything, more like a just-in-case

#### Special notes for your reviewer:

Not sure if it matters, though

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/approve

These methods are not exposed and they are used inside kube-proxy that AFAIK will not able to use "wrong" ports, but since we are already validating this looks correct

/assign @danwinship 

Dan for final lgtm

**Comment by danwinship** [comment]
> These methods are not exposed and they are used inside kube-proxy that AFAIK will not able to use "wrong" ports, but since we are already validating this looks correct

lol, I would say the opposite. We should remove the "< 0" check. We shouldn't have errors that can only be returned in case of programmer error.

How about if we change the API to have `port uint16` rather than `port int`?

**Comment by seantywork** [comment]
> > These methods are not exposed and they are used inside kube-proxy that AFAIK will not able to use "wrong" ports, but since we are already validating this looks correct
> 
> lol, I would say the opposite. We should remove the "< 0" check. We shouldn't have errors that can only be returned in case of programmer error.
> 
> How about if we change the API to have `port uint16` rather than `port int`?

Is it up to me to answer that? I'm all for it though because that sounds like a clearer solution.

**Comment by aojea** [comment]
> lol, I would say the opposite. We should remove the "< 0" check.

we have a `<= 0`, 0 is an error with current state, do we want to allow 0 now?

>  We shouldn't have errors that can only be returned in case of programmer error.

These functions are exported, I'm assuming that can be imported elsewhere and those checks, but I do not have a strong opinion, whatever Dan decides sounds good to me

**Comment by seantywork** [comment]
> These functions are exported, I'm assuming that can be imported elsewhere or maybe it was imported in another place that maybe was not safe, anyway I do not have a strong opinion, whatever Dan decides sounds good to me

removed checks and int -> uint16

**Comment by seantywork** [comment]
oops, seems like there ARE other folks importing them with int type!

**Comment by seantywork** [comment]
I've reverted to the original PRd version

**Comment by seantywork** [comment]
+
and according to the error log only, it might be sufficient here to just change a few lines to comply with the uint16 version, but I'm afraid the effect might not be fully known and unexpected far-reaching

**Comment by seantywork** [comment]
To @aojea , @danwinship

Please check out your Kubernetes Slack channel for updates.

Thanks!

**Comment by danwinship** [comment]
note: for small PRs it's pretty much always better to always keep the PR in the form you want it committed in (ie, squash changes back into the original commit rather than adding new commits as you change things).

I still feel like this commit is unnecessary. There is no codepath where that function is ever called with a port number `<= 0` or `> 65535`. If there _was_, it would indicate a bug in the code, not a problem with the configuration or the environment that the end user could fix themselves, so IMO it doesn't make sense to have kube-proxy log it as an error and then continue.

> oops, seems like there ARE other folks importing them with int type!

yes, they would have to be changed as well. But nothing in k/k is exported outside of k/k, so we are able to fix all users of the function.

This is part of a more general problem in kube-proxy / kubernetes as a whole, with how to handle data that is known to be valid but not statically-provable-by-the-compiler to be valid. (e.g., there are lots of places where we parse an IP address and check that it was successful even though the IP address in question was already validated by the apiserver). I'm not sure what the best solution for this is, but IMO it is not to add further checks that we know will always pass.

I'm not going to reject this PR if another maintainer thinks it's a good idea but I'm not going to approve it myself.

**Comment by seantywork** [comment]
> note: for small PRs it's pretty much always better to always keep the PR in the form you want it committed in (ie, squash changes back into the original commit rather than adding new commits as you change things).

Thanks for a great piece of advice.

> This is part of a more general problem in kube-proxy / kubernetes as a whole, with how to handle data that is known to be valid but not statically-provable-by-the-compiler to be valid. (e.g., there are lots of places where we parse an IP address and check that it was successful even though the IP address in question was already validated by the apiserver). I'm not sure what the best solution for this is, but IMO it is not to add further checks that we know will always pass.

Point taken. 
I take that as that you are also not for the change involving uint16 since, according to your words, it doesn't change so much in the essence.

> I'm not going to reject this PR if another maintainer thinks it's a good idea but I'm not going to approve it myself.

I think it's not necessary nor meaningful to wait out for another guy as long as the very first hand-picked assignee thinks it's not worth lgtm on this kind of simple one. 

Thanks for your detailed response, and I do hope our communication continues! :)

**Pull request closed without merging**
