### PR TITLE
Add missing source to ubuntu/util.sh

### LINKED ISSUE #9237: 'kubectl get nodes' returns unknown command
Hi, I'm following the ubuntu.md document to build my kubernetes node, having both master and minion configured in same node and another minion node but I'm getting an error while I run the below command:

$kubectl get nodes
 NAME            LABELS                                 STATUS
10.x.x.x   kubernetes.io/hostname=10.x.x.x   Ready
10.x.x.y   kubernetes.io/hostname=10.x.x.y   NotReady

The 10.x.x.y is the separate minion node. I haven't set the bridge utils yet, is that the reason it's unable to fetch the state?

### PR DESCRIPTION
**Pull request by j3ffml**
Closes #9237. Forgot a lib import in #9227.

@adyanthaya17 let me know if this fixes issue for you.

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM

**Comment by WIZARD-CXY** [comment]
Something is still wrong.I run `kube-up.sh`.It complains

`/home/vcap/kube/util.sh: line 20: /cluster/common.sh: No such file or directory`

seems the `KUBE_ROOT` variable is empty, did you test it?

**Comment by WIZARD-CXY** [comment]
Aha, I found the reason, because this util.sh is remotely executed on the master and minion machine, not on your  machine you clone the repo.So common.sh is not there. I will fix it today.

**Comment by adyanthaya17** [comment]
@jlowdermilk Hi, thank you it did fix the kube-up.sh issue though I'm still facing the issue with kubectl command which tells it's an unknown command.

**Comment by WIZARD-CXY** [comment]
@adyanthaya17 I assume you messed it up.Please download from http://storage.googleapis.com/kubernetes-release/release/v0.18.2/bin/linux/amd64/kubectl
if you use linux.

**Comment by adyanthaya17** [comment]
@WIZARD-CXY I downloaded the kubectl from the link you specified but the kubectl still gives 'command not found'.

**Comment by WIZARD-CXY** [comment]
@adyanthaya17 whar arch do you use? Don't tell me it's not amd64 linux. You need to use arch-specific binary and `chmod 755 kubectl` to make it executable.Then you can definitely use it.

**Pull request merged**
