### PR TITLE
fix error of func TestValidateStatefulSet that updateStrategy

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
spec.updateStrategy.rollingUpdate.partition,but spec.updateStrategy.rollingUpate need "d"
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/cc @xiangpengzhao @zhangxiaoyu-zidif 
thanks

**Comment by zhangxiaoyu-zidif** [comment]
ping @mbohlool 
PTAL

**Pull request merged**
