### PR TITLE
fix shellcheck in test/integration/... and test/kubemark/...

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix shellcheck in test/integration/... and test/kubemark/...

**Which issue(s) this PR fixes**:

Fixes #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by xichengliudui** [comment]
thanks
@liggitt

**Pull request merged**
