### PR TITLE
refactor: Kubernetes role specific files into it's own sls 

### PR DESCRIPTION
**Pull request by j1n6**
CLA: DONE

Reference to comment in Github Issue:https://github.com/kubernetes/kubernetes/issues/23174#issuecomment-223917770

Description:
Salt state `top.sls` file contains mixed conditional logic and role information about Kubernetes master or pool states. These should be separated into it's own state sls file. There are great advantages in doing so:
- As an external state implementation user, I can now include `master.sls` or `pool.sls` state without copy/paste the entire master/pool if & else logics implmeneted in the original `top.sls`
- State code is much more readable in separation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26885)

### CODE REVIEW

**Comment by activars** [comment]
I have multiple emails for Github, signed the CLA with both Google account. It should be fine now.

**Comment by activars** [comment]
Jenkins run run run

**Comment by activars** [comment]
rebase done, Jenkins run run run

**Comment by activars** [comment]
Thanks for planning this into the roadmap.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by mikedanese** [comment]
This never passed tests so closing

**Pull request closed without merging**
