### PR TITLE
Add network packet stats in kubelet Summary API

### LINKED ISSUE #109837: Add network packet stats in kubelet Summary API
### What would you like to be added?

Expose network packet stats in kubelet Summary API:

- RxPackets: Cumulative count of packets received
- RxDropped: Cumulative count of packets dropped while receiving
- TxPackets:  Cumulative count of packets transmitted
- TxDropped: Cumulative count of packets dropped while transmitting

### Why is this needed?

Packet related metrics are important to monitor network.

### Plan
- [ ] Add packet stats in Summary API
- [ ] Expose packet stats using cAdvisor
- [ ] Expose packet stats using CRI (containerd)

### PR DESCRIPTION
**Pull request by CatherineF-dev**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Summary API stats don't have network packet related stats. Those metrics are important for monitoring network.

#### Which issue(s) this PR fixes:

Fixes #109837

-  Add packet stats in Summary API
- Expose packet stats using cAdvisor

#### Does this PR introduce a user-facing change?

```release-note
Add these four network packet stats in Summary API, which have values when using cAdvisor.
- RxPackets: Cumulative count of packets received
- RxDropped: Cumulative count of packets dropped while receiving
- TxPackets:  Cumulative count of packets transmitted
- TxDropped: Cumulative count of packets dropped while transmitting

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
/retest
I think this needs a release note.

**Comment by CatherineF-dev** [comment]
Hi team,

does anyone know where is the release note?  Plan to add it to release note if it's approved.

**Comment by matthyx** [comment]
Thanks @CatherineF-dev I hope we can triage this soon during the next meeting!

**Pull request closed without merging**
