### PR TITLE
Automated cherry pick of #64588: Fix some log issues in flexvolume

### PR DESCRIPTION
**Pull request by louyihua**
Cherry pick of #64588 on release-1.9.

#64588: Fix some log issues in flexvolume

### CODE REVIEW

**Comment by mbohlool** [comment]
@louyihua this PR needs lgtm/approval from original PR's reviewer. Please ping them to do so. Deadline for next patch release is today.

**Comment by louyihua** [comment]
@saad-ali @sjenning

**Comment by louyihua** [comment]
@saad-ali @sjenning Please approve this cherry-pick.

**Pull request merged**
