### PR TITLE
Add ability to disable dumping logs and move log-dump.sh script to new path

### PR DESCRIPTION
**Pull request by shyamjvs**
Cherry-pick of PR #41886 to fix broken tests on 1.5 branch.

/cc @saad-ali @mwielgus

### CODE REVIEW

**Comment by zmerlynn** [comment]
Also, is there a reason this wasn't an automated cherry-pick?

**Comment by shyamjvs** [comment]
Cherry-pick on 1.4 seemed to include a couple of extra lines too that weren't part of the pr (no idea why), so I had to make a change on top of it. This one I created using `git cherry-pick` so I guess it should be the same. SG?

**Comment by mwielgus** [comment]
One approval is missing

**Pull request merged**
