### PR TITLE
Bump go-openapi/jsonpointer and go-openapi/jsonreference versions

### LINKED ISSUE #75653: ci-kuberentes-verify and pull-kubernetes-verify are failing in master, 1.13, 1.14
**Which jobs are failing**:
`ci-kubernetes-verify-beta`

**Which test(s) are failing**:
`verify.godeps` [kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647)

**Since when has it been failing**:
Test has been failing since 3/24, at 9:19

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#verify-1.14

**Reason for failure**:
Error during `hack/verify-godeps.sh`:
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-03-25 02:24:42.529814436 +0000
+++ /tmp/gopath.tmXTzL/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-03-25 03:08:44.614866981 +0000
@@ -1758,12 +1758,12 @@
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonpointer",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonreference",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "8483a886a90412cd6858df4ea3483dce9c8e35a3"
 		},
 		{
Godeps Verify failed.
If you're seeing this locally, run the below command to fix your Godeps.json:
patch -p0 < godepdiff.patch
(The above output can be saved as godepdiff.patch if you're not running this locally)
(The patch file should also be exported as a build artifact if run through CI)
Copying patch to artifacts..
Leaving /tmp/gopath.tmXTzL for you to examine or copy. Please delete it manually when finished. (rm -rf /tmp/gopath.tmXTzL)
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-godeps.sh	825s
```
Due to release v0.19.0 of
[go-openapi/jsonpointer/releases](https://github.com/go-openapi/jsonpointer/releases)
and [go-openapi/jsonreference/releases](https://github.com/go-openapi/jsonreference/releases)
the morning of 3/23.

/milestone v1.14
/kind failing-test
/priority critical-urgent

/cc @smourapina @mariantalla @kacole2 @mortent @spiffxp @nikopen

### PR DESCRIPTION
**Pull request by alejandrox1**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
Bump github.com/go-openapi/jsonpointer and github.com/go-openapi/jsonreference from v0.18.0 to v0.19.0 to fix test failures in 1.14-blocking dashboard, xref: #75653

**Which issue(s) this PR fixes**:

Fixes #75653 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by hoegaarden** [comment]
/hold

I don't want to merge anything new before cutting `v1.14` if not really necessary.

We can check after the cut if we want to bring that in into `v1.14.1` or even leave it for `1.15`.

Also another question is maybe: why is this a blocking test? I think I could find arguments for an against it ... 🤷‍♂️

**Comment by liggitt** [comment]
this is required to fix CI on the release branch.

verify-godeps is a blocking test because we want to ensure the content of vendor actually matches the content of the referenced repositories at those SHAs

/hold cancel

**Comment by hoegaarden** [comment]
I think it is now absolutely fine to merge that, I just wanted to `hold` it for after the release.

Would there be any advantage in opening a PR with [the cherry-pick tooling](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md) in favour of this PR? I don't think so, right?
@kubernetes/patch-release-team

**Comment by spiffxp** [comment]
Manually applying cherry-pick-approved as former v1.14 release lead

**Comment by liggitt** [comment]
thanks. we also need the same fix on 1.13

**Pull request merged**
