### PR TITLE
Set readOnly for CSI mounter

### LINKED ISSUE #61008: CSI NodePublishVolume readonly is never set
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The `readonly` field passed to `NodePublishVolume` is never set. 

In https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L198:

```GO
	err = csi.NodePublishVolume(
		ctx,
		c.volumeID,
		c.readOnly,
		deviceMountPath,
		dir,
		accessMode,
		c.volumeInfo,
		attribs,
		nodePublishSecrets,
		fsType,
	)
```

where `c` is a `csiMountMgr` object that is initialized in the `NewMounter(...)` method in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L113:

```GO
	mounter := &csiMountMgr{
		plugin:       p,
		k8s:          k8s,
		spec:         spec,
		pod:          pod,
		podUID:       pod.UID,
		driverName:   pvSource.Driver,
		volumeID:     pvSource.VolumeHandle,
		specVolumeID: spec.Name(),
		csiClient:    client,
	}
```

Notice the `readonly` field is never set.

**What you expected to happen**:

The `readonly` field should be set to `Pod.PodSpec.Containers[x].VolumeMounts[x].readonly`

**How to reproduce it (as minimally and precisely as possible)**:
Create a CSI volume and set `Pod.PodSpec.Containers[x].VolumeMounts[x].readonly` to true.
Check the value of `readonly` in the CSI `NodePublishVolume(...)` call.
It should be true, but is false.

CC @vladimirvivien @sbezverk 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mlmhl**
**What this PR does / why we need it**:

Currently the `csiMountMgr .readOnly` field is never set, we should set it to `Spec.ReadOnly`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61008 

**Special notes for your reviewer**:

Currently, most of the volume plugins use a `getVolumeSourceFromSpec` method to fetch `VolumeSource` and `ReadOnly` from `volume.Spec`. If the volume is an inline volume, `ReadOnly` is fetched from `Spec.Volume.<SpecificVolumeSource>.ReadOnly`, and if the volume is a `PersistentVolume`, `ReadOnly` is set to `Spec.Readonly`, which comes from `PersistentVolumeClaimVolumeSource.ReadOnly`.

However, as CSI volume plugin is only supported in `PersistentVolume`, so we can just set `ReadOnly` to `Spec.ReadOnly`.

**Release note**:

```release-note
NONE
```

/sig storage

### CODE REVIEW

**Comment by saad-ali** [comment]
As mentioned in https://github.com/kubernetes/kubernetes/issues/61008#issuecomment-372207974, I am leaning towards https://github.com/kubernetes/kubernetes/pull/61014 over this PR.

**Comment by mlmhl** [comment]
@saad-ali  OK, I will close this PR.

**Comment by saad-ali** [comment]
As mentioned in https://github.com/kubernetes/kubernetes/issues/61008#issuecomment-372410286, after today's meeting we decided that consistency with other plugins is better. So we will accept this PR even though `volume.Spec.readonly` is never set correctly. Once that is fixed this should start working correctly for CSI and other volume plugins.

/lgtm
/approve

**Pull request merged**
