### PR TITLE
Intial draft on SeedProvider docs

### PR DESCRIPTION
**Pull request by chrislovecnm**
Alsa more documentation.  We need to reference the config section in the example docs.  There are multiple PRs open in those docs, so at this point I do not want to make a mess.

Let me know if there are docs standard template that will make this more pretty.

### CODE REVIEW

**Comment by bgrant0607** [comment]
add to whitelist

**Comment by bgrant0607** [comment]
ok to test

**Comment by chrislovecnm** [comment]
@bgrant0607 ping

**Comment by bgrant0607** [comment]
@jeffmendoza Could you help review this?

**Comment by bgrant0607** [comment]
@chrislovecnm Did you run hack/update-all.sh? Verification checks appear to have failed.

**Comment by bgrant0607** [comment]
Nevermind @jeffmendoza. It's pretty short.

Thanks, @chrislovecnm LGTM once checks pass.

**Comment by chrislovecnm** [comment]
@bgrant0607 only added one file 😄 Sorry newbie ... Why are jenkins checks failing on docs??

**Comment by jeffmendoza** [comment]
There are some automated checks on all docs. If you add a new one that doesn't conform, checks will fail.

Run `hack/update-generated-docs.sh` and it will update your new doc to conform to the standards.

**Comment by chrislovecnm** [comment]
@jeffmendoza ahhh - is there a n00b guide that covers this??

**Comment by bgrant0607** [comment]
N00b guide: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/how-to-doc.md

**Comment by chrislovecnm** [comment]
@bgrant0607 missed that guide.  Let's see how this commit does!  Appreciate the help.

**Comment by bgrant0607** [comment]
LGTM, thanks!

**Comment by chrislovecnm** [comment]
@bgrant0607 Can a get a one of the following labels  "release-note", "release-note-none", or "release-note-action-required"?

**Pull request merged**
