### PR TITLE
Make apiserver listen on 0.0.0.0 in hyperkube

### LINKED ISSUE #13904: API server is not accessible via VirtualBox/docker-machine after getting started instructions
The (awesome) getting started guide for docker includes support for running on VirtualBox and suggests using docker-machine to manage that. While the provided commands do get the kubernetes cluster up and running /within/ the VirtualBox VM, the cluster's API server is not accessible from /outside/ the VM without further hackery.

The `master.json` file configures the API server to listen on 127.0.0.1:

``` json
    {
      "name": "apiserver",
      "image": "gcr.io/google_containers/hyperkube:VERSION",
      "command": [
              "/hyperkube",
              "apiserver",
              "--portal-net=10.0.0.1/24",
              "--address=127.0.0.1",
              "--etcd-servers=http://127.0.0.1:4001",
              "--cluster-name=kubernetes",
              "--v=2"
        ]
    },
```

https://github.com/kubernetes/kubernetes/blob/dd5f970679e81c4c4338788f0458f0f17b6a1095/cluster/images/hyperkube/master.json#L25

The following commands instead reconfigure kubelet to create API servers listening on all addresses (assuming the kubelet container is named `kubelet`):

``` console
docker exec kubelet perl -pi -e 's/address=127.0.0.1/address=0.0.0.0/' /etc/kubernetes/manifests/master.json
docker restart kubelet
```

With this adjustment, everything works as expected and a user can connect to the API server on the VirtualBox's IP address:

``` console
$ kubectl -s $(docker-machine ip dev):8080 get nodes
NAME        LABELS                             STATUS
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready
```

Based on the above, I'd suggest modifying `master.json`'s API server configuration to listen on 0.0.0.0. I can imagine that this might feel icky from a security perspective, but I would hope users are not simply running these images in production without modification. Further, the other containers described in the guide listen on 0.0.0.0 (including etcd), so it seems no less secure (and more useful) if the API server does as well.

Thanks!

Reference:

https://github.com/kubernetes/kubernetes/blob/8de12acc3d3ac391f28c4854f557421dac5cbcea/docs/getting-started-guides/docker.md#step-two-run-the-master

``` console
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

``` console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

``` console
$ uname -a
Darwin radioactivity.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

``` console
$ VBoxManage -v
4.3.28r100309
```

``` console
$ docker-machine --version
docker-machine version 0.4.0-dev (HEAD)
```

### PR DESCRIPTION
**Pull request by oszi**
This PR closes #13904.

There was no sign of life around that issue so as trivial this is I hope we can merge this.

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM, but can you add a warning to the hyperkube docs that this opens up the API server on all addresses?  If you did this on a box on the network you are essentially allowing anyone to run code on your machine.

**Comment by oszi** [comment]
@brendandburns I noted the change in the single-node getting started guide. Should we maybe make it stand out more? I'm not aware of other affected docs.

**Comment by brendandburns** [comment]
Yeah, I'm changing my mind on this (sorry!)  I think the right answer here is to use an SSH tunnel rather than open up to all interfaces.

I'm ok if you update the docs to describe how to listen on `0.0.0.0.` but I don't think that it should be the default.

**Comment by oszi** [comment]
The multi-node manifest only differs in this one thing. So I agree with not merging this.
Originally, I wanted it to listen on 0.0.0.0 because I wanted to run it in Docker-in-Docker without net=host (where there is no sshd).

**Pull request closed without merging**
