### PR TITLE
Honor InsecureSkipVerify flag

### LINKED ISSUE #8211: insecure-skip-tls-verify doesn't work for 'exec'
Trying to use the 'kubectl exec' command and it failes with the following error

```
Error: Error sending request: Get https://mydomain.com:6443/api/v1beta3/proxy/nodes/node3.c.my-project.internal/exec/default/myserver-522124b-3kgs5/rest-server?command=%2Fbin%2Fbash&error=1&output=1: x509: certificate is valid for 10.240.125.40@1431531404, not mydomain.com
```

Using kubelet, kube-apiserver and kubectl 0.16 and this is run on CoreOS 675.0.0 and GCE.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #8211

### CODE REVIEW

**Comment by liggitt** [comment]
@ncdc PTAL

**Comment by ncdc** [comment]
@liggitt do we want to try to add some tests?

**Comment by ncdc** [comment]
Otherwise LGTM

**Comment by liggitt** [comment]
I'm not going to have time to work on tests before next week

**Comment by liggitt** [comment]
Added tests anyway. Looking at the diff ignoring whitespace makes it less intimidating: https://github.com/kubernetes/kubernetes/pull/14889/files?w=1

**Comment by liggitt** [comment]
@ncdc PTAL

**Comment by ncdc** [comment]
Shippable failure was a flake (integration.go timed out).

**Comment by ncdc** [comment]
LGTM

**Pull request merged**
