### PR TITLE
Added NetworkUnavailable toleration to pod using host network.

### LINKED ISSUE #61312: Add network unavailable toleration to the Pod using host network
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

If `TaintNodesByCondtion` enabled, it's better to add `NetworkUnavailable` toleration to the pod using host network.

/sig node

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61312 

**Release note**:
```release-note
If pod using host network, `node.kubernetes.io/network-unavailable` toleration is added to the pod automatically.
```

### CODE REVIEW

**Comment by k82cn** [comment]
Because of Pod version issue, we can not get `hostNetwork` value in admission controller.

**Comment by liggitt** [comment]
> Because of Pod version issue, we can not get hostNetwork value in admission controller.

Can you clarify what you mean by this?

**Comment by k82cn** [comment]
`.spec.hostNetwork` belongs to `v1.Pod`; but this admission is using `api.Pod` which did not have `.spec.hostNetwork` member :(

**Comment by liggitt** [comment]
When the api server deals with a pod internally, the host network setting is relocated to the security context structure from the v1 spec.hostNetwork field

**Comment by liggitt** [comment]
See

https://github.com/kubernetes/kubernetes/blob/ebae09e7416b4e7e045af242bd2e8b36a664b154/pkg/apis/core/v1/conversion.go#L371-L415

**Comment by k82cn** [comment]
Interesting, test with `cluster/addons/metadata-proxy/gce/metadata-proxy.yaml`, the toleration was not appended :(.


```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
...
spec:
  updateStrategy:
    type: RollingUpdate
  template:
...
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: metadata-proxy
      hostNetwork: true    <=============== using host network!
      dnsPolicy: Default
```

**Comment by k82cn** [comment]
@liggitt , thanks for your comments; it works as you said. My test was failed because this admission is not enabled in local-up-cluster.

Removed WIP, that's ready for review now :)

**Comment by liggitt** [comment]
> @liggitt , thanks for your comments; it works as you said. My test was failed because this admission is not enabled in local-up-cluster by default.

What are the implications of putting this in an optional admission plugin? Are there new taints being added in 1.10 that will break things if this admission plugin is not enabled?

**Comment by k82cn** [comment]
No new taints in 1.10; but when `ScheduleDaemonSet` enabled, the Pod using host network need to tolerate network unavailable taints.

**Comment by liggitt** [comment]
> the Pod using host network need to tolerate network unavailable taints.

"sometimes auto-added" tolerations don't seem particularly valuable... portable pod specs will need to include them explicitly

**Comment by jdumars** [comment]
Note, we'll need to revisit this in 1.11.

**Comment by k82cn** [comment]
close this for now; will re-open it if necessary.

**Pull request closed without merging**
