### PR TITLE
CRI: Remove the mount name and port name.

### LINKED ISSUE #33526: kubelet.makeMounts() is mixing the usage of the kubecontainer.Mount.Name
[kubelet.makeMounts](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/kubelet.go#L1207) is a help function that runs during each container creation.
It takes a **pod spec**, and a **container spec** to generate **kubecontainer.Mount (name, container-path, host-path, readonly, selinux_relabel)** by matching the container spec's [volume mount](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/api/types.go#L882-L893) to the pod spec's [volumes](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/api/types.go#L172-L181).

But meanwhile, it's also generating arbitrary **kubecontainer.Mount** that has no corresponding volumes in the pod spec, such as [mounting host machine's /etc/hosts](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/kubelet.go#L1247-L1252).

Thus when runtime tries to look for the volumes by the volume name in the [interface](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L104), it cannot find any volumes.

Another issue is if container spec defines a `subPath` in the volume mount, then we will end up with two **kubecontainer.Mount** that have same names, same container paths, but different host paths. This is not supported by rkt as one volume name should map to one host path.

So the action required here is:
**Option 1**: Generate correct volumes for these arbitrary mounts and subpath mounts, and pass them through `PodSandboxConfig` during the creation of the sandbox. Later it passes the runtime the mounts object (volume_name, container_path), and runtime is able to do the correct mounts by finding the volumes through names.

This implies the mounts for each apps within the sand box must have a pre-established volumes.

**Option 2**: Remove the mount name, or at least change that to not be the volume name. Require runtime to support mounting any **container-path:host-path** pairs, basically requires runtime to **know nothing about volumes**

cc @yujuhong @feiskyer @euank @alban @lucab @jonboulle

### LINKED ISSUE #33873: Discuss about some `name` fields in the CRI
So during implementing the CRI, I found actually the [name of the Mount](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L104) and the [name of the PortMapping](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L90) are not useful for several reasons.

- Docker doesn't support names for these two things
- rkt has a more strict rule about name format, so we are not relying on these names in CRI.
- There is a misuse of the `Mount name`, which causes the mount name to be not unique (Related to #33526). Where in most case, the `Mount name` comes from the volume's name in the k8s API, but sometimes it's generated by kubelet. (e.g. the `/etc/hosts` mounts).

So given these facts, I suggest we just remove the name fields from the CRI.

/cc @kubernetes/sig-node @kubernetes/sig-rktnetes

### PR DESCRIPTION
**Pull request by yifan-gu**
Per discussion on https://github.com/kubernetes/kubernetes/issues/33873.

Currently the mount name is not being used and also involves some
incorrect usage (sometimes it's referencing a mount name, sometimes
it's referecing a volume name), so we decide to remove it from CRI.

The port name is also not used, so remove it as well.

Fix #33873
Fix #33526 

/cc @kubernetes/sig-node @kubernetes/sig-rktnetes

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33970)

### CODE REVIEW

**Comment by euank** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM

**Comment by feiskyer** [comment]
LGTM

**Comment by yifan-gu** [comment]
Updated the `hack/verify-flags/exceptions.txt` since the api.pb.go has changed.

**Pull request merged**
