### PR TITLE
cleanup: fix log capitalization in scheduler

### PR DESCRIPTION
**Pull request by wangyx1992**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix some errors start with capital letters in scheduler.

#### Which issue(s) this PR fixes:
Ref #15863

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
> Which issue(s) this PR fixes:
> Fixes #15863

Would you mind rewording it to "Ref #15863"?

**Comment by wangyx1992** [comment]
> > Which issue(s) this PR fixes:
> > Fixes #15863
> 
> Would you mind rewording it to "Ref #15863"?

Thanks for the suggestion, it has been reworded already.

**Pull request merged**
