### PR TITLE
Fix a dead link in cluster/update-storage-objects.sh

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**: This PR fixes a dead link in cluster/update-storage-objects.sh.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by superbrothers** [comment]
@zmerlynn Thank you for your approval. However you might need to write `/approve no-issue` in a comment in order to merge this PR.

**Comment by fejta** [comment]
/retest
Automatic retester of approved PRs with test failures, please send feedback to fejta

**Pull request merged**
