### PR TITLE
cmd/kubelet: remove deprecated otel NewNoopTracerProvider

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will replace the use of the deprecated `go.opentelemetry.io/otel/trace.NewNoopTracerProvider` 
 by the recommended `go.opentelemetry.io/otel/trace/noop.NewTracerProvider`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by endocrimes — COMMENTED** [review]
/triage accepted
/priority important-longterm 
^ dependency health
/lgtm

**Comment by mrunalp** [comment]
Any reason to just update one file at a time? I see around ~30 instances in the repo which we can get together or do per component.

**Comment by endocrimes** [comment]
@mrunalp I imagine that will mostly end up sitting in "waiting for approver" nightmare state for a while

**Comment by TommyStarK** [comment]
Yes exactly I thought it would be more efficient from an approval pov

**Comment by TommyStarK** [comment]
@endocrimes @mrunalp I've updated the PR so the changes are applied to the kubelet related code under the `cmd` and `pkg` folders.

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
