### PR TITLE
Getting Started Guide style update

### PR DESCRIPTION
**Pull request by karlkfi**
- Don't indent top-level lists
- Use 2 space list item indentation, unless using multi-line items, then use 4 space indents
- Use underline for page title
- Auto-generate table of contents
- Start with lvl 2 headers (lvl 1 headers look too much like the page title)
- Empty line before new lists

The 4-space list indent is critical to how redcarpet renders lists as html on kubernetes.io. The rest are just for stylistic consistency.

### CODE REVIEW

**Comment by karlkfi** [comment]
e2e flake or bug in master:

```
Summarizing 1 Failure:

[Fail] Kubectl client Kubectl run job [AfterEach] should create a job from an image when restart is Never [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1159

Ran 116 of 206 Specs in 612.750 seconds
FAIL! -- 115 Passed | 1 Failed | 2 Pending | 88 Skipped 
```

**Comment by karlkfi** [comment]
This will need to be cherry-picked to release-1.1 and then the gh-pages updated in order to get this to kubernetes.io

**Comment by karlkfi** [comment]
Since this modifies the guide readme, can you take a look @bgrant0607 ? The changes are pretty trivial, just style and formatting. I wasn't ambitious enough to refactor all the docs...

**Comment by erictune** [comment]
lgtm

**Pull request merged**
