### PR TITLE
Remove deadcode in pkg/util/node

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove deadcode in pkg/util/node, discuss at: https://github.com/kubernetes/kubernetes/pull/126478#discussion_r1712645401

/cc @danwinship 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm

`GetNodeHostIP` is an unused single-stack version of `GetNodeHostIPs` that nobody should be using any more.

`GetNodeIP` polls the apiserver until the node IPs have been set on the named `Node` object, but:
- kube-proxy no longer uses it because it has its own private (new-and-improved dual-stack) version of it.
- kubelet doesn't need it.
- anything that runs in a pod doesn't need it because it can just request `hostIPs` via the downward API
- control-plane components can't use it because they can't assume they're running on a node
- nothing else in k/k always runs on a node but sometimes runs outside of a pod

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

good explanation from @danwinship on why it is bad top have those here.

**Pull request merged**
