### PR TITLE
Removed obsolete argument 'cloud_provider'. Otherwise service failed …

### PR DESCRIPTION
**Pull request by eghobo**
…with 'kube-apiserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT'

### CODE REVIEW

**Comment by mikedanese** [comment]
@doublerr

**Comment by lavalamp** [comment]
Looks correct, if we don't have a rackspace cloud provider.

**Comment by eghobo** [comment]
I signed it!

**Comment by mikedanese** [comment]
LGTM. Thanks!

**Comment by mikedanese** [comment]
I'm not sure that we don't... I'll do a deep review of this tomorrow.

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/pkg/cloudprovider/rackspace

**Comment by eghobo** [comment]
I signed it!

**Comment by eghobo** [comment]
@mikedanese - any updates? @thommay - could you help?

**Comment by mikedanese** [comment]
I don't know if this is right. We do have a rackspace cloud_provider: 

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/rackspace/rackspace.go#L94

**Comment by eghobo** [comment]
@mikedanese - agree, but I still not sure how to test this class. Could you point me to any integration tests for cloud providers?

**Comment by mikedanese** [comment]
There are only unit tests for the cloud provider plugin. I don't believe that end to end test run on rackspace (someone in the community would have to spend some time/compute to set that up).

I don't believe this is the solution. There is a rackspace cloud provider and it seems to be wired up correctly. We don't want to disable this for the rackspace getting started guide. Can you create a support issue and paste the command you are using to start the apiserver and the apiserver logs? Then we can start to debug this.

**Pull request closed without merging**
