### PR TITLE
fix goroutine leak in the DeleteCollection

### PR DESCRIPTION
**Pull request by sxllwx**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In our k8s cluster, 3 kube-apiservers are running and consume a lot of memory resources. Through analysis of Heap and Goroutine Profile, we can find that a lot of memory is used by DeleteCollection and has not been released. After analysis, I think there is a goroutine leak in DeleteCollection.

> Sorry, because the company's regulations cannot provide a complete profile, here are some screenshots.

image

image

image

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

All workers exit, which will cause the permanent block of the task producer to be in the sent code block.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1131-L1139

I think that in the process of requesting the `DeleteCollection` interface to kube-apiserver, if a Leader switch or other error occurs in etcd, this bug will be triggered.

#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver: fix a memory leak when deleting multiple objects with a deletecollection.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kube-apiserver: fix a memory leak when deleting multiple objects with a deletecollection.
```

**Review by wojtek-t — COMMENTED** [review]
Some small comments.

**Comment by wojtek-t** [comment]
Heh... - I didn't make the cancelling on time.

@aojea - https://github.com/kubernetes/kubernetes/pull/105606#discussion_r733695697 is a valid comment
We should send a follow up to it.

**Comment by sxllwx** [comment]
> hmm @sxllwx this test pass with and without this patch 🤔

Without this patch, the new UT (TestStoreDeleteCollectionWorkDistributorExited)[https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go#L2127] cannot pass.

**Pull request merged**
