### PR TITLE
Bug fix 72757.Removed deprecated label kubernetes.io/cluster-service

### PR DESCRIPTION
**Pull request by ramnar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes deprecated labels in kuberenetes add-ons

**Which issue(s) this PR fixes**:

Remove deprecated label kubernetes.io/cluster-service in yaml files of kubernetes add-ons. Ref #72757

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM thanks.

/ok-to-test
/priority backlog

**Comment by BenTheElder** [comment]
/assign @spiffxp 
this seems reasonable but I'm not sure what the full implications are, assigning a cluster/ approver

**Comment by MrHohn** [comment]
@ramnar Why are these not included in https://github.com/kubernetes/kubernetes/pull/73637?

**Comment by ramnar** [comment]
@MrHohn This change is required in many yaml files spread across many SIGS in cluster/addons. I felt including all the changes in a single pull request will be too big for review

**Comment by spiffxp** [comment]
/hold
Wait, hang on... how does `kubectl cluster-info` get the necessary info when this label is removed?

**Comment by ramnar** [comment]
Hi,
I hope this can be this can be looked into now as similar pull request #73637 is merged
Regards,
Ram

**Comment by spiffxp** [comment]
/hold cancel
/approve
/lgtm
Looking more closely, this doesn't touch any `Service` objects

**Pull request merged**
