### PR TITLE
fix resource scale overflow

### LINKED ISSUE #99231: Overflow when the resource is negative
#### What happened:

Get the size difference of the resources:
```
// import "k8s.io/apimachinery/pkg/api/resource"

res1 := resource.MustParse("1.0Gi")
res2 := resource.MustParse("10.0Gi")
res1.Sub(res2)
fmt.Println(res1.Value())
```

Result: `8783067658`

#### What you expected to happen:

The correct value should be -9.0Gi: `-9663676416`

#### Anything else we need to know?:

Solution：

Replace `unscaled.Cmp(maxInt64) < 0` with `unscaled.CmpAbs(maxInt64) < 0` in [scale_int.go](https://github.com/kubernetes/kubernetes/blob/release-1.20/staging/src/k8s.io/apimachinery/pkg/api/resource/scale_int.go#L61)

/sig api-machinery

### PR DESCRIPTION
**Pull request by spyyang**
#### What type of PR is this?

/kind bug
/sig api-machinery

#### What this PR does / why we need it:

This PR fixes the overflow bug when the resource is negative. Sometimes negative resources can be used, e.g. computing the diff value of LVM disks.

#### Which issue(s) this PR fixes:

Fixes #99231 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by fedebongio** [comment]
Thank you for your pr! can you please also provide a unit test as part of it? 
Cheers!

**Comment by spyyang** [comment]
> Thank you for your pr! can you please also provide a unit test as part of it?
> Cheers!

ok, i've added a unit test.

**Comment by spyyang** [comment]
/ping @fedebongio
Someone needs to approve it?

**Pull request closed without merging**
