### PR TITLE
storage: enhance test for ValidateCSIDriverUpdate

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This revised test changes one field at a time in various ways. This
ensures that one failure reason doesn't mask the other.

An incorrect comment also gets fixed.

**Which issue(s) this PR fixes**:

Suggested in https://github.com/kubernetes/kubernetes/pull/80568#pullrequestreview-272836101.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by pohly** [comment]
@msau42 I said yesterday that the PR needs to be rebased, but it actually still applies cleanly, so I won't rebase.

/remove-lifecycle stale
/retest

**Comment by pohly** [comment]
Oh, this is an old one... but still relevant.

/remove-lifecycle stale
/assign @smarterclayton 

For approval.

**Comment by jtslear** [comment]
Hello, @jtslear as Bug Triage Shadow for 1.19. Assigning to sig-storage. If this is incorrect, please notify us and remove the sig.

/sig storage

**Pull request merged**
