### PR TITLE
Manually cherry pick part of #58712: Add better event handling for deleted Pods

### LINKED ISSUE #69926: Scheduler fails to schedule pods due to "Insufficient CPU" while nodes have enough resources
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We create and delete  a large number of pods in our k8s cluster every day. Every time after a few hours, some new pods stay in `Pending` state and can't be created correctly. Describing these pods shows `FailedScheduling` due to `Insufficient cpu`, while describing nodes shows that there are still enough computing resources. After restarting the kube-scheduler, everything goes back to normal.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create and delete a large number of pods in cluster continuously.

**Anything else we need to know?**:
1. We tried to debug this problem by adding some logs in kube-scheduler source code and found that the `requestedResource` of nodes in scheduler cache was much higher than actual `requestedResource` of nodes in the cluster.

2. We noticed many error messages in kube-scheduler's log as follows:
    `kube-scheduler[21493]: E1017 13:33:39.871893   21493 factory.go:166] unable to handle object in *factory.ConfigFactory: cache.DeletedFinalStateUnknown`
This error will lead scheduler to fail to `deletePodFromCache` and eventually cause the above problem.

3. Our k8s version is 1.8.13, I found this bug has been fixed in version 1.10(#58712), so we need to cherry pick that PR selectively.

4. Some related issues: #33777 #45237 #37232

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.13
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jimmy-zh**
**What this PR does / why we need it**:
Manually cherry pick part of #58712 on release-1.8.

#58712: This PR makes the event handling logic more robust by adding logic to check for cache.DeletedFinalStateUnknown in our event handler filters.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69926

**Special notes for your reviewer**:
See #69926 for more details.

**Release note**:

```release-note
Stability: Make Pod delete event handling of scheduler more robust.
```
/sig scheduling

### CODE REVIEW

**Comment by jimmy-zh** [comment]
cla

**Comment by jimmy-zh** [comment]
I signed it

**Review by bsalamat — CHANGES_REQUESTED** [review]
The current released "patch" version of K8s is 1.12. Version 1.11 and 1.10 are still supported, but 1.9 and older are considered EOL. We do not backport fixes to those versions.

**Comment by jimmy-zh** [comment]
I signed it

**Comment by idealhack** [comment]
It seems this is a fix worth merge?

/kind bug
/reopen
@kubernetes/sig-scheduling-bugs

**Comment by bsalamat** [comment]
> The problem we encountered has been described in detail in #69926. The scheduler of version 1.8 and 1.9 will eventually become unavailable without this fix. Many users, including our own customers, still rely on version 1.8 or 1.9, so this pr should be valuable.

I understand, but 1.8 and 1.9 are no longer built and released officially. So, even if you backport patches, no more dot versions will be built and released. I would strongly recommend upgrading your clusters.

**Comment by liggitt** [comment]
/close

no additional 1.8 releases are planned

**Pull request closed without merging**
