### PR TITLE
Ephemeral storage test fix

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What this PR does / why we need it:

This PR will test possible ephemeral-storage kubeadm fixes.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
closing some stale PRs. please reopen if testing is still needed here.

/close

**Comment by jackfrancis** [comment]
thx @neolit123

**Pull request closed without merging**
