### PR TITLE
[KMSv2] remove key hierarchy in reference implementation

### PR DESCRIPTION
**Pull request by aramase**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- Remove key hierarchy from reference implementation as it's no longer used
- Update mock kms plugin to use remote service

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by enj** [comment]
/lgtm
/approve
/milestone v1.27

With #116155 merged we no longer need plugins to implement a key hierarchy.  Currently this code is only used in tests but is exported via the `k8s.io/kms` staging repo.  It would be best to not expose code that we do not want KMS v2 plugin authors to use.

**Comment by aramase** [comment]
/hold

to confirm `pull-kubernetes-e2e-kind-kms` passes

**Comment by enj** [comment]
/hold cancel

KMS job is green.

**Pull request merged**
