### PR TITLE
e2e lifecycle: reduce test flackiness

### PR DESCRIPTION
**Pull request by matthyx**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Attempting to reduce flakes in SidecarContainers e2e tests using the container_lifecycle_pod_construction methods.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
/assign @bart0sh 
Ed, I did this change to keep the order as mentioned in the other PR, do you think it helps deflaking them?

**Comment by aojea** [comment]
I don't fully understand the intent, but bear in mind that CI environments are always resource contrained, and we have seens pauses in the order of seconds for processes ... so don't expect some test that depends on subsecond operations to be reliable

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/pull/124499#issuecomment-2087353999

**Comment by matthyx** [comment]
> I don't fully understand the intent, but bear in mind that CI environments are always resource contrained, and we have seens pauses in the order of seconds for processes ... so don't expect some test that depends on subsecond operations to be reliable 

It's the quite the opposite, I want to make sure 2 events happening almost at the same time are properly ordered.

**Comment by bart0sh** [comment]
> [#124499 (comment)](https://github.com/kubernetes/kubernetes/pull/124499#issuecomment-2087353999)
> 
> I think we can use the stable sort to deflake it.

@matthyx Do we need to sort the output at all?

**Comment by matthyx** [comment]
> > [#124499 (comment)](https://github.com/kubernetes/kubernetes/pull/124499#issuecomment-2087353999)
> > I think we can use the stable sort to deflake it.
> 
> @matthyx Do we need to sort the output at all?

not sure... maybe @tzneal remembers?

**Comment by tzneal** [comment]
> > > [#124499 (comment)](https://github.com/kubernetes/kubernetes/pull/124499#issuecomment-2087353999)
> > > I think we can use the stable sort to deflake it.
> > 
> > 
> > @matthyx Do we need to sort the output at all?
> 
> not sure... maybe @tzneal remembers?

I sorted it as a lot of the checks are of the type "does X happen before Y". We don't particularly care about the timing involved, just the ordering.

**Comment by bart0sh** [comment]
> I sorted it as a lot of the checks are of the type "does X happen before Y". We don't particularly care about the timing involved, just the ordering.

I thought that messages come ordered by their time naturally. Isn't it the case?

**Comment by tzneal** [comment]
> > I sorted it as a lot of the checks are of the type "does X happen before Y". We don't particularly care about the timing involved, just the ordering.
> 
> I thought that messages come ordered by their time naturally. Isn't it the case?

Within a container, yes, but we [aggregate](https://github.com/kubernetes/kubernetes/blob/d387c0c9034287a7ffd424325d36970b62ce6027/test/e2e_node/container_lifecycle_pod_construction.go#L316) the output of all the containers within the pod.

Its to handle testing things like "Does init container start and finish before a non-init main container?". There were a lot more of these sorts of tests with sidecars.

**Comment by bart0sh** [comment]
> The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-node-swap-fedora	[8833b4d](https://github.com/kubernetes/kubernetes/commit/8833b4def00d6d66c81f2b351159ddb45b7e5f36)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124645/pull-kubernetes-node-swap-fedora/1785708000204296192)	false	`/test pull-kubernetes-node-swap-fedora`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=124645). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Amatthyx). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

This is concerning. I'm generally ok with this PR, but the job is still flaking.

BTW, can you point me out to other flaking jobs, if any?

**Comment by bart0sh** [comment]
Example of failing test case that made me think that the test case is not correct:
```
• [FAILED] [48.513 seconds]
[sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle [It] should terminate sidecars simultaneously if prestop doesn't exit [sig-node, NodeFeature:SidecarContainers]
k8s.io/kubernetes/test/e2e_node/container_lifecycle_test.go:2597

  Timeline >>
  STEP: Creating a kubernetes client @ 05/01/24 16:48:13.44
  STEP: Building a namespace api object, basename containers-lifecycle-test @ 05/01/24 16:48:13.44
  I0501 16:48:13.476283 2820 framework.go:275] Skipping waiting for service account
  W0501 16:48:13.573970    2820 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "restartable-init-1", "restartable-init-2", "restartable-init-3", "regular-1" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "restartable-init-1", "restartable-init-2", "restartable-init-3", "regular-1" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "restartable-init-1", "restartable-init-2", "restartable-init-3", "regular-1" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "restartable-init-1", "restartable-init-2", "restartable-init-3", "regular-1" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  STEP: Analyzing results @ 05/01/24 16:49:01.805
  I0501 16:49:01.806150 2820 container_lifecycle_test.go:2685] Unexpected error: 
      <*errors.errorString | 0xc000c29af0>: 
      couldn't find that restartable-init-2 started after restartable-init-1, got
      0) 2024-05-01 16:48:18.688 +0000 UTC restartable-init-1 Starting
      1) 2024-05-01 16:48:18.71 +0000 UTC restartable-init-2 Starting
      2) 2024-05-01 16:48:18.942 +0000 UTC restartable-init-2 Started
      3) 2024-05-01 16:48:18.945 +0000 UTC restartable-init-1 Started
...
```
I took this from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/124645/pull-kubernetes-node-swap-fedora/1785708000204296192/build-log.txt

It expects that `restartable-init-2 started after restartable-init-1` which doesn't reflect reality it seems.

**Comment by bart0sh** [comment]
Despite flaking tests, I'm ok to merge this PR for two reasons:
- it doesn't fix all the flakes, but it has good fixes anyway
- trying to fix everything by one PR may gather a lot of changes and break jobs as happened before, so I'd suggest incremental changes

/lgtm

**Comment by bart0sh** [comment]
/assign @SergeyKanzhelev 
for approval

**Comment by bart0sh** [comment]
@matthyx @tzneal 

> It expects that restartable-init-2 started after restartable-init-1 which doesn't reflect reality it seems.

Would it make sense to use "Starting" instead of "Started" [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/container_lifecycle_pod_construction.go#L153)? Not in this PR for sure.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by matthyx** [comment]
> @matthyx @tzneal
> 
> > It expects that restartable-init-2 started after restartable-init-1 which doesn't reflect reality it seems.
> 
> Would it make sense to use "Starting" instead of "Started" [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/container_lifecycle_pod_construction.go#L153)? Not in this PR for sure.

I don't think so, because `Started` reflects startupProbe success which should be the green light for the next initContainer... if we switch to `Starting` it would only check that we start in the right order without taking into account probes.

**Comment by bart0sh** [comment]
@matthyx 
> I don't think so, because Started reflects startupProbe success which should be the green light for the next initContainer...

It's not entirely obvious when I looked at the code. Here is what's happening between "Starting" and "Started" log entries:
```
fmt.Fprintf(&cmd, "echo %s '%s Starting %d' | tee -a %s >> /proc/1/fd/1; ", timeCmd, name, c.StartDelay, containerLog)
fmt.Fprintf(&cmd, "_term() { sleep %d; echo %s '%s Exiting' | tee -a %s >> /proc/1/fd/1; exit %d; }; ", c.TerminationSeconds, timeCmd, name, containerLog, c.ExitCode)
fmt.Fprintf(&cmd, "trap _term TERM; ")
if c.StartDelay != 0 {
	fmt.Fprint(&cmd, sleepCommand(c.StartDelay))
}
// You can check started file to see if the container has started
fmt.Fprintf(&cmd, "touch started; ")
fmt.Fprintf(&cmd, "echo %s '%s Started' | tee -a %s >> /proc/1/fd/1; ", timeCmd, name, containerLog)
```

I still don't see how is this related to a startupProbe. Can you point me out?

**Comment by matthyx** [comment]
initContainers are starting one after the other (keeping the order in the slice):
- regular initContainers are run to completion before the next one starts
- [sidecar](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers#proposal) initContainers should be `Started` and have `postStart` completed

If we want to make sure `restartable-init-2` is launched after `restartable-init-1` has started we should add a startupProbe to the first one that looks for the creation of the file `started`.

**Comment by bart0sh** [comment]
Thank you for the explanations! I'm not sure I fully understood it, but it's more clear now. I'm still wondering how "Started" log entry depends on `postStart` or `startupProbe`. The code is pretty simple: there are a couple of things that happen between "Starting" and "Started" log entries and neither of them depends on anything similar to what you've mentioned:
- setting TERM reaction
- touching `started`

According to your explanation "Started" log entry should only appear in the container log after `postStart` or/and  `startupProbe` succeed, which is not the case. So the code should still be modified to achieve that, I guess.

**Comment by matthyx** [comment]
> Thank you for the explanations! I'm not sure I fully understood it, but it's more clear now. I'm still wondering how "Started" log entry depends on `postStart` or `startupProbe`. The code is pretty simple: there are a couple of things that happen between "Starting" and "Started" log entries and neither of them depends on anything similar to what you've mentioned:
> 
> * setting TERM reaction
> * touching `started`
> 
> According to your explanation "Started" log entry should only appear in the container log after `postStart` or/and `startupProbe` succeed, which is not the case. So the code should still be modified to achieve that, I guess.

Not quite, if you want to properly use the started file, you should add a startupProbe on `restartable-init-1` that checks for that file presence, and in that case you should see `restartable-init-2` start after `restartable-init-1` got into `Started` state.

**Comment by matthyx** [comment]
The log refers to events happening on the container level, but in order to lift this information to the kubelet you have to define a startupProbe, and in that case kubelet will use this knowledge to start sidecars after one another instead of almost immediately.
I might open a PR tonight to add these probes...

**Comment by bart0sh** [comment]
@matthyx It looks like we're talking about the same thing, but somehow don't understand each other.
I'm talking about current code that produces "Started" log entries that don't depend on either `startupProbe` or `postStart` and about `StartBefore` function that uses "Started" log entries to determine which container starts first and which second.
Even if you define a startupProbe it wouldn't change this.
As far as I understand the code should be changed to only produce "Started" log entry after the probe succeeds, which is not the case now.

**Pull request merged**
