### PR TITLE
Update fluent bit version to 1.8.10 for GKE windows container

### PR DESCRIPTION
**Pull request by liurupeng**
#### What type of PR is this?
/kind maintenance

#### What this PR does / why we need it:
Update component (fluent bit) version on GKE windows container
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

**Comment by liurupeng** [comment]
Hi, I have signed the CLA, can you take a look? thanks!

**Review by ibabou — CHANGES_REQUESTED** [review]
Can you squash both commits together? Just to keep the git history cleaner.

**Review by ibabou — APPROVED** [review]

**Comment by mauriciopoppe** [comment]
I'm investigating why Windows CI builds of PD CSI aren't running in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/892, the error that I see in the bootstrap is

```
2022/01/25 20:03:33 GCEMetadataScripts: windows-startup-script-ps1: C:\flb-exporter\flb-exporter.exe corrupted, SHA256 @{Algorithm=SHA256; Hash=C808C9645D84B06B89932BD707D51A9D1D0B451B5A702A5F9B2B4462C8BE6502; Path=C:\flb-exporter\flb-exporter.exe} doesn't match expected f84bc732c9078421930cf9791c52066a56e692836e13857133d9927a35663a6b
2022/01/25 20:03:33 GCEMetadataScripts: windows-startup-script-ps1: Hash validation of https://storage.googleapis.com/gke-release/winnode/fluentbit-exporter/v0.17.0/flb-exporter-v0.17.0.exe failed. Will retry. Error: System.Management.Automation.RuntimeException: C:\flb-exporter\flb-exporter.exe corrupted, SHA256 @{Algorithm=SHA256; Hash=C808C9645D84B06B89932BD707D51A9D1D0B451B5A702A5F9B2B4462C8BE6502; Path=C:\flb-exporter\flb-exporter.exe} doesn't match expected f84bc732c9078421930cf9791c52066a56e692836e13857133d9927a35663a6b
```

I think that this hash belongs to loging exporter and not logging agent, probably we should revert this line

```
$LOGGINGEXPORTER_HASH = 'f84bc732c9078421930cf9791c52066a56e692836e13857133d9927a35663a6b'
```

**Pull request merged**
