### PR TITLE
Add a flag to disable legacy APIs

### PR DESCRIPTION
**Pull request by brendandburns**
@bgrant0607 @nikhiljindal 

Fore-runner to permanent disabling.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
Elsewhere we call these PreV1beta3 (search the code).

Also, we're going to need to be able to remove these APIs from list of versions understood for conversion.

**Comment by nikhiljindal** [comment]
Thanks! I need this for testing https://github.com/GoogleCloudPlatform/kubernetes/pull/7819.

https://github.com/GoogleCloudPlatform/kubernetes/pull/7939 adds support for modifying the list of API versions for which resources are registered.

**Comment by nikhiljindal** [comment]
The advantage of "legacy" over "preV1beta3" here is that when v1 becomes the default, we can use the same flag to turn off v1beta3.

**Comment by nikhiljindal** [comment]
LGTM

**Pull request merged**
