### PR TITLE
update github.com/Azure/go-autorest/autorest/adal to 0.9.5 and github…

### PR DESCRIPTION
**Pull request by patrickshan**
….com/Azure/go-autorest/autorest to v0.11.12

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
similar to https://github.com/kubernetes/kubernetes/pull/95692 and https://github.com/kubernetes/kubernetes/pull/97033. This is to bump related libraries inside 1.19 branch

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

```release-note
Bump github.com/Azure/go-autorest/autorest/adal to 0.9.5 and github.com/Azure/go-autorest/autorest to v0.11.12
```

### CODE REVIEW

**Comment by liggitt** [comment]
given kubernetes doesn't actually build with the code impacted by the CVE (xref https://github.com/kubernetes/kubernetes/pull/97033#issuecomment-738940122), is this important to backport?

**Comment by patrickshan** [comment]
It's just a cleanup to remove that dependency from Kubernetes repository. Sometimes it's annoying to have some CVE scanning tools alerting on Kubernetes due to those library dependency.

**Comment by liggitt** [comment]
In general, we only bump dependencies in maintenance branches when there is a significant reason to. This seems like a large change to avoid a false positive.

**Comment by patrickshan** [comment]
I see. will close these PRs then.

**Pull request closed without merging**
