### PR TITLE
hack/lib/version.sh: fix error log to stderr

### PR DESCRIPTION
**Pull request by llhuii**
Since this invalid Semantic Version messages redirecting to stdout
will be captured by line 790 at hack/lib/golang.sh:
`goldflags="${GOLDFLAGS=-s -w -buildid=} $(kube::version::ldflags)"`

**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by llhuii** [comment]
Hi, @dims thanks for your time. Can you add lgtm since lgtm label is missed?

**Comment by dims** [comment]
@llhuii yep, had to wait for the CI jobs to go green

/lgtm

**Pull request merged**
