### PR TITLE
[component-based] Use a narrow interface in SetFeatureGateDuringTest

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Use a narrow interface in SetFeatureGateDuringTest.

Since `testing.TB` can only be implemented by internal testing types, change `SetFeatureGateDuringTest` to receive a narrower interface. 
This way other types like `ginkgo.GinkgoTInterface` can be used to call `SetFeatureGateDuringTest`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
This seems backwards compatible.

/lgtm

**Comment by aojea** [comment]
/hold

what David says ^^^

**Comment by trasc** [comment]
> featuregates carry an impact for an entire binary. Sometimes they are re-read, sometimes only on creation. Kube uses gingko tests to run them in parallel from many packages at once against clusters that are already running. Setting featuregates in those contexts is unlikely to lead to success.
> 
> Unit and maybe integration tests seem like the only contexts where these set methods will (mostly) work as expected. Inside of unit tests and integration tests, we do have access to TB.
> 
> Rather than add this method, I would recommend code being written take booleans in its construction and avoid a direct dependency on the gate. This way the unit and integration tests will use different instances and not have side effects outside their given test.

Indeed the most common use-case for featuregates is in some global scope, however in this case `SetFeatureGateDuringTest` gets it's target as a parameter , not using some hard-coded global scope, so the global side effects depend on who writes the code and the intentions .

I personally don't think that keeping this as TB as a valid security measure, since passing `nil` could work as well.

**Pull request closed without merging**
