### PR TITLE
[DO NOT MERGE] WIP: Refactor Image management

### PR DESCRIPTION
**Pull request by vishh**
This is the first step towards simplifying disk management in the kubelet and enable eviction of pods to free up disk space when required.

For #25239

### CODE REVIEW

**Comment by yujuhong** [comment]
Pasting my suggestion from an offline discussion. To make reviewing easier, this can be separated into a few commits.
 - move image_manager.go to a separate package
 - add a PodGetter interface in the runtime and use it
 - git mv a the image puller files into pkg/image (not-compilable)
 - fix the build 
 - ...

**Comment by yifan-gu** [comment]
This is targeted for next release, right?

**Comment by yujuhong** [comment]
> This is targeted for next release, right?

I think @vishh wants to get this in v1.3 if possible(?). @yifan-gu, are there any concerns?

**Comment by vishh** [comment]
Closing this PR since @ronnielai is working on splitting this up into several small ones.

**Pull request closed without merging**
