### PR TITLE
use new method to detect cgroup driver

### PR DESCRIPTION
**Pull request by chenzhiwei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Use new easy method to detect cgroup driver

**Which issue(s) this PR fixes**:

Related to: https://github.com/kubernetes/kubernetes/pull/72831

**Special notes for your reviewer**:

/area kubeadm
sig/cluster-lifecycle

/assign @yagonobre
/assign @neolit123 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@chenzhiwei 
thank you for the PR.

we had a similar PR for this open recently but i had to close it.
please see the explanation here:
https://github.com/kubernetes/kubernetes/pull/76562#pullrequestreview-226406803

/hold

**Comment by chenzhiwei** [comment]
@neolit123 Thank you for reviewing this PR.

Kubernetes bumped the Docker minimal version to v1.13.1 in Kubernetes v1.14, so maybe we need sometime to bump it in kubeadm as kubeadm can deploy lower versions of Kubernetes.

Should I close this PR or leave it as is or bump the kubeadm Docker minimal version for future review?

**Comment by neolit123** [comment]
@chenzhiwei 
> Kubernetes bumped the Docker minimal version to v1.13.1 in Kubernetes v1.14

i may have missed this bump, could you please share the link to the PR?

> Should I close this PR or leave it as is or bump the kubeadm Docker minimal version for future review?

let's leave it open for now, but if we are going to merge it we need to merge another PR before that that updates the minimal version in kubeadm.

**Comment by chenzhiwei** [comment]
@neolit123 It is in the this issue content: https://github.com/kubernetes/kubernetes/pull/72831

**Comment by chenzhiwei** [comment]
I can update this PR to bump the minimal docker version in kubeadm.

**Comment by neolit123** [comment]
> @neolit123 It is in the this issue content: #72831

thanks, now i remembered..

could you please send another PR that updates the version in kubeadm in the validation code and ping me on it? i will review these tomorrow.

**Comment by chenzhiwei** [comment]
@neolit123 Thanks, I will do that.

**Comment by neolit123** [comment]
@chenzhiwei 
the PR to update 1.13 is merging:
https://github.com/kubernetes/kubernetes/pull/77051

please update this PR if needed and we can review it again.

**Comment by chenzhiwei** [comment]
@neolit123 Thanks, I will rebase this PR once the https://github.com/kubernetes/kubernetes/pull/77051 is merged.

**Review by neolit123 — COMMENTED** [review]
/approve
/lgtm
/hold
/test pull-kubernetes-e2e-kind

**Pull request merged**
