### PR TITLE
Add some aliases into import-aliases for e2e framework

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR adds some aliases of e2e sub framework packages for consistent aliases.

**Which issue(s) this PR fixes**:
Ref #87042

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig testing

### CODE REVIEW

**Comment by neolit123** [comment]
i guess this will fail some checks now, unless i'm mistaken.

**Comment by k-toyoda-pi** [comment]
@neolit123 Thank you for seeing this.

**Comment by k-toyoda-pi** [comment]
/assign @bentheelder
for approval, thank you

**Comment by BenTheElder** [comment]
I'm not sure about this pattern tbqh, I think usually you try to avoid having imports that need renaming, but it's pervasive in this repo so...
/approve

**Pull request merged**
