### PR TITLE
add wrapper to provide stderr on command errors

### PR DESCRIPTION
**Pull request by deads2k**
The go standard library doesn't include stderr in the error message, but in many cases it is present: https://golang.org/src/os/exec/exec.go#L389 .  This adds a wrapper to display that information. I've added in it on spot where the kops test is having trouble.  If it works well, we can add it elsewhere. 

@wojtek-t ptal

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37624)

### CODE REVIEW

**Comment by deads2k** [comment]
This is to try to debug 
```
2016/11/29 03:55:26 e2e.go:587: kubectl get nodes failed: exit status 1
```
from the kops tests without any server logs.  If its a dead server (panic'ed perhaps?), we'll get a different answer than if its a permissions problem or something. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/2319

**Comment by dims** [comment]
LGTM 👍

**Comment by deads2k** [comment]
@wojtek-t @dims I think I'm going crazy, but is the kops test *not* using the e2e from the commit its testing?  It's showing
```
W1129 05:23:05.553] 2016/11/29 05:23:05 e2e.go:724: Step 'kops update' finished in 19.856312539s
W1129 05:23:05.668] 2016/11/29 05:23:05 e2e.go:587: kubectl get nodes failed: exit status 1
```

That's old output (not showing what I just changed) and the line number is wrong.  It should be https://github.com/deads2k/kubernetes/blob/8896293cba1cfc8d603781ef3c44ffe43784db72/hack/e2e.go#L753 not https://github.com/deads2k/kubernetes/blob/8896293cba1cfc8d603781ef3c44ffe43784db72/hack/e2e.go#L724

**Comment by dims** [comment]
@deads2k perhaps it's coming from here? https://github.com/kubernetes/kops/blob/master/vendor/k8s.io/kubernetes/test/e2e/e2e.go

**Comment by wojtek-t** [comment]
@deads2k - actually I forgot. The problem is that we are using e2e.go from some docker image. So we need to push a new image for that to take effect. But for now I can't find what image it is - I will try to look for it.

**Comment by deads2k** [comment]
> @deads2k perhaps it's coming from here? https://github.com/kubernetes/kops/blob/master/vendor/k8s.io/kubernetes/test/e2e/e2e.go

A kubernetes merge is blocked by a downstream project which is vendoring kubernetes?  This seems crazy.

**Comment by wojtek-t** [comment]
@fejta @kubernetes/test-infra-maintainers ^^

**Comment by deads2k** [comment]
> A kubernetes merge is blocked by a downstream project which is vendoring kubernetes? This seems crazy.

I mean, put in perspective, OpenShift doesn't try to block Kubernetes merges when they change in ways that aren't machine reconcilable.  It makes more work for those who wish to vendor, but its a tradeoff that you make when you decide to vendor.  The tail doesn't wag the dog.

**Comment by dims** [comment]
@deads2k y, that's why this whole kops-aws gating master is nuts!

**Comment by deads2k** [comment]
@kubernetes/rh-cluster-infra @smarterclayton is this kops (project vendoring kube) gating kube merges something we're expecting?

**Comment by derekwaynecarr** [comment]
@deads2k - I don't believe it blocks unless its marked as "Required" , which it appears to not be at this time.

**Comment by derekwaynecarr** [comment]
@k8s-bot node e2e test this

**Comment by ncdc** [comment]
The GH "Required" text doesn't mean anything. The list of queue-blocking jobs is at http://submit-queue.k8s.io/#/e2e.

**Comment by derekwaynecarr** [comment]
@ncdc - then that is madness.  my memory is failing me.

**Comment by deads2k** [comment]
@k8s-bot verification test this

**Comment by deads2k** [comment]
@k8s-bot verify test this

**Comment by deads2k** [comment]
@k8s-bot test this: issue #IGNORE

**Comment by deads2k** [comment]
a bunch of retest-not-required pulls just merged.  I'm going to kick these test again to make sure it all passes on current master and then tag this debugging pull.

**Comment by zmerlynn** [comment]
@deads2k: As I'm explaining on Slack, it's expected that e2e.go isn't tested in the same PR. This is a bit of a PITA right now and we need to auto-infer this, but you can add a commit that touches `hack/jenkins/.use_head_e2e` and the PR builders will pick up the new version. (Take it out after you've tested.)

**Pull request merged**
