### PR TITLE
kubeadm cleanup: master -> control-plane (cont.3)

### PR DESCRIPTION
**Pull request by vanduc95**
This PR continuation of [#73987](https://github.com/kubernetes/kubernetes/pull/73987)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/assign @neolit123

### CODE REVIEW

**Review by rosti — APPROVED** [review]
Nice work @vanduc95 !

/ok-to-test
/lgtm
/kind cleanup
/priority important-longterm

**Review by neolit123 — APPROVED** [review]
thank you
/approve

**Comment by neolit123** [comment]
@vanduc95 you just need to run `./hack/update-gofmt.sh` locally and commit the changes as part of the same commit.

**Comment by neolit123** [comment]
> @vanduc95 you just need to run `./hack/update-gofmt.sh` locally and commit the changes as part of the same commit.

/lgtm cancel

**Comment by vanduc95** [comment]
Thanks @neolit123, @rosti !
The commit is OK to pass gofmt :)

**Review by neolit123 — APPROVED** [review]
/lgtm

**Pull request merged**
