### PR TITLE
remove validNonResourceVerbs in create role

### PR DESCRIPTION
**Pull request by xilabao**
non-resource-url is only reasonable for clusterroles

### CODE REVIEW

**Comment by pwittrock** [comment]
@xilabao who is familiar with create role?

**Comment by xilabao** [comment]
@deads2k

**Comment by xilabao** [comment]
@liggitt

**Comment by liggitt** [comment]
LGTM, are there any tests around this?

**Comment by xilabao** [comment]
> LGTM, are there any tests around this?

finished.

**Comment by xilabao** [comment]
@pwittrock @liggitt  could we start to test this pr?

**Pull request merged**
