### PR TITLE
Move file cluster/log-dump.sh -> cluster/log-dump/log-dump.sh in release 1.6

### PR DESCRIPTION
**Pull request by shyamjvs**
Equivalent of PR https://github.com/kubernetes/kubernetes/pull/49451 but for 1.6.

DumpClusterLogs step is failing for jobs running against release 1.6 as test-infra expects the file in the new path (i.e. cluster/log-dump/log-dump.sh):
- https://k8s-testgrid.appspot.com/google-gce-scale#gce-1.6

Cherry-picking those commits. I can squash them if you want.

/cc @caesarxuchao

### CODE REVIEW

**Comment by shyamjvs** [comment]
fyi - @fejta

**Comment by shyamjvs** [comment]
Also please let's wait for bug-fix https://github.com/kubernetes/kubernetes/pull/49426 to be merged before this, so we can include that too.

**Comment by wojtek-t** [comment]
I'm not sure we want this PR. If test-infra expects the file in new location, just move it in release branches and avoid making unnecessary changes.

**Comment by shyamjvs** [comment]
@wojtek-t Done. Just moving the file for now (as discussed in https://github.com/kubernetes/kubernetes/pull/49451).

**Pull request merged**
