### PR TITLE
Remove unused func 'applyLimits'

### PR DESCRIPTION
**Pull request by junxu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
Hi @junxu could you explain a bit why you're removing this function?

**Comment by junxu** [comment]
> Hi @junxu could you explain a bit why you're removing this function?

Because this function do nothing, just return nil.

**Comment by matthyx** [comment]
Sure, this code has spent several years untouched... @derekwaynecarr do you remember what was the purpose of this particular func in the overall pod level resource management
https://github.com/kubernetes/kubernetes/issues/27204

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

LGTM, unless @derekwaynecarr has a reason it should still be around. If it does serve a purpose, I'd be interested to see if we can think about a more effective method of achieving that purpose than a func which always returns nil :)

**Comment by derekwaynecarr** [comment]
The function today is a no-op, but its likely/possible we add resource limits that are pod scope bounded only.  Swap is one possible example.  Prefer to keep function as-is today.

**Pull request closed without merging**
