### PR TITLE
kubelet: Add 'image pulling' event. Refactor dockerManager.createPodInfraContainer()

### PR DESCRIPTION
**Pull request by yifan-gu**
Since it takes a while (1-2mins) for kubelet to pulling a big image
(>500MB). Just showing "Pending" for pod status is not very helpful.

This commit introduces a "pulling" event, and inserts it before the
kubelet starts to pull an image.

Before:

``` shell
$ kubectl describe pods dns-frontend
W0608 18:01:31.222834   32037 request.go:291] field selector: v1beta3 - events - involvedObject.name - dns-frontend: need to check if this is versioned correctly.
W0608 18:01:31.222911   32037 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0608 18:01:31.222922   32037 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 102ad4ca-0e43-11e5-a405-28d244b00276: need to check if this is versioned correctly.
Name:               dns-frontend
Image(s):           ddysher/dns-frontend
Host:               127.0.0.1/
Labels:             name=dns-frontend
Status:             Pending
Replication Controllers:    <none>
Containers:
Events:
  FirstSeen             LastSeen            Count   From            SubobjectPath               Reason      Message
  Mon, 08 Jun 2015 18:01:30 -0700   Mon, 08 Jun 2015 18:01:30 -0700 1   {scheduler }                            scheduled   Successfully assigned dns-frontend to 127.0.0.1
  Mon, 08 Jun 2015 18:01:30 -0700   Mon, 08 Jun 2015 18:01:30 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   pulled      Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
  Mon, 08 Jun 2015 18:01:30 -0700   Mon, 08 Jun 2015 18:01:30 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   created     Created with docker id 0d00c8b1e3aca395de644536d994921dea06836e22bb12c4ae72e8937c894189
  Mon, 08 Jun 2015 18:01:31 -0700   Mon, 08 Jun 2015 18:01:31 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   started     Started with docker id 0d00c8b1e3aca395de644536d994921dea06836e22bb12c4ae72e8937c894189
```

After:

``` shell
$ kubectl describe pods dns-frontend
W0623 13:07:06.800598   21221 request.go:291] field selector: v1beta3 - events - involvedObject.name - dns-frontend: need to check if this is versioned correctly.
W0623 13:07:06.800665   21221 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0623 13:07:06.800675   21221 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 15f60526-19e3-11e5-a355-28d244b00276: need to check if this is versioned correctly.
Name:               dns-frontend
Image(s):           ddysher/dns-frontend
Node:               127.0.0.1/127.0.0.1
Labels:             name=dns-frontend
Status:             Running
Replication Controllers:    <none>
Containers:
  dns-frontend:
    Image:      ddysher/dns-frontend
    State:      Running
      Started:      Tue, 23 Jun 2015 13:07:05 -0700
    Ready:      True
    Restart Count:  0
Conditions:
  Type      Status
  Ready     True 
Events:
  FirstSeen             LastSeen            Count   From            SubobjectPath               Reason      Message
  Tue, 23 Jun 2015 13:04:42 -0700   Tue, 23 Jun 2015 13:04:42 -0700 1   {scheduler }                            scheduled   Successfully assigned dns-frontend to 127.0.0.1
  Tue, 23 Jun 2015 13:04:42 -0700   Tue, 23 Jun 2015 13:04:42 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   pulled      Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Tue, 23 Jun 2015 13:04:42 -0700   Tue, 23 Jun 2015 13:04:42 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   created     Created with docker id 1f083693aee2
  Tue, 23 Jun 2015 13:04:42 -0700   Tue, 23 Jun 2015 13:04:42 -0700 1   {kubelet 127.0.0.1} implicitly required container POD   started     Started with docker id 1f083693aee2
  Tue, 23 Jun 2015 13:04:42 -0700   Tue, 23 Jun 2015 13:04:42 -0700 1   {kubelet 127.0.0.1} spec.containers{dns-frontend}       pulling     Pulling image "ddysher/dns-frontend"
  Tue, 23 Jun 2015 13:07:05 -0700   Tue, 23 Jun 2015 13:07:05 -0700 1   {kubelet 127.0.0.1} spec.containers{dns-frontend}       pulled      Successfully pulled image "ddysher/dns-frontend"
  Tue, 23 Jun 2015 13:07:05 -0700   Tue, 23 Jun 2015 13:07:05 -0700 1   {kubelet 127.0.0.1} spec.containers{dns-frontend}       created     Created with docker id 242aafcbb2cf
  Tue, 23 Jun 2015 13:07:05 -0700   Tue, 23 Jun 2015 13:07:05 -0700 1   {kubelet 127.0.0.1} spec.containers{dns-frontend}       started     Started with docker id 242aafcbb2cf
```

Also did some minor cleanup on the way :)
/cc @vmarmol @dchen1107 @yujuhong

### CODE REVIEW

**Comment by yifan-gu** [comment]
Will add some tests

**Comment by yujuhong** [comment]
Thanks for the PR!

Shippable failure: 	`*fakeRuntimeHooks does not implement container.RuntimeHooks (missing ReportImagePulled method)`

Since @vmarmol and I will both be out starting Tuesday, assigning this to @dchen1107 to review or re-assign.

**Comment by yifan-gu** [comment]
@yujuhong Fixed. And added tests

**Comment by yifan-gu** [comment]
@yujuhong @dchen1107 @vmarmol Rebased, and refactored the tests. Want take a look?

**Comment by yujuhong** [comment]
The rest looks good to me.

@k8s-bot, ok to test

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
@yifan-gu, both integration tests (2 builds on shippable) and jenkins e2e failed. Could you take another look at the PR? Thanks!

**Comment by yifan-gu** [comment]
@yujuhong OK

**Comment by yifan-gu** [comment]
@yujuhong Fixed. The reason is I added the image pull policy for the pod infra container spec during creation, but I forgot to do the same when comparing the pod infra container.

As for risk assessment, this touches the pod infra container creation and comparison. But I think the change is mostly cleanup, and very straightforward.

Would like another LGTM for merging :) /cc @vmarmol @dchen1107

**Comment by yujuhong** [comment]
@yifan-gu, the new policy requires LGTMs from two team leads, so aside from @dchen1107, we'll need another one :)

I like the cleanup in this PR, and it makes events sending more consistent for infra/user containers. Whether we should send so many events is up for debate though, but this is probably beyond this PR as there is no standard set in our codebase :\

**Comment by dchen1107** [comment]
@yifan-gu, could you please rebase your pr.

LGTM in general. Thanks!

**Comment by dchen1107** [comment]
Shippable is failing, and one example is:

--- FAIL: TestSyncPodWithPodInfraCreatesContainer (0.01s)
docker_test.go:55: Expected: []string{"inspect_container", "create", "start", "inspect_container"}, Actual: []string{"inspect_container", "inspect_container", "stop", "create", "start", "inspect_container", "create", "start", "inspect_container"}

You need updating the test.

**Comment by yifan-gu** [comment]
@dchen1107 I just updated. it should be fine now :)

**Comment by dchen1107** [comment]
Also following question is that why there are extra operations being introduced by this pr?

**Comment by yifan-gu** [comment]
@dchen1107 No extra operations. The tests failed because the `generatePodInfraContainerHash` is not updated, it didn't take the image pull policy into account when computing the hash, thus the expected hash is not correct, and it cause the pod infra container to be killed incorrectly in the tests.

**Comment by dchen1107** [comment]
@yifan-gu That makes sense. 

LGTM

**Comment by dchen1107** [comment]
As an record: If image pulling failed due to a bad image, this pr will generate more events related to pulling operation. But this won't cause issue of too many events in etcd since event compression will be triggered.

**Pull request merged**
