### PR TITLE
Use unique service name for expose when --name is not specified

### LINKED ISSUE #13178: Clarify documentation about `kubectl expose`
In the document, `expose` should take rc and service as input. I tried `kubectl expose po nginx --port=80 --target-port=8080` and `kubectl expose -f pod-nginx.yaml ...`, they all worked (when pod has labels).

Another thing is, in `expose` command, service name is duplicated from input resource name(when `--name` is not specified), if service with same name already exsits, it will return an error. Can we give the service a unique name as rc does to the pods it manages.

@kubernetes/kubectl @feihujiang

### PR DESCRIPTION
**Pull request by hurf**
Use generate name instead of name.

Partially fixes: #13178

### CODE REVIEW

**Comment by hurf** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Do we want to encourage random names for services?  Part of the point of a service is to have a name that identifies the target pods.  If the user is incentivized to delete the service they expose because they don't like the name, that means we aren't generating the name they need.

I would recommend using the name of the thing they exposed if they don't specify --name, and normalizing (truncating) it to match service reqts.

**Comment by thockin** [comment]
I agree with Clayton - Service is supposed to be less ephemeral than Pod.
I think the current default name is the same as the exposed object, which
seems correct

**Comment by bgrant0607** [comment]
Services should not have random names.

**Comment by hurf** [comment]
@thockin - When exposing a service as another serive,  if name is not specified, like `kubectl expose svc foo`, it always fails because `service foo` already exsits. 
Do you think we should give a different name to the newly created service or just let it report the error? Maybe random names is not a solution for it, but we can do something when the input is a service.

**Comment by smarterclayton** [comment]
I think the user should specify --name in this case.

On Aug 31, 2015, at 10:15 PM, Victor HU <notifications@github.com> wrote:

@thockin <https://github.com/thockin> - When exposing a service as another
serive, if name is not specified, like kubectl expose svc foo, it always
fails because service foo already exsits.
Do you think we should give a different name to the newly created service
or just let it report the error? Maybe random names is not a solution for
it, but we can do something when the input is a service.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/13379#issuecomment-136552985>
.

**Comment by hurf** [comment]
Closing the PR since most people think the existing behaviour is okay.

**Comment by thockin** [comment]
Yeah, I think --name is appropriate.  Thanks for the idea, though.  we do
appreciate it :)

**Pull request closed without merging**
