### PR TITLE
Add containerized option to kubelet binary

### PR DESCRIPTION
**Pull request by pmorie**
@vmarmol Now with stub file

### CODE REVIEW

**Comment by pmorie** [comment]
kicked shippable

**Comment by vmarmol** [comment]
LGTM, did you get a chance to run `hack/build-cross.sh` btw?

**Comment by pmorie** [comment]
@vmarmol I had breakages in that script, even in master.  Is it possible that I did something wrong?

**Comment by vmarmol** [comment]
LGTM, verified it builds. Thanks @pmorie!

**Comment by pmorie** [comment]
:+1:

**Pull request merged**
