### PR TITLE
Add an e2e test that pods get a host IP

### PR DESCRIPTION
**Pull request by ghost**
Targeted test for #6665, so that we can remove the check for host IP from RC e2e tests, as per #6424 .

### CODE REVIEW

**Comment by bprashanth** [comment]
Not sure I'm the best person to do this since I don't know anything of what the initial test was trying to achieve, nor do I have any great experience with the kubelet or nodecontroller. Just leave this under team/node and someone will pick it up?

**Comment by quinton-hoole** [comment]
Oh, and that one line deletion from util.go is unreachable code.  I decided to delete it as I came across it.

**Comment by bprashanth** [comment]
Untrained eye review :)

**Comment by quinton-hoole** [comment]
All sounds good - will fix :-)

**Comment by quinton-hoole** [comment]
OK, I think I've addressed all comments.  PTAL.

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
