### PR TITLE
Compute avg and quantiles of scheduler throughput in density test

### PR DESCRIPTION
**Pull request by shyamjvs**
Based on my comment here - https://github.com/kubernetes/kubernetes/pull/64266#issuecomment-393189953

/sig scheduling
/kind cleanup
/priority important-soon
/milestone v1.11
/cc @wojtek-t 

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
I've explained the rationale here - https://github.com/kubernetes/kubernetes/pull/64266#issuecomment-393210412

**Comment by wojtek-t** [comment]
I still think percentiles would be more consistent with other things we report - see: https://github.com/kubernetes/kubernetes/pull/64266#issuecomment-393294497

**Comment by jberkus** [comment]
Givien that foks are still arguing about this, and Code Freeze is 24 hours away, should we just punt it until after 1.11 release?

**Comment by shyamjvs** [comment]
Josh, I guess we don't really need to worry about this one as this is
purely a test related change.

**Comment by wojtek-t** [comment]
> Givien that foks are still arguing about this, and Code Freeze is 24 hours away, should we just punt it until after 1.11 release?

That's purely test change and it's improvement. I don't think we should be punting that.

**Comment by colemickens** [comment]
@wojtek-t It isn't clear that this change is ready though, given your early comments and the labels on the PR.

Is this critical and ready to go, or should we punt it?

**Comment by shyamjvs** [comment]
It's not ready to go and is not critical. It's also not a release-blocker.
However, it's fine to have this in even in code freeze IMO - as it's just a
test change.

**Comment by jberkus** [comment]
If it's not a blocker, then let's take it out of the milestone.  If you get it working before release, we'll add the milestone back so that we can merge it.

**Comment by shyamjvs** [comment]
Sgtm. Plus I think we shouldn't have this come up in the release meetings :)

**Comment by shyamjvs** [comment]
Putting it back into release milestone as it's an important testing change.

/milestone v1.11

**Pull request merged**
