### PR TITLE
Automated cherry pick of #60625

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #60625 on release-1.9.

#60625: add remount logic for azure file plugin

### CODE REVIEW

**Comment by feiskyer** [comment]
@andyzhangx bazel failed. Have you run update-bazel.sh locally?

**Comment by mbohlool** [comment]
how is this tested?

**Comment by andyzhangx** [comment]
Hi @mbohlool I did the manual test, restart windows node to verify whether pod could access original azure file. Currently there is no e2e test on Windows node, we will add such e2e test in the future.

**Comment by andyzhangx** [comment]
@feiskyer It's a random failure, something wrong with bazel verify tool.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by mbohlool** [comment]
The branch is frozen. holding this for 1.9.5.

/hold

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60677)

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Pull request merged**
