### PR TITLE
Remove deletecollection support from namespace object

### PR DESCRIPTION
**Pull request by liggitt**
Cherry-pick of #46407 onto release-1.6
```release-note
The namespace API object no longer supports the deletecollection operation, which was previously allowed by mistake and did not respect expected namespace lifecycle semantics.
```

### CODE REVIEW

**Comment by enisoc** [comment]
I've edited the release note a bit to clarify why a "feature" is apparently being removed in a patch release. Please make sure it's still accurate.

**Comment by liggitt** [comment]
LGTM

**Pull request merged**
