### PR TITLE
Support list and watch Scale objects of CRD

### PR DESCRIPTION
**Pull request by chenchun**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
To provider a way to list and watch scale objects for all workloads. 
Ref https://github.com/kubernetes/autoscaler/issues/3266

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support list and watch Scale objects
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

Test manually with client-go: https://gist.github.com/chenchun/5ad2d3023d1874a9f51c7bce7c054bc3
Test manually with curl: 

**list scale of a crd**

```
$ curl -k --cert /var/run/kubernetes/client-admin.crt \
  --key  /var/run/kubernetes/client-admin.key \
  --cacert /var/run/kubernetes/server-ca.crt \
"$APISERVER/apis/apps.tkestack.io/v1/namespaces/default/tapps//scale"

{
  "kind": "ScaleList",
  "apiVersion": "autoscaling/v1",
  "metadata": {
    "selfLink": "/apis/apps.tkestack.io/v1/namespaces/default/tapps//scale"
  },
  "items": [
    {
      "kind": "Scale",
      "apiVersion": "autoscaling/v1",
      "metadata": {
        "name": "eapp",
        "namespace": "default",
        "selfLink": "/apis/apps.tkestack.io/v1/namespaces/default/tapps/eapp/scale",
        "uid": "ac45f6e4-9628-4959-98bc-469d7fc531a5",
        "resourceVersion": "401",
        "creationTimestamp": "2020-07-17T14:59:46Z"
      },
      "spec": {
        "replicas": 3
      },
      "status": {
        "replicas": 0
      }
    },
    {
      "kind": "Scale",
      "apiVersion": "autoscaling/v1",
      "metadata": {
        "name": "example-tapp",
        "namespace": "default",
        "selfLink": "/apis/apps.tkestack.io/v1/namespaces/default/tapps/example-tapp/scale",
        "uid": "3a808790-7fcc-4052-ba64-746e4bae44f3",
        "resourceVersion": "346",
        "creationTimestamp": "2020-07-17T14:55:32Z"
      },
      "spec": {
        "replicas": 3
      },
      "status": {
        "replicas": 0
      }
    }
  ]
}
```

**watch all scales of a crd**

```
$ curl -k --cert /var/run/kubernetes/client-admin.crt \
  --key  /var/run/kubernetes/client-admin.key \
  --cacert /var/run/kubernetes/server-ca.crt \
"$APISERVER/apis/apps.tkestack.io/v1/watch/namespaces/default/tapps//scale"
{"type":"ADDED","object":{"kind":"Scale","apiVersion":"autoscaling/v1","metadata":{"name":"example-tapp","namespace":"default","selfLink":"/apis/apps.tkestack.io/v1/namespaces/default/tapps/example-tapp/scale","uid":"3a808790-7fcc-4052-ba64-746e4bae44f3","resourceVersion":"346","creationTimestamp":"2020-07-17T14:55:32Z"},"spec":{"replicas":3},"status":{"replicas":0}}}
{"type":"ADDED","object":{"kind":"Scale","apiVersion":"autoscaling/v1","metadata":{"name":"eapp","namespace":"default","selfLink":"/apis/apps.tkestack.io/v1/namespaces/default/tapps/eapp/scale","uid":"ac45f6e4-9628-4959-98bc-469d7fc531a5","resourceVersion":"401","creationTimestamp":"2020-07-17T14:59:46Z"},"spec":{"replicas":3},"status":{"replicas":0}}}
{"type":"DELETED","object":{"kind":"Scale","apiVersion":"autoscaling/v1","metadata":{"name":"example-tapp","namespace":"default","selfLink":"/apis/apps.tkestack.io/v1/namespaces/default/tapps/example-tapp/scale","uid":"3a808790-7fcc-4052-ba64-746e4bae44f3","resourceVersion":"435","creationTimestamp":"2020-07-17T14:55:32Z"},"spec":{"replicas":3},"status":{"replicas":0}}}
```

**watch a single object of a crd**

```
$ curl -k --cert /var/run/kubernetes/client-admin.crt \
  --key  /var/run/kubernetes/client-admin.key \
  --cacert /var/run/kubernetes/server-ca.crt \
"$APISERVER/apis/apps.tkestack.io/v1/watch/namespaces/default/tapps/example-tapp/scale"
{"type":"ADDED","object":{"kind":"Scale","apiVersion":"autoscaling/v1","metadata":{"name":"example-tapp","namespace":"default","selfLink":"/apis/apps.tkestack.io/v1/namespaces/default/tapps/example-tapp/scale","uid":"6ffe0532-a6fc-4eb8-ac58-9b85a7a20691","resourceVersion":"455","creationTimestamp":"2020-07-17T15:03:57Z"},"spec":{"replicas":3},"status":{"replicas":0}}}
{"type":"DELETED","object":{"kind":"Scale","apiVersion":"autoscaling/v1","metadata":{"name":"example-tapp","namespace":"default","selfLink":"/apis/apps.tkestack.io/v1/namespaces/default/tapps/example-tapp/scale","uid":"6ffe0532-a6fc-4eb8-ac58-9b85a7a20691","resourceVersion":"456","creationTimestamp":"2020-07-17T15:03:57Z"},"spec":{"replicas":3},"status":{"replicas":0}}}
```

### CODE REVIEW

**Comment by roycaihw** [comment]
`GET /apis/apps.tkestack.io/v1/namespaces/default/tapps//scale` This doesn't follow Kubernetes API conventions. The subresource endpoints belong to one resource instance, and do not support LIST operation. This is true for both built-in types and custom resources. 

I'm not sure why vpa-recommender was sending so many `GET scale` requests. Could you explain a little more why this issue is unique for custom resources, and not for built-in types? I imagine you can still use a informer to leverage the local cache without this PR.

**Comment by chenchun** [comment]
> GET /apis/apps.tkestack.io/v1/namespaces/default/tapps//scale This doesn't follow Kubernetes API conventions

Since `scale` is a sub resource, and k8s never supports list and watch sub resource before.
I was also thinking of if listing `scale` objects like `GET /apis/apps.tkestack.io/v1/namespaces/default/tapps/*/scale`?

> why this issue is unique for custom resources, and not for built-in types

Because vpa-recommender lists and watches built-in types via informers, e.g. [controller_fetcher](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go#L100), [vpaTargetSelectorFetcher](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/target/fetcher.go#L124-L141), when it finds a pod is controllered by a built-in workload, it can get the object from informer. FYI, `controller_fetcher` is used to validate a vpa's target is an existing controller object. `vpaTargetSelectorFetcher` is used to get the selector of a vpa's target object to list all pods of this vpa.
But when it comes to a crd instance,  vpa-recommender can't embed every crd client into vpa's code, so it leverages `scale` API to get the selector of crd target.

My use case is that most workloads are crd workloads and I created vpas targeting to them, so that vpa-recommender calls `scale` API to get the selector of them.

> I imagine you can still use a informer to leverage the local cache without this PR.

Are you saying we can vendor crd client to build the local cache? If so, I don't think its good idea to vendoring all crd client into the code.

**Comment by liggitt** [comment]
> I imagine you can still use an informer to leverage the local cache without this PR.

You can't use an informer on an object without knowing how to transform each object into it's scale representation, which clients would not be expected to be able to do for arbitrary custom objects.

> `GET /apis/apps.tkestack.io/v1/namespaces/default/tapps//scale` This doesn't follow Kubernetes API conventions. The subresource endpoints belong to one resource instance, and do not support LIST operation. This is true for both built-in types and custom resources.

That is true, and the change proposed in this PR is not likely to be accepted for that reason.

**Comment by chenchun** [comment]
> You can't use an informer on an object without knowing how to transform each object into its scale representation, which clients would not be expected to be able to do for arbitrary custom objects.

I think I have an idea. I can get the scale subresource definition, i.e. `labelSelectorPath`, `specReplicasPath`, `statusReplicasPath`, of any `CustomResourceDefinition` to know how to transform it. I'll have a try.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tapps.apps.tkestack.io
spec:
  group: apps.tkestack.io
  version: v1
  names:
    kind: TApp
    listKind: TAppList
    plural: tapps
    singular: tapp
  scope: Namespaced
  subresources:
    status: {}
    scale:
      labelSelectorPath: .status.scaleLabelSelector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas

**Pull request closed without merging**
