### PR TITLE
change infof to Errorf in endpoint_helper.go

### PR DESCRIPTION
**Pull request by lojies**
change glog.Infof() to glog.Errorf()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32472)

### CODE REVIEW

**Comment by madhusudancs** [comment]
LGTM!

**Comment by madhusudancs** [comment]
ok to test

**Comment by luxas** [comment]
Thanks @lojies for this patch!
Just a small note, in order to have an optimal PR flow, please try to group your PRs in logical units.
For example, this PR should include the changes in #32470 #32473 #32474 #32475 as well.

Small PRs => easier reviewing yes, but 5 PRs for 5 lines changed takes up 5x Submit Queue and testing load, and up to five more people have to be involved for the same change, which leads to _slower_ reviewing.
Please bear that in mind when contributing in the future, and thanks again for helping!

**Comment by lojies** [comment]
@luxas i'm so sorry about this. i will try to group my PRs in logical units in future.

**Comment by luxas** [comment]
@lojies No worry, but I would be glad if you could squash all the referenced PRs plus #32476 into this PR, it would save some of @madhusudancs's time and the overall Submit Queue process.
Thanks!

**Comment by luxas** [comment]
Thanks @lojies! LGTM
I assume it's still OK for @madhusudancs

**Comment by lojies** [comment]
@luxas sorry again for the additional work.

**Comment by madhusudancs** [comment]
@lojies no worries.

@luxas thanks for shepherding this!

**Pull request merged**
