### PR TITLE
federation: Cleanup cluster scripts of older federation bring up method

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**:
Remove older method of bringing up federation via scripts. Currently `kubefed` is the only supported mechanism and is well established and stable.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by madhusudancs** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by madhusudancs** [comment]
/approve no-issue

(This is 1.8-bound)

**Pull request merged**
