### PR TITLE
remove unused not api functions in the pkg/apis directory

### LINKED ISSUE #111666: We should delete unused functions on internal (unsupported for external users, not staging/...) pkgs.
non-staging is effectively internal and we DO NOT make API guarantees there.  We just can't.

_Originally posted by @thockin in https://github.com/kubernetes/kubernetes/issues/111628#issuecomment-1203117518_

### LINKED ISSUE #115088: Cleanup dead code in the codebase
https://github.com/kubernetes/kubernetes/pull/111654 started here but it got big (shocking!) and the contributor got busy.  There are a lot of potential cleanups in there, though, and I hate wasting work.

I see it as an opportunity for someone to rack up some PRs and net-negative LOCs (the best kind!) - just take over that PR, break it up into a bunch of smaller PRs, and send them our way!

A very eager beaver might automate this, but there's a lot of manually-identified low-hanging fruit, I think.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #115088
Fixes #111666

#### Special notes for your reviewer:
This PR follows the content of #111654, the purpose is to split #111654 into many small PRs, and listen to the suggestions in #115095, this PR only modifies the not api functions in pkg/apis
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
@ash2k this test error looks unrelated to this PR, can you help me retest

**Comment by HirazawaUi** [comment]
@ash2k please retest again, this error is different from the previous error, but still looks unrelated to this PR

**Comment by ash2k** [comment]
You should be able to retest yourself, can't you?

**Comment by HirazawaUi** [comment]
> You should be able to retest yourself, can't you?

sorry, i didn't know that I can retest myself

**Comment by aramase** [comment]
@liggitt @enj PTAL when you get a chance!

**Pull request merged**
