### PR TITLE
Update azure_instances.go

### PR DESCRIPTION
**Pull request by Abhik1998**
**What type of PR is this?**
Kind bug
> Uncomment only one, leave it on its own line:
>
> /kind api-change
     kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This Pull request adds a unit test for NodeExpresses

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #This fixes #71093 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
action required
```

### CODE REVIEW

**Review by nvzard — COMMENTED** [review]
Is that python code inside a golang file?

**Comment by Abhik1998** [comment]
Someone should review out this here.I added up a unit test to NodeExpresses

**Comment by Abhik1998** [comment]
Check it up now I have reviewed the Golang code

**Comment by Abhik1998** [comment]
Someone please review my code

**Comment by karataliu** [comment]
```
./azure_instances.go:128:1: syntax error: non-declaration statement outside function body
./azure_instances.go:130:7: missing function body
./azure_instances.go:131:1: syntax error: unexpected semicolon or newline before {
./azure_instances.go:132:12: missing function body
./azure_instances.go:132:45: syntax error: unexpected ) after top level declaration
```

If you would like to add some unit test, please turn to azure_instances_test.go

**Comment by Abhik1998** [comment]
Ok Sir looking forward to it

**Pull request closed without merging**
