### PR TITLE
#66067: fixes hostport interaction with systemd-resolved

### LINKED ISSUE #66067: DNS is broken in Ubuntu 18.04 due to CNI hostport rules
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In Ubuntu 18.04 DNS queries are being served via `systemd-resolved` daemon which is listening on `127.0.0.53:53` and serves queries only from `127.0.0.1/8`.
The only line in `/etc/resolv.conf` is `nameserver 127.0.0.53`, and this file is managed by systemd.
Once any pod with `hostPort` notation appears on the host, `kubelet` fires the iptables rule in `POSTROUTING` chain of `nat` table:

    -A POSTROUTING -s 127.0.0.0/8 -o lo -m comment --comment "SNAT for localhost access to hostports" -j MASQUERADE

See commit https://github.com/kubernetes/kubernetes/commit/aabdaa984f3cff92421bb87197e1767d51407333
and lines https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/hostport/hostport.go#L137-L138
for details.

Therefore all queries to `127.0.0.53:53` goes not from `127.0.0.0/8`, but from interface with default route due to masquerading, and `systemd-resolved` rejects all of these requests with

    systemd-resolved[21366]: Got packet on unexpected IP range, refusing.

**How to reproduce it (as minimally and precisely as possible)**:

Just install Kubernetes with CNI on Ubuntu-18.04 (with kubeadm, kubespray, chef-kubernetes, whatever) and run any pod with `hostPort`.
Voila! You just lost DNS resolving.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.11.0`
- Cloud provider or hardware configuration: Digital Ocean (but reproduceable on any configuration)
- OS (e.g. from /etc/os-release): `Ubuntu 18.04 LTS`
- Kernel (e.g. `uname -a`): `Linux kube01 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: [chef-kubernetes](https://github.com/evilmartians/chef-kubernetes) (but reproduceable with any install tool)
- Others:
  - CNI: 0.6.0
  - CNI plugins: 0.7.1
  - CNI daemon: weave

/sig network

### PR DESCRIPTION
**Pull request by erhudy**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

systemd-resolved reacts poorly to the global MASQUERADE rule that is inserted for hostport pods. This changeset adds an extra rule that is inserted before the global MASQUERADE rule if systemd-resolved is detected to be running on the host.

**Which issue(s) this PR fixes**:

Fixes #66067

**Special notes for your reviewer**: Best tested on Ubuntu Bionic 18.04.

**Does this PR introduce a user-facing change?**:

```release-note
Fixes hostport networking on Linux systems using systemd-resolved
```

### CODE REVIEW

**Comment by dcbw** [comment]
@squeed @danwinship thoughts on this one?

**Comment by squeed** [comment]
Interesting. I'm pretty bad at mentally executing all of these iptables rules. Can you give an example of a flow that was previously broken and is fixed by this?

**Comment by erhudy** [comment]
@squeed this specifically fixes an issue with systemd-resolved where the global MASQUERADE hostport rule causes packets to systemd-resolved to appear to be coming from somewhere other than localhost, which results in systemd-resolved refusing to answer the request. The rule I'm inserting creates a pinhole for requests to 127.0.0.53 so that they still appear to be coming from localhost, which keeps systemd-resolved happy.

**Comment by danwinship** [comment]
The linked issue mentions the existence of an iptables rule

    -A POSTROUTING -s 127.0.0.0/8 -o lo -m comment --comment "SNAT for localhost access to hostports" -j MASQUERADE

This is obviously messed up. (It effectively says "SNAT all packets going from localhost to localhost".) The `lo` here is the interface that the network plugin claims that the pods are on. Either it is passing the wrong interface, or else it is just configuring the network in a way that `HostPortManager` and `HostportSyncer` are not currently written to be able to support. Assuming the latter, then a fix to the hostport code may be in order, but this is not the correct fix.

**Comment by erhudy** [comment]
@danwinship I know the original rule is weird, but Chesterton's fence. I do not have a problem with changing the solution; I just want to fix the specific problem of nodeport services breaking my hosts running Bionic.

**Comment by danwinship** [comment]
The original rule makes sense if the interface is anything other than `lo`. The hostport code was written to assume that the interface you passed in was going to be a bridge or something like that (eg, `"br0"` in the kubenet case), and the rules it create don't necessarily make sense if it's not.

The fix is probably to just not have any SNAT rule in this case. (You'd have to run the conformance tests in this environment to see if everything still works that way.)

**Comment by erhudy** [comment]
How about I update this PR so that instead of adding the pinhole rule, it will not apply the MASQUERADE rule if the interface in question is `lo`?

**Comment by danwinship** [comment]
@erhudy yes, I *think* that's the right fix, but you're going to need to run the test suite with that fix in your environment to make sure that that change doesn't break anything else. I'm not sure how to do that. (The docs and/or developers for whatever method you're using to install your cluster may have suggestions.)

**Comment by danwinship** [comment]
#80591 should fix this more simply
/close

**Comment by RRAlex** [comment]
Anybody has been able to confirm that this allow them to run on Ubuntu 18.04 without any issue? :)

**Pull request closed without merging**
