### PR TITLE
Skip publishing OpenAPI for nonstructural schemas

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
* Restores compatibility with 1.15 CRDs by not publishing openapi non-structural schemas
* Restores compatibility with 1.14 CRDs by not publishing openapi for structural schemas whose CRDs set `spec.preserveUnknownFields=true`

**Which issue(s) this PR fixes**:
Fixes #82651

**Does this PR introduce a user-facing change?**:
```release-note
Restores compatibility with <=1.15.x custom resources by not publishing OpenAPI for non-structural custom resource definitions
```

/assign @roycaihw @sttts 
/cc @aanm 
/sig api-machinery

### CODE REVIEW

**Review by aanm — APPROVED** [review]
I've test it out kube-apiserver rc.1 with this patch and it works again. Thanks @liggitt ! :speedboat:

**Comment by roycaihw** [comment]
LGTM

**Comment by alexellis** [comment]
@liggitt not sure if you mind the question here vs. another forum. Could this patch be related to a recent regression in the OpenFaaS CRD when taking K8s 1.17.5 and 1.18? https://github.com/openfaas/faas-netes/issues/630#issuecomment-625448013

**Comment by liggitt** [comment]
no, this is not related. what you are seeing might be related to https://github.com/kubernetes/kubernetes/issues/85127#issuecomment-605890538

**Pull request merged**
