### PR TITLE
amend spec.PersistentVolume.Spec 

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
ping @msau42
/assign @jingxu97

**Comment by jingxu97** [comment]
@jianglingxia I think there is one err not defined. Please fix the error and then I will approve it

**Comment by jianglingxia** [comment]
ping @msau42 
/assign @jingxu97
thanks

**Comment by msau42** [comment]
Can you update the title since you're not modifying the err definition anymore.

**Comment by jianglingxia** [comment]
ok,I have updated it,Submitted twice yesterday and the ci always failed，so I submit the error info!

**Comment by jianglingxia** [comment]
/assign @jingxu97
for approved 
thanks

**Comment by jianglingxia** [comment]
/assign @jingxu97
for approved
thanks

**Comment by jianglingxia** [comment]
sorry，trouble to you again @jingxu97
there has three pr need you label 
/approve no-issue  
not approve 
the below to
#49707
#49615
thanks very much

**Comment by jianglingxia** [comment]
sorry,the pr Tests are more than 96 hours old. Re-running tests then always failed so I rebase it,
please review the pr again. @jingxu97 
please label lgtm and /approve no-issue

**Comment by jianglingxia** [comment]
@fejta-bot  why the pr always failed recently?please help me,thanks

**Comment by jianglingxia** [comment]
Previously marked lgtm but by k8s-merge-robot removed,re-needed lgtm @k8s-merge-robot @msau42 
thanks

**Pull request merged**
