### PR TITLE
Update snapshot CRDs to v1

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updates CRDs installed by the cluster to v1.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
Can you also change the snapshot tests to use the v1 object?

**Comment by xing-yang** [comment]
@msau42 I have this PR that updates e2e tests: https://github.com/kubernetes/kubernetes/pull/96089

**Comment by msau42** [comment]
That one also updates images. Can this PR include v1 crd + e2e test using v1 api, but keep the images the same?

**Comment by xing-yang** [comment]
> That one also updates images. Can this PR include v1 crd + e2e test using v1 api, but keep the images the same?

That won't work.  Old controller/sidecar does not know v1 CRDs.

**Comment by msau42** [comment]
That should be fine because we convert the objects to v1beta1

**Comment by xing-yang** [comment]
> That one also updates images. Can this PR include v1 crd + e2e test using v1 api, but keep the images the same?

Updated e2e test using v1 API while keeping images the same.

**Comment by msau42** [comment]
Awesome, this demonstrates that the v1 api works with v1beta controller.

In your other PR #96089, can you revert the test/e2e v1 change to show that v1beta API users can work with the v1 controller?

/lgtm
/hold
for https://github.com/kubernetes-csi/external-snapshotter/pull/419 to merge

**Comment by xing-yang** [comment]
> In your other PR #96089, can you revert the test/e2e v1 change to show that v1beta API users can work with the v1 controller?

I updated PR #96089 to have v1 CRDs and v1 snapshot controller and sidecars while keeping test/e2e using v1beta snapshot.  It has passed CI.

One thing I didn't change is the external-provisioner image.  It is still using the old image.  I tried to use the updated image depending on v1 snapshot, but external-provisioner failed to start due to unknown parameter "-provisioner".  I think it has to do with this deprecated provisioner flag: https://github.com/kubernetes-csi/external-provisioner/blob/v1.6.0/cmd/csi-provisioner/csi-provisioner.go#L66

**Comment by xing-yang** [comment]
In PR https://github.com/kubernetes/kubernetes/pull/96422, we have shown that existing v1beta users will still function with an upgraded controller and driver.

PR https://github.com/kubernetes-csi/external-snapshotter/pull/419 is merged.  Removing the hold.

/hold cancel

**Pull request merged**
