### PR TITLE
Add blank /stats/summary kubelet endpoint

### PR DESCRIPTION
**Pull request by pwittrock**
Add a `/stats/summary` endpoint to the kubelet which will return an
empty Summary{} struct (json formatted), as a summary API
placeholder. Once the next cAdvisor release is vendored, the summary
API will be filled in.

### CODE REVIEW

**Comment by pwittrock** [comment]
I signed it!

**Comment by vishh** [comment]
LGTM

**Comment by pwittrock** [comment]
I think I confused the CLA bot by sending a PR for a commit by @timstclair

**Comment by vishh** [comment]
I guess we can ignore CLA in this case.

**Comment by alex-mohr** [comment]
I think this is a dup of #19725 which I just merged, so closing -- reopen if I got that wrong.

**Pull request closed without merging**
