### PR TITLE
Bump cadvisor to v0.24.0

### LINKED ISSUE #31015: Cut cAdvisor release for Kubernetes 1.4 release.
File this for tracking the progress...

### PR DESCRIPTION
**Pull request by dchen1107**
cc/ @Random-Liu @vishh @timstclair
Fix #31015

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31048)

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM.

**Comment by Random-Liu** [comment]
@dchen1107 Rebase is needed. :(

**Comment by timstclair** [comment]
I think we should consider renaming this tag to `v0.24.0-alpha`. Let's chat before this goes in.

**Comment by dchen1107** [comment]
Talked to @timstclair who is trying to standardize the cadvisor release procedure. He will pick up the work from here. Thanks!

**Comment by Random-Liu** [comment]
SGTM

**Pull request closed without merging**
