### PR TITLE
Improving StopContainer failed log level

### PR DESCRIPTION
**Pull request by 249043822**
Using at least Warning level will be more property

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32259)

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM from the bulk LGTM tool (testing...)

**Comment by 249043822** [comment]
@brendandburns , @yujuhong , why the Jenkins GKE smoke e2e — Error in queue. still in pr #32261

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #32259

**Comment by 249043822** [comment]
@k8s-bot test this issue: #31884

**Comment by 249043822** [comment]
@yujuhong , I have done force-push to make it retest, now it's green, need lgtm, thanks

**Pull request merged**
