### PR TITLE
update cni from 1.4.1 to 1.5.0

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

The  cni-plugin has updated to 1.5.0
https://github.com/containernetworking/plugins/releases/tag/v1.5.0
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Update CNI Plugins to v1.5.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by aojea** [comment]
yes, this is breaking the jobs

```
May 24 11:48:44.479624 e2e-fc7af2d18e-674b9-master configure.sh[21447]: https://www.googleapis.com/auth/devstorage.read_only
May 24 11:48:44.480961 e2e-fc7af2d18e-674b9-master configure.sh[1737]: Getting the service account access token configured for VM.
May 24 11:48:44.546694 e2e-fc7af2d18e-674b9-master configure.sh[1737]: Service account access token is received. Downloading https://storage.googleapis.com/k8s-artifacts-cni/release/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz using this token.
May 24 11:48:44.560055 e2e-fc7af2d18e-674b9-master configure.sh[21454]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 24 11:48:44.562331 e2e-fc7af2d18e-674b9-master configure.sh[21454]:                                  Dload  Upload   Total   Spent    Left  Speed
May 24 11:48:44.731742 e2e-fc7af2d18e-674b9-master configure.sh[21454]: [158B blob data]
May 24 11:48:44.733349 e2e-fc7af2d18e-674b9-master configure.sh[21454]: curl: (22) The requested URL returned error: 404
May 24 11:48:44.738565 e2e-fc7af2d18e-674b9-master configure.sh[1737]: == Failed to download https://storage.googleapis.com/k8s-artifacts-cni/release/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz. Retrying. ==
May 24 11:48:44.741733 e2e-fc7af2d18e-674b9-master configure.sh[1737]: Getting the scope of service account configured for VM.
```

**Comment by saschagrunert** [comment]
I uploaded the artifacts to the bucket.

/retest

**Pull request merged**
