### PR TITLE
Fix some golint failures of test/e2e/framework/service_util.go

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix some golint failures of test/e2e/framework/service_util.go

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority important-soon

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm
/approve
/hold
/retest
/remove-priority important-soon
/priority backlog

**Comment by SataQiu** [comment]
Thanks @neolit123 
Can this PR cancel hold now? :confused:

**Comment by neolit123** [comment]
> Can this PR cancel hold now? confused

yes, it seems fine.

**Pull request merged**
