### PR TITLE
Automated cherry pick of #24531

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #24531 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@zmerlynn @roberthbailey @fabioy please review this cherry-pick

**Comment by andyzheng0831** [comment]
@k8s-bot test this issue: #23321

**Comment by zmerlynn** [comment]
@k8s-bot unit test this, issue #24207.

**Comment by zmerlynn** [comment]
@k8s-bot unit test this, issue #24207. (AGAIN.)

**Pull request merged**
