### PR TITLE
WIP: Testing

### PR DESCRIPTION
**Pull request by xing-yang**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update volume snapshot controller and sidecar images to v6.0.1.

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes-csi/external-snapshotter/issues/736
#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Hi @humblec, this PR is based on https://github.com/kubernetes/kubernetes/pull/110826 except that I removed the timeouts.  It passed the snapshot tests now.  Can you take a look?

**Comment by humblec** [comment]
> Hi @humblec, this PR is based on #110826 except that I removed the timeouts. It passed the snapshot tests now. Can you take a look?

Sure @xing-yang .. one more difference from the referenced PR is the version of the provisioner which is `3.2.1` here instead of `3.2.0` . I have updated my PR to `3.2.1` and checking the tests pass on that.

**Comment by humblec** [comment]
Its interesting that , even after keeping only sidecar version changes, my PR tests fail. now the only difference between this PR and mine is that, this PR has not updated csi-snapshotter version https://github.com/kubernetes/kubernetes/pull/111373/files#diff-1e966d5d795fba59a8ceea256e18d4390e98c4b6fc5adeb135397ab391598174L24 and https://github.com/kubernetes/kubernetes/pull/110826/files#diff-d206a6719a9e122d9b370a436ccb2f1e80b7c257737f104b5f88fc8f7f3830a8L355 . I am wondering if you update these 2 lines for latest version , the tests pass or not @xing-yang

**Comment by humblec** [comment]
@xing-yang so this commit https://github.com/kubernetes/kubernetes/pull/111373/commits/d3b5760424c9d2622b3179ae40689b62f7eed694 make the test to fail as suspected :(

**Comment by xing-yang** [comment]
Closing this testing PR to avoid confusion.

**Comment by sonasingh46** [comment]
Opened a new PR to verify/fix the failure 
https://github.com/kubernetes/kubernetes/pull/112790

**Pull request closed without merging**
