### PR TITLE
[ut] Increase test coverage for kubelet/pleg

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109717

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by bart0sh** [comment]
/assign
@my-git9 please update your code as in your another pr, thanks.

**Comment by pacoxu** [comment]
/cc @harche 
the Evented PLEG feature owner.

```
https://k8s.io/kubernetes/pkg/kubelet/pleg/evented.go%20(16.3%)
```
with this pr, only `getPodIPs` is covered. 16.3% -> 22.4%.

**Review by harche — APPROVED** [review]
/lgtm

**Review by pacoxu — APPROVED** [review]

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
