### PR TITLE
Removes deprecated kubectl openapi column printing

### PR DESCRIPTION
**Pull request by seans3**
* Removes deprecated kubectl openapi column printing; deprecated over four years ago. OpenAPI column printing relies on `x-kubernetes-print-column` field in the swagger to identify what columns to print.
* server-side printing is the approved substitute for openapi column printing.
* By removing openapi code and dependencies, simplifies our effort to move from OpenAPI V2 to OpenAPI V3.

/sig cli
/kind cleanup
/priority important-longterm

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
Looks good to me, leaving it to you Arda to tag it. Thanks, that's really great!

**Comment by ardaguclu** [comment]
this flag was deprecated in 1.12(ref https://github.com/kubernetes/kubernetes/pull/65601) and it is safe to remove it altogether;

/lgtm

**Pull request merged**
