### PR TITLE
Removing old sample JSON; updating references

### PR DESCRIPTION
**Pull request by MikeJeffrey**
There's one more reference - in cmd/integration/integration.go. It uses controller.json to test replication controller creation... where would be a good place to move that file to?

### CODE REVIEW

**Comment by MikeJeffrey** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/5039

**Comment by bgrant0607** [comment]
Thanks, @MikeJeffrey. The right solution is to change code, but I'm not going to ask you to do that. Just move the file to cmd/integration for now.

**Comment by bgrant0607** [comment]
The other changes LGTM

**Comment by bgrant0607** [comment]
@MikeJeffrey Please let me know when you've made the changes.

**Comment by bgrant0607** [comment]
Build still fails. You need to change the integration test's path.

Also, why did you decide not to delete the examples that we don't need?

**Comment by MikeJeffrey** [comment]
I messed up the git workflow. I'll close this PR when I get back to my desk
and start again.

**Pull request closed without merging**
