### PR TITLE
remove DevicePlugins featuregate

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
remove GAed feature gate DevicePlugins
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Review by swatisehgal — APPROVED** [review]
/lgtm

/assign @klueska @mrunalp 
for approval

**Comment by swatisehgal** [comment]
/cc @dims @derekwaynecarr @dchen1107 

for features approval

**Pull request merged**
