### PR TITLE
feat(scheduler): implement node affinity as score plugin

### LINKED ISSUE #83848: [migration phase 1] NodeAffinity as Score plugin
**What would you like to be added**:

Add a Score that calls into NodAffinity priority, should be added to the existing NodeAffinity plugin, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

### PR DESCRIPTION
**Pull request by draveness**
/sig scheduling
/priority important-soon
/kind feature

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/83848

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
Thanks Draven.

/approve
/lgtm
/hold

Holding until tide makes progress, this has the potential to conflict with a PR being merged now.

**Comment by draveness** [comment]
> Holding until tide makes progress, this has the potential to conflict with a PR being merged now.

+1, the tide gets pretty slow now..

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Review by wgliang — APPROVED** [review]
/lgtm

**Pull request merged**
